### ISSUE TITLE
Bun Reformats package.json

### ISSUE THREAD

**Issue by barziahmed** [oven-sh/bun#10007]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Windows 11 64-bit

### What steps can reproduce the bug?

bun install command

### What is the expected behavior?

Hello, I use Prettier to format my files, including `package.json`, and I set things like 4 width tabs and etc. 
Everytime when I try to install or update my packages using `bun install`, it format package.json without I solicit it to do so. +

### What do you see instead?

I want Bun to not formats my package json to default or anything, just leave it as is, 

### Additional information

n/a

**Comment by Electroid** [comment]
Duplicate of #9351
