### ISSUE TITLE
Shell: Running docker with a multi-line command fails

### ISSUE THREAD

**Issue by dimfeld** [oven-sh/bun#10000]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

`Linux 5.15.0-91-generic x86_64 x86_64` and `Darwin 23.3.0 arm64 arm`

### What steps can reproduce the bug?

I'm trying to run a docker command to create a container from Bun shell, and it fails to run if I split the command across multiple lines.

To reproduce, create and run this script :

```js
#!/usr/bin/env bun

import {$} from 'bun';

await $`docker run \
 my-image`;
```

My actual command is much longer than this, but this short one suffices to reproduce the error. It doesn't matter if the image exists or not, this fails before it gets to the point of checking that.

You can use `podman` too if you have that installed instead of docker; both have the same error.

### What is the expected behavior?

The command executes successfully.

### What do you see instead?

```shell
> bun test.js
docker: invalid reference format.
See 'docker run --help'.
1 | #!/usr/bin/env bun
2 |
                   ^
ShellError: Failed with exit code 125
 info: {
  "exitCode": 125,
  "stderr": "docker: invalid reference format.\nSee 'docker run --help'.\n",
  "stdout": ""
}

      at new ShellError (:12:16)
      at new ShellPromise (:64:16)
      at BunShell (:184:35)
      at module code (/home/dimfeld/test.js:2:8)
```

(also the code location is wrong but that's a different problem)

### Additional information

It works fine if I remove the backslash and put everything on a single line, but that's unwieldy for large docker commands.

I also tried removing the backslashes like this:

```
await $`docker run
   my-image`
```

but that appears to just run each line as a separate command like a normal shell would, so it doesn't work either.

**Comment by zackradisic** [comment]
This was fixed with #10122
