### ISSUE TITLE
Why is bun so slow

### ISSUE THREAD

**Issue by TechGunners** [oven-sh/bun#10015]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Don't know 

### What is the expected behavior?

Install in milliseconds
start the SvelteKit application in milliseconds

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/164009551/2c20a6df-03d1-4576-9fa7-1210e14a5793)

It took 65 seconds to install

![Untitled](https://github.com/oven-sh/bun/assets/164009551/d262f2cf-132e-455c-a765-48e4b9d60e50)

It took 11 seconds to start my SvelteKit application

**Comment by m1abdullahh** [comment]
Hi, if it was the first time using `bun install`, it makes sense for it to take time. That's because it won't have any global cache to copy the packages from. On the first time, it will install packages as well as copy them to a cache and use that cache the next time you try to install any of  those packages. Try copying the `package.json` and `bun.lockb ` to another dir. and install there.

**Comment by TechGunners** [comment]
No, it wasn't the first time Installing those pkg's but it was first time Installing some of the newer versions, but it still shouldn't take  that much time but when I deleted the node_modules folder to run **bun i** again, it took around 22 sec, which is still a lot compere to what you guys claim in your website and what about the slow startup time?

**Comment by blk-raffy** [comment]
Same to me on my Win11 pc, 165s to download the first time, 95s the others, npm takes 33s with cache.
On my Mac it's speedy af

**Comment by m1abdullahh** [comment]
> No, it wasn't the first time Installing those pkg's but it was first time Installing some of the newer versions, but it still shouldn't take  that much time but when I deleted the node_modules folder to run **bun i** again, it took around 22 sec, which is still a lot compere to what you guys claim in your website and what about the slow startup time?

Can you please share the package file.

**Comment by TechGunners** [comment]
@m1abdullahh Here's the full [repo link](https://github.com/TechGunnerINC/TechGunner)
and heres the package file
[package.json](https://github.com/oven-sh/bun/files/14895589/package.json)
