### ISSUE TITLE
Bun create work on wsl but not on powershell

### ISSUE THREAD

**Issue by mathysth** [oven-sh/bun#10023]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun create github.com/ae-creator/cosmosjs-core-template  hello

### What is the expected behavior?

It should create a project from the github repository

### What do you see instead?

Project is downloaded from github bun the script crash

### Additional information

![image](https://github.com/oven-sh/bun/assets/38434126/42384f74-63db-4e0a-9d60-dfe4e0e6dbed)

**Comment by gvilums** [comment]
this appears to work correctly when omitting the directory name.

`bun create github.com/ae-creator/cosmosjs-core-template` works.

`bun create github.com/ae-creator/cosmosjs-core-template hello` doesn't.
