### ISSUE TITLE
cannot run next app when upgrade to 0.1.7

### ISSUE THREAD

**Issue by dawnswwwww** [oven-sh/bun#1002]
### Version

0.1.7

### Platform

Darwin C02G86LCMD6R 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

```shell
bun create next ./next-app

cd next-app

bun dev
```

### What do you see instead?

![image](https://user-images.githubusercontent.com/49851272/183248306-5e7fae5e-0a35-474c-95a8-6831c0d188d4.png)

**Comment by Jarred-Sumner** [comment]
Working on a fix

**Comment by xhyrom** [comment]
Already fixed, install canary.
