### ISSUE TITLE
`bun build`: uh-oh: index out of bounds

### ISSUE THREAD

**Issue by malezjaa** [oven-sh/bun#10026]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

When i try to build cli.ts with --minify, bun just crashes

```bash
bun build ./src/cli.ts --minify --target bun

uh-oh: index out of bounds
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.2 (c8d072c2) Windows x64
BuildCommand: tsconfig_paths(2) tsconfig(4)
Elapsed: 327ms | User: 875ms | Sys: 343ms
RSS: 0.73GB | Peak: 0.73GB | Commit: 0.85GB | Faults: 178120
----- bun meta -----

0   00007FF61A62E048
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 47576 panic: index out of bounds
???:?:?: 0x7ff61991a9e6 in ??? (bun.exe)
???:?:?: 0x7ff6196ecf0d in ??? (bun.exe)
???:?:?: 0x7ff6197db2e8 in ??? (bun.exe)
???:?:?: 0x7ff619065b30 in ??? (bun.exe)
???:?:?: 0x7ff6194eec39 in ??? (bun.exe)
???:?:?: 0x7ff9ede1257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff9ee7eaa47 in ??? (ntdll.dll)
```

Without --minify i get this error:
```bash
2 |  * @typedef {import('estree-jsx').Expression} Expression
              ^
warn: Unsupported JSX runtime: "theRuntime`.
"
   at C:\Development\pressrs\node_modules\estree-util-build-jsx\lib\index.js:2:11

126 |           return require("pnpapi"); // eslint-disable-line node/no-missing-require
                       ^
error: Could not resolve: "pnpapi". Maybe you need to "bun install"?
    at C:\Development\pressrs\node_modules\enhanced-resolve\lib\ResolverFactory.js:126:18
```

**Comment by seofernando25** [comment]
Can you provide a minimal example of the `cli.ts` file?

**Comment by malezjaa** [comment]
Sure https://github.com/maripose-js/maripose/blob/main/src/cli.ts

**Comment by seofernando25** [comment]
@malezjaa  might not be the answer you are looking but
taking a look at that project I think the command you are looking for is `bun run build` would it be not?

**Comment by malezjaa** [comment]
No I was trying to build project using `bun build` because it's faster than tsup.

**Comment by seofernando25** [comment]
> No I was trying to build project using `bun build` because it's faster than tsup.

oh my bad, I had just skimmed over it.

**Comment by seofernando25** [comment]
I was able to mostly isolate the error.

It seems its happens with the `@rsbuild/core` pkg which uses `enhanced-resolve`

```ts
import { createRsbuild } from "@rsbuild/core";

const rsbuild = await createRsbuild();
```

Running `bun build ./index.ts --target bun` gives me 

```
126 |           return require("pnpapi"); // eslint-disable-line node/no-missing-require
                       ^
error: Could not resolve: "pnpapi". Maybe you need to "bun install"?
    at /workspaces/workspace/node_modules/enhanced-resolve/lib/ResolverFactory.js:126:18
```

[Minimal reproduction example with v1.1.2](https://codesandbox.io/p/devbox/amazing-david-f49p67?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluprhf0v00072v6fq1kvhuzt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluprhf0u00022v6f4v80alvw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluprhf0u00042v6ftb7klqwp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluprhf0v00062v6f479nkr3r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluprhf0u00022v6f4v80alvw%2522%253A%257B%2522id%2522%253A%2522cluprhf0u00022v6f4v80alvw%2522%252C%2522activeTabId%2522%253A%2522cluprwwws02n42v6fa8xlgx85%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252Fenhanced-resolve%252Flib%252FResolverFactory.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A120%252C%2522startColumn%2522%253A39%252C%2522endLineNumber%2522%253A120%252C%2522endColumn%2522%253A39%257D%255D%252C%2522id%2522%253A%2522cluprwwws02n42v6fa8xlgx85%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cluprhf0v00062v6f479nkr3r%2522%253A%257B%2522id%2522%253A%2522cluprhf0v00062v6f479nkr3r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluprhf0v00052v6fj6u0j0z9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cluprlvb500v22v6f86jbxh96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluprlvb500v22v6f86jbxh96%2522%257D%252C%2522cluprhf0u00042v6ftb7klqwp%2522%253A%257B%2522id%2522%253A%2522cluprhf0u00042v6ftb7klqwp%2522%252C%2522activeTabId%2522%253A%2522cluprtvam02a52v6fibyuk8ki%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluprtvam02a52v6fibyuk8ki%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluprtvby000rdhgm3pdx66qk%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Build%2522%252C%2522id%2522%253A%2522clupru16w02dv2v6fbl8twctl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Only the minify issue might be windows specific,  ~~it seems it has to do with how bun tries to bundle `pnpapi` which doesn't actually exists but its definitelly a bun bug.~~

I'm not a core developer so I wouldn't know how much I could help :sweat_smile:

**Comment by seofernando25** [comment]
## My solution

@malezjaa I was able to build your project by marking `pnpapi` and `/dist/loader.js` as [external](https://bun.sh/docs/bundler#external) (resolved at runtime)

```
$: bun build ./src/cli.ts --minify --target bun --external pnpapi --external "./dist/loader.js" --outdir dist

  cli.js                                         7497.36 KB

  rspack.linux-x64-musl-7622293b5797420a.node    59568.95 KB

  rspack.linux-x64-gnu-aa132764ba0db361.node     60364.54 KB

[231ms] bundle 773 modules
```

 does it builds for you (with and without minify)? I'm on linux so there is a chance we might have different results

**Comment by RiskyMH** [comment]
This looks like its fixed now 🎉
(at least from my tests, and my issue linked above also is fixed at least on canary)

**Comment by cworld1** [comment]
I'm not canary user and use scoop for pm. Looking forward to author's next update, which can include this feat/fix.
