### ISSUE TITLE
TensorFlow.js error: Could not resolve dependencies

### ISSUE THREAD

**Issue by russplusplus** [oven-sh/bun#10027]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Darwin 23.4.0 x86_64 i386

### What steps can reproduce the bug?

1) CLI:
    bun install @tensorflow/tfjs-node
2) index.ts:
    import * as tf from '@tensorflow/tfjs-node'
    await tf.loadGraphModel(modelPath)
4) CLI:
    bun build index.ts

### What is the expected behavior?

Create bundle folder

### What do you see instead?

60 |     "./dist/platforms/*.js",
         ^
warn: wildcard sideEffects are not supported yet, which means this package will be deoptimized
   at /Users/russellkerber/Vibecheq/tfjs-node-bug/node_modules/@tensorflow/tfjs-core/package.json:60:5

43 |     const AWSMock = require('mock-aws-s3');
                                 ^
error: Could not resolve: "mock-aws-s3". Maybe you need to "bun install"?
    at /Users/russellkerber/Vibecheq/tfjs-node-bug/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:29

76 |   const AWS = require('aws-sdk');
                           ^
error: Could not resolve: "aws-sdk". Maybe you need to "bun install"?
    at /Users/russellkerber/Vibecheq/tfjs-node-bug/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:23

112 |   const nock = require('nock');
                             ^
error: Could not resolve: "nock". Maybe you need to "bun install"?
    at /Users/russellkerber/Vibecheq/tfjs-node-bug/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:24

6 | const childProcess = require('child_process');
                                 ^
error: Browser build cannot require() Node.js builtin: "child_process". To use Node.js builtins, set target to 'node' or 'bun'
    at /Users/russellkerber/Vibecheq/tfjs-node-bug/node_modules/detect-libc/lib/detect-libc.js:6:30

### Additional information

This runs fine with "bun index.ts"; it's just bundling with this package that causes the error. I have tried running "bun install" like it suggests, but the same error message results. 

I unfortunately don't have a model endpoint to provide for testing this code. If this is required to address this bug let me know and I'll look for something that can work.

Thanks!

package.json:

{
  "name": "tfjs-node-bug",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "@tensorflow/tfjs-node": "^4.17.0"
  }
}

tsconfig.json:

{
  "compilerOptions": {
    // Enable latest features
    "lib": ["ESNext", "DOM"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    // Bundler mode
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    // Best practices
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,

    // Some stricter flags (disabled by default)
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noPropertyAccessFromIndexSignature": false
  }
}

index.ts: 

import * as tf from '@tensorflow/tfjs-node';
const modelPath = 'file://model/model.json';
const model: tf.GraphModel = await tf.loadGraphModel(modelPath);

**Comment by Electroid** [comment]
Try `bun build --target=node`, since the default target is for browsers.

**Comment by russplusplus** [comment]
> Try `bun build --target=node`, since the default target is for browsers.

Hi Electroid,

Thanks for the response. I tried adding "--target=node" to the build command but it got the same error.
