### ISSUE TITLE
support --conditions in `bun test`

### ISSUE THREAD

**Issue by subtleGradient** [oven-sh/bun#10036]
### What is the problem this feature would solve?

Working on code that requires `--conditions=react-server` to run.
Currently there is no way to use `bun test` to test this code.
Adding support for `--conditions` to `bun test` would allow me to write tests

### What is the feature you are proposing to solve the problem?

add support for `--conditions` to `bun test`

### What alternatives have you considered?

Currently looking into having my test spin up a separate instance of bun (using `--conditions=react-server` in the separate process) and then communicating between the process.
I'm not excited about doing this seemingly unnecessary work

**Comment by subtleGradient** [comment]
related to #8990

**Comment by Jarred-Sumner** [comment]
Fixed by @snoglobe in #13902
