### ISSUE TITLE
error message for dependency typo

### ISSUE THREAD

**Issue by Mouvedia** [oven-sh/bun#1004]
### Version

0.1.7

### Platform

Darwin MacBook-Air-de-?.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

package.json
```
"dependencies": {
  "react-dom/client": "latest"
},
```
instead of
```
"dependencies": {
  "react-dom": "latest"
},
```

`bun i`

### What is the expected behavior?

error message in the console

### What do you see instead?

```
  🔍 react-dom/client [1/1]
GET https://registry.npmjs.org/react-dom/client - 405
```

### Additional information

just `405` is not enough to convey that something went wrong IMHO

**Comment by Jarred-Sumner** [comment]
`react-dom/client` is not a valid npm package

`react-dom` is the npm package

**Comment by Mouvedia** [comment]
Yes, I know that. I was asking for an informative error message instead of just having `405`.
e.g. `invalid package name`
