### ISSUE TITLE
Windows: Bun install & bun Dev (11x - 6x) Slower than WSL

### ISSUE THREAD

**Issue by taymakz** [oven-sh/bun#10042]
### What version of Bun is running?

1.1.2

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun install and bun run dev is so slow on WIndows im testing it on Next js project but same in nuxt 3 too
![image](https://github.com/oven-sh/bun/assets/71381670/f3049e1e-f578-40d1-9ef3-54fb419d600d)
in the image left  terminal is windows, and the right one is on the WSL,

**Comment by sibouras** [comment]
that's comparing windows vs linux, and file operations in Windows are more expensive than in Linux, they will probably optimize windows more but it won't get close, here's a good read: https://github.com/Microsoft/WSL/issues/873#issuecomment-425272829

**Comment by 7f8ddd** [comment]
Windows Defender moment, and https://github.com/oven-sh/bun/pull/10037

**Comment by e3dio** [comment]
As a linux user, I prefer Bun stick with Linux + WSL, Windows is a pain to support, takes time away from more important things, why bother when you have WSL

**Comment by taymakz** [comment]
> As a linux user, I prefer Bun stick with Linux + WSL, Windows is a pain to support, takes time away from more important things, why bother when you have WSL

I'm obsessed, honestly 😂

**Comment by e3dio** [comment]
Are you ok with using WSL or you need native windows support for some reason ?

**Comment by taymakz** [comment]
> Are you ok with using WSL or you need native windows support for some reason ?

Yes, I don't have a problem, but I would be more happy if the speed of both was close to each

**Comment by e3dio** [comment]
If WSL will always be faster than native Windows due to Windows just being slow, and spending endless time supporting a slower native Windows takes valuable time away from more important features, would you prefer Bun stick with WSL or continue support for native Windows ?

**Comment by taymakz** [comment]
> If WSL will always be faster than native Windows due to Windows just being slow, and spending endless time supporting a slower native Windows takes valuable time away from more important features, would you prefer Bun stick with WSL or continue support for native Windows ?

Well, I prefer WSL if it is more than 2x faster

**Comment by cpakken** [comment]
For me, using vscode with wsl and plugins uses a lot more resources ~4gb per project. I normally have multiple vscode projects opened so that's like 8-12gb in total and it will bog down my computer. vscode without wsl runs fine though.

**Comment by Jarred-Sumner** [comment]
Can you give this a try in Bun v1.1.12 and let us know if you're still seeing a large performance difference between WSL and Windows with `bun install`?

**Comment by taymakz** [comment]
> Can you give this a try in Bun v1.1.12 and let us know if you're still seeing a large performance difference between WSL and Windows with `bun install`?

now it takes 5 second

390 packages installed [5.01s]

**Comment by Jarred-Sumner** [comment]
I think a 2x - 3x difference on Linux is close to what it is on macOS. I'm going to close this for now but if you feel like it's too slow let us know and we can reopen.
