### ISSUE TITLE
Type-checking Array passes without warning or error

### ISSUE THREAD

**Issue by mioxyz** [oven-sh/bun#1005]
### Version

0.1.7

### Platform

Linux ****** 5.13.13-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:34:21 UTC 2021 x86_64 GNU/Linux

### What steps will reproduce the bug?

The following code executes without warning or error when using `bun`:
```
function printStrings(...args:[string, string]) {
    console.log(args);
}
printStrings("a", "b", "c");
```
but fails during compilation with `tsc` with the following (correct) error message:
```
test.ts:11:24 - error TS2554: Expected 2 arguments, but got 3.

11 printStrings("a", "b", "c");
                          ~~~
Found 1 error in test.ts:11
```

### How often does it reproduce? Is there a required condition?

deterministic, is always reproducible.

### What is the expected behavior?

bun should fail before execution with a similar error message to tsc: "Expected 2 arguments, but got 3."

### What do you see instead?

code executes, printing »[ "a", "b", "c" ]«.

**Comment by Jarred-Sumner** [comment]
Bun does not currently support typechecking. It transpiles TSX similarly to `esbuild`, `swc`, and `babel`
