### ISSUE TITLE
`bunx bun@1.1.2` throws "could not determine executable to run for package exec" on Windows

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#10068]
![image](https://github.com/oven-sh/bun/assets/709451/3101b300-a3b5-42de-b690-3b3e14b2cd7d)
![image](https://github.com/oven-sh/bun/assets/709451/a7ad3099-a914-449b-8948-322a16ebfd60)

**Comment by kaminskypavel** [comment]
similar thing happens on 1.1.3

```shell
~/Desktop/trigger.dev-v3
$ bunx trigger.dev@beta dev
  ⚙️  esbuild [1/1] error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

**Comment by qbenben** [comment]
```sh
❯ bunx ajv-cli -s "${WORK_DIR}/.vscode/link.schema.json" -d "${WORK_DIR}/data/link.yml"
error: could not determine executable to run for package ajv-cli
```

**Comment by maietta** [comment]
Out of the blue, I am getting exact same error in both NPX and Bun. Fresh directory, multiple system reboots, reinstalling NodeJS, Bun, etc.

Even tried different terminals. Nothing.

If anyone has resolved this error, PLEASE explain what was done. This post is 3 weeks old, so either they haven't been able to work since, or they resolved it.

**Comment by dalessandro07** [comment]
<img width="681" alt="probe" src="https://github.com/oven-sh/bun/assets/89921531/ad1c6c94-84a1-48b0-af33-c0c2996f8912">

I don't know if this will be exactly the solution, but I'm sharing it anyway.

**I have bun version 1.1.17.**

Didn't work `> bunx create-next-app`

I got the same error: "could not determine the executable to run for the create-next-app package".

I went to the .bun cache folder in "C:/Users/[user]/.bun/install/cache".

And I got the surprise that there are 2 create-next-app folders, they are installing fine, but the folder that doesn't contain the version is just a symlink to the other folder that bun can't find to run.

**I tried: `> bunx create-next-app@14.2.4@@@1` as it is in the cache folder and it worked for me.**

**Comment by Zhengqbbb** [comment]
> Out of the blue, I am getting exact same error in both NPX and Bun. Fresh directory, multiple system reboots, reinstalling NodeJS, Bun, etc.
> 
> Even tried different terminals. Nothing.
> 
> If anyone has resolved this error, PLEASE explain what was done. This post is 3 weeks old, so either they haven't been able to work since, or they resolved it.

Reinstallation include remove the global cache file, such as, `npm prefix -g` -> `~/.npm` , `~/.bun`
I remove them and reinstall it to return to normal.
