### ISSUE TITLE
`node:fs` `readdir` doesn't work recursively

### ISSUE THREAD

**Issue by oriongonza** [oven-sh/bun#10063]
### What version of Bun is running?

1.0.13

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

> `require("node:fs").readdirSync("src", {recursive:true})`

### What do you see instead?

Only the shallow path

### Additional information

cc: https://github.com/oven-sh/bun/pull/7296

**Comment by Jarred-Sumner** [comment]
Please upgrade to [Bun v1.0.15](https://bun.sh/blog/bun-v1.0.15) or later.

The current version if Bun v1.1.2.

<img width="1514" alt="image" src="https://github.com/oven-sh/bun/assets/709451/b5edd299-e2b5-4551-aae6-ae6cff89d9dd">
