### ISSUE TITLE
Blob.type is not working

### ISSUE THREAD

**Issue by juliomuhlbauer** [oven-sh/bun#10072]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Linux 5.13.0-1022-aws x86_64 x86_64

### What steps can reproduce the bug?

1. Fetch a url
2. Get the blob
3. Try to get the blob.type

```ts
const blob = await fetch("https://bun.sh/logo.svg").then((res) => res.blob());

console.log("Blob type is: ",blob.type)
  ```

### What is the expected behavior?

Blob.type appearing on the console

### What do you see instead?

Nothing

### Additional information

Playground: https://codedamn.com/playground/J2cXvOIyG72SDI_lM3Zkp

**Comment by Electroid** [comment]
It looks like there's some sort of race condition going on.

```sh
bun --print 'for (let i = 0; i < 10_000; i++) await fetch("https://bun.sh/logo.svg").then((res) => res.blob()).then(blob => console.log(blob.type))'
```

You'll occasionally see the `blob.type` is undefined.

**Comment by juliomuhlbauer** [comment]
This type of bug makes bun unreliable to me. Sad

**Comment by Jarred-Sumner** [comment]
Confirmed this is still reproducing as of Bun v1.1.13:

```js
~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml

~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml

~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml

~/Desktop
❯ bun hm.js
Blob type is:

~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml

~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml

~/Desktop
❯ bun hm.js
Blob type is:  image/svg+xml
```
