### ISSUE TITLE
Support `-u` alias in `bun test`

### ISSUE THREAD

**Issue by silverwind** [oven-sh/bun#10073]
### What is the problem this feature would solve?

The CLI flag to update snapshots is inconsistent with `jest` and `vitest`.

### What is the feature you are proposing to solve the problem?

Add `-u` as an alias for `--update-snapshots` in `bun test`.

- jest supports `-u` and `--updateSnapshot`
- vitest supports `-u` and `--update`
- bun only supports `--update-snapshots`

**Comment by Electroid** [comment]
This makes sense, we can support this and it should be a trivial change.
