### ISSUE TITLE
`prompts` (and general stdout) issues

### ISSUE THREAD

**Issue by kaleidawave** [oven-sh/bun#10087]
### What version of Bun is running?

1.1.2

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Given the following using the [prompts](https://www.npmjs.com/package/prompts) library
```js
import prompts from "prompts";

{
  const out = await prompts({ type: "text", message: "Input 1", name: "input" });
  console.log(out)
}
{
  const out = await prompts({ type: "text", message: "Input 2", name: "input" });
  console.log(out)
}
```

### What is the expected behavior?

Text to show/echo as typing in the first input

### What do you see instead?

No text is echoed (although it is registered as the first `console.log(out)` shows a result). After the first input is run, the second one **does** echo?

### Additional information

I see similar behaviour for the `bun repl` where this keys pressed for the first input line don't echo but after that it works.

Also the program doesn't exist once the inputs have ran?

**Comment by asasinmode** [comment]
Having the same issue as described in https://github.com/oven-sh/bun/issues/10029, prompt with type `select` not responding to input. If I run the same code with node it works, hope it gets fixed, here's a quick snippet

```js
import prompts from "prompts";

const { test } = await prompts({
  type: 'select',
  name: 'test',
  message: `tmp`,
  choices: [
    {
      title: `option1`,
      value: 1,
    },
    {
      title: `option2`,
      value: 2,
    },
    {
      title: `option3`,
      value: 3,
    },
  ]
})

console.log('value', test);
```

If I press `enter` it seems to register and prompt is finished, value is logged. If I do `ctrl+c` or `ctrl+d` nothing happens, however if I do `ctrl+c` then `enter` then prompt it finished and `undefined` is logged as a value, as if I escaped except the program was still running

**Comment by paperdave** [comment]
I can reproduce this on 1.1.2 but not on the latest version. I'm not sure exactly when this was fixed, but it seems to be.
