### ISSUE TITLE
console.log() handles latin1 supplement characters incorrectly 

### ISSUE THREAD

**Issue by gourmetseasoningsake** [oven-sh/bun#1008]
### Version

0.1.5

### Platform

Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

console.log(JSON.parse('["ü", "à", "ô"]'))

### What is the expected behavior?

["ü", "à", "ô"]

### What do you see instead?

[ "�", "�", "�" ]

### Additional information

After a few more samples, it seems to be only Latin-1 Supplement chars.

**Comment by Jarred-Sumner** [comment]
Give it a try in bun v0.1.7. This might already be fixed

**Comment by xhyrom** [comment]
It if doesn't works on v0.1.7, reopen issue. Thanks

**Comment by gourmetseasoningsake** [comment]
Thanks for the quick feedback.
I have no problems with `console.log` but with `JSON.parse` in 0.1.5 and 0.1.7, even without console.log: For example when I write parsed data containing umlauts to a db, I see replacement chars there.

New issue: #1031 (cannot reopen this one)
