### ISSUE TITLE
InvalidURL - Installing a library, works on npm/node

### ISSUE THREAD

**Issue by thejasonxie** [oven-sh/bun#10094]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Not sure. this is a private package. works on node/npm though.

![bun-bug](https://github.com/oven-sh/bun/assets/34463193/87dd3c10-2693-4d40-a4a1-e0cc155d0800)

**Comment by Electroid** [comment]
Is it possible to share the `package.json`? If there are IP addresses, feel free to change them to localhost.

**Comment by thejasonxie** [comment]
> Is it possible to share the `package.json`? If there are IP addresses, feel free to change them to localhost.

```js
{
  "name": "client",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "bunx --bun vite",
    "build": "bunx --bun vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^6.1.6",
    "@elysiajs/eden": "^1.0.11",
    "@radix-ui/react-avatar": "^1.0.4",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-progress": "^1.0.3",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toggle": "^1.0.3",
    "@radix-ui/react-toggle-group": "^1.0.4",
    "@radix-ui/react-tooltip": "^1.0.7",
    "@tanstack/react-router": "^1.26.4",
    "@##### private library #####": "^1.2.357",
    "aws-amplify": "^6.0.27",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "lucide-react": "^0.365.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwind-merge": "^2.2.2",
    "tailwindcss-animate": "^1.0.7",
    "vaul": "^0.9.0"
  },
  "devDependencies": {
    "@tanstack/router-devtools": "^1.26.3",
    "@tanstack/router-vite-plugin": "^1.25.0",
    "@types/node": "^20.11.28",
    "@types/react": "^18.2.64",
    "@types/react-dom": "^18.2.21",
    "@typescript-eslint/eslint-plugin": "^7.1.1",
    "@typescript-eslint/parser": "^7.1.1",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "autoprefixer": "^10.4.18",
    "elysia": "latest",
    "eslint": "^8.57.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "postcss": "^8.4.36",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.2.2",
    "vite": "^5.1.6"
  }
}

```

**Comment by thejasonxie** [comment]
my bunfig.toml

```toml
# bunfig.toml - reads GITHUB_TOKEN from .env
[install.scopes]
"#### @private org ### = { token = "$GITHUB_TOKEN", url = "https://npm.pkg.github.com" }
```

**Comment by thejasonxie** [comment]
it worked for prior versions, just 1.2.357 had this issue now but nothings really different from prior versions

**Comment by aiell0** [comment]
Also just started having this issue as of the latest version.

**Comment by thejasonxie** [comment]
Yeah i uninstalled bun and installed v1.0.0 to try, and got [ConnectionRefused](https://github.com/oven-sh/bun/issues/5548) which was [resolved](https://github.com/oven-sh/bun/pull/6206). so I uninstalled bun again and installed the latest 1.1.3+2615dc742. And now I cannot install any version of my private packages lol. I get "error: Expected tarball URL to start with https:// or http://, got "/download/......"

**Comment by aiell0** [comment]
I actually pinned Bun to version `1.1.0` which was the last version I had working a few hours ago and it's still giving me the same error....not sure where to go from here.

**Comment by thejasonxie** [comment]
> I actually pinned Bun to version `1.1.0` which was the last version I had working a few hours ago and it's still giving me the same error....not sure where to go from here.

As much as i don't want to, I switched to npm for now which works. It seems pnpm is also having this issue. This is what i got with pnpm
```
pnpm [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:640:5)
    at getAuthHeaderByURI (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:111180:25)
    at Object.download (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:83251:38)
    at fetchFromTarball (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:104780:18)
    at fetcher (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:123623:22)
    at ctx.requestsQueue.add.priority.priority (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:123559:78)
    at run (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:123082:90)
    at PQueue._tryToStartAnother (/Users/jasonxie/Library/pnpm/global/5/.pnpm/pnpm@8.15.1/node_modules/pnpm/dist/pnpm.cjs:123030:13)
Progress: resolved 1814, reused 1768, downloaded 0, added 2
```

**Comment by aiell0** [comment]
@thejasonxie perhaps it's github's private package management system then? I am also using github's npm.

**Comment by thejasonxie** [comment]
> @thejasonxie perhaps it's github's private package management system then? I am also using github's npm.

That's a good point. Maybe. Try installing your dependencies with npm. You can still use "bun dev" after installing to run your app i think

**Comment by thejasonxie** [comment]
Goddammit lol, now for some reason npm does not work now! Now I think there's definitely something going on with Github's Packages like @aiell0 mentioned....

**Comment by thejasonxie** [comment]
You were right @aiell0. Seems we're not the only ones 
https://github.com/orgs/community/discussions/118352

**Comment by Jarred-Sumner** [comment]
It sounds like GitHub's API is returning relative URLs when it should be returning absolute URLs.

**Comment by aiell0** [comment]
Looks like it's been resolved: https://github.com/orgs/community/discussions/118352

We should close this as it wasn't really a bun issue.
