### ISSUE TITLE
Not able to start CycleTLS instance

### ISSUE THREAD

**Issue by vikasg603** [oven-sh/bun#10115]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Install https://www.npmjs.com/package/cycletls npm package
and run the code
`import initCycleTLS from "cycletls";
const cycleTLS = await initCycleTLS();`

When running getting an error
error: Could not connect to the CycleTLS instance within 4000ms

### What is the expected behavior?

It should start the cycletls instance.

### What do you see instead?

error: Could not connect to the CycleTLS instance within 4000ms

### Additional information

https://github.com/Danny-Dasilva/CycleTLS official cycletls repo

**Comment by maxrandrade** [comment]
I'm facing the same problem.

**Comment by vikasg603** [comment]
Can confirm this works with latest version.
