### ISSUE TITLE
Illegal hardware instruction notices after updating to 0.1.17

### ISSUE THREAD

**Issue by simonholm** [oven-sh/bun#1011]
### Version

0.1.7

### Platform

Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

![image](https://user-images.githubusercontent.com/1653494/183275827-c32c24e1-5647-45e3-94fc-044728a37510.png)

### How often does it reproduce? Is there a required condition?

invariable

### What is the expected behavior?

run examples as expected

### What do you see instead?

[1]    870 illegal hardware instruction  bun create blank ./blank-app

**Comment by xhyrom** [comment]
~~Try to install canary build, known issue - https://github.com/oven-sh/bun/discussions/999#discussioncomment-3341340~~

Not working too ^

**Comment by xhyrom** [comment]
From discussion:
https://github.com/oven-sh/bun/discussions/999#discussioncomment-3348506

After the current GitHub actions run completes, there's a good chance canary will be fixed

^ I think it works

**Comment by xhyrom** [comment]
Fixed by latest canary build, https://github.com/oven-sh/bun/releases/tag/canary
