### ISSUE TITLE
Bun does not read the .env file correctly

### ISSUE THREAD

**Issue by SoulHarsh007** [oven-sh/bun#10118]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Linux 6.8.4-1-cachyos-bore x86_64 unknown

### What steps can reproduce the bug?

If the `.env` file's content includes `$` in a variable's value, bun does not seem to read it correctly, it ignores some content from it.

For reference:
![image](https://github.com/oven-sh/bun/assets/57407752/eea0134a-d558-43a9-8c25-9a9f6997cf70)

You will notice that bun ignores the content in the env variable value after it encounters the `$` symbol.

The same `.env` file works fine with `dotenv`, `tsx --env-file` and `node --env-file`

### What is the expected behavior?

The `.env` variable should get loaded without stripping characters after `$` symbol is encountered.

### What do you see instead?

The env variable is loaded, but content after `$` is stripped away

### Additional information

What I find weird is that if I use `$HOME` instead of `$random_gibberish` it evaluates the `$HOME` variable. Which does not happen with other implementations like `dotenv`, `tsx --env-file` and `node --env-file`.

For reference see:
![image](https://github.com/oven-sh/bun/assets/57407752/6a04e02e-7afc-4916-9bb7-bba3a6233039)

**Comment by Electroid** [comment]
Bun resolves environment variables in the `.env` file for convenience. You can escape the `$` with `\$`.

**Comment by SoulHarsh007** [comment]
I see, so this is not a bug?

**Comment by SoulHarsh007** [comment]
Sorry for the inconvenience.
