### ISSUE TITLE
Some monorepos do not work on Windows

### ISSUE THREAD

**Issue by supern64** [oven-sh/bun#10125]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64

### What steps can reproduce the bug?

Importing Prisma from a monorepo doesn't work on Windows. It works on linux without any errors.
Minimal repro: https://github.com/supern64/prisma-monorepo-minimal-repro
1. bun install
2. bun run init
3. bun start

### What is the expected behavior?

Every time you run `bun start`, the application says `There are x users in the database`, where x is an increasing number. This is how it runs on a Linux host (Linux 5.4.0-105-generic x86_64 x86_64):
```
[user]@[host]:~/prisma-monorepo-minimal-repro$ bun start
$ bun packages/server/main.ts
There are 1 users in the database.
[user]@[host]:~/prisma-monorepo-minimal-repro$ bun start
$ bun packages/server/main.ts
There are 2 users in the database.
[user]@[host]:~/prisma-monorepo-minimal-repro$ bun start
$ bun packages/server/main.ts
There are 3 users in the database.
```

### What do you see instead?

```
$ bun packages/server/main.ts
error: Unexpected reading "[project root]\node_modules\database"
error: script "start" exited with code 1
```

**Comment by supern64** [comment]
Actually, it seems like monorepos just don't work on Windows in general.

**Comment by scffs** [comment]
> Actually, it seems like monorepos just don't work on Windows in general.

It's not actually 

[example](https://github.com/Diary-SPO/core) of monorepo powered by bun (also works on windows fine)

**Comment by supern64** [comment]
> > Actually, it seems like monorepos just don't work on Windows in general.
> 
> It's not actually 
> 
> [example](https://github.com/Diary-SPO/core) of monorepo powered by bun (also works on windows fine)

does it import anything from another package in the same workspace?

**Comment by scffs** [comment]
> > > Actually, it seems like monorepos just don't work on Windows in general.
> > 
> > 
> > It's not actually
> > [example](https://github.com/Diary-SPO/core) of monorepo powered by bun (also works on windows fine)
> 
> does it import anything from another package in the same workspace?

yes

see

file 1 https://github.com/Diary-SPO/core/blob/main/apps/web/package.json#L28

file 2 https://github.com/Diary-SPO/core/blob/main/apps/api/package.json#L30

(the `shared` package is actually using in web and api)

**Comment by alex-demchenko** [comment]
reproduced in the v1.1.7

**Comment by supern64** [comment]
Well, in my project, in some cases it works and in some cases it doesn't, though my minimal repro is still valid so I'll leave this open

**Comment by Jarred-Sumner** [comment]
Fixed by @paperdave in https://github.com/oven-sh/bun/pull/11157
