### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by ImAhmadAbdullah** [oven-sh/bun#10127]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

It's completely random.

### What is the expected behavior?

For the code to run without errors.

### What do you see instead?

This appears:

Segmentation fault at address 0xffffffffffffffff
???:?:?: 0x7ff7e2fe27a7 in ??? (bun.exe)
???:?:?: 0x7ff7e2d285e6 in ??? (bun.exe)
???:?:?: 0x7ff7e14d827d in ??? (bun.exe)
???:?:?: 0x7ff7e14cb46b in ??? (bun.exe)
???:?:?: 0x7ff7e14caebf in ??? (bun.exe)
???:?:?: 0x7ff7e08500e1 in ??? (bun.exe)
???:?:?: 0x7ff7e2ccbb7a in ??? (bun.exe)
???:?:?: 0x7ff7e07c89f6 in ??? (bun.exe)
???:?:?: 0x7ff7e07db72a in ??? (bun.exe)
???:?:?: 0x7ff7e07e04db in ??? (bun.exe)
???:?:?: 0x7ff7e05115fe in ??? (bun.exe)
???:?:?: 0x7ff7e3097203 in ??? (bun.exe)
???:?:?: 0x7ffc2214257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffc231eaa47 in ??? (ntdll.dll)

**Comment by Jarred-Sumner** [comment]
Sorry this is happening. Please include code that reproduces the issue, along with more information about your computer (what CPU)

Happy to re-open once that's provided

**Comment by ImAhmadAbdullah** [comment]
I said it's random since it randomly happens on any bun command. And not on certain codes.
https://github.com/oven-sh/bun/issues?q=segmentation (you can see many more of these)

**Comment by ImAhmadAbdullah** [comment]
@Jarred-Sumner I think the cause of the error is how bun stores its data in memory.
