### ISSUE TITLE
pnpm bun run xxx.ts only works at root dir

### ISSUE THREAD

**Issue by recallwei** [oven-sh/bun#10132]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

My repository root dir is `/interview`, and I run this command at `/interview/quiz`, the target file is `/interview/quiz/lazyman.ts`, but cannot find the script.
![image](https://github.com/oven-sh/bun/assets/62941121/38a99fab-a755-43d4-a0ac-adba1e2d7c6c)

### What is the expected behavior?

`cd` to inner dir, and I want to `pnpm bun run **.ts` anywhere.

**Comment by Jarred-Sumner** [comment]
i think i know why

**Comment by Jarred-Sumner** [comment]
but need to test it first

**Comment by Jarred-Sumner** [comment]
Turns out, this is a pnpm bug. You should file an issue there. You can also try running `bun run xxx.ts`
<img width="334" alt="image" src="https://github.com/oven-sh/bun/assets/709451/7dcf8ae3-ac28-4e09-a63d-b79576d12192">
