### ISSUE TITLE
Flag "-o" in "bun add" is documented but not usable.

### ISSUE THREAD

**Issue by A-D-E-A** [oven-sh/bun#10145]
### What is the type of issue?

Documentation is incorrect, Example code is not working

### What is the issue?

When running `bun add -h`, the examples show the following lines:

```
  Add a dev, optional, or peer dependency 
  bun add -d typescript
  bun add -o lodash
  bun add --peer esbuild
```

But running `bun add -o <anypackage>` reports the error "error: Invalid Argument '-o'".

### Where did you find it?

It is documented in `bun add -h`.

**Comment by ghost** [comment]
Should the example instead show `--optional`, or should there be support for `-o`?
