### ISSUE TITLE
`export default Bun.serve()` tries to start the server twice.

### ISSUE THREAD

**Issue by shiguxx0** [oven-sh/bun#10151]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 6.1.0-18-amd64 x86_64 unknown

### What steps can reproduce the bug?

Save this code snippet into a file and run it with Bun.

```ts
export default Bun.serve({ fetch: () => new Response("Hi!") });
```

### What is the expected behavior?

The server is exported.

### What do you see instead?

```
EADDRINUSE: Failed to start server. Is port 3000 in use?
 syscall: "listen"

      at bun:main:11:4
```

**Comment by gvilums** [comment]
Seems to work as of 1.1.7, if the issue persists feel free to reopen

**Comment by kejedi** [comment]
please re-open this, its still doing this

i have the simplest server and its logging twice on every request:

```ts
const server = Bun.serve({
  port: 3000,
  fetch(req) {
    console.log("hello");

    return new Response("Bun!");
  },
});

console.log(`Listening on http://localhost:${server.port} ...`);
```

so what this means bun is going to run my logic twice on every request???

unusable

**Comment by taciturnaxolotl** [comment]
this is happening again as of bun `1.2.13`
