### ISSUE TITLE
Transpiler incorrectly unescapes template literal strings in some cases

### ISSUE THREAD

**Issue by zhuzilin** [oven-sh/bun#1015]
### Version

v0.1.7

### What steps will reproduce the bug?

```javascript
console.log(String.raw`\?`)
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

```
\?
```

### What do you see instead?

```
?
```

### Additional information

relates to #622

**Comment by Jarred-Sumner** [comment]
This is a transpiler bug

The template string is being un-escaped since `\?` normally is the same is `?`

**Comment by birkskyum** [comment]
This is giving the expected output now:

```sh
➜ bun --bun index.ts
\?
```
