### ISSUE TITLE
Buffer#toString("binary") regressed

### ISSUE THREAD

**Issue by SheetJSDev** [oven-sh/bun#1016]
[The SheetJS bun test suite started failing](https://github.com/SheetJS/sheetjs/actions/workflows/bun.yml) due to a regression in `Buffer#toString("binary")`:

```js
var x = Buffer.from("<?xm", "binary");
console.log(x);
console.log(x.toString("binary"))
```

Node:
```
<Buffer 3c 3f 78 6d>
<?xm
```

Bun 0.1.7:
```
Uint8Array(4) [ 60, 63, 120, 109 ]
㼼浸
```

The output matches the `utf16le` encoding in NodeJS.

The last successful test run was 7 days ago, which could have been 0.1.5 or 0.1.6

**Comment by Jarred-Sumner** [comment]
thanks for flagging
