### ISSUE TITLE
Missing double quotes while parsing String via scripts

### ISSUE THREAD

**Issue by smol-ninja** [oven-sh/bun#10164]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

1. Add a script in `package.json` such as 
```js
"test": "forge test",
```

2. Run the following:
```shell
$ bun run test --match-path "test/integration/**/**/*.sol"
forge test --match-path test/integration/**/**/*.sol
error: unexpected argument 'test/integration/batch/create-with-durations-ll/createWithDurationsLL.t.sol' found

Usage: forge test [OPTIONS]

For more information, try '--help'.
```

It is missing double-quotes ("") around `test/integration/**/**/*.sol` during the resolution of the script command.

### What is the expected behavior?

It should parse double quotes ("")

```shell
$ bun run test --match-path "test/integration/**/**/*.sol"
forge test --match-path "test/integration/**/**/*.sol"
error: unexpected argument 'test/integration/batch/create-with-durations-ll/createWithDurationsLL.t.sol' found

Usage: forge test [OPTIONS]

For more information, try '--help'.
```

### What do you see instead?

No double quotes.

**Comment by zackradisic** [comment]
I believe this is expected behavior, the shell is removing the double quotes here, not Bun

If you want to preserve the quotes you should escape them
