### ISSUE TITLE
Bun build --target bun with NODE_ENV=production transpiles JSX to objects with "react-jsx"

### ISSUE THREAD

**Issue by awilderink** [oven-sh/bun#10171]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```json
{
  "compilerOptions": {
      ...
      "jsx": "react-jsx",
      "jsxImportSource": "@kitajs/html",
      ...
   }
}
```

```tsx
// index.tsx
const Test = () => {
 return (
    <div>
      <h1>Hello, World!</h1>
    </div>
  );
};

console.log(<Test />);
```

run `bun build --target bun index.tsx --outfile index.js && bun index.js`

### What is the expected behavior?

wrapping JSX input with the jsxRuntime

### What do you see instead?

```js
// @bun
var $$typeof = Symbol.for("react.element");

// index.tsx
var Test = () => {
  return {
    $$typeof,
    type: "div",
    key: null,
    ref: null,
    props: {
      children: {
        $$typeof,
        type: "h1",
        key: null,
        ref: null,
        props: {
          children: "Hello, World!"
        },
        _owner: null
      }
    },
    _owner: null
  };
};
console.log({
  $$typeof,
  type: Test,
  key: null,
  ref: null,
  props: Test.defaultProps || {},
  _owner: null
});
```

### Additional information

Workaround is to not compile with NODE_ENV=production. I have renamed the env variable to `prod`

**Comment by Jarred-Sumner** [comment]
This is an intentional performance optimization. If you set jsxImportSource, you can disable it. We might change the details of this transform in the future to support React 19.

**Comment by awilderink** [comment]
Hi @Jarred-Sumner, Thank you for answering so quickly. 

I for got to mention that I have set the `jsxImportSource` to `@kitajs/html`, but it still gives me the same result. I updated the issue.

**Comment by sirenkovladd** [comment]
I have the same issue, could you please reopen this issue?
