### ISSUE TITLE
class extending blob cant set `name` prop

### ISSUE THREAD

**Issue by juliusmarminge** [oven-sh/bun#10178]
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Repo: https://github.com/juliusmarminge/bun-blob

To test, run `bun run index.js` - see error.
Run `node index.js` - works as expected.

![CleanShot 2024-04-11 at 21 31 03](https://github.com/juliusmarminge/bun-blob/assets/51714798/318eb53f-c8fc-41c5-be3b-6fcde67f9565)

### What is the expected behavior?

```sh
➜  bun-blob node index.js
blob name undefined
Blob { size: 13, type: '' }
hello.txt
1712863862801
undefined
```

### What do you see instead?

```sh
➜  bun-blob bun index.js
blob name undefined
 8 |         ...options,
 9 |         type: options?.type ?? undefined,
10 |         lastModified: options?.lastModified ?? Date.now(),
11 |       };
12 |       super(parts, optionsWithDefaults);
13 |       this.name = name;
           ^
TypeError: Attempted to assign to readonly property.
      at new UTFile (/Users/julius/dev/sandbox/bun-blob/index.js:13:7)
      at /Users/julius/dev/sandbox/bun-blob/index.js:19:16
```

**Comment by juliusmarminge** [comment]
Interesting side note, extending e.g. `Buffer` works fine:

![CleanShot 2024-04-11 at 21 36 00](https://github.com/oven-sh/bun/assets/51714798/dc23a067-098f-4eb3-9144-f82ed7d005df)

**Comment by fahidsarker** [comment]
This issue still exists in bun 1.2.2. why is it closed?

**Comment by MathiasGruber** [comment]
I'm still running into this on latest bun and latest uploadthing

**Comment by juliusmarminge** [comment]
> I'm still running into this on latest bun and latest uploadthing, any hints on what to do [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/51714798?s=64&amp;u=7010559c831ddae241a5c1ace13e5a78048f9219&amp;v=4">@juliusmarminge](https://github.com/juliusmarminge) ?

nothing we can do unfortunately :/ This is an issue in Bun...
