### ISSUE TITLE
Hang when running bun install

### ISSUE THREAD

**Issue by u9g** [oven-sh/bun#1017]
### Version

0.1.7

### Platform

Linux codespaces-38a1b0 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. `git clone https://github.com/PrismarineJS/mineflayer`
2. `cd mineflayer`
3. `bun i`
4. Hangs...

### How often does it reproduce? Is there a required condition?

Reproduces every time I've tested it, no required condition

### What is the expected behavior?

mineflayer's dependencies install correctly

### What do you see instead?

A hang on downloading a random dependency each time

**Comment by Jarred-Sumner** [comment]
The bug is caused by the package depending on itself:
```
"mineflayer": "file:.",
```

**Comment by u9g** [comment]
Works now
