### ISSUE TITLE
Promisified execFile: Bun incorrectly returns stdout instead of object with stdout & stderr

### ISSUE THREAD

**Issue by ad-si** [oven-sh/bun#10170]
### What version of Bun is running?

1.1.3+257f4c1b3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { execFile } from "node:child_process"
import util from "node:util"

const execFileAsync = util.promisify(execFile)
const result = await execFileAsync("ls")
console.log(result)
```

### What is the expected behavior?

```sh
$ node test.js
{
  stdout: 'archive\n' +
    'bun.lockb\n' +
    'changelog.md\n' +
    'readme.md\n' +
    'test.js\n',
  stderr: ''
}
```

### What do you see instead?

```sh
$ bun run test.js
archive
bun.lockb
changelog.md
readme.md
test.js
```

**Comment by kitajchuk** [comment]
+1. Discovered this issue trying to switch to `bun` to run an app using node-poppler which uses promisified execFile.
