### ISSUE TITLE
console.log says "Function" instead of "AsyncFunction"

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#10173]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
async function a() {}

console.log(a);
```

### What is the expected behavior?

AsyncFunction

### What do you see instead?

Function

### Additional information

in Node.js, this says "AsyncFunction"

**Comment by touhidurrr** [comment]
now this is some interesting bug.

**Comment by mw2000** [comment]
@huseeiin happy to tackle this

**Comment by Jarred-Sumner** [comment]
Fixed in #12136
