### ISSUE TITLE
`bun upgrade` not showing full changelog

### ISSUE THREAD

**Issue by Wyatt-Stanke** [oven-sh/bun#1019]
### Version

v0.1.7

### Platform

Darwin Wyatts-Mac-mini.local 22.0.0 Darwin Kernel Version 22.0.0: Wed Jul 20 01:51:06 PDT 2022; root:xnu-8792.0.188.141.3~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

`bun upgrade` from 0.1.5 to 0.1.7

### How often does it reproduce? Is there a required condition?

Every time and no.

### What is the expected behavior?

The full changelog from versions v0.1.5 to v0.1.7

### What do you see instead?

```
What's new:

    https://github.com/oven-sh/bun/releases/tag/bun-v0.1.7
```
(not full changelog)

**Comment by xhyrom** [comment]
I don't think this is a bug. The URL has the whole changelog, but if it was sent to console it would be spammed. Closing.

**Comment by xhyrom** [comment]
I'm sorry, we just misunderstood a bit. I think `bun upgrade` should send the URL of both v0.1.6 and v0.1.7 changelogs

**Comment by Wyatt-Stanke** [comment]
Yeah, my bad. I worded it a little weird.
