### ISSUE TITLE
Implement bun . like node .

### ISSUE THREAD

**Issue by LiberaTeMetuMortis** [oven-sh/bun#1021]
### Version

0.1.7

### Platform

Linux metumortis-monster 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Try it.

### How often does it reproduce? Is there a required condition?

Every time.

### What is the expected behavior?

It should run the "module" or the "main" file in package.json

### What do you see instead?

error: Script not found "."

**Comment by xhyrom** [comment]
That's not bug, it's not implemented

**Comment by LiberaTeMetuMortis** [comment]
> That's not bug, it's not implemented 

https://discord.com/channels/876711213126520882/887787428973281300/1005872545561583736

**Comment by birkskyum** [comment]
Node doesn't find `main.js` or `module.js`, but it does find `index.js`.

I checked with `bun .` just now, at it at least find `index.js`, `index.ts`, `index.jsx`, `index.tsx`, and maybe more.
