### ISSUE TITLE
Arrow keys for terminal prompts not working when nodejs is not installed

### ISSUE THREAD

**Issue by piranha771** [oven-sh/bun#10217]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

EITHER

- nodejs is **NOT** installed
- `bun create vite test-app`

OR

- `bun create --bun vite test-app`

### What is the expected behavior?

When prompted to select a framework using the arrow keys, the arrow keys move the cursor up and down

### What do you see instead?

The arrow keys are not recognized as input, nothing happens. The user is unable to select anything else than the standard option. It does not matter what terminal / shell you use.

### Additional information

**The problem can be solved by installing nodejs**. But there isn't any error message or anything that helps the user to find the cause of the input not getting recognized.

I first thought this was only vite.
Please also see: https://github.com/vitejs/vite/issues/16403#event-12450641332

**Comment by gvilums** [comment]
For context: When node is installed, the creation script runs in node. Without node, it runs with bun. When node is installed this can be reproduced with `bun create --bun vite test-app` to force running in bun.

**Comment by anarchylimes** [comment]
Also having this issue. Resolved it by installing node but I would really prefer to not have node installed if I can use bun.

**Comment by NStodd** [comment]
This appears to be an issue with gitbash in certain circumstances. 
Solution noted here is to use vscode: https://stackoverflow.com/questions/55753151/cant-use-arrow-keys-in-git-bash-windows
