### ISSUE TITLE
node:dns error codes are different

### ISSUE THREAD

**Issue by firecow** [oven-sh/bun#10213]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Linux 6.5.0-27-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
import {Resolver} from "node:dns/promises";

void (async () => {
    try {
        const resolver = new Resolver({timeout: 250, tries: 2});
        const addresses = await resolver.resolve("docker-stack_service");
        console.log(addresses);
    } catch (e: any) {
        console.error(e.message, e.code);
    }
})();
```

### What is the expected behavior?

The same error code as nodejs gives.

### What do you see instead?

Error codes are prefixed with `DNS_`

```
$ bun src/test.ts 
DNS lookup failed: Domain name not found DNS_ENOTFOUND

$ node src/test.js
queryA ENOTFOUND docker-stack_service ENOTFOUND
```

**Comment by Arthur944** [comment]
I noticed the same issue. An even shorter reproduction:

```
import dns from "dns";

try {
  const record = await dns.promises.resolveTxt("asdf");
} catch (e) {
  console.log({ errorCode: e.code });
}
```

Output:
```
$ tsx repro.ts
{ errorCode: 'ENOTFOUND' }

$ bun run repro.ts
{
  errorCode: "DNS_ENOTFOUND",
}
```

Platform: `Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64` and `Microsoft Windows NT 10.0.22621.0 x64`
