### ISSUE TITLE
Bun.build: Internal error: missing asset file

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#10227]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 5.15.0-102-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
Bun.build({
    entrypoints: ["path/to/file.myext"],
    plugins: [
       {
          setup(build) {
            build.onLoad(
              {
                filter: /\.myext$/,
              },
              async (args) => {
                return {
                  loader: "file",
                  contents: await Bun.file(args.path).text(),
                };
              }
            );
          },
        },
    ]
})
```

### What is the expected behavior?

To copy the file as-is

### What do you see instead?

uh-oh: Internal error: missing asset file
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.3 (2615dc74) Linux x64 (baseline) #112~20.04.1-Ubuntu SMP Thu Mar 14 14:28:24 UTC 2024
AutoCommand: tsconfig(8) transpiler_cache(2) Bun.stdin(2) 
Builtins: "bun:main" "node:events" "node:fs" "node:module" "node:os" "node:path" "node:path/posix" "node:process" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" 
Elapsed: 1363ms | User: 1712ms | Sys: 166ms
RSS: 67.15MB | Peak: 0.16GB | Commit: 67.15MB | Faults: 0
----- bun meta -----

0   0x556f46aaa19b
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 6733 panic: Internal error: missing asset file
Unwind information for `:0x556f45700607` was not available, trace may be incomplete

### Additional information

Workaround:

```ts
Bun.build({
    // ...
    loader: {
        [".myext"]: "file"
   }
})
```

**Comment by Electroid** [comment]
Duplicate of #9537

**Comment by ghost** [comment]
@Electroid can you mark #9537 as a duplicate of this issue? I found that this bug only occurs when a plugin try to use the "file" loader on an entrypoint, so #10227 is more accurate than #9537
