### ISSUE TITLE
bun update not working on bun 1.1.3, it was working on older version

### ISSUE THREAD

**Issue by Dhruv-Garg79** [oven-sh/bun#10241]
### What version of Bun is running?

1.1.3

### What platform is your computer?

darwin, arm

### What steps can reproduce the bug?

run bun update

### What is the expected behavior?

should update outdated packages

### What do you see instead?

nothing happening

### Additional information

it was working on older version, stopped working when I updated to 1.1.3 today

**Comment by JeissonWeeDev** [comment]
@Dhruv-Garg79 for solve this, use `bun run upgrade` or `bun upgrade`, if you're using linux use `sudo bun upgrade` _(Could cause problems)_

**Comment by Dhruv-Garg79** [comment]
- I am on mac(darwin). 
- The upgrade command is for updating the bun itself and not dependencies
- I still tried running it and it didn't work.

**Comment by touhidurrr** [comment]
As of `1.1.4`, I am facing problems with:
1. `bun update`
2. `bun update --latest`
3. `bun update -f`
4.  `bun update -f --latest`

Non of these commands update `package.json`.

**Comment by dylan-conway** [comment]
This was fixed in bun `v1.1.11` with #11340. If you run into any issues with `bun update` please reopen or create a new issue
