### ISSUE TITLE
Implement `AbortSignal.any()` static method

### ISSUE THREAD

**Issue by dillonstreator** [oven-sh/bun#10251]
### What is the problem this feature would solve?

The `AbortSignal.any()` static method takes an iterable of abort signals and returns an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal). The returned abort signal is aborted when any of the input iterable abort signals are aborted. The [abort reason](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/reason) will be set to the reason of the first signal that is aborted. If any of the given abort signals are already aborted then so will be the returned [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal).

### What is the feature you are proposing to solve the problem?

Implement `AbortSignal.any()` static method.

https://dom.spec.whatwg.org/#dom-abortsignal-any
https://nodejs.org/api/globals.html#static-method-abortsignalanysignals
https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/any_static

**Comment by Jarred-Sumner** [comment]
Can you run `bun upgrade --canary` and try again?

**Comment by dillonstreator** [comment]
Looks good on `canary` - I see `any` was introduced [here](https://github.com/oven-sh/bun/commit/df49a5a8e4644ce833bd91db0ae14a279bb97bce#diff-787e684583b8b7cfd42b27f4dfed66042a1a9e5375ebad4d9ba23bf427be5ad6R86) 👍
