### ISSUE TITLE
bun run script error on windows

### ISSUE THREAD

**Issue by lonelysnows** [oven-sh/bun#10272]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 | x64

### What steps can reproduce the bug?

1: bunx create-elysia@latest;
2: bun install;
3: bun run start
if I run the index.ts directly ,it works.I think there is  a bug when reslove start command.

### What is the expected behavior?

run the project

### Additional information

![image](https://github.com/oven-sh/bun/assets/155499396/25c411a1-27f8-4fd5-a390-abb03a6df923)

**Comment by Electroid** [comment]
This could possibly be an issue with non-ascii file paths.

**Comment by dylan-conway** [comment]
Fixed in Bun v1.1.16 with #11990
