### ISSUE TITLE
bun test - add support for Flow

### ISSUE THREAD

**Issue by mrobokit** [oven-sh/bun#10276]
### What is the problem this feature would solve?

We have tons of tests that include Flow, and because of that i cann't propose my business use `bun test`. How much effort would have to go into this one?

### What is the feature you are proposing to solve the problem?

- bun test support for Flow

### What alternatives have you considered?
- Webpack, but having to run a process to remove those Flow comments before testing completely negates the speed benefit of using bun test.

_No response_

**Comment by Electroid** [comment]
This can be done with a Bun plugin for now: https://bun.sh/docs/runtime/plugins#loaders

We don't currently have native-Flow support on the roadmap.
