### ISSUE TITLE
Bun.serve missing Date header

### ISSUE THREAD

**Issue by littledivy** [oven-sh/bun#1028]
### Version

0.1.6

### Platform

Darwin mini.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

```js
Bun.serve({
  fetch() {
    return new Response("Hello World");
  },
  port: 4545,
});
```

```
curl -vs localhost:4545
*   Trying 127.0.0.1:4545...
* Connected to localhost (127.0.0.1) port 4545 (#0)
> GET / HTTP/1.1
> Host: localhost:4545
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 HM
< content-type: text/plain;charset=utf-8
< Content-Length: 11
<
* Connection #0 to host localhost left intact
Hello World⏎        
```

### What is the expected behavior?

The Date header is passed as a UTC string.

### What do you see instead?

No Date header.

### Additional information

Quoting [rfc7231](https://www.rfc-editor.org/rfc/rfc7231#section-7.1.1.2)

> An origin server MUST NOT send a Date header field if it does not have a clock capable of providing a reasonable approximation of the current instance in Coordinated Universal Time. An origin server MAY send a Date header field if the response is in the 1xx (Informational) or 5xx (Server Error) class of status codes. **An origin server MUST send a Date header field in all other cases.**

**Comment by wa22im** [comment]
Hello, can I work on this issue?

**Comment by evanwashere** [comment]
I don't see why we should implement it, there are only downsides to it like larger packets, timing attacks, and hard to predict path for cpu

**Comment by Jarred-Sumner** [comment]
There are HTTP cache implications sometimes & it's not spec-compliant

Will be fixed soon.

**Comment by Jarred-Sumner** [comment]
`Date` header has been added in Bun v0.2.1
