### ISSUE TITLE
Completion: Support Tab completion for arguments in powershell

### ISSUE THREAD

**Issue by musafiroon** [oven-sh/bun#10293]
### What is the problem this feature would solve?

Support tab completion for powershell. 

### What is the feature you are proposing to solve the problem?

Using [Register-ArgumentCompleter
](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.4) , we can register arguments for powershell tab completion

**Comment by paperclover** [comment]
Duplicate of #8939
