### ISSUE TITLE
Workspace: "bun --filter './packages/NAME' SCRIPT_NAME PARAM_VALUE" Module/Script not found

### ISSUE THREAD

**Issue by baphony** [oven-sh/bun#10299]
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Trying to run a command for a worspace package doesn't work on Windows 11 powershell 7
![image](https://github.com/oven-sh/bun/assets/112877883/2b9bbffc-b493-4828-b0a0-e15db1aa4fc3)

bun --filter ".\\packages\\d" step-version is-changed
bun --filter ./packages/d step-version is-changed
bun --filter d step-version is-changed

### What is the expected behavior?

This but from the workspace root:
![image](https://github.com/oven-sh/bun/assets/112877883/cb79fcc1-08d1-42f9-a2c7-317b4f3bce10)

### What do you see instead?

error: Script not found "d"
error: Module not found "./packages/d"

I tried:
with package name "d", package path "./packages/d"
with / and \
with quotes, double quotes and no quotes

### Additional information

workspace root package.json:
```json
{
    "name": "base",
    "version": "1.0.0",
    "private": true,
    "license": "UNLICENSED",
    "scripts": {
        "step-version": "wsrun --serial --exclude-missing --no-prefix step-version",
        "step-version-validate-root": "step-version validate-root"
    },
    "workspaces": [
        "packages/*"
    ],
    "devDependencies": {}
}
```

Package "d" package.json:
```json
{
  "name": "d",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "scripts": {
    "step-version": "step-version"
  }
}
```

wsrun & step-version are in workpaceRoot/node_modules/.bin

**Comment by Electroid** [comment]
You'll need to upgrade to canary, run `bun upgrade --canary`. This will be released today.

**Comment by baptistecs** [comment]
Many thanks!
