### ISSUE TITLE
Bun 10x slower while running OCR

### ISSUE THREAD

**Issue by derekhearst** [oven-sh/bun#10307]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Clone [this repo](https://github.com/derekhearst/BunSlowdown)
run bun install
run bun index.js 
then run node index.js

### What is the expected behavior?

Bun is over 10x slower than node

### What do you see instead?

I expect bun to be equal or quicker than node

**Comment by derekhearst** [comment]
https://github.com/oven-sh/bun/issues/10306\
Main isue

**Comment by Jarred-Sumner** [comment]
(marking as duplicate for tracking purposes, as it was not completed)
