### ISSUE TITLE
Support `"file://…"` for paths passed to `dlopen(…)` (from `bun:ffi`)

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#10304]
This is a new issue based on https://github.com/oven-sh/bun/issues/9878#issuecomment-2039068136

### What version of Bun is running?

1.1.4

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```shell
git clone https://github.com/cubing/twsearch && cd twsearch
git checkout 6279f4abbee4ac8941d7cd5648c6811eb283cb0a
cargo install cargo-run-bin # Requires `cargo` to be installed already.
make build-rust-ffi
bun run "src/rs-ffi/test/js_test.ts"
```

### What is the expected behavior?

`dlopen` opens the `file://` path from `import.meta.resolve(…)`

### What do you see instead?

```
 8 |   `../../../target/release/libtwsearch_ffi.${suffix}`,
 9 | );
10 | 
11 | const {
12 |   symbols: { ffi_random_scramble_for_event },
13 | } = dlopen(path, {
         ^
ERR_DLOPEN_FAILED: Failed to open library. This is usually caused by a missing library or an invalid library path.
 syscall: "dlopen"

      at bun:ffi:61:41
      at /Users/lgarron/Code/git/github.com/cubing/twsearch/src/rs-ffi/test/js_test.ts:13:5
make: *** [test-rust-ffi-js] Error 1
```

### Additional information

I was glad to see https://github.com/oven-sh/bun/pull/9883 land in `bun` 1.1.1, but it doesn't seem to work on my computer at all. 🥺
I would love to be able to use it!

**Comment by Jarred-Sumner** [comment]
oh, this is `dlopen` from bun:ffi

I thought this was process.dlopen

🤦

**Comment by lgarron** [comment]
> oh, this is `dlopen` from bun:ffi
> 
> I thought this was process.dlopen

Ah, I also didn't realize there were multiple. 😅
Would definitely appreciate compat in `bun:ffi` as well! 😄
