### ISSUE TITLE
JSON.parse and Bun.write handle latin1 supplement characters incorrectly

### ISSUE THREAD

**Issue by gourmetseasoningsake** [oven-sh/bun#1031]
### Version

0.1.7

### Platform

Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

```javascript
let ae = '["ä"]'
console.log(ae) //-> ["ä"]
console.log(JSON.parse(ae)) //-> [ "�" ]
Bun.write("ae.txt", ae) //-> [ "�" ]
```

### What is the expected behavior?

["ä"]

### What do you see instead?

[ "�" ]

**Comment by binary-koan** [comment]
Just to note that this affects server responses and bun:sqlite as well (I assume for the same reason). For example:

```ts
import { Database } from "bun:sqlite"

const db = new Database("test.sqlite")

db.run("CREATE TABLE IF NOT EXISTS test (str)")

db.run("INSERT INTO test VALUES (?)", "¥¥¥¥¥¥¥¥¥")

console.log(db.query("SELECT * FROM test").all()) // ends up blank - [{ str: '' }]
```

or

```ts
Bun.serve({
  port: 1234,
  fetch() {
    return new Response("¥¥¥¥¥¥¥¥¥")
  }
})
```

should respond with `¥¥¥¥¥¥¥¥¥` but responds with `���������`

**Comment by gourmetseasoningsake** [comment]
```javascript
let ae = '["ä"]'
Bun.write("ae.txt", ae)
```
..works for me in v0.1.13
