### ISSUE TITLE
Bun treats js variables as typed variables and throws error

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#10317]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```js
// test.js
for (i = 0; i < 3; i++) {
  console.log(i);
}
```

### What is the expected behavior?

```bash
node test.js
0
1
2
```

### What do you see instead?

```bash
bun test.js
1 | for (i = 0; i < 3; i++) {
         ^
ReferenceError: Can't find variable: i
      at C:\Users\User\Desktop\NewProjects\test2.js:1:6
```

### Additional information

So js files are ts files by default? Interesting info.

**Comment by Jarred-Sumner** [comment]
Bun uses strict mode & ES Modules by default, unless a CommonJS-only feature like `exports` or `module` is used.

This error happens due to strict mode where assigning to a variable without declaring it is an error by default

**Comment by touhidurrr** [comment]
Ok, so not a real issue I guess. Thanks for replying. I tried using `"use strict"` with node and could reproduce similar behavior.
