### ISSUE TITLE
Windows: package patch is applied to the bun cache files

### ISSUE THREAD

**Issue by baphony** [oven-sh/bun#10327]
### What version of Bun is running?

1.1.4+df190815d

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Install
https://www.npmjs.com/package/patch-package

Create a patch
Just make you changes inside node_modules/PACKAGE_NAME
bunx patch-package PACKAGE_NAME --append 'my-change-description'

Apply that patch
bunx patch-package PACKAGE_NAME 

.bun/install/cache/PACKAGE_NAME will be updated too

### What is the expected behavior?

.bun/install/cache/PACKAGE_NAME should not be updated, only PROJECT/node_modules/PACKAGE_NAME

**Comment by Jarred-Sumner** [comment]
By default, bun install used hardlinks on Windows. You can change this behavior via —backend=copyfile or by setting `install.backend = “copyfile”` in bunfig.toml. Copying files has a significant performance penalty compared to hardlinks so we won’t be changing this default unless that changes or a better install approach is implemented.

**Comment by baptistecs** [comment]
Yes, —backend=copyfile works fine, but if I don’t do it, I get some errors after deleting node_modules and installing again.

This is not a great user experience for default settings:-/

**Comment by UltimateGG** [comment]
How do you test if the file is hardlinked? Viewing the properties on the node_modules folder it still takes up the same space as normal, and no properties show it as being a link to another file?

**Comment by Araxeus** [comment]
> How do you test if the file is hardlinked? Viewing the properties on the node_modules folder it still takes up the same space as normal, and no properties show it as being a link to another file?

basic way: run `fsutil hardlink list MyFileName.txt` to see all hardlinked version of a file

if you want visual tools to manage hardlinks in Windows Explorer: 
you can try https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html 
 
which will make you able to visually differentiate between hardlinks and normal files, view their properties, create and delete them etc

keep in mind bun is hardlinking **individual files** and not making symbiotic links or junctions for folders
