### ISSUE TITLE
`bun run --filter '*'` does not support scoped package name

### ISSUE THREAD

**Issue by guyutongxue** [oven-sh/bun#10322]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

With following monorepo structure:

```
├─package.json
└─packages
  ├─a
  │ └─package.json
  └─b
    └─package.json
```

Root `package.json` is:

```json
{
  "workspaces": ["packages/*"]
}
```

`packages/a/package.json` is:

```json
{
  "name": "@my/a",
  "private": true,
  "scripts": {
    "test": "echo a"
  }
}
```

`packages/b/package/json` is:

```json
{
  "name": "@my/b",
  "private": true,
  "scripts": {
    "test": "echo b"
  }
}
```

Type `bun run --filter '*' test` under root working directory.

### What is the expected behavior?

If we "unscope" those subpackages name (like `a` `b` without `@my/` part), then the behavior is correct:

```
>  bun run --filter '*' test
a test $ echo a                                                                                                                                                        
│ a                                                                                                                                                                    
└─ Done in 82 ms                                                                                                                                                       
b test $ echo b                                                                                                                                                        
│ b                                                                                                                                                                    
└─ Done in 79 ms        
```

Or we use `bun run --filter '@my/*'` instead of `'*'`:

```
>  bun run --filter '@my/*' test
@my/a test $ echo a                                                                                                                                                    
│ a                                                                                                                                                                    
└─ Done in 78 ms                                                                                                                                                       
@my/b test $ echo b                                                                                                                                                    
│ b                                                                                                                                                                    
└─ Done in 70 ms      
```

### What do you see instead?

Currently bun doesn't support using '*' filter to find those scoped-name packages:

```
>  bun run --filter '*' test
error: No packages matched the filter
```

**Comment by moritzmla** [comment]
Is there a work around for this?

**Comment by Jarred-Sumner** [comment]
This appears to be a bug with the glob matching code.

A workaround: 
```js
bun run --filter="**" test
```

`*` is matching the path `*` instead of every package.json name

**Comment by mrousavy** [comment]
I'm not sure what I'm doing wrong, but I simply cannot get `--filter` to match anything for me. Any ideas? @Jarred-Sumner 

![Screenshot 2024-08-02 at 01 11 04](https://github.com/user-attachments/assets/36137900-88f8-465a-a351-30713af80fba)

**Comment by Jarred-Sumner** [comment]
@mrousavy  can you try adding a name to your package.json?

**Comment by mrousavy** [comment]
Hey - adding a `name` to that root `package.json` didn't change anything, but apparently `tsc` just doesn't work.

I tried another command (literally `"some-custom-command": "tsc"`), which now works - I guess `tsc` is conflicting names with the actual `tsc` bin in the typescript package?

**Comment by Jarred-Sumner** [comment]
Ah, `--filter` applies to package.json scripts, rather than executable files in node_modules/.bin. `tsc` is an executable, not a key in package.json `"scripts"`

It'd be reasonable to add support for this, but also technically a breaking change

**Comment by mrousavy** [comment]
Maybe a dumb question, but does bun automatically replace `workspace:*` syntax with the actual dependency version like yarn workspaces does?

When I run `release-it` with bun (and one of my packages in my monorepo has a `"package-a": "workspaces:^"` dependency), it fails because the `workspace:*` syntax is not replaced with an actual version string:

```diff
- ERROR npm error code EUNSUPPORTEDPROTOCOL
- npm error Unsupported URL Type "workspace:": workspace:^
```
