### ISSUE TITLE
bun install cannot resolve local file dependencies

### ISSUE THREAD

**Issue by Stono** [oven-sh/bun#10324]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

macosx

### What steps can reproduce the bug?

We have a module we publish which bundles some eslint rules, and it does so with a file:./ reference in the package.json

<img width="898" alt="Screenshot 2024-04-17 at 11 59 27" src="https://github.com/oven-sh/bun/assets/1486729/3cd3b23e-7523-41bb-b3ae-d7e79086e51a">

Subsequently this fails to install in a downstream app with:

```
error: eslint-plugin-webserver-custom-rules@file:./webserver-custom-rules failed to resolve
error: eslint-plugin-custom-rules@file:./custom-rules failed to resolve
```

### What is the expected behavior?

File dependencies to work

**Comment by dylan-conway** [comment]
Thank you for the bug report. We will fix this soon
