### ISSUE TITLE
Behaviour of fs.existsSync, when using long file paths, deviates from Node

### ISSUE THREAD

**Issue by torjue** [oven-sh/bun#10356]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```typescript
import fs from "node:fs";
fs.existsSync("<string with more than 1025 characters>");
```

### What is the expected behavior?

Not to throw, as Node.js. Also, max file length on most Linux systems are often set to 4096, not 1024.

### What do you see instead?

```
1 | import fs from "node:fs";
2 | fs.existsSync(
    ^
ENAMETOOLONG: File name too long
 errno: -63
```

### Additional information

Some packages uses fs.existsSync as a way to check if a parameter contains information or points to a file. Probably not the best idea, but it's still used. See [these lines](https://github.com/hashicorp/terraform-cdk/blob/153a4b2bb7312abf9ca5ce1b501d724f3da153c4/packages/cdktf/lib/testing/matchers.ts#L146-L148) in CDKTF from Hashicorp.

**Comment by Jarred-Sumner** [comment]
ah yes, 

Reading node's code, looks like `fs.existsSync` is supposed to never throw, including on invalid input:
https://github.com/nodejs/node/blob/main/lib/fs.js#L275-L295

```js
// fs.existsSync never throws, it only returns true or false.
// Since fs.existsSync never throws, users have established
// the expectation that passing invalid arguments to it, even like
// fs.existsSync(), would only get a false in return, so we cannot signal
// validation errors to users properly out of compatibility concerns.
// TODO(joyeecheung): deprecate the never-throw-on-invalid-arguments behavior
/**
 * Synchronously tests whether or not the given path exists.
 * @param {string | Buffer | URL} path
 * @returns {boolean}
 */
function existsSync(path) {
  try {
    path = getValidatedPath(path);
  } catch {
    return false;
  }

  return binding.existsSync(pathModule.toNamespacedPath(path));
}
```

We need to make ours behave similarly
