### ISSUE TITLE
TypeError on function hexToRgb in index.js

### ISSUE THREAD

**Issue by jessicahirsch** [oven-sh/bun#10361]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

When running orbit `bun run ./lib/bun/scripts/orbit/exec.ts` I am receiving the following error. Discovered today. There are no special steps to reproduce. Has this been reported elsewhere?
```js
134 |           hexToRgb: {
135 |                   value(hex) {
136 |                           const matches = /[a-f\d]{6}|[a-f\d]{3}/i.exec(hex.toString(16));
                                                        ^
TypeError: undefined is not an object (evaluating 'hex.toString')
      at value (/Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/vendor/ansi-styles/index.js:136:51)
      at getModelAnsi (/Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/index.js:88:46)
      at /Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/index.js:101:33
      at printEmulateCompose (/Users/jessicahirsch/Developer/workstation/lib/bun/utils/cmdline.ts:81:17)
      at /Users/jessicahirsch/Developer/workstation/lib/bun/utils/sub-processes/index.ts:68:17
      at /Users/jessicahirsch/Developer/workstation/lib/bun/utils/sub-processes/index.ts:121:13
```

**Comment by Electroid** [comment]
Hi there! We will need some code in order to reproduce this.

**Comment by jessicahirsch** [comment]
Here is a greater snippet of the stacktrace
`        web-1           | nps is executing `build.clean` : rimraf ../../build/components
[ "41444B" ]
        web-1           | nps is executing `build.ts` : tsc --project tsconfig.build.json && tsc-alias -p tsconfig.build.json
[ "51CB8C" ]
        api-gateway-1   | [12:22:10 AM] Found 0 errors. Watching for file changes.
[ "51CB8C" ]
        api-gateway-1   | 
131 |                   },
132 |                   enumerable: false,
133 |           },
134 |           hexToRgb: {
135 |                   value(hex) {
136 |                           const matches = /[a-f\d]{6}|[a-f\d]{3}/i.exec(hex.toString(16));
                                                        ^
TypeError: undefined is not an object (evaluating 'hex.toString')
      at value (/Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/vendor/ansi-styles/index.js:136:51)
      at getModelAnsi (/Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/index.js:88:46)
      at /Users/jessicahirsch/Developer/workstation/lib/bun/node_modules/chalk/source/index.js:101:33
      at printEmulateCompose (/Users/jessicahirsch/Developer/workstation/lib/bun/utils/cmdline.ts:81:17)
      at /Users/jessicahirsch/Developer/workstation/lib/bun/utils/sub-processes/index.ts:68:17
      at /Users/jessicahirsch/Developer/workstation/lib/bun/utils/sub-processes/index.ts:121:13
`

Here is the full function responsible for failure.
`	// From https://github.com/Qix-/color-convert/blob/3f0e0d4e92e235796ccb17f6e85c72094a651f49/conversions.js
	Object.defineProperties(styles, {
		rgbToAnsi256: {
			value(red, green, blue) {
				// We use the extended greyscale palette here, with the exception of
				// black and white. normal palette only has 4 greyscale shades.
				if (red === green && green === blue) {
					if (red < 8) {
						return 16;
					}

					if (red > 248) {
						return 231;
					}

					return Math.round(((red - 8) / 247) * 24) + 232;
				}

				return 16
					+ (36 * Math.round(red / 255 * 5))
					+ (6 * Math.round(green / 255 * 5))
					+ Math.round(blue / 255 * 5);
			},
			enumerable: false,
		},
		hexToRgb: {
			value(hex) {
				const matches = /[a-f\d]{6}|[a-f\d]{3}/i.exec(hex.toString(16));
        console.log(matches);
				if (!matches) {
					return [0, 0, 0];
				}

				let [colorString] = matches;

				if (colorString.length === 3) {
					colorString = [...colorString].map(character => character + character).join('');
				}

				const integer = Number.parseInt(colorString, 16);

				return [
					/* eslint-disable no-bitwise */
					(integer >> 16) & 0xFF,
					(integer >> 8) & 0xFF,
					integer & 0xFF,
					/* eslint-enable no-bitwise */
				];
			},
			enumerable: false,
		},`

**Comment by jessicahirsch** [comment]
Here is the `hexToRgb` function.
_Sorry for the formatting. Github is not formatting as expected._

`hexToRgb: {
			value(hex) {
				const matches = /[a-f\d]{6}|[a-f\d]{3}/i.exec(hex.toString(16));
        console.log(matches);
				if (!matches) {
					return [0, 0, 0];
				}

				let [colorString] = matches;

				if (colorString.length === 3) {
					colorString = [...colorString].map(character => character + character).join('');
				}

				const integer = Number.parseInt(colorString, 16);

				return [
					/* eslint-disable no-bitwise */
					(integer >> 16) & 0xFF,
					(integer >> 8) & 0xFF,
					integer & 0xFF,
					/* eslint-enable no-bitwise */
				];
			},
			enumerable: false,
		},`
