### ISSUE TITLE
`--filter` option not working neither for installs or scripts

### ISSUE THREAD

**Issue by wesleycoder** [oven-sh/bun#10367]
### What version of Bun is running?

1.1.4+e134ed253

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

- Clone the [minimal reproduction repository](https://github.com/wesleycoder/bun-test) on the machine or Github Codespaces (tested there too, not working)
- Open on the repository on the terminal
- Install Bun
- Upgrade Bun to canary (optional, also broken on production version at the time of this issue submission)
- Run the following commands observing the outputs
```sh
bun run --filter 'a' test # should run the test command on the `packages/a` package
bun --filter 'a' test # should run the test command on the `packages/a` package 
bun --filter '*' test # should run the test command on both `packages/a` and `packages/b` packages 
```

### What is the expected behavior?

We should be able to provide the `--filter` flag as described on [the docs](https://github.com/oven-sh/bun/blob/main/docs/cli/filter.md) and be able to run scripts of children packages.

### What do you see instead?

Despite validating the `workspaces` option on `package.json`, the `--filter` option is faulty when detecting the existence of the packages for running scripts and always returns `error: No packages matched the filter` 

### Additional information

I've tried on my machine (Macbook Pro 14, M1 2021, Sonoma 14.5 Beta) and on GH Codespaces (smaller spec).
Both environments fail both on install and on script runs.

This is a follow up on the feedback given [on this issue](https://github.com/oven-sh/bun/issues/2232#issuecomment-2060542929) that tracked the feature being implemented.

*Edit:* removing the intent of installing dependencies as it is out of scope.

**Comment by gvilums** [comment]
Just as a heads up: the link to the minimal reproduction repository seems to be broken.

`--filter` currently only works with `package.json` scripts. This means that you can't yet install packages with --filter or run installed packages directly. If it's not working for running `package.json` scripts then that's a bug - it would be helpful if you could clarify (and fix the link to the reproduction example if possible).

**Comment by wesleycoder** [comment]
I'm sorry, I meant to create it public, but in the rush it was private, should be available now.
Thanks for the heads up, I'm sorry I took this long to check it.

**Comment by wesleycoder** [comment]
I was under the impression it would work for installs too when looking at the discussions on the PR, but now I understand was a misconception of mine, mainly because of the current behavior that installs packages to the root.

But to clarify, yes, the scripts are not running with `--filter`
`bun --filter '*' test` always errors with `error: No packages matched the filter`

**Comment by Lxkas** [comment]
Most likely related to [#10322](https://github.com/oven-sh/bun/issues/10322) ?
After removing the scopes from the package names, the scripts run fine.

However, the single quotation marks also break it?
![image](https://github.com/oven-sh/bun/assets/24469918/716a82fc-a889-4dc9-9c21-1954e52a7b9b)
![image](https://github.com/oven-sh/bun/assets/24469918/c4c77364-1176-4caf-8f45-e674b9196577)
![image](https://github.com/oven-sh/bun/assets/24469918/3fc499a4-acb7-4134-b657-16116060bf89)

I'm on Windows 10, build 19045.4291

**Comment by wesleycoder** [comment]
Ohh, yeah, for sure.
Tested the workaround on #10322 on the sample repo and my other projects and it seems to work without the scopes.
I haven't noticed that before, because all my projects have scopes.

I'll be closing this issue in favor of keeping it centralized on #10322 which is already focused on this.

Thanks @Lxkas, this has helpful!
