### ISSUE TITLE
Support `#!`

### ISSUE THREAD

**Issue by 343max** [oven-sh/bun#1038]
### What is the problem this feature will solve?

In order to write Shellscripts using bun it would be helpful scripts would support the shebang `!#` syntax.

### What is the feature you are proposing to solve the problem?

Writing shell scripts using bun by adding `#!/usr/bin/env bun run` as the first line

### What alternatives have you considered?

running `bun run script.ts` manually

**Comment by xhyrom** [comment]
![image](https://user-images.githubusercontent.com/56601352/183656775-f012f555-776e-49d2-a0f0-0da6e46d35ec.png)

**Comment by 343max** [comment]
Thank you!

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/1038

**Comment by Jarred-Sumner** [comment]
Fixed in 83e4d04ce70c36e8461afe6f9f9c5547f5221fa2
