### ISSUE TITLE
Bun crashes when generating coverage report.

### ISSUE THREAD

**Issue by RonaldBunk** [oven-sh/bun#10395]
### How can we reproduce the crash?

Just run `bun test --coverage`

### Relevant log output

```shell
bun test v1.1.4 (accfff02)

src\lib\filter.test.ts:

src\lib\map.test.ts:

src\lib\reduce.test.ts:

src\lib\sort.test.ts:
------------------------|---------|---------|-------------------
File                    | % Funcs | % Lines | Uncovered Line #s
------------------------|---------|---------|-------------------

============================================================
Bun v1.1.4 (accfff02) Windows x64
Args: "C:\Users\Azoraqua\.bun\bin\bun.exe", "test", "--coverage"
Features: tsconfig(2)
Elapsed: 26ms | User: 15ms | Sys: 15ms
RSS: 111.84MB | Peak: 111.84MB | Commit: 0.16GB | Faults: 27527

panic(main thread): attempt to cast negative value to unsigned integer
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

https://bun.report/1.1.4/waccfff01gtrqIgp17H+08isCk//6Eovm8E+lqsF69Korqo1CCa\KERNEL32.DLL63yECU\ntdll.dllwk1WA0eNoVyMEJACAMA8BVslrRUApaRaPzi/c8k9inoIFiW0i6KS5xrR3+PrnDkxWRonM95EETDA

**Comment by zapteryx** [comment]
+1, experiencing this crash as well

**Comment by sebastianbuechler** [comment]
+1 for windows setup

**Comment by dylan-conway** [comment]
minimum repro
```js
// test.test.js
async function foo() {}
```

**Comment by RonaldBunk** [comment]
> minimum repro
> 
> ```js
> // test.test.js
> async function foo() {}
> ```

If that's all to cause the error, something seems terribly wrong with the coverage feature. Hope it gets fixed quickly, seems like an useful feature.

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/10836

**Comment by Jarred-Sumner** [comment]
We will fix this, but please follow along in https://github.com/oven-sh/bun/issues/10836 to track this issue
