### ISSUE TITLE
Using tilde (~) to cd in a Bun script with `$` not working

### ISSUE THREAD

**Issue by aryzing** [oven-sh/bun#10415]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

When using changing directory to a path beginning with tilde `~`, the directory is always switched to the home directory and ignores sub paths,

```ts
import { $ } from "bun";

await $`cd ~ && pwd`;              // /home/user
await $`cd ~/with/subpath && pwd`; // also /home/user
```

### What is the expected behavior?

The second `cd` above should set the pwd to `/home/user/with/subpath`

### Additional information

Using `$HOME` instead of `~` works just fine.

**Comment by ghiscoding** [comment]
possible open PR #9017

**Comment by zackradisic** [comment]
This was added in #10981
