### ISSUE TITLE
Add custom message to `expect` function of `bun:test` module

### ISSUE THREAD

**Issue by abhi3700** [oven-sh/bun#10414]
### What is the problem this feature would solve?

How can i translate this `chai` package based assertion:
```ts
assert(amount.lte(currentBalance), "Insufficient WTSSC in sender's balance")
```
to that of bun.

I have been able to write this using `bun:test`, but couldn't find any place to add the error message :disappointed: .
```ts
expect(amount.lte(currentBalance)).toBe(true)
```

### What is the feature you are proposing to solve the problem?

Add custom message to `expect`. The structure of this could look like this:

```ts
expect(amount.lte(currentBalance)).toBe(true).message("Insufficient WTSSC in sender's balance")
```

### What alternatives have you considered?

I am using `chai` package for this work. Here is a code snippet:
```ts
import { assert } from 'chai'

assert(amount.lte(currentBalance), "Insufficient WTSSC in sender's balance")
```

**Comment by riywo** [comment]
I guess you're looking for the second argument of `expect()`?
https://github.com/oven-sh/bun/blob/bun-v1.1.22/packages/bun-types/test.d.ts#L492-L498

**Comment by abhi3700** [comment]
> I guess you're looking for the second argument of `expect()`? https://github.com/oven-sh/bun/blob/bun-v1.1.22/packages/bun-types/test.d.ts#L492-L498

Yes! I see.
