### ISSUE TITLE
Bun install failed with overflow when collaborating with multi-platform team (macOS + Windows)

### ISSUE THREAD

**Issue by 44kia244** [oven-sh/bun#10427]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Create a bun project on macOS
2. Create a lint-fix github workflow, test it both locally and github (Linux)
3. Using a Windows-based PC, clone that repository
4. Run `bun install` on Windows PC
5. Commit to GitHub, let it run workflow

### What is the expected behavior?

[2] Both environment should be working fine without any issues
[4] Expect `bun install` to be successfully installed in the same way as macOS and Linux
[5] Expect nothing changed

### What do you see instead?

- At [4], bun is crashing with integer overflow. Then I delete `bun.lockb` and it working again.
- At [5], bun is re-creating the `bun.lockb` again

--------

## From [4] (Windows)
```
bun install v1.1.4 (fbe2fe0c)

uh-oh: integer overflow
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.4 (fbe2fe0c) Windows x64
InstallCommand: bunfig
Elapsed: 21ms | User: 15ms | Sys: 0ms
RSS: 56.16MB | Peak: 56.16MB | Commit: 100.27MB | Faults: 13887
----- bun meta -----

0   00007FF644E02588
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 26824 panic: integer overflow
???:?:?: 0x7ff643d0ab74 in ??? (bun.exe)
???:?:?: 0x7ff6439317c3 in ??? (bun.exe)
???:?:?: 0x7ff643966a3c in ??? (bun.exe)
???:?:?: 0x7ff6439654c1 in ??? (bun.exe)
???:?:?: 0x7ff643a1fd4e in ??? (bun.exe)
???:?:?: 0x7ff643741603 in ??? (bun.exe)
???:?:?: 0x7ff646304c63 in ??? (bun.exe)
???:?:?: 0x7ffa92bb257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa941aaa47 in ??? (ntdll.dll)
```

## From [5] (GitHub Workflow Linux)
```
bun install v1.1.4 (fbe2fe0c)
error parsing lockfile: BufferOverflow
ignoring lockfile
 Resolving dependencies
 Resolved, downloaded and extracted [42[16](https://github.com/my-org/my-repo/actions/runs/9999999999/job/99999999999#step:7:17)]
 Saved lockfile
```

### Additional information

- I'm experiencing this since my team start using bun around the day that Bun for Windows has released.
- My system locale is not `en-US`, but it is `th-TH`
- GitHub actions use action `oven-sh/setup-bun@v1` to setup
- macOS is from my colleague, using M1-based MacBook Pro, but OS version is not known
- The machine that's running GitHub workflow is the default linux one, nothing special
- I'm using GCP artifact registry to store some of private dependencies, there's a script for converting `.npmrc` to `bunfig.toml` with `[install.scopes]` and `"@my-org" = { url = "https://asia-southeast1-npm.pkg.dev/.....", token = "ya29..." }`

**Comment by Jarred-Sumner** [comment]
@44kia244 can you run `bun upgrade --canary` and then upload the crash report? that will help us figure out where it's crashing

**Comment by 44kia244** [comment]
> @44kia244 can you run `bun upgrade --canary` and then upload the crash report? that will help us figure out where it's crashing

```
Bun v1.1.5 ([`22a289e`](https://github.com/oven-sh/bun/tree/22a289e2726f9df8e115247a30116c3cd183d0df)) on windows x86_64 [InstallCommand]

**panic**: integer overflow

- [`lockfile.zig:5588`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/install/lockfile.zig#L5588): `load`
- [`lockfile.zig:229`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/install/lockfile.zig#L229): `loadFromBytes`
- [`install.zig:10315`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/install/install.zig#L10315): `installWithManager`
- [`filter_run.zig:423`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/cli/filter_run.zig#L423): `install`
- [`cli.zig:1437`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/cli.zig#L1437): `start`
- [`cli.zig:61`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/cli.zig#L61): `start`
- [`exe_common.inl:78`](https://github.com/oven-sh/bun/blob/22a289e2726f9df8e115247a30116c3cd183d0df/src/src/startup/exe_common.inl#L78): `invoke_main`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

Features: bunfig

<!-- from bun.report: r9KsywtYNFELfeRUe6KP -->
```

**Comment by Jarred-Sumner** [comment]
Very helpful, thank you

**Comment by 44kia244** [comment]
After trying, it seems weird.

Case 1: Create project in WSL (just simple `express`, `@google-cloud/storage`, and 1 internal dependency) => Installing back and forth between windows (`v1.1.5-cacary.1 (22a289e2)`) and WSL (`v1.1.4 (fbe2fe0c)`) are working fine.

Case 2: Try to copy dependencies (and dev) from a larger project => Installing in WSL is fast, but it very slow on Windows (511.42s to be finished), and no error

Case 3: Using my main project, try deleting `bun.lockb` and let GitHub Actions rebuild it (`v1.1.4 (fbe2fe0c)`) => Installing on Windows cause an error `error parsing lockfile: BufferOverflow`

I'd like to try creating project using macOS (Apple Silicon) again, but I don't have it on hand for now.

-----
Update 1: The very-slow installing on Windows seems to be caused by the company-installed antivirus.
Update 2: Using the main project, I tried deleting `bun.lockb` and run `bun install` again using bun v1.1.4 on macOS, then transfer to Windows (excl. `node_modules`) and run `bun install` again. Everything working fine.
Update 3: the `error parsing lockfile: BufferOverflow` I mentioned at the issue itself is caused by `.gitattributes` configuration that normalize all text files line ending to `LF` (`* text eol=lf`). Adding configuration from [documentation](https://bun.sh/docs/install/lockfile#how-do-i-git-diff-bun-s-lockfile) seems to solve the issue.
Update 4: Using same configuration from Update 3 without additional configuration from documentation, running `bun install` from linux, then commit to git, then clone on windows and run `bun install` make it error `uh-oh: integer overflow`. Copy the `bun.lockb` manually without using git make it works, so it is the same thing as the Update 3 and can be solved in the same way.

**Comment by 44kia244** [comment]
Closing this issue as it is actually caused by `.gitattributes` configuration. Using `* text eol=lf` alone will corrupt the `bun.lockb` file.
