### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by nicklvh** [oven-sh/bun#10436]
### How can we reproduce the crash?

run bun src/index.ts in my project

### Relevant log output

```shell
============================================================
Bun v1.1.5 (ab79940e) Windows x64
Args: "C:\Users\iamni\.bun\bin\bun.exe", "."
Features: Bun.stdin(2) dotenv fetch transpiler_cache(6) tsconfig(4) WebSocket 
Builtins: "bun:main" "node:buffer" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:net" "node:os" "node:path" "node:perf_hooks" "node:stream" "node:string_decoder" "node:timers" "node:timers/promises" "node:tls" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws" 
Elapsed: 940ms | User: 281ms | Sys: 109ms
RSS: 0.22GB | Peak: 0.22GB | Commit: 0.26GB | Faults: 54890

panic(main thread): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.5 ([#10417](https://github.com/oven-sh/bun/pull/10417)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2617`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/uws.zig#L2617): `run`
- [`event_loop.zig:1464`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/bun.js/event_loop.zig#L1464): `waitForPromise`
- [`javascript.zig:1149`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/bun.js/javascript.zig#L1149): `waitForPromise`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/bun.js/bindings/shimmer.zig#L186): `cppFn`

Features:

**Comment by cirospaciari** [comment]
Fixed in canary `v1.1.22` if is happening after `bun upgrade --canary` feel free to reopen
