### ISSUE TITLE
[Bug] Bun crashing on `import React = require("react")`

### ISSUE THREAD

**Issue by coffeeispower** [oven-sh/bun#1045]
This bug is happening on version 1.8.0 of bun
```ts
import React = require("react"); // CRASH
```
```
SegmentationFault at 0x3700008003000000


----- bun meta -----
Bun v0.1.8 Linux x64 #1 SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:06 +0000
RunCommand: 
Elapsed: 88ms | User: 12ms | Sys: 27ms
RSS: 67.11MB | Peak: 26.57MB | Commit: 67.11MB | Faults: 111
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by xhyrom** [comment]
Next time, use bug template

**Comment by that-ambuj** [comment]
I think the commonJS syntax is :
`const DefaultExport = require('package')`

Or more commonly used ESmodule one in React :
`Import React from 'react'`

**Comment by coffeeispower** [comment]
it's an old typescript thing. and visual studio code still does that, but even if won't be implemented, it shouldn't EVER segfault. Segfaults are bugs.

**Comment by coffeeispower** [comment]
Great!

**Comment by that-ambuj** [comment]
So is that unexpected behaviour or wrong syntax? I only have experience with javascript.
