### ISSUE TITLE
bun --filter ignores exit code of child scripts

### ISSUE THREAD

**Issue by iJigg** [oven-sh/bun#10452]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```bash
  zsh: bun --filter './packages/fail' test
      fail test $ bun run index.ts
      │ Fail!
      └─ Exited with code 1
  zsh: $?
  zsh: command not found: 0
```

### What is the expected behavior?

If any child scripts fails, I would expect bun --filter to do the same.

Eg. running tests in multiple workspaces give false positives 

### What do you see instead?

bun --filter ignores child script exit codes and always exits successfully

### Additional information

Minmal reproduction: https://github.com/iJigg/bun-filter-exitcode

**Comment by Jarred-Sumner** [comment]
This is fixed in the next version of Bun

to get it now, run `bun upgrade --canary`
