### ISSUE TITLE
Support `dd-trace`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#10468]
This issue tracks supporting DataDog's `dd-trace`, which is currently spread across a few different issues.

Known blockers:
- `node:dgram` #1630 
- `Module._resolveLookupPaths` #8839 
- `Module._findPath`-  no issue for this one yet

`Module._resolveLookupPaths` and `Module._findPath` are necessary to allow dd-trace's monkey-patching [require-in-the-middle](https://github.com/DataDog/dd-trace-js/blob/0f36e48775b1fe47ee4de18eeffae6cf3ac761aa/packages/dd-trace/src/ritm.js#L53-L147)

As of Bun v1.1.4, calling `init` on `dd-trace` throws this error:
```js
❯ bun server.js
[bun] Warning: async_hooks.createHook is not implemented in Bun. Hooks can still be created but will never be called.
[bun] Warning: async_hooks.executionAsyncResource is not implemented in Bun. It returns a reference to process.stdin every time.
110 |
111 |       hooks = moduleHooks[name]
112 |       if (!hooks) return exports // abort if module name isn't on whitelist
113 |
114 |       // figure out if this is the main module file, or a file inside the module
115 |       const paths = Module._resolveLookupPaths(name, this, true)
                          ^
TypeError: Module._resolveLookupPaths is not a function. (In 'Module._resolveLookupPaths(name, this, !0)', 'Module._resolveLookupPaths' is undefined)
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/dd-trace/packages/dd-trace/src/ritm.js:115:21
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/express/lib/express.js:15:5
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:21
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/express/index.js:11:8
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:21
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/src/app.js:3:7
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:21
      at /Users/jarred/Build/trace-examples/javascript/node/microservices/auth/server.js:5:7
```

The warnings are potentially relevant as well, but we haven't gotten far enough to see if they cause issues yet. Also, their ESM hooks won't work at all.

cc @bengl

**Comment by Koka** [comment]
I have a tiny bit of experience setting up dd-trace on Bun, hope this helps a bit.

I've tried to run dd-trace on Bun and succeeded to the some extent through monkey-patching dd-trace (see my gist at the end of https://github.com/DataDog/dd-trace-js/issues/3749).

No metrics would be sent as `dgram` is absent, but I'm able to send APM trace spans manually using dd-trace API (as automatic instrumentation doesn't work on Bun apparently) and see them in Datadog.

Things I had to fix/monkey-patch:

1. `net.BlockList` - Apparently it's missing in Bun, and dd-trace has it's own shim, but it doesn't play well with fake Node version detection
2. Disable dd-trace custom metrics module entirely as it relies on UDP
3. Disable `appsec` module in dd-trace config (whatever it is, it's just crashing)
4. Declare following datadog module as external to Bun bundler (and NOT adding them to package.json):

```
'@datadog/native-metrics',
'@datadog/pprof',
'@datadog/native-appsec',
'@datadog/native-iast-taint-tracking',
'@datadog/native-iast-rewriter',
```

**Comment by Jarred-Sumner** [comment]
@paperdave in  #10568 + @gvilums in #1630 fixed this

dd-trace works (at least in an Express hello world app) in Bun v1.1.6. 

I don't think the ESM import hook will work.

**Comment by hpx7** [comment]
dd-trace is causing issue for me in Bun 1.1.8:

```ts
import { MongoClient, ServerApiVersion } from "mongodb";
import ddtrace from "dd-trace";

ddtrace.init({ logInjection: true }); // only works if this is commented out

const mongoUri = process.env.MONGO_URI ?? "mongodb://localhost:27017";
console.log("Connecting to mongo...", mongoUri);
const client = new MongoClient(mongoUri, { serverApi: ServerApiVersion.v1 });
await client.connect();
console.log("Connected to mongo");
```

this is the error I get:
```
error: Authentication failed.
 code: "18"

      at new MongoError (/Dev/bun-test/node_modules/mongodb/lib/error.js:97:9)
      at new MongoServerError (/Dev/bun-test/node_modules/mongodb/lib/error.js:147:9)
      at onMessage (/Dev/bun-test/node_modules/mongodb/lib/cmap/connection.js:202:26)
      at processIncomingData (/Dev/bun-test/node_modules/mongodb/lib/cmap/message_stream.js:124:9)
      at _write (/Dev/bun-test/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
      at writeOrBuffer (node:stream:2611:53)
      at node:stream:2594:79
      at ondata (node:stream:2110:43)

Bun v1.1.8 (macOS arm64)
```

**Comment by chin2km** [comment]
Is there any example or documentation about how dd-trace works with Bun.
Automatic instrumentation and custom instrumentation doesnt work in bun as it does in node.

any help is highly appreciated 🙏
