### ISSUE TITLE
On Windows, module resolver does not handle junctions or symlinks correctly

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#10469]
On Windows, Bun's module resolver does not detect correctly that a junction is a directory. We think it is a file. We try to read it from a file. And the code for reading files doesn't expect to receive a directory, causing it to return `Unexpected`.

Related issues:
- https://github.com/oven-sh/bun/issues/10013
- https://github.com/oven-sh/bun/discussions/10172
- #10125

**Comment by Humorist7475** [comment]
Can we please prioritize this? Monorepos basically just don't work at all on Windows.

**Comment by paperdave** [comment]
interesting

<img width="1458" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/473f0195-6283-460a-b72f-cdf282543b4a">
