### ISSUE TITLE
add bun -v for version

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#10480]
### What is the problem this feature would solve?

`bun -v` is an invalid argument

### What is the feature you are proposing to solve the problem?

add `bun -v`

### What alternatives have you considered?

nothing, because what I am working with uses `-v` and not `--version`

**Comment by Electroid** [comment]
What platform are you seeing this on? Also what is the output of `bun --revision`?

**Comment by Polygons1** [comment]
the revision is 1.1.4+fbe2fe0c3 and I am seeing this in a Python web framework named Reflex. I am on macOS

**Comment by paperclover** [comment]
this works on all platforms:

<img width="300" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/792aed87-74fa-4d74-a845-3c4c4fb46050">

the issue you are facing must be some bug in however you are spawning bun to get the version. note that `bun hello.js -v` will pass `-v` to the script.

**Comment by Polygons1** [comment]
it was in the `node` executable that bun dropped that is equivalent to `bun run`
