### ISSUE TITLE
Crash on bun install --frozen-lockfile in Docker on linux

### ISSUE THREAD

**Issue by Fxlr8** [oven-sh/bun#10490]
### How can we reproduce the crash?

The problem is probably related to child_process spawn. I had another but similar crash error on Bun 1.1.4 when Bun tried to run postinstall jobs. I updated base container to canary and got kernel panic. I will provide logs for both crashes.

The problem happens when I try to build a Dockerfile in GitLab CI pipeline.
Everything is fine when built on M1 MacBook Pro

```Dockerfile
FROM oven/bun:canary as base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install

RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile
```

Sorry, can't provide a full reproduction right now.

### Relevant log output

```shell
# Bun canary crash

#9 [install 3/7] RUN cd /temp/dev && bun install --frozen-lockfile
#9 0.528 bun install v1.1.5 (ab79940e)
#9 0.531  Resolving dependencies
#9 0.726  Resolved, downloaded and extracted [2]
#9 2.305 ============================================================
#9 2.305 Bun v1.1.5 (ab79940e) Linux x64 (baseline)
#9 2.305 Args: "bun", "install", "--frozen-lockfile"
#9 2.305 Features: extracted_packages(1502) lifecycle_scripts(2) spawn(2) 
#9 2.305 Elapsed: 1781ms | User: 1289ms | Sys: 2456ms
#9 2.305 RSS: 0.74GB | Peak: 0.39GB | Commit: 0.74GB | Faults: 0
#9 2.305 
#9 2.305 panic(main thread): This shouldn't happen
#9 2.305 oh no: Bun has crashed. This indicates a bug in Bun, not your code.

# Bun 1.1.4 crash

#9 6.914 chrome-headless-shell (123.0.6312.122) downloaded to /temp/dev/.cache/chrome-headless-shell/linux-123.0.6312.122
#9 10.05 Chrome (123.0.6312.122) downloaded to /temp/dev/.cache/chrome/linux-123.0.6312.122
#9 10.05 [PackageManager] waiting for 1 tasks
#9 10.05 [Scripts] Starting scripts for "puppeteer"
#9 10.05 error: Failed to run postinstall script from "puppeteer" due to
#9 10.05 ECHILD: No child processes (waitpid())
#9 ERROR: executor failed running [/bin/sh -c cd /temp/dev && bun install --verbose --frozen-lockfile]: runc did not terminate sucessfully
------
 > [install 3/7] RUN cd /temp/dev && bun install --verbose --frozen-lockfile:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c cd /temp/dev && bun install --verbose --frozen-lockfile]: runc did not terminate sucessfully
```

### Stack Trace (bun.report)

Bun v1.1.5 ([#10417](https://github.com/oven-sh/bun/pull/10417)) on linux x86_64_baseline [InstallCommand]

**panic**: This shouldn't happen

- [`env_loader.zig:245`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/env_loader.zig#L245): `src.env_loader.Loader.getNodePath`
- [`output.zig:364`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/output.zig#L364): `src.cli.run_command.RunCommand.configureEnvForRun`
- [`string_immutable.zig:905`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/string_immutable.zig#L905): `src.install.install.PackageManager.init__anon_83142`
- [`sys.zig:2654`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/sys.zig#L2654): `src.install.install.PackageManager.init__anon_83142`
- [`hash_map.zig:0`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/hash_map.zig#L0): `src.install.lockfile.Package.parseWithJSON__anon_316008`
- [`Mutex.zig:161`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/Thread/Mutex.zig#L161): `Progress.log__anon_289802`
- [`install.zig:5015`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/install/install.zig#L5015): `src.install.install.PackageManager.processExtractedTarballPackage__anon_289743`
- [`x86_64.zig:0`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/deps/zig/lib/std/os/linux/x86_64.zig#L0): `src.output.prettyWithPrinterFn__anon_289745`
- [`multi_array_list.zig:200`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/multi_array_list.zig#L200): `src.install.lockfile.cleanWithLogger__anon_82076`
- [`install.zig:10183`](https://github.com/oven-sh/bun/blob/ab79940e6a621b902589016d58bec92e33fdebb6/src/install/install.zig#L10183): `src.install.install.PackageManager.installPackages__anon_82083`

Features:

**Comment by Jarred-Sumner** [comment]
cc @paperdave, the top frame of the stack trace was wrong in the crash reporter. 

It was really pointing to this line: 

https://github.com/oven-sh/bun/blob/a64554bba65956c689a74e9e7ac45ced481c4c46/src/bun.js/api/bun/process.zig#L324
