### ISSUE TITLE
Bun does not replace RegExp

### ISSUE THREAD

**Issue by teyfix** [oven-sh/bun#10508]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Bun does not replace positive lookbehind RegExp `/(?<=[,:] |TData = |<)(\w+(?:Error|Variables|Response))/g` when Node.js does but it does match. Also when I run the tests, it fails to check if matched array is equal to expected. It succeeds when i explicitly check item by item. 
You can reproduce the issue with this repository https://github.com/teyfik-on-it/bun-regex-match
Repository also has actions for node and bun that you can checkout to see the issue.

### What is the expected behavior?

It should replace the expression

### What do you see instead?

It does not replace the expression

### Additional information

All the required information is available in the repository.

**Comment by accountsosoci** [comment]
Any updates?

**Comment by ufukdev** [comment]
Still not solved?

**Comment by dylan-conway** [comment]
This is a bug in JSC. Filed a bug with a minified example https://bugs.webkit.org/show_bug.cgi?id=273254
