### ISSUE TITLE
Can't run react app on docker, says invalidPort

### ISSUE THREAD

**Issue by timam** [oven-sh/bun#1051]
### Version

0.1.5

### Platform

docker (jarredsumner/bun:edge)

### What steps will reproduce the bug?

1. Create a react app with bun `bun create react `.  My code is available [here ](https://github.com/timam/helloworld-bun/tree/react/reactapp)
2. Create a Dockerfile, [here is mine ](https://github.com/timam/helloworld-bun/blob/react/reactapp/Dockerfile)
3. docker build and run
```
$ docker build . -t react:03
$ docker run -it react:03 -p 8000:8000 /bin/bash
```

### How often does it reproduce? Is there a required condition?

All the time 

### What is the expected behavior?

It should show "Welcome to React!" page 

### What do you see instead?

docker run gives me following output, i was using -p flag with value 8080:8080

```
error: InvalidPort

–––– bun meta ––––
Bun v0.1.5 Linux x64 #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022
DevCommand: 
Elapsed: 0ms | User: 26ms | Sys: 5ms
RSS: 67.11MB | Peak: 11.15MB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

### Additional information

The behaviour is  consistent with port 3000.

Host machine has react installed, works fine over there.
```
reactapp# docker -v 
Docker version 20.10.12, build 20.10.12-0ubuntu4

reactapp# uname -a 
Linux ip-10-10-3-151 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by borislavvp** [comment]
I managed to run your solution with the following command: 

`docker run -it -p 8000:8000 react:03`

I think the `docker run` command requires you to specify the port binding before the image argument.

**Comment by timam** [comment]
Thanks !
