### ISSUE TITLE
[bun shell] support output directly on the terminal (inherits parent stdio)

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#10515]
### What is the problem this feature would solve?

<b></b>

### What is the feature you are proposing to solve the problem?

Add stdio option
```js
Bun.$`bun myscript.js`.inheritStdio()
// or zx style
Bun.$`bun myscript.js`.stdio('inherit', 'inherit', 'inherit')
```

**Comment by zackradisic** [comment]
By default the shell will use stdout, stderr, and stdin of the bun process. If this is not working, please open an issue, thank you!

**Comment by karlhorky** [comment]
> By default the shell will use stdout, stderr, and stdin of the bun process

Wonder if this should be more visibly documented on [the $ Shell docs page](https://bun.sh/docs/runtime/shell)

Currently the only mention of it appears to be [this short sentence](https://bun.sh/docs/runtime/shell#:~:text=By%20default%2C%20shell%20commands%20print%20to%20stdout.%20To%20quiet%20the%20output%2C%20call%20.quiet())

> By default, shell commands print to stdout. To quiet the output, call `.quiet()`

Maybe also including the keyword "inherit" and also mentioning stderr and stdin?
