### ISSUE TITLE
bunx command broken

### ISSUE THREAD

**Issue by wsrer** [oven-sh/bun#10512]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bunx cowsay "Hello world!"

### What is the expected behavior?
```
 ______________
< Hello world! >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```
### What do you see instead?
```
error: Script not found "cowsay"
```

**Comment by dylan-conway** [comment]
Fixed in #10362 and will be available in `v1.1.5`

**Comment by madbarron** [comment]
I'm seeing this bug in v1.1.12 on Windows 10.

**Comment by dylan-conway** [comment]
@madbarron could you open a new issue with the bunx command that is having this issue?

**Comment by madbarron** [comment]
@dylan-conway opened #11757
