### ISSUE TITLE
--max-http-header-size does not work

### ISSUE THREAD

**Issue by sean256** [oven-sh/bun#10525]
### What version of Bun is running?

1.1.4

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```sh
bun --max-http-header-size=200000 -e "const http = require('http'); console.log(http.maxHeaderSize)"
```

### What is the expected behavior?

It should log out `200000`

### What do you see instead?

`16384`

**Comment by CPTNB** [comment]
+1 here.  I can also repro this setting the header size directly on the http server object:

```ts
createServer(
  {
    maxHeaderSize: 200000,
  },
  app,
).listen(PORT, () => {
  log.info(`Http server started at http://localhost:${PORT}`);
```

Is there any way to increase header size? (bun version `1.1.12`)

**Comment by joshshowalter** [comment]
+1 on this, we're gonna have to eject and use node if we can't bump the maxHeaderSize 😢

**Comment by julianocomg** [comment]
+1. The max header size seems to be hard coded to 16384. But in practice it’s actually half of it.

**Comment by jftanner** [comment]
This issue just ate about three hours of dev time. 😭 

For now, my workaround is to use `npx tsx --env-file=.env src/app.ts` instead of `bun run src/app.ts`. ☹️

**Comment by Jarred-Sumner** [comment]
Support for the `--max-http-header-size` flag and the node:http global `maxHeaderSize` will land in Bun v1.1.27. This will not include the per-HTTP server option - it will be a global option.

We've also increased the default HTTP server header limit from 8 KB -> 16 KB.

**Comment by jftanner** [comment]
Would it be reasonable to throw an error if `maxHeaderSize` is set on a node:http or node:https server?

The silent nature of the problem is what made it so brutal for me. It was just `ERR_EMPTY_RESPONSE` in the browser with _nothing_ in my code. Even the `connect` event didn't fire. Having some kind of "you can't do that in Bun yet" error would have saved _hours_.
