### ISSUE TITLE
bun install is too slow

### ISSUE THREAD

**Issue by cjdxhjj** [oven-sh/bun#10538]
### What version of Bun is running?

1.1.4

### What platform is your computer?

windows 10

### What steps can reproduce the bug?

ng new xx
and then run the bun install, even i have install the ng deps, the second time it also very very slow
![image](https://github.com/oven-sh/bun/assets/5616997/ae93bfa3-28d5-4e6d-bfb4-49c1a3364c43)
the first time i run the bun install, 
![image](https://github.com/oven-sh/bun/assets/5616997/56c98da7-be55-47f7-b123-a26cec5f6f42)
the next time i run the bun install 
![image](https://github.com/oven-sh/bun/assets/5616997/b20996c4-7572-4f26-b7c6-2930d308ad39)
![image](https://github.com/oven-sh/bun/assets/5616997/e7fb0893-4eef-4c8b-9c63-55c9721d2336)
![image](https://github.com/oven-sh/bun/assets/5616997/73ca54fc-0965-4465-8e16-5d8f005aee6d)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/5616997/86a3fac4-aee7-494b-9804-c25d9d40b86d)

**Comment by cjdxhjj** [comment]
![image](https://github.com/oven-sh/bun/assets/5616997/29e598f5-f4dc-4420-95e4-8c11ac91cf18)

**Comment by ChalermpornPosoppitakwong** [comment]
me too.

**Comment by Jarred-Sumner** [comment]
I think this was fixed in [Bun v1.1.10](https://bun.sh/blog/bun-v1.1.10#2x-faster-uncached-bun-install-on-windows), where we made bun install faster on Windows. 

There were further improvements in Bun v1.1.11 with DNS caching and non-blocking sockets.

Please let us know what speed you're seeing now. if it's still slow, we'll re-open the issue.

**Comment by cjdxhjj** [comment]
![image](https://github.com/oven-sh/bun/assets/5616997/ebd45a30-f249-4a1e-a46f-7c397d3c8389)
![image](https://github.com/oven-sh/bun/assets/5616997/c911ede9-41de-488c-889d-10e2188897f5)
the install also very slow
the deps is very simple
![image](https://github.com/oven-sh/bun/assets/5616997/4c68d905-e6df-407d-a46c-e794173ecd62)

**Comment by cjdxhjj** [comment]
i remove the node_modules, and reinstall it took 110.17s
![image](https://github.com/oven-sh/bun/assets/5616997/daeb424c-cfc5-459c-b821-5f9b9cf3c8bf)

**Comment by cjdxhjj** [comment]
the first time install, it cost much time to dependency analysis

**Comment by cjdxhjj** [comment]
@Jarred-Sumner

**Comment by JungYeonHwi** [comment]
me too  same on the windows, any solutions ?
