### ISSUE TITLE
bun upgrade Error

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#10545]
### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64_baseline [UpgradeCommand]

Illegal instruction at address 0x7FF67B6B8831

- [`tccgen.c:4947`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L4947): `post_type`
- [`tccgen.c:5051`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/tinycc/tccgen.c#L5051): `post_type`
- [`Allocator.zig:314`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/mem/Allocator.zig#L314): `free`
- [`fmt.zig:661`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L661): `formatType`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`fmt.zig:583`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L583): `formatType`
- [`fmt.zig:659`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/fmt.zig#L659): `formatType`
- [`writer.zig:28`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/deps/zig/lib/std/io/writer.zig#L28): `print`
- `??`
- `??`

**Comment by Andres6936** [comment]
Same problem, this ouput of console:

```shellsession
PS C:\Users\Saturno> bun -v
1.1.3
PS C:\Users\Saturno> bun upgrade
Bun v1.1.5 is out! You're on v1.1.3

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.3 (2615dc74) Windows x64
UpgradeCommand:
Elapsed: 2366ms | User: 0ms | Sys: 46ms
RSS: 76.68MB | Peak: 76.68MB | Commit: 131.68MB | Faults: 18918
----- bun meta -----

0   00007FF6B2CE3E18
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 8344 panic: attempt to unwrap error
???:?:?: 0x7ff6b1907ae1 in ??? (bun.exe)
???:?:?: 0x7ff6b1905589 in ??? (bun.exe)
???:?:?: 0x7ff6b1908136 in ??? (bun.exe)
???:?:?: 0x7ff6b1914e38 in ??? (bun.exe)
???:?:?: 0x7ff6b1641603 in ??? (bun.exe)
???:?:?: 0x7ff6b41e3eb3 in ??? (bun.exe)
???:?:?: 0x7fff616a53df in ??? (KERNEL32.DLL)
???:?:?: 0x7fff6282485a in ??? (ntdll.dll)
```

**Comment by Bader-Idris** [comment]
If it was limited to this command, we can simply do a workaround by running the PowerShell bun installation cmdlet.

However, there are some other critical errors with primary commands such as `bun install` both globally and locally. I wish that the developers of bunjs would do some real-world testing on older workstations and PCs; it would be helpful.

**Comment by Abhinav1217** [comment]
Facing same issue

```
PS D:\Projects\tydei> bun upgrade
Bun v1.1.6 is out! You're on v1.1.3

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.3 (2615dc74) Windows x64
UpgradeCommand:
Elapsed: 4853ms | User: 140ms | Sys: 62ms
RSS: 77.44MB | Peak: 77.44MB | Commit: 131.68MB | Faults: 19100
----- bun meta -----

0   00007FF6FC713E18
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 9312 panic: attempt to unwrap error
???:?:?: 0x7ff6fb337ae1 in ??? (bun.exe)
???:?:?: 0x7ff6fb335589 in ??? (bun.exe)
???:?:?: 0x7ff6fb338136 in ??? (bun.exe)
???:?:?: 0x7ff6fb344e38 in ??? (bun.exe)
???:?:?: 0x7ff6fb071603 in ??? (bun.exe)
???:?:?: 0x7ff6fdc13eb3 in ??? (bun.exe)
???:?:?: 0x7fffe8a47343 in ??? (KERNEL32.DLL)
???:?:?: 0x7fffe8be26b0 in ??? (ntdll.dll)
PS D:\Projects\tydei>
```
