### ISSUE TITLE
[bun bun] Could not resolve: "bun"

### ISSUE THREAD

**Issue by rsc1975** [oven-sh/bun#1054]
### Version

0.1.8

### Platform

Linux 5.10.102.1-microsoft-standard-WSL2

### What steps will reproduce the bug?

```
// test-hash.ts
import { SHA256 } from "bun";

console.log(SHA256);
```

```sh
bun bun test-hash.ts
```

### What is the expected behavior?

A bundle creation without warnings

### What do you see instead?

```
$ bun bun src/test-hash.ts 
 41.32 KB JavaScript
        0 modules
        0 packages
 2     LOC parsed
      5ms elapsed
 Saved to ./node_modules.bun


warn: Could not resolve: "bun". Maybe you need to "bun install"?
import { SHA256 } from "bun";
                       ^
test-hash.ts:1:24 23
```
Why is this warning displayed ?

### Additional information

If I run the file, all works fine:

```sh
$ bun run src/test-hash.ts 
[0.03ms] "node_modules.bun" - 0 modules, 0 packages
SHA256 { byteLength: 32,  }
```

**Comment by xhyrom** [comment]
SHA256 is global in Bun, use:
```
const { SHA256 } = Bun
```

**Comment by rsc1975** [comment]
You are right, I used the import format suggested by VSCode.

**Comment by Jarred-Sumner** [comment]
This is a bug in `bun bun`

For now, you can run `bun bun --platform=bun`

**Comment by Electroid** [comment]
`bun bun` was changed in Bun v1.0, it is now an alias for bun build, which is Bun's new bundler. Because of that, this issue is no longer applicable.
