### ISSUE TITLE
fs.readFileSync throws error

### ISSUE THREAD

**Issue by lyuly** [oven-sh/bun#1055]
### Version

0.1.8

### Platform

Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

const fs = require('fs');
const line = fs.readFileSync('a.txt', 'utf-8').toString().split(/\r\n|\r|\n/);

### How often does it reproduce? Is there a required condition?

Everytime I try to use fs.readFileSync

### What is the expected behavior?

It should show the correct input to the given file.

### What do you see instead?

```js
const fs = require('fs');
const line = fs.readFileSync('a.txt', 'utf-8').toString().split(/\r\n|\r|\n/);
console.log(line);
```

```sh
SegmentationFault at 0x0000000000000000


----- bun meta -----
Bun v0.1.8 macOS x64 19.6.0
RunCommand: 
Elapsed: 14ms | User: 11ms | Sys: 9ms
RSS: 12.82MB | Peak: 12.82MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

```

**Comment by Jarred-Sumner** [comment]
Having a hard time reproducing this

Can you paste the contents of `a.txt`?

<img width="620" alt="image" src="https://user-images.githubusercontent.com/709451/184337823-363a5693-568e-4d2c-8cd2-de6fc2577ee5.png">

**Comment by zhuzilin** [comment]
@Jarred-Sumner I can repro on mac but not on linux:
```bash
% bun run ./readFile.js

SegmentationFault at 0x0000000000000000


----- bun meta -----
Bun v0.1.8 macOS x64 21.1.0
RunCommand: 
Elapsed: 11ms | User: 11ms | Sys: 8ms
RSS: 12.85MB | Peak: 12.85MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

zilinzhu@MacBook-Pro-3 javascript % lldb bun ./readFile.js
(lldb) target create "bun"
Current executable set to 'bun' (x86_64).
(lldb) settings set -- target.run-args  "./readFile.js"
(lldb) r
Process 55393 launched: '/Users/zilinzhu/.bun/bin/bun' (x86_64)
Process 55393 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001019be1d7 bun`JSC::JIT::JIT(JSC::VM&, JSC::CodeBlock*, JSC::BytecodeIndex) + 103
bun`JSC::JIT::JIT:
->  0x1019be1d7 <+103>: vmovaps %ymm0, 0x100(%rbx)
    0x1019be1df <+111>: vmovups %ymm0, 0x110(%rbx)
    0x1019be1e7 <+119>: testq  %r14, %r14
    0x1019be1ea <+122>: je     0x1019be1fa               ; <+138>
Target 0: (bun) stopped.
```

**Comment by coffeeispower** [comment]
Jarred made a mac optimization, this is the time that shortcuts destroy the code.

**Comment by lyuly** [comment]
@Jarred-Sumner  the a.txt is follow
```txt
[[2,-1],[2,2],[2,1],[2,0],[2,3]]
```

**Comment by zhuzilin** [comment]
@lyuly could you upgrade bun with `bun upgrade --canary`? This should have been fixed.

**Comment by lyuly** [comment]
@zhuzilin Follow your instruction, it  works fine. Thanks😆
