### ISSUE TITLE
Bun crashed with index out of bounds

### ISSUE THREAD

**Issue by OljasOmar** [oven-sh/bun#10565]
### How can we reproduce the crash?

bun install

### Relevant log output

```shell
PS C:\Users\olzha\OneDrive\Рабочий стол\devika\ui> bun install
bun install v1.1.5 (b257a309)
  🚚 vite... ============================================================
Bun v1.1.5 (b257a309) Windows x64
Args: "C:\Users\olzha\.bun\bin\bun.exe", "install"
Features: extracted_packages(171)
Elapsed: 20743ms | User: 468ms | Sys: 5125ms
RSS: 0.28GB | Peak: 0.28GB | Commit: 0.41GB | Faults: 80461

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.5/wi1b257a30AgQksitH66ntHu2smE0m60HwxllEu02iEo+3hE862tFql/Bu4IA0eNrLzEtJrVDILy1RyE9TSMovzUspBgBHeAcx
```

### Stack Trace (bun.report)

Bun v1.1.5 ([#10527](https://github.com/oven-sh/bun/pull/10527)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4872`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/install.zig#L4872): `processDependencyListItem`
- [`logger.zig:850`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/logger.zig#L850): `allocPrint`
- [`install.zig:5652`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/install.zig#L5652): `runTasks`
- [`install.zig:1145`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/install.zig#L1145): `name`
- [`event_loop.zig:2027`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/bun.js/event_loop.zig#L2027): `tick`
- [`install.zig:10795`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/install/install.zig#L10795): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1304`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/cli.zig#L1304): `which`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/b257a309772db2e9dfb745f97068aea6a32ca151/src/main.zig#L52): `main`

**Comment by dylan-conway** [comment]
This was fixed in #11763 and will be included in v1.1.13. You can try the fix in canary (`bun upgrade --canary`)
