### ISSUE TITLE
Bun not setting exception code when a module could not be found

### ISSUE THREAD

**Issue by coffeeispower** [oven-sh/bun#1058]
### Version

1.8.0

### Platform

Linux tiagodinis33-gitcoffee-72c3w3ziqur 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

run the following code:
```js
try {
 module = require("some_module_that_dowsnt_exist");
} catch (err) {
  assert(err.code !== "MODULE_NOT_FOUND")
}
```

### How often does it reproduce? Is there a required condition?

Always happens.

### What is the expected behavior?

The require function is supposed to throw and exception with the code "MODULE_NOT_FOUND" when it couldn't find the module

### What do you see instead?

The code is `undefined`

**Comment by coffee-is-power** [comment]
Any news here?

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/07e1a158e9a854286dabcec6cace0d048cf8fd85
