### ISSUE TITLE
Bug in `visibleUTF8WidthFn`

### ISSUE THREAD

**Issue by pfgithub** [oven-sh/bun#10584]
### What steps can reproduce the bug?

https://github.com/oven-sh/bun/blob/cc8cdf6c51e7729575924d101aa2cbaf0964fa5f/src/string_immutable.zig#L5812-L5819

It's trying to parse a utf-8 character with `bytes[i], bytes[1], bytes[2], bytes[3]` which only works when i is 0.

I'm not sure if there's a way to create a utf-8 string in bun to test this, but in zig on a string like "_字", it outputs 2 instead of 3 because it failed to parse the utf-8 codepoint and measured the replacement character instead.

### What is the expected behavior?

`bun.strings.visible.width.utf8("_字")` should return `3`

### What do you see instead?

`bun.strings.visible.width.utf8("_字")` returns `2`

**Comment by Jarred-Sumner** [comment]
Thank you. This can be reproduced with `console.table`.
