### ISSUE TITLE
bun upgrade fails on Windows 11

### ISSUE THREAD

**Issue by redraskal** [oven-sh/bun#10594]
### How can we reproduce the crash?

`bun upgrade` does not work on Windows 11 build 22621.3447.

The release will download and panic after failing to switch versions.

Also, this issue has persisted across multiple versions of Bun.

### Relevant log output

```shell
E:\>bun upgrade --canary
============================================================
Bun v1.1.6-canary.1 (829ac496) Windows x64
Args: "bun", "upgrade", "--canary"
Features: spawn
Elapsed: 6436ms | User: 15ms | Sys: 1046ms
RSS: 108.30MB | Peak: 108.30MB | Commit: 0.20GB | Faults: 34997

panic(main thread): TODO windows
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`829ac49`](https://github.com/oven-sh/bun/tree/829ac496126345b47a8deb9d206ce8d8b403ee70)) on windows x86_64 [UpgradeCommand]

**panic**: TODO windows

- [`c.zig:161`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/c.zig#L161): `copyFileZSlowWithHandle`
- [`upgrade_command.zig:861`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/cli/upgrade_command.zig#L861): `_exec`
- [`upgrade_command.zig:430`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/cli/upgrade_command.zig#L430): `exec`
- [`cli.zig:1762`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/cli.zig#L1762): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/cli.zig#L62): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/main.zig#L52): `main`
- [`exe_common.inl:78`](https://github.com/oven-sh/bun/blob/829ac496126345b47a8deb9d206ce8d8b403ee70/src/src/startup/exe_common.inl#L78): `invoke_main`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

Features: spawn

**Comment by Altro31** [comment]
I have had the same issue since a few versions ago

**Comment by ralphwest1** [comment]
I have the same issue.

Here is the output I get when I run `bun upgrade`

```sh
Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. All rights reserved.

C:\Users\RalphWest>bun -v
1.1.4

C:\Users\RalphWest>bun upgrade
Bun v1.1.8 is out! You're on v1.1.4

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.4 (fbe2fe0c) Windows x64
UpgradeCommand:
Elapsed: 2292ms | User: 31ms | Sys: 15ms
RSS: 79.95MB | Peak: 79.95MB | Commit: 0.14GB | Faults: 19719
----- bun meta -----

0   00007FF7F1C92588
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 10196 panic: attempt to unwrap error
???:?:?: 0x7ff7f08a3221 in ??? (bun.exe)
???:?:?: 0x7ff7f08a0e06 in ??? (bun.exe)
???:?:?: 0x7ff7f08a3876 in ??? (bun.exe)
???:?:?: 0x7ff7f08b02fc in ??? (bun.exe)
???:?:?: 0x7ff7f05d1603 in ??? (bun.exe)
???:?:?: 0x7ff7f3194c63 in ??? (bun.exe)
???:?:?: 0x7ffe2988257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe2b5eaa47 in ??? (ntdll.dll)
```

**Comment by Jarred-Sumner** [comment]
This specific issue iwth `copyFileZSlowWithHandle` was fixed in more recent versions of Bun. Please upgrade to Bun v1.1.12 or later. You may need to use the powershell script to install:

```powershell
powershell -c "irm bun.sh/install.ps1 | iex"
```
