### ISSUE TITLE
When generating a single executable for Windows, an error occurs on Mac and Linux: `error: Module not found "/$bunfs/root/<executable_name>"`.

### ISSUE THREAD

**Issue by myrlagksruf** [oven-sh/bun#10595]
### What version of Bun is running?

1.1.5+b257a3097

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64, Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

When building with `bun-windows-x64` as the target on a Windows environment, it executes properly. However, if I build with `bun-windows-x64` as the target on Mac or Linux and then run it on Windows, an error occurs: `error: Module not found '/$bunfs/root/<executable_name>'`.

Therefore, I checked the two executables built in the same way using a hex editor.

```text
< 060c4a00: 423a 2f7e 4255 4e2f 726f 6f74 2f74 6573  B:/~BUN/root/tes
---
> 060c4a00: 2f24 6275 6e66 732f 726f 6f74 2f74 6573  /$bunfs/root/tes
6341797c6341797
< 060c4a40: 0000 0000 0000 0001 aaaa aaaa aaaa aa4f  ...............O
---
> 060c4a40: 0000 0000 0000 0001 0000 0000 0000 004f  ...............O
```

`<` is build in window, `>` is build in other.

**Comment by michalCapo** [comment]
I got the same problem on Linux (debian12 if this matter). Cross compiling to windows target will produce ```error: Module not found "/$bunfs/root/<executable_name>"``` on windows.

## Code
```console.log('hello')```

**Comment by Jarred-Sumner** [comment]
Please run `bun upgrade --canary` and try again. I believe this was fixed by @dylan-conway last night.

**Comment by michalCapo** [comment]
Cannot confirm. Running ```bun build --compile --target=bun-windows-x64 test.ts``` after upgrading to canary will ends with this message:
```
   [3ms]  bundle  1 modules
error: Does this target and version of Bun exist?

404 downloading bun-windows-x64-v1.1.6 from https://registry.npmjs.org/@oven/bun-windows-x64/-/bun-windows-x64-1.1.6.tgz
```

Even using latest canary target ```bun build --compile --target=bun-windows-x64-1.0.21-canary.20240427.1 test.ts```  from ```https://registry.npmjs.org/@oven/bun-windows-x64/``` will end with this output:
```
error: Unsupported target "1.0.21" in "bun-windows-x64-1.0.21-canary.20240427.1"
```

**Comment by Jarred-Sumner** [comment]
@michalCapo I forgot that cross-compiling on a canary build chooses the latest version

the npm canary builds have the wrong version number

Can you try `bun build --compile --target=bun-windows-x64-v1.1.5`?

**Comment by michalCapo** [comment]
Not working for me. Also I double checked.
```
bun upgrade --canary
bun build --compile --target=bun-windows-x64-v1.1.5 test.ts
```
on windows I got ```error: Module not found '/$bunfs/root/<executable_name>'```

**Comment by infrahead** [comment]
Same issue (or closely related?) going the other way.  Trying Windows v1.1.6 to cross-compile to Linux... `bun build --compile --target=bun-linux-x64 ./index.ts` generates the binary, but when trying to execute on Linux get `error: Module not found "B:/~BUN/root/."`  

The source file is a simple test:
```
console.log(`Hello from ${navigator.userAgent}! (${process.platform}-${process.arch})`)
```

Have tried changing paths in the build command to be `index.ts` and  `.\index.ts` but get same error, but with `B:/~BUN/root/index` (thought might be related to https://github.com/oven-sh/bun/issues/9852)

**Comment by saade** [comment]
i can confirm this still occurs on canary. I'm on MacOS Arm64 cross-compiling to Windows x64.

**Comment by roja** [comment]
I am hitting the same issues when cross compiling for --target=bun-linux-arm64 and running the executable under systemd

`Failed to locate executable /$bunfs/root/<executable_name>: No such file or directory`

**Comment by gvilums** [comment]
#10751 should contain the fix, can you try again with latest canary?

**Comment by infrahead** [comment]
@gvilums initial testing is successful!

Note to others, follow Jarred advice above to target a specific version (i.e. ` --target=bun-v1.1.6-linux-x64` vs ` --target=bun-linux-x64`) if testing with canary, otherwise will get...
```
error: Does this target and version of Bun exist?
404 downloading bun-linux-x64-v1.1.7 from https://registry.npmjs.org/@oven/bun-linux-x64/-/bun-linux-x64-1.1.7.tgz
```

**Comment by saade** [comment]
> @gvilums initial testing is successful!
> 
> Note to others, follow Jarred advice above to target a specific version if testing with canary, otherwise will get...
> 
> ```
> error: Does this target and version of Bun exist?
> 404 downloading bun-linux-x64-v1.1.7 from https://registry.npmjs.org/@oven/bun-linux-x64/-/bun-linux-x64-1.1.7.tgz
> ```

Can you share the command you ran? Its a 404 here.

EDIT: `--target=bun-v1.1.6-windows-x64` did the trick

**Comment by saade** [comment]
> #10751 should contain the fix, can you try again with latest canary?

It works!

**Comment by michalCapo** [comment]
Confirmed. It's working with last canary (1.1.7-canary.1+d66a4fc0f).

**Comment by gvilums** [comment]
Nice, I'll go ahead an close this issue then
