### ISSUE TITLE
heapSize returns 0 on linux

### ISSUE THREAD

**Issue by Smugaski** [oven-sh/bun#1059]
### Version

0.1.8

### Platform

Linux mail 5.18.6-1-default #1 SMP PREEMPT_DYNAMIC Thu Jun 23 05:46:18 UTC 2022 (5aa0763) x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

import { heapStats } from "bun:jsc"

console.log(heapStats().heapSize)

### How often does it reproduce? Is there a required condition?

Always returns 0.

### What is the expected behavior?

Return the heap size from JSC in bytes.

### What do you see instead?

0
![error](https://cdn.discordapp.com/attachments/1007071055321497670/1007459032845537280/IMG_5176.png)

**Comment by Jarred-Sumner** [comment]
The problem is that GC hasn't been run

As a temporary workaround, try running `Bun.gc()` first

**Comment by Jarred-Sumner** [comment]
Fixed some time ago
<img width="181" alt="image" src="https://github.com/oven-sh/bun/assets/709451/ae74df84-0e2d-43ed-bc6b-94b3cda8c5c5">
