### ISSUE TITLE
bunfig.toml coverage does not apper

### ISSUE THREAD

**Issue by KrOxYs** [oven-sh/bun#10621]
### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [TestCommand]

**panic**: attempt to cast negative value to unsigned integer

- [`Allocator.zig:310`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/mem/Allocator.zig#L310): `free`
- [`CodeCoverage.zig:252`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/CodeCoverage.zig#L252): `do`
- `??`
- [`CodeCoverage.zig:290`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/CodeCoverage.zig#L290): `generate`
- [`test_command.zig:327`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/test_command.zig#L327): `printCodeCoverage`
- [`cli.zig:1304`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1304): `which`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/main.zig#L52): `main`
- `_ZN9hashbrown3raw21RawTable$LT$T$C$A$GT$14reserve_rehash17h6e5acef1e33143a1E`
- ??? at `0x1257d` in /KERNEL32.DLL

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/10836

**Comment by Jarred-Sumner** [comment]
We will fix this, but please follow along in https://github.com/oven-sh/bun/issues/10836 to track this issue
