### ISSUE TITLE
error when use bun build express.ts --compile --minify --sourcemap --outfile dist/express

### ISSUE THREAD

**Issue by KrOxYs** [oven-sh/bun#10624]
### Relevant log output

```shell
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Program Files\nodejs\node_modules\bun\bin\bun.exe", "build", "express.ts", "--compile", "--minify", "--sourcemap", "--outfile", "dist/express"
Features: bunfig define dotenv tsconfig(9) 
Elapsed: 6791ms | User: 6125ms | Sys: 0ms
RSS: 120.21MB | Peak: 120.29MB | Commit: 0.22GB | Faults: 30391

panic(thread 3616): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`sourcemap.zig:443`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L443): `advance`
- [`sourcemap.zig:418`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L418): `advance`
- [`bundle_v2.zig:6365`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bundler/bundle_v2.zig#L6365): `generateChunkJS`
- [`output.zig:402`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/output.zig#L402): `flush`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

**Comment by Jarred-Sumner** [comment]
can you share the input code?

**Comment by Jarred-Sumner** [comment]
im able to reproduce a similar issue with the following:
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```
