### ISSUE TITLE
Bun::test documentation

### ISSUE THREAD

**Issue by lau1944** [oven-sh/bun#1062]
### What is the problem this feature will solve?

I try to use bun test to test my project, but could not find any docs.

### What is the feature you are proposing to solve the problem?

Write a bun::test docs

**Comment by xhyrom** [comment]
You can check https://github.com/oven-sh/bun/blob/main/test/wiptest/README.md for now

**Comment by lau1944** [comment]
Thanks

**Comment by Electroid** [comment]
Hi there, we've started to work on the official docs for Bun. This will indeed be there.
