### ISSUE TITLE
Can't execute scripts without extension

### ISSUE THREAD

**Issue by rsc1975** [oven-sh/bun#1063]
### Version

0.1.8

### Platform

Linux 5.10.102.1-microsoft-standard-WSL2

### What steps will reproduce the bug?

Create a file  `cli-tool` like:

```js
#!/usr/bin/env bun
console.log('ARGS:', process.arg); 
```
```sh
chmod +x cli-tool
./cli-tool
```

### What is the expected behavior?

No error

### What do you see instead?

An error happens:

```
error: Script not found "/home/.../cli-tool"
error "cli-tool" exited with 1 status
```

### Additional information

Same result calling : `bun run ./cli-tool `

**Comment by Jarred-Sumner** [comment]
Fixed in 83e4d04ce70c36e8461afe6f9f9c5547f5221fa2
