### ISSUE TITLE
confirm() is never true on Windows

### ISSUE THREAD

**Issue by infrahead** [oven-sh/bun#10643]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Ran into same thing I reported previously on Linux... https://github.com/oven-sh/bun/issues/5985

### What is the expected behavior?

returns true for `y`

### What do you see instead?

is always false, regardless of value

### Additional information

It does work (was fixed) on Linux

**Comment by paperclover** [comment]
without investigating, i am almost certain this is because a `\r` is included on the read data.

**Comment by ADTmux** [comment]
Hi, I would like to work on this!
