### ISSUE TITLE
panic(thread 22512): integer overflow, Bun has crashed. This indicates a bug in Bun, not your code. 

### ISSUE THREAD

**Issue by kouseki11** [oven-sh/bun#10645]
### Relevant log output

```shell
bun build express.ts --compile --minify --sourcemap --outfile dist/express
[0.00ms] ".env"
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Users\USER\.bun\bin\bun.exe", "build", "express.ts", "--compile", "--minify", "--sourcemap", "--outfile", "dist/express"
Features: bunfig define dotenv tsconfig(9) 
Elapsed: 8616ms | User: 7968ms | Sys: 15ms
RSS: 100.01MB | Peak: 100.28MB | Commit: 0.17GB | Faults: 25286       

panic(thread 22512): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.   

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.6/wb1e58d67bAgngggC+2v/Bil31K49t+Bk/3xKCa\KERNEL32.DLL63yECU\ntdll.dllwk1WA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD
```

### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`sourcemap.zig:443`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L443): `advance`
- [`sourcemap.zig:418`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/sourcemap/sourcemap.zig#L418): `advance`
- [`bundle_v2.zig:6365`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bundler/bundle_v2.zig#L6365): `generateChunkJS`
- [`output.zig:402`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/output.zig#L402): `flush`
- ??? at `0x1257d` in /KERNEL32.DLL
- ??? at `0x5aa48` in /ntdll.dll

**Comment by Jarred-Sumner** [comment]
Duplicate of #10624

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/10625
