### ISSUE TITLE
Get client's IP address

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#1065]
### What is the problem this feature will solve?

Same as [#518](https://github.com/oven-sh/bun/issues/518) 

### What is the feature you are proposing to solve the problem?
Using new interface `ConnInfo` as in [Deno's ConnInfo](https://deno.land/std@0.152.0/http/server.ts?s=ConnInfo) 

```js
Bun.serve({
    fetch(req: Request, con: ConnInfo) {
        return new Response(`Client IP: ${con.remoteAddr}`);
    }
})
```

**Comment by xhyrom** [comment]
There is no reason to have duplicate issues.

**Comment by Jarred-Sumner** [comment]
Closing as duplicate
