### ISSUE TITLE
`Bun.parseArgs` in typings is invalid

### ISSUE THREAD

**Issue by teidesu** [oven-sh/bun#10659]
### What version of Bun is running?

1.1.6-canary.1+7af0ed164

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```ts
const args = Bun.parseArgs(...)
```

when running, this errors because `parseArgs` is not in `Bun` namespace, but typescript doesn't show any errors.

### What is the expected behavior?

typescript errors that `parseArgs` is not in the `Bun` namespace

### What do you see instead?

it doesn't

### Additional information

https://github.com/oven-sh/bun/blob/fbbc20fe83383eb89e4f9979cd0d1750e2e5b8d3/packages/bun-types/bun.d.ts#L4784

**Comment by paperclover** [comment]
this was originally going to be an alias but it was decided against, but it seems the type definition for this was never removed.

**Comment by papidb** [comment]
Hi @paperdave, I don't think this problem doesn't exist anymore. 

I'm on version `1.1.22`
<img width="935" alt="image" src="https://github.com/user-attachments/assets/b51881c4-c79d-4b1f-933a-a23a12404ff4">

**Comment by SunsetTechuila** [comment]
fixed by #10777
