### ISSUE TITLE
`fetch` doesn't respect `redirect` option with `manual` value

### ISSUE THREAD

**Issue by 29decibel** [oven-sh/bun#1068]
### Version

0.1.8

### Platform

Darwin a1.local 22.0.0 Darwin Kernel Version 22.0.0: Mon Aug  1 06:32:26 PDT 2022; root:xnu-8792.0.207.0.6~26/RELEASE_ARM64_T8103 arm64

### What steps will reproduce the bug?

1. Create blank bun project with following code in `src/app.js`
```javascript
(async function () {
  const url =
    "https://click.convertkit-mail4.com/o8u8vovkk5hqhk6wwddfv/7qh7h8h075w7llfz/aHR0cHM6Ly93d3cuaW5kaWVoYWNrZXJzLmNvbS96YWNrYnJ1Y2UvaGlzdG9yeT91dG1fc291cmNlPWluZGllLWhhY2tlcnMtZW1haWxzJnV0bV9jYW1wYWlnbj1paC1uZXdzbGV0dGVyJnV0bV9tZWRpdW09ZW1haWw=";
  const result = await fetch(
    new Request(url, {
      redirect: "manual",
    })
  );
  console.log(result.status);
  console.log(result.headers.get("Location"));
})();

```

2. Execute this script
```bash
bun run ./src/app.js
```

### How often does it reproduce? Is there a required condition?

Every time

## Expected result (same as running `node src/app.js`):
```
302
https://www.indiehackers.com/zackbruce/history?utm_source=indie-hackers-emails&utm_campaign=ih-newsletter&utm_medium=email
```

## Actual result:
```
200
null
```

### Additional information

Same script when running in Node v18.4.0 gave us this `node src/app.js`:
```
302
https://www.indiehackers.com/zackbruce/history?utm_source=indie-hackers-emails&utm_campaign=ih-newsletter&utm_medium=email

```

**Comment by Electroid** [comment]
Implemented in 5854d395259f4084b1d66e9f12b54085f277527e
