### ISSUE TITLE
I was banned from discord for no reason...

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#10705]
Sorry to bother you guys, but I do not know where else could I complain about this

I just made a post on discord and got kicked... What did I do?

**Comment by xhyrom** [comment]
This is not the right place to complain about ban on discord server but since you're already complaining, what's your discord user id?

**Comment by ghost** [comment]
Sorry... Where is it?

levipires_99018

**Comment by xhyrom** [comment]
> Sorry... Where is it?
> 
> levipires_99018

You had ban for spamming mentions (5), probably by automod. Sorry for that case and please avoid doing that again, also, we don't actually have a place where you can complain about bans but I'll discuss it with team. I hope you can close this issue now 👍
