### ISSUE TITLE
Bun crash on Windows - panic(main thread)

### ISSUE THREAD

**Issue by neilsonnn** [oven-sh/bun#10709]
### Relevant log output

Same crash reproducable on 1.1.4, 1.1.6, and 1.1.7

### Stack Trace (bun.report)

Bun v1.1.7 ([`32bf5eb`](https://github.com/oven-sh/bun/tree/32bf5eb4441007bb2f39a8db29f9e4aafae06223)) on windows x86_64 [RunCommand]

**panic**: Expected boolean but found JSFunction

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/32bf5eb4441007bb2f39a8db29f9e4aafae06223/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/32bf5eb4441007bb2f39a8db29f9e4aafae06223/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/32bf5eb4441007bb2f39a8db29f9e4aafae06223/src/output.zig#L356): `panic`
- [`bindings.zig:5143`](https://github.com/oven-sh/bun/blob/32bf5eb4441007bb2f39a8db29f9e4aafae06223/src/bun.js/bindings/bindings.zig#L5143): `asBoolean`
- [`server.zig:4500`](https://github.com/oven-sh/bun/blob/32bf5eb4441007bb2f39a8db29f9e4aafae06223/src/bun.js/api/server.zig#L4500): `send`
- `??`
- *4 unknown/js code*

Features: Bun.stdout, dotenv, http_server, transpiler_cache, tsconfig

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/10710
