### ISSUE TITLE
Error creating a Bun + Svelte app

### ISSUE THREAD

**Issue by alexiusdevox** [oven-sh/bun#10737]
### How can we reproduce the crash?

bun create svelte@latest example

### Relevant log output

```shell
🚚 kleur [10/16] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "C:\Users\gabri\.bun\bin\bun.exe", "add", "create-svelte@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 938ms | User: 15ms | Sys: 62ms
RSS: 68.71MB | Peak: 68.71MB | Commit: 130.00MB | Faults: 17587

panic(thread 26652): Illegal instruction at address 0x7FF710845541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.6/eI1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA3u//Bi0qxwQ
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF648875541

- [`tccgen.c:4964`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4964): `post_type`
- [`tccgen.c:5046`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L5046): `post_type`
- [`math.zig:436`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/math.zig#L436): `mul`
- [`sort.zig:48`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/sort.zig#L48): `insertionContext`
- [`fmt.zig:1173`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/fmt.zig#L1173): `format`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x17344` in /KERNEL32.DLL
- ??? at `0x526b1` in /ntdll.dll

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.8 and try again. This was likely fixed by changes to the build system.

**Comment by alexiusdevox** [comment]
Resolved. Now it worked!
