### ISSUE TITLE
Timeout in benchmark

### ISSUE THREAD

**Issue by innerop** [oven-sh/bun#1073]
### Version

0.1.8

### Platform

Linux

### What steps will reproduce the bug?

Run this with n.= 4000

https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/algorithm/coro-prime-sieve/1.js

See results under coro-prime-sieve:

https://programming-language-benchmarks.vercel.app/javascript-vs-zig

### How often does it reproduce? Is there a required condition?

Every time, presuambly

### What is the expected behavior?

a list of prime integers

### What do you see instead?

timeout

### Additional information

I am just reporting this result from someone else's benchmarks after having searched the issues in this repo and confirmed that it had not been reported. 

I am thinking of adopting bun, so I have not tried it yet, but if it has a serious bug like this then I might wish to wait. I don't have the time right now to install bun to run the benchmark code in the link above but I figured you'd rather have this potential bug reported than not.

**Comment by zhuzilin** [comment]
just tried with my mac with v0.1.10. It won't timeout. The benchmark is actually comparing v8 vs jsc instead of node vs bun, because it's just javascript code. And the reason is probably jsc does not have good support for new js features.

**Comment by innerop** [comment]
I see. It says Bun specifically and provides the version as the previous release. Maybe it was some issue that was already fixed in the latest release. I would expect JSC to support generators. They are an ES6 feature. I thought JSC was crashing and bun swallowing the error. 

Will close since you can’t repro in latest.
