### ISSUE TITLE
Bun Crashing for some reason

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#10741]
### How can we reproduce the crash?

I just ran a **bun .** but its just sometimes it does it. 

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `quote_cmd_arg`
- `fs__open`
- `??`
- [`javascript.zig:829`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/javascript.zig#L829): `onUnhandledError`
- `JSC__JSValue__callCustomInspectFunction`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/bindings/shimmer.zig#L186): `cppFn`
- [`run_command.zig:1300`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/run_command.zig#L1300): `exec`
- [`cli.zig:1852`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1852): `start`

**Comment by Jarred-Sumner** [comment]
I think this was fixed in Bun v1.1.8

Can you let us know if you're still running into this issue? To upgrade, run `bun upgrade`.

**Comment by lassejlv** [comment]
Hey Jarred, i posted this before 1.1.8. Just forgot to close it. My code does not crash anymore!
