### ISSUE TITLE
Easy way to handle http request

### ISSUE THREAD

**Issue by lau1944** [oven-sh/bun#1075]
### What is the problem this feature will solve?

1. Easy to maintain rest api
2. Easy to write api
3. Easy to learn if people know nodejs and express.

### What is the feature you are proposing to solve the problem?

I writed a package called [bunrest](https://github.com/lau1944/bunrest), it's designed to solve this problem. It's an ExpressJs-like API for bun http server. It was built on top of bun. 

If the team likes this solution, I am able to write a sample on bun example dir and pr.

**Comment by Jarred-Sumner** [comment]
You're welcome to submit a PR with an example!
