### ISSUE TITLE
postinstall script from "full-icu" exited with 1

### ISSUE THREAD

**Issue by baphony** [oven-sh/bun#10765]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

bun i

bunfig.toml:
```
[install]
registry = { url = "https://...", token = "..." }
# Avoid patches to be applied on the Bun cache files
backend = "copyfile"

[install.lockfile]
print = "yarn"
```

### What is the expected behavior?

Not sure what's the status of Bun for internationalization but there is what NodeJS is doing:
https://github.com/nodejs/node/pull/3102/files

### What do you see instead?

```shell
bun install v1.1.6 (e58d67b4)
  🚚 jss... 53 |   } else {
54 |     icuver = process.config.variables.icu_ver_major // only get the major
55 |   }
56 |
57 |   if (!icuver) {
58 |     throw Error('Cannot determine Node’s ICU version!')
               ^
error: Cannot determine Node’s ICU version!
      at /home/bap/work/symphony/sfe-rtc/node_modules/full-icu/full-icu.js:58:11
      at /home/bap/work/symphony/sfe-rtc/node_modules/full-icu/postinstall.js:5:7

error: postinstall script from "full-icu" exited with 1
```

### Additional information

I am using Ubuntu in WSL2

node_modules/full-icu/full-icu.js:58:11
```
  if (process.versions.icu) {
    icuver = process.versions.icu // Thanks https://github.com/nodejs/node/issues/3089
  } else {
    icuver = process.config.variables.icu_ver_major // only get the major
  }

  if (!icuver) {
    throw Error('Cannot determine Node’s ICU version!')
  }
```
https://www.npmjs.com/package/full-icu

**Comment by dylan-conway** [comment]
We are missing `icu` (and `unicode`) on `process.versions`. This will be fixed when #10760 merges
