### ISSUE TITLE
Error using discordjs

### ISSUE THREAD

**Issue by Mrgaton** [oven-sh/bun#10772]
### How can we reproduce the crash?

its weird some times happends other dont

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `us_socket_raw_write`
- `??`
- `??`
- `quote_cmd_arg`
- `fs__open`
- `??`
- [`bun_js.zig:321`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun_js.zig#L321): `start`
- `JSC__JSValue__callCustomInspectFunction`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/bindings/shimmer.zig#L186): `cppFn`
- [`resolve_path.zig:1635`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/resolver/resolve_path.zig#L1635): `normalizeStringWindowsT`

**Comment by Mrgaton** [comment]
![image](https://github.com/oven-sh/bun/assets/68958481/2d7f6ba5-3edc-48f8-a88d-c485b4e9d182)

**Comment by cirospaciari** [comment]
Fixed in canary `v1.1.22` if is happening after `bun upgrade --canary` feel free to reopen

**Comment by Mrgaton** [comment]
THX
