### ISSUE TITLE
Bun crashes on Windows 2019 Datacenter and 2022 Standard

### ISSUE THREAD

**Issue by ewildee** [oven-sh/bun#10788]
## Installation steps
- Install  Visual C++ Redistributable (as instructed)
- Install Bun 1.1.6 on Windows 2019 Datacenter (version 1809) or Windows 2022 Standard (version 21H2) using the Powershell command from the homepage
- Open, as instructed, a new Powershell terminal (or cmd)
  
## Run/crash steps
- Crashes when running `bun repl` or `bun install`
  - Error: `ENOENT: Bun could not find a file, and the code that produces this error is missing a better error.`
- Crashes when running `bun .\test.js` (only containing a `console.log` line)
  - Error: `error: Module not found "C:\Users\Administrator\Desktop\bun-test\test.js"`
  - Happens with and without an accompanying `package.json` file
- Crashes when running `bun upgrade`
  - See the linked crash report (from the Windows 2019 installation)

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64_baseline [UpgradeCommand]

Illegal instruction at address 0x7FF655A05541

- [`tccgen.c:4886`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4886): `post_type`
- [`tccgen.c:4938`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4938): `post_type`
- [`Allocator.zig:193`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/mem/Allocator.zig#L193): `alignedAlloc`
- [`fmt.zig:594`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/fmt.zig#L594): `formatType`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`writer.zig:28`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L28): `print`
- `??`
- `??`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.8 and try again. Very likely has been fixed.
