### ISSUE TITLE
`bun run` not handling escaped quotes in package.json script

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#1079]

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/896

**Comment by xhyrom** [comment]
And.... you have old bun version

**Comment by invrainbow** [comment]
Oh yeah, but 0.1.8 didn't fix it either.

**Comment by Jarred-Sumner** [comment]
(accidentally re-opened, previous duplicate is the right issue)
