### ISSUE TITLE
Random crash using discord.js bot

### ISSUE THREAD

**Issue by malmz** [oven-sh/bun#10797]
### How can we reproduce the crash?

Create a minimal discord bot with discord.js (maybe also @sapphire/framework?). This error occured randomly after running for a few minutes. 

### Relevant log output

```shell
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Users\[redacted]\.bun\bin\bun.exe", "run", "src/index.ts"
Features: Bun.stderr Bun.stdin(2) Bun.stdout dotenv fetch(6) transpiler_cache(6) tsconfig_paths(2) tsconfig(4) WebSocket(2)
Builtins: "bun:main" "bun:sqlite" "node:buffer" "node:console" "node:events" "node:fs" "node:fs/promises" "node:http" "node:path" "node:string_decoder" "node:timers" "node:timers/promises" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws"
Elapsed: 1429263ms | User: 1062ms | Sys: 750ms
RSS: 0.14GB | Peak: 0.20GB | Commit: 0.22GB | Faults: 353052
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [RunCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/uws.zig#L2619): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/bindings/shimmer.zig#L186): `cppFn`
- [`run_command.zig:1402`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/run_command.zig#L1402): `exec`
- [`cli.zig:1746`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1746): `start`

**Comment by cirospaciari** [comment]
Fixed in canary `v1.1.22` if is happening after `bun upgrade --canary` feel free to reopen
