### ISSUE TITLE
Make `node:inspector` `url()` stub return `undefined` rather then throw

### ISSUE THREAD

**Issue by Dimava** [oven-sh/bun#10793]
### What is the problem this feature would solve?

`!!require('node:inspector').url()` is often used to determine the presence of inspector *and do nothing inspector-related if it is not active*

This is what OP of https://github.com/oven-sh/bun/issues/2445 did need to make [typedoc](https://github.com/TypeStrong/typedoc) work

### What is the feature you are proposing to solve the problem?

> ### inspector.url()[#](https://nodejs.org/api/inspector.html#inspectorurl)
> Returns: [\<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [\<undefined>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Undefined_type)
> Return the URL of the active inspector, or undefined if there is none.

According to documentation, returning `undefined` if there is no active inspector is correct, and as Bun doesn't have inspector implementation, the function should always return `undefined`.

https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/js/node/inspector.ts#L14-L16

change to
```diff
  function url() { 
-  throwNotImplemented("node:inspector url", 2445);
+  // This is a stub! Inspector is not implemented, so the url is always `undefined`, as per https://nodejs.org/api/inspector.html#inspectorurl
+  return undefined;
  } 
```

### What alternatives have you considered?

```ts
// well, noone did expect inspector.url to error
function safeHasInspector() {
  try { return !!inspector.url() } catch(err) { return false }
}
```

**Comment by Jarred-Sumner** [comment]
i like this

we could even return the real inspector URL if bun was launched via `bun --inspect`

**Comment by Dimava** [comment]
> i like this
> 
> we could even return the real inspector URL if bun was launched via `bun --inspect`

Looking further on `node:inspector` docs, implementing `waitForDebugger` may also be straightforward as it's a runtime equivalent of `--inspect-brk` which is present in `bun run`  

`inspector.console` however is expected to work slightly different from the current implementation, because IIRC it's expected to **not** log into shell stdio  
I generally used it to log 100kb-long JSON response objects which I definitely don't want to see in my slow Windows/VSCode/powershell shell

**Comment by Electroid** [comment]
> i like this
> 
> we could even return the real inspector URL if bun was launched via `bun --inspect`

I don't think we can realistically do this until we support the V8 <> JSC conversion. Otherwise lots of subtle things will break. (most usages I've seen expect devtools commands to essentially never fail)

**Comment by Dimava** [comment]
cc @ivawzh @mProjectsCode @Robbson @pragmatta typedoc should start working on the next release I guess
