### ISSUE TITLE
Weird crash in Bun when exporting using variable with 6 imports

### ISSUE THREAD

**Issue by lafkpages** [oven-sh/bun#10809]
### How can we reproduce the crash?

For some reason, Bun crashes with the following code snippet:

```ts
import { Database } from 'bun:sqlite';

import 'bun';
import 'bun:ffi';
import 'bun:jsc';
import 'node:assert';
import 'bun:test';

using a = new Database();

export { a };
```

If you add or remove any more imports, it works. If you replace `using` with `const`, it works. If you remove the `export` line, it works. It doesn't seem to matter what you import, as long as you have exactly 6 imports, it crashes.

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x58D82000000

- *2 unknown/js code*
- `array_hash_map.ArrayHashMap`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.Parser._parse__anon_341012`
- `src.json_parser.JSONLikeParser_`
- `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_309263`
- `src.watcher.NewWatcher`
- `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_302024`

**Comment by paperclover** [comment]
<img width="1025" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/e7266581-8cd1-4473-acfb-bc7a1d9c2e27">
thank you for the reproduction
