### ISSUE TITLE
Single-file executables icon on Windows

### ISSUE THREAD

**Issue by standstonecraft** [oven-sh/bun#10823]
### What is the problem this feature would solve?

Currently, the icon of an exe file built as a single-file executable with bun is a cute bun icon and cannot be changed.

### What is the feature you are proposing to solve the problem?

It would be great if the build command allows us to specify an icon file like this:
`bun build ./index.ts --compile --outfile hello.exe  --icon ./nikuman.ico`

### What alternatives have you considered?

The icon can be changed with Resource Hacker. However, it must be done each time you rebuild.

**Comment by sohaieb** [comment]
thank you @standstonecraft for raising this topic, I was about to raise it too 😄  

I want also to add as a suggestion (if possible), to support an optional default json-like configuration in the route of bun project, that can replace the compiling options.
something like: 
```js
// build-config.json:
{
   "outFile": "hello.exe",
   "icon": "your_icon.ico",
   "target": "windows10",
   ...
   ...
}
```
accordingly the command could be:
`bun build ./index.ts --compile` (automatically target build-config.json if it exists in the root project) 
or 
`bun build ./index.ts --compile --config-file custom-named-file.json`

**Comment by safagwq** [comment]
1. 
mv ~/.bun/install/cache/bun-windows-x64-v1.1.12  ~/.bun/install/cache/bun-windows-x64-v1.1.12.exe

2. 
use Resource Hacker

3. 
mv ~/.bun/install/cache/bun-windows-x64-v1.1.12.exe ~/.bun/install/cache/bun-windows-x64-v1.1.12

4. ^_^
bun build  --compile

**Comment by nknikolay** [comment]
I support you. I'd really like to see this kind of functionality.
Additionally, I would like to note that I would like to apply not only the icon settings, but also add information about the version, author, copyright, and so on

**Comment by colinshr** [comment]
@Jarred-Sumner @paperclover this doesn't work with cross compiling on mac for windows, when adding icon will not work
- create x.js
- run on mac or linux
- compile for windows exe
- add icon
- will write Using '--windows-icon is only available when compiling on Windows'
