### ISSUE TITLE
Error UNABLE_TO_VERIFY_LEAF_SIGNATURE!

### ISSUE THREAD

**Issue by sanguogege** [oven-sh/bun#10828]
### What version of Bun is running?

1.1.7

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

I can `bun init`，and then the file ok, but no node_modules.
![1](https://github.com/oven-sh/bun/assets/25738532/3c82de12-b7ee-46c7-9f58-38cc802f74d7)
![2](https://github.com/oven-sh/bun/assets/25738532/665c3851-35ee-426a-ad7c-110a9882e1c8)
when i want to  `bun install`
it come to this:
![image](https://github.com/oven-sh/bun/assets/25738532/e84289f5-6190-465f-a1d1-f564b5e6d5a9)
also `bun add` .

**Comment by zcg** [comment]
same issue how slove？
