### ISSUE TITLE
Memory Leak and 100% CPU while waiting for setTimeout

### ISSUE THREAD

**Issue by jcweaver997** [oven-sh/bun#1083]
### Version

0.1.8

### Platform

Linux DESKTOP-AUIP4S5 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

main.ts:
```
console.log("test")
setTimeout(()=>{}, 1000000)
```
Check CPU and memory usage

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior?

Low to none CPU usage, no increase in memory usage over time

### What do you see instead?

Memory reaches over 10GB of usage after just a minute
100% CPU usage on a single core

**Comment by JulienUsson** [comment]
Hello,

I had the same problem with Kubuntu 22.04 and Bun 0.1.2 but after upgrading bun to 0.1.13 it works correctly.

**Comment by Jarred-Sumner** [comment]
This should be fixed as of Bun v0.1.13 (it no longer spin loops). If you run into something like this again, please leave a comment
