### ISSUE TITLE
websocket 

### ISSUE THREAD

**Issue by aguadeowo** [oven-sh/bun#10832]
### How can we reproduce the crash?

i just closed and open again my app with bun test.js --watching

const WebSocket = require('ws');
const ws = new WebSocket('wss://stream.binance.com:9443/ws');
const symbols = ['btcusdt','ethusdt'];

ws.on('open', function open() {
  console.log('Conexión establecida con Binance.');
  for (const symbol of symbols) {
    ws.send(JSON.stringify({
      "method": "SUBSCRIBE",
      "params": [
        `${symbol}@ticker`
      ],
      "id": 1
    }));
  }
});

ws.on('message', function incoming(data) {
  const message = JSON.parse(data);
  if (message.a) {
    console.log(`Precio de ${message.s}: ${message.a}`);
  }
});

ws.on('error', function error(err) {
  console.error('Error en la conexión:', err);
});

ws.on('close', function close() {
  console.log('Conexión cerrada.');
});

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `us_socket_close`
- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/uws.zig#L2619): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/bindings/shimmer.zig#L186): `cppFn`
- [`cli.zig:1995`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1995): `maybeOpenWithBunJS`

**Comment by cirospaciari** [comment]
Fixed in canary `v1.1.22` if is happening after `bun upgrade --canary` feel free to reopen
