### ISSUE TITLE
Update pnpm file

### ISSUE THREAD

**Issue by CarmeloCampos** [oven-sh/bun#10838]
### What is the problem this feature would solve?

I am currently deploying my project in firebase, previously I had pnpm configured

### What is the feature you are proposing to solve the problem?

I would like to see if there is a way that when I run bun install or update, it updates the local packages, both the normal lock and the pnpm one.

### What alternatives have you considered?

Currently the only way to do this is to delete node_modules and do a pnpm install/update to update the lock.

**Comment by Electroid** [comment]
Hi, thanks for opening up a feature request. We don't have plans for Bun to update multiple lockfiles at the same time (e.g. npm's or pnpm's). This would slow down installations, and would also be hard to maintain.

You shouldn't need to delete node_modules to run `pnpm install` though? If there is a specific bug you're experiencing with bun install, let us know and we can investigate.
