### ISSUE TITLE
Is our TinyCC build on Windows setting `-march` correctly?

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#10856]
Where are we setting C flags when building TinyCC? How are we making sure that baseline builds are working correctly with TinyCC?

https://github.com/oven-sh/bun/blob/830af23742c957296db4cd7a5ffe25c1bac143db/scripts/build-tinycc.ps1#L20-L25

It feels highly suspicious that so many of the "Illegal instruction" errors include a stack trace that points to TinyCC. Either something is going wrong while generating the stacktrace, or something is wrong with the TinyCC build. 

Related issues:
- https://github.com/oven-sh/bun/issues/10435
- https://github.com/oven-sh/bun/issues/10460
- https://github.com/oven-sh/bun/issues/10545
- https://github.com/oven-sh/bun/issues/10546
- https://github.com/oven-sh/bun/issues/10547
- https://github.com/oven-sh/bun/issues/10578
- https://github.com/oven-sh/bun/issues/10583
- https://github.com/oven-sh/bun/issues/10615
- https://github.com/oven-sh/bun/issues/10629
- https://github.com/oven-sh/bun/issues/10700
- https://github.com/oven-sh/bun/issues/10755
- https://github.com/oven-sh/bun/issues/10756
- https://github.com/oven-sh/bun/issues/10788
- https://github.com/oven-sh/bun/issues/10790
- https://github.com/oven-sh/bun/issues/10798
- https://github.com/oven-sh/bun/issues/10841
- https://github.com/oven-sh/bun/issues/10853

**Comment by jexroid** [comment]
will this problem fixed in the next version?
