### ISSUE TITLE
bun add @clerk/theme

### ISSUE THREAD

**Issue by michael0945** [oven-sh/bun#10858]
### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [AddCommand]

error: InstallFailed

- [`install.zig:10706`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L10706): `installWithManager`
- [`array_list.zig:649`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/array_list.zig#L649): `deinit`
- [`install.zig:8321`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L8321): `updatePackageJSONAndInstallWithManager`
- [`add_command.zig:6`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/add_command.zig#L6): `exec`
- [`add_command.zig:6`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/add_command.zig#L6): `exec`
- [`cli.zig:1768`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1768): `start`

**Comment by Electroid** [comment]
Are you able to share the `package.json` you used?

**Comment by dylan-conway** [comment]
fixed in #10758
