### ISSUE TITLE
`\x08` mistranspiles into `\f`

### ISSUE THREAD

**Issue by begoon** [oven-sh/bun#1085]
### Version

0.1.8

### Platform

Darwin alexander-m1.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

The following one-line program `t.js` is expected to print `8`, but instead, it prints 12.
```
console.log("\x08".charCodeAt(0));
```

Execution:
```
bun t.js

12
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Print `8` always.

### What do you see instead?

It prints `12`.

### Additional information

When run under `node`, `d8` (V8 cli), `deno`, `jsc` (JavaScriptCore), `js` (SpiderMonkey), it always prints `8` as it should.

**Comment by Jarred-Sumner** [comment]
Bun is mis-transpiling `\x08` into `\f`.

**Comment by begoon** [comment]
Fixed in 0.3.0
