### ISSUE TITLE
bun install <PackageName> Throws Errors

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#10861]
### Relevant log output

```shell
similar errors occur when running:


bun upgrade # even with the latest version 1.1.7
bun install -g <package>
# and what mentioned in prior issues, the same address causes them: 0x7FF61037FA41
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF61037FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x153e0` in KERNEL32.DLL
- ??? at `0x485b` in ntdll.dll

**Comment by Electroid** [comment]
Are you able to share the `package.json` you used?

**Comment by Bader-Idris** [comment]
> Are you able to share the `package.json` you used?


This is an example of my `package.json` file used with my package. [here](https://github.com/Bader-Idris/e-commerce/blob/bader/server/package.json)

Although I believe it's not the cause, I think the incompatibility with my PC, the workstation HP Z600 with 64GB DDR3 RAM and two Xeon x5675 CPUs, is the cause. However, in the Ubuntu system, that issue doesn't exist on the same hardware.

**Comment by Jarred-Sumner** [comment]
@Bader-Idris you've already opened issues for this:
- #10547
- #10546
- #10545

Closing as duplicate
