### ISSUE TITLE
bun: command not found: cp when `bun *.sh`

### ISSUE THREAD

**Issue by LifeJustDLC** [oven-sh/bun#10869]
### What version of Bun is running?

1.1.7

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```shell
# build.bun.sh
cp src/manifest.json dist/manifest.json
```
`$ bun build.bun.sh`

### What is the expected behavior?

work

### What do you see instead?

```
bun: command not found: cp
```

### Additional information

`cat` `mv` does work, only `cp` doesn't.
Is this not implemented yet? BTW, can I find the doc of "which is implemented and which is not?"

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.8 by @zackradisic
