### ISSUE TITLE
SegmentationFault at 0xBC00000000000000 react-scripts

### ISSUE THREAD

**Issue by BGOPC** [oven-sh/bun#1088]
### Version

0.1.8

### Platform

Linux behrad 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Hi, I was curious about bun and react.js and bun.
I'm using [Create React app with bun](https://dev.to/ashirbadgudu/create-a-react-app-with-bun-125o)
I just made a react app using `bun create react buntest`, then I cd into that.
when I try to install react script using `bun a react-scripts -d`
I receive:
![image](https://user-images.githubusercontent.com/94793764/184892207-8f2dd08d-ad13-4d6b-a2e1-5839be29350c.png)

What do I do??

### How often does it reproduce? Is there a required condition?

There is no condition I tried this with so many proxy servers, my own network. I log out and Logged in. but there is no changelog out

### What is the expected behavior?

Install `react-scripts` successfully 

### What do you see instead?

```bash
bun add v0.1.8
  🔍 json-stable-stringify-without-jsonify [99/331] 
InstructionError at 0x9A429F0300000000


----- bun meta -----
Bun v0.1.8 (1bc5036d) Linux x64 #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022
AddCommand: 
HTTP: 1069
Elapsed: 79297ms | User: 79763ms | Sys: 725ms
RSS: 0.17GB | Peak: 123.65MB | Commit: 0.17GB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

### Additional information

My country is banned from so many techs

**Comment by Electroid** [comment]
We've made improvements to the reliability of `bun install`, and it looks like it works properly on MacOS Silicon.

```
bun add v0.2.2

 installed react-scripts@5.0.1 with binaries:
  - react-scripts

 1136 packages installed [14.80s]
```

If you're still able to reproduce the issue, please feel free to comment and we'll re-open the issue.
