### ISSUE TITLE
Segfault when using Binaryen

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#10891]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 5.10.0-28-amd64 x86_64 unknown

### What steps can reproduce the bug?

1. Create a new project with `bun init`
2. Install `binaryen`
3. Write the following code in the `index.ts` file:
```typescript
import binaryen from 'binaryen';
binaryen.Module()
```
4. See error: `Segmentation Fault`

### What is the expected behavior?

Expected it to work as usual, aka not getting any segfaults, and when using binaryen stuff

### What do you see instead?

As said before, Bun outputs a `Segmentation Fault`

**Comment by soitchu** [comment]
Duplicate of #9756. To get around it, you can change one of the commas to a semicolon for the time being, like I have done [here](https://github.com/soitchu/MyWASM/blob/main/Compiler/patches/binaryen.js)

**Comment by ghost** [comment]
> Duplicate of #9756. To get around it, you can change one of the commas to a semicolon for the time being, like I have done [here](https://github.com/soitchu/MyWASM/blob/main/Compiler/patches/binaryen.js)

Yup it's a duplicate of #9756
