### ISSUE TITLE
error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"

### ISSUE THREAD

**Issue by ngmisl** [oven-sh/bun#1089]
### Version

0.1.8

### What do you see instead?

bun install v0.1.8
error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/82
