### ISSUE TITLE
Windows crash when reading 2 files

### ISSUE THREAD

**Issue by JonnyBurger** [oven-sh/bun#10890]
### How can we reproduce the crash?

```tsx

import { createReadStream } from 'fs';

const file = 'iphone-hevc.mov'

const stream = createReadStream(file, {end: 1024});
stream.on('data', () => {});
createReadStream(file );
```

File: 

https://github.com/oven-sh/bun/assets/1629785/15b08b0b-21fc-468d-b32f-8c25f5d2021b

### JavaScript/TypeScript code that reproduces the crash?

```shell
See above
```

### Relevant log output

```shell
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "C:\Users\Jonny\.bun\bin\bun.exe", ".\src\test\parse-video.test.ts"
Features: jsc tsconfig(5) 
Builtins: "bun:main" "node:fs" "node:string_decoder" "node:util/types" 
Elapsed: 58ms | User: 15ms | Sys: 15ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.22GB | Faults: 33580

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [RunAsNodeCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/output.zig#L356): `panic`
- [`bun.zig:3159`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L3159): `assertionFailure`
- [`PipeReader.zig:420`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/io/PipeReader.zig#L420): `onFileRead`
- `uv__work_done`
- `??`
- `uv_run`
- [`uws.zig:2619`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/uws.zig#L2619): `run`
- `JSC__VM__holdAPILock`

**Comment by cirospaciari** [comment]
Fixed by https://github.com/oven-sh/bun/pull/11849
