### ISSUE TITLE
Another segfault

### ISSUE THREAD

**Issue by SunP04** [oven-sh/bun#10904]
### How can we reproduce the crash?

Run any command, like `bun i`

### Relevant log output

```shell
bun install v1.1.8-canary.1 (288b5406)
  � tsx [6/16] ============================================================
  ­ƒöì fsevents [10/20] Bun v1.1.8-canary.1 (288b5406) Windows x64 (baseline)
Elapsed: 2059ms | User: 437ms | Sys: 468ms
  ­ƒöì swagger-ui-dist [16/26] 130.49MB | Peak: 0.18GB | Commit: 0.27GB | Faults: 56654

  ­ƒöì get-tsconfig [17/28] (thread 6772): Illegal instruction at address 0x7FF754B44B41
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`288b540`](https://github.com/oven-sh/bun/tree/288b540621467f5ce03f405b56c72909de88a76a)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF754B44B41

- [`tccpp.c:408`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/deps/tinycc/tccpp.c#L408): `cstr_reset`
- [`tccgen.c:5017`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/deps/tinycc/tccgen.c#L5017): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/install/semver.zig#L268): `slice`
- [`pdq.zig:29`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/deps/zig/lib/std/sort/pdq.zig#L29): `pdq`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/288b540621467f5ce03f405b56c72909de88a76a/src/bun.zig#L1754): `insert`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

**Comment by dylan-conway** [comment]
fixed in #10884
