### ISSUE TITLE
Error Running Bun Install

### ISSUE THREAD

**Issue by senja24** [oven-sh/bun#10909]
### How can we reproduce the crash?

run "bun install" on windows. Already using v1.1.7

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7A91DFA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
The fix for this will release in Bun v1.1.8, which ships May 8th (tomorrow).

To get it early:
```sh
bun upgrade --canary
```
