### ISSUE TITLE
Get request params from request object

### ISSUE THREAD

**Issue by lau1944** [oven-sh/bun#1091]
### What is the problem this feature will solve?

I did not find any doc about getting a request params from a request, a default way is to parse request path myself, but it requires a bunch of boring code. Add the `params` field inside request object will be great.

### What is the feature you are proposing to solve the problem?

Easy to get request params.

### What alternatives have you considered?

const json = await req.json();

On my machine, it appears to be `SyntaxError: Failed to parse JSON`.

**Comment by xhyrom** [comment]
`const { searchParams } = new URL(request.url)`

**Comment by lau1944** [comment]
Thanks a lot. 
How do I get the request body?

**Comment by xhyrom** [comment]
> Thanks a lot. 
> How do I get the request body?

`await request.json()/.text()/.blob()/.arrayBuffer()`
