### ISSUE TITLE
Segfault with fs.watchFile

### ISSUE THREAD

**Issue by JonnyBurger** [oven-sh/bun#10917]
### How can we reproduce the crash?

`bun create video`
-> Empty template
-> `bun start`
-> Click "Render"

### JavaScript/TypeScript code that reproduces the crash?

Probably caused by calling fs.watchFile: https://github.com/remotion-dev/remotion/blob/e647d45e200bf6981fc62fc4ad482f79752843e9/packages/studio-server/src/file-watcher.ts#L34

### Relevant log output

```shell
╭─ Starting render 
│ Bundled code       ━━━━━━━━━━━━━━━━━━ 1380ms
│ ⚡️ Cached bundle. Subsequent renders will be faster.
============================================================
Bun v1.1.7 (b0b7db5c) macOS Silicon
Args: "bun", "/Users/jonathanburger/light-leaks-demo/node_modules/.bin/remotionb", "studio"
Features: jsc Bun.stderr Bun.stdin Bun.stdout abort_signal(17) fetch(9) http_server(2) spawn(28) transpiler_cache(18) tsconfig(2) WebSocket 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" 
Elapsed: 1936775ms | User: 27665ms | Sys: 12082ms
RSS: 0.54GB | Peak: 0.60GB | Commit: 0.39GB | Faults: 673

panic: Segmentation fault at address 0x6D6F74746F4267C6
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/Ma1b0b7db5A+hihoV__+wiyUm7woI__A2on69ttDs8zpovD
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x6D6F74746F4267C6

- *2 unknown/js code*
- `src.bun.js.node.node_fs_stat_watcher.StatWatcherScheduler.workPoolCallback`
- `Thread.PosixThreadImpl.spawn__anon_314379.Instance.entryFn`
- *2 unknown/js code*

**Comment by JonnyBurger** [comment]
macOS aarch64

**Comment by nektro** [comment]
no longer crashes or errors
