### ISSUE TITLE
bun crashed

### ISSUE THREAD

**Issue by ShadyShenAli** [oven-sh/bun#10914]
### How can we reproduce the crash?

in cmd.exe, execute bun repl  and it crashes (see crash report)

The same thing happens when I execute bun install after bun init -y.

### Relevant log output

```shell
D:\>bun repl
============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "bun", "bun-repl"
Elapsed: 11ms | User: 0ms | Sys: 0ms
RSS: 20.50MB | Peak: 20.50MB | Commit: 62.50MB | Faults: 5153

panic(main thread): attempt to unwrap error
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/wB1b0b7db5AA8wzkCk1mlCqkpqEm05rE44krE27gvFq4kBiiJoiyu2CCa\KERNEL32.DLL63yEA0eNpLLClJzS0oUSjJVyjNKy9KLFBILSrKLwIAbHQJCg

D:\p>dir
 Volume in drive D has no label.
 Volume Serial Number is 56A5-A7D0

 Directory of D:\p

05/08/2024  02:34 PM    <DIR>          .
05/08/2024  02:34 PM             2,233 .gitignore
05/08/2024  02:34 PM                30 index.ts
05/08/2024  02:34 PM               172 package.json
05/08/2024  02:34 PM               215 README.md
05/08/2024  02:34 PM               635 tsconfig.json
               5 File(s)          3,285 bytes
               1 Dir(s)   1,750,319,104 bytes free

D:\p>bun install
============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "bun", "install"
Elapsed: 6ms | User: 15ms | Sys: 0ms
RSS: 24.11MB | Peak: 24.11MB | Commit: 71.60MB | Faults: 6040

panic(main thread): attempt to unwrap error
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/wi1b0b7db5AA8wzkCw66kD8mrpCkw9iE8pvvFq4kBiiJoiyu2CCa\KERNEL32.DLL63yECU\ntdll.dllwk1WA0eNpLLClJzS0oUSjJVyjNKy9KLFBILSrKLwIAbHQJCg


```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [AddCommand]

**panic**: attempt to unwrap error

- [`mem.zig:197`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/mem.zig#L197): `copyForwards`
- [`windows.zig:3369`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/windows.zig#L3369): `GetFinalPathNameByHandle`
- [`install.zig:7126`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/install.zig#L7126): `initWithCLI`
- [`install.zig:8270`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/install.zig#L8270): `updatePackageJSONAndInstall`
- [`cli.zig:1447`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L1447): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L62): `start`
- [`main.zig:51`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/main.zig#L51): `main`
- [`exe_common.inl:78`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/src/startup/exe_common.inl#L78): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Related https://github.com/ziglang/zig/issues/18756
