### ISSUE TITLE
Support SQLite JSONB

### ISSUE THREAD

**Issue by broccolihighkicks** [oven-sh/bun#10926]
### What is the problem this feature would solve?

Faster processing of JSON data inside SQL queries. Dr Hipp says “up to 3x faster” processing.

### What is the feature you are proposing to solve the problem?

Upgrade the SQLite version to the one that has JSONB support

### What alternatives have you considered?

Not a blocking issue, just nice to have.

**Comment by infrahead** [comment]
This can be closed.  JSONB supported with Bun since https://bun.sh/blog/bun-v1.0.23#upgraded-sqlite-to-v3-45-0
