### ISSUE TITLE
Add support for packages that need building

### ISSUE THREAD

**Issue by neo773** [oven-sh/bun#1093]
### What is the problem this feature will solve?

Lot of packages have a post/pre install hook which builds the package for example: husky, @sentry/cli, react-native-purchases

### What is the feature you are proposing to solve the problem?

building fresh packages like Yarn
<img width="468" alt="Screen Shot 2022-08-17 at 4 38 20 PM" src="https://user-images.githubusercontent.com/62795688/185217004-a690ee06-abb5-4568-b6e7-fd844a92a1c5.png">

**Comment by k3n** [comment]
```sh
$ time bun install
bun install v0.1.10
 + depcheck@1.4.3
 + eslint@8.22.0
 + eslint-config-airbnb@19.0.4
 + eslint-plugin-import@2.26.0
 + eslint-plugin-node@11.1.0
 + eslint-plugin-promise@6.0.0
 + glob@7.2.3
 + husky@6.0.0
 + lerna@3.22.1
 + lint-staged@10.5.4
 + nyc@15.1.0
 + yarn@1.22.19
/bin/bash: husky: command not found

 979 packages installed [10.99s]
Script error "prepare" exited with 127 status
```

**Comment by Electroid** [comment]
Yes, we will support this when we add npm lifecycle hooks: #606
