### ISSUE TITLE
Bun crashes when trying to install a package.

### ISSUE THREAD

**Issue by FabioJMV** [oven-sh/bun#10934]
### How can we reproduce the crash?

Crash is shown using the `bun add` command to install any package.
```ps
bun add zod
```

### Relevant log output

```shell
bun add v1.1.7 (b0b7db5c)
  🚚 zod [5/9] ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64 (baseline)
Args: "C:\<path>\.bun\bin\bun.exe", "add", "zod"
Elapsed: 819ms | User: 78ms | Sys: 140ms
RSS: 74.83MB | Peak: 74.84MB | Commit: 125.01MB | Faults: 19238

panic(thread 6676): Illegal instruction at address 0x7FF63BC7FA41
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF7D672FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
This crash is fixed in Bun v1.1.8, which releases later today.

To get it now, run:
```sh
bun upgrade --canary
```
