### ISSUE TITLE
Arguments differ for process.once listener

### ISSUE THREAD

**Issue by sahithyandev** [oven-sh/bun#10941]
### What version of Bun is running?

1.1.7+b0b7db5c0

### What platform is your computer?

Linux 6.6.10-76060610-generic x86_64 x86_64

### What steps can reproduce the bug?

Run the below code on both bun and node.js

```js
process.once("SIGINT", (...args) => {
	// in Node.js
	// args is [ "SIGINT", 2 ]

	// in Bun
	// args is [ 2 ]
	console.log("\nSIGINT", args);
	process.exit(0);
});
```

I made a reproduction repo as well https://github.com/sahithyandev/bun-node-issue

### What is the expected behavior?

I was expecting the arguments to include the event name as well (same as Node's)

### What do you see instead?

The arguments list is missing the event name.

**Comment by Jarred-Sumner** [comment]
Fixed in #10940
