### ISSUE TITLE
Next.js app (v14.2.3) crashes bun

### ISSUE THREAD

**Issue by 0xsha** [oven-sh/bun#10952]
### How can we reproduce the crash?

Might be related to : https://github.com/oven-sh/bun/issues/10871

### JavaScript/TypeScript code that reproduces the crash?

```shell
Next.js app (v14.2.3) crashes after a few minutes when running `bun run -b dev`.
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x00000008

- *2 unknown/js code*
- `JSC::InlineCacheCompiler::regenerate`
- `JSC::StructureStubInfo::addAccessCase`
- `JSC::repatchGetBy`
- `operationGetByIdOptimize`
- *1 unknown/js code*
- `llint_entry`
- `llint_entry`
- *1 unknown/js code*

**Comment by Jarred-Sumner** [comment]
This should be fixed as of Bun v1.1.8. Please let us know if you're still running into this
