### ISSUE TITLE
Bun.build: Very high ongoing CPU usage on Windows, despite completing successfully

### ISSUE THREAD

**Issue by axefrog** [oven-sh/bun#10967]
### What version of Bun is running?

1.1.7

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Command line:

```sh
bun run --watch ./source/server.ts
```

`source/server.ts`:

```ts
import Path from 'node:path';

const result = await Bun.build({
  entrypoints: [Path.resolve('./source/client.ts')],
});

console.debug(`result.success:`, result.success);
```

`source/client.ts`:

```ts
console.log('Hello, world');
```

In watch mode, running the above results in a constant 13% CPU usage figure until the process is terminated. The problem goes away when I comment out the call to `Bun.build`, suggesting the bundler is the issue, not watch mode. But this is just speculation on my part.

[Here is a zip file](https://github.com/oven-sh/bun/files/15269741/server.zip) containing the project setup.

### What is the expected behavior?

CPU usage should be negligible, as the process shouldn't be doing any real work other than waiting for a change to the file to trigger a restart.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/298883/e5fb192a-a236-4877-be10-33da2725a9ba)

**Comment by paperdave** [comment]
thanks for the reproduction.

if i pause the process and see where we are at, we see that threads the bundler spawned are waiting for new work, but waiting in the wrong way and infinitely polling.

![image](https://github.com/oven-sh/bun/assets/24465214/6c63a92e-d368-4bea-a9dc-e041f74f59a7)

making these threads sleep properly is a minimum, but i wonder if we should be exiting these threads if the bundler is not being frequently called.
