### ISSUE TITLE
Cannot run command bun

### ISSUE THREAD

**Issue by witsuu** [oven-sh/bun#10984]
### How can we reproduce the crash?

every time I run the command on bun it always gives an error. This is my first time installing it

Version Windows: 22H2 OS Build 19045.4291

### Relevant log output

```shell
Bun v1.1.7 (b0b7db5c) Windows x64 (baseline)
Args: "C:\Users\witsu\.bun\bin\bun.exe", "create", "elysia"
Elapsed: 699ms | User: 31ms | Sys: 46ms
RSS: 41.59MB | Peak: 41.59MB | Commit: 90.39MB | Faults: 10340

panic(thread 1276): Illegal instruction at address 0x7FF7E3ECFA41
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [CreateCommand]

Illegal instruction at address 0x7FF6E543FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`fmt.zig:583`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/fmt.zig#L583): `formatType`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- `??`
- `??`

**Comment by gvilums** [comment]
Can you try upgrading to v1.1.8 and seeing if this issue still occurs? We landed a fix that should have resolved this

**Comment by witsuu** [comment]
I've updated to v1.1.8 and the problem doesn't appear anymore, thanks to you and the team
