### ISSUE TITLE
critical crash in bun install

### ISSUE THREAD

**Issue by romradchenko** [oven-sh/bun#10982]
### How can we reproduce the crash?

I tried to install packages via bun install
{
  "name": "test",
  "version": "0.1.0",
  "author": "nicro + Harland [KFC]",
  "homepage": "https://ragemp.pro",
  "license": "MIT",
  "private": true,
  "scripts": {
    "postinstall": "npm run install:client && npm run install:server && npm run install:ui",
    "install:client": "cd src_client && npm install",
    "install:server": "cd src_server && npm install --legacy-peer-deps",
    "install:ui": "cd src_ui && npm install --legacy-peer-deps",
    "build": "npm run build:ui && npm run build:client && npm run build:server",
    "build:ui": "cd src_ui && npm run build",
    "build:client": "cd src_client && npm run build",
    "build:server": "cd src_server && npm run build",
    "postbuild": "echo ✔ All Build success!",
    "bun:postinstall": "bun run bun:install:client && bun run bun:install:server && bun run bun:install:ui",
    "bun:install:client": "cd src_client && bun install",
    "bun:install:server": "cd src_server && bun install --legacy-peer-deps",
    "bun:install:ui": "cd src_ui && bun install --legacy-peer-deps",
    "bun:build": "concurrently \"bun run bun:build:ui\" \"bun run bun:build:client\" \"bun run bun:build:server\"",
    "bun:build:ui": "cd src_ui && bun run build",
    "bun:build:client": "cd src_client && bun run build",
    "bun:build:server": "cd src_server && bun run build",
    "bun:postbuild": "echo ✔ All Build success!"
  },
  "dependencies": {
    "@babel/runtime": "^7.14.5",
    "@tanstack/react-query": "4.36.1",
    "axios": "^0.21.1",
    "bcryptjs": "^2.4.3",
    "chalk": "^4.1.1",
    "cross-env": "^7.0.3",
    "crypto-random-string": "^4.0.0",
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "ioredis": "^4.27.5",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "mongodb-client-encryption": "^2.3.0",
    "mongoose": "^5.12.13",
    "nodemailer": "^6.6.1",
    "rage-rpc": "github:Yoegibby/rage-rpc#rage1.1_fixes",
    "source-map-support": "^0.5.19",
    "winston": "^3.3.3"
  }
}

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/output.zig#L356): `panic`
- [`bun.zig:3159`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L3159): `assertionFailure`
- [`fmt.zig:653`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/fmt.zig#L653): `formatType`
- [`install.zig:10960`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/install.zig#L10960): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L62): `start`
- [`main.zig:51`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/main.zig#L51): `main`

**Comment by witsuu** [comment]
Update your bun to v1.1.8, the developer has fixed this bug in this version
