### ISSUE TITLE
what is the ms/iter means in table?

### ISSUE THREAD

**Issue by Tiffanysbear** [oven-sh/bun#1099]
### Affected URL(s)

https://github.com/oven-sh/bun#bunsqlite-sqlite3-module

### Description of the problem

what is the ms/iter means? what is the meaning of "iter" ?

iterm or iteration ? 
if iteration, how to understand it in the sqlite3 searching ?

or iterm, stands for one operation ?

**Comment by xhyrom** [comment]
It is the milliseconds per iteration.

less time = faster

**Comment by paperclover** [comment]
**m**illi**s**econd per **iter**ation

**Comment by zhuzilin** [comment]
close as solved.
