### ISSUE TITLE
Convert all stored paths in .bun to project-relative

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#11]
This will prevent errors when user A tries to load a persisted node_modules.bun

**Comment by Electroid** [comment]
@Jarred-Sumner It looks like `.bun` stores imports that are relative to the project. Would this include any path, like an `fs` call? Or has this already been addressed?

```js
// lodash/lodash.js
export var $c691ac66 = $$m({
  "lodash/lodash.js": (module, exports) => {
// ...
```
