### ISSUE TITLE
SegmentationFault  at 0x0000000000000000 on Array.map

### ISSUE THREAD

**Issue by SillyCoon** [oven-sh/bun#1100]
### Version

0.1.8

### Platform

Darwin P86752 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Simple array map in ts file with >= number of elements (not exactly 6)

`[
  6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
  6, 6, 6, 6, 6, 6, 6, 6,
].map((v) => v);`

### How often does it reproduce? Is there a required condition?

Always, No

### What is the expected behavior?

No SegmentationFault  at 0x0000000000000000 

### What do you see instead?

![image](https://user-images.githubusercontent.com/26674286/185524317-885db556-c50f-4785-8804-237256ea3faa.png)

**Comment by Jarred-Sumner** [comment]
This is fixed in Bun v0.1.9
