### ISSUE TITLE
REPL not working

### ISSUE THREAD

**Issue by valcubeto** [oven-sh/bun#11015]
### What version of Bun is running?

1.1.8+89d25807f

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Just running `bun repl`

### What is the expected behavior?

Starting a REPL ig

### What do you see instead?

error: could not determine executable to run for package bun-repl

### Additional information

It wasn't working on previous versions (I ran 'bun upgrade').
I used the REPL like 3 times and it stopped working.

**Comment by RiskyMH** [comment]
We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this
