### ISSUE TITLE
Add support for URI

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#11012]
### What is the problem this feature would solve?

Add support for URI.

It could even replace some of the `node:path` features, like `relative` and `join`

### What is the feature you are proposing to solve the problem?

It would be great to have an URI handler, like [urijs](https://github.com/medialize/URI.js)

### What alternatives have you considered?

`bun add urijs`

**Comment by Jarred-Sumner** [comment]
Bun supports [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) and [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) to help with this
