### ISSUE TITLE
bun crash cant add plugin elysia and vite

### ISSUE THREAD

**Issue by oiandin** [oven-sh/bun#11021]
### How can we reproduce the crash?

bun crashed when I tried to add some plugin and create elysia or vite on my project

### Relevant log output

```shell
C:\Users\Asus\Documents\auth-bun>bun create vite app
  🔍 Resolving [1/1] ============================================================
Bun v1.1.6 (e58d67b4) Windows x64 (baseline)
Args: "C:\Users\Asus\AppData\Roaming\npm\node_modules\bun\bin\bun.exe", "add", "create-vite@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 263ms | User: 46ms | Sys: 78ms
RSS: 62.59MB | Peak: 62.59MB | Commit: 116.32MB | Faults: 15484

panic(thread 2568): Illegal instruction at address 0x7FF6CD605541
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.6/eI1e58d67bAAi0qlcg+rlc66j+G2uggGkojiGkmurKCa\KERNEL32.DLL63yECU\ntdll.dllwk1WA3s//B/r1+zyB
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64_baseline [AddCommand]

Illegal instruction at address 0x7FF621A15541

- [`tccgen.c:4886`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4886): `post_type`
- [`tccgen.c:4938`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/tinycc/tccgen.c#L4938): `post_type`
- [`Allocator.zig:193`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/mem/Allocator.zig#L193): `alignedAlloc`
- [`semver.zig:726`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/semver.zig#L726): `orderWithoutTag`
- [`writer.zig:23`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/io/writer.zig#L23): `writeAll`
- [`multi_array_list.zig:540`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/multi_array_list.zig#L540): `capacityInBytes`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.8 and try again. To upgrade, run `bun upgrade`
