### ISSUE TITLE
Implement Request/Response `.bytes()` method

### ISSUE THREAD

**Issue by bakkot** [oven-sh/bun#11049]
See https://github.com/whatwg/fetch/issues/1732.

Tests at https://github.com/web-platform-tests/wpt/pull/46198.

The above spec PR adds a `bytes()` method to get a Uint8Array to Body, instead of requiring users to get an ArrayBuffer with `arrayBuffer()` and then wrap it.

There are also PRs to do the same for Blob and PushMessageData, which copy relevant parts of the Body interface:
- https://github.com/w3c/FileAPI/pull/197
- https://github.com/w3c/push-api/pull/369

I don't think Bun has PushMessageData but it does have Blob.

**Comment by Jarred-Sumner** [comment]
Sounds great. We will add this.

**Comment by bakkot** [comment]
You may be interested in [the WebKit PR](https://github.com/WebKit/WebKit/pull/28530) for the same.
