### ISSUE TITLE
Bun won't install on Parallel Desktop Windows on MacOS

### ISSUE THREAD

**Issue by yousefelgoharyx** [oven-sh/bun#11043]
### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Try to run the install command

### What is the expected behavior?

to install properly

### What do you see instead?

Install Failed:
Bun for Windows is currently only available for x86 64-bit Windows.

1

### Additional information

Maybe because it's Windows on ARM? If so it should give an appropriate error message

**Comment by Clemens-E** [comment]
Isn't that error message already exactly what you are asking for?
It specifies that it can't run on your system, and it's only available on x86 64-bit

**Comment by Electroid** [comment]
Duplicate of #9824
