### ISSUE TITLE
"dyld: missing symbol called" when using knex.js

### ISSUE THREAD

**Issue by MrKampla** [oven-sh/bun#11040]
### What version of Bun is running?

1.1.8

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Copy the code from https://stackblitz.com/edit/stackblitz-starters-sscwot
Run the `index.ts` file with `tsx` and with bun

### What is the expected behavior?

The script prints selected rows from local sqlite database.
<img width="469" alt="image" src="https://github.com/oven-sh/bun/assets/46401284/3290d2e2-e719-4111-a8fb-aff75deda7ed">

### What do you see instead?

Script works perfectly fine with node, but in bun it throws "dyld[]: missing symbol called" error:
<img width="465" alt="image" src="https://github.com/oven-sh/bun/assets/46401284/ed4ab2ea-3bc5-41c4-8add-5a356580ebbc">

**Comment by Jarred-Sumner** [comment]
Please follow along in #4290 

@190n is actively working on supporting V8 C++ APIs in Bun
