### ISSUE TITLE
Exit Code 137 when a background subprocess is closed externally

### ISSUE THREAD

**Issue by wellwelwel** [oven-sh/bun#11055]
### What version of Bun is running?

1.1.8+89d25807f

---

### What platform is your computer?

Darwin 23.4.0 arm64 arm

---

### What steps can reproduce the bug?

When a subprocess is started, but is terminated externally (e.g., using `kill -9`), **Bun** executes the entire script normally until its end, but terminates the process with code `137` if this subprocess was previously called (using `fetch`, for example), even if it all worked properly.

> I've created a minimal repository for a simple step-by-step repro using solely native **Bun** features:
> https://github.com/wellwelwel/bun-unexpected-exit-code-137

#### Steps

- Start a subprocess (e.g., `spawn`) that will be used in background
- Fetch it
- Close the subprocess directly by PID
- Wait for the main process to be completed

> If "fetch" step is removed, everything will work perfectly.

<details>
<summary>
<i>lib/server.ts</i>
</summary>

```ts
// Nothing wrong here (it could be any service or server, using Bun or not) 🙋🏻‍♂️

Bun.serve({
  port: 4000,
  fetch: () => new Response('✅ Server is Live'),
});
```

</details>

<details>
<summary>
<i>lib/pid.ts</i>
</summary>

```ts
// Nothing wrong here (just for context) 🙋🏻‍♂️

const findPID = (port: number): Promise<number[]> =>
  new Promise(async (resolve) => {
    const PIDs: Set<number> = new Set();
    const service = Bun.spawn(['lsof', '-t', '-i', `:${Number(port)}`]);

    const output = (await new Response(service.stdout).text())
      .trim()
      .split('\n');

    output.forEach((pid) => {
      if (pid) PIDs.add(Number(pid));
    });

    return resolve(Array.from(PIDs));
  });

const killPID = async (PID: number) => {
  const proc = Bun.spawn(['kill', '-9', PID.toString()]);

  return await proc.exited;
};

export const killPort = async (port: number) => {
  const PIDs = await findPID(port);

  PIDs.forEach(async (PID) => await killPID(PID));
};
```

</details>

<details open>
<summary>
<i><b>repro.error.ts</b></i>
</summary>

```ts
import { killPort } from './lib/pid.js';

// Start the server in background
try {
  const proc = Bun.spawn(['bun', 'lib/server.ts'], {
    // It doesn't run if "fetch" is used
    onExit: (proc) => {
      console.log('✅ Sub process signal Code is', proc.signalCode);
      console.log('✅ Sub process exit code is', proc.exitCode);
    },
  });

  const error = await new Response(proc.stderr).text();
  if (error) console.log(error);
} catch (quiet) {
}

const repro = async () => {
  const res = await (await fetch('http://localhost:4000')).text();
  console.log(res);

  await killPort(4000);

  console.log('✅ Module continues to work normally after closing the PIDs');
};

setTimeout(repro, 1000);

// It doesn't run if "fetch" is used
process.on('exit', (code) => {
  console.log('✅ Exit Code is', code);
});
```

</details>

#### Output

```bash
bun repro.error.ts
```

```
✅ Server is Live
✅ Module continues to work normally after closing the PIDs
[1]    7901 killed     bun repro.error.ts
```

ℹ️ Note that the error is not exactly related to `fetch` itself. Even using `node:http` or an external package, the issue seems to be related to the simple fact of **Bun** triggers a service running in the background.

> Testing manually, this behavior also occurred on **Linux**, including the official **Docker** **Alpine** images to check different **Bun** versions and the platform `linux/amd64`.

---

### What is the expected behavior?

I tried the same approach for **Deno** and **Node.js**, and everything worked normally in all cases, as expected.

Also, in **Bun**, by just not calling the background subprocess, everything will work as usual:

<details>
<summary>
<i>repro.success.ts</i>
</summary>

```ts
import { killPort } from './lib/pid.js';

try {
  const proc = Bun.spawn(['bun', 'lib/server.ts'], {
    // Without "fetch", everything works fine
    onExit: (proc) => {
      console.log('✅ Sub process signal Code is', proc.signalCode);
      console.log('✅ Sub process exit code is', proc.exitCode);
    },
  });

  const error = await new Response(proc.stderr).text();
  if (error) console.log(error);
} catch (quiet) {
}

const repro = async () => {
  // const res = await (await fetch('http://localhost:4000')).text();
  // console.log(res);

  await killPort(4000);

  console.log('✅ Module continues to work normally after closing the PIDs');
};

setTimeout(repro, 1000);

// Without "fetch", everything works fine
process.on('exit', (code) => {
  console.log('✅ Exit Code is', code);
});
```

</details>

- Same code, just commenting `fetch`

#### Output

```bash
bun repro.success.ts
```

```
✅ Module continues to work normally after closing the PIDs
✅ Sub process signal Code is SIGKILL
✅ Sub process exit code is null
✅ Exit Code is 0
```

---

### What do you see instead?

A visual output of both the error and success examples:

<img width="552" alt="Screenshot 2024-05-13 at 18 55 24" src="https://github.com/oven-sh/bun/assets/46850407/8051dccd-fbfd-40aa-ab02-a18dcbeff3cd">

<img width="552" alt="Screenshot 2024-05-13 at 19 03 00" src="https://github.com/oven-sh/bun/assets/46850407/c2eec18e-a177-4169-aac9-ad0513a452da">

---

### Additional information

I noticed that both **Bun** and **Deno** reproduce the issue #7441. To solve this in my package, I've allowed the user to pass a port when finishing a subprocess to ensure its end.

But even if the process terminates completely successfully, this happens (due to the `137` exit code — _this reported issue_):

> The following test results use `node:child_process` and `node:http`, so this issue also occurs by using solely native **Node.js** features and using **Bun** just to run it (although it works normally for **Node.js** and **Deno**).

<img width="552" alt="Screenshot 2024-05-13 at 19 37 03" src="https://github.com/oven-sh/bun/assets/46850407/4c992aa1-c106-467e-840f-4d0f5d152413">

---

_Thanks for your time_ 🙋🏻‍♂️

**Comment by paperclover** [comment]
thanks for detailed bug report, but this is not a bug

note that `137` is 128+9, where 9 is SIGKILL. this is what shells use to encode signals and exit codes at once. 

if i stick a console log in your kill function, logging the desired pid and the current pid, i see that the `fetch`ing process is being killed by your code.
<img width="632" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/a0f47b4f-30c9-4a14-a20c-63bf2ba39d7e">

this is because `fetch` is keeping it's connection to port 4000 open (http keep alive, an intentional feature). so doing lsof will report it.

<img width="354" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/4517449f-44ff-4988-b8f7-771bdaf6e215">

the command i find from googling seems to be `lsof -t -i :4000 -sTCP:LISTEN`. the last arg to filter just to listeners and not connections.

**Comment by paperclover** [comment]
eek, why does removing a tag still cause robobun bot to spam the tags

**Comment by wellwelwel** [comment]
Thanks, @paperdave 🤝

Same approach worked for **Windows**, using `netstat` instead.

<img width="518" alt="Screenshot 2024-05-15 at 03 05 21" src="https://github.com/oven-sh/bun/assets/46850407/9fbcdbab-8f0a-4876-b6e3-69070af68584">
