### ISSUE TITLE
`Unexpected Identifier` when running esbuild bundled script

### ISSUE THREAD

**Issue by theseyan** [oven-sh/bun#1105]
### Version

0.1.10

### Platform

Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

Need to have `esbuild` preinstalled
```bash
git clone https://github.com/jhmaster2000/bun-repl && cd bun-repl
# small patch to make it bundle with esbuild
sed "3 c\import * as _util from '.\/util.js';" src/utl/index.ts
esbuild src/repl.ts --bundle --outdir=out --platform=node --target=node16 --format=esm --external:bun --external:bun:ffi --loader:.node=file --external:bun:jsc
bun out/repl.js
```

### How often does it reproduce? Is there a required condition?

It is reproducible everytime in this repository. However, I'm unsure of what exactly triggers this, it may not happen for simpler projects.

### What is the expected behavior?

On running `bun out/repl.js`, script should run successfully (or atleast not throw `Unexpected identifier 'Bun'` error).
`Bun.file` should be a valid function, and `Bun` is not seen as an unexpected identifier.

### What do you see instead?

Bun throws an error on trying to run the script:
```ts
5014 |   #historypath;
5015 | };
5016 | 
5017 | // src/pkgjson.ts
5018 | import path from "path";
5019 | var pkgjson = await Bun.file(path.join(import.meta.dir, "..", "package.json")).json();
        ^
SyntaxError: Unexpected identifier 'Bun'
      at /home/theseyan/Zig/bun-repl/out/repl.js:5019:4
```

### Additional information

The esbuild bundled output `repl.js` has been attached as txt.
Relevant line number is: 5019
[repl.txt](https://github.com/oven-sh/bun/files/9382510/repl.txt)
Possibly related to Bun's transpiler, as pointed out by Jarred.

**Comment by Electroid** [comment]
Can't reproduce this anymore, we've liked fixed this from a while ago.
