### ISSUE TITLE
please check so i have to install some software's please

### ISSUE THREAD

**Issue by shahidiqbal369** [oven-sh/bun#11052]
### How can we reproduce the crash?

Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\shahi\.bun\bin\bun.exe", "install"
Elapsed: 69ms | User: 0ms | Sys: 46ms
RSS: 51.59MB | Peak: 51.59MB | Commit: 92.16MB | Faults: 12779

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.8/wi189d2580AAglq4L+g0uIwit1F+swCm/uwH0v53D0k7kE0jnjE8zqvFqg4BA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/output.zig#L356): `panic`
- [`bun.zig:3177`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.zig#L3177): `assertionFailure`
- [`lockfile.zig:4902`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/lockfile.zig#L4902): `save`
- [`lockfile.zig:1643`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/lockfile.zig#L1643): `saveToDisk`
- [`install.zig:10942`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L10942): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L62): `start`

**Comment by Yaritza1095** [comment]
This was th original issue which was marked as closed and fixed https://github.com/oven-sh/bun/issues/10849 however I retried and can confirm the same thing is still happening

**Comment by paperclover** [comment]
can you try this on a canary build? The above trace is from a version before the fix in #11051, so it should just work now. If it can be reproduced in a version newer, please open a new crash report.
