### ISSUE TITLE
Empty pacakges

### ISSUE THREAD

**Issue by malezjaa** [oven-sh/bun#11069]
### What version of Bun is running?

1.1.8

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. `bunx create-turbo`
2. `bun install`
3. `bun run build`

### What do you see instead?

When trying to run `unbuild` package from workspace root I get this error:
```
bun --bun unbuild
error: Cannot find package "hookable" from "C:\dev\kuro.js\kurogashi\node_modules\unbuild\dist\cli.mjs"
```

![image](https://github.com/oven-sh/bun/assets/66274761/ba28e80f-1c12-4515-8a4a-f2169bfa18b8)

It looks like some directories in `node_modules` are just empty

### Additional information

Clearing the cache resolved this issue

**Comment by dylan-conway** [comment]
This could happen if `hookable` was an empty directory in cache. Most likely you can fix this by deleting cache (`bun pm cache rm`) and reinstalling.
