### ISSUE TITLE
Runtime debugger 

### ISSUE THREAD

**Issue by delaneyj** [oven-sh/bun#1106]
### What is the problem this feature will solve?

Ability to debug a bun server similar to the workflow that you would have using ts-node.

### What is the feature you are proposing to solve the problem?

I honestly don't know the details enough to have a plan. I'm adding this request per a discussion with @Jarred-Sumner on discord channel.

### What alternatives have you considered?

It doesn't really matter if it's using the node.js hooks, chrome tools, etc.  Just looking for the raillery to set breakpoints and inspect variables at runtime.

**Comment by mlntr** [comment]
https://www.youtube.com/watch?v=EsAvqwNSKZM + [tweet](https://twitter.com/jarredsumner/status/1665701332940996609) 
 Looks like it's now being looked into

**Comment by vjpr** [comment]
Maybe this is useful: https://microsoft.github.io/debug-adapter-protocol/

> Since it is unrealistic to assume that existing debuggers or runtimes adopt this protocol any time soon

Maybe Bun could just support this protocol natively.

**Comment by Jarred-Sumner** [comment]
In Bun v0.8.0, we added support for [debugging bun](https://bun.sh/docs/runtime/debugger). 

Try `bun --inspect ./script.ts`

Currently, it's only available via web inspector but we will soon add a VSCode extension. I'm marking this as completed, but we will post a link to this thread when the VSCode extension lands. 

The VSCode extension implements the [debug adapter protocol](https://microsoft.github.io/debug-adapter-protocol/) which means it should be straightforward for the community to add extensions for other editors compatible with the debug adapter protocol. 

If you want to start messing with it early, [have a look in here](https://github.com/oven-sh/bun/blob/main/packages/bun-debug-adapter-protocol/debugger/adapter.ts).
