### ISSUE TITLE
Next.js middleware Error: Attempt to export a nullable value for "TextDecoderStream"

### ISSUE THREAD

**Issue by nodirbekrajaboff** [oven-sh/bun#11062]
### What version of Bun is running?

1.1.2

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

If I use middleware in my nextjs project I get this error:
Error: Attempt to export a nullable value for "TextDecoderStream"

**Comment by Jarred-Sumner** [comment]
Duplicate of #5648

**Comment by Jarred-Sumner** [comment]
Closing as duplicate
