### ISSUE TITLE
bunx cowsay "Hello world!" thows an error

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#11061]
### How can we reproduce the crash?

the same cause of prior bun install bugs, #10435 #10460 #10545, etc, is causing this error

```sh
bunx cowsay "Hello world!" # causes this

bunx cowsay "Hello world!"~
  🔍 get-stdin [4/8] ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64 (baseline)
Args: "C:\Users\me\.bun\bin\bunx.exe", "add", "cowsay@latest", "--no-summary", "--no-cache", "--force"
Elapsed: 844ms | User: 31ms | Sys: 78ms
RSS: 62.00MB | Peak: 62.00MB | Commit: 116.37MB | Faults: 15344

panic(thread 14168): Illegal instruction at address 0x7FF7F5C7FA41
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

```

the bun install prior bugs are yes fixed, but the same source that causes these errors is not fixed well, `0x7FF7F5C7FA41`  with old CPUs

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64_baseline [InstallCommand]

Illegal instruction at address 0x7FF61037FA41

- [`libtcc.c:188`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/libtcc.c#L188): `pstrcpy`
- [`tccgen.c:5018`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/tinycc/tccgen.c#L5018): `post_type`
- [`logger.zig:993`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/logger.zig#L993): `addRangeErrorFmt`
- [`semver.zig:268`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/semver.zig#L268): `slice`
- [`math.zig:452`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/math.zig#L452): `sub`
- [`bun.zig:1754`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L1754): `insert`
- ??? at `0x153e0` in KERNEL32.DLL
- ??? at `0x485b` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.8 and try again

**Comment by Bader-Idris** [comment]
> Please upgrade to Bun v1.1.8 and try again

Then this is another issue, I updated bun, but bunx didn't get updated with it
