### ISSUE TITLE
TransformStream doesn't seem to work

### ISSUE THREAD

**Issue by cyco130** [oven-sh/bun#1107]
### Version

v0.1.10

### Platform

`Linux fatih-hp 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

The following works on Node¹ and Chrome but fails with `TypeError: undefined is not a function` on Bun.

```js
const { writable, readable } = new TransformStream();

const reader = await readable.getReader();
const writer = await writable.getWriter();

reader.read().then((v) => console.log(v));
await writer.write("Hello");
```

¹ With `TransformStream` imported from `stream/web`.

### How often does it reproduce? Is there a required condition?

Seemingly all the time

### What is the expected behavior?

The expected behavior is it to output `{ value: 'Hello', done: false }` on the console.

### What do you see instead?

The following output:

```
2 | 
3 | const reader = await readable.getReader();
4 | const writer = await writable.getWriter();
5 | 
6 | reader.read().then((v) => console.log(v));
7 | await writer.write("Hello");
          ^
TypeError: undefined is not a function
      at /home/cyco/Documents/github/rakkasjs/examples/todo/src/entry-bun.js:7:6
```

### Additional information

There are several references to TransformStream in the source code but the docs aren't clear on whether TransformStream is supported or not. If it isn't, feel free to consider this a feature request (it's a prerequisite for [Rakkas](https://github.com/rakkasjs/rakkasjs) to run on Bun :)

**Comment by Electroid** [comment]
This has been fixed as of Bun 0.5.8.

```ts
const { writable, readable } = new TransformStream();

const reader = await readable.getReader();
const writer = await writable.getWriter();

reader.read().then((v) => console.log(v));
await writer.write("Hello");
```

```console
{
  value: "Hello",
  done: false
}
```
