### ISSUE TITLE
dyld[21041]: missing symbol called zsh: abort bun test.mjs

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#11072]
### What version of Bun is running?

1.1.8+89d25807f

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```ts
import midi from 'midi';

const output = new midi.Output();

console.log(output);
```

### What is the expected behavior?

NodeMidiOutput {}

### What do you see instead?

dyld[21041]: missing symbol called
zsh: abort      bun test.mjs

**Comment by Electroid** [comment]
Duplicate of #4290
