### ISSUE TITLE
Can't run shadcn CLI a second time

### ISSUE THREAD

**Issue by Sisableng** [oven-sh/bun#11118]
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

the first time I installed bun on my laptop then I installed shadcn/ui for the first time on the nextjs project that I created, everything worked fine, but when I created a new Nextjs project and installed shadcn/ui I got an error 

```bash
$ bunx shadcn-ui@latest init
error: could not determine executable to run for package shadcn-ui
```

at first I thought this problem was from the shadcn CLI, but I tried looking for a fix on google and found this issue [#4583](https://github.com/oven-sh/bun/issues/4583#issue-1887835592), I followed [this comment](https://github.com/oven-sh/bun/issues/4583#issuecomment-1712800618) to reset the cache on the bun then I tried it and the CLI can work again

**Comment by vgseven** [comment]
`bunx --bun shadcn-ui@latest init` use this and re-try..

**Comment by psnwd** [comment]
same here

```
$ bunx --bun shadcn-ui@latest add alert-dialog
error: could not determine executable to run for package shadcn-ui

$ bunx --bun shadcn-ui@latest init
error: could not determine executable to run for package shadcn-ui
```

**Comment by youesei** [comment]
me too

```
C:\...>bunx --bun shadcn-ui@latest add dialog
error: could not determine executable to run for package shadcn-ui
```

**Comment by Sisableng** [comment]
so what the best solution?

**Comment by psnwd** [comment]
> so what the best solution?

I'm currently using **bun** for my project, but I use **pnpm** specifically to install any shadcn UI components.

```
pnpm dlx shadcn-ui@latest add accordion
```

**Comment by viiccwen** [comment]
I'm also facing the same problem. : (

**Comment by viiccwen** [comment]
hello @Sisableng ,
you can use this to substitute command:
`bun add shadcn-ui@latest`
`bun shadcn-ui init`
`bun shadcn-ui add <component>`

**Comment by Sisableng** [comment]
> hello @Sisableng , you can use this to substitute command: `bun add shadcn-ui@latest` `bun shadcn-ui init` `bun shadcn-ui add <component>`

did it work for you? I think I tried it but it was the same, maybe I'll try it again in the next project.

**Comment by vgseven** [comment]
> ### What version of Bun is running?
> 1.1.4+fbe2fe0c3
> 
> ### What platform is your computer?
> Microsoft Windows NT 10.0.19045.0 x64
> 
> ### What steps can reproduce the bug?
> the first time I installed bun on my laptop then I installed shadcn/ui for the first time on the nextjs project that I created, everything worked fine, but when I created a new Nextjs project and installed shadcn/ui I got an error
> 
> ```shell
> $ bunx shadcn-ui@latest init
> error: could not determine executable to run for package shadcn-ui
> ```
> 
> at first I thought this problem was from the shadcn CLI, but I tried looking for a fix on google and found this issue [#4583](https://github.com/oven-sh/bun/issues/4583#issue-1887835592), I followed [this comment](https://github.com/oven-sh/bun/issues/4583#issuecomment-1712800618) to reset the cache on the bun then I tried it and the CLI can work again
> 
> ### What is the expected behavior?
> _No response_
> 
> ### What do you see instead?
> _No response_
> 
> ### Additional information
> _No response_

have you run the command `bunx --bun shadcn-ui@latest init` initally ?

**Comment by viiccwen** [comment]
> > hello @Sisableng , you can use this to substitute command: `bun add shadcn-ui@latest` `bun shadcn-ui init` `bun shadcn-ui add <component>`
> 
> did it work for you? I think I've tried it before but it was the same, maybe I'll try it again in my next project.

Haha, yes.
It's work for me. Hope u can find the solution.

**Comment by fjohanssondev** [comment]
Looks like some of the comments doesn't read the initial post. The OP points towards another thread where a solution is presented. Had the same issue and the following that was written worked for me.

_You can try again deleting bun's cache: `bun pm cache rm` (you also have to delete **node_modules** and **bun.lockb** again)
@lorenzorapetti_

**Comment by creative-tutorials** [comment]
> Looks like some of the comments doesn't read the initial post. The OP points towards another thread where a solution is presented. Had the same issue and the following that was written worked for me.
> 
> _You can try again deleting bun's cache: `bun pm cache rm` (you also have to delete **node_modules** and **bun.lockb** again) @lorenzorapetti_

Thank you ver much. This helped me out a lot

**Comment by VAaRrUNn** [comment]
These set of commands are working for me:
> For initial install and init

`bun add shadcn-ui@latest`
`bun x shadcn-ui init`

> For adding any components, just use `bun x` instead of `bunx`:

`bun x --bun shadcn-ui@latest add button`

**Comment by 10d3** [comment]
bunx --bun shadcn@latest init instead of bunx shadcn-ui@latest init

don't put the ui in

**Comment by AnasMostefaoui** [comment]
Thank you @10d3 , that fixed the issue on my side.

**Comment by Sisableng** [comment]
guys, its fixed with `bunx --bun shadcn@latest init`

**Comment by AngelBlackBlue** [comment]
$ bun x --bun shadcn@latest add dialog
error: could not determine executable to run for package shadcn

**Comment by anhwrkspx** [comment]
> bunx --bun shadcn@latest init instead of bunx shadcn-ui@latest init
> 
> don't put the ui in

Thanks you. I guess it's the documents false

**Comment by anhwrkspx** [comment]
@AngelBlackBlue 
> $ bunx 
not bun x
