### ISSUE TITLE
Bun crash on create t3-app@latest

### ISSUE THREAD

**Issue by 17robots** [oven-sh/bun#11129]
### How can we reproduce the crash?
On Windows 11 22631.3593, powershell, bun installed through installer for windows (not through scoop or other pkg mngr). No node or npm installed on machine. 

1. run bun create t3-app@latest
2. fill in the name (I used test)
3. select typescript option
4. select yes for tailwind
5. select no for trpc
6. select none for auth
7. select drizzle for db
8. select yes for app router

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- `??`
- *4 unknown/js code*

Features: jsc, Bun.stdin, Bun.stdout, fetch, transpiler\_cache

**Comment by vgseven** [comment]
you have to install node, because bun is not currently compatible with all node api's. t3 is built on top of node, so to function properly you need node installed.
