### ISSUE TITLE
bun install

### ISSUE THREAD

**Issue by yatish27** [oven-sh/bun#11159]
### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on linux aarch64 [RunAsNodeCommand]

**panic**: A C++ exception occurred

- [`bindings.zig:1901`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/bindings.zig#L1901): `Zig__GlobalObject__onCrash`
- [`ZigGlobalObject.cpp:218`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/ZigGlobalObject.cpp#L218): `JSCInitialize::$_0::__invoke`
- [`unumsys.cpp:0`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/unumsys.cpp#L0): `__cxxabiv1::__terminate`
- [`unumsys.cpp:0`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/unumsys.cpp#L0): `std::terminate`
- [`unumsys.cpp:0`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/unumsys.cpp#L0): `__cxa_throw`
- [`floatsitf.c:0`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/floatsitf.c#L0): `std::__throw_system_error`
- [`ZigGlobalObject.cpp:0`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/ZigGlobalObject.cpp#L0): `JSCInitialize`
- [`bindings.zig:6293`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/bindings.zig#L6293): `src.bun_js.Run.boot`
- [`run_command.zig:1645`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/run_command.zig#L1645): `src.cli.Cli.start`
- [`main.zig:50`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/main.zig#L50): `main`

**Comment by vgseven** [comment]
Hey Yatish, Can you please describe on which `bun install` command this particular error occurred ? If possible consider sharing screenshots while `bun install` crashed..
