### ISSUE TITLE
Another repo to keep all examples

### ISSUE THREAD

**Issue by uwussimo** [oven-sh/bun#1116]
### What is the problem this feature will solve?

Avoid checking irrelevant example PRs. Instead focus on the compiler source code and bug&fixes

### What is the feature you are proposing to solve the problem?

Simply create another repo for examples and let the audience create & push their example apps they made with bun in to that repo. Assign a few people to review codes and merge PRs.

**Comment by Electroid** [comment]
Yes, this is something we will be doing when the docs are ready to go. We're tracking this internally.
