### ISSUE TITLE
Error relocating /root/.bun/bin/bun: fcntl64: symbol not found

### ISSUE THREAD

**Issue by guijun** [oven-sh/bun#1117]
### Version

0.1.10

### Platform

alpha linux 3.15

### What steps will reproduce the bug?

download v0.1.10.
apk add libc6-compat gcompat
unzip v0.1.10.zip
./bun

Error relocating /root/.bun/bin/bun: fcntl64: symbol not found
Error relocating /root/.bun/bin/bun: __res_init: symbol not found

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

runnable.

### What do you see instead?

Error relocating /root/.bun/bin/bun: fcntl64: symbol not found
Error relocating /root/.bun/bin/bun: __res_init: symbol not found

**Comment by Electroid** [comment]
Bun does not support MUSL, so there will be oddities when running on Alpine Linux. We do offer a [`bun:alpine`](https://hub.docker.com/layers/oven/bun/alpine/images/sha256-faf3617e1d047eaf7f200409ba559b9575177f8e1c9c1da7cee5aa21199207d9?context=explore) Docker image that you can use or adapt to fix this issue.

Related: #918
