### ISSUE TITLE
sentinel mismatch

### ISSUE THREAD

**Issue by malezjaa** [oven-sh/bun#11170]
### How can we reproduce the crash?

`bun install` in folder inside workspace package

![Zrzut ekranu 2024-05-18 222511](https://github.com/oven-sh/bun/assets/66274761/0b2c3431-4f30-4dcd-a9bd-73d4f75e47f3)

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [InstallCommand]

**panic**: sentinel mismatch

- [`Allocator.zig:98`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/mem/Allocator.zig#L98): `rawFree`
- [`install.zig:7122`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L7122): `initWithCLI`
- [`filter_run.zig:401`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/filter_run.zig#L401): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L62): `start`
- [`main.zig:51`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/main.zig#L51): `main`
- [`exe_common.inl:78`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/src/startup/exe_common.inl#L78): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by dylan-conway** [comment]
This was fixed in bun `v1.1.14` with #11856
