### ISSUE TITLE
Sqlite Error

### ISSUE THREAD

**Issue by jsiwa** [oven-sh/bun#11187]
### How can we reproduce the crash?

Bun v1.1.8 (89d25807) macOS x64
Args: "bun", "run", "src/test-maijia-rewrite.ts"
Features: jsc shell(11899) spawn(11899) tsconfig
Builtins: "bun:main" "bun:sqlite"
Elapsed: 228065768ms | User: 395348ms | Sys: 381233ms
RSS: 47.97MB | Peak: 0.15GB | Commit: 0.44GB | Faults: 8

panic(main thread): Segmentation fault at address 0x8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on macos x86_64 [RunCommand]

Segmentation fault at address 0x00000008

- *2 unknown/js code*
- `src.shell.interpreter.Interpreter.Expansion.next`
- `src.shell.interpreter.Interpreter.Expansion.next`
- `src.shell.interpreter.Interpreter.Expansion.next`
- `src.shell.interpreter.Interpreter.Expansion.next`
- `src.shell.interpreter.Interpreter.setupIOBeforeRun`
- `ShellInterpreterClass__finalize`
- `WebCore::ShellInterpreterPrototype__setCwdCallback`
- *1 unknown/js code*

**Comment by Electroid** [comment]
Is it possible to share the code? It looks like it might be shell related, not SQLite related.

**Comment by jsiwa** [comment]
> If you're still running into this, feel free to please include a reproduction to help us narrow down the cause of the issue and we will re-open the issue

There still has this problem, but I have lost the test code. Maybe like:
```javascript
while() {
  const data await = $`curl url`.json()
}
```
I will try to find the original file tomorrow.
