### ISSUE TITLE
slashes are facing the wrong way (Bundler)

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#11181]
### What version of Bun is running?

1.1.8+89d25807f

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Just have an asset. Import it. `Bun.build` it with this config:

```ts
naming: {
      asset: "[dir]/[name].[ext]",
},
```

### What is the expected behavior?

Lets say that the asset is at `src/assets/asset.png`
And the entrypoint is at: `src/foo.ts`

The asset path should be `./assets/asset.png`

### What do you see instead?

`./assets\asset.png`

**Comment by levii-pires** [comment]
@paperdave

**Comment by levii-pires** [comment]
![image](https://github.com/oven-sh/bun/assets/158751532/219c06d4-1086-4c6d-8d14-1ac4cd56f250)

**Comment by paperdave** [comment]
odd note, this only appears when enabling sourcemaps
