### ISSUE TITLE
Bun downloaded empty files for @types/express-session 

### ISSUE THREAD

**Issue by ab-shafei** [oven-sh/bun#11199]
Hello,

When I run `bun add -D @types/express-session ` bun downloaded empty files for type declarations .

![image](https://github.com/oven-sh/bun/assets/52571066/ae9343b6-3134-4b64-b475-cd2a47f93fdf)
![image](https://github.com/oven-sh/bun/assets/52571066/8d28b9b4-11d9-454b-92eb-df3dd79b9905)

**Comment by Electroid** [comment]
Could you share your package.json? and the log output? So we can see the version of Bun you're running

**Comment by Alshafei2430** [comment]
I solved this bug deleting my node_modules folder and run bun pm cache rm and reinstall with bun install.

**Comment by Electroid** [comment]
This was also likely fixed in Bun v1.1.8 or v1.1.9.

**Comment by Alshafei2430** [comment]
@Electroid  thank you for your help.
