### ISSUE TITLE
Fetch() response url is unchanged when request redirect is followed

### ISSUE THREAD

**Issue by Eckhardt-D** [oven-sh/bun#1119]
### Version

0.1.10

### Platform

Darwin  <redacted> 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

- fetch() does not change the response.url if the response was redirected.

```ts
const response = await fetch('https://google.com', {
  redirect: "follow",
}) // will redirect to www.google.com

response.redirected // true ☑️
response.url // https://google.com ❌

```

### How often does it reproduce? Is there a required condition?

Every redirected fetch() call.

### What is the expected behavior?

I expect `response.url` to report the redirected url. 

### What do you see instead?

I see the original url when calling `response.url`

### Additional information

🤷🏻‍♂️

**Comment by zhiyuang** [comment]
in 0.1.13, url is correct already, but redirected property is `undefined`.
