### ISSUE TITLE
bun install fails - 404 on private packages (maybe related)

### ISSUE THREAD

**Issue by kylemh** [oven-sh/bun#112]
<img width="1347" alt="Screen Shot 2022-01-24 at 1 44 03 PM" src="https://user-images.githubusercontent.com/9523719/150734689-25170902-b96c-45da-b13f-5240fd0fe96a.png">

My token is available via `.npmrc` in the project's root.

**Comment by Jarred-Sumner** [comment]
bun install [is unreliable](https://github.com/Jarred-Sumner/bun/issues/101) and fixing the https client is my top priority right now.

Private packages is not implemented yet, and will come shortly after fixing the https client.

What specific version of chalk is used in your repo? Does the repo use multiple versions of chalk?

The slow filesystem warning is also kind of interesting. It tests if renaming an empty file from the cache dir -> temp dir takes longer than 10ms. Maybe I should set that warning to print around 50ms though

```zig
if (this.options.log_level != .silent) {
    const elapsed = timer.read();
    if (elapsed > std.time.ns_per_ms * 10) {
        var cache_dir_path = std.os.getFdPath(cache_directory.fd, &path_buf) catch "it's";
        Output.prettyErrorln(
            "<r><yellow>warn<r>: Slow filesystem detected. If {s} is a network drive, consider setting $BUN_INSTALL_CACHE_DIR to a local folder.",
            .{cache_dir_path},
        );
    }
}
```

**Comment by kylemh** [comment]
I think there are multiple versions of `chalk` outlined in the lockfile, but only one in `package.json`
