### ISSUE TITLE
Segmentation fault at address 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by SenorLawyer** [oven-sh/bun#11207]
### How can we reproduce the crash?

by running my code (NODE_ENV=development bun --watch run src/index.ts)

### JavaScript/TypeScript code that reproduces the crash?

```shell
erm there are like 50 files
```

### Relevant log output

```shell
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\larsm\.bun\bin\bun.exe", "--watch", "run", "src/index.ts"
Features: jsc Bun.stdin(2) dotenv fetch transpiler_cache(3) tsconfig(4) WebSocket 
Builtins: "bun:main" "node:buffer" "node:events" "node:fs" "node:fs/promises" "node:http" "node:path" "node:string_decoder" "node:timers" "node:timers/promises" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws" 
Elapsed: 533ms | User: 31ms | Sys: 0ms
RSS: 0.17GB | Peak: 0.17GB | Commit: 0.22GB | Faults: 41007

panic(main thread): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.8/wr189d2580AqoiggV+h7u8Cu9ir2C8u0ne4ttkegzqkesq+xG2t9t1C6r+pF8kzqF4+pvFA2DD

--- Bun is auto-restarting due to crash [time: 1716242176859] ---
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [RunCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/uws.zig#L2619): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/shimmer.zig#L186): `cppFn`
- [`run_command.zig:1399`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/run_command.zig#L1399): `exec`
- [`cli.zig:1733`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1733): `start`

**Comment by Jarred-Sumner** [comment]
Can you provide the JavaScript/TypeScript code that reproduces this? The stack trace here is really hard for us to take any action on, it's essentially saying "something crashed while the event loop was doing work"
