### ISSUE TITLE
bun fails to stream videos

### ISSUE THREAD

**Issue by agentquackyt** [oven-sh/bun#11216]
### How can we reproduce the crash?

just run the code with a valid video

### JavaScript/TypeScript code that reproduces the crash?

```js
const express = require("express");
const app = express();
const fs = require("fs");

app.get("/", function (req, res) {
  res.sendFile(__dirname + "/index.html");
});

app.get("/video", function (req, res) {
  // Ensure there is a range given for the video
  const range = req.headers.range;
  if (!range) {
    res.status(400).send("Requires Range header");
  }

  // get video stats (about 61MB)
  const videoPath = "./../videos/1080/elonmusk.mov";
  const videoSize = fs.statSync("./../videos/1080/elonmusk.mov").size;

  // Parse Range
  // Example: "bytes=32324-"
  const CHUNK_SIZE = 10 ** 6; // 1MB
  const start = Number(range.replace(/\D/g, ""));
  const end = Math.min(start + CHUNK_SIZE, videoSize - 1);

  // Create headers
  const contentLength = end - start + 1;
  const headers = {
    "Content-Range": `bytes ${start}-${end}/${videoSize}`,
    "Accept-Ranges": "bytes",
    "Content-Length": contentLength,
    "Content-Type": "video/mp4",
  };

  // HTTP Status 206 for Partial Content
  res.writeHead(206, headers);

  // create video read stream for this particular chunk
  const videoStream = fs.createReadStream(videoPath, { start, end });

  // Stream the video chunk to the client
  videoStream.pipe(res);
});

app.listen(8000, function () {
  console.log("Listening on port 8000!");
});
```

### Relevant log output

```shell
Listening on port 8000!
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Users\jonij\.bun\bin\bun.exe", "index.js"
Features: http_server tsconfig(7) 
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:net" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" 
Elapsed: 2568ms | User: 62ms | Sys: 46ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.26GB | Faults: 43293

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [RunAsNodeCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/output.zig#L356): `panic`
- [`bun.zig:3119`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.zig#L3119): `assertionFailure`
- [`PipeReader.zig:420`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/io/PipeReader.zig#L420): `onFileRead`
- `uv__work_done`
- `??`
- `uv_run`
- [`uws.zig:2619`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/uws.zig#L2619): `run`
- `JSC__VM__holdAPILock`

**Comment by cirospaciari** [comment]
Fixed by https://github.com/oven-sh/bun/pull/11849
