### ISSUE TITLE
Randomly hangs on bun install (0.1.10)

### ISSUE THREAD

**Issue by yvg** [oven-sh/bun#1121]
### Version

0.1.10

### Platform

Darwin box.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

1. If it already exists, remove the node_modules folder : `rm -rf node_modules` in a given repo.
2. If it already exists, remove the bun installs cache: `rm -rf ~/.bun/install/cache`.
3. Run `bun install` in a given repo.

### How often does it reproduce? Is there a required condition?

It always reproduces, in previous versions it sometimes worked, but in 0.1.10 it has not worked so far.

### What is the expected behavior?

`bun install` should complete the installation.

### What do you see instead?

`bun install` hangs and it does not seem to hang on a particular dependency.

I've logged the output of three different tries from the same repo, the outputs seem different in size with no clear issue to me, here are the gists: 
 - https://gist.github.com/yvg/e4cdcde66133a1b84eab87b38de93740
 - https://gist.github.com/yvg/184fd97dec3f405869d46824f9cf07e4
 - https://gist.github.com/yvg/3683a47aa389298a309d5d96f79255d2 (note: this is an install without removing the cache)

### Additional information

One of the dependencies relies on a private registry in github, I am using a `bunfig.toml` file to configure the registry:

```
[install.scopes]

"@tooltime2019" = {token = "--REDACTED--", url = "https://npm.pkg.github.com"}
```

The Bearer token is outputted by the `--verbose` flag, I have redacted the token for obvious security reasons, and replaced it with the `--REDACTED--` string in the logs.

In addition, I've tried a run without the package from the private registry. It sadly hangs too.

**Comment by whjvenyl** [comment]
I have the same issue in a repository built with github actions, running into a timeout while trying to install the dependencies. Going back to version 0.1.8 successfully installs.

**Comment by yvg** [comment]
Can't reproduce this in 0.1.13, so I'll close this issue.

**Comment by ThatOneCalculator** [comment]
I'm now getting this again as of bun 1.0.28/29

**Comment by ThatOneCalculator** [comment]
Still occurs, tried completely erasing/reinstalling bun, node_modules, testing multiple projects, etc

**Comment by dylan-conway** [comment]
> Still occurs, tried completely erasing/reinstalling bun, node_modules, testing multiple projects, etc

can you try with `--ignore-scripts`? if it doesn't hang it might be a bug with bun running lifecycle scripts

**Comment by ThatOneCalculator** [comment]
Still occurs with `--ignore-scripts`, and hangs randomly each time it's restarted.

**Comment by ThatOneCalculator** [comment]
Still getting this even as of 1.0.30

**Comment by ThatOneCalculator** [comment]
.......never mind. It was DNS :facepalm:
