### ISSUE TITLE
socket.destroyed not sets to true and socket.write triggers the callback instantly

### ISSUE THREAD

**Issue by Mrgaton** [oven-sh/bun#11225]
### What version of Bun is running?

1.1.8

### What platform is your computer?

linux - debian

### What steps can reproduce the bug?

download a file from an express server that is over 512mb that is using bun

**Comment by Mrgaton** [comment]
the promise ends instanly before the data arrived to the client

**Comment by Mrgaton** [comment]
Yes, the callback trigers instanly. How i can fix it?

**Comment by Mrgaton** [comment]
And `req.socket.destroyed` seems to not set to true when download is cancelled

**Comment by Electroid** [comment]
This is because Bun's `node:http` implementation uses `fetch()` and we do not allow access to the `request.socket`. This is something we want to change.

**Comment by Electroid** [comment]
Duplicate of #11225

**Comment by Electroid** [comment]
Duplicate of #11230
