### ISSUE TITLE
Bun.serve streams memory leak

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1122]
Something isn’t being freed. Running the benchmark in `bench/react-hello-world` Shows increasing memory usage over time

To investigate:
- genersteHeapSnapshot() and view it in Safari
- heapStats() and see counts of what objects are going up in each request

**Comment by GabrieleGigante** [comment]
I've found the same issue using Bun.serve in the blank template

**Comment by Jarred-Sumner** [comment]
Fixed today
