### ISSUE TITLE
bun install should normalize line endings

### ISSUE THREAD

**Issue by guigui64** [oven-sh/bun#1125]
### Version

All

### Platform

Linux 64bit

### What steps will reproduce the bug?

`bun install live-server`
`./node_modules/.bin/live-server`

Will raise this error:

> /usr/bin/env: ‘node\r’: No such file or directory

`npm install` normalizes the line endings

### What do you see instead?

> /usr/bin/env: ‘node\r’: No such file or directory

### Additional information

According to Jarred on discord:

> I looked at npm’s code and they do this specifically for bin files

**Comment by Kruithne** [comment]
This prevents usage of `resedit` via Bun. Temporarily resolving this in build pipelines by running `sed -i 's/\r$//' "$(which resedit)"` after installation. You can replace `resedit` with any script effected with this issue.

Note: Hacky workaround, obviously not for production use.

**Comment by ghost** [comment]
See #2516

**Comment by paperclover** [comment]
ah the linked issue is a duplicate of this.
