### ISSUE TITLE
Error while running src/build.ts

### ISSUE THREAD

**Issue by drosanda** [oven-sh/bun#11259]
### How can we reproduce the crash?

From this repository -> https://github.com/drosanda/DAFTAR-API-LOKAL-INDONESIA/tree/add_api_lokasi_dan_bank

then npm install

then npm run check

it caused error

### Relevant log output

```shell
Bun v1.1.9 (bb13798d) Windows x64
Args: "bun", "run", "src/build.ts"
Features: jsc fetch(127) tsconfig(2)
Builtins: "bun:main" "node:fs/promises" "node:https" "node:path" "node:string_decoder" "node:util/types" "node-fetch"
Elapsed: 286685ms | User: 406ms | Sys: 93ms
RSS: 0.23GB | Peak: 0.23GB | Commit: 0.32GB | Faults: 89902

panic(main thread): Segmentation fault at address 0x1A
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x0000001A

- *10 unknown/js code*

Features: jsc, fetch, tsconfig

**Comment by nektro** [comment]
just tried running `bun install` in the linked repo and was unable to reproduce the error

if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
