### ISSUE TITLE
Panic Error when run "bun install"

### ISSUE THREAD

**Issue by dungnthe130669** [oven-sh/bun#11267]
### How can we reproduce the crash?

I run an existing project, which is fine in WSL, but crash on window (both Window 10 and 11)

### Relevant log output

```shell
bun install
[1.01ms] ".env"
bun install v1.1.9 (bb13798d)
  🚚 yallist... error: InstallFailed extracting tarball for @esbuild/win32-x64
  ⚙️  esbuild [1/2] ============================================================
Bun v1.1.9 (bb13798d) Windows x64
Args: "C:\Users\DuNT\.bun\bin\bun.exe", "install"
Features: dotenv extracted_packages(266) lifecycle_scripts(2) spawn(2) 
Elapsed: 105355ms | User: 1828ms | Sys: 112781ms
RSS: 0.27GB | Peak: 0.27GB | Commit: 0.38GB | Faults: 91069

panic(main thread): Segmentation fault at address 0x113
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.9/wi1bb13798AgohkICY\ctiuser.dllgmvdCY\ctiuser.dllohkdCa\KERNEL32.DLLqwoCCe\KERNELBASE.dllqy5QCe\KERNELBASE.dllsujgBCa\KERNEL32.DLLo/wFCY\ctiuser.dlluz1b6j8xeutp2Dkl/2DA2AmR
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on windows x86_64 [InstallCommand]

Segmentation fault at address 0x00000113

- ??? at `0x75e60` in ctiuser.dll
- ??? at `0x74814` in ctiuser.dll
- ??? at `0x9105` in KERNEL32.DLL
- ??? at `0x43325` in KERNELBASE.dll
- ??? at `0x806e6` in KERNELBASE.dll
- ??? at `0x161f4` in KERNEL32.DLL
- ??? at `0x6eb37` in ctiuser.dll
- `uv_spawn`
- [`libuv.zig:1486`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/deps/libuv.zig#L1486>): `spawn`
- [`process.zig:1189`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/api/bun/process.zig#L1189>): `spawnProcess`

**Comment by Electroid** [comment]
Are you able to share your `package.json`?

**Comment by nektro** [comment]
Hi! if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
