### ISSUE TITLE
[Bug] Bun 1.1.9 (from 1.1.8) windows, bun install hangs on resolving. Never completes command.

### ISSUE THREAD

**Issue by cpakken** [oven-sh/bun#11272]
### What version of Bun is running?

1.1.9+bb13798d9

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Bun upgrade from 1.1.8 to 1.1.9
`bun install` hangs on resolve and never completes command

To replicate:
`bun init` in a new directory
This commands also hangs and need to manually ctrl-c to exit `bun init`

Then `bun i` or `bun install`
Hangs on Resolving

![image](https://github.com/oven-sh/bun/assets/61718569/d8707ea9-a7d5-417f-adad-ac0d902a992f)

`bun add`, `bun install` commands also hangs and does not work in existing projects after upgrading.

**Comment by Jarred-Sumner** [comment]
Fixed in canary build.

Will be available in Bun v1.1.10 releasing tonight.

In the meantime:

```
bun upgrade --canary
```
