### ISSUE TITLE
ENOENT parsing package.json

### ISSUE THREAD

**Issue by supfiger** [oven-sh/bun#11287]
### How can we reproduce the crash?

`$ bun add -g supabase`

### Relevant log output

```shell
$ bun add -g supabase
bun add v1.1.9 (bb13798d)
============================================================
Bun v1.1.9 (bb13798d) macOS x64
Args: "bun", "add", "-g", "supabase"
Elapsed: 48ms | User: 20ms | Sys: 32ms
RSS: 14.92MB | Peak: 14.92MB | Commit: 1.07GB | Faults: 1505

panic(main thread): ENOENT parsing package.json
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on macos x86_64 [AddCommand]

**panic**: [0m[31mENOENT[0m parsing package.json[0m

- `debug.panicExtra__anon_319397`
- `debug.panic__anon_292088`
- `src.output.panic__anon_70956`
- `src.install.install.PackageManager.updatePackageJSONAndInstallWithManager__anon_70838`
- `src.cli.Cli.start`
- `main`
- *2 unknown/js code*

**Comment by dylan-conway** [comment]
Fixed in #11254 and available in canary (to upgrade run `bun upgrade --canary`). The bugfix will be included in `v1.1.10`
