### ISSUE TITLE
Cant install global packages on MacOS

### ISSUE THREAD

**Issue by Alt-iOS** [oven-sh/bun#11299]
### How can we reproduce the crash?

Try to install any global package in macos with bun, for example `bun install --global tailwind
`

### Relevant log output

```shell
bun add v1.1.9 (bb13798d)
============================================================
Bun v1.1.9 (bb13798d) macOS Silicon
Args: "bun", "install", "--global", "cowsay"
Elapsed: 19ms | User: 13ms | Sys: 13ms
RSS: 16.60MB | Peak: 16.60MB | Commit: 1.07GB | Faults: 623

panic(main thread): ENOENT parsing package.json
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.9/MI1bb13798AA2/5qoC+l3ooCmr5koCu14xD2qwB2tc__A0eNqTjjbIlY42Nsx19fN39QuRjjbIVShILCrOzEtXKEhMzk5MT9XLKs7PA0kAACt0DjI

zsh: trace trap  bun install --global cowsay
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on macos aarch64 [AddCommand]

**panic**: [0m[31mENOENT[0m parsing package.json[0m

- `debug.panicExtra__anon_319427`
- `debug.panic__anon_292037`
- `src.output.panic__anon_70902`
- `src.install.install.PackageManager.updatePackageJSONAndInstallWithManager__anon_70784`
- `src.cli.Cli.start`
- `main`
- *2 unknown/js code*

**Comment by dschuessler** [comment]
Same here for `bun install --global surge`.
