### ISSUE TITLE
Crash when using font in Next.js 14

### ISSUE THREAD

**Issue by BbayuGt** [oven-sh/bun#11292]
### How can we reproduce the crash?

Just use any font in your projects

Note that im using Ubuntu 22.04 with WSL (Windows 11)

### JavaScript/TypeScript code that reproduces the crash?

```shell
//👇 Import Open Sans font
import { Open_Sans } from "next/font/google";

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <main>
      <div>
        <h1 className={openSans.className}>Hello World</h1>
      </div>
    </main>
  );
}
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on linux x86_64 [AutoCommand]

Bus error at address 0x558246BB3B60

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`

**Comment by BbayuGt** [comment]
Just found out about #8518, this might be the problem but it crashes only when using font.

**Comment by tonyxiao** [comment]
I'm still getting this error on a fresh install of `bun create next-app`. Doesn't seem that this issue is resolved?

**Comment by tonyxiao** [comment]
```
 ⨯ Error: @next/font/google failed to run or is incorrectly configured.
If you just installed `@next/font`, please try restarting `next dev` and resaving your file.

Read more: https://nextjs.org/docs/basic-features/font-optimization
    at @next/font/google (.next/server/pages/index.js:86:18)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:11:75)
    at ./pages/index.tsx (.next/server/pages/index.js:65:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42) {
  page: '/'
}```

**Comment by tonyxiao** [comment]
https://github.com/oven-sh/bun/issues/17037 filed a new issue.
