### ISSUE TITLE
Postgres.js | CONNECTION_CLOSED issue.

### ISSUE THREAD

**Issue by amjed-ali-k** [oven-sh/bun#11301]
### What version of Bun is running?

1.1.9+bb13798d9

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

[Test Repo to reproduce this issue](https://github.com/amjed-ali-k/bun-elysia-drizzle-postgres-test)

### What do you see instead?

https://github.com/oven-sh/bun/issues/7325#issuecomment-2123535963
https://github.com/porsager/postgres/issues/817#issuecomment-2030636937
![image](https://github.com/oven-sh/bun/assets/86785660/2b0be61a-7a16-450f-a122-02faf566878e)

### Additional information
This issue frequently occurred to me for requests when the server was idling.

Related:
https://github.com/oven-sh/bun/issues/7325#issuecomment-2126030305
https://github.com/porsager/postgres/issues/749
https://github.com/porsager/postgres/issues/817#issuecomment-2117616412

Possible Duplicate of:
https://github.com/oven-sh/bun/issues/8946
https://github.com/oven-sh/bun/issues/7325

**Comment by amjed-ali-k** [comment]
Postgres.js 3.4.4 | Bun 1.1.12
![image](https://github.com/user-attachments/assets/79ee363e-23d7-4d5d-84dc-8c5d12c005e2)

**Comment by lord007tn** [comment]
Same problem with Hono
is there any fix ?

**Comment by amjed-ali-k** [comment]
👀 https://github.com/oven-sh/bun/issues/11230

**Comment by amjed-ali-k** [comment]
This issue seems fixed in bun 1.1.39 👍🏼.
