### ISSUE TITLE
(Bundler) Another Windows backslash bug

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#11300]
### How can we reproduce the crash?

Just trying to use `Bun.build`

### JavaScript/TypeScript code that reproduces the crash?

```shell
// build-entrypoint.tsx

// this resolves to 'C:\Projs\bunsai2\examples\node_modules\bunsai\src\extra\react\index.tsx'
import { make, React } from "bunsai/react";

// ...
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on windows x86_64 [AutoCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Projs\bunsai2\examples\node_modules\bunsai\src\extra\react\index.tsx'

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`fs.zig:1724`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/fs.zig#L1724>): `assertPrettyIsValid`
- [`bundle_v2.zig:2015`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bundler/bundle_v2.zig#L2015>): `runResolutionForParseTask`
- [`event_loop.zig:246`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/event_loop.zig#L246>): `run`
- [`bundle_v2.zig:1728`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bundler/bundle_v2.zig#L1728>): `runFromJSInNewThread`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

**Comment by levii-pires** [comment]
#11181

**Comment by levii-pires** [comment]
@paperdave 
I think this could help:

```bash
$ git clone https://github.com/levii-pires/bunsai2
$ cd bunsai2
$ bun install
$ bun link
$ cd examples
$ bun install
$ bun byte
```

**Comment by levii-pires** [comment]
> @paperdave I think this could help:
> 
> ```shell
> $ git clone https://github.com/levii-pires/bunsai2
> $ cd bunsai2
> $ bun install
> $ bun link
> $ cd examples
> $ bun install
> $ bun byte
> ```

The bug pops out when BunSai tries to build a file and this file imports `bunsai/react` (that, in my case, resolved to `'C:\Projs\bunsai2\examples\node_modules\bunsai\src\extra\react\index.tsx'`)
