### ISSUE TITLE
"bun run dev" not run

### ISSUE THREAD

**Issue by shiyanaaa** [oven-sh/bun#11324]
### How can we reproduce the crash?

bun create vue@latest
bun install
bun run dev

### JavaScript/TypeScript code that reproduces the crash?

```shell
{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "typescript": "^5.2.2",
    "vite": "^5.2.0",
    "vue-tsc": "^2.0.6"
  }
}
```

### Relevant log output

```shell
bun run dev
$ vite
error: Failed due to error: bunsh: No such file or directory:
```

### Stack Trace (bun.report)

 bun run dev
$ vite
error: Failed due to error: bunsh: No such file or directory:

**Comment by Jarred-Sumner** [comment]
What version of Bun? From the errors, this looks like a very old version of Bun. I suggest running `bun upgrade` and trying again.

**Comment by shiyanaaa** [comment]
> What version of Bun? From the errors, this looks like a very old version of Bun. I suggest running `bun upgrade` and trying again.

I am currently using version 1.1.10, and I had this problem when I first installed 1.1.8,
I also had this problem when I upgraded to 1.1.9 via bun upgrade
Runs on windows11
I had no problems running Windows 10 on two other computers.

**Comment by BenjaBobs** [comment]
I've seen this issue on one of my coworker's computers, and I suspect it may have to do with special characters in the windows user name.

**Comment by shiyanaaa** [comment]
> 我在同事的一台计算机上看到了这个问题，我怀疑它可能与 Windows 用户名中的特殊字符有关。
my windows username is “Chen” ，

> I've seen this issue on one of my coworker's computers, and I suspect it may have to do with special characters in the windows user name.

my windows username is “Chen”

**Comment by chengazhen** [comment]
> I've seen this issue on one of my coworker's computers, and I suspect it may have to do with special characters in the windows user 

Yes! you are right.  thanks

**Comment by chengazhen** [comment]
> > 我在同事的一台计算机上看到了这个问题，我怀疑它可能与 Windows 用户名中的特殊字符有关。
> > my windows username is “Chen” ，
> 
> > I've seen this issue on one of my coworker's computers, and I suspect it may have to do with special characters in the windows user name.
> 
> my windows username is “Chen”

i think he means your file path

**Comment by shiyanaaa** [comment]
> > > 我在同事的一台计算机上看到了这个问题，我怀疑它可能与 Windows 用户名中的特殊字符有关。my windows username is “Chen” ，
> > 
> > 
> > > I've seen this issue on one of my coworker's computers, and I suspect it may have to do with special characters in the windows user name.
> > 
> > 
> > my windows username is “Chen”
> 
> i think he means your file path

oh,my file path has chinese,I will try again in the evening.

**Comment by chengazhen** [comment]
同志有点卷! 晚上就别学了! 放松放松

**Comment by shiyanaaa** [comment]
> 同志有点卷! 晚上就别学了! 放松放松

卷一点吧，多学点没坏处

**Comment by shiyanaaa** [comment]
> 同志有点卷! 晚上就别学了! 放松放松

没毛病，确实是文件路径中有中文
