### ISSUE TITLE
Random errors after upgrading from v1.0.17

### ISSUE THREAD

**Issue by dszymon** [oven-sh/bun#11326]
### What version of Bun is running?

1.1.9+bb13798d9

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

`bun run` a code with the following:
a) multiple macros created like:
1.ts
```ts
import { fnA, fnB } from './some.macro' assert { type: 'macro' };

const a = fnA();
const b = fnB();
```
some.macro.ts
```ts
import path from 'node:path';

export function fnA() {
    return Bun.file(path.join(__dirname, 'dir', 'fileA.ext')).text();
}

export function fnB() {
    return Bun.file(path.join(__dirname, 'dir', 'fileB.ext')).text();
}
```
b) inversify and its `@injectable` decorators

### What is the expected behavior?

Bun runs the app

### What do you see instead?

with macro:
```ts
7 | const a = fnA();
                      ^
ReferenceError: Can't find variable: fnA
      at module code (/path/to/file.ts:7:19)
      at requestFetch (:1:11)
      at requestInstantiate (:1:11)
      at requestSatisfyUtil (:1:11)
```

without the macro:
```ts
3210 |     var isFunction = serviceIdentifier === Function;
3211 |     var isUndefined = serviceIdentifier === undefined;
3212 |     var isUnknownType = isObject || isFunction || isUndefined;
3213 |     if (!isBaseClass && isUnknownType) {
3214 |       var msg = MISSING_INJECT_ANNOTATION + " argument " + index + " in class " + constructorName + ".";
3215 |       throw new Error(msg);
                   ^
error: Missing required @inject or @multiInject annotation in: argument 0 in class SomeDecoratedClass.
```

after a few changes:
```
15 | export class RandomClass {
            ^
ReferenceError: Cannot access uninitialized variable.
```

### Additional information

The code used to work in Bun v1.0.17, so downgraded with the command `curl -fsSl https://bun.sh/install | bash -s "bun-v1.0.17"` and ran the app. It started without raising the error mentioned.

Surprisingly, after upgrading to Bun v1.19 with `bun upgrade`, the code still works. I suspected the transpiler cache, so I've altered its behavior with the following commands:
- `BUN_RUNTIME_TRANSPILER_CACHE_PATH=0 bun ./src/app.ts`
- `BUN_RUNTIME_TRANSPILER_CACHE_PATH=./wtf bun ./src/app.ts` 
and the app kept working

According to `madge`, there are no circular dependencies:
```sh
npx madge -c --extensions ts,js .
⠋ Finding files=============
Processed 80 files (435ms) (1 warning)

✔ No circular dependency found!
```

The code also works on a Docker container:
```dockerfile
FROM oven/bun

WORKDIR /app
ADD package.json tsconfig.json bun.lockb ./
RUN bun i
COPY ./src ./src
CMD bun run ./src/app.ts subcommand
```

**Comment by Jarred-Sumner** [comment]
Can you provide a reproduction that we can? The code above does not reproduce the issue

**Comment by dszymon** [comment]
> Can you provide a reproduction that we can run? The code above does not reproduce the issue

Unfortunately, that won't be possible as I can't pinpoint the issue, and this is the company's internal repository. But I'm sure the problem exists because a coworker could replicate it

**Comment by Jarred-Sumner** [comment]
Okay. I'm guessing this is actually unrelated to macros and instead something to do with TypeScript experimental decorators in a computed property, or an assignment to a typescript decorator. Another guess is that an import is missing a `type` attribute, like `import {type MyInterface}` instead of `import {MyInterface}`

**Comment by dszymon** [comment]
> Okay. I'm guessing this is actually unrelated to macros and instead something to do with TypeScript experimental decorators in a computed property, or an assignment to a typescript decorator. Another guess is that an import is missing a `type` attribute, like `import {type MyInterface}` instead of `import {MyInterface}`

We use an ESLint rule to add the `type` keyword to every import used as a type (it detects the type used as a value via the decorator metadata).

As mentioned, the code started working after the downgrade to v10.17, starting the app, and doing the upgrade. It also works in a clean container, so my guess would be a corrupted transpiler cache (maybe somehow related to `bun build --outfile` and/or `--compile` as this was the first command I ran on v1.1.9)

**Comment by dszymon** [comment]
closing as probably unresolvable
