### ISSUE TITLE
Add bun list command

### ISSUE THREAD

**Issue by alinco8** [oven-sh/bun#11338]
### What is the problem this feature would solve?

I can't see the package I'm currently install in.

### What is the feature you are proposing to solve the problem?

add
`bun list`
`bun ls`
command

### What alternatives have you considered?

use
`npm ls`

**Comment by Jarred-Sumner** [comment]
Try `bun pm ls`

**Comment by alinco8** [comment]
@Jarred-Sumner

**Comment by alinco8** [comment]
Oh my God, I didn't know that. Thanks!

**Comment by alinco8** [comment]
Oh my God, I didn't know that. Thanks!
