### ISSUE TITLE
Bun treating unknown proxy protocol as HTTP instead of fail

### ISSUE THREAD

**Issue by rinsuki** [oven-sh/bun#11343]
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. Open Terminal and put `nc -l 9999 | hexdump -C` (you might be need to install netcat)
2. Open Another Terminal and run `HTTPS_PROXY=socks5://localhost:9999 bun repl` (If your machine already have a cached REPL, run some HTTPS request like `await fetch("https://httpbin.org/get")`

### What is the expected behavior?

Connect with SOCKS5 proxy protocol, instead of HTTP CONNECT.

or, at least, throw error something like `unknown proxy protocol specified`

### What do you see instead?

Bun will try to connect with HTTP CONNECT, instead of SOCKS5 protocol.

<img width="1446" alt="image" src="https://github.com/oven-sh/bun/assets/6533808/3236d3b9-234e-4a61-a4d4-abb29072e77c">

<details>
<summary>Note: actual SOCKS5 protocol would like:</summary>

![image](https://github.com/oven-sh/bun/assets/6533808/b4899725-4865-4431-bdde-b06d1ed980c5)

</details>

**Comment by erikschul** [comment]
@Jarred-Sumner This is closed as completed, but does Bun support SOCKS? I'm still getting an error with v1.2.0

Perhaps this should be reopened?
