### ISSUE TITLE
tesseract.js recognize() uber slow

### ISSUE THREAD

**Issue by mefistofelix** [oven-sh/bun#11350]
### What version of Bun is running?

1.1.10-canary.1+c689b2b26

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```js
import ocr from 'tesseract.js'
let ocr_s = ocr.createScheduler()
let ocr_w = await ocr.createWorker('eng',1,{
  logger: function(m){console.log(m.progress)}
})
ocr_s.addWorker(ocr_w)
//x.jpg is 64kb large
let ocr_res = await ocr_s.addJob('recognize','x.jpg')
console.dir(ocr_res)
process.exit()
```

### What is the expected behavior?

work fast as nodejs

### What do you see instead?

it takes some minutes on a decent laptop, nodejs requires just 1 second

**Comment by Lawlzer** [comment]
Also happening for me. ~70s in Bun, ~3s in Node. 
Here's a slightly easier test (that runs in Node and Bun, for easy comparison)

```ts
// import { createWorker } from 'tesseract.js';
const { createWorker } = require('tesseract.js');

(async () => {
	const start = Date.now();
	const worker = await createWorker('eng', 1, {
		logger: (m) => {
			console.log(m);
		},
	});
	const ret = await worker.recognize('https://tesseract.projectnaptha.com/img/eng_bw.png');
	console.log(ret.data.text);
	await worker.terminate();

	console.log(`total time taken: ${Date.now() - start}m`);
})();
```

**Comment by dylan-conway** [comment]
FTL JIT was enabled on Windows in Bun v1.1.19, significantly improving `tesseract.js`. On my machine with a 538kb jpg:

```
bun-v1.1.18: 04:28.04
bun-v1.1.38: 00:03.06
```
