### ISSUE TITLE
Crash while trying to load the repl

### ISSUE THREAD

**Issue by easrng** [oven-sh/bun#11359]
### How can we reproduce the crash?

my repro steps are run `bun repl`, wait for a while (it hangs for ~45s), observe crash
other information:
```
$ uname -a
Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2899.998
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 5799.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 15
model           : 6
model name      : Common KVM processor
stepping        : 1
microcode       : 0x1
cpu MHz         : 2899.998
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 5799.99
clflush size    : 64
cache_alignment : 128
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

### Relevant log output

```shell
$ bun repl
============================================================
Bun v1.1.10 (5102a944) Linux x64 (baseline)
Args: "bun" "/tmp/bunx-1000-bun-repl@latest/node_modules/.bin/bun-repl"
Features: jsc transpiler_cache(2) tsconfig(3) 
Builtins: "bun:main" "node:assert" "node:fs" "node:module" "node:os" "node:path" "node:readline" "node:string_decoder" "node:url" "node:util" "node:util/types" 
Elapsed: 47624ms | User: 28433ms | Sys: 16104ms
RSS: 13.76GB | Peak: 8.00GB | Commit: 13.76GB | Faults: 15

panic(main thread): Segmentation fault at address 0x5EEC4000000
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.10/Ba15102a94AiggggF2/tkjE+kgPuwo1hDi5698Cy3qohD21ky8D__6t115D6t115DA28+Chgggg8B

Illegal instruction
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x5EEC4000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`encoding.zig:905`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/webcore/encoding.zig#L905>): `src.string.SliceWithUnderlyingString.transcodeFromOwnedSlice`
- [`node_fs.zig:5487`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/node/node_fs.zig#L5487>): `src.bun.js.node.node_fs.NodeFS.readFile__anon_306318`
- [`node_fs_binding.zig:64`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/node/node_fs_binding.zig#L64>): `NodeJSFSPrototype__readFileSync`
- [`ZigGeneratedClasses.cpp:27203`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4//build/bun/build/codegen/ZigGeneratedClasses.cpp#L27203>): `WebCore::NodeJSFSPrototype__readFileSyncCallback`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/ld-temp.o#L0>): `llint_op_call`

**Comment by RiskyMH** [comment]
I can't seem to reproduce, if this is still an issue @easrng let me know and I can re-open.
The linked issues also seem to be fixed, so this should be too!
