### ISSUE TITLE
Bun package installer crashing with issue 

### ISSUE THREAD

**Issue by itsyashvardhan** [oven-sh/bun#11354]
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Current version of dependencies in project :
```json
  "dependencies": {
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522",
    "next": "15.0.0-rc.0"
  },
```
Error thrown in console : 
```
$ next dev --turbo
error: bin executable does not exist on disk

Bun failed to remap this bin to its proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues

error: script "dev" exited with code 255
```
even after executing `bun install --turbo`, it's returning the same error

**Comment by Jarred-Sumner** [comment]
Please run `bun upgrade` and try again. The current version of Bun is v1.1.10.

**Comment by PythonicBoat** [comment]
@Jarred-Sumner even after upgrading bun to latest version `1.1.10`, the console outputs the same error

**Comment by PythonicBoat** [comment]
well surprisingly it worked, after doing it for the second time 
```
rm -rf node_modules
rm bun.lockb
```
Re-install the dependencies :
```
bun install
bun upgrade
```
