### ISSUE TITLE
Bunx crash on windows in the v1.1.10

### ISSUE THREAD

**Issue by Lan-Hekary** [oven-sh/bun#11352]
### How can we reproduce the crash?

I just update to the latest version on windows.
I tested it with `bunx cowsay hello`
It crashed immediately.

### JavaScript/TypeScript code that reproduces the crash?

```shell
bunx cowsay hello
```

### Relevant log output

```shell
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\Lan\scoop\apps\bun\1.1.10\bun.exe" "add" "cowsay@latest" "--no-summary" "--no-cache" "--force"
Elapsed: 5ms | User: 0ms | Sys: 15ms
RSS: 25.37MB | Peak: 25.37MB | Commit: 71.75MB | Faults: 6383

panic(main thread): attempt to unwrap error
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.10/wI15102a94AA86glCwvqpComgqEu56rEu15xFqn4BiiJo3ht+CCa\KERNEL32.DLLo05FCU\ntdll.dllirzUA0eNpLLClJzS0oUSjJVyjNKy9KLFBILSrKLwIAbHQJCg
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [AddCommand]

**panic**: attempt to unwrap error

- [`mem.zig:197`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/deps/zig/lib/std/mem.zig#L197>): `copyForwards`
- [`windows.zig:3402`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/windows.zig#L3402>): `GetFinalPathNameByHandle`
- [`install.zig:7401`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L7401>): `initWithCLI`
- [`install.zig:8528`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L8528>): `updatePackageJSONAndInstall`
- [`cli.zig:1468`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L1468>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Related https://github.com/ziglang/zig/issues/18756
