### ISSUE TITLE
`Unexpected keyword "export"` when exporting enum from namespace

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#1136]
### Version

0.1.10

### Platform

Darwin computername.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Create file:

```ts
// test.ts
namespace ns {
  export enum Blarg {}
}
```

Then `bun run` it

Results in:

```bash
$ bun run test.ts
1 | namespace ns {
2 |   export enum Blarg {}
             ^
SyntaxError: Unexpected keyword 'export'
      at /path/to/test.ts:2:9
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Compilation succeeds

### What do you see instead?

```bash
$ bun run test.ts
1 | namespace ns {
2 |   export enum Blarg {}
             ^
SyntaxError: Unexpected keyword 'export'
      at /path/to/test.ts:2:9
```

**Comment by Jarred-Sumner** [comment]
There is currently very little test coverage for `namespace` in TS, which needs to be fixed
