### ISSUE TITLE
bun compile project into single executable

### ISSUE THREAD

**Issue by uwussimo** [oven-sh/bun#1139]
### What is the problem this feature will solve?

Instead of porting js||ts files, developer will be running single executable on top of Bun/JavaScriptCore. 

### What is the feature you are proposing to solve the problem?

Bun will create an executable that will include bun itself and project files, assets inside like `deno compile`.

### What alternatives have you considered?

Maybe use existing libraies or add support for bun to those like ncc, pkg, etc...

**Comment by kdabir** [comment]
related issue to watch: https://github.com/oven-sh/bun/issues/441

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/441
