### ISSUE TITLE
HMR Failure after running basic react-app template

### ISSUE THREAD

**Issue by mwarger** [oven-sh/bun#114]
I created a test app with the basic react-app template.  I installed dependencies and ran bun (and tried again with bun dev).  The HMR doesn't appear to work, and when reloading the page, it spits out the BusError message.  The first example has an `HMR WebSocket error`, but that doesn't seem to consistently show up.

```
❯ bun
[8.00ms] bun!! v0.0.68


  Link: http://localhost:3000
        ./public/index.html 


HMR WebSocket error: missing Sec-WebSocket-Version header
📜  File change: src/App.jsx

BusError at 2535445954560


–––– bun meta ––––
Bun v0.0.68 macOS Silicon
AutoCommand: single_page_app_routing fast_refresh hot_module_reloading public_folder define loaders 
HTTP: 1
Elapsed: 85787ms | User: 27ms | Sys: 54ms
RSS: 10.96MB | Peak: 31.57MB | Commit: 46.89MB | Faults: 361
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

```
❯ bun dev
[3.00ms] bun!! v0.0.68


  Link: http://localhost:3000
        ./public/index.html 


📜  File change: src/App.jsx

BusError at 4159572738048


–––– bun meta ––––
Bun v0.0.68 macOS Silicon
DevCommand: single_page_app_routing fast_refresh hot_module_reloading public_folder define loaders 
HTTP: 1
Elapsed: 28585ms | User: 26ms | Sys: 40ms
RSS: 11.08MB | Peak: 29.98MB | Commit: 50.82MB | Faults: 207
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by Jarred-Sumner** [comment]
Thanks for the issue. Looking into it

**Comment by Jarred-Sumner** [comment]
@mwarger can you give it another try in Bun v0.0.69? I believe the underlying cause here was in the HTTP client, it was causing crashes on some computers after bun checked for upgrades

**Comment by mwarger** [comment]
@Jarred-Sumner `bun upgrade` failed, so I had to upgrade manually.  But the app now works and HMR is so fast!  Thank you.

**Comment by Aakarshak1** [comment]
Hi can we reopen this issue?  As of today, HMR is not working with bun v0.7.3
