### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by coratgerl** [oven-sh/bun#11403]
### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x00000018

- *2 unknown/js code*
- `JSC::CodeBlock::finishCreation`
- `JSC::ScriptExecutable::prepareForExecutionImpl`
- `operationDefaultCall`
- *1 unknown/js code*
- `llint_entry`
- `llint_entry`
- `llint_entry`
- `vmEntryToJavaScript`

**Comment by Jarred-Sumner** [comment]
I think this was fixed by https://github.com/WebKit/WebKit/pull/29073

But we haven't upgraded WebKit yet

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.24
