### ISSUE TITLE
unable to remove package using the bun

### ISSUE THREAD

**Issue by Boby900** [oven-sh/bun#11411]
### What version of Bun is running?

1.1.10

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

using the cmd `bun uninstall turbo`, I was trying to remove the package turbo

### What is the expected behavior?

It didn't remove the package it persists.
![Screenshot (484)](https://github.com/oven-sh/bun/assets/111265239/13acfa7a-7954-4689-9e71-f3c489829efa)

### What do you see instead?

after running `bun uninstall turbo --global` and `bun uninstall turbo`, I was able to see the version of the package 
```bash
turbo --version
1.13.4-canary.5
```

### Additional information

when I was trying to remove the package ("both in my project and globally") using the bun I was not able to, in the end I removed it using the npm then it finally removed the package.

![Screenshot (484)](https://github.com/oven-sh/bun/assets/111265239/2ebe3a5c-9026-4fbf-9127-77fd95fb91f1)

**Comment by dylan-conway** [comment]
Are you able to repro this consistently? If so, after running `bun uninstall turbo --global` can you run `which turbo`? My hunch is you also had turbo globally installed with npm, which is why uninstalling it with npm fully removed it from your system. If `which turbo` returns a path to npm's global cache, this is the case.

**Comment by Boby900** [comment]
> Are you able to repro this consistently? If so, after running `bun uninstall turbo --global` can you run `which turbo`? My hunch is you also had turbo globally installed with npm, which is why uninstalling it with npm fully removed it from your system. If `which turbo` returns a path to npm's global cache, this is the case.

thanks for jumping in.
yes, I installed Turbo globally using npm.
I successfully removed it globally with npm.
![Screenshot (496)](https://github.com/oven-sh/bun/assets/111265239/02b68673-5dfc-4261-9b8f-29d9cfafc6d9)
