### ISSUE TITLE
Error setup tRPC with Next.js

### ISSUE THREAD

**Issue by architectureman** [oven-sh/bun#1141]
### Version

0.1.10

### Platform

Darwin Mikes-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Just build follow [t3-stack video](https://www.youtube.com/watch?v=syEWlxVFUrY&t=232s&ab_channel=TomDoesTech) 

### What do you see instead?

**undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')**
λ() node_modules/react-dom/cjs/react-dom.development.js:994:29
```js
      error('disabledDepth fell below zero. ' + 'This is a bug in React. Please file an issue.');
    }
  }
}

var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;
/*                          ^ happened here                             */
```
Stack trace:
```js

  λ()   node_modules/react-dom/cjs/react-dom.development.js:994:29
  λ()   node_modules/react-dom/cjs/react-dom.development.js:29864:71
  λ()   node_modules.server.bun:0:16354
  λ()   node_modules/react-dom/index.js:37:27
  λ()   node_modules.server.bun:0:16354
  (esm) node_modules/react-query/es/react/reactBatchedUpdates.js:1:0
```
Info:
  > bun v0.1.10
  > framework: bun-framework-next@12.2.4
  > macOS 12.6.0 (x64)
  > User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63
  > Pathname: /

[Error Image](https://i.imgur.com/pOiVI1P.png)

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
