### ISSUE TITLE
Bun with next dev server is freezing while HMR and doesnt update UI after code changes. 

### ISSUE THREAD

**Issue by devhik0** [oven-sh/bun#11448]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22000.0 x64

### What steps can reproduce the bug?

Open a next.js app with bun and look its compile times and change the code to see the effects to UI.

### What is the expected behavior?

It should update UI in short time due to HMR and shouldnt hang up for 1-2 min

### What do you see instead?

○ Compiling /tasks ...
✓ Compiled in 39.9s (sometimes around 60)
✓ Compiled /tasks in 18.2s

### Additional information

With other runtimes like node, compiling times are still close to bun but they are compiling code and showing code changes at UI from HMR

**Comment by devhik0** [comment]
Anything ?

**Comment by Jarred-Sumner** [comment]
@devhik0 can you provide a reproduction? We have automated tests that verify this works in CI that runs on every commit. So it's going to be caused by something we aren't handling yet, which means there's some network or system configuration which we aren't handling correctly

**Comment by devhik0** [comment]
Actually i can share my repo to check and if required .env values too 
`devhik0/crm-saas` (can check on my GitHub too)

**Comment by devhik0** [comment]
Anything?

**Comment by devhik0** [comment]
Anything?
