### ISSUE TITLE
Dead code elimination strips out code which is actually not dead

### ISSUE THREAD

**Issue by sedubois** [oven-sh/bun#11464]
### What version of Bun is running?

1.1.10

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

- clone https://github.com/sedubois/bun-dead-code-bug/tree/670cfa650f32429b754bdf846213e368526d3f3e
- `bun run build`
- open index.html in a browser
- open the JS console

### What is the expected behavior?

No JS error.

### What do you see instead?

There is an error `Uncaught TypeError: class heritage EVENT is not an object or null`.

<img width="631" alt="Screenshot 2024-05-30 at 18 29 44" src="https://github.com/oven-sh/bun/assets/4217871/f84d9d30-e3ce-4f0a-8ec0-7a6682965307">

The error is raised in maverick.js, a transitive dependency of Vidstack. An `EVENT` constant is defined just before the place where it is referenced `maverick/packages/maverick/src/std/event.ts`:
https://github.com/maverick-js/maverick/blob/d72709f1e367265ab2465fa153c25d72d0b2c709/packages/maverick/src/std/event.ts#L17

 The EVENT constant referred to in the error should be kept by bun in the bundle.

### Additional information

I first [reported](https://discord.com/channels/742612686679965696/1237413629989621913/1237413629989621913) this to Vidstack, who responded _"This would be an issue with Bun, not Vidstack. It seems like they're too aggressively eliminating dead code and not checking if a variable is used in a class heritage."_

**Comment by paperdave** [comment]
Fixed in #12729
