### ISSUE TITLE
File Path gets garbled when Bun.serve is benchmarked

### ISSUE THREAD

**Issue by Eckhardt-D** [oven-sh/bun#1149]
### Version

0.1.10

### Platform

Linux virtual 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```typescript
Bun.serve({
  port: 3001,
  async fetch() {
    const json = await Bun.file("./test.json").json();
    json.bunupdates += 1;
    const text = JSON.stringify(json);
    Bun.write("./test.json", text);
    return new Response(text, {
      headers: { "content-type": "application/json" },
    });
  },
});
```

When requesting via browser to `http://localhost:3000`, every request the data gets incremented and written (though most of the time twice [probably another issue]).

When using a tool like `wrk`, the filepath gets garbled and ENOENT is thrown.

### How often does it reproduce? Is there a required condition?

It only occurs in high frequency requests via `wrk` (other benchmark tools not tested). Occurs every time. It also happens with absolute file paths `imports.meta.dir + "/path.json"`.

### What is the expected behavior?

The expected behaviour is that the inline file path does not change and always finds and reads the file with every request.

### What do you see instead?

![image](https://user-images.githubusercontent.com/37825447/186827779-cc3e0db1-a878-42e5-8921-3d781fee7c6a.png)

**Comment by Jarred-Sumner** [comment]
This was fixed long ago
