### ISSUE TITLE
utf-8 parsing error for package.json

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#115]
Error:
```
  "author": "Arnuad Barr\xE9 (https://github.com/ArnaudBarre)",
            ^
/Users/arnaud/git/rds/package.json:5:13 95

uh-oh: SyntaxError parsing package.json for "/Users/arnaud/git/rds/"
```

and the line is:
```json
  "author": "Arnaud Barré (https://github.com/ArnaudBarre)",
```

Changing é to e works.

I wish my name didn't have accent sometimes 😅

**Comment by Jarred-Sumner** [comment]
So far, this seems specific to `bun install` (rather than when reading any json file). Still trying to understand why

**Comment by Jarred-Sumner** [comment]
I believe this is fixed, but please re-open if it is not

**Comment by ArnaudBarre** [comment]
Fixed thanks!

**Comment by ArnaudBarre** [comment]
Actually no, the error did not trigger on `bun i` but is still here for `bun add` (I can't re-open)
