### ISSUE TITLE
Issues resolving Promise within `setInterval()` scope

### ISSUE THREAD

**Issue by ctjlewis** [oven-sh/bun#1150]
### Version

0.1.10

### Platform

Darwin Lewiss-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

An attempt to resolve a Promise from within a `const interval = setInterval(...)` call that clears itself using `clearInterval(interval)` results in unexpected behavior where the process never exits.

Interestingly, the Promise *does* resolve, and a statement after `await new Promise(...)` will execute, but Bun simply never closes the process. Similar behavior is not reproduced in Node.

#### Repro

This repro is very simple, but it was distilled down (significantly) from a real-world bug I found writing a testing library for Bun. Basically just clarifying that this isn't some trivial edge case but seemingly a noteworthy issue related to resolving a Promise in a setInterval scope.

https://replit.com/@ctjlewis/bun-interval-promise

### How often does it reproduce? Is there a required condition?

No related issues with `setTimeout`, seems `setInterval`-specific.

### What is the expected behavior?

The process should close when the program is finished.

### What do you see instead?

A process that never closes. In the repro program, a Promise is awaited and the last expression is a `console.log` call that does execute, but the `bun` process never terminates.

#### Unsuccessful workarounds

  - ❌  Placing `interval` identifier in parent scope

#### Successful workarounds

  -  ✅  Refactoring interval as recursive `setTimeout`

**Comment by Jarred-Sumner** [comment]
Can you try this in Bun v0.1.11 and see if it still happens?

To upgrade:
```bash
bun upgrade --canary
```

**Comment by ctjlewis** [comment]
@Jarred-Sumner Didn't know about `--canary`. It does not repro! Based.
