### ISSUE TITLE
`bun update` replacing tilde with caret on `package.json`

### ISSUE THREAD

**Issue by inetol** [oven-sh/bun#11517]
### What version of Bun is running?

1.1.11

### What platform is your computer?

Linux 6.6.32_1 x86_64 unknown

### What steps can reproduce the bug?

- A `package.json` with some package in `dependencies`, `devDependencies`, `peerDependencies` or `optionalDependencies` with tilde (`~`) char. (E.g `"chalk": "~5.3.0"`)
- Do `bun update`

### What is the expected behavior?

Tilde (`~`) should be preserved following patch-version update strategy.

### What do you see instead?

Tilde (`~`) is replaced with caret (`^`) making subsequent `bun update` minor-version updates.

**Comment by dylan-conway** [comment]
Fixed in #11575. You can try it out now in canary (`bun upgrade --canary`), and it will be included the next release.
