### ISSUE TITLE
`bun install` fails to install `@roxi/routify@3.0.0-next.228`

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#11519]
### What version of Bun is running?

latest

### What platform is your computer?

Linux 6.8.0-31-generic x86_64 x86_64, Linux 6.5.0-1021-azure x86_64 x86_64 (codespaces)

### What steps can reproduce the bug?

bun install

**Comment by dylan-conway** [comment]
Can you provide more information about the project you're installing in? What dependencies do you have in `package.json` and are you using `bunfig.toml`?

**Comment by yus-ham** [comment]
been narrowed with current conditions:
- the package.json has only `@roxi/routify@next` deps which causes hangs 
- bun upgraded to latest
- no bunfig
-  `npm install` works  but not `bun install`
- `bun install` works if there `package-lock.json` or `bun.lockb`


either `bun i`, `bun i -f`, `bun  add -d  @roxi/routify@3.0.0-next.228` it just hanging
```shell
[0.13ms] ".env"
bun add v1.1.13-canary.1 (5e619ee3)
warn: incorrect peer dependency "vite@5.2.13"

warn: incorrect peer dependency "vite@5.2.13"
^C
```

**Comment by dylan-conway** [comment]
thanks, I can repro this issue with `@roxi/routify@3.0.0-next.228`

**Comment by yus-ham** [comment]
downgrade installs `@roxi/routify@3.0.0-next.227` seems works

**Comment by dylan-conway** [comment]
`@roxi/routify@3.0.0-next.228` has a file dependency on itself:
```json
"dependencies": {
    "@roxi/routify": "file:.",
}
```
I think possibly bun isn't handling this correctly which is causing the hanging
