### ISSUE TITLE
Segmentation fault at address 0xFFFFFFFFFFFFFFFF running `bun upgrade`

### ISSUE THREAD

**Issue by tnfAngel** [oven-sh/bun#11516]
### How can we reproduce the crash?

Run bun upgrade in the version 1.1.11 on Windows 11 23H2 (22631.3672)

![image](https://github.com/oven-sh/bun/assets/57068341/9dde1d26-9404-437a-b3d4-8049e46fe1bb)

### Relevant log output

```shell
PS C:\Users\tnfAngel\Documents\Projects\tnfAngel\Website> bun upgrade
============================================================
Bun v1.1.11 (4fb6056f) Windows x64
Args: "C:\Users\tnfAngel\.bun\bin\bun.exe" "upgrade"
Elapsed: 451ms | User: 15ms | Sys: 0ms
RSS: 56.58MB | Peak: 56.58MB | Commit: 117.07MB | Faults: 14028

panic(thread 55152): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.11/wp14fb6056AACiB\VCRUNTIME140.dll23oE08i2Kgv+3Zgv93Zu8j4Zi0ujYkwi/Vkoyj9C6mj/2C80o1eA2DD
```

### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on windows x86_64 [UpgradeCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- ??? at `0x1117b` in VCRUNTIME140.dll
- [`fixed_buffer_stream.zig:70`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/io/fixed_buffer_stream.zig#L70>): `write`
- [`writer.zig:23`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/io/writer.zig#L23>): `writeAll`
- [`http.zig:3191`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3191>): `handleResponseBodyFromSinglePacket`
- [`http.zig:3176`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3176>): `handleResponseBody`
- [`http.zig:2788`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2788>): `onData`
- [`uws.zig:916`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L916>): `on_data`
- `??`
- `??`
- `uv__process_poll_req`

**Comment by Jarred-Sumner** [comment]
Fixed in #11515
