### ISSUE TITLE
Crash Report: Bun Upgrade

### ISSUE THREAD

**Issue by BilligsterUser** [oven-sh/bun#11522]
### How can we reproduce the crash?

Bun Version

    Version: v1.1.11
    Commit: 4fb6056f
    Platform: Windows x64
    
  Command
```bash
bun upgrade
```

### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on windows x86_64 [UpgradeCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- ??? at `0x112bb` in VCRUNTIME140.dll
- [`fixed_buffer_stream.zig:70`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/io/fixed_buffer_stream.zig#L70>): `write`
- [`writer.zig:23`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/zig/lib/std/io/writer.zig#L23>): `writeAll`
- [`http.zig:1422`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L1422>): `getBodyBuffer`
- [`http.zig:2801`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2801>): `onData`
- [`uws.zig:916`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L916>): `on_data`
- `??`
- `??`
- `uv__process_poll_req`
- `??`

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.12. You can reinstall via the powershell script to upgrade.
