### ISSUE TITLE
bun add error

### ISSUE THREAD

**Issue by mayowing** [oven-sh/bun#11520]
### How can we reproduce the crash?

Bun v1.1.12 (macOS x64 baseline)
flymayo@flymayoui-Macmini quickstart % bun add -d @types/bun
bun add v1.1.12 (43f0913c)
  🔍 Resolving [1/1] ============================================================
Bun v1.1.12 (43f0913c) macOS x64 (baseline)
Args: "bun" "add" "-d" "@types/bun"
Elapsed: 1246ms | User: 56ms | Sys: 78ms
RSS: 18.69MB | Peak: 18.69MB | Commit: 1.07GB | Faults: 0

panic: Illegal instruction at address 0x10FE00CBD
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/bI143f0913AA__kx4gV64wlTw92llBkwomlB43+gRgtuvG__A3C6rmg8P

  🔍 Resolving [1/1] 

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on macos x86_64_baseline [AddCommand]

Illegal instruction at address 0x10FE00CBD

- *2 unknown/js code*
- `src.http.onData__anon_472002`
- `src.deps.uws.NewSocketHandler`
- `ssl_on_data`
- `us_loop_run_bun_tick`
- `src.http.HTTPThread.processEvents`
- `Thread.PosixThreadImpl.spawn__anon_291048.Instance.entryFn`
- *2 unknown/js code*

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.13. Please run `bun upgrade --canary` or wait until Bun v1.1.13 is released (later today)

Let us know if you're still running into this issue.
