### ISSUE TITLE
`bun bun` throws for entrypoint with hashbang

### ISSUE THREAD

**Issue by ctjlewis** [oven-sh/bun#1152]
### Version

0.1.11 (canary)

### Platform

Darwin macbook-air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

Execute `bun bun [file]` where `file` begins with a hashbang like `#!/usr/bin/env bun`.

#### Repro
https://replit.com/@ctjlewis/bun-bun-hasbang

### What is the expected behavior?

Hashbang should not affect the behavior of `bun bun`.

### What do you see instead?

```
error: Unexpected #!/usr/bin/env bun
#!/usr/bin/env bun
```

**Comment by birkskyum** [comment]
Is bun bun documented anywhere or is it old API? Is this what is currently `bun build`?
