### ISSUE TITLE
Crash on Windows that (likely) occurs when making a fetch request

### ISSUE THREAD

**Issue by ItsRealmy** [oven-sh/bun#11525]
### How can we reproduce the crash?

It's hard to reproduce, since the software that triggered the crash is a web crawler/spider (that continuously finds new links from the web and fetches them). However, I am pretty confident that the crash does not occur on Linux/WSL, only Windows.

I used the built in `fetch` function with no extra parameters, like so: `await fetch(url);`

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [TestCommand]

**panic**: reached unreachable code

- [`http.zig:1616`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/http.zig#L1616>): `isCompressed`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`http.zig:840`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/http.zig#L840>): `processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/http.zig#L757>): `onStart`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Fixed in #11579 

This will be part of Bun v1.1.13. To get it before that releases, run `bun upgrade --canary`.

Let us know if you still run into this issue.
