### ISSUE TITLE
bun create next ./app does not create a new project directory

### ISSUE THREAD

**Issue by levyn96** [oven-sh/bun#1153]
### Version

0.1.10

### Platform

WSL Ubuntu 22.04.1

### What steps will reproduce the bug?

`bun create next ./app
`
The command above does not produce any new directory.

### How often does it reproduce? Is there a required condition?

I wasn't able to make it work at all.

### What is the expected behavior?

I expect it to create a new nextjs project with its basic file structure.

### What do you see instead?

Nothing, not even an error is printed, but the exit code is 1 when running:
`echo $?`

**Comment by FinnRG** [comment]
Could you provide the output with the ``--verbose`` flag?

**Comment by levyn96** [comment]
sure
```
~/projects$ bun create --verbose next ./app
Fetching package.json...
```

**Comment by Electroid** [comment]
We've made very significant changes and improvements to `bun create` and `bun install` between Bun v0.1 and Bun v1.0. Specifically, we fixed some of the issues around hanging a while ago. However, if you can still reproduce this issue after upgrading, please feel free to re-open this issue and we'll investigate.
