### ISSUE TITLE
Segfault on "bun update"

### ISSUE THREAD

**Issue by thfsilvab** [oven-sh/bun#11544]
### How can we reproduce the crash?

Clean project with the following package.json:

```json
{
  "name": "fluence",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.5.9",
    "@astrojs/node": "^8.2.5",
    "@astrojs/solid-js": "^4.0.1",
    "astro": "^4.5.6",
    "postgres": "^3.4.4",
    "solid-js": "^1.8.15",
    "typescript": "^5.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.11.30",
    "prettier": "^3.2.5",
    "prettier-plugin-astro": "^0.13.0"
  },
  "module": "index.ts",
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

### Relevant log output

```shell
bun update v1.1.12 (43f0913c)
============================================================
Bun v1.1.12 (43f0913c) Linux x64
Args: "bun" "update"
Elapsed: 3ms | User: 0ms | Sys: 9ms
RSS: 1.07GB | Peak: 34.71MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x25B1E2C1248
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/lu143f0913AA+tlP0gyw4C+yq24C4yvi0C+ggi0CuouJ20uJyy+h0CA22lBwkpwle

Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [UpdateCommand]

Segmentation fault at address 0x25B1E2C1248

- `??`
- [`logger.zig:1358`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/logger.zig#L1358>): `src.install.install.PackageManager.updatePackageJSONAndInstallWithManager__anon_68365`
- [`comptime.zig:105`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig-clap/clap/comptime.zig#L105>): `src.cli.update_command.UpdateCommand.exec`
- [`cli.zig:1726`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1726>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`
- `??`
- `??`
- [`start.zig:474`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/start.zig#L474>): `main`

**Comment by dylan-conway** [comment]
Thanks for the bug report. Was there an existing lockfile, or this was the first update/install for the project?

**Comment by thfsilvab** [comment]
I actually deleted the lock files due to manually changing the package.json, running bun install right after deleting them and before running bun update

**Comment by dylan-conway** [comment]
I see, I can repro this. We'll have a for this in the next release (`v1.1.13`)
