### ISSUE TITLE
`spyOn` is not working as expected

### ISSUE THREAD

**Issue by KaiVolland** [oven-sh/bun#11556]
### What version of Bun is running?

v1.1.10

### What platform is your computer?

Linux 6.5.0-35-generic x86_64 x86_64

### What steps can reproduce the bug?

This quite simple example is not working. IMHO the test should pass. Checkout here: 
https://codesandbox.io/p/devbox/bun-test-ljs8sz

### code
```ts
const foo = (b: number) => {
  console.log(b);
};

const bar = (a: number) => {
  foo(a * a);
};

export default {
  bar,
  foo,
};
```

### test
```ts
import { expect, test, spyOn } from "bun:test";

import stuff from "./index";

const fooSpy = spyOn(stuff, "foo");

test("spy is working", () => {
  fooSpy.mockRestore();
  stuff.bar(2);
  expect(fooSpy).toHaveBeenCalledWith(4);
  expect(fooSpy).toHaveBeenCalledTimes(1);
});
```

### What is the expected behavior?

`spyOn` function detects the call of the `foo` function.

### What do you see instead?

The spy doesn't get called and the test is failing.

**Comment by paperdave** [comment]
SpyOn/mock functions can't work in this way considering the call to `foo` is a local variable. It must be kept in mind `spyOn(stuff, "foo")` just replaces the property "foo" on the object "stuff". So it only applies to the single imported instance of the module. for what it's worth, this is exactly how vitest behaves, and likely how jest behaves too (i couldnt get the es modules stuff to work in jest)

To make this work, you need to make sure the function reference is the one hit by spyOn

```ts
const foo = (b: number) => {
  console.log(b);
};

const bar = (a: number) => {
  stuff.foo(a * a);
};

const stuff = {
  bar,
  foo,
};
export default stuff;
```
then replacing .foo on the `stuff` object would be seen by the inner call.

**Comment by KaiVolland** [comment]
Ok. Thanks for the clarification.
