### ISSUE TITLE
Could not resolve: "react-is". Maybe you need to "bun install"?

### ISSUE THREAD

**Issue by jfigueroapcs** [oven-sh/bun#1155]
### Version

bun!! v0.1.10 (bdf73397)

### Platform

Darwin iMac.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

next-coockies-test bun dev
[353.00ms] bun!! v0.1.10 (bdf73397)

  Link: http://localhost:3000

error: Could not resolve: "react-is". Maybe you need to "bun install"?

import * as ReactIs from "react-is";
                         ^
/Users/Imac/projects/next-coockies-test/node_modules/bun-framework-next/renderDocument.tsx:25:26 1002JavaScript VM failed to start.
while loading "/Users/Imac/projects/next-coockies-test/node_modules/bun-framework-next/server.development.tsx"

SegmentationFault at 0xE8FF52F443050000

----- bun meta -----
Bun v0.1.10 (bdf73397) macOS x64 16.7.0
DevCommand: fast_refresh tsconfig filesystem_router framework macros public_folder bunfig 
Elapsed: 8004ms | User: 34ms | Sys: 83ms
RSS: 17.76MB | Peak: 17.81MB | Commit: 16.79MB | Faults: 2189
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

### How often does it reproduce? Is there a required condition?

Forever

### What is the expected behavior?

when executing bun dev and then clicking on the Link, the server throws the mentioned error and the execution stops

### What do you see instead?

run project :)

### Additional information

The error only appears when opening the page localhost:3000

**Comment by Jarred-Sumner** [comment]
For now, try `bun add react-is`

However, there's a few things there that is interesting

bun should not take 353ms to start, basically ever.

**Comment by jfigueroapcs** [comment]
react-is currently installed.
