### ISSUE TITLE
Multiple threads are crashing panic

### ISSUE THREAD

**Issue by mewisme** [oven-sh/bun#11551]
### How can we reproduce the crash?

I am writing a multithreaded code to continuously create NoSQL records using Mongoose. I don't know why I am encountering the error shown in the image. Please help me resolve this issue.
![image](https://github.com/oven-sh/bun/assets/63306485/8204edf4-450a-44c9-a5a0-bbbb56d417b8)

### JavaScript/TypeScript code that reproduces the crash?

```typescript
// index.ts
import type { User } from "./schema";

const runWorkerThread = (user: User) => {
  return new Promise<boolean>((resolve, reject) => {
    const worker = new Worker('./worker.ts');
    worker.postMessage(user);
    worker.onmessage = (event) => resolve(event.data);
    worker.onerror = (error) => reject(error);
  })
};

const limitConcurrency = async (concurrency: number, users: User[]) => {
  const results: boolean[] = [];
  const userQueue = users.slice();

  const workerPool = Array.from({ length: concurrency }, () => {
    return (async () => {
      while (userQueue.length > 0) {
        const user = userQueue.shift();
        if (!user) break;
        try {
          const result = await runWorkerThread(user);
          results.push(result);
        } catch (error) {
          throw error;
        }
      }
    })();
  });
  await Promise.all(workerPool);
  return results;
};

const processUsers = async (users: User[]) => {
  const result = await limitConcurrency(20, users);
  return result;
};

const userList = Array.from({ length: 200 }, (_, i) => ({ age: i, name: `Task ${i}` })) as User[];

await processUsers(userList)
  .then((result) => {
    console.log('User completed', result.filter(Boolean).length);
  })
  .catch((error) => {
    console.error('Error processing user', error);
  });
```

```typescript
//connect.ts
import * as mongoose from "mongoose";

export function connect() {
  return mongoose.connect("mongodb://localhost:27017/bun", {
    maxPoolSize: 100,
  });
}
```

```typescript
//schema.ts
import * as mongoose from "mongoose";

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  age: {
    type: Number,
    required: true
  }
}, {
  methods: {
    calcAge() {
      return this.age
    }
  }
})

export type User = mongoose.InferSchemaType<typeof userSchema>
export const User = mongoose.model<User>("user", userSchema)
```

```typescript
//worker.ts
declare const self: Worker;
import { connect } from "./connect";
import { User } from './schema'

self.onmessage = async (event) => {
  const db = await connect();
  const user = new User(event.data);
  await user.save().then(() => self.postMessage(true)).catch(() => self.postMessage(false));
  await db.disconnect();
  self.terminate();
};
```
```


### Relevant log output

```shell
============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\Mew\.bun\bin\bun.exe" ".\index.ts"
Features: jsc transpiler_cache(191) tsconfig(4)
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:net" "node:os" "node:stream" "node:string_decoder" "node:timers" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib"
Elapsed: 2593ms | User: 12390ms | Sys: 1187ms
RSS: 1.61GB | Peak: 1.72GB | Commit: 2.23GB | Faults: 476418

panic(thread 13568): Segmentation fault at address 0x9
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/wa143f0913AiggggFq525jB86hvf6vm+1CgyrzUqn18Rg889Os/uw3Cgqj9gBygw/gB+rzigBA2AS

oh no: multiple threads are crashingpanic(thread 5712): Segmentation fault at address 0x9
 https://bun.report/1.1.12/wa143f0913AiggggFq525jB86hvf6vm+1CgyrzUqn18Rg889Os/uw3Cgqj9gBygw/gB+rzigBA2AS
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000009

- [`atomic:979`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/include/atomic#L979>): `std::_Atomic_storage<unsigned int,4>::store`
- [`CompactPointerTuple.h:109`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/D:/a/WebKit/WebKit/WebKitBuild/WTF/Headers/wtf/CompactPointerTuple.h#L109>): `WTF::CompactPointerTuple<WTF::UniquedStringImpl *,unsigned short>::decodeType`
- `JSModuleLoader__import`
- [`event_loop.zig:808`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L808>): `enter`
- [`string.zig:898`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/string.zig#L898>): `toThreadSafeSlice`
- [`event_loop.zig:1633`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1633>): `platformEventLoop`
- `??`
- [`DoublyLinkedList.h:119`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/D:/a/WebKit/WebKit/WebKitBuild/WTF/Headers/wtf/DoublyLinkedList.h#L119>): `WTF::DoublyLinkedList<JSC::GCArraySegment<const JSC::JSCell *> >::head`
- [`MarkedSpace.cpp:313`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/D:/a/WebKit/WebKit/Source/JavaScriptCore/heap/MarkedSpace.cpp#L313>): `JSC::MarkedSpace::prepareForConservativeScan`
- [`GCActivityCallback.cpp:87`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/D:/a/WebKit/WebKit/Source/JavaScriptCore/heap/GCActivityCallback.cpp#L87>): `JSC::GCActivityCallback::didAllocate`

**Comment by Jarred-Sumner** [comment]
I think this was fixed in https://github.com/oven-sh/bun/pull/11635 and https://github.com/oven-sh/bun/pull/11494.

If you're still running into this issue in Bun v1.1.13 or later, please let us know and I'll re-open the issue.
