### ISSUE TITLE
Shell: panic: No arguments provided

### ISSUE THREAD

**Issue by EmileDeGamer** [oven-sh/bun#11561]
### How can we reproduce the crash?

Just create a ts file with await $`$(/bin/bash script.sh)` and all the required imports

Even if the script is not found, it throws the same error

### JavaScript/TypeScript code that reproduces the crash?

```shell
await $`$(/bin/bash script.sh)`
```

### Relevant log output

```shell
Bun v1.1.12 (43f0913c) Linux x64
Args: "./wics-cli-converter"
Features: jsc Bun.stderr(29) Bun.stdin(2) Bun.stdout(29) shell(41) spawn(41) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:util" "node:util/types" 
Elapsed: 15889ms | User: 255ms | Sys: 63ms
RSS: 1.07GB | Peak: 83.86MB | Commit: 1.07GB | Faults: 0

panic(main thread): No arguments provided
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/l_143f0913A+gggM6h8+lDyqrqmD265m7C+l2pmDq6jwjDst2y7Cg93tkD2igs6C0ptu/Dowgk0CA0eNrzy1dILEovzU3NKylWKCjKL8tMSU0BAFeTCDE

Illegal instruction
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [_]

**panic**: No arguments provided

- [`fmt.zig:1426`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/fmt.zig#L1426>): `src.output.print__anon_430212`
- [`string_immutable.zig:3377`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/string_immutable.zig#L3377>): `src.shell.interpreter.Interpreter.Expansion.next`
- [`array_list.zig:1157`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L1157>): `src.bun.js.api.bun.process.ProcessExitHandler.call`
- [`module_loader.zig:393`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/module_loader.zig#L393>): `src.bun.js.module_loader.RuntimeTranspilerStore.TranspilerJob.runFromJSThread`
- [`tagged_pointer.zig:40`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/tagged_pointer.zig#L40>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_363385`
- [`unbounded_queue.zig:114`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/unbounded_queue.zig#L114>): `src.bun.js.event_loop.EventLoop.tick`
- [`options.zig:2060`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/options.zig#L2060>): `src.bun.js.event_loop.AnyTask.New`
- [`javascript.zig:948`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/javascript.zig#L948>): `src.bun.js.javascript.OpaqueWrap__anon_53035__struct_285803.callback`
- [`EnsureStillAliveHere.h:39`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/EnsureStillAliveHere.h#L39>): `JSC__JSPromise__resolvedPromiseValue`
- [`cli.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L0>): `src.cli.Cli.start`

**Comment by 0pilatos0** [comment]
Im also experiencing a simular issue executing sh files, directly calling the .sh file with 

> $\`./script.sh\`

 causes a Exec format error

**Comment by Jarred-Sumner** [comment]
Minimal reproduction:

``ts
import {$} from 'bun';
await $`$(exit 0)`
```

**Comment by Jarred-Sumner** [comment]
> Im also experiencing a simular issue executing sh files, directly calling the .sh file with

Please open a separate issue. That one is unrelated to this one
