### ISSUE TITLE
script "dev" was terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by AndreyKindin** [oven-sh/bun#11560]
### Relevant log output

Bun v1.1.12 (43f0913c) Linux x64
Args: "node" "/XXXXX/node_modules/.bin/nuxt" "dev"
Features: jsc Bun.stderr(2) Bun.stdin(4) Bun.stdout(2) dotenv(3) fetch(108) http_server(2) spawn(2) transpiler_cache(102) tsconfig_paths(14) tsconfig(28) 
Builtins: "bun:jsc" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" 
Elapsed: 9324701ms | User: 149614ms | Sys: 66966ms
RSS: 0.23GB | Peak: 2.07GB | Commit: 0.23GB | Faults: 34

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000011

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::ClonedArguments::getOwnPropertySlot`
- [`JSCJSValueInlines.h:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/JSCJSValueInlines.h#L0>): `JSC__JSObject__getIndex`
- [`Allocator.zig:320`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/mem/Allocator.zig#L320>): `src.string.String.toThreadSafeSlice`
- [`socket.zig:1249`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/bun/socket.zig#L1249>): `src.bun.js.api.bun.socket.NewSocket`
- [`Strong.zig:12`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/Strong.zig#L12>): `src.bun.js.api.bun.socket.Handlers.rejectPromise`
- [`socket.zig:2042`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/bun/socket.zig#L2042>): `TCPSocketClass__finalize`
- [`StructureID.h:133`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/StructureID.h#L133>): `WebCore::TCPSocketPrototype__getAuthorizationErrorCallback`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`

**Comment by Jarred-Sumner** [comment]
This one is fixed in #11494
