### ISSUE TITLE
Crash on installation

### ISSUE THREAD

**Issue by Diazblack** [oven-sh/bun#11576]
### How can we reproduce the crash?

Just by running 
```
bun install
```
On a elixir:1.15.4-otp-25-slim container 

### Relevant log output
```
$ bun install
bun install v1.1.12 (43f0913c)
[5.99ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.12 (43f0913c) Linux x64
Args: "bun" "install"
Features: extracted_packages(216) lockfile_migration_from_package_lock 
Elapsed: 6779ms | User: 1251ms | Sys: 2836ms
RSS: 3.86GB | Peak: 0.35GB | Commit: 3.86GB | Faults: 0
panic(main thread): Segmentation fault at address 0x68
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```
### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [InstallCommand]

Segmentation fault at address 0x00000068

- `??`
- [`atomic.zig:48`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/atomic.zig#L48>): `Progress.log__anon_322084`
- [`wyhash.zig:146`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/wyhash.zig#L146>): `src.install.install.PackageManager.PackageInstaller.installEnqueuedPackages__anon_293735`
- [`bit_set.zig:306`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/bit_set.zig#L306>): `src.install.install.PackageManager.runTasks__anon_85265`
- [`event_loop.zig:1785`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1785>): `src.install.install.PackageManager.sleepUntil__anon_85268`
- [`install.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L0>): `src.install.install.PackageManager.installPackages__anon_85260`
- [`install.zig:11057`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L11057>): `src.install.install.PackageManager.installWithManager__anon_85246`
- [`install.zig:7532`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L7532>): `src.cli.install_command.InstallCommand.exec`
- [`cli.zig:1491`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1491>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`

**Comment by dylan-conway** [comment]
Can you share the package.json? I'm interested in seeing the dependencies

**Comment by Diazblack** [comment]
@dylan-conway  

```
{
  "name": "repair-claims",
  "version": "1.0.0",
  "description": "An Elixir/Phoenix application",
  "main": "index.js",
  "repository": "<>",
  "author": "<>",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "fuse.js": "^7.0.0",
    "tailwindcss-theme-variants": "^2.0.0-beta.0"
  }
}

```

**Comment by Jarred-Sumner** [comment]
I'm not able to reproduce this yet. I tried on Linux x64 and on macOS arm64 with cache cleared and without.

**Comment by Diazblack** [comment]
@Jarred-Sumner Thank you for investigating this issue. We retried the pipeline again this morning, but the problem persists. I've added the log output to the issue above to help with further troubleshooting.

**Comment by Jarred-Sumner** [comment]
we’ll probably need the package-lock.json to reproduce 

Judging by the stack trace, there’s a small chance —no-progress or —verbose might work around the issue.

**Comment by Jarred-Sumner** [comment]
Starting to think this is actually a progress bar issue.

If you run `bun install --no-progress` does it still happen?

**Comment by Diazblack** [comment]
@Jarred-Sumner `bun install --no-progress` flag the installation worked as expected. 
Thank you for the information. 

I will close this issue
