### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#11573]
### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`loop.c:388`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/loop.c#L388>): `us_loop_run_bun_tick`
- [`Timer.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/Timer.zig#L0>): `src.bun.js.event_loop.EventLoop.autoTickActive`
- [`bun_js.zig:379`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun_js.zig#L379>): `src.bun.js.javascript.OpaqueWrap__anon_52814__struct_285577.callback`
- [`bindings.cpp:4660`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/bindings.cpp#L4660>): `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/shimmer.zig#L186>): `src.bun_js.Run.boot`
- [`cli.zig:1998`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1998>): `src.cli.Command.maybeOpenWithBunJS`
- [`cli.zig:1865`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1865>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L50>): `main`

**Comment by Jarred-Sumner** [comment]
Not actionable without more information, unfortunately. Is there anything else you can provide? JavaScript/TypeScript code, the output of the logs, anything?

**Comment by huseeiin** [comment]
> Not actionable without more information, unfortunately. Is there anything else you can provide? JavaScript/TypeScript code, the output of the logs, anything?

i was using puppeteer. tell me if more info is needed.

**Comment by huseeiin** [comment]
> Not actionable without more information, unfortunately. Is there anything else you can provide? JavaScript/TypeScript code, the output of the logs, anything?

with `google-chrome-stable` installed on linux, run this:

```ts

import { connect } from 'puppeteer-real-browser'

const { page, browser } = await connect({})

await page.goto('https://www.google.com')
```
