### ISSUE TITLE
Workspace package name alias is not working

### ISSUE THREAD

**Issue by saravanan10393** [oven-sh/bun#11583]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Here is the minimal reproduceable example:

https://codesandbox.io/p/devbox/sweet-cloud-jvxr8s?file=%2Fpackage.json%3A11%2C1

1. Just do `bun install`

### What is the expected behavior?

Package name alias should work instead of raising module not found error.

### What do you see instead?

`error: workspace dependency "sub" not found`

Searched in "./c@latest"

### Additional information

I am trying to switch from PNPM to Bun as I relay on Pnpm workspace package aliasing i tried to do the same with Bun but it failed. Please checkout the above code sandbox.

**Comment by dylan-conway** [comment]
Bun is expecting the workspace package.json to have a version field when workspace aliases are used. A fix for this will be included in the next release (v1.1.13) this Wednesday
