### ISSUE TITLE
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### ISSUE THREAD

**Issue by BonderTam** [oven-sh/bun#11591]
### How can we reproduce the crash?

``` Dockerfile
FROM oven/bun:1.1.8-alpine as base
WORKDIR /app

FROM base as builder
COPY package.json bun.lockb tsconfig.json build.js bunfig.toml .env ./
COPY src ./src
COPY prisma ./prisma

RUN bun install --frozen-lockfile --production && bun run prisma:generate && bun run build

FROM base as runner
WORKDIR /app

COPY --from=builder /app/package.json /app/bun.lockb /app/.env ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# .env PORT
EXPOSE 3300
USER bun
ENV NODE_ENV=production

ENTRYPOINT ["bun", "./dist/index.js"]

```

![image](https://github.com/oven-sh/bun/assets/249648/32f0d6b0-e0d4-487c-b6db-af7ff78dd037)

docker compose up -d

container created.

### Relevant log output

```shell
logs of container:
============================================================
Bun v1.1.8 (89d25807) Linux x64 (baseline)
Args: "bun", "./dist/index.js"
Features: jsc Bun.stdin dotenv http_server spawn 
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:os" "node:path" "node:string_decoder" "node:tty" "node:util" "node:util/types" 
Elapsed: 149ms | User: 137ms | Sys: 58ms
RSS: 1.07GB | Peak: 102.08MB | Commit: 1.07GB | Faults: 0
panic(main thread): Segmentation fault at address 0x4A0D0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
 https://bun.report/1.1.8/Ba189d2580AqoghI2783iEA2AgtwS
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x0004A0D0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`

**Comment by Electroid** [comment]
Does this happen if you use the non-`alpine` Docker image?

**Comment by BonderTam** [comment]
> Does this happen if you use the non-`alpine` Docker image?

Thx,  non-`alpine` works fine.

**Comment by BonderTam** [comment]
non-alpine works.

**Comment by cholasimmons** [comment]
> non-alpine works.

oh? I was going to say prisma is usually installed as a devDependency so it would not generate in this instance as you built for ```--production```

**Comment by cholasimmons** [comment]
i use the non-alpine and my builds dont work since after Bun 1.1.8 💔 #11931
