### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by billgo** [oven-sh/bun#11596]
### How can we reproduce the crash?

Just run command `bun update`

### Relevant log output

```shell
bun update v1.1.12 (43f0913c)
============================================================
Bun v1.1.12 (43f0913c) macOS Silicon
Args: "bun" "update"
Features: bunfig
Elapsed: 7ms | User: 10ms | Sys: 7ms
RSS: 18.24MB | Peak: 18.24MB | Commit: 1.07GB | Faults: 242

panic(main thread): Segmentation fault at address 0x274A8342A08
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on macos aarch64 [UpdateCommand]

Segmentation fault at address 0x3CC60372A08

- *2 unknown/js code*
- `src.install.install.PackageManager.updatePackageJSONAndInstallWithManager__anon_70529`
- `src.cli.update_command.UpdateCommand.exec`
- `src.cli.Cli.start`
- `main`
- *2 unknown/js code*

**Comment by Jarred-Sumner** [comment]
Please run `bun upgrade --canary` and try again.
