### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by supportsyncpro** [oven-sh/bun#11603]
### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000011

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::ClonedArguments::getOwnPropertySlot`
- [`JSCJSValueInlines.h:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/JSCJSValueInlines.h#L0>): `JSC__JSObject__getIndex`
- [`Allocator.zig:320`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/mem/Allocator.zig#L320>): `src.string.String.toThreadSafeSlice`
- [`socket.zig:1249`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/bun/socket.zig#L1249>): `src.bun.js.api.bun.socket.NewSocket`
- [`Strong.zig:12`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/Strong.zig#L12>): `src.bun.js.api.bun.socket.Handlers.rejectPromise`
- [`socket.zig:2042`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/bun/socket.zig#L2042>): `TCPSocketClass__finalize`
- [`StructureID.h:133`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/JavaScriptCore/StructureID.h#L133>): `WebCore::TCPSocketPrototype__getAuthorizationErrorCallback`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::SlotVisitor::~SlotVisitor`

**Comment by Jarred-Sumner** [comment]
Fixed by #11494
