### ISSUE TITLE
Running `bun` with no arguments crashes powershell

### ISSUE THREAD

**Issue by panaman67** [oven-sh/bun#11604]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. open windows terminal
2. run `bun`
3. help text shown, input stops working
4. pwsh crashes with `[process exited with code 2 (0x00000002)]
You can now close this terminal with Ctrl+D, or press Enter to restart`

### What is the expected behavior?

help is shown and no error occurs

### What do you see instead?

`[process exited with code 2 (0x00000002)]`
`You can now close this terminal with Ctrl+D, or press Enter to restart.`

### Additional information

Installed `Oven-sh.Bun` package from winget

**Comment by Jarred-Sumner** [comment]
Fixed in #11612 pretty sure
