### ISSUE TITLE
Bad TS class translation

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#11605]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Linux 5.15.0-107-generic x86_64 x86_64

### What steps can reproduce the bug?

Considering following TS code:
```ts
abstract class Cparent {
    public parentVal: string;
    constructor() {
        this.parentVal = 'parent';
        this.init();
    }
    init() { }
}

class Achild extends Cparent {
    public childVal!: string;
    constructor() {
        super();
    }
    override init() {
        this.childVal = 'child';
    }
}

const a = new Achild();
console.log(a.parentVal, a.childVal);
```

### What is the expected behavior?

Expected behavior when compiling with TS:
```js
"use strict";
class Cparent {
    constructor() {
        this.parentVal = 'parent';
        this.init();
    }
    init() { }
}
class Achild extends Cparent {
    constructor() {
        super();
    }
    init() {
        this.childVal = 'child';
    }
}
const a = new Achild();
console.log(a.parentVal, a.childVal);
```

And when running:
```
"parent",  "child"
```

### What do you see instead?

When building with bun:
```js
// buntest.ts
class Cparent {
  parentVal;
  constructor() {
    this.parentVal = "parent";
    this.init();
  }
  init() {
  }
}

class Achild extends Cparent {
  childVal;
  constructor() {
    super();
  }
  init() {
    this.childVal = "child";
  }
}
var a = new Achild;
console.log(a.parentVal, a.childVal);
```

When running:
```
parent undefined
```

**Comment by codehz** [comment]
I think it is related to useDefineForClassFields in tsconfig.json
which is defaulted to true in ESNext
<img width="1108" alt="image" src="https://github.com/oven-sh/bun/assets/13158903/04d8a0fd-a9d3-4733-b433-9c7d1f1f8dd2">
ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

**Comment by pierreduot** [comment]
If I set useDefineForClassFields, the result is :
```js
"use strict";
class Cparent {
    constructor() {
        Object.defineProperty(this, "parentVal", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        this.parentVal = 'parent';
        this.init();
    }
    init() { }
}
class Achild extends Cparent {
    constructor() {
        super();
        Object.defineProperty(this, "childVal", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
    }
    init() {
        this.childVal = 'child';
    }
}
const a = new Achild();
console.log(a.parentVal, a.childVal);
```
And result is `parent, undefined` because `childVal` property is redifined after super().

But I think that the logical behavior should be this result : `parent, child`.
I'm right or not ?

**Comment by codehz** [comment]
check this https://github.com/microsoft/TypeScript/pull/33509 it should be considered as correct behavior in spec...
if you don't like it, set `useDefineForClassFields` to false

**Comment by pierreduot** [comment]
Thanks for the ref.
I understand the differences in behavior better.
In fact, I think the problem mainly comes from having the parent call the init function implemented in the child.
By writing differently, I would no longer have problems!
I can close the issue ! :-)
