### ISSUE TITLE
Can't import package inner directory

### ISSUE THREAD

**Issue by juunini** [oven-sh/bun#1161]
### Version

0.1.10

### Platform

Darwin juunini-MacBookAir.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

I want to import inner directory like this

![image](https://user-images.githubusercontent.com/41536271/187040686-18327a44-8b48-4184-9baf-0d0e2928edf9.png)

but, causes under error

![image](https://user-images.githubusercontent.com/41536271/187040669-0374b063-75bc-4034-85bf-97d2b91de3c1.png)

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

Can import package under directory

### What do you see instead?

When I use this,

```ts
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
```

causes under error

```txt
error: Could not resolve: "three/examples/jsm/loaders/GLTFLoader". Maybe you need to "bun install"?

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
                           ^
/Users/juunini/Desktop/juunini/glb-animation-combiner/src/App.tsx:3:28 91

error: Could not resolve: "three/examples/jsm/exporters/GLTFExporter". Maybe you need to "bun install"?

import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter'
                             ^
/Users/juunini/Desktop/juunini/glb-animation-combiner/src/App.tsx:4:30 160
```

### Additional information

https://github.com/juunini/glb-animation-combiner/blob/bun/src/App.tsx

**Comment by xHyroM** [comment]
Try ./tree/xx

**Comment by Jarred-Sumner** [comment]
Unfortunately, this is not a bug - but a detail of package.json `"exports"`. You'll need to specify a file extension at the end because the exported pattern includes the file extension.

From `three`'s package.json:
```json
"exports": {
    "./examples/jsm/*": "./examples/jsm/*",
```

To fix this error, try:
```js
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
```

If that doesn't work, please comment and I'll re-open the issue.

**Comment by juunini** [comment]
@Jarred-Sumner thanks. working now.
