### ISSUE TITLE
Segmentation fault at address 0x2386A000000

### ISSUE THREAD

**Issue by Intevel** [oven-sh/bun#11618]
### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x2386A000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`blob.zig:3697`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/webcore/blob.zig#L3697>): `src.bun.js.webcore.blob.ReadFile.ReadFile.create__anon_416009.Handler.run`
- [`ReadFile.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/webcore/blob/ReadFile.zig#L0>): `src.bun.js.event_loop.WorkTask`
- [`event_loop.zig:1004`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1004>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_363297`
- [`event_loop.zig:1249`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1249>): `src.bun.js.event_loop.EventLoop.tick`
- [`event_loop.zig:1495`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1495>): `src.bun.js.event_loop.EventLoop.waitForPromise`
- [`javascript.zig:1289`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/javascript.zig#L1289>): `src.bun.js.javascript.OpaqueWrap__anon_52814__struct_285577.callback`
- [`bindings.cpp:4660`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/bindings.cpp#L4660>): `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/shimmer.zig#L186>): `src.bun_js.Run.boot`

**Comment by Jarred-Sumner** [comment]
Is there anything more you could share here? This is difficult to debug because most likely, the real bug happened before the spot it crashed.

**Comment by Intevel** [comment]
> Is there anything more you could share here? This is difficult to debug because most likely, the real bug happened before the spot it crashed.

I'll try to make a small reproduction and share it to you.

**Comment by Jarred-Sumner** [comment]
It likely isn't fixed

**Comment by Intevel** [comment]
> It likely isn't fixed

Indeed, but it's hard for me to create a reproduction because this error only occurs on a specific VM.

**Comment by Jarred-Sumner** [comment]
@Intevel does the VM use Alpine Linux? (or any musl)

**Comment by Intevel** [comment]
> @Intevel does the VM use Alpine Linux? (or any musl)

Debian 12.
