### ISSUE TITLE
Websocket: Randomly crashes on multiple `.terminate()` call

### ISSUE THREAD

**Issue by Yonle** [oven-sh/bun#11625]
### How can we reproduce the crash?

Call `.terminate()` on `WebSocket(url)` instance. The example code could be the following:

```js
function newC() {
  const ws = new WebSocket("wss://...");
  setTimeout(() => {
    ws.terminate();
  }, 3000);
}

for (let i = 0; i <= 20; i++) {
  newC();
}
```

If you call `.close()` instead, It does not seems to crash.

### Stack Trace (bun.report)

Bun v1.1.12 ([`c7a08f1`](<https://github.com/oven-sh/bun/tree/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f>)) on linux x86_64 [RunCommand]

**panic**: A C++ exception occurred

- [`bindings.zig:1901`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/src/bun.js/bindings/bindings.zig#L1901>): `Zig__GlobalObject__onCrash`
- [`unumsys.cpp:0`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/unumsys.cpp#L0>): `__cxxabiv1::__terminate`
- [`MessageEvent.cpp:88`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/src/bun.js/bindings/webcore/MessageEvent.cpp#L88>): `WebCore::MessageEvent::~MessageEvent`
- [`MessageEvent.cpp:88`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/src/bun.js/bindings/webcore/MessageEvent.cpp#L88>): `WebCore::MessageEvent::~MessageEvent`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/ld-temp.o#L0>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/ld-temp.o#L0>): `JSC::MarkedBlock::Handle::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/ld-temp.o#L0>): `JSC::LocalAllocator::tryAllocateIn`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/ld-temp.o#L0>): `JSC::LocalAllocator::allocateSlowCase`
- [`LocalAllocatorInlines.h:41`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f//build/bun/bun-webkit/include/JavaScriptCore/LocalAllocatorInlines.h#L41>): `WebCore::JSMessageEvent::create`
- [`JSDOMWrapperCache.h:189`](<https://github.com/oven-sh/bun/blob/c7a08f1ec5a146897971ef6ec8f72a3da332ee5f/src/bun.js/bindings/JSDOMWrapperCache.h#L189>): `WebCore::toJSNewlyCreated`

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/11635
