### ISSUE TITLE
Bun upgrade crash

### ISSUE THREAD

**Issue by molcsan** [oven-sh/bun#11629]
### How can we reproduce the crash?

Idk i just wanted to run `bun upgrade` 

### Relevant log output

```shell
============================================================
Bun v1.1.11 (4fb6056f) Linux x64
Args: "bun" "upgrade"
Elapsed: 407ms | User: 4ms | Sys: 2ms
RSS: 1.07GB | Peak: 17.96MB | Commit: 1.07GB | Faults: 0

panic: Segmentation fault at address 0x7F61E7526950
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.11/lp14fb6056AA+xyQ+1uhrD+p1hrDqlp7pDwzi+nDiq8l8Dknxl8Dsrp4lDgn456CksllBA2i2/Bhrr21Y

Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on linux x86_64 [UpgradeCommand]

Segmentation fault at address 0x7F61E7526950

- `??`
- [`http.zig:3191`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3191>): `src.http.handleResponseBodyFromSinglePacket`
- [`http.zig:3397`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3397>): `src.http.handleResponseBodyChunkedEncoding`
- [`http.zig:2801`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2801>): `src.http.onData__anon_472662`
- [`http.zig:518`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L518>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:523`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/crypto/openssl.c#L523>): `ssl_on_data`
- [`loop.c:388`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/loop.c#L388>): `us_loop_run_bun_tick`
- [`uws.zig:1278`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L1278>): `src.http.HTTPThread.processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L757>): `Thread.PosixThreadImpl.spawn__anon_290709.Instance.entryFn`
- `??`

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.12
