### ISSUE TITLE
Failure to write out a NodeJS stream to disk

### ISSUE THREAD

**Issue by l1mey112** [oven-sh/bun#11633]
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Linux 6.1.0-13-amd64 x86_64 unknown

### What steps can reproduce the bug?

```
bun i librespot
```

Inside `bun` when running the below program the file contents being written are just the string `[object EventEmitter]` and not the actual OGG data. Im sure bun has a deficiency here with NodeJS streams.

```js
import Librespot from 'librespot'
import fs from 'fs/promises'

const spotify = new Librespot({})

await spotify.login('username', 'pasword')

const track = await spotify.get.track('7suTW2CMSgQdioqvEvaALy')

await fs.writeFile('example.ogg', track.stream)
await spotify.disconnect()
```

### What is the expected behavior?

To properly write the data into the file, not just that string.

### What do you see instead?

```
[object EventEmitter]
```

### Additional information

It works perfectly in NodeJS.

**Comment by maximehuylebroeck** [comment]
Same for things like readable streams you'll see [object object]
