### ISSUE TITLE
`bun update` with NO_COLOR crashed on windows

### ISSUE THREAD

**Issue by ryuapp** [oven-sh/bun#11649]
### How can we reproduce the crash?

Please set NO_COLOR and do `bun update` anywhere.
```sh
bun init
set NO_COLOR=1
bun update
# crashed
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [UpdateCommand]

**panic**: reached unreachable code

- [`fmt.zig:487`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/fmt.zig#L487>): `formatType`
- [`Mutex.zig:131`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/Thread/Mutex.zig#L131>): `unlock`
- [`install.zig:9077`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L9077>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:8819`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L8819>): `updatePackageJSONAndInstall`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`cell.rs:769`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cell.rs#L769>): `core::cell::panic_already_borrowed`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x526b1` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
Confirming I'm able to reproduce.

This is a bug in `std.Progress` when colors are disabled manually and it's printing to stderr. 

```zig
C:\bun\src\deps\zig\lib\std\debug.zig:342:14: 0x7ff63287b25d in assert (bun-zig.o)
    if (!ok) unreachable; // assertion failure
             ^
C:\bun\src\deps\zig\lib\std\Progress.zig:241:29: 0x7ff633483218 in clearWithHeldLock (bun-zig.o)
            std.debug.assert(p.is_windows_terminal);
                            ^
C:\bun\src\deps\zig\lib\std\Progress.zig:306:22: 0x7ff632f74675 in refreshWithHeldLock (bun-zig.o)
    clearWithHeldLock(self, &end);
                     ^
C:\bun\src\deps\zig\lib\std\Progress.zig:219:36: 0x7ff633103f49 in maybeRefreshWithHeldLock (bun-zig.o)
    return self.refreshWithHeldLock();
                                   ^
C:\bun\src\deps\zig\lib\std\Progress.zig:208:33: 0x7ff632d440a4 in maybeRefresh (bun-zig.o)
        maybeRefreshWithHeldLock(self, timer);
                                ^
C:\bun\src\deps\zig\lib\std\Progress.zig:101:34: 0x7ff632bac5b0 in completeOne (bun-zig.o)
        self.context.maybeRefresh();
                                 ^
C:\bun\src\install\install.zig:11326:50: 0x7ff63354c981 in installPackageWithNameAndResolution__anon_153455 (bun-zig.o)
                                    .extern_string_buf = extern_string_buf,
                                                 ^
C:\bun\src\install\install.zig:11635:53: 0x7ff6330830c8 in installPackageImpl__anon_118297 (bun-zig.o)
        patch_name_and_version_hash: ?u64,
                                                    ^
C:\bun\src\install\install.zig:11610:36: 0x7ff632c8b29b in installPackage__anon_86829 (bun-zig.o)
                return;
                                   ^
C:\bun\src\install\install.zig:12058:49: 0x7ff632c8a7c1 in installPackages__anon_86823 (bun-zig.o)
                            log_level,
```
