### ISSUE TITLE
FTL JIT support on Windows

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#11648]
Currently, Bun on Windows does not support the high performance [FTL JIT](https://www.webkit.org/blog/3362/introducing-the-webkit-ftl-jit/) in JavaScriptCore. This makes Bun's runtime slower on Windows, particularly involving math or some property lookups. This is a tracking issue we will close once FTL JIT is supported on Windows.

WebKit's plan for this to make JavaScriptCore on Windows use the SysV ABI instead of the Windows ABI, which will mean the implementation between Windows, macOS, and Linux will largely be the same (other than CPU architecture). This reduces the maintenance burden of supporting JIT on Windows.

Fixes https://github.com/oven-sh/bun/issues/10261
Fixes https://github.com/oven-sh/bun/issues/11350

This WebKit PR https://github.com/WebKit/WebKit/pull/28723 is relevant

**Comment by dylan-conway** [comment]
FLT JIT was enabled for Windows in Bun v1.1.19. Closing as complete.

Both issues have improved significantly.

```
#10261
bun-v1.1.18: 00:03.76
bun-v1.1.38: 00:01.69

#11350
bun-v1.1.18: 04:28.04
bun-v1.1.38: 00:03.06
```
