### ISSUE TITLE
bun i fails to install babel-plugin-react-compiler

### ISSUE THREAD

**Issue by philipheinser** [oven-sh/bun#11646]
### What version of Bun is running?

1.1.12

### What steps can reproduce the bug?

have `babel-plugin-react-compiler: 0.0.0-experimental-938cd9a-20240601` in package json run and run bun i

### What is the expected behavior?

have a dist folder in node_modules

### What do you see instead?

nothing

**Comment by philipheinser** [comment]
after doing it a second time it seam to have worked very strange are it was "babel-plugin-react-compiler" in package.json and it did not work

**Comment by michael-haberzettel** [comment]
i have noticed the same issue with `yarn add babel-plugin-react-compiler` command

**Comment by MariuzM** [comment]
Having same issue now with nextjs it was working like this morning but now random
