### ISSUE TITLE
Bun Crash

### ISSUE THREAD

**Issue by scutifer** [oven-sh/bun#11643]
### How can we reproduce the crash?

Not sure where the crash happens. This is inside a large TS project and I'm not able to reliably reproduce it.

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64_baseline [AutoCommand]

**panic**: A C++ exception occurred

- [`bindings.zig:1901`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/bindings.zig#L1901>): `Zig__GlobalObject__onCrash`
- [`unumsys.cpp:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/unumsys.cpp#L0>): `__cxxabiv1::__terminate`
- [`Worker.cpp:276`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/webcore/Worker.cpp#L276>): `WTF::Detail::CallableWrapper<WebCore::jsFunctionPostMessage(...)::$_0, void, WebCore::ScriptExecutionContext&>::call`
- [`Function.h:82`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/Function.h#L82>): `Bun__performTask`
- [`event_loop.zig:300`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L300>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_363297`
- [`event_loop.zig:1249`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1249>): `src.bun.js.event_loop.EventLoop.tick`
- [`javascript.zig:1275`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/javascript.zig#L1275>): `src.bun.js.javascript.OpaqueWrap__anon_52814__struct_285577.callback`
- [`bindings.cpp:4660`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/bindings.cpp#L4660>): `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/shimmer.zig#L186>): `src.bun_js.Run.boot`
- [`cli.zig:1998`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1998>): `src.cli.Command.maybeOpenWithBunJS`

**Comment by Jarred-Sumner** [comment]
Judging by the stacktrace, there’s a good chance that #11635 fixes this and that will be included in Bun v1.1.3. In about 45 minutes you could try `bun upgrade --canary` and test it out

**Comment by Jarred-Sumner** [comment]
I'm going to close this but please let us know if you still run into it after upgrading to Bun v1.1.13 or the canary, and we'll re-open
