### ISSUE TITLE
Bun deoptimizes class in TS files without explicit super call

### ISSUE THREAD

**Issue by eddyw** [oven-sh/bun#11655]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Darwin 23.5.0 x86_64 i386

### What steps can reproduce the bug?

Create two files `_bench.js` and `_bench.ts`, paste the following **exact** code in both files:

```ts
class Hardcoded {
	constructor() {
		this.foo = ''
	}
}
class Extended extends Hardcoded {}

function warm() {
	for (let i = 0; i < 2000000; i++) {
		var def = new Extended()
		def.foo = Math.random().toString()
	}
}

function bench() {
	console.time('loop')
	warm()
	console.timeEnd('loop')
}

warm()
warm()
bench()
```

In the terminal run:
```shell
$ bun _bench.ts && bun _bench.js
[222.10ms] loop
[143.67ms] loop

$ hyperfine "bun _bench.js" "bun _bench.ts"
Benchmark 1: bun _bench.js
  Time (mean ± σ):     551.6 ms ±  19.2 ms    [User: 494.8 ms, System: 69.8 ms]
  Range (min … max):   527.4 ms … 577.3 ms    10 runs
 
Benchmark 2: bun _bench.ts
  Time (mean ± σ):     748.7 ms ±  23.5 ms    [User: 727.6 ms, System: 58.4 ms]
  Range (min … max):   719.2 ms … 789.2 ms    10 runs
```

The TS file is always slower (~100ms) if the constructor with a call to `super()` is not explicit. You can reproduce it by running this example as many times as you want.

If you replace the `Extended` class with this version (in both files):

```ts
class Extended extends Hardcoded {
	constructor() {
		super() // <- explicit call to super
	}
}
```

And run benchmarks again:

```shell
$ bun _bench.ts && bun _bench.js
[146.09ms] loop
[137.13ms] loop

$ hyperfine "bun _bench.js" "bun _bench.ts"
Benchmark 1: bun _bench.js
  Time (mean ± σ):     531.1 ms ±  16.9 ms    [User: 474.7 ms, System: 66.9 ms]
  Range (min … max):   507.1 ms … 567.6 ms    10 runs
 
Benchmark 2: bun _bench.ts
  Time (mean ± σ):     516.8 ms ±  16.5 ms    [User: 463.5 ms, System: 62.7 ms]
  Range (min … max):   489.2 ms … 544.3 ms    10 runs
```

The performance is equivalent in both TS and JS files.

### What is the expected behavior?

The performance in TS vs JS files should be equivalent when initializing a class that extends another class without explicit call to `super()`.

### What do you see instead?

There is performance degradation initializing classes that do not explicitly call `super` in the constructor.

### Additional information

Maybe a transpiler bug TS -> JS?

**Comment by paperdave** [comment]
thanks for the investigation. i cant find any example of any other transpiler that adds this transform (including `tsc`) so i think we should just remove this, as it's equivilent, and hits a slow path in jsc
