### ISSUE TITLE
Bun has crashed

### ISSUE THREAD

**Issue by renat2985** [oven-sh/bun#11657]
### How can we reproduce the crash?

The code worked for about 2 weeks and just crashed.

### Relevant log output

```shell
Bun v1.1.8 (89d25807) Linux x64
Args: "bun", "socket.js"
Features: jsc fetch(24) http_server 
Builtins: "bun:main" "bun:sqlite" 
Elapsed: 879577242ms | User: 1082904ms | Sys: 3228703ms
RSS: 1.07GB | Peak: 0.29GB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x2
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000002

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/ld-temp.o#L0>): `char32_t WTF::Unicode::next<(...)0, char8_t>`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/ld-temp.o#L0>): `llint_relativePCBase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/ld-temp.o#L0>): `JSC::ClonedArguments::materializeSpecials`
- [`JSObjectInlines.h:671`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c//build/bun/bun-webkit/include/JavaScriptCore/JSObjectInlines.h#L671>): `JSObjectCallAsFunctionReturnValueHoldingAPILock`
- [`array_list.zig:859`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/array_list.zig#L859>): `src.bun.js.bindings.bindings.JSGlobalObject.throw__anon_413766`
- [`hashtable_policy.h:433`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c//usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/hashtable_policy.h#L433>): `uWS::TopicTree<uWS::TopicTreeMessage, uWS::TopicTreeBigMessage>::subscribe`
- [`javascript.zig:856`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/javascript.zig#L856>): `src.deps.uws.WebSocketBehavior.Wrap`
- [`basic_string.h:348`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c//usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h#L348>): `uWS::InflationStream::inflate`

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.13. Please let us know if you still run into this once Bun v1.1.13 is released and we'll re-open this issue.
