### ISSUE TITLE
Write file from stream using thread worker

### ISSUE THREAD

**Issue by vitaliy-melnik** [oven-sh/bun#11656]
### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x100009C5F

- *4 unknown/js code*

**Comment by Jarred-Sumner** [comment]
Likely fixed in Bun v1.1.13 with the other Worker-related fixes
