### ISSUE TITLE
Segmentation fault on running a test

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [oven-sh/bun#11662]
### How can we reproduce the crash?

```
git clone git@github.com:grafana/grafana.git
yarn install --immutable
bun test public/app/features/manage-dashboards/state/actions.test.ts
```

### Relevant log output

```shell
bun test v1.1.12 (43f0913c)

public/app/features/manage-dashboards/state/actions.test.ts:
============================================================
Bun v1.1.12 (43f0913c) Linux x64
Args: "bun" "test" "public/app/features/manage-dashboards/state/actions.test.ts"
Features: jsc transpiler_cache(15) tsconfig_paths(2) tsconfig(12) 
Builtins: "node:util" "node:util/types" 
Elapsed: 441ms | User: 348ms | Sys: 113ms
RSS: 0.80GB | Peak: 0.27GB | Commit: 0.80GB | Faults: 0

panic(main thread): Segmentation fault at address 0x1A
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x0000001A

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `llint_relativePCBase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::JSModuleEnvironment::getOwnPropertySlot`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`StringImpl.h:262`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L262>): `Bun::ProcessBindingUV::jsErrname`
- [`Timer.zig:390`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/api/Timer.zig#L390>): `src.bun.js.api.Timer.TimerObject.runImmediateTask`
- [`tagged_pointer.zig:40`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/tagged_pointer.zig#L40>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_363385`

**Comment by Jarred-Sumner** [comment]
The underlying cause is a TSX transpiler issue in Bun with the following line:
```tsx
 export const A = <T = unknown,>({}: B<T>) => {};
```

And then a yet-to-be-understood bug with error handling happens sometime after that.
