### ISSUE TITLE
Incorrect WebAssembly result

### ISSUE THREAD

**Issue by mfcc64** [oven-sh/bun#11667]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Linux 6.8.0-31-lowlatency x86_64 x86_64

### What steps can reproduce the bug?

At the extracted bun-debug folder, compare result log between node and bun
`node test.mjs`
`bun test.mjs`

[bun-debug.zip](https://github.com/user-attachments/files/15687590/bun-debug.zip)

### What is the expected behavior?

The results should be equal.

### What do you see instead?

Invalid result, starting at index 512.

**Comment by mfcc64** [comment]
https://bugs.webkit.org/show_bug.cgi?id=275596

**Comment by mfcc64** [comment]
Fixed in https://github.com/WebKit/WebKit/commit/2fdb35959e51641413e88e0eb9d47fb134f46b01

Thank's

**Comment by Jarred-Sumner** [comment]
@mfcc64 this change will be applied in #12246
