### ISSUE TITLE
 Index out of bounds on bun update

### ISSUE THREAD

**Issue by tnfAngel** [oven-sh/bun#11676]
### How can we reproduce the crash?

Running `bun update`
on `Window 11 22631.3672`
with this `package.json`
```json
{
  "dependencies": {
    "typescript": "5.4.5"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```
![image](https://github.com/oven-sh/bun/assets/57068341/8a4054c3-604a-4418-aa30-4627b71156ff)

Could be related to https://github.com/oven-sh/bun/issues/10565?

`bun i` works great.

### Relevant log output

```shell
bun update
bun update v1.1.12 (43f0913c)

Checked 1 install across 2 packages (no changes) [391.00ms]
============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\tnfAngel\.bun\bin\bun.exe" "update"
Elapsed: 393ms | User: 31ms | Sys: 0ms
RSS: 0.21GB | Peak: 0.21GB | Commit: 0.39GB | Faults: 52188

panic(main thread): index out of bounds
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [UpdateCommand]

**panic**: index out of bounds

- [`install.zig:6955`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L6955>): `editUpdateNoArgs`
- [`install.zig:9097`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L9097>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:8819`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L8819>): `updatePackageJSONAndInstall`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`cell.rs:769`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cell.rs#L769>): `core::cell::panic_already_borrowed`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
This was fixed by @dylan-conway 

Please run `bun upgrade --canary` and try again. If you still run into this issue, we will re-open it.
