### ISSUE TITLE
Incorrect code transformation when referencing `module` and `export` with hmr

### ISSUE THREAD

**Issue by tikotzky** [oven-sh/bun#117]
If a file references `module.hot` it gets wrapped in `__cJS2eSM` however it keeps the esm exports in the function being wrapped causing a syntax error
```
Uncaught SyntaxError: Unexpected token 'export'
```

I was able to reproduce with a file that contained

```jsx
import React from 'react';

function App() {
  return (
    <div>
      <h1>Hello from bun!</h1>
    </div>
  );
}

export default App;

module.hot; // <--- this line triggers the incorrect transform.
```

which ended up getting transformed to:

```js
import {
__FastRefreshRuntime as FastRefresh_b5da893a11e0b9e5
} from "http://localhost:3001/bun:wrap";
import {
__require as require
} from "http://localhost:3001/bun:wrap";
import {
__cJS2eSM
} from "http://localhost:3001/bun:wrap";
import * as $a5be275f from "http://localhost:3001/node_modules/react/jsx-dev-runtime.js";
var JSX = require($a5be275f);
var jsx = require(JSX).jsxDEV;

import * as $abdb1838 from "http://localhost:3001/node_modules/react/index.js";
var { default: React} = require($abdb1838);

export default __cJS2eSM(function(module, exports) {
  ;

  function App() {
    return jsx("div", {
      children: jsx("h1", {
        children: "Hello from bun!"
      }, undefined, false, undefined, this)
    }, undefined, false, undefined, this);
  }

  export default App; // <--- this export is left unmodified causing a syntax error
  module.hot;
}, "src/App.jsx");
```

**Comment by Jarred-Sumner** [comment]
Thanks for filing. This is definitely a bug.

For now, if you remove the line referencing `module.hot`, it will prevent the CommonJS transform. Referencing `module` triggers the CommonJS transform, which also disables hot module reloading for the file. Using `module.exports` and `export` statements in the same file is not supported, though using `require` and `import` in the same file is supported. 

This is what happened:

1. Referencing `module.hot` disabled HMR for the file
2. `export default` was incorrectly left in, and should've been transformed to match esbuild's behavior for ESM exports -> CommonJS exports

There isn't a great way to override the HMR runtime yet. I could make `import.meta.hot` return either the `FastRefreshModule` or the `HMRModule` object.

**Comment by Jarred-Sumner** [comment]
Please re-open this if you're still seeing this bug after upgrading to bun v0.0.70
