### ISSUE TITLE
Issue: Prefilled crash report

### ISSUE THREAD

**Issue by ramandhika** [oven-sh/bun#11708]
### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [CreateCommand]

**panic**: reached unreachable code

- [`fmt.zig:487`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/fmt.zig#L487>): `formatType`
- [`Mutex.zig:131`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/Thread/Mutex.zig#L131>): `unlock`
- [`http.zig:3240`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/http.zig#L3240>): `handleResponseBodyChunkedEncoding`
- [`http.zig:3404`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/http.zig#L3404>): `handleResponseMetadata`
- [`heap.zig:506`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/heap.zig#L506>): `stackFallback`
- [`uws.zig:338`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/uws.zig#L338>): `ext`
- `??`
- `??`
- `??`
- `fs__open`

**Comment by paperdave** [comment]
thanks for submitting a crash report. unfortunately, the crash report tool had a bug which malformed the stack traces (see #11720). since this report does not have a reproduction, there is nothing i can do about this report. if you continue to see a crash in Bun v1.1.13, please open a new issue.
