### ISSUE TITLE
Implement `aborted` in `node:util`

### ISSUE THREAD

**Issue by amagee** [oven-sh/bun#11716]
### What version of Bun is running?

Bun v1.1.12 (Linux x64)

### What platform is your computer?

Linux 6.5.0-41-generic x86_64 x86_64

### What steps can reproduce the bug?

1. `bun init`
2. `bun install execa` (or `bun execa@9.2.0` for current version as of today)
3. Create a file `abort.js` with a single line - `import { execa } from "execa";`
4. `bun abort.js`

### What is the expected behavior?

Program should execute and do nothing but no errors

### What do you see instead?

```
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'aborted' not found in module 'util'.

Bun v1.1.12 (Linux x64)
```

**Comment by yoursunny** [comment]
I have a complicated script that imports execa in one of its dependencies.
Without reading this thread, I would not have guessed the offending import is from execa.

Bun only gives the following error message:

```
$ bun run ./producer.ts 
[bun] Warning: async_hooks.createHook is not implemented in Bun. Hooks can still be created but will never be called.
- | (function (entry, fetcher)
SyntaxError: Export named 'aborted' not found in module 'util'.

Bun v1.1.17 (Linux x64)
```

**Is there any command line flag or environment variable setting that can make Bun print where the offending import is?**
I already tried `--trace-warnings` and `--inspect-wait`, but never could reveal this information.

**Comment by OskarLebuda** [comment]
Same issue here :(

**Comment by hiddentao** [comment]
Seeing this too in v9+. Switched to v8 of `execa` and it works.

**Comment by Jarred-Sumner** [comment]
@hiddentao what version of Bun are you on? we implemented support for this months ago

**Comment by hiddentao** [comment]
> [@hiddentao](https://github.com/hiddentao) what version of Bun are you on? we implemented support for this months ago

My bad, I'm on 1.1.34. Will upgrade!
