### ISSUE TITLE
Fix bugs and DX issues with `bun patch`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#11719]
TODOs for @zackradisic:
- [x] Replace `bun patch-commit` with `bun patch --commit package-name`
- [x] Don't copy it into a temporary directory, instead overwrite each file individually in `node_modules/package-name` with a copy of itself (excluding node_modules, like `patch-package`). This lets developers test their patches locally before committing them, and avoids the issue where hardlinks can potentially overwrite the cached package. This does not handle postinstall scripts 
- [ ] Optional, but nice: `bun patch --revert package-name` 
- [x] `bun patch --commit` needs tests. I am surprised that we merged `bun patch` when `bun patch-commit` had zero test coverage.
- [x] `bun patch --commit` should handle when the patch already exists
- [x] `bun patch --commit` should work with scoped packages
- [x] `bun patch --commit` should never cause "Resolving..." to happen indefinitely on install
- [x] `bun patch` should not be missing from the help menu
- [x] Documentation page

**Comment by TheKnightCoder** [comment]
This is probably the biggest blocker for myself and many others from adopting bun.. would love to know how soon this feature could be implemented

**Comment by zackradisic** [comment]
> This is probably the biggest blocker for myself and many others from adopting bun.. would love to know how soon this feature could be implemented

I have a PR open now for these changes here: #11858

**Comment by vijaybritto** [comment]
> This is probably the biggest blocker for myself and many others from adopting bun.. would love to know how soon this feature could be implemented
This is sort of doable with patch-package. 
https://github.com/oven-sh/bun/issues/2336#issuecomment-2092697099
