### ISSUE TITLE
bun install in brand new project fails on Windows

### ISSUE THREAD

**Issue by mardukbp** [oven-sh/bun#11725]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```
mkdir project
cd project
bun init -y
bun install
```

### What is the expected behavior?

bun install succeeds

### What do you see instead?

bun install v1.1.12 (43f0913c)
  🚚 typescript [2/2] error: InstallFailed extracting tarball for typescript
error: moving "typescript" to cache dir failed
EPERM: Operation not permitted (NtSetInformationFile())      
  From: .1fdfd9896ef6f7fc-00000001.typescript
    To: typescript@5.4.5

### Additional information

This happens with a brand new installation of bun.

This bug prevents installing any package in the project.

I have admin rights.

The directory .1fdfd9896ef6f7fc-00000001.typescript exists in %LOCALAPPDATA%\Temp

**Comment by Ajay01103** [comment]
I using latest bun in windows and I am also getting the same tarball extraction failure error

**Comment by Electroid** [comment]
Duplicate of #11250
