### ISSUE TITLE
Memory leak on <ws>.WebSocket()

### ISSUE THREAD

**Issue by Yonle** [oven-sh/bun#11722]
### What version of Bun is running?

Linux 4.19.191-g96eac46b6306-dirty aarch64 unknown

### What platform is your computer?

Linux

### What steps can reproduce the bug?

```js
const WS = require("ws");
const server = new WS.WebSocketServer({ port: 1111 }); // dummy server

function c() {
  const sock = new WS.WebSocket("ws://localhost:1111");
  sock.on('open', _ => {
    sock.terminate();
    c();
  });
}

c();
```

### What is the expected behavior?

Memory usage should not go above than 60 MB (?) and shrinks.

### What do you see instead?

Memory usage go above than 60 MB and never shrinks.

### Additional information

Same effect occurs even with `WebSocket().close()`. Removing listeners also does not shrink.

**Comment by Jarred-Sumner** [comment]
An example which more conclusively demonstrates a memory leak where the `WebSocket` object seems to never be finalized:
```js
const WS = require("ws");

const server = Bun.serve({
   port: "1111",
   fetch(req, server) {
     return server.upgrade(req);
   },
   websocket: {
     open() {},
     data() {},
     message() {}, 
     drain() {},
  } 
});

var queue = [];
function c() {
  const {promise, resolve} = Promise.withResolvers();
  const sock = new WebSocket("ws://localhost:1111");
  sock.addEventListener('open', _ => {
    sock.addEventListener("close", () => {
       resolve();
    });
    sock.close();
  })

  return promise;
}

setInterval(() => 
{
  Bun.gc(true);
  
  const rss = process.memoryUsage.rss() / 1024 / 1024 | 0;
  const objectTypeCounts = require("bun:jsc").heapStats().objectTypeCounts;
  console.log(require("bun:jsc").heapStats().protectedObjectTypeCounts);
  console.log(Object.fromEntries(Object.entries(objectTypeCounts).sort()));
}, 1000);

while (true) {
  await c();
 await Bun.sleep(0);
}
```

**Comment by NextGenOP** [comment]
this issue also occur while using ws npm package
server: 
```
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080 });
wss.on('connection', (ws) => {
	ws.close()
});
```
but fixed with Bun.gc

closing connection from server also create issue in client

**Comment by Yonle** [comment]
The memory usage is still exceeding 70 MB of RAM.

Bun:
![Screenshot_20240612-140810.png](https://github.com/oven-sh/bun/assets/63401712/35f4550d-47ae-489e-9450-9e9bfcbde967)

NodeJS:
![Screenshot_20240612-141104.png](https://github.com/oven-sh/bun/assets/63401712/8e324d8c-ed58-46ab-bd15-c0f68f3446b3)
