### ISSUE TITLE
AbortSignal.any is not working as expected

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#11726]
### What version of Bun is running?

1.1.13-canary.1+4786c6139

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```js
const a = new AbortController();
const b = new AbortController();

const signal = AbortSignal.any([a.signal, b.signal]);
signal.addEventListener("abort", () => {
  console.log("aborted");
});

a.abort();
b.abort();
```
run it in browser devtools and bun

### What is the expected behavior?

print "aborted"

### What do you see instead?

nothing output in bun
but it is working in browser

### Additional information

https://github.com/oven-sh/bun/issues/10251
the API is added, but broken

**Comment by guest271314** [comment]
Reprodicible on Bun 1.1.12

`abortable.js`
```
const a = new AbortController();
const b = new AbortController();

const signal = AbortSignal.any([a.signal, b.signal]);
signal.addEventListener("abort", (e) => {
  console.log("aborted", e.target.reason);
});

a.abort("a");
b.abort("b");
```

Chromium 127

```
aborted a
```

Deno 1.44.0 (release, x86_64-unknown-linux-gnu)

`deno run -A abortable.js`
```
aborted a
```

Node.js v23.0.0-nightly202406038c5c2c18b6

`node  abortable.js`
```
aborted a
```

Bun 1.1.12

`bun run abortable.js`

```

```
