### ISSUE TITLE
My bun crash on run update command

### ISSUE THREAD

**Issue by jvddavid** [oven-sh/bun#11737]
### How can we reproduce the crash?

i use the Kubuntu 22.04 LTS as OS

this crash occurred on my repository https://github.com/jvddavid/puppeteer-extra-plugin-devtools

### Relevant log output

```shell
 bun update
bun update v1.1.12 (43f0913c)
============================================================
Bun v1.1.12 (43f0913c) Linux x64
Args: "bun" "update"
Elapsed: 8ms | User: 14ms | Sys: 4ms
RSS: 1.07GB | Peak: 25.82MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x52C002DCBF0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/...

Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [UpdateCommand]

Segmentation fault at address 0x52C002DCBF0

- `??`
- [`logger.zig:1358`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/logger.zig#L1358>): `src.install.install.PackageManager.updatePackageJSONAndInstallWithManager__anon_68365`
- [`comptime.zig:105`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig-clap/clap/comptime.zig#L105>): `src.cli.update_command.UpdateCommand.exec`
- [`cli.zig:1726`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1726>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`

**Comment by dylan-conway** [comment]
This was fixed in #11547 and will be included in v1.1.13. You can also try out the fix in canary (`bun upgrade --canary`)
