### ISSUE TITLE
Ignore hashbang for Node when directly running `bun run file.ts`

### ISSUE THREAD

**Issue by illright** [oven-sh/bun#11740]
### What is the problem this feature would solve?

I was using Bun in development because Node can't execute TypeScript, and Bun was a nice drop-in alternative, but I stumbled into an issue where if I have `#!/usr/bin/env node` at the top of the file, whenever I try to run this file with `bun run`, it instead starts Node, which obviously fails because the file is in TypeScript.

### What is the feature you are proposing to solve the problem?

For `bun run` to ignore hashbangs

### What alternatives have you considered?

- Removing the hashbang, but since I'm publishing for Node, that would mean I have to remember to add it back once I'm done.
- Extra command-line argument, but that would needlessly complicate the interface of `bun run` in my opinion

**Comment by Jarred-Sumner** [comment]
You can use `--bun` to ignore the shebang:

```
bun --bun  ./foo.ts
```

**Comment by illright** [comment]
Okay, that solves my issue. Didn't see that part of the docs, my bad! Thanks for the prompt response and thanks for making Bun, it's awesome :)
