### ISSUE TITLE
Drizzle join values scrambled after v1.1.4

### ISSUE THREAD

**Issue by wendevlin** [oven-sh/bun#11747]
### What version of Bun is running?

1.1.4 - 1.1.12

### What platform is your computer?

Linux 6.1.90-1-MANJARO x86_64

### What steps can reproduce the bug?

Use drizzle ORM with bun:sqlite

Joint 2 tables.

```JavaScript
import { drizzle } from 'drizzle-orm/bun-sqlite'
import { Database } from 'bun:sqlite'
const db = drizzle(sqlite)

const smsToServer = await db
  .select({
    sms: smsToServerTable,
    sirene: sirenenTable,
  })
  .from(smsToServerTable)
  .leftJoin(sirenenTable, eq(smsToServerTable.fromSireneId, sirenenTable.id))
  .where(
    and(
      gte(smsToServerTable.timestamp, from.toDate()),
      lte(smsToServerTable.timestamp, to.toDate()),
    ),
  )
```

### What is the expected behavior?

I should get the joined result as I defined it.

### What do you see instead?

The result objects does have the correct structure, but the values are scrambled. 
So all values are there but for example the value for a timestamp is inside the id field.

### Additional information

There is already a stackoverflow post from another user: https://stackoverflow.com/questions/78376844/drizzle-join-results-are-scrambled

**Comment by kravetsone** [comment]
> ### What version of Bun is running?
> 1.1.4 - 1.1.12
> 
> ### What platform is your computer?
> Linux 6.1.90-1-MANJARO x86_64
> 
> ### What steps can reproduce the bug?
> Use drizzle ORM with bun:sqlite
> 
> Joint 2 tables.
> 
> ```js
> import { drizzle } from 'drizzle-orm/bun-sqlite'
> import { Database } from 'bun:sqlite'
> const db = drizzle(sqlite)
> 
> const smsToServer = await db
>   .select({
>     sms: smsToServerTable,
>     sirene: sirenenTable,
>   })
>   .from(smsToServerTable)
>   .leftJoin(sirenenTable, eq(smsToServerTable.fromSireneId, sirenenTable.id))
>   .where(
>     and(
>       gte(smsToServerTable.timestamp, from.toDate()),
>       lte(smsToServerTable.timestamp, to.toDate()),
>     ),
>   )
> ```
> 
> ### What is the expected behavior?
> I should get the joined result as I defined it.
> 
> ### What do you see instead?
> The result objects does have the correct structure, but the values are scrambled. So all values are there but for example the value for a timestamp is inside the id field.
> 
> ### Additional information
> There is already a stackoverflow post from another user: https://stackoverflow.com/questions/78376844/drizzle-join-results-are-scrambled

+1 

I also got a randomed response from drizzle & bun:sqlite. I had to use better-sqlite3 & Node.js and all works as expected
