### ISSUE TITLE
Crashed when trying to run brain.js

### ISSUE THREAD

**Issue by AvuxDemons** [oven-sh/bun#11748]
### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](<https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFE74F11942

- *1 unknown/js code*
- ??? at `0x5128c` in ntdll.dll
- ??? at `0x50fe7` in ntdll.dll
- ??? at `0x50c8d` in ntdll.dll
- ??? at `0x182ab` in KERNEL32.DLL
- ??? at `0x1bac0` in ucrtbase.dll
- ??? at `0x1bcd9` in ucrtbase.dll
- [`Global.zig:105`](<https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/Global.zig#L105>): `exitWide`
- [`Global.zig:98`](<https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/Global.zig#L98>): `exit`
- [`javascript.zig:907`](<https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/javascript.zig#L907>): `eventLoop`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v11.1.12
