### ISSUE TITLE
Random crash on my express.js app

### ISSUE THREAD

**Issue by ui0ppk** [oven-sh/bun#11749]
### How can we reproduce the crash?

I do not know how because it is just a random crash from a request using express.js
Here's a list of what packages I use:
    "@types/cookie-parser": "^1.4.7",
    "@types/express": "^4.17.21",
    "@types/locale": "^0.1.4",
    "@types/lowdb": "^1.0.15",
    "@types/twig": "^1.12.16",
    "@types/yaml": "^1.9.7",
    "argon2": "^0.40.3",
    "autoprefixer": "^10.4.19",
    "bootstrap": "^5.3.3",
    "cloudflare-express": "^1.0.1",
    "cookie-parser": "^1.4.6",
    "express": "^4.19.2",
    "express-rate-limit": "^7.3.0",
    "get-root-path": "^2.0.2",
    "lowdb": "^7.0.1",
    "nodemon": "^3.1.0",
    "postcss-cli-simple": "^4.0.1",
    "sass": "^1.77.4",
    "twig": "^1.17.1",
    "xss": "^1.0.15",
    "yaml": "^2.4.2"

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x00000000

**Comment by ui0ppk** [comment]
#11568 I think we both have the same issue. I will close this for now.

**Comment by Jarred-Sumner** [comment]
Duplicate of #11568
