### ISSUE TITLE
Internal assertion failure while trying to add d3-org-chart

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [oven-sh/bun#11746]
### How can we reproduce the crash?

I tried to add this package: https://www.npmjs.com/package/d3-org-chart

Create a new project, then add the package:

```shell
bun a d3-org-chart
```

Please tell me if you need more information.

### Relevant log output

```shell
bun add v1.1.7 (b0b7db5c)
  🔍 Resolving [1/3] ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "C:\Users\rmanc\.bun\bin\bun.exe", "a", "d3-org-chart"
Elapsed: 435ms | User: 15ms | Sys: 0ms
RSS: 62.41MB | Peak: 62.41MB | Commit: 117.51MB | Faults: 15445

panic(thread 22704): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 ...
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](<https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254>)) on windows x86_64 [AddCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/output.zig#L356>): `panic`
- [`bun.zig:3159`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L3159>): `assertionFailure`
- [`js_ast.zig:7498`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/js_ast.zig#L7498>): `pop`
- [`npm.zig:265`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/npm.zig#L265>): `getPackageMetadata`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/atomic.zig#L40>): `load`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
@TheLonelyAdventurer can you try this in Bun v1.1.12?

**Comment by TheLonelyAdventurer** [comment]
@Jarred-Sumner  I confirm it doesn't work in 1.1.12
 
output:

```
bun add v1.1.12 (43f0913c)
  🔍 d3-cloud [4/5] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\rmanc\.bun\bin\bun.exe" "a" "d3-org-chart"
Elapsed: 816ms | User: 0ms | Sys: 15ms
RSS: 79.51MB | Peak: 79.51MB | Commit: 0.14GB | Faults: 19636

panic(thread 24264): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

...
```

Stack Trace:

```
Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [AddCommand]

**panic**: Internal assertion failure

- [`fixed_buffer_stream.zig:70`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/io/fixed_buffer_stream.zig#L70>): `write`
- [`windows_c.zig:705`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/windows_c.zig#L705>): `init`
- [`sys_uv.zig:328`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/sys_uv.zig#L328>): `preadv`
- [`bun.zig:3234`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.zig#L3234>): `assertionFailure`
- [`ArenaAllocator.zig:52`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/ArenaAllocator.zig#L52>): `deinit`
- [`time.zig:72`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/time.zig#L72>): `timestamp`
- [`Thread.zig:523`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/Thread.zig#L523>): `entryFn`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

<!-- from bun.report: bb_N9rgUf03RT_3RawNK -->
```
