### ISSUE TITLE
`bun update` changes the versions in the `package.json` instead of just updating the lock file

### ISSUE THREAD

**Issue by AmionSky** [oven-sh/bun#11741]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Linux 6.9.3-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Have a dependency with its minor or patch version not set to the latest.
Run `bun update`

### What is the expected behavior?

Only the lockfile updates to the latest versions allowed by the `package.json`

### What do you see instead?

The versions in the `package.json` change too
(also changes the "tab width" to 2 spaces)

### Additional information

`npm update` has the expected behavior

package.json is used to specify the version ranges, not the exact version used (that is the lockfile's job)

**Comment by Jarred-Sumner** [comment]
This is intentional behavior added in #5856.

If you want to update without saving to package.json, pass `--no-save`:
```sh
bun update --no-save
```

**Comment by AmionSky** [comment]
> --no-save               Don't update package.json or save a lockfile

`--no-save` seem to imply that it does not change the lockfile as well

Also why does bun go against the behavior of all other package managers?
