### ISSUE TITLE
`requestIP` returns `null` after async call

### ISSUE THREAD

**Issue by adhusson** [oven-sh/bun#11756]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```javascript
Bun.serve({
  port: 3001,
  async fetch(req,server) {
    console.log(server.requestIP(req));
    await req.formData();
    console.log(server.requestIP(req));
  }
});
```

Then `curl --data "k=v" http://127.0.0.1:3001`

### What is the expected behavior?

```
{
  address: "::ffff:127.0.0.1",
  family: "IPv6",
  port: 54636,
}
{
  address: "::ffff:127.0.0.1",
  family: "IPv6",
  port: 54636,
}
```

### What do you see instead?

```
{
  address: "::ffff:127.0.0.1",
  family: "IPv6",
  port: 54728,
}
null
```

**Comment by kevinmingtarja** [comment]
I'm able to reproduce this too on Bun `1.1.22`, and `Darwin 21.4.0 arm64`.

**Comment by luksch42** [comment]
same with 1.1.26

**Comment by KenjiGinjo** [comment]
🥺
