### ISSUE TITLE
There is "bun login --registry"  like 'npm login --registry'?

### ISSUE THREAD

**Issue by NeuralMayu** [oven-sh/bun#1176]
### Version

0.1.5

### Platform

Darwin mayudeMacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What do you see instead?

error: Script not found "login"

**Comment by xhyrom** [comment]
You have old version + https://github.com/oven-sh/bun#configuring-bun-install-with-bunfigtoml

**Comment by NeuralMayu** [comment]
> You have old version + https://github.com/oven-sh/bun#configuring-bun-install-with-bunfigtoml

thanks
