### ISSUE TITLE
bun install crash report

### ISSUE THREAD

**Issue by GusrifarisYudaAlhafis** [oven-sh/bun#11768]
### Relevant log output

```shell
[1.00ms] ".env"
bun install v1.1.12 (43f0913c)
[19.89ms] migrated lockfile from package-lock.json
  📦 Installing [11/431] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "bun" "install"
Features: dotenv extracted_packages(161) lockfile_migration_from_package_lock 
Elapsed: 20809ms | User: 2906ms | Sys: 8093ms
RSS: 0.42GB | Peak: 0.49GB | Commit: 0.61GB | Faults: 284109
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5156`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5156>): `processDependencyListItem`
- [`logger.zig:850`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/logger.zig#L850>): `allocPrint`
- [`install.zig:5937`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5937>): `runTasks`
- [`install.zig:10695`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L10695>): `installPackages`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1450`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1450>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`cell.rs:769`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cell.rs#L769>): `core::cell::panic_already_borrowed`
- ??? at `0x17344` in KERNEL32.DLL

**Comment by Jarred-Sumner** [comment]
Fixed in #11763 

This fix will be included in Bun v1.1.13
