### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by romradchenko** [oven-sh/bun#11777]
### How can we reproduce the crash?

```
{
	"name": "streetrp-server",
	"version": "0.1.0",
	"author": "nicro",
	"homepage": "https://ragemp.pro",
	"license": "MIT",
	"private": true,
	"scripts": {
		"dev": "webpack --profile --progress --mode development --config webpack.config.js",
		"build": "cross-env NODE_ENV=production webpack --profile --progress --mode production --config webpack.config.js"
	},
	"dependencies": {
		"@babel/runtime": "^7.14.5",
		"axios": "^0.21.1",
		"bcryptjs": "^2.4.3",
		"chalk": "^4.1.1",
		"cross-env": "^7.0.3",
		"crypto-random-string": "^4.0.0",
		"dotenv": "^10.0.0",
		"express": "^4.17.1",
		"ioredis": "^4.27.5",
		"lodash": "^4.17.21",
		"moment": "^2.29.1",
		"mongodb-client-encryption": "^2.3.0",
		"mongoose": "^5.12.13",
		"nodemailer": "^6.6.1",
		"rage-rpc": "github:Yoegibby/rage-rpc#rage1.1_fixes",
		"source-map-support": "^0.5.19",
		"winston": "^3.3.3"
	},
	"devDependencies": {
		"@babel/core": "^7.14.5",
		"@babel/plugin-proposal-class-properties": "^7.14.5",
		"@babel/plugin-proposal-numeric-separator": "^7.14.5",
		"@babel/plugin-transform-runtime": "^7.14.5",
		"@babel/preset-env": "^7.14.5",
		"@babel/preset-typescript": "^7.14.5",
		"@types/bcryptjs": "^2.4.2",
		"@types/core-js": "^2.5.4",
		"@types/express": "^4.17.12",
		"@types/ioredis": "^4.26.4",
		"@types/lodash": "^4.14.170",
		"@types/moment": "^2.13.0",
		"@types/mongoose": "^5.11.97",
		"@types/node": "^15.14.9",
		"@types/nodemailer": "^6.4.2",
		"@types/ragemp-s": "github:CocaColaBear/types-ragemp-s#v1.0",
		"babel-loader": "^8.2.2",
		"clean-webpack-plugin": "^4.0.0-alpha.0",
		"terser-webpack-plugin": "^5.1.3",
		"tsconfig-paths-webpack-plugin": "^3.5.1",
		"webpack": "^5.38.1",
		"webpack-cli": "^4.7.2",
		"webpack-node-externals": "^3.0.0"
	}
}

```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`fixed_buffer_stream.zig:70`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/io/fixed_buffer_stream.zig#L70>): `write`
- [`windows_c.zig:705`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/windows_c.zig#L705>): `init`
- [`sys_uv.zig:328`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/sys_uv.zig#L328>): `preadv`
- [`bun.zig:3234`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.zig#L3234>): `assertionFailure`
- [`lockfile.zig:1372`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/lockfile.zig#L1372>): `shouldPrintPackageInstall`
- [`lockfile.zig:1293`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/lockfile.zig#L1293>): `printInstalledWorkspaceSection`
- [`lockfile.zig:1577`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/lockfile.zig#L1577>): `print`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1450`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1450>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`

**Comment by Jarred-Sumner** [comment]
Do you still run into this in the canary build of Bun?

```
bun upgrade --canary
```

**Comment by nodenwwsfww** [comment]
Thanks, it helped!
