### ISSUE TITLE
`bun ci` as shortcut for `bun i --frozen-lockfile`

### ISSUE THREAD

**Issue by axelrindle** [oven-sh/bun#11772]
### What is the problem this feature would solve?

I am lazy for writing `bun i --frozen-lockfile` everytime I clone a repository or checkout a feature branch to not change the lockfile.

### What is the feature you are proposing to solve the problem?

Implement a command `bun ci` similar to [`npm ci`](https://docs.npmjs.com/cli/v10/commands/npm-ci) which does essentially the same as `bun i --frozen-lockfile`.

**Comment by Electroid** [comment]
Duplicate of #5283
