### ISSUE TITLE
Crash with the bun update --latest

### ISSUE THREAD

**Issue by romradchenko** [oven-sh/bun#11784]
### How can we reproduce the crash?

{
	"name": "streetrp-client",
	"version": "0.1.0",
	"author": "nicro",
	"homepage": "https://ragemp.pro",
	"license": "MIT",
	"private": true,
	"scripts": {
		"dev": "webpack --profile --progress --mode development --config webpack.config.js",
		"build": "cross-env NODE_ENV=production webpack --profile --progress --mode production --config webpack.config.js"
	},
	"dependencies": {
		"keycode": "^2.2.0",
		"lodash": "^4.17.21",
		"rage-rpc": "github:Yoegibby/rage-rpc#rage1.1_fixes"
	},
	"devDependencies": {
		"@babel/core": "^7.14.5",
		"@babel/plugin-proposal-class-properties": "^7.14.5",
		"@babel/plugin-transform-runtime": "^7.14.5",
		"@babel/preset-env": "^7.14.5",
		"@babel/preset-typescript": "^7.14.5",
		"@babel/runtime": "^7.14.5",
		"@types/core-js": "^2.5.4",
		"@types/lodash": "^4.14.170",
		"@types/node": "^15.12.2",
		"@types/ragemp-c": "github:CocaColaBear/types-ragemp-c#v1.0",
		"babel-loader": "^8.2.2",
		"clean-webpack-plugin": "^4.0.0-alpha.0",
		"cross-env": "^7.0.3",
		"javascript-obfuscator": "^2.15.1",
		"terser-webpack-plugin": "^5.1.3",
		"tsconfig-paths-webpack-plugin": "^3.5.1",
		"webpack": "^5.38.1",
		"webpack-cli": "^4.7.2",
		"webpack-obfuscator": "3.3.1"
	}
}

### Stack Trace (bun.report)

Bun v1.1.13-canary ([`ee30e86`](<https://github.com/oven-sh/bun/tree/ee30e8660c673d32c410281dad92daa8ebab554c>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/output.zig#L356>): `panic`
- [`bun.zig:3254`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/bun.zig#L3254>): `assertionFailure`
- [`lockfile.zig:1402`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/install/lockfile.zig#L1402>): `shouldPrintPackageInstall`
- [`lockfile.zig:1323`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/install/lockfile.zig#L1323>): `printInstalledWorkspaceSection`
- [`lockfile.zig:1608`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/install/lockfile.zig#L1608>): `print`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1465`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/cli.zig#L1465>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/ee30e8660c673d32c410281dad92daa8ebab554c/src/cli.zig#L62>): `start`

Features: extracted\_packages, git\_dependencies

**Comment by dylan-conway** [comment]
Fixed with #14461 in bun v1.1.31
