### ISSUE TITLE
Panicked while trying to install dependencies  

### ISSUE THREAD

**Issue by levlavryniuk** [oven-sh/bun#11787]
### How can we reproduce the crash?

# First step (preparation)

Since the issue happened while installing hardhat dependencies (framework for blockchain stuff), we need to init a hardhat project first.
```sh
bun install hardhat -d
bunx hardhat init
```
✔ What do you want to do? · Create a TypeScript project
✔ Hardhat project root: · /any
✔ Do you want to add a .gitignore? (Y/n) · y
✔ Do you want to install this sample project's dependencies with npm (hardhat @nomicfoundation/hardhat-toolbox)? (Y/n) · n

# Second step (bug is here)

Run
```bash
bun add @nomicfoundation/hardhat-ignition-ethers @nomicfoundation/hardhat-ethers @nomicfoundation/hardhat-ignition @nomicfoundation/hardhat-verify @nomicfoundation/ignition-core ethers -d
```

This is the point when it panics. I hope it helps.

### Relevant log output

```shell
-
```

### Stack Trace (bun.report)

bun add v1.1.9 (bb13798d)
============================================================
Bun v1.1.9 (bb13798d) Linux x64
Args: "bun", "add", "@nomicfoundation/hardhat-ignition-ethers", "@nomicfoundation/hardhat-ethers", "@nomicfoundation/hardhat-ignition", "@nomicfoundation/hardhat-verify", "@nomicfoundation/ignition-core", "ethers", "-d"
Elapsed: 4ms | User: 4ms | Sys: 0ms
RSS: 1.07GB | Peak: 23.46MB | Commit: 1.07GB | Faults: 3

panic(main thread): ENOENT parsing package.json
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.9/lI1bb13798AAgh/h+Cw4126Civq73C2vyo4C+nsg0C+g//zCA0eNqTjjbIlY42Nsx19fN39QuRjjbIVShILCrOzEtXKEhMzk5MT9XLKs7PA0kAACt0DjI

[1]    10205 illegal hardware instruction (core dumped)  bun add @nomicfoundation/hardhat-ignition-ethers     ethers -d

**Comment by Lavryniukk** [comment]
Nevermind, i was using bun v1.1.8.

It worked on newer, v1.1.12, version. Bun is so good, thank you guys.
