### ISSUE TITLE
Bun 0.1.10 incorrectly installs Express in Ubuntu WSL

### ISSUE THREAD

**Issue by peter-sereda** [oven-sh/bun#1178]
### Version

0.1.10

### Platform

Microsoft Windows NT 10.0.19043.0 x64

### What steps will reproduce the bug?

Ubuntu 22.04.01 running on top of WLS

Bun 0.1.10 incorrectly installs express package dependencies. The error did not happen in 0.1.8. Got this after running a very simple test express app:
```
/express-install-bug$ bun express.js

error: Could not resolve: "vary". Maybe you need to "bun install"?

var vary = require('vary');
```

Steps to reproduce: 
1) Run Ubuntu 22.04.1 on Windows 10 WSL
2) create a new empty folder
3) "bun install express" in the folder
4) create a very basic express app that just listens to '/' HTTP GET on some port
5) run it with bun: 'bun express.js'
6) Got the error above

Please note that running "node express.js" for the same file and folder also throws a similar error (which probably hints that express was really installed incorrectly):
```
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'vary'
Require stack:
- c:\Work\small\express-install-bug\node_modules\express\lib\response.js
```

![image](https://user-images.githubusercontent.com/22524183/187395952-2c3efefc-694c-4251-abe7-6b05716edb6c.png)

### How often does it reproduce? Is there a required condition?

Not conditions as far as I know.

### What is the expected behavior?

Express app is up and running with output like:
"express app is listening on port 19319"

### What do you see instead?

Error highlighted above.

### Additional information

The error did not happen in 0.1.8 (it got another problem with hanging HTTP requests in express, but that was another story I believe).

If express is installed via npm then bun runs express.js correctly:
```
c:\Work\small\express-install-bug>npm install express

added 57 packages, and audited 58 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
/mnt/c/Work/small/express-install-bug$ bun express.js
express app is listening on port 19319
```

**Comment by LoiLock** [comment]
Works fine for me. Could you share the express.js file that you're running?

**Comment by peter-sereda** [comment]
Hey @LoiLock ,

You can find it on the screenshot attached to the bug description, but here is it again just in case. Btw, upgrade to 0.1.11 didn't help.

```
const express = require('express');

const port = 19319;
const app = express();

app.get('/', (req, res) => {
    res.send('Hey from express');

    res.status(200).end();
});

app.listen(port, () => {
    console.log(`express app is listening on port ${port}`);
});

```

**Comment by peter-sereda** [comment]
Clearing out bun's packages cache didn't help, stil get the same error:
```
error: Cannot find package "vary" from "/mnt/c/Work/small/expr-inst-bug/node_modules/express/lib/response.js"
```

**Comment by skoblenick** [comment]
The issue seems to be related to a mounted or external drive specifically. I ran into a similar issue in Ubuntu on a (secondary) mounted m.2 drive, but things ran OK when I moved the project into my home folder.

**Comment by peter-sereda** [comment]
@skoblenick thank you for the idea. Moving of the test project folder to Ubuntu's own drive from the hosting Windows one did solve the issue. Express installs and runs perfectly fine now.
