### ISSUE TITLE
My Bun App Crashed

### ISSUE THREAD

**Issue by f4id** [oven-sh/bun#11798]
### Relevant log output

```shell
Args: "C:\Users\Administrator\AppData\Roaming\npm\\node_modules\bun\bin\bun.exe", "src/index.ts"
Features: jsc Bun.stdin(2) dotenv fetch(91) transpiler_cache(10) tsconfig_paths(2) tsconfig(4) WebSocket(59)
Builtins: "bun:main" "bun:sqlite" "node:buffer" "node:events" "node:fs" "node:fs/promises" "node:http" "node:path" "node:stream" "node:string_decoder" "node:timers" "node:timers/promises" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws"
Elapsed: 353343326ms | User: 39937ms | Sys: 11234ms
RSS: 0.22GB | Peak: 0.23GB | Commit: 0.25GB | Faults: 13052848

panic(main thread): Segmentation fault at address 0x38
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.8/ea189d2580AqoiggX4u251Cypy/7Cuwu51C85vge44o9dg+l9dki6tG2ug/0CkrgmFu1/wFA2AwD

error: script "start" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on windows x86_64_baseline [AutoCommand]

Segmentation fault at address 0x00000038

- `us_socket_close`
- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/uws.zig#L2619>): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`
- [`cli.zig:1982`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1982>): `maybeOpenWithBunJS`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.13:
```sh
bun upgrade
```

Let us know if you still run into an issue like this
