### ISSUE TITLE
macOS zig install instruction error `xattr -dr` -> `option -r not recognized`

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#1180]
From https://github.com/oven-sh/bun#install-zig-macos

```
# Make sure it gets trusted
xattr -dr com.apple.quarantine $HOME/.bun-tools/zig/zig
```

Output

```
option -r not recognized

usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -s: act on symbolic links themselves rather than their targets
  -l: print long format (attr_name: attr_value)
  -z: compress or decompress (if compressed) attribute value in zip format
```

**Comment by jbergstroem** [comment]
I don't think recursing here (`-r`) is relevant seeing how its only one file/binary.

**Comment by yoBoss283** [comment]
> From https://github.com/oven-sh/bun#install-zig-macos
> 
> ```
> # Make sure it gets trusted
> xattr -dr com.apple.quarantine $HOME/.bun-tools/zig/zig
> ```
> 
> Output
> 
> ```
> option -r not recognized
> 
> usage: xattr [-slz] file [file ...]
>        xattr -p [-slz] attr_name file [file ...]
>        xattr -w [-sz] attr_name attr_value file [file ...]
>        xattr -d [-s] attr_name file [file ...]
>        xattr -c [-s] file [file ...]
> 


Not sure if you ever fixed this error on your Mac, but I found the solution: https://stackoverflow.com/questions/43297564/recursive-xattr-fails-horribly

On my machine 'somehow' the /usr/local/bin/xattr was installed and used instead of the one that came with macOS. I don't know how this was installed (since I often just copy/paste commands). At least the -r option is working again.
