### ISSUE TITLE
`bun` without arguments crashes PowerShell.exe with exit code 2

### ISSUE THREAD

**Issue by daball** [oven-sh/bun#11818]
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Install bun using Windows PowerShell. `powershell -c "irm bun.sh/install.ps1 | iex"`
2. Run bun without any arguments. `bun`

### What is the expected behavior?

Return to PowerShell normally without side effects.

### What do you see instead?

Return to PowerShell then within 1-2 seconds the PowerShell process exits with exit code 2.

### Observations

1. `bun` from Windows 11 PowerShell with no arguments crashes Windows PowerShell.
2. `bun` from Windows 11 Command Prompt (using the new Windows Terminal interface) terminates normally without side effects.
3. `bun --help` from PowerShell terminates normally without side effects.
4. `bun --revision` from PowerShell terminates normally without side effects.
5. `cmd /c bun` from PowerShell crashes Windows PowerShell.

### Summary

It seems to work fine if you use arguments. This appears to be happening when `bun` is run without any arguments. It does not seem to crash Command Prompt (cmd.exe) but even when you run `cmd /c bun` from PowerShell, it crashes the PowerShell process. While I understand in some way this may be Microsoft's fault as well, as one shell crashes when the other does not, there must be something about the termination state of the `bun` app that is causing this to happen. I can run and then terminate with [Ctrl]+[C] twice, the `node` process without any side effects to my shell. See screenshot.

### Screenshot

![image](https://github.com/oven-sh/bun/assets/703034/206e77ac-9a26-4105-b575-ed49e64ba659)

Upper left corner you see the results of executing `cmd /c bun` from the Command Prompt default configuration in Windows 11 Terminal.

Upper right corner you see the results of executing `bun` from the Windows PowerShell default configuration in Windows 11 Terminal. You see the PowerShell crash with exit code 2. You see I pressed Enter to restart it. I also run the two inputs you asked for in this shot.

Lower left corner you see the results of executing `cmd /c bun` from the Windows PowerShell default configuration in Windows 11 Terminal. You see the PowerShell crash with exit code 2.

Lower right corner you see the result of running `bun --help` from a custom Windows PowerShell configuration in Windows 11 Terminal. There are no side effects to the PowerShell environment which results in PowerShell exit code 2.

### Upstream

This is probably not the intended design of Microsoft PowerShell for Windows 11 either. According to `$PSVersionTable.PSVersion` I am running version 5.1.22621.3672. If this appears to be a defect in the PowerShell app, when someone figures out the underlying issue for what causes the crash, would you also inform Microsoft about the defect in PowerShell? I'll try to keep track of this issue in case someone needs to report this to Microsoft as well.

**Comment by SunsetTechuila** [comment]
in addition: this happens only with Windows Terminal

**Comment by paperdave** [comment]
Fixed in #11927
