### ISSUE TITLE
RangeError: Out of Memory with `pbkdf2`

### ISSUE THREAD

**Issue by alexfaber2011** [oven-sh/bun#11814]
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Linux 6.8.11-200.fc39.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

Import `pbkdf2` from `node:crypto`, and call it with any password, salt, iterations, key length, and digest.

```ts
import { pbkdf2 } from "node:crypto";
pbkdf2(
  "foo",
  "salt",
  2 ** 16,
  64,
  "SHA256",
  (error, derivedKey) => console.log({ error, derivedKey })
)
```

### What is the expected behavior?

Console should log

```ts
{ error: undefined, derivedKey: "<string>" }
```

### What do you see instead?

```ts
{
  error: 1556 |       sha384: 48,
1557 |       sha512: 64,
1558 |       rmd160: 20,
1559 |       ripemd160: 20
1560 |     };
1561 |     function Hmac(alg, key2, saltLen) {
                                         ^
RangeError: Out of memory
      at new Hmac (node:crypto:1561:35)
      at pbkdf2 (node:crypto:1584:39)
,
  derivedKey: undefined,
}

````

### Additional information

This does not seem to happen on apple silicon

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.13 and let us know if you still run into this

**Comment by alexfaber2011** [comment]
Wow, that fixed it.  I thought I had the latest version (updated yesterday), but y'all are cruising along!  Thank you @Jarred-Sumner.
