### ISSUE TITLE
[1.1.13] `Can't find variable: module` 

### ISSUE THREAD

**Issue by finscn** [oven-sh/bun#11840]
### What version of Bun is running?

1.1.13

### What platform is your computer?

macOS

### What steps can reproduce the bug?

run these code: 

```js
if (require.main === module) {
    console.log('log something...')
}
```
there will be an error :  `ReferenceError: Can't find variable: module`

<img width="429" alt="image" src="https://github.com/oven-sh/bun/assets/288367/d644a017-cf0e-474d-b3d3-ae5bb303eb9d">

**Comment by nektro** [comment]
does this still reproduce for you? (you may need to run `bun upgrade`)

**Comment by finscn** [comment]
> does this still reproduce for you? (you may need to run `bun upgrade`)

No.   it could work with `module`  now.
