### ISSUE TITLE
Expected 0 values, got ... in bun:sqlite Database.run

### ISSUE THREAD

**Issue by lafkpages** [oven-sh/bun#11846]
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

It seems like when you use `?` parameters in a `run` call but the `?`s aren't in the first query, it expects 0 and crashes.

Repro:
```ts
import { Database } from 'bun:sqlite';

const db = new Database();

db.run(
  `\
CREATE TABLE demo (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO demo (name) VALUES (?);`,
  ['Hello, world!'],
);

console.log(db.query('SELECT * FROM demo').all());
```

### What is the expected behavior?

That a value is inserted into the demo table with the values given as parameters.

### What do you see instead?

```ts
1 | import { Database } from 'bun:sqlite';
2 |
3 | const db = new Database();
4 |
5 | db.run(
       ^
error: Expected 0 values, got 1
      at /Users/.../bun-db-run-error-repro.ts:5:4

Bun v1.1.13 (macOS arm64)
```

**Comment by Jarred-Sumner** [comment]
`db.run` only accepts bindings for the first statement. 

```ts
import { Database } from 'bun:sqlite';

const db = new Database();

db.run(`CREATE TABLE demo (id INTEGER PRIMARY KEY, name TEXT)`);

db.run(
  `INSERT INTO demo (name) VALUES (?)`,
  ['Hello, world!'],
);

console.log(db.query('SELECT * FROM demo').all());
```

In https://github.com/oven-sh/bun/commit/a1ffc2144635a331f619e522c20aab3efe22831e, I made the error message a little clearer
