### ISSUE TITLE
Bun Upgrade Fails

### ISSUE THREAD

**Issue by hakkano** [oven-sh/bun#11879]
### How can we reproduce the crash?

I did the following on terminal
>> bunx npm-check-updates -i
Update all by pressing enter; didn't install through npm install
>> bun install
>> bun update
>> bun upgrade

### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on linux x86_64 [UpgradeCommand]

Segmentation fault at address 0x70F64F46D950

- `??`
- [`http.zig:3245`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3245>): `src.http.handleResponseBody`
- [`http.zig:2788`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2788>): `src.http.onData__anon_472662`
- [`http.zig:518`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L518>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:523`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/crypto/openssl.c#L523>): `ssl_on_data`
- [`loop.c:388`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/loop.c#L388>): `us_loop_run_bun_tick`
- [`uws.zig:1278`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L1278>): `src.http.HTTPThread.processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L757>): `Thread.PosixThreadImpl.spawn__anon_290709.Instance.entryFn`
- `??`

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.12

For now, please upgrade using the curl script:

```sh
curl https://bun.sh/install | bash
```
