### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by satodu** [oven-sh/bun#11877]
### How can we reproduce the crash?

bun install

### Relevant log output

```shell
bun install v1.1.13 (bd6a6051)
[4.30ms] migrated lockfile from package-lock.json
  🚚 uuid... ============================================================
Bun v1.1.13 (bd6a6051) Windows x64
Args: "C:\Users\edsat\AppData\Roaming\npm\node_modules\bun\bin\bun.exe" "install"
Features: extracted_packages(2) git_dependencies lockfile_migration_from_package_lock
Elapsed: 1366ms | User: 15ms | Sys: 31ms
RSS: 91.45MB | Peak: 91.45MB | Commit: 0.16GB | Faults: 22929

panic(main thread): Ran callback to install enqueued packages, but there was no task associated with it. 263 src.install.install.ExtractData{ .url = { 104, 116, 116, 112, 115, 58, 47, 47, 114, 101, 103, 105, 115, 116, 114, 121, 46, 110, 112, 109, 106, 115, 46, 111, 114, 103, 47, 117, 117, 105, 100, 47, 45, 47, 117, 117, 105, 100, 45, 57, 46, 48, 46, 49, 46, 116, 103, 122 }, .resolved = {  }, .json = src.install.install.ExtractData.ExtractData__struct_31966{ .path = {  }, .buf = {  } } }
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on windows x86_64 [InstallCommand]

**panic**: Ran callback to install enqueued packages, but there was no task associated with it. 259 src.install.install.ExtractData{ .url = { 104, 116, 116, 112, 115, 58, 47, 47, 114, 101, 103, 105, 115, 116, 114, 121, 46, 110, 112, 109, 106, 115, 46, 111, 114, 103, 47, 99, 114, 121, 112, 116, 111, 45, 106, 115, 47, 45, 47, 99, 114, 121, 112, 116, 111, 45, 106, 115, 45, 52, 46, 50, 46, 48, 46, 116, 103, 122 }, .resolved = {  }, .json = src.install.install.ExtractData.ExtractData__struct_31966{ .path = {  }, .buf = {  } } }

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/output.zig#L356>): `panic`
- [`mem.zig:3994`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/zig/lib/std/mem.zig#L3994>): `sliceAsBytes`
- [`install.zig:6548`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/install/install.zig#L6548>): `runTasks`
- [`install.zig:12137`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/install/install.zig#L12137>): `isDone`
- [`event_loop.zig:1875`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/event_loop.zig#L1875>): `tick`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1465`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli.zig#L1465>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli.zig#L62>): `start`

**Comment by dylan-conway** [comment]
Can you provide more information about the project you are installing in? `package.json` would be helpful, and does this error occur with each install?

**Comment by satodu** [comment]
I did the installation in WSL and worked fine.
