### ISSUE TITLE
Panic on `bun install`: Index out of bounds error

### ISSUE THREAD

**Issue by Alemar16** [oven-sh/bun#11894]
### How can we reproduce the crash?

Thank you so much for submitting a crash report. You're helping us make Bun more reliable for everyone!

### Steps to Reproduce

1. Clone the following repository: [Alemar16/blog-tutorial-astro](https://github.com/Alemar16/blog-tutorial-astro)
2. Rename the directory to `tutorial-extend-with-content-collections`
3. Navigate to the directory in your terminal:
    ```sh
    cd tutorial-extend-with-content-collections
    ```
4. Run `bun install`:
    ```sh
    bun install
    ```

This should trigger the error.

### Repository Link

[GitHub Repository for Reproduction](https://github.com/Alemar16/blog-tutorial-astro)

### Relevant log output

```shell
❯ bun install
bun install v1.1.12 (43f0913c)
  📦 Installing [91/509] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\Armando\.bun\bin\bun.exe" "install"
Features: extracted_packages(74) 
Elapsed: 20104ms | User: 843ms | Sys: 3687ms
RSS: 0.20GB | Peak: 0.20GB | Commit: 0.29GB | Faults: 70097

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

https://bun.report/1.1.12/wi143f0913AggBk+vyH6s1yHuj80EmvlxEi3puE8ot2Fqi4BiiJow6y+CCa\KERNEL32.DLL63yEA0eNrLzEtJrVDILy1RyE9TSMovzUspBgBHeAcx
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5159`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5159>): `processDependencyListItem`
- [`install.zig:5217`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5217>): `processDependencyList`
- [`install.zig:5937`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5937>): `runTasks`
- [`install.zig:10695`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L10695>): `installPackages`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.13
