### ISSUE TITLE
Bun script crashes when trying to compile SASS styles

### ISSUE THREAD

**Issue by Atulin** [oven-sh/bun#11893]
### How can we reproduce the crash?

Install the `sass-embedded` package and write a build script like

```ts
import { Glob } from "bun";
import { join } from "node:path";
import * as sass from 'sass-embedded';

const styleFiles = new Glob(join(import.meta.dir, "static/**/*.scss"));

const outDir = join(import.meta.dir, "dist");

for await (const file of styleFiles.scan()) {
	const contents = await Bun.file(file).text();
	const result = await sass.compileStringAsync(contents);
	await Bun.write(join(outDir, file.replace('.scss', '.css')), result.css);
}
```

with a single `style.scss` file

```sass
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

placed in `./static/styles` directory.

The same issue occurs with the `sass` package, and even when using `scanSync` and `compileString` to remove some asynchronous code.

### Relevant log output

```shell
MyRepo\_Docs on  master [!?] via 🍞 v1.1.12 via  v21.6.2 
❯ bun run build
$ bun build.mts
============================================================
Bun v1.1.12 (43f0913c) Windows x64
ng_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:worker_threads"
Elapsed: 420ms | User: 343ms | Sys: 187ms
RSS: 0.17GB | Peak: 0.17GB | Commit: 0.25GB | Faults: 42050

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/wa143f0913AqgggoHghg+L+3pzIwi67F+8vCivprb4o91Qy8tjIww77Rwo13G28vh2CA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg

error: script "build" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [AutoCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/output.zig#L356>): `panic`
- [`bun.zig:3234`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.zig#L3234>): `assertionFailure`
- [`js_ast.zig:3117`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/js_ast.zig#L3117>): `assert`
- [`event_loop.zig:202`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L202>): `run`
- [`event_loop.zig:1257`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1257>): `tickConcurrent`
- [`event_loop.zig:1497`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1497>): `waitForPromise`
- [`javascript.zig:1289`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/javascript.zig#L1289>): `waitForPromise`
- `JSC__VM__holdAPILock`

**Comment by dylan-conway** [comment]
Fixed in Bun v1.1.21 with #12364
