### ISSUE TITLE
Bun not waiting for callback in some cases

### ISSUE THREAD

**Issue by maxts** [oven-sh/bun#1189]
### Version

v0.1.11

### Platform

Mac/Ubuntu

### What steps will reproduce the bug?

Without the last line this only works in Nodejs (bun will exit without waiting for either of the callbacks).
> const fs = require('fs');
> const path = require('path');
>  
> const test = fs.readFileSync(path.join(__dirname,"test.wasm"));
> WebAssembly.instantiate(test, {}).then((instance) => {
> 	console.log("callback");
> 	return null;
> }).catch((err) => {
> 	console.log("err",err);
> 	return null;
> });
>  
> setTimeout(function(){ }, 5000);

### How often does it reproduce? Is there a required condition?

It happens in multiple places, bun simply doesn't wait for the callbacks and continues on.

### What is the expected behavior?

One of the callbacks need to be fired.

### What do you see instead?

The program finished executing without an error.

### Additional information

Should be an easy one to fix.

**Comment by Jarred-Sumner** [comment]
We need a way to hold the process open when SharedTask is enqueued from JSC
