### ISSUE TITLE
Bun has crashed

### ISSUE THREAD

**Issue by renat2985** [oven-sh/bun#11907]
### How can we reproduce the crash?

This is not a server resource issue.
This is a fairly powerful Amazon cloud server that runs only bun,
serves about 200 WebSoscket connections...
```
free -h
              total        used        free      shared  buff/cache   available
Mem:           31Gi       871Mi        18Gi        22Mi        12Gi        30Gi
Swap:         511Mi          0B       511Mi
```

### Relevant log output

```shell
Bun v1.1.13 (bd6a6051) Linux x64
Args: "bun" "socket.js"
Features: jsc http_server 
Builtins: "bun:main" "bun:sqlite" 
Elapsed: 314201443ms | User: 359302ms | Sys: 1072896ms
RSS: 1.07GB | Peak: 0.15GB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x2
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000002

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::profiledCall`
- [`bindings.cpp:2285`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/bindings/bindings.cpp#L2285>): `JSObjectCallAsFunctionReturnValue`
- [`server.zig:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/api/server.zig#L0>): `src.deps.uws.AnyWebSocket.cork__anon_347613.Wrapper.wrap`
- [`MoveOnlyFunction.h:247`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/MoveOnlyFunction.h#L247>): `uws_ws_cork`
- [`uws.zig:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/uws.zig#L0>): `src.deps.uws.WebSocketBehavior.Wrap`
- [`MoveOnlyFunction.h:247`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/MoveOnlyFunction.h#L247>): `uWS::WebSocketContext<false, true, void*>::handleFragment`

**Comment by renat2985** [comment]
These are excerpts, hope it helps you.

```
import { Database } from "bun:sqlite";
const db = Database.open(":memory:");
db.exec('CREATE TABLE "online" ("onlineID" INTEGER, "activity" TEXT,  *** , PRIMARY KEY("onlineID" AUTOINCREMENT))');
***
const port = process.env.PORT || 8585;
const server = Bun.serve({
  fetch(req, server) {
    const url = new URL(req.url);
    if (url.search.length == 72) {
      server.upgrade(req, {
        data: {
          name: "none",
          room: new URL(req.url).search.split("?")[1].split("&")[0].replace(/[^a-zA-Z0-9]/g, ''),
          mac: new URL(req.url).search.split("?")[1].split("&")[1].replace(/[^a-zA-Z0-9:]/g, ''),
          pid: Math.floor(Math.random() * (9999999 - 1000000 + 1)) + 1000000
        },
      })
    }
***
  port: port,
  websocket: {
    open(ws) {
      ws.subscribe(ws.data.room);
      ws.send(`Enter name:`);
    },
    message(ws, msg) {
      var dateString = viewDateTime();
***
      if (ws.data.name == "none") {
        ws.data.name = msg;
        msg = `joined`;
        ws.send(`[${dateString}] Welcome to the control ${ws.data.name}!`);
        console.log(dateString+' Connect: ' + ws.data.room + ' ' + ws.data.mac + ' ' + ws.data.pid + ' ' + ws.data.name);
***
        const result = db.query(`SELECT * FROM online WHERE token = '${ws.data.room}' AND mac = '${ws.data.mac}'`).get();
          db.query(`DELETE FROM online *** `).get();
        }
        db.query(`INSERT INTO online *** `).get();
      }
 ***
      }
      const out = `[${dateString}] ${ws.data.name} ${msg}`;
      ws.publishText(ws.data.room, out);
      ws.send(out);
    },
    close(ws, code, message) {
      var dateString = viewDateTime();
      const out = `[${dateString}] ${ws.data.name} disconnect`;
      ws.unsubscribe(ws.data.room);
      server.publish(ws.data.room, out);
***
      db.query(`DELETE FROM online  *** ');
      delete ws.data;
    },
    perMessageDeflate: false,
    idleTimeout: 60,  // 900 = 15min default: 120 (seconds)
  },
});



```

**Comment by Jarred-Sumner** [comment]
Oh, I wonder if it's `delete ws.data`. If you instead `ws.data = null` or `ws.data = undefined`, does that help?

**Comment by renat2985** [comment]
Ok, thanks.

**Comment by renat2985** [comment]
replace `delete ws.data` with `ws.data = null` 
unfortunately this did not help.

**Comment by Electroid** [comment]
Fixed by https://github.com/oven-sh/bun/pull/13319
