### ISSUE TITLE
bun script runner fail to execute prisma

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#1191]
### Version

0.1.10

### Platform

Mac intel

### What steps will reproduce the bug?

```sh
bun add prisma@4.1.0
bun prisma
bun prisma -v
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Same as yarn
```sh

◭  Prisma is a modern DB toolkit to query, migrate and model your database (https://prisma.io)

Usage

  $ prisma [command]
[...]
```
```sh
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : darwin
[...]
```

### What do you see instead?

```sh
error: Failed to run "prisma" due to error ChildExecFailed
```
```sh
0.1.10
```

Also reproduced in 0.1.9 and 0.1.4

**Comment by xhyrom** [comment]
Because node's child_process is not implemented (https://cs.github.com/?scopeName=Prisma&scope=repo%3Aprisma%2Fprisma&q=child_process)

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/595

**Comment by marchellodev** [comment]
Prisma seems to be working now. There are still some problems now

**Comment by Zhomart** [comment]
It's still happening, even though https://github.com/oven-sh/bun/issues/595 is implemented.

```
$ bun --version
0.4.0

$ bun run prisma generate
error: Failed to run "prisma" due to error ChildExecFailed
```

**Comment by Jarred-Sumner** [comment]
The bug is that `waitpid` is returning `ECHILD` when it shouldn't be. It could be a signal handler causing an issue. Need to read more to understand why this happens

**Comment by zzjin** [comment]
Same error here with:

```
bun upgrade
bun v0.5.1 is out! You're on 0.4.0
error Failed to verify bun ChildExecFailed)
```

But bun is upgraded to v0.5.1, just show this error message.

**Comment by OmLanke** [comment]
> Same error here with:
> 
> ```
> bun upgrade
> bun v0.5.1 is out! You're on 0.4.0
> error Failed to verify bun ChildExecFailed)
> ```

Same with me. Intel MacOS Monterey

**Comment by ArnaudBarre** [comment]
I opened another issue for the upgrade issue: https://github.com/oven-sh/bun/issues/1860

**Comment by Zhomart** [comment]
`bun run prisma generate` works on v0.5.1!

<img width="768" alt="image" src="https://user-images.githubusercontent.com/830536/213873044-09b48076-7d5c-4957-ac41-3968dac63bac.png">

**Comment by ArnaudBarre** [comment]
Closing the issue but FWI I'm not able to run Prisma fully in bun because `Buffer.alloc` is undefined
