### ISSUE TITLE
`command not found: SET` in Windows

### ISSUE THREAD

**Issue by hyoretsu** [oven-sh/bun#11910]
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create the following script `SET NODE_OPTIONS=--max_old_space_size=4096&&SET NODE_ENV=development&&webpack --progress --color --watch --env dev` and run it

### What is the expected behavior?

It should run, like it does on Yarn

### What do you see instead?

bun: command not found: SET

**Comment by paperdave** [comment]
Bun runs package.json scripts as bash scripts, to make it consistent with how it runs on Linux. To opt out of this behavior, you can pass `--shell=system` or add this into [bunfig.toml](https://bun.sh/docs/runtime/bunfig#run-shell-use-the-system-shell-or-bun-s-shell)

```
[run]
shell = "system"
```
