### ISSUE TITLE
bug crach

### ISSUE THREAD

**Issue by 0xx9** [oven-sh/bun#11934]
### How can we reproduce the crash?

import { readFile, writeFileSync } from 'fs';
import axios from 'axios';
import qs from 'qs';  // For converting data to URL-encoded format
import { v4 as uuidv4 } from 'uuid';

let autoCallCount = 0;
let totalAutoTime = 0;

readFile('sessionid.txt', 'utf8', (err, datasession) => {
  if (err) {
    console.error('sessionid.txt is not there');
    return;
  }

  const lines = datasession.trim().split('\n');
  const sessions = lines.map(line => line.trim());

  let sessionIdle = 0;
  const getSession = () => {
    if (sessionIdle >= sessions.length) {
      sessionIdle = 0;
    }
    sessionIdle++;
    return sessions[sessionIdle - 1];
  };

  const got = [];

  const lsd = "Jzjg4rUruOR0MRbYcsZQWV";
  const username = "_0x1";  // Replace with the actual username
  const randomString = () => Math.random().toString(36).substring(2, 15); // Generates a random string

  const url = "privetapi";

  const data = {
    route_url: `/${username}/`,
    routing_namespace: "igx_www",
    __d: "www",
    __user: "0",
    __a: "1",
    __req: "f",
    __hs: "19815.HYP:instagram_web_pkg.2.1..0.1",
    dpr: "1.5",
    __ccg: "UNKNOWN",
    __rev: "1012466965",
    __s: "tm6xmf:hiczu3:l6feh8",
    __hsi: "7353111851706739166",
    __dyn: "7xeUjG1mxu1syUbFp40NonwgU7SbzEdF8aUco2qwJxS0k24o0B-q1ew65xO0FE2awt81s8hwGwQwoEcE7O2l0Fwqo31w9a9x-0z8jwae4UaEW2G1NwwwNwKwHw8Xxm16wUwtEvwww4cwJCwLyES1Twoob82cwMwrUdUbGwmk0KU6O1FwlE6PhA6bxy4VUK6V89F8C58",
    __csr: "gmMlLOgLOl4FaBSJkHtELnnV9bvAGCkoQ_HGl5LBBRAAhKDG8il4XFVrQqUMxrABh_RXAyGAGhbUzCmuV-Xu9jy98yqGoO5FZ6izaDx6FEyaxqQVV-FbUKFe4VqG5UpxGte00l361MDOwea0OE1fO043yE0Ue06V9VQaCG1co4W4Nd5wEK2d0to9F9z1m0bMw3i9QaIw3Ng7UE6Dw2l83jCwqE58gdg02k3w",
    __comet_req: "7",
    fb_dtsg: "NAcNno8k5RFZW36GMJNLWhL-ZFARg_yO3Hssi1cec9aH394hcGR_xEA:17864721031021537:1689368114",
    jazoest: "25998",
    lsd: lsd,
    __spin_r: "1012466965",
    __spin_b: "trunk",
    __spin_t: "1712029765"
  };

  const headers = {
    'Host': 'www.privetapi.com',
    'Accept-Language': 'en-US,en;q=0.9,ar;q=0.8',
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36',
  };

  let xx = 0;
  function go() {
    axios.post(url, qs.stringify(data), { headers })
      .then(response => {
        if (response.data == 'for (;;);{"payload":{"error":true},"dtsgAsyncGetToken":null,"dtsgToken":null}') {
          console.log('yes')
        }
        console.log(xx)
        xx++;
      })
      .catch(error => {
        console.error('Error:', error);
      });
  }

  setInterval(() => {
    go();
    process.title = xx;
  }, 10);
});

### Relevant log output

```shell
C:\Users\jasim\Desktop\newmoon>bun run index.js
0
1
2
3
4
5
6
7
8
9
10
============================================================
Bun v1.1.13 (bd6a6051) Windows x64
Args: "bun" "run" "index.js"
Features: jsc fetch(142) tsconfig(7)
Builtins: "bun:main" "node:assert" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:path" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib"
Elapsed: 1641ms | User: 765ms | Sys: 156ms
RSS: 0.20GB | Peak: 0.20GB | Commit: 0.25GB | Faults: 51116

panic(main thread): Segmentation fault at address 0x1A8407841A0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.13/wr1bd6a605AigiggECiB\VCRUNTIME140.dll4mK2vpoNqvooN20mp4C______A2wag6ghvgC


C:\Users\jasim\Desktop\newmoon>
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x1E0FA6329B0

- ??? at `0x146c` in VCRUNTIME140.dll
- [`brotli.zig:573`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/api/brotli.zig#L573>): `run`
- [`brotli.zig:526`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/api/brotli.zig#L526>): `decodeSync`
- `??`
- *6 unknown/js code*

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.21 with #12800
