### ISSUE TITLE
worker_threads.Worker option "eval" is not yet implemented in Bun

### ISSUE THREAD

**Issue by zhuyuanmin** [oven-sh/bun#11932]
### What version of Bun is running?

v1.1.13

### What steps can reproduce the bug?

![image](https://github.com/oven-sh/bun/assets/23226876/a6bef19b-de50-479f-aca7-4c3e5399dc20)

**Comment by Jarred-Sumner** [comment]
Bun v1.1.13 implemented this in #3925 

Please make sure you're using Bun v1.1.13. You might have multiple versions of Bun installed. This error message comes from an older version of Bun.

**Comment by zhuyuanmin** [comment]
I sure my bun version is 1.1.13 ，windows 64

![image](https://github.com/oven-sh/bun/assets/23226876/3a884ce4-32a7-4486-844f-8cf6bbb92063)

**Comment by Jarred-Sumner** [comment]
@zhuyuanmin it could be an issue with bunx. If you run `bun x —bun vite build` does that fix it? It’s possible bunx is pointing to an older version of bun.

**Comment by zhuyuanmin** [comment]
> @zhuyuanmin it could be an issue with bunx. If you run `bun x --bun vite build` does that fix it? It’s possible bunx is pointing to an older version of bun.

You are right, but there is another issue with the build process.
![image](https://github.com/oven-sh/bun/assets/23226876/19ed7bc2-e59b-4c59-9669-14e82dc67945)

**Comment by Jarred-Sumner** [comment]
can you file that issue separately?
