### ISSUE TITLE
rejectUnauthorized in https agent doesn't work

### ISSUE THREAD

**Issue by danrvc** [oven-sh/bun#11942]
### What version of Bun is running?

1.1.13

### What platform is your computer?

Windows

### What steps can reproduce the bug?

```typescript
import https from "https";

const httpsAgent = new https.Agent({
    rejectUnauthorized: false,
});

// Then use agent in axios
```

### What is the expected behavior?

The same exact code works in NodeJS but in Bun I'm getting this error:
`DEPTH_ZERO_SELF_SIGNED_CERT: self signed certificate`

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/95404853/888d722f-b88a-4dfc-a9ef-156e13ef52cd)

**Comment by kravetsone** [comment]
maybe similar issue - https://github.com/oven-sh/bun/issues/11821

**Comment by Jarred-Sumner** [comment]
I think https://github.com/oven-sh/bun/pull/11826 will fix this case

**Comment by bitofbreeze** [comment]
It still doesn't work as an argument to the Agent used with undici.
