### ISSUE TITLE
Bun crashing on SSL/TLS upgrade with pg package

### ISSUE THREAD

**Issue by XTREME1738** [oven-sh/bun#11951]
### How can we reproduce the crash?

[demo](https://github.com/XTREME1738/bun-crash-tls-demo/blob/main/src/demo.ts)
Crashes when connecting via TLS/SSL to a PostgreSQL database using the pg package.

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000130

- `us_socket_wrap_with_tls`
- [`uws.zig:300`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/deps/uws.zig#L300>): `wrapTLS`
- [`socket.zig:2967`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/api/bun/socket.zig#L2967>): `upgradeTLS`
- `??`
- *6 unknown/js code*

Features: jsc, Bun.stdin, http\_server, transpiler\_cache, tsconfig\_paths, tsconfig

**Comment by cirospaciari** [comment]
Fixed in canary v1.1.22 if is happening after `bun upgrade --canary` feel free to reopen
