### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#11955]
### Stack Trace (bun.report)

Bun v1.1.14 ([`9621721`](<https://github.com/oven-sh/bun/tree/9621721e3df4f618cc1f975b043dbefd7fd61c07>)) on linux x86_64 [AutoCommand]

**panic**: [1m32 | [0mconsole[0m[3m[1m.log[0m([0m[32m"Listening on"[0m, server.port)[0m[2m;[0m
                                              [1m[31m[1m^[0m
[31merror[0m[2m: [0m[1mExpected scope (src.js_ast.Scope.Kind.function_args, 718) in /home/hussein/Desktop/rspack-project/server.tsx, found scope (src.js_ast.Scope.Kind.label, 596)[0m
    [2mat [0m[36m/home/hussein/Desktop/rspack-project/server.tsx[0m[2m:[0m[33m32[0m[2m:[0m[33m42[0m

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/deps/zig/lib/std/debug.zig#L373>): `debug.panicExtra__anon_477631`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/deps/zig/lib/std/debug.zig#L348>): `debug.panic__anon_453104`
- [`Global.zig:183`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/Global.zig#L183>): `src.Global.panic__anon_395392`
- [`js_parser.zig:14267`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L14267>): `src.js_parser.NewParser_`
- [`js_parser.zig:6790`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L6790>): `src.js_parser.NewParser_`
- [`js_parser.zig:17160`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L17160>): `src.js_parser.NewParser_`
- [`js_parser.zig:16868`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L16868>): `src.js_parser.NewParser_`
- [`js_parser.zig:15629`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L15629>): `src.js_parser.NewParser_`
- [`js_parser.zig:19579`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L19579>): `src.js_parser.NewParser_`
- [`js_parser.zig:21186`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/js_parser.zig#L21186>): `src.js_parser.NewParser_`

**Comment by Jarred-Sumner** [comment]
Do you have any code that reproduces this issue?

**Comment by huseeiin** [comment]
> Do you have any code that reproduces this issue?

no, unfortunately
