### ISSUE TITLE
bun upgrade from brew install should not install update

### ISSUE THREAD

**Issue by glensc** [oven-sh/bun#11978]
### What version of Bun is running?

1.1.13

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

$ brew install oven-sh/bun/bun # assume it installs 1.1.13
$ bun upgrade # this will update to 1.1.14, which is now replacing brew installed version

### What is the expected behavior?

bun shouldn't do self update if it's under package manager control. in this example it was installed via brew, so brew must be used to update bun package

### What do you see instead?

bun installed from brew is replaced with 1.1.14 binaries, brew still thinks it has 1.1.13 installed

### Additional information

Having come from other package manager, tried to run some command that would "update all packages" but accidentally updated bun itself.

**Comment by Jarred-Sumner** [comment]
If you want to use homebrew to manage your version of bun, don't run `bun upgrade` and instead use homebrew

Manually disabling this on bun's end is likely to cause more confusion and make it harder for people to upgrade to the latest version of bun and get stuff fixed

**Comment by glensc** [comment]
as added in extra: ran it mistakenly, wanted to update all packages. also the brew packages is under your organization.

bun could detect the scenario and tell use "brew upgrade blah"
