### ISSUE TITLE
`bun patch --commit` fails for scoped packages

### ISSUE THREAD

**Issue by gabrielmaldi** [oven-sh/bun#11971]
### What version of Bun is running?

1.1.15-canary.1+3ff29955a

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. `bun patch @sanity/rich-date-input`
2. Make changes to some files in `node_modules/@sanity/rich-date-input`
3. `bun patch --commit 'node_modules/@sanity/rich-date-input'`
4. Error

### What is the expected behavior?

`bun patch --commit` finishes without error and correctly creates the patch file.

### What do you see instead?

`bun patch --commit` fails:

![image](https://github.com/oven-sh/bun/assets/3728897/1e739cf9-87da-4465-b75a-3de87dd1f3b9)

But the stated file does exist:

![image](https://github.com/oven-sh/bun/assets/3728897/5fcf5e62-ddd9-4baf-8ef1-a56303884ff5)

Nevertheless, the patch file is created (albeit encoding `/` into `%2F`):

![image](https://github.com/oven-sh/bun/assets/3728897/9409dfd4-beb7-4d4b-9678-a41dee1bdca0)

But the patch file, in addition to containing the applied changes, also has the rest of the untouched files:

![image](https://github.com/oven-sh/bun/assets/3728897/e06d95c7-2270-498b-b923-aa4f22b6facd)

![image](https://github.com/oven-sh/bun/assets/3728897/d29de2ae-bc8d-4bcc-b02b-2e80f863eaf5)

If I edit the patch file to only contain the actual changes, then `bun install` correctly applies the patch and everything works. So the problem is in `bun patch --commit` for —I think— scoped packages. I can even edit the patch file name to use a `+` instead of `%2F` (like `patch-package` does) and Bun accepts that:

![image](https://github.com/oven-sh/bun/assets/3728897/6bde8f82-7fbe-46e2-8cd4-f8ac03faa07d)

**Comment by gabrielmaldi** [comment]
I just tried `bun patch --commit @sanity/rich-date-input` (as stated in the [release notes](https://bun.sh/blog/bun-v1.1.14#qmJfwfAUkcFI)) instead of `bun patch --commit 'node_modules/@sanity/rich-date-input'` (`bun patch` output) and the behavior is exactly the same.

**Comment by zackradisic** [comment]
Hi @gabrielmaldi, thanks for opening this issue.

This appears to be an issue with workspaces, specifically that `bun patch --commit` is using the wrong directory.

Will have a fix up soon

**Comment by gabrielmaldi** [comment]
Can confirm this works now, thanks!

Would you consider changing patches file names for scoped packages from `@sanity%2Frich-date-input@3.0.1.patch` to `@sanity+rich-date-input@3.0.1.patch` if I open a new issue?
