### ISSUE TITLE
Property ''as' does not exist on type 'Statement<...>'

### ISSUE THREAD

**Issue by calebamiles** [oven-sh/bun#11980]
### What version of Bun is running?

1.1.14

### What platform is your computer?

Linux 6.1.0-21-amd64 x86_64 unknown

### What steps can reproduce the bug?

attempt to append `.as()` to a query in VS Code

### What is the expected behavior?

[newly added functionality][] to map query results to a class to not add Typescript error as seen from VS Code 

[newly added functionality]: https://bun.sh/docs/api/sqlite#as-class-map-query-results-to-a-class

### What do you see instead?

when appending `.as(ClassName)` to a query VS Code highlights an error:

````
Property 'as' does not exist on type 'Statement<unknown, SQLQueryBindings[] | [null] | [string] | [number] | [bigint] | [false] | [true] | [Uint8Array] | [Uint8ClampedArray] | ... 9 more ... | [...]>'.ts(2339)
```

### Additional information

it's somewhat surprising that `@types/bun` is versioned independently from `bun-types` or the bun runtime itself

**Comment by calebamiles** [comment]
possibly [this PR][] will fix things?

[this PR]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69850

**Comment by Jarred-Sumner** [comment]
yes
