### ISSUE TITLE
GPG Key expiration error when building devcontainer

### ISSUE THREAD

**Issue by hqnna** [oven-sh/bun#1200]
### What steps will reproduce the bug?

Follow the guide on the README for development on linux:
- Clone the repository with `git clone https://github.com/oven-sh/bun`
- Attempt to build the devcontainer with `cd bun && make devcontainer-build`

### How often does it reproduce? Is there a required condition?

Consistently, 100% of the time. No condition required.

### What is the expected behavior?

The dev container should build and launch successfully.

### What do you see instead?

An error is returned from the command saying the GPG key is expired:
```
W: GPG error: https://cli.github.com/packages focal InRelease: The following signatures were invalid: EXPKEYSIG C99B11DEB97541F0 Nate Smith <vilmibm@github.com>
E: The repository 'https://cli.github.com/packages focal InRelease' is not signed.
The command '/bin/sh -c mkdir -p /home/ubuntu/.bun /home/ubuntu/.config $GITHUB_WORKSPACE/bun &&     bash /scripts/common-debian.sh &&     bash /scripts/github.sh &&     bash /scripts/nice.sh &&     bash /scripts/zig-env.sh' returned a non-zero code: 100
[124910 ms] Error: Command failed: docker build -f /home/hanna/dev/bun/Dockerfile.devcontainer -t vsc-bun-0690fe241c74e940af45ae1e03e20e1b --target bun.devcontainer --cache-from ghcr.io/oven-sh/bun.devcontainer:latest --build-arg BUILDARCH=amd64 --build-arg --platform=linux/amd64 --build-arg --tag=ghcr.io/oven-sh/bun.devcontainer:latest /home/hanna/dev/bun
```

### Additional information

Running on WSL2, fedora:
- `Linux solar 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- `Docker version 20.10.17, build aa7e414`
- Commit [89524d5](https://github.com/oven-sh/bun/commit/89524d55bdbe4a799d6eb8b4141ed7e2ebd0b3ce)

**Comment by Kit-p** [comment]
As <https://github.com/cli/cli/issues/6175#issuecomment-1235984381> suggests directly fetching the latest binary from GitHub release, <https://github.com/devcontainers/features/pull/133> should just be the solution for now.
