### ISSUE TITLE
Bun install: panic(main thread): Internal assertion failure

### ISSUE THREAD

**Issue by fzn0x** [oven-sh/bun#12003]
### How can we reproduce the crash?

Got this on bun install

bunfig.toml

```toml
[install.lockfile]
print = "yarn"
```

### Relevant log output

```shell
bun install v1.1.8-canary.1 (889ec13b)
Saving yarn.lock... ============================================================
Bun Canary v1.1.8-canary.1 (889ec13b) Windows x64 (baseline)
Args: "C:\Program Files\Git\usr\local\node_modules\bun\bin\bun.exe", "install"
Features: bunfig 
Elapsed: 144ms | User: 0ms | Sys: 15ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.28GB | Faults: 38496

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8-canary ([`889ec13`](<https://github.com/oven-sh/bun/tree/889ec13b3221f1697d0e39dd9e19752f8ac9370d>)) on windows x86_64_baseline [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/output.zig#L356>): `panic`
- [`bun.zig:3177`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/bun.zig#L3177>): `assertionFailure`
- [`lockfile.zig:1427`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/install/lockfile.zig#L1427>): `packages`
- [`lockfile.zig:1405`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/install/lockfile.zig#L1405>): `print`
- [`install.zig:10976`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/install/install.zig#L10976>): `installWithManager`
- [`filter_run.zig:428`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/cli/filter_run.zig#L428>): `install`
- [`cli.zig:1440`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/cli.zig#L1440>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/889ec13b3221f1697d0e39dd9e19752f8ac9370d/src/cli.zig#L62>): `start`

Features: bunfig

**Comment by dylan-conway** [comment]
This was fixed in bun `v1.1.13` with #11763
