### ISSUE TITLE
Convenient multithreading like GO

### ISSUE THREAD

**Issue by phrynus** [oven-sh/bun#12028]
### What is the problem this feature would solve?

Processing of multithreading

### What is the feature you are proposing to solve the problem?

Convenient multithreading like GO

### What alternatives have you considered?

Workers; But the effect is like dog poop

**Comment by Polygons1** [comment]
maybe like a Bun.Thread class

**Comment by paperdave** [comment]
closing this as it is unclear exactly what this feature request is. multithreading is [theoretically possible](https://webkit.org/blog/7846/concurrent-javascript-it-can-work/), but would require a large amount of work within the engine itself.
