### ISSUE TITLE
`bun create hono` on Windows needs Node.js

### ISSUE THREAD

**Issue by ryuapp** [oven-sh/bun#12038]
### What version of Bun is running?

1.1.13

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Related: https://github.com/honojs/create-hono/issues/51

Please uninstall Node.js first.
And run the following command:
```sh
bun create hono
```
And select "x-basic" as a template.
Once the template is cloned, I got an error on readFileSync.

### What do you see instead?

```sh
C:\Users\xxxx\>bun create hono
create-hono version 0.9.0
? Target directory my-app
? Which template do you want to use? x-basic
? Directory not empty. Continue? yes
✔ Cloning the template
22377 |       projectDependenciesHook.applyHook(templateName, {
22378 |         directoryPath: targetDirectoryPath
22379 |       })
22380 |     );
22381 |   } catch (e) {
22382 |     throw new Error(
                  ^
error: Error running hook for x-basic: No such file or directory
      at C:\Users\xxxx\AppData\Local\Temp\bunx-2632733703-create-hono@latest\node_modules\create-hono\bin:22382:11

Bun v1.1.13 (Windows x64)
```

### Additional information

This only occurs without Node.js installed on Windows.
If I download `create-hono` bin file locally and run it, I will get an error even though Node.js is installed.

Looks like there is a problem with readFileSync/writeFileSync.
https://github.com/honojs/create-hono/blob/f7ba1917bd1087c71deeea7e2a408484f08a8ba9/src/hooks/after-create.ts#L11-L16

**Comment by dylan-conway** [comment]
Most likely this was fixed with #11990. Can you try this with canary? (`bun upgrade --canary`)

**Comment by ryuapp** [comment]
Unfortunately it fails the same way.
```sh
C:\Users\xxxx>bun create hono@0.9.0
create-hono version 0.9.0
? Target directory my-app
? Which template do you want to use? x-basic
? Directory not empty. Continue? yes
✔ Cloning the template
22377 |       projectDependenciesHook.applyHook(templateName, {
22378 |         directoryPath: targetDirectoryPath
22379 |       })
22380 |     );
22381 |   } catch (e) {
22382 |     throw new Error(
                  ^
error: Error running hook for x-basic: No such file or directory
      at C:\Users\xxxx\AppData\Local\Temp\bunx-985628887-create-hono@0.9.0\node_modules\create-hono\bin:22382:11

Bun v1.1.16-canary.1+3b199cde5 (Windows x64)

```

**Comment by ryuapp** [comment]
There was a problem with a library it was using.
Tracking this in #12150.
