### ISSUE TITLE
cannot get request ip in sveltekit

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12055]
### What version of Bun is running?

1.1.14-canary.1+9621721e3

### What platform is your computer?

Linux 6.5.0-18-generic x86_64 x86_64

### What steps can reproduce the bug?

https://github.com/huseeiin/sveltekit-ip-bun-bug

### What is the expected behavior?

it works without `--bun`

**Comment by scffs** [comment]
dublicate of https://github.com/oven-sh/bun/issues/10458
