### ISSUE TITLE
Bun.bundle leaves __require("process/"); in the bundled code

### ISSUE THREAD

**Issue by GerbenRampaart** [oven-sh/bun#12057]
### What version of Bun is running?

1.1.15+b23ba1fe1

### What platform is your computer?

Darwin 23.4.0 x86_64 i386

### What steps can reproduce the bug?

I created an esm api project, using both commonjs and esm modules. (things like nestjs, pino, axios and so on). 

This api must work in both bun (latest) AND node (16 - 22).

It's important for me it works well in both because I work for a fortune 100 company and I can't simply switch projects over to bun without starting with the toolchain (bun install, bun test, bundling) before switching the actual runtime because, like it works in many large corporations, there's lots of convincing to be done of people.

Anyway, when I start bundling this api (because I only want to npm publish an index.js and a index.d.ts), I bundle up all libraries and frameworks.

```
const buildResult = await Bun.build({
	entrypoints: [
		join(AppConstantsService.projectRoot, 'index.ts'),
	],
	target: 'node',
	format: 'esm',
	sourcemap: 'none',
	minify: true,
	plugins: [
		// https://github.com/oven-sh/bun/issues/5141
		dts(),
	],
	outdir: join(AppConstantsService.projectRoot, AppConstantsService.libraryOutDir),
});
```

Note that I _have_ to target 'node'.

This bundling leaves an index.js which works fine stand-alone in Bun, but node errors with:
![2024-06-22 13 11 28](https://github.com/oven-sh/bun/assets/1949178/ec8536aa-24d7-486b-80ec-02c575625447)

Which seems to be because the index.js has about 28 places in the bundled code with this require
![2024-06-22 13 12 00](https://github.com/oven-sh/bun/assets/1949178/4d8a6ed8-53ff-40fb-a5fe-03c600da018d)

Now here's what puzzels me:
- Why does this work just fine in Bun?
- Why does it not work in node HOWEVER if I do a hard find-replace of 'process/' with 'process' in the bundle it works just fine in node?

minify true/false seems to have no impact on the behaviour.

**Comment by paperdave** [comment]
`process/` is expected to resolve to `node_modules/process/...`, while `process` resolves to the built-in `node:process`.

bun is being tricked into thinking `process/` is a built-in because it is "process", when in reality it needs to consider the edge case with the trailing slash

the linked PR will fix this.
