### ISSUE TITLE
NODE_ENV is undefined (1.1.15) when running with hot reload

### ISSUE THREAD

**Issue by szabbbbu** [oven-sh/bun#12056]
### What version of Bun is running?

1.1.15

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

my "dev" command and dependencies:
<img width="1377" alt="Screenshot 2024-06-22 at 13 01 05" src="https://github.com/oven-sh/bun/assets/140390606/834d3f5e-97bb-4772-8c04-4b106c4751d3">

I get "undefined" when printing out the NODE_ENV variable, when i should be getting "development". This causes me to have to have new issues with code i was using to direct DB connections. 
<img width="1046" alt="Screenshot 2024-06-22 at 13 09 37" src="https://github.com/oven-sh/bun/assets/140390606/bce2e922-8a39-445a-a2c0-a1cdadaf47b9">

This happens when checking NODE_ENV in v1.1.15:
<img width="1142" alt="Screenshot 2024-06-22 at 13 10 55" src="https://github.com/oven-sh/bun/assets/140390606/0e4c1bd8-d8ec-484a-8ece-496b5eb674fe">

This happens when checking NODE_ENV in v1.0.9:
<img width="1152" alt="Screenshot 2024-06-22 at 13 12 33" src="https://github.com/oven-sh/bun/assets/140390606/b29a468b-cee7-456e-9f4f-5de2efc38dd7">

### What is the expected behavior?

running "bun dev", the Bun.env.NODE_ENV variable should print "development"

### What do you see instead?

"undefined", inconsistent behavior between "Bun.env" and  "process.env", which should be interchangeable.

### Additional information

It's my understanding that using the "--hot" flag when running a Bun program should set the NODE_ENV variable to "development".

**Comment by Jarred-Sumner** [comment]
This is a deliberate breaking change we made in Bun v1.1.0

See https://github.com/oven-sh/bun/issues/7829 and https://github.com/oven-sh/bun/issues/7663
