### ISSUE TITLE
Bun test module mocking not working

### ISSUE THREAD

**Issue by 0pilatos0** [oven-sh/bun#12062]
### What version of Bun is running?

1.1.16-canary.1+4830e2d81

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### Description:
When using mock.module in the bun:test framework to mock the is-even module, the mock does not override the original module's behavior as expected. Despite setting up the mock before importing the module under test, the test fails because the mock does not return the mocked value.

### Steps to Reproduce:
- Create a module that uses the is-even package.
- Write a test that mocks the is-even module to always return false.
- Import the module under test and check the result of a function using the mocked module.

### Example code
```typescript
// isEvenWrapper.js
import isEven from "is-even";

export function isEvenWrapper(value: number): boolean {
  return isEven(value);
}
```

```typescript
// isEvenWrapper.test.js
import { test, expect, mock } from "bun:test";

// Mock the 'is-even' module
mock.module("is-even", () => {
  return () => false;
});

// Import the module under test
import { isEvenWrapper } from ".";

test("isEvenWrapper should always return false because of the mock", () => {
  const result = isEvenWrapper(4);
  expect(result).toBe(false); // Test should pass because of the mock returning false
});
```

### What is the expected behavior?

The isEvenWrapper function should return false for any input because the is-even module is mocked to return false.

### What do you see instead?

The test fails because the isEvenWrapper function does not return false, indicating that the is-even module was not properly mocked.

**Comment by sirenkovladd** [comment]
```js
mock.module("is-even", () => {
  return {
    default: () => false,
  };
});
```

**Comment by Jarred-Sumner** [comment]
@0pilatos0, @sirenkovladd is correct - the API for module mocks is to return an object for the exports

It sounds like we need more examples in the documentation to to make this clearer
