### ISSUE TITLE
SlowBuffer is missing - TypeError: undefined is not an object (evaluating 'SlowBuffer.prototype')

### ISSUE THREAD

**Issue by benc-uk** [oven-sh/bun#1206]
### Version

0.1.10

### Platform

Linux BENSL3 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Use the `@azure/msal-node` library or `jsonwebtoken`
Run your app
Error `TypeError: undefined is not an object (evaluating 'SlowBuffer.prototype')` is thrown

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

jsonwebtoken doesn't crash when used

### What do you see instead?

```
❯ bun server.mjs
[0.05ms] ".env"
32 |     return bufferEq(this, that);
33 |   };
34 | };
35 | 
36 | var origBufEqual = Buffer.prototype.equal;
37 | var origSlowBufEqual = SlowBuffer.prototype.equal;
                           ^
TypeError: undefined is not an object (evaluating 'SlowBuffer.prototype')
      at /app/src/node_modules/buffer-equal-constant-time/index.js:37:23
      at bun:wrap:1:16354
      at /app/src/node_modules/jwa/index.js:1:26
      at bun:wrap:1:16354
      at /app/src/node_modules/jws/lib/sign-stream.js:4:18
      at bun:wrap:1:16354
      at /app/src/node_modules/jws/index.js:2:25
      at bun:wrap:1:16354
      at /app/src/node_modules/jsonwebtoken/decode.js:1:18
      at bun:wrap:1:16354
      at /app/src/node_modules/jsonwebtoken/index.js:2:18
      at bun:wrap:1:16354
      at /app/src/node_modules/@azure/msal-node/dist/msal-node.esm.js:7:0
```

### Additional information

Apparently the missing SlowBuffer was fixed here https://github.com/oven-sh/bun/issues/1131

**Comment by xhyrom** [comment]
Please update to canary. 

GitHub Issues are related to latest canary build (commit)

**Comment by Jarred-Sumner** [comment]
Fixed in canary, but also the function is called `equals` (not `equal`). In node those functions are undefined (in node v18.4.0)
