### ISSUE TITLE
Using Worker API and setInterval

### ISSUE THREAD

**Issue by shivamklr** [oven-sh/bun#12061]
### How can we reproduce the crash?

I am using setInterval and Worker API. The main files runs every minute. Depending upon some conditions, the worker API is called. After worker is done, worker is terminated manually. 

### Relevant log output

```shell
....
(console logs....)
....
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "C:\Users\admin\scoop\apps\bun\current\bun.exe" ".\src\index.ts"
Features: jsc dotenv(53) fetch(136) transpiler_cache(102) tsconfig_paths(2) tsconfig(4) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:stream" "node:string_decoder" "node:timers" "node:timers/promises" "node:tls" "node:url" "node:util" "node:util/types" "node:zlib" 
Elapsed: 6902769ms | User: 7921ms | Sys: 2406ms
RSS: 0.33GB | Peak: 0.44GB | Commit: 0.81GB | Faults: 2723786
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x41342AF0418

- `??`
- `uv_loop_init`
- [`libuv.zig:2811`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/deps/libuv.zig#L2811>): `int`
- [`uws.zig:2787`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/deps/uws.zig#L2787>): `get`
- [`javascript.zig:2536`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/javascript.zig#L2536>): `reloadEntryPoint`
- [`javascript.zig:2591`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/javascript.zig#L2591>): `loadEntryPointForWebWorker`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa58` in ntdll.dll

**Comment by Jarred-Sumner** [comment]
This was likely fixed, but it's hard to say without a reproduction

If you leave a comment with a reproduction we would be happy to re-open it
