### ISSUE TITLE
Bun does not upgrade correctly through `winget`

### ISSUE THREAD

**Issue by panaman67** [oven-sh/bun#12089]
### What version of Bun is running?

1.1.16+bf7b327f6

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. `winget update` - see that there is a new version. 
2. `winget update -r` - winget "correctly" sees new version and does upgrade
3. `bun` - command works
4. close terminal
5. `bun` - command not recognized

### What is the expected behavior?

new version of bun works as expected after upgrade and terminal close

### What do you see instead?

```
bun : The term 'bun' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bun
+ ~~~
    + CategoryInfo          : ObjectNotFound: (bun:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Additional information

This has been a problem for me ever since starting to use bun at 1.0
Current workaround is to uninstall and reinstall.

**Comment by paperdave** [comment]
the winget installation method is not officially supported by us, as it is code that we do not maintain ourselves (there is a PR to add this into docs which i am blocking on some issues, noted here: https://github.com/oven-sh/bun/pull/9806)

Please install bun through the powershell script (after removing it with winget)

```ps1
powershell -c "irm bun.sh/install.ps1 | iex"
```
