### ISSUE TITLE
"Segmentation fault at address 0x5" when trying to bootstrap Astro project

### ISSUE THREAD

**Issue by thewirv** [oven-sh/bun#12092]
### How can we reproduce the crash?

Download the latest version of Bun (1.1.16 as of writing), run `bunx --bun create-astro@latest`, and go through the steps. If I select "TypeScript? No", then the same error occurs when agreeing to install dependencies.

Here's a screenshot of the output:
![image](https://github.com/oven-sh/bun/assets/4397989/e8a94988-3401-4f15-90b0-2094fd7a5e14)

Further information, because I just noticed the `[RunAsNodeCommand]`: I have not installed Node on my system, and I expected the `--bun` flag to ensure execution exclusively via Bun.

### Relevant log output

```shell
See provided screenshot
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- `??`
- *4 unknown/js code*

**Comment by TheWirv** [comment]
The command works after installing Node v20.15.0 and omitting the `--bun` flag. But in "Bun-only" mode there's a bug somewhere.

**Comment by nektro** [comment]
duplicate of https://github.com/oven-sh/bun/issues/12092

**Comment by TheWirv** [comment]
> duplicate of [#12092](https://github.com/oven-sh/bun/issues/12092)

Duplicate of _this issue_?

**Comment by nektro** [comment]
apologies, https://github.com/oven-sh/bun/issues/11824

**Comment by heimskr** [comment]
Fixed by #15357.
