### ISSUE TITLE
Using JS/TS on IOT devices, microcontrollers via Bun

### ISSUE THREAD

**Issue by seahindeniz** [oven-sh/bun#1209]
### What is the problem this feature will solve?

We will be able to use Bun on small environments like ESP32/ESP8266 to built small, portable and affordable devices. 
I also believe that, this will open a new door for Bun to live on IOT devices.

### What is the feature you are proposing to solve the problem?

It is not a specific feature, but the whole idea is making Bun available on microcontrollers, just like we install Bun on a Mac or PC

### What alternatives have you considered?

Espruino

**Comment by Electroid** [comment]
Thanks for opening a feature request! We want Bun to work on many different platforms, including IoT devices and microcontrollers, but it's going to be a long time before we get there.

**Comment by seahindeniz** [comment]
Alright, thanks 😃 but I didn't get why it got closed. A mistake, perhaps?
