### ISSUE TITLE
Bun crashing on almost every restart of a bot based on discord.js module

### ISSUE THREAD

**Issue by Synyxe7323** [oven-sh/bun#12096]
### How can we reproduce the crash?

Download discord.js module.
Write any code in TypeScript.
Run the code through `bun run`  

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/uws.zig#L2619>): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`
- [`run_command.zig:1304`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/run_command.zig#L1304>): `exec`
- [`cli.zig:1733`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1733>): `start`

**Comment by InFiNiTy1234568** [comment]
No. I am not.
