### ISSUE TITLE
`bun patch` not working in monorepo

### ISSUE THREAD

**Issue by Scalahansolo** [oven-sh/bun#12103]
### What version of Bun is running?

1.1.16+bf7b327f6

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Our monorepo contains plenty of apps / packages all defined in the root `package.json` workspaces array of our monorepo. After upgrading to bun 1.1.16 the following screen shot shows off the issue I am running into. 

![CleanShot 2024-06-23 at 21 35 07@2x](https://github.com/oven-sh/bun/assets/4317253/eedc77f2-f55e-4cc2-9b16-b2e475027316)

**Comment by Scalahansolo** [comment]
Opened as a response to https://github.com/oven-sh/bun/issues/2336

**Comment by flokol120** [comment]
I am also experiencing problems while trying to use `bun patch` in a monorepo:
```
bun patch monaco-editor@0.36.1
bun patch v1.1.16 (bf7b327f)

Checked 4260 installs across 2976 packages (no changes) [47.00ms]
error: error overwriting folder in node_modules: FileNotFound
```

```
ls node_modules/monaco-editor 
CHANGELOG.md  dev  esm  LICENSE  min  min-maps  monaco.d.ts  package.json  README.md  ThirdPartyNotices.txt
```
I was using the latest canary release (1.1.17-canary).

**Comment by Neiso** [comment]
Same here. Is there anything I could provide to help debug this or should I open a new issue?
 
```bash
$ bun -v
1.1.18
$ bun patch react-native-dropdown-picker
[1.05ms] ".env"
bun patch v1.1.18 (5a0b9352)

Checked 1488 installs across 1241 packages (no changes) [324.00ms]
error: error overwriting folder in node_modules: FileNotFound
```

**Comment by Jarred-Sumner** [comment]
@Neiso @adamdottv are you still running into this in the canary build of Bun?

```
bun upgrade --canary
```

**Comment by adamdottv** [comment]
> @Neiso @adamdottv are you still running into this in the canary build of Bun?
> 
> ```
> bun upgrade --canary
> ```

works for me now, thanks @Jarred-Sumner!

**Comment by hassankhan** [comment]
@Jarred-Sumner This issue persists for me in an nx monorepo with a top-level `node_modules/` on both Bun v1.1.18 and v1.1.19-canary.1 (a36a01e2)

**Comment by Jarred-Sumner** [comment]
@hassankhan can you open a new issue with a reproduction? It’s likely a different bug

**Comment by hassankhan** [comment]
@Jarred-Sumner While I was trying to create a repro, I found that opening a new terminal session and running `bun patch` in the project seems to work.

In my case, I'd upgraded bun from `1.1.14` to `1.1.18` and then `1.1.19-canary.1` in the same session.
