### ISSUE TITLE
Bun terminates windows batch script(.cmd) but, node.js not.

### ISSUE THREAD

**Issue by songinnight** [oven-sh/bun#12108]
### What version of Bun is running?

1.1.16

### What platform is your computer?

Windows 11

### What steps can reproduce the bug?

Bun terminates windows batch script(.cmd) but, node.js not.
Therefore, I cannot run the following commands in sequence.

test.js

```javscript
setTimeout(() => {
	console.log('Proc Finished. Bun terminates windows batch script(.cmd) but, node.js not.');
	
	// The code below gives the same result.
	// process.exit();
	// process.exit(0);
	// process.exit(1);
}, 1000);
```

batch.cmd

```
@echo off

echo Start Bun
bun test.js

echo It doesn't get there.
```

### What is the expected behavior?

Bun should not stop windows batch script.

**Comment by paperdave** [comment]
I cannot reproduce this in powershell or cmd / Windows terminal or conhost.
![image](https://github.com/oven-sh/bun/assets/24465214/09e377d3-c21b-44a6-bc4b-3f528c72d3fe)

can you reply with more details about how your script is being executed.
