### ISSUE TITLE
Bun install regularly fails on windows

### ISSUE THREAD

**Issue by szigetib95** [oven-sh/bun#12113]
### How can we reproduce the crash?

bun install

### Relevant log output

bun install v1.1.13 (bd6a6051)
  📦 Installing [54/2402] ============================================================
Bun v1.1.13 (bd6a6051) Windows x64
Args: "C:\Users\**\.bun\bin\bun.exe" "i"
Features: bunfig dotenv extracted_packages(96)
Elapsed: 86698ms | User: 6296ms | Sys: 62546ms
RSS: 0.74GB | Peak: 0.86GB | Commit: 0.93GB | Faults: 528044

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`output.zig:356`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/output.zig#L356>): `panic`
- [`bun.zig:3254`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.zig#L3254>): `assertionFailure`
- [`types.zig:162`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/node/types.zig#L162>): `unwrap`
- [`bin.zig:691`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/install/bin.zig#L691>): `link`
- [`install.zig:11372`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/install/install.zig#L11372>): `installPackageWithNameAndResolution`
- [`install.zig:12082`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/install/install.zig#L12082>): `installPackages`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1465`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli.zig#L1465>): `start`

**Comment by zozobalogh0817** [comment]
Same occures on my side too @szigetib95 

I'm curiously waiting how could we fix this

**Comment by SirEndii** [comment]
I had some issues with bun 1.1.12 under windows, after upgrading to bun 1.1.16 the most of them were resolved
But I also don't have as many packages as you

**Comment by szigetib95** [comment]
For me over 2000 packages its regularly happens in nearly every installation process but repeating bun install will succeed after quite some time like 2 3 times, but its very annoying in pipelines.

**Comment by szigetib95** [comment]
The same happened with the latest aswell.
Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`output.zig:357`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/output.zig#L357>): `panic`
- [`bun.zig:3252`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.zig#L3252>): `assertionFailure`
- [`fd.zig:197`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/fd.zig#L197>): `close`
- [`bin.zig:691`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/bin.zig#L691>): `link`
- [`install.zig:12090`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12090>): `installPackageWithNameAndResolution`
- [`array_list.zig:417`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/deps/zig/lib/std/array_list.zig#L417>): `clearAndFree`
- [`install.zig:6632`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L6632>): `runTasks`
- [`install.zig:12861`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12861>): `isDone`
- [`install.zig:12899`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12899>): `installPackages`
- [`install.zig:13637`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L13637>): `installWithManager`

**Comment by szigetib95** [comment]
I feel like it happens when you have something wrong with your dependencies, I've migrated my whole project to Angular v18 and updated every dependencies to latest or even compatible with current NX 19.3 and now I dont get this error during installation. 
Thanks

**Comment by szigetib95** [comment]
Today I'm facing the same issue, its feels very annoying I need to hit bun install couple of times, to finish the whole process on Windows only.
---
Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`output.zig:357`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/output.zig#L357>): `panic`
- [`bun.zig:3252`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.zig#L3252>): `assertionFailure`
- [`fd.zig:197`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/fd.zig#L197>): `close`
- [`bin.zig:691`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/bin.zig#L691>): `link`
- [`install.zig:12090`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12090>): `installPackageWithNameAndResolution`
- [`install.zig:12352`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12352>): `installPackage`
- [`install.zig:12806`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L12806>): `installPackages`
- [`install.zig:13637`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L13637>): `installWithManager`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1494`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli.zig#L1494>): `start`

**Comment by dylan-conway** [comment]
#11886 will fix this issue
