### ISSUE TITLE
importing webpack returns undefined

### ISSUE THREAD

**Issue by drinking-code** [oven-sh/bun#1212]
### Version

0.1.10

### Platform

Darwin <hostname> 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Install the webpack package `bun a webpack`
Execute a javascript file like this

```javascript
import webpack from 'webpack'

console.log(webpack) // => undefined
webpack() // throws "undefined is not a function (near '...webpack...')"
```

### How often does it reproduce? Is there a required condition?

Always (on my machine), no additional conditions required.

### What is the expected behavior?

Webpack would be imported normally, just as in Node.js

### What do you see instead?

Webpack is imported without errors, however the imported "variable" is `undefined`

### Additional information

I'm not sure, but it seems like the [`Object.freeze`](https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/index.js#L101) that webpack uses before exporting is the culprit. It's the last operation that is applied to the object before it's handed over for export and if I comment it out, the import works just fine (apart from another, unrelated error coming from `graceful-js`).

**Comment by Jarred-Sumner** [comment]
This is a CommonJS <> ESM interop bug

Seeing a few different variations of it

Will fix shortly

**Comment by Jarred-Sumner** [comment]
Fixed in canary along with the issue with `graceful-fs`, though `webpack` won't load yet due to missing `vm` module
