### ISSUE TITLE
readLine.createInterface closes early

### ISSUE THREAD

**Issue by dtorres** [oven-sh/bun#12125]
### What version of Bun is running?

1.1.15+b23ba1fe1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create a test file at `/tmp/testfile.txt` with the following content:
```
1
2
3
4
```

Run this script:
```
import { createReadStream, existsSync } from 'fs';
import { createInterface } from 'readline';

const fileStream = createReadStream("/tmp/testfile.txt", {encoding: "latin1"});

  const rl = createInterface({
    input: fileStream,
    crlfDelay: Infinity
  });

  for await (const line of rl) {
    console.log(`Line 1: ${line}`)
    break;
  }

  for await (const line of rl) {
    console.log(`Line 2: ${line}`)
    break;
  }

  for await (const line of rl) {
    console.log(`Line 3: ${line}`)
    break;
  }

  for await (const line of rl) {
    console.log(`Line 4: ${line}`)
    break;
  }
```

### What is the expected behavior?

```
Line 1: 1
Line 2: 2
Line 3: 3
Line 4: 4
```

### What do you see instead?

```
Line 1: 1
```

### Additional information

This was tested agains Node v22.3.0 which works as expected

**Comment by RiskyMH** [comment]
@dtorres this seems to have been fixed in `v1.1.34` from my testing. 

If you're still running into this issue, please let me know and I'll re-open this
