### ISSUE TITLE
Writing file to stdout causes Bun to crash unexpectedly.

### ISSUE THREAD

**Issue by ejini6969** [oven-sh/bun#12134]
### How can we reproduce the crash?

Code that causes failure

```js
// write file incrementally
const file2 = Bun.file('./test.txt');
const writer = file2.writer();
writer.write("A");
writer.write("B");
writer.write("C");
writer.flush(); // flush the buffer
writer.end() // flush buffer and close file
// write Blob to file (transfer content from 1 file to another)
await Bun.write('./test2.txt', Bun.file('./test.txt'));
// write to stdout
await Bun.write(Bun.stdout, file2)
```

### Relevant log output

```shell
panic(main thread): reached unreachable code
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.15/wr1b23ba1fAyggggEqkglC48nMkwhlT6j8+Jwz99J_A1

error: script "js" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [AutoCommand]

**panic**: reached unreachable code

- [`mem.zig:197`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/deps/zig/lib/std/mem.zig#L197>): `copyForwards`
- [`windows.zig:3402`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/windows.zig#L3402>): `GetFinalPathNameByHandle`
- [`blob.zig:2020`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/webcore/blob.zig#L2020>): `copyfile`
- [`blob.zig:881`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/webcore/blob.zig#L881>): `writeFileWithSourceDestination`
- [`blob.zig:1201`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/webcore/blob.zig#L1201>): `writeFile`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment]
Related https://github.com/ziglang/zig/issues/18756
