### ISSUE TITLE
Bun install not working on main repo

### ISSUE THREAD

**Issue by codeman4033** [oven-sh/bun#12135]
### How can we reproduce the crash?

Bun install on main repo

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`output.zig:357`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/output.zig#L357>): `panic`
- [`bun.zig:3252`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/bun.zig#L3252>): `assertionFailure`
- [`resolve_path.zig:563`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/resolver/resolve_path.zig#L563>): `windowsVolumeNameLen`
- [`resolve_path.zig:1352`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/resolver/resolve_path.zig#L1352>): `_joinAbsStringBuf`
- [`lockfile.zig:4757`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/lockfile.zig#L4757>): `parseWithJSON`
- [`lockfile.zig:3932`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/lockfile.zig#L3932>): `parse`
- [`install.zig:13391`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L13391>): `installWithManager`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1494`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli.zig#L1494>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli.zig#L62>): `start`

**Comment by dylan-conway** [comment]
Interesting, does this happen with each install?

**Comment by cody-ferguson** [comment]
Yes

**Comment by Jarred-Sumner** [comment]
@cody-ferguson what is the current working directory path?

**Comment by cody-ferguson** [comment]
D:\Code\Improvement repos\bun

**Comment by Jarred-Sumner** [comment]
If you type `pwd` in PowerShell is that precisely what it prints? The stacktrace implies we have a parsing issue with Windows filesystem paths so seeing exactly what it prints is important to help us fix it

**Comment by cody-ferguson** [comment]
In that case this is precisely what it prints
```
Path
----
D:\Code\Improvement repos\bun

```

**Comment by cody-ferguson** [comment]
Too bad I can't try and fix it myself...

**Comment by cody-ferguson** [comment]
> Interesting, does this happen with each install?

Also it even happens on the canary version

**Comment by museadam** [comment]
What is items are you trying to install? Like what does your package.json look like?

**Comment by cody-ferguson** [comment]
The `package.json` is the one on the official repo...
