### ISSUE TITLE
Implement os version report for Windows

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#12133]
#12098 did not implement windows support. The crash message should be able to say `Windows 11 v10.x.x.x`. This is likely just calling two functions for the display name, and the version number, respectively.

This is low priority but very simple. If an outside contributor wants to add it, just look at the PR and see where it's missing info on Windows.

**Comment by CarlosEduR** [comment]
hey @paperdave, can I open a PR for this?

**Comment by paperdave** [comment]
sure
