### ISSUE TITLE
`bun dev` on a new react app wrongly serves static manifest.json as ES module

### ISSUE THREAD

**Issue by BarbieroDB1** [oven-sh/bun#1213]
### Version

0.1.10

### Platform

```
Linux USER 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### What steps will reproduce the bug?

```sh
bun create react bun-react-app
cd bun-react-app
bun dev
curl -v http://localhost:3000/public/manifest.json
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Since this is a static JSON on `/public`, the expected result should be the json itself(with `Content-Type` set to `application/json`, preferably), so that things like `<link rel="manifest"` work properly.

Maybe there should be a bunfig option to set certain files(especially public assets) to not be transpiled?

### What do you see instead?

The `curl` command will output this:
```
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /public/manifest.json HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 YAY
< Date: Tue, 6 Sep 2022 14:45:30 GMT
< Connection: close
< Content-Type: text/javascript;charset=utf-8
< ETag: CD6FE17852515044
< Content-Length: 476
< 
export default {
  short_name: "React App",
  name: "Create React App Sample",
  icons: [
    {
      src: "favicon.ico",
      sizes: "64x64 32x32 24x24 16x16",
      type: "image/x-icon"
    },
    {
      src: "logo192.png",
      type: "image/png",
      sizes: "192x192"
    },
    {
      src: "logo512.png",
      type: "image/png",
      sizes: "512x512"
    }
  ],
  start_url: ".",
  display: "standalone",
  theme_color: "#000000",
  background_color: "#ffffff"
};
```

note how the JSON file was somehow transpiled to ESM, even though this is a manifest file in `/public`.

### Additional information

related issues:
- https://github.com/oven-sh/bun/issues/856
- https://github.com/oven-sh/bun/issues/494

**Comment by kamikaz1k** [comment]
Same issue - just renamed my files to deal with it... for now

**Comment by birkskyum** [comment]
`bun dev` is removed
