### ISSUE TITLE
`bun upgrade` shouldn't assume --canary after using it once

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12147]
i was using a canary build and i just upgraded
it tells me "Welcome to Bun's latest canary build!"
even tho i didn't pass `--canary`
`bun install` says "bun install v1.1.17-canary.1"
but `bun -v` says "1.1.17"
i think bun upgrade shouldn't make --canary the default after using it once

**Comment by Jarred-Sumner** [comment]
This is intentional. If you're using canary, you probably want to keep using canary. If you're using stable, you probably want to keep using stable. We offer `--stable` and `--canary` flags to change this default.

**Comment by pkpowell** [comment]
It seems to install canary if you do a regular `bun upgrade` while on the latest stable version.
Shouldn't it default to stable?

````
~ -> bun --version 
1.1.20

~ -> bun upgrade
Bun v1.1.22 is out! You're on v1.1.20
[1.60s] Upgraded.

Welcome to Bun v1.1.22!

What's new in Bun v1.1.22:

    https://bun.sh/blog/release-notes/bun-v1.1.22

Report any bugs:

    https://github.com/oven-sh/bun/issues

Commit log:

    https://github.com/oven-sh/bun/compare/bun-v1.1.20...bun-v1.1.22


~ -> bun upgrade
[1233.00ms] Upgraded.

Welcome to Bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/df33f2b2a264912c7a742d0c03587082415fbba6...main
````

**Comment by huseeiin** [comment]
> It seems to install canary if you do a regular `bun upgrade` while on the latest stable version. Shouldn't it default to stable?
> 
> ```
> ~ -> bun --version 
> 1.1.20
> 
> ~ -> bun upgrade
> Bun v1.1.22 is out! You're on v1.1.20
> [1.60s] Upgraded.
> 
> Welcome to Bun v1.1.22!
> 
> What's new in Bun v1.1.22:
> 
>     https://bun.sh/blog/release-notes/bun-v1.1.22
> 
> Report any bugs:
> 
>     https://github.com/oven-sh/bun/issues
> 
> Commit log:
> 
>     https://github.com/oven-sh/bun/compare/bun-v1.1.20...bun-v1.1.22
> 
> 
> ~ -> bun upgrade
> [1233.00ms] Upgraded.
> 
> Welcome to Bun's latest canary build!
> 
> Report any bugs:
> 
>     https://github.com/oven-sh/bun/issues
> 
> Changelog:
> 
>     https://github.com/oven-sh/bun/compare/df33f2b2a264912c7a742d0c03587082415fbba6...main
> ```

that sounds like a bug and different from my original issue. you should open a new issue

**Comment by ansh** [comment]
I'm facing that issue too @pkpowell
