### ISSUE TITLE
Crypto is undefinned in browser

### ISSUE THREAD

**Issue by Booteille** [oven-sh/bun#12154]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 6.9.3-76060903-generic x86_64 x86_64

### What steps can reproduce the bug?

I am trying to generate a key using Web Crypto API.

```typescript
crypto.subtle.generateKey(
        {
            name: "AES-GCM",
            length: 256,
        },
        true,
        ["encrypt", "decrypt"]
    );
```

### What is the expected behavior?

I would like to be able to use Web Crypto API when targeting `browser`.

### What do you see instead?

It works fine using bun runtime but when I build the app with `browser` as a target, I get the following error in my browser console:

`TypeError: crypto.subtle is undefined`

### Additional information

What can I do to make Web Crypto API work with bun in browser?

**Comment by paperdave** [comment]
the above code sample bundles to
```
// index.ts
crypto.subtle.generateKey({
  name: "AES-GCM",
  length: 256
}, true, ["encrypt", "decrypt"]);
```
which does not throw in Safari 17.5. I used `bun build index.ts --target=browser > out.js` to build this.

can you share a more complete reproduction?

**Comment by Booteille** [comment]
Hi!

Here is a complete code I just used to try it:

index.ts
```typescript
const run = async() => {
  const key = await crypto.subtle.generateKey(
    {
        name: "AES-GCM",
        length: 256,
    },
    true,
    ["encrypt", "decrypt"]
);

console.debug(key)
}

run()
```

Build command used:
`bun build --target=browser src/index.ts  --outfile=dist/lufi-api.browser.sourcemap.js --sourcemap`

Tried on Firefox 127.0 on Linux Pop!_OS.

**Comment by Booteille** [comment]
I just understood what was wrong.

The development server I was running on the app using this script was not providing a HTTPS context so the crypto API was not available.

There is nothing wrong with Bun here.

Anyway, thanks for your time.
