### ISSUE TITLE
Typescript cannot find .vue file when running type-check in new Vue project through Docker image

### ISSUE THREAD

**Issue by andyexeter** [oven-sh/bun#12153]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 6.8.0-35-generic x86_64 x86_64

### What steps can reproduce the bug?

When running the `type-check` command on a newly created Vue project through the Docker image the following error is thrown:

```
src/main.ts(4,17): error TS2307: Cannot find module './App.vue' or its corresponding type declarations.
```

Running the same command through my host machine's Bun (same version) doesn't throw this error. Running it through Node doesn't throw it either.

Steps to reproduce:

Create a Vue project (with TypeScript support):

```console
npm create vue@latest
cd vue-project
npm install
```

Run the following:

```console
docker run --rm -v $PWD:/app -w /app oven/bun:1.1.17 run type-check
```

And see the following error:

```console
$ vue-tsc --build --force
src/main.ts(4,17): error TS2307: Cannot find module './App.vue' or its corresponding type declarations.
```

### What is the expected behavior?

No errors

### What do you see instead?

```console
src/main.ts(4,17): error TS2307: Cannot find module './App.vue' or its corresponding type declarations.
```

### Additional information

Running the following commands do not throw this error:

```console
bun run type-check
docker run --rm -v $PWD:/app -w /app node:20.15.0 npm run type-check
```

**Comment by DrWarpMan** [comment]
I tried it with older Bun versions down to 1.1.5 and the behavior is the same.
I have also tried it on Arch Linux host, Debian host, and within Debian docker container host.

I did some testing, and found out that _**this problem occurs only when Node is not installed**_ on the system. That is why you are not getting the error on your host machine, cause you have Node installed.

Try installing Node in that container and suddenly `bun run build` will work as expected.
Steps to reproduce via Docker:
1. Create a blank Debian container and exec into it:
```bash
docker run -d --name bun-test debian:bookworm-slim /bin/sh -c "tail -f /dev/null"
docker exec -it bun-test bash
```
2. Install dependencies:
```bash
apt update && apt install unzip curl -y
```
3. Install Bun:
```bash
curl -fsSL https://bun.sh/install | bash
source /root/.bashrc
```
5. Create new Vue project, choose **YES** for TypeScript and **NO** for everything else:
```bash
bun create vue@latest
cd vue-project
bun install
```
6. Try to build with Bun, it will fail with a TypeScript error:
```bash
bun run build
```
_Output:_
```
root@58dd56fd73a4:/vue-project# bun run build
$ run-p type-check "build-only {@}" --
$ vite build
$ vue-tsc --build --force
vite v5.3.3 building for production...
✓ 26 modules transformed.
dist/index.html                  0.43 kB │ gzip:  0.28 kB
dist/assets/index-DdiqUGQG.css   3.71 kB │ gzip:  1.19 kB
dist/assets/index-Cm4-ybsi.js   64.16 kB │ gzip: 25.42 kB
✓ built in 843ms
src/main.ts:4:17 - error TS2307: Cannot find module './App.vue' or its corresponding type declarations.

4 import App from './App.vue'
                  ~~~~~~~~~~~

Found 1 error.

ERROR: "type-check" exited with 2.
error: script "build" exited with code 1
```
7. Now install Node:
```
apt install nodejs -y
```
8. Building with Bun should now work without any error:
```bash
bun run build
```
_Output:_
```
root@58dd56fd73a4:/vue-project# bun run build
$ run-p type-check "build-only {@}" --
$ vue-tsc --build --force
$ vite build
vite v5.3.3 building for production...
✓ 26 modules transformed.
dist/index.html                  0.43 kB │ gzip:  0.29 kB
dist/assets/index-DdiqUGQG.css   3.71 kB │ gzip:  1.19 kB
dist/assets/index-CAjzAup_.js   64.16 kB │ gzip: 25.42 kB
✓ built in 1.01s
```
And as soon as you remove Node via `apt remove nodejs`, Bun won't be able to build again.

**Comment by andyexeter** [comment]
@DrWarpMan nice detective work! 

I've tried all the way down to Bun v0.5.0 and the issue persists so it doesn't seem to be a regression, just something that's never worked.

Very odd that it works with nodejs installed...I wonder if it's actually one of Node's dependencies being installed which fixes it. Running `apt-cache depends nodejs` shows the following:

```
nodejs
  Depends: libc6
  Depends: libgcc1
    libgcc-s1
  Depends: libstdc++6
  Depends: python3
  Depends: ca-certificates
```

When I get some time I'll try installing those on their own one by one to see if any fix the issue.

**Comment by andyexeter** [comment]
Closing as a duplicate of https://github.com/oven-sh/bun/issues/4754 (https://github.com/vuejs/language-tools/issues/4082)
