### ISSUE TITLE
`raiseIgnoringPanicHandler` triggers crash reporter

### ISSUE THREAD

**Issue by sparanoid** [oven-sh/bun#12169]
### How can we reproduce the crash?

My program connects to WebSocket connections and saving events to a PostgreSQL db with Drizzle ORM. The code is not opensourced at the moment.

### Relevant log output

```shell
Application exited with code 132
error: script "start" was terminated by signal SIGKILL (Forced quit)
============================================================
Bun v1.1.13 (bd6a6051) Linux x64 (baseline)
Args: "bun" "run" "start"
Features: spawn 
Elapsed: 15428549ms | User: 7ms | Sys: 19ms
RSS: 1.07GB | Peak: 12.32MB | Commit: 1.07GB | Faults: 188
panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
 https://bun.report/1.1.13/Br1bd6a605AggggI+1mOwxji5C6vj35C43q35Ci7+m0Cg9vm0CA2AA
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- `??`
- [`Global.zig:128`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/Global.zig#L128>): `src.Global.raiseIgnoringPanicHandler__anon_86500`
- [`run_command.zig:407`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli/run_command.zig#L407>): `src.cli.run_command.RunCommand.runPackageScriptForeground`
- [`run_command.zig:1461`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli/run_command.zig#L1461>): `src.cli.run_command.RunCommand.exec__anon_272747`
- [`cli.zig:1772`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/cli.zig#L1772>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/main.zig#L50>): `main`

Edited: Still got this error with v1.1.17:

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- `??`
- [`Global.zig:128`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/Global.zig#L128>): `src.Global.raiseIgnoringPanicHandler__anon_68457`
- [`run_command.zig:407`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli/run_command.zig#L407>): `src.cli.run_command.RunCommand.runPackageScriptForeground`
- [`run_command.zig:1461`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli/run_command.zig#L1461>): `src.cli.run_command.RunCommand.exec__anon_71499`
- [`cli.zig:1801`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli.zig#L1801>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/main.zig#L50>): `main`

**Comment by paperdave** [comment]
> Application exited with code 132
> error: script "start" was terminated by signal SIGKILL (Forced quit)

the "start" script was killed. this is a bug in that script (if it is running bug and crashing, it is a bug in bun). SIGKILL can also be an out of memory or timeout

the fact bun crashes in `raiseIgnoringPanicHandler`, which is supposed to forward the script's crash to the shell, and hitting the panic handler, is a bug in bun.

**Comment by sparanoid** [comment]
I'm running it on Koyeb within a container. The memory usage seems to be fine:

<img width="607" alt="image" src="https://github.com/oven-sh/bun/assets/96356/50a05055-b420-4073-88c6-a619145984ac">

The gap in the chart is when the service dies

**Comment by yard2010** [comment]
I'm having this issue as well, even with the last version of bun, any idea how can I workaround it?

**Comment by jessym** [comment]
I ran into the same error `error: script "start" was terminated by signal SIGKILL (Forced quit)` and managed to fix it by increasing the available memory of the Docker container running my bun process from 128 to 256 MB.

**Comment by tushar1998** [comment]
I was running bun supabase:start command spins up local supabase `supabase start` but bun or supabase was taking too much time to start so I killed the process by ctrl + c and then tried it again and then I am facing this error

```
➜ bun supabase:start
$ bunx supabase start
error: script "supabase:start" was terminated by signal SIGKILL (Forced quit)
[1]    46162 killed     bun supabase:start
```

Update: bun pm cache rm worked for me
