### ISSUE TITLE
GRPC Not working

### ISSUE THREAD

**Issue by YZYLAB** [oven-sh/bun#12174]
### What version of Bun is running?

1.1.17

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Using Yellowstone GRPC library from triton. Returning Z_DATA_ERR and Z_BUF_ERR after 1 second of running, does receive events before that. 

Uncaught exception: 2486 |       if (opts.dictionary) {
2487 |         if (!Buffer2.isBuffer(opts.dictionary))
2488 |           throw new Error("Invalid dictionary: it should be a Buffer instance");
2489 |       }
2490 |       this._handle = new binding.Zlib(mode);
2491 |       this._hadError = !1, this._handle.onerror = function(message, errno) {
                                                                 ^
error: unexpected end of file
 errno: -5
  code: "Z_BUF_ERROR"

      at node:zlib:2491:59
      at node:zlib:2234:40
      at node:zlib:2209:45
      at node:zlib:2228:40
      at node:zlib:2155:39

**Comment by nektro** [comment]
should be fixed by https://github.com/oven-sh/bun/pull/14079. will be available in the next canary/1.1.30. if the issue still persists after uprgading please let us know
