### ISSUE TITLE
Bun still ask for Github credential when SSH key is set up

### ISSUE THREAD

**Issue by Paper-Folding** [oven-sh/bun#12172]
### What version of Bun is running?

1.1.17

### What platform is your computer?

Windows

### What steps can reproduce the bug?

1. Add ssh+git as a dependency, for example:  
```
"my-lib": "git+ssh://git@github.com/My-Namespace/my-lib.git#1.0.0"
```
2. Note that SSH key has been generated and add to git locally, i.e., these command is being executed before:  
```sh
git config --global gpg.format ssh
git config --global user.signingkey "C:\Users\[my-username]\.ssh\id_ed25519.pub"
```
4. Run `bun install`  
5. A "Connect to Github" dialog will appear first:  
![image](https://github.com/oven-sh/bun/assets/49343539/f68bb5b3-526f-4fc4-8b30-b2f6db942940)
6. Close the dialog manually and "The string binding is invalid" error dialog will show:   
![image](https://github.com/oven-sh/bun/assets/49343539/97465bfc-9be0-475c-9838-7d42c406ce45)
7. Close the error dialog again and I'm using vscode, vscode will ask me for password, so I skip with esc key  
8. Finally, bun will install the dependency successfully via SSH key.

The problem is, the dialog in step 5 and 6 should not appear. When I'm using yarn before, this issue does not exists.

### What is the expected behavior?

 The dialog in step 5 and 6 above should not appear, Bun should check for SSH key first before asking for github credential.

**Comment by rluba** [comment]
I just encountered a similar issue with a private GitLab instance:
I have a  `git+ssh://git@<server>/<repo>#v2.1.0` dependency and `bun install` shows a `Password for https://git@<server>` prompt – for a split-second, before it gets overwritten by other console status updates.

That the prompt gets deleted makes the issue more difficult to diagnose because then the process just hangs and you don’t know why. You can only detect it due to the still-visible trailing key symbol on the macOS terminal:
<img width="212" alt="missing password prompt" src="https://github.com/user-attachments/assets/c2abf2c8-cf1f-47f2-aab4-5e04acaeffe2">

The password prompt gives a hint to the underlying issue: the dependency is configured as `git+ssh`, but bun nonetheless tries to access it via `https`!

**Comment by Paper-Folding** [comment]
> I just encountered the same issue, but with a private GitLab instance: I have a `git+ssh://git@<server>/<repo>#v2.1.0` dependency and `bun install` shows a `Password for https://git@<server>` prompt – for a split-second, before it gets overwritten by other console status updates.
> 
> That the prompt gets deleted makes the issue more difficult to diagnose because then the process just hangs and you don’t know why. You can only detect it due to the still-visible trailing key symbol on the macOS terminal: <img alt="missing password prompt" width="212" src="https://private-user-images.githubusercontent.com/4600573/360853419-c2abf2c8-cf1f-47f2-aab4-5e04acaeffe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDcxMTksIm5iZiI6MTcyNDQwNjgxOSwicGF0aCI6Ii80NjAwNTczLzM2MDg1MzQxOS1jMmFiZjJjOC1jZjFmLTQ3ZjItYWFiNC01ZTA0YWNhZWZmZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDk1MzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY2MGIxNGVlMmU2NDg1YjRmZTFhNjYzYTkwZDNjZTY2NzQ1N2ZhMGYzMTJkMjZjYmQ0MmE3MGM0NjM5MDkxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rzxTYE3awAvOBD6063R7bliPFEL-SaDsgD_fPZxJcMk">
> 
> The password prompt hints at the underlying issue: the dependency is configured as `git+ssh`, but bun nonetheless tries to access it via `https`!

The problem is, I have already set up **git** properly after that the bun stills ask me for credentials.

**Comment by rluba** [comment]
Never mind. The issue I mentioned is actually fixed with the latest bun version. (I was running a slightly outdated version.)
