### ISSUE TITLE
Illegal Instruction error when running most of the bun commands on an aarch64 hardware

### ISSUE THREAD

**Issue by iPigTW** [oven-sh/bun#12173]
### How can we reproduce the crash?

1.Install bun using official script on a orange pi zero3 (aarch64) running dietpiOS(Debian)
2.Run bun install/run

### Stack Trace (bun.report)

Illegal Instruction

**Comment by Jarred-Sumner** [comment]
Duplicate of #12076

**Comment by Jarred-Sumner** [comment]
We are tracking this in #12076, please follow along there
