### ISSUE TITLE
Bun.spawn guide incorrect function call

### ISSUE THREAD

**Issue by lachlanmcmillan** [oven-sh/bun#12188]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The example of using Bun.spawn on the bun.sh website throws a TypeError when trying to run.

```typescript
const proc = Bun.spawn("echo", ["Hello, world!"], {
  cwd: "/tmp",
  env: { FOO: "bar" },
  onExit(proc, exitCode, signalCode, error) {
    // exit handler
  },
});
```

```
TypeError: cmd must be an array
 code: "ERR_INVALID_ARG_TYPE"
```

Screenshot below is of my terminal when trying to execute this code.

<img width="511" alt="image" src="https://github.com/oven-sh/bun/assets/23187474/3b69abeb-3657-4446-9e52-5cb45f7992e0">

The correct call to `Bun.spawn` should be `Bun.spawn(["echo", "Hello, world!"], {`

### Where did you find it?

https://bun.sh/guides/process/spawn
https://github.com/oven-sh/bun/blob/main/docs/guides/process/spawn.md

**Comment by Jarred-Sumner** [comment]
embarassing
