### ISSUE TITLE
http.Server.listen(undefined) uses 3000

### ISSUE THREAD

**Issue by adraffy** [oven-sh/bun#12182]
### What version of Bun is running?

1.1.12

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

```js
import {createServer} from 'http';
let h = createServer(() => {});
h.listen(undefined, () => {
	console.log(h.address());
});
```

### What is the expected behavior?

random open port

### What do you see instead?

port 3000

**Comment by paperdave** [comment]
location of bug: `src/js/node/http.ts` line 529. node:http uses bun.serve and it defaults to port 3000 instead of random.

<img width="818" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/d237a4e4-605a-4f50-81c8-6ae2ce44fbef">
