### ISSUE TITLE
Support `aarch64` release on Docker

### ISSUE THREAD

**Issue by dinojs** [oven-sh/bun#1219]
### Version

0.1.11

### Platform

Darwin MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

The ```Dockerfile```:
```
FROM jarredsumner/bun:edge
WORKDIR /app
COPY . .
RUN bun install
EXPOSE 3000
ENTRYPOINT ["bun", "src/index.ts"]
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Successfully creating the Docker image. Tested on my MacOS Intel machine, and it worked
![image](https://user-images.githubusercontent.com/22294355/189231475-0c10fb91-bdd1-497d-b78d-6039c6f7fc97.png)

### What do you see instead?

```
#8 [4/4] RUN bun install
#8 0.214 qemu: uncaught target signal 4 (Illegal instruction) - core dumped
```

### Additional information

It would be great if we had an official Docker Image for M1 devices, as by looking online, loads of other people are facing the same issue.

**Comment by DarthBenro008** [comment]
Hey there!

I ended up making my own image which you can find on dockerhub here: 
https://hub.docker.com/repository/docker/darthbenro008/bun

The relevant `Dockerfile` can be found on my fork here:
https://github.com/DarthBenro008/bun/blob/dockerhub/aarch64/dockerhub/aarch64/Dockerfile

🚨**DISCLAIMER**

- Use this workaround until there is an official launch of bun for `aarch64`, I had created this workaround for my personal use-case (would love to send a PR for the same tho)
- The above image uses `debian:slim` instead of `alpine` due to `glibc` incompatiability for aarch64 in alpine base images

**Comment by matteocodogno** [comment]
@DarthBenro008 when I tried to run your docker image I obtained the following error: `executor failed running [/bin/sh -c bun --version]: exit code: 127`. Did I miss something?

**Comment by DarthBenro008** [comment]
@matteocodogno can you share the `Dockerfile` or the error logs?

The below Dockerfile:
```dockerfile
FROM darthbenro008/bun
ENTRYPOINT ["bun", "--version"]
```

Works just fine:

![image](https://user-images.githubusercontent.com/31009634/194270055-7cebb6fe-d8b3-426d-9448-a216c3b86625.png)

Note: the docker image is only for ARM (M1 Processor) architecture

**Comment by matteocodogno** [comment]
@DarthBenro008 using your docker file it works like a charm.
I was trying to replicate your Dockerfile:

```Dockerfile
FROM alpine:latest as builder

WORKDIR /tmp
RUN apk --no-cache add unzip

ADD https://github.com/oven-sh/bun/releases/latest/download/bun-linux-aarch64.zip bun-linux-aarch64.zip
RUN unzip bun-linux-aarch64.zip


FROM debian:bookworm-slim

COPY --from=builder /tmp/bun-linux-aarch64/bun /usr/local/bin

RUN /usr/local/bin/bun --version
```

And I obtained the above error.

**Comment by Electroid** [comment]
You can now use `FROM oven/bun`, which has [support](https://hub.docker.com/r/oven/bun/tags) for `aarch64` and `x64`.
