### ISSUE TITLE
Single Flight server actions - SolidStart (notes example)

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#12191]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Create project:
- bun create solid@latest
- Is this a Solid-Start project? **Yes**
- Which template would you like to use? **Notes**
-  Use Typescript? **Yes**

Run:
- bun i
- bun --bun run dev
- Go to http://localhost:3000/
- Click "New"
- Fill in "Title" and "Description"
- Click "Done"

### What is the expected behavior?

New note is saved

### What do you see instead?

Internal server error in browser console

Terminal shows:

```zig
➜ bun --bun run dev
$ vinxi dev
vinxi v0.3.12
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

8:48:05 AM [vite] ✨ new dependencies optimized: marked
8:48:05 AM [vite] ✨ optimized dependencies changed. reloading
[h3] [unhandled] 1 | export default "native";
    ^
error: Unexpected end of JSON input
      at json (native:1:1)

1 | export default "native";
    ^
SyntaxError: Unexpected end of JSON input
      at json (native:1:1)
```

**Comment by paulo-assoc** [comment]
@birkskyum It worked for you?

**Comment by birkskyum** [comment]
> @birkskyum It worked for you?

Yes

**Comment by paulo-assoc** [comment]
@birkskyum I deleted the .data folder and therefore the old notes. It still crashes like originally when saving the first (and subsequent) new note.

**Comment by birkskyum** [comment]
@paulo-assoc , did you try making a new repo with "bun create solid"?

**Comment by paulo-assoc** [comment]
@birkskyum I tried it with an update of an existing repo and with a new repo using "bun create solid". Either way it crashes with bun 1.1.18 on Windows.

bun run --bun dev
$ vinxi dev --port 3004
vinxi v0.3.14
vinxi starting dev server

  ➜ Local:    http://localhost:3004/
  ➜ Network:  use --host to expose

[h3] [unhandled] 1 | export default "native";
    ^
error: Unexpected end of JSON input
      at json (native:1:1)

1 | export default "native";
    ^
SyntaxError: Unexpected end of JSON input
      at json (native:1:1)

**Comment by paulo-assoc** [comment]
@birkskyum You must have an update I don't have. Thoughts?

**Comment by birkskyum** [comment]
@paulo-assoc , I don't know why it seemed like it worked briefly... must be a fluke, or there could be a race condition.

**Comment by paulo-assoc** [comment]
Thanks, @birkskyum! I want you to know that I appreciate you.

**Comment by paulo-assoc** [comment]
Any updates, @birkskyum?

**Comment by birkskyum** [comment]
@paulo-assoc , not that I'm aware of. [This is](https://x.com/jarredsumner/status/1814475975708889186) what's being worked on rn, so some highly requested features. The merger of the node:cluster appear to be [in progress](https://github.com/oven-sh/bun/pull/11492), so hopefully there will be more room for "niche" bugs like this when the top tickets are ironed out.

**Comment by paulo-assoc** [comment]
Thanks for the update, @birkskyum!

**Comment by birkskyum** [comment]
@paulo-assoc , with the new Bun 1.1.27, I believe this is working.

Can you verify?

**Comment by paulo-assoc** [comment]
Wow! I tested the SolidStart notes app with Bun 1.1.27 on Windows 11 and found no issues. Thanks, @birkskyum!

**Comment by paulo-assoc** [comment]
@birkskyum Does this mean we can safely use solid start with Bun? Or are there other known issues?

**Comment by birkskyum** [comment]
SolidStart appear to be well supported now. There are some auth packages / https/http2 areas that aren't in place yet, as noted [here](https://github.com/oven-sh/bun/issues/3736#issuecomment-2193934709), but thats the same issues for everyone, i.e. sveltekit [here](https://github.com/oven-sh/bun/issues/7560), and I think the [crypto rewrite](https://github.com/oven-sh/bun/issues/13681) is what will ultimately will unlock these tickets - so there's nothing solidstart-specific left to my knowledge.

**Comment by paulo-assoc** [comment]
@birkskyum I didn't see any mention of this big news in the release notes for Bun 1.1.27.

**Comment by birkskyum** [comment]
@paulo-assoc , i'm not sure, but I think this might have been resolved as part of
- https://github.com/oven-sh/bun/pull/13744
