### ISSUE TITLE
How to manage multiple packages with a custom scope

### ISSUE THREAD

**Issue by mountEvarus** [oven-sh/bun#12192]
### What is the type of issue?

Documentation is missing

### What is the issue?

I have the following config:

```
[install]
exact = true
[install.scopes."@foo"]
url = "https://foo.codeartifact.region.amazonaws.com/npm/bar/"
token = "$TOKEN"
```

This works great for using a package @foo/bar, but when trying to install @foo/baz, it returns an unauthorized error for the new package. They share a token and install scope, but their urls differ. How can I account for this in the config?

**Comment by Jarred-Sumner** [comment]
hm, it shouldn't return an unauthorized error if they both have the same scope

what version of bun is this on?

**Comment by mountEvarus** [comment]
> hm, it shouldn't return an unauthorized error if they both have the same scope
> 
> what version of bun is this on?

I have tried this on several version of bun, but the latest is v1.1.17

From what I can see, I define the scope as:

[install.scopes."@stellar-fusion"]
url = "https://stellarfusion-170140544096.d.codeartifact.eu-west-1.amazonaws.com/npm/data-query/"
token = "$TOKEN"

```
[install]
exact = true
[install.scopes."@foo"]
url = "https://foo.codeartifact.region.amazonaws.com/npm/bar/"
token = "$TOKEN"
```

Then when attempting to get @foo/baz, it reaches out to https://foo.codeartifact.region.amazonaws.com/npm/bar/@stellar-fusion%2fbaz

It seems to tightly tie a scope to a single url, whereas I would require multiple urls (one for each package) in a single scope

**Comment by mountEvarus** [comment]
I have tried this on several version of bun, but the latest is v1.1.17

From what I can see, I define the scope as:

[install]
exact = true
[install.scopes."@foo"]
url = "https://foo.codeartifact.region.amazonaws.com/npm/bar/"
token = "$TOKEN"
Then when attempting to get @foo/baz, it reaches out to https://foo.codeartifact.region.amazonaws.com/npm/bar/@foo%2fbaz

It seems to tightly tie a scope to a single url, whereas I would require multiple urls (one for each package) in a single scope
