### ISSUE TITLE
Bun will not run correctly in child processes

### ISSUE THREAD

**Issue by akirarika** [oven-sh/bun#12222]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Repo: https://github.com/akirarika/wF0nK6cB6wJ6mH3u

When I write my package.json in this way and run `bun run command`, bun does not actually execute the command.

<img width="567" alt="image" src="https://github.com/oven-sh/bun/assets/33272184/ef8eb189-186f-4211-b9af-e25a2cd27e36">
<img width="439" alt="image" src="https://github.com/oven-sh/bun/assets/33272184/aab7e830-dfab-40b9-9132-d5e48d9819ce">

However, when I run `bun run ./run-command.ts` directly, everything works fine:
<img width="464" alt="image" src="https://github.com/oven-sh/bun/assets/33272184/754b7855-0464-4429-b4a7-2e8952c3f96d">

When bun runs in a subprocess, it always stops unexpectedly without outputting any content, and I can't locate the reason. Until I realized that some of the small tools I had written, like https://github.com/akirarika/co, were no longer working with Bun (they were effective in older versions), I also found that even running Bun itself could cause such problems.

**Comment by paperdave** [comment]
<img width="326" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/fc4b0cfb-639a-4775-aa54-fe0dae2ff45b">

I cannot reproduce this on `Darwin 23.5.0 arm64` kernel (M2 Macbook)

**Comment by akirarika** [comment]
Yesterday, I tried to get my friend to give it another try, and I discovered that the issue seemed to be unique to me. After reinstalling Bun (not `bun upgrade`), the problem disappeared

This might be due to my own reasons

**Comment by hugo082** [comment]
Actually I have the same issue, I tried to re-install via curl & homebrew but it didn't work.
```
•  Architecture: ARM64 (Apple Silicon - M2)
•  OS: macOS 15.4.1
•  Kernel: Darwin 24.4.0
•  Bun revision: 1.2.13+64ed68c9e
```

**Comment by akirarika** [comment]
@hugo082 This issue has been closed. Creating a new one should be able to draw the official's attention to the problem you encountered. In fact, I also encountered some similar problems in scenarios of multiple shell nesting later, but I didn't bring them up
