### ISSUE TITLE
`bun build` output diff from local machine and ci

### ISSUE THREAD

**Issue by afonsojramos** [oven-sh/bun#12230]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

<img width="754" alt="image" src="https://github.com/oven-sh/bun/assets/19473034/16812269-f895-49a6-b998-a90a33a25687">

When running bun's bundler using `bun build src/index.ts --target=node --outfile=dist/index.js` the output from the CI differs from the local output by these two lines.

The CI is GitHub's `ubuntu-latest`

It's hard for me to get a reproducible environment, but if it is REALLY needed I can try to mess around.

### What is the expected behavior?

Output is consistent across the two environments.

> Note: Love bun and what you are doing with the platform, keep it up!

**Comment by Jarred-Sumner** [comment]
The hoisting is different, which causes the node_modules folder to have different paths which causes the file paths printed in the comment to be different

Is the same npm client used for both local and release? Is the CI environment installing with  `--no-production` or `--frozen-lockfile`?

You can omit the file paths for these if you pass `--minify` or `--minify-whitespace`.

**Comment by Jarred-Sumner** [comment]
The above is an answer - please let us know if you’re still running into issues with this

**Comment by afonsojramos** [comment]
In this case we were actually producing both a minified and non minified output, but I suppose we don't need both either way so, that solves the issue, sorry for wasting your valuable time and hope this helps someone else!
