### ISSUE TITLE
Request: `outdated` CLI command

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#1223]
### What is the problem this feature will solve?

Currently there is no way to view outdated packages in a project like one can with NPM's CLI.

### What is the feature you are proposing to solve the problem?

A new command has to be implemented that would show a similar result (perhaps better formatted) that shows any out dated packages within a project.

### What alternatives have you considered?

N/A

**Comment by jakeboone02** [comment]
As an additional request, something like Yarn v2's [`upgrade-interactive` plugin](https://www.npmjs.com/package/@yarnpkg/plugin-interactive-tools) would be really nice.

![image](https://user-images.githubusercontent.com/366438/230443633-e8d15602-03fc-492e-97b8-e227421fcf75.png)

**Comment by jack-weilage** [comment]
Bumping this issue to ask: Is this feature being considered/worked on? This and #1372 are basically the only reasons that I haven't adopted `bun` for anything besides task running.

**Comment by kenbanks-peng** [comment]
My mitigation for the missing `bun pm outdated` CLI is to use [ncu](https://github.com/raineorshine/npm-check-updates), which just focuses on maintenance of package versions within package.json. 

```
ncu
ncu -u or ncu -u <package>
bun install
```

**Comment by ImBIOS** [comment]
Currently I'm using this script:

```package.json
...
"deps:update": "npx npm-check-updates --interactive --format group"
...
```

When I run it using `bun run deps:update`:

```js
 ➜  bun run deps:update 
$ bun x npm-check-updates --interactive --format group
```

It'll auto-convert `npx` to `bun x`, pretty awesome! but `ncu` is using normal npm under the hood 🤣

**Comment by ImBIOS** [comment]
For fastest implementation, I made a PR in ncu:

- https://github.com/raineorshine/npm-check-updates/pull/1309

At the moment, it's not support bun yet for installation after dependency update. That's the main point of my PR.

**Comment by Jarred-Sumner** [comment]
Bun v0.7.4 gets `bun update` which does this

You can use it to update all your dependencies via:
```bash
bun update
```

or you can update just a single dependency via
```bash
bun update <my-package-name>
```

Thanks to @alexlamsl #4046

**Comment by Jarred-Sumner** [comment]
I guess this is technically "do the update" instead of "check for updates", but I wonder if that's fine?

**Comment by jack-weilage** [comment]
In my opinion, this is still a valuable issue and shouldn't be closed. `bun outdated` meets a different need than `bun update`, so it shouldn't be bundled like this. Maybe a flag like `bun update --dry` if you don't want to add more subcommands?

**Comment by Jarred-Sumner** [comment]
There is bun update --dry-run but it does the wrong thing right now (it prints out every version of instead of only changes, which is nonsensical)

I think we should do `bun pm outdated`

**Comment by jack-weilage** [comment]
`bun pm outdated` sounds good, but I feel that the `pm` subcommand confuses things. Why are `update`/`add`/`remove` the same as `npm`, but `outdated` goes under `pm`?

**Comment by jakeboone02** [comment]
Agree with @jack-weilage—this should not be closed yet. `bun outdated` should show the actual installed versions per the lock file, the latest versions that match the respective semver strings in package.json, and the absolute latest versions. It would be primarily informational but could be interactive.

Sounds like `bun update <package>` will just bump it to the latest semver-matching version.

**Comment by Jarred-Sumner** [comment]
sounds good, we'll do `bun outdated` and leave `bun pm` namespace for the more obscure commands that potentially conflict with script names

**Comment by kenbanks-peng** [comment]
'ls' is used for 'list', ok, a little off-beat from npm but makes sense. But I see it only available using `bun pm ls`. Any hope of moving this to `bun ls`?

**Comment by saturnonearth** [comment]
pnpm's `pnpm up -L -i` is something I can't live without. It lists all packages and shows which ones are outdated, regardless of semvar verisons in package.json, and allows you to choose which ones to update - then, once chosen, updates the packages accordingly and updates the package.json file.

This is _needed_

**Comment by oedotme** [comment]
@saturnonearth This command is so underrated!

I've been using `--recursive` with it as well, to list and update all packages from all (monorepo) workspaces: 

```shell
pnpm update --latest --interactive --recursive
```

Would be great to have something similar in Bun! ❤️

**Comment by azat-io** [comment]
+1 for `bun update --interactive`

**Comment by ImBIOS** [comment]
> For fastest implementation, I made a PR in ncu:
> 
> * [feat: bun as packageManager option raineorshine/npm-check-updates#1309](https://github.com/raineorshine/npm-check-updates/pull/1309)
> 
> At the moment, it's not support bun yet for installation after dependency update. That's the main point of my PR.

Just to notify, everyone who waiting for this. It's merged in `ncu`, it's enough for temporary solution.

**Comment by danielbarion** [comment]
it would be nice to have something like this package natively on bun:

https://www.npmjs.com/package/npm-check

**Comment by wJoenn** [comment]
Hello there, just saying but I really second having an interactive CLI interface for outdated packages like yarn's `yarn upgrade-interactive --latest`
![image](https://github.com/oven-sh/bun/assets/75388869/b0c0f29c-ae00-4558-a304-9ade21975859)

Compared to a more simple statement of outdated packages like `npm outdated`
![image](https://github.com/oven-sh/bun/assets/75388869/318b3c78-8d28-4b74-b768-c95ca6588b47)

Being able to both check versions and hand pick those we want to update with a single command is such a pleasant DX utility.
The caviar would be a link to the actual changelogs though I have no idea whether that's dealt by the package manager or the package itself

**Comment by deadcoder0904** [comment]
i use 2 commands with `pnpm` as bun isn't available directly on windows without wsl:

`pnpm outdated` & `pnpm update --latest`

i would love to have this in bun so i can fully replace `pnpm` with `bun` otherwise i have to find a workaround for this using `ncu` which i used to use previously before i learned about the respective `pnpm` commands.

definitely a must-have for me.

**Comment by bkniffler** [comment]
Seems like someone added a tool based on npm-check: https://www.npmjs.com/package/npm-check-bun

```
bunx run npm-check-bun -u
```

(I'm not affiliated with the author, found it randomly)

would love to see this built-in though, but looks like a good intermediate solution

**Comment by bkniffler** [comment]
Found another alternative FYI in case you use `workspace:*`: https://www.npmjs.com/package/npm-check-updates#npm-check-updates

```
npx npm-check-updates -ws --root --format group -i
```

Works good with workspaces and has an interactive mode.

**Comment by nijikon** [comment]
@Jarred-Sumner is there any plan to implement this?

**Comment by itsjavi** [comment]
I use `pnpm update --latest` to upgrade all deps in my `package.json`, then I clean up node_modules and run `bun install`.

I don't know if there is a cleaner way to do this, but `bun update -f` isn't updating the package.json, and I am not sure why we need `bun outdated` instead of `bun update --outdated`, I'd rather have readable explicit behavior.

**Comment by silvenon** [comment]
> I am not sure why we need `bun outdated` instead of `bun update --outdated`, I'd rather have readable explicit behavior.

Because `outdated` is a command we're very much used to from npm and yarn. The two command you specified sound different to me, what would the latter one do? It sounds like it updates outdated dependencies, which is what `bun update` already does anyway.

And what is the relation between that and the pnpm example you specify?

**Comment by itsjavi** [comment]
@silvenon that's right. I guess I got confused (lack of sleep :D). What I tried to say is that it seems there is no way to update the package.json after the dependencies have been updated. Unless I am missing something. But I think this is not the right issue to discuss this.

**Comment by silvenon** [comment]
Yep, that issue is frustrating for me too, you can track #4312 for that.

**Comment by toniengelhardt** [comment]
This is really the one thing stopping me from trying bun for package management...

**Comment by nahoc** [comment]
> This is really the one thing stopping me from trying bun for package management...

It really shouldn't be -- like others mentionned, just do
```json
  "scripts": {
    "update-deps": "bunx npm-check-updates --root --format group -i"
  }
```

And you're good.

**Comment by wottpal** [comment]
Still `bun` should have a native interactive updater. This is one of the best things about `pnpm` that this things works so smoothly out of the box.

**Comment by fungilation** [comment]
Ya I moved all my projects over to pnpm now. It got performance (not as blazing fast as bun but next best) and it got useful management cmds like outdated, up interactive 

Would love to have bun as the 0 compromise package manager and runtime

**Comment by sillvva** [comment]
Only reason I haven't switched from pnpm is lack of interactive updates

**Comment by barziahmed** [comment]
1+ 

Please deliver "bun outdated" command, same as "pnpm outdated".

**Comment by deadcoder0904** [comment]
now that windows is out, would love `bun outdated` & `bun up --latest` command to update it to latest dependencies.

for reference, check out how pnpm does it. its the only thing i do daily with pnpm.

**Comment by Scc33** [comment]
> > This is really the one thing stopping me from trying bun for package management...
> 
> It really shouldn't be -- like others mentionned, just do
> 
> ```json
>   "scripts": {
>     "update-deps": "bunx npm-check-updates --root --format group -i"
>   }
> ```
> 
> And you're good.

Thanks for sharing. This is awesome. Since bun is supposed to be all-in-one it would be great if native support is still added.

**Comment by KieranP** [comment]
Facing the same issue as others. Bun runs my Typescript project just fine, but lack of `bun outdated` is holding me back from switching from NodeJS/PNPM to just Bun. Once `bun outdated` is implemented, this will fill the remaining gap.

**Comment by Blankeos** [comment]
Confirmed `npm-check-updates` works (as a work-around), hopefully Bun's own implementation would be faster.

```sh
bunx npm-check-updates
```
<img width="500" alt="image" src="https://github.com/oven-sh/bun/assets/38070918/eeecbb52-c0a2-491b-806f-4d08efcefef6">

**Comment by RubyDorian** [comment]
voting this up. really needed feature. I don't want to update dependencies if I can't see what's outdated

**Comment by felixranesberger** [comment]
For the moment you could simply create a terminal alias for `bunx npm-check-updates` called `bun outdated`. You would have to make sure to remove it, when this feature is available in bun directly, so calling it something else would probably be better.

**Comment by Araxeus** [comment]
> For the moment you could simply create a terminal alias for `bunx npm-check-updates` called `bun outdated`. You would have to make sure to remove it, when this feature is available in bun directly, so calling it something else would probably be better.

![image](https://github.com/oven-sh/bun/assets/78568641/81d16475-f43f-44ae-9574-7c7018bbad70)

btw for global install you can run
```Hosts File
bunx npm-check-updates -p bun --cwd $USERPROFILE/.bun/install/global
```

**Comment by Dimava** [comment]
Another alternative is https://github.com/antfu-collective/taze 
`bunx taze -I -r` (`bunx taze --interactive --recursive`)

**Comment by lubuzzo** [comment]
+1 for bun outdated

**Comment by darklight9811** [comment]
+1 for bun outdated

**Comment by darklight9811** [comment]
if you try to run the command it shows its reserved, so they intend to do this feature and its already scoped, its just not the priority right now.

The taze alternative does cover this necessity for the time being

**Comment by ken717w** [comment]
Wondering why such a core feature of package management was not implemented in the first place, is there any story behind it?

**Comment by birkskyum** [comment]
Having tried taze for a bit, it feels like `update` and `update --latest` just are less intuitive ways of saying `minor` and `major`.

Also, it would be great to ignore pinned packages, because in a repo that uses a pre-release like `"convert-units": "3.0.0-beta.6"`, running `bun update --latest` will set it to `"2.3.4"`, and then I have to manually revert that one package... `interactive` mode could ofc. make it less problematic, because it then wouldn't be bumped in the first place.

**Comment by Jarred-Sumner** [comment]
This feature will be part of the Bun v1.1.26 release, thanks to @dylan-conway in https://github.com/oven-sh/bun/pull/13461

**Comment by gitblit** [comment]
I'm very happy to see a native `outdated` command! 🎉 But I really wish it supported workspaces (really important, imo) & interactivity (bonus/nth).
