### ISSUE TITLE
Bun crashing upon serving a Bun.file() inside a promise.

### ISSUE THREAD

**Issue by KissKonradUni** [oven-sh/bun#12249]
### How can we reproduce the crash?

Have an HTTP webserver.
Have a repsonse that uses Bun.file() inside a promise
Change the file while the app is running.
Refresh the page.

### Relevant log output

```shell
Bun v1.1.17 (bb66bba1) Windows x64
Args: "C:\ProgramData\chocolatey\lib\bun\tools\bun-windows-x64\bun.exe" "index.ts"
Features: jsc abort_signal dotenv http_server tsconfig 
Builtins: "bun:main" 
Elapsed: 168220ms | User: 109ms | Sys: 15ms
RSS: 0.14GB | Peak: 0.20GB | Commit: 0.21GB | Faults: 101931

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [RunCommand]

**panic**: Internal assertion failure

- [`debug.zig:443`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/deps/zig/lib/std/debug.zig#L443>): `panicExtra`
- [`bun.zig:3252`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.zig#L3252>): `assertionFailure`
- [`blob.zig:1706`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/webcore/blob.zig#L1706>): `sharedView`
- [`ReadFile.zig:756`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/webcore/blob/ReadFile.zig#L756>): `queueRead`
- `??`
- `fs__open`
- `uv_run`
- [`uws.zig:2819`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/deps/uws.zig#L2819>): `tickWithoutIdle`
- `JSC__JSValue__fastGet_`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`

**Comment by cirospaciari** [comment]
Fixed on https://github.com/oven-sh/bun/pull/12441
