### ISSUE TITLE
bun install fails for private SSH git repo that definitely exists

### ISSUE THREAD

**Issue by jonblatho** [oven-sh/bun#12257]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

1. Add a private SSH Git repository dependency in package.json, e.g. `"my_module": "git+ssh://my.gitlab.instance.com/path/to/repo.git#some-tag"`
2. Attempt `bun install`.
3. Change the dependency URL to `git+ssh://git@my.gitlab.instance.com/path/to/repo.git#some-tag`
4. Reattempt `bun install`

### What is the expected behavior?

Git repository should be cloned over SSH successfully.

### What do you see instead?

It depends.

If I do not include the username `git` in the dependency URL — it should be used anyway on that hostname, per my `~/.ssh/config` file — cloning the repository fails with the following message:
```
error: "git clone" for "my_module" failed

error: RepositoryNotFound cloning repository for my_module
```

If I add the username `git` into the URL as suggested in step 3 above, the package manager seems to hang. Here's about two minutes' worth of `bun install --verbose` output, which might be important with the variable number of `Resolving [1/1]` lines between lines that don't include that:
```
bun install v1.1.17 (bb66bba1)
Loaded 277 hoisted_dependencies
Loaded 511 resolutions
Loaded 511 dependencies
Loaded 0 extern_strings
Loaded 22452 string_bytes
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
[PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
```

I killed it manually because it shouldn't take that long to clone this rather small repo. I've been able to find workarounds generally for private Git repo issues, but I've yet to find one for this one.

### Additional information

The repository it's trying to load _definitely_ exists. Yarn and NPM are able to install the above without issue, and `git clone` for the repository over SSH works perfectly. Removing the tag portion of the URL doesn't help.

My `~/.ssh/config` file instructs SSH to use the user `git` with this hostname by default, e.g.:

```
Host my.gitlab.instance.com
  User git
```

so specifying `git@` in the URL shouldn't be necessary and _definitely_ shouldn't cause differing behavior.

**Comment by jonblatho** [comment]
Ahh, quick update — when I thought it was hanging, it wasn't. I was running this in the VS Code terminal and it was prompting me for an HTTP password. It's not being resolved as SSH.

**Comment by jonblatho** [comment]
@dylan-conway Is there any update on this? This is still occurring in Bun v1.1.26 (latest) and fully blocking us from continued work with Bun at this time. Happy to provide additional information if needed. To summarize:

* I get "RepositoryNotFound" errors for repositories that definitely exist when defined using this format: `git+ssh://my.gitlab.instance.com/path/to/repo.git#some-tag`
* SSH should be using the user `git` on `my.gitlab.instance.com` based on my SSH configuration. However, if I choose to explicitly specify the username in the package dependency, e.g. `git+ssh://git@my.gitlab.instance.com/path/to/repo.git#some-tag`, Bun attempts to clone the dependency using HTTPS, not SSH, despite beginning with `git+ssh://`.

Previously, I was able to work around `error: "git clone" for "my-dependency" failed` messages for our private dependencies by just running `bun install` again, which would usually succeed. That no longer works. All we get is `git clone failed` and `RepositoryNotFound`, the former of which is opaque and unhelpful, and the latter of which is flat out wrong.

More broadly, why have private SSH dependencies been so problematic for basically all of Bun's existence so far? It frankly leaves me with some significant concerns with using Bun in the long term. Our SSH configuration for our GitLab instance is extremely straightforward and "just works" with literally everything except Bun. But like I said, happy to provide additional information if it helps get us to a fix.

**Comment by jonblatho** [comment]
I'm now confident that when `git clone` is being run, for some reason it's not respecting my SSH config (at `~/.ssh/config`, the typical location) telling SSH to use the user `git` on `my.gitlab.instance.com`. As with GitHub, our GitLab instance requires that all users connect via SSH as `git`, not their own username.

I say this because I created a user on my computer named `git`, with SSH access to my account on `my.gitlab.instance.com`, and installed Bun for that user. Running `bun install` for a package.json containing one of our private repos as a dependency when using this `git` user worked on the first try.

I'm not able to tell for sure, but I assume that this means Bun is trying to run `git clone` using my computer username instead of `git` as specified in my SSH config. So, the issue here is that I'm completely unable (as far as I know) to use the user `git` when attempting to `git clone` from `my.gitlab.instance.com`, because:
1. My (very simple) SSH configuration is clearly not being respected for some reason, and
2. If I attempt to specify the user in the URL (by adding `git@` following `git+ssh://`), Bun attempts to resolve the package over HTTPS instead of SSH, despite my explicitly requesting the latter.

I'm at a loss for how to work around this until this is fixed, since again this is completely blocking us from continued work with Bun at the moment.

**Comment by jonblatho** [comment]
Since this isn't actually fixed (see #13620) can this be reopened?

**Comment by msanchezdev** [comment]
@Jarred-Sumner @jonblatho Can we get this reopnened? I am experience the same issue in Bun v1.2.5

**Comment by jonblatho** [comment]
@msanchezdev, to work around this issue in the meantime, I've been using Docker to build a custom image based on the [Bun image](https://hub.docker.com/r/oven/bun) that includes a `git` user and uses Docker's SSH agent forwarding to accomplish the install:

```Dockerfile
FROM oven/bun:1.2

RUN useradd git
```

Say you build and tag that image as `my_bun_installer`. Then run:
```bash
docker run --name my_memorable_container_name -v ${PWD}:/app -v ~/.ssh:/home/git/.ssh -w /app my_bun_installer bun install

docker cp my_memorable_container_name:/app/node_modules ./node_modules
docker cp my_memorable_container_name:/app/bun.lock ./bun.lock

docker rm my_memorable_container_name
```

It's not a 100% fix and you'll probably need to tweak a thing or two, but hope that helps to get you unstuck without needing to resort to using multiple package managers, which I also tried briefly. That's also a mess.

@dylan-conway @Jarred-Sumner It's frankly pretty silly that the above is **still** necessary as of Bun 1.2.10. If there is some way that we're all missing to properly install private git repo dependencies, then please fill us in and update your documentation. The suggested `package.json` [dependency URI formats](https://bun.sh/docs/cli/add#git-dependencies) do not work.

**Comment by felixdrp** [comment]
When trying to install a private repository with a custom user and port, it freezes...

bun add git+ssh://user@IP:9999/home/rp/git-server/package.git --trust
bun add v1.3.11 (af24e281)
  🔍 Resolving [1/1]
