### ISSUE TITLE
Implement WebMIDI

### ISSUE THREAD

**Issue by vexcited** [oven-sh/bun#1226]
### What is the problem this feature will solve?

Not being able to use MIDI in Bun.

### What is the feature you are proposing to solve the problem?

Implement WebMIDI API into Bun. There's libraries like PortMidi that could be a great starting point I think, though I didn't read the whole thing.

**Comment by Electroid** [comment]
Thanks for making this feature request! Unfortunately, I don't think we're going to implement this anytime soon. If possible, this would be a good candidate for a 3rd party package.

**Comment by mickmister** [comment]
I'm using a MIDI library in node called [node-midi](https://github.com/Julusian/node-midi/tree/master/src) which relies on the C++ library [rtmidi](https://github.com/thestk/rtmidi/tree/84a99422a3faf1ab417fe71c0903a48debb9376a) to work.

I also see there is a [zig-midi](https://github.com/Hejsil/zig-midi) library. @Electroid Could this hypothetically be integrated into Bun somehow, i.e. as a package as you mention? I would be interested in implementing this as a package.

**Comment by Electroid** [comment]
@mickmister Even with a Zig library, there doesn't seem to be enough demand for MIDI for us to consider adding it to Bun. If that ever changes, we would reconsider.

**Comment by thirtythreeforty** [comment]
How do we indicate interest? I would also use WebMIDI in Bun.

**Comment by mickmister** [comment]
How might one integrate this into bun?
