### ISSUE TITLE
error: No matching export in "node:buffer" for import "Buffer"

### ISSUE THREAD

**Issue by davidstevens37** [oven-sh/bun#12272]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

While using bun to run a typescript file that, imports the `Buffer` named export from the `node:buffer` module, the `Buffer` is imported. However, when using `bun build` on the same file: `error: No matching export in "node:buffer" for import "Buffer"`

**index.ts**
```typescript
import { Buffer } from "node:buffer";
console.log(Buffer);
```
---
**While trying to transpile:**
`> bun build index.ts`

```typescript
> bun build index.ts 
1 | import { Buffer } from "node:buffer";
             ^
error: No matching export in "node:buffer" for import "Buffer"
    at /Users/home/index.ts:1:10
```

--- 
**While executiong the TS directly:**
`> bun run index.ts`
```
[class Function]
```

**Comment by davidstevens37** [comment]
@CodingMarkus it wasn’t a bug, I just wasn’t including the right arguments to the build command. I’m not in front or my computer, but I think you need to include a target argument or something

**Comment by CodingMarkus** [comment]
But I'm seeing this issue with this Buffer implementation:

https://github.com/feross/buffer

And as the page says:

"The buffer module from node.js, **for the browser.**"

When running

```
bun add buffer
```

it downloads exactly this implementation and I can use it in TypeScript with

```
import { Buffer } from "buffer"
```

but I cannot use

```
bun build index.ts
```

As that yields exactly the same error.

Note that the same project has no issue when I install the package with `npm` and then bundle it with `tsc`.

**Comment by davidstevens37** [comment]
Hmm, I’m not sure. I wonder if it’s due to a difference in import precedence when the external  package name matches a built in package name.

Are you able to import using a relative path “./node_modules/path-to-package” instead of “buffer”?

Does tsc default to browser also, or is tsc targeting a node bundle?

**Comment by CodingMarkus** [comment]
`tsc` without any arguments reads all information from `tsconfig.json`, which looks like this:

```
{
	"compilerOptions": {
		"strict": true,

		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitOverride": true,
		"noUncheckedIndexedAccess": true,
		"noFallthroughCasesInSwitch": true,
		"noPropertyAccessFromIndexSignature": true,

		"lib": [ "ES2020", "DOM" ],
		"target": "ES2015",
		"module": "ES2015",
		"moduleResolution": "bundler",

		"sourceMap": true,
		"removeComments": true,
		"preserveConstEnums": true,

		"outDir": "dist"
	},

	"include": [
		"src/*.ts",
		"wasm/*.d.ts"
	],
  }
```

There is no `node` or `browser` with `tsc`. 

`ES2015` is the target that pretty much any browser still relevant supports (aka `ES6`, aka `ESM`). Newest browsers also support `ES2020` (aka `ESNEXT`). If you want to target Node, you'd either also use `ES2020` or `COMMONJS`. `COMMONJS` is the default module system of Node, but since `ES2015`-modules are a language feature of ES6, every runtime that supports ES6 must support those, regardless if browser or Node.

**Comment by davidstevens37** [comment]
@CodingMarkus  hey, sorry i completely forgot to respond to this.

- `bun add buffer`
--- 
*Scenario A*
```javascript
import { Buffer } from "buffer";
```
- `bun build index.js`

---
*Scenario B*
```javascript
import { Buffer } from "./node_modules/buffer/index.js";
```
- `bun build index.js`

--- 
Scenario A outputs the error you're experiencing. Scenario B builds successfully. I'm assuming the node builtins are taking precedence over node_modules. To overcome you're issue, simply reference the library directly instead of using the default module resolution.

I'm not sure what the correct resolution precedence is supposed to be, but both bun and node behave the same way in this scenario.  Perhaps `tsc` deviates in the module resolution ordering.  

---
```javascript
import { Buffer as thirdPartyBuffer } from "./node_modules/buffer/index.js";
console.log(thirdPartyBuffer === global.Buffer);
```
- `bun run index.js` // outputs `false`
- `node index.js` // outputs `false`
---

```javascript
import { Buffer as maybeThirdPartyBuffer } from "buffer";
console.log(maybeThirdPartyBuffer === global.Buffer);
```
- `bun run index.js` // outputs `true`
- `node index.js` // outputs `true`

**Comment by 7flash** [comment]
I'm currently experiencing this issue, and cannot reference buffer by relative path, because its being referenced inside of another library dependency. Please, any workaround I can apply to resolve this?
