### ISSUE TITLE
"bun i" installation loss

### ISSUE THREAD

**Issue by shiyanaaa** [oven-sh/bun#12273]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

When I execute "bun i @ vue office/docx", it prompts success, but the entry file is missing in the node.modules/@ vue office/docx/lib folder

### What is the expected behavior?

"npm i @ vue office/docx" is correct
![Snipaste_2024-07-01_11-58-56](https://github.com/oven-sh/bun/assets/78543700/f778cc9f-ef25-40c9-9197-c308fdb3ba0a)

### What do you see instead?

Missing file
![Snipaste_2024-07-01_11-58-18](https://github.com/oven-sh/bun/assets/78543700/3ff2af2b-b62f-400f-8264-504b39483341)

**Comment by dylan-conway** [comment]
`@vue-office/docx` has a postinstall that creates these files. To fix this issue you will need to add `@vue-office/docx` to `"trustedDependencies"` and install again. You can also do this by running `bun pm trust @vue-office/docx`.

https://bun.sh/docs/cli/install#lifecycle-scripts
