### ISSUE TITLE
Failed to install packages on macOS

### ISSUE THREAD

**Issue by aamibhoot** [oven-sh/bun#1227]
### Version

0.1.11 

### Platform

Darwin -.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

1.  `bun create next next-bun --yarn` (Used npm, pnpm and yarn. Only Yarn show completed other get stuck)
2. First tried `bun dev` and it didn't run so i tried `bun install` then it shows 

### How often does it reproduce? Is there a required condition?

Every time. I even completely removed Bun twice and installed it again.

### What is the expected behavior?

To run Bun 🤷🏻‍♂️

### What do you see instead?

![Screenshot 2022-09-10 at 8 56 02 PM](https://user-images.githubusercontent.com/77445154/189488944-0138c84e-acaa-4fab-a1a0-70431aeb5db5.png)

### Additional information

Any fixes please?

**Comment by eswr** [comment]
I could not reproduce this issue. Can you share your node and Next.js version too?
Also, have you tried updating the node_modules, that way you would move to a compatible Next.js version (if that is the issue)
```
bun bun --use next
```

**Comment by aamibhoot** [comment]
![Screenshot 2022-09-10 at 9 42 42 PM](https://user-images.githubusercontent.com/77445154/189490924-465cd318-acf2-40af-ad5e-595c05f79ff5.png)

**Comment by aamibhoot** [comment]
![Screenshot 2022-09-10 at 9 43 57 PM](https://user-images.githubusercontent.com/77445154/189490965-ca8a2811-4a42-481e-9dcf-4785657852de.png)

```
{
  "name": "next-bun",
  "version": "0.0.57",
  "dependencies": {
    "next": "12.2.3",
    "react": "^18",
    "react-dom": "^18",
    "react-is": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^18",
    "bun-framework-next": "^12.2.4",
    "typescript": "latest",
    "react-refresh": "0.10.0"
  },
  "module": "index.js"
}
```

**Comment by Jarred-Sumner** [comment]
Can you try running `bun install --backend=copyfile` and tell me if that works? It will be slower

**Comment by aamibhoot** [comment]
🐰❤️ Thanks @Jarred-Sumner it worked. Can you tell me what caused it? 

And two more things .... it's telling ... `Possibly incompatible Next.js version:  12.2.3 . Please upgrade to Next.js 11.1.2 or Next.js 12.0.2+.` and also 😞
![Screenshot 2022-09-12 at 11 35 55 PM](https://user-images.githubusercontent.com/77445154/189719716-94924347-e84f-4cea-a3af-cb03ae41fea4.png)

**Comment by himyjan** [comment]
Update example Next app to 13.0

**Comment by aamibhoot** [comment]
What about `Cannot access 'default' before initialization` ?

**Comment by Electroid** [comment]
Workaround is to use:

```
bun install --backend=copyfile
```

We're tracking this issue here: #362
