### ISSUE TITLE
Bun crashes on `bun i` on bun canary, Windows 11

### ISSUE THREAD

**Issue by hrtowii** [oven-sh/bun#12275]
### How can we reproduce the crash?

package.json is attached. How to reproduce: Just run bun i.

[package.json](https://github.com/user-attachments/files/16049542/package.json)

### Stack Trace (bun.report)

Bun v1.1.18 ([`861be55`](<https://github.com/oven-sh/bun/tree/861be5560ec776ea1a737b360cde2544a71b37c9>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds: index 1507, len 1496

- [`install.zig:4913`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L4913>): `enqueueDependencyWithMain`
- [`install.zig:5802`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L5802>): `processDependencyList`
- [`install.zig:12947`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L12947>): `isDone`
- [`install.zig:12985`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L12985>): `installPackages`
- [`install.zig:13724`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L13724>): `installWithManager`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1494`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/cli.zig#L1494>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.19 with #12485.
