### ISSUE TITLE
Internal assertion failure in Bun v1.1.17 on Windows when using --watch flag

### ISSUE THREAD

**Issue by mBuergi86** [oven-sh/bun#12279]
### How can we reproduce the crash?

To reproduce this crash, it appears the following steps were taken:

Use a project with pnpm as the package manager.
Have a script in package.json named "dev" that runs "bun --watch index.js".
Run the command "pnpm dev" in the project directory.
The crash occurs during the execution of this command, specifically while Bun is watching the index.js file.

### Relevant log output

```shell
The most relevant parts of the log output are:

Bun version and environment:
CopyBun v1.1.17 (bb66bba1) Windows x64

The command being executed:
CopyArgs: "C:\Users\marku\AppData\Local\pnpm\\global\5\node_modules\bun\bin\bun.exe" "--watch" "index.js"

The crash message:
Copypanic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

The auto-restart attempt:
Copy--- Bun is auto-restarting due to crash [time: 1719833585017] ---

The port conflict after restart:
CopyPort 3000 is already in use. Retrying in 5 seconds...


This log output suggests that the crash is indeed an internal issue with Bun, specifically related to its file watching functionality on Windows. The crash occurs during runtime, and Bun attempts to auto-restart, but then encounters a port conflict, likely due to the previous instance not fully terminating.
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [AutoCommand]

**panic**: Internal assertion failure

- [`debug.zig:443`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/deps/zig/lib/std/debug.zig#L443>): `panicExtra`
- [`bun.zig:3252`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.zig#L3252>): `assertionFailure`
- [`blob.zig:1706`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/webcore/blob.zig#L1706>): `sharedView`
- [`ReadFile.zig:756`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/webcore/blob/ReadFile.zig#L756>): `queueRead`
- `??`
- `fs__open`
- `uv_run`
- [`javascript.zig:985`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/javascript.zig#L985>): `unhandledRejection`
- `JSC__JSValue__fastGet_`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`

**Comment by cirospaciari** [comment]
Fixed in https://github.com/oven-sh/bun/pull/12441
