### ISSUE TITLE
Reduce the size of JS code when using `--minify-syntax` and enum

### ISSUE THREAD

**Issue by redphx** [oven-sh/bun#12285]
### What is the problem this feature would solve?

Reduce the size of JS code when using `--minify-syntax` and enum

### What is the feature you are proposing to solve the problem?

In the current version of Bun (1.1.17), this TS code 

```ts
enum VeryLongEnumName {
  A = 'a',
  B = 'b',
  C = 'c',
  D = 'd',
}
```

is being transformed into this JS code (same output when using `--minify-syntax`)

```js
var VeryLongEnumName;
(function(VeryLongEnumName2) {
  VeryLongEnumName2["A"] = 'a';
  VeryLongEnumName2["B"] = 'b';
  VeryLongEnumName2["C"] = 'c';
  VeryLongEnumName2["D"] = 'd';
})(VeryLongEnumName || (VeryLongEnumName = {}));
```

It'd be nice to have the `VeryLongEnumName2` variable replaced with a single-character variable name to reduce the size when using `--minify-syntax`. And use dot-notations to reduce the size even more.

```js
// Replace "VeryLongEnumName2" with "e"
(function(e) {
  e["A"] = 'a';
  e["B"] = 'b';
  e["C"] = 'c';
  e["D"] = 'd';
})(VeryLongEnumName || (VeryLongEnumName = {}));

// Even better: use dot-notations
(function(e) {
  e.A = 'a';
  e.B = 'b';
  e.C = 'c';
  e.D = 'd';
})(VeryLongEnumName || (VeryLongEnumName = {}));

// Or this
(function(e) {
  e.A = 'a', e.B = 'b', e.C = 'c', e.D = 'd';
})(VeryLongEnumName || (VeryLongEnumName = {}));

```

Thanks for your consideration.

**Comment by paperdave** [comment]
I just pushed up #12144 which is worth looking at. In this case, all uses of this enum unless you refer to the enum by name will avoid this codegen entirely.

To get minified identifiers, use --minify-identifiers

```
// hi.ts
var c;
(function(b) {
  b["A"] = "a";
  b["B"] = "b";
  b["C"] = "c";
  b["D"] = "d";
})(c || (c = {}));
```

Then with that and this PR, the codegen is now
```
// hi.ts
var l;
((c) => {
  c.A = "a";
  c.B = "b";
  c.C = "c";
  c.D = "d";
})(l ||= {});
```

I'm going to add a small patch to use the comma operator, and then mark this as closed.

**Comment by redphx** [comment]
I'm building an Userscript with Bun, and for transparency reason I don't want to use `--minify-identifiers`. So I'm hoping this feature can be applied to `--minify-syntax` too.  

If you don't want to then it's fine too. Thanks for your work.

**Comment by paperdave** [comment]
New codegen
```
var VeryLongEnumName;
((VeryLongEnumName2) => (
  VeryLongEnumName2.A = "a", 
  VeryLongEnumName2.B = "b", 
  VeryLongEnumName2.C = "c", 
  VeryLongEnumName2.D = "d"
))(VeryLongEnumName ||= {});
```
With minify-identifiers
```
var l;
((c) => (c.A = "a", c.B = "b", c.C = "c", c.D = "d"))(l ||= {});
```

I believe #12114 should suffice your use case with enum inlining. I don't want to enable identifier minification in any context without that flag.

**Comment by paperdave** [comment]
Actually the comma operator does not reduce code size at all. I am going to revert that. This will be fixed by all the existing changes in my PR.

<img width="791" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/1dcf8296-6211-4e34-aa27-a52c7fa91f39">

^ it's possible that gzip compression will perform worse on that considering `()=>{` is much more likely to see than `()=>(`
