### ISSUE TITLE
Incomplete support on Ubuntu 20.04

### ISSUE THREAD

**Issue by ryuujo1573** [oven-sh/bun#12281]
### What is the type of issue?

Something else

### What is the issue?

> ⚠️ Ubuntu distributions may require installation of the C++ standard library independently. See the [troubleshooting section](https://bun.sh/docs/project/contributing#span-file-not-found-on-ubuntu) for more information.

Per reference above, I had `gcc-11` and `g++-11` installed, which solved missing `#include <span>`.

However, as continuing the make progress, the linker complains about `error: undefined symbol: __libc_single_threaded`.

After searching for possible causes and solutions online, I've found that
**this symbol was introduced by `glibc` after `2.32`, and unfortunately the ubuntu 20.24 only provides [`2.31`](https://launchpad.net/ubuntu/focal/+source/glibc) for now.**

So it might be of help if we add a reminder that with an ubuntu below 22 the experience might be rough....

**Comment by paperdave** [comment]
would you like to contribute docs changes for this?

**Comment by ryuujo1573** [comment]
> would you like to contribute docs changes for this?

Sure! But pls excuse my expression. I'm not a native tongue 💭

**Comment by ryuujo1573** [comment]
I guess this can be closed for now!
