### ISSUE TITLE
`bun patch --commit` produces an empty package.json

### ISSUE THREAD

**Issue by flokol120** [oven-sh/bun#12288]
### What version of Bun is running?

1.1.18-canary.1+bf14a09a2

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Run `bun patch` in a repo with workspaces (in this case `bun patch @parcel/runtime-browser-hmr`)
2. Make changes to package
3. Run `bun patch --commit` (in this case `bun patch --commit 'node_modules/@parcel/runtime-browser-hmr'`) 

### What is the expected behavior?

The patched changes should be added to the package.json.

### What do you see instead?

The package.json is completely purged.

### Additional information

If I can somehow provide additional information, please help me on how to gather them. I tried to run `bun install --yarn` afterwards to get some human-readable information, but as the package.json is empty, bun deleted the bun.lockdb aswell.

**Comment by flokol120** [comment]
The patches themselves seem to be created successfully. I can add the patch manually to the package.json and it works:
```json
	"patchedDependencies": {
		"react-collapse-pane@3.0.1": "patches/react-collapse-pane@3.0.1.patch",
		"@parcel/runtime-browser-hmr@2.12.0": "patches/@parcel%2Fruntime-browser-hmr@2.12.0.patch"
	}
```

**Comment by dylan-conway** [comment]
Trying to repro this behavior, a couple questions:
- did you run `bun patch <package>` within a workspace or in the root?
- was it the root package.json that was deleted or a workspace package.json?
- could you share the root package.json?
- did bun print `No packages! Deleted empty lockfile` before deleting the lockfile?

**Comment by flokol120** [comment]
- bun patch was executed in the root folder
- The root package.json was deleted
- Yes, the message was printed before bun deleted the lock file
I will try to create a min repro from my package.json.

**Comment by flokol120** [comment]
@dylan-conway: I was able to set up a min repro project: https://github.com/flokol120/workspaces-patch-bug

Unfortunately, the issue seems to arise only sporadically. In rare cases, an error is printed, the package.json is not cleared, but no patches are added:
```
bun patch --commit 'node_modules/@parcel/runtime-browser-hmr'
bun patch v1.1.18-canary.1 (bf14a09a)

1 package installed [4.51s]
error: An unknown error occurred (Unexpected)
```
Every so often the package.json is not empty but filled with gibberish/binary data.

**Comment by flokol120** [comment]
The fix is working. Impressive! thanks for the quick fix.
