### ISSUE TITLE
Implement esbuild `packages` option in bun bundler

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12293]
### What is the problem this feature would solve?

sometimes, we want to bundle all of our local imports (i.e. `./utils.js`) but not our `node_modules` (i.e. `svelte`)

### What is the feature you are proposing to solve the problem?

Implement esbuild `packages: "external"` option
https://esbuild.github.io/api/#packages

### What alternatives have you considered?

```ts
import pkg from "./package.json";

Bun.build({
  external: Object.keys(pkg.dependencies),
});
```

**Comment by paperdave** [comment]
i like this

**Comment by huseeiin** [comment]
> i like this

Basically its like a transpiler but only bundles local imports. another example is `tsup`, it externalizes all `devDependencies` without even asking it.
