### ISSUE TITLE
`bun --version` takes ~1s to run

### ISSUE THREAD

**Issue by NivaldoFarias** [oven-sh/bun#12294]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 6.5.0-42-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Install bun.
2. Run `bun --version`.

### What is the expected behavior?

It should return either immediatly or in a few milliseconds.

### What do you see instead?

It takes ~1s to execute and return the current version.

### Additional information
This wouldnt be much of a headache, but I use starship and it runs that command to correctly display bun's version when it finds a lockfile in the current repo. Starship's runtime timeouts bc of bun and doesnt display it correctly. 

I've already tried re-installing bun, but that didnt seem to make any difference :(.

time benchmark:
![image](https://github.com/oven-sh/bun/assets/90518458/960c1fa7-d65b-4442-9312-fb2de328f182)

**Comment by birkskyum** [comment]
On macos i see it work, so maybe it's OS-specific:

<img width="545" alt="Screenshot 2024-07-02 at 19 54 40" src="https://github.com/oven-sh/bun/assets/74932975/0e4439aa-dbb0-4b9a-9735-b7105bddca19">

1.1.17+bb66bba1b

**Comment by paperdave** [comment]
if you run `which bun`, does it point at $HOME/.bin/bun, or is there some wrapper your shell is providing? if you install via `npm`, there is a possible but unlikely chance there is a node.js wrapper script, but one second is extreme.

**Comment by NivaldoFarias** [comment]
> if you run `which bun`, does it point at $HOME/.bin/bun, or is there some wrapper your shell is providing? if you install via `npm`, there is a possible but unlikely chance there is a node.js wrapper script, but one second is extreme.

Beforehand, I ran `du -sh ~/.bun/bin/bun` thinking that was the bin used for bun, it yields `93M`. However, `which bun` gave me `~/.proto/bin/bun`. Running `du -sh ~/.proto/bin/bun` yields `4,0K`. 

This might be related to some compression issue?

**Comment by NivaldoFarias** [comment]
oh my god it was actually bc of [proto](https://moonrepo.dev/docs/proto) 😭 I installed it years ago but didnt really use it, I have absolutely no idea why the binary was using proto for install ?? I used the default bash script to install bun.

Anyways, uninstalling `proto` resolved the issue. Steps: 

- `rm -rf ~/.proto`
- `which bun` now yields correct binary, `~/.bun/bin/bun`.

![image](https://github.com/oven-sh/bun/assets/90518458/bdda25e0-a77a-40c1-9008-aac967509bfb)

I was going MAD over this for ages. tysm for the help !!

**Comment by NivaldoFarias** [comment]
oh my god it was actually bc of [proto](https://moonrepo.dev/docs/proto) 😭 I installed it years ago but didnt really use it, I have absolutely no idea why the binary was using proto for install ?? I used the default bash script to install bun.

Anyways, uninstalling `proto` resolved the issue. Steps: 

- `rm -rf ~/.proto`
- `which bun` now yields correct binary, `~/.bun/bin/bun`.

![image](https://github.com/oven-sh/bun/assets/90518458/bdda25e0-a77a-40c1-9008-aac967509bfb)

I was going MAD over this for ages. tysm for the help !!

**Comment by A-D-E-A** [comment]
That's weird. I have no issue with proto on my side. It's a bit slower than using `bun` directly, but not *that* bad.

![image](https://github.com/oven-sh/bun/assets/52578762/f6e7180e-0100-4c7f-9ab4-ae9dd07431ff)
