### ISSUE TITLE
HTTP randomly hangs or has a segmentation fault

### ISSUE THREAD

**Issue by malonehedges** [oven-sh/bun#1229]
### Version

0.1.11

### Platform

Darwin [redacted].lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

it seems to be random but will happen fairly frequently. running many http requests results in it eventually

### How often does it reproduce? Is there a required condition?

no clear repro case, just running a bunch of http requests

### What is the expected behavior?

http requests dont have a segmentation fault or hang

### What do you see instead?

<img width="553" alt="image" src="https://user-images.githubusercontent.com/12092296/189496143-947f3e24-e1a1-47f6-a45b-ed4eed627af8.png">

### Additional information

NOTE: This is happening with requests to a localhost server. i am requesting `127.0.0.1` which you wouldn't expect to ever fail as long as the local server responds properly

**Comment by malonehedges** [comment]
I've also noticed that the requests come in much slower with 0.1.11 compared to 0.1.10

doing about 50 requests in a row is where this behavior is very noticable

**Comment by malonehedges** [comment]
basic repro repo shows that randomly requests will hang in v0.1.10. have yet to try on v0.1.11 as i have a program running where I need 0.1.10. will update with results from that later today
https://github.com/malonehedges/bun-http-error-repro

**Comment by Jarred-Sumner** [comment]
For other readers: this will be fixed in the next version of Bun and on macOS it should be fixed now in canary

`bun upgrade --canary`

Still working on a fix for Linux.

**Comment by Jarred-Sumner** [comment]
Should be fixed as of Bun v0.1.12
