### ISSUE TITLE
fastify errors when using bun, works fine with node

### ISSUE THREAD

**Issue by 4-0-9** [oven-sh/bun#12298]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 6.9.7-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Bun produces an error that node doesn't when I updated to a newer version (4.26.2 -> 4.28.1) of [Fastify](https://github.com/fastify/fastify).
```javascript
const fastify = require('fastify')();

fastify.listen({ port: 3000 }, function (err, address) {
  if (err) {
    console.log(`Error: ${err}`);
    process.exit(1);
  }

  console.log(`Server running (${address})`);
});
```

### What is the expected behavior?

This is the output I get when I run the script using node (`node index.js`):
 `Server running (http://[::1]:3000)`

### What do you see instead?

This is the output I get when I run the script using Bun (`bun index.js`):
`Error: localhost`

**Comment by CarlosEduR** [comment]
Interesting case here, I am taking a look...

While testing, I noticed this version works fine with fastify v4.28.1:

```javascript
const fastify = require("fastify")();

fastify
  .listen({ port: 3000 })
  .then(address => {
    console.log(`Server running (${address})`);
  })
  .catch(err => {
    console.log(`Error: ${err}`);
    process.exit(1);
  });
```

**Comment by 4-0-9** [comment]
Interesting. Any idea why the promise works but the callback doesn't?

**Comment by CarlosEduR** [comment]
Yeah, no ideia yet. Another thing I noticed, v4.28.0 still works fine using callbacks with bun, so seems something related to this patch version update.

**Comment by 4-0-9** [comment]
It seems [Bun v1.1.21](https://github.com/oven-sh/bun/releases/tag/bun-v1.1.21) has fixed this issue.
