### ISSUE TITLE
Worker not terminated when `parentPort` closed

### ISSUE THREAD

**Issue by guyutongxue** [oven-sh/bun#12309]
### What version of Bun is running?

1.1.17

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64 (also tested under Linux 6.8.0-35-generic x86_64 x86_64)

### What steps can reproduce the bug?

**`main.js`**:

```js
import { Worker } from "node:worker_threads";
import path from "node:path";
const worker = new Worker(path.resolve(import.meta.dirname, "./worker.js"));
worker.postMessage("ping");
```

**`worker.js`**:

```js
import { parentPort } from "node:worker_threads";
parentPort?.on("message", () => {
  parentPort?.close();
});
```

Also assume that `package.json` has `"type": "module"` already. Run `bun main.js`.

### What is the expected behavior?

The process (and its child threads) should terminate immediately. With node v20.15.0:

```
PS C:\Users\Guyutongxue\Downloads\temp\test> node main.js
PS C:\Users\Guyutongxue\Downloads\temp\test> echo $?     # <-- process exit immediately
True
```

### What do you see instead?

With `bun`:

```
PS C:\Users\Guyutongxue\Downloads\temp\test> bun main.js

```

... oops, it just hang.

### Additional information

This might be the root cause of #8816 (or mark as a duplicate of that but that issue is some kind of off-topic in later discussion).

This issue causes [tsup](https://tsup.egoist.dev/) with `dts` enabled cannot run successfully in Bun. I've chose tsup because `bun build` lacks builtin dts generation, but running tsup with Bun will stuck after all tasks done (because the dts generation is running in a background worker). I need Node installed to make that work.

**Comment by Guyutongxue** [comment]
Dups of #11760
