### ISSUE TITLE
Dynamic import only tries to use the first of two concatenated strings?

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#1230]
### Version

0.1.6

### Platform

Darwin Germain 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run the following file:

```ts
// entry.ts
console.log(await import("@esm-bundle" + "/chai"))
```

```shell
> bun entry.ts


error: Cannot find package "@esm-bundle" from "/Users/lgarron/Code/git/github.com/cubing/cubing.js/src/test/chai-workarounds/entry.ts"
```

It seems that `bun` is only taking the `"@esm-bundle"` string, and is therefore breaking the semantics of the source code.

### How often does it reproduce? Is there a required condition?

Consistently.

### What is the expected behavior?

`bun` should try to import the concatenated string (`"@esm-bundle/chai"`).

I understand that this may sound like a bit of an edge case, but I'm filing this issue after encountering it in real code.

It's easy to end up with such concatenations after a refactor, or as a workaround for other issues. For example, some formatters may try/suggest to inline code in a way that will trigger the issue:

```ts
// entry.ts before refactoring
const CHAI = "chai";
console.log(await import("@esm-bundle/" + CHAI))
```

```ts
// entry.ts after refactoring
console.log(await import("@esm-bundle/" + "chai"))
```

I think it would be valuable if we could rely on `bun` to handle such code correctly.

### What do you see instead?

See error above.

**Comment by Jarred-Sumner** [comment]
Definitely a bug
