### ISSUE TITLE
`--if-present` flag not recognized if passed last

### ISSUE THREAD

**Issue by todor-a** [oven-sh/bun#12301]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Running:
```
bun run --if-present format
```

Is resolved correctly, but running:
```
bun run format --if-present
```

is not.

For reference, with npm both work.

### What is the expected behavior?

Resolve the flag, no matter it's position.

**Comment by Jarred-Sumner** [comment]
Unfortunately, we cannot as that would prevent the script from receiving the arguments and it gets very confusing with flags that may exist in both like `--help`
