### ISSUE TITLE
zsh completions being added to `.zshrc` on every upgrade is unnecessary

### ISSUE THREAD

**Issue by aboqasem** [oven-sh/bun#12308]
https://github.com/oven-sh/bun/blob/2f0789af7c46d54e75c7d1639f2ddc19f9aeb7d6/src/cli/install_completions_command.zig#L544-L553

It's a little annoying to keep removing it from `.zshrc` if you have managed dotfiles and you structure things outside of `.zshrc`. For example, I place it in another custom `profile.zsh`: https://github.com/aboqasem/dotfiles/blob/fbfd5ddb303a8c4109d619d697efa822a005eafc/custom/profile.zsh#L15-L16

Can it possibly be just a log to stdout?

Like:

```
To enable Bun completions, run the following command:

  echo '# bun completions\n[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"' >> ~/.zshrc
```

**Comment by Jarred-Sumner** [comment]
Add the comment below and Bun will no longer attempt to insert it
```
# bun completions
```

For most users, asking them to install completions means it will never happen and the experience will be worse as a result - so we're unlikely to disable this default.
