### ISSUE TITLE
No version matching "^5.16.1" found for specifier "prisma" (but package exists)

### ISSUE THREAD

**Issue by bilabror** [oven-sh/bun#12317]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

**First** :
I ran `bun add -D prisma` and encountered the following error:
```zsh
bun add v1.1.17 (bb66bba1)
error: Package "prisma" with tag "latest" not found, but package exists
error: prisma@ failed to resolve
```

**Second** :
I manually added the following to `package.json`:
```json
{
  "devDependencies": {
     "prisma": "^5.16.1"
  }
}
```
Before running `bun install` again, I deleted `node_modules` and `bun.lockb`, but unfortunately I still encountered the same error.

### What is the expected behavior?

installing a package that is released should work

### What do you see instead?

No version matching "^5.16.1" found for specifier "prisma" (but package exists)

### Additional information

prisma version is `5.16.1`

**Comment by bilabror** [comment]
I ran `bun install --force`, but it still doesn't work.

**Comment by 7f8ddd** [comment]
`bun i prisma@^5.16.1` works for me

**Comment by bilabror** [comment]
Guys, This morning I tried again and suddenly the error was not encountered again

`bun add -D prisma` : WORK
`bun install` : WORK

**Comment by Randysheng** [comment]
i have the same problem 😭

**Comment by bilabror** [comment]
> i have the same problem 😭

@Randysheng  is it solved now?
