### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Pancake-Q** [oven-sh/bun#12329]
### What version of Bun is running?

1.1.8

### What steps can reproduce the bug?

<img width="1167" alt="image" src="https://github.com/oven-sh/bun/assets/81684567/1b77fa28-e6fd-4d23-8293-4e918b958172">

**Comment by Jarred-Sumner** [comment]
Please install Bun via the powershell script or make sure that optional dependencies are installed when using npm to install Bun
