### ISSUE TITLE
`.set` method with `File` from `FormData` differs in behavior from Node.js (file name is lost)

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#12325]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I came across this when [I was uploading files to Telegram using GramIO](https://gramio.dev/files/overview). I am sure that this is reproduced in other cases.

The fact is that when I fill in the `FormData` using the `.set` method, the **filename** is lost when uploading to Telegram, although in `Node.js` everything works as expected...

```ts
async function sendDocument(body) {
    const response = await fetch(
        `https://api.telegram.org/bot${process.env.BOT_TOKEN}/sendDocument`,
        {
            method: "POST",
            body: body
        }
    );
    
    const json = await response.json();
    
    console.log(json);
}

const formDataSet = new FormData();

formDataSet.set("chat_id", "617580375");
formDataSet.set("document", new File(["some text notes"], "text-notes.txt"));

await sendDocument(formDataSet)

const formDataAppend = new FormData();

formDataAppend.append("chat_id", "617580375");
formDataAppend.append("document", new File(["some text notes"], "text-notes.txt"));

await sendDocument(formDataAppend)
```

If you try to run this option through `Node.js`, both options will send a file with the specified name, but if you run it through `Bun`, then there will be only second file with the correct name (where it was `FormData.append` used)

![image](https://github.com/oven-sh/bun/assets/57632712/94c8da49-537f-4f41-8d29-18bab98d3697)

Verbose logs where `.set` used (wrong filename)

```bash
[fetch] > HTTP/1.1 POST https://api.telegram.org/bot[REDACTED]/sendDocument
[fetch] > Content-Type: multipart/form-data; boundary="-WebkitFormBoundary980f0dfe1eed40e094766072fdf6ca05"
[fetch] > Connection: keep-alive
[fetch] > User-Agent: Bun/1.1.17
[fetch] > Accept: */*
[fetch] > Host: api.telegram.org
[fetch] > Accept-Encoding: gzip, deflate, br
[fetch] > Content-Length: 349
```

Verbose logs where `.append` used

```bash
[fetch] > HTTP/1.1 POST https://api.telegram.org/bot[REDACTED]/sendDocument
[fetch] > Content-Type: multipart/form-data; boundary="-WebkitFormBoundary233a1c42edc94d80ba8d2c57b543727c"
[fetch] > Connection: keep-alive
[fetch] > User-Agent: Bun/1.1.17
[fetch] > Accept: */*
[fetch] > Host: api.telegram.org
[fetch] > Accept-Encoding: gzip, deflate, br
[fetch] > Content-Length: 363
```
as we can see `Content-Length` differs

Because of this, file uploads to [GramIO](https://gramio.dev/) didn't work correctly for a long time, but I'm glad to get to the truth!

**Comment by billywhizz** [comment]
PR here https://github.com/oven-sh/bun/pull/12379
