### ISSUE TITLE
bun install - azure private feeds not supported?

### ISSUE THREAD

**Issue by Catharsis68** [oven-sh/bun#1233]
Version: `0.1.11`

Not sure if this is a bug or more a feature request:

Currently it is not possible to use feeds from **Azure Artifcats** as **private npm package registry** together with `bun install`.

According to the [documentation](https://docs.microsoft.com/de-de/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=linux%2Cclassic), authentication to the azure servers requires a `.npmrc` file with this syntax ([protocol relative url](https://en.wikipedia.org/wiki/URL#prurl))

```sh
# Set the private azure registry for 'my-private-package' scoped packages
my-private-package:registry=https://<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/

; begin auth token
//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:always-auth ="true"
//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:username="some string"
//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:_password="<base64-secret>"
//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:email="some email address"
; end auth token
```

I created a `.bunfig.toml` file:
```
"my-private-package" = { url = "https://<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry" }
"//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:always-auth" = "true"
"//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:username" = "some string"
"//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:_password" = "<base64-secret>"
"//<ORGANIZATION_NAME>.pkgs.visualstudio.com/_packaging/<FEED_NAME>/npm/registry/:email" = "some email address"
```

`npm i` is working, `bun install` throws a 401 Unauthenticated error.

Any thoughts here?

**Comment by Electroid** [comment]
We will support this, but don't right now. We're tracking support for `.npmrc` here: #643

**Comment by zachbryant** [comment]
I was able to get my private azure feeds to authenticate (for the most part). Not sure why I could now, but I copied in the same username with base64-decoded PAT as password and it works. Only one of my registries doesn't work for some reason that isn't explained beyond 401.

**Comment by zachbryant** [comment]
I also don't think azure specifically requires that npmrc format, it just looks like what they give you as instructions for how to connect
