### ISSUE TITLE
Seg fault when using SSH2 and exception thrown

### ISSUE THREAD

**Issue by PhilBladen** [oven-sh/bun#12345]
### How can we reproduce the crash?

Run `bun i ssh2` first. Then run:
```js
import "ssh2";
throw new Error("This is a test error");
```

### Relevant log output

```shell
1 | import "ssh2";
2 | throw new Error("This is a test error");
          ^
error: This is a test error
      at D:\segfault.mjs:2:7

Bun v1.1.17 (Windows x64)
============================================================
Bun v1.1.17 (bb66bba1) Windows x64
Args: "C:\Users\Phil\.bun\bin\bun.exe" ".\segfault.mjs"
Features: jsc transpiler_cache(5) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:dns" "node:events" "node:fs" "node:http" "node:https" "node:net" "node:path" "node:stream" "node:string_decoder" "node:tls" "node:util" "node:util/types" "node:zlib" 
Elapsed: 321ms | User: 15ms | Sys: 15ms
RSS: 0.29GB | Peak: 0.29GB | Commit: 0.36GB | Faults: 71044

panic(main thread): Segmentation fault at address 0x7FFD527657DC
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FF8001C3B38

- *1 unknown/js code*
- ??? at `0x5177c` in ntdll.dll
- ??? at `0x514d7` in ntdll.dll
- ??? at `0x5117d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- ??? at `0x1bed8` in ucrtbase.dll
- ??? at `0x1c099` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/Global.zig#L106>): `exit`
- [`bun_js.zig:313`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun_js.zig#L313>): `start`

**Comment by Jarred-Sumner** [comment]
wow thank you for this reproduction

we've seen several crsah reports with a similar stacktrace, and had no way to reproduce this

**Comment by Jarred-Sumner** [comment]
Turns out it's caused by `cpu-features` which relies on V8 C++ APIs

Please follow along in #4290. @190n is actively working on fixing it.
