### ISSUE TITLE
Bun drops arguments in process.argv

### ISSUE THREAD

**Issue by borkdude** [oven-sh/bun#1236]
### Version

0.1.11

### Platform

macOS

### What steps will reproduce the bug?

A script `args.js`:

```
console.log(process.argv)
```

Node:

```
$ node /tmp/args.js -e '(+ 1 2 3)'
[
  '/Users/borkdude/.nvm/versions/node/v17.8.0/bin/node',
  '/tmp/args.js',
  '-e',
  '(+ 1 2 3)'
]
```

Bun:

``` 
$ bun /tmp/args.js -e '(+ 1 2 3)'
[ "bun", "/tmp/args.js" ]
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Behave as node: don't drop argv arguments

### What do you see instead?

Arguments `-e '(+ 1 2 3)'` are dropped

**Comment by xhyrom** [comment]
try `bun /tmp/args.js -- -e '(+ 1 2 3)'`

**Comment by borkdude** [comment]
I'm aware of this workaround, but I still consider the originally reported issue as a bug.

**Comment by Jarred-Sumner** [comment]
Fixed in canary

To upgrade:

```bash
bun upgrade --canary
```

**Comment by borkdude** [comment]
Confirmed. I noticed that the script argument's symbolic link is now fully resolved as well. Not sure if that was intended, but I don't mind the change.

```
borkdude@m1 /tmp/sqt $ bun /tmp/args.js -e '(+ 1 2 3)'
[ "bun", "/private/tmp/args.js", "-e", "(+ 1 2 3)" ]
```
