### ISSUE TITLE
Bun crashing when trying to await `Bun.write` inside test function

### ISSUE THREAD

**Issue by karlrobeck** [oven-sh/bun#12360]
### How can we reproduce the crash?

Hi, im trying to create a cli tool for executing .exe file on bun. i'm also trying to create a test for generating random .exe file so that my "validatePath" function could determine if that file path exist or not.

here is my validatePath function code

```javascript
import { fileURLToPath, pathToFileURL } from "bun"

export async function validatePath(path: URL): Promise<URL | string> {

  const filePath = fileURLToPath(path)

  if (await Bun.file(filePath).exists()) {
    return pathToFileURL(filePath)
  } else {
    return ""
  }
}
```

i have two test, the first one test for invalid input

```javascript
test("validate executable given in the config using `validatePath`: invalid value", async () => {

    const filePath = "./sample.exe"

    const newFilePath = await validatePath(pathToFileURL(filePath))

    expect(newFilePath).toBe("");
})
 ```

and for the second test, it will now generate a .exe file or any file.

```javascript
test("validate executable given in the config using `validatePath`: expected real implementation", async () => {

  const editorPath: URL | string = pathToFileURL("./metaeditor64.exe")
  const terminalPath: URL | string = pathToFileURL("./terminal64.exe")

  await Bun.write(editorPath.pathname, "im a editor")
  await Bun.write(terminalPath.pathname, "im a terminal")

  const newEditorPath = <URL>await validatePath(editorPath)
  const newTerminalPath = <URL>await validatePath(terminalPath)

  expect(newEditorPath.pathname).toBe(editorPath.pathname)
  expect(newTerminalPath.pathname).toBe(terminalPath.pathname)
})
```

when running `bun test`. bun panics when trying to execute the second test

```bash
src\utils.test.ts:
✓ validatePath > validate executeable given in the config using `validatePath`: invalid value
============================================================
Bun v1.1.18 (5a0b9352) Windows x64
Args: "bun" "test"
Features: jsc tsconfig(2)
Elapsed: 67ms | User: 46ms | Sys: 62ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.22GB | Faults: 33489

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

after further investigation. the main culprit on why bun is crashing is the `Bun.write` function.

```javascript
await Bun.write(editorPath.pathname, "im a editor")
await Bun.write(terminalPath.pathname, "im a terminal")
```

trying to await `Bun.write` when testing cause the Bun runtime to panic.

### Relevant log output

```shell
Bun v1.1.18 (5a0b9352) Windows x64
Args: "bun" "test"
Features: jsc tsconfig(2)
Elapsed: 73ms | User: 62ms | Sys: 93ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.22GB | Faults: 33447

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [TestCommand]

**panic**: Internal assertion failure

- [`debug.zig:439`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/zig/lib/std/debug.zig#L439>): `panicExtra`
- [`bun.zig:3258`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.zig#L3258>): `assertionFailure`
- [`bindings.zig:2713`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/bindings/bindings.zig#L2713>): `getSourceCode`
- [`event_loop.zig:1010`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/event_loop.zig#L1010>): `tickQueueWithCount`
- [`event_loop.zig:1465`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/event_loop.zig#L1465>): `tick`
- [`javascript.zig:809`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/javascript.zig#L809>): `get`
- [`test_command.zig:1138`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli/test_command.zig#L1138>): `begin`
- [`Ref.h:48`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/C:/a/bun/bun/build/bun-webkit/include/wtf/Ref.h#L48>): `WTF::DefaultRefDerefTraits<WTF::StringImpl>::refIfNotNull`
- [`test_command.zig:1147`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli/test_command.zig#L1147>): `runAllTests`
- [`test_command.zig:918`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli/test_command.zig#L918>): `exec`

**Comment by Jarred-Sumner** [comment]
Unfortunately, for us to be able to potentially reproduce this - it will need all the code that is being executed when the crash occurs. The specific line causing the crash is not the line where it happens. The cause is happening earlier, and then only triggering at the next allocation or something along those lines. Can you send a .zip file or a Github repo we can run?

<img width="902" alt="image" src="https://github.com/oven-sh/bun/assets/709451/37c38d99-fc49-4b41-9a6a-b0ce4df47387">

**Comment by karlrobeck** [comment]
here is the source code that contains the code.

https://github.com/karlrobeck/Bun-write-error-test

i also tried the repo to my arch wsl to see if i can also reproduce the error. weird thing is that on my wsl system. it doesnt reproduce the error only on my windows system.


Arch wsl Bun 1.1.17

![image](https://github.com/oven-sh/bun/assets/119088381/9a401e3e-34dc-447e-a0c2-c028dc669ded)

windows 10 Bun 1.1.18

![image](https://github.com/oven-sh/bun/assets/119088381/8ff58b61-fcc5-4940-bb44-8277aafce894)

Arch wsl Bun 1.1.18 (i upgraded it)

![image](https://github.com/oven-sh/bun/assets/119088381/acdce557-2988-4a70-8d0d-70757bfea89c)

**Comment by Jarred-Sumner** [comment]
Thank you. I am able to reproduce this on Windows.
