### ISSUE TITLE
Importing a file again after modification uses a cached version

### ISSUE THREAD

**Issue by Guibi1** [oven-sh/bun#12371]
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Ubuntu WSL on Win11

### What steps can reproduce the bug?

Have one file import dynamically another file, modify the imported file, then re-import it. The second import will always (as far as i know) return the module that was imported beforehand.

./index.ts
```ts
console.log(await import("./module"));
await Bun.sleep(10_000); // Or any other code
console.log(await import("./module"));
```

./module.ts
```ts
export default "This string is cached after the first import :(";
```

### What is the expected behavior?

The import should return the new version of the file.

I understand this behaviour in a performance stand point, but i think there _should_ be a way to disable this behaviour/clear the cache. Something like `Bun.clearImportCache()` would be perfect for my use case.

### What do you see instead?

> bun index.ts

Module {
  default: "This string is cached after the first import :(",
}
Module {
  default: "This string is cached after the first import :(",
}

### Additional information

In the exemple, you have to modify the other file by hand, but the same behaviour occurs when the file is rewritten by the same process. (`Bun.write` instead of `Bun.sleep` for example)

This also affects Plugins:
```ts
const plugin: BunPlugin = {
    name: "RandomExamplePlugin",
    async setup(build) {
        build.onLoad({ filter: /\.ts$/ }, async (args) => {
            return {
                contents: `export const version = ${Math.random()};`,
                loader: "js",
            };
        });
    },
};
```

**Comment by 0zl** [comment]
You can use a query string to version the module, like `import('./module?v=1')`. This should bypass the cache and give you the updated file.

**Comment by Guibi1** [comment]
I forgot to mention it, but that behaviour also happens in deeply imported module.
For example, reimporting a file which itself imports a module, or two files importing the same module. In that case, I can't add a query string, as I am *technically* not the one who imported the modified file...

Also, in my particular use case (react SSR), the import statements live inside the react code base, so I can't really alter them to add a query string.

**Comment by Syth-1** [comment]
I had asked this question on discord, which jarred had answered but i had yet to implament, having seen your question, i had a look through again and have got a implamentation (thanks jarred!)

```ts
for (const file of Object.keys(require.cache) 
    delete require.cache[file]
```
that should completely clear the import cache!

**Comment by Guibi1** [comment]
Oh nice! I never would have guessed that `require.cache` exists!

Just some minor details:

- What imports do you need for your code to run? (path.dirname is from `node:path` ?)
- Why do you need to _not_ re-import what's in import.meta.dir? (does stuff break?)
- Same question about node_modules (though thats curiosity more than anything else)

**Comment by Syth-1** [comment]
- 1) Yup, my bad forgot to put `import path from 'node:path'`
- 2) Found the root cause for my app breaking, if you re-import modules with a static class property, well the module being completely different means it has no links to the prior module that was imported. this is expected behaviour ig. 
- 3) I had tried a bunch of things that remedied my bug in point 2, but failed to test if those made any difference - having re-test them, it seems everything is fine, rather i should make changes to my project to avoid using static class properties, TLDR you should be fine removing all imports if so needed.

**Comment by Guibi1** [comment]
Sounds good !
Thanks for the fast answers :)
