### ISSUE TITLE
bun upgrade | unzip

### ISSUE THREAD

**Issue by MRgrav** [oven-sh/bun#12395]
### What version of Bun is running?

1.1.16

### What platform is your computer?

Linux 6.9.7-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

I don't know why unzip is not detected by bun,  unzip is installed using 
```
sudo pacman -S unzip
```

issue:
```
$ bun upgrade
Bun v1.1.18 is out! You're on v1.1.16
error: Failed to locate "unzip" in PATH. bun upgrade needs "unzip" to work.
```

**Comment by Jarred-Sumner** [comment]
Duplicate of #7732
