### ISSUE TITLE
panic(main thread): index out of bounds: index 1547, len 1436

### ISSUE THREAD

**Issue by pulgueta** [oven-sh/bun#12401]
### How can we reproduce the crash?

1. Clone the following repo: https://github.com/pulgueta/OSS-Interviewer
2. Run `bun install`
3. Crash

### Relevant log output

```shell
bun install v1.1.17 (bb66bba1)
============================================================
Bun v1.1.17 (bb66bba1) Windows x64
Args: "C:\Users\retar\.bun\bin\bun.exe" "i"
Features: extracted_packages(5)
Elapsed: 476ms | User: 31ms | Sys: 15ms
RSS: 0.25GB | Peak: 0.25GB | Commit: 0.42GB | Faults: 60994

panic(main thread): index out of bounds: index 1547, len 1436
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.17/wi1bb66bbaAggB42h7H82oiF4psiFupvhFq/r+Eo9/6E2m7iGqmfi8Io82g+CA0eNrLzEtJrVDILy1RyE9TSMovzUsptlLIBAsampqY6yjkpOYpGJoYmwEALSsNDQ
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds: index 7337, len 5957

- [`install.zig:4906`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L4906>): `enqueueDependencyWithMain`
- [`install.zig:5793`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L5793>): `processDependencyList`
- [`install.zig:12861`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L12861>): `isDone`
- [`install.zig:12899`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L12899>): `installPackages`
- [`install.zig:13637`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L13637>): `installWithManager`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1492`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli.zig#L1492>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/main.zig#L51>): `main`
- [`int_log10.rs:146`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/num/int_log10.rs#L146>): `core::num::int_log10::panic_for_nonpositive_argument`

**Comment by dylan-conway** [comment]
This is fixed in the latest version of bun. I believe #12485 fixed it in v1.1.19.
