### ISSUE TITLE
napi exports is broken on latest version

### ISSUE THREAD

**Issue by xhyrom** [oven-sh/bun#1240]
### Version

v0.1.11

### Platform

Linux LAPTOP-J5PF3D19 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```js
import { spawn } from 'bun-utilities/spawn';

const test = spawn('echo', ['test']);
console.log(test);
```

on bun v0.1.10:
![image](https://user-images.githubusercontent.com/56601352/190345568-d2d7805d-c16b-4442-b245-e2a56c19fac7.png)

on bun v0.1.11:
![image](https://user-images.githubusercontent.com/56601352/190345883-997e2eb4-1939-419a-b56f-f1bc8de58379.png)

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Works like in v0.1.10:
![image](https://user-images.githubusercontent.com/56601352/190345568-d2d7805d-c16b-4442-b245-e2a56c19fac7.png)

### What do you see instead?

![image](https://user-images.githubusercontent.com/56601352/190345900-1915a672-6db3-467c-86f3-7998078fb15c.png)

TypeError: spawn is not a function. (In 'spawn("echo", ["test"])', 'spawn' is undefined)

### Additional information

When i try to do
```js
import * as a from 'bun-utilities/spawn';
console.log(a);
```

it returns `{}` but it should work: https://github.com/xHyroM/bun-utilities/blob/master/lib/utils/spawn.mjs

**Comment by xhyrom** [comment]
Not sure if its exports issue

**Comment by xhyrom** [comment]
also doesnt work on canary

**Comment by Jarred-Sumner** [comment]
This is NAPI specific
