### ISSUE TITLE
npm-like CLI options `--prefix` which allows us to set the project root outside the project directory

### ISSUE THREAD

**Issue by FlysoftBeta** [oven-sh/bun#12414]
### What is the problem this feature would solve?

I have a CLI tool that can be accessed by `bun run foo` under the project folder, however when I switch to a directory outside the project this command simply doesn't work. In npm I can `npm run foo --prefix /path/to/project`.

### What is the feature you are proposing to solve the problem?

Add similar CLI options that can set project root outside the project directory.

### What alternatives have you considered?

Use absolute path of the script: `bun run /path/to/project/foo.ts`

**Comment by Jarred-Sumner** [comment]
You can do `--cwd` to do the equivalent of `cd path/to/project && bun run foo`

```sh
bun --cwd=./path/to/project foo
```

**Comment by FlysoftBeta** [comment]
> You can do `--cwd` to do the equivalent of `cd path/to/project && bun run foo`
> 
> ```shell
> bun --cwd=./path/to/project foo
> ```

Hello, @Jarred-Sumner . Thanks for your help but that's probably unrelated to my issue.

Run script with `bun --cwd=./path/to/project foo` result in `process.cwd()` being changed to the project folder. What I want to do is to run script in a directory outside the project **and meanwhile, with current directory unchanged.**
