### ISSUE TITLE
[Windows] Bun build fails to resolve import | bun build crashes when invoked via cli 

### ISSUE THREAD

**Issue by mGranTY** [oven-sh/bun#12418]
### How can we reproduce the crash?

@Jarred-Sumner already has the repo, which is private.
maybe this is a duplicate of https://github.com/oven-sh/bun/issues/12344
build.ts
```ts
import * as fs from "fs";

const result = await Bun.build({
  entrypoints: ["src/app.ts"],
  minify: true,
  outdir: "dist",
  target: "bun",
  splitting: false,
  sourcemap: "external",
});

if (!result.success) {
  console.error("Build failed");
  console.timeEnd("Build");
  for (const message of result.logs) {
    console.error(message);
    process.exit(0);
  }
} else {
  console.info("Build Successful");
  fs.cpSync("assets", "dist/assets", { recursive: true });
  for (const message of result.logs) {
    console.info(message);
  }
}
```
results in:

 ```ts
 $ bun build.ts
Build failed
2 | import { Hono } from "hono";
                         ^
error: Could not resolve: "hono". Maybe you need to "bun install"?
    at api\src\app.ts:2:22
  ```
  
  and if i change the import, it does the same errors for the next import and so on...
  
  
  but if i run the same build via the cli using:
  
  ```ts
  bun build --entrypoints src/app.ts --outdir ./dist --target bun --sourcemap=external --minify
  ```
  
  bun crashes :(

### Relevant log output

```shell
PS api> bun build --entrypoints src/app.ts --outdir ./dist --target bun --sourcemap=external --minify
>>
============================================================
Bun v1.1.18 (5a0b9352) Windows x64
Args: "C:\Users\grant\.bun\bin\bun.exe" "build" "--entrypoints" "src/app.ts" "--outdir" "./dist" "--target" "bun" "--sourcemap=external" "--minify"
Features: dotenv tsconfig(2)
Elapsed: 22ms | User: 93ms | Sys: 15ms
RSS: 84.47MB | Peak: 84.60MB | Commit: 0.17GB | Faults: 20970

panic(thread 1296): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.18/wb15a0b935AgogggEwgv8ayuwia8t9hak2kiaw+qia+ii8ai3lia8sozV6l2jZk20kXA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 13664): integer overflow
 https://bun.report/1.1.18/wb15a0b935AgogggEwgv8ayuwia8t9haoouia8sozV4/ukXyt6yVw75kT8ouiZy5xkXA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 8112): integer overflow
 https://bun.report/1.1.18/wb15a0b935AgogggEwgv8ayuwia8t9hak2kiaoouia8sozVw75kT8ouiZy5xkXyt6yVA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 9940): integer overflow
 https://bun.report/1.1.18/wb15a0b935AgogggEwgv8ayuwia8t9hak2kiaoouia8sozV4/ukXyt6yVw75kT8ouiZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:5275`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L5275>): `transposeImport`
- [`js_parser.zig:17358`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17358>): `visitExprInOut`
- [`js_parser.zig:7724`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L7724>): `checkAndPrepare`
- [`js_parser.zig:17226`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17226>): `visitExprInOut`
- [`js_parser.zig:17281`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17281>): `visitExprInOut`
- [`js_parser.zig:22418`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L22418>): `visitStmts`
- [`array_list.zig:431`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/zig/lib/std/array_list.zig#L431>): `ensureTotalCapacity`
- [`js_ast.zig:479`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_ast.zig#L479>): `alloc`
- [`js_parser.zig:18053`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L18053>): `exprCanBeRemovedIfUnused`
- [`js_parser.zig:21646`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L21646>): `visitClass`

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/12344

**Comment by Jarred-Sumner** [comment]
We are trakcing this in https://github.com/oven-sh/bun/issues/12344
