### ISSUE TITLE
Error running in `alpine` Docker images on `amd64` machine

### ISSUE THREAD

**Issue by maximal** [oven-sh/bun#12415]
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 6.1.0-22-amd64 x86_64 unknown

### What steps can reproduce the bug?

I’m trying to run Bun inside my CI/CD Docker runners.

Basic image is `alpine`.

Basic packages are:
```
apk update  &&  apk upgrade &&  apk add --update --no-interactive curl bash git gcompat
```
`gcompat` here is for compatibility reasons to run `glibc`-based programs.

Installation:
```shell
$ curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
Manually add the directory to ~/.bashrc (or similar):
  export BUN_INSTALL="$HOME/.bun" 
  export PATH="$BUN_INSTALL/bin:$PATH" 
To get started, run: 
  bun --help 
```

### What is the expected behavior?

Bun runs as usual.

### What do you see instead?

Bun run:
```
$ ~/.bun/bin/bun  i
Error relocating /root/.bun/bin/bun: unsupported relocation type 37
Error relocating /root/.bun/bin/bun: unsupported relocation type 37
Error relocating /root/.bun/bin/bun: unsupported relocation type 37
```

### Additional information

I get this errors only when Docker runner is on `amd64 x86_64` machine. When the runner is on `aarch64` machine, Bun runs just fine (considering that `gcompat` package is installed inside the image).

**Comment by Jarred-Sumner** [comment]
We don't support musl yet (#918) 

I suggest using the Debian slim build in the meantime

**Comment by Satont** [comment]
Why closed as not planned?
