### ISSUE TITLE
Crash when defining nested merged namespace in TypeScript

### ISSUE THREAD

**Issue by axefrog** [oven-sh/bun#12425]
### How can we reproduce the crash?

This is the most minimal case I was able to produce that would cause the crash.
- If I move `Y` to the top scope, the crash doesn't happen.
- If I remove function `Y` to avoid the merging of the namespace, the crash doesn't happen.
- If I remove `Z` from `Y` (or change it to just a type definition), again preventing a merge, the crash doesn't happen.

```ts
// test.ts
namespace X {
  export function Y (): void {}
  export namespace Y {
    export const Z = 1;
  }
}
```

```sh
bun test.ts
```

### Relevant log output

```shell
============================================================
Bun v1.1.18 (5a0b9352) Windows x64
Args: "C:\Users\axefr\.bun\bin\bun.exe" "test.ts"
Features: jsc
Builtins: "bun:main"
Elapsed: 44ms | User: 15ms | Sys: 46ms
RSS: 98.08MB | Peak: 98.08MB | Commit: 0.14GB | Faults: 24169

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [AutoCommand]

**panic**: Internal assertion failure

- [`debug.zig:439`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/zig/lib/std/debug.zig#L439>): `panicExtra`
- [`bun.zig:3258`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.zig#L3258>): `assertionFailure`
- [`baby_list.zig:193`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/baby_list.zig#L193>): `list`
- [`js_parser.zig:10724`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L10724>): `parseStmt`
- [`js_parser.zig:12387`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L12387>): `parseStmtsUpTo`
- [`js_parser.zig:3390`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L3390>): `_parse`
- [`js_parser.zig:3253`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L3253>): `parse`
- [`bundler.zig:1442`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bundler.zig#L1442>): `parseMaybeReturnFileOnlyAllowSharedBuffer`
- [`module_loader.zig:1722`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/module_loader.zig#L1722>): `transpileSourceCode`
- [`module_loader.zig:2416`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/module_loader.zig#L2416>): `Bun__transpileFile`

**Comment by Jarred-Sumner** [comment]
@axefrog can you run bun upgrade —canary and try again? @paperdave may have already fixed this

**Comment by axefrog** [comment]
@Jarred-Sumner Tried it just now:

```
Bun Canary v1.1.18-canary.1 (c2a5451e) Windows x64
Args: "C:\Users\axefr\.bun\bin\bun.exe" "--watch" "./projects/app-server/source/entrypoint.ts"
Features: jsc transpiler_cache tsconfig(2)
Builtins: "bun:main"
Elapsed: 71ms | User: 15ms | Sys: 109ms
RSS: 118.21MB | Peak: 118.21MB | Commit: 0.18GB | Faults: 29097

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```
