### ISSUE TITLE
Bun Crash with Segmentation fault at address 0x200000001A

### ISSUE THREAD

**Issue by trylovetom** [oven-sh/bun#12422]
### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x200000001A

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`MarkedBlock.h:589`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69//build/bun/bun-webkit/include/JavaScriptCore/MarkedBlock.h#L589>): `WebCore::JSBufferList::visitChildren`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::SlotVisitor::drain(...)::$_0::operator()`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::SlotVisitor::drain`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::SlotVisitor::drainFromShared`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::SharedTaskFunctor<void (...)::$_1>::run`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::ParallelHelperPool::Thread::work`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(...)::$_0, void>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::wtfThreadEntryPoint`

**Comment by trylovetom** [comment]
on `docker pull oven/bun:1.1.18-alpine` and kubernete

**Comment by Jarred-Sumner** [comment]
Fixed by #12427

**Comment by trylovetom** [comment]
@Jarred-Sumner Wow! you are great!
