### ISSUE TITLE
[bun i] scripts in child workspaces pastes x2 "\node_modules" in resolved path. which is unwanted/bug behaviour

### ISSUE THREAD

**Issue by sequencerr** [oven-sh/bun#12438]
### What version of Bun is running?

1.1.18-canary.1+ee2561819

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

repro repo: https://github.com/sequencerr/bun-repro-workspaces/tree/postinstall
run - `bun i` in project root

p.s.: start of conversation https://discord.com/channels/876711213126520882/1149339379446325248/1259179223130837002

### What is the expected behavior?

to successfully run `node D:\***\bun-repro-postinstall\node_modules\puppeteer\lib\esm\puppeteer\node\cli.js ...` command in postinstall package.json script

### What do you see instead?

```
PS D:\***\bun-repro-postinstall> bun i
bun install v1.1.18-canary.1 (ee256181)
  ⚙️  asd [1/2] node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'D:\***\bun-repro-postinstall\node_modules\node_modules\puppeteer\lib\esm\puppeteer\node\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.0

error: postinstall script from "asd" exited with 1
```

**Comment by Razunter** [comment]
Hm... I have similar issue with bun v1.1.18 on Windows: `Cannot find module 'W:\W:\web\…`. Drive letter is added twice for some reason. No workspaces though.
