### ISSUE TITLE
Ability to set keepAliveTimeout in server created by "node:http" like in Nodejs.

### ISSUE THREAD

**Issue by phonezawphyo** [oven-sh/bun#12446]
### What is the problem this feature would solve?

AWS Application Load Balancer (ALB) has idle timeout (default 60s) property and it appears not to kill connections even if the target (Bun server) sent connection close signal.
When a client makes another HTTP request and ALB uses the connection already closed by Bun due to idle timeout (10s defined in [HttpContext.h HTTP_IDLE_TIMEOUT_S](https://github.com/oven-sh/bun/blob/9ae870546b5/packages/bun-uws/src/HttpContext.h#L45C22-L45C41)), ALB returns "502 Bad Gateway" error.

AWS described the issue [here](https://repost.aws/knowledge-center/elb-alb-troubleshoot-502-errors#:~:text=The%20target%20closed%20the%20connection%20with%20a%20TCP%20RST%20or%20a%20TCP%20FIN%20while%20the%20load%20balancer%20had%20an%20outstanding%20request%20to%20the%20target).
It is reported [here](https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/) as well.

### What is the feature you are proposing to solve the problem?

To solve this problem, idleTimeout of ALB needs to be lower than that of Bun server. 
For that, we need the ability to set idle timeout on Bun server. 
In Nodejs, it is set as [keepAliveTimeout](https://nodejs.org/api/http.html#serverkeepalivetimeout) in "http" module. 
We need a similar configuration in "node:http" module in Bun.

Specifically, we need the ability to override the default [HTTP_IDLE_TIMEOUT_S](https://github.com/oven-sh/bun/blob/9ae870546b5/packages/bun-uws/src/HttpContext.h#L45C22-L45C41) with keepAliveTimeout.

### What alternatives have you considered?

I can lower ALB idleTimeout to 8~9s and alleviate this problem but the ideal solution is to have it at 60s and Bun server.keepAliveTimeout > 60s because we have some requests that legitimately require more than 10s process for certain scenarios and if the socket idle time is 10s, it results in timeout error on ALB (504 Gateway Timeout).

**Comment by cirospaciari** [comment]
If you are using `Bun.serve` you can use `idleTimeout` and if you are using http/https Server you can use `server.setTimeout(12000)`;

```js
Bun.serve({
 idleTimeout: 120,
 fetch(req){
    ....
 }
});
```

in this cases would set to 2 min you can use 0 to disable.

**Comment by phonezawphyo** [comment]
Thank you!
