### ISSUE TITLE
Bundows 1.1.18 crash bun build --compile --minify

### ISSUE THREAD

**Issue by Ivan-Baranov** [oven-sh/bun#12448]
### How can we reproduce the crash?

bun 1.1.18: `bun build --compile` -- build ok
bun 1.1.18: `bun build --compile --minify` -- build error

bun 1.1.17: `bun build --compile` -- build ok
bun 1.1.17: `bun build --compile --minify` -- build ok

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:5275`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L5275>): `transposeImport`
- [`js_parser.zig:17358`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17358>): `visitExprInOut`
- [`js_parser.zig:7724`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L7724>): `checkAndPrepare`
- [`js_parser.zig:7724`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L7724>): `checkAndPrepare`
- [`js_parser.zig:17281`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17281>): `visitExprInOut`
- [`js_parser.zig:22418`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L22418>): `visitStmts`
- [`js_parser.zig:20307`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L20307>): `visitDecls`
- [`js_parser.zig:19190`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L19190>): `visitAndAppendStmt`
- [`js_ast.zig:479`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_ast.zig#L479>): `alloc`
- [`js_parser.zig:20307`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L20307>): `visitDecls`

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/12344

**Comment by Jarred-Sumner** [comment]
We are tracking this in https://github.com/oven-sh/bun/issues/12344
