### ISSUE TITLE
url.origin does not have protocol

### ISSUE THREAD

**Issue by fabiancook** [oven-sh/bun#1244]
### Version

0.1.11

### Platform

Darwin Mac-mini.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

Run:

```javascript
const url = new URL(
    "https://html.spec.whatwg.org/"
);
const {
    origin,
    host,
    hostname
} = url;

console.log({
    string: url.toString(),
    origin,
    host,
    hostname
});

equals(hostname, "html.spec.whatwg.org");
equals(host, "html.spec.whatwg.org");
equals(origin, "https://html.spec.whatwg.org");

function equals(left, right) {
    ok(left === right, `Expected "${left}" to equal "${right}"`)
}

function ok(value, message) {
    if (!value) throw new Error(message)
}
```

### How often does it reproduce? Is there a required condition?

No required condition

### What is the expected behavior?

For the above script to run and output:

```
{ string: "https://html.spec.whatwg.org/", origin: "https://html.spec.whatwg.org", host: "html.spec.whatwg.org", hostname: "html.spec.whatwg.org" }
```

In node the output is:

```
{
  string: 'https://html.spec.whatwg.org/',
  origin: 'https://html.spec.whatwg.org',
  host: 'html.spec.whatwg.org',
  hostname: 'html.spec.whatwg.org'
}
```

And deno

```
{
  string: "https://html.spec.whatwg.org/",
  origin: "https://html.spec.whatwg.org",
  host: "html.spec.whatwg.org",
  hostname: "html.spec.whatwg.org"
}

```

### What do you see instead?

```
{ string: "https://html.spec.whatwg.org/", origin: "html.spec.whatwg.org", host: "html.spec.whatwg.org", hostname: "html.spec.whatwg.org" }
21 | function equals(left, right) {
22 |     ok(left === right, `Expected "${left}" to equal "${right}"`)
23 | }
24 | 
25 | function ok(value, message) {
26 |     if (!value) throw new Error(message)
                          ^
error: Expected "html.spec.whatwg.org" to equal "https://html.spec.whatwg.org"
      at ok (/Users/fabiancook/src/virtualstate/navigation/url.js:26:22)
      at equals (/Users/fabiancook/src/virtualstate/navigation/url.js:22:4)
      at /Users/fabiancook/src/virtualstate/navigation/url.js:19:0

```

**Comment by fabiancook** [comment]
I had a good look through url.zig and it looks like there everything is as expected. 

`origin` should be `base[0..offset]`, meaning it must start with the same as `href`:

https://github.com/oven-sh/bun/blob/c3bf97002d6f0b117060dabf2aa281eedd85b7fd/src/url.zig#L212
https://github.com/oven-sh/bun/blob/c3bf97002d6f0b117060dabf2aa281eedd85b7fd/src/url.zig#L235 

Looking at:

```javascript
const url = new URL(
    "https://html.spec.whatwg.org:90/test"
);
const {
    origin,
    host,
    hostname,
    protocol,
    href
} = url;
```

```
{ string: "https://html.spec.whatwg.org:90/test", origin: "html.spec.whatwg.org:90", host: "html.spec.whatwg.org:90", hostname: "html.spec.whatwg.org", protocol: "https:", href: "https://html.spec.whatwg.org:90/test" }
```

`href` definitely has protocol and all. 

I figured then that it could be a mapping between js land and zig land... not sure if this is the exact spot, but, it seems like the same problem: 

https://github.com/oven-sh/bun/blob/c3bf97002d6f0b117060dabf2aa281eedd85b7fd/src/bun.js/bindings/URLDecomposition.cpp#L32-L35

Notice in the above log we get `hostname` + `port`, I would expect `origin` to also have `protocol`

**Comment by Jarred-Sumner** [comment]
> Notice in the above log we get hostname + port, I would expect origin to also have protocol

Yep, that's the bug. Thank you.

When I ported the `URL` object from WebKit (`url.zig` is used elsewhere but is not exposed to JS), made a mistake

This is WebKit's implementation of that function:
```
String URLDecomposition::origin() const
{
    return SecurityOrigin::create(fullURL())->toString();
}
```

`SecurityOrigin` doesn't exist in Bun so I had to modify it
