### ISSUE TITLE
Segfault error

### ISSUE THREAD

**Issue by miguelvictor** [oven-sh/bun#12455]
### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x000000B0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`http.zig:2999`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L2999>): `src.http.closeAndFail__anon_149990`
- [`http.zig:1139`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L1139>): `src.deps.uws.NewSocketHandler`
- [`socket.c:199`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/socket.c#L199>): `us_socket_close`
- [`loop.c:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/loop.c#L0>): `us_loop_run_bun_tick`
- [`uws.zig:1283`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/uws.zig#L1283>): `src.http.HTTPThread.processEvents`
- [`http.zig:814`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L814>): `Thread.PosixThreadImpl.spawn__anon_136440.Instance.entryFn`
- `??`

**Comment by cirospaciari** [comment]
Fixed in canary v1.1.22 if is happening after `bun upgrade --canary` feel free to reopen
