### ISSUE TITLE
bun: symbol lookup error: /node_modules/@newrelic/native-metrics/prebuilds/linux-x64/@newrelic+native-metrics.abi115.uv1.glibc.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by monkfromearth** [oven-sh/bun#12453]
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 6.8.0-36-generic x86_64 x86_64

### What steps can reproduce the bug?

Installed `newrelic` and add it using `import` on top of the main file.

**Comment by Jarred-Sumner** [comment]
Duplicate of #4290

**Comment by Jarred-Sumner** [comment]
Please follow along in #4290
