### ISSUE TITLE
"bunx jsr add ___" throws "error: Script not found "jsr""

### ISSUE THREAD

**Issue by MarArMar** [oven-sh/bun#12465]
### What version of Bun is running?

❯ bun --revision 1.1.18+5a0b93523

### What platform is your computer?

Linux 6.5.0-10043-tuxedo x86_64 x86_64

### What steps can reproduce the bug?

❯ bun upgrade
Congrats! You're already on the latest version of Bun (which is v1.1.18)
❯ bunx jsr add @ryoppippi/unplugin-typia
error: Script not found "jsr"

### What is the expected behavior?

bun would install the dependency

As it seems implied in documentations : 
https://github.com/ryoppippi/unplugin-typia/issues/170
https://github.com/oven-sh/bun/discussions/11897
https://typia.io/docs/setup/#unplugin-typia => Bun tab

### What do you see instead?

error: Script not found "jsr"

**Comment by Jarred-Sumner** [comment]
It sounds like `bunx` doesn't realize it's `bunx` and not `bun`. I suggest either reinstalling bun via `curl https://bun.sh/install | bash` or using `bun x jsr` to avoid this
