### ISSUE TITLE
Crash: bun --hot 

### ISSUE THREAD

**Issue by aymammeri** [oven-sh/bun#12462]
### How can we reproduce the crash?

Cmd + s multiple times using bun --hot

### Relevant log output

============================================================
Bun v1.1.18 (5a0b9352) macOS x64
macOS v12.7.5
Args: "bun" "--hot" "src/server.ts"
Features: jsc dotenv(2) http_server(2) transpiler_cache(45) tsconfig(10) 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:http" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" 
Elapsed: 976282ms | User: 6483ms | Sys: 1730ms
RSS: 0.33GB | Peak: 0.33GB | Commit: 0.45GB | Faults: 1

panic: Illegal instruction at address 0x10AF2CA68
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on macos x86_64 [RunCommand]

Illegal instruction at address 0x110D42A68

- *2 unknown/js code*
- `bmalloc_heap_config_specialized_try_deallocate_not_small_exclusive_segregated`
- `void JSC::MarkedBlock::Handle::specializedSweep<true, (...)1, (...)1, (...)1, (...)0, (...)1, (...)1, JSC::IsoInlinedHeapCellType<JSC::JSString>::DestroyFunc>(...)::'lambda'(...)::operator()`
- `void JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::IsoInlinedHeapCellType<JSC::JSString>::DestroyFunc>`
- `JSC::IsoInlinedHeapCellType<JSC::JSString>::finishSweep`
- `JSC::MarkedBlock::Handle::sweep`
- `JSC::LocalAllocator::tryAllocateIn`
- `JSC::LocalAllocator::allocateSlowCase`
- `JSC::JSString::create`

**Comment by dylan-conway** [comment]
Could you try this again with canary (`bun upgrade --canary`)? #12442 might've fixed this yesterday

**Comment by Jarred-Sumner** [comment]
Please leave a comment if you're still running into this issue on Bun v1.1.20 or later and we'll re-open
