### ISSUE TITLE
TypeScript module resolution cannot find module "*.mjs" 

### ISSUE THREAD

**Issue by brettwillis** [oven-sh/bun#12471]
### What version of Bun is running?

1.1.18

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

In an ESM TypeScript project using `.mts` files, TypeScript enforces import extensions to be `*.mjs`. However Bun seemingly cannot resolve `*.mjs` import paths to the `*.mts` files.

E.g.

```ts
// index.mts
import { app } from './app.mjs';
app.start();
```

```ts
// app.mts
export const app = // ...
```

### What is the expected behavior?

Bun should resolve the `./app.mjs` import into the `./app.mts` file like TypeScript and other loaders.

### What do you see instead?

`error: Cannot find module "./app.mjs" from "<redacted>/index.mts"`

**Comment by mangs** [comment]
(if using Bun) FYI if you set `"module": "Preserve" in your `tsconfig.json`, you can import `.mts` files directly without needing to write the transpiled file extension

**Comment by brettwillis** [comment]
v1.1.21 works great now, thanks!
