### ISSUE TITLE
crash when just doing raw SQL calls to local postgres instance

### ISSUE THREAD

**Issue by capaj** [oven-sh/bun#12482]
### How can we reproduce the crash?

not sure.
In my script I was basically just doing this:
```ts
import postgres from 'postgres'
const sql = postgres()

// lot more sql calls before
await  sql`update addresses set address='1234 Fake Street'`
```

I have it built with Bun.build() to a JS file

### Relevant log output

```shell
============================================================
Bun v1.1.18 (5a0b9352) Linux x64
Linux Kernel v6.8.0 | glibc v2.39
Args: "/home/ubuntu/.bun/bin/bun" "build/transformDb.js"
Features: jsc dotenv tsconfig 
Builtins: "bun:main" "node:buffer" "node:crypto" "node:fs" "node:net" "node:os" "node:perf_hooks" "node:stream" "node:string_decoder" "node:tls" "node:util/types" 
Elapsed: 482969ms | User: 100ms | Sys: 35ms
RSS: 1.07GB | Peak: 60.54MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`StringImpl.h:1155`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L1155>): `Bun::formatStackTrace`
- [`ZigGlobalObject.cpp:569`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/bindings/ZigGlobalObject.cpp#L569>): `computeErrorInfoWithoutPrepareStackTrace`
- [`ZigGlobalObject.cpp:661`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun.js/bindings/ZigGlobalObject.cpp#L661>): `computeErrorInfoWrapper`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69//build/bun/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::ErrorInstance::computeErrorInfo`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

**Comment by Jarred-Sumner** [comment]
This bug was fixed around Bun v1.1.25 or so, when we fixed a crash that could occur while printing stack traces for errors
