### ISSUE TITLE
Broken enums inside namespace

### ISSUE THREAD

**Issue by matej21** [oven-sh/bun#12516]
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

define and access enum inside namespace

```ts
namespace Foo {
	export enum Bar {
		one = 'one',
	}
}

console.log(Foo.Bar)
```

### What is the expected behavior?

output:
```
{
  one: "one",
}
```

transpiled code:
```js
// foo.ts
var Foo;
((Foo) => {
  let Bar;
  ((Bar2) => {
    Bar2["one"] = "one";
  })(Bar = Foo.Bar ||= {});
})(Foo ||= {});
console.log(Foo.Bar);
```

### What do you see instead?

output:
```
{
  Bar: {
    one: "one",
  },
}
```

transpiled code:
```js
// foo.ts
var Foo;
((Foo) => {
  let Bar;
  ((Bar2) => {
    Bar2["one"] = "one";
  })(Bar = Foo.Bar ||= {});
})(Foo ||= {});
console.log(Foo); // <--- missing Foo.Bar
```

**Comment by Jarred-Sumner** [comment]
This is fixed in the canary build of Bun

to upgrade, run 
```
bun upgrade --canary
```
