### ISSUE TITLE
Bun segmentation fault (running a honojs web app)

### ISSUE THREAD

**Issue by szabbbbu** [oven-sh/bun#12513]
### How can we reproduce the crash?

I'm running a honojs web app with these dependencies: 

the code is private so im not sure what else i should add, I will check this ticket if there are questions.

```json

{
  "name": "studentsite",
  "scripts": {
    "dev": "NODE_ENV=development bun run --hot src/index.tsx"
  },
  "dependencies": {
    "drizzle-orm": "^0.31.2",
    "hono": "^4.4.8",
    "mysql2": "^3.10.2"
  },
  "devDependencies": {
    "@types/bun": "latest",
    "drizzle-kit": "^0.22.8"
  }
}

```

[package.json](https://github.com/user-attachments/files/16177982/package.json)

### Relevant log output

```shell
============================================================
Bun v1.1.18 (5a0b9352) macOS Silicon
macOS v14.4.1
Args: "bun" "run" "--hot" "src/index.tsx"
Features: jsc dotenv http_server transpiler_cache(355) tsconfig 
Builtins: "bun:main" "node:buffer" "node:crypto" "node:events" "node:net" "node:stream" "node:string_decoder" "node:timers" "node:tls" "node:url" "node:util" "node:util/types" 
Elapsed: 7298581ms | User: 29337ms | Sys: 5533ms
RSS: 1.36GB | Peak: 1.36GB | Commit: 0.02ZB | Faults: 72

panic: Segmentation fault at address 0x2EC88000000
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.18/Mr15a0b935AioghgF__mv8tRuygsPmkixLmnqxLu67wL+35zL+im5M26lzIA24uBhgggg4D

error: script "dev" was terminated by signal SIGTRAP (Trace or breakpoint trap)
[1]    4376 trace trap  bun dev
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x4FBEC000000

- *2 unknown/js code*
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.js_parser.NewParser_`
- `src.runtime.Runtime.Imports.Iterator.next`
- `src.js_parser.NewParser_`
- `src.string_mutable.MutableString.ensureValidIdentifier`
- `Bun__DNSResolver__lookupService`

**Comment by Jarred-Sumner** [comment]
Likely fixed by #11568, please run bun upgrade --canary  and leave a comment if you’re still running into this
