### ISSUE TITLE
Allow `--conditions=browser` for `bun test`

### ISSUE THREAD

**Issue by mProjectsCode** [oven-sh/bun#12545]
### What is the problem this feature would solve?

When running test using Svelte 5, bun will always import Sveltes server code since it prefers the export condition `default` over `brower`.

### What is the feature you are proposing to solve the problem?

Allow the use of `--conditions=browser`, like it already works for `bun run` to prefer other export conditions.

**Comment by sameer-dudeja** [comment]
Hey, I would like to work on this but lack the knowledge know where to or how to start. Can you guide me a little in the right direction, if that's okay

**Comment by mProjectsCode** [comment]
I currently have to patch the Svelte 5 `package.json` every time to remove the export conditions for Svelte SSR to be able to test my client-side code with HappyDOM.
