### ISSUE TITLE
Failed to link jest/storybook: EBUSY

### ISSUE THREAD

**Issue by sburgpit** [oven-sh/bun#12541]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 (Windows 11)

### What steps can reproduce the bug?

Do `bun i` in app with jest dependency to get `Failed to link jest: EBUSY`
Do `bun i` when storybook running to get `Failed to link storybook: EBUSY`

### What is the expected behavior?

The packages to be installed

### What do you see instead?

Failed to link jest/storybook: EBUSY

**Comment by caioedut** [comment]
Same here using package "tsx"

**Comment by crazytweeks** [comment]
#12440 Duplicate issue

**Comment by dylan-conway** [comment]
Fixed in #13575 and will be included in bun v1.1.27. You can try the fix now with canary (bun upgrade --canary)
