### ISSUE TITLE
[Windows] Integer overflow on bun build

### ISSUE THREAD

**Issue by Araxeus** [oven-sh/bun#12547]
### How can we reproduce the crash?

I don't know, it suddenly started happening on my local Windows machine after upgrading to bun v1.1.20, I tried downgrading, but it still kept happening.

This is happening on a server that is deployed on a remote linux instance, and it builds fine there, the crash only ocurrs locally

### Relevant log output

```shell
Bun v1.1.18 (5a0b9352) Windows x64
Args: "C:\Users\Araxeus\.bun\bin\bun.exe" "./build.ts"
Features: jsc dotenv external tsconfig_paths(2) tsconfig(5)
Builtins: "bun:main"
Elapsed: 38ms | User: 15ms | Sys: 78ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.23GB | Faults: 34100

panic(thread 11336): integer overflow
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [AutoCommand]

**panic**: integer overflow

- [`js_parser.zig:5275`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L5275>): `transposeImport`
- [`js_parser.zig:17358`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L17358>): `visitExprInOut`
- [`js_parser.zig:7474`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L7474>): `visitRightAndFinish`
- [`js_parser.zig:16925`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L16925>): `visitExprInOut`
- [`js_parser.zig:7579`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L7579>): `visitRightAndFinish`
- [`js_parser.zig:16925`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L16925>): `visitExprInOut`
- [`js_parser.zig:22418`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L22418>): `visitStmts`
- [`js_parser.zig:18053`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L18053>): `exprCanBeRemovedIfUnused`
- [`js_parser.zig:21646`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L21646>): `visitClass`
- [`js_parser.zig:20372`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/js_parser.zig#L20372>): `visitDecls`

**Comment by paperdave** [comment]
i've seen crashes like this in transposeImport before. it is almost certainly a result of my typescript Enum pr, as it enables a lot more constant folding within import expressions.

do you have a file you can share? otherwise, i'll still take a look through transposeImport to see if i can find it without a debugger.

**Comment by Araxeus** [comment]
The exact `Bun.build` this is happening on is:: https://github.com/Araxeus/opl-whatsapp-server/blob/4658fcb9c437a02e71fc55fc9e1f1e0aec5fd1b1/build.ts#L15-L23

i'm not sure which part exactly is causing this issue

**Comment by paperdave** [comment]
reproduces. the reason this doesnt happen on linux is because only the Windows build is compiled with safety checks like this integer underflow.

![image](https://github.com/user-attachments/assets/3f210347-9457-4500-9d6b-e710b86b4d19)
