### ISSUE TITLE
bun build with `--minify` breaks Elysia context

### ISSUE THREAD

**Issue by mavyfaby** [oven-sh/bun#12594]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 6.8.0-38-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a simple elysia app with GET method:

```ts
import Elysia from "elysia";

const app = new Elysia();

app.get("/", ({ query }) => {
  console.log("Query:", query);
});

app.listen(5000);
```

After that, build it with:

```sh
bun build --compile --minify src/test.ts --outfile test
```

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/3ed896cf-e8cf-4296-aa35-a7bb7c006776)

P.S: I used `bun test.ts` for this.

### What do you see instead?

`query` is undefined:

![image](https://github.com/user-attachments/assets/8c82d284-0851-44b6-8c2b-ad648908686a)

### Additional information

I ran it with:

```sh
curl http://127.0.0.1:5000\?bug\=bun
```

**Comment by paperdave** [comment]
bug in elysia

**Comment by paperdave** [comment]
See https://github.com/elysiajs/elysia/issues/724

![image](https://github.com/user-attachments/assets/c4888ea5-2a07-4e25-9e4e-0b52808954e4)
