### ISSUE TITLE
Segmentation fault at address 0x0

### ISSUE THREAD

**Issue by dancerinthedarkkk** [oven-sh/bun#12611]
### Relevant log output

```shell
[XRfBu2xXuA]: 2024-07-16T03:49:41.123Z 1 Inference started from subscription instance.llama3:latest.inference.
[XRfBu2xXuA]: 2024-07-16T03:49:43.655Z 1 Heartbeat
[XRfBu2xXuA]: 2024-07-16T03:49:46.655Z 1 Heartbeat
[XRfBu2xXuA]: 2024-07-16T03:49:49.655Z 1 Heartbeat
============================================================
Bun v1.1.18 (5a0b9352) Linux x64 (baseline)
WSL Kernel v5.15.153 | glibc v2.35
Args: "kuzco" "worker" "start"
Features: jsc Bun.stderr Bun.stdin(2) Bun.stdout fetch(65561) spawn(869895) WebSocket(11)
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:timers" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "node:diagnostics_channel"
Elapsed: 174148398ms | User: 14484640ms | Sys: 1147999ms
RSS: 0.02ZB | Peak: 9.24GB | Commit: 0.02ZB | Faults: 1270

panic: Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.18/B_15a0b935A+gigoQ2uw3mE+xyQqh4vpDku5swDkmvlwDk+6q/D209p/Ds8xxvDgjh0rDksllBA2AA

Illegal instruction
root@LAPTOP-G0N03UML:~/kuzco#
root@LAPTOP-G0N03UML:~/kuzco#
root@LAPTOP-G0N03UML:~/kuzco#
root@LAPTOP-G0N03UML:~/kuzco#
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on linux x86_64_baseline [_]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`http.zig:2097`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L2097>): `src.http.HTTPClientResult.Callback.New`
- [`http.zig:3145`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L3145>): `src.http.NewHTTPContext`
- [`uws.zig:951`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/uws.zig#L951>): `src.deps.uws.NewSocketHandler`
- [`context.c:534`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/context.c#L534>): `us_internal_socket_after_resolve`
- [`loop.c:198`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/loop.c#L198>): `us_loop_run_bun_tick`
- [`uws.zig:1283`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/deps/uws.zig#L1283>): `src.http.HTTPThread.processEvents`
- [`http.zig:814`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/http.zig#L814>): `Thread.PosixThreadImpl.spawn__anon_136392.Instance.entryFn`
- `??`

**Comment by cirospaciari** [comment]
Fixed in canary v1.1.22 if is happening after `bun upgrade --canary` feel free to reopen
