### ISSUE TITLE
No blog page for v1.1.20

### ISSUE THREAD

**Issue by tomByrer** [oven-sh/bun#12612]
### What steps can reproduce the bug?

https://bun.sh/blog/release-notes/bun-v1.1.20

### What is the expected behavior?

show info

### What do you see instead?

404: NOT_FOUND
Code: NOT_FOUND
ID: sfo1::59bhj-1721179542590-2f4fec3c6a60

### Additional information

Why are you using Vercel & not Bun?  ;)

**Comment by ghiscoding** [comment]
![image](https://github.com/user-attachments/assets/4fc09023-6b0f-4179-b04c-482c9e97de71)

**Comment by paperdave** [comment]
duplicate of #12590
