### ISSUE TITLE
🚀 Catalog to ensure version consistency in monorepos (similar to pnpm)

### ISSUE THREAD

**Issue by Yberion** [oven-sh/bun#12625]
### What is the problem this feature would solve?

Could help to ensure version consistency on buildable libs/apps in monorepos.

### What is the feature you are proposing to solve the problem?

Something similar to https://pnpm.io/catalogs

- https://github.com/pnpm/pnpm/pull/8122
- https://github.com/pnpm/pnpm/issues/7072

**Comment by jakeleventhal** [comment]
Duplicate of #4844

**Comment by coolcorexix** [comment]
I tried set `workspace:*` and it just does not work because this is only used to mention the sub-repo of monorepo not the used packages 
reference: https://bun.sh/docs/install/workspaces
