### ISSUE TITLE
Websocket client receiving 1006 after sending 4998 close code

### ISSUE THREAD

**Issue by bsansouci** [oven-sh/bun#12644]
### What version of Bun is running?

1.1.20

### What platform is your computer?

Linux 6.1.0-20-cloud-amd64 x86_64 unknown

### What steps can reproduce the bug?

First off, I am not sure this is a bug due to Bun. I only noticed it after switching over but it might've been around for a while under node. The behavior is that on the client I close the websocket with a specific error code 4998, on the bun server I receive 4998 in the onclose callback, but then on the client when the onclose gets finally called, I get 1006 which implies something happened and chrome decided to nuke the connection.
It's possible that there are a few edge cases where chrome or firefox throw 1006 and so I shouldn't rely on the error code, but I don't want to ignore this problem.

It's hard to repro because this only happens with our specific GCP setup. We have a load balancer in front of a compute engine instance. In the compute engine instance we just run bun that listens on a port. All of this is with TLS enabled. This doesn't repro when running bun locally without TLS.

**Comment by cirospaciari** [comment]
Thank for reporting, can you send me a example of the close payload/reason? If the reason/payload contains invalid UTF-8 this can happen. Maybe it can be an encoding bug or utf8 validation bug.

**Comment by cirospaciari** [comment]
In some case we are doing a fast shutdown on TLS that may is the cause of this, working in a fix and also working in a repro for this bug.
