### ISSUE TITLE
no idea ?

### ISSUE THREAD

**Issue by kamalkech** [oven-sh/bun#12646]
### Relevant log output

```shell
Bun v1.1.16 (bf7b327f) macOS Silicon
Args: "bun" "run" "--watch" "src/index.ts"
Features: jsc dotenv transpiler_cache(2) tsconfig_paths tsconfig(4) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:events" "node:fs" "node:module" "node:os" "node:path" "node:string_decode
r" "node:url" "node:util" "node:util/types" "node:worker_threads" 
Elapsed: 57ms | User: 640ms | Sys: 183ms
RSS: 59.16MB | Peak: 59.08MB | Commit: 1.07GB | Faults: 443

panic(main thread): Segmentation fault at address 0x1A
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/Mr1bf7b327AiogggH___mrgrqCu8jq1B2qgw9BmvyphCuix4cm9y+Nu448NA2A0B

--- Bun is auto-restarting due to crash [time: 1721329403158] ---
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x0000001A

- *3 unknown/js code*
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeCall`
- `JSC::JSMicrotask::~JSMicrotask`
- `JSC::VM::drainMicrotasks`
- `Bun::JSNextTickQueue::drain`
- `src.bun.js.api.brotli.BrotliEncoder.runFromJSThread`
- `src.output.printError__anon_113855`

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.21, thanks to @dylan-conway in #12800
