### ISSUE TITLE
run `bun build --minify .\src\a.ts --compile` failed

### ISSUE THREAD

**Issue by zzztttkkk** [oven-sh/bun#12657]
### How can we reproduce the crash?

but `bun build .\src\a.ts --compile` is ok

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:16274`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16274>): `visitExpr`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:17447`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17447>): `visitExprInOut`
- [`js_parser.zig:16977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16977>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:16245`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16245>): `visitStmtsAndPrependTempRefs`
- [`js_parser.zig:16313`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16313>): `visitFunc`
- [`js_parser.zig:20072`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L20072>): `visitAndAppendStmt`

**Comment by dylan-conway** [comment]
Thanks for the bug report. Could you share the contents of `a.ts`?

**Comment by hyoretsu** [comment]
@dylan-conway it happens on my project too. Here it is: https://github.com/midas-abgl/zaimu
`bun build --minify --outfile zaimu.js --target node ./main.ts`

**Comment by dylan-conway** [comment]
@hyoretsu Thanks for the repro.

The fix is in canary (`bun upgrade --canary`), and will be included in the next release.
