### ISSUE TITLE
Support `--env-file` to import custom `.env` files

### ISSUE THREAD

**Issue by danosiersonos** [oven-sh/bun#1265]
### What is the problem this feature will solve?

So for a lot of users/companies, they have multiple environments to deal with different datasets, connections, API, integrations, etc. Right now bun supports .env, .env.local, and .env.development (unless I'm mistaken).

It would be nice if bun could support more than just these 4, and support custom names as well. Staging, performance, testing, etc.

### What is the feature you are proposing to solve the problem?

I think that this could be solved multiple ways, likely.

I think you could support some type of map/fallback structure in the bunfig.toml.
Base the name of the .env file you load from a BUN_ENV, or to be more compatible with node, use NODE_ENV.

### What alternatives have you considered?

To force everyone to only ever have 3 env files ¯\_(ツ)_/¯

I'm no expert, I just thought this would be an excellent addition

**Comment by Jarred-Sumner** [comment]
The only reason Bun hardcodes it right now was due to prioritization constraints when implementing it - not philosophical 

A good question is how best to specify which .env files to load. An environment variable could work, with some constraint that the environment variable comes from the process instead of another .env 

A CLI flag would also make sense 

A bunfig option would sort of make sense except there's only one bunfig right now

**Comment by danosiersonos** [comment]
I assumed it was a prioritization thing, not a philosophical one 🙌. But always good to have something on the board rather than possibly lose track of it.

CLI flag would be good too.

Does the one bunfig prevent you from using it? Worried about it becoming massive?

**Comment by joshuat** [comment]
@Jarred-Sumner I think the defaults in place make a lot of sense, but I've always really liked the API from [node-foreman](https://github.com/strongloop/node-foreman/blob/782cf090d4917ff137e9980a36803b93df818b96/nf.js#L20) for .env loading. You're able to supply a comma-separated list of filenames which load in order similar to how Bun loads the current files in order.

**Comment by bertyhell** [comment]
An cli option would be nice. Something similar to the latest nodejs version:
```
node --env-file=env-folder/.env.production index.js
```

https://netbasal.com/node-js-v20-6-0-introducing-built-in-env-file-support-fb1b1de4f1fa

This would provide a good migration path for people using dotenv:
```
dotenv -e ./env-folder/.env.production node index.js 
```

eg:
```
bun --env-file=env-folder/.env.production index.ts
```

**Comment by webfussel** [comment]
I'd like to push this issue.
It's one of the reasons we can't use bun for development at the moment, as we have several .env files for different countries, languages and environments

**Comment by Cristiandi** [comment]
a CLI flag will be enough for most of us 😅 

> The only reason Bun hardcodes it right now was due to prioritization constraints when implementing it - not philosophical
> 
> A good question is how best to specify which .env files to load. An environment variable could work, with some constraint that the environment variable comes from the process instead of another .env
> 
> A CLI flag would also make sense
> 
> A bunfig option would sort of make sense except there's only one bunfig right now

**Comment by AlexisWalravens** [comment]
Yes, a CLI flag would do it, in my case I have a monorepo, and I have a single `.env` at the root of the project that all packages feed on.

Currently I'm using `dotenv -e ../../.env` before each script that needs it.

**Comment by DivMode** [comment]
This would be great, currently cannot access env variables in the root of a monorepo (turborepo). Is there a workaround to getting it to work with bun? dotenv doesnt work with bun

**Comment by Jarred-Sumner** [comment]
This has been implemented by @otgerrogla in https://github.com/oven-sh/bun/pull/7032
