### ISSUE TITLE
--packages external not working as expected

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12661]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 6.5.0-18-generic x86_64 x86_64

### What steps can reproduce the bug?

bun build index.ts --target bun --outdir dist --packages external
bun build eslint.config.js --packages external

### What do you see instead?

`error: ModuleNotFound resolving "external" (entry point)`
`error: Must use --outdir when specifying more than one entry point.`

**Comment by huseeiin** [comment]
also when using Bun.build:
```js
Bun.build({
  entrypoints: ["./eslint.config.js"],
  target: "bun",
  outdir: "dist",
  packages: "external",
});
```
its bundling all dependencies

**Comment by Jarred-Sumner** [comment]
This feature was added in Bun v1.1.21, which isn't released yet.
