### ISSUE TITLE
Building with --minify-syntax crashes with integer overflow

### ISSUE THREAD

**Issue by mkahvi** [oven-sh/bun#12672]
### How can we reproduce the crash?

Attempting to build the [PF1](<https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1>) system package for FVTT with syntax minification crashes.

Without syntax minification it works without issue. Other projects I've tried work fine with syntax minification.

Tested on Windows 11 in Power Shell.

```sh
 bun build .\pf1.mjs --outfile=dist/pf1.js --outdir=dist --sourcemap=linked --minify-whitespace --minify-syntax
 ```
 (realizing my command-line params are slightly wrong, but that user error is not influential for the integer overflow)

### Relevant log output

```shell
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "bun.exe" "build" ".\pf1.mjs" "--outfile=dist/pf1.js" "--outdir=dist" "--sourcemap=linked" "--minify-whitespace" "--minify-syntax"
Features: tsconfig_paths(2) tsconfig(2) 
Elapsed: 27ms | User: 15ms | Sys: 0ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.27GB | Faults: 35796

panic(thread 21612): integer overflow
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:16274`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16274>): `visitExpr`
- [`js_parser.zig:7504`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L7504>): `visitRightAndFinish`
- [`js_parser.zig:16978`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16978>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:21643`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L21643>): `visitSingleStmt`
- [`js_parser.zig:19783`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L19783>): `visitAndAppendStmt`
- [`js_parser.zig:22102`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L22102>): `visitStmts`

**Comment by mkahvi** [comment]
Got very similar stacktraces on [different project](<https://gitlab.com/koboldworks/pf1/little-helper>) and this is tied to using syntax minification.

---

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:17398`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17398>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:21643`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L21643>): `visitSingleStmt`
- [`js_parser.zig:19794`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L19794>): `visitAndAppendStmt`
- [`js_parser.zig:22102`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L22102>): `visitStmts`
- [`js_parser.zig:16245`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16245>): `visitStmtsAndPrependTempRefs`
- [`js_parser.zig:16313`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16313>): `visitFunc`



---

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:16905`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16905>): `visitExprInOut`
- [`js_parser.zig:17678`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17678>): `visitExprInOut`
- [`js_parser.zig:17447`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17447>): `visitExprInOut`
- [`js_parser.zig:17545`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17545>): `visitExprInOut`
- [`js_parser.zig:17678`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17678>): `visitExprInOut`
- [`js_parser.zig:17447`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17447>): `visitExprInOut`
- [`js_parser.zig:16977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16977>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`



---

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17678`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17678>): `visitExprInOut`
- [`js_parser.zig:17038`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17038>): `visitExprInOut`
- [`js_parser.zig:16977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16977>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:16245`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16245>): `visitStmtsAndPrependTempRefs`
- [`js_parser.zig:16313`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16313>): `visitFunc`
- [`js_parser.zig:20072`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L20072>): `visitAndAppendStmt`
- [`js_parser.zig:22102`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L22102>): `visitStmts`

**Comment by paperdave** [comment]
thanks for linking multiple samples to reproduce this.

**Comment by Jarred-Sumner** [comment]
Mysteriously doesn't crash in a debug build or release build on macOS
```
❯ bun build ./pf1.mjs --outfile=dist/pf1.js --outdir=dist --sourcemap=linked --minify-whitespace --minify-syntax


  pf1.js               1129.17 KB

  pf1.js.map           2831.76 KB

  pf1-ps5dm0a4.less    0.70 KB

[22ms] bundle 202 modules


❯ bun-debug build ./pf1.mjs --outfile=dist/pf1.js --outdir=dist --sourcemap=linked --minify-whitespace --minify-syntax


  pf1.js               1129.17 KB

  pf1.js.map           2831.76 KB

  pf1-ps5dm0a4.less    0.70 KB

[133ms] bundle 202 modules
```

**Comment by paperdave** [comment]
I have tested both reproductions, This is fixed on latest canary.

**Comment by mkahvi** [comment]
Confirmed this works without issue with the new 1.1.21 version. Thanks for fixing it! (or confirming it was fixed I guess?)
