### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by jprocks101** [oven-sh/bun#12673]
### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [RunCommand]

**panic**: cast causes pointer to be null

- [`bun.zig:266`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.zig#L266>): `cast`
- [`queue.h:33`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/src/queue.h#L33>): `uv__queue_empty`
- [`async.c:96`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/src/win/async.c#L96>): `uv__process_async_wakeup_req`
- [`core.c:657`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/src/win/core.c#L657>): `uv_run`
- [`event_loop.zig:1452`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/event_loop.zig#L1452>): `autoTickActive`
- [`bindings.cpp:4824`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/bindings/bindings.cpp#L4824>): `JSC__VM__holdAPILock`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/bindings/shimmer.zig#L197>): `cppFn`
- [`run_command.zig:1399`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/cli/run_command.zig#L1399>): `exec`
- [`cli.zig:1801`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/cli.zig#L1801>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/cli.zig#L62>): `start`

**Comment by Electroid** [comment]
Hi there, could you share some code or commands so we can try to reproduce your issue?

**Comment by Jarred-Sumner** [comment]
Closing due to lack of reproduction. If we find another issue with a similar stacktrace we will link it
