### ISSUE TITLE
`bun build` inlines `process.env` when `--target` is set to `bun` is this intentional?

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12695]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 6.5.0-18-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
// file.js

console.log(process.env.HOME);
```
```
bun build file.js --target bun --outdir dist
```

### What is the expected behavior?

This can be extremely harmful if you have something like `const IS_PROD = process.env.NODE_ENV === 'production'` because its going to be transpiled to `const IS_PROD = false` by default

### Additional information

1. This doesn't happen when using `Bun.env` instead
1. This doesn't happen when you set `--target` to `node` or `browser` (or leave `--target` empty)

**Comment by RiskyMH** [comment]
Duplicate of #11191

**Comment by BadMachine** [comment]
When runnung
bun --env-file=.env build --env=inline --minify --target=bun src/main.ts --outfile dist/main.js

no env variables inlined in the built file
