### ISSUE TITLE
Segmentation fault at address 0x5

### ISSUE THREAD

**Issue by shimizu-izumi** [oven-sh/bun#12692]
### How can we reproduce the crash?

Execute `bun create t3-app@latest` with Bun 1.1.20 on Windows 11

### Relevant log output

```shell
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "bun" "C:\Users\Izumi\AppData\Local\Temp\bunx-2031881272-create-t3-app@latest\node_modules\create-t3-app\dist\index.js"
Features: jsc Bun.stdin(2) Bun.stdout fetch
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:events" "node:fs" "node:https" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types"
Elapsed: 15696ms | User: 15ms | Sys: 0ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.23GB | Faults: 44826
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:968`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L968>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`
- *3 unknown/js code*

**Comment by nektro** [comment]
if this crash still reproduces for you on the latest version of Bun please let us know the steps you took and we'll reopen but for now we'll close. (you may need to run `bun upgrade`).

![Image](https://github.com/user-attachments/assets/2ed82500-9b45-4ff1-8f04-84f86880202f)
