### ISSUE TITLE
Promise pending /2 

### ISSUE THREAD

**Issue by carlopi** [oven-sh/bun#127]
I believe this to be somehow connected to https://github.com/Jarred-Sumner/bun/issues/122.

I am trying to run the Cheerp benchmarks in bun 0.0.72, but I am encountering some problems.

Take this zip, that contains a JS + a Wasm file: [cheerp-fannkuch.zip](https://github.com/Jarred-Sumner/bun/files/8283253/cheerp-fannkuch.zip)

```
$ bun run cheerp-v8-wasm_fannkuch.js
```
Just terminates without any feedback.
While
```
$ bun run cheerp-bun-wasm_fannkuch.js
Promise { <pending> }
```
For reference:
```
node cheerp-v8-wasm_fannkuch.js
deno run cheerp-bun-wasm_fannkuch.js (requires http-server serving from the same folder)
```
work (printing the result of some computations).

I am good with modifying the fetch mechanism / serving the wasm file locally / whatever is required, but I think both version should either give an error or work as intended.

**Comment by Jarred-Sumner** [comment]
I think it's three bugs:
1. Unhandled promise rejection is not propagating
2. fetch() might not work correctly for localhost
3. Task queue precedence causing WebAssembly.Instantiate to never run


Switching to fs.readFileSync & synchronous WebAssembly compilation gets further
```javascript
"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/ var aZ = Math.imul;
var a0 = Math.fround;
var oSlot = 0;
var nullArray = [null];
var nullObj = { d: nullArray, o: 0 };
function bo(p) {
  var b = null,
    f = "function";
  if (typeof fetch === f) {
    b = fetch(p).then((r) => r.arrayBuffer());
    console.log(b);
    return b;
  } else if (typeof require === f) {
    p = require("path").join(__dirname, p);
    b = new Promise((y, n) => {
      require("fs").readFile(p, (e, d) => {
        if (e) n(e);
        else y(d);
      });
    });
  } else
    b = new Promise((y, n) => {
      y(read(p, "binary"));
    });
  return b;
}
function aI() {
  throw new Error("Abort called");
}
function aA(j, k, i) {
  var h = 0,
    g = null;
  g = az(j, k, i);
  h = (i - 1) | 0;
  if ((j[(k + h) | 0] & 255) === 10) {
    g = g.substr(0, h);
    console.log(g);
    return;
  }
  console.log(g);
}
function az(q, r, p) {
  var j = 0,
    h = null,
    n = 0,
    o = 0,
    m = 0,
    g = 0,
    i = null;
  h = String();
  if ((p | 0) === 0) return h;
  o = p;
  n = 0;
  while (1) {
    j = q[(r + n) | 0] | 0;
    if ((j & 255) !== 0) {
      g = j & 255;
      if (j << 24 <= -16777216)
        if ((j & 255) < 192) {
          g = ((g & 63) + (m << 6)) | 0;
        } else if ((j & 255) < 224) {
          g &= 31;
        } else if ((j & 255) < 240) {
          g &= 15;
        } else {
          g &= 7;
        }
      o = (o - 1) | 0;
      n = (n + 1) | 0;
      a: {
        if ((o | 0) !== 0)
          if ((q[(r + n) | 0] & 192) === 128) {
            m = g;
            break a;
          }
        if (g >>> 0 < 65536) {
          m = g;
        } else {
          m = (g - 65536) | 0;
          i = String.fromCharCode(((m >>> 10) + 55296) | 0);
          h = h.concat(i);
          g = ((g & 1023) + 56320) | 0;
        }
        i = String.fromCharCode(g);
        h = h.concat(i);
      }
      if ((o | 0) !== 0) continue;
      return h;
    }
    break;
  }
  return h;
}
function aw(h, g) {
  aA(a, h >> 0, g);
}
function bi(bytes) {
  var pages = (bytes + 65535) >> 16;
  try {
    __asm.bl.grow(pages);
    bj(__asm.bl.buffer);
    return pages << 16;
  } catch (e) {
    return -1;
  }
}
var a = null,
  __asm = null,
  __heap = null;
function bk() {
  throw new Error("this should be unreachable");
}
bk.promise = await( new Promise((resolve, reject) => resolve(require("fs").readFileSync("./cheerp-v8-wasm_fannkuch.wasm")))
  .then((g) => g).then(buf => new WebAssembly.Module(buf)).then(g => new WebAssembly.Instance(g, { i: { aI: aI, aw: aw, bi: bi } }))
  .then((g) => {
      
    __asm = g.instance.exports;
    __heap = __asm.bl.buffer;
    bj(__heap);
    console.log("CIAO");
    __asm.aR();
  }));
function bj(g) {
  a = new Uint8Array(g);
}
```

**Comment by carlopi** [comment]
Then it's just a matter of using this:
[cheerp-bun-instance-wasm_fannkuch.zip](https://github.com/Jarred-Sumner/bun/files/8284068/cheerp-bun-instance-wasm_fannkuch.zip) (coupled with the previous Wasm file) and it works.
(fix is basically moving ``__asm = g.instance.exports`` to ``__asm = g.exports`` since Instance has a different interface)

**Comment by Jarred-Sumner** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/709451/158796774-2e2e95d2-5922-453a-89c5-38914a0ca427.png">
i have no idea what this means but here you go

**Comment by Jarred-Sumner** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/709451/158796944-8d8b457d-7843-49bb-abbd-d64154b88acf.png">

i think JSC's wasm is a little slower than v8's

it also doesn't support SIMD yet

**Comment by carlopi** [comment]
Meaning of the prints is basically pointless, there are a bunch of programs (.js + .wasm files) generated and then used to benchmark Emscripten and Cheerp. Currently the benchmarks are run on v8 and spidermonkey (+ sometimes on node / deno), and JSC somehow was never tested, I was looking at bun to enable it.

Here performances would be bounded by the underlying engine, so I expect that depending on the test there will be swings in one direction or the other, but it's still interesting (to me working on Cheerp at least, possibly also to the relative engines team if there are clear outliers).

Still I think it might be of relevance, and I was thinking of publishing the commented benchmark at some point. (probably I would wait for Instantiate to be fixed plus depending on the timeline and what you prefer for bun to be public).

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago
