### ISSUE TITLE
Bun install not detecting local pakages in workspace.

### ISSUE THREAD

**Issue by juancolson** [oven-sh/bun#12708]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

package.json
```json
{
	"name": "novels",
	"private": "true",
	"module": "index.ts",
	"type": "module",
	"workspaces": [
		"packages/prisma",
		"packages/mega",
		"packages/imagekit",
		"packages/constants"
	],
}
```
packages/prisma/package.json
```json
{
	"name": "prisma_local",
	"module": "index.ts",
	"type": "module",
	"version": "0.0.3",
	"devDependencies": {
		"@types/bun": "latest",
		"prisma": "^5.17.0"
	},
	"peerDependencies": {
		"typescript": "^5.0.0"
	},
	"dependencies": {
		"@prisma/client": "^5.17.0",
		"constants_local": "^1.0.0"
	}
}
```
packages/mega/package.json
```json
{
	"name": "mega_local",
	"module": "index.ts",
	"version": "0.0.1",
	"type": "module",
	"devDependencies": {
		"@types/bun": "latest"
	},
	"peerDependencies": {
		"typescript": "^5.0.0",
		"prisma_local": "^0.0.1",
		"constants_local": "^1.0.0"
	},
	"dependencies": {
		"megajs": "1.1.4"
	}
}
```

### What is the expected behavior?

Bun install finds and install the local packages

### What do you see instead?

error: GET https://registry.npmjs.org/prisma_local - 404

### Additional information

It was working on v1.1.17. I upgraded after i got error
Bun v1.1.17 ([bb66bba](https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x0000001A

now I have different problem

**Comment by Jarred-Sumner** [comment]
@juancolson van you provide a complete reproduction? (zip folder with package.json’s where we can run bun install)

it would also be helpful if you could include the crash report link.

**Comment by juancolson** [comment]
I downgraded to 1.1.19 and it worked now.

**Comment by juancolson** [comment]
So this can probably be ignored.
