### ISSUE TITLE
fetch doesn't forward bodies correctly 

### ISSUE THREAD

**Issue by Flaque** [oven-sh/bun#12701]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Bun doesn't appear to be forwarding bodies through redirects in the same way node does. In this case, it happens when we have a vercel domain alias (sfcompute.dev).

Running:
```bash 
# Returns a 400, because the server didn't get the body
bun --print 'fetch("https://sfcompute.dev/cli/session", { body: JSON.stringify({ validation: 123 }), method: "POST" })'

# Returns a 200, because the body went through 
node --print 'fetch("https://sfcompute.dev/cli/session", { body: JSON.stringify({ validation: 123 }), method: "POST" }) '
```

In the node case, the server receives the body as expected. In the node case, the body is empty. 

### What is the expected behavior?

I would expect both node & bun to have the same result.

**Comment by monstermichl** [comment]
Could this be related to [this](https://github.com/honojs/hono/issues/3298) issue? I'm testing in a container with *oven/bun:latest*. Has your fix been released? I mean I can see that it has been merged [here](https://github.com/oven-sh/bun/pull/12698).
