### ISSUE TITLE
Unable to debug with Bun VSCode Extension on Windows

### ISSUE THREAD

**Issue by nolios** [oven-sh/bun#12735]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

On Windows 10, Install Bun VSCode extension and try to debug a TS file.

### What is the expected behavior?

TypeScript code should be run and debuggable.

### What do you see instead?

I see an error in the debug console

```javascript
Failed to start inspector:
 40 |       }
41 |     },
42 |     close: () => {
43 |       writer.close(), pendingMessages.length = 0;
44 |     }
45 | }, parseUrl = function(input) {
                           ^
TypeError: "ws+unix://C:\Users\[USER_NAME]\AppData\Local\Temp\fee8lxqt44n.sock?break=1" cannot be parsed as a URL.
      at internal:debugger:45:23
      at new Debugger (internal:debugger:124:14)
      at internal:debugger:100:13
```

### Additional information

[Similar issue that is closed](https://github.com/oven-sh/bun/issues/8250)

### Tried
@Electroid mentioned to try `bun upgrade --canary`, but the same problem persisted.

### Assumption
The URL format `ws+unix://` suggests it's trying to use a Unix socket, which is not directly compatible with Windows file paths.
>**Note:** I assume using WSL would fix this, but that is a boundary for companies that primarily use Windows for development. This leads to more complicated setups and being forced into WSL.

### Possible Solution (based on assumption)
If possible, maybe platform specific handling could be done such as:
- On Windows, Bun could use `ws://` instead of `ws+unix://`. 
- For WSL/Unix, `ws+unix://` could still be used.

**Comment by elemental-mind** [comment]
This is what I see once attached. It does not bind breakpoints: 
![image](https://github.com/user-attachments/assets/3c3f7a02-e459-4e97-bf24-b7592ea6a214)

**Comment by adarshmadrecha** [comment]
I am getting same error. 
I ran the file with VS Code Command `Bun: Debug File`

![image](https://github.com/user-attachments/assets/35a0d4ce-56db-40dd-9bf7-0da34c0e22f4)

**Comment by adarshmadrecha** [comment]
I think main issue which tracks this issue is - https://github.com/oven-sh/bun/issues/8851
Hence, this issue should be marked as duplicate and closed.

**Comment by elemental-mind** [comment]
@adarshmadrecha Good catch. Let's close this and unify the threads.

**Comment by nick4814** [comment]
Thanks @adarshmadrecha I did not see this before creating the issue. Will close this now.


Duplicate issue is [#8851](https://github.com/oven-sh/bun/issues/8851)

**Comment by tonka3000** [comment]
@Jarred-Sumner I replaced the `\\` with `/` (in `adapter.ts`, `debug.ts` and `signal.ts`) and URL parse error is gone e.g. instead of `ws+unix://C:\\Users\\myusername` it is now `ws+unix://C:/Users/myusername`.

The only problem which I'm not stuck is no permission error. It seems that the sock files get created, but no write/read permissions.

```
rejected promise not handled within 1 second: Error: listen EACCES: permission denied C:/Users/myusername/b/mysock_dyswppiw3gt.sock
extensionHostProcess.js:148
stack trace: Error: listen EACCES: permission denied C:/Users/myusername/b/mysock_dyswppiw3gt.sock
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2019:5)
    at new UnixSignal (c:\sandbox\bun\packages\bun-debug-adapter-protocol\src\debugger\signal.ts:41:18)
    at DebugAdapter.#launch (c:\sandbox\bun\packages\bun-debug-adapter-protocol\src\debugger\adapter.ts:493:20)
    at DebugAdapter.launch (c:\sandbox\bun\packages\bun-debug-adapter-protocol\src\debugger\adapter.ts:439:18)
    at DebugAdapter.Adapter.request (c:\sandbox\bun\packages\bun-debug-adapter-protocol\src\debugger\adapter.ts:350:21)
    at DebugAdapter.emit (c:\sandbox\bun\packages\bun-debug-adapter-protocol\src\debugger\adapter.ts:297:26)
    at FileDebugSession.handleMessage (c:\sandbox\bun\packages\bun-vscode\src\features\debug.ts:195:20)
```

Note to the stack trace: I hardcoded the prefix `C:/Users/myusername/b` to make sure that I have write/read permission on disk.

Any idea?
