### ISSUE TITLE
[crash] fs readdir crash

### ISSUE THREAD

**Issue by vinhjaxt** [oven-sh/bun#12742]
### How can we reproduce the crash?

```
// bun --hot main.ts
import fs from 'node:fs/promises'

const folder = 'does-exists-folder' // yes the folder exists, can list by ls -al does-exists-folder
await fs.readdir(folder, { recursive: true })
```

### Relevant log output

```shell
[preindex] processFile: ENOENT: No such file or directory
   errno: -2
 syscall: "stat"



============================================================
Bun v1.1.20 (ae194892) Linux x64 (baseline)
Linux Kernel v6.1.0 | glibc v2.39
CPU: sse42 popcnt avx avx2
Args: "bun" "--hot" "/preindex.ts"
Features: jsc fetch(6) shell(2) spawn 
Builtins: "bun:main" "node:fs/promises" 
Elapsed: 14385ms | User: 76ms | Sys: 45ms
RSS: 1.07GB | Peak: 94.53MB | Commit: 1.07GB | Faults: 3

panic(main thread): Segmentation fault at address 0x38
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.20/Ba1ae19489AigigG2q06mE+xpRsmml/C6g609C0k6piE4pm48Cwh998C6wsl3Cgt4j3Cy8wKA2AwD
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x00000038

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- [`unbounded_queue.zig:106`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/unbounded_queue.zig#L106>): `src.bun.js.event_loop.EventLoop.tick`
- [`javascript.zig:1010`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/javascript.zig#L1010>): `src.bun.js.javascript.OpaqueWrap__anon_51506__struct_81562.callback`
- [`HeapCellInlines.h:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66//build/bun/bun-webkit/include/JavaScriptCore/HeapCellInlines.h#L0>): `JSC__JSValue__createUninitializedUint8Array`
- [`interpreter.zig:1477`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/shell/interpreter.zig#L1477>): `src.shell.interpreter.Interpreter.initAndRunFromSource`
- [`cli.zig:2054`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/cli.zig#L2054>): `src.cli.Command.maybeOpenWithBunJS`
- [`cli.zig:1946`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/cli.zig#L1946>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`
- `??`

**Comment by ippsav** [comment]
I'm a bit confused when it comes to the logs, you're running `bun --hot main.ts` but the log mentions you're passing `--hot /preindex.ts` as args to bun ? am i missing something ?
