### ISSUE TITLE
bun.report link includes windows path separators

### ISSUE THREAD

**Issue by Araxeus** [oven-sh/bun#12747]
### What version of Bun is running?

1.1.21-canary.1+5a5f3d6b3

### What platform is your computer?

Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Crash on windows

### What is the expected behavior?

I get a link that i can click to open, i.e `https://bun.report/1.1.21/wa25a5f3d6AiogggDCqB/node.napi.glibc.nodesjZCqB/node.napi.glibc.node+jjCCqB/node.napi.glibc.nodeo/7Bw6sk0C0q+psB__A2AwK`

### What do you see instead?

A link with `\` in the middle instead of `/`, thus i can't click the full link because the terminal doesn't understand it
`https://bun.report/1.1.21/wa25a5f3d6AiogggDCqB\node.napi.glibc.nodesjZCqB\node.napi.glibc.node+jjCCqB\node.napi.glibc.nodeo/7Bw6sk0C0q+psB__A2AwK`

![image](https://github.com/user-attachments/assets/a8aefbe1-bce9-4957-a797-8a18656cbe81)

**Comment by paperdave** [comment]
the \ is coming from the filepath of a native library file `node.napi.glibc.node` but the slash is being included in this unfortunately

**Comment by Araxeus** [comment]
you could just bruteforce format before printing the link, replacing `\` with `/`
