### ISSUE TITLE
Running a binary from `bun bun src/index.ts` just spits out the source code

### ISSUE THREAD

**Issue by ThatOneCalculator** [oven-sh/bun#1274]
### Version

0.1.4

### Platform

`Linux cali 5.19.10-xanmod1-1-x64v2 #1 SMP Wed, 21 Sep 2022 17:59:40 +0000 x86_64 GNU/Linux`

### What steps will reproduce the bug?

- Test: `bun src/index.ts` works
- `bun bun src/index.ts`
- `./node_modules.bun` -> prints out source code instead of running

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Runs the program

### What do you see instead?

Prints the source code

**Comment by Jarred-Sumner** [comment]
This is intentional. You can run your file like normal. Running the .bun file prints out the original source. The bundles today are just dependencies.
