### ISSUE TITLE
nodejs incompatibility in toString()

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12749]
duplicate

**Comment by Electroid** [comment]
Duplicate of #8624

**Comment by Electroid** [comment]
This is a similar duplicate of the linked issue. Essentially, bun does not preserve the original content of `Function.toString()`, so it's showing a minified version. It's a known issue.

**Comment by huseeiin** [comment]
> This is a similar duplicate of the linked issue. Essentially, bun does not preserve the original content of `Function.toString()`, so it's showing a minified version. It's a known issue.

but in the second example. its node that is showing the minified version
