### ISSUE TITLE
There is no stack trace for the following errors

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#1275]
### What is the problem this feature will solve?

sometime is really hard to solve this js errors 

```
 SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.
 SyntaxError: Importing binding name 'jwt' is not found.
```

### What is the feature you are proposing to solve the problem?
Stack trace needed

**Comment by Jarred-Sumner** [comment]
Yeah, this is a JSC issue but Bun should patch it

**Comment by Jarred-Sumner** [comment]
No stack trace yet, but it will at least include the module specifier after the next JSC upgrade

https://github.com/oven-sh/WebKit/commit/134e3a7963e8425e45073e48db0181ebd9d0bd11
