### ISSUE TITLE
Bun build --packages=external doesn't work as noted in the docs.

### ISSUE THREAD

**Issue by deathlynocturnal** [oven-sh/bun#12768]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 5.15.0-50-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a project `bun init` and then install any package.
2. Create a `src/index.ts` file and write some code to import the new package alongside some code to call it.
3. Run `bun build src/index.ts --outDir ./dist --target=bun --format=esm --packages=external`
4. Notice that the dependency you imported is now compiled into your app, even though according to the docs it shouldn't do this.

### What is the expected behavior?

I would expect that the code would import the dependency separately in the built JS files.

### What do you see instead?

That the dependencies are still being concatenated into the output file, regardless of that setting.

### Additional information

If this is not a bug, then a workaround or something would be great, if possible.
Had to switch back to `tsc` in the meantime.

**Comment by zpix1** [comment]
This feature is not in 1.1.20 release, you can try canary build:

```
❯ bun upgrade --canary
Congrats! You're already on the latest canary build of Bun

To downgrade to the latest stable release, run bun upgrade --stable
❯ cat index.ts
import * as chalk from "chalk";

console.log(chalk);
❯ bun build index.ts --target=bun --format=esm --packages external
// @bun
// index.ts
import * as chalk from "chalk";
console.log(chalk);
```

 or wait until 1.1.21.
