### ISSUE TITLE
Passing Request to fetch in SvelteKit dev mode loses all headers and body information

### ISSUE THREAD

**Issue by nipatiitti** [oven-sh/bun#12764]
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 6.4.6-76060406-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a standard svelte-kit barebones project with `bun create svelte@latest`
2. Add a `+page.ts` file to `src/routes`
3. In the file put
```ts
export const load = async () => {
  const req = new Request("http://localhost:8080", {
    headers: {
      "test-header": "test-value",
    },
  })

  const res = await fetch(req)
}
```
4. Run `nc -l -p 8080` in bash
5. Run `bun --bun run dev` and open http://localhost:5173

### What is the expected behavior?

You should see in the netcat console:
```
GET / HTTP/1.1
test-header: test-value
Connection: keep-alive
User-Agent: Bun/1.1.18
Accept: */*
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
```

(The test-header: test-value, is passed along as it should)

### What do you see instead?

```
GET / HTTP/1.1
Connection: keep-alive
User-Agent: Bun/1.1.18
Accept: */*
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
```

(We lose the passed headers. If there were any body we would also lose that)

### Additional information

I checked #9846, #4718 and #10543 which are similar but they seem to have slightly different problems.

If you run the project without the `--bun` flag (so using node) everything works just fine.

If you check the `fetch` with lodash `isNative()` it returns false. This is because svelte-kit does this [here](https://github.com/sveltejs/kit/blob/d4e14071f3f4252b826971398ce650269308ba20/packages/kit/src/exports/vite/dev/index.js#L41-L50):

```js
const fetch = globalThis.fetch;
globalThis.fetch = (info, init) => {
	if (typeof info === 'string' && !SCHEME.test(info)) {
		throw new Error(
			`Cannot use relative URL (${info}) with global fetch — use \`event.fetch\` instead: https://kit.svelte.dev/docs/web-standards#fetch-apis`
		);
	}

	return fetch(info, init);
};
```

This shim somehow breaks things with bun but I don't see how as it works just fine in node :thinking:. If you add the `svelte-bun-adapter` library and build a production build of the project or just go to node_modules, comment out the shim and run `bun --bun run dev --force` to rebuild vite debs, the `isNative` returns true and everything works as it should.

Also if you replace 
```ts
const req = new Request("http://localhost:8080", {
  headers: {
    "test-header": "test-value",
  },
})

const res = await fetch(req)
```
with
```ts
const req = new Request("http://localhost:8080", {
  headers: {
    "test-header": "test-value",
  },
})

const res = await fetch(req.url, {
  headers: req.headers,
})
```

It works as it should, so this makes me think there is something funny going on with object references when passed multiple times.

**Comment by Jarred-Sumner** [comment]
Can you run `bun upgrade` and let us know if you're still running into this?

**Comment by nipatiitti** [comment]
`bun --version` is now 1.1.20 but seems to still be an issue 😕
![image](https://github.com/user-attachments/assets/e7cfe339-8c68-4896-9174-6db02da1792b)

With 
```ts
const res = await fetch(req.url, {
	headers: req.headers,
});
```
It works tho

**Comment by Bewinxed** [comment]
> Can you run `bun upgrade` and let us know if you're still running into this?

Still an issue, but if you create a request, then fetch it, it works.

Otherwise same issue.
