### ISSUE TITLE
Worked for 8 days and crash.

### ISSUE THREAD

**Issue by renat2985** [oven-sh/bun#12781]
### Relevant log output

Bun v1.1.20 (ae194892) Linux x64
Linux Kernel v5.4.0 | glibc v2.31
CPU: sse42 popcnt avx avx2
Features: jsc fetch(2) http_server 
Builtins: "bun:main" "bun:sqlite" 
Elapsed: 851894083ms | User: 1130625ms | Sys: 2819700ms
RSS: 1.07GB | Peak: 0.25GB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x2
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000002

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/ld-temp.o#L0>): `WTF::Unicode::convertReplacingInvalidSequences`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/ld-temp.o#L0>): `llint_relativePCBase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/ld-temp.o#L0>): `JSC::ClonedArguments::getOwnPropertySlot`
- [`JSCJSValueInlines.h:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66//build/bun/bun-webkit/include/JavaScriptCore/JSCJSValueInlines.h#L0>): `JSC__JSObject__getIndex`
- [`array_list.zig:1081`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/array_list.zig#L1081>): `src.bun.js.bindings.bindings.JSGlobalObject.throw__anon_123877`
- [`hashtable_policy.h:433`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66//usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/hashtable_policy.h#L433>): `uWS::TopicTree<uWS::TopicTreeMessage, uWS::TopicTreeBigMessage>::subscribe`
- [`uws.zig:1728`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/uws.zig#L1728>): `src.deps.uws.WebSocketBehavior.Wrap`
- [`basic_string.tcc:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66//usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.tcc#L0>): `uWS::InflationStream::inflate`

**Comment by cirospaciari** [comment]
Fixed in canary v1.1.22 if is happening after `bun upgrade --canary` feel free to reopen
