### ISSUE TITLE
bun crash

### ISSUE THREAD

**Issue by VinayTech3d** [oven-sh/bun#12807]
### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [AutoCommand]

**panic**: attempt to use null value

- [`javascript.zig:847`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/javascript.zig#L847>): `get`
- [`ZigGlobalObject.cpp:564`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/bindings/ZigGlobalObject.cpp#L564>): `computeErrorInfoWithoutPrepareStackTrace`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/bun/bun/build/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...),WTF::String,JSC::VM &,WTF::Vector<JSC::StackFrame,0,WTF::CrashOnOverflow,16,WTF::FastMalloc> &,unsigned int &,unsigned int &,WTF::String &,JSC::JSObject *>::call`
- [`utility:756`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/include/utility#L756>): `std::exchange`
- [`Heap.cpp:713`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/Heap.cpp#L713>): `JSC::Heap::finalizeMarkedUnconditionalFinalizers<JSC::ErrorInstance,JSC::IsoSubspace>::<lambda_1>::operator()`
- [`SubspaceInlines.h:65`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/SubspaceInlines.h#L65>): `JSC::Subspace::forEachPreciseAllocation`
- [`Heap.cpp:872`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/Heap.cpp#L872>): `JSC::Heap::removeDeadCompilerWorklistEntries`
- [`Heap.cpp:1378`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/Heap.cpp#L1378>): `JSC::Heap::runCurrentPhase`
- [`Heap.cpp:1299`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/Heap.cpp#L1299>): `JSC::Heap::collectInCollectorThread`
- [`AutomaticThread.cpp:226`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/WTF/wtf/AutomaticThread.cpp#L226>): `WTF::AutomaticThread::start::<lambda_0>::operator()`

**Comment by Jarred-Sumner** [comment]
@VinayTech3d can you give us some code to reproduce this? Would love to fix it but it's hard to see what happened here
