### ISSUE TITLE
WASM error reporting

### ISSUE THREAD

**Issue by KaffinPX** [oven-sh/bun#12817]
### What is the problem this feature would solve?

WASM crashes are too hard to debug rn, a stack trace would be helpful.

### What is the feature you are proposing to solve the problem?

Instead of WASM ([ wasm code ]) provide exact locations and traces like on Node.js.

<img width="296" alt="Screenshot 2024-07-25 at 16 47 25" src="https://github.com/user-attachments/assets/c2b8be18-f49a-4f12-92ae-57886df21a51">

**Comment by Jarred-Sumner** [comment]
Can you run `bun upgrade --canary` and see if it’s any better?

**Comment by KaffinPX** [comment]
<img width="260" alt="Screenshot 2024-07-26 at 17 19 09" src="https://github.com/user-attachments/assets/511b5a02-b2c0-481d-b545-4800bb89a2b6">

still seems to be missing traces but yea way better
