### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by FranzaLeny** [oven-sh/bun#12814]
### How can we reproduce the crash?

await Bun.build({
  entrypoints: ['./src/server.ts'],
  outdir: './build',
  target: 'bun',
  minify: {
      whitespace: true,
      identifiers: true,
      syntax: true,
  },
})

### Relevant log output

```shell
bun run build
$ bun --env-file=.env run src/build.ts
============================================================
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\xxxx\.bun\bin\bun.exe" "--env-file=.env" "run" "src/build.ts"
Features: jsc dotenv tsconfig_paths(2) tsconfig(2)
Builtins: "bun:main"
Elapsed: 104ms | User: 46ms | Sys: 78ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.30GB | Faults: 44176

panic(thread 10028): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.20/wr1ae19489AiogggDq+gqb8v9sa+hssayg9sa+hssaomysamq7sa8zp8V694tZktwuXA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

error: script "build" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [RunCommand]

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:16274`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16274>): `visitExpr`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:17447`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17447>): `visitExprInOut`
- [`js_parser.zig:17212`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17212>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:21643`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L21643>): `visitSingleStmt`
- [`js_parser.zig:19783`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L19783>): `visitAndAppendStmt`

**Comment by dylan-conway** [comment]
This is fixed in canary (`bun upgrade --canary`), and will be included in the next release
