### ISSUE TITLE
esbuild dependency is not executable when using Astro

### ISSUE THREAD

**Issue by ngryman** [oven-sh/bun#1281]
### Version

0.1.13

### Platform

Darwin [redacted] 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

```sh
$ npm create astro@latest
# skip installing dependencies

$ bun install
$ bun run dev

```

### How often does it reproduce? Is there a required condition?

Always reproducible.

### What is the expected behavior?

It should be able to execute `esbuild`.

### What do you see instead?

```sh
$ astro dev
  🚀  astro  v1.3.0 started in 44ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

The service was stopped: spawn /[redacted]/node_modules/vite/node_modules/esbuild-darwin-64/bin/esbuild EACCES
```

### Additional information

The executable permissions are not present:

```sh
$ ls -l node_modules/vite/node_modules/esbuild-darwin-64/bin/esbuild
Permissions Size User    Date Modified Name
.rw-r--r--  9.0M [redacted] 26 Sep 21:59  node_modules/vite/node_modules/esbuild-darwin-64/bin/esbuild
```

I'm not familiar with how `bun` dedupes dependencies, but it seems another hoisted version of `esbuild` exists, with the appropriate permissions:

```sh
$ ls -l node_modules/esbuild-darwin-64/bin/esbuild
.rwxr-xr-x 8.8M ngryman 26 Sep 22:28 node_modules/esbuild-darwin-64/bin/esbuild
```

But `vite` seems to use the deeply nested one.

In comparison, `pnpm` only has the hoisted `esbuild` version with the appropriate permissions.

**Comment by kirill-dev-pro** [comment]
Same issue. It happens when node modules are installed via bun. If modules installed with `npm i` projects starts ok with both mpn and bun
