### ISSUE TITLE
Crash on bun build. Works on 1.1.17

### ISSUE THREAD

**Issue by StefanFeederle** [oven-sh/bun#12849]
### How can we reproduce the crash?

  "scripts": {
    "bunbuild": "bun build ./src/index.ts --target=node --outfile=server.mjs --minify",
  },

### Relevant log output

```shell
PS C:\github\unified-data-server> bun run bunbuild
$ bun build ./src/index.ts --target=node --outfile=server.mjs --minify
============================================================
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\StefanFeederle\.bun\bin\bun.exe" "build" "./src/index.ts" "--target=node" "--outfile=server.mjs" "--minify"
Features: tsconfig(2) 
Elapsed: 16ms | User: 0ms | Sys: 0ms
RSS: 117.66MB | Peak: 117.66MB | Commit: 0.23GB | Faults: 29183

panic(thread 29656): integer overflow
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.20/wb1ae19489AgggggCq+gqb8v9sak1vsao49saomysayg9samlzsa8zp8Vwm6sT89wsZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 82816): integer overflow
 https://bun.report/1.1.20/wb1ae19489AgggggCq+gqb8v9sak1vsao49saomysayg9samlzsa8zp8Vwm6sT89wsZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 86132): integer overflow
 https://bun.report/1.1.20/wb1ae19489AgggggCq+gqb8v9sak1vsao49saomysayg9samlzsa8zp8Vwm6sT89wsZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

oh no: multiple threads are crashingpanic(thread 93132): integer overflow
 https://bun.report/1.1.20/wb1ae19489AgggggCq+gqb8v9sak1vsao49saomysayg9samlzsa8zp8Vwm6sT89wsZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

error: script "bunbuild" exited with code 3
PS C:\github\unified-data-server> bun --version
1.1.20
PS C:\github\unified-data-server> bun --version
1.1.17
PS C:\github\unified-data-server> bun run bunbuild
$ bun build ./src/index.ts --target=node --outfile=server.mjs --minify

  server.mjs  7586.62 KB

[396ms] bundle 3043 modules
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17545`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17545>): `visitExprInOut`
- [`js_parser.zig:17678`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17678>): `visitExprInOut`
- [`js_parser.zig:17447`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17447>): `visitExprInOut`
- [`js_parser.zig:16274`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16274>): `visitExpr`
- [`js_parser.zig:16977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16977>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:16245`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16245>): `visitStmtsAndPrependTempRefs`
- [`js_parser.zig:16313`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16313>): `visitFunc`

**Comment by dylan-conway** [comment]
The fix is in canary (`bun upgrade --canary`) and will be included in the next release. Closing as complete

**Comment by StefanFeederle** [comment]
Thank! Works again on 1.1.21
