### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12851]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Linux 6.5.0-18-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
console.log(eval('require("path");'));
```

### What is the expected behavior?

in node this works

### What do you see instead?

ReferenceError: Can't find variable: require

### Additional information

workaround
```js
eval('import("path").then((path) => console.log(path));');
```

**Comment by Aarav-Juneja** [comment]
Seems to be working when using `bun repl`.

**Comment by huseeiin** [comment]
> Seems to be working when using `bun repl`.

bun repl is currently bad and not representative of bun

**Comment by Jarred-Sumner** [comment]
It didn't detect this as a CommonJS module and it's a slippery slope reading `eval` strings at transpilation time

Is there a specific package this is breaking?
