### ISSUE TITLE
Support for private registry by reading .npmrc

### ISSUE THREAD

**Issue by itemsCenter** [oven-sh/bun#1287]
### What is the problem this feature will solve?

npm is configured by a .npmrc, but currently, bun seems to require the configuration to be duplicated to a bunfig.toml file.

### What is the feature you are proposing to solve the problem?

For bun install to support reading from the .npmrc file.

**Comment by MarkLyck** [comment]
I think this is a duplicate of: https://github.com/oven-sh/bun/issues/643 but yes, this is the only thing left preventing me from using bun as well 😞

**Comment by Electroid** [comment]
Yep, we're going to support this. Tracking in #643
