### ISSUE TITLE
Bun upgrade fails on Windows 11 for v1.1.21

### ISSUE THREAD

**Issue by deadcoder0904** [oven-sh/bun#12872]
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Install bun v1.1.20
2. Try `bun upgrade` & you'll see this error

```bash
example.com> bun upgrade
Bun v1.1.21 is out! You're on v1.1.20
Expand-Archive : A positional parameter cannot be found that accepts argument 'PC\AppData\Local\Temp\1.1.21'.
At line:1 char:47
+ ... lyContinue';Expand-Archive -Path bun.zip C:\Users\My PC\AppDat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Expand-Archive

error: Failed to verify Bun (code: FileNotFound))
```

### What is the expected behavior?

Upgrade bun to v1.1.21

**Comment by Jarred-Sumner** [comment]
do you by chance have a space character in your home folder?

**Comment by deadcoder0904** [comment]
Yep, exactly. Its my firstname & surname.

**Comment by deadcoder0904** [comment]
@Jarred-Sumner @paperdave this isn't fixed yet. i tried upgrading to v1.1.22 now.

**Comment by deadcoder0904** [comment]
Okay, you guys talked about it in the released notes but i think a note in the issue or PR rather than directly closing an issue is appreciated.

https://bun.sh/blog/bun-v1.1.22#bun-upgrade-on-windows-with-space-in-home-directory
