### ISSUE TITLE
Special characters are not supported after being compiled into an executable program

### ISSUE THREAD

**Issue by lvzhenbo** [oven-sh/bun#12887]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```js
import boxen from "boxen";

console.log(boxen("1"));

```
`bun build ./1.ts --compile --outfile outfile`

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/79b295b3-7232-4afc-9ab6-9522e34dfb8f)

### What do you see instead?

![image](https://github.com/user-attachments/assets/75dd49e0-4ab4-4107-8a2f-2554b2ea2471)

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.22
<img width="475" alt="image" src="https://github.com/user-attachments/assets/3997e5ee-40c8-4347-97ae-457e733dcbd4">
