### ISSUE TITLE
add Bun.buildSync

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12895]
### What is the problem this feature would solve?

like esbuild.buildSync, but for bun

### What is the feature you are proposing to solve the problem?

Bun.buildSync

**Comment by Electroid** [comment]
You already opened this issue.

**Comment by Electroid** [comment]
Duplicate of #12813

**Comment by huseeiin** [comment]
> You already opened this issue.

alzheimers :skull:
