### ISSUE TITLE
Circular array when ```new Array(n).fill([])```

### ISSUE THREAD

**Issue by mikelxk** [oven-sh/bun#1289]
### Version

0.1.13

### Platform

Linux *** 5.15.57.1-microsoft-standard-WSL2 #1 SMP Wed Jul 27 02:20:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```
let t = new Array(4).fill([])
console.log(t)
```
console output will be
```
[ [], [Circular], [Circular], [Circular] ]
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Output should be
```
[ [], [], [], [] ]
```

### What do you see instead?

```
[ [], [Circular], [Circular], [Circular] ]
```

**Comment by Jarred-Sumner** [comment]
The bug here is that `Circular` is currently a hash table of all visited values when it should perhaps be a little looser

Maybe it should reprint arrays & objects of primitive-only values
