### ISSUE TITLE
`bun run` npm env variables causing errors when script executes `npm --global`

### ISSUE THREAD

**Issue by bompus** [oven-sh/bun#129]
I believe that 4b36efd50ad27f7b390ca38b2f968e1dfcdbe4f1 caused any `bun run` script that executes the `npm --global` cli to stop functioning.

For what it's worth, I'm actually using pnpm as a node version manager, but I don't believe that is related after looking at the source code.

Success: curl -fsSL https://bun.sh/install | bash -s bun-v0.0.71
Failure: curl -fsSL https://bun.sh/install | bash -s bun-v0.0.72
Failure: curl -fsSL https://bun.sh/install | bash -s bun-v0.0.73

`package.json`:
```
"scripts": {
  "npmListGlobal": "npm ls --json --global",
  "npmListGlobalFix": "bash ./npmListGlobalFix.sh"
}
```

`bun run npmListGlobal`

To workaround this in the current version, 0.0.73, I had to create a bash script which unsets `npm_config_prefix` prior to running `npm ls --json --global` executed via `bun run npmListGlobalFix`

`npmListGlobalFix.sh`:
```
#!/bin/bash

# unset some variables that bun run sets improperly
unset npm_config_prefix
# unset npm_execpath # not necessary to unset, but this is incorrect

# to find what the correct values should be:
# export npm_config_prefix=$(npm config get prefix)
# export npm_execpath=$(which npm)

npm ls --json --global

```

**Comment by Jarred-Sumner** [comment]
Thanks for filing

It looks like npm expects a `lib` directory in `$npm_config_prefix/lib`

I have removed the code that sets `$npm_config_prefix` in d21cfe6202e8db8eed83d32198ee96bbeba585f8

Note that `$npm_execpath` is also set by yarn
```bash
❯ yarn run-bash
yarn run v1.22.17
warning package.json: No license field
$ bash
bash-5.1$ echo $npm_execpath
/opt/homebrew/lib/node_modules/yarn/bin/yarn.js
bash-5.1$
exit
✨  Done in 7.99s.
```

The reason bun sets `$npm_execpath` is for `npm create-*` packages to know how to load an npm client. Bun will eventually get a `npx`-like script runner

I'm closing this as fixed but please re-open it if you still need that hack or run into any other similar problems
<img width="250" alt="image" src="https://user-images.githubusercontent.com/709451/159095665-6cbcc0ad-9eff-406a-bfcc-04d9042041a5.png">
