### ISSUE TITLE
Template literals are broken after Bun v1.1.17

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#12904]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```js
// broken, output: 123➖
console.log(`${123}➖` + '123456 456')

// fine, output: 123- 123456 456
console.log(`${123}- ` + `${123456} ` + '456')

// fine, 123➖123456 456
console.log(`123➖` + '123456 456')

// fine, 123➖123456 456
console.log(`${123}➖${123456} 456`)
```

### Additional information

works as expected in v1.1.17, broken in v1.1.18

**Comment by Jarred-Sumner** [comment]
@paperdave is this a constant folding bug?
