### ISSUE TITLE
Scraping huge HTML file

### ISSUE THREAD

**Issue by seiftahawy54** [oven-sh/bun#12903]
### How can we reproduce the crash?

I've been trying to srcape a website that has a big content size. This is it [https://usul.ai/t/jamic-li-ahkam-quran](Jami'a Li Ahkam Al Quran). It doesn't work well with Bun but works fine with NodeJS. The request is sent through _Axios_ and saved to file system.

![image](https://github.com/user-attachments/assets/6a57cd36-5d76-404d-a2b9-b19a1231dc80)

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x1E0E29E20C0

- [`memcpy.asm:304`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/src/string/amd64/memcpy.asm#L304>): `memcpy`
- [`js_brotli.zig:573`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/api/js_brotli.zig#L573>): `run`
- [`js_brotli.zig:526`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bun.js/api/js_brotli.zig#L526>): `decodeSync`
- [`JSCJSValue.h:746`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/bun/bun/build/bun-webkit/include/JavaScriptCore/JSCJSValue.h#L746>): `JSC::ensureStillAliveHere`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.1.21. This was fixed by @dylan-conway
