### ISSUE TITLE
404 downloading bun-windows-x64-v1.1.22

### ISSUE THREAD

**Issue by okineadev** [oven-sh/bun#12939]
### What version of Bun is running?

1.1.22-canary.31+9b8340a5b

### What platform is your computer?

Linux 6.6.36.3-microsoft-standard-WSL2+ x86_64 x86_64

### What steps can reproduce the bug?

1. Run `bun build main.js --compile --minify --target=bun-windows-x64`
2. See:

```
Downloading [22] error: Does this target and version of Bun exist?

404 downloading bun-windows-x64-v1.1.22 from https://registry.npmjs.org/@oven/bun-windows-x64/-/bun-windows-x64-1.1.22.tgz
```

**Comment by Jarred-Sumner** [comment]
1.1.22 isn't out yet, you're on a canary build of Bun

We should make this error better

**Comment by okineadev** [comment]
> 1.1.22 isn't out yet, you're on a canary build of Bun
> 
> We should make this error better

So I have to roll back to the previous version, ok then, thanks

**Comment by lutfi-haslab** [comment]
just add version available in target, like this: `--target=bun-windows-x64-v1.2.2`
