### ISSUE TITLE
Fix spell mistake

### ISSUE THREAD

**Issue by Sarmad426** [oven-sh/bun#12945]
### What is the issue?

There is a spell mistake on the landing page of [https://bun.sh/](bun). I've attached a screenshot. The problem is with the world optimized. It is written as optimimized which is wrong. Thank me later

<img width="476" alt="image" src="https://github.com/user-attachments/assets/c608929b-8597-43aa-93a3-6f0d93230979">

### Where did you find it?

At page <https://bun.sh/>

**Comment by paperdave** [comment]
the website homepage is unfortunately private (we use it for drafting blog posts that should be private until published). i've gone ahead and fixed the typo
