### ISSUE TITLE
Bundler crash

### ISSUE THREAD

**Issue by jefripunza** [oven-sh/bun#12947]
### How can we reproduce the crash?

const bundledObject = {
  "/favicon.ico": {
    content:
      "AAABAAEAMDAAAAEACAAGBgAAFgAAAIlQTkcNChoKAAAADUlIRFIAAAAwAAAAMAgGAAAAVwL5hwAAAAlwSFlzAAAD6AAAA+gBtXtSawAABbhJREFUeJzlmG9IXWUcx30TRARBL8pFBFEvhDGjFFpwn7vA0WTceqG0XBo6qrVZN9eWGWFZdt1A8CYjZM07GnSHXpWppWxjg2hlkSA0FGHRbaQDYRiEsDDmPU98zz3P8Xee85xznvvH3OjFF/Vcvc/n+3t+v+/zXEsiB98puZNVshmLphKX7uILjWV8YU8TX6zv44sN3/PFml23pQEl7B/PZ1xavA0MBMJeCxu2fqvktq6FDfztphowgf0g/fRrxdl81y2agbW5yqVA0KtPqrWwp6lgA/UTa5+/8B3nNRf4lZpLfHTv1/xw3STfFWtb3ZKTAS9IlebLs1poLFO9J9aOt/DdPYeMj2PtxuDxg5nZ+CGD42eXAUDDgKwXz3Fe9w3/E8ZgUhg7doTf62ghHVCF1uYql9D/3YczT3yxjzcI2M6PMn91txpcCODQ8TcNfvLl1UGXAbyBDE5VP7aupqGsYOztE3wKxvwgXZrdamvq7Kd/A7azw+DQ0Q+yksEFPARW5QyINtKBh15PZnVsYN4X0k9fdl9xgKvgBbhcfZcB9Byqmgt88ynLgA7wL2VOzW5VVl0F37ffMCB5Jl2Dgx7XARfwLgMypI/mRt9ywGM3JuMjJrAKng6vpwEMlDmwmvC2AT/YmceVWpurXIKJG+M7Hc+TrWkXPCQHh+c5gJSh8F7gLX1ZjQwNeEJq6edHbc2fftcBfnKfwSEkVE4HGWJVB17bAIH0U7I17YJH/ntdNTwNIKp04N/7TDKgCWrqp0ccQvVl+FMNBsdhltdVArHqBS7gIWS5LqRLUw/bQvUFuICXYzMnA4gsr6pTmQY0IZW6/JBZfQouRA+tnA2IWPWDbz/KzTjUgfRT0qq+AD9dF1x9LQMYHlwXZHiAC9kGAiAd+vYBW6L6AlxI5yIZaADCEHnBCwPIcnzFQSQOJBnUS8PNaQd8stbgozv5hzpsWgYg7IIMLy5gquuAaUADPh0/4II/U31zRXVoFWQAw6QLj2sA2sIGvXi/p4ab0w54yOvQKsiAmUrtxiCF97tBmtcDH3AoHT/gAIfGqtZ+yIUpNwNtq1vE3T3oBnlr4kE39Ln7HBpuTjvghyL+h1bBBiDcCIM+dCASZVhZqH6SgEM6sVmwAcQq7iZ+93ZzgC1QtNLKwGMOeOzO5N60Ax4KOrSKYgDCNvt96EBr/Nh5gg803TATBt/z0bttieoPEXjd2CyKAQi7QD/qqS5hIh4BTA2g+hT+TPXNFd3/fhTNALZb/sChgofMFiLVp/DjVflXvyADEIaOgqvg0Uaq6gN8vCpb/Xz/rRhoIBQKVewI73hJFmOs+qm6/fdg24UBGby39nqmvfGqET8yau+AqL6A7629ntne8VXPtlj/K+VdiQqsifctmgHG2PlwOMy9xBjrQazK8BjQ3e+P8fKuhKmRxLN29Wnly63XIZiw1uwJhUKl/4kBCDuCgabwMEPhor1Rs/oCHmp5bWb9d2L9y6g8xBhbZoxFi26AMZZCS6F9GGPT4jme4e5CT1QHnCVafeiZjuQ/4jW0EdZDMay1pjfCQA+dDevZ7+IZ7jAi22n7CKHfAX7xaYNjNqTXK6z1HIXZMAPYBfoMAIhVwMOEDA+9+sblW4CHaPW3xRJT5H2nVesVawYmrASKovK0SmaSdCU+QazS6tKdADTgsROq4Y1k14sSA8s68Zr3ENP2wRBCiFUKDVj6M5LnubaRGXl4I+utWSqtUb2RBuz2ocNIKy6nDdqIVn+7NbwAx25aIUHbKFX0FLJk5zRax6/n5bz3GN7zXoUKOhPyGmIqDKEKDu2jGlp5eENS2yh2OrrBBsxrgNNArH8ZsSoMyK1DhzcUCpUqriq0jaY31IDHLqQQq8IA0kk26HfnYSSNgs6EIAOIzBSEynj9njXIKSJzQVyTsRNIJ/o6jc6IQtgVsW7Q2r4G7gSVbDZA5P9u4F8Ol3xYUnDhSwAAAABJRU5ErkJggg==",
    extension: "ico",
  },
  "/index.html": {
    content:
      "PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04IiAvPgogICAgCiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCIgLz4KICAgIDx0aXRsZT5CdW5kYSArIFRTPC90aXRsZT4KICAgIDxzY3JpcHQgdHlwZT0ibW9kdWxlIiBjcm9zc29yaWdpbiBzcmM9Ii9hc3NldHMvaW5kZXgtNFFPRUdLeWwuanMiPjwvc2NyaXB0PgogICAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBjcm9zc29yaWdpbiBocmVmPSIvYXNzZXRzL2luZGV4LURFeU1UM2xuLmNzcyI+CiAgPGxpbmsgcmVsPSJtYW5pZmVzdCIgaHJlZj0iL21hbmlmZXN0LndlYm1hbmlmZXN0Ij4KPG1ldGEgbmFtZT0idGhlbWUtY29sb3IiIGNvbnRlbnQ9IiNmZmZmZmYiPgo8bGluayByZWw9Imljb24iIGhyZWY9Ii9mYXZpY29uLmljbyIgc2l6ZXM9IjQ4eDQ4Ij4KPGxpbmsgcmVsPSJpY29uIiBocmVmPSIvZmF2aWNvbi5zdmciIHNpemVzPSJhbnkiIHR5cGU9ImltYWdlL3N2Zyt4bWwiPgo8bGluayByZWw9ImFwcGxlLXRvdWNoLWljb24iIGhyZWY9Ii9hcHBsZS10b3VjaC1pY29uLTE4MHgxODAucG5nIj48L2hlYWQ+CiAgPGJvZHk+CiAgICA8ZGl2IGlkPSJyb290Ij48L2Rpdj4KICA8L2JvZHk+CjwvaHRtbD4K",
    extension: "html",
  },
};
export default bundledObject;

### Relevant log output

```shell
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\jefri\.bun\bin\bun.exe" "build" "--compile" "--minify" "--sourcemap" "./server.ts" "--outfile" "app"
Features: define tsconfig 
Elapsed: 9ms | User: 0ms | Sys: 0ms
RSS: 54.75MB | Peak: 54.75MB | Commit: 112.34MB | Faults: 13577

---

saya ingin semua file reactjs di masukan dalam single file execute bersama backend


import assets from "../assets";

// FrontEnd Handling
app.all("*", async (req: Request, res: Response, next: NextFunction) => {
  const { path } = req;
  if (String(path).startsWith("/api")) return next();
  let path_fix = path;
  if (path_fix == "/") {
    path_fix = "/index.html";
  }
  let match_file = assets[path_fix];
  if (!match_file) {
    path_fix = "/index.html";
    match_file = assets[path_fix];
  }
  function getMimeType(extension: string): string {
    const mimeTypes: { [key: string]: string } = {
      // tambah extension yang belum ada, di sini...
      ico: "image/x-icon",
      svg: "image/svg+xml",
    };
    return (
      mimeTypes[extension] ||
      mime.lookup(extension) ||
      "application/octet-stream"
    );
  }
  const mimeType = getMimeType(match_file.extension);
  const buffer = Buffer.from(match_file.content, "base64");
  res.setHeader("Content-Type", mimeType);
  return res.send(buffer);
});
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [BuildCommand]

**panic**: integer overflow

- [`js_parser.zig:16326`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16326>): `deoptimizeCommonJSNamedExports`
- [`js_parser.zig:17362`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17362>): `visitExprInOut`
- [`js_parser.zig:17604`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L17604>): `visitExprInOut`
- [`js_parser.zig:7476`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L7476>): `visitRightAndFinish`
- [`js_parser.zig:16978`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16978>): `visitExprInOut`
- [`js_parser.zig:6370`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L6370>): `substituteSingleUseSymbolInStmt`
- [`js_parser.zig:16245`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16245>): `visitStmtsAndPrependTempRefs`
- [`js_parser.zig:16313`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L16313>): `visitFunc`
- [`js_parser.zig:20072`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L20072>): `visitAndAppendStmt`
- [`js_parser.zig:22102`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/js_parser.zig#L22102>): `visitStmts`

**Comment by paperdave** [comment]
This is fixed already. please upgrade to 1.1.21
