### ISSUE TITLE
FYI: It appears Bun segfaulted due to an export before the defined class during tests.

### ISSUE THREAD

**Issue by adrianhelvikspond** [oven-sh/bun#12949]
### How can we reproduce the crash?

Not sure. I create a TCP connection in a test file and see this error about half the time.

Not a big deal for me at all, but since it's a segfault I figured I'd send the report anyways. Might be easy to spot.

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x0000001A

- *3 unknown/js code*
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeCall`
- `JSC::runJSMicrotask`
- `JSC::VM::drainMicrotasks`
- `Bun::jsFunctionDrainMicrotaskQueue`
- *1 unknown/js code*
- `llint_entry`

**Comment by adrianhelvikspond** [comment]
Yes.

**Comment by Jarred-Sumner** [comment]
@adrianhelvikspond can you run `bun upgrade --canary` and try again? I think this was fixed

**Comment by adrianhelvikspond** [comment]
Looks like that consistently fixes the problem. Great! 🙂
