### ISSUE TITLE
Prefilled crash report

### ISSUE THREAD

**Issue by ErikPham** [oven-sh/bun#12942]
### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x00000005

- *2 unknown/js code*
- `JSC::JSObject::getOwnPropertyDescriptor`
- `JSC::objectConstructorGetOwnPropertyDescriptor`
- *3 unknown/js code*
- `llint_entry`
- `llint_entry`
- *1 unknown/js code*

**Comment by Jarred-Sumner** [comment]
Unfortunately, this doesn't give us enough to go off of to reproduce the issue
