### ISSUE TITLE
Static Globals/Constants (--define) Not Defined Soon Enough (or at all)

### ISSUE THREAD

**Issue by Exitium-DEV** [oven-sh/bun#12953]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

**test.ts**
```ts
const apple = 0;
const pear = 1;

if (apple) console.log("hello");
if (pear) console.log("world");
console.log(Bun.env.NODE_ENV);
```

### What is the expected behavior?

`bun --define apple=1 test.ts`

**Expected Output**
```
hello
world
undefined
```

### What do you see instead?

`bun --define apple=1 test.ts`

**Actual Output**
```
world
undefined
```

### Additional information

It would appear that definitions either do not work for variables, or are happening far too late in the transpiler's optimisation process.

One would expect that the transpiler would convert the code to the following
```ts
console.log("hello");
console.log("world");
console.log(Bun.env.NODE_ENV);
```

However it does not.

What makes this issue even more interesting is that if you run the example script with the following command:
`bun --define Bun.env.NODE_ENV=true test.ts` then you get the following (expected) output.

```ts
world
true
```

This indicates that either variables are being missed by definitions, or that optimisations are happening before the transpiler can replace instances of the definition with the value (it's running too soon).

If this is the case, I propose that any `--define` definitions should be the very first thing the transpiler does, before it proceeds into any optimisations.

Reference: https://bun.sh/guides/runtime/define-constant

**Comment by paperdave** [comment]
this is intentional. defines only work on unbound/global identifiers

https://bun.sh/docs/bundler#define

> A map of **global identifiers** to be replaced at build time.
