### ISSUE TITLE
crush when use bun --hot run

### ISSUE THREAD

**Issue by Asmo343** [oven-sh/bun#12969]
### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [RunCommand]

**panic**: napi: napi_define_properties
  Error::Error

- [`bun.zig:1394`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.zig#L1394>): `lenSliceTo`
- [`napi.zig:1168`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/napi/napi.zig#L1168>): `napiSpan`
- ??? at `0x1bb7` in node_sqlite3.node
- ??? at `0x1d04` in node_sqlite3.node
- ??? at `0x280a8` in node_sqlite3.node
- [`napi.cpp:1883`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/bindings/napi.cpp#L1883>): `napi_get_last_error_info`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/12052

**Comment by Jarred-Sumner** [comment]
Please follow along in https://github.com/oven-sh/bun/issues/12052
