### ISSUE TITLE
[docs] Add a mention in the docs for adding @types/bun to the compilerOptions.types array of the tsconfig.json

### ISSUE THREAD

**Issue by MERakram** [oven-sh/bun#12963]
### Discussed in https://github.com/oven-sh/bun/discussions/10471

<div type='discussions-op-text'>

<sup>Originally posted by **angelhdzmultimedia** April 23, 2024</sup>
Hello! 🔥🤩👋🐰🍞

I searched in Google and in the docs, and there's no mention of adding `@types/bun` to the `compilerOptions.types` array of the `tsconfig.json`. I get an error if I don't add it, and also don't get types completion.
> Cannot find name 'Bun'. Do you need to install type definitions for Bun? Try `npm i --save-dev @types/bun` and then add 'bun' to the types field in your tsconfig.

Even the `bun init` generated `tsconfig.json` doesn't have it!</div>

**Comment by TiBianMod** [comment]
you don't need to add `@types/bun` on `compilerOptions.types`
just add it as "devDependencies".

`bun add -d @types/bun`

**Comment by Jarred-Sumner** [comment]
@TiBianMod is right
