### ISSUE TITLE
for loop issue

### ISSUE THREAD

**Issue by rasa7x** [oven-sh/bun#12974]
### What version of Bun is running?

1.1.21

### What platform is your computer?

Windows 11 Pro last version

### Description This Bug?

**Console.log(arr) is performed in all stages of the loop, it should be executed after the console.log(arr) loop is finished and return the entire array once.**

```javascript
var arr = [];

for (let i = 0; i < 100000000; i++) {
    arr.push(i);
}

console.log(arr);
```

**Comment by Jarred-Sumner** [comment]
It is logging the entire array

It takes time to log 100000000 integers sequentially

**Comment by madrasa7** [comment]
console.log(arr) should be executed when the for loop operation is finished, this is the case in node js but not in bun js.
