### ISSUE TITLE
bun upgrade command yelds Illegal instruction error

### ISSUE THREAD

**Issue by igorvolnyi** [oven-sh/bun#1298]
### Version

0.1.13

### Platform

Linux oldshit 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. Well, take pretty old Intel Q6600 processor...
2. Try to launch "bun upgrade"

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Obviously upgrade of bun

### What do you see instead?

[1]    3305 illegal hardware instruction  bun upgrade

### Additional information

bun from https://github.com/oven-sh/bun/releases/download/bun-v0.1.13/bun-linux-x64-baseline.zip

**Comment by eclairevoyant** [comment]
see https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144, use one of the baseline builds

also this is a duplicate

**Comment by Electroid** [comment]
Duplicate of #67
