### ISSUE TITLE
bunfig.toml: doesn't respect install.cache.dir 

### ISSUE THREAD

**Issue by sequencerr** [oven-sh/bun#12990]
### What steps can reproduce the bug?

I didn't use install.sh script. Installed to `bun` binary to different directory from `~/.bun/bin/bun`.

bunfig.toml: doesn't respect install.cache.dir 
also `[install]\n auto = "force"` creates local `node_modules` directory. not sure about other config parameters, didn't test.

**Comment by vktrl** [comment]
It ignores CLI flags as well.
```
$ cat bunfig.toml                                                                               
[install.cache]
dir = "./custom-cache"

$ bun --cache-dir='./custom-cache' pm cache                                
/Users/vktrl/.bun/install/cache

$ uname -psmr
Darwin 23.5.0 arm64 arm

$ bun --revision
1.1.22-canary.96+df33f2b2a
```

**Comment by ragavpr** [comment]
Can confirm this issue, with (`1.1.26+0a37423ba` Arch)
this simple config file is automatically read and applied when in
- $HOME/`.bunfig.toml`
- $cwd/`bunfig.toml` (current working dir)

For testing purposes, an invalid registry URL is written in config, it is used and does fail as expected.
Yet still `install.cache.dir` is ignored.

```
[install]
registry = "https://registry.invalid.local"

[install.cache]
dir = "/somedir/.bun/install/cache"
```

Current workaround
- Just symlinked the default `~/.bun` dir to my required location (`/somedir/.bun`) in a different volume (still ext4), confirmed that hardlinks still do work in that same volume.
- After the fix, symlink can be removed and the required location can be directly used as cache.

**Comment by sequencerr** [comment]
closing as duplicate
