### ISSUE TITLE
error: Unexpected installing fs-extra when aws-cdk-lib is also installed

### ISSUE THREAD

**Issue by ryan-thorburn** [oven-sh/bun#1300]
### Version

0.1.13

### Platform

Darwin Ryans-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create package.json file:
{
  "devDependencies": {
    "aws-cdk-lib": "^2.40.0",
    "fs-extra": "^10.0.0"
  }
}

The error goes away if was-cdk-lib is removed. I don't know how they are interacting.

code/bunerror is 📦 vnull via ⬢ v16.3.0 via 🅒 v4.10.3 at ☸️  docker-desktop () 
➜ rm -r node_modules/ && rm bun.lockb && bun install                                                                                                                   (base) 
bun install v0.1.13
 + aws-cdk-lib@2.45.0
 + fs-extra@10.1.0

 19 packages installed [584.00ms]
Failed to install 1 packages
error: Unexpected installing fs-extra

code/bunerror is 📦 vnull via ⬢ v16.3.0 via 🅒 v4.10.3 at ☸️  docker-desktop () 
➜ ls node_modules/fs-extra/                                                                                                                                            (base) 
LICENSE       README.md     lib/          package.json

code/bunerror is 📦 vnull via ⬢ v16.3.0 via 🅒 v4.10.3 at ☸️  docker-desktop () 
➜ bun install                                                                                                                                                          (base) 
bun install v0.1.13

Checked 20 installs across 21 packages (no changes) [17.00ms]

When I run bun install a second time it does not try to install fs-extra again

### How often does it reproduce? Is there a required condition?

It consistently reproduces with the package.json shown above.

### What is the expected behavior?

That fs-extra will install without a returned error.

### What do you see instead?

code/bunerror is 📦 vnull via ⬢ v16.3.0 via 🅒 v4.10.3 at ☸️  docker-desktop () 
➜ rm -r node_modules/ && rm bun.lockb && bun install                                                                                                                   (base) 
bun install v0.1.13
 + aws-cdk-lib@2.45.0
 + fs-extra@10.1.0

 19 packages installed [584.00ms]
Failed to install 1 packages
error: Unexpected installing fs-extra

### Additional information

Increasing the package versions to the latest does not fix the error:

{
  "devDependencies": {
    "aws-cdk-lib": "^2.45.0",
    "fs-extra": "^10.1.0"
  }
}

Moving the dependencies from the devDependencies section to the dependencies section does not change the error.

**Comment by zhiyuang** [comment]
I have also reproduced it. I think I could look into this issue.
