### ISSUE TITLE
Broken string concatenation when "\/" is used

### ISSUE THREAD

**Issue by sstenchlak** [oven-sh/bun#13005]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```.js
const foo = "hello";
console.log(`${foo} \/` + "world");
```

### What is the expected behavior?

I am not sure what is the **correct** behavior since `\/` is not meaningful, but Node.js v22.5.1 produces
```
hello /world
```

### What do you see instead?

```
hello /
```

### Additional information

Discovered this when debugging N3 writer library, specifically [this line](https://github.com/rdfjs/N3.js/blob/4868ab627cb056941eaf55e2733b63f97f65ecbf/src/N3Writer.js#L299) causes the issue.

**Comment by zoto-ff** [comment]
related to #12904, fixed in #12928. works fine in canary build

<img width="240" alt="image" src="https://github.com/user-attachments/assets/f4779ec7-d2ad-4410-9774-37cac46f782a">
