### ISSUE TITLE
Worker from node:worker_threads constructed with eval option evaluates filename as code

### ISSUE THREAD

**Issue by joas8211** [oven-sh/bun#13034]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 6.6.40-2-lts x86_64 unknown

### What steps can reproduce the bug?

Running following code:
```typescript
import { Worker } from "node:worker_threads";

new Worker("console.log('this should not get printed')", { eval: false });
``` 

### What is the expected behavior?

Following error is expected:
```
TypeError: BuildMessage: ModuleNotFound resolving "console.log('this should not get printed')" (entry point)
```

### What do you see instead?

Following is printed to console instead:
```
this should not get printed
```

### Additional information

This happens only with `eval` option is set for `Worker` with any value. I tried with `true`, `false`, `undefined`.

**Comment by billywhizz** [comment]
i have taken an initial look at this and can reproduce it. working on a fix.
