### ISSUE TITLE
Not able to write excel file using Bun.write

### ISSUE THREAD

**Issue by sukeshpabolu** [oven-sh/bun#13035]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```javascript
const filePath = path.join(__dirname, "GDSN_Attributes_with_BMSId_xPath_3.1.27_Feb_27_2024.xlsx");
const url = "https://www.gs1.org/docs/gdsn/3.1/GDSN_Attributes_with_BMSId_xPath_3.1.27_Feb_27_2024.xlsx";

await Bun.write(filePath, Bun.file(url))
```

### What is the expected behavior?

File should be written to the specified path

### What do you see instead?

ENOENT: No such file or directory
   errno: -2
 syscall: "copyfile"
   path: "C:\Users\supab1\OneDrive - Inter IKEA Group\Documents\code\test-converter\src\GDSN_Attributes_with_BMSId_xPath_3.1.27_Feb_27_2024.xlsx"

### Additional information

Does Bun.write work with excel file which is directly taken from a url?

**Comment by dszymon** [comment]
`Bun.file` expects a path, try:
```ts
const filePath = path.join(__dirname, "GDSN_Attributes_with_BMSId_xPath_3.1.27_Feb_27_2024.xlsx");
const url = "https://www.gs1.org/docs/gdsn/3.1/GDSN_Attributes_with_BMSId_xPath_3.1.27_Feb_27_2024.xlsx";

await Bun.write(filePath, fetch(url));
```

**Comment by Jarred-Sumner** [comment]
try `await. fetch`
