### ISSUE TITLE
Support named pipes on Windows

### ISSUE THREAD

**Issue by LightQuanta** [oven-sh/bun#13042]
### What is the problem this feature would solve?

Support named pipes on Windows just like [node.js](https://nodejs.org/api/net.html#identifying-paths-for-ipc-connections).

> On Windows, the local domain is implemented using a named pipe. The path must refer to an entry in \\?\pipe\ or \\.\pipe\. Any characters are permitted, but the latter may do some processing of pipe names, such as resolving .. sequences. Despite how it might look, the pipe namespace is flat. Pipes will not persist. They are removed when the last reference to them is closed. Unlike Unix domain sockets, Windows will close and remove the pipe when the owning process exits.

Use the following script modified from [#8851](https://github.com/oven-sh/bun/issues/8851#issuecomment-1941804484):

```javascript
const { createServer, connect } = require("node:net")

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

async function test() {
    let responded = false;
    const server = createServer((socket) => {
        socket.on("data", (data) => {
            const message = data.toString()
            console.log(`Message received from client: ${message}`)
            socket.write("Goodbye World!")
            responded = true
        })
    })
    server.listen("\\\\.\\pipe\\test");

    const client = connect("\\\\.\\pipe\\test")
        .on('data', (data) => {
            const message = data.toString();
            console.log(`Message received from server: ${message}`)
        })

    client.write("Hello World!")

    while (!responded) {
        await sleep(10)
    }

    client.destroy()
    server.close()
}

test()
```

Running this with node works properly:

```
node test.js

Message received from client: Hello World!
Message received from server: Goodbye World!
```

But not for bun:

```shell
bun testnode.js

12 |             responded = true
13 |         })
14 |     })
15 |     server.listen("\\\\.\\pipe\\test");
16 |
17 |     const client = connect("\\\\.\\pipe\\test")
                            ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at connect (node:net:302:10)
      at C:\path\to\file\test.js:17:20
      at C:\path\to\file\test.js:5:23
      at C:\path\to\file\test.js:33:1

Bun v1.1.20 (Windows x64)
```

### What is the feature you are proposing to solve the problem?

Support named pipes on Windows just like [node.js](https://nodejs.org/api/net.html#identifying-paths-for-ipc-connections).

This may also be used to solve #11378 .

**Comment by wont-stream** [comment]
Was this falsely closed?
On the canary build and can't use named pipes still.
Running the example code provided in the issue throws this log
```sh
PS C:\Users\-\projects\-> bun run test.js
12 |             responded = true
13 |         })
14 |     })
15 |     server.listen("\\\\.\\pipe\\test");
16 |
17 |     const client = connect("\\\\.\\pipe\\test")
                        ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at connect (node:net:302:10)
      at C:\Users\-\projects\-\test.js:17:20
      at test (C:\Users\-\projects\-\test.js:5:23)
      at C:\Users\-\projects\-\test.js:33:1

Bun v1.1.22-canary.1+f04991f6b (Windows x64)
```

**Comment by Jarred-Sumner** [comment]
@cirospaciari implemented named pipes support on Windows

But there could be a bug here. @cirospaciari does anything stick out?

**Comment by cirospaciari** [comment]
@wont-stream Can you try wait for the listening event before connect?

```js
import { once } from "node:events";
import { createServer, connect } from "node:net";

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function test() {
  let responded = false;
  const server = createServer(socket => {
    socket.on("data", data => {
      const message = data.toString();
      console.log(`Message received from client: ${message}`);
      socket.write("Goodbye World!");
      responded = true;
    });
  });
  server.listen("\\\\.\\pipe\\test");
  await once(server, "listening");

  const client = connect("\\\\.\\pipe\\test").on("data", data => {
    const message = data.toString();
    console.log(`Message received from server: ${message}`);
  });

  client.write("Hello World!");

  while (!responded) {
    await sleep(10);
  }

  client.destroy();
  server.close();
}

test();
```

Locally this works fine without waiting for listening because should be pretty much instant.

Also make sure that the pipe don't exists yet or that you have the right, and that you are on the right version here locally I'm on:
````bash
bun upgrade --stable
Congrats! You're already on the latest version of Bun (which is v1.1.29)
PS C:\repos\bun> bun --revision      
1.1.29+6d43b3662
````

**Comment by wont-stream** [comment]
My apologizes, had installed bun from scoop which is several version behind.
Reinstalled directly and all works now. 🙂

**Comment by Seblor** [comment]
I had a similar issue with a named pipe. Apparently, Bun does not support pipe location using forward slashes (although Node does) and requires double backslashes.

For example this won't work with Bun:

    net.connect('//./pipe/sp_remote_control')

But this will:

    net.connect('\\\\.\\pipe\\sp_remote_control')

But both will work with Node.

Should I open a new issue ?
