### ISSUE TITLE
SQLite segmentation fault

### ISSUE THREAD

**Issue by AlexBlokh** [oven-sh/bun#1304]
### Version

0.1.13

### Platform

Darwin MacBook-Pro-4.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

import { fstatSync, lstatSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { Database } from "bun:sqlite";

const db = new Database(readFileSync("mydb.sqlite"));

// database file
https://www.dropbox.com/s/slw0b5gv1ytpvz3/mydb.sqlite?dl=0

### How often does it reproduce? Is there a required condition?

every time

### What is the expected behavior?

no segmentation fault

### What do you see instead?

SegmentationFault at 0x0000000000000000

----- bun meta -----
Bun v0.1.13 (55bdf268) macOS Silicon 21.5.0
AutoCommand: 
Elapsed: 59ms | User: 8ms | Sys: 23ms
RSS: 30.24MB | Peak: 30.24MB | Commit: 67.11MB | Faults: 837
----- bun meta -----

### Additional information

// if you do this way, it works

const _ = new Database();
const db = new Database(readFileSync("mydb.sqlite"));

// here's a database file
https://www.dropbox.com/s/slw0b5gv1ytpvz3/mydb.sqlite?dl=0

**Comment by Jarred-Sumner** [comment]
Does it happen if you do this?

```js
import {Database} from "bun:sqlite";
const db = new Database("mydb.sqlite")
```

**Comment by AlexBlokh** [comment]
nope

**Comment by Jarred-Sumner** [comment]
Will push a fix in about an hour, once WebKit finishes building https://github.com/oven-sh/webkit

For now, loading any database should fix it. The bug is that deserializing a database isn't lazy-loading SQLite
