### ISSUE TITLE
panic(main thread): Illegal instruction at address 0x2B0B5A0

### ISSUE THREAD

**Issue by tnafele** [oven-sh/bun#13052]
### How can we reproduce the crash?

Bun v1.1.21 (70ca2b76) Linux x64 (baseline)
Linux Kernel v5.10.0 | glibc v2.31
Args: "bun" "add" "puppeteer"
Features: no_avx no_avx2 
Elapsed: 39ms | User: 38ms | Sys: 68ms
RSS: 1.07GB | Peak: 15.82MB | Commit: 1.07GB | Faults: 0

This is on Debian 11.10.
```
$ bun init
$ bun run ./index.ts
Hello via Bun!
$ bun add puppeteer
```

### Relevant log output

```shell
panic(main thread): Illegal instruction at address 0x2B0B5A0
oh no: Bun has crashed. This indicates a bug in Bun, not your code
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on linux x86_64_baseline [AddCommand]

Illegal instruction at address 0x02B0B5A0

- `??`
- [`env_loader.zig:509`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/env_loader.zig#L509>): `src.env_loader.Loader.load__anon_51018`
- [`install.zig:8424`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L8424>): `src.install.install.PackageManager.init`
- [`install.zig:9700`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L9700>): `src.install.install.PackageManager.updatePackageJSONAndInstall`
- [`install.zig:8716`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L8716>): `src.cli.add_command.AddCommand.exec`
- [`cli.zig:1535`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/cli.zig#L1535>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/main.zig#L50>): `main`

**Comment by Jarred-Sumner** [comment]
Bun requires CPUs with AVX support. 

If you’re using a cpu emulator, this issue may help #3312

**Comment by tnafele** [comment]
Thanks for your reply. Unfortunately the baseline version without AVX crashes, too:

```
Bun Canary v1.1.22-canary.96 (df33f2b2) Linux x64 (baseline)
Linux Kernel v5.10.0 | glibc v2.31
Args: "/home/hplus/bun" "run" "test.js"
Features: jsc transpiler_cache(6) tsconfig no_avx no_avx2 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "ws" 
Elapsed: 905ms | User: 702ms | Sys: 355ms
RSS: 1.07GB | Peak: 101.18MB | Commit: 1.07GB | Faults: 0

panic(main thread): Illegal instruction at address 0x31C16C5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```
