### ISSUE TITLE
Error with astro and bun

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#13057]
### How can we reproduce the crash?

Create an new astro project using `bun create astro` and run `bun --bun run dev`
Then you will get this crash.

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on macos aarch64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- *2 unknown/js code*
- `napi_get_named_property`
- *3 unknown/js code*
- `src.napi.napi.ThreadSafeFunction.call`
- `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_121843`
- `src.bun.js.event_loop.EventLoop.tick`
- `src.bun.js.javascript.OpaqueWrap__anon_54007__struct_82603.callback`

**Comment by zoto-ff** [comment]
cant reproduce this on macos aarch64, Bun 1.1.21+70ca2b76c
maybe some extra steps?

<img width="365" alt="image" src="https://github.com/user-attachments/assets/5351d112-4cee-417d-a19c-369edbeb53c7">

**Comment by lassejlv** [comment]
Try using "bunx astro add node". This will add the node adapter so it can run server side. Or go to the url

**Comment by dylan-conway** [comment]
I believe this is fixed with #13214. Could you try with canary (`bun upgrade --canary`)?

**Comment by lassejlv** [comment]
@dylan-conway yes seems to work, thanks!
