### ISSUE TITLE
ɵ sign in imported identifier causes syntax error

### ISSUE THREAD

**Issue by Jakob-em** [oven-sh/bun#1306]
### Version

0.1.13

### Platform

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

src/export.js
```js
export function ɵtest() {};
```

src/index.js
```js
import {ɵtest} from './export'

console.log('Hello, World!');
```

And then run
```
bun run src/index.js
```

### What is the expected behavior?

The expected behaviour is that the import works the same way with and without the `ɵ` sign.

### What do you see instead?

```
1 | import {ɵtest} from './export'
2 |
3 | console.log('Hello, World!');
   ^
SyntaxError: Unexpected token '}'. Expected 'as' after the module export name string.
      at /projects/bun-repro/src/index.js:3:0
```

### Additional information

The `ɵ` is used a lot for indicating that functions are private in the angular packages

**Comment by zhiyuang** [comment]
it seems JavascriptCore doesn't support this ɵ sign

**Comment by Jarred-Sumner** [comment]
This is an issue with Bun's transpiler

Non-unicode identifiers are supported for WASM which can have non-unicode identifiers, but they are being quoted


<img width="369" alt="image" src="https://user-images.githubusercontent.com/709451/194935508-862961cc-ae65-451c-aead-8d1f0a6050ba.png">

The code for quoting the identifier should treat imports specially to only quote if it's a non-BMP identifier (> `0xFFFF`)

**Comment by zhiyuang** [comment]
`This is an issue with Bun's transpiler`

oh, I missed this part

**Comment by Jakob-em** [comment]
Thanks for the quick fix. I can confirm that the original issue is no longer present with version 0.2.0.

Now that this issue is fixed, I ran into the next problem related to the special characters when using namespace imports.
```
1 | import * as i from './export'
2 |
3 | console.log(i.ɵtest())
               ^
TypeError: i["Éµtest"] is not a function. (In 'i["Éµtest"]()', 'i["Éµtest"]' is undefined)
```
with export.js containing:
```ts
export function ɵtest() {
  return 1;
};
```
