### ISSUE TITLE
--watch-env: reload --watch on `.env` change

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#13075]
### What is the problem this feature would solve?

when using `bun --watch`, you have to shut off the process (ctrl + c)  and run it again to use new `Bun.env` variables added by `.env`

### What is the feature you are proposing to solve the problem?

add a new flag (example: `--watch-env`) to reload bun process when `.env` files change

**Comment by simylein** [comment]
Duplicate of #2521

**Comment by huseeiin** [comment]
> Duplicate of #2521

closing then
