### ISSUE TITLE
If the enumeration variable name is a little long, it will panic on Windows(Bun v1.1.21).

### ISSUE THREAD

**Issue by shuimugan** [oven-sh/bun#13081]
### How can we reproduce the crash?

```1.ts
export const A1_AAAAAAAAAAAAAAAAAAA = "aaaaaaaaaaaaaaaaaaa";
export const B1 = "bbbbbbbbbbbbbbbb";

export enum AccountType {
  A = A1_AAAAAAAAAAAAAAAAAAA,
  B = B1,
}

console.log(AccountType);

```

bun run 1.ts

### Relevant log output

```shell
============================================================
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\admin\.bun\bin\bun.exe" "run" "1.ts"
Features: jsc tsconfig
Builtins: "bun:main"
Elapsed: 31ms | User: 46ms | Sys: 93ms
RSS: 97.49MB | Peak: 97.49MB | Commit: 0.14GB | Faults: 24014

panic(main thread): index out of bounds: index 22, len 11
Crashed while visiting C:\code\bun-nest\1.ts
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [RunCommand]

**panic**: index out of bounds: index 18, len 11

- [`array_list.zig:263`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/array_list.zig#L263>): `append`
- [`js_ast.zig:3180`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/js_ast.zig#L3180>): `assert`
- [`Allocator.zig:325`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/mem/Allocator.zig#L325>): `free`
- [`js_parser.zig:18035`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/js_parser.zig#L18035>): `exprCanBeRemovedIfUnused`
- [`js_parser.zig:16011`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/js_parser.zig#L16011>): `appendPart`
- [`debug.zig:412`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/debug.zig#L412>): `assert`
- [`js_parser.zig:3291`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/js_parser.zig#L3291>): `parse`
- [`bundler.zig:1434`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bundler.zig#L1434>): `parseMaybeReturnFileOnlyAllowSharedBuffer`
- [`string_immutable.zig:806`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L806>): `eqlComptimeCheckLenU8`
- [`module_loader.zig:2413`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/module_loader.zig#L2413>): `Bun__transpileFile`

**Comment by shuimugan** [comment]
The same version will not panic on Mac OS and Linux

**Comment by dylan-conway** [comment]
debug stack trace:
```
❯ bun-debug index.ts
============================================================
Bun Debug v1.1.22 (98f9e276) macOS Silicon
macOS v14.4.1
Args: "bun-debug" "index.ts"
Features: jsc bunfig tsconfig(2) 
Builtins: "bun:main" 
Elapsed: 143ms | User: 21ms | Sys: 45ms
RSS: 75.91MB | Peak: 75.91MB | Commit: 1.07GB | Faults: 2873

panic(main thread): index out of bounds: index 22, len 11
Crashed while visiting /Users/dylan/code/bun/index.ts
/Users/dylan/code/bun/src/js_parser.zig:18121:71: 0x1043fec1f in exprCanBeRemovedIfUnused (bun-debug)
                    if (ex.can_be_removed_if_unused or p.symbols.items[ex.ref.innerIndex()].kind != .unbound) {
                                                                      ^
/Users/dylan/code/bun/src/js_parser.zig:20315:68: 0x1048abaaf in visitAndAppendStmt (bun-debug)
                                    if (!p.exprCanBeRemovedIfUnused(&enum_value)) {
                                                                   ^
/Users/dylan/code/bun/src/js_parser.zig:22105:53: 0x1043fa78b in visitStmts (bun-debug)
                            try p.visitAndAppendStmt(&temp, stmt);
                                                    ^
/Users/dylan/code/bun/src/js_parser.zig:16235:29: 0x103deba47 in visitStmtsAndPrependTempRefs (bun-debug)
            try p.visitStmts(stmts, opts.kind);
                            ^
/Users/dylan/code/bun/src/js_parser.zig:16024:47: 0x10374ad43 in appendPart (bun-debug)
            try p.visitStmtsAndPrependTempRefs(&partStmts, &opts);
                                              ^
/Users/dylan/code/bun/src/js_parser.zig:3572:41: 0x10373e7e3 in _parse__anon_116032 (bun-debug)
                        try p.appendPart(&enum_parts, sliced.items);
                                        ^
/Users/dylan/code/bun/src/js_parser.zig:3277:35: 0x1037b13db in parse (bun-debug)
            return try self._parse(TypeScriptParser);
                                  ^
/Users/dylan/code/bun/src/cache.zig:258:36: 0x1039212b3 in parse (bun-debug)
        const result = parser.parse() catch |err| {
                                   ^
/Users/dylan/code/bun/src/bundler.zig:1459:65: 0x10330e21f in parseMaybeReturnFileOnlyAllowSharedBuffer__anon_100919 (bun-debug)
                return switch ((bundler.resolver.caches.js.parse(
                                                                ^
/Users/dylan/code/bun/src/bundler.zig:1308:57: 0x10326c8a7 in parseMaybeReturnFileOnly__anon_95698 (bun-debug)
        return parseMaybeReturnFileOnlyAllowSharedBuffer(
```
cc @paperdave

**Comment by Jarred-Sumner** [comment]
The bug is related to inlining the string into the enum value. It thinks its a symobl, but it appears to be the source_contents_slice.

**Comment by Jarred-Sumner** [comment]
Minimum reproduction:
```ts
let ZZZZZZZZZ;
enum B {
  C = ZZZZZZZZZ,
}
```

**Comment by paperdave** [comment]
the identifer in `... = ZZZZZZZZZ` is being visited however when we check if it has side effects, we use the unvisited expression.
