### ISSUE TITLE
Crash Integer Overflow

### ISSUE THREAD

**Issue by sulvii** [oven-sh/bun#13116]
### How can we reproduce the crash?

Just add minify true in Bun.build

await Bun.build({
  root: "./src",
  entrypoints: ["src/index.ts"],
  outdir: "./dist",
  minify: true,
});

console.log("Build complete ✅");

### Stack Trace (bun.report)

oh no: multiple threads are crashingpanic(thread 16548): integer overflow
 https://bun.report/1.1.20/wr1ae19489AqoggwCq4trbu30ua+/grb6pquakihrb8vxuayxyua86r9VwgwxT88svZA0eNrLzCtJTU8tUsgvSy1Ky8kvBwA2xQaD

**Comment by Jarred-Sumner** [comment]
This is not enough for us to reproduce the issue

Please include the source code of the file

**Comment by Jarred-Sumner** [comment]
Also, can you try `bun upgrade`?

**Comment by codeblitz97** [comment]
upgrading to 1.1.21 seems to fix the issue thanks!
