### ISSUE TITLE
Bun TimeZone (process.env.TZ) is not working

### ISSUE THREAD

**Issue by abdurahmanshiine** [oven-sh/bun#13139]
### What version of Bun is running?

1.1.18

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

This is my entire code:

```ts
process.env.TZ = "Africa/Nairobi"

console.log("Timezone:", process.env.TZ)
console.log(new Date())
```
I have also tried passing an env var with `TZ=Africa/Nairobi bun run index.ts` but it yields the same result. I also tested with a different timezone `process.env.TZ = "America/New_York";` but it changes nothing.

[EDIT]:
I have just noticed that other date methods are working just fine, like `new Date().toLocaleString()` & `new Date().getHours()`, but the `new Date()` isn't.

### What is the expected behavior?

That timezone changes to UTC+03:00

### What do you see instead?

The timezone isn't changing, it's still showing UTC times

**Comment by zoto-ff** [comment]
not a bug. console.log(new Date()) prints time in UTC+0 timezone, the same behavior like in Node or your browser

**Comment by abdurahmanshiine** [comment]
It's the same if I do `new Date().toISOString()`, it prints UTC+0 as well.

Anyway to get the time in ISO format while considering the timezone?

**Comment by zoto-ff** [comment]
the same behavior like in browsers. please read JS docs/specifications, this is not related to Bun

**Comment by abdurahmanshiine** [comment]
Alright. Thanks for the help.
