### ISSUE TITLE
Request: bun tests setup and teardown

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#1314]
### What is the problem this feature will solve?

Currently, there is no way to set up and teardown tests, this causes for a lot of repetition.

### What is the feature you are proposing to solve the problem?

`bun:test` should provide the following APIs:
- [ ] `beforeEach()`
- [ ] `afterEach()`
- [ ] `beforeAll()`
- [ ] `afterAll()`

### What alternatives have you considered?

The only viable alternative currently is to use Jest, which isn't ideal for anyone trying to "de-node".

**Comment by chrisAXZA** [comment]
Definitely good idea!

**Comment by Electroid** [comment]
Yes! We are going to implement these all, tracking this here: #1280
