### ISSUE TITLE
Request: bun tests in the browser

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#1315]
### What is the problem this feature will solve?

Currently, it is undocumented and (not) possible to tests frontends and browser focused projects via `bun wiptest` or `bun test`

### What is the feature you are proposing to solve the problem?

The `bun:test` package should be able to run on browser and possibly other environments to provide a consistent testing experience, especially when working with full-stack applications.

### What alternatives have you considered?

A testing library such as jest could be used currently, although I would prefer that bun handle this

**Comment by Electroid** [comment]
Thanks for filling a feature request! This is certainly interesting, but not something we'll be supporting anytime soon.

**Comment by itsezc** [comment]
@Electroid since Bun has a working test suite and builder properly now, would now be a good time to reopen this issue? Theres many use cases for this for instance using Bun's test suite instead of "Vitest" or "Jest" for projects like Storybook.
