### ISSUE TITLE
Bun crashes on empty TOML

### ISSUE THREAD

**Issue by dmgnr** [oven-sh/bun#13170]
### How can we reproduce the crash?

- Create test script
```js
// test.js
import auth from './test.toml';
console.log(auth);
```
- Create a blank `test.toml` file
- `bun test.js`

### Relevant log output

```shell
$ bun test.js
============================================================
Bun v1.1.21 (70ca2b76) Linux arm64
Linux Kernel v6.5.0 | glibc v2.35
Args: "bun" "test.js"
Features: jsc tsconfig 
Builtins: "bun:main" 
Elapsed: 10ms | User: 4ms | Sys: 8ms
RSS: 1.07GB | Peak: 32.95MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.21/La170ca2b7AiggggCupk++D+8E2i/s8Cuhqu8C29us2Dmn5hzD+20s5E_m+o2xDm+o2xDA2AA

Trace/breakpoint trap (core dumped)
$
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on linux aarch64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `WTF::jscSignalHandler`
- [`alloc.rs:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/alloc.rs#L0>): `??`
- [`module_loader.zig:1824`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/module_loader.zig#L1824>): `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_91127`
- [`module_loader.zig:2413`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/module_loader.zig#L2413>): `Bun__transpileFile`
- [`ModuleLoader.cpp:765`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/bindings/ModuleLoader.cpp#L765>): `Bun::fetchESMSourceCodeAsync`
- [`ZigGlobalObject.cpp:3913`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/bindings/ZigGlobalObject.cpp#L3913>): `Zig::GlobalObject::moduleLoaderFetch`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `JSC::moduleLoaderFetch`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `llint_op_call`

**Comment by Jarred-Sumner** [comment]
sad, thought we fixed this awhile ago
