### ISSUE TITLE
Bun build `error: TODO: implement .node loader for Node.js target`

### ISSUE THREAD

**Issue by Araxeus** [oven-sh/bun#13198]
### What version of Bun is running?

1.1.22-canary.96+df33f2b2a

### What platform is your computer?

Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

create a file like so:
```ts
import { BitwardenClient } from '@bitwarden/sdk-napi';
const client = new BitwardenClient();
```
and try to build it via `Bun.build` or run `bun build --target=node ./bw-test.ts`

### What is the expected behavior?

it builds

### What do you see instead?

![image](https://github.com/user-attachments/assets/332171c0-51a3-4198-b426-2ca2331bf850)

```
bun build --target=node ./bw-test.ts
error: TODO: implement .node loader for Node.js target
```

### Additional information

this `TODO: ` comment does not exist in this repo

https://github.com/search?q=repo%3Aoven-sh%2Fbun+%22TODO%3A+implement+.node%22&type=code

how is this possible? where is it coming from?

**Comment by paperdave** [comment]
this todo comment is defined in bundle_v2. quickly looking, it should be easily fixable by using e_require_call_target instead inlining `import.meta.require(unique_key)`

**Comment by Araxeus** [comment]
> bundle_v2

Where is this file or how is it generated? How come github search doesn't find it? 🧐

**Comment by ikrom** [comment]
what the solution of this bug?
`TODO: implement .node loader for Node.js target`
I'm trying build from my express app, then the error appear

**Comment by regexj-twinkl** [comment]
Also run into this error. Had to change to using esbuild. Problem was `canvas` is a native node module which bun attempts to bundle and throws this error. Could bun implement a solution similar to esbuild where you can add a parameter to list external packages so bun won't attempt to bundle them?

E.g.:
`external: ["canvas"],`

See: https://esbuild.github.io/api/#external

**Comment by Jarred-Sumner** [comment]
@regexj-twinkl did you try `external: ["canvas"]` in bun?

**Comment by regexj-twinkl** [comment]
Of course that works. No need for another builder. Thanks for the comment @Jarred-Sumner
