### ISSUE TITLE
How to use `bun build ` with a config file

### ISSUE THREAD

**Issue by bmbper** [oven-sh/bun#13200]
### What is the type of issue?

Something else

### What is the issue?

```bun build --watch code/bmbp_data_ui/dev/app/**/index.tsx  --target=browser --asset-naming=css/[name].[ext] --entry-naming=js/[dir]/[name].[ext]  --root=code/bmbp_data_ui/dev/app --outdir=code/bmbp_data_ui/static/ --external:react --external:react-dom --external:@arco-design/web-react --bundle --minify```

### Where did you find it?

how can i use a bun.config.js or bunfig.toml which config the build falgs; such as 
`bun.config.js`:
```javascript
export default{
  jsx:"react",
  entrypoints: ["code/bmbp_data_ui/dev/app/**/*.js"],
  root : "code/bmbp_data_ui/dev/",
  outdir : "code/bmbp_data_ui/static/",
  watch : true,
  minify : true,
  bundle : true,
  externals: ["react", "react-dom", "@arco-design/web-react"]
};

```

`bun build --config=bun.config.js`

**Comment by paperdave** [comment]
you can use the `Bun.build` API, but it doesnt support watching (tracked in #5866) 

```ts
const bundle = await Bun.build({
  entrypoints: ["code/bmbp_data_ui/dev/app/**/*.js"],
  root: "code/bmbp_data_ui/dev/",
  outdir: "code/bmbp_data_ui/static/",
  naming: { entry: "js/[dir]/[name].[ext]" },
  watch: true,
  minify: true,
  external: ["react", "react-dom", "@arco-design/web-react"]
});
if (!bundle.success) throw new AggregateError(bundle.logs);
```

**Comment by bmbper** [comment]
my project struct like this:
<img width="454" alt="image" src="https://github.com/user-attachments/assets/6f098c0d-012c-4525-8d92-a7ab708b2687">

my bun.config.js code:
```
const bundle = await Bun.build({
  jsx: "react",
  entrypoints: ["web/jsx/**/index.jsx"],
  root: "web/jsx",
  outdir: "web/static/",
  naming: { entry: "js/[dir]/[name].[ext]" },
  watch: true,
  minify: true,
  external: ["react", "react-dom", "@arco-design/web-react"],
});
if (!bundle.success) throw new AggregateError(bundle.logs);

```

but when i run :
```
bun run bun.config.js
```
i got an error `error: ModuleNotFound resolving "web/jsx/**/index.jsx" (entry point)`, but when i assign one file ,it work correctly (#13201)

**Comment by huseeiin** [comment]
> my project struct like this: <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/121366560/356799943-6f098c0d-012c-4525-8d92-a7ab708b2687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzMzNzcsIm5iZiI6MTcyMzYzMzA3NywicGF0aCI6Ii8xMjEzNjY1NjAvMzU2Nzk5OTQzLTZmMDk4YzBkLTAxMmMtNDUyNS04ZDkyLWE3YWI3MDhiMjY4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGVkNjE4NGE2ZWUzNzM3ZDg2NmNhNGE1MWFmZDZiNzlhYmRkZWY4MWYwODE0Y2I0ODc1ZjIwZTVmMzA5MmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m6ISMJzHC-4mH_DmStqfxG9bve0jzYZvuDpay9B74Hg">
> 
> my bun.config.js code:
> 
> ```
> const bundle = await Bun.build({
>   jsx: "react",
>   entrypoints: ["web/jsx/**/index.jsx"],
>   root: "web/jsx",
>   outdir: "web/static/",
>   naming: { entry: "js/[dir]/[name].[ext]" },
>   watch: true,
>   minify: true,
>   external: ["react", "react-dom", "@arco-design/web-react"],
> });
> if (!bundle.success) throw new AggregateError(bundle.logs);
> ```
> 
> but when i run :
> 
> ```
> bun run bun.config.js
> ```
> 
> i got an error `error: ModuleNotFound resolving "web/jsx/**/index.jsx" (entry point)`, but when i assign one file ,it work correctly (#13201)

you're using a glob matcher which isn't supported. but good idea though :D
