### ISSUE TITLE
sqlite query wrapped in a function causes segmentation fault

### ISSUE THREAD

**Issue by kolesparks** [oven-sh/bun#13226]
### How can we reproduce the crash?

Create a light "todos" array abstraction over sqlite. push a bunch of items, pop them all, then pop again.

https://github.com/kolecreates/bun-sqlite-crash-reproduction

### Relevant log output

```shell
Items inserted: 10000
Items after popping: 0
============================================================
Bun Canary v1.1.22-canary.96 (df33f2b2) macOS Silicon
macOS v14.4.1
Args: "bun" "./index.ts"
Features: jsc tsconfig 
Builtins: "bun:main" "bun:sqlite" 
Elapsed: 191ms | User: 79ms | Sys: 63ms
RSS: 39.27MB | Peak: 39.27MB | Commit: 1.07GB | Faults: 1169

panic(main thread): Segmentation fault at address 0x2
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.22/Ma2df33f2bAiggggC___m7n/qC2ron2B2jjq+Bmphp+B_2l/orC2l/orCA2AE

Trace/BPT trap: 5
```

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x00000002

- *3 unknown/js code*
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeModuleProgram`
- `JSC::JSModuleRecord::evaluate`
- `JSC::JSModuleLoader::evaluate`
- *1 unknown/js code*
- `llint_entry`
- `llint_entry`

**Comment by Jarred-Sumner** [comment]
The repo link there 404s

**Comment by Jarred-Sumner** [comment]
Thanks. This is a great repro.
