### ISSUE TITLE
Segmentation fault at address 0xD0000003B

### ISSUE THREAD

**Issue by AktharAzif** [oven-sh/bun#13235]
### Relevant log output

```shell
============================================================

Bun Canary v1.1.23-canary.17 (7aaf9357) Linux x64 (baseline)

Linux Kernel v6.1.0 | glibc v2.31

CPU: sse42 popcnt avx avx2 avx512

Args: "bun" "src/index.ts"

Features: jsc abort_signal(255) fetch(10609) http_server tsconfig(13) 

Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:dns" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node-fetch" "node:http2" 

 

Elapsed: 10227938ms | User: 956593ms | Sys: 245954ms

RSS: 24.80MB | Peak: 0.41GB | Commit: 24.80MB | Faults: 498

 

panic(main thread): Segmentation fault at address 0xD0000003B

oh no: Bun has crashed. This indicates a bug in Bun, not your code.

 

To send a redacted crash report to Bun's team,

please file a GitHub issue using the link below:

 

 https://bun.report/1.1.23/Ba27aaf935AihihgCu+5gjE+1mOwhr3jDsh417Dw24m/Esv8u2E8uxu2Ekmvu2Ewnj27Dgq0/9CA2a2D

 

error: script "start" was terminated by signal SIGILL (Illegal instruction)
```

### Stack Trace (bun.report)

Bun v1.1.23-canary ([`7aaf935`](<https://github.com/oven-sh/bun/tree/7aaf935711e8c2753561bddc88d5daa84ce695e8>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0xD0000003B

- [`uws.zig:100`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8/src/deps/uws.zig#L100>): `TLSSocketClass__finalize`
- [`ZigGeneratedClasses.cpp:39835`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8//var/lib/buildkite-agent/builds/linux-x64-hetzner-6/bun/bun/build/codegen/ZigGeneratedClasses.cpp#L39835>): `WebCore::JSTLSSocket::destroy`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8/ld-temp.o#L0>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8/ld-temp.o#L0>): `JSC::MarkedBlock::Handle::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8/ld-temp.o#L0>): `JSC::LocalAllocator::tryAllocateIn`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8/ld-temp.o#L0>): `JSC::LocalAllocator::allocateSlowCase`
- [`LocalAllocatorInlines.h:41`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8//var/lib/buildkite-agent/builds/linux-x64-hetzner-6/bun/bun/build/bun-webkit/include/JavaScriptCore/LocalAllocatorInlines.h#L41>): `TLSSocket__create`
- [`ZigGeneratedClasses.zig:12221`](<https://github.com/oven-sh/bun/blob/7aaf935711e8c2753561bddc88d5daa84ce695e8//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-6/bun/bun/build/codegen/ZigGeneratedClasses.zig#L12221>): `src.bun.js.api.bun.socket.NewSocket`

Features: jsc, abort\_signal, fetch, http\_server, tsconfig

**Comment by Jarred-Sumner** [comment]
@cirospaciari can you take a look?

**Comment by Jarred-Sumner** [comment]
We don't have a way to reproduce the issue, but likely this fixes it: https://github.com/oven-sh/bun/pull/13249

Please leave a comment if you still run into the issue after running `bun upgrade --canary` again and we will continue to investigate.

It would be really helpful if you could provide a way for us to reproduce the issue

**Comment by AktharAzif** [comment]
@Jarred-Sumner I cannot reproduce this issue as I don't know its exact cause. I'm using a canary Docker image, so I'll wait for the new release and see if it resolves the problem. Thanks for your help.
