### ISSUE TITLE
dyld: Symbol not found: `_posix_spawn_file_actions_addchdir_np` on MacOS Mojave

### ISSUE THREAD

**Issue by chrisAXZA** [oven-sh/bun#1323]
### Version

0.1.13

### Platform

local 18.7.0 Darwin Kernel Version 18.7.0 root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

bun upgrade

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Successful upgrade

### What do you see instead?
```
bun v0.2.0 is out! You're on 0.1.13

dyld: Symbol not found: _posix_spawn_file_actions_addchdir_np
Referenced from: (which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib

Crash at 0xBA23BB1401000000

----- bun meta -----
Bun v0.1.13 (55bdf268) macOS x64 18.7.0
UpgradeCommand: 
Elapsed: 3519ms | User: 99ms | Sys: 248ms
RSS: 28.92MB | Peak: 28.92MB | Commit: 71.31MB | Faults: 816
----- bun meta -----
```

### Additional information

Probably related to ticket #1266, submitted by kt3k

**Comment by Mouvedia** [comment]
still getting
```sh
dyld: lazy symbol binding failed: Symbol not found: _posix_spawn_file_actions_addchdir_np
…
dyld: Symbol not found: _posix_spawn_file_actions_addchdir_np
…
Crash at 0x56A2561601000000
```
on `bun upgrade`

bun version : 0.1.7
macOS version : 10.13.6

**Comment by chrisAXZA** [comment]
As of version 0.2.2, bun is still not running on MacOS 10.xx versions (webkit memory allocator). Otherwise, use `bun install` as per instructions instead of `upgrade`.
