### ISSUE TITLE
Non-ascii characters in a directiory name break the directory reference in node_modules.server.bun 

### ISSUE THREAD

**Issue by undrscrdt** [oven-sh/bun#1324]
### Version

0.2.0

### Platform

Darwin mac 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create a nextjs project with bun in a non-ascii directory. `bun create next 〇`

Start a development server. `bun dev`

### How often does it reproduce? Is there a required condition?

Reproducible everytime, tried with `〇` `ه` `🐛` and `ねこ`.

### What is the expected behavior?

A project with non-ascii characters (such as internationalized characters) should function identically to an ascii one.

### What do you see instead?

```
[redacted]@[redacted] 〇〇〇.ooo % bun dev 
[0.21ms] "node_modules.bun" - 2140 modules, 335 packages
[5.00ms] bun!! v0.1.13 (55bdf268)


  Link: http://localhost:3000


[0.06ms] "node_modules.server.bun" - 48 modules, 6 packages
[42.50ms] Next.js ready! (powered by bun)
Error loading page: /Users/[redacted]/〇〇〇.ooo/pages/index.tsx


error: Cannot find module "/Users/[redacted]/00" from "/node_modules.server.bun"
send() error: Protocol wrong type for socket
FAIL [EPROTOTYPE] - GET: /bun:error.js
```

**Comment by Jarred-Sumner** [comment]
`node_modules.bun` was deprecated in v0.6 or so
