### ISSUE TITLE
Newer projects can't install without --no-cache flag

### ISSUE THREAD

**Issue by rajatsandeepsen** [oven-sh/bun#13260]
### What version of Bun is running?

1.1.23-canary.30+444766833

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```bash
mkdir project-folder 
cd project-folder 

bun init

bun i
```

### What is the expected behavior?

The project dependency should install just like normal.

![image](https://github.com/user-attachments/assets/48ad67bc-3b1b-4973-9e0d-f75bed0c8124)

#### Problem
![Screenshot 2024-08-13 115545](https://github.com/user-attachments/assets/703438cc-1305-4a89-ac28-11aebb020d67)

#### Current solution 
```bash
bun install --no-cache
```
![image](https://github.com/user-attachments/assets/48ad67bc-3b1b-4973-9e0d-f75bed0c8124)

### Additional information

I think i deleted or moved some old project folder. After that, im getting this error for all new projects. Not just bun init, all new project cloned are getting this error. Older existing projects works just fine. IDK what happened.

**Comment by Jarred-Sumner** [comment]
can you try `bun pm cache rm`?

**Comment by rajatsandeepsen** [comment]
Thanks, its working now 😊 

(sorry for this silly issues, my bad)

```bash
bun pm cache rm
```



![image](https://github.com/user-attachments/assets/0f534445-20e0-4462-bca4-27a8854866b0)
