### ISSUE TITLE
cannot match **/node_modules in Bun.Glob

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#13262]
### What version of Bun is running?

1.1.22-canary.96+df33f2b2a

### What platform is your computer?

Linux 6.5.0-44-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
console.log([...new Bun.Glob("**/node_modules").scanSync()]);
// []
```

### What is the expected behavior?

in node 22 this works:
```ts
import { glob } from "node:fs/promises";

console.log(await Array.fromAsync(glob("**/node_modules")));
```

**Comment by ericchase** [comment]
```
console.log([...new Bun.Glob('**/node_modules').scanSync({ onlyFiles: false })]);
```
onlyFiles is true by default

**Comment by huseeiin** [comment]
> ```
> console.log([...new Bun.Glob('**/node_modules').scanSync({ onlyFiles: false })]);
> ```
> 
> onlyFiles is true by default
> 
> ![image](https://private-user-images.githubusercontent.com/30473157/364196046-50c12724-7481-4df6-8d13-0e2912ffe917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzY3MzIsIm5iZiI6MTcyNTQzNjQzMiwicGF0aCI6Ii8zMDQ3MzE1Ny8zNjQxOTYwNDYtNTBjMTI3MjQtNzQ4MS00ZGY2LThkMTMtMGUyOTEyZmZlOTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3NTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOWZjM2M2OWJmOGIzMWJhNjc4YzkyYmJlZmY1MDg1ODM0YjU0N2YwYjI5ZGJlYTIzOWU2YzZjMzZhODY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9a_ArXy3xY1g0VsmYE8fHNBl22Hyxb19yhfFfYxGxkk)

i should close this. mods can reopen if they wish to.
