### ISSUE TITLE
Bun 1.1.22 crashes but not 1.1.21 on azure linux

### ISSUE THREAD

**Issue by Jonatthu** [oven-sh/bun#13264]
### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64_baseline [_]

Segmentation fault at address 0x000000BC

- [`uws.zig:110`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/deps/uws.zig#L110>): `TLSSocketClass__finalize`
- [`ZigGeneratedClasses.cpp:39835`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6//var/lib/buildkite-agent/builds/linux-x64-hetzner-3/bun/bun/build/codegen/ZigGeneratedClasses.cpp#L39835>): `WebCore::JSTLSSocket::destroy`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::MarkedBlock::Handle::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::LocalAllocator::tryAllocateIn`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::LocalAllocator::allocateSlowCase`
- [`LocalAllocatorInlines.h:41`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6//var/lib/buildkite-agent/builds/linux-x64-hetzner-3/bun/bun/build/bun-webkit/include/JavaScriptCore/LocalAllocatorInlines.h#L41>): `TLSSocket__create`
- [`ZigGeneratedClasses.zig:12221`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-5/bun/bun/build/codegen/ZigGeneratedClasses.zig#L12221>): `src.bun.js.api.bun.socket.NewSocket`

**Comment by cirospaciari** [comment]
This should be fixed in `v1.1.23` if you encounter the same issue again after `bun upgrade` feel free to reopen this issue again.
