### ISSUE TITLE
`spawn.exited` yields weird numbers

### ISSUE THREAD

**Issue by nitsanavni** [oven-sh/bun#1326]
### Version

0.2.0

### Platform

Linux ... 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```ts
import { test } from "bun:test";
import { spawn } from "bun";
import * as assert from "assert";

test("echo hello", async () => {
  assert.deepEqual(
    await spawn({
      cmd: ["echo", "hello world!"],
    }).exited,
    0
  );
});
```

### How often does it reproduce? Is there a required condition?

seems like it never works...

### What is the expected behavior?

exit code should be `0`

### What do you see instead?

```sh
$ bun wiptest

my.test.ts:
AssertionError: Expected values to be loosely deep-equal:

1194066176

should equal

0
 code: "ERR_ASSERTION"

✗ echo hello

 0 pass
 1 fail
 Ran 1 tests across 1 files [26.00ms]
```

### Additional information

when trying `spawnSync` - the exit code it right

**Comment by Jarred-Sumner** [comment]
Thanks for reporting this
