### ISSUE TITLE
open bun.lockb make vscode crash

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#13268]
### What version of Bun is running?

1.1.23-canary.37+460d6edbd

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Open a bun.lockb file in vscode
change package.json and run `bun i` command
Open it again

### What is the expected behavior?

vscode won't crash

### What do you see instead?

vscode crashed (and I cannot get any useful information, since it also crash the vscode debugger)

### Additional information

vscode version: 1.92.1 (Universal)

**Comment by Hamza12700** [comment]
Bun have nothing to do with vscode. Submit this issue on vscode issue tracker, not here.

**Comment by codehz** [comment]
> Bun have nothing to do with vscode. Submit this issue on vscode issue tracker, not here.

bun has an official vscode extension, and I think it is an issue for this extension, because I never observe this behavior before...

**Comment by codehz** [comment]
just for reference: https://github.com/microsoft/vscode/issues/177046
