### ISSUE TITLE
Bun v1.1.23 regression tracking issue: Socket2 is not a function

### ISSUE THREAD

**Issue by thinhbuzz** [oven-sh/bun#13283]
### What version of Bun is running?

11.1.23

### What platform is your computer?

Linux 5.10.0-30-amd64 x86_64 unknown

### What steps can reproduce the bug?

install [pg](https://www.npmjs.com/package/pg) package used to connect postgresql, then run following code and wait for timeout to disconnect

```bash
bun run demo.ts
```

```demo.ts
import { Pool } from 'pg';

const db = new Pool({
          host: process.env.PG_HOST,
          port: +process.env.PG_PORT!!,
          user: process.env.PG_USER,
          password: process.env.PG_PASSWORD,
          database: process.env.PG_DATABASE,
          ssl: process.env.PG_SSL === 'true',
          query_timeout: 5000,
          statement_timeout: 5000,
});
console.log(await db.query('SELECT version();')); // version: "PostgreSQL 16.3 (Debian 16.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit"
console.log('done');
```

### What is the expected behavior?

close connection and close process without any error (same as bun 1.1.22)

### What do you see instead?

![image](https://github.com/user-attachments/assets/892c4bc5-5fb7-4802-8617-43d29d14eedd)

```text
 9 |     return 4;
10 |   if (isIPv6(s))
11 |     return 6;
12 |   return 0;
13 | }, endNT = function(socket, callback, err) {
14 | }, closeNT = function(callback, err) {
                          ^
TypeError: Socket2 is not a function
      at node:net:14:22
```

**Comment by Jarred-Sumner** [comment]
This will be fixed tonight. We will push a release out. 

Here's what happened:
1. To allow local development, a couple tests were being skipped automatically when the required credentials were not present
2. Previously, these credentials were always present in CI. We moved to a new CI, and forgot to migrate the credentials.
3. A PR to our `node:net` implementation broke something important, and the tests which should've failed were skipped due to the missing credentials.

**Comment by thinhbuzz** [comment]
> This will be fixed tonight. We will push a release out.
> 
> Here's what happened:
> 
> 1. To allow local development, a couple tests were being skipped automatically when the required credentials were not present
> 2. Previously, these credentials were always present in CI. We moved to a new CI, and forgot to migrate the credentials.
> 3. A PR to our `node:net` implementation broke something important, and the tests which should've failed were skipped due to the missing credentials.

Thanks for the quick response, I will downgrade to a lower version to wait for the patch. Thanks for the team's efforts to identify the issue.

**Comment by Jarred-Sumner** [comment]
I will keep this open until Bun v1.1.24 is pushed

**Comment by thinhbuzz** [comment]
> I will keep this open until Bun v1.1.24 is pushed
The problem has been solved. Thanks for the team's efforts.

**Comment by nektro** [comment]
for posterity, https://github.com/oven-sh/bun/releases/tag/bun-v1.1.24

you can also get the latest version of Bun with `bun upgrade`

**Comment by thinhbuzz** [comment]
> I will keep this open until Bun v1.1.24 is pushed

hi @Jarred-Sumner The use case mentioned above has been solved, but in the case of pg used together with the HTTP server (elysia), after a long time, all queries hang.

I am trying to reproduce it to provide sample code.

Some preliminary information is as follows:

1. Bun 1.1.22 is not affected, 1.1.23 is not tested, and 1.1.24 is affected.

2. At least 10 hours after the server is started, there will be a hang query; once it hangs, all queries will hang.

**Comment by Jarred-Sumner** [comment]
Okay, I will revert the allowHalfOpen PR which originally caused this for now.

**Comment by thinhbuzz** [comment]
> Okay, I will revert the allowHalfOpen PR which originally caused this for now.

thanks, i hope that will also solve the issue of pg connection pool not working on 1.1.24.
i have reverted all my servers to 1.1.22 and everything is working fine.
