### ISSUE TITLE
fs/promises.stat always logs promise rejections even if the promise catches

### ISSUE THREAD

**Issue by asilvas** [oven-sh/bun#1328]
### Version

0.2.0

### Platform

Linux e4ce933799b1 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```
import fs from 'fs/promises';

await fs.stat('some/file/that/does/not/exist').catch(err => err); // this should not log anything
```

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

No log

### What do you see instead?

```
stat some/file/that/does/not/exist
      at node:fs/promises:5:2
      at node:fs/promises:20:17
      at node:fs/promises:37:6
      at node:fs/promises:36:11
      at filename.ts:77:24
```

**Comment by mia-z** [comment]
Going to assume this is the same issue as #1410 that was "fixed" in https://github.com/oven-sh/bun/commit/f9f169bb9e53afb6d9d8978ffdd4939d3033a6e8

@Jarred-Sumner can you confirm this?

**Comment by Jarred-Sumner** [comment]
@robobun 

```js
import fs from 'fs/promises';

await fs.stat('some/file/that/does/not/exist').catch(err => err); // this should not log anything
```

**Comment by robobun** [comment]
@Jarred-Sumner here you go!
```tsx

```
<details>
  <summary>Code</summary>
  
```tsx
import fs from 'fs/promises';

await fs.stat('some/file/that/does/not/exist').catch(err => err); // this should not log anything
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
