### ISSUE TITLE
Shell fails with interpolated variable

### ISSUE THREAD

**Issue by monstermichl** [oven-sh/bun#13289]
### What version of Bun is running?

1.1.22-canary.96+df33f2b2a

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

If I'm trying to run the shell "$" with an interpolated variable, it fails because it seems to add a newline at the end. Here's the code:

```typescript
import { $ } from 'bun';

const script = 'bun run dev';

await $`${script}`;
```

```
bun: command not found: bun run dev
1 | import { $ } from 'bun';
2 |
3 | const script = 'bun run dev';
                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "bun: command not found: bun run dev\n",
  "stdout": ""
}
```

However, when I'm running the same code without the interpolation, it works as expected.

```typescript
await $`bun run dev`;
```

### What is the expected behavior?

To also work with the interpolated variable.

### What do you see instead?

```
bun: command not found: bun run dev
1 | import { $ } from 'bun';
2 |
3 | const script = 'bun run dev';
                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "bun: command not found: bun run dev\n",
  "stdout": ""
}
```

**Comment by Jarred-Sumner** [comment]
For security reasons, Bun Shell escapes [interpolated variables by default](https://bun.sh/docs/runtime/shell#escape-escape-strings). 

You might want this:

```ts
import { $ } from 'bun';

const script = 'bun run dev';

await $`${{raw: script}}`;
```

**Comment by monstermichl** [comment]
Ah, good to know. Thanks 👍
