### ISSUE TITLE
`AbortSignal.timeout` and `fetch` not working when can't reach server

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#13302]
### What version of Bun is running?

1.1.24

### What platform is your computer?

Linux 5.15.0-117-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
const url = "https://some-url.com";

try {
  const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
  console.log(res);
  // …
} catch (err) {
  if (err.name === "TimeoutError") {
    console.error("Timeout: It took more than 5 seconds to get the result!");
  } else if (err.name === "AbortError") {
    console.error(
      "Fetch aborted by user action (browser stop button, closing tab, etc.",
    );
  } else if (err.name === "TypeError") {
    console.error("AbortSignal.timeout() method is not supported");
  } else {
    // A network error, or some other problem.
    console.error(`Error: type: ${err.name}, message: ${err.message}`);
  }
}
```

But it works correctly when i run it by node

![image](https://github.com/user-attachments/assets/76886878-4a76-4d22-b68b-c03b66ac6132)

I can't ping via shell it too

```sh
ping (this url)
```

and nothing is happend

**Comment by kravetsone** [comment]
issue still exists on 1.0.0, 1.1.15 so its not regression

**Comment by cirospaciari** [comment]
Thank you for the report, if you can provide some extra information can help us to findout the problem, here is some questions:

1 - Are you using proxy or VPN? 
2 - Did you tried another DNS like google or cloudflare? 
3 - Did you test another URLs or is with all URLs? sometimes if you can providing the url causing the problem can help to reproduce here. 
4 - The URL is always https? do http urls works fine?

**Comment by kravetsone** [comment]
> Thank you for the report, if you can provide some extra information can help us to findout the problem, here is some questions:
> 
> 1 - Are you using proxy or VPN? 2 - Did you tried another DNS like google or cloudflare? 3 - Did you test another URLs or is with all URLs? sometimes if you can providing the url causing the problem can help to reproduce here. 4 - The URL is always https? do http urls works fine? 5 - Are you using self signed certificates or extra CAs?

1 - No
2 - How can i do it safely?
3 - The url is - https://securepay.tinkoff.ru/v2

It accepts requests, but does not accept them from my server (apparently it blocks traffic by mistake). The rest of the requests (to another servers) are working properly.

4 - I test only with this https url
5 - No

**Comment by cirospaciari** [comment]
We did some improvements when connecting to a address in canary can you try `bun upgrade --canary` and se if is still happening in this case?
My guess is we are failing in the resolution (IPV4/IPV6 choice) and timing out instead of giving a error like connection refused or similar.

**Comment by kravetsone** [comment]
> We did some improvements when connecting to a address in canary can you try `bun upgrade --canary` and se if is still happening in this case?
> My guess is we are failing in the resolution (IPV4/IPV6 choice) and timing out instead of giving a error like connection refused or similar.

Thanks for your work!
I'm happy that you try to help me)
But i try canary version and issue still exists
![IMG_20240815_222335_705.jpg](https://github.com/user-attachments/assets/396dc9e3-b507-4337-a3f0-9f759e6a57e1)

**Comment by Josh-Cena** [comment]
I think this is the same problem. Minimal repro:

```js
const startTime = Date.now();

fetch("https://creativejs.com/", { signal: AbortSignal.timeout(3000) }).then(console.log, () => {
  const endTime = Date.now();
  console.log(`Time taken: ${endTime - startTime}ms`);
});
```

In Node v22, it takes `3003ms`; in Bun 1.1.24, it hangs.

**Comment by kravetsone** [comment]
> I think this is the same problem. Minimal repro:
> 
> ```js
> const startTime = Date.now();
> 
> fetch("https://creativejs.com/", { signal: AbortSignal.timeout(3000) }).then(console.log, () => {
>   const endTime = Date.now();
>   console.log(`Time taken: ${endTime - startTime}ms`);
> });
> ```
> 
> In Node v22, it takes `3003ms`; in Bun 1.1.24, it hangs.
> 
> (The website doesn't exist in HTTPS, but that's what I'm trying to programmatically verify via the timeout.)

Yeah, really!
Thanks for more great reproduction 
![Screenshot_2024-08-17-00-05-04-08_3d419158bad5872c40592a6c9956e692.jpg](https://github.com/user-attachments/assets/db965d47-e22d-46b3-aa65-3483cc015be3)

**Comment by kravetsone** [comment]
server@test:~/elycart-monorepo$ bun proxy.mts 
AbortSignal.timeout() method is not supported


wtf??

server@test:~/elycart-monorepo$ bun -v
1.1.25

**Comment by kravetsone** [comment]
update

**Comment by emersonlaurentino** [comment]
any update about it?

**Comment by exentrich** [comment]
Same problem. Easy to reproduce:
```js
await fetch('https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker', {
    signal: AbortSignal.timeout(5000),
    verbose: true
})
```

**Comment by cirospaciari** [comment]
> Same problem. Easy to reproduce:
> 
> await fetch('https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker', {
>     signal: AbortSignal.timeout(5000),
>     verbose: true
> })

Thanks for the repro
