### ISSUE TITLE
llint_call_javascript CRASH

### ISSUE THREAD

**Issue by renat2985** [oven-sh/bun#13311]
### How can we reproduce the crash?

For about 5 months now, every new version works for 6-8 days and crashes. I only use "bun:main" "bun:sqlite". It's very sad that BUN is still so green and unstable.

### Relevant log output

```shell
Bun Canary v1.1.22-canary.96 (df33f2b2) Linux x64
Linux Kernel v5.4.0 | glibc v2.31
CPU: sse42 popcnt avx avx2
Features: jsc fetch(11) http_server 
Builtins: "bun:main" "bun:sqlite" 
Elapsed: 644681051ms | User: 948747ms | Sys: 2171860ms
RSS: 1.07GB | Peak: 0.22GB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x2
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000002

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::profiledCall`
- [`bindings.cpp:2424`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/bindings/bindings.cpp#L2424>): `JSObjectCallAsFunctionReturnValue`
- [`bindings.zig:3798`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/bindings/bindings.zig#L3798>): `src.deps.uws.AnyWebSocket.cork__anon_113864.Wrapper.wrap`
- [`MoveOnlyFunction.h:247`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/MoveOnlyFunction.h#L247>): `uws_ws_cork`
- [`uws.zig:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/deps/uws.zig#L0>): `src.deps.uws.WebSocketBehavior.Wrap`
- [`MoveOnlyFunction.h:247`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/MoveOnlyFunction.h#L247>): `uWS::WebSocketContext<false, true, void*>::handleFragment`

**Comment by Electroid** [comment]
Sorry you're running into this. Does your app also use WebSockets? (client or server?)

**Comment by renat2985** [comment]
> Sorry you're running into this. Does your app also use WebSockets? (client or server?)

Server. I posted the main code fragments some time ago here:
https://github.com/oven-sh/bun/issues/11907#issuecomment-2171576768

**Comment by Jarred-Sumner** [comment]
@renat2985 please try again in Bun v1.1.25

A crash could occur in `ws.cork(fn)` when the function threw an exception. #13319 fixed that crash.
