### ISSUE TITLE
Crash on implementing a Deep Mock for unit tests

### ISSUE THREAD

**Issue by marviobezerra** [oven-sh/bun#13331]
### How can we reproduce the crash?

Sandbox: https://codesandbox.io/p/devbox/awesome-hill-395c2x

Run: 
```
bun test
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on macos aarch64 [TestCommand]

Segmentation fault at address 0x00000058

- *3 unknown/js code*
- `llint_entry`
- `llint_entry`
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeCall`
- `JSC::profiledCall`
- `JSObjectCallAsFunctionReturnValue`
- `src.bun.js.test.jest.DescribeScope.runBeforeCallbacks__anon_159614`

**Comment by Jarred-Sumner** [comment]
Thank you for the reproduction! We received the crash report and I wasn't sure how to reproduce this.

**Comment by marviobezerra** [comment]
One extra piece of information: If you run the tests individually they work fine. However, if you run all it crashes on `should return error if person is empty 2`.
