### ISSUE TITLE
execa: undefined is not a function

### ISSUE THREAD

**Issue by fdaciuk** [oven-sh/bun#13343]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Linux 6.6.44-3-MANJARO x86_64 unknown

### What steps can reproduce the bug?

- Create a new project with `bun init`
- Install execa: `bun add execa`
- Add this code to `index.ts`:

```ts
import { execa } from 'execa';

const { stdout } = await execa`echo "test"`;
console.log(stdout);
```

Run `bun index.ts`

### What is the expected behavior?

See `"test"` on console.

### What do you see instead?

```
87 |                    verboseInfo,
88 |            });
89 |    }
90 | 
91 |    const controller = new AbortController();
92 |    setMaxListeners(Number.POSITIVE_INFINITY, controller.signal);
      ^
TypeError: undefined is not a function
      at node:events:101:30
      at spawnSubprocessAsync (/code/execa-test/node_modules/execa/lib/methods/main-async.js:92:2)
      at execaCoreAsync (/code/execa-test/node_modules/execa/lib/methods/main-async.js:26:32)
      at /code/execa-test/index.mjs:3:26

Bun v1.1.24 (Linux x64)
```

**Comment by zacostudio** [comment]
I'm experiencing the same symptoms. Does bunjs still not support it? I've installed node 20, but I'm still experiencing the same symptoms.

**Comment by zacostudio** [comment]
> Hi, everyone. I'm experiencing the same symptoms. Does bunjs still not support it? I've installed node 20, but I'm still experiencing the same symptoms.

I have found another method. https://bun.sh/docs/api/spawn :(

**Comment by Jarred-Sumner** [comment]
@zacostudio you can also use 


```sh
import { $ } from 'bun';

await $`echo "test"`
```

We will fix execa in Bun but that should be a workaround in the meantime if it's a dependency you control
