### ISSUE TITLE
How to install Bun on windows 11?

### ISSUE THREAD

**Issue by tiagocaus** [oven-sh/bun#1334]
### What is the problem this feature will solve?

How to install Bun on windows 11?

### What is the feature you are proposing to solve the problem?

.

**Comment by chrisAXZA** [comment]
Some clips on "install Bun on windows 11"=>
https://www.youtube.com/watch?v=aNL3gXW0ZuM
https://www.youtube.com/watch?v=yp2buL-hG0Q
https://www.youtube.com/watch?v=WH_CNDre39I

**Comment by Kapsonfire** [comment]
I dont understand this issue. Do you think we need to explain how to install wsl?

**Comment by tiagocaus** [comment]
@Kapsonfire-DE I thought it was possible to install as it is done in nodejs for windows.

**Comment by Electroid** [comment]
We're tracking official Windows support here: #43
