### ISSUE TITLE
can't install astro

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#13347]
### What version of Bun is running?

1.1.24-canary.5+cf1863236

### What platform is your computer?

Linux 6.5.0-44-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
bun i astro -d
```
to prove its minimally reproducible:
![image](https://github.com/user-attachments/assets/6d204527-1662-47f1-879d-e74f8d2660f5)

**Comment by Jarred-Sumner** [comment]
I am not able to reproduce this

But I do think it would make sense to have some kind of cache invalidation fallback mechanism. When a non-top level dependency being added fails to resolve from the on-disk cache, it should make a network request

**Comment by huseeiin** [comment]
![image](https://github.com/user-attachments/assets/2ea2768e-3609-42ad-9ce9-52c594683b94)
after upgrading to 1.1.25-canary.27+33c91fe3f it works!
