### ISSUE TITLE
Segmentation fault at address TLSSocketClass__finalize (Bun panic)

### ISSUE THREAD

**Issue by svengraziani** [oven-sh/bun#13350]
### How can we reproduce the crash?

Getting this error since a few days now but can't find the issue why.

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x100000028F

- [`uws.zig:91`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/deps/uws.zig#L91>): `TLSSocketClass__finalize`
- [`ZigGeneratedClasses.cpp:39835`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6//var/lib/buildkite-agent/builds/linux-x64-hetzner-4/bun/bun/build/codegen/ZigGeneratedClasses.cpp#L39835>): `WebCore::JSTLSSocket::destroy`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::PreciseAllocation::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Heap::handleNeedFinalize`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Heap::finishChangingPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

**Comment by svengraziani** [comment]
Sadly I'm on platform.sh and can't control the version in use.

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.24
