### ISSUE TITLE
VS Code extension fails to start debugger on windows  "ws+unix://....." cannot be parsed as a URL.

### ISSUE THREAD

**Issue by KilianB** [oven-sh/bun#13367]
### What version of Bun is running?

1.1.25-canary.18+98a709fb1

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Open any bun project and attempt to launch a file in the debugger. 

![image](https://github.com/user-attachments/assets/08fd427a-c874-4584-bd3c-5993034bb8f6)

### What do you see instead?

````
Failed to start inspector:
 40 |       }
41 |     },
42 |     close: () => {
43 |       writer.close(), pendingMessages.length = 0;
44 |     }
45 | }, parseUrl = function(input) {
                           ^
TypeError: "ws+unix://C:\Users\Kilian\AppData\Local\Temp\f4lo7afea4c.sock?wait=1" cannot be parsed as a URL.
      at internal:debugger:45:23
      at new Debugger (internal:debugger:124:14)
      at internal:debugger:100:13
````

### Additional information

I just installed the extension via the marketplace. This is version v0.0.12

VSCode:
````
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
````

**Comment by smultar** [comment]
I'm also experiencing this issue, and im unable to debug my work and personal-related projects, that rely on bun.

**Comment by KilianB** [comment]
Already tracked in https://github.com/oven-sh/bun/issues/8851
