### ISSUE TITLE
[Bun Shell]: Providing full command as string breaks bun shell

### ISSUE THREAD

**Issue by mathiasrw** [oven-sh/bun#13366]
### What version of Bun is running?

1.1.24

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

If I construct the full command for `Bun.$` as a string and then provide it with 

    Bun.$`${fullCommand}`
    
the call always throws a ShellError. Example:

    bun --print  'await Bun.$`${"grep --version"}`.text()'

If I construct the same command as part of the call to `Bun.$` it works as expected. 

### What is the expected behavior?

The command 

    bun --print  'await Bun.$`grep --version`.text()'

and 

    bun --print  'await Bun.$`${"grep --version"}`.text()'
        
return the same result

### What do you see instead?

The code

    bun --print  'await Bun.$`${"grep --version"}`.text()'    
    
always throws a `ShellError`

### Additional information

 If I construct a command as part of the call to `Bun.$` it works as expected. If I have the identical full command in a string that I feed to `Bun.$` then it breaks. 
 

```js
import Bun from 'bun';

console.log(1, await Bun.$`bun --version`.text()). 		// works

const prop = '--version'
console.log(2, await Bun.$`bun ${prop}`.text()) 		// works

const exe = 'Bun'
console.log(3, await Bun.$`${exe} --version`.text())	// works

console.log(4, await Bun.$`${exe} ${prop}`.text())		// works

const fullCommand = `${exe} ${prop}`			 		// same string as above
console.log(5, await Bun.$`${fullCommand}`.text()) 		// throws error
```

The error is 

       at new ShellError (12:16)
       at new ShellPromise (72:16)
       at BunShell (187:35)

<img width="426" alt="image" src="https://github.com/user-attachments/assets/c8703de3-2daa-4c51-84b0-c3dc187b3204">

**Comment by Jarred-Sumner** [comment]
Bun Shell escapes variables for security reasons similar to sql injection. To disable that for an argument, you can wrap the argument in `raw` like `{ raw: fullCommand }`

This behavior is intentional, but we could probably document this more clearly

**Comment by mathiasrw** [comment]
That makes sense. Thank you for clarifying.
