### ISSUE TITLE
Resolve package.json `"#imports"` with "node" subpath if "bun" doesn't exist

### ISSUE THREAD

**Issue by drinking-code** [oven-sh/bun#1337]
### What is the problem this feature will solve?

Bun currently may use code intended to client-side execution when importing npm packages that use package.json imports with subpaths, which results in unwanted behavior of the package.

### What is the feature you are proposing to solve the problem?

As I understand currently, bun resolves package.json `"#imports"` and looks for the "bun" subpath, and it it doesn't find it, it falls back to the "default" subpath.
Chalk for example uses imports to link to their embedded version of the `supports-color` package.
There are two subpaths there "node" and "default": [link to lines](https://github.com/chalk/chalk/blob/158bf4429ee5c40fd23d45b7d43e5cbbbdf6795e/package.json#L13-L16). The "default" subpath here is used to point to the browser polyfill / version of `supports-color`. Because bun aims to be node compatible I propose that bun should check for a "node" subpath before falling back to "default". This would result in this subpath priority list:
1. bun
2. node
3. default

**Comment by Jarred-Sumner** [comment]
I agree with this however I also think we need to be further along with Node.js compatibility before we do this
