### ISSUE TITLE
`process.hrtime` is the wrong time

### ISSUE THREAD

**Issue by CanadaHonk** [oven-sh/bun#13387]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Linux 6.8.10-200.fc39.x86_64 x86_64 unknown

### What steps can reproduce the bug?

`bun --print "process.hrtime()"` or `bun --print "process.hrtime.bigint()"`

### What is the expected behavior?

The time is from startup(?)

### What do you see instead?

The time is using real/system time (try running the same in Node)

**Comment by CanadaHonk** [comment]
> These times are relative to an arbitrary time in the past
> https://nodejs.org/api/process.html#processhrtimetime

Oh, nvm?

**Comment by jdmarshall** [comment]
I don't know if this is the same situation or something entirely different, but I was fiddling around with perf analysis the other day and I made this gist to show someone:

https://gist.github.com/jdmarshall/2852b799091518bc64f71d6b27e73ee0

I'd like you to look at the timing differences for back-to-back hrtime calls on Bunjs versus Nodejs 22.

The time difference between sequential hrtime.bigInt() calls is around 3-30 times larger on Bun than on Node. That could be slower system call overhead, or actual errors in the timings.
