### ISSUE TITLE
Errors in transforming URL objects back to URLs.

### ISSUE THREAD

**Issue by PoneyClairDeLune** [oven-sh/bun#1338]
### Version

0.2.1

### Platform

Linux unknown 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC unknown 5.19.11-1 (2022-09-24) x86_64 GNU/Linux

### What steps will reproduce the bug?

Listener: https://github.com/PoneyClairDeLune/cloudhop/blob/main/src/bun/index.js
Handler: https://github.com/PoneyClairDeLune/cloudhop/blob/main/src/core/index.js#L235

In short, when turning a `URL` object back to `String`, errors occur. Example snippet below.
```
let bunServer = Bun.serve({
	fetch: async function (request) {
		return await fetch((new URL("https://browserleaks.com/").toString()));
	}
});
```

### How often does it reproduce? Is there a required condition?

There isn't a required condition to reproduce, it fails every time.

### What is the expected behavior?

`URL` objects transforms correctly into strings.

### What do you see instead?

When in ported code, `fetch()` returns `FailedToOpenSocket: fetch() failed`;

When running the demo snippet, the following can be seen in the console.
```
SegmentationFault at 0x5C00000000000000


----- bun meta -----
Bun v0.2.1 (f356da1b) Linux x64 #1 SMP PREEMPT_DYNAMIC Unknown 5.19.11-1 (2022-09-24)
RunCommand: dotenv 
Elapsed: 23504ms | User: 18ms | Sys: 18ms
RSS: 69.21MB | Peak: 64.65MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by Jarred-Sumner** [comment]
This has been fixed, likely in 0.4.0 but I'm not sure when exactly

If you run into it again, please leave a comment and we'll reopen
