### ISSUE TITLE
Reworked websocket api broken when setting headers

### ISSUE THREAD

**Issue by Kapsonfire** [oven-sh/bun#1339]
### Version

 v0.2.1 (923d9c1b)

### Platform

linux amd64

### What steps will reproduce the bug?

adding any headers object to server.upgrade fails setting data to ws - data is undefined
```ts
server.upgrade(this.request, {
            data: {...data, request: this.request, __wsEndPoint: this.websocketEndpoint},
            headers: { 'custom-header': 'custom-value' }
        });
```

adding a non object for headers leads to crash
```
uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.2.1 (923d9c1b) Linux x64 #1 SMP Mon Sep 19 19:14:52 UTC 2022
```

**Comment by Jarred-Sumner** [comment]
Fixed

**Comment by Kapsonfire** [comment]
@Jarred-Sumner do we really want c++ exeption / crash when non-object is passed as header?

**Comment by Jarred-Sumner** [comment]
Hm, the error seems to not be propagating correctly
