### ISSUE TITLE
Bun.serve HTTP timeout is 10s

### ISSUE THREAD

**Issue by mmvsk** [oven-sh/bun#13392]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Linux 6.10.5-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Serving HTTP over TLS, with a response being sent more than 10s after the request.

```typescript
Bun.serve({
	tls: {
		cert: Bun.file(`${import.meta.dir}/cert.pem`),
		key: Bun.file(`${import.meta.dir}/cert.key`),
	},
	async fetch() {
		/* more than the SSL handshake timeout ~10s */
		await Bun.sleep(12_000);
		return new Response("OK\n");
	},
});
```

Call:

```bash
curl -v https://localhost:3000/
```

### What is the expected behavior?

(using node): `OK`

```
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 OK
< content-type: text/plain;charset=utf-8
< Date: Sun, 18 Aug 2024 17:49:01 GMT
< Content-Length: 3
<
OK
* Connection #0 to host localhost left intact
```

### What do you see instead?

(using bun): `curl: (52) Empty reply from server`

```
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS alert, close notify (256):
* Empty reply from server
* shutting down connection #0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (52) Empty reply from server
```

**Comment by cirospaciari** [comment]
Now you should be able to increase the timeout if you wish:

```js
Bun.serve({
  tls,
  port: 8080,
  idleTimeout: 120, //timeout in seconds
  async fetch() {
    return new Response(
      new ReadableStream(
        {
          async pull(controller) {
            controller.enqueue(new TextEncoder().encode("Hello, "));
            await Bun.sleep(12_000);
            controller.enqueue(new TextEncoder().encode("world!"));
            controller.close();
          },
        },
        { type: "text/plain" }
      )
    );
  },
});
```

**Comment by codehz** [comment]
@cirospaciari is it possible to disable this feature for some request? like Server-Sent-Event I want to make it keep until client decided to close the connection

**Comment by ArtDmn** [comment]
> [@cirospaciari](https://github.com/cirospaciari) is it possible to disable this feature for some request? like Server-Sent-Event I want to make it keep until client decided to close the connection

I also would like to know if it's possible to disable this feature on a request basis. What if we want to maintain the connections for a long time? 

At the moment, 255 seems to be the maximum:  https://github.com/oven-sh/bun/blob/main/src/bun.js/api/server.zig#L1271

What I don't understand (but I'm a beginner dev) is that the idleTimeout variable is initially declared as u8 (https://github.com/oven-sh/bun/blob/main/src/bun.js/api/server.zig#L443C18-L443C20) so it cannot be more than 255, but it is then cast as u64 (as seen on line 1271) which will allow near infinite idleTimeout.
