### ISSUE TITLE
I'm not getting the `request.body` property so I cannot retrieve the body of a post request.

### ISSUE THREAD

**Issue by jetgriffin** [oven-sh/bun#1340]
### Version

0.1.13

### Platform

Linux

### What steps will reproduce the bug?

```
Bun.serve({
  fetch(req) {
    console.log(req) // Request (0 KB) { method: "POST", url: "http://0.0.0.0:3001/post-one-form/1" }
    return melonpan.serve(req)
  },
  port: 3001
})
```

The `req` param does not contains the body, which is sent by the client.

### What is the expected behavior?

The expected request should be:
```
{
  method: "POST",
  url: "http://0.0.0.0:3001/post-one-form/1",
  body: ReadableStream | null
}
```

### What do you see instead?

I see instead:
```
{
  method: "POST",
  url: "http://0.0.0.0:3001/post-one-form/1"
}
```

**Comment by Kapsonfire** [comment]
Please update to latest Bun Version 0.2.0
also dont rely on the console.log, even if it doesnt output the body its still there, try to access it

**Comment by jetgriffin** [comment]
I have updated to latest bun version (0.2.0) and the `request body` is not undefined anymore but a Readable Stream as it should be. Fixed.
