### ISSUE TITLE
--- Bun is auto-restarting due to crash [time: 1724066411841] ---

### ISSUE THREAD

**Issue by MoeOuni** [oven-sh/bun#13402]
### How can we reproduce the crash?

I think when i console.log(payload) with huge amount of data it crashed and returned the relevand log output.

### Relevant log output

```shell
Bun v1.1.17 (bb66bba1) macOS Silicon
macOS v14.1.1
Args: "bun" "run" "--watch" "src/app.ts"
Features: jsc Bun.stdin(2) dotenv http_server transpiler_cache(18) tsconfig_paths tsconfig(4) 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:timers" "node:timers/promises" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "ws" 
Elapsed: 1176ms | User: 515ms | Sys: 123ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.95GB | Faults: 219

panic(main thread): Bus error at address 0x410D000001
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x800000007

- *2 unknown/js code*
- `Bun::formatStackTrace`
- `computeErrorInfoWithoutPrepareStackTrace`
- `computeErrorInfoWrapper`
- `JSC::ErrorInstance::computeErrorInfo`
- `JSC::Heap::runEndPhase`
- `JSC::Heap::runCurrentPhase`
- `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`
- `JSC::callWithCurrentThreadState`

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.22.  Please let us know if you still run into this after upgrading.
