### ISSUE TITLE
Bun v1.1.16 repl crash on macos Sonoma w/ M3

### ISSUE THREAD

**Issue by MaxTretikov** [oven-sh/bun#13407]
### How can we reproduce the crash?

Run bun release v1.1.16 with ``bun repl`` on Sonoma 14.5 (Mac M3 128GB). All other functions work.

Prefilled bug reports are an absolutely genius idea btw, I'm stealing that for my next project.

### Relevant log output

```shell
============================================================
Bun v1.1.16 (bf7b327f) macOS Silicon
Args: "/Users/lila/.asdf/installs/bun/1.1.16/bin/bun" "bun-repl"
Elapsed: 1ms | User: 6ms | Sys: 13ms
RSS: 2.98MB | Peak: 2.98MB | Commit: 1.07GB | Faults: 20

panic(main thread): Bus error at address 0x1055E5BE0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/MB1bf7b327AA__+h+lEunlB2pY__A4Cg+t5rF

[1]    15604 trace trap  bun repl
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on macos aarch64 [BunxCommand]

Bus error at address 0x10389DBE0

- *2 unknown/js code*
- `src.cli.bunx_command.BunxCommand.getBinNameFromTempDirectory`
- `src.cli.Cli.start`
- `_mh_execute_header`

**Comment by dylan-conway** [comment]
This was fixed in bun v1.1.17 with #12071
