### ISSUE TITLE
`require` defined in global scope, `globalThis.require` undefined

### ISSUE THREAD

**Issue by ctjlewis** [oven-sh/bun#13410]
### What version of Bun is running?

1.1.25-canary.36+d55b5cc16

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Run:

```ts
console.log(require)
console.log(globalThis.require)
```

### What is the expected behavior?

`require` is `globalThis.require`:

```
Welcome to Node.js v21.0.0.
Type ".help" for more information.
> console.log(require)
[Function: require] {
  resolve: [Function: resolve] { paths: [Function: paths] },
  main: undefined,
  extensions: [Object: null prototype] {
    '.js': [Function (anonymous)],
    '.json': [Function (anonymous)],
    '.node': [Function (anonymous)]
  },
  cache: [Object: null prototype] {}
}

> console.log(globalThis.require)
[Function: require] {
  resolve: [Function: resolve] { paths: [Function: paths] },
  main: undefined,
  extensions: [Object: null prototype] {
    '.js': [Function (anonymous)],
    '.json': [Function (anonymous)],
    '.node': [Function (anonymous)]
  },
  cache: [Object: null prototype] {}
}

> require === globalThis.require
true
```

**And every global variable should exist on the global object.**

### What do you see instead?

In bun, somehow global `require` is defined without it existing on the global object:

```
[Function: require]
undefined
```

### Additional information

Related: https://github.com/oven-sh/bun/issues/13405

Last issue today, so sorry for these.

**Comment by Jarred-Sumner** [comment]
When bun's transpiler detects an unbound require usage (a `require` without any declaration), it replaces it with either `import.meta.require` or the module becomes CommonJS which means the `require` is an argument passed to the function

**Comment by ctjlewis** [comment]
@Jarred-Sumner Can we just bind `globalThis.require` to `import.meta.require`?

**Comment by Jarred-Sumner** [comment]
`globalThis.require` isn't a thing

**Comment by Jarred-Sumner** [comment]
or rather, if we did, then `import.meta.require` would point to the wrong module

**Comment by ctjlewis** [comment]
OK, then createRequire(import.meta.url) has to equal import.meta.require.

**Comment by Jarred-Sumner** [comment]
like `===` (memoized) or produce the same result?

**Comment by ctjlewis** [comment]
That statement could be inlined. We need the `createRequire(import.meta.url).resolve("./file")` case to work, which is the correct way of referencing a file relative to the script itself in ESM.

**Comment by ctjlewis** [comment]
Damn. Apparently even `import.meta.require.resolve` and `require.resolve` behave differently when I manually edit the bundle before compiling. `require.resolve("./file")` works, `import.meta.require.resolve` throws `$bunfs` error.

I'm closing in favor of the other issue. IDK.

**Comment by Jarred-Sumner** [comment]
oh we can fix $bunfs with require.resolve

**Comment by Jarred-Sumner** [comment]
the main issue is it won't know to copy the .wasm file

**Comment by ctjlewis** [comment]
@Jarred-Sumner That's totally fine. We can take over from there and make sure any runtime file dependencies are shipped with the binary:

> If we can always guarantee these statements map correctly, then we can always correct for situations like this by just copying dependencies from node_modules to the build directory.
> 
> If dependency A requires ./internal/thing.wasm, we can just cp -r node_modules/thing_module/dist/internal ./dist if it comes down to it, and any import ... from "./internal/thing.wasm" statements will resolve correctly. Here it's even more trivial because it's just ./yoga.wasm.
