### ISSUE TITLE
Reloading CLI script with bun dev

### ISSUE THREAD

**Issue by khromov** [oven-sh/bun#1341]
### What is the problem this feature will solve?

I have a simple long-running CLI application. I want Bun to restart it every time the file changes during development.

Example:

```typescript
setInterval(() => {
    console.log("Hello world!");
}, 2000);
```

When using `bun dev index.ts` it starts a dev server on port 3000 which does not work. When running `bun run index.ts` it starts correctly, but does not restart when the `index.ts` file changes.

### What is the feature you are proposing to solve the problem?

Some way of telling Bun to not start a dev server and just watch the file, eg: `bun dev index.ts --no-dev-server` or `bun start index.ts --watch` or `bun watch index.ts`.

### What alternatives have you considered?

Existing task runner, eg. Nodemon.

**Comment by Jarred-Sumner** [comment]
This is confusing right now, but use `bun run` instead of `bun dev` for running CLI apps with bun.

**Comment by khromov** [comment]
@Jarred-Sumner But `bun run` does not restart the application when files have changed... It's not a CLI tool that I'm working on, it's a background worker.

**Comment by Jarred-Sumner** [comment]
Try `bun --hot index.ts`

This will reload it, but preserve the existing state. For a background worker, you'd probably want to cancel scheduled tasks
