### ISSUE TITLE
bun update not working as intended

### ISSUE THREAD

**Issue by mAmineChniti** [oven-sh/bun#13432]
### What version of Bun is running?

1.1.24+85a329911

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

do a bun update inside a project

### What is the expected behavior?

to actually update packages to the latest version

### What do you see instead?

instead update behaves like install, it installs the packages and shows you which ones need updating without actually updating them
![WindowsTerminal_fLqgnkT3pa](https://github.com/user-attachments/assets/135204ab-50be-48d3-9221-a074160e6474)
and in the package.json it adds a new key value pair, key being project name and value being `"file:"`
![Code_IsLSU8g0MO](https://github.com/user-attachments/assets/13be5774-4fae-473f-b9e7-4b2084f2dfc9)

**Comment by Jarred-Sumner** [comment]
`bun update` preserves semver ranges to minimize breaking changes from updates

To always use the latest version, pass `--update`:
```
bun update --latest
```

**Comment by mAmineChniti** [comment]
@Jarred-Sumner but what about the added dependancy that's just the project name as key and `file:` as the value/version

**Comment by dylan-conway** [comment]
@mAmineChniti could you share `dependencies`, `devDependencies`, `peerDependencies`, and `optionalDependencies` from your package.json?

**Comment by mAmineChniti** [comment]
look at the dependencies part,
before running bun update:
```json
{
  "name": "tester",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@t3-oss/env-nextjs": "^0.10.1",
    "geist": "^1.3.0",
    "next": "^14.2.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "zod": "^3.23.3"
  },
  "devDependencies": {
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.14.10",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^8.1.0",
    "@typescript-eslint/parser": "^8.1.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.4",
    "postcss": "^8.4.39",
    "prettier": "^3.3.2",
    "prettier-plugin-tailwindcss": "^0.6.5",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.5.3"
  },
  "ct3aMetadata": {
    "initVersion": "7.37.0"
  }
}
```
after running bun update:
```json
{
  "name": "tester",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@t3-oss/env-nextjs": "^0.10.1",
    "geist": "^1.3.1",
    "next": "^14.2.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "tester": "file:",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/eslint": "^8.56.11",
    "@types/node": "^20.16.1",
    "@types/react": "^18.3.4",
    "@types/react-dom": "^18.3.0",
    "@typescript-eslint/eslint-plugin": "^8.2.0",
    "@typescript-eslint/parser": "^8.2.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.5",
    "postcss": "^8.4.41",
    "prettier": "^3.3.3",
    "prettier-plugin-tailwindcss": "^0.6.6",
    "tailwindcss": "^3.4.10",
    "typescript": "^5.5.4"
  },
  "ct3aMetadata": {
    "initVersion": "7.37.0"
  }
}
```
also this error appears, i guess cuz its trying to install the project name
![WindowsTerminal_PQI037mVqm](https://github.com/user-attachments/assets/c184f3ef-f1ec-49b4-be1a-ba8054340000)

**Comment by dylan-conway** [comment]
I think it's possible you have a lockfile with the root package saved as a top level dependency. Before `bun update`, if you run `bun pm ls` does it include `tester`?

**Comment by mAmineChniti** [comment]
i ran bun pm ls before bun update and its not there it only appears after i run bun update
