### ISSUE TITLE
Open debug.bun.sh source code

### ISSUE THREAD

**Issue by efogdev** [oven-sh/bun#13437]
### What is the problem this feature would solve?

It is kinda insane that debugging currently requires active internet connection and we have no option to deploy/serve the inspector by ourselves.  I personally see this as a critical issue. 

### What is the feature you are proposing to solve the problem?

Please consider sharing the source code.

### What alternatives have you considered?

There are no alternatives. I wasn't able to download the source code with client-only methods (like chromium File -> Save Page) as many files are missing until they are explicitly used and loaded (images, scripts).

**Comment by Jarred-Sumner** [comment]
The source code is in https://github.com/oven-sh/bun/tree/main/packages/bun-inspector-frontend, but we haven't deployed it for a little while

**Comment by EfogDev** [comment]
Thank you, I've already found it (that is why I've closed the issue) 
It would be great to have an updated version tho
