### ISSUE TITLE
Segmentation fault at address 0x5 when use create t3-app

### ISSUE THREAD

**Issue by joe-Thanapol** [oven-sh/bun#13447]
### How can we reproduce the crash?

just run
`bun create t3-app@latest`
and after last option "Would you like to use Next.js App Router?" 
it crashes

Not sure if this is caused by the t3 app or not but the terminal say 
"oh no: Bun has crashed. This indicates a bug in Bun, not your code."

### Relevant log output

```shell
Bun v1.1.25 (fe62a614) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "C:\Users\63600\AppData\Local\Temp\bunx-3410940882-create-t3-app@latest\node_modules\create-t3-app\dist\index.js"
Features: jsc Bun.stdin(2) Bun.stdout fetch transpiler_cache
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:events" "node:fs" "node:https" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types"
Elapsed: 9968ms | User: 406ms | Sys: 156ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.23GB | Faults: 44919

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- [`CodeBlock.h:299`](<https://github.com/oven-sh/bun/blob/fe62a614046948ebba260bed87db96287e67921f/C:/a/WebKit/WebKit/Source/JavaScriptCore/bytecode/CodeBlock.h#L299>): `JSC::CodeBlock::bytecodeOffset`

**Comment by nektro** [comment]
if this crash still reproduces for you on the latest version of Bun please let us know the steps you took and we'll reopen but for now we'll close. (you may need to run `bun upgrade`).

![Image](https://github.com/user-attachments/assets/423c1bac-35e0-4bd3-a457-30feab114c1e)
