### ISSUE TITLE
Bunx crash on creating T3 app?

### ISSUE THREAD

**Issue by wrlliam** [oven-sh/bun#13452]
### How can we reproduce the crash?

bunx create-t3-app, fill out the options and then there is a seg fault

### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:968`](<https://github.com/oven-sh/bun/blob/fe62a614046948ebba260bed87db96287e67921f/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L968>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

**Comment by nofrinth** [comment]
Running latest version of bun too. (1.1.25)

**Comment by nektro** [comment]
if this crash still reproduces for you on the latest version of Bun please let us know the steps you took and we'll reopen but for now we'll close. (you may need to run `bun upgrade`).

![Image](https://github.com/user-attachments/assets/2ed82500-9b45-4ff1-8f04-84f86880202f)
