### ISSUE TITLE
Bundler breaks node library imports

### ISSUE THREAD

**Issue by Weldawadyathink** [oven-sh/bun#13479]
### What version of Bun is running?

1.1.24

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Write a script that uses node apis. For example:

// test.ts
```
import { readdir } from "node:fs/promises";
const files = await readdir(import.meta.dir);
console.log(files);
```
(code taken from bun documentation)

Bundle it with bun. For example:

`bun build test.ts --outfile test.js`

Run the file with `bun run test.js`

### What is the expected behavior?

File runs correctly. 

### What do you see instead?

File shows an error: TypeError: readdir is not a function. (In 'readdir(import.meta.dir)', 'readdir' is undefined)

File output is:
```
var {readdir} = (()=>({}));
var files = await readdir(import.meta.dir);
console.log(files);
```
readdir is clearly not a valid function, let alone the node/node compatible function call. 

### Additional information

Possibly similar to #8993

**Comment by Weldawadyathink** [comment]
Tested on 1.1.25 with the same result.

**Comment by Jarred-Sumner** [comment]
> bun build test.ts --outfile test.js

The command needs to specify `--target=node` or `--target=bun` when using node builtins. Otherwise, it assumes you're building for browsers

```sh
bun build --target=bun test.ts --outfile test.js
```

If that doesn't fix the issue please leave a comment

**Comment by Weldawadyathink** [comment]
That works! I see that option in the documentation now.
