### ISSUE TITLE
nanoid generating same characters

### ISSUE THREAD

**Issue by Akumzy** [oven-sh/bun#13471]
### What version of Bun is running?

1.1.25

### What platform is your computer?

Linux 5.15.0-113-generic x86_64 unknown

### What steps can reproduce the bug?

import { nanoid } from 'nanoid'

console.log(nanoid())

### What is the expected behavior?

random characters: iwj3swWbRIipUP4Xp9P11

### What do you see instead?

![image](https://github.com/user-attachments/assets/29c99f36-c26c-4c20-8655-4f9c3f843e56)

**Comment by Jarred-Sumner** [comment]
Fixed by https://github.com/oven-sh/bun/pull/13470

Please let us know if you still run into this after `bun upgrade --canary`
