### ISSUE TITLE
Using idleTimeout of WebSockets longer than 950 causes Bun to eat the free space of / and segfaults

### ISSUE THREAD

**Issue by HaimenToshi** [oven-sh/bun#13483]
### What version of Bun is running?

1.0.18+6443c26a4

### What platform is your computer?

Linux 6.10.6-arch1-1 x86_64

### What steps can reproduce the bug?

Use Bun's built-in websockets server and set idleTimeout to a value larger than 950 seconds.

### What is the expected behavior?

It should be allowed to set WS connections to a larger value without segfaulting.

### What do you see instead?

bun[656609]: segfault at 0 ip 00006415e05a3e6f sp 00007fffc3166eb0 error 4 in bun[3aeae6f,6415df325000+2bd6000] likely on CPU 2 (core 2, socket 0)

bun[657972]: segfault at 0 ip 00005d43939f5e6f sp 00007fffd1811c10 error 4 in bun[3aeae6f,5d4392777000+2bd6000] likely on CPU 3 (core 3, socket 0)

These are 2 segfaults on two separate runs.

**Comment by Jarred-Sumner** [comment]
Please upgrade to a more recent version of Bun. Bun v1.0.18 is 250 days old, and we've released at least 40 new versions of Bun since that time

**Comment by HaimenToshi** [comment]
Alright, bun upgrade --canary doesn't seem to upgrade as I thought, so I had to re-install using curl. Now Bun throws a good error :

20 | Bun.serve({
         ^
TypeError: websocket expects idleTimeout to be 960 or less
 code: "ERR_INVALID_ARG_TYPE"
