### ISSUE TITLE
wrong charset for bun script

### ISSUE THREAD

**Issue by cvng** [oven-sh/bun#13491]
### What version of Bun is running?

1.1.25-canary.3+1bac09488

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```bash
bun --eval "/* @bun */console.log('€')" 
```

### What is the expected behavior?

```bash
bun --eval "/* @bun */console.log('€')"
> € # char code 8364
```

### What do you see instead?

```bash
bun --eval "/* @bun */console.log('€')" 
> â¬ # char code 226
```

### Additional information

without the `// @bun` comment - it works as expected

```bash
bun --eval "console.log('€')" 
> € # char code 8364
```

**Comment by Jarred-Sumner** [comment]
This is due to the `@bun` comment at the top of the file

`@bun` at the top of the file is a special comment we use to say "don't transpile this file". this comment is emitted when using `bun build --target=bun`

in that case, it's expected the file is latin1

**Comment by Jarred-Sumner** [comment]
We are unlikely to change this because a lot of builds rely on this 

But if you have any questions about this feel free to leave a comment

**Comment by cvng** [comment]
@Jarred-Sumner I had not given enough context initially - after investigating here is probably the root cause: https://github.com/oven-sh/bun/issues/13514
