### ISSUE TITLE
`bun add`/`bun install` failed for `imagemin-webpack-plugin`

### ISSUE THREAD

**Issue by dangh** [oven-sh/bun#135]
Hello,

I'm using bun v0.0.73 on m1 macOS

When install this package it keeps saying `error: AccessDenied extracting tarball for imagemin-webpack-plugin`. You can reproduce it by install this package in an empty dir.

I have attached the logs of `bun install --verbose 2>bunlogs` below.

[bunlogs.zip](https://github.com/Jarred-Sumner/bun/files/8399637/bunlogs.zip)

**Comment by Jarred-Sumner** [comment]
thank you for reporting

very interesting, it's consistent for this package specifically

**Comment by Jarred-Sumner** [comment]
I understand why

The function for creating a directory when the file comes before the directory in the archive is not setting the correct permissions. This usually isn't a problem because in most cases the directory appears first (where this permissions problem doesn't occur)

**Comment by alechartung** [comment]
I think I'm running into this same issue with `postgraphile-plugin-atomic-mutations` as well.

**Comment by vitalii-kyktov** [comment]
Getting same issue here with `react-virtualized` after installing this way:  `bun install --backend=copyfile`

```
react-virtualized... error: AccessDenied extracting tarball for react-virtualized
```

**Comment by Gabriel-Alves-Cunha** [comment]
Getting the same issue with `pngjs` + `electron`
```
bun install v0.1.2
  🚚 pngjs... error: AccessDenied extracting tarball for pngjs + electron@19.0.8

 2 packages installed [526.00ms]
```

**Comment by the-reality-engineer** [comment]
Same
   🚚 flux... error: AccessDenied extracting tarball for flux

**Comment by FitFingers** [comment]
I'm getting the same:

```
🚚 @n8tb1t/use-scroll-position... error: AccessDenied extracting tarball for @n8tb1t/use-scroll-position
```
