### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING in latest 1.1.26

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#13515]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
const server = Bun.serve({
  fetch(request, server) {
    let controller!: ReadableStreamDefaultController;
    const interval = setInterval(() => {
      controller.enqueue(`data: ${Date.now()}\n\n`);
    }, 100);
    return new Response(
      new ReadableStream({
        start(_controller) {
          controller = _controller;
        },
        cancel(controller) {
          clearInterval(interval);
        },
      }),
      {
        headers: {
          "Content-Type": "text/event-stream",
          "Cache-Control": "no-cache",
        },
      }
    );
  },
});

console.log(`server listening on http://localhost:${server.port}`);
```

and use curl to test

### What is the expected behavior?

the connection should not be closed...

### What do you see instead?

curl: (18) transfer closed with outstanding read data remaining

### Additional information

it works in 1.1.25

**Comment by codehz** [comment]
I think this issue related to https://github.com/oven-sh/bun/pull/13453

**Comment by cirospaciari** [comment]
Investigating the issue, looks like the socket did not reset the timeout on each send/flush, and its timeouting in 10s (the default)

```js
const server = Bun.serve({
  idleTimeout: 0, 
  fetch(request, server) {
    let controller;
    const interval = setInterval(() => {
      controller.enqueue(`data: ${Date.now()}\n\n`);
    }, 100);
    return new Response(
      new ReadableStream({
        start(_controller) {
          controller = _controller;
        },
        cancel(controller) {
          clearInterval(interval);
        },
      }),
      {
        headers: {
          "Content-Type": "text/event-stream",
          "Cache-Control": "no-cache",
        },
      },
    );
  },
});

console.log(`server listening on http://localhost:${server.port}`);
```

**Comment by EvHaus** [comment]
I think I'm still seeing this issue in 1.1.27. In 1.1.25 my stream properly completes. However in both 1.1.26 and 1.1.27 it seems like my stream gets executed twice, which causes a race condition which sometimes causes the HTTP request not to return any response.

Before I create a new issue -- just confirming, did this fix go out in 1.1.27?

**Comment by Jarred-Sumner** [comment]
It did - can you paste some code that would reproduce it? @cirospaciari will look at it

**Comment by cirospaciari** [comment]
@EvHaus with 10s will fall on the timeout try setting `idleTimeout: 120` with is 2min for example or 0 to disable idleTimeout and you wwill get the request completed, instead of closed.  If you are getting this error without timeout let me know.

**Comment by EvHaus** [comment]
@cirospaciari Thanks. Setting `idleTimeout` to 60, or 120 fixed the issue for me. Not sure if there's anything Bun can do about it, but the DX was pretty poor. It would be great if the error thrown could be something like, `Bun.serve timed out (idleTimeout is set to 10)`. Would the team consider doing that if I were to log that as a new request?
