### ISSUE TITLE
`bun test` fails for testing Next.js when using image source from import: TypeError: "/absolute/path/to/image.svg" cannot be parsed as a URL.

### ISSUE THREAD

**Issue by vojtechmares** [oven-sh/bun#13517]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

See the example repository: https://github.com/vojtechmares/next-bun-image-url-bug

1. clone the repo
2. `bun install`
3. `bun test`

### What is the expected behavior?

Tests pass as they should (like with npm or pnpm, I previously used vitest, but that's buggy with Bun too)

### What do you see instead?

```plaintext
408 |         if (typeof window !== "undefined") {
409 |             let fullUrl;
410 |             try {
411 |                 fullUrl = new URL(imgAttributes.src);
412 |             } catch (e) {
413 |                 fullUrl = new URL(imgAttributes.src, window.location.href);
                            ^
TypeError: "/opt/me/next-bun-image-url-bug/images/next.svg" cannot be parsed as a URL.
      at new URL (1:23)
      at getImgProps (/opt/me/next-bun-image-url-bug/node_modules/next/dist/shared/lib/get-img-props.js:413:27)
      at /opt/me/next-bun-image-url-bug/node_modules/next/dist/client/image-component.js:279:70
      at renderWithHooks (/opt/me/next-bun-image-url-bug/node_modules/react-dom/cjs/react-dom.development.js:15486:18)
      at updateForwardRef (/opt/me/next-bun-image-url-bug/node_modules/react-dom/cjs/react-dom.development.js:19245:20)
      at callCallback (/opt/me/next-bun-image-url-bug/node_modules/react-dom/cjs/react-dom.development.js:4164:14)
      at captureError (/opt/me/next-bun-image-url-bug/node_modules/happy-dom/lib/window/WindowErrorUtility.js:21:22)
      at dispatchEvent (/opt/me/next-bun-image-url-bug/node_modules/happy-dom/lib/event/EventTarget.js:153:44)
      at dispatchEvent (/opt/me/next-bun-image-url-bug/node_modules/happy-dom/lib/nodes/element/Element.js:933:35)
```

### Additional information

For my app, I am using canary release of Next.js, but I tried downgrading to latest stable (v14.2.6) thinking it might be an issue in Next.js, but unfortunately the result was the same.

In my bug reproduction repository, I tried Next version: v14.2.6, v13.5.6 with React ^18. 
Production website is running on Next.js 15.0.0-canary.129 and React 19 (19.0.0-rc-b57d2823-20240822).

Also, I am using `@testing-library/react`: `v16.0.0`.

**Comment by raul-rtl** [comment]
I am having the same issue

**Comment by vojtechmares** [comment]
@raul-rtl you are right, I will raise this issue at happy-dom repo. Therefore I am closing this one.

**Comment by IslamGamal88** [comment]
can you please share the link to the happy-dom issue? having the same problem here

**Comment by vojtechmares** [comment]
Hi @IslamGamal88, to be honest I stopped trying to migrate my app to Bun and left it be. So I did not create an issue on happy-dom repo. Feel free to create it yourself and perhaps link to this issue. Thanks!

**Comment by raul-rtl** [comment]
@vojtechmares  shall we leave the issue open? perhaps the bun team can do something about that

**Comment by vojtechmares** [comment]
@raul-rtl I do not know and I am not sure if Bun team can do anything. This is a happy-dom issue. Feel free to open another issue.

For me this is not priority and I won't invest the time, I am currently running the Next.js app on Node and it's running fine (no need to switch to Bun at the moment).
