### ISSUE TITLE
`Request.url` does not use the hostname

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1354]
### Version

0.2.1

### Platform

Darwin {} 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64

### What steps will reproduce the bug?

```js
// index.js
export default {
  port: 3000,
  fetch(request) {
    console.log(request.url);
    return new Response();
  }
}
```

1. `bun run index.js`
2. `curl http://localhost:3000/`

### What is the expected behavior?

```bash
http://localhost:3000/
```

### What do you see instead?

```bash
http://0.0.0.0:3000/
```

**Comment by Kapsonfire** [comment]
this should work out when you set the hostname inside the server options.
but i think you're right, the hostname should be get by the Host Header
