### ISSUE TITLE
Warn when unrecognized CLI argument is used

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1355]
### What is the problem this feature will solve?

Developers will attempt to use Bun to replace other tools, but should be aware when certain CLI arguments are not supported. (so they can report it as a bug/feature request)

### What is the feature you are proposing to solve the problem?

Bun should provide a list of CLI arguments that it did not understand, but continue anyway.

```bash
bun --doesnotexist --nothing run index.js
> Bun did not recognize the following arguments: --doesnotexist, --nothing
```

**Comment by Jarred-Sumner** [comment]
pedantic: In that particular example, the arguments are forwarded to the script transparently, they're now `index.js` arguments

But in the general case, of where it appears before the script name -- I definitely agree we should do this
