### ISSUE TITLE
bun build --compile "Cannot find module ./yoga.wasm" (Ink CLI App)

### ISSUE THREAD

**Issue by bephrem1** [oven-sh/bun#13552]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

0) Install [commander](https://github.com/tj/commander.js) v`12.1.0` & [ink](https://github.com/vadimdemedes/ink) v`5.0.1`
1) Create a file called `index.tsx` in a folder `src` with contents:
```javascript
#!/usr/bin/env bun

// ./src/index.tsx

import { Command } from "commander";
import { Box, Text, render } from "ink";

const program = new Command();

program.command("hello").action(() => {
  render(
    <Box>
      <Text>world</Text>
    </Box>,
  );
});

program.parse(Bun.argv);

```
2) Run:
```bash
bun build ./src/index.tsx --compile --target=bun-darwin-arm64 --outfile dist/bin
```
3) Run:
```bash
./dist/bin hello
```
4.) You will see the output:
```
error: Cannot find module "./yoga.wasm" from "/$bunfs/root/bin"

Bun v1.1.26 (macOS arm64)
```

### What is the expected behavior?

The output should be:
```
world
```

### What do you see instead?

```
error: Cannot find module "./yoga.wasm" from "/$bunfs/root/bin"

Bun v1.1.26 (macOS arm64)
```

### Related Issues & PRs
- https://github.com/oven-sh/bun/issues/2034
- https://github.com/oven-sh/bun/issues/6567
- https://github.com/oven-sh/bun/issues/13405
- https://github.com/oven-sh/bun/pull/13421
- https://github.com/oven-sh/bun/issues/13522

**Comment by Flaque** [comment]
For a way to replicate this issue in real-world context, it breaks the build of [sfcompute's CLI](https://github.com/sfcompute/cli/tree/bephrem/sf-buy-ink). 

```bash
git clone git@github.com:sfcompute/cli.git
cd ./cli
bun build ./src/index.ts --compile 
```

**Comment by ctjlewis** [comment]
Shim for now:

https://github.com/oven-sh/bun/issues/13522#issuecomment-2311173485

**Comment by Plopix** [comment]
Hello here, is this fixed? I can't make it work. I must miss something but I tried the different workaround here

**Comment by ChrisSchofieldCheckatrade** [comment]
> Hello here, is this fixed? I can't make it work. I must miss something but I tried the different workaround here

https://github.com/oven-sh/bun/issues/13405#issuecomment-2613751135

**Comment by Plopix** [comment]
if you update the deps on react-ink it should fix itself. Which version are you using?
