### ISSUE TITLE
[SolidStart] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#13568]
### What version of Bun is running?

1.1.26-canary.14+6415cc3e9

### What platform is your computer?

Linux 6.5.0-44-generic x86_64 x86_64

### What steps can reproduce the bug?

https://github.com/huseeiin/bun-solid-bug
to reproduce, bun --bun dev
and add some stuff by clicking the "Add" button and then deleting using the "Delete" button

### What is the expected behavior?

in the server console, you'll see

SyntaxError: Unexpected end of JSON input
      at json (native:1:1)
      at unknown:96:64
      at processTicksAndRejections (unknown:12:39)

### Additional information

it works in prod

**Comment by birkskyum** [comment]
Potentially a duplicate of:
- https://github.com/oven-sh/bun/issues/12191

**Comment by huseeiin** [comment]
> Similar to:
> 
>     * [Single Flight server actions - SolidStart (notes example) #12191](https://github.com/oven-sh/bun/issues/12191)

closing as duplicate
