### ISSUE TITLE
Panic when calculating two very large number operations

### ISSUE THREAD

**Issue by I-hope1** [oven-sh/bun#13572]
### How can we reproduce the crash?

Two BigInteger too big. ( >10^6 )

### Relevant log output

```shell
Bun v1.1.26 (0a37423b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\ASUS\.bun\bin\bun.exe" "E:\Users\ASUS\Desktop\aaa.js"
Features: jsc
Builtins: "bun:main"
Elapsed: 73ms | User: 15ms | Sys: 0ms
RSS: 107.17MB | Peak: 111.46MB | Commit: 0.14GB | Faults: 28924

panic(main thread): Segmentation fault at address 0x10
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000010

- [`SymbolTable.h:535`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/SymbolTable.h#L535>): `JSC::SymbolTable::maxScopeOffset`
- [`JSModuleEnvironment.h:48`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleEnvironment.h#L48>): `JSC::JSModuleEnvironment::create`
- [`VMTraps.h:206`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/VMTraps.h#L206>): `JSC::VMTraps::maybeNeedHandling`
- [`JSModuleLoader.cpp:454`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L454>): `JSC::moduleLoaderModuleDeclarationInstantiation`
- *2 unknown/js code*
- `llint_entry`

**Comment by I-hope1** [comment]
Yes, I can reproduce it on the latest version of Bun

**Comment by Electroid** [comment]
Could you share the code you used to reproduce this?

**Comment by I-hope1** [comment]
[TwoBigInt.zip](https://github.com/user-attachments/files/16775272/TwoBigInt.zip)

**Comment by I-hope1** [comment]
Or 10n ** 100_0000n

**Comment by I-hope1** [comment]
Or 2n ** 1048576n

**Comment by xhyrom** [comment]
![image](https://github.com/user-attachments/assets/3c1d164d-b224-4012-92e2-8849458062de)
can't reproduce on my machine :thinking:

**Comment by Jarred-Sumner** [comment]
Scared to open zip files from github last few days

**Comment by I-hope1** [comment]
Try `(bun --print "2n ** 1048576n") + (echo "*1n") > F:/aaa.js`
