### ISSUE TITLE
JavaScript code bun needs

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1358]
- `child_process` polyfill built on top of `Bun.spawn`
- `fs.createReadStream`, `fs.createWriteStream`, `process.stdout`, `process.stdin`, `process.stderr` can be built on `Bun.file().writer()` and ~`Bun.file().stream()`~
- `readline`, in theory, could be built on top of `Bun.file` directly or possibly it could be polyfilled via `bun:ffi`
- Tests for `bun install` which check private npm registries, check bins more thoroughly, and more packages

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.

**Comment by Electroid** [comment]
Most of this is done in [Bun v0.3.0](https://bun.sh/blog/bun-v0.3.0), with the exception of `node:readline`, which we will track elsewhere.
