### ISSUE TITLE
issue in downloading shadcn library 

### ISSUE THREAD

**Issue by Jain-Pranjal** [oven-sh/bun#13585]
### What version of Bun is running?

1.1.26

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

using the official command to download the shadcn ui lib it is showing error 
also it is not able to download the component 

### What is the expected behavior?

i made the next js project using the "bun create next-app my-next-app "
and i am not able to use the shadcn lib as it is giving me error script not found

### What do you see instead?

i see the error while installing the component

.Command failed with exit code 1: bun add @radix-ui/react-slot
bun add v1.1.26 (0a37423b)
Resolving dependencies
Resolved, downloaded and extracted [5]
error: Failed to link next: EBUSY

**Comment by dylan-conway** [comment]
Fixed in #13575 and will be included in bun v1.1.27. You can try the fix now with canary (`bun upgrade --canary`)
