### ISSUE TITLE
Bun cannot start without /proc

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [oven-sh/bun#1360]
### What version of Bun is running?

0.2.1

### What platform is your computer?

x64

### What steps can reproduce the bug?

unmount /proc and then run bun

### How often does it reproduce? Is there a required condition?

every time /proc is not present

### What is the expected behavior?

to start like nodejs

### What do you see instead?

Crash at 0x8A00000000000000

----- bun meta -----
Bun v0.2.1 (1835e4b9) Linux x64 #5 SMP PREEMPT_DYNAMIC Wed Oct 19 22:01:04 CEST 2022
RunCommand: 
Elapsed: 13ms | User: 0ms | Sys: 11ms
RSS: 67.11MB | Peak: 28.36MB | Commit: 67.11MB | Faults: 158
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

### Additional information

I wanted to put bun in an embedded Linux install in which /proc wasn't mounted.

this isn't really an important bug but it would be nice to have a clear error at least.

**Comment by Jarred-Sumner** [comment]
Bun needs /proc to efficiently get the file path for open file descriptors. 

What’s the rationale against mounting /proc?

**Comment by Marc-Pierre-Barbier** [comment]
There is no real reason against mounting /proc it just wasn't done on my system initially. 

As I have written in additional information, it's not really important, but it would be cool to have an error message instead of a simple crash.

**Comment by Electroid** [comment]
In Bun v0.5.0, we implemented a workaround for when `/proc` is not mounted. https://github.com/oven-sh/bun/commit/a345efd270bcd19672b13b363d287354113b7aba
