### ISSUE TITLE
Problem with unicode string / assumed encoding and RegExp?

### ISSUE THREAD

**Issue by tonioloewald** [oven-sh/bun#1362]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

If you create a file containing this line and run it in bun:

`console.log('(0,∞)'.match(/^([[(]-?[\d.∞]+)?,?(-?[\d.∞]+[\])])?$/))`

It will (incorrectly) emit `null` vs. the correct result `["(0,∞)", "(0", "∞)"]`

I've tested this in Chrome, node, and Safari — all produce the correct result.

### How often does it reproduce? Is there a required condition?

100% reproducible

### What is the expected behavior?

It should output:

`["(0,∞)", "(0", "∞)"]`

### What do you see instead?

`null`

### Additional information

This seems to be an encoding error. Bun isn't assuming utf8 encoding in text files. Replacing the '∞' characters with `\u221E` fixes the issue, so:

console.log('(0,\u221E)'.match(/^([[(]-?[\d.\u221E]+)?,?(-?[\d.\u221E]+[\])])?$/))

Produces the expected output.

**Comment by Jarred-Sumner** [comment]
This was fixed in January or so
