### ISSUE TITLE
[yarn berry][PnP] missing dev dependencies

### ISSUE THREAD

**Issue by rtritto** [oven-sh/bun#13632]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Windows 11 x64

### What steps can reproduce the bug?

Reproduction using for example `elysia` dev dependency:
- `yarn init -y`
- `yarn set version berry`
- `yarn add -D elysia`
- Create `index.test.ts` file:
  ```ts
  import { Elysia } from 'elysia'
  new Elysia()
  ```
- `bun test`

### What is the expected behavior?

No error

### What do you see instead?

```console
bun test v1.1.26 (0a37423b)

index.test.ts:

# Unhandled error between tests
-------------------------------
error: Cannot find package "elysia" from "C:\<PROJECT>\index.test.ts"
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 tests across 1 files.
```

**Comment by Jarred-Sumner** [comment]
We don’t support PnP, nor is it likely we will outside of a Bun.plugin. 

Please try installing with a regular node_modules folder.
