### ISSUE TITLE
Memory accumulation and crash when calling fetch() with Blob in FormData running in Docker

### ISSUE THREAD

**Issue by mshameti** [oven-sh/bun#13657]
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Linux 6.6.16-linuxkit aarch64

### What steps can reproduce the bug?

- Run Bun in a containerized environment.
- Repeatedly send Blob in FormData as request body in fetch().

Code snippet: https://github.com/mshameti/bun-memory-accumulation-formdata-fetch-docker/blob/main/sender/script.js
```
git clone https://github.com/mshameti/bun-memory-accumulation-formdata-fetch-docker
cd bun-memory-accumulation-formdata-fetch-docker
docker-compose up --build
```

### What is the expected behavior?

No memory accumulation when sending Blobs in FormData with fetch() in Docker.

### What do you see instead?

Memory accumulates until container runs out of memory.

### Additional information

Container exits with code 137 when it runs out of memory. 

Potentially related: https://github.com/oven-sh/bun/issues/5507

**Comment by Jarred-Sumner** [comment]
This code isn’t waiting for the response to finish receiving the body before starting the next request. If you `await response.blob()` or similar does that reduce memory usage?

**Comment by shametim** [comment]
Thanks for taking a look! 
It did not reduce memory usage unfortunately.

I awaited the response in the commented code in the same file if you’d like to try it out

**Comment by mshameti** [comment]
updated example

**Comment by Jarred-Sumner** [comment]
Will have a fix shortly.
