### ISSUE TITLE
In some cases, SQLite fails to persist changes unless "close" is called

### ISSUE THREAD

**Issue by chrisdavies** [oven-sh/bun#1366]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Fedora 36

## Sample Program

Save the following script to `example.mjs` and then run it twice (or more) `bun ./example.mjs`:

```js

import { Database } from 'bun:sqlite';

const db = new Database('demo.sqlite');

// Note, I've played with various values and it doesn't seem to change
// the behavior. The "beter-sqlite3" npm package does not exhibit this
// bug, so it doesn't seem to be a general SQLite thing.
db.run(`PRAGMA journal_mode = WAL`);
db.run(`PRAGMA synchrounous = NORMAL`);

db.run(
  `CREATE TABLE IF NOT EXISTS examples (
    id TEXT PRIMARY KEY
  )`
);

// When you run the program for the second time, you should see
// "hello" and "world" as ids, but you only see "hello"
console.log('Persisted: ', db.query(`SELECT * FROM examples`).all());

// This persists, but if you place this call 
db.run(
  `
    INSERT INTO examples
    VALUES ('hello')
    ON CONFLICT (id) DO
      UPDATE SET id='hello'
    RETURNING id
  `
);

console.log(
  'Upserted: ',
  db.query(`SELECT id FROM examples WHERE id='hello'`).get().id
);

// This does not persist
console.log(
  'Upserted: ',
  db
    .query(
      `
      INSERT INTO examples
      VALUES ('world')
      ON CONFLICT (id) DO
        UPDATE SET id='world'
      RETURNING id
    `
    )
    .get().id
);

console.log(
  'Upserted: ',
  db.query(`SELECT * FROM examples`).all(),
);

// Calling db.close() fixes the issue.
// db.close();
console.log('DONE');

```

### How often does it reproduce? Is there a required condition?

It is quite consistent. I noticed it when I was doing an upsert for sesion cookies, and the session was reset every time I rebuilt the app. It didn't matter how long I remained logged in-- I was always logged out when I restarted the app. It turned out, the session info was not being persisted to disk for some reason.

When I changed `sql.query(' upsert here with returning ').get()` to two separate clauses:

```
sql.run(' ... ')
sql.query(' ... ')
```

The problem resolved, but I should be able to do that as a single upsert with a RETURNING.

### What is the expected behavior?

I can do `sql.query().get()` with an insert / on conflict / returning statement, and have the actual data persist.

### What do you see instead?

The data doesn't persist (see the demo script).

**Comment by Jarred-Sumner** [comment]
`get()` only runs the first step because it is supposed to be limited to the first result. 

But maybe that should be changed.
