### ISSUE TITLE
Add `--icon` option to customize icon when building single-file executables for Windows

### ISSUE THREAD

**Issue by philipp-spiess** [oven-sh/bun#13686]
### What is the problem this feature would solve?

Right now, running `bun build` to build a Windows executable will always use the Bun icon for the resulting `.exe` file. It's possible to customize this by using third party decompiler [tools like `ResourceHacker.exe`](https://github.com/tailwindlabs/tailwindcss/pull/14270/commits/698d9c4bd182391adb4b236f19a539aff13f78f9) or patching the binary but it would be nice if we can do this at build time instead.

### What is the feature you are proposing to solve the problem?

Add a new `--icon` option to customize the inlined `.ico` file for Windows builds

**Comment by paperdave** [comment]
see https://github.com/oven-sh/bun/pull/15894
