### ISSUE TITLE
Two mentions of .npmrc contradict each other in the docs

### ISSUE THREAD

**Issue by aShimoka** [oven-sh/bun#13725]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

I found two conflicting mentions for `.npmrc` support in the documentation.
On the [registry page](https://bun.sh/docs/install/registries#npmrc), it says that:
> Bun does not currently read `.npmrc` files. For private registries, migrate your registry configuration to `bunfig.toml` as documented above.

However, there is a whole page for `.npmrc` support [here](https://bun.sh/docs/install/npmrc), with a conflicting mention:
> Bun supports loading configuration options from [`.npmrc`](https://docs.npmjs.com/cli/v10/configuring-npm/npmrc) files, allowing you to reuse existing registry/scope configurations.

It seems the note was added in the commit 609f81a about a year ago. And when the [`docs/install/npmrc.md`](https://github.com/oven-sh/bun/blob/main/docs/install/npmrc.md) page was added more recently through commit cdc68a2 that mention was not removed appropriately

### Where did you find it?

The first mention is made here: https://bun.sh/docs/install/registries#npmrc

And the second one can be found here: https://bun.sh/docs/install/npmrc

**Comment by Jarred-Sumner** [comment]
Thanks. Updated
