### ISSUE TITLE
`bun update`: update all dependencies to latest version

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#1372]
### What is the problem this feature would solve?

easily updating all dependencies of your project to the latest version. removing the lockfile will do this, but it doesnt update package.json with the new versions. it's handy to be able to see what version of a package you're using by looking into package.json, and bumping thse values manually or by `bun install package1 package2 package3 package4 ...` is tedious. currently, `bun update` is aliased to install, and this works for passing package names directly, but i propose adding real command to update _all_ packages.

[i brought it in the discord here](https://discord.com/channels/876711213126520882/876711213126520885/1033211968871485450)

### What is the feature you are proposing to solve the problem?

i'm proposing an api similar/identical to `pnpm update`:

- `bun update` with no extra arguments would update all packages to the latest version allowed by the specifier in package.json, then bump up the entry in package.json to only allow that version and newer ones; as in, rewrite `^1.0.0` to `^1.5.0`, not `^2.0.0`.

- at the same time, it would be useful if this told the user if the `latest` tag of each package was newer than the range the package specifies. something like how pnpm will do this "(v is available)" message.
![image](https://user-images.githubusercontent.com/24465214/197372366-75c4c6a7-2636-4beb-81c1-8a735469e8a8.png)
  this would be useful as when installing a package, the specifier doesnt allow for major versions to get bumped, so a little note that a major update exists may be helpful.
  - unlike `pnpm update` / `pnpm install`, i think bun's implementation should always show any major out of date packages, so the user is aware of the package releases. while testing behavior of various package managers, i _just now_ learned that `formdata-node@5` was released two months ago.

- a `--latest` flag which does updates each package to it's `latest` tag.

### What alternatives have you considered?

- external script which pulls from package.json and runs `bun install <every package name>` to achieve similar behavior
- dealing with `bun install a b c d e ...`

**Comment by jakeboone02** [comment]
This issue and #1223 are quite similar, and [my comment on 1223](https://github.com/oven-sh/bun/issues/1223#issuecomment-1499347101) is relevant here:

> As an additional request, something like Yarn v2's [`upgrade-interactive` plugin](https://www.npmjs.com/package/@yarnpkg/plugin-interactive-tools) would be really nice.
> 
> ![image](https://user-images.githubusercontent.com/366438/230443633-e8d15602-03fc-492e-97b8-e227421fcf75.png)

**Comment by ImBIOS** [comment]
For the fastest implementation, I made a PR in ncu:

- https://github.com/raineorshine/npm-check-updates/pull/1309

**Comment by Electroid** [comment]
This was introduced in [Bun 0.8](https://bun.sh/blog/bun-v0.8.0)! 🎉

**Comment by michaelhays** [comment]
Glad to see `bun update` land, but AFAIK there's still no option to replicate the [`pnpm update --latest`](https://pnpm.io/cli/update#--latest--l) functionality, right?

`--latest` is super useful because it allows you to view the diff of all of your dependencies in `package.json`, so that you can go through and read the changelogs for any relevant library updates.

**Comment by jakeboone02** [comment]
@michaelhays the upcoming `bun outdated` command (see #1223) isn't exactly the same but might help.

**Comment by ImBIOS** [comment]
> For the fastest implementation, I made a PR in ncu:
> 
> * [feat: bun as packageManager option raineorshine/npm-check-updates#1309](https://github.com/raineorshine/npm-check-updates/pull/1309)

Just to notify, everyone who waiting for this. It's merged in `ncu`, it's enough for temporary solution.

**Comment by ctison** [comment]
A nice tool is [npm-check-updates](https://www.npmjs.com/package/npm-check-updates):
```sh
bun x npm-check-updates -ui
```
It even works in workspaces!
```sh
bun x npm-check-updates -ui -ws
```

**Comment by ThatOneCalculator** [comment]
`bun update -f` can probably handle this nowdays

**Comment by TomasHubelbauer** [comment]
Looks like `bun update --latest` is a thing now. Check `bun update --help`. I tested it and it seems to work. Leaving this note here, because this is the top search engine result for "bun update all to latest" which in my mind translates to "update all packages to latest versions" not "update all packages to the latest compatible versions as specified by their semver ranges" which is both useful, but for people specifically looking for the former, here is an explicit confirmation that it exists and information on how it can be used.

**Comment by jakeboone02** [comment]
Looks like my request for an interactive mode in https://github.com/oven-sh/bun/issues/1223#issuecomment-1499347101 (mentioned above in https://github.com/oven-sh/bun/issues/1372#issuecomment-1500956174) is being added in the next version. See:
- https://x.com/jarredsumner/status/1941790838922887624
- #4895
- #20850
