### ISSUE TITLE
On Linux, node:cluster does not perform load balancing.

### ISSUE THREAD

**Issue by Chacix** [oven-sh/bun#13721]
### What version of Bun is running?

latest

### What platform is your computer?

Linux 5.4.0-156-generic x86_64 x86_64

### What steps can reproduce the bug?

<img width="1525" alt="image" src="https://github.com/user-attachments/assets/63e9096a-12f5-40ca-861e-c0d5d01ceb70">

**Comment by Jarred-Sumner** [comment]
If you run multiple requests at a time does the behavior change?
