### ISSUE TITLE
Bug in the accessing of the property object syntax

### ISSUE THREAD

**Issue by xiaoxigua-1** [oven-sh/bun#1373]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Linux 5.15.0-1018-gcp #24~20.04.1-Ubuntu SMP Mon Sep 12 06:14:01 UTC 2022 x86_64

### What steps can reproduce the bug?

```js
const test = {
    test: 'WTF'
}

console.log(test.)
```

### What is the expected behavior?

syntax error

### What do you see instead?

![image](https://user-images.githubusercontent.com/60529600/197379568-d26ba3e8-83fd-44fb-bd58-78515f4fc7b1.png)

**Comment by Jarred-Sumner** [comment]
Looks like the logger is being silenced for some reason

<img width="449" alt="image" src="https://user-images.githubusercontent.com/709451/197382470-ed3925c5-ae77-425e-a068-8913a76d7142.png">
