### ISSUE TITLE
bun:sqlite Database .as(Class) parses boolean as number (does not honor type)

### ISSUE THREAD

**Issue by 8549** [oven-sh/bun#13737]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
import { Database } from "bun:sqlite";

export class Test {
  valid: boolean;
}

const db = new Database(":memory:", { strict: true });
db.query("CREATE TABLE IF NOT EXISTS test (valid BOOLEAN)").run();

const obj = {
  valid: true,
};

db.query("INSERT INTO test VALUES ($valid)").run(obj);

const result = db.query("SELECT * FROM test").as(Test).get();

console.log(typeof result?.valid);
```

### What is the expected behavior?

Output: `boolean`

### What do you see instead?

Output: `number`

### Additional information

I know that SQLite does not have a native boolean type. But the issue is that the `.as(Class)` method does not adhere to the class types.

**Comment by lkwr** [comment]
These kind of types are only exists in TypeScript. Without any extra work JavaScript can't figure out the type declaration of a class property because it does not exists in JavaScript.

You can solve it with a validator library or convert it yourself.

**Comment by Jarred-Sumner** [comment]
Unfortunately, `.as` is not aware of TypeScript type definitions. TypeScript types are build-time only. Maybe a decorator-based approach might work in the future, or potentially some way of hinting like a default initialized value (_maybe_)
