### ISSUE TITLE
Server request timeout after 9-15 seconds

### ISSUE THREAD

**Issue by mrgoonie** [oven-sh/bun#13745]
### What version of Bun is running?

1.1.26

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```typescript
const app = express();
app.get("/api", async (req, res) => {
  await new Promise((resolve) => setTimeout(resolve, 60_000));
  res.json({ ok: true });
});
app.listen(3000);

// Timeout after 9-12s
fetch("http://localhost:3000/api").then((res) => res.json()).then(console.log);
// ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "http://localhost:3000/api"
```

### What is the expected behavior?

Print `{ ok: true }` after 60 seconds.
It works normally with NodeJS or TSX.

### What do you see instead?

ConnectionClosed: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
 path: "http://localhost:3000/api"

### Additional information

I tried these approach but not working:
```typescript
var timeout = require('connect-timeout')
const app = express();

// [1] use timeout middleware
app.use(timeout());

app.get("/api", async (req, res) => {
  // [2] add timeout to req & res
  req.setTimeout(100_000);
  res.setTimeout(100_000);

  await new Promise((resolve) => setTimeout(resolve, 60_000));
  res.json({ ok: true });
});

const server = app.listen(3000);
// [3] server timeout
server.setTimeout(100_000);
```

**Comment by saminiemi** [comment]
We found same problem, related issue #13712 . Hopefully this problem will get more attention as it will currently broke all http services ran with Bun.
