### ISSUE TITLE
FDImpl.UV makes closing impossible!

### ISSUE THREAD

**Issue by yzrmsy** [oven-sh/bun#13750]
### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on windows x86_64 [RunCommand]

**panic**: Cast 476[handle] -> FDImpl.UV makes closing impossible!

The supplier of this FileDescriptor should call 'bun.toLibUVOwnedFD'
or 'FDImpl.makeLibUVOwned', probably where open() was called.

- [`js_ast.zig:3211`](<https://github.com/oven-sh/bun/blob/fe62a614046948ebba260bed87db96287e67921f/src/js_ast.zig#L3211>): `assert`
- [`JSCJSValue.h:752`](<https://github.com/oven-sh/bun/blob/fe62a614046948ebba260bed87db96287e67921f/C:/buildkite-agent/builds/windows-x64-hetzner-1/bun/bun/build/bun-webkit/include/JavaScriptCore/JSCJSValue.h#L752>): `JSC::ensureStillAliveHere`
- *2 unknown/js code*
- `llint_entry`

**Comment by yzrmsy** [comment]
[[](url)](https://github.com/oven-sh/bun/issues/13751)

**Comment by Electroid** [comment]
Will be fixed in https://github.com/oven-sh/bun/pull/13719
