### ISSUE TITLE
Bun does not read from $HOME/.npmrc if it exists

### ISSUE THREAD

**Issue by tobowers** [oven-sh/bun#13764]
### What version of Bun is running?

 v1.1.26-canary.13 (8d34846d)

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

create a ~/.npmrc with a different registry, that registry will not be respected during a `bun add`

### What is the expected behavior?

Bun can correctly read from project specific .npmrc files, so it should also read from the home directory too.

### What do you see instead?

The global .npmrc is ignored.

**Comment by tobowers** [comment]
#13199 #643 #12390

**Comment by robertshuford** [comment]
PR to add reading from `$HOME/.npmrc` https://github.com/oven-sh/bun/pull/13990
