### ISSUE TITLE
Bun install hangs/runs extremely slow on Windows

### ISSUE THREAD

**Issue by Nanome203** [oven-sh/bun#13801]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

First, clear the global cache or fresh install bun

Then create a vite project (react javascript template - this ended successfully)

After scaffolding the project, i ran : 
```ps
bun install --verbose
```

### What is the expected behavior?

Bun should install all the dependencies

### What do you see instead?

Bun hangs on some packages, Here's a photo of one of the hanged packages:

![image](https://github.com/user-attachments/assets/c9bf7434-85d0-46f2-9318-a5d6eaa68030)

### Additional information

I already turned of all AVs as well as set Windows Security to exclude ~\\ .bun. I'm also not using any proxy / third-party dns server. No network issues either.

**Comment by Jarred-Sumner** [comment]
Could you include the bun.lockb file?

**Comment by Nanome203** [comment]
> Could you include the bun.lockb file?

I can't, since bun install never finished, the bun.lockb file was never generated. But here's the package.json: 
```json
{
  "name": "ie106",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.9.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "eslint": "^9.9.0",
    "eslint-plugin-react": "^7.35.0",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.9",
    "globals": "^15.9.0",
    "vite": "^5.4.1"
  }
}
```

**Comment by Jarred-Sumner** [comment]
The interesting thing here is the 🚚 emoji means that it was extracting packages

so it got stuck extracting that package, for some reason

**Comment by Nanome203** [comment]
@Jarred-Sumner 
I just tried reproducing this bug on another Windows laptop. 
On first try, it successfully installed all the dependencies. 
Then i deleted node_modules folder, bun.lockb and all the cache in ~\\ .bun \\ install \\ cache.
Run `bun install --verbose` again and bun starts to hang

**Comment by Nanome203** [comment]
Updates:

After deleting all the temp files in `%LOCALAPPDATA%\Temp` and `C:\Windows\Temp`, bun somehow works properly again.

So i'm closing this issue for now
