### ISSUE TITLE
bun + alpine + node rust addons crash

### ISSUE THREAD

**Issue by izaakschroeder** [oven-sh/bun#13815]
### How can we reproduce the crash?

`.tool-versions`:
```
bun 1.1.27
```

`Dockerfile`:
```Dockerfile
FROM alpine:3.20.3

WORKDIR /workdir

COPY .tool-versions .tool-versions

# libc6-compat is needed by bun, node, etc.
RUN apk add mise libc6-compat git curl jq

# Setup tools
RUN mise install
ENV PATH="$PATH:/root/.local/share/mise/shims:/root/.bun/bin"
```

Run image:

```sh
docker build . -t test
docker run -ti test /bin/ash
```

Crash bun:

```sh
bun repl
```

### Relevant log output

```shell
bun repl
  ⚙️  @swc/core [1/1] ============================================================
Bun v1.1.27 (267afa29) Linux arm64
Linux Kernel v6.10.0 | glibc v2.8
Args: "node" "postinstall.js"
Features: jsc
Elapsed: 0ms | User: 0ms | Sys: 0ms
RSS: 1.07GB | Peak: 0.25GB | Commit: 1.07GB | Faults: 0

panic(main thread): A C++ exception occurred
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on linux aarch64 [RunAsNodeCommand]

**panic**: A C++ exception occurred

- [`bindings.zig:1936`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/bindings.zig#L1936>): `Zig__GlobalObject__onCrash`
- [`ZigGlobalObject.cpp:203`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/ZigGlobalObject.cpp#L203>): `JSCInitialize::$_0::__invoke`
- [`utf8_util.c:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/utf8_util.c#L0>): `__cxxabiv1::__terminate`
- [`utf8_util.c:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/utf8_util.c#L0>): `std::terminate`
- [`utf8_util.c:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/utf8_util.c#L0>): `__cxa_throw`
- [`divtf3.c:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/divtf3.c#L0>): `std::__throw_system_error`
- [`ZigGlobalObject.cpp:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/ZigGlobalObject.cpp#L0>): `JSCInitialize`
- [`bindings.zig:6673`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/bindings.zig#L6673>): `src.bun_js.Run.boot`
- [`run_command.zig:1635`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/cli/run_command.zig#L1635>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/main.zig#L50>): `main`

Features: jsc

**Comment by Jarred-Sumner** [comment]
We don’t officially support musl yet (#918), so this is expected when using musl node addons with bun. 

We don’t recommend using alpine with Bun until #918 is addressed

I suggest trying the Debian slim image

**Comment by izaakschroeder** [comment]
Ok will keep an eye on #918, thanks! 😄
