### ISSUE TITLE
Env variables are not read by bun

### ISSUE THREAD

**Issue by Renato66** [oven-sh/bun#13821]
### What version of Bun is running?

1.1.27

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```.env
API_TOKEN=$123==
API_TOKEN_2="$123=="
```

```sh
 bun --print process.env 
 ```

### What is the expected behavior?

 ```json
 {
   "API_TOKEN": "$123==",
   "API_TOKEN_2": "$123==",
 }
 ```

### What do you see instead?

 ```json
 {
   "API_TOKEN": "==",
   "API_TOKEN_2": "==",
 }
 ```

### Additional information

by using node and dotenv config we can have this variable with the correct value

**Comment by aashari** [comment]
Yes, using `dotenv` works as expected, my workaround for this is by adding backslash to the `$` character
```
API_TOKEN=\$123==
API_TOKEN_2="\$123=="
```

**Comment by Renato66** [comment]
@aashari yea its a feature explained here https://bun.sh/docs/runtime/env#expansion, but there is no warn over it;

would be better to have some **string concatenation** like so it wouldn't be miss leading with some secrets that contains $
```.env
DB_USER=postgres
DB_PASSWORD=secret
DB_HOST=localhost
DB_PORT=5432
DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
```

or some warn visually 

<img width="145" alt="image" src="https://github.com/user-attachments/assets/fae14bb7-a61a-4c04-9a57-6cdf01235967">

or a log if not defined
console.log('123 was not defined')

or throw an error as it's needed to be escaped
