### ISSUE TITLE
Cannot read body after `.tee()`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1382]
### What version of Bun is running?

0.2.1 (canary)

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64 arm

### What steps can reproduce the bug?

```ts
import { readableStreamToJSON } from "bun";

export default {
  async fetch(request) {
    try {
      const [body, cloned] = request.body.tee();
      console.log("body", await readableStreamToJSON(body));
      console.log("cloned body", await readableStreamToJSON(cloned));
    } catch (error) {
      console.log(error.stack);
    }
    return new Response("Ok");
  }
}

```

### How often does it reproduce? Is there a required condition?

Always. I tested `readableStreamToJSON` without a `tee` and it works fine, so this seems to be an issue with `tee`.

### What do you see instead?

```
readableStreamDefaultReaderRead@[native code]
@[native code]
promiseInvokeOrNoopMethodNoCatch@[native code]
promiseInvokeOrNoopMethod@[native code]
readableStreamDefaultControllerCallPullIfNeeded@[native code]
@[native code]
promiseReactionJob@[native code]
```

**Comment by Jarred-Sumner** [comment]
There is currently 0 test coverage for tee(), we should fix that. I haven’t modified it much from the WebKit implementation it’s based on, but enough of the rest of the streams implementation has diverged that bugs like these are unsurprising

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/360a007f160b6935140dc75003a503059ff23976
