### ISSUE TITLE
ffi varargs support

### ISSUE THREAD

**Issue by ohroy** [oven-sh/bun#13822]
### What is the problem this feature would solve?

can support varargs such as `printf`, `curl_set_opt`

### What is the feature you are proposing to solve the problem?

ffi

### What alternatives have you considered?

This is a somewhat complex edge problem with many considerations, such as call conventions, chips, systems, etc

esp on arm, it will read varargs from stack not register

**Comment by evanwashere** [comment]
you can wrap vararg functions with c in js https://bun.sh/blog/compile-and-run-c-in-js

**Comment by ohroy** [comment]
awesome！！！
