### ISSUE TITLE
Segfault with duckdb

### ISSUE THREAD

**Issue by ibash-corpusant** [oven-sh/bun#13836]
### How can we reproduce the crash?

```
bun install duckdb
```

run.js
```javascript
const duckdb = require('duckdb');
const db = new duckdb.Database(':memory:');

db.all(
  `SELECT *
   FROM read_parquet(['/path/to/large/parquet_file.parquet']);`,
  (err, res) => {
    if (err) {
      console.log("Error", err);
    } else {
      console.log('res.length', res.length)
    }
  }
);
```

### Relevant log output

```shell
$ bun run.js 
============================================================
Bun v1.1.24 (85a32991) Linux x64
Linux Kernel v5.10.0 | glibc v2.31
CPU: sse42 popcnt avx avx2
Args: "bun" "run.js"
Features: jsc tsconfig 
Builtins: "bun:main" "detect-libc" "node:assert" "node:buffer" "node:events" "node:fs" "node:os" "node:path" "node:stream" "node:string_decoder" "node:url" "node:util" "node:util/types" 
Elapsed: 12390ms | User: 19396ms | Sys: 1969ms
RSS: 1.07GB | Peak: 4.64GB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.24/la185a3299AiggggCu1o/jE+8mOyixhiF67lk8D48qoUkptqUo+rjU89kiU2/rslDs33x9CA2AQ
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000008

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `JSC::JSRopeString::resolveRopeToAtomString`
- [`JSString.h:824`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/./build/./build/bun-webkit/include/JavaScriptCore/JSString.h#L824>): `napi_set_property`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `icudt75_dat`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `icudt75_dat`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `icudt75_dat`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `icudt75_dat`
- [`napi.zig:1116`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/napi/napi.zig#L1116>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_120839`
- [`event_loop.zig:1251`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/bun.js/event_loop.zig#L1251>): `src.bun.js.event_loop.EventLoop.tick`

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.27. 

If you're still running into it after upgrading, please leave a comment

**Comment by ibash-corpusant** [comment]
Thanks @Jarred-Sumner! Works great!

**Comment by Jarred-Sumner** [comment]
100% of the credit goes to @190n for implementing napi handle scopes
