### ISSUE TITLE
bun install fails if suffix doesn't exist in the list of versions for the package

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#1385]
### What version of Bun is running?

2.1

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

bun install
bun install v0.2.1

error: No version matching "^0.6.0-alpha.9+f3f1b8b" found for specifier "babel-plugin-minify-simplify" (but package exists)

### How often does it reproduce? Is there a required condition?

Systematic

### What is the expected behavior?

packages to be installed in node_modules

### What do you see instead?

error: No version matching "^0.6.0-alpha.9+f3f1b8b" found for specifier "babel-plugin-minify-simplify" (but package exists)

### Additional information

As discussed with jarred on Discord: "its a bug - the bug is that the semver range includes suffixes as the minimum which fails if the suffix doesn't exist in the list of versions for the package"

**Comment by alexlamsl** [comment]
Fixed by #1854
