### ISSUE TITLE
Segfault using Web Workers

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#13888]
### How can we reproduce the crash?

I could not make a simple reproduction, even though this is happening 100% of the time in my code i could not reproduce it while narrowing it down.

In my code the only way to stop bun from segfaulting is to have invalid js code (which will end up crashing at runtime either way).

Worth noting that this also happens with the `Worker` from `node:worker_threads`

### Relevant log output

```shell
============================================================
Bun v1.1.27 (267afa29) Linux x64
WSL Kernel v5.15.153 | glibc v2.35
CPU: sse42 popcnt avx avx2
Args: "bun" "src/index.ts"
Features: jsc dotenv(14) fetch(6) tsconfig WebSocket(2) workers_spawned(6) workers_terminated 
Builtins: "bun:main" "bun:sqlite" "node:assert" "node:buffer" "node:crypto" "node:path" "node:string_decoder" "node:timers/promises" "node:util/types" 
Elapsed: 385ms | User: 337ms | Sys: 154ms
RSS: 0.45GB | Peak: 0.28GB | Commit: 0.45GB | Faults: 11

panic: Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.27/la1267afa2GioiggKuzlxlE+xyQskqltDw1ks+C8xx07D8i/j+C265luD06t27D2h+0iDksllBA2AA

error: script "dev" was terminated by signal SIGILL (Illegal instruction)
Illegal instruction
```

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000158

- [`web_worker.zig:342`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/web_worker.zig#L342>): `src.bun.js.web_worker.WebWorker.onUnhandledRejection`
- [`javascript.zig:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/javascript.zig#L0>): `Bun__handleRejectedPromise`
- [`ZigGlobalObject.cpp:3737`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/ZigGlobalObject.cpp#L3737>): `JSC__JSGlobalObject__handleRejectedPromises`
- [`bindings.zig:3249`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/bindings.zig#L3249>): `src.bun.js.event_loop.EventLoop.tick`
- [`event_loop.zig:1535`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/event_loop.zig#L1535>): `src.bun.js.javascript.OpaqueWrap__anon_158230__struct_165134.callback`
- [`bindings.cpp:4878`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/bindings.cpp#L4878>): `JSC__VM__holdAPILock`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/shimmer.zig#L197>): `Thread.PosixThreadImpl.spawn__anon_111054.Instance.entryFn`

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
