### ISSUE TITLE
panic: Segmentation fault at address 0x325AE8FB8

### ISSUE THREAD

**Issue by ImBIOS** [oven-sh/bun#13885]
### How can we reproduce the crash?

As per this issue was first created, IDK what caused this, and it's happened for the first time. Maybe if it happen several times, I might know how to reproduce it.

My condition when this panic happened, I was scraping some (more than 1000) web with `puppeteer-cluster`, for my research.

UPDATE 1: It never happened before, I've been scraping some (less than a thousand) pages each scraping run, this whole 2 months. It's my first time scrape more than 1000 pages in a single run, this whole 2 months. Using Bun, I love ❤️ bun.

### Relevant log output

```shell
============================================================
Bun v1.1.27 (267afa29) Linux x64
Linux Kernel v6.8.0 | glibc v2.39
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "index.ts" "-b" "true" "-l" "trace"
Features: jsc Bun.stdin(2) Bun.stdout bunfig dotenv(536) fetch(68) spawn(360) transpiler_cache(15) tsconfig_paths tsconfig(7) WebSocket(46) workers_spawned(535) workers_terminated(526)
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws"
Elapsed: 602224ms | User: 162422ms | Sys: 36862ms
RSS: 0.02ZB | Peak: 1.74GB | Commit: 0.02ZB | Faults: 36625

panic: Segmentation fault at address 0x325AE8FB8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.27/la1267afa2G6qig0LuzlxlE+xpRi54g2Cmxkl8C4+x+1CwyptlDo/qlgD4zmlgD6z443Ds7yojFA2Gw7n61lB
```

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x325AE8FB8

- [`hash_map.zig:1315`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/deps/zig/lib/std/hash_map.zig#L1315>): `src.allocators.BSSMap.BSSMapType.getOrPut`
- [`resolver.zig:2650`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/resolver/resolver.zig#L2650>): `src.resolver.resolver.Resolver.dirInfoCached`
- [`resolver.zig:1214`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/resolver/resolver.zig#L1214>): `src.resolver.resolver.Resolver.resolveAndAutoInstall`
- [`javascript.zig:2183`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/javascript.zig#L2183>): `src.bun.js.javascript.VirtualMachine._resolve__anon_120549`
- [`javascript.zig:2364`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/javascript.zig#L2364>): `src.bun.js.javascript.VirtualMachine.resolveMaybeNeedsTrailingSlash__anon_99280`
- [`javascript.zig:2270`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/javascript.zig#L2270>): `Zig__GlobalObject__resolve`
- [`ZigGlobalObject.cpp:3870`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bun.js/bindings/ZigGlobalObject.cpp#L3870>): `Zig::GlobalObject::moduleLoaderResolve`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/ld-temp.o#L0>): `JSC::moduleLoaderResolve`

**Comment by Jarred-Sumner** [comment]
Does this crash occur if you don't use `Worker`?

**Comment by ImBIOS** [comment]
In my codebase itself, I'm not using Bun's `Worker` (I've tried it, but it caused another roadblock, so I'm using `puppeteer-cluster`), maybe `Worker` automatically used by `puppeteer-cluster` (?)

Are you asking me to try running puppeteer without `puppeteer-cluster`?

**Comment by ImBIOS** [comment]
UPDATE 1: It never happened before, I've been scraping some (less than a thousand) pages each scraping run, this whole 2 months. It's my first time scrape more than 1000 pages in a single run, this whole 2 months. Using Bun, I love ❤️ bun.

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
