### ISSUE TITLE
Debugging support on windows machines.

### ISSUE THREAD

**Issue by smultar** [oven-sh/bun#13895]
### What is the problem this feature would solve?

Allows users to debug and write more efficient code, without having to use libraries like `tsx` or `node-ts`

### What is the feature you are proposing to solve the problem?

Can you update the bun extension, to support functionality on native windows, without requiring wsl?

### What alternatives have you considered?

The alternatives require me to use other tooling instead of sticking to bun exclusively.

**Comment by elemental-mind** [comment]
Could you elaborate what currently doesn't work?

There should be native inspector support, but also VSCode debugging support:

https://github.com/oven-sh/bun/issues/8851
