### ISSUE TITLE
fetch('http://localhost:8080') fails

### ISSUE THREAD

**Issue by maor-benami** [oven-sh/bun#1389]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

```javascript
// server.js
import http from 'node:http'

await new Promise((resolve) => {
  const server = http.createServer()

  server.listen(8080, () => {
    console.log('running')
    resolve()
  })
})

fetch('http://localhost:8080').then((res) => {
  console.log(res)
})
```

```
bun server.js
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

using `fetch('http://127.0.0.1:8080')` seems to work

### What do you see instead?

```
ConnectionRefused: fetch() failed
  path: "http://localhost:8080"
```

**Comment by eli-rich** [comment]
```ts
Bun.serve({
  port: 8080,
  fetch(request) {
    return new Response('Hello World!');
  },
});

fetch('http://localhost:8080').then(async res => {
  console.log(await res.text());
});
```
Works for me

Edit:

This works for me in Bun and in node:
```ts
import { createServer } from 'node:http';

const server = createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('Hello World');
});

server.listen(8080);

const data = await fetch('http://localhost:8080');
console.log(await data.text());
```

**Comment by mganeko** [comment]
I have same problem on Ubuntu 22.04 LTS.
But it works fine on Ubuntu 20.04 LTS and macOS 12.

In addition, if I use host option (not documented) it works fine one Ubuntu 22.04.
I guess it is related with IPv4 / IPv6 address.

```js
const PORT = 8000;
const HOST = 'localhost';
const URL = 'http://localhost:' + PORT;

Bun.serve({
  port: PORT,
  host: HOST,
  fetch(request) {
    return new Response('Hello World!');
  },
});

fetch(URL).then(async res => {
  console.log(await res.text());
});
```
