### ISSUE TITLE
Bun Bundler Crashes on Windows when path includes `\` for plugins

### ISSUE THREAD

**Issue by rametta** [oven-sh/bun#13897]
### How can we reproduce the crash?

Create a build with a plugin that looks something like this:

```ts
const buildOut = await Bun.build({
  entrypoints: [ROOT_ENTRY],
  outdir: DIST,
  minify: true,
  sourcemap: "linked",
  plugins: [
    {
      name: "My windows plugin",
      async setup(build) {
        build.onResolve({ filter }, () => ({ path: "C:\some\windows\path" }))
      },
    },
  ],
})
```

Bun crashes because a windows path is returned from the plugin setup's onResolve callback

Temporary hack I found to fix is to do: ` "C:\some\windows\path".replaceAll("\\", "/")`

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on windows x86_64 [AutoCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Users\Ramet\Desktop\Repos\brick-breaker\.secret\generated.ts'

- [`fs.zig:1722`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/fs.zig#L1722>): `assertPrettyIsValid`
- [`bundle_v2.zig:6487`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/bundler/bundle_v2.zig#L6487>): `generateChunkJS`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/src/deps/zig/lib/std/atomic.zig#L40>): `load`

**Comment by aralroca** [comment]
I have the same problem
