### ISSUE TITLE
using fetch with a '@' in the url is stuck

### ISSUE THREAD

**Issue by maor-benami** [oven-sh/bun#1390]
### What version of Bun is running?

0.2.1

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

```javascript
// server.js
import http from 'node:http'

await new Promise((resolve) => {
  const server = http.createServer((req, res) => {
    res.end()
  })

  server.listen(8080, () => {
    console.log('running')
    resolve()
  })
})

fetch('http://127.0.0.1:8080/@/test').then((res) => {
  console.log(res)
})
```

```
bun server.js
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

regular fast response

### What do you see instead?

it takes a very long time for the server to respond

**Comment by Jarred-Sumner** [comment]
We should potentially use WebKit's URL parser instead of Bun's - or rewrite Bun's URL parser to handle more cases.

**Comment by chrisAXZA** [comment]
For the long-term better to expand Bun's parser, instead of relying on WebKit?
