### ISSUE TITLE
`bun install` error: Failed to link @node-kit/extra.fs: ENOENT

### ISSUE THREAD

**Issue by quirin-buechner-mdctec** [oven-sh/bun#13942]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown (<- Inside Docker Desktop on Windows 11)

### What steps can reproduce the bug?

```bash
# start a container with bun
docker run -it oven/bun:debian bash;

# inside the container, install the 'workspace-root' package:
bun install workspace-root
```

### What is the expected behavior?

should install package with all dependencies

### What do you see instead?

This causes the following error:
```
bun add v1.1.27 (267afa29)
error: Failed to link @node-kit/extra.fs: ENOENT

error: Failed to link @node-kit/lerna-workspace-root: ENOENT

error: Failed to link @node-kit/pnpm-workspace-root: ENOENT

error: Failed to link @node-kit/yarn-workspace-root: ENOENT

error: Failed to link workspace-root: ENOENT
```

### Additional information

Tree of npm dependencies:
```yaml
'workspace-root':
  - '@node-kit/pnpm-workspace-root':
      - '@node-kit/extra.fs'
      - '@pnpm/error'
      - 'find-up'
  - '@node-kit/lerna-workspace-root':
      - '@node-kit/extra.fs'
      -  'find-up'
  - '@node-kit/yarn-workspace-root': 
      - '@node-kit/extra.fs'
      - 'find-up'
      - micromatch
```
See [https://www.npmjs.com/package/workspace-root?activeTab=readme](https://www.npmjs.com/package/workspace-root?activeTab=readme)

Maybe the `dot` in the package name '@node-kit/extra.fs' is causing problems? 🤔

**Comment by dylan-conway** [comment]
Bun needs to not error when a package provides `directories.bin` and the folder does not exist
