### ISSUE TITLE
using ReadableStream as Response will not send each chunk one by one but in batches

### ISSUE THREAD

**Issue by BennyAlex** [oven-sh/bun#13944]
### Discussed in https://github.com/oven-sh/bun/discussions/13923

<div type='discussions-op-text'>

<sup>Originally posted by **BennyAlex** September 12, 2024</sup>
I return a ReadableStream in a bun.serve server, but in the browser I always see multiple chunks at once instead of getting one by one.

Is this normal? Can I change this behavior?</div>

If I call res.write in node.js I can send multiple chunks one by one without issues.

In bun I mostly get multiple chunks (In the browser) at once when I return new Response(new ReadableStream()).

**Comment by Jarred-Sumner** [comment]
If you want to control the batching behavior, you must add an artificial delay or call flush() manually. 

TCP & HTTP make zero guarantees about how much data will be received at once. It is up to the server, your network, your ISP, your browser, your NIC, and everything else between your machine and their machine. 

If you rely on receiving complete messages from the network in your code, your code will be buggy - whether that’s Node or bun or elsewhere.  You might not see those bugs happening locally, but your users eventually will. 

Websocket is an example of a protocol with message framing handled for you. It buffers each message until the complete message is received. Server-sent events are another.

**Comment by BennyAlex** [comment]
@Jarred-Sumner 
Thanks for clearifing this.
As far as I know the SSE are not possible in bun.serve or?

**Comment by BennyAlex** [comment]
But there must be some caching or waiting happen in bun since only a delay of atleast 400ms will cause each chunk to be send at once. In node a much smaller one is sufficent and the answer is still very continious and does not take that long
