### ISSUE TITLE
Bun executes obfuscated code (target=browser) about 100x-600x slower than Node.js / ts-node / chromium browser console

### ISSUE THREAD

**Issue by ajfhs812** [oven-sh/bun#13940]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

1. Go to [https://pastebin.com/raw/xc1uanbE](https://pastebin.com/raw/xc1uanbE).
2. Copy the raw code.
3. Then, run it using:
   1. **Bun**:
      1. Paste it into a local JS file on your system.
      2. Run it via `bun run <path_to_the_file>.js`.
   2. **bunx ts-node** (similar steps as for Bun).
   3. **Node.js** (similar steps as for Bun).
   4. **Browser's console** (paste and run).

How did I get the code:
1. Built source TS code using Bun (`NODE_ENV=production bun build --minify --target=browser <PATH_TO_INPUT_FILE> --outfile=<PATH_TO_OUTPUT_FILE>`).
2. Then, received code from Bun uglified+mangled+minified with [terser](https://www.npmjs.com/package/terser) (`NODE_ENV=production bunx terser <PATH_TO_INPUT_MINIFIED_FILE> --compress='drop_console=false,unsafe_arrows=true,unsafe_comps=true,unsafe_Function=true,unsafe_math=true,unsafe_symbols=true,unsafe_methods=true,unsafe_proto=true,unsafe_regexp=true,unsafe_undefined=true,unsafe=true,ecma=2020,hoist_funs=true,toplevel=true,pure_new=true,passes=10'  --format='semicolons=true,beautify=false,ecma=2020,quote_style=1' --mangle 'eval=true,module=true,toplevel=true' --mangle-props --toplevel --comments=false --indent_level=1 --module  -o <PATH_TO_OUTPUT_UGLIFIED_FILE>`).
3. Then, received code from terser obfuscated using [obfuscator.io](https://www.obfuscator.io/#code).

P.S: if you need the source code of some (or even each) of these steps, let me know.

### What is the expected behavior?

1. Bun should execute it fast enough.
5. Bun should execute it maybe even more faster than Node.js, ts-node, browser's console, and other tools.

### What do you see instead?
Bun is doing it much slower than expected.

#### Benchmark results for that code I provided above:
- **Bun:** about 2.60s-2.80s (seconds);
- **ts-node:** about  6.800ms-7.278ms;
- **Node.js:** about 15.466ms-24.000ms;
- **Chromium browser's console:** about 4.733ms-5.401ms.

#### Computer specs:
-  **CPU:** Intel i9-9880H (16) @ 2.30GHz
- **Memory:** 10014MiB / 16384MiB
- **Host:** MacBookPro15,1
- **OS:** macOS 14.1.1 23B81 x86_64

**Comment by 190n** [comment]
Can you share the code before compiling and obfuscation?
