### ISSUE TITLE
bun crashes when using docker layers but fine wthout them

### ISSUE THREAD

**Issue by mohsen-tahmasebi** [oven-sh/bun#13969]
### How can we reproduce the crash?

```dockerfile
FROM oven/bun:1-alpine as base

FROM base AS deps

WORKDIR /app 

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN bunx prisma generate 
RUN bun build ./index.ts --outdir ./build --target=node

FROM base AS runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./
COPY --from=builder /app/sounds ./sounds

ENV NODE_ENV=production

USER bun

EXPOSE 3000

CMD ["bun", "index.js"]
```

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x0004A0D0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/ld-temp.o#L0>): `char32_t WTF::Unicode::next<(...)0, char8_t>`

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/12905
