### ISSUE TITLE
Add "-r, --require" in cmd bun run

### ISSUE THREAD

**Issue by Shuruhatik** [oven-sh/bun#1398]
### What is the problem this feature would solve?

Preload the specified module at startup.

### What is the feature you are proposing to solve the problem?

Preload the specified module at startup.

Follows require()'s module resolution rules. module may be either a path to a file, or a npm package name.

### What alternatives have you considered?

From some alternatives, I think the name "preload" can be used instead of "require" to give more clarification on its usefulness!

**Comment by Jarred-Sumner** [comment]
This was added, both as `-r` and as `--preload`. It technically uses `import` instead of `require`.
