### ISSUE TITLE
Breakpoints not hit in async code using debug adapter

### ISSUE THREAD

**Issue by Soarex16** [oven-sh/bun#13994]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

The problem is that breakpoints don't hit if the code contains async functions.

To reproduce, try to debug this sample using `bun-vscode` plugin:

```javascript
console.log('Script started');

async function start() {
    console.log('Starting async function...');
    const test = 'Hello from async function!';
    console.log(test); // breakpoint (ignored)
}

console.log('Starting job...'); // breakpoint (ignored)

start()
    .then(() => console.log(0))
    .catch((e) => {
        console.error('Job failed: ', e);
        process.exit(1);
    })
```

At the same time, if you try to run the same example with WebInspector-based debugger (https://debug.bun.sh) or Safari, all breakpoints hit.

### Additional information

Initially, this issue was reported in WebStorm ([YouTrack](https://youtrack.jetbrains.com/issue/WEB-68018/Bun-debugger-ignores-breakpoints-in-async-function)).

After some investigation, I found out that the problem lies somewhere in the debug adapter used by the Bun plugins for WebStorm and VS Code.

I had the assumption that it was because `Debugger.resume` [was sent](https://github.com/oven-sh/bun/blob/main/packages/bun-debug-adapter-protocol/src/debugger/adapter.ts#L1466) without awaiting for the future breakpoints to be set. I tried to make a quick fix to check if this was the case, but it turned out that the problem persists.

Here are some examples I used during my investigation: [repro.zip](https://github.com/user-attachments/files/17026578/repro.zip)

**Comment by RiskyMH** [comment]
@Soarex16 do you still run into this issue? I have tried latest bun with latest webstorm and vscode (with extension) and they seem to both respect the 2 breakpoints now!
