### ISSUE TITLE
crash using rpio on windows 10 (22H2 19045.3803) with bun

### ISSUE THREAD

**Issue by draneone** [oven-sh/bun#14004]
### How can we reproduce the crash?

using rpio on windows 10 (22H2 19045.3803) with bun
https://replit.com/@idraneone/rpio-windows-bun-crash?v=1

index.ts:
```
import rpio from 'rpio';

rpio.init({
    mapping: 'physical',
    gpiomem: false,
    mock: "raspi-zero-w",
    close_on_exit: true
});


rpio.open(11, rpio.OUTPUT, rpio.LOW);

```

package.json: 
```
{
  "name": "bun-rpi-sandbox",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "start": "bun run index.ts"
  },
  "devDependencies": {
    "@types/bun": "latest",
    "@types/rpio": "^2.4.6"
  },
  "trustedDependencies": ["rpio"],
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "rpio": "^2.4.2"
  }
}
``

### Relevant log output

```shell
bun start
$ bun run index.ts
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: @>87>H5; A1>9 2 ?@>3@0<<5 8=8F80;870F88 1
      at bindings (C:\projects\bun-rpi-sandbox\node_modules\bindings\bindings.js:112:48)
      at C:\projects\bun-rpi-sandbox\node_modules\rpio\lib\rpio.js:17:5

Bun v1.1.24 (Windows x64)
============================================================
Bun v1.1.24 (85a32991) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\ddrain\.bun\bin\bun.exe" "run" "index.ts"
Features: jsc tsconfig(2) 
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util/types" 
Elapsed: 84ms | User: 15ms | Sys: 15ms
RSS: 121.32MB | Peak: 121.33MB | Commit: 0.17GB | Faults: 29872

panic(main thread): Segmentation fault at address 0x7FF827AA242C
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFD012B1620

- *1 unknown/js code*
- ??? at `0x5deb5` in ntdll.dll
- ??? at `0x5dbab` in ntdll.dll
- ??? at `0x5da8d` in ntdll.dll
- ??? at `0x1e3bb` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/Global.zig#L121>): `exit`
- [`javascript.zig:1267`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/bun.js/javascript.zig#L1267>): `globalExit`
- [`javascript.zig:1179`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/src/bun.js/javascript.zig#L1179>): `eventLoop`

**Comment by alexvrv** [comment]
That library seems to work only on "Node.js Versions: 0.8, 0.10, 0.12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14." 
I think that's the problem... BUN is made to replace Node 20/22 as far as I know
