### ISSUE TITLE
bun build cause Elysia to panic on cluster mode

### ISSUE THREAD

**Issue by SaltyAom** [oven-sh/bun#14027]
### What version of Bun is running?

1.1.28

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Clone repro
```bash
git clone http://github.com/saltyaom/elysia-cluster-demo
```

2. Build
```bash
cd elysia-cluster-demo && bun run build
```

3. Run
```bash
bun ./dist/index.js
```

### What is the expected behavior?

It should not crash

### What do you see instead?

TypeError: Y of p1 is not a function. (In 'Y of p1(H)', 'Y of p1' is undefined)

### Additional information

Bundled code using Bun build cause panic on run.

This error only happens on Bun 1.1.28 and not on previous versions.

**Comment by nektro** [comment]
PR linked above should have fixed this but did not link it. if the issue persists please let us know
