### ISSUE TITLE
SegmentationFault when running async function inside setInterval

### ISSUE THREAD

**Issue by 0x4a61636f62** [oven-sh/bun#1403]
### What version of Bun is running?

Bun v0.2.0

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

The following async function should run at a set interval but sometimes results in a `SegmentationFault at 0x7000000000000000` and does not run at all. 

**Code**

```
setInterval(async function () {
  if (new Date().getSeconds() === 0) {
    await restClient
      .getLatestMultiBars({
        symbols: ["AAPL", "TSLA"],
      })
      .then((res) => res.json())
      .then((json) => json["bars"]) 
      .then((bars) => {
        Object.entries(bars).forEach(([symbol, bar]: [string, any]): void => {
          console.log("bar=", bar);
          console.log("symbol=", symbol);
        });
      });
  }
}, 1000);
```

### How often does it reproduce? Is there a required condition?

Half of the time, the code throws the segfault the first time the function is called.

### What is the expected behavior?

No segfault.

### What do you see instead?

The debug console shows:

```
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /home/myuser/bin/bun-profile /home/myuser/project/src/main.ts
Launched process 22203
[0.33ms] ".env"
RestClient instance created
Stop reason: signal SIGSEGV: invalid address (fault address: 0x70)

SegmentationFault at 0xB4560000E8030000


----- bun meta -----
Bun v0.2.2 (6632135e) Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
AutoCommand: dotenv 
Elapsed: 79168ms | User: 273ms | Sys: 35ms
RSS: 69.21MB | Peak: 68.08MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

Process exited with code 139.

```

The file `@us_socket_context_get_native_handler` shows:

```

; id = {0x00013ed9}, range = [0x0000000003f1b000-0x0000000003f1b011), name="us_socket_context_get_native_handle"
; Source location: /build/bun/src/deps/uws/uSockets/src/context.c:143
03F1B000: 85 FF                      testl  %edi, %edi
03F1B002: 74 0A                      je     0x3f1b00e  ; <+14> at context.c
03F1B004: 55                         pushq  %rbp
03F1B005: 48 89 E5                   movq   %rsp, %rbp
03F1B008: 48 8B 46 70                movq   0x70(%rsi), %rax
03F1B00C: 5D                         popq   %rbp
03F1B00D: C3                         retq   
03F1B00E: 31 C0                      xorl   %eax, %eax
03F1B010: C3                         retq   
```

**Comment by 0x4a61636f62** [comment]
@Electroid I am keen to know if you see any issues resulting from bugs in my code, or whether this is a segfault caused by Bun? Perhaps there is a way I can generate a core file to debug and see if any lines are causing the issue?

By the way, I made some slight updates to the code above for easier readability. I have also updated Bun to `v0.2.2` with the same result.

**Comment by Jarred-Sumner** [comment]
0x7 is “null” in JS so it looks like something internally is being set to null unexpectedly 

One thing that sticks out is new Date() - it’s calling toString() on that most likely. If you manually call .toString() on the Date does that workaround the issue?

Can you download a -profile build of Bun? That will include a stack trace with debug symbols so that we can see more detailed information

**Comment by 0x4a61636f62** [comment]
Thanks, @Jarred-Sumner, for the reply. the `new Date()` doesn't seem to be the issue. I tried swapping it for a string constant, and the same issue occurred.

The following code should work as far as I can tell, however it also crashes with the same segfault:

```
setInterval(async function () {
  if (new Date().getSeconds() === 0) {
    await restClient
      .getLatestMultiBars({
        symbols: ["AAPL", "TSLA"],
      })
      .then((res) => res.json())
      .then((json) => json["bars"])
      .then((bars) => {
        Object.entries(bars).forEach(([symbol, bar]: [string, any]): void => {
          console.log("bar=", bar);
          console.log("symbol=", symbol);
        });
      });
  }
}, 1000);
```

I don't see any issue with the above code, so I suspect the issue is in Bun, perhaps only for Linux WSL.

> Can you download a -profile build of Bun? That will include a stack trace with debug symbols so that we can see more detailed information

I tried to set up the development environment for Bun previously, but to be honest, I failed and gave up. It might be that I don't have the hardware necessary but I'll nevertheless give it another try.

**Comment by Jarred-Sumner** [comment]
`-profile` builds can be downloaded without compiling Bun from the releases and canary page

Here is the one for your OS + arch: https://github.com/oven-sh/bun/releases/download/bun-v0.2.2/bun-linux-x64-profile.zip

**Comment by 0x4a61636f62** [comment]
Thanks @Jarred-Sumner!

I have tried to run it with the bun-profile but am not able to make it run.

The debugger outputs:

```
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /home/myuser/project/test/bun-profile /home/myuser/project/src/main.ts
```

Then a prompt shows up, which I have no idea of what it means:
![image](https://user-images.githubusercontent.com/50423468/198852698-1b5bf8d3-8e35-45c5-8287-3bb27b7b4d2a.png)

This is what my `launch.json` looks like:

```
{
  "version": "0.2.0",
  "configurations": [
    
    {
      "type": "lldb",
      "request": "launch",
      "name": "bun-profile current file",
      "program": "/home/myuser/bin/bun-profile",
      "args": ["${file}"],
      "cwd": "${file}/../../",
      "env": {
        "FORCE_COLOR": "1"
      },
      "console":"internalConsole"
    }
  ]
}
```
According to [HERE](https://github.com/vadimcn/vscode-lldb/wiki/Debugger-startup-problems#a-packet-returned-an-error) the message `'A' packet returned error: 8` means:


> This is the catch-all message for LLDB's failure to create the debuggee process. Some common reasons include:

> * The current working directory ("cwd") does not exist or is not accessible by the current user.
> * Debugging inside an unprivileged Docker container with disabled [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization). While disabling ASLR is generally desirable during debugging (because it may cause non-determinism of program execution), doing so may be disallowed by the default container security profile. Possible solutions:
> ** Relax container security profile by starting it with --security-opt seccomp=unconfined option.
> ** Turn off ASLR disabling by adding "initCommands": ["set set target.disable-aslr false"] to your launch configuration.


My file privileges:

```
drwxr-xr-x  2 myuser myuser      4096 Oct 30 00:06 ./
drwxr-xr-x 16 myuser myuser      4096 Oct 30 00:06 ../
-rw-r--r--  1 myuser myuser 124193808 Oct 28 01:16 bun-profile
-rw-r--r--  1 myuser myuser        90 Oct 28 01:16 bun-profile:Zone.Identifier
```

**Comment by 0x4a61636f62** [comment]
After changing permissions to write `-rwx rx rx` I think I was able to debug.

The debug console shows:

```
Console is in 'commands' mode, prefix expressions with '?'.
Launching: /home/myuser/bin/bun-profile /home/myuser/project/src/main.ts
Launched process 22203
[0.33ms] ".env"
RestClient instance created
Stop reason: signal SIGSEGV: invalid address (fault address: 0x70)

SegmentationFault at 0xB4560000E8030000


----- bun meta -----
Bun v0.2.2 (6632135e) Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
AutoCommand: dotenv 
Elapsed: 79168ms | User: 273ms | Sys: 35ms
RSS: 69.21MB | Peak: 68.08MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

Process exited with code 139.

```

The file `@us_socket_context_get_native_handler` shows:

```

; id = {0x00013ed9}, range = [0x0000000003f1b000-0x0000000003f1b011), name="us_socket_context_get_native_handle"
; Source location: /build/bun/src/deps/uws/uSockets/src/context.c:143
03F1B000: 85 FF                      testl  %edi, %edi
03F1B002: 74 0A                      je     0x3f1b00e  ; <+14> at context.c
03F1B004: 55                         pushq  %rbp
03F1B005: 48 89 E5                   movq   %rsp, %rbp
03F1B008: 48 8B 46 70                movq   0x70(%rsi), %rax
03F1B00C: 5D                         popq   %rbp
03F1B00D: C3                         retq   
03F1B00E: 31 C0                      xorl   %eax, %eax
03F1B010: C3                         retq   
```

I have updated the issue title and description.

**Comment by 0x4a61636f62** [comment]
Changing `.then()` to full await gives the same result; most of the time it throws the segfault but sometimes it gives the expected result.

**Comment by Jarred-Sumner** [comment]
@jastraberg can you try in `bun upgrade --canary`

I made some tweaks last night to this code

**Comment by 0x4a61636f62** [comment]
In canary, both full await and `then()` throws a segfault.

**Comment by Jarred-Sumner** [comment]
Can you try once again?

**Comment by 0x4a61636f62** [comment]
Sorry Jarred, it still seems to throw the segfault with the latest canary.

```
SegmentationFault at 0x7000000000000000


----- bun meta -----
Bun v0.2.3 (cb41d77d) Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
AutoCommand: dotenv 
Elapsed: 37065ms | User: 24ms | Sys: 169ms
RSS: 69.21MB | Peak: 63.21MB | Commit: 69.21MB | Faults: 0
----- bun meta -----
```

**Comment by Jarred-Sumner** [comment]
I'm going to need a complete repro to fix this

Can you paste a minimal reproduction? Thanks for being patient with all the back-and-forth

**Comment by 0x4a61636f62** [comment]
No problem @Jarred-Sumner. Here is a minimal reproduction (I will PM you the key and secret):

```
const apiKey = 'KEY';
const apiSecret = 'SECRET';

async function getLatestBar() {
  const path = `AAPL/bars/latest`;
  const url = new URL(path, 'https://data.alpaca.markets/v2/stocks/');

  try {
    return await fetch(url.href, {
      method: "GET",
      headers: new Headers({
        "APCA-API-KEY-ID": apiKey,
        "APCA-API-SECRET-KEY": apiSecret,
        "Content-Type": "application/json",
      }),
      redirect: "follow",
    }).then((res) => {
      if (res.ok) return res;
      else {
        throw new Error(`status: ${res.status}\nstatusText: ${res.statusText}\nType: ${res.type}`);
      }
    });
  } catch (error) {
    console.log(error);
  }
}

setInterval(async () => {
  if (new Date().getSeconds() === 0) {
    await getLatestBar().then((res) => res.json()).then((json) => console.log(json));
  }
}, 1000);
```

**Comment by Jarred-Sumner** [comment]
sounds good
