### ISSUE TITLE
Unable to Retrieve C Function Return Value/Response  'cstring' Using bun-ffi in JavaScript

### ISSUE THREAD

**Issue by exvillager** [oven-sh/bun#14041]
### What is the type of issue?

Documentation is missing

### What is the issue?

well this isnt issue of bun maybe its my skill issue.

here is what problem im getting  - evrything works correct but im getting memory address of return string value in js .

here is the  c code -  ``
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char* parse_headers(const char *string) {
    if (string == NULL) {
        return "{\"error\":\"Received NULL pointer\"}";
    }
    return "hello pradeep";
}

``
where im returning a normal string.

and here is js code - ``
module.exports = {
  symbols: { parse_headers }
} = cc({
  source: pathToCFile,
  symbols: {
    parse_headers: {
      returns: "cstring",
      args: ["cstring"]
    }
  }
});

const response = parse_header();

console.log(response) 
// in console i get 
memory address or pointer of the returned valude 

pradeep@pradeep:~/Desktop/maya$ bun test/tester.js 
Server is running on http://localhost:3000
2902931759186

``

 so my problem is that how can i access this pointer value in js?? because there is no documentation about how to get value from c code or how to get value of return pointer from c function

**Comment by evanwashere** [comment]
https://bun.sh/docs/api/ffi#strings

**Comment by pradeepbgs** [comment]
Thanks 👍
