### ISSUE TITLE
Add support for process.release

### ISSUE THREAD

**Issue by coolaj86** [oven-sh/bun#1404]
### What is the problem this feature would solve?

`process.release.name` is useful for runtime debugging / comparing versions, constructing User-Agent strings, and just knowing whether you're running `bun` or `node`.

### What is the feature you are proposing to solve the problem?

Replicate https://nodejs.org/api/process.html#processrelease 

```js
{
  name: 'bun',
  lts: '',
  sourceUrl: 'https://github.com/oven-sh/bun/release/v0.x/bun-v0.x-arch-os.tar.gz',
  headersUrl: '',
  libUrl: ''
}
```

### What alternatives have you considered?

Make a PR on the things that use `platform.release` to instead check `process.versions.bun` or `process.title` or `process.isBun`... or `platform?.release.name ?? 'unknown'`.

**Comment by Jarred-Sumner** [comment]
Sure

**Comment by Jarred-Sumner** [comment]
Done https://github.com/oven-sh/bun/commit/901c4f57aa1fd0914c5f153fe56768f23b7a6511

**Comment by Jarred-Sumner** [comment]
That being said, the best way to get a user agent in bun: `navigator.userAgent`

The best way to know whether it is Bun or Node without relying on globals which may not exist: `!!process.isBun`

**Comment by pzmarzly** [comment]
This is now returning fake data:

https://github.com/oven-sh/bun/blob/ec0e931e9f7934f4f1f7617eac2a880d13794d0c/src/bun.js/bindings/Process.cpp#L862-L865

I switched to using `if (process.versions.bun !== undefined)`, as `process.isBun` is missing in TS definitions.
