### ISSUE TITLE
`bun wiptest` segfaults when not given paths

### ISSUE THREAD

**Issue by sno2** [oven-sh/bun#1406]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

Run `bun wiptest` in any location.

### How often does it reproduce? Is there a required condition?

Every time.

### What is the expected behavior?

It should show the dialogue that happens when you run `bun wiptest foo.js` when `foo.js` is an empty file:

```
 0 pass
 0 fail
 Ran 0 tests across 0 files [297.00ms]
```

### What do you see instead?

```
sno2@Carter-PC:~/projects/bun/bun$ bun wiptest

SegmentationFault at 0x3000000000000000


----- bun meta -----
Bun v0.2.2 (792ad30a) Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
TestCommand: 
Elapsed: 291ms | User: 43ms | Sys: 87ms
RSS: 69.21MB | Peak: 96.10MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

```

### Additional information

Here is the call stack in LLDB.  Seems like it's trying to setup a server.

![image](https://user-images.githubusercontent.com/43641633/198495505-8035c5c7-a2c6-4ab0-ad49-822b7af31ca6.png)

**Comment by Jarred-Sumner** [comment]
I'm not yet able to reproduce this on a debug or release build

Are you sure the expected version of uWebSockets installed on your machine? This has been updated a few times in the past few weeks

`git submodule foreach git submodule sync && git submodule sync`

**Comment by sno2** [comment]
Isn't UWS statically linked? I tested this using the version of bun from `bun upgrade --canary`.

**Comment by Jarred-Sumner** [comment]
hm maybe its linux specific

**Comment by Jarred-Sumner** [comment]
nope can't repro on a linux remote machine either

You're sure that it's happening in a release build? It's easy for uSockets in src/deps/uws to be out of sync

**Comment by sno2** [comment]
It's definitely in the release build.  You can see the `bun` and `bun-debug` locations are different.

```cmd
sno2@Carter-PC:~/projects/bun/bun$ bun -v
0.2.2

sno2@Carter-PC:~/projects/bun/bun$ which bun
/home/sno2/.bun/bin/bun

sno2@Carter-PC:~/projects/bun/bun$ which bun-debug
/home/sno2/projects/bun/bun/packages/debug-bun-linux-x64/bun-debug

sno2@Carter-PC:~/projects/bun/bun$ bun wiptest

SegmentationFault at 0x3000000000000000


----- bun meta -----
Bun v0.2.2 (792ad30a) Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
TestCommand: 
Elapsed: 1772ms | User: 68ms | Sys: 275ms
RSS: 69.21MB | Peak: 96.11MB | Commit: 69.21MB | Faults: 2
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by Jarred-Sumner** [comment]
If you try it in a sub-directory does it still happen? I think the issue here is that one of the tests being executed deep in the WebKit folder (because .test.js is being matched) is causing a segfault

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago (was unrelated to `bun wiptest` specifically)
