### ISSUE TITLE
Add node_modules to default gitignore created by `bun init`

### ISSUE THREAD

**Issue by steve4650** [oven-sh/bun#14085]
### What is the problem this feature would solve?

Most folks exclude node_modules from their git repos. Currently, `bun init` initializes a gitignore file that includes node_modules, which leads to inconveniently large repos.

### What is the feature you are proposing to solve the problem?

Add `/node_modules` to the gitignore that `bun init` already installs.

**Comment by huseeiin** [comment]
it is already in the generated .gitignore?

**Comment by sirenkovladd** [comment]
@janie314 https://github.com/oven-sh/bun/blob/main/src/cli/gitignore-for-init#L59

**Comment by janie314** [comment]
User error.
