### ISSUE TITLE
ERR_HTTP2_INVALID_STREAM  The stream has been destroyed.

### ISSUE THREAD

**Issue by betacoder7** [oven-sh/bun#14133]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x6

### What steps can reproduce the bug?

setup firebase admin sdk and try to use sendEachForMulticast.

### What is the expected behavior?

it should send notifications to multiple users rather than destrying stream like this.

### What do you see instead?

```
      error: 27 |      * @param errorInfo - The error information (code and message).
28 |      * @constructor
29 |      * @internal
30 |      */
31 |     constructor(errorInfo) {
32 |         super(errorInfo.message);
             ^
error: Error while making request: ERR_HTTP2_INVALID_STREAM: The stream has been destroyed. Error code: ERR_HTTP2_INVALID_STREAM
 code: "app/network-error"

      at new FirebaseError (E:\myapp\node_modules\firebase-admin\lib\utils\error.js:32:9)      at new PrefixedFirebaseError (E:\myapp\node_modules\firebase-admin\lib\utils\error.js:69:9)
      at new FirebaseAppError (E:\myapp\node_modules\firebase-admin\lib\utils\error.js:103:9)
      at E:\myapp\node_modules\firebase-admin\lib\utils\api-request.js:318:19
,
    }
  ],
  successCount: 0,
  failureCount: 2,
}
```

**Comment by betacoder7** [comment]
I have tested the same thing with node.js and it is working.

**Comment by ikrom** [comment]
> Facing the same issue while implementing FCM (sendEachForMulticast method) with ElysiaJs (bun supported)
> 
> packages config: <img alt="Screenshot 2024-09-27 at 11 47 13 PM" width="263" src="https://private-user-images.githubusercontent.com/101730507/371638185-eb0bb7c0-c635-416c-9b28-37620d3482ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTY5NTcsIm5iZiI6MTcyODA5NjY1NywicGF0aCI6Ii8xMDE3MzA1MDcvMzcxNjM4MTg1LWViMGJiN2MwLWM2MzUtNDE2Yy05YjI4LTM3NjIwZDM0ODJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMjUwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY5ZTM2ZjAzMDMzMGRlYjViZTk3ZjQ4MGI3NjMwMjZjZmU3YmYxN2NjYzk4Y2YzNTU5YTE3ZjUyNjg0NGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NSmFlM0Btm5uqKUvRJaOvXyILymh2-e5D6TZDDlSSLs">
> 
> error: <img alt="Screenshot 2024-09-27 at 11 48 26 PM" width="1051" src="https://private-user-images.githubusercontent.com/101730507/371638547-129b0190-d892-4eee-a40a-6b717dbe1318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTY5NTcsIm5iZiI6MTcyODA5NjY1NywicGF0aCI6Ii8xMDE3MzA1MDcvMzcxNjM4NTQ3LTEyOWIwMTkwLWQ4OTItNGVlZS1hNDBhLTZiNzE3ZGJlMTMxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMjUwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTEzYTZhZjRjNGYwNzJkZWZlOTRlZGNmNGNmNjkxZDQyNDAxYmU4OTBlNDI4YTEzZmM1ZTFkMTU4ZGI3NzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YhxCN_Fc_5Y6HXvbRR6IdSui7GmgLZ8GeEZ76wu6sTM">

same here, Facing the same issue when I use express + bun (1.1.29)

**Comment by yadsbah** [comment]
I had the same issue. 
downgrading firebase admin to  "^11.10.1"
fixed the issue. 

I believe it is something with bun.

**Comment by cirospaciari** [comment]
Fixed by https://github.com/oven-sh/bun/pull/14286

**Comment by darkyelox** [comment]
This keeps happening to me, I have:

bun: 1.1.41
firebase-admin: 13.0.2
elysia: 1.1.26

I send 3 notifications using sendEachForMulticast I get:

```
Error while making request: Stream closed with error code NGHTTP2_PROTOCOL_ERROR. Error code: ERR_HTTP2_STREAM_ERROR
```

If I downgrade to firebase-admin 11.10.1 it works. is this a bun or a firebase error? Should I open a new issue?
