### ISSUE TITLE
Segmentation fault for Valkey GLIDE client

### ISSUE THREAD

**Issue by infrahead** [oven-sh/bun#14145]
### How can we reproduce the crash?

Was testing the newly released ValKey client for node, as potential Redis client replacement.  It uses NAPI native addon for the core driver.

I'm getting random panics with "Illegal instruction", even though first couple runs and about every other are fine.   Simplest repro:

```
import { GlideClient } from '@valkey/valkey-glide'

const client = await GlideClient.createClient({
	addresses: [
		{
			host: '127.0.0.1',
			port: 6379
		}
	],
})


const pong = await client.customCommand(['PING'])
console.log(pong)

client.close()
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x7FCB00000030

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call`

Features: jsc, transpiler\_cache, tsconfig

**Comment by avifenesh** [comment]
Hi @infrahead, 
Glide maintainer here :)
It's been a while since the issue was opened but if it is still relevant i would love to check it from our side and try to find solutions/workarounds.

On top of it, I'm interested in the bun project for a while now, so if someone from the community would like to help with some directions, i would be happy to contribute a real solution.

**Comment by infrahead** [comment]
@avifenesh It seems to run on latest versions of Bun!  That said, I haven't had a chance to run any extensive tests, but I'll close this for now.

Regarding feedback, obviously Glide is built around a native addon, but that is always problematic across platforms in Node and Bun community it seems.  So not sure that is helpful, I've written my own simple client/parser for simple standalone Redis/Valkey deployments for now and will do more work with Glide if/when have more complex architectures.
