### ISSUE TITLE
zlib brotli compression is truncated

### ISSUE THREAD

**Issue by kobutri** [oven-sh/bun#14156]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```js
const fs = require('node:fs');
const { brotliCompressSync, brotliDecompressSync, constants } = require('node:zlib');

let input = '';
for (let i = 0; i <= 1000000; i++) {
    input += `${i}\n`;
}
const compressed = brotliCompressSync(input, {
    params: {
        [constants.BROTLI_PARAM_QUALITY]: constants.BROTLI_MIN_QUALITY,
    }
});
const decompressed = brotliDecompressSync(compressed);
const output = decompressed.toString('utf8');
const lines = output.split('\n');

console.log(lines.slice(-2).join('\n'));
```

The following code creates a string with 1M lines, compresses it and then decompresses it. 

### What is the expected behavior?

The output should be
```plaintext
1000000

```

which it is when running with node

### What do you see instead?

but with bun it's 
```plaintext
615058
6
```

**Comment by nektro** [comment]
Fixed by https://github.com/oven-sh/bun/pull/14079. will be available in the next canary/release.
