### ISSUE TITLE
Implement `FormData`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1415]
We should implement the [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) API.

```js
const request = new Request(new FormData());
const response = new Response();
const form = await response.formData();
```

**Comment by Jarred-Sumner** [comment]
I agree. The reason we haven't is because WebKit's implementation is closely tied to HTMLFileElement. I don't know if we can just use WebKit's version.

**Comment by Electroid** [comment]
Closing as a duplicate, now being tracked here: #621
