### ISSUE TITLE
bundler: ensure that dead code referencing import identifiers don't load the imports

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#14164]
`b.ts`
```ts
console.log('test failed');
```
`a.ts`
```ts
import { other } from './b';

if (false) {
    other;
}
```

it is incorrect to place a dependency on b since `other` is not used in any live branches. you can comment `other` to change the bundling behavior.

this bug is what caused the bun.report regression where the node:zlib polyfill got included in the browser, however it also seems that the node:zlib polyfill doesnt fully work.

this issue will be more relevant later when there are modules that bundle for Client-side and Server-side, using `import.meta.env.SSR` or other DCE tactics to change behavior.

**Comment by Jarred-Sumner** [comment]
You forget about side effects in imports.

**Comment by Jarred-Sumner** [comment]
It’s not an attribute

it’s inherent to the language

imports have side effects

**Comment by Jarred-Sumner** [comment]
For things like fs we should set side effects: false
