### ISSUE TITLE
Memory leak in `on` method from `node:events`

### ISSUE THREAD

**Issue by sebastiansandqvist** [oven-sh/bun#14187]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

- Repro: https://github.com/sebastiansandqvist/trpc-ee-repro
- (Setup instructions in the readme)

### What is the expected behavior?

The `node:events` `on` function takes a `{ signal }` [option](https://nodejs.org/api/events.html#eventsonemitter-eventname-options) which is an `AbortSignal` that should cause the the event listener to deregister. 

### What do you see instead?

When using the `signal` from a request sent over SSE, the event listener is not canceled even after the signal should fire.

### Additional information

https://github.com/trpc/trpc/issues/6045

I've also tried adding the following code to the subscription, which never fires, so perhaps there's something wrong with the request's `AbortController`:

```ts
addAbortListener(signal, () => {
  console.log('aborting');
});
```

**Comment by KATT** [comment]
You should probably strip trpc from this and make a minimal one


here's a start:

```tsx
const ac = new AbortController();
const ee = new EventEmitter();

async function* gen() {
  for await (const item of on(ee, 'greeting', { signal: ac.signal })) {
    yield item;
  }
}

// [....]
```

**Comment by KATT** [comment]
Minimal reproduction


```ts
import assert from 'assert';
import EventEmitter, { on } from 'events';

const ac = new AbortController();
const ee = new EventEmitter();

async function* gen() {
  for await (const item of on(ee, 'beep', { signal: ac.signal })) {
    yield item;
  }
}

const iterator = gen();

iterator.next().catch(() => {});

assert(ee.listenerCount('beep') === 1);
ac.abort();

assert(ee.listenerCount('beep') === 0);

console.log('✅');
```

### Node
```sh
$ tsx test.ts
✅
```

### Bun
```sh
$ bun test.ts 
15 | iterator.next().catch(() => {});
16 | 
17 | assert(ee.listenerCount('beep') === 1);
18 | ac.abort();
19 | 
20 | assert(ee.listenerCount('beep') === 0);
     ^
AssertionError: false == true
 code: "ERR_ASSERTION"

      at module code (/Users/alex/dev/trpc/test.ts:20:1)
      at moduleEvaluation (native:1:1)
      at moduleEvaluation (native:1:1)
      at native:1:1

```

**Comment by Jarred-Sumner** [comment]
Thanks @KATT

**Comment by oleasteo** [comment]
I wasn't able to create a simple repro, but it's probably related:

I've observed for `abort()` calls to cause the wrong `on(...)` iterator to throw.

For example:
Given `it0 = on(ee, "A", {signal: ac0.signal})`
and `it1 = on(ee, "B", {signal: ac1.signal})`

Then `ac0.abort()` might cause `it1` to abort.

Might help with debugging.

---

For reference, the essential part in my more complex codebase:

```typescript
export async function* watchRoom(
  roomId: string,
  signal?: AbortSignal,
): AsyncIterableIterator<RoomEvent> {
  console.log("START", roomId);
  signal?.addEventListener("abort", () => console.log("ABORT", roomId))
  try {
    for await (const [evt] of on(roomEvents, roomId, { signal })) {
      yield evt;
    }
  } finally {
    console.log("STOP ", roomId, signal);
  }
}
```

yields the following output:

```
START A
START B
ABORT A
STOP  A AbortSignal {  aborted: true, ... }
STOP  B AbortSignal {  aborted: false, ... }
```
