### ISSUE TITLE
Bun should automatically load environment variable files when running package.json scripts

### ISSUE THREAD

**Issue by joulev** [oven-sh/bun#14189]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Linux 6.8.0-1014-azure x86_64 unknown

### What steps can reproduce the bug?

1. Clone/replicate the minimal reproduction here: https://github.com/joulev/debug/tree/bun-load-env-for-scripts.
2. Run `bun start`.
3. Run `bun --env-file=.env start`

### What is the expected behavior?

Both should print

```
$ node index.js
test
```

meaning I shouldn't need to [manually specify `--env-file`](https://bun.sh/docs/runtime/env#manually-specifying-env-files) for the [automatically loaded environment variable files](https://bun.sh/docs/runtime/env#setting-environment-variables).

### What do you see instead?

The `bun start` command prints

```
$ node index.js
undefined
```

indicating the environment variable is not loaded at all.

**Comment by joulev** [comment]
Closing since [this is not a bug but intended behaviour](https://discord.com/channels/876711213126520882/876711213126520885/1288916445740273738).

**Comment by paperdave** [comment]
see https://github.com/oven-sh/bun/issues/9635#issuecomment-2021350123
