### ISSUE TITLE
Unexpected behavior of "bun run script"

### ISSUE THREAD

**Issue by thgh** [oven-sh/bun#14190]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

`bun run script`

### What is the expected behavior?

```
error: Script not found "script"
```

### What do you see instead?

```bash
# High up the filesystem
» bun run script
script: typescript: Permission denied
error: "script" exited with code 1

# In my home folder and any subfolder
» bun run script
Script started, output file is typescript
load .bashrc # I have this echo in my .bashrc
» exit

Script done, output file is typescript
error: "script" exited with code 127
```

Also, in the second case, a new file named "typescript" is created containing "Script started on Thu Sep 26 19:01:52 2024" which seems to record anything happening in the shell. 

### Additional information

This is probably a hidden feature, that should be documented on https://bun.sh/docs/cli/run

**Comment by Jarred-Sumner** [comment]
`bun run script` runs `/usr/bin/script` 

> A script session is captured in file name typescript by default; to specify a different filename follow the script command with a space and the filename as such: script recorded_session.

https://en.wikipedia.org/wiki/Script_(Unix)

**Comment by thgh** [comment]
OK, but why does it run executables outside of my working directory? And why shouldn't it be documented?
