### ISSUE TITLE
Feature Request: `Bun.build()` add a drop when building

### ISSUE THREAD

**Issue by MolikoDeveloper** [oven-sh/bun#14192]
### What is the problem this feature would solve?

is not that necessary (like cjs, we need that XD), but, is there any plan to add a "drop" argument and config in JS to drop certain part of the code?.

im not comparing it with other tools like esbuild, i just dont like to have too many tools if bun actually have it (like the bundler).

### What is the feature you are proposing to solve the problem?

for example:
`bun build index.ts --drop console`
`bun build index.ts --drop debugger`

```ts
Bun.build({
   entrypoint: [...],
   outdir: "dist",
   minify:{...},
   format: "esm",
   drop: ["console", "debugger"]
})
```

### What alternatives have you considered?

actually, i use esbuild for some situations:
VSCode Extensions for cjs*
Watch mode in-code 
drop console messages in production

**Comment by paperdave** [comment]
im surprised this does not have an issue open already (i searched a little bit)

**Comment by MolikoDeveloper** [comment]
My request was before it was implemented 😅

**Comment by MolikoDeveloper** [comment]
yep, you are right.. don`t be mad at me please :(
![Image](https://github.com/user-attachments/assets/444348a4-b7fb-494b-96a6-0634af697bb5)

@paperdave thanks for your job!
