### ISSUE TITLE
sleepSync takes second and not ms

### ISSUE THREAD

**Issue by JulienUsson** [oven-sh/bun#1420]
Hello,

I'm not sure if it's a typing problem or a code problem but the function `sleepSync` seems like to take seconds as parameters but the typing say `Sleep the thread for a given number of milliseconds`.

```javascript
import { sleepSync } from 'bun'

while (true) {
    sleepSync(1)
    console.log(new Date())
}
```
```
2022-09-27T08:10:49.235Z
2022-09-27T08:10:50.235Z
2022-09-27T08:10:51.235Z
2022-09-27T08:10:52.236Z
2022-09-27T08:10:53.236Z
2022-09-27T08:10:54.236Z
```

**Comment by JohnCosta27** [comment]
Can confirm this is still an issue.
