### ISSUE TITLE
SIGILL when using bun

### ISSUE THREAD

**Issue by leath-dub** [oven-sh/bun#1421]
### What platform is your computer?

Linux 5.19.16_1 #1 SMP PREEMPT_DYNAMIC Mon Oct 17 00:37:29 UTC 2022 x86_64 unknown( Void linux )

### How did you attempt to install or upgrade?

I installed it using the script at `https://bun.sh/install`. I am using glibc on void linux.

### What do you see instead?

All but ``bun help`` command results in the following output
```sh
The process was killed by SIGILL: Illegal instruction
```

**Comment by Electroid** [comment]
Hi, are you still running into the same issue when you try running the install script?

Also, do you run into the same issue if you install using: `npm install bun -g`?

**Comment by leath-dub** [comment]
> Hi, are you still running into the same issue when you try running the install script?
> 
> Also, do you run into the same issue if you install using: `npm install bun -g`?

I don't have the machine I was using back in 2022 it was an x61. I'll close this since I can't reproduce it anymore
