### ISSUE TITLE
navigator.userAgent with bunx

### ISSUE THREAD

**Issue by nshiab** [oven-sh/bun#14220]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Run `bunx setup-sda@1.1.3` in an empty folder.

This script uses `navigator.userAgent` to detect the runtime.

With bunx, the userAgent is 'Node' instead of 'Bun'.

### What is the expected behavior?

It should return 'Bun'.

### What do you see instead?

We see 'Node'.

### Additional information

If you run `console.log(navigator.userAgent)` with `bun run`, we have the correct output.

For some reason, it's just bunx that is not providing the correct value.

Thank you!

**Comment by Jarred-Sumner** [comment]
To forcefully use Bun's runtime, pass `--bun`. By default, [bunx and bun run respect the shebang](https://bun.sh/docs/cli/bunx#shebangs) specified by scripts, so if they're specifying `#!/usr/bin/env node` it may run with Node instead of Bun by default.

**Comment by nshiab** [comment]
Ahhhh! I see. Thank you @Jarred-Sumner !
