### ISSUE TITLE
I am able to Insert a string in an Array<Number>

### ISSUE THREAD

**Issue by berzinv** [oven-sh/bun#14237]
### What version of Bun is running?

1.1.29

### What platform is your computer?

Windows

### What steps can reproduce the bug?

class Points {
	points: Array<Number>;
	
	constructor(points: Array<Number>) {
		this.points = points;
	}
	
	length() {
		return this.points.length;
	}
}

let p = new Points(["a", 1, 2, 3]);
console.log(p.length());
console.log(p.points);

### What is the expected behavior?

An error like the one I get with tsc

testpoints.ts:13:21 - error TS2322: Type 'string' is not assignable to type 'Number'.

13 let p = new Points(["a", 1, 2, 3]);
                       ~~~


Found 1 error in testpoints.ts:13


### What do you see instead?

I am able to insert a string in an Annay<Number> which should return an error instead. The output is executed and I get this 

4
[ "a", 1, 2, 3 ]

### Additional information

_No response_

**Comment by devaoto** [comment]
This is a typescript error, this is not a bug in bun.

```ts
class Points {
  points: Array<string | number>;

  constructor(points: Array<string | number>) {
    this.points = points;
  }

  length() {
    return this.points.length;
  }
}

let p = new Points(["a", 1, 2, 3]);
console.log(p.length()); 
console.log(p.points);
```

This should work as expected, and I'd recommend you to learn typescript more.

Resources:
https://www.typescriptlang.org/docs/handbook/2/understanding-errors.html
https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html

**Comment by Jarred-Sumner** [comment]
@devaoto

**Comment by berzinv** [comment]
@Jarred-Sumner 

No, the code you provided is avoiding the real issue. What I’m reporting is that Bun is able to insert a string in an Array<Number>. With tsc, I get this and Bun should too instead of inserting the string and executing the code. It is a bug with Bun which is not respecting the types.

The error with tsc is

testpoints.ts:13:21 - error TS2322: Type 'string' is not assignable to type 'Number'.

13 let p = new Points(["a", 1, 2, 3]);
                       ~~~


Found 1 error in testpoints.ts:13

**Comment by berzinv** [comment]
Ok, I read in the docs there is no typechecking.

https://bun.sh/docs/runtime/typescript
