### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by mrctrifork** [oven-sh/bun#14230]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

Install a dependency:

`bun add exceljs`

### What is the expected behavior?

The package is installed

### What do you see instead?

```
bun add v1.1.29 (6d43b366)
error: GET https://registry.npmjs.org/wrap-ansi-cjs/-/wrap-ansi-cjs-7.0.0.tgz - 404
```

**Comment by bilabror** [comment]
It's working for me.

<img width="230" alt="Screenshot 2024-09-28 at 20 59 59" src="https://github.com/user-attachments/assets/fe66256f-1b32-41db-b5b1-645022bf2fad">

**Comment by mrctrifork** [comment]
![imagen](https://github.com/user-attachments/assets/f364ed9f-2bc9-44b6-9413-da6b595055ed)
It doesnt for me. Accessing the URL through the browser yields a 404 too

**Comment by mrctrifork** [comment]
Incredibly weird. I was working on this monorepo; so I decided to remove the parent's directory `package-lock.json` and `bun.lockb`; run "bun i" and only *now* I can do `bun add exceljs`

**Comment by mrctrifork** [comment]
Incredibly weird. I was working on this monorepo; so I decided to remove the parent's directory `package-lock.json` and `bun.lockb`; run "bun i" and only *now* I can do `bun add exceljs`

**Comment by KatayaAyman** [comment]
what was the fix here? I am having the same issue. Was 7.0 removed from npmjs

**Comment by bilabror** [comment]
Oh, I thought this issue would never come up again, so that’s why I closed it.
I'll open it again

**Comment by bilabror** [comment]
@KatayaAyman 

Try `bun pm cache rm`

**Comment by wintercounter** [comment]
This should be re-opened. I believe this is happening when you don't have a bun lock file, bun will try to convert your package-lock.json, but it does it wrong.

The is the entry in package-lock.json
```
"wrap-ansi-cjs": "npm:wrap-ansi@^7.0.0"
```

But seems like bun is trying to install this as `wrap-ansi-cjs@^7.0.0` when it should be `wrap-ansi@^7.0.0` at the end. Deleting bun lock and package-lock.json then running `bun install` fixes it.

**Comment by iwasrobbed** [comment]
The fix is:

- remove your bun and/or package lock files
- run `bun i`
- push to CI/CD
