### ISSUE TITLE
Segfault in bun

### ISSUE THREAD

**Issue by josephg** [oven-sh/bun#14250]
### How can we reproduce the crash?

I'm running into a bun segfault while running a pure CPU (in memory) simulation of a little network protocol I'm sketching out. The program is made up of ~600 lines of pure javascript + 1 dependency from npm (seed-random).

I'm not sure whats causing the crash. The program doesn't always crash at the same time. It usually crashes within the first second or so of starting, but sometimes it runs for 10 seconds before crashing.

I've put the code up here. The crashing version is this:

https://github.com/josephg/gossip/tree/7630e0598e84826a52b5739efe706899f04a8984

Run with `bun run index.ts`.

Despite the apparent use of a random number generator in the program, I'm using a seeded RNG for the simulation. The program itself is 100% deterministic.

Bun has been installed from the curl command on the website.

### Relevant log output

```shell
$ bun run index.ts
j 0
j 100
============================================================
Bun v1.1.29 (6d43b366) Linux x64
Linux Kernel v6.8.0 | glibc v2.35
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "run" "index.ts"
Features: jsc tsconfig 
Builtins: "bun:main" "node:assert/strict" "node:util/types" 
Elapsed: 1644ms | User: 1708ms | Sys: 60ms
RSS: 1.07GB | Peak: 123.17MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::SlotVisitor::drain(...)::$_0::operator()`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::SlotVisitor::drain`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::Heap::runFixpointPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::callWithCurrentThreadState`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::Heap::collectInMutatorThread`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::Heap::collectIfNecessaryOrDefer`

Features: jsc, tsconfig

**Comment by Jarred-Sumner** [comment]
Minimal reproduction:
```ts
import { deepEquals } from "bun";
for (let i = 0; i < 1000000; i++) {
  let outer = new Map([
    [1, [1]],
    [2, [1]],
    [3, [1]],
    [4, [1]],
  ]);

  let inner = new Map([
    [1, [1]],
    [2, [1]],
    [3, [1]],
    [4, [1]],
  ]);

  deepEquals(outer, inner);
}
```

Likely caused by https://github.com/oven-sh/bun/pull/13674
