### ISSUE TITLE
Module blocked because of disallowed MIME type

### ISSUE THREAD

**Issue by chris-crespo** [oven-sh/bun#1427]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 6.0.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Oct 2022 18:28:09 +0000 x86_64 unknown

### What steps can reproduce the bug?

- Create React/Nextjs app
- Add `pixi.js`
- Add `import * as pixi from 'pixi.js'` to a file

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior?

It should just import the library

### What do you see instead?

```
Loading module from “http://localhost:3000/node:url” was blocked because of a disallowed MIME type (“”).
```

### Additional information

This only happens when using pixijs with bun. It works fine with node.

**Comment by Electroid** [comment]
This issue was caused from using `bun dev`, which was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
