### ISSUE TITLE
bun add edge-js failed

### ISSUE THREAD

**Issue by behnik** [oven-sh/bun#14290]
### How can we reproduce the crash?

<img width="850" alt="Screenshot 2024-10-02 1040010" src="https://github.com/user-attachments/assets/cd5d7884-95e2-4c59-8197-79b6130567ee">

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on windows x86_64 [AddCommand]

**panic**: Internal assertion failure

- [`output.zig:357`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/output.zig#L357>): `panic`
- [`bun.zig:3388`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.zig#L3388>): `assertionFailure`
- [`js_ast.zig:3249`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/js_ast.zig#L3249>): `assert`
- [`lockfile.zig:2353`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/lockfile.zig#L2353>): `stringHash`
- [`migration.zig:888`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/migration.zig#L888>): `migrateNPMLockfile`
- [`migration.zig:67`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/migration.zig#L67>): `detectAndLoadOtherLockfile`
- [`lockfile.zig:245`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/lockfile.zig#L245>): `loadFromDisk`
- [`install.zig:13607`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L13607>): `installWithManager`
- [`install.zig:10387`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L10387>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:9936`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/install/install.zig#L9936>): `updatePackageJSONAndInstall`

Features: lockfile\_migration\_from\_package\_lock

**Comment by dylan-conway** [comment]
Thanks for reporting. Can you share the `package.json` and `package-lock.json` for your project? It would be useful for investigating this bug

**Comment by behnik** [comment]
[package.json](https://github.com/user-attachments/files/17221324/package.json)
[package-lock.json](https://github.com/user-attachments/files/17221325/package-lock.json)
