### ISSUE TITLE
SegmentationFault at 0x7000000000000000 when using fetch API

### ISSUE THREAD

**Issue by cohenerickson** [oven-sh/bun#1429]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 x86_64 unknown

### What steps can reproduce the bug?

```js
await fetch("https://example.com:443/");
```

Repo: https://github.com/cohenerickson/bare-server-bun

```bash
git clone https://github.com/cohenerickson/bare-server-bun.git
cd bare-server-bun
bun install
bun start
```

run `tests/v1/method.get.http`

### How often does it reproduce? Is there a required condition?

From what I have observed this seems to occur when fetching resources that aren't cached but it seems more random than that.

### What is the expected behavior?

The resource should be fetched without error.

### What do you see instead?

```
SegmentationFault at 0x7000000000000000


----- bun meta -----
Bun v0.2.2 (6632135e) Linux x64 #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022
AutoCommand: 
Elapsed: 85277ms | User: 117ms | Sys: 39ms
RSS: 69.21MB | Peak: 80.43MB | Commit: 69.21MB | Faults: 0
----- bun meta -----

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

Script error "start" exited with 139 status
```

### Additional information

I have had this occur on both a GitHub codespace as well as on my local windows machine, I will update this with the version information from my windows machine when I have the opportunity.

**Comment by birkskyum** [comment]
I'm on a mac, but cloning the [bare-server-bun](https://github.com/cohenerickson/bare-server-bun) and running it with bun 0.8 I do get:

```
{
  "versions": [
    "v1"
  ],
  "language": "Bun",
  "memoryUsage": 1.92,
  "maintainer": {
    "email": "contact@cohenerickson.com",
    "website": "https://cohenerickson.com"
  },
  "project": {
    "name": "bare-server-bun",
    "description": "TOMP bare server implementation using native Bun API's.",
    "email": "contact@cohenerickson.com",
    "website": "https://cohenerickson.com",
    "repository": "https://github.com/cohenerickson/bare-server-bun.git",
    "version": "0.0.1"
  }
}
```

So I believe this ticket can be closed. @cohenerickson , does it works for you too?

**Comment by birkskyum** [comment]
can be closed
