### ISSUE TITLE
fs.readdirSync causes script to crash

### ISSUE THREAD

**Issue by numso** [oven-sh/bun#143]
Running the following code with bun:

```js
import fs from 'fs'
fs.readdirSync(import.meta.dir)
```

renders the following output:

```
trying-out-bun → bun repro.mjs

Crash at 4360274624


–––– bun meta ––––
Bun v0.0.78 macOS Silicon 21.0.1
AutoCommand: single_page_app_routing public_folder 
Elapsed: 8ms | User: 8ms | Sys: 6ms
RSS: 17.33MB | Peak: 17.33MB | Commit: 0.27GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

I've found that the code succeeds when I run it on my home directory (`fs.readdirSync('/Users/dallin')`). Everything else crashes for me. In the repro above I was in a folder nested in my home directory: `/Users/dallin/code/trying-out-bun/`.

**Comment by Jarred-Sumner** [comment]
Thanks for filing

For `readdir`, bun stack allocates up to 32 file path strings before converting them to a JS array

The bug was: when < 32 file paths, bun sent the entire stack allocated buffer when it should've sent only the part of the stack allocated buffer in use.
  
```patch
-                    var array = JSC.JSValue.createStringArray(context.ptr(), zig_strings.ptr, zig_strings.len, clone).asObjectRef();
+                    var array = JSC.JSValue.createStringArray(context.ptr(), zig_strings.ptr, value.len, clone).asObjectRef();
```
