### ISSUE TITLE
startRemoteDebugger fails to start

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1430]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64 arm

### What steps can reproduce the bug?

```js
import { startRemoteDebugger } from "bun:jsc";

try {
  startRemoteDebugger("127.0.0.1", 10252);
} catch (error) {
  console.error("Failed to start debugger", error);
}
```

### How often does it reproduce? Is there a required condition?

Always. No matter which host or port is used.

### What do you see instead?

```
5 | import { startRemoteDebugger } from "bun:jsc";
6 | 
7 | try {
8 |   startRemoteDebugger("127.0.0.1", 10252);
      ^
error: Failed to start server "127.0.0.1:10252". Is port already in use?
```

**Comment by birkskyum** [comment]
Still issue with 0.8.2+36f9d2291c71d151dceff6d7d40adbbb2c3b3809

**Comment by Jarred-Sumner** [comment]
We should deprecate this API.
