### ISSUE TITLE
Add a `lastModified` parameter to the `FileBlob` returned by `Bun.file(...)`

### ISSUE THREAD

**Issue by imjuniper** [oven-sh/bun#1431]
### What is the problem this feature would solve?

I want to add the option to automatically send the `Last-Modified` header in my [serve-static-bun](https://github.com/jakobbouchard/serve-static-bun) package. To do that, I need to read the file system's last modified value, which Bun doesn't provide.

### What is the feature you are proposing to solve the problem?

Adding a `lastModified` parameter to the `FileBlob` that is returned from `Bun.file(...)`.

### What alternatives have you considered?

If there is another way to get the last modified date, I am open to it, but I haven't found any. Though, to be fair I haven't dug in the code much yet.

**Comment by Jarred-Sumner** [comment]
We can make it insert the Last-Modified header by default

We already have to call `stat` on the file, so it should have no performance impact

**Comment by imjuniper** [comment]
hm, since `stat` is already called, maybe it could be interesting to add what type of file it is, like `symbolic link`, `regular file`, `directory`? Since right now, the way I detect directories is by trying to run `arrayBuffer()` on the blob, catching the error and if its code is `EISDIR`, it's a directory. It would be cleaner to not rely on catching errors haha

**Comment by paperclover** [comment]
implemented in 0.6.0
