### ISSUE TITLE
Segmentation fault | RakNet Module

### ISSUE THREAD

**Issue by SashaGoncharov19** [oven-sh/bun#14336]
### How can we reproduce the crash?

Download RAGE:MP server, start it and try to run this sample code.

```ts
import { Client } from 'raknet-native'

(async () => {
    const client = new Client('127.0.0.1', 22005, { protocolVersion: 9 })

    await client.connect()

    client.on('encapsulated', (buffer) => {
        console.assert(buffer.toString() == '\xA0 Hello world')
    })
})()
```

### Relevant log output

```
#### PS C:\Users\lol\WebstormProjects\raknet-ragemp> bun run .\index.ts
============================================================
Bun v1.1.25 (fe62a614) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\Sasha\.bun\bin\bun.exe" "run" ".\index.ts"
Features: jsc tsconfig(5) 
Builtins: "bun:main" "node:events" "node:fs" "node:os" "node:path" "node:string_decoder" "node:tty" "node:util" "node:util/types" 
Elapsed: 398ms | User: 46ms | Sys: 31ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.21GB | Faults: 37318

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x00000005

- `llint_entry`

**Comment by SashaGoncharov19** [comment]
Same thing on v1.1.29

**Comment by 190n** [comment]
@SashaGoncharov19 I may have a fix in c44eb732ee25945df42e399f84f76429acea149a. I can see that Bun is successfully connecting to my RAGE:MP server, but is it expected that the `client.on('encapsulated'` event handler is never reached? That's what happens for me running the script in Node.js, and in Bun with that change the result is the same (no crash). I just wanna make sure I didn't do something wrong setting up the server, in case there's a crash that happens later on during a successful connection.

**Comment by SashaGoncharov19** [comment]
@190n I created a repo with all this files and configs. 

https://github.com/SashaGoncharov19/bun-segmentation-fault

![Image](https://github.com/user-attachments/assets/a212eada-8265-4d71-b3d6-0563d69392ee)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x00000005

- `llint_entry`

Features: jsc, tsconfig

**Comment by 190n** [comment]
Thanks, I did run your code already, I was more worried about the RAGE:MP server setup in case it wasn't fully connecting. Can you try downloading a copy of Bun with my recent changes [here](https://buildkite.com/organizations/bun/pipelines/bun/builds/5310/jobs/0192c67e-369a-49fa-b1a7-bb4e3b2831d3/artifacts/0192c687-4965-4a3f-92cd-c549a50bb2b3) and tell me if it works correctly with your server?

**Comment by SashaGoncharov19** [comment]
Looks like it's not crashing anymore with your build, because if i will use official latest release, i can't start my file, it's just crashing with Segmentation Fault.

**Comment by 190n** [comment]
OK, great. This should be fixed in the next version of Bun then.
