### ISSUE TITLE
SyntaxError: Unexpected identifier 'Promise'

### ISSUE THREAD

**Issue by thers** [oven-sh/bun#14357]
### What version of Bun is running?

1.1.29

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Have 2 files:

`main.ts`:
```ts
console.log(await import('./async'));
```

`async.ts`:
```ts
export const test = await Promise.resolve().then(() => 123);
```

Run Bun build:
```
bun build main.ts --target="bun" --outfile=bundled.js
```

Run bundled file with Bun:
```
bun bundled.js
```

### What is the expected behavior?

Bundled script runs and prints out the module object.

### What do you see instead?

Error:
```
16 | __export(exports_async, {
17 |   test: () => test
18 | });
19 | var test;
20 | var init_async = __esm(() => {
21 |   test = await Promise.resolve().then(() => 123);
     ^
SyntaxError: Unexpected identifier 'Promise'
      at <parse> (C:\dev\bun_bugs\async_in_imports\bundled.js:21:1)
note: missing sourcemaps for C:\dev\bun_bugs\async_in_imports\bundled.js
note: consider bundling with '--sourcemap' to get unminified traces

Bun v1.1.29 (Windows x64)
```

### Additional information

If we look at the trace, the code is trying to use `await` keyword in a non-async context of: `__esm(() => {...`.

I was checking how the bundler verifies if it needs to use async for this wrapper, but it looks like it only checks for parent, if I am understanding the code correctly: https://github.com/oven-sh/bun/blob/main/src/bundler/bundle_v2.zig#L8312

**Comment by 190n** [comment]
#14218 fixed this for your example. With a canary build I get:

```
{
  test: [Getter/Setter],
}
```

(and `(await import('./async')).test` is 123).

If you still get similar errors in a different codebase after upgrading to canary, feel free to re-open this issue.
