### ISSUE TITLE
Unexpected Dependency with Project Name Added to package-lock.json in Bun

### ISSUE THREAD

**Issue by SantiagoEmanuel** [oven-sh/bun#14350]
# Bug Reproduction: Dependency Added with the Same Name as the Project

## Problem Description

When creating a project in Bun, a dependency is added in the `package-lock.json` file with the same name as the project, without explicitly installing that dependency. This causes an inconsistency in the `package-lock.json` file.

## Steps to Reproduce

1. **Create a new project in Bun**:
   Run the command to initialize a new project or manually create a `package.json` file with the following content:

   ```bash
   bun init
   ```

   Or create a `package.json` file like this:

   ```json
   {
     "name": "task-app",
     "version": "0.0.0",
     "scripts": {
       "dev": "bun run dev"
     }
   }
   ```

2. **Install dependencies**:
   Install some dependencies using Bun. For example:

   ```bash
   bun add react react-dom react-router-dom
   ```

3. **Check the `package-lock.json` file**:
   After installing the dependencies, review the `package-lock.json` file. You will notice that Bun adds a dependency with the exact same name as the project (`task-app`) without having explicitly installed it.

   Example of the `package-lock.json` file:

   ```json
   "dependencies": {
     "react": "^18.3.1",
     "react-dom": "^18.3.1",
     "react-router-dom": "^6.26.2",
     "task-app": "file:"
   }
   ```

4. **Confirm the problem**:
   If the project shows a dependency with the same name in `package-lock.json` without being explicitly installed, the bug has been reproduced.

## System and Versions

- **Bun Version**: Bun v1.1.29 (6d43b36) Windows x64
- **Operating System**:Windows v.win10_fe

## Expected Result

No dependency should be added with the same name as the project unless it is explicitly installed.

## Observed Result

A dependency with the project’s name is automatically added to the `package-lock.json`, which should not happen.

### package-lock.json File

[package-lock.json](https://github.com/user-attachments/files/17263449/package-lock.json)

![Image](https://github.com/user-attachments/assets/5f69786f-fb6a-4bcc-9afb-e3438e364b3e)

[5.12ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.29 (6d43b366) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\santi\.bun\bin\bun.exe" "install"
Features: lockfile_migration_from_package_lock 
Elapsed: 35ms | User: 46ms | Sys: 62ms
RSS: 66.67MB | Peak: 66.67MB | Commit: 111.35MB | Faults: 16469

panic(main thread): Internal assertion failure: unexpected resolution tag
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

**Comment by Jarred-Sumner** [comment]
Can you paste the package-lock.json file?

**Comment by SantiagoEmanuel** [comment]
[BunBugReport_EN.md](https://github.com/user-attachments/files/17263445/BunBugReport_EN.md)
[package-lock.json](https://github.com/user-attachments/files/17263449/package-lock.json)
