### ISSUE TITLE
Top-level await breaks self.addEventListener in Workers

### ISSUE THREAD

**Issue by SwanX1** [oven-sh/bun#14363]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Linux 6.8.0-45-generic x86_64 x86_64

### What steps can reproduce the bug?

Create an `index.ts` and `worker.ts` files with the following contents respectively:
```ts
const worker = new Worker(new URL('./worker.ts', import.meta.url).href);

// This allows exiting immediately after receiving a message from the worker
worker.unref();

// Send a simple message to the worker
worker.postMessage('hello');

// This await works in the main thread, as expected
await new Promise(resolve => {
  worker.addEventListener('message', e => {
    console.log(e.data);
    resolve();
  });
});
```

```ts
declare var self: Worker;

// This await breaks self.addEventListener
await new Promise<void>(resolve => {
  self.addEventListener('message', (e: MessageEvent) => {
    console.log(e.data); // Log the data received
    self.postMessage('world'); // Send back 'world'
    resolve();
  });
});
```

### What is the expected behavior?

Should log the following when running `bun run index.ts`:
```
hello
world
```

### What do you see instead?

Does not log anything, and the main thread hangs on awaiting a response from the worker.

### Additional information

Wrapping the promise in an async function in the worker works as expected.
```ts
async function main() {
  await new Promise(/* ... */);
}

main(); // Using await here breaks everything again
```

**Comment by guest271314** [comment]
Reproducible on Linux running Bun version 1.1.30.

**Comment by guest271314** [comment]
This is pretty much completely broken. 

Wrapping both scripts inside of an anonymous async function results in both scripts exiting without logging anything.

**Comment by guest271314** [comment]
I was trying to make the code work as expected, by any means. I'm not sure how using an anonymous async function should be blocking anything. The function, just like the `executor` function passed to `new Promise()` constructor is executed immediately.

I tested both with the `ref` and without `ref`. Neither worked as expected for me cf. `Worker` in the browser.

**Comment by SwanX1** [comment]
This is a duplicate of #13570
