### ISSUE TITLE
Cannot exit "bun tsc -w" since v1.1.27

### ISSUE THREAD

**Issue by thgh** [oven-sh/bun#14375]
### What version of Bun is running?

1.1.27+267afa293

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

1. Install either bun version 1.1.27, 1.1.28, 1.1.29, 1.1.30 - 1.1.36
2. Run `bun tsc -w`
3. Press `Ctrl+C`

https://codesandbox.io/p/devbox/repro-14375-hhlr5s

### What is the expected behavior?

Script exits

### What do you see instead? (macos)

Script does not exit
Output: `^Cerror: Failed to run "tsc" due to signal SIGINT`

### What do you see instead? (codesandbox)

Script exits as wanted
Output: `^Cerror: Failed to run "tsc" due to signal SIGINT`

### Additional information

Works as expected in 1.1.26
Typescript version 5.5.4, same issue in typescript@5.6.2

**Comment by thgh** [comment]
OK, here it is: https://codesandbox.io/p/devbox/repro-14375-hhlr5s
![Image](https://github.com/user-attachments/assets/d62992b4-f0ef-4f75-80b3-343cb5756287)

**Comment by Electroid** [comment]
Fixed by #15545
