### ISSUE TITLE
Bun.build define env error

### ISSUE THREAD

**Issue by shaddollxz** [oven-sh/bun#14382]
### What version of Bun is running?

1.1.29

### What platform is your computer?

macbook pro m2 arm64

### What steps can reproduce the bug?

have this build code, inject a env to code, expect `Bun.env.PROGRAM_VERSION` will be hard code in output
```javascript
Bun.build({
  define: {
      "Bun.env.PROGRAM_VERSION": "1.2.3",
  }
})
```
but it be a number in output
```diff
- program.version(Bun.env.PROGRAM_VERSION)
+ program.version(1.2)
```

### What is the expected behavior?

All variables injected by define are strings.
```diff
- program.version(Bun.env.PROGRAM_VERSION)
+ program.version("1.2.3")
```

**Comment by Jarred-Sumner** [comment]
`define` is a little confusing - this becomes the literal value `1.2.3` which is not valid syntax 

you meant

```js
Bun.build({
  define: {
      "Bun.env.PROGRAM_VERSION": "'1.2.3'",
  }
})
```
