### ISSUE TITLE
Update bun

### ISSUE THREAD

**Issue by iezed** [oven-sh/bun#14413]
### What version of Bun is running?

bun upgrade

### What platform is your computer?

Linux 6.9.3-76060903-generic x86_64 x86_64

### What steps can reproduce the bug?

bun upgrade

### What is the expected behavior?

upgrade bun

### What do you see instead?

Bun v1.1.30 is out, but not for this platform (linux-x64) yet.

**Comment by Skywalker13** [comment]
Same here with Debian Bookworm. As workaround I run `curl -fsSL https://bun.sh/install | bash` in order to "upgrade" from 1.1.29 to 1.1.30

**Comment by Jarred-Sumner** [comment]
Fixed
