### ISSUE TITLE
Implement iterator-helpers

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#14426]
### What is the problem this feature would solve?

iterator.map
iterator.filter
iterator.take
iterator.drop
iterator.flatMap
iterator.reduce
iterator. toArray
iterator. forEach
iterator. some
iterator. every
iterator. find
iterator. from

### What is the feature you are proposing to solve the problem?

https://github.com/tc39/proposal-iterator-helpers?tab=readme-ov-file

stage: 4

**Comment by nektro** [comment]
https://bugs.webkit.org/show_bug.cgi?id=280811 upstream tracking

**Comment by sirenkovladd** [comment]
@nektro 
https://github.com/WebKit/WebKit/pull/34418
