### ISSUE TITLE
Implement Promise.try

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#14425]
### What is the problem this feature would solve?

Promise.try

### What is the feature you are proposing to solve the problem?

Stage: 4

https://github.com/tc39/proposal-promise-try?tab=readme-ov-file

**Comment by nektro** [comment]
https://bugs.webkit.org/show_bug.cgi?id=275359 upstream tracking

**Comment by sirenkovladd** [comment]
https://github.com/WebKit/WebKit/pull/31556 implemented

**Comment by dylan-conway** [comment]
Available since bun v1.1.22
