### ISSUE TITLE
Global .npmrc not using authentication for custom registry

### ISSUE THREAD

**Issue by lenovouser** [oven-sh/bun#14433]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

Use a global config like this:

```
@slug:registry=https://my-registry.tld/
//my-registry.tld/:_authToken="<token>"
```

and a project config like this:

```
@slug:registry=https://my-registry.tld/

https://my-registry.tld/:always-auth=true

auto-install-peers=true
engine-strict=true
prefer-frozen-lockfile=true
resolution-mode=highest
save-exact=true
save-prefix=''
strict-peer-dependencies=true
update-notifier=true
```

### What is the expected behavior?

It should install the dependencies correctly 

### What do you see instead?

```
error: GET https://my-registry.tld/@slug%2fpackage-1 - 401

error: GET https://my-registry.tld/@slug%2fpackage-2 - 401
```

### Additional information

https://github.com/oven-sh/bun/pull/13990

**Comment by jonguenther** [comment]
Hitting the same issue on same OS & `v1.1.34` with [`bunfig.toml`](https://bun.sh/docs/install/registries):

```toml
[install.scopes]
"@org" = {url="https://npm.pkg.github.com/",token="$npm_token"}
```

which leads to following error

```
error: GET https://npm.pkg.github.com/@org%2fpackage-name - 401
error: @org/package-name@^version failed to resolve
```

**Comment by dbryar** [comment]
it could be the braces on the env var. That was the issue in my org setup

see https://github.com/oven-sh/bun/issues/4654

**Comment by alexgorbatchev** [comment]
Same issue on 1.3.1, however 1.3.3 seems to be working fine
