### ISSUE TITLE
`bun publish` not work as expected

### ISSUE THREAD

**Issue by lkwr** [oven-sh/bun#14445]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

ubuntu-latest (github runner)

### What steps can reproduce the bug?

In a cli project I switched from `npm publish` to `bun publish` in my CI/CD and discovered a bug where packages published via `bun publish` not correctly installed with the binary file (there was no `node_modules/.bin/my_cli` file). By publishing the exact same package via `npm publish` the `node_modules/.bin/my_cli` file was successfully created.

I try to create public package which showcase the bug but `bun publish` even failed to publish a package to `https://npm.pkg.github.com`. Publishing to my private gitea instance works (but not the binary install part).

Link to the failed job: https://github.com/lkwr/bun-hello/actions/runs/11262578487/job/31318968346

### What is the expected behavior?

Publishing via bun works as expected like the `npm publish`

**Comment by rodhoward** [comment]
bun version 1.1.30
```shell
bun publish
```
I'm getting a 500 error publishing to a private gitlab repository:
``` shell
Total files: 20
Shasum: 127d96c0d527eced30ab197459c72a0f94735bb5
Integrity: sha512-7kMjnj7wPGo1K[...]LoTREAaT9lJJA==
Unpacked size: 14.62KB
Packed size: 4.99KB
Tag: latest
Access: default
Registry: https://gitlab.my.repo

500 Internal Server Error: https://gitlab.my.repo/project/path
```

using npm is working fine, simply replace the `bun publish` with `npm publish` and it works.
