### ISSUE TITLE
Bun crashes when building empty css file with --experimentalCss

### ISSUE THREAD

**Issue by Voldemortas** [oven-sh/bun#14487]
### How can we reproduce the crash?

```tsx
//Component.tsx

import React from 'react'
import './styles.css'

export default function Whatever() {
  return <div>dsfsdf</div>
}
```

The `styles.css` file exists but it's empty

```ts
//build.ts

await Bun.build({
  entrypoints: ['Component.tsx'],
  outdir: "out",
  experimentalCss: true,
})
```

and doing `bun run build.ts` gives the seg fault

it works fine if `styles.css` has anything (even comments)

### Relevant log output

panic: Segmentation fault at address 0x8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000008

- [`bundle_v2.zig:5611`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bundler/bundle_v2.zig#L5611>): `src.bundler.bundle_v2.LinkerContext.findImportedFilesInCSSOrder`
- [`bundle_v2.zig:5010`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bundler/bundle_v2.zig#L5010>): `src.bundler.bundle_v2.LinkerContext.computeChunks`
- [`bundle_v2.zig:4867`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bundler/bundle_v2.zig#L4867>): `src.bundler.bundle_v2.LinkerContext.link`
- [`bundle_v2.zig:1908`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bundler/bundle_v2.zig#L1908>): `src.bundler.bundle_v2.BundleV2.runFromJSInNewThread`
- [`bundle_v2.zig:2788`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bundler/bundle_v2.zig#L2788>): `Thread.PosixThreadImpl.spawn__anon_186129.Instance.entryFn`

Features: Bun.stderr, Bun.stdout, jsc, shell, spawn, transpiler\_cache, tsconfig

**Comment by versecafe** [comment]
Going to take a pass at this, just to note in case anyone comes on this, as long as the file contains anything besides new lines, even if it's just junk chars or comment blocks works, it probably *shouldn't* bundle out a css file if there isn't any css but it does currently make

```css

/* styles.css */

```
> white space is part of this
