### ISSUE TITLE
bun build --bytecode command fails with "cannot write multiple output files without an output directory" error

### ISSUE THREAD

**Issue by 839900146** [oven-sh/bun#14500]
### What version of Bun is running?

1.1.30

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

[demo.zip](https://github.com/user-attachments/files/17348394/demo.zip)

**Steps to reproduce:**

1. Create a directory under a certain drive on a Windows system.
2. Create a `.ts` file with any name in that directory.
3. Write some arbitrary content in the `.ts` file, such as a print statement.
4. Execute `bun build --bytecode --output=./dist ./math.ts` in bash or PowerShell.

### What is the expected behavior?

Can compile successfully

### What do you see instead?

```bash
admin@DESKTOP-D8E7ODP MINGW64 /e/bun-demo
$ bun build --bytecode --output=./dist ./math.ts 
error: cannot write multiple output files without an output directory

admin@DESKTOP-D8E7ODP MINGW64 /e/bun-demo
$
```

### Additional information

![Image](https://github.com/user-attachments/assets/34d1a403-c7c0-4265-bdc7-f4c465d4379b)

**Comment by RiskyMH** [comment]
You need to use `--outdir` instead of `--output` because it creates a special .js.jsc file.
