### ISSUE TITLE
<input> and <img> complain and crash if they are given children in JSX code, but shouldn't

### ISSUE THREAD

**Issue by ceymard** [oven-sh/bun#14515]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Linux 6.8.0-45-generic x86_64 x86_64

### What steps can reproduce the bug?

I do not use react, but another library that uses JSX.

In this library, it is perfectly valid to give those items children. I feel this is not the place of a JSX transpiler to emit that warning, since even typescript does not do so. In the following example, you can see that the `$on` function is used as a child to bind an event to the element as is the way in this library.

Also, it seems to confuse the scope handling since at some places, it actually crashes the build.

Here is a minimal example that crashes bun 1.1.30 :

```tsx
// test.tsx

export function Input(a: InlineInputAttrs, ch: DocumentFragment) {
  const o_model = a.model
  const nullable = (a.type||'').indexOf('null') > -1

  return <input>
      {$on('input', (ev) => {
        var v = ev.currentTarget.value
        if (nullable && v === '') {
          o_model.set(null!)
        } else {
          // @ts-ignore typescript is confused by the type of o_model, rightly so.
          o_model.set(to_obs(v))
        }
      })}

    </input>

}

function _pad(n: number) {
  return (n < 10 ? ('0' + n) : n)
}

function _iso_date(d: Date) {
  return `${d.getFullYear()}-${_pad(d.getMonth()+1)}-${_pad(d.getDate())}`
}
```

This is used alongside a simple `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "strict": true,
    "jsx": "react",
    "reactNamespace": "E",
  }
}
```

### What is the expected behavior?

It should just transpile, not crash, and not output *warnings* as the code is perfectly valid.

### What do you see instead?

Running `bun build test.tsx` produces the following crash :

```
===========================================================
Bun v1.1.30 (7996d06b) Linux x64
Linux Kernel v6.8.0 | glibc v2.39
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "build" "test.tsx"
Features: tsconfig
Elapsed: 2ms | User: 0ms | Sys: 3ms
RSS: 1.07GB | Peak: 17.17MB | Commit: 1.07GB | Faults: 0

panic: Scope mismatch while visiting
17 |     </input>
           ^
warn: <input / is a void element and must not have "children"
   at /home/cey/projects/test/e/test.tsx:17:7

25 | function _iso_date(d: Date) {
                       ^
debug: Expected this scope (.function_args)
    at /home/cey/projects/test/e/test.tsx:25:19

9 |         if (nullable && v === '') {
                                      ^
debug: Found this scope (.block)
    at /home/cey/projects/test/e/test.tsx:9:35

Crashed while visiting /home/cey/projects/test/e/test.tsx
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.30/lb17996d06AggggggCw58gwD8wtnuDw0vwsD4ynkqDginhwD08ihuDi6/qsDg6g8kD2t56kD0mk0mDA0eNqtks1uwjAMx+99BS5/ceDjQkcRQyDYadsL7Ig0FFJDszVJ1biFaXv4KVE70EDTDuQQf8R2nF/8Im1B0MppwTLDIVM5oVZOsTL7qLMe6/EMX+is7zSAIJd+i5UpKn6IcFqddaJ9QitffVzkrYMojTe8vkCr+ZhlKIMYykGgtioF5aTJMIRJoSvHMJaRiZrQlZnK05JMN1RurhTcVJzc6zizmmJJH3FR2jeS7GImxzEFMWJ3/GmjyZno8ezSF1xR6D2ZNs9vDqd6VxnJyoYXYaOc3aSCaZAu8CiYhvg8h4J/AUppW+2vE3o6FiSZUnCmHFz4rsGo7WEjyr0btjhuwiOZXmE0PwGZn41DOxKBi9oF98BUeS62OaHXQ43VatWGJLrf9+ofiG5B7NlW5heubW7l+20xzS9dk0Au+gan//AO
```

### Additional information

If the two functions at the end are removed, it builds, but erroneously :

```js
function Input(a, ch) {
  const o_model = a.model;
  const nullable = (a.type || "").indexOf("null") > -1;
  return /* @__PURE__ */ React.createElement("input", null);
}
export {
  Input
};
```

Here, the children were removed !
Renaming input to input2 in the source code does produce the correct result :

```js
function Input(a, ch) {
  const o_model = a.model;
  const nullable = (a.type || "").indexOf("null") > -1;
  return /* @__PURE__ */ React.createElement("input2", null, $on("input", (ev) => {
    var v = ev.currentTarget.value;
    if (nullable && v === "") {
      o_model.set(null);
    } else {
      o_model.set(to_obs(v));
    }
  }));
}
export {
  Input
};
```

**Comment by RiskyMH** [comment]
Wow, I can reproduce this issue as well! Below is the crash report:

## Crash report
Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on linux x86_64 [BuildCommand]

**panic**: Scope mismatch while visiting
[1m93 | [0m      [0m<[0m/input>
             [2m[1m[2m[1m^[0m
[2mwarn[0m[2m: [0m[2m[1m<input / is a void element and must not have "children"[0m
   [2mat [0m[36m/home/cey/swapp/apps/salesway-intra/client/widgets/input.tsx[0m[2m:[0m[33m93[0m[2m:[0m[33m9[0m

[2m100 | [0m[0m[35mfunction[0m _iso_date(d: Date) {
                        [2m[1m[2m[1m^[0m
[2mdebug[0m[2m: [0m[2m[1mExpected this scope (.function_args)[0m
    [2mat [0m[36m/home/cey/swapp/apps/salesway-intra/client/widgets/input.tsx[0m[2m:[0m[33m100[0m[2m:[0m[33m19[0m

[2m68 | [0m          [0m[35mif[0m (comp !== v) {
                               [2m[1m[2m[1m^[0m
[2mdebug[0m[2m: [0m[2m[1mFound this scope (.block)[0m
    [2mat [0m[36m/home/cey/swapp/apps/salesway-intra/client/widgets/input.tsx[0m[2m:[0m[33m68[0m[2m:[0m[33m27[0m

- [`output.zig:0`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/output.zig#L0>): `src.output.panic__anon_172751`
- [`js_parser.zig:14766`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L14766>): `src.js_parser.NewParser_`
- [`js_parser.zig:14742`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L14742>): `src.js_parser.NewParser_`
- [`js_parser.zig:7082`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L7082>): `src.js_parser.NewParser_`
- [`js_parser.zig:16126`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L16126>): `src.js_parser.NewParser_`
- [`js_parser.zig:19973`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L19973>): `src.js_parser.NewParser_`
- [`js_parser.zig:22000`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L22000>): `src.js_parser.NewParser_`
- [`js_parser.zig:16071`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L16071>): `src.js_parser.NewParser_`
- [`js_parser.zig:3469`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L3469>): `src.js_parser.Parser._parse__anon_123625`
- [`js_parser.zig:3096`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/js_parser.zig#L3096>): `src.cache.JavaScript.parse`

Features: tsconfig
