### ISSUE TITLE
`bun publish` sometimes stuck in Bun Shell

### ISSUE THREAD

**Issue by guyutongxue** [oven-sh/bun#14523]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Linux 6.1.0-25-amd64 x86_64 unknown

### What steps can reproduce the bug?

This is not 100% reproducible. Possibly happens when network is bad.

With following files:
- `package.json`: Some package name and version that we have access to

```json
{
  "name": "@gytx/test",
  "version": "0.0.1-alpha.44"
}
```

- `a.mjs` A Bun Shell script, with some prior shell command, and finally a `bun publish`:

```js
import { $ } from "bun";

await $`echo Hello`.quiet();
await $`cp a.mjs b.mjs`.quiet();
await $`bun publish --access public`;
```

At last, run `bun a.mjs`.

### What is the expected behavior?

A package published and the Bun process exited successfully.

### What do you see instead?

Bun publish stuck on here:

```
> bun a.mjs
bun publish v1.1.30 (7996d06b)

packed 57B package.json
packed 126B a.mjs
packed 126B b.mjs

Total files: 3
Shasum: 118daeb7ac9ecc5b64f23dac643148af4c0b4f6a
Integrity: sha512-IbGD6OtI4CSKK[...]uxCFGTNtyG3Iw==
Unpacked size: 309B
Packed size: 275B
# and no more output
```

The package *IS* published anyway, but the shell script cannot be continued.

### Additional information

In my experiments, above steps cannot be 100% reproducible. If the network status is not so good and more Bun Shell commands executed before the `` $`bun publish` ``, the easier this issue can happen. I have no idea about this.

**Comment by RiskyMH** [comment]
This is a tricky one. I haven't been able to reproduce it so far, but I’ll keep trying, as it seems rare but still a significant issue. It could be related to network conditions or other factors, so I’ll investigate further when I have the chance.

**Comment by guyutongxue** [comment]
Hmm... Not reproducible on GitHub Codespaces. Frustrating. 

(Btw I'm using `bunx npm publish` instead, that works on my machine)

**Comment by guyutongxue** [comment]
Ok, just mark it as duplicate for now :)
