### ISSUE TITLE
NPM: jsonwebtoken doesnt work

### ISSUE THREAD

**Issue by Kapsonfire** [oven-sh/bun#1454]
![image](https://user-images.githubusercontent.com/67053124/199675592-d5f8fdde-f078-43d5-a2dc-830d2029d805.png)

```js
import jwt from "jsonwebtoken";

const secret = "Im not that smart";
const message = "My secret message";
const json_web_token = jwt.sign(message, secret);
const decoded_message = jwt.verify(json_web_token, secret);
console.log(decoded_message);
```

Didnt break down yet, whats happening here

Version: 0.2.2 and latest canary

**Comment by OAguinagalde** [comment]
Maybe related, but almost the same code for `jwt-simple` fails as well with a different error:

code is 
```ts
import jwt from "jwt-simple";

const secret = "Im not that smart";
const data = {msg:"My secret message"};
const json_web_token = jwt.encode(data, secret);
const decoded = jwt.decode(json_web_token, secret);
```

Exception is...

```ts
70 |   var headerSeg = segments[0];
71 |   var payloadSeg = segments[1];
72 |   var signatureSeg = segments[2];
73 |
74 |   // base64 decode and parse JSON
75 |   var header = JSON.parse(base64urlDecode(headerSeg));
                   ^
SyntaxError: JSON Parse error: Unrecognized token '�'
      at jwt_decode (/mnt/c/Users/oscara/git_projects/project_cutepon/server/node_modules/jwt-simple/lib/jwt.js:75:15)
      at /mnt/c/Users/oscara/git_projects/project_cutepon/server/tests.ts:19:24
      at test (/mnt/c/Users/oscara/git_projects/project_cutepon/lib/tester.ts:52:12)
      at /mnt/c/Users/oscara/git_projects/project_cutepon/server/tests.ts:15:4
      at run (/mnt/c/Users/oscara/git_projects/project_cutepon/lib/tester.ts:62:12)
      at /mnt/c/Users/oscara/git_projects/project_cutepon/server/tests.ts:23:3
```

**Comment by Kapsonfire** [comment]
its seems like the crypto api isnt either encoding or decoding in wrong way

**Comment by panva** [comment]
1) jsonwebtoken's `decode()` is not a signature verification function, passing a secret to it does nothing. this function merely decodes the base64url encoded JSON parts (@OAguinagalde)
2) `jsonwebtoken` depends on node's `node:crypto` module. While it may end up working in `bun` for HMAC based JWS algorithms, it will not reliably work for others due to `bun`'s use of `crypto-browserify`, this polyfill is not kept up to date and its use means you're running crypto that isn't backed by a proper vetted crypto implementation.

Here's a snippet that works reliably using `jose`'s Web API based runtime (no node modules used) in bun v0.2.2

```js
import * as jose from 'jose'

const secret = new TextEncoder().encode('Im not that smart')
const data = { msg: 'My secret message' }

const jwt = await new jose.SignJWT(data)
  .setProtectedHeader({ alg: 'HS256' })
  .sign(secret)

const verified = await jose.jwtVerify(jwt, secret)

console.log(verified)
```

@Jarred-Sumner I strongly believe the choice to use `crypto-browserify` is not great. Either port the actual `node:crypto` module whilst backing it with BoringSSL or don't bundle any emulation of `node:crypto`.

**Comment by OAguinagalde** [comment]
Thanks for the explanation @panva ! I'm trying `jose` now, it seems to work (although I am struggling to use the API but thats another issue)

**Comment by isaced** [comment]
Here is my code:

```
const jwt = require("jsonwebtoken");
var token = jwt.sign({ foo: "bar" }, "shhhhh");
console.log("token: ", token);
```

error:

```
➜  bun-test git:(master) ✗ bun jsonwebtoken-example.ts 
103 | 
104 |   if (!secretOrPrivateKey && options.algorithm !== 'none') {
105 |     return failure(new Error('secretOrPrivateKey must have a value'));
106 |   }
107 | 
108 |   if (secretOrPrivateKey != null && !(secretOrPrivateKey instanceof KeyObject)) {
                                         ^
TypeError: Right hand side of instanceof is not an object
      at /Users/isaced/Desktop/some-code/bun-test/node_modules/jsonwebtoken/sign.js:108:38
      at /Users/isaced/Desktop/some-code/bun-test/jose-example.ts:2:12
```

**Comment by birkskyum** [comment]
Works in bun 0.8, and maybe earlier too - can be closed. @Kapsonfire-DE can you check?

**Comment by birkskyum** [comment]
can be closed

**Comment by ceopaludetto** [comment]
Get the same error pointed by @isaced in v0.8.1 since `KeyObject` still not implemented

**Comment by ItsDoot** [comment]
I am also getting the same error as isaced, on `v1.0`.

**Comment by prjwl16** [comment]
Getting same issue as @isaced

**Comment by danny-avila** [comment]
Same issue using the sign method on jsonwebtoken 9.0.0

```js
109 | 
110 |   if (!secretOrPrivateKey && options.algorithm !== 'none') {
111 |     return failure(new Error('secretOrPrivateKey must have a value'));
112 |   }
113 | 
114 |   if (secretOrPrivateKey != null && !(secretOrPrivateKey instanceof KeyObject)) {
                                         ^
TypeError: Right hand side of instanceof is not an object
      at /node_modules/jsonwebtoken/sign.js:114:38
```

**Comment by Lukasz-pluszczewski** [comment]
I don't understand why it has been closed and marked as "working" while `crypto.KeyObject` is still not implemented. I don't think jsonwebtoken library can work without it.
I'm getting the same error as @danny-avila "Right hand side of instanceof is not an object".

**Comment by birkskyum** [comment]
It's been reopened

**Comment by danny-avila** [comment]
> It's been reopened

Thanks! I think this is crucial for adoption. There are countless apps built in node.js with authentication. I would really like to see how my own projects' stress tests fare in the bun runtime.

I know my frontend bundling has sped up 2 seconds on average, and that's enough for me to start using bun, hoping to see this fully implemented for the backend!

**Comment by mammothpublishing** [comment]
> Here's a snippet that works reliably using `jose`'s Web API based runtime (no node modules used) in bun v0.2.2

This works, thank you. To have it work for Bun v1.0.0 I only needed to adjust line 1:

```
const jose = require('jose');

const secret = new TextEncoder().encode('Im not that smart');
const data = { msg: 'My secret message' };

const jwt = await new jose.SignJWT(data)
  .setProtectedHeader({ alg: 'HS256' })
  .sign(secret);

const verified = await jose.jwtVerify(jwt, secret);
console.log(jwt);
console.log(verified);

**Comment by PrinzJuliano** [comment]
Thanks for the workaround.
NestJS Passport integration uses jsonwebtoken which I have used in all of my NestJS Projects. Using a workaround would mean significant work rewriting security critical parts.

**Comment by danny-avila** [comment]
> Thanks for the workaround. NestJS Passport integration uses jsonwebtoken which I have used in all of my NestJS Projects. Using a workaround would mean significant work rewriting security critical parts.

My concern exactly
