### ISSUE TITLE
sub packages aren't installing upon adding package

### ISSUE THREAD

**Issue by arthurvanl** [oven-sh/bun#14549]
![Image](https://github.com/user-attachments/assets/a6f1accb-be28-4f56-963e-0c183a61efdb)

This package is made by me. I use bun publish to deploy my package.
In the discord server @RiskyMH said that I could upload my typescript files directly to npm.
After this the sub packages are not installed anymore:
![Image](https://github.com/user-attachments/assets/3881d3b6-63f2-45ff-9f58-68556758190c)

**Comment by Jarred-Sumner** [comment]
Can you include a reproduction and paste the relevant package.json files or a link to a github repository?

**Comment by arthurvanl** [comment]
I created another package: https://www.npmjs.com/package/utils-repro

# Reproduction
```sh
bun init
```

```sh
bun i utils-repro
```

Open the `node_modules` folder
Find the `utils-repro` folder
Open up the `src/index.ts`.

**Comment by arthurvanl** [comment]
Seems dev dependencies and dependencies are not published to npm (version 1.0.0 published on npm).

I also tried to publishing the same package using `npm publish`. This did upload the packages to npm (version 1.0.1).

**Comment by arthurvanl** [comment]
seems to be fixed: https://github.com/oven-sh/bun/pull/14488
