### ISSUE TITLE
Running "bun <script>" does not expand env vars anymore

### ISSUE THREAD

**Issue by bjesuiter** [oven-sh/bun#14556]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Add a .env file with content: 
```
PROD_VERSION=0.1.0
```

2. Add the following config to package.json: 
```
"config": {
    "prod_version": "0.1.0"
}
```

3. Write the following scripts in package.json

```
scripts: {
	"echo1": "echo $PROD_VERSION",
	"echo2": "echo "$PROD_VERSION"",
	"echo3": "echo ${PROD_VERSION}",
	"echo4": "echo \"$npm_config_prod_version\"",
}
```

4. Run these scripts 

5. Result: None of these scripts expand the variables inside, they simply print the script line! :O 
    Like this: `echo $PROD_VERSION` or `echo $npm_config_prod_version`

### What is the expected behavior?

The env vars should be expanded, like: 

bun echo1 // 0.1.0

### What do you see instead?

bun echo1 // echo $PROD_VERSION

**Comment by fel1x-developer** [comment]
Running `bun run ffi` also does not work in `bench/` due to this bug since it is running `$BUN bun.js` in `package.json`

**Comment by dylan-conway** [comment]
This was an intentional breaking change introduced in v1.0.36, see https://github.com/oven-sh/bun/issues/9635#issuecomment-2021350123.

Closing as not planned

**Comment by bjesuiter** [comment]
I think, we have a missunderstanding here. 

I'm not setting the env vars in the package.json script I want to execute, but I set them in a .env file. 
So, the case in your linked comment doesn't apply, since I never re-set the NODE_ENV in the package-json script. 

I simply want to expand an EnvVar comming from .env in a package json script and pass it to 'echo' :D 

There is not even a js or ts file involved. 

The goal is to run a docker command like the following via a package json script and have the version in that command interpolated: 
```js
docker buildx build --platform linux/amd64,linux/arm64 --pull -t myimage:$VERSION --push ./ubuntu-pure
```
