### ISSUE TITLE
`bun run` doesn't parse string arguments correctly

### ISSUE THREAD

**Issue by Kostas-Xafis** [oven-sh/bun#14562]
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Linux 6.5.0-44-generic x86_64 x86_64

### What steps can reproduce the bug?

I have a script named `query` that executes this: `bun --env-file=".env.development" getData/query.ts`.

Now to pass any arguments to the script I would use it like: `bun run query --prod --q "SELECT * from table"` .

But running it normally like: `bun --env-file='.env.development' getData/query.ts --prod --q "SELECT * from table"` doesn't have any problems running and parsing the arguments, like the case above.

I tried to escape both `"`  and `'` but nothing worked.

Unless this is 1-to-1 behaviour with how npm loads argruments to scripts, then I am pretty sure that this is a bug.

### What is the expected behavior?

Expected behaviour should be that the `bun run` command would parse a string argument, like in the example above correctly, as 1 argument. Like:
```python
argv = [ "/home/user/.bun/bin/bun", "/home/user/project/getData/query.ts",
  "--prod", "--q", "SELECT * FROM table"
]
```

### What do you see instead?

What I get instead is: 
```python 
argv = [
  "/home/user/.bun/bin/bun", "/home/user/project/getData/query.ts",
  "--prod", "--q", "SELECT", "astro.config.mjs", "bucket", "bunfig.toml", "bun.lockb", "dbSnapshots",
  "dist", "email", "getData", "imageCompression", "lib", "node_modules", "notAssets", "notes.txt",
  "package.json", "pdfWorker", "public", "replicaDbSync.txt", "schema.sql", "src", "tailwind.config.cjs",
  "tests", "test.ts", "tsconfig.json", "types", "wrangler.toml", "FROM", "table"
]
```

### Additional information

Importing `argv` through either `process` or `bun` result to the same problem.

**Comment by pfgithub** [comment]
Should be fixed by #14884
