### ISSUE TITLE
bunx create uses latest version of node , latest experiement verion, I want to use lts of node

### ISSUE THREAD

**Issue by prakash03yes** [oven-sh/bun#14581]
### What version of Bun is running?

1.1.30

### What platform is your computer?

linux debain

### What steps can reproduce the bug?

![Image](https://github.com/user-attachments/assets/54fc1814-2cc0-4951-8b6f-45ee817c66e5)

I have not instaled node on my machine, just only bun.

### What is the expected behavior?

![Image](https://github.com/user-attachments/assets/54fc1814-2cc0-4951-8b6f-45ee817c66e5)

**Comment by touhidurrr** [comment]
> latest experiement verion, I want to use lts of node

I don't this this is an issue? can you share your `node -v` output? I am pretty sure **Bun** just uses the **node** version that is installed on your system.

**Comment by prakash03yes** [comment]
node -v gives -> command not found. so i have installed node and tried the bunx create , and it worked.  I thought of using bun without installing node, like I usally do. wastn't sure linux cloud seems different

**Comment by touhidurrr** [comment]
> I thought of using bun without installing node, like I usally do. wastn't sure linux cloud seems different

cli tools specify what they want to be run with. for npm packages most cases this is node. i am guessing that without node installed, bun tries to run the script itself and reports as latest version of node. interesting.
