### ISSUE TITLE
`bun publish` ignores dependencies defined in package.json

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#14580]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

In my repo https://github.com/codehz/nanokv 
1. `cd npm/nanokv`
2. `bun run dist.ts`
3. `cd ../dist`
4. `bun publish` (it require login, I think you can just compare the results of `bun pm pack` and `npm pack`

### What is the expected behavior?

should same as npm publish

![Image](https://github.com/user-attachments/assets/ff06052d-afdd-4ccd-a944-1a082eeeed93)
![Image](https://github.com/user-attachments/assets/e94b7e25-40d4-4853-b7c4-c76050eb54ce)

### What do you see instead?

The result is https://www.npmjs.com/package/nanokv/v/0.3.3
but I found the dependencies is missing from this version, which cause runtime error
`npm publish` is OK

![Image](https://github.com/user-attachments/assets/b277c45b-f5cc-4adb-9adb-99e70b585c9a)
![Image](https://github.com/user-attachments/assets/2719b359-5b3d-4881-98f4-1ec3a967511b)

### Additional information

just make a diff:
```diff
diff --color=auto bun/package.json npm/package.json
1c1
< { "name": "nanokv", "version": "0.3.4", "module": "index.js", "type": "module", "description": "A simple kv implementation.", "repository": { "type": "git", "url": "git+https://github.com/codehz/nanokv.git" }, "license": "MIT", "author": { "name": "CodeHz", "email": "git@hertz.moe" }, "keywords": ["kv", "nanokv"], "devDependencies": {}, "dependencies": { "flatbuffers": "^24.3.25" } }
\ No newline at end of file
---
> {"name":"nanokv","version":"0.3.4","module":"index.js","type":"module","description":"A simple kv implementation.","repository":{"type":"git","url":"git+https://github.com/codehz/nanokv.git"},"license":"MIT","author":{"name":"CodeHz","email":"git@hertz.moe"},"keywords":["kv","nanokv"],"devDependencies":{},"dependencies":{"flatbuffers":"^24.3.25"}}
\ No newline at end of file
```

**Comment by RiskyMH** [comment]
Oh, this is the same issue we encountered in #14549, and it was fixed in the canary build from #14488!
