### ISSUE TITLE
`bun install` does not install any package at all if one post script fails

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#14583]
### What version of Bun is running?

`1.1.31-canary.53+5532e1af1`

### What platform is your computer?

`Microsoft Windows NT 10.0.22631.0 x64`

### What steps can reproduce the bug?

```bash
git clone https://github.com/jmerle/competitive-companion.git
cd competitive-companion
bun install # fails on canvas post script
bun build:firefox # fails saying many packages cannot be imported
```

### What is the expected behavior?

`node_modules` and `bun.lockb` gets generated. most packages are installed.

### What do you see instead?

`node_modules` and `bun.lockb` is not generated. no package gets installed.

### Additional information

`yarn` works. For example:
```bash
yarn # complains on canvas, but works anyways
bun build:firefox # works
```

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.33 with #14783. `canvas` is an optional dependency of `pdfjs-dist`
