### ISSUE TITLE
installing package directly from github is broken

### ISSUE THREAD

**Issue by capaj** [oven-sh/bun#14609]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Linux 6.8.0-45-generic x86_64 x86_64

### What steps can reproduce the bug?

run `bun add sergeymild/react-native-alert` in any project, empty folder works too

### What is the expected behavior?

https://github.com/sergeymild/react-native-alert/ gets installed

### What do you see instead?

[0.03ms] ".env.production", ".env"
bun add v1.1.30 (7996d06b)
error: GET https://api.github.com/repos/sergeymild/react-native-alert/tarball/ - 401
error: sergeymild/react-native-alert failed to resolve

### Additional information

tested on both macos and ubuntu 24.04

works fine with pnpm/yarn/npm

**Comment by Mara-Li** [comment]
Related to #14557 ?

**Comment by capaj** [comment]
@Mara-Li yes it's a dupe, closing

**Comment by RiskyMH** [comment]
Duplicate of #14557
