### ISSUE TITLE
Segmentation Fault using Nuxt Nitro Server

### ISSUE THREAD

**Issue by yschroe** [oven-sh/bun#14617]
### How can we reproduce the crash?

It basically the same crash as in #13001 but I can't reopen the issue and it still happens in v1.1.30.

Repro repo: https://github.com/yschroe/bun-segfault-nuxt

1. Start the dev server via `bun --bun run dev`.
2. Navigate to server/api/test.ts.
3. Just hit CTRL+S a few times to save the file over and over again.
4. Each save should trigger `✔ Nuxt Nitro server built in xx ms` in the console (I am using the prettier Plugin for VS Code - not sure if it is a prerequisite to actually trigger a rebuild due to reformatting).
5. After a few times (10-30) bun crashes on my system.

### Relevant log output

```sh
✔ Nuxt Nitro server built in 84 ms                                                                                                                                                                      nitro 19:35:59
✔ Nuxt Nitro server built in 79 ms                                                                                                                                                                      nitro 19:35:59
✔ Nuxt Nitro server built in 95 ms                                                                                                                                                                      nitro 19:35:59
============================================================
Bun v1.1.30 (7996d06b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "node" "C:\Users\yanni\Documents\repos\bun-segfault-nuxt\node_modules\nuxi\bin\nuxi.mjs" "dev"
Features: Bun.stdin(56) Bun.stdout http_server(27) jsc spawn(4) transpiler_cache(199) tsconfig(57) tsconfig_paths(16) workers_spawned(27) workers_terminated(26) 
Builtins: "bun:jsc" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" 
Elapsed: 23658ms | User: 6406ms | Sys: 1484ms
RSS: 1.81GB | Peak: 1.81GB | Commit: 6.76GB | Faults: 773072

panic(thread 4212): Segmentation fault at address 0x2D786364C18
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.30/wn17996d06M1//6/diwnjH+lrsSolnhMk7xgMkz8rByk21Ly+55Jo685J0guoxB_A2utBx+5m55D

error: script "dev" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x37810552DC4

- [`module_loader.zig:1919`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/module_loader.zig#L1919>): `transpileSourceCode`
- [`module_loader.zig:2361`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/module_loader.zig#L2361>): `Bun__transpileFile`
- [`ModuleLoader.cpp:785`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/ModuleLoader.cpp#L785>): `Bun::fetchESMSourceCode<1>`
- [`ModuleLoader.cpp:883`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/ModuleLoader.cpp#L883>): `Bun::fetchESMSourceCodeAsync`
- [`ZigGlobalObject.cpp:4066`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/ZigGlobalObject.cpp#L4066>): `Zig::GlobalObject::moduleLoaderFetch`
- [`JSModuleLoader.cpp:277`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L277>): `JSC::JSModuleLoader::fetch`
- [`JSModuleLoader.cpp:486`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L486>): `JSC::moduleLoaderFetch`

Features: workers\_spawned, workers\_terminated, Bun.stdin, Bun.stdout, extracted\_packages, http\_server, jsc, spawn, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
