### ISSUE TITLE
CryptoHasher with sha3-512 algorithm for HMAC crashes

### ISSUE THREAD

**Issue by heavensrevenge** [oven-sh/bun#14616]
### How can we reproduce the crash?

`const hasher = new CryptoHasher("sha3-512", "key"); console.log(hasher.update("1").digest("hex"));`
CryptoHasher instantiation to make an HMAC sha3-512 algorithm, which it says it supports in the list upon trying something invalid, crashes bun while 1.1.29 doesn't crash.

### Relevant log output

Bun v1.1.30 (7996d06b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "bun-windows-x64\bun.exe" "hash-test.js"
Features: Bun.stdin Bun.stdout jsc
Builtins: "bun:main" "node:string_decoder" "node:util/types"
Elapsed: 1461ms | User: 0ms | Sys: 15ms
RSS: 112.70MB | Peak: 112.70MB | Commit: 0.16GB | Faults: 27726

panic(main thread): Segmentation fault at address 0x28
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000028

- [`digest.c:77`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/C:/buildkite-agent/builds/windows-x64-hetzner-9/bun/bun/vendor/boringssl/crypto/fipsmodule/digest/digest.c#L77>): `EVP_MD_block_size`
- [`BunObject.zig:1202`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/api/BunObject.zig#L1202>): `init`
- [`encoding.zig:466`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/webcore/encoding.zig#L466>): `constructor`
- [`ZigGeneratedClasses.cpp:7209`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/C:/buildkite-agent/builds/windows-x64-hetzner-4/bun/bun/build/release-ci/codegen/ZigGeneratedClasses.cpp#L7209>): `WebCore::JSCryptoHasherConstructor::construct`
- *2 unknown/js code*
- `llint_entry`

Features: jsc

**Comment by Jarred-Sumner** [comment]
Ah this is supposed to throw a runtime exception saying it’s not supported
