### ISSUE TITLE
`bun publish` does not keep homepage, license or repository fields from `package.json` when publishing to the NPM package registry

### ISSUE THREAD

**Issue by benyakirten** [oven-sh/bun#14633]
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bun init`
2. Add a `repository`, `homepage` and `license` field to the `package.json` as well as all other fields required for a package to be published to the npm registry (`author`, `main`, etc.)
3. Write a `.npmrc` file and configure it to publish to the NPM package registry
4. Run `bun publish`
5. Observe the sidebar does not have the various fields filled out.

### What is the expected behavior?

I expect the sidebar on the npm registry to have the license, homepage and repository fields filled out using the `package.json` fields. Although screenshots are discouraged, I will include a screenshot of what the page looks like if I run `npm publish`:

![Image](https://github.com/user-attachments/assets/5ae421a0-11d1-4218-aa23-93b042d5becb)

### What do you see instead?

The license is filled as `none`  repository and website pages are empty. Although screenshots are discouraged, I feel it is helpful for illustrative purposes:

![Image](https://github.com/user-attachments/assets/75c62f64-4e89-41e4-b85b-981e4f6e3b3c)

### Additional information

The documentation for `bun publish` mentions a configuration file for `bunfig.toml`, but it does not appear that `bunfig.toml` has the appropriate fields to help with my problem.

**Comment by RiskyMH** [comment]
Can you try updating Bun to version v1.1.31? It seems that pr #14488, which addresses the missing metadata in `bun publish`, has been fixed in this release.

The update should resolve the problem you're encountering with missing metadata when publishing packages to the npm registry. Let me know how it goes!

**Comment by benyakirten** [comment]
Thank you for the response. I just published using bun version `v1.1.31`, and it correctly included the metadata fields.
