### ISSUE TITLE
`TransformStream` can't be canceled properly

### ISSUE THREAD

**Issue by HK-SHAO** [oven-sh/bun#14652]
### What version of Bun is running?

1.1.31

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Run `bun test.js`:

```js
const test = async () => {
  for (let i = 0; i < 3; i++) {
    const stream = new ReadableStream({
      start(controller) {
        controller.enqueue('Hello');
        controller.enqueue('World');
        controller.close();
      },
    });
    const transformer = new TransformStream({
      transform(chunk, controller) {
        controller.enqueue(chunk);
      },
    });
    const stream2 = stream.pipeThrough(transformer);
    for await (const chunk of stream2) {
      console.log(chunk);
      break;
    }
  }
};

test();

```

### What is the expected behavior?

```log
Hello
Hello
Hello
```

### What do you see instead?

```log
Hello
Hello
Hello
error: undefined
error: undefined
error: undefined
```

### Additional information

The same error is reported when executing the following code.
```js
const reader = stream2.getReader();
await reader.cancel();
```

However, in `nodejs v22.6.0` everything works fine.

**Comment by guest271314** [comment]
Reproducible on Linux Bun version 1.1.31.

Works as expected using `node` v23.0.0-nightly20241016019efe1453 and `deno` deno 2.0.0+661882f (canary, release, x86_64-unknown-linux-gnu).

**Comment by HK-SHAO** [comment]
It's fixed.
