### ISSUE TITLE
Bun Crash

### ISSUE THREAD

**Issue by mjjabarullah** [oven-sh/bun#14685]
### Stack Trace (bun.report)

Bun v1.1.31 ([`e448c4c`](<https://github.com/oven-sh/bun/tree/e448c4cc3bf43fc67e39799d34c4ed70b8037509>)) on windows x86_64 [RunCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\projects\web-obelis-platform\packages\eslint\node_modules\@obelis\eslint-plugin-obelis\src\index.ts'

- [`xxhash.zig:189`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-aXOE3R/bun/bun/vendor/zig/lib/std/hash/xxhash.zig#L189>): `update`
- [`tracy.zig:24`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509/src/tracy.zig#L24>): `end`
- [`thread_pool.zig:351`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509/src/thread_pool.zig#L351>): `Do`
- [`fmt.zig:1185`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-aXOE3R/bun/bun/vendor/zig/lib/std/fmt.zig#L1185>): `formatInt`

**Comment by zsj1029** [comment]
https://github.com/oven-sh/bun/issues/14767#issuecomment-2434075470

**Comment by cirospaciari** [comment]
Fixed by https://github.com/oven-sh/bun/pull/15119
