### ISSUE TITLE
using send() in open() event of ServerWebSocket cause disconnect

### ISSUE THREAD

**Issue by mganeko** [oven-sh/bun#1469]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:04:57 UTC 2022 aarch64 aarch64

### What steps can reproduce the bug?

If I use send() function immediately  in open() event handler of ServerWebSocket, then the connection will be disconnected after first message() event handler.

Server code

```js:bun_websocket_server.js

const PORT=8000;
const HOST='localhost';

Bun.serve({
  host: HOST,
  port: PORT,
  websocket: {
    open(ws) {
      console.log('--open--');

      // --- FAIL:  cause disconnect after 1st message event --
       ws.send('connected!'); // DO NOT reach to the client
    },

    message(ws, message) {
      console.log('received: %s', message);
      ws.send('Echoback:' + message);
    },

    close(ws) {
      console.log('--close--');
    },

    perMessageDeflate: false,
  },

  fetch(req, server) {
    if (server.upgrade(req))
      return;

    return new Response("Regular HTTP response");
  },
});

console.log('Server start on port:' + PORT);
```

Clinet code

```js:client.js

const PORT = 8000;
const URL = 'ws://localhost:' + PORT; // OK for Node.js, OK for Bun
//const URL = 'ws://127.0.0.1:' + PORT; // OK
const Client = require('ws').WebSocket;

const ws = new Client(URL);

ws.on('open', function open() {
  ws.send('Hello');
});

ws.on('message', function message(data) {
  console.log('received: %s', data);
  const text = '' + data;

  if (text === 'Echoback:Hello') {
    ws.send('BYE');
  }
});


```

Run Server

```
$ bun bun_websocket_server.js
```

Run Client

```
$ bun client.js
```

### How often does it reproduce? Is there a required condition?

Every time I use Bun server and Bun client.

If I use Node.js for client, it will not happen.

```
$ node client.js
```

### What is the expected behavior?

The connection will be keep alive and sent message from server will reach to the client.

### What do you see instead?

The connection will be disconnected after first message from client, and message from server  will not reach to the client.

### Additional information

If I do not use send() in open() event handler, then the connection will be alive and works well.

Also I use setTimeout() before send() in open() even handler, then the connection will be alive and works well.

```js
Bun.serve({
  host: HOST,
  port: PORT,
  websocket: {
    open(ws) {
      console.log('--open--');


      //  -- OK: need timeout for Bun ws client --
      setTimeout(() => {
          ws.send('connected!'); // reach to the client
      }, 10);

   // -------
 }
}
```

Full source code:

- https://github.com/mganeko/websocket_server_sample/blob/master/bun_websocket_server.js
- https://github.com/mganeko/websocket_server_sample/blob/master/client.js

**Comment by Jarred-Sumner** [comment]
I think this is an issue with the WebSocket client and not the server

**Comment by mganeko** [comment]
It seems that  this issue happens on the combination of ServerWebSocket and Bun WebScoket client.

When I use  Node.js ws server and Bun client, it works well.

```js:ws_server.js
// WebSocker server with Node.js
const PORT = 8000;
const Server = require('ws').WebSocketServer;
const wss = new Server({port:PORT});

wss.on('connection', function connection(ws) {
  ws.on('message', function message(data) {
    console.log('received: %s', data);
    ws.send('Echoback:' + data);
    const text = '' + data;

    if (text === 'QUIT') {
      console.log('QUIT Server');
      process.exit(0);
    }
  });

  ws.send('connected!');
});

console.log('WS server listening port:' + PORT);
```

```

**Comment by cirospaciari** [comment]
@mganeko this still happens on `v0.6.3`?

**Comment by mganeko** [comment]
@cirospaciari Thank you for your notice.
I tried v0.6.3.
It doesn't happen any more.
Thank you for fixing this issue!
