### ISSUE TITLE
`bun link` won't work on packages with `name`: `@something/somethingelse`

### ISSUE THREAD

**Issue by einar-hjortdal** [oven-sh/bun#1470]
### What version of Bun is running?

0.2.2

### What platform is your computer?

`Linux 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Thu Sep 22 11:36:42 UTC 2022 x86_64 x86_64`

### What steps can reproduce the bug?

1. Install bun
2. cd to directory of a project. This project must have a name containing the character `@` in `package.json`
4. `bun install`
5. 
```bash
$ bun link
bun link v0.2.2
error: failed to create symlink to node_modules in global dir due to error FileNotFound
```

### How often does it reproduce? Is there a required condition?

Every time a package name contains `@` such as in the case of any package in a monorepo.

### What is the expected behavior?

`Success! Registered "@something/somethingelse"`

### What do you see instead?

`error: failed to create symlink to node_modules in global dir due to error FileNotFound`

**Comment by einar-hjortdal** [comment]
Temporarily closed because something else may be causing this. Investigating

**Comment by danilotorrisi** [comment]
I got the same error while trying to link @organization/some-package modules, the issue is still there on 0.3.0.

**Comment by saravanan10393** [comment]
I got the same error above. This error still there in 0.5.1

**Comment by alator21** [comment]
I'm getting 

```
error: invalid package.json name "@orgName/packageName" in { 47, 104, ... }"
```
when running `bun link` 

`bun -v`

-> `1.0.14`

**Comment by alator21** [comment]
Did some experiments and the reason that above was failing is because my packageName was actually like "@orgName/libs/packageName". Apparently this convention is not allowed by neither bun or npm.
