### ISSUE TITLE
bun test crashes on `revert` from Solidity contract

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [oven-sh/bun#14716]
Hi,

I'm using the bun test runner for testing Solidity contracts with the HardHat default provider. On each `revert` from the Solidity contract bun crashes with a segfault.

### How can we reproduce the crash?

Install dependencies
```fish
bun install  hardhat @nomicfoundation/hardhat-toolbox
```

Configure HardHat in `./hardhat.config.js`
```js
require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.27",
};
```

Create the minimal Solidity contract in `./contracts/Revert.sol`
```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.0;

contract Revert {
  error Oh();
  function doRevert() pure external {
    revert Oh();
  }
}
```
Compile the Solidity contract
```fish
bunx hardhat compile
```

Create the minimal JS test using the bun test runner in `./tests/Revert.test.js`
```js
import { ethers } from "hardhat"

test("Unconditional revert", async() => {
  const revert = await ethers.deployContract("Revert")
  await revert.doRevert()
})
```

Run the test with the bun test runner
```fish
bun test
```

The bun test runner *crashes* every time.

Thank you for doing the exceptional work!

### Stack Trace (bun.report)

Bun v1.1.32 ([`fe8d007`](<https://github.com/oven-sh/bun/tree/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e>)) on linux x86_64_baseline [TestCommand]

Segmentation fault at address 0x00000020

- [`ZigGlobalObject.cpp:308`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/bindings/ZigGlobalObject.cpp#L308>): `formatStackTraceToJSValue`
- [`ZigGlobalObject.cpp:2642`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/bindings/ZigGlobalObject.cpp#L2642>): `Zig::jsFunctionDefaultErrorPrepareStackTrace`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ZigGlobalObject.cpp:336`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/bindings/ZigGlobalObject.cpp#L336>): `formatStackTraceToJSValue`
- [`ZigGlobalObject.cpp:697`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/bindings/ZigGlobalObject.cpp#L697>): `computeErrorInfoWithPrepareStackTrace`
- [`ZigGlobalObject.cpp:737`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/bindings/ZigGlobalObject.cpp#L737>): `computeErrorInfoToJSValue`

Features: jsc, no\_avx2, transpiler\_cache, tsconfig

**Comment by Jarred-Sumner** [comment]
Thank you for the reproduction, that made this a lot easier to fix
