### ISSUE TITLE
Support Next.js

### ISSUE THREAD

**Issue by isrmicha** [oven-sh/bun#1472]
### What is the problem this feature would solve?

The create bun next app will install NextJs 12.x.x

### What is the feature you are proposing to solve the problem?

Support for NextJs 13 on create bun next app

**Comment by KryptXBSA** [comment]
Anyone got Next 13 working with bun?
I keep getting this error when trying to use the `app` dir:
```
error: MissingRouteDir

----- bun meta -----
Bun v0.6.14 (b5665739) Linux x64 #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M
DevCommand: framework public_folder bunfig
Elapsed: 1ms | User: 0ms | Sys: 4ms
RSS: 33.55MB | Peak: 14.68MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x56524658860b
```

**Comment by ChiefORZ** [comment]
Working like a charm, using server components, use client directives, error pages, api directory.
Are you maybe using [server actions](https://nextjs.org/docs/app/api-reference/functions/server-actions)?
