### ISSUE TITLE
Class type declaration must be removed during bundling

### ISSUE THREAD

**Issue by mattfysh** [oven-sh/bun#14753]
### What version of Bun is running?

1.1.32+fe8d0079e

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

**index.ts**
```ts
class Parent {
  constructor() {
    Object.assign(this, { x: 'abc' })
  }
}

export class Child extends Parent {
  public readonly x!: string
}

export class ChildNoType extends Parent {}
```

**bug.sh**
```sh
bun build index.ts --outfile build.js
bun -e "import * as x from './build.js'; console.log(new x.Child()); console.log(new x.ChildNoType())"
```

### What is the expected behavior?

```
Child {
  x: "abc",
}
ChildNoType {
  x: "abc",
}
```

### What do you see instead?

```
Child {
  x: undefined,
}
ChildNoType {
  x: "abc",
}
```

**Comment by mattfysh** [comment]
Notable output from **build.js** where the type declaration was turned into an undefined property.

```js
class Child extends Parent {
  x;
}
```

**Comment by Jarred-Sumner** [comment]
We are tracking this in https://github.com/oven-sh/bun/issues/4612, please follow along there. Thanks for providing a clear case where this behavior breaks code
