### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kodermax** [oven-sh/bun#14765]
### Stack Trace (bun.report)

Bun v1.1.31 ([`e448c4c`](<https://github.com/oven-sh/bun/tree/e448c4cc3bf43fc67e39799d34c4ed70b8037509>)) on windows x86_64 [RunCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\projects\web-obelis-platform\packages\eslint\node_modules\@obelis\eslint-plugin-obelis\src\index.ts'

- [`xxhash.zig:189`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-aXOE3R/bun/bun/vendor/zig/lib/std/hash/xxhash.zig#L189>): `update`
- [`tracy.zig:24`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509/src/tracy.zig#L24>): `end`
- [`thread_pool.zig:351`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509/src/thread_pool.zig#L351>): `Do`
- [`fmt.zig:1185`](<https://github.com/oven-sh/bun/blob/e448c4cc3bf43fc67e39799d34c4ed70b8037509//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-aXOE3R/bun/bun/vendor/zig/lib/std/fmt.zig#L1185>): `formatInt`

**Comment by cirospaciari** [comment]
Can you describe how you got into this issue, and provide the code/minimal reproduction for this error?

**Comment by zsj1029** [comment]
#14767

**Comment by cirospaciari** [comment]
Duplicated of https://github.com/oven-sh/bun/issues/14685
