### ISSUE TITLE
Reached unreachable code in `NuxtJS 3`

### ISSUE THREAD

**Issue by Mixerou** [oven-sh/bun#14775]
### How can we reproduce the crash?

Develop an app with `NuxtJS 3`. Failure occurs sometimes during a hot reload.

### Relevant log output

```
Bun v1.1.32 (fe8d0079) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "node" "C:\Users\[REDACTED]\GitHub\[REDACTED]\[REDACTED]\node_modules\nuxi\bin\nuxi.mjs" "dev" "--host"
Features: Bun.stderr(2) Bun.stdin(8) Bun.stdout(2) abort_signal bunfig fetch(161) http_server(4) jsc spawn(3) transpiler_cache(93) tsconfig(102) tsconfig_paths(51) workers_spawned(7) workers_terminated(2) 
Builtins: "bun:jsc" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" 
Elapsed: 211709ms | User: 73125ms | Sys: 13859ms
RSS: 5.00GB | Peak: 5.00GB | Commit: 10.40GB | Faults: 1417003
```

### Stack Trace (bun.report)

Bun v1.1.32 ([`fe8d007`](<https://github.com/oven-sh/bun/tree/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e>)) on windows x86_64 [RunAsNodeCommand]

**panic**: reached unreachable code

- [`array_hash_map.zig:873`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-EsNl1L/bun/bun/vendor/zig/lib/std/array_hash_map.zig#L873>): `ensureTotalCapacityContext`
- [`node_fs_watcher.zig:753`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bun.js/node/node_fs_watcher.zig#L753>): `init`
- [`JSCJSValue.h:753`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/C:/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/windows-x64-build-cpp/webkit-543cca2140eafdba845f6689024abaac0d9924f5/include/JavaScriptCore/JSCJSValue.h#L753>): `JSC::ensureStillAliveHere`

Features: workers\_spawned, workers\_terminated, Bun.stderr, Bun.stdin, Bun.stdout, dotenv, fetch, http\_server, jsc, spawn, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
