### ISSUE TITLE
bun --watch logs error twice

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#14791]
### What version of Bun is running?

1.1.33-canary.16+6f60523e6

### What platform is your computer?

Linux 6.8.0-47-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
// bug.js

console.log(Math.random());

console.log(location);
```
```
bun --watch bug.js
```

### What is the expected behavior?

for the error to show once

### What do you see instead?

error shows twice

### Additional information

![Image](https://github.com/user-attachments/assets/071bd05b-4ecd-48a0-a0fa-3adffe2c71c9)

**Comment by RiskyMH** [comment]
Fixed by  #15261 and released in [`bun v1.1.37`](https://bun.sh/blog/bun-v1.1.37#fixed-errors-printing-twice-in-watch-or-hot-mode)
