### ISSUE TITLE
Crash at 0x9E010000E8030000 when trying to ```server.upgrade()``` to web socket - free(): invalid pointer 

### ISSUE THREAD

**Issue by davood-n** [oven-sh/bun#1480]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

I've isolated a random crash that started to happen randomly today. Bun crashes with server.upgrade().
```javascript
fetch: (request, server) => {
    server.upgrade(reqeust)
    // Indiscriminately crashes in my web socket server no matter where I put it in response process.
}

```

### How often does it reproduce? Is there a required condition?

Crashes randomly started to happen today. There was a line in my  code where a server.upgrade was tried, and that remained problem free for the longest time; until today. It crashes no matter where I put it in my code, even if I strip away my router, all middleware, and auth. However, on a fresh new index.ts file, server.upgrade(req) doesn't cause a crash.

### What is the expected behavior?

Successful connection upgrade to web socket.

### What do you see instead?

![Screenshot 2022-11-09 201354](https://user-images.githubusercontent.com/73272137/200992165-f4abace3-76ef-43c4-b5ea-87608c6f02db.png)

### Additional information

The link to my code can be found [https://github.com/davidn000/bun-web-socket-server](https://github.com/davidn000/bun-web-socket-server).

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/c52ebd96ba5d0b695a4b7a27071815a96d1f568f
