### ISSUE TITLE
Be able to run bun:test from within the VSCode Debugger

### ISSUE THREAD

**Issue by inf3rnus** [oven-sh/bun#14806]
### What is the problem this feature would solve?

You would be able to run the debugger on your test code.

### What is the feature you are proposing to solve the problem?

I propose you do whatever it takes to allow the debugger to run code that uses `from "bun:test";`

### What alternatives have you considered?

- Using node.js to run .ts files, (ew)
- Crying

**Comment by pfgithub** [comment]
The bun extension for vscode supports debugging tests: https://bun.sh/guides/runtime/vscode-official

Open the `.test.ts` file and run with "Bun: Debug File"

**Comment by inf3rnus** [comment]
The bun team is so unbelievably GOAT'd!!!

Thank you so much, can't wait to try this out!
