### ISSUE TITLE
bun: command not found when command is a variable

### ISSUE THREAD

**Issue by fpereira1** [oven-sh/bun#14810]
### What version of Bun is running?

1.1.33-canary.15+2de2e9f60

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

using this code

```js
import { $ } from 'bun';

// Does not work
const cmd = `ffmpeg --help`;
await $`${cmd}`;

// Works!
await $`ffmpeg --help`;
```

### What is the expected behavior?

Same output as 

```js
await $`ffmpeg --help`;
```

### What do you see instead?

Error message: 
```
bun: command not found: ffmpeg --help
1 | import { $ } from 'bun';
2 |
3 | const cmd = `ffmpeg --help`;
4 | await $`${cmd}`;
                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "bun: command not found: ffmpeg --help\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
```

**Comment by nektro** [comment]
when part of the the command output is in a variable, `await $`${{ raw: cmd }}`;` is the proper way to invoke it

additionally `await $`${{ raw: cmd }} --flag ${arg}`;` can be used to add extra arguments
