### ISSUE TITLE
Fails to parse Typescript rest spread syntax in function parameter object pattern 

### ISSUE THREAD

**Issue by yepitschunked** [oven-sh/bun#1481]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

```
export interface Test {
  ({ foo: string, ...rest }): JSX.Element;
}
```

should parse, but produces an error in bun

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

it should parse

### What do you see instead?

```
error: Unexpected ...

  ({ foo: string, ...rest }): JSX.Element;
                  ^
```

**Comment by Electroid** [comment]
@robobun

```ts
export interface Test {
  ({ foo: string, ...rest }): JSX.Element;
}
```

**Comment by robobun** [comment]
error: Unexpected ...
  ({ foo: string, ...rest }): JSX.Element;
                  ^
/tmp/bun-jR13dw/08c22f39551545f1a38638afe312019d31a8f7414fedd69add2151d96a05938e.ts:2:19 43
