### ISSUE TITLE
Bun crashed during bun install

### ISSUE THREAD

**Issue by N1ghtHunter** [oven-sh/bun#14823]
### `package.json` file

```json
{
  "name": "******",
  "version": "1.6.0",
  "description": "******",
  "main": "app.js",
  "scripts": {
    "start": "******",
    "dev": "******",
    "staging": "******",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "format": "prettier --write .",
    "test": "jest --coverage"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@sendgrid/mail": "^8.1.3",
    "@sentry/node": "^8.32.0",
    "@sentry/profiling-node": "^8.32.0",
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "dotenv-handler": "^1.3.0",
    "eslint-plugin-jest": "^28.8.2",
    "express": "^4.19.2",
    "express-validator": "^7.2.0",
    "helmet": "^7.1.0",
    "interworky-core": "file:",
    "jsonwebtoken": "^9.0.2",
    "moment-timezone": "^0.5.46",
    "mongodb": "^6.8.0",
    "mongoose": "^8.6.1",
    "morgan": "^1.10.0",
    "openai": "^4.57.1",
    "twilio": "^5.2.3",
    "uuid": "^10.0.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.9.1",
    "cross-env": "^7.0.3",
    "eslint": "^9.9.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.2.1",
    "globals": "^15.9.0",
    "jest": "^29.7.0",
    "nodemon": "^3.1.4",
    "supertest": "^7.0.0"
  }
}
```

### How can we reproduce the crash?

Just run `bun install`

### Relevant log output

```
bun install v1.1.33 (247456b6)
[7.65ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\zamza\.bun\bin\bun.exe" "install"
Features: extracted_packages(65) lockfile_migration_from_package_lock 
Elapsed: 10570ms | User: 625ms | Sys: 6421ms
RSS: 0.23GB | Peak: 0.24GB | Commit: 0.39GB | Faults: 94377

panic(main thread): Internal assertion failure: unexpected resolution tag
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure: unexpected resolution tag

- [`install.zig:12918`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L12918>): `installPackageWithNameAndResolution`
- [`install.zig:13240`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L13240>): `installPackage`
- [`install.zig:13704`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L13704>): `installPackages`
- [`install.zig:14536`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L14536>): `installWithManager`
- [`install.zig:11993`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L11993>): `install`
- [`cli.zig:1676`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/cli.zig#L1676>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/src/startup/exe_common.inl#L78>): `invoke_main`

Features: extracted\_packages, lockfile\_migration\_from\_package\_lock

**Comment by dylan-conway** [comment]
Fixed with #14811, and will be included in bun v1.1.34.
