### ISSUE TITLE
HTTP spec issues

### ISSUE THREAD

**Issue by uNetworkingAB** [oven-sh/bun#14826]
### What version of Bun is running?

1.1.34-canary.10+61534c7ef

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

There are a few spec. compliance issues in Bun which aren't in upstream uWS. I have a tool to trigger them at https://github.com/uNetworking/h1spec

Here's the run:

![Image](https://github.com/user-attachments/assets/a46dcc6f-e99c-4a69-9b10-94a7a2c2f234)

Specifically the timeout issues. Syncing with uWS would fix these issues.

Running the test against Node.js HTTP server produces no issues. Also Deno passes most tests.

### What is the expected behavior?

All tests passing as the upstream uWS does.

### What do you see instead?

The failed tests. Many tests fail because Bun closes the connection instead of sending an HTTP error status code, and other tests fail from timing out rather than sending a HTTP status error code.

**Comment by Jarred-Sumner** [comment]
Thank you
