### ISSUE TITLE
Bun's TCP Socket server is unreliable

### ISSUE THREAD

**Issue by Ikaleio** [oven-sh/bun#14836]
### What version of Bun is running?

1.1.33+247456b6

### What platform is your computer?

Windows 11 x64 and Debian 12 Bookwarm x64

### What steps can reproduce the bug?

[Ikaleio/portforwarding_test](https://github.com/Ikaleio/portforwarding_test)

There seems to be an issue with Bun's implementation of `net.createServer` or `Bun.listen`, resulting in inconsistencies between the data received and the data sent.

The provided repository contains my tests for `Bun.listen`, `net.createServer(with Bun)`, and `net.createServer(with Nodejs)`, with only `net.createServer(with Nodejs)` successfully completing reliable transmission.

### What is the expected behavior?

Please refer to the repository I have provided for further details.

### What do you see instead?

Please refer to the repository I have provided for further details.

### Additional information

Please refer to the repository I have provided for further details.

**Comment by Jarred-Sumner** [comment]
Bun's socket API does not buffer data, which means that if an incomplete write occurs, you have to track that and then send it on drain. The provided repository doesn't check if all the passed bytes were sent

**Comment by Ikaleio** [comment]
> Bun's socket API does not buffer data, which means that if an incomplete write occurs, you have to track that and then send it on drain. The provided repository doesn't check if all the passed bytes were sent

However, there are also issues with the implementation using only the Node.js net module.

Additionally, could you provide a correct example of implementing simple port forwarding using the Bun TCP API?

**Comment by Ikaleio** [comment]
The following code always works properly in a Windows environment but consistently freezes at 3.6 MB in a Debian 12 environment (although everything is fine when it's <3 MB).

```ts
import { listen, connect } from 'bun'
import { randomBytes } from 'crypto'

const data = randomBytes(16 * 1024 * 1024) // Generate 16MB of random data

let recvBuffer = Buffer.alloc(0)

listen({
	hostname: '127.0.0.1',
	port: 55555,
	socket: {
		open(socket) {
			socket.write(data)
		},
		data(socket, chunk) {
			recvBuffer = Buffer.concat([recvBuffer, chunk])
			console.log(`Total MB: ${recvBuffer.byteLength / 1024 / 1024}`)
			if (recvBuffer.byteLength >= data.byteLength) {
				console.log(
					`Validation result: ${Buffer.compare(recvBuffer, data) === 0}`
				)
				socket.end()
			}
		}
	}
})

const client = await connect({
	hostname: '127.0.0.1',
	port: 55555,
	socket: {
		open(socket) {
			socket.write(data)
		},
		data(socket, data) {}
	}
})
```

**Comment by Jarred-Sumner** [comment]
The code snippet above does not handle incomplete writes. Like the underlying [`send`](https://man7.org/linux/man-pages/man2/sendto.2.html) system call, calling `socket.write` using Bun's TCP socket API does not buffer data. Assuming all writes went through completely will lead to lost data.

If this issue is also occuring in `node:net`, then that is definitely a bug because `node:net` does buffer data.

Here is an implementation that handles incomplete writes:
```ts
import { listen, connect } from "bun";
import { randomBytes } from "crypto";

const data = randomBytes(16 * 1024 * 1024); // Generate 16MB of random data

let recvBuffer = Buffer.alloc(0);
let serverBuffer = data;
var listener = listen({
  hostname: "127.0.0.1",
  port: 0,
  socket: {
    open(socket) {
      const written = socket.write(serverBuffer);
      console.log(`Server written: ${written}`);
      if (written > 0) {
        serverBuffer = serverBuffer.subarray(written);
      }
    },
    drain(socket) {
      while (serverBuffer.byteLength > 0) {
        const written = socket.write(serverBuffer);
        if (written === 0) {
          break;
        }
        console.log(`Server drain written: ${written}`);
        serverBuffer = serverBuffer.subarray(written);
      }
    },
    data(socket, chunk) {
      recvBuffer = Buffer.concat([recvBuffer, chunk]);
      console.log(`Total MB: ${recvBuffer.byteLength / 1024 / 1024}`);
      if (recvBuffer.byteLength >= data.byteLength) {
        console.log(
          `Validation result: ${Buffer.compare(recvBuffer, data) === 0}`
        );
        socket.end();
        listener.stop();
      }
    },
  },
});

let clientBuffer = data;
await connect({
  hostname: "127.0.0.1",
  port: listener.port,
  socket: {
    open(socket) {
      const written = socket.write(clientBuffer);
      console.log(`Client written: ${written}`);
      if (written > 0) {
        clientBuffer = clientBuffer.subarray(written);
      }
    },
    data(socket, data) {},
    drain(socket) {
      while (clientBuffer.byteLength > 0) {
        const written = socket.write(clientBuffer);
        clientBuffer = clientBuffer.subarray(written);
        if (written === 0) {
          break;
        }
      }
    },
  },
});
```

**Comment by Ikaleio** [comment]
The forwarding based on the net module provided in the code library above will also have issues when run with Bun.
