### ISSUE TITLE
Expected pretty file path to have only forward slashes

### ISSUE THREAD

**Issue by kodermax** [oven-sh/bun#14843]
### How can we reproduce the crash?

link to reproduce the error https://github.com/kodermax/bun-monorepo

### Relevant log output

Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\user\.bun\bin\bun.exe" "build" "--compile" "--minify-whitespace" "--minify-syntax" "--target" "bun" "--outfile" "server" "./apps/server/src/index.ts"
Features: define tsconfig(4) 
Elapsed: 79ms | User: 0ms | Sys: 0ms
RSS: 122.45MB | Peak: 122.45MB | Commit: 0.19GB | Faults: 30369

panic(thread 8376): Expected pretty file path to have only forward slashes, got 'C:\Temp\my-turborepo\node_modules\@acme\error\dist\index.js'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Projects\jetsite\mott\platform\node_modules\@mott\error\dist\index.js'

- [`fs.zig:1728`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/fs.zig#L1728>): `assertPrettyIsValid`
- [`bundle_v2.zig:9103`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L9103>): `postProcessJSChunk`
- [`bundle_v2.zig:8005`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L8005>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-dp3pZl/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/13897
