### ISSUE TITLE
Error while runing bunx scripts

### ISSUE THREAD

**Issue by TheCukitoDev** [oven-sh/bun#14848]
### What version of Bun is running?

1.1.33

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create a repository with bunx create-t3-app@latest (next v14)
Run `bunx storybook@latest init`

### What is the expected behavior?

To run the installation storybook as npx does

### What do you see instead?

⚙️  esbuild [1/1] Resolving dependencies
Resolved, downloaded and extracted [4]
Saved lockfile
error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1

**Comment by kravetsone** [comment]
getting same errors so many times...
