### ISSUE TITLE
Invalid enum value

### ISSUE THREAD

**Issue by Mixerou** [oven-sh/bun#14844]
### How can we reproduce the crash?

Develop a simple `Nuxt 3` application, and as in problem #14775, I have not done any specific actions leading to this panic.

### Relevant log output

```
Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "node" "C:\Users\[REDACTED]\GitHub\[REDACTED]\[REDACTED]\node_modules\nuxi\bin\nuxi.mjs" "dev" "--host"
Features: Bun.stderr(3) Bun.stdin(10) Bun.stdout(4) bunfig fetch(774) http_server(5) jsc spawn(3) transpiler_cache(108) tsconfig(102) tsconfig_paths(51) workers_spawned(8) workers_terminated(3)  
Builtins: "bun:jsc" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8"  
Elapsed: 23356908ms | User: 309640ms | Sys: 240250ms
RSS: 2.76GB | Peak: 9.27GB | Commit: 18.82GB | Faults: 4341990   

panic(thread 20216): invalid enum value
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

error: script "dev" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [RunAsNodeCommand]

**panic**: invalid enum value

- [`event_loop.zig:1255`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/event_loop.zig#L1255>): `tickQueueWithCount`
- [`event_loop.zig:1275`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/event_loop.zig#L1275>): `tickConcurrent`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-dp3pZl/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`
- [`bindings.cpp:4859`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/bindings.cpp#L4859>): `JSC__VM__holdAPILock`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/shimmer.zig#L197>): `cppFn`

Features: workers\_spawned, workers\_terminated, Bun.stderr, Bun.stdin, Bun.stdout, bunfig, fetch, http\_server, jsc, spawn, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
