### ISSUE TITLE
Build got crash when using workspaces

### ISSUE THREAD

**Issue by fresholia** [oven-sh/bun#14857]
### How can we reproduce the crash?

When I import packages/locales from package a that I use in Monorepo, I get crash.

*Note: `bun run src/index.ts` command works properly, When I build package with `bun build src/index.ts` I get the following crash.*

(Example)
Module a: ./apps/server/
Crash caused package path: ./packages/locales

(packages/locales/index.ts)
```ts
export const translate = (key: string) => {
  return key;
};
```

(apps/server/index.ts)
```ts
import { translate } from '@repo/locales';

console.log(translate('hello'));
```

### Relevant log output
```
Bun v1.1.32 (fe8d0079) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\cleop\.bun\bin\bun.exe" "build" "./src/index.ts" "--outdir" "../../server-build/packages/server" "--watch"
Features: tsconfig(4) 
Elapsed: 18ms | User: 0ms | Sys: 15ms
RSS: 72.90MB | Peak: 72.90MB | Commit: 123.01MB | Faults: 18049

panic(thread 23680): Expected pretty file path to have only forward slashes, got 'D:\GitHub\v-source\node_modules\@repo\locales\index.ts'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.32 ([`fe8d007`](<https://github.com/oven-sh/bun/tree/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e>)) on windows x86_64 [RunCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'E:\Proj\spfx\sample\src\appwithassets\assets\blueprint.jpg'

- [`fs.zig:1728`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/fs.zig#L1728>): `assertPrettyIsValid`
- [`bundle_v2.zig:9103`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bundler/bundle_v2.zig#L9103>): `postProcessJSChunk`
- [`bundle_v2.zig:8005`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/bundler/bundle_v2.zig#L8005>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-EsNl1L/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: Bun.stderr, Bun.stdout, jsc, shell, transpiler\_cache, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/13897
