### ISSUE TITLE
Bun crashing when accessing sqlite

### ISSUE THREAD

**Issue by nperez0111** [oven-sh/bun#14861]
### How can we reproduce the crash?

I run bun within docker on this repo: https://github.com/nperez0111/wedding-invitation

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux aarch64 [RunCommand]

Segmentation fault at address 0x00000000

- [`workaround-missing-symbols.cpp:227`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/workaround-missing-symbols.cpp#L227>): `__wrap_fcntl64`
- [`sqlite3.c:39643`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L39643>): `unixLock`
- [`sqlite3.c:25840`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L25840>): `sqlite3PagerSharedLock`
- [`sqlite3.c:73349`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73349>): `btreeBeginTrans`
- [`sqlite3.c:73839`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73839>): `sqlite3InitOne`
- [`sqlite3.c:141093`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L141093>): `sqlite3LocateTable`
- [`sqlite3.c:121060`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L121060>): `sqlite3Insert`
- [`sqlite3.c:175152`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L175152>): `yy_reduce`

Features: jsc

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/14442
