### ISSUE TITLE
Build exe crash in windows

### ISSUE THREAD

**Issue by lvzhenbo** [oven-sh/bun#14860]
### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Users\29422\Desktop\dcv-decryptor\node_modules\node-widevine\dist\index.js'

- [`fs.zig:1728`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/fs.zig#L1728>): `assertPrettyIsValid`
- [`bundle_v2.zig:9103`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L9103>): `postProcessJSChunk`
- [`bundle_v2.zig:8005`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L8005>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-dp3pZl/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/13897
