### ISSUE TITLE
Bun  not installed my laptop

### ISSUE THREAD

**Issue by Ranjushau** [oven-sh/bun#14886]
### How can we reproduce the crash?

```
PS C:\Users\R A N J U> powershell -c "irm bun.sh/install.ps1|iex"
################################################################################################################ 100.0%
============================================================
Bun v1.1.33 (247456b6) Windows x64 (baseline)
Windows v.win10_fe
Args:
Features: no_avx2 no_avx
Elapsed: 12ms | User: 0ms | Sys: 31ms
RSS: 15.47MB | Peak: 15.48MB | Commit: 25.53MB | Faults: 3893

CPU lacks AVX support. Please consider upgrading to a newer CPU.
panic(thread 1944): Illegal instruction at address 0x7FF7E5CBEF45
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.33/e_1247456bAggggYq03r+Bqntr+B66kr+B6g+q+Bk13q+Bir0q+Buxgq+B40/p+Bsq9p+B2kJA3u//B3rowma

Install Failed - could not verify bun.exe
The command 'C:\Users\R A N J U\.bun\bin\bun.exe --revision' exited with code 3
```

1

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64_baseline [_]

Illegal instruction at address 0x7FF7536EEF45

- [`internal.h:315`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/buildkite-agent/builds/windows-x64-IYaZYF/bun/bun/vendor/mimalloc/include/mimalloc/internal.h#L315>): `_mi_align_up`
- [`arena.c:963`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L963>): `mi_reserve_os_memory_ex`
- [`arena.c:374`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L374>): `mi_arena_reserve`
- [`segment.c:835`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L835>): `mi_segment_os_alloc`
- [`segment.c:1397`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L1397>): `mi_segments_page_alloc`
- [`segment.c:1521`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L1521>): `_mi_segment_page_alloc`
- [`page.c:279`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L279>): `mi_page_fresh_alloc`
- [`page.c:758`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L758>): `mi_page_queue_find_free_ex`
- [`page.c:918`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L918>): `_mi_malloc_generic`
- [`memory_allocator.zig:108`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/memory_allocator.zig#L108>): `alignedAlloc`

Features: no\_avx2, no\_avx

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5883289266/">BUN-5V6</a></strong></sub>

**Comment by 190n** [comment]
What model CPU do you have?

**Comment by nektro** [comment]
you can retrieve this information by running the following command in an administrator command prompt

```
wmic cpu get caption, deviceid, name, numberofcores
```

**Comment by nikeshparajuli** [comment]
Hi, I'm experiencing the same. This is my CPU spec:
![Image](https://github.com/user-attachments/assets/db726df5-aa94-4bef-a1a1-4b0705665339)

**Comment by nikeshparajuli** [comment]
And this is the error during installation
![Image](https://github.com/user-attachments/assets/0c77124f-8780-4317-a241-9363a2513300)

**Comment by 190n** [comment]
@nikeshparajuli Thanks for reporting and including your CPU info. Unfortunately, Bun does not support your CPU at this time (even in the baseline build) as [you do not have the SSE4.2 extension](https://www.techpowerup.com/cpu-specs/athlon-ii-x4-640.c787). We do intend to provide a better error message in these cases than simply crashing; that's tracked in #14745. The error you're seeing is because the install script tries to run `bun.exe` to make sure it works, but Bun crashes with an illegal instruction.

We don't have current plans to lower our CPU requirement. Doing so would increase the complexity of testing Bun, and would draw our team's resources away from adding new features and enhancing stability. However, we may revisit this in the future if there is significant community demand to run Bun on older CPUs.

**Comment by nikeshparajuli** [comment]
Thank you for your prompt response @190n

**Comment by 190n** [comment]
Hey @ranupratapsingh, can you open a separate issue and mention which docker image you are using?
