### ISSUE TITLE
Crash while building a nestjs project on Windows

### ISSUE THREAD

**Issue by ericleib** [oven-sh/bun#14893]
### How can we reproduce the crash?

The build command was:

```
bun build .\src\main.ts --outdir ./out --target bun -e class-transformer/storage -e canvas -e @fastify/static -e @nestjs/microservices -e @nestjs/websockets/socket-module
```

The project is a nestjs application within a monorepo (under <root>/packages/webapp).

### Relevant log output

```
bun build .\src\main.ts --outdir ./out --target bun -e class-transformer/storage -e canvas -e @fastify/static -e @nestjs/microservices -e @nestjs/websockets/socket-module
============================================================
Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\ericl\.bun\bin\bun.exe" "build" ".\src\main.ts" "--outdir" "./out" "--target" "bun" "-e" "class-transformer/storage" "-e" "canvas" "-e" "@fastify/static" "-e" "@nestjs/microservices" "-e" "@nestjs/websockets/socket-module"
Features: external tsconfig(30) tsconfig_paths(2) 
Elapsed: 618ms | User: 250ms | Sys: 93ms
RSS: 0.82GB | Peak: 0.82GB | Commit: 1.05GB | Faults: 210781

panic(thread 33720): Expected pretty file path to have only forward slashes, got 'C:\dev\squadra\node_modules\@ragtime\types\dist\models\index.js'
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'D:\@touhouclouddb\node_modules\@touhouclouddb\utils\src\index.ts'

- [`fs.zig:1728`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/fs.zig#L1728>): `assertPrettyIsValid`
- [`bundle_v2.zig:9103`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L9103>): `postProcessJSChunk`
- [`bundle_v2.zig:8005`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L8005>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-dp3pZl/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, dotenv, tsconfig, tsconfig\_paths, tsconfig\_paths

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/13897
