### ISSUE TITLE
Install Failed - could not verify bun.exe

### ISSUE THREAD

**Issue by OfficialRushO** [oven-sh/bun#14902]
### How can we reproduce the crash?

I just ran `powershell -c "irm bun.sh/install.ps1 | iex"` in the powershell.
After the downloading process, this error/crash happened.

### Relevant log output

```
Bun v1.1.33 (247456b6) Windows x64 (baseline)
Windows v.win10_fe
Args:
Features: no_avx2 no_avx
Elapsed: 3ms | User: 15ms | Sys: 15ms
RSS: 15.98MB | Peak: 15.98MB | Commit: 25.56MB | Faults: 4046

CPU lacks AVX support. Please consider upgrading to a newer CPU.
panic(thread 7732): Illegal instruction at address 0x7FF698C9EF45
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.33/e_1247456bAggggYq03r+Bqntr+B66kr+B6g+q+Bk13q+Bir0q+Buxgq+B40/p+Bsq9p+B2kJA3s//B3ro4mnD

Install Failed - could not verify bun.exe
The command 'C:\Users\RushO\.bun\bin\bun.exe --revision' exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64_baseline [_]

Illegal instruction at address 0x7FF7536EEF45

- [`internal.h:315`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/buildkite-agent/builds/windows-x64-IYaZYF/bun/bun/vendor/mimalloc/include/mimalloc/internal.h#L315>): `_mi_align_up`
- [`arena.c:963`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L963>): `mi_reserve_os_memory_ex`
- [`arena.c:374`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L374>): `mi_arena_reserve`
- [`segment.c:835`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L835>): `mi_segment_os_alloc`
- [`segment.c:1397`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L1397>): `mi_segments_page_alloc`
- [`segment.c:1521`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L1521>): `_mi_segment_page_alloc`
- [`page.c:279`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L279>): `mi_page_fresh_alloc`
- [`page.c:758`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L758>): `mi_page_queue_find_free_ex`
- [`page.c:918`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L918>): `_mi_malloc_generic`
- [`memory_allocator.zig:108`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/memory_allocator.zig#L108>): `alignedAlloc`

Features: no\_avx2, no\_avx

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5883289266/">BUN-5V6</a></strong></sub>

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/14886

**Comment by abdallaoui-mechanic** [comment]
install failed - could not verify bun.exe
