### ISSUE TITLE
bunx shadcn-svelte@next init

### ISSUE THREAD

**Issue by suryakencana007** [oven-sh/bun#14906]
### How can we reproduce the crash?

bun version v1.1.33

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by nektro** [comment]
likely windows specific, does not reproduce on macos
