### ISSUE TITLE
Zig fork doesn't work on macOS Ventura

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#1490]
See: https://github.com/oven-sh/bun/issues/1489

Zig 0.10.0 supports Ventura since late October.

https://github.com/ziglang/zig/pull/13299

See also: 

- https://github.com/ziglang/zig/issues/10478
- https://github.com/ziglang/zig/pull/12080

**Comment by birkskyum** [comment]
this is obsolete now. zig was recently updated https://github.com/oven-sh/bun/pull/4233
