### ISSUE TITLE
Bun Crashed

### ISSUE THREAD

**Issue by roulljdh** [oven-sh/bun#14903]
### How can we reproduce the crash?

I am using the built-in SQLite API. I encountered this when I'm creating a Docker container based off Alpine (oven/bun:1.1.33-alpine). No issues when I used the vanilla Debian image (oven/bun:1.1.33-debian).

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux aarch64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`workaround-missing-symbols.cpp:227`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/workaround-missing-symbols.cpp#L227>): `__wrap_fcntl64`
- [`sqlite3.c:39643`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L39643>): `unixLock`
- [`sqlite3.c:25840`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L25840>): `sqlite3PagerSharedLock`
- [`sqlite3.c:73349`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73349>): `btreeBeginTrans`
- [`sqlite3.c:73839`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73839>): `sqlite3InitOne`
- [`sqlite3.c:141093`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L141093>): `sqlite3Init`
- [`sqlite3.c:141119`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L141119>): `sqlite3StartTable`
- [`sqlite3.c:174523`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L174523>): `yy_reduce`

Features: Bun.stdin, jsc

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/14442
