### ISSUE TITLE
Bun crashed after reinstallation.

### ISSUE THREAD

**Issue by frank-mitchell-com** [oven-sh/bun#14904]
### How can we reproduce the crash?

1. Remove the old instance of Bun: "rm -r ~/.bun"
2. Install a new instance: "curl -fsSL https://bun.sh/install | bash"
3. Run bun with no arguments: "~/.bun/bin/bun"
4. Receive the following message:

```
============================================================
Bun v1.1.33 (247456b6) Linux x64 (baseline)
Linux Kernel v6.8.0 | glibc v2.39
Args: 
Features: no_avx2 no_avx 
Elapsed: 1ms | User: 1ms | Sys: 3ms
RSS: 0B  | Peak: 6.42MB | Commit: 0B  | Faults: 0

CPU lacks AVX support. Please consider upgrading to a newer CPU.
panic: Illegal instruction at address 0x3D07178
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux x86_64_baseline [_]

Illegal instruction at address 0x03D07178

- `??`
- [`arena.c:962`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L962>): `mi_reserve_os_memory_ex`
- [`arena.c:374`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/arena.c#L374>): `mi_segment_alloc`
- [`segment.c:1378`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L1378>): `mi_segments_page_alloc`
- [`segment.c:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/segment.c#L0>): `mi_page_fresh_alloc`
- [`page.c:302`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L302>): `mi_find_page`
- [`page.c:917`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/page.c#L917>): `_mi_malloc_generic`
- [`memory_allocator.zig:45`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/memory_allocator.zig#L45>): `main`

Features: no\_avx2, no\_avx

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6012534389/">BUN-7A8</a></strong></sub>

**Comment by nektro** [comment]
Duplicate https://github.com/oven-sh/bun/issues/14886
