### ISSUE TITLE
bake: assertion failure with invalid cache key

### ISSUE THREAD

**Issue by GGAlanSmithee** [oven-sh/bun#14913]
### What version of Bun is running?

1.1.34 (debug build of latest main branch)

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

This is an issue that only occurs when running a debug, and under certain circumstances.

Reproduction

1. create a new minimal bun bake project
2. add a folder; `pages`
3. create a file; `pages/route.tsx`, with a proper default exported component
4. add above file in bun bake's index file `routes` (as below)
5. run the application `bun-debug run index.tsx`
6. add a new folder in the `pages` directory

### What is the expected behavior?

nothing happens, app continues to run as before

### What do you see instead?

app crashes with error:

```sh
panic: Internal Assertion Failure: Invalid cache key "/bun-bake/pages/" See Resolver.assertValidCacheKey for details.
```

### Additional information

sample config:

```tsx
wipDevServerExpectHugeBreakingChanges({
  // routes must be statically known so production
  // builds can prepare all required assets.
  routes: [
    { pattern: '/', entrypoint: './pages/route.tsx' },
  ],
  // for framework authors, attach your framework
  // via the interface described in `bake.d.ts`
  framework: 'react',
});
```

ping @paperdave

**Comment by paperdave** [comment]
in DevServer.onFileUpdate i have applied a possible fix, adding `bun.strings.withoutTrailingSlash`. will visit this after #11430 is resolved since it provides a better function.

```
// TODO: correctly solve https://github.com/oven-sh/bun/issues/14913
_ = dev.server_bundler.resolver.bustDirCache(bun.strings.withoutTrailingSlash(file_path));
```
