### ISSUE TITLE
Crash when build app

### ISSUE THREAD

**Issue by dario61081** [oven-sh/bun#14929]
### How can we reproduce the crash?

launch build: bunx --bun vite build

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on windows x86_64 [RunAsNodeCommand]

**panic**: attempt to unwrap error: OutOfMemory

- [`sourcemap.zig:518`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/sourcemap/sourcemap.zig#L518>): `parse`
- [`javascript.zig:175`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L175>): `toMapping`
- [`javascript.zig:393`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L393>): `resolveMapping`
- [`javascript.zig:3198`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L3198>): `remapStackFramePositions`
- [`ZigGlobalObject.cpp:531`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/bindings/ZigGlobalObject.cpp#L531>): `Bun::formatStackTrace`
- [`utility:762`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/utility#L762>): `std::exchange`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/C:/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/windows-x64-build-cpp/webkit-4a2db3254a9535949a5d5380eb58cf0f77c8e15a/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...),WTF::String,JSC::VM &,WTF::Vector<JSC::StackFrame,0,WTF::CrashOnOverflow,16,WTF::FastMalloc> &,unsigned int &,unsigned int &,WTF::String &,JSC::JSObject *>::call`
- [`utility:753`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/include/utility#L753>): `std::exchange`
- [`RefPtr.h:71`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/C:/a/WebKit/WebKit/WebKitBuild/WTF/Headers/wtf/RefPtr.h#L71>): `WTF::RefPtr<WTF::StringImpl,WTF::RawPtrTraits<WTF::StringImpl>,WTF::DefaultRefDerefTraits<WTF::StringImpl> >::operator!`
- [`JSGlobalObject.h:1127`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSGlobalObject.h#L1127>): `JSC::JSGlobalObject::vm`

Features: workers\_spawned, jsc, Bun.stderr, Bun.stdin, Bun.stdout, abort\_signal, dotenv, fetch, http\_server, spawn, transpiler\_cache, tsconfig\_paths, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5898350185/">BUN-5ZH</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Tracking this in https://github.com/oven-sh/bun/issues/15964
