### ISSUE TITLE
stopping a tcp socket server from `Bun.listen()` keeps bun open for an extra second.

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#1492]
### What version of Bun is running?

0.2.3

### What platform is your computer?

Linux 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 unknown

### What steps can reproduce the bug?

```ts
const server = Bun.listen({
  port: 1144,
  hostname: '127.0.0.1',
  data: undefined,
  socket: { data() {} } as any,
});
server.stop();
console.log('hello, world')
```

### How often does it reproduce? Is there a required condition?

it happens every time unless the port is in use or another error.

### What is the expected behavior?

instantly closes

### What do you see instead?

the console log is shown instantly, but bun waits a second before fully closing

### Additional information

i dont know how sockets work, so i'm not sure if this is something that can be fixed.

**Comment by Jarred-Sumner** [comment]
Fixed awhile ago
