### ISSUE TITLE
`write` should create directories if it does not exist

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1493]
Using the example below, if `./path/to` does not exist, it should be auto-created before writing the file.

```js
Bun.write("./path/to/file.txt", "hello");
```

It also might make sense to have an option to disable this.

```js
Bun.write("./path/to/file.txt", "hello", { createDirs: false });
```

**Comment by davood-n** [comment]
sounds like a good idea. I'm all for it

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/7535

**Comment by keisanng** [comment]
There's an issue with the implementation (#8396) me and others are experiencing (even if setting `createDirs` to `true` manually.)
