### ISSUE TITLE
Panic when passing an existing/default import condition to --conditions

### ISSUE THREAD

**Issue by Shenlok** [oven-sh/bun#14979]
### How can we reproduce the crash?

Running `bun --conditions=bun index.ts` caused the attached panic. Seems to happen with other conditions too that I'd expect to already be present and thus not needed to be passed in via this CLI param (e.g `--conditions=import`, `--conditions=default`) 

Making up a custom condition (`--conditions=bun2`) does not panic.

### Relevant log output

bun --conditions=default index.ts
```
============================================================
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\shenl\.bun\bin\bun.exe" "--conditions=default" "index.ts"
Features: jsc 
Elapsed: 8ms | User: 0ms | Sys: 0ms
RSS: 37.04MB | Peak: 37.04MB | Commit: 79.36MB | Faults: 9246

panic(main thread): reached unreachable code
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

**panic**: reached unreachable code

- [`array_hash_map.zig:894`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/array_hash_map.zig#L894>): `ensureUnusedCapacityContext`
- [`options.zig:1724`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/options.zig#L1724>): `fromApi`
- [`javascript.zig:1747`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/javascript.zig#L1747>): `init`
- [`bun_js.zig:192`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun_js.zig#L192>): `boot`
- [`cli.zig:2270`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/cli.zig#L2270>): `maybeOpenWithBunJS`
- [`cli.zig:2137`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/cli.zig#L2137>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/src/startup/exe_common.inl#L78>): `invoke_main`

Features: jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6040995038/">BUN-7XW</a></strong></sub>

**Comment by RiskyMH** [comment]
Fixed in [`v1.1.41`](https://bun.sh/blog/bun-v1.1.41#fixed-conditions-default-in-bun-build) by #15861
