### ISSUE TITLE
Bun install infinite loop

### ISSUE THREAD

**Issue by SamiFraca** [oven-sh/bun#14984]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Bun install / bun i 

### What is the expected behavior?

Packages installed correctly

### What do you see instead?

Infinite loop that consist of multiple<

$ bun install
[0.02ms] ".env.local"
bun install v1.1.34 (5e5e7c60)

### Additional information

Here is the repo im having problems with:
https://github.com/SamiFraca/DCP

**Comment by ghiscoding** [comment]
I'm guessing it's because you added the `"install":"bun install"` npm script, so when you start the bun install, it will afterward run the npm script install and you're falling into an infinite loop. Just remove the `install` npm script should be enough (I made that mistake in Node as well couple times)

**Comment by dylan-conway** [comment]
> I'm guessing it's because you added the `"install":"bun install"` npm script, so when you start the bun install, once completed it will afterward run the npm script install and you're falling into an infinite loop. Just remove the `install` npm script should be enough (I made that mistake in Node as well couple times)

This is exactly what's happening, the `install` lifecycle script will run `bun install` after the install finishes, causing an infinite loop.

Closing as not planned. See more about lifecycle script here https://bun.sh/docs/install/lifecycle. We've thought about detecting this, but it breaks `bun install --cwd ./another/pkg` in postinstalls.

**Comment by SamiFraca** [comment]
Thank you so much! I thought it was something related with the new version because i upgraded and then this happened. But i guess it was my bad
