### ISSUE TITLE
Bun crashing on build with windows

### ISSUE THREAD

**Issue by darklight9811** [oven-sh/bun#14993]
### How can we reproduce the crash?

repo specifications:
- monorepo
- tsconfig path alias
- only uses bun
- windows
- build command: `bun build src/index --minify --target=bun --outdir=../../dist`

### Relevant log output

Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\rafae\.bun\bin\bun.exe" "build" "src/index" "--target=bun"
Features: tsconfig(5) tsconfig_paths(3)
Elapsed: 207ms | User: 343ms | Sys: 218ms
RSS: 0.17GB | Peak: 0.17GB | Commit: 0.24GB | Faults: 43256

panic(thread 7448): Expected pretty file path to have only forward slashes, got 'C:\projects\javascript\muse9\knosis\node_modules\@repo\schemas\src\schemas\pagination.ts'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Users\foxxorcat\Documents\ipfs\helia-cli\node_modules\.pnpm\@multiformats+dns@1.0.6\node_modules\hashlru\index.js'

- [`fs.zig:1732`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/fs.zig#L1732>): `assertPrettyIsValid`
- [`bundle_v2.zig:9284`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L9284>): `postProcessJSChunk`
- [`bundle_v2.zig:8174`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L8174>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/13897
