### ISSUE TITLE
Segfault when running bunx sv create.

### ISSUE THREAD

**Issue by rosaldanha** [oven-sh/bun#14999]
### How can we reproduce the crash?

This segfault only happen if I select the flowing combination in the "bunx sv create test2"  command:
drizzle with PostgreSQL, if  i choose any other drizzle driver (mysql, neon, sqlite..) works fine. 
If i don't install any drizzle option and add the drizzle + PostgreSQL  to the project later, it works fine too. 

### Relevant log output

```
PS C:\bun> bunx sv create teste2
┌  Welcome to the Svelte CLI! (v0.6.1)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  drizzle
│
◇  Which database would you like to use?
│  PostgreSQL
│
◇  Which PostgreSQL client would you like to use?
│  Postgres.JS
│
◇  Do you want to run the database locally with docker-compose?
│  Yes
│
◇  Which package manager do you want to install dependencies with?
│  bun
│
◆  Successfully setup add-ons
============================================================
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "C:\Users\saldanha\AppData\Local\Temp\bunx-3698819160-sv@latest\node_modules\sv\dist\bin.js" "create" "teste2"
Features: Bun.stdin(2) Bun.stdout jsc spawn transpiler_cache
Builtins: "bun:main" "node:buffer" "node:child_process" "node:events" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tty" "node:url" "node:util/types" "node:zlib"
Elapsed: 12609ms | User: 234ms | Sys: 31ms
RSS: 0.17GB | Peak: 0.19GB | Commit: 0.18GB | Faults: 55517

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/wa15e5e7c6AsggkgiB___8o00jC__s3tnkC___A2AK
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/14926
