### ISSUE TITLE
**panic**: Expected pretty file path to have only forward slashes

### ISSUE THREAD

**Issue by WeedTest** [oven-sh/bun#15007]
### How can we reproduce the crash?

# Run bun build command
bun build .\index.ts --compile --outfile=build\$name

### Relevant log output

```
Bun v1.1.34 (fe8d0079) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "~\.bun\bin\bun.exe" "build" ".\index.ts" "--compile" "--outfile=build"
Features: define tsconfig(23) tsconfig_paths(6)
Elapsed: 101ms | User: 0ms | Sys: 15ms
RSS: 0.19GB | Peak: 0.19GB | Commit: 0.31GB | Faults: 47249

panic(thread 11792): Expected pretty file path to have only forward slashes, got '~\OneDrive\Desktop\Workspace\octopush\node_modules\.pnpm\@inquirer+expand@2.3.0\node_modules\yoctocolors-cjs\index.js'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'D:\@touhouclouddb\node_modules\@touhouclouddb\utils\src\index.ts'

- [`fs.zig:1732`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/fs.zig#L1732>): `assertPrettyIsValid`
- [`bundle_v2.zig:9284`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L9284>): `postProcessJSChunk`
- [`bundle_v2.zig:8174`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L8174>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: bunfig, define, dotenv, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/13897
