### ISSUE TITLE
Build plugin feat: add `entrypoint` field to args in `onLoad` callback

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#15003]
### What is the problem this feature would solve?

Currently, in Bun build plugins, tracking which files belong to which entry points during the build process is difficult. This limitation complicates dependency analysis, as there is no straightforward way to determine the original `entrypoint` context for each file within the `onLoad` callback. 

### What is the feature you are proposing to solve the problem?

I propose adding an `entrypoint` field to the args object within the `onLoad` callback. This field would contain the path of the original entrypoint associated with each file being processed. By having this reference available in `onLoad`, plugin developers can easily associate files with their respective entrypoints, making it simpler to build accurate dependency trees and perform entrypoint-specific analyses.

```js
build.onLoad({ filter: /.*/ }, async ({ path, loader, entrypoint, namespace }) => {
   console.log({ entrypoint })
   // ...
});
```

### What alternatives have you considered?

One alternative is to manually track entrypoints in `onResolve` and then try to match each loaded file back to an entrypoint based on its path. However, this approach becomes complicated and error-prone as the complexity of the project increases, especially with dynamic imports or multiple layers of dependencies. Another option would be to use custom properties or metadata on each file, but this requires additional bookkeeping and does not integrate cleanly with the build process. Adding the `entrypoint` field directly in `onLoad `would provide a more robust and native solution within esbuild’s existing framework.

**Comment by aralroca** [comment]
I wonder if currently, file execution is deterministic. If it could be solved by detecting the entrypoint in the `onResolve` and using it in the `onLoad`... Can we trust this? 🤔

```ts
function loadPlugin(entrypoints: string[]) {
  let entrypoint = '';
  const analysisPerEntrypoint: Record<string, string[]> = {};
  const entrypointsSet = new Set(entrypoints);
  const plugin: BunPlugin = {
      name: 'some-plugin',
      setup(build) {
        build.onResolve({ filter: /.*/ }, async ({ path, namespace, importer }) => {
          if(entrypointsSet.has(importer)) entrypoint = importer;
          return { path, namespace }
        });
        build.onLoad({ filter: /.*/  },
          async ({ path, loader, namespace }) => {
            let code = await Bun.file(path).text();
    
            // ... some stuff
            if(!analysisPerEntrypoint[entrypoint]) analysisPerEntrypoint[entrypoint] = []
            analysisPerEntrypoint[entrypoint].push(/* something */)
          
            return {
              contents: code,
              loader,
            };
          },
        );
    }
  }

  return { plugin, getAnalysisPerEntrypoint: () => analysisPerEntrypoint }
}
```

**Comment by aralroca** [comment]
@paperdave Is there any current workaround to solve this meanwhile this is not implemented? thanks

**Comment by BjornTheProgrammer** [comment]
This seems pretty similar to what I needed as well. You could probably just adapt the code in my [pull request](https://github.com/oven-sh/bun/issues/15033) to add this argument to the bundler.

**Comment by BjornTheProgrammer** [comment]
I ended up writing a custom resolver plugin to be able to get the original file paths. You can view that code [here](https://github.com/BjornTheProgrammer/bun-plugin-html/blob/d621af22e8b4065f4be097cf0cc4c7f3c5984cdf/src/index.ts#L321). Has a few problems, mainly being that you have to call Bun.build from within your plugin. Which prevents there from being output information.

**Comment by aralroca** [comment]
@BjornTheProgrammer your PR is just that, we can close this PR as a duplicated of your ticket! Great job!
