### ISSUE TITLE
segfault with `Bun.spawnSync` with stdout: ArrayBufferView 

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#1500]
### What version of Bun is running?

0.2.2 (also on main branch as of creating the issue)

### What platform is your computer?

`Linux 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 x86_64`

### What steps can reproduce the bug?

Types say that `SpawnOptions.Readable` can be an `ArrayBufferView`

`echo "hello world" > test.txt`

```ts
const view: ArrayBufferView = new Uint8Array(100);
const proc = Bun.spawnSync({
  cmd: ["cat"],
  stdin: Bun.file("test.txt"),
  stdout: view,
  stderr: "inherit",
});
```

### How often does it reproduce? Is there a required condition?

every time.

### What is the expected behavior?

honestly, i'm not sure what i'm expecting to happen, maybe write the contents to the buffer. in the async spawn case which doesnt crash, **nothing is written to the buffer**, that might be another bug.

### What do you see instead?

Segfault at 0x8563000000000000

**Comment by Electroid** [comment]
@robobun 

```js
import { writeFileSync } from "node:fs";
import { file } from "bun";

writeFileSync("./test.txt", "hello world", "utf-8");
const stdout = new Uint8Array(100);
const process = Bun.spawnSync({
  cmd: ["cat"],
  stdin: file("test.txt"),
  stdout,
  stderr: "inherit",
});
console.log(stdout);
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx

```
<details>
  <summary>Code</summary>
  
```tsx
import { writeFileSync } from "node:fs";
import { file } from "bun";

writeFileSync("./test.txt", "hello world", "utf-8");
const stdout = new Uint8Array(100);
const process = Bun.spawnSync({
  cmd: ["cat"],
  stdin: file("test.txt"),
  stdout,
  stderr: "inherit",
});
console.log(stdout);
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
