### ISSUE TITLE
Bunx command fails on arm64 windows

### ISSUE THREAD

**Issue by Tiktack** [oven-sh/bun#15004]
### How can we reproduce the crash?

Running this command gives an error 
```
bunx solidui-cli@latest init
```

### Relevant log output

```
Bun v1.1.33 (247456b6) Windows x64 (baseline)
Windows v.win10_fe
CPU: sse42
Args: "bun" "C:\Users\XXXX\AppData\Local\Temp\bunx-1441488167-solidui-cli@latest\node_modules\solidui-cli\dist\index.js" "init"
Features: Bun.stdin(2) Bun.stdout jsc no_avx2 no_avx transpiler_cache(12) tsconfig(3) tsconfig_paths
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:timers/promises" "node:tty" "node:url" "node:util" "node:util/types" "node:v8"
Elapsed: 26576ms | User: 1093ms | Sys: 312ms
RSS: 0.31GB | Peak: 0.31GB | Commit: 0.38GB | Faults: 84009

CPU lacks AVX support. Please consider upgrading to a newer CPU.
panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64_baseline [AutoCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- [`CodeBlock.h:292`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/a/WebKit/WebKit/Source/JavaScriptCore/bytecode/CodeBlock.h#L292>): `JSC::CodeBlock::bytecodeOffset`
- [`CommonSlowPaths.cpp:924`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/CommonSlowPaths.cpp#L924>): `slow_path_enter`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, jsc, no\_avx2, no\_avx, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5697723847/">BUN-40F</a></strong></sub>

**Comment by nektro** [comment]
duplicate https://github.com/oven-sh/bun/issues/12618
