### ISSUE TITLE
Fetch body doesn't work properly with fs.ReadStream

### ISSUE THREAD

**Issue by benardayim** [oven-sh/bun#15022]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64

### What steps can reproduce the bug?

Create a request with fetch and use fs.ReadStream (from fs.createReadStream()) as body.

Save this code to a file then run it with both bun and node.

```javascript
import http from "node:http";
import fs from "node:fs";

const TEST_FILE_PATH = "test.txt";

let server = http.createServer((req, res) => {
    res.writeHead(200);

    let data = "";
    req.on("data", e => data += e);
    req.on("end", () => {
        res.end("body is " + data.length + " bytes.");
    })
});

server.listen(3131, () => console.log("Listening"));

let response = await fetch("http://localhost:3131/", {
    method: "POST",
    body: fs.createReadStream(TEST_FILE_PATH)
});
let body = await response.text();

console.log(body);
```

### What is the expected behavior?

It should use the data from the stream as body but it doesn't.

### What do you see instead?

It sends 0 bytes as body.

**Comment by guest271314** [comment]
See [Streaming requests with the fetch API ](https://developer.chrome.com/docs/capabilities/web-apis/fetch-streaming-requests) and how the current implementation of Bun's `fetch()` does not handle HTTP/2 full-duplex streaming https://github.com/oven-sh/bun/issues/7206.
