### ISSUE TITLE
`--preload` with `new Worker`

### ISSUE THREAD

**Issue by SlexAxton** [oven-sh/bun#15044]
### What version of Bun is running?

1.1.33+247456b67

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```bash
bun --preload preload.ts ./app.ts
```

```tsx
# preload.ts

globalThis.EXPANDO = 'EXPANDO';
```

```tsx
# app.ts
console.log('From app', globalThis.EXPANDO);

const worker = new Worker('./worker.ts');
```

```tsx
# worker.ts
console.log('From worker', globalThis.EXPANDO);
```

### What is the expected behavior?

```
From app EXPANDO
From worker EXPANDO
```

### What do you see instead?

```
From app EXPANDO
From worker undefined
```

### Additional information

I'm not super sure how it should work for sure! But! For something like opentelemetry, it means that all of my telemetry is silently ignored inside of my workers.

I'd hope there's *some* way to make it to where I could reliably load the `telemetry.ts` file for everything.

It's possible there's a better way than `--preload` to add the telemetry file, but that's how @Jarred-Sumner is suggesting it in this issue: https://github.com/oven-sh/bun/issues/3775#issuecomment-1892843091

**Comment by SlexAxton** [comment]
It's possible workers should have their own `--worker-preload` or simply take the preload argument as an option on `new Worker(path, {preload: './file/from/root.ts'})`

**Comment by Jarred-Sumner** [comment]
--worker-preload sounds good + adding a `preload` argument

**Comment by truongan07** [comment]
i may transfer data to worker by globalThis variable without postMessage method ?

**Comment by Jarred-Sumner** [comment]
> i may transfer data to worker by globalThis variable without postMessage method ?

i wish

**Comment by SlexAxton** [comment]
(It’s a different `globalThis` instance is why)
