### ISSUE TITLE
Using Bun compile for a linux binary crashes.

### ISSUE THREAD

**Issue by axodouble** [oven-sh/bun#15052]
### How can we reproduce the crash?

`index.ts`
```ts
console.log("Hello via Bun!");
```

`package.json`
```ts
{
  "name": "onebeer",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

Then compiling it with `bun build --compile --target=bun-linux-x64 . --outfile myapp --minify --sourcemap --bytecode`, running it in WSL Ubuntu and it crashes.

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on linux x86_64 [_]

Segmentation fault at address 0x53BAC000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::decodeCodeBlockImpl`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::Interpreter::executeProgram`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::evaluate`
- [`CommonJSModuleRecord.cpp:155`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/CommonJSModuleRecord.cpp#L155>): `Bun::evaluateCommonJSModuleOnce`
- [`CommonJSModuleRecord.cpp:1171`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/CommonJSModuleRecord.cpp#L1171>): `WTF::Detail::CallableWrapper<Bun::createCommonJSModule(...)::$_0, void, JSC::JSGlobalObject*, JSC::Identifier, WTF::Vector<JSC::Identifier, 4ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, JSC::MarkedVector<JSC::JSValue, 8ul, WTF::RecordOverflow>&>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::moduleLoaderParseModule`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_op_call`

Features: jsc, standalone\_executable, tsconfig

**Comment by Axodouble** [comment]
After testing some more, it seems that it is the `--bytecode` flag that will cause bun to crash.

**Comment by Jarred-Sumner** [comment]
Can you provide the code that reproduces this issue? Unfortunately, this is not actionable without a reproduction.

**Comment by guest271314** [comment]
Did you try to run the executable when either the original source files were deleted or on a different machine?

**Comment by Axodouble** [comment]
> Can you provide the code that reproduces this issue? Unfortunately, this is not actionable without a reproduction.

It is in my main reply:
`index.ts`
```ts
console.log("Hello via Bun!");
```
`package.json`
```ts
{
  "name": "onebeer",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

And the bundling it into an executable with --bytecode, same machine in WSL Ubuntu.

**Comment by guest271314** [comment]
Doesn't crash on Linux 5.15.0-43-generic x86_64 x86_64.

**Comment by Axodouble** [comment]
Can't repro again most recent version with Bun & Ubuntu WSL, will report if it happens again or if I can succesfully repro.
