### ISSUE TITLE
Node.js signal handling

### ISSUE THREAD

**Issue by bwasti** [oven-sh/bun#1505]
### What is the problem this feature would solve?

This would allow users to install signal handlers in a syntax that is well established.  It may improve compatibility with extent node.js applications.

### What is the feature you are proposing to solve the problem?

Currently `process.on` doesn't do anything

Ideally things like `process.on('SIGINT', ()=>{})` would work

**Comment by Electroid** [comment]
Yes, we'll definitely implement this. Thanks for opening an issue.

**Comment by Electroid** [comment]
Tracking this issue here: #429
