### ISSUE TITLE
Remove inaccurate claims on the website

### ISSUE THREAD

**Issue by shinebayar-g** [oven-sh/bun#15075]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Bun install is not faster than light speed. It's physically impossible to download packages in 0 seconds. Other package managers aren't even that slow.

I love Bun. But this just looks bad tbh.

![Image](https://github.com/user-attachments/assets/8f72f2ea-9fdd-4c80-b839-e0d8e47f07bb)

### Where did you find it?

https://bun.sh/

**Comment by Jarred-Sumner** [comment]
The [View benchmark](https://github.com/oven-sh/bun/tree/main/bench/install) link in the screenshot shows how to reproduce the benchmark. It does not say 0 seconds, it says 0.36s.

You are welcome to reproduce the benchmark yourself and verify the claims we make about Bun's performance.

**Comment by shinebayar-g** [comment]
You were right. It's using the cache, I should've seen the notes.
