### ISSUE TITLE
Add a new template starter to bun create command: bun create tanstack-start

### ISSUE THREAD

**Issue by ali-abdelqawy** [oven-sh/bun#15089]
### What is the problem this feature would solve?

Tanstack Start is a full-stack React framework powered by TanStack Router. The TanStack ecosystem has been gaining much traction lately in the Javascript ecosystem, so it would be great to add its ecosystem to the Bun guides section.

### What is the feature you are proposing to solve the problem?

Consider adding a guide to it in the Bun ecosystem section when the stable version of it is released.

**Comment by nektro** [comment]
`bun create foo` is a shorthand for running `bun x create-foo`

so, `bun create tanstack-start` is possible but would rely on https://tanstack.com having control of https://www.npmjs.com/package/create-tanstack-start
