### ISSUE TITLE
Allow `bun wiptest` to run specific file

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1508]
If you attempt to run `bun wiptest index.js`, and that file has tests, you'll see the following and get confused:

```
 0 pass
 0 fail
 Ran 0 tests across 0 files [112.00ms]
```

That's because, by default, it is filtering out files that contain `.test.` in its path.

To make this better, if `bun wiptest` is given a specific file, it should ignore those rules and run it anyway.

**Comment by paperclover** [comment]
i did this
