### ISSUE TITLE
Fallback loader not returning path

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#1509]
### What version of Bun is running?

0.2.3 (canary as of 2022-11-14)

### What platform is your computer?

Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

Attempting to import a markdown file doesn't return a file path as expected.

```md test.md
# Hello there
```

```ts markdown.ts
// all three fail
import data from './readme.md';
const data = await import('./readme.md');
const data = require('./readme.md');

console.log(data);
```

```bash
$ bun run markdown.ts
```

It seems to be attempting to use the JS lexer here. 

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Return a file path for the file (equivalent to `require.resolve`.

```ts
import data from './readme.md';
// => /path/to/readme.md
```

### What do you see instead?

```bash
$ bun run markdown.ts
error: Syntax Error!!
# Hello there
^
/Users/colinmcd94/Documents/bun/fun/readme.md:1:1 0
```

**Comment by alpharder** [comment]
+1, same for `.svg` files.

This could probably be caused by https://github.com/oven-sh/bun/blob/main/src/bundler.zig#L1124

**Comment by snoglobe** [comment]
does not repro (tested with 1.1.39-debug+503154c1b)
