### ISSUE TITLE
Bun Crash After several time

### ISSUE THREAD

**Issue by digitalinaja** [oven-sh/bun#15092]
### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x29DFF4993C8

- [`core.c:173`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/win/core.c#L173>): `uv__wake_all_loops`
- [`detect-wakeup.c:41`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/win/detect-wakeup.c#L41>): `uv__system_resume_callback`

Features: workers\_spawned, workers\_terminated, Bun.stderr, Bun.stdin, Bun.stdout, extracted\_packages, fetch, http\_server, jsc, spawn, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5679205923/">BUN-3NV</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Tracking this in https://github.com/oven-sh/bun/issues/15964

note the `workers_spawned`
