### ISSUE TITLE
Bun keep install devDependencies on project

### ISSUE THREAD

**Issue by indrazm** [oven-sh/bun#15107]
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I am currently build an npm package with bun.
However when i do install. It will install `extraneous` dependencies.

if i do `bun i` it will install me all dependencies, even the devDependencies.
But if i do `npm i` it will install me only dependencies, NOT devDependencies.

Here is my package.json.

```json
{
    "name": "litojs",
    "version": "0.0.1",
    "main": "src/index.ts",
    "type": "module",
    "exports": {
        ".": "./src/index.ts"
    },
    "scripts": {
        "lint": "bunx eslint ./src"
    },
    "devDependencies": {
        "@types/bun": "latest",
        "@eslint/js": "^9.14.0",
        "@types/eslint__js": "^8.42.3",
        "eslint": "^9.14.0",
        "eslint-plugin-simple-import-sort": "^12.1.1",
        "typescript-eslint": "^8.13.0"
    },
    "peerDependencies": {
        "typescript": "^5.6.3"
    },
    "dependencies": {
        "chalk": "^5.3.0"
    }
}
```

### What is the expected behavior?

The expected behaviour is only Install Dependencies, without devDependencies.

### What do you see instead?

This is when i do install using `bun`.
![Image](https://github.com/user-attachments/assets/209dc128-9551-4706-838b-b57633c90745)

This is when i do install using `npm`.
![Image](https://github.com/user-attachments/assets/b7278b35-c023-4fe5-a569-7b5d4fda857c)

**Comment by dylan-conway** [comment]
Do you have `omit=dev` in a `.npmrc` file? I believe this is happening because bun isn't reading the `omit` config setting

**Comment by indrazm** [comment]
Hey @dylan-conway yes. it's there. But still installing the devDependencies.
Here is what i have did : 

```bash
npm ci ✅ 
npm i ✅ 

bun i ❌ 
bun i --production ❌ 
bun i --omit=dev ❌ 
```

✅ installing only dependencies
❌ include the devDependencies

Current way to fix this at the moment is : `npm prune`
