### ISSUE TITLE
child_process.spawnSync does not provide signal

### ISSUE THREAD

**Issue by 190n** [oven-sh/bun#15111]
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

Create a simple executable that exits with SIGTRAP:

```zig
// trap.zig
pub fn main() void {
    @trap();
}
```
```sh
$ zig build-exe trap.zig
$ ./trap
zsh: trace trap  ./trap
```

Run a script to compare the results of `spawnSync` and `spawn`:

```js
// trap.mjs
import { spawn, spawnSync } from "node:child_process";

const sync = spawnSync("./trap", []);
console.log("sync: status", sync.status, "signal", sync.signal);

spawn("./trap", []).on("exit", (status, signal) => console.log("async: status", status, "signal", signal));
```

### What is the expected behavior?

`spawn` and `spawnSync` both provide signal information:

```sh
$ node trap.mjs
sync: status null signal SIGTRAP
async: status null signal SIGTRAP
```

### What do you see instead?

Only `spawn` provides the signal. In `spawnSync` the signal is always null:

```sh
$ bun trap.mjs
sync: status null signal null
async: status null signal SIGTRAP
```

### Additional information

`Bun.spawnSync` seems to work correctly.

**Comment by cirospaciari** [comment]
Fixed by https://github.com/oven-sh/bun/pull/15137
