### ISSUE TITLE
process.env cannot be spread

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#1512]
### What version of Bun is running?

0.2.3 canary

### What platform is your computer?

`Linux 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 x86_64`

### What steps can reproduce the bug?

```ts
import { test, expect } from 'vitest'; // vitest is a direct alias of `bun:test`
 
test('process.env can be spread', () => {
  expect(Object.keys({ ...process.env }).length !== 0).toEqual(true);
});
```
this test succeeds on node but fails on bun

### How often does it reproduce? Is there a required condition?

every time

### What is the expected behavior?

to contain the actual environment variables

### What do you see instead?

spreading process env does nothing, you get `{}`

**Comment by Electroid** [comment]
@robobun 

```js
console.log(Object.keys({ ...process.env }));
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx

```
<details>
  <summary>Code</summary>
  
```tsx
console.log(Object.keys({ ...process.env }));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
