### ISSUE TITLE
Duckdb + Bun crashes

### ISSUE THREAD

**Issue by tengla** [oven-sh/bun#15136]
### How can we reproduce the crash?

```js
import duckdb from 'duckdb';

const db = new duckdb.Database(':memory:');

const csv = [
  'name,age',
  '"John Doe",42',
  '"Jane Doe",36'
];

async function main() {
  await Bun.write('data.csv', csv.join('\n'));
  const query = `SELECT * FROM read_csv('data.csv')`;
  db.all(query, (err, rows) => {
    if (err) {
      console.error(err);
    }
    console.log(JSON.stringify(rows));
  });
}
main();
```

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.35-canary ([`c5df329`](<https://github.com/oven-sh/bun/tree/c5df329772411a8968c4ed55fdc6f7c40eed329d>)) on macos aarch64 [RunCommand]

**panic**: A C++ exception occurred

- `Zig__GlobalObject__onCrash`
- `JSCInitialize::$_0::__invoke`
- *7 unknown/js code*
- `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_143628`

Features: process\_dlopen, dotenv, jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6062309086/">BUN-8BH</a></strong></sub>

**Comment by tengla** [comment]
BigInt is not serializable. Same in nodejs. But an error with context is reported: ```libc++abi: terminating due to uncaught exception of type Napi::Error: Do not know how to serialize a BigInt```

**Comment by luciandavidescu** [comment]
untested, but should be something like this:
console.log(JSON.stringify(rows, (_, v) => typeof v === "bigint" ? v.toString() : v))
