### ISSUE TITLE
Crash re-running bun i

### ISSUE THREAD

**Issue by PXNX** [oven-sh/bun#15161]
### `package.json` file

```json
{
  "name": "surreal-sveltekit",
  "version": "0.0.1",
  "devDependencies": {
    "@master/css-server": "2.0.0-rc.13",
    "@master/css.svelte": "2.0.0-rc.13",
    "@master/normal.css": "2.0.0-rc.13",
    "@sveltejs/adapter-auto": "3.1.1",
    "@sveltejs/adapter-node": "4.0.1",
    "@sveltejs/kit": "2.5.0",
    "@sveltejs/vite-plugin-svelte": "3.0.2",
    "@typescript-eslint/eslint-plugin": "7.0.1",
    "@typescript-eslint/parser": "7.0.1",
    "dayjs": "1.11.10",
    "eslint": "8.56.0",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-svelte": "2.35.1",
    "prettier": "3.2.5",
    "prettier-plugin-svelte": "3.1.2",
    "surrealdb.js": "0.11.0",
    "svelte": "4.2.10",
    "svelte-check": "3.6.4",
    "sveltekit-superforms": "1.13.4",
    "tslib": "2.6.2",
    "typescript": "5.3.3",
    "vite": "5.1.1",
    "vitest": "1.2.2",
    "zod": "3.22.4"
  },
  "private": true,
  "scripts": {
    "multitaskum:developum": "docker compose up -d && vite dev --host",
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "test": "vitest",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write ."
  },
  "type": "module",
  "dependencies": {
    "@master/css": "2.0.0-rc.13"
  }
}
```

### How can we reproduce the crash?

clone https://github.com/oskar-gmerek/surreal-sveltekit

run `bun i`

as stuck at 168/168, press `ctrl + c`

run `bun i` again

### Relevant log output

```shell
PS D:\dev\surreal-sveltekit> bun i
[7.00ms] ".env"
bun install v1.1.12 (43f0913c)
  🚚 @typescript-eslint/type-utils [168/168]
PS D:\dev\surreal-sveltekit> ^C
PS D:\dev\surreal-sveltekit> ^C
PS D:\dev\surreal-sveltekit> bun i
[0.00ms] ".env"
bun install v1.1.12 (43f0913c)
  📦 Installing [219/394] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\nyx\.bun\bin\bun.exe" "i"
Features: dotenv extracted_packages(51) 
Elapsed: 9153ms | User: 890ms | Sys: 10765ms
RSS: 0.26GB | Peak: 0.26GB | Commit: 0.41GB | Faults: 67932

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/wi143f0913AgoBk+vyH6s1yHuj80EmvlxEi3puE8ot2Fqi4BiiJow6y+CCa\KERNEL32.DLLo35FA0eNrLzEtJrVDILy1RyE9TSMovzUspBgBHeAcx

PS D:\dev\surreal-sveltekit>
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5159`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5159>): `processDependencyListItem`
- [`install.zig:5217`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5217>): `processDependencyList`
- [`install.zig:5937`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5937>): `runTasks`
- [`install.zig:10695`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L10695>): `installPackages`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/src/startup/exe_common.inl#L78>): `invoke_main`

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5404858290/">BUN-H3</a></strong></sub>

**Comment by dylan-conway** [comment]
This was fixed in bun v1.1.19 with #12485. Run `bun upgrade` to upgrade to bun v1.1.34.
