### ISSUE TITLE
`writeFileSync(path, data, { flag: undefined })` throws an error

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#1516]
### What version of Bun is running?

0.2.3 canary

### What platform is your computer?

Linux 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 unknown

### What steps can reproduce the bug?

```ts
require('fs').writeFileSync('a', 'b', { flag: undefined });
```

### What is the expected behavior?

To use the default setting and properly write, undefined shouldn't cause anything here.

### What do you see instead?

```
EPERM: Operation not permitted
    fd: "14"
syscall: "write"
  errno: -1
```

**Comment by Electroid** [comment]
@robobun 

```js
require('fs').writeFileSync('a', 'b', { flag: undefined });
```

**Comment by Electroid** [comment]
@robobun 

```js
require('fs').writeFileSync('a', 'b', { flag: undefined });
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
1 | import.meta.require("node:fs").writeFileSync("a", "b", { flag: undefined });
           ^
ENOENT: No such file or directory
   path: "a"
  scall: "open"
  errno: -2
      at /tmp/bun-LF2hoS/index.js:1:8
```
<details>
  <summary>Code</summary>
  
```tsx
require('fs').writeFileSync('a', 'b', { flag: undefined });
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
   path: "a"
```
<details>
  <summary>Code</summary>
  
```tsx
require('fs').writeFileSync('a', 'b', { flag: undefined });
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
