### ISSUE TITLE
bun -r crashes if file does not exist

### ISSUE THREAD

**Issue by trhinehart-godaddy** [oven-sh/bun#15177]
### How can we reproduce the crash?

`bun --hot --cwd ../ -r ./boom.js file.ts`

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- [`WriteBarrier.h:172`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/WriteBarrier.h#L172>): `JSC::WriteBarrierBase<JSC::Unknown,WTF::RawValueTraits<JSC::Unknown> >::get`
- [`bindings.cpp:3270`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/bindings.cpp#L3270>): `JSC__JSInternalPromise__status`
- [`shimmer.zig:177`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/shimmer.zig#L177>): `matchNullable`
- [`bindings.cpp:4876`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/bindings.cpp#L4876>): `JSC__VM__holdAPILock`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/shimmer.zig#L197>): `cppFn`
- [`cli.zig:2248`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/cli.zig#L2248>): `maybeOpenWithBunJS`
- [`cli.zig:2115`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/cli.zig#L2115>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/src/startup/exe_common.inl#L78>): `invoke_main`

Features: jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5780512711/">BUN-4YH</a></strong></sub>

**Comment by nektro** [comment]
are you able to provide us with the contents of `boom.js` and `file.ts` ?

**Comment by Jarred-Sumner** [comment]
@nektro it is trivially reproducible, I have a fix
