### ISSUE TITLE
Trying to use pino lib, but get Cannot find package "vm" error message

### ISSUE THREAD

**Issue by fernandolguevara** [oven-sh/bun#1517]
### What version of Bun is running?

0.2.2

### What platform is your computer?

macos m1 max arm64

### What steps can reproduce the bug?

```sh
mkdir buntest
cd buntest
bun install pino
echo -e "console.log(require('pino'))" > index.ts
bun index.ts
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

pino lib should be imported

### What do you see instead?

```
error: Cannot find package "vm" from "/Users/nil/projects/buntest/node_modules/.pnpm/registry.npmmirror.com+fast-redact@3.1.2/node_modules/fast-redact/lib/validator.js"
```

**Comment by Electroid** [comment]
Hey there, thanks for opening an issue! This is happening because we haven't implemented support for the `vm` module yet, but we're tracking support in this issue: #401
