### ISSUE TITLE
error: Cannot find module '@elastic/elasticsearch'

### ISSUE THREAD

**Issue by yharaskrik** [oven-sh/bun#15192]
### What version of Bun is running?

1.1.34

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

1. `bun install @elastic/elasticsearch@8`
2. import `import { Client } from '@elastic/elasticsearch';` into a script
3. `bun run script.ts`

### What is the expected behavior?

Should be able to import elastic search v8 package

### What do you see instead?

`error: Cannot find module '@elastic/elasticsearch'`

### Additional information

Works with v7 of the ES SDK.

Using v8 of the SDK and doing `const { Client } = require('@elastic/elasticsearch');` works, but it doesn't when using `import`

When running with `vite-node` I get:

```
Error: Failed to resolve entry for package "@elastic/elasticsearch". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@elastic/elasticsearch" package
```

Which might be the same issue bun is running into (the message for vite-node is more verbose so thats why I am including it)

**Comment by zurmokeeper** [comment]
@yharaskrik @elastic/elasticsearch v8.16.0 is buggy, maybe you can try v8.16.1, to see if there are still issues!

**Comment by yharaskrik** [comment]
> @yharaskrik @elastic/elasticsearch v8.16.0 is buggy, maybe you can try v8.16.1, to see if there are still issues!

Yup! This can actually be closed I think!
