### ISSUE TITLE
compile flag to prevent terminal window when launching single file exe

### ISSUE THREAD

**Issue by sensiblearts** [oven-sh/bun#15206]
### What is the problem this feature would solve?

When you create a single file exe on windows, e.g., with 

```
bun build ./index.ts --compile --outfile myexe
```

and then double-click on the exe, **a terminal window is opened**.

### What is the feature you are proposing to solve the problem?

In a zig program for Windows, you can prevent this terminal by adding to your `build.zig` file:

```
   exe.subsystem = .Windows;
```

It would be great if you could do something like:
```
bun build ./index.ts --compile --exe_subsystem_windows --outfile myexe
```
to avoid the terminal window.

**Comment by pfgithub** [comment]
Tracked in #13084, follow that issue for updates
