### ISSUE TITLE
int64 support for sqlite

### ISSUE THREAD

**Issue by AlexBlokh** [oven-sh/bun#1521]
### What version of Bun is running?

0.2.2

### What platform is your computer?

cpu: Apple M1 Pro runtime: bun 0.2.2 (arm64-darwin)

### What steps can reproduce the bug?

const result = sqlite.prepare(`select 1667476703000 as a`).all()
console.log(result) //1029392152

### What is the expected behavior?

1667476703000

### What do you see instead?

1029392152

**Comment by Jarred-Sumner** [comment]
_technically_ we don't support 64-bit integers but instead support doubles which go up to 52 signed bits

**Comment by AlexBlokh** [comment]
that should be `bigint` just like it is in other drivers
