### ISSUE TITLE
Bun vscode extension breaks "javascript debug terminal" for node

### ISSUE THREAD

**Issue by ulugbekna** [oven-sh/bun#15223]
### What version of Bun is running?

1.1.18

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

0. Have Bun vscode extension installed
1. Open command palette (cmd+shift+p or F1) and invoke command "debug: javascript debug terminal"
2. In the newly opened javascript debug terminal, run `node` and see how debugger cannot attach to the process 

### What is the expected behavior?

Javascript debug terminal can attach to a new node process 

### What do you see instead?

Javascript debug terminal cannot attach to a new node process 

### Additional information

This's the cause of the problem - https://github.com/oven-sh/bun/blob/d5a118e25f5cbb980078c52b35a6a9d13f3f85af/packages/bun-vscode/src/features/debug.ts#L95-L132. 

@connor4312 (from the vscode team, who works on debugging experience) would be happy to add some simple metadata to JS debug terminal environment to make Bun debugging work well.

**Comment by Electroid** [comment]
We'd love so that both Node and Bun work in the JavaScript debugger, are there any suggestions from the VSCode team on the canonical way to make this work?

**Comment by connor4312** [comment]
In https://github.com/microsoft/vscode-js-debug/pull/2136, I've made a way for you to extend the js debug terminal that should fit your needs:

1. Add a step in your build process to pull down https://github.com/microsoft/vscode-js-debug/blob/main/src/typings/vscode-js-debug.d.ts to somewhere in your sources. Or do so manually.
2. Add some code like this in your extension. Here I just modify the color, but for your case you would launch your server and modify the environment variables:

     ```ts
     const jsDebugExt = vscode.extensions.getExtension('ms-vscode.js-debug-nightly')
       || vscode.extensions.getExtension('ms-vscode.js-debug');
     await jsDebugExt.activate()
     const jsDebug: import('@vscode/js-debug').IExports = jsDebugExt.exports;
   
     jsDebug.registerDebugTerminalOptionsProvider({
    	provideTerminalOptions(options) {
    		options.color = new vscode.ThemeColor('charts.red');
    		return options;
    	},
     });
    ```

This will be on [js-debug nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension) tomorrow, please let me know how this works for you.
