### ISSUE TITLE
Bun crashes when reading very large file via Bun global

### ISSUE THREAD

**Issue by melindatrace** [oven-sh/bun#15242]
### How can we reproduce the crash?

Get a very large file like 5GB video file and try to load it into the memory via Bun global:
```ts
await Bun.file("./very-large-file").arrayBuffer();
```
Note: This doesn't happen with NodeJS API readFile, as an error "out of memory" is thrown.

### Relevant log output

```shell
panic(main thread): Internal assertion failure
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [RunCommand]

**panic**: Internal assertion failure

- [`ReadFile.zig:759`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/webcore/blob/ReadFile.zig#L759>): `queueRead`
- [`queue.h:33`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/queue.h#L33>): `uv__queue_empty`
- [`req-inl.h:189`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/win/req-inl.h#L189>): `uv__process_reqs`
- [`core.c:657`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/win/core.c#L657>): `uv_run`
- [`uws.zig:4145`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/deps/uws.zig#L4145>): `tickWithTimeout`
- [`event_loop.zig:1522`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/event_loop.zig#L1522>): `waitForPromise`
- [`javascript.zig:1566`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/javascript.zig#L1566>): `waitForPromise`
- [`bindings.cpp:4855`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/bindings.cpp#L4855>): `JSC__VM__holdAPILock`

Features: jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6074565962/">BUN-8KG</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
ah its supposed to throw an error
