### ISSUE TITLE
bun upgrade --stable installs a canary version

### ISSUE THREAD

**Issue by ottomated** [oven-sh/bun#15257]
### What version of Bun is running?

1.1.35-canary.86+206d2edf1

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

- Install bun 1.1.34: `curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.34"`
- Run `bun revision`: `1.1.34+5e5e7c60f`
- Run `bun upgrade --stable`
- Run `bun revision`: `1.1.35-canary.86+206d2edf1` 

Now bun is out of sync and will redownload the upgrade *every time* you run `bun upgrade`.

### What is the expected behavior?

`bun upgrade --stable` should install a stable version of bun. `bun upgrade` should also install the latest stable version.

### What do you see instead?

A canary version is installed instead.

**Comment by Electroid** [comment]
We are fixing this right now, and will be releasing 1.1.36 within the hour.

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.36

https://github.com/oven-sh/bun/releases/tag/bun-v1.1.36
