### ISSUE TITLE
Bun fails with packages that have no package.json

### ISSUE THREAD

**Issue by filmakarov** [oven-sh/bun#15285]
Some Solidity packages installed from github may have no `package.json` at all, as they have no dependecies.
One example is this:
https://github.com/Arachnid/solidity-stringutils

When it is used as dependency in a dependency, bun fails to `bun i`

![Image](https://github.com/user-attachments/assets/65e28e94-a490-4423-8986-e0ed57e2e0a5)

Can `package.json` be optional in such cases?

**Comment by dylan-conway** [comment]
This was implemented in bun v1.1.13 with #11644. Run `bun upgrade` to get the latest version of bun including this change.

If you add a git dependency from the cli without a name and the repo does not include a package.json with a name, Bun will choose the repo name as the dependency name.

```
bun add Arachnid/solidity-stringutils
```
package.json:
```diff
"dependencies": {
+     "solidity-stringutils": "Arachnid/solidity-stringutils"
}
```
