### ISSUE TITLE
[Regression] Bun snapshot test fails when escaping characters in v1.1.36

### ISSUE THREAD

**Issue by esciullo** [oven-sh/bun#15283]
### What version of Bun is running?

1.1.36+ededc168c

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run `bun test` twice with the following code

```typescript
import { it, expect } from "bun:test";

it("Should work", () => {
  expect(`This is \`wrong\``).toMatchSnapshot();
});
```

### What is the expected behavior?

It should pass after running twice.

### What do you see instead?

The second run fails.

**Comment by Jarred-Sumner** [comment]
We will fix this in Bun v1.1.37, which ships tomorrow
