### ISSUE TITLE
bun:test (tracking)

### ISSUE THREAD

**Issue by dylan-conway** [oven-sh/bun#1529]
**test**
- [ ] test.skip
- [ ] test.skipIf
- [ ] test.runIf
- [ ] test.only
- [ ] test.concurrent
- [ ] test.todo
- [ ] test.fails
- [ ] test.each

**describe**
- [ ] describe.skip
- [ ] describe.only
- [ ] describe.concurrent
- [ ] describe.shuffle
- [ ] describe.todo
- [ ] describe.each

**expect**
- [x] not
- [x] toBe
- [ ] toBeCloseTo
- [x] toBeDefined
- [x] toBeUndefined
- [x] toBeTruthy
- [x] toBeFalsy
- [x] toBeNull
- [x] toBeNaN
- [ ] toBeTypeOf
- [ ] toBeInstanceOf
- [ ] toBeGreaterThan
- [ ] toBeGreaterThanOrEqual
- [ ] toBeLessThan
- [ ] toBeLessThanOrEqual
- [x] toEqual
- [x] toStrictEqual
- [x] toContain
- [ ] toContainEqual
- [x] toHaveLength
- [x] toHaveProperty
- [ ] toMatch
- [ ] toMatchObject
- [ ] toThrowError
- [ ] toMatchSnapshot
- [ ] toMatchInlineSnapshot
- [ ] toThrowErrorMatchingSnapshot
- [ ] toThrowErrorMatchingInlineSnapshot
- [ ] toHaveBeenCalled
- [ ] toHaveBeenCalledTimes
- [ ] toHaveBeenCalledWith
- [ ] toHaveBeenLastCalledWith
- [ ] toHaveBeenNthCalledWith
- [ ] toHaveReturned
- [ ] toHaveReturnedTimes
- [ ] toHaveReturnedWith
- [ ] toHaveLastReturnedWith
- [ ] toHaveNthReturnedWith
- [ ] toSatisfy
- [ ] resolves
- [ ] rejects
- [ ] expect.assertions
- [ ] expect.hasAssertions
- [ ] expect.anything
- [ ] expect.any
- [ ] expect.arrayContaining
- [ ] expect.objectContaining
- [ ] expect.stringContaining
- [ ] expect.stringMatching
- [ ] expect.addSnapshotSerializer
- [ ] expect.extend

**mock methods**
- [ ] getMockName
- [ ] mockClear
- [ ] mockName
- [ ] mockImplementation
- [ ] mockImplementationOnce
- [ ] mockRejectedValue
- [ ] mockRejectedValueOnce
- [ ] mockReset
- [ ] mockRestore
- [ ] mockResolvedValue
- [ ] mockResolvedValueOnce
- [ ] mockReturnThis
- [ ] mockReturnValue
- [ ] mockReturnValueOnce

**mock properties**
- [ ] mock.calls
- [ ] mock.lastCall
- [ ] mock.results
- [ ] mock.instances

**Comment by Jarred-Sumner** [comment]
Let's not do the type checking ones from vitest for now. It'll need integration with tsc which we should think about carefully

**Comment by Electroid** [comment]
Closing in favor of #1825
