### ISSUE TITLE
`http2-wrapper` package breaks on `linux/amd64`

### ISSUE THREAD

**Issue by devunt** [oven-sh/bun#15308]
### What version of Bun is running?

oven/bun:1.1.36

### What platform is your computer?

Docker

### What steps can reproduce the bug?

[http2-wrapper](https://www.npmjs.com/package/http2-wrapper) package breaks on Bun v1.1.35 onwards.

If I downgrade the image tag to `oven/bun:1.1.34` it works well.

A weird thing is: Bun v1.1.36 in darwin/arm64 works well, but it only breaks in the docker (which is a linux/arm64).

**EDIT:** It also breaks in alpine image, too.

### What is the expected behavior?

Code builds well.

### What do you see instead?

```
|   "../../node_modules/.pnpm/http2-wrapper@2.2.1/node_modules/http2-wrapper/source/utils/js-stream-socket.js"(exports2, module2) {
|     "use strict";
|     init_cjs_shims();
|     var stream2 = require("stream");
|     var tls = require("tls");
|     var JSStreamSocket = new tls.TLSSocket(new stream2.PassThrough())._handle._parentWrap.constructor;
                                                                              ^
TypeError: null is not an object (evaluating 'new tls.TLSSocket(new stream2.PassThrough)._handle._parentWrap')
```

**Comment by ayZagen** [comment]
can't upgrade bun because if this regression.

**Comment by nathan-maybrey** [comment]
Just ran into this bug myself too
