### ISSUE TITLE
require.cache implementation

### ISSUE THREAD

**Issue by hades3729** [oven-sh/bun#1530]
### What is the problem this feature would solve?

Is was trying to use the module "terminal-kit" and got an error because of require.cache

31 | const path = require( 'path' ) ;
32 | 
33 | if ( process.browser || require.cache[ path.join( __dirname , 'termkit-no-lazy-require.js' ) ] ) {
                            ^
TypeError: undefined is not an object (evaluating 'require.cache[path.join(__dirname, "termkit-no-lazy-require.js")]')
      at /home/bitch/Bun/Cli_again/node_modules/terminal-kit/lib/termkit.js:33:24
      at bun:wrap:1:16360
      at /home/bitch/Bun/Cli_again/mod.ts:1:0

### What is the feature you are proposing to solve the problem?

Devs talked about setting it to an empty object or making it a proxy and that internally, require.cache is a `Map` 🤷🏻

**Comment by rejetto** [comment]
I'm using require.cache in my project with node.
I'm using it to re-import a plugin when its file is changed.
With node, the file wouldn't be re-loaded [unless I delete cache entries](https://github.com/rejetto/hfs/blob/95be5b6e1b70345697693c81b5a7eacadb2ecc1e/src/plugins.ts#L316).

is there a caching mechanism in Bun?
If yes, is there a way to avoid/manipulate it?
