### ISSUE TITLE
Segmentation fault on shadcn-svelte init

### ISSUE THREAD

**Issue by kyuuaria** [oven-sh/bun#15317]
### How can we reproduce the crash?

I keep getting the following error when trying to configure [shadcn-svelte](https://www.shadcn-svelte.com) via `bun x shadcn-svelte init` at the end

### Relevant log output

```shell
Bun v1.1.36 (ededc168) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "bun" "C:\Users\User\AppData\Local\Temp\bunx-1070947736-shadcn-svelte@next\node_modules\shadcn-svelte\dist\index.js" "init"
Features: Bun.stdin(2) Bun.stdout jsc transpiler_cache(3) tsconfig(2) tsconfig_paths 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:console" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "node:http2" "node:diagnostics_channel" 
Elapsed: 8321ms | User: 156ms | Sys: 31ms
RSS: 0.24GB | Peak: 0.24GB | Commit: 4.60GB | Faults: 61727

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc, spawn

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by heimskr** [comment]
Fixed by #15357.
