### ISSUE TITLE
`expect` within a `describe` block causes tests to not be detected

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1532]
The following code causes no tests to be detected.

```js
import { expect, describe, test } from "bun:test";

describe("1", () => {
  expect(1).toBe(1);
  test("1", () => {
    expect(1).toBe(1);
  });
});
```

```
 0 pass
 0 fail
 Ran 0 tests across 1 files [252.00ms]
```

When you remove the first `expect`, it works fine.

```js
import { expect, describe, test } from "bun:test";

describe("1", () => {
  test("1", () => {
    expect(1).toBe(1);
  });
});
```
```
✓ 1 > 1

 1 pass
 0 fail
 1 expect() calls
 Ran 1 tests across 1 files [307.00ms]
```

The intended behavior should be that if there is an `expect` and it fails, it bail the entire describe early.

**Comment by blackmann** [comment]
`expect` is currently required to be run in a test (or `it`) but throws (or bails early) if not. Should this issue be closed now?

**Comment by Electroid** [comment]
Yes, this was also fixed. The behaviour makes sense, `expect()` should be run in the context of a test.
