### ISSUE TITLE
Crash in CI

### ISSUE THREAD

**Issue by fmorency** [oven-sh/bun#15346]
### Relevant log output

```shell
#18 115.1  ✓ Compiled successfully
#18 115.1    Collecting page data ...
#18 116.3 ============================================================
#18 116.3 Bun v1.1.36 (ededc168) Linux x64 (baseline)
#18 116.3 Linux Kernel v6.5.0 | glibc v2.31
#18 116.3 CPU: sse42 popcnt avx avx2
#18 116.3 Args: "/usr/local/bin/bun" "/app/node_modules/next/dist/compiled/jest-worker/processChild.js"
#18 116.3 Features: bunfig dotenv jsc tsconfig(16) tsconfig_paths 
#18 116.3 Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "ws" "node-fetch" 
#18 116.3 Elapsed: 1249ms | User: 1063ms | Sys: 214ms
#18 116.3 RSS: 1.02GB | Peak: 0.45GB | Commit: 1.02GB | Faults: 0
#18 116.3 
#18 116.3 panic(main thread): Segmentation fault at address 0x6024C
#18 116.3 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
#18 116.3 
#18 116.3 To send a redacted crash report to Bun's team,
#18 116.3 please file a GitHub issue using the link below:
#18 116.3 
#18 116.3  https://bun.report/1.1.36/Ba1ededc16Ahs/7//Bu6+xiE+8mOo1mg8C84hl2C+qv0gDq8v1gDysj1gDqlnl3CskxkgD07vv+CA2A4khY
#18 116.3 
#18 116.4 ============================================================
#18 116.4 Bun v1.1.36 (ededc168) Linux x64 (baseline)
#18 116.4 Linux Kernel v6.5.0 | glibc v2.31
#18 116.4 CPU: sse42 popcnt avx avx2
#18 116.4 Args: "/usr/local/bin/bun" "/app/node_modules/next/dist/compiled/jest-worker/processChild.js"
#18 116.4 Features: bunfig dotenv jsc tsconfig(16) tsconfig_paths 
#18 116.4 Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "ws" "node-fetch" 
#18 116.4 Elapsed: 1291ms | User: 1094ms | Sys: 227ms
#18 116.4 RSS: 1.02GB | Peak: 0.45GB | Commit: 1.02GB | Faults: 0
#18 116.4 
#18 116.4 panic(main thread): Segmentation fault at address 0x6024C
#18 116.4 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x0006024C

- [`dependency.zig:851`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/dependency.zig#L851>): `src.resolver.resolver.Resolver.parsePackageJSON__anon_96763`
- [`resolver.zig:3987`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L3987>): `src.resolver.resolver.Resolver.dirInfoUncached`
- [`resolver.zig:2810`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L2810>): `src.resolver.resolver.Resolver.dirInfoCached`
- [`resolver.zig:1675`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L1675>): `src.resolver.resolver.Resolver.loadNodeModules`
- [`resolver.zig:2387`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L2387>): `src.resolver.resolver.Resolver.resolveWithoutRemapping`
- [`resolver.zig:1379`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L1379>): `src.resolver.resolver.Resolver.resolveAndAutoInstall`
- [`javascript.zig:2331`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/javascript.zig#L2331>): `src.bun.js.javascript.VirtualMachine.resolveMaybeNeedsTrailingSlash__anon_116043`
- [`javascript.zig:2407`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/javascript.zig#L2407>): `src.bun.js.api.BunObject.doResolveWithArgs__anon_109291`

Features: jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6076618246/">BUN-8MW</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.37. Try running `bun upgrade --canary` or wait till tomorrow for the release

This was a regression in v1.1.35
