### ISSUE TITLE
Segmentation fault during `bun --filter '*' dev`

### ISSUE THREAD

**Issue by eknowles** [oven-sh/bun#15343]
### How can we reproduce the crash?

- Running in devcontainer.
- Have two workspaces (app/server)

`bun i` works as does the same thing...

```ts
Bun.spawn(["bun", "run", "dev"], {
  cwd: "./apps/client",
});

Bun.spawn(["bun", "run", "dev"], {
  cwd: "./apps/server",
});
```

### Relevant log output

```shell
vscode ➜ /workspace (main) $ bun --filter '*' dev
============================================================
Bun v1.1.36 (ededc168) Linux arm64
Linux Kernel v6.10.4 | glibc v2.31
Args: "bun" "--filter" "*" "dev"
Elapsed: 11ms | User: 0ms | Sys: 4ms
RSS: 1.07GB | Peak: 11.51MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x6024C
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.36/La1ededc16AA+5Dm65x2Cm/og8C2z7p5C2kmn0C2n2l0Cu9mImz0l0CA2A4khY

[1]    13691 trace trap  bun --filter '*' dev
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on linux aarch64 [AutoCommand]

Segmentation fault at address 0x0006024C

- [`alloc.rs:0`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/alloc.rs#L0>): `??`
- [`semver.zig:582`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/semver.zig#L582>): `src.install.dependency.parseWithTag`
- [`dependency.zig:851`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/dependency.zig#L851>): `src.resolver.package_json.PackageJSON.parse__anon_106905`
- [`filter_run.zig:475`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli/filter_run.zig#L475>): `src.cli.filter_run.runScriptsWithFilter`
- [`cli.zig:2076`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli.zig#L2076>): `src.cli.Cli.start`
- [`main.zig:48`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/main.zig#L48>): `main`
- `??`
- `_start`

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6082633772/">BUN-8S9</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.37. try running `bun upgrade --canary` or wait till tomorrow for the release

This was a regression in v1.1.35
