### ISSUE TITLE
`bun build` doesn't accept Window's forward slashes

### ISSUE THREAD

**Issue by tresabhi** [oven-sh/bun#15356]
### How can we reproduce the crash?

Bun was stumped by `D:\blitzkit\node_modules\@blitzkit\core\src\index.ts`. The stack trace was automatically obfuscated by bun.

### Relevant log output

```shell
Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\coola\.bun\bin\bun.exe" "build" "packages/bot/src/main.ts" "--target=bun"
Features: dotenv tsconfig(10) 
Elapsed: 116ms | User: 109ms | Sys: 46ms
RSS: 0.25GB | Peak: 0.25GB | Commit: 0.37GB | Faults: 63322


panic(thread 9856): Expected pretty file path to have only forward slashes, got 'D:\blitzkit\node_modules\@blitzkit\core\src\index.ts'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Projects\jetsite\mott\platform\node_modules\@mott\error\dist\index.js'

- [`fs.zig:1728`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/fs.zig#L1728>): `assertPrettyIsValid`
- [`bundle_v2.zig:9103`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L9103>): `postProcessJSChunk`
- [`bundle_v2.zig:8005`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bundler/bundle_v2.zig#L8005>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-dp3pZl/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Can you upgrade to Bun v1.1.36 and try again?

**Comment by tresabhi** [comment]
Jarred, this issue is fixed. However, Bun's error logs are nightmare fuel. Bun has printed out every single file in the directory in this format:

```
  [8 /* VeryGood */]: "pink",
  [9 /* Unicum */]: "plum",
  [10 /* SuperUnicum */]: "purple"
};
// packages/core/src/statistics/getWN8Percentile.ts
var WN8_PERCENTILES = [
  [0, 0 /* VeryBad */],
  [300, 1 /* Bad */],
  [450, 2 /* BelowAverage */],
  [650, 3 /* Average */],
  [900, 4 /* AboveAverage */],
  [1200, 5 /* Good */],
  [1600, 6 /* VeryGood */],
  [2000, 7 /* Great */],
  [2450, 8 /* Unicum */],
  [2900, 9 /* SuperUnicum */]
];
// packages/core/src/streams/buffer.ts
class ReadStream {
  buffer;
  index = 0;
  dataView;
  textDecoderAscii = new TextDecoder("ascii");
  textDecoderUtf8 = new TextDecoder("utf8");
  constructor(buffer) {
    this.buffer = buffer;
    this.d
```

...and so on just to notify me in the end that...

```
});

// packages/bot/src/main.ts
manager.on("shardCreate", (shard) => {
  console.log(`\uD83D\uDFE1 Launching shard ${shard.id}`);
  shard.on("ready", () => console.log(`\uD83D\uDFE2 Launched shard ${shard.id}`));
}).spawn();
25 |   "sideEffects": [ "./src/nodes/**/*" ],
                        ^
warn: wildcard sideEffects are not supported yet, which means this package will be deoptimized
   at D:\blitzkit\node_modules\three\package.json:25:20
```

Why lol? 1 warning, 30,000 lines in the error log.
