### ISSUE TITLE
Segfault running Bun + Remix (w/ vite)

### ISSUE THREAD

**Issue by michaelgmcd** [oven-sh/bun#15353]
### How can we reproduce the crash?

Running a custom remix server in development crashes with Bun.

Reproduction: https://github.com/michaelgmcd/bun-remix-repro

Server code:
```
import { createServer } from 'vite';

import { Hono } from 'hono';

await createServer();

const app = new Hono();

Bun.serve({ port: 3000, fetch: app.fetch });
```

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x0006024C

- *1 unknown/js code*
- `src.install.dependency.parseWithTag`
- `src.resolver.resolver.Resolver.parsePackageJSON__anon_97690`
- `src.resolver.resolver.Resolver.dirInfoUncached`
- `src.resolver.resolver.Resolver.dirInfoCached`
- `src.resolver.resolver.Resolver.loadNodeModules`
- `src.resolver.resolver.Resolver.resolveWithoutRemapping`
- `src.resolver.resolver.Resolver.resolveAndAutoInstall`
- `src.bun.js.javascript.VirtualMachine.resolveMaybeNeedsTrailingSlash__anon_116799`
- `src.bun.js.api.BunObject.doResolveWithArgs__anon_110045`

Features: process\_dlopen, Bun.stdin, dotenv, jsc, spawn, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6077153494/">BUN-8NE</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15332

This will be part of the Bun v1.1.37 release, which is today

For now, you can run bun upgrade --canary
