### ISSUE TITLE
Crash on yarn representation of lockfile

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#15363]
### How can we reproduce the crash?

I open my project (in previous i open lockfile) and see this 

![Image](https://github.com/user-attachments/assets/0d7bbddd-041c-4e1a-b20a-8052e8aa5811)

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [AutoCommand]

**panic**: incorrect alignment

- [`dependency.zig:1072`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/dependency.zig#L1072>): `parseWithTag`
- [`dependency.zig:416`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/dependency.zig#L416>): `toVersion`
- [`lockfile.zig:5869`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/lockfile.zig#L5869>): `load`
- [`lockfile.zig:6123`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/lockfile.zig#L6123>): `load`
- [`lockfile.zig:263`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/lockfile.zig#L263>): `loadFromDisk`
- [`lockfile.zig:1241`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/lockfile.zig#L1241>): `print`
- [`cli.zig:2105`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli.zig#L2105>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/src/startup/exe_common.inl#L78>): `invoke_main`

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6067098973/">BUN-8FJ</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.37, please run `bun upgrade --canary`
