### ISSUE TITLE
Inconsistent compiled builds

### ISSUE THREAD

**Issue by begoon** [oven-sh/bun#15370]
### What version of Bun is running?

1.1.37-canary.44+aa60ab3b6

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

I have a file server to serve embedded assets:
```typescript
import { file } from "bun";
import index from "./files/index.html" with { type: "file" };

export default {fetch(req) { return new Response(file(index))}};
```
and assets in "./files/".
```console
echo "INDEX-1" > ./files/index.html
ls -l ./files/*
-rw-r--r--  1 alexander  staff  8 Nov 23 14:29 ./files/index.html
hexdump -C ./files/*
00000000  49 4e 44 45 58 2d 31 0a                           |INDEX-1.|
00000008
```
I compile to `exe1`:
```sh
bun build --compile ./main2.ts ./files/*.html --outfile exe1
  [14ms]  bundle  2 modules
  [98ms] compile  exe1
```
Then I change one character in "index.html" from "1" to "2":
```
echo "INDEX-2" > ./files/index.html
ls -l ./files/*
-rw-r--r--  1 alexander  staff  8 Nov 23 14:29 ./files/index.html
hexdump -C ./files/*
00000000  49 4e 44 45 58 2d 32 0a                           |INDEX-2.|
00000008
```
and recompile to "exe2":
```console
bun build --compile ./main2.ts ./files/*.html --outfile exe2
   [2ms]  bundle  2 modules
 [105ms] compile  exe2
```
As a result, I have two binaries of equal size:
```
ls -al exe*
-rwxrwxrwx@ 1 alexander  staff  54192910 Nov 23 14:29 exe1
-rwxrwxrwx@ 1 alexander  staff  54192910 Nov 23 14:29 exe2
```
Assuming that the only difference between the source and the assets is one character, changed from '1' to '2', I assumed that the executables should differ in one byte only.

I compare them:
```console
// diff <(xxd exe1) <(xxd exe2)
3387020c3387020
< 033ae8b0: 3100 2f2f 2040 6275 6e0a 2f2f 2066 696c  1.// @bun.// fil
---
> 033ae8b0: 3200 2f2f 2040 6275 6e0a 2f2f 2066 696c  2.// @bun.// fil
3387024c3387024
< 033ae8f0: 696e 6465 782d 3736 3376 7632 7362 2e68  index-763vv2sb.h
---
> 033ae8f0: 696e 6465 782d 7774 3476 7238 6d70 2e68  index-wt4vr8mp.h
3387042c3387042
< 033aea10: 3736 3376 7632 7362 2e68 746d 6c22 3b0a  763vv2sb.html";.
---
> 033aea10: 7774 3476 7238 6d70 2e68 746d 6c22 3b0a  wt4vr8mp.html";.
3387046,3387047c3387046,3387047
< 033aea50: 726f 6f74 2f69 6e64 6578 2d37 3633 7676  root/index-763vv
< 033aea60: 3273 622e 6874 6d6c 0049 4e44 4558 2d31  2sb.html.INDEX-1
---
> 033aea50: 726f 6f74 2f69 6e64 6578 2d77 7434 7672  root/index-wt4vr
> 033aea60: 386d 702e 6874 6d6c 0049 4e44 4558 2d32  8mp.html.INDEX-2
```
Hm... I see that changed string from "INDEX-1" to "INDEX-2".

I see the changed string in the diff in plain text, but I also see other differences. I assumed that equal input in compilation should produce equal output.

### What is the expected behavior?

The same input to the compiler should produce the same result, bit to bit.

### What do you see instead?

The output is different though.

**Comment by Jarred-Sumner** [comment]
Bun hashes files and stores hashes internally. We also do sourcemaps. It won’t have 1 byte of difference. 

This is unlikely to change. But let us know if you find unexpected patterns in the data
