### ISSUE TITLE
Bun crashes when using fillText @napi-rs/canvas

### ISSUE THREAD

**Issue by taro445** [oven-sh/bun#15372]
### How can we reproduce the crash?

I am experiencing a crash in Bun when using ctx['fillText']("Big smile!", 10, 90) with @napi-rs/canvas while integrating with Elysia on Bun.

### Relevant log output

```shell
node_modules\@napi-rs\canvas-win32-x64-msvc\icudtl.dat.
SkIcuLoader: datafile missing: C:\Users\...\AppData\Roaming\npm\node_modules\bun\bin\icudtl.dat.
../../modules/skparagraph/src/ParagraphBuilderImpl.cpp(252): fatal error: "check(fUnicode)"
============================================================
Bun v1.1.36 (ededc168) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\...\AppData\Roaming\npm\\node_modules\bun\bin\bun.exe" "run" "--watch" "./src/app.ts"
Features: Bun.stdin(2) dotenv http_server jsc transpiler_cache(12) tsconfig(14) tsconfig_paths(2) process_dlopen
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:stream" "node:string_decoder" "node:timers" "node:timers/promises" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads"
Elapsed: 2690ms | User: 578ms | Sys: 281ms
RSS: 0.51GB | Peak: 0.51GB | Commit: 0.77GB | Faults: 130554

panic(main thread): Illegal instruction at address 0x7FFD829BA420
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [RunCommand]

Illegal instruction at address 0x7FFD829BA420

- ??? at `0x1ea420` in skia.win32-x64-msvc.node
- ??? at `0x20e3e9` in skia.win32-x64-msvc.node
- ??? at `0x20e3b8` in skia.win32-x64-msvc.node
- ??? at `0x17e5b8` in skia.win32-x64-msvc.node
- ??? at `0x1eb85` in skia.win32-x64-msvc.node
- ??? at `0x1ad29` in skia.win32-x64-msvc.node
- ??? at `0x1a94f` in skia.win32-x64-msvc.node
- ??? at `0x23ad7` in skia.win32-x64-msvc.node
- ??? at `0x3b819` in skia.win32-x64-msvc.node
- [`napi.cpp:452`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/bindings/napi.cpp#L452>): `NAPIFunction::call`

Features: process\_dlopen, Bun.stdin, dotenv, http\_server, jsc, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6085257859/">BUN-8TN</a></strong></sub>

**Comment by 190n** [comment]
I reproduced this crash with a small example using `@napi-rs/canvas` v0.1.63, and it's fixed after upgrading to v0.1.64. @AceLikesGhosts if your code still runs into errors even after upgrading, please re-open this issue.

> although Bun should not be dying like this.

There isn't really anything better we can do when third-party native code crashes. While _in this specific case_ it may have worked to, say, unwind the stack up to the last JavaScript code and raise some kind of exception:

- it's much harder to implement that behavior (especially cross-platform and cross-architecture) than to describe it
- we can't assume, after encountering a segmentation fault or an illegal instruction, that the process is in a state fit to continue running. There may be unrecoverable memory corruption, and trying to keep executing code could just crash in a different, harder-to-debug way.
