### ISSUE TITLE
`ConnectionClosed` error with bun update

### ISSUE THREAD

**Issue by tembbo** [oven-sh/bun#15384]
### What version of Bun is running?

1.1.36+ededc168c

### What platform is your computer?

Darwin 24.2.0 arm64 arm

### What steps can reproduce the bug?

This is not reproducible.

Do something with bun that requires fetching, like `bun update` or `bun create`, i have no problems with `bun i` on projects with dependencies already installed. I now see `error: ConnectionClosed downloading package manifest <package>`

### What is the expected behavior?

It should actually install the package without errors.

### What do you see instead?

`error: ConnectionClosed downloading package manifest <package>`

### Additional information

I know this has been answered multiple times before, but none of the proposed solutions there have worked for me

The only solutions I've found are:
1. Switching to npm, deno, yarn or pnpm (not viable)
2. Hotspotting from my phone or switching to another network (thats slow). _switching to another network also doesnt work now_
3. Downgrading bun to `bun-v1.0.20` (also not viable)

**Comment by realguse** [comment]
Fixed by turning off "iCloud Private Relay".
