### ISSUE TITLE
`bun install` fails to match semver versions with `-0` pre tags when the other version doesn't have a pre tag

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1539]
This test fails but it shouldn't:
```zig
expect.range("~1.2.3", "1.2.3-0", @src());
```

The problem is we treat pre tags right now as effectively separate namespaces. 

This leads to certain packages incorrectly reporting "no matching version found". 

Example: https://www.npmjs.com/package/etpl?activeTab=versions. 

The package `"asd"` has a dependency on `"etpl@~2.1.0"`. 

In that case, we should be matching `2.1.0-rc`.

**Comment by alexlamsl** [comment]
This failure is consistent with `semver`:
```js
$ cat test.js
console.log(require("semver").satisfies("1.2.3-0", "~1.2.3"));
```
```console
$ BUN_DEBUG_QUIET_LOGS=1 bun-debug test.js
false
```
I think the rationale is that `1.0.0-rc` should be lesser than `1.0.0`
