### ISSUE TITLE
Failure to build Nuxt in docker

### ISSUE THREAD

**Issue by Coops0** [oven-sh/bun#15394]
### How can we reproduce the crash?

Attached is my docker file, my package.json, and my bun.lockb file.
[Dockerfile.txt](https://github.com/user-attachments/files/17895820/Dockerfile.txt)
[bun.lockb.txt](https://github.com/user-attachments/files/17895821/bun.lockb.txt)
[package.json](https://github.com/user-attachments/files/17895818/package.json)

### Relevant log output

```shell
> [jrnl-front install 3/6] RUN cd /temp/dev && bun install --frozen-lockfile:
0.112 bun install v1.1.36 (ededc168)
141.9
141.9 $ nuxt prepare
142.1 ============================================================
142.1 Bun v1.1.36 (ededc168) Linux arm64
142.1 Linux Kernel v6.8.0 | glibc v2.31
142.1 Args: "node" "/temp/dev/node_modules/.bin/nuxt" "prepare"
142.1 Features: Bun.stdin(2) jsc
142.1 Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:crypto" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:v8"
142.1 Elapsed: 154ms | User: 141ms | Sys: 17ms
142.1 RSS: 1.05GB | Peak: 0.16GB | Commit: 1.05GB | Faults: 19
142.1
142.1 panic(main thread): Segmentation fault at address 0x6024C
142.1 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
142.1
142.1 To send a redacted crash report to Bun's team,
142.1 please file a GitHub issue using the link below:
142.1
142.1  https://bun.report/1.1.36/Ln1ededc16AkggEu/229DuvEm65x2C27k+5C2/5w0C2zow0Cmv1u6C2smu1C+ov99C2io99CA2A4khY
142.1
142.2 error: postinstall script from "jrnl-front" terminated by SIGTRAP (Trace or breakpoint trap)
142.3 Trace/breakpoint trap (core dumped)
------
failed to solve: process "/bin/sh -c cd /temp/dev && bun install --frozen-lockfile" did not complete successfully: exit code: 133
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on linux aarch64 [RunAsNodeCommand]

Segmentation fault at address 0x0006024C

- [`semver.zig:582`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/semver.zig#L582>): `src.install.dependency.parseWithTag`
- [`dependency.zig:851`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/dependency.zig#L851>): `src.resolver.resolver.Resolver.parsePackageJSON__anon_96738`
- [`resolver.zig:3987`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L3987>): `src.resolver.resolver.Resolver.dirInfoUncached`
- [`resolver.zig:2810`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L2810>): `src.resolver.resolver.Resolver.dirInfoCachedMaybeLog__anon_56580`
- [`resolver.zig:2491`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L2491>): `src.resolver.resolver.Resolver.finalizeResult`
- [`resolver.zig:884`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/resolver/resolver.zig#L884>): `src.resolver.resolver.Resolver.resolveAndAutoInstall`
- [`javascript.zig:2331`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/javascript.zig#L2331>): `src.bun.js.javascript.VirtualMachine.resolveMaybeNeedsTrailingSlash__anon_116018`
- [`javascript.zig:2418`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/javascript.zig#L2418>): `Zig__GlobalObject__resolve`

Features: Bun.stdin, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6081278325/">BUN-8RM</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.37

Please either run `bun upgrade --canary`, downgrade to Bun v1.1.34, or wait until tomorrow
