### ISSUE TITLE
panic: Segmentation fault at address 0x102000000E4

### ISSUE THREAD

**Issue by yolmcore** [oven-sh/bun#15390]
### How can we reproduce the crash?

Note, I am using workers to parallelize documentation generation. This does not happen every single time, maybe one out of 6 times.

### Relevant log output

```shell
Bun v1.1.36 (ededc168) macOS Silicon
macOS v14.6.1
Args: "bun" "scripts/jsdoc.ts" "packages/**/*.ts"
Features: jsc transpiler_cache(57) tsconfig tsconfig_paths workers_spawned(18) workers_terminated(3) 
Builtins: "bun:main" "node:buffer" "node:crypto" "node:fs" "node:fs/promises" "node:os" "node:path" "node:perf_hooks" "node:string_decoder" "node:util" "node:util/types" "node:worker_threads" 
Elapsed: 1462ms | User: 10626ms | Sys: 1675ms
RSS: 3.30GB | Peak: 3.30GB | Commit: 1.80GB | Faults: 56

panic: Segmentation fault at address 0x102000000E4
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.36/Ma1ededc16Mhgg8/f__u90whBui302Bm28y2B+9ww2B27gg2Bmy4ujCus/yhB2vo5WA2kQoO

76 |   }
77 | 
78 |   const exitCode = await proc.exited;
79 | 
80 |   if (exitCode !== 0) {
81 |     throw new Error(`${name} failed with exit code ${exitCode}${dirMessage}`);
               ^
error: bun scripts/jsdoc.ts packages/**/*.ts failed with exit code 133
      at /Users/ralfhaug/dev/yolm/scripts/utils.ts:81:11

Bun v1.1.36 (macOS arm64)
error: script "docs" exited with code 1
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x616C7265764F656B

- *2 unknown/js code*
- `WebCore::WebCoreTypedArrayController::JSArrayBufferOwner::finalize`
- `JSC::WeakBlock::lastChanceToFinalize`
- `JSC::PreciseAllocation::lastChanceToFinalize`
- `JSC::MarkedSpace::lastChanceToFinalize`
- `JSC::Heap::lastChanceToFinalize`
- `JSC::VM::~VM`
- `WebWorker__dispatchExit`
- `src.bun.js.web_worker.WebWorker.exitAndDeinit`

Features: workers\_spawned, workers\_terminated, jsc, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6041090820/">BUN-7Y3</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
We are tracking Worker stability in #15964
