### ISSUE TITLE
VSCode extension issue using the embedded CLI of VSCode

### ISSUE THREAD

**Issue by ScreamZ** [oven-sh/bun#15425]
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

I'm not able to tell exactly when it started but using the VSCode extension for bun now trigger an error in the console, before running the expected TypeScript code.

---

Inside VSCode terminal

A simple 
```ts
// poke.ts
console.log("hello world");
``` 

now run `bun poke.ts` and get:

- **Without bun extension for VSCode**
```sh
hello world          
``` 

- **With Bun extension for VSCode (after re-opening the terminal)**
```sh
382 | function reset() {
383 |   if (enableANSIColors)
384 |     return "\x1B[49m";
385 |   return "";
386 | }
387 |   Bun.connect({
                   ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at notify (internal:debugger:387:14)
      at internal:debugger:73:13
hello world
``` 

### What is the expected behavior?

There should be no error in the console.

### What do you see instead?

```sh
382 | function reset() {
383 |   if (enableANSIColors)
384 |     return "\x1B[49m";
385 |   return "";
386 | }
387 |   Bun.connect({
                   ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at notify (internal:debugger:387:14)
      at internal:debugger:73:13
```

**Comment by Jonatthu** [comment]
Also, vscode fails in debug tests randomly.
```
bun test v1.1.37 (8ca0eb83)

src/middleware/publicProcedure.test.ts:
Debugger attached.

# Unhandled error between tests
-------------------------------
4 | 
5 | import { createTestSuite, createTestTrpcCaller } from '~@/utils/test.helpers';
6 | 
7 | const suite = await createTestSuite();
8 | 
9 | describe('publicProcedure', () => {
    ^
TypeError: Cannot convert a symbol to a string
      at /publicProcedure.test.ts:9:1
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 tests across 1 files. [3.66s]
Debugger detached.

```

**Comment by RiskyMH** [comment]
The main issue should be fixed in canary, but people have reported it still slow afterwards.
```ts
bun upgrade --canary
```

**Comment by LeulAria** [comment]
im still facing issue even after

```shell
bun upgrade --canary
```

```shell
$ bun run --hot src/server.ts --inspect
80 |     return `\x1B[1m\x1B]8;;${url}\x1B\\${url}\x1B]8;;\x1B\\\x1B[22m`;
81 |   return url;
82 | }, reset = function() {
83 |   if (enableANSIColors)
84 |     return "\x1B[49m";
85 | }, notify = function(unix) {
                         ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at internal:debugger:85:21
      at internal:debugger:100:13
```

**Comment by pipisasa** [comment]
> The main issue should be fixed in canary, but people have reported it still slow afterwards.
> 
> bun upgrade --canary

I had the same problem. It was fixed when I updated Bun to 1.1.38

**Comment by LeulAria** [comment]
1.1.38 work's fine for me as well, loving bun <3

**Comment by ScreamZ** [comment]
@RiskyMH Nice, but shouldn't also be fixed in the VSCode extension, not a big fan of using canary version… :/

Any ETA on release ? :)

**Comment by lunfardo** [comment]
It fixed it for me as well. I can also confirm that it runs slower than in the Windows Terminal

**Comment by RiskyMH** [comment]
> [@RiskyMH](https://github.com/RiskyMH) Nice, but shouldn't also be fixed in the VSCode extension, not a big fan of using canary version… :/
> 
> Any ETA on release ? :)

Bun 1.1.38 was released a few days ago and I just updated the extension which should be harder to get his issue in future (main changes #15458)

Let me know if its still noticeably slower still also.
