### ISSUE TITLE
Adding an emoji to the first arg for console.log causes substitution to not work?

### ISSUE THREAD

**Issue by OmgImAlexis** [oven-sh/bun#1542]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64 i386

### What steps can reproduce the bug?

```ts
// Works
console.log('field: %s', 3000);

// Doesn't work
console.log('🌭field: %s', 3000);
console.log('field: %s🌭', 3000);
```

### How often does it reproduce? Is there a required condition?

100% of the time

### What is the expected behavior?

```
field: 3000
🌭field: 3000
field: 3000🌭
```

### What do you see instead?

```
🌭field: %s 3000
field: %s🌭 3000
```

**Comment by Electroid** [comment]
@robobun 

```js
// Works
console.log('field: %s', 3000);

// Doesn't work
console.log('🌭field: %s', 3000);
console.log('field: %s🌭', 3000);
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
field: 3000
堼弭field: %s 3000
field: %s堼弭 3000
```
<details>
  <summary>Code</summary>
  
```tsx
// Works

console.log('field: %s', 3000);



// Doesn't work

console.log('🌭field: %s', 3000);

console.log('field: %s🌭', 3000);
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Jarred-Sumner** [comment]
I think this is fixed in canary along with the latin1 issues (the code for this was commented out before for UTF16)
