### ISSUE TITLE
Expected pretty file path to have only forward slashes

### ISSUE THREAD

**Issue by aBitEmberous** [oven-sh/bun#15421]
### How can we reproduce the crash?

Context: Using NPM workspaces. The package 'web' is where `bun build` is being run.  This package imports another workspace package called `spark-engine`, specifically an `index.js` file.  The paltform is Windows 11 Home, version 23H2.

Please note that the `web` package is using React. This *should* not make a difference, but as it may be relevant I'd prefer to mention it.

1.  Added script 'dev:bun' to package.json of `web` : `bun build src/main.tsx --outfile=dist/index.js --watch --sourcemap --target=node`
2.  cd to package
3. Run above script using bun: `bun run dev:bun`
4. In my case, the error posted in the stacktrace occurs.

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Users\Gustavo\Desktop\brisa-example\node_modules\brisa\jsx-runtime\index.js'

- [`fs.zig:1732`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/fs.zig#L1732>): `assertPrettyIsValid`
- [`bundle_v2.zig:9284`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L9284>): `postProcessJSChunk`
- [`bundle_v2.zig:8174`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L8174>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: Bun.stdin, bunfig, define, external, jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by AtherActive** [comment]
Welp, I'm an idiot for not updating Bun 🤦‍♀
