### ISSUE TITLE
Debugging Not Working After Upgrade to 1.1.37

### ISSUE THREAD

**Issue by k3341095** [oven-sh/bun#15439]
### What version of Bun is running?

1.1.37+8ca0eb831

### What platform is your computer?

Linux 6.8.0-49-generic x86_64 x86_64

### What steps can reproduce the bug?

console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");
console.log("Hello via Bun!");

Set breakpoints on lines 1 to 4.
Run the debugger.

### What is the expected behavior?

The breakpoint only stops at line 1.

### What do you see instead?

The breakpoints do not trigger, and the program simply continues running without stopping.

Debugger attached.
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Hello via Bun!
Debugger detached.

### Additional information

In version 1.1.36, breakpoints are triggered, but as reported previously, the breakpoint incorrectly stops at line 2 instead of line 1.
After upgrading to 1.1.37, the breakpoints no longer work at all — the program just runs without stopping.
The expected behavior is for the breakpoint to trigger on line 1.

https://github.com/oven-sh/bun/issues/15131

**Comment by LoganTann** [comment]
I'm experiencing the same issue. Downgraded to 1.1.36, I can confirm this issue happens only on 1.1.37.

**Comment by devtrader** [comment]
Experiencing the same not hitting breakpoints issue. Solved by downgrading Bun to 1.1.36 as suggested above.

Visual Studio Code v1.95.3
Bun for Visual Studio Code v0.0.25
Typescript v5.7.2

bun v1.1.38  - Breakpoints not hit in VSCode
bun v1.1.37  - Breakpoints not hit in VSCode
bun v1.1.36  - **_Works._**
bun v1.1.35 - **_Works_**

VSCode configuration
 {
        "name": "Bun File",
        "program": "${file}",
        "cwd": "${workspaceFolder}",
        "request": "launch",
        "type": "bun",
      },
