### ISSUE TITLE
bun dev command cannot work

### ISSUE THREAD

**Issue by Mantou1233** [oven-sh/bun#1543]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

do `bun create react ./app`, `cd app`, and `bun dev`
connect to localhost:3000, gives `ERR_CONNECTION_REFUSED`

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

the app open normally

### What do you see instead?

the app closes after connecting

### Additional information

i am using WSL

**Comment by LF-Fish** [comment]
I hava a same problem

**Comment by birkskyum** [comment]
`bun dev` has been removed
