### ISSUE TITLE
Bun crashed while replacing already installed shadcn components

### ISSUE THREAD

**Issue by xnammu** [oven-sh/bun#15450]
### How can we reproduce the crash?

Bun v1.1.36 (ededc168) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Nammu\.bun\bin\bunx.exe" "--bun" "shadcn@latest" "add"
Features: Bun.stderr Bun.stdin(2) Bun.stdout dotenv fetch(130) jsc spawn(2) transpiler_cache tsconfig(2) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:timers/promises" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node-fetch" 
Elapsed: 101287ms | User: 859ms | Sys: 609ms
RSS: 0.46GB | Peak: 0.53GB | Commit: 0.62GB | Faults: 202565

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc, spawn

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5610708776/">BUN-226</a></strong></sub>

**Comment by heimskr** [comment]
This bug was fixed in 1.1.37. Try upgrading and let us know if you still get crashes.
