### ISSUE TITLE
Undocumented incompatibility between `bun:test` and `jest` with `expect.reject` and `expect.resolves`

### ISSUE THREAD

**Issue by robin-kuzco** [oven-sh/bun#15457]
### What is the type of issue?

Documentation is missing

### What is the issue?

Matchers `resolve` and `reject` from `bun:test` have different behaviour to `resolve` and `reject` from `jest`. 

The matchers from `bun:test` will block until the `Promise` is resolved or rejected:
https://github.com/oven-sh/bun/blob/1bb211df56f528d536803d4a0c15bcfed49d0fb9/src/bun.js/test/expect.zig#L214

The matchers from jest do not block, and instead return `Promise`s that must be awaited.

For example,
```js
async function delay(value) {
  await new Promise((resolve) => setTimeout(resolve, value));
}

// Bun style resolves
test("sync", () => {
  expect.assertions(1);
  expect(delay(100)).resolves.toBe(undefined);
});

// Jest style resolves
test("async", async () => {
  expect.assertions(1);
  await expect(delay(100)).resolves.toBe(undefined);
});
```

Note that the matchers are typed as expected - `expect(...).{resolves,rejects}.[...]() => void`. The documentation, however, doesn't make any note of this difference.

### Where did you find it?

https://bun.sh/docs/cli/test

**Comment by RiskyMH** [comment]
Interesting, also similar to https://github.com/oven-sh/bun/issues/15428
