### ISSUE TITLE
Regularily Crashing

### ISSUE THREAD

**Issue by jeremynack** [oven-sh/bun#15480]
### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [RunCommand]

**panic**: Internal assertion failure

- [`ZigGeneratedClasses.zig:13529`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/build/release-ci/codegen/ZigGeneratedClasses.zig#L13529>): `UDPSocketClass__finalize`
- [`Weak.h:89`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/windows-x64-build-cpp/webkit-9b84f43643eff64ab46daec9b860de262c80f5e2/include/JavaScriptCore/Weak.h#L89>): `JSC::Weak<WebCore::JSUDPSocket>::impl`
- [`JSDestructibleObjectHeapCellType.cpp:43`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSDestructibleObjectHeapCellType.cpp#L43>): `JSC::JSDestructibleObjectDestroyFunc::operator()`
- [`MarkedBlockInlines.h:513`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/MarkedBlockInlines.h#L513>): `JSC::MarkedBlock::Handle::finishSweepKnowingHeapCellType<JSC::JSDestructibleObjectDestroyFunc>`
- [`JSDestructibleObjectHeapCellType.cpp:56`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSDestructibleObjectHeapCellType.cpp#L56>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`
- [`SweepingScope.h:43`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/SweepingScope.h#L43>): `JSC::SweepingScope::~SweepingScope`
- [`BlockDirectory.cpp:254`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/heap/BlockDirectory.cpp#L254>): `JSC::BlockDirectory::lastChanceToFinalize::<lambda_0>::operator()`

Features: workers\_spawned, workers\_terminated, http\_server, jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6086351339/">BUN-8V7</a></strong></sub>

**Comment by DonIsaac** [comment]
Thanks for reporting this! Just a few questions:
1. What happened when the crash occurred? e.g. Did you press CTRL-C?
2. Do you have a reproduction handy?
