### ISSUE TITLE
upgrade bun uses canary version instead of released

### ISSUE THREAD

**Issue by valpuia604** [oven-sh/bun#15529]
I used ubuntu 24.04 and I run `bun upgrade` and it gives me incorrect version?

![Image](https://github.com/user-attachments/assets/402eafb0-427b-4ba2-9b49-983266d28edf)

It looks like it upgrade to upcoming version `1.1.39-canary.8+d2acb2eac` but don't know why and how
![Image](https://github.com/user-attachments/assets/fb49670f-331a-41f0-9546-632c23c762de)

**Comment by RiskyMH** [comment]
If you had upgraded to `v1.1.35`, Bun may mistakenly assume you want the canary build due to an issue in its release process. 

To resolve this, run **`bun upgrade --stable`** to switch back to the stable version.

> We will be releasing 1.1.36 shortly. Due to an issue with the release process, the canary flag was set to true in the release build and we will bump the version with a new release to compensate  
https://x.com/bunjavascript/status/1859000037977846211

**Comment by valpuia604** [comment]
Thank you, yes it's indeed 1.1.35 -> canary, now uses stable using `--stable`
