### ISSUE TITLE
segmentation fault with two line program

### ISSUE THREAD

**Issue by KevinBrogan** [oven-sh/bun#1555]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Linux 5.14.0-183.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 31 09:18:51 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

index.js
```
import { spawnSync } from "bun";
const {stdout} =  spawnSync('cwd');
```
command line
`bun index.js`

### How often does it reproduce? Is there a required condition?

everytime

### What is the expected behavior?

not a segmentation fault

### What do you see instead?

a segmentation fault

SegmentationFault at 0x0600000000000000

----- bun meta -----
Bun v0.2.2 (6632135e) Linux x64 #1 SMP PREEMPT_DYNAMIC Mon Oct 31 09:18:51 UTC 2022
AutoCommand:
Elapsed: 46ms | User: 23ms | Sys: 24ms
RSS: 67.11MB | Peak: 57.20MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

**Comment by Jarred-Sumner** [comment]
This has been fixed in canary, though there are more bugs with `spawnSync` that haven't been fixed yet

To upgrade:
```bash
bun upgrade --canary
```
