### ISSUE TITLE
bun repl in VSC terminal messed up

### ISSUE THREAD

**Issue by branaway** [oven-sh/bun#15588]
### What version of Bun is running?

1.1.38

### What platform is your computer?

macOS Montereey

### What steps can reproduce the bug?

I worked fine before 1.1.38. 

now simply starting `bun repl` outputting enormous amount of junk letters, end of which is like:

`functionName\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"url\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"scriptId\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"lineNumber\\\\\\\\\\\\\\\":138,\\\\\\\\\\\\\\\"columnNumber\\\\\\\\\\\\\\\":22}]}}}}\\\\\\\"}],\\\\\\\"stackTrace\\\\\\\":{\\\\\\\"callFrames\\\\\\\":[{\\\\\\\"functionName\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"url\\\\\\\":\\\\\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\\\\\",\\\\\\\"scriptId\\\\\\\":\\\\\\\"2\\\\\\\",\\\\\\\"lineNumber\\\\\\\":138,\\\\\\\"columnNumber\\\\\\\":22}]}}}}\\\"}],\\\"stackTrace\\\":{\\\"callFrames\\\":[{\\\"functionName\\\":\\\"\\\",\\\"url\\\":\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\",\\\"scriptId\\\":\\\"2\\\",\\\"lineNumber\\\":138,\\\"columnNumber\\\":22}]}}}}\"}],\"stackTrace\":{\"callFrames\":[{\"functionName\":\"\",\"url\":\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\",\"scriptId\":\"2\",\"lineNumber\":138,\"columnNumber\":22}]}}}}"}],"stackTrace":{"callFrames":[{"functionName":"","url":"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts","scriptId":"2","lineNumber":138,"columnNumber":22}]}}}}`

### What is the expected behavior?

clean

### What do you see instead?

`functionName\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"url\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"scriptId\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"2\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"lineNumber\\\\\\\\\\\\\\\":138,\\\\\\\\\\\\\\\"columnNumber\\\\\\\\\\\\\\\":22}]}}}}\\\\\\\"}],\\\\\\\"stackTrace\\\\\\\":{\\\\\\\"callFrames\\\\\\\":[{\\\\\\\"functionName\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"url\\\\\\\":\\\\\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\\\\\",\\\\\\\"scriptId\\\\\\\":\\\\\\\"2\\\\\\\",\\\\\\\"lineNumber\\\\\\\":138,\\\\\\\"columnNumber\\\\\\\":22}]}}}}\\\"}],\\\"stackTrace\\\":{\\\"callFrames\\\":[{\\\"functionName\\\":\\\"\\\",\\\"url\\\":\\\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\\\",\\\"scriptId\\\":\\\"2\\\",\\\"lineNumber\\\":138,\\\"columnNumber\\\":22}]}}}}\"}],\"stackTrace\":{\"callFrames\":[{\"functionName\":\"\",\"url\":\"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts\",\"scriptId\":\"2\",\"lineNumber\":138,\"columnNumber\":22}]}}}}"}],"stackTrace":{"callFrames":[{"functionName":"","url":"/private/tmp/bunx-502-bun-repl@latest/node_modules/bun-repl/src/repl.ts","scriptId":"2","lineNumber":138,"columnNumber":22}]}}}}`

### Additional information

This only heppens in the VSC terminals. Regular system terminal is fine.

**Comment by RiskyMH** [comment]
@branaway can you try my fix in #15594

```py
# install fixed version from pr
$ bunx bun-pr 15594

# and then use it
$ bun-15594 repl
```

**Comment by branaway** [comment]
> [@branaway](https://github.com/branaway) can you try my fix in [#15594](https://github.com/oven-sh/bun/pull/15594)
> 
> # install fixed version from pr
> $ bunx bun-pr 15594
> 
> # and then use it
> $ bun-15594 repl

Cannot do it. It seems I need an OAuth token for it.

**Comment by RiskyMH** [comment]
Ah fair you need to login with the `gh` cli.

Anyway it's merged into main, so `bun upgrade --canary` should have the fix now (it doesn't need any loging into).

**Comment by branaway** [comment]
It's woking now. Thanks

**Comment by mollthecoder** [comment]
Having this issue on both 1.2.3-canary.51+ba8573494 and 1.2.2+c1708ea6a on Windows
