### ISSUE TITLE
Potential memory leak in http server request handler

### ISSUE THREAD

**Issue by Breadbuddy** [oven-sh/bun#15581]
### What version of Bun is running?

1.1.37

### What platform is your computer?

Linux x64

### What steps can reproduce the bug?

```javascript
Bun.serve({
    fetch (request: Request) {
        const url = request.url;
        return new Response('ok');
    }
})
```

As far as I can see problem appears when request.url is used in any way, inside request handler. In my example I defined const url but I didn't even use it later and that's enough to cause the problem. I've also tried deeply cloning request.url in few ways, cloning whole request and few more. Tried with sync and async fetch. Other properties of request can be used without problem.

### What is the expected behavior?

server memory usage shouldn't increase over time

### What do you see instead?

Memory is increasing like 12mb per 100.000 requests. Infinitely, then server restarts.

Requst.url used:

```javascript
Bun.serve({
    fetch (request: Request) {
        const url = request.url;
        return new Response('ok');
    }
})
```

![Image](https://github.com/user-attachments/assets/2a7daf81-cf4e-4ed0-9549-4243c0fa5c94)

Request.url not being used:

```javascript
Bun.serve({
    fetch (request: Request) {
        // const url = request.url;
        return new Response('ok');
    }
})
```

![Image](https://github.com/user-attachments/assets/91fcc585-9e74-485c-b49f-ffdb6c8893c3)

### Additional information

Currently I am using bun 1.1.37 but it doesn't matter. I was using Bun since 0.X.X and that occured in every version.
App is running in docker container. Official Bun image (oven/bun:1.1.37).
Tried to deploy on few machines with different CPUs. Right now I don't know their exact linux distros but I can check. Problem occurred on every of them.

**Comment by Jarred-Sumner** [comment]
I'm not able to reproduce this. the memory stays the same around 48.4 MB.  We have memory leak tests for the `request.url` inside of `Bun.serve()`'s `fetch()` handler specifically. I tried both on Bun v1.1.37 and on the latest canary build with no meaningful difference.

![Image](https://github.com/user-attachments/assets/23ccb2f5-6666-426a-a8af-a2608b372116)

There must be something else going on, such as a load balancer or HTTP client keeping the connection alive for a long time between requests. I'll re-open once you provide a way for us to reproduce this.

**Comment by Breadbuddy** [comment]
I don't have the error locally on my computers either. I'll try to give you exact platform specification. But bun server code and docker is exactly the same in every environment I test

**Comment by Breadbuddy** [comment]
@Jarred-Sumner all I can say for now is that changing from Bun.serve to Bun's implementation of classic node http server helps.

changed:
```javascript
Bun.serve({
    port: 3333,
    fetch (request) {
        const url = request.url;
        return new Response('ok');
    }
})
```

to:
```javascript
 http.createServer(function (req, res) {
     const url = req.url;
     res.writeHead(200, {'Content-Type': 'text/plain'});
     res.write('ok');
     res.end();
}).listen(3333);
```

Both version are on naked bun image. Without installing anything additionaly.
I will tell you If I will find the way to reproduce it locally.
