### ISSUE TITLE
Bun process.env behaviour not consistent with Node during testing

### ISSUE THREAD

**Issue by dominicporteous** [oven-sh/bun#1559]
### What version of Bun is running?

0.3.0 (needs node:child_process)

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64 i386

### What steps can reproduce the bug?

Behaviour has been captured here: https://github.com/dominicporteous/bun-env

I think the core of this is it is not correctly passing through the `delete process.env.BAR` and as such its value is being made available to the next test (which may expect that value to be empty)

Tests which are manipluating process.env (simulating that env variables are being set and unset for different tests) behave correctly in Node, however in Bun it seems that the unset operations are not being applied and therefore the env variables set are being persisted across test cases.

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Should be able to unset a value on process.env

### What do you see instead?

Attempting to unset the value in the test case will not unset the value for the scope of the next test case

**Comment by dominicporteous** [comment]
FWIW: I have run a small script to test the set/unset of env variables and it seems to work correctly in Bun main, so not sure if this issue is localised to wiptest?

**Comment by dominicporteous** [comment]
This seems to be fixed on latest canary

**Comment by maxmcd** [comment]
I am still seeing this bug, this script:
```ts
process.env.FOO = 1

delete process.env.FOO
delete process.env.SHELL
console.log(process.env.SHELL, process.env.FOO)
process.env.SHELL = "hi"
console.log(process.env.SHELL)
```
Prints the following:
```
$ bun -v
0.5.6
$ bun ./foo.ts 
/bin/bash undefined
/bin/bash
```

Seems modification of env vars that are present when the process starts is not possible?

However, this cannot be reproduced with bun-repl:
```
$ bun x bun-repl
Welcome to Bun.js v0.5.6
Type ".help" for more information.
> process.env.SHELL
'/bin/bash'
> process.env.SHELL = 1
1
> process.env.SHELL
1
> delete process.env.SHELL
true
> process.env.SHELL
undefined
```

@dominicporteous mind re-opening? Or happy to create a new issue.
