### ISSUE TITLE
Implement a bundler designed for production

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#156]
Currently, bun's bundler is best suited to development. It prioritizes compilation speed over bundle size. I want bun's production bundler to prioritize these things:

- bundle size
- runtime performance
- incremental _production_ bundling fast enough to run in an HTTP request
- onLoad/onResolve plugins & plugin performance. This will enable other frameworks like Vue and Svelte to easily work in Bun.
- compilation speed
- hot module reloading

This work has started in [this branch](https://github.com/Jarred-Sumner/bun/tree/jarred/new-bund).

The other thing I want as part of this project is a new bundling format which should support:
- CSS files
- image files & binary assets
- minification
- tree shaking
- sourcemaps

This will be a single binary artifact which can either be run directly for bun.js (makes deploys easy) or be uploaded to a server and then extracted

**Comment by JakeCooper** [comment]
To add to the prod column: 
- disabling watch to prevent needless inode assignment for files that won't change

**Comment by Electroid** [comment]
Closing as a duplicate, since we are tracking bundling here: #121
