### ISSUE TITLE
Implementation of features and correction of important bugs in `bun pm pack` and `bun publish`

### ISSUE THREAD

**Issue by okineadev** [oven-sh/bun#15603]
💡 Important (but not critical) features:

- [ ] #15601 

❌ Bugs in `bun pm pack`:

- [ ] #15602 

---

> This is a kind of roadmap :)

**Comment by okineadev** [comment]
When this is ready, I and many others will be able to fully switch to `bun publish`

**Comment by Electroid** [comment]
Thanks for opening up these issues. We do want you to be able to switch to `bun publish`! Though, we won't need a tracking issue for them, so going to close this out and keep the issues you posted.
