### ISSUE TITLE
Segfault issue with wiptest

### ISSUE THREAD

**Issue by dominicporteous** [oven-sh/bun#1561]
### What version of Bun is running?

0.3.0 (7b59d9d9)

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64 i386

### What steps can reproduce the bug?

- Download repo: https://github.com/dominicporteous/bun-commander
- Run command: `bun wiptest` (same behaviour is observed with `bun wiptest tests/`)

Results in;

```
bun wiptest v0.3.0 (7b59d9d9)
...

command.help.test.js:
Segmentation fault: 11
```

When running the file mentioned standalone (`bun wiptest tests/command.help.test.js`), this does not occur
```
bun wiptest v0.3.0 (7b59d9d9)

command.help.test.js:
...

30 pass
0 fail
39 expect() calls
Ran 30 tests across 1 files [261.00ms]
```

### How often does it reproduce? Is there a required condition?

Occurs every time

### What is the expected behavior?

The `bun wiptest` command to run all the test files without a segfault

If you run the files seperatley, or in a batch (e.g. `ls tests/*.test.js | xargs -L 1 bun wiptest`) there is no seg fault and all tests pass (verified with exit code 0)

### What do you see instead?

Segmentation fault: 11

**Comment by Jarred-Sumner** [comment]
Looks like this hit a code path in the transpiler which is not implemented yet? Investigating

```

uh-oh: Not implemented yet!!
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.3.0_debug (b631ea7d) macOS Silicon 21.6.0
TestCommand: 
Elapsed: 3786ms | User: 999ms | Sys: 677ms
RSS: 70.03MB | Peak: 70.03MB | Commit: 69.22MB | Faults: 0
----- bun meta -----
```

**Comment by dominicporteous** [comment]
@Jarred-Sumner This seems to be resolved on the latest canary.
