### ISSUE TITLE
Packet losses in Websocket

### ISSUE THREAD

**Issue by fir4tozden** [oven-sh/bun#15647]
### What version of Bun is running?

1.1.33+247456b67

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Send 1 million packets to the client that connects to the Websocket server using bun.serve using a for loop

### What is the expected behavior?

Trouble-free transmission of all packets

### What do you see instead?

Incomplete and hundreds of thousands of undelivered packets

### Additional information

This problem only happens on the Bun.serve websocket server. If you use the ws library from NPM you won't encounter any problems. This is a big problem that needs to be fixed.

![Image](https://github.com/user-attachments/assets/4056874b-d4e5-4822-b0df-edfc1e2eeb50)
![Image](https://github.com/user-attachments/assets/87b759b9-1b8b-40ba-8edc-6543433ed468)
![Image](https://github.com/user-attachments/assets/b3df5aa2-4436-47fb-9aae-f704e9f3ce8e)

**Comment by evanwashere** [comment]
you need to handle backpressure when sending messages to clients https://bun.sh/docs/api/websockets#backpressure

**Comment by fir4tozden** [comment]
Yes, I found the problem. Actually, this is an additional security measure. Bun starts dropping packets if there is a packet sending sequence between a client and a server that exceeds 1 MB. Actually, you can send 1 million packets to different people, but when you try to send to 1 person, Bun sees it as an attack and blocks it. You can increase the limit if you want, but it is not necessary.

If you want to detect this, check this out: https://bun.sh/docs/api/websockets#backpressure

You can change this limit with the `backpressureLimit` value.

```js
Bun.serve({
  fetch(req, server) {
    if (server.upgrade(req)) return;
  },

  websocket: {
    open(socket) { ... }
    backpressureLimit: 1 * 1024 * 1024 // (1 MB)
  },

  port: 8080
})
```
