### ISSUE TITLE
Segmentation fault at address 0x00000000

### ISSUE THREAD

**Issue by filipduch** [oven-sh/bun#15640]
### How can we reproduce the crash?

Don't know how to reproduce. Possibly there were some changes to incoming requests parsing/handling that are causing this

My setup:
docker-compose with ngnix and 4 bun web workers. The incoming request(s) crashed all of the web workers at the same time (nginx passes the request to next healthy instance after instance fails). Nginx handles SSL so bun workers are getting the request via plain http.

I upgraded from 1.1.34 to 1.1.38 and this is happening like twice a day - I'm rolling back to 1.1.34 as I didn't have the issue there.

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.38 ([`bf2f153`](<https://github.com/oven-sh/bun/tree/bf2f153f5ca45876bc88369273743cd6fa04881c>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/ld-temp.o#L0>): `JSValueUnprotect`
- [`javascript_core_c_api.zig:89`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/bun.js/javascript_core_c_api.zig#L89>): `src.bun.js.api.bun.socket.Handlers.unprotect`
- [`socket.zig:193`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/bun.js/api/bun/socket.zig#L193>): `src.bun.js.api.bun.socket.NewSocket`
- [`socket.zig:3648`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/bun.js/api/bun/socket.zig#L3648>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:1869`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/crypto/openssl.c#L1869>): `ssl_wrapped_context_on_close`
- [`openssl.c:433`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/crypto/openssl.c#L433>): `ssl_on_close`
- [`socket.c:218`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/socket.c#L218>): `us_socket_close`
- [`openssl.c:0`](<https://github.com/oven-sh/bun/blob/bf2f153f5ca45876bc88369273743cd6fa04881c/src/crypto/openssl.c#L0>): `ssl_on_data`

Features: napi\_module\_register, process\_dlopen, Bun.stdout, abort\_signal, dotenv, fetch, http\_server, jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6117758318/">BUN-9F3</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
I think this was fixed in Bun v1.1.40+, we fixed some issues related to TCP/TLS socket lifetime of upgraded sockets.

Please let us know if you still run into this after upgrading and I'll reopen.
