### ISSUE TITLE
Option to hide the console window for single-file executables

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [oven-sh/bun#15664]
### What is the problem this feature would solve?

I'm making an app that utilizes another framework to display GUI to users (Neutralino), with Bun being the main process that launches this GUI and orchestrates everything.
When a packaged bun application is run, however, it creates a console window — understandable in most cases, but not quite needed as I am not making a CLI app but a visual one.

I also intend to release the structure and build tools I've made as an open-source alternative to electron and nw.js, as Bun and Neutralino make quite a good combo for making cross-platform desktop apps.

### What is the feature you are proposing to solve the problem?

In `bun build --compile`, it would be great to add a flag to prevent the console window to pop up, or at least to hide it when a Bun application fully initializes. Something like `--no-window` or `--silent`, perhaps?

### What alternatives have you considered?

Coding a launcher file in Go or such that will run Bun as a subprocess.

**Comment by pfgithub** [comment]
Tracked in #13084, follow that issue for updates
