### ISSUE TITLE
error: No version matching

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#15663]
### What version of Bun is running?

1.1.33-canary.16+6f60523e6

### What platform is your computer?

Linux 6.8.0-49-generic x86_64 x86_64

### What steps can reproduce the bug?

![Image](https://github.com/user-attachments/assets/75ac3f9a-fd15-4179-aae6-25b04ddd31e7)

### What is the expected behavior?

works with pnpm

**Comment by nektro** [comment]
![Image](https://github.com/user-attachments/assets/79592323-a0e5-467b-97ec-92f34cc721f3)

does this work if you upgrade to the lastest version of bun?

**Comment by huseeiin** [comment]
> ![Image](https://github.com/user-attachments/assets/79592323-a0e5-467b-97ec-92f34cc721f3)
> 
> does this work if you upgrade to the lastest version of bun?

yes its fixed
