### ISSUE TITLE
Prepublish script is not executing during bun publish

### ISSUE THREAD

**Issue by GenrikhFetischev** [oven-sh/bun#15681]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Linux  x86_64

### What steps can reproduce the bug?

Hello!

I’ve encountered an issue where the prepublish script defined in the package.json file is not being executed before publishing when running the bun publish command.

I reviewed the Bun documentation but couldn’t find any specific mention of whether this behavior is expected. My assumption is that lifecycle scripts, such as prepublish, should behave consistently with other package managers (e.g., npm, PNPM, Yarn), where they are executed automatically as part of the publishing process.

Could you clarify whether this is intentional behavior or a potential bug? If it is intentional, I suggest adding this detail to the documentation for clarity.

### What is the expected behavior?

Bun call `prepublish` script before publishing as part of `bun publish` execution 

### What do you see instead?

`prepublish` script not being executed

**Comment by nektro** [comment]
this is the expected behavior https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-publish
