### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by its-dorra** [oven-sh/bun#15717]
### How can we reproduce the crash?

panic(thread 22764): Segmentation fault at address 0x20C8D9773C8      
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.32 ([`fe8d007`](<https://github.com/oven-sh/bun/tree/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x20C8D9773C8

- [`core.c:173`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/win/core.c#L173>): `uv__wake_all_loops`
- [`detect-wakeup.c:41`](<https://github.com/oven-sh/bun/blob/fe8d0079ecdfeb61cea6ba041ed6845d6fffa43e/src/win/detect-wakeup.c#L41>): `uv__system_resume_callback`

Features: workers\_spawned, workers\_terminated, dotenv, http\_server, jsc, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5679205923/">BUN-3NV</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
This issue is very likely caused by `Worker`. 

We are tracking Worker stability in #15964
