### ISSUE TITLE
Compatibility issues with react-scan

### ISSUE THREAD

**Issue by notSagyo** [oven-sh/bun#15783]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Windows

### What steps can reproduce the bug?

`bunx react-scan@latest http://localhost:3000/`

### What is the expected behavior?

Should start scanning as with `npx react-scan@latest http://localhost:3000/`

### What do you see instead?

```
  ⚙️  esbuild [1/2] error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

### Additional information

I don't know if this is directly related to Node.js compatibility with Bun, but it seems to work with any other Package Manager.

**Comment by kravetsone** [comment]
Its not about Node.js compatibility 
Its old bug on windows with postinstall scripts
