### ISSUE TITLE
Bun.file on a nonexistent file segfaults

### ISSUE THREAD

**Issue by u9g** [oven-sh/bun#1578]
### What version of Bun is running?

0.3.0 canary

### What platform is your computer?

Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

run `console.log(await (await Bun.file(require('path').join(import.meta.dir, 'a.a')).text()))` if the `a.a` file doesn't exist.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Don't segault

### What do you see instead?

It segfaults

### Additional information

Jarred: Mention “stack buffer path text error object Bun.file().text()l

context: https://discord.com/channels/876711213126520882/1049061422086234255/1049075240719892510

**Comment by Electroid** [comment]
@robobun 

```js
console.log(await Bun.file("blah.txt").text());
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
error: ENOENT
   path: "blah.txt"
syscall: "open"
```
<details>
  <summary>Code</summary>
  
```tsx
console.log(await Bun.file("blah.txt").text());
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Electroid** [comment]
@robobun 

```js
console.log(Bun.revision);
console.log(await Bun.file("blah.txt").text());
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
c7f411bd88bf9443f1133b2c24fd018250f80541
error: ENOENT
   path: "blah.txt"
syscall: "open"
```
<details>
  <summary>Code</summary>
  
```tsx
console.log(Bun.revision);
console.log(await Bun.file("blah.txt").text());
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Jarred-Sumner** [comment]
I think this happens in some situation where io_uring is unsupported on the machine

**Comment by Jarred-Sumner** [comment]
@u9g can you let us know if this issue remains in Bun v0.3.0/v0.3.1?

**Comment by u9g** [comment]
> @u9g can you let us know if this issue remains in Bun v0.3.0/v0.3.1?

Works fine now, in latest canary.
