### ISSUE TITLE
throwIfNoEntry isn't acknowledged in fs.statSync

### ISSUE THREAD

**Issue by miklosme** [oven-sh/bun#1579]
### What version of Bun is running?

0.2.2

### What platform is your computer?

Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64 arm

### What steps can reproduce the bug?

```js
import fs from 'fs';

fs.statSync('file_that_does_not_exist', {
  throwIfNoEntry: false,
});

console.log('done');
```

The above code reaches the console.log in Node, but throws in Bun.

**Comment by Jarred-Sumner** [comment]
This has been fixed in Bun v0.6.14
