### ISSUE TITLE
Bun.write Behavior with Response and Streams

### ISSUE THREAD

**Issue by bradleat** [oven-sh/bun#15796]
### What version of Bun is running?

1.1.38

### What platform is your computer?

Linux 6.10.14-linuxkit aarch64 unknown

### What steps can reproduce the bug?

1. Create a file at the input path (e.g., /tmp/input.file.
2. Attempt to write it to an output path using the two methods below:

```
const inputPath = '/tmp/nkrmix_01jf1jkw3tfqea21zz2q8kkjxw.intermix.m4a';
const outputPath = '/tmp/inkibra/media/mixes/nkrmix_01jf1jm3phfqea22190qrjpw3r.m4a';

// Method: As documented, hangs and never completes
await Bun.write(outputPath, new Response(Bun.file(inputPath).stream()));
console.log('done');
```

### What is the expected behavior?

- Bun.write completes successfully and logs “done ,” consistent with the documentation.

### What do you see instead?

- Hangs indefinitely and never completes, failing to write the file.

### Additional information

	•	The documentation suggests that wrapping a ReadableStream in a Response is a supported input for Bun.write. However, this behavior doesn’t work as expected.

Please clarify:
	1.	Should Bun.write support Response wrapping a ReadableStream as documented?
	2.	If so, is this a bug with how Bun.write handles the Response object or its stream?
	3.	Update TypeScript type definitions to better align with the actual behavior.

**Comment by cirospaciari** [comment]
Bun can handle some response streams like:
```js
await Bun.write(fetch(url));
```
but not all scenarios today, I have a PR open with some improvements, and more will come after it.

Duplicated of https://github.com/oven-sh/bun/issues/13237 PR related: https://github.com/oven-sh/bun/pull/15631

**Comment by bradleat** [comment]
@cirospaciari 
Thanks for the context here.
What I'm gathering is that you all are already aware of the failure here: `await Bun.write(outputPath, new Response(Bun.file(inputPath).stream())); and you are addressing it in that upcoming PR.
