### ISSUE TITLE
Crash when running "bun install"

### ISSUE THREAD

**Issue by robicruzo** [oven-sh/bun#15799]
### `package.json` file

```json
{
  "name": "reacttic",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "reacttic": "file:"
  },
  "devDependencies": {
    "@eslint/js": "^9.15.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.4",
    "eslint": "^9.15.0",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.14",
    "globals": "^15.12.0",
    "vite": "^6.0.1"
  }
}
```

### How can we reproduce the crash?

Just trying to start a new project with vite. The crash happened when I ran "bun install."

### Relevant log output

```shell
bun install v1.1.33 (247456b6)
[10.87ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.33 (247456b6) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\robse\.bun\bin\bun.exe" "install"
Features: lockfile_migration_from_package_lock
Elapsed: 54ms | User: 0ms | Sys: 0ms
RSS: 65.76MB | Peak: 65.76MB | Commit: 110.78MB | Faults: 16257

panic(main thread): Internal assertion failure: unexpected resolution tag
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure: unexpected resolution tag

- [`install.zig:12918`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L12918>): `installPackageWithNameAndResolution`
- [`install.zig:13240`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L13240>): `installPackage`
- [`install.zig:13704`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L13704>): `installPackages`
- [`install.zig:14536`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L14536>): `installWithManager`
- [`install.zig:11993`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/install/install.zig#L11993>): `install`
- [`cli.zig:1676`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/cli.zig#L1676>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/src/startup/exe_common.inl#L78>): `invoke_main`

Features: lockfile\_migration\_from\_package\_lock

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5622674357/">BUN-2FG</a></strong></sub>

**Comment by dylan-conway** [comment]
Fixed in Bun v1.1.34 with #14811. Run `bun upgrade` to get the latest version. Please re-open or create a new issue if you continue to see this bug, or have a related issue.
