### ISSUE TITLE
package.json scripts not running

### ISSUE THREAD

**Issue by MarioEPrieto** [oven-sh/bun#15819]
### What is the issue?

In the Bun quickstart it says that we can run "scripts" in package.json.  I created a scripts section in packagejson just like the documentation says, but when I run it says "Script not found". I din't want to put it as a bug because it seems so simple. I am new to Bun so forgive me if I am missing something simple.

<img width="964" alt="Image" src="https://github.com/user-attachments/assets/d54683f6-0cc6-44bb-bcd2-76cf8120d42f" />

**Comment by MarioEPrieto** [comment]
Also when I run "bun run" it says 'No "scripts" found in package.json

My computer is MacBook Air M1 in case it matters

**Comment by Erb3** [comment]
You typoed, `"scripts:":` vs `"scripts":`.

```diff
-"scripts:": {
+"scripts": {
```
