### ISSUE TITLE
Support native module loading without "node:<pkg name>" module loading

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#1582]
### What version of Bun is running?

0.3.0 (just installed via canary)

### What platform is your computer?

Linux 5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

```js
import dns from "dns"
```
This above code works on nodejs, providing the native node module, but won't work on Bun, unless you change it to `node:dns`
Maybe you guys can add a polyfill to work around this? Looks like fastify and a lot of packages uses the old way and didn't move to the new nodejs way of importing like `node:<native pkg name>`.

### What do you see instead?

```js
import dns from "dns";
                ^
/home/user/coding/benchmarks/fastify/index.js:1:17 16
```

**Comment by Jarred-Sumner** [comment]
dns isn't implemented yet

**Comment by ken0x0a** [comment]
Duplicate of #288
Good to close

**Comment by renhiyama** [comment]
@Jarred-Sumner & @ken0x0a my bad, i already know dns isnt available, but we cant use `dns` instead of using `node:dns` or any similar packages? or what? a lot of old pkgs use that type instead of the current "node:dns" way

**Comment by Jarred-Sumner** [comment]
This works

The packages where this doesn't work are just not implemented yet.
