### ISSUE TITLE
Error on run puppeteer after compile

### ISSUE THREAD

**Issue by rianaditro** [oven-sh/bun#15830]
### How can we reproduce the crash?

I leave the log below, i dont understand

### Relevant log output

```shell
Bun v1.1.39 (1d485617) Linux x64
Linux Kernel v5.15.0 | glibc v2.35
CPU: sse42 popcnt avx avx2
Args: "./cli"
Features: jsc standalone_executable tsconfig tsconfig_paths 
Builtins: "bun:main" "node:buffer" "node:crypto" "node:fs" "node:os" "node:path" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:util" "node:util/types" 
Elapsed: 539ms | User: 493ms | Sys: 56ms
RSS: 1.07GB | Peak: 87.34MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x10070
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.39/l_11d48561Chgg8/3DoqqomE+xyQm2yk+D4juiiE_gm7j8Dm8477Duygy6Eq7ti+Dqwin+DA2AgngE

[1]    13649 illegal hardware instruction (core dumped)  ./cli
```

### Stack Trace (bun.report)

Bun v1.1.39 ([`1d48561`](<https://github.com/oven-sh/bun/tree/1d4856170978abe3aa47960e2fd7d4f400423808>)) on linux x86_64 [_]

Segmentation fault at address 0x00010070

- [`BunProcess.cpp:1065`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/src/bun.js/bindings/BunProcess.cpp#L1065>): `Bun::onDidChangeListeners`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/./build/release-ci/cache/webkit-58549ddc4d9e7164823fe9d4e86c46c003e46a19/include/wtf/Function.h#L53>): `WebCore::JSEventEmitter::addListener`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`BunProcess.cpp:1907`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/src/bun.js/bindings/BunProcess.cpp#L1907>): `Bun::constructStdioWriteStream`
- [`Lookup.h:540`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/./build/release-ci/cache/webkit-58549ddc4d9e7164823fe9d4e86c46c003e46a19/include/JavaScriptCore/Lookup.h#L540>): `JSC::reifyStaticProperty`

Features: jsc, standalone\_executable, tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6152811394/">BUN-9Y5</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in #15825 

Please run `bun upgrade --canary` or wait about 3 hours and run `bun upgrade`
