### ISSUE TITLE
Importing better-sqlite3 causes crash

### ISSUE THREAD

**Issue by vedantroy** [oven-sh/bun#15834]
### What version of Bun is running?

1.1.33+247456b67

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

```
import Database from "better-sqlite3"
new Database("foo")
```

### What is the expected behavior?

It works.

### What do you see instead?

dyld[65247]: missing symbol called

### Additional information

Question -- can I just import from `bun:sqlite` as a drop-in replacement for `better-sqlite3`?

**Comment by 190n** [comment]
This happens because better-sqlite3 uses V8 APIs that Bun doesn't support yet. You can track our progress on V8 in issue #4290.

> can I just import from bun:sqlite as a drop-in replacement for better-sqlite3?

The APIs aren't exactly the same.
