### ISSUE TITLE
NestJS - Segmentation fault at address 0x10070

### ISSUE THREAD

**Issue by DoKoB0512** [oven-sh/bun#15850]
### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.39 ([`1d48561`](<https://github.com/oven-sh/bun/tree/1d4856170978abe3aa47960e2fd7d4f400423808>)) on linux x86_64 [_]

Segmentation fault at address 0x00010070

- [`BunProcess.cpp:1065`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/src/bun.js/bindings/BunProcess.cpp#L1065>): `Bun::onDidChangeListeners`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/./build/release-ci/cache/webkit-58549ddc4d9e7164823fe9d4e86c46c003e46a19/include/wtf/Function.h#L53>): `WebCore::JSEventEmitter::addListener`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`BunProcess.cpp:1907`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/src/bun.js/bindings/BunProcess.cpp#L1907>): `Bun::constructStdioWriteStream`
- [`Lookup.h:540`](<https://github.com/oven-sh/bun/blob/1d4856170978abe3aa47960e2fd7d4f400423808/./build/release-ci/cache/webkit-58549ddc4d9e7164823fe9d4e86c46c003e46a19/include/JavaScriptCore/Lookup.h#L540>): `JSC::reifyStaticProperty`

Features: jsc, standalone\_executable, tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6152811394/">BUN-9Y5</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed in v1.1.40
