### ISSUE TITLE
Bun documentation on .npmrc file is inconsistent

### ISSUE THREAD

**Issue by markgarrigan** [oven-sh/bun#15856]
### What is the issue?

This page says bun support .npmrc files.
https://bun.sh/docs/install/npmrc

This page says bun does not support .npmrc files.
https://bun.sh/guides/install/registry-scope

### Where did you find it?

https://bun.sh/docs/install/npmrc
https://bun.sh/guides/install/registry-scope

**Comment by Jarred-Sumner** [comment]
We do support .npmrc, the guide is outdated
