### ISSUE TITLE
Bun Install does not use the correct registry

### ISSUE THREAD

**Issue by markgarrigan** [oven-sh/bun#15855]
### What version of Bun is running?

1.1.40+b5b51004e

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

Create a .npmrc in the project directory

.npmrc
```
registry=https://repo1.redacted.com/artifactory/api/npm/npm-virtual
```

run `bun install`

bun install returns

```
error: GET https://repo1.redacted.com/artifactory/api/npm/mysql2 - 404
error: GET https://repo1.redacted.com/artifactory/api/npm/multer - 404
```

It's dropping the npm-virtual part of the registry url.

### What is the expected behavior?

To use the exact url I specify as the registry.

### Additional information

I can create another bug for this, but on a side note... The bunfig.toml seems to be ignored by bun install if there's a .npmrc file present somewhere. For me I have an .npmrc file in my home directory. bun install will always use that file if the only file I have in my project is a bunfig.toml.

**Comment by Jarred-Sumner** [comment]
Did oyu mean to close this as completed?

**Comment by markgarrigan** [comment]
I think I meant to withdraw it. I figured it out. But, I can't remember what I did now to make it work.

**Comment by arcuo** [comment]
For me it worked by adding a ending slash: ".../npm-virtual/"

```
registry=https://repo1.redacted.com/artifactory/api/npm/npm-virtual/
```
