### ISSUE TITLE
Bun freezes OS when new Array(4096*8) is handled by readSync() and process.stdin.write()

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#1587]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Linux 5.15.0-43-generic ... x86_64 x86_64

### What steps can reproduce the bug?

Send `new Array(4096*8)` to Native Messaging host from Chromium or Chrome

nm_bun.js
```
#!bun
// Bun Native Messaging host

import {readSync} from 'node:fs';

function getMessage() {
  const header = new Uint32Array(1);
  readSync(0, header);
  const content = new Uint8Array(header[0]);
  readSync(0, content);
  return content;
}

function sendMessage(json) {
  let header = Uint32Array.from({
    length: 4,
  }, (_,index)=>(json.length >> (index * 8)) & 0xff);
  let output = new Uint8Array(header.length + json.length);
  output.set(header, 0);
  output.set(json, 4);
  process.stdout.write(output);
  header = output = null;
}

function main() {
  while (true) {
    try {
      const message = getMessage();
      sendMessage(message);
    } catch (e) {
      process.exit();
    }
  }
}

main();
```

background.js

```
globalThis.name = chrome.runtime.getManifest().short_name;

globalThis.port = chrome.runtime.connectNative(globalThis.name);
port.onMessage.addListener((message) => console.log(message));
port.onDisconnect.addListener((p) => console.log(chrome.runtime.lastError));
port.postMessage(new Array(4096*8));

chrome.runtime.onInstalled.addListener((reason) => {
  console.log(reason);
});
```
manifest.json

```
{
  "name": "nm-bun",
  "short_name": "nm_bun",
  "version": "1.0",
  "manifest_version": 3,
  "description": "Bun Native Messaging host",
  "permissions": ["nativeMessaging"],
  "background": {
    "service_worker": "background.js",
    "type": "module"
  },
  "action": {}
}
```

nm_bun.json

```
{
  "name": "nm_bun",
  "description": "Bun Native Messaging Host",
  "path": "/path/to/native-messaging-bun/nm_bun.js",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://<id>/"
  ]
}
```

### How often does it reproduce? Is there a required condition?

Consistently. Yes, when passing `new Array(4096*8)` to the Native Messaging host.

### What is the expected behavior?

Bun to process the input similar to how Node.js, Deno, QuickJS process the data. Node.js does have an issue with processing input greater than 65535 length, see https://github.com/nodejs/node/issues/6456 and https://github.com/nodejs/node/issues/11568#issuecomment-282765300.

I don't think Bun has 

```
process.stdout._handle.setBlocking(true);
```

### What do you see instead?

```
{message: 'Error when communicating with the native messaging host.'}
```

before the OS freezes. Then I need to - when possible - open a new TTY and sign in again.

### Additional information

I suggest thoroughly testing at least 65535 length input to `readSync()` and output from `process.stdout.write()`.

To install the Native Messaging host copy nm_bun.json to NativeMessagingHosts in Chrome or Chromium configuration directory. Make sure nm_bun.js is marked executable, and the path points to the file, then load the extension, take note of the generated extension ID and write chrome-extension://\<id\>/ in nm_bun.json. Reload the extension, inspect the background `ServiceWorker` using DevTools.

**Comment by Jarred-Sumner** [comment]
As a workaround, try using 

var writer = Bun.stdout().writer() 
writer.write(myArry) 

There is better test coverage for Bun.stdout.writer() than node's APIs for this currently

**Comment by guest271314** [comment]
I'll try. Last time I tried `Bun` methods didn't work https://github.com/oven-sh/bun/issues/1297. I've been checking in here periodically to see if you folks implemented working `stdout`, `stdin`. I read where you signed off on the Node.js implementation, with appparent hesitancy.

**Comment by guest271314** [comment]
> As a workaround, try using
> 
> var writer = Bun.stdout().writer() writer.write(myArry)

That just exists immediately 

```
{message: 'Native host has exited.'}
```

**Comment by Jarred-Sumner** [comment]
What is the file type? We’ve tested files & pipes /  FIFOs mostly. Is it a socket? Sockets haven’t been tested for this yet

**Comment by guest271314** [comment]
I'm testing Bun as a Native Messaging host https://developer.chrome.com/docs/apps/nativeMessaging/.

Ultimately the communication is JSON or a JSON-_like_ Chrome implementation.

So far I have written Native Messaging hosts in several prgramming languages. Using JavaScript with Node.js, Deno, and QuickJS, where I post `new Array(200000)` from client to host and get the input back at the client.

**Comment by Jarred-Sumner** [comment]
The file descriptor has an underlying representation though for the file  - a physical file on disk, a pipe, a domain socket, a named pipe, etc. require(“fs”).fstat(1) will tell you 

It sounds like this is likely a socket and that Bun.stdout will need changes to support writing to sockets 

We do have a TCP socket api but no way to connect domain sockets currently

**Comment by guest271314** [comment]
Which file are you referring to?

This is the Native Messaging protocol https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-protocol, see https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/messaging/native_message_host.h

**Comment by guest271314** [comment]
When I tested previously Bun's stdio read and write didn't work at all as a Native Messaging host. Now, at least messages are processed - as long as we don't write 4096*8 (32768, or `JSON.stringify(new Array(4096*8)).length`, 163841) of data from the browser to the Bun Native Messaging host. QuickJS https://github.com/guest271314/native-messaging-quickjs and Deno https://github.com/guest271314/native-messaging-deno process 200000. The only way `node` executable processes 65535 input is when `process.stdout._handle.setBlocking(true)` https://github.com/guest271314/native-messaging-nodejs/blob/main/nm_nodejs.js#L11 is called at the top of the script, so I'm not sure Bun wants to be emulating Node.js re stdin and stdout.

The issue here is Bun freezes the entire OS when processesing only 163841 (plus 4 for message header) of input to the Bun Native Messaging host.

**Comment by guest271314** [comment]
There is a memory leak. RSS remains around 30MB for input to Native Messaging host read by `readSync()` and intended to be written back to host with process.stdout.write()` when input is `new Array(4096*2)`, `new Array(4096*3)`. When input is `new Array(4096*4)` RSS increases to 1.8GB.

**Comment by guest271314** [comment]
Interestingly Node.js and Deno (V8) JavaScript engines appears to be exhibiting similar beaviour. No changes to C, C++, QuickJS I/O.

**Comment by guest271314** [comment]
Getting close using this code https://github.com/denoland/deno/discussions/17236#discussioncomment-4566134.

I don't know why I can process the last 4 bytes of data up to 1024*1024. I should be able to pass `port.postMessage(new Array(209715))` from the browser. Right now `port.postMessage(new Array(209714))` (1048571 length) works as expected, `port.postMessage(new Array(209714))` (1048576) hangs. 

Any idea why Bun hangs on 1024*1024, not (1024*1024)-4 writing to stdout?

```
#!bun
// Bun Native Messaging host
// guest271314, 10-9-2022
import {readSync} from 'node:fs';

function readFullSync(fd, buf) {
  let offset = 0;
  while (offset < buf.byteLength) {
    offset += readSync(fd, buf, { offset });
  }
  return buf;
}

function getMessage() {
  const header = new Uint32Array(1);
  readFullSync(0, header);
  const content = new Uint8Array(header[0]);
  readFullSync(0, content);
  return content;
}

function sendMessage(json) {
  let header = Uint32Array.from({
    length: 4,
  }, (_,index)=>(json.length >> (index * 8)) & 0xff);
  let output = new Uint8Array(header.length + json.length);
  //await Bun.write(Bun.file('log.txt')
  // , [json.length, JSON.stringify(header)]);
  output.set(header, 0);
  output.set(json, 4);
  process.stdout.write(output);
  // Mitigate RSS increasing expotentially for multiple messages
  // between client and host during same connectNative() connection
  // header = output = null;
  // global.gc();
}

function main() {
  while (true) {
    try {
      const message = getMessage();
      sendMessage(message);
    } catch (e) {
      process.exit();
    }
  }
}

main();

```

**Comment by guest271314** [comment]
Processing stdout of 1048576 length only works intermittenly. Is there some kind of caching that is going on?

**Comment by guest271314** [comment]
Solved. I think the issue, at least using Bun, was sending a `Uint32Array` having length `4` instead of `1`.

```
#!/usr/bin/env -S ./bun run --no-install --hot
// Bun Native Messaging host
// guest271314, 10-9-2022
import {readSync} from 'node:fs';

function readFullSync(fd, buf) {
  let offset = 0;
  while (offset < buf.byteLength) {
    offset += readSync(fd, buf, { offset });
  }
  return buf;
}

function getMessage() {
  const header = new Uint32Array(1);
  readFullSync(0, header);
  const content = new Uint8Array(header[0]);
  readFullSync(0, content);
  return content;
}

function sendMessage(json) {
  // https://github.com/denoland/deno/discussions/17236#discussioncomment-4566134
  const header = new Uint32Array([json.length]);
  /*
  // Long form
  const header = new Uint32Array([
    ((uint32) =>     
      // https://stackoverflow.com/a/58288413
      (uint32[3] << 24) 
      | (uint32[2] << 16) 
      | (uint32[1] << 8) 
      | (uint32[0])
      )(Array.from({
        length: 4,
      }, (_,index)=>(json.length >> (index * 8)) & 0xff)
    )
  ]);
  */
  Bun.write(Bun.file('log.txt')
  , [json.length, JSON.stringify(header));
  process.stdout.write(new Uint8Array(header.buffer));
  process.stdout.write(json);
  Bun.gc(true);
}

function main() {
  while (true) {
    try {
      const message = getMessage();
      sendMessage(message);
    } catch (e) {
      process.exit();
    }
  }
}

main();
```
