### ISSUE TITLE
Code comments containing "#bun" causes Bun to not parse TypeScript

### ISSUE THREAD

**Issue by dtinth** [oven-sh/bun#15884]
### What version of Bun is running?

1.1.40+b5b51004e

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

Run this:

```ts
// https://bun.sh/docs/api/http#bun-serve
const a: string = "hello";
console.log(a);
```

### What is the expected behavior?

Output should be:

```
hello
```

### What do you see instead?

SyntaxError is thrown:

```
1 | // https://bun.sh/docs/api/http#bun-serve
2 | const a: string = "hello";
    ^
SyntaxError: Unexpected token ':'. const declared variable 'a' must have an initializer.
      at <parse> (/Users/dtinth/Projects/elysia-by-example/hello.ts:2:1)
      at native:11:43
note: missing sourcemaps for /Users/dtinth/Projects/elysia-by-example/hello.ts
note: consider bundling with '--sourcemap' to get unminified traces

Bun v1.1.40 (macOS arm64)
```

### Additional information

The repro case can be reduced to:

```ts
// #bun
const a: string = "hello";
console.log(a);
```

Without the comment, it works:

```ts
const a: string = "hello";
console.log(a);
```

With the comment not containing `#bun`, it works:

```ts
// https://bun.sh/docs/api/http#fetch-request-handler
const a: string = "hello";
console.log(a);
```

With the comment containing `#bun` immediately followed by an alphanumeric character, it works:

```ts
// #bunlai
const a: string = "hello";
console.log(a);
```

**Comment by dtinth** [comment]
Thanks for a speedy fix! 🙏

**Comment by Jarred-Sumner** [comment]
We had to revert it due to a regression it caused, but we'll likely get it into the following release
