### ISSUE TITLE
Bun Crash with worker threads

### ISSUE THREAD

**Issue by KrishnaPG** [oven-sh/bun#15890]
### How can we reproduce the crash?

When worker thread is terminated in a pool, causing the Bun to crash. This is happening with the https://github.com/poolifier/poolifier-web-worker/blob/e99582f4b4331b6d7ab53d2f0cf691378acb6aab/src/pools/worker-node.ts#L159C17-L159C26

### Relevant log output

```shell
Features: Bun.stdin(34) jsc transpiler_cache(2) tsconfig(2) workers_spawned(16) workers_terminated(16)
Builtins: "bun:main" "node:buffer" "node:fs" "node:fs/promises" "node:os" "node:path" "node:process" "node:string_decoder" "node:util/types" "node:worker_threads"
Elapsed: 5689ms | User: 2515ms | Sys: 2343ms
RSS: 0.35GB | Peak: 0.81GB | Commit: 0.52GB | Faults: 204942

panic(thread 4108): Segmentation fault at address 0x211E6C44800
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00010060

- [`atomic.zig:100`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L100>): `fetchOr`
- [`utility:762`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/utility#L762>): `std::exchange`
- [`ZigSourceProvider.cpp:149`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/ZigSourceProvider.cpp#L149>): `Zig::SourceProvider::~SourceProvider`
- [`HashTable.h:1202`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/WebKitBuild/WTF/Headers/wtf/HashTable.h#L1202>): `WTF::HashTable<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::KeyValuePair<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > >,WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > > >,WTF::DefaultHash<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashMap<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> >,WTF::DefaultHash<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashTraits<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashTraits<WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > >,WTF::HashTableTraits,0>::KeyValuePairTraits,WTF::HashTraits<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,0>::deallocateTable`
- [`VM.cpp:520`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/VM.cpp#L520>): `JSC::VM::~VM`
- [`VM.h:297`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/windows-x64-build-cpp/webkit-9b84f43643eff64ab46daec9b860de262c80f5e2/include/JavaScriptCore/VM.h#L297>): `JSC::VM::operator delete`
- [`web_worker.zig:475`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/web_worker.zig#L475>): `exitAndDeinit`
- [`web_worker.zig:369`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/web_worker.zig#L369>): `spin`
- [`bindings.cpp:4855`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/bindings.cpp#L4855>): `JSC__VM__holdAPILock`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/shimmer.zig#L197>): `cppFn`

Features: workers\_spawned, workers\_terminated, Bun.stdin, jsc, transpiler\_cache, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6163107895/">BUN-A25</a></strong></sub>

**Comment by KrishnaPG** [comment]
Upgraded to the latest and still same issue. 

### Stack Trace (bun.report)

Bun v1.1.40 ([`b5b5100`](<https://github.com/oven-sh/bun/tree/b5b51004e8de80dcd43849e4da1d2623ee3d3008>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x20D72024788

- [`ZigGlobalObject.h:292`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/bindings/ZigGlobalObject.h#L292>): `Zig::GlobalObject::bunVM`
- [`ZigSourceProvider.cpp:149`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/bindings/ZigSourceProvider.cpp#L149>): `Zig::SourceProvider::~SourceProvider`
- [`HashTable.h:1204`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/C:/a/WebKit/WebKit/WebKitBuild/WTF/Headers/wtf/HashTable.h#L1204>): `WTF::HashTable<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::KeyValuePair<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > >,WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > > >,WTF::DefaultHash<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashMap<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> >,WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> >,WTF::DefaultHash<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashTraits<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,WTF::HashTraits<WTF::RefPtr<JSC::SourceProviderCache,WTF::RawPtrTraits<JSC::SourceProviderCache>,WTF::DefaultRefDerefTraits<JSC::SourceProviderCache> > >,WTF::HashTableTraits,0>::KeyValuePairTraits,WTF::HashTraits<WTF::RefPtr<JSC::SourceProvider,WTF::RawPtrTraits<JSC::SourceProvider>,WTF::DefaultRefDerefTraits<JSC::SourceProvider> > >,0>::deallocateTable`
- [`VM.cpp:522`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/VM.cpp#L522>): `JSC::VM::~VM`
- [`VM.h:298`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/C:/buildkite-agent/cache/https---github-com-oven-sh-bun-git/main/windows-x64-build-cpp/webkit-3845bf370ff4e9a5c0b96036255142c7904be963/include/JavaScriptCore/VM.h#L298>): `JSC::VM::operator delete`
- [`web_worker.zig:513`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/web_worker.zig#L513>): `exitAndDeinit`
- [`web_worker.zig:407`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/web_worker.zig#L407>): `spin`
- [`bindings.cpp:5068`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/bindings/bindings.cpp#L5068>): `JSC__VM__holdAPILock`
- [`shimmer.zig:201`](<https://github.com/oven-sh/bun/blob/b5b51004e8de80dcd43849e4da1d2623ee3d3008/src/bun.js/bindings/shimmer.zig#L201>): `cppFn`

Features: workers\_spawned, workers\_terminated, Bun.stdin, jsc, transpiler\_cache, tsconfig, tsconfig

**Comment by Jarred-Sumner** [comment]
We are tracking worker stability in #15964
