### ISSUE TITLE
Segmentation fault at address 0x0

### ISSUE THREAD

**Issue by pichxyaponn** [oven-sh/bun#15903]
### How can we reproduce the crash?

![Image](https://github.com/user-attachments/assets/490ac897-d714-4a0e-b2c2-ce46cf00e100)

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.41 ([`b8f28ed`](<https://github.com/oven-sh/bun/tree/b8f28ed8afd1c2b60568b2b0158d39a674178027>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x00000000

- [`js_parser.zig:4272`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/js_parser.zig#L4272>): `src.js_parser.Parser._parse__anon_141505`
- [`js_parser.zig:3098`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/js_parser.zig#L3098>): `src.cache.JavaScript.parse`
- [`bundler.zig:1408`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bundler.zig#L1408>): `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_121976`
- [`bundler.zig:1255`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bundler.zig#L1255>): `src.bundler.Bundler.parseMaybeReturnFileOnly__anon_117118`
- [`module_loader.zig:1656`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/module_loader.zig#L1656>): `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_117062`
- [`module_loader.zig:2367`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/module_loader.zig#L2367>): `Bun__transpileFile`
- [`ModuleLoader.cpp:609`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/bindings/ModuleLoader.cpp#L609>): `Bun::jsFunctionRequireCommonJS`

Features: jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6164820105/">BUN-A3S</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway in #15911
