### ISSUE TITLE
when add prisma the flowing error o

### ISSUE THREAD

**Issue by linnaungnaunghtun** [oven-sh/bun#15907]
### How can we reproduce the crash?

➜  my-next-app git:(master) ✗ bun add -d prisma
bun add v1.1.41 (b8f28ed8)
  ⚙️  prisma [1/2] ============================================================
Bun v1.1.41 (b8f28ed8) macOS Silicon
macOS v15.2
Args: "node" "scripts/postinstall.js"
Features: jsc transpiler_cache(3) tsconfig tsconfig_paths 
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util/types" 
Elapsed: 102ms | User: 20ms | Sys: 20ms
RSS: 31.90MB | Peak: 31.90MB | Commit: 1.07GB | Faults: 505

panic(main thread): Segmentation fault at address 0xAAAAAAAAAAAAAAAA
Crashed while visiting /Users/linnaungnaunghtun/Desktop/Next.js/my-next-app/node_modules/@prisma/get-platform/dist/chunk-6HZWON4S.js
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.41/Mn1b8f28edChgg8//B_2qy6Omo47O+sw3JmpmpJur9wImolwIuqoxIm2sggB+4ikfA2t1q1q1Ct1q1q1C

error: postinstall script from "@prisma/engines" terminated by SIGTRAP (Trace or breakpoint trap)
[1]    49778 trace trap  bun add -d prisma

### Relevant log output

```shell
➜  my-next-app git:(master) ✗ bun add -d prisma
bun add v1.1.41 (b8f28ed8)
  ⚙️  prisma [1/2] ============================================================
Bun v1.1.41 (b8f28ed8) macOS Silicon
macOS v15.2
Args: "node" "scripts/postinstall.js"
Features: jsc transpiler_cache(3) tsconfig tsconfig_paths 
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util/types" 
Elapsed: 102ms | User: 20ms | Sys: 20ms
RSS: 31.90MB | Peak: 31.90MB | Commit: 1.07GB | Faults: 505

panic(main thread): Segmentation fault at address 0xAAAAAAAAAAAAAAAA
Crashed while visiting /Users/linnaungnaunghtun/Desktop/Next.js/my-next-app/node_modules/@prisma/get-platform/dist/chunk-6HZWON4S.js
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.41/Mn1b8f28edChgg8//B_2qy6Omo47O+sw3JmpmpJur9wImolwIuqoxIm2sggB+4ikfA2t1q1q1Ct1q1q1C


error: postinstall script from "@prisma/engines" terminated by SIGTRAP (Trace or breakpoint trap)
[1]    49778 trace trap  bun add -d prisma
```

### Stack Trace (bun.report)

Bun v1.1.41 ([`b8f28ed`](<https://github.com/oven-sh/bun/tree/b8f28ed8afd1c2b60568b2b0158d39a674178027>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0xAAAAAAAAAAAAAAAA

- *1 unknown/js code*
- `src.js_parser.NewParser_`
- `src.js_parser.Parser._parse__anon_142565`
- `src.cache.JavaScript.parse`
- `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_123966`
- `src.bundler.Bundler.parseMaybeReturnFileOnly__anon_119104`
- `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_119048`
- `Bun__transpileFile`
- `Bun::fetchCommonJSModule`
- `Bun::jsFunctionRequireCommonJS`

Features: napi\_module\_register, process\_dlopen, jsc, tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6164609970/">BUN-A3N</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway in #15911
