### ISSUE TITLE
Another segmentation fault on bun 1.1.41

### ISSUE THREAD

**Issue by LoicEvenium** [oven-sh/bun#15904]
### How can we reproduce the crash?

Error occured while parsing node_modules/jest-message-util/build/types.js
Same error on linux github action env

```
Bun v1.1.41 (b8f28ed8) Linux x64 (baseline)
  Linux Kernel v6.5.0 | glibc v2.35
  CPU: sse42 popcnt avx avx2
  Args: "bun" "test" ""
  Features: bunfig dotenv(2) jsc transpiler_cache tsconfig(24) tsconfig_paths 
  Builtins: "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" 
  Elapsed: 1665ms | User: 1811ms | Sys: 291ms
  RSS: 0.98GB | Peak: 0.23GB | Commit: 0.98GB | Faults: 0
  
  panic(main thread): Segmentation fault at address 0x0
  Crashed while visiting /home/runner/work/evenium/evenium/node_modules/jest-message-util/build/types.js
  oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.41 ([`b8f28ed`](<https://github.com/oven-sh/bun/tree/b8f28ed8afd1c2b60568b2b0158d39a674178027>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0xAAAAAAAAAAAAAAAA

- *1 unknown/js code*
- `src.js_parser.NewParser_`
- `src.js_parser.Parser._parse__anon_142565`
- `src.cache.JavaScript.parse`
- `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_123966`
- `src.bundler.Bundler.parseMaybeReturnFileOnly__anon_119104`
- `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_119048`
- `Bun__transpileFile`
- `Bun::fetchCommonJSModule`
- `Bun::jsFunctionRequireCommonJS`

Features: napi\_module\_register, process\_dlopen, jsc, tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6164609970/">BUN-A3N</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway in #15911
