### ISSUE TITLE
Error thrown in `describe` block exits entire test suite

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1591]
```js
describe("a", () => {
  throw new Error();
});
describe("b", () => {
  // Does not run
});
```

**Comment by chrisAXZA** [comment]
Same behaviour when throwing error inside nested `it` case ?

**Comment by Jarred-Sumner** [comment]
This is fixed

**Comment by Jarred-Sumner** [comment]
> Same behaviour when throwing error inside nested it case ?


nested `it` shouldn't be supported. It is a bug that it doesn't throw
