### ISSUE TITLE
Container with base image 1.1.41-slim crashes instantly (base-image 1.1.40-slim works fine)

### ISSUE THREAD

**Issue by Strehk** [oven-sh/bun#15910]
### How can we reproduce the crash?

Just run the container `ghcr.io/deutschemodelunitednations/deutschemodelunitednations/munify-delegator:1.2.5`
https://github.com/DeutscheModelUnitedNations/munify-delegator/pkgs/container/deutschemodelunitednations%2Fmunify-delegator/326456785?tag=1.2.5

https://github.com/DeutscheModelUnitedNations/munify-delegator/releases/tag/1.2.5

### Relevant log output

```shell
============================================================
Bun v1.1.41 (b8f28ed8) Linux x64 (baseline)
Linux Kernel v5.15.0 | glibc v2.31
CPU: sse42 popcnt avx avx2
Args: "node" "/app/node_modules/.bin/prisma" "migrate" "deploy"
Features: jsc
Builtins: "bun:main" "node:fs" "node:string_decoder" "node:util/types"
Elapsed: 485ms | User: 325ms | Sys: 54ms
RSS: 1.00GB | Peak: 0.14GB | Commit: 1.00GB | Faults: 347

panic(main thread): Segmentation fault at address 0x0
Crashed while visiting /app/node_modules/@prisma/get-platform/dist/chunk-6HZWON4S.js
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.41/Bn1b8f28edAgggEog9hlE+8mO0qz3nDig49hD2i2rhD++6wgD0l9vgDujqxgD4+4k9D_A2AA

Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.41 ([`b8f28ed`](<https://github.com/oven-sh/bun/tree/b8f28ed8afd1c2b60568b2b0158d39a674178027>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x00000000

- [`js_parser.zig:4272`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/js_parser.zig#L4272>): `src.js_parser.Parser._parse__anon_141505`
- [`js_parser.zig:3098`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/js_parser.zig#L3098>): `src.cache.JavaScript.parse`
- [`bundler.zig:1408`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bundler.zig#L1408>): `src.bundler.Bundler.parseMaybeReturnFileOnlyAllowSharedBuffer__anon_121976`
- [`bundler.zig:1255`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bundler.zig#L1255>): `src.bundler.Bundler.parseMaybeReturnFileOnly__anon_117118`
- [`module_loader.zig:1656`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/module_loader.zig#L1656>): `src.bun.js.module_loader.ModuleLoader.transpileSourceCode__anon_117062`
- [`module_loader.zig:2367`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/module_loader.zig#L2367>): `Bun__transpileFile`
- [`ModuleLoader.cpp:609`](<https://github.com/oven-sh/bun/blob/b8f28ed8afd1c2b60568b2b0158d39a674178027/src/bun.js/bindings/ModuleLoader.cpp#L609>): `Bun::jsFunctionRequireCommonJS`

Features: jsc

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway in #15911
