### ISSUE TITLE
Evaluation of @babel/parser fails in bun; works fine in node. Top level variable declared in the file can't be found.

### ISSUE THREAD

**Issue by nirrek** [oven-sh/bun#1594]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```bash
yarn init -y && yarn add @babel/parser

echo "require('@babel/parser')" > test.cjs

bun test.cjs
```

### What is the expected behavior?

The file should be evaluated without error.

### What do you see instead?

```
10322 |
10323 | const mixinPlugins = {
10324 |   estree,
10325 |   jsx,
      ^
ReferenceError: Can't find variable: jsx
      at /bun-test/node_modules/@babel/parser/lib/index.js:10325:2
      at /bun-test/test.cjs:1:8
```

### Additional information

There is a top level variable declared on line 4853 in `node_modules/@babel/parser/lib/index.js`
`var jsx = ...`

Which is then referenced on line 8268 in `node_modules/@babel/parser/lib/index.js` when declaring a top level object
```
const mixinPlugins = {
  estree,
  jsx, // <-- this guy
  flow,
  typescript,
  v8intrinsic,
  placeholders
};
```

Running `node test.cjs` evaluates without issue.

Copying the source code from `node_modules/@babel/parser/lib/index.js` into my own file `babel-parser.cjs` and then require()ing `babel-parser.cjs` instead of `@babel/parser` also evaluates without issue.

So presumably some distinct behaviour in how modules which are imported from node_modules are being evaluated is eliciting this failure.

**Comment by Jarred-Sumner** [comment]
Minimum reproduction

Source
```js
var jsx = (superClass) => class JSXParserMixin  extends superClass {
};
export const mixinPlugins = {
  jsx
};
```


For bun:
```
bun build --platform=bun repro.js
```

```js
export const mixinPlugins = {
  jsx
};
```

No dead code elimination:

```
bun build repro.js
```

```js
var jsx = (superClass) => class JSXParserMixin  extends superClass {
};
export const mixinPlugins = {
  jsx
};
```


Dead code elimination bug
