### ISSUE TITLE
Bun is crashing with Many Worker Threads

### ISSUE THREAD

**Issue by MNK144** [oven-sh/bun#15942]
### How can we reproduce the crash?

I am just trying to do some benchmarking of BunJS along with Express. So the code is looping through and performing some arithmatic and logical expressions nothing much.

Issue started occuring when i was doing performance testing on Worker Thread based code by Ramping up concurrent connections from 5 to 100, it is crashing with provided error at around 150-200 requests (15-20 concurrent requests). I have also tried running it with fixed 50 concurrent requests and it crashed again. I have provided error logs for both

### Relevant log output

```shell
============================================================
Bun v1.1.42 (50eec002) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Manank\.bun\bin\bun.exe" "run" "server.js"
Features: http_server jsc tsconfig(15) workers_spawned(157) workers_terminated(156)
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:net" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads"
Elapsed: 31108ms | User: 8703ms | Sys: 2468ms
RSS: 0.25GB | Peak: 0.35GB | Commit: 0.40GB | Faults: 1213611

panic(thread 30552): Segmentation fault at address 0x5432C1804E8
oh no: Bun has crashed. This indicates a bug in Bun, not your code.



============================================================
Bun v1.1.42 (50eec002) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Manank\.bun\bin\bun.exe" "run" "server.js"
Features: http_server jsc tsconfig(15) workers_spawned(817) workers_terminated(814)
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:net" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads"
Elapsed: 93692ms | User: 49171ms | Sys: 16171ms
RSS: 0.41GB | Peak: 0.55GB | Commit: 0.99GB | Faults: 6085794

panic(thread 46216): Segmentation fault at address 0x36AB3B50400
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.42 ([`50eec00`](<https://github.com/oven-sh/bun/tree/50eec0025b482ad7b340c82f64749903b2fad4b8>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x39F4C1B0728

- [`core.c:109`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/win/core.c#L109>): `uv__loops_add`
- [`core.c:299`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/win/core.c#L299>): `uv_loop_init`
- [`libuv.zig:2805`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/deps/libuv.zig#L2805>): `errEnum`
- [`event_loop.zig:1606`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/bun.js/event_loop.zig#L1606>): `ensureWaker`
- [`javascript.zig:3083`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/bun.js/javascript.zig#L3083>): `reloadEntryPoint`
- [`javascript.zig:3132`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/bun.js/javascript.zig#L3132>): `loadEntryPointForWebWorker`
- [`bindings.cpp:5068`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/bun.js/bindings/bindings.cpp#L5068>): `JSC__VM__holdAPILock`
- [`shimmer.zig:201`](<https://github.com/oven-sh/bun/blob/50eec0025b482ad7b340c82f64749903b2fad4b8/src/bun.js/bindings/shimmer.zig#L201>): `cppFn`

Features: workers\_spawned, workers\_terminated, http\_server, jsc, tsconfig, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5738332326/">BUN-4GW</a></strong></sub>

**Comment by Jarred-Sumner** [comment]
Tracking this in #15964
