### ISSUE TITLE
Feat: Build executables with bun build

### ISSUE THREAD

**Issue by brrock** [oven-sh/bun#15967]
### What is the problem this feature would solve?

Having to use other tools than bun when making an executable file for all platforms and archs 

### What is the feature you are proposing to solve the problem?

I want to in the build command the ability to set the target to something Linux-x64 …

### What alternatives have you considered?

Writing a quick compiler in rust will or using nexe or pkg

**Comment by Jarred-Sumner** [comment]
> I want to in the build command the ability to set the target to something Linux-x64 …

Guess what:

```
bun build --target=linux-x64 ./entry.ts
```

More about [cross compilation ](https://bun.sh/docs/bundler/executables#cross-compile-to-other-platforms)
