### ISSUE TITLE
Consider using `inline switch` expression handling

### ISSUE THREAD

**Issue by i0bs** [oven-sh/bun#1598]
https://github.com/oven-sh/bun/blob/b400dfb386be65ca1d16ada005e75683ec48c1a5/src/fs.zig#L205-L218

When handling file structure kind structure we can optimise on perf by using the [accepted `inline switch` proposal](https://github.com/ziglang/zig/pull/12979). This should eliminate a small amount of bloat from ZIR and parsed rendering calls otherwise when not using it in a strategic manner.

**Comment by Jarred-Sumner** [comment]
We haven't migrated to stage2 yet

**Comment by i0bs** [comment]
Oh did not know Bun is still stage1 dependent. Is stage2 migration in the works? Couldn't see on the road map

**Comment by Jarred-Sumner** [comment]
we are mostly blocked on stage2 compiler segfaults, which I think will be resolved by this PR: https://github.com/ziglang/zig/pull/13017

this branch is the current one https://github.com/oven-sh/bun/tree/jarred/attempt-upgrade

**Comment by i0bs** [comment]
Brilliant, I propose for this to remain in its current state then 'till stage2 workarounds are met with full compromise or segfaults are corrected in the next 0.1x dev release. Awesome stuff on the branch btw 👏
