### ISSUE TITLE
Error installing Aceternitiy UI component

### ISSUE THREAD

**Issue by karthikeyasomayajula** [oven-sh/bun#15990]
### `package.json` file

```json
{
  "name": "notelify",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@radix-ui/react-avatar": "^1.1.2",
    "@radix-ui/react-slot": "^1.1.1",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "framer-motion": "^11.15.0",
    "lucide-react": "^0.469.0",
    "next": "14.2.16",
    "next-themes": "^0.4.4",
    "notelify": "file:",
    "react": "^18",
    "react-dom": "^18",
    "recharts": "^2.15.0",
    "tailwind-merge": "^2.6.0",
    "tailwindcss-animate": "^1.0.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.16",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```

### How can we reproduce the crash?

run the following command in a nextjs application

after you install shadcn 

-- bun i framer-motion clsx tailwind-merge

### Relevant log output

```shell
[8.92ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\karth\AppData\Roaming\npm\node_modules\bun\bin\bun.exe", "i", "framer-motion", "clsx", "tailwind-merge"
Features: lockfile_migration_from_package_lock 
Elapsed: 37ms | User: 15ms | Sys: 15ms
RSS: 57.69MB | Peak: 57.69MB | Commit: 92.12MB | Faults: 14264
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure: unexpected resolution tag

- [`install.zig:9274`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L9274>): `installPackageWithNameAndResolution`
- [`install.zig:10163`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L10163>): `installPackages`
- [`install.zig:8561`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L8561>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`filter_run.zig:410`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/filter_run.zig#L410>): `install`
- [`cli.zig:1440`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1440>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by RetardRento** [comment]
Thank you, the issue seems to be resolved
