### ISSUE TITLE
Request `.text` method returns empty string if payload is relatively big and the read follows a dynamic import

### ISSUE THREAD

**Issue by chrisdavies** [oven-sh/bun#1600]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Linux 6.0.11-300.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

Given an `index.ts` like this:

```ts
// index.ts
// Using a normal import works fine...
// import { Page } from './hi';

Bun.serve({
  async fetch(req: Request): Promise<Response> {
    // But doing a *dynamic* import causes the req.text() await to give  an empty string
    // if the request payload is large (100KB or so). Note: if I change this to use require,
    // it works: `const { Page } = require('./hi');`
    const { Page } = await import('./hi');

    if (req.method === 'POST') {
      const data = await req.text();
      console.log('You posted: "' + data + '"');
    }

    return Page(req);
  },
});
```

And a second file which the index dynamically imports:

```ts
// hi.ts
export function Page(_req: Request): Response {
  return new Response(
    `
      <form method="POST">
        <textarea name="big" placeholder="Enter something big" ></textarea>
        <button>Save</button>
      </form>
    `,
    {
      headers: {
        'Content-Type': 'text/html',
      },
    }
  );
}
```

Run it `bun ./index.ts` and then paste a relatively large chunk of text into the textarea (in my case, the text was around 100KB).

For *small* amounts of text, everything works fine.

It's quite a strange bug. It's almost like the dynamic import is using up some kind of shared buffer, and there's no longer adequate room to process the large text read, but... I have no idea.

### What is the expected behavior?

The `await req.text()` always returns the posted text.

### What do you see instead?

The `await req.text()` returns the posted text only in the case where the text is relatively small.

### Additional information

Nothing else. Thanks for Bun. It's great! I'm excited to see it move forward.

**Comment by Jarred-Sumner** [comment]
Does it happen if other async work occurs, such as a `setTimeout`?

**Comment by chrisdavies** [comment]
To answer your question, no. Other async stuff works fine. In fact, strangely, adding another await anywhere before awaiting `request.text()` makes the bug go away. 

Here's a repo that reproduces the issue:

https://github.com/chrisdavies/bun-example-bug

**Comment by Jarred-Sumner** [comment]
I suspect this is caused by `JSInternalPromise` being a different promise than `JSPromise` and some code somewhere is missing a check for which `JSPromise` type it is. dynamic import returns a `JSInternalPromise` which is a Promise that cannot be modified by userland, iirc

**Comment by bitdom8** [comment]
Worst here, async fetch functions runs the server but not load the url pages. Endlessly loading

**Comment by Jarred-Sumner** [comment]
The text is there, but it's a little confusing.

The bug is actually a string escaping behavior in console.log and it's not strictly a bug.  It's writing the null bytes to stdout. You can verify this with a `JSON.stringify`. In Bun, when you console.log a string as the only argument, it treats it similarly to `process.stdout.write`, with minimal formatting or escaping. null bytes are often not printed by terminals.

You can verify this with the following snippet:
```js

Bun.serve({
  async fetch(req: Request): Promise<Response> {
    // But doing a *dynamic* import causes the req.text() await to give  an empty string
    // if the request payload is large (100KB or so). Note: if I change this to use require,
    // it works: `const { Page } = require('./hi');`
    const { Page } = await import('./hi');

    if (req.method === 'POST') {
      const data = JSON.stringify(await req.text());
      console.log('You posted: "' + data + '"');
    }

    return Page(req);
  },
});
```

Instead of printing seemingly nothing, it prints a whole lot of `\u0000` characters.
