### ISSUE TITLE
cannot chain Node.js EventEmitter API calls

### ISSUE THREAD

**Issue by alexlamsl** [oven-sh/bun#1601]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Linux 4.4.0-17763-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

```js
$ cat test.js
console.log(process.stdin.on('end', function() {
  console.log('end');
}) === process.stdin);
console.log(process.stdin.once('end', function() {
  console.log('end');
}) === process.stdin);
```

### What is the expected behavior?

```console
$ node -v
v0.8.28
v0.10.48
v0.12.18
v4.9.1
v6.17.1
v8.17.0
v10.24.1
v12.22.12
v14.20.0
v16.17.0
v18.8.0

$ node test.js
true
true
```

### What do you see instead?

```console
$ bun test.js
false
false
```

**Comment by Jarred-Sumner** [comment]
Can you try in the canary build?

```bash
bun upgrade --canary
```

**Comment by alexlamsl** [comment]
... half of it works, i.e. `once()` behaves correctly but not `on()`:
```console
$ bun upgrade --canary
[4.09s] Upgraded.

Welcome to bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/a13e64c28645f0a1dcd36bd986fc57cf2d91ef7e...main
$ bun -v
0.3.0
$ bun test.js
false
true
$
```

**Comment by alexlamsl** [comment]
Assuming I'm looking at the right place, it's weird since while `once()` is more straightforward:
https://github.com/oven-sh/bun/blob/c6f3044654ab8c6bf2ea98ee2594f636cc099020/src/node-fallbacks/events.js#L281-L285
`on()` seems to be ultimately doing the same:
https://github.com/oven-sh/bun/blob/c6f3044654ab8c6bf2ea98ee2594f636cc099020/src/node-fallbacks/events.js#L245-L249
https://github.com/oven-sh/bun/blob/c6f3044654ab8c6bf2ea98ee2594f636cc099020/src/node-fallbacks/events.js#L174
https://github.com/oven-sh/bun/blob/c6f3044654ab8c6bf2ea98ee2594f636cc099020/src/node-fallbacks/events.js#L242-L243

**Comment by alexlamsl** [comment]
Ah wait &minus; could this be the problem?
https://github.com/oven-sh/bun/blob/c6f3044654ab8c6bf2ea98ee2594f636cc099020/src/bun.js/builtins/js/ProcessObjectInternals.js#L513-L518
Note the return value from `super.on()` being discarded.

`once()` is not being overridden, which would explain why that one works.

(Edit: since `once()` would eventually call `this.on()`, i.e. the overridden version, there is no need to intercept yet again there)
