### ISSUE TITLE
`bun wiptest` process to fail if typescript compile error

### ISSUE THREAD

**Issue by nitsanavni** [oven-sh/bun#1605]
### What is the problem this feature would solve?

`bun wiptest` exits with code `0` when running tests that have typescript errors.

### What is the feature you are proposing to solve the problem?

should exit with code `1`

**Comment by Jarred-Sumner** [comment]
Bun doesn't support typechecking currently. We might add support for this in the future (via tsc)

**Comment by nitsanavni** [comment]
it does show 'error' on stderr, so I suggest it exits with code 1

**Comment by birkskyum** [comment]
@nitsanavni , can you provide a repro for this?

**Comment by nitsanavni** [comment]
@birkskyum couldn't reproduce due to another problem - the `bun test` process never terminates

[see here](https://github.com/nitsanavni/bun-1605)

**Comment by Electroid** [comment]
Closing in favor of #6711
