### ISSUE TITLE
`napi_set_named_property` doesn't work with some names

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#161]
Rather amusingly, `napi_set_named_property` doesn't work with all property names. I can set these property names:
`a`, `b`, `x`, `version`, `patch`
but I can't properly set these property names:
`major`, `minor`, `good`, `foo`, `bar`, `really really really long name`
In the latter case, it seems the property actually gets created, but the value is undefined regardless of what value I actually supplied.

Creating a `napi_value` with the property name and using `napi_set_property` seems to work just fine, and as Jarred pointed out, probably an issue with marking the strings to protect them from GC.

**Comment by Jarred-Sumner** [comment]
I'm not 100% this is fixed but it's worth a try after next update
