### ISSUE TITLE
`.pipe()` doesn't end the stream

### ISSUE THREAD

**Issue by xori** [oven-sh/bun#1615]
### What version of Bun is running?

0.3.1 (canary)

### What platform is your computer?

Linux 5.15.0-56-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
import { createWriteStream, createReadStream } from 'fs'

const readable = createReadStream('data/in.txt') // with 'hello world' in it
const writable = createWriteStream('data/out.txt', { flags: 'w' })

readable.pipe(writable);

new Promise(res => {
  writable.on('close', res)
  writable.on('finish', res)
  writable.on('end', res)
  if(writable.writableEnded) res(true)
  console.log('writableEnded: ', writable.writableEnded)
}).then(_ => console.log('done!'))
```

### What is the expected behavior?

```bash
writableEnded:  false
done!
```

I would also expect that Bun would output to the `data/out.txt` file, but it's blank. This works "as expected" in `node 16.8.1`

### What do you see instead?

```bash
writableEnded:  false
```

and a blank `data/out.txt` file.

**Comment by ThatOneBro** [comment]
I'll take a look at it. Seems like it could be related to what is causing #1607 (Promises not being awaited before exiting process) or it could be related to write not blocking

**Comment by xori** [comment]
I'll add that even if I append a `setTimeout(_ => {}, 10000)` the same problem persists.

**Comment by alexlamsl** [comment]
Reduced test case on Ubuntu 22.04 (`Linux 5.15.0-56-generic x86_64 x86_64`):
```js
$ cat test.js
require("fs").createReadStream("test.js")
  .on("end", () => console.log("ENDED"))
  .on("data", data => console.log(data))
  .on("close", () => console.log("CLOSED"))
  .on("finish", () => console.log("FINISHED"));
```
With Node.js:
```console
$ node -v
v18.8.0

$ node test.js
<Buffer 72 65 71 75 69 72 65 28 22 66 73 22 29 2e 63 72 65 61 74 65 52 65 61 64 53 74 72 65 61 6d 28 22 74 65 73 74 2e 6a 73 22 29 0d 0a 20 20 2e 6f 6e 28 22 ... 171 more bytes>
ENDED
CLOSED
$
```
With `bun`:
```console
$ bun test.js
CLOSED
$
```
Seems like it hasn't even tried to read any data &minus; however it does emit & process a `close` event, which means the process does sit around & wait unlike #1607

**Comment by Jarred-Sumner** [comment]
This is fixed in canary
