### ISSUE TITLE
Implement dgram

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1630]

**Comment by pepper-lees** [comment]
Yes please! I'm working on an open source UPnP server package which uses dgram for some of its connection backend. It would be great if we could take advantage of bun's much improved speed in sqlite3 and general code execution, but we can't yet until dgram is implemented.

**Comment by deadlinecode** [comment]
This would also be nice to have for using @discordjs/voice to stream audio (especially since ytdl-core is working now)

**Comment by ezShroom** [comment]
@Jarred-Sumner How's this going?

**Comment by pcfreak30** [comment]
Just tested some of my code again on bun 0.7.4 and this is needed.

Kudos.

**Comment by daviddutch** [comment]
I've just tried on Bun 0.8 without any luck:
`NotImplementedError: node:dgram createSocket is not yet implemented in Bun.`

This seems to be the blocker for one of our app.

**Comment by joetifa2003** [comment]
This would be awesome for discord/voice, waiting for this!

**Comment by meluiz** [comment]
> Isso seria incrível para discord/voz, esperando por isso!

Yes. I'm have some difficult to use discord/voice or discord-player.

**Comment by meluiz** [comment]
> This would be awesome for discord/voice, waiting for this!

Yes. I'm have some difficult to use discord/voice or discord-player.

**Comment by hpx7** [comment]
I tried Bun 1.0 but it looks like our https://www.npmjs.com/package/hot-shots dependency doesn't work due to lack of `node:dgram` support

**Comment by jedahan** [comment]
Well maybe we can start the discussion of whats needed to implement.

Cursory look at the [node docs for dgram](https://nodejs.org/api/dgram.html) shows 1 type (Socket) with 19 methods, 5 events, and 2 constructors.

**Comment by onionhammer** [comment]
node-ssdp relies on dgram

**Comment by paymog** [comment]
This is required for any applications that use [hot-shots](https://www.npmjs.com/package/hot-shots) for statsd metrics reporting

**Comment by billdybas** [comment]
`dd-trace` ([Datadog APM](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs/)) also relies on `dgram`

https://github.com/DataDog/dd-trace-js/blob/8cf126c82cdeccb54ae119249c7905ab06a05d94/packages/dd-trace/src/dogstatsd.js#L5

**Comment by Zibri** [comment]
also bittorrent-dht relies on dgram.
:(
this should be prioritized.

**Comment by coffeeispower** [comment]
discord voice protocol uses UDP, @discordjs/voice uses dgram, this should be done ASAP (after bug fixes)

**Comment by Saissaken** [comment]
I reviewed #159, but it seems like this is not on the roadmap, is it? @Jarred-Sumner

**Comment by rcarmo** [comment]
Came here looking for this since it's a blocking issue for doing all sorts of IoT stuff.

**Comment by MrDanielHarka** [comment]
I would really need it for Webtorrent. 🙏

**Comment by kalanchoej** [comment]
Bun can't be a drop-in replacement for really any of my projects without dgram support since we use dd-trace and hot-shots.

**Comment by Reusek** [comment]
Does anyone working on this? I could try implement something...

**Comment by rcarmo** [comment]
A quick note: UDP support also implies multicast ;)

**Comment by oliverlevay** [comment]
this library that I want to use https://github.com/alxhotel/chromecast-api needs this

**Comment by Marcos-Rollon** [comment]
A lot of us working with IoT and robotics really need this. I hope it gets prioritized, since is not on the roadmap (as in #159 )

**Comment by alessandroamella** [comment]
Up! Really need this for Bonjour (mDNS)

**Comment by LIMPIX31** [comment]
Looking forward to the datagram.

**Comment by BlusteryS** [comment]
Up

**Comment by nahuelon** [comment]
It would be great for IoT ad-hoc servers listening for UDP messages. Thanks.

**Comment by LIMPIX31** [comment]
As a temporary solution, this can be implemented via FFI

**Comment by rcarmo** [comment]
> As a temporary solution, this can be implemented via FFI

At what cost for developers adopting `bun`? Not everyone wants to do their own socket code.

**Comment by pepper-lees** [comment]
> As a temporary solution, this can be implemented via FFI

What's FFI?

**Comment by pcfreak30** [comment]
> > As a temporary solution, this can be implemented via FFI
> 
> What's FFI?

bridging from a `.SO`/`.DLL`.

**Comment by LIMPIX31** [comment]
I don't know much about low level stuff, but this could be a starting point. This is a simple code to listen for data from a socket. I haven't implemented sending data yet due to some unrelated issues.

Lib (Rust)
```rust
use {
  std::{
    net::UdpSocket,
    sync::{Arc, Mutex}, 
  },
  lazy_static::lazy_static,
  safer_ffi::prelude::*,
};

lazy_static! {
  static ref SOCKETS: Arc<Mutex<Vec<UdpSocket>>> = Arc::new(Mutex::new(Vec::new()));
}

fn store_socket(socket: UdpSocket) -> usize {
  let mut sockets_store = SOCKETS.lock().unwrap();
  sockets_store.push(socket);

  sockets_store.len() - 1
}

#[ffi_export]
fn bind<'a>(addr: char_p::Ref<'a>) -> usize {
  let socket = UdpSocket::bind(addr.to_str()).unwrap();

  store_socket(socket)
}

#[ffi_export]
fn recv_from<'a>(socket_idx: usize, buf: c_slice::Mut<'a, u8>) -> usize {
  let sockets_store = SOCKETS.lock().unwrap();
  let socket = sockets_store.get(socket_idx).unwrap();

  socket.recv_from(buf.as_slice()).unwrap().0
}
```

Bun
```ts
const { symbols, close } = dlopen(`${import.meta.dir}/libbungram.${suffix}`, {
  bind: {
    args: [FFIType.cstring],
    returns: FFIType.u32,
  },
  recv_from: {
    args: [FFIType.u32, FFIType.ptr],
    returns: FFIType.u32,
  },
})

const addr = Buffer.from('0.0.0.0:10011', 'utf8')

const socketIdx = symbols.bind(ptr(addr))

const buf = ptr(Buffer.alloc(2048))

while (true) {
  const len = symbols.recv_from(socketIdx, buf)

  const payload = toArrayBuffer(buf, 0, len)
  const stringified = Buffer.from(payload).toString('utf8')

  console.log(`Payload(${len}): ${stringified}`)

  if (stringified.startsWith('exit')) {
    break
  }
}

close()
```
Besides, Bun does not have the ability to call FFI without blocking the main thread (at least it is not written in the documentation).

**Comment by jedahan** [comment]
here is a udp broadcast example from another zig project - https://github.com/MasterQ32/zig-network/blob/master/examples/udp_broadcast.zig

**Comment by Zibri** [comment]
thanks @jedahan but that's not the point.
Bun seems very cool but without the dgram implementation is quite useless in today's world.

**Comment by juanvergara3** [comment]
I'm trying to make an sql server backend and the mssql module used dgram :/

**Comment by incon** [comment]
https://github.com/wankdanker/node-discover uses dgram

**Comment by crhowell3** [comment]
Would something quick and dirty like a translation of the [Node.js dgram library](https://github.com/nodejs/node/blob/main/lib/dgram.js) from JavaScript into Zig be enough (at least for now)? It would be very nice to have dgram support in Bun as quickly as possible, and it seems that many other people agree that it needs to happen sooner rather than later. If that approach is too naive, then what needs to be done in order to get the ball rolling? I'd be more than happy to start contributing if anyone has ideas for how to start.

**Comment by richherbs** [comment]
up

**Comment by Bartel-C8** [comment]
Maybe @Jarred-Sumner can give somewhat an official statement or reaction. I think it's clear now there is plenty of need for this module (myself included). 🙏

**Comment by Electroid** [comment]
> Maybe @Jarred-Sumner can give somewhat an official statement or reaction. I think it's clear now there is plenty of need for this module (myself included). 🙏

We are 100% going to implement `dgram`. Right now our short-term priority is fixing bugs so more packages and applications can work in Bun. Of course, we'll have to include things we haven't implemented like `dgram`, but we're not quite there yet.

**Comment by richherbs** [comment]
@Electroid any idea of where this is in the road map? Would really love to test out Bun but this is a blocker for me on most of my projects.

**Comment by CrisD404** [comment]
Up

**Comment by alowelter** [comment]
Hello friends, I am waiting for this, to work with the SNMP package.

**Comment by rob-raisch-simplisafe** [comment]
definitely needed. up up up! ;)

**Comment by TrigamDev** [comment]
> > Maybe @Jarred-Sumner can give somewhat an official statement or reaction. I think it's clear now there is plenty of need for this module (myself included). 🙏
> 
> We are 100% going to implement `dgram`. Right now our short-term priority is fixing bugs so more packages and applications can work in Bun. Of course, we'll have to include things we haven't implemented like `dgram`, but we're not quite there yet.

Would you be able to give an estimated time frame of when this can be implemented? A project I'm working on depends on this being implemented.

**Comment by phi0x** [comment]
Looking to use dgram as well.

**Comment by xd1gital** [comment]
Need this! My App connects to ZKTeco devices  over UDP

**Comment by harish-chander** [comment]
UP wanted for a sip call manager

**Comment by alancnet** [comment]
`multicast-dns` depends on this

**Comment by btx-systems** [comment]
`@discordjs/voice` requires this

**Comment by evsar3** [comment]
As an IoT developer, this is the only thing that is holding me of using Bun as my production runtime.

**Comment by adminy** [comment]
`@project-chip/matter.js` also requires this

**Comment by Pigges** [comment]
Any updates regarding this?

**Comment by BlusteryS** [comment]
up

**Comment by evsar3** [comment]
> Any updates regarding this?

It seems they already start working on something towards UDP, as you can see on PR #6792

**Comment by vsnthdev** [comment]
Looking forward to using Bun with webtorrents 👏

**Comment by ShanonJackson** [comment]
Bittorrent heavily uses UDP. I'd love to see the performance of the overall swarm improved just by swapping some Node servers to Bun.

**Comment by sergi0g** [comment]
> `multicast-dns` depends on this

I also need this

**Comment by Kisakay** [comment]
up

**Comment by factoidforrest** [comment]
darn, webtorrent wont work without this! Was really hoping to use Bun for my current project. Ah well

**Comment by QuentinGruber** [comment]
Most of my projects use udp so beside some cli tools i can't use bun for my main projects +1

**Comment by ShadowLeiPolestar** [comment]
Trying to use BUN for the runtime for backend microservices.
Currently (bun v1.0.20) met an issue that when invoking the AWS X-Ray SDK would throw an error associated w/ "dgram".
Ref: AWS X-Ray SDK depends on UDP: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs.html

Hope this feature would have higher priority for implementation 🙏

Thanks.

**Comment by samifouad** [comment]
writing a DNS server in JavaScript, would love to swtich to bun

**Comment by ansarizafar** [comment]
I also need this feature for using https://socketsupply.co/ streaming real protocol with Bun.

**Comment by jmordica** [comment]
Needing this as well!

**Comment by janilahti** [comment]
Logging using syslog transport is challenging without `node:dgram`.

**Comment by bmansfie** [comment]
Need dgram for one of my projects as well.

**Comment by VigilioYonatan** [comment]
public-ip neeed this

**Comment by binsarjr** [comment]
up

**Comment by scorp1k** [comment]
Waiting for dgram support, especially with Source Specific Multicast UDP

**Comment by anthonykrivonos** [comment]
Any way to put this issue higher on the priority list? Not being able to use `dd-trace` or `hot-shots` in production is bludgeoning our observability rn.

That being said, has anyone found a workaround with using these packages on TCP? Far from ideal, but better than nothing.

**Comment by Daavidaviid** [comment]
I wanted to stream `ffmpeg` to `node-datachannel`, i think I'm gonna need to go back to node.js

**Comment by AdnanCukur** [comment]
Wanted to migrate all of our node services to bun, but can't since we use AWS Xray for ray tracing and aws-xray-sdk-core uses `dgram.createSocket('udp4')`

**Comment by PMK744** [comment]
Need this 🙏

**Comment by AnarchyEcho** [comment]
Need this to stop erroring with @discord.js/voice as well

**Comment by meqativ** [comment]
when

**Comment by LIMPIX31** [comment]
> when

tomorrow

**Comment by sulvii** [comment]
progress?

**Comment by jedahan** [comment]
If someone is interested in implementing, they likely want to contribute off of https://github.com/oven-sh/bun/pull/7271 
If someone wants to make it from scratch, maybe look at https://github.com/MasterQ32/zig-network/blob/master/examples/udp_broadcast.zig and https://nodejs.org/api/dgram.html

**Comment by jadbox** [comment]
I'm stuck on this same bug

**Comment by volschin** [comment]
@jadbox it‘s not a bug, simply not implemented as described in the documentation.

**Comment by rob-raisch-simplisafe** [comment]
Um. It seems to me that "not implemented as described in the documentation" would require either fixing the module so it does what the documentation describes or the documentation needs to be changed so it reflects the correct operation of the module. So, yes, I'd say it's a bug. :)

**Comment by fitzn** [comment]
@rob-raisch-simplisafe UDP is not in the documentation, so there is no bug or error in the documentation. It is not listed as something that is supported. This issue tracks support for UDP. As @jedahan said, you are welcome to pick up where #7271 left off, or start from scratch. And, of course, if you see an error in the documentation, please open a pull request.

**Comment by rob-raisch-simplisafe** [comment]
Thanks for the clarification.

**Comment by volschin** [comment]
@rob-raisch-simplisafe The documentation I have written about, is this one:
https://bun.sh/docs/runtime/nodejs-apis

**Comment by recanman** [comment]
I'm willing to set a bounty, paid in XMR, for someone that can get a PR merged as soon as possible.
This is a critical issue.

**Comment by pcfreak30** [comment]
> I'm willing to set a bounty, paid in XMR, for someone that can get a PR merged as soon as possible. This is a critical issue.

:eyes: crypto has entered the house! :upside_down_face:.

**Comment by dathacky** [comment]
+1

**Comment by Bytedefined** [comment]
Would be great to see support for this, along with node:cluster.

**Comment by xenyal** [comment]
Being unable to use `dd-trace` blocks apps using Datadog APM in production. Is prometheus the only monitoring tool people use to monitor bun apps?

**Comment by defaultkavy** [comment]
I really need this to complete my project...

**Comment by sharathprabhal** [comment]
Is the core team working on this @Jarred-Sumner 

Also, is anyone in the community actively working on this? Happy to take a stab otherwise.

**Comment by evsar3** [comment]
Despite of the excellent job being done by the Bun team, this feature should be top priority by now. This "bun shell" thing should have take a lot of effort to accomplish and at least for me, I don't see it being more critical for server-side software development than one of the most important network protocols in the world.

Maybe I'm too dumb to see the real potential of bun shell, but IMO bun should focus on features that would really bring the community into Bun.

**Comment by recanman** [comment]
@sharathprabhal I don't believe that anyone is working on it currently. If you (or anyone else) can successfully get a PR merged, I will pay some XMR.

**Comment by gvilums** [comment]
@recanman I'm working on this right now

**Comment by sharathprabhal** [comment]
> @recanman I'm working on this right now

❤️ 
@gvilums do you have release timeline?

**Comment by renejfc** [comment]
> @recanman I'm working on this right now

Much appreciated! 🙏 the community will love this

**Comment by Zibri** [comment]
> > @recanman I'm working on this right now
> 
> ❤️ @gvilums do you have release timeline?

About time!
(I'm joking.... thanks!!!)

**Comment by FDiskas** [comment]
A good test case would be this simple example:
```js
import util from 'node:util';
import nslookup from 'nslookup';

const debuglog = util.debuglog('test');
const domain = 'example.com';

debuglog('Looking up', domain);

nslookup(domain)
.server('208.67.222.123')
.type('a')
.timeout(10 * 1000)
.end(function(error, address) {
    debuglog('got ip', address[0], 'for', domain);
});
```
To test this
```
NODE_DEBUG=test bun test.js
```

It throws an error as currently expected:
![image](https://github.com/oven-sh/bun/assets/468006/5706483e-cebe-435c-b0b2-ced85f4b048c)

**Comment by MrDanielHarka** [comment]
Why is it closed if it's not fixed, @gvilums?

```
$ bun upgrade
Bun v1.1.5 is out! You're on v1.1.3
[11.94s] Upgraded.

Welcome to Bun v1.1.5!

Report any bugs:

    https://github.com/oven-sh/bun/issues

What's new:

    https://github.com/oven-sh/bun/releases/tag/bun-v1.1.5

Changelog:

    https://github.com/oven-sh/bun/compare/bun-v1.1.3...bun-v1.1.5

~/code/harka-torrent
$ bun app.js 
14 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
15 | }, $;
16 | 
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
                               ^
NotImplementedError: node:dgram createSocket is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/1630
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:2:69
      at node:dgram:2:55
      at createSocket (/Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/lib/upnp/ssdp.js:83:18)
      at /Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/lib/upnp/ssdp.js:41:9
      at forEach (:1:21)
      at createSockets (/Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/lib/upnp/ssdp.js:39:22)
      at new Ssdp (/Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/lib/upnp/ssdp.js:28:5)
      at new Client (/Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/lib/upnp/index.js:6:17)
      at new NatAPI (/Users/d.harka/.bun/install/cache/@silentbot1/nat-api@0.4.7/index.js:53:26)

**Comment by Bartel-C8** [comment]
Have a little patience... The merge only has been done 7hours ago...
As I can track, it will be included in the v1.1.6 release.

Thanks for your work on this @gvilums !

**Comment by MrDanielHarka** [comment]
Error 404: Patience not found!

Oh, shite! I thought it was included in v1.1.5.

**Comment by Jarred-Sumner** [comment]
This will be part of the Bun v1.1.6 release, which we are aiming to do later tonight

**Comment by LIMPIX31** [comment]
It's a win, folks! 🎉

**Comment by recanman** [comment]
@gvilums Thank you very much. If you'd like the bounty, please post an XMR address

**Comment by Letrab** [comment]
Everyone wanting to use dgram, be advised that multicast UDP is not implemented yet: https://github.com/oven-sh/bun/issues/10381
