### ISSUE TITLE
Bun add / Bun install | Installing certain package on specific WSL configurations will fail to install the package but with success message

### ISSUE THREAD

**Issue by i-Welch** [oven-sh/bun#1631]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

** Steps to reproduce**
----
- Setup a system with windows 10 and WSL 2
- Create a bun project on your Desktop directory of your windows System
- You can do that via navigating to the desktop of your windows system via the /mnt/c directory of your wsl system which maps to the C: drive of your windows system
- do a bun add `zod`
- do a bun install and note it shows 
![image](https://user-images.githubusercontent.com/46887906/208485329-d89b5022-6919-49fa-8419-4bb52a619449.png)
- do a bun install again and see that it claims to have successfully installed the package again when instead it should claim that you are already up to date.
- Notice that the `/node_modules/zod` directory is empty

### What is the expected behavior?

It is expected that the package will install properly and you will be able to use that package in your code.

### What do you see instead?

The CLI claims to install the application successfully but instead does not.

### Additional information

This isn't the case with all packages. Just a subset of packages (ex: zod).

**Work Around**
----
If you experience this issue just put your project in the wsl file system if possible. This isn't possible with all projects but for most it should be fine.

**Comment by Jarred-Sumner** [comment]
Can you try in the canary build of Bun?
```
bun upgrade —canary 
```

**Comment by alexlamsl** [comment]
Tested on WSL:
```console
$ bun add zod
bun add v0.5.1 (42e9f6e0)

 installed zod@3.20.2


 1 packages installed [560.00ms]
```
```json
$ cat package.json
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "zod": "^3.20.2"
  }
}
```
```console
$ ls node_modules
zod
$ ls node_modules/zod
LICENSE README.md index.d.ts lib package.json
```
