### ISSUE TITLE
setTimeout crashes (on WSL?)

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#164]
A simple setTimeout crashes for me:
`setTimeout(() => {console.log('done')}, 0);`
with:
```
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
```
I am guessing maybe related to running on WSL (using Ubuntu 20, WSL 2 on Windows 10).

**Comment by kriszyp** [comment]
FWIW, this still persists after upgrading to Ubuntu 22 (with 5.10 linux kernel):
```
$ ~/.bun/bin/bun upgrade
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
$ uname -r
5.10.16.3-microsoft-standard-WSL2
```

**Comment by Jarred-Sumner** [comment]
Hm.

What does `ulimit -Hl` report?
```bash
ulimit -Hl
```

I wonder if the memlock limit is set too low

**Comment by kriszyp** [comment]
It was 64. I tried bumping it up to 1024, but still get same error in `bun upgrade`.

**Comment by Jarred-Sumner** [comment]
Does it still happen if you run “sudo bun upgrade”? Sometimes the memlock
limit doesn’t actually update without sudo

**Comment by kriszyp** [comment]
Yes, it fails with the same error for sudo (root has the same memlock limit). Are you thinking it needs to be higher than 1024KB?
Also tried with "unlimited":
```
~$ ulimit -l
unlimited
~$ bun upgrade
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
```

**Comment by PhilNorfleet** [comment]
I am seeing the same error when running `bun install` on WSL

```
$ bun install
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
$ uname -r
5.10.16.3-microsoft-standard-WSL2
$ sudo env "PATH=$PATH" bun upgrade
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
```

**Comment by PhilNorfleet** [comment]
upgrading wsl kernel to the latest release fixed the issue for me.

**Comment by kriszyp** [comment]
Thanks for the tip, this is now working for me! And for posterity and anyone who visits this ticket, let me clarify what this means, as it does _not_, as I had originally assumed, mean upgrading your linux distribution (ubuntu or whatever) to a newer version (although perhaps some minimum version is needed). Instead this is actually a "Windows Update", and to enable you need to go to Settings / Windows Updates / Advanced Options and choose to enable "Receive updates for other Microsoft products when you update Windows" (and then check for updates). This will provide the actual WSL kernel update necessary to fix this issue.

**Comment by ash-grennan** [comment]
I'm getting this too, kernel is updated to latest

**Comment by thrzl** [comment]
I'm also having this error
