### ISSUE TITLE
Add snapshot testing

### ISSUE THREAD

**Issue by 5d-jh** [oven-sh/bun#1642]
### What is the problem this feature would solve?

Jest supports [snapshot testing](https://jestjs.io/docs/27.x/snapshot-testing), but Bun does not supports it.

### What is the feature you are proposing to solve the problem?

To support running tests that are using snapshot testing.

**Comment by Jarred-Sumner** [comment]
Yeah, we need to do this

**Comment by chrisAXZA** [comment]
+ Delta and Simulate testing ?

**Comment by ethanburrell** [comment]
Going to pick this up

**Comment by Electroid** [comment]
This was implemented, you can now use [`expect().toMatchSnapshot()`](https://jestjs.io/docs/expect#tomatchsnapshotpropertymatchers-hint). We still need to implement inline snapshots.
