### ISSUE TITLE
Bun install does nothing other than add bun.lockb and a folder

### ISSUE THREAD

**Issue by aquapi** [oven-sh/bun#1645]
### What version of Bun is running?

0.3.0

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Use `bun init` and bun add `bun-types`

### What is the expected behavior?

`node_modules/bun-types` should have d.ts files

### What do you see instead?

the installed package has nothing
![image](https://user-images.githubusercontent.com/87530663/209198836-c42309cd-f66f-493f-82dd-f9c1484705f1.png)

**Comment by alexlamsl** [comment]
Seems to work now with `bun@0.4.0` &minus; as tested on WSL:
```console
$ bun -v
0.4.0
$ bun init
bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit

package name (test-bun):
entry point (index.ts):

Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts

$ bun add bun-types
bun add v0.4.0 (a94bba63)

 installed bun-types@0.4.0

[32.00ms] done
$ ls node_modules/bun-types
README.md  package.json  types.d.ts
```
