### ISSUE TITLE
Detected offset inconsistency

### ISSUE THREAD

**Issue by AlexBlokh** [oven-sh/bun#1646]
### What version of Bun is running?

v0.3.0

### What platform is your computer?

Darwin 21.5.0 arm64 arm

### What steps can reproduce the bug?

Run this query on Northwind database
```typescript
sqlite.prepare('select * from "employee" left join "employee" "recipient" on "recipient"."id" = "employee"."reports_to" where "employee"."id" = 1')
  .all();
```

or
```typescript
sqlite.prepare('select * from "order" left join "order_detail"  on "order"."id" = "order_detail"."order_id" left join "product"  on "order_detail"."product_id" = "product"."id" where "order"."id" = 17568')
  .all();
```

### What do you see instead?

```
etected offset inconsistency: numberOfSlotsForMaxOffset doesn't match totalSize!
this = 0x30002f3c0
transitionOffset = 18
maxOffset = 18
m_inlineCapacity = 36
propertyTable = 0x1187463b0
numberOfSlotsForMaxOffset = 19
totalSize = 18
inlineOverflowAccordingToTotalSize = 0
numberOfOutOfLineSlotsForMaxOffset = 0
```

**Comment by mingodad** [comment]
When testing on Ubunut 18.04 amd64 with bun 0.4.0 (after fixing wrong column names) there is no error:
```
import { Database } from "bun:sqlite";

const db = Database.open("./src/northwind.sqlite");

const sql = db.prepare('select * from employee left join employee recipient on recipient.id = employee.reportsto where employee.id = 1');
sql.all();
const sql2 = db.prepare('select * from "order" left join orderdetail  on "order".id = orderdetail.orderid left join product  on orderdetail.productid = product.id where "order".id = 17568');
sql2.all();
```
Output:
```
bun "test-sqlite.js"
[0.02ms] ".env"
```

**Comment by mingodad** [comment]
By the way when testing `bench/sqlite/bun.js` the resulting downloaded database is named `Northwind_large.sqlite` and not `northwind.sqlite`, I did a symbolic link to be able to run it:
```
ln -s Northwind_large.sqlite northwind.sqlite
```

**Comment by mingodad** [comment]
Found the problem with wrong database filename, I was executing  `download.sh` in `bench/sqlite/src` -> `bash download.sh` instead of `bench/sqlite` -> `bash src/download.sh`.

**Comment by Jarred-Sumner** [comment]
This bug was caused by an optimization which didn’t handle every edgecase correctly (such as when the number of columns in the table doesn’t match up with the number of columns returned in a row) 

The optimization was introduced in v0.3.0 and disabled in v0.4.0
