### ISSUE TITLE
Request should have a `signal`

### ISSUE THREAD

**Issue by jacob-ebey** [oven-sh/bun#1653]
### What is the expected behavior?

Each request should have an abort signal.

### Additional information

@Jarred-Sumner and I had chatted about this a while back and not sure if I ever filed an issue or if it was tracked anywhere so just adding this to make sure it doesn't fall through the cracks.

**Comment by Jarred-Sumner** [comment]
thanks for filing

**Comment by ThatOneBro** [comment]
Looks like I accidentally created a duplicate issue here with #1864, should have kept this one but since the other issue is already linked to an issue on the Elysia repo, I'll close this one. Thank you @jacob-ebey
