### ISSUE TITLE
HTTPS File Serve does not work

### ISSUE THREAD

**Issue by dalisoft** [oven-sh/bun#1654]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 5.15.0-56-generic x86_64 x86_64

### What steps can reproduce the bug?

Download https://github.com/nanoexpress/static-serve-benchmark/blob/master/src/bun.js and run `bun run --hot bun.js`

### What is the expected behavior?

Running server and serve file

### What do you see instead?

Delaying/stuck at loading

### Additional information

I am see log of `Started server https://0.0.0.0:4400` and if change `Response(file())` to `Response('String')` it works

**Comment by jojobyte** [comment]
@Jarred-Sumner Looks like file streaming does not work when SSL is enabled on canary in linux/Pop!_OS similar to how WebSockets wasnt working

```sh
# https://github.com/FiloSottile/mkcert
mkcert -install
mkcert localhost 127.0.0.1 ::1
```

```html
<!-- ./index.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>😢</title>
</head>
<body>
  <div id="app">
    <h1>this should work but it doesnt</h1>
  </div>
</body>
</html>
```

```js
// ./index.js
import { serve, file, } from "bun";

serve({
  port: 3000,
  keyFile: "./localhost.key.pem", // commenting these out
  certFile: "./localhost.pem", // and it works fine
  fetch(req, server) {
    console.log(
      "fetch",
      req,
    );

    return new Response(
      file('./index.html'),
      {
        headers: {
          "Content-Type": "text/html; charset=utf-8",
        },
      },
    );
  },
})
```

Some refs to other messages
https://twitter.com/jarredsumner/status/1613765493680373760
https://discord.com/channels/876711213126520882/1064551470097240084
https://discord.com/channels/876711213126520882/1063287647147135138/1063287647147135138

**Comment by jojobyte** [comment]
Thanks again for the quick fix. Still seems to have an issue with file streaming though.

```js
import { serve, file, } from 'bun';

serve({
  port: 3000,
  keyFile: './localhost.key.pem',
  certFile: './localhost.pem',
  async fetch(req, server) {
    console.log(
      'fetch',
      req,
    )

    return new Response(
      file('./index.html'), // doesnt work with SSL, should it?
      await file('./index.html').text(), // works!
    )
  },
})
```

https://github.com/oven-sh/bun#streaming-files-with-bunserve
