### ISSUE TITLE
`bun run` does not pass arguments to script

### ISSUE THREAD

**Issue by dalisoft** [oven-sh/bun#1655]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 5.15.0-56-generic x86_64 x86_64

### What steps can reproduce the bug?

Download https://github.com/nanoexpress/static-serve-benchmark/blob/master/src/bun.js and run `bun run --hot bun.js`

### What is the expected behavior?

Change/reload script on file change like `nodemon`

### What do you see instead?

Non changeable old script behavior

### Additional information

Related issue: #1654

**Comment by birkskyum** [comment]
Needs reproduction.
@dalisoft , the link you provided is broken. Is this still an issue?

**Comment by c4software** [comment]
Same problem for me, partial hot reload on MacOS :

My Sample File : 

```ts
console.log("Listening on http://localhost:8080");
const fakeData = [
    { id: 1, name: "John Doe" },
    { id: 2, name: "Jane Doe" },
    { id: 3, name: "John Smith" },
    { id: 4, name: "Jane Smith" },
    { id: 99, name: "John Wayne" },
    ];

Bun.serve({
    development: true,
    port: 8080,
    fetch(req) {
        const url = new URL(req.url);
        if (url.pathname === "/") return Response.json({ message: `Hello ${Bun.env.APP_NAME}`, version: Bun.env.APP_VERSION});
        if (url.pathname === "/list") return Response.json(fakeData);
        return Response.json({ message: "Not found" }, { status: 404 });
      },
})
```

The **non working** command (command declared in `scripts` section of the `package.json`) : 

```sh
bun --hot run serve
```

The **working** command, pointing directly to the script file : 

```sh
bun --hot run index.ts
```

**Comment by dalisoft** [comment]
@birkskyum I re-opened repository, made it private & archived before due of no time of changing or fixing security issues, sorry

**Comment by dalisoft** [comment]
As `v1.0.35` this issue was fixed. Thanks you developers which does amazing job
