### ISSUE TITLE
Bun does not support `SIGTERM` listeners

### ISSUE THREAD

**Issue by ghoullier** [oven-sh/bun#1657]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

1. create `server.js` file with following content:
```js
const http = require("node:http");

const server = http.createServer((req, res) => {
  res.write("hello");
  res.end();
});

server.listen(4000, () => {
  console.log("listening", { pid: process.pid });
});

process.on("SIGINT", () => {
  console.log("closing", "sigint");
  server.close(() => {
    console.log("closed");
  });
});
```

3. run  command below 

```sh
bun server.js
```

4. Stop process using Ctrl+C or  run command `kill -int <pid>`

### What is the expected behavior?

Process should output: 

```sh
closing sigint
closed
```

### What do you see instead?

Callback registered with `process.on("SIGINT", callback)` is not called.

### Additional information

This feature is important to support graceful shutdown in cloud env like kubernetes.

**Comment by Electroid** [comment]
Thanks for reporting, yes, we'll get this added.

**Comment by Electroid** [comment]
Tracking this here: #429
