### ISSUE TITLE
Don't log .env reads by default or have ability to hide them

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#1666]
### What is the problem this feature would solve?

If there is .env in folder when I try to run my script with bun, I get:

```
 bun main.ts
[0.32ms] ".env"
test
```

And this happens every time I run it. I would like to not see this. If not by default, then at least by passing some flag. I tried `--silent` and `-q` for quiet, both failed. 

I would argue default behaviour should be clean stdout output or error.

### What is the feature you are proposing to solve the problem?

```
 bun main.ts
test
```

Would be perfect. Or:

```
 bun -q main.ts
test
```

That's what Deno uses for example.

**Comment by Jarred-Sumner** [comment]
yes, this is necessary

**Comment by rolfb** [comment]
Am I doing something wrong here since .env load time still shows when using `--silent` on 0.5.7?

```shell
bun -v
0.5.7

echo "console.log('Hi, Mom')" > hello.ts; bun hello.ts
Hi, Mom

touch .env; echo "console.log('Hi, Mom')" > hello.ts; bun hello.ts
[0.03ms] ".env"
Hi, Mom

touch .env; echo "console.log('Hi, Mom')" > hello.ts; bun --silent hello.ts
[0.02ms] ".env"
Hi, Mom
```

**Comment by nikivdev** [comment]
I can replicate it too. `--silent` did not thing to stop the reappearing same log. 😞
