### ISSUE TITLE
Forced 206 Partial Content in response

### ISSUE THREAD

**Issue by qwelias** [oven-sh/bun#1668]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 6.1.1-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. `bun init`
2. **index.ts**
```ts
export default {
    async fetch () {
        return new Response(Bun.file('package.json'), { status: 200 })
    },
} 
```
3. `bun run index.ts`
4. `curl -I http://localhost:3000`

### What is the expected behavior?

HTTP/1.1 200 OK
content-type: application/json;charset=utf-8
content-length: 124

### What do you see instead?

HTTP/1.1 206 Partial Content
content-type: application/json;charset=utf-8
content-length: 124
content-range: bytes 0-123/*

**Comment by Jarred-Sumner** [comment]
Two bugs here:
1. The content-range header is being passed even if the entire file is being sent
2. Explicitly setting `status` should disable the content-range header from being sent.
