### ISSUE TITLE
Unsupported HTTP methods

### ISSUE THREAD

**Issue by qwelias** [oven-sh/bun#1669]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 6.1.1-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. index.ts:
```ts
export default {
    async fetch (req: Request) {
        return new Response(req.method)
    },
}
```
2. `bum run index.ts`
3. `for m in $(node -e 'console.log(...require("http").METHODS)'); do curl -X $m http://localhost:3000 &>/dev/null || echo $m; done` (echoes method name if curl failed)

### What is the expected behavior?

_none_

### What do you see instead?

ACL
BIND
CHECKOUT
COPY
LINK
LOCK
M-SEARCH
MERGE
MKACTIVITY
MKCALENDAR
MKCOL
MOVE
NOTIFY
PROPFIND
PROPPATCH
PURGE
REBIND
REPORT
SEARCH
SOURCE
SUBSCRIBE
UNBIND
UNLINK
UNLOCK
UNSUBSCRIBE

### Additional information

I've failed to find a list of supported HTTP methods, so filing this as a bug.

**Comment by moderation** [comment]
I couldn't get your script to work but this works with fish.
`for m in (node -e 'console.log(...require("http").METHODS)' | xargs -n1 echo); echo $m && xh $m http://localhost:3001 && echo; end`
