### ISSUE TITLE
^C does not terminate `bun init`

### ISSUE THREAD

**Issue by JacksonKearl** [oven-sh/bun#1673]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

`bun init` // `^C` (control-C)

### What is the expected behavior?

Program terminates cleanly

### What do you see instead?

`^C` written to console.

`^D` does properly terminate the program, but not cleanly. 

### Additional information

<img width="829" alt="image" src="https://user-images.githubusercontent.com/8586769/209715990-f339439b-bfa6-4bb4-b231-f25c1950bd4c.png">

**Comment by Jarred-Sumner** [comment]
hmm i am unable to repro on macOS or linux

**Comment by JacksonKearl** [comment]
Strange, I can't repro anymore either. Will reopen if it comes up again.
