### ISSUE TITLE
copyFile: Cross-device link error

### ISSUE THREAD

**Issue by theoparis** [oven-sh/bun#1675]
EDIT: This also breaks create-vite, which seems to be related to the /tmp folder mentioned below.

### What version of Bun is running?

0.4.0

### What platform is your computer?

Linux 6.1.0-gentoo x86_64 AMD Ryzen 5 5600X 6-Core Processor

### What steps can reproduce the bug?

Attempting to use `fs.promises.copyFile` across btrfs fileystems.

### What is the expected behavior?

The file to be succesfully copied into the target folder.

### What do you see instead?

EXDEV: Cross-device link
   path: "/home/theo/.bun/bin/bun"
syscall: "copy_file_range"
  errno: -18

### Additional information

See https://github.com/oven-sh/bun/blob/main/src/bun.js/node/node_fs.zig#L2621.

The following code works fine.
```
export const copyFile = async (input: string, output: string) => {
  await Bun.write(output, await Bun.file(input).arrayBuffer());
};
```

If you were to remove the arrayBuffer call it has the same issue as earlier.

**Comment by Jarred-Sumner** [comment]
To fix this, we will need to detect `EXDEV` and then implement read & write functions in copyFile within node_fs.zig

**Comment by v3nntrnx** [comment]
I also have to mention, the same error happens when I try to copy a file into a sub-dirrectory inside the linux /tmp folder.
