### ISSUE TITLE
OutOfMemory Error when using "bun install"

### ISSUE THREAD

**Issue by Northernside** [oven-sh/bun#1677]
### What version of Bun is running?

0.4.0 (latest canary build; commit: ef3c9b7c6d6557f7cf50210f4a54187351d47ca8)

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

1. Upgrade bun to commit ef3c9b7c6d6557f7cf50210f4a54187351d47ca8
2. Open up a project
3. Run `bun i(nstall)`

Result: 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/60970791/209884523-af7edeef-98b1-4f6f-b1cc-4d05b8b850b6.png">

### What is the expected behavior?

Bun should finish installing all dependencies from the `package.json`.

### What do you see instead?

An error telling me that bun failed to serialize the lockfile because of `OutOfMemory`.

### Additional information

LMK if you need something (more) detailed!

**Comment by Northernside** [comment]
Thank you 🫶

**Comment by Northernside** [comment]
Maybe I did something wrong while upgrading (I rang `bun upgrade --canary` again), but it still seems to not be working. 👀
<img width="591" alt="image" src="https://user-images.githubusercontent.com/60970791/209890390-1473687d-8934-483b-94d8-344b61fd5e0d.png">

**Comment by Jarred-Sumner** [comment]
It takes about an hour for CI to build

**Comment by Northernside** [comment]
Ahh, alright, sorry! Thank you :D
