### ISSUE TITLE
Implement a string differ 

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1679]
The output of `bun wiptest` when tests fail is ugly and not informative enough.

To fix that, we should have a pretty printer which prints a green/red diff. Like on GitHub or in Jest.

Some things we should look at:
- https://github.com/google/diff-match-patch
- [The Histogram Diff Algorithm](https://tiarkrompf.github.io/notes/?/diff-algorithm/)
- [libxdiff](https://directory.fsf.org/wiki/LibXDiff)

We should implement this ourself in Zig. It should do zero temporary memory allocations (only stack space). 

We should also consider exposing it as an API in Bun:
```ts
import {diff, apply, print} from 'bun:diff';

const patch = diff("abc", "abcd");
print(patch);
```

Current state of `bun wiptest`:
![image](https://user-images.githubusercontent.com/709451/209901621-bde1d6a3-4131-4fd0-bb5b-93eb362c9a38.png)

**Comment by Electroid** [comment]
Done in https://github.com/oven-sh/bun/pull/2122
