### ISSUE TITLE
Test suite `beforeAll` is not executed

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#1688]
### What version of Bun is running?

0.4.0

### What platform is your computer?

WSL / Windows

### What steps can reproduce the bug?

Use Surreal.JS with Bun:

```ts
import { beforeAll, it, describe, expect, afterAll } from 'bun:test';
import Surreal from 'surrealdb.js';

const TEST_DB = 'tests';
const db = new Surreal(process.env.SURREAL_HOST);

describe('Database', async () => {
	beforeAll(async () => {
		await db.signin({
			user: 'root',
			pass: 'root',
		});

		await db.use('test_namespace', TEST_DB);

		await db.query('DEFINE DATABASE tests');
		console.log('beforeAll');
	});

	afterAll(async () => {
		await db.query('REMOVE DATABASE tests');
		db.close();

		console.log('afterAll');
	});

	it('Database connection', async () => {
		expect(db).toBeDefined();
	});
});

```

### What is the expected behavior?

I expect the code provided in `beforeAll` to be executed but there are no DB calls or console.logs

### What do you see instead?

Only the `afterAll` is executed and logged

**Comment by Jarred-Sumner** [comment]
I think this is an issue with async

**Comment by itsezc** [comment]
> I think this is an issue with async

Yup, when I move the logic from `beforeAll` into the parent describe (with async), everything seems to work as expected - even the `afterAll` works 🤔
