### ISSUE TITLE
"make devcontainer" build error in Windows

### ISSUE THREAD

**Issue by i11010520** [oven-sh/bun#1690]
### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### How did you attempt to install or upgrade?

In host Windows:

1. install docker
2. git clone the latest bun code, as the commit-id is `b86915c80819e61e6e1932d7802a4c31c73094e9`
3. open vscode in bun/, and reopen it in devcontainer

Inside devcontainer, follow the build/README.md:

-   gh auth login
-   gh repo clone oven-sh/bun . -- --depth=1 --progress -j8
-   make devcontainer # then, error terminated

### What do you see instead?

```
src/bun.js/bindings/simdutf.cpp:3995:1: error: '#pragma clang attribute pop' with no matching '#pragma clang attribute push'
SIMDUTF_UNTARGET_REGION
^
/build/bun/src/bun.js/bindings/simdutf.h:160:33: note: expanded from macro 'SIMDUTF_UNTARGET_REGION'
#define SIMDUTF_UNTARGET_REGION _Pragma("clang attribute pop")
                                ^
<scratch space>:346:8: note: expanded from here
 clang attribute pop
       ^
src/bun.js/bindings/simdutf.cpp:18845:1: error: '#pragma clang attribute pop' with no matching '#pragma clang attribute push'
SIMDUTF_UNTARGET_REGION
^
/build/bun/src/bun.js/bindings/simdutf.h:160:33: note: expanded from macro 'SIMDUTF_UNTARGET_REGION'
#define SIMDUTF_UNTARGET_REGION _Pragma("clang attribute pop")
                                ^
<scratch space>:359:8: note: expanded from here
 clang attribute pop
       ^
```

### Additional information
some C/C++ configuration warning:
```
[12/31/2022, 10:14:41 AM] Unable to resolve configuration with compilerPath "/opt/homebrew/opt/llvm/bin/clang++".  Using "/usr/bin/gcc" instead.
[12/31/2022, 10:14:41 AM] Unable to resolve configuration with compilerPath "/opt/homebrew/opt/llvm/bin/clang++".  Using "/usr/bin/gcc" instead.
```
_No response_

**Comment by theseyan** [comment]
A quick workaround until this is fixed, is commenting out the two lines:
`src/bun.js/bindings/simdutf.cpp:3995` and `src/bun.js/bindings/simdutf.cpp:18845`

**Comment by i11010520** [comment]
> A quick workaround until this is fixed, is commenting out the two lines: `src/bun.js/bindings/simdutf.cpp:3995` and `src/bun.js/bindings/simdutf.cpp:18845`

ok
but `simdutf.*` is auto-generated codes

**Comment by lemire** [comment]
Please try with https://github.com/simdutf/simdutf/releases/tag/v2.1.0

**Comment by i11010520** [comment]
> Please try with https://github.com/simdutf/simdutf/releases/tag/v2.1.0

@lemire Thanks for your suggestion, could you tell me how to specify simdutf's tag version in bun?
I didn't find out the location of simdutf submodule.
There're only two auto-generated simdutf.h/simdutf.cpp source file.

**Comment by Jarred-Sumner** [comment]
@i11010520 I have updated bun to use the new version

Please `git pull` and try again

For future reference, it's in src/bun.js/bindings/simdutf.cpp

**Comment by i11010520** [comment]
> @i11010520 I have updated bun to use the new version
> 
> Please `git pull` and try again

@Jarred-Sumner Thanks for your quick repair! `make devcontainer`, `make dev`, and `bun-debug` all built ok in dev-container now.
