### ISSUE TITLE
console.log() should output object for URL instead of string

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#1699]
### What version of Bun is running?

0.4.0

### What platform is your computer?

windows11-WSL

### What steps can reproduce the bug?

`
console.log(new URL("http://example.com/test"));
`

The output is:`http://example.com/test`

### What is the expected behavior?

Should be the URL object

**Comment by Electroid** [comment]
@robobun 

```js
console.log(new URL("http://example.com/test"));
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
http://example.com/test
```
<details>
  <summary>Code</summary>
  
```tsx
console.log(new URL("http://example.com/test"));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by Jarred-Sumner** [comment]
```js
❯ bun /tmp/a.js
URL {
  href: "http://example.com/test",
  origin: "http://example.com",
  protocol: "http:",
  username: "",
  password: "",
  host: "example.com",
  hostname: "example.com",
  port: "",
  pathname: "/test",
  hash: "",
  search: "",
  searchParams: {},
  toJSON: [Function: toJSON],
  toString: [Function: toString]
}
```

Fixed some time ago
