### ISSUE TITLE
Serve /public/ as root URL by default

### ISSUE THREAD

**Issue by drush** [oven-sh/bun#170]
bun serves index.html from the /public folder as the server root, ie:

./public/index.html -> http://localhost:3000/index.html

However running bun from the project root serves from the root, so any other files in /public need to be accessed 
./public/data.json -> http://localhost:3000/public/data.json

CHANGE: /public should be the default root for all served resources.

**Comment by Jarred-Sumner** [comment]
Yeah, I would call this a bug.

**Comment by steveblue** [comment]
I was a little confused by this behavior at first too and had to implement the following in the index.html to get some static css and favicon.ico to work with `bun dev`, which seemed contrary to examples in the repo. I started from scratch, not using a framework, didn't use `bun create` if that helps. Running bun 0.1.4

```html
  <head>
    <link rel="stylesheet" href="./public/global.css" />
    <link rel="icon" type="image/x-icon" href="./public/favicon.ico">
  </head>
```

**Comment by birkskyum** [comment]
This is resolved. Adding a `index.html` and `test.html` in `/public/`.

The index.html will be reached at:
- `http://localhost:3000/`

The test.html will be reached at:
- `http://localhost:3000/test`
- `http://localhost:3000/public/test.html`

Other unknown paths will lead to index.html, including
- `http://localhost:3000/public/test`

@steveblue , @drush , do you find this to be resolved as well?
