### ISSUE TITLE
Can't install git type dependencies

### ISSUE THREAD

**Issue by agustinkassis** [oven-sh/bun#1703]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Include a dependency with like this one

`"git+https://github.com/ethereumjs/ethereumjs-abi.git"`

### What is the expected behavior?

Install it correctly

### What do you see instead?

Get the following error

`error:  Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"`

**Comment by olivernosto** [comment]
Same issue, also for `github:google/postcss-rename`

**Comment by Jarred-Sumner** [comment]
This isn't implemented yet but @dylan-conway is working on it.
