### ISSUE TITLE
`bun pm cache rm` is unusable due to being overridden by `bun pm cache`

### ISSUE THREAD

**Issue by jhmaster2000** [oven-sh/bun#1720]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 5.15.79.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run `bun pm cache rm`

### What is the expected behavior?

It clears the cache

### What do you see instead?

Instead it acts the same as if you ran `bun pm cache` since that command seems to have higher priority.

### Additional information

Going off the information given by running `bun pm`:
```
  ...
  bun pm cache        print the path to the cache folder
  bun pm cache rm     clear the cache
```

Updated for Bun v0.6.3 (issue persists)

**Comment by pepper-lees** [comment]
FYI: Tested on 0.5.8 and the issue still remains.

Side note: `bun pm cache` should probably print a newline but it doesn't.

Other side note: `bun pm cache | xargs rm -rf` works for me as a temporary substitute on Linux.

**Comment by silverwind** [comment]
Another related problem, it refuses to work when there is no package.json in the working directory:

```bash
$ bun pm cache
error: MissingPackageJSON
bun could not find a package.json file.

**Comment by jhmaster2000** [comment]
That's expected, you're missing the `-g` flag so its trying to do a local operation.

**Comment by silverwind** [comment]
> That's expected, you're missing the `-g` flag so its trying to do a local operation.

Okay, so it's just a docs issue as docs describe this command as a "global" one:

<img width="438" alt="image" src="https://github.com/oven-sh/bun/assets/115237/2438ad7b-483f-43f2-9d49-c1c4bdeecb8b">

**Comment by OliverWich** [comment]
I also cannot prune my global cache (e.g. for bunx) with `bun pm cache rm -g`, it keeps complaining about a missing package.json file

**Comment by pepper-lees** [comment]
> I also cannot prune my global cache (e.g. for bunx) with `bun pm cache rm -g`, it keeps complaining about a missing package.json file

I'm getting different behavior on v1.0.1. All permutations of `bun pm cache rm -g` (`bun -g pm cache rm`, `bun pm -g cache rm`, `bun pm cache -g rm`) exhibit the same behavior as described in the issue, i.e., printing the cache location and exiting. For me, only `bun pm cache` and `bun pm cache rm` (no `-g`) complain about a missing package.json.
