### ISSUE TITLE
Transpiler must rename symbols banned in strict mode

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1724]
Examples:
- `interface`
- `public`

This currently breaks `serve` when used with `bunx`

```zig
❯ bunx --bun serve
341 | 		break;
342 | 	}
343 |
344 | 	if (entry) {
345 | 		const {public} = config;
346 | 		config.public = path.relative(cwd, (public ? path.resolve(entry, public) : entry));
     ^
SyntaxError: Cannot use abbreviated destructuring syntax for reserved name 'public' in strict mode.
      at /usr/lib/node_modules/serve/bin/serve.js:346:2
```

Since bun only supports ESM & strict mode, this is necessary to do.

**Comment by Jarred-Sumner** [comment]
An alternative approach is commenting out these lines in [Keywords.table](https://github.com/oven-sh/WebKit/blob/main/Source/JavaScriptCore/parser/Keywords.table)

```
# Reserved for future use in strict code.
implements      RESERVED_IF_STRICT
interface       RESERVED_IF_STRICT
package         RESERVED_IF_STRICT
private         RESERVED_IF_STRICT
protected       RESERVED_IF_STRICT
public          RESERVED_IF_STRICT
static          RESERVED_IF_STRICT
```

**Comment by paperclover** [comment]
I think this is related: `arguments` needs to be renamed in addition to these keywords.

This is breaking runtime checks on the bundle test `default/ArgumentsSpecialCaseNoBundle` in [this file](https://github.com/oven-sh/bun/blob/jarred/new-bundler/test/bundler/esbuild/bundler_default.test.ts), which are currently just set to use node.

Edit: There's definetly some other symbols to handle too: `var eval = 2;` not sure on all of them.
