### ISSUE TITLE
Can't make a Bun.file using base64 string buffer

### ISSUE THREAD

**Issue by SwatDoge** [oven-sh/bun#1729]
### What version of Bun is running?

0.4.0

### What steps can reproduce the bug?

```ts
const file = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAbSURBVChTYxiygPH///9QJjbABKVxAEqkGRgAb8cDBcxO9iAAAAAASUVORK5CYII=";

const buffer = Buffer.from(file, "base64");
const fileBlob = Bun.file(buffer);
console.log(fileBlob.size);
console.log(fileBlob.type);
```

### What is the expected behavior?

Two console logs that returns the file size and the mimetype.

### What do you see instead?

The console outputs:
```
0
application/octet-stream
```

### Additional information

Please feel free to change the title, I do not know terminology.

Had a conversation about this with Jarred in bun discords' #help-chat:
https://discord.com/channels/876711213126520882/1060497945096630364

**Comment by jimmywarting** [comment]
I would suggest doing this way to avoid any NodeJS or Bun specific tricks, as it's more cross functional for any engine. 

```js
const file = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAbSURBVChTYxiygPH///9QJjbABKVxAEqkGRgAb8cDBcxO9iAAAAAASUVORK5CYII="

const blob = await fetch(file).then(res => res.blob())
console.log(blob.size)
console.log(blob.type)
```

if you really want a sync way: then i suppose you could use `Buffer.from` or any other base64 parser.

then you could do:
```js
const buffer = Buffer.from(file, "base64")
const blob = new Blob([buffer], { type: 'image/png' })
console.log(fileBlob.size)
console.log(fileBlob.type)
```

on a 2nd note i would try to avoid using base64 in the first place and instead start working with binary directly. base64 is a wasteful overhead. read: https://github.com/tc39/proposal-arraybuffer-base64/issues/6

**Comment by Electroid** [comment]
See #1741 for this won't be fixed. Basically, Bun matches Node.js behaviour.
