### ISSUE TITLE
Napi::External Passed from JS -> Native Code Not Typed Correctly

### ISSUE THREAD

**Issue by cryptodeal** [oven-sh/bun#1733]
### What version of Bun is running?

0.4.1

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

Clone the following repo (branch: `handle_as_external`): https://github.com/cryptodeal/gen-napi

Ensure `flashlight`/`arrayfire` are installed: https://github.com/facebookresearch/shumai#install

Ensure switched to branch `handle_as_external`.

Build bindings: `bun install`

Run: 
```sh
bun bun_repro.cjs
```

Throws `TypeError` because `Napi::External<fl::Tensor>` passed into `_add` fails the following check `if (!info[index].IsExternal())`.

### What is the expected behavior?

The argument passed is `Napi::External<fl::Tensor>` and the same operation works from node. 

To demo expected behavior:
```sh
node node_works.cjs
```

### What do you see instead?

```sh
13 |       this._native_self = t
14 |     }
15 |   }
16 | 
17 |   add(other) {
18 |     return new Tensor(_add(this._native_self, other._native_self))
                         ^
TypeError: `add` expects args[0] to be `Napi::External<fl::Tensor>` `Tensor`
      at add (/Users/cryptodeal/gen-napi/test/js/tensor.cjs:18:22)
      at /Users/cryptodeal/gen-napi/tensor.cjs:19:9
      at /Users/cryptodeal/gen-napi/tensor.cjs:12:13
      at /Users/cryptodeal/gen-napi/tensor.cjs:27:6
```

**Comment by bwasti** [comment]
The bug is related to the napi_type not being correctly tracked: https://github.com/nodejs/node-addon-api/blob/main/napi-inl.h#L734

**Comment by Jarred-Sumner** [comment]
yeah that's the bug

**Comment by Jarred-Sumner** [comment]
```
❯ node node_works.cjs
0.6025929160118103 seconds to calculate 10005.385574519634
bytes:  33880

❯ bun-debug node_works.cjs
0.49214683299999995 seconds to calculate 10005.387356042862
bytes:  15396920
```
why is bytes so much higher in bun?

**Comment by cryptodeal** [comment]
Huh, we're using Napi::External w a Finalizer passed in as such:
```cc
template <typename T>
static Napi::External Napi::External::New(napi_env env,
                    T* data,
                    Finalizer finalizeCallback);
```

So at least in node, it's freeing @ Garbage Collection. 

Once canary build finishes, I can test w manually triggering GC to see whether the underlying data is being freed @ GC.

**Comment by Jarred-Sumner** [comment]
I think its a GC scheduling thing. Sticking a `Bun.gc(true)` before `bytesUsed` is called makes the number report 0

**Comment by cryptodeal** [comment]
Awesome; really appreciate the you getting this resolved so quickly! :)
