### ISSUE TITLE
Buffer methods throw range errors for out of bounds indices

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#174]
The native typed array methods, as well as Node's buffer tolerate index references outside the range of the source array, and automatically adjust to last item, but bun is throw range errors:
```
new Uint8Array(8).slice(4,20) // returns 4 byte array
Buffer.alloc(8).slice(4,20) // returns 4 byte array in node, but throws range error in bun
```
The same is true of `subarray` and Buffer's `copy` methods, as well (and probably others, I assume).

**Comment by Electroid** [comment]
This should have been fixed in https://github.com/oven-sh/bun/commit/38db5f1c83c40546420ee5379876456a6bd125ac, but let's confirm.

@robobun

```js
console.log(Buffer.alloc(8).slice(4,20));
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
Uint8Array(4) [ 0, 0, 0, 0 ]
```
<details>
  <summary>Code</summary>
  
```tsx
console.log(Buffer.alloc(8).slice(4,20));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
