### ISSUE TITLE
Use Tar instead of Unzip

### ISSUE THREAD

**Issue by mucookul** [oven-sh/bun#1740]
### What is the problem this feature would solve?

Removes a dependency for one that is preinstalled in most supported platforms, would also stop people from trying to run on windows.

### What is the feature you are proposing to solve the problem?

Use tar instead of unzip in install.sh to remove all dependencies not preinstalled. 

### What alternatives have you considered?

There isn't really any preinstalled application that could do the same thing as tar.

**Comment by Jarred-Sumner** [comment]
macOS only supports signing/provisioning binaries with .zip files - not .tar.gz

That's the only reason we use zip files
