### ISSUE TITLE
MySQL/8.0 Benchmark?

### ISSUE THREAD

**Issue by Jurugi** [oven-sh/bun#1742]
### What is the problem this feature would solve?

I'd like to see if there'd be any improvement here for a usual SQL server. It's great that SQLite will improve speeds and will fit the needs for many apps, up to 8x faster. But I figure this is a combination of memory handling and file handling, as SQLite is a situational direct file read/write operation database; so are others, but they sometimes handle it differently. I want to know is it handling a bit faster for MySQL? Or I guess, there's really no room for improvement there other than in the pipeline between MySQL/files and the running code? In such case it'd be good to know even as it's already quite fast. 

### What is the feature you are proposing to solve the problem?

Potentially benchmark or show if there is an improvement, or mark as 'none' for MySQL, potentially MSSQL, MariaDB, etc.

### What alternatives have you considered?

None, it's not that important but MySQL8 (or latest ones) are usually my choice of DB and have all the functionality anyway; being 'faster' or needing upgrading just becomes a matter of preference.  

Anyway, no one seems to have tried it, and I haven't tried bun yet.

**Comment by Electroid** [comment]
We are working on `bun:sql`, for now it will support Postgres, but we will support MySQL in the future.
