### ISSUE TITLE
Throwing error: "Cannot access uninitialized variable"

### ISSUE THREAD

**Issue by Northernside** [oven-sh/bun#1743]
### What version of Bun is running?

0.4.1 (d5565ab2cdd7099a5852ba5ba6d180ef291af084)

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Run the following commands:
1. `git clone https://github.com/LiloLookup/Lilo`
2. `git checkout switch/bun`
3. `git submodule update --init --recursive --force`
4. `bun install`
5. `bun apps/lilo/src/index.ts`

When running the 5th command, my code already fails/crashes at starting up due to the error mentioned in the following sections. The "affected" snippets are also put into the next 2 sections to provide a better context within these sections, I hope that's fine :D

### What is the expected behavior?

Bun should be able to access those variables, but instead it tells the user, that it can't because those are uninitialized.
Those are the variables (except for the one in the middle): https://github.com/LiloLookup/Lilo/blob/cde3211ca1fea32ac56b80f86da13a242ca9fa80/packages/api/src/index.ts#L27-L29

### What do you see instead?

This is the following error:
```js
1 | __require as require_ab102cbd93061951
2 | } from "bun:wrap";
3 | var __dirname = "/Users/elias/Development/LiloLookup/Lilo/packages/api/src/routes/server";
4 | import * as $6a88d62f from "/Users/elias/Development/LiloLookup/Lilo/packages/api/src/index.ts";
5 | 
6 | var {defaultServerIcon, notFoundHTML} = require_ab102cbd93061951($6a88d62f);
   ^
ReferenceError: Cannot access uninitialized variable.
      at /Users/elias/Development/LiloLookup/Lilo/packages/api/src/routes/server/view.ts:1:0
```

This is where those variables originally come from:
https://github.com/LiloLookup/Lilo/blob/cde3211ca1fea32ac56b80f86da13a242ca9fa80/packages/api/src/routes/server/view.ts#L1

Note: Actually I don't even know if this is really a bug or just a stupid thing caused by me, please tell me carefully what I did wrong and how to avoid it if it's my fault 🙏
I'm confused, because it used to work on Node.js `v18.10.0` & `v19.3.0`.

**Comment by Northernside** [comment]
Also, off-topic, but do you know how to embed the linked code lines into the text field? Because as far as I know you could embed them, so that they're viewable within the section/text without having to open them in another tab? 👀

**Comment by Jarred-Sumner** [comment]
Can you try setting `"type": "module"`  in each package's package.json?

**Comment by Jarred-Sumner** [comment]
Ah that won't fix it

**Comment by Northernside** [comment]
It fixed it for me though, thank you!
I also found this to explain the reason, because I also wanted to know what it does: https://stackoverflow.com/a/62554884/17241423

**Comment by Northernside** [comment]
Should I close this issue now, or is there something else you want to mention, because you last stated that it won't fix my issue?
