### ISSUE TITLE
Support for `decompress` package

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1758]
[`decompress`](https://www.npmjs.com/package/decompress) is a popular package that decompresses files. After the issues below are fixed, it should work in Bun.

- #1757

**Comment by ThatOneBro** [comment]
Oh I think I fixed this, maybe it ended up in another branch. I'll submit a PR.

EDIT: Looks like the fix didn't work for this edge case. I'll be fixing this in a refactor of `node:streams` I'm working on.

**Comment by ThatOneBro** [comment]
Working in canary now, likely since: https://github.com/oven-sh/bun/commit/4dfc09018fe3fee391afc7b4edc129730bd037b8

See: https://github.com/oven-sh/bun/issues/1757#issuecomment-1406112302
