### ISSUE TITLE
dns.resolveSrv does not resolve the same as node

### ISSUE THREAD

**Issue by sp90** [oven-sh/bun#1766]
### What version of Bun is running?

0.4.1

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

1. create a script.ts

```ts
const dns = require("dns");
dns.resolveSrv("_mongodb._tcp.YOUR_MONGO_ATLAS_CLUSTER", (err, addresses) => {
  console.log(err);
  console.log(addresses);
});
```

2. `bun run script.ts`

### What is the expected behavior?

Error: `null`
Addresses: 
```ts
[
  {
    name: 'SHARD_0_YOUR_MONGO_ATLAS_CLUSTER',
    port: 27017,
    priority: 0,
    weight: 0
  },
  {
    name: 'SHARD_1_YOUR_MONGO_ATLAS_CLUSTER',
    port: 27017,
    priority: 0,
    weight: 0
  },
  {
    name: 'SHARD_2_YOUR_MONGO_ATLAS_CLUSTER',
    port: 27017,
    priority: 0,
    weight: 0
  }
]
```

### What do you see instead?

Error: `null`
Addresses:  `[]`

### Additional information

Cant seem to find another url to replicate the resolve on

**Comment by Jarred-Sumner** [comment]
resolveSrv is not implemented yet.

You can track the status here: https://github.com/oven-sh/bun/issues/1744

**Comment by sp90** [comment]
Just found out i will close this in right away
