### ISSUE TITLE
Segfault creating strings with NAPI

### ISSUE THREAD

**Issue by kriszyp** [oven-sh/bun#177]
I haven't actually isolated this that well, and it seems somewhat intermittent, so I am not certain of the cause, but it seems like it occurs when there is a large numbers strings created with `napi_create_string_latin1` or `napi_create_string_utf8`. How to reproduce:
```
git clone https://github.com/kriszyp/msgpackr.git
cd msgpackr
npm install
bun tests/benchmark.cjs
```
And this usually will segfault for me after this first benchmark finishes. Again, I am not certain of where it is occurring, possibly in my code, but this runs fine on Node.

**Comment by Jarred-Sumner** [comment]
Thank you for the repro

**Comment by Jarred-Sumner** [comment]
It is a crash when GC'ing strings

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/709451/169157395-5cf72afd-3533-4f75-9ec2-f897e82c0a53.png">

Going to try changing this code slightly to ensure that the JSValue is referenced in the stack memory so the GC can see it

If that doesn't work, then I'll try making this an external string
<img width="981" alt="image" src="https://user-images.githubusercontent.com/709451/169158377-487ef336-d40e-4ddf-91c7-0b9ead9b41fe.png">

**Comment by Jarred-Sumner** [comment]
This is tricky. I see one way to fix it, but I think it causes the GC to never free the strings (using `jsOwnedString` instead of `jsString`)

In JSC's C API, they never actually let you create strings this way. Instead, they have an `OpaqueJSString` which you ref/unref manually and then, when ready, you turn that into a JSValue (usually when returning)

What would probably work but be kind of awful: protect the string until the next tick

I looked at the code that writes the strings to the array and it is unfortunate that you have to do an extra loop there. What I do in Bun is pass an array of `ZigString` (a made up abstraction which is a pointer and a length with a pointer-tagged value) and then set those all at once, which means it isn't observable by the GC until the very end (good thing). 

I'm not sure yet the best way to fix this

**Comment by kriszyp** [comment]
It is very interesting to hear how this works. I thought the GC protection in V8 was through the scope handles, is there not a real parallel in JSC? Anyway, if you have suggestions for a better way for me to create these in my code, certainly open to it.

**Comment by Jarred-Sumner** [comment]
JSC doesn't have an equivalent to handles - that's also why I haven't implemented that in NAPI yet

JSC scans the native stack for pointers to heap-allocated values. 

Judging from this, it sounds like JSValueProtect would be a good option 

https://lists.webkit.org/pipermail/webkit-dev/2013-December/025930.html

**Comment by Jarred-Sumner** [comment]
as a next step, maybe I need to add a wrapper function to do the equivalent of JSValueProtect / JSValueUnprotect automatically for any values added in the most recent function call

Can have a statically allocated array associated with the JSGlobalObject and append to it each call :(

Then add it to be visited whenever the GC does it's thing

Then, prior to returning to JS function, it would just set the array's length to 0

**Comment by kriszyp** [comment]
Would it make a difference if I declared my `target` (C) array on my stack in extractStrings?

**Comment by kriszyp** [comment]
The answer is yes! It actually does fix it! JSC really does scan the native stack!

FWIW, I actually had considered my static target array technique to be somewhat questionable in terms of proper scope handling of C generated JS values. But V8 never complained, so I kept it. So it is actually not clear to me that the current bun behavior is really violating any guarantees that NAPI makes.

**Comment by Jarred-Sumner** [comment]
> The answer is yes! It actually does fix it! JSC really does scan the native stack!

Wow that's great

Also worth noting that bun tries to use very large stacks when possible so it's probably pretty safe to do this

On Linux, it's 12 MB
```bash
-Wl,-z,stack-size=12800000
```

Bun's JS parser is very recursive in some places, so a large stack is somewhat necessary

**Comment by kriszyp** [comment]
Great, thank you for insight/direction how this works in JSC. I'd say bun's behavior is perfectly reasonable here, closing.
