### ISSUE TITLE
Stripe - undefined is not a constructor

### ISSUE THREAD

**Issue by zolomatok** [oven-sh/bun#1773]
### What version of Bun is running?

0.4.0

### What platform is your computer?

"Darwin 21.6.0 arm64 arm" and I also tried with "Darwin 21.6.0 x86_64 i386" (rosetta terminal)

### What steps can reproduce the bug?

Single line program:
`const stripe = require('stripe')('sk_test_...')`

then just:
`bun test.ts`

### What is the expected behavior?

A stripe instance to be initialised.

### What do you see instead?

```
1 | 'use strict';
2 | const http = require('http');
3 | const https = require('https');
4 | const _HttpClient = require('./HttpClient');
5 | const {HttpClient, HttpClientResponse} = _HttpClient;
6 | const defaultHttpAgent = new http.Agent({keepAlive: true});
                             ^
TypeError: undefined is not a constructor (evaluating 'new http.Agent({ keepAlive: true })')
      at /Users/zolo/project/egyeb/demo/node_modules/stripe/lib/net/NodeHttpClient.js:6:25
      at /Users/zolo/project/egyeb/demo/node_modules/stripe/lib/stripe.js:117:9
      at new Stripe (/Users/zolo/project/egyeb/demo/node_modules/stripe/lib/stripe.js:89:36)
      at Stripe (/Users/zolo/project/egyeb/demo/node_modules/stripe/lib/stripe.js:52:11)
      at /Users/zolo/project/egyeb/demo/bun.ts:2:6
```

**Comment by Jarred-Sumner** [comment]
http.Agent and node:http client isn't implemented yet, but really needs to be

**Comment by zolomatok** [comment]
Gotcha, thanks @Jarred-Sumner !

**Comment by andrei-piatrou** [comment]
@Jarred-Sumner is `node:http` somewhere in the existing roadmap? thanks

**Comment by ThatOneBro** [comment]
> @Jarred-Sumner is `node:http` somewhere in the existing roadmap? thanks

I'm working on it currently

**Comment by ThatOneBro** [comment]
@zolomatok You could try this again in canary if you'd like, and let us know how far you get now
```
bun upgrade --canary
```

**Comment by zolomatok** [comment]
Thank you @ThatOneBro, fantastic, works great!
Managed to import stripe and do a balance call no problem! 🌈
