### ISSUE TITLE
Improve test coverage for bunx

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1775]
The following don't work but definitely should:

- `bunx webpack-cli`
- `bunx @babel/cli`

**Comment by cometkim** [comment]
`bun x` works fine in all cases. this should verify the difference between alias `bunx` and `bun x`.

**Comment by cometkim** [comment]
alias version of bunx works correctly only for packages currently installed from node_modules .

**Comment by dylan-conway** [comment]
These packages should work with `bunx`/`npx` after installing their dependencies. `babel-cli` requires `@babel/core` and `@babel/cli`, `webpack` requires `webpack-cli`.
https://babeljs.io/docs/en/babel-cli#usage
https://webpack.js.org/api/cli/
