### ISSUE TITLE
[install] Support for `--frozen-lockfile`

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#1776]
### What is the problem this feature would solve?

Fail on CI on inconsistent package.json/lockfile

### What is the feature you are proposing to solve the problem?

Add `--frozen-lockfile` to CLI like other package manager.

Nice to have: pnpm set it to true by default on CI: https://pnpm.io/cli/install#--frozen-lockfile

### What alternatives have you considered?

Run a git command to fail if there are git diff on the lockfile

**Comment by Jarred-Sumner** [comment]
Try `--production`

**Comment by Jarred-Sumner** [comment]
Though maybe adding the flag `--frozen-lockfile` would be good for compatibility

**Comment by ArnaudBarre** [comment]
If `CI=true bun install` fails like `bun install --production` I think this is also ok (not the case on v0.4.0)
