### ISSUE TITLE
`exitCode` can be a non-integer

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1780]
```js
14 |       const exitCode = await Bun.spawn({ cmd: ["blah"] });
15 |       expect(exitCode).toBe(0);
          ^
error: 
	Expected: 0
	Received: SIGSEGV
```

**Comment by Kruithne** [comment]
This appears to be out-dated. `Bun.spawn` doesn't return a `Promise<number>` as this seems to expect, but returns a `Subprocess` object. To get the exit code you would need to attach an `onExit` callback, or wait for the `.exited` promise to resolve, then either check the second parameter from the callback or the `.exitCode` directly.
