### ISSUE TITLE
readline.prompt(true) doesnt work as intended

### ISSUE THREAD

**Issue by h110m** [oven-sh/bun#1787]
### What version of Bun is running?

0.4.1

### What platform is your computer?

Linux 5.4.72-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

The `readline.prompt(true)` function does not keep the cursor position and text

### What is the expected behavior?

For example this
```ts
// rl is the result of readline.createInterface
rl.prompt(true);
const log = (msg: string) => {
    readline.cursorTo(process.stdout, 0);
    process.stdout.clearLine(0);
    conosole.log(msg);
    rl.prompt(true);
}
log("Hello, world");
```

should produce this

```
Hello, world
> 
```

It should keep the cursor always at the bottom and make sure when something gets logged it rerenders the prompt with the current input that has already been typed in so far so that the text doesnt just disappear when you type something and log something bevore hitting enter

### What do you see instead?

It just prints out the currently set prompt but without the input
However when you hit enter (to trigger the on line event for rl) the input shows for a split second and then dissapears

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v0.7.1
