### ISSUE TITLE
`error: linking <bin>: FileNotFound`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#1791]
### What version of Bun is running?

canary (0.4.1)

### What platform is your computer?

ubuntu-latest

### What steps can reproduce the bug?

I can't repro on my Mac, I'm only seeing this in CI during CI runs

### What is the expected behavior?

Properly link executables

### What do you see instead?

Here is a failed CI run that runs `bun install --verbose`: https://github.com/oven-sh/bun/actions/runs/3914696324/jobs/6692049536

**Comment by Jarred-Sumner** [comment]
Fixed

**Comment by macocha** [comment]
There seems to be a regression with this.
As witnessed here: https://github.com/oven-sh/bun/actions/runs/4769105066/jobs/8479151688
