### ISSUE TITLE
`fs.WriteStream` is undefined

### ISSUE THREAD

**Issue by pateketrueke** [oven-sh/bun#1797]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

I found that `formidable` uses `fs.WriteStream` but bun does not expose that, e.g. in `bunx bun-repl`

```js
import * as fs from 'node:fs';
console.log(fs.WriteStream); // undefined
```

I was having the error `TypeError: undefined is not a constructor (evaluating 'new fs.WriteStream(this.filepath)')` so I decided to patch the module:

```js
formidable.PersistentFile.prototype.open = function open() {
  this._writeStream = fs.createWriteStream(this.filepath);
  this._writeStream.on('error', err => {
    this.emit('error', err);
  });
};
```

This works, but now under certain cases (e.g. sending json) it complains with another error, see: https://github.com/oven-sh/bun/issues/1757

### What is the expected behavior?

The `fs.WriteStream` should return something, to avoid monkey-patching.

### What do you see instead?

An error, as I described above.

### Additional information

Well, bun is awesome, thank you! I am really having fun with. :)

**Comment by Jarred-Sumner** [comment]
yeah this is a bug
