### ISSUE TITLE
Behaviour of Websocket topics and publishing

### ISSUE THREAD

**Issue by h110m** [oven-sh/bun#1803]
### What is the problem this feature would solve?

You can currently only publish to all sockets.
It would be nice to publish to all sockets except the current one. 

### What is the feature you are proposing to solve the problem?

I think it would make more sense to say `server.publish()` publishes to all sockets and `socket.publish()` publishes to all clients except the current one.

This would be more node/socket.io like.

### What alternatives have you considered?

Another possibility would be to have a option object on which we can set if we want to also sent it to the current socket.
If not i will need to implement a broadcast method myself which i think won't be as efficient as the original one.

**Comment by Jarred-Sumner** [comment]
In the canary build of Bun (`bun upgrade --canary`), pass `publishToSelf` in the `websocket` handler and then it will do as you want

It was an API design mistake that this is not the default.
