### ISSUE TITLE
bun create /some/path doesn't work

### ISSUE THREAD

**Issue by arnorhs** [oven-sh/bun#1812]
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

- follow instructions for https://bun-docs.pages.dev/en/bun_create/ by using the 'absolute path' variation
- create an empty project with a package.json and name
- `bun create /path/to/this/project newdir`

### What is the expected behavior?

Directory gets populated with the template

### What do you see instead?

error: "/path/to/this/project" was not found. Here are templates you can use:

**Comment by birkskyum** [comment]
Obsolete, since the `bun create` command in question has been removed.
