### ISSUE TITLE
Memory use for fetching/processing 7.4MB JSON file much larger than Node/V8

### ISSUE THREAD

**Issue by leeoniya** [oven-sh/bun#1824]
### What version of Bun is running?

0.4.1 (canary)

### What platform is your computer?

Linux 6.1.4-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

I'm processing some Prometheus metrics, the response size is 7.4MB of JSON.

(Bun is much faster overall, which is great!)

with Node v19.4 i'm seeing ~220MB peak mem, and after a few secs of idle it drops to ~120MB consistently.

with Bun v0.4.1 (canary) the same setup uses ~250MB peak, which seems okay?, but the memory is never reclaimed and stays at about ~230MB even after idle.

at first i thought it was a JIT cache that JSC was not releasing, since follow-up requests after idle seem to respond much faster than Node, but the retained mem size seems to be affected by the JSON size, so that theory seems invalidated.

here are what i believe are equivalent scripts, one for Node and one for Bun: [bun-vs-node-fetch-json.zip](https://github.com/oven-sh/bun/files/10441457/bun-vs-node-fetch-json.zip). simply run `bun bun.js` and `node node.js`. then go to `localhost:3001` and hit `Query` 5-10 times. observe the used memory behavior in `htop` or wherever.

Node idle:
![image](https://user-images.githubusercontent.com/43234/213068338-db6820d5-062d-455a-a05a-8331f0ff082c.png)

Bun idle:
![image](https://user-images.githubusercontent.com/43234/213068376-a3764758-0ece-4879-bd09-b6a9f2884cf8.png)

### What is the expected behavior?

same(ish) memory usage.

### What do you see instead?

bun idles with more mem.

**Comment by Jarred-Sumner** [comment]
I think this is a GC scheduling bug

If you do `Response.json` instead of `new Response(JSON.stringify`, does it get better?

**Comment by leeoniya** [comment]
yes somewhat.

sits at 205MB now, and peak looks lower maybe by about the same amount. non-scientific measurements, of course :sweat_smile:

**Comment by Jarred-Sumner** [comment]
If you run `Bun.gc()` in one of the promise handlers, is it any better? You shouldn't have to do this, but it would imply we need to schedule the GC when memory usage grows significantly between microtask ticks

Another thing you could try is `await`, though honestly I'd somewhat expect it to be better without await. If the rationale for not using await is to avoid the `async` function causing it to return a Promise, Bun.serve() avoids the extra microtick for fulfilled Promise objects automatically (native code reads the status of the promise, if not pending, it takes the result out same as if you didn't return a Promise)

**Comment by leeoniya** [comment]
this takes it down to ~190MB:

```
Bun.gc();

return Response.json(series);
```

**Comment by Jarred-Sumner** [comment]
what about

```js
Bun.gc(true)
return Response.json(series);
```

note that Bun.gc(true) makes it much slower

**Comment by leeoniya** [comment]
~155MB

off to bed for now, hopefully that's enough info :)

> note that Bun.gc(true) makes it much slower

doesnt feel slower when it's 0.5 rps :D

**Comment by Jarred-Sumner** [comment]
@leeoniya can you try setting this environment variable? `BUN_JSC_forceRAMSize="1073741"` (its in kilobytes)

I think the reason why JSC is using a lot more ram than V8 is because V8/Node sets a default max heap size and Bun isn't right now. When I read the code before, it appeared to be automatically set based on the maximum memory reported by the operating system -- however, relying on that number is too high. On the server, you don't really want the JS application to ever use more than 1/2 or 1/4 of available ram but by default, it allows up to the entire system memory.

**Comment by leeoniya** [comment]
i'll try it in the next few days. currently writing the millionth JavaScript CSV parser :sweat_smile: (Bun seems to be underperforming by quite a bit, so heads up for another incoming issue soon)

![image](https://github.com/oven-sh/bun/assets/43234/7c816301-2ba6-4e2b-8d37-a334f71ea9b6)

**Comment by Jarred-Sumner** [comment]
would need to look at the code to guess at the cause 

Maybe a rope string thing (processing time might be quicker, but if you try to access contents of the strings, it would be slower)

**Comment by ImLunaHey** [comment]
I added in `Bun.gc(true);` before my response. I'm going to let this sit in case there's something else going on but this seems to have fixed the problem.


**Before** 
<img width="421" alt="Screen Shot 2023-09-25 at 12 12 45 am" src="https://github.com/oven-sh/bun/assets/105922175/3c25a729-a3a4-4f3d-a6b8-1740cbb92e1c">

**After**
<img width="409" alt="Screen Shot 2023-09-25 at 7 53 36 am" src="https://github.com/oven-sh/bun/assets/105922175/2d6b7836-4f1b-40aa-8e4e-4147b435b1af">

**Comment by ImLunaHey** [comment]
Added `--smol` instead of calling `Bun.gc(true);` after each response and im seeing similar performance but 1/2 the memory.

**Comment by ImLunaHey** [comment]
Here's the memory usage over the day, looks like `--smol` fixes it for now.

The last dotted line is when I switched to `--smol`.

![image](https://github.com/oven-sh/bun/assets/105922175/e33c12f3-ade3-42d3-b412-511db95cdcfb)

**Comment by ImLunaHey** [comment]
So maybe `--smol` isnt the "fix" or its a bug on my end. 😞 

![image](https://github.com/oven-sh/bun/assets/105922175/d0f6e62d-6b5c-4d23-b602-ae7737ef89a3)

**Comment by leeoniya** [comment]
@Jarred-Sumner, i tested this again with latest canary just parsing a local 14.3MB json file and then stringifying it back out. Bun uses significantly more memory while being only somewhat faster vs Node (except the 4x faster file read :heart:). since json handling is such a core part of web apps, it would be very appreciated if some effort was put into getting these numbers as low as feasible.

```js
import fs from 'fs';

console.time('read');
let text = fs.readFileSync('./ttec.json', 'utf8');
console.timeEnd('read');

console.time('parse');
let struct = JSON.parse(text);
console.timeEnd('parse');

console.time('unparse');
let text2 = JSON.stringify(struct);
console.timeEnd('unparse');

const used = process.memoryUsage();
for (let key in used) {
  console.log(`Memory: ${key} ${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB`);
}
```

![image](https://github.com/oven-sh/bun/assets/43234/179a028a-5b16-4567-9b15-5b9855e876c5)

when pretty-printed, the json file sample looks like this:

```json
{
  "results": [
    {
      "statement_id": 0,
      "series": [
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-248",
            "oracle_id": "3167640"
          },
          "columns": [
            "time",
            "pc_name",
            "timestamp_seconds",
            "client_name",
            "cpu_used",
            "d_bytes",
            "u_bytes",
            "disk_used",
            "jitter",
            "memory_used",
            "latency",
            "r_score",
            "packet_loss",
            "idletime_raw",
            "solution",
            "isp",
            "vpn_type"
          ],
          "values": [
            [
              1678723623474,
              "LAPTOP-123456789",
              1678734134503,
              "",
              16.726718841369227,
              null,
              null,
              53,
              null,
              48.72,
              null,
              null,
              null,
              null,
              "SRW BYOD",
              null,
              null
            ]
          ]
        },
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-258",
            "oracle_id": "0"
          },
          "columns": [
            "time",
            "pc_name",
            "timestamp_seconds",
            "client_name",
            "cpu_used",
            "d_bytes",
            "u_bytes",
            "disk_used",
            "jitter",
            "memory_used",
            "latency",
            "r_score",
            "packet_loss",
            "idletime_raw",
            "solution",
            "isp",
            "vpn_type"
          ],
          "values": [
            [
              1678723623474,
              "SRWD21LCRN3",
              1678734188679,
              "",
              23.432988173518233,
              null,
              null,
              64,
              null,
              70.92,
              null,
              null,
              null,
              null,
              null,
              null,
              null
            ]
          ]
        },
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-28",
            "oracle_id": "0"
          },
          "columns": [
            "time",
            "pc_name",
            "timestamp_seconds",
            "client_name",
            "cpu_used",
            "d_bytes",
            "u_bytes",
            "disk_used",
            "jitter",
            "memory_used",
            "latency",
            "r_score",
            "packet_loss",
            "idletime_raw",
            "solution",
            "isp",
            "vpn_type"
          ],
          "values": [
            [
              1678723623474,
              null,
              null,
              "Unknown",
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null
            ]
          ]
        },
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-28",
            "oracle_id": "2249908"
          },
          "columns": [
            "time",
            "pc_name",
            "timestamp_seconds",
            "client_name",
            "cpu_used",
            "d_bytes",
            "u_bytes",
            "disk_used",
            "jitter",
            "memory_used",
            "latency",
            "r_score",
            "packet_loss",
            "idletime_raw",
            "solution",
            "isp",
            "vpn_type"
          ],
          "values": [
            [
              1678723623474,
              "PHQC4FEA344B",
              1678734167565,
              "",
              10.772527844239201,
              null,
              null,
              25,
              null,
              58.33,
              null,
              null,
              null,
              null,
              null,
              null,
              null
            ]
          ]
        },
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-327",
            "oracle_id": "3415374"
          },
          "columns": [
            "time",
            "pc_name",
            "timestamp_seconds",
            "client_name",
            "cpu_used",
            "d_bytes",
            "u_bytes",
            "disk_used",
            "jitter",
            "memory_used",
            "latency",
            "r_score",
            "packet_loss",
            "idletime_raw",
            "solution",
            "isp",
            "vpn_type"
          ],
          "values": [
            [
              1678723623474,
              "USDAYBSCB270XM3",
              1678734222642,
              "Lorem Ipsum is simply dummy text of the printing and typesetting",
              40.61198862661182,
              null,
              null,
              33,
              null,
              51.41,
              null,
              null,
              null,
              null,
              "SCCM",
              null,
              null
            ]
          ]
        },
        {
          "name": "associates_view",
          "tags": {
            "mac_address": "-331",
```

**Comment by Jarred-Sumner** [comment]
> @Jarred-Sumner, i tested this again with latest canary just parsing a local 14.3MB json file and then stringifying it back out. Bun uses significantly more memory while being only somewhat faster vs Node (except the 4x faster file read ❤️). since json handling is such a core part of web apps, it would be very appreciated if some effort was put into getting these numbers as low as feasible.
> 
> ```js
> import fs from 'fs';
> 
> console.time('read');
> let text = fs.readFileSync('./ttec.json', 'utf8');
> console.timeEnd('read');
> 
> console.time('parse');
> let struct = JSON.parse(text);
> console.timeEnd('parse');
> 
> console.time('unparse');
> let text2 = JSON.stringify(struct);
> console.timeEnd('unparse');
> 
> const used = process.memoryUsage();
> for (let key in used) {
>   console.log(`Memory: ${key} ${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB`);
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43234/289399643-179a028a-5b16-4567-9b15-5b9855e876c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTgyOTYsIm5iZiI6MTcwMjI1Nzk5NiwicGF0aCI6Ii80MzIzNC8yODkzOTk2NDMtMTc5YTAyOGEtNWIxNi00NTY3LTliMTUtNWI5ODU1ZTg3NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAxMjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMjRlZjYyNDZiYTM1N2NlY2NiMGZhM2E3Y2RlOTkxNmQ1M2NkNTc0MmEwMmFhYmRjZTlmNTgxOGNkNDkxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXQRJBDq0qPfCuP8ATTBdo359eaVE23ZK1QOPb9_UjU)
> 
> when pretty-printed, the json file sample looks like this:
> 
> ```json
> {
>   "results": [
>     {
>       "statement_id": 0,
>       "series": [
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-248",
>             "oracle_id": "3167640"
>           },
>           "columns": [
>             "time",
>             "pc_name",
>             "timestamp_seconds",
>             "client_name",
>             "cpu_used",
>             "d_bytes",
>             "u_bytes",
>             "disk_used",
>             "jitter",
>             "memory_used",
>             "latency",
>             "r_score",
>             "packet_loss",
>             "idletime_raw",
>             "solution",
>             "isp",
>             "vpn_type"
>           ],
>           "values": [
>             [
>               1678723623474,
>               "LAPTOP-123456789",
>               1678734134503,
>               "",
>               16.726718841369227,
>               null,
>               null,
>               53,
>               null,
>               48.72,
>               null,
>               null,
>               null,
>               null,
>               "SRW BYOD",
>               null,
>               null
>             ]
>           ]
>         },
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-258",
>             "oracle_id": "0"
>           },
>           "columns": [
>             "time",
>             "pc_name",
>             "timestamp_seconds",
>             "client_name",
>             "cpu_used",
>             "d_bytes",
>             "u_bytes",
>             "disk_used",
>             "jitter",
>             "memory_used",
>             "latency",
>             "r_score",
>             "packet_loss",
>             "idletime_raw",
>             "solution",
>             "isp",
>             "vpn_type"
>           ],
>           "values": [
>             [
>               1678723623474,
>               "SRWD21LCRN3",
>               1678734188679,
>               "",
>               23.432988173518233,
>               null,
>               null,
>               64,
>               null,
>               70.92,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null
>             ]
>           ]
>         },
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-28",
>             "oracle_id": "0"
>           },
>           "columns": [
>             "time",
>             "pc_name",
>             "timestamp_seconds",
>             "client_name",
>             "cpu_used",
>             "d_bytes",
>             "u_bytes",
>             "disk_used",
>             "jitter",
>             "memory_used",
>             "latency",
>             "r_score",
>             "packet_loss",
>             "idletime_raw",
>             "solution",
>             "isp",
>             "vpn_type"
>           ],
>           "values": [
>             [
>               1678723623474,
>               null,
>               null,
>               "Unknown",
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null
>             ]
>           ]
>         },
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-28",
>             "oracle_id": "2249908"
>           },
>           "columns": [
>             "time",
>             "pc_name",
>             "timestamp_seconds",
>             "client_name",
>             "cpu_used",
>             "d_bytes",
>             "u_bytes",
>             "disk_used",
>             "jitter",
>             "memory_used",
>             "latency",
>             "r_score",
>             "packet_loss",
>             "idletime_raw",
>             "solution",
>             "isp",
>             "vpn_type"
>           ],
>           "values": [
>             [
>               1678723623474,
>               "PHQC4FEA344B",
>               1678734167565,
>               "",
>               10.772527844239201,
>               null,
>               null,
>               25,
>               null,
>               58.33,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null,
>               null
>             ]
>           ]
>         },
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-327",
>             "oracle_id": "3415374"
>           },
>           "columns": [
>             "time",
>             "pc_name",
>             "timestamp_seconds",
>             "client_name",
>             "cpu_used",
>             "d_bytes",
>             "u_bytes",
>             "disk_used",
>             "jitter",
>             "memory_used",
>             "latency",
>             "r_score",
>             "packet_loss",
>             "idletime_raw",
>             "solution",
>             "isp",
>             "vpn_type"
>           ],
>           "values": [
>             [
>               1678723623474,
>               "USDAYBSCB270XM3",
>               1678734222642,
>               "Lorem Ipsum is simply dummy text of the printing and typesetting",
>               40.61198862661182,
>               null,
>               null,
>               33,
>               null,
>               51.41,
>               null,
>               null,
>               null,
>               null,
>               "SCCM",
>               null,
>               null
>             ]
>           ]
>         },
>         {
>           "name": "associates_view",
>           "tags": {
>             "mac_address": "-331",
> ```

If you do` --smol` does it use less? Another thought: if you do await Bun.file(path).json(), does that reduce usage (this avoids the trip through JS)

**Comment by leeoniya** [comment]
`--smol` has no effect on rss, though heapTotal and heapUsed drop:

```
[leeoniya@endeavour-p14s frame-conv]$ bun --smol run toframes.mjs 
[8.65ms] read
[58.26ms] parse
[54.04ms] unparse
Memory: rss 269.9 MB
Memory: heapTotal 39.08 MB
Memory: heapUsed 32.12 MB
Memory: external 0 MB
Memory: arrayBuffers 0 MB
```

i removed `stringify` for now from both versions, and the `await` variant helps somewhat:

```
[leeoniya@endeavour-p14s frame-conv]$ bun run ./toframes.mjs 
[8.34ms] read
[61.81ms] parse
Memory: rss 170.38 MB
Memory: heapTotal 41.42 MB
Memory: heapUsed 50.89 MB
Memory: external 0 MB
Memory: arrayBuffers 0 MB
[leeoniya@endeavour-p14s frame-conv]$ bun run ./toframes-await.mjs 
[67.09ms] read+parse
Memory: rss 129.5 MB
Memory: heapTotal 39.66 MB
Memory: heapUsed 32.84 MB
Memory: external 0 MB
Memory: arrayBuffers 0 MB
```

this is pretty close to Node without `stringify`:

```
[leeoniya@endeavour-p14s frame-conv]$ node ./toframes.mjs 
read: 38.77ms
parse: 90.183ms
Memory: rss 115.21 MB
Memory: heapTotal 79.67 MB
Memory: heapUsed 60.33 MB
Memory: external 1.56 MB
Memory: arrayBuffers 0.01 MB
```

realistically, i guess you would typically stream the output of `stringify` to io (if possible), since there's little reason to hold that in memory.

**Comment by Jarred-Sumner** [comment]
@leeoniya I think this issue has been fixed in more recent versions of Bun
```ts
❯ mem bun node.js
[263.74ms] query
[754.66ms] parse
[21.94ms] munge
[155.02ms] query
[560.51ms] parse
[19.43ms] munge
[142.82ms] query
[629.04ms] parse
[17.68ms] munge
[129.08ms] query
[590.35ms] parse
[17.20ms] munge
[157.21ms] query
[563.65ms] parse
[20.49ms] munge
[144.82ms] query
[498.89ms] parse
[20.35ms] munge
[178.24ms] query
[657.63ms] parse
[22.03ms] munge
^C
Peak memory usage: 132 MB
```

```ts
❯ mem node node.js
query: 254.11ms
parse: 850.961ms
munge: 25.036ms
query: 160.903ms
parse: 577.796ms
munge: 23.404ms
query: 135.023ms
parse: 644.937ms
munge: 25.511ms
query: 143.308ms
parse: 584.932ms
munge: 24.046ms
query: 141.344ms
parse: 889.091ms
munge: 24.945ms
query: 158.907ms
parse: 904.948ms
munge: 25.281ms
query: 203.953ms
parse: 669.003ms
munge: 24.942ms
^C
Peak memory usage: 233 MB
```

Note that I updated the url in both to be `"http://demo.promlabs.com:9090/api/v1/query_range?query=container_memory_usage_bytes&start=2024-08-07T00:00:00Z&end=2024-08-08T00:00:00Z&step=20s";`
