### ISSUE TITLE
Add `proxy` option to `fetch()`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1829]
**Guide: https://bun.sh/guides/http/proxy**

This would be an optional parameter to `fetch()` that would allow you to define a proxy URL to route the request. This is similar to the [`http_proxy` and `https_proxy`](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/) environment variables, except the `proxy` must be a fully-qualified URL instead of a host and port.

```js
await fetch("http://example.com", {
  proxy: "http://localhost:8080/proxy"
});
```

Originally proposed by [@alistaiir](https://twitter.com/alistaiir/status/1615775318601515014)

**Comment by cirospaciari** [comment]
already available in the latest release.

**Comment by ghost** [comment]
do you have any example for proxy using user and password, i am learning about request proxy and don't understand fetch proxy requirements. I didn't find it in the docs

**Comment by ashwwwin** [comment]
Here's how it would work however, there's a bug with it atm + seems like the team is working on a fix!

```
async function testProxy(proxy: string) {
  let data = await fetch("https://api.ipify.org/?format=json", {
    headers: {
      accept: "*/*",
    },
    proxy: proxy,
  });

  data = await data.json();

  console.log(data);
}

testProxy("http://username:password@host:port")
```

**Comment by andrewphandev** [comment]
There is a typescript error when passing proxy to fetch

**Comment by ragavpr** [comment]
> There is a typescript error when passing proxy to fetch

Typescript error tracked in Issue #13827
