### ISSUE TITLE
Implement `AsyncLocalStorage`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1832]
[`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstorage) is a Node.js API that allows you to store and access values from an asynchronous context. It's commonly used in observability libraries like Sentry that need to track request and correlation IDs.

**Comment by ThatOneBro** [comment]
Implementing `AsyncResource` and `executionAsyncId` would cover other `async_hooks` use cases used in packages like `fastify`, `prisma`, `sequelize`, and some other database ORMs and libraries. It may be worth including those too

**Comment by pyronaur** [comment]
[`zx` ](https://github.com/google/zx )relies on this, so it would be pretty exciting to see added to bun 🙂

**Comment by ianwatts22** [comment]
I'm getting `error: Cannot find package "async_hooks" from "/Users/ianwatts/robome-bun/node_modules/@prisma/client/runtime/library.js"`. Anyway around this or just wait until Bun supports async_hooks? Chomping at the bit to build on Bun but need Prisma.

**Comment by ThatOneBro** [comment]
@ianwatts22 Sadly I think we'll just have to wait until we have `async_hooks`, specifically `AsyncLocalStorage` and *I think* `AsyncResource`. 

This is a pretty time consuming feature to implement but super important for a lot of things, so we are trying to coordinate on getting this done soon.

We may have someone who will be working on the implementation, but we still don't know for sure and maybe someone else ends up doing it instead. Will post in this issue once we have more updates 👍

**Comment by ianwatts22** [comment]
Thank you for the quick response and for all of y'alls hard work! I can only imagine the things y'all are doing.

Are there other PostgreSQL ORMs you know of that work with Bun? Otherwise, would I be able to just use straight-up PostgreSQL queries just fine?

**Comment by ThatOneBro** [comment]
I have been meaning to test TypeORM with Bun but have yet to do it, you may be able to get that working (let me know if you do!) 

Otherwise postgres.js (`postgres` on npm) should be working and you could make raw SQL queries with that until other ORMs / libraries are working (probably after `async_hooks` is at least partially implemented)

**Comment by paperclover** [comment]
i was looking at `@prisma/client`, and i noticed if you take away `extends AsyncResource` from it's classes, and then replace it's `return asyncRes.runInAsyncScope(() => consumer(params))` with just `return consumer(params)`... it seems to work. (though the `String.raw` bug is also stopping it to run as is, need to replace that manually too).

I'm not fully aware of what `async_hooks` exactly does but it seems that `prisma` for one doesn't fully rely on it, and in the short term a partial implementation might be able to get a lot the library to work.

**Comment by gtrabanco** [comment]
Just to give info, this should be implemented to all who wants to use [zx](https://github.com/google/zx) project with Bun.
