### ISSUE TITLE
Helptext ordering

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#1834]
### What is the problem this feature would solve?

When running `--help` on a subcommand (`bun run --help`) don't print all top level commands. Alternatively don't print them at the bottom, so the command-specific helptext isn't hidden on small Terminals.

<img width="803" alt="Screenshot 2023-01-18 at 3 47 43 PM" src="https://user-images.githubusercontent.com/3084745/213319935-9b06fed5-1d7f-4dfb-8ce2-5ab5351d4cc7.png">

**Comment by Electroid** [comment]
We've changed the help page since this issue was created.
