### ISSUE TITLE
Bun report v8 in process.versions

### ISSUE THREAD

**Issue by rizrmd** [oven-sh/bun#1842]
### What version of Bun is running?

0.5.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Posted reproduction on lmdb-js issue here: 

https://github.com/kriszyp/lmdb-js/issues/208

process.versions should not have v8 entry. But it shows v8:

```
{
  node: "18.13.0",
....
  v8: "10.8.168.20-node.8",
  modules: "108"
}
```

### What is the expected behavior?

v8 not presents

### What do you see instead?

```
{
  node: "18.13.0",
....
  v8: "10.8.168.20-node.8",
  modules: "108"
}
```

**Comment by Electroid** [comment]
Unfortunately, we need to report the `v8` property because some libraries will check it. We periodically update it.
