### ISSUE TITLE
Support for the http module

### ISSUE THREAD

**Issue by alexreyes** [oven-sh/bun#1849]
### What version of Bun is running?

0.5.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

1) Run the following (or any script that uses the http module from nodeJS): 
```
const http = require('http');

const options = {
  host: 'www.google.com',
  path: '/',
  method: 'GET'
};

const req = http.request(options, (res) => {
  console.log(`statusCode: ${res.statusCode}`);

  res.on('data', (d) => {
    process.stdout.write(d);
  });
});

req.on('error', (error) => {
  console.error(error);
});

req.end();
```

2) Get this error: ```TypeError: undefined is not a function (near '...http.request...')```

### What is the expected behavior?

This returns the expected response (the result of a request to google) when I run it with node.

### What do you see instead?

TypeError: undefined is not a function (near '...http.request...')

### Additional information

I'm guessing this is happening because bun doesn't have support for the HTTP module yet. I'm just making an issue to track that.

**Comment by ThatOneBro** [comment]
This is currently in progress, will link this issue when PR is up.
