### ISSUE TITLE
this in constructor

### ISSUE THREAD

**Issue by AlexBlokh** [oven-sh/bun#1855]
### What version of Bun is running?

0.5.0

### What platform is your computer?

Darwin 21.5.0 arm64 arm

### What steps can reproduce the bug?

```typescript
class Test {
  constructor(private readonly a: string){
    console.log(a)
    console.log(this.a)
  }
}
new Test("all good")
```

### What is the expected behavior?

all good
all good

### What do you see instead?

all good
undefined

<img width="511" alt="image" src="https://user-images.githubusercontent.com/4045375/213641336-116d979d-c443-4c80-8805-91ce5e508144.png">

**Comment by Jarred-Sumner** [comment]
Bun's output:
```ts
class Test {
  a;
  constructor(a) {
    console.log(a);
    console.log(this.a);
    this.a = a;
  }
}
```
