### ISSUE TITLE
Failed to move extracted bun to destination

### ISSUE THREAD

**Issue by zolomatok** [oven-sh/bun#1859]
### What platform is your computer?

Darwin 21.6.0 arm64 arm

### How did you attempt to install or upgrade?

By running
`curl -fsSL https://bun.sh/install | bash`

I had 4.0 before, I tried `bun upgrade` then (to update to `0.5.1`), that didn't work either.
It was something about not finding `Child`... something. I deleted Bun and tried to install from fresh, this is what I got.
I've been using 4.0 without any problems before.

### What do you see instead?

```
mv: /Users/zolo/.bun/bin/bun-darwin-aarch64/bun: No such file or directory
error: Failed to move extracted bun to destination
```

**Comment by Coadon** [comment]
Same problem.

**Comment by mosessmax** [comment]
yeah i got the same thing.

**Comment by Jarred-Sumner** [comment]
Fixed, please try again either via bun upgrade or the curl script
