### ISSUE TITLE
module-resolver support

### ISSUE THREAD

**Issue by andidev** [oven-sh/bun#186]
Is it possible to configure module resolver to add support for absolute paths imports and path aliases?

we have absolute paths congigured with `babel-plugin-module-resolver` like this
```
   ["module-resolver", {
        "extensions": [".js", ".json"],
        "root": ["."]
      }
    ]
```

but with bun we get following error I guess since we use absolute path imports:
```
warn: Could not resolve: "src/AppRoot". Maybe you need to "bun install"?
import { AppRoot } from 'src/AppRoot';
                        ^
```

**Comment by Jarred-Sumner** [comment]
Bun supports [`"paths"` in tsconfig.json](https://www.typescriptlang.org/tsconfig#paths), have you tried that?

The nice thing about `"paths"`: VSCode & other editors support autocompleting imports with them.

If you're not using TypeScript, try naming the file `jsconfig.json` instead of `tsconfig.json`.

**Comment by wmertens** [comment]
Or keep the name tsconfig.json and add "allowJs: true" and "checkJs: true".

Then sprinkle in some jsdoc and watch intellisense work its magic. You can also add some .d.ts ambient files to define types used throughout your project, very handy and no typescript support needed. (Be sure to keep them ambient, no top-level imports allowed)

**Comment by andidev** [comment]
Hmm actually we use flow. Looks like `jsconfig.json` solved it thanks. But now I have issue with flow syntax.
Hmm maybe I should create a new issue for it? Is flow supported? dont find any issues about it.

**Comment by andidev** [comment]
closing this since original question was resolved
