### ISSUE TITLE
Upgrade from 0.4.0 to 0.5.1 fail on Mac OS Intel

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#1860]
### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### How did you attempt to install or upgrade?

`bun upgrade`

### What do you see instead?

`error Failed to verify bun ChildExecFailed)`

**Comment by brian316** [comment]
I tried upgrading from v5.0 to v5.1 and I also tried doing the curl command install then got this error:

```bash
curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
mv: /Users/brian/.bun/bin/bun-darwin-x64/bun: No such file or directory
error: Failed to move extracted bun to destination
```

my system
```
neofetch
                    'c.          xxxxxxx@xxxxx.lan
                 ,xNMM.          --------------------
               .OMMMMo           OS: macOS 13.1 22C65 x86_64
               OMMM0,            Host: MacBookPro16,2
     .;loddo:' loolloddol;.      Kernel: 22.2.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 2 days, 18 hours, 9 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 118 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WarpTerminal
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-1068NG7 (8) @ 2.30GHz
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel Iris Plus Graphics
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 18177MiB / 32768MiB
       .cooc,.    .,coo:.

```

**Comment by baristikir** [comment]
Can confirm that this is also an issue for Apple Silicon macs (M1 in my case).
I tried to upgrade from `0.4.0` to latest via `bun upgrade` and got the same error message.

```bash
☁  ~  bun upgrade 
bun v0.5.1 is out! You're on 0.4.0
error Failed to verify bun ChildExecFailed)
```

**Comment by zolomatok** [comment]
Same here
https://github.com/oven-sh/bun/issues/1859

**Comment by yaameen** [comment]
> ### What platform is your computer?
> Darwin 21.6.0 x86_64 i386
> 
> ### How did you attempt to install or upgrade?
> `bun upgrade`
> 
> ### What do you see instead?
> `error Failed to verify bun ChildExecFailed)`
> 
> ### Additional information
> _No response_

Same issue

**Comment by chrisAXZA** [comment]
On Mac OS Mojave 10.14 latest updates from 0.4 -> 0.5 + 0.5 -> 0.5.1 are successful via `curl` (`bun upgrade` still not working), even though will return error message from 0.5 -> 0.5.1, which was not present with transition from 0.4 -> 0.5:

`curl -fsSL https://bun.sh/install | bash`
Error => `error: Failed to move extracted bun to destination`

`bun --version`
`0.5.1`

**Comment by zolomatok** [comment]
Huh, you're right, it really _is_ installed, we just get an error. Strange 🤔.

**Comment by Jarred-Sumner** [comment]
Fixed, please try again either via bun upgrade or the curl script

**Comment by zolomatok** [comment]
Works like a dream, thanks @Jarred-Sumner !

![wwe-okay](https://user-images.githubusercontent.com/11703903/213811894-9cda3520-20b8-4f51-946a-146f91663a8e.gif)
