### ISSUE TITLE
List globally installed packages with bun

### ISSUE THREAD

**Issue by alexreyes** [oven-sh/bun#1863]
### What is the problem this feature would solve?

It's helpful to see which packages I've installed globally. 

NPM has: `npm list -g`

Yarn has: `yarn global list`

Bun has: ???

### What is the feature you are proposing to solve the problem?

Add a command named: `bun list -g` to list the global packages

### What alternatives have you considered?

Finding bun path with: `which bun`

Manually checking: `/Users/[user goes here]/.bun/install/global/node_modules`

If this wouldn't be too hard, I'd be happy to make a PR for this. Some pointers would be helpful on where to start in the bun repo

**Comment by Jarred-Sumner** [comment]
The DX/error messages need work, but you can do `bun pm ls -g`

**Comment by alexreyes** [comment]
@Jarred-Sumner would you take a PR that makes a shortcut for that and turns it into `bun list -g` & adds the command to the help menu?

**Comment by silkfire** [comment]
This isn't working for me, I'm getting an error:

```
error: No package.json was found for directory "C:\Users\Gabriel\.bun\install\global"
note: Run "bun init" to initialize a project
```

Strangely, this command doesn't work if the cwd is a project containing a `package.json` file either.
