### ISSUE TITLE
`Request.signal` is `undefined` when passed an `AbortController.signal`

### ISSUE THREAD

**Issue by ThatOneBro** [oven-sh/bun#1864]
### What version of Bun is running?

0.5.1 (canary)

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
const controller = new AbortController();
const signal = controller.signal;

console.log({
  signal,
  requestSignal: new Request("http://localhost:3000/blog/salt", {
    signal,
  }).signal,
});
```

### What is the expected behavior?

`requestSignal` should be an `AbortSignal` like the signal created manually

### What do you see instead?

`requestSignal` is `undefined` on `Request`

### Additional information

Reported by @SaltyAom (originally reported by @jacob-ebey in #1653)

**Comment by cirospaciari** [comment]
This was fixed by 24d624b176df241936d4ec82b2d6f93861de6229
