### ISSUE TITLE
`fs/promises` support

### ISSUE THREAD

**Issue by coderaiser** [oven-sh/bun#187]
Trying to run 🐊[Putout](https://github.com/coderaiser/putout) code transformer with help of `Bun`, but see an error:

```sh
coderaiser@cloudcmd:~/putout/packages/putout$ bun bin/putout.mjs


error: Could not resolve: "fs/promises". Maybe you need to "bun install"?

} from 'fs/promises';
       ^
/Users/coderaiser/putout/packages/putout/bin/putout.mjs:6:8 66
```

Here is how `bin/putout.mjs` looks like:

```js
#!/usr/bin/env node

import {
    readFile,
    writeFile,
} from 'fs/promises';

import cli from '../lib/cli/index.js';

const {stdout} = process;
const write = stdout.write.bind(stdout);
const logError = console.error;

await cli({
    write,
    halt: process.exit,
    argv: process.argv.slice(2),
    log: console.log,
    logError,
    readFile,
    writeFile,
});
```

Also `bun bun bin/putout.mjs` shows:

```sh
error: Unexpected #!/usr/bin/env node
#!/usr/bin/env node
^
/Users/coderaiser/putout/packages/putout/bin/putout.mjs:1:1 0
```

**Comment by Jarred-Sumner** [comment]
> error: Could not resolve: "fs/promises". Maybe you need to "bun install"?

Yeah, `fs/promises` is not implemented yet. There are subtle differences in the API compared to `fs` (i.e. it's not just wrapping with promises). As a temporary wrokaround, you could use `fs` – much of that is implemented.

> Also bun bun bin/putout.mjs shows:

This is a terrible error message, but currently top-level `await` isn't supported with `bun bun`.  Can you try replacing `await` with a promise?

**Comment by coderaiser** [comment]
Thanks for a quick answer!

> i.e. it's not just wrapping with promises

Why not wrapping with promises? I think `promisify` can be good solution :).
I saw a lot `callbackify` over sync versions of `fs` methods, is it related?

I made changes:

```diff
+import {promisify} from 'util';
+
 import {
     readFile,
     writeFile,
-} from 'fs/promises';
+} from 'fs';

 import cli from '../lib/cli/index.js';

@@ -17,7 +19,7 @@ await cli({
     argv: process.argv.slice(2),
     log: console.log,
     logError,
-    readFile,
-    writeFile,
+    readFile: promisify(readFile),
+    writeFile: promisify(writeFile),
 });
```

And now I have a new error:

```
error: Could not resolve: "readline". Maybe you need to "bun install"?
Ȅ�
                         ^
/Users/coderaiser/putout/packages/cli-keypress/lib/keypress.js:4:26
```

**Comment by Jarred-Sumner** [comment]
> error: Could not resolve: "readline". Maybe you need to "bun install"?

`readline` from node isn't implemented yet. 

> Ȅ�

This is a bug too, it's dumping undefined memory when it should be error text

**Comment by Jarred-Sumner** [comment]
> This is a bug too, it's dumping undefined memory when it should be error text

This is fixed in https://github.com/Jarred-Sumner/bun/commit/0843e383b249f9ed9b257767e904f2335b65dfc2

> Why not wrapping with promises? I think promisify can be good solution :).

Fixed in https://github.com/Jarred-Sumner/bun/commit/2cdbd2de83981aa0e0bc26db5b5ebd261507f112

Feel free to open a separate issue for `readline`
