### ISSUE TITLE
[install] Segmentation fault on when installing `@fortawesome` and `react`

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#1871]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Mac OS Intel (Darwin 21.6.0 x86_64 i386)

### What steps can reproduce the bug?

I was able to reduce the issue to this set of installed deps (without caching for `@fortawesome/*`)

As soon as I remove one of them install works, and re-adding the missing one also works.

```json
{
  "name": "bun-segfault",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "6.2.0",
    "@fortawesome/free-solid-svg-icons": "6.2.0",
    "@fortawesome/react-fontawesome": "0.2.0",
    "react": "18.0.0"
  }
}
```

### What do you see instead?

```
bun install v0.5.1 (42e9f6e0)
[1]    33272 segmentation fault  bun i
```

**Comment by alexlamsl** [comment]
Ran with latest `main` without segfault:
```json
$ cat package.json
{
  "name": "bun-segfault",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "6.2.0",
    "@fortawesome/free-solid-svg-icons": "6.2.0",
    "@fortawesome/react-fontawesome": "0.2.0",
    "react": "18.0.0"
  }
}
```
```console
$ rm -rf bun.lockb node_modules ~/.bun/install
$ bun install
bun install v0.5.1 (17bde9bc)
 + @fortawesome/fontawesome-svg-core@6.2.0
 + @fortawesome/free-solid-svg-icons@6.2.0
 + @fortawesome/react-fontawesome@0.2.0
 + react@18.0.0

 10 packages installed [2.36s]
$ ls node_modules
@fortawesome  js-tokens  loose-envify  object-assign  prop-types  react  react-is
```
Should be addressed by https://github.com/oven-sh/bun/commit/24e8aa105f9d5d55d560884eaa38dc2e51d403aa and https://github.com/oven-sh/bun/commit/17bde9bc86e97bd1d9f2dc80924dde780b759635 &minus; `bun upgrade --canary` might carry the fix.

**Comment by ArnaudBarre** [comment]
Yep working on canary!
