### ISSUE TITLE
`process.stdout.write()` hangs after many writes

### ISSUE THREAD

**Issue by sno2** [oven-sh/bun#1872]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create the following program `index.js`:

```js
for (let i = 0; ;i++) {
	process.stdout.write(`${i}\n`);
}
```

Run the program using `bun index.js`.

### What is the expected behavior?

The program should log out the numbers from 0 to infinity until the program exits.

### What do you see instead?

The program hangs after roughly 25,000 logs. Here are the numbers that it stopped at after 5 runs:

28696
26579
27236
25192
27163

**Comment by sno2** [comment]
This also seems to be leaking memory while stalling. The WSL instance's memory grows from 20% of my 32gb of ram to 85% after letting it stall for 3 minutes.

**Comment by Jarred-Sumner** [comment]
.write() buffers if the entire chunk wasn't written

You would see similar leaks in node if calling .write to a socket

**Comment by sno2** [comment]
Are you saying this is a problem with never flushing the buffer in some cases then?

**Comment by birkskyum** [comment]
@sno2, is this still an issue?

**Comment by Electroid** [comment]
It appears that this has been fixed, as of Bun v1.0.7. (let it running for a while, got to `51642992`) If you still run into this issue, please feel free to re-open.
