### ISSUE TITLE
Add CommonJS wrapper for `await import`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#1878]
This will fix a number of cases where `await import` breaks for CommonJS

**Comment by Kleywalker** [comment]
Is this related to issue [#7636](https://github.com/oven-sh/bun/issues/7636). Are there any plans to implement this soon?

**Comment by Jarred-Sumner** [comment]
This issue is stale and no longer relevant (it was before Bun supported CommonJS natively)

**Comment by Jarred-Sumner** [comment]
You’re asking for CommonJS or IIFE output support for either Bun.Transpiler or Bun.build 

That is a different thing than this

**Comment by Kleywalker** [comment]
Ok, thanks anyway. 😊
