### ISSUE TITLE
`fetch` typing in `bun-types` doesn’t accept URL

### ISSUE THREAD

**Issue by controversial** [oven-sh/bun#1880]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Shell:
```
bun add bun-types
```
`tsconfig.json`:
```
  "types": ["bun-types"],
```
`index.ts`:
```
const url = new URL('https://google.com/');
const response = await fetch(url);
```
Typescript reports an error on the “fetch” call: “No overload matches this call ... Argument of type 'URL' is not assignable to parameter of type 'string' ... Argument of type 'URL' is not assignable to parameter of type 'Request'.”

### What is the expected behavior?

The typings for `fetch` should accept a URL; the Fetch API is designed to accept a URL object. This usage works in Bun at runtime; it just doesn’t pass type checking.

### What do you see instead?

Typescript reports an error from the `fetch` definition provided in `bun-types`.

### Additional information

[Documentation that `fetch` should take a URL](https://developer.mozilla.org/en-US/docs/Web/API/fetch)

**Comment by controversial** [comment]
Similarly, the types for `Bun.file` don't accept a URL, even though the method seems to work with a URL at runtime

**Comment by gaurishhs** [comment]
> Similarly, the types for `Bun.file` don't accept a URL, even though the method seems to work with a URL at runtime

```js
Bun.serve({
    fetch() {
        return new Response(
            Bun.file(new URL('./jsconfig.json'))
        )
    }
})
```

If you meant this, This doesn't work for me...

**Comment by controversial** [comment]
@gaurishhs The following example runs for me: 
```js
Bun.write(Bun.file(new URL('test.txt', import.meta.url)), 'hello');
```

---

Your example throws a type error, but so does this on its own:
```js
new URL('./jsconfig.json');
```
The type error appears because you don’t pass a fully qualified URL in the first parameter, but you omit the second “base” parameter. From MDN:
> If `url` is a relative URL, `base` is required

You need to pass a fully qualified URL (starting with `file://`), or else construct one by passing a fully qualified `base` for your incomplete URL in the second parameter.

**Comment by gaurishhs** [comment]
@controversial I probably didnt read that part, Was able to reproduce this time.. The latest commit on my PR fixes this
