### ISSUE TITLE
url() paths in .css files use incorrect port when dev server is listening on non-default port

### ISSUE THREAD

**Issue by nirrek** [oven-sh/bun#1885]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Basic file structure:
```
├── index.js
├── public
│   └── index.html
├── referenced-image.svg
└── styles.css
```

Have the .js file import the .css file which specifies the image as a url() asset
```
// index.js
import "./styles.css";

// styles.css
div {
  background-image: url("./referenced-image.svg");
}
```

Have something bound to the default port (3000) so the dev server has to pick the next available port to listen on.

Now start the dev server
```
$ bun dev
[3.00ms] bun!! v0.5.1 (42e9f6e0)

  Link: http://localhost:3001
        public/index.html
```

### What is the expected behavior?

If we look at the .css file being served we want to see that the `url()` specifies port `3001`

```
curl localhost:3001/styles.css

@supports (hmr-bid:1194587806) {}

@supports (hmr-wid:1194587806) and (hmr-file:"styles.css") {}
/* styles.css*/
div {
  background-image: url('http://localhost:3001/hash:494b0125a97b37d6/referenced-image.svg');
}
```

### What do you see instead?

What we actually see is that the url() specifies the default port (3000) instead of 3001

```
curl localhost:3001/styles.css

@supports (hmr-bid:1194587806) {}

@supports (hmr-wid:1194587806) and (hmr-file:"styles.css") {}
/* styles.css*/
div {
  background-image: url('http://localhost:3000/hash:494b0125a97b37d6/referenced-image.svg');
}
```

### Additional information

If we manually specify a non-default port (which can be listened to), it does work. So seems to have something to do with when the port to listen on is automatically chosen.

```
bun dev --port 3001

curl localhost:3001/styles.css

@supports (hmr-bid:1194587806) {}

@supports (hmr-wid:1194587806) and (hmr-file:"styles.css") {}
/* styles.css*/
div {
  background-image: url('http://localhost:3001/hash:494b0125a97b37d6/referenced-image.svg');
}
```

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
