### ISSUE TITLE
String.replace, replaceValue is not the same 

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#1890]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Linux 6.1.6-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

```js
const main = "Hello";
const side = "$$Help";

const replaced = main.replace("Hello", side);

// They should be the same
console.log(replaced);
console.log(side);
```

### What is the expected behavior?

```
$$Help
$$Help
```

### What do you see instead?

```
$Help
$$Help
```

### Additional information

Now I tested the same code with `node` and `deno` and they behave the same. Idk if this a bug or magic in JS

**Comment by xhyrom** [comment]
also happens when you escape $ with `\` so `\$\$`, funny JS moment

**Comment by Kapsonfire** [comment]
https://stackoverflow.com/questions/38866071/javascript-replace-method-dollar-signs
