### ISSUE TITLE
exec() return an output consistently 

### ISSUE THREAD

**Issue by alexreyes** [oven-sh/bun#1893]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Run the following code by calling `bun test.js` in the terminal 10 times. 

```
const { exec } = require('child_process');

exec('which bun', (error, stdout, stderr) => {
  if (error) {console.log("ERROR: ", error); return;}

  console.log('stdout: ', stdout); 
});
```

Sometimes an `stdout` value is printed, sometimes it's not. 

Example output: 

Iteration 1: `stdout:  /Users/hack/.bun/bin/bun`
Iteration 5: `stdout: `

Also, the following doesn't return any `stdout` values *at all* (while on node it runs consistently): 

```
const { exec } = require('child_process');

for (var i = 0; i < 10; i++) {
  exec('which bun', (error, stdout, stderr) => {
    if (error) {console.log("ERROR: ", error); return;}

    console.log('stdout: ', stdout); 
  });
}
```
Output: 
```
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
stdout:  
``` 
Node output: 

```
stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun

stdout:  /Users/hack/.bun/bin/bun
```

### What is the expected behavior?

Written above

### What do you see instead?

exec() doesn't always return a value

**Comment by Electroid** [comment]
Tested and this no longer occurs as of Bun v1.0.26. If you're still experiencing this issue, please let us know and we'll re-open this issue.
