### ISSUE TITLE
installing without internet connection

### ISSUE THREAD

**Issue by janwilmake** [oven-sh/bun#1899]
### What platform is your computer?

macOS

### How did you attempt to install or upgrade?

I don't know how

### What do you see instead?

I don't know how to install without internet connection

### Additional information

I'd like to know how I can install bun.sh without an internet connection on a computer that is 100% isolated (put the files there via flash drive)

**Comment by Jarred-Sumner** [comment]
bun is a single binary executable. You can copy Bun onto a flash drive and then copy it onto your computer
