### ISSUE TITLE
WebSocket Client Hangs with Large Payload

### ISSUE THREAD

**Issue by marcoschwartz** [oven-sh/bun#1900]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

I've been trying Bun in our app that uses WebSockets to communicate between different services, and I am encountering an issue with Bun with 'large' payloads (more than 80,000 bytes in length).

I am using the example code for the client WebSocket, as well as the example code for the server.

Server code:

```
Bun.serve({
    port: 8091,
    websocket: {
        open(ws) {

            console.log("Connection ...")

        },
        message(ws, message) {

            console.log("Received message, sending it back to client")

            var status = ws.send(message);
            console.log(status)

        },
    },

    fetch(req, server) {

        if (server.upgrade(req))
            return;

        return new Response("Regular HTTP response");
    },
});
```

Client code:

```
const ws = new WebSocket('ws://0.0.0.0:8091');

ws.onopen = function(event) {

    const buf = Buffer.allocUnsafe(100000);

    ws.send(buf)

}
ws.addEventListener('message', (event) => {

    console.log("Got message back")

});
```

In this example the server receives the message, but the client never receives it back as an echo. In the equivalent code in Node (using the ws package), it works just fine.

I also checked, there is no backpressure whatsover at this payload size, both in Bun and with Node.

### What is the expected behavior?

As for the Node version using the ws npm package, I think it should work fine even for large payloads (under the 16 MB limit by default of course).

### What do you see instead?

The client never gets back the data sent by the WebSocket server.

**Comment by antlanc7** [comment]
found out that maximum size working is 65532, with 65533 will fail.
Reproducible with one single file:
```
Bun.serve({
  port: 8091,
  websocket: {
    open(ws) {
      console.log("Connection ...");
    },
    message(ws, message) {
      console.log("Received message, sending it back to client");
      var status = ws.send(message);
      console.log(status);
    },
  },

  fetch(req, server) {
    if (server.upgrade(req)) return;
    return new Response("Regular HTTP response");
  },
});

// client
const ws = new WebSocket("ws://0.0.0.0:8091");
ws.onopen = function (event) {
  const buf = Buffer.allocUnsafe(65532); // if setting to 65533, it will fail
  ws.send(buf);
};
ws.addEventListener("message", (event) => {
  console.log("Got message back");
  console.log(event.data);
});
```

**Comment by antlanc7** [comment]
also tried moving the creation of the buffer directly in the server, in this case the client hangs at 16381 buffer size:
```
Bun.serve({
  port: 8091,
  websocket: {
    open(ws) {
      console.log("Sending buffer to new client ...");
      const buf = Buffer.allocUnsafe(16380); // if setting to 16381, it will fail
      ws.send(buf);
    },
    message(ws, message) {},
  },

  fetch(req, server) {
    if (server.upgrade(req)) return;
    return new Response("Regular HTTP response");
  },
});

// client
const ws = new WebSocket("ws://0.0.0.0:8091");
ws.addEventListener("message", (event) => {
  console.log("Got message from server");
  console.log(event.data);
});
```

**Comment by Jarred-Sumner** [comment]
I think this is a bug in Bun's WebSocket client protocol implementation.

The server has a default max payload of 16 MB which is very high 

https://github.com/oven-sh/bun/blob/b767f9a99a2b4b6bd8f54cb851bda6a2696587ce/src/bun.js/api/server.zig#L2492

**Comment by marcoschwartz** [comment]
Thanks for confirming, initially I thought it was coming from my dev computer so already tried it on Linux with the same behaviour. Do you know if it's something difficult to fix? It's the last obstacle to have our whole SaaS run on Bun :) (as we have some large packets shared between services sometimes).
