### ISSUE TITLE
Server not responding to nginx requests

### ISSUE THREAD

**Issue by Smugaski** [oven-sh/bun#1901]
### What version of Bun is running?

0.5.2

### What platform is your computer?

Linux 5.14.0-162.6.1.el9_1.0.1.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

```js
import { Hono } from "hono"

const app = new Hono()

app.get("/", (ctx) => {
    return ctx.text("hello world")
})

export default {
    port: 6968,
    fetch: app.fetch,
}
```

### What is the expected behavior?

Respond to http request and show text.

### What do you see instead?

Web page doesn't load. nginx log below:
```
2023/01/23 14:34:44 [error] 7769#7769: *78 upstream timed out (110: Connection timed out) while reading response header from upstream, client: CLOUDFLARE_IP, server: exampledomain.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:6968/", host: "exampledomain.com"
```
![aPaLOvsMsh](https://user-images.githubusercontent.com/73793685/214654585-c593022b-b22f-45c3-b547-80f62e74ba17.png)

### Additional information

Everything was working fine until I upgraded bun to 0.5.1. I was using bun 0.4.0 before.

**Comment by Smugaski** [comment]
I have also tested this using Bun.serve(without honojs on top) and it still doesn't respond. The code can be found below:
```ts
Bun.serve({
    fetch(req: Request) {
        return new Response("hello world")
    },
    development: true,
    port: 6968,
})
```

**Comment by BSN4** [comment]
post your nginx config

**Comment by Smugaski** [comment]
> post your nginx config

```
server {
    listen 80;
    server_name exampledomain.com;

    location /webhook {
        return https://$host/api;
    }

    location / {
        proxy_pass http://127.0.0.1:6968/;
    }
}
```

**Comment by Smugaski** [comment]
this does work as I have downgraded bun back to 0.4.0 and everything is working fine.

**Comment by ThatOneBro** [comment]
Does this have anything to do with DNS resolution maybe? @cirospaciari

**Comment by cirospaciari** [comment]
> Does this have anything to do with DNS resolution maybe? @cirospaciari 

I will try to debug this, I don't think is related to DNS because uWS don't depends on DNS module, but it can be related to recent changes.

**Comment by ThatOneBro** [comment]
> > Does this have anything to do with DNS resolution maybe? @cirospaciari
> 
> I will try to debug this, I don't think is related to DNS because uWS don't depends on DNS module, but it can be related to recent changes.

Oh yeah that's a good point, we're not actually using the new `node:dns` code here. But yeah seems like it may be related to something new in 0.5.0

**Comment by cirospaciari** [comment]
> > > Does this have anything to do with DNS resolution maybe? @cirospaciari
> > 
> > I will try to debug this, I don't think is related to DNS because uWS don't depends on DNS module, but it can be related to recent changes.
> 
> Oh yeah that's a good point, we're not actually using the new `node:dns` code here. But yeah seems like it may be related to something new in 0.5.0

I think we upgrade the uws version, I think is maybe related to this

**Comment by Smugaski** [comment]
> Does this have anything to do with DNS resolution maybe? @cirospaciari

nope, as it works fine when I downgrade.

**Comment by cirospaciari** [comment]
> > post your nginx config
> 
> ```
> server {
>     listen 80;
>     server_name exampledomain.com;
> 
>     location /webhook {
>         return https://$host/api;
>     }
> 
>     location / {
>         proxy_pass http://127.0.0.1:6968/;
>     }
> }
> ```

@Smugaski can you try this configuration?

```
server {
    listen 80;
    server_name exampledomain.com;

    location /webhook {
        return https://$host/api;
    }

    location / {
        proxy_pass http://127.0.0.1:6968/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

In my tests it did not work without `proxy_http_version 1.1;` , but worked with it.

**Comment by Smugaski** [comment]
> > > post your nginx config
> > 
> > 
> > ```
> > server {
> >     listen 80;
> >     server_name exampledomain.com;
> > 
> >     location /webhook {
> >         return https://$host/api;
> >     }
> > 
> >     location / {
> >         proxy_pass http://127.0.0.1:6968/;
> >     }
> > }
> > ```
> 
> @Smugaski can you try this configuration?
> 
> ```
> server {
>     listen 80;
>     server_name exampledomain.com;
> 
>     location /webhook {
>         return https://$host/api;
>     }
> 
>     location / {
>         proxy_pass http://127.0.0.1:6968/;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection 'upgrade';
>         proxy_set_header Host $host;
>         proxy_cache_bypass $http_upgrade;
>         proxy_set_header X-Forwarded-For $remote_addr;
>     }
> }
> ```
> 
> In my tests it did not work without `proxy_http_version 1.1;` , but worked with it.

it works now thanks, however I think that this should be fixed.

**Comment by cirospaciari** [comment]
> > > > post your nginx config
> > > 
> > > 
> > > ```
> > > server {
> > >     listen 80;
> > >     server_name exampledomain.com;
> > > 
> > >     location /webhook {
> > >         return https://$host/api;
> > >     }
> > > 
> > >     location / {
> > >         proxy_pass http://127.0.0.1:6968/;
> > >     }
> > > }
> > > ```
> > 
> > 
> > @Smugaski can you try this configuration?
> > ```
> > server {
> >     listen 80;
> >     server_name exampledomain.com;
> > 
> >     location /webhook {
> >         return https://$host/api;
> >     }
> > 
> >     location / {
> >         proxy_pass http://127.0.0.1:6968/;
> >         proxy_http_version 1.1;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection 'upgrade';
> >         proxy_set_header Host $host;
> >         proxy_cache_bypass $http_upgrade;
> >         proxy_set_header X-Forwarded-For $remote_addr;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my tests it did not work without `proxy_http_version 1.1;` , but worked with it.
> 
> it works now thanks, however I think that this should be fixed.

Sure I'm taking a look at it.

**Comment by cirospaciari** [comment]
This was fixed in the latest release.
