### ISSUE TITLE
Segmentation fault when using `bun bun` on a new project

### ISSUE THREAD

**Issue by zodiia** [oven-sh/bun#1904]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Linux 6.1.6-zen1-2-zen x86_64 unknown

### What steps can reproduce the bug?

1. In an empty folder, run `bun init`
2. Without modifying anything, run `bun bun index.ts`

### What is the expected behavior?

Create a .bun file

### What do you see instead?

A segmentation fault, without any additional information

**Comment by Jarred-Sumner** [comment]
I wish i knew how to repro this

Could you upload the folder as a zip/tarball?

**Comment by zodiia** [comment]
I can upload a tarball of this bug, but it happens every time I create a new project using `bun init`:
![image](https://user-images.githubusercontent.com/14910727/214791161-859dc8ca-3a43-46f2-ac72-a44f51a768a1.png)
I would be uploading a new project and nothing else.

Let me know if you still want me to upload it, or if you need any additional information about my system.

**Comment by cyrus01337** [comment]
Can vouch this also happens when using `bun create next` on Solus with Linux Kernal 6.1.5-229.current x86_64. Unsure if using a VM would be considered overkill for diagnosing such a problem.

**Comment by cyrus01337** [comment]
When spinning up a Ubuntu 22.10 VM running an older kernal version (5.19.0-29-generic), installing Bun, creating a project at the path `~/Desktop/project` then running `bun create next .` immediately followed by `bun bun` causes a segfault.

**Comment by cyrus01337** [comment]
Still getting this on Ubuntu in the canary build (`bun upgrade --canary`), is this my fault or shall I create a separate issue?

**Comment by Jarred-Sumner** [comment]
CI is backed up
