### ISSUE TITLE
Can't read a file with bun, errors out when node doesn't 

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#1905]
### What version of Bun is running?

0.5.2

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Code:

```javascript
import * as fs from "fs"
import * as path from "path"

function* walkSync(dir: string): IterableIterator<string> {
  const files = fs.readdirSync(dir, { withFileTypes: true })
  for (const file of files) {
    if (file.isDirectory()) {
      yield* walkSync(path.join(dir, file.name))
    } else {
      yield path.join(dir, file.name)
    }
  }
}

async function getFiles(dir: string) {
  let files: string[] = []
  for (const filePath of walkSync(dir)) {
    files.push(filePath)
  }
  return files
}

const files = await getFiles("/Users/nikiv/Dropbox/Write/knowledge/docs")

const mdFiles = files.filter((file) => {
  return file.endsWith(".md")
})

fs.readFile(mdFiles[0], "utf-8", (err, data) => {
  if (err) {
    console.error(err)
  }
  console.log(data)
})
```

Basically what above does is try to scan for files and then read one of the files. 

The file it tries to open is this one: https://github.com/nikitavoloboev/knowledge/blob/main/docs/3d-printing/3d-printing.md

With bun if I run above code I get: 

```
❯ bun wiki.ts 
fish: Job 1, 'bun wiki.ts' terminated by signal SIGBUS (Misaligned address error)
```

With node I get:

```
❯ tsx wiki.ts
# 3D Printing

## Links
```

So it works. 

I am not sure if this is the API I should be using to open files, maybe thats the issue. I just took node API.

I read bun readme and did not find any docs not on how to parse directories, not on how to open files so was not sure.

### What is the expected behavior?

It should parse the file and give me the output of it.

### What do you see instead?

Error, crash.

**Comment by nikivdev** [comment]
I found Bun.file() in readme https://github.com/oven-sh/bun#fast-paths-for-web-apis

But that just returns:

```
❯ bun wiki.ts
FileRef ("/Users/nikiv/Dropbox/Write/knowledge/docs/research/asking-questions.md") {
  type: "text/markdown"
}
```

Actually strangely or not, the file it reads is different from node so the generator thing to pass through the files works differently on node too.

**Comment by nikivdev** [comment]
Actually I get error reading file with this too strangely:

```js
let file = Bun.file(mdFiles[0])
console.log(await file.text())
```

Get:

```
❯ bun wiki.ts
fish: Job 1, 'bun wiki.ts' terminated by signal SIGBUS (Misaligned address error)
```

mdFiles[0] is a valid path. `/Users/nikiv/Dropbox/Write/knowledge/docs/research/asking-questions.md` in my case.

**Comment by birkskyum** [comment]
This works in bun 0.8.1 - can be closed

```
➜ bun foo.ts
# 3D Printing

Would love to get a 3D printer at some point and do some [hardware](../hardware/hardware.md) projects.

## Links

- [ShapeWays](https://www.shapeways.com/) - Upload 3D model, choose materials and get the thing.
```
