### ISSUE TITLE
WebAssembly missing in bun-types

### ISSUE THREAD

**Issue by pfgithub** [oven-sh/bun#1908]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 21.2.0 x86_64 i386

### What steps can reproduce the bug?

```sh
bun init -y
bun add typescript
echo "console.log(WebAssembly);" > index.ts
bun run tsc
```

### What is the expected behavior?

No errors

### What do you see instead?

```js
index.ts:1:13 - error TS2304: Cannot find name 'WebAssembly'.

1 console.log(WebAssembly);
              ~~~~~~~~~~~


Found 1 error in index.ts:1

```

### Additional information

It still errors if "DOM" is added to the tsconfig's compilerOptions.lib, so I'm not sure how to work around it

**Comment by colinhacks** [comment]
Fixed in https://github.com/oven-sh/bun/pull/2003
