### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by andidev** [oven-sh/bun#191]
Is it possible to run bun with flow? Dont see any documentation or issues of it but seems that it cannot read the flow syntax.
Any workarounds this maybe?

**Comment by Jarred-Sumner** [comment]
Not without some awful hacks, unfortunately.

The easiest way for now would be a build step before bun that strips flow types.

Longer-term, Bun will get an ESM module loader/resolve API.

**Comment by Electroid** [comment]
It will be a while before we prioritize Flow, with a module loader/resolver API. For now, you can use [`flow-remove-types`](https://github.com/facebook/flow/tree/main/packages/flow-remove-types#flow-remove-types) which will convert your Flow code to JavaScript, then run it using Bun.

**Comment by Electroid** [comment]
It's possible to use Bun's [loader API](https://github.com/oven-sh/bun#loader-api), which is based on esbuild, to transpile [Flow](https://flow.org/en/docs/getting-started/) to JavaScript.

```js
import { plugin } from "bun";

await plugin({
  name: "flow",
  setup(build) {
    const { readFileSync } = require("fs");
    const flowRemoveTypes = require("flow-remove-types");
    build.onLoad({ filter: /\.(j|t)sx?$/ }, ({ path }) => {
      const contents = readFileSync(path, "utf-8");
      const header = contents.substring(0, contents.indexOf("\n"));
      if (!header.includes("@flow")) {
        return { contents, loader: null };
      }
      return {
        contents: flowRemoveTypes(contents, { pretty: true }).toString(),
        loader: "jsx",
      }
    });
  }
});

import { foo } from "./flow";
console.log(foo(1234));
```

Then import the plugin at the entrypoint of your code.

```js
// @flow
// Example: https://flow.org/en/docs/usage/
export function foo(x: ?number): string {
  if (x) {
    return x;
  }
  return "default string";
}
```
