### ISSUE TITLE
When I install react-native-skia it doesn't execute the command bun install postinstall

### ISSUE THREAD

**Issue by meftunca** [oven-sh/bun#1912]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

When I install react-native-skia it doesn't execute the command bun install postinstall.
I can't run my android project because of this problem

**Comment by birkskyum** [comment]
@meftunca , have you tried adding it to [trustedDependencies](https://bun.sh/guides/install/trusted)?

**Comment by meftunca** [comment]
@birkskyum No, but I will try tomorrow ?

**Comment by Electroid** [comment]
Duplicate of #4959

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave  in #7132 

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.
