### ISSUE TITLE
 'bun i' terminated by signal SIGSEGV during esbuild postinstall script in bun install on very old version of bun

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [oven-sh/bun#1916]
### What version of Bun is running?

0.5.1

### What platform is your computer?

Linux 6.0.18-300.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

Hi! I was checking if I could change from yarn to bun and on the command `bun i` an error appeared. 

It stopped at package "esbuild": "0.17.5"

### What is the expected behavior?

To all packages to be installed correctly.

### What do you see instead?

```
bun install v0.5.1 (42e9f6e0)
  🔍 @esbuild/linux-x64 [81/109] fish: Job 1, 'bun i' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Jarred-Sumner** [comment]
Please try again in canary 

We should push up the new build soon so people stop running into this

**Comment by ThatOneBro** [comment]
I this this has already been solved since. Closing this for now. Please re-open if this is still a problem in the latest version
