### ISSUE TITLE
Svelte Transpiler

### ISSUE THREAD

**Issue by wcervini** [oven-sh/bun#193]
Its posible to include Svelte Transpiler......

**Comment by Electroid** [comment]
Bun now has a [Loader API](https://github.com/oven-sh/bun#loader-api) that allows you to add custom transpilation, like for Svelte, using esbuild plugins.

Here's the plugin:
```js
import { plugin } from "bun";

await plugin({
  name: "svelte loader",
  async setup(builder) {
    const { compile } = await import("svelte/compiler");
    const { readFileSync } = await import("fs");

    // Register a loader for .svelte files
    builder.onLoad({ filter: /\.svelte$/ }, ({ path }) => ({
      // Run the Svelte compiler on the import path
      contents: compile(readFileSync(path, "utf8"), {
        filename: path,
        generate: "ssr",
      }).js.code,

      // Set the loader to "js"
      // This runs it through Bun's transpiler
      loader: "js",
    }));
  },
});
```

And here's how you would use it:
```js
import "./myplugin.js";
import MySvelteComponent from "./component.svelte";

console.log(mySvelteComponent.render());
```

We might consider making this a default in the future, but for now you can customize it with plugins.

**Comment by MircoSteyer** [comment]
I came across this issue while trying to figure out why my bun test runner would crash during the compilation step for the svelte components.

In case it saves someone's time, don't forget to preprocess your components, if you use `lang=ts` for your scripts, as the compiler only parses JS. Your plugin might then look like this:

```ts
await plugin({
	name: 'svelte loader',
	async setup(builder) {
		const { compile, preprocess } = await import('svelte/compiler');
		const { readFileSync } = await import('fs');

		builder.onLoad({ filter: /\.svelte$/ }, async ({ path }) => {
			return {
				// Use the preprocessor of your choice.
				contents: compile(
					await preprocess(readFileSync(path, 'utf8'), vitePreprocess()).then(
						(processed) => processed.code
					),
					{
						filename: path,
						generate: 'dom'
					}
				).js.code,
				loader: 'js'
			};
		});
	}
});
```

While this doesn't technically add anything to the ticket, I thought it might safe someone else a lot of time.
