### ISSUE TITLE
Allow `-D` as an alias for `--development` in `bun add` (in addition to `-d`)

### ISSUE THREAD

**Issue by dtinth** [oven-sh/bun#1931]
### What is the problem this feature would solve?

```
bun add -D @types/yargs
```

This results in a CLI parsing error.

**npm, Yarn, and pnpm all use `-D` for `--dev` or `--save-dev`.**

- npm: 
   <img width="248" alt="image" src="https://user-images.githubusercontent.com/193136/215319774-730da9e7-95aa-47cd-9c48-18c37d0d0a4b.png">

- yarn:
   <img width="382" alt="image" src="https://user-images.githubusercontent.com/193136/215319788-b4205a4b-b969-4a8f-9ede-f8773c2b8d78.png">

- pnpm:
   <img width="240" alt="image" src="https://user-images.githubusercontent.com/193136/215319803-9817c650-761e-4327-bceb-884be7274d65.png">

Only `bun` uses `-d`. This increased the cognitive load, e.g. if I’m using bun, I need to use `-d`, otherwise I use `-D`.

### What is the feature you are proposing to solve the problem?

Also allow `-D` in addition to `-d`.

### What alternatives have you considered?

Remove `-d` and replace with `-D`, but that is a breaking change (but it might be fine given that Bun is still v0.x).

### Related
- [x] https://github.com/oven-sh/bun/pull/3989

**Comment by Jarred-Sumner** [comment]
yes definitely

This is not an intentional decision. The CLI argument parser library we forked doesn't like single-letter capital arguments and didn't have time to fix yet

**Comment by jakeboone02** [comment]
Seems like this was already fixed in or before v0.7.3 (I think by 78081cbb40b3149be3fcd7f050ec365c499421d0).

![image](https://github.com/oven-sh/bun/assets/366438/ce43ad04-8408-4e67-9b26-6ba26ed81229)

**Comment by dtinth** [comment]
Seems like this can be closed now, thank you!

Fixed by #3989.
