### ISSUE TITLE
execute code from stdin

### ISSUE THREAD

**Issue by Kapsonfire** [oven-sh/bun#1932]
### What is the problem this feature would solve?

Executing code from CLI without storing in a file before

### What is the feature you are proposing to solve the problem?

bun -e 'console.log("Hello world")'

### Why -e
e => eval

**Comment by 90dy** [comment]
Eval take it from command line options,

I would like something like node, where you can run it that way:
```bash
bun run <<< "console.log('hello world !')"
```

Or maybe with an option
```bash
bun run --stdin <<< "[...]"
```

What do you think about that ?

**Comment by FreePhoenix888** [comment]
It would be nice if this feature would be implemented not only by using CLI but also right in the code
Example:
```
const code = "const result: number = 1+1; result"
const result = Bun.eval(code)
```

Our [organization](https://github.com/deep-foundation/) needs it. Right now we transpile code to js and eval it

**Comment by FreePhoenix888** [comment]
For some situations `bun repl --eval` can be used but note that it does not evaulaute like `eval`. If you want to get some result you have to use console.log for example or write to file.

This command will not write 2 to stdout:
```ts
bun repl --eval "const result: number = 1+1; result"
```

This command will write 2 to stdout:
```ts
bun repl --eval "const result: number = 1+1; console.log(result)"
```

**Comment by jhmaster2000** [comment]
> For some situations `bun repl --eval` can be used but note that it does not evaulaute like `eval`. If you want to get some result you have to use console.log for example or write to file.
> 
> This command will not write 2 to stdout:
> 
> ```ts
> bun repl --eval "const result: number = 1+1; result"
> ```
> 
> This command will write 2 to stdout:
> 
> ```ts
> bun repl --eval "const result: number = 1+1; console.log(result)"
> ```

If you replace --eval with --print on the first one it will show the 2.

**Comment by FreePhoenix888** [comment]
> ```ts
> bun repl --eval "const result: number = 1+1; console.log(result)"
> ```

True!

**Comment by FreePhoenix888** [comment]
Array:
```
freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; [result]"
[ 2 ]
```

**Comment by FreePhoenix888** [comment]
Object:
```
freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result}"
2

freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result: result}"
2
```

**Comment by FreePhoenix888** [comment]
Ok there is 

> Object:
> 
> ```
> freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result}"
> 2
> 
> freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result: result}"
> 2
> ```

Ok we can stringify our object then:
```
freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; JSON.stringify({result})"
'{"result":2}'
```

**Comment by jhmaster2000** [comment]
> Ok there is
> 
> > Object:
> > ```
> > freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result}"
> > 2
> > 
> > freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result: result}"
> > 2
> > ```
> 
> Ok we can stringify our object then:
> 
> ```
> freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; JSON.stringify({result})"
> '{"result":2}'
> ```

This is because that's just how JS works, Node does the same:
```
~ $ node -p "const result = 1+1; {result: result}"
2
~ $ node -p "const result = 1+1; {result}"
2
```
The `{...}` at the end are interpreted as a block, not an object. The `result` inside is then interpreted just as the variable by itself, alone in the block. In the `result: result` case it interprets the 1st `result:` as a label, hence still doesn't error.

You don't need to JSON.stringify, you can just wrap the object in parenthesis: `({ result })` and that will force the JS engine to treat it as JS since the parens make it an expression.

The parenthesis trick is what is done under the hood in the Node REPL when an unparenthesized object is entered as the only input to make it work nicer, this feature is still missing in Bun REPL but it will be implemented soon. Although it still wouldn't "fix" what you're showing since it only works when the object is alone, as shown that it still fails in Node there.

**Comment by FreePhoenix888** [comment]
> > Ok there is
> > > Object:
> > > ```
> > > freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result}"
> > > 2
> > > 
> > > freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; {result: result}"
> > > 2
> > > ```
> > 
> > 
> > Ok we can stringify our object then:
> > ```
> > freephoenix888@FreePhoenix:~/Programming/bun-test$ bun repl --print "const result: number = 1+1; JSON.stringify({result})"
> > '{"result":2}'
> > ```
> 
> This is because that's just how JS works, Node does the same:
> 
> ```
> ~ $ node -p "const result = 1+1; {result: result}"
> 2
> ~ $ node -p "const result = 1+1; {result}"
> 2
> ```
> 
> The `{...}` at the end are interpreted as a block, not an object. The `result` inside is then interpreted just as the variable by itself, alone in the block. In the `result: result` case it interprets the 1st `result:` as a label, hence still doesn't error.
> 
> You don't need to JSON.stringify, you can just wrap the object in parenthesis: `({ result })` and that will force the JS engine to treat it as JS since the parens make it an expression.
> 
> The parenthesis trick is what is done under the hood in the Node REPL when an unparenthesized object is entered as the only input to make it work nicer, this feature is still missing in Bun REPL but it will be implemented soon. Although it still wouldn't "fix" what you're showing since it only works when the object is alone, as shown that it still fails in Node there.

Thank you for exaplanations! Can you please comment [my new issue](https://github.com/oven-sh/bun/issues/5105)?

**Comment by Electroid** [comment]
This has now been implemented.

```js
❯ bun -e 'console.log(Bun.version)'
1.0.26
```

**Comment by FreePhoenix888** [comment]
> This has now been implemented.
> 
> ```js
> ❯ bun -e 'console.log(Bun.version)'
> 1.0.26
> ```

What is the difference between the new solution and `bun repl --eval` ?

**Comment by Electroid** [comment]
We still need to implement: `echo "console.log('Hello') | bun`

**Comment by adamfei** [comment]
It works like that:
```
echo "console.log('Hello World')" | bun -
```

**Comment by FreePhoenix888** [comment]
> It works like that:
> 
> ```
> echo "console.log('Hello World')" | bun -
> ```

Are you sure?
```
freephoenix888@FreePhoenix888:~$ echo "console.log('Hello World')" | bun -
error: Script not found "-"

```
What version of bun do you use?
