### ISSUE TITLE
fs.createWriteStream quits before the end of a large(ish) file

### ISSUE THREAD

**Issue by controversial** [oven-sh/bun#1939]
### What version of Bun is running?

0.5.1 / 0.5.2

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

First find a reasonably large file (mine is ~322 KB). Then:
```js
import fs from 'fs';

let len = 0;
fs.createReadStream(new URL('./path/to/largeish/file', import.meta.url))
  .on('data', (chunk) => {
    len += chunk.toString().length;
    console.log(len);
  })
  .on('end', () => console.log('done!'));
```

Under `node script.js`, this produces:
```
65526
131054
196578
262110
327644
329912
done!
```
Under `bun script.js`, this produces:
```
65526
131054
196578
done!
```

### What is the expected behavior?

Bun should read and stream the whole file.

### What do you see instead?

Bun only reads and streams a few chunks of the file.

### Additional information

Simple reproduction in one screenshot:
<img width="723" alt="Screenshot 2023-01-30 at 4 05 08 AM" src="https://user-images.githubusercontent.com/10377391/215433413-1c3a9649-4f41-4424-8fba-2fc2537d78d0.png">

**Comment by Jarred-Sumner** [comment]
Failing test:

```js

it("Bun.file().stream() read text from large file", async () => {
  var hugely = "HELLO!".repeat(1024 * 1024 * 10);
  const tmpfile = resolve(tmpdir() + "/bun-streams-test.txt");
  writeFileSync(tmpfile, hugely);
  var chunks = [];
  for await (const chunk of Bun.file(tmpfile).stream()) {
    chunks.push(chunk);
  }
  const output = Buffer.concat(chunks).toString();
  expect(output).toHaveLength(hugely.length);
  expect(output).toBe(hugely);
});
```
