### ISSUE TITLE
Support git dependencies with access tokens

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1954]
Bun now supports `github:` dependencies, which also includes `git+https:`, but it does not properly handle access tokens.

`error: Support for dependency type "git" is not implemented yet ("git+https://repo-clone-access:TOKEN@github.com/ORG/repository.git")`

_Originally posted by @dalisoft in https://github.com/oven-sh/bun/issues/1921#issuecomment-1410229681_

**Comment by magiconair** [comment]
Are access tokens for private git repos now supported? If yes how? I cannot find anything in the docs.
