### ISSUE TITLE
SQLite is being built with AVX2 instructions when it shouldn't be

### ISSUE THREAD

**Issue by HaimenToshi** [oven-sh/bun#1966]
### What version of Bun is running?

0.5.4

### What platform is your computer?

Linux 5.15.90-1-lts x86_64

### What steps can reproduce the bug?

This bug started occurring recently as of 4 days ago (after upgrading to a canary build), basically when a POST request is made to Bun.serve() that involves a SQLite query, bun would start filling up the remaining free space of the disk which the project is running from, at the rate of approximately 500MB/s until the free space is exhausted which then results in bun terminating with "Illegal instruction (core dumped)".

Relevant code : 
server.js (the main file I run using bun run)
`import * as API from "./backend";
Bun.serve({
  port: 4449,
  async fetch(req) {
    const { pathname: path } = new URL(req.url);
    if (req.method === 'POST') {
      if (path === '/api') {
        let reqJSON = await Bun.readableStreamToJSON(req.body);
        let response = await API.dbHandle(reqJSON);
        return new Response(response, { headers: { 'Content-Type': 'application/json' }});
      }`

the backend.js file (first step in POST handling) : 
`import { tablesInstaller } from "./dbh";

export const dbHandle = async (reqJSON) => {
    if (reqJSON.fun === 'installtables') {return await tablesInstaller();}
}`

the dbh.js (the SQLite main query handling functions) : 
`export const tablesInstaller = async () => {
    let tables = [
        'items',
        'settings'
    ]
    for (const table of tables) {
        await db.exec("CREATE TABLE IF NOT EXISTS "+table+" (documents TEXT NOT NULL);");
    }
}`

### What is the expected behavior?

Query should execute properly and return result.

### What do you see instead?

Bun starts filling the remaining the free disk space as soon as the POST request is made.

**Comment by Jarred-Sumner** [comment]
The illegal instruction part is the cause

This is either:
-  a miscompilation (unlikely)
- SQLite for avx2+ is being used where it should only be using a non-avx in baseline builds

Can you check if /proc/cpuinfo mentions "avx2"?

**Comment by Jarred-Sumner** [comment]
actually this is the same issue as https://github.com/oven-sh/bun/issues/1756
