### ISSUE TITLE
Bun does not work with commonjs as expected

### ISSUE THREAD

**Issue by gera2ld** [oven-sh/bun#1968]
### What version of Bun is running?

0.5.4

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

In a new directory, run the commands below:

```bash
$ bun init -y
$ bun add encoding-japanese
```

Change the content of `index.ts` to `require('encoding-japanese')`.
Then run `bun run index.ts`.

### What is the expected behavior?

No error.

### What do you see instead?

An error occurred.

```
1 | exports.UTF8_TO_JIS_TABLE = require('./utf8-to-jis-table');
2 | exports.UTF8_TO_JISX0212_TABLE = require('./utf8-to-jisx0212-table');
3 | exports.JIS_TO_UTF8_TABLE = require('./jis-to-utf8-table');
           ^
TypeError: null is not an object (evaluating 'l[U]')
      at .../node_modules/encoding-japanese/src/encoding-table.js:3:8
      at .../node_modules/encoding-japanese/src/config.js:2:4
      at .../node_modules/encoding-japanese/src/index.js:1:4
      at .../index.ts:1:0
```

**Comment by Jarred-Sumner** [comment]
This needs to be documented somewhere but currently if you use CommonJS in your own app code it won't work unless you use `require` or `.cjs`, `.cts` etc

It will work if it's a dependency or `node_modules`

You can always import ESM though

**Comment by gera2ld** [comment]
Actually I got an issue from `node_modules` and then found this when I tried to debug it.

I updated my case, sorry for the trouble.
