### ISSUE TITLE
`.pipeTo(console)`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1969]
If `console` is a `WritableStream`, then you can pipe output to it.

```js
const { stdout } = await spawn({
  cmd: ["bun", "--version"],
  stdout: "pipe",
});
stdout.pipeTo(console);
```

**Comment by Jarred-Sumner** [comment]
this sounds nice but is non-standard and people will get mad at us if we do this

Bun.stdout would be reasonable to pipe to though

**Comment by arianabuilds** [comment]
> Bun.stdout would be reasonable to pipe to though


Running:

```ts
const subprocess = Bun.spawn(['echo', 'hello'])
subprocess.stdout?.pipeTo(Bun.stdout)
```

Errors:

```
TypeError: ReadableStream pipeTo requires a WritableStream
```
