### ISSUE TITLE
Implement `bun publish`

### ISSUE THREAD

**Issue by gaurishhs** [oven-sh/bun#1976]
### What is the problem this feature would solve?

Publishing to NPM Registry.

### What is the feature you are proposing to solve the problem?

A `publish` command which makes use of already logged in information through npm's cli

**Comment by Hebilicious** [comment]
Would be neat to also support `bun publish -r` for monorepos, similar to [pnpm](https://pnpm.io/cli/publish#--recursive--r).

**Comment by joaopaulomoraes** [comment]
Some workaround?

**Comment by nyxb** [comment]
Since I would like to use only bun without installing node at all. I would also like to have a way to publish my packages

**Comment by v1rtl** [comment]
I'm converting some of the tinyhttp stuff to use with Bun and it's the only thing preventing it right now

**Comment by morlay** [comment]
Here is a simple implement without publish hooks (just work)

https://github.com/innoai-tech/nodekit/tree/main/nodedevpkg/bunpublish (published https://github.com/orgs/innoai-tech/packages/npm/package/bunpublish)

reuse `install.registry.token`, but may `publish.registry.token` in future

**Comment by morlay** [comment]
split as single package https://github.com/morlay/bunpublish

**Comment by ewmb7701** [comment]
If/ when this gets implemented, it would be awesome if `publishConfig` respected `main` [like Yarn does](https://yarnpkg.com/configuration/manifest#publishConfig).

My use case is changing the `main` property from ./src/index.ts during development to ./out/index.js at publish time. This way I can use [internal packages](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages) in development, but also publish them as external packages.

**Comment by morlay** [comment]
@vveisard may consider to use export condition instead.

```json
"exports": {
    "bun": "./src/index.ts",
    "import": "./out/index.js"
}
```

Realword example: https://github.com/innoai-tech/nodekit/blob/main/nodepkg/config/package.json#L21-L43
which support nodejs too.

**Comment by FHU-yezi** [comment]
Any update for this?

**Comment by jedisct1** [comment]
> Any update for this?

Here's where discussions and updates relevant to that issue are posted: https://github.com/oven-sh/bun/issues/1976

**Comment by sv2dev** [comment]
Running into this because the simple workaround to use npm for publishing does not easily work with bun workspaces.
If the `publish` command is not implemented, it would be nice to be able to reference packages in a workspace without the `workspace:` prefix, such that npm can process it.

**Comment by lishaduck** [comment]
> Since I would like to use only bun without installing node at all. I would also like to have a way to publish my packages

You can run `bun install -g npm` to get npm without node, but npm (should) need node. You can run `bunx --bun npm` to run npm with bun. Both work on my machine, though I have both node and bun so it's hard to tell if they're working as intended.

**Comment by eliot-akira** [comment]
Using `bunx --bun npm` is a great idea to run `npm` without Node.js. That should enable publishing npm packages entirely with Bun, solving these related issues.

- #1976
- #6034

When I first ran `bunx --bun npm`, it was running an existing installation of `npm` from Node.js. Specifying `npm@latest` downloaded it to `/tmp` and ran with Bun for sure.

So it should be possible to publish to npm registry with the following command. I tried with `--dry-run` option and it looks to be working correctly.

```sh
bunx --bun npm@latest publish
```

**Comment by Jarred-Sumner** [comment]
@dylan-conway is working on it this week

**Comment by MunMunMiao** [comment]
> workspace:

Hope that I can replace `workspace:*` when it's published.

**Comment by aryzing** [comment]
Great to hear that an implementation is underway. Would be great if the publish command could be made to work off of CLI arguments & env vars without needing any config files like `.npmrc` (which is currently necessary when using auth tokens).

Currently, when using a bun-only workflow, an `.npmrc` [is still needed](https://github.com/secretkeylabs/stacks-tools/tree/main/.github/workflows) just for the auth token. Would be great to rely on the CLI alone.

**Comment by Jarred-Sumner** [comment]
`bun publish` will ship as part of the Bun v1.1.30 release, thanks to @dylan-conway

**Comment by baptisteArno** [comment]
> `bun publish` will ship as part of the Bun v1.1.30 release, thanks to [@dylan-conway](https://github.com/dylan-conway)

When will it be released?

**Comment by Jarred-Sumner** [comment]
tonight or tomorrow
