### ISSUE TITLE
After `bun install`, package.json has weird formatting

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#1980]
Before
```json
{
  "dependencies": {},
}
```

After
```json
{
  "dependencies": { "@actions/core": "^1.10.0" },
}
```

It should look like this instead:
```json
{
  "dependencies": {
    "@actions/core": "^1.10.0"
  },
}
```

**Comment by Jarred-Sumner** [comment]
Let's not prioritize this for awhile

**Comment by R4R3-M37** [comment]
any news? Tabs auto convert to 2 spaces

**Comment by orbiteleven** [comment]
Yeah this is actually quite annoying; if I have Prettier set to tabs but use `bun add|install` via the command line, it'll convert my tabs to spaces, requiring a re-format of `package.json`. It's trivial, but not very ergonomic.
