### ISSUE TITLE
Implement `querystring.escape` and `querystring.unescape`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#1983]
### What is the problem this feature would solve?

These are the only missing bits of functionality from a complete implementation of `node:querystring`

### What is the feature you are proposing to solve the problem?

Full compat  `node:querystring`

**Comment by gaurishhs** [comment]
Bumping `querystring-es3` to 1.0.0-0 should fix this issue 

https://github.com/SpainTrain/querystring-es3
