### ISSUE TITLE
Files in folders with special characters fail to execute

### ISSUE THREAD

**Issue by TibixDev** [oven-sh/bun#1986]
### What version of Bun is running?

0.5.4

### What platform is your computer?

Linux 6.1.8-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Make a folder anywhere called "Fájlok" (`mkdir Fájlok`)
2. Make a file in it called `app.js` (`touch app.js`)
3. Try to run it with Bun. (`bun app.js`)

### What is the expected behavior?

The JS file runs as expected.

### What do you see instead?

`error: FileNotFound reading "/home/user/Desktop/FÃ¡jlok/app.js"`

**Comment by Electroid** [comment]
We fixed this a while ago.

```
❯ bun Fájlok/index.js
hi
```
