### ISSUE TITLE
Update cli to match the Create Next.js app steps as they do not start a dev server

### ISSUE THREAD

**Issue by eswr** [oven-sh/bun#200]
### Issue:
The current steps for [creating a demo next.js app](https://github.com/Jarred-Sumner/bun#using-bun-with-nextjs) can confuse many first time users as the last step makes many assume that running bun would also start a dev server (as the terminal output shows a link to localhost:3000) and one can just navigate to localhost:3000 to view the running application.

This is not the case. I got confused because of this as well and thought of reporting a bug regarding the 404 error I was later seeing on navigating to localhost:3000:

```
404 GET / as application/octet-stream
```

### Proposed solution:
refer: 
On top of the previous update (#183), I want to change the cli comment to reflect the same.

**Comment by Jarred-Sumner** [comment]
Thank you. It originally let you just run `bun`, but that changed for reasons I don't remember at the moment
