### ISSUE TITLE
reflect-metadata - unable to get design:type

### ISSUE THREAD

**Issue by soya-miruku** [oven-sh/bun#2002]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Fedora 37

### What steps can reproduce the bug?

Install reflect-metadata package
create any decorator
call the function 
`let type = Reflect.getMetadata('design:type', target, key);`

### What is the expected behavior?

When calling the function we should get the type result, but instead i get undefined

### What do you see instead?

undefined

### Additional information

I am new to bun, so i still have a ways to go in terms of fully understanding it, but i have tested this on several versions as well as on tsc/ts-node

**Comment by Jarred-Sumner** [comment]
Bun doesn't implement the type metadata for TypeScript decorators, but does implement the rest of TypeScript decorators.

Unfortunately this isn't something we are planning to support as it is very difficult to do without running `tsc` which would significantly slow down bun's start time

**Comment by soya-miruku** [comment]
Thanks for the quick response @Jarred-Sumner 
I know this is closed but just got one more question, again probably an ignorance on my part on how bun works, but could we use custom typescript transformers or change it via a configuration option?

If not what would you recommend to do instead as a work around

Thanks!
