### ISSUE TITLE
SQLite not null text column causes "Illegal instruction" error

### ISSUE THREAD

**Issue by chrisdavies** [oven-sh/bun#2007]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 6.1.9-200.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

Place this in a file `foo.ts` and then `bun run ./foo.ts`:

```ts
import { Database } from 'bun:sqlite';
const db = new Database('app.db');

db.exec(`
  create table if not exists foos (
    name text not null unique
  )
`);
console.log('inserting...');
db.exec(`insert into foos (name) values ('foo')`);
console.log('inserted...');
```

Note: if you remove the `not null unique` constraint, it works. But adding either of those constraints causes it to fail. The queries work fine in my local `sqlite3` which is version `3.40.0`, so it seems it's something to do with the way sqlite was built for Bun. This sequence of queries worked before bun 0.5.

### What is the expected behavior?

The insert should work.

### What do you see instead?

Illegal instruction (core dumped).

In a more complex configuration, I was seeing this:

```
error: script "migrate" exited with code 4 (SIGILL)
```

**Comment by chrisAXZA** [comment]
Related to #1756, since different table properties (UNIQUE, NOT NULL, CHECK, FOREIGN KEY) in initial `CREATE`, as well as their various combinations, trigger "Illegal instruction" ?

> if you remove the not null unique constraint, it works.

**Comment by Jarred-Sumner** [comment]
Please upgrade to the canary build of Bun
