### ISSUE TITLE
New Docker images "MissingPackageJSON"

### ISSUE THREAD

**Issue by mattlgroff** [oven-sh/bun#2008]
### How did you attempt to install or upgrade?

Using the new Docker images:
```
FROM oven/bun:0.5
WORKDIR /app
COPY package.json package.json
COPY bun.lockb bun.lockb
RUN bun install
COPY ./src ./src
EXPOSE 3000
ENTRYPOINT ["bun", "src/index.js"]
```

### What do you see instead?

It fails on `bun install` missing package.json, though package.json is in the same directory.
![image](https://user-images.githubusercontent.com/3247978/217349137-7b9a9782-f33e-4a30-a43d-b3c0f717bb0a.png)

You can see in the `ls` command they are in the same directory.

This dockerfile syntax worked on the jarred docker image, but its not on the new ones. I tried 0.5, 0.5.5. and canary

**Comment by Electroid** [comment]
Thanks for reporting, will take a look.
