### ISSUE TITLE
bun inti generated README.md reports wrong version number

### ISSUE THREAD

**Issue by RobViren** [oven-sh/bun#2012]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 6.1.9-x64v3-xanmod1 x86_64 x86_64

### What steps can reproduce the bug?

Install bun
make new folder
run bun int
check readme for version
see that is claims old version

### What is the expected behavior?

I would expect the version in the generated readme to reflect the current version of bun installed

### What do you see instead?

I see the following line
```
This project was created using `bun init` in bun v0.4.5. [Bun](https://bun.sh) is a fast all-in-one JavaScript runtime.
```

**Comment by Jarred-Sumner** [comment]
Thank you
