### ISSUE TITLE
 error: Duplicate dependency: "foo" specified in package.json when using peer and dev dependencies

### ISSUE THREAD

**Issue by evert** [oven-sh/bun#2072]
### What version of Bun is running?

v0.5.6

### What platform is your computer?

Ubuntu   22.04.1   LTS

### What steps can reproduce the bug?

```json
{
  "devDependencies": {
     "@curveball/kernel": "^0.21",
  },
  "peerDependencies": {
     "@curveball/kernel": "^0.21",
  },
}
```

### What is the expected behavior?

Installation should not error

### What do you see instead?

```
error: Duplicate dependency: "@curveball/kernel" specified in package.json
```

### Additional information

We use peerDependencies to make sure users of our libraries install packages. However, we also need to those same dependencies in devDependencies to enable unittests. `npm` does not error with this scenario, current bun does.

**Comment by Electroid** [comment]
This has been fixed and will be available in the next release. You can try it out early using `bun upgrade --canary`.

```ts
bun install v0.5.7 (ef75cd46)
 + @curveball/kernel@0.21.0

 20 packages installed [1142.00ms]
```

**Comment by evert** [comment]
Awesome, thanks!
