### ISSUE TITLE
Support `discord.js`

### ISSUE THREAD

**Issue by ThatOneBro** [oven-sh/bun#2077]
We've long had requests for `discord.js` support. It doesn't seem too far away now that we've got `undici.Agent` and a workaround for the `worker_threads` requirement.

Currently it looks like we need the following to finish support for `discord.js`:
- [x] `undici.request` (tracking in #1987)
- [x] `response.arrayBuffer()` hangs when called more than once (no tracking yet)

**Comment by avasilic** [comment]
Is there any update on 
> response.arrayBuffer() hangs when called more than once (no tracking yet)

**Comment by ThatOneBro** [comment]
@net-tech I think a fix may have just made it into main, I'll check tomorrow and update this issue accordingly

**Comment by ThatOneBro** [comment]
Update: `response.arrayBuffer()` no longer hangs, but when calling the function Bun reports `undefined is not a function` although when `console.log()`ing `response.arrayBuffer` just before calling it, it seems to be defined as the appropriate function. Will take a closer look at this soon.

**Comment by Mw3y** [comment]
I got the same error with the Winston logging library. It looks like it's a general issue.

**Comment by avasilic** [comment]
> Update: `response.arrayBuffer()` no longer hangs, but when calling the function Bun reports `undefined is not a function` although when `console.log()`ing `response.arrayBuffer` just before calling it, it seems to be defined as the appropriate function. Will take a closer look at this soon.

Hey any update on that closer look? Not trying to be a bother, just wondering if there's been any progress.

**Comment by TiranexDev** [comment]
I just want to say I am experiencing the same error
```
68 |   }
69 | 
70 |   async arrayBuffer() {
71 |     this.#consume();
72 | 
73 |     return await this.#response.arrayBuffer();
                    ^
TypeError: undefined is not a function
      at undici:73:17
      at arrayBuffer (undici:71:22)
      at parseResponse (/mnt/c/Users/tiramify/Documents/bunsh/node_modules/.pnpm/@discordjs+rest@1.7.0/node_modules/@discordjs/rest/dist/index.js:493:29)```

**Comment by ThatOneBro** [comment]
Gonna check on this one later today. There was an issue in our fetch implementation that was causing this but I think it might have been merged into canary already.

**Comment by GillHoang** [comment]
> Gonna check on this one later today. There was an issue in our fetch implementation that was causing this but I think it might have been merged into canary already.

i can't use bun for discord.js when update to latest bun build
![image](https://user-images.githubusercontent.com/89916615/230069583-9ded8f9e-2714-4ddc-b1a8-83e760ff2ec4.png)

**Comment by v3nntrnx** [comment]
> i can't use bun for discord.js when update to latest bun build

Same: (token is there, it's just invisible cuz of my blur)

![Screenshot 2023-04-05 140109](https://user-images.githubusercontent.com/94789999/230074720-5ffa657a-3ed3-4cf4-b6a7-80b2a1bb89ae.png)

**Comment by GillHoang** [comment]
> > i can't use bun for discord.js when update to latest bun build
> 
> Same: (token is there, it's just invisible cuz of my blur)
> 
> ![Screenshot 2023-04-05 140109](https://user-images.githubusercontent.com/94789999/230074720-5ffa657a-3ed3-4cf4-b6a7-80b2a1bb89ae.png)

just wait util have new update, .-. i very want to use bun intead of tsc and run

**Comment by redraskal** [comment]
> I just want to say I am experiencing the same issue
> 
> bun version: 0.5.8 discord.js version: 14.9.0
> 
> ```
> 68 |   }
> 69 | 
> 70 |   async arrayBuffer() {
> 71 |     this.#consume();
> 72 | 
> 73 |     return await this.#response.arrayBuffer();
>                     ^
> TypeError: undefined is not a function
>       at undici:73:17
>       at arrayBuffer (undici:71:22)
>       at parseResponse (/mnt/c/Users/tiramify/Documents/bunsh/node_modules/.pnpm/@discordjs+rest@1.7.0/node_modules/@discordjs/rest/dist/index.js:493:29
> ```

`res.headers['content-type']` returns undefined (I think you have to use `res.headers.get("content-type")` with Bun?), so res.body.json() is never called.

```js
export async function parseResponse(res: Dispatcher.ResponseData): Promise<unknown> {
	const header = parseHeader(res.headers['content-type']);
	if (header?.startsWith('application/json')) {
		return res.body.json();
	}

	return res.body.arrayBuffer();
}
```
https://github.com/discordjs/discord.js/blob/f27631175a97b8a7620efedc24073fdb944cb728/packages/rest/src/lib/utils/utils.ts#L64

**Comment by v3nntrnx** [comment]
Now it managed to succeed, after I downloaded @discordjs/rest package and replace the source code in dist/index.js (res.headers.get('content-type') instead of res.headers['content-type']) it managed to go past client.login!

Now the next problem is 

```
612 |     super();
613 |     this.strategy = strategy;
614 |     this.id = id;
615 |   }
616 |   async connect() {
617 |     const promise = this.initialConnectResolved ? Promise.resolve() : (0, import_node_events2.once)(this, "ready" /* Ready */);
                                                                     ^
TypeError: Not enough arguments
      at /home/tiramify/Documents/newbun/node_modules/.pnpm/@discordjs+ws@0.8.2/node_modules/@discordjs/ws/dist/index.js:617:66
      at connect (/home/tiramify/Documents/newbun/node_modules/.pnpm/@discordjs+ws@0.8.2/node_modules/@discordjs/ws/dist/index.js:616:18)
      at /home/tiramify/Documents/newbun/node_modules/.pnpm/@discordjs+ws@0.8.2/node_modules/@discordjs/ws/dist/index.js:1113:20
      at connect (/home/tiramify/Documents/newbun/node_modules/.pnpm/@discordjs+ws@0.8.2/node_modules/@discordjs/ws/dist/index.js:1110:18)
      at /home/tiramify/Documents/newbun/node_modules/.pnpm/@discordjs+ws@0.8.2/node_modules/@discordjs/ws/dist/index.js:1367:10
```
 
 Also I just found more res.headers[''] instead of res.headers.get() in the discord.js rest file, after changing everything I also needed to change 
 
```
   if (header === void 0 || typeof header === "string") {
    return header;
  }
```


  
  to
  
```
    if (header == void 0 || typeof header === "string") {
    return header;
  }
```

because one of the headers returned is equal to null.

it still however returned Promise.resolve error

UPDATE: The error is not in Promise.resolve but rather in import_node_events2.once(this, "ready")

after a bit of trials I found out when you use

import_node_events2.once(this, "ready", {})

it works. But there are still a lot of errors.

**Comment by v3nntrnx** [comment]
After I and some guys on the discord server investigated the issue (we still are) we found out that these versions work:
 
14.9.0: works (normal bun)
14.8.0: works (normal bun)
13.16.0: works (normal bun)
13.14.0: works (normal bun) 

Anything above 14.9.0 doesn't work, Anything below 14.0.0 requires modified

node_modules/discord.js:
    src/rest/APIRequest.js,
    src/util/DataResolver.js,
    src/util/Util.js.

you need to remove the line ``const fetch = require('node-fetch')`` from every file i mentioned above.

For anything above 14.0.0 you should (example below made for 14.9.0)

node_modules/@discordjs/rest/dist/index.js:
change res.headers["(text)"] to res.headers.get("(text)") and maybe on line 453 ``=== void 0`` with just ``== void 0``

I didn't fully test this, but the bot seems to launch.

**Comment by v3nntrnx** [comment]
![image](https://github.com/oven-sh/bun/assets/94789999/bec9d886-c262-43b2-8590-fcead0366b84)
(discord.js version on the picture,14.9.0)

**Comment by paperclover** [comment]
discord.js is working on this branch
![discord_js](https://github.com/oven-sh/bun/assets/24465214/7a212e4a-8f9f-40cd-9406-34e893c99d70)

didn't test every feature of it.

if you're curious why arrayBuffer() was breaking, we were trying to call `.then` on what we thought was a promise but it was actually just the value.

**Comment by GillHoang** [comment]
> discord.js is working on this branch ![discord_js](https://user-images.githubusercontent.com/24465214/242108615-7a212e4a-8f9f-40cd-9406-34e893c99d70.png)
> 
> didn't test every feature of it.
> 
> if you're curious why arrayBuffer() was breaking, we were trying to call `.then` on what we thought was a promise but it was actually just the value.

how you can do that

**Comment by v3nntrnx** [comment]
> how you can do that
> 

It's not out yet, just wait a couple days and upgrade your version of bun.

**Comment by GillHoang** [comment]
> > how you can do that
> 
> It's not out yet, just wait a couple days and upgrade your version of bun.
hmm after i edit something, it works, but when using class Client for extend, i got some error :((

**Comment by v3nntrnx** [comment]
> > > how you can do that
> > 
> > 
> > It's not out yet, just wait a couple days and upgrade your version of bun.
> > hmm after i edit something, it works, but when using class Client for extend, i got some error :((

Do you have discord? It's more comfortable for me to help you there than on GitHub.
Here is a server link in case you do https://discord.gg/bun-876711213126520882

**Comment by GillHoang** [comment]
> > > > how you can do that
> > > 
> > > 
> > > It's not out yet, just wait a couple days and upgrade your version of bun.
> > > hmm after i edit something, it works, but when using class Client for extend, i got some error :((
> 
> Do you have discord? It's more comfortable for me to help you there than on GitHub. Here is a server link in case you do https://discord.gg/bun-876711213126520882

yep i am in bun server, my discord is GillCoder#7005

**Comment by ImLunaHey** [comment]
Still hitting issue with discord.js 😢 

https://github.com/oven-sh/bun/issues/1987
https://github.com/oven-sh/bun/issues/2688#issuecomment-1574908765

**Comment by Jarred-Sumner** [comment]
That stack trace is interesting. It shouldn’t be going to undici through
node_modules and it shouldn’t be going through undici for websockets
either. Hm

**Comment by ImLunaHey** [comment]
@Jarred-Sumner happy to provide more details here or in the discord. Same username there.
