### ISSUE TITLE
Potential NAPI issues for `@prisma/client`

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2078]
### What version of Bun is running?

canary 2023-05-15

### What platform is your computer?

Linux 6.1.11-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

here is my code sample `repro.cjs`. may be nontrivial to setup since you need the `libquery` stuff setup. i got this by running yarn prisma generate with a PostgreSQL setup

i found these issues when trying to brute force `@prisma/client` into functioning, and isolating a critical loading bug to the code block below, which is a bare-bones version of what the prisma client (at least on PostgreSQL) does. i don't understand the node-api much so its blackmagic what is going on.

```ts
async function main() {
  // this depends on your prisma installation
  const library = require('./node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node');

  // this line sometimes throws
  // InvalidArg: "invalid utf-8 sequence of 1 bytes from index 2"
  const engine = new library.QueryEngine(
    {
      datamodel:
        'generator client {\nprovider="prisma-client-js"\n}\ndatasource db{\nprovider="postgresql"\nurl=env("DATABASE_URL")\n}\n',
      logQueries: false,
      ignoreEnvVarErrors: false,
      datasourceOverrides: {},
      logLevel: 'error',
      configDir: '',
      env: {
        // you dont need a db url, it will just throw an error since the connection failed.
        DATABASE_URL:
          process.env.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/postgres'
      }
    },
    () => {}
  );

  // This line always throws
  // InvalidArg: failed to create napi ref
  await engine.connect(JSON.stringify({ traceparent: '00-10-10-00' }));

  console.log('success');
}

main();
```

sometimes the constructor `new library.QueryEngine` fails with the error `InvalidArg: invalid utf-8 sequence of 1 bytes from index [...]`, the index varies

![image](https://user-images.githubusercontent.com/24465214/218960537-cae43f67-42dc-4f50-99ec-24b692fca9c9.png)

if that error does not happen we are greeted with this error on the `.connect()`

![image](https://user-images.githubusercontent.com/24465214/218960756-34066f28-45c8-4cbb-9097-1e5bb0fce8c8.png)

Also, it should be noted for the prisma client to even get to this point, I had to hack my way through a lot of modifications, which will be fixed as soon as `AsyncResource` and `String.raw` are implemented.

**Comment by haouarihk** [comment]
i gave chatgpt file `https://github.com/oven-sh/bun/blob/main/src/napi/napi.zig` from line 30 to 65.
and gave him the error, and asked him for a solution or a potential bug.


![image](https://user-images.githubusercontent.com/57036855/220791120-1fec8ef6-f7fe-45b6-a069-52c835650a5d.png)


i hope it helps, 
(i also see it as a black magic box)

**Comment by Jarred-Sumner** [comment]
fwiw this particular issue is fixed in canary, but there's a real bug somewhere else that occurs in the same code

**Comment by paperclover** [comment]
![image](https://user-images.githubusercontent.com/24465214/221061540-aeaef890-b7fc-4d40-bf1d-df74c94f835b.png)
yeah i can see that. it's getting much farther now than before.

**Comment by paperclover** [comment]
i just want to put an extra note here because the error is really similar to the one in my last image
```ts
import { transform } from "lightningcss";
transform({ code: Buffer.from(''), filename: 'A' });
Bun.spawnSync({ cmd: ['echo', '1'] }); // causes sigsegv
```
![image](https://user-images.githubusercontent.com/24465214/223349056-fa8ec5d8-613b-46c9-95f4-6cf8167fb9e3.png)

Maybe this is related, maybe this case is useful to know about as well. idk. logging it here just in case.

**Comment by Jarred-Sumner** [comment]
Fixed by @cirospaciari in https://github.com/oven-sh/bun/pull/3176
