### ISSUE TITLE
Implement `tty.WriteStream`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2081]
Some of [`tty.WriteStream`](https://nodejs.org/api/tty.html#class-ttywritestream) may already be implemented, but there are some missing pieces.

```ts
4 | const settings_1 = require("./settings");
5 | function termwidth(stream) {
6 |     if (!stream.isTTY) {
7 |         return 80;
8 |     }
9 |     const width = stream.getWindowSize()[0];
                      ^
TypeError: stream.getWindowSize is not a function. (In 'stream.getWindowSize()', 'stream.getWindowSize' is undefined)
      at termwidth (/node_modules/@oclif/core/lib/screen.js:9:18)
      at /node_modules/@oclif/core/lib/screen.js:19:34
```

This blocks the [`oclif`](https://oclif.io/) CLI parser from working.

**Comment by ThatOneBro** [comment]
Some related issues: 
* #1787
* #1774 
* #2040 possibly

**Comment by ThatOneBro** [comment]
I think this will be easy to do once I finish setting the framework up around TTY stuff in #2025

**Comment by Electroid** [comment]
Also, if someone wants to use `oclif`, here's a temporary workaround:

```ts
// HACK: https://github.com/oven-sh/bun/issues/2081
process.stdout.getWindowSize = () => [80, 80];
process.stderr.getWindowSize = () => [80, 80];

import { Command, Flags } from "@oclif/core";
// ...
```

Of course, we will fix this in Bun so you don't need to do this.

**Comment by CyriacBr** [comment]
FWIW this breaks many packages such as https://www.npmjs.com/package/clipanion sadly.

**Comment by vjpr** [comment]
> FWIW this breaks many packages such as https://www.npmjs.com/package/clipanion sadly.

Workaround: 

```
require('tty').WriteStream.prototype = {}
```
