### ISSUE TITLE
Bun install with scoped imports 

### ISSUE THREAD

**Issue by bradens** [oven-sh/bun#209]
Hey, bun looks great so far. I just wanted to test with an internal github repo to my organization, and it segfaults when doing a `bun install`. 

Here's a repro repository: https://github.com/bradens/bun-test (redacted my org name and token obviously) 

Just running `bun install` or `bun add` causes a segfault.

**Comment by programVeins** [comment]
+1 This is probably the only thing stopping me from installing / running my project 🥲

**Comment by FinnRG** [comment]
Duplicate of #190. Please close this issue.

**Comment by bradens** [comment]
> Duplicate of #190. Please close this issue.

Done, sorry for the duplicate.
