### ISSUE TITLE
Wrong links to source files on the home page

### ISSUE THREAD

**Issue by eliseumds** [oven-sh/bun#210]
<img width="414" alt="Screen Shot 2022-07-05 at 19 09 46" src="https://user-images.githubusercontent.com/640840/177425724-f6a36f86-e6f0-4fe7-80ad-547c36b3c6c8.png">

 Node's example file here is pointing to Deno's and vice-versa. I couldn't find out how to edit it on GitHub.

**Comment by ntnyq** [comment]
https://github.com/Jarred-Sumner/bun/blob/main/packages/bun-landing/page.tsx

**Comment by eliseumds** [comment]
Fixed by https://github.com/Jarred-Sumner/bun/commit/72184748d87af6e645e2f85a69bb0cfcc6b31ad7
