### ISSUE TITLE
createContext is undefined

### ISSUE THREAD

**Issue by caramboleyo** [oven-sh/bun#2105]
### What version of Bun is running?

0.5.6

### What platform is your computer?

Linux 5.15.0-60-generic x86_64 x86_64

### What steps can reproduce the bug?

index.js:
```javascript
import { runInContext, createContext } from 'vm';

const context = createContext({
	key1: 'value1',
});
```
bun run index.js

### What is the expected behavior?

create a context

### What do you see instead?

``` 
3 | const context = createContext({
                    ^
TypeError: createContext is not a function. (In 'createContext({
  session: "ldaf\xE4\xF6lsd\xF6f\xF6sd"
})', 'createContext' is undefined)
      at /root/www/bun/base1/index.js:3:16
```

### Additional information

Without separate contexts javascript in unusable on the server side, major problem of deno. You would have to pass around a context object in every function. Also if that function does not exist, shouldn't the import already fail?

**Comment by Electroid** [comment]
Yes, we need to implement support for the `vm` module, which we are tracking here: #401

**Comment by caramboleyo** [comment]
ah, ok
i was under the impression all node core modules are supported (otherwise you could not rely on npm packages)
