### ISSUE TITLE
`require.main` !== module (node compat)

### ISSUE THREAD

**Issue by AgentEnder** [oven-sh/bun#2107]
### What version of Bun is running?

0.5.6

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Try to run this script w/ bun:

```javascript
if (require.main === module) {
	console.log('Running as main')
} else {
    console.log('required by other module')
}
```

### What is the expected behavior?

The first statement is logged

### What do you see instead?

The second statement is logged

### Additional information

This was found when testing compatibility with [Nx encapsulated installs](https://nx.dev/more-concepts/encapsulated-nx-and-the-wrapper), as an experiment to see if bun could run Nx well. So far, this and #401 are two "blockers" that I've found.

**Comment by Jarred-Sumner** [comment]
In the current implementation of `require`, this wouldn't work (CJS modules share the same runtime code as in browsers, which would be one of the things that need to change to support this)

**Comment by AgentEnder** [comment]
Could it be something that is changed when transpiling to the web-compatible format? 

In that format would import.meta.url work?

E.g. https://stackoverflow.com/questions/57838022/detect-whether-es-module-is-run-from-command-line-in-node

**Comment by birkskyum** [comment]
Working now:

```sh
➜ bun --bun index.ts
Running as main
```
