### ISSUE TITLE
Add "bunr" shortcut to "bun run", similar to "bunx"

### ISSUE THREAD

**Issue by pepper-lees** [oven-sh/bun#2116]
### What is the problem this feature would solve?

Some folks may be used to package managers like Yarn, which has the shortcut `yarn <script>` to run scripts in package.json; which is an equivalent to `yarn run <script>` / `npm run <script>`, as long as said command isn't one of Yarn's built-in commands. It would be helpful to have a shortcut to `bun run` which has the same behavior.

### What is the feature you are proposing to solve the problem?

Similar to how `bunx` is simply a symlink to `bun`, and I assume Bun internally uses `argv` to determine whether `bun` or `bunx` is being executed, I believe we would benefit from an additional shortcut, `bunr`.

There's definitely some overlap between `bunx` and `bun run`, but to my understanding `bunx` does *not* execute scripts from package.json while `bun run` does. That's where `bunr` can step in. It's faster to type (and if you use it in package.json scripts, it'd result in less lengthy scripts).

### What alternatives have you considered?

Individuals could probably create a command-line alias that serves the same purpose, but then we wouldn't be able to put that in package.json scripts.

**Comment by pepper-lees** [comment]
Alternative command alias idea: `brun`

**Comment by Electroid** [comment]
You can run scripts in Bun using just `bun <script>`. The only exception is where there is a reserved Bun command, like `bun build`, where you would need to run `bun run`. While we could add an alias, we want to keep things simple.

**Comment by pepper-lees** [comment]
> You can run scripts in Bun using just `bun <script>`. The only exception is where there is a reserved Bun command, like `bun build`, where you would need to run `bun run`. While we could add an alias, we want to keep things simple.

Nice, thanks! I guess this must have been added since after I wrote the post.
