### ISSUE TITLE
Bun.readFile => File reading with Chinese path and name is not supported

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#2123]
### What version of Bun is running?

0.5.7

### What platform is your computer?

windows11 wsl2 debian

### What steps can reproduce the bug?

中文名称.txt
```
随便一些内容 random content
```

bun run run.js
```js
const path = "./中文路径/中文名称.txt";
console.log(Bun.readFile(path));
```

error:
![image](https://user-images.githubusercontent.com/121753618/220505048-4664b0fc-ee3f-483e-968f-94ce8037cf3a.png)

**Comment by Jarred-Sumner** [comment]
Bun.readFile is not an api in bun

You want

Bun.file(path).text()
