### ISSUE TITLE
Promisified exec from child_spawn different from Node

### ISSUE THREAD

**Issue by coyotte508** [oven-sh/bun#2127]
### What version of Bun is running?

0.5.6

### What platform is your computer?

docker Linux 6.0.12-76060006-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
import { exec } from "node:child_process";
import { promisify } from "node:util";

const __exec = promisify(exec);

console.log(await __exec("echo hi"));
```

### What is the expected behavior?

```
{ stdout: 'hi\n', stderr: '' }
```

### What do you see instead?

```
hi

```

### Additional information

The bun implementation of `exec` probably doesn't use the `util.promisify.custom` symbol: https://nodejs.org/api/util.html#custom-promisified-functions

**Comment by ThatOneBro** [comment]
Thank you for reporting this, we'll have that fixed as soon as #2128 is merged

**Comment by coyotte508** [comment]
Thanks for being so reactive @ThatOneBro !

Was psyching myself up to get in the codebase in a few days :)

**Comment by ThatOneBro** [comment]
Sure thing! Feel free to take a look at some of the other issues labeled `node.js` if you feel motivated to get involved on the JS front! We greatly appreciate any contributions from the community
