### ISSUE TITLE
Alias `bun uninstall` to `bun remove`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2137]
`bun uninstall` = `bun remove`

**Comment by Electroid** [comment]
Done in https://github.com/oven-sh/bun/commit/9024125d41751895496048e30e3fdc30019ef4ad

**Comment by plutoniumm** [comment]
hey it seems this can go one step more & we'll have full compatibility with npm
`bun un` can also be same as `npm un` with just another alias
