### ISSUE TITLE
Website UI seems outdated of main branch: How do I work locally on the latest bun website? Main branch's fixture.html seems outdated

### ISSUE THREAD

**Issue by abhiram11** [oven-sh/bun#2140]
Hi, I am creating a new issue based on the discussion opened recently by me as well.

### Discussed in https://github.com/oven-sh/bun/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **abhiram11** February 23, 2023</sup>
Hi all,

I was trying and testing the frontend of the `bun.sh` website where I found a bug in the UI of the page. I thought of creating a new issue for it but thought of working on the code to see if I can solve it as well (it is a minor bug). But the git clone of the _main_ branch of this repository seems to contain outdated code.

E.g. Bun install shows `0.2.1` version on `fixture.html`, but the current official website shows `0.5.6` along with various updated UI.

Where do I find the latest code base for the `bun.sh` website? Or is it not open-source anymore? 😟

Thanks in advance!</div>

P.S.: I have tried reproducing the dev environment container in Windows and Linux, and the issue still exists.

**Comment by Electroid** [comment]
Hey there! We've been in the process of redoing the website, specifically working on documentation. It's _really_ close, so the changes will be here, in this repository, in a few days.

**Comment by abhiram11** [comment]
Thanks for the update, I'll be waiting for the new website!!
Wish you the best!
