### ISSUE TITLE
Website and docs should say Bun is NOT SUPPORTED on OSX 10.xx

### ISSUE THREAD

**Issue by jq170727** [oven-sh/bun#2154]
### What is the type of issue?

Example code is not working

### What is the issue?

It seems for the past several months https://github.com/oven-sh/bun/issues/1266 prevents Bun from working on OSX 10.xx
yet neither the website or docs mention this.  

I'm on OSX 10.15 with no plans to upgrade anytime soon, so I wasted a half hour trying it out and writing up my experience.  
For the benefit of others here are my notes:

---

## Visit https://bun.sh

> Install Bun v0.5.7
> curl -fsSL https://bun.sh/install | bash
> Supported on macOS, Linux, and WSL

## Bun sounds great let's give it a try!

* download bun from https://bun.sh/install
* inspect bun-install.sh, then run it
    
      % sh bun-install.sh
    
* fix up "~/.zshrc" 

## Visit https://bun.sh/docs/quickstart
    
      % mkdir bun-quickstart
      % cd bun-quickstart
      % bun init
        bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit
        
        package name (bun-quickstart): 
        entry point (index.ts): 
        
        Done! A package.json file was saved in the current directory.
         + index.ts
         + .gitignore
         + tsconfig.json (for editor auto-complete)
         + README.md
        
        To get started, run:
          bun run index.ts
    
      % bun index.ts
        dyld: lazy symbol binding failed: Symbol not found: _pthread_self_is_exiting_np
          Referenced from: /Users/jq170727/.bun/bin/bun (which was built for Mac OS X 11.0)
          Expected in: /usr/lib/libSystem.B.dylib
        
        dyld: Symbol not found: _pthread_self_is_exiting_np
          Referenced from: /Users/jq170727/.bun/bin/bun (which was built for Mac OS X 11.0)
          Expected in: /usr/lib/libSystem.B.dylib
        
        zsh: killed     bun index.ts
    
    
Not good.  Perhaps installer gave me the wrong binary?

## Visit https://bun.sh/docs/installation

> Bun ships as a single executable that can be installed a few different ways.
> 
> Windows users — Bun does not currently provide a native Windows
> build. We're working on this; progress can be tracked at this
> issue. In the meantime, use one of the installation methods below
> for Windows Subsystem for Linux.
> 
> Linux users — Kernel version 5.6 or higher is strongly recommended, but the minimum is 5.1.

## Let's try the brew tap
    
Let's try the brew tap
    
      % brew tap oven-sh/bun
        ==> Tapping oven-sh/bun
        Cloning into '/usr/local/Homebrew/Library/Taps/oven-sh/homebrew-bun'...
        remote: Enumerating objects: 116, done.        
        remote: Counting objects: 100% (116/116), done.        
        remote: Compressing objects: 100% (71/71), done.        
        remote: Total 116 (delta 72), reused 73 (delta 34), pack-reused 0        
        Receiving objects: 100% (116/116), 22.51 KiB | 120.00 KiB/s, done.
        Resolving deltas: 100% (72/72), done.
        Tapped 22 formulae (37 files, 83.4KB).
    
      % brew install bun
        ...
        ==> Summary
        🍺  /usr/local/Cellar/bun/0.5.7: 7 files, 54.7MB, built in 4 seconds
           
      % bun index.ts
        dyld: lazy symbol binding failed: Symbol not found: _pthread_self_is_exiting_np
          Referenced from: /usr/local/bin/bun (which was built for Mac OS X 11.0)
          Expected in: /usr/lib/libSystem.B.dylib
        
        dyld: Symbol not found: _pthread_self_is_exiting_np
          Referenced from: /usr/local/bin/bun (which was built for Mac OS X 11.0)
          Expected in: /usr/lib/libSystem.B.dylib
        
        zsh: killed     bun index.ts
    
## Search issues on GitHub
Discover https://github.com/oven-sh/bun/issues/1266
    
> webkit has dropped support for their memory allocator on macOS 10.xx as of the most recent webkit upgrade

> Due to webkit issues, bun is so far running only on Mac OS 11.x.x versions and above.

      % uname -a
        Darwin xxxxxx.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; ...
        root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
    
      % sw_vers
        ProductName:	Mac OS X
        ProductVersion:	10.15.7
        BuildVersion:	19H15

## Looks like bun is not for me :-(
    
      % brew uninstall bun
        Uninstalling /usr/local/Cellar/bun/0.5.7... (7 files, 54.7MB)

      % rm -rf ~/.bun

### Where did you find it?

No mention of limitation in either of these places:

## Visit https://bun.sh

> Install Bun v0.5.7
> curl -fsSL https://bun.sh/install | bash
> Supported on macOS, Linux, and WSL

## Visit https://bun.sh/docs/installation

> Bun ships as a single executable that can be installed a few different ways.
> 
> Windows users — Bun does not currently provide a native Windows
> build. We're working on this; progress can be tracked at this
> issue. In the meantime, use one of the installation methods below
> for Windows Subsystem for Linux.
> 
> Linux users — Kernel version 5.6 or higher is strongly recommended, but the minimum is 5.1.

**Comment by Electroid** [comment]
Thanks, we'll add a section about the incompatibility. Also will see if we can revisit OS X support

**Comment by jq170727** [comment]
install.sh could also check `sw_vers` on OSX as well

**Comment by jq170727** [comment]
Confirmed bun 0.5.8 quickstart worked for me on OSX 10.15.7

    % mkdir bun-quickstart
    % cd bun-quickstart 
  
    % bun init
      bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit
      
      package name (bun-quickstart): 
      entry point (index.ts): 
      
      Done! A package.json file was saved in the current directory.
       + index.ts
       + .gitignore
       + tsconfig.json (for editor auto-complete)
       + README.md
      
      To get started, run:
        bun run index.ts
  
    % bun run index.ts
      Hello via Bun!
  
    % bun --version 
      0.5.8
      
    % sw_vers
      ProductName:    Mac OS X
      ProductVersion: 10.15.7
      BuildVersion:   19H15
