### ISSUE TITLE
Investigate EventEmitter 20% perf regression

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2169]
Looks like Bun 0.5.7 is 20% slower at emitting events compared to Bun 0.5.5

Bench: https://github.com/oven-sh/bun/blob/main/bench/snippets/emitter.js

<img width="846" alt="image" src="https://user-images.githubusercontent.com/709451/221327697-e4cdd3b2-2a5a-4416-bcfe-78ac2d331909.png">

**Comment by ThatOneBro** [comment]
🤔 That's odd. I'm curious what happened here. That means we're probably a lot slower than we should be on a lot of our Node builtins

**Comment by Jarred-Sumner** [comment]
Performance regression to `.emit` is fixed in canary, due to a handful of things. The overall performance of EventEmitter is not good though. It should be faster than EventEmitter3, at least. 

Currently, the floor for native callback into JS seems to be 29ns on an M1. So we can't have a faster EventEmitter wihtout writing it in JS

<img width="796" alt="image" src="https://user-images.githubusercontent.com/709451/221391003-fcc2e54f-4508-42ee-8ede-abaa1abe87a5.png">
