### ISSUE TITLE
`bun install` using `workspaces`

### ISSUE THREAD

**Issue by antooni** [oven-sh/bun#2180]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

git clone git@github.com:l2beat/l2beat.git
cd l2beat
bun install

### What is the expected behavior?

deps are installed correctly

### What do you see instead?

bun install
bun install v0.5.7 (5929daee)

error: Workspace not found "packages/*" in "/Users/antooni/repos/quickstart/l2beat"

      "packages/*"
      ^
/Users/antooni/repos/quickstart/l2beat/package.json:11:7 172

**Comment by Electroid** [comment]
Hey there, thanks for reporting this issue! We have not yet implemented glob support in workspaces, which is why this error is occurring, but we will be adding it soon. #1918

In the meantime, a workaround is to manually list all your workspaces, e.g.
```json
{
  "packages": [
    "package-a",
    "package-b"
  ]
}
```

**Comment by Electroid** [comment]
`packages/*` is supported as of Bun 0.5.8. Glob support, more generally, will be tracked in #1918

**Comment by antooni** [comment]
Thank you <3
