### ISSUE TITLE
`bun dev` imports from the wrong URL

### ISSUE THREAD

**Issue by pfgithub** [oven-sh/bun#2186]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.79.1-microsoft-standard-WSL2 x86_64 unknown / Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

a.ts:
```ts
console.log("loaded");
```

a.html:
```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <script src="./a.js"></script>
    </body>
</html>
```

run two bun dev servers:
```
# server 3000:
bun dev
# server 3001, in another terminal:
bun dev
# now, kill the 3000 server
```

navigate to `http://localhost:3001/a.html`

notice that bun tries to import files from `http://localhost:3000`, and fails

```
import {
__HMRClient as Bun
} from "http://localhost:3000/bun:wrap";
Bun.activate(false);
import {
__HMRModule as HMR
} from "http://localhost:3000/bun:wrap";
```

### What is the expected behavior?

Bun should either:
- generate import statements based on the request origin. eg:
  ```ts
  import {
    __HMRClient as Bun
  } from "http://localhost:3001/bun:wrap";
  // or http://172.22.234.120:3000/bun:wrap from an ip address
  ```
- or generate absolute paths in import statements. eg:
  ```ts
  import {
    __HMRClient as Bun
  } from "/bun:wrap";
  ```

### What do you see instead?

bun generates an import statement to a dead link:

```ts
import {
  __HMRClient as Bun
} from "http://localhost:3000/bun:wrap";
```

### Additional information

Workaround: `bun dev --origin "http://172.22.234.120:3000`, or your origin

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
