### ISSUE TITLE
[0.5.8] Bun install segfault on Ubuntu (was working)

### ISSUE THREAD

**Issue by asilvas** [oven-sh/bun#2196]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 5.19.0-31-generic x86_64 x86_64

### What steps can reproduce the bug?

Originally thought it was a dependency conflict with the latest bun, but was able to remove all dependencies and repro with basically an empty package.json:

```
{
  "name": "t",
  "version": "1.0.0",
  "description": "",
  "scripts": {
  },
  "author": "",
  "dependencies": {
  }
}
```

`bun i`

### What is the expected behavior?

Installs

### What do you see instead?

```
Segmentation fault (core dumped)
```

### Additional information

Here's the view from `gdb`:

```
gdb bun
(gdb) r i
Starting program: /home/myUser/.bun/bin/bun i
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7bff6c0 (LWP 10173)]

Thread 2 "HTTP Client" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7bff6c0 (LWP 10173)]
0x0000555557dddb09 in ?? ()
```

**Comment by Jarred-Sumner** [comment]
A bad commit earlier today broke BoringSSL on Linux, you'll need to reinstall and it should work once again in canary after that


`curl https://bun.sh/install | bash`
