### ISSUE TITLE
Improve SEO of docs

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2197]
The SEO for the docs isn't very good right now. We probably will need to manually write descriptions for some pages.

Ideally though, we'd use JSON+LD so that google has high quality search cards that appear

https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data

It would be funny to make some examples literally appear as recipes 

Currently, it looks like this when you google:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/709451/221390608-b351de4e-1708-47a5-b27c-29b66f978a2c.png">

**Comment by xhyrom** [comment]
Good idea, also some FAQ would be great

And we should take a look here: https://pagespeed.web.dev/report?url=https%3A%2F%2Fbun.sh%2Fdocs&form_factor=desktop
there are issues in SEO, we should fix them

**Comment by simylein** [comment]
It looks like the docs are pretty good now and page speed gives them a 100 in every category. Thank you for improving them 🙂
