### ISSUE TITLE
Bun with socket.io

### ISSUE THREAD

**Issue by N0N1m3** [oven-sh/bun#2199]
### Discussed in https://github.com/oven-sh/bun/discussions/2111

<div type='discussions-op-text'>

<sup>Originally posted by **N0N1m3** February 20, 2023</sup>
Starting with version [4.4.0](https://socket.io/blog/socket-io-4-4-0/), a Socket.IO server can now bind to a [µWebSockets.js](https://github.com/uNetworking/uWebSockets.js) server.

```ts
const { App } = require("uWebSockets.js");
const { Server } = require("socket.io");

const app = new App();
const io = new Server();

io.attachApp(app);

io.on("connection", (socket) => {
  // ...
});

app.listen(3000, (token) => {
  if (!token) {
    console.warn("port already in use");
  }
});
```

As written in the Readme:  **The HTTP server and server-side _websockets_ are based on [uWebSockets](https://github.com/uNetworking/uWebSockets).**

So, is there any way to port this to the capabilities of bun?

P.S. **[Socket.io article](https://socket.io/docs/v4/server-installation/#usage-with-uwebsockets)**</div>

**Comment by darrachequesne** [comment]
@N0N1m3 if I'm not mistaken, bun already uses uWS under the hood, so I don't think there is much to do here.

**Comment by Electroid** [comment]
While Bun uses the `uWebSockets` library, it does not implement the same APIs. It would be interesting if Socket.io's `attachApp` supported Bun's server as an argument. Though, that would be best to ask in their repository.

We do have tests for socket.io, it should work in Bun. If you're still running into issues, please file another issue and we'll investigate.
