### ISSUE TITLE
SegmentationFault at 188 when running `bun add bun-framework-next`

### ISSUE THREAD

**Issue by AlecSchneider** [oven-sh/bun#220]
❯ bun add bun-framework-next

bun add v0.1.1
  🚚 @webassemblyjs/helper-numbers [1217/1282]
SegmentationFault at 188

–––– bun meta ––––
Bun v0.1.1 macOS Silicon 21.5.0
AddCommand:
HTTP: 103
Elapsed: 64499ms | User: 64332ms | Sys: 1743ms
RSS: 0.18GB | Peak: 0.23GB | Commit: 0.62GB | Faults: 249
–––– bun meta ––––

**Comment by AlecSchneider** [comment]
UPDATE:

running again would freeze eventually:
❯ bun add bun-framework-next

bun add v0.1.1
  🚚 path-type [863/864] ^C

  
running a third time did end up working
❯ bun add bun-framework-next

bun add v0.1.1
 + tailwindcss@3.1.4
 + @codesandbox/sandpack-react@1.2.2
 + @next/mdx@12.2.0
 + @trpc/client@9.25.3
 + @trpc/next@9.25.3
 + @trpc/react@9.25.3
 + @trpc/server@9.25.3
 + next-axiom@0.8.1

 installed bun-framework-next@12.1.5


 496 packages installed [9.81s]

**Comment by Jarred-Sumner** [comment]
Should be fixed as of Bun v0.1.12 and possibly earlier
