### ISSUE TITLE
Support for Instantiation Expressions

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#2203]
### What is the problem this feature would solve?

Running Bun parser on modern TS code (added in TS 4.7).

### What is the feature you are proposing to solve the problem?

Bun parser should support instantiation expressions https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#instantiation-expressions

Related commits in esbuild:
- https://github.com/evanw/esbuild/pull/2038/files?w=1
- https://github.com/evanw/esbuild/commit/1a5716883079f944de96ab0cd479d3c8a3980c29
- https://github.com/evanw/esbuild/commit/64a638882562d9af7a4ce5c1dd18f1671a442358

**Comment by Jarred-Sumner** [comment]
yeah we need to fix this

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/2593
