### ISSUE TITLE
Bun.Transpiler fail to parse code with shebang

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#2204]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 x86_64 i386

### What steps can reproduce the bug?

```ts
console.log(
  new Bun.Transpiler({ loader: "ts" }).transformSync(`
#!/usr/bin/env node
console.log("Hello world");
`),
);

```

### What is the expected behavior?

Works

### What do you see instead?

```
error: Syntax Error!!

#!/usr/bin/env node
^
input.ts:2:1 1
```

### Additional information

Even if probably not a common usecase, I ran into this while writing a script that uses `scanImports` on all the files in my codebase, some of which contains shebang.

**Comment by Jarred-Sumner** [comment]
The shebang line has to be at the start, but there is a newline before that

```js
console.log(
  new Bun.Transpiler({ loader: "ts" }).transformSync(`#!/usr/bin/env node
console.log("Hello world");
`),
);

**Comment by ArnaudBarre** [comment]
Oh yeah my bad, mistake when trying to make a small repro.
This works for transformSync and scan, but not scanImports:
```ts
console.log(
  new Bun.Transpiler({ loader: "ts" }).scanImports(`#!/usr/bin/env node
console.log("Hello world");
`),
);
```

**Comment by ArnaudBarre** [comment]
Because it works with scan I think the issue can be a won't fix
