### ISSUE TITLE
Rewrite `EventEmitter` implementation, use JS builtin for `emit`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2207]
An approach that will probably work well:
- `JSMap` in a private property for the underlying storage (probably)
- The class itself should be in C++, but the emit function should be done as a JS builtin
- Use LazyClassStructure instead of the WebCore structure cache. It's faster.
- Experiment with polymorphic value in the JSMap. When one listener and initially created, a `InternalFields(2)` where one value is a function and the other value tracks `once` (or other flags). After more than one listener is added for the first time, make it an Array and keep it an Array subsequently. Making it either the wrapper or an Array only containing wrappers  makes it much simpler to potentially have a C++ implementation of emit (for emitting from native code) as well.  Using `InternalFields(2)` should be good because it's fast for native code to read and it's cheaper than a "real" object
- Verify that JSMap is actually faster than `Object.create(null)`. I believe it should be because JSC has inline caching for Map.get and Map.delete, and it means no structure transitions on add/remove
- Remember that EventEmitter needs to be callable as well as constructable
- Remember that `Process` (and others) need to subclass `EventEmitter`

**Comment by ThatOneBro** [comment]
This is really interesting. I was also thinking about how we could keep `EventEmitter` in native but pull out `emit` into JS, but I didn't have enough context to know if it was feasible. This sounds good

**Comment by Jarred-Sumner** [comment]
@paperdave has done this
