### ISSUE TITLE
`--silent` param not working

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#2209]
### What version of Bun is running?

0.5.8

### What platform is your computer?

macOS

### What steps can reproduce the bug?

```
❯ bun run index.ts --silent
[0.02ms] ".env"
Hello via Bun!
```

Above is after creating some folder, starting it with `bun init`. And adding an empty `.env` file.

### What is the expected behavior?

There should be no `[0.02ms] ".env"` log

### What do you see instead?

See `[0.02ms] ".env"`.

**Comment by Electroid** [comment]
See #2120, this won't be nessecary anymore.
