### ISSUE TITLE
`~/.bunfig.toml` global config is only being read by `bun install` 

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#2210]
### What version of Bun is running?

0.5.8

### What platform is your computer?

macOS

### What steps can reproduce the bug?

Want to have `~/.bunfig.toml ` with this content:

`logLevel = "error"`

Then in some folder on my computer run `bun run index.ts` with `.env` too and there should be no log shown.

### What is the expected behavior?

`~/.bunfig.toml ` gets read by `bun run` at least.

**Comment by Jarred-Sumner** [comment]
This was fixed some time ago
