### ISSUE TITLE
Make `File` a global constructor

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2212]
- `Bun.file("foo") instanceof File` should return true
- For now, `new File(path)` should do the same as `Bun.file("foo")`

Motivating usecase: `formData.get("avatar") instanceof File`

**Comment by matiaslagoevia** [comment]
I'd like to work on this issue if it's still available, thanks!

**Comment by e3dio** [comment]
I am needing this, to detect if File was passed to a function

**Comment by fbaltor** [comment]
If I understand, `File` as a type does not exist yet, right?

**Comment by Ekott2006** [comment]
@matiaslagoevia, @e3dio   Any Updates

**Comment by paperclover** [comment]
This breaks `openai` v4

**Comment by ian-weir** [comment]
I'll take a look at this since it's been a while from when Matias commented
Edit: Might not be a good first issue >.>

**Comment by Jarred-Sumner** [comment]
Fixed in c99a9ba33a36f16f79e38ff77423f5d301f6d2a8
