### ISSUE TITLE
bun bundler segmentation fault

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#2221]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 6.1.12-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

Create empty project, install any library - svelte in this case

Create index.ts
```ts
import * as svelte from "svelte";

// i know this is is not the right syntax
export svelte;
```
run `bun bun index.ts`

### What is the expected behavior?

Error message

### What do you see instead?

segmentation fault

**Comment by jwhear** [comment]
It looks like this is not an issue in the latest canary:
```
❯ bun upgrade --canary
[2.62s] Upgraded.

Welcome to bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/09585c4b24c8cf6ffa3b0c10d98b144bea8b298e...main

❯ took 2s bun run test.js


error: Unexpected svelte

export svelte;
       ^
```

**Comment by jwhear** [comment]
*previous comment deleted because I misread `bun bun` as `bun run`*

This issue is present in current canary build.
