### ISSUE TITLE
Aliasing does not work 

### ISSUE THREAD

**Issue by gaurishhs** [oven-sh/bun#2228]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 21.5.0 x86_64 i386

### What steps can reproduce the bug?

I'm trying to get Preact to work with Bun, I tried aliasing `react/jsx-runtime` and `react/jsx-dev-runtime` with `preact/jsx-runtime` and `preact/jsx-dev-runtime` but those aliases probably don't work and i still get the error of `react/jsx-dev-runtime` not found

## Reproduce: 

```
git clone https://github.com/gaurishhs/preact-bun-template
cd preact-bun-template
bun install
bun src/index.jsx
```

### What is the expected behavior?

Alias should work not giving module not found error for react's jsx runtime

### What do you see instead?

❯ bun src/index.jsx

error: Cannot find module "react/jsx-dev-runtime" from "/Users/gaurish/Desktop/Coding/test/preact-bun-template/src/components/header/index.jsx"

**Comment by Jarred-Sumner** [comment]
Use `jsxImportSource`

https://github.com/oven-sh/bun/blob/main/test/snippets/custom-emotion-jsx/tsconfig.json#L1-L6

**Comment by gaurishhs** [comment]
Ah, thank you!
