### ISSUE TITLE
`Unexpected keyword 'export'` when importing `opentype.js`

### ISSUE THREAD

**Issue by swissspidy** [oven-sh/bun#2233]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```
// index.ts
import { loadSync } from 'opentype.js';

console.log(loadSync);
```

Run `bun index.ts`

### What is the expected behavior?

No syntax error

### What do you see instead?

```
$ bun index.ts 
14454 | 	load: load,
14455 | 	loadSync: loadSync
14456 | });
14457 | 
14458 | export default opentype;
14459 | export { BoundingBox, Font, Glyph, Path, parse as _parse, load, loadSync, parseBuffer as parse };
                                                                                             ^
SyntaxError: Unexpected keyword 'export'
      at /~/.bun/install/cache/opentype.js@1.3.4/dist/opentype.module.js:14459:89
```

### Additional information

Related:

* #1270

**Comment by nzoschke** [comment]
Same problem here. Commenting out the last line in module makes everything work in my use case. I tried some path remapping as a workaround to no success.

**Comment by swissspidy** [comment]
AFAICT this started working at some point, it no longer happens to me
