### ISSUE TITLE
FormData description is (probably) incorrect

### ISSUE THREAD

**Issue by simon-abbott** [oven-sh/bun#2234]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The description of the `FormData` global on the nodejs page says that compatibility was "Added in Bun 0.7.0.", but the latest bun release is only 0.5.7. I think you either have a typo or a time-traveling contributor.

### Where did you find it?

https://bun.sh/docs/ecosystem/nodejs#node_formdata

**Comment by ThatOneBro** [comment]
@simon-abbott Thank you for catching that!
