### ISSUE TITLE
Segfault even when running bun upgrade.

### ISSUE THREAD

**Issue by HaimenToshi** [oven-sh/bun#2235]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 6.1.14-1-lts x86_64 unknown

### What steps can reproduce the bug?

Bun segfaults when Bun.serve() receives a connection, trying to run bun upgrade or bun upgrade --canary also results in a segfault.

relevant dmesg output : 

`HTTP Client[1685797]: segfault at 7efe0fff8218 ip 000055f0ebcc0ac9 sp 00007efe14a9fd28 error 4 in bun[55f0ebcb6000+2f6b000] likely on CPU 6 (core 2, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1685837]: segfault at 7f95d7ff8181 ip 00005570b4a6bac9 sp 00007f95de6bfd28 error 4 in bun[5570b4a61000+2f6b000] likely on CPU 7 (core 3, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1685875]: segfault at 7eff3fff8217 ip 000055a5551e0ac9 sp 00007eff45430d28 error 4 in bun[55a5551d6000+2f6b000] likely on CPU 7 (core 3, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1685957]: segfault at 7f77d7ff819f ip 0000561716e57ac9 sp 00007f77dd9ded28 error 4 in bun[561716e4d000+2f6b000] likely on CPU 2 (core 2, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1686005]: segfault at 7f6667ff81b0 ip 00005650f80a3ac9 sp 00007f666d1fcd28 error 4 in bun[5650f8099000+2f6b000] likely on CPU 6 (core 2, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1688061]: segfault at 7f240fff81f2 ip 0000561a147d0ac9 sp 00007f24159c6d28 error 4 in bun[561a147c6000+2f6b000] likely on CPU 6 (core 2, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
HTTP Client[1688078]: segfault at 7ff10fff8125 ip 0000559573b01ac9 sp 00007ff117662d28 error 4 in bun[559573af7000+2f6b000] likely on CPU 0 (core 0, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce
bun[1688102]: segfault at 5631640085dc ip 00005631604c6ab8 sp 00007ffc6464eeb8 error 4 in bun[5631604bc000+2f6b000] likely on CPU 3 (core 3, socket 0)
Code: ff 90 48 85 ff 74 45 48 89 fa 48 ff cf 48 81 e7 00 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 <8b> 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 f6 81 16 01 00
HTTP Client[1688202]: segfault at 7f55e3ff81c1 ip 00005558fee33ac9 sp 00007f55ec0dfd28 error 4 in bun[5558fee29000+2f6b000] likely on CPU 2 (core 2, socket 0)
Code: 00 00 fe 48 89 d0 48 29 f8 48 c1 e8 10 48 8d 04 80 48 c1 e0 04 48 8d 0c 07 8b 84 07 0c 01 00 00 48 29 c1 48 8d b1 08 01 00 00 <f6> 81 16 01 00 00 02 75 0b 8b 46 1c 85 c0 78 09 c3 31 c0 c3 e9 ce`

### What do you see instead?

[ /srv/bun/ ] bun upgrade --canary
Downloading... Segmentation fault (core dumped)

[ /srv/bun/ ] bun run src/server.js 
Segmentation fault (core dumped)

[ /srv/bun/ ] sudo bun upgrade --canary
Downloading... Segmentation fault

**Comment by Jarred-Sumner** [comment]
The version of bun canary a couple days ago, for about three hours had a broken BoringSSL implementation.

Please reinstall and bun upgrade —canary again

Lmk if this still happens after that
