### ISSUE TITLE
bun gives "illegal hardware instruction" when executing it

### ISSUE THREAD

**Issue by kkuriboh** [oven-sh/bun#224]
OS: Artix Linux
init system: runit
kernel: linux-zen 5.18.6
shell: zsh
terminal: alacritty
processor: Intel Pentium G4560 (4) @ 3.500GHz

```console
[vanilla@banana ~]$ bun
[1]    4950 illegal hardware instruction  bun
```
```console
[vanilla@banana ~]$ bun bun_test.js
[1]    4967 illegal hardware instruction  bun bun_test.js
```

**Comment by codehz** [comment]
I think it is probably a duplicate of https://github.com/Jarred-Sumner/bun/issues/181

**Comment by kkuriboh** [comment]
yea, I think it's, ty

**Comment by zgagnon** [comment]
That repo has been closed. Was there a resolution on this? I'm also running in to it, and this is the first google hit

**Comment by kkuriboh** [comment]
This error basically means "your CPU does not support bun", some hardware acceleration kind of shit, it worked when i bought a newer CPU :rofl:

**Comment by zgagnon** [comment]
Ah, I think its because I'm on Apple Silicon

**Comment by Gianclgar** [comment]
I just got  `[1]    28480 illegal hardware instruction  bun init` ona. freshly installed bun instance.

This is my setup:

Mac Pro 2013 (Trashcan)
3,7 GHz Intel Xeon E5 4 core
macOS Monterey 12.7.6 (21H1320)
