### ISSUE TITLE
GC Issues (followup from HN)

### ISSUE THREAD

**Issue by sroussey** [oven-sh/bun#2243]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Oooh... I have a process that runs for a few hours reading data from disk and then writing it back to sqlite (sometimes reading from sqlite instead -- i have pulled the SEC edgar db down and have it in files and processing it with bun into sqlite so i can get rid of the files some day).

While it runs, it does not have much opportunity to GC -- the sqlite is synchronous and I am using fs synchronously as well. As it iterates, I have it Bun.sleep(1) a bit around the time I update the CLI output (maybe 4 times a second). I have to update the CLI/UI this way since everything is sync. It took a bit for the fact that doing sqlite in loops is never going to let the timeouts update the UI.

### What is the expected behavior?

Should toss data no longer used.

### What do you see instead?

I see all my memory get used, memory pressure get high, and tens of GB in swap.

### Additional information

https://news.ycombinator.com/item?id=34931412#34934714

**Comment by leeoniya** [comment]
maybe related: https://github.com/oven-sh/bun/issues/1824, though that one is mostly async, and has enough breathing room to collect, imo.

**Comment by Jarred-Sumner** [comment]
As a stopgap until we more properly schedule the GC for scenarios like this, in the canary build of Bun you can pass environment variables prefixed with `BUN_JSC_` which allow modifying a lot of the internal options in JSC. Many of these are GC-related

https://github.com/oven-sh/webkit/blob/main/Source/JavaScriptCore/runtime/OptionsList.h

<img width="1930" alt="image" src="https://user-images.githubusercontent.com/709451/222058467-d2f24e01-ff26-4ab0-ac21-e17bc0f856d2.png">

**Comment by Electroid** [comment]
We have made a lot of improvements to Bun's GC since this issue was created. If you're still noticing weird stuff, let us know and we'll investigate again.
