### ISSUE TITLE
Bun.spawnSync is stuck on larger files

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#2245]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 6.1.12-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

```ts
const { stdout } = Bun.spawnSync(["cat", "/boot/vmlinuz-linux"]);
// won't run because it's stuck
console.log(stdout);
```

### What is the expected behavior?

Write the buffer content out

### What do you see instead?

Nothing

**Comment by LowByteFox** [comment]
the specified file is too large, `/etc/services` is smaller but it gets stuck on latest canary build

**Comment by Jarred-Sumner** [comment]
Fixed in canary
