### ISSUE TITLE
Update SQLite version

### ISSUE THREAD

**Issue by Dialga** [oven-sh/bun#2250]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 6.2.1-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

The builtin version of SQLite is 3.38.5.

The latest SQLite release is [Version 3.41.0](https://sqlite.org/releaselog/3_41_0.html) (2023-02-21).

**Comment by ThatOneBro** [comment]
Thank you for the suggestion, we'll consider upgrading soon

**Comment by infrahead** [comment]
Fingers crossed that will get upgraded to 3.42.0 which has great JSON enhancements I'm leveraging, or even the forthcoming 3.43.0

**Comment by Dialga** [comment]
Thanks for upgrading this in #7668!
