### ISSUE TITLE
bun does not follow PromiseResolveThenableJob of the spec

### ISSUE THREAD

**Issue by artalar** [oven-sh/bun#2255]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.63 x86_64 x86_64

### What steps can reproduce the bug?

https://codesandbox.io/p/sandbox/runtime-architecture-pgzmzc

```sh
> cat test.js 
"const promise = Promise.resolve();/
promise.then(() => console.log(1));/
new Promise((resolve) => resolve(promise)).then(() => console.log(3));/
new Promise((resolve) => promise.then(resolve)).then(() => console.log(2));"
> bun test.js
1
3
2
```

### What is the expected behavior?

1
2
3

### What do you see instead?

1
3
2

### Additional information

Browsers and node shows `1, 2, 3`.

According to [the spec](https://262.ecma-international.org/6.0/#sec-promiseresolvethenablejob) the behaviour of passed promise to a resolve function and pass resolve function to "then" of promise is different.

From my personal perspective it isn't obvious and weird, but I assumes an engine should follow the spec.

**Comment by Jarred-Sumner** [comment]
The fix is in reverting my change to PromiseOperations.js in JSC. My change is no longer necessary

**Comment by artalar** [comment]
Sooo, would it be fixed? `bun@1` still has the issue. Safari works as expected.

**Comment by kirill-dev-pro** [comment]
@Jarred-Sumner please revert your fix to PromiseOperations.js in JSC 🙂
