### ISSUE TITLE
util.inspect doesnt format Uint8Array 

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2259]
### What version of Bun is running?

0.5.8 canary

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

```
import { inspect } from 'util';

console.log(inspect(new Uint8Array([1, 2, 3, 4, 5]), false, 10, true));
console.log(new Uint8Array([1, 2, 3, 4, 5]));
```
these lines should print out the same content

### What is the expected behavior?

```
Uint8Array(5) [ 1, 2, 3, 4, 5 ]
Uint8Array(5) [ 1, 2, 3, 4, 5 ]
```

### What do you see instead?

```
{ '0': 1, '1': 2, '2': 3, '3': 4, '4': 5 }
Uint8Array(5) [ 1, 2, 3, 4, 5 ]
```

### Additional information

not sure if any other objects are printed differently from inspect vs log

**Comment by Electroid** [comment]
Since Bun v1.0, this has been fixed.

```
❯ bun inspect.js
Uint8Array(5) [ 1, 2, 3, 4, 5 ]
Uint8Array(5) [ 1, 2, 3, 4, 5 ]
```
