### ISSUE TITLE
This file should not be required, when using bun run .ts flie.

### ISSUE THREAD

**Issue by qlly0630** [oven-sh/bun#2266]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.2.0 x86_64 i386

### What steps can reproduce the bug?

show errors when i try to using `shelljs`:
```bash
1 | if (require.main !== module) {
2 |   throw new Error('This file should not be required');
            ^
error: This file should not be required
```

**Comment by paperclover** [comment]
I think this was fixed.
