### ISSUE TITLE
Support ```npm:``` dependencies

### ISSUE THREAD

**Issue by suienzan** [oven-sh/bun#227]
run `bun add eslint-import-resolver-typescript` get the following error

```sh
bun add v0.1.1


error: No version matching "npm:@unts/get-tsconfig@^4.1.1" found for specifier "get-tsconfig" (but package exists)
```

**Comment by RodrigoRVSN** [comment]
Same issue using bun install

Momentum workaround:

add ` "eslint-import-resolver-typescript": "^2.7.1",` in package.json (or lower) and using `bun install`

**Comment by FinnRG** [comment]
```eslint-import-resolver-typescript``` uses the npm syntax for specifying dependencies. I think bun checks [get-tsconfig](https://www.npmjs.com/package/get-tsconfig) (latest version: 4.1.0), when it should check [@unts/get-tsconfig](https://www.npmjs.com/package/@unts/get-tsconfig) (latest version: 4.1.1).

**Comment by DreierF** [comment]
Same issue with `bun add plotly.js` resulting in 

```
error: No version matching "npm:@plotly/regl@^2.1.2" found for specifier "regl" (but package exists)
```

**Comment by Electroid** [comment]
Thanks for reporting. This is something we are definitely going to implement. (soon!)

**Comment by Jarred-Sumner** [comment]
This was added in Bun v0.5.1
