### ISSUE TITLE
Fix the casing of node:http/https response headers

### ISSUE THREAD

**Issue by mpodwysocki** [oven-sh/bun#2273]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Making a request through the node:http/https stack does not downcase the response headers that Node.js already does.

```javascript
async function sendRequest(url, headers, body, method) {
  const agent = new https.Agent({

  });

  const options = {
    agent,
    hostname: url.hostname,
    path: `${url.pathname}${url.search}`,
    port: url.port,
    method: method,
    headers: headers
  };

  return new Promise((resolve, reject) => {
    const request = https.request(url, options, (response) => {
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };

      response.on("data", (data) => {
        res.body += data;
      });

      response.on("end", () => {
        resolve(res);
      });
    });

    request.on("error", (err) => {
      reject(err);
    });

    request.write(body);
    request.end();
  });
}
```

### What is the expected behavior?

I would expect to be able to get the Tracking ID such as this using the full lower case:

```javascript
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };
```

Which would then print out like the following:

```bash
Tracking ID: efdb6e84-b4d9-4a6c-b8e0-c6823ade8713
```

### What do you see instead?

Bun does not normalize or lower case the headers, therefore, the field is undefined, so instead the field is returned as `TrackingId` and not `trackingid`.

```javascript
      const res = {
        correlationId: response.headers["x-ms-correlation-request-id"],
        trackingId: response.headers["trackingid"],
        statusCode: response.statusCode,
        body: ""
      };
```

Which would then print out like the following:

```bash
Tracking ID: undefined
```

**Comment by ThatOneBro** [comment]
Hey @mpodwysocki, thanks again for reporting your issues trying to get `http/https.request` to work. 

I'm going to look into this and one of the things I'm going to do today/tomorrow is begin porting all of the Node tests for the `http` and `https` packages so we can ensure (at least theoretically) 100% compatibility with `http` and `https` going forward. 

Once we get those tests and and correct any incorrect behavior you should be able to use these packages without any worries. 😉
