### ISSUE TITLE
Support running package.json scripts from package.json without a name

### ISSUE THREAD

**Issue by privatenumber** [oven-sh/bun#229]
## Description
`bun run` fails when the `package.json` in the CWD doesn't have a `name` property.

## Reproduction

package.json
```json
{
  "scripts": {
    "test": "echo hi"
  }
}
```

Command & Output:
```sh
$ bun run
No "scripts" in package.json found.%
```

Output with `name` property:
```
$ bun run
test-ts-node scripts:

 bun run test
   echo hi

1 scripts
```

**Comment by twysto** [comment]
This is a normal behaviour.

According to the NPM documentation `A package.json file must contain "name" and "version" fields.`  
https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields

**Comment by privatenumber** [comment]
@twysto The documentation page you linked is in the context for published packages. It's under the section "[Contributing packages to the registry](https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry)".


From the [documentation page for `package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json
):
> **name**
> If you don't plan to publish your package, the name and version fields are optional.


> **version**
> If you plan to publish your package, the most important things in your package.json are the name and version fields as they will be required. ... If you don't plan to publish your package, the name and version fields are optional.

My use-case is for `package.json` in unpublished/private projects which don't need to have `name` or `version`. You can confirm that it's still a valid `package.json` by running `npm run ...` to access the `scripts` object.

**Comment by twysto** [comment]
@privatenumber Good catch !
I always thought that these two fields were necessary regardless of the context.
