### ISSUE TITLE
`bunx` fails to find the executable for scoped package

### ISSUE THREAD

**Issue by Zeko369** [oven-sh/bun#2292]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

When using `bunx` with scoped packages i.e. `@withfig/autocomplete-tools` it fails to find the binary to run

1. `bunx @withfig/autocomplete-tools --version`

### What is the expected behavior?

Example with npx
```
franzekan@Frans-M1-Macbook-Pro: /Users/franzekan
➜   npx @withfig/autocomplete-tools --version
Need to install the following packages:
  @withfig/autocomplete-tools@2.7.9
Ok to proceed? (y)
1.0.0
```

Fixed bun (still a WIP locally on my machine)
```
⬢ [Docker] ❯ bun-debug x @withfig/autocomplete-tools --version
initial_bin_name: autocomplete-tools
1.0.0
```

### What do you see instead?

```
➜   bunx @withfig/autocomplete-tools --version
error: could not determine executable to run for package @withfig/autocomplete-tools
```

### Additional information

I've fixed this so it works if the package is already installed (bun i package; bunx package), so it still breaks if you delete the cache on first run i.e.
```
bunx @foo/package -> fails
bunx @foo/package -> works (and every subsequent)
```

**Comment by alexlamsl** [comment]
I had trouble replicating this for all scoped packages:
```console
$ bun --version
0.5.7
$ bun x @npmcli/arborist version
6.2.4
```
looks like this issue applies to more specific cases.
