### ISSUE TITLE
SegmentationFault at `$SOME_INTEGER` when adding entry to `[install.scopes]` in `bunfig.toml`

### ISSUE THREAD

**Issue by yowmamasita** [oven-sh/bun#230]
I am aware of https://github.com/Jarred-Sumner/bun/issues/190 but this seems different

To reproduce:

```
bun create react ./test
cd test
echo "[install.scopes]" > bunfig.toml
echo 'mybigcompany3 = { token = "$npm_config_token" }' >> bunfig.toml
```

Now when you run `bun install`

```
bun install v0.1.1

SegmentationFault at 7885630768349870445


–––– bun meta ––––
Bun v0.1.1 macOS Silicon 21.4.0
InstallCommand: bunfig
Elapsed: 17ms | User: 4ms | Sys: 10ms
RSS: 23.56MB | Peak: 23.56MB | Commit: 69.22MB | Faults: 181
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

```

On x86-64 hardware

```

SegmentationFault at 0


–––– bun meta ––––
Bun v0.1.1 Linux x64 #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022
InstallCommand: bunfig
Elapsed: 7ms | User: 6ms | Sys: 6ms
RSS: 69.21MB | Peak: 27.26MB | Commit: 69.21MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by FinnRG** [comment]
Duplicate of #190. Please close this issue.

**Comment by FinnRG** [comment]
Hmm, I can reproduce this issue, but I'm not sure if this is a duplicate of #190. If you remove the ```[install.scopes]``` part it works, but the SegFault on macOS Silicon is interesting. Could you please run ```sudo perf trace bun install --silent > log.perf.txt 2>&1``` and ```bun install --verbose 2> logs.txt``` on macOS Silicon?

**Comment by yowmamasita** [comment]
Just tested this https://github.com/Jarred-Sumner/bun/issues/260#issuecomment-1176647984 and the segfault error is gone. Same results as commenter as it's still resolving everything from the default registry.
