### ISSUE TITLE
.env.development always loaded

### ISSUE THREAD

**Issue by Kapsonfire** [oven-sh/bun#2303]
### What version of Bun is running?

0.5.8

### What steps can reproduce the bug?

.env.development
```
PORT=3334
```

.env.production
```
PORT=3333
```

> BUN_ENV=production bun index.ts

### What is the expected behavior?
PORT = 3333 in console

### What do you see instead?
PORT = 3334

### Additional information
Tested it in .env.development not having PORT ENV.
Works correctly, so the production .env is loaded and overwritten by the development .env
The logs doesnt say anything about loading the development env

![image](https://user-images.githubusercontent.com/67053124/222907702-e1eeab8d-e6cc-4523-9a34-c835f08fa36d.png)

**Comment by Kapsonfire** [comment]
NODE_ENV is working

**Comment by Kapsonfire** [comment]
Error seems only occuring when using in a package.json script

![image](https://user-images.githubusercontent.com/67053124/222909793-dbd15a6d-35db-42bc-ab61-4cc437b874e3.png)

**Comment by Kapsonfire** [comment]
NPM behaves like expected
![image](https://user-images.githubusercontent.com/67053124/222911466-0d9ed7a8-d434-485e-a3d1-a2021234fd83.png)

**Comment by onionhammer** [comment]
Interesting, I'm seeing it *never* loaded for `bun test`

**Comment by nektro** [comment]
while this is being investigated, do note that if the script itself is:

```json
    "prod": "BUN_ENV=production bun index.js",
```

then it will behave as expected.

**Comment by snoglobe** [comment]
![Image](https://github.com/user-attachments/assets/b0422e8e-d627-404f-b888-86213b6d877e)
does not repro
