### ISSUE TITLE
Bun run not working with special character in folder name

### ISSUE THREAD

**Issue by Douglasgomestosta** [oven-sh/bun#2304]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 5.4.0-139-generic x86_64 x86_64

### What steps can reproduce the bug?

when using bun run servidor.js on a folder called "socialfan (cópia)" where "cópia" means copy on english, the bun return an error, i think this occurs because the special character ó

### What is the expected behavior?

Code running in bun.

### What do you see instead?

error: FileNotFound reading "/home/douglas/Documentos/GitHub/socialfan (cÃ³pia)/servidor.js"

### Additional information

When i change the  "ó" character for "o" without the special character /home/douglas/Documentos/GitHub/socialfan (copia) the code runs without any problem

**Comment by Singha360** [comment]
I can confirm that this problem also persist in MacOS (Ventura 13.4)

Hopefully this would be addressed before version 1 comes out.

Bun info:
version 0.6.7

**Comment by Hanaasagi** [comment]
testing with Bun 0.8.1 no longer has this issue. This issue can be closed now.

![2023-08-28_00-33](https://github.com/oven-sh/bun/assets/9482395/4cddef79-234a-4706-b2ab-1c6f3d18cd22)
