### ISSUE TITLE
"jsxImportSource" is partially ignored

### ISSUE THREAD

**Issue by drinking-code** [oven-sh/bun#2308]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

See https://github.com/drinking-code/bun-jsximportsource.
Mock a simple custom jsx runtime (function that creates a class instance `VirutalElement`) and set the jsx parameters in `tsconfig.json` accordingly:
```json
"jsx": "react-jsx",
"jsxImportSource": "src",
```
Write a jsx/tsx file with a function that returns a jsx element, execute it and log the output.
```jsx
function App() {
    return <Button/>
}
console.log(App())
```

### What is the expected behavior?

Because the custom jsx runtime was set in `tsconfig.json` I would expect that the jsx elements would be transformed into `_jsx()` function calls, which would in turn be imported from "src/jsx-runtime" (or "src/jsx-dev-runtime").
I would also expect that `<Fragment/>`s (and `<></>`) would also be imported from there.
The called function `_jsx()` would return whatever the custom runtime function returns, in my case a `VirutalElement` class instance.

### What do you see instead?

The supposed jsx element that is returned from the function and logged is acutally an object:
```js
{
    $$typeof,
    type: Button,
    key: null,
    ref: null,
    props: Button.defaultProps || {},
    _owner: null
}
```
and not, a `VirutalElement` class instance.

### Additional information

Assuming that the `Bun.Transpiler.transform` returns code that would be used internally by bun, we can take a look a what happens with the jsx runtime. This file (https://github.com/drinking-code/bun-jsximportsource/blob/master/src/app/App.jsx):
```jsx
import Button from './Button.jsx'

export default function App() {
    return <Button/>
}
```
transpiles to:
```js
var $$typeof = Symbol.for("react.element");
import Button from "./Button.jsx";
export default function App() {
  return {
    $$typeof,
    type: Button,
    key: null,
    ref: null,
    props: Button.defaultProps || {},
    _owner: null
  };
}
```
where "src/jsx-runtime" is not at all imported, nor is the `<Button/>` transformed into `_jsx()`.
"jsxImportSource" is only partially ignored however, because if the `<Button/>` is wrapped in `<></>`, it transpiles to:
```js
import* as JSX from "src/jsx-dev-runtime";
import * as $ded8e790 from "react";
var JSXClassic = require($ded8e790);
var $$typeof = Symbol.for("react.element"), $jsx = JSX.jsxDEV, JSXFrag = JSXClassic.Fragment;
import Button from "./Button.jsx";
export default function App() {
  return $jsx(JSXFrag, {
    children: {
      $$typeof,
      type: Button,
      key: null,
      ref: null,
      props: Button.defaultProps || {},
      _owner: null
    }
  });
}
```
where, `_jsx()` is imported from "src/jsx-dev-runtime", to create the Fragment, but the symbol for the Fragment is imported from react.

For reference, these are the outputs of `tsc` of both versions of the file, with the same "compilerOptions":
```js
import { jsx as _jsx } from "src/jsx-runtime";
import Button from './Button.jsx';
export default function App() {
    return _jsx(Button, {});
}

```
```js
import { jsx as _jsx, Fragment as _Fragment } from "src/jsx-runtime";
import Button from './Button.jsx';
export default function App() {
    return _jsx(_Fragment, { children: _jsx(Button, {}) });
}
```

**Comment by Jarred-Sumner** [comment]
Currently, `react-jsx` in `jsx` enables bun's inlining optimization (the object you see), but `jsxImportSource` not being `react` is supposed to disable that. The bug is that `jsxImportSource` is not disabling that optimization.
