### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by nitsanavni** [oven-sh/bun#2311]
### What is the problem this feature would solve?

code coverage is useful for many things

### What is the feature you are proposing to solve the problem?

could we have something similar to [c8](https://github.com/bcoe/c8) or [istanbul](https://istanbul.js.org/) for example?

**Comment by Jarred-Sumner** [comment]
yeah, we need to figure out a way to do this. JavaScriptCore _probably_ has something for this, but I haven't seen it yet.

**Comment by JUSTIVE** [comment]
think this PR is ok to close now

**Comment by Electroid** [comment]
We added initial code coverage in #3975. To support other formats, we're tracking support here:
* #4015 
* #6715 
* #6716

**Comment by maxmilton** [comment]
Issue #4346 seems to be about CLI configurable thresholds rather than supporting other output providers. Perhaps we need to open a new issue?

**Comment by Electroid** [comment]
> Issue #4346 seems to be about CLI configurable thresholds rather than supporting other output providers. Perhaps we need to open a new issue?

I linked the wrong issue, I updated my comment.
