### ISSUE TITLE
`SystemOutdated` error on WSL

### ISSUE THREAD

**Issue by metehus** [oven-sh/bun#233]
When running `bun create`, i get this error:

```bash
$ matehus@Matheus:~/bun$ bun create
Fetching manifest... error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
```

I'm running this on WSL 2 with ubuntu 20 on windows 11 and already tried to apt update & upgrade

**Comment by AurelienConte** [comment]
HI! 
I'm getting also the same error on the command: `bun install` (I think creating another issue is not worth it)
Same as @metehus for the specs and commands tried to resolve the issue.

**Comment by evanwashere** [comment]
does it work if you open powershell as admin and run `wsl --update`?

**Comment by metehus** [comment]
> does it work if you open powershell as admin and run `wsl --update`?

This has fixed the issue perfectly, thanks!

**Comment by mattDuque** [comment]
Hello, I'm having the same issue and already tried apt update & upgrade and `wsl --update` in admin

**Comment by metehus** [comment]
modifying the title so it's easier for others to find
