### ISSUE TITLE
`path.parse` includes file extension in the `name` field

### ISSUE THREAD

**Issue by errilaz** [oven-sh/bun#2338]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.19.0-35-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
const path = require("path")
console.log(path.parse("foo.txt").name)
```

### What is the expected behavior?

`foo`

### What do you see instead?

`foo.txt`

**Comment by Ruk33** [comment]
Hello, I'd like to work on this issue if that's ok. Thanks!
