### ISSUE TITLE
chalk package cannot be imported

### ISSUE THREAD

**Issue by magus** [oven-sh/bun#234]
## Repro

In a fresh folder run the following commands

```
cat << EOF > chalk.ts
import chalk from "chalk";
console.log(chalk.cyan("hi"));
EOF

bun add chalk
bun install

bun chalk.ts
```

> <img width="800" alt="Screen Shot 2022-07-05 at 9 51 56 PM" src="https://user-images.githubusercontent.com/290084/177471336-b38ca49e-b376-4224-b2a5-674229032581.png">

> Error text for searching + google

```
error: Could not resolve: "#ansi-styles". Maybe you need to "bun install"?
import ansiStyles from '#ansi-styles';
                       ^
/Users/noah/github/repro/node_modules/chalk/source/index.js:1:24 23

error: Could not resolve: "#supports-color". Maybe you need to "bun install"?

import supportsColor from '#supports-color';
                          ^
/Users/noah/github/repro/node_modules/chalk/source/index.js:2:27 65%  
```

**Comment by afrokick** [comment]
https://nodejs.org/api/packages.html#packages_subpath_patterns

Seems like Bun doesn't respect "imports" field in package.json of chalk

```json
{
	"name": "chalk",
	"version": "5.0.1",
	...
	"type": "module",
	"main": "./source/index.js",
	"exports": "./source/index.js",
	"imports": {
		"#ansi-styles": "./source/vendor/ansi-styles/index.js",
		"#supports-color": {
			"node": "./source/vendor/supports-color/index.js",
			"default": "./source/vendor/supports-color/browser.js"
		}
	},
        ...
}

```

**Comment by Jarred-Sumner** [comment]
Depends on https://github.com/Jarred-Sumner/bun/issues/478

**Comment by ctjlewis** [comment]
I wrote an equivalent wrapper around `ansi-styles`, if anyone wants to use it in place of `chalk` in the meantime:

https://www.npmjs.com/package/bun-style

Sadly this will not help if you need to use something that depends on `chalk`, like `ora`.

See also #822.
