### ISSUE TITLE
express with bun: `req.query` is empty

### ISSUE THREAD

**Issue by nitsanavni** [oven-sh/bun#2344]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.0-47-generic x86_64 x86_64

### What steps can reproduce the bug?

here's a small repo that compares the same minimal express app run by Node vs Bun:

https://github.com/nitsanavni/bun-express-issue

### What is the expected behavior?

`req.query` should have the query params

### What do you see instead?

`req.query` is an empty object, while in Node it's populated

**Comment by Jarred-Sumner** [comment]
Do you still run into this on the canary build of Bun?

```
bun upgrade --canary
```

**Comment by nitsanavni** [comment]
Tested now. With canary build it's resolved. 👍🏼
