### ISSUE TITLE
Hundreds of looping symlinked files created when installing typescript on android in a manjaro proot environment

### ISSUE THREAD

**Issue by pfgithub** [oven-sh/bun#2349]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.10.107-android13-4-00004-gf0fe4f768061-ab8935229 aarch64 unknown

### What steps can reproduce the bug?

```
bun add typescript
bun run tsc --noEmit
```

### What is the expected behavior?

Typescript runs

### What do you see instead?

```
bun run tsc --noEmit


error: SymLinkLoop reading "/home/pfg/.bun/install/cache/typescript@4.9.5/lib/tsc.js"

error: "tsc" exited with code 1 (SIGHUP)
```

```
u0_a269@localhost ~/m/h/p/J/amvjire> readlink ../../.bun/install/cache/typescript@4.9.5/lib/tsc.js
/data/data/com.termux/files/home/manjaro/home/pfg/.bun/install/cache/typescript@4.9.5/lib/.l2s.tsc.js0001
u0_a269@localhost ~/m/h/p/J/amvjire> readlink /data/data/com.termux/files/home/manjaro/home/pfg/.bun/install/cache/typescript@4.9.5/lib/.l2s.tsc.js0001
/data/data/com.termux/files/home/manjaro/home/pfg/.bun/install/cache/typescript@4.9.5/lib/.l2s.tsc.js0001.0002
u0_a269@localhost ~/m/h/p/J/amvjire> readlink /data/data/com.termux/files/home/manjaro/home/pfg/.bun/install/cache/typescript@4.9.5/lib/.l2s.tsc.js0001.0002
/data/data/com.termux/files/home/manjaro/home/pfg/.bun/install/cache/typescript@4.9.5/lib/.l2s..l2s.tsc.js0001.00020001
u0_a269@localhost ~/m/h/p/J/amvjire>
```

![Screenshot_20230308-130133](https://user-images.githubusercontent.com/6010774/223793827-a63a27f6-35f9-4b9a-b565-d56857b8a145.png)

### Additional information

If this doesn't occur on other platforms, it's probably an issue with the manjaro proot environment specifically

**Comment by nektro** [comment]
Hi! if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
