### ISSUE TITLE
Allow "bun:test" to be imported outside of `bun test`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2350]
If you have a utility file that imports any of the `bun:test` globals, the entire file can't be imported by Bun.

```
// util.js
import { test } from "bun:test";
```

```console
1 | var { test } = globalThis.Bun.jest(import.meta.path);
   ^
error: Run "bun test" to run a test
```

Instead, Bun should only error when `test` or related functions are called, not imported.

**Comment by Jarred-Sumner** [comment]
@paperdave fixed this awhile ago
