### ISSUE TITLE
Timeout: Cannot connect to remote mongodb via a IP Address.

### ISSUE THREAD

**Issue by ltcaosj** [oven-sh/bun#2355]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Mac M1

### What steps can reproduce the bug?

This code does not work.
import { MongoClient } from "mongodb";

const client = new MongoClient("mongodb://192.168.1.200:27017");
await client.connect();
const db = client.db("test");
const collection = db.collection("test");
await collection.insertOne({ hello: "world" });
const result = await collection.findOne({ hello: "world" });

console.log(JSON.stringify(result));

### What is the expected behavior?

Can connect to remote mongodb succesfully.

### Additional information

Same code,  but if I connect to mongodb at localhost - it's working fine.

import { MongoClient } from "mongodb";

const client = new MongoClient("mongodb://localhost:27017");
await client.connect();
const db = client.db("test");
const collection = db.collection("test");
await collection.insertOne({ hello: "world" });
const result = await collection.findOne({ hello: "world" });

console.log(JSON.stringify(result));

**Comment by Angusross111** [comment]
Im also getting the same problem. It seems it exits quietly at the first await. eg `await client.connect();`. 
Looking in the code I think it fails here: `await promisify(callback => topology.connect(options, callback))();` in `mongo_client.ts`
I tested it with bun `v0.5.6`, `v0.5.7`, and `v0.5.8-canary`. Also tested it with mongodb `v5.1`, `v5.0` and `v4.14`

**Comment by swagisays** [comment]
got same issue
