### ISSUE TITLE
package.json `exports` ignores some conditions (`@astrojs/compiler` breaking)

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2357]
### What version of Bun is running?

0.5.8

### What steps can reproduce the bug?

Bun Docs show that package.json `exports` can define these fields.
![image](https://user-images.githubusercontent.com/24465214/224123057-859fe50c-17b2-4a01-af45-28b46151251d.png)

It is missing `import` and `require`, where the former breaks importing `@astrojs/compiler` as it defines this for it's `exports`:
```json
  "exports": {
    ".": {
      "browser": "./browser/index.js",
      "import": "./node/index.js",
      "default": "./browser/index.js"
    },
    ...
  },
```

And bun picks up `browser`, and ignores `import`.

[node docs here](https://nodejs.org/api/packages.html#conditional-exports) define `import`, `require`, and `node-addons` which bun ignores. I've never seen that last one but it seems to have some extra logic where the first two can just be treated as a higher priority than `browser`.

Reproduction:
```ts
import {transform} from '@astrojs/compiler';
transform("");
```

### What is the expected behavior?

Loading the node version of the astro compiler.

### What do you see instead?

![image](https://user-images.githubusercontent.com/24465214/224123984-4479d5bf-07ce-4335-9cf9-5d3df19c9fc2.png)

### Additional information

Workaround for astro compiler:
```ts
import { transform } from "./node_modules/@astrojs/compiler/node/index.js";
```

**Comment by Jarred-Sumner** [comment]
ah yeah, we should prioritize "browser" last
