### ISSUE TITLE
Missing documentation for Bun.hash / crypto utils

### ISSUE THREAD

**Issue by drinking-code** [oven-sh/bun#2360]
### What is the type of issue?

Documentation is missing

### What is the issue?

#885 pointed out that Bun.hash is not documented and @Electroid responded that they are tracking docs issues elsewhere but will move back to GitHub issues when the first version of the official docs is out. I guess this happened, and i couldn't find any other issues mentioning Bun.hash docs, so here it is.

**Comment by humphd** [comment]
Is any of `Bun` documented?  In https://bun.sh/docs/api/globals the link for `Bun` goes to https://nodejs.org/api/buffer.html#class-buffer

**Comment by Electroid** [comment]
Yes we will document `Bun.hash`, and fix the issue with the incorrect URL.

**Comment by colinhacks** [comment]
> Is any of `Bun` documented? In https://bun.sh/docs/api/globals the link for `Bun` goes to https://nodejs.org/api/buffer.html#class-buffer

The Bun APIs are documented under "API".

<img width="864" alt="Screenshot 2023-03-10 at 6 39 51 PM" src="https://user-images.githubusercontent.com/3084745/224460711-e6e098b1-0a67-4736-950f-5dc91d8df108.png">
