### ISSUE TITLE
Add a locals() function like python’s

### ISSUE THREAD

**Issue by u9g** [oven-sh/bun#2374]
### What is the problem this feature would solve?

Would allow for debug printing locals programmatically.

### What is the feature you are proposing to solve the problem?

Adding a locals function similar to pythons which outputs an object with each local’s name mapped to it’s current value.

### What alternatives have you considered?

Manually writing out each variable name cooresponding to it’s value, which isn’t really an alternative, as it isn’t programmaticly generated.

**Comment by Jarred-Sumner** [comment]
we will have proper debugger support and that will be a better solution

**Comment by u9g** [comment]
> we will have proper debugger support and that will be a better solution

Yes, but I was more hoping to be able to do something like this: https://rich.readthedocs.io/en/stable/console.html#logging (see the second paragraph) which isn't really doable even with a proper debugger.

**Comment by Electroid** [comment]
We implemented debugger support with `bun --inspect`
