### ISSUE TITLE
AOT compilation with Hop.js, instead of JSC JIT

### ISSUE THREAD

**Issue by paulocoghi** [oven-sh/bun#2376]
### What is the problem this feature would solve?

Bun still has the same problem of not being able to AOT compile its programs, as in any other JIT implementation of JS.

With AOT compiled JS plus the ultra-fast standard library from Bun, we could reach a theoretically oasis for JS, being finally able to use it universally, including native iOS applications, low-latency scenarios like command line apps, and many more.

Additionally:
 - the startup time on serverless would reach a whole new level
 - the memory usage would reduce even more _(perhaps on various scales of magnitude, as presented in https://www.youtube.com/watch?v=iY1EXHQ6IeQ)_

### What is the feature you are proposing to solve the problem?

Using Hop.js ([manuel-serrano/hop](https://github.com/manuel-serrano/hop)) as an AOT compiled JS implementation as a replacement of JSC to solve such problem and bringing (in some cases) an additional increase of performance.

### What alternatives have you considered?

There were some attempts to AOT compile javascript, but they were incomplete _or_ not performant, losing badly from JIT implementations.

Hop.js is a profound research on AOT JS which finally brings the same performance than the JIT counterparts (on average) and adds the benefits of independent and really compiled binaries, as in C/C++, instead of fake compilation like on `pkg` and `bkg`.

**Comment by Electroid** [comment]
We aren't planning on replacing JavaScriptCore.
