### ISSUE TITLE
Support parsing TypeScript 5.0's const generics

### ISSUE THREAD

**Issue by alii** [oven-sh/bun#2377]
### What is the problem this feature would solve?

Right now, bun is not sure what the `function a<const T>(t: T)`  syntax is.

### What is the feature you are proposing to solve the problem?

Support this syntax

### What alternatives have you considered?

n/a

**Comment by Electroid** [comment]
Thanks for opening this issue, yes, we'll need to add support for the new goodies from TypeScript 5.0

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/2593
