### ISSUE TITLE
Integration tests running unnecessarily in CI

### ISSUE THREAD

**Issue by logikaljay** [oven-sh/bun#238]
Looking at GitHub Actions for this project, it appears that the CI takes a long time to run:
![image](https://user-images.githubusercontent.com/980149/177475856-ca2c87a9-a298-4abc-b54b-184d892f2f0d.png)

For example, in PR #236 - this was a simple typo fixed in the `/package/bun-landing` project.

I don't think its necesary to to run CI tests when changes are made to the `/package/bun-landing` project.

**Comment by Electroid** [comment]
Hey, thanks for taking the time to contribute! We totally agree the build times are unacceptable. We've made some improvements to which folders trigger a build, but are working on improving it overall.

We're already tracking this elsewhere so going to close this for now.
