### ISSUE TITLE
build ci fails for forks

### ISSUE THREAD

**Issue by jsoref** [oven-sh/bun#2384]
### What version of Bun is running?

0.5.8

### What platform is your computer?

macOS (x64, arm64), Linux (x64)

### What steps can reproduce the bug?

1. Add a blank line to `Dockerfile` on a branch
2. Create a PR from that branch in a fork
3. wait
4. realize that the workflows are stuck waiting for "self hosted" runners: https://github.com/check-spelling/bun/actions?query=is%3Acancelled+branch%3Apoke-build

### What is the expected behavior?

If self-hosted runners (or custom github runners) are necessary, workflows should either offer fallbacks or only run in the main repository (using an `if`)

### What do you see instead?

The runs took >3 hours waiting for things that would never happen.

(Sorry, I cancelled the runs, and when that happens github eats the output that it had temporarily provided)

### Additional information

It's possible to provide a friendlier experience:
https://github.com/commercialhaskell/stack/blob/8fd916a3941243ca3ac559390e5ea84af5aef037/.github/workflows/integration-tests.yml#L150-L184

**Comment by Electroid** [comment]
This was fixed.
