### ISSUE TITLE
"bun install" or "bun add package@^version" problem when I set installl.registry

### ISSUE THREAD

**Issue by ystaryou** [oven-sh/bun#2385]
### What version of Bun is running?

0.5.7

### What platform is your computer?

mac x64

### What steps can reproduce the bug?

add bunfig.toml and set 
[install]
registry = "https://registry.npmmirror.com"

<img width="404" alt="image" src="https://user-images.githubusercontent.com/127463010/224911960-62228949-62e7-4a12-b6ed-6b68c6fbe2ea.png">

`bun add eslint@^7.11.0`
 then eslint 7.11.0 is installed

but I run `yarn add  eslint@^7.11.0` or `npm i eslint@^7.11.0`
then eslint 7.32.0 is installed

when I remove bunfig.toml, the result is fine (eslint 7.32.0 is installed)

**Comment by Electroid** [comment]
We recently fixed various issues with `bun install` using the wrong tag. In Bun v1.0.7, this has been fixed.

```
❯ cat bunfig.toml 
[install]
registry="https://registry.npmmirror.com"
```

```
❯ bun add eslint@^7.11.0
bun add v1.0.7 (fa1bbec0)

 installed eslint@7.32.0 with binaries:
  - eslint


 94 packages installed [6.68s]
```
