### ISSUE TITLE
fetch() failed

### ISSUE THREAD

**Issue by Powma** [oven-sh/bun#2386]
### What version of Bun is running?

0.5.5

### What platform is your computer?

Linux 5.10.0-20-rt-amd64 x86_64 unknown

### What steps can reproduce the bug?

```typescript
fetch(
	'https://foo.toto:9443',
	{
		method: 'GET',
		headers: {
			'Content-Type': 'application/json',
			Authorization: `Bearer xxxxxxx`,
		},
	}
)
	.then((res: any) => res.json())
	.catch((err) => {
		console.error(err);
	});
```
output : 
```
ConnectionClosed: fetch() failed
 path: "https://foo.toto:9443"
```
 
With curl : 
```
curl -vvv --location 'https://foo.toto' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer XXXXXXX'
*   Trying 10.0.202.96:8443...
* Connected to foo.toto(10.0.0.0) port 9443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=XXXX; CN=foo.titi; emailAddress=foo@foo.com
*  start date: Jun 15 12:40:46 2021 GMT
*  expire date: Jun 16 12:40:46 2023 GMT
*  subjectAltName: host "foo.toto" matched cert's "foo.toto"
*  issuer: C=XX; O=XXX; OU=XXXXX; CN=XXXXX
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: foo.toto:9443
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer XXXXXXX
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200
< Date: Tue, 14 Mar 2023 08:39:32 GMT
< X-AREQUESTID: @xxxxxxxx
< X-ASEN: SEN-XXXXX
< X-AUSERID: XXXX
< X-AUSERNAME: XXXXXXX
< X-ASESSIONID: qvnjmx
< Cache-Control: no-cache, no-transform
< Vary: X-AUSERNAME,Accept-Encoding
< Content-Length: 4670
< Content-Type: text/plain;charset=UTF-8
< X-Content-Type-Options: nosniff
< Content-Disposition: attachment; filename="submodules.json"; filename*=UTF-8''submodules.json
< Set-Cookie: FOOSESSIONID=xxxxxx; Path=/; Secure; HttpOnly
< Via: 1.1 foo:9443
< Connection: close
<
***here my data***
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

### What is the expected behavior?

Response (2 KB) {
  ok: true,
  url: "foo.toto:9443",
  statusText: "OK",
  redirected: false,
  bodyUsed: false,
  status: 200,
  Blob (2 KB)
}

### What do you see instead?

ConnectionClosed: fetch() failed

### Additional information

I'm feeling the problem is present in the header of the answer request Connection: close...

The certification authority is not public, there is probably a link with the problem but I have a doubt because the other sites on my intranet work.

I'm trying to browse sites on the internet in order to have the same bug but for the moment I can't find...

**Comment by Landris18** [comment]
Same issue and I also created an issue for that, the only difference is the version of bun , I use bun 0.5.8

**Comment by Jarred-Sumner** [comment]
Two things that stand out here:
> < Connection: close
> TLSv1.2 (OUT), TLS alert, close notify (256):

Seems likely we are seeing the Connection close and then halting all data, even though the connection may have received the entire response body.

**Comment by Landris18** [comment]
> Two things that stand out here:
> 
> > < Connection: close
> > TLSv1.2 (OUT), TLS alert, close notify (256):
> 
> Seems likely we are seeing the Connection close and then halting all data, even though the connection may have received the entire response body.

@Jarred-Sumner I don't know if I can reply to your comment but I'm facing the same with a npm package called `yt-search` who work very well on nodeJS but not with bun. My issue is explained here #2421

**Comment by Powma** [comment]
> Seems likely we are seeing the Connection close and then halting all data, even though the connection may have received the entire response body.

Do you have a solution for fix this problem ? With NodeJS I didn't have this problem. I'm free on Discord if you want try something with me for found the problem.

**Comment by Jarred-Sumner** [comment]
I am pretty confident this is fixed 

Please leave a comment if it isn't
