### ISSUE TITLE
Feature: Worker threads Or Rust tokio

### ISSUE THREAD

**Issue by ymzuiku** [oven-sh/bun#2390]
### What is the problem this feature would solve?

Since there is currently no Worker threads feature, why not skip it and implement a Tokio-like solution similar to Rust? The Node.js ecosystem has always struggled to solve computationally intensive projects, and since Bun wants to change the world of Node.js, it could consider addressing these issues.

Although WebWorker is a standard, it requires the use of a separate worker.js file, which has not provided a great user experience. Likewise, Worker threads require developers to manage threads themselves, making high demands on them. The GMP model in Golang and tokio in Rust make it easier for developers to complete multi-threaded tasks, something that the Nodejs ecosystem has always envied.

### What is the feature you are proposing to solve the problem?

In Zid runtime create like Rust Tokio, bunjs develper just use `bun run index.ts --tokio`.

Rust tokio has two modes, one is single-threaded, similar to the event loop of Nodejs; the other is multi-threaded, where each thread will take on tasks to fully utilize the computational power of multiple threads. For users, this is imperceptible, as they only need to use async/await. If Bunjs can accomplish this great task, then veteran Nodejs players will have more motivation to switch to Bunjs.

**Comment by Jarred-Sumner** [comment]
By tokio, I think you mean a lightweight multithreaded coroutine abstraction inside JavaScript. It’s a good idea, very difficult to implement though. 

The same-file issue with Worker can be solved via the module declarations tc39 proposal 

We will definitely add Worker support to Bun

**Comment by jimmywarting** [comment]
I suggest impl web workers instead...
you can create a web worker from code also (with object urls)

```js
const blob = new Blob([ code ], { type: 'text/javascript' })
const url = URL.createObjectURL(blob)
const worker = new Worker(url, { type: 'module' })
```

don't repeat the same misstake nodejs did with worker_threads 
follow deno's example of being web compatible as a mean to be cross compatible.

**Comment by ghiscoding** [comment]
Looks like the first implementation was merged in PR #3645

**Comment by Jarred-Sumner** [comment]
Web Workers has been added in #3645 (thanks @ghiscoding for bumping this issue)

[We wrote some docs](https://bun.sh/docs/api/workers)

This will be released in Bun v0.7.0, but you can try it now in the canary build:
```bash
bun upgrade --canary
```

**Comment by jimmywarting** [comment]
I haven updated or tested buns new web worker but i read the documentation over at: https://bun.sh/docs/api/workers#open

> The "open" event is emitted when a worker is created and ready to receive messages. **This can be used to send an initial message to a worker once it's ready**. (This event does not exist in browsers.)
> ```js
> const worker = new Worker(new URL("worker.ts", import.meta.url).href);
> 
> worker.addEventListener("open", () => {
>   console.log("worker is ready");
> });
> ```

I want to highlight this in particular:
> This can be used to send an initial message to a worker once it's ready.

This is not how web worker works.
you can send a `postMessage` to a worker that haven't yet been fully loaded.
The message will instead be queued and sent to the worker later when it's fully loaded.

```js
const worker = new Worker(url)
worker.postMessage('do the thing') // should work fine.
```

i would say that it gives false believes that it's how the deno & web workers are suppose to behave as well but it isn't.
if i where to depend on `open` event to wait for it and then emit a initial message when it is ready and then later wished to build something that's more cross friendly for other env. too then it would just sit there and do nothing cuz no open event is being fired. 

i'm not so sure that having a open event was the best idea...
it would be better for the worker to send a postMessage back to tell the main thread that it's ready instead, and then listen to message event to know when it's done loading.

**Comment by Jarred-Sumner** [comment]
> This is not how web worker works. you can send a `postMessage` to a worker that haven't yet been fully loaded. The message will instead be queued and sent to the worker later when it's fully loaded.

Yes, that is also how it works in Bun. You can send messages before the worker has started and the messages are enqueued.

The `"open"` event exists as another way.

**Comment by jimmywarting** [comment]
> Yes, that is also how it works in Bun. You can send messages before the worker has started and the messages are enqueued.

👍 that's good.

> The `"open"` event exists as another way.

it's just that i'm not so sure that it's such a good idea to depend on this other solution. that's all.

---

also some nit pick in the docs:

```diff
// Worker thread:
- self.addEventListener("message", = event => {
+ self.addEventListener("message", event => {
  console.log(event.data);
});
// or use the setter:
// self.onmessage = fn

// if on the main thread
- worker.addEventListener("message", = event => {
+ worker.addEventListener("message", event => {
  console.log(event.data);
});
```
there is two `=` too many...
