### ISSUE TITLE
There are missing value from .env file when value contains '$'

### ISSUE THREAD

**Issue by tonyrsb-ralali** [oven-sh/bun#2406]
### What version of Bun is running?

0.5.7

### What steps can reproduce the bug?

in `.env` file, I have variable:
`MY_SECRET_KEY=kMHy=*Yju$VB?%7p`

When i get the value using `process.env.MY_SECRET_KEY` the output is `kMHy=*Yju?%7p` 
There are 3 characters `$VB` are missing out

### What is the expected behavior?

When i get the value using `process.env.MY_SECRET_KEY` the output should be `kMHy=*Yju$VB?%7p` 

### What do you see instead?

When i get the value using `process.env.MY_SECRET_KEY` the output should be `kMHy=*Yju?%7p` 
There are 3 characters `$VB` are missing out

### Additional information

Please fix this issue :)

**Comment by adrien-zinger** [comment]
Hi, is there someone who works on it ? Can I try to fix it ?

**Comment by adrien-zinger** [comment]
Hey @tonyralali, actually the behavior is very the same as the version 18.9.1 of node. I could fix it, but I don't think it will be merged.

Temporary, you can define your environment variable surrounded by single quotes and it should work.

```js
// I declared with: `export MY_VAR='*Yju$VB?%7p'`

console.log(process.env.MY_VAR);
// output: *Yju$VB?%7p
```

**Comment by bitdom8** [comment]
Can't run Bun.env in Ubuntu 20

**Comment by colinhacks** [comment]
You should escape the dollar sign. 

```
MY_SECRET_KEY="kMHy=*Yju\$VB?%7p"
```
This is happening because your env vars can contain other env vars:

```
REGISTRY_URL=http://$username:$password@mydomain.com
```

**Comment by Bezlepkin** [comment]
> You should escape the dollar sign.
> 
> ```
> MY_SECRET_KEY="kMHy=*Yju\$VB?%7p"
> ```
> 
> This is happening because your env vars can contain other env vars:
> 
> ```
> REGISTRY_URL=http://$username:$password@mydomain.com
> ```

it sounds weird... сan't you just fix it?
