### ISSUE TITLE
bun static --watch transpile files to the output directory

### ISSUE THREAD

**Issue by boldurean** [oven-sh/bun#2408]
### What is the problem this feature would solve?

Web Bundler capable to watch file changes without running dev server. In case of working with ASP.NET framework which runs it's own dev server will be nice if Bun will just watch for file changes, transpile and output to the specified directory same  option has `webpack --watch`. No any current bundlers except webpack support this feature. 

### What is the feature you are proposing to solve the problem?

`bun static --watch` command will watch for file changes, transpile and output the files to the specific directory. 

### What alternatives have you considered?

`webpack --watch`

**Comment by Lewenhaupt** [comment]
Esbuild has the same feature and I'm looking to use it a project related to AWS CDK and hot-reloading lambdas.

**Comment by Electroid** [comment]
This is implemented in Bun's bundler with `bun build --watch`.
