### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by steren** [oven-sh/bun#241]
I was expecting to quickly be able to see Bun's license, but wasn't able to find a LICENSE file at the root of the repo.

**Comment by halostatue** [comment]
It’s [complicated](https://github.com/Jarred-Sumner/bun#license). The presence of a `LICENSE` file *usually* indicates a single licence, which is not something that Bun can exactly promise.

**Comment by ignoramous** [comment]
I always thought that `NOTICES` file serves as dependencies licenses file (like in the Android Open Source Project), while `LICENSE` (or `LICENSE-xyz` like [rust-lang](https://github.com/rust-lang/rust)) serves as a license for the original/all parts of `bun` itself.

Edit: IANAL. Accepting contributions without a license file suitable for open-source / source-available code is an even more hairy problem, I'd imagine.

**Comment by jheysaaz** [comment]
Why not add a MIT license file?

(See [Jarred-Sumner/bun#license](https://github.com/Jarred-Sumner/bun#license))

**Comment by paralin** [comment]
@halostatue I've seen plenty of projects that use MIT/Apache-2, how is this different?

https://github.com/libp2p/go-libp2p-noise/blob/master/LICENSE.md

**Comment by halostatue** [comment]
I can’t speak for @Jarred-Sumner’s reasoning, but there’s no *explicit* reason that a `LICENSE` file is necessary. It’s conventional, but even when it’s complicated (see [halostatue/diff-lcs/License.md](https://github.com/halostatue/diff-lcs/blob/main/License.md), the presence of a single file sometimes is not useful.

I personally think that the documentation in the README is sufficient.

**Comment by paralin** [comment]
~It's not sufficient~ every project has a LICENSE file, there are very few that don't. When evaluating a project one of the first things many developers click on is the license file.

Obviously it's up to the project owners to decide, but it goes against the norm to not have one.

It would be IMO best to either copy paste what is in the license section currently into that file or to add a couple lines in the file referencing the readme.

**Comment by halostatue** [comment]
No, it’s sufficient. You may not *like* it, but many project owners don’t particularly care. I have rejected a PRs for a project that I manage to undo some formatting (in order to make it hash identically to other copies) that I did to my project’s copy of the MIT licence, because I write my documentation (*including* the licence file, if I choose to include one) for humans, not for machines.

**Comment by paralin** [comment]
@halostatue It's legally sufficient; yes,

![image](https://user-images.githubusercontent.com/534887/179162345-324840ae-8331-4e46-bc9e-7c70cf71266b.png)

Please consider the following cases:

 - GitHub UI: if you have a license file, even if it is just 2 lines which say "check readme.md" the link shown above works.
 - Many tools scan code repositories for a LICENSE and aggregate the contents for legal bundles.
 - In bundlers like [buildroot](https://buildroot.org) the LICENSE file is hashed separately, such that any changes in the license can be detected by the changed hash. This would be infeasible with the license in the README, which changes more frequently.

Example: https://github.com/buildroot/buildroot/commit/33e947a2d5db2e7b8fb0cfc64183add77b29c347#diff-5a5f0fbd26a4731b6c9f980a53dd3a2699e60427f0659e6d41ae6baec991e5a4R5

**Comment by Jarred-Sumner** [comment]
Probably just makes sense to copy paste the readme license section into a
LICENSE file and call it a day

**Comment by Aspie96** [comment]
I am slightly confused.
The documentation says MIT license (without specifying the copyright notice), however files contain the text of the 2-clause BSD license, which is nearly equivalent, but not the same license.

**Comment by birkskyum** [comment]
Seen a lot of this license business license stuff the past few years:

https://www.percona.com/blog/the-future-of-open-source-is-polarized/
https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.0.0

Should we be worried about something like that happening to bun?

**Comment by Jarred-Sumner** [comment]
No. We have a detailed license page on our docs:
https://bun.sh/docs/project/licensing

I will copy paste that into a LICENSE.md

**Comment by paralin** [comment]
@Jarred-Sumner much appreciated. There's still no hashable license file here, which would, if added, also make generating project legal info much easier!
