### ISSUE TITLE
Optimize the execution behavior of setTimeout when the delay is 0

### ISSUE THREAD

**Issue by WangYuLue** [oven-sh/bun#2410]
### What is the problem this feature would solve?

Make the execution behavior of setTimeout consistent with nodejs when the delay is 0

### What is the feature you are proposing to solve the problem?

I executed the demo below with different JS runtimes:

```js
# test.js 

let start = Date.now();
let times = [];

setTimeout(function run() {
  const timeout = Date.now() - start;
  if (timeout > 20) {
    console.log(times);
    console.log("length:", times.length);
    return;
  }
  times.push(timeout);
  setTimeout(run);
});
```

The following is the execution result：

run in browser:

```js
[0, 0, 0, 0, 5, 10, 15, 20]
length: 8
```

run in nodejs:

```js
[
   1,  3,  3,  4,  6,  7,  8,
   9, 10, 12, 14, 15, 15, 17,
  18, 19, 20
]
length: 17
```

run in deno:

```js
[
  3, 4,  5,  6,
  7, 8, 14, 20
]
length: 8
```

run in bun:

```js
[
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  ...,
  ...
]
length: 73561
```

**Comment by Jarred-Sumner** [comment]
Ah, Bun is currently running the timer once the task queue is completed

Node seems to be running the timer 1ms later
