### ISSUE TITLE
bun for Android 

### ISSUE THREAD

**Issue by Andev70** [oven-sh/bun#2413]
### What is the problem this feature would solve?

Please make bun available for Android as well

### What is the feature you are proposing to solve the problem?

android support 

### What alternatives have you considered?

Node js

**Comment by gaurishhs** [comment]
I think https://termux.dev/ can help

**Comment by HarukaYamamoto0** [comment]
> I think https://termux.dev/ can help

he said he wanted it to have android support, just putting the termux link won't help

**Comment by gaurishhs** [comment]
> > I think https://termux.dev/ can help
> 
> he said he wanted it to have android support, just putting the termux link won't help

It's quite weird to expect a runtime to run on Android. These are just work arounds and shouldn't last in the long run. Termux is the best option out there to run Bun/Node. Also, There's this app as well https://github.com/tempage/dorynode to run node on android which is closed source and does not work. So the only way out is Termux

**Comment by romanovj** [comment]
I can run bun with grun https://github.com/termux-pacman/glibc-packages
but it requites disable selinux in order to install packages, weird, no denies in logs
```
~/bun-linux-aarch64/hh $ grun ../bun install
bun install v0.7.3 (a9b3d583)
Failed to install 2 packages
error: AccessDenied installing bun-types
error: AccessDenied installing hono
[1.67s] done
~/bun-linux-aarch64/hh $ su -c setenforce 0
~/bun-linux-aarch64/hh $ grun ../bun install
bun install v0.7.3 (a9b3d583)
 + bun-types@0.7.3
 + hono@2.7.8

 2 packages installed [12.00ms]
~/bun-linux-aarch64/hh $ grun ../bun run src/index.ts
Running at http://localhost:3000
^C
~/bun-linux-aarch64/hh $ su -c setenforce 1
~/bun-linux-aarch64/hh $ grun ../bun run src/index.ts
Running at http://localhost:3000
```
UPD
manually coping modules from ~/.bun/install/cache to project directory solved the problem with selinux

**Comment by iMrDJAi** [comment]
https://github.com/nodejs-mobile/nodejs-mobile

**Comment by iMrDJAi** [comment]
@gaurishhs Context: It has nothing to do with termux, people often use plugins like https://github.com/hampoelz/Capacitor-NodeJS as part of their app stack to allow full JavaScript mobile development experience. You can combine Cordova/Capacitor with Node.js mobile, similarly to Electron on PC.

**Comment by gaurishhs** [comment]
i get that. i wasn't aware of such projects.

**Comment by xeoshow** [comment]
> https://github.com/nodejs-mobile/nodejs-mobile

This looks like is not maintained any more ...

**Comment by birkskyum** [comment]
Is anything specific blocking here?

**Comment by iMrDJAi** [comment]
Just to say, if you're willing to release Bun on Android, make sure to support at least API 21 and up (don't believe the statistics)...

**Comment by Electroid** [comment]
We are not likely to add official Android support anytime soon. There are some people that have used [Termux]( https://termux.dev/), though that is an emulator and not an actual replacement for full Android support.

**Comment by iMrDJAi** [comment]
> We are not likely to add official Android support anytime soon. There are some people that have used [Termux](https://termux.dev/) with success.

@Electroid Excuse me but again just to be clear, Termux won't allow you to embed Bun as a JavaScript runtime on your mobile app. I'm afraid that you misunderstood the issue here.

Can you please take a look at https://github.com/nodejs-mobile/nodejs-mobile?

**Comment by HarukaYamamoto0** [comment]
> We are not likely to add official Android support anytime soon. There are some people that have used [Termux](https://termux.dev/) with success.

Termux is just a terminal emulator, it doesn't do compatibility miracles

**Comment by Electroid** [comment]
> > We are not likely to add official Android support anytime soon. There are some people that have used [Termux](https://termux.dev/) with success.
> 
> Termux is just a terminal emulator, it doesn't do compatibility miracles

Yes, that is understood. I updated my comment to clear that up. Unfortunately, it still doesn't change the reality that we are unlikely to introduce full Android support anytime soon, if ever.

**Comment by HarukaYamamoto0** [comment]
To be honest, I don't even expect this support to be provided, after all, whoever creates the packages never bothers to create support for Android, even though it is a reality that there are more cell phones than PCs and that many people don't have enough money to buy a good one. . computer. to be able to program. (If my English isn't very good, it's Google Translate's fault)

**Comment by HarukaYamamoto0** [comment]
It can be said that mobiles are minorities.

**Comment by SerJaimeLannister** [comment]
> > https://github.com/nodejs-mobile/nodejs-mobile
> 
> This looks like is not maintained any more ...

I don't think so , its not archived , maybe the developer has left but hey its open source you can contribute to it as well unlike dorynode.

I think the spirit of open source lies in collective labour towards a common goal not having someone else labor away their time and if they stop doing it , then call the project a waste of time.

**Comment by SerJaimeLannister** [comment]
> To be honest, I don't even expect this support to be provided, after all, whoever creates the packages never bothers to create support for Android, even though it is a reality that there are more cell phones than PCs and that many people don't have enough money to buy a good one. . computer. to be able to program. (If my English isn't very good, it's Google Translate's fault)

I don't think that we need to create specific packages for android , atleast for things like express etc. , some of us just want to put a backend in android in a language that we are familiar 

Node is just running js code in v8 , so node_mobile somehow does it on android , there has to be virtually very little difference in compatibility b/w android and pc's. The only thing where it can be different is probably file structure etc.

Maybe the same can be done for bun
