### ISSUE TITLE
Protocol mismatch. Expected: http:. Got: https:

### ISSUE THREAD

**Issue by Landris18** [oven-sh/bun#2415]
### What version of Bun is running?

Latest

### What platform is your computer?

Linux 5.15.94-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

This error happens when using a package yt-search from npm. 
This npm package work well in nodejs but not in bun.

![image](https://user-images.githubusercontent.com/47665507/225971269-0fa44302-a3f5-4eb1-97cd-ecdfa9e1bb8f.png)

How can I solve this ?

**Comment by ThatOneBro** [comment]
Can you try this on the canary build? 
```
bun upgrade --canary
```

I believe this issue was recently fixed and the fix should be available in the next release.

**Comment by Landris18** [comment]
`bun upgrade --canary` fixed the isssue.

Thank you very much, have a nice day
