### ISSUE TITLE
Bun test fails `toEqual` test for non-empty array passed through `produce` from `immer`

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/bun#2417]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Reproducible repo [here](https://github.com/jakeboone02/bun-test-immer-toequal/blob/main/src/testrun.ts#L6-L10). Run `bun test bun.test & bunx jest jest` to see the result of both bun:test and Jest for the same test suite.

Short version:

```ts
import { produce } from "immer";

test('fails in bun but not jest', () => {
  const array1 = [""];
  const array2 = [""];
  expect(produce(array1, a => a)).toEqual(array2);
});
```

### What is the expected behavior?

bun:test's `toEqual` should behave the same as Jest's `toEqual` even when `immer` is involved.

### What do you see instead?

bun:test always fails a `toEqual` comparison between two non-empty arrays if exactly one of the arrays is passed through `immer`'s `produce` function, even if the `produce` function simply returns the draft unchanged.

If the arrays are empty, or if they are _both_ passed through `produce` first, the test will pass in both bun:test and Jest.

**Comment by dylan-conway** [comment]
Thanks for filing

This is likely an edgecase in our deep equals function that we haven't handled yet

**Comment by jakeboone02** [comment]
I was able to narrow this down. It happens when an array is passed through the `Object.preventExtensions()` method, which is (effectively?) called when `Object.freeze()` is called.

Once an array has been through `preventExtensions`, `Bun.deepEquals` fails to match it with an equivalent array. If both arrays have been through `preventExtensions`, they will match.

## Minimal reproduction

```ts
const a = [1];
const b = [1];
Bun.deepEquals(a, b);           // true (neither is "frozen")
Object.preventExtensions(b);    // [ 1 ]
Bun.deepEquals(a, b);           // false (`b` is now "frozen" but `a` is not)
Object.preventExtensions(a);    // [ 1 ]
Bun.deepEquals(a, b);           // true (both are now "frozen")
```

This only happens with arrays, not with objects:

```ts
const a = { foo: 'bar' };
const b = { foo: 'bar' };
Bun.deepEquals(a, b);           // true (neither is "frozen")
Object.preventExtensions(b);    // { foo: 'bar' }
Bun.deepEquals(a, b);           // true <<DIFFERENCE>> (`b` is now "frozen" but `a` is not)
Object.preventExtensions(a);    // { foo: 'bar' }
Bun.deepEquals(a, b);           // true (both are now "frozen")
```

## Immer

By default, `immer`'s `produce` method will recursively `Object.freeze` (aka "deep freeze") an object/array after its draft is finalized. One workaround in the context of `bun test` is to call `setAutoFreeze(false)` like this:

```ts
import { setAutoFreeze, produce } from "immer";
const immer = produce((d) => d);
const a = [1];
const b = [1];

Bun.deepEquals(a, immer(b));    // false

setAutoFreeze(false);           // <-- workaround

const c = [1];
const d = [1];
Bun.deepEquals(c, immer(d));    // true
```

I was able to get my tests running with this setup file:

```ts
import { setAutoFreeze } from 'immer';
setAutoFreeze(false);
```

...called with the `--preload` flag like this:

```shell
bun test --preload ./bunTestSetup.ts
```
