### ISSUE TITLE
BusError at 5100912640/SegmentationFault at 10

### ISSUE THREAD

**Issue by n1ru4l** [oven-sh/bun#242]
Reproduction:

```bash
git clone https://github.com/dotansimha/graphql-yoga.git
cd graphql-yoga
git checkout bun-compat
yarn # install deps/setup workspace
# start the HTTP server
bun examples/bun/index.ts
# now visit localhost:3000 in your browser
```

Once you visit `localhost:3000`, the following error occurs and the server exits:

```
laurinquast@Laurins-MBP graphql-yoga % bun examples/bun/index.ts                                   

BusError at 5100912640


–––– bun meta ––––
Bun v0.1.1 macOS Silicon 21.3.0
AutoCommand: 
Elapsed: 19284ms | User: 146ms | Sys: 222ms
RSS: 1.14GB | Peak: 1.14GB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

Sometimes you also get the following error:

```
laurinquast@Laurins-MBP graphql-yoga % bun examples/bun/index.ts

SegmentationFault at 10


–––– bun meta ––––
Bun v0.1.1 macOS Silicon 21.3.0
AutoCommand: 
Elapsed: 3653ms | User: 107ms | Sys: 99ms
RSS: 0.51GB | Peak: 0.51GB | Commit: 67.11MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by Jarred-Sumner** [comment]
I believe this is fixed, but I'm honestly not sure

Can you leave a comment if it's still happening?

**Comment by ardatan** [comment]
Yes it looks fixed! Thanks!
Now as part of our new [GraphQL Yoga v3 Roadmap](https://github.com/dotansimha/graphql-yoga/issues/1358) which is almost done with fully working Bun support , the new version has an official Bun support thanks to our new server adapter library `@whatwg-node/server` that allows you to implement servers in platform agnostic way using Fetch API;
https://the-guild.dev/blog/fetch-for-servers

**Comment by ardatan** [comment]
Bad news :/ now we have a new issue in the latest release;
https://github.com/dotansimha/graphql-yoga/actions/runs/3085570494/jobs/4989009800#step:8:75
But it works fine in `v0.1.10`

**Comment by Jarred-Sumner** [comment]
Are you setting a `hostname`? I just pushed a fix for that. For now, try omitting a hostname or upgrading to the canary build.

**Comment by ardatan** [comment]
Yes I was doing that and it worked after removing it! Thanks for the tip and your awesome effort on this project!
