### ISSUE TITLE
Invalid console.log() of InvalidDate

### ISSUE THREAD

**Issue by yhdgms1** [oven-sh/bun#2422]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Run the code

```ts
console.log(new Date(1679142083813))
console.log(new Date("1679142083813"))
```

### What is the expected behavior?

InvalidDate is shown like `Invalid Date`

### What do you see instead?

InvalidDate is shown like `ul`

![image](https://user-images.githubusercontent.com/44583679/226106121-b8f40132-0dff-4f1f-a3f6-f72802f0172b.png)

**Comment by Jarred-Sumner** [comment]
Fixed in #2474
