### ISSUE TITLE
docs confusion + `proc.stdin.flush()` bug

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#2423]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 6.1.19_1 x86_64 unknown

### What steps can reproduce the bug?

I wrote 2 identical code ( python and ts )

py
```py
import subprocess

sub_proc = subprocess.Popen(["cat"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)

while True:
    try:
        sub_proc.stdin.write((input(">> ") + "\n").encode())
    except:
        exit(0)
    sub_proc.stdin.flush()

    output = sub_proc.stdout.readline()

    print(output.decode().strip())
```

ts
```ts
import { spawn } from "bun";

const proc = spawn(["cat"], { stdin: "pipe", stdout: "pipe" });

while (true) {
    try {
        proc.stdin.write(prompt(">>") + "\n");
    } catch (e) {
    }
    proc.stdin.flush();

    const output = await new Response(proc.stdout).text(); 
    console.write(output);
}
```

### What is the expected behavior?

Python:
```
>> Hello
Hello
>> World
World
```
Bun:
```
>> Hello
Hello
>> World
World
```

### What do you see instead?

Python:
```
>> Hello
Hello
>> World
World
```
Bun:
```
>> Hello
World
```

### Additional information

When i add `proc.stdin.end()` right under `proc.stdin.flush()` it sends the input but then i can't send anything

About the docs part
![obrázok](https://user-images.githubusercontent.com/64907994/226117353-45dbb85c-738f-4db9-b5ed-0977dcceab34.png)
It says that `.flush()` sends the data but nothing happens, only after `.end()`
I thought that `.end()` can be used when i don't need to send anything to `stdin`

**Comment by Jarred-Sumner** [comment]
`proc.stdout` is a `ReadableStream`. Once closed, `ReadableStream` cannot be opened again

`await new Response(proc.stdout).text()` reads the stream until the end

For this case, you want something like

```js
import { spawn } from "bun";

const proc = spawn(["cat"], { stdin: "pipe", stdout: "pipe" });
const reader = proc.stdout.getReader();
while (true) {
    try {
        proc.stdin.write(prompt(">>") + "\n");
    } catch (e) {
    }
    proc.stdin.flush();

    const {value: output, done} = await reader.read();
    if (done) break;
    console.write(output);
}
```

**Comment by Jarred-Sumner** [comment]
@colinhacks we should document usage better

**Comment by LowByteFox** [comment]
Thanks, the code works fine :+1:
