### ISSUE TITLE
Implement `node:cluster` module

### ISSUE THREAD

**Issue by Tushar-Chavan14** [oven-sh/bun#2428]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Linux 6.2.0-76060200-generic x86_64 x86_64

### What steps can reproduce the bug?

bun i rate-limiter-flexible

import { RateLimiterMemory } from "rate-limiter-flexible";

const rateLimiter = new RateLimiterMemory({
  points: 5,
  duration: 120,
});

**Comment by Jarred-Sumner** [comment]
We haven't implemented the Node.js `cluster` module yet.

**Comment by ThatOneCalculator** [comment]
Is there currently any other way to do multiprocessing/multithreading with bun? This seems like it should be a very high priority item to support.

**Comment by xb1itz** [comment]
+1 on this. The lack of `node:cluster` implementation is probably the main reason we are not switching to Bun right now.

**Comment by CharnSrinivas** [comment]
> +1 on this. The lack of `node:cluster` implementation is probably the main reason we are not switching to Bun right now.
Same here i am shifting back to node since i get know that `node:cluster` is not available yet

**Comment by melroy89** [comment]
I got indeed:

```
error: Could not resolve Node.js builtin: "cluster". To use Node.js builtins, set target to 'node' or 'bun'

const cluster = require('cluster')
```

I was very surprised to see this error. EDIT: I know `cluster` is not yet implemented. But then don't call it bun 1.0 yet.

**Comment by joshholly** [comment]
I ran bun --bun run dev to run my nextJS app. And I got this exact error.

**Comment by ThatOneCalculator** [comment]
Well, `node:cluster` isn't implemented yet, so that's why you're seeing the error.

**Comment by ElYaiko** [comment]
+1

**Comment by masfahru** [comment]
For now (Bun v.1.0.3), I can imitate the behavior of the `node:cluster` in Bun to spawn as many server instances as the number of CPU cores, using this script.

spawn.ts
```typescript
import os from "node:os";

const numCPUs = os.cpus().length;
for (let i = 0; i < numCPUs; i++) {
  Bun.spawn(["bun", "index.ts"], {
    stdio: ["inherit", "inherit", "inherit"],
    env: { ...process.env },
  });
}
```

index.ts
```typescript
Bun.serve({
  port: 8080,
  reusePort: true, // allow Bun server instances to use same port 
  fetch(req: Request) {
    // ...
```

run `bun spawn.ts`

**Comment by calebeaires** [comment]
@masfahru,

I performed the test and observed that the process ID remains the same every time I access the endpoint and print it. It appears that the access point is not redistributing properly.


```js
 if (process.pid) {
            console.log(process.pid);
 }

```



index.ts

```js

const server = Bun.serve({
    port: 3000,
    // @ts-ignore
    reusePort: true, // allow Bun server instances to use same port
    fetch(request) {
        if (process.pid) {
            console.log(process.pid);
        }
        return new Response("Welcome to Bun!");
    },
});

console.log(`Listening on localhost:${server.port}`);
```

cluster.ts
```js

import os from "node:os";

const numCPUs = os.cpus().length;
for (let i = 0; i < numCPUs; i++) {
    Bun.spawn(["bun", "index.ts"], {
        stdio: ["inherit", "inherit", "inherit"],
        env: { ...process.env },
    });
}
```

**Comment by masfahru** [comment]
@calebeaires 

> [SO_REUSEPORT is a builtin way to do load balancing, but it only really works properly on Linux](https://github.com/oven-sh/bun/issues/1443#issuecomment-1299274295).

Sorry, I don't know how load balancing works in Bun. To fulfill my curiosity about Bun server performance, I have tested the script in the [TechEmpower Framework Benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/commit/9c5800eaa78ee4fd4aab46953dac34ae3aec143b), and the result is amazing. Bun is able to serve up to 2.7M requests per second for plain text test.

![image](https://github.com/oven-sh/bun/assets/92277627/2d15af1e-2c08-4bf9-9c80-91a5206a8d6a)
[https://www.techempower.com/benchmarks/#section=test&runid=235acf72-7de8-4f61-baca-36c2df35a5c0&test=plaintext&l=zik0zj-33z](https://www.techempower.com/benchmarks/#section=test&runid=235acf72-7de8-4f61-baca-36c2df35a5c0&test=plaintext&l=zik0zj-33z)

**Comment by calebeaires** [comment]
@masfahru, you're right. I've tested in a linux machine and works like a charm.

**Comment by ThatOneCalculator** [comment]
@calebeaires Would you mind sharing the details on what hardware/setup was used to achieve those numbers?

**Comment by calebeaires** [comment]
On M1 Mac OS 8 cores, it does not work. On linux, Ubuntu 22, 2 cores I could get a good result. Sending concurrent requests to Bun server that console log the process.id numbers, we get different results.

**Comment by ednt** [comment]
> +1 on this. The lack of `node:cluster` implementation is probably the main reason we are not switching to Bun right now.

THIS!

**Comment by CsVeryLoveXieWenLi** [comment]
没有像Nodejs那样的多进程/线程，我觉得这应该是一个优先级很高的问题，并且应该写到示例文档里，我认为应该如此，毕竟这是一个性能相关的问题。我看了一下回复列举的代码，等会试试看有没有效果。

Google Machine Translate -> There are no multi-processes/threads like Nodejs. I think this should be a high priority issue and should be written into the sample documentation. I think it should be so. After all, this is a performance related issue. I took a look at the code listed in the reply and will try it later to see if it has any effect.

**Comment by Matthew-Tersigni** [comment]
+1 I Can't fully convert my node apps to bun without this feature.

**Comment by arbile26** [comment]
I do wait for this feature in order to switch to bun on all my node apps.

**Comment by ThatOneCalculator** [comment]
Can we please keep this thread productive, such as discussing potential implementations?

**Comment by ndaidong** [comment]
I'm looking forward to seeing this feature implemented in Bun.

**Comment by ganeshkbhat** [comment]
+1 for this.

I am also recommend implementing `cluster_thread` module which is genuinely a good starting point for creating clusters of threads like clusters of processes in node.js. Currently a multi-threading option is a little buggy. There is no random round robin as well in Windows due to absence of `file descriptor` module [presumed - check] in windows environment.

This is the Node.js Suggestion recommendation. https://github.com/nodejs/node/issues/48350


> @masfahru,
> 
> I performed the test and observed that the process ID remains the same every time I access the endpoint and print it. It appears that the access point is not redistributing properly.
> 
> ```js
>  if (process.pid) {
>             console.log(process.pid);
>  }
> ```
> 
> index.ts
> 
> ```js
> const server = Bun.serve({
>     port: 3000,
>     // @ts-ignore
>     reusePort: true, // allow Bun server instances to use same port
>     fetch(request) {
>         if (process.pid) {
>             console.log(process.pid);
>         }
>         return new Response("Welcome to Bun!");
>     },
> });
> 
> console.log(`Listening on localhost:${server.port}`);
> ```
> 
> cluster.ts
> 
> ```js
> import os from "node:os";
> 
> const numCPUs = os.cpus().length;
> for (let i = 0; i < numCPUs; i++) {
>     Bun.spawn(["bun", "index.ts"], {
>         stdio: ["inherit", "inherit", "inherit"],
>         env: { ...process.env },
>     });
> }
> ```

**Comment by rgillan** [comment]
Actually the feature for Bun.serve to allow port reuse (reusePort:true) and simple Bun.spawn of a number of processes works a treat.  We have refactored a node:cluster websocket application using this simple approach and found it to be quite straightforward (on Linux at least), sharing both 443 and 80 (hsts).  The ipc comms makes it a pretty simple drop in replacement with some simple rewrites. Subsequent websocket connections are load balanced by the OS in round robin. Still need to load test but functional.

**Comment by chlorophant** [comment]
> We haven't implemented the Node.js `cluster` module yet.

Is there a timeline on this? Would love to have this feature!

**Comment by isaadabbasi** [comment]
Just came to this thread to tell, all the benchmark blogs n videos are comparing nodejs (clustered), Go (which is natively clustered) vs Bun. Though Bun outperform node on single process mode but its really not good for general sentiment build up. 
It'd be really hard to educate the masses on fair grounds of comparison. If we could implement clustered mode that would be really great.

**Comment by antn9x** [comment]
I hope this feature release soon.

**Comment by waghanza** [comment]
> Just came to this thread to tell, all the benchmark blogs n videos are comparing nodejs (clustered), Go (which is natively clustered) vs Bun. 

Not really https://web-frameworks-benchmark.netlify.app/result?l=javascript is comparing node vs bun on with clustering for both of them. Clustering could be done, but it depends ... It could be useless, with some architecture, to have clustering mode

**Comment by rgillan** [comment]
So in my opinion having used node:cluster for many years (and the cluster module pre integration), the ability to reuse sockets in the Bun.serve implementation pretty much removes the need for node:cluster support in Bun for _some_ of the use cases.  The IPC channel support is identical syntax, and things like http/s and websocket server port sharing just work out of the box on Linux.  Spawn separate workers and reuse the ports.  Reach out if you need any guidance but we've pretty much deprecated the need for the cluster capability with what Bun already has implemented.  Cheers Rob

**Comment by AlexanderEpolite** [comment]
> So in my opinion having used node:cluster for many years (and the cluster module pre integration), the ability to reuse sockets in the Bun.serve implementation pretty much removes the need for node:cluster support in Bun for most of the use cases.  The IPC channel support is identical syntax, and things like http/s and websocket server port sharing just work out of the box on Linux.  Spawn separate workers and reuse the ports.  Reach out if you need any guidance but we've pretty much deprecated the need for the cluster capability with what Bun already has implemented.  Cheers Rob

What if I want to have multiple instances of smtp-server running on port 25?  Only other option would be nginx, but that comes with its own set of issues.

**Comment by rgillan** [comment]
> > So in my opinion having used node:cluster for many years (and the cluster module pre integration), the ability to reuse sockets in the Bun.serve implementation pretty much removes the need for node:cluster support in Bun for most of the use cases.  The IPC channel support is identical syntax, and things like http/s and websocket server port sharing just work out of the box on Linux.  Spawn separate workers and reuse the ports.  Reach out if you need any guidance but we've pretty much deprecated the need for the cluster capability with what Bun already has implemented.  Cheers Rob
> 
> What if I want to have multiple instances of smtp-server running on port 25? Only other option would be nginx, but that comes with its own set of issues.

Understood, and yes you'd need to handle that externally (nginx, possibly pm2 would be another option but not sure) Another approach we have done in the nodejs world is have a single process handle the raw port, then workers doing what's needed.  I've modified my comment to say _some_ rather than _most_

**Comment by fahidmohammad** [comment]
I know this thread is dated, but I recently encountered a similar scenario and have done a Nodejs inspired implementation to replicate the cluster process.

`import os from "node:os";
import path from "node:path";

type Subprocess = ReturnType<typeof Bun.spawn>;

let shouldRespawn = true;
const workers: Set<Subprocess> = new Set();
const indexPath = path.resolve("src/index.ts");
const numCPUs = os.cpus().length;

function spawnWorker() {
    const proc = Bun.spawn(["bun", indexPath], {
        stdio: ["inherit", "inherit", "inherit"],
        env: { ...process.env },
        onExit(proc, exitCode) {
            console.log(`Worker ${proc.pid} exited with code ${exitCode}`);
            workers.delete(proc); // Remove from the set of active workers
            if (shouldRespawn) {
                console.log(`Respawning worker ${proc.pid}...`);
                setTimeout(spawnWorker, 1000);
            } else if (workers.size === 0) {
                console.log("All workers have been shut down. Exiting...");
                process.exit();
            }
        },
    });

    workers.add(proc); // Add to the set of active workers
    console.log(`Spawned worker with PID ${proc.pid}`);
}

for (let i = 0; i < numCPUs; i++) {
    spawnWorker();
}

function shutdownWorkers() {
    shouldRespawn = false; // Prevent further respawning
    for (const worker of workers) {
        console.log(`Shutting down worker ${worker.pid}...`);
        worker.kill(); // Terminate the worker process
    }
}

// Listen for termination signals
process.on('SIGINT', () => {
    console.log('SIGINT signal received. Shutting down...');
    shutdownWorkers();
});

process.on('SIGTERM', () => {
    console.log('SIGTERM signal received. Shutting down...');
    shutdownWorkers();
});
` 

I've tested this in both linux and mac, seems efficient and does what it suppose to do. 

Open for feedback and any collaboration to enhance this further.

**Comment by Ivanmatthew** [comment]
> +1 on this. The lack of `node:cluster` implementation is probably the main reason we are not switching to Bun right now.

+1

> So in my opinion having used node:cluster for many years (and the cluster module pre integration), the ability to reuse sockets in the Bun.serve implementation pretty much removes the need for node:cluster support in Bun for _some_ of the use cases. The IPC channel support is identical syntax, and things like http/s and websocket server port sharing just work out of the box on Linux. Spawn separate workers and reuse the ports. Reach out if you need any guidance but we've pretty much deprecated the need for the cluster capability with what Bun already has implemented. Cheers Rob

The use-case would still be to reinforce Bun's statement of being a "drop-in" replacement for Node, since most of the functionality that entails the cluster module is apparently already implemented, I hope some of the code can be reused for a node:cluster module (mock?).

**Comment by snorremd** [comment]
> On M1 Mac OS 8 cores, it does not work. On linux, Ubuntu 22, 2 cores I could get a good result. Sending concurrent requests to Bun server that console log the process.id numbers, we get different results.

Just for any other MacOS user like me coming to this thread to find out why `reusePort` is not working. It seems this feature works different on older FreeBSD and Darwin than Linux [according to this StackOverflow thread](https://stackoverflow.com/questions/41247790/so-reuseport-on-macos-with-libuv). On MacOS the `SO_REUSEPORT` implementation does not round robin the TCP requests. Instead it sends the requests to the last process to attach to the socket.

Not sure if Darwin will ever implement this or not. So for the time being MacOS users will need to put a proxy in front of their Bun servers to support multiple process request handling.

**Comment by Bytedefined** [comment]
Would be great to see support sometime soon!

**Comment by elliotthill** [comment]
For a lot of us running regular servers, like ec2 instances, we cannot run Bun in production due to this. 

Yes its possible to rewrite your app to use bun.serve() or rearchitect it to run on single threaded containers, but thats not really a drop in replacement as is claimed. 

Given its the 12th most thumbs up'd issue out of ~2k, can it be added to the roadmap?

**Comment by mrtcmn** [comment]
This is power of the nodejs. I'll waiting node:cluster implemetation for migrate my all servers to bun.

**Comment by lodembeep** [comment]
What if you need clustering for tasks other than serving http requests ?

Clustering is important for non web tasks, i usually spawn workers on server side for CPU intensive tasks, nothing related to serving at all.

**Comment by Jarred-Sumner** [comment]
We are planning to implement node:cluster towards the end of this month.

**Comment by lodembeep** [comment]
> We are planning to implement node:cluster towards the end of this month.

Awesome !!! I will spread the word :)

**Comment by haimev** [comment]
cool! great news

**Comment by i8ramin** [comment]
Hello has anyone successfully been able to use pm2 with bun compiled node binary? i've tried many different commands and variations but cannot figure it out. any help would be greatly appreciated.

**Comment by techsin** [comment]
is it out?

**Comment by dienstbereit** [comment]
> Hello has anyone successfully been able to use pm2 with bun compiled node binary? i've tried many different commands and variations but cannot figure it out. any help would be greatly appreciated.

I assume that as soon as node:cluster is implemented, bun will also run with pm2 in cluster mode out-of-the-box. At least I hope so ;-)

**Comment by ajimix** [comment]
> We are planning to implement node:cluster towards the end of this month.

+1 if you are here in June or later, waiting for it to be implemented 😄

**Comment by Jarred-Sumner** [comment]
@nektro is working on this, please follow along in #11492

**Comment by lortmorris** [comment]
I need using clusters for s42-core.
When you think guys this features will be available?

**Comment by Jarred-Sumner** [comment]
Initial support for the `cluster` module will be part of the Bun v1.1.25 release, thanks to @nektro!

**Comment by dienstbereit** [comment]
Magnificent… thanks to @nektro  👏 Now I can finally go into production with my project 🤩

**Comment by censujiang** [comment]
Thank you bro!

**Comment by kravetsone** [comment]
It's happening! Thanks!

It would be nice if you provide somewhere in Documentation prons and cons of usage `node:cluster` or `reusePort: true`

**Comment by kravetsone** [comment]
> It's happening! Thanks!
> 
> It would be nice if you provide somewhere in Documentation prons and cons of usage `node:cluster` or `reusePort: true`

I guess also provide benchmarks of normal mode, cluster, reusePort will be great)

**Comment by rgillan** [comment]
Not sure it's up to the Bun team to recommend one way or another (cluster vs reusePort) but happy to share our experience.  We have been running two nodejs applications in production that rely upon the cluster functionality to spin up numbers of workers, each with high volume websocket servers (using the websocket module, not ws for performance).  One of these applications also serves http/s content.  These applications would happily service 16k concurrent connections and traffic per worker on nodejs.
One of the major attractions of Bun to us was the native integration of uWebsockets into the run time which itself is very high performance, so we no longer needed to use third party modules and the refactoring to Bun.serve was quite trivial and straightforward.  There's no additional layer of clustering code needed, and the sharing of the port is done at very low level in the OS not higher up in the node stack in my understanding.  We are achieving over 100k connections per worker with a very simple refactoring so Bun is a gamechanger for us.
Obviously the node:cluster module does more than just the http/websocket ports and is more generic, so the benefits will be down to how and what you need to run multiple workers for.

**Comment by Jarred-Sumner** [comment]
>  prons and cons of usage node:cluster or reusePort: true

Internally, cluster relies on reusePort: true, so it's mostly helpful for automatic restarts and integration with existing codebases relying on cluster

**Comment by msveshnikov** [comment]
I tried today my old nodejs code and everything works. Does it mean cluster was implemented recently? Code here:

import cluster from 'cluster';
import express from 'express';
import promBundle from 'express-prom-bundle';

const MAX_CPU = 4;

if (cluster.isPrimary) {
    console.log(`Master ${process.pid} is running`);

    for (let i = 0; i < MAX_CPU; i++) {
        cluster.fork();
    }
    const metricsApp = express();
    metricsApp.use('/metrics', promBundle.clusterMetrics());
    metricsApp.listen(6022);
    cluster.on('exit', (worker) => {
        console.log(`Worker ${worker.process.pid} died`);
        cluster.fork();
    });
} else {
    import('./app.js');
}
