### ISSUE TITLE
Path resolve SegmentationFault

### ISSUE THREAD

**Issue by promer94** [oven-sh/bun#243]
<img width="2424" alt="Screen Shot 2022-07-06 at 14 33 56" src="https://user-images.githubusercontent.com/15878786/177484447-2b289368-947c-47f1-8b9b-e95c650803a9.png">

bunfig.toml
```toml
framework = "next"
```

**Comment by zhuzilin** [comment]
This is now fixed by ignoring browser field in package.json when running with platform bun.
