### ISSUE TITLE
bun uninstall

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#2438]
### What is the problem this feature would solve?

- Allows uninstalling bun easily
- Allows for testing what errors a new developer who doesn't have bun installed would encounter

### What is the feature you are proposing to solve the problem?

- `bun uninstall`
- uninstall command is visible in the help me

### What alternatives have you considered?

- Searching "bun uninstall" on Google
- Using instructions from here: https://stackoverflow.com/questions/72989971/how-to-uninstall-bun

**Comment by Electroid** [comment]
We can add a section on the docs for it. We can't make a `bun uninstall`, uninstall bun, because it has parity with `npm uninstall`.

**Comment by Electroid** [comment]
We have documented this here: https://bun.sh/docs/installation#uninstall
