### ISSUE TITLE
Cluster nodejs process.binding fail

### ISSUE THREAD

**Issue by Douglasgomestosta** [oven-sh/bun#2454]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 5.4.0-144-generic x86_64 x86_64

### What steps can reproduce the bug?

insert const cluster = require("cluster") in the code.

### What is the expected behavior?

run code in multiple threads

### What do you see instead?

9 |  * Module dependencies.
10 |  */
11 | 
12 | var EventEmitter = require('events').EventEmitter
13 |   , spawn = require('child_process').spawn
14 |   , binding = process.binding('net')
                  ^
TypeError: process.binding is not supported in Bun. If this breaks a library you're using, please file an issue at https://bun.sh/issues and include a reproducible code sample.
      at /home/douglas/Documentos/GitHub/socialfan/node_modules/cluster/lib/worker.js:14:14
      at /home/douglas/Documentos/GitHub/socialfan/node_modules/cluster/lib/master.js:12:4
      at /home/douglas/Documentos/GitHub/socialfan/node_modules/cluster/lib/cluster.js:12:4
      at /home/douglas/Documentos/GitHub/socialfan/node_modules/cluster/index.js:2:7
      at /home/douglas/Documentos/GitHub/socialfan/bun/main.js:3:6

### Additional information

more information to Cluster module
https://nodejs.org/api/cluster.html
https://www.coderrocketfuel.com/article/run-a-node-js-http-express-js-server-on-multiple-cpu-cores

when using "const cluster = require('node:cluster');" instead of "const cluster = require("cluster")" show the message  "error: Cannot find package "node:cluster" from "/home/douglas/Documentos/GitHub/socialfan/bun/main.js"

**Comment by Electroid** [comment]
We need to implement `cluster` first. #2428
