### ISSUE TITLE
bun bun.lockb absolute path doesn't work

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#2455]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 6.1.20_1 x86_64 unknown

### What steps can reproduce the bug?

```bash
$ bun /absolute/path/to/bun.lockb
```

### What is the expected behavior?

output readable version of bun.lockb
```bash
bun bun.lockb
```

### What do you see instead?

lockfile not found:

### Additional information

I went to /
and tried both
`bun home/jani/devel/js/buchta/bun.lockb`
this one worked
but this one
`bun /home/jani/devel/js/buchta/bun.lockb`
didn't

**Comment by Jarred-Sumner** [comment]
The bug is probably here:

https://github.com/oven-sh/bun/blob/a6e12fc90309546440986613afb41106059aab74/src/install/lockfile.zig#L854-L855

**Comment by LowByteFox** [comment]
I found a way around it by going into / and removing `/` from string in plugin but it isn't the best solution, i'll test `node_modules.bun` as well

**Comment by LowByteFox** [comment]
`node_modules.bun` works fine

**Comment by LowByteFox** [comment]
It is still happening. Not to mention when there is too much packages, it doesn't write everything

**Comment by Electroid** [comment]
Tested in Bun v1.0.7, this has been fixed. If you can still reproduce this issue, please re-open this issue and we'll investigate.
