### ISSUE TITLE
Low-prio: Copy-paste leftover in src/emcc_main.c

### ISSUE THREAD

**Issue by floooh** [oven-sh/bun#246]
Found a little leftover here while browsing the code ;)

https://github.com/Jarred-Sumner/bun/blob/8c1157be229137963d1dd513d389ae181db00821/src/emcc_main.c#L17

**Comment by Electroid** [comment]
Nice catch :) Closing though since it's a small priority thing.

**Comment by Jarred-Sumner** [comment]
Some of the symbols from emcc is used in the (yet to be released) wasm build of bun to support using mimalloc in wasm
