### ISSUE TITLE
`bun install` fails to git clone private Enterprise GitHub dependency

### ISSUE THREAD

**Issue by privatenumber** [oven-sh/bun#2464]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.3.0 x86_64 i386

### What steps can reproduce the bug?

Install with the following `package.json`  where "@org/website-i18n" points to a private GitHub repo.

```json
{
  "dependencies": {
    "@org/website-i18n": "github:org/website-i18n#branch-name"
  }
}
```

### What is the expected behavior?

For it to install with the appropriate Git credentials.

### What do you see instead?

It fails.

Also note, the first error message truncates the package name for some reason.

```
$ bun i --verbose
bun install v0.5.8 (1a25af5e)
  🔍 Resolving [1/1]
error: InstallFailed cloning repository for @org/website-i1

error: "git clone" for "@org/website-i18n" failed


error: "git clone" for "@org/website-i18n" failed
```

### Additional information

- Passing in `--verbose` doesn't provide me with more information. Here, I'm interested in seeing the `git clone` command & error.
- I'm not certain this error is as a result of the repository being private. The org is an enterprise org, so it might be that the installation URL doesn't follow the typical GitHub git URL.

	The git clone command looks like this:
	```
	git clone org-12345678@github.com:org/website-i18n.git
	```

**Comment by Jarred-Sumner** [comment]
github: syntax is only supported for public repositories in Bun. We use the GitHub tarball api for these (I think npm does as well) 

We should make the error message better though, and suggest to try with a git+ssh URL

**Comment by privatenumber** [comment]
Since the error message says "git clone" failed I think it's happening here:
https://github.com/oven-sh/bun/blob/732c5e7fa9b0bb89938ca001749a13501386485e/src/install/repository.zig#L180

----

I was just about to file a bug for the GitHub tarball API url. It doesn't seem to work for private repositories either:

```
bun install v0.5.8 (1a25af5e)
  🔍 Resolving [1/1]
GET https://api.github.com/repos/org/analytics-js/tarball/v0.8.7 - 404
error: analytics-js@github:org/analytics-js#v0.8.7 failed to resolve
```

I think an API token will need to be passed in to access private repositories via GitHub API. It works with npm and I haven't configured a token so I think they're using the Git+SSH method.
