### ISSUE TITLE
Support `@aws-sdk` packages

### ISSUE THREAD

**Issue by daniel-price** [oven-sh/bun#2465]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.3.0 x86_64 i386

### What steps can reproduce the bug?

Create the repo with dependency
```
mkdir bun_repo
cd bun_repo
bun i @aws-sdk/client-cloudformation
echo 'import { CloudFormationClient } from "@aws-sdk/client-cloudformation"; const cf = new CloudFormationClient({});' > index.ts
bun index.ts
```

This results in the first error:
```
error: Could not resolve: "http2". Maybe you need to "bun install"?

import { constants } from "http2";
                          ^
bun_repo/node_modules/@aws-sdk/node-http-handler/dist-es/node-http2-handler.js:3:27 146
```

We can get around this by installing http2
```
bun i http2
bun index.ts
```

But this results in another error:
```
1 | import { EndpointError } from "../types";
2 | import { callFunction } from "./callFunction";
   ^
ReferenceError: Cannot access uninitialized variable.
      at bun_repo/node_modules/@aws-sdk/util-endpoints/dist-es/utils/evaluateExpression.js:2:0
```

### What is the expected behavior?

These errors should not be shown (they aren't with node)

### Additional information

Thanks for your help - I really love bun so far!

**Comment by Electroid** [comment]
Thanks for reporting this issue. Yes, we need to implement the `http2` module, which is being tracked here: #887

**Comment by birkskyum** [comment]
For some reason I don't get this http2 error with "@aws-sdk/client-cloudformation": "^3.398.0", and bun 0.8. When logging the created cf object it also mentions:

```sh
    requestHandler: {
      metadata: {
        handlerProtocol: "http/1.1"
      },
      configProvider: Promise { <pending> },
      resolveDefaultConfig: [Function: resolveDefaultConfig],
      destroy: [Function: destroy],
      handle: [Function: AsyncFunction]
    },
```

@daniel-price  is this working for you now?

**Comment by o-alexandrov** [comment]
@birkskyum just wondering:
- are all `@aws-sdk/*` work for you w/ bun 0.8, or just `@aws-sdk/client-cloudformation`?

**Comment by daniel-price** [comment]
@birkskyum I've just tried my reproduction and it now works. I will close this issue now, thanks.
