### ISSUE TITLE
NPM `lru-cache` regression in Bun v0.5.7 due to `timeout.unref()`

### ISSUE THREAD

**Issue by spiffytech** [oven-sh/bun#2466]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux (Fedora 37, kernel 6.1.18-200)

### What steps can reproduce the bug?

Beginning in Bun v0.5.7, the `lru-cache` NPM module no longer expires entries that exceed the cache TTL.

(TTL is  in milliseconds). The delayed `tryGet()` which should clearly be expired and print `Miss`, instead prints `Hit`.

In Bun v0.4.0, the delayed `tryGet()` correctly prints `Miss`.

```js
import LRU from "lru-cache";

const lru = new LRU({
  max: 3,
  ttl: 3,
});

const tryGet = () => {
  const value = lru.get("foo");
  if (value) {
    console.log("Hit");
  } else {
    console.log("Miss");
  }
};

lru.set("foo", "bar");
tryGet();
tryGet();

await new Promise((resolve) => setTimeout(resolve, 500));
tryGet();
```

### What is the expected behavior?

Cache items should `Miss` when expired.

### What do you see instead?

Cache items continue to `Hit` indefinitely.

### Additional information

`lru-cache` [will `unref` a timeout when possible](https://github.com/isaacs/node-lru-cache/blob/77e977f3dfe41edaa483bad7d2ae8b4d1f7e86f1/src/index.ts#L1118). If I delete the lines for the `unref` call, correct behavior is restored.

This suggests Bun's implementation of `timeout.unref()` (IIRC introduced in v0.5.7) is malfunctioning.

(The repro code works fine in Node.js, too).

**Comment by Jarred-Sumner** [comment]
yes, this is a bug

The bug is that unref is cancelling the timeout when I think it should instead be preventing the timeout from keeping the process alive.

**Comment by lnbc1QWFyb24** [comment]
Yeah I am finding that the `rate-limiter-flexible` and `node-cache` libraries are broken because of a timer issue which I suspect is due to this bug.

**Comment by gornostay25** [comment]
Any updates?

**Comment by gornostay25** [comment]
@spiffytech @Jarred-Sumner It seems to be working now, so we can close the issue
