### ISSUE TITLE
Feature request (Browser release)

### ISSUE THREAD

**Issue by frog-o** [oven-sh/bun#2471]
### What is the problem this feature would solve?

Portability and easy of install
One thing I can not understand is why people are not make a node,dónde,bunjs equivalent that you can run in a browser. I would like to see buns release a wasm build so that allow you to use typescript, bundler etc with not need a server. Typescript so far needs something running and installed.  If buns where able to run in a browser it would solve all that. From everything I read , zig is supposed to be easily be able to compile to wasm ;so in theory this should work.  I wanted to mention That I would like to see this for zig language also but I don't want a discord account or anything complicated like that IRC,mailinglist, etc.

### What is the feature you are proposing to solve the problem?

Portability and easy of install(what easier then no install)

### What alternatives have you considered?

Bable-standalone with packages from sky pack and unpkg

**Comment by pfgithub** [comment]
Node can run in the browser with webcontainers: https://webcontainers.io/ . I believe bun wants to support a wasm release eventually. I believe zig does too, their build process currently involves running a wasi build of the zig compiler, but they don't seem to distribute wasi binaries yet on their downloads page.

**Comment by Electroid** [comment]
We do not plan to support running Bun in the browser anytime soon.
