### ISSUE TITLE
Certificate expired 

### ISSUE THREAD

**Issue by johnnyreilly** [oven-sh/bun#2478]
### What platform is your computer?

N/A

### How did you attempt to install or upgrade?

GitHub Actions:

oven-sh/setup-bun@v1
  with:
    bun-version: latest

### What do you see instead?

Downloading a new version of Bun: https://bun.sh/download/latest/linux/x64?avx2=true&profile=false
certificate has expired
Waiting 13 seconds before trying again
certificate has expired
Waiting 19 seconds before trying again
Error: Error: certificate has expired

https://github.com/johnnyreilly/blog.johnnyreilly.com/actions/runs/4515191076/jobs/7952173889

**Comment by Electroid** [comment]
This looks like an ongoing GitHub issue: https://news.ycombinator.com/item?id=35295216
