### ISSUE TITLE
nested .env not working

### ISSUE THREAD

**Issue by u007** [oven-sh/bun#248]
i have this .env file which uses other variable set in the .env itself
```
DB_USER=postgres
DB_PASS=xyz
DB_HOST=localhost
DB_PORT=5432
DB_NAME=db

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?pool_timeout=30&connection_limit=22"
```

**Comment by muhammedogz** [comment]
I had the same issue.

Bun can't handle replacing .env variables. 
It stays the same variable as given value.

**Comment by FinnRG** [comment]
@u007 Bun actually supports nested environment variables. You need to remove the curly braces for it to work:
```
DB_USER=postgres
DB_PASS=xyz
DB_HOST=localhost
DB_PORT=5432
DB_NAME=db

DATABASE_URL="postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?pool_timeout=30&connection_limit=22"
```

But we should probably support the curly braces syntax too.

**Comment by u007** [comment]
Sorry needed curly bracket for prisma orm to work

**Comment by tapsu01** [comment]
Hi @u007, how do you use Prisma with bun? I'm getting the error "Could not resolve: "stream/web"." when trying to use Prisma with Bun

**Comment by ekil1100** [comment]
I am new to Zig, but I am willing to help on this, give it a try.
