### ISSUE TITLE
Process exit callback function is not executed

### ISSUE THREAD

**Issue by mx369** [oven-sh/bun#2480]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```js
//test.js
process.on('exit', (code) => {
    console.log(`About to exit with code: ${code}`);
});
```
> node ./src/node.js
About to exit with code: 0

> bun ./src/node.js
//No output

**Comment by Jarred-Sumner** [comment]
yeah this isn't implemented

**Comment by Electroid** [comment]
This was implemented since this issue was created, tested using Bun v1.0.7.

```
❯ cat exit.js
process.on('exit', (code) => {
    console.log(`About to exit with code: ${code}`);
});
```

```
❯ bun exit.js
About to exit with code: 0
```
