### ISSUE TITLE
There is zero documentation about the bundler

### ISSUE THREAD

**Issue by TheDirigible** [oven-sh/bun#2483]
### What is the type of issue?

Documentation is missing

### What is the issue?

There is zero documentation about the bundler.  Just the blurb "bun is a .. bundler"
Running it I see "bun bun" which just sits there.
Running "bun bun --platform node src/main.ts" I was able to get it to build "node_modules.bun" which is weird.
Trying to run that I got "error: Failed to run "node_modules.bun" due to error InvalidExe"

How do I replace webpack with this?  How do you make it support scss?  How do I specify the html template to use?

**Comment by paperclover** [comment]
The `bun bun` command is being rewritten, which is why there is no documentation on how to use the legacy version. #2312 has more information on the new version but it's not far enough for real world usage yet.

**Comment by gaurishhs** [comment]
> Can I work on this?

Sure you can, Check the jarred/new-bundler branch
