### ISSUE TITLE
Support for executing code provided right from a flag

### ISSUE THREAD

**Issue by fabiospampinato** [oven-sh/bun#2505]
### What is the problem this feature would solve?

Node supports executing code like this:

```
node -e '1+2'
```

### What is the feature you are proposing to solve the problem?

Adding something like:

```
bun -e '1+2'
```

Though I see "e" is already used for something else. Maybe that should be freed first to better align with Node.

### What alternatives have you considered?

Executing a file.

**Comment by Electroid** [comment]
Duplicate of #1932
