### ISSUE TITLE
typescript compile errors in `bun-types`

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#2511]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. run `bun add bun-types`
2. create a tsconfig file including them:
   ```json
    {
        "compilerOptions": {
            "types": ["bun-types"]
        },
        "include": ["main.ts"]
    }
    ````
3. run `bun run tsc`

### What is the expected behavior?

no compile errors

### What do you see instead?

```
$ bun run tsc
node_modules/bun-types/types.d.ts:622:13 - error TS2300: Duplicate identifier 'require'.

622 declare var require: NodeJS.Require;
                ~~~~~~~

node_modules/bun-types/types.d.ts:2443:18 - error TS2300: Duplicate identifier 'require'.

2443 declare function require(path: string): import(path);
                      ~~~~~~~

node_modules/bun-types/types.d.ts:2443:48 - error TS1141: String literal expected.

2443 declare function require(path: string): import(path);
                                                    ~~~~

node_modules/bun-types/types.d.ts:2443:48 - error TS2749: 'path' refers to a value, but is being used as a type here. Did you mean 'typeof path'?

2443 declare function require(path: string): import(path);
                                                    ~~~~


Found 4 errors in the same file, starting at: node_modules/bun-types/types.d.ts:622
```

### Additional information

typescript 5.0.2

**Comment by colinhacks** [comment]
You're seeing conflicts between `bun-types` and `@types/node`. We necessarily declare some of the same global variables, like `require`. If you have `@types/node` in your package.json, removing it should solve the problem. It's also possible it's being installed as a dependency of another package, which makes things trickier. In that case, running `bun pm ls --all` should help you figure out why it's being installed.

**Comment by DetachHead** [comment]
as far as i can tell these conflicts are not related to `@types/node`. the first two errors are caused by the fact that `bun-types` contains two separate declarations of `require`:
```ts
/**
 * NodeJS-style `require` function
 *
 * Internally, uses `import.meta.require`
 *
 * @param moduleId - The module ID to resolve
 */
declare var require: NodeJS.Require;
```
```ts
declare function require(path: string): import(path);
```

 the second two errors are caused by the invalid return type `import(path)`. instead it should be `import('path')`

**Comment by DetachHead** [comment]
my bad, i was accidentally using an ancient version of `bun-types` (0.1.11)
