### ISSUE TITLE
Shebang on CRLF file accessed through a symlink throws error

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/bun#2516]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install a package that defines a `bin` script, where the script file has CRLF line endings and begins with the `node` shebang:

```
#!/usr/bin/env node
```

Minimal reproduction: https://github.com/jakeboone02/bun-shebang-crlf-bug

1. `git clone https://github.com/jakeboone02/bun-shebang-crlf-bug.git`
2. `cd bun-shebang-crlf-bug`
3. `bun link` to register the package
4. `bun link bun-shebang-crlf-bug` to create symlinks in `./node_modules`
5. `bunx buncrlfbug` or `bunx --bun buncrlfbug`

### What is the expected behavior?

The script should run as expected, either with a Node instance when run with `bunx` or with Bun when run with `bunx --bun`.

### What do you see instead?

```
/usr/bin/env: ‘node\r’: No such file or directory
error: "buncrlfbug" exited with code 127
```

### Additional information

I first saw this issue when running

```sh
bunx jscodeshift ...
```

because `jscodeshift` ships with CRLF files. Converting all the `node_modules` files to LF avoids the problem (at least for the [example repo](https://github.com/jakeboone02/bun-shebang-crlf-bug)):

```sh
grep -lr $'\r$' node_modules | xargs -d '\n' sed -i 's/\r//g'
```

The CRLF issue does not seem to be a problem when symlinks are not involved.

**Comment by jakeboone02** [comment]
More information: The (as yet unreleased) workaround for a [similar issue with Yarn global installs](https://github.com/facebook/jscodeshift/issues/424) that [`jscodeshift` implemented a few weeks ago](https://github.com/facebook/jscodeshift/pull/549) is to add a space character after the shebang directive, before the carriage return.

In my testing with the same [example repo](https://github.com/jakeboone02/bun-shebang-crlf-bug), this is not an acceptable solution in Bun's case. It actually leads to separate, different problems with `bunx buncrlfbug` and `bunx --bun buncrlfbug`.

(I'm still not sure why they ship CRLF files in the first place, especially with a *nix-centric pragma like that.)

**Comment by controversial** [comment]
Seeing this issue with the `live-server` package

```
❯ bunx live-server
env: node\r: No such file or directory
```

**Comment by jakeboone02** [comment]
The execution also fails if there is a <kbd>Space</kbd> character after `node`.

**Comment by jakeboone02** [comment]
@paperdave / @Jarred-Sumner - It just occurred to me that this is probably going to be more of an issue once Bun is released with Windows support.

**Comment by paperclover** [comment]
<img width="440" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/ecdbcb12-1373-4640-92e7-e2656760a74f">

i don't think this is a bug in bun. does WSL allow npx to work here?

**Comment by paperclover** [comment]
<img width="414" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/2c2c99b9-1e8d-4338-b91d-8285bdca9908">


nevermind, this is a bug in linking itself not bunx. confirmed and reproduced on macos

**Comment by controversial** [comment]
<img width="406" alt="Screenshot 2024-01-09 at 12 29 00 PM" src="https://github.com/oven-sh/bun/assets/10377391/3c87649d-268a-4589-9df3-8912347fffbb">

I can confirm the behavior is inconsistent between npx and bunx on macOS (Bun 1.0.21; node 20.10.0; macOS 14.2.1; Darwin 23.2.0 arm64 arm)

**Comment by ghost** [comment]
Currently you can work around this by adding a `prepublishOnly` script to `package.json`:


```json
{
  "scripts": {
    "prepublishOnly": "dos2unix index.ts"
  }
}
```

**Comment by VigilioYonatan** [comment]
any update?

**Comment by jakeboone02** [comment]
@Jarred-Sumner / @dylan-conway I tested this with the latest build from #11866 and the results are the same, at least on Linux (WSL).

I think it's because the `if` block in commit c211140b1037ac3206b7224a23171e4a02c3ed07 limits the fix to Windows:

https://github.com/oven-sh/bun/blob/da27f2262216f287f4f5f98b66e0b3d82701b09c/src/install/bin.zig#L380-L397

Here's the script I used and the results. I couldn't get `bunx bun-pr 11886` to work on Windows (that may be a "me" problem) but I'm guessing that this would pass.

```shell
bunx bun-pr 11886
git clone https://github.com/jakeboone02/bun-shebang-crlf-bug.git
cd bun-shebang-crlf-bug
bun link
bun link bun-shebang-crlf-bug
# the following commands all exit with code 127
bun-11886 x buncrlfbug
bun-11886 buncrlfbug
```

```
$ ./bun-issue-2516.sh
Searching GitHub for artifact bun-linux-x64 from PR #11886...
Choosing artifact from run that started Jun 26, 2024, 10:41:46 PM
Downloading bun-linux-x64 from PR #11886 - https://github.com/oven-sh/bun/actions/runs/9691311413
Downloaded to:

/home/jaboone/.bun/bin/bun-c211140b1037ac3206b7224a23171e4a02c3ed07-pr11886

To run the downloaded executable, use any of the following following commands:

bun-c211140b1037ac3206b7224a23171e4a02c3ed07-pr11886
bun-11886
bun-latest
Cloning into 'bun-shebang-crlf-bug'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
bun link v1.1.17 (bb66bba1)
Success! Registered "bun-shebang-crlf-bug"

To use bun-shebang-crlf-bug in a project, run:
  bun link bun-shebang-crlf-bug

Or add it in dependencies in your package.json file:
  "bun-shebang-crlf-bug": "link:bun-shebang-crlf-bug"
bun link v1.1.17 (bb66bba1)

installed bun-shebang-crlf-bug@link:bun-shebang-crlf-bug with binaries:
 - buncrlfbug

1 package installed [3.00ms]
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: ‘node\r’: No such file or directory
error: "buncrlfbug" exited with code 127
```

**Comment by dylan-conway** [comment]
It seems to work on my machine (although I don't like the visible extra newline it adds to `index.js`, might change this before the next release)
<img width="526" alt="Screenshot 2024-06-28 at 8 18 27 AM" src="https://github.com/oven-sh/bun/assets/35280289/d3865fa5-d8b2-4222-ad2d-0ba47e420d76">

Looks like the revision of bun you used for link is `bb66bba1`, can you try running bun-pr again? Commit should be `dcf14fa82`

**Comment by jakeboone02** [comment]
@dylan-conway oh you're right, and I'm an idiot. After I updated the `bun link` lines in the script to `bun-11886 link` it worked. Thanks!
