### ISSUE TITLE
bun install in pnpm/yarn workspaces

### ISSUE THREAD

**Issue by o-az** [oven-sh/bun#2517]
### What version of Bun is running?

0.5.8 to latest (0.6.7)

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

run `bun install` in pnpm workspaces or yarn workspaces.

### What is the expected behavior?

It should install dependencies and work for internal dependencies and external ones.

### What do you see instead?

```sh
bun install
```
```sh
[0.58ms] ".env"
bun install v0.5.8 (1a25af5e)


error: Workspace name "eslint-config-base" already exists
{
^
/project/package.json:1:1 0
```

in `package.json` I have `eslint-config-base`:

```json
{
  "name": "root",
  "devDependencies": {
    "@types/node": "^18.14.2",
    "eslint-config-base": "workspace:*",
    "tsconfig": "workspace:*",
    "typescript": "^4.9.5"
  }
}
```

This is the same if I'm using yarn workspaces (in that case it's `"eslint-config-base": "*"`.

It also happens when I don't have any dependencies in root `package.json`.

**Comment by 1tpp** [comment]
I found a solution for this issue. I tried creating a new folder called '.fix-bun-install' within the 'apps' directory and added a 'package.json' file with only the following content:
```
{
  "private": true
}
```

The directory structure would look like this:
```
├── apps/
│   ├── .fix-bun-install/
│   │   └── package.json
│   ├── elysia-backend/
│   │   └── ...
│   └── react-app/
├── packages/
├── package.json
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
└── turbo.json
```

**Comment by o-az** [comment]
@1tpp that's great news, I will try it today. 
Do you have local packages from ./packages installed in ./apps/*?

E.g., packages/tsconfig installed in apps/react-app?

**Comment by Jarred-Sumner** [comment]
This was fixed some time ago by @dylan-conway. Bun v1.1.8 - Bun v1.1.13 have had many improvements to workspaces support. Please let us know if you're still running into errors like `Workspace name "eslint-config-base" already exists`.
