### ISSUE TITLE
fish: Job 1, 'bun' terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by tsklxiv** [oven-sh/bun#252]
Hey there.

Recently I installed Bun using the shell command shown on the website, and when I tried to run Bun I got this error:

```
$ bun
fish: Job 1, 'bun' terminated by signal SIGILL (Illegal instruction)
```

Machine information from `neofetch` (if necessary):

```
OS: Pop!_OS 22.04 LTS x86_64
Host: Vostro 3550
Kernel: 5.17.15-76051715-generic
Packages: 4060 (dpkg), 76 (brew), 16 (flatpak), 40 (snap)
Shell: fish 3.3.1
Resolution: 1366x768
WM: sway
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: alacritty
Terminal Font: 'Cozette Vector'
CPU: Intel i3-2310M (4) @ 2.100GHz
GPU: Intel 2nd Generation Core Processor Family
Memory: 3102MiB / 3832MiB
```

**Comment by logikaljay** [comment]
I believe `bun` requires `avx2` support in your CPU.

The Intel i3-2310M does not have support for this.

More details here: https://github.com/Jarred-Sumner/bun/issues/154

**Comment by harish2704** [comment]
I got the same issue when I tired to run bun ( OS: Fedora 26 ).

![image](https://user-images.githubusercontent.com/1652903/177515454-5b22dbd9-7c7f-4569-a6e5-b6df78e59f51.png)

**Comment by omgbox** [comment]
Generally, CPUs with the commercial denomination Core i3/i5/i7/i9 support them, whereas Pentium and Celeron CPUs before Tiger Lake do not

**Comment by Guztaver** [comment]
This occurs because bunny only run in CPU's with `AVX2`, and the `AVX` support isn't launched yet.

See #67

**Comment by FinnRG** [comment]
@HoangTuan110 Please check if your CPU supports AVX2 by running ```grep avx2 /proc/cpuinfo```. If you don't see any output, please close this issue and follow the steps at #181.

**Comment by jnpn** [comment]
Owners should consider rewriting the README because the `avx` issue is not an Apple hardware exclusive. Maybe add a "hard requirement: avx2 processor" up top the install part.

**Comment by FinnRG** [comment]
> Owners should consider rewriting the README because the `avx` issue is not an Apple hardware exclusive. Maybe add a "hard requirement: avx2 processor" up top the install part.

There are already PR's to add this information to the README

**Comment by AndrusGerman** [comment]
[282](https://github.com/Jarred-Sumner/bun/issues/282) Here they presented an alternative solution, it seems good to test, but for big things it seems somewhat tedious and you cannot take advantage of the maximum performance of this project

**Comment by tsklxiv** [comment]
> @HoangTuan110 Please check if your CPU supports AVX2 by running `grep avx2 /proc/cpuinfo`. If you don't see any output, please close this issue and follow the steps at #181.

I ran `grep avx2 /proc/cpuinfo` now. Nothing found. Will close this issue.
