### ISSUE TITLE
node:http has missing ref/unref functions

### ISSUE THREAD

**Issue by krutoo** [oven-sh/bun#2524]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

Here's an example that shows Bun does not implement the ref and unref functions:
https://github.com/krutoo/bun-opentelemetry

According to @Jarred-Sumner on discord we ned to implement this functions:
https://discord.com/channels/876711213126520882/1091280232025182239/1091376674425274499

### What is the expected behavior?

Bun should implement ref/unref functions of http module

### What do you see instead?

Bun now not implemented ref/unref functions of http module

**Comment by krutoo** [comment]
looks like docs contain incorrect information about node:http module according this issue 
https://bun.sh/docs/runtime/nodejs-apis

**Comment by JuroOravec** [comment]
Came across this while trying to run [Crawlee/Apify](https://crawlee.dev/) (web scraping framework) via Bun (See discussion https://github.com/apify/proxy-chain/issues/521). This and the missing `fs.opendir` are blocking the adoption.
