### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by mihailnicamn** [oven-sh/bun#2526]
### What platform is your computer?

Darwin 19.6.0 x86_64 i386

### How did you attempt to install or upgrade?

installed, updated to cannary, downgraded to latest version

### What do you see instead?

<img width="521" alt="Screenshot 2023-04-01 at 00 11 03" src="https://user-images.githubusercontent.com/110503052/229232265-277b206d-35ef-4d96-9b68-07c0390d5c0d.png">
node on the left bun on the right 4 processes bun has 11 mb usage and node 33mb and 1 of the bun processes has 99 cpu usage 😅, while writting this the 2nd got into the same issue too 
<img width="503" alt="Screenshot 2023-04-01 at 00 13 40" src="https://user-images.githubusercontent.com/110503052/229232511-df33f462-766b-4cd7-a0e4-e0664f51982c.png">

the process is basic 1 simple setInterval printing it's own process.pid 

### Additional information

i don't know for sure what the issue might be, installed via sh script, just noticed it hit 100 real quick, like the meme goes 😅

**Comment by Electroid** [comment]
Do you have a minimal code example?

**Comment by mihailnicamn** [comment]
> the process is basic 1 simple setInterval printing it's own process.pid
```
setInterval(() => {
    console.log(`i'm logging an loggy log ${Date.now()} - ${process.pid} `)
}, 1000)
```

**Comment by Jarred-Sumner** [comment]
@mihailnicamn it does not seem to reproduce on macOS aarch64.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/709451/229313746-7cec942d-9b56-4b9f-9bd1-b21f4a701975.png">

Is that the complete code snippet that should reproduce the issue?

**Comment by Jarred-Sumner** [comment]
Though I haven't left it running for 7 minutes, I could wait longer

**Comment by mihailnicamn** [comment]
> Is that the complete code snippet that should reproduce the issue? 

 yes, 😅
 
 > Though I haven't left it running for 7 minutes, I could wait longer

i first noticed it after 1-2 hours, than tested if made some config error in pm2 than posted it here 👌

**Comment by mihailnicamn** [comment]
fount that in logs 
```
[16357] Failed to suspend pthread 0x70000d630000 (mach thread 0) associated with TLC 0x112168000: 268435459 [16357] thread 0x70000d630000 does not have id
```

it may help 👌

**Comment by mihailnicamn** [comment]
yes, this is the "source of all evils" 😅
```
[9443] Failed to suspend pthread 0x70000b875000 (mach thread 0) associated with TLC 0x10e121000: 268435459
[9443] thread 0x70000b875000 does not have id
[9443] thread 0x70000b875000 does not have name
```
after it prints that starts 100% on cpu

**Comment by Jarred-Sumner** [comment]
thats very interesting

i wonder whats going on

**Comment by mihailnicamn** [comment]
launched manual via vscode (xterm or whatever it uses further) no signs of issue, all the errors comes when started with spawn(using bun) or fork(using pm2),
launched manual and still no issue, if it prints that "evil" message again and starts hitting 100% i'll brb with update 👌

**Comment by mihailnicamn** [comment]
[13221] Failed to suspend pthread 0x7000023ce000 (mach thread 0) associated with TLC 0x108b0d000: 268435459
[13221] thread 0x7000023ce000 does not have id
[13221] thread 0x7000023ce000 does not have name
in vscode terminal
there you have it, no terminal is safe 😂, i'll try on linux later, hope its from macos version/ cpu arch 🤷‍♂️

**Comment by Jarred-Sumner** [comment]
I suspect the issue is a bug in the logic for accessing threadlocal storage on macOS x64 in WebKit caused by a patch I made to JSC to make memory allocation very marginally faster

https://twitter.com/_saagarjha/status/1643169347064692736

The fix will be disabling BunFastTLS in our WebKit build

**Comment by mihailnicamn** [comment]
same issue on linux, without any trace in terminal 
```
const socket = new WebSocket(`wss://stream.binance.com:9443/ws/btcusdt@kline_1m`);

const ping = () => {
    socket.send(Buffer.alloc(0));
}
const isPong = (event: any) => {
}
socket.addEventListener('open', function (event) {
    console.log("opened");
});
socket.addEventListener('ping', function (event) {
    console.log('ping');
});
socket.addEventListener('pong', function (event) {
    console.log('ping');
});
```
running this hangs up the script after 10seconds <-> 2-3 minutes both linux(Ubuntu 20.04.6 LTS -> Linux 5.15.0-69-generic x86_64 x86_64) and macos (Darwin 19.6.0 x86_64 i386)

**Comment by mihailnicamn** [comment]
offtopic : amazing project, it may be my go to option for algotrading after it get's out of alpha 
## stuff i noticed:
- can't use pm2 fork is not implemented on child_process
- as the code above shows i don't have any way to handle ping/pong through websockets as client side 
- net module can't listen to unix sockets it throws there is no port 

solution as i see it (out of context never touched zig or low level programming)
- please enable the option/implementation method of underlying node core modules eg: to be able to use/import somehow any of the https://github.com/nodejs/node/tree/main/lib

**Comment by L3P3** [comment]
I have 100% cpu usage again, same symtoms on linux. Why was this "completed"?

**Comment by Jarred-Sumner** [comment]
@L3P3 please file a new issue with a code snippet that reproduces the problem so that we are able to help you.

nowadays, we have automated tests that check CPU usage for setInterval and Bun.spawn don't idly consume high CPU, so the cause is different.
