### ISSUE TITLE
Database.prepare without .finalize results in left-over wal file

### ISSUE THREAD

**Issue by betamos** [oven-sh/bun#2537]
### What version of Bun is running?

0.5.8

### What platform is your computer?

Linux 5.15.0-69-generic x86_64 x86_64

### What steps can reproduce the bug?

Run this bun program at least twice:

```ts
import { Database } from "bun:sqlite";
const db = new Database("dirty.sqlite", { create:true })
const prep = db.prepare(`SELECT "hello"`)
db.exec("pragma journal_mode = wal")

// NOTE: If this line is uncommented, the `shm` and `wal` files are removed on exit
// prep.finalize()

db.close()
```

### What is the expected behavior?

Normally, the `shm` and `wal` files are cleaned up on close. I suppose that's what's expected, but.. if manual `finalize` is required then it should probably be documented.

### What do you see instead?

```sh
$ ls | grep dirty
dirty.sqlite
dirty.sqlite-shm
dirty.sqlite-wal
```

**Comment by sayalovesu** [comment]
it looks like calling `.finalize()` on `prep` doesn't work if there happened any writes:

```js
import { Database } from 'bun:sqlite'

const db = new Database('test.db')
db.exec('PRAGMA journal_mode = WAL')

// or simply db.exec('CREATE TABLE test (id INTEGER PRIMARY KEY)')
const prep = db.prepare('CREATE TABLE test (id INTEGER PRIMARY KEY)')
prep.run()
prep.finalize()

db.close()
```

```sh
❱ bun test.js
❱ ls test.db*                                                            
test.db     test.db-shm test.db-wal
```

and in the code in the op, the `.finalize()` call doesn't seem to matter either anymore, btw. 
has something changed in the last year?

**Comment by doroved** [comment]
> and in the code in the op, the `.finalize()` call doesn't seem to matter either anymore, btw.
> has something changed in the last year?

I too have encountered this problem and wal_checkpoint doesn't help.

```ts
process.on('SIGINT', (code) => {
  db.exec('PRAGMA wal_checkpoint(TRUNCATE);')
  db.close()
  process.exit(1)
})
```

**Comment by doroved** [comment]
It might be worth checking this information out
![image](https://github.com/oven-sh/bun/assets/30116541/eee48cfc-97f9-44b9-b3dd-b8f492b74a65)
