### ISSUE TITLE
Incorrect `deepEquals` when comparing array to object

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2548]
```js
AssertionError: Expected values to be strictly deep-equal:
+ actual - expected

+ [ 1, 2, 3, 4 ]
- { '0': 1, '1': 2, '2': 3, '3': 4 }
 code: "ERR_ASSERTION"

      at node:assert:721:50
```

**Comment by fG40912** [comment]
Can you give a minimal reproducible repo?

**Comment by Jarred-Sumner** [comment]
`Bun.deepEquals( [ 1, 2, 3, 4 ], Object.fromEntries(Object.entries([ 1, 2, 3, 4 ])))`

**Comment by fG40912** [comment]
Found this implementation in my node_modules/bun-types/types.d.ts Hope it helps? 
```typescript
export function deepEquals(
    a: any,
    b: any,
    /** @default false */
    strict?: boolean,
  ): boolean;
```

**Comment by jakeboone02** [comment]
> `Bun.deepEquals( [ 1, 2, 3, 4 ], Object.fromEntries(Object.entries([ 1, 2, 3, 4 ])))`

@Jarred-Sumner I'm a little confused...you're expecting that to pass? I guess I can see why since the index properties are the same.

FWIW, it only passes in Jest if you add a `length` property (which can be wrong) and then cast it with `Array.from`:

```ts
it('does things', () => {
  const obj = { ...Object.fromEntries(Object.entries([1, 2, 3, 4])), length: 4 };

  // PASS in both
  expect([1, 2, 3, 4]).toEqual(Array.from(obj));

  // PASS in both
  expect(Array.from({ '0': 1, length: 1 })).toEqual([1]);

  // PASS in Jest; FAIL in bun:test
  expect(Array.from({ '0': 1, length: 42 })).toEqual([1]);
  //                  length is wrong ^^

  // FAIL in Jest; segfault in bun:test !!!
  expect([1, 2, 3, 4]).toEqual(obj);
});
```

Sorry if this is just noise; I've been looking into `deepEquals` a lot because of #2417.

**Comment by jakeboone02** [comment]
I was thinking #2557 would help resolve the segfault I mentioned above, but it still happens in canary which includes #2557.

Does this need a new issue?

Reproduction:

```ts
import { expect, it } from "bun:test";
it("does not segfault", () => {
  const obj = { ...Object.fromEntries(Object.entries([1, 2, 3, 4])), length: 4 };
  expect([1, 2, 3, 4]).toEqual(obj);
});
```

![image](https://user-images.githubusercontent.com/366438/230470887-48a79b64-3341-4272-b3a2-83c4745a0137.png)

**Comment by dylan-conway** [comment]
@jakeboone02 Thanks for the investigation. I will have a fix for these bugs shortly

**Comment by dylan-conway** [comment]
#2580

**Comment by jakeboone02** [comment]
@dylan-conway - I confirmed with bun@canary that #2580 resolves the segfault, but I'm still confused by @Jarred-Sumner's example above (https://github.com/oven-sh/bun/issues/2548#issuecomment-1496717612). Maybe I'm misunderstanding the original issue.

> `Bun.deepEquals( [ 1, 2, 3, 4 ], Object.fromEntries(Object.entries([ 1, 2, 3, 4 ])))`

Is that expression supposed to evaluate to `true`? The object with numeric keys and a (correct) `length` value doesn't "deep equal" the array literal unless you cast the object with `Array.from` first, even in Jest (which borrows its `equals` function from Underscore).

![image](https://user-images.githubusercontent.com/366438/230634390-f38afb31-657e-4942-91e9-121d9def78c7.png)

**Comment by dylan-conway** [comment]
@jakeboone02 This issue needs more information. You're right, the expression should not evaluate to true with `Bun.deepEquals`, jest `toEqual`, or `assert.deepEqual`. This bug was originally found when running tests from another project (I think lodash or jest). We'll try to find more information, and if not we'll close the issue.

**Comment by snoglobe** [comment]
>Reproduction: 
>
```js
import { expect, it } from "bun:test";
  it("does not segfault", () => {
  const obj = { ...Object.fromEntries(Object.entries([1, 2, 3, 4])), length: 4 };
  expect([1, 2, 3, 4]).toEqual(obj);
});
```

no longer segfaults (tested on `1.1.39-debug+503154c1b`)

example provided above is false on Node:
```js
> assert.deepEqual( [ 1, 2, 3, 4 ], Object.fromEntries(Object.entries([ 1, 2, 3, 4 ])))
Uncaught AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
...
```
