### ISSUE TITLE
Hashing packages don't work [argon2 - bcrypt]

### ISSUE THREAD

**Issue by yousefelgoharyx** [oven-sh/bun#2550]
### What version of Bun is running?

0.5.9

### What platform is your computer?

WSL - x64

### What steps can reproduce the bug?

Try using argon or bcrypt

### What is the expected behavior?

Hashing packages should work.

### What do you see instead?

![image](https://user-images.githubusercontent.com/30435916/229707566-3a54cc35-c524-4f80-8e98-cb1bff32bbae.png)

**Comment by fG40912** [comment]
Did you install declaration file for bcrypt?
```
npm i @types/bcrypt
```
Argon did have a declaration file that's why it didn't have errors.

**Comment by v3nntrnx** [comment]
> Did you install declaration file for bcrypt?
> 
> ```
> npm i @types/bcrypt
> ```
> 
> Argon did have a declaration file that's why it didn't have errors.

I just tested it on latest canary build. In his issue he mentioned that argon doesn't work too. Argon doesn't have @types/argon package but it still wouldn't work with it, just like bcrypt (see below)

When I downloaded types for bcrypt, it still wouldn't work
![image](https://user-images.githubusercontent.com/94789999/230080208-8308f430-6913-4661-a075-d33fe1aa8221.png)

The error Argon throws is the almost the same
![image](https://user-images.githubusercontent.com/94789999/230079107-bb85ba89-a5d6-4518-a4e3-fe4145bf680a.png)

**Comment by Jarred-Sumner** [comment]
The bug is missing postinstall in bun inwtall, which will be fixed as part of #2073

**Comment by v3nntrnx** [comment]
> The bug is missing postinstall in bun inwtall, which will be fixed as part of #2073

Just wanted to say, I used npm, not bun install. I don't think it's related

**Comment by fG40912** [comment]
can you try delete node_modules & package-lock.json first then re-install the packages?

**Comment by v3nntrnx** [comment]
Now it returns different error

argon:
![Screenshot 2023-04-08 154940](https://user-images.githubusercontent.com/94789999/230724824-5f3be521-19e3-40eb-968f-65ffa2cd6f52.png)

bcrypt:
![image](https://user-images.githubusercontent.com/94789999/230724793-1b3a5819-3f7f-43d2-929f-dee823eef8aa.png)

I didn't go very technical about it but I think it fails to import because it's trying to import a binary

**Comment by Jarred-Sumner** [comment]
Bun v0.6.8 will have Bun.password & Bun.passwordSync which provide both argon2 and bcrypt without needing a dependency to install

#3204

**Comment by benfavre** [comment]
It's my understanding that your proposed improvement in 0.6.8 would not help fix things like me trying to run : https://directus.io/ via bunx ?
Error: Cannot find module '/tmp/directus@latest--bunx/node_modules/argon2/lib/binding/napi-v3/argon2.node'

Is there a path forward for using stuff that depends on argon2 explicitly in bun ?
Thanks.

**Comment by smartrusorg** [comment]
`npm rebuild bcrypt`

**Comment by divmgl** [comment]
Still running into this, but `npm rebuild bcrypt` worked. Would love for the build to work through `bun i` though. I added it to my trusted dependencies and I'm still running into this.

**Comment by Babailan** [comment]
when is this going to be fixed i use bcrypt on svelte and got error

`/home/ronnel/code/capstone-project/src/routes/api/test/+server.js: failed to import "bcrypt"
|- Error: Cannot find module '/home/ronnel/code/capstone-project/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'`

**Comment by Electroid** [comment]
See issues for each:
* #2022 
* #299
