### ISSUE TITLE
DuckDB like SQLite

### ISSUE THREAD

**Issue by sroussey** [oven-sh/bun#2559]
### What is the problem this feature would solve?

For terminal/script usage (quick start time makes this a good use case), many analytical scripts would be best done with DuckDB over SQLite. 

### What is the feature you are proposing to solve the problem?

Embed DuckDB

**Comment by Electroid** [comment]
Thanks for filing a feature request! While this would be interesting, I don't think it would make sense to embed this, by default, in Bun. This seems like something that would still be best with an npm package.

**Comment by develar** [comment]
It makes sense in the light of the NPM issue, that no one want to fix — https://github.com/mapbox/node-pre-gyp/issues/661#issuecomment-1754057766

> despite Bun is in a very experimental stage, it's worth keeping an eye on it, as it has SQLite in the standard library, out of the box, without any precompiled dependency.
