### ISSUE TITLE
Correct `node:events.getEventListeners()` behavior with `AbortSignal`

### ISSUE THREAD

**Issue by ThatOneBro** [oven-sh/bun#2586]
It seems that `getEventListeners(signal, "abort")` does not properly return the `"abort"` listeners added to an `AbortSignal`, or at least it seemed to be that way when testing in `node:events.once()` tests (see #2571). 

`getEventListeners()` should work with `AbortSignal`, as it extends `EventTarget`.

**Comment by snoglobe** [comment]
fixed in https://github.com/oven-sh/bun/pull/2604
