### ISSUE TITLE
Windows Subsystem for Linux (Ubuntu) get SegmentationFault at 0

### ISSUE THREAD

**Issue by andtii** [oven-sh/bun#259]
![image](https://user-images.githubusercontent.com/1434571/177540356-8aecabbb-8860-4c3b-ab2c-8ecaa9e8b04e.png)

**Comment by FinnRG** [comment]
Do you have a repo, which you could share?

**Comment by FinnRG** [comment]
@andtii Please provide a repo and test this again with the latest version (v0.1.2).

**Comment by andtii** [comment]
Yes will try this out early next week and report back

**Comment by Electroid** [comment]
Hey @andtii, if you have time, let us know if you still see this issue. We've made some improvements to the stability of `bun install` since you reported this and want to make sure we made it better.

Be sure to try the newest version of Bun: `bun upgrade`

**Comment by andtii** [comment]
@Electroid I have tested the latest version and it works as expected now so im closing this out. Thnx!
