### ISSUE TITLE
Segfault with default config from Readme

### ISSUE THREAD

**Issue by pierrick-martin-dev** [oven-sh/bun#260]
Os:
```
uname --all
Linux archlinux 5.18.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:03 +0000 x86_64 GNU/Linux
```
Bun: 0.1.1
`$home/.bunfig.toml`:
```
# Using scoped packages with bun install
[install.scopes]

# Scope name      The value can be a URL string or an object
"@mybigcompany" = { token = "123456", url = "https://registry.mybigcompany.com" }
```
Output:
```
bun install v0.1.1

SegmentationFault at 0


–––– bun meta ––––
Bun v0.1.1 Linux x64 #1 ZEN SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:03 +0000
InstallCommand: bunfig
Elapsed: 5ms | User: 1ms | Sys: 9ms
RSS: 69.21MB | Peak: 35.21MB | Commit: 69.21MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

If I remove the whole block `[install.scopes]` it works. Even with the full rest of the exemple the segfault doesn't show up

**Comment by pierrick-martin-dev** [comment]
`sudo perf trace bun install --silent > log.perf.txt 2>&1`: [log.perf.txt](https://github.com/Jarred-Sumner/bun/files/9054512/log.perf.txt)
`bun install --verbose 2> logs.txt`: [logs.txt](https://github.com/Jarred-Sumner/bun/files/9054513/logs.txt)

**Comment by taymoork2** [comment]
@Jarred-Sumner I think this is the point of failure and seems to be a misspelling
However changing it to `[install.scoped]` still doesnt resolve to the right registry

https://github.com/Jarred-Sumner/bun/blob/master/src/install/install.zig#L2637=

**Comment by FinnRG** [comment]
Duplicate of #190. Please close this issue and post your comment with the logs there.
