### ISSUE TITLE
Ability to get number of changes from SQLite query

### ISSUE THREAD

**Issue by jonasb** [oven-sh/bun#2608]
### What is the problem this feature would solve?

When executing an INSERT, UPDATE or DELETE query I'd like to know how many rows were changed.

### What is the feature you are proposing to solve the problem?

Using `bun:sqlite`, there doesn't seem to be an API for getting the number of changes done by INSERT, UPDATE, DELETE statement.

I propose that either `Statement.run` return `{ changes: number }` or that `Database` get a `changes()` function.

[sqlite3_changes](https://www.sqlite.org/c3ref/changes.html)

### What alternatives have you considered?

`Statement.all()` currently returns changes as a number if there are no columns in the result, but it's not documented and isn't reflected in the Typescript types of the function.

[result = jsNumber(sqlite3_changes(castedThis->version_db->db));](https://github.com/oven-sh/bun/blob/5c37d0f2a57af40352ef8a30f941551c24fe06eb/src/bun.js/bindings/sqlite/JSSQLStatement.cpp#L1216-L1217)

Another alternative is to use `changes()` from a separate query, but it feels a bit much.

```ts
const result = database
  .prepare<{ changes: number }, never>('SELECT changes() AS changes')
  .get();
return result?.changes ?? 0;
```

**Comment by infrahead** [comment]
solved with https://bun.sh/blog/bun-v1.1.14#track-changes-with-query-run-sql

This should be closed

**Comment by jonasb** [comment]
Yup, verified that it works, thanks!
