### ISSUE TITLE
When using `bun add some-package` creates a package.json file, it lacks name and version property defaults

### ISSUE THREAD

**Issue by RobiFerentz** [oven-sh/bun#261]
This is very minor, but it means no scripts can be run with `bun run` .

A solution could be adding defaults, or even better, giving a better error when `bun run` fails (currently it says a script name whatever does not exist, even if it does).

Probably relates to this issue: https://github.com/Jarred-Sumner/bun/issues/229

**Comment by nickfla1** [comment]
I think adding a default name would be a good solution for this issue!
@Jarred-Sumner If you agree I'd like to have a go at this as my first contribution.

**Comment by xhyrom** [comment]
Fixed by https://github.com/oven-sh/bun/commit/7904f49b5dc48dc057729eb158067baf54f94cfb
