### ISSUE TITLE
Segfault from official `duckdb` package

### ISSUE THREAD

**Issue by controversial** [oven-sh/bun#2612]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```ts
import duck from 'duckdb';

const db = new duck.Database(':memory:');
db.all('SELECT 42 as fortytwo', console.log);

db.close();
```

### What is the expected behavior?

```
❯ node test.js
null [ { fortytwo: 42 } ]
```

### What do you see instead?

```
❯ bun test.js
[0.03ms] ".env"
[1]    90900 segmentation fault  bun test.js
```
```
❯ lldb bun test.js         
(lldb) target create "bun"
Current executable set to 'bun' (arm64).
(lldb) settings set -- target.run-args  "test.js"
(lldb) run
Process 90926 launched: '/Users/luke/.bun/bin/bun' (arm64)
[0.03ms] ".env"
Process 90926 stopped
* thread #1, stop reason = EXC_BAD_ACCESS (code=1, address=0x5)
    frame #0: 0x0000000101fb6d4c bun`JSC__JSValue__isInstanceOf + 40
bun`JSC__JSValue__isInstanceOf:
->  0x101fb6d4c <+40>: ldrb   w8, [x2, #0x5]
    0x101fb6d50 <+44>: cmp    w8, #0x17
    0x101fb6d54 <+48>: b.lo   0x101fb6de0               ; <+188>
    0x101fb6d58 <+52>: ldr    w8, [x22]
```

**Comment by controversial** [comment]
I can no longer reproduce this on latest canary

**Comment by tjbroodryk** [comment]
Can we reopen this issue? I've started running into the same thing on the latest bun canary version

## What version of Bun is running?
1.0.4

## What platform is your computer?
Darwin 21.6.0 Apple M1

## What steps can reproduce the bug?
```typescript
import duck from 'duckdb';

const db = new duck.Database(':memory:');
db.all('SELECT 42 as fortytwo', console.log);

db.close();
```

## What is the expected behavior?
```bash
❯ node test.js
null [ { fortytwo: 42 } ]
```
## What do you see instead?
```bash
$ lldb bun index.ts
(lldb) target create "bun"
Current executable set to 'bun' (arm64).
(lldb) settings set -- target.run-args  "index.ts"
(lldb) run
Process 88194 launched: '/Users/tjaartbroodryk/.bun/bin/bun' (arm64)
Process 88194 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5)
    frame #0: 0x0000000101f56ad4 bun`JSC__JSValue__isInstanceOf + 40
bun`JSC__JSValue__isInstanceOf:
->  0x101f56ad4 <+40>: ldrb   w8, [x2, #0x5]
    0x101f56ad8 <+44>: cmp    w8, #0x17
    0x101f56adc <+48>: b.lo   0x101f56b70               ; <+196>
    0x101f56ae0 <+52>: ldr    w8, [x22]
Target 0: (bun) stopped.
(lldb) 
```

**Comment by controversial** [comment]
Does not fail for me on the latest `bun upgrade --canary`:

<img width="429" alt="Screenshot 2023-09-26 at 1 03 08 PM" src="https://github.com/oven-sh/bun/assets/10377391/093eaccc-bd09-469a-8a8b-fd35c914c010">


However, `bun` hangs and doesn’t exit, which isn’t ideal behavior

**Comment by tjbroodryk** [comment]
unfortunately im still getting an issue with duckdb on the latest canary, albeit a different one.
It looks as if the `duckdb.node` binary was not included in the duckdb package install

<img width="1217" alt="image" src="https://github.com/oven-sh/bun/assets/67912111/84e4025f-244c-4467-ab8b-d84aafca1328">

What version of duckdb are you using?

**Comment by jean343** [comment]
You need to add `duckdb` to your `trustedDependencies` as mentioned here https://bun.sh/guides/install/trusted.

```
  "trustedDependencies": [
    "duckdb"
  ]
}
```
