### ISSUE TITLE
Bun not reading a string containing a '#' character in .env file

### ISSUE THREAD

**Issue by Tarang-singhal** [oven-sh/bun#2622]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.19.0-38-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Declare an environment variable in .env file of a project with a value (for example - "hastag#string" ). 
        `var="hashtag#string"`
2. try printing the variable using BUN.env.var in console. 
        ` console.log(Bun.env.var) `    
        `//expected output - hastag#string`
         `//actual output - hashtag`
3. you will see that only "hashtag" is printed.
4. which means that BUN is not reading the string after '#' character. 

### What is the expected behavior?

Expected behavior - whole string should be read if enclosed in double quotes

### What do you see instead?

what I see - whole string is not read

@Jarred-Sumner can you look into it

**Comment by simylein** [comment]
This is working with bun 0.7.1. Can we close this as resolved?
