### ISSUE TITLE
bun install --global is broken

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2626]
### What version of Bun is running?

0.5.9 and 0.6 canary

### What steps can reproduce the bug?

`bun i -g esbuild`
`bun i --global esbuild`

![image](https://user-images.githubusercontent.com/24465214/231265743-38cf2b23-eec4-43b6-a980-725630f269e6.png)

its installed at `~/.bun/install/global/node_modules/esbuild/bin/esbuild` but the bin file is not added to `.bun/bin`

$BUN_INSTALL is set to `/home/dave/.bun` as it should be

### What is the expected behavior?

to install

**Comment by colinhacks** [comment]
Hm, working for me on mac/zsh

**Comment by paperclover** [comment]
okay weird it works for me now. must've been some weird PATH config or whatever

**Comment by isaced** [comment]
This works for me.

```
export BUN_INSTALL="/home/YOUR_USERNAME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
```

**Comment by yemreak** [comment]
Generalized version of @isaced's solution

- `touch ~/.zprofile` if not exists
- Append the below to `~/.zprofile` with `open ~/.zprofile` command

```
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
```
