### ISSUE TITLE
Unicode characters in imports throws error

### ISSUE THREAD

**Issue by marcj** [oven-sh/bun#263]
Code like

```typescript
import { __Ωfoo } from './test2.js';
```

throws following error when run via `bun run test.js` (assuming empty test2.js exists)

```
SyntaxError: Unexpected token '}'. Expected a ':' prior to a named destructuring property.
      at /Users/marc/bude/deepkit-framework/packages/benchmark/test.js:3:0
```

If I remove `Ω` then it works as expected (throws that `__foo` is not found in test2.js).

**Comment by whaaaley** [comment]
I just encountered this when using culori which uses a theta

**Comment by Electroid** [comment]
Tested using `0.2.2` and it looks like we fixed this! 

```js
// index.js
import { __Ωfoo } from './util';
console.log(__Ωfoo());

// util.js
export function __Ωfoo(): string {
  return "hi";
}
```

If you're still running into this issue, please feel free to comment and we can reopen the issue.
