### ISSUE TITLE
`WebSocket.close()` error code

### ISSUE THREAD

**Issue by ElYaiko** [oven-sh/bun#2631]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

I'm storing the WS connections in a Map and when I get a stored ws and call `ws.close(1008)` (with a code) it throws and shutdowns server:

`zsh: segmentation fault  bun run index.ts`

But when not setting an error code it closes normal.

**Comment by Jarred-Sumner** [comment]
Thanks for flagging, we'll take a look

**Comment by jakeg** [comment]
Confirm that `ws.close()` works while `ws.close(400)` or `ws.close(400, 'Some reason')` is giving a segmentation fault on v0.5.9.
