### ISSUE TITLE
when will you support LinuxOne s390x?

### ISSUE THREAD

**Issue by SeqCrafter** [oven-sh/bun#2632]
### What is the problem this feature would solve?

Can't install bun on s390x arch now

### What is the feature you are proposing to solve the problem?

support more arch

**Comment by Electroid** [comment]
Hi there, thanks for submitting a feature request!

While we do want Bun to work on many platforms, it's likely not feasible — in terms of time, added complexity, and maintainability — for us to support s390x, given it's old and uncommon. For now, our priority is adding support for Windows.
