### ISSUE TITLE
FormData missing final boundary

### ISSUE THREAD

**Issue by yousefelgoharyx** [oven-sh/bun#2644]
### What version of Bun is running?

0.5.9

### What platform is your computer?

WSL - x64

### What steps can reproduce the bug?

```js
async function handler(req: Request) {
	const contentType = req.headers.get("Content-Type")
	if (!contentType) throw new Error("Missing Content-Type");

	if (contentType.startsWith("multipart/form-data")) {
		const fd = await req.formData()
		const body = Object.fromEntries(fd.entries());
		return new Response(JSON.stringify(body))
	}

	throw new Error("Invalid Content-Type");
}
Bun.serve({
	port: 3000,
	async fetch(request) {
		await new Promise((resolve) => setTimeout(resolve, 0));
		const response = await handler(request)
		await new Promise((resolve) => setTimeout(resolve, 0));
		return response;
	}
})
```
Here is the code causing the bug. Try to hit `localhost:3000` many times quickly and the server will throw the following error message: 
`error: FormData missing final boundary`

When removing the setTimeouts everything works correctly. That is what causing the problem.

### What is the expected behavior?

Not to throw an error

### What do you see instead?

The error described above.

**Comment by Liliandev** [comment]
With Astrobuild, i have this error : 

TypeError: FormData parse error missing final boundary

Same thing is i submit with Json

**Comment by lafkpages** [comment]
Same error with SvelteKit and Superform

**Comment by nanolikestea** [comment]
Can confirm the error on Sveltekit

**Comment by maxa-ondrej** [comment]
Getting the same error on SvelteKit with `svelte-adapter-bun` adapter.

**Comment by Dan1ve** [comment]
Same error here

**Comment by ArthurSegato** [comment]
Can confirm the error on Qwik with bun adapter.
```
Ubuntu - 23.10
Bun - 1.0.23
Qwik - 1.4.0
Qwik City - 1.4.0
```

**Comment by yaikohi** [comment]
I am not sure if it is bun or H3, but I am receiving this error as well when using solidstart, which proxies h3s functions.
```error
[h3] [unhandled] 1 | export default "native";
    ^
error: FormData parse error missing final boundary
      at formData (native:1:1)

1 | export default "native";
    ^
TypeError: FormData parse error missing final boundary
      at formData (native:1:1)

```

**Comment by znycheporuk** [comment]
Here is the repo you can clone to reproduce the error (SolidStart)
https://github.com/znycheporuk/bun-formdata

**Comment by KyleFontenot** [comment]
This makes Bun completely unusable for my purposes. After 1 year of the OP, and a 1.0 release, can we maybe bump up this priority?

**Comment by ElYaiko** [comment]
Any update? It doesn't append the Boundary neither with `fetch`.
Not even `node-fetch` works.

**Comment by Electroid** [comment]
I'm able to reproduce this 

> Here is the repo you can clone to reproduce the error (SolidStart) https://github.com/znycheporuk/bun-formdata

This is reproducible, though getting a more minimal reproduction proved difficult.

It looks like there is some issue with how solidstart's dependencies are cloning the request and its body that causes the body to be empty by the time `.formData()` is called. We will still fix this, but it's more complicated.

**Comment by ElYaiko** [comment]
> I'm able to reproduce this
> 
> > Here is the repo you can clone to reproduce the error (SolidStart) https://github.com/znycheporuk/bun-formdata
> 
> This is reproducible, though getting a more minimal reproduction proved difficult.
> 
> It looks like there is some issue with how solidstart's dependencies are cloning the request and its body that causes the body to be empty by the time `.formData()` is called. We will still fix this, but it's more complicated.

To me happens even without solidstart, just sending a simple request with a FormData body doesn't attach the Boundary so the servers doesn't detect the `multipart/form-data` request.

**Comment by zoto-ff** [comment]
please fix it

**Comment by zoto-ff** [comment]
bump

**Comment by aralroca** [comment]
same error :/

**Comment by karemont** [comment]
I had this issue on my class 
```
class Parent {
	public async fetch(req: Request) {
		const httpRequest = new HTTPRequest(req)
		console.log(await httpRequest.formData())
	}
}
```

in which `HTTPRequest` is just a wrapper
```
class HTTPRequest extends Request {
    message = 'Hello'
    constructor(input: RequestInfo, init?: RequestInit) {
        super(input, init);
    }
}
```

I resolved it using a copy function inside the parent class

```
class Parent {
	private copy(req: Request) {
		const r = req as HTTPRequest
		r.message = 'Hello'
		return r
	}
	public async fetch(req: Request) {
		const httpRequest = this.copy(req)
		console.log(await httpRequest.formData());
	}
}
```

hopefully this helps solve this bug, somehow.

**Comment by huseeiin** [comment]
also present in astro

**Comment by KyleFontenot** [comment]
This should be re-opened. Error remains. https://github.com/oven-sh/bun/issues/14988

**Comment by avarayr** [comment]
This error is not fixed, still getting "FormData parse error missing final boundary"

**Comment by ruohki** [comment]
Fixed for me when using the canary tag to build my stuff

**Comment by darklight9811** [comment]
Getting this error with `1.1.38` using hono

**Comment by shriharip** [comment]
Yeah, having same issue on latest Astro (5.1.0) running on bun . Astro form results in this error.

**Comment by niyrme** [comment]
A working (hopefully temporary) fix for astro is to this is to not prerender that specific route.

https://docs.astro.build/en/reference/routing-reference/#per-page-override

**Comment by shriharip** [comment]
@niyrme  i agree. But this requires having a node adapter and then finding different ways to host the app too right?

**Comment by VesperQuartz** [comment]
Why was this closed  if it is not solved? I am having this issue with Hono

**Comment by emanuele-toma** [comment]
Still happening with hono
