### ISSUE TITLE
The example for the `bun pm bin` command to get the path to the global `bin` directory is incorrect

### ISSUE THREAD

**Issue by sounisi5011** [oven-sh/bun#2646]
### What is the type of issue?

Documentation is incorrect, Example code is not working

### What is the issue?

Currently, an example command to get the path to the global `bin` directory is written as follows:

https://github.com/oven-sh/bun/blob/aeb3bb949b0052d0573bef507f1b66bbcf4f3dc0/docs/cli/install.md?plain=1#L417-L422

However, `bun pm bin` is the command to get the path to the `bin` directory for the local project.

https://github.com/oven-sh/bun/blob/aeb3bb949b0052d0573bef507f1b66bbcf4f3dc0/docs/cli/install.md?plain=1#L410-L415

This example does not have the `-g` / `--global` option. Perhaps it should be written like this:

``````md
To get the path to the global `bin` directory:

```bash
$ bun pm bin --global # or `bun pm bin -g`
<$HOME>/.bun/bin
```
``````

> **Note** 
> This command works the same for `bun --global pm bin` and `bun pm --global bin`.
> I'm not familiar with Bun, so I don't know where to put the `-g` / `--global` option for a better example code.

### Where did you find it?

https://bun.sh/docs/cli/install#utilities

**Comment by colinhacks** [comment]
Thank you, fixed in https://github.com/oven-sh/bun/pull/2638
