### ISSUE TITLE
Building on Arch Linux is missing libatomic.a

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2664]
The make flag [-l:libatomic.a](https://github.com/oven-sh/bun/blob/main/Makefile#L488) fails on Arch Linux since this flag doesn't exist. We can use `-latomic` to fix this but this ends up breaking CI in a very subtle way.

Related Issue where the quick change above had to be reverted: https://github.com/oven-sh/bun/issues/2645

**if you are on arch right now and you want to build bun, use this**

```bash
sudo ln -s /lib/libatomic.so /lib/libatomic.a
```

However the makefile should do this fallback for us and work fine on Arch. I think the solution is some dynamic check that specifically tests for the existence of libatomic.a in all the places the linker would check, and if not, then use -latomic. and also make sure that CI does not ever use this fallback.

keywords for search: libatomic, latomic, atomic

**Comment by Hanaasagi** [comment]
Tested it locally, and it works. Thank you.

**Comment by krk** [comment]
`sudo ln -s /lib/libatomic.so /lib/libatomic.a` doesn't fix the build for me, fails with:

```
...
ld.lld: error: attempted static link of dynamic object /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/libatomic.a
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
error: script "setup" exited with code 1 (SIGHUP)
```

**Comment by krk** [comment]
Changing `libatomic.a` to `libatomic.so` fixed the link:

* https://github.com/oven-sh/bun/blob/cbc5ca770bd427ffff29c748f9da60b83b621a00/Makefile#L490
* https://github.com/oven-sh/bun/blob/cbc5ca770bd427ffff29c748f9da60b83b621a00/CMakeLists.txt#L930

**Comment by paperclover** [comment]
the old workaround was before CMake build. We need to link atomic statically for our release, but it's ok to be dynamic in dev environment. The solution now is we need to add a CMake flag like -DUSE_DYNAMIC_LIBATOMIC=1 for arch users, and then

```
if(USE_DYNAMIC_LIBATOMIC)
  target_link_libraries(${bun} PRIVATE "libatomic.a") 
else()
  target_link_libraries(${bun} PRIVATE "atomic") 
endif()
```

Then `bun setup` should accept arguments that are passed to CMake, or maybe we detect Arch specifically.
