### ISSUE TITLE
Communicating with RavenDB errors out

### ISSUE THREAD

**Issue by dieeisenefaust** [oven-sh/bun#2668]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Create a simple script to connect to a RavenDB instance such as 

```import { DocumentStore } from 'ravendb';

const store = new DocumentStore("http://localhost:8080", "MCM");
store.initialize();

const session = store.openSession();
const user = await session.load("user/0000000000000000102-A");
console.log(user);
```

### What is the expected behavior?

Receive a response like below which is received when the script is run using node (Note: the document being retrieve has only username & password attributes).

`{
  username: 'first.name@gmail.com',
  password: 'password1',
  '@metadata': MetadataInternal {
    '@nested-object-types': MetadataInternal {},
    'Raven-Node-Type': null,
    '@change-vector': 'A:102-tZN4/9V2NkatJfXC5RXcow',
    '@id': 'user/0000000000000000102-A',
    '@last-modified': '2023-04-16T04:17:41.5935074Z'
  },
  id: 'user/0000000000000000102-A'
}`

### What do you see instead?

```
RavenException: An exception occurred while contacting http://localhost:8080/databases/MCM/docs?&id=user%2F0000000000000000102-A: (fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe is not a function. (In '(fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe(passthrough)', '(fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe' is undefined) . 
@/root/fbpTest/janus-bun-elysia/node_modules/ravendb/dist/Http/RavenCommand.js:129:110
generatorResume@[native code]
fulfilled@/root/fbpTest/janus-bun-elysia/node_modules/ravendb/dist/Http/RavenCommand.js:17:30
promiseReactionJob@[native code]
The server at http://localhost:8080/databases/MCM/docs?&id=user%2F0000000000000000102-A responded with status code: 503: (fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe is not a function. (In '(fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe(passthrough)', '(fetcher ? new ReadableWebToNodeStream_1.ReadableWebToNodeStream(response.body) : response.body).pipe' is undefined)
```

### Additional information

I was able to create a new document from within a bun elysia program.

I had the following execute within a beforeHandle:

```
        const user = {
          username: headers.get("username"),
          password: headers.get("password"),
        };
        await session.store(user, "user/");
        await session.saveChanges();
```

**Comment by nektro** [comment]
Hi! if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
