### ISSUE TITLE
`relative` from node:path returns the wrong result

### ISSUE THREAD

**Issue by mk12** [oven-sh/bun#2671]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

Save this as `test.js`:
```js
import { relative } from "node:path";
console.log(relative("a/b", "c"));
console.log(relative("a/b", "cd"));
```
Then `bun run test.js`.

### What is the expected behavior?

Node and Deno both print this:
```
../../c
../../cd
```

### What do you see instead?

Bun prints this, which is clearly wrong:
```
../..
../..cd
```

**Comment by Jarred-Sumner** [comment]
I'm having some trouble reproducing this, but I have an idea

<img width="352" alt="image" src="https://user-images.githubusercontent.com/709451/232394635-d322e7e0-6ca0-43f5-9a5d-0202dfd7ce67.png">


How many characters long is the cwd of the folder being executed in? If it's almost 1024 characters that would potentially explain it

**Comment by Jarred-Sumner** [comment]
Oh just noticed you're running Bun v0.5.7, where this reproduces consistently.

Please run

```bash
bun upgrade
```
