### ISSUE TITLE
Use bun's bundler on runtime JS builtin modules

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2672]
Instead of our current pattern of `src/bun.js/*.exports.js`

What if we did a directory structure like:
- 📁  builtins
- 📁  builtins/bun
- 📂  builtins/bun/ffi.js 
- 📂  builtins/bun/sqlite.js
- 📁  builtins/node/
- 📂  builtins/node/fs.js
- 📂  builtins/node/dns.js
- 📂  builtins/node/fs/promises.js
- 📂  builtins/internal/...

From there, we would bundle each top-level module individually (`node:fs` as one bundle). Note that the build system here will be a little bit complicated. For good reasons, we have to concatenate some code to the top of `node:fs` and `bun:ffi` at Bun's compile-time, which means that those files appear to have unbound global identifiers. Some magic required.

In debug builds of Bun, we can configure it to run the bundler on import of one of these modules.

In release builds of Bun, we would ahead of time build each file and commit built files into the repository so that people can find it online.

### TypeScript?

I think it's probably worthwhile to start writing new modules in TypeScript, but the priority must be (1) correctness and (2) performance.

If we find ourselves writing code in a way that prioritizes making `tsc` not show an error in-editor instead of performance, the TS error should be ignored or the tsconfig.json rules should be changed to permit the behavior. JavaScript builtins code is extremely pedantic, sometimes weird, and that's okay

Our users matter more than our internal developer experience of building Bun.

It might sound convenient for bun-types to be generated from these files that are used, but that won't work:
- Most of the actual implementations of things are not in JavaScript/TypeScript. `node:fs` in Bun mostly just calls .bind() on a bunch of functions
- The internal types should probably be different than the public types. We need to be extremely careful about runtime type checking. `instanceof` is not good enough.

**Comment by Electroid** [comment]
We've started to do some of this, going to close since this is a chore.
