### ISSUE TITLE
`Bun.write` fails to write to stdout with long strings

### ISSUE THREAD

**Issue by savioxavier** [oven-sh/bun#2674]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Write a long string to `Bun.stdout` using `Bun.write()`

> It will fail at string lengths greater than 262143 (see Additional Information below)

If the string is small enough, the command is successfully executed
```js
import { write, stdout } from 'bun'

const str = "hello"
await write(stdout, str)
```

However, if the string is large (for example a huge text or code file), the command fails
```js
import { write, stdout, file } from 'bun'

const str = await file("path/to/huge/file").text() // for extracting the text
await write(stdout, str)
```

The same can be achieved even if we use a huge string as well:
```js
import { write, stdout } from 'bun'

const str = "a".repeat(300000)
await write(stdout, str)
```

### What is the expected behavior?

The text should be displayed in the console properly, instead of the `ENOENT` error.

### What do you see instead?

```
ENOENT: No such file or directory
syscall: "open"
  errno: -2
```

#### Reason

- Although this works fine with `console.log()`, I wanted to use `Bun.write()` because it writes to stdout _way_ faster than `console.log()`, which is really helpful while outputting a really long string
- Although I could have directly used the `file()`'s Blob output, I required it to be converted to a String format so that I could modify the text (eg: string replaces)

#### Experiment

I wanted to see at what string length would `Bun.write()` fail, so I made a small script as follows:

![image](https://user-images.githubusercontent.com/38729705/232490117-07b68a5b-b011-43dc-b5e3-9628acb9a9bc.png)

With my previous tests on reading file contents using `Bun.write()`, I figured the max length was somewhere in the range 250k < x < 300k, and with the help of some trial and error, I was able to find out the failing length.

The bash script runs the JS file repeatedly until it _does not fail_. When the JS file runs successfully, the bash script exits and greps the "len" field. I used a reverse loop instead of starting from length 0 as it would have taken an unnaturally long time to fully execute.

Executing the script shows us that it fails at string length _greater than_ 262143

I should also note that this worked perfectly fine in v0.2 and has not been working since. I probably should have reported this earlier, but I really didn't have a chance to experiment in the past few months.

**Comment by Jarred-Sumner** [comment]
As a temporary.workaround: you could use `console.write`

**Comment by savioxavier** [comment]
Thanks! Any idea what causes this issue? Also, why the number 262143?

**Comment by Jarred-Sumner** [comment]
I suspect Linux kernel 5.15 is too old for the io_uring stuff that is being used

**Comment by savioxavier** [comment]
Ah, that does make sense.

I'm currently using Debian on WSL, which uses the latest version of Debian (Bullseye, v11.0) – which still uses a v5.10 < x < v6 version of the Linux kernel. The next Debian version with v6 of the kernel is due to be released in mid 2023. I suppose current Debian users who are on the latest version wouldn't be able to use most of Bun's features then.

Just a heads-up, thought I would let you know.

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/234746233-24eb3f42-15f5-43d5-a947-d54ed8130fb2.png)

ubuntu 22.04 has 5.15 kernel as well :(
