### ISSUE TITLE
`dirname` from node:path returns the wrong result

### ISSUE THREAD

**Issue by mk12** [oven-sh/bun#2676]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```js
import { dirname } from "node:path";
console.log(dirname("x"));
```

### What is the expected behavior?

Node and Deno both print `.`.

### What do you see instead?

Bun prints `/`.

**Comment by Jarred-Sumner** [comment]
Once the canary build finishes please run 

```
bun upgrade --canary
```
