### ISSUE TITLE
`events.on` is not implemented (async iterator for EventEmitter)

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2679]
The PR for `node:events` (#2604) left this unimplemented. Defined in `events.exports.js`, [reference here](https://github.com/nodejs/node/blob/17c9aa2f7635eccbb132cce20cd45c4cf14fd7be/lib/events.js#L1042), [docs here](https://nodejs.org/api/events.html#eventsonemitter-eventname-options)

**Comment by blackmius** [comment]
```js
import { createInterface } from 'readline';
import { createReadStream } from 'fs';
const readInterface = createInterface(createReadStream('debug.log'));
for await (const line of readInterface) {
 console.log(line)
}
  ```
  
error: events.on is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2679


Also would be great if readline.createInterface can consume Bun.file object instead of ReadStream

**Comment by blackmius** [comment]
```
import { createInterface } from 'readline';
import { createReadStream } from 'fs';
const readInterface = createInterface(createReadStream('debug.log'));
for await (const line of readInterface) {
 console.log(line)
}
  ```
  
error: events.on is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2679

**Comment by adrianord** [comment]
Ran into this issue today on bun 1.0.7 trying to use [dagger](https://dagger.io/).

**Comment by wesleycoder** [comment]
Ran into this while solving my first adventofcode sadly.
Any updates? It seems this is going on since jan #1750

**Comment by Sceat** [comment]
I made a polyfill for `events` which I use in the mean time https://gist.github.com/Sceat/e2c3b3969513bbd62c1dc2ba2a565fbf
