### ISSUE TITLE
Finish implementing `--minify-whitespace`

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2698]
There are a number of edgecases where this currently doesn't work correctly. We add an unnecessary space sometimes. Other times, we don't add the space or semicolon when it needs one (such as when the previous statement was an export statement)

**Comment by paperclover** [comment]
these two bundler tests should be helpful for testing

- `default/MinifiedBundleES6`
- `default/MinifiedBundleCommonJS`
