### ISSUE TITLE
`export * from "./commonjs"` does not run or bundle (Breaks vue)

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2699]
### What version of Bun is running?

0.5.9 and also canary

### What steps can reproduce the bug?

`a.cjs`
```ts
module.exports = { hello: true };
```

`b.mjs`
```ts
export * from './a.cjs';
```

```ts
import * as mod from './b.mjs';
console.log(mod);
```

### What is the expected behavior?

`{ hello: true }`

### What do you see instead?

`{ }`

### Additional information

Breaks importing anything from Vue since it gives an empty object.

![image](https://user-images.githubusercontent.com/24465214/233190372-65cb2e5f-43ad-403c-b0d7-3af14ee52b1b.png)

**Comment by paperclover** [comment]
I believe the issue boils down to how this is transpiled for the runtime:

```ts
export * from "./a.cjs";
```

![image](https://user-images.githubusercontent.com/24465214/233193805-1818d97d-518f-43fd-9771-920db0989ac3.png)

**Comment by paperclover** [comment]
is also a bundler issue

**Comment by Jarred-Sumner** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/709451/233257379-5a0fc423-8018-4971-a04f-26fcbc48700a.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/709451/233257430-4ff1f5b6-d696-4fbd-a37f-5f85bead0437.png">


hmm
