### ISSUE TITLE
Segfault with server.fetch in testing

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#2711]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```

uh-oh: Not implemented yet!!
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.5.9 (f3ab445c) macOS Silicon 22.4.0
TestCommand: dotenv 
Elapsed: 36ms | User: 1819ms | Sys: 410ms
RSS: 42.81MB | Peak: 42.81MB | Commit: 34.62MB | Faults: 3399
----- bun meta -----

0   0x102286788 WTFGetBacktrace
1   ??? Bun__crashReportDumpStackTrace
2   ??? src.report.fatal
3   ??? Zig::GlobalObject::moduleLoaderFetch(JSC::JSGlobalObject*, JSC::JSModuleLoader*, JSC::JSValue, JSC::JSValue, JSC::JSValue)
4   ??? JSC::moduleLoaderFetch(JSC::JSGlobalObject*, JSC::CallFrame*)
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ??? llint_entry
13  ???
14  ??? llint_entry
15  ??? llint_entry
16  ???
17  ??? llint_entry
18  ??? vmEntryToJavaScript
19  ??? JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
20  ??? JSC__JSModuleLoader__loadAndEvaluateModule

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord


```

### Additional information

Does server.fetch call dotenv somewhere because I am never calling it myself. I have not yet managed to make a minimal reproduction repository.

**Comment by simylein** [comment]
I managed to debug a little more and noticed in the console:

<img width="806" alt="Screenshot 2023-05-04 at 22 11 32" src="https://user-images.githubusercontent.com/67859356/236318673-df5166eb-29f4-4de7-ae19-4f3fd9c98875.png">

**Comment by Jarred-Sumner** [comment]
is the code using a `with` statement? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

**Comment by simylein** [comment]
I searched my whole repository and did not find any `with` statements in the code directly. 
I am however using the console for logging and there are a lot of `with` as strings in them. 
Also I am using `bun test` to run tests and again there are a lot of `with` as strings in `expect` functions. 
Any chance one of them escapes the string and slips into sqlite client by mistake?

**Comment by simylein** [comment]
I managed to track down the bug. 

I did stuff like this:
```ts
const response = await server.fetch(new Request(`http://${server.hostname}:${server.port}`));
// some expect calls
```
in my tests and forgot the `http://` prefix in `new Request`.

I think we should improve the validation of the initialization of a new Request.
