### ISSUE TITLE
Bun.write() – "No such file or directory" when writing to non-existent directory

### ISSUE THREAD

**Issue by Nick-Mazuk** [oven-sh/bun#2714]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Try to write to a file inside a folder that doesn't exist. For instance, in the following example the `./non-existent` folder does not exist  before writing this file.

```ts
Bun.write("non-existent/hello.txt", "hello")
```

This produces the following error:

```txt
ENOENT: No such file or directory
```

### What is the expected behavior?

From reading the [docs](https://bun.sh/docs/api/file-io), it's my impression the File I/O APIs are intended to replace Node's `fs` module.

So I'd expect any of the following:

1. The relevant directories are silently created for you, or
2. Bun would provide an API to check if directories exist and create them, or
3. Add docs to say to use the `node:fs` module instead to do this to clarify `Bun.file` is not a complete replacement for the `fs` module.

### What do you see instead?

It just errors.

### Additional information

Lower priority, easy workarounds using the `fs` module.

**Comment by Electroid** [comment]
Agreed on your instinct that it should auto-mkdir by default. We have an issue open for this here: #1493
