### ISSUE TITLE
zig.build is incompatible with zig 0.10.1

### ISSUE THREAD

**Issue by nikkicoon** [oven-sh/bun#2721]
### What version of Bun is running?

0.5.9

### What steps can reproduce the bug?

run `zig build -Drelease-safe=true -Dcpu=baseline  --prefix /usr/work/wip/bun/work/.destdir/usr/pkg` in the repository.

### What is the expected behavior?

zig (version 0.10.1) builds bun.

### What do you see instead?

```
/usr/work/wip/bun/work/bun-bun-v0.5.9/build.zig:138:18: error: root struct of file 'std' has no member named 'Build'
const Build = std.Build;
              ~~~^~~~~~
referenced by:
    build: /usr/work/wip/bun/work/bun-bun-v0.5.9/build.zig:146:18
    runBuild: /usr/pkg/lib/zig/build_runner.zig:231:45
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

### Additional information

I'm working on packaging bun for pkgsrc (http://pkgsrc.org). Your zig.build seem to target a version which is no longer supported as stable/recent release by zig.

**Comment by Jarred-Sumner** [comment]
We use a recent `$HEAD` build of zig: https://bun.sh/docs/project/development#install-zig

Currently that is `0.11.0-dev.2571+31738de28`:

https://github.com/oven-sh/bun/blob/de3316f9d700ac2949de077046a06ab0bc848c6f/Dockerfile#L15

**Comment by nikkicoon** [comment]
so 0.5.9 just needs a backported patch for build.zig, this was fixed after the 0.5.9 release?

**Comment by Jarred-Sumner** [comment]
Unfortunately, there were many breaking changes to Zig between 0.10.1 and 0.11.0 and we're not going to support Zig 0.10.1. It won't be as simple as a build.zig change

**Comment by nikkicoon** [comment]
Okay, thanks for the information. Since 0.11.0 will be out soon enough, I'll wait.
