### ISSUE TITLE
bun run does not work with docker volume mount

### ISSUE THREAD

**Issue by jnewbigin** [oven-sh/bun#2725]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 6.2.7-1.el7.elrepo.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

`package.json`
```json
{
  "name": "test",
  "scripts": {
    "test": "echo test",
  }
}
```

`docker run -ti --rm -v $(pwd):/work -w /work oven/bun:0.5.9 run`

### What is the expected behavior?

```
test scripts:

 bun run test
   echo test

1 scripts
```

### What do you see instead?

```
No "scripts" in package.json found.
```

### Additional information

If you copy the `package.json` file into the docker container, it works as expected.
```
docker run -ti --rm -v `pwd`:/work -w /work oven/bun:0.5.9 bash
cp package.json /tmp
cd /tmp
bun run
```

I am unable to compare with running `bun` outside of docker because I am using CentOS-7 which is only `glibc-2.17`

**Comment by tcarrio** [comment]
This appears to be an issue that comes up when trying to use `Bun.file(...)` to open a file that is mounted into a Docker container as well.

**Comment by tcarrio** [comment]
Or, when mounting a TS file and trying to execute it within the container, it also fails, similar to if the file was in a directory that was mounted.

Also, Docker Desktop v4.9.1 (81317) on macOS 13.3.1 (a) (22E772610a) on M1 (arm64) hardware.
