### ISSUE TITLE
Implement `crypto.generateKeyPairSync`

### ISSUE THREAD

**Issue by u9g** [oven-sh/bun#2730]
### What is the problem this feature would solve?

Would stop `const keyPair = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' })` from throwing
```
TypeError: crypto.generateKeyPairSync is not a function. (In 'crypto.generateKeyPairSync("ec", { namedCurve: "P-256" })', 'crypto.generateKeyPairSync' is undefined)
```

### What is the feature you are proposing to solve the problem?

Implement `crypto.generateKeyPairSync`

### What alternatives have you considered?

Not sure

**Comment by urasdbwd** [comment]
do this

**Comment by Kirill89** [comment]
Currently, this issue is a blocker for me to migrate to Bun.

**Comment by kaduvert** [comment]
yes, same. this is very important!
