### ISSUE TITLE
`http.request` `socketPath` seems not working

### ISSUE THREAD

**Issue by loynoir** [oven-sh/bun#2734]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 6.1.22-1-lts x86_64 unknown

### What steps can reproduce the bug?

```
import http from 'node:http'

void http.request(
  'http://localhost/version',
  {
    socketPath: '/var/run/docker.sock',
  },
  (res) => res.on('data', (c) => console.log('' + c)),
).end()
```

### What is the expected behavior?

Node successfully request docker api.
```sh
$ node reproduce.mjs
{"Platform":{"Name...
```

### What do you see instead?

Bun output nothing.
```sh
$ bun reproduce.mjs
$
```

### Additional information

Related package: `dockerode`

**Comment by chrisvander** [comment]
Can corroborate - attempting to use Dockerode in a project and I get 
```bash
❯ bun ./server/middleware/development/dbDocker.ts
[0.04ms] ".env"
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost/containers/json"
```

I also tried the same reproduction above, leading to the same result with Bun outputting nothing. macOS 13.5.2, Bun 1.0.0

**Comment by mmadson** [comment]
this also affects the popular testcontainers library as it's nodejs implementation relies on dockerode.

https://testcontainers.com/

**Comment by loynoir** [comment]
Related 

[feat] Make backend js ecosystem future better

https://github.com/nodejs/node/issues/50195

**Comment by julia-script** [comment]
yea..having the same issue here.

here's my very nasty  temporary solution if that is of any help

I'm only doing queries, but should be simple to adapt it for other use cases

```tsx
const dockerFetch = async (endpoint: string) => {
  const proc = Bun.spawn(
    [
      "curl",
      "--unix-socket",
      "/var/run/docker.sock",
      `http://localhost${endpoint}`,
    ],
    {
      stdio: ["pipe", "pipe", "pipe"],
    },
  );
  await proc.exited;

  return new Response(proc.stdout).json() as unknown;
};

await dockerFetch(
  "/v1.24/containers/json",
);
```
