### ISSUE TITLE
Segmentation fault on node:fs/promises.writeFile()

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#2735]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 4.4.0-1104-aws x86_64 x86_64

### What steps can reproduce the bug?

On some (but not all) files submitted by users, I'm getting a segmentation fault. Code is like this:

```js
import * as fs from 'node:fs/promises'
(async() => {
  // ... need this in a server POST handler
  const data = await req.formData()
  const file = data.get('file')
  await fs.writeFile('./path/to', await file.arrayBuffer())
 // ...
})()
```

I'm getting a `TypeError: Request aborted` with code `ABORT_ERR`, then `5 Segmentation fault` appearing in my log.

I can't use `Bun.write()` due to Heroku being stuck on Linux kernel 4.4.

**Comment by cirospaciari** [comment]
@jakeg can you check if still occurring in the lastest canary? you can upgrade to it using `bun upgrade --canary`

**Comment by npetillon** [comment]
Same things here. With the lastest canary version too.

**Comment by simylein** [comment]
Is this still happening with bun 0.7.0?

**Comment by Electroid** [comment]
This is actually like a crash with FormData, which was fixed. #2499 If you are still running into this issue, please feel free to re-open and we'll investigate.

**Comment by jakeg** [comment]
Heoku now supports io_uring so node:fs no longer needed
