### ISSUE TITLE
Remainder % operator incorrect for negative operands

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#2738]
### What version of Bun is running?

0.5.9

### What steps can reproduce the bug?

```js
console.log('8 % 3:', 8 % 3)
console.log('-8 % 3:', -8 % 3)
console.log('8 % -3:', 8 % -3)
console.log('-8 modulus 3:', ((n, d) => ((n % d) + d) % d)(-8, 3))
```

### What is the expected behavior?

```
8 % 3: 2
-8 % 3: -2
8 % -3: 2
-8 modulus 3: 1
```

### What do you see instead?

```
8 % 3: 2
-8 % 3: 1
8 % -3: 0
-8 modulus 3: 1
```

### Additional information

When either operand is negative, the result is incorrect.

**Comment by Jarred-Sumner** [comment]
lol this is probably a transpiler bug

**Comment by Jarred-Sumner** [comment]
yep, transpiler bug

<img width="508" alt="image" src="https://user-images.githubusercontent.com/709451/234300457-aebe3479-7efb-46c4-b20b-bbfc01e8fc8b.png">
