### ISSUE TITLE
`bun install` failing when cloneifle is unavailable.

### ISSUE THREAD

**Issue by piano1029** [oven-sh/bun#2749]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

- Create a Bun project on an external APFS volume
- Run `bun install`

### What is the expected behavior?

Installing the packages

### What do you see instead?

bun install v0.6.0 (ab447e4f)
Failed to install 2 packages
error: Unexpected installing bun-types
error: Unexpected installing hono
[7.00ms] done

**Comment by Electroid** [comment]
We fixed this in a previous release. If you're still experiencing this issue, please feel free to re-open.
