### ISSUE TITLE
NextJS version doesn't work with tailwindcss

### ISSUE THREAD

**Issue by AndreBastos23** [oven-sh/bun#275]
Hello!

I just tried creating a NextJS app with tailwind using the recommended bun command `bun create next ./app`, and then following the tailwindcss documentation with NextJS, and it doesn't look like bun is picking up the tailwind classes.

Not sure why this is happening, since there isn't any kind of logging going on.

Steps to reproduce:
1. run `bun create next ./app`
2. run `cd ./app`
3. run `bun add -D tailwindcss postcss autoprefixer`
4. run `npx tailwindcss init -p`
5. Change the `content` property in `tailwind.config.js` to `./pages/**/*.{ts,tsx,js,jsx}`
6. Go to a `pages/index.tsx` and try adding a tailwind css class to a DOM element

**Comment by jsjoeio** [comment]
In Step 3, that should be a lowercase `-d` (I think).

When I used the `next` template, I noticed this in the output: 

```sh
# When dependencies change, run this to update node_modules.bun:

bun bun --use next
```

Did you try that?

**Comment by AndreBastos23** [comment]
> In Step 3, that should be a lowercase `-d` (I think).
> 
> When I used the `next` template, I noticed this in the output:
> 
> ```shell
> # When dependencies change, run this to update node_modules.bun:
> 
> bun bun --use next
> ```
> 
> Did you try that?

Didn't try this, I also didn't saw this warning. Let me check

**Comment by poberbeck** [comment]
I can confirm that there is a problem using Tailwind. I also tried to run `bun bun --use next` with no results. Maybe PostCSS is the problem? But this is only a guess. ✌️

**Comment by aniket-jena-dev** [comment]
it says `To use Tailwind with bun, use the Tailwind CLI and import the processed .css file.` in the console

**Comment by AndreBastos23** [comment]
I'll close this since people already answered how to use tailwind with Bun! Thanks everyone
