### ISSUE TITLE
Better error message when attempting to reassign a const

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#2760]
### What is the problem this feature would solve?

Error message when reassigning a `const` is not ideal.

### What is the feature you are proposing to solve the problem?

```js
const x = 5; x = 2
```
gives error (in v0.5.9):
 `SyntaxError: Left side of assignment is not a reference.`

but Chrome, Deno etc give more useful error
 `error: Uncaught TypeError: Assignment to constant variable.`

**Comment by Jarred-Sumner** [comment]
wdyt about this

<img width="395" alt="image" src="https://user-images.githubusercontent.com/709451/234855658-b8b29fc9-cb04-4d63-81a3-87b5a3779fa9.png">

**Comment by jakeg** [comment]
sweet!
