### ISSUE TITLE
Bun.build() is not a function

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#2762]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.4.0-1105-azure x86_64 x86_64

### What steps can reproduce the bug?

- Install Bun
- Run `bun init`
- Run `bun install`
- Add `bun-types` to `tsconfig.json`
- In main ts file, add:
```ts
await Bun.build({
  entrypoints: ['./index.tsx'],
  outdir: './build',
});
```

### What is the expected behavior?

The filepaths listed in `Bun.build.entrypoints` should be transpiled to `Bun.build.outdir`.

### What do you see instead?

The `Bun.build()` function is undefined and does not exist.

### Additional information

This issue happened both with VSCode intellisense and when running the file.

**Comment by Jarred-Sumner** [comment]
Bun build is in Bun v0.6.0, which is the canary build
