### ISSUE TITLE
Performance issue with division

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#2769]
From #2768 I've narrowed it down to division, and it can be ~15x slower than Deno!

```js
let time = (name, func) => { console.time(name); func(); console.timeEnd(name) }
for (let divisor = 2; divisor <= 10; divisor++) {
  time(`Division by ${divisor}`, () => { let n; for (let i = 1; i < 200000000; i++) n = i / divisor })
}
```

Deno:
```
Division by 2: 179ms
Division by 3: 179ms
Division by 4: 68ms
Division by 5: 65ms
Division by 6: 63ms
Division by 7: 68ms
Division by 8: 108ms
Division by 9: 67ms
Division by 10: 66ms
```

Bun (v0.5.9 on WSL):
```
[1169.79ms] Division by 2
[1118.11ms] Division by 3
[1045.81ms] Division by 4
[1116.08ms] Division by 5
[1142.23ms] Division by 6
[1122.19ms] Division by 7
[1047.59ms] Division by 8
[1104.51ms] Division by 9
[1105.55ms] Division by 10
```

If we switch `/` division out for `%` remainder (or any of `* + -`) performance is fine.

**Comment by Jarred-Sumner** [comment]
This is a constant propagation thing that is unlikely to have any real world impact outside of a microbenchmark like this, not division. V8 is detecting the code is doing nothing because the variable doesn't escape the scope and it is optimizing away parts of the inner loop

Note how the performance becomes essentially the same if the value escapes the scope

```js
let time = (name, func) => { console.time(name); func(); console.timeEnd(name) }
for (let divisor = 2; divisor <= 10; divisor++) {
  var n = 10_000;
  time(`Division by ${divisor}`, () => {  for (let i = 1; i < 200000000; i++) n /= i / divisor })
  globalThis.n = n;
}
```

**Comment by tomByrer** [comment]
> If we switch `/` division out for `%` remainder (or any of `* + -`) performance is fine.

I guess you could make an ESLint rule or the like on your end?

I get it though; when I used to optimize DSP ASM, I constantly swapped out a `div 4` for `mul 0.25`.  I still do something similar when building animation loops in JS.

**Comment by ThePrimeagen** [comment]
a really really really good rule of thumb is the following.

if it bares out a problem with micro benchmarks, it has a 99.9% chance of being irrelevant or a lie

create a server, make millions of requests, and see if you can impact RPS.  that is where the truer version of performance comes to play.

apache bench, sets of 20k requests, take the average of the medians of ~15 rounds of this, see where you land
