### ISSUE TITLE
nextjs's api routes doesn't work 

### ISSUE THREAD

**Issue by fdemir** [oven-sh/bun#277]
**Issue**

API Routes doesn't work with bun.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/48316033/177611623-a178c2cf-2c72-4d3f-acb6-0447fcb44997.png">

**Reproduction**
1. create a project with `bun create next api-routes`
2. go to project folder `cd api-routes`
3. create API folder under pages.
4. add an example API route called `hello.ts`
5. add an example handler to hello 
```js
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

type Data = {
  name: string
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  res.status(200).json({ name: 'John Doe' })
}

```

**Comment by njbraun** [comment]
It looks as though api handlers for nextjs, while called, are called with invalid arguments. req and res are empty objects.

Seems as though it's treating api routes the same as pages:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/154621/177688829-0afbf372-b448-42c5-a156-80b3ca071060.png">

**Comment by fdemir** [comment]
I've just investigated and read the bun-framework-next code. But it looks so complicated I cannot resolve the issue. Need help.
