### ISSUE TITLE
Bun.file just not working for me

### ISSUE THREAD

**Issue by atinseau** [oven-sh/bun#2775]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.4.0-147-generic x86_64 x86_64

### What steps can reproduce the bug?

this is my code

main.ts:

const output = Bun.file('test.txt');
await output.text()

test.txt:

hi

i get this

EBADF: Bad file number
   path: "test.txt"
syscall: "open"
  errno: -9

why ?

### What is the expected behavior?

//

### What do you see instead?

//

### Additional information

//

**Comment by Jarred-Sumner** [comment]
> Linux 5.4.0-147-generic x86_64 x86_64

Can you try on a more recent Linux kernel? Something >= 5.15

**Comment by wavded** [comment]
Had similar issue. Can confirm that Kernel 5.15 fixed it for me.

**Comment by atinseau** [comment]
> Had similar issue. Can confirm that Kernel 5.15 fixed it for me.

I ll check, thanks you

**Comment by Electroid** [comment]
Duplicate of #1446
