### ISSUE TITLE
Module resolution bug 

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#2784]
### What version of Bun is running?

Canary

### What steps can reproduce the bug?

```
$ bun add @heroicons/react
```

```ts
// index.tsx
import {CheckIcon} from '@heroicons/react/24/solid';
console.log(<CheckIcon />);
```

```sh
$ bun run index.tsx
SyntaxError: Import named 'CheckIcon' not found in module '/path/to/dir/node_modules/@heroicons/react/24/solid/index.js'.
```

**Comment by paperclover** [comment]
notes:
- `@heroicons/react/24/solid/index.js` works
- `import * as icons from '@heroicons/react/24/solid'`
  - `icons` is `{ default: () => ({ CheckIcon, ... }) }`
- runtime only, this file can be bundled (though it wont tree shake the other icons :/)

**Comment by birkskyum** [comment]
When I run this, I just get:

```sh
➜ bun run index.tsx
<NoName />
```

Using `import {CheckIcon} from '@heroicons/react/24/solid';`, without the `index.js`, I can embed it in a react app.

<img width="468" alt="Screenshot 2023-09-07 at 00 08 43" src="https://github.com/oven-sh/bun/assets/74932975/f8cf33d0-39dc-4613-9f0f-5ac5a55e6d16">
