### ISSUE TITLE
browserGlobal.fetch.bind is not a function

### ISSUE THREAD

**Issue by dilutedev** [oven-sh/bun#2794]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Errors while running application with [Node-Fetch](https://www.npmjs.com/package/node-fetch) as a dependency

### What is the expected behavior?

App running on port ...

### What do you see instead?

3 |     return (mod && mod.__esModule) ? mod : { "default": mod };
4 | };
5 | // istanbul ignore file
6 | var node_fetch_1 = __importDefault(require("node-fetch"));
7 | var browserGlobal = typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : null; // self is the global in web workers
8 | module.exports = !browserGlobal ? node_fetch_1.default : browserGlobal.fetch.bind(browserGlobal);
                                                             ^
TypeError: browserGlobal.fetch.bind is not a function. (In 'browserGlobal.fetch.bind(browserGlobal)', 'browserGlobal.fetch.bind' is undefined)

**Comment by SuperKruse** [comment]
[ky](https://github.com/sindresorhus/ky) returns almost the same error

```
119 |             // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
120 |             prefixUrl: String(options.prefixUrl || ''),
121 |             retry: normalizeRetryOptions(options.retry),
122 |             throwHttpErrors: options.throwHttpErrors !== false,
123 |             timeout: typeof options.timeout === 'undefined' ? 10000 : options.timeout,
124 |             fetch: options.fetch ?? globalThis.fetch.bind(globalThis),
                                        ^
TypeError: globalThis.fetch.bind is not a function. (In 'globalThis.fetch.bind(globalThis)', 'globalThis.fetch.bind' is undefined)
```
