### ISSUE TITLE
incorrect DCE of destructuring catch scope variables

### ISSUE THREAD

**Issue by kzc** [oven-sh/bun#2795]
### What version of Bun is running?

2250f7a0c04e554234e2f32f8c251c665594e12a

### What platform is your computer?

Darwin 18.7.0 x86_64 i386

### What steps can reproduce the bug?

```
$ cat destructuring-catch-scope.js
let a = 1;         // mistakenly dropped
let def = "PASS2"; // mistakenly dropped
try {
    throw [ "FAIL2", "PASS1" ];
} catch ({ [a]: b, 3: d = def }) {
    let a = 0, def = "FAIL3";
    console.log(b, d);
}
```
```
$ bun destructuring-catch-scope.js
PASS1 PASS2
```
```
$ bun build destructuring-catch-scope.js | tee out.js
// destructuring-catch-scope.js
try {
  throw ["FAIL2", "PASS1"];
} catch ({ [a]: b, 3: d = def }) {
  let a = 0, def = "FAIL3";
  console.log(b, d);
}
```

### What is the expected behavior?

`bun out.js` should produce: `PASS1 PASS2`

### What do you see instead?

```
$ bun out.js
1 | // destructuring-catch-scope.js
2 | try {
3 |   throw ["FAIL2", "PASS1"];
4 | } catch ({ [a]: b, 3: d = def }) {
               ^
ReferenceError: Can't find variable: a
```

### Additional information

See https://github.com/evanw/esbuild/blob/main/scripts/uglify-tests.js as an example of how to validate a minifying bundler against uglify's test suite.

**Comment by Jarred-Sumner** [comment]
Thank you for the bug report

The canary build of Bun has a very different minifier implementation which is enabled via `bun build --minify-syntax`, `bun build --minify`, `bun build --minify-identifiers`, `bun build --minify-whitespace` (same flags as esbuild)

**Comment by kzc** [comment]
`bun build` appears to perform DCE even without any minify flag?

Any way to disable that behavior?

**Comment by Jarred-Sumner** [comment]
In v0.5.9, no

In v0.6.0 (canary), it should do a limited amount of DCE but not very much

**Comment by kzc** [comment]
Isn't the bun binary artifact from the commit https://github.com/oven-sh/bun/commit/2250f7a0c04e554234e2f32f8c251c665594e12a essentially a "canary" build from yesterday?

```
$ bun -v
0.6.0
```
