### ISSUE TITLE
Support returning multiple ASTs in one parse

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#2800]
At the time of writing, there are two situations where transpiling one file using Bun's JS parser _should_ result in multiple ASTs but do not.

### `Bun.plugin`

Currently, `Bun.plugin` makes this work by splitting the `Bun.plugin` function callbacks into a separate list of statements. Since the transpiler doesn't run the symbol renamer, we don't need to track scopes, declared symbols etc or a bunch of other features quite as much. From there, it does some very limited DCE to skip any top-level statements which clearly are not part of the plugin (and vice versa)

The other case is `"use server"`. 

### `"use server"`

There's really no sound way without two separate ASTs that have different `*Scope`, import records and so forth.

```tsx
async function respond(formData: FormData) {
   "use server";
    return { data: { hey: formData.get("hey") } };
}

function Hey() {
  return <button onClick={() => console.log(respond)}>hey</button>
}
```

This approach will also let us support multiple build configurations that build the same file. For Server Components, we may need to build the same files three times:
1) RSC build `("use server")`
2) SSR build (consume the RSC vDOM stream on the server, rendering HTML)
3) browser build (consume the RSC vDOM stream on the client)

We don't actually need to parse three times. We can do this in one parse pass. We _might_ need to do up to two visiting passes. 

One idea that comes to mind for implementing this:

`ModuleBlock` as a `Stmt.Data` type. A `"use server"` or `"use client"` directive at the start of a function statement becomes a `"ModuleBlock"`. Then JS parser would have something like:
```zig
const ModuleBlockResolver = struct {
    onResolve: *const fn(*anyopaque, UseDirective) Resolution;
    ctx: *anyopaque,
};

const Resolution = union(enum) {
    module: Parser.Options,
    err: anyerror,
    identity: void // when "use server" is used inside a "use server"
}; 
```

**Comment by paperdave** [comment]
This issue is stale. All of the ideas above are no longer applicable.
