### ISSUE TITLE
HMR renames imports wrong for static HTML

### ISSUE THREAD

**Issue by tomByrer** [oven-sh/bun#2812]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Linux 6.2.6-pikaos x86_64 x86_64

### What steps can reproduce the bug?

plain html files with some CSS & JS in root directory:
https://github.com/tomByrer/ldt-highlight-demo/tree/initial
`bun dev`

### What is the expected behavior?

https://qbit.works/LDT/examples/generic.html
This is also how it looks locally using another package:
https://github.com/lwsjs/local-web-server

### What do you see instead?

It does find the `index.html` fine; HTML textarea shows, but blank because the JS in the HTML file could not find the `Parser.js` file &/or `Parser()` function.

Seems HMR import renaming makes it not render properly:
```bash
caught ReferenceError: HMR_ce7bf0fbcae8180a is not defined
    at Parser.js:1:28
TextareaDecorator.js:1 Uncaught ReferenceError: HMR_ce7bf0fbcae8180a is not defined
    at TextareaDecorator.js:1:28
(index):23 Uncaught ReferenceError: Parser is not defined
    at (index):23:17
```
**in browser** `Parcer.js`:
```js
var hmr_35bc09afeb282330 = new HMR_ce7bf0fbcae8180a(2777576416, "Parser.js"), exports = hmr_35bc09afeb282330.exports;
(hmr_35bc09afeb282330._load = function() {
  let Parser = function(rules, i) {
...
```
in browser `TextareaDecorator.js`
```js
var hmr_35bc09afeb282330 = new HMR_ce7bf0fbcae8180a(1098453777, "TextareaDecorator.js"), exports = hmr_35bc09afeb282330.exports;
(hmr_35bc09afeb282330._load = function() {
  let TextareaDecorator = function(textarea,
...
```

### Additional information

v0.6.0 (nightly last night)
running in Bash in VSCode in Ubuntu 22.10 fork

low priority, but hopefully by v1.0 :)
TIA

**Comment by mfcochauxlaberge** [comment]
I have the exact same issue. I thought I was able to have a single page hot reload using `bun dev` in the past, but I'm not sure. It was a while ago.

It seems like it's trying to do that, given the generated JS code mentioning `HMR`, but it fails unfortunately.

**Comment by Electroid** [comment]
This issue was caused by running `bun dev`, which was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
