### ISSUE TITLE
incorrect build output for var redeclaration in catch block

### ISSUE THREAD

**Issue by kzc** [oven-sh/bun#2815]
### What version of Bun is running?

0.6.0 canary

### What platform is your computer?

macos 10.14

### What steps can reproduce the bug?

given:
```
$ cat catch.js 

    "use strict";
    var x = 1;
    try {
        console.blog;
    } catch (x) {
        var x = 2;
    }
    console.log(x);

    var e = 3;
    try {
        console.log("try2");
    } catch (e) {
        var e = 4;
    }
    console.log(e);

    try {
        var z = 5;
        throw "try3";
    } catch (w) {
        z += w;
        var w = 6;
    }
    console.log(z);

    var c = 8;
    try {
        "try4";
    } catch (c) {
        var c = 9;
    }
    console.log(c);
```
expected:
```
$ bun catch.js 
1
try2
3
5try3
8
```
actual:
```
$ bun build catch.js | tee out.js
// catch.js
try {
  console.blog;
} catch (x) {
  x2 = 2;
}
var x2;
console.log(x2);
try {
  console.log("try2");
} catch (e) {
  e2 = 4;
}
var e2;
console.log(e2);
try {
  z = 5;
  throw "try3";
} catch (w) {
  z += w2;
  w2 = 6;
}
var z;
var w2;
console.log(z);
console.log(c);
```
```
$ bun out.js
undefined
try2
undefined
NaN
21 |   w2 = 6;
22 | }
23 | var z;
24 | var w2;
25 | console.log(z);
26 | console.log(c);
               ^
ReferenceError: Can't find variable: c
```

**Comment by kzc** [comment]
Thanks @dylan-conway. The original problem as reported above no longer occurs.

However, there's a different but related bug in latest canary when the [same `catch.js` input](https://github.com/oven-sh/bun/issues/2815#issue-1699129693) is run through `--minify`.  I thought it'd be easier to report it here rather than opening another ticket...

expected:
```
$ bun catch.js
1
try2
3
5try3
8
```
```
$ bun build catch.js > out.js && bun out.js
1
try2
3
5try3
8
```
minify actual:
```
$ bun build catch.js --minify > out.js && bun out.js
1
try2
3
NaN
8
```
Here's a simplified test case...
```
$ cat catch3.js
    "use strict";
    try {
        var z = 5;
        throw "try3";
    } catch (w) {
        z += w;
        var w = 6;
    }
    console.log(z);
```
expected:
```
$ bun catch3.js 
5try3
```
actual:
```
$ bun build catch3.js --minify > out.js && bun out.js
NaN
```
```
$ cat out.js
try{throw l=5,"try3"}catch(c){l+=o;var o=6}var l;console.log(l);
```

**Comment by dylan-conway** [comment]
Interesting, identifier minification is changing `w` in the catch scope and not in the binding. Thanks, we'll fix this soon

**Comment by kzc** [comment]
The catch tests above are just a sample.  If you run `make uglify` from https://github.com/oven-sh/bun/issues/2807#issuecomment-1537201530 with latest bun canary you'll still see a couple dozen `catch` scope and binding errors.  `catch` behavior in the ES spec is pretty convoluted.
