### ISSUE TITLE
Node compatibility: stdout.rows and stdout.columns

### ISSUE THREAD

**Issue by xixixao** [oven-sh/bun#2816]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Create a file `test.js`
```js
console.log(process.stdout.rows);
```

Run it via `node test.js` and `bun test.js`. 

### What is the expected behavior?

It should print the number of rows in the terminal.

### What do you see instead?

undefined

**Comment by Electroid** [comment]
Implemented in 728c8fdcdb4e9276a7bd0721bad3b5d0cbed67fa and will be available in the next release, v0.7, or now if you run: `bun upgrade --canary`
