### ISSUE TITLE
`Error.stack` does not use source map

### ISSUE THREAD

**Issue by mitsuhiko** [oven-sh/bun#2818]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

I was trying to figure out reported column offsets in bun (see https://github.com/source-map/source-map-rfc/issues/5#issuecomment-1538000188). For some reason I get wrong line numbers and columns. Reported:

```js
function fail() {
  throw new Error();
}

function logColumn(c, e) {
  const lines = e.stack.split(/\r?\n/g);
  if (lines[0] === 'Error') {
    lines.shift();
  }
  console.log(c, parseInt(lines[1].match(/:\d+:(\d+)/)[1]));
}

try {
  /* xxxxx */fail();
} catch (e) {
  logColumn("x", e);
}
try {
  /* ☃️☃️☃️☃️☃️ */fail();
} catch (e) {
  logColumn("☃️", e);
}
try {
  /* 🔥🔥🔥🔥🔥 */fail();
} catch (e) {
  logColumn("🔥", e);
}
try {
  /* 👩‍👩‍👧👩‍👩‍👧👩‍👩‍👧👩‍👩‍👧👩‍👩‍👧 */fail();
} catch (e) {
  logColumn("👩‍👩‍👧", e);
}
```

### What is the expected behavior?

Expected

```
x 14
☃️ 19
🔥 19
👩‍👩‍👧 49
```

### What do you see instead?

```
x 7
☃️ 7
🔥 7
👩‍👩‍👧 7
```

### Additional information

If you add some print on the lines you can see that not just the columns are wrong, the lines are too.

**Comment by Jarred-Sumner** [comment]
Source maps are not yet integrated into `Error.prototype.stack` - what you're seeing is the stack from the transpiled source in JavaScriptCore

You can use `Error.captureStackTrace` or `console.error` to get a source-mapped error
