### ISSUE TITLE
Illegal hardware instruction in wsl2 ubuntu

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#282]
![image](https://user-images.githubusercontent.com/92968534/177621496-3bf8ebab-a911-49a3-81a0-0419b2a8de6c.png)

**Comment by kaduvert** [comment]
same problem with manjaro zsh
![grafik](https://user-images.githubusercontent.com/70949550/177626299-f28897e6-2b13-4591-855b-03a018d07807.png)

**Comment by Guztaver** [comment]
same problem in Arch Linux kernel `5.18.9-zen1-1-zen`, bun version `0.0.1`
![image](https://user-images.githubusercontent.com/39814943/177629726-e5177a77-323f-4077-ad5c-53b56df0cf4c.png)

**Comment by vonlooten** [comment]
same problem with linux mint 

![image](https://user-images.githubusercontent.com/5501855/177629825-ecf64737-7550-44eb-8a75-1e71ea4d382f.png)

**Comment by chocsx** [comment]
WSL2
Ubuntu 20.04.4 LTS

![image](https://user-images.githubusercontent.com/5263969/177630198-0459df6e-93d1-4325-be54-d10ad082db90.png)

**Comment by skamansam** [comment]
I am getting the same error on Fedora 36. (not WSL). already have the path set up:

```
[sam@rbe]$ rm -rf ~/.bun
[sam@rbe]$ curl https://bun.sh/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4906    0  4906    0     0  28786      0 --:--:-- --:--:-- --:--:-- 28858
######################################################################## 100.0%
Bun was installed successfully to /home/sam/.bun/bin/bun
Run 'bun --help' to get started
[sam@rbe]$ bun --help
	    --use <STR>Illegal instruction (core dumped)
[sam@rbe]$ bun --vesion
Illegal instruction (core dumped)
[sam@rbe]$ which bun
~/.bun/bin/bun
```

**Comment by Guztaver** [comment]
Actualy, the problem is because the CPU needs to have "AVX2", and olders CPU didn't have it. Is REALLY sad, but is the truth. 
Is in the roadmap to add AVX(1) support since 09/2021, but until now, none "progress".

**Comment by skamansam** [comment]
@Guztaver confirmed that my cpu does not have avx2 flag. :( Thank you!

**Comment by athalas** [comment]
So sad that a new promising project like this has already these limitations. My CPU (Core I3 3570) works perfecly fine for all of my work and developments, and much more complex tasks than this, yet it is unable to run bun at first try? Come on... Why not also ask for TPM2 too, btw?.

Jokes and irony aside, please consider your target systems and don't limit a promising project to just "latest hardware". We can live without RTX 3090 and AVX2 easily.

I'd join the request and really would appreciate and test a compiled version without these requirements.

**Comment by logikaljay** [comment]
Foreword: I know very little about CPU instructions.

With that being said, I imagine the speed improvements that this project has been able to make are partly due to the fact that it is targeting the new capabilities in "modern" CPUs.

I say "modern" in quotes, because `avx2` has been available in Intel CPUs since Q2 2013, and AMD CPUs since Q2 2015.

I imagine that there are a lot of people with older hardware that are frustrated they can't use `bun`. To them I would say: Maybe buy a new computer? If it is a tool you are using for education and/or professionally, then you should always invest in your tools.

You will get a lot more benefit from a more "modern" computer than just being able to run `bun`.

I wrote and rewrote this comment 3 times trying to make it sound better. 
I mean no offense to anyone.
I also don't wish to discredit the authors work by saying the speed of `bun` is due to `avx2`, but I am sure there was a reason it was targeted.

**Comment by Guztaver** [comment]
> Foreword: I know very little about CPU instructions.
> 
> With that being said, I imagine the speed improvements that this project has been able to make are partly due to the fact that it is targeting the new capabilities in "modern" CPUs.
> 
> I say "modern" in quotes, because `avx2` has been available in Intel CPUs since Q2 2013, and AMD CPUs since Q2 2015.
> 
> I imagine that there are a lot of people with older hardware that are frustrated they can't use `bun`. To them I would say: Maybe buy a new computer? If it is a tool you are using for education and/or professionally, then you should always invest in your tools.
> 
> You will get a lot more benefit from a more "modern" computer than just being able to run `bun`.
> 
> I wrote and rewrote this comment 3 times trying to make it sound better. I mean no offense to anyone. I also don't wish to discredit the authors work by saying the speed of `bun` is due to `avx2`, but I am sure there was a reason it was targeted.

you need to understand one thing, the project release the 0.0.1 today, be calm bro, `bun` will be available to `avx` soon or later

**Comment by athalas** [comment]
Thanks @logikaljay for your quick & detailed reponse, also to @Guztaver.

First, sorry for the rant, I got just excited by bun and wanted to test because I see its potential and looks very promising. I got frustrated by the technicality and wrote on the rage, something you should not do in any way, so apologies for that.

I understand the benefits of new CPUs and for sure using them would be important to improve performance. That said, I still think that AVX2 requirement would seriously limit so many devices I'd like to run bun on. I have a recent Mac with AVX2, but I usually work my side projects on this other computer, and deploy them to a NAS also without AVX2 (see? two examples). I can run node on them, so I thought I should aim to replace node with bun also on these for the evident benefits etc.

I hope that my stupid rant do not demoralize you in any way. Your project looks amazing, and I just look forward to see it working soon.

**Comment by logikaljay** [comment]
Two very good usecases @athalas, I do this myself with my synology NAS.

I also just spun up a `c6g.medium` instance on AWS and was unable to run `bun`, but I am not sure why I expected something different, given there is no mention of support for linux on arm.

```
[user@graviton-test ~]$ cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1
```

```
[user@graviton-test ~]$ file `which bun`
/home/user/.bun/bin/bun: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, stripped
```

**Comment by hrmtn** [comment]
Possible duplicate of #67

**Comment by Guztaver** [comment]
> Thanks @logikaljay for your quick & detailed reponse, also to @Guztaver.
> 
> First, sorry for the rant, I got just excited by bun and wanted to test because I see its potential and looks very promising. I got frustrated by the technicality and wrote on the rage, something you should not do in any way, so apologies for that.
> 
> I understand the benefits of new CPUs and for sure using them would be important to improve performance. That said, I still think that AVX2 requirement would seriously limit so many devices I'd like to run bun on. I have a recent Mac with AVX2, but I usually work my side projects on this other computer, and deploy them to a NAS also without AVX2 (see? two examples). I can run node on them, so I thought I should aim to replace node with bun also on these for the evident benefits etc.
> 
> I hope that my stupid rant do not demoralize you in any way. Your project looks amazing, and I just look forward to see it working soon.

you don't demoralized me, i understand and really is a bad don't have this, only time will help us now

**Comment by renhiyama** [comment]
Found a fix!
Illegal hardware instruction happens when you have an old cpu, as in my case: its Intel Pentium CPU...
Here's the fix for make bun work perfectly!

`<path/to/sde/installation>/sde64 -chip-check-disable -- bun` works perfectly!

For users who dont want to write such long line, they can make an `alias` and add it to your .bashrc or .zshrc ;)

```
alias sde='~/sde-external-9.7.0-2022-05-09-lin/sde64'
alias bun='sde -chip-check-disable -- bun'
```

and after restarting your shell, run `bun` and it just works perfectly, just like you have no problems in the first place :)


You can download the sde by running these lines btw:
```
 wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz
tar -xf sde-external-9.7.0-2022-05-09-lin.tar.xz
```
run the above in ur home folder, or edit the alias urself to keep the paths updated ;)


On an alternative note, I think compiling js/ts files are slow as hell, just as rust language...
Nodejs would start `console.log("Hello")` within 1-2 secs of typing `node index.js`
But thats not the case with bun, atleast not when you are using sde (The compability layer for avx2)
It took 6-7 secs to run that for me... Rust takes that time to build their hello world app!

**Comment by Otrex** [comment]
Thanks @renhiyama your solution worked like a charm

**Comment by athalas** [comment]
(jaw on the floor!)

@renhiyama your solution works.

p.s. I love you 😄 

thank you very much, and thanks for sharing.

So basically you need to install the package that he mentions and then run bun thru the sde64 binary with the command he wrote... and it works wonderfully. 👍

**Comment by zekefeu** [comment]
I've made a script to simplify and automate SDE's installation based on @renhiyama's solution, lmk if there's anything to fix.

`$ curl https://gist.githubusercontent.com/fuka-g/afb29296db34d2451cdddcc14dbeef3c/raw/0c9e5d43910cf53b9bd82b358559bb8b75ebbfdc/bun-sde-fix-install_script.sh | bash`

EDIT: Updated script, this one is up to date.

**Comment by FinnRG** [comment]
@renhiyama  @fuka-g  Could you two please post your solution in #67? I'm closing this issue now, because we really don't need three AVX2 issues with the same content.

**Comment by AndrusGerman** [comment]
I am pleasantly surprised, sde seems to make everything incredibly slow, 'just try it on a zsh shell | bash by itself.
And yet the speed of 'bun' on installation is very high, this project is on a great track but though I really hope for avx support soon.

`time ./sde-external-9.7.0-2022-05-09-lin/sde64 -chip-check-disable -- ls`
```
./sde-external-9.7.0-2022-05-09-lin/sde64 -chip-check-disable -- ls  0,63s user 0,25s system 98% cpu 0,890 total
```


`time ls`
```
ls $LS_OPTIONS  0,00s user 0,00s system 89% cpu 0,004 total
```


simply the cost of cpu per 'sde' is absurd I can't afford something like that since while more components are used in it the loss of performance exceeds the gain of 'bun'. (if this is not understood, it means that the more movement of 'io' there is, the slower it becomes)

so i have to wait for the update

**Comment by renhiyama** [comment]
> Thanks @renhiyama your solution worked like a charm

Your welcome!

**Comment by renhiyama** [comment]
> I am pleasantly surprised, sde seems to make everything incredibly slow, 'just try it on a zsh shell | bash by itself. And yet the speed of 'bun' on installation is very high, this project is on a great track but though I really hope for avx support soon.
> 
> `time ./sde-external-9.7.0-2022-05-09-lin/sde64 -chip-check-disable -- ls`
> 
> ```
> ./sde-external-9.7.0-2022-05-09-lin/sde64 -chip-check-disable -- ls  0,63s user 0,25s system 98% cpu 0,890 total
> ```
> 
> `time ls`
> 
> ```
> ls $LS_OPTIONS  0,00s user 0,00s system 89% cpu 0,004 total
> ```
> 
> simply the cost of cpu per 'sde' is absurd I can't afford something like that since while more components are used in it the loss of performance exceeds the gain of 'bun'. (if this is not understood, it means that the more movement of 'io' there is, the slower it becomes)
> 
> so i have to wait for the update

That confirms my statement that sde is pretty much slow!

**Comment by renhiyama** [comment]
Closing this issue btw, as @FinnRG pointed out, its better to bring issues together at one place: #67 . Let's see there!
Btw FinnRG let me know if I need to post the same above answer there or not :smile:

**Comment by max-programming** [comment]
> tar -xf sde-external-9.7.0-2022-05-09-lin.tar.xz

Thanks man!!!!

**Comment by vasileermicioi** [comment]
> I've made a script to simplify and automate SDE's installation based on @renhiyama's solution, lmk if there's anything to fix.
> 
> `$ curl https://gist.githubusercontent.com/fuka-g/afb29296db34d2451cdddcc14dbeef3c/raw/0c9e5d43910cf53b9bd82b358559bb8b75ebbfdc/bun-sde-fix-install_script.sh | bash`
> 
> EDIT: Updated script, this one is up to date.

this script doesn't work for me
but the instructions provided by [renhiyama](https://github.com/renhiyama) works

**Comment by renhiyama** [comment]
> > I've made a script to simplify and automate SDE's installation based on @renhiyama's solution, lmk if there's anything to fix.
> > `$ curl https://gist.githubusercontent.com/fuka-g/afb29296db34d2451cdddcc14dbeef3c/raw/0c9e5d43910cf53b9bd82b358559bb8b75ebbfdc/bun-sde-fix-install_script.sh | bash`
> > EDIT: Updated script, this one is up to date.
> 
> this script doesn't work for me but the instructions provided by [renhiyama](https://github.com/renhiyama) works

Glad to help you out!

**Comment by renhiyama** [comment]
![](https://windows.is-a.fail/ogp/5D1O6LNhs.png)
now thats some serious dedication to failure management; for the first time my issue ranks first on google search. A proud moment😄
