### ISSUE TITLE
bun create react app broken in canary

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#2828]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```bash
bun create react ./playground
cd playground
bun dev
```

### What is the expected behavior?

the react template should work like in 0.5.9

### What do you see instead?

In the browser console I get
```
TypeError: Zr.require is not a function. (In 'Zr.require (e)', 'Zr.require' is undefined)
```

### Additional information

I think this might be a regression in `bun dev` or rather the template of `bun create react` which has not yet been updated to reflect the new features/changes.

**Comment by simylein** [comment]
also mentioned in #2831

**Comment by notnoahpp** [comment]
confirmed on the same system with bun canary `0.6.1` loading a vanilla react jsx file

<img width="495" alt="image" src="https://github.com/oven-sh/bun/assets/129184615/f220a386-a990-4b3c-88ea-c98b05fe1d03">

```javascript
import { StrictMode } from "react";
import ReactDOM from "react-dom/client";

ReactDOM.createRoot(document.getElementById(`root`)).render(
  <StrictMode>
    <div>I am a div</div>
  </StrictMode>
);

```

**Comment by jesseagleboy** [comment]
> confirmed on the same system with bun canary `0.6.1` loading a vanilla react jsx file
> 
> <img alt="image" width="495" src="https://user-images.githubusercontent.com/129184615/238979814-f220a386-a990-4b3c-88ea-c98b05fe1d03.png">
> ```js
> import { StrictMode } from "react";
> import ReactDOM from "react-dom/client";
> 
> ReactDOM.createRoot(document.getElementById(`root`)).render(
>   <StrictMode>
>     <div>I am a div</div>
>   </StrictMode>
> );
> ```
@notnoahpp I'm using `0.6.3` and getting the same error you mentioned.

**Comment by notnoahpp** [comment]
@jesseagleboy using `bun create react --no-git ./yourappname` fixed it for me

- [check working repo](https://github.com/nirv-ai/fullstackapps/tree/develop/apps/nirvlife)
- [the react template](https://github.com/bun-community/create-templates/tree/main/react)

i think either the update to the template / bun fixed the issue if using the template. 

However I havent tried without the template

**Comment by jesseagleboy** [comment]
@notnoahpp Thank you for the response 😄. I tested that earlier this week (it would have been 0.6.2, but the problem still exists in both versions) and tested the template with Bun, which worked. Reading through the template, I didn't see any changes that would make React work with a template but improperly import without using a template.

**Comment by notnoahpp** [comment]
@jesseagleboy must be a process thing then (or just a bug), if you check `dev.tsx` it builds and serves the transpiled JS to the browser (which is required if you check the bun docs)

I would think bun dev does that automatically, but dunno

i'll take a look at it after work today

**Comment by simylein** [comment]
I am gonna close this as `bun dev` will likely receive a rewrite and is also not documented at the moment.
