### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by brailateo** [oven-sh/bun#2829]
### What version of Bun is running?

probably v0.5.9

### What platform is your computer?

Linux amd64

### What steps can reproduce the bug?

teo@teo-amd:~$ curl -fsSL https://bun.sh/install | bash
######################################################################## 100,0%
bun was installed successfully to ~/.bun/bin/bun 

Added "~/.bun/bin" to $PATH in "~/.bashrc" 

To get started, run: 

 source /home/teo/.bashrc 
  bun --help 
teo@teo-amd:~$ source /home/teo/.bashrc
teo@teo-amd:~$ bun --help
	    --use <STR>Illegal instruction (core dumped)

**Comment by Electroid** [comment]
We recently changed the install script to better detect for this. If you still experience this issue, re-open this issue and we'll investigate.
