### ISSUE TITLE
[UI website]  text overlapping on window resize

### ISSUE THREAD

**Issue by Nithin1506200** [oven-sh/bun#285]
## When the window is resized smaller the text `bash` and `copy` overlaps.  
![image](https://user-images.githubusercontent.com/57832822/177625001-7920835a-571e-4360-8261-7b4610bf98cd.png)

**Comment by patel-manas** [comment]
I will be interested to pick this up.

**Comment by patel-manas** [comment]
I am thinking to wrap the command and show an ellipsis (...)

**Comment by FinnRG** [comment]
I'm not able to reproduce this issue anymore.
