### ISSUE TITLE
Support `fetch` over UNIX socket

### ISSUE THREAD

**Issue by klirix** [oven-sh/bun#2853]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run docker with default config.

```js
await fetch("http+unix:///var/socker/docker.sock")
```

### What is the expected behavior?

HTTP response from unix socket

### What do you see instead?

Throws `FailedToOpenSocket: Was there a typo in the url or port?`

**Comment by klirix** [comment]
https://github.com/oven-sh/bun/pull/2777 should probably solve it

**Comment by ImLunaHey** [comment]
I really need this for docker API support. Is there anything that can be done to help this along? 🙏

**Comment by donflopez** [comment]
I hate being the guy, but same here! I can't use Dockerode because of this with Bun. The alternative is to run spawn but is so much trouble to gather all the information :(

**Comment by isaced** [comment]
I am still unable to use dockerode with Bun. 😭

**Comment by Jarred-Sumner** [comment]
This was implemented quite awhile ago.

From a [guide page](https://bun.sh/guides/http/fetch-unix):

```ts
const unix = "/var/run/docker.sock";

const response = await fetch("http://localhost/info", { unix });

const body = await response.json();
console.log(body); // { ... }
```
