### ISSUE TITLE
Website: Bun.serve benchmark links to wrong source code

### ISSUE THREAD

**Issue by jnsprnw** [oven-sh/bun#286]
On the website https://bun.sh/, the links to the source code below the benchmark graph point to the wrong source files. The file for node and deno are mixed up.

![Screenshot_2022-07-06_at_21_11_51](https://user-images.githubusercontent.com/5550700/177625328-5d98366a-fc46-4b27-8753-380a73dc68e3.jpg)

**Comment by StephenStrickland** [comment]
Duplicate of #240
Edit: looks like the original is #210
