### ISSUE TITLE
`BigInt64Array`/`BigUint64Array` returned from NAPI GC'd Early

### ISSUE THREAD

**Issue by cryptodeal** [oven-sh/bun#2871]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Clone the following repo: https://github.com/cryptodeal/zig-bindgen-js

Build NAPI bindings:
```sh
zig build
```

Run unit tests:
```sh
bun test
```

### What is the expected behavior?

All tests pass & returning an external `BigInt64Array`/`BigUint64Array` doesn't throw `Internal consistency error: the expect(value) was garbage collected but it should not have been!`

### What do you see instead?

The 2 tests for `BigInt64Array` and `BigUint64Array` both fail, throwing the following error: `Internal consistency error: the expect(value) was garbage collected but it should not have been!`

**Comment by Electroid** [comment]
This was likely fixed by https://github.com/oven-sh/bun/pull/6598. If you still run into this issue after upgrading with `bun upgrade --canary`, please re-open this issue and we'll investigate.
