### ISSUE TITLE
incorrect DCE of unreferenced object literal

### ISSUE THREAD

**Issue by kzc** [oven-sh/bun#2873]
### What version of Bun is running?

0.6.0 canary

### What platform is your computer?

macos 10.14

### What steps can reproduce the bug?

given:
```
$ cat obj-lit-dce.js

    ({
        0: 1,
        2: console.log("EFFECT1"),
    });
    ({
        0: 1,
        [console.log("EFFECT2")]: 2,
    });
```
expected:
```
$ node obj-lit-dce.js
EFFECT1
EFFECT2
```
actual:
```
$ bun obj-lit-dce.js
EFFECT2
```
```
$ bun run obj-lit-dce.js
EFFECT2
```

### Additional information

This `bun run` bug also exists in `bun build` and `bun build --minify`.

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/4d751db27a65c800c1c4cd6e6a241e360a9faa54
