### ISSUE TITLE
Lodash baseIsEqualDeep causes react-cosmos failure

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#2877]
### What is the problem this feature would solve?

Unable to integrate with react-cosmos due to lodash baseIsEqualDeep.js

- https://github.com/react-cosmos/rfcs/issues/27

### What is the feature you are proposing to solve the problem?
If bun.sh lodash dependency did not throw; it could be used with react cosmos as a [custom bundler](https://github.com/react-cosmos/react-cosmos/blob/main/docs/customBundlerSetup.md) and even a [bun.sh native plugin like vite has](https://github.com/react-cosmos/react-cosmos/tree/main/packages/react-cosmos-plugin-vite/src)
- IMO react-cosmos would be the preferred library as the only requirement is to setup the bundler and doesnt have reliance on
  - legacy react proptypes
  - webpack, vite, nextjs, etc

### What alternatives have you considered?

initial exploration; open to suggestions on a storybook-esq library that works with bun.sh and doesnt require **extraneous** dependencies

IMO integrating with storybook, ladle, react-styleguidist (etc) are all steps in the wrong direction

**Update 5/16**:
- document the correct issue: lodash _baseIsEqualDeep.js
> ![image](https://github.com/oven-sh/bun/assets/10324554/6c8c0f5d-7f42-4656-9748-789b02b8856b)

**Comment by Jarred-Sumner** [comment]
Please try again in the canary build of bun

```
bun upgrade --canary
```

**Comment by noahehall** [comment]
@Jarred-Sumner 

Unfortunately the bug exists in canary.

```sh
08:19 PM (react-cosmos-spike-2) 
$ bun -v
0.6.3
```
**update 5/20**
And also fixed this example repo to [reproduce the error](https://github.com/noahehall/react-ideal-image/tree/react-cosmos-spike-2)

```sh
# clone repo

git clone -b \ 
  react-cosmos-spike-2 \
  --single-branch \
  git@github.com:noahehall/react-ideal-image

# setup env
bun upgrade --canary
bun install

# start app
bun run cosmos

# open browser to localhost:5000 

```

**Comment by noahehall** [comment]
closed in favor of this: https://github.com/oven-sh/bun/issues/3206

sorry for the duplicate
