### ISSUE TITLE
bun canary:  syntax errors in various packages on `bun dev`

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#2878]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Linux 5.19.0-41-generic x86_64 x86_64

### What steps can reproduce the bug?

- [clone this repo](https://github.com/nirv-ai/fullstackapps/tree/fix/bun-latest-now-failing)
```sh
# cd into frontend app
cd apps/nirvlife

# switch to canary
bun run upgrade:bun

# install deps and start dev server
bun install
bun dev

open localhost:3000

```

### What is the expected behavior?

on 0.5.9 the page loads

![image](https://github.com/oven-sh/bun/assets/10324554/6ed19fb4-f1c9-4483-9448-e034f316ae03)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/10324554/6f1502ee-7f26-42e3-a110-5e30677f791e)

![image](https://github.com/oven-sh/bun/assets/10324554/e0cac2d9-9ab0-49e6-b45a-3991b87a10af)

Uncaught SyntaxError: ambiguous indirect export: useMemo

- if you comment `import @tanstack/react-query-devtools` from `api/QueryProvider.tsx` additional errors are thrown in `@emotion/react`

**Comment by Jarred-Sumner** [comment]
node_modules.bun is essentially deprecated 

Please try without that
