### ISSUE TITLE
`bun build --compile` outputs a truncation fail

### ISSUE THREAD

**Issue by savioxavier** [oven-sh/bun#2882]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Yesterday, when I found out that bun could now build compiled executables, I became very excited and decided to take a look. I created a quick, basic script and tried using `bun build --compile`. However, I was met with the following error:

See below screenshot:
![image](https://github.com/oven-sh/bun/assets/38729705/c85a2cfb-57d2-4afd-b874-c7e889ed1c39)

### What is the expected behavior?

Actually create an executable, without the error

### What do you see instead?

```text
error: failed to truncate temporary file: Unexpected
```

It feels like the error message stating a truncation fail, is also truncated

### Additional information

The same error occurs when modules are included in the file.

Possibly linked with the old Linux kernel version, perhaps? Or probably just another file build/minify error?

**Comment by Jarred-Sumner** [comment]
I'm not sure what's going wrong here. But I made some tweaks to the error messages that this code produces to hopefully say something more helpful in 47d2e2cb190ccfb87cb16356d9c0857e471b256d

Can you try again in about 1 hour?

**Comment by savioxavier** [comment]
Okay, I've upgraded and run the command again. The executable is created now, however there is an `ftruncate` permission error. The compiled executable does run a bit slow though, and 92 MB is quite huge.

![image](https://github.com/oven-sh/bun/assets/38729705/52a59a9d-057d-462d-b7ab-98f872972983)

**Comment by Jarred-Sumner** [comment]
2.67 seconds is also very slow to copy to disk

I have a hunch the file performance is partially due to creating a sparse file (that's what truncate() is doing here)

It turns out we don't need to do that. So I changed it in https://github.com/oven-sh/bun/commit/0a879be3288483299e5f05e0a4ded52726c0c5e4

The file size is indeed an issue and that will be a separate TODO to address.
