### ISSUE TITLE
`process.binding` prevents hugo-bin from installing Hugo binary

### ISSUE THREAD

**Issue by gabrielmaldi** [oven-sh/bun#2891]
### What version of Bun is running?

0.5.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

When installing [hugo-bin](https://github.com/fenneclab/hugo-bin) with Bun, the [Hugo](https://github.com/gohugoio/hugo) binary does not get installed due to:

```sh
TypeError: process.binding() is not supported in Bun. If that breaks something, please file an issue and include a reproducible code sample.
```

This can be verified by running:

```sh
npm install hugo-bin
file node_modules/hugo-bin/vendor/hugo # Success: Hugo binary exists

rm -rf ./node_modules
rm package-lock.json

bun install
file node_modules/hugo-bin/vendor/hugo # Error: Hugo binary does not exist
```

<img width="926" alt="Screenshot 2023-05-16 at 11 27 38" src="https://github.com/oven-sh/bun/assets/3728897/554f8469-ae79-4837-b08d-6c6e8d25476f">

If we execute hugo-bin's `postinstall` script with Bun we see the cause:

```sh
bun node_modules/hugo-bin/lib/install.js
```

<img width="1021" alt="Screenshot 2023-05-16 at 11 28 37" src="https://github.com/oven-sh/bun/assets/3728897/7d8d3e05-0ed1-48d5-88f6-35effb65135f">

Which leads us to execa: https://github.com/sindresorhus/execa/issues/31#issuecomment-215939939

Maybe Bun could add support for some of these scenarios so existing npm libraries continue to work without changes? That would make the path of migrating to Bun easier.

Thanks!

### What is the expected behavior?

Hugo's executable exists after `bun install`.

### What do you see instead?

Hugo's executable does not exist after `bun install` (it does after `npm install`).

### Additional information

Bun is ⚡️:

<img width="549" alt="Screenshot 2023-05-16 at 11 41 54" src="https://github.com/oven-sh/bun/assets/3728897/475d20de-8cba-4d77-adbd-ab03444c1bf1">

**Comment by vafanassieff** [comment]
I have the same issue when running `storybook` vite dev server inside docker with `oven/bun:canary` or `oven/bun:0.8.1`

The command is running fine on my host (Macbook M2) -> I have not using bun to run the server but node in the end, running `bunx --bun storybook dev -h 0.0.0.0 -p 6006 --no-open --disable-telemetry` throw on my host too

```
execa/lib/errname: unable to establish process.binding('uv') 1 | (function (bindingName){"use strict";if(bindingName==="constants")return @processBindingConstants;const issue={fs:3546,buffer:2020,natives:2254,uv:2891}[bindingName];if(issue)throw new Error(`process.binding("${bindingName}") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/${issue}`);@throwTypeError(`process.binding("${bindingName}") is not implemented in Bun. If that breaks something, please file an issue and include a reproducible code sample.`)})
                       ^
error: process.binding("uv") is not implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2891
      at binding (:1:20)
      at /home/user/node_modules/envinfo/dist/envinfo.js:1:0
      at n (/home/user/node_modules/envinfo/dist/envinfo.js:1:33779)
      at /home/user/node_modules/envinfo/dist/envinfo.js:1:128061
      at n (/home/user/node_modules/envinfo/dist/envinfo.js:1:33779)
      at /home/user/node_modules/envinfo/dist/envinfo.js:1:127427
      at n (/home/user/node_modules/envinfo/dist/envinfo.js:1:33779)
      at /home/user/node_modules/envinfo/dist/envinfo.js:1:126485
      at n (/home/user/node_modules/envinfo/dist/envinfo.js:1:33779)
      at /home/user/node_modules/envinfo/dist/envinfo.js:1:124600
  
      TypeError: import_node_zlib.default.createBrotliDecompress is not a function. (In 'import_node_zlib.default.createBrotliDecompress()', 'import_node_zlib.default.createBrotliDecompress' is undefined)
      at /home/user/node_modules/@storybook/core-server/dist/index.js:101:36807
      at node:http:859:28
TypeError: undefined is not an object (evaluating 'require("node:module")._extensions[".ts"]')
    at interopRequireDefault (/home/user/node_modules/@storybook/core-common/dist/index.js:31:3074)
    at serverRequire (/home/user/node_modules/@storybook/core-common/dist/index.js:36:409)
    at <anonymous> (/home/user/node_modules/@storybook/core-common/dist/index.js:49:6912)

**Comment by tujoworker** [comment]
Looks like `process.binding` is vital for many Node.js projects. Would be nice to get this in now that v1 is out 🙏

**Comment by Xyndra** [comment]
Creates problems with lit too

**Comment by rishabh-ahuja007** [comment]
Still not implemented in v1 release :-(

**Comment by fanegui** [comment]
having problems also with this `process.binding('uv')`

**Comment by Esummins** [comment]
I ran into this issue from running `create-react-app` on WSL.

**Comment by Allain55** [comment]
I'd love this as needed for gulp

**Comment by Luks3110** [comment]
having the same error with `process.binding('uv')`

**Comment by mariobm** [comment]
Same issue with `process.binding('uv')` is there any workaround?

They need to implement process.binding

**Comment by 0x051C** [comment]
1.0 bun create react-app fails with a link to this issue.

**Comment by Tanveeshs** [comment]
Nest.js fails with this issue

**Comment by tvonessen** [comment]
Same issue on WSL
```console
> bun -v
1.0.1
> uname -srm
Linux 5.15.90.1-microsoft-standard-WSL2 x86_64
```

**Comment by gcontarini** [comment]
> Same issue with `process.binding('uv')` is there any workaround?
> 
> They need to implement process.binding

Had the same problem while trying to use bun to run a Vue frontend server for local development.

**Comment by gabrielmaldi** [comment]
Thanks! Filed #5514 because even though now Bun implemented `process.binding`, my use-case of installing Hugo through hugo-bin hit another problem.
