### ISSUE TITLE
Crash with standalone executable (bun build --compile) on MacOS

### ISSUE THREAD

**Issue by kernoeb** [oven-sh/bun#2895]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Hi!

I just wanted to try the `--compile` option on Bun, really appreciate this ! 👍 

First, I noticed that without `--outfile`, it doesn't work :

```
bun build --minify --compile ./index.js
  [14ms]  minify
   [2ms]  bundle  1 modules
error: failed to rename /xxxxx/test-bun/.b8304964ec4a1c00bun-build to .: Unexpected
````

Then I tried another simple example (my `index.js` is just a `console.log("HELLO")`) : 

```
~/Documents/test-bun
❯ bun build --minify --compile ./index.js --outfile wow
  [14ms]  minify
   [2ms]  bundle  1 modules
  [83ms] compile  wow

~/Documents/test-bun
❯ ./wow
HELLO

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.6.0 (65237b30) macOS Silicon 21.6.0
Unknown:
Elapsed: 19ms | User: 10ms | Sys: 19ms
RSS: 18.40MB | Peak: 18.40MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x10248e350
1   ???

Crash report saved to:
  ~/.bun/.bun-crash/v0.6.0-1684261748822.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 38463 panic: attempt to unwrap error
fish: Job 1, './wow' terminated by signal SIGABRT (Abort)
```

The "HELLO" is logged, but then Bun show this crash 😔 

Any idea ?
Thanks :)

**Comment by Jarred-Sumner** [comment]
working on it

**Comment by evanwalsh** [comment]
FWIW, I only get the `error: failed to rename /xxxxx/test-bun/.b8304964ec4a1c00bun-build to .: Unexpected` error when the file I'm compiling is named `index.js` or `index.ts`. Any other file name works without using `--outfile`.

**Comment by Jarred-Sumner** [comment]
going to push up bun v0.6.1 when CI finishes

**Comment by kernoeb** [comment]
Thanks a lot ! @Jarred-Sumner 👌 
Just in case, 0.6.1 fix the crash issue, but not the issue related `--outfile` not in arguments (see @evanwalsh's reply)
