### ISSUE TITLE
`bun build` out-of-memory crash with `--source-map=external`

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#2908]
### What version of Bun is running?

0.6.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm (macOS 13.3.1)

### What steps can reproduce the bug?

```shell
git clone https://github.com/cubing/cubing.js && cd cubing.js
git checkout 72febf0a943cfaeb852a6205a349315cd2ec3fb5
bun install
make build-search-worker

cd src/cubing
bun build --sourcemap=external --splitting */index.ts --outdir ../../dist/esm-bun
```

The last command crashes with the following error:

```
uh-oh: TODO: handle error: OutOfMemory
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.6.0 (65237b30) macOS Silicon 22.4.0
BuildCommand: 
Elapsed: 58ms | User: 134ms | Sys: 53ms
RSS: 115.54MB | Peak: 115.44MB | Commit: 0.17GB | Faults: 17
----- bun meta -----
thread 4218403 panic: TODO: handle error: OutOfMemory

0   0x106582350
1   ???

Crash report saved to:
  ~/.bun-crash/v0.6.0-1684282258200.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 4218399 panic: TODO: handle error: OutOfMemory
thread 4218405 panic: TODO: handle error: OutOfMemory
thread 4218407 panic: TODO: handle error: OutOfMemory
thread 4218402 panic: TODO: handle error: OutOfMemory
thread 4218400 panic: TODO: handle error: OutOfMemory
thread 4218404 panic: TODO: handle error: OutOfMemory
fish: Job 1, 'bun build --sourcemap=external …' terminated by signal SIGABRT (Abort)
```

My first guess is that this might be triggered by a particularly large source file (`./src/cubing/search/search-worker-inside-generated-string.js`, generated by `make build-search-worker`), but the error remains even after I remove that large file from the build. I'm sorry I don't have a smaller repro.

The command succeeds if `--sourcemap=external` is removed.

### What is the expected behavior?

Not crashing? 😃

### What do you see instead?

Reproducible crash. 😢

**Comment by Jarred-Sumner** [comment]
Thank you for the repro, we will take a look

**Comment by lgarron** [comment]
I can confirm `v0.6.3` doesn't crash, thanks! 😻
