### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED after bun install in WSL

### ISSUE THREAD

**Issue by NikolaRHristov** [oven-sh/bun#291]
If I try it on a directory within WSL it gets stuck.

```
bun install v0.1.1
  🚚 @types/nlcst [2277/2284]
```

Only in a Windows directory I get this message.

**KMODE_EXCEPTION_NOT_HANDLED**
**NetAdapterCx.sys**

Windows Insider Build 22H2 25151.1010
This is WSL Ubuntu 22.04

**Comment by Jarred-Sumner** [comment]
Wow, blue screen of death. that's new.

Bun shouldn't be able to cause a BSOD. That sounds like a Windows kernel bug, possibly in their io_uring implementation. The stuck at the last step there is a bug in bun though.

**Comment by NikolaRHristov** [comment]
Yeah, it's a kernel bug not BSOD, my mistake. It's just the green screen kernel exception.

**Comment by NikolaRHristov** [comment]
Stuck on install fixed itself.

**Comment by Kapsonfire** [comment]
had this issue as well when upgrading from 0.1.3 to 0.1.4 - had to upgrade my network device driver

**Comment by Electroid** [comment]
This issue was likely fixed by the many stability improvements we've made to `bun install` leading up to Bun v1.0. If you still run into this problem, please feel free to re-open this issue.
