### ISSUE TITLE
Failed to build with TOML file

### ISSUE THREAD

**Issue by linux-china** [oven-sh/bun#2910]
### What version of Bun is running?

0.6.1

### What platform is your computer?

Darwin 22.4.0 x86_64 i386

### What steps can reproduce the bug?

I have a config.toml, and code as below: 

```toml
title = "TOML Example"
```

Then I create a demo.ts to import config.toml, and code as below: 

```typescript
import config from "./config.toml";

console.log(config);
```

All is good with `bun run demo.ts`, and print the toml's object correctly. 

When I want to use build command and bundle demo.ts, and coomand is `bun build demo.ts --outfile demo-bundle.js` and the bundle code as following: 

```javascript
// config.toml
var config_default = {};

// demo.ts
console.log(config_default);
```

As you can see,  build command can not load TOML correctly, and all toml information lost.

**Comment by dylan-conway** [comment]
this is fixed in 21bc3a9c391ddebf2afad3e420e782a306f62a11
