### ISSUE TITLE
bun create hangs fetching manifest

### ISSUE THREAD

**Issue by cybertouchllc** [oven-sh/bun#2912]
### What platform is your computer?

MacOS Ventura 13.3.1

### How did you attempt to install or upgrade?

```
> bun -v
0.5.9

> bun upgrade
> bun create
```

### What do you see instead?

```
> bun create
Fetching manifest...
ConnectionRefused while trying to fetch examples list. Please try again
```

### Additional information

I was on 0.5.9

**Comment by birkskyum** [comment]
This works with bun 0.8.1 - @cybertouchllc , if you see this again, please reopen the ticket.

```sh
➜ bun create
Welcome to bun! Create a new project by pasting any of the following:

  bun create apollo-server ./apollo-server-app

  bun create bun-bakery ./bun-bakery-app
```
