### ISSUE TITLE
`process.argv[0]` is always "bun" in the executable produced by `bun build --compile`

### ISSUE THREAD

**Issue by rickymohk** [oven-sh/bun#2916]
### What version of Bun is running?

0.6.1

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Given `index.js`
```js
console.log(process.argv);
```
Run 
```bash
bun build ./index.js --compile --outfile mycli
./mycli
```
prints
```
[ "bun", "compiled://root/mycli" ]
```

### What is the expected behavior?

`process.argv[0]` should be "path/to/mycli"

### What do you see instead?

`process.argv[0]` is always "bun"

### Additional information

I known `Bun.argv` exists and it represents the command line arguments exactly. But it is not as useful because of some inconsistency in some situation. Specifically when running with the `bun` command, one can run `bun index.js <param>` or `bun run index.js <param>`. As a result `<param>` may come in either `Bun.argv[2]` or `Bung.argv[3]`, while being in `Bung.argv[1]` when running `./mycli <param>` after compile. In contrast, using `process.argv` always have `<param>` starting from `process.argv[2]`. This makes me prefer `process.argv` over `Bun.argv`.

**Comment by Jarred-Sumner** [comment]
The behavior with `process.argv` is intentional because existing scripts do `process.argv.slice(2)`, so continuing to make that work is least likely to break code

TBH, I didn't think about it as much for `Bun.argv`. Maybe we should do the same there.

**Comment by rickymohk** [comment]
> The behavior with `process.argv` is intentional because existing scripts do `process.argv.slice(2)`, so continuing to make that work is least likely to break code
> 
> TBH, I didn't think about it as much for `Bun.argv`. Maybe we should do the same there.

I don't get it. What does `process.argv.slice(2)` have to do with `process.argv[0]` being `bun`? Shouldn't `process.argv[0]` always be the executing file? I know `pkg` does that.

**Comment by ckhatton-transreport** [comment]
Yeah I totally agree - `Bun.argv` should mirror the behaviour of `process.argv` (if `Bun.argv` is to be kept). I am going to switch to using `process.argv` now that I know of the risk of a wrong argument appearing in `Bun.argv`.

I actually stumbled across a TypeScript error when using `Bun.argv`, which I will report in a bit.

`Bun.argv.slice(3)`

> Property 'argv' does not exist on type 'typeof import("bun")'.
