### ISSUE TITLE
fetch module errors at random times

### ISSUE THREAD

**Issue by Calemy** [oven-sh/bun#292]
sometimes fetch works and sometimes it just doesn't. i didn't change anything in the code but ran it over and over again

```js
(async () => {
    console.time("Execution")
    const request = await fetch('https://catboy.best/api')
    const response = await request.json()
    console.log(response)
    console.timeEnd("Execution")
})();
```

**Comment by Jarred-Sumner** [comment]
@kprotty is there a chance you'd be willing to review some of the code and offer suggestions in [io_linux.zig](https://github.com/Jarred-Sumner/bun/blob/main/src/io/io_linux.zig) and [io_darwin.zig](https://github.com/Jarred-Sumner/bun/blob/main/src/io/io_darwin.zig) and [thread_pool.zig](https://github.com/Jarred-Sumner/bun/blob/main/src/thread_pool.zig)? Something in there is causing this and other dead locks, I believe

I think it's this:

https://github.com/Jarred-Sumner/bun/blob/f0c283c632816143d8eb3a9dc9ed41d326dcbde1/src/thread_pool.zig#L274-L297

**Comment by kprotty** [comment]
- Seems like the IO stuff is ported from Tigerbeetle. It's single threaded but tick() is being called by multiple threads here.
- I'm not sure what the http stuff is doing w.r.t thread waiting.

**Comment by Jarred-Sumner** [comment]
> Seems like the IO stuff is ported from Tigerbeetle. It's single threaded but tick() is being called by multiple threads here.

This thread_pool isn't actually being used as a thread pool for IO, but just for scheduling. It only runs one thread. Doing it this way feels pretty hacky, but multiple threads could potentially schedule work to the HTTP thread (MPSC basically) 

> I'm not sure what the http stuff is doing w.r.t thread waiting.

The spin loop here is because it goes to sleep when there are no tasks, but the IO activity needs to be able to wake up the thread. What's the best way to do that?

**Comment by kprotty** [comment]
You should consider a single HTTP thread, foregoing all the thread pool complexities. You can use a mutex protected queue for getting tasks onto the HTTP thread.

For waking up the HTTP thread, use an eventfd/pipe/socket which waits for read() in the IO thread and others do write() to wake. You then guard this through an atomic `is_waiting` boolean of sorts to avoid needless syscalls.  This is the scheme behind the [TigerBeetle C/Go client](https://github.com/kprotty/tigerbeetle/blob/tb_client/src/c/tb_client/signal.zig).

**Comment by FinnRG** [comment]
@Calemy I can't reproduce this issue in the latest version (``v0.1.4``) anymore. Could you please try this again and close this issue if it's resolved?

**Comment by Calemy** [comment]
I apologise for the very late response, but with the lastest version (v0.1.7) it seems to have been resolved.
Thank you! :)
