### ISSUE TITLE
Support for Monorepos with Turborepo

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [oven-sh/bun#2921]
### What is the problem this feature would solve?

With the new feature bun would be a drop in replacement of turborepo, as it aims to be also in other places, or bun would work seamlessly with turborepo. 

### What is the feature you are proposing to solve the problem?

Make bun a replacement for turborepo, or make bun work with turborepo

**Comment by notnoahpp** [comment]
interesting if bun plans to add similar caching mechanism for running scripts as well as script dependencies

**Comment by Electroid** [comment]
Turborepo works with Bun now.

* Run `bun i -g turbo@latest`
* Run `bunx create-turbo@latest`
