### ISSUE TITLE
Missing `Bun.build` types

### ISSUE THREAD

**Issue by iam-medvedev** [oven-sh/bun#2923]
### What version of Bun is running?

0.6.1

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

There seems to be a problem with the `Bun.build' typing.

`build.ts`:
```ts
await Bun.build();
       // ^ Property 'build' does not exist on type 'typeof import("bun")'.ts(2339)
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "types": ["bun-types"]
  }
}
```

`package.json`:
```json
"dependencies": {
  "bun-types": "latest"
}
```

[StackBlitz example](https://stackblitz.com/edit/typescript-3mgejt?file=build.ts)

### What is the expected behavior?

Types must be defined.

**Comment by colinhacks** [comment]
Thanks, CI issue. We've manually released `bun-types@0.6.1`: https://www.npmjs.com/package/bun-types?activeTab=versions
