### ISSUE TITLE
Segfault / SyntaxError on RegExp when using a template string in a second, unused variable

### ISSUE THREAD

**Issue by pepper-lees** [oven-sh/bun#2929]
### What version of Bun is running?

0.6.1

### What platform is your computer?

Linux 6.2.0-20-generic x86_64 x86_64

### What steps can reproduce the bug?

When testing this, I've ran multiple permutations of the same concept and got very different results. I first saw the issue when loading ipaddr.js:

```js
21 |     // For IPv6, the task is simpler: it is enough to match the colon-delimited
22 |     // hexadecimal IPv6 and a transitional variant with dotted-decimal IPv4 at
23 |     // the end.
24 |     const ipv6Part = '(?:[0-9a-f]+::?)+';
25 |     const ipv6Regexes = {
26 |         zoneIndex: new RegExp(zoneIndex, 'i'),
                       ^
SyntaxError: Invalid regular expression: unmatched parentheses
      at /home/drak/Nextcloud/Projects/Programming/Miscellaneous/MediaMonkeyServer/node_modules/ipaddr.js/lib/ipaddr.js:26:19
      at /home/drak/Nextcloud/Projects/Programming/Miscellaneous/MediaMonkeyServer/node_modules/ipaddr.js/lib/ipaddr.js:993:22
      at /home/drak/Nextcloud/Projects/Programming/Miscellaneous/MediaMonkeyServer/lib/auth.js:15:6
      at /home/drak/Nextcloud/Projects/Programming/Miscellaneous/MediaMonkeyServer/lib/upnpServer.js:16:6
      at /home/drak/Nextcloud/Projects/Programming/Miscellaneous/MediaMonkeyServer/api.js:14:6
```

I created an almost-minimal reproducible example:

```js
const foo = '.*';
const regex1 = new RegExp(foo); // Invalid regular expression: unmatched parentheses
const regex2 = new RegExp(`(${foo})`);
```
The third line (`new RegExp(`(${foo})`)`) is necessary. If I omit the third line, there is no error. I guessed it had something to do with the creation of template strings.

If you replace `${foo}` with `${String(foo)}`, and thus create a copy of foo before putting it into a RegEx, then the error does not occur:
```js
const foo = '.*';
const regex1 = new RegExp(foo); // no errors
const regex2 = new RegExp(`(${String(foo)})`);
```
Same goes for `new RegExp(`(${foo + ''})`);` in this case.

But then, check this out:
```js
const str1 = '.*';
const str2 = `(${str1})`;
new RegExp(str1 + '');
```
This code results in a segmentation fault. If you omit the second line (`const str2 = ...`), then there is no segmentation fault.

Here's an even more minimal reproducible example. (I found this after typing out the one with `regex1` and `regex2`, but I figured it'd be helpful to keep both.)
This code results in `SyntaxError: Invalid regular expression: unmatched parentheses`:
```js
const str1 = '.*';
const str2 = `(${str1})`;
new RegExp(str1);
```
Note that I'm creating a RegExp of str1, not str2, but it depends on str2 being defined. Here are two different permutations of the code you can make to stop the SyntaxError.

First: Change the template string to old string concatenation:
```js
const str1 = '.*';
const str2 = '(' + str1 + ')';
new RegExp(str1);
```

Second, and this is a weird one: Remove the second parenthesis from str2 such that if you _were_ to create a RegExp from str2, there would be mismatched parentheses:
```js
const str1 = '.*';
const str2 = `(${str1}`;
new RegExp(str1);
```
But if you remove the first parenthesis instead of the second, the SyntaxError still occurs.

### What is the expected behavior?

Using `node` instead of `bun` for any of these code snippets will not result in any errors.

### Additional information

MAY be related to #2926, but it's worth noting that #2926 caused the template string itself to be formatted incorrectly, so it may be a different underlying issue.

**Comment by Jarred-Sumner** [comment]
Can you try in the canary build of bun?

```
bun upgrade --canary
```

**Comment by pepper-lees** [comment]
Works, thanks! Now I wish I didn't spend so much time writing this issue out XD
