### ISSUE TITLE
After unsuccessful installation due to permission, the script shows that bun was successfully installed.

### ISSUE THREAD

**Issue by FaisalAfroz** [oven-sh/bun#293]
After running curl https://bun.sh/install | bash command in terminal on macosx , it shows 
```
Bun was installed successfully to /Users/Username/.bun/bin/bun .
bash: line 141: /Users/Username/.zshrc: Permission denied
bash: line 142: /Users/Username/.zshrc: Permission denied
 Added "/Users/Username/.bun/bin" to $PATH in "~/.zshrc"

To get started, run

   exec /bin/zsh
   bun --help
```
After running `bun --help`
We get `zsh: command not found: bun`.

**Comment by theabhayprajapati** [comment]
even i am getting this

**Comment by ernischay** [comment]
@FaisalAfroz @theabhayprajapati 
Just reload the terminal or use this command below before starting using bun.
`source ~/.zshrc`

**Comment by boehs** [comment]
If you read the error ```
bash: line 141: /Users/Username/.zshrc: Permission denied
bash: line 142: /Users/Username/.zshrc: Permission denied
``` it failed modifying your zshrc. Just manually add `/Users/Username/.bun/bin` to your path and you are good to go

Being said there should be a better error here

**Comment by kevinforrestconnors** [comment]
This PR should fix https://github.com/oven-sh/bun/pull/695/files

in the mean time, modify your shell config, e.g. add

```
export BUN_INSTALL="/home/kevinforrestconnors/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
```

source it, and you should be fine.  The install did not fail, the error message is because bun tried to add to your `zshrc` and it was not writable.  It's just missing this `BUN_INSTALL` and `PATH`.

**Comment by Electroid** [comment]
This has been fixed, since the [install script](https://github.com/oven-sh/bun/blob/bba4054da3a5cbc2f234b9cf4b3ebdb7bb19e69d/src/cli/install.sh#L185) now checks if the shell configs are writable.
