### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by AlbertShown** [oven-sh/bun#2933]
I want to know when Bun will be available for Microsoft Windows. Is there any plan?

**Comment by AlbertShown** [comment]
https://github.com/oven-sh/bun/issues/159

> **Windows support**
> 
> - The HTTP client needs a Windows implementation for the syscalls
> - Bun needs test coverage for Windows filepath handling
> - All of bun's dependencies need to compile on Windows
> - Building JavaScriptCore needs to work on Windows and the JIT tiers need to work. I don't know what the current status of this is. WebKit's [bug tracker](https://bugs.webkit.org/show_bug.cgi?id=145366) suggests it may not have JITs enabled which will likely need some patches to fix it.

Any updates? I'm sure many people are waiting for this.

**Comment by paperclover** [comment]
Duplicate of #43. Bun will be able to run on Windows before 1.0, but not certain exactly when.

**Comment by AlbertShown** [comment]
It seems there is progress. Good to hear that 👍
Thank you.
