### ISSUE TITLE
HTTPS fetch seems broken when using both proxy and body options.

### ISSUE THREAD

**Issue by likecyber** [oven-sh/bun#2940]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

`fetch('https://google.com', {
    method: 'POST',
    headers: {
        accept: '*/*'
    },
    body: 'payload=1',
    proxy: 'http://172.21.0.1:8888',
    verbose: true
}).then((response) => console.log(response)).catch((error) => console.log(error))`

### What do you see instead?

Request: POST /
        accept: */*
        Connection: keep-alive
        User-Agent: Bun/0.6.2
        Host: google.com
        Accept-Encoding: gzip, deflate
        Content-Length: 9

Response: < 200 Connection established

SSL: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://google.com"

### Additional information

It looks like the function will always fail if you using both 'proxy' and 'body' options in fetch().
I think it mixes up the body part in proxy connection part?

**Comment by shiny** [comment]
Facing the same problem

**Comment by birkskyum** [comment]
potentially related
- https://github.com/oven-sh/bun/issues/4368

**Comment by birkskyum** [comment]
closed by https://github.com/oven-sh/bun/pull/4510
