### ISSUE TITLE
Inline `const enum` in `bun build`

### ISSUE THREAD

**Issue by jack-weilage** [oven-sh/bun#2945]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Linux 5.19.0-41-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a file called `bug.ts`.
2. Fill with
```ts
const enum ConstantEnum {
    First,
    Second,
}
console.log(ConstantEnum.First, ConstantEnum.Second)
```
3. Run `bun build ./bug.ts`

### What is the expected behavior?

The const enum should be have instances of its values replaced, instead of just referenced (like in [this TypeScript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgYXNAhmKBRJVAbwCgZyYAxASwCdoAaMigZTlDABMmBfEjiCAA2cAHRCQAcwAUGSFBz5ComvSgN0mBbgIpRbDpwCUQA)).

### What do you see instead?

The const enum acts the exact same as a normal enum, simply adding an IIFE to create an object.

**Comment by Jarred-Sumner** [comment]
Yeah, scoped const enum inlining out so that we could ship the bundler

**Comment by paperclover** [comment]
btw we have some tests for this already, including making sure this behavior works cross-file (they fail rn)
inside of `bundler/esbuild/ts.test.ts`, `ts/EnumSameModuleInliningAccess` and the ones around this

**Comment by Iamshankhadeep** [comment]
is this issue a `good first issue` and to get familiar with the repo ?

**Comment by dsogari** [comment]
Any status on this yet? I like bun because it's really fast, but I miss this feature.

The workaround is to run `tsc` as a first pass, then `bun build` on the generated output.

**Comment by Jarred-Sumner** [comment]
This will be part of the Bun v1.1.18 release, thanks to @paperdave.
