### ISSUE TITLE
_assign is not a function

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#2951]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64 arm

### What steps can reproduce the bug?

on a large React project - using the following command (with --splitting):

 bun build  --outdir out ./src/index.js --target browser --format esm --splitting  --jsx-runtime classic

Getting _assign is not a function
![image](https://github.com/oven-sh/bun/assets/68567770/2b86f46f-b085-4e72-9b5b-8ce30c3d1de2)

**Comment by Jarred-Sumner** [comment]
could you explain what the rationale is for using `--jsx-runtime=classic`?

**Comment by samopus1io** [comment]
Good question - I'm not sure to be honest - It wouldn't build without it before and it looks like its building now with 0.6.2 without `--jsx-runtime=classic` - Getting same error without `--jsx-runtime=classic`

**Comment by samopus1io** [comment]
Tried with 0.6.7 and it seems the issue is still there.
`bun build  --outdir out ./src/index.js --target browser --format esm --splitting`
