### ISSUE TITLE
js out put in the wrong directory

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#2957]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

The following code when bundled ends up outputting a js file in the same directory as the code instead of the output directory:

```js
if (notification.sound) {
        (async () => {
            const dingSound = (await import('../../../sound/notif.mp3'))
                .default;
            const ding = new Audio(dingSound);
            ding.volume = 0.2;
            ding.play();
        })();
    }
```

the following notif.js file is generated in the same directory instead of the outdir:

```js
import"../chunk-434c2b80af717b7d.js";

// sound/notif.mp3
var notif_default = "../notif-e2894d8fc7fbdbdf.mp3";
export {
  notif_default as default
};
```

The referenced notif-e2894d8fc7fbdbdf.mp3 is in the outdir

**Comment by Electroid** [comment]
Are you still experiencing this issue? If so, could you also provide a small reproduction?

**Comment by nektro** [comment]
Hi! if this is still affecting you in the latest version of Bun (you may need to run `bun upgrade`) please leave a comment and let us know. for now we're going to mark this as closed.
