### ISSUE TITLE
Weird const variable change

### ISSUE THREAD

**Issue by samuelgja** [oven-sh/bun#2960]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Just run this code

```ts
const CONST_VALUE = "CONST_VALUE"; 

function blaBla(a) {
  const { propertyName } = a;
  const condition = `${propertyName}.${CONST_VALUE}AA.WHAT`; // this somehow change the `CONST_VALUE`
  return condition;
}

console.log(CONST_VALUE);
console.log(CONST_VALUE === "CONST_VALUE"); // return false :D
```

Will return result for constant value: `CONST_VALUEAA.WHAT`. Weird. 

On previous version before 0.6 it works as expected.

Also hint: 
if I change ` const { propertyName } = a;` to `propertyName = something` it works
or if I remove `propertyName` variable from condition - it works.

### What is the expected behavior?

Const value cannot be changed :p

**Comment by Jarred-Sumner** [comment]
@dylan-conway i think this is the resolveRopeString bug you have a fix for
