### ISSUE TITLE
`FileSystemRouter` causes segfault when given an `assetPrefix`

### ISSUE THREAD

**Issue by 0aoq** [oven-sh/bun#2967]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Linux 6.3.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Create instance of `Bun.FileSystemRouter` 
2. Add an `assetPrefix` to options
3. Use `FileSystemRouter.match`

The code I used to produce this bug is below:
```ts
const Router = new Bun.FileSystemRouter({
    style: "nextjs",
    dir: process.env.ROUTER_DIR as string,
    origin: process.env.ROUTER_ORIGIN as string,
    assetPrefix: "_assetprefix/static/",
});

Bun.serve({
    port: process.env.PORT as string,
    async fetch(request: Request) {
        return new Response(JSON.stringify(Router.match(request)));
    },
});
```
Running the same code but without adding `assetPrefix` to the router options works as expected.

### What is the expected behavior?

Router should process request quickly without causing a segfault.

### What do you see instead?

Router causes a segfault on second request. Easily reproducible if you quickly send multiple requests.

**Comment by Jarred-Sumner** [comment]
thanks for the bug report

**Comment by paperclover** [comment]
Can you try this again on the latest version of bun? I cant reproduce it on arch linux and an arm mac. What were the contents of the router dir and what did you set origin as?

**Comment by 0aoq** [comment]
@paperdave Certainly! Tried again in v0.6.7.
The code provided below doesn't use `.env` for values, so it should be easier.
```ts
const Router = new Bun.FileSystemRouter({
    style: "nextjs",
    dir: "./page",
    origin: "http://localhost:3572",
    assetPrefix: "_assetprefix/static/",
});

Bun.serve({
    port: 3572,
    async fetch(request: Request) {
        return new Response(JSON.stringify(Router.match(request)));
    },
});
```

The router dir looks like this:
```
pages
└── index.tsx
```

`pages/index.tsx` looks like this:
```tsx
export default function Index() {
    return {};
}
```

Running the server and refreshing quickly a couple times causes the page to become unresponsive and exit with a segmentation fault.

Ran again on an Ubuntu VM (Ubuntu 22.04.2 LTS x86_64), got the same result with the same files and steps. (Using Bun v0.6.7)

In both instances, a segmentation fault is not given unless you send multiple subsequent requests within a short period. I've found not using an `assetPrefix` removes the problem entirely and the server runs as expected.

**Comment by paperclover** [comment]
Thank you for that code. Here's a simpler reproduction (doesnt need bun.serve, crashes instantly). We'll be looking into this.
```ts
import { tmpdir } from "os";
import { mkdtempSync } from "fs";
import { sep } from "path";
import { writeFileSync } from "fs";

const tempdir = mkdtempSync(tmpdir() + sep);
writeFileSync(
  tempdir + sep + "index.tsx",
  "export default () => <div>hello</div>"
);

const Router = new Bun.FileSystemRouter({
  style: "nextjs",
  dir: tempdir,
  origin: "http://localhost:3572",
  assetPrefix: "_assetprefix/static/",
});

for (let i = 0; i < 1000; i++) {
  Router.match(new Request("http://localhost:3572/"));
  Bun.gc(true);
}
```

**Comment by paperclover** [comment]
seems this got fixed sometime. can repro anymore on mac and linux.
let me know if you can still reproduce this.
