### ISSUE TITLE
Cant use `bun install` to install `express`

### ISSUE THREAD

**Issue by eugenioclrc** [oven-sh/bun#297]
Just
```
mkdir app-bun
cd app-bun
npm init
npm i express
bun install
```
![Captura de pantalla de 2022-07-06 17-16-39](https://user-images.githubusercontent.com/332426/177635644-5c928dfd-557e-4fcc-91a4-485285aae286.png)
![Captura de pantalla de 2022-07-06 17-16-24](https://user-images.githubusercontent.com/332426/177635660-57d208b7-1874-49ba-931a-4321a04f3762.png)

What i am missing?

**Comment by moinulse** [comment]
Can you try `bun add`?

`bun add express`

**Also On the doc, it mentions about newer kernel for Linux users.** 
`bun install` needs Linux Kernel 5.6 or higher to work well

**Comment by eugenioclrc** [comment]
Dale issue with bun add

**Comment by erennakdag** [comment]
`bun add` worked for me. It seems like `bun install` looks for a `package.json` to install all the dependencies. Probably useful for an existing project transitioning to bun.js
On another note, I cannot get even the most basic express app to work somehow. It is giving me `TypeError: Error.captureStackTrace is not a function.`

**Comment by NullDev** [comment]
@erennakdag Yep, running into the same issue. Currently Bun seems to have very basic node compatibility. A lot of core modules are missing as well. That being said, `Error.captureStackTrace` is a NodeJS internal method and not native to JavaScript (<https://nodejs.org/api/errors.html#errorcapturestacktracetargetobject-constructoropt>). So I guess only time will tell whether such Node built-ins will be added to Bun

**Comment by moinulse** [comment]
@NullDev Actually this one will be included. #258

**Comment by 0xedb** [comment]
The way I bypassed this issue was to  `add body-parser` separatedly. Then `add express` after

**Comment by eugenioclrc** [comment]
yeha! that work!

Solution (crappy but works);
```sh
bun add body-parser
bun add express
```

**Comment by FrancescoSaverioZuppichini** [comment]
Following the above discussion with the following code

```javascript
const express = require('express')
const app = express()

app.get('/', function (req, res) {
  res.send('Hello World')
})

console.log("Listen port 3000")
app.listen(3000)
```

Result in the following error:

```
root@923fdf084dbf:/code# bun app.js 


error: Cannot find module "./util.inspect" from "/code/node_modules/object-inspect/index.js"
```

**Comment by georgekrax** [comment]
Same here +1. @eugenioclrc This issue must be re-opened!

**Comment by siddisking** [comment]
@FrancescoSaverioZuppichini whats your system like ?

I created a simple app with bun init and copy pasted your code and ran

```
bun add express
bun run index.js

```
it works fine for me


System: MacOS Monterey 12.3
bun 2.2

**Comment by FrancescoSaverioZuppichini** [comment]
@siddisking here we go :)

![image](https://user-images.githubusercontent.com/15908060/208466810-c1fbf262-94fe-4d75-82bd-952252b88f63.png)

**Comment by suvanshenoy** [comment]
You could use :
1) npm init     "this will install package.json
2) bun add express
3) write your express code
4) bun . or bun run .

- there is some problem with bun
package.json  which doesnot allow only express to be imported to the script.
- But the package.json generated from "npm init " works.

So please try.....
