### ISSUE TITLE
bun link: unable to link local package

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#2970]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 5.19.0-41-generic x86_64 x86_64

### What steps can reproduce the bug?

in directory 1: run `bun link`
in directory 2: copy paste and run the output

### What is the expected behavior?

the package in directory 1 is installed directory 2

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/10324554/1fa9de5f-ab3e-4080-b9a2-095460a9ac53)

**Comment by noahehall** [comment]
potentially related to https://github.com/oven-sh/bun/issues/2990

**Comment by Electroid** [comment]
Likely fixed by https://github.com/oven-sh/bun/pull/6631, if you still experience this issue, please re-open and we'll investigate.
