### ISSUE TITLE
bun-framework-next: undefined is not an object (evaluating 'packageJson.version')

### ISSUE THREAD

**Issue by cravend** [oven-sh/bun#2971]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

- run `bun create next ./test && cd test`
- run `bun dev`
- See console error

### What is the expected behavior?

The server starts correctly

### What do you see instead?

A blank page + this error in the console:

```sh
[1.00ms] bun!! v0.6.2 (8d90d795)


  Link: http://localhost:3000


23 | import * as ReactDOMServer from "react-dom/server.browser";
24 | import * as React from "react";
25 | import * as ReactIs from "react-is";
26 | import packageJson from "next/package.json";
27 |
28 | const nextVersion = packageJson.version;
                        ^
TypeError: undefined is not an object (evaluating 'packageJson.version')
      at /Users/cravend/src/web/bunnext/node_modules/bun-framework-next/renderDocument.tsx:28:20
      at /Users/cravend/src/web/bunnext/node_modules/bun-framework-next/server.development.tsx:1:0
JavaScript VM failed to start.
while loading "/Users/cravend/src/web/bunnext/node_modules/bun-framework-next/server.development.tsx"
```

### Additional information

If I manually edit `node_modules/bun-framework-next/renderDocument.tsx` & `node_modules/bun-framework-next/server.development.tsx` to manually define a version, it throws a different error, but renders the page successfully:

```sh
[1.00ms] bun!! v0.6.2 (8d90d795)


  Link: http://localhost:3001


Possibly incompatible Next.js version:  13 . Please upgrade to Next.js 12.2.0+.

[70.16ms] Next.js ready! (powered by bun)
23 |     DocumentLoaded = true;
24 |   },
25 |   (err) => {
26 |     // ResolveError is defined outside of bun-framework-next in ../../src/runtime/errors
27 |     // @ts-expect-error
28 |     if (err instanceof ResolveError) {
                           ^
ReferenceError: Can't find variable: ResolveError
      at /Users/cravend/src/web/bunnext/node_modules/bun-framework-next/server.development.tsx:28:23
```

**Comment by affulk000** [comment]
Issues Occurs when creating next.js 
these are the prompt i see:

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'stream/promises'
Require stack:
- /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.8776 (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:30476)
    at __nccwpck_require__ (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:59273)
    at /tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:60137
    at Object.<anonymous> (/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js:74:60181)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/create-next-app@latest--bunx/node_modules/create-next-app/dist/index.js'
  ]
}
