### ISSUE TITLE
implement process.env.npm_lifecycle_event

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#2972]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

run the following code with `bun start:dev`

// package.json
```
{
  "scripts": {
    "start:dev": "bun main.ts"
  }
}
```

// main.ts
```ts
console.log(process.env.npm_lifecycle_event);
```

### What is the expected behavior?

it should log `start:dev`

### What do you see instead?

it logs `undefined`

### Additional information

This is probably not used very often but we should provide a similar (or the same) way to access the currently running lifecycle script

**Comment by TiranexDev** [comment]
I just check and there is no other way to do it. So I really think this is a important commit.

The only workaround for now is using process arguments (process.argv.includes('--dev-start'));
