### ISSUE TITLE
Hot reload - needs debounce on file watch

### ISSUE THREAD

**Issue by e3dio** [oven-sh/bun#2987]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Linux 5.19.0-1025-aws aarch64 aarch64 (Ubuntu 22.04)

### What steps can reproduce the bug?

While in Hot Reload mode, updating a module file via SSH gives error on reload. Looks like it successfully loads the updated file and continues running correctly, just displays an error: `SyntaxError: Import named 'a' not found in module '/home/ubuntu/bun/a.mjs'.`

```js
// app.mjs
import { a } from './a.mjs';

export default {
  fetch(req) {
    return new Response(a);
  }
}

```

```js
// a.mjs
export const a = 1;
```

```
bun --hot app.mjs
```

Now save new version of `a.mjs`

```
SyntaxError: Import named 'a' not found in module '/home/ubuntu/bun/a.mjs'.
```

### What is the expected behavior?

No error

### What do you see instead?

SyntaxError: Import named 'a' not found in module '/home/ubuntu/bun/a.mjs

**Comment by Jarred-Sumner** [comment]
Sometimes Bun hot reloads faster than your text editor can save the files.

I suspect that's the cause (the text editor truncated the file to 0, bun reloaded it, then it saved the rest, Bun reloaded again)

**Comment by e3dio** [comment]
Ok can confirm issue only happens with file upload via SSH. Should probably add a short couple of millisecond debounce on file watching so it only reloads once. If multiple files get updated you need to give it time to update all files, like a git pull etc. Could make it configurable, `--hot=100` for 100ms debounce. Or just have some reasonable default. It's more important to wait for files to correctly update than have premature reload to save a couple millisecond. This also applies to `--watch`

**Comment by e3dio** [comment]
Should probably add a short couple of millisecond debounce on file watching, so it only reloads once

**Comment by e3dio** [comment]
Could even make it configurable, `--hot=100` for 100ms debounce

**Comment by e3dio** [comment]
Also Iooks like the SSH file upload is appending to the file in chunks so over a certain size file 4KB it hot reloads a partial file. Just need some amount of debounce time either by default or configurable.

Hot Reload is a really nice feature for keeping WebSockets/HTTP connections open and updating the app so would be nice to make it work well

**Comment by e3dio** [comment]
`Bun.watch()` could also have some configurable or default debounce. With Node.js `fs.watch()` I manually add a debounce function to handle the multiple events. `Bun.watch(fileOrDirectory, { debounce: 100 })`

**Comment by BeyondMagic** [comment]
This error still exists and I don't think there's anything I can do to from the command line to make it work properly. I save my files and sometimes, half the time, I save it and it gives me the error `Cannot find module` when it clearly exists there, it just needed a few milliseconds for the text editor to save it and import it (I'm using Vim, by the way!) Bun is too fast in watching files.

**Comment by brw** [comment]
> This error still exists and I don't think there's anything I can do to from the command line to make it work properly. I save my files and sometimes, half the time, I save it and it gives me the error `Cannot find module` when it clearly exists there, it just needed a few milliseconds for the text editor to save it and import it (I'm using Vim, by the way!) Bun is too fast in watching files.

I'm also running into this issue with `--watch` when saving a file in Vim/Neovim. Bun will sometimes exit with `error: Script not found`. The problem does not occur if I turn off swap files using `:set noswapfile` (though I would like to keep using swap files).

I assume this is the same problem so I didn't create a new issue for it.

**Comment by BeyondMagic** [comment]
Thank you @brw, the problem was completely mitigated from my environment using `:set noswapfile`. Guess now I just can hope to not crash the editor and end up and lose the files!

**Comment by jjt** [comment]
Same issue as @brw with `run --watch`, but only if the formatter [conform.nvim](https://github.com/stevearc/conform.nvim) is loaded and set to format on save.

I don't love going without swap files, but I save frequently enough and nvim crashes infrequently enough that it shouldn't be an issue in Bun-based projects.

**Comment by Jarred-Sumner** [comment]
This was done in >= Bun v1.1.20

When multiple reloads are sent before the next one finishes, they're deduped. This fixes cases where bun would not be watching files that need to be watched in order to reload at the right time

**Comment by trya2l** [comment]
Hi, I'm using bun v1.1.29 (I also tried with v1.1.20), and with neovim the issue persist. I've confirm that this is not happening with vscodium for example.

![Image](https://github.com/user-attachments/assets/0d6d996d-0c19-4a4d-86c0-499ea3404c0a)

**Comment by chrisdavies** [comment]
I'm seeing this still on Linux (Arch) and bun 1.1.38. I have prettierd which autoformats my files on save.

**Comment by ShikChen** [comment]
Hit the same issue with neovim for both `--hot` and `--watch`.
