### ISSUE TITLE
bun link of a package inside a workspace resolves into a link to the WORKSPACE itself instead of the package

### ISSUE THREAD

**Issue by cpakken** [oven-sh/bun#2990]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

## Repo reproduction the issue
https://github.com/cpakken/bun-link-workspace-issue

Running bun link in a package within a workspace (monorepo-a/packages/app-a)

```bash
# in monorepo-a/packages/app-a
bun link
```
```ts
// in app-b package.json
{
  ...
  "dependencies": {
    "@monorepo-a/app-a": "link:@monorepo-a/app-a"
  }
}

// bun install
// (also bun link @monorepo-a/app-a works too)
This does not link correctly. app-b/node_modules/@monorepo-a/app-a is linked to the workspace (monorepo-a) instead of the package.
```
cannot import @monorepo-a/app-a from app-b
![image](https://github.com/oven-sh/bun/assets/61718569/946ff13f-b003-4bf4-99b5-b3e4821562c9)

Please notice that the link in the node_modules in app-b `node_modules/@monorepo-a/app-a` doesn't link to the package but instead to its workspace

`import {add} from '@monorepo-a/app-a` does not work

### What is the expected behavior?

When `bun link` of a package inside a workspace
`bun link @monorepo/app-inside-workspace` should resolve to the workspace instead. 

### What do you see instead?

See above

**Comment by raikasdev** [comment]
Can confirm happening in version 1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

**Comment by joshunrau** [comment]
Also in v1.0.3
