### ISSUE TITLE
export default class extends EventEmitter (has commonjs symbol) breaks.

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#2996]
### What version of Bun is running?

0.6.2

### What steps can reproduce the bug?

You can try using the `jimp` module or this reproduction:

`node_modules/jimp/index.js`
```ts
const EventEmitter = function () { };

EventEmitter[Symbol.for("CommonJS")] = 0; // bug is here

class Jimp extends EventEmitter { }

export default Jimp;
export const a = 123;
```

```ts
import Default, { a } from "jump";
console.log(a, Default);
```

### What is the expected behavior?

exports are properly imported
`123 [Function: Jimp]`

### What do you see instead?

`undefined undefined`. The commonjs symbol is making the class the `module.exports` object and then giving undefined on both `default` and `a`

### Additional information

probably for a different reason but the package above, with the commonjs line commented out, breaks when bundling too.

**Comment by paperclover** [comment]
For extra context, the events module defines `Symbol.for("CommonJS")`, which is checked for internally; what it does is the equiv of doing `module.exports =` but its used in the default export (this is how commonjs modules work at all), but this presents this edge case where that symbol is still visible.

Maybe we can set the symbol to 1 within the module, then 0 after checking; that way re-exporting wouldn't trigger that behavior twice in a row?

**Comment by paperclover** [comment]
this was fixed but `jimp` does not yet work for a different bug

**Comment by joaomendoncaa** [comment]
@paperdave Could you point us towards said bug so we can track it? Thanks in advance!

**Comment by paperclover** [comment]
there isn't one open right now, as I didn't look through it enough to trace what the exact bug was.

**Comment by Jarred-Sumner** [comment]
feel free to open a bug for jimp specifically @joaomendoncaa

**Comment by joaomendoncaa** [comment]
> there isn't one open right now, as I didn't look through it enough to trace what the exact bug was.

Would love to know more about it if possible. I would really take advantage of running bun in a tool which uses jimp but isn't running because of the above mentioned.

**Comment by paperclover** [comment]
I should've clarified what happens and why I didn't look into it:

I ran their first example and it wrote an empty buffer, no errors reported. this isn't trivial to investigate

**Comment by joaomendoncaa** [comment]
> feel free to open a bug for jimp specifically @joaomendoncaa

I feel like they'll tell me the same thing :/ Sadly fault it on bun support and point me here.

**Comment by Jarred-Sumner** [comment]
@joaomendoncaa It's bun specifically at fault, not jimp. Feel free to open an issue in Bun's repository for us to make `jimp` work in Bun.

**Comment by joaomendoncaa** [comment]
> I should've clarified what happens and why I didn't look into it:
> 
> I ran their first example and it wrote an empty buffer, no errors reported. this isn't trivial to investigate

Actually the above was done because of a "help ticket" on discord.

The actual breaking error on the tool is the following in case it helps:
![image](https://github.com/oven-sh/bun/assets/57664150/30628641-2710-4481-8317-ba27e4500968)

**Comment by joaomendoncaa** [comment]
> @joaomendoncaa It's bun specifically at fault, not jimp. Feel free to open an issue in Bun's repository for us to make `jimp` work in Bun.

Ohhh, gotcha! Will do!

**Comment by joaomendoncaa** [comment]
> @joaomendoncaa It's bun specifically at fault, not jimp. Feel free to open an issue in Bun's repository for us to make `jimp` work in Bun.

For context and guidance, added the issue in #3122! Thank you all.
