### ISSUE TITLE
bun install / binary in wrong place

### ISSUE THREAD

**Issue by samopus1io** [oven-sh/bun#2998]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

- yarn init
- yarn add @sentry/cli

notice sentry-cli below.

```
❯ ls -la node_modules/@sentry/cli
total 52296
drwxr-xr-x@ 11 samlll42  wheel       352 May 22 09:58 .
drwxr-xr-x@  3 samlll42  wheel        96 May 22 09:57 ..
-rw-r--r--@  1 samlll42  wheel      1528 May 22 09:57 LICENSE
-rw-r--r--@  1 samlll42  wheel      5309 May 22 09:57 README.md
drwxr-xr-x@  3 samlll42  wheel        96 May 22 09:57 bin
-rw-r--r--@  1 samlll42  wheel       814 May 22 09:57 checksums.txt
drwxr-xr-x@  7 samlll42  wheel       224 May 22 09:57 js
drwxr-xr-x@  3 samlll42  wheel        96 May 22 09:57 node_modules
-rw-r--r--@  1 samlll42  wheel      1633 May 22 09:57 package.json
drwxr-xr-x@  7 samlll42  wheel       224 May 22 09:57 scripts
-rwxr-xr-x@  1 samlll42  wheel  26751672 May 22 09:58 sentry-cli
```

with Bun the sentry-cli binary is not there

```
❯ bun install @sentry/cli --yarn
bun add v0.6.2 (8d90d795)

 installed @sentry/cli@2.18.1 with binaries:
  - sentry-cli


 13 packages installed [332.00ms]
❯ ls -la node_modules/@sentry/cli
total 40
drwxr-xr-x@ 9 samlll42  wheel   288 May 22 09:58 .
drwxr-xr-x@ 3 samlll42  wheel    96 May 22 09:58 ..
-rw-r--r--@ 1 samlll42  wheel  1528 May 22 09:58 LICENSE
-rw-r--r--@ 1 samlll42  wheel  5309 May 22 09:58 README.md
drwxr-xr-x@ 3 samlll42  wheel    96 May 22 09:58 bin
-rw-r--r--@ 1 samlll42  wheel   814 May 22 09:58 checksums.txt
drwxr-xr-x@ 7 samlll42  wheel   224 May 22 09:58 js
-rw-r--r--@ 1 samlll42  wheel  1633 May 22 09:58 package.json
drwxr-xr-x@ 7 samlll42  wheel   224 May 22 09:58 scripts
```

### What is the expected behavior?

It looks like bun install is not handling certain part of the package install correctly or am I missing something?

**Comment by canopus1io** [comment]
![image](https://github.com/oven-sh/bun/assets/68567963/f24e6855-3116-4463-876b-d43204fa2497)
I have found that after running this install script, sentry-cli is in the root of the node_modules

yarn must be executing this script as part of the install process

**Comment by muan** [comment]
I just ran into the same problem with `sqlite3` package which also has an [`install` script](https://github.com/TryGhost/node-sqlite3/blob/dfbe3ba5287c5901c1d32840cd54fc3c5f61d3f5/package.json#L74) that was not run when I add the package with `bun add` but does when I add it with `yarn`.

**Comment by crishoj** [comment]
> I just ran into the same problem with sqlite3 package which also has an [install script](https://github.com/TryGhost/node-sqlite3/blob/dfbe3ba5287c5901c1d32840cd54fc3c5f61d3f5/package.json#L74) that was not run when I add the package with bun add but does when I add it with yarn.

For anyone in the same situation, to invoke the missing install script for `sqlite3` manually, do:

```bash
cd node_modules/sqlite3
npx node-pre-gyp install --fallback-to-build
```

**Comment by zachbryant** [comment]
For packages that don't have an install script, this is still an issue. On a fresh install with just-scripts, I expected to see the path `node_modules/just-scripts/bin/just-scripts.js`, however all I see are a trail of `node_modules` folders with no binaries.

**Comment by HappyGick** [comment]
Ran into this problem when using the ssh2 package. It couldn't find a binary dependency and thus didn't run.

**Comment by byCedric** [comment]
I don't think this is an issue with Bun, it's caused by Sentry's own CLI wrapping script. The Sentry CLI is written in Rust, and therefore is a bit "wacky" regarding npm installs. Basically, they have:

- JS wrapping code around the Rust binary ([here](https://github.com/getsentry/sentry-cli/blob/2353fa1ffa4b16952c1cc91664ed1da486b7a153/bin/sentry-cli#L8-L16))
- A custom Rust binary install script ([hooked into the **package.json** `install` script](https://github.com/getsentry/sentry-cli/blob/master/package.json#L33))

And, due to [Bun not executing lifecycle scripts](https://bun.sh/docs/cli/install#trusted-dependencies), this Rust binary install script is never called. This is "due to security risks", which makes sense.

Can you add `trustedDependencies` this to your **package.json** @samopus1io, delete lock file (`bun.lockb`) and local modules (`node_modules`), and install again through `bun install`? E.g. like:

```json package.json
{
  "name": "my-app",
  "version": "1.0.0",
  ...
  "trustedDependencies": ["@sentry/cli"],
  ...
}
```

Then run:

```
$ rm -rf node_modules bun.lockb
$ bun install
```

No idea why Sentry just doesn't ship their Rust binary within the npm package, and instead, rely on remotely downloading an executable binary 🙈

**Comment by juanmagalhaes** [comment]
> I don't think this is an issue with Bun, it's caused by Sentry's own CLI wrapping script. The Sentry CLI is written in Rust, and therefore is a bit "wacky" regarding npm installs. Basically, they have:
> 
> * JS wrapping code around the Rust binary ([here](https://github.com/getsentry/sentry-cli/blob/2353fa1ffa4b16952c1cc91664ed1da486b7a153/bin/sentry-cli#L8-L16))
> * A custom Rust binary install script ([hooked into the **package.json** `install` script](https://github.com/getsentry/sentry-cli/blob/master/package.json#L33))
> 
> And, due to [Bun not executing lifecycle scripts](https://bun.sh/docs/cli/install#trusted-dependencies), this Rust binary install script is never called. This is "due to security risks", which makes sense.
> 
> Can you add `trustedDependencies` this to your **package.json** @samopus1io, delete lock file (`bun.lockb`) and local modules (`node_modules`), and install again through `bun install`? E.g. like:
> 
> ```json
> {
>   "name": "my-app",
>   "version": "1.0.0",
>   ...
>   "trustedDependencies": ["@sentry/cli"],
>   ...
> }
> ```
> 
> Then run:
> 
> ```
> $ rm -rf node_modules bun.lockb
> $ bun install
> ```
> 
> No idea why Sentry just doesn't ship their Rust binary within the npm package, and instead, rely on remotely downloading an executable binary 🙈

Had this same issue and this fix worked for me! Thank you @byCedric!!!

**Comment by lksnmnn** [comment]
Hey, I am having the same issue with `@sentry/nextjs`. However, adding both this and the `cli` package as `trustedDependencies` does work. I even cleared the global bun cache to no avail.

**Comment by dylan-conway** [comment]
Closing as complete. This was fixed when support for lifecycle scripts was added to `bun install` in Bun v1.0.17.

Packages that aren't in the [default trusted list](https://github.com/oven-sh/bun/blob/main/src/install/default-trusted-dependencies.txt) will need to be added to `"trustedDependencies"` in package.json for their scripts to run on install. You can edit manually or use `bun add <package> --trust`. If the package is already installed, `bun pm trust` can be used to run scripts and add to package.json.
