### ISSUE TITLE
Replacing `pnpm` with `bun` fails in scripts

### ISSUE THREAD

**Issue by cyberalien** [oven-sh/bun#300]
Sometimes when running a script from `package.json`, script specifies package manager. I'm mostly using that to run different unit tests in different environments which cannot be ran in one command.

Example `package.json`:
```json
{
	"scripts": {
		"success": "pnpm run foo",
		"fail1": "pnpm run foo && pnpm run bar",
		"fail2": "env NODE_OPTIONS=--experimental-vm-modules pnpm run foo"
	}
}
```

There are 3 scripts in `package.json` (+ 2 missing dummy scripts `foo` and `bar`, but they are irrelevant for showing error).

Script `success` works as expected: `bun run success` runs `bun run foo`.

Script `fail1` fails: `bun run fail1` runs `bun run foo && pnpm run bar`. Only first command is replaced.

Script `fail2` fails: `bun run fail2` runs command as is, not replacing `pnpm`.

- - -

I'd like to suggest a possible solution: allow to override entries in `scripts`. For example, if looking for `foo`, look for `bun:foo` first and run it instead:

```json
{
	"scripts": {
		"success": "pnpm run foo",
		"fail1": "pnpm run foo && pnpm run bar",
		"bun:fail1": "bun run foo && bun run bar",
		"fail2": "env NODE_OPTIONS=--experimental-vm-modules pnpm run foo",
		"bun:fail2": "env NODE_OPTIONS=--experimental-vm-modules bun run foo"
	}
}
```

**Comment by Electroid** [comment]
Tested as of Bun 0.5.8, and this is now fixed. If you're still running into this issue, please let us know.
