### ISSUE TITLE
Nodemailer does not work

### ISSUE THREAD

**Issue by Akumzy** [oven-sh/bun#3003]
### What version of Bun is running?

0.6.2

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```ts
'use strict';
import nodemailer from 'nodemailer';

// async..await is not allowed in global scope, must use a wrapper
async function main() {
  // Generate test SMTP service account from ethereal.email
  // Only needed if you don't have a real mail account for testing
  const transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: '...',
      pass: '...',
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: '"Fred Foo 👻" <foo@example.com>', // sender address
    to: 'example@gmail.com', // list of receivers
    subject: 'Hello ✔', // Subject line
    text: 'Hello world?', // plain text body
    html: '<b>Hello world?</b>', // html body
  });

  console.log('Message sent: %s', info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>

  // Preview only available when sending through an Ethereal account
  console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
  // Preview URL: https://ethereal.email/message/WaQKMgKddxQDoou...
}

main().catch(console.error);

```

### What is the expected behavior?

To send email successfully

### What do you see instead?

Depending on the SMTP credentials I'm getting different errors
```log
1371 |             return;
1372 |         }
1373 | 
1374 |         this._upgradeConnection((err, secured) => {
1375 |             if (err) {
1376 |                 this._onError(new Error('Error initiating TLS - ' + (err.message || err)), 'ETLS', false, 'STARTTLS');
                                 ^
error: Error initiating TLS - Expected "port" to be a number between 0 and 65535
 code: "ETLS"

      at /Users/[redacted]/node_modules/nodemailer/lib/smtp-connection/index.js:1376:30
      at _actionSTARTTLS (/Users/[redacted]/node_modules/nodemailer/lib/smtp-connection/index.js:1374:8)

```
and also

```log
error: DNS lookup failed: Given hostname is not numeric
 code: "EDNS"
```

**Comment by cirospaciari** [comment]
Missing socket option on `tls.connect` https://nodejs.org/api/tls.html#tlsconnectoptions-callback

**Comment by Akumzy** [comment]
@cirospaciari oh!
Hopefully that'll be added soon

**Comment by binary-koan** [comment]
Same as https://github.com/oven-sh/bun/issues/2981 I think

This is breaking the `postgres` package for me as well - localhost works but using a remote domain (e.g. with neon.tech) fails with the same error. Looking at the postgres package code, it does seem to be using the `socket` parameter to connect

**Comment by bitdom8** [comment]
any progress? @Akumzy

**Comment by Akumzy** [comment]
@bitdom8 I really don't know as I've checked again to gotten any feedback from Oven team

**Comment by bitdom8** [comment]
nope

**Comment by Jarred-Sumner** [comment]
Please give it another try in the canary build in about 40 minutes (once it finishes compiling)

```bash
bun upgrade --canary
```

**Comment by bitdom8** [comment]
Sounds like GDA go do action @Jarred-Sumner  thanks

**Comment by bitdom8** [comment]
It states it's fixed but it's not https://bun.sh/blog/bun-v0.6.13#nodemailer-works. Get 

`state.length while ret = null 0
Segmentation fault`

in running, sometimes get this:

`state.length while ret = null 0
290 |       }).catch((error) => {
291 |         this.emit("error", error);
292 |       });
293 |     else
294 | 
295 |       bunConnect({
         ^
error: Failed to connect
 code: "ECONNECTION"` 
 
 tried with host: 'smtp.gmail.com', the config and variables works with nodejs fine

**Comment by bitdom8** [comment]
ANy success @Jarred-Sumner , can't wait to use bun.sh

**Comment by bitdom8** [comment]
@Jarred-Sumner

**Comment by bitdom8** [comment]
İt works now. Thank you @Jarred-Sumner

**Comment by Jarred-Sumner** [comment]
All credit goes to @cirospaciari

**Comment by bitdom8** [comment]
Thanks. It works when having it runed on cmd linux ssh but when started on .service file:

Jul 18 13:09:02 xxyy xxx.service[751]: error: Error initiating TLS - Expected "port" to be a number between 0 and 65535

what's wrong here? @cirospaciari

**Comment by cirospaciari** [comment]
> Thanks. It works when having it runed on cmd linux ssh but when started on .service file:
> 
> Jul 18 13:09:02 xxyy xxx.service[751]: error: Error initiating TLS - Expected "port" to be a number between 0 and 65535
> 
> what's wrong here? @cirospaciari 

Looks like it is running an older version, can you confirm the version that is being executed?

**Comment by bitdom8** [comment]
Thanks for speedy reply. @cirospaciari  It's new

xx@yy:/usr/local/lsws/nodes/xx$ bun -v
0.6.14

this results an error:
` sudo /root/.bun/bin/bun --hot serverwh.ts`
 
 when I go to folder and run 
 `bun serverwh.ts`
 all is well. No error as such below:
 
 Jul 18 13:09:02 xxyy xxx.service[751]: error: Error initiating TLS - Expected "port" to be a number between 0 and 65535

**Comment by cirospaciari** [comment]
> Thanks for speedy reply. @cirospaciari  It's new
> 
> xx@yy:/usr/local/lsws/nodes/xx$ bun -v
> 0.6.14
> 
> this results an error:
> ` sudo /root/.bun/bin/bun --hot serverwh.ts`
>  
>  when I go to folder and run 
>  `bun serverwh.ts`
>  all is well. No error as such below:
>  
>  Jul 18 13:09:02 xxyy xxx.service[751]: error: Error initiating TLS - Expected "port" to be a number between 0 and 65535

Interesting, can you try `sudo /root/.bun/bin/bun upgrade --canary` to see if it works?

**Comment by bitdom8** [comment]
I understood now. We didn't update with sudo command as `sudo curl -fsSL https://bun.sh/install | bash`

Thus it was mistaking the old version as a command file. Now it works. However you were right about last version @cirospaciari . Thanks

**Comment by cirospaciari** [comment]
> I understood now. We didn't update with sudo command as `sudo curl -fsSL https://bun.sh/install | bash`
> 
> Thus it was mistaking the old version as a command file. Now it works

Happy that's worked for you

**Comment by bitdom8** [comment]
After update to 0.8, nodemailer not works

```
if (this.remotePort = port, socket.data = this, socket.timeout(this.timeout), socket.ref(), this[bunSocketInternal] = socket, this.connecting = !1, !this.#upgraded)
218 |       this.emit("connect", this);
219 |     Socket2.#Drain(socket);
220 |   }
221 | 
222 |   connect(port, host, connectListener) {
                     ^
error: Failed to connect
 code: "ECONNECTION"

      at connect (node:net:222:18)
      at /mnt/c/Users/Administrator/Documents/Bun/q/node_modules/nodemailer/lib/smtp-connection/index.js:354:35
      at /mnt/c/Users/Administrator/Documents/Bun/q/node_modules/nodemailer/lib/shared/index.js:152:19
      at /mnt/c/Users/Administrator/Documents/Bun/q/node_modules/nodemailer/lib/shared/index.js:66:15
```

@cirospaciari @colinhacks Thanks for awesomeness on this amazing lib

**Comment by bitdom8** [comment]
Ok, it doesn't work on first try, but in second try, it works.

That's why it doesn't work on linux .service scripts

**Comment by bitdom8** [comment]
It doesn't ork also when script is runned from another subfolder as `cd subfolder;bun indexapihere.ts`

**Comment by bitdom8** [comment]
Here is the .service log

```
Aug 24 19:15:10 nodemailerservice.service[2387]:  syscall: "open"
Aug 24 19:15:10 nodemailerservice.service[2387]:    errno: -6
Aug 24 19:15:10 nodemailerservice.service[2387]:       at new WriteStream2 (node:fs:428:26)
Aug 24 19:15:10 nodemailerservice.service[2387]:       at WriteStream3 (node:fs:419:46)
Aug 24 19:15:10 nodemailerservice.service[2387]:       at new  (node:tty:22:50)
Aug 24 19:15:10 nodemailerservice.service[2387]:       at node:tty:22:50
Aug 24 19:15:10 nodemailerservice.service[2387]:       at getStdioWriteStream (:1:20)
Aug 24 19:15:10 nodemailerservice.service[2387]:       at node:stream:2027:82
Aug 24 19:15:10 nodemailerservice.service[2387]:       at /usr/local/lsws/nodes/bun/node_modules/nodemailer/lib/fetch/index.js:238:12
Aug 24 19:15:10  nodemailerservice.service[2387]:       at node:http:853:28
```
