### ISSUE TITLE
`console.log()` of an array does not show non-index properties

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#301]
```
const arr = ['a', 'b', 'c'];
arr['five'] = 5

console.log(arr)
```

Above program if run with node returns:

`[ 'a', 'b', 'c', five: 5 ]`

With `bun`, it returns:

`[ "a", "b", "c" ]`

Was going through a course on [ExecuteProgram.com](https://www.executeprogram.com) and they had it as one of their lessons to teach that arrays in JS are also objects. 

Actually in safari if you run above, it will return what `bun` returns but chrome will return what `node` does. This makes sense given how zig is built on JavaScriptCore. Just found it interesting. I guess this can be closed. JavaScriptCore probably chose to do it this way for perf reasons as no sane person would modify arrays with custom properties.

**Comment by AbdelrhmanSaid** [comment]
I guess it's more logic, cause `five` is not an entry like `a` or `b`, it's a new prop added to `arr`.

**Comment by nikivdev** [comment]
Yea going to close this as bun is using console.log() from JavaScriptCore so it's a question to them rather than bun.

**Comment by Jarred-Sumner** [comment]
bun implements console.log -- it's a bug in bun's implementation that it doesn't look at array properties

**Comment by nikivdev** [comment]
> it's a bug in bun's implementation that it doesn't look at array properties

But if you run above code snippet in safari console, you also won't see properties. 

<img width="216" alt="image" src="https://user-images.githubusercontent.com/6391776/177641868-3ba829b4-4377-4ea0-928c-96509567d163.png">
