### ISSUE TITLE
bash: line 167: 261707 Illegal instruction

### ISSUE THREAD

**Issue by NatoBoram** [oven-sh/bun#302]
My default shell is `zsh`. When running the install command, I get this error:

```bash
❯ curl https://bun.sh/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4906    0  4906    0     0  25322      0 --:--:-- --:--:-- --:--:-- 25419
######################################################################## 100.0%
Bun was installed successfully to /home/nato/.bun/bin/bun
bash: line 167: 261707 Illegal instruction     (core dumped) IS_BUN_AUTO_UPDATE="true" SHELL="zsh" $exe completions > /dev/null 2>&1

 Added "/home/nato/.bun/bin" to $PATH in "~/.zshrc"

To get started, run

   exec /usr/bin/zsh
   bun --help
```

**Comment by rubyFeedback** [comment]
I run into the exact same issue.

I aliased "bun" to the bin; stat /root/.bun/bin/bun also works so
the file exists (as superuser). But running it I get illegal instructions.

I think it would be useful to show more information to the user WHY
this fails. Right now I only get these two words and I have no idea
about what to do next.

**Comment by delight** [comment]
Pretty much the same here
```
bun run 
zsh: illegal hardware instruction  bun run
```

bun -v
0.1.1 
is the only thing that works correctly

OS: Kde Neon (baiscally and ubuntu 20.04 / focal ) x86_64

**Comment by yozlet** [comment]
This may be the same as issue #282: the x86_64 build of bun 0.1.1 requires AVX2 support in your CPU.

**Comment by hrmtn** [comment]
Possible duplicate of #67

**Comment by NatoBoram** [comment]
Right, I investigated more into it and it's indeed a duplicate of #67. I thought it was a different issue because it happened at installation time, but the installer is actually calling `bun`.

To make it work, we have to download [intel-sde](https://www.intel.com/content/www/us/en/download/684897/732268/intel-software-development-emulator.html), unzip it somewhere like `$HOME/Applications/intel-sde` like some kind of Windows peasant, add it to `$PATH` then add an alias from `bun` to `sde`.

```zsh
export BUN_INSTALL="$HOME/Applications/bun"
PATH="$BUN_INSTALL/bin:$PATH"

PATH="$HOME/Applications/intel-sde:$PATH"
alias bun='sde -chip-check-disable -- bun'
```

* https://github.com/Jarred-Sumner/bun/issues/282#issuecomment-1177154684


This, however, makes `bun` excruciatingly slow.
