### ISSUE TITLE
[optimization] Delta updates

### ISSUE THREAD

**Issue by Bellisario** [oven-sh/bun#3022]
### What is the problem this feature would solve?

Currently, running the `upgrade` command on Bun, it downloads each time all the binary file, which is very slow if using poor connections.

### What is the feature you are proposing to solve the problem?

Using [Delta updates](https://en.wikipedia.org/wiki/Delta_update), the update size will be noticeably reduced, because each update will only contain the changed parts of the binary file.

---

Anyway, this could be very difficult to implement:
- Bun updater should handle delta files
- Bun releases should contain delta files, too: it means delta updates should be calculated each time and should compare the "old" and "new" release, plus it requires a delta update for each platform and requires the user to have the "latest" build or the delta update to be available for a user coming from a specific version

### What alternatives have you considered?

The current update method is good enough for most users...
...but enhancing and making it faster (and being fast is a must for Bun) would grant a better user experience and "instantaneous" updates.

**Comment by Electroid** [comment]
We could do this, but it's not worth the maintenance and potential for issues.
