### ISSUE TITLE
Emoji broken with `common-tags` package after upgrade to Bun 0.6.3

### ISSUE THREAD

**Issue by spiffytech** [oven-sh/bun#3031]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 6.2.15-300.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```js
import {stripIndent} from 'common-tags';
console.log(stripIndent`🐰`); 
```
`bun run index.js`

### What is the expected behavior?

A bunny is printed to the console

### What do you see instead?

After upgrading from Bun 0.6.2 to 0.6.3, the output is `ð°`.

### Additional information

This affects HTTP responses, too.

**Comment by Jarred-Sumner** [comment]
A change we made to printing tagged template literals was incorrect. In Bun's runtime, it needs to print them as unicode escape sequences instead of the utf-8 byte sequence

**Comment by reedspool** [comment]
I think I have a very similar issue?

Bun version 1.1.10

```typescript
const html: typeof String.raw = (templates, ...args): string =>
    String.raw(templates, ...args);

console.log(`💣`);
console.log(html`💣`);
```

Expect the two log outputs to be the same, the bomb emoji

Actual:

```
💣
\u{1f4a3}
```
