### ISSUE TITLE
bun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bun)

### ISSUE THREAD

**Issue by victorhernandezo** [oven-sh/bun#304]
tryng to run bun ubuntu 18.04

**Comment by Coding-Crashkurse** [comment]
I had the same Problem, for me it just worked out of the box on Ubuntu 20. Installation of GLIBC_2.29 was not possible

**Comment by FinnRG** [comment]
Duplicate of #255. Please close this issue.
