### ISSUE TITLE
`.env` prevents usage of `bun install` and `bun add`

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#3042]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

I currently have a `.env` file with the following data:
```
PORT="7000"
USERNAME="test1"
PASSWORD="test2"
```
While the file is present I can't run `bun install` and `bun add`.

### What is the expected behavior?

I expected to be able to run `bun install` and `bun add` and the package would be added to my project.

### What do you see instead?

Segmentation fault

**Comment by Jarred-Sumner** [comment]
jeez

thank you

**Comment by e3dio** [comment]
> Microsoft Windows NT 10.0.19045.0 x64

I thought Windows was not supported

**Comment by Quatton** [comment]
Looks like it does. I had the same issue with `.env.local` as well.

**Comment by Jarred-Sumner** [comment]
I did try to investigate last week but I wasn't able to reproduce the issue. Can you send more information about your computer? Are there non-ascii filenames in the current or parent directories? Are there windows newlines in the `.env` files? 

Could you send a .zip file with as much redacted but minimally reproducible as you can?

**Comment by Quatton** [comment]
> Are there windows newlines in the .env files?

I changed the newline to `LF` and the issue is fixed for me. 
OP also uses Windows as well and that's probably why.

Thank you!
