### ISSUE TITLE
Next.js does not work with bun v0.6.3

### ISSUE THREAD

**Issue by jim-king-2000** [oven-sh/bun#3043]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Ubuntu 23.04

### What steps can reproduce the bug?

1. Create an demo project of Next.js.
1. `bun run dev`

### What is the expected behavior?

Next.js starts successfully.

### What do you see instead?

```
TypeError: undefined is not an object (evaluating 'delete import.meta.require.cache[__filename]')
      at /home/jim/test/nextjs/node_modules/next/dist/compiled/conf/index.js:1:105361
      at __nccwpck_require__ (/home/jim/test/nextjs/node_modules/next/dist/compiled/conf/index.js:15:28568)
      at /home/jim/test/nextjs/node_modules/next/dist/compiled/conf/index.js:15:28860
      at /home/jim/test/nextjs/node_modules/next/dist/compiled/conf/index.js:15:28901
      at /home/jim/test/nextjs/node_modules/next/dist/telemetry/storage.js:12:28
      at /home/jim/test/nextjs/node_modules/next/dist/cli/next-dev.js:22:6
      at /home/jim/test/nextjs/node_modules/next/dist/lib/commands.js:15:21
      at /home/jim/test/nextjs/node_modules/next/dist/bin/next:150:0
      at bun:main:3:0
error: script "dev" exited with code 1 (SIGHUP)
```

### Additional information

It works when bun v0.6.2 is used. It fails when being upgraded to v0.6.3.

**Comment by jim-king-2000** [comment]
It is fixed on Bun v0.6.6.

**Comment by jim-king-2000** [comment]
Still exists on v0.6.6.

**Comment by jim-king-2000** [comment]
Still exists on v0.6.9.

**Comment by refrehz** [comment]
Hi,

I'm using Ubuntu 22.04. After creating Next.js application with Bun, I get this error whenever I run. I tried both on native ubuntu and wsl.

`TypeError: Loadable.preloadAll is not a function. (In 'Loadable.preloadAll()', 'Loadable.preloadAll' is undefined)`

This error is based on bun-framework-next module.

**Comment by jim-king-2000** [comment]
I can't verify the fix because of #2688. Postpone the closure until #2688 is fixed.

**Comment by jim-king-2000** [comment]
Fixed on bun v0.7.3.

**Comment by Jarred-Sumner** [comment]
it doesn't actually work still, the CLI loads successfully but requests don't respond due to lack of child_process IPC

**Comment by jim-king-2000** [comment]
> it doesn't actually work still, the CLI loads successfully but requests don't respond due to lack of child_process IPC

What is the symptom? I follow the "manual installation" instruction [here](https://nextjs.org/docs/getting-started/installation) and it works well.
