### ISSUE TITLE
bun init old types in packages.json file

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#3046]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 6.3.2-1-default x86_64 x86_64

### What steps can reproduce the bug?

create new directory, run `bun init` and look into `package.json`, old version of types

### What is the expected behavior?

```
{
  "name": "bunovel",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.6.0"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

### What do you see instead?

```
{
  "name": "bunovel",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.5.0"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

**Comment by paperclover** [comment]
this is fixed in canary
