### ISSUE TITLE
mongodb is not connecting with bun v0.6.3

### ISSUE THREAD

**Issue by prolazydev** [oven-sh/bun#3054]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

The code that reproduced the bug:

```ts
import { MongoClient } from 'mongodb';

try {
	const dbClient = new MongoClient('mongodb://127.0.0.1:27017');
	await dbClient.connect();

	const db = dbClient.db('mytestdb');
	const Car = db.collection('Car');
	await Car.insertOne({ type: 'Audi', color: 'black', topSpeed: 360 });
	const res = Car.find();

	console.log(res);
} catch (err) {
	console.error(err);
}
```
This was on a fresh `bun init` project with only `bun install mongodb` dependency

### What is the expected behavior?

A connection to the mongodb database, a new collection created, an insert done and the data from that collection as written in the code above.

### What do you see instead?

The WSL Ubuntu Console output after running `bun run index.ts` :

```
94 |         if (message instanceof Error) {
95 |             super(message.message);
96 |             this.cause = message;
97 |         }
98 |         else {
99 |             super(message);
                ^
error: Failed to connect
 code: "undefined"

      at new MongoError (/home/mul/work/#TESTING/node_modules/mongodb/lib/error.js:99:12)
      at new MongoSystemError (/home/mul/work/#TESTING/node_modules/mongodb/lib/error.js:589:12)
      at new MongoServerSelectionError (/home/mul/work/#TESTING/node_modules/mongodb/lib/error.js:611:8)
      at /home/mul/work/#TESTING/node_modules/mongodb/lib/sdam/topology.js:278:37
```

**Comment by prolazydev** [comment]
Also forgot to add that I was using `"mongodb": "^5.5.0"`

**Comment by Electroid** [comment]
Between Bun v1.0 and v1.0.7, we've made a lot of fixes to TCP/TLS connections. The "Failed to connect" errors should be fixed. If you are still experiencing this error, after upgrading, please re-open this issue and we'll investigate.

**Comment by prolazydev** [comment]
> Between Bun v1.0 and v1.0.7, we've made a lot of fixes to TCP/TLS connections. The "Failed to connect" errors should be fixed. If you are still experiencing this error, after upgrading, please re-open this issue and we'll investigate.

Hi! I will do that tomorrow and let you know how it goes :> 
Ps. Will mostly wait for the native support whenever it is stable (no pressure)
