### ISSUE TITLE
bun init has the wrong version number used to create a project in the README.md

### ISSUE THREAD

**Issue by mattlgroff** [oven-sh/bun#3058]
### What version of Bun is running?

0.6.3

### What platform is your computer?

WSL2 Ubuntu 22.04

### What steps can reproduce the bug?

`bun init`

Look at the created `README.md`:

```markdown
This project was created using `bun init` in bun v0.5.3. [Bun](https://bun.sh) is a fast all-in-one JavaScript runtime.
```

### What is the expected behavior?

The README.md should either show the correct version of bun used to run `bun init` which in this case is `v0.6.3`

```
This project was created using `bun init` in bun v0.6.3. [Bun](https://bun.sh) is a fast all-in-one JavaScript runtime.
```

### What do you see instead?

```
This project was created using `bun init` in bun v0.5.3. [Bun](https://bun.sh) is a fast all-in-one JavaScript runtime.
```

### Additional information

This was happening on `0.6.2` and it was showing `0.5.2`.

I tried looking for the problem myself, it seems like this is the only place in the codebase utilizing `Global.version.fmt("")` (the `init_command.zig`. Nothing stood out to me as the root cause but as I don't write Zig I am creating an issue instead or a PR.

**Comment by Electroid** [comment]
Tested using Bun v1.0.7, Bun now uses the correct version.

```
This project was created using `bun init` in bun v1.0.7. [Bun](https://bun.sh) is a fast all-in-one JavaScript runtime.
```
