### ISSUE TITLE
clipanion not supported: TypeError: tty.WriteStream.prototype is not an Object. (evaluating '`getColorDepth` in tty.WriteStream.prototype')

### ISSUE THREAD

**Issue by CyriacBr** [oven-sh/bun#3072]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

Import clipanion and run `bun --bun`

### What is the expected behavior?

It should work.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/38442110/411df7a9-53f4-46ef-95c9-9969782e8fe3)

Seems like an issue with `tty.WriteStream`.  
This is similar to https://github.com/oven-sh/bun/issues/2081 I guess but the error message is different. Feel free to close if needed.

### Additional information

https://www.npmjs.com/package/clipanion

**Comment by vjpr** [comment]
Temp and hacky workaround:

```
require('tty').WriteStream.prototype = {}
```

**Comment by birkskyum** [comment]
Ran `import clipanion from 'clipanion'` with bun 0.8 and it works as expected. This can be closed.

**Comment by dylan-conway** [comment]
fixed in #4179
