### ISSUE TITLE
Failed to install bun inside Docker container

### ISSUE THREAD

**Issue by sandy-garrido** [oven-sh/bun#3075]
### What platform is your computer?

node:18-alpine

### How did you attempt to install or upgrade?

Build this dockerfile
```Dockerfile
FROM node:18-alpine
RUN apk update
RUN apk add --update bash

RUN npm install -g bun

ENTRYPOINT [ "/bin/sh" ]
```

### What do you see instead?

```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/bun
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Failed to find package "@oven/bun-linux-x64". You may have used the "--no-optional" flag when running "npm install".
npm ERR! Failed to find package "@oven/bun-linux-x64-baseline". You may have used the "--no-optional" flag when running "npm install".
npm ERR! Error: Failed to install package "bun"
npm ERR!     at /usr/local/lib/node_modules/bun/install.js:311:11
npm ERR!     at Generator.throw (<anonymous>)
npm ERR!     at rejected (/usr/local/lib/node_modules/bun/install.js:35:27)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-26T00_03_58_341Z-debug-0.log
```

### Additional information

Hi team,
I'm sure there's a reasonable explanation for this but wondered if this was considered a problem or not

**Comment by dimka3553** [comment]
try this maybe:

```dockerfile
# Use the offical Bun image
FROM oven/bun:latest

# Set the Docker working directory as /usr/src/app
# Copy everything root of the app into Docker's /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

# Install the dependencies
RUN bun install

# Run the app
CMD bun index.js
```

**Comment by sandy-garrido** [comment]
Thanks @dimka3553 yeah I did see this. I was trying to avoid this image but I may have to go for it any way.

**Comment by sandy-garrido** [comment]
I fixed it! It's actually not a Bun bug here, at least from what it seems. The alpine image is missing `glibc`.

```Dockerfile



# Install glibc (Bun dependancies)
RUN apk add gcompat
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk
RUN apk --no-cache --force-overwrite add glibc-2.35-r0.apk glibc-bin-2.35-r0.apk

RUN /usr/glibc-compat/bin/ldd /lib/ld-linux-x86-64.so.2 
```

This ended up allowing me to use Bun

**Comment by LayssonOL** [comment]
> I fixed it! It's actually not a Bun bug here, at least from what it seems. The alpine image is missing `glibc`.
> 
> ```dockerfile
> # Install glibc (Bun dependancies)
> RUN apk add gcompat
> RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
> RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk
> RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk
> RUN apk --no-cache --force-overwrite add glibc-2.35-r0.apk glibc-bin-2.35-r0.apk
> 
> RUN /usr/glibc-compat/bin/ldd /lib/ld-linux-x86-64.so.2 
> ```
> 
> This ended up allowing me to use Bun


Thank you, man! Worked well for me. I'm using the image `node:18-alpine3.18`
This worked for me too. For who don't worry to use bigger images (like `node:*-slim`) the bun installation works fine.
For me, I was looking for the best solution with an alpine image and only with this **glibc** installation process this was possible.

PS: ` apk add gcompat` didn't work.
