### ISSUE TITLE
`bun build` error: Could not resolve: "fs/promises". Maybe you need to "bun install"

### ISSUE THREAD

**Issue by nickbeaulieu** [oven-sh/bun#3078]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

I am unable to build a script that imports `fs/promises` using `bun build` that runs successfully with `bun run`

**Minimal reproduction**

```ts
// fs-test.ts
import { readFile } from "fs/promises";

const contents = await readFile("./test.txt", "utf-8");
console.log("contents:", contents);
```
```ts
// test.txt
hello world
```
---
This works okay with `bun run`
```sh
$ bun run fs-test.ts
> contents: hello world
```

### What is the expected behavior?

`fs/promises` is built in, and works with `bun run` so I'd expect that I can build successfully. Anything that can be run should be able to be bundled.

### What do you see instead?

This fails with `bun build`
```sh
$ bun build fs-test.ts
>

error: Could not resolve: "fs/promises". Maybe you need to "bun install"?
import { readFile } from "fs/promises";
                         ^
```

### Additional information

I was not able to find a report of this issue already - apologies if it's a duplicate. I tried searching for issues that included `fs/promises` and the string "Maybe you need to"

Found #323 which is related to running, not building.

---

I also tried to use this format
```ts
import { promises } from "fs";

const contents = await promises.readFile("./test.txt", "utf-8");
console.log("contents:", contents);
```
Which built (and runs) successfully but resulted in an error when running the output script.
```sh
$ bun build fs-test.ts --outfile ./index.js

  index.js  0.14 KB

[5ms] bundle 1 modules

$ bun run ./index.js
1 | // fs-test.ts
2 | var {promises} = (() => ({}));
3 | var contents = await promises.readFile("./test.txt", "utf-8");
                         ^
TypeError: undefined is not an object (evaluating 'promises.readFile')
      at /Users/nick/Desktop/tester/index.js:3:21
```

I recognize that this is probably not related to `fs/promises` specifically, but more likely due to the path having a slash so the module resolution is not working.

**Comment by Jarred-Sumner** [comment]
To run code in Bun, you don't need to `bun build` (unless there is a bug). 

That being said,  try passing `--target=bun` or `--target=node`. By default, `bun build` sets `--target` to `browser`. It looks like we missed a case in the error message here - it should've told you to pass `--target=bun` or `--target=node`.
