### ISSUE TITLE
`node:child_process#spawn` doesn't fire `close` event if app exits immediately after spawned app exits

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3083]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Try the example from here: https://nodejs.org/api/child_process.html#event-close

```
const { spawn } = require('node:child_process');
const ls = spawn('ls', ['-lh', '/usr']);

ls.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

ls.on('close', (code) => {
  console.log(`child process close all stdio with code ${code}`);
});

ls.on('exit', (code) => {
  console.log(`child process exited with code ${code}`);
}); 
```

---

```
brew install watchman
```

```ts
import {spawn} from 'node:child_process'
import Bun from 'bun'

export default async function index() {
  console.log('Bun Child Process')

  //const watchmanBin = Bun.which('watchman')
  const watchmanBin = '/opt/homebrew/bin/watchman'

  const args = ['version']
  const spawnOpts = {
    stdio: ['pipe', 'pipe', 'pipe'],
  }
  const child = spawn(watchmanBin, args, spawnOpts)
  child.stdout.on('data', data => {
    data = data.toString('utf8')
    console.log(data)
  })
  child.stderr.on('data', data => {
    console.log(data)
  })
  child.on('close', (code, signal) => {
    console.log('closed')
    console.log({code, signal})
  })

  return 1
}

```

### What is the expected behavior?

Node.js

```
Bun Child Process
{
    "version": "2023.05.15.00"
}

closed
{ code: 0, signal: null }

```

### What do you see instead?

Bun

```
Bun Child Process
{
    "version": "2023.05.15.00"
}


```

### Additional information

This prevents `fb-watchman` package from working.

**Comment by vjpr** [comment]
https://github.com/oven-sh/bun/blob/0f2a79b9c1a5b0142f8099e94712799607e8990f/src/bun.js/child_process.exports.js#L1095

calls:

https://github.com/oven-sh/bun/blob/0f2a79b9c1a5b0142f8099e94712799607e8990f/src/bun.js/child_process.exports.js#L939

Only `exit` is being fired...but even that is not working.

---

I check with this underlying impl, and the issue is `process.nextTick` is not firing...

https://github.com/oven-sh/bun/blob/0f2a79b9c1a5b0142f8099e94712799607e8990f/src/bun.js/child_process.exports.js#L1083-L1102

**Comment by vjpr** [comment]
When I add `setInterval(() => {}, 100)` at the bottom of my program, it prints fine.

So the issue seems to be that the program exits before the `nextTick` in the `onExit` cb can fire.

**Comment by Hanaasagi** [comment]
The issue still persists in 1.0.1

```JavaScript
const { spawn } = require("node:child_process");

function exitHandler(code, signal) {
  console.log(code, signal);
}

const p = spawn("ls", ["-l"]);

p.on("exit", exitHandler);
p.on("close", exitHandler);

```

both `close` and `exit` is not emitted.
