### ISSUE TITLE
Fileupload error using Express/Multer (busboy) 

### ISSUE THREAD

**Issue by sp90** [oven-sh/bun#3085]
### What version of Bun is running?

0.6.4 (canary)

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Made a repo to simply reproduce the error:

1. `git clone https://github.com/sp90/bun-multer-busboy`
2. `bun run index.ts`
3.  Visit `localhost:3000`
4. Upload file
5. See the error in the terminal

### What is the expected behavior?

In this given example we should get the uploaded file meta data through a console.log

### What do you see instead?

```
Example app listening on port 3000
58 |             ++this.byteCount;
59 |             const code = chunk[pos];
60 |             if (TOKEN[code] !== 1) {
61 |               if (code !== 58/* ':' */)
62 |                 return -1;
63 |               this.name += chunk.latin1Slice(start, pos);
                               ^
TypeError: Expected string
      at push (/Users/simon/Documents/dev/multer-bun/node_modules/busboy/lib/types/multipart.js:63:27)
      at /Users/simon/Documents/dev/multer-bun/node_modules/busboy/lib/types/multipart.js:394:22
      at /Users/simon/Documents/dev/multer-bun/node_modules/streamsearch/lib/sbmh.js:248:4
      at push (/Users/simon/Documents/dev/multer-bun/node_modules/streamsearch/lib/sbmh.js:104:15)
      at _write (/Users/simon/Documents/dev/multer-bun/node_modules/busboy/lib/types/multipart.js:567:4)
      at writeOrBuffer (node:stream:3614:8)
      at node:stream:3574:13
      at ondata (node:stream:2987:20)
      at node:stream:2913:8
```

**Comment by sp90** [comment]
This also would close #2026

**Comment by sp90** [comment]
This issue persists in version `0.6.10`

**Comment by Hanaasagi** [comment]
`base64Slice` and `asciiSlice` also have the same issue. A reproducible code example is as follows:

```JavaScript
const buffer = require("node:buffer");

const buf = buffer.Buffer.from("hello world", "latin1");

console.log(buf.asciiSlice(1, 5));
console.log(buf.base64Slice(1, 5));
```

--- 

I'm attempting to resolve this problem, and it appears that making a modification like the following will be work:

```diff
diff --git a/src/js/builtins/JSBufferPrototype.ts b/src/js/builtins/JSBufferPrototype.ts
index 97b25b9b..f1c84596 100644
--- a/src/js/builtins/JSBufferPrototype.ts
+++ b/src/js/builtins/JSBufferPrototype.ts
@@ -436,8 +436,9 @@ export function ucs2Slice(this: BufferExt, offset, length) {
 export function utf16leSlice(this: BufferExt, offset, length) {
   return this.toString(offset, length, "utf16le");
 }
-export function latin1Slice(this: BufferExt, offset, length) {
-  return this.toString(offset, length, "latin1");
+export function latin1Slice(this: BufferExt, start, end) {
+  // return this.toString(offset, length, "latin1");
+  return this.toString("latin1", start, end);
 }
 export function asciiSlice(this: BufferExt, offset, length) {
   return this.toString(offset, length, "ascii");

```

But I'm curious why there is an overload here. At least in node, there is no overload (maybe a design in bun).
Ref: https://nodejs.org/api/buffer.html#buftostringencoding-start-end


https://github.com/oven-sh/bun/blob/68e6fe00a4be7857f474cb3aa80e0d876499e3f8/src/js/builtins/JSBufferPrototype.ts#L4-L9

And it seems that the overload here is not handled correctly.

```JavaScript
const buffer = require("node:buffer");

const buf = buffer.Buffer.from("hello world", "latin1");

console.log(buf.toString("latin1", 1, 2));
console.log(buf.toString(1, 2, "latin1"));

```

**Comment by Jarred-Sumner** [comment]
oh interesting

https://github.com/oven-sh/bun/blob/8984c819613b52b3cfaf1cd22fc059d0150eedfc/src/bun.js/bindings/JSBuffer.cpp#L1436-L1472

probably in here needs to be changed to handle the reversed order

we can just not use uncheckedArgument() and ensureStillAliveHere. argument(0), argument(1) etc will return jsUndefined similarly to JS

Instead we can do the simpler thing and assign the three JSValues at the top of the scope

Then check if the first one is a string. Otherwise if the last one is a string.

**Comment by Hanaasagi** [comment]
I think I understand what you mean, but there is one more thing I need to confirm.

```JavaScript
   toString(encoding?: BufferEncoding, start?: number, end?: number): string; 
   toString(offset: number, length: number, encoding?: BufferEncoding): string; 
```

According to the function signature, one function uses `start` and `end`, while the other function uses `offset` and `length`. Is the following behavior expected?

```JavaScript
const buf = buffer.Buffer.from("0123456789", "latin1");
assert.strictEqual(buf.toString("latin1", 3, 4), "3");
assert.strictEqual(buf.toString(3, 4, "latin1"), "3456");

```

**Comment by Jarred-Sumner** [comment]
wow thats confusing

**Comment by Hanaasagi** [comment]
Perhaps it's because of Bun's common use of `offset` and `length`(not sure). I noticed that the [buffer-related functions in the documentation](https://bun.sh/docs/api/binary-data#from-buffer) are written that way. In Node, however, they use `start` and `end`. This has resulted in the confusing parameters for `toString`.
