### ISSUE TITLE
AWS CDK - The superclass is not a constructor

### ISSUE THREAD

**Issue by sandy-garrido** [oven-sh/bun#3088]
### What version of Bun is running?

0.6.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Minimal repro repo: https://github.com/Sandy-Garrido/bun-cdk-superclass-bug

If you don't have CDK installed you can simply just `bun bin/cdk-bun.ts`

### What is the expected behavior?

I would expect the type check to pass
I would expect it to attempt deploying

### What do you see instead?

```Bash
$ cdk deploy
1 | import * as cdk from "aws-cdk-lib";
2 | export class CdkBunStack extends cdk.Stack {
           ^
TypeError: The superclass is not a constructor.
      at /home/ubuntu/projects/bun-cdk-superclass-bug/lib/cdk-bun-stack.ts:2:7

Subprocess exited with error 1
```

### Additional information

I already tried the suggested upgrading to canary release as of recently https://github.com/oven-sh/bun/issues/2826#issuecomment-1540532296 however, this did not fix it for me :( 
I also ran the same test within that bug report in the same directory with no problems, which proves out that https://github.com/oven-sh/bun/issues/2826 was in fact fixed but I still face a similar issue

**Comment by sandy-garrido** [comment]
I guess this is a separate issue but if I switch to named imports (Found a suggestion to a similar issue on discord), I get a different issue

```Typescript
import { Stack, App, StackProps } from "aws-cdk-lib";
export class CdkBunStack extends Stack {
  constructor(scope: App, id: string, props?: StackProps) {
    super(scope, id, props);
  }
}

```

The error now ends up being 
`SyntaxError: Import named 'Stack' not found in module '/home/ubuntu/projects/bun-cdk-superclass-bug/node_modules/aws-cdk-lib/index.js'.`

**Comment by Electroid** [comment]
Fixed as of Bun v1.0.26. If you're still experiencing this issue, let us know and we'll re-open this issue.

**Comment by laurensV** [comment]
I still get this error message (for a different package though) that I try to bundle with `bun 1.0.26`

**Comment by Electroid** [comment]
> I still get this error message (for a different package though) that I try to bundle with `bun 1.0.26`

Thanks for letting us know, would you mind opening an issue with some example code? @laurensV 🙏

**Comment by laurensV** [comment]
> > I still get this error message (for a different package though) that I try to bundle with `bun 1.0.26`
> 
> Thanks for letting us know, would you mind opening an issue with some example code? @laurensV 🙏

Opened an issue with example code and a link to a small example repo to reproduce the bug:
https://github.com/oven-sh/bun/issues/8925
