### ISSUE TITLE
Convert objects/arrays to TEXT datatype (bun:sqlite)

### ISSUE THREAD

**Issue by rinodrummer** [oven-sh/bun#309]
I saw the list of the supported [data types](https://github.com/Jarred-Sumner/bun#datatypes).

While looking, I haven't seen any `object` or `array` datatype binding.

It would be awesome to automatically cast those types to the TEXT datatype.

I have to test it in this days, but if they are already treated like this, it should be written in the documentation.

**Comment by maxmilton** [comment]
Implicit cast of objects to TEXT seems a bit too magical. It feels like binding an object to a TEXT column should throw an error (developers should explicitly `JSON.stringify` etc.).

Additionally, if there was implicit conversion, what is expected when retrieving data from the same TEXT field? Behaviour should be consistent both ways.

`better-sqlite3` does a pretty good job of providing error feedback in cases like this.

**Comment by rinodrummer** [comment]
> Implicit cast of objects to TEXT seems a bit too magical. It feels like binding an object to a TEXT column should throw an error (developers should explicitly `JSON.stringify` etc.).
> 
> Additionally, if there was implicit conversion, what is expected when retrieving data from the same TEXT field? Behaviour should be consistent both ways.
> 
> `better-sqlite3` does a pretty good job of providing error feedback in cases like this.

You are right, I only considered the SQLite standard that uses TEXT columns for JSON value.
