### ISSUE TITLE
`Symbol['for']` in `undefined` in Bun 0.6.4

### ISSUE THREAD

**Issue by zloirock** [oven-sh/bun#3091]
### What version of Bun is running?

0.6.4

### What platform is your computer?

macOS 13.4

### What steps can reproduce the bug?

It's a very strange bug that breaks `core-js`. In 0.6.3 all works fine.
```js
console.log(Symbol.for); // -> function
console.log(Symbol['for']); // -> undefined
```

**Comment by Jarred-Sumner** [comment]
Looks like a bug in Bun's transpiler. Seems to happen without minification enabled.

**Comment by zloirock** [comment]
Hey, it looks like a critical bug. Could you publish a patch release ASAP?

**Comment by Jarred-Sumner** [comment]
Will do today
