### ISSUE TITLE
bun 0.6.4  ，error after bun init when bun run or bun run index.ts

### ISSUE THREAD

**Issue by waltbest2** [oven-sh/bun#3106]
### What version of Bun is running?

0.6.4

### What steps can reproduce the bug?

bun init to create index.ts

but run error when bun run or bun run index.ts

it seems that path is wrong

### What is the expected behavior?

pass

### What do you see instead?

bun run index.ts

error: Could not resolve: "/opt/service/test/index.ts"

import * as start from '/opt/service/test/index.ts';
                       ^
bun:main:3:24 85

bun run
No "scripts" in package.json found.

there are package.json and initial scripts in the package.json

**Comment by Jarred-Sumner** [comment]
does the process have read permissions to that directory?

**Comment by waltbest2** [comment]
> permissions

in same user
i can run  bun help or  bun init
