### ISSUE TITLE
Http upstream encoding problem

### ISSUE THREAD

**Issue by wycers** [oven-sh/bun#3116]
### What version of Bun is running?

0.6.5_debug

### What platform is your computer?

Linux 6.2.15-200.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

1. generate a file filled with hex > 0x80
2. upload this file with formdata/multipart

### What is the expected behavior?

The server should receive a same file

### What do you see instead?

The server will receive a file, but hex in this file are replaced with `0xef 0xbf 0xbd`

**Comment by wycers** [comment]
And this issue may be related to #3085 and #2026.

I have dived into this bug for a little bit. I believe the problem is located at `src/bun.js/http.exports.js`. Maybe I can take up this and make a pr.

**Comment by wycers** [comment]
The root cause is [src/bun.js/http.exports.js#L1191](https://github.com/oven-sh/bun/blob/756e15f6e283fd7e21fe91e060d63440ce5c72de/src/bun.js/http.exports.js#L1191), the add operation implicitly calls Buffer.toString() and turns invalid `utf-8` bytes into `U+FFFD(�)`.

**Comment by sp90** [comment]
@Wycers any news still seems to be an issue in the canary version of bun :)

**Comment by Hanaasagi** [comment]
Hi, I'm trying to reproduce this problem.

> The root cause is [src/bun.js/http.exports.js#L1191](https://github.com/oven-sh/bun/blob/756e15f6e283fd7e21fe91e060d63440ce5c72de/src/bun.js/http.exports.js#L1191), the add operation implicitly calls Buffer.toString() and turns invalid utf-8 bytes into U+FFFD(�).

Based on your previous debugging, I guess you are referring to an issue on the client side. However, I couldn't reproduce locally, or perhaps I misunderstood something or there might be some problem with the steps.


1. Create binary file.
```
$ echo -n -e '\x80\x81\x82\x83' > byteFile
```

2. Client Code

```JavaScript
const fs = require("fs");
const http = require("http");

function uploadFile(filepath, url) {
  const fileStream = fs.createReadStream(filepath);

  const options = {
    method: "POST",
    headers: {
      "Content-Type": "multipart/form-data",
      "Content-Length": fs.statSync(filepath).size,
    },
  };

  const req = http.request(url, options, res => {
    res.on("data", chunk => {
      console.log(`BODY: ${chunk}`);
    });
    res.on("end", () => { });
  });

  req.on("error", e => {
    console.log("error", e);
  });

  fileStream.pipe(req);
}

const fileToUpload = "byteFile";
const uploadUrl = "http://httpbin.org/post";

uploadFile(fileToUpload, uploadUrl);


```

3. View HTTP request messages.

I'm using `strace` here to view system calls instead of packet capturing, but the effect should be the same.

```
strace -f -esendto -s1024 bun run a.js
```


![2023-07-02_22-55](https://github.com/oven-sh/bun/assets/9482395/45659e2f-2f22-4d3e-ad1f-cd3fa9f187b6)

`\200\201\202\203` corresponds to the octal values `\x80\x81\x82\x83`.



My Env

- bun 0.6.13 canary
- Linux 6.3.9-arch1-1

**Comment by wycers** [comment]
> Hi, I'm trying to reproduce this problem.
> 
> 
> 
> > The root cause is [src/bun.js/http.exports.js#L1191](https://github.com/oven-sh/bun/blob/756e15f6e283fd7e21fe91e060d63440ce5c72de/src/bun.js/http.exports.js#L1191), the add operation implicitly calls Buffer.toString() and turns invalid utf-8 bytes into U+FFFD(�).
> 
> 
> 
> Based on your previous debugging, I guess you are referring to an issue on the client side. However, I couldn't reproduce locally, or perhaps I misunderstood something or there might be some problem with the steps.
> 
> 
> 
> 
> 
> 1. Create binary file.
> 
> ```
> 
> $ echo -n -e '\x80\x81\x82\x83' > byteFile
> 
> ```
> 
> 
> 
> 2. Client Code
> 
> 
> 
> ```JavaScript
> 
> const fs = require("fs");
> 
> const http = require("http");
> 
> 
> 
> function uploadFile(filepath, url) {
> 
>   const fileStream = fs.createReadStream(filepath);
> 
> 
> 
>   const options = {
> 
>     method: "POST",
> 
>     headers: {
> 
>       "Content-Type": "multipart/form-data",
> 
>       "Content-Length": fs.statSync(filepath).size,
> 
>     },
> 
>   };
> 
> 
> 
>   const req = http.request(url, options, res => {
> 
>     res.on("data", chunk => {
> 
>       console.log(`BODY: ${chunk}`);
> 
>     });
> 
>     res.on("end", () => { });
> 
>   });
> 
> 
> 
>   req.on("error", e => {
> 
>     console.log("error", e);
> 
>   });
> 
> 
> 
>   fileStream.pipe(req);
> 
> }
> 
> 
> 
> const fileToUpload = "byteFile";
> 
> const uploadUrl = "http://httpbin.org/post";
> 
> 
> 
> uploadFile(fileToUpload, uploadUrl);
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> 3. View HTTP request messages.
> 
> 
> 
> I'm using `strace` here to view system calls instead of packet capturing, but the effect should be the same.
> 
> 
> 
> ```
> 
> strace -f -esendto -s1024 bun run a.js
> 
> ```
> 
> 
> 
> 
> 
> ![2023-07-02_22-55](https://github.com/oven-sh/bun/assets/9482395/45659e2f-2f22-4d3e-ad1f-cd3fa9f187b6)
> 
> 
> 
> `\200\201\202\203` corresponds to the octal values `\x80\x81\x82\x83`.
> 
> 
> 
> 
> 
> 
> 
> My Env
> 
> 
> 
> - bun 0.6.13 canary
> 
> - Linux 6.3.9-arch1-1
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Thank you for your time confirming this, and I am sorry that I missed a critical point to reproduce that the binary file should be long enough ( e.g. 1000 0x8f).

**Comment by Hanaasagi** [comment]
Thanks for your quick reply :)
It seems strange. I tested it locally several times and found that the uploaded data is correct.

![2023-07-02_23-28](https://github.com/oven-sh/bun/assets/9482395/a5382b1b-3127-4dca-8eeb-058b4aa16b62)


According to the code, it seems that the length of the uploaded data is unrelated. Initially, there should be a zero-length `#body` concatenated with the chunk during the first write operation.

```
  _write(chunk, encoding, callback) {
    var body = this.#body;
    if (!body) {
      this.#body = chunk;
      callback();
      return;
    }
    this.#body = body + chunk;
    callback();
  }

```

**Comment by wycers** [comment]
okay, I got my PC now... and I do some tests.
I can confirm that your code works well and does not reproduce this problem.
But my test code persists(I should post it before, sorry):
```
import axios from 'axios';
import FormData from "form-data";
import { readFileSync } from 'fs';

const form = new FormData();
form.append('files', readFileSync('./test_data'), {
  filename: 'test_file'
})

const res = await axios.post('http://httpbin.org/post', form, {
  headers: {
    ...form.getHeaders()
  }
})
```

**Comment by Hanaasagi** [comment]
Yes, this code snippet reproduces the problem. :+1: 

![2023-07-03_00-18](https://github.com/oven-sh/bun/assets/9482395/dad4b66d-f2e3-44c2-bb2e-8a57c695c42e)
