### ISSUE TITLE
`bun bun` on a non-existent entry point shows double error

### ISSUE THREAD

**Issue by Snazzah** [oven-sh/bun#312]
If you run `bun bun` on a file that doesn't exist, it loads the .env then does nothing until you stop it.

**Comment by Electroid** [comment]
It will now show an error, unfortunately it seems to be printed twice!
```
❯ bun bun hello.blah
error: ModuleNotFound resolving "hello.blah" (entry point)
error: ModuleNotFound resolving "hello.blah" (entry point)
```

**Comment by Electroid** [comment]
No longer an issue, but now related to: #2215
