### ISSUE TITLE
.env parser causes Bun fails to execute script in package.json

### ISSUE THREAD

**Issue by tghpereira** [oven-sh/bun#3121]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Create a simple project with typescript in bun.

Add an index.ts file with simple code
```ts
console.log("test")
```
Add a bun start script to package.json

```json
  "scripts": {
    "start": "bun run ./index.ts"
  },
```

### What is the expected behavior?

Should able to find the script and run the index.js file

### What do you see instead?

Bunjs constantly crashes in and out of test environments
The only error that is pointed out in the console is
```bash
tghpereira@DESKTOP-Q0N536G:~/blog$ bun run ./src/server/infra/http/app/index.ts
[0.06ms] ".env"
Segmentation fault
```
![image](https://github.com/oven-sh/bun/assets/86755966/63d965d1-fbe3-4751-a4cb-ee051ac7b713)

### Additional information

I checked the project's syntax and didn't find any code flaws in the project.
Versions 0.5.8 and 0.5.9 can run in a docker environment.
But cannot run from bun version 0.6.0

**Comment by Jarred-Sumner** [comment]
I believe this was a bug in our .env parser that was fixed in Bun v0.8.1

If you're still running into this, feel free to let us know
