### ISSUE TITLE
Make Jimp work on Bun

### ISSUE THREAD

**Issue by joaomendoncaa** [oven-sh/bun#3122]
### What is the problem this feature would solve?

**[Jimp](https://github.com/jimp-dev/jimp) is the biggest image processing/manipulation tool used in javascript runtimes.** 

Sadly, it's currently not working in bun. 

### What is the feature you are proposing to solve the problem?

So this is my vouch to investigate the issues and add support to [jimp](https://github.com/jimp-dev/jimp)!

In case there's anything I can provide to help bootstrap this initiative do let me know.

**Comment by FredMK1** [comment]
Hope this gets worked on soon. Would really make a big use of bun's performance when using jimp.

**Comment by rubenjfps** [comment]
Also interested in this. I have a CLI pipeline making heavy use of jimp that would highly benefit from bun's support.

**Comment by charnould** [comment]
Any progress on this?
Probably linked:

```
export const resize_image = async () => {
  await Jimp.read('__tests__/testing_purpose.jpg')
    .then((img) => {
      console.log(img)
      return img
        .resize(256, 256)
        .write('output.jpg')
    })
    .catch((err) => {
      console.error(err)
    })

    return
}
```
A file is written, but it seems corrupted...

**Comment by joaomendoncaa** [comment]
> A file is written, but it seems corrupted...

@charnould which bun + jimp version?

And can you specify what you mean by "corrupted"? How exacly does the output look like?

**Comment by charnould** [comment]
@joaomendoncaa 

I've made a simple public repo to reproduce the bug (?): https://github.com/charnould/bun-jimp-bug.git

1. fork/download the repo (running on `Bun` last version - 0.6.9 - with all deps updated)
2. run `bun install`
3. run `bun index.ts`
4. see that an `output.jpg` is created.
5. see that the file is "corrupted" and/or "empty"
6. it should return a readable resized .JPG image

**Note:** I'm a self-learning newbie. Maybe something is totally wrong in my code. Sorry for it.

**Comment by birkskyum** [comment]
@charnould the linked repository doesn't appear to exist.

**Comment by joaomendoncaa** [comment]
@charnould @birk Recent efforts to fix a few problems with es modules have resolved this issue. Unfortunately, I've lost track of the specific release/patch. 

Please [upgrade to latest](https://github.com/oven-sh/bun/releases/tag/bun-v0.8.1). I'll be closing this issue. If you encounter any further blockers, feel free to reopen.
