### ISSUE TITLE
Support for tracking CPU usage

### ISSUE THREAD

**Issue by lurajon** [oven-sh/bun#3127]
### What is the problem this feature would solve?

To monitor our applications we are using express-prom-bundle, and one of the built in metrics is the cpu-usage metric.

### What is the feature you are proposing to solve the problem?

By adding cpuUsage feature, the migration to bun becomes easier and it also allows extended monitoring of the application.

TypeError: process.cpuUsage is not a function. (In 'process.cpuUsage()', 'process.cpuUsage' is undefined)
      at /node_modules/prom-client/lib/metrics/processCpuTotal.js:14:20
      at collectDefaultMetrics (//node_modules/prom-client/lib/defaultMetrics.js:47:2)
      at /node_modules/express-prom-bundle/src/index.js:90:4
  

14 | 	let lastCpuUsage = process.cpuUsage();

**Comment by philkunz** [comment]
I second this.

**Comment by simylein** [comment]
As of bun version 0.7.1 `process.cpuUsage()` is now implemented and returns stuff like:

```
{
  user: 183126,
  system: 116134
}
```

If that works for you, can we close this as resolved?
