### ISSUE TITLE
Yargs still does not work with Bun.

### ISSUE THREAD

**Issue by ckhatton-transreport** [oven-sh/bun#3128]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. Create a new directory
2. `bun init`
3. `bun add yargs`
4. `bun add -d @types/yargs`
5. Use the [code from their example](http://yargs.js.org)
6. `bun run index.ts -- help`

### What is the expected behavior?

It should output help commands:

```
  pirate-parser <cmd> [args]

  Commands:
    pirate-parser hello [name]  welcome ter yargs!

  Options:
    --help  Show help    
```

### What do you see instead?

An error:

```shell
someappname on  main [!] via 🍞 v0.6.5 via  v20.2.0 
❯ bun run start --help
$ bun run index.ts --help
179 | 			} else if (groups.uri !== undefined) {
180 | 				escapeUrl = groups.uri.length === 0 ? undefined : groups.uri;
181 | 			}
182 | 		}
183 | 
184 | 		const code = ansiStyles.codes.get(Number(escapeCode));
                   ^
TypeError: undefined is not an object (evaluating 'ansiStyles.codes.get')
      at /Users/foo/bar/someappname/node_modules/wrap-ansi/index.js:184:15
      at /Users/foo/bar/someappname/node_modules/wrap-ansi/index.js:215:12
      at /Users/foo/bar/someappname/node_modules/wrap-ansi/index.js:210:8
      .
      .
      .
```

### Additional information

Another example:

```js
var argv = require('yargs/yargs')(process.argv.slice(2)).argv;

if (argv.ships > 3 && argv.distance < 53.5) {
    console.log('Plunder more riffiwobbles!');
} else {
    console.log('Retreat from the xupptumblers!');
}
```

Which works if you run `bun run index.ts --ships=5 --distance=30`, but if you run the help command `bun run index.ts --help` it breaks.

A previous issue: https://github.com/oven-sh/bun/issues/1370

:octocat:

**Comment by birkskyum** [comment]
In 0.8 I get the expected result with similar platform (Darwin 22.5.0 arm64 arm):

```sh
➜ bun --bun index.js -- help
pirate-parser <cmd> [args]

Commands:
  pirate-parser hello [name]  welcome ter yargs!

Options:
  --version  Show version number                                       [boolean]
  --help     Show help     
```

@ckhatton-transreport  can you try with latest bun?

**Comment by birkskyum** [comment]
can be closed
