### ISSUE TITLE
Bun exits before `await subprocess.exited` resolves

### ISSUE THREAD

**Issue by Kruithne** [oven-sh/bun#3137]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Linux 5.15.0-71-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
async function test() {
    const proc = Bun.spawn(['echo', 'cheese'], {
        cwd: process.cwd(),
        stdout: 'inherit',
        stderr: 'inherit'
    });

    await proc.exited;
    console.log(proc.exitCode);
}

test();
console.log('foo');
```

### What is the expected behavior?

```bash
> foo
> cheese
> 0
```

### What do you see instead?

```
> foo
> cheese
```

### Additional information

The code snippet demonstrates that if an async function is not awaited then it will not fully resolve if the main module finishes processing first. The intended behaviour can be achieved if the call to `test()` is prefixed with an `await` keyword, for demonstration.

```ts
async function test() {
    const proc = Bun.spawn(['echo', 'cheese'], {
        cwd: process.cwd(),
        stdout: 'inherit',
        stderr: 'inherit'
    });

    await proc.exited;
    console.log(proc.exitCode);
}

await test();
console.log('foo');
```

But to be working as intended, async functions that are not awaited should still fully resolve even after the main module is done processing.

I brought this issue up in the Discord and was asked to raise this as an issue.

**Comment by cendyne** [comment]
I have also hit this bug on Mac OS Ventura 13.4.

I am also seeing unexpected intermittent exiting when reading stdout from a process that quickly exits.

**Comment by vjpr** [comment]
Related: https://github.com/oven-sh/bun/issues/3083

**Comment by vjpr** [comment]
> I am also seeing unexpected intermittent exiting when reading stdout from a process that quickly exits.

Might be related: https://github.com/oven-sh/bun/issues/3083

**Comment by asilvas** [comment]
> > I am also seeing unexpected intermittent exiting when reading stdout from a process that quickly exits.
> 
> Might be related: #3083

No, any async code will exit process unless the await is on something that specifically holds the process open.

**Comment by jakebailey** [comment]
I was working on potentially testing `bun` in TypeScript's CI and hit this same problem; the task runner we use exits early once one of the promises has resolved even though there's other work pending that is still being awaited by someone:

```
$ bun run --bun hereby runtests --no-lint
Using ~/work/TypeScript/Herebyfile.mjs to run runtests
Starting lib
Starting generate-diagnostics
> /home/jabaile/.local/share/pnpm/global/5/.pnpm/bun@0.8.1/node_modules/bun/bin/bun scripts/processDiagnosticMessages.mjs src/compiler/diagnosticMessages.json
Reading diagnostics from src/compiler/diagnosticMessages.json
Finished lib in 37ms
```

Versus:

```
$ ./node_modules/.bin/hereby runtests --no-lint      
Using ~/work/TypeScript/Herebyfile.mjs to run runtests
Starting lib
Starting generate-diagnostics
> /home/jabaile/.fnm/node-versions/v20.5.1/installation/bin/node scripts/processDiagnosticMessages.mjs src/compiler/diagnosticMessages.json
Reading diagnostics from src/compiler/diagnosticMessages.json
Finished lib in 52ms
Finished generate-diagnostics in 62ms
Starting bundle-tests
Starting build-tests
Starting build-services
Finished bundle-tests in 358ms
^C (more stuff)
```

**Comment by janpio** [comment]
Prisma users are also hitting this problem: https://github.com/prisma/prisma/issues/21108

**Comment by jakebailey** [comment]
1.0.3 now seems to work for my above example in the TS repo. I was hoping to bisect this to figure out when this was fixed, but the debug version hangs in my example for other reasons...

**Comment by jakebailey** [comment]
Hm, but if I go back to 1.0.0, it also works again. Yeah, I have no idea :(

**Comment by kandros** [comment]
in `1.0.4` still present

**Comment by janpio** [comment]
Many more Prisma users are hitting this now: https://github.com/prisma/prisma/issues/21324

**Comment by timfee** [comment]
i lost a day to this! 😭

**Comment by ChandlerVS** [comment]
Still an issue in ``1.0.15``

**Comment by Royal-lobster** [comment]
> i lost a day to this! 😭

+1 to this 🤧

**Comment by Electroid** [comment]
As of Bun v1.0.26, this has been fixed. If you're still experiencing this issue, let us know and we'll re-open the issue.

```
❯ bun index.ts
foo
cheese
0
```

**Comment by Yadheedhya06** [comment]
still facing the same issue :((
v1.0.3

**Comment by Patrick-Ullrich** [comment]
@Yadheedhya06 have you tried using Bun v1.0.26 or later? This issue wouldn't have been fixed in v1.0.3

**Comment by reillyjodonnell** [comment]
Still facing the issue on 1.0.29

**Comment by funnisimo** [comment]
Still there in 1.0.30

**Comment by wanosoft** [comment]
Still facing this issue on `1.0.35`

**Comment by Jarred-Sumner** [comment]
The snippet at the top does not reproduce in v1.0.35

@wanosoft please open a new issue and provide a reproduction. 

This class of bug is specific to the APIs in use, so the general issue of "bun exits early" is unfortunately not actionable

**Comment by M-Subhan1** [comment]
script terminates before async main module is complete in `1.1.12`. This was working fine in an earlier version.

CONTEXT: Using a script to seed data using prisma. So might be related to what users have mentioned above.
