### ISSUE TITLE
Pub/Sub feature of Bun's ServerWebSocket implementation doesn't work

### ISSUE THREAD

**Issue by vesamet** [oven-sh/bun#3146]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64

### What steps can reproduce the bug?

1) Either run the pub/sub demo in the docs as is ( see https://bun.sh/docs/api/websockets#pub-sub )

```

Bun.serve<{username: string}>({
  fetch(req, server) {
    if (req.url === '/chat') {
      const cookies = getCookieFromRequest(req);
      const success = server.upgrade(req, {
        data: {username: cookies.username},
      });
      return success
        ? undefined
        : new Response('WebSocket upgrade error', {status: 400});
    }

    return new Response('Hello world');
  },
  websocket: {
    open(ws) {
      ws.subscribe('the-group-chat');
      ws.publish('the-group-chat', `${ws.data.username} has entered the chat`);
    },
    message(ws, message) {
      // this is a group chat
      // so the server re-broadcasts incoming message to everyone
      ws.publish('the-group-chat', `${ws.data.username}: ${message}`);
    },
    close(ws) {
      ws.unsubscribe('the-group-chat');
      ws.publish('the-group-chat', `${ws.data.username} has left the chat`);
    },
});

```

2) Or run this simplified version of the demo for testing purposes.

```

Bun.serve({
  fetch(req, server) {
    if (
      server.upgrade(req, {
        data: { username: "mike" },
      })
    ) {
      return;
    }
    return new Response("Upgrade failed :(", { status: 500 });
  },
  websocket: {
    open(ws) {
      ws.subscribe("the-group-chat");
      ws.publish("the-group-chat", `${ws.data.username} has entered the chat`);
    },
    message(ws, message) {
      // this is a group chat
      // so the server re-broadcasts incoming message to everyone
      ws.publish("the-group-chat", `${ws.data.username}: ${message}`);
    },
    close(ws) {
      ws.unsubscribe("the-group-chat");
      ws.publish("the-group-chat", `${ws.data.username} has left the chat`);
    },
  },
});


``` 

### What is the expected behavior?

The server should publish back any messages we send, as we are subscribed to `'the-group-chat'`.

### What do you see instead?

The server doesn't echo any message sent to `'the-group-chat'`.

### Additional information

I tried many ways to get `ws.publish` to work, to no avail.

(Also , i've observed that they are no tests for ws.subscribe() and ws.publish() in `test/js/web/websocket/websocket.test.js`, but the other methods do. )

**Comment by Jarred-Sumner** [comment]
We have tests for pub/sub, pub/sub does work. 

The example is probably out of date after publushToSelf was changed to default to false.

**Comment by vesamet** [comment]
Oh, I see. 
Pardon me. I'll find the tests and see how its works :)

**Comment by vesamet** [comment]
So from the chat-server (`bun/bench/websocket-server/chat-server.bun.js`) used for benchmarks, I see that `ws.publishText()` is used instead. Yet I can't manage to make it work.

If someone has a working example, I would be happy to see it :)

**Comment by vesamet** [comment]
@Jarred-Sumner You where right. I simply needed to add `publishToSelf: true,` , even tho I have no clue what I does :P

Thank you for your help and your time. I'll close this issue

**Comment by ocodista** [comment]
@Jarred-Sumner Is it possible to include an example for individual publishes? Instead of group chats.
