### ISSUE TITLE
dynamic required not working 

### ISSUE THREAD

**Issue by FaizanAqeek** [oven-sh/bun#3148]
### What version of Bun is running?

0.6.5

### What platform is your computer?

windows subsystem 

### What steps can reproduce the bug?

I just run bun start it give me an error like this 

![image](https://github.com/oven-sh/bun/assets/11156849/8f53b0bc-bf68-4f1f-a246-cdd3b9b4f28f)

### What is the expected behavior?

it should be easily run as usual.

**Comment by Electroid** [comment]
Duplicate of #299

**Comment by Electroid** [comment]
This should now be fixed, let us know if you're still experiencing this issue.
