### ISSUE TITLE
Cannot locate svg file?

### ISSUE THREAD

**Issue by rarenatoe** [oven-sh/bun#315]
## The problem

Excuse me if it's a silly mistake, but I cannot seem to solve this issue.
<img width="717" alt="Screen Shot 2022-07-06 at 19 55 25" src="https://user-images.githubusercontent.com/44821537/177666947-910fd4b6-95bb-4159-88f7-aee7a077306d.png">

## How to reproduce:

- `bun create react test`
- `cd test`
- change `App.js` to `App.tsx`.

## Questions:
- Do we maybe need an svg loader?
- I tried adding this:
```json
// tsconfig.json
{
    "compilerOptions": {
      "moduleResolution": "node",
      "jsx": "react"
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules"]
}
```

**Comment by Jarred-Sumner** [comment]
I think this is an issue where TypeScript isn't configured to understand svg files

So it's not exactly a bun issue, but because it's the `bun create react` template, it needs to be fixed in the template so that you (and others) don't experience this

**Comment by FinnRG** [comment]
@rarenatoe You can resolve this issue by creating a ```images.d.ts``` file in the src directory with the following content:
```
declare module '*.svg' {
  const content: any;
  export default content;
}
```
@Jarred-Sumner Should I create a PR with this fix?
