### ISSUE TITLE
Lokalise Node API does not connect successfully

### ISSUE THREAD

**Issue by ckhatton-transreport** [oven-sh/bun#3153]
### What version of Bun is running?

0.6.5

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. Create a new directory
2. `bun init`
3. `bun add @lokalise/node-api`
4. Add this code with an API key to `index.ts`:
```js
import { LokaliseApi } from "@lokalise/node-api";
const lokaliseApi = new LokaliseApi({ apiKey: '<apiKey>'});
```
5. `bun run index.ts`

### What is the expected behavior?

It connects successfully.

### What do you see instead?

```shell
pa-global-loci on  main [!] via 🍞 v0.6.5 via  v20.2.0 
❯ bun run start
$ bun run index.ts
 7 | const ClientRequest = require('./client-request.js');
 8 | const IncomingMessage = require('./incoming-message.js');
 9 | const auto = require('./auto.js');
10 | const {
11 | 	HttpOverHttp2,
12 | 	HttpsOverHttp2
    ^
TypeError: undefined is not an object (evaluating 'new tls.TLSSocket(new stream.PassThrough)._handle._parentWrap') while parsing module "/Users/foo/bar/someappname/node_modules/http2-wrapper/source/utils/js-stream-socket.js" while parsing module "/Users/foo/bar/someappname/node_modules/http2-wrapper/source/proxies/h1-over-h2.js"
      at /Users/foo/bar/someappname/node_modules/http2-wrapper/source/index.js:12:1
      at (eval) (/Users/foo/bar/someappname/node_modules/http2-wrapper/source/index.js:50:0)
error: script "start" exited with code 1 (SIGHUP)
```

### Additional information

Creating an account on Lokalise is easy and free. You will have a API key ready in no time.

https://lokalise.com

:octocat:

**Comment by Electroid** [comment]
Thanks for reporting, we'll take a look. Seems like the same issue in #3150

**Comment by Electroid** [comment]
Are you still running into this issue?

**Comment by nektro** [comment]
This looks to have been fixed some time ago. if you are still running into this please let us know.
