### ISSUE TITLE
Package ESLint 8.41.0 does not work with Bun 

### ISSUE THREAD

**Issue by lyudmil-mitev** [oven-sh/bun#3154]
### What version of Bun is running?

0.6.6

### What platform is your computer?

Linux 6.1.0-9-amd64 x86_64 Debian 12

### What steps can reproduce the bug?

```
$ bun install eslint
$ bunx eslint
```

### What is the expected behavior?

eslint should work

### What do you see instead?

eslint crashes with a stack trace

```
Oops! Something went wrong! :(

ESLint: 8.41.0

unlinkSync@[native code]
unlinkSync@[native code]
executeOnFiles@/node_modules/eslint/lib/cli-engine/cli-engine.js:296:24
@/node_modules/eslint/lib/eslint/eslint.js:223:76
asyncFunctionResume@[native code]
lintFiles@/node_modules/eslint/lib/eslint/eslint.js:219:25
@/node_modules/eslint/lib/cli.js:197:41
asyncFunctionResume@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

### Additional information

I have tested with Bun 0.6.5 and 0.6.6

**Comment by Electroid** [comment]
Thanks for reporting, we'll take a look.

**Comment by ghoullier** [comment]
I face the problem with `bun --bun eslint --ext .ts src`

I have tested bun 0.7.0

[Repository](https://github.com/ghoullier/fp-nutshell)

```console
$ eslint --ext .ts src

Oops! Something went wrong! :(

ESLint: 8.45.0

EPERM: Operation not permitted
    at unlinkSync (native)
    at executeOnFiles (/workspaces/fp-nutshell/node_modules/eslint/lib/cli-engine/cli-engine.js:785:14)
    at <anonymous> (/workspaces/fp-nutshell/node_modules/eslint/lib/eslint/eslint.js:551:8)
    at lintFiles (/workspaces/fp-nutshell/node_modules/eslint/lib/eslint/eslint.js:543:13)
    at <anonymous> (/workspaces/fp-nutshell/node_modules/eslint/lib/cli.js:393:20)
```

**Comment by dLedda** [comment]
Still present in 0.7.3

I am slowly moving towards using bun for more of my local setups for work. Vite (no SSR), vue-tsc and would love to extend that to eslint. Cuts down several minutes of idle CPU time per day.

**Comment by birkskyum** [comment]
I get this:

```sh
➜ bun --bun eslint --ext .ts src

Oops! Something went wrong! :(

ESLint: 8.48.0

TypeError: Cannot read config file: /Users/admin/repos/bun-parent-module-test/.eslintrc.js
Error: stacks.shift is not a function. (In 'stacks.shift()', 'stacks.shift' is undefined)
    at <anonymous> (/Users/admin/repos/bun-parent-module-test/node_modules/import-fresh/node_modules/parent-module/index.js:15:12)
```

Blocked by
- #4324

**Comment by Jarred-Sumner** [comment]
its clear that we need to fix an issue with Error.captureStackTrace

**Comment by NikhilVerma** [comment]
I patched around it but ran into the issue where `module.parent` API (which was deprecated BTW) is not supported in bun.

https://github.com/microsoft/rushstack/blob/main/eslint/eslint-patch/src/modern-module-resolution.ts#L159

**Comment by Foorack** [comment]
@birkskyum  Somebody recommended me to rewrite `.eslintrc.cjs` into the new flat-file format, to avoid this error.

After this I first got:

```ruby
$ bunx eslint

Oops! Something went wrong! :(

ESLint: 8.49.0

{}
```

Modifying the `eslint/bin/eslint.js` to add a `console.error(error);` inside the `onFatalError` function revealed:

```ruby
error: Cannot find package "@typescript-eslint" from "PROJECT_PATH/eslint.config.js?mtime=1695053312661"
```

This revealed the error was caused by myself during migration. Fixing the import now makes eslint run successfully in Bun.

**Comment by JonasRothmann** [comment]
For anyone getting this i changed `eslint/bin/eslint.js` as mentioned before to log the error and got the followin: `error: Cannot find package 'typescript-eslint' from '[...]/app/eslint.config.js'`. To fix it I ran `bun add -D typescript-eslint`.
