### ISSUE TITLE
Add `--exact` flag to `bun install`

### ISSUE THREAD

**Issue by fdaciuk** [oven-sh/bun#3157]
### What is the problem this feature would solve?

Install the exact latest version of a package, just like yarn and npm already does, without the `^` sign in `package.json`.

### What is the feature you are proposing to solve the problem?

Add `--exact` flag to `bun install` command

### What alternatives have you considered?

Today the only way to do this is installing the package using `package@version`, but we have to know what is the latest version at the time we're using the `bun install` command.

**Comment by MarkLyck** [comment]
Yes please, it's a little annoying having to do `bun add x`, then go to the package.json, remove the ^, and run `bun i` every time to get an exact version.

**Comment by Electroid** [comment]
This was implemented in https://github.com/oven-sh/bun/pull/3409
