### ISSUE TITLE
Support test coverage reporters in `bun test`

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/bun#3158]
### What is the problem this feature would solve?

Existing test libraries like Jest and Vitest support coverage reporters like istanbul and c8. `bun test` merely runs the tests, but it does not collect coverage information that could be provided to a reporter.

### What is the feature you are proposing to solve the problem?

Add the ability to specify a reporter (possibly include a default reporter with Bun) and collect coverage information with a `--coverage` flag or something similar.

### What alternatives have you considered?

The only alternative is to stick with Jest/Vitest/etc when coverage reporting is needed.

**Comment by TiBianMod** [comment]
+1

**Comment by Jarred-Sumner** [comment]
Bun v0.7.3 now includes a default code coverage reporter.

To use it:
```bash
bun test --coverage
```

It will output something like:

```ts
-------------|---------|---------|-------------------
File         | % Funcs | % Lines | Uncovered Line #s
-------------|---------|---------|-------------------
All files    |   38.89 |   42.11 |
 index-0.ts  |   33.33 |   36.84 | 10-15,19-24
 index-1.ts  |   33.33 |   36.84 | 10-15,19-24
 index-10.ts |   33.33 |   36.84 | 10-15,19-24
 index-2.ts  |   33.33 |   36.84 | 10-15,19-24
 index-3.ts  |   33.33 |   36.84 | 10-15,19-24
 index-4.ts  |   33.33 |   36.84 | 10-15,19-24
 index-5.ts  |   33.33 |   36.84 | 10-15,19-24
 index-6.ts  |   33.33 |   36.84 | 10-15,19-24
 index-7.ts  |   33.33 |   36.84 | 10-15,19-24
 index-8.ts  |   33.33 |   36.84 | 10-15,19-24
 index-9.ts  |   33.33 |   36.84 | 10-15,19-24
 index.ts    |  100.00 |  100.00 |
-------------|---------|---------|-------------------
```

**Comment by ImLunaHey** [comment]
@Jarred-Sumner is there an issue we can follow for support for html, json, etc. reporters for that?

**Comment by Jarred-Sumner** [comment]
@ImLunaHey there is an issue for lcov #4015 which could be used to generate an HTML reporter. But feel free to file one for HTML specifically

**Comment by idfunctor** [comment]
@Jarred-Sumner 
Most production projects rely on more advanced coverage reporting. Using instanbul, c8, etc which has line, function, branch and statements reported. Pipelines involving SonarQube etc currently rely on that sort of coverage.
Do you think it might be on Bun roadmap to have compatibility with Istanbul? Or can we assume that we get in-built reporters and have to modify how we measure coverage in CI?

Asking not to be annoying but to inform stakeholders of the changes required to switch to Bun.

**Comment by ctsstc** [comment]
Uncovered Lines is nice to figure things out, but other things like logical branching is not explicitly visible in this report. Sure your `% Funcs` or `%Lines` may be down, but there's not much to go off of regarding this. I know Jest doesn't expose this in the CLI much either, but I normally end up opening up an HTML report for this kind of visibility.

## Example

Note the: `src/utilities/files.ts` with no uncovered line numbers, but funcs and lines are not fully covered. This does not make it easy to determine what still needs additional coverage, which I assume the line is tested, but a logical branch within that line is likely not tested.

<img width="597" alt="image" src="https://github.com/oven-sh/bun/assets/416814/8e19c7be-b68d-4919-b0e4-f3ed610851aa">

**Comment by pukingrainbows** [comment]
(noobie question) Meanwhile we wait for properly report support, I was trying to to consume outup from the cli after running `test --coverage` but for some reason running

```js
	const proc = Bun.spawn(["bun", "test"], { stdout: "pipe" });
	const output = await new Response(proc.stdout).text();
```

output it is empty, does anyone know how can I get the coverage output text?

ps. I have configured that --coverage it is always enable

**Comment by jakeboone02** [comment]
@pukingrainbows try `stderr` instead of `stdout`

**Comment by pukingrainbows** [comment]
> @pukingrainbows try `stderr` instead of `stdout`

ohhh that worked, why was that? shouldn't be part of `stdout`?

**Comment by jakeboone02** [comment]
> ohhh that worked, why was that? shouldn't be part of `stdout`?

I'm not really sure. I only know because of this comment from Jarred on one of my PRs: https://github.com/oven-sh/bun/pull/2566#pullrequestreview-1373771216.
