### ISSUE TITLE
Segmentation fault at both --hot and --watch modes running expressjs server with ES modules

### ISSUE THREAD

**Issue by sukalov** [oven-sh/bun#3161]
### What version of Bun is running?

0.6.6

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

I have a simple node express server running phonebook with minimal API, which can be found at [this repo](https://github.com/sukalov/phonebook_copy). I've been using it to play around with got stuck with this segfault error. I tried 4 scripts:
  1. `bun --hot index.js`
  2. `bun run --hot index.js`
  3. `bun --watch index.js`
  4. `bun run --watch index.js` 

They all returned the same, and upgrading bun to canary didn't solve the issue overall, but it did run in --hot mode ONCE (soon it crushed segfault too).

However, when I tried it with [another simple express server](https://github.com/sukalov/node-countries), that uses CommonJS modules instead of ES modules, both worked fine.
 
  

### What is the expected behavior?

``` bash
# at app using CJS modules
bun run --hot index.js  # saving several times
Example app listening on port 3000
Example app listening on port 3000
Example app listening on port 3000
Example app listening on port 3000
Example app listening on port 3000
Example app listening on port 3000
```

### What do you see instead?

``` bash
# at app using ES modules
bun run --hot index.js  
[0.16ms] ".env"
connecting to mongodb+srv://<................>
connected to MongoDB
[1]    3391 segmentation fault  bun run --hot index.js
```

**Comment by Jarred-Sumner** [comment]
Looked at it a little, something to do with Mongoose + node:net, I think. Likely some arguments parsing which is incorrect

**Comment by sukalov** [comment]
> Looked at it a little, something to do with Mongoose + node:net, I think. Likely some arguments parsing which is incorrect

oh, interesting. i didn't think it might be mongoose. I can implement mongoose to the second repo to check, how it behaves with commonjs modules, if you wish
