### ISSUE TITLE
`fsPromises.open` should return instance of `FileHandle`

### ISSUE THREAD

**Issue by muzuiget** [oven-sh/bun#3167]
Here is a reproduce code:

```javascript
// index.js
import {open} from 'node:fs/promises';

const file = await open('package.json', 'r');
const stat = await file.stat();
console.log(stat.size);
```

```bash
$ node --version
v20.2.0
$ node index.js 
332
```

```bash
$ bun --version
0.6.6
$ bun index.js 
1 | import {open} from 'node:fs/promises';
2 | 
3 | const file = await open('package.json', 'r');
4 | const stat = await file.stat();
                       ^
TypeError: file.stat is not a function. (In 'file.stat()', 'file.stat' is undefined)
      at /home/muzuiget/test/index.js:4:19
```

NodeJS document [filehandle.stat()](https://nodejs.org/api/fs.html#filehandlestatoptions).

**Comment by gormster** [comment]
It's even worse than you think - try adding `console.log("file handle is a ", typeof file);`

```
file handle is a number
```

Yep - the FileHandle class is not a thing. `FsPromises.open` straight up returns the raw *file descriptor*.

**Comment by Jarred-Sumner** [comment]
Yes, FileHandle is not implemented yet.

**Comment by gormster** [comment]
be great if that were mentioned in the [NodeJS compatibility page](https://bun.sh/docs/runtime/nodejs-apis).

**Comment by AlttiRi** [comment]
Maybe it makes sense to _partially_ implement `FileHandle`, at least as a simple object `{fd: number}`? For compatibility with Node.js code. In order to not break the already written code in future.

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/8141
