### ISSUE TITLE
Bun bundler typo checker

### ISSUE THREAD

**Issue by LowByteFox** [oven-sh/bun#3171]
### What is the problem this feature would solve?

Currently, when you run bun build or Bun.build and bundle files, it will bundle them, but it won't tell you where is the issue. Then get to the browser and realise something is wrong and until you realise what you did wrong, it s going to take time.

### What is the feature you are proposing to solve the problem?

To add some basic check for typos in the code so when the bundler runs, it will notify the user somewhere is a mistake so they could fix it right away, just like typescript warns with incorrect types.

**Comment by Electroid** [comment]
This is something we are unlikely to implement.
