### ISSUE TITLE
when bun fully available for windows

### ISSUE THREAD

**Issue by umararshad4** [oven-sh/bun#318]

**Comment by MagiqueDeveloper** [comment]
Bun is sort of fully available for Windows. If you mean like installing with an installer without WSL, I think I saw Jarred say a few hours ago that it is planned. I may be wrong though.

**Comment by flawnn** [comment]
I can't use bun with WSL on NTFS. This is a real bummer
![image](https://user-images.githubusercontent.com/19386703/177722645-9a892e80-b2d4-4673-b985-6f61aba1f272.png)

**Comment by MagiqueDeveloper** [comment]
> I can't use bun with WSL on NTFS. This is a real bummer ![image](https://user-images.githubusercontent.com/19386703/177722645-9a892e80-b2d4-4673-b985-6f61aba1f272.png)

To fix this, run `bun install [PACKAGE(S)] --backend=copyfile` in your WSL terminal.

**Comment by rollingmoai** [comment]
Duplicate of #43, #153. Please don't create multiple issues of the same thing.
