### ISSUE TITLE
error: Could not resolve: "react"

### ISSUE THREAD

**Issue by michellbrito** [oven-sh/bun#319]
I'm trying to run the code that is inside bun's `bun-landing` folder and I do `bun install` -> `bun ssr.tsx` but it still complains that react is missing

<img width="682" alt="Screen Shot 2022-07-06 at 10 19 50 PM" src="https://user-images.githubusercontent.com/32559031/177676126-925e6dfb-10e4-4a07-ad0a-db20ba3658cc.png">

**Comment by Jarred-Sumner** [comment]
This is happening because `ssr.tsx` is using the build of react-dom in `test/bun.js` since it isn't on npm yet

To fix this, try running `bun install` inside `bun/test/bun.js`
