### ISSUE TITLE
bunx ate my logs

### ISSUE THREAD

**Issue by ImLunaHey** [oven-sh/bun#3193]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

1. Create a file called `main.ts` with some basic js/ts in it.
2. Add a `package.json` with a script called `build` that does `npx tsup ./main.ts`
3. Run `bun run build`

### What is the expected behavior?

```bash
➜  ticket-genie git:(main) ✗ npm run build

> ticket-genie@0.0.0-development build
> npx tsup ./src/main.ts --treeshake --minify

CLI Building entry: ./src/main.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Target: es2020
CJS Build start
Use of eval in "dist/main.cjs" is strongly discouraged as it poses security risks and may cause issues with minification.
CJS dist/main.cjs 1.60 MB
CJS ⚡️ Build success in 4286ms
```

### What do you see instead?

```bash
➜  ticket-genie git:(main) ✗ bun run build
$ bun x tsup ./src/main.ts --treeshake --minify
[0.05ms] ".env"
Use of eval in "dist/main.cjs" is strongly discouraged as it poses security risks and may cause issues with minification.
```

**Comment by RiskyMH** [comment]
@ImLunaHey We've invested a ton of time into making Bun more reliable over the last year. I'm having a really hard time reproducing this. If you're still running into this issue, please let me know and I'll re-open this
