### ISSUE TITLE
Benchmarks reference non-existent CPU

### ISSUE THREAD

**Issue by isaac-mcfadyen** [oven-sh/bun#320]
In two of the Bun benchmarks, it is referenced that they were run on "M1X".

This is not possible, there is no such thing as the M1X chip. There are:
- the M1 Pro
- the M1 Max

These should likely be clarified with the real processor name, especially as these the Max has double the memory bandwidth as the Pro and so would perform drastically different.

**Comment by Jarred-Sumner** [comment]
I mis-remembered the name of my CPU because the 'M1X' was the leaked name before the release

<img width="251" alt="image" src="https://user-images.githubusercontent.com/709451/177679609-06c7386d-88e9-4dc2-ab91-66386b27e763.png">

**Comment by isaac-mcfadyen** [comment]
Ah, no problem! Just thought I'd point it out 🙂
