### ISSUE TITLE
[bun] Warning: ws.WebSocket.ping() is not implemented in bun

### ISSUE THREAD

**Issue by ImLunaHey** [oven-sh/bun#3202]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import CertStreamClient from 'certstream';

let client = new CertStreamClient(function(message){
    console.log("Received -> ", message.data.leaf_cert.issuer.O, message.data.leaf_cert.subject.CN);
});

client.connect();

// The `ws.ping` here causes the error
setInterval(() => client.ws.ping(), 30000);

client.ws.on('terminate',  (...args: unknown[]) => console.log('terminate', ...args));
client.ws.on('close',  (...args: unknown[]) => console.log('close', ...args));
client.ws.on('error', (...args: unknown[]) => console.log('error', ...args) );
```

### What is the expected behavior?

The `ping()` method to work.

### What do you see instead?

```
[bun] Warning: ws.WebSocket.ping() is not implemented in bun
```

**Comment by Ekott2006** [comment]
Can I try this issue?

**Comment by PaddeK** [comment]
I would like to connect to EV charger via websocket which requires proper ping/pong handling. Is there a timetable/roadmap when this is available?

**Comment by tobowers** [comment]
seems like this hasn't made it into a release yet?

**Comment by Electroid** [comment]
> seems like this hasn't made it into a release yet?

This was implemented a long time ago, are you seeing an error?

**Comment by tobowers** [comment]
> This was implemented a long time ago, are you seeing an error?

This doesn't work: https://github.com/oven-sh/bun/blob/main/test/js/web/websocket/websocket-server-echo.mjs

Turns out it's from using "ws" which does not expose "ping" - the above looks like it should be testing it, but it doesn't work.

**Comment by fabiendeborde** [comment]
I can confirm that using `ws.ping()` and `ws.pong()`, does not work.
(I am not sure if I am using it right, but when I receive a ping message, and respond to it with `ws.ping()` nothing is happening)
