### ISSUE TITLE
[Issue] inquirer.js show no output

### ISSUE THREAD

**Issue by gtrabanco** [oven-sh/bun#3205]
### What version of Bun is running?

0.6.8 

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

1. `bun add @inquirer/prompts` into your project.
2. Use any example of Inquirer.js README project: https://github.com/SBoudrias/Inquirer.js

### What is the expected behavior?

I tried select example with node. This is what is showed when execute:
![Captura de pantalla 2023-06-04 a las 13 48 33](https://github.com/oven-sh/bun/assets/1969593/0b9a3ac5-6b47-4a1c-a5ec-183fee13fa62)

This is after select a value and keypress enter.
![Captura de pantalla 2023-06-04 a las 13 48 46](https://github.com/oven-sh/bun/assets/1969593/61525a18-3182-4567-a0af-0236c93e304e)

### What do you see instead?

This is when the script is executed:
![Captura de pantalla 2023-06-04 a las 13 49 00](https://github.com/oven-sh/bun/assets/1969593/8ba12d79-1e85-4251-b0c8-fa8a1e982bfc)

This is after pressing enter without using arrows:
![Captura de pantalla 2023-06-04 a las 13 49 08](https://github.com/oven-sh/bun/assets/1969593/75d97d27-8aa6-4c4f-9d0a-46d4d2fae7fc)

I have to press enter again to finish the program:
![Captura de pantalla 2023-06-04 a las 13 49 16](https://github.com/oven-sh/bun/assets/1969593/2a20f03e-3dc9-4165-b53a-80329074cfe2)

If I executed and play a little bit with the arrows I receive an error after press enter key and after press enter again I receive the first value:
![Captura de pantalla 2023-06-04 a las 13 54 01](https://github.com/oven-sh/bun/assets/1969593/c2aea779-b17b-4e71-9fb1-6af429e46785)

No other errors were received. I also tried input with similar results.

### Additional information

The used sample code:

```ts
import select, { Separator } from '@inquirer/select';

const answer = await select({
  message: 'Select a package manager',
  choices: [
    {
      name: 'npm',
      value: 'npm',
      description: 'npm is the most popular package manager',
    },
    {
      name: 'yarn',
      value: 'yarn',
      description: 'yarn is an awesome package manager',
    },
    new Separator(),
    {
      name: 'jspm',
      value: 'jspm',
      disabled: true,
    },
    {
      name: 'pnpm',
      value: 'pnpm',
      disabled: '(pnpm is not available)',
    },
  ],
});

console.log(answer);
```

I think this is could be related to not supported stdin raw mode and also any other errors probably with chalk or ansi codes but I am not sure and there are some knowledge I don't have to provide more details about this error.

**Comment by jasperdunn** [comment]
I have this issue too.

Using bun to run their demo works 🤔 
`bunx @inquirer/demo@latest`

I guess it's to do with Node.js readline not being supported by bun. Looks like it's done differently.

For now I'm just using the built-in: `prompt`
It would be nice to have select support.

**Comment by gtrabanco** [comment]
> I have this issue too.
> 
> Using bun to run their demo works 🤔 `bunx @inquirer/demo@latest`
> 
> I guess it's to do with Node.js readline not being supported by bun. Looks like it's done differently.
> 
> For now I'm just using the built-in: `prompt` It would be nice to have select support.

Not sure but probably is using node to execute the demo while using bunx and that's why it is working?

- Related to #3361

**Comment by v3nntrnx** [comment]
> I have this issue too.
> 
> Using bun to run their demo works thinking `bunx @inquirer/demo@latest`
> 
> I guess it's to do with Node.js readline not being supported by bun. Looks like it's done differently.
> 
> For now I'm just using the built-in: `prompt` It would be nice to have select support.

It does work, but not if you try to "bunx --bun @inquirer/demo@latest"

**Comment by gtrabanco** [comment]
With today's current Canary it shows no output and when you press Ctrl+C shows this error:

```bash
187 |             let shouldHandleExit = true;
188 |             const onForceExit = () => {
189 |                 if (shouldHandleExit) {
190 |                     shouldHandleExit = false;
191 |                     onExit();
192 |                     reject(new Error('User force closed the prompt with CTRL+C'));
                              ^
error: User force closed the prompt with CTRL+C
      at onForceExit (/private/tmp/@inquirer/demo@latest--bunx/node_modules/@inquirer/core/dist/esm/index.mjs:192:27)
```

My Canary Build is: https://github.com/oven-sh/bun/compare/18a2e18ae1959d0198e8262cbc5bc8a1760981fe...main

**Comment by birkskyum** [comment]
Tested with bun 0.8.1, and `bun --bun x @inquirer/demo@latest` is working now. This can be closed.
