### ISSUE TITLE
Uncaught TypeError: isBuffer3.default is not a function

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#3206]
### What version of Bun is running?

0.6.8

### What platform is your computer?

ubuntu

### What steps can reproduce the bug?

- [clone this PR](https://github.com/noahehall/react-idealer-image/pull/8)

```sh

bun install
bun run cosmos

open browser to localhost:5000
```

### What is the expected behavior?

component development framework that uses bun as the bundler

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/10324554/93fa16a2-82e4-409a-8c64-01a29f4f6962)

### Additional information

taking a look at the technical landscape, IMO react-cosmos is the most `bunnish` framework to use as it doesnt require legacy proptypes nor webpack/etc

**Comment by Jarred-Sumner** [comment]
@dylan-conway @paperdave  we should probably add a third-party test for lodash-es specifically, this function has broken like 3 times

**Comment by noahehall** [comment]
testing this out now

**Comment by noahehall** [comment]
confirmed! you guys are awesome

![image](https://github.com/oven-sh/bun/assets/10324554/ca9e3d11-f60d-4691-9eaf-aa501dcce334)
