### ISSUE TITLE
Support new ECMAScript RegExp `v` flag

### ISSUE THREAD

**Issue by en0ent1ty** [oven-sh/bun#3212]
Ref: https://github.com/tc39/proposal-regexp-v-flag

JavaScriptCore has already implemented the new flag on runtime:
- https://github.com/WebKit/WebKit/pull/10984

I have verified Bun's current WebKit version used already contains the linked PR commit.

However Bun itself currently doesn't support the flag at parsing level on regex literals such as `/foo/v` (but can be "tricked" to accept it with all forms of string code/regex generation, `eval`, `Function`, `new RegExp(..., 'v')`, etc and it will run fine at runtime as predicted)

**Comment by Jarred-Sumner** [comment]
Ah yeah this should be a one line fix in js_lexer.zig

**Comment by davidchambers** [comment]
`/x/v` does not work in the REPL in v1.0.9: “Unknown regular expression flags”. `RegExp('x', 'v')` works, though.
