### ISSUE TITLE
Runtime Directory Caching Issue (breaks vite config files)

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#3216]
### What steps can reproduce the bug?

```ts
const file = `${import.meta.dir}/temp.mjs`;

import { existsSync, unlinkSync, writeFileSync } from "fs";

if (existsSync(file)) {
  console.log("temp.mjs cannot exist before running this script");
  unlinkSync(file);
  process.exit(0);
}

writeFileSync(file, "export default 1;");

try {
  const module = await import(file);
  console.log(module.default);
} finally {
  unlinkSync(file);
}
```

### Additional information

Vite blocker

**Comment by paperclover** [comment]
gonna paste this text to make this issue more searchable, this is bug causing vite with config files to crash on startup
```
$ vite dev
failed to load config from vite.config.js
error when starting dev server:
```

**Comment by paperclover** [comment]
the fix doesnt strictly fix this bug, but it does fix the case if you're using a query string in the import path, like `test.mjs?hello`

**Comment by paperclover** [comment]
tbh

i want to fix this for all cases. the file strictly exists and `import()` should be able to catch it

**Comment by AlbertMarashi** [comment]
Related

https://github.com/vitejs/vite/discussions/17851
