### ISSUE TITLE
setTimeout with delay 0 results in 1 second delay in some cases

### ISSUE THREAD

**Issue by anttikissa** [oven-sh/bun#3226]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.5.0 x86_64 i386 (M2 Mac running Rosetta)

### What steps can reproduce the bug?

The following code spends 1 second in setTimeout instead of executing the function immediately:

```
// test1.js
function log(...args) {
	console.log(new Date().toISOString(), ...args)
}

log('start')
setTimeout(() => log('end'), 0)

export default {
	fetch: () => new Response('ok')
}
```

### What is the expected behavior?

setTimeout(f, 0) to execute immediately

### What do you see instead?

There's a 1 second delay between start and end:

```
% bun test1.js
2023-06-06T19:51:29.572Z start
2023-06-06T19:51:30.575Z end
```

### Additional information

The function does run almost immediately if I use delay of 1 instead of 0, or if I omit the `export default` part:

```
// test2.js
function log(...args) {
	console.log(new Date().toISOString(), ...args)
}

log('start')
setTimeout(() => log('end'), 1)

export default {
	fetch: () => new Response('ok')
}
```

```
// test3.js
function log(...args) {
	console.log(new Date().toISOString(), ...args)
}

log('start')
setTimeout(() => log('end'), 0)

//export default {
//	fetch: () => new Response('ok')
//}
```

```
% bun test2.js
2023-06-06T19:51:37.032Z start
2023-06-06T19:51:37.035Z end
^C
% bun test3.js
2023-06-06T19:51:41.144Z start
2023-06-06T19:51:41.146Z end
```

Might have something to do with issue https://github.com/oven-sh/bun/issues/2410

**Comment by Jarred-Sumner** [comment]
setTimeout isn't precise and will soon have a minimum delay of 1ms, matching other runtimes
