### ISSUE TITLE
Cannot connect to postgres instance using tls

### ISSUE THREAD

**Issue by add1ed** [oven-sh/bun#3236]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```
import postgres from "postgres";

const sql = postgres("postgres://user:pass@localhost:5432/test?sslmode=require");
const [{ version }] = await sql`SELECT version()`;

console.log(version); // "PostgreSQL 14.2 ..."
```
where the argument is a valid connection string for a postgres db that can only be connected to using ssl.

### What is the expected behavior?

A secure connection is created and the `SELECT version()` query returns successfully.

### What do you see instead?
```
236 |       if (this.authorized = !1, this.secureConnecting = !0, this._secureEstablished = !1, this._securePending = !0, connectListener)
237 |         this.on("secureConnect", connectListener);
238 |     } else if (connectListener)
239 |       this.on("connect", connectListener);
240 |
241 |     return bunConnect(path ? {
              ^
TypeError: Expected "port" to be a number between 0 and 65535
 code: "ERR_INVALID_ARG_TYPE"

      at connect (node:net:241:11)
      at /PATH/TO/CODE/node_modules/postgres/src/connection.js:271:13
```
### Additional information

The postgres package is attempting to upgrade an existing socket to a secure one.

I found it a little surprising that the error message seemed to indicate that code in node:net is being called, rather than node:tls (but I am fairly unfamiliar with the internals of bun, so this just could be naivety or minunderstanding on my part 🤷)

**Comment by Akiyamka** [comment]
Same issue with [pg](https://www.npmjs.com/package/pg) library 
And test code works without errors in the node (20.3.0)
```
236 |       if (this.authorized = !1, this.secureConnecting = !0, this._secureEstablished = !1, this._securePending = !0, connectListener)
237 |         this.on("secureConnect", connectListener);
238 |     } else if (connectListener)
239 |       this.on("connect", connectListener);
240 | 
241 |     return bunConnect(path ? {
              ^
TypeError: Expected "port" to be a number between 0 and 65535
 code: "ERR_INVALID_ARG_TYPE"

      at connect (node:net:241:11)
        at getSecureStream (/home/user/project/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/stream.js:25:11)
      at /home/user/project/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/connection.js:100:22
      at m (node:stream:2:68547)
      at u (node:stream:2:67202)
      at data (node:net:48:12)
```
code:
https://github.com/brianc/node-postgres/blob/735683c5cb41bcbf043c6490be4b7f38cfe3ac48/packages/pg/lib/stream.js#L20-L28

Looks like buns tls.connect require `options.port` property, but in fact it's not required for case when we pass `options.socket` property (I could be wrong)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/16c0ed21f021e3685aa44193400396f49fdbbf5d/types/node/tls.d.ts#L599

**Comment by Jarred-Sumner** [comment]
Fixed by @cirospaciari
