### ISSUE TITLE
Vite error when using bun with Tauri

### ISSUE THREAD

**Issue by MidKnightXI** [oven-sh/bun#3237]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

- Create a new Tauri project
- Replace the dependencies with `yarn` in `tauri.conf.json`
- Install the node_modules with `bun install`
- Run `bun run tauri dev`

### What is the expected behavior?

Vite should create a server for the front and tauri should build the project with cargo

### What do you see instead?

```
$ tauri dev
     Running BeforeDevCommand (`bun run dev`)
$ vite
failed to load config from /Users/vite.config.js
error when starting dev server:
Error: The service was stopped: spawn /Users/node_modules/esbuild-darwin-arm64/bin/esbuild EACCES
    at /Users/node_modules/esbuild/lib/main.js:1122:25
    at Object.responseCallbacks.<computed> (/Users/node_modules/esbuild/lib/main.js:680:9)
    at ChildProcess.afterClose (/Users/node_modules/esbuild/lib/main.js:670:28)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error: script "dev" exited with code 1 (SIGHUP)
       Error The "beforeDevCommand" terminated with a non-zero status code.
error: script "tauri" exited with code 1 (SIGHUP)
```

### Additional information

```json
// package.json

{
  "name": "",
  "version": "",
  "description": "",
  "scripts": {
    "start": "vite",
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview",
    "tauri": "tauri"
  },
  "license": "MIT",
  "devDependencies": {
    "@tauri-apps/cli": "^1.3.1",
    "vite": "^3.0.0",
    "vite-plugin-solid": "^2.3.0"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.1.0",
    "solid-js": "^1.4.7"
  }
}
```

```js
// vite.config.js
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";

export default defineConfig({
  plugins: [solidPlugin()],

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  // prevent vite from obscuring rust errors
  clearScreen: false,
  // tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
  },
  // to make use of `TAURI_DEBUG` and other env variables
  // https://tauri.studio/v1/api/config#buildconfig.beforedevcommand
  envPrefix: ["VITE_", "TAURI_"],
  build: {
    // Tauri supports es2021
    target: ["es2021", "chrome100", "safari13"],
    // don't minify for debug builds
    minify: !process.env.TAURI_DEBUG ? "esbuild" : false,
    // produce sourcemaps for debug builds
    sourcemap: !!process.env.TAURI_DEBUG,
  },
});
```

```json
// tauri.conf.json "build" variable

{
  "build": {
    "beforeDevCommand": "bun run dev",
    "beforeBuildCommand": "bun run build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": false
  },
}
```

**Comment by paperclover** [comment]
this is a duplicate of #3216 

but the EACCES on spawn esbuild is a little concerning.

can you try this again not within `/Users` but instead in a folder like `/Users/yournamehere/example`, might be a permission error.

**Comment by MidKnightXI** [comment]
It wasn't in my /Users but on my personal user directory, I also tried with sudo but same error

**Comment by birkskyum** [comment]
@MidKnightXI , the `failed to load config from /Users/vite.config.js` is likely to be resolved by some recent changes (https://github.com/oven-sh/bun/issues/3724, https://github.com/oven-sh/bun/issues/3783, https://github.com/oven-sh/bun/pull/3732) in the latest canary `bun upgrade --canary`. Would you mind checking if this error still persist?

**Comment by birkskyum** [comment]
I find that even running the tauri creation script gives a Strict mode error:

* `bun --bun x create-tauri-app@latest`

Output:

```sh

➜ bun --bun x create-tauri-app@latest


error: Declarations with the name arguments cannot be used with esm due to strict mode

const [bin, script, ...arguments] = process.argv;
                       ^
/private/tmp/create-tauri-app@latest--bunx/node_modules/create-tauri-app/create-tauri-app.js:10:24 249
error: "create-tauri-app" exited with code 1 (SIGHUP)

```

**Comment by MidKnightXI** [comment]
> @MidKnightXI , the `failed to load config from /Users/vite.config.js` is likely to be resolved by some recent changes (#3724, #3783, #3732) in the latest canary `bun upgrade --canary`. Would you mind checking if this error still persist?

I'll check tonight if I can, will post the result when I'm done trying 👍🏻

**Comment by MidKnightXI** [comment]
```zsh
➜  ~ bun --bun x create-tauri-app@latest


error: Declarations with the name arguments cannot be used with esm due to strict mode

const [bin, script, ...arguments] = process.argv;
                       ^
/Users/midknight/.config/yarn/global/node_modules/create-tauri-app/create-tauri-app.js:10:24 249
error: "create-tauri-app" exited with code 1 (SIGHUP)
```

**Comment by birkskyum** [comment]
not sure, but could be related to:
- #4130 
- #4075

**Comment by paperclover** [comment]
that is not related. the error shown is related to strict mode. if you rename the variable, things almost work but there is an event loop related bug which can be fixed by using top-level await on their `.run()` function later in the same file. this brings it to working but with stability issues.

**Comment by birkskyum** [comment]
This issue with `arguments` and strict mode is now fixed upstream in create-tauri-app Node.js CLI, but it's not released yet.

**Comment by s9kt** [comment]
This doesn't seem to be entirely fixed (at least for me). While I'm able to create the Tauri app, I can't run it with `bun --bun run tauri dev`. 

```
$ tauri dev

error: Declarations with the name arguments cannot be used with esm due to strict mode

const [bin, script, ...arguments] = process.argv
                       ^
/home/dev/tauri-app/node_modules/@tauri-apps/cli/tauri.js:10:24 246
error: script "tauri" exited with code 1 (SIGHUP)
```

`bun run tauri dev` compiles and works as intended though.

**Comment by birkskyum** [comment]
@s9kt , as explained [here](https://github.com/tauri-apps/tauri/pull/7919#issuecomment-1741234600) will the error be resolved when a new version of [@tauri-apps/cli](https://github.com/tauri-apps/tauri/tree/dev/tooling/cli) comes out.
- https://github.com/tauri-apps/tauri/pull/7641

**Comment by birkskyum** [comment]
`bun --bun x create-tauri-app@latest` works now to create a new repo.

When running the `bun --bun run tauri dev` or `tauri build`, the cli exists immediately

**Comment by birkskyum** [comment]
continuation of this
- #7731

**Comment by AlbertMarashi** [comment]
Anyone still getting this issue?

https://github.com/vitejs/vite/discussions/17851
