### ISSUE TITLE
Option to build into a flat directory structure (--flat?)

### ISSUE THREAD

**Issue by loicnestler** [oven-sh/bun#3238]
### What is the problem this feature would solve?

Some tools, servers, etc. (especially Shopify) expects the `assets/` directory to be flat (i.e. to have no other dir inside it).

### What is the feature you are proposing to solve the problem?

A `Bun.build` flag (possible `flat?: boolean` / `--flat`) to tell Bun to build all assets into a top-level directory.

### What alternatives have you considered?

Nasty symlinking, additional build-steps, ...

**Comment by paperclover** [comment]
unless you have multiple entrypoints in different directories, is the directory not already flat?

try setting `naming.entry` to `[name].[ext]` or `--entry-naming '[name].[ext]'`
