### ISSUE TITLE
Crash with JSDOM and Prettier

### ISSUE THREAD

**Issue by spiffytech** [oven-sh/bun#3239]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Linux 6.3.5-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

This is _absolutely bizarre_! I have this garbage test HTML from my project, but attempting to simplify it any more than this breaks the reproduction.

We need all of these or the reproduction fails:
- 2 JSDOM instances
- The `<script>` tag, or either statement inside it
- The `<p>`
- Both `<section>`s
- Both `dom.serialize()` and the Prettier call (printing the serialized DOM doesn't fail, and prettying a hardcoded HTML string doesn't fail)

```ts
import { JSDOM } from "jsdom";
import prettier from "prettier";

const render = () => {
  // JSDOM document.write() stuffs everything inside <body>, and trying anything
  // else errors out that you can't modify <html> or whatever.
  //let dom2 = new JSDOM(`
  const dom1 = new JSDOM("");
  let dom2 = new JSDOM(`
    <!DOCTYPE html>
    <html lang="en" class="no-js">
      <head>
        <title>Hello, world!</title>

        <script type="module">
          document.documentElement.classList.remove('no-js');
          document.documentElement.classList.add('js');
        </script>
      </head>

      <body>
        <section bar="{&quot;a&quot;:1,&quot;b&quot;:&quot;2023-06-07T17:39:47.022Z&quot;}" baz="2023-06-07T17:39:47.022Z">
          Section 123 with children Top-level Blah:
        </section>
        
        <p>Another child: Top-level Blah:</p>

        <section bar="{&quot;a&quot;:1,&quot;b&quot;:&quot;2023-06-07T17:39:47.021Z&quot;}" baz="2023-06-07T17:39:47.021Z">
          Section 456 with children Grandchildren!
        </section>
      </body>
    </html>`);
  const html = prettier.format(dom2.serialize(), { parser: "html" });
  return html;
};

render();
```

```sh
bun run index.ts
```

### What is the expected behavior?

No crash

### What do you see instead?

```
$ bun run index.tsx
zsh: segmentation fault (core dumped)  bun run index.tsx
```

Bun hangs for a bit, unresponsive to Ctrl-c, and eventually crashes with a segfault. Even SIGKILL takes a moment to kill it.

### Additional information

Node runs this without issue.

**Comment by Jarred-Sumner** [comment]
Sounds like a memory issue causing malloc in a loop

**Comment by paperclover** [comment]
Feels related to #3224 because i can do this
```
import "jsdom";
Bun.gc(true);
```

**Comment by spiffytech** [comment]
> Sounds like a memory issue causing malloc in a loop

This inspired me to try playing with the input size. By making the HTML a couple hundred lines long, I could reproduce the crash with a simplified HTML structure, and with only DOM instance:

```ts
const render = () => {
  let dom = new JSDOM(`
    <!DOCTYPE html>
    <html lang="en" class="no-js">
      <body>
      <p>Hello</p>
      <p>Hello</p>
      ...
      <p>Hello</p>
      </body>
    </html>`);
  const html = prettier.format(dom.serialize(), { parser: "html" });
  return html;
};

render();
```

**Comment by spiffytech** [comment]
Alright, here's the itsiest-bitsiest repro I can make:

```ts
for (let i = 0; i < 12; i += 1) {
  new JSDOM("");
}
```

Sounds like you already have an idea where to look, so I'll leave you to it 🙂

**Comment by Jarred-Sumner** [comment]
JSDOM segfault is a missing symbol error.

not a memory issue

Something we haven't implemented in napi yet.

**Comment by paperclover** [comment]
Fixed in https://github.com/oven-sh/bun/pull/3294 (0.6.9)

your other issue with `| less` still stands
