### ISSUE TITLE
Running code generated with `useDefineForClassFields` option fails

### ISSUE THREAD

**Issue by mindreframer** [oven-sh/bun#3246]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 21.4.0 arm64 arm

### What steps can reproduce the bug?

Repo with code reproduction here: 
- https://github.com/mindreframer/bun-defineForClassField

The compilation works, but running code that uses decorators for class fields fails. Other decorators for functions seem to work OK. 

### What is the expected behavior?

Code should evaluate properly

### What do you see instead?

```
$ bun run index.ts
568 |   const key = Symbol(`Observable ${prop}`);
569 |
570 |   const field = function () {
571 |     var _descriptor$initializ;
572 |
573 |     return key in this ? this[key] : this[key] = observable(((_descriptor$initializ = descriptor.initializer) === null || _descriptor$initializ === void 0 ? void 0 : _descriptor$initializ.call(this)) ?? undefined);
                                                                                          ^
TypeError: undefined is not an object (evaluating 'descriptor.initializer')
      at /Users/roman/Desktop/bun-defineForClassFields/node_modules/@whatsup/core/dist/index.esm.js:573:86
      at set (/Users/roman/Desktop/bun-defineForClassFields/node_modules/@whatsup/core/dist/index.esm.js:582:13)
      at new User (/Users/roman/Desktop/bun-defineForClassFields/index.ts:22:4)
      at /Users/roman/Desktop/bun-defineForClassFields/index.ts:27:13
```
<img width="1439" alt="Screenshot 2023-06-08 at 12 24 22" src="https://github.com/oven-sh/bun/assets/1232/338133ff-61b2-4791-b307-57c79913fa38">

### Additional information

Bun is great, hoping those issues will be ironed out in near future!

**Comment by NicolasThierion** [comment]
I encountered this issue today, with **bun@1.1.26**.

**Comment by paperdave** [comment]
Duplicate of #2060
