### ISSUE TITLE
Unable to require files/modules with multiple "." in the name

### ISSUE THREAD

**Issue by tandpfun** [oven-sh/bun#325]
When requiring a local file like `require('./hello.world.js')`, bun tries to get `./hello.world` instead of `./hello.world.js`.

**Comment by oculus42** [comment]
Unable to reproduce this issue on 0.1.4.

**Comment by ghost** [comment]
@tandpfun Can you confirm that this issue is still present?

**Comment by zhuzilin** [comment]
close for now, feel free to reopen if it still persists :)
