### ISSUE TITLE
Prompt retrying command with sudo upon file permission errors

### ISSUE THREAD

**Issue by Dev5H0** [oven-sh/bun#3251]
### What is the problem this feature would solve?

This feature would fix the inability to run global, and certain bunx commands caused by file permission errors. 

### What is the feature you are proposing to solve the problem?

Have bunx commands and bun pm -g bin prompt you whether you want to retry with sudo if you get a permission error

**Comment by Electroid** [comment]
We are unlikely to do this, we already show a permission error.
