### ISSUE TITLE
global configuration file is not working

### ISSUE THREAD

**Issue by gutenye** [oven-sh/bun#3258]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```
$ vi $HOME/.bunfig.toml
	[dev]
	port = 3001

$ cd /tmp
$ bun dev
  Link: http://localhost:3000
```

### What is the expected behavior?

bun dev should listen on 3001 port

### What do you see instead?

3000 port

### Additional information

use local configuration works by mving $HOME/.bunfig.toml to ./bunfig.toml

**Comment by Electroid** [comment]
Instead of `$HOME/.bunfig.toml`, what if you try `$HOME/bunfig.toml`?

**Comment by gutenye** [comment]
`$HOME/bunfig.toml` also doesn't work

**Comment by Hanaasagi** [comment]
It seems there are some commands that do not read the config file in the home directory.

https://github.com/oven-sh/bun/blob/6402967b6d16004219254495bc70d112981c36b3/src/cli.zig#L277-L287

https://github.com/oven-sh/bun/blob/6402967b6d16004219254495bc70d112981c36b3/src/cli.zig#L1615-L1620

`DevCommand` is not in the list.

**Comment by Jarred-Sumner** [comment]
`bun dev` no longer exists
