### ISSUE TITLE
Crypto.Hash digest() returns Uint8Array instead of expected Buffer

### ISSUE THREAD

**Issue by justinhippo** [oven-sh/bun#3289]
### What version of Bun is running?

v0.6.8

### What platform is your computer?

Linux 5.19.0-43-generic x86_64 x86_64

### What steps can reproduce the bug?

```
const digest = Crypto.createHash('md5').update(chunk).digest();
console.log(digest)
```

### What is the expected behavior?

`Crypto.Hash` `digest()` returns a `Buffer`

### What do you see instead?

`Crypto.Hash` `digest()` returns a `Uint8Array`

### Additional information

This breaks some implementations of hashing where it is useful to be able to call `Buffer.toString(encoding)`

**Comment by Jarred-Sumner** [comment]
This one is fixed in the canary build of bun
