### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by SunPodder** [oven-sh/bun#329]
I installed bun with the installing script from `bun.sh/install`. When running bun in command line it gives the following error.
```
bash: ./.bun/bin/bun: cannot execute binary file: Exec format error
```

I know this is caused of my system configuration. So now how can I install bun? Would I need to compile it myself?

**Comment by Jarred-Sumner** [comment]
Can you tell me a little more about your computer? are you running on arm64?

**Comment by SunPodder** [comment]
Yeah. I'm actually using a terminal emulator.

Result of `uname -a`
```
Linux localhost 4.19.127-22457755 #1 SMP PREEMPT Wed Nov 10 18:56:38 KST 2021 aarch64 Android
```

**Comment by Ta1al** [comment]
only x64 is supported on linux for now

**Comment by lavahasif** [comment]
Linux DESKTOP-ODLD7P9 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

what about this ? show cannot execute binary file.

**Comment by lynn2910** [comment]
> only x64 is supported on linux for now

Did aarch63 work ?

**Comment by leap0x7b** [comment]
> > only x64 is supported on linux for now
> 
> Did aarch63 work ?

lmfao

**Comment by FinnRG** [comment]
@SunPodder ```aarch64``` support will be tracked in #418. Please close this issue.
