### ISSUE TITLE
JSX `createElement` imported from module not present at runtime

### ISSUE THREAD

**Issue by spiffytech** [oven-sh/bun#3301]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux 6.3.5-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

tsconfig.json:

```
    "jsx": "react",
    "jsxFactory": "createElement",
```

jsx.ts:
```ts
export const createElement = () => null;
```

index.tsx:
```tsx
import { createElement } from "./jsx.tsx";

Bun.serve({
  port: 8082,
  fetch(req) {
    return <div>Hello, world!</div>;
  },
});
```

### What is the expected behavior?

The code runs

### What do you see instead?

```
$ bun run index.tsx
1 | import { createElement } from "./jsx.tsx";
2 | 
3 | Bun.serve({
4 |   port: 8082,
5 |   fetch(req) {
6 |     return <div>Hello, world!</div>;
               ^
ReferenceError: Can't find variable: createElement
      at fetch (/tmp/123/index.tsx:6:11)
GET - / failed
```

### Additional information

`console.log(createElement)` prevents the error.

Might or might not be related to #3299.

Affects `jsxFragmentFactory` too.

If `jsxFactory` is set to `jsx.createElement`, the same error occurs. Insure if that's related, or if Bun improperly handles namespaced values for that field.

**Comment by dylan-conway** [comment]
fixed with #3360
