### ISSUE TITLE
Bun.argv => argv  with Chinese  is not supported

### ISSUE THREAD

**Issue by peterwangfeng** [oven-sh/bun#3307]
### What version of Bun is running?

0.6.9

### What platform is your computer?

ubuntu x64

### What steps can reproduce the bug?

```js
const arg = Bun.argv
console.log(arg)
```

### What is the expected behavior?
bun test.js 中国
```js
['bun', 'test.js', '中国']
```

### What do you see instead?

```js
[ "bun", "test.mjs", "ä¸­å›½" ]
```

**Comment by Jarred-Sumner** [comment]
will fix, this code is some of the oldest in Bun and needs to be updated

For now, I suggest `process.argv`

**Comment by peterwangfeng** [comment]
thanks
