### ISSUE TITLE
Crash when loading mapbox sdk in Bun v0.6.9

### ISSUE THREAD

**Issue by TommasoAmici** [oven-sh/bun#3315]
### What version of Bun is running?

0.6.9

### What platform is your computer?

`Darwin 22.5.0 arm64 arm`, I also tried on `Linux 5.15.0-25-generic x86_64 x86_64`

### What steps can reproduce the bug?

I have a telegram bot written in typescript that I've been running fine with bun up until v0.6.9.

It now fails with 

```
error: script "start" exited with code 11 (SIGSEGV)
```

I've identified the problematic code in this file: https://github.com/TommasoAmici/sandro-cois-bot/blob/main/src/plugins/loc.ts

```ts
const mbxGeocoding = require("@mapbox/mapbox-sdk/services/geocoding");
import { Context, HearsContext } from "grammy";
import cfg from "../config";

const geocodingClient = mbxGeocoding({ accessToken: cfg.mapboxToken });

const makeMapboxScreenshot = (coord: number[]): string =>
  `https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/${coord[0]},${coord[1]},10,0.00,0.00/1000x600@2x?access_token=${cfg.mapboxToken}`;

export const location = async (ctx: HearsContext<Context>) => {
  const query = ctx.match[1];
  geocodingClient
    .forwardGeocode({ query: query, limit: 1 })
    .send()
    .then(async (response: unknown) => {});
};
```
I haven't been able to make a minimal reproduction as a bot with only this function works properly, but when I run it with the entire codebase it fails.

### What is the expected behavior?

No error

### What do you see instead?

```
error: script "start" exited with code 11 (SIGSEGV)
```

### Additional information

I realize this is not easy to reproduce because it requires a few API tokens and to checkout a non-minimal reproduction, so if you could point me to some docs on how to produce a more meaningful bug report, I'll be happy to help.

**Comment by Jarred-Sumner** [comment]
I believe the crash is in code like this 

`var f = module; f.require(“boom”)` 

Can you try in the canary build? Might’ve been fixed 

`bun upgrade --canary`

**Comment by TommasoAmici** [comment]
Indeed, I just tried converting the `require` to `import` and it's working properly.

With the canary build I get a new set of errors though

```
$ bun run src/index.ts
[0.06ms] ".env"
18 | __exportStar(require("./queue.js"), exports);
19 | __exportStar(require("./runner.js"), exports);
20 | __exportStar(require("./sequentialize.js"), exports);
21 | __exportStar(require("./sink.js"), exports);
22 | __exportStar(require("./source.js"), exports);
23 | __exportStar(require("./worker.js"), exports);
                                               ^
TypeError: undefined is not an object (evaluating 'this.module.require = this.require')
      at (eval) (.../sandro-cois-bot/node_modules/@grammyjs/runner/out/mod.js:23:44)
```

so 0.6.9 with `import` works, canary with `require` throws these new errors in another lib

**Comment by hostlund** [comment]
I got this error when i try and follow this guide: https://dev.to/harshmangalam/add-jwt-authentication-in-bun-api-488d

Think i got it the fisrt time when i tried to run `bun add @elysiajs/cookie @elysiajs/jwt`

Can't find any require in the main src files. Tried canary as well and got the same error.

![bild](https://github.com/oven-sh/bun/assets/459391/b640a06c-cbb6-48f2-be03-f0496dcde47e)

Is there some way I can downgrade to 0.6.8?

**Comment by simylein** [comment]
You may try `brew install bun@0.6.8` if you are on macOS. 
Also is this still happening in the latest bun version?

**Comment by shlomoweb1** [comment]
I am running bun via nx, so I thought maybe nx; after few hours I get crash 

`error: script "serve" exited with code 11 (SIGSEGV)`

The code is written from scratch with typescript and use only import

Using Bun version 0.7.3
Mac book Pro
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 64 GB 2667 MHz DDR4
macOS: 13.4.1 (c) (22F770820d)

**Comment by Tanguille** [comment]
I currently have the exact same error output with bun version v1.0.6 on Fedora Linux.

**Comment by nomadshiba** [comment]
Same issue with the `oven/bun:1.0.6` docker image.
Weird thing is container runs fine on my local machine but gives `...exited with code 11 (SIGSEGV)` on the remote server.
Weird because i use the same `dockerfile` and run command for both.

**Comment by MagicFun1241** [comment]
Actual on Bun 1.1.3 and grammy 1.22.4

**Comment by Jarred-Sumner** [comment]
For any future readers of this issue

If you run into an issue with `SIGSEGV` note that it can be many different causes unrelated to this particular issue 

Since this issue, we've added a crash reporter and please include the crash report if you run into a segfault

I am confident OP's original issue was fixed

I am not confident the grammy issue is fixed as I was unable to reproduce it in both current and older versions of Bun
