### ISSUE TITLE
`nodejs-polars` IO methods throwing `error: InvalidArg`

### ISSUE THREAD

**Issue by danscan** [oven-sh/bun#3317]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Using the `nodejs-polars` package, attempt to read a parquet file, either from a file path, or from a Buffer.

## Using File Path
```typescript
const dataframe = pl.readParquet(filepath);
```
```
188 |         const inline = !(0, utils_1.isPath)(pathOrBody, [".parquet"]);
189 |         if (inline) {
190 |             return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(Buffer.from(pathOrBody), pliOptions, parallel));
191 |         }
192 |         else {
193 |             return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(pathOrBody, pliOptions, parallel));
                                                  ^
error: InvalidArg
      at /redacted/node_modules/nodejs-polars/bin/io.js:193:47
```

## Using Buffer
```typescript
const dataframe = pl.readParquet(
  Buffer.from(await Bun.file(filepath).arrayBuffer())
);
```
```
180 |     }
181 |     pliOptions.nRows = options?.numRows;
182 |     pliOptions.rowCount = options?.rowCount;
183 |     const parallel = options?.parallel ?? "auto";
184 |     if (Buffer.isBuffer(pathOrBody)) {
185 |         return (0, dataframe_1._DataFrame)(polars_internal_1.default.readParquet(pathOrBody, pliOptions, parallel));
                                              ^
error: InvalidArg
      at /redacted/node_modules/nodejs-polars/bin/io.js:185:43
```

### What is the expected behavior?

The `pl.readParquet` call should return a `pl.DataFrame` with data from the parquet file.

### What do you see instead?

`error: InvalidArg` is thrown

### Additional information

Using `nodejs-polars`, I'm encountering `error: InvalidArg` for I/O methods, which include `readCsv`, `readParquet`, `readJson`, `scanParquet`, etc.

**Comment by danscan** [comment]
Related issue in the nodejs-polars repo: https://github.com/pola-rs/nodejs-polars/issues/49#issuecomment-1591331139

**Comment by karagraysen** [comment]
Hi @danscan,

Thank you for posting this ticket. 

* I've been really interested in Bun and decided to take a look at this ticket for investigatory/learning purposes.
* I've created a repo (https://github.com/karagraysen/bun-3317) that has the code related to my investigation. 

The Node.js version ([`node-js-version/index.js`](https://github.com/karagraysen/bun-3317/blob/032c7525b45d9e72df23b269ee7d42b2139fb4ce/node-js-version/index.js)) behaves as expected with the following code:

```js
const filepath = "../nation.parquet"
const dataframe = pl.readParquet(filepath);
console.log(`${dataframe}`)
```

<img width="676" alt="Screenshot 2023-06-20 at 6 03 56 PM" src="https://github.com/oven-sh/bun/assets/6799989/4f5e993e-3448-489b-8a0b-6ac9947bd294">

However, after some time investigating, I managed to get the same output using Bun with the following two changes:

1. Explicitly listing the columns in the `options` field.
2. Modifying `io.ts` in `nodejs-polars` to set both `pliOptions.projections` and `pliOptions.columns` to `options?.columns`.

[`bun-version/index.ts`](https://github.com/karagraysen/bun-3317/blob/main/bun-version/index.ts):

```js
const filepath = "../nation.parquet"
const dataframe = pl.readParquet(filepath, {columns: ["nation_key", "name", "region_key", "comment_col"]});
console.log(`${dataframe}`)
```

[`bun-version/node_modules/nodejs-polars/bin/io.js`](https://github.com/karagraysen/bun-3317/blob/main/bun-version/node_modules/nodejs-polars/bin/io.js):

```js
if (typeof options?.columns?.[0] === "number") {
  pliOptions.projection = options?.columns;
} else {
  pliOptions.columns = options?.columns;
  pliOptions.projection = options?.columns; // Added this line
}
```

<img width="725" alt="Screenshot 2023-06-20 at 6 05 17 PM" src="https://github.com/oven-sh/bun/assets/6799989/e8b81278-077f-4f58-866f-d4e13e3b8ef5">

With that said, I focused on Parquet for this current response. This is IMO not an I/O issue as much as it is a parsing options/settings issue. I tried to find where this inferred behaviour happens but couldn't locate the package handling it (Any thoughts?) 

I also wasn't able to reproduce it with `readJSON` with multiple JSON files that I tested so I would be interested to see the file that you used/reproduce the issue with it.

Questions for @danscan:

- Please provide the test files (`.csv`, `.parquet`, `.json`) that you reproduced these issues on. It would be helpful so we're comparing the same types of files as there are many ways to customize these formats. Especially parquet files. They be intense. 😳 

(Possibly) Questions for @Jarred-Sumner:

- What library/package manages the options inference for the columns? I am less familiar with JavaScript ecosystem but I know there are many packages for the same thing that can be slotted in but I forget the nomenclature for what's that referred to.
- How do you see a fix progressing for this issue? As I'm learning Zig, Bun, and the ecosystems, it would be super helpful to just have a direction to move into.

Thanks and hope this was helpful!
