### ISSUE TITLE
Maybe there should be a web framework like Deno's "fresh", thus, Bun immediately has an application scenario.

### ISSUE THREAD

**Issue by zwl1619** [oven-sh/bun#332]
Maybe there should be a web framework like Deno's "[fresh](https://github.com/denoland/fresh)", thus, Bun immediately has an application scenario.
I'm looking forward to it.

**Comment by Jarred-Sumner** [comment]
Initially, I think it'd be great for this to be existing frameworks like Next.js and Remix so that people don't have to invest in learning a new framework
