### ISSUE TITLE
Allow naming entrypoints

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3323]
### What is the problem this feature would solve?

You can't output two entrypoints with the same filename but different paths to the same directory:

e.g. `root/blah/foo/index.ts` and `root/blah/bar/index.ts`

I want `outdir/foo-bundle.ts` and `outdir/bar-bundle.ts`.

### What is the feature you are proposing to solve the problem?

It would be nice to be able to name entrypoints and then use that name in the `naming`. This would mean I wouldn't need nested entrypoint paths.

```
entrypoints: [
  {name: 'foo', path: '/path/to/foo/index.ts},
  {name: 'bar', path: '/path/to/bar/index.ts}
]

naming: {
  //entry: '[dir]/[name].[ext]',
  entry: '[entrypoint-name].[ext]',
  chunk: '[name]-[hash].[ext]',
  asset: '[name]-[hash].[ext]',
},
```

You can see that at present both are named `index.ts`.

**Comment by paperclover** [comment]
i like the idea of `{name:'foo',path:'...'}`, but i think it should still use the `[name]` placeholder. setting a custom name should also set `dir` to "". could also allow this notation, which i think i've seen in rollup(?)

```ts
entrypoints: {
  foo: './path/to/foo/index.ts',
  bar: './path/to/foo/index.ts',
}
```

note: with your current directory setup, `[dir]` will be equal to "foo" or "bar" (relative to first common ancestor directory) so you could get away with `naming: "[dir].[ext]"`

**Comment by arkmech** [comment]
[#4714](https://github.com/oven-sh/bun/issues/4714)

**Comment by dartess** [comment]
It would be enough for me to have a function to which the entry is passed:

```js
{
  entrypoints: [
    '/path/to/foo/index.ts',
    ''/path/to/bar/index.ts',
  ],
  naming: entrypoint => {
    if (entrypoint === '/path/to/foo/index.ts') {
      return './path/to/foo/index.ts';
    }
    return './path/to/bar/index.ts';
  },
}
```

(UPD: did not take into account that this config will be used in zig. This might be a little difficult.)

**Comment by Electroid** [comment]
Duplicate of #5160
