### ISSUE TITLE
HTTP requests will not work

### ISSUE THREAD

**Issue by hamidreza01** [oven-sh/bun#333]
Hi, This error will be displayed in all http requests 
```bash
pc@pc:~/project$ bun add bun-types
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().

```

**Comment by Coding-Crashkurse** [comment]
For some people running `wsl --update` and `wsl --shutdown` solved the problem. For me it did not. Let me know if it works for you

**Comment by MagiqueDeveloper** [comment]
**Windows:**
In Windows Powershell (Admin Permissions), run `wsl --update` and then after that run `wsl --shutdown`.

**Other OS':**
`None known fix from myself.`

**Comment by hamidreza01** [comment]
> **Windows:** In Windows Powershell (Admin Permissions), run `wsl --update` and then after that run `wsl --shutdown`.
> 
> **Other OS':** `None known fix from myself.`

Thank you all, but the problem is still there 
I enter the commands and then I enter wsl again.
But the error will be displayed again.

**Comment by MagiqueDeveloper** [comment]
> > **Windows:** In Windows Powershell (Admin Permissions), run `wsl --update` and then after that run `wsl --shutdown`.
> > **Other OS':** `None known fix from myself.`
> 
> Thank you all, but the problem is still there I enter the commands and then I enter wsl again. But the error will be displayed again.

Try asking for help in the Bun Discord server. There will be better support there. https://discord.gg/PxYjYhWr

**Comment by hamidreza01** [comment]
> Try asking for help in the Bun Discord server. There will be better support there. https://discord.gg/PxYjYhWr

The problem was solved with these commands, thank you.
The first time I was losing my Internet connection

**Comment by MagiqueDeveloper** [comment]
Nice to hear you got it sorted!
