### ISSUE TITLE
ytld-core: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by imalfect** [oven-sh/bun#3336]
### What version of Bun is running?

0.6.1 (also tested on canary, same problem)

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Paste the following code snippet into a new file:
```js
import ytdl from 'ytdl-core';
const info = await ytdl.getInfo('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
console.log(info);
```

Run your file using `bun start`

### What is the expected behavior?

Expected behavior is information about the video provided in a JSON format printed in the console.

### What do you see instead?

A segmentation fault error.
`[1]    27760 segmentation fault (core dumped)  bun run tst.js`

**Comment by v3nntrnx** [comment]
Also, just trying to `ytdl()` doesn't work too

**Comment by imalfect** [comment]
Issue still persists on latest canary (to commit `4f34d48029772676b6c0ea6656b0aac74ac3b39f`)
