### ISSUE TITLE
Buffer => readBigUint64BE  is not a function

### ISSUE THREAD

**Issue by peterwangfeng** [oven-sh/bun#3338]
### What version of Bun is running?

0.6.9

### What platform is your computer?

macos13.2.1 x64

### What steps can reproduce the bug?

```js
const buf = Buffer.alloc(8)
buf.writeBigUint64BE(BigInt(123), 0)
const first = buf.readBigUint64BE(0)
console.log(first)
```

### What is the expected behavior?

123n

### What do you see instead?

TypeError: buf.readBigUint64BE is not a function. (In 'buf.readBigUint64BE(0)', 'buf.readBigUint64BE' is undefined)

**Comment by Jarred-Sumner** [comment]
yeah we need to add the alias

try `readBigUInt64BE` for now

**Comment by peterwangfeng** [comment]
thanks
