### ISSUE TITLE
 51197 segmentation fault  bun run ...

### ISSUE THREAD

**Issue by shuiRong** [oven-sh/bun#3339]
### What version of Bun is running?

0.6.7

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I run `bun run index.js` directly, and then I get the error above.

After testing, I found that the error is related to the length of the html. Because if I only use a small piece of html code to parse, then there will be no problem.

<details>
  <summary>It's the issue code</summary>
  <pre><code>

const html = `<!doctype html><html lang="ja-jp" dir="ltr">

<head>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta charset="utf-8">
  <base href="https://www.sparticle.com/ja/blog-jp-2/ai-gptbase-ai">
  <meta name="keywords" content="Sparticle">
  <meta name="author" content="vincent">
  <meta name="description" content="Sparticle">
  <meta name="generator" content="Helix Ultimate - The Most Popular Joomla! Template Framework.">
  <title>AI時代の革命者：GPTBaseがこれからの、日本のAIアシスタントサービス市場を変える！</title>
  <link href="/images/favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
  <link
    href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&subset=latin&display=swap"
    rel="stylesheet" media="none" onload="media=&quot;all&quot;">
  <link
    href="//fonts.googleapis.com/css?family=Noto Sans:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&subset=latin&display=swap"
    rel="stylesheet" media="none" onload="media=&quot;all&quot;">
  <link href="/templates/shaper_helixultimate/css/bootstrap.min.css" rel="stylesheet">
  <link href="/plugins/system/helixultimate/assets/css/system-j3.min.css" rel="stylesheet">
  <link href="/templates/shaper_helixultimate/css/font-awesome.min.css" rel="stylesheet">
  <link href="/templates/shaper_helixultimate/css/v4-shims.min.css" rel="stylesheet">
  <link href="/templates/shaper_helixultimate/css/template.css" rel="stylesheet">
  <link href="/templates/shaper_helixultimate/css/presets/preset4.css" rel="stylesheet">
  <link href="/media/mod_languages/css/template.css?6357188fe7a64624969d58a72a53bd73" rel="stylesheet">
  <link href="/media/jui/css/chosen.css?6357188fe7a64624969d58a72a53bd73" rel="stylesheet">
  <style>
    body {
      font-family: 'Roboto', sans-serif;
      font-size: 16px;
      line-height: 1.56;
      text-decoration: none;
    }

    @media (min-width:768px) and (max-width:991px) {
      body {
        font-size: 14px;
      }
    }

    @media (max-width:767px) {
      body {
        font-size: 13px;
      }
    }

    h1 {
      font-family: 'Noto Sans', sans-serif;
      text-decoration: none;
    }

    h2 {
      font-family: 'Noto Sans', sans-serif;
      text-decoration: none;
    }

    h3 {
      font-family: 'Noto Sans', sans-serif;
      text-decoration: none;
    }

    h4 {
      font-family: 'Noto Sans', sans-serif;
      text-decoration: none;
    }
  </style>
  <script type="application/json"
    class="joomla-script-options new">{"csrf.token":"863b4909f6cac81d0cd0fa442ed772f6","data":{"breakpoints":{"tablet":991,"mobile":480},"header":{"stickyOffset":"0"}},"system.paths":{"root":"","base":""}}</script>
  <script src="/media/jui/js/jquery.min.js?6357188fe7a64624969d58a72a53bd73"></script>
  <script src="/media/jui/js/jquery-noconflict.js?6357188fe7a64624969d58a72a53bd73"></script>
  <script src="/media/jui/js/jquery-migrate.min.js?6357188fe7a64624969d58a72a53bd73"></script>
  <script src="/templates/shaper_helixultimate/js/bootstrap.bundle.min.js"></script>
  <script src="/templates/shaper_helixultimate/js/main.js"></script>
  <script src="/media/jui/js/chosen.jquery.min.js?6357188fe7a64624969d58a72a53bd73"></script>
  <script src="/media/system/js/core.js?6357188fe7a64624969d58a72a53bd73"></script>
  <script>
    ; (function ($) {
      $.ajaxSetup({
        headers: {
          'X-CSRF-Token': Joomla.getOptions('csrf.token')
        }
      });
      template = "shaper_helixultimate";
      jQuery(function ($) {
        initChosen();
        $("body").on("subform-row-add", initChosen);

        function initChosen (event, container) {
          container = container || document;
          $(container).find(".advancedSelect").chosen({ "disable_search_threshold": 10, "search_contains": true, "allow_single_deselect": true, "placeholder_text_multiple": "\u3044\u304f\u3064\u304b\u306e\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u5165\u529b\u307e\u305f\u306f\u9078\u629e", "placeholder_text_single": "\u30aa\u30d7\u30b7\u30e7\u30f3\u3092\u9078\u629e", "no_results_text": "\u4e00\u81f4\u3059\u308b\u3082\u306e\u306f\u3042\u308a\u307e\u305b\u3093" });
        }
      });

  </script>
</head>

<body
  class="site helix-ultimate hu com-content view-article layout-blog task-none itemid-207 ja-jp ltr sticky-header layout-fluid offcanvas-init offcanvs-position-left">

  <div class="body-wrapper">
    <div class="body-innerwrapper">

      <div class="sticky-header-placeholder"></div>
      <header id="sp-header" class="header-with-social">
        <div class="container">
          <div class="container-inner">
            <div class="row">
              
              <div id="sp-logo" class="has-border col-auto">
                <div class="sp-column">

                  <a id="offcanvas-toggler" aria-label="Menu" class="offcanvas-toggler-left d-flex align-items-center" href="#"
                    aria-hidden="true" title="Menu">
                    <div class="burger-icon"><span></span><span></span><span></span></div>
                  </a><span class="logo"><a href="/">Sparticle</a></span>
                </div>
              </div>

              
              <div id="sp-menu" class="menu-with-social col-auto flex-auto">
                <div class="sp-column d-flex justify-content-between align-items-center">
                  <div class="d-flex menu-wrap menu-with-offcanvas justify-content-between align-items-center flex-auto">
                    <nav class="sp-megamenu-wrapper d-flex" role="navigation">
                      <ul class="sp-megamenu-parent menu-animation-fade d-none d-lg-block">
                        <li class="sp-menu-item sp-has-child"><a href="#">サービス</a>
                          <div class="sp-dropdown sp-dropdown-main sp-menu-right" style="width: 180px;">
                            <div class="sp-dropdown-inner">
                              <ul class="sp-dropdown-items">
                                <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://glarity.app/ja-JP"
                                    target="_blank">Glarityとは</a></li>
                                <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://gptbase.ai/"
                                    target="_blank">GPTBaseとは</a></li>
                                <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://felo.me/ja-JP/home"
                                    target="_blank">Feloとは</a></li>
                                <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://circleo.me/"
                                    target="_blank">CircleOとは</a></li>
                                <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://teamgpt.me/"
                                    target="_blank">TeamGPTとは</a></li>
                              </ul>
                            </div>
                          </div>
                        </li>
                        <li class="sp-menu-item"></li>
                        <li class="sp-menu-item"><a rel="noopener noreferrer" href="/ja/blog-jp" target="_blank">ブログ</a></li>
                        <li class="sp-menu-item"><a rel="noopener noreferrer" href="https://felo.me/contact"
                            target="_blank">問い合わせ</a></li>
                        <li class="sp-menu-item"><a rel="noopener noreferrer" href="/ja/security" target="_blank">セキュリティー</a></li>
                      </ul>
                    </nav>
                    <div class="sp-module ">
                      <div class="sp-module-content">
                        <div class="mod-languages">

                          <form name="lang" method="post" action="https://www.sparticle.com/ja/blog-jp-2/ai-gptbase-ai">
                            <select class="inputbox advancedSelect" onchange="document.location.replace(this.value);">
                              <option dir="ltr" value="/ja/blog-jp-2/ai-gptbase-ai" selected="selected">
                                日本語</option>
                              <option dir="ltr" value="/en-us/">
                                English</option>
                            </select>
                          </form>

                        </div>
                      </div>
                    </div>
                  </div>

                  
                  <div class="d-none d-lg-flex header-modules align-items-center">

                  </div>

                  
                  

                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <section id="sp-page-title">

        <div class="row">
          <div id="sp-title" class="col-lg-12 ">
            <div class="sp-column ">
              <div class="sp-page-title">
                <div class="container">
                  <h2 class="sp-page-title-heading">ブログ</h2>
                </div>
              </div>
            </div>
          </div>
        </div>

      </section>
      <section id="sp-main-body">

        <div class="container">
          <div class="container-inner">

            <div class="row">

              <main id="sp-component" class="col-lg-12 ">
                <div class="sp-column ">
                  <div id="system-message-container" aria-live="polite">
                  </div>

                  <div class="article-details " itemscope itemtype="https://schema.org/Article">
                    <meta itemprop="inLanguage" content="ja-JP">

                    <div class="article-full-image">
                      <img src="/images/2023/06/05/WechatIMG297.jpeg" alt="AI時代の革命者：GPTBaseがこれからの、日本のAIアシスタントサービス市場を変える！"
                        itemprop="image">
                    </div>

                    <div class="article-header">
                      <h1 itemprop="headline">
                        AI時代の革命者：GPTBaseがこれからの、日本のAIアシスタントサービス市場を変える！</h1>
                    </div>
                    <div class="article-can-edit d-flex flex-wrap justify-content-between">
                    </div>
                    <div class="article-info">

                      <span class="category-name" title="カテゴリ: Blog">
                        <a href="/ja/blog-jp-2">Blog</a>
                      </span>

                      <span class="published" title="公開日:2023年06月05日">
                        <time datetime="2023-06-05T17:03:55+09:00" itemprop="datePublished">
                          2023年06月05日 </time>
                      </span>

                      <span class="hits">
                        <meta itemprop="interactionCount" content="UserPageVisits:166">
                        参照数: 166
                      </span>
                    </div>

                    <div class="article-ratings-social-share d-flex justify-content-end">
                      <div class="me-auto align-self-center">
                        <div class="article-ratings" data-id="37">
                          <span class="ratings-label">Ratings</span>
                          <div class="rating-symbol">
                            <span class="rating-star" data-number="5"></span><span class="rating-star"
                              data-number="4"></span><span class="rating-star" data-number="3"></span><span class="rating-star"
                              data-number="2"></span><span class="rating-star" data-number="1"></span>
                          </div>
                          <span class="fas fa-circle-notch fa-spin" aria-hidden="true" style="display: none;"></span>
                          <span class="ratings-count">(0)</span>
                        </div>
                      </div>
                      <div>
                      </div>
                    </div>

                    <div itemprop="articleBody">
                      <p class="release--sub_title">Aiチャットボット2.0：GPTBase</p>

                      <div class="release--info_wrapper">
                        <div class="information-release"> </div>
                        <div class="information-release">
                          GPTBaseの開発者で、またSparticle株式会社の代表でもある金田は、世界有数の大手ITテクノロジー企業で長年経験を積んだ後、その豊富な経験と専門知識を元に、2019年に自身の会社を創業。この度、独自の戦略とGPT技術を組み合わせた革新的なAIチャットボット（以下AIアシスタントサービス）である【GPTBase】のサービスを開始致しました。
                        </div>
                      </div>
                      <div class="release--info_wrapper">
                        <div class="inner">
                          <div class="rbody">
                            <div class="r-head">この度、【GPTBase】(<a href="https://gptbase.ai/)" target="_blank"
                                rel="nofollow ugc noopener noreferrer">https://gptbase.ai/)</a>が、東京を拠点とするAIスタートアップ企業Sparticle株式会社（<a
                                href="/ja" target="_blank"
                                rel="nofollow ugc noopener noreferrer">https://www.sparticle.com/ja</a>）により開発されました。</div>
                            <div class="r-text clearfix">
                              <div class="rich-text">
                                <p id="p-iframe-image-869b3772-6e5a-4d8a-9e9d-476acb2bb979"><span
                                    class="text-image-caption clearfix editor-image center"><img
                                      src="https://prcdn.freetls.fastly.net/release_image/87269/15/87269-15-1c1fb31dd43ba2c9385ca957d0888dd4-940x906.jpg?format=jpeg&auto=webp&quality=85%2C65&width=1950&height=1350&fit=bounds"
                                      alt width="1012" height="975"></span></p>
                                <ul>
                                  <li>
                                    <p>【GPTBase】は、GPT技術特有の強みを利用し、ユーザー独自のデータを活用した、AIアシスタントサービスを提供するものです。</p>
                                  </li>
                                  <li>
                                    <p>【GPTBase】の利用者は企業ユーザーのみに限定されず、一般の個人ユーザーやブログの開設者等も、簡単に自身のウェブサイトにAIアシスタントサービスを組み込むことができます。</p>
                                  </li>
                                  <li>
                                    <p>これにより、ウェブサイトの訪問者の滞在時間が大幅に向上し、UXを向上させることが可能です。</p>
                                  </li>
                                  <li>
                                    <p>
                                      【GPTBase】のポイントは、単なる質疑応答のチャットボットにとどまらず、ウェブサイトの公開情報や追加のバックエンドで提供されるドキュメントなども含め、事前に提出されたすべての情報に基づいて、GPTのAI技術活用により言語を再構成し、訪問者により自然で、よりリアルな、AIアシスタントサービスを提供できるという点です。
                                    </p>
                                  </li>
                                </ul>
                                <p>GPTBaseのより自然なコミュニケーションの提供は、これまでにない新たな体験といっても過言ではないでしょう。</p>
                                <p>この【GPTBase】は、すでに日本の市場でサービスが展開されており、高い評価を受けています。</p>
                                <p>
                                  シリコンバレーにも類似の製品がありますが、日本市場には見合っていないという現状があります。その点【GPTBase】は日本市場のニーズを把握し、開発されたものであるため、日本のAIアシスタント市場に確信をもたらすことができるでしょう。
                                </p>
                                <p id="p-iframe-image-8f0eff8e-741d-47df-aaf3-7acc04306f1c"><span
                                    class="text-image-caption clearfix editor-image center"><img
                                      src="https://prcdn.freetls.fastly.net/release_image/87269/15/87269-15-2fa6af650a14be0fbd6018de42f9455a-2880x1408.png?format=jpeg&auto=webp&quality=85%2C65&width=1950&height=1350&fit=bounds"
                                      alt width="1013" height="495"></span></p>
                                <p>
                                  また、弊社所有の卓越した技術力と市場への深い理解の甲斐もあり、現在、【GPTBase】は日本市場だけでなく、世界からも注目を集めております。小売業、電子商取引、金融業など<strong>100以上の企業</strong>がGPTBaseのサービスを利用し始めています。
                                </p>
                                <p>
                                  実際に、その優れたパフォーマンスは日本のみならず、シンガポール、そして遠く離れたアメリカまで広がっております。世界のベンチャーキャピタル（VC）機関も、大きな関心を寄せており、弊社の起業理念でもある「技術によるサービス革新」は、世界中で共感を呼んでいます。
                                </p>
                                <p> </p>
                                <p>
                                  また、代表の金田は、「今後の展望としては、【GPTBase】をさらに多くの日本企業に提供し、日本の企業と一般の人々が最新のAI技術による高品質なサービスを手軽に享受できるようになることで、日本社会全体の情報化のプロセスを促進したい」と語っています。
                                </p>
                                <p> </p>
                                <p>
                                  今後もSparticle株式会社は、2023年に入り動き始めた人工知能の大きな波の中で、【GPTBase】を広く普及させルことで、日本そして世界の企業を牽引する企業となるべく邁進していきます。<br><br>GPTBase公式アカウント
                                </p>
                                <p><a href="https://twitter.com/FeloApp" target="_blank"
                                    rel="nofollow ugc noopener noreferrer">https://twitter.com/FeloApp</a><br><br>GPTBase
                                  Community</p>
                                <p><a href="https://discord.gg/AHchujpkf6" target="_blank"
                                    rel="nofollow ugc noopener noreferrer">https://discord.gg/AHchujpkf6</a></p>
                              </div>
                            </div>
                          </div>
                          <div class="releasefooter">
                            <div class="media-only-box">
                              <div class="mlimit-msg">
                                <br>【本件に関する報道関係者からのお問合せ先】<br>Sparticle株式会社　<br>広報担当：山田<br>電話：03-3527-2828　<br>メールアドレス：<span
                                  id="cloak3d3fe89492a45e8ed46aa5dd770b2a83">このメールアドレスはスパムボットから保護されています。閲覧するにはJavaScriptを有効にする必要があります。</span>
                                <script type="text/javascript">
  document.getElementById('cloak3d3fe89492a45e8ed46aa5dd770b2a83').innerHTML = '';
  var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
  var path = 'hr' + 'ef' + '=';
  var addy3d3fe89492a45e8ed46aa5dd770b2a83 = 's&#117;pp&#111;rt' + '&#64;';
  addy3d3fe89492a45e8ed46aa5dd770b2a83 = addy3d3fe89492a45e8ed46aa5dd770b2a83 + 'sp&#97;rt&#105;cl&#101;' + '&#46;' + 'c&#111;m';
  var addy_text3d3fe89492a45e8ed46aa5dd770b2a83 = 's&#117;pp&#111;rt' + '&#64;' + 'sp&#97;rt&#105;cl&#101;' + '&#46;' + 'c&#111;m'; document.getElementById('cloak3d3fe89492a45e8ed46aa5dd770b2a83').innerHTML += '<a ' + path + '\'' + prefix + ':' + addy3d3fe89492a45e8ed46aa5dd770b2a83 + '\'>' + addy_text3d3fe89492a45e8ed46aa5dd770b2a83 + '<\/a>';
                                </script>　
                              </div>
                            </div>
                            <div class="pos-rela"> </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <ul class="pager pagenav">
                      <li class="previous">
                        <a class="hasTooltip" title="[Felo Translator] - リーダーが実践している、言葉の壁をなくすための４つの特徴"
                          aria-label="前の記事へ: [Felo Translator] - リーダーが実践している、言葉の壁をなくすための４つの特徴"
                          href="/ja/blog-jp-2/felo-translator" rel="prev">
                          <span class="icon-chevron-left" aria-hidden="true"></span> <span aria-hidden="true">前へ</span> </a>
                      </li>
                      <li class="next">
                        <a class="hasTooltip" title="リアルなオフィス体験をオンラインで！CircleOが提供する次世代コミュニケーションツール"
                          aria-label="次の記事へ: リアルなオフィス体験をオンラインで！CircleOが提供する次世代コミュニケーションツール" href="/ja/blog-jp-2/circleo"
                          rel="next">
                          <span aria-hidden="true">次へ</span> <span class="icon-chevron-right" aria-hidden="true"></span> </a>
                      </li>
                    </ul>

                  </div>

                </div>
              </main>
            </div>
          </div>
        </div>

      </section>
      <footer id="sp-footer">

        <div class="container">
          <div class="container-inner">

            <div class="row">
              <div id="sp-footer1" class="col-lg-6 ">
                <div class="sp-column "><span class="sp-copyright">Copyright © 2023 Sparticle株式会社 - All Rights Reserved.</span>
                </div>
              </div>
              <div id="sp-footer2" class="col-lg-6 ">
                <div class="sp-column ">
                  <ul class="social-icons">
                    <li class="social-icon-facebook"><a target="_blank" rel="noopener noreferrer"
                        href="https://www.facebook.com/groups/136775538422596/" aria-label="Facebook"><span
                          class="fab fa-facebook" aria-hidden="true"></span></a></li>
                    <li class="social-icon-twitter"><a target="_blank" rel="noopener noreferrer"
                        href="https://twitter.com/FeloApp" aria-label="Twitter"><span class="fab fa-twitter"
                          aria-hidden="true"></span></a></li>
                    <li class="social-icon-youtube"><a target="_blank" rel="noopener noreferrer"
                        href="https://www.youtube.com/channel/UC3_iFnHLJAnJMo99NOAtnpQ" aria-label="Youtube"><span
                          class="fab fa-youtube" aria-hidden="true"></span></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

      </footer>
    </div>
  </div>

  
  <div class="offcanvas-overlay"></div>
  
  
  
  <div class="offcanvas-menu">
    <div class="d-flex align-items-center p-3 pt-4">
      <a id="offcanvas-toggler" aria-label="Menu" class="offcanvas-toggler-left d-flex align-items-center" href="#"
        aria-hidden="true" title="Menu">
        <div class="burger-icon"><span></span><span></span><span></span></div>
      </a><span class="logo"><a href="/">Sparticle</a></span> <a href="#" class="close-offcanvas" aria-label="Close Off-canvas">
        <div class="burger-icon">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </a>
    </div>
    <div class="offcanvas-inner">
      <div class="d-flex header-modules mb-3">

      </div>

      <div class="sp-module ">
        <div class="sp-module-content">
          <ul class="menu">
            <li class="item-199 default"><a href="/ja/" target="_blank">ホーム</a></li>
            <li class="item-200 menu-deeper menu-parent"><a href="#">サービス<span class="menu-toggler"></span></a>
              <ul class="menu-child">
                <li class="item-219"><a href="https://glarity.app/ja-JP" target="_blank" rel="noopener noreferrer">Glarityとは</a>
                </li>
                <li class="item-220"><a href="https://gptbase.ai/" target="_blank" rel="noopener noreferrer">GPTBaseとは</a></li>
                <li class="item-221"><a href="https://felo.me/ja-JP/home" target="_blank" rel="noopener noreferrer">Feloとは</a>
                </li>
                <li class="item-222"><a href="https://circleo.me/ja" target="_blank" rel="noopener noreferrer">CircleOとは</a></li>
                <li class="item-223"><a href="https://teamgpt.me/" target="_blank" rel="noopener noreferrer">TeamGPTとは</a></li>
              </ul>
            </li>
            <li class="item-207 current"><a href="/ja/blog-jp-2">ブログ</a></li>
            <li class="item-208"><a href="https://felo.me/contact" target="_blank" rel="noopener noreferrer">問い合わせ</a></li>
          </ul>
        </div>
      </div>

      <div class="mb-4">
        <ul class="sp-contact-info">
          <li class="sp-contact-phone"><span class="fas fa-phone" aria-hidden="true"></span> <a
              href="tel:+810335272828">+81-03-3527-2828</a></li>
          <li class="sp-contact-email"><span class="far fa-envelope" aria-hidden="true"></span> <a
              href="/cdn-cgi/l/email-protection#12616762627d60665261627360667b717e773c717d7f"><span class="__cf_email__"
                data-cfemail="64171114140b16102417140516100d0708014a070b09">[email protected]</span></a></li>
        </ul>
      </div>

      <ul class="social-icons">
        <li class="social-icon-facebook"><a target="_blank" rel="noopener noreferrer"
            href="https://www.facebook.com/groups/136775538422596/" aria-label="Facebook"><span class="fab fa-facebook"
              aria-hidden="true"></span></a></li>
        <li class="social-icon-twitter"><a target="_blank" rel="noopener noreferrer" href="https://twitter.com/FeloApp"
            aria-label="Twitter"><span class="fab fa-twitter" aria-hidden="true"></span></a></li>
        <li class="social-icon-youtube"><a target="_blank" rel="noopener noreferrer"
            href="https://www.youtube.com/channel/UC3_iFnHLJAnJMo99NOAtnpQ" aria-label="Youtube"><span class="fab fa-youtube"
              aria-hidden="true"></span></a></li>
      </ul>
    </div>
  </div>

  

  <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
  <script>
      console.log('test');      
  </script>
</body>
</html>`;

import { Readability } from 'readability';
import { JSDOM } from 'jsdom';
var doc = new JSDOM(html, {
  url: 'https://www.example.com/the-page-i-got-the-source-from',
});
let reader = new Readability(doc.window.document);
let article = reader.parse();
console.log('article', article);

  </code></pre>
</details>

### What is the expected behavior?

no segmentation fault, and will print like this:
```
article {
  title: "",
  byline: null,
  dir: null,
  lang: null,
  content: ".......",
  textContent: ".......",
  excerpt: undefined,
  siteName: null
}
```

### What do you see instead?

⇒  bun run parser.js
[1]    51078 segmentation fault  bun run parser.js

or

⇒  bun run parser.js
[1]    51197 segmentation fault  bun run parser.js

**Comment by birkskyum** [comment]
I don't get a segfault with bun 0.8, but I do get this:

```
⇣9% ➜ bun index.js
[0.08ms] ".env"
2218 | if (!jsdom.applyDocumentFeatures)
2219 | (function() {
2220 |  //hack for older versions of jsdom when features can't be disabled by API
2221 |  var core = jsdom.defaultLevel;
2222 |  //disable loading frames
2223 |  delete core.HTMLFrameElement.prototype.setAttribute;
            ^
TypeError: undefined is not an object (evaluating 'core.HTMLFrameElement')
      at /Users/admin/repos/bun-node-tty/node_modules/readability/lib/readability.js:2223:8
      at /Users/admin/repos/bun-node-tty/node_modules/readability/lib/readability.js:2226:41
      at globalThis (/Users/admin/repos/bun-node-tty/node_modules/readability/lib/readability.js:2229:18)
```

**Comment by Hanaasagi** [comment]
This segmentation fault can be reproduced on Linux.

```
uh-oh: access of union field 'path' while field 'fd' is active
```


#### coredump stack

```
(gdb) bt
#0  0x00007ff654c8e83c in ?? () from /usr/lib/libc.so.6
#1  0x00007ff654c3e668 in raise () from /usr/lib/libc.so.6
#2  0x00007ff654c26542 in abort () from /usr/lib/libc.so.6
#3  0x000056473912c6e9 in os.abort () at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/os.zig:598
#4  0x00005647391283f4 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/debug.zig:440
#5  0x0000564739127114 in src.main.panic (msg=..., error_return_trace=0x0, addr=...) at /home/kumiko/zig/bun/src/main.zig:88
#6  0x000056473960d267 in debug.panicExtra__anon_102135 (trace=0x0, ret_addr=..., args=...) at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/debug.zig:373
#7  0x00005647397839b5 in builtin.panicInactiveUnionField__anon_127017 (active=fd, wanted=path) at /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.163+6780a6bbf/lib/std/builtin.zig:846
#8  0x0000564739aa0c84 in Blob__estimatedSize (this=0x25a16efbc40) at /home/kumiko/zig/bun/src/bun.js/webcore/blob.zig:1257
#9  0x0000564738f982c0 in Blob__create (globalObject=<optimized out>, ptr=0x25a16efbc40) at src/bun.js/bindings/ZigGeneratedClasses.cpp:1874
#10 0x0000564739aa4612 in src.bun.js.bindings.generated_classes.JSBlob.toJS (this=0x25a16efbc40, globalObject=0x7ff6094c4068) at /home/kumiko/zig/bun/src/bun.js/bindings/generated_classes.zig:442
#11 0x0000564739b5e22a in BunObject_callback_file (globalObject=0x7ff6094c4068, callframe=0x7fff51c21f10) at /home/kumiko/zig/bun/src/bun.js/webcore/blob.zig:1297
#12 0x00007ff60a4081b8 in ?? ()
#13 0x00007fff51c22010 in ?? ()
#14 0x0000564737f73883 in js_trampoline_op_call ()
#15 0x0000000000000000 in ?? ()

```

#### Related code

https://github.com/oven-sh/bun/blob/e1dacf88d0778fb9f2aa6932dcc67f9980e03265/src/bun.js/webcore/blob.zig#L1257

**Comment by Jarred-Sumner** [comment]
@Hanaasagi that is a different error and is fixed in @Electroid's branch which we will merge soon

**Comment by Electroid** [comment]
The root issue here has been fixed.
