### ISSUE TITLE
Protocol Mismatch error in bun 

### ISSUE THREAD

**Issue by VrindavanSanap** [oven-sh/bun#3340]
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

import { YoutubeTranscript } from 'youtube-transcript';
YoutubeTranscript.fetchTranscript("PaCmpygFfXo").then(console.log)

### What is the expected behavior?

vrindavan@Vrindavans-MBP text500 % node bun_issue.js
[
  { text: "hi everyone hope you're well", duration: 3840, offset: 240 },
  {
    text: "and next up what i'd like to do is i'd",
    duration: 3920,
    offset: 2240
  },
  { text: 'like to build out make more', duration: 4479, offset: 4080 },
  {
    text: 'like micrograd before it make more is a',
    duration: 4080,
    offset: 6160
  },
  {
    text: 'repository that i have on my github',
    duration: 2801,
    offset: 8559
  },
  { text: 'webpage', duration: 2399, offset: 10240 },
  { text: 'you can look at it', duration: 3040, offset: 11360 },
  {
    text: "but just like with micrograd i'm going",
    duration: 3681,
    offset: 12639
  },
  {
    text: "to build it out step by step and i'm",
    duration: 3520,
    offset: 14400
  },
  {
    text: "going to spell everything out so we're",
    duration: 2719,
    offset: 16320
  },
  {
    text: 'going to build it out slowly and',
    duration: 2320,
    offset: 17920
  },
  { text: 'together', duration: 3121, offset: 19039 },
  { text: 'now what is make more', duration: 4320, offset: 20240 },
  {
    text: 'make more as the name suggests',
    duration: 5359,
    offset: 22160
  },
  {
    text: 'makes more of things that you give it',
    duration: 4479,
    offset: 24560
  },
  { text: "so here's an example", duration: 4000, offset: 27519 },
  {
    text: 'names.txt is an example dataset to make',
    duration: 3441,
    offset: 29039
  },
  { text: 'more', duration: 2880, offset: 31519 },
  {
    text: "and when you look at names.txt you'll",
    duration: 4320,
    offset: 32480
  },
  {
    text: "find that it's a very large data set of",
    duration: 3761,
    offset: 34399
  },
  { text: 'names', duration: 3360, offset: 36800 },
  { text: 'so', duration: 3520, offset: 38160 },
  {
    text: "here's lots of different types of names",
    duration: 4000,
    offset: 40160
  },
  {
    text: 'in fact i believe there are 32 000 names',
    duration: 4399,
    offset: 41680
  },
  {
    text: "that i've sort of found randomly on the",
    duration: 3680,
    offset: 44160
  },
  { text: 'government website', duration: 4000, offset: 46079 },
  {
    text: 'and if you train make more on this data',
    duration: 5359,
    offset: 47840
  },
  {
    text: 'set it will learn to make more of things',
    duration: 5201,
    offset: 50079
  },
  { text: 'like this', duration: 4401, offset: 53199 },
  {
    text: 'and in particular in this case that will',
    duration: 5040,
    offset: 55280
  },
  {
    text: 'mean more things that sound name-like',
    duration: 4720,
    offset: 57600
  },
  {
    text: 'but are actually unique names',
    duration: 3520,
    offset: 60320
  },
  {
    text: "and maybe if you have a baby and you're",
    duration: 2960,
    offset: 62320
  },
  {
    text: "trying to assign name maybe you're",
    duration: 3200,
    offset: 63840
  },
  {
    text: 'looking for a cool new sounding unique',
    duration: 4240,
    offset: 65280
  },
  {
    text: 'name make more might help you',
    duration: 4240,
    offset: 67040
  },
  {
    text: 'so here are some example generations',
    duration: 3840,
    offset: 69520
  },
  { text: 'from the neural network', duration: 4879, offset: 71280 },
  {
    text: 'once we train it on our data set',
    duration: 4399,
    offset: 73360
  },
  { text: "so here's some example", duration: 3521, offset: 76159 },
  {
    text: 'unique names that it will generate',
    duration: 3921,
    offset: 77759
  },
  { text: 'dontel', duration: 3759, offset: 79680 },
  { text: 'irot', duration: 2799, offset: 81680 },
  { text: 'zhendi', duration: 3521, offset: 83439 },
  {
    text: 'and so on and so all these are sound',
    duration: 4401,
    offset: 84479
  },
  {
    text: "name like but they're not of course",
    duration: 3680,
    offset: 86960
  },
  { text: 'names', duration: 4000, offset: 88880 },
  {
    text: 'so under the hood make more is a',
    duration: 4560,
    offset: 90640
  },
  {
    text: 'character level language model so what',
    duration: 4400,
    offset: 92880
  },
  {
    text: 'that means is that it is treating every',
    duration: 4480,
    offset: 95200
  },
  {
    text: 'single line here as an example and',
    duration: 4799,
    offset: 97280
  },
  {
    text: "within each example it's treating them",
    duration: 4320,
    offset: 99680
  },
  {
    text: 'all as sequences of individual',
    duration: 6801,
    offset: 102079
  },
  {
    text: 'characters so r e e s e is this example',
    duration: 6560,
    offset: 104000
  },
  {
    text: "and that's the sequence of characters",
    duration: 2960,
    offset: 108880
  },
  {
    text: "and that's the level on which we are",
    duration: 4239,
    offset: 110560
  },
  {
    text: 'building out make more and what it means',
    duration: 4639,
    offset: 111840
  },
  {
    text: 'to be a character level language model',
    duration: 3600,
    offset: 114799
  },
  {
    text: "then is that it's just uh sort of",
    duration: 3441,
    offset: 116479
  },
  {
    text: 'modeling those sequences of characters',
    duration: 2961,
    offset: 118399
  },
  {
    text: 'and it knows how to predict the next',
    duration: 3680,
    offset: 119920
  },
  { text: 'character in the sequence', duration: 3920, offset: 121360 },
  {
    text: "now we're actually going to implement a",
    duration: 3839,
    offset: 123600
  },
  {
    text: 'large number of character level language',
    duration: 3920,
    offset: 125280
  },
  {
    text: 'models in terms of the neural networks',
    duration: 3440,
    offset: 127439
  },
  {
    text: 'that are involved in predicting the next',
    duration: 4240,
    offset: 129200
  },
  {
    text: 'character in a sequence so very simple',
    duration: 4401,
    offset: 130879
  },
  {
    text: 'bi-gram and back of work models',
    duration: 3680,
    offset: 133440
  },
  {
    text: 'multilingual perceptrons recurrent',
    duration: 4319,
    offset: 135280
  },
  {
    text: 'neural networks all the way to modern',
    duration: 4560,
    offset: 137120
  },
  {
    text: 'transformers in fact the transformer',
    duration: 4080,
    offset: 139599
  },
  {
    text: 'that we will build will be basically the',
    duration: 4559,
    offset: 141680
  },
  {
    text: 'equivalent transformer to gpt2 if you',
    duration: 4960,
    offset: 143680
  },
  {
    text: "have heard of gpt uh so that's kind of a",
    duration: 4640,
    offset: 146239
  },
  {
    text: "big deal it's a modern network and by",
    duration: 3920,
    offset: 148640
  },
  {
    text: 'the end of the series you will actually',
    duration: 3761,
    offset: 150879
  },
  {
    text: 'understand how that works um on the',
    duration: 4240,
    offset: 152560
  },
  {
    text: 'level of characters now to give you a',
    duration: 5200,
    offset: 154640
  },
  {
    text: 'sense of the extensions here uh after',
    duration: 4640,
    offset: 156800
  },
  {
    text: 'characters we will probably spend some',
    duration: 3440,
    offset: 159840
  },
  {
    text: 'time on the word level so that we can',
    duration: 3600,
    offset: 161440
  },
  {
    text: 'generate documents of words not just',
    duration: 4239,
    offset: 163280
  },
  {
    text: 'little you know segments of characters',
    duration: 4400,
    offset: 165040
  },
  {
    text: 'but we can generate entire large much',
    duration: 3440,
    offset: 167519
  },
  { text: 'larger documents', duration: 2879, offset: 169440 },
  {
    text: "and then we're probably going to go into",
    duration: 3681,
    offset: 170959
  },
  { text: 'images and image text', duration: 4721, offset: 172319 },
  {
    text: 'networks such as dolly stable diffusion',
    duration: 5360,
    offset: 174640
  },
  {
    text: 'and so on but for now we have to start',
    duration: 5119,
    offset: 177040
  },
  {
    text: 'here character level language modeling',
    duration: 3360,
    offset: 180000
  },
  { text: "let's go", duration: 2641, offset: 182159 },
  {
    text: 'so like before we are starting with a',
    duration: 3599,
    offset: 183360
  },
  {
    text: 'completely blank jupiter notebook page',
    duration: 3760,
    offset: 184800
  },
  {
    text: 'the first thing is i would like to',
    duration: 4801,
    offset: 186959
  },
  {
    text: 'basically load up the dataset names.txt',
    duration: 5280,
    offset: 188560
  },
  {
    text: "so we're going to open up names.txt for",
    duration: 3600,
    offset: 191760
  },
  { text: 'reading', duration: 3520, offset: 193840 },
  {
    text: "and we're going to read in everything",
    duration: 4400,
    offset: 195360
  },
  { text: 'into a massive string', duration: 4000, offset: 197360 },
  {
    text: "and then because it's a massive string",
    duration: 3360,
    offset: 199760
  },
  ... 3265 more items
]

### What do you see instead?

vrindavan@Vrindavans-MBP text500 % bun bun_issue.js 
60 |                     if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
61 |                     if (t[2]) _.ops.pop();
62 |                     _.trys.pop(); continue;
63 |             }
64 |             op = body.call(thisArg, _);
65 |         } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
                                       ^
error: [YoutubeTranscript] 🚨 Error: Protocol mismatch. Expected: http:. Got: https:
      at new YoutubeTranscriptError (/Users/vrindavan/Code/text500/node_modules/youtube-transcript/dist/youtube-transcript.esm.js:65:35)
      at /Users/vrindavan/Code/text500/node_modules/youtube-transcript/dist/youtube-transcript.esm.js:121:28
      at step (/Users/vrindavan/Code/text500/node_modules/youtube-transcript/dist/youtube-transcript.esm.js:59:73)
      at rejected (/Users/vrindavan/Code/text500/node_modules/youtube-transcript/dist/youtube-transcript.esm.js:33:91)
vrindavan@Vrindavans-MBP text500 % 

### Additional information

Jared said "Can you file an issue in bun’s repo? Probably a bug in our node:http"

**Comment by VrindavanSanap** [comment]
More simpler way to recreate the bug is 
import p from 'phin'
const res = await p('https://ethanent.me')

console.log(res.body)

node works fine breaks with bun

**Comment by simylein** [comment]
Have you tried with the latest version of bun? `bun upgrade` or they way your package manager does it.

**Comment by VrindavanSanap** [comment]
"bun v0.6.9 is out! You're on 0.5.7" Yup it works now😃

**Comment by simylein** [comment]
You may wanna close the issue 😉
