### ISSUE TITLE
`ws.publish` doesn't work when `ws` is not subscribed itself.

### ISSUE THREAD

**Issue by arguiot** [oven-sh/bun#3353]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

If we have two connections opened, one listening to a topic X, and another connection sending data to the server. If WS 2 calls `.publish` without being subscribed, WS 1 will not receive anything.

### What is the expected behavior?

WS 1 should receive what's being published.

### What do you see instead?

Nothing.

**Comment by Jarred-Sumner** [comment]
Use `server.publish()` instead of `ws.publish`

`ws.publish` by default publishes to everyone else. `server.publish` publishes to all.

**Comment by arguiot** [comment]
Yes, but it's still a bug though. `ws.publish` should publish to everyone else, as you said.

**Comment by Jarred-Sumner** [comment]
[Not a bug, a change we made](https://bun.sh/blog/bun-v0.6.3#breaking-change-to-publishtoself-behaviour) after several reports that publishing to self by default was confusing.

To bring back the previous behavior, `publishToSelf: true` in `websocket`

**Comment by Jarred-Sumner** [comment]
maybe it'd be less confusing if the name was "broadcast" instead of "publish" because broadcasting sort of implies not broadcasting to self

**Comment by Jarred-Sumner** [comment]
If you’re still having trouble lmk
