### ISSUE TITLE
Node is ~30% faster than bun at an algorithm

### ISSUE THREAD

**Issue by dimka3553** [oven-sh/bun#3358]
### What version of Bun is running?

0.6.9

### What platform is your computer?

M1 MacBook Pro -> Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

This code:
```js
var appendDelay = 1;
var chartLen = 10;
var delaysSoFar = 0;
var arr = [0];

function update(x) {
  if (arr.length < chartLen) {
    if (delaysSoFar == appendDelay) {
      arr.push(x);
      delaysSoFar = 0;
    } else {
      arr[arr.length - 1] = x;
    }
    delaysSoFar += 1;
  }

  if (arr.length == chartLen) {
    for (var i = 0; i < 10; i += 2) {
      arr[i / 2] = arr[i];
    }
    arr.length = 5;

    appendDelay *= 2;
    arr.push(x);
  }
}

const now = performance.now();
for (var i = 0; i < 1000000000; i++) {
  update(i);
}
console.log(performance.now() - now);

console.log(arr);
```

### What is the expected behavior?

For bun to be faster

### What do you see instead?

bun is slower

### Additional information

<img width="701" alt="Screenshot_2023-06-10_at_21 25 25" src="https://github.com/oven-sh/bun/assets/37512400/e2973045-6047-4364-983c-d3ae1c791688">

**Comment by Jarred-Sumner** [comment]
If you run into performance issues with real code in your application feel free to file an issue 

This looks more like a microbenchmark. JS engines are really good at optimizing microbenchmarks with statically known data. It probably isn't meaningful in applications.
