### ISSUE TITLE
`fs.readdir` or stack trace seg fault

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3364]
### What version of Bun is running?

0.6.10

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

I'm working on a reproduction but it's tricky.

I am reading all `package.json` files in a large monorepo using the `fdir` package. When using the `recursive-fs` package it also happens. I can't replicate the issue when running from a simple script.

It seems to happen while the web server is running.

I saw this stack trace served from a web server error at one point:

<img width="520" alt="Screenshot 2023-06-19 at 7 50 33 pm" src="https://github.com/oven-sh/bun/assets/281413/2ffcfc89-6200-42ed-89fe-13087f76e7c2">

And when I log the `fs.readdir` calls, I saw this sometimes before the segfault:

<img width="659" alt="Screenshot 2023-06-20 at 11 55 19 am" src="https://github.com/oven-sh/bun/assets/281413/5b805a7b-c554-4ea8-8e77-d11a45d662ce">

**Comment by Jarred-Sumner** [comment]
This is in the canary build newer than 2 days ago?

**Comment by vjpr** [comment]
Canary as of right now...but I was getting sporadic errors before I updated today too.

**Comment by Jarred-Sumner** [comment]
Oh it’s the stack trace. I’ll have a fix tomorrow

**Comment by Jarred-Sumner** [comment]
We just need to clone the source origin URL. see the garbled text in the stack trace file names? That’s probably the cause

**Comment by vjpr** [comment]
It's so lucky I took that screenshot...I only saw it once by chance 😅

**Comment by vjpr** [comment]
Any chance to look at this? I'm getting segfaults all over the place right now.

I'm going to start trying to debug this today.

**Comment by Jarred-Sumner** [comment]
I'm going to go ahead and merge a branch that will likely address this, though not all segfaults related to this are fixed yet

**Comment by vjpr** [comment]
Fixed by https://github.com/oven-sh/bun/compare/2ab797ff75e640e8f398b2ae003195398403d96b...main
