### ISSUE TITLE
Can't run art-template

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#3375]
### What version of Bun is running?

0.6.9

### What platform is your computer?

mac m1 max

### What steps can reproduce the bug?

```js
var express = require('express');
var template = require('art-template');

const app = express();
const port = 4000;

app.get('/', function (req, res) {
  const html = template('templates/home.art', { message: 'Yeshua loves everybody' });
  res.send(html);
});

app.listen(port, () => {
  console.log(`App listening at http://localhost:${port}`);
});
```

### What is the expected behavior?

it works lol :). Great work, love it, keep up the good work Jared and team!  You guys are amazing!!

### What do you see instead?

extension is  undefined
.art
2 | const extension = require('./lib/extension');
3 | 
4 | template.extension = extension;
5 | console.log("extension is ", extension.extensions)
6 | console.log(template.defaults.extname)
7 | require.extensions[template.defaults.extname] = extension;
   ^
TypeError: undefined is not an object (evaluating 'require.extensions[template.defaults.extname] = extension')
      at /Users/dev/Documents/prg/alpha/renderer/node_modules/art-template/index.js:7:0
      at (eval) (/Users/dev/Documents/prg/alpha/renderer/node_modules/art-template/index.js:9:17)
      at /Users/dev/Documents/prg/alpha/renderer/src/main.js:5:4

**Comment by dylan-conway** [comment]
This seems to be working now. Could you give this a try with bun v0.6.11?

**Comment by ghost** [comment]
I don't think it's working. Still getting it on 0.6.14.

TypeError: undefined is not an object (evaluating 'import.meta.require.extensions[template.defaults.extname] = extension')

```
const template = require('./lib/index');
const extension = require('./lib/extension');

template.extension = extension;
>>> require.extensions[template.defaults.extname] = extension;

module.exports = template;
```

This line is marked as deprecated.

**Comment by birkskyum** [comment]
With bun 1.0.18, trying the original reproduction prints:

```sh
➜ bun --bun run index.js
[0.08ms] ".env"
App listening at http://localhost:4000
```

When accessing the localhost:4000, I see:

`Error: template not found: No such file or directory`

**Comment by Electroid** [comment]
This appears to have been fixed. If you're still experiencing an issue, let us know and we'll re-open the issue.
