### ISSUE TITLE
segmentation fault  bun run src/index.ts

### ISSUE THREAD

**Issue by ElYaiko** [oven-sh/bun#3381]
### What version of Bun is running?

0.6.10

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Running any file with bun shows error

### What is the expected behavior?

To run the file

### What do you see instead?

segmentation fault  bun run src/index.ts

**Comment by simylein** [comment]
Can you share your `index.ts` file with us? This would be helpful for debugging.

**Comment by vjpr** [comment]
Could be related to this one: https://github.com/oven-sh/bun/issues/3364

Seems like there might be a bug in error stack traces...

**Comment by ElYaiko** [comment]
It seems, now it works well...
