### ISSUE TITLE
node:util:274:9 cb is not a function.

### ISSUE THREAD

**Issue by ElYaiko** [oven-sh/bun#3382]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I'm using a package (whatsapp-web.js) that depends on node:util

### What is the expected behavior?

To run the script

### What do you see instead?

269 |   if (!reason) {
270 |     var newReason = new Error("Promise was rejected with a falsy value");
271 |     newReason.reason = reason, reason = newReason;
272 |   }
273 | 
274 |   return cb(reason);
            ^
TypeError: cb is not a function. (In 'cb(reason)', 'cb' is an instance of Error)
      at node:util:274:9

**Comment by dylan-conway** [comment]
This was probably fixed with #3428  . Could you try again with the canary build?

**Comment by ElYaiko** [comment]
> 

Now works well. 👍

**Comment by ElYaiko** [comment]
> 

Now works well. 👍
