### ISSUE TITLE
Addition of crash reporter in internal package "bun"

### ISSUE THREAD

**Issue by tghpereira** [oven-sh/bun#3385]
### What is the problem this feature would solve?

Bunjs is certainly the most amazing tool I've ever known, but there's a lot of difficulty finding the starting point of errors when bun fails to run. For more lay users, having the bun development environment to debug bugs can be a challenge. The introduction of a crash report that collects the starting point of an error or crash dump will be of great help to the community as well as the development team in finding the starting point of the most critical bugs.

### What is the feature you are proposing to solve the problem?

Add to the "bun" package a resource that can be invoked at the entry point of the app's startup to collect information about unknown errors by bun.

### What alternatives have you considered?

Manual debug in bun development environment.

**Comment by Electroid** [comment]
We do provide a small output summary if Bun crashes. We are unlikely to change this for now.
