### ISSUE TITLE
How to build for the mobile platform?

### ISSUE THREAD

**Issue by hectorqin** [oven-sh/bun#339]
How to build for the mobile platform?

**Comment by hectorqin** [comment]
Does it support the Worker function?

**Comment by FinnRG** [comment]
Could you please specify? Do you want support for ```aarch64```? And what exactly do you mean with worker function?

**Comment by hectorqin** [comment]
I'm curious how to build this library for the mobile(ios/android) platform, just like the [nodejs-mobile](https://github.com/JaneaSystems/nodejs-mobile)?
And the worker function is the worker threads of nodejs.

**Comment by adminy** [comment]
Yes, bun makes sense on mobile since apple only allow their js engine to run there and bun is using it.

https://github.com/denoland/deno/issues/6607

is related topic.

**Comment by Electroid** [comment]
Hi there, it's going to be a while before we have an official path to embedding bun on iOS. It is possible, but might require a lot of work.

**Comment by evelant** [comment]
Now that Bun supports aarch64 and linux arm is this significantly easier or more feasible @Electroid ? Sorry if that's a naive question, I don't have much understanding of the challenges in cross-compilation.

**Comment by loicnestler** [comment]
Would be interested in this as well. 👀

**Comment by xeoshow** [comment]
If bun could support android/iOS, will be a huge advantage compared to nodejs/deno

**Comment by Electroid** [comment]
We will not be officially supporting Android/iOS for the foreseeable future.

**Comment by ghost** [comment]
U know, this could be the real "electron" moment, a truly cross platform solution for building UIs.  I can't wait!

**Comment by biels** [comment]
> U know, this could be the real "electron" moment, a truly cross platform solution for building UIs. I can't wait!

+1

**Comment by elix1er** [comment]
Bump
