### ISSUE TITLE
`segmentation fault` when running `bun i` on a directory with a `.env` present

### ISSUE THREAD

**Issue by LeoBorai** [oven-sh/bun#3397]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. Create a repo with a `.env` file. I'm using this one: https://github.com/whizzes/gabble-web/tree/36d0c205dd4fb095021e88a087a9c42f78853cd2
2. Run `bun i`

### What is the expected behavior?

Bun install packages as usual

### What do you see instead?

```bash
➜  gabble-web git:(main) bun i
[0.25ms] ".env"
bun install v0.6.9 (2ab797ff)
[1]    7556 segmentation fault  bun i
```

**Comment by Jarred-Sumner** [comment]
Please upgrade to canary and try again 

```
bun upgrade --canary
```

If this still happens afterwards leave a comment and we will investigate
