### ISSUE TITLE
Querystring module does not export a default.

### ISSUE THREAD

**Issue by ApproachingApathy** [oven-sh/bun#3408]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux 6.3.8-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

I believe, but am not sure, that this is an issue with how bun exports the `querystring` module. `querystring` does not export a default.

 I encountered this issue when trying to save a file using `@google-cloud/storage`. The save function would fail because `require("querystring").default` is undefined.

```ts
const qs = require("querystring")
console.log(qs.default) // undefined
```

### What is the expected behavior?

`querystring.default` Should be defined.

### What do you see instead?

`querystring.default` is not defined.

### Additional information

I believe the issue may be with may be here: https://github.com/oven-sh/bun/blob/f2285a6d71eba0abc27bc449e9a50116447decf8/src/node-fallbacks/querystring.js#L2

Unless I'm misunderstanding this should be:
```ts
export * as default from "querystring-es3"
```

**Comment by paperclover** [comment]
this is already fixed in the latest canary with our commonjs and node_fallback changes.

you can use the canary version with `bun upgrade --canary`, or wait for 0.6.10
