### ISSUE TITLE
Some private registries give 406 for `Accept: application/vnd.npm.install-v1+json` header

### ISSUE THREAD

**Issue by tchetwin** [oven-sh/bun#341]
The following `Accept` header is sent for some npm registry requests:

https://github.com/Jarred-Sumner/bun/blob/1f887bb8636f976cf9c5ed78205dcd1ea4bb5444/src/install/install.zig#L188

(rightly conforming with the npm registry specification [here](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md)).

Some private package registries, or at least an older version of at least one of them, do not understand this header, and return HTTP 406 Not Acceptable responses. I found this ticket for JFrog: https://www.jfrog.com/jira/browse/RTFACT-18398

The registry specification recommends that `Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*` be used to provide a more tolerant fallback for non-compliant registries. Could this technique be applied to Bun too?

I appreciate that the fallback path leads to potentially 10s MBs of unecessary payload for non-conforming registries, but the alternative (as far as I can tell so far) is that they don't work at all.

Can't wait to be up-and-bunning ;)

**Comment by goooseman** [comment]
@tchetwin I have the same problem with JFrog registry, can not test `bun wiptest` because of that. How unfortunate it is: I was sure finally there is a faster test runner then this slow `jest`

**Comment by Jarred-Sumner** [comment]
Pushed a fix, will deploy tomorrow

**Comment by tchetwin** [comment]
I should have linked originally, but the `Accept` header appears in two other places in this file:

https://github.com/Jarred-Sumner/bun/blob/d6fb0682300e46e6344d110adab0d2ad0d9e74c8/src/install/install.zig#L221-L239

Not sure if these also need to be updated or not, idk when `header_builder.header_count` will be `> 0`

**Comment by Jarred-Sumner** [comment]
> I should have linked originally, but the Accept header appears in two other places in this file:

No it's my fault for not re-reading the surrounding code more carefully

Made it slightly harder for this to happen again. The bigger issue is that Bun 's runtime currently lacks a process spawning API, which means things like this do not have good test coverage

https://github.com/Jarred-Sumner/bun/commit/ee83e25120f8ff52fb44d83ac25b965c2cc2b062

**Comment by rodoabad** [comment]
Thanks, @Jarred-Sumner !
