### ISSUE TITLE
Calling `bun:test` `spyOn` a second time causes a crash with `SIGSEGV` 

### ISSUE THREAD

**Issue by maxmilton** [oven-sh/bun#3412]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux dmx 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux

### What steps can reproduce the bug?

1. Create a file `index.test.ts`:
```ts
import { spyOn, test } from 'bun:test';

test('runs OK', () => {
  spyOn(console, 'log');
});

test('triggers SIGSEGV', () => {
  spyOn(console, 'log');
});
```

2. Run `bun test`

### What is the expected behavior?

Calling `spyOn` more than once does not cause a segmentation fault. Both tests should pass and `bun test` should exit cleanly.

### What do you see instead?

```
~/P/_/bun-test-sigsegv ❱ bun test
bun test v0.6.10 (76626ac5)

index.test.ts:
✓ runs OK [0.58ms]
fish: Job 1, 'bun test' terminated by signal SIGSEGV (Address boundary error)
```

### Additional information

Only causes the crash when `spyOn` is called a second time with _the same_ arguments.

Calling `mockRestore()` etc. on the spy/mock does not change the result.

Both bun stable `v0.6.9 (2ab797ff)` and current canary `v0.6.10 (76626ac5)` exhibit the same behavior.

Bun `v0.6.8 (f18423cf)` does not have this issue, which leads me to think it could be related to commit <https://github.com/oven-sh/bun/commit/dbb2416542ee391fac5a11ba56090bf946117b9d>.

Possibly related:
- https://github.com/oven-sh/bun/issues/3315
- https://github.com/oven-sh/bun/issues/3200

**Comment by simylein** [comment]
Also if there is already a mock function registered it will segfault immediately after the first attempt of spyOn.

```ts
import { describe, mock, spyOn, test } from 'bun:test';

describe('mocking and spying is awesome', () => {
	test('should not segfault', () => {
		console.log = mock(() => void 0);
		const spy = spyOn(console, 'log');
	});
});
```
