### ISSUE TITLE
`MacroLoadError` when trying to use macros

### ISSUE THREAD

**Issue by eatse21** [oven-sh/bun#3415]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

Hi,
I wanted to test bun's macro feature, but couldn't get it to work.

I set up the basic [macro example from the docs](https://bun.sh/docs/bundler/macros) (here is my test [test-macros.zip](https://github.com/oven-sh/bun/files/11866461/test-macros.zip)), and on running `bun build ./index.ts`, I get an error

### What is the expected behavior?

```js
bun build ./index.ts
console.log(`Your random number is ${0.6805550949689833}`);
```

### What do you see instead?

```js
error: FileNotFound reading "macro://71c4c142a4b30add.js"

error: MacroLoadError error in macro

console.log(`Your random number is ${random()}`);
                                     ^
test-macros/index.ts:3:38 99
```

### Additional information

Everything builds and runs fine when I remove the `with { type: 'macro' }` part of the `import` statement.

Running on macOS 11.7.7

**Comment by Jarred-Sumner** [comment]
This has been fixed in the canary build of Bun

**Comment by arHSM** [comment]
@Jarred-Sumner I upgraded to canary and tried the files provided unchanged, and the output doesn't evaluate the macro
![image](https://github.com/oven-sh/bun/assets/82430093/9f5a1e00-82e6-4dcf-962d-bac42f1a3aff)

**Comment by Jarred-Sumner** [comment]
hm.

**Comment by Jarred-Sumner** [comment]
The bug is here:

https://github.com/oven-sh/bun/blob/2eb885c1d8140106b9e292234456cc1482a5a5e1/src/js_ast.zig#L9671

The hash table has a different ID than expected, for reasons I haven't figured out yet

**Comment by eatse21** [comment]
It's working fine now with bun `0.6.12`, thanks!

**Comment by arHSM** [comment]
Can confirm it works! Thank you very much.
