### ISSUE TITLE
bun install needs to normalize line endings for bins

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#3416]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux

### What steps can reproduce the bug?

`bunx live-server`

### What is the expected behavior?

Live server running

### What do you see instead?

```js
bunx live-server
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
error: "live-server" exited with code 127
```

**Comment by godalming123** [comment]
Dupe of: #1125

**Comment by Electroid** [comment]
Duplicate of #1125
