### ISSUE TITLE
Bun should hack shebang and replace node with bun

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#3417]
### What is the problem this feature would solve?

This will make bunx truly run applications on bun instead of nodejs

### What is the feature you are proposing to solve the problem?

Bun should replace the shebang from nodejs to bun

**Comment by Jarred-Sumner** [comment]
Try -b

**Comment by renhiyama** [comment]
> Try -b

People expect bun x to run npm modules in bun environment and not in nodejs. So I created the issue for this reason. Hopefully you understand

**Comment by Jarred-Sumner** [comment]
Yeah the original reason for this was because our node compatibility wasn’t good enough. We’re almost there though

**Comment by mrnoname1000** [comment]
Since node compatibility still isn't 100%, I propose adding a flag to `bun install` like `--hack-shebang` or something for packages that are known by the user to work with bun. The downside is it would have to be deprecated once that behavior becomes the default.

**Comment by renhiyama** [comment]
@Jarred-Sumner could you now add support for this built in? Bun has full support for node native modules except here and there, but since its now stable and recommended for all apps, its better to move to bun completely than still relying on node. Fyi that might even confuse newbies and think bun doesn't provide any significant boost in performance

**Comment by timdp** [comment]
So this indeed really confuses me (with v1.0.6):

```js
#!/usr/bin/env node
console.log(process.argv)
```

`bunx --bun test.js`

```
[
  '/path/to/node',
  '/path/to/file.js',
  '--bun'
]
```

What seems to be happening is that:

1. Bun basically behaves like a shell and immediately forks out to `node`.
2. The `--bun` flag gets passed down to the script.

Because of the latter, things like `bunx --bun eslint` also don't work, because `eslint --bun` is invalid.

I don't think any other runtime behaves this way?

**Comment by Electroid** [comment]
For now a workaround is to run:

```
❯ bun --bun run [...command]
```

In the future, we will make it that the default is Bun.

**Comment by bersace** [comment]
When running hugo, I have do change `node_modules/.bin/postcss` shebang to search node instead of bun. Is this a postcss or a bun issue ?
