### ISSUE TITLE
Cannot use dynamic imports in bun repl

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#3418]
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux 5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64

### What steps can reproduce the bug?

Write `await import("node:process")` in bun repl

### What is the expected behavior?

It should return back the export

### What do you see instead?

```
> await import("node:process")
SyntaxError: Unexpected keyword 'import'
      at /home/ren/coding/frontend/$bun$repl.ts:4:106
```

**Comment by Electroid** [comment]
`bun repl` is not an official command yet, you must be using the unofficial [bun-repl](https://github.com/jhmaster2000/bun-repl)
