### ISSUE TITLE
Wrong docker tag: 0.6.10 was published as 0.6.1

### ISSUE THREAD

**Issue by patlux** [oven-sh/bun#3425]
### What steps can reproduce the bug?

https://github.com/oven-sh/bun/actions/runs/5385842473/jobs/9775272884

![CleanShot 2023-06-27 at 09 41 34@2x](https://github.com/oven-sh/bun/assets/4481570/a37e32e0-f3e4-4f22-85c9-038ed33202da)

https://hub.docker.com/r/oven/bun/tags

![CleanShot 2023-06-27 at 09 42 17@2x](https://github.com/oven-sh/bun/assets/4481570/638bd164-27df-4e03-9865-fdcc3054b488)

**Comment by Electroid** [comment]
This has been fixed.
