### ISSUE TITLE
WebSocket Strange?

### ISSUE THREAD

**Issue by rexwu1104** [oven-sh/bun#343]
I use WebSocket to connect this discord gateway, but on onmessage event it doesn't send me anything
![image](https://user-images.githubusercontent.com/44058270/177742993-9b0af31c-e250-4fa8-8e72-4f2f9a2c0ded.png)
![image](https://user-images.githubusercontent.com/44058270/177742892-580445da-00dc-45d0-91a5-21a289ebd763.png)
![image](https://user-images.githubusercontent.com/44058270/177743114-f4cc9eee-b7e8-4b0b-91f1-087df62c4a8f.png)
just a isTrusted property

**Comment by Jarred-Sumner** [comment]
Does that say: `encoding=etf`

`etf` is probably a typo, you probably meant `utf8`

**Comment by rexwu1104** [comment]
no, I use etf.js
it is make from discord

**Comment by rexwu1104** [comment]
it is a encoding for discord, there have "json" and "etf"

**Comment by vinayakkulkarni** [comment]
what font is that @rexwu1104 ?

**Comment by rexwu1104** [comment]
it must be this 
![image](https://user-images.githubusercontent.com/44058270/177771300-581553c9-1b75-412b-ac42-a16df5265cec.png)
and this is I catched
![image](https://user-images.githubusercontent.com/44058270/177771519-5e0d928f-b2f0-41c7-86b9-46397a98a2b9.png)

**Comment by rexwu1104** [comment]
> what font is that @rexwu1104 ?

If you use "json" directly for encoding, you will see these results directly

**Comment by rexwu1104** [comment]
I use "enoding=json" to try this code, but it still have bug.
the discord send me the InvalidSession Event.
it mean my packet is wrong, but my packet doesn't have any changes.
so, I think it is the bug of WebSocket and the etf.js can't work perfect on bun.

this is the etf.js package url.
https://www.npmjs.com/package/etf.js

**Comment by rexwu1104** [comment]
> what font is that @rexwu1104 ?

do you mean this? 
https://www.erlang.org/doc/apps/erts/erl_ext_dist.html

**Comment by Electroid** [comment]
@rexwu1104 If you have time, are you still seeing this issue on the latest version of Bun? `bun upgrade`

**Comment by rexwu1104** [comment]
there is a new error.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/44058270/199934111-772c2c87-44ab-4e7a-90ba-d8d3f860081e.png">

**Comment by rexwu1104** [comment]
it is from erlpack.
and here is etf.js error.
<img width="822" alt="image" src="https://user-images.githubusercontent.com/44058270/199934326-535d120c-fffc-4882-94bb-b62a948811dc.png">

**Comment by Electroid** [comment]
This doesn't appear to be a `WebSocket` issue. 

Code:
```js
const ws = new WebSocket("wss://gateway.discord.gg/?encoding=json&v=10");
ws.addEventListener("message", ({ data }) => console.log(Buffer.from(data).toString()));

```

Output:
```json
{"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-b-pn41\",{\"micros\":0.0}]"]}}
```

I did try using `etf` encoding with the [`etf.js`](https://github.com/vladfrangu/etf.js) package, but received the following error, `Incompatible ETF version.`, which does not seem related to Bun.
