### ISSUE TITLE
process is wrong killed!!!

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#3435]
### What version of Bun is running?

0.6.11

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

* create a new file `index.js`

```ts
console.log("hello...");
```

* bun index.js

### What is the expected behavior?

no error indication on terminal

<img width="590" alt="CleanShot 2023-06-28 at 01 12 47@2x" src="https://github.com/oven-sh/bun/assets/6713842/692b8687-23e6-4639-80dc-8bd7d6b97e6f">

### What do you see instead?

> iTerm

![CleanShot 2023-06-28 at 01 14 36@2x](https://github.com/oven-sh/bun/assets/6713842/3a60196e-4207-4f4f-82b7-15a1ba3113aa)

> Warp

![CleanShot 2023-06-28 at 01 17 26@2x](https://github.com/oven-sh/bun/assets/6713842/b05c75c1-7e36-494d-bf69-6935e5c595c8)

**Comment by simylein** [comment]
Can you check the exit code of the process? I cannot reproduce this as I am getting the exit code 0 which means success.

**Comment by simylein** [comment]
@robobun

```js
console.log("hello...");
```

**Comment by TiBianMod** [comment]
the exitCode is 0

<img width="806" alt="CleanShot 2023-06-29 at 20 11 18@2x" src="https://github.com/oven-sh/bun/assets/6713842/a181314d-d843-48bd-8de0-6fc43e417582">

**Comment by TiBianMod** [comment]
**Issue is fixed on version 0.6.12**

![CleanShot 2023-06-30 at 12 05 47](https://github.com/oven-sh/bun/assets/6713842/4b835f58-d5c0-4aff-b451-6bcd8c27028a)
