### ISSUE TITLE
Next.js HMR websocket error

### ISSUE THREAD

**Issue by adjsky** [oven-sh/bun#344]
**Description**

Using default Next.js template (bun create next) i get websocket errors after editing files

**Environment information**

OS - Manjaro KDE 21.3.2
Browser - Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)
bun v0.1.1

**Screenshots**

![image](https://user-images.githubusercontent.com/49305219/177741380-cb4bc820-7bd7-4ef1-b25d-d745f5f6668c.png)
![image](https://user-images.githubusercontent.com/49305219/177743905-9fb33321-9168-46e1-8b3b-9274fd22e297.png)

**Comment by rupurt** [comment]
Also getting this on `create-react-app`. Bun `v0.1.3`

**Comment by DamageESP** [comment]
Getting this too in `v0.1.3`. Probably unrelated, but running on WSL (Ubuntu 22.04).

**Comment by chebread** [comment]
The same error occurs in Bun `v0.4.0` running on MacOS Monterey.

**Comment by chebread** [comment]
The same error occurs in Bun v0.5.0 running on MacOS Monterey.

**Comment by chebread** [comment]
In Bun v0.5.7 version running on MacOS Ventura 13.2, react projects other than next js are getting the same error.

**Comment by chebread** [comment]
The same error occurs in Bun v0.5.3 running on MacOS Monterey!
