### ISSUE TITLE
text loader parses backslashes

### ISSUE THREAD

**Issue by PineappleRind** [oven-sh/bun#3449]
### What version of Bun is running?

0.6.11

### What platform is your computer?

Darwin 22.4.0 x86_64 i386

### What steps can reproduce the bug?

I was able to reproduce using `bun test`, or logging both moons to the console — https://github.com/PineappleRind/bun-import-txt 

### What is the expected behavior?

imo the text loader should act like readFileSync and leave escapes as-is

### What do you see instead?

Having an escaped space in a txt file (`\ `) results in the backslash being removed after importing (or it seems so, console.log doesn't show them)

`bun test`

<img width="1149" alt="image" src="https://github.com/oven-sh/bun/assets/65303441/5ea3ff67-89ba-4996-b9f0-304b23584974">

the screenshot shows that moonFromFS() has `\\` though I think that's just `bun test`, the original file doesn't

### Additional information

My current workaround is to escape the backslash (`\\`) in the txt file itself

**Comment by sportshead** [comment]
Still happening on version `1.0.18`

Reproduction: [CodeSandbox](https://codesandbox.io/p/devbox/import-text-jkcj6j) <https://jkcj6j-3000.csb.app/>
