### ISSUE TITLE
[BUN-801] Bun.build var in root scope being reused across packages breaks bundle

### ISSUE THREAD

**Issue by nirrek** [oven-sh/bun#3454]
### What version of Bun is running?

0.6.11

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```bash
# install the necessary dependencies
bun add react react-dom katex
```

**index.tsx**
```js
import { createRoot } from "react-dom/client";
import katex from "katex";

const container = document.createElement("div");
document.body.appendChild(container);
const root = createRoot(container);
root.render(
  <App />
);

function App() {
  return (
    <div>{katex.renderToString("3x+5")}</div>
  )
}
```

**public/index.html**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="module" src="index.js"></script>
  </head>
</html>
```

```bash
# Build the bundle
bun build ./index.tsx --outdir ./public

# Serve the directory (I use `serve`, use whatever you typically use)
serve -d public
```

Load the index.html in the browser using whatever URL your server provides

### What is the expected behavior?

React should mount and render successfully. There should be a simple math expression (`3x+5`) rendered to the screen.

### What do you see instead?

Error while executing the `createRoot` call:

```
index.js:23822 Uncaught TypeError: Cannot create property 'usingClientEntryPoint' on number '14'
    at $createRoot2 (index.js:23822:29)
    at index.js:37518:12
```

### Additional information

The issue seems to be that `katex` and `react-dom/client` both define a `var i` in the root scope in their code. When these get concatenated in the built index.js there is a collision here, so both katex and react-dom/client try to mutate the same variable.

**Here's the bit in the built `index.js` that throws the error**. 
```js
// node_modules/react-dom/client.js
var m = __toESM(require_react_dom(), 1);
var $createRoot2;
var $hydrateRoot2;
if (false) {
} else {
  i = m.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
  $createRoot2 = function(c, o) {
    // 🚨 This line breaks, as `i` is no longer the object assigned two lines up
    // it has since been mutated to be the number 14.
    i.usingClientEntryPoint = true;
    try {
      return m.createRoot(c, o);
    } finally {
      i.usingClientEntryPoint = false;
    }
  };
};
  $hydrateRoot2 = function(c, h, o) {
    i.usingClientEntryPoint = true;
    try {
      return m.hydrateRoot(c, h, o);
    } finally {
      i.usingClientEntryPoint = false;
    }
  };
}
var i;
```
If we look where else `var i` is defined in the root scope, we see that code for the katex module also has a `var i;` declaration.

```js
var mathTextSymbols = "0123456789/@.\"";
for (i = 0;i < mathTextSymbols.length; i++) {
  ch = mathTextSymbols.charAt(i);
  defineSymbol(math, main, textord, ch, ch);
}
var ch;
var i;
```

If we look at the length of mathTextSymbols, it's 14 (which is the value we're seeing in the error, where react-dom/client is expecting an object)

During initial evaluation of the file, react-dom/client is setting the value of `i` on line 23820. Then katex is settings the value of that same `i` on line 28509. When the index.tsx code is evaluated on like 37519, and we call into react-dom/client function, the i value is now wrong and we get the exception.

The unbundled code for `react-dom/client.js` (`node_modules/react-dom/client.js`) looks like this:
```js
'use strict';

var m = require('react-dom');
if (process.env.NODE_ENV === 'production') {
  exports.createRoot = m.createRoot;
  exports.hydrateRoot = m.hydrateRoot;
} else {
  var i = m.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;
  exports.createRoot = function(c, o) {
    i.usingClientEntryPoint = true;
    try {
      return m.createRoot(c, o);
    } finally {
      i.usingClientEntryPoint = false;
    }
  };
  exports.hydrateRoot = function(c, h, o) {
    i.usingClientEntryPoint = true;
    try {
      return m.hydrateRoot(c, h, o);
    } finally {
      i.usingClientEntryPoint = false;
    }
  };
}
```

The relevant part of the unbundled katex code (`node_modules/katex/dist/katex.js`) looks like this:
```js
var mathTextSymbols = "0123456789/@.\"";

for (var i = 0; i < mathTextSymbols.length; i++) {
  var ch = mathTextSymbols.charAt(i);
  defineSymbol(math, main, textord, ch, ch);
} // All of these are textords in text mode
```

<sub>[BUN-801](https://linear.app/oven/issue/BUN-801/bunbuild-var-in-root-scope-being-reused-across-packages-breaks-bundle)</sub>

**Comment by Jarred-Sumner** [comment]
Looks like a bug in our CommonJS to ESM conversion code
