### ISSUE TITLE
http.ServerResponse `headersSent` didn't set to `true` after body-write function.

### ISSUE THREAD

**Issue by muzuiget** [oven-sh/bun#3458]
Here is reproduce code:

```
import process from 'node:process';
import {createServer} from 'node:http';
createServer((request, response) => {
    response.end('OK');
    const {headersSent, writableEnded} = response;
    console.log({headersSent, writableEnded});
    process.exit(0);
}).listen(8000);
setTimeout(() => {
    fetch('http://127.0.0.1:8000/');
}, 100);
```

Result:

```
$ node --version
v20.3.1
$ bun --version
0.6.11
$ node index.js 
{ headersSent: true, writableEnded: true }
$ bun index.js 
{
  headersSent: false,
  writableEnded: true
}
```

**Comment by domingo2000** [comment]
Up!, Im experiencing the same Issue, is causing some http npm libraries like morgan to not log correctly the requests.

**Comment by armenfilipetyan** [comment]
This is the same case for me. `morgan` is using `on-finished` which in turn is expecting socket as part of the `ServerResponse` object but it looks to be an `EventEmitter` instead.

**Comment by iMrDJAi** [comment]
UP! This issue breaks my express.js code:

```js
try {
  // some logic
  if (!res.headersSent) throw 500
} catch (err) {
  res.sendStatus(typeof err === 'number' ? err : 500)
}
```
`res.headersSent` is not being assigned after response is sent.

**Comment by SnowMarble** [comment]
This causes pino-std-serializers to be unable to properly display the status code.

```js
function resSerializer (res) {
  const _res = Object.create(pinoResProto)
  _res.statusCode = res.headersSent ? res.statusCode : null
  _res.headers = res.getHeaders ? res.getHeaders() : res._headers
  _res.raw = res
  return _res
}
```
https://github.com/pinojs/pino-std-serializers/blob/cdd614619511deab7d0d993d79647739667c716f/lib/res.js#L35-L41

**Comment by iMrDJAi** [comment]
@cirospaciari @Jarred-Sumner Seems like the problem isn't full solved. Look at the example below:

```
import express from 'express'
import compression from 'compression'


const app = express()

app.use(compression())

app.get('/', function (req, res) {
  console.log(res.headersSent) // false
  res.json(Bun) // an object that is big enough
  console.log(res.headersSent) // false ;(
})

app.listen(12345)

```
Removing `app.use(compression())` solves the issue. Adding 1 sec delay before the second `console.log` does the trick as well. The issue only happens when you send relativity large responses.

**Comment by Akalanka47000** [comment]
Hello, we're experiencing the same issue when used alongside the compression library. One additional thing we noticed is that it happened once we upgraded from bun 1.1.29 to 1.1.30 and persists until the latest version of bun which is 1.1.36. Hope it'll be helpful for debugging and a fix can be readied as soon as possible
