### ISSUE TITLE
fs.watch for symbolic links

### ISSUE THREAD

**Issue by tipiirai** [oven-sh/bun#3469]
### What version of Bun is running?

0.6.11

### What platform is your computer?

Darwin 20.6.0 arm64 arm

### What steps can reproduce the bug?

fs.watch for symbolic links to directories does not emit changes. Works on Node. 

### Additional information

Thanks for the awesome project!

**Comment by Hanaasagi** [comment]
Symbolic files also have this problem. Here are the steps to reproduce it:

1. Create file and symlink
```
$ touch testfile && ln -s testfile testlink
```

2. Run following code

```JavaScript
const fs = require("fs");

// const file = "testfile";
const file = "testlink";

fs.watch(file, (eventType, filename) => {
  console.log(eventType, filename);
});

```

Error and traceback.

```
35 |       listener = () => {
36 |       };
37 |     this.#listener = listener;
38 |     try {
39 |
40 |       this.#watcher = fs.watch(path, options || {}, this.#onEvent.bind(this));
                         ^
error: NotDir Failed to watch filename
      at new FSWatcher (node:fs:40:22)
      at watch2 (node:fs:159:9)
      at /home/kumiko/zig/bun/x.js:6:0
      at globalThis (/home/kumiko/zig/bun/x.js:8:1)

```

- bun 0.6.12
- Linux 6.3.9-arch1-1

----



https://github.com/oven-sh/bun/blob/d356cd5d4817852ad870f3fff0b07bb53fa55222/src/bun.js/node/node_fs_watcher.zig#L799-L806

I think Line 805 should be changed to

```zig
                result.is_file = _stat.kind != .directory;

```

**Comment by cirospaciari** [comment]
> Symbolic files also have this problem. Here are the steps to reproduce it:
> 
> 1. Create file and symlink
> 
> ```
> $ touch testfile && ln -s testfile testlink
> ```
> 
> 2. Run following code
> 
> ```js
> const fs = require("fs");
> 
> // const file = "testfile";
> const file = "testlink";
> 
> fs.watch(file, (eventType, filename) => {
>   console.log(eventType, filename);
> });
> ```
> 
> Error and traceback.
> 
> ```
> 35 |       listener = () => {
> 36 |       };
> 37 |     this.#listener = listener;
> 38 |     try {
> 39 |
> 40 |       this.#watcher = fs.watch(path, options || {}, this.#onEvent.bind(this));
>                          ^
> error: NotDir Failed to watch filename
>       at new FSWatcher (node:fs:40:22)
>       at watch2 (node:fs:159:9)
>       at /home/kumiko/zig/bun/x.js:6:0
>       at globalThis (/home/kumiko/zig/bun/x.js:8:1)
> ```
> 
> * bun 0.6.12
> * Linux 6.3.9-arch1-1
> 
> https://github.com/oven-sh/bun/blob/d356cd5d4817852ad870f3fff0b07bb53fa55222/src/bun.js/node/node_fs_watcher.zig#L799-L806
> 
> I think Line 805 should be changed to
> 
> ```zig
>                 result.is_file = _stat.kind != .directory;
> ```

That was a big oopsie on my part, sorry about that.

**Comment by tipiirai** [comment]
Thank you @cirospaciari !
