### ISSUE TITLE
None of the commands are working in wsl (ubuntu20.04) and outputs this error while creating the app.

### ISSUE THREAD

**Issue by yash-10x** [oven-sh/bun#347]
Fetching package.json... error: Failed to initialize network thread: SystemOutdated.
**HTTP requests will not work. Please file an issue and run strace().**

**Comment by niri81** [comment]
Seems like a duplicate of #233

**Comment by yash-10x** [comment]
Sorry about it I didn't realised

**Comment by yash-10x** [comment]
I will delete it asp

**Comment by yash-10x** [comment]
to solve 
`wsl --shutdown`
`wsl --update`
`wsl --shutdown`
and then restart the pc.
