### ISSUE TITLE
Malformed_HTTP_Response when repeating the same request through an HTTP_PROXY

### ISSUE THREAD

**Issue by terrywh** [oven-sh/bun#3471]
### What version of Bun is running?

v0.6.11

### What platform is your computer?

Linux 4.14.105-1-tlinux3-0020 x86_64 x86_64

### What steps can reproduce the bug?

``` js

const host = "127.0.0.1";
const port = 7778;

async function doRequest(host, port, auth) {
    const rsp = await fetch("https://ipinfo.io/", {
        verbose: true,
        headers: {
            "User-Agent": "curl/7.66.6", // for json response
        },
        proxy: `http://${host}:${port}`,
    })
    const rst = await rsp.json();
    return rst;
}

await doRequest(host, port, {});
await Bun.sleep(1000);
await doRequest(host, port, {});
```

### What is the expected behavior?

both request should be able to get JSON response.

### What do you see instead?
The second request, failed with:
```
Malformed_HTTP_Response: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://ipinfo.io/"
```

### Additional information

1. When not using "proxy: xxxx", the problem goes away;
2. Doing two different request (to different target domain) using "proxy: xxxx", the problem is the same.

**Comment by terrywh** [comment]
seems setting init option `keepalive: false` is a workaround.

**Comment by birkskyum** [comment]
closed by https://github.com/oven-sh/bun/pull/4510
