### ISSUE TITLE
What's the wrong?

### ISSUE THREAD

**Issue by developersharif** [oven-sh/bun#348]
My app.js file
![bun-error](https://user-images.githubusercontent.com/54396379/177753212-6b7b4dfb-1d06-4757-831f-8b13fed1d3bf.png)
and package.json file
![bun-pkg](https://user-images.githubusercontent.com/54396379/177753249-43c8c20c-bd00-4c04-b576-dd62a040f0d7.png)

**Comment by jub0t** [comment]
It should be `bun app.js`

**Comment by developersharif** [comment]
> It should be `bun app.js`
Same Error.
![2022-07-07_17-33](https://user-images.githubusercontent.com/54396379/177763936-a8caa1dc-b8e5-455c-a27d-cbf6c3bbdf44.png)

**Comment by ziloka** [comment]
its `bun run app.js`

**Comment by erra0002** [comment]
Duplicate of https://github.com/Jarred-Sumner/bun/issues/258 please close this issue and checkout the discussion there

**Comment by developersharif** [comment]
Bun needs to add a polyfill for V8's Error.captureStackTrace API.
