### ISSUE TITLE
Running Bun on TSC fails 

### ISSUE THREAD

**Issue by mikecann** [oven-sh/bun#349]
Aww I was really hoping this would work and thus get some TSC speed improvements.

But alas no luck.

![image](https://user-images.githubusercontent.com/215033/177758017-a72b4f81-8e9c-4eec-b204-eaf373fd7033.png)

Just so this is googleable, the error I get is:

```
 TypeError: undefined is not an object (evaluating 'process.stdout.isTTY')
      at /mnt/c/dev/gangbusters/battletabs/node_modules/typescript/lib/tsc.js:4274:27
      at defaultIsPretty (/mnt/c/dev/gangbusters/battletabs/node_modules/typescript/lib/tsc.js:104004:41)
      at updateReportDiagnostic (/mnt/c/dev/gangbusters/battletabs/node_modules/typescript/lib/tsc.js:103999:15)
      at executeCommandLineWorker (/mnt/c/dev/gangbusters/battletabs/node_modules/typescript/lib/tsc.js:104416:31)
      at /mnt/c/dev/gangbusters/battletabs/node_modules/typescript/lib/tsc.js:104765:0
      at bun:wrap:1:16354
      at bun:main:3:0
```

Im running bun 0.1.1 on WSL2

**Comment by Jarred-Sumner** [comment]
Bun still needs to implement `process.stderr`, `process.stdout`, and `process.stdin`. It has `Bun.stdout`, `Bun.stderr`, and `Bun.stdin`, but that won't help for this particular case.

**Comment by mikecann** [comment]
@Jarred-Sumner ah ye evan on Discord mentioned that too.

He also mentioned that you have already managed to get TSC working with Bun once.. Did you get much of a performance bump? It could be a gamechanger for many people if you get get a performance increase for TSC...

**Comment by gerardmarquinarubio** [comment]
I'm also interested in the performance gains bun could bring to TSC. Do you have any metrics on that @Jarred-Sumner?

**Comment by Neo1975** [comment]
same issue for me due to process.stderr.fd
```shell
TypeError: undefined is not an object (evaluating 'process.stderr.fd')
      at useColors (/Users/dfornaciari/Development/selly-email-sender/node_modules/debug/src/node.js:158:13)
```

**Comment by trevorsargent** [comment]
there's no workaround for this is there? I have the same issue as @Neo1975

**Comment by hanayashiki** [comment]
😄

**Comment by Electroid** [comment]
We're making progress on the Node.js compatibility work that is required to get `tsc` to run. We'll update when we can get a minimal version running.

**Comment by mikecann** [comment]
Awesome, if you can show a meaningful improvement in TSC performance with Bun I think that would be a big game changer for tooling for many folks.

**Comment by hanayashiki** [comment]
> Awesome, if you can show a meaningful improvement in TSC performance with Bun I think that would be a big game changer for tooling for many folks.

I don't think jsc will be any faster than v8

**Comment by Electroid** [comment]
This has been fixed since 0.3.0.

**Comment by thalys** [comment]
I just tested this on a huge project with *tons* on files and a lot of template union types, and where node fails to compile with default memory settings, bun finished successfully 🫰

**Comment by hanayashiki** [comment]
> I just tested this on a huge project with *tons* on files and a lot of template union types, and where node fails to compile with default memory settings, bun finished successfully 🫰

I tried running bun tsc rather than node tsc, on a 2000-3000 line project, but it turns out bun isn't running any faster than node 18. (Macos, intel)
![1D9Ku65KVW](https://user-images.githubusercontent.com/26056783/229030593-68d49abf-729c-484e-9f93-f73fb5d145da.jpg)

**Comment by DreierF** [comment]
Also tried it on our Typescript project with approx 170k LoC and it was 10sec slower with bun. Node 18: 31sec, bun 0.5.8 41sec

**Comment by thalys** [comment]
So our project has 189k LoC, and I don't know if it would be faster, normal tsc running on with node doesn't finish the compilation because of poor memory handling
Bun can finish, but not by running `bun tsc`. I _think_ that still runs the binary with nodejs, but by running `bun run node_modules/typescript/lib/tsc.js --noEmit --pretty` that does the job because of better memory handling
With node I always hit the 4GB memory limit set crashing the process
(but it's not a replacement, using --watch crashes)

_-edit-_
I'm running on:
```
  Bun 0.5.8
  System: Linux Kernel: 5.15.102-1-MANJARO arch: x86_64 bits: 64 v: 5.26.5
  RAM: 32GB [(2x)type: DDR4 size: 16 GiB speed: 3600 MT/s]
  CPU: AMD Ryzen 9 5950X L1: 1 MiB L2: 8 MiB L3: 64 MiB
  Drives: SSD 980 PRO 2TB size: 1.82 TiB
```

**Comment by mctrafik** [comment]
Not a lot of things come up when searching `bun tsc`. For what it's worth I also noticed that our `tsc` takes ~49s, and `bun tsc` takes ~52s, for total savings of -3 seconds.
