### ISSUE TITLE
browser.close() with puppeteer causes a segfault

### ISSUE THREAD

**Issue by vedantroy** [oven-sh/bun#3492]
### What version of Bun is running?

0.6.12

### What platform is your computer?

Linux 5.19.0-46-generic x86_64 x86_64

### What steps can reproduce the bug?

This code segfaults:
```
test("fullstack", async () => {
  const { browser, page } = await inlineDriver(
    path.join(FIXTURES_DIR, "10thingszine.html"),
    { inline: true }
  );

  console.log("RIGHT HERE ...");

  //@ts-ignore
  const bodyHtml = await page.evaluate(() => document.body.innerHTML);
  // segfault right here
  await browser.close();
}, 30_000);
```

Also, when I run a scraper overnight (using puppeteer), I find that it segfaults. Guessing it also has to do with `await browser.close()`

Too lazy to reproduce the full thing, but here's the HTML file. I'm guessing simply opening the file in puppeteer and then running
[10thingszine.zip](https://github.com/oven-sh/bun/files/11928940/10thingszine.zip)

```
  const bodyHtml = await page.evaluate(() => document.body.innerHTML);
  await browser.close()
```

will do the trick:

### What is the expected behavior?

No segfault

### What do you see instead?

segfault core dumped

**Comment by Jarred-Sumner** [comment]
This seems to be fixed in canary, but I'm not 100% sure which commit was the fix. 

Can you try after `bun upgrade --canary`?

**Comment by Jarred-Sumner** [comment]
I'm pretty confident this issue has been fixed, but please leave a comment if it hasn't
