### ISSUE TITLE
Segmentation Faults: exited with code 11 (SIGSEGV)

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#3495]
### What version of Bun is running?

0.6.12

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

> the issue is not related to Elysia, but is something that you can reproduce

* first create a new Elysia.js project
    * [Official docs](https://elysiajs.com/quick-start.html#quick-start)
* run `bun --hot src/index.ts`
* open `src/index.ts`
   * change the response and save (repeat the process around 3-6+ times)
   * and in this point you going to see the error of `SIGSEGV`

### What is the expected behavior?

no errors

### What do you see instead?

> from script `bun run dev:hot`
-> package.json script: `"dev:hot": "bun --hot src/index.ts"`

![CleanShot 2023-07-02 at 18 51 47](https://github.com/oven-sh/bun/assets/6713842/e917fdfd-8b77-40ad-a2d4-5fb5a553b23c)

> on terminal `bun --hot src/index.ts`

![CleanShot 2023-07-02 at 18 51 27](https://github.com/oven-sh/bun/assets/6713842/44e8f8e7-7876-4edb-926f-232fe008e3a8)

### Additional information

this issue is related to the `--hot` flag, the watch flag `bun --watch src/index.ts` is working as expected.

**Comment by Jarred-Sumner** [comment]
Oh no, I thought this was fixed

Thank you for reporting

**Comment by TiBianMod** [comment]
hehe, so fast ?

👍
