### ISSUE TITLE
`utf-8-validate` doesn't work with `bun install` due to not running postinstall script

### ISSUE THREAD

**Issue by pdenapo** [oven-sh/bun#3497]
### What version of Bun is running?

0.6.12

### What platform is your computer?

Linux 5.15.0-76-generic x86_64 x86_64

### What steps can reproduce the bug?

I have found this issue while trying to use the package 

https://www.npmjs.com/package/utf-8-validate

After installing the package (with bun install utf-8-validate), just copy the example code there
in a file validate.js 

``` js
'use strict';

const isValidUTF8 = require('utf-8-validate');

const buf = Buffer.from([0xf0, 0x90, 0x80, 0x80]);

console.log(isValidUTF8(buf));
// => true
```
and run it with bun validate.js

### What is the expected behavior?

Under node  (tested with version16.20-1) it prints "true" as documented in that page.

### What do you see instead?

7 | console.log(isValidUTF8(buf));
               ^
TypeError: isValidUTF8 is not a function. (In 'isValidUTF8(buf)', 'isValidUTF8' is an instance of Object)

### Additional information

Adding a console.log(isValidUTF8)
 shows it is an anonymous function

[Function (anonymous)]

**Comment by Jarred-Sumner** [comment]
This is due to #3288. This package depends on a native module and we aren't running postinstall for that right now

**Comment by Jarred-Sumner** [comment]
After https://github.com/oven-sh/bun/pull/3498 lands, you can use this to validate utf8:
```js
import {isUtf8} from 'node:buffer'
```
