### ISSUE TITLE
for...of is 3x + slower that .forEach and .map !

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#3500]
### What version of Bun is running?

0.6.12

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

* clone repo [bun-bench-loop](https://github.com/TiBianMod/bun-bench-loop)
* cd `bun-bench-loop`
* bun install
* run `bun loop_on_array.js` or `node loop_on_array.js` and compare results

### What is the expected behavior?

I expect `for...of` to be faster than other loops (.forEach and .map)

### What do you see instead?

I see `for...of` to be 3x + time slower from the other loops, and also is slower from nodejs `for...of` 😢 

![CleanShot 2023-07-02 at 21 54 00](https://github.com/oven-sh/bun/assets/6713842/efc8bf47-aa66-4e49-afe6-85878637f731)

**Comment by Jarred-Sumner** [comment]
This is a microbenchmark with results that vary wildly based on the input data. JITs do clever things that don't correlate with reality much in a case like this.

If you run into a performance issue with an application in Bun, feel free to open an issue.

**Comment by TiBianMod** [comment]
Thank you for the response, for the moment I don't have any performance issue with Bun. I'm very happy with Bun.

I opened this issue, because the results was very weird to me.


Keep up the good work 😃
