### ISSUE TITLE
Fetching manifest....

### ISSUE THREAD

**Issue by murtadapy** [oven-sh/bun#351]
After running:
```
bun create
```
I get the following and it takes forever:
![image](https://user-images.githubusercontent.com/63660298/177765447-5a161b5f-70cc-4276-9236-49dccc2f0bae.png)

Note that I'm using Linux mint 20

**Comment by FinnRG** [comment]
Could you please run ```uname -r``` and tell use  your kernel version?

**Comment by murtadapy** [comment]
5.4.0-121-generic

**Comment by FinnRG** [comment]
According to the README, you need kernel version 5.6 or higher for bun install to work well (https://github.com/Jarred-Sumner/bun#using-bun-as-a-package-manager). So this issue is to be expected.

**Comment by FinnRG** [comment]
Please close this issue if you don't have any more questions.

**Comment by murtadapy** [comment]
Thanks for helping
