### ISSUE TITLE
print more details for the `dyld[39817]: missing symbol called` error

### ISSUE THREAD

**Issue by wizzard0** [oven-sh/bun#3511]
### What is the problem this feature would solve?

Identifying specific problematic modules while adjusting existing node projects to use bun takes a long time

### What is the feature you are proposing to solve the problem?

Print more details for the `dyld[39817]: missing symbol called` error (symbol name, library name, ideally where it was required from)

### What alternatives have you considered?

- dtrace (dtruss, opensnoop) - inconvenient to use in the face of system integrity protection and stuff
- binary search over node_modules - hard to drag thru the mess of other errors because problematic modules are typically indirect dependencies

**Comment by Jarred-Sumner** [comment]
Unfortunately this error happens in dyld (it is not produced by Bun)

It means that the native library expects a function to exist but it didn't exist

You might get more info with `DYLD_PRINT_APIS=1`

**Comment by wizzard0** [comment]
Interestingly, `DYLD_PRINT_APIS=1` /always/ gives me `bus error`:
```sh
% bun src/hello.ts         
hello bun
% DYLD_PRINT_APIS=1 bun src/hello.ts
zsh: bus error  DYLD_PRINT_APIS=1 bun src/hello.ts
% cat src/hello.ts 
console.log("hello bun");
```
Reproduces for bun 0.6.13, 0.6.12, 0.6.11 on macOS Ventura 13.4.1

```
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64
```

**Comment by divmgl** [comment]
I'm running into this problem now. I'd love to switch us over to using Bun but I'm unable to tell what function is getting called (or even what package has a V8 binary) in our app.

**Comment by jondot** [comment]
Not perfect but try:
DYLD_PRINT_BINDINGS=1

I'm stuck migrating a project as well.
My issue it seems comes from `libkrb5support`

**Comment by Jarred-Sumner** [comment]
Duplicate of #4290

**Comment by Jarred-Sumner** [comment]
@190n is actively working on supporting V8 C++ APIs in Bun

Please follow along in #4290. It will be fixed
