### ISSUE TITLE
Checking buffer is a buffer causes process to hang and CPU to hit 99.9%

### ISSUE THREAD

**Issue by add1ed** [oven-sh/bun#3515]
### What version of Bun is running?

0.6.13 (though exists in 0.6.12 too)

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```js
async function main() {
  for (var i = 10000000; i >= 0; i--) {
    const buf = Buffer.alloc(32);
    
    // this works:
    // const isBuf = (buf instanceof Uint8Array);
    
    // and this works:
    // const isBuf = Buffer.isBuffer(buf);
    
    // but weirdly checking both together doesn't:
    const isBuf = Buffer.isBuffer(buf) || (buf instanceof Uint8Array);
    
    if (i % 1000 === 0) {
      console.log("%d: isBuf is %s", i, isBuf);
      await new Promise(r => setTimeout(r, 20));
    }
  }
}

main();
```

### What is the expected behavior?

process loops happily and exits after many iterations

### What do you see instead?

process hangs after a handful of iterations and CPU hits 99%

### Additional information

Running this script in node works fine. 
Running either predicate check individually doesn't seem to cause the problem it is only when running both as `a || b` that the issue occurs :shr

**Comment by Jarred-Sumner** [comment]
This is a bug with our DOMJIT implementation of Buffer.isBuffer. Will have a fix shortly.
