### ISSUE TITLE
Support AWS Lambda layer running bun

### ISSUE THREAD

**Issue by efiShtain** [oven-sh/bun#352]
Hey

Is there a lambda layer for running bun instead of node?

**Comment by TobiasGeiselmann** [comment]
Been trying to build a Lambda layer with the bun executable. The problem is that custom runtimes are based on Amazon Linux 2, which comes with GLIBC v2.26, but bun needs v2.27 or newer. This means that bun will not be usable in a Lambda function with custom runtime (or an EC2 instance with Amazon Linux 2).

**Comment by Jarred-Sumner** [comment]
There are two problems:
1. Bun depends on a version of GLIBC that is too new
2. Bun depends on io_uring

Both need to be fixed

**Comment by ghostfuel** [comment]
Only recently have my eye on Bun, looking forward to trying it out in anger sometime!

For AWS Lambda Layer compatibility, for the problems 1,2 listed above - it appears Amazon Linux 2022 (in preview, not yet released and no date announced for Lambda runtime) may well solve both of these if I'm reading it right?

1. [glibc updated to v2.34](https://docs.aws.amazon.com/linux/al2022/release-notes/version-compare-al2022.html#:~:text=2.68.4%2D1.amzn2022-,glibc,-2.26%2D58.amzn2)
2. [liburing is a newly included package](https://docs.aws.amazon.com/linux/al2022/release-notes/new-packages-al2022.html#:~:text=libstemmer-,liburing,-libva)

**Comment by efiShtain** [comment]
@GSt4r 
Didn't touch base on c lately 
Is it possible to statically link the relevant glibc to bun instead of using the system's version ?

**Comment by lightpriest** [comment]
> @GSt4r Didn't touch base on c lately Is it possible to statically link the relevant glibc to bun instead of using the system's version ?

Aside from io_uring, there will probably be some ABI compatibility issues.

**Comment by Electroid** [comment]
This should now be possible, we've tested [Bun 0.3.0](https://bun.sh/blog/bun-v0.3.0) on Amazon Linux 2 and it works. (though work still needs to be done to wire up the Lambda Layer)

**Comment by aprilmintacpineda** [comment]
@Electroid will there be instructions in the docs on how to use Bun with AWS Lambda? Is there gonna be a `Bun3` [runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)?
