### ISSUE TITLE
Can not init tree-sitter parser

### ISSUE THREAD

**Issue by aabccd021** [oven-sh/bun#3524]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 5.15.0-25-generic x86_64 unknown

### What steps can reproduce the bug?

```bash
git clone https://github.com/aabccd021/bun-tree-sitter-bug
cd bun-tree-sitter-bug
bash reproduce.sh
```

### What is the expected behavior?

Expected output
```console
node
v18.16.1
start
finised

bun
0.6.13
start
finished
```

### What do you see instead?

Output:
```console
node
v18.16.1
start
finised

bun
0.6.13
start
```

### Additional information

Might be related to / a duplicate of #2732

**Comment by Jarred-Sumner** [comment]
The code does not use `await`

```js
import Parser from 'web-tree-sitter';

const main = async () => {
  console.log('start')
  await Parser.init();
  console.log('finised')
};

await main();
// ^ await the promise
```

**Comment by Jarred-Sumner** [comment]
We do need to find a way around this for Node.js compatibility reasons
