### ISSUE TITLE
A mocked new Date() isn't sent to function

### ISSUE THREAD

**Issue by charnould** [oven-sh/bun#3525]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Considering this test:

```
  it('Test the new mock Date', async () => {
    setSystemTime(new Date('2020-01-01T00:00:00.000Z'))
    const input = User.parse(u1) // where parse() has a created_at field with value = new Date()
    expect(input.created_at).toBe('2020-01-01T00:00:00.000Z')
  })
```

### What is the expected behavior?

Test must pass

### What do you see instead?

```
error: expect(received).toBe(expected)

Expected: "2020-01-01T00:00:00.000Z"
Received: "2023-07-05T08:37:40.000Z"
```

**Comment by Jarred-Sumner** [comment]
This test passes:
```js
import { setSystemTime, expect, test } from "bun:test";

const User = {
  parse(val) {
    return { created_at: new Date() };
  },
};

test("Test the new mock Date", async () => {
  setSystemTime(new Date("2020-01-01T00:00:00.000Z"));
  const input = User.parse({}); // where parse() has a created_at field with value = new Date()
  expect(input.created_at).toEqual(new Date("2020-01-01T00:00:00.000Z"));
});
```

Are you sure that `User.parse` is using `new Date`?

**Comment by charnould** [comment]
It might be `Zod`-related?

import { z } from 'zod'

```
export const User = z.object({
  created_at: z.string().default(new Date().toISOString().split('.')[0]), // <=== here
  created_by: z.string().toLowerCase().trim().default('auto'),
  is_admin: z.enum(['true', 'false']).default('false'),
  domain: z.string().toLowerCase().trim().default(''),
  lang: z.string().toLowerCase().trim().default(''),
  email: z.string().toLowerCase().email(),
})

export type User = z.infer<typeof User>
```

**Comment by Jarred-Sumner** [comment]
The code for the User object is being executed before the test begins

**Comment by charnould** [comment]
How is it possible?
I've updated my test to make sure it's synchronous.
So `setSystemTime()` happens before parsing.

```
it('should works', () => {

  // Mock new Date() and console.log the proof Bun works
  setSystemTime(new Date('2100-01-01T00:00:00.000Z'))
  console.log("The Proof: ", new Date()) 

  // Zod.parse something...
  const input = User.parse(u1)
  
  // ... and see that the mocked date isn't used
  console.log("The Zod-parsed input: ", input)

  // Thus a failing test
  expect(input.created_at).toBe('2100-01-01T00:00:00.000Z')
})
```

**Comment by Jarred-Sumner** [comment]
No, `setSystemTime` is called after `User` is evaluated (`User.parse` is using the default from `User`). `new Date()` is called in `z.object`. `new Date` must be called after.

```js
export const User = z.object({
   // default(new Date()) calls new Date() before the test() is invoked.
  created_at: z.string().default(new Date().toISOString().split('.')[0]), // <=== here
})
```

You want to defer evaluating the `default` until it is called so that `new Date` can be generated as expected. This is a bug in your code both in the test and outside the test, as `created_at` would be defined at application start time instead of at the time the User instance was created. 


You can verify this with a couple console.log in your code.

**Comment by Jarred-Sumner** [comment]
Another option here is to call setSystemTime from a —preload script. Then you can avoid changing your other code.

**Comment by charnould** [comment]
Really weird because `new Date()` is not defined at application start time.
Each time I re-run this test, the `created_at` changes and is the real `new Date()`:

```
// Run #1
Expected: "2100-01-01T00:00:00.000Z"
Received: "2023-07-05T11:16:45" <--------

// Run #2
Expected: "2100-01-01T00:00:00.000Z"
Received: "2023-07-05T11:16:48" <--------

// Run #3
Expected: "2100-01-01T00:00:00.000Z"
Received: "2023-07-05T11:16:51" <--------
```

**Comment by Jarred-Sumner** [comment]
When you do

```
// user.ts
export const User = {};
console.log("foo');
```

```
import {User} from './user';

test(label, () => console.log("bar"))
```

Your console will print
```
foo
bar
```

That's because `User` is evaluated first. `new Date()` is being evaluated at the same time as `User` is.
