### ISSUE TITLE
Mongoose localhost connection fails

### ISSUE THREAD

**Issue by Wattville** [oven-sh/bun#3527]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. install mongoose with `bun install mongoose`
2. `mongoose .connect("mongodb://127.0.0.1:27017/test").then(() => console.log("connected to database")).catch((error) => console.log(error));
`

### What is the expected behavior?

console logs "connected to database"

### What do you see instead?

`1 | (function (...args) { super(...args); })   
                                   ^
MongooseServerSelectionError: Failed to connect
 code: "undefined"

      at new MongooseError (:1:32)
      at new MongooseServerSelectionError (:1:32)
      at _handleConnectionErrors (/home/watty/bun-projects/catalog-search/node_modules/mongoose/lib/connection.js:792:10)
      at /home/watty/bun-projects/catalog-search/node_modules/mongoose/lib/connection.js:767:10`

### Additional information

works perfectly fine with node js

**Comment by Wattville** [comment]
does not work with any mongodb libs.

**Comment by Jarred-Sumner** [comment]
Is MongoDB running on WSL2 or on Windows? There can be port forwarding issues when stuff is running on Windows and attempting to connect over WSL2.

**Comment by Wattville** [comment]
WSL

**Comment by Jarred-Sumner** [comment]
@cirospaciari can you take a look?

**Comment by Wattville** [comment]
https://github.com/microsoft/WSL/issues/5486 this worked

**Comment by chadacious** [comment]
I was struggling with this and found that if you have enabled mondbo replica set to do transactions on your dev machine, you need to also update the replica set config. The mongoose docs talk about it here [replicaset hostnames](https://github.com/Automattic/mongoose/blob/master/docs/connections.md#replicaset-hostnames)

Once I reconfigured my rs config as they suggested, then I was finally able to connect mongoose in my bun project through wsl.
