### ISSUE TITLE
createCipheriv/decipheriv throw length error when setting the `iv` to null

### ISSUE THREAD

**Issue by Gusb3ll** [oven-sh/bun#3529]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

https://github.com/Gusb3ll/bun-crypto-issue

When using the function `createCipheriv` or `createDecipheriv` with **iv** being `null`

### What is the expected behavior?

It should work like the deprecated createCipher/Decipher function

### What do you see instead?

bun throws error 
```
TypeError: null is not an object (evaluating 'E.length') at F (node:crypto:2:110418)
```
when running the script

**Comment by Hanaasagi** [comment]
Some debugging information may be helpful.

From the nodejs doc https://nodejs.org/api/crypto.html#cryptocreatecipherivalgorithm-key-iv-options, `null` is supported in some algorithm. For example, `aes-256-ecb` algorithm does not require an iv, so it can be `null`.

And the exception occurs at line 3105 `iv.length !== config.iv`

https://github.com/oven-sh/bun/blob/3aaec120e7ac26b3904895d2783a08352b63201a/src/js/node/crypto.js#L3100-L3112

**Comment by Gusb3ll** [comment]
The workaround for me as of now is setting `iv` value to be `Buffer.alloc(0)` and not `null`
