### ISSUE TITLE
Add Svelte Loader as Bun default

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#3552]
### What is the problem this feature would solve?

This issue is primarily targetted towards component testing of Svelte components, but relevant to other issues where Svelte needs to be loaded in.

Currently Bun does not easily integrate with Svelte, Bun ships with a bundler, which allows for `.svelte` files to be loaded in and used; however, this would include manual imports of the plugin in every test file:

```sh
Button.svelte
Button.test.ts
```

```ts
// button.test.ts
import '../../sveltePlugin';
```

Additionally, the types for the tests would be incorrect i.e.:
```ts
import '../src/index';

import { expect, test, describe } from 'bun:test';
import Component from './component.svelte';

describe('it works', () => {
  test('Exists', () => {
    console.log(Component.render());
    expect(Component).toBeDefined();
  })
});
```

in this case, `Component.render()` is not a valid Svelte function according to TS - even though it is, so this would have to be manually typed causing for a lot of type errors which are unnecessary that Bun can handle easily.

### What is the feature you are proposing to solve the problem?

Add svelte is a default loader / plugin into the Bun runtime, this allows for seamless integration when loading Svelte components.

### What alternatives have you considered?

- Using Vite / Vitest which is undesireable considering Bun already provides a bundler (loaders) and the testing framework.
- Using `preload` on `bunfig.toml` again, causes an extra pain point of creating a global file which imports the plugin among other logic

### Additional notes

Related to #193 but an extension on it

**Comment by hyuzea** [comment]
you can also try another alternative using preload in cli
```
bun test  -r ./plugin.js 
bun test v0.6.12 (d356cd5d)
[0.03ms] ".env"

aaa.test.js:
plugins loaded
✓ it works > Exists [0.07ms]

 1 pass
 0 fail
Ran 1 tests across 1 files. 1 total [347.00ms]
```

**Comment by Jarred-Sumner** [comment]
You can use a plugin to import and require .svelte files in Bun. That's what we do in Bun's test suite. 

https://github.com/oven-sh/bun/blob/d55ac0fa434d31503147faefef5340919735c2ad/test/js/third_party/svelte/bun-loader-svelte.ts#L3-L10


Svelte is less of a standard than JSX, so we're unlikely to add support default runtime support beyond making it as easy as possible for people to use a plugin for this.

**Comment by jesseagleboy** [comment]
As Bun now has the full stack dev server, would there be a change to have a Svelte plugin? It seems people have written a loader already but wanted to see if there was any official focus on Svelte (or compiler frameworks) like there is on how to use React with the dev server or using a plugin for Tailwind.

**Comment by Morbden** [comment]
I'm trying to develop a plugin loader for Svelte. The repository is https://github.com/vulppi-dev/libs/tree/main/bun-svelte-loader.

However, I have a bug when I enable HMR.
The HMR script in the Svelte package crashes because it can't detect whether render is a class or a function constructor.

https://github.com/sveltejs/svelte/blob/018996c1677e17857c404df33c8035a1a0c8b42e/packages/svelte/src/internal/client/dev/hmr.js#L47

If anyone can help, I'm all ears.
