### ISSUE TITLE
Support JSDOM

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#3554]
### What is the problem this feature would solve?

Currently DOM testing *can* be achieved, albeit through a third party library, while this is fine it'd be great if we can standardise this to some extent similar to Vite / Vitest's approach, by making this an easily configurable option.

### What is the feature you are proposing to solve the problem?

For tests, I believe the DOM should automatically be added in where for instance the `tsconfig.json` contains `DOM` in the `lib` field, or alternatively a configuration option in `bunfig.toml`. This could also additionally be used to enable DOM matchers (related to #1825).

JSDOM is the obvious candidate, but other alternatives could be considered here, such as happy-dom. Although from my (limited) understanding, JSDOM remains prevalent with many testing libraries out there.

Related to #198 and #1825 

### What alternatives have you considered?

N/A

**Comment by colinhacks** [comment]
Hijacking this to serve as a tracking issue for JSDOM support.

Currently this is blocked on `node-canvas` which uses V8 C++ APIs internally.

**Comment by gitblit** [comment]
Adding a small failure sample here concerning `vm.runInContext` used by JSDOM. Same test works as expected on Node.

<img width="480" alt="image" src="https://github.com/oven-sh/bun/assets/868217/6b371fa1-7180-402e-b32d-fe2d9d4e43e1">

**Comment by niels-bosman** [comment]
I’d like to add that JSDOM support would not only enhance testing capabilities but also benefit applications that use JSDOM to convert XML data into a queryable DOM. Are there any plans to prioritize this in the short term?

**Comment by quantizor** [comment]
> Adding a small failure sample here concerning `vm.runInContext` used by JSDOM. Same test works as expected on Node.
> 
> <img alt="image" width="480" src="https://private-user-images.githubusercontent.com/868217/289868281-6b371fa1-7180-402e-b32d-fe2d9d4e43e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTAyODgsIm5iZiI6MTczMDM0OTk4OCwicGF0aCI6Ii84NjgyMTcvMjg5ODY4MjgxLTZiMzcxZmExLTcxODAtNDAyZS1iMzJkLWZlMmQ5ZDRlNDNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwNDQ2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWZmOGZkYWQ2NThlMDRlNzRiMTgwMzQyYjIwZTJmMDVhYTIwZTJiZDk3MDBkZGUyM2FhM2M4NDFlZjBlZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tA_W7Tzolf_IavcbFYzwLw6dOpXI6NFQy-E7d7cBQdQ">

I'm seeing this too on latest bun + jest@29.7.0 + jest-environment-jsdom@29.7.0

**Comment by niels-bosman** [comment]
You are a hero @Jarred-Sumner

**Comment by coopbri** [comment]
> You are a hero [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/709451?s=64&amp;u=c72c2dd8b0368dc63bf2278e0f4f2ff290449cfb&amp;v=4">@Jarred-Sumner](https://github.com/Jarred-Sumner)

Truly a god among men

Jarred: ~but~ bun wait, there's more
