### ISSUE TITLE
Missing 'default' import in module - CJS file

### ISSUE THREAD

**Issue by FoundedPlains** [oven-sh/bun#3559]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 6.4.1-artix1-1 x86_64 unknown

### What steps can reproduce the bug?

```bash
git clone https://github.com/Fire-The-Fox/Own-Nuxt-Like-Framework.git
cd Own-Nuxt-Like-Framework
bun i
# apply patch
sed -i "s/this.builder.prepare();/this.builder.prepare(this.config?.dirs ?? ['public']);/" node_modules/buchta/src/buchta.ts
bun run index.ts
```
Open in your webbrowser `localhost:3000/`

### What is the expected behavior?

![obrázok](https://github.com/oven-sh/bun/assets/120419528/9f1f6509-371a-47d1-a35b-f60704e7b87d)

### What do you see instead?

`Missing 'default' import in module '/home/jani/git/Own-Nuxt-Like-Framework/node_modules/primevue/toast/toast.cjs.js'.`

### Additional information

I haven't tested every bun version, but it works fine in `0.6.6`

**Comment by sooluh** [comment]
any update here?

**Comment by FoundedPlains** [comment]
The issue still persists even on latest canary version, we have discussed this issue on bun's discord server with the project owner as well and it seems like hidden bug in bun's module resolution that cannot be simply reproduced because then bun behaves like it should

**Comment by FoundedPlains** [comment]
The owner @Fire-The-Fox told me that he found the issue within his build tool and will publish 0.6 as soon as possible
