### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by coffeeispower** [oven-sh/bun#356]
I heard about bun on youtube and i wanted to try it out, i installed through the AUR (bun-bin/bun package) but it just SEGILLs

![imagem](https://user-images.githubusercontent.com/92828847/177778619-740b56d1-1b9e-4926-96f4-caed591ae817.png)

**Comment by coffeeispower** [comment]
My processor is a Intel Pentium and I'm running arch linux obviously

**Comment by sadiki-o** [comment]
same issue running arch on intel i5

**Comment by iammer** [comment]
Same issue on Ubuntu 20.04 on an older processor.   Tested with a few old servers results:
AMD Phenom(tm) II X4 925  - Same issue
Intel(R) Core(TM) i3-2100  - Same issue
Intel(R) Core(TM) i7-5600U - Works
Intel(R) Core(TM) i5-7600 - Works
Intel(R) Core(TM) i7-11800H - Works

**Comment by rockerBOO** [comment]
Possible duplicate of #181

**Comment by Yeasiin** [comment]
I was facing the same problem (Pentium  processor)

by using Intel-SDE I fix the problem on my device. [Fix From](https://github.com/Jarred-Sumner/bun/issues/181#issuecomment-1177133633)

follow the instructions 

```
cd ~
```
```
sudo wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz
```
```
tar -xf sde-external-9.7.0-2022-05-09-lin.tar.xz
```
Writing alias on .bashrc otherwise, alias are not persisting
```
echo "alias sde='~/sde-external-9.7.0-2022-05-09-lin/sde64'" >>  ~/.bashrc
```
```
echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc
```

**Comment by sadiki-o** [comment]
for Arch users u can grab the package from AUR using Paru aur Yay the name is intel-sde, after installation if you have zsh or bash echo the following just like @Yeasiin said : 
`echo "alias sde='/usr/bin/sde" >>  ~/.bashrc or ~/.zshrc`

next : 
`echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc  or  ~/.zshrc`

finally run in terminal: 
`source ~/.bashrc or ~/.zshrc`

**Comment by coffeeispower** [comment]
I love how installing third party packages on archlinux is so much easier than ubuntu XD

**Comment by coffeeispower** [comment]
Using intel sde worked, thx!
This definitely should be on the README

**Comment by jeda** [comment]
Adding the workaround in the README works for now, but is not ideal. `bun` should be able to adapt and not use instructions that are not supported by the processor instead of crashing and forcing users to use external tools to work around things, avoiding the performance penalities and any possible irregularity.

I believe this issue should be re-opened.
