### ISSUE TITLE
Stack traces don't map to correct lines because they ignore commented lines

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3565]
### What version of Bun is running?

0.6.11

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```
// a
// b
// c
console.log(new Error().stack)
```

```
bun src/foo.ts
module code@/Users/Vaughan/dev-mono/thirtyfive/repos/livex/terminal/src/foo.ts:1:22
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

### What is the expected behavior?

Line number should be 4.

### What do you see instead?

Line number is 1.

### Additional information

I've also noticed this in Bun.build source maps. The line mappings are always off by random amounts. Probably caused by this same bug.

**Comment by Jarred-Sumner** [comment]
This was fixed in .12, though there may be other bugs with sourcemaps still
