### ISSUE TITLE
randomUUID() returns invalid and not-v4 UUID in Bun (thus failing Zod-validation)

### ISSUE THREAD

**Issue by charnould** [oven-sh/bun#3575]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run this simple script:

```
import { randomUUID } from "node:crypto";
import { version, validate } from "uuid";
import { z } from "zod";

export const uuid_schema = z.string().uuid();

const a_crypto_uuid = randomUUID();

console.log("For ", a_crypto_uuid);
console.log("version    : ", version(a_crypto_uuid));
console.log("Validation : ", validate(a_crypto_uuid));

uuid_schema.parse(a_crypto_uuid);
```

Sometimes an error is thrown like below.

<img width="721" alt="Capture d’écran 2023-07-08 à 10 24 07" src="https://github.com/oven-sh/bun/assets/7513363/a9ab8e57-ee6b-44ea-ad87-7b2dcfe33dac">

Moreover, sometimes `UUID` version seems to be (according to `UUID` lib): `v2`, `v5` whereas `randomUUID` should return `v4`. The same script never fails with `node` runtime (`node index.js`) and always returns `v4`

### What is the expected behavior?

An always succeeding script

### What do you see instead?

See image.

**Comment by Jarred-Sumner** [comment]
I think the bug is right here

https://github.com/oven-sh/bun/blob/5846ad00edddd89127873bed8df911b48c5bc792/src/bun.js/uuid.zig#L17-L20

**Comment by charnould** [comment]
@Jarred-Sumner I'm unfortunately not a `zig`-guy. Hope you can fix it. BTW, congrats for the road toward `1.0`!

**Comment by Hanaasagi** [comment]
If no one else is currently working on it,  I think I can fix it.
