### ISSUE TITLE
Implement `getCurves` in `node:crypto`

### ISSUE THREAD

**Issue by venkatd** [oven-sh/bun#3584]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Create a `curves.js` file with the following code:

```js
const { getCurves } = require("crypto");

if (getCurves().includes("prime256v1")) {
  console.log("yay");
}
```

### What is the expected behavior?

It should print yay

### What do you see instead?

```
$ bun run curves.js
1 | const { getCurves } = require("crypto");
2 | 
3 | if (getCurves().includes("prime256v1")) {
       ^
TypeError: getCurves is not a function. (In 'getCurves()', 'getCurves' is undefined)
      at /Users/venkat/code/tressel/curves.js:3:4
      at globalThis (/Users/venkat/code/tressel/curves.js:4:19)
```

### Additional information

This is one of the blockers to deploying a server in production. We use the `firebase-admin` library which makes use of node crypto functions.

**Comment by dror-weiss** [comment]
I'm getting this error while trying to use a library that has [openpgp](https://github.com/openpgpjs/openpgpjs) as a dependency.

**Comment by venkatd** [comment]
Wow, that was fast 🤯
