### ISSUE TITLE
express-session Set-Cookie not occurring with Bun

### ISSUE THREAD

**Issue by ketiddies** [oven-sh/bun#3585]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

Run this simple express http server with `bun run index.js` and then with `node index.js`
```
const express = require('express')
const session = require('express-session')

const app = express()
app.use(
  session({
   name: `bun-cookie-test`,
    secret: 'blah-secret',
    resave: false,
    saveUninitialized: true,
    cookie: {
      secure: false,
    },
  }),
)
// Simple route to test session
app.get('/', (req, res) => {
  if (req.session) {
    if (req.session.views) {
      req.session.views++
      res.setHeader('Content-Type', 'text/html')
      res.write('<p>views: ' + req.session.views + '</p>')
      res.end()
    } else {
      req.session.views = 1
      res.end('Welcome to the session demo. Refresh the page!')
    }
  }
})
app.listen(8080)
```

### What is the expected behavior?

You see a `Set-Cookie` header in the response.

Also, you would be able to refresh the page and see the view count rendered in the html

### What do you see instead?

No `Set-Cookie` header with bun.

Yes `Set-Cookie` header with node.

**Comment by ketiddies** [comment]
Did a little digging into the dependencies...

Maybe related to incomplete `node:crypto`?
https://github.com/tj/node-cookie-signature/blob/master/index.js#L19

This is the last line I see in debug logs
https://github.com/expressjs/session/blob/master/index.js#L477

I'll leave this dump here. Not sure if it's coming from bun or somewhere else
run with `DEBUG=express-session node index.js` to reproduce
```
  express-session no SID sent, generating session +2s
resume
read - n = 0
need readable false
length less than watermark true
state.constructed? false
reading, ended or constructing false
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = undefined
need readable true
length less than watermark true
state.constructed? false
reading, ended or constructing false
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = 0
need readable true
length less than watermark true
state.constructed? false
reading, ended or constructing false
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = 0
need readable true
length less than watermark true
do read
readableAddChunk null
n @ fromList 0
ret @ read null
state.length while ret = null 0
read - n = undefined
read: calling endReadable if length 0 -- length, state.ended 0 true
endEmitted @ endReadable false
endReadableNT -- endEmitted, state.length false 0
end emitted @ endReadableNT
finishMaybe -- state, sync {
  objectMode: false,
  highWaterMark: 16384,
  finalCalled: false,
  needDrain: false,
  ending: false,
  ended: false,
  finished: false,
  destroyed: false,
  decodeStrings: false,
  defaultEncoding: "utf8",
  writing: false,
  corked: 0,
  sync: false,
  bufferProcessing: false,
  onwrite: [Function: f],
  writecb: null,
  writelen: 0,
  afterWriteTickInfo: null,
  buffered: [],
  bufferedIndex: 0,
  allBuffers: true,
  allNoop: true,
  pendingcb: 0,
  constructed: true,
  prefinished: false,
  errorEmitted: false,
  emitClose: true,
  autoDestroy: true,
  errored: null,
  closed: false,
  closeEmitted: false,
  [Symbol(kOnFinished)]: [],
  getBuffer: [Function: o],
  bufferedRequestCount: [Getter]
} undefined
...
...
express-session split response +1ms
```

**Comment by Hanaasagi** [comment]
It seems that the callback function in `onHeader` is not being called. Here are the relevant code locations.

https://github.com/expressjs/session/blob/1010fadc2f071ddf2add94235d72224cf65159c6/index.js#L219-L244

https://github.com/jshttp/on-headers/blob/34ef1bad7f5fff187bce0a635aca91892b220d2f/index.js#L56-L66


A temporary workaround is to call `writeHead`. Try this diff

```diff
diff --git a/index.js b/index.js
index 5bdbad8..193f328 100644
--- a/index.js
+++ b/index.js
@@ -18,11 +18,12 @@ app.get("/", (req, res) => {
   if (req.session) {
     if (req.session.views) {
       req.session.views++;
-      res.setHeader("Content-Type", "text/html");
+      res.writeHead(200, { "Content-Type": "text/html" });
       res.write("<p>views: " + req.session.views + "</p>");
       res.end();
     } else {
       req.session.views = 1;
+      res.writeHead(200, { "Content-Type": "text/html" });
       res.end("Welcome to the session demo. Refresh the page!");
     }
   }
```

**Comment by Zykatious** [comment]
This issue appears to still be occurring in 1.0, has there been a regression?

**Comment by Hanaasagi** [comment]
I tried running the code from the issue using bun 1.0, and I could see the `Set-Cookie` header successfully. Could you please provide the code you're using to reproduce the issue? Thanks @Zykatious

**Comment by kishanio** [comment]
there's some issue related to cookie for sure because i'm trying to get parse dashboard working that has csrf middleware. Which also has some trouble.

**Comment by Foorack** [comment]
@kishanio  Please try upgrade to 1.0.3 by running `bun upgrade` and see if the problem can be replicated.

There was a bugfix in 1.0.3 which would cause secure cookies not to be set because Express throught the connection was unencrypted, even though it wasn't.
