### ISSUE TITLE
Using @aws-sdk/client-s3 PutObjectCommand fails - Connection timed out after 0 ms

### ISSUE THREAD

**Issue by sp90** [oven-sh/bun#3588]
### What version of Bun is running?

0.6.14 - canary

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Made a repo to reproduce the bug

* Clone `git clone https://github.com/sp90/bun-aws-upload`
* Install - `bun install`
* Configure `.env` with credentials for your s3 bucket
* Run - `bun run index.ts`

### What is the expected behavior?

Uploads the file

### What do you see instead?

TimeoutError: Connection timed out after 0 ms

### Additional information

What should happen is that it should upload in this example i use the `bun.file` api which ofc makes it unable to run in node. 

But essentially reading a file in node and doing the same works.

I found a similar issue mentioned in the deno repo

Link to the ticket: https://github.com/denoland/deno/issues/18932
Link to the resolve on their end: https://github.com/denoland/deno/issues/18932#issuecomment-1530466970

Maybe they're related maybe they they're not.

**Comment by sp90** [comment]
Does this mean its available in canary?

**Comment by Jarred-Sumner** [comment]
Yeah
