### ISSUE TITLE
process.env.npm_lifecycle_event has only the value of the first script call

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#3589]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 5.15.0-76-generic x86_64 x86_64

### What steps can reproduce the bug?

/package.json

```json
"scripts": {
  "frontend:dev": "bun run --cwd frontend dev"
}
```

/frontend/package.json

```json
"scripts": {
  "dev": "bun run index.js",
  "example": "scripty"
}
```

index.js

```js
console.log(process.env.npm_lifecycle_event) // should ouput "dev" but shows "frontend:dev"
```

run `bun run frontend:dev` in root.

### What is the expected behavior?

`process.env.npm_lifecycle_event` should have the value of the last execute script-name.

### What do you see instead?

The first executed script name

### Additional information

This prevents e.g. running [scripty](https://www.npmjs.com/package/scripty) in the package, cause it resolves npm_lifecycle_event which is in npm or pnpm the last called script-name. (view above frontend/package.json example-script)

Mention: https://github.com/oven-sh/bun/pull/3097

**Comment by v3nntrnx** [comment]
I implemented process.env.npm_lifecycle_event, ill look into that a bit later. But thanks for reporting this information

**Comment by TiranexDev** [comment]
I investigated and couldn't find anything, the problem is that the "second" command runs in a spawn context in a very weird way to me. I am a newbie so I don't know much about bun's codebase, I pass this to another contributor or bun core team.
