### ISSUE TITLE
bun install fails with NotSameFileSystem error

### ISSUE THREAD

**Issue by wojd0** [oven-sh/bun#359]
Steps to reproduce:

1. `bun create react ./react-app`
2. `bun install`
3. Returns:
> bun install v0.1.1
>  Failed to install 9 packages
> [6.00ms] done
> error: NotSameFileSystem installing web-vitals
> error: NotSameFileSystem installing object-assign
> error: NotSameFileSystem installing js-tokens
> error: NotSameFileSystem installing typescript
> error: NotSameFileSystem installing react-refresh
> error: NotSameFileSystem installing react
> error: NotSameFileSystem installing react-dom
> error: NotSameFileSystem installing loose-envify
> error: NotSameFileSystem installing scheduler

Installed with the default install shell on
OS: Manjaro 21.3.1 Ruah
Kernel: x86_64 Linux 5.15.49-1-MANJARO

**Comment by ebadfd** [comment]
`bun install --backend=copyfile` should resolve the `NotSameFileSystem` error
https://github.com/Jarred-Sumner/bun/issues/213#issuecomment-1175633155
