### ISSUE TITLE
Hot module Reload is not working. Probably WebSocket error.

### ISSUE THREAD

**Issue by amaan-ahmad** [oven-sh/bun#360]
WebSocket request fails on editing files in Nextjs.
`ws://localhost:3000/bun:_api.hmr`

![image](https://user-images.githubusercontent.com/27350808/177786137-5b3c4ddc-fdb2-4556-8eca-1a6d21444767.png)

**Comment by denniscual** [comment]
I also experienced this when running `bun dev` command.

**Comment by MuktadirHassan** [comment]
Same Issue while running react. Here is a screenshot of the **WebSocket** error from the console.
![image](https://user-images.githubusercontent.com/46109431/177865399-5d8f3648-12d2-4857-ac55-d081dc154591.png)

**Comment by juliencastera** [comment]
![image](https://user-images.githubusercontent.com/43409919/177874113-50640023-da56-412d-bc6a-23a72dd8e05a.png)

Same here, with same "error objects"

**Comment by FinnRG** [comment]
@amaan-ahmad  Duplicate of #344. Please close this issue.
