### ISSUE TITLE
Standalone minify function

### ISSUE THREAD

**Issue by tipiirai** [oven-sh/bun#3603]
### What is the problem this feature would solve?

Bun has a fantastic JS minifier, but it's not available as an API method.

### What is the feature you are proposing to solve the problem?

`Bun.minify(js)` or something

### What alternatives have you considered?

`esbuild.transformSync` method or [Terser](https://github.com/terser/terser)

**Comment by Electroid** [comment]
```js
new Bun.Transpiler({ minify: true }).transformSync(code);
```

**Comment by tipiirai** [comment]
Wow! Thanks. Worth mentioning on your docs
