### ISSUE TITLE
usage of node:readline prevents programs from exiting

### ISSUE THREAD

**Issue by rubys** [oven-sh/bun#3604]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run the example from the node readline docs: https://nodejs.org/api/readline.html

```js
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const rl = readline.createInterface({ input, output });

const answer = await rl.question('What do you think of Node.js? ');

console.log(`Thank you for your valuable feedback: ${answer}`);

rl.close();
```

### What is the expected behavior?

Program exits upon completion

### What do you see instead?

Program hangs

### Additional information

Obviously `prompt` is a viable alternative, but I'm reporting this as Node compatibility is a goal.

See https://fly.io/blog/flydotio-heart-bun/ for more background.

**Comment by birkskyum** [comment]
This seem to exit correct in bun 0.8

**Comment by rubys** [comment]
Confirmed, problem no longer exists with bun 0.8
