### ISSUE TITLE
express.static returns error when serving an empty file

### ISSUE THREAD

**Issue by RobotoSkunk** [oven-sh/bun#3607]
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 6.3.0-1-amd64 x86_64 unknown

### What steps can reproduce the bug?

1. Create a new project and install express.
2. Configure express to serve static files with `express.static`.
3. Create an empty file (CSS, JS or whatever).
4. Run the project.
5. Load the file with an HTTP request.

### What is the expected behavior?

Express returning an empty HTTP response.

### What do you see instead?

The next error:
```
TypeError: |this| is not a Promise
    at then (native)
    at #internalRead (node:fs:333:13)
    at <anonymous> (node:stream:2:36318)
    at maybeReadMore (native)
    at performMicrotask (native)
```

### Additional information

I'm testing bun with this project: https://github.com/RobotoSkunk/personal-website/

You can easily reproduce this bug with `public/assets/css/stylesheet.css` file, writing content in it and leaving it empty like in the steps to reproduce the bug.

This bug is not that important because static files should not be empty, but it can be confusing for newcomers.

**Comment by Hanaasagi** [comment]
Testing with bun 0.7.0, the initial requests are processed correctly, but subsequent identical requests result in errors.

![2023-07-29_00-00](https://github.com/oven-sh/bun/assets/9482395/401487e3-fa60-4562-9cc2-ad99c4d39b19)

- bun 0.7.0
- Linux 6.4.4-arch1-1 x86_64 unknown


Update:

When using the latest debug build, there might be a coredump generated.

![2023-07-29_23-23](https://github.com/oven-sh/bun/assets/9482395/46da26bc-8d35-44c0-bafd-c215ea6c62b5)

GDB stack trace

![2023-07-29_23-23_1](https://github.com/oven-sh/bun/assets/9482395/6583dd05-d296-437b-bafe-60bc31a46488)
