### ISSUE TITLE
Implement `structuredClone`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#3619]
[`structuredClone()`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) is a function that allows complex JavaScript object to be copied. It is supported in [WebKit](https://github.com/WebKit/WebKit/blob/2517a540e6f5a2037c6843102f3a9cb753f2f9f0/Source/WebCore/bindings/js/SerializedScriptValue.cpp), we just need to port it to work in Bun.

**Comment by TiranexDev** [comment]
With this we can fix stuff like:
https://github.com/oven-sh/bun/issues/3619

**Comment by TiranexDev** [comment]
Closed as completed in #3637
