### ISSUE TITLE
Implement `child_process.fork()`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#3620]
Spawns another process of Bun with IPC.

https://nodejs.org/api/child_process.html#child_processforkmodulepath-args-options

**Comment by simylein** [comment]
Can we close this as it is now implemented?

**Comment by sirenkovladd** [comment]
I think, probably not

https://bun.sh/blog/bun-v0.7.1#child-process-fork-is-partially-implemented
> ... IPC support is not implemented yet and will be added in a future release.
