### ISSUE TITLE
Implement inline snapshots

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#3623]
* [`toMatchInlineSnapshot()`](https://jestjs.io/docs/expect#tomatchinlinesnapshotpropertymatchers-inlinesnapshot)
* [`toThrowErrorMatchingInlineSnapshot()`](https://jestjs.io/docs/expect#tothrowerrormatchinginlinesnapshotinlinesnapshot)
* [`toThrowErrorMatchingSnapshot()`](https://jestjs.io/docs/expect#tothrowerrormatchingsnapshothint) (unrelated, but also)

**Comment by cah4a** [comment]
I want this so badly... :)

**Comment by xieyuheng** [comment]
`toMatchInlineSnapshot` is the only missing API that blocks me from using `bun test`

**Comment by xieyuheng** [comment]
(I will just use `toMatchSnapshot` instead)

**Comment by firatoezcan** [comment]
Can some contributor include some pointers for new contributors to take on this issue?

**Comment by Jarred-Sumner** [comment]
This will be included in Bun v1.1.39, which releases tonight.

**Comment by whekin** [comment]
It seems like these functions are not yet defined in bun:test (@types/bun@1.1.14)

**Comment by mary-ext** [comment]
`@types/bun` seems to be stuck at an earlier version of bun-types
