### ISSUE TITLE
bun:sqlite does not interpret boolean columns as booleans

### ISSUE THREAD

**Issue by bhalonen** [oven-sh/bun#3624]
### What is the problem this feature would solve?

```
import { Database } from 'bun:sqlite'

const db = new Database(':memory:')

const makeTableWithBoolean = db.prepare(`
  CREATE TABLE IF NOT EXISTS table_with_boolean (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    boolean_column BOOLEAN
  )
`)
makeTableWithBoolean.run()

const insertBoolean = db.prepare(`
  INSERT INTO table_with_boolean (boolean_column)
  VALUES ($boolean_column)
`)
insertBoolean.run({ $boolean_column: true })

const selectBoolean = db.prepare(`
  SELECT * FROM table_with_boolean
`)
const booleanResult = selectBoolean.all()
console.log(booleanResult)
/*
[
  {
    id: 1,
    boolean_column: 1
  }
]
*/
```
instead of true

### What is the feature you are proposing to solve the problem?

Could there be a flag on Database("./name.db", config={interpBoolean:true}) to make the API work differently than better-sqlite, as it does on the write side (accepting true and false in contrast better sqlite errors)

I'm guessing compatibility with the better-sqlite implmentation should be the default configuration, but would be definitely a nice to have.

### What alternatives have you considered?

currently it is already better than better-sqlite, so as is works as well.

**Comment by charnould** [comment]
I may understand wrongly this issue, but SQLite has no `bool`-type: https://www.sqlite.org/datatype3.html.
Hence, your code is wrong, moreover this part:

```
const makeTableWithBoolean = db.prepare(`
  CREATE TABLE IF NOT EXISTS table_with_boolean (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    boolean_column BOOLEAN
  )
```

**Comment by Jarred-Sumner** [comment]
```c++
#define SQLITE_INTEGER  1
#define SQLITE_FLOAT    2
#define SQLITE_BLOB     4
#define SQLITE_NULL     5
#ifdef SQLITE_TEXT
# undef SQLITE_TEXT
#else
# define SQLITE_TEXT     3
#endif
#define SQLITE3_TEXT     3
```

Sqlite doesn't return booleans in `sqlite3_column_type`

**Comment by bhalonen** [comment]
@charnould the code I put up runs, but clearly sqlite doesn't allow you to query column types even though you can declare a boolean column.
