### ISSUE TITLE
http server with `serve` leaks memory

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#3628]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

start an http server

```ts
import { serve } from 'bun';

serve({
	port: 4000,
	fetch() {
		return new Response('hello world');
	},
});
```

attack it with `http_load_test 20 127.0.0.1 4000`

### What is the expected behavior?

memory usage fluctuates a little but says more or less consistent. 

### What do you see instead?

bun starts of with 6 to 8 mb of memory and keeps growing to over 200 to 300 mb of memory given enough time.

### Additional information

calling the garbage collector synchronously mitigates the problem and the process stays at around 12 mb of memory

```ts
import { gc, serve } from 'bun';

serve({
	port: 4000,
	fetch() {
		return new Response('hello world');
	},
});

setInterval(() => gc(true), 20000);
```

**Comment by Jarred-Sumner** [comment]
It’s based on how much memory your computer has. If the computer has more memory, the GC doesn’t need to run as often. If you want to restrict memory usage further, you can do BUN_JSC_forceRAMSize=NUM where NUM is number of bytes
