### ISSUE TITLE
Receiving 'error: FileNotFound reading "tty"'

### ISSUE THREAD

**Issue by W2Wizard** [oven-sh/bun#3629]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

I'm using [ora](https://github.com/sindresorhus/ora) for some fancy loading basically, on version `0.6.13` it worked just fine. Now I am getting the following error:

```bash
error: FileNotFound reading "tty"
```

---

To reproduce you can run this very simple example:

```ts
// test.ts
import ora from 'ora';

const spinner = ora('Loading').start();

setTimeout(() => {
	spinner.color = 'yellow';
	spinner.text = 'Doggo';
}, 1000);
```

```bash
bun run test.ts
```

### What is the expected behavior?

A fancy spinner should show up like demonstrated on their github repo.

### What do you see instead?

Once it tries to start the spinner: `error: FileNotFound reading "tty"`

### Additional information

Just a disclaimer, not sure if this is the fault of the package or bun itself but it only occured once I updated so I'll put it in here.

**Comment by dror-weiss** [comment]
I got the same error, thanks for opening this.

**Comment by Jarred-Sumner** [comment]
pretty sure I see the bug. Will have a fix once this finishes compiling.
