### ISSUE TITLE
Deadlocks when using WSL 2.0 with Bun.

### ISSUE THREAD

**Issue by AlonHor** [oven-sh/bun#363]
I tried both
```sh
bun c react ./app
```
and
```sh
bun c next ./app
```
Multiple times on my ubuntu 20.04 WSL. It never actually finished creating the app, and it keeps randomly freezing in a random step. Sometimes it freezes when `Fetching package.json...`, sometimes when `Downloading tarball [2352]` and sometimes in a random step after installing.

**Comment by FinnRG** [comment]
Could you please run ```uname -r``` and tell us your kernel version? If your kernel is below version 5.6 this issue is expected (https://github.com/Jarred-Sumner/bun#using-bun-as-a-package-manager). If your kernel version is higher than 5.6 please run ```wsl -l -v``` to check if you're using WSL2.

**Comment by mikrowdev** [comment]
same problem here, keeping freezing  during `burn add` `burn c next`, @FinnRG i'm actually on Mac OS

**Comment by FrankFang** [comment]
@FinnRG  5.10.102.1-microsoft-standard-WSL2

**Comment by Lastorder-DC** [comment]
Same issue here. tried several times but results are same(stuck at `Fetching package.json...`)

Ubuntu 22.04
Kernal version is `5.15.0-1013-kvm`

p.s.) Not WSL. I'm using AMD based KVM VPS.

**Comment by Electroid** [comment]
This issue was likely fixed by the many stability improvements we've made to `bun install` and `bun create`. If you still run into this problem, please feel free to re-open this issue.
