### ISSUE TITLE
Successive fetch() with HTTPS proxy is unreliable

### ISSUE THREAD

**Issue by FlatMapIO** [oven-sh/bun#3632]
### What version of Bun is running?

0.6.12

### What platform is your computer?

macOS

### What steps can reproduce the bug?

```tsx
async function* fetch_generator() {
  for (let i = 0; i < 3; i++) {
    const txt = await fetch(
      `https://raw.githubusercontent.com/oven-sh/bun/main/README.md`,
      {}
    ).then((it) => it.text());
    // yield 'hello ' + i;
    yield txt;
  }
}

async function main() {
  let i = 0;
  for await (let txt of fetch_generator()) {
    console.log(`success ${++i} times`);
  }
}

main();
```

bun: 
```
[0.41ms] ".env"
success 1 times
Malformed_HTTP_Response: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://raw.githubusercontent.com/oven-sh/bun/main/README.md"
```

node / deno:
```
success 1 times
success 2 times
success 3 times
```

### What is the expected behavior?

node / deno:
```
success 1 times
success 2 times
success 3 times
```

**Comment by Jarred-Sumner** [comment]
Is this macOS x64 or macOS arm64? Is your internet fast / reliable or slow / unreliable?

I'm unable to reproduce this on fast internet on macOS arm64 on Bun v0.6.12 - Bun v0.6.14

**Comment by FlatMapIO** [comment]
macOS arm64 
I'm using a proxy to access the internet (China), maybe this has something to do with it? I've been observing this problem in bun for a few months now, neither node nor deno have the same problem, I'll test again later with a non-proxy network

**Comment by Jarred-Sumner** [comment]
Ah, yes most likely it’s a bug with HTTP or Httpstt keep alive in proxies.
Can you try setting keepalive: false in fetch()

**Comment by FlatMapIO** [comment]
The root cause of this issue is indeed due to HTTPS_PROXY (GFW), however bun and node & Deno behave differently in this regard. I'm not sure if bun can make some adjustments to avoid edge case problems in the ecosystem?

**Comment by ph1losof** [comment]
I also strongly support this, have encountered the same bug when using proxies with bun

**Comment by ph1losof** [comment]
> keepalive: false

this has fixed the issue for me

**Comment by terrywh** [comment]
setting header  `Keep-Alive: false` AND `Connection: close` does **NOT** work, but init option with the above `keepalive: false` works. https://github.com/oven-sh/bun/issues/3471

**Comment by birkskyum** [comment]
Tested the original reproduction with 0.8.2+07d8623976cd5fe1b11dd13f6988cd02e4fc5c15, and it now does work.

```sh
➜ bun --bun index.js
success 1 times
success 2 times
success 3 times
```
