### ISSUE TITLE
SIGSEGV for wss message

### ISSUE THREAD

**Issue by deadlinecode** [oven-sh/bun#3634]
### What version of Bun is running?

0.6.15

### What platform is your computer?

Linux 5.4.0-128-generic x86_64 x86_64

### What steps can reproduce the bug?

Run this code
(You will need valid keys for https/wss)
```ts
Bun.serve({
  hostname: "example.com",
  port: 3005,
  key: fs.readFileSync(
    path.join("/etc/letsencrypt/live/example.com/", "privkey.pem")
  ),
  cert: fs.readFileSync(
    path.join("/etc/letsencrypt/live/example.com/", "fullchain.pem")
  ),
  ca: fs.readFileSync(
    path.join("/etc/letsencrypt/live/example.com/", "chain.pem")
  ),
  fetch(req, server) {
    // upgrade the request to a WebSocket
    if (server.upgrade(req)) {
      return; // do not return a Response
    }
    return new Response("Upgrade failed :(", { status: 500 });
  },
  websocket: {
    message(ws, message) {
      console.log(message);
    },
    open(ws) {},
  },
});
```

Use https://websocketking.com to connect to the web socket (using `wss://`)
Send a message
Et voilà
SIGSEGV

### What is the expected behavior?

It should print out the message that was sent

### What do you see instead?

error: script "dev" exited with code 11 (SIGSEGV)

**Comment by deadlinecode** [comment]
Any prog?

**Comment by cirospaciari** [comment]
> Any prog?

Can you check if this still happens on canary if you try like this?

``` js

import fs from "fs";
import path from "path";

const cert_path = path.resolve("./tests/example.com/");
Bun.serve({
  hostname: "0.0.0.0", // passing IP instead of the domain
  port: 8080,
  tls: {
    key: fs.readFileSync(
      path.join(cert_path, "privkey.pem")
    ),
    cert: fs.readFileSync(
      path.join(cert_path, "fullchain.pem")
    ),
    ca: fs.readFileSync(
      path.join(cert_path, "chain.pem")
    ),
  },
  fetch(req, server) {
    // upgrade the request to a WebSocket
    if (server.upgrade(req)) {
      return; // do not return a Response
    }
    return new Response("Upgrade failed :(", { status: 500 });
  },
  websocket: {
    message(ws, message) {
      console.log(message);
    },
    open(ws) {},
  },
});
```

**Comment by deadlinecode** [comment]
Yes i will test ASAP

**Comment by deadlinecode** [comment]
@cirospaciari seems to work just fine 👍🏻
Thx for the fix
Btw what is the difference between using the tls object vs defining the keys directly on the root config object?

**Comment by cirospaciari** [comment]
> @cirospaciari seems to work just fine 👍🏻 Thx for the fix Btw what is the difference between using the tls object vs defining the keys directly on the root config object?

should be no difference, but i will investigate more

**Comment by cirospaciari** [comment]
this looks like is solved in the current version
