### ISSUE TITLE
Pass function as macro argument segfaults

### ISSUE THREAD

**Issue by m1212e** [oven-sh/bun#3636]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

clone https://github.com/m1212e/bun-fs-router-plugin/commit/6f0e0137726726b8c48dc599ed9f0bb788946d8c

build the the plugin and then the example via the `build.ts` files. 
Use bun link command, to link the out dir of the plugin folder to the example project.

### What is the expected behavior?

I expected the macro to work or display a useful error.

### What do you see instead?

```
/mnt/c/Coding/bun-fs-router-plugin/example$ bun build.ts 
Building...
Segmentation fault
```

**Comment by m1212e** [comment]
I was able to narrow it down to cases where the macro function accepts a function reference.

In any scenario, when I pass a function to a macro function call, I get a segfault.

**Comment by m1212e** [comment]
In my usecase I want to use the macro to augment a function call.

User code:
```
import {GET} from "bun-fs-router-plugin/macros" with { type: 'macro' };

GET((req) => return new Response("Hello world"));
```

post macro code how I would like to output it:

```
import {GET} from "bun-fs-router-plugin/macros" with { type: 'macro' };

GET((req) => return new Response("Hello world"), "/hello/world");
```

Therefore I pass a function as reference to the macro call.

**Comment by m1212e** [comment]
The idea was to then replace it with an iif at build time to enforce configuration based on the macro outputs:

```
import {handlers} from "../lib";
import {HTTPMethod, Handler} from "../types";

export function GET(handler: Handler, path: string) {
  return (() => {
    let map = handlers.get(path);
    if (!map) {
      const newMap = new Map();
      map = newMap;
      handlers.set(path, newMap);
    }

    map.set(HTTPMethod.GET, handler);
  })();
}
```

**Comment by m1212e** [comment]
This is probably caused by the resulting value not being serializeable into JSON: https://bun.sh/docs/bundler/macros#serializablility
Nonetheless a more useful error message would be good, I think

**Comment by Jarred-Sumner** [comment]
It is definitely a bug that this segfaults instead of throws an error

**Comment by m1212e** [comment]
This also happens when passing `import.meta.path` as an argument

**Comment by Jarred-Sumner** [comment]
No longer segfaults as of Bun v1.0.1
