### ISSUE TITLE
Dev server doesn't handle alternative ports properly

### ISSUE THREAD

**Issue by mogita** [oven-sh/bun#364]
## Environment

OS: macOS Monterey 12.3.1 (Apple Silicon)
Shell: zsh 5.8
Bun: 0.1.1
Firefox: 102.0

## Expected Behavior

With a freshly created `react` project, the app should render in the browser with a rotating logo.

## Current Behavior

A blank page shows up, with some errors in the console.

## Steps to Reproduce

1. Run some service to occupy port `3000`, like another web app project or anything
1. With `bun` 0.1.1 installed, create a new React project with `bun create react hello-world`
2. Enter the project directory and start the dev server with `bun dev`, it will automatcally listen on `:3001` which is good
3. Open the dev link `http://localhost:3001` in the **Firefox** browser, a blank page would show
4. Open the browser's console, the following logs can be seen:

```
http://localhost:3001/src/index.jsx is being assigned a //# sourceMappingURL, but already has one
[index.jsx]

Loading module from “http://localhost:3000/node_modules.c87bb419727a84b2.bun” was blocked because of a disallowed MIME type (“text/html”). [localhost:3001]

Loading failed for the module with source “http://localhost:3000/node_modules.c87bb419727a84b2.bun”. [localhost:3001:42:1]

Loading module from “http://localhost:3000/src/app.jsx” was blocked because of a disallowed MIME type (“text/html”). [localhost:3001]

Loading failed for the module with source “http://localhost:3000/src/app.jsx”. [localhost:3001:42:1]

Source map error: Error: request failed with status 404
Resource URL: http://localhost:3001/src/index.jsx
Source Map URL: http://localhost:3000/src/index.jsx.map
```

Peaking deeper into the source code on `localhost:3001/src/index.jsx`, the modules would still be imported on port `3000` instead of `3001` which seems to be the cause of the problem. The source code is listed as below:

```js
import {
__FastRefreshModule as FastHMR
} from "http://localhost:3000/node_modules.c87bb419727a84b2.bun";
import {
__HMRClient as Bun
} from "http://localhost:3000/node_modules.c87bb419727a84b2.bun";
Bun.activate(false);
import {$ad386d4a, $befec4b, $fd6c7e8f, $2d42243f} from "http://localhost:3000/node_modules.c87bb419727a84b2.bun";
var JSX = $fd6c7e8f();
var FastRefresh = $2d42243f();
var jsx = JSX.jsxDEV;
var React = $ad386d4a();
var $$befec4b = $befec4b(), ReactDOM = (($$befec4b && "default" in $$befec4b) ? $$befec4b.default : $$befec4b);
globalThis.document?.dispatchEvent(new CustomEvent("onimportcss", {detail: "http://localhost:3000/src/index.css"}));
import App from "http://localhost:3000/src/app.jsx";
var hmr = new FastHMR(3314931105, "src/index.jsx", FastRefresh), exports = hmr.exports;
(hmr._load = function() {
  ReactDOM.render(jsx(React.StrictMode, {
    children: jsx(App, {}, undefined, false, undefined, this)
  }, undefined, false, undefined, this), document.getElementById("root"));
  hmr.exportAll({});
})();
hmr._update = function(exports) {
};

//# sourceMappingURL=http://localhost:3000/src/index.jsx.map
```

At the meantime, the project opens in Safari and Chromium and renders well.

**Comment by timfeid** [comment]
a temporary fix:  `bun dev --port 3001` (or some other different port!)

**Comment by mogita** [comment]
Thanks @timfeid this works for me. 

Since the server automatically avoids asking silly questions like "there seems to be something running on port 3000, would you like to use 3001?` and starts immediately, it would be really nice if it goes down the road.

**Comment by Pyroseza** [comment]
I fell into this trap by using the sample app, I was not thinking about what I already had running.

for instance I created this:

```js
// http.js
export default {
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
};
```

and ran it with 
```bash
bun run http.js
```

and this is the error that I got:
```
❯ bun run http.js
12 |       if(typeof entryNamespace?.default?.fetch === 'function')  {
13 |         Bun.serve(entryNamespace.default);
14 |       }
15 |    }, reportError);
16 | } else if (typeof entryNamespace?.default?.fetch === 'function') {
17 |    Bun.serve(entryNamespace.default);
       ^
 error: Failed to start server
      at bun:main:17:3
```

The fix is to just start it on a different port.

e.g.
```js
// http.js
export default {
  port: 3030,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
};
```

```
❯ bun run http.js

```

no more error and I can now see it on a different port :)

```
❯ curl http://localhost:3030
Welcome to Bun!
```

**Comment by mansisindhu** [comment]
I also see the same issue in next app template. Even the css also fails to load and links always pointing to `localhost:3000`

This is how this looks on default port - `localhost:3000`
<img width="1512" alt="Screenshot 2022-07-07 at 10 26 18 PM" src="https://user-images.githubusercontent.com/76626095/177829633-b90d7ada-78e3-4020-9f41-a9bfb80dd660.png">

When `localhost:3000` running elsewhere
<img width="1512" alt="Screenshot 2022-07-07 at 10 27 50 PM" src="https://user-images.githubusercontent.com/76626095/177829831-a117d304-2309-4915-893b-de12e8bdd70d.png">

<img width="1512" alt="Screenshot 2022-07-07 at 10 28 31 PM" src="https://user-images.githubusercontent.com/76626095/177829920-c859156b-3d4d-4b36-b81d-2a095cdc7c98.png">

**Comment by Electroid** [comment]
This is good feedback about how Bun handles port conflicts. Right now, Bun runs with the [`SO_REUSEPORT`](https://lwn.net/Articles/542629/) option by default. This means that if there is another process open on the same port, connections will round-robin between them. This is sometimes useful for servers, but it is clearly confusing.

In #1443, we will change the default to error when there is a port conflict.
