### ISSUE TITLE
bun init --help unexpectedly proceeds with init prompt

### ISSUE THREAD

**Issue by eyelidlessness** [oven-sh/bun#3640]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 19.6.0 x86_64 i386

### What steps can reproduce the bug?

```sh
bun init --help
```

### What is the expected behavior?

If possible, display `init` command-specific help. If none is specifically available for the command: exit, ideally with a link or some guidance as to where to find documentation.

### What do you see instead?

A prompt to enter a project name to initilize:

```sh
package name (current directory name):
```

### Additional information

It may be silly to even invoke `bun init --help`, but what prompted me to try was that many tools with an `init` command allow an optional third parameter to specify the name of a subdirectory to create (if not present) and perform the init within. Some actually expect the argument, and do confusing things with the current working directory without it. Granted I'm currently just trying this out in a clean parent directory, but I wanted to have a mental model of the behavior before I did anything that would hit the filesystem at/below `$CWD`.

**Comment by Jarred-Sumner** [comment]
Fixed as of Bun v1.1
