### ISSUE TITLE
'arr.sort()' a little bit slow, in comparsion to Node.js

### ISSUE THREAD

**Issue by gazoblock** [oven-sh/bun#365]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/94359821/177801427-b0f4a9fe-c58f-4f47-b52f-39700e8580da.png">

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/94359821/177808448-63b6ac3f-2134-4c67-9782-334e0b7c79bf.png">

macOS MONTEREY 12.2.1 (21D62)
node 18
bun 0.1.1
zsh

**Comment by nekrondev** [comment]
see https://github.com/WebKit/WebKit/blob/73c597ea4a015c1ec34435f3608e8f0a6f653081/Source/JavaScriptCore/builtins/TypedArrayPrototype.js#L217 

This is related to Webkit's JavaScriptCore `sort` prototype and no runtime function within bun so in the end it's Webkits array sorting that is slow.
