### ISSUE TITLE
Error <No matching export in "node:string_decoder"> in bun build command

### ISSUE THREAD

**Issue by xavikortes** [oven-sh/bun#3660]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Linux 5.19.0-46-generic x86_64 x86_64

### What steps can reproduce the bug?

Launching the command <bun build start.ts>

### What is the expected behavior?

I think this command should be able to build the app and create the bundled files

### What do you see instead?

error: No matching export in "node:string_decoder" for import "StringDecoder"

import { StringDecoder } from 'node:string_decoder';
         ^
/__path__/__to__/__project__/node_modules/minipass/dist/mjs/index.js:9:10 212

### Additional information

I don't know if it should be a problem with my code, with bun or with the dependency. No more information is given.

<bun add string_decorder> doesn't resolve the problem.

These are the dependencies of my project:

  "dependencies": {
    "glob": "^10.3.3",
    "mongodb": "^5.7.0",
    "uuid": "^9.0.0"
  }

I don't know how to give more information about this. Please, feel free to ask for it

**Comment by paperclover** [comment]
`bun build` defaults to browsers, if you are building for bun/node you should use `bun build --target=bun` or `--target=node`.

Though this is still a correct bug report, because this should be inserting a proper browser js polyfill for `string_decoder`.
