### ISSUE TITLE
Can't dynamically require relative imports

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#3666]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

``` javascript
let files = ["second"]
for(let fileName of files) {
    let file = require(__dirname + "/" + fileName);
    file()
}
```

### What is the expected behavior?

Should just work - require file and be done

### What do you see instead?

```
TypeError: require(__dirname + "/" + fileName) is not a function. (In 'require(__dirname + "/" + fileName)()', 'require(__dirname + "/" + fileName)' is an instance of Module)
      at /Users/dev/Documents/prg/bunbug/main.ts:6:15
      at globalThis (/Users/dev/Documents/prg/bunbug/main.ts:7:9)
```

### Additional information

Also when I read the directory structure and tried to require files in a different project I got this:

error: Unexpected pending import in "/Users/dev/Documents/prg/prj/default/server/src/methods/main.ts". To automatically install npm packages with Bun, please use an import statement instead of require() or dynamic import().
This error can also happen if dependencies import packages which are not referenced anywhere. Worst case, run `bun install` and opt-out of the node_modules folder until we come up with a better way to handle this error.

Panic: Unexpected binding of type src.js_ast.Binding{ .loc = src.logger.Loc{ .start = 673517067 }, .data = src.js_ast.B{ .b_identifier =  } }

bun has crashed :'(

----- bun meta -----
Bun v0.5.9 (f3ab445c) macOS Silicon 22.4.0
AutoCommand: extracted_packages 
Elapsed: 1144ms | User: 19ms | Sys: 43ms
RSS: 46.66MB | Peak: 46.66MB | Commit: 56.69MB | Faults: 41
----- bun meta -----

0   0x1043fa788 WTFGetBacktrace
1   ??? Bun__crashReportDumpStackTrace

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

``` json
{
    "compileOnSave": true,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "outDir": "build.nosync",
        "target": "es2020",
        "moduleResolution": "node",
        "module": "commonjs",
        "skipDefaultLibCheck": true,
        "skipLibCheck": true,
        "rootDir": "src",
        "pretty": true,
        "noImplicitThis": true,
        "noFallthroughCasesInSwitch": true,
        "allowUnreachableCode": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "resolveJsonModule": true
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

**Comment by dylan-conway** [comment]
could we see your package.json?

**Comment by ghost** [comment]
Well it's empty

**Comment by ghost** [comment]
https://github.com/turbobuilt/bunbug

Thanks for the help by the way!  This is kind of strange and I'm not sure why it doesn't work.  You guys are great, this is awesome, Bun is just the best, has a few bugs, but I love the hard work!  Thanks for the help!

**Comment by ghost** [comment]
I realize now there was an issue with ES modules.  It can't handle default imports.  Sorry.

**Comment by ghost** [comment]
But I still have the second issue - I don't know what it is so I will reopen

**Comment by ghost** [comment]
```
let fileNames = readdirSync(__dirname).filter(f => f !== 'main.ts' && f.endsWith('.ts'));
for (const file of fileNames) {
    let fileData = require(join(__dirname, file));
}
```

**Comment by ghost** [comment]
Nevermind, I'm gonna reopen when I have more details.  Can't reproduce right now outside my main repo.  Thanks for the time, sorry to waste it.

**Comment by dylan-conway** [comment]
No worries, we are able to repro this bug and will try to get a fix in soon

**Comment by Jarred-Sumner** [comment]
In this case, the `default` export does not become `module.exports`

The fix is to call `.default` on the required module.

```js
let fileNames = readdirSync(__dirname).filter(f => f !== 'main.ts' && f.endsWith('.ts'));
for (const file of fileNames) {
    let fileData = require(join(__dirname, file)).default;
}
```
