### ISSUE TITLE
Compatibility with `comlink` for workers

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#3669]
### What is the problem this feature would solve?

I'm excited to see worker support land in https://github.com/oven-sh/bun/pull/3645 — the tradeoffs look pretty great!

However, I've so far been unable to use the `bun` v0.6.15 canary with [`comlink`](https://github.com/GoogleChromeLabs/comlink). Adapting the `comlink` README:

```js
// index.js
import { wrap } from "comlink";

async function init() {
  const worker = new Worker(await import.meta.resolve("./worker.js"), {"type": "module"});
  // WebWorkers use `postMessage` and therefore work with Comlink.
  const obj = wrap(worker);
  console.log(`Counter: ${await obj.counter}`);
  await obj.inc();
  console.log(`Counter: ${await obj.counter}`);
}
await init(); // Note: `await` was missing here in the original report; see issue conversation
```

```js
// worker.js
import { expose } from "comlink";

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  },
};

expose(obj);
console.log("Worker initialized.")
```

This prints "Worker initialized." but not the counters. In fact, there is no error output, so I'm a bit stuck trying to debug.

### What is the feature you are proposing to solve the problem?

Due to the lack of an error, I'm not 100% sure what would be needed to be compatible with `comlink`.

- The fact that `comlink` has hardcoded assumptions about browsers and `node` may be causing unexpected behaviour.
- This may be due to `MessagePort`, but I'm not sure (since some `postMessage(…)` functionality is already supported).

Given that `comlink` is the de facto library for exposing an async API over a worker boundary, I think it would be pretty valuable to be compatible out of the box.

### What alternatives have you considered?

I'm not aware of any viable alternatives to `comlink` (which has ≈10K stars on GitHub). If `bun` were not compatible, I'd probably have to figure out how to implement custom workarounds instead of consolidating around ecosystem standards and conventions. I have a lot of experience with this, but it doesn't scale to other projects.

It's also possible that small fixes to `comlink` would make it work with `bun` — I don't have enough information to draft a potential PR, though.

**Comment by Jarred-Sumner** [comment]
Workers have a lifetime similar to Node rather than Web 

Try calling .ref() on the Worker. Or pass` { bun: { ref: true } }` to the Worker constructor if you want to stick with browser compatible code

**Comment by Jarred-Sumner** [comment]
Also see https://bun.sh/docs/api/workers

**Comment by lgarron** [comment]
> Workers have a lifetime similar to Node rather than Web
> 
> Try calling .ref() on the Worker. Or pass` { bun: { ref: true } }` to the Worker constructor if you want to stick with browser compatible code

Hmm, interesting. Normally, to get `node`'s `worker_threads` working like web workers I have to call [`.unref()`](https://github.com/cubing/cubing.js/blob/ba5b5e13fc4f9b8d8bc66aabdb62a97f8fd3a5d1/src/cubing/vendor/apache/comlink-everywhere/outside/index.ts#L21). However, if the main thread is `await`ing on a `Promise` that requires a message from the worker to resolve, the program shouldn't be exiting early either way, right?

If I ref the worker, I see the output "Counter: 0" but the program exits (with exit code 0) before `await obj.inc()` resolves. But thanks, this gives me a place to start debugging!

EDIT: actually, it seems to be a race condition whether "Counter: 0" prints or whether the program exits before that line as well.

**Comment by lgarron** [comment]
> If I ref the worker, I see the output "Counter: 0" but the program exits (with exit code 0) before `await obj.inc()` resolves. But thanks, this gives me a place to start debugging!
> 
> EDIT: actually, it seems to be a race condition whether "Counter: 0" prints or whether the program exits before that line as well.

More specifically, the following program exits without waiting 10 seconds and without printing an error. Somehow the execution of the main thread is being halted due to the presence of `await obj.inc();` without throwing an error. 🤔

```js
import { wrap } from "comlink";

async function init() {
  try {
    const worker = new Worker(await import.meta.resolve("./worker.js"), {"type": "module", bun: { ref: true }});
    worker.ref()
    // WebWorkers use `postMessage` and therefore work with Comlink.
    const obj = wrap(worker);
    console.log(`Counter: ${await obj.counter}`);
    await obj.inc();
  } catch (e) {
    console.log("Error!", e);
  } finally {
    await new Promise((resolve) => setTimeout(resolve, 10000)); // sleep 10 seconds
  }
}
init();
```

**Comment by Jarred-Sumner** [comment]
> However, if the main thread is awaiting on a Promise that requires a message from the worker to resolve, the program shouldn't be exiting early either way, right?

normally yes, but init isn’t awaited.

**Comment by lgarron** [comment]
> normally yes, but init isn’t awaited.

Ah, I'm sorry. Good catch — I was trying to stay close to the sample code but I'm not normally used to testing code using a named `async` wrapper like this. 🤦

**Comment by lgarron** [comment]
Okay, I dug into this for an hour and unfortunately all I could determine is that [the `"message"` listener on the worker side](https://github.com/GoogleChromeLabs/comlink/blob/dffe9050f63b1b39f30213adeb1dd4b9ed7d2594/src/comlink.ts#L298) executes the first time it receives [a `postMessage(…)` from `requestResponseMessage(…)` to the worker object](https://github.com/GoogleChromeLabs/comlink/blob/dffe9050f63b1b39f30213adeb1dd4b9ed7d2594/src/comlink.ts#L61), but it does not execute on subsequent times (in the current `bun` canary).

The worker remains alive and has not [removed the `"message"` listener](https://github.com/GoogleChromeLabs/comlink/blob/dffe9050f63b1b39f30213adeb1dd4b9ed7d2594/src/comlink.ts#L365), so I don't know why it would stop receiving messages. I still have no idea if this might be due to `bun`'s implementation or due to a bad assumption in `comlink`.

**Comment by Jarred-Sumner** [comment]
there's probably a bug in bun here, due to lack of test coverage. sorry for taking up your time on this

**Comment by Jarred-Sumner** [comment]
After https://github.com/oven-sh/bun/commit/777ee4ececebe912a08c1ffe69546aacb6a497c7, back and forth messages work as expected

<img width="416" alt="image" src="https://github.com/oven-sh/bun/assets/709451/04035af5-948b-488b-ba17-564405c17f1e">

**Comment by Jarred-Sumner** [comment]
There is a GC bug, I suggest waiting a couple more days or until v0.7 is released

**Comment by lgarron** [comment]
Thanks for the fix, I'm glad to see it! 😻

I can confirm that the latest canary prints out all the expected counters.

However, it now seems to have the opposite problem, where the sample program in the first comment doesn't exit, and I'm unable to fix that by trying to explicity `unref` the worker. (From other projects, I know that `comlink` doesn't prevent the program from exiting, as long as the worker is `unref`ed.)

This isn't necessarily a big issue, but I thought I'd note it.

**Comment by paperclover** [comment]
I did some work on `Worker`s and their lifetime+event loop to bring them closer to how they work in Node.js, and those unref issues shouldnt exist anymore; I think we can close this issue now. If there are any new inconsistencies, we can re-open this.
