### ISSUE TITLE
`error: IsDir` when running bun install in repo with `.env` folder

### ISSUE THREAD

**Issue by jamiehaywood** [oven-sh/bun#3670]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

`package.json`
```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "react": "18.2.0"
  }
}
```
`folder structure`
```
.
├── .env
│   ├── .env.development
│   └── .env.production
└── package.json
```

### What is the expected behavior?

The installer checks whether it's a folder or a file.

### What do you see instead?

`error: IsDir`

### Additional information

ref: #168 which was closed prematurely

**Comment by Jarred-Sumner** [comment]
Yeah it shouldn’t error, it should just ignore it
