### ISSUE TITLE
Express projects do not transmit fonts and images correctly while running under Bun

### ISSUE THREAD

**Issue by ezShroom** [oven-sh/bun#3674]
### What version of Bun is running?

0.6.14

### What platform is your computer?

macOS Ventura 13.4.1 (Darwin 22.5.0 x86_64 i386)

### What steps can reproduce the bug?

Make an Express project serving `.webp` or `.woff2` static files (you can reproduce this by setting [this repo](https://github.com/Shroom2020/bunrepro) up). This bug probably applies to more types, but I haven't personally tested any others. In Chromium, the `.webp` files will not load and the `.woff2` file will; the opposite applies to Gecko-based browsers like Firefox.

### What is the expected behavior?

Both file types load and display properly.

### What do you see instead?

They do not load and display properly.

**Comment by Jarred-Sumner** [comment]
we will fix this in Bun v0.7.1

**Comment by Jarred-Sumner** [comment]
I'm pretty sure this was fixed in v0.7.1 or v0.7.2. If you run into it again, please leave a comment.
