### ISSUE TITLE
Pre-release versions not resolved correctly

### ISSUE THREAD

**Issue by scinos** [oven-sh/bun#3684]
### What version of Bun is running?

v0.6.15 (17903570)

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Create a `package.json` with:

```
{
  "name": "my-package",
  "dependencies": {
    "html-webpack-plugin": "^5.0.0-beta.4"
  }
}
```
Run `bun install`

### What is the expected behavior?

It should install `html-webpack-plugin@5.5.3`. `5.5.3` is the latest version that matches the range at the time of writing, according to `yarn` and https://semver.npmjs.com/.

### What do you see instead?

It installs `html-webpack-plugin@5.0.0-beta.6`, as confirmed by `bun pm ls` or `cat node_modules/html-webpack-plugin/package.json| grep version`

**Comment by dylan-conway** [comment]
This is fixed in the latest release of bun `v1.1.13`. I believe this bug was originally fixed around `v1.0.5`
