### ISSUE TITLE
Bun trims environment variables

### ISSUE THREAD

**Issue by v3nntrnx** [oven-sh/bun#3689]
### What version of Bun is running?

0.6.15

### What platform is your computer?

Linux 6.3.9-zen1-1-zen x86_64

### What steps can reproduce the bug?

a.js:
`console.log(process.env.EXAMPLE, process.env.EXAMPLE == " hi")`

console:
`EXAMPLE=" hi" bun run a.js`

### What is the expected behavior?

" hi true" in the terminal. (like node.js)

### What do you see instead?

"hi false" in the terminal

### Additional information

I found this bug while working on #3661,
also it works correctly if the env is set in .env

![image](https://github.com/oven-sh/bun/assets/94789999/eb2e677c-fa1b-4aeb-95cc-c21429d121e1)

**Comment by v3nntrnx** [comment]
![image](https://github.com/oven-sh/bun/assets/94789999/e0f6429b-13a5-4ba0-83db-b35fb83303ec)
may this be the line which breaks it? (src/env_loader.zig, line 690)

UPD: probably not, removing this does not seem to fix the issue. But I might be wrong

**Comment by TiranexDev** [comment]
I'll create a pr for that

**Comment by clemg** [comment]
On my side it seems to be fine when using the dev/release builds (no space trimmed)
When using the public bun bin its different, tf?

is the publicly shared bin different from the release build?

**Comment by clemg** [comment]
> ![image](https://user-images.githubusercontent.com/94789999/254729963-e0f6429b-13a5-4ba0-83db-b35fb83303ec.png) may this be the line which breaks it? (src/env_loader.zig, line 690)
> 
> UPD: probably not, removing this does not seem to fix the issue. But I might be wrong

I think it's because when parsing the value, the spaces get ignored at the beginning because of [env_loader.zig#L695C1-L695C1](https://github.com/oven-sh/bun/blob/main/src/env_loader.zig#L695C1-L695C1)

**Comment by iMrDJAi** [comment]
Related https://github.com/oven-sh/bun/issues/3743#issuecomment-1646612423

**Comment by v3nntrnx** [comment]
> Related https://github.com/oven-sh/bun/issues/3743#issuecomment-1646612423

I think what you're looking for is #3716

**Comment by clemg** [comment]
then we might want to mark this as closed

**Comment by v3nntrnx** [comment]
oh yeah, seems to be fixed
![image](https://github.com/oven-sh/bun/assets/94789999/b0ea0de8-ce57-4a89-b199-784a18337662)
