### ISSUE TITLE
FFI with CGo issue

### ISSUE THREAD

**Issue by wobsoriano** [oven-sh/bun#369]
I was playing around `bun:ffi` with [CGO](https://pkg.go.dev/cmd/cgo) and it throws the following

```bash
~/tmp/bun-robot is 📦 v1.0.0 via 🐹 v1.18.1 via  v18.4.0
❯ bun ./ffi.ts
235 |   callback: nativeCallback,
236 | };
237 |
238 | export function dlopen(path, options) {
239 |
240 |   const result = nativeDLOpen(path, options);
                    ^
 TypeError: Failed to open library
 code: "ERR_INVALID_ARG_TYPE"

      at dlopen (bun:ffi:240:17)
      at /Users/wobsoriano/tmp/bun-robot/ffi.ts:5:36
```

Here's my code in Go:

```go
package main

/*
#include <stdlib.h>
#include <string.h>
*/
import "C"

//export GetVersion
func GetVersion() *C.char {
  return C.CString("v0.69")
}

func main() {} // Required but ignored
```

running `go build -o ./tray_darwin.dylib test.go` generates the `dylib` file.

And here's my TS file:

```ts
import { dlopen, FFIType, suffix } from "bun:ffi";

const path = `tray_darwin.${suffix}`;

const { symbols: { GetVersion } } = dlopen(path, {
  GetVersion: {
    args: [],
    returns: FFIType.cstring,
  },
});

console.log(GetVersion())
```

My machine is a MBP 14-inch in Monterey v12.4

Any help would be much appreciated.

**Comment by nekrondev** [comment]
You are compiling a static executable instead of a shared object (.so or .dylib).

Please use
```
go build --buildmode c-shared -o ./tray_darwin.dylib test.go
```
If the FFI binding is unable to load or find your dynamic library you will get `TypeError: Failed to open library` error, if your symbols are not found (but loading works)  you will get something like `TypeError: Symbol "GetVersion" not found in "./lib.so"`.

**Comment by wobsoriano** [comment]
Thank you @nekrondev ! That fixed it.

**Comment by sayeed205** [comment]
How do I pass strings as args with cgo in bun ffi
