### ISSUE TITLE
Got Array size error when run bunx prisma init

### ISSUE THREAD

**Issue by UnkAtreus** [oven-sh/bun#3704]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

create new project
bun add -d prisma
bunx prisma init <-- error issue

### What is the expected behavior?

should run prisma init and migrate

### What do you see instead?

Error: Array size is not a small enough positive integer.
error: "prisma" exited with code 1 (SIGHUP)

### Additional information
prisma version 5.0.0
_No response_

**Comment by Electroid** [comment]
Could you try again after running `bun upgrade --canary`? We likely fixed this issue here: #3567

**Comment by UnkAtreus** [comment]
error message is missing but still not working. Do not have any file created.

**Comment by telesvar** [comment]
On my side when I run the command, I don't get an error 🤔

**Comment by UnkAtreus** [comment]
Can I ask you, What a prisma and bun version that you used?

**Comment by bytespider** [comment]
Maybe relevant or not, but I was getting no output from bunx with the Prisma CLI until I installed node.
It seems likely to me that Prisma is explicitly calling node for some parts of its CLI.

**Comment by Jarred-Sumner** [comment]
Pretty confident this has since been fixed

If you're still running into this issue, please let us know
