### ISSUE TITLE
Vite/SvelteKit failed to load config from vite.config.ts

### ISSUE THREAD

**Issue by gitblit** [oven-sh/bun#3705]
### What version of Bun is running?

0.6.15

### What platform is your computer?

WSL2

### What steps can reproduce the bug?

1. `npm create svelte@latest my-app`
2. Choose demo, TypeScript, Vitest
3. cd my-app
4. bun install
5. bun --bun run dev

<img width="544" alt="image" src="https://github.com/oven-sh/bun/assets/868217/02b36007-277b-4714-82a1-53da1467323d">

### What is the expected behavior?

Would like to see Vite dev server running & serving content. :)

### What do you see instead?

Error message

**Comment by paperclover** [comment]
duplicate of https://github.com/oven-sh/bun/issues/250 and https://github.com/oven-sh/bun/issues/3216

also vite will not work entirely until the ws patch to their repo is complete
