### ISSUE TITLE
Database type doesn't allow to deserialize

### ISSUE THREAD

**Issue by baptistecs** [oven-sh/bun#3712]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

Hello,

Apparently, we can't deserialize as it is specified in the doc:
https://github.com/oven-sh/bun/blob/main/docs/api/sqlite.md#serialize

```jsx
const olddb = new Database("mydb.sqlite");
const contents = olddb.serialize(); // => Uint8Array
const newdb = new Database(contents); // <= HERE the Database type doesn't allow to pass a Buffer in the constructor
```
![image](https://github.com/oven-sh/bun/assets/50966051/3dfb08ad-f1c4-4c8a-9f28-26b54d3a8e4f)

The deserialize method doesn't exist neither:
![image](https://github.com/oven-sh/bun/assets/50966051/b6422c54-9ff7-4e4b-8c03-f3e910ba2086)

Ideally, I would like to load a DB from a file to an in memory DB when my app starts, and from the in-memory to the file DB from time to time.

![image](https://github.com/oven-sh/bun/assets/50966051/0cee5fc1-6243-4f0c-8d8e-9d803bd4d6b4)

Thanks in advance!

Kind regards,
Baptiste

### What is the expected behavior?

There is a way to deserialize (load content in a db from a serialized db).

### What do you see instead?

No way to do it

**Comment by baptistecs** [comment]
My bad, there is a static method, but the doc need to be updated:
```jsx
Database.deserialize(contents) // And not: new Database(contents)
```

**Comment by baptistecs** [comment]
It's not the doc which needs to be updated, but the Database typescript interface/type, if I use the "@ts-expect-error" comment, it works:
```jsx
const fileDatabase = new Database('myDB.sqlite', { create: true, readonly: false });
fileDatabase.run(`
    CREATE TABLE "foo" (
        "id"	INTEGER,
        "name"	TEXT NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
    );
`);
const contents = fileDatabase.serialize();

// @ts-expect-error "Database type/interface not updated"
const db = new Database(contents);
const tables = db.query('select name from sqlite_master where type="table"').all();
console.log('in mem DB', tables); // I get the foo table in the list
```

if I use the static method, it fails (there is something else to fix):
```jsx
const db = Database.deserialize(contents); // that works
const tables = db.query('select name from sqlite_master where type="table"').all(); // that fails
```

TypeError: db.query is not a function. (In 'db.query('select name from sqlite_master where type="table"')', 'db.query' is undefined)

I use the version 0.7.0 now

**Comment by 9Morello** [comment]
The static function error reported by @baptistecs still happens with Bun 1.0.2.

**Comment by Jarred-Sumner** [comment]
will have a fix shortly
