### ISSUE TITLE
Bun.env truncates .env string values containing `#` when run as an npm script

### ISSUE THREAD

**Issue by SpencerWhitehead7** [oven-sh/bun#3716]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Create a directory containing
.env
```
TEST_VAR='ABC#DEF'
```

reproFile.js
```
console.log(Bun.env.TEST_VAR);
```

package.json
```
{
  "name": "bun-env-bug-repro",
  "scripts": {
    "reproScript": "bun run reproFile.js"
  }
}
```

cd into new directory
run `bun run reproFile.js` - the terminal output is correct `ABC#DEF`
run `bun reproScript` - the terminal output is incorrect `ABC` (truncates `#` and rest of string)

### What is the expected behavior?

The output of `bun reproScript` and `bun run reproFile.js` is `ABC#DEF` in both cases

### What do you see instead?

`bun run reproFile.js` outputs `ABC#DEF`
`bun reproScript` outputs `ABC` and truncates the `#` and the rest of the string

### Additional information

The same bug appears if the reproFile is `.ts`
`bun run reproScript` has the same bug as just `bun reproScript`

Not sure whether that's any help

**Comment by v3nntrnx** [comment]
does this happen when you run 
TEST_VAR="ABC#DEF" bun run reproScript/reproFile.(ts/js)

**Comment by SpencerWhitehead7** [comment]
Yes, the bug is still present using double quotes for the env var.

Wow, thank you for the quick response! Unfortunately, I won't have a chance to check back until the weekend, so if you want to look into it more before then, you'll have to create the repro locally I'm afraid.

**Comment by v3nntrnx** [comment]
> Yes, the bug is still present using double quotes for the env var.
> 
> Wow, thank you for the quick response! Unfortunately, I won't have a chance to check back until the weekend, so if you want to look into it more before then, you'll have to create the repro locally I'm afraid.

It‘s okay, I‘ll call someone from the core team to look into this

**Comment by v3nntrnx** [comment]
UPD: We discussed this with the core team on the discord server, and we'll come up with a solution soon

**Comment by SpencerWhitehead7** [comment]
Thank you for fixing this so quickly!! Bun is a fantastic project and I really appreciate the high level of support.
