### ISSUE TITLE
BigInt has very poor performance

### ISSUE THREAD

**Issue by duthanhduoc** [oven-sh/bun#3723]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. Create `utils.js`

```js

const handleBigNumber = () => {
  const n = 1000
  let result = BigInt(1)
  for (let i = 0; i < n; i++) {
    result *= BigInt(i)
  }
  return result
}

const fibonacci = (n) => {
  if (n <= 1) {
    return n
  }
  return fibonacci(n - 1) + fibonacci(n - 2)
}
const t1 = performance.now()
handleBigNumber()
const t2 = performance.now()
console.log(`handleBigNumber took ${t2 - t1} milliseconds.`)

```

2. Run command `bun run utils.js` or `node utils.js` to run script
3. Bun: 0.24995800000000035 and Node: 0.06970787048339844

Bun version: 0.7
Node version: 19.7.0

### What is the expected behavior?

BigInt Performance Improvement. At least as fast as Node.js

### What do you see instead?

**Bun is 3 times slower than Node**

**Comment by MohammedWaheeb** [comment]
what is the content of utils.js

**Comment by duthanhduoc** [comment]
> what is the content of utils.js

Sorry, i missed. i updated

**Comment by birkskyum** [comment]
I find with bun 0.8.1 that this is resolved.

```zig
➜ hyperfine "bun run utils.js" "node utils.js"
Benchmark 1: bun run utils.js
  Time (mean ± σ):       9.7 ms ±   0.8 ms    [User: 4.6 ms, System: 3.1 ms]
  Range (min … max):     8.0 ms …  13.7 ms    253 runs
 
Benchmark 2: node utils.js
  Time (mean ± σ):      31.0 ms ±   0.7 ms    [User: 23.8 ms, System: 6.0 ms]
  Range (min … max):    29.3 ms …  33.3 ms    85 runs
 
Summary
  bun run utils.js ran
    3.21 ± 0.29 times faster than node utils.js
```

**Comment by duthanhduoc** [comment]
@birkskyum 

i checked and found the command `hyperfine "bun run utils.js" "node utils.js"` gives almost the same result as you.

But why is it that when running `bun run utils.js` and `node utils.js` commands individually, node still gives much better performance. 

Is there a problem with the `performance.now()` statement?

**Comment by Deyvi-dev** [comment]
The problem persists.

**Comment by tshmieldev** [comment]
```js
// Program counting fib(n)
let prev = BigInt(0);
let curr = BigInt(1);

let n = Number(process.argv.length > 2 ? process.argv[2] : null)

if(isNaN(n)) { console.log("Provide a valid number"); process.exit(0); }
let start = Date.now();
for(let i = 0; i < n; ++i){
    let tmp = prev + curr;
    prev = curr;
    curr = tmp;
}
let end = Date.now();
console.log(end - start);
```

This very simple snippet consistently runs about 2x slower in Bun than in Node and Deno.
Tested on M3 macbook air 16GB RAM
Bun 1.2.23

@birkskyum Perhaps reopen issue?
