### ISSUE TITLE
Vite dev is failing on 0.7 

### ISSUE THREAD

**Issue by MohammedWaheeb** [oven-sh/bun#3724]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

` bun --bun vite dev
`
returns 
`failed to load config from /Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/vite.config.ts
error when starting dev server:
Error: config must export or return an object.
    at <anonymous> (/Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:66014:15)
error: "vite" exited with code 1 (SIGHUP)
`

this is the vite config `import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react-swc'
import {posix} from "path";

const config = defineConfig({
    plugins: [react()],
    build: {
        outDir: "build",
    },
    server: {
        port: 3000,

    },
    resolve: {
        alias: [
            {find: "@/src", replacement: posix.resolve("/", "src")},
            {find: "src", replacement: posix.resolve("/", "/src")}
        ]
    },
})

export default config`

### What is the expected behavior?

Vite dev runs 

### What do you see instead?

import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react-swc'
import {posix} from "path";

const config = defineConfig({
    plugins: [react()],
    build: {
        outDir: "build",
    },
    server: {
        port: 3000,

    },
    resolve: {
        alias: [
            {find: "@/src", replacement: posix.resolve("/", "src")},
            {find: "src", replacement: posix.resolve("/", "/src")}
        ]
    },
})

export default config

**Comment by MohammedWaheeb** [comment]
I found the root cause of the issue, when vite is trying to load the config file it checking the export is an object by running to string and matching it with [object object], it works as intended in node but when running it with bun its an [object Module] so it fails

**Comment by paperclover** [comment]
If you set your package.json to have `"type": "module"` this should fix this issue but i think it's still a bug that `require` on an ESM module gives you a `[object Module]`

**Comment by MohammedWaheeb** [comment]
It didnt work , a sig fault on bun and it fails loading postcss on node 

The output using bun 
`error: "vite" exited with code 11 (SIGSEGV)
error: script "dev:bun" exited with code 11 (SIGSEGV)
`

output using node 
```

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/mohammedkalouti/Dev/S9OSS/InfolinkUi): [Failed to load PostCSS config] Failed to load PostCSS config (searchPath: /Users/mohammedkalouti/Dev/S9OSS/InfolinkUi): [ReferenceError] module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/postcss.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importDefault (file:///Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:36537:18)
    at async Object.search (file:///Users/mohammedkalouti/Dev/S9OSS/InfolinkUi/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:28973:38)
]

Node.js v18.12.1

````

**Comment by paperclover** [comment]
the pr i opened doesnt really address the postcss stuff. i'll take a look

**Comment by MohammedWaheeb** [comment]
the post css error happened when running with type module using node not bun
