### ISSUE TITLE
Incorrect decoding result when using Latin1 (`node:string_decoder`)

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#3738]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 6.4.4-arch1-1 x86_64

### What steps can reproduce the bug?

```JavaScript
const { StringDecoder } = require("string_decoder");
const assert = require("assert");

const buf = Buffer.from("dd", "hex");

const sd = new StringDecoder("latin1");

const s = sd.write(buf);

console.log(s);

assert.strictEqual(s, "Ý");

```

### What is the expected behavior?

No error.

### What do you see instead?

```
AssertionError: Expected values to be strictly equal:

'�' !== 'Ý'

 code: "ERR_ASSERTION"
```

### Additional information

In Bun, the decoding result is `\ufffd`.

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/2323f5d08d4c1d85d65ac89460dac592a7514fbd/src/bun.js/webcore/encoding.zig#L822-L835

Maybe `latin1` is missing here.

**Comment by Jarred-Sumner** [comment]
> https://github.com/oven-sh/bun/blob/2323f5d08d4c1d85d65ac89460dac592a7514fbd/src/bun.js/webcore/encoding.zig#L822-L835
> 
> Maybe `latin1` is missing here.

yeah, that's probably it

The Buffer.from() and Buffer.toString() case skips this code path because it can call `createUninitialized` and that used to not be exposed to C++
