### ISSUE TITLE
fs.writeFile mode is not Node.js compatible

### ISSUE THREAD

**Issue by gutenye** [oven-sh/bun#3740]
### What version of Bun is running?

0.6.14

### What steps can reproduce the bug?

```
import fs from 'fs'
fs.writeFileSync('a.txt', 'content', { mode: 33188 })
```

### What is the expected behavior?

Works fine on Node

### What do you see instead?

TypeError: Invalid mode: must be an octal number
 code: "ERR_INVALID_ARG_TYPE"

**Comment by Hanaasagi** [comment]
It looks like the upper limit of the value is constrained to `0o777` in bun, which is causing this issue.

https://github.com/oven-sh/bun/blob/636cec03e10ab487b1df3057aaab60b4d2b02c99/src/bun.js/node/types.zig#L1008-L1011

In Node.js, this limit is a u32.


https://github.com/nodejs/node/blob/9dd574c9e232515aa894795b8a2522f53024b6f7/lib/internal/validators.js#L69-L80

**Comment by Jarred-Sumner** [comment]
ah, we probably should wrap it
