### ISSUE TITLE
`WebSocket` client doesn't properly handle frame-fragmentation (continuation frame)

### ISSUE THREAD

**Issue by Sec-ant** [oven-sh/bun#3742]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

- Checkout this repo: https://github.com/Sec-ant/etts
- `cd ./etts` and install all dependencies: `bun install`
- Build the bun-oriented bundle: `bun run build`. This uses the native `WebSocket` implementation in Bun.
- Build the node-oriented bundle: `bun run build:node`. This uses the [`ws`](https://github.com/websockets/ws) nodejs library. 
- Test the bun-oriented script: `bun ./dist/bun/bin/main.js`. You can see received binary messages logged into the console. But if you're lucky, you'll also see an error thrown: `error: Invalid binary message format. Header content missing.` If no errors are thrown, `ctrl + c` and rerun `bun ./dist/bun/bin/main.js` for several times. This error is thrown from the script when the received binary message is not what we expected (with wrong starting bytes).
- Test the node-oriented script: `node ./dist/node/bin/main.js`. No errors observed, everything works fine no matter how many times I run it.

### What is the expected behavior?

I expect the bun-oriented script to work without errors thrown and be consistent with the node-oriented script.

### What do you see instead?

This bun-oriented script throws errors at unexpectable moments: `error: Invalid binary message format. Header content missing.`

![image](https://github.com/oven-sh/bun/assets/10386119/22d0da7a-8220-4916-911f-446a370decd0)

### Additional information

I did some further tests and I think the malformed binary messages received are actually continuation payloads. However AFAIK the continuation frames should be handled correctly by the `WebSocket` API internally.

**Comment by Sec-ant** [comment]
I don't know how to debug Zig or even where I should look at, so I just add a `console.log` in `receiver.js` of `ws` and run the node-oriented build. From the result we can see that the server will sometimes send back [fragmented messages](https://datatracker.ietf.org/doc/html/rfc6455#section-5.4) with an opcode of `0x0`. `ws` can handle these messages without a problem, but I'm pretty convinced the `WebSocket` API in bun cannot properly handle these. 

<img width="460" alt="websocket fragmentation" src="https://github.com/oven-sh/bun/assets/10386119/e66d2266-7a39-4ccc-baea-ab531ab6ad40">

ref: 
- https://datatracker.ietf.org/doc/html/rfc6455#section-5.4
- https://www.openmymind.net/WebSocket-Framing-Masking-Fragmentation-and-More

**Comment by iam4x** [comment]
Running into this as well, gentle bump. Thank's guys!

**Comment by arondius** [comment]
I ran into this too, using ethersjs and a websocketProvider.

**Comment by Mwni** [comment]
Same here, long JSON payloads get split into two individual messages, causing parsing errors on both. Happens with `ws` and the bun native `WebSocket`.

**Comment by Mwni** [comment]
Minimal repo: https://github.com/Mwni/bun-bugs/blob/main/websocket-fragmentation.js

**Comment by Electroid** [comment]
We need to test our WebSocket client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: https://github.com/oven-sh/bun/issues/6686

**Comment by Electroid** [comment]
Duplicate of #6686
