### ISSUE TITLE
Preact (not React) JSX doesn't work with `production` env

### ISSUE THREAD

**Issue by yusukebe** [oven-sh/bun#3753]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Install Preact:

```
bun add preact preact-render-to-string
```

Edit `tsconfig.json`:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
```

Edit `jsx.tsx`:

```ts
import { render } from 'preact-render-to-string'

export default {
  fetch: () => {
    return new Response(render(<h1>Bun</h1>), {
      headers: {
        'Content-Type': 'text/html',
      },
    })
  },
}
```

Run with `BUN_ENV=production`:

```
BUN_ENV=production bun run jsx.tsx
```

Blank, it doesn't work well:

<img width="419" alt="Screenshot 2023-07-23 at 7 50 13" src="https://github.com/oven-sh/bun/assets/10682/0d847303-5d47-4647-ad36-09ed8a3c39eb">

The same bug occurs with [hono/jsx](https://hono.dev/middleware/builtin/jsx).

### What is the expected behavior?

Should work.

### What do you see instead?

It works with React.

**Comment by Jarred-Sumner** [comment]
The bug is: Bun's JSX production transform is being executed when the jsxImportSource is not `"react"` and that is incorrect

**Comment by Jarred-Sumner** [comment]
The transpiled output becomes:
```js
import {
$$typeof as $$typeof_4ad651bb3f5de058
} from "bun:wrap";
import {render} from "/Users/jarred/Desktop/hoono/node_modules/preact-render-to-string/dist/index.module.js";
export default {
  fetch: () => {
    return new Response(render({
      $$typeof: $$typeof_4ad651bb3f5de058,
      type: "h1",
      key: null,
      ref: null,
      props: {
        children: "Bun"
      },
      _owner: null
    }), {
      headers: {
        "Content-Type": "text/html"
      }
    });
  }
};
```

**Comment by yusukebe** [comment]
Thanks Jarred.
