### ISSUE TITLE
Error when running express

### ISSUE THREAD

**Issue by timarnoldev** [oven-sh/bun#3765]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

import express from 'express';

### What is the expected behavior?

Run the script without an error

### What do you see instead?

[0.17ms] ".env"
1 | import express from 'express';
2 | 
3 | import cookieParser from 'cookie-parser'
   ^
SyntaxError: Unexpected identifier 'express'. import call expects one or two arguments.

**Comment by Jarred-Sumner** [comment]
sounds like a bug where bun is incorrectly choosing CommonJS for a file which is an ES Module

I don't think that's the complete reproduction though. We have tests that import express specifically

**Comment by timarnoldev** [comment]
I forgot to mention it's a typescript file. How can I specify the type?

**Comment by timarnoldev** [comment]
I resolved it. From an older test this was at the end of the file:

```
//access server for tests
module.exports = app;
```

It would be nice if bun could inform the user on which criteria the type is selected
