### ISSUE TITLE
bun fails to increment vite's port

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#3767]
### What version of Bun is running?

0.7.1

### What platform is your computer?

ubuntu 22.04

### What steps can reproduce the bug?

bun --bun vite

### What is the expected behavior?

```
Forced re-optimization of dependencies
Port 5000 is in use, trying another one...

  VITE v4.4.6  ready in 1662 ms

  ➜  Local:   http://localhost:5001/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

### What do you see instead?

```
Forced re-optimization of dependencies
358 |     try {
359 |       const tls = this.#tls;
360 |       if (tls)
361 |         this.serverName = tls.serverName || host || "localhost";
362 | 
363 |       this.#server = Bun.serve({
                        ^
error: Failed to start server. Is port 5000 in use?
      at listen (node:http:363:21)

  VITE v4.4.6  ready in 1512 ms

  ➜  Network: use --host to expose
  ➜  press h to show help
```

**Comment by hyuzea** [comment]
Fixed in 1.0.3 (f77df12894e7952ea58605432bf9f6d252fff273)

**Comment by emircanerkul** [comment]
@yus-ham Is it?

<img width="367" alt="image" src="https://github.com/oven-sh/bun/assets/11430795/54263c35-4d45-4008-9885-2cf6e909158a">

I'm using docker dev container.

**Comment by hyuzea** [comment]
@emircanerkul yes, previously it simply fails to start  the server. now vite works but it seems slightly different output. 
with `--bun` no server information printed but its actually the server started on port `5007` in my case. I think it is different issue

![image](https://github.com/oven-sh/bun/assets/3823496/40138aaf-cb91-451f-a041-bda381a20a77)

![image](https://github.com/oven-sh/bun/assets/3823496/82d6ca68-495f-439b-8f14-ee20deba82c0)

**Comment by jgiannuzzi** [comment]
@emircanerkul I had the same issue and it turns out it's due to the lack of IPv6 support in your container (that's the default with Docker). Here is how you can run vite in a container instead:
```
bunx --bun vite --host 0.0.0.0
```
