### ISSUE TITLE
toMatchSnapshot() breaks when test name contains `

### ISSUE THREAD

**Issue by alexandertrefz** [oven-sh/bun#3769]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Add a test that uses a snapshot and who's name contains a backtick (`), like this:

```
import {it, describe, expect} from "bun:test"

describe("Snapshot Tests", () => {
  it("`breaks`", () => {
    expect(1).toMatchSnapshot()
  })
})
```

### What is the expected behavior?

- running `bun test --update-snapshots` should create the snapshot file
- running `bun test` afterwards should work and not change the snapshot file

### What do you see instead?

- [x] running `bun test --update-snapshots` should create the snapshot file
- [ ] running `bun test` afterwards should work and not change the snapshot file

The test do not work, and if multiple calls to `toMatchSnapshot()` are present, all but the first test get appended to the snapshot file, probably because bun fails to parse the existing snapshot, since the ` in the testname did not get escaped, and thus break the file format.

**Comment by ian-weir** [comment]
I'll take a crack at this one

**Comment by v3nntrnx** [comment]
makes sense
![image](https://github.com/oven-sh/bun/assets/94789999/49626e40-516c-48c5-8f40-6202a3042d61)

**Comment by Itsamanjain** [comment]
Hi 
i want to work on this issue is it still open ?

**Comment by Hanaasagi** [comment]
There was a PR https://github.com/oven-sh/bun/pull/4146, but not merge now.

**Comment by Itsamanjain** [comment]
@Hanaasagi  need Help
After completing all the steps of setting it up locally, I got stuck on the last step. The binary should be located at `packages/debug-bun-{platform}-{arch}/bun-debug`. It is recommended to add this to your `$PATH`. 
However, when I add it to my path and then run `bun-debug`, it shows an error: "bun-debug: command not found." My platform is Darwin, and the architecture is aarch64.

**Comment by Hanaasagi** [comment]
1. Check if the compiled files exist. (`packages/debug-bun-{platform}-{arch}/bun-debug`)
2. The paths added to `$PATH` should be absolute path.
3. After modifying `$PATH`, some shell need to exec `reload` or `rehash`.

@Itsamanjain It might be helpful.

**Comment by Itsamanjain** [comment]
@Hanaasagi 
I tried the steps you mentioned, which provided an absolute path, but it still isn't working.
![Screenshot from 2023-09-13 22-31-43](https://github.com/oven-sh/bun/assets/112370476/d27433be-72c4-4c79-b61a-ce50225981e5)
![Screenshot from 2023-09-13 22-32-47](https://github.com/oven-sh/bun/assets/112370476/55960e28-3d99-485c-b7c7-b10621d55eb1)
![Screenshot from 2023-09-13 22-29-33](https://github.com/oven-sh/bun/assets/112370476/bb4fdcdc-12d3-4630-944c-985bb60e4277)

**Comment by Electroid** [comment]
Duplicate of #5272
