### ISSUE TITLE
Command 'bun' not found

### ISSUE THREAD

**Issue by datlechin** [oven-sh/bun#377]
After I installed `bun` successfully

I run `bun` and it show

Command 'bun' not found, did you mean:

  command 'bus' from deb atm-tools (1:2.5.1-4)
  command 'zun' from deb python3-zunclient (4.0.0-0ubuntu1)
  command 'ben' from deb ben (0.9.0ubuntu2)

Try: apt install <deb name>

**Comment by nekrondev** [comment]
Did you read what the installer tells you (adding the path to .bashrc and opening a new shell)?

```
nekron@dev:~$ curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
Bun was installed successfully to /home/heiko/.bun/bin/bun

Manually add the directory to your $HOME/.bashrc (or similar)

   BUN_INSTALL="/home/heiko/.bun"
   PATH="$BUN_INSTALL/bin:$PATH"

To get started, run

   bun --help
```

**Comment by datlechin** [comment]
@nekrondev here
I added to .bashrc and `source .bashrc`

<img width="452" alt="image" src="https://user-images.githubusercontent.com/56961917/177820385-c64ff805-c0cb-407d-8a0d-fe730ceb3fa1.png">

But it still not works

**Comment by icanc0** [comment]
it seems like you installed it under the root user, so it should be:
```
BUN_INSTALL="/root/.bun"
PATH="$BUN_INSTALL/bin:$PATH"
```

**Comment by datlechin** [comment]
Thanks @icanotc, it works now

<img width="670" alt="image" src="https://user-images.githubusercontent.com/56961917/177822735-11d0983e-7f49-497b-b7b7-c31f83d828ab.png">
