### ISSUE TITLE
Make all builtin `node:*` or `bun:*` modules use a variant of CommonJS

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#3773]
It looks like the crash in #3746 is caused by a module evaluation issue with ES Modules. If we switched our node/bun modules to use CommonJS we can lazy load them and also avoid any module evaluation linking issues

**Comment by wayjake** [comment]
<img src="https://media1.giphy.com/media/Yhzc40blQRNsJnr1Gq/giphy.gif"/>
