### ISSUE TITLE
Implement `cp` for `node:fs/promises`

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#3778]
### What is the problem this feature would solve?

I've tried completely replacing `node` with `bun` for a [fairly large project](https://github.com/cubing/cubing.js). There were a few incompatibilities that were easy to work around (as well as a general issue running Playwright), but the main thing that's not easy to fix within the project itself was a dependency using `cp` from `fs/promises`: https://nodejs.org/api/fs.html#fspromisescpsrc-dest-options

The function is marked as experimental, but has been available without a flag for two years.

### What is the feature you are proposing to solve the problem?

Implement it? 🤓

### What alternatives have you considered?

I can work around this, since I control the build dependency. But I thought I'd report that this was the main thing blocking us from a trivial switchover to `bun` for most of our project!

**Comment by Jarred-Sumner** [comment]
yeah we need to do this

I know how to make it super fast on macOS too

**Comment by janwilmake** [comment]
I also came across this. Now trying to work around it, but it would be great if there was more parity with fs and fs/promises.

In bun 0.7, it says it can't find "cp" from "node:fs" nor "node:fs/promises"

**Comment by janwilmake** [comment]
I've temporarily implemented it like so (probably not the best way, not sure if it covers everything):

```ts

import { stat, mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { path } from "node:path";

/**
 * Implements a primitive cp for bun
 * 
 * Usage:


bunCpAsync(
  "/path/fs-util/src",
  "/path/fs-util/src2",
  { recursive: true }
);


 */
export const bunCpAsync = async (
  source: string,
  destination: string,
  config?: {
    recursive?: boolean;
    /** NB: not implemented yet */
    preserveTimestamps?: boolean;
  }
) => {
  const stats = await stat(source);
  const isDirectory = stats.isDirectory();

  // Recursion case
  if (config?.recursive && isDirectory) {
    const files = await readdir(source);
    const paths = files.map((file) => ({
      source: path.join(source, file),
      destination: path.join(destination, file),
    }));

    if (!existsSync(destination)) {
      await mkdir(destination);
    }

    // find all files at source and run it for all of them
    await Promise.all(
      paths.map((x) => bunCpAsync(x.source, x.destination, config))
    );
    return;
  }

  // Base case, not recursive, but still folder
  if (isDirectory) {
    throw new Error("Should be a file. This is a folder");
  }
  // Base case, not recursive, and it's a file

  const file = Bun.file(source);

  if (!(await file.exists())) {
    throw new Error("This file doesn't exist");
  }

  await Bun.write(destination, await file.arrayBuffer());
};
```

Hope this helps.
