### ISSUE TITLE
error function in Bun.serve() ignores Promise<Response>

### ISSUE THREAD

**Issue by mzdr** [oven-sh/bun#3779]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```js
Bun.serve({
  development: true,
  port: 7777,
  fetch() {
    throw new Error("woops!");
  },
  // error: () => new Response("works"),
  error: () => Promise.resolve(new Response("does not work")),
  // ^-- always triggers Bun’s internal error page
});
```

### What is the expected behavior?

The async response in the error handler should print the data that was passed to the Response object.

### What do you see instead?

Bun’s internal error page always comes up when error returns a Promise<Response> instead of Response.

**Comment by simylein** [comment]
Can confirm that marking the error handler async has the same behaviour as long as there is no await call.

**Comment by Electroid** [comment]
See #8217
