### ISSUE TITLE
Run script in watch mode

### ISSUE THREAD

**Issue by denniscual** [oven-sh/bun#378]
First of all, I want to thank the team for your work to create this new Runtime environment. I believe this would really improve the JS ecosystem. 

I just have a question - Is there any way to run a script in watch mode? Let say I created a file to spin up a server. I ran it using `bun run` command. Right now, whenever I edit the file, it doesn't automatically reload the server. I checked the docs in github, but I can't see any section about this. Maybe I missed something? Or is there any chance "bun" will support this feature? I also do believe nodemon is not suitable for this case considering nodemon is using nodejs, that will defeat the purpose of wanting to use bun as the runtime environment.

**Comment by Pruxis** [comment]
Hey @denniscual have you tried `bun bun` instead of `bun run`

**Comment by Jarred-Sumner** [comment]
Here is an example that reloads code on every HTTP request:

https://github.com/Jarred-Sumner/bun/blob/57d9c500a8977a786e8973fd7cede9411e3b830f/packages/bun-landing/ssr.tsx#L1-L34

Since bun's JSX/TypeScript transpiler is builtin, the main step that's necessary is necessary is resetting the ESM module registry

`bun-livereload` is an npm package which does that

Eventually, bun will probably get a `--watch` but this should work okay for now

**Comment by denniscual** [comment]
Thanks @Jarred-Sumner , this `bun-livereload` could suffice for now. Looking forward to watch mode!

**Comment by copongcopong** [comment]
if you are still using `nodemon` (globally), you can use it with your bun project like:

```
nodemon --exec "bun run" my-bun-server.js
```

**Comment by thebearingedge** [comment]
You can also use `npx` to launch nodemon without the `install -g`

```shell
npx nodemon --exec "bun run" my-bun-server.js
```

**Comment by 174n** [comment]
Nodemon didn't work for me. I tried the following:
```bash
npx nodemon --exec "bun run" src/index.ts
npx nodemon --exec 'bun run src/index.ts' --watch src
```

And injecting some code just for live reloading doesn't seem like a good option.

**Comment by trylovetom** [comment]
this work for me in macOS 12.1

**package.json**
```json
{
  "scripts": {
    "dev": "nodemon --exec bun src/index.ts"
  }
}
```

**command**
```sh
bun run dev
```

**Comment by Electroid** [comment]
Bun now supports hot reloading with [`bun --hot`](https://github.com/oven-sh/bun#bun---hot)
```bash
bun --hot run [entrypoint]
```
