### ISSUE TITLE
`dirname` returns wrong result When the path is the root

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#3782]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 6.4.4-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```JavaScript
const path = require("path");
const assert = require("assert");
assert.strictEqual(path.posix.dirname("/"), "/");

```

### What is the expected behavior?

No `AssertionError``.

### What do you see instead?

```
AssertionError: Expected values to be strictly equal:

'.' !== '/'

 code: "ERR_ASSERTION"

```

### Additional information

I think this bug is related to https://github.com/oven-sh/bun/issues/2676

Here, the returned value should be determined by more context details instead of returning a `.`.

https://github.com/oven-sh/bun/blob/967ccb5d50b3ce163bb98fd125c56b039743de90/src/bun.js/node/types.zig#L1699-L1702

**Comment by Hanaasagi** [comment]
After running the `dirname` related test files in Nodejs, I found some other incompatibilities.

```JavaScript
assert.strictEqual(path.posix.dirname("////"), "/");
assert.strictEqual(path.posix.dirname("//a"), "//");
assert.strictEqual(path.win32.dirname("c:\\"), "c:\\");
assert.strictEqual(path.win32.dirname("\\"), "\\");

assert.strictEqual(path.win32.dirname("c:"), "c:");
assert.strictEqual(path.win32.dirname("c:foo"), "c:");
assert.strictEqual(path.win32.dirname("c:foo\\"), "c:");
assert.strictEqual(path.win32.dirname("\\\\unc\\share"), "\\\\unc\\share");
assert.strictEqual(path.win32.dirname("/"), "/");
assert.strictEqual(path.win32.dirname("////"), "/");
```


Ref: https://github.com/nodejs/node/blob/main/test/parallel/test-path-dirname.js

**Comment by Jarred-Sumner** [comment]
I’m surprised we still have these bugs

**Comment by Hanaasagi** [comment]
I think i can fix this.

**Comment by Jarred-Sumner** [comment]
Please do
