### ISSUE TITLE
Bun install stuck while installing nextjs project dependencies

### ISSUE THREAD

**Issue by divyam234** [oven-sh/bun#3789]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 5.15.0-76-generic x86_64 x86_64

### What is the expected behavior?

Bun install should succeed

### What do you see instead?

Bun  stuck with 100% cpu usage

**Comment by Electroid** [comment]
Hi, @divyam234 was this an actual issue? If so, we'd want to fix it.

**Comment by divyam234** [comment]
@Electroid It was issue due to peerDependencies in packages which was targeting react 17 or lower. For npm  using  legacy-peer-deps bypasses  this but in Bun installation was stuck .Although bun ignores peerDependencies by default don't know why this was happening.For now I have removed the package which was causing issue.
