### ISSUE TITLE
Implement performance.mark(), performance.measure()

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#3790]
These api's [aren't implemented in Bun](https://github.com/oven-sh/bun/issues/250#issuecomment-1240393129). 

> This is partially implemented, performance.now() exists but not performance.mark(), performance.measure(), nor the other Node-specific functions (they throw a not implemented error)

**Comment by birkskyum** [comment]
Apparently Jest rely on this as well

**Comment by Jordan-Hall** [comment]
@paperdave  this is the last major barrier for NX, Any chance we can stub this. I'm not good with bun internal so wouldn't know where to start :( Stubbing this will help with a few libraries i believe

**Comment by paperclover** [comment]
can you retry on canary. these methods already were stubbed I think.

**Comment by Jordan-Hall** [comment]
@paperdave  THANK YOU. It's worked no more patching NX, with a custom runner  #3786  is now supported

**Comment by ImLunaHey** [comment]
next returns `NaN` because of this 😅 

```
➜  watcher git:(main) bun --revision
1.0.18+a648ed9e6
➜  watcher git:(main) bun --bun next dev
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in NaNms
 ○ Compiling / ...
 ✓ Compiled / in 1022ms (491 modules)
 ✓ Compiled in 752ms (235 modules)
^C
                                                                                                                                                                      
➜  watcher git:(main) bun --node next dev
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 2.2s
 ○ Compiling / ...
 ✓ Compiled / in 619ms (491 modules)
 ✓ Compiled in 109ms (235 modules)
^C
```

**Comment by birkskyum** [comment]
Believe this is closed by
- https://github.com/oven-sh/bun/pull/8011

Duplicate issue
- https://github.com/oven-sh/bun/issues/4708
