### ISSUE TITLE
Web Crypto API doesn't keep the event loop alive

### ISSUE THREAD

**Issue by tomlarkworthy** [oven-sh/bun#3795]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 21.4.0 arm64 arm

### What steps can reproduce the bug?

Executing the following code does not log any output because the program exits suring the sign operation.
```
crypto.subtle
  .generateKey(
    {
      name: "HMAC",
      hash: { name: "SHA-512" },
    },
    true,
    ["sign"]
  )
  .then((key) => {
    return crypto.subtle.sign("HMAC", key, new TextEncoder().encode(""));
  })
  .then(console.log);
```

### What is the expected behavior?

It should print something like 
```
ArrayBuffer(64) [ 253, 33, 237, 69, 208, 124, 175, 243, 112, 88, 114, 143, 167, 55, 6, 107, 245, 207, 201, 226, 94, 130, 15, 60, 196, 91, 235, 217, 190, 111, 146, 221, 135, 39, 83, 114, 133, 236, 164, 97, 35, 119, 79, 117, 235, 164, 137, 162, 191, 247, 58, 192, 165, 170, 149, 56, 49, 84, 15, 143, 174, 108, 49, 76 ]
```

### What do you see instead?

Nothing, the program exits

### Additional information

Sometimes rearranging the code in unrelated ways seemed to make it work, but I cannot figure out the logic behind it. (maybe it depends on the key generated and hence nothing to do with my program modifications)

**Comment by Jarred-Sumner** [comment]
The bug is that Web Crypto API isn't keeping the event loop alive. Since the promise is not awaited, the application exits

**Comment by tomlarkworthy** [comment]
I see. I was trying to get aws4fetch working and found it was terminating early on the webcrypto stuff. Adding a `setTimeout(() => {}, 1000);` at the end "fixed" it. Cool. Yeah, this is still a bug for scripting but at least I have a workaround for aws SDK.
