### ISSUE TITLE
Add support for importing URLs in JavaScript

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#38]
Example:

```js
import { a, b, c } from "https://example.com/modules/some/module.js"
```

**Comment by Electroid** [comment]
We should do this, here are some follow up questions that should be discussed when we get closer:

* How long are URLs cached?
  * Forever or respect cache headers?
* Should `http` imports be allowed?
* How is the `Content-Type` determined?
  * Use the HTTP header or using the URL extension?
  * Can you override it?
* Can you define `https` imports in the `package.json`?
* Do we also support [import maps](https://github.com/WICG/import-maps#the-basic-idea)?
  * If so, how does it interact with the existing `package.json` dependencies?
  * If so, where do developers specify it? `import-map.json`? `"imports"` inside the `package.json`?
* Can you modify URLs to add authentication headers or search params?
  * Useful for fetching code from an internal source. 

We don't need to solve all these questions for the first iteration, but we should keep them in mind.

**Comment by guest271314** [comment]
This is possible with `deno` using an import map, e.g., 

deno.json
```
{
  "imports": {
    "base32-encode": "https://esm.sh/base32-encode@2.0.0",
    "cborg": "https://esm.sh/cborg@1.10.2",
    "commander": "https://esm.sh/commander@4.1.1",
    "mime": "https://esm.sh/mime@2.6.0",
    "to-data-view": "https://esm.sh/to-data-view@2.0.0",
    "wbn": "https://esm.sh/wbn@0.0.9",
    "wbn-sign-webcrypto": "https://raw.githubusercontent.com/guest271314/wbn-sign-webcrypto/main/lib/wbn-sign.js",
    "zod": "https://esm.sh/zod@3.22.4"
  }
}
```

```
deno run -A --config=deno.json --unstable-byonm index.js
```

To some extent using `package.json`, see `"wbn-sign-webcrypto": "https://github.com/guest271314/wbn-sign-webcrypto.git"`

```
{
  "name": "telnet-client",
  "version": "0.0.2",
  "description": "Generate Signed Web Bundle and Isolated Web App with Web Cryptography API to use Direct Sockets API",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/guest271314/telnet-client"
  },
  "dependencies": {
    "base32-encode": "^2.0.0",
    "mime": "^2.6.0",
    "wbn": "^0.0.9",
    "wbn-sign-webcrypto": "https://github.com/guest271314/wbn-sign-webcrypto.git",
    "zod": "^3.22.4"
  }
}

```

```
bun install
```

will fetch the GitHub repository.

I tried the same thing with a Gist using this pattern `https://gist.github.com/5834862.git` from https://stackoverflow.com/a/18019143 and `bun install` froze the OS.

**Comment by guest271314** [comment]
This works in v22.0.0-nightly2024011594f824a19d

test-network-imports.js
```
import * as base32Encode from "https://esm.sh/base32-encode@2.0.0";
console.log(base32Encode);
```

```
node --experimental-default-type=module --experimental-network-imports test-network-imports.js
```

**Comment by guest271314** [comment]
`bun` behaviour. The URL is imported as the `default` Module. This can't be WAI.

```
bun run test-network-imports.js
Module {
  default: "https://esm.sh/base32-encode@2.0.0",
}
```

**Comment by Electroid** [comment]
The reason this does not work is because we have not implemented it yet.

**Comment by guest271314** [comment]
I see that. I'm documenting how Bun and other JavaScript runtimes behave here.

**Comment by guest271314** [comment]
@Electroid Re

> - Do we also support [import maps](https://github.com/WICG/import-maps#the-basic-idea)?
> -- If so, how does it interact with the existing package.json dependencies?

I think the idea is to get away from `package.json` for import maps. 

Either the `deno` approach (`--config deno.json` which for some reason needs `--unstable-byonm` to _not_ create a `node_modules` folder) or the `node` approach (`--experimental-default-type=module` with `--experimental-network-imports` which does not cache anything anywhere that I can see) will work for `bun`.

**Comment by guest271314** [comment]
Per the `package.json` documentation https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository something like this should work

```

  "name": "network-import-test",
  "version": "0.0.0",
  "description": "Network import test",
  "license": "",
  "repository": {
    "type": "git",
    "url": "https://gist.github.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6.git"
  },
  "dependencies": {
    "buffer": "https://gist.github.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6.git"
  }
}
```

This is what happens

```
bun install
bun install v1.0.22 (b400b36c)
  🚚 buffer [4/4] error: InstallFailed extracting tarball for buffer  🚚 buffer error: ZlibError decompressing "buffer"

```

**Comment by guest271314** [comment]
This works for dynamic `import()`, not static `import` which is hoisted - unless the file already exists on the file system

```
import { writeFileSync } from "node:fs";
const url =
"https://gist.githubusercontent.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6/raw/aac580355cfe4b4a0d6e20a493fca028dfe62dbb/buffer.js";
const text = await (await fetch(url)).text();
writeFileSync("buffer.js", text);
const { Buffer } = await import("./buffer.js");
console.log(Buffer);
```

**Comment by guest271314** [comment]
One way I am able to do this

gist-plugin.js
```
import { plugin } from "bun";

plugin({
  name: "import-from-gist",
  setup(build) {
    build.module(
      // The specifier, which can be any string - except a built-in, such as "buffer"
      "https://gist.githubusercontent.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6/raw/aac580355cfe4b4a0d6e20a493fca028dfe62dbb/buffer.js",
      // The callback to run when the module is imported or required for the first time
      async () => {
        return {
          contents: await (await fetch("https://gist.githubusercontent.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6/raw/aac580355cfe4b4a0d6e20a493fca028dfe62dbb/buffer.js")).text(),
          loader: "js",
        };
      },
    );
  },
});
```

```
import { Buffer } from "https://gist.githubusercontent.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6/raw/aac580355cfe4b4a0d6e20a493fca028dfe62dbb/buffer.js";
console.log(Buffer.from([0]));
```

```
bun run  --preload ./gist-plugin.js ./test-network-imports.js
<Buffer 00>
```

**Comment by jamesdiacono** [comment]
Here is my polyfill for HTTP imports.

```javascript
const rx_any = /./;
const rx_http = /^https?:\/\//;
const rx_relative_path = /^\.\.?\//;

function load_http_module(href) {
    return fetch(href).then(function (response) {
        return response.text().then(function (text) {
            return (
                response.ok
                ? {contents: text, loader: "js"}
                : Promise.reject(
                    new Error("Failed to load module '" + href + "': " + text)
                )
            );
        });
    });
}

Bun.plugin({
    name: "http_imports",
    setup(build) {
        build.onResolve({filter: rx_relative_path}, function (args) {
            if (rx_http.test(args.importer)) {
                return {path: new URL(args.path, args.importer).href};
            }
        });
        build.onLoad({filter: rx_any, namespace: "http"}, function (args) {
            return load_http_module("http:" + args.path);
        });
        build.onLoad({filter: rx_any, namespace: "https"}, function (args) {
            return load_http_module("https:" + args.path);
        });
    }
});
```

**Comment by Jarred-Sumner** [comment]
You can implement URL imports via [`Bun.plugin`](https://bun.sh/docs/bundler/plugins). 

We aren't planning to implement 1st-party support for this unless significantly more people ask for it and a community plugin is popular enough to demonstrate it's worth the maintenance burden

**Comment by rivy** [comment]
😞

@Jarred-Sumner , that's disappointing. IMO, importing URLs is the *main* benefit of Deno over Bun. It's an important step in creating a more flexible module ecosystem and as a basis for simple local user scripts.

I've been very impressed with `bun`'s development up to now. You and your team have developed a cohesive and well-thought-out implementation with amazing speed and impressive ingenuity while maintaining strong compatibility with the Node ecosystem. You've also added lots of creative, developer-friendly features.

And so, I had been waiting with bated breath to see your implementation of URL imports, expecting it to be even better than Deno's implementation.

Direct importing modules via URLs allows users to do away with a great deal of useless Node infrastructure and the associated time wasting preliminaries (eg, `bun install`, ...). It allows the creation of simple, portable, singular/self-sufficient scripts which can be run from just about anywhere and even be wholly independent of the npm repository.

Instead, the alternative of using a to-be-written `Bun.plugin` is a deficient substitute. It's a multi-file solution which still requires surrounding project infrastructure, such as `bunfig.toml` and some sibling plugin script, all of which must travel with the script.

`bun compile` to a single executable might ultimately be a sufficient alternative, but it still adds user-side project complexity, a compile step, and, usually, dependence on the npm repository for imports.

I do hope you'll reconsider, or at least build in a better hook which wouldn't require user-created surrounding infrastructure.

Otherwise, I do sincerely want to thank you for the work that you've already done.

**Comment by b3nten** [comment]
Perhaps some of the bandwidth being spent on rewriting Lightingcss in zig could be spent on this? It is a web standard after all.

**Comment by b3nten** [comment]
It's a bit concerning that things like rewriting lightningcss from rust to zig takes precedence over this.

**Comment by evanwashere** [comment]
> 😞
> 
> @Jarred-Sumner , that's disappointing. IMO, importing URLs is the _main_ benefit of Deno over Bun. It's an important step in creating a more flexible module ecosystem and as a basis for simple local user scripts.
> 
> I've been very impressed with `bun`'s development up to now. You and your team have developed a cohesive and well-thought-out implementation with amazing speed and impressive ingenuity while maintaining strong compatibility with the Node ecosystem. You've also added lots of creative, developer-friendly features.
> 
> And so, I had been waiting with bated breath to see your implementation of URL imports, expecting it to be even better than Deno's implementation.
> 
> Direct importing modules via URLs allows users to do away with a great deal of useless Node infrastructure and the associated time wasting preliminaries (eg, `bun install`, ...). It allows the creation of simple, portable, singular/self-sufficient scripts which can be run from just about anywhere and even be wholly independent of the npm repository.
> 
> Instead, the alternative of using a to-be-written `Bun.plugin` is a deficient substitute. It's a multi-file solution which still requires surrounding project infrastructure, such as `bunfig.toml` and some sibling plugin script, all of which must travel with the script.
> 
> `bun compile` to a single executable might ultimately be a sufficient alternative, but it still adds user-side project complexity, a compile step, and, usually, dependence on the npm repository for imports.
> 
> I do hope you'll reconsider, or at least build in a better hook which wouldn't require user-created surrounding infrastructure.
> 
> Otherwise, I do sincerely want to thank you for the work that you've already done.

At the end of the day, most url imports go to npm proxies, and the rest are either unreliable or private sources. Instead of reinventing the wheel for the worse, bun focuses on making working with npm as easy as it can be.

One of the direct ways bun tries to improve on this is by solving the exact problem you describe. As long as there is no `package.json` file, bun will automatically handle dependency management for you (no `bun install`, node_modules, lock files) and just let you do `bun run script.js`

**Comment by oscarotero** [comment]
To me, this is a sad decision. As a Deno heavy user, I have been waiting a long time for this feature in order to try Bun and even adapt some of my http-import-based libraries to Bun. Now that Node has an experimental implementation, I was hoping Bun to implement it in order to have finally a standard and real cross-runtime (node, deno, bun, browsers...) way to import and run scripts.
I wish this decision is reconsidered in the future.

**Comment by guest271314** [comment]
> to have finally a standard and real cross-runtime (node, deno, bun, browsers...) way to import and run scripts.

Writing JavaScript runtime agnostic source code is tedious. Sometimes possible, sometimes not possible.

Deno throws for dynamic `import()` when the specifier and script are created in the running script [Deno dynamic import("./exports") throws module not found for "exports.js" dynamically created in the script](https://gist.github.com/guest271314/4637bb1288321256d7c14c72ebc81137). 

```
// Deno dynamic import("./exports") throws module not found for "exports.js" dynamically created in the script
// dynamic_import_always_throws.js
// References: https://www.reddit.com/r/Deno/comments/18unb03/comment/kfsszsw/ https://github.com/denoland/deno/issues/20945
// Usage:
// deno run -A dynamic_import_always_throws.js
// bun run dynamic_import_always_throws.js
// node --experimental-default-type=module dynamic_import_always_throws.js
import { open, unlink } from "node:fs/promises";
const runtime = navigator.userAgent;
const encoder = new TextEncoder();
try {
  const script = `export default 1;`;
  // deno
  if (runtime.includes("Deno")) {
    await Deno.writeFile("exports.js", encoder.encode(script));
  }
  // node
  if (runtime.includes("Node")) {
    const dynamic = await open("./exports.js", "w");
    await dynamic.write(script);
    await dynamic.close();
  }
  // bun
  if (runtime.includes("Bun")) {
    await Bun.write("exports.js", encoder.encode(script));
  }
  const { default: module } = await import("./exports.js"); // Raw string specifier
  console.log({ module });
  console.log({ runtime });
} catch (e) {
  console.log("Deno always throws.");
  console.log({ runtime });
  console.trace();
  console.log(e.stack);
} finally {
  console.log("Finally");
  // node, bun
  if (runtime.includes("Node") || runtime.includes("Bun")) {
    await unlink("./exports.js");
  } // deno
  else if (runtime.includes("Deno")) {
    await Deno.remove("./exports.js");
  }
}
```

If you read the fine print that decision is supposedly to support static analyzation for TypeScript. However, Bun supports running `.ts` files directly, too, and does not throw for the same code. `bun` is faster than `deno` and `node --experimental-strip-types` for running `.ts` files directly, and `.js` files in the domain of standard streams.

```
0	'nm_qjs'	0.09469999998807907
1	'nm_rust'	0.10389999997615815
2	'nm_tjs'	0.1372000000178814
3	'nm_wasm'	0.16619999998807908
4	'nm_typescript'	0.21030000001192092
5	'nm_bash'	0.2147999999821186
6	'nm_bun'	0.24419999998807906
7	'nm_deno'	0.29219999998807905
8	'nm_nodejs'	0.4075999999940395
9	'nm_d8'	0.40990000000596044
10	'nm_spidermonkey'	0.481
11	'nm_llrt'	0.6699000000059605
```

Deno's `compile` can produce an executable that is ~78 MB.

Bun's `build` works for bare `node:` and `npm:` specifiers. I usually use `bun` for bundling.

Node.js sold `npm` to GitHub, so GitHub's NPM has a bunch of packages.

`deno` has `fmt`. Bun doesn't support formatting directly, though does support formatting  with `build`

```
$ bun build fmt.js --no-bundle | bun -e 'Bun.write(Bun.file("fmt.js"), await Bun.file("/dev/stdin").text())'
```

We can create a `node_modules` with `deno add npm:package`. Deno supports `file:` protocol for `fetch()`, too.

Of course Bun still does not support HTTP/2 so we can full-duplex stream over WHATWG Fetch.

And so forth [Why I use node, deno, bun, qjs, tjs at the same time](https://gist.github.com/guest271314/da04334bb0dce19fcd970415bb003b02).

I use `node`, `deno`, `bun` and other JavaScript runtimes without entertaining a preference for either. They each has pros and cons and are all tools for the JavaScript developer.

I know which one I would pick if I had to pick one... but I don't have to pick one. I don't think anybody else does, either. Hack them all. Pull out the appropriate tool from the developer toolbox for the given task or requirement.

**Comment by rivy** [comment]
> At the end of the day, most url imports go to npm proxies, and the rest are either unreliable or private sources.

With CDNs and hash verification, I'd say that's debatable.

> Instead of reinventing the wheel for the worse, bun focuses on making working with npm as easy as it can be.
>
> One of the direct ways bun tries to improve on this is by solving the exact problem you describe. As long as there is no `package.json` file, bun will automatically handle dependency management for you (no `bun install`, node_modules, lock files) and just let you do `bun run script.js`

I do appreciate `bun run SCRIPT.js`. But it has some limitations and quirks (I was burned by an unexpected parent 'package.json'). And it seems so close to full http/https support... hence, my disappointment.

**Comment by maxmcd** [comment]
Has someone started any work on trying to support this with Bun.plugin?

**Comment by jamesdiacono** [comment]
@maxmcd https://github.com/oven-sh/bun/issues/38#issuecomment-2033654106

**Comment by theAJFM** [comment]
@maxmcd Thanks! I would add absolute path resolution to your plugin as well, just because `esm.sh` modules use it quite often.

```js
const rx_any = /./;
const rx_http = /^https?:\/\//;
const rx_relative_path = /^\.\.?\//;
const rx_absolute_path = /^\//;

function load_http_module(href) {
    return fetch(href).then(function (response) {
        return response.text().then(function (text) {
            return (
                response.ok
                ? {contents: text, loader: "js"}
                : Promise.reject(
                    new Error("Failed to load module '" + href + "': " + text)
                )
            );
        });
    });
}

Bun.plugin({
    name: "http_imports",
    setup(build) {
        build.onResolve({filter: rx_relative_path}, function (args) {
            if (rx_http.test(args.importer)) {
                return {path: new URL(args.path, args.importer).href};
            }
        });
        build.onResolve({ filter: rx_absolute_path }, function (args) {
            if (rx_http.test(args.importer)) {
                return {path: new URL(args.path, args.importer).href};
            }
        })
        build.onLoad({filter: rx_any, namespace: "http"}, function (args) {
            return load_http_module("http:" + args.path);
        });
        build.onLoad({filter: rx_any, namespace: "https"}, function (args) {
            return load_http_module("https:" + args.path);
        });
    }
});
```

**Comment by guest271314** [comment]
I guess Bun won't be implementing [WICG Import Maps](https://github.com/WICG/import-maps).

Unfortunate.

That technology is quite useful.

**Comment by KaKi87** [comment]
Hi,
How to use the polyfill ?
I'm still getting `ENOENT` errors on HTTPS imports after adding this code to the file.
Thanks

**Comment by jamesmcnamara** [comment]
@KaKi87 and others who try this:
Create this file in your project directory anywhere, say at a path `plugins/http.ts`

Then in your [`bunfig.toml`](https://bun.sh/docs/runtime/bunfig) add:
```toml
preload = ['./plugins/http.ts']
```

**Comment by rivy** [comment]
Unfortunately, this still requires surrounding infrastructure.

Being able to implement this as a single file would, IMO, be significantly more useful and portable.

For myself, despite liking `bun` and wanting a strong JS runtime contender, this keeps pushing me back to Deno. 😞

**Comment by janwilmake** [comment]
> Unfortunately, this still requires surrounding infrastructure.
> 
> Being able to implement this as a single file would, IMO, be significantly more useful and portable.
> 
> For myself, despite liking `bun` and wanting a strong JS runtime contender, this keeps pushing me back to Deno. 😞

100%. URL imports are a very useful feature, it makes entirely new patterns possible. Also having a standalone file being able to  be enough is super useful.

**Comment by kravetsone** [comment]
> Unfortunately, this still requires surrounding infrastructure.
> 
> Being able to implement this as a single file would, IMO, be significantly more useful and portable.
> 
> For myself, despite liking `bun` and wanting a strong JS runtime contender, this keeps pushing me back to Deno. 😞

Why u need it?

**Comment by KaKi87** [comment]
> Why u need it?

Just read the previous comment 🤦

**Comment by gaui** [comment]
Yes please, I love this feature in Deno!

**Comment by pqnet** [comment]
> You can implement URL imports via [`Bun.plugin`](https://bun.sh/docs/bundler/plugins).
> 
> We aren't planning to implement 1st-party support for this unless significantly more people ask for it and a community plugin is popular enough to demonstrate it's worth the maintenance burden

The issue with it being a plugin is that we need to install the plugin locally in the first place, because - uh - bun does not support importing URLs.

The main use case of this feature (writing simple standalone scripts without a `package.json`) cannot really be solved by plugins because to import those plugins you would need to have them downloaded in the local project cache, and not having a local `package.json` and `node_modules` is the main reason we would like to be able to import http directly in the first place. It's a catch 22.

This is to say that "let's see if a community plugin gains traction before implementing this in core" is not a fair standard to match for this feature to be considered relevant. Maybe having it in core behind an experimental feature flag could get you a more representative usage data.

**Comment by kravetsone** [comment]
> > You can implement URL imports via [`Bun.plugin`](https://bun.sh/docs/bundler/plugins).
> > We aren't planning to implement 1st-party support for this unless significantly more people ask for it and a community plugin is popular enough to demonstrate it's worth the maintenance burden
> 
> The issue with it being a plugin is that we need to install the plugin locally in the first place, because - uh - bun does not support importing URLs.
> 
> The main use case of this feature (writing simple standalone scripts without a `package.json`) cannot really be solved by plugins because to import those plugins you would need to have them downloaded in the local project cache, and not having a local `package.json` and `node_modules` is the main reason we would like to be able to import http directly in the first place. It's a catch 22.
> 
> This is to say that "let's see if a community plugin gains traction before implementing this in core" is not a fair standard to match for this feature to be considered relevant. Maybe having it in core behind an experimental feature flag could get you a more representative usage data.

also why node modules is the problem? Also please check auto install at bun docs

**Comment by redradist** [comment]
> Here is my polyfill for HTTP imports & nested relative import (based on [@jamesdiacono](https://github.com/jamesdiacono) polyfill and some edits)
> 
> ```
> // Enhanced HTTP imports plugin for Bun with nested relative import support
> // Based on https://github.com/oven-sh/bun/issues/38#issuecomment-2033654106 
> // and https://github.com/oven-sh/bun/issues/38#issuecomment-2558033081 
> 
> /* 
> Create this file in your project directory anywhere, say at a path plugins/http.ts 
>  
> Then in your bunfig.toml add: 
>  
> from the command line (https://bun.sh/docs/cli/run): 
>     bun test --preload ./plugins/http.ts 
>  
> OR 
>  
>     preload = ['./plugins/http.ts'] 
> */ 
> 
> const rx_any = /./;
> const rx_http = /^https?:[\\\/]/;
> const rx_path = /^\.\.?\//;
> const rx_http_url = /^https?:\/\/.+/;
> 
> // Cache for loaded modules to avoid duplicate fetches
> const moduleCache = new Map();
> 
> function load_http_module(href) {
>     // Check cache first
>     if (moduleCache.has(href)) {
>         return moduleCache.get(href);
>     }
>     
>     const promise = fetch(href).then(function (response) {
>         return response.text().then(function (text) {
>             if (!response.ok) {
>                 throw new Error("Failed to load module '" + href + "': " + text);
>             }
>             
>             // Determine the appropriate loader based on the URL
>             let loader = "js";
>             const url = new URL(href);
>             const pathname = url.pathname.toLowerCase();
>             
>             if (pathname.endsWith('.ts')) {
>                 loader = "ts";
>             } else if (pathname.endsWith('.tsx')) {
>                 loader = "tsx";
>             } else if (pathname.endsWith('.jsx')) {
>                 loader = "jsx";
>             } else if (pathname.endsWith('.json')) {
>                 loader = "json";
>             } else if (pathname.endsWith('.css')) {
>                 loader = "css";
>             }
>             
>             return {
>                 contents: text,
>                 loader: loader
>             };
>         });
>     }).catch(function(error) {
>         // Remove from cache if loading failed
>         moduleCache.delete(href);
>         throw error;
>     });
>     
>     // Cache the promise
>     moduleCache.set(href, promise);
>     return promise;
> }
> 
> function resolveHttpUrl(path, importer) {
>     try {
>         // If path is already a full HTTP URL, return as-is
>         if (rx_http.test(path)) {
>             return path;
>         }
>         
>         // If importer is an HTTP URL and path is relative, resolve against importer
>         if (importer && rx_http.test(importer)) {
>             // Normalize backslashes to forward slashes for URL resolution
>             const normalizedImporter = importer.replace(/\\/g, '/');
>             return new URL(path, normalizedImporter).href;
>         }
>         
>         return null;
>     } catch (error) {
>         //console.log.warn(`Failed to resolve URL: ${path} from ${importer}`, error);
>         return null;
>     }
> }
> 
> Bun.plugin({
>     name: "http_imports",
>     setup(build) {
>         // Handle direct HTTP/HTTPS imports
>         build.onResolve({filter: rx_http_url}, function (args) {
>             const url = new URL(args.path);
>             return {
>                 path: "//" + url.host + url.pathname + url.search + url.hash,
>                 namespace: url.protocol.slice(0, -1) // Remove the ':' from protocol
>             };
>         });
>         
>         // Handle relative imports from HTTP modules
>         build.onResolve({filter: rx_path}, function (args) {
>             // Debug logging
>             //console.log.log('Resolving relative path:', args.path, 'from importer:', args.importer, 'namespace:', args.namespace);
>             
>             if (args.importer && rx_http.test(args.importer)) {
>                 // Importer is a full HTTP URL, resolve relative path against it
>                 const resolvedUrl = resolveHttpUrl(args.path, args.importer);
>                 //console.log.log('Resolved to:', resolvedUrl);
>                 if (resolvedUrl) {
>                     const url = new URL(resolvedUrl);
>                     return {
>                         path: "//" + url.host + url.pathname + url.search + url.hash,
>                         namespace: url.protocol.slice(0, -1)
>                     };
>                 }
>             } else if (args.namespace === "http" || args.namespace === "https") {
>                 // Importer is in http/https namespace, reconstruct full URL and resolve
>                 const importerUrl = args.namespace + ":" + args.importer;
>                 const resolvedUrl = resolveHttpUrl(args.path, importerUrl);
>                 //console.log.log('Resolved to:', resolvedUrl);
>                 if (resolvedUrl) {
>                     const url = new URL(resolvedUrl);
>                     return {
>                         path: "//" + url.host + url.pathname + url.search + url.hash,
>                         namespace: url.protocol.slice(0, -1)
>                     };
>                 }
>             }
>         });
>         
>         // Handle loading from http namespace
>         build.onLoad({filter: rx_any, namespace: "http"}, function (args) {
>             const fullUrl = "http:" + args.path;
>             //console.log.log('Loading HTTP module:', fullUrl);
>             return load_http_module(fullUrl);
>         });
>         
>         // Handle loading from https namespace
>         build.onLoad({filter: rx_any, namespace: "https"}, function (args) {
>             const fullUrl = "https:" + args.path;
>             //console.log.log('Loading HTTPS module:', fullUrl);
>             return load_http_module(fullUrl);
>         });
>     }
> });
> ```

@Jarred-Sumner
Why not to add this possibility by default ? Wihtout using this duplicated plugin ...
For example 'preload = ['bun:plugin:http'] '
