### ISSUE TITLE
Install References non-existent readme section #unzip

### ISSUE THREAD

**Issue by lumodon** [oven-sh/bun#380]
Installing via script within WSL responds with:
```
user@LAPTOP-REDACTED:~$ curl https://bun.sh/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4906    0  4906    0     0  48098      0 --:--:-- --:--:-- --:--:-- 48098
error: unzip is required to install Bun (see: https://github.com/Jarred-Sumner/bun#unzip-is-required).
```

Navigating to https://github.com/Jarred-Sumner/bun#unzip-is-required yields top of `README.md` - indicating that `#unzip-is-required` is not a section that exists in readme.

**Comment by FinnRG** [comment]
This will be fixed by #305. Please run ```sudo apt install zip```. (I'm assuming you're using Ubuntu in WSL) and close this issue.
