### ISSUE TITLE
fetch implementation

### ISSUE THREAD

**Issue by janwilmake** [oven-sh/bun#3801]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Fetch implementation seems to have a small problem. If you fetch an url like this:

`www.google.nl?q=hi` 

It does not send the `q=hi` part

This is only sent if you put it like this:

`www.google.nl/?q=hi`

I guess it's the way it should be, but I also think some apis expect it to work (and it does work in the normal fetch)

I got stuck with this one: https://scrape.do/documentation/#quick-start

### What is the expected behavior?

It should also work without "/"

### What do you see instead?

It does not send the thing after "?"

**Comment by Jarred-Sumner** [comment]
Should be fixed in canary
