### ISSUE TITLE
bun install not working for workspace projects from root

### ISSUE THREAD

**Issue by AWare** [oven-sh/bun#3806]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. create a pair of empty packages, a & b where b is in a subfolder of b
2. add the subfolder to workspaces in a
3. add some dependency to b
4. install

```sh
mkdir -p a/packages/b
cd a 
bun init -y
cd packages/b
bun init -y
```
add `  "workspaces": ["packages/*"],` to `a/package.json`
and some dependency to `packages/b/package.json`
```sh
cd packages/b
cd ../..
bun install
```

### What is the expected behavior?

I expect the dependency to be present in `a/packages/b/node_modules`

### What do you see instead?

b's dependencies have not been installed

### Additional information

I would expect running `bun install` in `b` also to install the full project.

I might also expect some kind of ability to restrict or filter this like pnpm provides.

**Comment by Jarred-Sumner** [comment]
This was fixed some time ago, most likely in Bun v1.0.3 or so

```zsh
Build/worky2/a
❯ cd packages/b
  cd ../..
  bun install^C

Build/worky2/a
❯ code packages/b/package.json

Build/worky2/a
❯ cd packages/b
  cd ../..
  bun install
bun install v1.0.11 (8f3e278a)
 + b@workspace:packages/b

 1 package installed [99.00ms]
  Removed: 2

Build/worky2/a
❯ ls node_modules
b@  bun-types/  typescript/

Build/worky2/a
❯ cat package.json
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: package.json
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   "name": "a",
   3   │   "module": "index.ts",
   4   │   "type": "module",
   5   │   "workspaces": [
   6   │     "packages/*"
   7   │   ]
   8   │ }
───────┴───────────
```
