### ISSUE TITLE
Implement `bun init`

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#381]
npm init for bun
https://docs.npmjs.com/cli/v8/commands/npm-init

**Comment by nike-17** [comment]
isn't `bun create` do the same and even more?

**Comment by gkiely** [comment]
I mean for creating a project from scratch.
`git init`
`npm init -y`

Feel free to close @Jarred-Sumner  if you don't think it's a useful use case.

**Comment by Jarred-Sumner** [comment]
I think this is necessary as a simple way to get started

**Comment by imadbz** [comment]
can I do this? I will push a pull request for it

**Comment by Jarred-Sumner** [comment]
@imadbz sure! it will need to be done in Zig though

**Comment by Jarred-Sumner** [comment]
Another option is to make `bun create .` point to a default template

**Comment by imadbz** [comment]
> @imadbz sure! it will need to be done in Zig though

of course! on it.

**Comment by zhuzilin** [comment]
close the issue as we already have `bun init`.
