### ISSUE TITLE
Retain filename along with `blob` of uploaded files in `Request`

### ISSUE THREAD

**Issue by onionhammer** [oven-sh/bun#3811]
### What is the problem this feature would solve?

When parsing `formData` from a `Request`, a lot of information is lost, since all the content-disposition metadata about uploaded files is not accessible

![image](https://github.com/oven-sh/bun/assets/969938/e0b17a0c-fbf1-4448-b3c6-074173f2944f)

Example Elysia app:

```ts
const app = new Elysia()
    .post("/bind-faq-document", async ({ request, set, store }) => {
        const files = await request.formData();
        for (const [key, entry] of files.entries()) {
            console.log("LOG:", entry);
        }
    })
    .listen(3000);
```

Output:

```
LOG: Blob (72 bytes)
```

### What is the feature you are proposing to solve the problem?

Extend FormDataEntryValue to include information about the content-disposition

### What alternatives have you considered?

Parsing the raw request manually

**Comment by Jarred-Sumner** [comment]
Did you try .name or .type or .lastModified on the Blob?

**Comment by onionhammer** [comment]
@Jarred-Sumner those don't exist on the type, but if we ignore that:

![image](https://github.com/oven-sh/bun/assets/969938/0f5ae830-1dff-493e-9ad9-8d5c07992552)
![image](https://github.com/oven-sh/bun/assets/969938/e4e2a2d9-4129-43be-853b-a635c6998b6a)

If I run:
            console.log("PROPERTIES:", Object.getOwnPropertyNames(entry));
I get:
PROPERTIES: []

**Comment by TiBianMod** [comment]
+1

**Comment by TiBianMod** [comment]
@Jarred-Sumner can we take a look on this issue PLEASE.

**Comment by TiBianMod** [comment]
I think this is solved, https://github.com/oven-sh/bun/issues/4229#issuecomment-1685891960
