### ISSUE TITLE
Implement fs.watchFile

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#3812]
### Needed for Rollup support

When running Rollup, the missing fs.watchFile breaks.

➜ bun --bun run build-dev
$ rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev
[!] (plugin typescript) TypeError: _fs.watchFile is not a function. (In '_fs.watchFile(fileName, { persistent: !0, interval: pollingInterval }, fileChanged)', '_fs.watchFile' is undefined)

### What is the feature you are proposing to solve the problem?

Implement fs.watchFile ([support status](https://bun.sh/docs/runtime/nodejs-apis#node_fs))

**Comment by birkskyum** [comment]
Here is a reproduction for this issue:

https://github.com/oven-sh/bun/issues/1641#issuecomment-1672673300

**Comment by paperclover** [comment]
this is implemented (as of the pr which will be merged shortly) but it's really bad that rollup is using this api for file watching, it should use `fs.watch` instead.

**Comment by JonnyBurger** [comment]
Nice! This issue can be closed then?

**Comment by paperclover** [comment]
i forgot to close it sorry
