### ISSUE TITLE
Can't install on IPv6-only machine

### ISSUE THREAD

**Issue by kansson** [oven-sh/bun#3813]
### What platform is your computer?

Linux 5.15.0-78-generic aarch64 aarch64

### How did you attempt to install or upgrade?

`curl -fsSL https://bun.sh/install | bash`

### What do you see instead?

```zsh
curl: (7) Couldn't connect to server

error: Failed to download bun from "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-aarch64.zip"
```

### Additional information

Seems to be the same problem as this: https://github.com/k3s-io/k3s/issues/5921
Fixed this temporarily by buying an IPv4 for the VPS.

**Comment by patlux** [comment]
This is an issue with GitHub. Not bun.

**Comment by kansson** [comment]
> This is an issue with GitHub. Not bun.

You're right. Wanted to create an issue if someone else encounters this as the error message from `curl` isn't clear. Maybe we could add a small note in the docs about IPv6-only environments to clear out any confusion.
