### ISSUE TITLE
console.timeLog data arguments aren't logged in output

### ISSUE THREAD

**Issue by hanneswidrig** [oven-sh/bun#3821]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run the following code with Bun in a TypeScript file:

```typescript
console.time("log");
console.timeLog("log", "hello", "world");
console.timeEnd("log");
```

### What is the expected behavior?

```bash
Welcome to Node.js v16.20.1.
Type ".help" for more information.
> console.time("log");
undefined
> console.timeLog("log", "hello", "world");
log: 11.793ms hello world
undefined
> console.timeEnd("log");
```

### What do you see instead?

```bash
[0.12ms] log
[0.78ms] log
```

**Comment by birkskyum** [comment]
expected:

```sh
log: 0.027ms hello world
log: 0.585ms
```

**Comment by birkskyum** [comment]
it does log at the right times, it just only prints `log` and not the times etc.

**Comment by ChappIO** [comment]
We're running into the same issue. We are looking to benchmark our current NodeJS application against Bun but can't really get any insights due to missing output on `console.timeLog`.

**Comment by hanneswidrig** [comment]
@lqqyt2423 Thanks so much for fixing this with Bun `v1.0.15`!
