### ISSUE TITLE
Bun crashes doing text operations on Linux under Virtual Box

### ISSUE THREAD

**Issue by szatkus** [oven-sh/bun#3825]
### What version of Bun is running?

0.6.14, 0.7.0, canary

### What platform is your computer?

Kubuntu (Virtual Box)

### What steps can reproduce the bug?

I found two problems, both probably related.

This one gets into an infinite loop:
```js
const t = new TextDecoder();
const a = new Uint8Array([97]);
console.log(t.decode(a));
```

And this one segfaults:
```js
const b = new Blob([1,2,3]);
b.text().then(t => console.log(t));
```

Both work fine under Node.js

**Comment by Jarred-Sumner** [comment]
Can you try installing the -baseline build of Bun? https://github.com/oven-sh/bun/releases/download/canary/bun-linux-x64-baseline.zip

I wonder if the bug is that the install script installed the avx2-supporting build and the virtualized OS doesn't support it

**Comment by szatkus** [comment]
Works like a charm. Case solved, I guess.

How to disable AVX2 in my build?

**Comment by szatkus** [comment]
All right, the magic word is `CPU_TARGET = nehalem`.

Thank you. Everything works fine now.
