### ISSUE TITLE
`Function.prototype.toString` output is inconsistent depending on the function's origin

### ISSUE THREAD

**Issue by jakeboone02** [oven-sh/bun#3829]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Generate the `toString()` result of a function using a locally-defined function and an imported function (CJS vs ESM doesn't matter). Even if the function definitions are exactly the same, the strings won't match.

When Bun stringifies an imported a function, it puts spaces around the `=>` and indents the function body and closing bracket two more spaces than necessary.

Node generates the same string regardless of origin. Also, it outputs the exact characters of the original function source code, whereas Bun outputs a transpiled version. (This last point is not as important as the inconsistency between imported and local functions.)

The shell script below demonstrates the various formatting inconsistencies, along with the Node equivalents.

```shell
# Setup
echo "module.exports = () => {};" > fn.js
echo 'module.exports = () => {
  let x  =
      0;
  for (const i of [1, 2, 3]) {
    alert(  `formatting inconsistency ${i}`  );
  }
}' > fn-not-empty.js

echo "================"
echo " SOURCE FILES"
echo "================"

echo "\n./fn.js:"
cat fn.js

echo "\n./fn-not-empty.js:"
cat fn-not-empty.js

echo "\n================"
echo " BUN REPL"
echo "================"

echo "\nlocal empty function"
bunx bun-repl -e 'const fn = () => {}; console.log(`${fn}`);'
# ()=>{}

echo "\nimport empty function"
bunx bun-repl -e 'const fn = require("./fn"); console.log(`${fn}`);'
# () => {
#   }

echo "\nlocal non-empty function"
bunx bun-repl -e 'const fn = () => { let x = 0; }; console.log(`${fn}`);'
# ()=>{
#     let x = 0;
# }

echo "\nimport non-empty function"
bunx bun-repl -e 'const fn = require("./fn-not-empty"); console.log(`${fn}`);'
# () => {
#       let x = 0;
#       for (const i of [1, 2, 3])
#         alert(`formatting inconsistency ${i}`);
#     }

echo "\n================="
echo " NODE REPL"
echo "================="

echo "\nimport empty function"
node -e 'const fn = require("./fn"); console.log(`${fn}`);'
# () => {}

echo "\nlocal empty function"
node -e 'const fn = () => {}; console.log(`${fn}`);'
# () => {}

echo "\nimport non-empty function"
node -e 'const fn = require("./fn-not-empty"); console.log(`${fn}`);'
# () => {
#     let x  =
#         0;
#     for (const i of [1, 2, 3]) {
#       alert(  `formatting inconsistency ${i}`  );
#     }
#   }

echo "\nlocal non-empty function"
node -e 'const fn = () => { let  x  =  0 ; }; console.log(`${fn}`);'
# () => { let  x  =  0 ; }
```

### What is the expected behavior?

Bun should use the same `toString`/formatting algorithm regardless of a function's origin. As stated above, returning the original source _à la_ Node is not as important as being consistent.

My two cents: the `=>` should always be surrounded by spaces (e.g. `() => {}`).

### What do you see instead?

This is the result of the script above:

```
================
 SOURCE FILES
================

./fn.js:
module.exports = () => {};

./fn-not-empty.js:
module.exports = () => {
  let x  =
      0;
  for (const i of [1, 2, 3]) {
    alert(  `formatting inconsistency ${i}`  );
  }
}

================
 BUN REPL
================

local empty function
()=>{}

import empty function
() => {
  }

local non-empty function
()=>{
    var x = 0;
}

import non-empty function
() => {
    let x = 0;
    for (const i of [1, 2, 3])
      alert(`formatting inconsistency ${i}`);
  }

=================
 NODE REPL
=================

import empty function
() => {}

local empty function
() => {}

import non-empty function
() => {
  let x  =
      0;
  for (const i of [1, 2, 3]) {
    alert(  `formatting inconsistency ${i}`  );
  }
}

local non-empty function
() => { let  x  =  0 ; }
```

### Additional information

[Test repo](https://github.com/jakeboone02/bun-fn-str-test)

**Comment by simylein** [comment]
This may be related to #3248 because bun is running the minifier by default.

**Comment by jakeboone02** [comment]
Thanks, @simylein. IMHO the fact that it's minified is not important, as long as it's consistent.

**Comment by Electroid** [comment]
Going to close as duplicate of https://github.com/oven-sh/bun/issues/3248, we'll track this issue there.
