### ISSUE TITLE
Bun overrides "ws" package even when --target=node

### ISSUE THREAD

**Issue by jackson-bean** [oven-sh/bun#3844]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 | Using WSL

### What steps can reproduce the bug?

- `bun init`

```typescript
// index.ts
import { WebSocket } from "ws";

console.log(WebSocket);
```

- `bun build --target=node --outdir=dist index.ts`

```javascript
// dist/index.js
import {WebSocket} from "ws";
console.log(WebSocket);
```

### What is the expected behavior?

Bun should bundle the original/node "ws" package since --target=node.

### What do you see instead?

The bundle contains the import without the "ws" package bundled with it.

**Comment by jackson-bean** [comment]
Trying to get around this by using a plugin in the meantime. I don't know if it's just that I don't know much about making plugins, but when I try to build with the plugin, no output files are generated and no errors are thrown. And yes, "outdir" is specified. Don't know if this is an issue with me or bun.

**Comment by Jarred-Sumner** [comment]
confirming that it is a bug that it is using bun's module list to mark as external when --target=node instead of using a different list for node

**Comment by paperclover** [comment]
resolver.zig line 592 is where we are using .Aliases, which contains ws and all the bun modules. should we just make a separate comptime list for this?

**Comment by paperclover** [comment]
this is also a problem for `@vercel/fetch` or any other module we override at runtime.

**Comment by Hanaasagi** [comment]
trying to work on this
