### ISSUE TITLE
Importing "mysql2(/promise)" segfaults

### ISSUE THREAD

**Issue by Northernside** [oven-sh/bun#3864]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 5.10.0-23-amd64 x86_64 unknown

### What steps can reproduce the bug?

1. `bun run file.js` ([file.js](https://paste.laby.net/ozaloyikej.coffeescript))
2. Watch bun segfault

### What is the expected behavior?

I expect a) the console.log's to work and b) bun to not segfault

### What do you see instead?

When running the earlier stated code, I receive a "Segmentation fault".

```sh
04:17:31 core@ebio edb ±|mysql-switch ✗|→ cat issue.mjs 
console.log("Before Import");
import mysql from "mysql2/promise";
console.log("After Import");
04:17:32 core@ebio edb ±|mysql-switch ✗|→ bun issue.mjs 
Segmentation fault
```

**Comment by v3nntrnx** [comment]
Couldn't replicate on Linux 6.4.6-zen1-1-zen (even if changing extension to .mjs and/or changing package to just mysql2)
![image](https://github.com/oven-sh/bun/assets/94789999/8e3a6b9f-1248-4a82-ad2d-aa30059de1ea)

**Comment by Northernside** [comment]
Okay, seems like it has a lot to do (if not the same as) https://github.com/oven-sh/bun/issues/3312.
