### ISSUE TITLE
Missing entry in TLDR

### ISSUE THREAD

**Issue by HighPriest** [oven-sh/bun#3867]
### What is the type of issue?

Documentation is missing

### What is the issue?

tldr is a popular tool which stores and serves the most frequently used and the most useful, but easily forgettable commands for most of the *nix tools.

It is currently missing an entry for `bun` :)

### Where did you find it?

https://github.com/tldr-pages/tldr#how-do-i-contribute-to-tldr-pages

**Comment by paperclover** [comment]
Is there something we need to do in Bun to achieve this? I'm just confused why this is an issue open in our repo instead of theirs?

**Comment by HighPriest** [comment]
It is something you, people experienced with Bun, could do, to improve UX. If you would rather defer it onto the community. Please ping me and close this issue @paperdave

**Comment by Electroid** [comment]
I think this is something we'll open to the community.
