### ISSUE TITLE
fs.stat, fs.statSync do not support files > 2GB

### ISSUE THREAD

**Issue by asilvas** [oven-sh/bun#3868]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```
import fs from "fs";
import assert from "assert";

const BIG_FILE = "some_file_bigger_than_2GB";
const BIG_FILE_SIZE = 15438888903; // actual file size
const bigFileStat = fs.statSync(BIG_FILE, { bigint: false });
assert(
  bigFileStat.size === BIG_FILE_SIZE,
  `File ${BIG_FILE} should be ${BIG_FILE_SIZE}B but was ${bigFileStat.size}B`
);
```

### What is the expected behavior?

Should work with and without `bigint` set.

### What do you see instead?

Negative values.

**Comment by asilvas** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/849

**Comment by Jarred-Sumner** [comment]
Thanks for reminding
