### ISSUE TITLE
implement nodejs readdir recursive

### ISSUE THREAD

**Issue by adamburgess** [oven-sh/bun#3871]
### What is the problem this feature would solve?

Recursive directory reading

### What is the feature you are proposing to solve the problem?

Nodejs added the recursive option to fs.readdir in v20.1.0: https://nodejs.org/api/fs.html#fsreaddirpath-options-callback

```js
await fs.readdir('.', { recursive: true });
```

Would be great if bun could support this :)

**Comment by v3nntrnx** [comment]
can confirm it's missing
![image](https://github.com/oven-sh/bun/assets/94789999/f817199b-dff8-4f10-ac74-f8e47ad14d8e)

**Comment by v3nntrnx** [comment]
I'll look into it

**Comment by A-D-E-A** [comment]
I saw that the PR was closed.
Does it mean the issue won't be fixed, or can I try opening another PR with @TiranexDev's work (all credit goes to them, of course) and finish it if there's something to change?

**Comment by v3nntrnx** [comment]
Sure, you can use some of my work, I closed my PR for personal reasons, also about the "is this issue not being fixed", it will, just not with my code.

**Comment by adamburgess** [comment]
fixed by #7296

**Comment by knowhatamine** [comment]
opendir is missing too it seems...
