### ISSUE TITLE
It doesn't mention it will run `prepare` lifecycle script.

### ISSUE THREAD

**Issue by scinos** [oven-sh/bun#3874]
### What is the type of issue?

Documentation is missing

### What is the issue?

In https://bun.sh/docs/cli/install, it says "Run your project's {pre|post}install scripts at the appropriate time."

However, it fails to mention it will _also_ run `prepare` ([source](https://github.com/oven-sh/bun/blob/53cc4df191aa823c3a5c5a2a377701439a2d3f89/src/install/install.zig#L7946))

### Where did you find it?

https://bun.sh/docs/cli/install

**Comment by v3nntrnx** [comment]
cc @colinhacks
