### ISSUE TITLE
Could not build this project using Bun 0.7.1

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#3883]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 6.4.4-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- Upgrade to bun 0.7.1
- Clone this project
- Run `make setup`

### What is the expected behavior?

Build successfully.

### What do you see instead?

![2023-07-30_00-49](https://github.com/oven-sh/bun/assets/9482395/6dd5fae8-9ed8-4344-a720-793114e24c1c)

### Additional information

- Rolling back to version 0.7.0, `make setup` is ok.
- make package version
```
>>​ make --version
GNU Make 4.4.1
Built for x86_64-pc-linux-gnu

```

**Comment by v3nntrnx** [comment]
Happened to me too, just uninstall and install bun again


(by uninstall I mean removing ~/.bun directory)

**Comment by v3nntrnx** [comment]
![Screenshot_20230730_152214.jpg](https://github.com/oven-sh/bun/assets/94789999/928e196e-96f5-4d30-8a73-11de369f7a7e)

**Comment by Jarred-Sumner** [comment]
oh I think we need to set the cwd of the script to the package.json's source dir

**Comment by Hanaasagi** [comment]
After deleting `~/.bun`, running` make setup` is successful. However, if I install Bun using `curl -fsSL https://bun.sh/install | bash` after deleting `~/.bun`, I still encounter the same error when executing `make setup`.


But at least I can rebuild this project now, thank you @TiranexDev

**Comment by v3nntrnx** [comment]
np, but still. we need to fix this

**Comment by v3nntrnx** [comment]
I hit this issue again today, this time reinstalling bun didn't help and I had to remove bun entirely. I hope this gets fixed ASAP 
cc @Jarred-Sumner

**Comment by v3nntrnx** [comment]
Today in discord I found out that the fix for it is to remove bktree-fast package in package.json of the test folder and remove the post install script. Hopes it helps anyone else in the future.

**Comment by Hanaasagi** [comment]
@TiranexDev thank you.

**Comment by birkskyum** [comment]
@Hanaasagi , is this still an issue?

**Comment by Hanaasagi** [comment]
There's already a workaround.
