### ISSUE TITLE
error: InvalidURL with 0.7.1

### ISSUE THREAD

**Issue by johnnyreilly** [oven-sh/bun#3884]
### What version of Bun is running?

0.7.1

### What steps can reproduce the bug?

I'm on a campsite with limited access to internet and only on my phone so I'm going to do a bad job of reporting the issue. But here goes. As of 0.7.1 we're experiencing this issue:

```
error: InvalidURL


----- bun meta -----
Bun v0.7.1 (53cc4df1) Linux x64 #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023
InstallCommand: 
Elapsed: 47ms | User: 3ms | Sys: 12ms
RSS: 34.61MB | Peak: 28.72MB | Commit: 34.61MB | Faults: 134
----- bun meta -----

0   0x55b84e2fa1ab

Crash report saved to:
  ~/.bun-crash/v0.7.1-1690640718412.crash
```

You can see it manifest here:

https://github.com/johnnyreilly/blog.johnnyreilly.com/actions/runs/5700912256/job/15451138826#step:5:102

Rolling back to 0.7.0 resolves things. See:

https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/632

### What is the expected behavior?

Not to error 

### What do you see instead?

See above 

### Additional information

I'll try and provide more info when I get back from camping.

**Comment by 0x00ahmad** [comment]
I experienced the exact same issue in my pnpm+bun turborepo, the error arises during bun install (worked fine with bun 0.6.x, started when I just upgraded to v0.7.1 a few hours ago). But I haven't yet figured out exactly what causes the error.

**Comment by Jarred-Sumner** [comment]
We started using WebKit’s URL parser to validate and normalize registry URLs for bun install. Previously, Bun wasn’t really validating the URLs much. 

This error message needs to be improved and show the url it attempted to validate. 

Would you be able to paste the registry URLs being used? It’s possible there is a bug here separately I since it previously worked, or that their url validation is too strict

**Comment by johnnyreilly** [comment]
If it's `bun install` where the issue arises then I guess it'd be one of these dependencies: https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/main/trim-xml/package.json

```json
{
  "name": "trim-xml",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "bun-types": "^0.7.0",
    "fast-xml-parser": "^4.0.12",
    "simple-git": "^3.15.0",
    "typescript": "^5.0.0"
  },
  "scripts": {
    "start": "bun index.ts"
  }
}
```

**Comment by Jarred-Sumner** [comment]
@johnnyreilly it would be in your bunfig.toml if you have one set. The URL being validated is the one used for the npm registry.

**Comment by johnnyreilly** [comment]
I don't think I do have one of those - I'm guessing the https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/main/trim-xml/bun.lockb is no good?

**Comment by Jarred-Sumner** [comment]
It could also be an environment variable like any of:
```
"BUN_CONFIG_REGISTRY"
"NPM_CONFIG_REGISTRY"
"npm_config_registry"
```

**Comment by Jarred-Sumner** [comment]
To be clear, there's no way this isn't a bug in Bun since this worked in v0.7.0 and it suddenly stopped working in v0.7.1

**Comment by johnnyreilly** [comment]
It's running in the context of GitHub actions - does oven-sh/setup-bun@v1 set any environment variables?

**Comment by 0x00ahmad** [comment]
The bun app's `package.json` in question is this one in my monorepo:
```json
{
  "name": "@local101/wserver",
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "postinstall": "bun install --ignore-scripts",
    "dev": "PORT=9001 bun run src/index.ts",
    "start": "bun run src/index.ts"
  },
  "dependencies": {
    "@local101/constants": "^0.0.0",
    "@local101/logic": "^0.0.0",
    "@local101/db": "^0.0.0",
    "ioredis": "^5.3.2",
    "bcryptjs": "^2.4.3",
    "zod": "^3.21.4",
    "dotenv": "^16.1.4",
    "hono": "^3.2.2"
  },
  "devDependencies": {
    "@types/node": "^20.2.5",
    "@types/bcryptjs": "^2.4.2",
    "bun-types": "^0.6.2"
  }
}
```
and the `.env` file:
```bash
NODE_ENV=development
ENCRYPTION_KEY="12345678901234567890123456789012"
API_KEY="supersecretapikeytodosomesensitivestuffwith"
NEXTAUTH_SECRET=somegibberishhere
SOMETHING="20t7j984yx30j8273ty||2xt703m49y89hdk"
CC_CONFIRMATION_PWD="foobarbaz"
DEFAULT_ADMIN_PASSWORD=password
ADMIN_SECONDARY_PASSWORD=ytszlo7uy8ikr4dex3qa2wszlo0pu8
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/mdb?schema=public"
REDIS_URL="redis://localhost:6379"
WSERVER_API_URL="http://localhost:6969"
NEXTAUTH_URL="http://localhost:80"
```

Other than this, there are no other relevant files OR environment variables for bun which I have setup/can provide :/ (other than the bun.lockb).

**Comment by Jarred-Sumner** [comment]
I’m going to just revert my changes to bun install to validate URLs since
nobody asked for this to be changed in the first place. I suspect it’s
breaking due to /:authToken & other options in npm URLs which are
nonstandard
