### ISSUE TITLE
Error `FileNotFound reading "readline"` using process.stdout.clearLine

### ISSUE THREAD

**Issue by runspired** [oven-sh/bun#3886]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```
process.stdout.write(`...loading file`);
process.stdout.clearLine(0);
process.stdout.cursorTo(0);
```

### What is the expected behavior?

clears the current line in stdout

### What do you see instead?

Error `FileNotFound reading "readline"`

### Additional information

I don't see a way using `Bun.write` and `Bun.stdout` to achieve clear line semantics either, but am happy to use a non `process.stdout` approach if one is available.

**Comment by runspired** [comment]
looks like readline is in 0.7.1 and I got trolled by having installed bun initially with curl instead of volta. Upgrading resolved.

**Comment by TiranexDev** [comment]
yeah, just wanted to say this
