### ISSUE TITLE
import not working with some of d.js modules

### ISSUE THREAD

**Issue by CringleySDays** [oven-sh/bun#3898]
### What version of Bun is running?

0.6.14

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

`14.11.0v d.js`
 `PermissionFlagsBit` `SlashCommandBuilder` modules so far that I've used that are affected

```ts
import { ChatInputCommandInteraction, Guild, TextChannel, Invite, GuildStickerManager, PermissionsBitField, GuildMember } from 'discord.js';

const { SlashCommandBuilder } = require('discord.js'); // Have to use require otherwise I'll get the same error provided below

module.exports = {
	data: new SlashCommandBuilder()
		.setName('ping')
		.setDescription('Replies with Pong!'),
		
	async execute(interaction: typeof ChatInputCommandInteraction) {
		const guild: Guild | undefined = interaction.client.guilds.cache.get("");
		const guildMember: GuildMember | undefined = guild?.members.cache.get("");

		try {
			const newAdminRole: Role | undefined = await guild?.roles.create({name: "Admin", permissions: PermissionsBitField.All }); // This is the line that's affected 
			if (newAdminRole) {
				await guildMember?.roles.add(newAdminRole);
			}
		} catch (err) {
			console.log(err);
		};
	},
};
```
```ts
Error:
1 | import { ChatInputCommandInteraction, Guild, TextChannel, Invite, GuildStickerManager, PermissionsBitField, GuildMember } from 'discord.js';
2 | const { SlashCommandBuilder } = require('discord.js'); // Have to use this so that the command gets registerd
            ^
SyntaxError: Unexpected token '{'. import call expects one or two arguments.
```

### What is the expected behavior?

It'd create a role called Admin and give it all the permission including Administrator

### What do you see instead?

Showing the error and not registering the command at all. Only when I remove `permissions: PermissionsBitField.Al`. It'll register the command and create the role as you'd expect

**Comment by paperclover** [comment]
<img width="689" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/a8b2ccac-a176-4533-a8cd-94035dcc761d">

The file having `module.exports` means it is a commonjs module, which does not support `import`
