### ISSUE TITLE
`bun install` uses incorrect url with private registry

### ISSUE THREAD

**Issue by dave-orion** [oven-sh/bun#3899]
### What version of Bun is running?

0.7.1

### What steps can reproduce the bug?

Setup bunfig.toml for a private registry: 
`[install]
registry = {url="https://artifactory.xxx.yyy/artifactory/api/npm/my-npm/",token="..."}
`
run bun install

### What is the expected behavior?

Console logs show 
`GET https://artifactory.xxx.yyy/artifactory/api/npm/my-npm/@types/eslint-visitor-keys - 200
`
(or nothing)
packages are installed

### What do you see instead?

Console logs show 
`GET https://artifactory.xxx.yyy//artifactory/api/npm/my-npm/@types/eslint-visitor-keys - 500
`

packages are not installed

### Additional information

Private registry has a self signed cert, but shouldn't affect this behaviour.

**Comment by Jarred-Sumner** [comment]
Looks like a bug when joining the URL
