### ISSUE TITLE
Allow build to output code that runs on Node.js

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#39]
Bun does not emit code that runs in Node.js. It's very close to doing that, but does not yet.

Blockers:

- [ ]  `require` shouldn't import the bundler runtime
- [ ]  `node:fs` and other `node:*` prefixes need to be marked as external
- [ ]  Parallelize `bun build` for performance
- [ ]  Output as CommonJS?

The best approach might be a Node.js `require` and/or ESM loader hook. This would involve using NP-API and writing C bindings. This would make the filesystem watcher work in Node.

**Comment by Electroid** [comment]
We implemented this with `bun build --target=node`. There are bugs, but there are plenty of issues tracking it.
