### ISSUE TITLE
bun install not working...

### ISSUE THREAD

**Issue by GuilhermeViterboGalvao** [oven-sh/bun#390]
The process stuck while it is trying to install my project dependencies.
![Screenshot from 2022-07-07 16-34-54](https://user-images.githubusercontent.com/3185451/177857903-dea15727-9b8c-4ed8-82e8-afbfd54457c4.png)

**Comment by nrademacher** [comment]
Same issue on macOS 12.4 x64, and `bun c` gets stuck on `Fetching manifest...` or `Fetching package.json...` for `bun c <framework>`

**Comment by iddar** [comment]
same here,  on Arch Linux. the command ends ok but does install anything. 
Only create a node_modules folder and don't add de dependecie to the package.json

![image](https://user-images.githubusercontent.com/199103/177887723-934bc259-0c94-46a9-91d6-f1d7fedaf663.png)

**Comment by nrademacher** [comment]
> Same issue on macOS 12.4 x64, and `bun c` gets stuck on `Fetching manifest...` or `Fetching package.json...` for `bun c <framework>`

This seems to work now! I guess there was some temporary server issue causing this
