### ISSUE TITLE
bun is loading the ESM version instead of the CommonJS version

### ISSUE THREAD

**Issue by KagChi** [oven-sh/bun#3901]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```ts
import { StoreRegistry } from "@sapphire/pieces";

const store = new StoreRegistry();
await store.load();
```

### What is the expected behavior?

It must be not show the error like node does

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/59391215/9ae96087-0664-4268-9afb-52da6f884780)

**Comment by paperclover** [comment]
should be fixed in next version
