### ISSUE TITLE
`XLSX.read` crashes Bun

### ISSUE THREAD

**Issue by emadda** [oven-sh/bun#3914]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin arm64 arm

### What steps can reproduce the bug?

I am trying to run this function: https://docs.sheetjs.com/docs/api/parse-options

The input is a Uint8Array. It works with Node.js, but with Bun it never returns from the `read` function with no output to stdout.

Is there a flag I can use to see the Bun error logs, or a debugger to follow the execution?

```
const workbook = XLSX.read(utf8ar_xlsx, {type: "array"});
```

Version: `"xlsx": "^0.18.5"`

### What is the expected behavior?

Function returns

### What do you see instead?

No return, process does nothing and stalls.

### Additional information

file.xlsx:

a | b
-- | --
1 | 1
2 | 2

**Comment by emadda** [comment]
[example-a.xlsx](https://github.com/oven-sh/bun/files/12232372/example-a.xlsx)

This is the file that crashes Bun when passed to `XLSX.read`

**Comment by Hanaasagi** [comment]
#### reproduce code

```JavaScript
import fs from "fs";
import XLSX from "xlsx";

fs.readFile("./example-a.xlsx", (err, result) => {
  if (err) throw err;

  const raw = new Uint8Array(result.buffer);

  const workbook = XLSX.read(raw, { type: "array" });
  console.log(workbook);
});

```


coredump stack

![2023-08-08_23-55](https://github.com/oven-sh/bun/assets/9482395/08f80975-0f61-469a-88d9-b00375e6555e)


This `encoding` might be Latin1.


Updated:

Here is the minimal reproduction code without relying on any third-party libraries:

```JavaScript
import assert from "assert";

const raw = Buffer.from([0, 104, 0, 101, 0, 108, 0, 108, 0, 111]);
const data = new Uint16Array(raw);

const decoder = new TextDecoder("UTF-16");
const str = decoder.decode(data);
assert.strictEqual(str, "\x00h\x00e\x00l\x00l\x00o");

console.log("panic now");
const buf = Buffer.from(str, "latin1");
console.log("never reach here");
assert.deepStrictEqual(buf, raw);
```
