### ISSUE TITLE
Implement `URL.createObjectURL`

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#3925]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

const blob = new Blob(['inline worker'], {type: 'text/plain'});

console.log(URL.createObjectURL(blob)); // undefined

### What is the expected behavior?

A reference url like blob:null/dd56aa40-18c1-4b56-a12b-f4346251b814

**Comment by Jarred-Sumner** [comment]
Confirming this isn’t implemented yet

**Comment by estubmo** [comment]
Should URL be marked as fully implemented when this is missing?
https://bun.sh/docs/runtime/nodejs-apis#url

**Comment by takinabradley** [comment]
I would have preferred it wasn't. 

When I needed this, I think I got around it by using `Bun.pathToFileURL` to nab me a file URL. May work for someone else who needs file URLs.

**Comment by truongan07** [comment]
> I would have preferred it wasn't.
> 
> When I needed this, I think I got around it by using `Bun.pathToFileURL` to nab me a file URL. May work for someone else who needs file URLs.

Bun.pathToFileURL is so cool and i use more tiny scripts in worker at anywhere on module and more modules. I can't create more files to only use worker.  I create a function in library and call it. So, needed **inline worker**

**Comment by cyfung1031** [comment]
Any roadmap for implementing this? This is somehow important for using WebWorker.

**Comment by truongan07** [comment]
This method is very important. priority implement please

**Comment by truongan07** [comment]
@Jarred-Sumner @Electroid high priority implementation, please
