### ISSUE TITLE
Provide native packages or alternatives to [curl | bash]

### ISSUE THREAD

**Issue by Everspace** [oven-sh/bun#393]
`curl example.com/installer | bash` is one of the eon-old "bad things to do" in a Unix-y environment.

It would be nice if this wasn't the default presented.

One of:
- A `make install` command from source.
- Native `.deb` or `.rpm` distributions.
- general binary installation instructions and needs

In the installer, things like needing `BUN_INSTALL` defined is a smell to me since it's otherwise completely standalone, and 99% of this installer could be instead "Extract somewhere and add to path however you please (Here's how to add completions)" and would otherwise avoid this.

**Comment by Jarred-Sumner** [comment]
The installer is the easiest way to get bun installed across different linux distributions and macOS.

Linux distributions and package managers are welcome to add support for Bun.

Using the installer is optional and the tarball can just be downloaded separately.

`BUN_INSTALL` is defined for `bun install`, bun's package manager, so it knows where to put cached installs

**Comment by Everspace** [comment]
Then that should be `BUN_CACHE` or similar, and defaulting to `~/.bun/cache` like `yarn` or `npm`.
