### ISSUE TITLE
`os.freemem()` node compatibility

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#3944]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 6.4.7-arch1-2 x86_64 unknown

### What steps can reproduce the bug?

```JavaScript
const os = require("node:os");

const free_memory = os.freemem();
const free_mem_in_gb = Math.floor(free_memory / 1024 / 1024 / 1024);

console.log("Free memory: " + free_mem_in_gb + "GB");

```

### What do you see instead?

![2023-08-03_20-41](https://github.com/oven-sh/bun/assets/9482395/bd47021d-1279-4ca6-a8ee-e3c9ed3af70c)

### Additional information

- node version: v18.16.0

It seems that bun uses the `free` field, while node uses the `available` field.

**Comment by pcapp** [comment]
I am taking a look at this. Based on [PR 4012](https://github.com/oven-sh/bun/pull/4012) commentary and my own digging, I see Node.js using libuv to do the the following:
1. Attempting to grab the total memory from /proc/meminfo
2. Falling back to a sysinfo call and using data from the returned struct to calculate the total memory.
