### ISSUE TITLE
bun —hot clear screen option

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#3954]
### What is the problem this feature would solve?

Hot reloading an http server with `bun —hot` multiple times leads to a lot of output in the terminal. 

### What is the feature you are proposing to solve the problem?

Similar to how `bun —watch` clears the screen on file change it could be done as well for `bun —hot`

### What alternatives have you considered?

Running `console.clear()` beforehand

**Comment by Jarred-Sumner** [comment]
do you think it should be the default?

**Comment by simylein** [comment]
That would be awesome and match the `--watch` behaviour

**Comment by simylein** [comment]
This is now available on canary and will be in the next release.

**Comment by comunidadio** [comment]
> That would be awesome and match the `--watch` behaviour

Currently clearing the screen is not the default behaviour for bun --watch actually.
https://github.com/oven-sh/bun/issues/3951

**Comment by simylein** [comment]
Yes in the test context currently not but I think this will be adjusted in the future. 
For normal file watching and hot reloading it is. 

https://github.com/oven-sh/bun/assets/67859356/5afcb7c7-ef65-4532-b5f5-34e3ea75c688


https://github.com/oven-sh/bun/assets/67859356/8c72a79d-59c4-4ceb-807d-eb90741e6a2d
