### ISSUE TITLE
macro serialization broken for when returning escaped string

### ISSUE THREAD

**Issue by cztomsik** [oven-sh/bun#3957]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

see the screenshot for a complete repro

![image](https://github.com/oven-sh/bun/assets/3526922/63dc7660-162c-44e9-893c-4aafdb24f08c)

### What is the expected behavior?

it should not fail (it works if I remove escaping) and I think it should not even un-escape the saved result/ast - or at least it should definitely not do so for `\\`

### What do you see instead?

`bun run` fails

### Additional information

@dylan-conway

**Comment by cztomsik** [comment]
also (probably unrelated and not that important to fix), it seems that using `import.meta.dir` in the argument does not work:

```
embedFileMacro(`${import.meta.dir}/index.html`)
```

sefaults:

```
error: script "dev" exited with code 11 (SIGSEGV)
```

**Comment by cztomsik** [comment]
I think the TypedArray serialization does not work either - I tried to do `new Uint8Array(await f.arrayBuffer())` and I got

```
error: cannot coerce Uint8Array to Bun's AST. Please return a valid macro using the JSX syntax
```

where `f` is result of `Bun.file()`

**Comment by Jarred-Sumner** [comment]
hm, new Uint8Array is supposed to become a base64-encoded string that gets converted into a Uint8Array

If you wrap it in a `Response`, does it work? `new Response(f)` (or if `f` is already a `Response`, return that)

**Comment by cztomsik** [comment]
I have tried that before (both, returning `Bun.file()` from macro and then also `Response(Bun.file())`) and then the result is empty string.

What I'm doing right now (and what works), is to encode it into base64 like this:
(simple `btoa(await blob.text())` didn't work because of unicode)

![image](https://github.com/oven-sh/bun/assets/3526922/fc61eec2-3fc9-449f-a09b-fcd71db8b965)
