### ISSUE TITLE
Error installing packages from workspaces when using workspace protocol

### ISSUE THREAD

**Issue by scinos** [oven-sh/bun#3958]
### What version of Bun is running?

0.7.1

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Create a `package.json` with

```
{
  "name": "bun-workspaces",
  "module": "index.ts",
  "type": "module",
  "workspaces": [
    "packages/a"
  ],
  "dependencies": {
    "a": "workspace:*"
  }
}
```

And a `packages/a/package.json` with:

```
{
  "name": "a",
  "version": "1.0.0"
}
```

Then run `bun install`.

### What is the expected behavior?

It installs without errors. `node_modules/a` is linked to `packages/a`.

### What do you see instead?

Got an error:

```
bun install v0.7.1 (53cc4df1)


error: workspace dependency "a" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

### Additional information

Looks related to the `"workspace:*"` dependency, because depending on just `"*"` seems to work.

**Comment by Jarred-Sumner** [comment]
is `"a"` the workspace package's package.json name or the folder name?

**Comment by scinos** [comment]
The page named `a` (declared in its package.json) lives in the folder `packages/a`.

**Comment by Jarred-Sumner** [comment]
@scinos we are having some trouble reproducing this issue

Can you paste the exact steps you took to reproduce the issue? This is what I tried
```sh
~/Desktop is 📦 v0.1.0
❯ mkdir workspace-repro

~/Desktop is 📦 v0.1.0
❯ cd workspace-repro

~/Desktop/workspace-repro
❯ vim package.json

~/Desktop/workspace-repro
❯ mkdir -p packages/a

~/Desktop/workspace-repro
❯ vim packages/a/package.json

~/Desktop/workspace-repro took 4s
❯ bun install
bun install v0.7.2 (9574db35)
 + a@workspace:packages/a

 1 packages installed [6.00ms]

~/Desktop/workspace-repro
```

<img width="279" alt="image" src="https://github.com/oven-sh/bun/assets/709451/60515784-8218-4b4a-a2c5-b7beac2e21c7">

**Comment by scinos** [comment]
My bad, I missed an important step: it fails the second time if you delete `node_modules`. Looks like a dupe of #3685 with a different error message.

```
[sergio:~/src/experiments/bun-workspaces] % cat package.json           
{
  "name": "bun-workspaces",
  "module": "index.ts",
  "type": "module",
  "workspaces": [
    "packages/a"
  ],
  "dependencies": {
    "a": "workspace:*"
  }
}
[sergio:~/src/experiments/bun-workspaces] % cat packages/a/package.json
{
  "name": "a",
  "version": "1.0.0"
}
[sergio:~/src/experiments/bun-workspaces] % bun install
bun install v0.7.1 (53cc4df1)
 + a@workspace:packages/a

 1 packages installed [5.00ms]
[sergio:~/src/experiments/bun-workspaces] % rm -fr node_modules       
[sergio:~/src/experiments/bun-workspaces] % bun install
bun install v0.7.1 (53cc4df1)


error: workspace dependency "a" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

![image](https://github.com/oven-sh/bun/assets/975703/b85bebd1-0aad-4abe-81df-3227045324e1)

**Comment by Jarred-Sumner** [comment]
That reproduces it, thank you
