### ISSUE TITLE
Compatibility data mapping

### ISSUE THREAD

**Issue by zloirock** [oven-sh/bun#396]
Is there a way to know a JavaScriptCore version (-> WebKit and Safari with the same engine version) for each current and future `bun` version? For example, for each NodeJS version, we can see the related V8 (-> Chrome) version [here](https://nodejs.org/dist/index.json). `process.versions.webkit` is just a hash:

```js
process.versions.webkit; // => 9a039f4901c48680700174c28dd4693873f7593a
```

Why it's required? To simplify getting compatibility data (sure, not for all) for `bun`. This data can be used by `core-js` and, for example, `babel` to include only required polyfills and transpile only unsupported features.

**Comment by Jarred-Sumner** [comment]
The build of WebKit bun uses is here: https://github.com/Jarred-Sumner/WebKit

The version of Safari that maps to, I think, is the Safari Technology Preview released after the latest upstream WebKit commit in the forked repository

**Comment by zloirock** [comment]
Clear, thanks.
