### ISSUE TITLE
Can't use a plugin without `console.log` first

### ISSUE THREAD

**Issue by altano** [oven-sh/bun#3968]
### What version of Bun is running?

0.7.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

If I run this example [from the bun documentation](https://bun.sh/docs/bundler/plugins#third-party-plugins):

```test.tsx
import { plugin } from "bun";
import mdx from "@mdx-js/esbuild";

plugin(mdx());

import { renderToStaticMarkup } from "react-dom/server";
import Foo from "./face.mdx";
console.log(renderToStaticMarkup(<Foo />));
```

I get this error:

```
1 | 
2 | globalThis.Bun.plugin(mdx());
                         ^
ReferenceError: Can't find variable: mdx
      at /Users/alan/src/bun-messing/mdx/test.tsx.plugin.tsx:2:22
```

But if i add a `console.log`:

```test.tsx
import { plugin } from "bun";
import mdx from "@mdx-js/esbuild";

console.log(mdx);

plugin(mdx());

import { renderToStaticMarkup } from "react-dom/server";
import Foo from "./face.mdx";
console.log(renderToStaticMarkup(<Foo />));
```

I don't get the error:
```
➜  bun mdx/test.tsx
[Function: esbuild]
<h1>Hello</h1>
<p>I&#x27;m a computer. <strong>STOP</strong> all the downloadin.</p>
```

### What is the expected behavior?

No error when using script from documentation

### What do you see instead?

Error:

> ReferenceError: Can't find variable: mdx

**Comment by vjpr** [comment]
Duplicate: https://github.com/oven-sh/bun/issues/3068
