### ISSUE TITLE
code 11 (SIGSEGV) sqlite crash with `0.7.2`?

### ISSUE THREAD

**Issue by charnould** [oven-sh/bun#3977]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Unfortunately, I don't know how to explain it.
- My code was working fine with `0.7.1`
- I've updated to `0.7.2` this morning
- And now, every page where `sqlite` is used crashes with `error: script "dev:start" exited with code 11 (SIGSEGV)`
- When I downgrade to `0.7.1`, it works again...

If there is a command to log debug code, let me know.

### What is the expected behavior?

It should work on `0.7.2`

### What do you see instead?

It crashes

**Comment by Jarred-Sumner** [comment]
Can you paste a repro of some code which crashes? There was a crash after the JSC upgrade we did, but I fixed that and it reproduced in tests. Guessing there’s another case but need a reproduction to be sure

**Comment by Jarred-Sumner** [comment]
Fixed in 637a38f394704eaea29b503a69d554b5726d6214. Please upgrade via `bun upgrade --canary` in an hour or two to get the update before it's released.

**Comment by charnould** [comment]
Thanks. You're to fast for me!
