### ISSUE TITLE
Bun does not stay alive when chokidar is watching files

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#3978]
### What version of Bun is running?

0.7.3

### What steps can reproduce the bug?

```
import chokidar from 'chokidar'

chokidar.watch('.').on('all', (event, path) => {
  console.log(event, path)
})
```

### What is the expected behavior?

Should stay alive.

### What do you see instead?

Exits.

#### Workaround

```
  setInterval(() => {
  }, 1000)
```

**Comment by paperclover** [comment]
This is because we implemented `napi_ref_threadsafe_function` as a no-op. Fixing this might help tauri's cli (#3237) work.
