### ISSUE TITLE
`bun dev --port=3000` does not respect port number

### ISSUE THREAD

**Issue by xnuk** [oven-sh/bun#3980]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Linux 6.4.7-zen1-3-zen x86_64 unknown

### What steps can reproduce the bug?

1. `bun dev --port=3000` in empty directory
2. Open `http://localhost:3000` in Firefox 117
3. Ctrl-C the server
4. Rerun `bun dev --port=3000`
5. Bun shows "Link: http://localhost:3001"

### What is the expected behavior?

Connect or show error like 'bind(port 3000): Address already in use'

### What do you see instead?

```
$ bun dev --port=3000
[0.02ms] ".env"
[2.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3000


404 GET / as application/octet-stream
^C⏎
$ bun dev --port=3000
[0.02ms] ".env"
[2.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3002


^C⏎
$ bun dev --port=3000
[0.03ms] ".env"
[2.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3000


404 GET / as application/octet-stream
^C⏎
$ bun dev --port=3000
[0.02ms] ".env"
[3.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3001


^C⏎
$ bun dev --port=3000
[0.01ms] ".env"
[1.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3001


^C⏎
$ bun dev --port=3000
[0.01ms] ".env"
[1.00ms] bun!! v0.7.2 (9574db35)


  Link: http://localhost:3001


^C⏎
```

**Comment by birkskyum** [comment]
@xnuk , I just tried this and only had the port change away from the provided in cases where it was already taken. Do you still experience this issue?

**Comment by xnuk** [comment]
```sh
$ ./bun --version
0.8.1
$ ./bun dev --port=3000
[2.00ms] bun!! v0.8.1 (16b4bf34)


  Link: http://localhost:3000


404 GET / as application/octet-stream
404 GET / as application/octet-stream
^C⏎
$ ./bun dev --port=3000
[1.00ms] bun!! v0.8.1 (16b4bf34)


  Link: http://localhost:3001
```

I think still yes?

**Comment by birkskyum** [comment]
Okay, it might be platform related then

**Comment by Hanaasagi** [comment]
This looks like a socket 2MSL issue, which can be resolved by setting `SO_REUSEADDR` flag. But there will be a breaking change in 1.0. `bun dev` will execute the `dev` script in package.json.

https://github.com/oven-sh/bun/blob/57a06745a48093c25d0f4729ccea41a918d6427d/src/bun_dev_http_server.zig#L2819-L2839

**Comment by Electroid** [comment]
This issue was caused by running `bun dev`, which was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
