### ISSUE TITLE
`bun build --compile` to include native module dependencies

### ISSUE THREAD

**Issue by pcfreak30** [oven-sh/bun#3984]
### What is the problem this feature would solve?

Being able to create single binaries that use native .node modules without having the file on the filesystem or need to be extracted to a temp folder.

### What is the feature you are proposing to solve the problem?

Allow some means of loading a native module from a bundle as well as supporting bundling native modules referenced. Since some loaders are very dynamic, the bundling might be trickier, but supporting loading without having to extract would streamline many things.

Currently this can be done with vercel pkg, but its very awkward.

### What alternatives have you considered?

N/A

**Comment by Jarred-Sumner** [comment]
It does this as of Bun v1.1.8 or so
