### ISSUE TITLE
Error installing related workspaces

### ISSUE THREAD

**Issue by scinos** [oven-sh/bun#3985]
### What version of Bun is running?

bun install v0.7.2 (9574db35)

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Create the follwing files:

* `package.json`:
  ```
  {
    "name": "bun-workspaces",
    "workspaces": [
      "packages/a",
      "packages/b"
    ],
    "dependencies": {
      "a": "workspace:*"
    }
  }
  ```
* `packages/a/package.json`:
  ```
  {
    "name": "a",
    "version": "1.0.0"
  }
  ```
* `packages/b/package.json`:
  ```
  {
    "name": "b",
    "version": "1.0.0",
    "devDependencies": {
      "a": "workspace:*"
    }
  }
  ```

Then run `bun install` at the root

### What is the expected behavior?

Installation fails without problems. `node_modules/a` points to `packages/a`.

### What do you see instead?

Error:
```
error: workspace dependency "a" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

![image](https://github.com/oven-sh/bun/assets/975703/97b2909c-b1a6-4e17-b7e2-94118f90b29b)

### Additional information

Also fails with current canary (`v0.7.3 (ff315a3b)`).

Deleting the dependency (or devDependency, doesn't matter) in either `package.json` or `packages/b/package.json` seems to work. And I get the symlink `node_modules/a -> ../packages/a`, as expected.

This was working with `bun 0.7.0`, started to fail in `bun 0.7.1`.

**Comment by Jarred-Sumner** [comment]
This is different than https://github.com/oven-sh/bun/pull/3974, right?

**Comment by scinos** [comment]
I think so. #3974 failed when `bun.lockb` was present, this fails even without `bun.lockb` (in fact I found this when testing the resolution for #3974)

**Comment by scinos** [comment]
Extra info: deleting the dependency (or devDependency, doesn't matter) in either `package.json` or `packages/b/package.json` seems to work. And I get the symlink `node_modules/a -> ../packages/a`, as expected.

**Comment by colinhacks** [comment]
FWIW it's not typical to add `dependencies` to the root of a monorepo. As you noticed, `node_modules/a` will point to `packages/a` even without this dependency - the workspaces get hoisted into the top-level node_modules by default. The messaging here can still be better.

**Comment by scinos** [comment]
> FWIW it's not typical to add dependencies to the root of a monorepo

Maybe not `dependencies`, but I certainly can imagine a few valid cases for adding `devDependencies`. The bug still happens. And while it may or may not be typical, is certainly valid and it should be supported IMO.
