### ISSUE TITLE
Errors seen when environment exports functions

### ISSUE THREAD

**Issue by ashsearle** [oven-sh/bun#40]
Errors seen when invoking bun from a bash environment with exported functions (e.g. as used by nvs / nvm):

To reproduce, simple package.json:
```json
{
  "scripts": {
    "invoke-ls": "ls"
  }
}
```

Then in a bash instance:
```bash
# Define a function (details aren't important)
fn() { :; }
# The important bit: export the function
export -f fn

bun run invoke-ls
```

Error output seen:
```
$ ls
/usr/local/bin/bash: fn: line 1: syntax error: unexpected end of file
/usr/local/bin/bash: error importing function definition for `fn'
...followed by actual output of ls...
```

**Comment by Jarred-Sumner** [comment]
Thank you - I'm able to reproduce this.

I suspect it's an escaping issue with the .env loader. I will add a unit test for this.
