### ISSUE TITLE
`path.format({base: ''})` inconsistency with Node

### ISSUE THREAD

**Issue by vjpr** [oven-sh/bun#4005]
### What version of Bun is running?

0.7.3

### What steps can reproduce the bug?

```
import path from 'path'

const test = 'foo.ts'

const out = changeExtension(test, '.rs')

console.log(out)

function changeExtension(p, ext) {
  const parsedPath = path.parse(p)
  const out = path.format({...parsedPath, base: '', ext})
  return out
}
```

### What is the expected behavior?

```
$ node .
foo.rs
```

### What do you see instead?

```
$ bun .

```

### Additional information

`base: null` works however.

**Comment by Hanaasagi** [comment]
It looks like here we should check if `base` is an empty string.

https://github.com/oven-sh/bun/blob/00a907c7de842787e87b0d0a42d8d33704c5aaae/src/bun.js/node/types.zig#L1869
