### ISSUE TITLE
Bun hangs on large results from mysql2 + ssl

### ISSUE THREAD

**Issue by StanfordCDT** [oven-sh/bun#4006]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Darwin 22.4.0 x86_64 i386

### What steps can reproduce the bug?

1. Start a MySQL server with `docker run -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql`
2. Create test.js as follows:
   ```js
   const mysql = require('mysql2');

   const connection = mysql.createConnection({
     host: "127.0.0.1",
     user: "root",
     password: "root",
     ssl: {
       rejectUnauthorized: false
     },
     multipleStatements: true
   });

   connection.query(`
     CREATE DATABASE IF NOT EXISTS test;
     USE test;
     DROP TABLE IF EXISTS foo;
     CREATE TABLE foo (bar INT);
     INSERT INTO foo (bar) VALUES ${'(10000),'.repeat(1700)} (10000);
     SELECT bar FROM foo
   `, () => {
     console.log("ok");
     connection.close();
   });
   ```
3. `bun install mysql2`
4. `bun test.js`

### What is the expected behavior?

"ok" in the console.

### What do you see instead?

Nothing in the console.

### Additional information

Node works correctly with this script.

Bun works if the `ssl` option is removed.

Bun works if there are only 1,600 or fewer rows in the database.

**Comment by birkskyum** [comment]
Hanging with SSL/TLS enabled - also the case here:
- https://github.com/oven-sh/bun/issues/4368

**Comment by Electroid** [comment]
Tested as of Bun v1.0.7, this has been fixed. If you still experience this issue after upgrading, please re-open this issue and we'll investigate.
