### ISSUE TITLE
Reference errors in `beforeAll` are not printed

### ISSUE THREAD

**Issue by jbgomez** [oven-sh/bun#4009]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```js
beforeAll(() => {
  const foo = bar;
});

test('test', () => {
  expect(true).toEqual(true);
});
```

### What is the expected behavior?

Error should be printed: `ReferenceError: Can't find variable: bar`

**Example** of expected behavior (using ***`afterAll`*** to demonstrate):
![Screenshot 2023-08-05 at 1 25 24 PM](https://github.com/oven-sh/bun/assets/24479183/ad42233b-cbfe-482b-b080-c0e753b6fddd)

### What do you see instead?

Error is not printed:
![Screenshot 2023-08-05 at 1 26 22 PM](https://github.com/oven-sh/bun/assets/24479183/1b8782b9-3438-4a9b-bbe3-97674dc1a63c)

**Comment by v3nntrnx** [comment]
Can replicate on wsl
![image](https://github.com/oven-sh/bun/assets/94789999/c519da39-a481-4336-8e80-7126c0ae39ed)

seems like it cannot print ANY error
![image](https://github.com/oven-sh/bun/assets/94789999/8be3057e-779b-4080-8cb4-75335dc5e188)

**Comment by v3nntrnx** [comment]
that's weird... 
![image](https://github.com/oven-sh/bun/assets/94789999/3b8037db-0335-4017-8310-081ff9e3ea1c)

**Comment by v3nntrnx** [comment]
it might happen cuz beforeAll doesn't get called when there are no tests.
for example, jest throws when there are no tests:
![image](https://github.com/oven-sh/bun/assets/94789999/930f476a-2693-4861-93ed-ce03bcc03eb3)

also, the beforeAll error is not being shown in bun
![image](https://github.com/oven-sh/bun/assets/94789999/57abb3b0-7824-4607-ab01-22d2e3325ca4)

**Comment by Electroid** [comment]
Duplicate of #4422
