### ISSUE TITLE
Support `vm` module

### ISSUE THREAD

**Issue by MixaMega** [oven-sh/bun#401]
![image](https://user-images.githubusercontent.com/93724648/177894864-28d5f785-e877-4d7d-bd08-c453dbc14152.png)

**Comment by caramboleyo** [comment]
I dont think this can be done with “just” a polyfill. You need to create a new, empty globalThis and then reference variables from the parent context to the new one.

**Comment by caramboleyo-no2fa** [comment]
Will there be an update on the error handling some time?
Its quite a pain because it often does not throw any error and if it does, it throws at the line of runInNewContext of the host file.
Also tried to wrap the whole script in a global catch block, but no change. Is there any way to achieve this now?

I do just something like that:
```js
const controller = new Script('long bundled code');
controller.runInNewContext({
    //some vars
});
```

**Comment by ImLunaHey** [comment]
@caramboleyo-no2fa please open a new issue.

**Comment by caramboleyo-no2fa** [comment]
https://github.com/oven-sh/bun/issues/11845

**Comment by sekoyo** [comment]
> Will there be an update on the error handling some time? Its quite a pain because it often does not throw any error and if it does, it throws at the line of runInNewContext of the host file. Also tried to wrap the whole script in a global catch block, but no change. Is there any way to achieve this now?
> 
> I do just something like that:
> 
> ```js
> const controller = new Script('long bundled code');
> controller.runInNewContext({
>     //some vars
> });
> ```
> 
> EDIT: I am having this problem with ShadowRealm now too.

What's Script? Is this some alternative to `vm` I can use for Bun? Don't see it in the docs

**Comment by sekoyo** [comment]
It would be great if Bun `Script` could handle ES modules (and Typescript), in the spirit of Bun being able to handle them for real
