### ISSUE TITLE
.env file won't load correctly sometimes

### ISSUE THREAD

**Issue by iddar** [oven-sh/bun#402]
I use  'entr' to reload mi server on each file change but sometimes the .env vars are empty. To replicate only can re-run your app very fast

```ts
Bun.serve({
  port: process.env.PORT,
  fetch(request: Request) {
    const url = new URL(request.url)
    console.log(url.searchParams)
    return new Response("Hello World");
  },
})

```

![image](https://user-images.githubusercontent.com/199103/177894404-44555a72-0da3-432c-ada8-50d989001eec.png)

OS: Arch Linux  5.18.9
Arch: x86_64
bun: 0.1.2

**Comment by Jarred-Sumner** [comment]
This is definitely a bug

The other interesting part is it prints `.env` three times there

It should only print once

**Comment by iddar** [comment]
print the `.env` three times because the process restart on each change and ran ` bun ./index.ts`. 
that's not a problem only the `.env` hydrating

In this example run a command manually, the `".env"` print ok 

![image](https://user-images.githubusercontent.com/199103/178033486-ddc47d8f-d595-4150-9004-c1c9e243b47e.png)

**Comment by Electroid** [comment]
This appears to not be an issue anymore, but there is still a related bug being tracked at #1451.

**Comment by robobun** [comment]
@Electroid, your commit bbb4e5ba8cf04082ef38401af933ccca2b8800a8 is building: [`#402`](https://api.buildkite.com/v2/organizations/bun/pipelines/bun/builds/402)
