### ISSUE TITLE
v0.7.3 regression: TypeError: (0, shim_node_js_1.fetch) is not a function

### ISSUE THREAD

**Issue by TommasoAmici** [oven-sh/bun#4022]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

This is the same issue as https://github.com/oven-sh/bun/issues/3544, but it's now happening again

```ts
import { Bot } from "grammy@latest";
// the script can be run as is, the token is not required to
// reproduce the error, any placeholder will be ok
const telegramAPIToken = "XXX";

const bot = new Bot(telegramAPIToken);

bot.start();
```

### What is the expected behavior?

No errors

### What do you see instead?

```
TypeError: (0, shim_node_js_1.fetch) is not a function. (In '(0, shim_node_js_1.fetch)(url instanceof URL ? url.href : url, options)', '(0, shim_node_js_1.fetch)' is undefined)
```

**Comment by Electroid** [comment]
Sorry about the twice regression, we'll fix it and add tests to make sure it's not a third time.

**Comment by Jarred-Sumner** [comment]
@paperdave most likely came from converting builtins to CJS
