### ISSUE TITLE
`fs.readdirSync` macOS vs Linux runtime differences

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#4023]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm || Linux 5.10.0-23-arm64 aarch64 unknown

### What steps can reproduce the bug?

create a `src` directory and insert two files `todo.seed.ts` and `user.seed.ts`.

then run this code with bun. 

```ts
import { readdirSync, statSync } from 'fs';
import { join } from 'path';

export const searchFiles = (dir: string, pattern: RegExp): string[] => {
	const files = readdirSync(dir);
	return files.reduce((acc: string[], file: string) => {
		const filePath = join(dir, file);
		if (statSync(filePath).isDirectory()) {
			const subDirFiles = searchFiles(filePath, pattern);
			return acc.concat(subDirFiles);
		} else if (pattern.test(filePath)) {
			return acc.concat(filePath);
		}
		return acc;
	}, []);
};

const files = searchFiles('./src', /\.seed\.ts$/);
console.log(files);
```

### What is the expected behavior?

The code should run on macOS and Linux equally

### What do you see instead?

The code produces on Linux

```ts
[ "src/seed/todo.seed.ts", "src/seed/user.seed.ts" ]
```

On macOS it produces

```ts
[ "src/seed/user.seed.ts", "src/seed/todo.seed.ts" ]
```

### Additional information

I don't really care how it is being sorted by default, I mean alphabetically would be nice, but I would want it to be consistent across different operating systems.

**Comment by simylein** [comment]
I managed to track it down and updated the bug report with a minimal reproduction.

**Comment by birkskyum** [comment]
ran `bun` and `tsx` both on macOS, and tsx is consistent with linux

```sh
➜ tsx index.ts
[ 'src/todo.seed.ts', 'src/user.seed.ts' ]

➜ bun index.ts      
[ "src/user.seed.ts", "src/todo.seed.ts" ]
```

**Comment by simylein** [comment]
Interesting, so I assume it is already platform specific 😞

**Comment by birkskyum** [comment]
could still be that it's just bun on macos that is an outlier. Would need more cross-platform examples to tell

**Comment by sirenkovladd** [comment]
Linux 6.2.0-26-generic x86_64 x86_64
```sh
❯ node index.js
[ 'src/seed/todo.seed.ts', 'src/seed/user.seed.ts' ]
❯ bun index.js 
[ "src/seed/todo.seed.ts", "src/seed/user.seed.ts" ]
❯ deno run --allow-read index.js
[ "src/seed/todo.seed.ts", "src/seed/user.seed.ts" ]
```

Darwin 22.5.0 arm64 arm
```sh
❯ node index.js 
[ 'src/seed/todo.seed.ts', 'src/seed/user.seed.ts' ]
❯ bun index.js 
[ "src/seed/user.seed.ts", "src/seed/todo.seed.ts" ]
❯ deno run --allow-read index.js
[ "src/seed/user.seed.ts", "src/seed/todo.seed.ts" ]
```

**Comment by Jarred-Sumner** [comment]
The order is not defined and I don’t think it needs to be. If people want to sort it they can call .sort() on the array but I’m not convinced it’s worth the performance cost of sorting by default.
