### ISSUE TITLE
`tsc` performance

### ISSUE THREAD

**Issue by ghoullier** [oven-sh/bun#4036]
### What version of Bun is running?

0.7.3

### What platform is your computer?

```console
Darwin 22.5.0 arm64 arm
```

### What steps can reproduce the bug?

```console
git clone https://github.com/ghoullier/fp-nutshell
bun install
hyperfine --warmup 5 --runs 25 'bun ./node_modules/.bin/tsc' 'bun --bun ./node_modules/.bin/tsc'
````
### What is the expected behavior?

There should not have significant difference between `bun` and `bun --bun`.

### What do you see instead?

```console
Benchmark 1: bun ./node_modules/.bin/tsc
  Time (mean ± σ):     453.3 ms ±  17.4 ms    [User: 721.4 ms, System: 40.7 ms]
  Range (min … max):   424.3 ms … 500.0 ms    25 runs

Benchmark 2: bun --bun ./node_modules/.bin/tsc
  Time (mean ± σ):     528.9 ms ±  15.8 ms    [User: 809.6 ms, System: 60.5 ms]
  Range (min … max):   503.4 ms … 554.8 ms    25 runs

Summary
  bun ./node_modules/.bin/tsc ran
    1.17 ± 0.06 times faster than bun --bun ./node_modules/.bin/tsc
```

**Comment by Electroid** [comment]
Thanks for reporting. The issue here is not specific to `bun --bun`, but the performance of `tsc` running on JSC instead of V8.

**Comment by Jarred-Sumner** [comment]
Most of the delta is transpiler overhead

One of the rare cases where a disk cache is a good idea

**Comment by Electroid** [comment]
Since Bun v1.0.15, we introduced a transpiler cache to make `tsc` much faster: https://bun.sh/blog/bun-v1.0.15#transpiler-cache-makes-clis-like-tsc-up-to-2x-faster

**Comment by maschwenk** [comment]
@Electroid I'm seeing a lot more muted improvements for `tsc` than are mentioned in the blogpost. Not sure if you are seeing the same? In a lot of cases I'm seeing closer to a 5% or 0% improvement over Node `20.10.0`.

**Comment by Jarred-Sumner** [comment]
@maschwenk the comparison was versus the previous version of Bun, quote from the blog post (with bold for emphasis)

> tsc --help gets a 2x speedup **compared to Bun v1.0.14**:

which is because previously Bun was transpiling every file before loading, including `tsc`

**Comment by maschwenk** [comment]
👍🏼 @Jarred-Sumner makes sense. I had also confused myself because I misread the original comment and thought that was a link to a new release. FWIW this is what I'm seeing on my machine.

```
node -v && bun -v && hyperfine  --warmup 1 'node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help' 'bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help'
```

```
v20.10.0
1.0.21
Benchmark 1: node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
  Time (mean ± σ):     109.7 ms ±   4.6 ms    [User: 86.7 ms, System: 10.5 ms]
  Range (min … max):   103.3 ms … 126.8 ms    25 runs
 
Benchmark 2: bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
  Time (mean ± σ):     107.1 ms ±  13.0 ms    [User: 82.1 ms, System: 16.4 ms]
  Range (min … max):    95.0 ms … 162.6 ms    26 runs
 
Summary
  bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help ran
    1.02 ± 0.13 times faster than node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
```

So for now the expectation is to similar performance to Node for executables like this, correct?

**Comment by maschwenk** [comment]
👍🏼 @Jarred-Sumner makes sense. I had also confused myself because I misread the original comment and thought that was a link to a new release. FWIW this is what I'm seeing on my machine.

```
node -v && bun -v && hyperfine  --warmup 1 'node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help' 'bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help'
```

```
v20.10.0
1.0.21
Benchmark 1: node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
  Time (mean ± σ):     109.7 ms ±   4.6 ms    [User: 86.7 ms, System: 10.5 ms]
  Range (min … max):   103.3 ms … 126.8 ms    25 runs
 
Benchmark 2: bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
  Time (mean ± σ):     107.1 ms ±  13.0 ms    [User: 82.1 ms, System: 16.4 ms]
  Range (min … max):    95.0 ms … 162.6 ms    26 runs
 
Summary
  bun --bun ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help ran
    1.02 ± 0.13 times faster than node ./node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/bin/tsc --help
```

So for now the expectation is to similar performance to just Node, correct?
