### ISSUE TITLE
404 GET / as application/octet-stream

### ISSUE THREAD

**Issue by samuelnihoul** [oven-sh/bun#4038]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Ubuntu 23

### What steps can reproduce the bug?

npx create-next-app@latest;
bun dev

### What is the expected behavior?

No error. Same behavior as running next dev. In fact it worked correctly in 0.7.2.

### What do you see instead?

The error in the title.

**Comment by krushit-dudhat** [comment]
@samuelnihoul  Not sure if this is a bug. but here something that works for me.
First I was getting the error `404 GET / as application/octet-stream `  while creating next project with the below command.
```
bun create next ./bun-next
```

after some digging, I found issue #200 which looks similar. leading to here: https://bun.sh/guides/ecosystem/nextjs

try creating next application with `bunx` equivalent to `npx`. 

```
bunx create-next-app bunx-next
```
