### ISSUE TITLE
process.env empty (caused by bunfig.toml and tsconfig.json)

### ISSUE THREAD

**Issue by IlyaSemenov** [oven-sh/bun#4039]
### What version of Bun is running?

0.7.2

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Create 3 files in an empty directory:

1) `env.ts`:

```ts
console.log(process.env)
```

2) `tsconfig.json`

```json
{"extends": "@tsconfig/node20"}
```

(There is no need to install `@tsconfig/node20`. Just having the file will trigger the bug. Installing it doesn't make any better, though.)

3) `bunfig.toml` - empty.

Then run: `bun env.ts`

### What is the expected behavior?

The script prints all environment variables, such as `USER`, `PATH`, etc.)

### What do you see instead?

```
❯ bun env.ts
{
  TZ: undefined
}
```

### Additional information

The bug only repeats with `bunfig.toml` (even empty) and `tsconfig` having `extends` in place. If either of these is missing, everything works. For example, if I remove `bunfig.toml`:

```sh
~/tmp/bun
❯ rm bunfig.toml

~/tmp/bun
❯ bun env.ts
{
  SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.n3nAeoapGE/Listeners",
  LC_TERMINAL_VERSION: "3.4.18",
  COLORFGBG: "15;0",
  ITERM_PROFILE: "Default",
  XPC_FLAGS: "0x0",
  ...
```

Changing `tsconfig.json` to say `{}` also fixes the problem.

**Comment by Hanaasagi** [comment]
I think it may be related to this, if configured with `"extends": "@tsconfig/node20/tsconfig.json"`. The `abs_path` will be concatenated into `$PWD/@tsconfig/node20/tsconfig.json`  which is an incorrect path, resulting in a FileNotFound error. The correct path should be `$PWD/node_modules/@tsconfig/node20/tsconfig.json`

https://github.com/oven-sh/bun/blob/efe987e8d12e824dde840b56cbb704feabe26ed1/src/resolver/resolver.zig#L3885-L3889


A temporary workaround is `node_modules` prefix. @IlyaSemenov 


```
  "extends": "node_modules/@tsconfig/node20/tsconfig.json"
```


Ref: https://www.npmjs.com/package/@tsconfig/node20

**Comment by eugene1g** [comment]
I can confirm that changing the `extends` value to a local file path (not the package name) fixes the issue. There is nothing special about `@tsconfig/node20` - I extend a different config from an internal package, and have the same problem with `process.env` becoming empty.

**Comment by Jarred-Sumner** [comment]
Does not occur as of Bun v1.0.1
