### ISSUE TITLE
Support Linux 4

### ISSUE THREAD

**Issue by brillout** [oven-sh/bun#4040]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 4.14.254-20323-gc32c2d54e434 x86_64 unknown

### What steps can reproduce the bug?

https://github.com/brillout/bun-vps

### What do you see instead?

The CLI hangs while nothing seems to happen.

**Comment by simylein** [comment]
I am not sure if this is possible because bun depends on a lot of kernel features from 5.1 and onwards.

**Comment by Electroid** [comment]
We are unlikely to support old Kernel versions at this time. The best thing to do is upgrade. Sorry!

**Comment by Jarred-Sumner** [comment]
That being said, we do implement polyfills for `copy_file_range` and `pidfd_open`

We will implement more of a polyfill for our io_uring usages which will likely make it so the specific issues you're running into with Linux Kernel 4.x will work. It just won't be exactly recommended.
