### ISSUE TITLE
undici fetch overwritten?

### ISSUE THREAD

**Issue by DianomiJH** [oven-sh/bun#4057]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I'm trying to use Bun as a dev server as using AWS SAM cli isn't suitable, but I'm not quite ready to use it in production. In production, I need access to the 'Set-Cookie' header, so I'm using undici fetch (have also tried node-fetch) to get access to it as node18 doesn't have a inbuilt way of getting the Set-Cookie header. But when I'm using Bun as a dev server, it seems to overwrite the fetch import and throws an error 'TypeError: headers.getSetCookie is not a function.' (for undici, something similar about headers.raw is not a function in node-fetch)

it should be relatively easy to reproduce 

```js
import { fetch } from 'undici';

async function test() {
const response = await fetch('www.url-that-sets-cookie.com');
const setCookieHeader = response.headers.getSetCookie();
// TypeError: response.headers.getSetCookie is not a function.
}

test()
```

or from node-fetch:

```js
import fetch from 'node-fetch';

async function test() {
const response = await fetch('www.url-that-sets-cookie.com');
const setCookieHeader = response.headers.raw()['set-cookie'];
// TypeError: response.headers.raw is not a function.
}

test()
```

### What is the expected behavior?

I should be able to use undici fetch without Bun overwriting it (or at least have the same features when it's overwritten)

### What do you see instead?

TypeError: response.headers.getSetCookie is not a function.

### Additional information

possibly related commit? https://github.com/oven-sh/bun/compare/2c0fd28e72f5...ba6908aed775

**Comment by Jarred-Sumner** [comment]
Bun is intentionally overwriting undici so that it uses the global `fetch`

However, we disabled getSetCookie() on `Headers` because it wasn't clear whether WHATWG would choose `getAll` or `getSetCookie`. We'll go ahead and enable `getSetCookie`.

**Comment by Jarred-Sumner** [comment]
This will be available once the next canary build finishes compiling (~1 hour)

```
bun upgrade --canary
```

**Comment by DianomiJH** [comment]
Amazing, Thanks @Jarred-Sumner

**Comment by battall** [comment]
i think this shouldn't be enabled when undici imported, because undici have other features that is needed besides fetch, like i cant use dispatcher or other options from undici, or the experimental h2 support, bun just overrides it. and not just fetch but other methods like undici.request, undici.stream overwritten
