### ISSUE TITLE
Implement node:tty.WriteStream

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4061]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Blocks Angular CLI and Analog

`bun --bun x @angular/cli --help`

### What is the expected behavior?

CLI doesn't break

### What do you see instead?

```sh
55 |     if (process.stdout instanceof tty_1.WriteStream) {
           ^
TypeError: instanceof called on an object with an invalid prototype property.
      at supportColor (/Users/admin/repos/analog-project/node_modules/@angular/cli/src/utilities/color.js:55:8)
```

### Additional information

Presumably breaking because tty_1.WriteStream [isn't implemented](https://bun.sh/docs/runtime/nodejs-apis#node-tty)

**Comment by sp90** [comment]
Implementation tracking: #2081
