### ISSUE TITLE
error: Unexpected while loading modules

### ISSUE THREAD

**Issue by janwilmake** [oven-sh/bun#4069]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

I'm using `require` to include functions to execute as part of my core functionality of my app. 
It always goes right in node, but in bun, sometimes it fails with this error:

```
error: Unexpected reading "/path/to/my/file.ts"
```

I think the path in my require isn't equal to the path in my error (but may be related).

### Additional information

I get the same behaviour with `await import(...)`

I just `console.log(e)`. This doesn't show enough information for me to understand what's going on.

PS: I also noticed dynamic require/import is significantly slower than in node.js, is that possible? A previous measurement in node.js took 42ms to import 150 files, in bun it took 800 ms

**Comment by Jarred-Sumner** [comment]
Can you paste input and output file paths where this happens?

**Comment by paperclover** [comment]
not sure where it is but the text `Unexpected` here is the name of a zig error value, from `error.Unexpected`. that doesn't tell us the full story though.

**Comment by janwilmake** [comment]
This is all information I'm receiving. I'm using `try { ...require statement... } catch (e){ console.log(e) }` and this is all bun shows. How can I show more?

e.g. my code:


```
import { log } from "log";
export const tryRequire = async (absoluteTsPath?: string) => {
  // console.log("tryRequire:", { absoluteTsPath });
  if (!absoluteTsPath) {
    return;
  }

  try {
    // console.log(`require:${absoluteTsPath}`);
    return await import(absoluteTsPath);
  } catch (e) {
    log(
      `COULD NOT REQUIRE. Recommended to build everything and fix build errors. Path: ${absoluteTsPath}`,
      { type: "warning" }
    );
    console.log(e);
    return undefined;
  }
};
```

Like I said, I first used `require` instead of `await import` but it showed the same behaviour.

**Comment by Jarred-Sumner** [comment]
This is an error related to reading files and not specific to import or require . It should reproduce for reading files more generally. Still very much a question why this happens. It’s likely an unusual & untested configuration — are you using a network filesystem? Is it fat32 or ntfs possibly? Something strange is going on and we need more info to help fix it

**Comment by janwilmake** [comment]
According to macOS disk utility I have APFS Data Volume • APFS for my disk. Default config for M1 afaik.

By the way, I haven't gotten it anymore in the last 3-4 days. It might have been solved by restarting my computer or maybe by removing node_modules and re-installing. Not sure if this matters, but I was also using `npm install` couple times alongside bun while using `bun run`. 
Edit: one last thing, I've also completely moved to ESM from a Common.JS target and therefore I'm now importing all with `.js` instead of without extension. Maybe that made the difference?

**Comment by Jarred-Sumner** [comment]
If you're still running into please let us know. I think it's likely we fixed it some months ago after moving from zig-based std.fs.* APIs to our own for reading files from disk.
