### ISSUE TITLE
SegmentationFault in NextJS during load-testing

### ISSUE THREAD

**Issue by efosao** [oven-sh/bun#407]
# Description

Bun exits with a SegmentationFault error when load-testing a default NextJS project.

## Steps to replicate error

1. Install new/default next project using `bun create next test_proj` command in terminal.
2. To run app, cd into project dir and execute the `bun dev` command in terminal.
3. If you don't have a load-tester handy, _Siege_ can be installed using `brew install siege` command in terminal.
4. Run load-test against project. eg. with **siege** I run the following - `siege http://localhost:3000 -c 100`

## Result

Application will crash with `SegmentationFault at 4611686014132420608` on MacOS (M1) or `SegmentationFault at 0` on WSL.

**Comment by Jarred-Sumner** [comment]
This is a bug, but I do not recommend `bun dev` for load testing of any kind

`bun dev` is not designed for production (hence "dev"). It's designed to be much faster than NodeJS-based dev servers, but it actually uses a completely different and much slower HTTP server than `Bun.serve`

**Comment by efosao** [comment]
> This is a bug, but I do not recommend `bun dev` for load testing of any kind
> 
> `bun dev` is not designed for production (hence "dev"). It's designed to be much faster than NodeJS-based dev servers, but it actually uses a completely different and much slower HTTP server than `Bun.serve`

Thanks for the info Jarred! Could you let me now how to run _NextJS apps_ in Production Mode with `Bun.serve`? It's not clear to me from the docs how this works currently.

**Comment by mattn** [comment]
My brief digging into this problem is most likely to occur when 404 occur.

```
$ mkdir foo
$ cd foo
$ bun dev
```
This always crash (for me)
```
$ mkdir foo
$ cd foo
$ touch index.html
$ bun dev
```
This does not occur. This is my guess, but the race condition may have occurred when "Connection: close" was returned.

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
