### ISSUE TITLE
Bug in Headers iterator

### ISSUE THREAD

**Issue by cyco130** [oven-sh/bun#4070]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run the following script and observe the assertion fail:

```js
const headers = new Headers({
	"Content-Type": "text/plain; charset=utf-8",
});

headers.append("Set-Cookie", "foo=bar");

const entries = [...headers];

console.log(entries);
console.assert(entries[1][0] === "set-cookie" && entries[1][1] === "foo=bar");
```

### What is the expected behavior?

I expect the assertion to succeed and have the following output (both Node and Deno give the correct one):

```js
[
  [ "content-type", "text/plain; charset=utf-8" ],
  [ "set-cookie", "foo=bar" ]
]
```

### What do you see instead?

```js
[
  [ "content-type", "text/plain; charset=utf-8" ], [ "content-type", "text/plain; charset=utf-8"
  ]
]
Assertion failed
```

### Additional information

Feels like an off-by-one error. Appending further entries seem to work (except for the broken second entry).

**Comment by dylan-conway** [comment]
this was fixed by #4048
