### ISSUE TITLE
docs search incomplete

### ISSUE THREAD

**Issue by a-parser** [oven-sh/bun#4072]
### What is the type of issue?

Something else

### What is the issue?

My first attempt to search for "docker" didn't yield any results, so I had to use Google to find the desired page

<img width="1150" alt="image" src="https://github.com/oven-sh/bun/assets/13880682/304a1b72-f153-4e63-890b-632e589ea55c">

**Comment by Electroid** [comment]
This is fixed, there are now instructions for using Docker.
