### ISSUE TITLE
Implement Worker option argv and execArgv

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#4075]
(Current blocker for #3787)

**Comment by birkskyum** [comment]
duplicate of #4130

**Comment by birkskyum** [comment]
Also, the worker_threads.Worker option "resourceLimits" would be great to have implemented. It often warns next to argv and execArgv

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4130
