### ISSUE TITLE
create-astro - can't change selections

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4085]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

* `bun --bun x create-astro@latest`
* hit enter to select default name
* try to select other options

### What is the expected behavior?

I expect to be able to step through the setup like I can with:

`bun x create-astro@latest`

### What do you see instead?

I cannot select any but the top-most option that is selected by default. Arrow-keys simply doesn't work.

**Comment by paperclover** [comment]
it's raw mode tty stuff. this wont be done in my initial pass for doing vite framework support, but we will get this working before 1.0

**Comment by birkskyum** [comment]
Works with bun 0.8
