### ISSUE TITLE
Bun.serve shows a confusing error when tls file does not exists

### ISSUE THREAD

**Issue by shiny** [oven-sh/bun#4088]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

When SSL cert or key does not exists, Error will occur but the message is confusing:

<img width="367" alt="图片" src="https://github.com/oven-sh/bun/assets/117487/de3e48e6-58c5-4cce-9b1f-41150ab70b2d">

```typescript
Bun.serve({
  fetch(req) {
    return new Response("Hello!!!");
  },

  tls: {
    key: Bun.file("./non-exists.key"),
    cert: Bun.file("./non-exists.pem"),
  }
});
```

**Comment by Jarred-Sumner** [comment]
That is extremely confusing

**Comment by PatrickDahlin** [comment]
This seems to occur even if the files exist, I presume the contents are in an incorrect format.

**Comment by Electroid** [comment]
Ran into this recently, indeed very confusing.

**Comment by Jarred-Sumner** [comment]
```ts
❯ bun tls.ts
1 | Bun.serve({
        ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "./non-exists.key"

      at /private/tmp/serv/tls.ts:1:5
```

Happy to report the error is better nowadays

**Comment by ulvido** [comment]
cant be able to find existing file aslo:

as you can see finds at line 14 but cant find at line 20. how come?
(in vscode devcontiner. bun v1.2.15)

![Image](https://github.com/user-attachments/assets/41f1434e-9c7d-4003-8603-bafe003139f3)
