### ISSUE TITLE
`deepEquals` returns `true` for different URLs.

### ISSUE THREAD

**Issue by tr1ckydev** [oven-sh/bun#4089]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Linux 6.4.6-1-cachyos x86_64 unknown

### What steps can reproduce the bug?

```ts
console.log(Bun.deepEquals(new URL("https://bun.sh/"), new URL("https://deno.com/")));
```

### What is the expected behavior?

console should log `false`

### What do you see instead?

console logs `true`

**Comment by paperclover** [comment]
so...
<img width="673" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/2911918d-fd9b-4dee-908a-ac6c6c00e747">

**Comment by tr1ckydev** [comment]
I see, but it also shouldn't happen right?
