### ISSUE TITLE
Websocket fragmented message compatibility 

### ISSUE THREAD

**Issue by jdgriffith** [oven-sh/bun#4101]
### What is the problem this feature would solve?

From my research, there currently does not exist a known npm package such as `websocket` or the like which handles fragmented messages over `wss` which is compatible with bun. I'm experiencing issues with every possibility I try.

### What is the feature you are proposing to solve the problem?

 It would be good to do one of the following (within reason and if within priority) 1) bake in some fragmented message capabilities into Bun for websockets 2) offer a guide or point to third party packages which can do this and are compatible with bun or 3) continue reaching towards parity with nodejs until the existing third party packages work with bun.  

### What alternatives have you considered?

I have considered the package `websocket`, attempted native WebSockets within Bun, `ws`, and lastly, have tried to use a socket.io client (experienced connection issues with this one for some reason).

**Comment by jdgriffith** [comment]
For reference, this is a very good implementation of frames for fragmented messages and continuation of messages:  https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketFrame.js

**Comment by Jarred-Sumner** [comment]
Probably a bug in our WebSocket client

**Comment by Electroid** [comment]
We need to test our WebSocket client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: https://github.com/oven-sh/bun/issues/6686

**Comment by Electroid** [comment]
Duplicate of #6686

**Comment by yemreak** [comment]
I'm still encountering the `Protocol error - control frame is fragmented` error sometimes while connecting to the Whitebit order book via websocket. Has anyone else experienced this issue? @Electroid

**Comment by jdgriffith** [comment]
I'm using the latest version to connect to Polygon.io to stream market trade data, and it has appeared to be corrected in my testing last week. I will keep an eye on it though.
