### ISSUE TITLE
TypeError: require() async module "file.ts" is unsupported.

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#4102]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Very hard to reproduce the issue in new project.

I will try to make a reproduction, if the issue stays unsolved.

### What is the expected behavior?

I expect the require to work without issues.

I need to `require(file)` as part of code block, and this can be done only with `require`.
The `import(file)` don't have the same behavior as `require(file)`.

for example something like this..

```ts
Route.group(() => require(routes));
```

with `Bun 0.7.0` the code is working.

### What do you see instead?

```js
(function (resolvedSpecifier){"use strict";var loader=@Loader,queue=@createFIFO(),key=resolvedSpecifier;while(key){var entry=loader.registry.@get(key);if((entry?.state??0)<=@ModuleFetch)@fulfillModuleSync(key),entry=loader.registry.@get(key);var sourceCodeObject=@getPromiseInternalField(entry.fetch,@promiseFieldReactionsOrResult),moduleRecordPromise=loader.parseModule(key,sourceCodeObject),mod=entry.module;if(moduleRecordPromise&&@isPromise(moduleRecordPromise)){var reactionsOrResult=@getPromiseInternalField(moduleRecordPromise,@promiseFieldReactionsOrResult),flags=@getPromiseInternalField(moduleRecordPromise,@promiseFieldFlags),state=flags&@promiseStateMask;if(state===@promiseStatePending||reactionsOrResult&&@isPromise(reactionsOrResult))@throwTypeError(`require() async module "${key}" is unsupported. use "await import()" instead.`);else if(state===@promiseStateRejected){if(!reactionsOrResult?.message)@throwTypeError(`${reactionsOrResult+""?reactionsOrResult:"An error occurred"} occurred while parsing module \"${key}\"`);throw reactionsOrResult}entry.module=mod=reactionsOrResult}else if(moduleRecordPromise&&!mod)entry.module=mod=moduleRecordPromise;@setStateToMax(entry,@ModuleLink);var dependenciesMap=mod.dependenciesMap,requestedModules=loader.requestedModules(mod),dependencies=@newArrayWithSize(requestedModules.length);for(var i=0,length=requestedModules.length;i<length;++i){var depName=requestedModules[i],depKey=depName[0]==="/"?depName:loader.resolve(depName,key),depEntry=loader.ensureRegistered(depKey);if(depEntry.state<@ModuleLink)queue.push(depKey);@putByValDirect(dependencies,i,depEntry),dependenciesMap.@set(depName,depEntry)}entry.dependencies=dependencies,entry.instantiate=@Promise.@resolve(entry),entry.satisfy=@Promise.@resolve(entry),entry.isSatisfied=!0,key=queue.shift();while(key&&(loader.registry.@get(key)?.state??@ModuleFetch)>=@ModuleLink)key=queue.shift()}var linkAndEvaluateResult=loader.linkAndEvaluateModule(resolvedSpecifier,@undefined);if(linkAndEvaluateResult&&@isPromise(linkAndEvaluateResult))@throwTypeError(`require() async module \"${resolvedSpecifier}\" is unsupported. use "await import()" instead.`);return loader.registry.@get(resolvedSpecifier)})

TypeError: require() async module "/path/to/file.ts" is unsupported. use "await import()" instead.
      at loadCJS2ESM (:1:20)
      at requireESM (:1:20)
      at require (:1:20)
```

### Additional information

This issue with the `require` started with Bun 0.7.1 failing first only on tests, now with the latest version is failing everywhere

**Comment by Jarred-Sumner** [comment]
Is the require’d module using top-level await?

**Comment by TiBianMod** [comment]
is inside async callback

```ts
Event.on("booted", async () => {
  // more code
  Route.group(() => require(routes));
});

**Comment by Jarred-Sumner** [comment]
Does the JS/TS file `routes` refers to use top-level await?

**Comment by TiBianMod** [comment]
no, i don't use top level await

**Comment by TiBianMod** [comment]
LOOOOOL


After 4 hours research, the error was not even related with the `require` or the error trace. hehe

The error was coming from the use of Bun Plugin with import.

[Bun release notes](https://bun.sh/blog/bun-v0.7.3#bun-plugin-no-longer-uses-transpiler-magic)

![CleanShot 2023-08-11 at 00 16 24](https://github.com/oven-sh/bun/assets/6713842/94974401-4d39-4df2-93a4-0dad1415a042)
![CleanShot 2023-08-11 at 00 22 10](https://github.com/oven-sh/bun/assets/6713842/e34b6810-09d9-4e62-b27c-70ee5397e58f)

@Jarred-Sumner can you improve please the error trace.

**Comment by paperclover** [comment]
Oh damn, i did some work on commonjs stuff and i think i changed how this error was thrown a little.

But I swear it was only done within `require`. Thanks for the reproduction.

Does this happen if you move your `js-yaml` and `fs` imports to the top level import statements, and just call `plugin`. I dont think `async setup()` is supposed to be async.

either way, it's bad that `import "..."` is causing the ... oh, it's require of that module.

I wonder if we can specifically pinpoint which async module it is.

**Comment by TiBianMod** [comment]
no they are not the imports, hehe, even this produces the same error

```ts
import { plugin } from "bun";

await plugin({
    name: "YAML",
    setup(build) {
        //
    },
});
```

about the `setup`, can be sync and async

```ts
setup(
  /**
   * A builder object that can be used to register plugin hooks
   * @example
   * ```ts
   * builder.onLoad({ filter: /\.yaml$/ }, ({ path }) => ({
   *   loader: "object",
   *   exports: require("js-yaml").load(fs.readFileSync(path, "utf8")),
   * }));
   * ```
   */
  build: PluginBuilder,
): void | Promise<void>;
```

> I wonder if we can specifically pinpoint which async module it is.

will be really nice 👍

**Comment by Jarred-Sumner** [comment]
confusingly, you don't need to `await` the call to `plugin`. It is automatically awaited

**Comment by TiBianMod** [comment]
OMG

without `await`, all works again (no errors), haha
