### ISSUE TITLE
`async.series` doesn't keep process alive

### ISSUE THREAD

**Issue by nwalters512** [oven-sh/bun#4108]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Here's a cloneable repo to make things easier: https://github.com/nwalters512/bun-pg-fs-reproduction. Prerequisites and reproduction steps can be found in the `README.md`.

### What is the expected behavior?

When running the unmodified `index.ts` file, I would expect to see the following output printed:

```
connecting pool...
connected pool
succeeded!
```

### What do you see instead?

Instead, only the following is printed:

```
connecting pool...
```

### Additional information

After uncommenting the `fs.readFile` line, things work as expected and the expected output is printed:

```
connecting pool...
connected pool
succeeded!
```

Note that moving things out of `async.series` and to the root of the file also makes things behave as expected. That is, both `async.series` and `fs.readFile` seem to be necessary for things to break.

**Comment by Jarred-Sumner** [comment]
interesting bug

**Comment by Jarred-Sumner** [comment]
The bug is that `async.series` is not keeping the event loop alive because there is no Promise being awaited at the top-level. 

The following fixes it:
```js
import pg from "pg";
import fs from "fs/promises";
import async from "async";

const { promise, resolve } = Promise.withResolvers();
async.series(
  [
    async () => {
      await fs.readFile("./config.json", "utf-8");

      const pool = new pg.Pool({
        host: "localhost",
        user: "postgres",
        database: "postgres",
      });

      console.log("connecting pool...");
      const client = await pool.connect();
      console.log("connected pool");

      client.release();
      await pool.end();
      resolve();
    },
  ],
  (err: any) => {
    console.log(err ?? "succeeded!");
  }
);

await promise;
```

The underlying cause is that Bun doesn't automatically await dangling promises. It could also be caused by `fs.readFile` unrefing the event loop before its called instead of after the callback has completed.

**Comment by nwalters512** [comment]
Interesting! Thanks for looking into this. Is this a working-as-intended scenario? AFAICT there aren't any dangling promises; `async.series` doesn't return a promise if a callback is provided as the second argument. Or is the dangling promise the `async` function in the first argument to `async.series`? I wouldn't expect that to be dangling either; the `async` lib should be awaiting it.

**Comment by paperclover** [comment]
> Bun doesn't automatically await dangling promises.

This isn't exactly the issue, a dangling promise alone wont keep the event loop alive on node:
```ts
await new Promise(() => {});
```
(this actually will end with exit code 13 "UnfinishedTopLevelAwait")

There are simply things that we are not doing that should keep the event loop. I started looking at what calling `pool.connect` does that keeps the event loop alive and my theory is that the time between `Bun.connect` (underlying implementation of our `node:net`) being called and the socket connecting doesn't keep the event loop alive.

I was using this to test:
```ts
(async () => {
  await Bun.sleep(10);
  console.log("connecting pool...");
  await Bun.connect({
    hostname: "localhost",
    port: 5432,
    socket: { data() {} },
  });
  console.log("connected pool");
})();
```
