### ISSUE TITLE
Bun v0.7.3 crashes with node-mysql2 module, works fine in v0.7.0

### ISSUE THREAD

**Issue by brynne8** [oven-sh/bun#4119]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.14.0-284.11.1.el9_2.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

1. Set up a new Bun project with v0.7.3.
2. Install the `node-mysql2` module.
3. Use the following code:

```js
import { Router } from '@stricjs/router'
const mysql = require('mysql2/promise');

const pool = await mysql.createPool({
  ...
});

const app = new Router({ port: 8000 })
    .get('/', () => new Response('JS-based server'))
    .get('/order/:id', async () => {
        const [rows] = await pool.query(`SELECT * FROM tb_xxx WHERE id = ?`, [ req.params.id ]);
        return Response.json(rows);
    });

Bun.serve(app);
```

### What is the expected behavior?

The application should run without any issues, and the routes should be accessible.

### What do you see instead?

The application crashes when visiting `/order` with the error `Trace/breakpoint trap (core dumped)`.

### Additional information

- The issue does not occur in Bun v0.7.0.
- It seems the bug only appears when using prepared statements in mysql2

**Comment by Jarred-Sumner** [comment]
Stack trace:
```ts
59 |   static fromPacket(packet) {
60 |     const args = {};
61 |     console.log(packet)
62 |     args.protocolVersion = packet.readInt8();
63 |     args.serverVersion = packet.readNullTerminatedString('cesu8');
64 |     args.connectionId = packet.readInt32();
                            ^
RangeError: Out of bounds access
      at fromPacket (node_modules/mysql2/lib/packets/handshake.js:64:24)
      at handshakeInit (node_modules/mysql2/lib/commands/client_handshake.js:112:21)
      at execute (node_modules/mysql2/lib/commands/command.js:45:16)
      at handlePacket (node_modules/mysql2/lib/connection.js:478:19)
      at node_modules/mysql2/lib/connection.js:97:6
      at executeStart (node_modules/mysql2/lib/packet_parser.js:75:10)
      at node_modules/mysql2/lib/connection.js:104:6
      at addChunk (node:stream:1803:46)
```

The message `Out of bounds access` comes from the `DataView` used internally by the `Buffer` object contained in `packet`

**Comment by brynne8** [comment]
Will this be fixed soon? Or do you need further comments?

**Comment by Jarred-Sumner** [comment]
@brynne8 I suspect it's a library bug and that this code worked in an earlier version of Bun is a bug

The below snippet based on your snippet doesn't run successfully in Node:
<img width="642" alt="image" src="https://github.com/oven-sh/bun/assets/709451/4f60170e-95f1-491a-8a79-7a700694eb8a">

```js
const mysql = require("mysql2/promise");

async function main() {
  const pool = await mysql.createPool({
    host: "localhost",
    port: 33060,
    user: "root",
    password: "ZlwyV9dQM0?p",
  });

  const { fields } = await pool.query(`SELECT * FROM tb_xxx WHERE id = ?`, [1]);
  console.log(fields);
}

main();

```

**Comment by melroy89** [comment]
> ```js
> ZlwyV9dQM0?p
> ```

Do did just exposed your local password of user `root` of the database (`ZlwyV9dQM0?p`). Just saying..

**Comment by Jarred-Sumner** [comment]
We run integration tests for mysql2 in CI nowadays, so I'm pretty confident this particular issue is fixed
