### ISSUE TITLE
`bun test` with `bun.file` runs **sometimes** (with repro)

### ISSUE THREAD

**Issue by charnould** [oven-sh/bun#4120]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I use `bun` `test` and it's freaking fast.  
I've written some tests aiming at comparing two `json` files (same number of keys...)

**Problem is:**

Sometimes tests pass or fails (but `bun` `test` tells me something)
<img width="414" alt="Capture d’écran 2023-08-11 à 22 02 16" src="https://github.com/oven-sh/bun/assets/7513363/e40e70ad-c5fc-4b76-b476-ebe22d4d1af1">

Sometimes `bun` `test` tells me nothing...
<img width="358" alt="Capture d’écran 2023-08-11 à 22 02 32" src="https://github.com/oven-sh/bun/assets/7513363/8841e8c9-08ba-484a-8053-7d62be7e1dac">

**Repro:** 
- Fork/download this repo: https://github.com/charnould/bun-bug-test
- Run `bun test --watch`
- Reload multiple times and see that sometimes it works, sometimes it doesn't.

### What is the expected behavior?

Should work?

### What do you see instead?

No test sometimes.

**Comment by Jarred-Sumner** [comment]
> files.forEach(async (f) => {

Most likely this is the responsible line of code. This async function is never awaited. You would need to use `await Promise.all(files.map(async (f) => ...`

**Comment by charnould** [comment]
Paraphrasing Clinton (to myself): it's asynchronous, stupid!
Thanks 👍
