### ISSUE TITLE
Native support for Path aliases / Import aliases

### ISSUE THREAD

**Issue by Majoramari** [oven-sh/bun#4123]
### What is the problem this feature would solve?

Paths could get very long like 
```ts
import X from "../../../../types";
```

You could shouren in in typescript using the opetion in compilerOptions > paths

Example:
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "Node",
    "types": [
      "bun-types"
    ],
    "paths": {
      "@types": [
        "../../../../types"
      ]
    },
  },
}
```

The problem is this has no native support in node nor bun

### What is the feature you are proposing to solve the problem?

I think the majority of the user using bun are using typescript without building, so if it's possible to add native support to bun to use paths in typescript that would be a great improvement for the whole developer experience that I see bun going towards

### What alternatives have you considered?

I guess just use a module like `module-alias` and compile the code like node

**Comment by Jarred-Sumner** [comment]
Bun has native support for tsconfig.json `paths` - https://bun.sh/docs/runtime/typescript#path-mapping

Please leave a comment if you run into any issues with it

**Comment by kuzzmi** [comment]
@Jarred-Sumner This doesn't work for me at all. Even with `bun init` bare repository. I'm on v1.0.0.

```
{
  "compilerOptions": {
    "lib": ["esnext"],
    "module": "esnext",
    "target": "esnext",
    "types": ["bun-types"],
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "baseUrl": "./",   <- added this
    "paths": {         <
      "@/*": "./src/*" <
    }
  }
}
```

Returns

```
Cannot find module "@/submodule" from "/Users/kuzzmi/Projects/bun-test-paths-min/index.ts"
```
