### ISSUE TITLE
custom config file path doesn't work (`bun --config`)

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4128]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```
touch ~/.bunfig2.toml
bun dev --config ~/.bunfig2.toml
```

### What is the expected behavior?

No error.

### What do you see instead?

```
error: FileNotFound opening config ""
```

### Additional information

Using an absolute path also doesn't work.

**Comment by Jarred-Sumner** [comment]
we're probably going to deprecate `bun dev` btw

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/117cee5ca5c36f78ae75a0dee3178620bba73968/src/cli.zig#L318-L320

`config_path` has not been initialized.

**Comment by Jarred-Sumner** [comment]
ah yeah that's supposed to be `config_path_`
