### ISSUE TITLE
Can't find variable: ImageBitmap or Image

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4135]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

make a `index.ts` file with:

```ts
new ImageBitmap();
new Image();
```

`bun index.ts`

### What is the expected behavior?

That the instances can be made.

### What do you see instead?

1 | new ImageBitmap;
       ^
ReferenceError: Can't find variable: ImageBitmap

1 | new Image;
       ^
ReferenceError: Can't find variable: Image

### Additional information

Hit this when running `bun test` in the root of ([MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js/))

**Comment by Electroid** [comment]
`Image` and `ImageBitmap` are browser APIs, they aren't available in runtimes like Bun and Node.js.

**Comment by birkskyum** [comment]
Okay. I noticed the [roadmap](https://github.com/oven-sh/bun/issues/159) says:

> Support [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) API, ImageBitmap for 2D graphics. This may use WebKit's implementation or it might use Skia
