### ISSUE TITLE
Bun-update command

### ISSUE THREAD

**Issue by neowsl** [oven-sh/bun#4147]
### What is the problem this feature would solve?

This feature would make it easier to update all existing packages to their latest versions.

### What is the feature you are proposing to solve the problem?

It would be similar to [npm-update](https://docs.npmjs.com/cli/v8/commands/npm-update):
In addition to the existing sub-commands (such as `bun add`), there would be a `bun update` command that updates every package listed in `package.json` to its latest version.

### What alternatives have you considered?

I have written my own "bun update" command (in Rust, not Zig): https://github.com/mathletedev/bunup
It simply iterates through all the packages listed in `package.json` and runs `bun add` for each one. However, it would be amazing if it could be packaged with Bun by default!

**Comment by hyuzea** [comment]
This already [implemented](https://github.com/oven-sh/bun/pull/4046)
