### ISSUE TITLE
Crash when importing long strings as paths

### ISSUE THREAD

**Issue by armanbilge** [oven-sh/bun#4149]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Linux 6.1.27-060127-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Checkout https://github.com/armanbilge/explore/commit/28ad4a9f820fe9276707b8ad3917d10cc0af75ce
2. `bun run build.mjs`

### What is the expected behavior?

Not a segfault (although I wouldn't be surprised if there is some other legitimate error).

### What do you see instead?

```
$ bun run build.mjs
vite v4.4.8 building for production...
[bun] Warning: worker_threads.Worker option "eval" is not implemented.
Segmentation fault
```

**Comment by paperclover** [comment]
Reproduction:
```
new Worker("a".repeat(10000), {});
// or
await import("a".repeat(10000));
```

we dont implement `eval:true` which made me think we have something breakdown if the path here is really long string.

**Comment by paperclover** [comment]
```
await import("a".repeat(252));
```
smallest string length to reproduce

**Comment by armanbilge** [comment]
Thanks for minimizing!
