### ISSUE TITLE
import 'virtual:windi.css';

### ISSUE THREAD

**Issue by u007** [oven-sh/bun#415]
hi,

im getting error on import 'virtual:*'

**Comment by cyberalien** [comment]
That's a Vite specific thing, you are expected to run those files through Vite and they won't work without it.

**Comment by FinnRG** [comment]
@u007 As this error is caused by using Vite (https://github.com/patak-dev/vite-plugin-virtual), which is not currently supported, please close this issue. You can track the Vite progress at #250.

**Comment by u007** [comment]
ya sorry just realised its a vite thing
