### ISSUE TITLE
customElements.get('my-element') does not seem to work

### ISSUE THREAD

**Issue by 4www** [oven-sh/bun#4167]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.7-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

In a project folder `my-project`:

- create a `/src/my-element.js` file with the content
```js
class MyElement extends HTMLElement {}
if (!customElements.get('my-element')) {
  customElements.define('my-element', MyElement);
}
```

- create a `/index.html` file with the content:
```html
<!DOCTYPE html>
<html>
  <head>
    <script type="module" src="./src/my-element.js"></script>
  </head>
  <body>
    <my-element></my-element>
  </body>
</html>
```

Then in the project's folder root, run `bun dev`.

The `MyElement` web-component called with `<my-element/>` is not defined.

### What is the expected behavior?

The web-component should be defined, because it is not already.

It seems to work "as expected", if the javascript code is written instead, without the if statement checking for an already defined element:
```js
customElements.define('my-element', MyElement);
```

### What do you see instead?

The web-component is not defined if wrapped into a "if statement checking if the web-component is already defined".

```
Uncaught ReferenceError: HMR_bb350214c69aa6db is not defined
    <anonymous> http://localhost:3000/src/my-element.js:1
```

### Additional information

Maybe it comes from my side, I am just learning `bun`, but can't figure what I am doing wrong.

**Comment by Electroid** [comment]
This issue was caused by running `bun dev`, which was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
