### ISSUE TITLE
`bunx <package>@latest` does not always download latest version

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#4183]
### What is the problem this feature would solve?

Currently the latest version of `create-solid` is 0.3.3 but `bunx` is still using a cached version from a few days ago, despite the fact `@latest` is specified in the command. 

```sh
$ bunx create-solid@latest  

  create-solid version 0.2.31
```

### What is the feature you are proposing to solve the problem?

Always re-check registry when a tag is specified

**Comment by colinhacks** [comment]
jk the version is wrong in `create-solid`

**Comment by brentvatne** [comment]
```
npx create-expo@latest --version
Need to install the following packages:
  create-expo@2.1.1
Ok to proceed? (y) y
2.1.1
bunx create-expo@latest --version
2.0.2
```

I'm able to reproduce this issue on my end, `bunx` appears to use a cached version from my first run, rather than fetching latest.

```
bun --version
1.0.0
```
