### ISSUE TITLE
bun dev, for react is not working, and react buildin template is kindof working but not very well

### ISSUE THREAD

**Issue by mi4uu** [oven-sh/bun#4184]
### What is the problem this feature would solve?

First Hi, 
I'm not sure if this is right place to write this, I noticed that bun dev, not working for react, and build in template to create react project works but without any refreshing. flags like --watch or --hot doesn't work. 

o I created my own, maby it will be useful to ppl who want to use it for react like me, but it is far from useful with template we have right now. 

link to my template:
https://github.com/mi4uu/bun-react-template

instructions are in readme, 

### What is the feature you are proposing to solve the problem?

- providing working dev server that refresh page on changes
- have tests configured with examples
- typescript configured
- building ready

if it is not right place, let me know - didn't want to break any rules.

### What alternatives have you considered?

I did search but found only other old repos that doesn't work at all

**Comment by JusttCallMeMike** [comment]
I've added also vscode configuration for watching tsc / tests, and debugging in chrome. everything works as a charm. If not please report issue in the repo. 
it's not HMR, it's refreshing whole page, but if there will be enough interest into this, I can spend some time and try to make real hmr for this.

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
