### ISSUE TITLE
environment variable for detecting execution under the BUN

### ISSUE THREAD

**Issue by OleksandrKucherenko** [oven-sh/bun#4185]
### What is the problem this feature would solve?

source code requires some changes to become compatible with the BUN current state.

if BUN introduce a process.env variable, than part of the code can be adjusted to BUN specificis.

### What is the feature you are proposing to solve the problem?

Problems that it can help to solve:
1. exclude tests from execution (partly)
2. resolve differences in import of the modules (https://github.com/OleksandrKucherenko/chatgpt-translate-md/pull/8)

### What alternatives have you considered?

any kind of global identifier will be a good thing.

**Comment by Jarred-Sumner** [comment]
Here are three ways you can detect whether currently running in Bun:
- `process.isBun`
- `typeof Bun !== "undefined"`
- `"Bun" in globalThis`

**Comment by OleksandrKucherenko** [comment]
```ts
// make typescript happy, isBun is runtime variable specific to BUN runtime
declare let process: {
  isBun: boolean
}
```
