### ISSUE TITLE
`--outfile` doesn't work with directory names

### ISSUE THREAD

**Issue by exoRift** [oven-sh/bun#4195]
### What version of Bun is running?

0.7.4 (canary)

### What platform is your computer?

Linux 4.4.0-22621-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

`bun build index.ts --compile --outfile foo/bar`

### What is the expected behavior?

Compilation of the code to a file called `bar` in the `foo` directory

### What do you see instead?

The directory is created, but then Bun throws a `FileNotFound` error.

**Comment by Hanaasagi** [comment]
**Some debugging information**

From the error log:

```
error: failed to rename /home/kumiko/zig/tmp/test_4195/.f638a7bc19b07c22bun-build to foo/bar.js: FileNotFound
```

And the location where the exception is thrown in the code (Line 447)


https://github.com/oven-sh/bun/blob/360acf5a80d7e0191d13b87226c8122a633f701f/src/standalone_bun.zig#L437-L454


The value of variable `outfile` is `foo/bar.js`. `moveFileZWithHandle` function calls the `renameatZ` function, which results in the destination path being `foo/foo/bar.js`. (`to_dir` is the fd of `foo/` and `destination` is `foo/bar.js`)

https://github.com/oven-sh/bun/blob/360acf5a80d7e0191d13b87226c8122a633f701f/src/c.zig#L115-L126


I think this is the reason for this error.
