### ISSUE TITLE
`syscall: TODO` with `fs-extra`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#4197]
The `copy` function in `fs-extra` is used in `create-docusaurus`

### What version of Bun is running?

v0.7.3

### What platform is your computer?

macos

### What steps can reproduce the bug?

```ts
import {copy} from 'fs-extra';

await copy('a', 'b');
```

Error

```sh
$ bun fsextra.ts
error: SystemError
 syscall: "TODO"
   errno: -126
```

**Comment by paperclover** [comment]
Fixed in #4208
