### ISSUE TITLE
Allow spaces in paths

### ISSUE THREAD

**Issue by haleksandre** [oven-sh/bun#42]
Currently Bun doesn't escape spaces in paths which result in a truncated path & is causing module not found errors.

**Comment by Jarred-Sumner** [comment]
Can you provide a repro?

This doesn't reproduce it:

```js
import { yes } from "./space in imported file";
export function test() {
  if (!yes) {
    throw new Error("no");
  }

  return testDone(import.meta.url);
}
```

```js
// space in imported file.js
export const yes = true;
```

**Comment by haleksandre** [comment]
I meant in the path of the project itself, sorry for not being precise.

To reproduce simply copy one of your example in a directory that contain a space i.e.: `/path/with some spaces/app` & insert a scripts in your package.json

#### project directory
`/srv/projects/open source/examples/next`

#### package.json
```json
{
  "name": "@bun-examples/next",
  "version": "0.0.37",
  "main": "index.js",
  "scripts": {
    "next": "next --help"
  },
  "dependencies": {
    "next": "11.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-is": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.19",
    "bun-framework-next": "^0.0.0-21",
    "typescript": "^4.3.5"
  },
  "bun-create": {
    "postinstall": [
      "bun bun --use next"
    ]
  }
}
````

#### bash
```bash
bun run next

$ next --help
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/srv/projects/open'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

As you can see bun is trying to find the module at `/srv/projects/open` instead of `/srv/projects/open source/examples/next`.

I tried to look around & I suspect the bug lies somewhere in [resolve_path.zig](https://github.com/Jarred-Sumner/bun/blob/e7a4f9f507d172fe1314c6d32b521a8e5a69759b/src/resolver/resolve_path.zig) or wherever you pass the `base_path` / `current_path` arguments for the various functions within that file but to be honest I had never heard of zig before a few days ago so I'm not familiar at all with Zig & might be wrong.

**Comment by Jarred-Sumner** [comment]
Haven’t forgotten about this, will get to it when I can
