### ISSUE TITLE
node:vm globalThis / this !== context

### ISSUE THREAD

**Issue by bytespider** [oven-sh/bun#4205]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Properties from the context are not available on the globalThis or this properties.

```javascript
import vm from 'node:vm';

const context = {};
vm.createContext(context);

context.a = 123
context.console = console;

vm.runInContext('console.log(this.a); console.log(a); console.log(a === this.a)', context);
```

### What is the expected behavior?

In Node v18.7.0
```bash
❯ node test.js
123
123
true
```

### What do you see instead?

In Bun 0.7.3
```bash
❯ bun test.js
undefined
123
false
```

**Comment by Jarred-Sumner** [comment]
Looked at this for a little, some notes:
- we don’t explicitly pass the `this` value to the DirectEvalExeuctable. How does it choose one? Should we use IndirectEvalExecutable instead? Or should we wrap the scripts in a closure? 
- While looking at that I briefly got distracted and tested if using JSC’s direct eval code cache is a performance win and from some simple tests it appeared to do absolutely nothing, but I didn’t properly check if the cache was hit or not.

**Comment by bytespider** [comment]
Looking at the Node code, it seems like they add getters/setters to the global scope that proxy back. Other than that research I have no idea how any of this works 😀

**Comment by shelterit** [comment]
Just wanted to follow-up to this as I've been doing a lot of happy-dom stuff lately, and it uses the VM's context to run eval code in a simulated browser way, but as soon as the object is passed to createContext() the 'this' at the end of execution is altered (rendering errors galore). Ref: https://github.com/capricorn86/happy-dom/issues/1225

Latest Bun 1.0.26, latest happy-dom 13.3.8

```
import VM from 'vm';
class Test {
   test() { // just a test method }
   constructor() {
      this.test();
      this.init();
      // "this" is no longer 'this', and throws a tantrum ....
      this.test();
   }
   init() {
      if (!VM.isContext(this)) {
         VM.createContext(this);
      }
   }
}
test = new Test();
```

**Comment by ohroy** [comment]
any news ?

**Comment by lukasbash** [comment]
Still happening on version 1.1.9 😢

**Comment by manzuni** [comment]
Any news? Still happening in v1.1.20

**Comment by lockieluke** [comment]
this is blocking use of `happydom`

**Comment by ianzone** [comment]
`happy-dom` is not happy anymore, could bun team rise the priority?

**Comment by lukasbash** [comment]
Still not working on the latest canary. How can we get the priority up in here?

**Comment by liflovs** [comment]
+1
