### ISSUE TITLE
`node:fs.read` returns `undefined` buffer

### ISSUE THREAD

**Issue by riywo** [oven-sh/bun#4214]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```mjs
import { open, read } from "node:fs";

open("/etc/hosts", "r", (err, fd) => {
  if (err) throw err;
  const buf = Buffer.alloc(256);
  read(fd, buf, 0, 256, 0, (err, bytesRead, buffer) => {
    if (err) throw err;
    console.log(bytesRead, buffer);
  });
});
```

### What is the expected behavior?

With Node.js:

```
$ node -v
v18.17.1

$ node foo.mjs
174 <Buffer 31 32 37 2e 30 2e 30 2e 31 09 6c 6f 63 61 6c 68 6f 73 74 0a 3a 3a 31 09 6c 6f 63 61 6c 68 6f 73 74 20 69 70 36 2d 6c 6f 63 61 6c 68 6f 73 74 20 69 70 ... 206 more bytes>
```

### What do you see instead?

With Bun:

```
$ bun foo.mjs
174 undefined
```

**Comment by Hanaasagi** [comment]
I think this has been fixed in https://github.com/oven-sh/bun/pull/4191. You can try `bun upgrade --canary` to use the latest nightly binary.

**Comment by riywo** [comment]
Oh, nice! I haven't searched closed ones, sorry.

Yes, `0.7.4` fixed the issue. Thanks!

```
$ bun --version
0.7.4

$ bun foo.mjs  
174 Buffer(256) [ 49, 50, 55, 46, 48, 46, 48, 46, 49, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 10, 58,...
```
