### ISSUE TITLE
After installing bun, every try of running it ends with: (core dumped)

### ISSUE THREAD

**Issue by Setitch** [oven-sh/bun#422]
Installed app (had to manually add paths) but then, every try of running it ends up with
```
:~$ bun
Illegal instruction (core dumped)
```

**Comment by FinnRG** [comment]
Could you paste the output of ```grep avx2 /proc/cpuinfo```? Possible duplicate of #181

**Comment by EndymionSpr** [comment]
There's a pr to add it to readme.md already [here](https://github.com/Jarred-Sumner/bun/pull/346) if that's because of avx2.

**Comment by Setitch** [comment]
@FinnRG yes sure:
```
:~$ grep avx2 /proc/cpuinfo
:~$
```

**Comment by EndymionSpr** [comment]
> @FinnRG yes sure:
> 
> ```
> :~$ grep avx2 /proc/cpuinfo
> :~$
> ```

Yup, head to [#181](https://github.com/Jarred-Sumner/bun/issues/181)

**Comment by FinnRG** [comment]
@Setitch Your CPU doesn't support AVX2 instructions. This is a duplicate of #181. Please close this issue.

**Comment by Setitch** [comment]
Shouldnt that be automatically checked by installer, and ask user if he wants to enable the emulation for that or the bun will not work at all?

**Comment by EndymionSpr** [comment]
> Shouldnt that be automatically checked by installer, and ask user if he wants to enable the emulation for that or the bun will not work at all?

Don't expect that from v0.1 i guess.

**Comment by Setitch** [comment]
Yes, but that would be very good idea to add it to the next relase as we arleady know about the issue^^

**Comment by FinnRG** [comment]
@Setitch Sure, but we don't need another issue for AVX2. There is already a PR to add this to the README and if AVX support doesn't come in the next few versions a check will probably be added to the installation script.
