### ISSUE TITLE
main process exits when capturing the stdout of child process (`node:child_process:spawn`)

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4224]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.11-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Code from https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

```JavaScript
const { spawn } = require("node:child_process");

const p = spawn("ls", ["-l"]);

p.stdout.on("data", data => {
  console.log(`stdout: ${data}`);
});

p.stderr.on("data", data => {
  console.error(`stderr: ${data}`);
});
```

### What is the expected behavior?

Get the same output as `ls` in shell.

### What do you see instead?

No output.

### Additional information

If it's a command that takes a **long time** to finish, then `stdout` can be captured normally.

e.g. 

```JavaScript
const p = spawn("du", ["-sh"]);
```

**Comment by Jarred-Sumner** [comment]
This is probably the cause of some of the flaky tests 

I suspect it’s a Bun.spawn bug rather than child_process specifically but unclear. I also think we should expose a `stdout: { message(data) { }, close() {} }` & stderr callbacks which don’t use promises or buffering

**Comment by birkskyum** [comment]
@Hanaasagi , I find that this is working now (on 0.8.1 and canary). Can you confirm that?

**Comment by Hanaasagi** [comment]
Tested with 0.8.1, confirmed fixed. Thanks!
