### ISSUE TITLE
Possible memory leak when using classic-level (node-gyp?)

### ISSUE THREAD

**Issue by samuelgozi** [oven-sh/bun#4225]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run the following script:

```js
import crypto from 'node:crypto';
import { ClassicLevel } from 'classic-level';

const db = new ClassicLevel(`./test_db`, { compression: true });

let i = 0;
while(i++ < 100_000_000)  {
    const key = crypto.randomBytes(16).toString('hex');
    const data = crypto.randomBytes(1024).toString('hex');
    await db.put(key, data);
}
console.log('done');
```

The bug reproduction doesn't rely on `node:crypto`, its just a fast way to generate random data.
Beware, this snippet generates a lot of data.

### What is the expected behavior?

Node doesn't use over 90mb in RAM. Bun uses over 3gb, and keeps going.

### Additional information

I'm not 100% sure (don't have time to reproduce), but I think I see the same behaviour when using other NAPI/GYP libraries.

**Comment by Jarred-Sumner** [comment]
seems to be `toString("hex")`

**Comment by Jarred-Sumner** [comment]
Fixed by https://github.com/oven-sh/bun/pull/4235
