### ISSUE TITLE
bash: /data/data/com.termux/files/home/.bun/bin/bun: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by PeterHackz** [oven-sh/bun#423]
![Screenshot_20220708-120519](https://user-images.githubusercontent.com/86655602/177958520-3101064f-6bc7-49ca-b567-4a72ec253082.jpg)

**Comment by FinnRG** [comment]
Could you please run ```uname -a```?

**Comment by PeterHackz** [comment]
> 
Linux localhost 4.4.23+ #1 SMP PREEMPT Tue Oct 27 12:37:26 CST 2020 aarch64 Android

**Comment by FinnRG** [comment]
aarch64 is not supported at the moment. Duplicate of #418. Please close this issue.

**Comment by PeterHackz** [comment]
> aarch64 is not supported at the moment. Duplicate of #418. Please close this issue.

oh, alright thx
