### ISSUE TITLE
fs.WriteStream close callback not called

### ISSUE THREAD

**Issue by jmmoser** [oven-sh/bun#4241]
### What version of Bun is running?

0.7.4

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```javascript
// test.js
import fs from 'node:fs';

const stream = fs.createWriteStream(new URL('test.txt', import.meta.url));

stream.close((err) => {
  console.log(err ?? 'closed');
});

console.log('close called');
```

```sh
bun run test.js
```

### What is the expected behavior?

The following is logged (`node test.js`):
```
close called
closed
```

### What do you see instead?

The following is logged:
```
close called
```

**Comment by birkskyum** [comment]
still issue in 0.8.1

**Comment by bnussman** [comment]
Maybe related to #4379?

I think i'm having issues with [`graphql-upload-minimal` ](https://www.npmjs.com/package/graphql-upload-minimal) because of this, but I'm not 100% sure.
