### ISSUE TITLE
process.exit in Worker hit SIGILL in linux aarch64

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#4248]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Linux 6.4.10-orbstack-00066-ga79fe089e66c aarch64 unknown

### What steps can reproduce the bug?

a.ts
```typescript
new Worker(new URL("b.ts", import.meta.url));
```
b.ts
```typescript
process.exit();
```

### What is the expected behavior?

normal execution, without crash

### What do you see instead?

Illegal instruction

### Additional information

it is running at orbstack vm in Apple M2 cpu, maybe it is related?

**Comment by Jarred-Sumner** [comment]
How are you installing Bun? In a VM ("orbstack"), it needs to use the baseline build which will be automatically configured if installed via `curl https://bun.sh/install | bash` in the machine itself.

**Comment by codehz** [comment]
> curl https://bun.sh/install | bash

yes, running in `curl https://bun.sh/install | bash` in this vm

**Comment by codehz** [comment]
md5sum for that bun binary
```
c85b8a47b95f43da7a60ec5e215c18da  /home/codehz/.bun/bin/bun
```

**Comment by codehz** [comment]
> baseline build

but aarch64 doesn't have 'baseline' build

<img width="369" alt="image" src="https://github.com/oven-sh/bun/assets/13158903/d8c61384-d3e0-4e86-b596-17da242bbde4">

I can confirm it use bun-linux-aarch64

**Comment by Jarred-Sumner** [comment]
i see

@kdrag0n does orbstack support aarch64 neon simd?

**Comment by kdrag0n** [comment]
@Jarred-Sumner Yes, NEON normally works fine. Not sure what's going on here.

**Comment by kdrag0n** [comment]
This code doesn't look right:

```
[New Thread 0xffffefc4d600 (LWP 296)]
[New Thread 0xffffc93ba600 (LWP 297)]
[New Thread 0xffffc9129600 (LWP 298)]
[New Thread 0xffffc8919600 (LWP 299)]
[New Thread 0xffffc3fa7600 (LWP 300)]
[New Thread 0xffffc3797600 (LWP 301)]
[New Thread 0xffffc2f87600 (LWP 302)]

Thread 3 "Worker" received signal SIGILL, Illegal instruction.
[Switching to Thread 0xffffc93ba600 (LWP 297)]
(gdb) bt
#0  0x0000aaaaafce0514 in ?? ()
#1  0x0000ffffee19f408 in ?? ()
#2  0x0000ffffee100ea0 in ?? ()
#3  0x0000000200000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) x/32i 0x0000aaaaafce0500
   0xaaaaafce0500:	mov	w1, w20
   0xaaaaafce0504:	bl	0xaaaaafcdffe0
   0xaaaaafce0508:	mov	x0, x19
   0xaaaaafce050c:	mov	w1, w20
   0xaaaaafce0510:	bl	0xaaaaadbf839c
=> 0xaaaaafce0514:	udf	#0
   0xaaaaafce0518:	udf	#0
   0xaaaaafce051c:	udf	#0
   0xaaaaafce0520:	stp	x29, x30, [sp, #-80]!
   0xaaaaafce0524:	str	x25, [sp, #16]
   0xaaaaafce0528:	stp	x24, x23, [sp, #32]
   0xaaaaafce052c:	stp	x22, x21, [sp, #48]
   0xaaaaafce0530:	stp	x20, x19, [sp, #64]
```

**Comment by Jarred-Sumner** [comment]
We have tests for this nowadays

Let us know if you still run into it though
