### ISSUE TITLE
Bun to an organization project

### ISSUE THREAD

**Issue by fzn0x** [oven-sh/bun#425]
Are there considerations to make it an organizational project and have a consensus?

I hope that by making this a project an organization will give developers a sense of security in using it. Like when we use Nodejs and Deno.

**Comment by Jarred-Sumner** [comment]
Yes

**Comment by FinnRG** [comment]
This was discussed on discord yesterday (https://discordapp.com/channels/876711213126520882/888937948345684008/994495287102029915)

**Comment by fzn0x** [comment]
> Yes

Cool, thanks @Jarred-Sumner @FinnRG
