### ISSUE TITLE
Unpredictable behavior using fastify server encapsulation

### ISSUE THREAD

**Issue by sher** [oven-sh/bun#4252]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Unpredictable behavior using `fastify` sever with multiple levels of context encapsulation. I the below example every call to `await server.register()` method creates a copy of the `server` and passes it down to the plugin, thus creating an encapsulated instance per `plugin`. The `prefix` option allows us to assign a URL prefix for the plugin routes.

```typescript
import fastify, { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

await start();

async function start() {
  const server = fastify();

  await server.register(plugin, { prefix: '/en' });
  await server.register(plugin, { prefix: '/ja' });
  await server.register(plugin, { prefix: '/fr' });
  
  console.log(server.printRoutes());
}

async function plugin(server: FastifyInstance) {
  server.get('/', async function handler(request: FastifyRequest, reply: FastifyReply) {
    return reply.send({ ok: true })
  });
}
```

Only if I add a `wait(1000)` somewhere between the plugin registration methods, the output of `console.log(server.printRoutes());` is as expected.

```ts
...
async function start() {
  const server = fastify();

  await server.register(plugin, { prefix: '/en' });
  await server.register(plugin, { prefix: '/ja' });

  // added some wait
  await wait(1000);
  await server.register(plugin, { prefix: '/fr' });
  
  console.log(server.printRoutes());
}
...

// added wait util
async function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```

### What is the expected behavior?

The expected output of the `server.printRoutes()` should be

```sh
bun-fastify $ bun index.ts
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    ├── ja (GET, HEAD)
    │   └── / (GET, HEAD)
    └── fr (GET, HEAD)
        └── / (GET, HEAD)
```

### What do you see instead?

The actual output, and plugin prefix levels, is somewhat unexpected, erroneous. The last plugin with prefix `/fr` was passed not the top level server instance, but the one that was passed to the plugin with the prefix `/ja`. This also means that plugin `/fr` has become a child of plugin `/ja`.

```sh
bun-fastify $ bun index.ts
└── /
    ├── en (GET, HEAD)
    │   └── / (GET, HEAD)
    └── ja (GET, HEAD)
        └── / (GET, HEAD)
            └── fr (GET, HEAD)
                └── / (GET, HEAD)
```

### Additional information

It is clear that, if we add an explicit delay with `wait` the behavior is as expected. Might this be an issue of object cloning via `Object.create(original)` or an `async/await` problem? 

Related `fastify` source code can be found somewhere [here](https://github.com/fastify/fastify/blob/main/lib/pluginOverride.js#L37) where instance cloning is happening.

**Comment by Jarred-Sumner** [comment]
The bug is a difference between `process.nextTick` in Bun and `process.nextTick` in Node. In Node, `process.nextTick` executes before microtasks are drained. In Bun, currently `process.nextTick` enqueues to the same microtask queue.
