### ISSUE TITLE
FFI on Worker got SIGBUS in mac (m1)

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#4258]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

code:
https://github.com/codehz/bun_python/blob/%F0%9F%A5%9F/examples/worker.ts

I've tried to simplify the code but it seems hard to reproduce on a tiny code snippet

### What is the expected behavior?

no crash

### What do you see instead?

'bun run examples/worker.ts' terminated by signal SIGBUS (Misaligned address error)

### Additional information

Note: it works without worker, or linux

**Comment by nektro** [comment]
this now correctly prints `55`.
