### ISSUE TITLE
`@distube/spotify` loading bug.

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#4275]
### What steps can reproduce the bug?

```
import * as dt from "distube";
import "@distube/spotify";

console.log(dt.DisTube); // undefined
```

```
import * as dt from "distube";

console.log(dt.DisTube); // a class
```

**Comment by birkskyum** [comment]
I find that both examples print:

```zig
➜ bun --bun index.ts
[class _DisTube]
```

At least on Darwin. @paperdave , do you still see undefined? I'll let you close it if it works

**Comment by paperclover** [comment]
![image](https://github.com/oven-sh/bun/assets/24465214/e0a13ce5-4b8b-4a18-8abe-76408ac0f74e)
still an issue

**Comment by Jarred-Sumner** [comment]
/private/tmp/serv via 🍞 v1.1.27
❯ bun diss.js
[class _DisTube]

/private/tmp/serv via 🍞 v1.1.27
❯ vim diss2.js

/private/tmp/serv via 🍞 v1.1.27
❯ bun diss2.js
[class _DisTube]

No longer an issue
