### ISSUE TITLE
`Bun.inspect` regression in 0.8.0

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#4287]
### What version of Bun is running?

0.8.0 || 0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

run the following code with bun 0.8.0 and 0.7.3

```ts
import { inspect } from 'bun';

class ValidationError extends Error {}

const isNot = (value: unknown, type: string): ValidationError => {
	return new ValidationError(`${inspect(value)} is not of type ${type}`);
};

console.log(isNot('id', 'number'));
```

### What is the expected behavior?

not sure on 0.7.3 it was

```
error: id is not of type number
```

### What do you see instead?

on 0.8.0 it is 

```
error: "id" is not of type number
```

### Additional information

Is this a regression or rather a breaking change to get close to node compatibility?

**Comment by paperclover** [comment]
yes, this was a breaking change with inspect to make it work more like `util.inspect`.

also beforehand, it could accept multiple args like `inspect(2, 3)` and this would print like `2 3`, kinda like the raw console.log function but printing to a string. now the second argument takes options like `inspect(2, { color: true })`.

**Comment by simylein** [comment]
okey, thank you for the info, will close this as resolved.
