### ISSUE TITLE
Vite's WS client not receive message

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#4288]
### What version of Bun is running?

0.8.0+ad326b77342dd3d8585a30b7da803d32f9c11fe2

### What platform is your computer?

ubuntu 22.04

### What steps can reproduce the bug?

bun --bun vite

### What is the expected behavior?

receive messages
on the first render: `{"type":"connected"}`
after file changes: `{"type":"update", ....}`

### What do you see instead?

no message at all

### Additional information

Terminal already logs hmr update

**Comment by paperclover** [comment]
what version of vite are you using, can you make sure you're on the latest?

**Comment by hyuzea** [comment]
its v3, i forgot to update. 
thankyou @paperdave
