### ISSUE TITLE
 Undici Polyfill Bug

### ISSUE THREAD

**Issue by Wattville** [oven-sh/bun#4309]
### What version of Bun is running?

0.8.0+097ae4e982a9cbcae6b4886c4efb82d452629b99

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

URL and undici.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/85033762/d15ec900-2006-493a-a8c5-065e1bf80dab)
![image](https://github.com/oven-sh/bun/assets/85033762/b89115cd-dace-4ce2-952b-585ff412045f)

**Comment by Electroid** [comment]
Do you have some example code we can run to reproduce this?

**Comment by Jarred-Sumner** [comment]
Duplicate of #4474

**Comment by Jarred-Sumner** [comment]
We are planning to fix this - please follow along in #4474
