### ISSUE TITLE
`net.Socket` does not emit `error` if cannot connect to server

### ISSUE THREAD

**Issue by JonnyBurger** [oven-sh/bun#4316]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

```ts

import net from 'node:net';

const getAvailablePort = (portToTry: number) =>
	new Promise<'available' | 'unavailable'>((resolve) => {
		let status: 'available' | 'unavailable' = 'unavailable';

		const host = '127.0.0.1';
		const socket = new net.Socket();

		socket.on('connect', () => {
			status = 'unavailable';
			socket.destroy();
		});

		socket.setTimeout(3000);
		socket.on('timeout', () => {
			status = 'unavailable';
			socket.destroy();
			resolve(status);
		});

		socket.on('error', () => {
			status = 'available';
		});

		socket.on('close', () => resolve(status));

		socket.connect(portToTry, host);
	});

console.log(await getAvailablePort(3000));
```

```
bun get-port.ts
```

### What is the expected behavior?

Print `"available"`

### What do you see instead?

Hanging process, no output

### Additional information

In Node.js, this works. `error` event is emitted and therefore we know that this port is available to listen to.

Maybe a second bug: The "timeout" also never fires.

**Comment by Jarred-Sumner** [comment]
@paperdave I wonder if this is a regression related to the recent onConnectError change
