### ISSUE TITLE
`bunx create-svelte` results in: TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by rempas** [oven-sh/bun#4318]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 6.4.11-arch2-1 x86_64 unknown

### What steps can reproduce the bug?

I've tried to follow the steps in the [Sveltekit](https://github.com/oven-sh/bun/blob/main/docs/guides/ecosystem/sveltekit.md) template guide.

1. I run: `bunx create-svelte my-app`
2. I choose "Skeleton project" in the first choice

After that, I get the following error:

`TypeError: Right side of assignment cannot be destructured`

### What is the expected behavior?

To not get the error and create the project

### What do you see instead?

The said error

**Comment by birkskyum** [comment]
I don't experience this issue on Darwin

**Comment by rempas** [comment]
> I don't experience this issue on Darwin

Platform specific bug then it is!

**Comment by AaronDewes** [comment]
I don't experience this either on Linux 6.2...

**Comment by mgamperl** [comment]
I have the same problem on windows wsl

**Comment by rempas** [comment]
Fixed after 1.0!
