### ISSUE TITLE
bun.lockb always changes on `bun install` on 0.8.1

### ISSUE THREAD

**Issue by karl-run** [oven-sh/bun#4319]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Linux 6.4.6-76060406-generic x86_64 x86_64

### What steps can reproduce the bug?

Use bun 0.8.1

Run `bun install`

Add bun.lockb as staged git file

Re-run `bun install`

### What is the expected behavior?

Lock file should not change

### What do you see instead?

Lock file changes

**Comment by Jarred-Sumner** [comment]
If you commit it one time, does it continue happening? Bun was previously not updating `"scripts"` which had changed their contents.

**Comment by karl-run** [comment]
Yeah, I noticed it because I kept getting errors in my GHA's because I use `--frozen-lockfile`.

**Comment by karl-run** [comment]
Here's a commit with a non-diff diff on a `bun.lockb`: 

https://github.com/navikt/teamsykmelding-automations/commit/4b400d45962f064318cd41e3c03bdefc0f0c5311#diff-911db038a89e27a7702a07805a21da08e4b2b4f7772913eefceaf824c3c516b9

**Comment by Jarred-Sumner** [comment]
If you `rm bun.lockb`, run `bun install`, commit that, then run it again, does it continue happening? I tried copying over your package.json in that repo (minus the private package) and not yet able to reproduce it after that

<img width="512" alt="image" src="https://github.com/oven-sh/bun/assets/709451/89f05946-bb48-4140-875b-6ddeb49a7332">

**Comment by karl-run** [comment]
That seems to fix it :smile:

**Comment by karl-run** [comment]
I'm not sure what I do, but when I mess around with the package.json, specifically the scripts, it starts happening again.

**Comment by birkskyum** [comment]
It's intentional - the scripts are stored in the lock file. More info in bun 0.8.1 release notes

https://bun.sh/blog/bun-v0.8.1#bun-install-bugfix-with-stale-package-json-scripts

**Comment by karl-run** [comment]
But the bug is that once I change the scripts, every single `bun install` causes the bun.lockb file to change, even when there are no new scripts changes.

**Comment by Jarred-Sumner** [comment]
We will fix this in v0.8.2

**Comment by Jarred-Sumner** [comment]
Confirming that this is currently broken

<img width="538" alt="image" src="https://github.com/oven-sh/bun/assets/709451/6f65c79d-b998-4c8b-b438-691c8a54362c">

**Comment by paperclover** [comment]
found where it is happening. uninitialized memory (random garbage bytes) is finding it's way into the lockfile.

**Comment by bradchristensen** [comment]
I thought I'd piggyback on this as I've noticed a similar issue in 1.0.2 (haven't tested with earlier versions) which probably has a different root cause, but manifests in the same way, where the lockfile changes every time you run a `bun install` (which breaks `bun install --frozen-lockfile`).

I have a monorepo containing many workspaces/packages, and I'm able to reproduce the problem reliably with one package if I have lots of entries in the `exports` field of the `package.json`. I tested it starting with 47 entries, each containing an `import` and a `require` property. This works correctly, and as soon as I add a 48th entry or more, `bun install --frozen-lockfile` stops working.

**Comment by atomicpages** [comment]
Same issue as @bradchristensen. Seeing this problem on 1.1.15. Speicially on Gitlab CI using `imbios/bun-node:latest-iron-alpine` as my build image.

**Comment by injust** [comment]
Encountered this issue on 1.1.29. Seems like I had to `bun install` after every `bun add foo` to get the lockfile to "stabilize".

**Comment by atomicpages** [comment]
For readers: I ended up generating a yarn lockfile and using `yarn` to perform installs to avoid this issue and the slowness on docker build:

```sh
bun i
bun i --yarn
```

Not ideal, but it works 🤷
