### ISSUE TITLE
Support parent-module (npm package)

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4324]
parent-module - [npm](https://www.npmjs.com/package/parent-module) - [github](https://github.com/sindresorhus/parent-module#readme)

### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Example from https://www.npmjs.com/package/parent-module :

```ts
// bar.js
import parentModule from 'parent-module';

export default function bar() {
	console.log(parentModule());
	//=> '/Users/<myyser>/<path>/foo.js'
};

// foo.js
import bar from './bar.js';

bar();
```

`bun foo.js`

### What is the expected behavior?

That it doesn't break and prints the foo.js path:

`/Users/<myyser>/<path>/foo.js`

### What do you see instead?

```sh
➜ bun foo.js 
2 | 
3 | export default function parentModule(filePath) {
4 |     const stacks = callsites();
5 | 
6 |     if (!filePath) {
7 |             return stacks[2].getFileName();
             ^
TypeError: undefined is not an object (evaluating 'stacks[2].getFileName')
      at parentModule (/Users/admin/repos/bun-parent-module-test/node_modules/parent-module/index.js:7:9)
      at bar (/Users/admin/repos/bun-parent-module-test/bar.ts:4:13)
      at /Users/admin/repos/bun-parent-module-test/foo.ts:3:0
```

### Additional information

Blocks:

- #3426 
- https://github.com/oven-sh/bun/issues/3154

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/5802

This will be released in Bun v1.0.3. 

If you don't want to wait until then, an hour after this comment was written you should be able to upgrade to the canary build of Bun:

```bash
bun upgrade --canary
```
