### ISSUE TITLE
bun.dns.lookup('0.0.0.0') throws a segmentation fault

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#4338]
### What version of Bun is running?

v0.8.1

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
require('dns').lookup('0.0.0.0', { family: 4 }, console.log);
// or
Bun.dns.lookup('0.0.0.0', { family: 4 }).then(console.log);
```

### What is the expected behavior?

```sh
❯ node bug.js
null 0.0.0.0 4
```

### What do you see instead?

```sh
❯ bun bug.js      
[1]    990418 segmentation fault (core dumped)  bun bug.js
```

**Comment by birkskyum** [comment]
on darwin it gives:

```sh
➜ bun bar.js
null 0.0.0.0 4
[
  {
    address: "0.0.0.0",
    family: 4,
    ttl: 0
  }, {
    address: "0.0.0.0",
    family: 4,
    ttl: 0
  }
]
```

**Comment by Electroid** [comment]
Appears to work fine on macOS with Bun v1.0.7, are you still running into this issue on Linux?
