### ISSUE TITLE
`exec` doesn't prevent runtime from exiting

### ISSUE THREAD

**Issue by cdmistman** [oven-sh/bun#4343]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { exec } from "child_process";
exec('echo hi', () => {
  console.log('ok')
})
```

### What is the expected behavior?

`ok` should be printed to stdout

### What do you see instead?

empty stdout

### Additional information

this only happens with `exec`, and only when it's not in a Promise that's awaited. For example:

```ts
import { exec } from "child_process";

// this works!
await new Promise(
  (resolve) => exec('echo hi', () => {
    console.log('ok!')
    resolve();
  })
)

// this also doesn't work
new Promise(
  (resolve) => exec('echo hi', () => {
    console.log('ok!')
    resolve();
  })
)
```

**Comment by Electroid** [comment]
As of Bun v1.0.7, this has been fixed. If you are still running into this bug, please re-open this issue and we'll investigate.
