### ISSUE TITLE
randomInt function from crypto and node:crypto returns max bound

### ISSUE THREAD

**Issue by reserved-word** [oven-sh/bun#4355]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

```
import { randomInt } from "node:crypto";

console.log(randomInt(0,1));
```
### What is the expected behavior?

Prints only 0 values

### What do you see instead?

Prints 0 and 1 values

### Additional information

According to jsdoc:

```
   * @param [min=0] Start of random range (inclusive).
   * @param max End of random range (exclusive).
   * @param callback `function(err, n) {}`.
   */
  function randomInt(max: number): number;
  function randomInt(min: number, max: number): number;
```

**Comment by dylan-conway** [comment]
fixed in 45edb7bcf780a492c418ddd551210c2613b5a562
