### ISSUE TITLE
The `bunx` command is missing unless install script run twice.

### ISSUE THREAD

**Issue by maietta** [oven-sh/bun#4356]
### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### How did you attempt to install or upgrade?

I am attempting to leverage Dev Containers to run Bun, which in theory should give me just the right environment to run it.

My Dockerfile for my dev container looks like:

```# [Choice] Debian OS version: bullseye, buster
FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/base:dev-bullseye

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

ENV BUN_INSTALL=/bun
RUN sudo mkdir -p ${BUN_INSTALL} \
    && curl -fsSL https://bun.sh/install | bash \
    && chown -R ${USERNAME} /bun

ENV PATH=${BUN_INSTALL}/bin:${PATH}
```

However

### What do you see instead?

sh: 8: bunx: not found

### Additional information

However, if I run `curl -fsSL https://bun.sh/install | bash` from the terminal inside my dev container environment, the `bunx` command is suddenly available.

I can automate this by adding the `    "postCreateCommand": "curl -fsSL https://bun.sh/install | bash",` directive in my devcontainer.json like so:

```
{
    "name": "Bun (Bullseye)",
    "build": {
        "dockerfile": "Dockerfile"
    },
    "workspaceMount": "src=${localWorkspaceFolder},dst=/workspace,type=bind,consistency=cached",
    "workspaceFolder": "/workspace",
    "forwardPorts": [
        3000,
        5173
    ],
    "features": {
        "common": {
            "username": "automatic",
            "uid": "automatic",
            "gid": "automatic",
            "installZsh": true,
            "upgradePackages": true
        },
        "docker-from-docker": {
            "version": "latest",
            "moby": false,
            "dockerDashComposeVersion": "v2"
        },
        "github-cli": "latest"
    },
    "customizations": {
        "settings": {
            "workbench.colorTheme": "Visual Studio 2019 Dark",
            "terminal.integrated.defaultProfile.linux": "zsh",
            "editor.formatOnPaste": true,
            "editor.guides.bracketPairs": "active",
            "scm.defaultViewMode": "tree",
            "debug.internalConsoleOptions": "neverOpen",
            "eslint.validate": [
                "javascript",
                "typescript"
            ],
            "eslint.workingDirectories": [
                {
                    "directory": "./src",
                    "changeProcessCWD": true
                }
            ],
            "liveServer.settings.NoBrowser": true,
            "liveServer.settings.port": 5173
        },
        "vscode": {
            "extensions": [
                "svelte.svelte-vscode"
            ]
        }
    },
    "postCreateCommand": "curl -fsSL https://bun.sh/install | bash",
    "remoteUser": "vscode"
}
```

While I do have this working, I'm not sure the root cause of the problem.

** I am new to Dev Containers. I acknowledge it is very possible that I don't know what I'm doing. By filing this "bug" report, perhaps someone else may find a use for my solution, as I wanted to get Bun working under Windows via WSL **

**Comment by maietta** [comment]
Okay, so someone pointed out to me that it's no longer `bunx`, but as of yesterday it is `bun x`. This resolved my issue.

**Comment by Electroid** [comment]
While you can use `bun x`, we haven't changed `bunx`, it should still work. If it's not working it's an actual issue.

**Comment by wlai-lp** [comment]
need to update guide to `bun x` instead of `bunx` https://bun.sh/guides/ecosystem/vite

**Comment by okunamayanad** [comment]
According to @Electroid 

> While you can use bun x, we haven't changed bunx, it should still work. If it's not working it's an actual issue.

If bunx is still a thing, `bunx nuxi@latest init <project-name>` isn't working but `bun x nuxi@latest init <project-name>` is working. You should reopen this issue

**Comment by cpakken** [comment]
Ran into this issue in bun 1.1.13. 
`bunx npm-check-updates -i` doesn't work `bun x npm-check-updates -i` works. 

1.1.13+bd6a60512
Microsoft Windows NT 10.0.22631.0 x64

![image](https://github.com/oven-sh/bun/assets/61718569/9f8777b9-ca62-4a8f-b28b-fe99ce2d609c)

**Comment by wangf1** [comment]
I run into same issue. My version is also 1.1.13. 
This issue happens on Windows 11, but on Linux VM it works fine.

> Ran into this issue in bun 1.1.13. `bunx npm-check-updates -i` doesn't work `bun x npm-check-updates -i` works.
> 
> 1.1.13+bd6a60512 Microsoft Windows NT 10.0.22631.0 x64
> 
> ![image](https://private-user-images.githubusercontent.com/61718569/339922786-9f8777b9-ca62-4a8f-b28b-fe99ce2d609c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njg5MTUsIm5iZiI6MTcxODc2ODYxNSwicGF0aCI6Ii82MTcxODU2OS8zMzk5MjI3ODYtOWY4Nzc3YjktY2E2Mi00YThmLWIyOGItZmU5OWNlMmQ2MDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzNDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYzIwOTNkZTQwZTEzODFjYjk2ZTg3OTgxYWQxZjRkMGY3OTRhZDM2ZWM1YTI1YmZmOTlhZDBjYjJhNGE5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0s8Scy3XwS40fp9jdReYboKQWnAkV-V19Rhc-OvkKA)
