### ISSUE TITLE
setTimeout doesn't have promisify.custom

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#4361]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
require('util').promisify(setTimeout)(100, 'ok').then(console.log);
```

### What is the expected behavior?

```sh
❯ node bug.js
ok
```

### What do you see instead?

```sh
❯ bun bug.js 
374 |       writable: !1,
375 |       configurable: !0
376 |     }), fn;
377 |   }
378 | 
379 |   function fn() {
                             ^
TypeError: setTimeout expects a function
      at fn (node:util:379:26)
      at <path>/bug.js:17:0
      at globalThis (<path>/bug.js:17:65)
```

### Additional information

```js
console.log(setTimeout[require('util').promisify.custom]);
```

```sh
❯ bun bug.js
undefined

❯ node bug.js 
[Function: setTimeout]
```

https://github.com/oven-sh/bun/blob/bun-v0.8.1/src/js/node/util.js#L478

**Comment by sirenkovladd** [comment]
It blocks the [close-with-grace](https://www.npmjs.com/package/close-with-grace?activeTab=dependents) (dependency in [fastify-cli](https://www.npmjs.com/package/fastify-cli))

**Comment by evmd** [comment]
Any update on this ?

**Comment by sirenkovladd** [comment]
Fixed in https://github.com/oven-sh/bun/pull/9467
