### ISSUE TITLE
child inherits env from parent when set `env: {}`

### ISSUE THREAD

**Issue by matsumoto0912** [oven-sh/bun#4362]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 6.4.4-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```
const cp = require("child_process");

if (process.argv[2] === "child") {
  console.log("Child $DISPLAY is", process.env.DISPLAY);
} else {
  console.log("Parent $DISPLAY is", process.env.DISPLAY);

  const child = cp.spawnSync(process.execPath, [__filename, "child"], {
    env: {},
  });
  console.log(child.stdout.toString());
}
```

### What is the expected behavior?

Node:

```
Parent $DISPLAY is :0
Child $DISPLAY is undefined
`
```

### What do you see instead?

Bun:

```
Parent $DISPLAY is :0
Child $DISPLAY is :0
```

**Comment by Hanaasagi** [comment]
It seems to be here, parent process's env are copied when `env_array` is an empty array.

https://github.com/oven-sh/bun/blob/9e653e610c4fe8d1536283cada7c21d1580259cd/src/bun.js/api/bun/subprocess.zig#L1260-L1263
