### ISSUE TITLE
implement `expect.toHaveBeenCalledWith()`

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#4365]
### What is the problem this feature would solve?

Instead of writing tests like

```ts
import { describe, expect, spyOn, test } from 'bun:test';

describe('i mock your mocks', () => {
	test('mock mock who is there', () => {
		const log = spyOn(console, 'log');
		log('hello world');
		expect(log.mock.calls[0]).toEqual(['hello world']);
	});
});
```

### What is the feature you are proposing to solve the problem?

We could do this

```ts
import { describe, expect, spyOn, test } from 'bun:test';

describe('i mock your mocks', () => {
	test('mock mock who is there', () => {
		const log = spyOn(console, 'log');
		log('hello world');
		expect(log).toHaveBeenCalledWith('hello world');
	});
});
```

### What alternatives have you considered?

Continuing to use `expect(log.mock.calls[0]).toEqual(['hello world']);`

**Comment by ImBIOS** [comment]
@testing-library/react renderHook  combined with bun:test expect need toHaveBeenCalledWith, as example:

```ts
import { renderHook } from '@testing-library/react'
import { describe, expect, it } from 'bun:test'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'

import { useUrlHelper } from '@/hooks/urlHelper'

jest.mock('next/navigation', () => ({
  // useRouter: jest.fn(),
  usePathname: jest.fn(),
  useSearchParams: jest.fn(),
}))

describe('useUrlHelper', () => {
  beforeEach(() => {
    ;(useRouter as jest.Mock).mockReturnValue({
      push: jest.fn(),
      refresh: jest.fn(),
    })
    ;(usePathname as jest.Mock).mockReturnValue('/test-path')
    ;(useSearchParams as jest.Mock).mockReturnValue(new URLSearchParams())
  })
  
// ... other tests

it('should remove specified query parameters', () => {
    ;(useSearchParams as jest.Mock).mockReturnValue(
      new URLSearchParams('foo=bar&baz=qux'),
    )

    const { result } = renderHook(() => useUrlHelper())

    result.current.appendQuery({ fizz: 'buzz' }, ['baz'])

    // Line bellow will be error, even though it's required and I don't have any alternative for this
    expect(result.current.router.push).toHaveBeenCalledWith(
      '/test-path?foo=bar&fizz=buzz',
    )
  })
```

Does someone can help me to find the solution/alternative? I can't figure out how to replace the jest.mock yet.

**Comment by phenax** [comment]
@ImBIOS You can use `.mock.calls` to get a list of arguments your mock was called with.

```ts
expect(result.current.router.push.mock.calls[0]).toEqual([ '/test-path?foo=bar&fizz=buzz' ])
```

Unfortunately for multiple calls, this'll get messy but should be a fine fix till this gets done.

**Comment by ImBIOS** [comment]
@phenax How to make the `result.current.router.push` has `.mock.calls[0]` ?

**Comment by phenax** [comment]
@ImBIOS, I don't know the internals of `useUrlHelper` but if the `.current.router` is the result of calling `useRouter` then it should be mocked since you're mocking the return value in `beforeEach`. If you're using typescript, then ts might not be aware of this so just do a `(result.current.router.push as jest.Mock).mock.calls[0]`.

**Comment by jakeboone02** [comment]
I believe this can be closed now. `expect().toHaveBeenCalledWith()` (along with related matchers) was [added in v1.0.15](https://bun.sh/blog/bun-v1.0.15#expect-extend-and-more-matchers).
