### ISSUE TITLE
Macros crashes Bun when trying to compile using `build --compile`

### ISSUE THREAD

**Issue by vexcited** [oven-sh/bun#4373]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Make a macro to remove dead code on production build, for example:

`./utils.ts`
```typescript
export const isDevelopment = () => process.env.NODE_ENV === "development";
```

`./index.ts`
```typescript
import { isDevelopment } from "./utils" with { type: 'macro' };

if (isDevelopment()) {
  console.log("something only for development");
}
```

Finally, run `bun build --compile --outfile ./bin ./index.ts`

### What is the expected behavior?

Have a binary in `./bin`

### What do you see instead?

```console
$ bun build --compile --outfile ./bin ./src/index.ts
[0.01ms] ".env"
[1]    13286 IOT instruction  bun build --compile --outfile ./bin ./index.ts
```

### Additional information

I am doing this because for some reason, I have an error with console.logs when running the Bun binary inside a service or in PM2.

Here's the output when doing `pm2 logs` for example...

![image](https://github.com/oven-sh/bun/assets/59152884/3037ac0b-5dae-4b39-83e4-a93c19600a30)

If that shouldn't open, I can open another issue for this if needed.

**Comment by Jarred-Sumner** [comment]
Does not reproduce as of Bun v1.0.7
