### ISSUE TITLE
child_process' execFileSync chooses executable in cwd even though it's not on PATH

### ISSUE THREAD

**Issue by jakebailey** [oven-sh/bun#4375]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

In `test.js`:

```js
const cp = require("child_process");

cp.execFileSync("node", ["--version"], { stdio: "inherit" });
```

Then in a local file next to `test.js` named `node`:

```sh
#!/bin/sh
echo "this is just some random file named node"
exit 1
```

Then `chmod +x node`.

Run `bun ./test.js`.

### What is the expected behavior?

Runs `node` in `PATH` (or, `bun` as `node`).

### What do you see instead?

The local `node` executable is chosen, even though it's not on PATH.

```
this is just some random file named node
714 |   path;
715 |   syscall;
716 |   errno;
717 |   code;
718 | 
719 |   constructor(message, path, syscall, errno, code) {
                             ^
error: Error
   path: "node"
   code: "1"
 syscall: "spawnSync"
   errno: -1

      at new SystemError (node:child_process:719:26)
      at node:child_process:171:46
      at node:child_process:206:52
      at /home/jabaile/work/bun-as-node/test.js:15:0
      at globalThis (/home/jabaile/work/bun-as-node/test.js:15:52)
```

Run with `node` proper:

```
v20.5.1
```

**Comment by nektro** [comment]
This no longer reproduces for me in Bun 1.1.3. Are you able to confirm?

**Comment by jakebailey** [comment]
I can no longer reproduce this in 1.1.3, no. 1.0.36 fails, 1.1.0 passes, so it's fixed somewhere in there!

![image](https://github.com/oven-sh/bun/assets/5341706/df68b46e-c0a4-4a2f-a090-5910b50d94eb)
