### ISSUE TITLE
`delete process.env.XXX` not work

### ISSUE THREAD

**Issue by matsumoto0912** [oven-sh/bun#4383]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Linux

### What steps can reproduce the bug?

```
console.log(process.env.NODE_ENV);
delete process.env.NODE_ENV;
console.log(process.env.NODE_ENV);
```

### What is the expected behavior?

`undefined` after deleted.

### What do you see instead?

not deleted.

### Additional information

https://nodejs.org/api/process.html#processenv

![2023-08-29_11-23](https://github.com/oven-sh/bun/assets/135786106/2a75ba76-cd2d-4ea9-baca-40791c9d2dd7)

**Comment by michaelhays** [comment]
This is fixed in Bun 1.0.15
