### ISSUE TITLE
HTMLRewritter Capability to Insert Element Nodes instead of Plain Text

### ISSUE THREAD

**Issue by cj-1010-1414** [oven-sh/bun#4385]
### What is the problem this feature would solve?

Easy HTML trasforming.

```
 const html = Bun.file('./browser/pages/masuk.html')
 const page = new Response(await html.text(), {
    headers: {
       'Content-Type': 'text/html'
    }
 })

return new HTMLRewriter()
    .on('#password', {
       element(element) {
          element
             .setAttribute('minlength', String(password_min_length))
             .setAttribute('maxlength', String(password_max_length))
             .after('<p>TEST</p>')
       }
    })
    .transform(page)
```

Calling this would render `<p>TEST</p>` as plain text instead of element node.

### What is the feature you are proposing to solve the problem?

Inserting string treated as element nodes, instead of plain text.

### What alternatives have you considered?

So far, just created empty element in which a text to be inserted.

**Comment by Jarred-Sumner** [comment]
Try passing `html: true` as the second argument to `after`
