### ISSUE TITLE
MSW package raise error in unit tests (yarn+ts-node works well)

### ISSUE THREAD

**Issue by OleksandrKucherenko** [oven-sh/bun#4387]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Please follow the instructions provided in open MSW repo issue - https://github.com/mswjs/msw/issues/1718

### What is the expected behavior?

- https://github.com/mswjs/msw/issues/1718

### What do you see instead?

- https://github.com/mswjs/msw/issues/1718

### Additional information

- https://github.com/mswjs/msw/issues/1718

**Comment by birkskyum** [comment]
Duplicate of
- https://github.com/oven-sh/bun/issues/2297
