### ISSUE TITLE
Cannot find name Bun

### ISSUE THREAD

**Issue by lcy101u** [oven-sh/bun#439]
While I tried to run this example code from docs
`Bun.serve({
  fetch(req: Request) {
    return new Response(`bun!`);
  },
  port: 3000,
});`

ends up I get ' Cannot find Bun' warning

screenshot see attachment
![not found](https://user-images.githubusercontent.com/12782646/177997097-e8eca8c9-44a2-445e-b458-4e99258fd3b5.jpg)

**Comment by michellbrito** [comment]
What's the output if you do the following `bun --version` in the terminal?

**Comment by dulranga** [comment]
typescript?
You may need to add "bun-types" type definitions to `tsconfig.json` under "types"

**Comment by erra0002** [comment]
@lcy101u Follow the instructions in https://github.com/Jarred-Sumner/bun#using-bun-with-typescript to add type definitions for typescript. Otherwise you can simply replace "Bun.serve" with "export default".

**Comment by equiman** [comment]
On TS you need to install bun-types as devDependency. 

Command:

```shell
bun add -d bun-types
```

tsconfig.json file:

```json
{
    "compilerOptions": {
        "types": [
            "bun-types"
        ]
    }
}
```

Follow this doc: https://bun.sh/docs/runtime/typescript
