### ISSUE TITLE
Error running compiled bun executable - FileNotFound "://root/..."

### ISSUE THREAD

**Issue by willfiore** [oven-sh/bun#4391]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.4.0-159-generic x86_64 x86_64

### What steps can reproduce the bug?

I am building a bun executable on a development machine, and attempting to run it on another Linux VM.

Development machine: Linux 5.19.0-50-generic x86_64 x86_64
Target machine: Linux 5.4.0-159-generic x86_64 x86_64

On development machine:
- Create bun project with `bun init`
- Compile project with `bun build index.ts --compile --outfile test`

On target machine:
- Run executable

### What is the expected behavior?

Executable runs and prints "Hello via Bun!"

### What do you see instead?

error: FileNotFound reading "://root/test"

### Additional information

Perhaps old kernel version is an issue (5.4), although I can't see anywhere about minimum requirements to run a bun executable.

Otherwise, I'm not sure what is going on or how to debug further.

**Comment by Jarred-Sumner** [comment]
Going to need a little more information to reproduce this. Here's what I tried:
<img width="431" alt="image" src="https://github.com/oven-sh/bun/assets/709451/62172c3f-115f-486a-9fdb-80ee1314c41f">

**Comment by Electroid** [comment]
If you are able to share your code, let us know and we'll re-investigate.
