### ISSUE TITLE
NX bun: Angular - bun will crash now 😭😭😭

### ISSUE THREAD

**Issue by Jordan-Hall** [oven-sh/bun#4393]
### What version of Bun is running?

0.8.2+07d8623976cd5fe1b11dd13f6988cd02e4fc5c15

### What platform is your computer?

Linux 6.1.0-11-amd64 x86_64 unknown

### What steps can reproduce the bug?

Check out this repo https://github.com/Jordan-Hall/nx-bun-playground

- `bun install`
- ` bun --inspect nx run fitness:serve`

### What is the expected behavior?

I would expect the same behaviour as  `bun nx run fitness:serve`

### What do you see instead?

```

uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.8.2 (07d86239) Linux x64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08)
AutoCommand: bunfig 
Elapsed: 110843ms | User: 12519ms | Sys: 2548ms
RSS: 0.71GB | Peak: 1.07GB | Commit: 0.71GB | Faults: 304
----- bun meta -----

0   0x557dfb98e1bb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???
14  ???
15  ???
16  ???
17  ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord


```

**Comment by AaronDewes** [comment]
`bun --inspect nx run fitness:serve` fails with

```
 >  NX   Cannot find project 'fitness'
```

Please update your instructions, I can't reproduce this issue.

**Comment by Electroid** [comment]
Unable to reproduce with the instructions given. If you're still experiencing this issue, let us know and we'll re-investigate.
