### ISSUE TITLE
https has been decoded already

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#4397]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
const { request } = require('https');
request('https://bun.sh/', { headers: { 'accept-encoding': 'gzip' } }, (res) => {
  function cb (chunk) {
    console.log(chunk.toString().slice(0, 100));
    res.off('data', cb);
  }
  res.on('data',cb);
}).end();
```

### What is the expected behavior?

```sh
❯ node test-pipeline.js
ܓ�n�@��}��H�b�8*�����N���Cw����Vn<Oȓ�u��m�Ĺ�g�7����+�͋O�>~|�
```

### What do you see instead?

```sh
❯ bun test-pipeline.js 

  <!DOCTYPE html>
<html lang="en">
<head><meta charSet="UTF-8" /><meta name="viewport" content="wid
```

### Additional information

Blocks `got`

node_modules/got/dist/source/create.js (got)
node_modules/got/dist/source/core/index.js (flush)
node_modules/got/dist/source/core/index.js (_makeRequest)
node_modules/got/dist/source/core/index.js (_onRequest)
node_modules/got/dist/source/core/index.js (_onResponse)
node_modules/got/dist/source/core/index.js (_onResponseBase)
node_modules/decompress-response/index.js (deferToConnect) - use zlib

**Comment by paperclover** [comment]
i think this is linux-specific. i cant reproduce it on macos, and more so the tests in my got pr is failing on linux

**Comment by sirenkovladd** [comment]
I just tried Darwin 22.5.0 arm64 arm (0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366)
and have the same problem
