### ISSUE TITLE
Used Caret Ranges, but installed the wrong version

### ISSUE THREAD

**Issue by xihale** [oven-sh/bun#4398]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Linux 6.1.44-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

First, init a new project, and add it to the `package.json`  
```json
{
  "Dependencies": {
    "hexo": "^6.3.0",
  }
}
```
Then run `bun i`  
Then run `head -n 4 node_modules/hexo/package.json`, as you can see, the version is "7.0.0-rc2"(or higher)

### What is the expected behavior?

reference the https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004, It should manager version likes this, otherwise there will be breaking errors in dev.

### What do you see instead?

When I use this `package.json`
```json
{
  "Dependencies": {
    "hexo": "^6.3.0",
  }
}
```
It installed the breaking changed version "7"
```json
"version": "7.0.0-rc2",
```

**Comment by Hanaasagi** [comment]
I think this is related to comparing two semver versions. Semantically, `7.0.0-rc2` is considered less than `7.0.0`, but npm has its own additional rules https://github.com/npm/node-semver#prerelease-tags. 

> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.



![2023-08-30_19-09](https://github.com/oven-sh/bun/assets/9482395/36c5fea9-9173-4e44-973b-543ad1aa5a84)

**Comment by xihale** [comment]
> I think this is related to comparing two semver versions. Semantically, `7.0.0-rc2` is considered less than `7.0.0`, but npm has its own additional rules https://github.com/npm/node-semver#prerelease-tags.
> 
> > For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.
> 
> ![2023-08-30_19-09](https://user-images.githubusercontent.com/9482395/264309305-36c5fea9-9173-4e44-973b-543ad1aa5a84.png)

That's it, I suddenly understood, thank you very much(I should also try using npm, but I didn't think of this)!

**Comment by Hanaasagi** [comment]
I believe this is a bug that needs to be fixed, and Bun should 100% compatibility with npm here. If you don't mind, please reopen this. Thank you.

**Comment by xihale** [comment]
> I believe this is a bug that needs to be fixed, and Bun should 100% compatibility with npm here. If you don't mind, please reopen this. Thank you.

Oh, it turns out that the result of the first line is false, sorry, I mistook it for true! Now it looks like a very important problem, just solve it!
