### ISSUE TITLE
Segmentation fault when called `fs.mkdtempSync` on `/tmp/XXXXXX` dir

### ISSUE THREAD

**Issue by itpcc** [oven-sh/bun#4404]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.0-78-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a file (Let's say `index.ts`)
```bun
import { mkdtempSync, realpathSync, rmdirSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

const tmpDirPrf = join(realpathSync(tmpdir()), 'doc-');
const tmpDir = mkdtempSync(tmpDirPrf);
```

then: `bun run index.ts`

### What is the expected behavior?

Directory `/tmp/doc-XXXXXX` should be created

### What do you see instead?

```bash
$ bun run index.ts
Segmentation fault (core dumped)
```

**Comment by itpcc** [comment]
Note: This issue might related: https://github.com/oven-sh/bun/issues/2967#issuecomment-1577265306

**Comment by itpcc** [comment]
I've also tried on `5.19.0-50-generic` and got the same result.

**Comment by itpcc** [comment]
Note: Still got the issue even Bun 1.0:
```bash
$ bun -v
1.0.0
$ bun ./test-bun.ts
Segmentation fault (core dumped)
```

**Comment by Jarred-Sumner** [comment]
We’ll fix this today

**Comment by rachasakr** [comment]
Fixed!
```bash
$ bun run bun-test.ts 
/tmp/doc-qi1D7E
$ bun -v
1.0.1

```
