### ISSUE TITLE
HTMLRewriter Issue in Bun >=0.8.0

### ISSUE THREAD

**Issue by gtrabanco** [oven-sh/bun#4408]
### What version of Bun is running?

`0.8.2+f24ca3900400bb41faefb42f426651d5d7e7c2e6`

### What platform is your computer?

`Darwin 21.6.0 x86_64 i386`

### What steps can reproduce the bug?

Execute any valid HTMLRewriter:

```ts
const url = 'https://midu.dev';
const res = await fetch(url);
const titles: string[] = [];

const rw = new HTMLRewriter();
rw.on('h3', {
  element: (element: HTMLRewriterTypes.Element) => {
    // console.log('Inside element');
  },
  text: ({ text }: HTMLRewriterTypes.Text) => {
    const newsTitle = text.trim();
    if (newsTitle.length > 0) {
      titles.push(newsTitle);
    }
  }
})

rw.transform(res);

console.log(titles)
```

### What is the expected behavior?

The expected behaviour is to output:

```shell
[ "Últimos artículos", "CURSOS de Programación Full Stack gratuitos",
  "Artículos por temas", "Libros", "Último vídeo en YouTube",
  "Último Podcast", "¡Suscríbete a la newsletter!"
]
```

### What do you see instead?

No output because it not process the HTML.

### Additional information / Workaround

There is a workaround that makes this works, you should replace the line with the transform for this one:

```ts
rw.transform(new Response(await res.text())); // This works
```

With that, you will see the expected output.

The code I am using in production and same code that is failing with Bun >= `0.8.x` works as expected with Bun `0.7.3`.

**Comment by Jarred-Sumner** [comment]
Thanks for the reproduction. Confirming that I'm able to reproduce this issue when running the script above enough times. It's likely a bug with fetch() body streaming (which was added in v0.8)

<img width="552" alt="image" src="https://github.com/oven-sh/bun/assets/709451/d39534b2-2211-495e-a9ef-e55551fada04">

**Comment by gtrabanco** [comment]
This is still failing with revision `0.8.2+f73f77d0dec9006f5f42ff401fb32f9eaefa749a`. Not sure if it should be resolved but seems like it should due the #4418 was applied in commit `2d80f94edafe09329b027424b32908632694553d` which is behind.

@cirospaciari

**Comment by gtrabanco** [comment]
I had to do a this workaround to rewrite a response with `HTMLRewriter` which means that this is happening also without doing `fetch`:
- https://github.com/gtrabanco/elysia-inject-html/blob/965357c582e661f1db8bb87d2d9bbd560566f17b/src/index.ts#L104

Bun revision: `1.0.4+ec0e931e9f7934f4f1f7617eac2a880d13794d0c`

**Comment by ogawa0071** [comment]
This problem works fine by waiting for asynchronous execution through the workaround below.

```diff
const url = 'https://midu.dev';
const res = await fetch(url);
const titles: string[] = [];

const rw = new HTMLRewriter();
rw.on('h3', {
  element: (element: HTMLRewriterTypes.Element) => {
    // console.log('Inside element');
  },
  text: ({ text }: HTMLRewriterTypes.Text) => {
    const newsTitle = text.trim();
    if (newsTitle.length > 0) {
      titles.push(newsTitle);
    }
  }
})

- rw.transform(res);
+ const _response = rw.transform(res);
+ await _response.text();

console.log(titles)
```

**Comment by Jarred-Sumner** [comment]
It was supposed to work this way originally. Prior to v0.8, we did not support fetch() body streaming. So `await fetch(...)` would have the complete body. You'll need to wait for the response to have the complete body before proceeding. `await response.text()` or `await response.blob()` works. 

Maybe we should add a `transformAndWait` function for this usecase which would return a `Promise<Response>`.

**Comment by gtrabanco** [comment]
> It was supposed to work this way originally. Prior to v0.8, we did not support fetch() body streaming. So `await fetch(...)` would have the complete body. You'll need to wait for the response to have the complete body before proceeding. `await response.text()` or `await response.blob()` works.
> 
> Maybe we should add a `transformAndWait` function for this usecase which would return a `Promise<Response>`.

But this is not how node works. See this example from Cloudflare: https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/#element-handlers

Maybe I am wrong, am I?
