### ISSUE TITLE
Same name in import and export causes problems in Bun, not in Node

### ISSUE THREAD

**Issue by inad9300** [oven-sh/bun#4413]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

Run `bun yt.mjs` with the single line `import 'youtubei.js'` in it. In contrast to Node, which returns without error, Bun spits:
```
 7 | export * as YTMusic from './ytmusic/index.js';
 8 | export * as YTKids from './ytkids/index.js';
 9 | export * as Helpers from './helpers.js';
10 | export * as Generator from './generator.js';
11 | import * as Parser from './parser.js';
12 | export default Parser;
   ^
SyntaxError: Cannot declare an imported binding name twice: 'Parser'.
      at .../node_modules/youtubei.js/dist/src/parser/index.js:12:0
```

### Additional information

Full contents of `.../parser/index.js` (notice the first and last lines):
```
export * as Parser from './parser.js';
export * from './continuations.js';
export * from './types/index.js';
export * as Misc from './misc.js';
export * as YTNodes from './nodes.js';
export * as YT from './youtube/index.js';
export * as YTMusic from './ytmusic/index.js';
export * as YTKids from './ytkids/index.js';
export * as Helpers from './helpers.js';
export * as Generator from './generator.js';
import * as Parser from './parser.js';
export default Parser;
//# sourceMappingURL=index.js.map
```

Original source code: https://github.com/LuanRT/YouTube.js/blob/2e5f076fd7a8eaa51f0e7be14134568a2f2e70a6/src/parser/index.ts.

**Comment by gtrabanco** [comment]
Have you tried with:

```js
export { Parser as default }
```

or you can do a named export:

```js
export { Parser }
```

**Comment by inad9300** [comment]
I am trying to import an external library over which I don't have any control.
