### ISSUE TITLE
Support st (static file server package)

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4417]
st - [npm](https://www.npmjs.com/package/st) - [github](https://github.com/isaacs/st)

### What version of Bun is running?

0.8.2+908018a4df5b03168988993f0b664d9443fca381

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```js
const st = require('st')
const http = require('http')

http.createServer(
  st(process.cwd())
).listen(1337)
```

### What is the expected behavior?

Start a server, accessible at localhost:1337

### What do you see instead?

When I go to `localhost:1337` i see this:

```zig
bun-kitchensink on  main [!?] via 🍞 v0.8.2 took 2.4s 
➜ bun --bun run index.js
608 |         this.cache.stat.get(pf, (er, stat) => {
609 |           if (er) {
610 |             return cb(er)
611 |           }
612 |           if (stat.isDirectory()) {
613 |             stat.size = '-'
                ^
TypeError: Attempted to assign to readonly property.
      at /Users/admin/repos/bun-kitchensink/node_modules/st/st.js:613:12
      at /Users/admin/repos/bun-kitchensink/node_modules/async-cache/ac.js:79:6
      at forEach (:1:20)
      at /Users/admin/repos/bun-kitchensink/node_modules/async-cache/ac.js:78:4
      at callback (/Users/admin/repos/bun-kitchensink/node_modules/graceful-fs/polyfills.js:306:16)
```

**Comment by paperclover** [comment]
this will be problematic to fix as `.size` there points to a `Stats` object that we implement in native code and simply point to `u64`s. overriding this in js needs to be supported for this package to work (it doesnt expose the stat in user API but it does use it as a part of sorting index pages) but i feel like will de-optimize things a bit.

**Comment by birkskyum** [comment]
I don't know how many of the 54 mil weekly downloads of https://www.npmjs.com/package/graceful-fs this would hit if ran by bun, but for those affected this can't really be de-optimized further.

**Comment by birkskyum** [comment]
It seems like `st` is on a downwards trend, so maybe there is an obvious replacement to it that I don't know, which could be mentioned here, and the ticket closed.

**Comment by birkskyum** [comment]
I reckon it's [http-server](https://www.npmjs.com/package/http-server) with directory listing that is the reasonable way to do this today.

**Comment by birkskyum** [comment]
this optimization will make adoption harder for `st` users, as I don't see an easy drop-in replacement for it. `http-server` can to some extend replace it when used as cli, but `st` can also be used from within the js

**Comment by nektro** [comment]
this looks to be working now. are you able to confirm?

**Comment by birkskyum** [comment]
@nektro  when i open the browser and click a file, i get an error like this

```sh
➜ bun --bun run index.ts
472 |     res.statusCode = 200
473 | 
474 |     if (gz) {
475 |       // we don't know how long it'll be, since it will be compressed.
476 |       res.setHeader('content-encoding', 'gzip')
477 |       stream.pipe(gzstr).pipe(res)
            ^
TypeError: undefined is not an object
      at node:stream:2087:83
      at streamFile (/Users/admin/repos/bun-kitchensink/test-tauri/node_modules/st/st.js:477:7)
      at file (/Users/admin/repos/bun-kitchensink/test-tauri/node_modules/st/st.js:417:7)
      at /Users/admin/repos/bun-kitchensink/test-tauri/node_modules/async-cache/ac.js:79:7
      at forEach (:1:21)
      at /Users/admin/repos/bun-kitchensink/test-tauri/node_modules/async-cache/ac.js:78:5
      at /Users/admin/repos/bun-kitchensink/test-tauri/node_modules/st/st.js:639:9
      at callback (/Users/admin/repos/bun-kitchensink/test-tauri/node_modules/graceful-fs/polyfills.js:306:17)

Bun v1.1.8-canary.1+3c082012b (macOS arm64)
```

**Comment by nektro** [comment]
whittled this down to an error in handling of `graceful-fs`. making `st` use `node:fs` unconditionally works as expected. need to wrap up another pr and will come back to this

**Comment by nektro** [comment]
`stream` from the trace for some reason doesn't have its `_readableState` field

**Comment by nektro** [comment]
narrowed this down again to `fs.ReadStream` being a class instead of a function. fixing...

**Comment by birkskyum** [comment]
Awesome, Thanks!
