### ISSUE TITLE
`beforeAll` error is swallowed

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#4422]
### What version of Bun is running?

0.8.2+9334fbe9b4facdfa9057a25e88e998f1fd2e346a

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

File
```js
import { beforeAll, test, expect } from "bun:test";

beforeAll(() => {
  throw new Error("Oops");
});

test("test", () => {});
```

Output:
```console
bun test v0.8.2 (9334fbe9)

file.test.ts:
✗ test

 0 pass
 1 fail
Ran 1 tests across 1 files. [13.00ms]
```

### What is the expected behavior?

You would expect the error message to get printed, but it does not.

**Comment by Jarred-Sumner** [comment]
No longer occurs as of Bun v1.0.1
