### ISSUE TITLE
improve http.ServerResponse

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#4430]
### What version of Bun is running?

0.8.2+9334fbe9b4facdfa9057a25e88e998f1fd2e346a

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
const http = require('http');
const res = new http.ServerResponse({});
console.log(res.constructor.name);
```

### What is the expected behavior?

```sh
❯ node test-bun.js
ServerResponse
```

### What do you see instead?

```sh
❯ bun test-bun.js 
621 | }
622 | var OriginalWriteHeadFn, OriginalImplicitHeadFn;
623 | 
624 | class ServerResponse extends Writable {
625 | 
626 |   constructor({ req, reply }) {
                              ^
TypeError: undefined is not an object
      at new ServerResponse (node:http:626:26)
      at <path>/test-bun.js:4:12
      at globalThis (<path>/test-bun.js:5:32)
```

### Additional information

https://github.com/fastify/light-my-request/blob/v5.10.0/lib/response.js#L10

**Comment by btmnk** [comment]
I would really love to see these changes in a release. If I'm not mistaken this currently also affects @fastify/websocket.
Fastify works great with bun so far but the websocket integration breaks with the node:http implementation in bun (Same error as stated above).

I wonder if there is a workaround I can use until this gets released? (Except for using node again :D)

**Comment by grefrit** [comment]
@btmnk Did you find workaround for fastify/websocket? It seems that assignSocket not implemented error is the only thing that stops me from using Bun

**Comment by btmnk** [comment]
> @btmnk Did you find workaround for fastify/websocket? It seems that assignSocket not implemented error is the only thing that stops me from using Bun

Unfortunately not yet.. I'm using node again for the project until this gets sorted.

(I didn't try much though, so there might be a workaround but the project wasn't that important so I didn't invest much time)
