### ISSUE TITLE
Recursive `cp` fails when the destination has a trailing slash

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#4436]
Glad to see https://github.com/oven-sh/bun/pull/4340 in canary! I've run into the following issue with the initial implementation:

### What version of Bun is running?

0.8.2+9334fbe9b4facdfa9057a25e88e998f1fd2e346a

### What platform is your computer?

macOS Ventura 13.5.1

### What steps can reproduce the bug?

```js
import { mkdir, cp, writeFile } from "node:fs/promises";

// Set up
await mkdir("./a/", { recursive: true });
writeFile("./a/foo.txt", "hello world");
await mkdir("./b/", { recursive: true });

// Copy from `./a/` to `./b/c/`
await cp("./a/", "./b/c/", { recursive: true });
```

### What is the expected behavior?

A folder at `./b/c/` is created, containing `foo.txt`.

(This is what `node` does. Note that both paths have trailing slashes, so they unambiguously refer to folders and not files.)

### What do you see instead?

```
ENOENT: No such file or directory
   path: "./b/"
 syscall: "clonefile"
   errno: -2
```

### Additional information

For a "real-world" case, try:

```shell
git clone https://github.com/lgarron/barely-a-dev-server && cd barely-a-dev-server
git checkout 79f70b086365a54b3b7fe7f09e3cc34dcd96cf17
bun run ./test/build.js
```

On [this line](https://github.com/lgarron/barely-a-dev-server/blob/923c708a0f2a0c17cd5ec5d5a99aade28d12ac0b/src/index.js#L28) it should be copying the contents of `./test/root/` to `dist/test/root/` but instead it errors with:

```
ENOENT: No such file or directory
   path: "dist/test/ro"
 syscall: "clonefile"
   errno: -2
```

Note that:

- The error shows a truncated path of `dist/test/ro`
- Even if `dist/test/root` exists, it is *deleted* by `bun`(!) instead of having files copied to it.

**Comment by paperclover** [comment]
thanks for the repro, it didn't seem to really be about trailing slashes but rather a case where bun wouldnt `mkdir` in this case.

there were also mistakes in the error message

**Comment by lgarron** [comment]
@paperdave Thanks, it's working perfectly in `0.8.2+5288178c865cd9dcb500b00a65197bf2641d4e5c` canary, even inside a significantly complicated build system! 😻
