### ISSUE TITLE
Websocket close event does not publish message

### ISSUE THREAD

**Issue by unpseudocomplique** [oven-sh/bun#4443]
### What is the problem this feature would solve?

When a close event is fired ws can not publish that for exemple a user as leaved the room.
![image](https://github.com/oven-sh/bun/assets/69119668/9dd8c31c-8cc8-4f6c-81ef-1932569a3b95)

### What is the feature you are proposing to solve the problem?

Could alias ws.publish to server.publish ?

Original discution here : https://discord.com/channels/876711213126520882/1146909757307891722

**Comment by twsau** [comment]
Running into this too :(

**Comment by frarillotta** [comment]
just ran into this as well. The return value of the publish was 0 (The message was dropped due to a connection issue) but was unable to get more info.

**Comment by Jarred-Sumner** [comment]
This will be fixed in Bun v1.1.27
