### ISSUE TITLE
[1]    31139 illegal hardware instruction (core dumped)  bun

### ISSUE THREAD

**Issue by fastslack** [oven-sh/bun#446]
Tried to run bun on Linux, Pop Os distribution latest version.

```
[1]    31139 illegal hardware instruction (core dumped)  bun
```

**Comment by MadadiSaeed** [comment]
Me too. linux x64.

**Comment by FinnRG** [comment]
@fastslack Could you paste the output of ```grep avx2 /proc/cpuinfo```?

**Comment by RickVerbon** [comment]
I get the error without "hardware"
- Illegal instruction (core dumped)

grep avx2 /proc/cpuinfo doesn't return anything for me. grep avx /proc/cpuinfo returns:
- https://pastebin.com/4iDyGdy6

**Comment by FinnRG** [comment]
@k0wek Your system doesn't support AVX2, which currently is a hard requirement. Please look at #67 or #282 for further information.

**Comment by DanielRamosAcosta** [comment]
Also, duplicated of #252
