### ISSUE TITLE
Different http outputs when running "bun run http.js" vs "bun dev"

### ISSUE THREAD

**Issue by vibecoder** [oven-sh/bun#447]
Env: Arch Linux
Installation: Using curl script.

Ran `curl http://localhost:3000/` after both the commands.

after `bun run http.js`
```
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 HM
< content-type: text/plain;charset=utf-8
< Content-Length: 15
<
* Connection #0 to host localhost left intact
Welcome to Bun!% 
```

after `bun dev`
```
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Fri, 8 Jul 2022 15:41:49 GMT
< Connection: close
<
* Closing connection 0

```

**Comment by vibecoder** [comment]
// http.js
```
// http.js
export default {
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
};
```

**Comment by vibecoder** [comment]
As per @TheSeyan#8202 on discord
"
bun dev will simply start a dev server on port 3000
my guess is that it serves static content
it has nothing to do with your http.js
"

So created a index.html and the index.html got served and the http.js did not run.

Please close the comments if you guys feel that this is clear to the user or we can update this in the docs.

**Comment by Electroid** [comment]
Thanks for this feedback! We're aware of the confusing about `bun dev`, and will make that clear in the upcoming docs or make it work more like `bun run` with development features. We're not sure yet, but we're tracking this!
