### ISSUE TITLE
The `descibe.only` causes later tests to be skipped when running without `--only` flag

### ISSUE THREAD

**Issue by Xkonti** [oven-sh/bun#4470]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Create several test files with at least 1 test in each.
2. Run `bun test` to see the order in which test files are executed
3. Add `.only` to either a `test` or `describe` in one of the test files that isn't the last one in execution order
4. Run `bun test` again - tests in files after the one with `.only` won't run

### What is the expected behavior?

It's expected that the `.only` will only take effect when running `bun test --only`. It's expected that all test files would be executed.

### What do you see instead?

Tests are not running after `only` has been encountered. It finds the file `getList.test.ts` but doesn't execute 15 tests that are inside:

```
✓ Upload file > should return 400 when trying to upload empty file [0.08ms]
✓ Upload file > should return 400 when trying to upload empty file [0.10ms]
✓ Upload file > should return 400 when trying to upload empty file [0.13ms]
✓ Upload file > should return 400 when trying to upload empty file [0.10ms]
✓ Upload file > should return 400 when trying to upload empty file [0.08ms]

src/endpoints/list/getList.test.ts:
----------------------------------|---------|---------|-------------------
File                              | % Funcs | % Lines | Uncovered Line #s
----------------------------------|---------|---------|-------------------
All files                         |  100.00 |   92.67 |
```

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.1.26
