### ISSUE TITLE
Support `apt-get install bun`

### ISSUE THREAD

**Issue by remcohaszing** [oven-sh/bun#4471]
### What is the problem this feature would solve?

As an Ubuntu / Debian / Pop!_OS user, I would like to install Bun using the builtin package manager: `apt` (aka `apt-get`). This means it will be kept up-to-date automatically with system dependencies.

### What is the feature you are proposing to solve the problem?

Host a PPA

### What alternatives have you considered?

Many projects use https://launchpad.net. Also a lot of projects use a custom domain.

**Comment by Electroid** [comment]
Yep, this is something we definitely want to support!

**Comment by Electroid** [comment]
Duplicate of #862
