### ISSUE TITLE
Installing globally a package does not install its peer dependencies

### ISSUE THREAD

**Issue by jeremylvln** [oven-sh/bun#4472]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.0-79-generic aarch64 aarch64

### What steps can reproduce the bug?

Installing a package globally will not install the listed peer dependencies (in the following example, [see source](https://gitlab.com/getanthill/datastore/-/blob/master/package.json?ref_type=heads#L47)).

```sh
$ bun install -g @getanthill/datastore

# It installs a global ds script
$ ds
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@getanthill/telemetry'
Require stack:
- /home/vscode/.bun/install/global/node_modules/@getanthill/datastore/dist/services/index.js
```

### What is the expected behavior?

When installing a package globally, bun should also install the needed peer dependencies. Installing the missing package globally by hand fixes the issue (`bun install -g @getanthill/telemetry`).

### What do you see instead?

See above!

**Comment by sturmenta** [comment]
+1

**Comment by tobi-or-not-tobi** [comment]
Duplicates #3410
