### ISSUE TITLE
problem with http and sockets: @gradio/client not working

### ISSUE THREAD

**Issue by janwilmake** [oven-sh/bun#4479]
### What version of Bun is running?

0.8.1

### What steps can reproduce the bug?

Try running `@gradio/client` predict

### What is the expected behavior?

Same as in node.js, it doesn't crash

### What do you see instead?

<img width="773" alt="Screenshot 2023-09-04 at 21 01 41" src="https://github.com/oven-sh/bun/assets/97664551/f82b4f67-259f-4a63-a702-a7a834d52227">

### Additional information

It seems it's attempting to establish a WebSocket connection but it's aborted with an 101 error

**Comment by Electroid** [comment]
This appears to be an issue with `WebSocket`, which we are tracking and will fix here: #6686
