### ISSUE TITLE
process.stdout -> "ENXIO: No such device or address" (rush build)

### ISSUE THREAD

**Issue by jonasb** [oven-sh/bun#4481]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.0-1041-azure x86_64 unknown

### What steps can reproduce the bug?

Unfortunately the circumstances are quite specific/elaborate. I haven't been able to boil it down further yet.

* Be on Linux
* Run bun as part of `rush build` ([Rush](https://rushjs.io/) is a monorepo manager)
* Access `process.stdout` and get an error (I've tried both `process.stdout.isTTY` and `process.stdout.write()`)

Github action log: https://github.com/dossierhq/dossierhq/actions/runs/6072140187/job/16471545680#step:12:350

Can also be run in GitHub Codespace: https://github.com/dossierhq/dossierhq
* Run `rush build -o benchpress -v`
* Running it directly (i.e. without `rush build`) works without a problem: `(cd libraries/benchpress/ && bun run ./src/examples/timer-benchmark.ts)`

### What is the expected behavior?

I expect `process.stdout` to work.

### What do you see instead?

```
423 |       return instance instanceof InternalWriteStream;
424 |     }
425 |   });
426 | }(class WriteStream2 extends Stream.NativeWritable {
427 | 
428 |   constructor(path, options = defaultWriteStreamOptions) {
                             ^
ENXIO: No such device or address
   path: "/dev/fd/1"
 syscall: "open"
   errno: -6

      at new WriteStream2 (node:fs:428:26)
      at WriteStream3 (node:fs:419:46)
      at new  (node:tty:22:50)
      at node:tty:22:50
      at getStdioWriteStream (:1:20)
      at replaceStdoutLineIfSupported (/home/runner/work/dossierhq/dossierhq/libraries/benchpress/src/compat/LogUtils.ts:10:6)
      at /home/runner/work/dossierhq/dossierhq/libraries/benchpress/src/Runner.ts:31:4
      at runTest (/home/runner/work/dossierhq/dossierhq/libraries/benchpress/src/Runner.ts:22:2)
      at /home/runner/work/dossierhq/dossierhq/libraries/benchpress/src/examples/timer-benchmark.ts:4:23
Returned error code: 1
```

### Additional information

* I don't see this issue on Mac
* I started seeing this issue on Linux / Github Actions when upgrading to bun 0.8 (bun <0.8 works fine)
* When running bun directly it works perfectly, it's only when bun is run by rush when I see the problem
* The same code works on Node
* Rush captures and processes the output when running the equivalent of `npm run build`. I don't know exactly what it does.

**Comment by dylan-conway** [comment]
Can you try this on a canary build of bun?
```
bun upgrade --canary
```

**Comment by jonasb** [comment]
@dylan-conway Yeah, works well with `0.8.2+bc2b55fdeee3001b07252d0f250671ea1876a3ed`!

So I guess I can expect it in the next release?

**Comment by dylan-conway** [comment]
Awesome, thanks for trying. Yes the fix will be included in the next release
