### ISSUE TITLE
Can't install type declarations for Express

### ISSUE THREAD

**Issue by Durgesh002** [oven-sh/bun#4494]
hello, I'm installed express using
**bun add -d express**
but how do I install type declarations for it ? Because, while importing express I get an error. The error says "**express or its corresponding type declarations not found"**.

**Comment by Hanaasagi** [comment]
try `bun add -d @types/express`

**Comment by Durgesh002** [comment]
Thanks. Soon after creating the issue. I did try `bun add -d @types/express`. It works. Thanks
