### ISSUE TITLE
Bun.serve not working on tls with HTML Response 

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#4497]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```
globalThis.Bun.serve({
    fetch(req) {
        const getFile = globalThis.Bun.file("./wb-form-registration.html");

        console.log('getFile = ', getFile, getFile.size);
        
      return new Response(getFile);          // not working with page : Why am I seeing this page?
    //   return new Response("Hello!!!");  // fine working 
    },
    tls: {
      key: globalThis.Bun.file("./key.pem"), // path to TLS key
      cert: globalThis.Bun.file("./cert.pem"), // path to TLS cert
      ca: globalThis.Bun.file("./ca.pem"), // path to root CA certificate
      passphrase: "localhost",
    }
  });
```

[test.zip](https://github.com/oven-sh/bun/files/12521032/test.zip)

### What is the expected behavior?

The code works in 0.71 as well

**Comment by Jarred-Sumner** [comment]
Please upgrade to the canary build of Bun, where this is fixed

```bun upgrade --canary```

Leave a comment if you still run into it

**Comment by truongan07** [comment]
i did upgrade and it works very well. Thank you. So before, i think my code is wrong, test and test.
