### ISSUE TITLE
[BUG] Bun ignores global.d.ts/declare in serve

### ISSUE THREAD

**Issue by DerGoogler** [oven-sh/bun#450]
When I run `bun dev` and open the web page at port 3000 gives me the following errors:

![image](https://user-images.githubusercontent.com/54764558/178044827-1d95651d-ebd4-4882-8839-bcd8cd79b69b.png)  
![image](https://user-images.githubusercontent.com/54764558/178044886-4614e46f-939b-434a-b349-5b48f6163d68.png)

**Comment by FinnRG** [comment]
Could you provide a repo with a minimal reproducible example?

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
