### ISSUE TITLE
fs.promises.stat doesn't throw ENOENT with empty string

### ISSUE THREAD

**Issue by coratgerl** [oven-sh/bun#4509]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

fs.promises.stat should return ENOENT with path equal to "".

**This code with bun :**
```javascript
import { promises } from 'fs'

const test = async () => {
	console.log(await promises.stat(''))
}

test()
```
![image](https://github.com/oven-sh/bun/assets/73360179/4e5742da-bee9-4ade-964b-fdf5fb844cfd)

**Same code with node :**
<img width="468" alt="image" src="https://github.com/oven-sh/bun/assets/73360179/ea3cd9d9-6a35-4f4b-bb13-863368db85dd">

### What is the expected behavior?

Return ENOENT with empty string

### Additional information

This bug block the use of the library mongodb-memory-server usefull to test a lot of applications.

**Comment by birkskyum** [comment]
same with latest version - 0.8.2+bc2b55fdeee3001b07252d0f250671ea1876a3ed

**Comment by jdmarshall** [comment]
There are a bunch of other places where bun doesn't issue ENOENT where nodejs does.

I've already seen 4 PRs for github projects that are 'fixing' the module so it works with Bun. How many modules touch the filesystem? It must be thousands. 

I just convinced someone to reject a PR on the basis that BunJS is wrong, not the node module, on the premise that I/We don't want to see 10,000 PRs to 'correct' file access sanity checking code across the entire Javascript and Typescript ecosystem. 

https://github.com/node-config/node-config/pull/744

How about we don't invite a proliferation of logic that looks like 

```
if (e2.code !== 'ENOENT' && e2.code !== 'EBADF') {
```

by externalizing compatibility issues onto a 10+ year old ecosystem, full of projects that haven't accepted a PR in 3 years?

I can see from other bug reports and PRs here that Bun is capable of issuing ENOENT, it just doesn't do it in the same places Node does. I don't think that's a feature. I think it's an unnecessary compatibility issue, and perhaps speaks to Bun needing E2E tests that consist entirely of running unit and integration tests for known OSS projects, and ensuring they are green on Bun.

When you break compatibility it should be for something important, like architectural improvements, not error codes.

**Comment by Electroid** [comment]
@jdmarshall If Node.js throws one error code, and Bun throws a different error code, for the same scenario; that is indeed a bug with Bun and we will fix it. If there are other places you notice we are throwing different errors, please open an issue and we'll address it.

**Comment by jdmarshall** [comment]
Good to hear.  I will start encouraging others to do the same. I'll ping the gentleman above and see if I can get him to condense out a repro case. Unfortunately I think there are three other things going on there at the moment.
