### ISSUE TITLE
Unable to install package using github url like npm/pnpm

### ISSUE THREAD

**Issue by SandipNirmal** [oven-sh/bun#4512]
### What version of Bun is running?

0.8.1

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

Installing package directly using github url. Bun always looks for `npm registry` even when github url is specified.

### What is the expected behavior?

Should install node package from github url like npm/pnpm.

**Comment by ghost** [comment]
what package was it?

**Comment by Hanaasagi** [comment]
test locally using the hexo GitHub url, and it works fine. need more information to reproduce.

![2023-09-06_17-06](https://github.com/oven-sh/bun/assets/9482395/c16fbb22-b889-4ffe-a865-2c588411b1ef)

**Comment by ar1g** [comment]
ideally bun should support the new syntax for github urls: `<user or org>/<repo>#<branch>` as per https://docs.npmjs.com/cli/v10/configuring-npm/package-json#github-urls

**Comment by Electroid** [comment]
As of Bun v1.0.7, these now work:

```json
{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "express": "expressjs/express",
    "mocha": "mochajs/mocha#4727d357ea"
  }
}
```

```
❯ bun install
bun install v1.0.7 (b0393fba)
 + express@github:expressjs/express#2a00da2
 + mocha@github:mochajs/mocha#4727d35

 79 packages installed [3.59s]
```
