### ISSUE TITLE
[HTTP server] req.signal.onabort not called when HTTP request is closed

### ISSUE THREAD

**Issue by A-D-E-A** [oven-sh/bun#4517]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Microsoft Windows NT 10.0.25931.0 x64 > Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

The `onabort` handler (or `addEventListener("abort", ...)`) set on the request signal is not called when ending a request to which a response has been sent, unless we manually check the `aborted` property.

Run the server below.

```ts
Bun.serve({
	port: 2000,
	fetch(req) {
		const { readable, writable } = new TransformStream();
		const encoder = new TextEncoder();
		const writer = writable.getWriter();

		setInterval(() => {
			const bytes = encoder.encode("Hello!\n");
			const bytesWritten = bytes.length;
			writer.write(bytes);
			const bytes_needed = 4096 - (bytesWritten % 4096);
			const BACKSPACE = 8;
			writer.write(new Uint8Array(bytes_needed).fill(BACKSPACE));
		}, 1000);

		req.signal.onabort = () => {
			console.log("Aborted!");
		};

		return new Response(readable, {
			headers: {
				"Content-Type": "text/event-stream",
			},
		});
	},
});
```

In another console,
```sh
curl http://localhost:2000
```

### What is the expected behavior?

Bun terminal
```sh
> bun run index.ts
# 2.5 seconds later >
Aborted!
```

Curl terminal
```sh
> curl http://localhost:2000
Hello!
Hello!
# After 2.5 seconds, cancel
^C
>
```

### What do you see instead?

Bun terminal
```sh
> bun run index.ts
# Blank, nothing is logged
```

Curl terminal
```sh
> curl http://localhost:2000
Hello!
Hello!
# After 2.5 seconds, cancel
^C
>
```

### Additional information

It works if you cancel the request before it has been sent:
```ts
return new Promise((resolve) => {
	setTimeout(() => {
		resolve(new Response(readable, {
			headers: { "Content-Type": "text/event-stream" }
		});
	, 1000);
});
```
(cancel the request before 1sec and the `onabort` handler is called)

It also works if you read the `aborted` property.
```ts
req.signal.onabort = () => console.log("Aborted!");
setInterval(() => req.signal.aborted /* do nothing */, 2000);
```
(cancel the request, the "Aborted!" line should be logged in the following 2 seconds)

Or if you call `dispatchEvent(new Event("abort"))`, but it's clearly not the goal here.

That's a shame, because writing Server-Sent Events with the Bun dev server would be easy if that handler was called. I cannot cleanup the streams of data without it.
For now, I check the `aborted` property in an interval.

**Comment by Electroid** [comment]
Related: #6758
