### ISSUE TITLE
Next.js Link component usage results in errors

### ISSUE THREAD

**Issue by Rototu** [oven-sh/bun#452]
Hi all,

I am facing an error that seems to indicate lack of proper support for React hooks even though the package versions for both React and Next are recent ones.

I first tried using the Link component from Next.js in the basic app created with `bun create next --open` without changing any versions in package.json. I got the following error:
`TypeError: _react.default.useRef is not a function. (In '_react.default.useRef(false)', '_react.default.useRef' is undefined)`

Then I tried upgrading the versions of all the React and Next.js related packages to their latest versions and I got a similar error:
`TypeError: _react.default.createContext is not a function. (In '_react.default.createContext({})', '_react.default.createContext' is undefined)`

Below is the complete error stack for the latter error (running `bun dev`):
```
Error loading page: /Users/emafarau1/CODE/next/pages/index.tsx
 7 | function _interopRequireDefault(obj) {
 8 |     return obj && obj.__esModule ? obj : {
 9 |         default: obj
10 |     };
11 | }
12 | const HeadManagerContext = _react.default.createContext({});
                               ^
 TypeError: _react.default.createContext is not a function. (In '_react.default.createContext({})', '_react.default.createContext' is undefined)
      at /Users/emafarau1/CODE/next/node_modules/next/dist/shared/lib/head-manager-context.js:12:27
      at http://localhost:3000/blob:node_modules.server.bun:1:16430
      at /Users/emafarau1/CODE/next/node_modules/next/dist/client/script.js:9:34
      at http://localhost:3000/blob:node_modules.server.bun:1:16430
      at /Users/emafarau1/CODE/next/node_modules/next/dist/shared/lib/router/router.js:13:22
      at http://localhost:3000/blob:node_modules.server.bun:1:16430
      at /Users/emafarau1/CODE/next/node_modules/next/dist/client/link.js:7:22
      at http://localhost:3000/blob:node_modules.server.bun:1:16430
      at /Users/emafarau1/CODE/next/node_modules/next/link.js:1:25
      at http://localhost:3000/blob:node_modules.server.bun:1:16430
      at /Users/emafarau1/CODE/next/components/HeaderLink.tsx:1:0
```

The error does not prevent the website from rendering or functioning properly though which makes things even more confusing 😄 

For completeness, below is the package.json:
```json
{
  "name": "next",
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {
    "tailwind": "tailwindcss -i styles/globals-base.css -o styles/globals.css --minify --watch "
  },
  "dependencies": {
    "next": "12.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-is": "18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18",
    "autoprefixer": "^10.4.7",
    "bun-framework-next": "^12",
    "react-refresh": "0.14.0",
    "tailwindcss": "^3.1.5",
    "typescript": "latest"
  }
}
```
(I am running `bun run tailwind` in parallel but I don't believe that to be the cause of the error.)

**Comment by Jarred-Sumner** [comment]
I think this is a CommonJS transform issue introduced shortly before bun v0.1.0, where a server-side-only transform is being run client-side

I believe the page appears to work because it is SSR'ing successfully and then failing to client-side render. Effectively, static html

**Comment by Rototu** [comment]
Just to add more detail to this in case it helps, I can use react hooks in my code and can update state successfully in browser (used a simple state variable that updates on click), it's just the Next.js `Link` component that is throwing a fit.

For even more details, though probably it's not relevant, I am running this on a 2019 Intel based Mac Pro using macOS Monterey 12.4.

**Comment by jparw3** [comment]
did you find a fix for this?

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
