### ISSUE TITLE
`bun build` breaks on some node builtins without node: specifiers

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#4521]
### What version of Bun is running?

0.8.2+70a5cfe9087c9836cef06ee3560f6111ed2fe18e

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Works:

```ts
import fs from "fs"
console.log(fs);
```

Breaks: at least for readline, child_process

```ts
import readline from "readline"
console.log(readline);
```

Error

```sh
error: Could not resolve Node.js builtin: "readline". To use Node.js builtins, set target to 'node' or 'bun'
import readline from "readline"
                     ^
```

This is a problem because sometimes dependencies doesn't have the `node:` so it's not trivial to just add that everywhere.

**Comment by Jarred-Sumner** [comment]
This is a confusing error message, but not a bug

Note the error message:
> To use Node.js builtins, set target to 'node' or 'bun'

`bun build` defaults to a `--target=browser`, and `readline` is unavailable in browsers

**Comment by birkskyum** [comment]
Aaah, thanks.
