### ISSUE TITLE
FileSystemRouter reload method not working

### ISSUE THREAD

**Issue by atinseau** [oven-sh/bun#4522]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Hello !

I'm trying to used FIleSystemRouter with watch function from fs but when i renamed, moved, deleted a file in the watched directory, the router keep the last route state (same routes, no change)

i tried many thing, like removing watch function and create a setInterval and reload router and console the router, but still same

i prepared for you a little zip containing minimal reproduction code

repro:
   add a new page in pages directory and remove it after

[FileSystemRouter_issue.zip](https://github.com/oven-sh/bun/files/12538806/FileSystemRouter_issue.zip)

thank you ! 

### What is the expected behavior?

refreshing the router instance to see the new discovered routes

**Comment by gtrabanco** [comment]
Same problem:

Machine: `Darwin 21.6.0 x86_64 i386`
Bun revision: 1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

## Code

```ts
const fsr = new FileSystemRouter({ 
  dir,
  style: 'nextjs',
  assetPrefix: '',
  origin: 'http://localhost:3000',
});

const watcher = watch(dir, { recursive: true, persistent: true }, async (eventType) => {
  fsr.reload();
  console.log(eventType, fsr.routes, fsr.match('/u'))
})
```

I also tested with this with same results:

```ts
let fsr = new FileSystemRouter({ 
  dir,
  style: 'nextjs',
  assetPrefix: '',
  origin: 'http://localhost:3000',
});

const watcher = watch(dir, { recursive: true, persistent: true }, async (eventType) => {
  fsr = new FileSystemRouter({ 
    dir,
    style: 'nextjs',
    assetPrefix: '',
    origin: 'http://localhost:3000',
  });
  console.log(eventType, fsr.routes, fsr.match('/u'))
})
```

**Comment by Kapsonfire-DE** [comment]
still buggy
