### ISSUE TITLE
`ReferenceError`: Can't Find Variable `myObj` 

### ISSUE THREAD

**Issue by Shiva953** [oven-sh/bun#4527]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

1. Define main.js as follows : 
```js
myObj = {
    favoriteNumber: 73,
    isDeveloper: true,
    firstName: "Shiva"
};

const favoriteNumber = (
    myObj.favoriteNumber !== undefined ? myObj.favoriteNumber : 42
);
const isDev = myObj.isDeveloper;
const firstName = myObj.firstName;
const lname = (
    myObj.lastName !== undefined ? myObj.lastName : "--missing--"
);
console.log(myObj)
```
2. `bun main.js`

### What is the expected behavior?

The console output should be 
`{ favoriteNumber: 73, isDeveloper: true, firstName: 'Shiva' }`

### What do you see instead?

```
 myObj = {
   ^
ReferenceError: Can't find variable: myObj
```

### Additional information

In NodeJS environment, the `myObj` becomes a global variable and therefore doesn't need to be explicitly declared. Hence there's no runtime error. However, the same isn't true with the bun runtime.

**Comment by Aixel402** [comment]
Are you working on strict mode? myObj is not declared using var, const or let, maybe that's the error?

**Comment by Jarred-Sumner** [comment]
Bun defaults to strict mode unless some specific sloppy-mode features are used like `with` or the CommonJS exports keyword `exports.abc = 123`
