### ISSUE TITLE
bun's `node:tls` compat missing `TLSSocket.servername`

### ISSUE THREAD

**Issue by ignoramous** [oven-sh/bun#4535]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.4.0-135-generic x86_64 x86_64

### What steps can reproduce the bug?

On a TLS socket, try grabbing the `servername` property ([like we attempt here](https://github.com/serverless-dns/serverless-dns/blob/e64a44d541e574593dd720932f3b69905c997982/src/server-node.js#L720)). It always comes up empty.

### What is the expected behavior?

Should contain the contents of the *Server Name Identification* field from `ClientHello`

### What do you see instead?

Empty str

### Additional information

[Bun runtime docs](https://bun.sh/docs/runtime/nodejs-apis#node-tls) need to note that node's [`tlsSocket`](https://nodejs.org/api/tls.html#class-tlstlssocket) perhaps may not be fully implemented?

**Comment by cirospaciari** [comment]
already fixed in currently version of bun

**Comment by ignoramous** [comment]
Thanks.

Which version first had the fix? In our experiments, `TLSSocket.servername` was populated only *some* of the time (and not always) on bun v1.1.30
