### ISSUE TITLE
Babel - Can't find variable: jsx

### ISSUE THREAD

**Issue by zolomatok** [oven-sh/bun#454]
**Beautiful project, so happy this exists.**

I tried taking it for a spin using [Pug](https://github.com/pugjs/pug) (HTML preprocessor). It imports parts (?) of Babel. Simply the following two lines...

```
import * as pug from 'pug'
let html = pug.compile('p Bun!')
```

... run with `bun server.ts` result in: 

```
ReferenceError: Can't find variable: jsx
```

The full stack trace:

```
11657 |     throw error;
11658 |   }
11659 | }
11660 | const mixinPlugins = {
11661 |   estree,
11662 |   jsx,
      ^
 ReferenceError: Can't find variable: jsx
      at /Users/zolo/project/blog/node_modules/@babel/parser/lib/index.js:11662:2
      at bun:wrap:1:16430
      at /Users/zolo/project/blog/node_modules/constantinople/lib/index.js:3:23
      at bun:wrap:1:16430
      at /Users/zolo/project/blog/node_modules/pug-filters/lib/handle-filters.js:4:29
      at bun:wrap:1:16430
      at /Users/zolo/project/blog/node_modules/pug-filters/index.js:4:32
      at bun:wrap:1:16430
      at /Users/zolo/project/blog/node_modules/pug/lib/index.js:19:22
      at bun:wrap:1:16430
      at /Users/zolo/project/blog/server.ts:1:0
```

I understand if this is not much to go on, but if resembles a known issue, I'd love to know what causes it and if something could be done to handle it. Thank you!

_(The code above runs no problem in Node ofc)_

**Comment by FinnRG** [comment]
This is probably a duplicate of #421. Please post your message there and close this issue.

**Comment by zolomatok** [comment]
Thank you @FinnRG!
