### ISSUE TITLE
Astro runner not working

### ISSUE THREAD

**Issue by art0s-dev** [oven-sh/bun#4546]
### What version of Bun is running?

0.8

### What steps can reproduce the bug?

--@--:/-----$ bunx create-astro
/usr/bin/node: 1: ELF: not found
/usr/bin/node: 2: : not found
/usr/bin/node: 4: Syntax error: Unterminated quoted string

### What is the expected behavior?

cli-wizard like i the docs

### What do you see instead?

elf error

**Comment by thalting** [comment]
![image](https://github.com/oven-sh/bun/assets/105032603/8a885982-3787-4a21-ab77-7b6570238e78)
with bun 0.8.1 works for me
