### ISSUE TITLE
Unintuitive error on invalid tls configuration

### ISSUE THREAD

**Issue by Airtune** [oven-sh/bun#4555]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```js
Bun.serve({
  fetch(req, server) {
    return undefined;
  },
  tls: {
    key: Bun.file('./key.pm'),
    cert: Bun.file('./cert.pem')
  }
});
```

### What is the expected behavior?

I expected either an error for the BunFile not existing or for the tls configuration being wrong since I had a typo: `key.pm` instead of the correct `key.pem`

### What do you see instead?
```js
1 | Bun.serve({
  fetch(req, server) {
    return;
  },
  tls: {
    key: Bun.file("./key.pm"),
    cert: Bun.file("./cert.pem")
  }
});
   ^
TypeError: Expected fetch() to be a function
 code: "ERR_INVALID_ARG_TYPE"

index.ts:1:0
```

**Comment by Airtune** [comment]
I upgraded to bun v1.0.0 and I'm still seeing the same error

**Comment by josiaho** [comment]
Same result on 1.0.3

**Comment by tonyea** [comment]
Dang. Got the same issue as I was about to launch a production microservice. Going to have to route HTTPS via a containerized nginx for now.

**Comment by josiaho** [comment]
@tonyea Not sure if it helps in the meantime, but I have letsencrypt/certbot SSL working like this:

    const fs = require('fs');
    const https = require('https');
    const express = require('express');
    
    const app = express();
    
    app.get('/', (req, res) => {
      return res.send('Hello, world!');
    });
    
    https.createServer( {
      cert: fs.readFileSync('server.crt'),
      key: fs.readFileSync('server.key')
    }, app).listen(443);

**Comment by tonyea** [comment]
> const https = require('https');

Good point. Could just use express in the meantime without switching to a reverse proxy or abandoning bun

**Comment by tonyea** [comment]
Actually ended up using an nginx container and reverse proxied tls

**Comment by mollthecoder** [comment]
Having this issue on v1.0.14

**Comment by ghost** [comment]
I think found a solution!
You have to put the tls bit before the fetch bit, I had the same issue and this worked for me!
Your code would look like this:
```
Bun.serve({
  tls: {
    key: Bun.file('./key.pm'),
    cert: Bun.file('./cert.pem')
  },
  fetch(req, server) {
    return undefined;
  }
});
```
Please let me know if you implement it and it works!

**Comment by hjaber** [comment]
> Please let me know if you implement it and it works!

I continue to have the same error despite moving the order of the arguments with `tls` first:


```ts
6 | const server = Bun.serve({
                   ^
TypeError: Expected fetch() to be a function
 code: "ERR_INVALID_ARG_TYPE"
```

**Comment by ducviet321** [comment]
I have the same issue, even after moving it to the top. Funny I tried this method before reading your comment @ctrleo . 

Even if it's working, I believe changing document is just a temporary solution and people would encounter this issue again until they ended up at this post.

My system:

OpenSUSE 15.6
bun version 1.0.23

**Comment by ducviet321** [comment]
It could be bun does not have enough permission to read tls files, I haven't tested it out

https://github.com/oven-sh/bun/issues/4088

**Comment by hjaber** [comment]
>I believe the issue might be related to insufficient permissions for 'bun' to access the TLS files. Although I haven't tested it >myself, this could be the cause.
>
>Issue #4088

I've resolved the problem. I was attempting to access root user directories as a non-root user, where my SSL certificates were stored. After adjusting the directory permissions, my TLS is now functioning as expected. 

It seems like a simple oversight, but the error was indeed causing some confusion.

**Comment by TomasHubelbauer** [comment]
If you find yourself here from Google after just having minted a pair of PEM files with Let's Encrypt using the manual workflow and curiously, these files not only can't be loaded by Bun seemingly, but also can't be opened in VS Code, make sure you've not copied over just the symbolic links from `live/`and deleted the target filees but that you've copied over the actual target files.
