### ISSUE TITLE
dd-trace segfaults :(

### ISSUE THREAD

**Issue by sualehasif** [oven-sh/bun#4556]
### What version of Bun is running?

v0.8.1

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

https://www.npmjs.com/package/dd-trace causes a dyld segfault. minimal reproduction:

```
import { tracer, TracerOptions } from 'dd-trace';
const tracerOptions = {
	logInjection: true,
	profiling: true,
	sampleRate: 1,
	plugins: true,
	service: 'server',
	runtimeMetrics: true,
} as TracerOptions;
tracer.init(tracerOptions);


function main() {
	console.log("Hello world!");
}

main();
```

### What is the expected behavior?

```
➜  server bun src/test.ts
[0.06ms] ".env"
Hello world!
```

### What do you see instead?

```➜  server ✗ bun src/test.ts
[0.06ms] ".env"
dyld[53763]: missing symbol called
/Users/sualeh/Library/pnpm/bun: line 13: 53763 Killed: 9               "$basedir/global/5/node_modules/bun/bin/bun" "$@"```
```
### Additional information

probably datadog's fault. unclear how to resolve easily

**Comment by weyert** [comment]
Yeah, neither does the OpenTelemetry packages work for me

**Comment by birkskyum** [comment]
Hmm, when I run the repro I get the "Hello world" response with both 0.8.1 and latest canary, on similar hardware. @weyert , can you make a repro for the OpenTelemetry?

**Comment by sualehasif** [comment]
hmm, I am currently on:
"dd-trace": "^4.8.1",

**Comment by weyert** [comment]
There already is  #4333 and #4548 for my work's usage of OpenTelemetry. But I will work on a repro

**Comment by birkskyum** [comment]
@sualehasif , that makes the difference in my setup. 4.8.1 breaks, whereas the latest 4.14.x works.

**Comment by sualehasif** [comment]
yup this is true! 4.14.x works!

**Comment by weyert** [comment]
@birkskyum My reproduction for OpenTelemetry: https://github.com/weyert/bun-opentelemetry

**Comment by maschwenk** [comment]
@sualehasif It no longer segfaults for me but I get no tracing/metrics at all. To be expected I suppose, I'm guessing `dd-trace` digs into a lot of low-level Node APIs that aren't supported.

**Comment by xenyal** [comment]
@maschwenk `dd-trace` relies on dgram, you can track bun's support for it here: https://github.com/oven-sh/bun/issues/1630
