### ISSUE TITLE
Package manager doesn't works on linux or is too slow

### ISSUE THREAD

**Issue by iddar** [oven-sh/bun#4561]
### What version of Bun is running?

0.8.1

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

run `bun install` or `bunx bun-repl`

![image](https://github.com/oven-sh/bun/assets/199103/f65eba44-2b83-42fb-8988-a72177027e04)

### What is the expected behavior?

works 

### What do you see instead?

include bun crash file output after run ` bun create elysia app` same output for `bun install`
```
error: ConnectionRefused

----- bun meta -----
Bun v0.8.1 (16b4bf34) Linux x64 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000
CreateCommand: 
Elapsed: 129772ms | User: 0ms | Sys: 9ms
RSS: 34.61MB | Peak: 20.76MB | Commit: 34.61MB | Faults: 0
----- bun meta -----

0   0x55ee96152bbb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

```

### Additional information

I already tried doing a clean installation and changing my dns and nothing worked, with other package managers it works fine.

My internet provider is Starlink and I use zsh.

If I can help in any way I am available.

Thanks for such a great project.

**Comment by Hanaasagi** [comment]
Related to #4507.

Crash after `ConnectionRefused` when installing package or reading manifest. A simple way to reproduce this crash is

```Bash
http_proxy=http://127.0.0.1:1087 https_proxy=http://127.0.0.1:1087 bun create elysia app
```

This proxy doesn't exist, and the port is not being listened to by any program.
