### ISSUE TITLE
Support for jest CLI

### ISSUE THREAD

**Issue by ffMathy** [oven-sh/bun#4562]
### What is the problem this feature would solve?

We make heavy use of the Jest Vscode extension. And there, you can already control which command-line is being used (so changing "jest" to "bun") , but not the command-line flags. 

It looks like Bun is going to have support for Jest's API (matchers etc).

### What is the feature you are proposing to solve the problem?

Is the plan also to have support for Jest's CLI options, so that things like the Vscode extension for Jest will work with Bun? 

### What alternatives have you considered?

I am considering filing an issue over at the Vscode jest extension repo instead. Just wanted to get some input here first.

**Comment by Electroid** [comment]
There are a lot of open issues to support various Jest CLI options, see the [`jest`](https://github.com/oven-sh/bun/labels/jest) issue label.
