### ISSUE TITLE
`bun install` and `bun update` replaces tabs with spaces.

### ISSUE THREAD

**Issue by chribjel** [oven-sh/bun#4563]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Have an existing `package.json` with tabs and install a new package with either `bun add` or `bun install` , or run `bun update`. Now you have a diff on the whole file since those commands rewrote the file with spaces rather than tabs.

### What is the expected behavior?

The expected behaviour would be to preserve the indentation in the original file.

**Comment by uncenter** [comment]
Looks like `pnpm` uses [`@gwhitney/detect-indent`](https://www.npmjs.com/package/@gwhitney/detect-indent)/[`detect-indent`](https://github.com/sindresorhus/detect-indent):
https://github.com/pnpm/pnpm/blob/10cb4b3245d597a7e9b1b4bca2889421cd19bcdb/pkg-manifest/read-project-manifest/src/index.ts#L125
