### ISSUE TITLE
SyntaxError: Import named 'textSync' not found in module 

### ISSUE THREAD

**Issue by sunshinego12138** [oven-sh/bun#4564]
### What version of Bun is running?

0.7.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

According to the official QuickStart case

```shell
mkdir quickstart
cd quickstart
bun init
bun add figlet
bun add -d @types/figlet # TypeScript users only
```

```ts
// index.ts
import figlet from "figlet";

const server = Bun.serve({
  fetch() {
    const body = figlet.textSync('Bun!');
    return new Response(body);
  },
  port: 3000,
});

```
Now it's starting to report an error`SyntaxError: Import named 'textSync' not found in module`

### What is the expected behavior?

```shell
  ____              _
 | __ ) _   _ _ __ | |
 |  _ | | | | '_ | |
 | |_) | |_| | | | |_|
 |____/ __,_|_| |_(_)

```

### What do you see instead?

```shell
SyntaxError: Import named 'textSync' not found in module '/Users/macbook/Desktop/myProject/bunTest/node_modules/figlet/lib/node-figlet.js'.
```

### Additional information

nothing

**Comment by Hanaasagi** [comment]
cannot reproduce this issue in Bun 0.8.1. Could you try upgrading to the latest version and test it again? (Run `bun upgrade`)

![2023-09-08_16-48](https://github.com/oven-sh/bun/assets/9482395/0d014aa5-af7d-42c6-9da6-8f878f42d43a)

- Bun: 0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366
- figlet: 1.6.0
- Linux

**Comment by nektro** [comment]
it appears this is now working. if this is still impacting you please let us know and we'll be happy to take another look.
