### ISSUE TITLE
[Jest] Support `%p` in test name formatting

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4569]
### What is the problem this feature would solve?

sometimes, we use `it.each` to run the same test suites with different data. When the data is a list of functions, I wish to be able to format them in the test name. Jest supports `%p` for formatting, but Bun does not support it currently.

Example code

```JavaScript
function A() { }

describe("test", () => {
  it.each([A])("test %p", async f => {
    f();
  });
});

```

Expect

```
✓ test > test [Function A] [0.07ms]
```

Bun

```
✓ test > test p [0.07ms]
```

### What is the feature you are proposing to solve the problem?

Use the `%p`. See https://jestjs.io/docs/api#1-describeeachtablename-fn-timeout

**Comment by Electroid** [comment]
I implemented this, but it looks like your commit might be better.
