### ISSUE TITLE
Supporting using packages in tsconfig.json (`extends`)

### ISSUE THREAD

**Issue by mvantellingen** [oven-sh/bun#4572]
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

In a mono repo setup I have the following tsconfig.json in an app:

```
{
  "extends": "@monorepo-shared/config/tsconfig/backend.json",
  "compilerOptions": {
    "paths": {
      "~src/*": ["./src/*"]
    }
  },
 "include": ["./src", "*.ts", "*.js", "*.cjs"]
}
```

The `@monorepo-shared` is a package in my monorepo setup which contains some shared configuration. When changing the package name to a relative path (e.g. `../../packages/config/tsconfig/backend.json` everything works fine. But when using the package syntax it isn't resolve the path aliasing.

BTW: really, really awesome to see the progress in Bun

**Comment by mvantellingen** [comment]
This might actually be something that is not working for me in relation to workspaces, need to debug some more

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/issues/4039#issuecomment-1695507174

the package syntax is not being handled; it is being treated as a regular file path and read

**Comment by mvantellingen** [comment]
Ah perfect, i'll close this one
