### ISSUE TITLE
[Cli] `bun create --help` is broken

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4577]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

`bun create --help`

### What is the expected behavior?

Show the flags like 0.8.1

```
>>​ bun create --help
bun create

  flags:
            --force             Overwrite existing files
            --no-install        Don't install node_modules
            --no-git            Don't create a git repository
            --verbose           Too many logs
            --no-package-json   Disable package.json transforms
            --open              On finish, start bun & open in-browser

```

### What do you see instead?

![2023-09-08_21-43](https://github.com/oven-sh/bun/assets/9482395/58383aaf-5fc3-4945-867b-42dc398f71d8)

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/822a00c4d508b54f650933a73ca5f4a3af9a7983/src/cli.zig#L1491-L1509

`positionals` might be `undefined` here when we only pass the `--help`. Trying to fix this.

**Comment by birkskyum** [comment]
`bun create` was removed in favor of functioning similar to `npm create`, so it could be that the cli wasn't updated to fully reflect that change
- #485

**Comment by Hanaasagi** [comment]
Thank you. I find that in version 1.0, "bun create" is actually a wrapper for "bunx create-template-name".

**Comment by Hanaasagi** [comment]
It seems that this problem will be fixed with some `create` cli issue together.
