### ISSUE TITLE
Express `listen` with string port creates unix socket

### ISSUE THREAD

**Issue by silversquirl** [oven-sh/bun#4582]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.14-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

`main.js`:
```js
import express from "express";
const app = express();
app.listen("8080");
```

`package.json`:
```json
{
  "type": "module",
  "dependencies": {
    "express": "latest"
  }
}
```

Then run it:
```sh
$ bun run main.js
```

### What is the expected behavior?

Bun should listen on TCP port `8080`, like Node does.

### What do you see instead?

Bun creates a unix socket in the current working directory, named `8080`

**Comment by Hanaasagi** [comment]
Try `app.listen(8080);`


![2023-09-08_23-52](https://github.com/oven-sh/bun/assets/9482395/22b74606-fb4d-42f8-9dd9-529962f8e388)

Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8446ecfb1b3bc757752a159d4966045f35d435b2/types/express-serve-static-core/index.d.ts#L1210-L1232
