### ISSUE TITLE
'navigator' global does not have property 'platform'

### ISSUE THREAD

**Issue by niemal** [oven-sh/bun#4588]
### What version of Bun is running?

v1.0

### What platform is your computer?

Linux 5.15.0-82-generic x86_64 x86_64

### What steps can reproduce the bug?

`bun --bun next dev` in my nextjs project.

### What is the expected behavior?

Normal runtime execution output with no errors.

### What do you see instead?

```
Watchpack Error (watcher): Error: FileNotFound
- event compiled successfully in 146 ms (1087 modules)
- wait compiling...
- event compiled successfully in 173 ms (272 modules)
- error 181 |     let ErrorType = Error;
182 |     if (serializedErr.name === "PageNotFoundError") {
183 |         ErrorType = _utils.PageNotFoundError;
184 |     }
185 |     const err = new ErrorType(serializedErr.message);
186 |     err.stack = serializedErr.stack;
                                 ^
TypeError: undefined is not an object (evaluating 'navigator.platform.includes')
      at /unitedgpt/node_modules/next/dist/server/render.js:186:30
 ```

### Additional information

Nextjs version if needs be: `"next": "13.4.11",`

**Comment by bconnorwhite** [comment]
Getting the same w/[pdfjs-dist](https://github.com/mozilla/pdfjs-dist/blob/5f07d5a4159bb99eee2f6143d1297f03b45bba58/lib/shared/util.js#L645)
