### ISSUE TITLE
build --compile fails on path.join

### ISSUE THREAD

**Issue by llimllib** [oven-sh/bun#4592]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.49-linuxkit-pr aarch64 unknown

(which is a docker container running inside a mac computer, `Darwin 22.6.0 arm64 arm`)

### What steps can reproduce the bug?

A repro using docker, since that should be easier to reproduce.

```shell
$ docker run --rm --init --ulimit memlock=-1:-1 -ti -v .:/local oven/bun bash
# printf "import path from 'path'; path.join('a', 'b');" > test.ts; \
> bun build --compile test.ts --outfile test --target=node && ./test
  [14ms]  bundle  1 modules
 [574ms] compile  test


error: FileNotFound reading "node:path"
```

That command is building a binary from this `test.ts` and then executing it:

```typescript
import path from 'path';
path.join('a', 'b');
```

It actually does not matter if you include `--target=node` or not, you get the same failure either way.

### What is the expected behavior?

`./test` executes successfully

### What do you see instead?

`error: FileNotFound reading "node:path"`

**Comment by llimllib** [comment]
If you remove `--compile` and execute with `bun`, it works as expected:

```
root@8a6cf5726c6b:/local# bun build test.ts --outfile test && bun ./test

  test  7.74 KB

[20ms] bundle 2 modules
/local
```

**Comment by luckydye** [comment]
I have a similar error. It seems like bun doesn't resolve (for example "node:fs") as modules.
My file (index.js):
`
import fs from "node:fs";
const file = fs.readFileSync("index.js");
console.log(file);
`
Prints: "error: FileNotFound reading "node:fs"" on execution of the executables.

It works fine in v0.8.

**Comment by srsholmes** [comment]
I am also getting the same issue with node:vm. 

It all works fine with the bun command in dev, but when packaged and then running the binary I get a

```
error: FileNotFound reading "node:vm"
```

The bundler is working / binary seems to be created correctly, in that there are no errors when making it.

**Comment by gynet** [comment]
same issue 
error: FileNotFound reading "node:crypto"

**Comment by kevincobain2000** [comment]
same issue here, `bun:1.0`

```
error: FileNotFound reading "node:module"
```

**Comment by mayankchhabra** [comment]
Same issue here with Bun 1.0 when trying to run a compiled binary. 

```
error: FileNotFound reading "node:process"
```

**Comment by matsumoto0912** [comment]
Ah, after upgrading to version 1.0, I also  got this. It's a regression :(

It works in 0.8.1

**Comment by 2coo** [comment]
Same here! but getting error with `node:os`
after running `bun build index.ts --compile --outfile runner && ./runner`
```bash
error: FileNotFound reading "node:os"
```

**Comment by AlexBlokh** [comment]
Having the same issue
```ts
import { writeFileSync } from "node:fs";
writeFileSync("test.txt", "not work")
```

building with
```shell
bun build ./fstest.ts --compile --outfile dist/index
```

and when running I get
```shell
error: FileNotFound reading "node:fs"
```

**Comment by txthinking** [comment]
same with compile npm package https://github.com/oven-sh/bun/issues/4477

**Comment by mayankchhabra** [comment]
Amazing, upgrading to [bun 1.0.1](https://bun.sh/blog/bun-v1.0.1) fixed the issue. Thank you devs!

> fixes a bug importing node: builtins in bun build --compile

**Comment by jnj16180340** [comment]
Just want to say thank you for fixing this so quickly, and Bun is so incredibly more easy to use than other JS build tools runtimes etc.

**Comment by Hanaasagi** [comment]
Tried the latest version, and the issue has been resolved. Thank you.
