### ISSUE TITLE
Bun loads wrong .env variables

### ISSUE THREAD

**Issue by danulqua** [oven-sh/bun#4594]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

According to the [Environment Variables docs](https://bun.sh/docs/cli/run#environment-variables), it looks for a `NODE_ENV` variable in order to decide which file to load, so:

1. Install `cross-env` package
2. Add the following scripts to the `package.json`:
```json
"start": "cross-env NODE_ENV=production bun run index.ts",
"dev": "cross-env NODE_ENV=development bun run --watch index.ts"
```
3. Create `.env.production` and `.env.development` files and fill in any variable with a different value
4. Output the variable using the `console.log`
5. Run these scripts and compare the outputs

### What is the expected behavior?

The output should be different, and variables should be loaded from the correct files: `dev` loads from `.env.development`, `start` loads from `.env.production`.

### What do you see instead?

It outputs the correct names of the environment files to the console, but it actually loads variables from a `.env.development` file when running both scripts.

<img width="650" alt="image" src="https://github.com/oven-sh/bun/assets/38916225/1684b4ae-1359-474e-9d2f-b9c98ee3f8d0">

**Comment by Electroid** [comment]
Thanks, we'll fix this ASAP.

**Comment by salvoravida** [comment]
@Electroid  The issue seems to be related to the fact that bun always loads .env.[NODE_ENV] and the spawn env override.

Here is my test:
-> NODE_ENV=production bunx cross-env NODE_ENV=production bun run env-test.ts
```
[0.01ms] ".env.production"
NODE_ENV :  production
SUPER_USER:  prod
```
NODE_ENV=whatever bunx cross-env NODE_ENV=production bun run env-test.ts 
```
[0.01ms] ".env.production"
NODE_ENV :  production
SUPER_USER:  dev
```

**Comment by salvoravida** [comment]
@dylan-conway  Hi, I see it's a known bug https://github.com/oven-sh/bun/blob/main/src/cli/run_command.zig#L519.

I suggest adding a flag not to load .env files, so we can use that flag in the first bun instance without polluting process.env with a wrong .env.

I think that since process.env has always high priority, there is no way to fix it, as forcing .env.production loading in a nested bun call, could break command line process.env injection.
Example:
NODE_ENV=whatever bunx cross-env NODE_ENV=production SUPER_USER:dev-high-priority bun run env-test.ts

The expected value should be SUPER_USER:dev-high-priority, and not a forced .env.production (prod) or the wrong .env.develpment (dev)

my2c

**Comment by dylan-conway** [comment]
@salvoravida I agree, and this behavior will be present in my pr. We don't need to add a flag because process env variables are loaded before .env files, and the .env files won't clobber existing variables.

**Comment by danulqua** [comment]
@dylan-conway the fix is going to be available on next Bun release, right?

**Comment by dylan-conway** [comment]
> @dylan-conway the fix is going to be available on next Bun release, right?

Yes, it's available in v1.0.1

**Comment by danulqua** [comment]
Already checked that, works like a charm 🔥

**Comment by onionhammer** [comment]
This break something for "bun test"?

```
bun test v1.0.1 (31aec4eb)
[0.01ms] ".env"
```

Bun test now does not load anything but .env

Edit: Ahh, peeking through the commits it looks like it looks at .env.test now but not .env.local or .env.development even if NODE_ENV is specified in the command
