### ISSUE TITLE
bunx command not found

### ISSUE THREAD

**Issue by mkarajohn** [oven-sh/bun#4598]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

* Install bun v1 with `curl -fsSL https://bun.sh/install | bash`
* Open new terminal or reload .bashrc in existing terminal
* Run `bunx` with any argument

### What is the expected behavior?

I would expect `bunx` to exist on the system as per [documentation](https://bun.sh/docs/cli/bunx#:~:text=The%20bunx%20CLI%20will%20be%20auto%2Dinstalled%20when%20you%20install%20bun)

### What do you see instead?

`bunx: command not found`

### Additional information

Hope bun gets traction :crossed_fingers:

**Comment by colinhacks** [comment]
Thanks, we're looking into it.

You can use `bun x` instead in the meantime.

**Comment by mkarajohn** [comment]
@colinhacks Thanks!

btw, are you aware of this? https://github.com/oven-sh/bun/issues/3673 
If so, can you suggest any workaround or is it in your plans to provide built in support? I am trying to evaluate bun for adoption at my org. Thank you

**Comment by Subhasish1993** [comment]
I'm also trying to convince my org to try out bun  ^_^

**Comment by ElisePatrikainen** [comment]
Hi, this is just to let you know that I also have this issue. 

**Bun's version:**
1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983 (the same as @mkarajohn)

**Computer's platform:** 
Linux 6.0.12-76060012-generic x86_64 x86_64

Thank you for building Bun! :fire:

**Comment by mizanmahi** [comment]
Also facing the same issue on WSL on Win11

Bun's version: 1.0.0

**Comment by robisadev** [comment]
I ran `bun completions /my/folder/path ` to fix this issue. `bunx` works now

**Comment by quajodk** [comment]
Add bun after installing to PATH or run this command ```exec /bin/zs``` as indicated at the end of the installation

**Comment by Nabwinsaud** [comment]
What could be the reason of not finding command while typed bunx create-any-stack

**Comment by nhanledev** [comment]
same problem on ubuntu 22.04. `bun x` still works.

**Comment by saremeskandary** [comment]
for ubuntu users you can use this line in your terminal to fix it.

`echo -e '\nalias bunx="bun x"' >> ~/.bashrc && source ~/.bashrc`

**Comment by paperclover** [comment]
the bunx symlink installation issues have been fixed a long time ago. if a clean installation of bun doesn't include bunx (`rm -r ~/.bun` then install again), please open a new issue for this.
