### ISSUE TITLE
All scripts run by bun are terminated with SIGKILL when invoked from fish

### ISSUE THREAD

**Issue by suchipi** [oven-sh/bun#4602]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

- on an arm64 macOS device,
- install fish (I used MacPorts to get it)
- install bun v1.0.0 via `curl -fsSL https://bun.sh/install | bash`
- clone the linked repo, or create executable file `script.js` with content:
  ```
  #!/usr/bin/env bun
  console.log("hi");
  ```
- run `./script.js` or `bun script.js`
- note that the process is terminated with SIGKILL (exit code 137) even though it ran to completion

### What is the expected behavior?

The process exits with status code 0.

### What do you see instead?

The process is terminated with SIGKILL. Sample output:
```
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro> ./script.js
hi
fish: Job 1, './script.js' terminated by signal SIGKILL (Forced quit)
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro [SIGKILL]>
```

### Additional information

I have created a sample repro here: https://github.com/suchipi/bun-fish-sigkill-repro

Fish version 3.6.1

**Comment by Jarred-Sumner** [comment]
This usually means that Bun was not codesigned correctly, which is confusing because it should be happening to everyone if that was the case and we'd have gotten many many more reports of this if so

Is it possible that the version of `bun` in $PATH is not the version of `bun` installed? It would be located in ~/.bun/bin/bun`

**Comment by suchipi** [comment]
Double-checked that it's the correct version:

```
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro (main)> which bun
/Users/suchipi/.bun/bin/bun
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro (main)> bun --version
1.0.0
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro (main)> /Users/suchipi/.bun/bin/bun --version
1.0.0
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro (main)> /Users/suchipi/.bun/bin/bun ./script.js
hi
fish: Job 1, '/Users/suchipi/.bun/bin/bun ./s…' terminated by signal SIGKILL (Forced quit)
suchipi@Ritsuko ~/C/bun-fish-sigkill-repro (main) [SIGKILL]>
```

Also, I'm not able to repro the issue in Ubuntu (which is likely not surprising)

**Comment by suchipi** [comment]
Here's the binary in question if you'd like to inspect it: [bun.zip](https://github.com/oven-sh/bun/files/12562892/bun.zip)

**Comment by suchipi** [comment]
Definitely seems codesigning-related; running `codesign --remove-signature ~/.bun/bin/bun` makes the issue go away. Obviously it's not ideal but I've already given iTerm and VS Code permission to run non-codesigned code, so this is a sufficient workaround for me... at least until I `bun upgrade`.

Excited to use bun! :D Thanks

I'll leave this issue open and revisit in a future release to see if it's still present at that time

**Comment by Electroid** [comment]
If you run into this issue with newer versions of Bun let us know and we'll re-investigate.

**Comment by suchipi** [comment]
Upgraded to bun 1.0.7 and there's no issue anymore :)

**Comment by suchipi** [comment]
Actually, after further testing, the issue is still present. I mistakenly only re-tested stuff like `bun run` and `bun repl`, but this error is specific to running a script with bun (via eg `bun src/index.ts`), which still results in a SIGKILL, even on bun 1.0.7.

Could you re-open this issue? Also, is there any additional info I can provide to help narrow this down? It may be relevant to note that I have System Integrity Protection *disabled* on my Mac:

```
$ csrutil status
System Integrity Protection status: disabled.
```

**Comment by ottodevs** [comment]
I re-experienced the same issue with bun 1.0.20.

It not only affects running scripts, but also commands like `bun add` where being "sigkill'ed"

It got solved by running `codesign --remove-signature $(where bun)`

**Comment by Jarred-Sumner** [comment]
This can happen when Bun was installed without code signing correctly

We manually codesign Bun before releasing it each time

This was likely an environment issue, as many, many more people would report it if it was happening by default

**Comment by NikhilVerma** [comment]
@Jarred-Sumner I am facing the same issue, But it seems to only happen when another bun process is running in the background. This is a sample sequence of commands.

```
>bun dev
$ bun --bun nuxt dev
error: script "dev" was terminated by signal SIGKILL (Forced quit)
fish: Job 1, 'bun dev' terminated by signal SIGKILL (Forced quit)
$ pkill -9 bun
>bun dev
```

This works out for me.

**Comment by NikhilVerma** [comment]
Ok I found the issue, for future reference: Check if your project's package.json files contain "bun" as a dependency. The node scripts were using the `node_modules/.bin/bun` for me which I think was an older version and no signed.

Removing it and forced reinstalling fixed this issue once and for all for me.

cc @Jarred-Sumner maybe bun can check for duplicate installations in node_modules
