### ISSUE TITLE
Running express with .env port doesnt start localhost

### ISSUE THREAD

**Issue by Matzielab** [oven-sh/bun#4605]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

.env
```PORT=3000```

index.ts
```typescript
import express from "express";

const app = express();
const port = process.env.PORT;

app.get("/", (req, res) => {
  res.send("Hello World!");
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});
```

package.json
```json
{
  "name": "bun-express-server",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.18.2"
  },
  "devDependencies": {
    "@types/express": "^4.17.17",
    "bun-types": "^1.0.0",
    "typescript": "^5.2.2"
  }
}
```

ts-config.json (recommended from bun docs)
```json
{
  "compilerOptions": {
    "types": ["bun-types"],

    "lib": ["esnext"],
    "module": "esnext",
    "target": "esnext",

    "moduleResolution": "bundler",
    "noEmit": true,
    "allowImportingTsExtensions": true,
    "moduleDetection": "force",

    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,

    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  }
}
```

run in terminal
`bun index.ts`

see
```
[0.04ms] ".env"
Example app listening on port 3000
```

but localhost can't be connected to

### What is the expected behavior?

server starts at localhost:3000 and displays Hello world on get /

### This site can’t be reached ###
localhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

### Additional information

if `const port = process.env.PORT;` is changed to `const port = 3000;` in index.ts, then it works perfectly

**Comment by buk0vec** [comment]
Successfully reproduced this bug running macOS 12.6 on Intel. Express output and `bun run env` indicates that the PORT variable is set to 3000

**Comment by buk0vec** [comment]
Interesting fix for this case: passing the environment variable within `parseInt` doesn't cause an error. If you pass the string `"3000"` directly into your `listen` call then it refuses to connect, but pass in the number `3000` and it works. When using Node, express accepts strings for port numbers (expected behavior). When using bun, the server refuses to accept requests when using a string as a port number.

**Comment by buk0vec** [comment]
I think I have found the main issue: Bun's implementation of `node:http` **does not accept a string as the port number**. Reproduction index.ts:
```ts
import http from 'node:http'

const port = '3000';

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello, World!\n');
});

server.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
}); 
```
After running `bun index.ts`
Expect `GET /` -> 'Hello World!\n'
Actual `GET /` -> Connection refused

**Comment by Electroid** [comment]
Thanks for reporting, #4620 will fix this and will go out in the next release.

**Comment by namhihi237** [comment]
The same issue.
