### ISSUE TITLE
Mutiple issues in bun plugin

### ISSUE THREAD

**Issue by tr1ckydev** [oven-sh/bun#4607]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.5.1-1-cachyos x86_64 unknown

### What steps can reproduce the bug?

1. Namespace doesnt work
 index.ts
```ts
import {} from "yaml:./ok.yaml";
```
plugin.ts
```ts
Bun.plugin({
    name: "Loader",
    async setup(build) {
        build.onLoad({ namespace: "yaml", filter: /.*/ }, (args) => {
            console.log("success");
            return { exports, loader: "object" };
        });
    },
});
```
`success` is never logged into the console rather an error `Could not resolve: "yaml:./ok.yaml"`.

2. If the above code is reproduced but this time
```ts
import {} from "http://whatever";
// or "https://whatever"
```
In plugin.ts, its changed to `namespace: "http"` or https, then `success` is logged

3. args has no `namespace` property
```ts
build.onLoad({ namespace: "http", filter: /.*/ }, (args) => {
            console.log(args.namespace)
            return { exports, loader: "object" };
        });
```
logs `undefined` instead of `http`

4. Plugins cannot load files with number in the file extension
```ts
import {} from "./ok.yaml.1";
```
plugin.ts
```ts
Bun.plugin({
    name: "Loader",
    async setup(build) {
        build.onLoad({ filter: /\.1$/ }, (args) => {
            console.log("success");
            return { exports, loader: "object" };
        });
    },
});
```
`success` is never logged into the console.

**Comment by Jarred-Sumner** [comment]
please file a separate issue for each one of these so that it can be tracked individually
