### ISSUE TITLE
Add Alpine-based Docker images

### ISSUE THREAD

**Issue by aradalvand** [oven-sh/bun#4611]
Couldn't find an issue specifically about Alpine-based versions for the official Docker image, but let me know if one already exists.

**Comment by zfben** [comment]
I have tried to install bun in alpine with https://github.com/oven-sh/bun/blob/main/dockerhub/Dockerfile-alpine, but it doesn't work.

```bash
 > [stage-1 18/18] RUN bun --version:
0.149 Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37
0.149 Error relocating /usr/local/bin/bun: __memmove_chk: symbol not found
```

**Comment by suchipi** [comment]
related: https://github.com/oven-sh/bun/issues/918

**Comment by melroy89** [comment]
I indeed noticed that `oven/bun:1.0.0` is 100MB compressed for amd64. While `node:lts-alpine3.18` is 51MB compressed for amd64.

I looking forward to see an alpine docker based image, before I migrate my projects to Bun.

**Comment by polarathene** [comment]
> I indeed noticed that `oven/bun:1.0.0` is 100MB compressed for amd64. While `node:lts-alpine3.18` is 51MB compressed for amd64.

It should be 65MB, there was a mistake/bug in the `Dockerfile`: https://github.com/oven-sh/bun/issues/5269

Depending on what the `bun` binary needs, it could possibly use a smaller glibc image (_assuming it needs to link to glibc/musl_), maybe a [distroless variant](https://github.com/GoogleContainerTools/distroless#why-should-i-use-distroless-images).

**EDIT:**
- Distroless is being [discussed here](https://github.com/oven-sh/bun/issues/1567#issuecomment-1465032637).
- A distroless [`Dockerfile` already exists](https://github.com/oven-sh/bun/blob/9d3f60d44ed90bcb581b590067b42d92e7cdecad/dockerhub/Dockerfile-distroless#L62), just no image published yet. It is roughly 40MiB compressed (`docker save local-build | gzip -c | wc -c | numfmt --to iec`).

> I looking forward to see an alpine docker based image

Sometimes Alpine isn't a good choice for very little savings. `musl` can introduce various problems, notably in performance and memory usage, but also in compatibility (_some NPM packages in the past have installed pre-built binaries for "linux" that expected glibc not musl and broke_), and other surprises (_DNS is handled a bit differently, especially when IPv6 lookups are involved IIRC_).

Maybe you don't notice the performance difference, or run into any of the other issues users encounter, but they're sometimes a bit difficult to troubleshoot when you do hit them. The disk savings can be very minor to justify it (_most of the time it's for network transit concern, not disk storage_).

**Comment by aradalvand** [comment]
> The disk savings can be very minor to justify it

Image size is not the only reason one might want to use Alpine-based images (albeit it is the primary one for most people), the `apk` package registry is another big pro.

Nearly all major runtimes and such in all languages provide Alpine-based Docker images, so it would be kind of weird for Bun to not also have them. Leave the actual decision on which image variant to use to the developers, but the option should be there, at least.

**Comment by suchipi** [comment]
Just me, but for what it's worth, the reason I *personally* care about musl support in bun is so that I can use it in *existing* alpine images; images where I compile binaries targeting musl, where I'd like to use bun as a compile-time tool. As a workaround, I could do the bun parts in a separate step in a separate image, but it's fewer moving parts if it's all in one.

**Comment by Electroid** [comment]
We now publish the `oven/bun:alpine` image, as well as `oven/bun:distroless`.
https://bun.sh/docs/installation#docker
https://hub.docker.com/r/oven/bun/tags

**Comment by aradalvand** [comment]
@Electroid Thanks. The Alpine version is apparently still installing glibc instead of using musl though, right? Is Bun not compatible with musl? If so, is there an issue tracking that?

**Comment by suchipi** [comment]
@aradalvand https://github.com/oven-sh/bun/issues/918

**Comment by aradalvand** [comment]
Oh yeah, sorry you had already mentioned that issue [in this comment](https://github.com/oven-sh/bun/issues/4611#issuecomment-1712595862), missed that! Thanks.
