### ISSUE TITLE
Unexpected behavior for `useDefineForClassFields=false`

### ISSUE THREAD

**Issue by JoostK** [oven-sh/bun#4612]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```sh
git clone git@github.com:JoostK/bun-usedefineforclassfields-issue.git
cd bun-usedefineforclassfields-issue
bun test
```

For reference, this is the test that fails:

```ts
class Foo {
  baz = this.bar;
  constructor(private readonly bar: string) {}
}

describe('issue', () => {
  it('works', () => {
    expect(new Foo('test').baz).toEqual('test');
  });
});
```

### What is the expected behavior?

The test succeeds, because `baz` gets assigned after `bar` has been assigned following, following the `useDefineForClassFields` setting in `tsconfig.json`.

### What do you see instead?

The test fails, because `baz` gets assigned before `bar` has been assigned.

Bun's current behavior is according to the ES2022 specification, but TypeScript defaults `useDefineForClassFields` to `false` which models different semantics that predate the ES2022 specification, wherein the assignment of `baz` is moved into the constructor _after_ the `bar` assignment.

### Additional information

[esbuild output](https://esbuild.github.io/try/#YgAwLjE5LjIAewovLyAgdGFyZ2V0OiBbJ2VzMjAyMiddLAp9AGUAZW50cnkudHMAY2xhc3MgRm9vIHsKICBiYXogPSB0aGlzLmJhcjsKICBjb25zdHJ1Y3Rvcihwcml2YXRlIHJlYWRvbmx5IGJhcjogc3RyaW5nKSB7fQp9AAB0c2NvbmZpZy5qc29uAHsiY29tcGlsZXJPcHRpb25zIjogeyJ1c2VEZWZpbmVGb3JDbGFzc0ZpZWxkcyI6IGZhbHNlfX0):

```js
class Foo {
  constructor(bar) {
    this.bar = bar;
    this.baz = this.bar;
  }
}
```

---

[TypeScript output](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oCMwC9oF5oAXACwEsIA6bAJwG51ph4A7CImgV2CPhoAoADjTIA3MEQCm0GpLAATViACeWMDQBc0diJYBzAJQoAvqmNA)

```js
"use strict";
class Foo {
    constructor(bar) {
        this.bar = bar;
        this.baz = this.bar;
    }
}
```

---

bun output (`bun build index.spec.ts`):

```js
class Foo {
  bar;
  baz = this.bar;
  constructor(bar) {
    this.bar = bar;
  }
}
```

**Comment by mattfysh** [comment]
are there any workarounds? currently editing bundle output by hand. are there any build flags I could use, or failing that a codemod to remove any unint'd class fields?

**Comment by JoostK** [comment]
Note that the TypeScript team is considering the deprecation of `useDefineForClassFields=false` (microsoft/TypeScript#60284) to align with ECMAScript behavior going forward.
