### ISSUE TITLE
`node:http` refuses to serve when port is a string

### ISSUE THREAD

**Issue by buk0vec** [oven-sh/bun#4618]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

After running `bun init` in a new directory, replace index.ts with:

```ts
import http from 'node:http'

const port = '3000';

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello, World!\n');
});

server.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
}); 
```

Run `bun index.ts` and then go to `localhost:3000` in a browser window

### What is the expected behavior?

The browser should display the server's response text of "Hello World!\n"

### What do you see instead?

The server refuses the connection from the browser

### Additional information

`node:http` works normally when passing in a number for the port. However, this isn't the required behavior. This also breaks express, which by default uses `node:http` for the `listen` function.

**Comment by Electroid** [comment]
Thanks for reporting, a fix will land in the next release.
