### ISSUE TITLE
Problems attempting to run a Mocha test suite

### ISSUE THREAD

**Issue by robogeek** [oven-sh/bun#462]
I want to evaluate Bun, and I thought to start with the test suite of one of my Node.js packages.  The tests are invoked using Mocha.

As you'll see there are some incompatibilities in the `process` object.  One is an issue which must be handed off to the Yargs team.

Mocha has a command installed - `node_modules/mocha/bin/mocha` that is installed in `node_modules/.bin`.  The script with no extension on the end is not recognised:

```
$ bun run ./node_modules/mocha/bin/mocha test-partials.js test-parse.js test-process.js 
error: Script not found "/home/david/Projects/akasharender/mahabhuta/test/./node_modules/mocha/bin/mocha"
error "mocha" exited with 1 status
```

If I make a copy of `mocha` as `mocha.js` I can execute the script, and then there are several additional failures

```
$ bun run ./node_modules/mocha/bin/mocha.js test-partials.js test-parse.js test-process.js 
986 |     ? Number(process.env.YARGS_MIN_NODE_VERSION)
987 |     : 10;
988 | if (process && process.version) {
989 |     const major = Number(process.version.match(/v([^.]+)/)[1]);
990 |     if (major < minNodeVersion) {
991 |         throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
                  ^
 error: yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
      at /home/david/Projects/akasharender/mahabhuta/test/node_modules/yargs-parser/build/index.cjs:991:14
```

Here it is failing because `process.version` is returning a number other than what Yargs expects.  Yargs is obviously not checking correctly, and Bun is obviously not going to return a Node.js-compliant version number.  So I commented that out so see how farther I could get.

```
$ bun run ./node_modules/mocha/bin/mocha.js test-partials.js test-parse.js test-process.js 
153 |  */
154 | 
155 | function useColors() {
156 | 	return 'colors' in exports.inspectOpts ?
157 | 		Boolean(exports.inspectOpts.colors) :
158 | 		tty.isatty(process.stderr.fd);
                ^
 TypeError: undefined is not an object (evaluating 'process.stderr.fd')
      at useColors (/home/david/Projects/akasharender/mahabhuta/test/node_modules/debug/src/node.js:158:13)
```

Here it's failing looking at `process.stderr.fd` -- commented that out

```
$ bun run ./node_modules/mocha/bin/mocha.js test-partials.js test-parse.js test-process.js 
33 | 
34 | /**
35 |  * Check if both stdio streams are associated with a tty.
36 |  */
37 | 
38 | var isatty = isBrowser || (process.stdout.isTTY && process.stderr.isTTY);
                              ^
 TypeError: undefined is not an object (evaluating 'process.stdout.isTTY')
      at /home/david/Projects/akasharender/mahabhuta/test/node_modules/mocha/lib/reporters/base.js:38:27
```

Ditto at `process.stdout.isTTY` -- at which time I thought to simply report it here.

**Comment by FinnRG** [comment]
@robogeek  Thank you for the provided details.

1. The ```process.version``` issue was recently fixed in #392
2. stdin/stderr/stdin still need to be implemented (https://github.com/Jarred-Sumner/bun/issues/349#issuecomment-1177474028)

If there aren't any more errors, please close this issue.
