### ISSUE TITLE
[Linux ARM64] fs.mkdirSync siliently fails

### ISSUE THREAD

**Issue by Xiot** [oven-sh/bun#4627]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.49-linuxkit-pr aarch64 unknown

### What steps can reproduce the bug?

This was using the `oven/bun` docker image

The setup that I currently have is a little complicated, but the gist of it is that it makes a bunch of folders in quick succession.

This works fine on my M2 laptop

This is mainly debugging code that I added, to try to figure out what is going on.
But the `mkdirp.before` and `mkdirp.after` lines will both show that the folder (`ret`) doesn't exist, even though I attempted to create it twice.  Neither instance throws an `Error` either
```javascript
console.log('mkdirp.before', ret, fs.existsSync(ret))
if (!fs.existsSync(ret)) fs.mkdirSync(ret, {recursive: true})
if (!fs.existsSync(ret)) fs.mkdirSync(ret, {recursive: true})
console.log('mkdirp.after', ret, fs.existsSync(ret))
```

It's a little weirder because I can re-run my script multiple times, and it will always 'fail' at the same place.  If I create the folder manually, my script will continue for a little bit, then start to fail (and continue to fail) at a different place.

### What is the expected behavior?

The folder is either successfully created, or an `Error` is thrown

### What do you see instead?

The call completes, however the directory doesn't actually exist.

### Additional information

This is the basics of the script.
It reads in coverage data, and creates a html report

```javascript
import libReport from 'istanbul-lib-report'
import reports from 'istanbul-reports'
import libCoverage from 'istanbul-lib-coverage'

const coverage = libCoverage.createCoverageMap()
map.merge(coverageJson)

const ctx = libReport.createContext({
  dir: reportPath,
  coverageMap: coverage,
})
reports.create('html', { subdir: 'html' }).execute(ctx)
```

**Comment by Xiot** [comment]
I'm not sure what actually changed, but seems to all work now.  
I re-created the image (for the 20th time) and it now looks like it is working.

Sorry for the noise

**Comment by dlorenc** [comment]
I just ran into this too on Docker (on an M2 mac)

**Comment by Whobeu** [comment]
I found what may be a related issue. For use with Node.js, I wrap mkdirSync in a try/catch block since it will throw an error if the directory already exists. In Bun, no such error is thrown. The unmodified code still works as expected in Node.js with the catch block catching the failure.

**Comment by Xiot** [comment]
In my case, the directory didn't exist, and it didn't give any indication that it wasn't able to create the directory

**Comment by Whobeu** [comment]
> In my case, the directory didn't exist, and it didn't give any indication that it wasn't able to create the directory

It looks like mkdirSync (and possibly related functions) is not throwing exceptions when it should and silently failing. In my case of the directory already existing, it is just something of note when I throw a message that a directory was successfully created when it already existed (I was just lazy by not calling existsSync to check for the pre-existence - easy just to let the unconditional call fail). In the case of not being able to create a needed directory, it is a serious problem.

**Comment by joshuamanns** [comment]
This is also failing (silently) for me when attempting recursively create directories. In `bun repl`:
```ts
import { mkdirSync } from "fs";
mkdirSync('foo'); // OK
mkdirSync('foo/bar', {recursive: true}); // OK
mkdirSync('foo/bar/baz/qux', {recursive: true}); // FAILS SILENTLY
```

**Comment by Whobeu** [comment]
Just tested with 1.0.1 and still fails. Bug report should update the version to 1.0.1 from 1.0.0.

**Comment by seanwessmith** [comment]
@Xiot how do you debug Bun? I have a silently failing axios script and the debugger doesn't seem to step in to the bun files.

**Comment by Xiot** [comment]
> @Xiot how do you debug Bun? I have a silently failing axios script and the debugger doesn't seem to step in to the bun files.
>  

I debugged it the same way that I debug node. 

```javascript
console.log('stuff')
```

**Comment by seanwessmith** [comment]
thanks for the reply. I did that but it doesn't help with the silent fails. I ended up switching from axios to fetch and that solved issues for now

**Comment by truongan07** [comment]
Bun.sh has any natively method to create directory ?

**Comment by seanwessmith** [comment]
> Bun.sh has any natively method to create directory ?

yea, Bun.file() and Bun.write() https://bun.sh/docs/api/file-io#reading-files-bun-file

**Comment by truongan07** [comment]
Bun.file() and Bun.write()  don't work with no exist directory in path. Ex: `` `./directory/${uuid}/db.sqlite3` `` and uuid is no exist directory before

**Comment by jumoog** [comment]
Works in `1.0.3`

```ts
import fs from 'node:fs'

fs.mkdirSync('/home/a/b/C', {recursive: true});
```

**Comment by alecdwm** [comment]
Not working in `1.0.3`

```ts
// contents of /workspaces/test/test.ts

import fs from 'node:fs'
fs.mkdirSync('/workspaces/test/a/b/c', { recursive: true })
```

```bash
$ pwd
/workspaces/test

$ ls -1
test.ts

$ bun run test.ts

$ ls -1
test.ts

$ bun --version
1.0.3

$ uname -a
Linux 1f945b3d4042 6.4.16-orbstack-00105-g14094bfeec09 #1 SMP Mon Sep 18 21:45:38 UTC 2023 aarch64 GNU/Linux
```

**Comment by Jarred-Sumner** [comment]
I suspect this is an issue specific to Linux arm64. We probably need to not use the Linux system-call interface on arm64 Linux because Zig's bindings for it are less stable than libc.

**Comment by jumoog** [comment]
> I suspect this is an issue specific to Linux arm64. We probably need to not use the Linux system-call interface on arm64 Linux because Zig's bindings for it are less stable than libc.

Yes Arm64 doesn't work. I tested it again with an ARM CPU.

**Comment by Whobeu** [comment]
> > I suspect this is an issue specific to Linux arm64. We probably need to not use the Linux system-call interface on arm64 Linux because Zig's bindings for it are less stable than libc.
> 
> Yes Arm64 doesn't work

That would explain it in my case. While I am using both arm64 and armhf for projects, I have only been working with Bun on arm64 as those systems are more robust than the older armhf platforms.

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/6942
