### ISSUE TITLE
Why does `Bun.build` not work in node runtime?

### ISSUE THREAD

**Issue by Dunqing** [oven-sh/bun#4631]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

<img width="994" alt="image" src="https://github.com/oven-sh/bun/assets/29533304/68333c04-c98a-4e4e-838a-0a922660b31c">

### What is the expected behavior?

Work

**Comment by Electroid** [comment]
`Bun.build` is an API that must be run in `bun`, that is because it is implemented in native code. It cannot be run in `node`.
