### ISSUE TITLE
`bun update` completely reformats package.json

### ISSUE THREAD

**Issue by jakebailey** [oven-sh/bun#4634]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run `bun update` in a repo with a 4-space indented `package.json` (I did it on TypeScript's package.json).

### What is the expected behavior?

Nothing is reformatted; deps are updated (or not).

### What do you see instead?

`package.json` is entirely reformatted, even when no deps changed.

**Comment by divmgl** [comment]
Duplicates: 
https://github.com/oven-sh/bun/issues/4563
https://github.com/oven-sh/bun/issues/3107

**Comment by jakebailey** [comment]
Oops, I apparently did not use the right search terms.
