### ISSUE TITLE
How to get IP Address from Request?

### ISSUE THREAD

**Issue by JawadAhbab** [oven-sh/bun#4640]
### What is the problem this feature would solve?

```ts
const server = Bun.serve({
  port: 3000,
  fetch(req) {
    // IP Address
    return new Response("Welcome to Bun!");
  },
});
```

### What is the feature you are proposing to solve the problem?

Could not find any way to get the IP Address of the client from the `req`. I think it should be provided!

**Comment by Hanaasagi** [comment]
I think your are looking for this feature https://github.com/oven-sh/bun/pull/4559

**Comment by simylein** [comment]
Can you close this as it is a duplicate of #3540?

**Comment by JawadAhbab** [comment]
Duplicate of #3540
