### ISSUE TITLE
Fastify "Is port ... in use?"

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#4651]
### What steps can reproduce the bug?

```
import { fastify } from 'fastify';

const server = fastify({ logger: true });
await server.listen({ port: 3000 });
```

**Comment by divmgl** [comment]
+1, also having this problem when using the `--watch` parameter.

**Comment by sirenkovladd** [comment]
That should fix it
https://github.com/oven-sh/bun/issues/4358

**Comment by multiwebinc** [comment]
I was having this error too. To make it work, you need to provide a `host` option to `fastify.listen`:

```typescript
await fastify.listen({ port: 3000, host: '0.0.0.0' });
```
