### ISSUE TITLE
console.log code is executing 4 times inside bun server's fetch method

### ISSUE THREAD

**Issue by santoshbadal1111** [oven-sh/bun#4657]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

const server = Bun.serve({
  fetch() {
    console.log('Hello');
    return new Response('Bun!!');
  },
  port: 3000,
});

When i run above code using bun run index.ts
output in terminal is 
Hello
Hello
Hello
Hello

### What is the expected behavior?

It should show Hello only one time when url is requested from browser i.e http://localhost:3000/
Hello

### What do you see instead?

When i run above code using bun run index.ts
output in terminal is 
Hello
Hello
Hello
Hello

**Comment by jakeg** [comment]
Are these requests for favicon.ico etc maybe?

**Comment by sirenkovladd** [comment]
I only have one "Hello" per request.

You can check the url with
```js
const server = Bun.serve({
  fetch(req) {
  console.log('Hello', req.url);
    return new Response('Bun!!');
  },
  port: 3000,
});
```

What browser are you using?

**Comment by Electroid** [comment]
This is likely from your browser asking for various URLs like `favicon.ico`. To confirm, add `console.log(req.url)`.
