### ISSUE TITLE
Bun Init, cli command to init git repo

### ISSUE THREAD

**Issue by KoesterJannik** [oven-sh/bun#4659]
### What is the problem this feature would solve?

You would instantly have your project under version control. The gitignore file is already generated by the cli, so I guess it was just missed

### What is the feature you are proposing to solve the problem?

Immediatly have version control

### What alternatives have you considered?

Doing it manually with git init

**Comment by Electroid** [comment]
If I understand the suggestion correctly, you'd like `bun init` to also initialize a `.git` repository. While this is something we could do, it's also easy enough to run `git init`, and you won't want a `.git` repository everytime you run it.
