### ISSUE TITLE
WSL terminal freezing using `bun create` or `bunx`

### ISSUE THREAD

**Issue by KirillTregubov** [oven-sh/bun#4664]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

Windows version: KB5029263

### What steps can reproduce the bug?

1. Run `bunx create-next-app`
2. Skip naming project (press enter)
3. Try to choose TypeScript (press enter)

OR

1. Run `bun create vite`
2. Skip naming project (press enter)
3. Try to select Vanilla (press enter)

### What is the expected behavior?

(tested with npx/npm, assume bun output is the same)

```
bunx create-next-app
√ What is your project named? … my-app
√ Would you like to use TypeScript? ... No / Yes
? Would you like to use ESLint? » No / Yes
```

OR

```
bun create vite
√ Project name: ... vite-project
√ Select a framework: » Vanilla
? Select a variant: » - Use arrow-keys. Return to submit.
>   TypeScript
    JavaScript
```

### What do you see instead?

```
bunx create-next-app
✔ What is your project named? … my-app
? Would you like to use TypeScript? › No / Yes
```

OR

```
bun create vite
✔ Project name: … vite-project
? Select a framework: › - Use arrow-keys. Return to submit.
❯   Vanilla
    Vue
    React
    Preact
    Lit
    Svelte
    Solid
    Qwik
    Others
```

### Additional information

It seems like interactive CLI prompts make my WSL terminal unresponsive when running scripts using `bunx` or `bun create` as opposed to their npx/npm counterparts. The unresponsiveness can be characterized as inability to use input keys (arrows, enter) or exit keys (Ctrl+C). Most notably text prompts work perfectly fine (the first inputs in these scripts).

This seems to be specific to WSL, but I did not test on Linux (tested working on Mac). #4646 seems to have the same issue.

**Comment by tranlehaiquan** [comment]
For me, I'm create vite it's okay, follow this guide https://bun.sh/guides/ecosystem/vite


<img width="721" alt="image" src="https://github.com/oven-sh/bun/assets/17347993/547bc4b7-7449-4b22-a342-50fe4c83477b">

**Comment by KirillTregubov** [comment]
> For me, I'm create vite it's okay <img alt="image" width="721" src="https://user-images.githubusercontent.com/17347993/266767028-547bc4b7-7449-4b22-a342-50fe4c83477b.png">

Just tested, can confirm it works on my Mac as well. Doesn't work in WSL though.

**Comment by NicoAvanzDev** [comment]
Figured out the same issue here, tested with WSL and Kali 

![image](https://github.com/oven-sh/bun/assets/35104310/32bab267-8991-49d2-9baf-865ebdcc4a21)

bun v1.0

**Comment by ksjitendra18** [comment]
Same issue in Bun 1.0 and Windows 11 and WSL (Ubuntu 22.04)

![image](https://github.com/oven-sh/bun/assets/88942257/6c7face6-79e4-4166-a783-5484fe0ea5f2)

**Comment by JotunnPy** [comment]
Same issue using `bunx create-next-app` it freezes on the second question.
Windows 11 (WSL, Ubuntu)
![image](https://github.com/oven-sh/bun/assets/106374742/d25bdc1a-74ab-448e-a62d-087d16fa0cff)

**Comment by seccentral** [comment]
can confirm on debian 12 and ubuntu 22 locally or remotely via ssh

**Comment by codebyjon** [comment]
Confirmed as well with Win10, WSL2, Ubuntu v22.

Having this issue across two PC's. Tried reformatting my laptop and reinstalling only WSL + Ubuntu to ensure there was no issues with it reaching to `node`.

Oddly enough, `bunx create-svelte test-app` will work, but `bunx create-svelte` followed by entering the app name does not. `bun create svelte` also hangs.

Though, on my work PC, `bunx create-svelte test-app` will allow me to initialize the new app, but `bun --bun run dev` and `bun dev` both result in a very similar hang after echoing `vite dev`.

Other frameworks like `bunx create-next-app` and `bunx create-astro` hang as well, irrelevant of whether the project name is supplied as an arg.

EDIT: Just installed `Arch WSL` to ensure it wasn't the distro and am having the same problems.

**Comment by ericklarsen** [comment]
Got the same issue here, I tried to create my nextjs app using this command `bunx create-next-app` and it freezes on the second option too.
![image](https://github.com/oven-sh/bun/assets/32609329/27bbf3f6-cc03-4361-a437-adfebd669c51)

But funny thing is, it works fine when I created svelkit project using bunx command.

**Comment by sonyarianto** [comment]
maybe related to prompts package? I do like this on my WSL

clone the prompts package and go to the directory

do:

bun example.js (hang on second question)
node example.js (success and smooth)

**Comment by ericklarsen** [comment]
> maybe related to prompts package? I do like this on my WSL
> 
> clone the prompts package and go to the directory
> 
> do:
> 
> bun example.js (hang on second question) node example.js (success and smooth)

I have tried it, and it happened the same thing.

**Comment by ericklarsen** [comment]
Got an idea from @sonyarianto , try to create you nextjs app by using this command (non-interactively) `bunx create-next-app <your-project-name> --ts --tailwind --eslint --app --src-dir --use-bun --import-alias "@/*"` for more details, you can find it here [https://nextjs.org/docs/pages/api-reference/create-next-app#non-interactive](url) 

 it fixed my problem.

**Comment by sonyarianto** [comment]
@ericklarsen glad you can solved it, non-interactive to the rescue jaiwakwkakawk

**Comment by devfakhzan** [comment]
> @ericklarsen glad you can solved it, non-interactive to the rescue jaiwakwkakawk

Well, what about other frameworks like Vite for example?

**Comment by sonyarianto** [comment]
@devfakhzan maybe you can try using non-interactive option during create Vite https://github.com/vitejs/vite/tree/main/packages/create-vite

**Comment by kopparam** [comment]
Able to reproduce on Ubuntu 22.04.3, amd64.

**Comment by Thiru-Malai** [comment]
Same issue. Terminal freezes when `bun create remix`

System: Windows 11

Running using WSL Remotely in VS Code

![image](https://github.com/oven-sh/bun/assets/73980589/19d67c5f-db38-42f0-9eac-0ed6e8ec47f4)

**Comment by PeterSenpai** [comment]
Same issue.

Command: `bunx create-next-app` in terminal

System: Windows 10 WSL Ubuntu 22

**Comment by Elbert-Ainstein** [comment]
just have to manually write all the arguments for creating apps :O

**Comment by JotunnPy** [comment]
Same problem is also encountered when doing `bunx prisma init`

**Comment by aduarterengifo** [comment]
same problem 

```
bun x create-next-app
```

on wsl

*non-interactive version works fine

**Comment by hambergerpls** [comment]
I have the same issue with `bunx create-next-app`. Freezes on second question.

It turns out that this issue arises when **node is not installed.**

You can verify this by trying it again when node is installed vs not installed. (I'm using nvm)

I'm using WSL Ubuntu 22.04.2 LTS

Apparently, other tools are broken as well when only bun is installed and not node. e.g. `bun x vercel build`

**Comment by patbhakta** [comment]
Same issue Win11 - WSL2/Ubuntu 22.04 - Node 18.16.3

bunx create-next-app@latest buntest
✔ Would you like to use TypeScript? … No / **Yes**
? Would you like to use ESLint? › No / **Yes**

bunx create-next-app@latest buntest --ts --eslint --tailwind
✔ Would you like to use `src/` directory? … **No** / Yes
? Would you like to use App Router? (recommended) › No / **Yes**

using strictly CLI s a workaround
bunx create-next-app@latest buntest --ts --tailwind --eslint --app --src-dir --use-bun --import-alias a

sudo apt-get install nodejs also fixes it

**Comment by rraeen** [comment]
use this command
 bun x create-next-app <your-project-name> --ts --tailwind --eslint --app --src-dir --use-bun --import-alias "@/*"

its working for me

**Comment by artenlf** [comment]
Finally managed to run "bun create vite" command on my WSL 2. Some hints:

Make sure you have installed the latest versions of the following:

1. Git (v. 2.42.0) (kudos to @iliareshetov )
2. Node.js LTS (V18.17.1) (kudos to @hambergerpls and @patbhakta )

I think Vite template still uses some of the Node modules so this is the only way. 
I'm not an expert, so be kind with your messenger, okay?

**Comment by Tobvl** [comment]
> ### What version of Bun is running?
> 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983
> 
> ### What platform is your computer?
> Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64
> 
> Windows version: KB5029263
> 
> ### What steps can reproduce the bug?
> 1. Run `bunx create-next-app`
> 2. Skip naming project (press enter)
> 3. Try to choose TypeScript (press enter)
> 
> OR
> 
> 1. Run `bun create vite`
> 2. Skip naming project (press enter)
> 3. Try to select Vanilla (press enter)
> 
> ### What is the expected behavior?
> (tested with npx/npm, assume bun output is the same)
> 
> ```
> bunx create-next-app
> √ What is your project named? … my-app
> √ Would you like to use TypeScript? ... No / Yes
> ? Would you like to use ESLint? » No / Yes
> ```
> 
> OR
> 
> ```
> bun create vite
> √ Project name: ... vite-project
> √ Select a framework: » Vanilla
> ? Select a variant: » - Use arrow-keys. Return to submit.
> >   TypeScript
>     JavaScript
> ```
> 
> ### What do you see instead?
> ```
> bunx create-next-app
> ✔ What is your project named? … my-app
> ? Would you like to use TypeScript? › No / Yes
> ```
> 
> OR
> 
> ```
> bun create vite
> ✔ Project name: … vite-project
> ? Select a framework: › - Use arrow-keys. Return to submit.
> ❯   Vanilla
>     Vue
>     React
>     Preact
>     Lit
>     Svelte
>     Solid
>     Qwik
>     Others
> ```
> 
> ### Additional information
> It seems like interactive CLI prompts make my WSL terminal unresponsive when running scripts using `bunx` or `bun create` as opposed to their npx/npm counterparts. The unresponsiveness can be characterized as inability to use input keys (arrows, enter) or exit keys (Ctrl+C). Most notably text prompts work perfectly fine (the first inputs in these scripts).
> 
> This seems to be specific to WSL, but I did not test on Linux (tested working on Mac). #4646 seems to have the same issue.

Having the same issue 
Ubuntu 22.04 freshly installed using Microsoft's WSL installation guide
Freezes when selecting a variant
<img width="239" alt="Captura de pantalla 2023-09-12 025844" src="https://github.com/oven-sh/bun/assets/66923698/ac413006-8570-4a31-aec6-1cc161f3c75b">

**Comment by vmxt** [comment]
The same thing. not working on wsl. (debian) I got up in this section only because the runtime's behavior was hung.

```
: bun create vite
✔ Project name: … vite-project
? Select a framework: › - Use arrow-keys. Return to submit.
❯   Vanilla
    Vue
    React
    Preact
    Lit
    Svelte
    Solid
    Qwik
    Others
```

**Comment by ShimiShimson** [comment]
Confirmed on win10 wsl ubuntu

**Comment by theebestzz** [comment]
~/next-js$ bun
Bun: a fast JavaScript runtime, package manager, bundler and test runner. (1.0.1)

  run       ./my-script.ts       Run JavaScript with Bun, a package.json script, or a bin
  test                           Run unit tests with Bun
  x         next                 Install and execute a package bin (bunx)
  repl                           Start a REPL session with Bun

  init                           Start an empty Bun project from a blank template
  create    next-app             Create a new project from a template (bun c)

  install                        Install dependencies for a package.json (bun i)
  add       hono                 Add a dependency to package.json (bun a)
  remove    moment               Remove a dependency from package.json (bun rm)
  update    react                Update outdated dependencies & save to package.json
  link                           Link an npm package globally
  unlink                         Globally unlink an npm package
  pm                             More commands for managing packages

  build     ./a.ts ./b.jsx       Bundle TypeScript & JavaScript into a single file

  upgrade                        Get the latest version of Bun
  bun --help                     Show all supported flags and commands

  Learn more about Bun:          https://bun.sh/docs
  Join our Discord community:    https://bun.sh/discord

~/next-js$ bun create next-app
/mnt/c/Users/femin/AppData/Roaming/npm/node_modules/node/bin/node: 1: This: not found
error: "create-next-app" exited with code 127


AppData/Roaming/npm/node_modules/node/bin/node: 1: This: not found
error: "create-next-app" exited with code 127


I get a direct error

Windows 10 -  wsl

**Comment by Virtute90** [comment]
For Vitejs, using scafolding works correct on Ubuntu server 22.04 on VM

![image](https://github.com/oven-sh/bun/assets/32056724/28240a68-df04-4852-9836-60e4cd48375a)


https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by vmxt** [comment]
> For Vitejs, using scafolding works correct on Ubuntu server 22.04 on VM
> 
> ![image](https://user-images.githubusercontent.com/32056724/267590617-28240a68-df04-4852-9836-60e4cd48375a.png)
> 
> https://vitejs.dev/guide/#scaffolding-your-first-vite-project

Yea, this one works but, by using pnpm it doesn't work.

**Comment by MaKTaiL** [comment]
I fixed this by installing Node inside the WSL environment. Don't ask me how this is related to Bun, but it worked!

![image](https://github.com/oven-sh/bun/assets/5403043/fb704d22-69cd-40da-a853-bd733bba6426)

**Comment by JohnC0de** [comment]
Woks here, unsing win 11 LTS, with WSL2 Ubuntu 22.04.3 LTS, using NVM to install latest node(v20.6.1), bun 1.0.1!

![image](https://github.com/oven-sh/bun/assets/88864312/888d3859-4bd7-446b-9f7f-62a3c063d78d)
![image](https://github.com/oven-sh/bun/assets/88864312/0f331d7b-aecb-483f-a733-72b04db99b3c)

It seems like when using commands such as `bun create vite` or the equivalent for `next`, the process might be relying on the Node engine to generate the template. If Node/npm isn't properly installed or configured in win/wsl, this could potentially lead to issues. Additionally, I've noticed that when trying to run `bunx --bun create-vite` to possibly utilize the `bun` engine during template creation on my machine, there seems to happen the same issu, it freezes.

**Comment by executionreverted** [comment]
i could create svelte project after installing node js 18.x and git , 

but hot reload does not work.

**Comment by sonyarianto** [comment]
WOW, the latest version v1.0.2 seems to solved this problem (at least on my machine).

**Comment by ohthepain** [comment]
`bun upgrade` to 1.0.2 and you should be good to go. The `react` template has been deprecated but it will walk you through the new template.

**Comment by KirillTregubov** [comment]
Can confirm that `bun upgrade` to 1.0.2 resolves the issues. Thanks to everyone who contributed their input and experiences! I will be closing this.

**Comment by emircanerkul** [comment]
@KirillTregubov  I'm using the latest one and I'm using the ubuntu container, had the same problem. Can't continue

<img width="525" alt="image" src="https://github.com/oven-sh/bun/assets/11430795/804528da-f2f8-4edd-8088-fcb9b89c12fd">

**Comment by MaKTaiL** [comment]
> @KirillTregubov I'm using the latest one and I'm using the ubuntu container, had the same problem. Can't continue
> 
> <img alt="image" width="525" src="https://user-images.githubusercontent.com/11430795/271477420-804528da-f2f8-4edd-8088-fcb9b89c12fd.png">

Use nvm to install node in the Ubuntu container and give it another try.

**Comment by emircanerkul** [comment]
@MaKTaiL thank you, it is solved via installing nvm and node.

**Comment by Levent0z** [comment]
I believe this has something to do with bun and/or inquirer. My code works well when building with bun using `--target=node` and running the outfile with Node. When I build with bun and `--target=bun` and then run with bun, it freezes after a few prompts. 

macOS 13.6, node 18.7.1, bun 1.0.5, inquirer 9.2.11

**Comment by Levent0z** [comment]
Added repro on https://github.com/oven-sh/bun/issues/6323

**Comment by pablodz** [comment]
> Same issue using `bunx create-next-app` it freezes on the second question. Windows 11 (WSL, Ubuntu) ![image](https://private-user-images.githubusercontent.com/106374742/266786554-d25bdc1a-74ab-448e-a62d-087d16fa0cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzUyMDAsIm5iZiI6MTcwMTIzNDkwMCwicGF0aCI6Ii8xMDYzNzQ3NDIvMjY2Nzg2NTU0LWQyNWJkYzFhLTc0YWItNDQ4ZS1hNjJkLTA4N2QxNmZhMGNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNTE1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDdlYTg5OWQzMjJkODlmYWU1ZTI1YTdmOWZmMWQxYzk0NGRhODI1NWNhOTQ0MmE2NzE5MDVlN2M3MjZmOTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Eu9t7LoTJO8dxH1rwr2CCelIna34qqrUNnNspsD2Kls)

same happening now to me, even on linux native, I don't have installed npm or nodejs

**Comment by cmd8** [comment]
Same happening to me:
`node -v`: `v18.19.0` or `v20.10.0`
`bun -v`: `1.0.15`

stuck on 2nd question while installing next.js in bun monorepo packages: [screen recording.webm](https://github.com/oven-sh/bun/assets/13213650/1b872b16-bd66-4285-97cb-706e0ee3f25b)

**Comment by pablodz** [comment]
Fixed using this command

```bash
# bun
bunx create-vite my-vue-app --template vue
```

from docs https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by giroberto** [comment]
```
$ bun create vite test-app
? Select a framework:
 › - Use arrow-keys. Return to submit.
❯ Vanilla
   Vue
   React
   Preact
```

Here it's as simple as that, if I have node installed on linux, I can select the options with the arrow keys and the enter key, and if I don't have node the command crashes and I can't even close it with CTRL+C.

**Comment by jjwallace** [comment]
![image](https://github.com/oven-sh/bun/assets/4450959/5664d772-5456-4bf2-bcfd-3142cc941880)

**Stuck,**
Node 20.10.0
bun 1.0.15
npm 10.2.3

ubuntu

**Comment by Jarred-Sumner** [comment]
> ![image](https://private-user-images.githubusercontent.com/4450959/291568207-5664d772-5456-4bf2-bcfd-3142cc941880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODY3MzAsIm5iZiI6MTcwMjk4NjQzMCwicGF0aCI6Ii80NDUwOTU5LzI5MTU2ODIwNy01NjY0ZDc3Mi01NDU2LTRiZjItYmNmZC0zMTQyY2M5NDE4ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTE0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFkNjE4M2Y5MmYwZDA3YWM5NjU5MmZmOTAyMDExYjUwYTkyYjFhNWY0MmJkYzk2YzRhZGViYjIwZDQ3NDgxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nBNk6SasCS1vnTK2znVczF0SGGTYubhzwoOLylps664)
> 
> **Stuck,** Node 20.10.0 bun 1.0.15 npm 10.2.3
> 
> ubuntu

@jjwallace please upgrade to Bun v1.0.18 by running `bun upgrade`

**Comment by giroberto** [comment]
> > ![image](https://private-user-images.githubusercontent.com/4450959/291568207-5664d772-5456-4bf2-bcfd-3142cc941880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODY3MzAsIm5iZiI6MTcwMjk4NjQzMCwicGF0aCI6Ii80NDUwOTU5LzI5MTU2ODIwNy01NjY0ZDc3Mi01NDU2LTRiZjItYmNmZC0zMTQyY2M5NDE4ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTE0NzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFkNjE4M2Y5MmYwZDA3YWM5NjU5MmZmOTAyMDExYjUwYTkyYjFhNWY0MmJkYzk2YzRhZGViYjIwZDQ3NDgxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nBNk6SasCS1vnTK2znVczF0SGGTYubhzwoOLylps664)
> > **Stuck,** Node 20.10.0 bun 1.0.15 npm 10.2.3
> > ubuntu
> 
> @jjwallace please upgrade to Bun v1.0.18 by running `bun upgrade`

I tested it again and now it's working. Node no longer needs to be installed on wsl.
