### ISSUE TITLE
error: package "@mui/x-tree-view" with tag "https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view" not found, but package exists

### ISSUE THREAD

**Issue by julianklumpers** [oven-sh/bun#4666]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

In a project with `@mui/lab` previously installed with Yarn or NPM. Remove node_modules and yarn.lock file then run `bun install`

### What is the expected behavior?

Packages will be installed correctly without errors

### What do you see instead?

bun install v1.0.0 (822a00c4)

error: package "@mui/x-tree-view" with tag "https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view" not found, but package exists

**Comment by suparthghimire** [comment]
Had same issue with package @mui/x-tree-view. Issue #4725

**Comment by tristonarmstrong** [comment]
There may be a better title for this issue ticket.. It seems to be an issue with the @mui/x-tree-view specifically within the @mui/lab package file which is instead of using a version, its specifically grabbing from a commit.. Maybe bun is having a hard time with that? because that link does resolve. Yet what that error is saying is: "I cant find that package version you have in your package file" referring to that link. You can  validate this issue by:

-> copy @mui/lab folder from node_modules to root dir of project
-> change package.json in @mui/lab folder, updating @mui/x-tree-view version from "link" to "latest"
-> change package.json in root, updating @mui/lab version to "./lab"
-> run bun install - should work
(then you can install @mui/x-tree-view directly and see it installs fine)

not a solution, but those are the steps that helped me identify what the problem was

**Comment by Jarred-Sumner** [comment]
The bug is that we are expecting a tarball URL to include `.tar.gz` or `.tgz` at the end, but this URL has no file extension and so we assume it is an npm tag. It looks like we should treat all URLs as tarball URLs instead of only URLs which end with .tgz or .tar.gz

**Comment by bharghav-raman** [comment]
Facing the same issue with    "@mui/lab": "^5.0.0-alpha.59". Any fixes?

**Comment by Semigradsky** [comment]
I have the same issue in yarn:
```
> yarn install
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @mui/x-tree-view@https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view isn't supported by any available resolver
```

**Comment by Semigradsky** [comment]
The solution is downgrading `@mui/lab` to `5.0.0-alpha.142`.
https://github.com/mui/material-ui/issues/38819

**Comment by chunkangwong** [comment]
> The solution is downgrading `@mui/lab` to `5.0.0-alpha.142`. [mui/material-ui#38819](https://github.com/mui/material-ui/issues/38819)

I tested this myself and it worked! The version previously installed in my `package-lock.json` was `5.0.0-alpha.132`. After specifying the version as `5.0.0-alpha.142` in `package.json`, `bun install` successfully installed dependecies.

**Comment by ayaroslav** [comment]
> > The solution is downgrading `@mui/lab` to `5.0.0-alpha.142`. [mui/material-ui#38819](https://github.com/mui/material-ui/issues/38819)
> 
> I tested this myself and it worked! The version previously installed in my `package-lock.json` was `5.0.0-alpha.132`. After specifying the version as `5.0.0-alpha.142` in `package.json`, `bun install` successfully installed dependecies.

Now working on @mui/lab 5.0.0-alpha.142 for me.

**Comment by enavarrocu** [comment]
It is not working for me on @mui/lab 5.0.0-alpha.142. Is there anything I need to check to make it work?

**Comment by cbsmith402** [comment]
> It is not working for me on @mui/lab 5.0.0-alpha.142. Is there anything I need to check to make it work?

Fwiw, I had to set the version to *exactly* 5.0.0-alpha.142 (not `^5.0.0-alpha.142`) for it to work for me.

**Comment by bykof** [comment]
> It is not working for me on @mui/lab 5.0.0-alpha.142. Is there anything I need to check to make it work?

`bun add @mui/lab@5.0.0-alpha.142`

**Comment by bharghav-raman** [comment]
I was previously using `@mui/lab 5.0.0-alpha.59` but after updating to `@mui/lab 5.0.0-alpha.142`, the date range picker seems to return null i think? Anyone has any idea on what the issue might be?


```jsx
import DateRangePicker from "@mui/lab/DateRangePicker"
import LocalizationProvider from "@mui/lab/LocalizationProvider";
import AdapterDateFns from "@mui/lab/AdapterDateFns";


<LocalizationProvider dateAdapter={AdapterDateFns}>
            <DateRangePicker
                startText="From"
                endText="To"
                PopperProps={{ ref: isDateCalOpen }}
                value={persistedFilters[filter.filterName]}
                onChange={(newValue, keyboardInputValue) => {
                    const parsedValue = newValue.map((date, index) =>
                        isValidDate(date) ? date : null
                    );

                    if (
                        keyboardInputValue &&
                        !isValidDate(new Date(keyboardInputValue)) &&
                        Array.isArray(parsedValue)
                    ) {
                        return;
                    }

                    onFiltersChange(filter?.filterName, parsedValue, null, filter);
                }}
                renderInput={(startProps, endProps) => (
                    <>
                        <TextField {...startProps} error={false} />
                        <Box sx={{ mx: 2 }}> to </Box>
                        <TextField {...endProps} error={false} />
                    </>
                )}
                inputFormat="yyyy-MM-dd"
            />
        </LocalizationProvider>

```

**Comment by Electroid** [comment]
Tested as of Bun v1.0.7, this now works:

```
❯ bun install @mui/x-tree-view
bun add v1.0.7 (b0393fba)

 installed @mui/x-tree-view@6.17.0

 4 packages installed [2.71s]
```

```
❯ bun install @mui/lab
bun add v1.0.7 (b0393fba)

 installed @mui/lab@5.0.0-alpha.150

 64 packages installed [4.74s]
```

If you're still experiencing this issue after upgrading Bun, let us know and we'll re-investigate.
