### ISSUE TITLE
import.meta.env support

### ISSUE THREAD

**Issue by beepsoft** [oven-sh/bun#4667]
### What is the problem this feature would solve?

Introducing access to `.env` variables via `import.meta.env` would make bun more compatible with existing tools (eg. Vite) and would help migrating to bun.

### What is the feature you are proposing to solve the problem?

It would be great to have support for accessing `.env` variables via `import.meta.env` as in Vite: https://vitejs.dev/guide/env-and-mode.html

**Comment by taranek** [comment]
@Jarred-Sumner Any idea when this might happen? We (+ probably many other devs) can't migrate our tests to bun due to this issue

**Comment by MarkLyck** [comment]
@Jarred-Sumner Also having this issue, a lot of my components import something from my config file which includes:

```
const NODE_ENV = import.meta.env.NODE_ENV
```

resulting in an error when running tests:

```
TypeError: undefined is not an object (evaluating 'import.meta.env.NODE_ENV')
```

**Comment by sciolist** [comment]
As a workaround (worked for me at least) you should be able to create a file, say, fix-import-meta-env.js with the content `import.meta.constructor.prototype.env = process.env` then run your scripts with `bun -r ./fix-import-meta-env.js my-script.ts`.

Not something you'd want to keep in the long term. Would be nice to get it built in!

**Comment by Jarred-Sumner** [comment]
Runtime support for import.meta.env is merged, thanks to @otgerrogla. Not yet supported at build-time

**Comment by mnpenner** [comment]
I don't know when this started happening, but `bun run --bun build` works but `bun run build` doesn't. I thought it worked without `--bun` before but it isn't now. (Revision `1.1.25-canary.28+996847bca`)

**Comment by Jarred-Sumner** [comment]
Seeing as `import.meta.env` is implemented at runtime, i'm going to close this. For now, we're keeping `process.env` as the only build-time inlined environment variable object.
