### ISSUE TITLE
bun build does not support `editions` in package.json

### ISSUE THREAD

**Issue by shyim** [oven-sh/bun#4668]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.90.4-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

```
bun install version-compare
```

Create file index.js

```
import versionCompare from 'version-compare'
console.log(['1.1', '2', '1.0'].sort(versionCompare))
```

```
❯ bun build test.js


error: Could not resolve: "version-compare". Maybe you need to "bun install"?
import versionCompare from 'version-compare'
```

### What is the expected behavior?

It bundles it normally

### What do you see instead?

error: Could not resolve: "version-compare". Maybe you need to "bun install"?

### Additional information

The package uses editions in his package.json maybe that's the problem? https://github.com/bevry/version-compare/blob/master/package.json#L85

**Comment by 43081j** [comment]
fyi it is just bun apparently not supporting the export map.

this also causes the failure:

```json
{
  "exports": {
    "node": {
      "import": "main.js",
      "require": "main.js"
    }
  }
}
```

i.e. this test fails right now:

```ts
  itBundled("packagejson/whatever", {
    files: {
      "/Users/user/project/src/entry.js": `import 'some-package'`,
      "/Users/user/project/node_modules/some-package/package.json": `{
        "exports": {
          "node": {
            "import": "main.js",
            "require": "main.js"
          }
        }
      }`,
      "/Users/user/project/node_modules/some-package/main.js": `console.log(808)`,
    },
  });
```

**Comment by balupton** [comment]
Hey there, I'm the maintainer of editions and the @bevry packages, of which editions is being used in a lot more of them. Seems the issue has been identified, let me know if you need anything else from me.

would also be cool for a "bun" export map, as that way a package could target bun specifically with different requirements than say node or deno or workers.

**Comment by Jarred-Sumner** [comment]
`bun build`'s default target is `browser`, and `"node"` is not in the list of `"exports"` conditions for `"browser"`.

To use `bun build` with this package, try

```
bun build --target=bun ./test.js
```

We should make that error message better though for this scenario (package.json "exports" condition did not match)

We won't be adding support for the `"editions"` field at this time.



> i.e. this test fails right now:

The test does not work in Node.js either. There are two reasons why:
1) The exports map is invalid. The file paths must be relative.
2) `target` must be set to `node` or `bun`

This test passes:
```js
  itBundled("packagejson/whatever", {
    files: {
      "/Users/user/project/src/entry.js": `import 'some-package'`,
      "/Users/user/project/node_modules/some-package/package.json": `{
        "exports": {
          "node": {
            "import": "./main.js",
            "require": "./main.js"
          }
        }
      }`,
      "/Users/user/project/node_modules/some-package/main.js": `console.log(808)`,
    },
    target: "bun",
  });
```
