### ISSUE TITLE
No version matching "npm:strip-ansi@^6.0.1" found for specifier "strip-ansi-cjs" (but package exists)

### ISSUE THREAD

**Issue by ChiefORZ** [oven-sh/bun#4669]
### What version of Bun is running?

0.1.2

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```sh
mkdir bun-test && cd ./bun-test
bun init
bun add @isaacs/cliui
```

### What is the expected behavior?

It should resolve dependencies with the **npm:** prefix correctly

### What do you see instead?

```sh
error: No version matching "npm:string-width@^4.2.0" found for specifier "string-width-cjs" (but package exists)
error: No version matching "npm:strip-ansi@^6.0.1" found for specifier "strip-ansi-cjs" (but package exists)
error: No version matching "npm:wrap-ansi@^7.0.0" found for specifier "wrap-ansi-cjs" (but package exists)
```

### Additional information

When i look at the corresponding package.json from the dependency **@isaacs/cliui** i see this resolution:

```json
  "dependencies": {
    "string-width": "^5.1.2",
    "string-width-cjs": "npm:string-width@^4.2.0",
    "strip-ansi": "^7.0.1",
    "strip-ansi-cjs": "npm:strip-ansi@^6.0.1",
    "wrap-ansi": "^8.1.0",
    "wrap-ansi-cjs": "npm:wrap-ansi@^7.0.0"
  }
```
so its requesting the packages in cjs version in their previous version - to prevent breaking changes i guess.
bun can ignore them in the end, but it should download the dependencies anyways so the dependency graph is satisfied.

this problem is quite problematic, because **@isaacs/cliui** is used by **glob@10.3.4** wich is used by a lot of packages

**Comment by ChiefORZ** [comment]
another question - is there a way to override resolved dependencies in bun?
the equivalent to yarn's "resolutions" or pnpm "overrides"

**Comment by julianklumpers** [comment]
I have the same problem with `@MUI/lab`
getting this error: `error: package "@mui/x-tree-view" with tag "https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view" not found, but package exists`

issue: [4666](https://github.com/oven-sh/bun/issues/4666)

**Comment by ChiefORZ** [comment]
had to update bun to 1.0 with `bun upgrade`, works like a charm now - kudos 👏

**Comment by guillaumeduhan** [comment]
`bun upgrade` is the answer
