### ISSUE TITLE
Releases for Linux arm

### ISSUE THREAD

**Issue by AndrusGerman** [oven-sh/bun#468]
Support for arm releases, it will allow us an easy installation in the new aws arm servers, being able to run the project on low-cost servers or even on mobile devices without having to juggle.

I have an android device, with an arch linux installation and an aws (arm) server.
But I can't find clear instructions on how to compile this project to ARM (perhaps there is a lack of documentation on this), and neither are releases to ARM Linux

**Comment by FinnRG** [comment]
Please look at #75 for further information regarding ```arm64```.
