### ISSUE TITLE
force "resolutions" support in bun install

### ISSUE THREAD

**Issue by hb1998** [oven-sh/bun#4685]
### What is the problem this feature would solve?

we are migrating from yarn berry to bun, I see that there is no way to use our existing lock file with bun, so I did a new install with bun, which bumped versions in many packages, with yarn we were forcing the resolutions of some packages, but in bun there seems no way to achieve it

### What is the feature you are proposing to solve the problem?

if bun can respect "resolutions" in package.json and resolve the nested deps based on that, it would be great. 
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by dstaver** [comment]
We would also need this to be able to migrate from yarn to bun. 

We've had numerous issues in the past with multiple incompatible versions of a package being installed through nested dependencies and the wrong version getting picked up for some reason. Forcing resolution to a specific version has solved those issues.

On a related note we have also been using [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) to fix unnecessary duplicate installs where a package could should have been resolved to a single version. I'm not sure if this is an issue with Bun though. Apparently it's specific to Yarn 1.

**Comment by chrisheninger** [comment]
Similar to https://github.com/oven-sh/bun/issues/1751

**Comment by hb1998** [comment]
> Similar to #1751

yeah, its similar, using `resolutions` would be a different way of solving it, for us at least.

**Comment by Hebilicious** [comment]
duplicate #1134

**Comment by hb1998** [comment]
Closing as duplicate of https://github.com/oven-sh/bun/issues/1134
