### ISSUE TITLE
Unsupported platform for bun@1.0.0

### ISSUE THREAD

**Issue by AMohamedAakhil** [oven-sh/bun#4696]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Windows
### What steps can reproduce the bug?

npm install -g bun
on a windows machine.

### What is the expected behavior?

A normal installation to continue

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/78485654/78cdaf76-2e2b-4ea1-af47-fd9d4974896a)
I get the following errror: 

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for bun@1.0.0: wanted {"os":"darwin,linux","arch":"arm64,x64"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  arm64,x64
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaakh\AppData\Local\npm-cache\_logs\2023-09-09T13_56_26_998Z-debug-0.log

**Comment by davinpkn** [comment]
Bun currently is not supported on windows, please view #43

**Comment by AMohamedAakhil** [comment]
lmao
