### ISSUE TITLE
(repo development) locally running zig build throwing errors

### ISSUE THREAD

**Issue by nodeicode** [oven-sh/bun#471]
![image](https://user-images.githubusercontent.com/20450775/178087818-abc48d97-5f8f-4f22-996a-8aa5396fdc45.png)

**Comment by nodeicode** [comment]
I checked zig docs and we actually don't have a path member, I think its updated to ```source```  am I using the wrong zig version?
https://ziglang.org/documentation/master/std/#std;build.Pkg

**Comment by Jarred-Sumner** [comment]
The version of Zig used to compile bun is [here](https://github.com/Jarred-Sumner/zig). Can you try with that one?

**Comment by nodeicode** [comment]
I got zig from that repo and getting this error, I have llvm 14 installed, not able to downgrade to 13 for some reason
![image](https://user-images.githubusercontent.com/20450775/178116762-8adb555b-7942-4165-833b-845bc430d698.png)

**Comment by nodeicode** [comment]
putting this aside I ran the repo with dev container since its evidently faster to get setup, running into this 
![image](https://user-images.githubusercontent.com/20450775/178117060-c1dec4fb-c05d-46e0-b2ef-8d44472dae6a.png)

**Comment by nodeicode** [comment]
there is some mismatch of zig verison going on in the DockerFile,  I think we're pulling a older version here

**Comment by nodeicode** [comment]
found a quick temporary fix https://github.com/Jarred-Sumner/bun/issues/472#issuecomment-1179605829 got devcontainer running, closing issue
