### ISSUE TITLE
"Build a frontend using Vite and Bun" example is not working

### ISSUE THREAD

**Issue by fax1ty** [oven-sh/bun#4710]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Go to https://bun.sh/guides/ecosystem/vite
2. Run `bunx create-vite my-app`
3. ```bunx: command not found```
4. `bun x create-vite my-app`

### What is the expected behavior?

A working project with `vite` and `react` was to be created

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/26363214/9f323201-69e0-4574-887c-4f51790fc971)

### Additional information

I'm using WSL 1.2.5.0

**Comment by fax1ty** [comment]
It turns out that a newer version of Node.js is needed. But I still don't understand why I need Node.js in general

**Comment by changeling123xu** [comment]
maybe your code is error, the 4 code is **bunx create-vite** my-app, the x is connection with bun
