### ISSUE TITLE
@discordjs/opus does not load

### ISSUE THREAD

**Issue by twlite** [oven-sh/bun#4711]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { OpusEncoder } from "@discordjs/opus";

console.log(OpusEncoder);
```

### What is the expected behavior?

Running this on node, it outputs `[Function: OpusEncoder]`.

### What do you see instead?

```ts
283 |           platform: options.target_platform || process.platform,
284 |           target_platform: options.target_platform || process.platform,
285 |           arch: options.target_arch || process.arch,
286 |           target_arch: options.target_arch || process.arch,
287 |           libc: options.target_libc || detect_libc.familySync() || 'unknown',
288 |           libc_version: detect_libc.versionSync() || 'unknown',
                    ^
TypeError: detect_libc.versionSync is not a function. (In 'detect_libc.versionSync()', 'detect_libc.versionSync' is undefined)
      at /.../node_modules/@discordjs/node-pre-gyp/lib/util/versioning.js:288:16
      at /.../node_modules/@discordjs/node-pre-gyp/lib/pre-binding.js:30:14
      at /.../node_modules/@discordjs/opus/lib/index.js:5:25
      at globalThis (/.../node_modules/@discordjs/opus/lib/index.js:5:70)
```

### Additional information

I believe this issue can be closed by PR #3534

**Comment by retrouser955** [comment]
Having the same issue as well.

**Comment by Electroid** [comment]
New error as of Bun v1.0.7 is:

```
error: Cannot find module "node_modules/@discordjs/opus/prebuild/node-v115-napi-v3-darwin-arm64-unknown-unknown/opus.node" from "node_modules/@discordjs/opus/lib/index.js"
```

Which is a duplicate of #4959, so tracking the issue there.

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.

**Comment by SkyLissh** [comment]
I'm haeing this issue, but the error that appears is `error: Cannot find module "node_modules/@discordjs/opus/prebuild/node-v115-napi-v3-linux-x64-glibc-2.29/opus.node" from "node_modules/@discordjs/opus/lib/index."`

This is happening with the Bun version 1.1.8

**Comment by layola13** [comment]
@Jarred-Sumner 
I got this error too

This is happening with the Bun version1.2.13
bun --version
1.2.13

**Comment by NikitaHerndlhofer** [comment]
I got this error too using bun 1.2.13 and 1.2.14
