### ISSUE TITLE
All path remapping in bun test

### ISSUE THREAD

**Issue by lpoulter1** [oven-sh/bun#4713]
### What is the problem this feature would solve?

Currently I use a jest.config to remap paths for tests e.g.
```
module.exports = {
  moduleNameMapper: {
	'my-module-lib': '../src/lib'
  }
};
```

### What is the feature you are proposing to solve the problem?

allow a simular config to be passed to bun test.

**Comment by lefuncq** [comment]
Any updates on that?

**Comment by Garruxx** [comment]
Bun provides ways to solve this, however, this is only possible through the creation of a plugin. Given that I have also had this problem, I decided to create the plugin. I tried to make its operation as similar to Jest’s moduleNameMapper as possible, and for that reason, the package is called bun-module-name-mapper. You can learn more about it at [npm project](https://www.npmjs.com/package/bun-module-name-mapper) or in [the github repository]( https://github.com/Garruxx/bun-module-name-mapper)

**Comment by Jarred-Sumner** [comment]
[We recommend using `"paths"`](https://bun.sh/docs/runtime/modules#path-re-mapping) in either tsconfig.json or jsconfig.json. It's one less thing for you to have to configure. If you need to alias modules specifically in tests, you can use module mocking in `--preload`. 

I'm going to close this for now as we have a solution in place, but please leave a comment if using `tsconfig.json` / `jsconfig.json` is insufficient for tests. Note that we also support [module mocking](https://bun.sh/docs/test/mocks#module-mocks-with-mock-module), which is kind of a heavier version of path remapping

**Comment by hmidmrii** [comment]
Hi @Jarred-Sumner, I need the same feature to map CSS module files to a dict, I don't want to mock every CSS module inside each component test to achieve that,
with jest it was possible to provide the following, and it will work:
```
moduleNameMapper: {
  '^.+\\.(css|s[ca]ss|less)$': 'identity-obj-proxy',
}
```
so there should be a way to map modules using regex like this,
I think a quick way to implement it is to change `mock.module` to accept regex or string for the first argument, and the second one could be a string or a function (now only accept function).
in this way we can rely on it instead of this `moduleNameMapper`

**Comment by igarrux** [comment]
Hi! @hmidmrii  Did you try using the [bun-module-name-mapper](https://www.npmjs.com/package/bun-module-name-mapper) package? Follow the steps in the documentation and you will have the same functionality of jest's moduleNameMapper. https://www.npmjs.com/package/bun-module-name-mapper

**Comment by hmidmrii** [comment]
Yes @igarrux , I used it and it did work, but it would be better to have this functionality supported by bun in the config file.
