### ISSUE TITLE
Building "Quickstart" example shows blank webpage

### ISSUE THREAD

**Issue by arnabanimesh** [oven-sh/bun#4715]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Build the [quickstart example](https://bun.sh/docs/quickstart) from the documentation using `bun build ./index.ts --outdir ./out`
2. Add `index.html` with the following contents in the output directory:
```html
<html>
  <body>
    <div id="root"></div>
    <script type="module" src="/index.js"></script>
  </body>
</html>
```
3. Run the output using `bun x serve out`
4. Open using Chrome

### What is the expected behavior?

See a webpage with ASCII art banner

### What do you see instead?

Blank webpage

### Additional information

Ubuntu 22.04.3 LTS on Windows 11 22H2

**Comment by typescriptlover** [comment]
`bun x serve out` runs the `serve` npm package with your `./out` directory, now here's the problem:

the serve package is meant to serve static files, so what you're really doing is running `index.html` which loads a script `index.js` that's supposed to run as an HTTP server, hence the `Bun.serve` with the `port: 3000`. but instead you're serving it on the browser side and loading it on the browser side, which cannot give you an ASCII art banner response to your `index.html`

**Comment by typescriptlover** [comment]
If want to embed an ASCII Art into your `index.html` via ur `index.js` you'd have to look at supporting figlet in the browser side of things, and then appending that to the DOM. you wouldn't need Bun.serve for any of that.

**Comment by arnabanimesh** [comment]
If there are portions of code that will be rendered obsolete when using `bun x serve` because they run server side, at least `Bun` should provide a warning of sorts regarding the things that won't work when running `bun x serve` IMO. Then I will know which parts of the application to implement browser side depending on what I want specifically. It should be a concern because some `npm` packages run client-side too. In a large application you have to check if each function is working fine if you are deploying the web app to be a hybrid of server side and client side render.
