### ISSUE TITLE
[wsl] bunx: command not found

### ISSUE THREAD

**Issue by kaminskypavel** [oven-sh/bun#4717]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
> bunx create-next-app
bunx: command not found
```

but the following works

```
> bun x create-next-app
? What is your project named? › my-app
```

**Comment by HassanShanJava** [comment]
@kaminskypavel is right, even i have the same issue, here is what i was getting using wsl: 
![image](https://github.com/oven-sh/bun/assets/55858014/45c4642b-ff58-4dce-a6da-03406af18c57)

then using what  he said it got stuck on installing: 
![image](https://github.com/oven-sh/bun/assets/55858014/e115b9c0-5421-49d2-9859-a0ab60702497)

**Comment by HassanShanJava** [comment]
after a while I got this too:
![image](https://github.com/oven-sh/bun/assets/55858014/6ef9f785-e92f-43fe-ad16-e35d7ef78301)

**Comment by kaminskypavel** [comment]
Yeah `bunx` hangs for me too on the first question of `creat-next-app`.

Not sure if there's another ticket opened for that.

**Comment by rraeen** [comment]
but after installing the app when i run bun dev  it open on the localhost:3000 and when i run it in the browser it automatically close the connection why ??

**Comment by 1eldiego** [comment]
@rraeen do you get any error message from the dev server?

**Comment by paperclover** [comment]
the bug in the initial message has been fixed: bun's installation process did not always create the `bunx` symlink.

the other bug where bun install hangs or fails like this seems to be tracked in #4988, which appears to not be a WSL-related issue. it's hard to tell what the exact cause of this problem is, it may be already fixed on the latest version of bun. not sure.

**Comment by kaminskypavel** [comment]
> the bug in the initial message has been fixed: bun's installation process did not always create the `bunx` symlink.

is this part of `1.0.30` ?

I just tried on 

```cli
> bun upgrade --latest
Congrats! You're already on the latest canary build of Bun

> bunx create-next-app
```
and it just exits without SIGTERM or any error message , but nothing happens 🤷
