### ISSUE TITLE
Unable to set up devcontainer

### ISSUE THREAD

**Issue by thislooksfun** [oven-sh/bun#472]
When I run `devcontainer build` it fails with `error: no member named 'source' in struct 'std.build.Pkg'` when trying to install/build `wolfpld/tracy`. I saw #265 and the messages saying to use not the latest zig, but I don't have zig installed locally at all, I'm just trying to run the devcontainer and it's failing.

Here's the relevant section of the output:
```
#0 37.86 Submodule path 'src/known-folders': checked out '9db1b99219c767d5e24994b1525273fe4031e464'
#0 39.01 From https://github.com/wolfpld/tracy
#0 39.01  * branch            2d8723b69b39721eadcc296451012828899c0f17 -> FETCH_HEAD
#0 39.13 Submodule path 'src/tracy': checked out '2d8723b69b39721eadcc296451012828899c0f17'
#0 43.12 ./build.zig:45:48: error: no member named 'source' in struct 'std.build.Pkg'
#0 43.12     exe.addPackage(.{ .name = "known-folders", .source = .{ .path = "src/known-folders/known-folders.zig" } });
```

**Comment by FinnRG** [comment]
@thislooksfun  Please make sure that you cloned the repo using ```git clone --recursive https://github.com/Jarred-Sumner/bun```

**Comment by thislooksfun** [comment]
Tried that, didn't work. I think the issue is related to this line:

https://github.com/Jarred-Sumner/bun/blob/7d1c9fa1a471d180c078a860c4885478f334bdf5/.devcontainer/scripts/zig-env.sh#L4

That clones the _latest_ zls, but as #265 says latest zls requires latest zig. I think the (at least temporary) solution is to check out an earlier commit in zls, but I don't have any idea which commit would work.

**Comment by nodeicode** [comment]
hey guys used this commit of zls, zls always match with zig master, since the zig version we're using is from early march I used zls commit closed to that time and it works! ```4e6564d7daec95b4fb51cadfe25973a87cac181a```
![image](https://user-images.githubusercontent.com/20450775/178122487-cda056ee-adf2-440b-ad98-0880827f491c.png)

**Comment by nodeicode** [comment]
this is definitely still a temporary solution once we update to zig master I think we won't run into any issues with zls latest

**Comment by nodeicode** [comment]
agh spoke too soon, got the container running but running ``` make devcontainer``` throws this error again its a zls issue 
![image](https://user-images.githubusercontent.com/20450775/178123221-5fb79844-d62e-4ca7-83ce-2692d132d073.png)

**Comment by ThatOneBro** [comment]
Having this issue too. Hoping pending upgrade to zig v0.10.0 will fix this

**Comment by hnakamur** [comment]
I confirmed `devcontainer build` runs successfully with a workaround I described at https://github.com/Jarred-Sumner/bun/pull/265#issuecomment-1179636601

**Comment by Electroid** [comment]
It looks like this issue has been resolved? There have also been some recent changes/improvements to the devcontainer. If you still can't set it up, please comment and I'll reopen.
