### ISSUE TITLE
Bun.CryptoHasher has no types (in vscode)

### ISSUE THREAD

**Issue by Aidan647** [oven-sh/bun#4721]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.85-1-pve x86_64 unknown

### What steps can reproduce the bug?

just use `Bun.CryptoHasher`

`const hasher = new Bun.CryptoHasher("sha256")`

### What do you see instead?

Property 'CryptoHasher' does not exist on type 'typeof import("bun")'.ts(2339)

### Additional information

bun-types@1.0.1

**Comment by zzeleznick** [comment]
Maybe a platform specific issue?

Types seem to be working for me running VSCode on a Mac 

<img width="1386" alt="Screenshot 2023-09-09 at 12 50 49 PM" src="https://github.com/oven-sh/bun/assets/5779832/48f05159-f202-41ba-8006-3560fcc808c6">

```
$ bun --revision
1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

$ uname -mprs
Darwin 22.4.0 arm64 arm
```

**Comment by Aidan647** [comment]
If I manually search buns type file there is no `CryptoHasher` in it.

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/682406c42ceee590c2b90900175f0eb1eaed5637/packages/bun-types/bun.d.ts#L2704

Hi, `CryptoHasher` is defined in `bun-types`. You need to install the `bun-types` package. If you have it installed, it might be a vscode configuration issue.


```json
  "devDependencies": {
    "bun-types": "latest"
  },

```

Also this might be helpful https://bun.sh/docs/installation#typescript

**Comment by Aidan647** [comment]
found CryptoHasher in types files.

Probably vscode issue but I never had similar issue before.
