### ISSUE TITLE
Build error on Clang 16

### ISSUE THREAD

**Issue by kisaragi-hiu** [oven-sh/bun#4732]
### What version of Bun is running?

N/A (trying to build 1.0.0)

### What platform is your computer?

Linux 6.1.51-1-lts x86_64 unknown

### What steps can reproduce the bug?

`make usockets` fails on Clang 16 due to `-Wimplicit-function-declaration`, `-Wimplicit-int`, and `-Wincompatible-function-pointer-types` ~~warnings~~ [diagnostics](https://clang.llvm.org/docs/DiagnosticsReference.html#wincompatible-function-pointer-types), which are ~~applied as part of `-Wall` in the `UWS_CC_FLAGS` make variable~~ enabled by default, being changed [from warnings to errors by default](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#potentially-breaking-changes).

https://github.com/oven-sh/bun/blob/ffe4f561a3af53b9f5a41c182de55d7199b5d692/Makefile#L760-L770

### What is the expected behavior?

The build proceeds successfully on Clang 16.

["Bun requires LLVM 15 and Clang 15"](https://bun.sh/docs/project/development#install-llvm) probably implies ("requires Foo version YYY" often means "Foo newer/equal to YYY"; Makefile also says "clang version >= 15 required" at line 667.

### What do you see instead?

The build fails on Clang 16 due to an incompatibility with Clang 16's changes (`-Wimplicit-function-declaration`, `-Wimplicit-int`, and `-Wincompatible-function-pointer-types`, applied by default, [changed from warnings to errors by default](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#potentially-breaking-changes)).

### Additional information

I can work around this by passing `-Wno-implicit-function-declaration -Wno-implicit-int -Wno-incompatible-function-pointer-types` to the command, which, given the way the Makefile is written, can be done with

```sh
make \
  UWS_INCLUDE="-Wno-implicit-function-declaration -Wno-implicit-int -Wno-incompatible-function-pointer-types" \
  usockets # or another target
```

as `UWS_INCLUDE` is only used as a part of `UWS_CC_FLAGS`, which is used in the call to Clang. If adding the flags to the Makefile they should probably be added to `UWS_CC_FLAGS` instead.

**Comment by Hanaasagi** [comment]
Thank you for the explanation. Currently, clang15 is required to compile this project. There is a pr https://github.com/oven-sh/bun/pull/4315 in progress to upgrade to clang16.

Development guide: https://github.com/oven-sh/bun/blob/main/docs/project/development.md

**Comment by Electroid** [comment]
We've since changed to use clang 16.
