### ISSUE TITLE
wrong package installed when using npm rc version

### ISSUE THREAD

**Issue by naftali100** [oven-sh/bun#4736]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.4.13-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

package json:
```json
{
  "name": "bun-rc-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue-toastification": "^2.0.0-rc.5"
  }
}
```
and running
`bun i`

### What is the expected behavior?

the 2.0.0-rc.5 version will be installed

### What do you see instead?

2.0.0-dev.1 verestion installed

### Additional information

![Screenshot from 2023-09-10 01-03-57](https://github.com/oven-sh/bun/assets/48069590/cfaebe40-cdbe-467f-be01-50154e0408e3)

**Comment by Electroid** [comment]
Tested in Bun v1.0.7., this is fixed.

```
❯ bun install
bun install v1.0.7 (b0393fba)
 + vue-toastification@2.0.0-rc.5

 21 packages installed [966.00ms]
```
