### ISSUE TITLE
Illegal instruction (core dumped) on everything

### ISSUE THREAD

**Issue by usama8800** [oven-sh/bun#4744]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

Target `linux-x64-baseline`

### What platform is your computer?

Linux 5.15.0-82-generic x86_64 x86_64

### What steps can reproduce the bug?

Installed bun with `curl -fsSL https://bun.sh/install | bash`

* `bun create folder` does nothing
* `bun init` works
* Going to one of my nodejs projects and doing `bun run index.ts` results in core dump
* `bun run index.ts` on a `bun init` project works fine
* `bun install package` results in illegal core dump
* `bun remove package` results in illegal core dump
* `bun pm` results in illegal core dump
* `bun build index.ts --outfile index.js` in `bun init` folder results in core dump
* `bun repl` does nothing
* `bun upgrade` results in illegal core dump

**Comment by v3nntrnx** [comment]
https://github.com/oven-sh/bun/issues/4124

Maybe this is related?

**Comment by eclairevoyant** [comment]
see https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144, use one of the baseline builds

also this is a duplicate

**Comment by v3nntrnx** [comment]
> see https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144, use one of the baseline builds
> 
> 
> 
> also this is a duplicate

He does use a baseline build

**Comment by usama8800** [comment]
I tried installing through node and docker. Same results

**Comment by TiranexDev** [comment]
Can you do a screenshot of this

`gdb (path to bun)
run upgrade
layout asm`

Also, if you can please join discord (https://bun.sh/discord) so I can respond faster, my username is tiramify on that server

**Comment by usama8800** [comment]
https://discord.com/channels/876711213126520882/1150015839995707425

**Comment by v3nntrnx** [comment]
pcmpgtq, interesting

**Comment by v3nntrnx** [comment]
popcnt (#4124) and pcpmpgtq are SSE4.2 

https://en.wikipedia.org/wiki/SSE4

In additional information (#4124) it says that the author‘s cpu doesn‘t support SSE4.2 which the new instruction uses, that‘s the answer.

**Comment by Electroid** [comment]
Duplicate of #4124, your machine likely has a very old CPU that we do not support. Sorry!
