### ISSUE TITLE
Promise.reject() expects a callback instead of an error (for testing `.rejects`)

### ISSUE THREAD

**Issue by franciscop** [oven-sh/bun#4755]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

Write [the Jest `.rejects` test example](https://jestjs.io/docs/expect#rejects):

```js
test('rejects to octopus', () => {
  // make sure to add a return statement
  return expect(Promise.reject(new Error('octopus'))).rejects.toThrow(
    'octopus',
  );
});
```

Run `bun test`

### What is the expected behavior?

The test passes with a `✓ rejects to octopus`

### What do you see instead?

The test fails with this message:

```js
error: Expected value must be a function
✗ remove > rejects to octopus [0.69ms]
```

### Additional information

From the error message it seems the `expect()` wants a function instead of a promise, but `expect(() => Promise.reject(new Error("octopus")))` also doesn't work (`Expected promise\nReceived: [Function]`).

After some more testing it seems it's `Promise.reject()` the one with a problem:

```js
// Works (notice function in the reject):
const rejecting = Promise.reject(() => new Error("octopus"));
return expect(rejecting).rejects.toThrow("octopus");

// Doesn't work (notice no function):
const rejecting = Promise.reject(new Error("octopus"));
return expect(rejecting).rejects.toThrow("octopus");
```

However [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject), the correct syntax should be the one without the callback, not the one with the callback:

```js
Promise.reject(new Error('fail'))
```

**Comment by franciscop** [comment]
Confirmed as still happening in Bun 1.0.2

**Comment by nektro** [comment]
does this still reproduce for you? it appears to be working on my end in Bun 1.1.9 (you may need to run `bun upgrade`)

**Comment by franciscop** [comment]
I can confirm this works now! A rejected promise works properly and as expected in JS:

```js
console.log(Promise.reject(new Error('octopus')));
// Promise { <rejected> }
```

And the default example I put above works. Thanks for fixing this!
