### ISSUE TITLE
Mongoose findById queries / creating ObjectId from strings not working at all.

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#4757]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

1 - Create a Typescript project with Bun and firstly mongoose
2- Create an async function using mongooseModel.findById
3 - See runtime/type/cast errors on console

### Additional information

Codes:

```js
    async findPlayerById(id: string | Types.ObjectId): Promise<IPlayer | null> {
        return Player.findById(id)
    }
```

Or any function that tries to convert an string to an ObjectId like this:

```js
new ObjectId(id)
```

Just trying to use findById will give you an error like this:
```
1 | (function (...args) { super(...args); })
                                   ^
CastError: Cast to ObjectId failed for value "64fbbf25753d8e6c5bb730ca" (type string) at path "_id" for model "Player"
 path: "_id"
      at new MongooseError (:1:32)
      at new CastError 
```

Trying to actually convert the string into an ObjectId will make a weird runtime error appear:

```


1 \| (function (items){"use strict";if(@isUndefinedOrNull(items))@throwTypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object.");if(typeof items==="string"\|\|typeof items==="object"&&(@isTypedArrayView(items)\|\|items instanceof @ArrayBuffer\|\|items instanceof SharedArrayBuffer\|\|items instanceof @String))switch(@argumentCount()){case 1:return new @Buffer(items);case 2:return new @Buffer(items,@argument(1));default:return new @Buffer(items,@argument(1),@argument(2))}var arrayLike=@toObject(items,"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.");if(!@isJSArray(arrayLike)){const toPrimitive=@tryGetByIdWithWellKnownSymbol(items,"toPrimitive");if(toPrimitive){const primitive=toPrimitive.@call(items,"string");if(typeof primitive==="string")switch(@argumentCount()){case 1:return new @Buffer(primitive);case 2:return new @Buffer(primitive,@argument(1));default:return new @Buffer(primitive,@argument(1),@argument(2))}}if(!("length"in arrayLike)\|\|@isCallable(arrayLike))@throwTypeError("The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.")}return new @Buffer(@Uint8Array.from(arrayLike).buffer)})
--
2 | ^
3 | TypeError: An error occurred while decoding the string
4 | at from (:1:20)


```

**Comment by mizhac** [comment]
![image](https://github.com/oven-sh/bun/assets/5867015/3f1745f6-deaf-4dbc-b479-fe26be792b9d)

I have tried to replicate your problem but I can't do it.

This is my config


```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

bun : 1.0.0
node: 16.19
mongoose: 7.5
hono: 3.5.8
```

**Comment by ghost** [comment]
Very odd, how do you think I can help you trying to replicate?

**Comment by ghost** [comment]
I just recorded a video showing the bug:

https://streamable.com/k1agh9

**Comment by ghost** [comment]
Update: I just tried doing the same thing on a different project and didn't got any errors.

**Comment by ghost** [comment]
I did more researchs and found out that it was the way I was treating bot interactions, still don't know what to do tho.

```JS
//Fetch and registers all event handlers
const eventFiles = fs.readdirSync(path.resolve(__dirname, 'events')).filter(fileFilter)
for (const file of eventFiles) {
    const event = require(`./events/${file}`).default;
    if (event.once) {
        client.once(event.name, (...args) => event.execute(...args).catch(console.error));
    } else {
        client.on(event.name, (...args) => {

            event.execute(...args).catch(console.error) // MORE SPECIFICALLY HERE
      });
    }
}
```

Still don't know what to do...

**Comment by mclmorais** [comment]
I was able to reproduce this issue consistently when parsing a string that contains an emoji to JSON.

```ts
import { ObjectId } from 'mongodb'
const rawMessage = "{\"userId\":\"5f50fbe0b6361571bd53e165\",\"content\":\"😃\"}"
const parsedMessage = JSON.parse(rawMessage)
console.log(parsedMessage.userId)
console.log(parsedMessage.content)
console.log(parsedMessage.userId === '5f50fbe0b6361571bd53e165')
console.log(new ObjectId('5f50fbe0b6361571bd53e165'))
console.log(new ObjectId(parsedMessage.userId))
```

this produces the following output:
```js
5f50fbe0b6361571bd53e165                 // parsedMessage.userId
😃                                       // parsedMessage.content
true                                     // parsedMessage.userId === '5f50fbe0b6361571bd53e165'
new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId('5f50fbe0b6361571bd53e165')
1 | (function (items){"use strict";if(@isUndefinedOrNull(items))@throwTypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object.");if(typeof items==="string"||typeof items==="object"&&(@isTypedArrayView(items)||items instanceof @ArrayBuffer||items instanceof SharedArrayBuffer||items instanceof @String))switch(@argumentCount()){case 1:return new @Buffer(items);case 2:return new @Buffer(items,@argument(1));default:return new @Buffer(items,@argument(1),@argument(2))}var arrayLike=@toObject(items,"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.");if(!@isJSArray(arrayLike)){const toPrimitive=@tryGetByIdWithWellKnownSymbol(items,"toPrimitive");if(toPrimitive){const primitive=toPrimitive.@call(items,"string");if(typeof primitive==="string")switch(@argumentCount()){case 1:return new @Buffer(primitive);case 2:return new @Buffer(primitive,@argument(1));default:return new @Buffer(primitive,@argument(1),@argument(2))}}if(!("length"in arrayLike)||@isCallable(arrayLike))@throwTypeError("The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.")}return new @Buffer(@Uint8Array.from(arrayLike).buffer)})
                       ^
TypeError: An error occurred while decoding the string
      at from (:1:20)
      at fromHex (/home/(...)/node_modules/bson/lib/bson.cjs:160:15)
      at new ObjectId (/home/(...)/node_modules/bson/lib/bson.cjs:2028:28)
      at /home/(...)/index.ts:8:12
```

Removing unicode characters from the string produces the expected output:
```js
{"userId":"5f50fbe0b6361571bd53e165","content":"qwerty"}
5f50fbe0b6361571bd53e165                 // parsedMessage.userId
qwerty                                   // parsedMessage.content
                                         // parsedMessage.userId === '5f50fbe0b6361571bd53e165'
new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId('5f50fbe0b6361571bd53e165')
new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId(message.userId)
```

Maybe the problem is related to the parsing of strings that are then used to create ObjectIds?

**Comment by ghost** [comment]
> I was able to reproduce this issue consistently when parsing a string that contains an emoji to JSON.
> 
> ```ts
> import { ObjectId } from 'mongodb'
> const rawMessage = "{\"userId\":\"5f50fbe0b6361571bd53e165\",\"content\":\"😃\"}"
> const parsedMessage = JSON.parse(rawMessage)
> console.log(parsedMessage.userId)
> console.log(parsedMessage.content)
> console.log(parsedMessage.userId === '5f50fbe0b6361571bd53e165')
> console.log(new ObjectId('5f50fbe0b6361571bd53e165'))
> console.log(new ObjectId(parsedMessage.userId))
> ```
> 
> this produces the following output:
> 
> ```js
> 5f50fbe0b6361571bd53e165                 // parsedMessage.userId
> 😃                                       // parsedMessage.content
> true                                     // parsedMessage.userId === '5f50fbe0b6361571bd53e165'
> new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId('5f50fbe0b6361571bd53e165')
> 1 | (function (items){"use strict";if(@isUndefinedOrNull(items))@throwTypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object.");if(typeof items==="string"||typeof items==="object"&&(@isTypedArrayView(items)||items instanceof @ArrayBuffer||items instanceof SharedArrayBuffer||items instanceof @String))switch(@argumentCount()){case 1:return new @Buffer(items);case 2:return new @Buffer(items,@argument(1));default:return new @Buffer(items,@argument(1),@argument(2))}var arrayLike=@toObject(items,"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.");if(!@isJSArray(arrayLike)){const toPrimitive=@tryGetByIdWithWellKnownSymbol(items,"toPrimitive");if(toPrimitive){const primitive=toPrimitive.@call(items,"string");if(typeof primitive==="string")switch(@argumentCount()){case 1:return new @Buffer(primitive);case 2:return new @Buffer(primitive,@argument(1));default:return new @Buffer(primitive,@argument(1),@argument(2))}}if(!("length"in arrayLike)||@isCallable(arrayLike))@throwTypeError("The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object.")}return new @Buffer(@Uint8Array.from(arrayLike).buffer)})
>                        ^
> TypeError: An error occurred while decoding the string
>       at from (:1:20)
>       at fromHex (/home/(...)/node_modules/bson/lib/bson.cjs:160:15)
>       at new ObjectId (/home/(...)/node_modules/bson/lib/bson.cjs:2028:28)
>       at /home/(...)/index.ts:8:12
> ```
> 
> Removing unicode characters from the string produces the expected output:
> 
> ```js
> {"userId":"5f50fbe0b6361571bd53e165","content":"qwerty"}
> 5f50fbe0b6361571bd53e165                 // parsedMessage.userId
> qwerty                                   // parsedMessage.content
>                                          // parsedMessage.userId === '5f50fbe0b6361571bd53e165'
> new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId('5f50fbe0b6361571bd53e165')
> new ObjectId("5f50fbe0b6361571bd53e165") // new ObjectId(message.userId)
> ```
> 
> Maybe the problem is related to the parsing of strings that are then used to create ObjectIds?

Hey, thanks for submitting your reply, probably discord is sending unicode characters within their JSON, probably the name of the channel or something similar, how could I solve this?

**Comment by Electroid** [comment]
Using the following repro in Bun v1.0.7, this has been fixed.

```js
import { ObjectId } from 'mongodb'
const rawMessage = "{\"userId\":\"5f50fbe0b6361571bd53e165\",\"content\":\"😃\"}"
const parsedMessage = JSON.parse(rawMessage)
console.log(parsedMessage.userId)
console.log(parsedMessage.content)
console.log(parsedMessage.userId === '5f50fbe0b6361571bd53e165')
console.log(new ObjectId('5f50fbe0b6361571bd53e165'))
console.log(new ObjectId(parsedMessage.userId))
```

```
❯ bun mongo.js 
5f50fbe0b6361571bd53e165
😃
true
new ObjectId('5f50fbe0b6361571bd53e165')
new ObjectId('5f50fbe0b6361571bd53e165')
```

If you are still running into this issue after upgrading, let us know and we'll re-open and investigate.
