### ISSUE TITLE
`bun create react` not working

### ISSUE THREAD

**Issue by vani0-0** [oven-sh/bun#4762]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

The create react command is not working properly, I managed to create a react app using 

```
bun create vite@latest react-bun-vite --template react-ts 
```

it did installed but running bun run dev didnt go so well as 'vite is not configured' error message prints out. please fix this so I can use bun in creating react projects. Bun seems so fast to use, i tried creating api's and it does its work pretty fast,

**Comment by bdharrington7** [comment]
dupe #4646 ?

**Comment by colinhacks** [comment]
Note that `bun create react` is not valid as there's no package called `create-react` on npm

I'm going to close this in favor of #4646
