### ISSUE TITLE
(ElectronJS) Generated checksum did not match expected checksum

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#4768]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-200.fc38.x86_64 x86_64

### What steps can reproduce the bug?

As quoted by the site "Bun is designed as a drop-in replacement for Node.js." Bun can run without having NodeJS installed, at all. However, some packages don't install nicely without NodeJS, in my case that is installing Electron, which has a checksum failure.

**Without NodeJS or NPM installed**
 - Open ElectronJS project
 - Run the install command: `bun i` or `bun install`

### What is the expected behavior?

Install as normal, with `bun i` or `bun install` running without failure and installing all packages successfully.	

### What do you see instead?

Error: 
```bash
Error: Generated checksum for "electron-v26.2.0-linux-x64.zip" did not match expected checksum.
```
Full Error:
```bash
[korbs@korbs-framework-13 nexus-polestar]$ bun add electron@latest
bun add v1.0.0 (822a00c4)

 installed electron@26.2.0 with binaries:
  - electron

$ node install.js
Error: Generated checksum for "electron-v26.2.0-linux-x64.zip" did not match expected checksum.
    at new ErrorWithFilename (/run/media/korbs/Framework/Development/SudoVanilla/nexus-polestar/node_modules/sumchecker/index.js:29:9)
    at new ChecksumMismatchError (/run/media/korbs/Framework/Development/SudoVanilla/nexus-polestar/node_modules/sumchecker/index.js:36:9)
    at <anonymous> (/run/media/korbs/Framework/Development/SudoVanilla/nexus-polestar/node_modules/sumchecker/index.js:132:54)
    at onEofChunk (native)
    at readableAddChunk (node:stream:1894:30)
    at <anonymous> (node:stream:3234:21)
    at _flush (node:crypto:1078:13)
    at final (node:stream:3232:19)
    at callFinal (node:stream:2763:23)
    at prefinish (node:stream:2786:23)
error: script "postinstall" exited with code 1 (SIGHUP)

 30 packages installed [2.33s]
error: script "postinstall" exited with code 1 (SIGHUP)
```

**Comment by ghost** [comment]
![image](https://github.com/oven-sh/bun/assets/51213244/6c86f1cd-b69c-4ee6-8707-a513051637cd)

**Comment by Electroid** [comment]
As of Bun v1.0.7, this appears to have been fixed. We fixed various issues with `bun install` resolving an incorrect package version, which may have broken the checksum.

```
❯ bun add electron@latest
bun add v1.0.7 (b0393fba)

 installed electron@27.0.2 with binaries:
  - electron

 61 packages installed [843.00ms]
```

```
❯ cd node_modules/electron
```

```
❯ bun run postinstall
$ node install.js
(exits with 0, normally)
```

**Comment by Electroid** [comment]
In #4959, we will fix the issue where you need to manually run the postinstall script.

**Comment by ghost** [comment]
![image](https://github.com/oven-sh/bun/assets/51213244/0083cc8b-8895-4b13-8346-c22cab2b6ff3)


Re-open it

**Comment by SudoVanilla** [comment]
![image](https://github.com/oven-sh/bun/assets/51213244/c4c46cdd-86f6-4f92-9852-909f2f531474)
:+1:

**Comment by ghost** [comment]
![image](https://github.com/oven-sh/bun/assets/51213244/f4b9945e-62f5-4c9c-a48c-aad778ec673b)

Nope, re-open it, I meant to test it without NodeJS and I didn't yesterday. @Jarred-Sumner

**Comment by ghost** [comment]
Opening duplicate issue in 5 days...
```
bun install v1.0.22 (b400b36c)
  ⚙️  electron [4/5] sharp: Using cached /home/korbs/.npm/_libvips/libvips-8.14.5-linux-x64.tar.br
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies

sharp: Installation error: zlib.BrotliDecompress is not implemented
/usr/bin/bash: line 1: node-gyp: command not found

error: install script from "sharp" exited with 127
```
