### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by zohaibakber** [oven-sh/bun#4770]
### What version of Bun is running?

1.0

### What platform is your computer?

Linux 6.4.14-200.fc38.x86_64 

### What steps can reproduce the bug?

Im trying bun on one of my old machines and at almost every step its throws this error. Maybe machine is way too old but most other things work, maybe binaries are corrupted. 
Here is lscpu:
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        36 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 2
  On-line CPU(s) list:  0,1
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz
    CPU family:         6
    Model:              37
    Thread(s) per core: 1
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           5
    CPU(s) scaling MHz: 80%
    CPU max MHz:        1999.0000
    CPU min MHz:        933.0000
    BogoMIPS:           3989.58
    Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse 
                          sse2 ht tm pbe syscall nx  rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopo  logy nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm pcid popcnt lahf_lm pti ssbd ibrs ibpb stibp dtherm arat flush_l1d
Caches (sum of all):
  L1d:                  64 KiB (2 instances)
  L1i:                  64 KiB (2 instances)
  L2:                   512 KiB (2 instances)
  L3:                   3 MiB (1 instance)

**Comment by eclairevoyant** [comment]
see https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144, use one of the baseline builds

also this is a duplicate
