### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mg3994** [oven-sh/bun#4777]
### What is the problem this feature would solve?

Most Of Problems, As we use Windows PC most of time

### What is the feature you are proposing to solve the problem?

New Windows Support

### What alternatives have you considered?

Modifications

**Comment by ZaLiTHkA** [comment]
FYI: as per the note in the `README.md` file, this is already being tracked in #43.

**Comment by paperclover** [comment]
duplicate of the linked issue. an experimental windows build is coming soon.
