### ISSUE TITLE
Bug Report: Error when using "pm2" module with "bun"

### ISSUE THREAD

**Issue by 4i8** [oven-sh/bun#4778]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.4.0-74-generic x86_64 x86_64

### What steps can reproduce the bug?

Run the following command to execute your script using "bun" with the "pm2" module:
```
nano test.js
```
In your script (located in the current directory), make sure to include the following line to require the "pm2" module:
```js
require("pm2");
```
Run
```
bun run .
```
Observe the behavior and error message generated.

With these steps, you should be able to reproduce the bug where an error occurs when using the "pm2" module with the "bun" command.

### What is the expected behavior?

Expected Behavior:
The "pm2" module should be imported without errors, and the script should run successfully.

Actual Behavior:
An error occurs with the following message:

```
214 | ...
error: Failed to connect at connect (node:net:219:18) ...
```

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/76555623/4d7cced6-fb49-45fd-814f-a701bcc43ceb)

### Additional information

Linux 5.4.0-74-generic x86_64 x86_64 - bun 1.0.0

**Comment by PureSci** [comment]
Any news? I have the same issue

**Comment by 4i8** [comment]
> Any news? I have the same issue

No 💀

**Comment by Electroid** [comment]
As of Bun v1.0.7, this issue appears to be fixed. If you are still running into it after upgrading, let us know and we'll re-investigate.

```
❯ bun install pm2
bun add v1.0.7 (b0393fba)

 installed pm2@5.3.0 with binaries:
  - pm2
  - pm2-dev
  - pm2-docker
  - pm2-runtime


 155 packages installed [695.00ms]
```

```
❯ cat pm2.js
require("pm2");
```

```
❯ bun pm2.js
(exits with 0, no output)
```
