### ISSUE TITLE
Next JS Issue with nextconfig.js

### ISSUE THREAD

**Issue by eveeifyeve** [oven-sh/bun#4784]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.23536.0 x64

### What steps can reproduce the bug?

# Steps

Installed node_modules by npm 

1. Running the code 

### What is the expected behavior?

- ready started server on [::]:3000, url: http://localhost:3000
- event compiled client and server successfully in 1287 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 408 ms (20 modules)

### What do you see instead?

error: Cannot find module "file:///mnt/c/Users/eveeg/Desktop/Development/TeaClient%20Development/Website/next.config.js" from "/mnt/c/Users/eveeg/Desktop/Development/TeaClient Development/Website/node_modules/next/dist/server/config.js"

### Additional information

Dave told me to submit this issue :)

**Comment by Sam-Apostel** [comment]
@Eveeifyeve You should try renaming the `TeaClient Development` folder to something without a whitespace. That solved this issue for me.

**Comment by eveeifyeve** [comment]
I'll look into it

> @Eveeifyeve You should try renaming the `TeaClient Development` folder to something without a whitespace. That solved this issue for me.

**Comment by RiskyMH** [comment]
There has been lots of improvements to next.js in last year and I can't seem to reproduce this error. As such I will close this, but @Eveeifyeve if this still occurs to you let me know and I can open again.

**Comment by Eveeifyeve** [comment]
It took a year and a and I have fully switched from nextjs but I will look into it anyways
