### ISSUE TITLE
Concerned with globally scoped Bun api's

### ISSUE THREAD

**Issue by c-ridgway** [oven-sh/bun#4786]
### What is the problem this feature would solve?

As bun will grow, and new developers come onboard - I've really had a hard time to accept the fact Bun comes with API's accessible through one namespace, for a bunch of unrelated API's.

**Here's a few offending examples:**
```
Bun.serve()
Bun.file()
Bun.write()
Bun.build()
Bun.spawn()
```

### What is the feature you are proposing to solve the problem?

Allowing such functionality to be imported or better namespaced.

**Import method**
Currently we have `import('node:fs')`
Perhaps `import('bun:fs')` and use a bun specific api.

**Namespace method**
```
Bun.http.serve()
Bun.fs.open()
Bun.fs.write()
Bun.bundle.build()
Bun.process.spawn()
```

I really feel like the current design will come back to bite everyone in the near future, as well as confuse a lot of people.

**Comment by Electroid** [comment]
We do this in some cases, for instance, `Bun.dns`. When we introduce new APIs, we'll consider this.
