### ISSUE TITLE
Inquirer.js doesn't work with Bun

### ISSUE THREAD

**Issue by fardjad** [oven-sh/bun#4787]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Install [`@inquirer/prompts@3.0.4`](https://www.npmjs.com/package/@inquirer/prompts/v/3.0.4) as a dependency, and run the following snippet:

```javascript
import { input } from "@inquirer/prompts";

const answer = await input({
  message: "What’s your name?",
  default: "John Doe",
});

console.log(answer);
```

### What is the expected behavior?

It should prompt the user to input some text and read a line from stdin. It works as expected on both Node and Deno.

### What do you see instead?

It throws the following error:

```
120 |
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 |
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
      at run (/Users/far/Desktop/inquirer-bun/node_modules/@inquirer/core/dist/esm/lib/hook-engine.mjs:87:13)
      at workLoop (/Users/far/Desktop/inquirer-bun/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:77:24)
      at /Users/far/Desktop/inquirer-bun/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:86:20
```

### Additional information

At this moment, the latest version of inquirer (`v3.1.0`) has an [unrelated](https://github.com/SBoudrias/Inquirer.js/issues/1297) issue, but after manually patching the file, the same error gets thrown. That's why the example uses an older (`v3.0.4`) version of the package

**Comment by AverageHelper** [comment]
For the record, it seems that [@inquirer/prompts@3.1.1](https://github.com/SBoudrias/Inquirer.js/releases/tag/%40inquirer%2Fprompts%403.1.1) fixes the aforementioned [unrelated](https://github.com/SBoudrias/Inquirer.js/issues/1297) issue.

**Comment by AverageHelper** [comment]
Also, some notes:

`bun --bun x @inquirer/demo@latest` behaves as expected on my machine. (v0.2.11 is the latest at time of writing.)

I can reproduce the issue described above with in a separate project with only `@inquirer/select@1.2.11`. Seems anything that depends on `@inquirer/core` is affected.

It seems that both `@inquirer/demo` and `@inquirer/select` depend on the same version of `@inquirer/core` (v5.0.0 at time of writing). I don't know yet what's making the difference, why one works and the other does not.

**Comment by Jarred-Sumner** [comment]
Fixed by @paperdave in https://github.com/oven-sh/bun/pull/6095
