### ISSUE TITLE
`node:path.relative` edge case

### ISSUE THREAD

**Issue by Hanaasagi** [oven-sh/bun#4789]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```JavaScript
const path = require("node:path");
console.log(path.relative("/app/node_modules/pkg", "../static"));
```

### What is the expected behavior?

```
>>​ node i.cjs
../../../static
```

### What do you see instead?

```
>>​ bun run i.cjs
../../static

```

`app` is my process cwd.

**Comment by Hanaasagi** [comment]
testcases
```JavaScript
const assert = require("assert");
const path = require("path");

const cwd = process.cwd();
const cwdParent = path.dirname(cwd);
const parentIsRoot = cwdParent === "/";

const cases = [
  [
    "/app/node_modules/pkg",
    "../static",
    `../../..${parentIsRoot ? "" : cwdParent}/static`,
  ],
  [
    "/app/node_modules/pkg",
    "../../static",
    `../../..${parentIsRoot ? "" : path.dirname(cwdParent)}/static`,
  ],
  ["/app", "../static", `..${parentIsRoot ? "" : cwdParent}/static`],
  ["/app", "../".repeat(64) + "static", "../static"],
  [".", "../static", "../static"],
  ["/", "../static", parentIsRoot ? "static" : `${cwdParent}/static`.slice(1)],
];

cases.forEach(([from, to, expected]) => {
  console.log("test", from, to);
  const result = path.relative(from, to);
  assert.equal(result, expected);
});

console.log("All test cases passed!");

```

**Comment by Jarred-Sumner** [comment]
Can we port all of node's tests for this? So that it stops being a problem going forward

**Comment by Hanaasagi** [comment]
@Jarred-Sumner 

I compared the test cases for `path.relative` in node and bun, and I found that Bun currently has more test cases than node. 🤦 Maybe we need a fuzz test.

node.js: https://github.com/nodejs/node/blob/afea87ee14cd47e70049cbd741ffccb8223f95ca/test/parallel/test-path-relative.js#L4
bun: https://github.com/oven-sh/bun/blob/afcbed218c425872648b7c0aa2ce331ad3b0d612/test/js/node/path/path.test.js#L458

**Comment by ottomated** [comment]
This will close #4616 :)
