### ISSUE TITLE
bun create astro@latest fails

### ISSUE THREAD

**Issue by marcinjahn** [oven-sh/bun#4800]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.13-200.fc38.x86_64 x86_64 unknow

### What steps can reproduce the bug?

Run:

```sh
bun create astro@latest
```

### What is the expected behavior?

I'd expect `bun create astro@latest` to create a project from template just like `npm create astro@latest` does.

### What do you see instead?

The error I'm getting is:

```
error: Cannot find package "giget" from "/tmp/create-astro@latest--bunx/node_modules/create-astro/dist/index.js"
error: "create-astro" exited with code 1 (SIGHUP)
```

**Comment by paperclover** [comment]
in 1.0.29, better cache invalidation was added to bunx (what `bun create` executes). the assumption is that an earlier version of bunx installed a astro incorrectly and cached that invalid data. `@latest` will also force cache busts here too.
