### ISSUE TITLE
Unable to connect to cassandra server using cassandra driver

### ISSUE THREAD

**Issue by Darker-Ink** [oven-sh/bun#4815]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 (WSL: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown)

### What steps can reproduce the bug?

For some reason when trying to use [cassandra-driver](https://www.npmjs.com/package/cassandra-driver) it doesn't seem to be able to connect to the scylladb (/cassandra) server, though running the same code in node seems to work, Below is some example code (I'm using a custom fork of cassandra-driver though same thing happens when just using the vanilla driver)

```ts
import { Client } from "@kastelll/cassandra-driver";

const client = new Client({
    contactPoints: ['localhost'],
    localDataCenter: 'datacenter1',
    credentials: {
        username: 'usr',
        password: 'pwd',
    },
});

await client.connect();
```

### What is the expected behavior?

It should connect to the scylladb / cassandra instance perfectly fine

### What do you see instead?

```
ink@SAMSUNG-S4MCZZA:~/testing/app$ bun run test.ts
NoHostAvailableError: All host(s) tried for query failed. First host tried, 127.0.0.1:9042: Error: Failed to connect. See innerErrors.
 info: "Represents an error when a query cannot be performed because no host is available or could be reached by the driver."
```

**Comment by AdamSGit** [comment]
Same issue. This seem to be the same as #4033
