### ISSUE TITLE
can't find variable: module

### ISSUE THREAD

**Issue by sibelius** [oven-sh/bun#4818]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```jsx
if (!isMainScript(module) {
    return;
  }
```

```jsx
export const isMainScript = (module) => {
  if (!module.parent) {
    return true;
  }

  return false;
};
```

module resolves to `NodeModule` inside `@types/node/globals.d.ts`

```
declare var module: NodeModule;
```

### What is the expected behavior?

it should work

### What do you see instead?

```
ReferenceError: Can't find variable: module
```

**Comment by matheusinfo** [comment]
I tried to reproduce it here, but apparently it works:

```
FILE: index.ts

const { isMainScript } = require("./main-script");

if (!isMainScript(module)) {
    console.log("Not main script");
}
```

```
FILE: main-script.ts

export const isMainScript = (module) => {
    if (!module.parent) {
        return true;
    }

    return false;
};
```

The point is that my module resolves from `bun-types/types.d.ts`. Do you have any repository with this code?

**Comment by jld-adriano** [comment]
I made a repro https://github.com/jld-adriano/bun-repro-4818
Just bun index.ts

I think it's related to a module that imports another module that is in "module mode" because it imports from another one. I had to do 3 files to repro but maybe there's another way

**Comment by jld-adriano** [comment]
@paperdave my repro still errors out, with the same error

Tested on 1.0.7

**Comment by vindard** [comment]
> I made a repro https://github.com/jld-adriano/bun-repro-4818 Just bun index.ts
> 
> I think it's related to a module that imports another module that is in "module mode" because it imports from another one. I had to do 3 files to repro but maybe there's another way

Bump

**Comment by paperclover** [comment]
`module` and `import`/`export` cant be used in the same file. @Jarred-Sumner 

<img width="785" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/59f212e4-da6d-4c78-9510-3e2f883470bc">

it seems the work done in #7223 to display a better error message here does not work.
