### ISSUE TITLE
Env loader bug

### ISSUE THREAD

**Issue by hanzydev** [oven-sh/bun#4827]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I have a value called PASSWORD in my .env file.

This looks like this:

`PASSWORD=$argon2id$v=19$m=65536,t=2,p=1$nk0RKpKqDlf8OwvOLmQ+wcypM7e7Su3E/yiP01/iueY$Klujl4K+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ`

However, if you try to get this value through the code as `Bun.env.PASSWORD`, you will see that it comes as `=19=65536,t=2,p=1+wcypM7e7Su3E/yiP01/iueY+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ`.

### What is the expected behavior?

$argon2id$v=19$m=65536,t=2,p=1$nk0RKpKqDlf8OwvOLmQ+wcypM7e7Su3E/yiP01/iueY$Klujl4K+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ

### What do you see instead?

=19=65536,t=2,p=1+wcypM7e7Su3E/yiP01/iueY+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ

**Comment by matheusinfo** [comment]
It looks like the encoding of your ENV. Try saving it like this, and it will work fine:

`
PASSWORD='\$argon2id\$v=19\$m=65536,t=2,p=1\$nk0RKpKqDlf8OwvOLmQ+wcypM7e7Su3E/yiP01/iueY\$Klujl4K+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ'
`

![image](https://github.com/oven-sh/bun/assets/48860569/413b8fe4-86ae-42af-bb01-6b1c865acd20)

**Comment by hanzydev** [comment]
> It looks like the encoding of your ENV. Try saving it like this, and it will work fine:
> 
> `PASSWORD='\$argon2id\$v=19\$m=65536,t=2,p=1\$nk0RKpKqDlf8OwvOLmQ+wcypM7e7Su3E/yiP01/iueY\$Klujl4K+SkE5zduCNCLwK0Xr1vtDB/aGzGMzj14TUUQ'`
> 
> ![image](https://user-images.githubusercontent.com/48860569/266848193-413b8fe4-86ae-42af-bb01-6b1c865acd20.png)

thanks! problem solved
