### ISSUE TITLE
Weird behavior on fresh install of WSL and Bun.

### ISSUE THREAD

**Issue by 0zl** [oven-sh/bun#484]
![image](https://user-images.githubusercontent.com/69357965/178100998-7809b7bd-56d0-4ac3-b585-ac57c67ed543.png)

Tried reinstalling Bun and resetting WSL Image, same result. I've also added Bun PATH to my `.bashrc`.

`Ubuntu 20`
`WSL Version: 1`

**Comment by zekefeu** [comment]
Take a look at #67, that may help with WSL issues.

**Comment by FinnRG** [comment]
Your CPU doesn't support AVX. Please look at #67 for further information.
