### ISSUE TITLE
Bun Lambda Layer does not properly handle API Gateway V1 events

### ISSUE THREAD

**Issue by tekkeon** [oven-sh/bun#4843]
### What steps can reproduce the bug?

1. Follow the steps in the Lambda Layer README to publish the layer and create a Lambda function.
2. Connect the Lambda Function with the Bun Lambda Layer to a REST API Gateway (V1).
3. Test the endpoint.

### What is the expected behavior?

The Lambda function should properly handle the request.

### What do you see instead?

Errors in the Lambda Layer trying to construct the request.

### Additional information

I've found these specific issues with the Lambda Layer `runtime.ts` code that, when changed, fixes the issues with V1 events:
1. `isHttpEventV1` assumes the event has a field called `version` and a value of `1.0`. In fact, only V2 events have a `version` with value `2.0` while V1 events simply omit the version field altogether.
2. `formatHttpEventV1` inserts headers to a Headers instance both from the `event.headers` field and the `event.multiValueHeaders` and then uses the Headers instance to get the Host and X-Forwarded-Proto header. The problem is that API gateway actually duplicates these values across headers and multiValueHeaders, probably as a convenience thing, so when you retrieve Host from Headers, you end up with something like `example.org, example.org` when you just want `example.org`.
3. If Host header is not defined, then `response.text()` is returned. I'm not sure why exactly this is, but it breaks the testing experience in API Gateway unless you explicitly include a Host header.

~~Also, while trying to debug all of this, I noticed that trying to `console.log` multiple values (e.g. `console.log('Message', object)`) results in only logging the first value. I see that the `runtime.ts` puts a wrapper around `console.log` and I'm guessing that `Bun.inspect` is perhaps the culprit here.~~ Looks like there is a PR fixing this issue here: https://github.com/oven-sh/bun/pull/4781

**Comment by tekkeon** [comment]
I'd be happy to take this issue and can probably get a fix out in the next couple days, but wanted to have the issue open before submitting a PR.

**Comment by tekkeon** [comment]
I see this PR: https://github.com/oven-sh/bun/pull/4781 already fixes the last comment I had about console.log only printing the first argument, so I'll just focus on the other four issues.

**Comment by Electroid** [comment]
Fixed in #5161, thanks @mkossoris! 🎉
