### ISSUE TITLE
fs.readFileSync with base64 encoding incompatible with Node.js

### ISSUE THREAD

**Issue by mjomble** [oven-sh/bun#4845]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Create file `b64.js` with contents
```
console.log(require('fs').readFileSync('b64.js', 'base64'))
```
then run `bun b64.js` and `node b64.js`

### What is the expected behavior?

Bun should write out the same base64 string as Node.js:
```
Y29uc29sZS5sb2cocmVxdWlyZSgnZnMnKS5yZWFkRmlsZVN5bmMoJ2I2NC5qcycsICdiYXNlNjQnKSkK
```

### What do you see instead?

Bun writes out the raw contents of the file, without base64-encoding them:
```
console.log(require('fs').readFileSync('b64.js', 'base64'))
```

### Additional information

This breaks `require('pdfmake')`

**Comment by ThieryMichel** [comment]
Exact same issue here.
