### ISSUE TITLE
Unable to create Vite app

### ISSUE THREAD

**Issue by eriquemelo** [oven-sh/bun#4853]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

`bun x create-vite ./`

### What is the expected behavior?

Should create a Vite template

### What do you see instead?

`error: ConnectionRefused downloading package manifest create-vite`
`error: create-vite@latest failed to resolve`

**Comment by ThatXliner** [comment]
Cannot reproduce (Bun 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983, Darwin 22.5.0 x86_64 i386)

**Comment by colinhacks** [comment]
This looks like a transient network error or npm registry outage

**Comment by eriquemelo** [comment]
> This looks like a transient network error or npm registry outage

Yep, it's now working on my machine!
