### ISSUE TITLE
Bun is so fast that the web client thinks that the served file is for download

### ISSUE THREAD

**Issue by neksodebe** [oven-sh/bun#4855]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.12-100.fc36.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

1. Have a somewhat complex TypeScript project that tunnels the traffic from port 5000 (express app) to port 3000 (React dev server)
2. Run this: `concurrently --kill-others \"cd ../Parottu-Client/ && bun x react-scripts start\" \"dotenv -v USE_DEV_SERVER=true -- nodemon --watch src -e 'ts tsx js jsx html json' --exec 'bun x tsc --skipLibCheck && bun out/src/server.js'\"` using `bun x devbun`

### What is the expected behavior?

Server works fine, and tunnels the traffic normally

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/64833558/a0189796-e0ac-443d-8d74-a430fee2e9e0)
![image](https://github.com/oven-sh/bun/assets/64833558/6be2d5ae-228e-47b2-8f4f-3602e1538e14)

**Comment by Electroid** [comment]
We'll need some code to reproduce this issue. Is that something you could provide?

**Comment by Electroid** [comment]
Not able to reproduce. If you're able to give us some more info we can look into it.
