### ISSUE TITLE
TypeError: Unsupported algorithm sha3-256

### ISSUE THREAD

**Issue by Khalid-Nowaf** [oven-sh/bun#4862]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import crypto from "node:crypto"

crypto
            .createHash('sha3-256')
            .update("sdfsdfsdfksjdflskfjslkfjsldkfj")
            .update(process.version)
            .digest('hex');
```

```log
1051 |     }, module.exports = CipherBase;
1052 |   }
1053 | }), require_browser2 = __commonJS({
1054 |   "node_modules/create-hash/browser.js"(exports, module) {
1055 | 
1056 |     const LazyHash = function Hash(algorithm, options) {
                                                                       ^
TypeError: Unsupported algorithm sha3-256
 code: "ERR_INVALID_ARG_TYPE"

      at new Hash (node:crypto:1056:68)
      at createHash (node:crypto:1175:80)
      at /Users/xxxx/projects/xxxx/src/main.ts:14:9
      at main (/Users/xxxx/projects/xxxx/src/main.ts:4:19)
      at /Users/xxxx/projects/xxxx/src/main.ts:22:0
```

### What is the expected behavior?

it should run without error
```
TypeError: Unsupported algorithm sha3-256
```

### What do you see instead?

```log
TypeError: Unsupported algorithm sha3-256
 code: "ERR_INVALID_ARG_TYPE"

      at new Hash (node:crypto:1056:68)
      at createHash (node:crypto:1175:80)
```

### Additional information

This is my first attempt to port my code to Bun, and I noticed one of my dependencies uses `node:crypto`, which is causing this error.

**Comment by simylein** [comment]
This could be missing in the implementation currently because the types suggest it is not supported. 
<img width="365" alt="Screenshot 2023-09-11 at 07 11 50" src="https://github.com/oven-sh/bun/assets/67859356/6283fd06-1128-4ce2-b8ca-f29f60e1b8c1">

**Comment by Jarred-Sumner** [comment]
It's missing from our build of BoringSSL. We could probably get it from zig stdlib though

**Comment by libre-man** [comment]
To add to this, the algorithm `blake2b512` is also missing.
