### ISSUE TITLE
Remove cache command doesn't clear it

### ISSUE THREAD

**Issue by akshaybabloo** [oven-sh/bun#4863]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

Running `bun pm cache rm` doesn't clear the cache, it just prints out the path of the cache.

### What is the expected behavior?

I think it should delete all the contents in `/home/<user>/.bun/install/cache`

### What do you see instead?

Prints out the cache path

**Comment by Hanaasagi** [comment]
this could be fixed by #4571

**Comment by jhmaster2000** [comment]
Closing as duplicate of #1720
