### ISSUE TITLE
Crash when running bun create-vite my-app or bun x create-vite my-app selecting a framework or variant

### ISSUE THREAD

**Issue by notjosho** [oven-sh/bun#4873]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Ubuntu 22.04.3 LTS 5.15.90.1-microsoft-standard-WSL2

### What steps can reproduce the bug?

install bun on ubuntu
run bun x create-vite my-app
select with enter React
On 'Select a variant: ' it will freeze
also happening with bun create vite@latest on 'Select a framework'

### What is the expected behavior?

user has to be able to select a framework and continue with installation

### What do you see instead?

freeze on selection

**Comment by artenlf** [comment]
See #4646 and #4664

**Comment by divyanthj** [comment]
+1
