### ISSUE TITLE
res.json() throw JSON Parse error

### ISSUE THREAD

**Issue by hkmute** [oven-sh/bun#4876]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

run below code with bun will throw `SyntaxError: JSON Parse error: Unrecognized token ''`

```
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const data = await res.json();
console.log(data);
```

### What is the expected behavior?

log the response json

### What do you see instead?

`SyntaxError: JSON Parse error: Unrecognized token ''`

**Comment by njsharpe** [comment]
Hello! I took a look into this and it seems the issue stems from the dataset used and not the JSON parser for Bun. You can fix this error by (if possible) modifying the source itself to trim any whitespace before or after the closing curly braces, or use an approach similar to the one below to modify the data after fetching it.

```js
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const text = await res.text();
const json = JSON.parse(text.trim());
console.log(json);
```

Hope this helps!

**Comment by ArjixWasTaken** [comment]
> Hello! I took a look into this and it seems the issue stems from the dataset used and not the JSON parser for Bun. You can fix this error by (if possible) modifying the source itself to trim any whitespace before or after the closing curly braces, or use an approach similar to the one below to modify the data after fetching it.
> 
> ```js
> const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
> const text = await res.text();
> const json = JSON.parse(text.trim());
> console.log(json);
> ```
> 
> Hope this helps!

if the error is caused by whitespace, ain't that a parser issue?
whitespace should be ignored if it is not within a string

**Comment by j0nimost** [comment]
should be an easy fix

**Comment by AaronDewes** [comment]
> Hello! I took a look into this and it seems the issue stems from the dataset used and not the JSON parser for Bun.

It works in Node.js, and the JSON spec says whitespace is allowed https://www.rfc-editor.org/rfc/rfc4627

> Insignificant whitespace is allowed before or after any of the six structural characters.

So this is definitely a bug in bun. 

```
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const text = await res.text();
const json = JSON.parse(text);
```

Also works in bun, so JSON.parse accepts the whitespace.

**Comment by Hanaasagi** [comment]
The first char in this json is [Zero Width Non-Breaking Space](https://www.fileformat.info/info/unicode/char/feff/index.htm).

```JavaScript
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const text = await res.text();
console.log(text[0].charCodeAt(0) == 0xfeff);
```


In node this is also not supported. You can try running the following code with node.js:


```JavaScript
const https = require("https");

const url = "https://www.1823.gov.hk/common/ical/en.json";

https
  .get(url, (response) => {
    let data = "";

    response.on("data", (chunk) => {
      data += chunk;
    });

    response.on("end", () => {
      try {
        const jsonData = JSON.parse(data);
        console.log(jsonData);
      } catch (error) {
        console.log(error);
      }
    });
  })
  .on("error", (error) => {
    console.log(error);
  });

```

node v18.17.1 will throw `SyntaxError: Unexpected token ﻿ in JSON at position 0`


I think trimming by user is necessary here (just a personal opinion).

**Comment by AaronDewes** [comment]
> In node this is also not supported. You can try running the following code with node.js:

```JS
const res = await fetch("https://www.1823.gov.hk/common/ical/en.json");
const data = await res.json();
console.log(data);
```

This snippet works in node, but not in Bun

**Comment by Hanaasagi** [comment]
Thank you for the correction. Node's fetch API can indeed handle this special character 0xfeff. Perhaps bun also needs to perform similar processing in the `resp.json`.

**Comment by akx** [comment]
> The first char in this json is [Zero Width Non-Breaking Space](https://www.fileformat.info/info/unicode/char/feff/index.htm).

That's incorrect (and it's weird that `res.text()` does that!).

```
$ curl https://www.1823.gov.hk/common/ical/en.json | head | xxd
00000000: efbb bf7b 0d0a 0909 2276 6361 6c65 6e64  ...{...."vcalend
00000010: 6172 223a 205b 7b0d 0a09 0909 2270 726f  ar": [{....."pro
```

The first three bytes are EF BB BF, the [UTF-8 Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark), which is actually specially handled by `undici`, the library Node apparently uses for `fetch`, when calling `.json()`: https://github.com/nodejs/undici/blob/e39a6324c4474c6614cac98b8668e3d036aa6b18/lib/fetch/body.js#L554-L574

In Node,

```
> fetch("data:application/json,%EF%BB%BF{}").then(r => r.json()).then(console.log)
{}
```
In Bun REPL,
```
> fetch("data:application/json,%EF%BB%BF%7B%7D").then(r => r.json())
SyntaxError: JSON Parse error: Unrecognized token ''
```
(replacing `%7B%7D` with `{}` triggers #5073 instead).

**Comment by dmythro** [comment]
Wow, I hope it gets fixed, otherwise a no-go. With workarounds above I get something like this:

```
48 | async function POST(request, { params: { customer } }) {
49 |     const requestParams = await request.text();
50 |
51 |     const { filter, offset = 0, query, sort } = JSON.parse(requestParams.trim());
                                                   ^
SyntaxError: JSON Parse error: Unexpected identifier "object"
```

**Comment by itpropro** [comment]
Have the same problem currently with a graphql server running with `bun.serve`. I get "Failed to parse JSON" as a friendly error due to the problems mentioned in this issue. Any timeline for a fix? Don't want to replace bun again.

**Comment by Jarred-Sumner** [comment]
#7391 fixes this
