### ISSUE TITLE
Cannot create astro

### ISSUE THREAD

**Issue by TeaEwan** [oven-sh/bun#4878]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.1.0-11-amd64 x86_64

### What steps can reproduce the bug?

url: [https://bun.sh/guides/ecosystem/astro](https://bun.sh/guides/ecosystem/astro)

Execute a command: `bun x create-astro`

In the second step "How would you like to start your new project?", you can't choose up and down, and you can't confirm the first one, no matter what key you press.

<img width="696" alt="image" src="https://github.com/oven-sh/bun/assets/93706123/b887574f-62f0-44af-9f36-a776bd17954d">

**Comment by TeaEwan** [comment]
When I use node.js and pnpm, I can choose normally.

<img width="701" alt="image" src="https://github.com/oven-sh/bun/assets/93706123/3db0fc31-6bea-48a8-bbb8-7e3e3579ebf9">

**Comment by nzoschke** [comment]
This works fine for me. Bun 1, Astro 3, OS X.

**Comment by birkskyum** [comment]
Interesting. @TeaEwan , does `bun --bun x create-astro` yield the same result?

**Comment by TeaEwan** [comment]
> Interesting. @TeaEwan , does `bun --bun x create-astro` yield the same result?

Still not. when "How would you like to start your new project?" appears, pressing "ctrl + c" cannot exit the command, it is stuck..

It works properly by manually installing it through the following steps:

`bun init`

`bun i astro`

`mkdir {src,public} && touch astro.config.mjs`

For more information, please see: [https://docs.astro.build/en/install/manual/](https://docs.astro.build/en/install/manual/).

`bun x astro dev --host`

**Comment by nzoschke** [comment]
I did hit a different problem with bun and the Astro cli today. Installing the tailwind plug-in didn't work, it automatically simulates typing ctrl-c when it prompted to write the tailwind cfg file.

So maybe some small subtle stuff with TTYs?

**Comment by birkskyum** [comment]
@nzoschke , could be - here are some of the unresolved terminal issues
- https://github.com/oven-sh/bun/issues/2333
- https://github.com/oven-sh/bun/issues/4835

**Comment by AdoryVo** [comment]
I had the same exact problem on Windows WSL Ubuntu!

Installing the Git & Node.js LTS versions mentioned in [this other issue thread comment](https://github.com/oven-sh/bun/issues/4664#issuecomment-1714389993) fixed it for me. 
I followed [this source](https://git-scm.com/download/linux) for Git and [this source](https://github.com/nodesource/distributions) for Node.js.

Perhaps only Node.js is needed for it to work, and I'm not sure how much the version matters - I didn't really mess around with these factors.

Hope this helps!

**Comment by TeaEwan** [comment]
Use version 1.0.2([https://github.com/oven-sh/bun/releases/tag/bun-v1.0.2](https://github.com/oven-sh/bun/releases/tag/bun-v1.0.2)) , it works properly. Thank you.
