### ISSUE TITLE
Bun with Elysia SIGHUP when reading file

### ISSUE THREAD

**Issue by xzones2014** [oven-sh/bun#4879]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

.get("/file", () => Bun.file("./src/halo.json"))

### What is the expected behavior?

just show the file content

### What do you see instead?

then open that path on the browser, immediately exit without stack trace info 
console show
error: script "dev" exited with code 1 (SIGHUP)

**Comment by yoroshikun** [comment]
https://bun.sh/docs/api/file-io

try `Bun.file("./src/halo.json").text()` <- convert to text, not just reference.

Do your best to practice defensive programming for bugs.
The above will error if the file doesn't exist etc. so try to write some catches etc to prevent your program from crashing.

**Comment by xzones2014** [comment]
> https://bun.sh/docs/api/file-io
> 
> try `Bun.file("./src/halo.json").text()` <- convert to text, not just reference.
> 
> Do your best to practice defensive programming for bugs. The above will error if the file doesn't exist etc. so try to write some catches etc to prevent your program from crashing.

i did many ways, but still not found the cause

```
.get("/puyeng", async() => {
    
    const file = Bun.file("package.json");
    const res = {
      size : file.size
    }
    if (file.size){
      try {
        const isi = await file.text()
        console.log(`isi : ${isi}`)
        return new Response( file )
        
      } catch (error) {
        console.log(error)
      }
    } 
    return res
   
  })
```

that code above still panic without meaningful error , SIGHUP immediately when reaching the line .text()

**Comment by Willbill360** [comment]
I'm having the same issue with the same simple code:
```js
try {
    const input = await file('./package.json').text() // .json() also breaks
    console.log(input)
} catch(e) {
    console.error(e)
}
```

Even a Try-Catch doesn't reveal any errors and the process still stops with a SIGHUP error. The `catch` is not even being executed.

Also, it doesn't appear to be related to Elysia, as my project doesn't use it.

Output:
`error: script "start" exited with code 1 (SIGHUP)`

**Comment by Speaker4TheUndead** [comment]
Experiencing same issue on Ubuntu. I'm also using Elysia Html.

**Comment by iamcsharper** [comment]
same thing on WSL 2

**Comment by iamcsharper** [comment]
@Jarred-Sumner sorry to bother you, but will this issue be addressed?

**Comment by hex2f** [comment]
Hmm, this is still happening for me in versions 1.0.18 and forwards. Works fine in 1.0.17
