### ISSUE TITLE
Reload page when serving server

### ISSUE THREAD

**Issue by FreePhoenix888** [oven-sh/bun#4887]
### What is the problem this feature would solve?

When I run an HTTP server with `--watch` or `--hot` option it actually reloads, but the page is not reloaded

### What is the feature you are proposing to solve the problem?

Reload page when server reloads

**Comment by FreePhoenix888** [comment]
I am not sure whether this feature should be added. As I see deno does not reload page too. What is the reason ? :)

**Comment by sirenkovladd** [comment]
Because Bun will need to edit the content that is sent from the HTTP server, this is usually not possible

**Comment by FreePhoenix888** [comment]
> Because Bun will need to edit the content that is sent from the HTTP server, this is usually not possible

Thank you for answer!
