### ISSUE TITLE
Small tweaks to error stack traces

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#4889]
The following stacktrace:
```js
1148 |         }
1149 |       }
1150 |     }
1151 |   }
1152 |   console.log(jsReleases);
1153 |   browserslist.nodeVersions = jsReleases.map(function (release) {
                                  ^
TypeError: jsReleases.map is not a function. (In 'jsReleases.map(function(release) {
      return release.version;
    })', 'jsReleases.map' is undefined)
      at /Users/jarred/Code/bun/test/js/third_party/webpack/node_modules/browserslist/index.js:1153:30
      at /Users/jarred/Code/bun/test/js/third_party/webpack/node_modules/browserslist/index.js:1155:3
      at globalThis (/Users/jarred/Code/bun/test/js/third_party/webpack/node_modules/browserslist/index.js:1158:17)
      at require (:1:20)
      at /Users/jarred/Code/bun/test/js/third_party/webpack/a.js:1:8
      at globalThis (/Users/jarred/Code/bun/test/js/third_party/webpack/a.js:1:35)
```
The following should be fixed:

- Why is `require (:1:20)` shown on a line by itself? Let's just get rid of it from the trace, it's an internal function being called
- Why do the CommonJS module scripts all have `globalThis` prepended? The literal answer: CJS functions use eval with an IIFE, but the real answer is lets not do that. It would be nice to have some indicator saying [ESM] or [CJS] but it's optional extra info 

It would be very nice if we added syntax highlighting to the source code snippet. But we don't have an easy way to do that right now. And it can't be done in JS.

**Comment by paperclover** [comment]
i think this is resolved now
