### ISSUE TITLE
Installing a package with @latest results in "latest" appearing as the version in package.json

### ISSUE THREAD

**Issue by yandodov** [oven-sh/bun#4892]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Install a package with `@latest`:

```
$ bun install axios@latest
bun add v1.0.0 (822a00c4)

 installed axios@1.5.0


 1 packages installed [14.00ms]
```

### What is the expected behavior?

I expect to get the installed version in package.json, just how npm does it. In this case, Axios 1.5.0 was installed, so I expect to have "^1.5.0" as the version:

```jsonc
{
  // ...
  "dependencies": {
    "axios": "^1.5.0"
  }
}
```

### What do you see instead?

```jsonc
{
  // ...
  "dependencies": {
    "axios": "latest"
  }
}
```

### Additional information

This also happens with `--exact`:

```
bun install axios@latest --exact 
```

**Comment by henrikklee** [comment]
please fix

**Comment by thunfisch987** [comment]
i actually liked this behavior, is there a way i can write the install/add command to do that?
