### ISSUE TITLE
Cannot run puppeteer with a clean browsers cache

### ISSUE THREAD

**Issue by rgl** [oven-sh/bun#4894]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.0-83-generic x86_64 x86_64

### What steps can reproduce the bug?

With an empty cache (`~/.cache/puppeteer` does not exist), after installing the browser using `browsers.install`, we cannot use the browser with `puppeteer.launch`.

You can reproduce the problem with the code at https://github.com/rgl/try-puppeteer-in-bun:

```bash
git clone https://github.com/rgl/try-puppeteer-in-bun.git
cd try-puppeteer-in-bun
bun install --frozen-lockfile
rm -rf ~/.cache/puppeteer
bun run main.js
```

Please note that I'm not adding puppeteer into the `trustedDependencies` `package.json` file. Instead, I'm installation the browser with `browsers.install`.

Please note that the second time `main.js` is executed, all works as expected.

### What is the expected behavior?

Expected it to launch the just installed browser.

### What do you see instead?

It fails with:

```
2023-09-09T14:17:43.077Z Downloading the browser Chrome/116.0.5845.96...
2023-09-09T14:17:49.732Z Launching the browser...
610 |   }
611 |   get stdio() {
612 |     return this.#stdioObject ??= this.#createStdioObject();
613 |   }
614 | 
615 |   spawn(options) {
                 ^
ESRCH: No such process
 syscall: "open"
   errno: -3

      at spawn (node:child_process:615:14)
      at node:child_process:2:40
      at new Process (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:104:31)
      at launch (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:58:11)
      at /home/vagrant/Projects/try-puppeteer-in-bun/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:60:31
      at processTicksAndRejections (:1:2602)
```

### Additional information

This is related to:

1. https://github.com/puppeteer/puppeteer/issues/10867
2. https://github.com/oven-sh/bun/issues/4705

**Comment by rgl** [comment]
This is still broken with bun 1.0.17 as:

```console
vagrant@dm1:~/Projects/try-puppeteer-in-bun$ rm -rf ~/.cache/puppeteer
vagrant@dm1:~/Projects/try-puppeteer-in-bun$ bun run main.js
2023-12-14T09:27:09.382Z Downloading the browser Chrome/119.0.6045.105...
2023-12-14T09:27:15.170Z Launching the browser from /home/vagrant/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome...
 99 |                 }
100 |                 return res;
101 |             }, {}),
102 |             stdio,
103 |         });
104 |         this.#browserProcess = childProcess.spawn(this.#executablePath, this.#args, {
                                     ^
ETXTBSY: Text file busy
   path: "/home/vagrant/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome"
 syscall: "posix_spawn"
   errno: -26

      at spawn (node:child_process:610:15)
      at node:child_process:2:41
      at new Process (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:104:32)
      at launch (/home/vagrant/Projects/try-puppeteer-in-bun/node_modules/@puppeteer/browsers/lib/esm/launch.js:52:12)
      at /home/vagrant/Projects/try-puppeteer-in-bun/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:60:32
      at processTicksAndRejections (:61:77)
vagrant@dm1:~/Projects/try-puppeteer-in-bun$ 

```

**Comment by songpola** [comment]
+1
Tested 1.0.20, still broken.

edit: Got it all working. My problem is just I'm using it in WSL and it was stated here: <https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux>
After following the first step (install Google Chrome in WSL), everything works fine. :D

**Comment by crbon** [comment]
This works now

**Comment by rgl** [comment]
Indeed, I've tried with Bun 1.1.0, and it now works! Thank you!
