### ISSUE TITLE
`bun upgrade` does not appear to use HTTPS_ PROXY？

### ISSUE THREAD

**Issue by FlatMapIO** [oven-sh/bun#49]
I'm in China. I run 'bun upgrade' to show that the download is slow and the transmission is interrupted

![image](https://user-images.githubusercontent.com/1720349/139774781-15abb9cc-5692-4363-8004-bec5ca2b1525.png)

**Comment by Jarred-Sumner** [comment]
Oh no. I did think about proxies for this case, but I didn't know how exactly people use them.

I guess `GITHUB_API_PROXY` is probably useless then and it should be `HTTPS_PROXY` instead and use `CONNECT`

<img width="526" alt="CleanShot 2021-11-01 at 19 56 48@2x" src="https://user-images.githubusercontent.com/709451/139779551-1accb326-ba05-497e-85a1-49ae43670425.png">

For now, you could try downloading the binary manually or re-running the install script. It does almost the exact same thing as `bun upgrade`

**Comment by Electroid** [comment]
We will fix this, tracking in #1440
