### ISSUE TITLE
http client causes deadlocks

### ISSUE THREAD

**Issue by FinnRG** [oven-sh/bun#490]
This is a tracking issue for http client concurrency issues. These issues can cause bun to get stuck while installing packages. 
Most of the time these issues can be resolved by restarting the installation process.

Issues that are caused by the http client:

- #481 
- #426
- #469
- (possibly) #438
- #390
- #291

Other possibly related issues:
- #337
- #292

**Comment by Jarred-Sumner** [comment]
This should be fixed as of Bun v0.1.12. If you run into freezing/hanging when sending HTTP requests, please comment and I'll reopen
