### ISSUE TITLE
Preinstall not called before try to install and collect packages information

### ISSUE THREAD

**Issue by alexander-schranz** [oven-sh/bun#4914]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a79

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

If you are using local dependencies which are only available after calling `preinstall` bun will fail.

e.g.:

```
    "scripts": {
        "preinstall": "node ./preinstall.js",
        "postinstall": "node ./postinstall.js"
    },
    "dependencies": {
        "local-package-available-after-preinstall": "file:../some/local/path"
    }
```

### What is the expected behavior?

First call the `preinstall` script before try todo the `install`.

### What do you see instead?

```
bun install v1.0.0 (822a00c4)


error: MissingPackageJSON


note: error occured while resolving local-package-...
```

```
error: FileNotFound installing local-package-...
```

### Additional information

Following works:

```
bun run preinstall
bun install
```

**Comment by mryraghi** [comment]
Same here.

I use `preinstall` to populate a $VAR, which is then used in 'bunfig.toml', and it seems it is also currently not working (#4901).

**Comment by gvilums** [comment]
As of 1.1.7 this is implemented.

**Comment by mryraghi** [comment]
It still doesn't work in 1.1.7.

``` bunfig.toml
# bunfig.toml
[install]
registry = "https://registry.npmjs.org"

[install.scopes]
"@company" = { url = "https://etc.amazonaws.com/npm/packages/", token = "$CODEARTIFACT_AUTH_TOKEN" }
```

`preinstall`: `export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain receiptor-ai --region eu-west-3 --query authorizationToken --output text)`

**Comment by dylan-conway** [comment]
@mryraghi `preinstall` does not run before package installation. Instead it runs before the `install` script, which runs after installation. See https://github.com/npm/cli/issues/2660#issuecomment-794415767. It looks like `npm` plans on addressing this in the future, most likely with more lifecycle hooks (maybe https://github.com/npm/rfcs/pull/403)

**Comment by mryraghi** [comment]
Gotcha—thanks for clarifying.

However, I get into this issue even when installing. Sometime it works, sometime it doesn't. It's a nightmare...
