### ISSUE TITLE
[Build compile] (Regression) can no longer compile projects using node built-ins in v1.0

### ISSUE THREAD

**Issue by A-D-E-A** [oven-sh/bun#4918]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Write the following file `program.ts`

```ts
// Either import or require
import a from "node:events";
// Can reproduce with "fs", "events", "path". I have not tested other modules. 
console.log(a);
// The log is there just to show an output and avoid removal of the import.
```

Then, run the following command
```sh
bun build program.ts --compile --outfile program --target="bun"
```

And try to run the executable
```
./program
```

### What is the expected behavior?

```sh
> ./program
[Function: EventEmitter2]
# Or whatever module you tested
```

### What do you see instead?

```sh
> ./program


error: FileNotFound reading "node:events"

```

### Additional information

It works under 0.8.1 (0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366).

**Comment by CollinCashio** [comment]
I am experiencing this same issue

**Comment by srsholmes** [comment]
Linking this issue as it is the same thing

https://github.com/oven-sh/bun/issues/4592

**Comment by A-D-E-A** [comment]
@srsholmes My bad, I did not see your issue and that it talked about the same problem.
I'll let mine open for now, but it will probably be closed as duplicate soon.

**Comment by srsholmes** [comment]
@A-D-E-A no problem. To be honest your title is better than the other issue. Keep it open, it gives better visibility of the issue. 👍

**Comment by A-D-E-A** [comment]
It seems that #5102 fixes the issue. Thanks, @Jarred-Sumner! I hope v1.0.1 will drop soonish.
