### ISSUE TITLE
bun plus100 ffi crash

### ISSUE THREAD

**Issue by littledivy** [oven-sh/bun#492]
To reproduce on apple arm64:
```
cd bench/ffi/plus100
bun setup
bun ./plus100.bun.js
```

![image](https://user-images.githubusercontent.com/34997667/178105337-bec65b25-a660-47eb-981e-def57f74600f.png)

**Comment by Jarred-Sumner** [comment]
If you rebuild the dylib does it still happen?

having trouble reproducing this

<img width="800" alt="image" src="https://user-images.githubusercontent.com/709451/178105534-16f2c516-1b52-4c37-8bc0-21fb33b5d258.png">

**Comment by littledivy** [comment]
Yeah

![image](https://user-images.githubusercontent.com/34997667/178105615-a2cde4ea-e301-47db-9c66-fe57da3bf292.png)

**Comment by Jarred-Sumner** [comment]
could be mitata / parent node modules

try `bun install` on the parent directory

**Comment by littledivy** [comment]
removing node_modules and reinstalling mitata worked.
