### ISSUE TITLE
Bun install crashes with "Package name mismatch" when package name differs from name in npm

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [oven-sh/bun#4925]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I have an internal private package repository package where for reasons of consistency the _name_ field inside of the package.json doesn't exactly match what it is in the repository.

### What is the expected behavior?

Though the package name is inconsistent and I will take that up with the team, this definitely shouldn't cause a segfault and is handled correctly in node/yarn

### What do you see instead?

uh-oh: internal: package name mismatch expected "@magnopus-opensource/connected-spaces-platform.web" but received "connected-spaces-platform.web"
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.0 (822a00c4) macOS Silicon 22.6.0
InstallCommand: dotenv bunfig 
HTTP: 165
Elapsed: 1335ms | User: 222ms | Sys: 474ms
RSS: 0.39GB | Peak: 0.39GB | Commit: 0.61GB | Faults: 387
----- bun meta -----

0   0x106aaa624 WTFGetBacktrace
1   ??? Bun__crashReportDumpStackTrace

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

**Comment by gareth-uk** [comment]
I'm also getting this issue.
