### ISSUE TITLE
Request constructor is not extending properties

### ISSUE THREAD

**Issue by nunofgs** [oven-sh/bun#4929]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Run this:

```
const request = new Request('https://google.com', { method: 'POST' });
const another = new Request(request, { body: 'hi' });

console.log('request method before', request.method);
console.log('request method after', another.method);
```

### What is the expected behavior?

This is what you get if you run: `node file.js`

```
request method before POST
request method after POST
```

### What do you see instead?

This is what you get if you run: `bun file.js`

```
request method before POST
request method after GET
```

**Comment by Jarred-Sumner** [comment]
Fixed in Bun v1.0.1
