### ISSUE TITLE
 Express+Apollo server with bun: Failed to construct 'Request': Invalid URL "/" 

### ISSUE THREAD

**Issue by TreeOfLearning** [oven-sh/bun#4947]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

My project uses Express and Apollo server to provide a GraphQL API. With Bun, requests to the server are failing. Here's how I'm constructing and running the server:

```
const app = express();

const apolloServer = new ApolloServer({
  schema,
  context: (ctx) => contextFactory(ctx),
  plugins: [
    {
      requestDidStart: async () => {
        return {
          willSendResponse: ClearContainerCallback,
        };
      },
    },
  ],
  introspection: process.env.NODE_ENV !== "production",
});

(async () => {
  await apolloServer.start();

  apolloServer.applyMiddleware({ app, path: "/graphql" });

  const port = parseInt(process.env.PORT ?? "4000");

  app
    .listen(port, () => {
      console.log(`🚀 API ready at http://localhost:${port}/graphql`);
    })
    .on("error", (err) => {
      console.error(err);
    });
})();
```

### What is the expected behavior?

Everything should *just work*. When I run with node requests succeed and are responded to. 

### What do you see instead?

When running with Bun (`bun --watch ./src/main.ts`, I get the following error in the terminal with each request:

```
Error: Failed to construct 'Request': Invalid URL "/"
    at Request (native)
    at convertNodeHttpToRequest (/Users/***/repositories/backend/node_modules/apollo-server-core/dist/nodeHttpToRequest.js:16:8)
    at <anonymous> (/Users/***/repositories/backend/node_modules/apollo-server-express/dist/ApolloServer.js:81:58)
    at handle (/Users/***/repositories/backend/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:288:13)
    at process_params (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:349:6)
    at next (/Users/***/repositories/backend/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (/Users/***/repositories/backend/node_modules/body-parser/lib/read.js:137:3)
    at runInAsyncScope (node:async_hooks:144:18)
    at invokeCallback (/Users/***/repositories/backend/node_modules/raw-body/index.js:237:31)
    at done (/Users/***/repositories/backend/node_modules/raw-body/index.js:229:13)
    at onEnd (/Users/***/repositories/backend/node_modules/raw-body/index.js:286:23)
    at emit (native)
    at endReadableNT (node:stream:2387:27)
    at processTicksAndRejections (:1:1302)
```

The requests never complete: when the error occurs, it never responds to the request. This is at odds with the behaviour I see with node, where even if an error should occur, a response is still sent to the client if possible. 

### Additional information

Apollo server version: `3.10.3`

**Comment by benwyrosdick** [comment]
I am seeing the same thing.

```
apollo-server-express@3.12.1
express@4.18.2
bun@1.0.0
```

**Comment by abrowne2** [comment]
Also seeing the same thing, not sure if there's a fix available atm

**Comment by TreeOfLearning** [comment]
Yeah, this is still an issue for us on 1.0.3

**Comment by Tjerk-Haaye-Henricus** [comment]
Same here

**Comment by akashgreninja** [comment]
So its just with bun.js is it ?

**Comment by TreeOfLearning** [comment]
> So its just with bun.js is it ?

Yes. With respect, I wouldn't have opened an issue in this repository otherwise.

**Comment by fdaciuk** [comment]
Same error here. Bun revision: 1.0.21+837cbd60d

**Comment by Ryiski** [comment]
I've got the similar error on `"apollo-server-express": "^3.11.1"`, after moving to the new [expressmiddleware](https://www.apollographql.com/docs/apollo-server/api/express-middleware#expressmiddleware), the error is no longer there

**Comment by Electroid** [comment]
If you upgrade Bun using `bun upgrade --canary`, this issue should be fixed.

**Comment by 0xadri** [comment]
Thx @Ryiski ,  I had this issue when using `"apollo-server-express": "^3.11.1"` along with `"express": "^4.17.1"` and `"@types/express": "^4.17.13"`. Moving to the new [expressmiddleware](https://www.apollographql.com/docs/apollo-server/api/express-middleware#expressmiddleware) solved the issue.

Details:
1. Install new packages
```
npm uninstall apollo-server-express apollo-server-core
npm install @apollo/server graphql body-parser
npm install @as-integrations/express4
```
2. Update GraphQL Server Setup
Replace this:
```
import { ApolloServer } from 'apollo-server-express'
import { ApolloServerPluginLandingPageGraphQLPlayground } from 'apollo-server-core'

```
With this:
```
import { ApolloServer } from '@apollo/server'
import { expressMiddleware } from '@as-integrations/express4'
import bodyParser from 'body-parser'
```
3. Update Apollo Server Integration
Replace this:
```
const server = new ApolloServer({
    schema: schemaWithResolvers,
    plugins: [ApolloServerPluginLandingPageGraphQLPlayground()]
})
await server.start()
server.applyMiddleware({ app })
```
With this:
```
const server = new ApolloServer({
    schema: schemaWithResolvers
})
await server.start()
app.use(
    '/graphql',
    bodyParser.json(),
    expressMiddleware(server)
)
```
