### ISSUE TITLE
[Bug] Trying running bun not foun

### ISSUE THREAD

**Issue by NotZer0Two** [oven-sh/bun#495]
i didn't had the sde after installing bun stopped working and say [tid:12200] bun : No such file or directory

**Comment by FinnRG** [comment]
@NotZer0Two  Could you give use more information? What is your computer architecture/OS? Are you using the latest version (v0.1.2)? Does your CPU support AVX2?  What are you trying to run? And please give use a complete error log.

**Comment by NotZer0Two** [comment]
> @NotZer0Two Could you give use more information? What is your computer architecture/OS? Are you using the latest version (v0.1.2)? Does your CPU support AVX2? What are you trying to run? And please give use a complete error log.

Os: Linux mint Amr64 20.03 
Latest: yes
No my cpu doesn't support it but i used an installer provided in other issues

error: 
purpletwo@PurpleTwoOS:~$ bun
[tid:17655] bun : No such file or directory

**Comment by FinnRG** [comment]
@NotZer0Two Is bun in your PATH?

**Comment by NotZer0Two** [comment]
what you mean by path when i installed the first time i did export 
export BUN_INSTALL="/home/purpletwo/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

**Comment by NotZer0Two** [comment]
my bad lol now works
