### ISSUE TITLE
Path parse breaks on Polish characters

### ISSUE THREAD

**Issue by kszpakowski** [oven-sh/bun#4954]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

bun run test.js

```js
import { parse } from "path"
const filePath = '/test/Ł.txt'
console.log(parse(filePath).dir)
# Outputs random characters like "P3/test", "P\)3/test"
```

### What is the expected behavior?

When run with node the output is correct
"/test"

### What do you see instead?

random characters like "P3/test", "P\)3/test"

**Comment by Hanaasagi** [comment]
If the output is different every time, it might be a memory issue. Perhaps this problem will be addressed in https://github.com/oven-sh/bun/pull/5067.

**Comment by davidmhewitt** [comment]
#5067 unfortunately doesn't fix this issue. I've opened #5083 with a failing test case and a possible solution.
