### ISSUE TITLE
module.parent api doesn't work

### ISSUE THREAD

**Issue by kszpakowski** [oven-sh/bun#4955]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

When using pdf-parse module

```js
import pdf from "pdf-parse";
```

it runs debug code because module.parent function does not return parent module

```js
# node_modules/pdf-parse/index.js
let isDebugMode = !module.parent; 
```

### What is the expected behavior?

module.parent should return parent module when module is imported

### What do you see instead?

module.parent returns undefined

**Comment by veryeasily** [comment]
I am having this issue also, and it is causing my server to exit/crash when I import `spritesheet-js` cause of this line:

https://github.com/krzysztof-o/spritesheet.js/blob/fa8411dcab0744286fbbd40a3b0fe013c7d54cb5/index.js#L26

**Comment by kszpakowski** [comment]
@Jarred-Sumner unfortunately it sitll doesn't work with bun 1.0.3 with your fix :(
<img width="634" alt="image" src="https://github.com/oven-sh/bun/assets/13149504/40a60724-27fd-42fb-9834-1fdbd4212a4d">

**Comment by falkenhawk** [comment]
still breaks on bun v1.1.0

**Comment by ilearnio** [comment]
Same error with Bun.
CC: @Jarred-Sumner

**Comment by Jarred-Sumner** [comment]
At the time this issue was created, Bun didn't support `module.parent` and it does at the time this issue was closed.

The rest of this is a bug in the library. They should use `require.main` instead of `!module.parent` to know if it's the entry point. 

Node produces a similar error.

```ts
❯ bun pd.js
10 | 
11 | //for testing purpose
12 | if (isDebugMode) {
13 | 
14 |     let PDF_FILE = './test/data/05-versions-space.pdf';
15 |     let dataBuffer = Fs.readFileSync(PDF_FILE);
                             ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "./test/data/05-versions-space.pdf"

      at /private/tmp/mod/node_modules/pdf-parse/index.js:15:25

Bun v1.1.19 (macOS arm64)
```

```ts
❯ node pd.js
node:fs:573
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open './test/data/05-versions-space.pdf'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at Object.<anonymous> (/private/tmp/mod/node_modules/pdf-parse/index.js:15:25)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at cjsLoader (node:internal/modules/esm/translators:318:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './test/data/05-versions-space.pdf'
}

Node.js v22.3.0
```
