### ISSUE TITLE
Fix `bin` not adding to path with `bun install`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#4962]
When an npm package has files added to `bin`, it sometimes does not add it to PATH.

For example:
```sh
❯ bun install pm2
bun add v1.0.0 (822a00c4)

 installed pm2@5.3.0 with binaries:
  - pm2
  - pm2-dev
  - pm2-docker
  - pm2-runtime


 151 packages installed [830.00ms]
```
```sh
❯ pm2
fish: Unknown command: pm2
```

Then, when I tried again, there was a segfault.
```sh
❯ bun install pm2
bun add v1.0.0 (822a00c4)
fish: Job 1, 'bun install pm2' terminated by signal SIGSEGV (Address boundary error)
```

After more attempts, it did not segfault, but the `bin` still did not appear in path.

**Comment by elendil7** [comment]
Can confirm this bug exists.

**Comment by vflorio** [comment]
I'm not sure if this is related or if a new issue should be opened, but when it comes to Dockers (Alpine and Debian),  adding a global package results in no errors but no bins availables

Example:
RUN bun add -g serve
RUN bun install
RUN bun run build

CMD ["serve", "-s", "build"] // --> error: script not found "serve"

Meanwhile, on Ubuntu WSL paths are updating correctly.

which serve --> /home/[USERNAME]/.bun/bin/serve

**Comment by ottodevs** [comment]
I added this to my `.zshrc`, I guess it should be similar with `.bashrc` or others:

```sh
# bun
export BUN_HOME="$HOME/.bun"
export PATH="$BUN_HOME/bin:$PATH"
```

then reopen the terminal and boom! global binaries in path...

I think this solution is on par with other node tools like `pnpm` or `volta` requiring exactly the same mechanism to put their stores in path.

EDIT: refined my answer after trying the solution myself.

**Comment by Nedi11** [comment]
Confirm, @shopify/plugin-cloudflare has a bin dir, does not add it to node_modules

**Comment by soundstep** [comment]
Same issue with an existing NextJS 12 project. Bin directory missing `next`:

<img width="227" alt="Screenshot 2023-09-21 at 09 46 27" src="https://github.com/oven-sh/bun/assets/133293/31679a6e-0fff-4ab1-add6-81506c9d700a">

With pnpm:

<img width="248" alt="Screenshot 2023-09-21 at 09 47 55" src="https://github.com/oven-sh/bun/assets/133293/2ceadf10-ec3b-4f37-abb9-b6dcdf0b3b84">

**Comment by kacperwyczawski** [comment]
I have the same problem

**Comment by haidarabdillah** [comment]
seem bun still error with pm2, so maybe not relate for production with pm2

**Comment by Jarred-Sumner** [comment]
We can add a warning when bun install's binaries globally and bun's global bin folder is not in `$PATH`, but it is expected behavior that one runs `bun pm2` in a situation like the above, where it wasn't installed globally. 

If you run into this issue yourself, please add `$BUN_INSTALL/bin` to `$PATH`:
```bash
# Either this:
export PATH=$PATH:$HOME/.bun/bin

# Or:
export PATH=$PATH:$BUN_INSTALL/bin
```

Another option is to add `./node_modules/.bin` to `$PATH`, but then you can't use `--bun` to override it with node.

**Comment by rochdev** [comment]
Reproduction code: https://github.com/rochdev/bun-prisma-client-no-bin-repro
Reproduction output: https://github.com/rochdev/bun-prisma-client-no-bin-repro/actions/runs/18734007042/job/53437002993
