### ISSUE TITLE
BunFile.slice() incorrect on macOS

### ISSUE THREAD

**Issue by tryggvil** [oven-sh/bun#4963]
### What version of Bun is running?

1.0.0+51d3d4382281f789f8175079ed426a63529eb3e7

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

BunFile.slice does not handle begin parameter correctly, on macOS.

```
const blb = new Blob(["contents"]);
const blbSlice = blb.slice(2, blb.size);
const blActualContents = await blbSlice.text();
console.log("blob actualContents:", blActualContents);

const filData = `contents`;
await Bun.write("contents.txt", filData);

const fil = Bun.file("contents.txt");
const filSlice = fil.slice(2, fil.size);
const filActualContents = await filSlice.text();
console.log("file actualContents:", filActualContents);

```
on macOS output is:

```
blob actualContents: ntents
file actualContents: conten

```
This seems to correctly implemented on Linux.

### What is the expected behavior?

Expected output from the above code should be:

```
blob actualContents: ntents
file actualContents: ntents
```

### What do you see instead?

```
blob actualContents: ntents
file actualContents: conten

```

**Comment by Jarred-Sumner** [comment]
Fixed by @cirospaciari in https://github.com/oven-sh/bun/pull/4991/files
