### ISSUE TITLE
Segmentation Fault when using await req.formData()

### ISSUE THREAD

**Issue by JawadAhbab** [oven-sh/bun#4966]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
Bun.serve({
  port: 4000,
  fetch: async (req) => {
    const data = await req.formData() // breaks at random data
    console.log(data)
    return new Response()
  }
})
```

### What do you see instead?

```text
FormData {
  "text": "lorem",
  "music": Blob (22.86 MB)
}
zsh: segmentation fault
```

**Comment by akx** [comment]
I can repro this with a file full of random data too, on 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983 (Darwin 22.6.0 arm64 arm):

```javascript
Bun.serve({
    port: 4000,
    fetch: async (req) => {
        await req.formData();
        return new Response();
    }
})
```

```
$ dd if=/dev/urandom of=foo bs=1M count=50
$ curl -vvv -XPOST -F uuu=@foo http://localhost:4000
```
and `bun` SIGSEGVs.
10485954 bytes works ok, 16777410 doesn't.

**Comment by akx** [comment]
Okay, actually, I can trigger a SIGSEGV somewhat randomly with
```fish
for i in (seq 1 5 16000); echo $i; dd if=/dev/urandom bs=1K count=$i 2>/dev/null | curl -sf -XPOST -F uuu=@- http://localhost:4000 || break; end
```
(fish shell syntax, sorry)

* that will first appear to run fine for a long while with larger and larger uploads (though Bun steadily leaks memory)
* if you re-try, it crashes (for me anyway) at e.g. 71 kb of upload.

By changing the `seq` step to `500`, I seem to trigger a crash at 15001 or 15501 kb.
