### ISSUE TITLE
Segmentation fault when using bun test

### ISSUE THREAD

**Issue by niklasarnitz** [oven-sh/bun#4971]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

1. Create the following function:
```typescript
function delay(callback: () => void, delayTime = 100, timeout: NodeJS.Timeout | null = null) {
	if (delayTime === 0) {
		callback();
		return timeout;
	} else {
		if (timeout != null) {
			clearTimeout(timeout);
		}
		return setTimeout(callback, delayTime);
	}
}
```

2. Write some tests for that function:
```typescript
test('helper delay timeout', () => {
	return new Promise<void>((resolve, reject) => {
		const timeout = setTimeout(() => reject(Error('this timeout should not run!')), 100);
		delay(
			() => {
				resolve();
			},
			50,
			timeout
		);
	});
});

test('helper delay called immediately', () => {
	let called = false;
	delay(() => {
		called = true;
	}, 0);
	expect(called).toBe(true);
});
```

### What is the expected behavior?

Runs the tests correctly

### What do you see instead?

```bash
bun test              
bun test v1.0.0 (822a00c4)
[0.06ms] ".env"

__tests__/helper.test.ts:
[1]    88073 segmentation fault  bun test
```

**Comment by nektro** [comment]
this no longer reproduces on Bun 1.0.23. please followup if this still fails for you.

<img width="570" alt="image" src="https://github.com/oven-sh/bun/assets/5464072/e5643676-6d06-4adb-be5f-c769cf2d4a2a">
