### ISSUE TITLE
bunx --bun astro dev not working

### ISSUE THREAD

**Issue by linocz1** [oven-sh/bun#4972]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 588c084220b1 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### What steps can reproduce the bug?

Hi, I use bun x create a astro project, but use bunx --bun astro dev  output error.

like this:
<img width="922" alt="截屏2023-09-12 00 23 00" src="https://github.com/oven-sh/bun/assets/129479296/7909a338-608b-473c-a7f0-20cd979e6764">

<img width="862" alt="截屏2023-09-12 00 25 07" src="https://github.com/oven-sh/bun/assets/129479296/e1508e08-49cc-4c5c-8486-d71d025ceb6a">

**Comment by linocz1** [comment]
same.  bun x --bun astro dev not working
just bun dev working

**Comment by kanashimia** [comment]
First problem is that on your system bunx symlink doesn't exist for some reason, as you can clearly see if you try to read the error message, either your bun installation is incorrect or bunx symlink is broken, show the output of `ls -la /tmp/bun-node`

Second problem is a problem with your usage of `bun x`, `bun --bun x astro dev` would work.
That is pretty weird in how it works, `bun -b x` won't work for example, I will open a separate issue for it.

**Comment by linocz1** [comment]
> First problem is that on your system bunx symlink doesn't exist for some reason, as you can clearly see if you try to read the error message, either your bun installation is incorrect or bunx symlink is broken, show the output of `ls -la /tmp/bun-node`
> 
> Second problem is a problem with your usage of , would work. That is pretty weird in how it works, won't work for example, I will open a separate issue for it.`bun x``bun --bun x astro dev``bun -b x`

Sorry, I forgot to mention that I started the project following the steps in the tutorial at https://bun.sh/guides/ecosystem/astro.

Here is a screenshot of my attempt.

<img width="506" alt="截屏2023-09-12 09 38 56" src="https://github.com/oven-sh/bun/assets/129479296/78f12a78-4ad6-4002-8b1d-3167d9ebf9a1">

<img width="577" alt="截屏2023-09-12 09 52 12" src="https://github.com/oven-sh/bun/assets/129479296/d53182bd-e113-4c3c-a0d4-07efec76d5aa">

If you need me to provide any other results, please let me know. Thank you.

**Comment by kanashimia** [comment]
Ah, sorry, I wrongly asked for the `ls -la /tmp/bun-node` output. 

Anyways the problem with `bunx` is the duplicate of this issue: https://github.com/oven-sh/bun/issues/4598, when you installed bun needed bunx symlink wasn't created and added to the `$PATH`.
And again, `bun x --bun` won't work, use `bun --bun x` instead, `bun x` and `bunx` behave differently with flags, `bun x --bun astro dev` tries to run `astro --bun dev`, astro doesn't have `--bun` argument and shows help menu instead.

I suggest asking for help on the discord instead, it is better suited for this.

**Comment by linocz1** [comment]
Ok, Thank's

**Comment by AimForNaN** [comment]
When I run `bunx --bun astro dev` I get the following error:

```sh
Node.js v18.15.0 is not supported by Astro!
Please upgrade Node.js to a supported version: >=18.14.1
```

Apart from the error message being ironic, I have Node v20.7.0 and Bun v1.0.3 installed on my machine.

**Comment by paperclover** [comment]
process.version in bun used to report this old number, it now reports v20.8.0. i linked this issue in my pr but it is actually something else, this was already fixed a while ago
