### ISSUE TITLE
Unknown option `--bun`

### ISSUE THREAD

**Issue by mdasifmunshe** [oven-sh/bun#4974]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.0-83-generic x86_64 x86_64

### What steps can reproduce the bug?

I was trying the [Build a frontend using Vite and Bun](https://bun.sh/guides/ecosystem/vite).
According to the document
//package.json
Attempt 1:
"scripts": {
  "dev": "bunx --bun vite",
  "build": "vite build",
  "serve": "vite preview"
},

Attempt 2:
"scripts": {
  "dev": "bun x --bun vite",
  "build": "vite build",
  "serve": "vite preview"
},

I know it has not been heavily optimized, nor has Vite been adapted to use Bun's bundler, module resolver, or transpiler.
But maybe fixing this initial issues might save some headache.

### What is the expected behavior?

**VITE** v4.x.x ready in 100ms
-> Local:   http://localhost:5173/

### What do you see instead?

Attempt 1 Result:
bunx: comand not found

Attempt 1 Result:
CACError: Unknown option `--bun`

### Additional information

Possible Fix for "dev":
//package.json
"scripts": {
  "dev": "bun x vite",
  "build": "vite build",
  "serve": "vite preview"
},

**Comment by birkskyum** [comment]
The flag can be set like this: `bun --bun x vite`

**Comment by rotu** [comment]
> The flag can be set like this: `bun --bun x vite`

That seems to work for me. And similar for `bunx cowsay moo` versus `bun --bun x cowsay moo`.

I got this after installing with `proto` and I'm not sure if this is a bun or proto problem.
@mdasifmunshe how did you install bun? Is `bunx` a shell script or a symlink (or something else)?

**Comment by paperclover** [comment]
linked PR will fix this

<img width="1228" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/ce532414-39bc-44c8-b79d-69fa29b0961e">
