### ISSUE TITLE
bun server crashes when returning very specific limit of data

### ISSUE THREAD

**Issue by japhex** [oven-sh/bun#4982]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

We previously had a node server running tsx which was fine, we changed it to bun and we're getting 1 very specific and strange scenario.

We use **sequelize** to connect to a **postgres DB** on **Azure**, when we query any tables and produce over around **246** rows of results, the server hangs instantly. Up to that number we receive results within 30ms...

- if we run the generated sequelize query directly against the DB it works absolutely fine in 0.03s.
- if we run the server against a local postgres DB its also absolutely fine.

Which points to the Azure DB, but like I said we don't have any issues at all running with node.

libraries and versions:

@apollo/server: ^4.9.0
express: ^4.18.2
pg: ^8.11.3
pg-hstore: ^2.3.4
sequelize: ^6.33.0

### What is the expected behavior?

Expected behaviour is for responses containing more than 246 records to be returned like normal.

### What do you see instead?

No error or console output at all, the SQL statement gets printed as it is started and then the server completely hangs until being force stopped.

### Additional information

I can't think of anything, but would like to say in advance thank you **very** much for your time, we're super excited about using bun, especially in production so really hoping we can get to the bottom of this.

**Comment by japhex** [comment]
Similarly if I reduce the complexity of the query and increase the LIMIT on the SELECT clause, it also works but again, only up until a certain point. I can then query for 300 records, but 350 still hangs.

It's very strange, its almost like the results are streaming into memory and past a certain point the bun server just hangs...BUT again, if I run this on a local postgres DB not the Azure one, its works absolutely fine.

**Comment by japhex** [comment]
Also - sorry I did think of some info that may be relevant! 

Its an existing express server with an Apollo Server implementation, too. Just in case that makes any difference, I have thought about re-producing this in hono, but as its been fine with a local database instance, have been reluctant!

**Comment by Zwimber** [comment]
You really haven't provided any steps to reproduce this bug

**Comment by japhex** [comment]
> You really haven't provided any steps to reproduce this bug

I didn't really know what to put other than:

- Create a Burstable Azure Cosmos Postrgres DB with 2 vCores, 4GB RAM & 64GB of storage
- Create a table with 5 rows: id, string, string, date, date
- Fille the table with 7,270 rows of data
- Create a node/express application with an Apollo Server and 1 resolver which uses Sequelize to form a query
- Make the query have a where clause that:
-- searches for a Date from one of the date type columns
-- searches for a string from one of the string columns
-- orders by the same date column DESC

Now run the server and call that resolver - you will get a result returned pretty quickly.

- Change the server to be bun instead of node and the query crashes the server unless the SQL query also has a `LIMIT` clause specifying a number less than (in our case) 246.

**Comment by japhex** [comment]
UPDATE: By following activity monitor locally on my mac when making the query, the memory spirals. 

The bun process has a memory leak when making this query, it starts to consume more and more memory from 1GB up to and over 9GB until we kill it. I think bun is leaking somewhere...

**Comment by giga123Z** [comment]
i got same problem

**Comment by MYKEU** [comment]
Seems like this issue is still happening on the latest Bun version - `1.0.6`

**Comment by Jarred-Sumner** [comment]
Can you provide a minimal reproduction? If you can make it easier for us to reproduce this we can likely fix it this week

**Comment by giga123Z** [comment]
> You can check below steps
1. Create a database and a table in postgresql, then init about 100 records in table
2. Use sequelize to connection database
3. excute query Table.findAll({})
after do step 3, cpu of server will hit 100%, then process will be killed
Hope this issue can fix soon!

**Comment by giga123Z** [comment]
> > You can check below steps
> 
> 1. Create a database and a table in postgresql, then init about 100 records in table
> 2. Use sequelize to connection database
> 3. excute query Table.findAll({})
>    after do step 3, cpu of server will hit 100%, then process will be killed
>    Hope this issue can fix soon!

@Jarred-Sumner
