### ISSUE TITLE
Right Hand side of instanceof is not an object

### ISSUE THREAD

**Issue by ManoloTonto1** [oven-sh/bun#4983]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

create a probot for github and try using octocat.

when trying to send a request using octocat the we get a `500` response with this error

this is the code:
```ts
// Your code here
module.exports = (app) => {
  	app.on('pull_request.opened', async (context) => {
		const prLink = context.payload.pull_request.html_url;
		const prNumber = context.payload.pull_request.number;
		const repoName = context.payload.repository.name;
		const createdAt = await parseDateStringToUTCString(
			context.payload.pull_request.created_at
		);

		const firstCommitOfCurrentPullRequestCreatedAt =
			await parseDateStringToUTCString(
				context.payload.pull_request.head.repo.created_at
			);

		const timeSpentCoding = await calculateTimeSpentCoding(
			firstCommitOfCurrentPullRequestCreatedAt,
			createdAt
		);
		// save all the data to the database
		await saveNewPullRequest({
			firstCommitOfCurrentPullRequestCreatedAt:
				firstCommitOfCurrentPullRequestCreatedAt,
			link: prLink,
			pullRequestCreatedAt: createdAt,
			pullRequestNumber: prNumber,
			repoName: repoName,
			timeSpentCoding: timeSpentCoding,
			pullRequestCoAuthors: getPrCoAuthors(
				context.payload.pull_request.requested_reviewers
			),
			pullRequestMainAuthor: context.payload.pull_request.user.login,
		});
		// write the comment inside the PR
		context.octokit.issues.createComment({
			owner: context.pullRequest().owner,
			repo: context.pullRequest().repo,
			issue_number: prNumber,
			body: `## Hey Skripty here!\nI am tracking the time it takes to review and merge this PR!\nThe first commit was created at: ${firstCommitOfCurrentPullRequestCreatedAt}\nThis PR was created at ${createdAt}\n${await formatTimeSpentCoding(
				timeSpentCoding
			)}`,
		});
	});
};
```

### What is the expected behavior?

to run like normal without any errors.

### What do you see instead?

```sh
109 | 
110 |   if (!secretOrPrivateKey && options.algorithm !== 'none') {
111 |     return failure(new Error('secretOrPrivateKey must have a value'));
112 |   }
113 | 
114 |   if (secretOrPrivateKey != null && !(secretOrPrivateKey instanceof KeyObject)) {
                                         ^
TypeError: Right hand side of instanceof is not an object
```

### Additional information

This works fine using node version 16.x.x with `ts-node` but not on any version above. Bun is using by default nodejs version `18.5.0` it would be great if we had the choice to choose the node version to run node stuff on.

**Comment by AaronDewes** [comment]
Per my comment [here](https://github.com/probot/probot/issues/1852#issuecomment-1714383415), this may simply be a bug in Probot, but choosing Node version is a valid feature request.

It would be interesting to know how bun plans to handle breaking changes in Node going forward...

**Comment by Electroid** [comment]
Thanks for reporting this issue! It looks like Bun need to implement [`KeyObject`](https://nodejs.org/api/crypto.html#class-keyobject) in `node:crypto`, which will be tracked here: #5036

**Comment by moshOntong-IT** [comment]
is there any status of this issue

**Comment by AaronDewes** [comment]
> is there any status of this issue

It has been fixed.
