### ISSUE TITLE
`path` property is missing in returned object for `fs.promises.opendir`

### ISSUE THREAD

**Issue by vladfrangu** [oven-sh/bun#4995]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

```
import { opendir } from 'fs/promises'

const dir = await opendir('.');

console.log(dir.path);
```

### What is the expected behavior?

It should log the loaded path for the directory (nodejs seems to just point to whatever is passed into opendir)

### What do you see instead?

`undefined`

**Comment by anru** [comment]
Bug is actual for bun v1.0.11
