### ISSUE TITLE
question: add create-t3-app to bun create-templates?

### ISSUE THREAD

**Issue by polderleo** [oven-sh/bun#500]
While reading the doc, I got stuck on the `bun create` command and was wondering if I could just make a pull request for [create-t3-app](https://github.com/t3-oss/create-t3-app)?

**Comment by travis-wang-v1** [comment]
I tried to implement this but tRPC seems to need more support from Bun

**Comment by FinnRG** [comment]
@polderleo ```bun create``` supports git repos. So you could create a repo ```polderleo/t3-stack-bun``` and everyone could use it with ```bun create polderleo/t3-stack-bun```

**Comment by polderleo** [comment]
@FinnRG yeah, I know about this feature.I just thought it would be great to add this t3 stack as one of the default templates. But to understand the whole thing better, therefore is this question issue:)
