### ISSUE TITLE
Allow passing a different `tsconfig.json` than the default one

### ISSUE THREAD

**Issue by zoominGiladSher** [oven-sh/bun#5000]
### What is the problem this feature would solve?

We have a big application that I would like to migrate to bun at some point. I was thinking about doing it in an incremental way by introducing bun for testing, followed by bun for running the app, followed by bun for bundling.
In order to do that I need my `tsconfig.json` to stay the same and have a different `tsconfig.test.json` that extends the default one but overrides some flags for bun to work as suggested in the documentation.

### What is the feature you are proposing to solve the problem?

I think that adding a way to pass a `tsconfig.json` path instead of assuming that you should always use `tsconfig.json` would be a better solution and (in my humble and not very knowledgable in Zig opinion) not too difficult to implement.
Something like `bun test --tsConfigPath tsconfig.test.json` and/or its equivalent in `bunfig.toml`.

### What alternatives have you considered?

I don't think that there's really a reason to consider anything else here since this should be a rather straight-forward change. Thanks for the awesome job you're doing :)

**Comment by george-of-croton** [comment]
This is already available via the --tsconfig-override flag. use`bun --help` for more info

**Comment by zoominGiladSher** [comment]
Awesome, didn't see this one! Thanks for the quick response!

**Comment by draylegend** [comment]
@george-of-croton `--tsconfig-override flag` doesn't exist in v1.1.29

**Comment by Jarred-Sumner** [comment]
@draylegend it seems to be missing from the --help menu but i believe it does exist, the code is in there
