### ISSUE TITLE
Syntax error: query(`create table foo;`)

### ISSUE THREAD

**Issue by PedroVMota** [oven-sh/bun#5003]
### What version of Bun is running?

1.0

### What platform is your computer?

Linux ubuntu WSL

### What steps can reproduce the bug?

After create the index.ts, I past a 5 line script that will initilize and create a table on a database;

Code:
```Typescript
  import { Database } from "bun:sqlite";
  import { close } from "fs";
  const db = new Database(":memory:");
  const query = db.query(`create table foo;`);
  query.run();
  console.log(query.get());
```

### What is the expected behavior?

By the documentation should create a table will be defined as undefined;

### What do you see instead?

Compilation Error:

pedro@PedroMota:~/OwnProjects/bun$ bun run index.ts
185 |     }
186 |     var arg0 = params[0];
187 |     return !isArray(arg0) && (!arg0 || typeof arg0 !== "object" || isTypedArray(arg0)) ? SQL.run(this.#handle, query, params) : SQL.run(this.#handle, query, ...params);
188 |   }
189 |
190 |   prepare(query, params, flags) {
                     ^
error: near ";": syntax error
      at prepare (bun:sqlite:190:18)
      at query (bun:sqlite:197:14)
      at /home/pedro/OwnProjects/bun/index.ts:6:14

**Comment by PedroVMota** [comment]
I m dumb nevermind

**Comment by dancrtis** [comment]
In case you're like me and google the error without thinking about it first and stumble upon this thread, you have to pass the columns:

```js
const query = db.prepare(`create table cats (name string);`);
```
