### ISSUE TITLE
GitHub Actions bunx --bun vite build error

### ISSUE THREAD

**Issue by serhii-chernenko** [oven-sh/bun#5008]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

ubuntu-latest

### What steps can reproduce the bug?

I've created the previous issue:
https://github.com/oven-sh/bun/issues/4961

It has been fixed, but I have the next error:
```
failed to load config from /home/runner/work/bun/bun/vite.config.ts
error during build:
undefined
error: "vite" exited with code 1 (SIGHUP)
error: script "build" exited with code 1 (SIGHUP)
Error: Process completed with exit code 1.
```

with the same command:
```
"build": "tsc && bunx --bun vite build",
```

when I run
```
vite build
```
everything is fine

### What is the expected behavior?

the command is successfully run via github actions
```
bunx --bun vite build
```

### What do you see instead?

I see the error

**Comment by HobMartin** [comment]
Hey, @serhii-chernenko 
`tsc && bunx --bun vite build` via GitHub actions works for me. Can you check again?

Bun version `1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49`

**Comment by serhii-chernenko** [comment]
yeah, now everything looks fine @HobMartin 
<img width="596" alt="image" src="https://github.com/oven-sh/bun/assets/28815318/4e29a1d4-26d9-46f8-92fb-6173efa9af72">

**Comment by tmuaz** [comment]
if some poor soul managed to navigate here and was using
```Dockerfile
FROM oven/bun:1.2.0-alpine AS base
```
in their dockerfile then just remove the alpine and it will work.
```Dockerfile
FROM oven/bun:1.2.0 AS base
```
