### ISSUE TITLE
`bun create next-app` fails by installing `@next/swc-linux-x64-gnu [224/383]`

### ISSUE THREAD

**Issue by t-kampa** [oven-sh/bun#5009]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

- Open a terminal
- run command: `bun create next-app`

### What is the expected behavior?

It should install all dependencies for a new bun project with next

### What do you see instead?

![Bildschirmfoto 2023-09-11 um 23 16 23](https://github.com/oven-sh/bun/assets/33285857/36b3a527-76b4-4dfc-81f1-f55e7d20d341)

It doesn't continue and stays in this step.

**Comment by t-kampa** [comment]
It worked the second time 🎉

But I'll leave it at that, maybe there really is a bug.

**Comment by SilviaBeatrizRamirez** [comment]
<body>

<form>

<div>

<label for=»user»> Usuario: </label>

<input type=»text» id=»user» required/>

</div>

<div>

<label for=»password»> Contraseña: </label>

<input type=»password» id=»password» required/>

</div>

<button type=»submit»> Login </button>

</form>

<script type=»module» src=»./login/login.js»></script>

</body>

**Comment by dudusotero** [comment]
Here I receive this error:
![image](https://github.com/oven-sh/bun/assets/7073199/a2b7b2aa-abcb-42d3-998f-365ca5ea302a)

The error happens with `bunx create-next-app` and `bun create next-app`

**Comment by deadcoder0904** [comment]
I got this error in my 2 year old next.js project:

```bash
[1.23ms] ".env"
bun install v1.1.2 (c8d072c2)
???:?:?: 0x7ff6e2ceaba6 in ??? (bun.exe)
warn: Could not resolve package '@next/swc-darwin-arm64' in lockfile during migration
warn: Could not resolve package '@next/swc-darwin-x64' in lockfile during migration
warn: Could not resolve package '@next/swc-linux-arm64-gnu' in lockfile during migration
warn: Could not resolve package '@next/swc-linux-arm64-musl' in lockfile during migration
warn: Could not resolve package '@next/swc-linux-x64-gnu' in lockfile during migration
warn: Could not resolve package '@next/swc-linux-x64-musl' in lockfile during migration
warn: Could not resolve package '@next/swc-win32-arm64-msvc' in lockfile during migration
warn: Could not resolve package '@next/swc-win32-ia32-msvc' in lockfile during migration
warn: Could not resolve package '@next/swc-win32-x64-msvc' in lockfile during migration
Error: NotAllPackagesGotResolved
Invalid NPM package-lock.json
In a release build, this would ignore and do a fresh install.
Aborting
```
