### ISSUE TITLE
new Date() doesn't accept valid string

### ISSUE THREAD

**Issue by cbetori** [oven-sh/bun#5010]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

WSL

### What steps can reproduce the bug?

Bun:
new Date('2020-09-21 15:19:06 +00:00') === Invalid Date

Node:
new Date('2020-09-21 15:19:06 +00:00') === 2020-09-21T15:19:06.000Z

This is causing date values returned from sequelize v6.33.0 to be returned as Invalid Date

### What is the expected behavior?

new Date('2020-09-21 15:19:06 +00:00') === 2020-09-21T15:19:06.000Z

### What do you see instead?

new Date('2020-09-21 15:19:06 +00:00') === Invalid Date

### Additional information

Bun doesn't like the space between the time and the timezone offset

**Comment by Electroid** [comment]
Thanks for reporting! This is because the JavaScript engines that are used by Bun and Node -- JavaScriptCore and V8, respectively -- differ in how they parse dates. Regardless, we will fix this in Bun.

**Comment by alekangelov** [comment]
Correct me if im wrong, but I think in order to implement this and not rely on JSC we have to implement the Date class in zig itself? If yes, then I would be down rewrite the date class from spec. Or another hacky way would be to regex it and parse the string before it goes into JSC and do transformations there.

**Comment by Electroid** [comment]
> Correct me if im wrong, but I think in order to implement this and not rely on JSC we have to implement the Date class in zig itself? If yes, then I would be down rewrite the date class from spec. Or another hacky way would be to regex it and parse the string before it goes into JSC and do transformations there.

We can patch/update JSC, and have done so many times before.

**Comment by dylan-conway** [comment]
we will have a fix in our WebKit fork soon
<img width="376" alt="Screenshot 2023-09-13 at 1 37 06 AM" src="https://github.com/oven-sh/bun/assets/35280289/c7f841bd-2094-44e5-b914-802177f2625d">

**Comment by samholmes** [comment]
```js
❯ bun repl
Welcome to Bun v1.0.0
Type ".help" for more information.
> new Date("Sep 09 2022 03:53:45Z")
Invalid Date
>
```

Same issue with this particular date.

**Comment by dylan-conway** [comment]
fixed with https://github.com/oven-sh/WebKit/pull/19
