### ISSUE TITLE
.env empty key is returning true when starting from a script

### ISSUE THREAD

**Issue by guizaodev** [oven-sh/bun#5015]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64
> Using WSL2
>
>> Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

> first of all you need to set a script inside your package.json with "bun index.ts"
> 
> then run it, `bun run start`

index.ts
```typescript
import figlet from "figlet";

const server = Bun.serve({
    fetch() {
      const body = figlet.textSync("IATec Test!");
      return new Response(body);
    },
    port: Bun.env.PORT || 3000,
  });
  
console.log(`Listening on http://localhost:${server.port} ...`);
```

.env
```
IP_ADDRESS='192.168.0.1'
PORT=
```

### What is the expected behavior?

the expected should be:

```sh
$ bun index.ts
[0.01ms] ".env"
Listening on http://localhost:3000 ...
```

### What do you see instead?

but the returned is forwarding to a random port:

```sh
$ bun index.ts
[0.01ms] ".env"
Listening on http://localhost:51379 ...
```

### Additional information

when I run the code using `bun index.ts` everything works pretty well, but if I use the start from the script `bun run start` this error occurs

**Comment by dylan-conway** [comment]
fixed in https://github.com/oven-sh/bun/commit/db8cb7d29f4b4f2950a4821604e982fe3d4f594e. The fix will be available in canary a couple hours after #4630 merges
