### ISSUE TITLE
`bun install` should not run the prepare script of trusted dependencies

### ISSUE THREAD

**Issue by ohana54** [oven-sh/bun#5017]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

Hi,

I encountered an issue with installing `@swc/core` as a trusted dependency.
Bun tries to run its `prepare` script, which fails.

AFAIK, per the npm docs and the behavior of npm/yarn, the `prepare` script should not be run when installing a dependency.
It is intended to be a script for the local dev of that package.

### What is the expected behavior?

`bun install` should not run `prepare` scripts of trusted dependencies.

### What do you see instead?

example failure when installing `@swc/core`:
```
bun install v1.0.0 (822a00c4)
 + @swc/core@1.3.84
/bin/bash: husky: command not found

 3 packages installed [30.00ms]
error: script "prepare" exited with code 127
```

**Comment by Jarred-Sumner** [comment]
definitely a bug

**Comment by nagolyhprum** [comment]
This might not be the solution you are looking for but you can skip life cycle events using  `--ignore-scripts`. I believe this is the line doing it: https://github.com/oven-sh/bun/blob/main/src/install/install.zig#L7955C37-L7955C37.

**Comment by ohana54** [comment]
Thanks, although I actually need to run the postinstall of `@swc/core`.

**Comment by kyleosborn** [comment]
This one is a blocker for us also. We've had issues with swc-loader and bun.sh - I just discovered the trusted-deps however since putting a few in here it's caused a whole host of other problems.

**Comment by martinmckenna** [comment]
yep having this exact issue when converting over my Dockerfile to use bun. This should definitely match what npm and yarn do

**Comment by jpthibault** [comment]
> yep having this exact issue when converting over my Dockerfile to use bun. This should definitely match what npm and yarn do

My docker builds were running smoothly until this merge. 

```
FROM oven/bun:1 as base
ENV NODE_ENV=production
WORKDIR /app
COPY . .
RUN bun install
```
>0.225 bun install v1.0.17 (5e60861c)
8.879 /bin/bash: line 1: node: command not found
8.879 
8.879 error: postinstall script from "@swc/core" exited with code 127
