### ISSUE TITLE
It looks like Bun is ignoring the await statement

### ISSUE THREAD

**Issue by RomaTk** [oven-sh/bun#5020]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create some file _.ts_ with the code below:

```typescript
import { ExecException, exec } from 'child_process'
;(async () => {
    exec('git config --get remote.origin.url', (error, stdout, stderr) => {
        console.log('working one', error, stdout, stderr)
    })
    const { error, stdout, stderr } = await new Promise<{ error: ExecException | null; stdout: string; stderr: string }>((resolve) => {
        exec('git config --get remote.origin.url', (error: ExecException | null, stdout: string, stderr: string) => {
            resolve({ error, stdout, stderr })
        })
    })
    console.log('not working one', error, stdout, stderr)
})()
```
After that run command: 
```console
bun run some-file-name.ts
```

### What is the expected behavior?

```console
working one null https://github.com/.....
not working one null https://github.com/.....
```
or 

```console
not working one null https://github.com/.....
working one null https://github.com/.....
```

### What do you see instead?

```console
working one null https://github.com/.....
```

### Additional information

- It looks like Bun is ignoring the await statement.
- The same code is working differently in Nodejs which means that it is not well compatible with nodeJs packages

**Comment by paul-uz** [comment]
I had to change `remote.origin.url` to `user.name` as I don't have the same config settings as you, however, calling `bun run foo.ts` or `bun foo.ts`, the code doesn't output anything at all.

Looks like you pasted the code slightly wrong, with the `;` being in the wrong place.

I now see the same result as you

**Comment by akx** [comment]
You're not `await`ing your top-level `async` call to finish.

Change 

```
(async () => {
```
to 
```
await (async () => {
```
and it works the same in Bun.

**Comment by RomaTk** [comment]
@akx , I agree that if I add await in the top level, the expected result will be returned.
I am talking about compatible bun to nodeJs. If I run the script using ts-node, the program will not be finished before all operations are completed. While bun does that.

Maybe I showed good example, but here is a new one:
```typescript
import { exec } from 'child_process'
exec('echo Ok', (error, stdout, stderr) => {
    console.log(error, stdout, stderr)
})
```
result in console form Bun:
<img width="129" alt="image" src="https://github.com/oven-sh/bun/assets/18241804/ea0cb708-156b-49a5-9529-6680cadcab0d">
and from ts-node:
<img width="125" alt="image" src="https://github.com/oven-sh/bun/assets/18241804/da519ef8-18e8-4a16-a8e1-6582f35e40e5">

**Comment by akx** [comment]
You're talking about compatibility with _ts-node_, or more broadly with tsc. With plain Node, you couldn't even add the top-level await, since it doesn't support it... 

However, yeah, I suppose dangling callbacks should leave Bun running.

**Comment by nektro** [comment]
does this still reproduce for you? it appears to be working now as of at least Bun 1.1.9 (you may need to run `bun upgrade`)

```
❯ bun-debug index.ts                                  
working one null https://github.com/nektro/test

not working one null https://github.com/nektro/test

```
