### ISSUE TITLE
Transitive/nested dependencies' asterisk (*) version doesn't respect project's specified version or override config

### ISSUE THREAD

**Issue by dulguun0225** [oven-sh/bun#5022]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### How to reproduce
Run `bun install` inside [this project](https://github.com/dulguun0225/asteriskbug)

### Explanation
- This project has `"@types/react": "^16.9.56"` depdendency.
- But its dependency `@types/react-transition-group` has `"@types/react" : "*"` that resolves to latest version 18.
These two different versions of `@types/react` conflict and cause type errors.

### What is the expected behavior?

1. `overrides` configuration should override nested/transitive dependencies' * versions. 
2. Preferably any project dependency should override nested/transitive dependencies' * version (`overrides` config should be unnecessary). Maybe it only makes sense for types only dependencies.

### What do you see instead?

Nested/transitive dependencies' * version overrides project dependencies' versions. Even `overrides` config doesn't work.

**Comment by MikeDombo** [comment]
Same as #4946

**Comment by Zikoat** [comment]
Overrides support is being tracked in #1134

**Comment by Zikoat** [comment]
Possible duplicate: #4642

**Comment by dulguun0225** [comment]
> Overrides support is being tracked in #1134

`overrides` config seems to work if transitive dependency version isn't `*`

**Comment by Jarred-Sumner** [comment]
@dylan-conway can you check if this is still an issue?

**Comment by dylan-conway** [comment]
Fixed in bun v1.0.6
