### ISSUE TITLE
Bun with Vite in HTTPS NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun

### ISSUE THREAD

**Issue by alveshelio** [oven-sh/bun#5026]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Mac Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I have an existing React/Vite App set up with HTTPS
`vite.config.ts`
```ts
server: {
    host: 'localhost',
    https: {
      key: './.cert/appia-ui.key',
      cert: './.cert/appia-ui.crt',
    },
    port: 3000,
  },
```

when I do `bunx --bun vite"` I get this error `NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun`

### What is the expected behavior?

I would expect Bun to work out of the box with Vite.

**Comment by birkskyum** [comment]
- #887

**Comment by alveshelio** [comment]
@birkskyum thanks for getting back. Is there any ETA? I've looked at Bun's roadmap https://github.com/oven-sh/bun/issues/159 but it hasn't been updated in a year.

Thanks

**Comment by birkskyum** [comment]
Think it's coming soon. Was told it's near top of the list
