### ISSUE TITLE
Support installing enterprise Git repositories via SSH

### ISSUE THREAD

**Issue by eliliam** [oven-sh/bun#5027]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.10.0-23-cloud-amd64 x86_64 unknown

### What steps can reproduce the bug?

I am unable to install packages hosted in private enterprise git repositories(specifically in BitBucket). I have tried using the shorthand syntax of `bitbucket:my-company/my-package` as well as every other form of the syntax(i.e. `git@bitbucket.org:my-company/my-package` and `git+ssh://git@bitbucket.org/my-company/my-package`) with the same result. The `--verbose` flag also does not give any more details. 

This seems to be slightly different if using HTTP authentication as it does seem to ask for a password, however the way that my company as well as others are set up, we need to be able to use our SSH keys to authenticate.

### What is the expected behavior?

This is related to #82 and #2464, but adds some additional information and potential solution. With both `npm` and `pnpm` I can specify the repo in a variety of formats, just like the [bun docs](https://bun.sh/docs/cli/install#git-dependencies) show, however it appears that with enterprise repositories(and possibly private repos too, but I haven't tested this one) all of these formats do not work.  

My proposed solution would be that in the case of the public tarball API not returning any results, to instead do a more expensive shallow git clone as a fallback, allowing the use of SSH authentication handled natively by git.

### What do you see instead?

```
$ bun install --verbose
bun install v1.0.0 (822a00c4)
  🔍 Resolving [1/1] 
error: InstallFailed cloning repository for my-package

error: "git clone" for "my-package" failed

error: "git clone" for "my-package" failed
```

**Comment by anand-gopinath** [comment]
Facing the similar errors

<img width="500" alt="Screenshot 2023-09-15 at 4 12 19 PM" src="https://github.com/oven-sh/bun/assets/25955939/beea72af-289e-45d9-b84e-2264e916e362">

<img width="382" alt="Screenshot 2023-09-15 at 4 13 12 PM" src="https://github.com/oven-sh/bun/assets/25955939/92e5a824-7529-4bdf-83e9-016769edd353">

**Comment by h2oearth** [comment]
It seems like this [PR](https://github.com/oven-sh/bun/pull/4528) will unblock us 🤞

**Comment by coolcorexix** [comment]
@h2oearth  I dont think PR #4528 will solve this problem because as in the description it just help change the format of the url with two semicolon.

git+ssh://git@example.com:path/to/repo -> git+ssh://git@example.com/path/to/repo

I changed this manually in my package.json and still have the same problem.

the problem that we are having rn with this issue is unclear and we need someone who know the codebase well enough to pinpoint the root cause and then we can start working from there
