### ISSUE TITLE
bun install incorrectly parses custom registries

### ISSUE THREAD

**Issue by zacowan** [oven-sh/bun#5029]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a `bunfig.toml` file in a project directory
2. Provide a custom registry URL:

```
[install]

registry = "https://www.custom-registry.com/one/two/three/four"
```

3. Attempt to install a package: `bun install react`
4. Note that bun interprets the installation URL in error messages as `www.custom-registry.com/one/two/three/react`, which omits the final part of the URL `four`

### What is the expected behavior?

In the same scenario as above, bun should interpret the installation URL as `www.custom-registry.com/one/two/three/four/react`.

### What do you see instead?

`www.custom-registry.com/one/two/three/react`

**Comment by zacowan** [comment]
Note: adding a trailing slash to the registry URL seems to solve this issue for the specific case outlined above.

**Comment by Jarred-Sumner** [comment]
This was fixed some time ago. We normalize the registry URLs nowadays.

If you're still running into issues like this, please leave a comment and we'll re-open.
