### ISSUE TITLE
fetch response body streams are not cancelable

### ISSUE THREAD

**Issue by ide** [oven-sh/bun#5039]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```js
const response = await fetch('http://example.com');
await response.body?.cancel();
```

The `cancel()` method is not defined on the [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/cancel) body object.

### What is the expected behavior?

`response.body.cancel()` should return a promise.

### What do you see instead?

The error is:
`1 | (function (stream,reason){"use strict";@putByIdDirectPrivate(stream,"disturbed",!0);const state=@getByIdDirectPrivate(stream,"state");if(state===@streamClosed)return @Promise.@resolve();if(state===@streamErrored)return @Promise.@reject(@getByIdDirectPrivate(stream,"storedError"));@readableStreamClose(stream);var controller=@getByIdDirectPrivate(stream,"readableStreamController"),cancel=controller.@cancel;if(cancel)return cancel(controller,reason).@then(function(){});var close=controller.close;if(close)return @Promise.@resolve(controller.close(reason));@throwTypeError("ReadableStreamController has no cancel or close method")})`

### Additional information

The two motivations for this bug are W3C standards compliance and Node.js compatibility. The `cancel()` method is part of the W3C ReadableStream API, and Node/Undici's fetch response bodies implement `cancel()`. Undici actually requires it to [release memory](https://github.com/nodejs/undici#garbage-collection) -- it's much nicer in Bun not to need to manually free memory -- but having a stub method would make it easier to run code written for Node.js in Bun.

**Comment by nektro** [comment]
does this still reproduce for you? it appears to work for me in Bun 1.1.9. (you may need to run `bun upgrade`)

**Comment by ide** [comment]
Appears to work in Bun v1.1.4 too:
```
> const response = await fetch('http://example.com');
> response.body.cancel
[Function: cancel]
```
