### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#504]
I downloaded the latest release and ran the following code on Linux 5.4.0-42-lowlatency

```
#!/usr/bin/env -S ./bun 
console.log('Hello, World!');
```

```
$ ./test.js
```

Result 

```
Illegal instruction (core dumped)
```

**Comment by mikrosystheme** [comment]
Please use the search before posting new issues.

https://github.com/Jarred-Sumner/bun/issues?q=Illegal+instruction

**Comment by FinnRG** [comment]
Duplicate of #67.

**Comment by guest271314** [comment]
I did search first.

Where are instructions for basic usage in the linked issue?

**Comment by guest271314** [comment]
The instructions in #67 don't change anything.
