### ISSUE TITLE
ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by pinkboid** [oven-sh/bun#5048]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```sh
mkdir project && cd project && bun init
```
```sh
bun add reveal.js
bun add -d @types/reveal.js
```
index.ts
```ts
import Reveal from 'reveal.js'

let deck = new Reveal({
    
})
deck.initialize();
```
```sh
bun run index.ts
```

### What is the expected behavior?

Following the npm setup guide for reveal.js [here](https://revealjs.com/installation/#full-setup)

### What do you see instead?

```sh
ReferenceError: Can't find variable: document
      at new Y (/Users/pb/proj/abar/patterns/node_modules/reveal.js/dist/reveal.js:8:67180)
      at /Users/pb/proj/abar/patterns/src/main.ts:3:11
```

### Additional information

tsconfig
```json
{
  "compilerOptions": {
    "lib": ["ESNext", "DOM"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "types": [
      "bun-types"
    ]
  }
}
```
package.json
```json
{
  "name": "project",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "start": "bun run index.ts"
  },
  "devDependencies": {
    "@types/reveal.js": "^4.4.2",
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "reveal.js": "^4.5.0"
  }
}
```

**Comment by AliReza99** [comment]
@pinkboid 
how did you fixed it ?

**Comment by pinkboid** [comment]
@AliReza99 I realized that this bug was not specific to bun but was a result of trying to access the `document` variable before the DOM had been loaded. AFAIK Bun on it's own is a runtime, not integrated with the web, and so doesn't have access to web entities like the `document`.

In order to get it working, you need to make sure that whatever code/library you use that attempts to use `document` is called _after_ DOM stuff has been setup, not before. So maybe only in a script that is called in an `index.html`? I forget exactly what I did to solve it, but that's the gist.
