### ISSUE TITLE
Enable Cloudflare Pages Support for Bun Runtime

### ISSUE THREAD

**Issue by SaucyOfficiale** [oven-sh/bun#5053]
### What is the problem this feature would solve?

Bun is not a supported runtime on Cloudflare Pages. 

### What is the feature you are proposing to solve the problem?

Add Bun runtime for Cloudflare Pages.

**Comment by Electroid** [comment]
Hi there, this is something that the Cloudflare Pages team will have to support. If you experience an issue, please feel free to open another issue.
