### ISSUE TITLE
Compiled code can't load internal node modules. (import `node:fs/promises` gives `error: FileNotFound reading "node:fs/promises"`)

### ISSUE THREAD

**Issue by GingerAdonis** [oven-sh/bun#5055]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.0-76-generic x86_64 x86_64

### What steps can reproduce the bug?

`test.ts` content:
```ts
import {readdir} from 'node:fs/promises';

console.log(await readdir('.'));
```

Command:
```bash
bun build ./test.ts --compile --outfile test && ./test
```

### What is the expected behavior?

Code runs normally and outputs contents of current directory.

### What do you see instead?

```
error: FileNotFound reading "node:fs/promises"
```

### Additional information
- Other internal modules seem to be affected as well. Tried `node:fs` and `node:path` as well.
- Works fine on Bun 0.8.1

**Comment by awilderink** [comment]
The default target for `bun build` is the browser, since `node:fs` and `node:path` are system apis, these do not work in the browser.  Did you try using `--target=bun`?

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/issues/4918 https://github.com/oven-sh/bun/issues/4592

**Comment by GingerAdonis** [comment]
> The default target for `bun build` is the browser, since `node:fs` and `node:path` are system apis, these do not work in the browser. Did you try using `--target=bun`?

Adding `--target=bun` doesn't fix this issue.

> Related to #4918 #4592

Definitely a duplicate, so I'm closing this issue.
