### ISSUE TITLE
package patch support for the package manager

### ISSUE THREAD

**Issue by ChristianRaoulis** [oven-sh/bun#5059]
### What is the problem this feature would solve?

it would allow bun pm users to apply package patches to dependencies without the need to install [patch-package](https://www.npmjs.com/package/patch-package)

### What is the feature you are proposing to solve the problem?

add a similar functionality to [pnpm patch](https://pnpm.io/cli/patch) where you can create and apply package patches to your dependencies

### What alternatives have you considered?

Using pnpm as package manager or patch-package with a postinstall hook

**Comment by sirenkovladd** [comment]
Possibly a duplicate of https://github.com/oven-sh/bun/issues/2336

**Comment by Charismara** [comment]
> Possibly a duplicate of #2336

You're right 👍

**Comment by ChristianRaoulis** [comment]
duplicate of #2336
