### ISSUE TITLE
setInterval() exits the program and does not loop

### ISSUE THREAD

**Issue by kyjus25** [oven-sh/bun#506]
I must be doing something terribly wrong, but creating an `index.js` file with the following code:
```
setInterval(() => {
    console.log('test');
}, 1000);
```
And running `bun index.js`, the interval is only ran once and the application quits. However, running with `node index.js`, the interval loops as expected.

Currently running bun v0.1.2 (latest at the time) on an M1 Macbook Pro (macOS Monterey).

Tested on an Intel Mac also and can confirm it is not only an Apple Silicon issue, but only tested on Mac devices as that is all that I have

**Comment by denniscual** [comment]
`setInterval` works on Ubuntu 20.04.4 LTS.

**Comment by kyjus25** [comment]
@denniscual Awesome, thank you for testing! 🙏

This seems like an issue specific to macOS then

**Comment by akylkb** [comment]
Same on Mojave 10.14.6 AMD

**Comment by crisanmm** [comment]
Doesn't work either on intel mac Monterey 12.4

This also prints once and then quits:

```js
const fn = () => {
  console.log('test');
  setTimeout(fn, 1000);
};

setTimeout(fn, 1000);
```

Reproduction:
```bash
$ node index.js    
test
test
test
test
test
^C
$ bun run index.js
test
$ bun 
```

**Comment by addy** [comment]
I've got the same issue with both `setTimeout` and `setInterval`.

**Comment by ghost** [comment]
> I've got the same issue with both `setTimeout` and `setInterval`.

How would you incur the same error with `setTimeout`? It doesn't loop.

**Comment by addy** [comment]
> How would you incur the same error with `setTimeout`? It doesn't loop.

See @crisanmm's comment, you can recursively call setTimeout to achieve a similar effect to setInterval. It should print every second, but on Mac it does not.

**Comment by addy** [comment]
Currently trying to get Bun compiling on MacOs to take a look at fixing this.

**Comment by kyjus25** [comment]
@addy Thank you for your time looking in to it!

**Comment by AroLeaf** [comment]
I'm on arch linux and getting the same issue, so it may not be macOS only?

**Comment by Skillz4Killz** [comment]
Having the same issues on Linux
