### ISSUE TITLE
[BABEL]: You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously.

### ISSUE THREAD

**Issue by ckken** [oven-sh/bun#5066]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

[BABEL]: You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously.
react-native project

**Comment by ckken** [comment]
```shell
error: index.js: [BABEL]: You appear to be using a native ECMAScript module plugin, which is only supported when running Babel asynchronously. (While processing: /Users/xuhongbin/Desktop/Develop/react-native/rn72FromTemplate/node_modules/babel-plugin-react-native-platform-specific-extensions/index.js)
```

**Comment by Electroid** [comment]
We'll need some code or commands to reproduce this issue. If you are able to, let us know and we'll re-open this issue and investigate.
