### ISSUE TITLE
bun test doesn't do tests

### ISSUE THREAD

**Issue by lucasew** [oven-sh/bun#507]
I know that this might be a missing feature that is WIP or something like that, but tests are not working yet on 0.1.2.

## How to replicate the issue
- Clone this repo
- cd into `test/bun.js`
- try to `bun run` any file that ends with `.test.js`
- with the problem, bun will give a error like this:
```
(shell:impure) lucasew@acer-nix ~/WORKSPACE/bun/test/bun.js 0$ bun atob.test.js 
1 | var { expect, it } = globalThis.Bun.jest(import.meta.path);
   ^
 error: Run bun test to run a test
      at /home/lucasew/WORKSPACE/bun/test/bun.js/atob.test.js:1:0
```
- try to run with `bun test $thatfile` and you will get an error like this:
```
(shell:impure) lucasew@acer-nix ~/WORKSPACE/bun/test/bun.js 0$ bun test atob.test.js 
error: Script not found "test"
```

**Comment by FinnRG** [comment]
@lucasew Testing is still WIP. Please try ```bun wiptest```.

**Comment by Jarred-Sumner** [comment]
Oh, it should print `bun wiptest` there

**Comment by lucasew** [comment]
> Oh, it should print `bun wiptest` there

Why not just rename it to test?

**Comment by FinnRG** [comment]
@lucasew It is still a WIP

**Comment by foreverzmy** [comment]
您好，您的来信我已经收到，请等待回复！
