### ISSUE TITLE
`bun:sqlite`: `BEGIN TRANSACTION` is ignored

### ISSUE THREAD

**Issue by karimfromjordan** [oven-sh/bun#5078]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.4.13-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```js
import { Database } from 'bun:sqlite';

const db = new Database('database.sqlite');

db.run(`
begin transaction;

create table kv (
  key   text not null unique,
  value text
) strict;

commit;
`);
```

### What is the expected behavior?

The table `kv` should be created.

### What do you see instead?

Nothing happens. It silently fails and no table is created. The same SQL code works correctly in `better-sqlite3` and in the `sqlite3` CLI.

### Additional information

In order to handle migrations I usually have a directory tree:
```
migrations/
  - 001.sql
  - 002.sql
  ...
```
I then get the `user_version` using `PRAGMA user_version;` and apply all files with a version greater than the current `user_version`. To do this a string is constructed like this:
```sql
PRAGMA foreign_keys = off;

BEGIN TRANSACTION;
-- contents of 001.sql
PRAGMA user_version = ${user_version + 1}
COMMIT;
```
This doesn't seem to work in Bun.

**Comment by Jarred-Sumner** [comment]
I wonder what we could be doing wrong here. 

This is the function that calls into sqlite3 for that code:

https://github.com/oven-sh/bun/blob/07a6443a80d57c2aaa958bafba091bf4f9e88ca8/src/bun.js/bindings/sqlite/JSSQLStatement.cpp#L1538-L1542

I wonder if we need to make sure that the enum is `SQLITE_OK` instead of `SQLITE_DONE`?

**Comment by mdevan** [comment]
Only the first statement gets executed with db.run() or stmt.run(). The following code will only create the tables `a1` and `b1`.

```js
import { Database } from "bun:sqlite";

const db = new Database('a.db');

db.query('create table a1 (c int); create table a2 (c int);').run();

db.run('create table b1 (c int); create table b2 (c int);');

db.close();
```

Bun needs to wrap the SQLite C API [sqlite3_exec](https://www.sqlite.org/c3ref/exec.html), which supports execution of mulitple statements. The `sqlite3_prepare_*` APIs which JSSQLStatement.cpp uses will only parse and compile the *first* SQL statement in the given string (see the [docs](https://www.sqlite.org/c3ref/prepare.html), which say "These routines only compile the first statement in zSql, so [...]").

As it stands, there is currently (v1.0.3) no way in Bun to run an initialization SQL script that will create tables, set pragmas etc. after opening a database -- which is the issue I originally came here to raise :)

**Comment by mdevan** [comment]
Also, `Database.run()` is not documented at https://bun.sh/docs/api/sqlite.

**Comment by mdevan** [comment]
Same root cause as #3283 and #2479.

**Comment by karimfromjordan** [comment]
Yeah, I just realized that too. So even something like this doesn't work.
```js
import { Database } from 'bun:sqlite';

const db = new Database('database.sqlite');

db.run(`
create table kv (
  key   text not null unique,
  value text
) strict;

insert into kv (key, value) values ('karim', 'jordan');
`);
```
This is a real blocker.
