### ISSUE TITLE
destructuring node core module import breaks build

### ISSUE THREAD

**Issue by mvayngrib** [oven-sh/bun#5095]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What steps can reproduce the bug?

doesn't work:
```js
// index.js
import { gzipSync, gunzipSync } from 'zlib'

console.log(gunzipSync(gzipSync(Buffer.from('abc'))).toString())
```

```sh
/Users/mv/code/bun-playground/index.js:1:20 19
➜  bun-playground bun build '/Users/mv/code/bun-playground/index.js' --outdir dist 


error: No matching export in "node:zlib" for import "gzipSync"
import { gzipSync, gunzipSync } from 'zlib'
         ^
/Users/mv/code/bun-playground/index.js:1:10 9

error: No matching export in "node:zlib" for import "gunzipSync"
import { gzipSync, gunzipSync } from 'zlib'
```

works:
```
// index.js
import zlib from 'zlib'

const { gzipSync, gunzipSync } = zlib
console.log(gunzipSync(gzipSync(Buffer.from('abc'))).toString())
```

### What is the expected behavior?

`bun build` should work for both examples above

### What do you see instead?

```
error: No matching export in "node:zlib" for import "gzipSync"
import { gzipSync, gunzipSync } from 'zlib'
```

**Comment by sheijne** [comment]
Same issue with `import { resolve } from 'node:path'`.

Interestingly `fs` is working fine for me (on 1.0.0 and 1.0.1): `import { readdir } from 'node:fs'`, `import { readdir } from 'node:fs/promises'`.

**Comment by grctest** [comment]
Experiencing this same issue with the elysia-static plugin: https://github.com/elysiajs/elysia-static/issues/9

**Comment by MattCCC** [comment]
Same issue with node:path

**Comment by Jarred-Sumner** [comment]
Please set `target` to `bun`:
```
bun build --target=bun file.ts
```

It’s building a browser polyfill which is likely not what you meant to do. 

Note that you do not have to build ahead of time when using Bun. You can run the files directly.

**Comment by staciax** [comment]
> Please set `target` to `bun`:
> 
> ```
> bun build --target=bun file.ts
> ```
> 
> It’s building a browser polyfill which is likely not what you meant to do.
> 
> Note that you do not have to build ahead of time when using Bun. You can run the files directly.

thanks <3
