### ISSUE TITLE
Incorrect parsing of empty envs in .env file, when running via package.json script

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [oven-sh/bun#5097]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

1. Clone the repo: https://github.com/Lukasz-pluszczewski/bun-envs-bug
2. Run `bun run index.js` (works correctly)
3. Run `bun dev` (the value of `process.env.FOO_BAR` is `""` instead of empty, bun adds quotes `"` to the env value)

You can also run `FOO_BAR= bun run index.js` or `FOO_BAR= bun dev`. In both instances the value of `process.env.FOO_BAR` is `""`, which is incorrect but this seems like a lot less severe issue as people generally don't set empty env variables this way.

### What is the expected behavior?

Empty env variable should remain empty (and regardles of the way we start the script)

### What do you see instead?

Bun adds quotes to the empty env values

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/issues/5666 and fixed in 1.0.3.

![2023-09-24_11-16](https://github.com/oven-sh/bun/assets/9482395/b9dc0379-e508-4339-aed0-62ca979ef8f4)
