### ISSUE TITLE
`private` inside function arguments (field notation)

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#51]
via @Vbitz https://discord.com/channels/876711213126520882/887787428973281300/905657075185639465

This code:

```typescript
class Testing {
  constructor(private hello: string) {}

  toString() {
    return this.hello;
  }
}
```

Fails with:
```bash
error: Expected ")" but found hello

  constructor(private hello: string) {}
```

It should transpile to:

```js
class Testing {
  constructor(hello) {}

  toString() {
    return this.hello;
  }
}
```

**Comment by Vbitz** [comment]
The shorthand also sets that variable in the class so you need to emit an assignment.
```javascript
"use strict";
class Hello {
    constructor(hello) {
        this.hello = hello;
    }
    toString() {
        return this.hello;
    }
}
```
Source: https://www.typescriptlang.org/play?#code/MYGwhgzhAEASCmIQHtoG8BQ1vWMgdhAC4BOArsEciQBQAOJAlgG5hHzQAWiKAXNMSb4A5gEp0GLDgC+knNCoBlUoxE1xmefJLwiZEvgWdGEAHTckyANxTss6UA

**Comment by Jarred-Sumner** [comment]
I see the problem.

The code does track this:

https://github.com/Jarred-Sumner/bun/blob/5537c03569e45bf73e490f58ac86d5cf661fa4ab/src/js_parser/js_parser.zig#L4417-L4428

But I forgot about the transform afterwards.

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/Jarred-Sumner/bun/commit/d91e8974130735fd43cd9c37d6147fe20f6b3290

Currently, it follows the semantics of [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) which TypeScript enables by default when targeting ESNext or ES2022.

The following code:
```ts
class Testing {
  constructor(private hello: string) {}

  toString() {
    return this.hello;
  }
}
```

Now transpiles to:
```js
class Testing {
  hello;
  constructor(hello) {
    this.hello = hello;
  }
  toString() {
    return this.hello;
  }
}
```

Note that there is a semantic difference when `useDefineForClassFields` is disabled with `tsc`. In that case, `tsc` removes the property from the class body.  When `useDefineForClassFields` is disabled, `tsc` transpiles to:
```js
class Testing {
    constructor(hello) {
        this.hello = hello;
    }
    toString() {
        return this.hello;
    }
}
```

Removing unitialized properties can cause a runtime performance problem when instantiating many objects of the same class due to polymorphism. However, for compatibility, it would be best if bun supports that anyway. The original issue was the build error due to `private` being used inside of function arguments though.
