### ISSUE TITLE
WebSocket client `messaage` event is broken

### ISSUE THREAD

**Issue by EmrysMyrddin** [oven-sh/bun#510]
Using bun's WebSocket client, the `message` event doesn't work as expected.

The `message` event handler always receive `{ "isTrusted": true }` as first parameter instead of the actual data sent by the server.

Here is the minimal reproduction test:

```js
// index.js
const ws = new WebSocket("ws://127.0.0.1:7000/connect")

ws.addEventListener("message", (data) => {
  console.log(data)
})
```

```bash
$ bun run index.js
{"isTrusted":true}
{"isTrusted":true}
```

**Comment by EmrysMyrddin** [comment]
After looking for your tests, it in facts pass the correct event to the event handler.

But, for some reason, the console.log doesn't display all the fields present in the event object.

**Comment by Jarred-Sumner** [comment]
Need to mark `data` as enumerable

I think Safari has the same behavior here. It's just confusing

**Comment by rexwu1104** [comment]
I have the same problem, I use WSL.
