### ISSUE TITLE
Dynamic `import()` doesn't decode urls - breaks vite in directories with spaces and special characters

### ISSUE THREAD

**Issue by justDeeevin** [oven-sh/bun#5100]
### What version of Bun is running?

1.0.1+07a6443a80d57c2aaa958bafba091bf4f9e88ca8

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

- Create a Vite app with `bun create vite`
- `cd` into the new app directory and install dependencies with `bun install`
- Attempt to run the Vite dev server with `bun --bun run dev`

### What is the expected behavior?

The Vite application should run on localhost

### What do you see instead?

```
$ vite
failed to load config from /home/devin/Software Dev/vite-project/vite.config.ts
error when starting dev server:
undefined
error: script "dev" exited with code 1 (SIGHUP)
```
<img width="647" alt="image" src="https://github.com/oven-sh/bun/assets/90054389/cb84c727-62f0-468b-9dc0-52b4b43d796c">

### Additional information

This also occurs on 1.0 (1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983)

**Comment by justDeeevin** [comment]
After further experimentation, I'm experiencing this issue with Vite as a whole.

**Comment by ThatXliner** [comment]
Same issue here (Bun 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983, Darwin 22.5.0 x86_64 i386)

**Comment by ThatXliner** [comment]
Same issue here (Bun 1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983, Darwin 22.5.0 x86_64 i386)

**Comment by nasa14119** [comment]
Appears the problem is in "bun install" try npm i and then it works

**Comment by justDeeevin** [comment]
I can't say the same.
![image](https://github.com/oven-sh/bun/assets/90054389/2947dd17-8039-4240-b65d-d1df2d48d064)

**Comment by ThatXliner** [comment]
I agree

<img width="1450" alt="image" src="https://github.com/oven-sh/bun/assets/66848002/1fc7fbe4-12b7-444d-add3-ab512611642a">

**Comment by paperclover** [comment]
we narrowed this down to being an issue with spaces in the directory name

the simple reproduction

```
await import("./file%20name.js");
```

**Comment by justDeeevin** [comment]
I'm continuing to see this issue with certain Vite frameworks (including React and Svletekit) while using Bun 1.0.6.
<img width="694" alt="image" src="https://github.com/oven-sh/bun/assets/90054389/bcf1e6ec-8b53-48d9-aa92-aa72e57f29a3">

**Comment by justDeeevin** [comment]
I'm going to create a new issue since this one has been marked as fixed as the decoding issue.
