### ISSUE TITLE
Segmentation fault in bun, while runs fine in node and deno (Linux)

### ISSUE THREAD

**Issue by elringus** [oven-sh/bun#5107]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.4.0-162-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Unzip the attached [repro.zip](https://github.com/oven-sh/bun/files/12587652/repro.zip)
2. Run `bun main.mjs`

### What is the expected behavior?

A message with bun version is written to the console.

### What do you see instead?

Segmentation fault

### Additional information

Same script works fine with:

- `node main.mjs` (node v20.6.1)
- `deno run main.mjs` (deno v1.36.4)

(script itself is .NET runtime compiled to WASM)

![scrn](https://github.com/oven-sh/bun/assets/2056864/2d757b2d-6584-4c57-a66b-2b7abed78422)

**Comment by Jarred-Sumner** [comment]
Fixed by @cirospaciari in #5422
