### ISSUE TITLE
error: FileNotFound reading "node:process" after building file to single executable

### ISSUE THREAD

**Issue by kerambit** [oven-sh/bun#5108]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Save code below to file test.js

```
import process from 'node:process';
console.log(process.argv)
```

`$ bun build ./test.js --compile --outfile test`

`$ ./test -h`

### What is the expected behavior?

Console shows the next message `[ "bun", "compiled://root/test", "-h" ]`

### What do you see instead?

I got runtime error `error: FileNotFound reading "node:process"`

### Additional information

No errors during compilation.
Looks like the problem in `import process from 'node:process';` line - if you remove it everything works fine.
It's not big a problem for my code but looks like a lot of dependencies use it this way and its broke the whole app.

**Comment by Hanaasagi** [comment]
I think this could be fixed in https://github.com/oven-sh/bun/pull/5102.

Related to https://github.com/oven-sh/bun/issues/4918 https://github.com/oven-sh/bun/issues/4592

**Comment by mayankchhabra** [comment]
[bun 1.0.1](https://bun.sh/blog/bun-v1.0.1) fixes the issue:

> fixes a bug importing node: builtins in bun build --compile
