### ISSUE TITLE
WebSocket instances are missing ready state constants

### ISSUE THREAD

**Issue by ferm10n** [oven-sh/bun#5116]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.4.0-150-generic x86_64 x86_64

### What steps can reproduce the bug?

While trying out bun with tRPC, I noticed that the subscriptions immediately close after they are started.
This is because tRPC checks if the websocket's `readyState` equals a ready state constant:
https://github.com/trpc/trpc/blob/c03a88ae91d368dbaf4c5c9bbf0f40fd7b00f0ec/packages/server/src/adapters/ws.ts#L238-L243
```ts
        if (client.readyState !== client.OPEN) {
          // if the client got disconnected whilst initializing the subscription
          // no need to send stopped message if the client is disconnected
          sub.unsubscribe();
          return;
        }
```

In bun, `client.OPEN` (and the other ready state constants) are `undefined`.

### What is the expected behavior?

If bun is going to replace the implementation of ws, I'd expect it to provide the same things, so that libraries that expect `ws` continue to work.

### What do you see instead?

ready state constants on the web socket instance are all `undefined`, and they're missing from the interface https://bun.sh/docs/api/websockets#reference

### Additional information

My understanding is that bun is overriding my `import ws from 'ws';` to resolve to Bun's implementation (ServerWebSocket) instead of the ws module from npm. Maybe it'd be better to opt in to Bun's replacement instead of doing it automatically? **I don't know how to force bun to resolve the npm module.**

Here's the ready state constants from ws: https://github.com/websockets/ws/blob/7460049ff0a61bef8d5eda4b1d5c8170bc7d6b6f/doc/ws.md#ready-state-constants

Also note that the browser native WebSocket also supports `WebSocket.OPEN` and the other ready states.

My understand on the ready state constants is limited, maybe they're non-standard. If that's the case then maybe I should be opening an issue on tRPC instead.

**Comment by nektro** [comment]
is this still affecting you? running with Bun 1.0.30-debug I'm having a hard time reproducing this.

```
podman run -e POSTGRES_PASSWORD=mysecretpassword -d postgres
npx create-next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-websockets-starter trpc-prisma-websockets-starter
**edit .env**
bun run dev
```

running the above and playing about on various pages of the example app it boots and runs correctly.

additionally the following code prints `1` and `1` as expected

```
const WebSocket = require("ws");
console.log(WebSocket.OPEN);
console.log((new WebSocket('ws://a')).OPEN);
```

**Comment by ferm10n** [comment]
Looks like this is no longer an issue. Using bun 1.0.15, with the project that initially caused an error. I appreciate the thorough attempt at a repro!!
