### ISSUE TITLE
Segmentation fault when sending a response with a length of 1024 bytes on ExpressJS + Sentry + Compression

### ISSUE THREAD

**Issue by romulovalez** [oven-sh/bun#5123]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

By combining Sentry and Compression with Express I have been able to generate a segmentation fault when sending a response with length of 1024 bytes, this combination of libraries is not unusual to see.

Made a basic repository where you can reproduce this bug: https://github.com/romulovalez/bun-bug/tree/master

- Execute `bun install`
- Execute `bun run index.ts`
- Go to `http://localhost:3002/`

### What is the expected behavior?

It should return the response like in NodeJS.

### What do you see instead?

Segmentation Fault

**Comment by bitsplitter** [comment]
I have the same issue. 
### What version of Bun is running?
1.0.1

### What platform is your computer?
Mac OS Version 13.2.1 (22D68)

### What steps can reproduce the bug?

**1024** is the default threshold for the compression library. I do not get the error when:
- The response is smaller than the threshold or 
- I omit the Accept-encoding:gzip header in the request or
- I disable Sentry

**Comment by romulovalez** [comment]
@bitsplitter I just tried version 1.0.3 and now there is no segmentation fault, it seems that it is already solved 👏, If you could confirm it I will close this issue.

**Comment by bitsplitter** [comment]
On my side the problem is also solved in version 1.0.3.
