### ISSUE TITLE
Segmentation fault (core dumped) bun install

### ISSUE THREAD

**Issue by thisisadarshjais** [oven-sh/bun#5125]
I am able to successfully install my dependency in my local machine, But when I run it via github action (bun version is 1.0.0)  I get the below error. 

The error dose not seems much informative to even debug further.  

It's working all fine using npm 

Bun itself is working fine which I can confirm, since packages from other symlink module is getting install.

Let me know what else I could share to understand it more better for you.

<img width="1388" alt="image" src="https://github.com/oven-sh/setup-bun/assets/117281532/d3d6d403-241d-4bf3-b6ab-3314acfa48b5">

Incase these info help, 

I also have a private repo inside, And this is how I am passing token for same. When I remove these token, Error change and I can see it's throwing 401 (which conclude that these token is getting accessible), I don't think issue is anyway related to even private repo. 

<img width="1015" alt="image" src="https://github.com/oven-sh/setup-bun/assets/117281532/53f6c8fd-7b5b-4b06-8361-7305e81b9fa1">

I also have the symlink modules, which is reference as below inside package.json. (Working fine in my local and even in github action on my another proj,)

<img width="643" alt="image" src="https://github.com/oven-sh/setup-bun/assets/117281532/43d2a1b0-08f7-41c1-b7b9-eaedac107f03">

**Comment by Electroid** [comment]
Thanks for reporting this issue, going to transfer it to the main Bun repository.

**Comment by nektro** [comment]
is this issue still impacting you? am happy to investigate further if so and we're able to reproduce

**Comment by Jarred-Sumner** [comment]
If you still run into an issue like this, please include the crash report and leave a comment
