### ISSUE TITLE
ESLint can't find `@typescript-eslint` plugin if installed with bun

### ISSUE THREAD

**Issue by javalsai** [oven-sh/bun#5128]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.4.12-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Clone the repo https://github.com/javalsai/bun-bug
1. Install dependencies with `bun i` 
1. Run `bun run lint`

 ESLint won't find `@typescript-eslint`.
 But if we install the dependencies with `npm i` instead, running `bun run lint` works as expected (eslint throws a linting error related to `no-console`)

### What is the expected behavior?

ESLint  finds `@typescript-eslint` and throws a linting error.

### What do you see instead?

ESLint doesn't find `@typescript-eslint` and can't run the linting process at all.

**Comment by xhyrom** [comment]
![image](https://github.com/oven-sh/bun/assets/56601352/c4a349cd-fddb-42ca-a814-e3f42c384d01)

You have `typescript` as peer dep and bun doesn't install peer dependencies by default. Install typescript as dev dependency and it'll work

**Comment by javalsai** [comment]
> ![image](https://user-images.githubusercontent.com/56601352/267404057-c4a349cd-fddb-42ca-a814-e3f42c384d01.png)
> 
> You have `typescript` as peer dep and bun doesn't install peer dependencies by default. Install typescript as dev dependency and it'll work

Alright, thanks, that fixes the issue! But that was the default `package.json` that bun produced with `bun init`, should that be changed and moved into dependencies by default?

**Comment by unimonkiez** [comment]
For me it still happens even after moving the peerDependency.

### What version of Bun is running?
1.0.4

### What platform is your computer?
Apple M1 Pro Sonoma 14.0
