### ISSUE TITLE
replace string with regular expression got wrong output

### ISSUE THREAD

**Issue by atoms18** [oven-sh/bun#5132]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

when try to match a regular expression with these emoji and replace it with string
```
let str = "🔴11 54 / 10,000";
str = str.replace(/[🔵🔴,]+/g, '');
console.log(str);
```

### What is the expected behavior?

the outputs should be:
```11 54 / 10000```
instead of
```🔴  / 0000```

**Comment by Electroid** [comment]
@dylan-conway Any ideas here?

**Comment by dylan-conway** [comment]
This is the transpiled source:
```js
let str = "\uD83D\uDD3411 54 / 10,000";
str = str.replace(/[\u{1f535}\u{1f534},]+/g, "");
console.log(str);
```
Using the regex constructor with a string works, `new RegExp("[🔵🔴,]+", "g");`, so we probably aren't encoding `/.../` correctly
