### ISSUE TITLE
`node:readline`: listening to 'line' event of `readline.Interface` slows down code execution

### ISSUE THREAD

**Issue by yschroe** [oven-sh/bun#5136]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I noticed that attaching a callback function to the ['line'](https://nodejs.org/api/readline.html#event-line) event of the [`readline.Interface`](https://nodejs.org/api/readline.html#class-readlineinterface) slows down the code execution in my case by around 25%. Even if the callback function has an empty body. Node.js shows no performance slowdown in the same example.

#### test.js
```javascript
import EventEmitter from 'node:events';
import { createReadStream } from 'node:fs';
import { performance } from 'node:perf_hooks';
import { createInterface } from 'node:readline';

let tStart, tdiff;

// warmup run to avoid any startup issues or buffering etc
const lineReader0 = createInterface({
    input: createReadStream('lichess_db_standard_rated_2013-12.pgn')
});
await EventEmitter.once(lineReader0, 'close');

// ======================
//        TEST 1
// ======================
console.log('TEST 1: line reader without callback');
tStart = performance.now();

// init line reader
const lineReader1 = createInterface({
    input: createReadStream('lichess_db_standard_rated_2013-12.pgn')
});

// wait for line reader to finish
await EventEmitter.once(lineReader1, 'close');
tdiff = Math.round(performance.now() - tStart) / 1000;
console.log(`--> Read all lines in ${tdiff}s.\n`);

// ======================
//        TEST 2
// ======================
console.log('TEST 2: line reader with empty callback');
tStart = performance.now();

// init line reader
const lineReader2 = createInterface({
    input: createReadStream('lichess_db_standard_rated_2013-12.pgn')
});

// empty on 'line' callback
lineReader2.on('line', (_) => {});

// wait for line reader to finish
await EventEmitter.once(lineReader2, 'close');
tdiff = Math.round(performance.now() - tStart) / 1000;
console.log(`--> Read all lines in ${tdiff}s.\n`);

// ======================
//        TEST 3
// ======================
console.log('TEST 3: line reader with callback function counting the lines');
tStart = performance.now();

// init line reader
const lineReader3 = createInterface({
  input: createReadStream('lichess_db_standard_rated_2013-12.pgn')
});

let lineCount = 0;
// on 'line' callback: count lines
lineReader3.on('line', (_) => {
    lineCount += 1;
});

// wait for line reader to finish
await EventEmitter.once(lineReader3, 'close');
tdiff = Math.round(performance.now() - tStart) / 1000;
console.log(
    `--> Read ${lineCount} lines in ${tdiff}s (${Math.round(
        lineCount / tdiff
    )} lines/s).\n`
);

```

#### run with bun
```
>bun test.js
TEST 1: line reader without callback
--> Read all lines in 0.278s.

TEST 2: line reader with empty callback
--> Read all lines in 0.352s.

TEST 3: line reader with callback function counting the lines
--> Read 2989876 lines in 0.356s (8398528 lines/s).
```

#### run with node.js v20.6.1
```
>node test.js
TEST 1: line reader without callback
--> Read all lines in 0.279s.

TEST 2: line reader with empty callback
--> Read all lines in 0.28s.

TEST 3: line reader with callback function counting the lines
--> Read 2989876 lines in 0.28s (10678129 lines/s).
```

It should be reproducible with any large enough file, but if needed I can upload my example file as well.

Since `readline.Interface` inherits from `EventEmitter` it could also be a general issue with the `EventEmitter` class.

### What is the expected behavior?

If node.js is the benchmark to beat, listening to the 'line' event should not slow down execution.

### What do you see instead?

A slowdown of around 25% simply by defining a callback.

### Additional information

Not sure if performance issues are already in your scope at this point in time, but I tried running my library [chessalyzer.js](https://github.com/YSchroe/chessalyzer.js) with bun and noticed that it is significantly slower compared to running it with node.js. The library is used to parse chess games from (large) PGN files and basically replays the games to extract some KPIs from them. It follows three main steps:

1. Read-in the PGN file asynchronously via the node:readline module
2. If enough lines have been read in pass the data to a node:worker_threads.Worker
3. In there parse the PGN (regex, string compare etc.) and extract the game stats. Then pass the data back to the main thread.

For the first step I already noticed some performance differences, described in this issue. Is fixing performance issues in your scope yet? Then I will have a look at the other two steps as well.

**Comment by yschroe** [comment]
I'm currently looking into this and I think this is more of a problem of the `EventEmitter` class which is multiplied by the `readline` module because it emits so many events.

The current implementation of the `EventEmitter.emit(...)` function clones the `handlers` array that contains all callback function for a given event every time the event is emitted, which costs some performance. The reason for this - as far as I can see - is that the length of the `handlers` array can change while looping over the callbacks. Callbacks added via `once(...)` are removed once the callback has been called.
```javascript
function emit(type, ...args) {
  // ...
  var handlers = events[type];
  // ...

  for (var handler of [...handlers]) {
    handler.apply(this, args);
  }
  return true;
};
```

Could this array cloning step not be avoided by simply looping over the array in the other direction? 
```javascript
  var handlers = events[type];

  const handlerCnt = handlers.length;
  for (let i = handlerCnt - 1; i >= 0; --i) {
    handlers[i].apply(this, args);
  }
```
If a callback is removed from the array while looping over it from end to start, it does not matter since only entries after the removed element are affected by the change in length (which have been called already anyways ). Or am I missing something? I am wondering, since Node.js did implement it in a similar way (cloning the array). It seems the order of the callback is important though since there is a `addListener(...)` and `prependListener(...)` function. But this could be fixed by also inverting the logic of both functions I guess.

By implementing the change above I get following results for a file with ~10 million lines:
#### bun v1.0.1
```
TEST 1: line reader without callback
--> Read all lines in 1.977s.

TEST 2: line reader with empty callback
--> Read all lines in 2.506s.
```
#### bun (debug-build)
```
TEST 1: line reader without callback
--> Read all lines in 1.971s.

TEST 2: line reader with empty callback
--> Read all lines in 2.167s.
```

Still not on Node.js level but an improvement nonetheless. Gotta investigate further how Node.js manages to not lose performance while also using array cloning.

**Comment by yschroe** [comment]
Alright, I figured out the second bottleneck and managed to get the implementation as fast as Node.js (in some cases at least).

In addition to the array cloning step from my last comment, using the `Function.apply(...)` method to spread the `args` argument slows things down as well. I implemented a condition which uses `Function.call(...)` instead, if only one argument is contained in `args`. In combination with the reversed array iteration there is no significant slowdown anymore in this case.

#### bun (debug-build v2)
```
TEST 1: line reader without callback
--> Read all lines in 1.925s.

TEST 2: line reader with empty callback
--> Read all lines in 1.928s.
```

Still I think it is worth investigating why using `Function.apply(...)` leads to performance issues in bun while in Node.js there is no hit to performance. But I am unsure if this is implemented in a different module in bun or is coming from jsc.

**Comment by Jarred-Sumner** [comment]
If it’s taking seconds to complete, that’s not the array allocations unless there are millions/billions of lines. It has to be blocking I/O

**Comment by yschroe** [comment]
> If it’s taking seconds to complete, that’s not the array allocations unless there are millions/billions of lines. It has to be blocking I/O

My test file has several millions of lines so it's expected to take some seconds to be read-in fully (it's a larger file than the one I used in the original issue). That is no problem. The main problem is that simply attaching a empty callback to the 'line' event slows things down (time difference between "TEST 1" and "TEST 2"). I think this cannot be I/O related since the file is been read-in anyways, with attached callbacks or not.

I tried some different things in the last hours and the two changes from above remove this slowdown for me.

Or did I misunderstand you?

The "fixed" `emit(...)` function now looks like this:
``` javascript
const emitWithoutRejectionCapture = function emit(type, ...args) {
  if (type === "error") {
    return emitError(this, args);
  }
  var { _events: events } = this;
  if (events === undefined) return false;
  var handlers = events[type];
  if (handlers === undefined) return false;
  // iterate in reverse so the handlers array does not need to be cloned
  for (let i = handlers.length - 1; i >= 0; --i) {
    // for performance reason Function.call(...) is used if only one arg needs to be passed
    if (args.length === 1) handlers[i].call(this, args[0]);
    else handlers[i].apply(this, args);
  }
  return true;
};
```
Alongside with some changes to the prependListener/addListener functions this also passes all tests in the node/js/events folder.

**Comment by jliocsar** [comment]
I'm having a similar issue, seems to be related to `readline` on Bun itself?

I have a repo with code to reproduce this [here](https://github.com/jliocsar/jstr), but essentially this simple script I wrote reads a JSON input piped from a previous command using `readline` (listening to the `line` event), here's a benchmark using Node v18.16.1 vs Bun 1.0.2:

![image](https://github.com/oven-sh/bun/assets/60270538/17fec4e9-a716-4949-8887-600413307133)

Using Bun is always a tad slower when comparing to Node.js.

Current platform is `Linux 6.2.0-32-generic x86_64 x86_64`.
