### ISSUE TITLE
Bun install and local workspaces, doesn't work the same on second install

### ISSUE THREAD

**Issue by httpete** [oven-sh/bun#5138]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux

### What steps can reproduce the bug?

I am trying to migrate from npm, and we use workspaces.

What I am seeing is if I do bunfig.toml to point to our artifactory registry for all third party packages, it works on the initial install just great. But after doing bun install again, I get "failed to resolve". My desired result is to have local workspaces resolve locally, and all other packages to resolve from our internal registry as npm does.

The INITIAL bun install does the workspace: prefix automatically successfully.

@dialog-components/confirmation-dialog@workspace:src/sharedComponents/dialog/ConfirmationDialog

### What is the expected behavior?

Bun install works the second run like the first.

### What do you see instead?

[_No response_](error: @dialog-components/confirmation-dialog@* failed to resolve)

**Comment by httpete** [comment]
This is what my current .npmrc file looks like:
```
registry=https://packages.mycompany.net/artifactory/api/npm/virtual/
//packages.mycompany.net/artifactory/api/npm/virtual/:_auth=thekey
//packages.mycompany.net/artifactory/api/npm/virtual/:always-auth=true

**Comment by giri-jeedigunta** [comment]
I'm trying to add bun to existing NextJS app. We have packages from 2 private npm repos. 
When I run `bun add bun-framework-next` it doesn't add any packages from the private repos. 

I looked at https://github.com/oven-sh/bun/blob/c3455c0ceee6bbe399781819a42fff6cf24792e2/docs/cli/bun-install.md and added scopes in the `bunfig.toml`

[install.scopes]
"@brand:registry" = { username = "xxx", password = "yyy", url = "https://url" }
"@brand-group:registry" = { token = "xxx", url = "https://url" }

it doesn't work ... Looking for help on how to install dependencies from multiple npm registries. 

This is how my .npmrc looks ... 

`
@brand-group:registry=https://npm.pkg.github.com
@brand:registry=https://pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/registry/
always-auth=true
engine-strict=true
//npm.pkg.github.com/:_authToken=XXX
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/registry/:username=YYY
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/registry/:_password=ZZZ
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/registry/:email=some-email
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/:username=YYY
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/:_password=ZZZ
//pkgs.dev.azure.com/brandcloud/Frontend/_packaging/brand-packages/npm/:email=some-email`

**Comment by giri-jeedigunta** [comment]
I removed registry from "@brand:registry" and there is no 404 error. 
But I see a new error - `error: ERR_TLS_CERT_ALTNAME_INVALID downloading package manifest @brand/jest-config`

**Comment by giri-jeedigunta** [comment]
> I removed registry from "@brand:registry" and there is no 404 error. But I see a new error - `error: ERR_TLS_CERT_ALTNAME_INVALID downloading package manifest @brand/jest-config`

I was able to resolve this issue ... here is what I did 

`NODE_TLS_REJECT_UNAUTHORIZED=0 bun add bun-framework-next --verbose` boom it installed all the dependencies including the ones from github private repo

**Comment by dylan-conway** [comment]
Recently we've fixed several bugs with custom registries and workspace bugs, I'm pretty sure this issue is fixed. Can you try again with bun `v1.1.13`?

**Comment by dylan-conway** [comment]
Closing as complete with #11606 and #11979. Please reopen or open a new issue if you continue to have problems with workspaces or custom registries
