### ISSUE TITLE
[Feature Request] Framework without file based routing

### ISSUE THREAD

**Issue by gffuma** [oven-sh/bun#515]
Hi first of all this project is awesome!
Should be cool if when developing a framework and omitting the `router` key in `framework` field in package.json bun still call the library development server script and let the framework library handle the request. At the moment only file based routing is supported and if `router`  the development server script is not called.

**Comment by Electroid** [comment]
This issue is related to the old `bun dev`, which was removed in Bun 1.0 and replaced by Bun running your `dev` script in the package.json.
