### ISSUE TITLE
SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.

### ISSUE THREAD

**Issue by giladv** [oven-sh/bun#5150]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

not sure how to isolate this exactly but i have a project that exports a config from the node-config package

```
// config.ts
export { default as config } from "config";
```

### What is the expected behavior?

it should work normally.

### What do you see instead?

i get the following error
```
SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.
      at processTicksAndRejections (:1:2602)
```

### Additional information

i managed to fix it by altering the file as follows

```
// config.ts
export { default as config } from "config";

// added new:
export default {};
```

**Comment by giladv** [comment]
and then another bug takes it's place :) will wait for a more stable release, keep up the good work!

**Comment by The-Code-Monkey** [comment]
I have the same issue doing what the person does above does not fix this.

Happens on this line: https://github.com/The-Code-Monkey/TechStack/blob/chore/setup-bun/packages/components/src/atoms/input/Input.tsx#L10

referencing this line: https://github.com/The-Code-Monkey/TechStack/blob/chore/setup-bun/packages/components/src/primal/index.ts#L1

Can someone explain a way to fix or when this is going to be fixed.

**Comment by 0xSalman** [comment]
I have run into this issue as well. The following code does not work even with the workaround mentioned by @giladv 

```
export { Attributes, SpanStatusCode } from '@opentelemetry/api'
```

The workaround I have used is like this:

```
import {
  Attributes as _Attributes,
  SpanStatusCode as _SpanStatusCode,
} from '@opentelemetry/api'

export type Attributes = _Attributes
export type SpanStatusCode = _SpanStatusCode
```

**Comment by The-Code-Monkey** [comment]
@salman-ahmad I found that I had to add type to all the imports too e.g. import type or import { type

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5426
