### ISSUE TITLE
Bun with Vite freezing

### ISSUE THREAD

**Issue by CoderKoen** [oven-sh/bun#5157]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

WSL on Windows 11

### What steps can reproduce the bug?

I did 
bunx create-vite@latest my-app
selected "React" but I think it would break all the options in the "Select Framework" section
and on the "Select variant" section, my entire shell freezes

### What is the expected behavior?

It is supported to not freeze and make my app

### What do you see instead?

It freezes my entire shell

**Comment by CoderKoen** [comment]
And i tried svelte and it also broke

**Comment by ghiscoding** [comment]
might be related to #4664 which ~has a PR #5035 in draft~, they had a PR in draft but it was later closed 😞

**Comment by ShimiShimson** [comment]
Same for me

**Comment by executionreverted** [comment]
same. vite dev command freezes

**Comment by nacimgoura** [comment]
Little similar to my issue too : https://github.com/oven-sh/bun/issues/4912

**Comment by CMOISDEAD** [comment]
Same problem in arch Linux, but only when replace dev script from  `vite` to `bunx --bun vite`. 👍🏻

**Comment by notramo** [comment]
Docker image is also affected.

**Comment by divyanthj** [comment]
Why was it closed? How do you fix it?

**Comment by nacimgoura** [comment]
> Why was it closed? How do you fix it?

I don't know, issue has not been resolved

**Comment by jjwallace** [comment]
still freezing

**Comment by igortas** [comment]
Still freezing with ```bun```

**Comment by krugi** [comment]
I'm experiencing it as well with `bun --bun vite build`

**Comment by notramo** [comment]
@divyanthj @nacimgoura @jjwallace  @igortas @krugi
I have been using it with Vite, both for SvelteKit projects, and others. I think the maintainers could more easily reproduce the issue if you provied an example repo where it freezes.
