### ISSUE TITLE
Illegal instruction on Intel Core 2 Duo

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5172]
Latest bun-baseline fails to run on my ancient processor due to illegal instructions. The processor in question is Intel Core 2 Duo.
Obviously no program can support all of the legacy hardware, so I am curious what is the baseline for Bun-baseline (like what is the newest instruction set it is expected to have)

_Originally reported on Discord: [`what is the baseline for bun-baseline`](https://discord.com/channels/876711213126520882/1151278676533592124/1151278676533592124)_

**Comment by Adamkaram** [comment]
have the same issue

**Comment by Adamkaram** [comment]
u could fix it with 
```1
wget  https://downloadmirror.intel.com/784319/sde-external-9.24.0-2023-07-13-lin.tar.xz -O /tmp/intel-sde.tar.xz
cd /tmp
tar -xf intel-sde.tar.xz
cd sde-external*
mkdir /usr/local/bin -p
cp sde64 /usr/local/bin/sde
cp -r intel64 /usr/local/bin/
cp -r misc /usr/local/bin/

```
```2
echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc
```

**Comment by Electroid** [comment]
We are unlikely to support very old CPUs, like Core Duo.
