### ISSUE TITLE
Warn when install scripts for a dependency are skipped

### ISSUE THREAD

**Issue by ineffyble** [oven-sh/bun#5174]
### What is the problem this feature would solve?

Right now bun won't run install scripts for any dependency that's not listed in `trustedDependencies`.

This is a great security feature but an awful developer experience, because not only will a lot of packages not work out of the box, but you have no idea why.

Additionally, even once you have worked out that this is the likely issue, you have no way of knowing _which_ of your dependencies (direct or transitive) have had install scripts skipped, and trying to debug this and work it out is surprisingly difficult.

### What is the feature you are proposing to solve the problem?

Whenever bun _doesn't_ run an install script because the package is not part of `trustedDependencies`, print a warning to let the user know what package's scripts were skipped and what they can do to address it.

### What alternatives have you considered?

It might also be useful to have a flag that ignores `trustedDependencies` and runs all install scripts, as part of debugging. This would make it easy for a dev to determine if skipped install scripts is to blame for their issue.

**Comment by ersoy78** [comment]
This. silently performing incomplete installs is terrible. Now I have no idea which package bun will silently not install properly so I've been using npm. This needs to be fixed urgently.

**Comment by MohamedLamineAllal** [comment]
That's a true actual drawback. And I wonder what are the performance effects of running the scripts. (That's not nodejs, npm compatible)
- Providing at least a command option to choose to install should be expected.

As per
- https://bun.sh/guides/install/trusted
    - bun is intending to manage a list of trusted packages, that are audited ....
    - To make security against such threat first class
    
- Still the option to choose to set all packages as trusted (ignore such security measure) => should be provided. Security concern should be our choice. It's ok to run bun by default on the secure behavior. And as users we can opt out of it.

**Comment by Jarred-Sumner** [comment]
This was fixed some time ago. 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/3efd70bf-444f-4faa-b2ac-aa8e1574974d">
