### ISSUE TITLE
`process.send is not a function` using pm2 and nodemon

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5177]
Hello! I'm creating a Discord bot manager for all my processes. However, it seems that pm2 and nodemon aren't able to be installed/used with Bun. For example, nodemon throws an error when using `nodemon.start()` (see screenshot for errors): https://sourceb.in/i0lOjDWqTB
And for `pm2.start()`, I get an error saying that pm2 is unable to connect (likely an issue with node:net/node:dgram not being fully implemented) (see screenshot for errors): https://sourceb.in/RTH2H0WHrt

![image.png](https://cdn.discordapp.com/attachments/1151218222075486269/1151218222402654228/image.png)

![image.png](https://cdn.discordapp.com/attachments/1151218222075486269/1151218222687850608/image.png)

_Originally reported on Discord: [`Using pm2/nodemon`](https://discord.com/channels/876711213126520882/1151218222075486269/1151218222075486269)_

**Comment by Eltik** [comment]
Hello! I'm the creator of this issue. I've created a repository with the bare minimum code to show what the issue is.
https://github.com/Eltik/Bun-pm2-nodemon

**Comment by paperclover** [comment]
the commit that i marked as fixes this issue only fixes the first half of it. the failed to connect thing is something ive noticed in a few other spots
