### ISSUE TITLE
Weird issues setting cookies in ExpressJS and Bun

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5183]
Apologies if this isn't the right place for it. 

I'm working on a backend application written in TypeScript. I'm using ExpressJS as my framework of choice, and Bun as my runtime.

I was trying to set some cookies using the usual res.cookie function calls in Express but for the life of me I couldn't get this working with more than one cookie at a time. The browser would accept the first cookie but then nothing else, even though multiple cookies were set. 

I ran the same code in just a normal NodeJS, JavaScript, and ExpressJS environment and this time it worked.

Did I miss something?

![Screenshot_from_2023-09-12_13-26-51.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118231742988419/Screenshot_from_2023-09-12_13-26-51.png)

![Screenshot_from_2023-09-12_13-26-33.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118232011419750/Screenshot_from_2023-09-12_13-26-33.png)

![Screenshot_from_2023-09-12_13-24-41.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118232292442182/Screenshot_from_2023-09-12_13-24-41.png)

![Screenshot_from_2023-09-12_13-25-41.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118232573456444/Screenshot_from_2023-09-12_13-25-41.png)

![Screenshot_from_2023-09-12_13-25-28.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118232837693510/Screenshot_from_2023-09-12_13-25-28.png)

![Screenshot_from_2023-09-12_13-25-02.png](https://cdn.discordapp.com/attachments/1151118231063502908/1151118233127104563/Screenshot_from_2023-09-12_13-25-02.png)

_Originally reported on Discord: [`Weird issues setting cookies in ExpressJS and Bun`](https://discord.com/channels/876711213126520882/1151118231063502908/1151118231063502908)_

**Comment by Electroid** [comment]
Related to #3585

**Comment by Electroid** [comment]
Related to #4285
