### ISSUE TITLE
How do you read a directory with Bun?

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5184]
Bun.file(...) is available for file i/o, but is there a native Bun way to read a folder's contents? Or do I have to use the Node-style api's Bun provides?

_Originally reported on Discord: [`How do you read a directory with Bun?`](https://discord.com/channels/876711213126520882/1150965935692329080/1150965935692329080)_

**Comment by Electroid** [comment]
We do have plans to support more `Bun.file()` APIs, such as listing files.

**Comment by lirc571** [comment]
Why is this issue closed as being completed? If it's implemented, can someone point to the doc or source for this function?

**Comment by deadcoder0904** [comment]
@Electroid would love the same. This ranks on Google but no solution.
