### ISSUE TITLE
Unable to access env values

### ISSUE THREAD

**Issue by Bsingh2697** [oven-sh/bun#519]
I tried to access env keys but returned undefined
<img width="668" alt="Screenshot 2022-07-09 at 23 46 48" src="https://user-images.githubusercontent.com/36998578/178124967-87ee23a9-55f3-44ea-b48a-b39264c8047b.png">

OS : MacOS M1
Bun : v0.1.2

**Comment by FinnRG** [comment]
The .env file should be located in the project root, not the src folder

**Comment by Bsingh2697** [comment]
<img width="680" alt="Screenshot 2022-07-10 at 20 05 23" src="https://user-images.githubusercontent.com/36998578/178158537-160d8ea9-20e4-4eff-8307-2898e0f0e7f0.png">
Still not working

**Comment by FinnRG** [comment]
@Bsingh2697 Are you using Next or any other framework? Could you share a repo?

**Comment by Bsingh2697** [comment]
@FinnRG  hi, Can't share the original repo but here's another one with the same issue. 
https://github.com/Bsingh2697/bunTestRepo
Forgive me if there's some minor issue :) haha

**Comment by FinnRG** [comment]
@Bsingh2697 The issue can be resolved by writing ``PORT_NUM=8081``. In particular bun fails to parse a env variable with a space before the equals sign.

- ``PORT_NUM= 8081`` works
- ``PORT_NUM =8081`` doesn't work

**Comment by Bsingh2697** [comment]
@FinnRG Thanks it's working now

**Comment by FinnRG** [comment]
I'll reopen this because it's still a bug that we should fix

**Comment by emanual4real** [comment]
How about react?  CRA requires you do the `REACT_APP` prefix.

**Comment by emanual4real** [comment]
Lol, I should have tried it first.  It works with `REACT_APP` prefix.  Know any way around this?

**Comment by Bsingh2697** [comment]
> Lol, I should have tried it first. It works with `REACT_APP` prefix. Know any way around this?

Not sure bout react but works fine with react-native when I was using react-native config
