### ISSUE TITLE
Pre- and post- scripts erroneously receive arguments

### ISSUE THREAD

**Issue by Arnesfield** [oven-sh/bun#5199]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

With the following `package.json`:

```json
"scripts": {
  "prebuild": "rimraf lib",
  "build": "rollup -c rollup.config.ts --configPlugin esbuild",
  "start": "npm run build -- -w --no-watch.clearScreen"
}
```

Running `bun start` gives the following output:

```
$ bun run build -- -w --no-watch.clearScreen
$ rimraf lib -w --no-watch.clearScreen
unknown option: -w
run `rimraf --help` for usage information
error: script "prebuild" exited with code 1 (SIGHUP)
error: script "start" exited with code 1 (SIGHUP)
```

From the output above, the args `-w --no-watch.clearScreen` are also passed to the `prebuild` script.

A simpler and more replicable example using only `echo`:

`package.json`:

```json
{
  "scripts": {
    "prebuild": "echo Hi",
    "build": "echo Hello",
    "postbuild": "echo Hey",
    "start": "npm run build -- World"
  }
}
```

Running `bun start` (or `bun run start`):

```
$ bun run build -- World
$ echo Hi World
Hi World
$ echo Hello World
Hello World
$ echo Hey World
Hey World
```

### What is the expected behavior?

`bun run`, unless this is intentional by design, shouldn't pass arguments to pre- and post- scripts similar to `npm run`.

Using the example `package.json` previously, running `npm start` will only pass the args to the main script.

`package.json`:

```json
{
  "scripts": {
    "prebuild": "echo Hi",
    "build": "echo Hello",
    "postbuild": "echo Hey",
    "start": "npm run build -- World"
  }
}
```

Running `npm start` (or `npm run start`):

```
> start
> npm run build -- World


> prebuild
> echo Hi

Hi

> build
> echo Hello "World"

Hello World

> postbuild
> echo Hey

Hey
```

### What do you see instead?

Arguments are being passed to pre- and post- scripts in `bun run` unlike `npm run`.

**Comment by swissspidy** [comment]
I'm still running into the same issue. Is there any workaround?

**Comment by Arnesfield** [comment]
@swissspidy Recently upgraded bun (to v1.0.15) and it looks like this issue has been solved. Using the same reproduction steps, `bun start` now outputs the following:

```
$ bun run build -- World
$ echo Hi
Hi
$ echo Hello World
Hello World
$ echo Hey
Hey
```

**Comment by Arnesfield** [comment]
Did a bit more testing with this, and while the arguments aren't passed to the pre- and post- scripts anymore, it looks like bun doesn't properly handle arguments with spaces (probably this issue: https://github.com/oven-sh/bun/issues/6780)
