### ISSUE TITLE
Next.Js incompatible version ^12.2

### ISSUE THREAD

**Issue by Naicriz** [oven-sh/bun#520]
Bun doesn't work well at all with the latests versions of Nextjs:

```
└> bun dev    
[0.00ms] bun!! v0.1.2

  Link: http://localhost:3000

Possibly incompatible Next.js version:  12.2.2 . Please upgrade to Next.js 11.1.2 or Next.js 12.0.2+.
```

For what i understood, the main problem is that bun scheme isn't supported.

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json.
