### ISSUE TITLE
Bun v1.0.1does not install npm packages using hardlink in node_modules in Linux

### ISSUE THREAD

**Issue by AuroraLantean** [oven-sh/bun#5203]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Bun v1.0.1 the latest does not install npm packages using hardlink in node_modules as described in the documentation below. Even the flag "--backend hardlink" does not work.

My environment: Linux kernel 5.4.0-162-generic, Bun v1.0.1

### Where did you find it?

https://bun.sh/docs/install/cache#saving-disk-space

**Comment by Jarred-Sumner** [comment]
If there are any errors when using hardlinks, it falls back to copying files. Hardlinks cannot be created when crossing filesystem boundaries, for example
