### ISSUE TITLE
vscode - run/debug buttons on npm scripts

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#5204]
### What is the problem this feature would solve?

npm has run/debug buttons for scripts in `package.json`:

![image](https://github.com/oven-sh/bun/assets/57028336/6f4ed29c-2349-4094-a0ab-743d336ff270)

![image](https://github.com/oven-sh/bun/assets/57028336/ae1fcaab-76b1-4b70-98d3-77a98ee962f0)

### What is the feature you are proposing to solve the problem?

the bun extension should replace these so that they run with bun instead of npm

### What alternatives have you considered?

if replacing them isn't possible, perhaps it can add separate bun run/debug buttons alongside the npm ones

**Comment by JeremyFunk** [comment]
This was in #5529 implemented and can be closed.
