### ISSUE TITLE
vscode - show npm scripts as tasks

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#5205]
### What is the problem this feature would solve?

pressing `F1` and typing `Tasks: Run Task` opens this menu:

![image](https://github.com/oven-sh/bun/assets/57028336/f7484180-6bda-445d-a61d-66c1001f6e36)

npm scripts defined in `package.json` show up as tasks under the `npm` category

### What is the feature you are proposing to solve the problem?

a bun category which also shows the npm tasks, but runs them with bun instead of node

related: #5204

**Comment by JeremyFunk** [comment]
This was implemented in #5529 and can be closed.
