### ISSUE TITLE
Support `bun run --workspaces`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#5207]
### What is the problem this feature would solve?

Run a package.json script in all workspaces (if it is defined)

### What is the feature you are proposing to solve the problem?

---

**Comment by Alia5** [comment]
pnpm has a `--filter` param for `pnpm run`

I suggest doing something similar (if not the same) for bun

**Comment by paulleonartcalvo** [comment]
Would love to see this for the sake of monorepo support

**Comment by dangenendt** [comment]
### **+**
Without this, a monorepo is quite hard to manage when it comes to slim and performant docker images made from monorepo parts

**Comment by paulleonartcalvo** [comment]
Seems like a nice QOL issue which could increase early adoption

**Comment by hyoretsu** [comment]
Bump, please add support for this, even if it's a simple cd in and cd out.

**Comment by SahilVasava** [comment]
Yes please. Much needed feature for monorepos.

**Comment by cyrsis** [comment]
Yes Please , Great help to make everything works the same

**Comment by o-az** [comment]
You can create your own `workspace` filter while this is under development:

in `package.json`:

```json
{
  "scripts": {
    "workspace": "bun ./scripts/workspace.ts"
  }
}
```

`./scripts/workspace.ts`
<details>
<summary>File content</summary>


```ts
// ./scripts/workspace.ts

import { file } from 'bun';
import { join } from 'node:path';

const [, , workspace, script] = process.argv;

const runScriptForWorkspace = (w: string) =>
  new Promise<number>((resolve, reject) => {
    console.info(`Running script "${script}" in workspace "${w}"`);
    Bun.spawn({
      cmd: ['bun', 'run', script],
      cwd: `./${w}`,
      stdio: ['inherit', 'inherit', 'inherit'],
      onExit(info) {
        if (info.exitCode !== 0) {
          console.log('The script failed', info.exitCode);
          reject(info.exitCode);
        } else {
          console.log('The script ran successfully');
          resolve(info.exitCode);
        }
      },
    });
  });

if (workspace.includes(',')) {
  const workspaces = workspace.split(',');
  for (const w of workspaces) {
    runScriptForWorkspace(w);
  }
} else if (workspace !== 'all' && !workspace.startsWith('-'))
  runScriptForWorkspace(workspace);
else {
  const excluded = workspace.startsWith('-') && workspace.slice(1);

  const packageJson = JSON.parse(
    await file(join(import.meta.dir, '../package.json')).text(),
  );

  const workspaces = packageJson.workspaces as string[];
  for (const w of workspaces) {
    if (w === excluded) continue;
    await runScriptForWorkspace(w);
  }
}
```

</details>

Then you can run workspaces with `bun run workspace <workspace-script>`.

Here's an example of a project using workspaces with `bun`:

https://github.com/rehype-pretty/rehype-pretty-code/blob/4a41af0c8fb706e26bdd00aec54b9bc384fc318a/package.json#L28
https://github.com/rehype-pretty/rehype-pretty-code/blob/master/scripts/workspace.ts
