### ISSUE TITLE
Peer Dependencies Not Installing in bun 1.0.2

### ISSUE THREAD

**Issue by johnnyhuirilef** [oven-sh/bun#5209]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Using the following package.json file
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native": "^0.72.4"
  }
}
```

And the following bunfig.toml file:

```toml
peer = true
```

Run
`bun install`

### What is the expected behavior?

the expected behavior was for React to be installed. This behavior is the default expectation in npm or pnpm, as React Native relies on React as a peer-dependency. However, in Bun, peer-dependencies are not automatically installed. Furthermore, the CLI's API doesn't provide an option to force the installation of peer dependencies. It also appears that the configuration file is ignoring the 'peer=true' property, even though it is [documented](https://bun.sh/docs/runtime/configuration#default-flags).

**npm**

![image](https://github.com/oven-sh/bun/assets/2802204/2265ffe0-ed34-4f54-998d-c832b76f4ec0)

**pnpm**

![image](https://github.com/oven-sh/bun/assets/2802204/e07efa80-8ddf-420a-b11b-1ab8a862ad92)

bun
![image](https://github.com/oven-sh/bun/assets/2802204/85805447-3550-4c80-9189-1411ed58871a)

### What do you see instead?

what I expected to see instead is the installation of React, as npm and pnpm do this automatically by default. To my knowledge, Yarn provides a flag to enable this installation, which would be helpful for maintaining backward compatibility with projects relying on this feature. Currently, the flag is not available in the command-line interface (CLI), and it seems that the configuration file is ignoring the 'peer=true' property."

**Comment by tobi-or-not-tobi** [comment]
Duplicates #3410
