### ISSUE TITLE
WebSockets cannot receive messages until you send one first

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#521]
Code example
```ts
import { WebSocket } from 'ws';

const ws = new WebSocket(`wss://gateway.discord.gg/?v=10&encoding=json`);
ws.onopen = ev => {
  console.log('open');
};
ws.onclose = ev => {
  console.log('close', ev);
};
ws.onerror = ev => {
  console.log('error', ev);
};
ws.addEventListener('message', msg => {
  console.log(msg.data);
});
```

In bun, we never receive the gateway hello message from Discord. Works fine on node. If we send the identify payload after some time, the rest of the messages come out fine.

**Comment by rexwu1104** [comment]
I meet this problem too.
But I use "encoding=etf".
and the unpack data is garbled.

**Comment by paperclover** [comment]
> I meet this problem too.
> But I use "encoding=etf".
> and the unpack data is garbled.

what are you using to decode the etf data. erlpack on npm wasn't working for me.

**Comment by rexwu1104** [comment]
I use "etf.js", but it isnt work in bun. #343

**Comment by paperclover** [comment]
we've noticed this doesn't happen on a native install of arch linux, whereas i am on windows wsl and it breaks.

**Comment by rexwu1104** [comment]
on bun v0.1.3, the data isnt garbled.
but the problem is still here.
1. cant send the correct data.
2. the data is not receive until send one first.

**Comment by rexwu1104** [comment]
on bun v0.1.4, the second problem resolve.

**Comment by rexwu1104** [comment]
on bun v0.1.5, the problem still alive

**Comment by paperclover** [comment]
running the code snippet above, i get inconsistant results where it sometimes does work and sometimes does not. maybe this is a different issue where the events are being emitted before i'm listening to them. this happens with both `addEventListener` and `onmessage`

![image](https://user-images.githubusercontent.com/24465214/184923884-61bb8738-3439-470e-be98-f38d4db81516.png)

**Comment by Jarred-Sumner** [comment]
The current logic is:
- if there is an event listener bound for the message type, dispatch the message in the same tick
- if there is no event listener bound, dispatch the message in the next tick

This is a non-spec compliant performance optimization. The spec states that events should be delivered next tick.

Perhaps this is silly for open & close and the rest though

**Comment by paperclover** [comment]
i don't think this is an issue on bun 0.1.9 anymore, but there are some other issues preventing a discord gateway connection
