### ISSUE TITLE
TextDecoder incompatibility with Nodejs when explicitly passing undefined

### ISSUE THREAD

**Issue by mouhannad-sh** [oven-sh/bun#5211]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

The following code will throw a TypeError in Bun but would work just fine in Nodejs.
in Bun 1.0.0
```js
new TextDecoder(undefined) // or pass any undefined variable
/** 
 * throws 
 * TypeError: TextDecoder(encoding) label is invalid
 * code: "ERR_INVALID_ARG_TYPE"
 * */
```
in NodeJS v20
```js
new TextDecoder(undefined) // or pass any undefined variable
/**
* TextDecoder { encoding: 'utf-8', fatal: false, ignoreBOM: false }
* */
```
<img width="751" alt="image" src="https://github.com/oven-sh/bun/assets/18495740/41298793-228b-49c2-95a5-7a33cfa8e529">

### What is the expected behavior?

Similar output to NodeJS

### What do you see instead?

```
TypeError: TextDecoder(encoding) label is invalid
 code: "ERR_INVALID_ARG_TYPE"
```

### Additional information

I came across this while I was migrating an existing codebase test suite from nodeJS + Jest to Bun test runner.
it's a small codebase and almost everything worked out of the box 🚀  
except with [MSW's interceptor ](https://github.com/mswjs/interceptors/blob/45df4685cb31d2f66c37fcd60b0f53359d838c98/src/utils/bufferUtils.ts#L7-L10)

https://github.com/mswjs/interceptors/blob/45df4685cb31d2f66c37fcd60b0f53359d838c98/src/utils/bufferUtils.ts#L8

This works in NodeJS without any issues

**Comment by Harshal662** [comment]
I think adding 
```
const decoder = new TextDecoder(encoding || 'utf-8');
```

will help.

**Comment by mouhannad-sh** [comment]
definitely 

> I think adding
> 
> ```
> const decoder = new TextDecoder(encoding || 'utf-8');
> ```
> 
> will help.

It definitely would !
Though I'm sure there are plenty of packages out there in the ecosystem expecting the decoder to work with `undefined`
