### ISSUE TITLE
Calling net socket unref doesn't make process exit

### ISSUE THREAD

**Issue by ArtemGovorov** [oven-sh/bun#5218]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

test.js
```
const s = require('net').Socket();
s.connect(80, 'google.com');
s.write('GET http://www.google.com/ HTTP/1.1\n\n');
s.on('data', function () {
    console.log('some data received, unref socket')
    s.unref()
});
```

node
```
$ node test.js
some data received, unref socket

process exits
```

bun
```
$ bun run test.js
some data received, unref socket

process doesn't exit
```

### What is the expected behavior?

Process should exit on socket unref call.

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago
