### ISSUE TITLE
Bun.serve Works but same thign with express doesn't (WSL - Windows)

### ISSUE THREAD

**Issue by oddbaijanian** [oven-sh/bun#5235]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64 this is WSL my normal pc is Windows 64 bit

### What steps can reproduce the bug?

I use express and bun to make a server on wsl and i can't connect from my windows machine, but if i do the same thing Bun.serve its compeletely fine.

### What is the expected behavior?

both of them working normally

### What do you see instead?

Error: Couldn't resolve host name (Insomnia Output)

### Additional information

https://discord.com/channels/876711213126520882/876711213126520885/1151425633751150643
  Dave from discord asked me to open this issue

**Comment by fardezh** [comment]
It might be a good idea to restart WSL by `wsl --shutdown {distro}` and then starting it.

**Comment by Electroid** [comment]
Can't find the context for this issue. If you are able to provide more info, like a reproducible example, let us know and we'll re-open this issue and investigate

**Comment by oddbaijanian** [comment]
fixed it by moviing to linux LOL.
