### ISSUE TITLE
bunx/bun c no confirmation

### ISSUE THREAD

**Issue by madflow** [oven-sh/bun#5239]
### What is the problem this feature would solve?

When running

```
bunx create-remix
```

or 

```
bun c create-remix
```

there is no confirmation that a package will be installed and a setup script is executed.

This is a security risk which should be addressed.

### What is the feature you are proposing to solve the problem?

* Require a user confirmation with details what is going to happen.
* Implement a `--no-confirmation` flag for the impatient

### What alternatives have you considered?

* ...

**Comment by Electroid** [comment]
This is the inherent purpose of `bunx`, though we do not run pre/post-install scripts for these dependencies.
