### ISSUE TITLE
WebSocket close() method doesnt send code and reason to the server

### ISSUE THREAD

**Issue by ezioda004** [oven-sh/bun#5242]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

```js
const socket = new WebSocket('ws://localhost:8080/');
setTimeout(() => socket.close(1000, "socket closed"), 1000);
```
Code and reason are not being sent to the server.

### What is the expected behavior?

Code and reason should be sent to the server.

### What do you see instead?

Default `1006` code is received by the server and the message is empty.

### Additional information

This works fine in the browser's WebSocket API.

**Comment by WingLim** [comment]
Releated code is here, when code == `1000`, will not send reason. Should fix it.

https://github.com/oven-sh/bun/blob/088bea026e6c49389f51ef6979c5e2d6dfd6d353/src/bun.js/bindings/webcore/WebSocket.cpp#L588-L598

**Comment by ezioda004** [comment]
Hi @WingLim,
I've noticed this happens for other codes as well, `4000` as an example also has the same behavior. My hunch is that the socket connection is being closed abruptly before the close control frame is being received by the server.

**Comment by WingLim** [comment]
> Hi @WingLim, I've noticed this happens for other codes as well, `4000` as an example also has the same behavior. My hunch is that the socket connection is being closed abruptly before the close control frame is being received by the server.

~I am looking in it, it seems to not only releated to code 1000.~

Bun handle this correctly.

**Comment by WingLim** [comment]
Alright, I think we misunderstand about websocket.

When a ws client call `close(code, reason)`, only `client.on('close', (code, reason) => {})` will receive them.

This will not send to server.

And because of client force close connection, the server will receive `1006` code.

Learn more about it on: https://websockets.spec.whatwg.org/#dom-websocket-close

**Comment by ezioda004** [comment]
So bun is missing the close handshake as mentioned here? 
https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.3

**Comment by WingLim** [comment]
> So bun is missing the close handshake as mentioned here? https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.3

No.

Normal close(1000):
- Server -> close -> Client
- Client -> close

Abnormal close(1006):
- Client -> close(without server close control frame)

**Comment by ezioda004** [comment]
> Normal close(1000):
> 
> * Server -> close -> Client
> * Client -> close
> 

In normal close as when client is explicitly calling the `close()` method it needs to send the code and reason to the server. This happens in browsers..and for WebAPI in Bun, shouldn't this behavior be the same?

**Comment by Electroid** [comment]
We need to test our WebSocket client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: https://github.com/oven-sh/bun/issues/6686
