### ISSUE TITLE
Can't install bun on windows

### ISSUE THREAD

**Issue by yairyakobson** [oven-sh/bun#5247]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Windows 11

### What steps can reproduce the bug?

I just get an error that it failed to install

![Bun Installation](https://github.com/oven-sh/bun/assets/32851854/7770dcbd-5191-45cc-b3f3-1863139e6e20)

### What do you see instead?

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for bun@1.0.1: wanted {"os":"darwin,linux","cpu":"arm64,x64"} (current: {"os":"win32","cpu":"x64"})
npm ERR! notsup Valid os:   darwin,linux
npm ERR! notsup Actual os:  win32
npm ERR! notsup Valid cpu:  arm64,x64
npm ERR! notsup Actual cpu: x64

### Additional information

Can Bun be installed on just on macOS and Linux at this point?

And what minimal version of macOS is required because I didn't see it in the documentation

**Comment by kcfuler** [comment]
+1

**Comment by 7heMech** [comment]
![image](https://github.com/oven-sh/bun/assets/83923848/2800d77f-93f7-4112-af45-c7e7d08ef105)
No one said bun was supported on windows, you need wsl.

**Comment by yairyakobson** [comment]
What is wsl?

**Comment by 7heMech** [comment]
@yair2000 [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/)
It basically lets you run linux on windows.

**Comment by AdrianoLupossa** [comment]
Windows Subsystem for Linux (WSL) is the right env to run bun on windows

**Comment by yairyakobson** [comment]
Thanks for the tip!

‫בתאריך יום ד׳, 13 בספט׳ 2023 ב-14:44 מאת ‪Adriano Lupossa‬‏ <‪
***@***.***‬‏>:‬

**Comment by ghiscoding** [comment]
duplicate of #43

**Comment by Hecatron** [comment]
> Windows Subsystem for Linux (WSL) is the right env to run bun on windows

WSL means enabling Hyper-V
Hyper-V means that you're actually running the main OS inside a virtual machine
this can impact things such as gaming, so I've always avoided it myself.

The other option is Msys2 which sort of simulates unix api's under windows in a shell.
But it looks as if the curl command `curl -fsSL https://bun.sh/install | bash` doesn't work under Msys2 due to the os detection within bun picking up that it's windows and blocking it from running

**Comment by icjosh10** [comment]
> ![image](https://user-images.githubusercontent.com/83923848/267597993-2800d77f-93f7-4112-af45-c7e7d08ef105.png) No one said bun was supported on windows, you need wsl.

Except [the docs](https://bun.sh/docs/installation) literally do say that bun is supported (just in a limited capacity).

**Comment by Hecatron** [comment]
In https://github.com/oven-sh/bun/issues/43 they say it's being worked on
I don't think you can ask more than that to be fair, it sounds as if the native build is still experimental.

**Comment by yairyakobson** [comment]
Ok, thanks for the update.

‫בתאריך יום ו׳, 15 בספט׳ 2023 ב-22:38 מאת ‪Hecatron‬‏ <‪
***@***.***‬‏>:‬

**Comment by WasathTheekshana** [comment]
## Hi @yair2000 !

[npm official page](https://www.npmjs.com/package/bun?activeTab=readme) tells, that you need to install Bun 1.0 on WLS (Windows Subsystem for Linux)

![Screenshot 2023-09-16 133113](https://github.com/oven-sh/bun/assets/91784445/a3eeb857-5f28-49c8-8ff0-d466994c85a0)

1. Try installing WSL from windows store & on top of it install the bun
[How to install WSL](https://learn.microsoft.com/en-us/windows/wsl/install)

2. After that refer the bun official doc installation guide.

``` 
curl -fsSL https://bun.sh/install | bash
```
[Bun Docs](https://bun.sh/docs)

**Comment by huangkaoya** [comment]
why bun not supported windows?

**Comment by GabrielDougherty** [comment]
On https://bun.sh/docs/installation#windows it says:

> Bun provides a limited, experimental native build for Windows. At the moment, only the Bun runtime is supported.
> 
> bun <file>
> bun run <file>

I am interested in obtaining that experimental native build rather than the WSL one.

**Comment by Hecatron** [comment]
If you search the existing messages
The main tracking issue for windows support is - https://github.com/oven-sh/bun/issues/43
The pull request being worked on is - https://github.com/oven-sh/bun/pull/4410

I suspect you'd have to try and manually build the source (from the pull request)
although I have no idea if it even works at this point, since I've not tried it myself

**Comment by faizov** [comment]
It's really sad that we can't use in windows directly. Can WSL affect performance?

**Comment by Anubarak** [comment]
> ![image](https://user-images.githubusercontent.com/83923848/267597993-2800d77f-93f7-4112-af45-c7e7d08ef105.png) No one said bun was supported on windows, you need wsl.

Well actually they said it in their release notes

https://bun.sh/blog/bun-v1.0#bun-more-thing

> Bun provides native builds for macOS and Linux, but there's been one notable absence: Windows. Previously, to run Bun on Windows, you would need to install Windows Subsystem for Linux... **but not anymore.**
> For the first time, we're excited to release an experimental, native build of Bun for Windows.

Sorry if I get this wrong but for this sounds like it is indeed supported. Experimental and not completed but installable at least.

**Comment by kangfredy** [comment]
hope it will works on windows

**Comment by abhishekpatelmc** [comment]
Why can't we use Bun on Windows currently?
How does JSC prevent Bun from running on Windows?

**Comment by Hecatron** [comment]
> Why can't we use Bun on Windows currently? How does JSC prevent Bun from running on Windows?

if you read the above comments, it's still be worked on
I posted links to the pull request and issue where it's being worked on

**Comment by Stanzilla** [comment]
I'm confused by this as well, if there is a native build, npm should not refuse to install it. If there is not, the docs need to be updated.

**Comment by Electroid** [comment]
Please track this issue for when Windows is ready: #43 (we're actively working on it)

**Comment by JRBros2346** [comment]
It is noted in installation page that windows have runtime support. But i cant find any runtimee binaries

**Comment by fras-alfurasy** [comment]
when it's going to be supported for windows ????

**Comment by BenjaBobs** [comment]
@Fras999 see #43

**Comment by yechielb2000** [comment]
you can also downlaod this https://www.microsoft.com/en-us/download/details.aspx?id=53840
