### ISSUE TITLE
Warn on missing peer dependencies

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#527]
recreate issue: `bun add @purplet/gateway`. will not warn for missing `discord-api-types`. make sure it doesn't warn for optional peer dependencies which are defined by `peerDependenciesMeta[pkg].optional` being true. our package has two optional peer deps.

**Comment by Hebilicious** [comment]
Imo, this issue is very important when considering a switch from pnpm/yarn to bun.

**Comment by nelson6e65** [comment]
There is a `peer` flag in [the configuration file](https://bun.sh/docs/runtime/configuration#default-flags), but setting it to `true` does not seem to work.

**Comment by Jarred-Sumner** [comment]
We do warn on missing peer dependencies nowadays
