### ISSUE TITLE
spyOn is wrongly typed

### ISSUE THREAD

**Issue by marvinside** [oven-sh/bun#5279]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import { test, expect, spyOn } from "bun:test";

class Dummy {
  public method(param: string) {
    return "original" + param;
  }
}

spyOn(Dummy.prototype, "method").mockImplementation(
  () => (param: string) => "mocked value" + param
);

test.only("spy should overwrite value", () => {
  const instance = new Dummy();
  expect(instance.method("param1")).toBe("mocked valueparam1");
});
```

Then run `bun test`

### What is the expected behavior?

```
bun test v1.0.0 (822a00c4)

test/bun.test.ts:
✓ spy should overwrite value [1.27ms]
```

### What do you see instead?

```
bun test v1.0.0 (822a00c4)

test/bun.test.ts:
10 |   () => (param: string) => "mocked value" + param
11 | );
12 | 
13 | test.only("spy should overwrite value", () => {
14 |   const instance = new Dummy();
15 |   expect(instance.method("param1")).toBe("mocked valueparam1");
      ^
error: expect(received).toBe(expected)

Expected: "mocked value"
Received: [Function]
```

### Additional information

The signature for the `spyOn` in combination with `mockImplementation` is wrong.

Changing the test to
```ts
spyOn(Dummy.prototype, "method").mockImplementation(
  (param: string) => "mocked value" + param
);
```

will result in a passing test but create the following typescript error:
```
test/bun.test.ts(10,3): error TS2345: Argument of type '(param: string) => string' is not assignable to parameter of type '() => (param: string) => string'.
  Target signature provides too few arguments. Expected 1 or more, but got 0.
```

The issue comes from `bun-types`:
```ts
export function spyOn<T extends object, K extends keyof T>(
    obj: T,
    methodOrPropertyValue: K,
  ): Mock<() => T[K]>;
 ```
 and
 ```ts
export interface MockInstance<T extends FunctionLike = UnknownFunction> {
    mockImplementation(fn: T): this;
    mockImplementationOnce(fn: T): this;
  }
```
Where T equals `() => T[K]` therefore resulting in `() => (param: string) => string` instead of `(param:string) => string`

**Comment by winghouchan** [comment]
I suspect the type for `spyOn` was written like that to accommodate spying on properties that aren't functions as from the tests it looks like this a capability in Bun: https://github.com/oven-sh/bun/blob/64033f11cc42e000ea3a67d7790359eeb21a7a00/test/js/bun/test/mock-fn.test.js#L557-L571

I see there are [type tests](https://github.com/oven-sh/bun/blob/main/packages/bun-types/tests/test.test-d.ts) as well but not sure what's going on here as types don't seem to be actually tested here.

I think `Mock<T[K] extends (...args: any) => any ? T[K] : () => T[K]>` on L117 in `bun-types/bun-test.d.ts` would accommodate properties that are either functions or non-functions. Testing this locally resolves the issue for me. https://github.com/oven-sh/bun/blob/64033f11cc42e000ea3a67d7790359eeb21a7a00/packages/bun-types/bun-test.d.ts#L114-L117

@paperdave @Electroid do you have thoughts on this as you've both touched a lot of these areas? With some feedback, I'd be happy to put a PR for this. Just keen to check I've understood everything as elaborated above.

**Comment by marvinside** [comment]
Seems to work now with bun-types@1.0.7. Closing issue
