### ISSUE TITLE
NextAuth: Bun is not defined

### ISSUE THREAD

**Issue by uaktags** [oven-sh/bun#5286]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.0-75-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a nextjs project
Add nextauth
configure login against a database
Attempt to use Bun.password

```
providers: [
    CredentialsProvider({
      credentials: {
        email: { label: 'Email', type: 'email' },
        password: { label: 'Password', type: 'password' },
        race: { label: 'Race', type: 'text' },
      },

      async authorize(credentials) {
        const { email, password } = credentials ?? {};
        if (!email || !password) {
          throw new Error('Missing username or password');
        }
        const user = await prisma.users.findUnique({
          where: {
            email,
          },
        });
        // if user doesn't exist or password doesn't match
        if (!user || !(await Bun.password.verify(password, user.password_hash))) {
          throw new Error('Invalid username or password');
        }
        ```

### What is the expected behavior?

A correct password should be achieved.

### What do you see instead?

We get a failure due to "Bun is not defined":
http://192.168.4.19:3002/api/auth/error?error=Bun%20is%20not%20defined"

**Comment by rajput-hemant** [comment]
The error `Bun is not defined` occurs because it still uses `Node.js` to spin up the development server. 

According to https://bun.sh/guides/ecosystem/nextjs:

> Next.js currently relies on Node.js APIs that Bun does not yet implement. The guide below uses Bun to initialize a project and install dependencies, but it uses Node.js to run the dev server.

**Comment by colinhacks** [comment]
At the moment, you can run a Next.js app using Bun like this:

```
$ bun --bun run dev
```

This will use Bun to run the dev server, so this should work. But the App Router is still not supported, so if you rely on that, you should avoid any `Bun` APIs for now.

**Comment by uaktags** [comment]
Thanks guys, I had thought I saw that NextJS was fully supported but I must have misinterpreted that. I'll keep an eye on the development for when that comes to be ready for the Router and rest of the framework.
