### ISSUE TITLE
The behavior of dynamic import changed on version 1.0.1 (duplicate entries)

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#5299]
### What version of Bun is running?

1.0.1+c3455c0ceee6bbe399781819a42fff6cf24792e2

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

`config.json`
> not related to json files...
we going to have the same behavior also with toml..

```json
{
    "key_1": "value 1",
    "key_2": "value 2",
    "key_3": "value 3",
    "key_4": "value 4",
    "key_5": "value 5"
}
```

`index.ts`

```ts
const content = await import("./config.json");

console.log(content);
```

 run `bun index.ts`

### What is the expected behavior?

```js
Module {
  default: {
    key_1: "value 1",
    key_2: "value 2",
    key_3: "value 3",
    key_4: "value 4",
    key_5: "value 5"
  }
}
```

### What do you see instead?

```js
Module {
  default: {
    key_1: "value 1",
    key_2: "value 2",
    key_3: "value 3",
    key_4: "value 4",
    key_5: "value 5"
  },
  key_1: "value 1",
  key_2: "value 2",
  key_3: "value 3",
  key_4: "value 4",
  key_5: "value 5"
}
```

**Comment by TiBianMod** [comment]
```ts
const content = await import("./config.json", {
    assert: {
        type: "json",
    },
});

console.log(content);
```

> you can compare also the difference between `node` and `bun`

**Comment by Electroid** [comment]
This is because Bun now allows you to have named imports, e.g.:

```js
const { key_1 } = await import("./config.json");
```

https://bun.sh/blog/bun-v1.0.1#named-imports-for-json-toml-files

**Comment by TiBianMod** [comment]
@Electroid will be nice the [Blog](https://bun.sh/blog) to include the release notes of 1.0.1 (like all the other releases)
