### ISSUE TITLE
Spaces and quotes aren't handled correctly by bun run

### ISSUE THREAD

**Issue by KishanBagaria** [oven-sh/bun#53]
package.json:
```json
{
  "scripts": {
    "argv": "node -e 'console.log(process.argv)'"
  }
}
```
<img width="1202" alt="" src="https://user-images.githubusercontent.com/1093313/140414358-aef402ab-8682-47d2-923c-538251876912.png">

<img width="546" alt="Screenshot 2021-11-05 at 1 55 05 AM" src="https://user-images.githubusercontent.com/1093313/140414605-2059676c-a547-4f1d-a3f9-47b23f0009ba.png">

**Comment by Jarred-Sumner** [comment]
working on a fix

**Comment by KishanBagaria** [comment]
looks like it's not fully identical to npm behavior (i've to use `\"` instead of just `"`):

<img width="536" alt="" src="https://user-images.githubusercontent.com/1093313/140580006-7df1bad3-fd85-44c3-b4bf-07d49f3d5384.png">

(this is fish)

**Comment by kidonng** [comment]
Not sure if the following issue is related:

```shellsession
❯ bat -p package.json 
{
  "name": "blank",
  "version": "0.0.3",
  "module": "src/index.js",
  "scripts": {
    "demo": "echo \"test\""
  },
  "devDependencies": {
    "bun-types": "latest"
  }
}

❯ npm run demo

> blank@0.0.3 demo
> echo "test"

test

❯ bun run demo
$ echo \"test\"
"test"
```

Basically npm does JSON parsing but bun doesn't seem to do it.

**Comment by Electroid** [comment]
Thanks for reproducing, @kidonng, confirmed it's still an issue as of `0.2.2`. We'll get it fixed.

**Comment by lutzissler** [comment]
Confirming this is still an issue with `0.5.9`:

```json
 "scripts": {
        "start": "bun run src/app.ts",
        "add:article": "curl -X POST -H 'Content-Type: application/json' -d '{\"id\":1,\"title\":\"Test article\",\"body\":\"Test body\"}' http://localhost:4000/articles/"
    }
```

Running this won’t work with Bun:

```bash
$ bun run add:article
$ curl -X POST -H 'Content-Type: application/json' -d '{\"id\":1,\"title\":\"Test article\",\"body\":\"Test body\"}' http://localhost:4000/articles/
{
  "title": "Bad Request",
  "status": 400,
  "detail": "Unable to parse JSON: JSON Parse error: Unrecognized token '\\'"
}
```

But it does with npm:

```bash
$ npm run add:article

> @ add:article
> curl -X POST -H 'Content-Type: application/json' -d '{"id":1,"title":"Test article","body":"Test body"}' http://localhost:4000/articles/
```

The reason is clearly that Bun doesn’t parse JSON as [stated above](https://github.com/oven-sh/bun/issues/53#issuecomment-1197356249).
