### ISSUE TITLE
Projects on different file system: error: NotSameFileSystem

### ISSUE THREAD

**Issue by adi-g15** [oven-sh/bun#531]
### What is the problem this feature will solve?

Some people may have projects on different partitions with different filesystems, than their home and root filesystems.
`bun` currently shows **error: NotSameFileSystem** in this case.

For eg. it can be reproduced like this:

1. Create your project in different file system, say a 'tmpfs', eg. `/tmp` on many systems is tmpfs:

   ```sh
   mkdir /tmp/proj
   cd /tmp/proj
   ```

2. Create a package.json, maybe using "npm init -y"
3. Install dependencies

   ```sh
   bun install
   ```

### What is the feature you are proposing to solve the problem?

Support projects on different filesystems.

### What alternatives have you considered?

Keeping projects in my subdirectories inside home directory.

**Comment by BeamNawapat** [comment]
could you try this?

```
bun install --backend=copyfile
```

**Comment by adi-g15** [comment]
> could you try this?
> 
> ```
> bun install --backend=copyfile
> ```

It worked ! Thanks @BeamNawapat :smiley: !

I read some code in the repo, thanks to you telling about the --backend=copyfile flag, I think in the relevant code is [here](https://github.com/Jarred-Sumner/bun/blob/f5d896542ae5a9e0b62c73d386727392d32489e0/src/install/install.zig#L1062-L1074).

In the switch, inside the else block, when `clonefile` backend fails, the error `NotSameFilesystem` can be added to the case like this?

```diff
-error.NotSupported => {
+error.NotSameFileSystem, error.NotSupported => {
     supported_method = .copyfile;
 },
```

It's already handled like this in case of `hardlink`,

https://github.com/Jarred-Sumner/bun/blob/f5d896542ae5a9e0b62c73d386727392d32489e0/src/install/install.zig#L1103-L1105

**Comment by FinnRG** [comment]
@adi-g15 Yes, I think that should work. Do you want to put up a PR for this?

**Comment by adi-g15** [comment]
> @adi-g15 Yes, I think that should work. Do you want to put up a PR for this?

Done :+1:

I think the error can happen in the `clonefile_each_dir` case too, have mentioned that in the PR. Thanks.

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago
