### ISSUE TITLE
In-source unit testing

### ISSUE THREAD

**Issue by ethanjdiamond** [oven-sh/bun#5313]
### What is the problem this feature would solve?

Vitest supports [in-source testing](https://vitest.dev/guide/in-source.html), which allows tests to be colocated with the file they're testing. This has several advantages:

- No need to keep test and src directories separate and in sync
- Needed modules for mocking are already loaded
- Easy to spot under-tested classes
- When breakpointing to debug, it's all within the same file

### What is the feature you are proposing to solve the problem?

Add the ability for Bun testing to also colocate with source code. This would involve being able to put the code in a block that the compiler cleans out for production builds. 

### What alternatives have you considered?

The alternative would be to not support this, which would be a shame but I understand it's a personal preference.

**Comment by TiranexDev** [comment]
Duplicate of #3560

**Comment by ethanjdiamond** [comment]
Closing as dupe and adding comment to other issue (thanks Tiranex).
