### ISSUE TITLE
Bun cannot handle a large stdout

### ISSUE THREAD

**Issue by codymikol** [oven-sh/bun#5319]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Found this while building an auditing report tool that prints our a large JSON blob, but you can reproduce this very easily in bun with this script that prints out an "=" n times

This will be fine

```javascript
import {exec} from "child_process";

exec("printf '=%.0s' {1..262144}")
```

If we increase n by one, bun will crash

```javascript
import {exec} from "child_process";

exec("printf '=%.0s' {1..262145}")
```

Probably some kind of memory allocation problem 🤷 

### What is the expected behavior?

It just returns the stdout

### What do you see instead?

```
TypeError: second argument to Function.prototype.apply must be an Array-like object
      at onChildStdoutEncoded (node:child_process:122:96)
      at addChunk (node:stream:1940:42)
      at readableAddChunk (node:stream:1894:58)
      at node:stream:13:342
      at node:stream:101:102
      at processTicksAndRejections (:1:2602)
```

### Additional information

Thanks for all your hard work 🤠

**Comment by codymikol** [comment]
~~Has something to do with this event handler that's registered when buffers are supposed to have infinite size~~

```javascript
      child.stdout.on(
          "data",
/
          function onUnlimitedSizeBufferedData(chunk) {
            ArrayPrototypePush.call(_stdout, chunk);
          },
      );
```

**Comment by codymikol** [comment]
`ArrayPrototypePush.call(_stdout, StringPrototypeSlice.apply(chunk, 0, truncatedLen));`
 
 truncatedLen here is actually NaN

**Comment by codymikol** [comment]
I actually don't think that is the issue either, because it seems to be NaN in both cases where the string is too long / not too long. 

Latest suspicion is that this is busted

StringPrototypeSlice.apply(chunk, 0, truncatedLen)

I can't seem to get the result of that to log and it would explain the function failing.

**Comment by codymikol** [comment]
I got it, PR coming soon

**Comment by codymikol** [comment]
Kinda lost on these tests, bun test doesn't seem to be evaluating my changes in child_process, is there a more correct way to run these tests?

**Comment by Aviortheking** [comment]
Hey, any news on this ? I have the same problem currently

**Comment by codymikol** [comment]
It's fixed in my PR, whenever they have time to merge it should be resolved

**Comment by codymikol** [comment]
@Electroid is this good to merge?

**Comment by Morglod** [comment]
Current workaround for this with temp file:

```ts
const tmpFileName = `./exec_tmp_${Date.now()}_${Math.floor(Math.random() * 9999)}`;

execSync(command + " > " + tmpFileName);

// read file
const data = await Bun.file(tmpFileName) // .text() / .json() ...

rmSync(tmpFileName);

// use data
```
