### ISSUE TITLE
Creating a project with Astro

### ISSUE THREAD

**Issue by jrealesdelaossa** [oven-sh/bun#5323]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 6.4.15-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

The error occurs when trying to create an astro project according to the framework documentation.

By running the following command line in the terminal: `bunx create-astro@latest my-first-proyect-astro`

![image](https://github.com/oven-sh/bun/assets/103285208/62b7304b-ac46-4c31-9ba8-cfaa3cecc58e)

### What is the expected behavior?

The creation of the Astro project

### What do you see instead?

It remains in the creation of the template.

![image](https://github.com/oven-sh/bun/assets/103285208/0e7db22a-2b7b-4b88-9075-2df30da77c64)

**Comment by AimForNaN** [comment]
This has happened to me with npm, too. It is likely some kind of network issue that may resolve on its own (like it did with me).
