### ISSUE TITLE
Support VitePress build

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5328]
Hi everyone,

Been trying to run `bunx --bun vitepress build docs` but oddly getting the issues seen in the screenshot. It's just a dummy install, using the `--bun`. Without the bun option, it builds properly (as seen in the follow-up image).

Any ideas?

Thanks!

![image.png](https://cdn.discordapp.com/attachments/1151691262559277227/1151691262928355450/image.png)

![image.png](https://cdn.discordapp.com/attachments/1151691262559277227/1151691263351996426/image.png)

_Originally reported on Discord: [`vitepress build issue`](https://discord.com/channels/876711213126520882/1151691262559277227/1151691262559277227)_

**Comment by birkskyum** [comment]
Duplicate of #3791

**Comment by brc-dd** [comment]
This can be closed I guess.
