### ISSUE TITLE
Import other package manager's lockfile

### ISSUE THREAD

**Issue by mkismy** [oven-sh/bun#5330]
### What is the problem this feature would solve?

If you want to switch to bun from another package manager it is mandatory to follow the existing lock file, especially in a large project.

Currently there are no such feature and the only way is to "clean install" libraries.

### What is the feature you are proposing to solve the problem?

Add an alternative feature to [`pnpm import`](https://pnpm.io/cli/import) and support pnpm, yarn, npm lock files.

**Comment by fregante** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/1751

**Comment by Jarred-Sumner** [comment]
Closing as duplicate
