### ISSUE TITLE
Allow multiple lines in REPL mode

### ISSUE THREAD

**Issue by ffxsam** [oven-sh/bun#5339]
### What is the problem this feature would solve?

I can't paste code into the Bun REPL if it's more than one line. This feature would solve that.

### What is the feature you are proposing to solve the problem?

In Node.js, it's possible in the REPL to write multiple lines, e.g.:
```
> function yo() {
... console.log('yo!');
... }
```
Currently, Bun doesn't allow this so it's not possible to paste in code fragments to test, at least if it involves functions or other statements that take multiple lines to complete.

**Comment by jhmaster2000** [comment]
Implemented in https://github.com/jhmaster2000/bun-repl/commit/a55daf9bfc9ecd01f57d1f5f14a046bf2b15fe03 (repl v2.0.7)

Use Alt+N to insert a newline anywhere or Alt+M to enable freeform multiline mode (similar to `.editor` in node repl).
Also see `.help` for more info

**Comment by ffxsam** [comment]
@jhmaster2000 Is this correct? There's no such thing as "Alt+M" on Mac. Hitting alt/option+M just prints a µ character, and Bun doesn't detect that. Ctrl+M doesn't work either.

**Comment by jhmaster2000** [comment]
I don't have a Mac so I don't know but it should be whatever key is the `meta` key as Node calls it (which is Alt in Windows/Linux).

If you can't find it there's also the command you can use: `.multiline`

Note: It could also be a bug with Bun's process on keypress detection code on Mac only but needs further testing.

**Comment by ffxsam** [comment]
Aha! Esc-M on the Mac works. I suppose the `.help` should show that if the OS is Darwin.

Thanks for your help!

**Comment by jhmaster2000** [comment]
Ah good to know, yeah I'll make it adapt based on the OS next update, thanks 👍

**Comment by onionhammer** [comment]
You should be able to paste multiple lines with a mouse, for example in a VS Code terminal. The alt+m/escape+m thing is not super intuitive

**Comment by jhmaster2000** [comment]
@onionhammer I assume you're referring to being able to bracketed-paste regardless of multiline mode being enabled, if so that is planned, but in the meantime you should be able to do a multiline paste without issues inside multiline mode, if you're not experiencing that please do let me know.
