### ISSUE TITLE
WebSocket connection // WASM initialization fails in `polkadot-js/api`

### ISSUE THREAD

**Issue by wottpal** [oven-sh/bun#5342]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Run the script from the following issue: https://github.com/polkadot-js/api/issues/5727 with the dependency `@polkadot/api` installed & a [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node) running in the background. Then it fails to establish the underlying WebSocket connection. I expect this might be some underlying issue not even directly related to `polkadot-js/api` as everything runs fine when executed with `ts-node`.

```bash
# Works ✅
bunx ts-node main.ts

# Fails 🚫
bun run main.ts
```

### What is the expected behavior?

Initialize successfully; print nothing.

### What do you see instead?

```bash
➜  bun run main.ts
2023-09-10 17:00:40          API-WS: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: getBlockHash(blockNumber?: BlockNumber): BlockHash:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: getRuntimeVersion(at?: BlockHash): RuntimeVersion:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: chain(): Text:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: properties(): ChainProperties:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: methods(): RpcMethods:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        RPC-CORE: getMetadata(at?: BlockHash): Metadata:: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
2023-09-10 17:00:40        API/INIT: 306 |                 this._isReady = true;
307 |                 this.emit('ready', this);
308 |             }
309 |         }
310 |         catch (_error) {
311 |             const error = new Error(`FATAL: Unable to initialize the API: ${_error.message}`);
                              ^
error: FATAL: Unable to initialize the API: disconnected from ws://127.0.0.1:9944: 1001:: Going Away
      at /.../bun-test/node_modules/@polkadot/api/base/Init.js:311:26
```

### Additional information

I decided to open the issue here as indicated by @Jarred-Sumner on Twitter he doesn't want to see existing package owners spammed with issues that are most probably related to bun.

Also, I tried to identify existing WebSocket-related issued that have been opened here, but was unable to find a related one.

**Comment by SealTV** [comment]
Have the same issue.

**Comment by btwiuse** [comment]
Hi, if you set `initWasm` to `false`, the problem goes away.

```
ApiPromise.create({
  initWasm: false,
})
```

So I think it has nothing to do with websocket. It's more of a WASM problem.

**Comment by wottpal** [comment]
Very interesting, @btwiuse – Thanks for sharing. Updated the title.

**Comment by xlc** [comment]
I don't think this is a wasm issue. At least `await cryptoWaitReady()` returns successfully, which is what `initWasm: false` disabled.

<img width="550" alt="Screenshot 2023-10-17 at 12 20 38 PM" src="https://github.com/oven-sh/bun/assets/1201310/8c4f10dd-e263-47d9-9404-ea4f3650ee53">

The websocket is receiving `close` event for some reason

**Comment by xlc** [comment]
I simplified the setup and ended up with this https://github.com/oven-sh/bun/issues/6543

**Comment by Electroid** [comment]
We need to test our WebSocket client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: https://github.com/oven-sh/bun/issues/6686

**Comment by Electroid** [comment]
Duplicate of #6686
