### ISSUE TITLE
Error when using `sharp` module with Bun

### ISSUE THREAD

**Issue by 0xtlt** [oven-sh/bun#5345]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I've created a repository that reproduces the issue. You can find it here: [Reproduction Repository](https://github.com/0xtlt/bun-sharp-error)

Alternatively, here's the code snippet that reproduces the issue:

```javascript
import sharp from "sharp";

const image = await Bun.file("./F5gsX_DWwAAVcCy.png").arrayBuffer();

// Error occurs below
await sharp(image).resize(128).png({ quality: 80 }).toBuffer();
```

### What is the expected behavior?

The `sharp` module should function without errors, allowing image manipulation tasks to be executed.

### What do you see instead?

The error message I receive is as follows:

```
if (loadedModule) {
const [, loadedPackage] = loadedModule.match(/node_modules[/]([^/]+)[/]/);
help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
}
throw new Error(help.join('n'));
```

```
error:
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "/....../node_modules/sharp/lib/sharp.js"
```

**Comment by birkskyum** [comment]
Related:
- https://github.com/oven-sh/bun/issues/4549

**Comment by 0xtlt** [comment]
Ok guys, I found how to makes it work:

Just add "sharp" in your "trustedDependencies" package.json :)

**Comment by Nnadivictory25** [comment]
> trustedDependencies

unfortunately this did not work for me
