### ISSUE TITLE
Running "bun create vite myapp" on win10 WSL causes this error

### ISSUE THREAD

**Issue by ShimiShimson** [oven-sh/bun#5351]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Win10 Pro WSL Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

![image](https://github.com/oven-sh/bun/assets/45741410/1704485c-96b3-4743-b9f8-d61827e13a6b)

On WSL run inside VSCode powershell terminal:
@anon
`curl https://bun.sh/install | bash`
`sudo apt-get install --reinstall build-essential`
`sudo apt-get update && sudo apt-get upgrade`
`sudo -i`
@root
`sudo apt-get update`
`sudo apt-get install nodejs`
`su -anon`
@anon 
`bun create vite test-app`

### What is the expected behavior?

Creating Vite app

### What do you see instead?

**The result is:**
file:///tmp/create-vite@latest--bunx/node_modules/create-vite/dist/index.mjs:48
`),this.close()}_(t,s){return t.toLowerCase()==="y"?(this.value=!0,this.submit()):t.toLowerCase()==="n"?(this.value=!1,this.submit()):this.bell()}render(){this.closed||(this.firstRender?this.out.write(Ie.hide):this.out.write(jr(this.outputText,this.out.columns)),super.render(),this.outputText=[_e.symbol(this.done,this.aborted),De.bold(this.msg),_e.delimiter(this.done),this.done?this.value?this.yesMsg:this.noMsg:De.gray(this.initialValue?this.yesOption:this.noOption)].join(" "),this.out.write(Nr.line+Ie.to(0)+this.outputText))}}var Lr=Fr,kr={TextPrompt:ci,SelectPrompt:gi,TogglePrompt:$i,DatePrompt:hr,NumberPrompt:gr,MultiselectPrompt:Ee,AutocompletePrompt:Mr,AutocompleteMultiselectPrompt:Rr,ConfirmPrompt:Lr};(function(e){const t=e,s=kr,i=r=>r;function n(r,l,d={}){return new Promise((a,b)=>{const p=new s[r](l),h=d.onAbort||i,c=d.onSubmit||i,g=d.onExit||i;p.on("state",l.onState||i),p.on("submit",x=>a(c(x))),p.on("exit",x=>a(g(x))),p.on("abort",x=>b(h(x)))})}t.text=r=>n("TextPrompt",r),t.password=r=>(r.style="password",t.text(r)),t.invisible=r=>(r.style="invisible",t.text(r)),t.number=r=>n("NumberPrompt",r),t.date=r=>n("DatePrompt",r),t.confirm=r=>n("ConfirmPrompt",r),t.list=r=>{const l=r.separator||",";return n("TextPrompt",r,{onSubmit:d=>d.split(l).map(a=>a.trim())})},t.toggle=r=>n("TogglePrompt",r),t.select=r=>n("SelectPrompt",r),t.multiselect=r=>{r.choices=[].concat(r.choices||[]);const l=d=>d.filter(a=>a.selected).map(a=>a.value);return n("MultiselectPrompt",r,{onAbort:l,onSubmit:l})},t.autocompleteMultiselect=r=>{r.choices=[].concat(r.choices||[]);const l=d=>d.filter(a=>a.selected).map(a=>a.value);return n("AutocompleteMultiselectPrompt",r,{onAbort:l,onSubmit:l})};const o=(r,l)=>Promise.resolve(l.filter(d=>d.title.slice(0,r.length).toLowerCase()===r.toLowerCase()));t.autocomplete=r=>(r.suggest=r.suggest||o,r.choices=[].concat(r.choices||[]),n("AutocompletePrompt",r))})(oe);const Nt=oe,Hr=["suggest","format","onState","validate","onRender","type"],Re=()=>{};async function V(e=[],{onSubmit:t=Re,onCancel:s=Re}={}){const i={},n=V._override||{};e=[].concat(e);let o,r,l,d,a,b;const p=async(h,c,g=!1)=>{if(!(!g&&h.validate&&h.validate(c)!==!0))return h.format?await h.format(c,i):c};for(r of e)if({name:d,type:a}=r,typeof a=="function"&&(a=await a(o,{...i},r),r.type=a),!!a){for(let h in r){if(Hr.includes(h))continue;let c=r[h];r[h]=typeof c=="function"?await c(o,{...i},b):c}if(b=r,typeof r.message!="string")throw new Error("prompt message is required");if({name:d,type:a}=r,Nt[a]===void 0)throw new Error(`prompt type (${a}) is not defined`);if(n[r.name]!==void 0&&(o=await p(r,n[r.name]),o!==void 0)){i[d]=o;continue}try{o=V._injected?Yr(V._injected,r.initial):await Nt[a](r),i[d]=o=await p(r,o,!0),l=await t(r,o,i)}catch{l=!await s(r,i)}if(l)return i}return i}function Yr(e,t){const s=e.shift();if(s instanceof Error)throw s;return s===void 0?t:s}function Vr(e){V._injected=(V._injected||[]).concat(e)}function Br(e){V._override=Object.assign({},e)}var Gr=Object.assign(V,{prompt:V,prompts:Nt,inject:Vr,override:Br});const Jr=ft(Gr);let W=!0;const X=typeof self<"u"?self:typeof window<"u"?window:typeof global<"u"?global:{};let it=0;if(X.process&&X.process.env&&X.process.stdout){const{FORCE_COLOR:e,NODE_DISABLE_COLORS:t,NO_COLOR:s,TERM:i,COLORTERM:n}=X.process.env;t||s||e==="0"?W=!1:e==="1"||e==="2"||e==="3"?W=!0:i==="dumb"?W=!1:"CI"in X.process.env&&["TRAVIS","CIRCLECI","APPVEYOR","GITLAB_CI","GITHUB_ACTIONS","BUILDKITE","DRONE"].some(o=>o in X.process.env)?W=!0:W=process.stdout.isTTY,W&&(process.platform==="win32"||n&&(n==="truecolor"||n==="24bit")?it=3:i&&(i.endsWith("-256color")||i.endsWith("256"))?it=2:it=1)}let Ae={enabled:W,supportLevel:it};function A(e,t,s=1){const i=`\x1B[${e}m`,n=`\x1B[${t}m`,o=new RegExp(`\\x1b\\[${t}m`,"g");return r=>Ae.enabled&&Ae.supportLevel>=s?i+(""+r).replace(o,i)+n:""+r}const B=A(0,0),ct=A(31,39),je=A(32,39),j=A(33,39),k=A(34,39),Wr=A(35,39),zr=A(36,39),qr=A(91,39),Ur=A(92,39),Ft=A(94,39),Lt=Ms(process.argv.slice(2),{string:["_"]}),kt=process.cwd(),Ht=[{name:"vanilla",display:"Vanilla",color:j,variants:[{name:"vanilla-ts",display:"TypeScript",color:k},{name:"vanilla",display:"JavaScript",color:j}]},{name:"vue",display:"Vue",color:je,variants:[{name:"vue-ts",display:"TypeScript",color:k},{name:"vue",display:"JavaScript",color:j},{name:"custom-create-vue",display:"Customize with create-vue \u2197",color:je,customCommand:"npm create vue@latest TARGET_DIR"},{name:"custom-nuxt",display:"Nuxt \u2197",color:Ur,customCommand:"npm exec nuxi init TARGET_DIR"}]},{name:"react",display:"React",color:zr,variants:[{name:"react-ts",display:"TypeScript",color:k},{name:"react-swc-ts",display:"TypeScript + SWC",color:k},{name:"react",display:"JavaScript",color:j},{name:"react-swc",display:"JavaScript + SWC",color:j}]},{name:"preact",display:"Preact",color:Wr,variants:[{name:"preact-ts",display:"TypeScript",color:k},{name:"preact",display:"JavaScript",color:j}]},{name:"lit",display:"Lit",color:qr,variants:[{name:"lit-ts",display:"TypeScript",color:k},{name:"lit",display:"JavaScript",color:j}]},{name:"svelte",display:"Svelte",color:ct,variants:[{name:"svelte-ts",display:"TypeScript",color:k},{name:"svelte",display:"JavaScript",color:j},{name:"custom-svelte-kit",display:"SvelteKit \u2197",color:ct,customCommand:"npm create svelte@latest TARGET_DIR"}]},{name:"solid",display:"Solid",color:k,variants:[{name:"solid-ts",display:"TypeScript",color:k},{name:"solid",display:"JavaScript",color:j}]},{name:"qwik",display:"Qwik",color:Ft,variants:[{name:"qwik-ts",display:"TypeScript",color:Ft},{name:"qwik",display:"JavaScript",color:j},{name:"custom-qwik-city",display:"QwikCity \u2197",color:Ft,customCommand:"npm create qwik@latest basic TARGET_DIR"}]},{name:"others",display:"Others",color:B,variants:[{name:"create-vite-extra",display:"create-vite-extra \u2197",color:B,customCommand:"npm create vite-extra@latest TARGET_DIR"},{name:"create-electron-vite",display:"create-electron-vite \u2197",color:B,customCommand:"npm create electron-vite@latest TARGET_DIR"}]}],Ne=Ht.map(e=>e.variants&&e.variants.map(t=>t.name)||[e.name]).reduce((e,t)=>e.concat(t),[]),Kr={_gitignore:".gitignore"},Yt="vite-project";async function Zr(){const e=Fe(Lt._[0]),t=Lt.template||Lt.t;let s=e||Yt;const i=()=>s==="."?O.basename(O.resolve()):s;let n;try{n=await Jr([{type:e?null:"text",name:"projectName",message:B("Project name:"),initial:Yt,onState:u=>{s=Fe(u.value)||Yt}},{type:()=>!E.existsSync(s)||tn(s)?null:"confirm",name:"overwrite",message:()=>(s==="."?"Current directory":`Target directory "${s}"`)+" is not empty. Remove existing files and continue?"},{type:(u,{overwrite:y})=>{if(y===!1)throw new Error(ct("\u2716")+" Operation cancelled");return null},name:"overwriteChecker"},{type:()=>ke(i())?null:"text",name:"packageName",message:B("Package name:"),initial:()=>Xr(i()),validate:u=>ke(u)||"Invalid package.json name"},{type:t&&Ne.includes(t)?null:"select",name:"framework",message:typeof t=="string"&&!Ne.includes(t)?B(`"${t}" isn't a valid template. Please choose from below: `):B("Select a framework:"),initial:0,choices:Ht.map(u=>{const y=u.color;return{title:y(u.display||u.name),value:u}})},{type:u=>u&&u.variants?"select":null,name:"variant",message:B("Select a variant:"),choices:u=>u.variants.map(y=>{const m=y.color;return{title:m(y.display||y.name),value:y.name}})}],{onCancel:()=>{throw new Error(ct("\u2716")+" Operation cancelled")}})}catch(u){console.log(u.message);return}const{framework:o,overwrite:r,packageName:l,variant:d}=n,a=O.join(kt,s);r?en(a):E.existsSync(a)||E.mkdirSync(a,{recursive:!0});let b=d||o?.name||t,p=!1;b.includes("-swc")&&(p=!0,b=b.replace("-swc",""));const h=sn(process.env.npm_config_user_agent),c=h?h.name:"npm",g=c==="yarn"&&h?.version.startsWith("1."),{customCommand:x}=Ht.flatMap(u=>u.variants).find(u=>u.name===b)??{};if(x){const u=x.replace(/^npm create /,()=>c==="bun"?"bun x create-":`${c} create `).replace("@latest",()=>g?"":"@latest").replace(/^npm exec/,()=>c==="pnpm"?"pnpm dlx":c==="yarn"&&!g?"yarn dlx":c==="bun"?"bun x":"npm exec"),[y,...m]=u.split(" "),G=m.map(M=>M.replace("TARGET_DIR",s)),{status:C}=Os.sync(y,G,{stdio:"inherit"});process.exit(C??0)}console.log(`

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
error: "create-vite" exited with code 1 (SIGHUP)
anon@DESKTOP-58HK8GP:~$ bun create vite myapp
file:///tmp/create-vite@latest--bunx/node_modules/create-vite/dist/index.mjs:48
`),this.close()}_(t,s){return t.toLowerCase()==="y"?(this.value=!0,this.submit()):t.toLowerCase()==="n"?(this.value=!1,this.submit()):this.bell()}render(){this.closed||(this.firstRender?this.out.write(Ie.hide):this.out.write(jr(this.outputText,this.out.columns)),super.render(),this.outputText=[_e.symbol(this.done,this.aborted),De.bold(this.msg),_e.delimiter(this.done),this.done?this.value?this.yesMsg:this.noMsg:De.gray(this.initialValue?this.yesOption:this.noOption)].join(" "),this.out.write(Nr.line+Ie.to(0)+this.outputText))}}var Lr=Fr,kr={TextPrompt:ci,SelectPrompt:gi,TogglePrompt:$i,DatePrompt:hr,NumberPrompt:gr,MultiselectPrompt:Ee,AutocompletePrompt:Mr,AutocompleteMultiselectPrompt:Rr,ConfirmPrompt:Lr};(function(e){const t=e,s=kr,i=r=>r;function n(r,l,d={}){return new Promise((a,b)=>{const p=new s[r](l),h=d.onAbort||i,c=d.onSubmit||i,g=d.onExit||i;p.on("state",l.onState||i),p.on("submit",x=>a(c(x))),p.on("exit",x=>a(g(x))),p.on("abort",x=>b(h(x)))})}t.text=r=>n("TextPrompt",r),t.password=r=>(r.style="password",t.text(r)),t.invisible=r=>(r.style="invisible",t.text(r)),t.number=r=>n("NumberPrompt",r),t.date=r=>n("DatePrompt",r),t.confirm=r=>n("ConfirmPrompt",r),t.list=r=>{const l=r.separator||",";return n("TextPrompt",r,{onSubmit:d=>d.split(l).map(a=>a.trim())})},t.toggle=r=>n("TogglePrompt",r),t.select=r=>n("SelectPrompt",r),t.multiselect=r=>{r.choices=[].concat(r.choices||[]);const l=d=>d.filter(a=>a.selected).map(a=>a.value);return n("MultiselectPrompt",r,{onAbort:l,onSubmit:l})},t.autocompleteMultiselect=r=>{r.choices=[].concat(r.choices||[]);const l=d=>d.filter(a=>a.selected).map(a=>a.value);return n("AutocompleteMultiselectPrompt",r,{onAbort:l,onSubmit:l})};const o=(r,l)=>Promise.resolve(l.filter(d=>d.title.slice(0,r.length).toLowerCase()===r.toLowerCase()));t.autocomplete=r=>(r.suggest=r.suggest||o,r.choices=[].concat(r.choices||[]),n("AutocompletePrompt",r))})(oe);const Nt=oe,Hr=["suggest","format","onState","validate","onRender","type"],Re=()=>{};async function V(e=[],{onSubmit:t=Re,onCancel:s=Re}={}){const i={},n=V._override||{};e=[].concat(e);let o,r,l,d,a,b;const p=async(h,c,g=!1)=>{if(!(!g&&h.validate&&h.validate(c)!==!0))return h.format?await h.format(c,i):c};for(r of e)if({name:d,type:a}=r,typeof a=="function"&&(a=await a(o,{...i},r),r.type=a),!!a){for(let h in r){if(Hr.includes(h))continue;let c=r[h];r[h]=typeof c=="function"?await c(o,{...i},b):c}if(b=r,typeof r.message!="string")throw new Error("prompt message is required");if({name:d,type:a}=r,Nt[a]===void 0)throw new Error(`prompt type (${a}) is not defined`);if(n[r.name]!==void 0&&(o=await p(r,n[r.name]),o!==void 0)){i[d]=o;continue}try{o=V._injected?Yr(V._injected,r.initial):await Nt[a](r),i[d]=o=await p(r,o,!0),l=await t(r,o,i)}catch{l=!await s(r,i)}if(l)return i}return i}function Yr(e,t){const s=e.shift();if(s instanceof Error)throw s;return s===void 0?t:s}function Vr(e){V._injected=(V._injected||[]).concat(e)}function Br(e){V._override=Object.assign({},e)}var Gr=Object.assign(V,{prompt:V,prompts:Nt,inject:Vr,override:Br});const Jr=ft(Gr);let W=!0;const X=typeof self<"u"?self:typeof window<"u"?window:typeof global<"u"?global:{};let it=0;if(X.process&&X.process.env&&X.process.stdout){const{FORCE_COLOR:e,NODE_DISABLE_COLORS:t,NO_COLOR:s,TERM:i,COLORTERM:n}=X.process.env;t||s||e==="0"?W=!1:e==="1"||e==="2"||e==="3"?W=!0:i==="dumb"?W=!1:"CI"in X.process.env&&["TRAVIS","CIRCLECI","APPVEYOR","GITLAB_CI","GITHUB_ACTIONS","BUILDKITE","DRONE"].some(o=>o in X.process.env)?W=!0:W=process.stdout.isTTY,W&&(process.platform==="win32"||n&&(n==="truecolor"||n==="24bit")?it=3:i&&(i.endsWith("-256color")||i.endsWith("256"))?it=2:it=1)}let Ae={enabled:W,supportLevel:it};function A(e,t,s=1){const i=`\x1B[${e}m`,n=`\x1B[${t}m`,o=new RegExp(`\\x1b\\[${t}m`,"g");return r=>Ae.enabled&&Ae.supportLevel>=s?i+(""+r).replace(o,i)+n:""+r}const B=A(0,0),ct=A(31,39),je=A(32,39),j=A(33,39),k=A(34,39),Wr=A(35,39),zr=A(36,39),qr=A(91,39),Ur=A(92,39),Ft=A(94,39),Lt=Ms(process.argv.slice(2),{string:["_"]}),kt=process.cwd(),Ht=[{name:"vanilla",display:"Vanilla",color:j,variants:[{name:"vanilla-ts",display:"TypeScript",color:k},{name:"vanilla",display:"JavaScript",color:j}]},{name:"vue",display:"Vue",color:je,variants:[{name:"vue-ts",display:"TypeScript",color:k},{name:"vue",display:"JavaScript",color:j},{name:"custom-create-vue",display:"Customize with create-vue \u2197",color:je,customCommand:"npm create vue@latest TARGET_DIR"},{name:"custom-nuxt",display:"Nuxt \u2197",color:Ur,customCommand:"npm exec nuxi init TARGET_DIR"}]},{name:"react",display:"React",color:zr,variants:[{name:"react-ts",display:"TypeScript",color:k},{name:"react-swc-ts",display:"TypeScript + SWC",color:k},{name:"react",display:"JavaScript",color:j},{name:"react-swc",display:"JavaScript + SWC",color:j}]},{name:"preact",display:"Preact",color:Wr,variants:[{name:"preact-ts",display:"TypeScript",color:k},{name:"preact",display:"JavaScript",color:j}]},{name:"lit",display:"Lit",color:qr,variants:[{name:"lit-ts",display:"TypeScript",color:k},{name:"lit",display:"JavaScript",color:j}]},{name:"svelte",display:"Svelte",color:ct,variants:[{name:"svelte-ts",display:"TypeScript",color:k},{name:"svelte",display:"JavaScript",color:j},{name:"custom-svelte-kit",display:"SvelteKit \u2197",color:ct,customCommand:"npm create svelte@latest TARGET_DIR"}]},{name:"solid",display:"Solid",color:k,variants:[{name:"solid-ts",display:"TypeScript",color:k},{name:"solid",display:"JavaScript",color:j}]},{name:"qwik",display:"Qwik",color:Ft,variants:[{name:"qwik-ts",display:"TypeScript",color:Ft},{name:"qwik",display:"JavaScript",color:j},{name:"custom-qwik-city",display:"QwikCity \u2197",color:Ft,customCommand:"npm create qwik@latest basic TARGET_DIR"}]},{name:"others",display:"Others",color:B,variants:[{name:"create-vite-extra",display:"create-vite-extra \u2197",color:B,customCommand:"npm create vite-extra@latest TARGET_DIR"},{name:"create-electron-vite",display:"create-electron-vite \u2197",color:B,customCommand:"npm create electron-vite@latest TARGET_DIR"}]}],Ne=Ht.map(e=>e.variants&&e.variants.map(t=>t.name)||[e.name]).reduce((e,t)=>e.concat(t),[]),Kr={_gitignore:".gitignore"},Yt="vite-project";async function Zr(){const e=Fe(Lt._[0]),t=Lt.template||Lt.t;let s=e||Yt;const i=()=>s==="."?O.basename(O.resolve()):s;let n;try{n=await Jr([{type:e?null:"text",name:"projectName",message:B("Project name:"),initial:Yt,onState:u=>{s=Fe(u.value)||Yt}},{type:()=>!E.existsSync(s)||tn(s)?null:"confirm",name:"overwrite",message:()=>(s==="."?"Current directory":`Target directory "${s}"`)+" is not empty. Remove existing files and continue?"},{type:(u,{overwrite:y})=>{if(y===!1)throw new Error(ct("\u2716")+" Operation cancelled");return null},name:"overwriteChecker"},{type:()=>ke(i())?null:"text",name:"packageName",message:B("Package name:"),initial:()=>Xr(i()),validate:u=>ke(u)||"Invalid package.json name"},{type:t&&Ne.includes(t)?null:"select",name:"framework",message:typeof t=="string"&&!Ne.includes(t)?B(`"${t}" isn't a valid template. Please choose from below: `):B("Select a framework:"),initial:0,choices:Ht.map(u=>{const y=u.color;return{title:y(u.display||u.name),value:u}})},{type:u=>u&&u.variants?"select":null,name:"variant",message:B("Select a variant:"),choices:u=>u.variants.map(y=>{const m=y.color;return{title:m(y.display||y.name),value:y.name}})}],{onCancel:()=>{throw new Error(ct("\u2716")+" Operation cancelled")}})}catch(u){console.log(u.message);return}const{framework:o,overwrite:r,packageName:l,variant:d}=n,a=O.join(kt,s);r?en(a):E.existsSync(a)||E.mkdirSync(a,{recursive:!0});let b=d||o?.name||t,p=!1;b.includes("-swc")&&(p=!0,b=b.replace("-swc",""));const h=sn(process.env.npm_config_user_agent),c=h?h.name:"npm",g=c==="yarn"&&h?.version.startsWith("1."),{customCommand:x}=Ht.flatMap(u=>u.variants).find(u=>u.name===b)??{};if(x){const u=x.replace(/^npm create /,()=>c==="bun"?"bun x create-":`${c} create `).replace("@latest",()=>g?"":"@latest").replace(/^npm exec/,()=>c==="pnpm"?"pnpm dlx":c==="yarn"&&!g?"yarn dlx":c==="bun"?"bun x":"npm exec"),[y,...m]=u.split(" "),G=m.map(M=>M.replace("TARGET_DIR",s)),{status:C}=Os.sync(y,G,{stdio:"inherit"});process.exit(C??0)}console.log(`

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
error: "create-vite" exited with code 1 (SIGHUP)

**Comment by koteelok** [comment]
+1

**Comment by brunogarciavaz** [comment]
Also happening on Ubuntu 22.04

**Comment by ghost** [comment]
Recently, I encountered an issue on Ubuntu that was related to bunsh. The problem was that an old version of nodejs (v12) was installed. To fix this, I needed to completely remove nodejs:


```bash
sudo rm -rf $(which node) $(which npm) /usr/local/bin/node /usr/local/lib/node* /usr/local/include/node* ~/.npm ~/.node-gyp
```

I then reinstalled nodejs:

```bash 
sudo apt install nodejs
sudo apt install npm
```

After that, when I ran `node -v`, I still got v12. Up-to-date version is v21, so I tried using bun but got the same error.
To update nodejs, I ran:

```bash
sudo n lts
sudo n latest
```

I checked the version again and now had v21.5. I tried using bunsh again and it worked.

I think this issue is related to Ubuntu automatically installing an old version of nodejs, resulting in incompatibility.

This briefly describes how I fixed the error that is described in this issue. Personally, this solution worked for me, but I don't know if it will work for others. Feel free to give it a try.

**Comment by baktify** [comment]
It is about your node version. 

If you use "nvm", make sure to use one of the last node versions.

You may run
```
nvm list
nvm use <node-version-from-previous-command>
bun create vite@latest 
```

**Comment by Jarred-Sumner** [comment]
Please use `--bun` or update to a later version of Node if you do want to use Node.js for this

```
bun create --bun vite myapp
```
