### ISSUE TITLE
bun create next-app is not working

### ISSUE THREAD

**Issue by tmnyoni** [oven-sh/bun#5352]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

{"os":"win32","arch":"x64"} WSL2

### What steps can reproduce the bug?

It is failing to create a nextjs project, it gets stuck on the would you like to use eslint.

**Comment by alfawal** [comment]
Couldn't reproduce that with the same version.

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983
