### ISSUE TITLE
Build Next.js in docker: `bun --bun run build; error: script "build" exited with code 11 (SIGSEGV)`

### ISSUE THREAD

**Issue by vojtechmares** [oven-sh/bun#5354]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Macbook: `Darwin 22.6.0 arm64 arm`, Docker: `Linux 6.4.15-200.fc38.aarch64 x86_64 unknown`

### What steps can reproduce the bug?

Try building an Next.js app with Bun in docker with the `Dockerfile` bellow, there is also a small repository with code to replicate the bug https://github.com/vojtechmares/bun-in-docker-nextjs-bug

I am using Macbook Pro M1 Pro, building a linux docker image with target platform `linux/amd64` (`--platform=linux/amd64` flag)

```Dockerfile
FROM --platform=linux/amd64 oven/bun:1.0.1

WORKDIR /app
EXPOSE 3000
ENV PORT 3000

ARG NEXT_TELEMETRY_DISABLED=1
ARG SKIP_ENV_VALIDATION=1
ENV NODE_ENV=production

RUN apt-get update && \
  apt-get install -y ca-certificates openssl=1.1.1n-0+deb11u5 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY . .

RUN bun install --frozen-lockfile
RUN bun --bun run build

CMD ["bun", "run", "/app/.next/standalone/server.js"]

```

### What is the expected behavior?

Successfully build a Next.js app and the docker image.

### What do you see instead?

```txt
STEP 11/12: RUN bun --bun run build
$ next build
error: script "build" exited with code 11 (SIGSEGV)
Error: building at STEP "RUN bun --bun run build": while running runtime: exit status 1
```

cc @CristhianF7

**Comment by ebalo55** [comment]
Try substituting `RUN bun --bun run build` to `RUN bunx next build`, you'll see that there's a type error here `./src/server/db.ts:1:10` which is:
```
Type error: Module '"@prisma/client"' has no exported member 'PrismaClient'.

> 1 | import { PrismaClient } from "@prisma/client";
    |          ^
  2 | 
  3 | import { env } from "~/env.mjs";
```

That may be the root cause of the SIGSEV you are experiencing, possibly there is some underground incompatibility with the bun engine but compiling using node and running with bun should fix your issue

**Comment by vojtechmares** [comment]
@ebalo55 to fix the type error, run `bunx prisma generate` to generate the client. There bay be an issue with the *postinstall* hook in `package.json`.

When I switched to `bunx next build`, I still get SIGSEGV with the same error message as mentioned in the top of the file.

My goal was to replace Node with Bun for the entire ecosystem of the application. From local development, builds and server-side runtime. I can make it work with multi-stage docker builds, e.g. built image would be node based and the runtime image would be bun based. Unfortunately that introduces an other problem of building the app on Alpine based image instead of Debian based (Bun). Which breaks Prisma.

**Comment by vojtechmares** [comment]
Update, because of Bun 1.0.2: issue remains

**Comment by vojtechmares** [comment]
I came back today to the issue (while I was looking for another issue of mine). And I checked if it is still broken or not.

I can happily report that the issue with Bun and Primsa was fixed and everything is working as suppose to!

Good job 👍
