### ISSUE TITLE
How to compile executable as x86 or ARM

### ISSUE THREAD

**Issue by iamnobodysir** [oven-sh/bun#5366]
### What is the issue?

I followed the tutorial in https://bun.sh/docs/bundler/executables in my Mac M2 . I able to run on other Macbook running on M1 as well but not able to work for my Ubuntu server running on x86.

Is there a way to change the architecture, thank you.

**Comment by kerambit** [comment]
Hello
Looks like there is no such option in bun, in deno, even in node.js
I suppose if bun supports cross-compilation it must be noted at the docs because it's sounds like killer feature

**Comment by gtrabanco** [comment]
I have read in any place that is planned, whatever you can use [bkg](https://github.com/theseyan/bkg) at this moment to do that.

**Comment by gtrabanco** [comment]
#3473

Remember you can setup a Github action to do that cross compilation by using qemu.

**Comment by iamnobodysir** [comment]
> #3473
> 
> Remember you can setup a Github action to do that cross compilation by using qemu.

I see, I keep that in mind.

**Comment by svallory** [comment]
> Looks like there is no such option in bun, in deno, even in node.js

I'm not sure how it was back then, but today Deno can [cross-compile binaries](https://docs.deno.com/runtime/manual/tools/compiler#cross-compilation) 

> You can compile binaries for other platforms by adding the --target CLI flag. Deno currently supports compiling to Windows x64, macOS x64, macOS ARM and Linux x64.

**Comment by alexandrubau** [comment]
@gtrabanco I'm new to using qemu, would you mind pointing me into the right direction in regards to cross-compilation for Bun? I would very much appreciate it. Thanks!

**Comment by iamnobodysir** [comment]
https://docs.deno.com/runtime/manual/tools/compiler#cross-compilation

**Comment by alexandrubau** [comment]
@iamnobodysir I was interested in cross-compilation using Bun, not Deno. It could have been a good idea to keep the issue open.

**Comment by iamnobodysir** [comment]
> @iamnobodysir I was interested in cross-compilation using Bun, not Deno. It could have been a good idea to keep the issue open.

I see sorry I closed it, basically what's @gtrabanco referring mean you either create a "Emulator" in your PC to build your bun or create a pipeline CI/CD to build it such as Jenkins.

**Comment by iamnobodysir** [comment]
> > @iamnobodysir I was interested in cross-compilation using Bun, not Deno. It could have been a good idea to keep the issue open.
> 
> I see sorry I closed it, basically what's @gtrabanco referring mean you either create a "Emulator" in your PC to build your bun or create a pipeline CI/CD to build it such as Jenkins.

@alexandrubau also note that it will be extreme slow due since is running emulator instead of virtualization, I won't recommend it unless you don't have any other way.

**Comment by gtrabanco** [comment]
> @gtrabanco I'm new to using qemu, would you mind pointing me into the right direction in regards to cross-compilation for Bun? I would very much appreciate it. Thanks!

I have no experience doing that.

**Comment by infrahead** [comment]
Coming in the next version: https://github.com/oven-sh/bun/pull/10477

**Comment by Jarred-Sumner** [comment]
[Bun supports cross-compilation](https://bun.sh/docs/bundler/executables) as of a few weeks ago. Note that we do not support 32 bit x86 or ARM, but we do support x64 and ARM64.
