### ISSUE TITLE
Bun install doesn't work with a registry url that don't end with `/`

### ISSUE THREAD

**Issue by atombarel** [oven-sh/bun#5368]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.15.90.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

- create a bunfig.toml with a registry URL without a slash as last character
- run command bun install

### What is the expected behavior?

- all packages get installed 

### What do you see instead?

- all packages result in a 404 error

### Additional information

Maybe related to a past bug #2462

**Comment by Hanaasagi** [comment]
Related to https://github.com/oven-sh/bun/issues/4589

**Comment by Jarred-Sumner** [comment]
Fixed by @Hanaasagi
