### ISSUE TITLE
Using `workspace:*` instead of just `*` in workspaces

### ISSUE THREAD

**Issue by VaronLaStrauss** [oven-sh/bun#5375]
### What is the type of issue?

Documentation is incorrect, Example code is not working

### What is the issue?

As found in [this](https://bun.sh/guides/install/workspaces) link, when in a monorepo, we must use a `"*"` to represent other packages in the same workspace. However, there were errors when I tried replicating the documentation.

Upon further research, I found [this](https://github.com/oven-sh/bun/issues/4676#issuecomment-1712482591) open issue where we have to use `"workspace:*"` instead.

Bun version: 1.0

### Where did you find it?

https://bun.sh/guides/install/workspaces
https://bun.sh/guides/install/workspaces

**Comment by dylang** [comment]
I created a PR to update the docs: https://github.com/oven-sh/bun/pull/5379
