### ISSUE TITLE
Add "bun create vue"

### ISSUE THREAD

**Issue by eladcandroid** [oven-sh/bun#538]
### What is the problem this feature will solve?

Create a vue project using https://github.com/vuejs/create-vue

### What is the feature you are proposing to solve the problem?

Add "bun create vue" command

**Comment by rowlo** [comment]
Currently, running `bun create vue@latest` results in the following console error output:
```
/tmp/create-vue@latest--bunx/node_modules/create-vue/outfile.cjs:4664
  const isFeatureFlagsUsed = typeof (argv.default ?? argv.ts ?? argv.jsx ?? argv.router ?? argv.pinia ?? argv.tests ?? argv.vitest ?? argv.cypress ?? argv.nightwatch ?? argv.playwright ?? argv.eslint) === "boolean";
                                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error: "create-vue" exited with code 1 (SIGHUP)
```

**Comment by Woovie** [comment]
As a good alternative solution, you can `bun create vite` and choose Vue when going through the installation process.

**Comment by edwin-cox** [comment]
> As a good alternative solution, you can `bun create vite` and choose Vue when going through the installation process.

I tried `bun create vite`, then chose Vue and TS, but the newly created project won't start. `bun run dev` says that vite is not found. And `bun src/main.ts`gives unresolved variable errors.

**Comment by Woovie** [comment]
```
~/projects
% which bun
/home/jbanasik/.bun/bin/bun

~/projects
% bun --version
1.0.0

~/projects
% bun create vite
✔ Project name: … test-project
✔ Select a framework: › Vue
✔ Select a variant: › TypeScript

Scaffolding project in /home/jbanasik/projects/test-project...

Done. Now run:

  cd test-project
  bun install
  bun run dev

~/projects took 7s
% cd test-project

~/projects/test-project
% bun install
bun install v1.0.0 (822a00c4)
 + @vitejs/plugin-vue@4.3.4
 + typescript@5.2.2
 + vite@4.4.9
 + vue-tsc@1.8.10
 + vue@3.3.4

 42 packages installed [1155.00ms]

~/projects/test-project
% bun run dev
$ vite

  VITE v4.4.9  ready in 249 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
error: script "dev" exited with code 1 (SIGHUP)

~/projects/test-project took 2s
1 % vite
zsh: command not found: vite

~/projects/test-project
127 % npm
zsh: command not found: npm

~/projects/test-project
127 % node
zsh: command not found: node
```

As you can see, it works in WSL perfectly. Any specifics you can provide about your environment perhaps to make this easier to diagnose?

Edit: I recognize this is off-topic, so I'll stop here.

**Comment by edwin-cox** [comment]
> % **bun install**
> bun install v1.0.0 (822a00c4)
>  + @vitejs/plugin-vue@4.3.4
>  + typescript@5.2.2
>  + vite@4.4.9
>  + vue-tsc@1.8.10
>  + vue@3.3.4
> 
>  42 packages installed [1155.00ms]

Suddenly I feel dumb. I forgot the install step. 
Welp. Thanks for spending time finding my mistake.

**Comment by KoltPenny** [comment]
Can this issue be considered closed?

**Comment by birkskyum** [comment]
Not yet. This should work, since it's the command from the vue quick-start guide - https://vuejs.org/guide/quick-start.html#creating-a-vue-application

```sh
➜ bun --bun create vue@latest
[Error: ENOENT: no such file or directory, open '/Users/admin/repos/bun-kitchensink/test-bue/vue-project/create-vue@latest/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/admin/vue-project/create-vue@latest/package.json'
}
```

**Comment by birkskyum** [comment]
my bad, it works with `bun create --bun vue@latest`
