### ISSUE TITLE
Environment variable https_proxy set but empty causes error: ConnectionRefused

### ISSUE THREAD

**Issue by 27escape** [oven-sh/bun#5380]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

in a shell
export https_proxy=''
bun upgrade
bun install

any script that uses 'fetch'
causes the error 'ConnectionRefused', either as 'bun upgrade failed with error: ConnectionRefused' or 'Unable to connect. Is the computer able to access the url?' in the case of fetch

### What is the expected behavior?

bun does the right thing (like node and npm do!)

### What do you see instead?

bun upgrade
bun upgrade failed with error: ConnectionRefused

Please upgrade manually:
  curl -fsSL https://bun.sh/install | bash

### Additional information

It can be common practice for people in environments that change and have multiple proxies on different sites to set the proxy based on location and then set it as empty when at their home base, rather than 'unset'ing it

**Comment by Electroid** [comment]
Thanks for reporting, we are likely not properly checking that the environment variable has a 0 length.

**Comment by Hanaasagi** [comment]
working on this
