### ISSUE TITLE
TS cannot find module bun:sqlite

### ISSUE THREAD

**Issue by christopher-aldred** [oven-sh/bun#5382]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Attempt steps on bun API page: https://bun.sh/docs/api/sqlite

```
import { Database } from "bun:sqlite";

const db = new Database(":memory:");
const query = db.query("select 'Hello world' as message;");
query.get(); // => { message: "Hello world" }
```

### What is the expected behavior?

bun:sqlite is a native package so it should be able to find the declaration.

### What do you see instead?

ERROR in src/components/app/App.tsx:16:26
TS2307: Cannot find module 'bun:sqlite' or its corresponding type declarations.
  > 16 | import { Database } from "bun:sqlite";

**Comment by Electroid** [comment]
Do you have `bun-types` installed?

```sh
bun install -d bun-types
```

**Comment by christopher-aldred** [comment]
I have installed the types now with 'bun install -d bun-types'.
I have updated my tsconfig to the suggested on bun docs (see below)
I now get the following: `Module build failed: UnhandledSchemeError: Reading from "bun:sqlite" is not handled by plugins (Unhandled scheme)`

  "compilerOptions": {

    // add Bun type definitions
    "types": ["bun-types"],

    // enable latest features
    "lib": ["esnext", "DOM"],
    "module": "esnext",
    "target": "esnext",

    // if TS 5.x+
    "moduleResolution": "bundler",
    "noEmit": true,
    "allowImportingTsExtensions": true,
    "moduleDetection": "force",

    // if TS 4.x or earlier
    // "moduleResolution": "nodenext",
    "jsx": "react-jsx", // support JSX
    "allowJs": true, // allow importing `.js` from `.ts`
    "esModuleInterop": true, // allow default imports for CommonJS modules

    // best practices
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
 }

**Comment by christopher-aldred** [comment]
It seems only to be an issue when using 'bun create react-app' as bun init works ok. I will close this.

**Comment by ealipio** [comment]
@christopher-aldred di you tried adding the following to you `tsconfig.json` ?:

```
 "types": [
    "bun-types" // add Bun global
  ]
```

**Comment by quantuminformation** [comment]
tried all the above, get

```
An error occured while server rendering /:

	Cannot find module 'bun:sqlite' imported from '/Users/nikos/WebstormProjects/coffeeconnect/src/lib/db/index.ts'
```

![image](https://github.com/oven-sh/bun/assets/216566/de3f021f-1736-4aef-8af5-a0cf2431b97f)

```js
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "module": "ESNext",
    "moduleResolution": "node",
    "paths": {
      "~/*": ["./src/*"]
    },
    "strict": true,
    "target": "ESNext",
    "types": ["vite/client", "bun-types"]
  }
}
```

**Comment by quantuminformation** [comment]
opening new issue

**Comment by anhtuank7c** [comment]
> ```shell
> bun install -d bun-types
> ```

this one work for me. Thank you so much @Electroid

**Comment by zemse** [comment]
> @christopher-aldred di you tried adding the following to you `tsconfig.json` ?:
> 
> ```
>  "types": [
>     "bun-types" // add Bun global
>   ]
> ```

I had to add `"types": ["bun-types"],` to compilerOptions, initally added to the top level object of tsconfig and it was not giving any effect.

**Comment by mariusbutuc** [comment]
> Do you have `bun-types` installed?
> 
> ```shell
> bun install -d bun-types
> ```

Confirming that [the same](https://github.com/oven-sh/bun/issues/5382#issuecomment-1719709470) works well for 
> Cannot find module 'bun:test' or its corresponding type declarations.ts

**Comment by buzzy** [comment]
Same problem here.

<img width="961" alt="image" src="https://github.com/oven-sh/bun/assets/344597/b716eb16-eac0-42bf-9ecf-645cc45fe9fe">

<img width="555" alt="image" src="https://github.com/oven-sh/bun/assets/344597/8d82287d-92ff-496d-8721-0597a913aa66">

**Comment by hoiekim** [comment]
I had this issue and it turns out that my typescript installed globally was outdated(4.x) and recognized [these lines](https://github.com/oven-sh/bun/blob/f73bde79c7f3ba7d1a5706214f770d1b3b08d025/packages/bun-types/ffi.d.ts#L558-L563) as invalid so couldn't load the whole bun-types package.

If that's your case, consider upgrading your typescript version to 5.0.2 or higher.

**Comment by anhtuank7c** [comment]
Bun has released a new types annotation package by Jan 28, 2024.

```
bun remove bun-types
bun add @types/bun -d
```

**Comment by mariusbutuc** [comment]
> Bun has released a new types annotation package by Jan 28, 2024.
> 
> ```
> bun remove bun-types
> bun add @types/bun
> ```

Thanks for sharing @anhtuank7c! 

Noticed that `bun-types` tends to be [added as a dev dependency][1], therefore adding a `--dev` or its shorthand `-d` might be appropriate for this case:

```
bun add @types/bun -d
```

[1]: https://bun.sh/guides/install/add-dev

**Comment by cto4** [comment]
> I still haven't solved this problem. Can anyone explain it in detail?
> 
> ```
> bun:sqlite
> Module build failed: UnhandledSchemeError: Reading from "bun:sqlite" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "bun:" URIs.
> ```

or:
```yml
error: Failed to load external module bun:sqlite: TypeError: Native module not found: bun:sqlite
```

just add this to `next.config.mjs`, worked for me: 

```ts
webpack: (config) => {
  config.externals.push('bun:sqlite');
  return config;
},
```

also take a look at [this](https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages), it says that next will add `serverExternalPackages` stable config option starting from `v15.0.0` but at this time its `v14.2.7`. i also tried the experimental [`serverComponentExternalPackages`](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#serverexternalpackages) option to exclude `bun:sqlite` but it didn't work.

**Comment by alihammad99** [comment]
same issue here, the suggested solutions not worked for me
