### ISSUE TITLE
node:child_process exec returns void in err, stdout,stderr

### ISSUE THREAD

**Issue by kerambit** [oven-sh/bun#5383]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Make file test.js
Insert code below

```javascript
import {exec} from "child_process";
exec("ls", (err, stdout, stderr) => {
  console.log(`stdout: ${stdout}`);
  console.error(`stderr: ${stderr}`);
  console.log(`err: ${err}`);
});
```

Run
`$ bun test.js`

### What is the expected behavior?

Returns 

```
stdout: package.json
test.js

stderr: 
err: null
```

### What do you see instead?

Returns void

### Additional information

I have tried same cmd with spawn - it works fine 

```javascript
import {spawn} from "child_process";

const ls = spawn('ls');

ls.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

ls.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

ls.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
}); 
```

Also looks like exec cmd under the hood works fine, but returns void in stdout/stderr. For example you could use `exec('mkdir hello')` and directory creating.

**Comment by kerambit** [comment]
I've checked #5324 but looks like my cmd could't exceed max buffer size

**Comment by Hanaasagi** [comment]
bun 1.0.3 fixes the issue in https://github.com/oven-sh/bun/pull/5481. Please upgrade.

**Comment by kerambit** [comment]
Great! Works fine. 
Closing the issue as fixed
