### ISSUE TITLE
`bun build --compile` not finding builtin node modules

### ISSUE THREAD

**Issue by Braayy** [oven-sh/bun#5399]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.1.52-1-lts x86_64 unknown

### What steps can reproduce the bug?

Just create a simple ts file with something like:
```typescript
// index.ts
import path from 'path';
console.log(path);
```

Running `bun index.ts` gives the expected result, it prints the path module.

But when i compile it using `build build --compile index.ts`, the resulting binary gives this error:
```
error: FileNotFound reading "node:path"
```

**Comment by A-D-E-A** [comment]
This has been fixed in v1.0.1 I believe. There are other issues about compiling node with node built-in modules on v1.0.
