### ISSUE TITLE
tsconfig's paths doesn't work

### ISSUE THREAD

**Issue by zfben** [oven-sh/bun#540]
### Version

0.1.2

### Platform

Darwin Ben-MBP.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

1. `bun install`
2. `bun wiptest`

### How often does it reproduce? Is there a required condition?

All times

### What is the expected behavior?

Run cases.

### What do you see instead?

```
error: Could not resolve: "@faasjs/func". Maybe you need to "bun install"?
import { Func } from '@faasjs/func'
```

### Additional information

In my tsconfig.json, the paths related configs is:
```
"baseUrl": ".",
"paths": {
  "@faasjs/func": ["./packages/func/src/index.ts"],
  "@faasjs/*": ["./packages/*/src"]
}
```

**Comment by FinnRG** [comment]
@zfben Could you please provide a minimal reproducible example? Best would be some form of git repo.

**Comment by zfben** [comment]
> @zfben Could you please provide a minimal reproducible example? Best would be some form of git repo.

My repo is https://github.com/faasjs/faasjs , and I create an action for testing with wiptest, the log is https://github.com/faasjs/faasjs/runs/7274343154?check_suite_focus=true

**Comment by Jarred-Sumner** [comment]
This was implemented awhile ago

**Comment by giangm9** [comment]
Is this issue is on build feature or run feature ?

**Comment by Sebastp** [comment]
doesn't work for me either
