### ISSUE TITLE
we must have turbo repo ?

### ISSUE THREAD

**Issue by mertcanaltin** [oven-sh/bun#5404]
### What is the problem this feature would solve?

hello everyone i want to make a very simple boilerplate using lerna called turbun, with turbun users will be able to create clients with frameworks such as nextjs or sveltejs, vuejs and at the same time create services with it.

repo : https://github.com/mertcanaltin/turbun

### What is the feature you are proposing to solve the problem?

make a turbo repo

**Comment by controversial** [comment]
Not sure what the issue / feature request is here?

**Comment by Electroid** [comment]
Vercel just introduced Beta support for Bun with Turborepo: https://twitter.com/turborepo/status/1702791416672387094

**Comment by mertcanaltin** [comment]
My project stands out as distinctly different from the Turbo repository. While Turbo served as a valuable reference, my project takes a unique approach and incorporates a range of customized features and functionalities. I would greatly appreciate any assistance and guidance tailored to the specific characteristics and goals of my project, as it diverges from the standard Turbo setup. @Electroid
