### ISSUE TITLE
No debugging support in IntelliJ IDEA IDE

### ISSUE THREAD

**Issue by iosifnicolae2** [oven-sh/bun#5406]
### What is the problem this feature would solve?

We would like to be able to debug our application using IntelliJ IDEA IDE.

### What is the feature you are proposing to solve the problem?

I don't know exactly what's needed to do in order to fix this problem.

**Comment by JoshuaHintze** [comment]
There is some discussion here:

https://youtrack.jetbrains.com/issue/WEB-56768/Bun-support#focus=Comments-27-8080814.0-0

However I can not confirm if anyone has been able to debug yet.

Also just as an FYI, when intellij (phpstrom, webstorm) tries to launch bun as a replacement for node its trying to use these arguments

 --debug-brk=62358 --expose_debug_as=v8debug
 
 I'm not sure if those are supported in bun

**Comment by kravetsone** [comment]
We get it in next Webstorm update 
![tg_image_3829832978](https://github.com/oven-sh/bun/assets/57632712/a324b6aa-c661-41c2-9f19-1c634baf2542)

**Comment by RiskyMH** [comment]
as kravetsone linked, its part of webstorm now. I have also tested it and it works well!
