### ISSUE TITLE
Support on Heroku

### ISSUE THREAD

**Issue by ajaymahadeven** [oven-sh/bun#5407]
### What version of Bun is running?

1.0.0

### What steps can reproduce the bug?

```
```
2023-09-14T20:30:38.765920+00:00 heroku[web.1]: Starting process with command `bun run  app.cjs`
2023-09-14T20:30:39.374669+00:00 app[web.1]: /bin/bash: line 1: bun: command not found
2023-09-14T20:30:39.471631+00:00 heroku[web.1]: Process exited with status 127
2023-09-14T20:30:39.491868+00:00 heroku[web.1]: State changed from starting to crashed
```
```

### What is the expected behavior?

No support on Heroku

### What do you see instead?

App crashing due to command not being found.

**Comment by jakeg** [comment]
Try using https://github.com/jakeg/heroku-buildpack-bun

**Comment by controversial** [comment]
This seems like an issue for Heroku rather than an issue for Bun

**Comment by ajaymahadeven** [comment]
I have encountered an issue that I'm unsure where to appropriately address. It appears that there is currently no dedicated build pack available in Heroku's Git repositories. After some consideration, I believe that discussing this matter within the Bun repository could prove beneficial for both Bun users and the internal team. Additionally, it could serve as a starting point for advocating for an official build pack from Heroku.

**Comment by jakeg** [comment]
Try adding the one I linked above. It should work, but isn't official.

**Comment by Electroid** [comment]
This is likely from Bun not being properly installed, and it looks like there is a suggested build-pack here: https://github.com/jakeg/heroku-buildpack-bun
