### ISSUE TITLE
Make bun docs searchable and easy to navigate

### ISSUE THREAD

**Issue by kimolalekan** [oven-sh/bun#541]
### What is the problem this feature will solve?

Make bun docs searchable and easy to navigate

### What is the feature you are proposing to solve the problem?

Documentation: https://bun-docs.vercel.app/

### What alternatives have you considered?

I will write this and do a pull request.

**Comment by kimolalekan** [comment]
@FinnRG I need permission to push documentation updates. 

Link: https://bun-docs.vercel.app/

Features: 
- Navigation menu
- Sidebar navigation
- Search
- Light and Dark theme

**Comment by FinnRG** [comment]
@kimolalekan Why can't you make a PR?
