### ISSUE TITLE
Unable to run app with pino-pretty logger transport

### ISSUE THREAD

**Issue by zach-betz-hln** [oven-sh/bun#5410]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

See the minimal reproducible example here please:
https://github.com/zach-betz-hln/mre-bun-pino

### What is the expected behavior?

The pino-pretty logger works.

### What do you see instead?

```
Hello via Bun!
124 |       return join(__dirname, '..', 'file.js')
125 |     }
126 | 
127 |     let fixTarget
128 | 
129 |     for (const filePath of callers) {
                               ^
TypeError: undefined is not an object (evaluating 'callers')
      at fixTarget (/Users/zachary.betz/dev/mre-bun-pino/node_modules/pino/lib/transport.js:129:27)
      at transport (/Users/zachary.betz/dev/mre-bun-pino/node_modules/pino/lib/transport.js:114:21)
      at normalizeArgs (/Users/zachary.betz/dev/mre-bun-pino/node_modules/pino/lib/tools.js:312:15)
      at pino (/Users/zachary.betz/dev/mre-bun-pino/node_modules/pino/pino.js:87:27)
      at /Users/zachary.betz/dev/mre-bun-pino/index.ts:7:15
```

### Additional information

I'm rooting for this tool SO HARD 🙂

**Comment by tezf** [comment]
👍 same issue here. 
Bun 1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b
Darwin 22.6.0 arm64 arm

edit: seems to be already raised here https://github.com/oven-sh/bun/issues/4280

**Comment by capaj** [comment]
I hackfixed the problem in pino here:
https://github.com/capaj/pino/commit/8fb80fb207127bc84c9ce5b73dd3899ecedf293f

this hackfix does not break any of pino tests: https://github.com/pinojs/pino-pretty/issues/448#issuecomment-1722187797

you can try it out by replacing your `    "pino": "^8.15.1",` with `    "pino": "github:capaj/pino#master", ` in package.json

**Comment by zach-betz-hln** [comment]
Tried with bun revision `1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49`, can still reproduce this.

**Comment by dimonnwc3** [comment]
I can run but it crashes with segmentation fault

```
❯ bun --version
1.0.2
```

```
"pino": "^8.15.1",
"pino-pretty": "^10.2.0",
```

```
import pino from "pino"
import pretty from "pino-pretty"

const stream = pretty()

export const log = pino(stream)

setInterval(() => log.info("Hello"), 500)
```

```
❯ bun ./lib/repr.ts
[0.02ms] ".env"
[11:33:38.539] INFO (78342): Hello
[11:33:39.037] INFO (78342): Hello
[11:33:39.535] INFO (78342): Hello
[11:33:40.033] INFO (78342): Hello
[11:33:40.536] INFO (78342): Hello
[11:33:41.038] INFO (78342): Hello
[1]    78342 segmentation fault  bun ./lib/repr.ts
```

**Comment by zach-betz-hln** [comment]
@dimonnwc3 you may be experiencing a separate issue. 

I'm able to run my app fine with `pino` - the issue only happens when using `pino` + `pino-pretty`

What is your [platform](https://github.com/oven-sh/bun/blob/main/.github/ISSUE_TEMPLATE/2-bug-report.yml)?

For MacOS and Linux: copy the output of `uname -mprs`

For Windows: copy the output of `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"` in the PowerShell console

**Comment by zach-betz-hln** [comment]
Closing this issue per https://github.com/oven-sh/bun/issues/4280#issuecomment-1727666887

**Comment by yemreak** [comment]
I encountered a similar error when trying to pipe (`|`) with `pino-pretty`, which was installed using `bun install -g`. I resolved it as follows:

```ts
bun src/index.ts | bun $HOME/.bun/bin/pino-pretty
```

_This might be helpful._
