### ISSUE TITLE
bun:sqlite cant open path with Tilda "~" character

### ISSUE THREAD

**Issue by nerkn** [oven-sh/bun#5417]
### What version of Bun is running?

1.0.1

### What platform is your computer?

windows wsl ubuntu

### What steps can reproduce the bug?

this fails
`export const db = new Database("~/db.sql",  { create: true });`

whereas this runs as normal
`export const db = new Database("/home/n/db.sql",  { create: true });`

### What is the expected behavior?

run without problem

### What do you see instead?

error message
```
110 | }
111 | var cachedCount = Symbol.for("Bun.Database.cache.count");
112 |
113 | class Database {
114 |
115 |   constructor(filenameGiven, options) {

```

**Comment by Electroid** [comment]
This is because the path to the `Database` needs to be an absolute path. You could try this:

```js
import { resolve } from "path";
export const db = new Database(resolve("~/db.sql"),  { create: true });
```
