### ISSUE TITLE
SvelteKit build with static adapter and `--bun` producing a TypeError

### ISSUE THREAD

**Issue by DeedleFake** [oven-sh/bun#5418]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 6.5.3-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

1. Run `bun create svelte@latest test` and choose skeleton project and no TypeScript.
2. Run
```bash
$ cd test
$ bun add -D @sveltejs/adapter-static
```
3. Replace `svelte.config.js`'s contents with
```javascript
import adapter from '@sveltejs/adapter-static';
export default {
	kit: {
		adapter: adapter({fallback: 'index.html'})
	}
};
```
4. Run `bunx --bun vite build`.

### What is the expected behavior?

It should compile correctly.

### What do you see instead?

It _looks_ like it compiles fine, and then at the very end produces

```
error: 30 |  * - `Request`
31 |  * - `Response`
32 |  */
33 | export function installPolyfills() {
34 | 	for (const name in globals) {
35 | 		Object.defineProperty(globalThis, name, {
     ^
TypeError: Attempting to change configurable attribute of unconfigurable property.
      at installPolyfills (/tmp/tmp.wiU9RmCWzZ/test/node_modules/@sveltejs/kit/src/exports/node/polyfills.js:35:2)
      at /tmp/tmp.wiU9RmCWzZ/test/node_modules/@sveltejs/kit/src/core/postbuild/fallback.js:20:1
```

before just hanging until I hit `^C`.

### Additional information

Running `bunx vite build` _without_ the `--bun` flag works correctly. Also, trying to run `bun run build` works fine but once the `build` directory exists, `bun --bun run build` fails because it tries to run the directory instead of the script. That's a different bug, though, I suppose.

The `package.json` that I wound up with while putting together a minimal reproduction is

```json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "lint": "prettier --plugin-search-dir . --check .",
    "format": "prettier --plugin-search-dir . --write ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^1.0.0",
    "@sveltejs/adapter-static": "^2.0.3",
    "@sveltejs/kit": "^1.0.0",
    "prettier": "^2.8.0",
    "prettier-plugin-svelte": "^2.8.1",
    "svelte": "^3.54.0",
    "vite": "^4.0.0"
  },
  "type": "module"
}
```

**Comment by coffeeispower** [comment]
This issue is a duplicate of #4574
