### ISSUE TITLE
The ES modules aren't always asynchronous.

### ISSUE THREAD

**Issue by DevinJohw** [oven-sh/bun#5420]
### What is the type of issue?

Documentation is confusing

### What is the issue?

I see something in the Bun documentation like this:
"The biggest difference between CommonJS and ES Modules is that CommonJS modules are synchronous, while ES Modules are asynchronous. ". The static ES modules are synchronous, only the modules imported by`import()` function are asynchronous. This sentence is kind of confusing.

### Where did you find it?

This is the URL: https://bun.sh/docs/runtime/modules

**Comment by h2210316651** [comment]
Created a PR to update the Docs [#5456](https://github.com/oven-sh/bun/pull/5456)

**Comment by DevinJohw** [comment]
Awesome!

**Comment by MonsterDeveloper** [comment]
Seems like an issue is resolved. Should this be closed then?
