### ISSUE TITLE
FailedToOpenSocket

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#5421]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 5.10.149-android12-9-00031-g8d44cb1a9e42-ab9703858 aarch64 unknown

### What steps can reproduce the bug?

bun install

### What is the expected behavior?

bun install packages from package.json

### What do you see instead?

![Screenshot_2023-09-15-01-34-28-51_84d3000e3f4017145260f7618db1d683](https://github.com/oven-sh/bun/assets/83625587/74a83e53-8799-4cff-8418-f1b05c74e85f)

**Comment by Mirza-Glitch** [comment]
is there any progress/update on this issue? It's been a while since the last update. Actually I'm also running into same issue
