### ISSUE TITLE
Not run in Promise All 

### ISSUE THREAD

**Issue by Nam088** [oven-sh/bun#5432]
### What steps can reproduce the bug?

```javascript
const main = async () => {

    let page = 1;
    const data = fs.readFileSync(`${folderData}/data.json`, "utf8");
    const dataJson = JSON.parse(data);
    const checkUrl = dataJson[dataJson.length - 1].url;
    const crawler = new CrawlerFont();
    crawler.checkUrl = checkUrl;
    const fontAll: Font[] = [];
    while (true) {
        crawler.page = page;
        fontAll.push(...await crawler.main());
        if (crawler.check) {
            break;
        }
        page++;
    }
    fontAll.reverse();
    dataJson.push(...fontAll)
    fs.writeFileSync(`${folderData}/data.json`, JSON.stringify(dataJson));

}
(async () => {
    await main()
})();
```

### What is the expected behavior?

It stopped when the code segment hadn't finished running. I tried running it with Node.js, and it worked very well

**Comment by controversial** [comment]
This is not a complete, nor minimal, reproduction; your code can’t be run without `CrawlerFont`

**Comment by Nam088** [comment]
If I run it with Nodejs it will be perfect. But when running with Bun, it only runs a few tasks and then stops suddenly, Class Crawler is private sorry i can't public it

**Comment by controversial** [comment]
It’s not a useful bug report if you don’t provide enough code for other people to reproduce the bug you’re facing.

If you can’t release your code, you should create another minimal example that exhibits the same problem.

**Comment by Electroid** [comment]
This is likely a duplicate of #6047 or #4662.
