### ISSUE TITLE
Bun install not run on external ssd

### ISSUE THREAD

**Issue by padunk** [oven-sh/bun#5436]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

- create new directory in external ssd
- run `bun init` and then `bun add <package-name>`
- or run `bun create elysia test-elysia`

### What is the expected behavior?

bun install run successfully like npm or yarn

### What do you see instead?

![Screenshot 2023-09-15 at 11 03 02](https://github.com/oven-sh/bun/assets/25411350/6baf8e14-856c-4cec-a3aa-550bb0c5336d)

### Additional information

the SSD is not encrypted

**Comment by divmgl** [comment]
I'm unsure if this is related to Bun...

**Comment by oluijks** [comment]
@padunk I had the same thing, adding this flag solved it `bun install --backend=copyfile`

**Comment by sonigeez** [comment]
it needs to fix, this issue is getting tracked here #362

**Comment by Electroid** [comment]
This should have been fixed in https://github.com/oven-sh/bun/pull/5610, if you are still experiencing issues after upgrading, let us know and we'll re-open to investigate.
