### ISSUE TITLE
fs.watch removing first letter of filename on linux

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5442]
consider following code:
 ```javascript
import { watch } from 'fs/promises';
for await (const { filename } of watch(Bun.cwd, { recursive: true })) {
  console.log('changed', filename);
};
```
or 
```javascript
import { watch } from 'fs';
watch(Bun.cwd, { recursive: true }, (event, filename) => {
  console.log('changed', filename);
});
```
Now once i change something in the directory i expect it to print "changed {nameOfFile}".
Instead it prints "changed {ameOfFile}" i.e. there is no first character of file name in filename variable.
If i change "index.html" file it prints "changed ndex.html"

```shell
bun -v
1.0.1

cat /etc/lsb-release                                                                                                                                                         
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.0.1"
DISTRIB_CODENAME="Uranos"
DISTRIB_DESCRIPTION="Manjaro Linux"

uname -a
Linux m7-workstation 6.5.1-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep  2 22:58:41 UTC 2023 x86_64 GNU/Linux
```

May be there's a Bun.watch api for me to use that is more reliable?

_Originally reported on Discord: [`BUG: fs.watch strips 1 character from filename at the beginning`](https://discord.com/channels/876711213126520882/1152059954157600819/1152059954157600819)_

**Comment by cquasar** [comment]
I am having the same problem. First character of filename is missing.

bun: 1.1.8
OS: Void Linux x86_64
Kernel: 6.6.31_1
