### ISSUE TITLE
`--hot` and `--watch` does not work if the flag is placed after the file name.

### ISSUE THREAD

**Issue by a4amado** [oven-sh/bun#5443]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

create file `index.ts`  
run it placing the `--hot` flag after the file name `bun run index.ts --hot`
the server will not reload when a change occurs.
but when the `--hot` flag is placed like this `bun  --hot run index.ts` it reloads fine.

### What is the expected behavior?

the server should reload when a change occurs.

### What do you see instead?

make the `--hot` and `--watch` flag detectable wherever it placed in the command.

**Comment by Airdevelopments** [comment]
I would expect the current behavior. Arguments after the filename are passed into your provided script (like in nodejs).

`bun run --watch index.ts --test`

index.ts:
`console.log(process.argv);`

Results in something like this:

`[ "/home/damner/.bun/bin/bun", "/home/damner/code/index.ts", "--test" ]`

**Comment by coffeeispower** [comment]
I think that behavior is intended, any argument after the file name is supposed to be on  `process.argv`
