### ISSUE TITLE
URLSearchParams.size is undefined

### ISSUE THREAD

**Issue by unpragmatic** [oven-sh/bun#5446]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
const params = new URLSearchParams({
    foo: "bar"
})

console.log(params.size)
```

### What is the expected behavior?

stdout: 1

### What do you see instead?

stdout: undefined

### Additional information

Seems like a typo, URLSearchParams.length exists and performs as expected. However, this is incorrect per the url spec: see https://url.spec.whatwg.org/#dom-urlsearchparams-size

**Comment by davidmhewitt** [comment]
Fixed in 9168be4f15c265a776066602a9721e0ca11d112c?

**Comment by Electroid** [comment]
Yep, this is fixed and will be available in the next release. You can also upgrade to canary now to try it:
```
bun upgrade --canary
```

**Comment by mitranim** [comment]
I think 9168be4f15c265a776066602a9721e0ca11d112c is incomplete: `.length` should be removed, as it's not part of the standard. Its presence appears harmless, but may cause users to write non-standard-compliant code, and causes false positives in code that tries to detect if a given value is a "list".
