### ISSUE TITLE
Unable to install node-packager

### ISSUE THREAD

**Issue by spyridonas** [oven-sh/bun#5449]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 5.15.0-83-generic x86_64 x86_64

### What steps can reproduce the bug?

I guess the issue is with this specific package, unfortunately i work on a legacy code and wanted to check out bun.

Reproduction:

- bun init -y
- bun i node-packager

### What is the expected behavior?

The package should be installed

### What do you see instead?

error: No version matching ">2.1.15-0 <=2.1.15" found for specifier "requirejs-memfiles" (but package exists)

**Comment by Electroid** [comment]
Thanks for reporting this issue, this looks related to: #5389
