### ISSUE TITLE
mock function/spyOn types issue

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5453]
The test passes without any problems, but it remains red at the bottom, can anyone help me?
It doesn't even solve it with if to check first.

![image.png](https://cdn.discordapp.com/attachments/1152136729218797588/1152136729436893255/image.png)

_Originally reported on Discord: [`Bun test type problems`](https://discord.com/channels/876711213126520882/1152136729218797588/1152136729218797588)_

**Comment by Jarred-Sumner** [comment]
this is not enough information 

if someone is watching this issue, please leave a comment with more information for us to help
