### ISSUE TITLE
bun run: avoid bun output on process exit code > 0

### ISSUE THREAD

**Issue by homburg** [oven-sh/bun#5455]
### What is the problem this feature would solve?

If I run a process with a non-zero exit code with `bun run` I get an extra bun error message on stderr.

This is very helpful as a default, but I would like an option to disable this to only get the output of the target process.

eg.
<img width="447" alt="Screenshot 2023-09-15 at 11 08 09" src="https://github.com/oven-sh/bun/assets/235886/58151789-c905-452b-b935-93d53b7747a3">
<img width="434" alt="Screenshot 2023-09-15 at 11 08 01" src="https://github.com/oven-sh/bun/assets/235886/87d5417b-f066-49db-bf5f-82db1b5e82af">

### What is the feature you are proposing to solve the problem?

Maybe make `bun run --silent` turn off bun exit code error messages as well.

**Comment by Jarred-Sumner** [comment]
oh --silent is supposed to be silent
