### ISSUE TITLE
Strange unicode error on valid code 

### ISSUE THREAD

**Issue by sickOscar** [oven-sh/bun#5457]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

From an empy folder, I run 

```
bun init -y
```
then in an `index.ts` file I paste the basic `Bun.serve` example 

```
const server = Bun.serve({
      port: 3000,
        fetch(request) {
                return new Response("Welcome to Bun!");
        },
});

console.log(`Listening on localhost:${server.port}`);
```

and run it with `bun index.ts`

### What is the expected behavior?

The expected behaviour is a simple working script

### What do you see instead?

```
❯ bun index.ts
1 | const server = Bun.serve({
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  }
});
                  ^
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.湉整湲污挠湯楳瑳湥祣攠牲牯›慷捴敨⁲畭整⁸獩氠捯敫⁤桷湥椠⁴桳畯摬渠瑯戠⹥䤀呎㐶呟彏半䅖啌⡅半
 code: "ERR_INVALID_ARG_TYPE"

      at car/Documenti/development/buntest/index.ts:1:15
```

I assume the chinese interpretation of the text is an unicode parsing error, but I'm quite sure my shell (bash + tmux) supports unicode characters correctly

**Comment by sirenkovladd** [comment]
I think it may be related to https://github.com/oven-sh/bun/issues/3312#issuecomment-1704486463

**Comment by sickOscar** [comment]
Thank you, I didn't realize it could be something related to the CPU.
I'm actually running this on a VM on Virtual Box, now that I know I'll try tweaking something there and report back the results

**Comment by sickOscar** [comment]
I didn't know about the existence of a baseline version.

Installing and using it via npm ([link for reference](https://www.npmjs.com/package/@oven/bun-linux-x64-baseline) actually works!

I also tried to play with the configurations of the virtual box CPU options but none of the changes I made seems to work.

I suppose that what @Jarred-Sumner said about this problem is true in this case: `/proc/cpuinfo` reports the system supports avx2, but it somehow doesn't. I suppose it's due to virtual box (Version 6.1.36 r152435 (Qt5.6.2) in my case)

```
❯ cat /proc/cpuinfo | grep avx2
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
```

**Comment by Electroid** [comment]
Sorry you're running into this, we'll track the work in #3312

**Comment by jameshibbard** [comment]
> Installing and using it via npm (link for reference actually works!

This worked for me. Thank you.
