### ISSUE TITLE
ClickHouse DB not connecting

### ISSUE THREAD

**Issue by stalingino** [oven-sh/bun#5470]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
import { createClient } from "@clickhouse/client";

console.log('connecting ClickHouse DB ...')
const CHDB = createClient({
    host: config.database.chdb.host,
    username: config.database.chdb.user,
    password: config.database.chdb.password,
    database: config.database.chdb.database
})
console.log(await CHDB.ping())
```

### What is the expected behavior?
```
connecting ClickHouse DB ...
{ success: true }
```
### What do you see instead?
```
connecting ClickHouse DB ...
```
### Additional information

It just hangs and laptop fan starts to make high noise.

Before bun 1.0, it used to crash with only "Segmentation Fault" in console.

**Comment by pavanbadugu** [comment]
the same is observed on m1 as well when using bun

**Comment by PaganMuffin** [comment]
After changing ``@clickhouse/client`` to ``@clickhouse/client-web`` it started working for me in bun v1.0.5.

**Comment by abhi-slash-git** [comment]
No luck for me, not even showing error logs

**Comment by SoprachevAK** [comment]
For `v1.0.23` on macos reproduce. No errors, it just doesn't work

**Comment by yanislav-igonin** [comment]
Same, macOS, not working, no errors.

**Comment by calebeaires** [comment]
Hey, I have the same issue in my application. When using @clickhouse/client-web it works, but this "secondary official package" does not have support to insert using stream.

Have you guys found a solution to this matter?

**Comment by aquinary** [comment]
Well, i also ran into this problem

**Comment by royalbhati** [comment]
+1
same issue on mac m1 and bun version v1.0.30

**Comment by skoshx** [comment]
Same issue, `@clickhouse/client` just exits with no stdout, `@clickhouse/client-web` almost works, it inserts data, but then exists with this:

```typescript
1 | (function (controller) {"use strict";
                       ^
TypeError: undefined is not an object
      at readableStreamDefaultControllerCanCloseOrEnqueue (:1:20)
      at readableStreamDefaultControllerCallPullIfNeeded (:1:20)

```

(So catching doesn't work, it just crashes)
