### ISSUE TITLE
ignoreBOM property not initialized on TextDecoder

### ISSUE THREAD

**Issue by milkmuffin** [oven-sh/bun#5471]
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux d31459b29751 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux

### What steps can reproduce the bug?

```js
new TextDecoder('utf-8').ignoreBOM;
new TextDecoder('utf-8', { ignoreBOM: false}).ignoreBOM;
new TextDecoder('utf-8', { ignoreBOM: true}).ignoreBOM;
`ignoreBOM` in new TextDecoder();
```

### What is the expected behavior?

`ignoreBOM` property should be `false`

### What do you see instead?

`ignoreBOM` property does not exist (and thus evaluates as undefined), regardless of how it's initialized.

**Comment by Timelord65** [comment]
Should be related to https://github.com/oven-sh/bun/issues/5211

**Comment by ashutosh887** [comment]
@milkmuffin @WingLim 
Let me try this issue... Please assign

**Comment by Electroid** [comment]
@ashutosh887 Feel free to submit a pull request, you don't need to be assigned to work on it.

**Comment by ashutosh887** [comment]
Is this issue accepted? @Electroid

**Comment by Electroid** [comment]
Yes, but also, there is already a pending pull request in #5550. So if you would like to contribute, I'd pick another issue.
