### ISSUE TITLE
Bun audit fix --force

### ISSUE THREAD

**Issue by satyavh** [oven-sh/bun#5474]
### What is the problem this feature would solve?

> The bun CLI contains a Node.js-compatible package manager designed to be a dramatically faster replacement for npm, yarn, and pnpm

Bun indeed installs packages faster but doesn't audit them for security risks like npm and yarn. The lack of this makes Bun not a real alternative / replacement as stated on the website.

### What is the feature you are proposing to solve the problem?

Support `bun audit fix --force`

### What alternatives have you considered?

Keep using npm, yarn or pnpm

**Comment by ghiscoding** [comment]
duplicate of #5359
