### ISSUE TITLE
`bun install` not able to resolve packages pointed at branches containing a `/`

### ISSUE THREAD

**Issue by tagliala** [oven-sh/bun#5478]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. `bun init`
2. Add `"@client-side-validations/client-side-validations": "DavyJonesLocker/client_side_validations#experimental/test"` to your package.json
3. `bun install`

### What is the expected behavior?

Install the expected package at the expected branch, like yarn and npm are doing

### npm

```
npm install

added 3 packages, changed 1 package, and audited 5 packages in 33s
```

### yarn

```
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning bun-test: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @client-side-validations/client-side-validations@0.4.0" has unmet peer dependency "jquery@>= 1.12.4 < 4.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 2.12s.
```

### What do you see instead?

```
error: package "@client-side-validations/client-side-validations" with tag "DavyJonesLocker/client_side_validations#experimental/test" not found, but package exists
```

### Additional information

Hello, 

I'm new to Bun and I'm not a javascript developer.

I've tried to search, so apologies if this is a duplicate.

This issue May be related to #4686, #4666 or #3274 but the description of the issue and the discussion does not look related

I've created an `experimental-test` branch and it works, so probably it's the `/` in the tag name

**Comment by dylan-conway** [comment]
fixed in #5941
