### ISSUE TITLE
[WSL] `Bun.file` crashes when attempting to write files >= 256KB, or read any file

### ISSUE THREAD

**Issue by Seblor** [oven-sh/bun#5479]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

WSL on Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Attempt to read a file using `Bun.file().text()`, `Bun.file().json()`, or `Bun.file().arrayBuffer()`

Attempt to write a file that exceeds or is 256 KB.

Here is the code I used to produce the issue (as-is, it will crash when attempting to write the 256KB file):

```ts
let iter = 0

while (true) {
  const data = 'a'.repeat(iter * 1024)
  const fileSizeString = humanFileSize(data.length)
  const fileName = `./files/${fileSizeString}.txt`
  console.log(fileSizeString);

  await Bun.write(fileName, data)
  const file = Bun.file(fileName)

  // console.log(await file.exists()); // <== This works

  // console.log((await file.text()).length); // <== This crashes
  // console.log((await file.json())); // <== This crashes
  // console.log((await file.arrayBuffer()).byteLength); // <== This crashes
  await new Promise(resolve => setTimeout(resolve, 100))
  iter++
}

function humanFileSize(bytes: number, si=false, dp=1) {
  const thresh = si ? 1000 : 1024;

  if (Math.abs(bytes) < thresh) {
    return bytes + 'B';
  }

  const units = si 
    ? ['kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'] 
    : ['KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'];
  let u = -1;
  const r = 10**dp;

  do {
    bytes /= thresh;
    ++u;
  } while (Math.round(Math.abs(bytes) * r) / r >= thresh && u < units.length - 1);


  return bytes.toFixed(dp) + units[u];
}
```

### What is the expected behavior?

Not crashing.

### What do you see instead?

Bun stops the execution, no crash logs.

### Additional information

Running on WSL with Debian GNU/Linux 11

**Comment by p0fi** [comment]
I can confirm this behavior outside WSL. It behaves in the same way when running a simple test script in docker.

```js
const path = 'test.txt'
const file = Bun.file(path)
const content = await file.text()

console.log(content)
```

When building the image on a M1 Mac and running it on a M1 Mac it works fine.
```
docker  build -t test: .
```

If I want to build and run the image on amd64 it crashes like you described.

```
docker buildx build --platform=linux/amd64 -t test .
``` 

It seems that its a particular linux/amd64 problem 🤔

**Comment by sansjack** [comment]
i seem to be getting a similar issue with docker running the oven/bun image on my M1 mac, it seems to be crashing with:

Error in docker image:

```
error: script "prod" exited with code 1 (SIGHUP)
```
Where it is crashing
```ts
const stickersFile = Bun.file(./random/stickers.json')
```

**Comment by Seblor** [comment]
@sansjack02 that does not seem the be the same issue. In my case, the file pointer variables can be created with no issue.

By the way you are missing a quote in your code example.

**Comment by tylerjrbuell** [comment]
I can confirm  `Bun.file().text()`, `Bun.file().json()`, or `Bun.file().arrayBuffer()` crash with no output on WSL: Ubuntu 22.04.3 LTS with Bun version 1.0.2. I can get `file.type` or `file.exists() == true` but once I try to read the file it crashes. Calling `file.readable` outputs `undefined`.

**Comment by Jarred-Sumner** [comment]
This is happening because the WSL2 Linux Kernel is out of date. 

Please upgrade to the latest Linux kernel version using Windows Update.

Duplicate of https://github.com/oven-sh/bun/issues/2775

**Comment by Seblor** [comment]
Thanks for the info :)

Shortcut for the other people having the same problem, run `wsl --update` in windows's cmd to update the kernel.
