### ISSUE TITLE
Transition repos from Jarred-Sumner/ to oven-sh/

### ISSUE THREAD

**Issue by alepouna** [oven-sh/bun#548]
After trying to update all GitHub URLs from Jarred-Sumner/ to over-sh/ (PR https://github.com/oven-sh/bun/pull/547) 
I have located multiple GitHub URLS that are still under Jarred-Sumner profile and should be moved to over-sh/ for consistency. 

Repositories that need transitioning: 
- https://github.com/Jarred-Sumner/WebKit
- https://github.com/Jarred-Sumner/mimalloc
- https://github.com/Jarred-Sumner/uWebSockets
- https://github.com/Jarred-Sumner/tinycc
- https://github.com/Jarred-Sumner/zig
- https://github.com/Jarred-Sumner/WebKit
- https://github.com/Jarred-Sumner/bun-releases-for-updater
- https://github.com/Jarred-Sumner/vscode-zig
- https://github.com/Jarred-Sumner/napi-plus100

**Comment by xhyrom** [comment]
I think `bun-releases-updater` can't be transferred because the old updaters will stop working.

**Comment by alepouna** [comment]
GitHub automatically redirects you to the new repo, e.g. if you go to https://github.com/Jarred-Sumner/bun it will send you over here, so technically the old updater URL is going to be deprecated but still operational.

**Comment by xhyrom** [comment]
> GitHub automatically redirects you to the new repo, e.g. if you go to https://github.com/Jarred-Sumner/bun it will send you over here, so technically the old updater URL is going to be deprecated but still operational.

Yeh, you're right. I just wasn't sure.

**Comment by xhyrom** [comment]
It's done 👍
