### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5487]
hey so from what I've seen I believe Bun should support both the import and require syntax but for some reason it's showing me this error when trying to use require in my code:

Internal server error: Can't find variable: require

this is my code

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
export default prisma
```

_Originally reported on Discord: [`Can't find variable: require`](https://discord.com/channels/876711213126520882/1152287487104909352/1152287487104909352)_

**Comment by paperclover** [comment]
i dont think this is a bun in bug

<img width="703" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/6ebaef16-a668-4261-993a-7e827bbb0279">

**Comment by johanfol** [comment]
Hi, I'm experiencing this same issue - more context: I use `bun build --target=bun ./src/index.ts --outfile=build/index.js`, that generates the index.js - then I use `bun build/index.js`, causing the error `ReferenceError: Can't find variable: require`

When scrolling through the bun-generated index.js bundle, I can see that these requires are references from node_modules - not my code. 

Bun Version: 1.0.3
```
johanfol@johanfol-PC:~/test$ bun build/index.js
[0.03ms] ".env"
39430 |   var coreHttpsRequest = import.meta.require("https").request;
39431 |   module.exports = {
39432 |     httpRequest
39433 |   };
39434 | 
39435 |   if (require.main === module) {
         ^
ReferenceError: Can't find variable: require
```
![image](https://github.com/oven-sh/bun/assets/36838637/382af773-0874-4e72-ada8-f29f14b83db7)

**Comment by paperclover** [comment]
> Hi, I'm experiencing this same issue - more context: I use `bun build --target=bun ./src/index.ts --outfile=build/index.js`, that generates the index.js - then I use `bun build/index.js`, causing the error `ReferenceError: Can't find variable: require`
> 
> When scrolling through the bun-generated index.js bundle, I can see that these requires are references from node_modules - not my code.
> 
> Bun Version: 1.0.3
> 
> ```
> johanfol@johanfol-PC:~/test$ bun build/index.js
> [0.03ms] ".env"
> 39430 |   var coreHttpsRequest = import.meta.require("https").request;
> 39431 |   module.exports = {
> 39432 |     httpRequest
> 39433 |   };
> 39434 | 
> 39435 |   if (require.main === module) {
>          ^
> ReferenceError: Can't find variable: require
> ```
> 
> ![image](https://user-images.githubusercontent.com/36838637/270656147-382af773-0874-4e72-ada8-f29f14b83db7.png)

seems this issue is #5809

**Comment by lostpebble** [comment]
Also running into this issue- bundled code (`index.js`) is broken with this error:

```
1 | require('crypto')
    ^
ReferenceError: Can't find variable: require
      at nodeWrap (/home/paul/dev/projects/meteor/meteor_backend_v2/dist/index.js:9645:20)
      at createMethod (/home/paul/dev/projects/meteor/meteor_backend_v2/dist/index.js:9630:19)
```

But if I run the source `./src/index.ts` directly, then it runs fine.

**Comment by paperclover** [comment]
please see the issue in the previous comment. you are running into that one, not this issue.
