### ISSUE TITLE
.env doesn't get parsed if framework is set to next in ``bunfig.toml``

### ISSUE THREAD

**Issue by FinnRG** [oven-sh/bun#549]
### Version

0.1.2

### Platform

Linux fedora 5.18.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jul 2 15:56:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. ``bun create next next``
2. Add a ``.env`` file with ``TEST="Hello, World!"``
3. Add a ``test.js`` file with ``console.log(process.env.TEST)``
4. Run ``bun test.js``

### How often does it reproduce? Is there a required condition?

This reproduces consistently.

### What is the expected behavior?

Hello, World!

### What do you see instead?

undefined

### Additional information

``bun run test.js`` works as expected

**Comment by Electroid** [comment]
This issue is no longer reproducible, and we've fixed a lot of `.env` bugs since this issue was created. If you can still run into this issue after upgrading, please feel free to re-open this issue.
