### ISSUE TITLE
Fix Catalina support

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#55]
Need to set the minimum OS target in the `build.zig` file for macOS x64.

Shouldn't be any other code changes. 

Filing an issue so I remember

**Comment by ashsearle** [comment]
Unfortunately this doesn't seem to be fixed for `bun bun`:

Given `example.js`:
```js
console.log('ok');
```

```bash
bun --version # 0.0.47
bun run ./example.js # runs and prints 'ok' as expected:
bun bun ./example.js # errors
```
Error output is garbled (presumably from multiple threads):
```
dyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: ___ulock_wai: Symbol not found: ___ulock_wait2
  Referenced from: /Users/aset2
  Referenced from: /Users/asearle/.bun/bin/bun (which was buiarle/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expectedlt for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in: /usr/lib/libSystem.B.dylib


dyld: Symbol not found: ___ulockdyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users_wait2
  Referenced from: /Users/asearle/.bun/bin/bun (which was/asearle/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expe built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dycted in: /usr/lib/libSystem.B.dylib

lib
```

```bash
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1419
```

**Comment by Jarred-Sumner** [comment]
Thanks for the detailed report


I suspect the issue is that it only passes the minimum macOS version to
zig, and not to clang when linking/generating the executable.


For now, you could try this and there’s maybe a 25% chance it’ll work. If
it does work, it’ll be slower than it could be


GOMAXPROCS=1 bun bun ./example.js


I am reopening this so I remember to update the makefile to set the minimum
macOS version in the clang options and also rebuild all the JSC bindings

**Comment by ashsearle** [comment]
Adding `GOMAXPROCS=1` does help a little with `bun bun`, but moving on to `bun dev` I quickly hit the `___ulock_wait2` issue opening dev server URL in a browser.

Thanks for looking at this 👍

**Comment by Jarred-Sumner** [comment]
I'm re-opening this as it didn't fix it, but I think https://github.com/Jarred-Sumner/bun/commit/b126392a8e555c5eb7a4f806822756ffb1be62af will fix it

**Comment by Jarred-Sumner** [comment]
I have confirmed that this is fixed

**Comment by ashsearle** [comment]
Using bun 0.0.48 there appears to be an issue detecting changes on catalina.

e.g. if I create a minimal project with react, react-dom, react-refresh and

public/index.html:
```html
<div id="root"></div>
<script type="module" async src="/src/index.js"></script>
```

src/index.js:
```js
import * as React from 'react';
import ReactDOM from 'react-dom';

const App = () => (<div>the app</div>);

ReactDOM.render(<App/>, document.getElementById('root'));
```

After bundling (with `bun bun ./src/index.js`) and running dev server (with `bun dev`) I open `http://localhost:3000` in a browser then...

In both Catalina and Monterey I see this when I open `src/index.js` in an editor (launching vim creates a swapfile called `src/.index.js.swp`):
```
Dir change: src/
Dir change: src/
Dir change: src/
Dir change: src/
Dir change: src/
```

If I save changes to `src/index.js` in Moneterey I see:
```
Dir change: src/
File change: src/index.js
6ms built src/index.js
Dir change: src/
```

But in Catalina I don't see any file or rebuild changes, I just see Dir change 5x again:
```
Dir change: src/
Dir change: src/
Dir change: src/
Dir change: src/
Dir change: src/
```

**Comment by Jarred-Sumner** [comment]
I don't think this is a catalina issue, but a filesystem watcher issue.

For now, I suggest disabling swapfiles in vim. Atomic file updates are hard for watchers to recognize without relying on directory changes

Also, feel free to open a separate issue about the filesystem watcher. Easy to lose track when it's in this issue

**Comment by victornpb** [comment]
I just installed bun 1.2.5 using `curl -fsSL https://bun.sh/install | bash`
Clean bun install, no previous version

```
victor@Victors-Mac-Mini ~ % bun
dyld: Symbol not found: ___ulock_wait2
  Referenced from: /Users/victor/.bun/bin/bun (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libSystem.B.dylib

zsh: abort      bun
```

**Comment by francwalter** [comment]
> I just installed bun 1.2.5 using `curl -fsSL https://bun.sh/install | bash` Clean bun install, (no previous version)
> 
> ```
>   ...
>   Referenced from: /Users/victor/.bun/bin/bun (which was built for Mac OS X 13.0)
>   ...
> ProductVersion:	10.15.7
> ```
> 

I have the same issue with bun 1.3 and I am on macOS 10.15.7 as well (patched OS on a very old MacBook Pro from Mid 2009).
I think it is clear: ...was built for Mac OS X 13.0 and we have only 10.15.7 so that wont run.
Which bun version could still run on a 10.15 OS and how to install?
Thanks.
