### ISSUE TITLE
`bun-types` `.json()` method on `Response` returns the global JSON object instead of actual json data.

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#550]
Bun's Repsonse type for `Response.json()` is Promise<JSON>, which resolves to the global JSON object, instead of a type alias for json data.

![image](https://user-images.githubusercontent.com/24465214/178159767-81211c52-0d77-4b87-a9ae-6822bceed823.png)

if i press go to definition i can find this in my bun-types file in the `Response` class

`types.d.ts`
```ts
  /**
   * Read the data from the Response as a JSON object.
   *
   * This first decodes the data from UTF-8, then parses it as JSON.
   *
   */
  json(): Promise<JSON>;
```

**Comment by rbargholz** [comment]
@davecaruso This has been fixed now in the latest version.
