### ISSUE TITLE
Importing CommonJS files does not create live bindings for the exports, but only a snapshot of the value at the time of the import

### ISSUE THREAD

**Issue by niieani** [oven-sh/bun#5511]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

dep.ts:

```ts
module.exports.value = 1;
module.exports.incrementValue = () => {
  module.exports.value++
};
```

main.ts:

```ts
import * as dep from "./dep.js";
console.log("value =", dep.value);
dep.incrementValue();
console.log("value =", dep.value);
```

### What is the expected behavior?

Should log:

```
value = 1
value = 2
```

### What do you see instead?

Should log:

```
value = 1
value = 1
```

### Additional information

This works correctly if the file is required instead of imported, i.e.

main.ts:
```ts
const dep = require("./dep.js");
console.log("value =", dep.value);
dep.incrementValue();
console.log("value =", dep.value);
```

It also works correctly when dep.ts is ESM and main.ts is either CJS or ESM (both work as expected):

dep.ts:
```ts
export let value = 1;
export const incrementValue = () => {
  value++;
};
```

It only breaks when combining ESM and CJS. 

This is likely because of this code in `CommonJSModuleRecord.cpp` (and its 3 other versions in that area):

https://github.com/oven-sh/bun/blob/99a92465f381cddc8469cf3515588ff5a68f0745/src/bun.js/bindings/CommonJSModuleRecord.cpp#L572-L574

It seems the bindings aren't live, because when loading CommonJS as a module, they use the value, or invoke the getter, to create a `JSValue value` that is then assigned to the export. This means the binding isn't live.

Interestingly, if you import the default, you do get the entirety of module.exports, as per this:

https://github.com/oven-sh/bun/blob/99a92465f381cddc8469cf3515588ff5a68f0745/src/bun.js/bindings/CommonJSModuleRecord.cpp#L662-L665

This leads to unusual behavior, in that:

main.ts:

```ts
import depDefault from "./dep.js";
import * as dep from "./dep.js";
console.log("value =", dep.value, depDefault.value);
dep.incrementValue();
console.log("value =", dep.value, depDefault.value);
```

would output two different values for the same export, depending on how it's accessed

```
value = 1 1
value = 1 2
```

##### There's a related problem with modules created using Bun's Object loader API:

```ts
let value = 1;
return {
  exports: {
    get value() {
      return value;
    },
    incrementValue: () => value++,
  },
  loader: "object",
};
```

The export `value` isn't a live binding, and will be evaluated to `1` when the `ObjectModule` is being created, as per the code here:

https://github.com/oven-sh/bun/blob/99a92465f381cddc8469cf3515588ff5a68f0745/src/bun.js/modules/ObjectModule.cpp#L66

**Comment by Jarred-Sumner** [comment]
This behavior is a deliberate tradeoff of our ESM <> CJS compatibility, and is consistent with Node.js.

```js
❯ node main.mjs
value = 1
value = 1
```

```js
❯ bun main.mjs
value = 1
value = 1
```

I'm not sure how we could change this without breaking compatibility with Node.js, so I'm going to close this.

For [module mocks](https://bun.sh/docs/test/mocks), we have a different approach.

**Comment by Jarred-Sumner** [comment]
The underyling issue is we ESM bindings cannot be getters. They're values which must be updated one at a time.

**Comment by niieani** [comment]
@Jarred-Sumner ESM bindings can be dynamic values though:

```ts
export let value = 1;
export const incrementValue = () => {
  value++;
};
```

It's impossible to simulate an `export let` via the `loader: "object"` currently.

I can create a separate issue for that.

**EDIT: opened https://github.com/oven-sh/bun/issues/7128**

---

What about the unexpected behavior when default importing CommonJS vs when importing individual exports? I feel like this should be addressed somehow.

---

> For [module mocks](https://bun.sh/docs/test/mocks), we have a different approach.

The link you provided doesn't mention anything about module mocks.

**Comment by niieani** [comment]
Also, what about the unexpected behavior when default importing CommonJS vs when importing individual exports? I feel like this should be addressed somehow.
