### ISSUE TITLE
Next.js custom document requires setting `getInitialProps` manually

### ISSUE THREAD

**Issue by merlinaudio** [oven-sh/bun#552]
### Version

0.1.2

### What do you see instead?

A custom _document in bun-framework-next requires

- Setting `CustomDocument.getInitialProps = NextImportedDocument.getInitialProps`
- Bundling again (`bun bun --use next`)

Otherwise,

```docker
"Document.getInitialProps()" should resolve to an object with a "html" prop set with a valid html string
```

is thrown.

---

Working example:

```
import NextDocument, { Head, Html, Main, NextScript } from "next/document";

export default function Document() {
	return (
		<Html>
			<Head />
			<body className="font-sans w-full h-full">
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}

// leave out this line 
Document.getInitialProps = NextDocument.getInitialProps;
```

**Comment by Electroid** [comment]
`bun bun` was changed in Bun v1.0, it is now an alias for `bun build`, which is Bun's new bundler. Because of that, this issue is no longer applicable.
