### ISSUE TITLE
Bcypt Module not working

### ISSUE THREAD

**Issue by Tanveeshs** [oven-sh/bun#5533]
### What version of Bun is running?

1.0.2+d976b22c95383c2623b7604ffef0563e5d53ca24

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Cannot find module "/mnt/c/Users/Tanve/WebstormProjects/fairshare-backend/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" from "/mnt/c/Users/Tanve/WebstormProjects/fairshare-backend/node_modules/bcrypt/bcrypt.js"

### What is the expected behavior?

My nest.js app is not booting up with this issue

### What do you see instead?

[2.24ms] ".env"

error: Cannot find module "/mnt/c/Users/Tanve/WebstormProjects/fairshare-backend/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" from "/mnt/c/Users/Tanve/WebstormProjects/fairshare-backend/node_modules/bcrypt/bcrypt.js"

**Comment by Electroid** [comment]
Thanks for reporting, we are tracking this work here: #299
