### ISSUE TITLE
`bun update --save` does not update version in `package.json` file

### ISSUE THREAD

**Issue by 2giosangmitom** [oven-sh/bun#5538]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.5.3-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

My `package.json`
```json
{
  "scripts": {
    "format": "prettier --write ."
  },
  "devDependencies": {
    "bun-types": "^1.0.1",
    "prettier": "^3.0.3"
  }
}
```
When run `bun update --save`, the version in `package.json` is not changed.

### What is the expected behavior?

The `bun-types` must be changed to "^1.0.2"

### What do you see instead?

The output of `bun update --save`

![image](https://github.com/oven-sh/bun/assets/87252943/2f95a5d0-95b2-4212-91f7-b340bb43d7c3)

The `package.json` after run the above command

![image](https://github.com/oven-sh/bun/assets/87252943/616efa46-652c-4c6b-af2a-b01d312a132d)

**Comment by noClaps** [comment]
Related issue: https://github.com/oven-sh/bun/issues/4312

**Comment by Electroid** [comment]
Closing in favor of #4312, yes we'll need to implement this.
