### ISSUE TITLE
Segmentation fault on a particular env variable with Apple Silicon 

### ISSUE THREAD

**Issue by thomscoder** [oven-sh/bun#554]
### Version

0.1.2

### Platform

Darwin Kernel Version 21.5.0

### What steps will reproduce the bug?

- created a React App with bun create react ./react-app
- created a .env file and put WELCOME_MESSAGE=ReactAppWithBun
- {process.env.WELCOME_MESSAGE} in App.jsx

The bug (?) only presents with that particular env variable. Works well with every other variables I've tested.

### How often does it reproduce? Is there a required condition?

All the time in React App created with bun create react

### What is the expected behavior?

Correctly displaying the values of the env variables.

### What do you see instead?

Segmentation fault error

```
SegmentationFault at 1929388152


–––– bun meta ––––
Bun v0.1.2 macOS Silicon 21.5.0
DevCommand: single_page_app_routing fast_refresh bun_bun public_folder dotenv 
Elapsed: 3372ms | User: 7ms | Sys: 16ms
RSS: 9.52MB | Peak: 9.52MB | Commit: 71.34MB | Faults: 268
–––– bun meta ––––
```

### Additional information

<img width="676" alt="Schermata 2022-07-10 alle 22 45 55" src="https://user-images.githubusercontent.com/78874117/178161844-9b4e3501-b0b8-4e24-8646-971e3f988e39.png">

Just adding one letter at the end of the env variable everything turns to work normally 
<img width="642" alt="Schermata 2022-07-10 alle 23 03 50" src="https://user-images.githubusercontent.com/78874117/178162073-21b76bdb-9eed-46df-99ec-b265e13b46f2.png">

**Comment by HarishTeens** [comment]
After a rigorous process of hit and trial. This issue seems to appear only when the Key and the Value of the env is exactly of length **15**

**Comment by Jarred-Sumner** [comment]
Super interesting

**Comment by thomscoder** [comment]
> After a rigorous process of hit and trial. This issue seems to appear only when the Key and the Value of the env is exactly of length 15

I confirm.
Tried with env set = `HelloFromBun!!!` or any other 15 characters string and it crashed with segmentation fault error.

Only in scaffolded React project. Works fine in a basic:

```
WELCOME_MESSAGE=HelloFromBun!!!
```

```js
export default {
 port: 3000,
 fetch(request) {
   return new Response(process.env.WELCOME_MESSAGE); 
 }
}
```

for example

**Comment by whiny-nil** [comment]
I'm also getting segfault errors if there are blank lines in any .env files.

**Comment by Johann01** [comment]
Exactly the same issue, with .env, just containing:

`NOTION_TOKEN=[REDACTED]`

If the string content has a different length, it works, but not with that combination.

**Comment by Electroid** [comment]
Confirming this is still an issue. Here's the reproduction:

```js
// .env
WELCOME_MESSAGE=ReactAppWithBun
```
```js
// index.js
export default {
  port: 3000,
  fetch(request) {
    return new Response(process.env.WELCOME_MESSAGE); 
  }
}
```
Output:
```js
SegmentationFault at 0x753700F300000000


----- bun meta -----
Bun v0.2.2 (88ddb103) macOS Silicon 21.5.0
RunCommand: bun_bun dotenv 
Elapsed: 25ms | User: 18ms | Sys: 7ms
RSS: 20.61MB | Peak: 20.61MB | Commit: 67.11MB | Faults: 5
----- bun meta -----
```

**Comment by Electroid** [comment]
As of Bun [v0.5.0](https://github.com/oven-sh/bun/releases/tag/bun-v0.5.0), on MacOS Apple Silicon, this no longer appears to be a bug. If you can still reproduce it, let us know and we'll re-open the issue.

**Comment by Jarred-Sumner** [comment]
I'm not able to reproduce this as of v0.4.0+ (tested 0.4, 0.5, 0.5.7, and 0.5.8), but please leave a comment/reopen if still happening
