### ISSUE TITLE
Repeated: "stdin: Input/output error"

### ISSUE THREAD

**Issue by herbievine** [oven-sh/bun#5544]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

bun run ed

### What is the expected behavior?

error: missing script "ed"

### What do you see instead?

Like a read on std 0, the terminal waits for input. When CMD+C, this happens:

```
stdin: Input/output error
stdin: Input/output error
stdin: Input/output error
stdin: Input/output error
stdin: Input/output error
```

**Comment by Electroid** [comment]
Are you running Bun in any special way? What shell are you using?
