### ISSUE TITLE
node:dns.lookup allows hostname to be empty and emits a warning 

### ISSUE THREAD

**Issue by fabiancook** [oven-sh/bun#5547]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Create the file `dns-lookup.js`: 

```typescript
import { lookup } from "node:dns";

lookup(undefined, (error, address, family) => console.log({ error, address, family }));
```

or 

```typescript
import { lookup } from "node:dns";

lookup("", (error, address, family) => console.log({ error, address, family }));
```

Run:

```bash
node dns-lookup.js
bun dns-lookup.js # throws error
```

### What is the expected behavior?

```bash
$ node dns-lookup.js
(node:72967) [DEP0118] DeprecationWarning: The provided hostname "undefined" is not a valid hostname, and is supported in the dns module solely for compatibility.
(Use `node --trace-deprecation ...` to show where the warning was created)
{ error: null, address: null, family: 4 }
$ bun dns-lookup.js
(bun:zzzzz) DeprecationWarning: The provided hostname "undefined" is not a valid hostname, and is supported in the dns module solely for compatibility.
{ error: null, address: null, family: 4 }
```

### What do you see instead?

```bash
[0.75ms] ".env"
1 | var getServers = function() {
2 |   return dns.getServers();
3 | 
4 | }, lookup = function(domain, options, callback) {
                                           ^
TypeError: Expected hostname to be a string for 'lookup'.
 code: "ERR_INVALID_ARG_TYPE"

      at node:dns:4:40
      at /Users/fabiancook/src/network/logistics/dns-lookup.js:3:0
```

### Additional information

Found here: https://github.com/opennetwork/logistics/actions/runs/6183147871/job/16851628790#step:11:401

Can confirm fastify receiving requests after providing a hostname: https://github.com/opennetwork/logistics/actions/runs/6206964124/job/16851733018#step:11:749  

Node ignores empty hostnames here: https://github.com/nodejs/node/blob/71b90faac06961fa3bae9ebf8e928f79cc95bc7e/lib/dns.js#L194C3-L202 

Bun throws on undefined here: 
https://github.com/oven-sh/bun/blob/b651b16fdd959b349c09ec5d5056229dcd12c86b/src/bun.js/api/bun/dns_resolver.zig#L1873-L1876

Bun could check the value of `domain` here and call the callback with the same default values that node utilises. https://github.com/oven-sh/bun/blob/b651b16fdd959b349c09ec5d5056229dcd12c86b/src/js/node/dns.js#L9-L22

**Comment by Electroid** [comment]
Interesting, so Node.js returns both `address` and `error` as null in that case? That's surprising, as the types don't reflect that possibility. It also means you can't do `if (error)`

```ts
export function lookup(
  hostname: string,
  options: LookupOneOptions,
  callback: (err: NodeJS.ErrnoException | null, address: string, family: number) => void,
): void;
```

Either way, yes we'll need to fix this.

**Comment by fabiancook** [comment]
Correct. The real type from the implementation is more like

```typescript
interface DNSLookup {
  address: string
  family: number | boolean
}

interface DNSLookupCallbackFn {
  (err: NodeJS.ErrnoException | null, all?: DNSLookup[]): void;
  (err: NodeJS.ErrnoException | null, address?: string | null, family?: number) => void,
}

export function lookup(
  hostname: string | "" | null | undefined,
  options: LookupOneOptions,
  callback: DNSLookupCallbackFn,
): object;
```

Its surprising that node returns the `GetAddrInfoReqWrap` instance here, or an empty object, in favour or `void`

Note while looking through the node implementation, it doesn't even do a lookup at all if the address is a v4 or v6 IP
