### ISSUE TITLE
SyntaxError: The requested module '@babel/core' does not provide an export named 'default'

### ISSUE THREAD

**Issue by 5o50** [oven-sh/bun#5549]
### What version of Bun is running?

1.0.3+b651b16fdd959b349c09ec5d5056229dcd12c86b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
bun sst dev
file:///home/johnk/workspace/bee/node_modules/sst/stacks/build.js:7
import babel from "@babel/core";
       ^^^^^
SyntaxError: The requested module '@babel/core' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.17.1
error: "sst" exited with code 1 (SIGHUP)
```

**Comment by ian-pascoe** [comment]
I have also experienced this and after further digging, bun is installing the 8.0.0-alpha version of babel instead of the 7.x version specified by SST.

**Comment by Electroid** [comment]
Could you provide a code snippet or set of commands so we can reproduce this?

**Comment by claudesortwell** [comment]
@Electroid I got this error, tried to reproduce it now, couldn't. But on an older version of bun (1.0.3 and 1.0.0), I can reproduce this error. I cant reproduce this error on 1.0.7, so seems safe to close this.

**Comment by 5o50** [comment]
@Electroid Same. I could not reproduce the original issue on 1.0.7. Its working now. Thank you
