### ISSUE TITLE
`SyntaxError: Unexpected token '.'` when processing postcss

### ISSUE THREAD

**Issue by luizkowalski** [oven-sh/bun#5561]
### What version of Bun is running?

1.0.2

### What platform is your computer?

flullstaq-ruby docker image

### What steps can reproduce the bug?

hey 👋🏻 

so, I have an application using postcss with some plugins, like this:

```json
{
  "name": "sumiu",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.1.0",
    "@hotwired/turbo-rails": "^7.3.0",
    "@rails/ujs": "^7.0.4",
    "autoprefixer": "^10.4.15",
    "current.js": "^0.2.0",
    "daisyui": "^3.0.1",
    "el-transition": "^0.0.7",
    "esbuild": "^0.19.0",
    "mnemonic-words": "^1.1.0",
    "notie": "^4.3.1",
    "postcss": "^8.4.29",
    "postcss-cli": "^10.1.0",
    "postcss-csso": "^6.0.1",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^15.1.0",
    "postcss-nesting": "^12.0.1",
    "stimulus-clipboard": "^4.0.1",
    "tailwindcss": "^3.2.3",
    "tailwindcss-stimulus-components": "^4.0.4",
    "zxcvbn": "^4.4.2"
  },
  "scripts": {
    "build": "bun bun.config.js",
    "build:css": "postcss ./app/assets/stylesheets/application.postcss.css -o ./app/assets/builds/style.css",
....
```

and my CSS `application.postcss.css` file looks like this:
```postcss
@import "tailwind.css";
@import "../../../node_modules/notie/dist/notie.css";
```

it works just fine on my development machine but when I try to compile the CSS on the Docker image, I get this error:

```
 > [build 7/7] RUN SECRET_KEY_BASE=DUMMY ./bin/rails assets:precompile:
#0 2.184 bun install v1.0.2 (37edd5a6)
#0 2.188
#0 2.188 Checked 256 installs across 277 packages (no changes) [7.00ms]
#0 2.195 $ postcss ./app/assets/stylesheets/application.postcss.css -o ./app/assets/builds/style.css
#0 2.478 /rails/node_modules/yaml/dist/compose/composer.js:33
#0 2.478                 if (prelude[i + 1]?.[0] !== '#')
#0 2.478                                    ^
#0 2.478
#0 2.478 SyntaxError: Unexpected token '.'
#0 2.478     at wrapSafe (internal/modules/cjs/loader.js:915:16)
#0 2.478     at Module._compile (internal/modules/cjs/loader.js:963:27)
#0 2.478     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#0 2.478     at Module.load (internal/modules/cjs/loader.js:863:32)
#0 2.478     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
#0 2.478     at Module.require (internal/modules/cjs/loader.js:887:19)
#0 2.478     at require (internal/modules/cjs/helpers.js:74:18)
#0 2.478     at Object.<anonymous> (/rails/node_modules/yaml/dist/index.js:3:16)
#0 2.478     at Module._compile (internal/modules/cjs/loader.js:999:30)
#0 2.478     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#0 2.489 error: script "build:css" exited with code 1 (SIGHUP)
```

### What is the expected behavior?

That the `postcss` build step succeeds

**Comment by AlexBlokh** [comment]
I potentially got similar issue, but with a compiled binary

```ts
const assertPackage = (pkg: string) => {
  require(pkg);
};

const ormCoreVersions = () => {
  const { npmVersion } =
    require("drizzle-orm/version") as typeof import("drizzle-orm/version");
  return { npmVersion };
};

console.log(ormCoreVersions().npmVersion);
assertPackage("drizzle-orm");
```

the only dependency in the project is:
```json
"drizzle-orm": "^0.28.6"
```

I build and compile
```sh
bun build index.ts --compile --outfile dist/bin --external drizzle-orm
```

then when I run the binary, I got:
```sh
~ ./dist/bin                                                            
0.28.6


warn: Invalid source index value
/Users/alexblokh/.bun/install/cache/drizzle-orm@0.28.6/index.cjs:1:0 1SyntaxError: Unexpected token '*'. import call expects one or two arguments.
      at /Users/alexblokh/.bun/install/cache/drizzle-orm@0.28.6/index.cjs:3:11
```

**Comment by AlexBlokh** [comment]
Another thing I've noticed is that when I run compiled binary, Bun doesn't require packages from node_modules, it fetches them with it's package manager

I'm not sure it's expected, but it potentially makes it completely unusable in most Node CLI cases

**Comment by luizkowalski** [comment]
damn, thanks for the heads up

**Comment by paperclover** [comment]
so what is happening here is `require(pkg);` is a dynamic require, so it doesn't get bundled. the runtime import fails, which i have a fix for. however, this still makes such code into a runtime import, which in this case asserts that the user has the package installed.

> fetches them with it's package manager

this is because auto-install is triggered which honestly is really silly. i want to disable this as there are some other bugs in auto install that aren't suitable to enable it when `--compile`d. this will essentially make it a runtime error. the correct way is to ensure that the import is statically analyzable like `require("drizzle-orm")` or `import "drizzle-orm"`

**Comment by paperclover** [comment]
> I try to compile the CSS on the Docker image, I get this error:

this is a node.js stack trace. `bun run <bin>` like postcss will prefer the hashbang `#!/usr/bin/env node`. uninstall node.js in the docker image or pass `--bun` to forcefully override node.
