### ISSUE TITLE
Make install.peer equal to true by default

### ISSUE THREAD

**Issue by FreePhoenix888** [oven-sh/bun#5565]
### What is the problem this feature would solve?

[install.peer](https://bun.sh/docs/runtime/bunfig#install-peer) is false by default. I would like it to be true by default

### What is the feature you are proposing to solve the problem?

[install.peer](https://bun.sh/docs/runtime/bunfig#install-peer) is false by default. I would like it to be true by default

**Comment by tobi-or-not-tobi** [comment]
Related to #3410
