### ISSUE TITLE
install.peer setting does not work

### ISSUE THREAD

**Issue by FreePhoenix888** [oven-sh/bun#5567]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

- Clone https://github.com/deep-foundation/capacitor-motion/tree/0a53253a5ba93b88f2d5f3d6d86e88165192e226
- Create `bunfig.toml` with this content in root of the project:
```
[install]
peer = true
```
- Run `bun install` and see that react is not installed:
```
freephoenix888@FreePhoenix888:~/Programming/capacitor-motion$ bun install
bun install v1.0.2 (37edd5a6)
 + @atao60/fse-cli@0.1.9
 + @capacitor/cli@5.4.0
 + @deep-foundation/npm-automation@18.1.6
 + @types/debug@4.1.8
 + @types/fs-extra@11.0.2
 + @types/node@20.6.2
 + bun-types@1.0.2
 + execa@7.2.0
 + fs-extra@11.1.1
 + replace-in-file@7.0.1
 + typescript@5.0.4
 + @deep-foundation/capacitor-device@10.0.1
 + @deep-foundation/core@0.0.2
 + @freephoenix888/object-to-links-async-converter@0.0.10
 + debug@4.3.4

 198 packages installed [95.00ms]
```
[but react is specified in peerDependencies](https://github.com/deep-foundation/capacitor-motion/blob/0a53253a5ba93b88f2d5f3d6d86e88165192e226/package.json#L43)

**Comment by tobi-or-not-tobi** [comment]
Duplicates #3410
