### ISSUE TITLE
`bun install` crash with lockfile on Bun v1.0.3

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#5569]
On macOS arm:

```
❯ bun install bufferutil
bun add v1.0.3 (b651b16f)
fish: Job 1, 'bun install bufferutil' terminated by signal SIGSEGV (Address boundary error)
```

Attached lockfile:
[bun.lockb.zip](https://github.com/oven-sh/bun/files/12641121/bun.lockb.zip)

Problem goes away when lockfile is removed and regenerated.

**Comment by IndigoCurnick** [comment]
Similar issue here - except it hangs forever. Deleting `bun.lockb` and running `bun install` works. This issue happens to me when I pull repos which have the `bun.lockb` from GitHub, from someone else's machine.

**Comment by Jarred-Sumner** [comment]
Are you on bun v1.0.32+?

**Comment by IndigoCurnick** [comment]
I'm on bun v1.0.33, ArchLinux

**Comment by Jarred-Sumner** [comment]
If anyone runs into this issue in the future, please include the package.json and bun.lockb in the issue.

This crash was very likely fixed, but at this point it's not actionable without a way to reproduce it.
