### ISSUE TITLE
Allow running files with nonstandard or missing extensions

### ISSUE THREAD

**Issue by silversquirl** [oven-sh/bun#557]
### What is the problem this feature will solve?

Many command line tools have no extension. Bun cannot currently run these scripts as it needs an extension in order to deduce the filetype.

### What is the feature you are proposing to solve the problem?

Allow specifying the filetype explicitly, possibly defaulting to JS if none is specified.

### What alternatives have you considered?

A command line option could be used to opt-in to this behaviour.

A different command (`bun exec`?) could be used to bypass the package.json script running behaviour and the translation behaviour.

**Comment by Jarred-Sumner** [comment]
There is a `--loader` CLI flag which can be used this way

But bun does need a file extension right now. It should not.

**Comment by Jarred-Sumner** [comment]
This isn't implemented yet but it needs to be

**Comment by xhyrom** [comment]
Ah, sorry

**Comment by kidonng** [comment]
FYI, Deno just treats extension-less files as JS (and seems like there's no way to tell Deno it's a TS file).

**Comment by Jarred-Sumner** [comment]
We do this for extension-less files as of Bun v1.0
