### ISSUE TITLE
Support bun install --omit=dev

### ISSUE THREAD

**Issue by melroy89** [oven-sh/bun#5571]
### What is the problem this feature would solve?

NPM advised us to use: `npm install --omit=dev`, and bun only has `--production` / `-p` flags.

Please, also introduce the `--omit` flag with Bun.

### What is the feature you are proposing to solve the problem?

Compatibility with node/npm. For a better drop-in replacement without regression impact.

### What alternatives have you considered?

Running: `bun install --omit=dev` .. but I don't think it works, it doesn't give an error either? Looking at the options: `bun install --help` doesn't show the `--omit` flag option.

Tested with bun v1.0.2.

**Comment by aradalvand** [comment]
Why can't you just use Bun's `--production` flag? Isn't it functionally identical to Node's `--omit=dev`?

**Comment by melroy89** [comment]
Ow I can, but again all my scripts and docker files are using this omit flag now. Which people (including myself) forget to change when moving to bun.

**Comment by aradalvand** [comment]
> Ow I can, but again all my scripts and docker files are using this omit flag now. Which people (including myself) forget to change when moving to bun.

Just update them to use the `--production` flag. If you're migrating to a whole new tool (Node => Bun), this sort of thing is just part of the process.

**Comment by melroy89** [comment]
"Bun aims to be a drop-in replacement"
