### ISSUE TITLE
nextjs dev - doesn't try other port if 3000 is in use.

### ISSUE THREAD

**Issue by aduarterengifo** [oven-sh/bun#5577]
### What version of Bun is running?

1.0.2

### What platform is your computer?

windows wsl

### What steps can reproduce the bug?

assuming port 3000 is in use:
```
$ bunx create-next-app@latest
...
$ bun dev
```

```
$ next dev
- error Failed to start server
error: Failed to start server. Is port 3000 in use?
```

using pnpm 
```
$ bunx create-next-app@latest
...
$ pnpm dev 
```

```
> next dev
- warn Port 3000 is in use, trying 3001 instead.
```

**Comment by jumoog** [comment]
It's not a bug. Port 3000 is currently in use by a process.

**Comment by Electroid** [comment]
> It's not a bug. Port 3000 is currently in use by a process.

It appears the bug is a difference in behaviour. With Node.js, next appears to try another port, but in Bun it does not.

**Comment by Amman30** [comment]
****Issue #5577: nextjs dev - doesn't try other port if 3000 is in use**

Thank you for reporting this issue. It seems that the **Next.js** development server is not attempting to use an **alternate port if port 3000 is already in use.**

One possible solution is to configure Next.js to use a different port by **setting the `PORT` environment variable.**

1. Stop the current Next.js development server, if it's running.

2. Set the `PORT` environment variable before starting the server. You can do this in a few different ways:

**FOR:**
  i)**Windows Command Prompt**:set PORT=3001
 ii)**Windows PowerShell**:$env:PORT=3001
 iii)**For Mac intel chip**:export PORT=3001
 iv)**Mac with an apple silicon chip**:arch -x86_64 export PORT=3001. 

**NOTE: You need to run one of these commands relative to your OS. You can also choose your desired PORT.**

**Comment by sirenkovladd** [comment]
in canary it was fixed `bun upgrade --canary`
https://github.com/oven-sh/bun/pull/5689

**Comment by nyxb** [comment]
if i set port to -p 330 `"dev": "next dev -p 3030",` its crashed

```
error: InvalidPort

----- bun meta -----
Bun v1.0.3 (edee1e3d) macOS Silicon 22.6.0
AutoCommand: 
Elapsed: 1ms | User: 1ms | Sys: 1ms
RSS: 3.95MB | Peak: 3.95MB | Commit: 33.55MB | Faults: 23
----- bun meta -----

0   0x1040102b8 WTFGetBacktrace

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
``` 

latest canary

**Comment by nyxb** [comment]
> if i set port to -p 330 `"dev": "next dev -p 3030",` its crashed
> 
> ```
> error: InvalidPort
> 
> ----- bun meta -----
> Bun v1.0.3 (edee1e3d) macOS Silicon 22.6.0
> AutoCommand: 
> Elapsed: 1ms | User: 1ms | Sys: 1ms
> RSS: 3.95MB | Peak: 3.95MB | Commit: 33.55MB | Faults: 23
> ----- bun meta -----
> 
> 0   0x1040102b8 WTFGetBacktrace
> 
> Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
> ```
> 
> latest canary

ok nvm if i do that with --port=3030 it works but why -p 3030 doenst work?

**Comment by Electroid** [comment]
This issue was fixed in https://github.com/oven-sh/bun/pull/5689. The `InvalidPort` issue is being tracked here: #5698
