### ISSUE TITLE
Representing function pointers as 53-bit integers (on 64-bit architectures) is unsound

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#558]
The README claims the following:
https://github.com/oven-sh/bun/blob/1e9cba99720e110e6a4d8fe3014491118b123fdc/README.md?plain=1#L2711-L2721
Yet, [the very article](https://en.wikipedia.org/wiki/64-bit_computing#Limits_of_processors) that is used to defend this statement, claims that there are other ISAs which do allow over 53-bits of addressing.

Although Arm64 and x86-64 are undoubtedly the most common 64-bit CPU architectures, they aren't the only ones, so outside of these platforms it may very well be unsound.

Furthermore, x86 and Arm64 may extend the addressing range eventually.

E.g., AMD64 claims
> Virtual addresses are 32 bits long, and physical addresses up to the supported physical-address size can be used. The AMD64 architecture enhances the legacy translation support by allowing virtual addresses of up to 64 bits long to be translated into physical addresses of up to 52 bits long.
> Currently, the AMD64 architecture defines a mechanism for translating 48-bit virtual addresses to 52-bit physical addresses. The mechanism used to translate a full 64-bit virtual address is reserved and will be described in a future AMD64 architectural specification.

\- https://www.amd.com/system/files/TechDocs/24593.pdf

**Comment by Jarred-Sumner** [comment]
> Yet, [the very article](https://en.wikipedia.org/wiki/64-bit_computing#Limits_of_processors) that is used to defend this statement, claims that there are other ISAs which do allow over 53-bits of addressing.
>
> Although Arm64 and x86-64 are undoubtedly the most common 64-bit CPU architectures, they aren't the only ones, so outside of these platforms it may very well be unsound.

Yes, Bun only supports aarch64 and x64. That is likely to be the case for awhile, but not forever. When Bun adds support for other architectures, this will need to be addressed, but that doesn't mean it will be an observable change (potentially similar to how JSValue on 32 bit architectures handles doubles)

A lot of software you use everyday depends on pointer tagging to work, and this is a lot like that.

When bun adds support for targets this method does not support, we will find a way to address it then.
