### ISSUE TITLE
Implement module mocking

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#5586]
> Should `jest.mock` be added as well? Doesn't seem to be tracked.

This still seems to not be on the list. Could we get support for `jest.mock` and `jest.requireActual` compatibility APIs added as an official target on this list? Module mocking is a [pretty important part](https://jestjs.io/docs/mock-functions#mocking-modules) of `jest` compatibility.

Example:
```ts
import { foo } from 'some-module'

jest.mock('some-module', () => ({
  ...jest.requireActual<object>('some-module'),
  foo: jest.fn(() => 'foo'),
}))
```
The pattern here allows you to override just the `foo` method of `some-module`, while `requireActual` gives you the _real_ implementation for the rest.

Jest also supports placing an override for `some-module` in a `__mocks__/some-module.ts` file, as another way to automatically module-mock, though imho that is less priority.

_Originally posted by @TroyAlford in https://github.com/oven-sh/bun/issues/1825#issuecomment-1710813619_

**Comment by sirenkovladd** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5394

**Comment by Electroid** [comment]
Duplicate of #5394
