### ISSUE TITLE
Update `npm install -g bun` to support Windows

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5590]
Can anybody help me to solve this issue regarding bun installation

![image.png](https://cdn.discordapp.com/attachments/1152461575043690496/1152461575165321216/image.png)

_Originally reported on Discord: [`Installation Problem`](https://discord.com/channels/876711213126520882/1152461575043690496/1152461575043690496)_

**Comment by Boierul** [comment]
> Can anybody help me to solve this issue regarding bun installation
> 
> ![image.png](https://camo.githubusercontent.com/7764cb793b751a0d31368946b8a9fe281f908a52546ee13d558b91856a4bb5ec/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313135323436313537353034333639303439362f313135323436313537353136353332313231362f696d6167652e706e67)
> 
> _Originally reported on Discord: [`Installation Problem`](https://discord.com/channels/876711213126520882/1152461575043690496/1152461575043690496)_

At the moment Bun does not support native Windows installation, you'll have to use WSL. To be noted that the WSL feature is still in the experimental stage and it is not ready for production. Hope that they will implement that in the near future.

**Comment by Electroid** [comment]
We will update it soon, follow this issue: #43
