### ISSUE TITLE
Error: "Undefined is not a constructor (evaluating 'new Stream')"

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5591]
Hello everyone I've an application using a fair old npm package in order to manage read and write to a key-value store.

Before opening an issue, here are some info:
- the store: memcached
- the lib where the error occurs: https://github.com/3rd-Eden/memcached (where the error is happening https://github.com/3rd-Eden/memcached/blob/master/lib/memcached.js#L169)

The error stack trace:

```
"TypeError: undefined is not a constructor (evaluating 'new Stream')
at factory (/Users/**/**/**/**/**/node_modules/memcached/lib/memcached.js:166:31)
at allocate (/Users/**/**/**/**/**/node_modules/jackpot/index.js:219:13)
at attempt (/Users/**/**/**/**/**/node_modules/jackpot/index.js:131:9)
at <anonymous> (/Users/**/**/**/**/**/node_modules/retry/lib/retry_operation.js:57:6)
at pull (/Users/**/**/**/**/**/node_modules/jackpot/index.js:128:26)
at connect (/Users/**/**/**/**/**/node_modules/memcached/lib/memcached.js:220:39)
at memcachedCommand (/Users/**/**/**/**/**/node_modules/memcached/lib/memcached.js:309:20)
at get (/Users/**/**/**/**/**/node_modules/memcached/lib/memcached.js:830:13)
at <anonymous> (/Users/**/**/**/**/**/node_modules/@andreafspeziale/nestjs-memcached/dist/memcached.service.js:86:14)
at get (/Users/**/**/**/**/**/node_modules/@andreafspeziale/nestjs-memcached/dist/memcached.service.js:76:14)
..."
```

Any help would be appreciated since I'm trying to deploy my application using Bun and this is blocking righ now.

Thanks again!

_Originally reported on Discord: [`Error: "Undefined is not a constructor (evaluating 'new Stream')"`](https://discord.com/channels/876711213126520882/1152345390004314213/1152345390004314213)_

**Comment by andreafspeziale** [comment]
So I placed some console.log() and what is pretty clear is the following:

with bun Stream si undefined as stated
with node it's actually something [Function: Socket]

Stream is imported like this in the lib var Stream = require('net').Stream

Is it something expected? It sounds like an API incompatibility

<img width="754" alt="Screenshot 2023-09-18 alle 13 41 05" src="https://github.com/oven-sh/bun/assets/7680940/0f5cff84-4ac2-4900-86aa-049efc063ef3">

**Comment by pporto** [comment]
I'm having exactly the same problem.

**Comment by Jarred-Sumner** [comment]
@andreafspeziale i have a fix in #5591, sorry this took so long

**Comment by andreafspeziale** [comment]
I'm pumped, I'll test as you suggested me on [Twitter](https://x.com/andreafspeziale/status/1828015445586125284) as soon as the CI is completed

**Comment by andreafspeziale** [comment]
@Jarred-Sumner Tested and not working. 

But:

`Undefined is not a constructor (evaluating 'new Stream')`

is not thrown anymore so I believe this current issue is fixed. 

Still, I'm not sure if the cause of what's still broken is related to the above because the error is different.

Scenario: I'm interacting with a fair old [memcached client](https://www.npmjs.com/package/memcached) which using under the hood a package named [jackpot](https://www.npmjs.com/package/jackpot)

<img width="732" alt="Screenshot 2024-08-26 alle 14 26 06" src="https://github.com/user-attachments/assets/9f1896a6-b7c0-4a6e-bba1-02407d4aec1f">

Let me know I'll be happy to eventually provide more feedbacks!

**Comment by andreafspeziale** [comment]
Oh I see, `destroySoon` is missing in [here](https://github.com/oven-sh/bun/blob/acd6b4c22e83ffc617f5b669f4438fc429352356/src/js/node/net.ts) like is actually present [here](https://github.com/nodejs/node/blob/2eff28fb7a93d3f672f80b582f664a7c701569fb/lib/net.js#L785)

**Comment by Jarred-Sumner** [comment]
@andreafspeziale follow-up for destroySoon: https://github.com/oven-sh/bun/pull/13555
