### ISSUE TITLE
The node  file system module "fs" is not recognized in bun when compiled from typescript to javascript using the bun build command

### ISSUE THREAD

**Issue by sergelawson** [oven-sh/bun#5592]
### What version of Bun is running?

1.0

### What platform is your computer?

MacOS 

### What steps can reproduce the bug?

`import fs from "fs";

const srcDir = process.argv[2];

const results = fs.readdir(srcDir, {}, (error) => console.error(error));

console.log(fs);`

This code is actually an index.ts file. 
When I try building the file with bun build ./index.ts --outdir  ./dist/index.js 
It spits out fs as var fs = (()=>({}));  which should actually be the node file system module.

### What is the expected behavior?

import fs form 'fs' 

must be compiled to 

var fs = require('fs')

### What do you see instead?

`var fs = (()=>({}));
var srcDir = process.argv[2];
var results = fs.readdir(srcDir, {}, (error) => console.error(error));
console.log(fs);`

fs is an anonymous function

**Comment by franciscop** [comment]
Two suggestions:

- Could you please try `import fs from 'node:fs';` and see if that works? (unsure)

- If you add the [`--target node` that definitely works](https://bun.sh/docs/bundler#target), since it defaults to `browser`.

**Comment by michaelessiet** [comment]
Did `node:fs` work? As the second suggestion isn't an option for us at the moment
