### ISSUE TITLE
bun upgrade gives me  ( illegal hardware instruction (core dumped)  bun upgrade ) 

### ISSUE THREAD

**Issue by Adamkaram** [oven-sh/bun#5599]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Ubuntu 23.04 (Lunar Lobster)

### What steps can reproduce the bug?

i run (bun upgrade )

install bun with 
curl https://bun.sh/install | bash

### What is the expected behavior?

upgrade to 1.0.2

### What do you see instead?

 20187 illegal hardware instruction (core dumped)  bun upgrade

### Additional information

my cpu is core 2 duo so if bun is just working with CPUs supporting the AVX2 instruction set then i'm out right?

**Comment by 7f8ddd** [comment]
What does `uname -ms` say in terminal?

**Comment by Adamkaram** [comment]
> What does `uname -ms` say in terminal?

Linux x86_64

**Comment by 7f8ddd** [comment]
It seems like the solution or talks about this are located here: https://github.com/oven-sh/bun/issues/67

Specifically https://github.com/oven-sh/bun/issues/67#issuecomment-1179486581 has the solution.

**Comment by Adamkaram** [comment]
> It seems like the solution or talks about this are located here: #67
> 
> Specifically [#67 (comment)](https://github.com/oven-sh/bun/issues/67#issuecomment-1179486581) has the solution.

thanx but it gives me 

root@panaroid:/home/adam/.oh-my-zsh# curl https://gist.githubusercontent.com/fuka-g/afb29296db34d2451cdddcc14dbeef3c/raw/0c9e5d43910cf53b9bd82b358559bb8b75ebbfdc/bun-sde-fix-install_script.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     26      0 --:--:-- --:--:-- --:--:--    26
bash: line 1: 404:: command not found

**Comment by Adamkaram** [comment]
i've tried this but with no luch even if i dowmload last versin from intel same issue 
https://github.com/oven-sh/bun/issues/762#issuecomment-1186505847

Edit i've make it worked with 
echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc

**Comment by trupakufi** [comment]
> > It seems like the solution or talks about this are located here: #67
> > Specifically [#67 (comment)](https://github.com/oven-sh/bun/issues/67#issuecomment-1179486581) has the solution.
> 
> thanx but it gives me
> 
> root@panaroid:/home/adam/.oh-my-zsh# curl https://gist.githubusercontent.com/fuka-g/afb29296db34d2451cdddcc14dbeef3c/raw/0c9e5d43910cf53b9bd82b358559bb8b75ebbfdc/bun-sde-fix-install_script.sh | bash % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 14 100 14 0 0 26 0 --:--:-- --:--:-- --:--:-- 26 bash: line 1: 404:: command not found

I had another error running it like this.

![image](https://github.com/oven-sh/bun/assets/72455038/110ef565-8782-48f2-972a-f4352f6af815)

**Comment by algj** [comment]
My laptop was released in 2022-02-19 (81WB IdeaPad 3) and AVX2 is not supported, neither is bun. Disappointed.
