### ISSUE TITLE
`net.Socket.prototype` is `undefined`

### ISSUE THREAD

**Issue by teh-obeng** [oven-sh/bun#5606]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

- Create `index.js` file
- Put this
```javascript
import net from "net";
import { promisify } from "util";

console.log(net.Socket.prototype);
const asyncWrite = promisify(net.Socket.prototype.write);
```
- Run `bun run index.js`

### What is the expected behavior?

the `console.log` should produce prototype of `net.Socket`, It could works if I run `node index.js`

### What do you see instead?

It is `undefined`

**Comment by colinhacks** [comment]
This is the root of https://github.com/apify/crawlee/issues/2046
