### ISSUE TITLE
console.log off-by-one error with typed arrays

### ISSUE THREAD

**Issue by SheetJSDev** [oven-sh/bun#561]
```js
var x = new Uint8Array([ 1,2,3,4,5 ]);
var y = x.slice(1);
var z = x.subarray(1);
var yy = y.subarray(1);
var zz = z.subarray(1);
console.log(yy, zz);
```

Based on the spec, both should be `Uint8Array` with 3 elements (`3, 4, 5`)

Node, Chrome and Safari give the expected result `Uint8Array(3) [ 3, 4, 5 ] Uint8Array(3) [ 3, 4, 5 ]`

Bun currently prints `[ 4, 5, 0 ] [ 5, 0, 0 ]`

**Comment by Jarred-Sumner** [comment]
This will be fun to debug

**Comment by ernischay** [comment]
Reproducible, Seems to be some issue with the subarray method.
Please see the image below for a comparison. Thanks, @SheetJSDev.

![image](https://user-images.githubusercontent.com/93801948/178247514-d3ec6d14-16da-4796-b97a-b6562e936ba9.png)
![image](https://user-images.githubusercontent.com/93801948/178247582-b004ef7c-dd8c-4ad2-96b2-6f71b7f5f88a.png)

This is the code used which same for both runs.
```
var x = new Uint8Array([ 1,2,3,4,5 ]);
console.log(x);
var y = x.slice(1);
console.log(y);
var z = x.subarray(1);
console.log(z);
var yy = y.subarray(1);
var zz = z.subarray(1);
console.log(yy, zz);
```

**Comment by Jarred-Sumner** [comment]
So, this is specific to Bun and not `jsc`

Running in the `jsc` shell using the same version that bun embeds:
```
bun on  main took 8s
❯ ./src/bun.js/WebKit/WebKitBuild/Release/bin/jsc /tmp/a.js
3,4,5 3,4,5

bun on  main
❯ ./src/bun.js/WebKit/WebKitBuild/ReleaseLTO/bin/jsc /tmp/a.js
3,4,5 3,4,5

bun on  main
❯ jsc /tmp/a.js
3,4,5 3,4,5
```

I'm inclined to think this is a strange JSC::Structure issue consistency issue in Bun

The big question is how is Bun causing the `subarray` function prototype to change. My best guess is either:
- Something to do with the TypedArrayController
- `Buffer`'s usage of `Object.setPrototypeOf` is causing things to change the `Uint8Array` structure when it should not be

Edit: this is a console.log bug. Not a JSC issue

<img width="284" alt="image" src="https://user-images.githubusercontent.com/709451/178250493-60a7195c-7ddb-4675-a5f5-de181ad79607.png">

```js
❯ cat /tmp/a.js
globalThis.print ||= console.log
var x = new Uint8Array([ 1,2,3,4,5 ]);
var y = x.slice(1);
var z = x.subarray(1);
var yy = y.subarray(1);
var zz = z.subarray(1);
print(yy[0], yy[1], yy[2], yy, zz);

```

**Comment by ernischay** [comment]
Yes, Probably @Jarred-Sumner  
I checked for other data types like Int8Array. It's giving different output as well.
