### ISSUE TITLE
Node API's not included in `build --compile` although docs say they are

### ISSUE THREAD

**Issue by avwie** [oven-sh/bun#5619]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

- Include dependency: `"@azure/identity": "^3.3.0"`

- Create this file:

``` // script.ts
import {EnvironmentCredential} from "@azure/identity";

new EnvironmentCredential();
```

- Run `bun build ./src/script.ts --compile --outfile script`
- Run `./script`
- Result: `error: FileNotFound reading "node:http"`

### What is the expected behavior?

Working script.

### What do you see instead?

Not working script

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.0.2

`bun upgrade`
