### ISSUE TITLE
Error when installing packages

### ISSUE THREAD

**Issue by mbledkowski** [oven-sh/bun#562]
### Version

0.1.2

### Platform

Linux jupiter 5.18.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

Initialize new project
> npm init

Install package
> bun install express

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Bun installs a package

### What do you see instead?

bun install v0.1.2
[12.00ms] done
No packages! Deleted empty lockfile

**Comment by mbledkowski** [comment]
You need to use bun add instead

**Comment by mieszko4** [comment]
> You need to use bun add instead

Thnx. But when do I use `bun add` and when `bun install`?
The error message is not intuitive and on the main page i(https://bun.sh/) it says to use `bun install`.
Would be great either correct the error msg or explain this in docs :)

**Comment by mbledkowski** [comment]
You use `bun install` to install packages from package.json, and `bun add` to add packages to package.json. Similarly to how things are being done with yarn
