### ISSUE TITLE
Support timeout on sqlite

### ISSUE THREAD

**Issue by internalfx** [oven-sh/bun#5621]
### What is the problem this feature would solve?

Sometimes the sqlite database is being read by another application and is intermittently locked for short periods of time. There is no way (that I know of) to currently have the database wait for the lock to free.

### What is the feature you are proposing to solve the problem?

the better-sqlite3 library has a `timeout` option...

```
options.timeout: the number of milliseconds to wait
when executing queries on a locked database,
before throwing a SQLITE_BUSY error (default: 5000).
```

### What alternatives have you considered?

I don't know of another alternative.

**Comment by karimfromjordan** [comment]
Isn't this already possible by running the following?
```js
db.run('pragma busy_timeout = 5000;');
```

**Comment by internalfx** [comment]
Nice! That does work. I always thought that was supported by the connection library not SQLITE itself. Good to know!
