### ISSUE TITLE
[bun-types] Module '"fs"' has no default export

### ISSUE THREAD

**Issue by alexsch01** [oven-sh/bun#5633]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What version of ```bun-types``` is running?

1.0.2

### What platform is your computer?

Linux 5.15.124-20260-g158060cabb35 x86_64 unknown

### What steps can reproduce the bug?

Ran...
```bash
bun add -d bun-types
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "types": ["bun-types"]
    }
}
```

![image](https://github.com/oven-sh/bun/assets/5721147/c8e091c0-00d1-4c47-9ba3-436639c09384)

### The steps that do not reproduce the bug

Ran...
```bash
bun add -d @types/node
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "types": ["node"]
    }
}
```

**Comment by jumoog** [comment]
Add `"allowSyntheticDefaultImports": true` to your tsconfig.

**Comment by alexsch01** [comment]
@jumoog The ```@types/node``` package doesn't need this

**Comment by alexsch01** [comment]
@types/node doesn't need this, so I believe it's a bug.

I updated the issue to include this information
