### ISSUE TITLE
Incorrect Handling of Relative URLs in Fetch HTTP Redirects

### ISSUE THREAD

**Issue by eskalera** [oven-sh/bun#5635]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I have encountered an issue with the handling of HTTP redirects involving relative URLs in the bun.sh runtime. According to the HTTP/1.1 specifications, when a server responds with a redirect containing a relative URL in the `Location` header, the HTTP client should interpret that relative URL with respect to the original request URL.

To reproduce this issue, I set up a simple Express.js server that responds to a GET request with a 302 redirect to a relative URL. Here is the server code:

```javascript
const express = require('express');
const app = express();
const port = 3000;

app.get('/redirect', (req, res) => {
  res.redirect(302, 'relative/path');
});

app.get('/relative/path', (req, res) => {
  res.send('You have been redirected to a relative path!');
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
});
```
And this is the client code which throws different results if executed with nodejs or bun.sh

```javascript
const resp = await fetch("http://localhost:3000/redirect", {
    method: "GET",
    verbose: true
});
const respText = await resp.text()
console.log(respText)
```

I found that when I make a request to `http://localhost:3000/redirect` using bun.sh, the client does not follow the redirect correctly. Instead of being redirected to `http://localhost:3000/relative/path` (as would be expected according to the HTTP/1.1 specifications), the client is attempting to access `http://localhost:3000relative/path`.

However, when I modify the server to respond with a redirect to `/relative/path` (noting the leading slash), bun.sh follows the redirect correctly.

### What is the expected behavior?

The formed redirect url should be `{host}/{relative/path}`. Therefore the output in my example should be
```
You have been redirected to a relative path!
```

### What do you see instead?

The formed redirect url is `{host}{relative/path}`. Therefore the current output is
```
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:3000/redirect"
```

### Additional information

This shouldn't be relevant to the case but I've tested it with a Bun server as well to test server redirects.

```javascript
const server = Bun.serve({
    port: 3000,
    fetch(req) {
        console.log(req.url);
        const url = URL(req.url);
        if (url.pathname === "/redirect") return Response.redirect("relative/path", 302);
        if (url.pathname === "/relative/path") return Response("This is the relative path!");
        return new Response("404!");
    },
});

console.log(`Listening on localhost:${server.port}`);
```

**Comment by elie-h** [comment]
Facing this issue too in another context
Redirects when performing a fetch loop infinitely and then raise an exception.

To recreate, with a simple script:

```
const response = await fetch("https://x.com", {
  verbose: true,
});
```

and the output is:

```
TooManyRedirects: The response redirected too many times. For more information, pass `verbose: true` in the second argument to fetch()
```

Same call works fine in nodejs & python. 
Using bun 1.0.2
