### ISSUE TITLE
Net.socket is missing prototype definition

### ISSUE THREAD

**Issue by tim-brand** [oven-sh/bun#5640]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.4.0 x86_64 i386

### What steps can reproduce the bug?

I tried to run my existing tests, that use the mockttp package.
This fails with the following error:
```
TypeError: undefined is not an object (evaluating 'net.Socket.prototype.resetAndDestroy')
```
I checked and the prototype property if undefined, so resulting in an error.
Example of the code that's using this: https://github.com/httptoolkit/mockttp/blob/main/src/util/socket-util.ts#L83

**Comment by Electroid** [comment]
Thanks for reporting, this is indeed an issue we need to fix. Already reported here: #5606

**Comment by tim-brand** [comment]
Ah I really tried to search for an existing issue. Sorry for the duplicate, and thanks for taking care of it!
