### ISSUE TITLE
Node incompatibility: mocha library

### ISSUE THREAD

**Issue by pubkey** [oven-sh/bun#5645]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Install the [mocha npm library](https://www.npmjs.com/package/mocha)
2. Create a file `test.js` with the following content:
```js
import { describe, it } from 'mocha';
describe('my tests', () => {
    it('should log one', () => {
        console.log('one');
    });
});
```

3. run the file with `bun test.js`

### What is the expected behavior?

The code should not fail and console log "one"

### What do you see instead?

```bash
106 | };
107 | exports.before = function (...args) {
108 |   return (currentContext.before || currentContext.suiteSetup).apply(this, args);
109 | };
110 | exports.describe = function (...args) {
111 |   return (currentContext.describe || currentContext.suite).apply(this, args);
             ^
TypeError: undefined is not an object (evaluating 'currentContext.describe')
      at /home/xxx/workspace/node_modules/mocha/lib/mocha.js:111:10
      at /home/xxx/workspace/test.js:7:0
      at processTicksAndRejections (:55:76)
```

**Comment by Electroid** [comment]
Interesting, this is either a Node.js or module loading bug.

**Comment by pubkey** [comment]
Sorry, the error was on my side.

Running `node test.js` gives the same error, so bun is not the problem here.
