### ISSUE TITLE
Bun does not install packages via a proxy 

### ISSUE THREAD

**Issue by forinda** [oven-sh/bun#565]
### What is the problem this feature will solve?

Enable those working with `bun` in `proxy` environment to be able to add packages using `bun` in that network

### What is the feature you are proposing to solve the problem?

Like npm and yarn being able to set proxy in the configuration or pick the URL from `$bash` variables

### What alternatives have you considered?

Tried to set them in the `bunfig.toml` but it could not load up

**Comment by amarpathak** [comment]
Can I take it up ?

**Comment by forinda** [comment]
> Can I take it up ?

Yes

**Comment by FunnyDewd** [comment]
I seem to be having issues with any command that accesses the network. Would this fix be applied to other commands like `bun upgrade` and `bun create` ?

**Comment by moderation** [comment]
I can't find it in Github or Discord or Twitter, but I don't believe `bun` uses `HTTP_PROXY` environment variables today - https://twitter.com/jarredsumner/status/1444982022775062535

**Comment by Electroid** [comment]
We will fix this, being tracked in #1440

**Comment by jylin** [comment]
`http_proxy` and `https_proxy` don't seem to work for me for `bun install` and `bun upgrade`. I tried the capitalized variants too. Is this confirmed to be working?

Comparatively, my proxy works with `npm install`, `yarn install`, and `pnpm install`.
