### ISSUE TITLE
CLI options with double hyphen after -- are still passed to the executable as options instead of arguments in bun x

### ISSUE THREAD

**Issue by cs-clarence** [oven-sh/bun#5651]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 6.4.15-200.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

1. run `bun x @rencedm112/with-env -- ls --all`

You should see something like this:
![image](https://github.com/oven-sh/bun/assets/71768661/a43c82ff-0af3-4772-b84c-afffa79f9153)

The --all flag is still passed to the executable (`with-env`) as options even though it's it supposed to be passed to it as an argument after double hyphen `--`. Single hyphen flags work fine, though:  `bun x @rencedm112/with-env -- ls -a`

### What is the expected behavior?

Options should not be passed to the executable after `--` 

### What do you see instead?

Options are still passed to the executable.

**Comment by Jarred-Sumner** [comment]
All options after the script/executable name are passed through to the executable. Try removing the `--`
