### ISSUE TITLE
Bun errors out when trying to import modules from an NPM package called "Crawlee" 

### ISSUE THREAD

**Issue by XooTB** [oven-sh/bun#5652]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

To reproduce the problem, Just create a new Crawlee project with `npx crawlee create my-crawler`  or `bunx crawlee create my-crawler`. By default Node in included in scripts. 
![image](https://github.com/oven-sh/bun/assets/42840601/a4cda3b3-520b-4846-95d1-20dd297c840d)
So change that to Bun and try running it. It should error out. 

### What is the expected behavior?

The expected output would be to import the package and run it. Instead, It errors out.

### What do you see instead?

Here's the Error that I get. 

![image](https://github.com/oven-sh/bun/assets/42840601/25bc89a2-f975-4aff-9ac0-cce3ddb85042)

`$ bun src/main.ts
2 | Object.defineProperty(exports, "__esModule", { value: true });
3 | exports.customConnect = void 0;
4 | const tslib_1 = require("tslib");
5 | const net_1 = tslib_1.__importDefault(require("net"));
6 | const util_1 = require("util");
7 | const asyncWrite = (0, util_1.promisify)(net_1.default.Socket.prototype.write);
                                            ^
TypeError: undefined is not an object (evaluating 'net_1.default.Socket.prototype.write')
      at /home/xoot/projects/drop-help/node_modules/proxy-chain/dist/custom_connect.js:7:41
      at globalThis (/home/xoot/projects/drop-help/node_modules/proxy-chain/dist/custom_connect.js:26:24)
      at require (:1:20)
      at /home/xoot/projects/drop-help/node_modules/proxy-chain/dist/server.js:21:6
      at globalThis (/home/xoot/projects/drop-help/node_modules/proxy-chain/dist/server.js:546:17)
      at require (:1:20)
      at /home/xoot/projects/drop-help/node_modules/proxy-chain/dist/index.js:5:8
      at globalThis (/home/xoot/projects/drop-help/node_modules/proxy-chain/dist/index.js:8:59)
error: script "dev" exited with code 1 (SIGHUP)`

**Comment by Electroid** [comment]
Thanks for reporting, we're tracking this issue here: #5640
