### ISSUE TITLE
TypeError when running simple example from Happy DOM's Wiki

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#5658]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. `bun init`
2. `bun add happy-dom@12.0.1 --exact`
3. Replace contents of `index.ts` with the following (taken from Happy DOM's "[Getting Started](https://github.com/capricorn86/happy-dom/wiki/Getting-started)" page):
    ```js
    import { Window } from 'happy-dom';

    const window = new Window({
       url: 'https://localhost:8080',
       width: 1024,
       height: 768
    });
    const document = window.document;

    document.body.innerHTML = '<div class="container"></div>';

    const container = document.querySelector('.container');
    const button = document.createElement('button');

    container.appendChild(button);

    // Outputs "<div class="container"><button></button></div>"
    console.log(document.body.innerHTML);
    ```
4. `bun run index.ts`

### What is the expected behavior?

Outputs `<div class="container"><button></button></div>` without any errors / warnings.

### What do you see instead?

```
<div class="container"><button></button></div>
64 |      * @see https://www.quirksmode.org/js/events_order.html#link4
65 |      * @param event Event.
66 |      * @returns The return value is false if event is cancelable and at least one of the event handlers which handled this event called Event.preventDefault().
67 |      */
68 |     dispatchEvent(event) {
69 |         const window = this._getWindow();
                           ^
TypeError: this._getWindow is not a function. (In 'this._getWindow()', 'this._getWindow' is undefined)
      at dispatchEvent ($HOME/happy-dom-example/node_modules/happy-dom/lib/event/EventTarget.js:69:23)
      at dispatchEvent ($HOME/happy-dom-example/node_modules/happy-dom/lib/event/EventTarget.js:91:20)
      at $HOME/happy-dom-example/node_modules/happy-dom/lib/nodes/document/Document.js:861:12
```

### Additional information

I know that DOM testing is [already supported / documented](https://bun.sh/docs/test/dom). I may be wrong with this assumption, but I think that because in the DOM testing example `GlobalRegistrator ` from `@happy-dom/global-registrator` is done in a preload, the TypeError isn't shown. I have a use case outside of testing, and would like to use `Window` rather than `GlobalWindow`. Also, `_getWindow` appears to be a function in the `EventTarget` class, so I'm not sure why this error is being shown.

**Comment by BjornTheProgrammer** [comment]
I second this issue. 

I added some logging, outputting the constructor being called, and outputting the call in the function that failed.
```js
_getWindow() {
    console.log('constructor:', this.constructor.name);
    if (this.ownerDocument) {
        return this.ownerDocument.defaultView;
    }
    if (this.defaultView) {
        return this.defaultView;
    }
    if (this.document) {
        return this;
    }
    return null;
}
```

### Node
```shell
$ node index.js
dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: Window
```

### Bun
```shell
$ bun run index.js
dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent [Function: _getWindow]
constructor: HTMLDocument

dispatchEvent undefined
```

It seems like the `this` object is getting overwritten somewhere causing the issue, right when the Window object should be the reference.

Additionally, I tested this with the following bare minimum setup
```js
import { Window } from 'happy-dom';

const window = new Window();
```

Also regarding your suspicion of preloading, I attempted this with a preloaded file, and it didn't seem to work.

**Comment by ghost** [comment]
Just an update on this ticket. While `happy-dom@12.0.1` is failing with the same TypeError, using the latest version (currently `13.5.3`) appears to work with Bun.
