### ISSUE TITLE
bun:sqlite truncates integers that cannot fit in a double

### ISSUE THREAD

**Issue by JackTYM** [oven-sh/bun#5661]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.4.0-153-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a SQLite row with an INT or DOUBLE value over 53 bits
Select the row using .get() or .values() and print it
Resulting numbers are changed

### What is the expected behavior?

The unchanged version of the number should be given

### What do you see instead?

INT provided with value 990760989492400188
Object given with value 990760989492400100

### Additional information

Seemingly happens from numbers over 53 bits

**Comment by JackTYM** [comment]
Current workaround is to just store text, but it is preferable if I could use normal integers or some sort of number data structure

**Comment by Prinzhorn** [comment]
https://github.com/oven-sh/bun/issues/1536 https://github.com/oven-sh/bun/issues/5256

**Comment by nektro** [comment]
53 bits is the max of `Number.MAX_SAFE_INTEGER` for baseline javascript numbers which use the same data type as DOUBLE. (`9007199254740991` for reference).

for clarification:
is the expectation that the number would then instead return in a BigInt instead? was the input already a BigInt?
