### ISSUE TITLE
npm-run-all style functionality in bun run

### ISSUE THREAD

**Issue by quantizor** [oven-sh/bun#5663]
### What is the problem this feature would solve?

If you have a set of commands that you generally want to run together, packages like [`npm-run-all`](https://www.npmjs.com/package/npm-run-all) make this a bit easier by allowing wildcards. Would love to see something like this built into bun directly for convenience.

### What is the feature you are proposing to solve the problem?

for `bun target:*` it should run all `package.json` scripts with the prefix `target:`

### What alternatives have you considered?

Third-party libraries--they work but it would be great to have it built-in.

**Comment by Electroid** [comment]
Thanks for opening this issue, we're tacking this here: #4402
