### ISSUE TITLE
Rendering `.tsx` stream with React 18.3 fails to pass `oha` simple load test

### ISSUE THREAD

**Issue by cayter** [oven-sh/bun#5664]
### What version of Bun is running?

1.0.2, 1.0.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

React/ReactDOM v18.3

`index.tsx`
```tsx
import { type Server as BunServer } from "bun";
import { renderToReadableStream } from "react-dom/server";

Bun.serve({
	hostname: "0.0.0.0",
	port: 3000,
	fetch: async (request: Request, server: BunServer) => {
		return new Response(
			await renderToReadableStream(
				<div className="w-[40rem]">
					<div className="pb-4">
						<div className="text-base">Move Goal</div>
						<div>Set your daily activity goal.</div>
					</div>

					<div className="pb-2">
						<div className="flex items-center justify-center space-x-2">
							<div className="h-8 w-8 shrink-0 rounded-full">
								<span className="sr-only">Decrease</span>
							</div>

							<div className="flex-1 text-center">
								<div className="text-5xl font-bold tracking-tighter">{200}</div>
								<div className="text-[0.70rem] uppercase text-muted-foreground">
									Calories/day
								</div>
							</div>

							<div className="h-8 w-8 shrink-0 rounded-full">
								<span className="sr-only">Increase</span>
							</div>
						</div>
					</div>

					<div>
						<div className="w-full">Set Goal</div>
					</div>
				</div>,
			),
			{
				headers: {
					"Content-Type": "text/html",
				},
			},
		);
	},
});
```

1. Run `bun index.tsx`.
2. Run `oha http://0.0.0.0:3000 -z 5s`.

https://github.com/oven-sh/bun/assets/242017/aef428d1-a575-4efb-a713-99107d3bbaad

**Comment by Jarred-Sumner** [comment]
This is a lot like one of our most frequently run benchmarks. What version of react & react-DOM?

**Comment by cayter** [comment]
Btw, I tested with `renderToString()` and it works fine. Also, this issue only started with 1.0.2, 1.0.1 is working entirely fine.

**React/ReactDOM versions**
<img width="349" alt="Screenshot 2023-09-18 at 1 07 02 PM" src="https://github.com/oven-sh/bun/assets/242017/d280e1c5-5c39-40ab-9ccd-f1d94f6d379f">

**Comment by Jarred-Sumner** [comment]
I'm able to reproduce it in @18.3 and not @18.2 and also only very recently. It looks like requests need to flush but aren't

**Comment by cayter** [comment]
Should we revert back to 18.2 or Bun team will make sure to fix it? Considering 18.3 is around the corner (I guess).

**Comment by cayter** [comment]
Reverted back to 18.2.0 for both react/react-dom and still getting the same issue with 1.0.2/1.0.3. Will stick to 1.0.1 first. Thanks for following up.

**Comment by Jarred-Sumner** [comment]
> Reverted back to 18.2.0 for both react/react-dom and still getting the same issue with 1.0.2/1.0.3. Will stick to 1.0.1 first. Thanks for following up.

I'm able to reproduce it on Bun v1.0.1 locally. And earlier versions when react & react-dom are `@canary`, but not when `@experimental` or `@18.2.0`

**Comment by cayter** [comment]
> > Reverted back to 18.2.0 for both react/react-dom and still getting the same issue with 1.0.2/1.0.3. Will stick to 1.0.1 first. Thanks for following up.
> 
> I'm able to reproduce it on Bun v1.0.1 locally. And earlier versions when react & react-dom are `@canary`, but not when `@experimental` or `@18.2.0`

Just verified. You're right that Bun v1.0.1 also have issues with React/ReactDOM canary.

**Comment by wladpaiva** [comment]
Had the same issue using 18.2.0 when running the `build/index.js` from a newly created remix built. We'll need to be able to import the `build/index.js` if we want to use Express/Elysia + Remix

<img width="1181" alt="Screenshot 2023-09-29 at 16 26 28" src="https://github.com/oven-sh/bun/assets/1843792/efbcb438-05e1-4b6a-945d-36d2151f7183">

The funny thing is that remix-serve works fine. ¯\_(ツ)_/¯ 
<img width="462" alt="Screenshot 2023-09-29 at 16 29 16" src="https://github.com/oven-sh/bun/assets/1843792/036af973-4d0c-4b83-9584-3bb6d42e34a3">

EDIT: it works fine if I reveal entry.server from remix and change the react-dom import to
```ts
import { renderToPipeableStream } from "react-dom/server.node";
```

**Comment by lauhon** [comment]
Not sure if Im right here, but I stumbled upon this when trying to run remix with bun via docker (to be able to deploy it on render.com).

Changing the `renderToPipeableStream` import like @wladpaiva describes enables to build and serve the app, but then the server does not deliver anything to the browser on requests. Upon visiting the app I get the following in the console:

```log
$ remix-serve ./build/index.js
[remix-serve] http://localhost:3000 (http://172.17.0.2:3000)
Expected a Response object
GET / - - - 14.717 ms
```

Also, the browser behaves very strangely, if I visit localhost on a tab that has another page open, the request just refreshes the old page. If I try to visit localhost from a new tab, it just clears the address bar and does nothing.

**Comment by Jarred-Sumner** [comment]
No longer happens as of Bun v1.1.30+ in either React v18.3 or React v19 (`@canary`) 

Let us know if you still run into this issue and we'll be happy to fix 

I think it was a flushing issue before
