### ISSUE TITLE
'zone.js/node' fails to import

### ISSUE THREAD

**Issue by NickGeek** [oven-sh/bun#5665]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Write a script containing:
```
import 'zone.js/node';
```

### What is the expected behavior?

zone.js should import correctly.

### What do you see instead?

```
1000 |             }
1001 |         }
1002 |     }
1003 |     function patchMethod(target, name, patchFn) {
1004 |         var proto = target;
1005 |         while (proto && !proto.hasOwnProperty(name)) {
                            ^
TypeError: undefined is not an object (evaluating 'proto.hasOwnProperty(name)')
```

**Comment by nektro** [comment]
is this still impacting you? it appears to be working on my end in Bun 1.1.10 (you may need to run `bun upgrade`)

happy to investigate further if any issues using the library arise
