### ISSUE TITLE
Empty env variable is being wrapped in string for no reason

### ISSUE THREAD

**Issue by Maxim-Filimonov** [oven-sh/bun#5666]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```
EMPTY_ENV_VARIABLE= bun repl                           
process.env.EMPTY_ENV_VARIABLE
```
Outputs `'""'`

### What is the expected behavior?

```
EMPTY_ENV_VARIABLE= node 
process.env.EMPTY_ENV_VARIABLE
```
Outputs `''`

### What do you see instead?

An empty string within a string

### Additional information

A lot of tools in nodejs ecosystem rely on being able to to check for existence of env variable by `null || value.length == 0`
`'""'.length` returns 2. 
I tried in both bash and zsh the same behaviour. We are actually not settings env variables ourselves - they come from `doppler` secret manager like that when not set.

**Comment by liz3** [comment]
https://github.com/oven-sh/bun/pull/5679
