### ISSUE TITLE
`content-encoding` is removed from response

### ISSUE THREAD

**Issue by jimmywarting** [oven-sh/bun#5668]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```js
fetch('https://httpbin.org/gzip').then(async r => {
  const json = await r.json()
  console.log('accept-encoding', new Headers(json.headers).get('accept-encoding'))
  console.log('response', r.headers.get('content-encoding'))
})
```

### What is the expected behavior?

expected `content-encoding` to be `gzip`

### What do you see instead?

`null`

**Comment by liz3** [comment]
This peeked my interest but i have yet to find where this is done(where the header would be removed from the map), will tinker with this tmrw, seams like another good issue to get to know the codebase!

**Comment by jimmywarting** [comment]
I think this can have something to do with CORS request, 
browser do this too if you fetch something from another origin. 

I think the solution could be to treat any request as if it was **not** a CORS request

**Comment by liz3** [comment]
> I think this can have something to do with CORS request, browser do this too if you fetch something from another origin.
> 
> I think the solution could be to treat any request as if it was **not** a CORS request

A server side process does not have anything within the concept of a "origin" to begin with since theres no origin website.
Iirc there is cors policies for headers like that but they should not apply on server side processes, cors is by definition a browser concept.

My theory is that the header is not copied somewhere but im going to research this now.

**Comment by liz3** [comment]
https://github.com/oven-sh/bun/pull/5743
