### ISSUE TITLE
Install bun with a package manager on Linux

### ISSUE THREAD

**Issue by axeld-galadrim** [oven-sh/bun#5671]
### What is the problem this feature would solve?

The preferred way to install bun for Linux is actually by using cURL.
Which works for sure, but I don't think that it should be the only way to install it on Linux.
Because if you want to use a new version of it, you need to remove and re fetch it every time manually. Which is just a mess compared to using a Package Manager.
Linux being somewhat used by people who program and used by the majority of servers in the world, it just makes sense that it should be one of the first target of bun.
But currently, there is no official support for any package manager (apt, pacman, portrage, rpm, xbps, apk, nix). Sure, you have "Homebrew", but I don't think that it's very popular in the linux community, and needing to install a package manager just for a single program doesn't seem optimized.

### What is the feature you are proposing to solve the problem?

I think that bun should create some official packages in popular package manager, and show them as a way to install bun in https://bun.sh/docs/installation.
Currently, there are already 3 ways to install bun in the AUR, it's somewhat a mess.
I think that it would be a good thing for bun to allow people to install bun using a package manager.

**Comment by psy0rz** [comment]
i think that they WANT to have an official package for all the major distro's, but thats a lot of work. So thats why they have this as a stopgap solution that just works for now i think.

**Comment by axeld-galadrim** [comment]
> i think that they WANT to have an official package for all the major distro's, but thats a lot of work. So thats why they have this as a stopgap solution that just works for now i think.

Having an "official" package in the AUR isn't hard. And if it's the case, maybe they should mention it somewhere ?

**Comment by gtrabanco** [comment]
They tried for Brew but they required to compile in the client instead of install with binaries and there are some imposible requirements.

Don't know about others.

You can install with brew on linux by using oven tap. You can also use proto and npm. 


--

- https://github.com/Homebrew/homebrew-core/pull/105263

**Comment by axeld-galadrim** [comment]
> You can install with brew on linux by using oven tap

Already mentioned it. Not a suitable way to do that if you don't have brew installed. Which isn't the case for the huge majority of devices running Linux.

> You can also use proto and npm.

That's not the point of this issue.

Most of the package managers (not portrage) just download and install binaries. So even if you can't compile it on local (which is a huge problem in itself if it's the case) it won't be a problem for most of the package managers.

**Comment by gtrabanco** [comment]
Yes, I understand your point I agree but keep in mind that other package managers could have similar requirements anyway it deserves a try. Sure Bun team always welcome a help doing that.

---

Related issues just to keep tracking and make easier the triage they want to do this week:

- https://github.com/oven-sh/bun/issues/393
- https://github.com/oven-sh/bun/issues/862
- https://github.com/oven-sh/bun/issues/4471

**Comment by axeld-galadrim** [comment]
The thing is that, already many people created some packages for bun in the [AUR](https://aur.archlinux.org/) for example: [bunjs-bin](https://aur.archlinux.org/packages/bunjs-bin), [bun-bin](https://aur.archlinux.org/packages/bun-bin) and [bun](https://aur.archlinux.org/packages/bun). The problem is that there are not official. So people can just stop maintain them (like for bun-bin). It's why just letting people create packages that may be unmaintained and that bun hasn't control of, isn't a fantastic idea.
So, what do you need as help ?

**Comment by axeld-galadrim** [comment]
What can people do to help with that ?
Just to mention [eza](https://github.com/eza-community/eza), it's a new project, and it's already on 6 different packages managers for linux, and they are working to add another one.

**Comment by gtrabanco** [comment]
That question should be solved by Core Team =)

**Comment by Electroid** [comment]
Duplicate of #862
