### ISSUE TITLE
BunAST documentation for macros

### ISSUE THREAD

**Issue by zb3qk** [oven-sh/bun#5687]
### What is the type of issue?

Documentation is missing

### What is the issue?

BunAST seems like a very powerful tool to create macros in javascript, allowing users to create syntactically correct code at bundle-time using typescript type checking. Like Rust macros, this seems like a very powerful tool to generate code safely, and I wanted to get my hands dirty with it. I checked Github and the bun docs and was not able to find a reference to how users can get started using BunAST such as:
1. What packages to install to use BunAST with intellisense (primary)
2. Documentation for BunAST specifically with more examples (secondary)
I tried cloning the example repository, but was not able to get the macro code to compile, nor get any intellisense hints for BunAST. If folks here are familiar with BunAST, any pointer in the right direction to get started exploring would be appreciated.

### Where did you find it?

https://github.com/search?q=BunAST.CallExpression&type=code
https://github.com/oven-sh/bun/blob/8f8ab301b415ac92b28211114daae44230703b2f/examples/macros/matchInFile.tsx#L2

**Comment by Electroid** [comment]
Bun does not expose a public AST API. This is something people have asked for though: #2729
