### ISSUE TITLE
Segfault on bun dev

### ISSUE THREAD

**Issue by mattn** [oven-sh/bun#569]
### Version

0.1.2

### Platform

Linux oracle1 5.15.0-1011-oracle #15-Ubuntu SMP Fri Jun 10 12:18:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```
$ bun create next ./bun-app
$ cd bun-app
$ bun dev
```

```
$ ab -n 10000 http://127.0.0.1:3000/
```

![screenshot](https://user-images.githubusercontent.com/10111/178204842-a4f0d6ff-617a-4ee7-89d5-8587c07dfafa.gif)

### How often does it reproduce? Is there a required condition?

Any time

### What is the expected behavior?

Finish without segfault.

### What do you see instead?

Segfault.

**Comment by FinnRG** [comment]
This is a bug, but please note that the dev server isn't recommended for load testing. Duplicate of #407.
