### ISSUE TITLE
Change node_modules to bun_modules

### ISSUE THREAD

**Issue by ATLAS2002** [oven-sh/bun#5694]
### What is the problem this feature would solve?

**Confusion** : can be confused with npm

### What is the feature you are proposing to solve the problem?

I think we should change the name from 'node_modules' to 'bun_modules'.
So developers don't get confused whether they have accidentally bootstrapped the project with node, instead of bun

**Comment by Electroid** [comment]
Hi, thanks for submitting an issue. We don't want to do this because it would break compatibility with the node ecosystem. Bun is supports `node_modules` for a reason.
