### ISSUE TITLE
Throw error or warn when using incompatible NodeJS version when running `bun create`

### ISSUE THREAD

**Issue by BruceMcRooster** [oven-sh/bun#5705]
### What is the problem this feature would solve?

When using `bun create`, I got an error regarding unexpected import syntax. It took me quite some time to realize I needed to change my NodeJS version. It's a quick fix with `nvm` once I realized the problem, but some guidance from Bun might have been nice.

### What is the feature you are proposing to solve the problem?

A warning or error from Bun if you attempt to use an older version of NodeJS that may not support various features (I had problems because I had NodeJS 8 running, for example (don't ask why; I don't even know)).

**Comment by Electroid** [comment]
I don't think this is something we will do. We would need to run `node -v` on each run, which would make `bun create` slower.
