### ISSUE TITLE
Cannot find module 'bun:test' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by Lauro235** [oven-sh/bun#5706]
### What version of Bun is running?

1.0.2+37

### What platform is your computer?

Windows 11 (WSL Ubuntu 22.04.2 lts)

### What steps can reproduce the bug?

Create root directory with the following structure

- tsconfig.json
- index.ts
- tests/main.test.ts

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "test": ["tests/*.test.ts"]
    }
  }
}
```

In main.test.ts add the following

```ts
import { expect, test } from "bun:test";
```

### What is the expected behavior?

The modules should be found.

### What do you see instead?

Cannot find module 'bun:test' or its corresponding type declarations.ts(2307)

### Additional information

I use VSCode and run a WSL instance. When I run 'which bun' in my vscode terminal instance I see the path correctly so it seems to have installed correctly.

**Comment by Electroid** [comment]
You'll need to install Bun's types: `bun install -d bun-types`

**Comment by Lauro235** [comment]
Thanks for your help. It was a straight forward fix. Now I know about it, I'll be up and running in no time in the future. Thanks again.

**Comment by rupurt** [comment]
In a monorepo should `bun-types` be installed at the root level `package.json`? I can't get my lsp to pick it up.

**Comment by Maxim-Filimonov** [comment]
> In a monorepo should `bun-types` be installed at the root level `package.json`? I can't get my lsp to pick it up.

Same problem here. I'm using bun only for buildscripts and would like to get type completions for vscode. Installing in the root doesn't seem to work.

**Comment by zemse** [comment]
> You'll need to install Bun's types: bun install -d bun-types

On top of this I had to add `"types": ["bun-types"],` to compilerOptions.

**Comment by alissonsleal** [comment]
> > You'll need to install Bun's types: bun install -d bun-types
> 
> On top of this I had to add `"types": ["bun-types"],` to compilerOptions.

In the newer versions you don't even need to do that, assuming you now install with `bun install -D @types/bun`

```sh
$ bun remove bun-types
$ bun install -D @types/bun
```

docs: https://github.com/oven-sh/bun/blob/main/packages/bun-types/README.md
