### ISSUE TITLE
Bun doesnt run on WSL

### ISSUE THREAD

**Issue by Clasen00** [oven-sh/bun#571]
### Version

idk

### Platform

Linux 0560-docdoc 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. Install Bun from doc with this command `curl -fsSL https://bun.sh/install | bash`
2. As instruction said type `bun --help`
![image](https://user-images.githubusercontent.com/18239785/178228467-0b146d4c-c3c5-47ca-bc02-f078f59d4ff7.png)

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Bun manual for newbie

### What do you see instead?

Command 'bun' not found, did you mean:

### Additional information

Bun is installed in a correct directory but it never run

**Comment by neilnahid** [comment]
Please include this in your .bashrc file.

BUN_INSTALL="/home/shaleav/.bun"
PATH="$BUN_INSTALL/bin:$PATH"

**Comment by David00154** [comment]
You have not manually added the directory of bun to your bashrc so you should do so.
If it persists, run 
source $HOME/.bashrc
