### ISSUE TITLE
Bun doesn't build types when `declarationDir` is defined

### ISSUE THREAD

**Issue by joaopaulomoraes** [oven-sh/bun#5713]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Define `declarationDir` in the `tsconfig.json` file with the following

```json
{
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "build/types",
  }
}
```

### What is the expected behavior?

The exported types inside `build/types/{fileTypes.d.ts}`

### What do you see instead?

No types are generated 😞

**Comment by paperclover** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5141
