### ISSUE TITLE
Incompatibility with @aws-sdk v3 - Constructing `Request` with explicit `undefined` signal causes error

### ISSUE THREAD

**Issue by tekkeon** [oven-sh/bun#5715]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Construct a Request with explicit undefined value passed in:

```ts
// Causes error
new Request({
  url: "https://www.example.org",
  signal: undefined
});
```

Simply creating a request and omitting the signal does not trigger the error:

```ts
// Does not cause error
new Request({
  url: "https://www.example.org"
});
```

### What is the expected behavior?

The request should be constructed properly, same as if the signal property had been omitted altogether.

### What do you see instead?

```
1 | import type { ServeOptions } from "bun";
3 | 
4 | export default {
5 |   async fetch(request: Request): Promise<Response | undefined> {
6 |     new Request({
        ^
error: Failed to construct 'Request': signal is not of type AbortSignal.
```

### Additional information

This is causing at least the DynamoDB client from the `@aws-sdk/client-dynamodb` to not work. I suspect it is causing most of the `@aws-sdk` clients to fail, though, as the actual code that's failing is from a more core dependency, `@smithy/fetch-http-handler`. This package has the following code that causes the error to occur:

```js
if (typeof AbortController !== "undefined") {
  (requestOptions as any)["signal"] = abortSignal;
}

const fetchRequest = new Request(url, requestOptions);
```

Reference to the code: https://github.com/awslabs/smithy-typescript/blob/main/packages/fetch-http-handler/src/fetch-http-handler.ts#L80-L82

If `abortSignal` is undefined, RequestInit.signal still gets explicitly set as undefined as opposed to just being omitted.

**Comment by Jarred-Sumner** [comment]
This is fixed in the canary build of Bun.

`bun upgrade --canary`

If you continue to see this issue, feel free to leave a comment

**Comment by tekkeon** [comment]
Just tested it out and it works, thanks Jarred!
