### ISSUE TITLE
AccessDenied create package.json

### ISSUE THREAD

**Issue by dsincl12** [oven-sh/bun#5723]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Run the command to create a SvelteKit app: bun create svelte@latest <app-name>

### What is the expected behavior?

SvelteKit app successfully created

### What do you see instead?

$ bun create svelte@latest my-app
error: AccessDenied create package.json

**Comment by squishyu** [comment]
Seems to work fine both on Arch Linux *amd64* and Alpine Linux (Docker) *arm64* with bun **1.0.2**

```sh
> bun create svelte@latest                                                                      

create-svelte version 5.0.6

┌  Welcome to SvelteKit!
│
◇  Where should we create your project?
│    (hit Enter to use current directory)
│
◇  Directory not empty. Continue?
│  Yes
│
◇  Which Svelte app template?
│  SvelteKit demo app
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

✔ Typescript
  Inside Svelte components, use <script lang="ts">

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-add

Next steps:
  1: npm install (or pnpm install, etc)
  2: git init && git add -A && git commit -m "Initial commit" (optional)
  3: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat
```

**Comment by dsincl12** [comment]
Not so much on macOS then though? I'm running macOS Sonoma (14.0).

**Comment by nektro** [comment]
does this still reproduce for you? it appears to be working on my end in Bun 1.1.10 (you may need to run `bun upgrade`)

I'm on arm64 macOS 14.4.1 

<img width="543" alt="image" src="https://github.com/oven-sh/bun/assets/5464072/899925bc-03a4-40ed-9368-bd44e534d17d">

**Comment by dsincl12** [comment]
Seems to work now
