### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by IzaanAnwar** [oven-sh/bun#5731]
### What version of Bun is running?

1.0.2

### What platform is your computer?

wsl ubuntu 22

### What steps can reproduce the bug?

`import { Database } from "bun:sqlite";` 

when building the file with `bun build ./src/sqlite/index.ts --outdir dist`

### What is the expected behavior?

it should build the file

### What do you see instead?

bun build ./src/sqlite/index.ts --outdir dist 

error: Could not resolve: "bun:sqlite". Maybe you need to "bun install"?
import { Database } from "bun:sqlite";

**Comment by Electroid** [comment]
By default, `bun build` targets browsers. Try `bun build --target=bun`
