### ISSUE TITLE
concurrently issue 'exitCode: existCode ?? String(singnal)', line 78 in command.js

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#5734]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

npm add  concurrently
then `"bun --hot src/index.js" "browser-sync start --proxy 'localhost:3001' --files '**/*.css, **/*.html'"`

### What is the expected behavior?

Expected is running the browser-sync and bun --hot paraler and that make basically do autoupdate page when you change .html/.css

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/130649230/6f30a66e-fc72-4480-8b97-95caf7750a6d)

### Additional information

Don't know

**Comment by Electroid** [comment]
`npm-run-all` is going to run that in Node.js, which is also why this error is happening (because it is running in Node.js) Try `bun --bun run start`
