### ISSUE TITLE
Bun add doesn't respect install.exact from bunfig.toml

### ISSUE THREAD

**Issue by kvnwolf** [oven-sh/bun#5736]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

1. Create a bun project
2. Add `exact.true` to `bunfig.toml`

**bunfig.toml:**

```toml
[install]
exact = true
```

### What is the expected behavior?

Installing new dependencies (`bun add myDep`) adds the dependency with the exact version.	

### What do you see instead?

The dependency is being added with the caret range.

**Comment by present-g** [comment]
I have the same problem too, any news?

**Comment by casret** [comment]
I don't think bunfig.toml works at all.

**Comment by present-g** [comment]
@casret, part of bunfig.toml works, I use `print = "yarn"` and it works

```toml
[install.lockfile]
print = "yarn"
```

**Comment by Electroid** [comment]
Duplicate of #5647
