### ISSUE TITLE
Missing `isBinary` argument for the `ws` package

### ISSUE THREAD

**Issue by darrachequesne** [oven-sh/bun#5741]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.4.0-162-generic x86_64 x86_64

### What steps can reproduce the bug?

When using the `ws` package, there is currently no way to distinguish a plain-text message from a binary message (you always receive a Buffer):

```js
import WebSocket, { WebSocketServer } from 'ws';

const wss = new WebSocketServer({
  port: 3000
});

wss.on('connection', ws => {
  ws.on('message', (data, isBinary) => {
    console.log('received', data, isBinary);
  });
});

const ws = new WebSocket('ws://www.localhost:3000');

ws.on('open', function open() {
  ws.send('hello');
  ws.send(Buffer.from([1, 2, 3]));
});
```

### What is the expected behavior?

Output with Node.js:

```
$ node test.js
received <Buffer 68 65 6c 6c 6f> false
received <Buffer 01 02 03> true
```

### What do you see instead?

Output with bun:

```js
$ bun test.js
received Buffer(5) [ 104, 101, 108, 108, 111 ] undefined
received Buffer(3) [ 1, 2, 3 ] undefined
```

### Additional information

The `isBinary` flag was added in `ws@8.0.0` (July 2021): https://github.com/websockets/ws/releases/tag/8.0.0

This difference means that it's not possible to send some binary data when using Socket.IO and WebSocket. Plain-text packets and binary packets with HTTP long-polling are OK though.

Related:

- https://github.com/socketio/socket.io/discussions/4828
- https://github.com/oven-sh/bun/issues/2485
- https://github.com/oven-sh/bun/discussions/2111

**Comment by sapter** [comment]
Related to #4529, #4568, and many other open bugs. 
It seems to all stem from Bun overriding the `ws` package but only implementing its most elementary methods. See #3613

**Comment by creazy231** [comment]
I guess this issue is the reason of getting `parse error` on server side using socket.io with bun (?)

**Comment by darrachequesne** [comment]
@creazy231 yes indeed. Since `isBinary` is `undefined`, the server thinks the binary payload is a string, hence the parsing error.
