### ISSUE TITLE
Issue with --watch and --hot on windows 11 with WSL

### ISSUE THREAD

**Issue by prathameshpowar1910** [oven-sh/bun#5745]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

The bug is seen when using --watch or --hot with bun for starting or running a simple server using the Bun.serve method.

`bun --watch index.ts`
`bun --hot index.ts`

### What is the expected behavior?

Both these commands are expected to show the updated changes made to a file on refreshing the browser and restart the server but that is not happening.

### What do you see instead?

The problem is that the updated changes in the file are not seen on the browser even after refreshing and the server doesn't restart after refreshing the webpage.

https://github.com/oven-sh/bun/assets/91151201/60385231-12c8-44c3-9c61-d3193afa608a

**Comment by ericklarsen** [comment]
don't put your files in /mnt folder, just put it in your WSL's home directory, it should solve your problem

**Comment by prathameshpowar1910** [comment]
Ok will surely try that

**Comment by prathameshpowar1910** [comment]
Thanks for the solution it has solved my problem and the commands are working as expected
