### ISSUE TITLE
Lockfile is missing data

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5754]
Getting an `error parsing lockfile: Lockfile is missing data` when running `bun i` . Happens on a fresh install of Bun 1.0.2 with no prior lockfile. Seems to be specific to my set of packages.

`package.json`:

```json
{
  "name": "cluster-landing",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "lint": "eslint --ext .js,.jsx,.ts,.tsx src",
    "dev": "vite dev",
    "build": "vite build",
    "serve": "vite preview"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "autoprefixer": "^10.4.14",
    "bun-types": "^1.0.1",
    "eslint": "^8.48.0",
    "eslint-plugin-solid": "^0.13.0",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.2.2",
    "vite": "^4.4.9",
    "vite-plugin-solid": "^2.7.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/free-solid-svg-icons": "^6.4.2",
    "solid-fa": "^0.2.0",
    "solid-js": "^1.7.6"
  }
}
```

_Originally reported on Discord: [`Lockfile is missing data`](https://discord.com/channels/876711213126520882/1153742681604902974/1153742681604902974)_

**Comment by andriygm** [comment]
Looks like `eslint` package causes this -- removing it from devDependencies and rerunning `bun i` fixes it.

**Comment by Kanabanarama** [comment]
I get the same errors for these packages in bun 1.0.6:

`"@libsql/client": "^0.3.5"`
`"drizzle-kit": "^0.19.13"`
`"drizzle-orm": "^0.28.6"`

**Comment by stefpb** [comment]
it also happens on bun 1.0.9, when you have
`"capture-website": "3.2.0",`
inside your package.json

**Comment by Jarred-Sumner** [comment]
I'm pretty confident this has since been fixed

If you still run into this, please let us know.
