### ISSUE TITLE
SyntaxError: Import named 'LEVEL' not found

### ISSUE THREAD

**Issue by Kleywalker** [oven-sh/bun#5763]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```bash
bun init -y
bun add triple-beam
bun add -d @types/triple-beam
```

new file index.test.ts
```typescript
import { describe, expect, it } from "bun:test";
import { LEVEL } from "triple-beam";

describe("Test", () => {
  it("should have level debug", () => {
    const data = {
      [LEVEL]: "debug",
      level: "debug",
      message: "test",
    };
    expect(data[LEVEL]).toBe("debug");
  });
});
```

```bash
bun test
```

### What is the expected behavior?

The test should run.

### What do you see instead?

index.test.ts:
SyntaxError: Import named 'LEVEL' not found in module './node_modules/triple-beam/index.js'.

 0 pass
 1 fail
Ran 1 tests across 1 files. [14.00ms]

**Comment by paperclover** [comment]
duplicate of #4432
