### ISSUE TITLE
Issue with nested type resolution

### ISSUE THREAD

**Issue by isaacfink** [oven-sh/bun#5776]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I created two applications one is an express/trpc api and one is a sveltekit frontend, I am trying to use the client on the frontend and it is giving me the wrong types, it looks like an issue with types resolution

I am getting two errors, in one of the views I am getting an error like this

```
The inferred type of 'inviteUsers' cannot be named without a reference to '../../node_modules/drizzle-orm/query-builders/select.types'. This is likely not portable. A type annotation is necessary.ts(2742)
```
This is the function in question
```
export async function inviteUsers(data: z.infer<typeof sendInvitesValidator>) {
  const res = await db
    .insert(schema.invites)
    .values(
      data.map((invite) => ({
        email: invite.email,
        roles: invite.roles,
        accepted: false,
      }))
    )
    .returning({ id: schema.invites.id })
    .execute();

  return res;
}
```
Inside the frontend I am declaring the client like this
```
import { createTRPCProxyClient, httpBatchLink } from '@trpc/client';
import type { AppRouter } from '../../../api/trpc/server';

export const client = createTRPCProxyClient<AppRouter>({
	links: [
		httpBatchLink({
			url: 'http://127.0.0.1:4000/trpc',
		})
	]
});
```
And when I try to do this `client.assets.query` I am getting an error `Property 'query' does not exist on type` I double checked all of my `tsconfig.json` files and everything is set to true, It doesn't look like a bun issue but that is the only thing I can think of now

### What is the expected behavior?

The types should be inferred correctly

### Additional information

It may seem like it has nothing to do with bun, but I have seen it on deno as well and it was because of the typescript implementation

**Comment by paperclover** [comment]
bun doesn't implement typechecking, this is a TypeScript error, not an error in bun.

TS wants you to add an explicit return type to `inviteUsers`, like

```ts
export async function inviteUsers(data: ...): Promise<...> {
```
