### ISSUE TITLE
Bun run/test sometimes hangs/get stuck during startup

### ISSUE THREAD

**Issue by woehrl01** [oven-sh/bun#5782]
### What version of Bun is running?

v1.0.2 (37edd5a6)

### What platform is your computer?

Ubuntu 22.04.3 LTS (github runner: ubuntu-latest)

### What steps can reproduce the bug?

Sometimes the application just hangs and gets stuck during startup. We tried to drill it down in our application first, but it's definitely something of the runtime. We upgraded from 0.6.11 directly to 1.0.2 and didn't have that issue once in the previous version.

Please see the strace below, of the process during "stuck" state.

It's not reproducible every time, but it happens in our CI/CD on github at least once per day.

### What is the expected behavior?

bun run/test just works.

### What do you see instead?

It gets stuck during startup.

### Additional information

![image](https://github.com/oven-sh/bun/assets/2535856/9021b311-9892-4c21-8e58-35e19fdde17d)

**Comment by Jarred-Sumner** [comment]
Can you paste the test file this happens?

**Comment by woehrl01** [comment]
@Jarred-Sumner Unfortunately I don't have a test file I can share. But we are using typescript only. Without any bun plugins. 

An assumption would be that it's a Linux only problem, as I didn't had the issue locally on my Mac M1, yet.

**Comment by woehrl01** [comment]
I have now found out that it must be related to import. ~Still haven't found the exact root cause~, but it's definitely something which happens on linux ("ubuntu-latest"). 

It is caused by importing "@node-rs/xxhash" which loads a native rust module. Not sure if this is a bun issue, or an issue of the library. I have now switched to xxhash-wasm and I don't have that problem anymore.
