### ISSUE TITLE
Add npm-version support

### ISSUE THREAD

**Issue by sergeifilippov** [oven-sh/bun#5790]
### What is the problem this feature would solve?

Would follow `npm version {command}` workflow to bump version numbers. Handy for builds & publishing.

https://docs.npmjs.com/cli/v10/commands/npm-version

### What is the feature you are proposing to solve the problem?

Allow for npm-friendly way to bump version.

### What alternatives have you considered?

npm version

https://docs.npmjs.com/cli/v10/commands/npm-version

**Comment by Electroid** [comment]
Duplicate of #5291
