### ISSUE TITLE
Support `bun run --filter`

### ISSUE THREAD

**Issue by long-woo** [oven-sh/bun#5793]
### What is the problem this feature would solve?

This is a cool project, I’m about to try it out in my project, thanks！

I hope to support `--filter` similar to `pnpm`, which is quite practical in `workspace` type projects.

https://pnpm.io/filtering

![image](https://github.com/oven-sh/bun/assets/3394035/4777745a-0c6d-4092-8596-0ddd5723a63c)

### What is the feature you are proposing to solve the problem?

Select the package through it, such as:

```sh
# File path
bun add vue --filter ./apps/web

# The name value of the package.json file
bun add vue --filter @dev/web
```

**Comment by DanielHoffmann** [comment]
This feature is really nice if you have a big monorepo with lots of separate projects, installing only a subset of dependencies can help with making builds faster and artifacts smaller

**Comment by Electroid** [comment]
Related to #5207

We can support both.

**Comment by FlatMapIO** [comment]
If you don't have a need to wildcard package names, you can first use `bun run --cwd packages/abc build`

**Comment by angelhdzmultimedia** [comment]
> If you don't have a need to wildcard package names, you can first use `bun run --cwd packages/abc build`

Life saver thanks! 🔥🐰🍞☺️🤝

**Comment by annminn104** [comment]
> If you don't have a need to wildcard package names, you can first use `bun run --cwd packages/abc build`

Thanks!
I also encountered the same error if I needed to run multiple packages at once
and this is how I modified it

example with yarn: `yarn run build --filter=packages/**`

with bun: `bun run --cwd packages build`

**Comment by magiconair** [comment]
I have three http servers in separate subdirectories and when I want to run the `dev` script (`bun run index.ts`) on all of them with `bun --filter './src/*' dev` it hangs as follows. Any idea what is wrong here?

<img width="297" alt="image" src="https://github.com/oven-sh/bun/assets/229005/008f0ccd-1e5f-44de-ab8a-1a4cb0d25c15">

**Comment by magiconair** [comment]
Reproduce this as follows:
* create a `test/a/index.ts` with the simple web server from https://bun.sh/guides/http/simple
* create a `test/b/index.ts` with the simple web server from https://bun.sh/guides/http/simple and change the port to 3001
* create a `test/a/package.json` with `{"scripts":{"dev":"bun run index.ts"}}`
* create a `test/b/package.json` with `{"scripts":{"dev":"bun run index.ts"}}`
* run `cd test && bun --filter './*' dev`

Result:
<img width="331" alt="image" src="https://github.com/oven-sh/bun/assets/229005/ff41e07f-09e9-4625-ab9b-9767368f29dd">

**Comment by ennioVisco** [comment]
it would be cool to have this also for the `install` command, like in pnpm

**Comment by geongeorge** [comment]
Anybody else get this?

```
> bun --filter './app/*' dev    
error: Module not found "./app/*"


> bun --filter '*' build   
error: Script not found "*"
```

**Comment by Jokcy** [comment]
> Anybody else get this?
> 
> ```
> > bun --filter './app/*' dev    
> error: Module not found "./app/*"
> 
> 
> > bun --filter '*' build   
> error: Script not found "*"
> ```

Same here, always got `Script not found error`

**Comment by jocades** [comment]
> Anybody else get this?
> 
> ```
> > bun --filter './app/*' dev    
> error: Module not found "./app/*"
> 
> 
> > bun --filter '*' build   
> error: Script not found "*"
> ```

Make sure you are using the latest Bun version v1.1.10.
I was on v1.0.36 and had the same issue.
$ bun updgrade
