### ISSUE TITLE
Node incompatibility: TypeError: fetch() URL is invalid

### ISSUE THREAD

**Issue by pubkey** [oven-sh/bun#5798]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a `test.js` file with the following content:
```js
async function run() {
    const myBlob = new Blob(['foobar'], {
        type: 'text/plain'
    });
    const fetchUrl = URL.createObjectURL(myBlob);
    const arrayBuffer = await fetch(fetchUrl).then(res => res.arrayBuffer());
    console.dir(arrayBuffer);
}
run();
```

2. run the file with `bun test.js`

### What is the expected behavior?

It should run and transfrom the  blob object into an array buffer.
In node.js it works and logs an ArrayBuffer Object.

### What do you see instead?

```bash
1 | async function run() {
2 |     const myBlob = new Blob(['foobar'], {
3 |         type: 'text/plain'
4 |     });
5 |     const fetchUrl = URL.createObjectURL(myBlob);
6 |     const arrayBuffer = await fetch(fetchUrl).then(res => res.arrayBuffer());
                                  ^
TypeError: fetch() URL is invalid
 code: "ERR_INVALID_ARG_VALUE"

      at /home/xxx/test.js:6:30
      at run (/home/xxx/test.js:1:18)
      at /home/xxx/test.js:9:0


```

**Comment by Jarred-Sumner** [comment]
URL.createObjectURL is not implemented yet

**Comment by pubkey** [comment]
@Jarred-Sumner Thank you, I didnt know that. But shouldn't `URL.createObjectURL()` throw instead of the later `fetch()` call?

**Comment by Electroid** [comment]
We'll be tracking support for this here:
Duplicate of #3925
