### ISSUE TITLE
TypeError: PerfHooks.performance.eventLoopUtilization is not a function

### ISSUE THREAD

**Issue by yesil** [oven-sh/bun#5804]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 21.2.0 x86_64 i386

### What steps can reproduce the bug?

Start a basic server with Hapi library

```
import Hapi from "@hapi/hapi";

async function init() {
  const server = Hapi.server({
    port: 3000,
    host: "localhost",
  });

  server.route({
    method: "GET",
    path: "/test",
    handler: async (request, h) => {
      return h.response({ success: true }).type("application/json");
    }
  });

  await server.start();
  console.log("Server running on %s", server.info.uri);
}

init();
```

### What is the expected behavior?

The server starts

### What do you see instead?

```
TypeError: PerfHooks.performance.eventLoopUtilization is not a function. (In 'PerfHooks.performance.eventLoopUtilization()', 'PerfHooks.performance.eventLoopUtilization' is undefined)
      at new Heavy (/Users/ilyas/git/genai/node_modules/@hapi/heavy/lib/index.js:42:37)
      at new  (/Users/ilyas/git/genai/node_modules/@hapi/hapi/lib/core.js:122:21)
      at /Users/ilyas/git/genai/node_modules/@hapi/hapi/lib/server.js:22:17
      at /Users/ilyas/git/genai/src/server.js:9:17
      at init (/Users/ilyas/git/genai/src/server.js:4:19)
      at /Users/ilyas/git/genai/src/server.js:37:0
```

**Comment by tudemaha** [comment]
I have the same problem here. The problem also appears when I start the Hapi server.

Steps I've tried to make sure that's the Bun bug:
- Update Bun to the latest version (1.0.2)
- CommonJS method: create my Hapi project using npm (init and install Hapi framework) then start the project using Bun, but the same problem appears (the project run smoothly using Node.js)
- Module method: create my Hapi project using npm, then start the project using Bun, the same problem appears (the project also runs smoothly using Node.js)
- Create using TypeScript: create my Hapi project using npm, install the typescript, then compile the ts file into js using npx tsc. I run the js build from compiled ts using Bun, but the same problem appears (run smoothly using Node.js)

For more information, the system I use:
Bun version: 1.0.2
Platform: WSL Ubuntu 20.04 LTS on Windows 11 x86_64
Linux kernel:  5.15.90.1-microsoft-standard-WSL2

**Comment by Electroid** [comment]
Looks like we haven't implemented this Node.js API yet: https://nodejs.org/api/perf_hooks.html#performanceeventlooputilizationutilization1-utilization2

**Comment by afgallo** [comment]
Have just tested with bun `v1.0.7` and can confirm the issue still remains. I'd love to use bun to run my hapi projects!

**Comment by Akumzy** [comment]
@Electroid any update please

**Comment by MollsReis** [comment]
+1 I'm experiencing this as well (bun `v1.0.23`). Avoiding the issue for now by pinning Hapi to v20. Looking forward to this being solved
