### ISSUE TITLE
new URL("blob:https://example.com").origin should be https://example.com

### ISSUE THREAD

**Issue by fabiancook** [oven-sh/bun#5805]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Create the file `origin.js`:

```javascript
console.log(JSON.stringify(new URL("blob:https://example.com").origin));
```

Run

```shell
node origin.js
bun origin.js
```

### What is the expected behavior?

For `"https://example.com"` to be logged

```shell
$ node origin.js
"https://example.com"
$ bun origin.js
"https://example.com"
```

### What do you see instead?

```shell
$ node origin.js
"https://example.com"
$ bun origin.js
"null"
```

### Additional information

Chrome:

```
"https://example.com"
```

Safari:

```
"https://example.com"
```

Firefox:

```
"https://example.com/"
```

This behaviour is noted here: 

- https://developer.mozilla.org/en-US/docs/Web/API/URL/origin
- https://url.spec.whatwg.org/#origin
- https://url.spec.whatwg.org/#example-43b5cea5 

> The [origin](https://url.spec.whatwg.org/#concept-url-origin) of blob:https://whatwg.org/d0360e2f-caee-469f-9a2f-87d5b0456f6f is the [tuple origin](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-tuple) ("https", "whatwg.org", null, null).

**Comment by Electroid** [comment]
Thanks for flagging this down, we'll fix this.

**Comment by liz3** [comment]
i wanna look at this, sounds interesting!
