### ISSUE TITLE
bun-vscode doesn't respect breakpoints

### ISSUE THREAD

**Issue by sidoshi** [oven-sh/bun#5807]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 21.3.0 arm64 arm

### What steps can reproduce the bug?

I created a new empty project with bun --init.
In index.ts there's only only line with a console.log statement. I attached a breakpoint to that line and created a default launch.json for VSCode using the bun-vscode extension. When I launch the debug, the breakpoint is not respected but I do see the output of the console in the debug output.

### What is the expected behavior?

The breakpoint is respected

**Comment by sidoshi** [comment]
I cleaned up my VSCode extensions and it works now. Sorry for the false alarm.

**Comment by Makeshift** [comment]
@sidoshi Interestingly I'm also seeing this exact issue. Do you happen to know if any particular extensions were causing problems?

**Comment by DanielMcCord** [comment]
@Makeshift I have this exact issue too. For me it's a special case of #8282.

I'm still seeing it even on a fresh profile with no other installed extensions.

**Comment by strickc** [comment]
I was having this problem related to symlinks.  The file I was debugging has a `~` for my home directory.  I resolved it by inserting a `debugger` statement and then running `Bun: Debug file` again.  This time it popped up a new editor with the resolved path to the file and stopped at the `debugger` statement.  Now it seems to have cached this relationship and can use normal debug breakpoint dots on the original file and it pops up the symlink-resolved file when they are reached.
