### ISSUE TITLE
feat: add local tgz via `bun add local.tgz`

### ISSUE THREAD

**Issue by OrbisK** [oven-sh/bun#5812]
### What is the problem this feature would solve?

Currently you can't install local tgz packages (at least not that I know of).

### What is the feature you are proposing to solve the problem?

`bun add example.tgz`
`bun add ./example.tgz`

### What alternatives have you considered?

Current behavior:
`error: package "example.tgz" not found registry.npmjs.org/example.tgz 404`

**Comment by Electroid** [comment]
Fixed by #6118
