### ISSUE TITLE
Peer dependencies are not installed, even with a configured bunfig file

### ISSUE THREAD

**Issue by jeremylvln** [oven-sh/bun#5813]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.15.0-83-generic aarch64 aarch64

### What steps can reproduce the bug?

1. Create a package.json with a peer dependency
2. Create a bunfig.toml alongside the package.json with `[install] \n peer = true`
3. Run `bun i`
4. The package is not installed (not in the `bun i` summary, not in the `node_modules` folder)

### What is the expected behavior?

Have the package installed if the `bunfig.toml` is configured accordingly.

### What do you see instead?

The package is not installed.

### Additional information

This is a critical issue which could make my company move back to `yarn`. Our development workflow is totally paralyzed

**Comment by FreePhoenix888** [comment]
Related https://github.com/oven-sh/bun/issues/5567

**Comment by Electroid** [comment]
This was fixed in Bun v1.0.7. If you are still experiencing issues with `peerDependencies`, let us know and we'll re-open to investigate.
