### ISSUE TITLE
NextJS Turborepo bug

### ISSUE THREAD

**Issue by RobSchilderr** [oven-sh/bun#5814]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I had these errors when trying to run my [Turborepo starter project ](https://github.com/RobSchilderr/nextjs-native-starter/tree/bun) with Bun. If you go to the `bun` branch of that repo, you can see my changes and what I tried to achieve. You can also go back to the main branch and start over if you'd like.

```
er.development.js:6141:7)
next-web:build: Error: <Html> should not be imported outside of pages/_document.
next-web:build: Read more: https://nextjs.org/docs/messages/no-document-import-in-page
```

and
```
next-web:build: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
next-web:build: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
```

Steps to reproduce:

**1. Initial Setup:**
No package manager was set initially. Ran: `npx @turbo/codemod add-package-manager` and then `yarn global add @turbo/codemod`. This added a `packageManager` field to package.json.

**2. Switching to Bun:**
Updated package.json with: `"packageManager": "bun@1.0.2"`. Encountered a type error: `String does not match the pattern of "(npm|pnpm|yarn)@\d+\.\d+\.\d+(-.+)?".` This comes from the IDE so we can safely ignore for now.

**3. Cleaning Up:**
Removed `node_modules`, Ran `bun install`. Deleted yarn.lock and now have a `bun.lockb`.

**4. Building with Bun:**
Instead of yarn build, used `bun run turbo build`. Note: There's a difference in command syntax which caused a brief confusion.

**5. Result:**
The errors as shown above.

### What is the expected behavior?

Hoping to build the Turborepo with Bun.

### What do you see instead?

1. Prerendering Errors: There are errors occurring during the prerendering of several pages (/, /login, /register). Prerendering is a process where Next.js generates the HTML for a page at build time, which can help with performance and SEO. The specific error message is Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error.

2. NextRouter was not mounted: This error is occurring multiple times and suggests that the Next.js Router is being used outside of a component, or in a place where the React context provided by Next.js's <RouterProvider> is not available. The specific error message is Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted.

3. Build script exited with code 1 (SIGHUP): This indicates that the build script encountered an error and had to exit. The SIGHUP signal is often sent when a terminal window is closed, which can cause programs running in that terminal to exit.

4. Export encountered errors on following paths: This error indicates that Next.js encountered errors while trying to export certain pages as static HTML. The pages that had errors are listed after the error message.

### Additional information

You can easily just pull the `bun` branch of my repository [Nextjs Native starter](https://github.com/RobSchilderr/nextjs-native-starter/tree/bun)  and try it yourself.

**Comment by chenglou** [comment]
I don't have a clean repro, so this might be misleading, but installing the deps using yarn (while still running the scripts using bun) doesn't give `NextRouter was not mounted` for me

**Comment by RobSchilderr** [comment]
> I don't have a clean repro, so this might be misleading, but installing the deps using yarn (while still running the scripts using bun) doesn't give `NextRouter was not mounted` for me

You can go to the `bun` branch, or start a clean repo: 

Run: `npx create-supertokens-app@latest --manager=yarn

Pick a name for your app

Choose `Capacitor`

and then it first ran smooth! But later I ran in to a fatal error when doing `bun run turbo build` inside a `next-web` app. 

This is what I did with my migration from Yarn to Bun in Turborepo on MacBook M1 with Node v18:


1. **Initial Setup:**
   - No package manager was set initially.
   - Ran:
     ```bash
     npx @turbo/codemod add-package-manager
     yarn global add @turbo/codemod
     ```
   - This added a `packageManager` field to `package.json`.

2. **Switching to Bun:**
   - Updated `package.json` with:
     ```json
     "packageManager": "bun@1.0.2"
     ```
   - Encountered a type error:
     ```plaintext
     String does not match the pattern of "(npm|pnpm|yarn)@\d+\.\d+\.\d+(-.+)?".
     ```

3. **Cleaning Up:**
   - Removed `node_modules`.
   - Ran `bun install`.
   - Deleted `yarn.lock` and now have a `bun.lockb`.

4. **Building with Bun:**
   - Instead of `yarn build`, used `bun run build`.
   - Note: There's a difference in command syntax which caused a brief confusion.

5. **Build Issues:**
   - Initial build was successful.
   - On subsequent builds, encountered the following error: 
   
```

 Generating static pages (0/9) [    ]Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at p (/Users/robschilder/Documents/Development/capacitor-supertokens-nextjs-turborepo/apps/next-web/.next/server/chunks/632.js:1:14344)
```

For the branch, check: bun-attempt

**Comment by RobSchilderr** [comment]
Any idea why its not prerendering the page and saying NextRouter was not mounted? Its only when doing this with Bun and NextJS pages router.
