### ISSUE TITLE
Segmentation fault on Buffer.toString

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#5819]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.1.0-11-amd64 x86_64 unknown

### What steps can reproduce the bug?

- Create a simple typescript file:
```
echo "console.log(Buffer.from('ABC', 'utf-8').toString('utf-8'))" > dummy.ts
```
- Run
```
bun run dummy.ts
```

### What is the expected behavior?

Printing `ABC` on the console

### What do you see instead?

`Segmentation fault`

### Additional information

Works with ts-node
```
npx ts-node dummy.ts
```

**Comment by ghost** [comment]
Maybe some hints:
- Did a test on another machine and it works as expected
`1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49`
`Linux 6.1.0-12-amd64 x86_64 unknown`
- Updated the machine with the segmentation fault to `Linux 6.1.0-12-amd64 x86_64 unknown` but still get the segmentation fault
- Both machines are Debian 12 btw.

Edit:
- There is one difference: The machine segfaulting is used as remote development machine on a server and does not have any desktop environment installed.

Hope that helps

**Comment by ghost** [comment]
Hey.

I think I found the issue.
* The machine is running as a VM on Proxmox VE 8.0
* The default cpu type is 'kvm64'
* Looking at the chapter 'QEMU CPU Types' on [this page](https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines#qm_virtual_machines_settings) some cpu features are not passed through to the guest system
* I changed the cpu type to `x86-64-v2` which enables - according to the documentation - the cpu features `+cx16, +lahf-lm, +popcnt, +pni, +sse4.1, +sse4.2, +ssse3`

After that change, the segmentation fault is gone.

**Comment by mio-moto** [comment]
Guess I'm out of luck then, I'm on some dirt-cheap VM right now and can't control the CPU features passed down:

```
Flags:                           fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology cpuid ts c_known_freq pni cx16 x2apic hypervisor lahf_lm pti
```

**Comment by Jarred-Sumner** [comment]
Duplicate of #3312 

Please use the baseline build of Bun and see more details in #3312. This isn't a bug in Buffer.
