### ISSUE TITLE
possible to create golang bun api to use bun with golang

### ISSUE THREAD

**Issue by passerbyo** [oven-sh/bun#583]
### What is the problem this feature will solve?

possible to create golang bun api to use bun with golang

### What is the feature you are proposing to solve the problem?

possible to create golang bun api to use bun with golang

### What alternatives have you considered?

possible to create golang bun api to use bun with golang

**Comment by boehs** [comment]
What? You want to transpile from go?

Tip: The questions in the issue are designed to help you get more specific, NOT paste the same sentence 3 times

*What* do you want to achieved with a "bun api for golang"*?

**Comment by yanislav-igonin** [comment]
@boehs thats easy, he just want to be _possible to create golang bun api to use bun with golang_

**Comment by vrmiguel** [comment]
I guess he wants a Bun version of something like [deno-core](https://github.com/denoland/deno/blob/main/core/examples/http_bench_json_ops.rs)

**Comment by Electroid** [comment]
Thanks for submitting a feature request! Unfortunately, this isn't something we're going to consider right now, at least officially.
