### ISSUE TITLE
Incorrect spelling in bun.sh landing page

### ISSUE THREAD

**Issue by ravi-sankarp** [oven-sh/bun#584]
### Affected URL(s)

packages/bun-landing/page.tsx

### Description of the problem

In line 543 the word built-in is spelled incorrectly as 'builtin'
I don't know whether it was kept on intentionally or it was a mistake.
Anyways I just noticed it so just reporting.
And wishing good luck for the foreseeable future.

**Comment by boehs** [comment]
Thanks, there was inconsistent usage of `built-in` and `builtin`

**Comment by ravi-sankarp** [comment]
So when will it be implemented in the live website?
I saw that it was not yet updated.
![image](https://user-images.githubusercontent.com/105059007/178403887-0adca132-e813-4c0f-a0b8-8ec511e9fbee.png)
