### ISSUE TITLE
DOM testing recommendations result in `TypeError: Attempted to assign to readonly property.` when setting global `ReadableStream`

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#5845]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Follow the exact steps from https://bun.sh/docs/test/dom#happy-dom

This is reproducible in a repo:

```shell
git clone https://github.com/lgarron/bun-happy-dom-TypeError && cd bun-happy-dom-TypeError
bun test
```

### What is the expected behavior?

`happy-dom` global registration is successful.

### What do you see instead?

```
bun test v1.0.0 (822a00c4)

dom.test.ts:
16 |         this.registered = {};
17 |         for (const key of Object.keys(window)) {
18 |             if (global[key] !== window[key] && !IGNORE_LIST.includes(key)) {
19 |                 this.registered[key] =
20 |                     global[key] !== window[key] && global[key] !== undefined ? global[key] : null;
21 |                 global[key] = typeof window[key] === 'function' ? window[key].bind(global) : window[key];
                    ^
TypeError: Attempted to assign to readonly property.
      at register (/Users/lgarron/Code/git/github.com/lgarron/bun-happy-dom-TypeError/node_modules/@happy-dom/global-registrator/lib/GlobalRegistrator.js:21:16)
      at /Users/lgarron/Code/git/github.com/lgarron/bun-happy-dom-TypeError/happydom.ts:3:0

 0 pass
 1 fail
Ran 1 tests across 1 files. [68.00ms]
make: *** [repro] Error 1
bun test
```

This seems to happen for the key `ReadableStream`. The following may be a smaller repro:

```ts
globalThis.ReadableStream = 4;
```

### Additional information

`happy-dom` should really be using [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis). But in any case, if this is the recommended approach for DOM testing with `bun` then it should probably not error out of the box.

**Comment by lgarron** [comment]
> This seems to happen for the key `ReadableStream`. The following may be a smaller repro:
> 
> ```ts
> globalThis.ReadableStream = 4;
> ```

Yeah, I think this is it. `node` and browsers allow this.

**Comment by dylan-conway** [comment]
Could you try with v1.0.2? I think this should be fixed

**Comment by lgarron** [comment]
> Could you try with v1.0.2? I think this should be fixed

Ah, excellent, thanks! 🤩
