### ISSUE TITLE
`happy-dom`'s global `EventTarget` registration can't be subclassed in `bun`

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#5847]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Install `@happy-dom/global-registrator` and try to run the following:

```ts
import { GlobalRegistrator } from "@happy-dom/global-registrator";
GlobalRegistrator.register();

class Foo extends EventTarget {}
```

### What is the expected behavior?

No error

### What do you see instead?

```
1 | import { GlobalRegistrator } from "@happy-dom/global-registrator";
2 | GlobalRegistrator.register();
3 | 
4 | class Foo extends EventTarget {}
   ^
TypeError: The value of the superclass's prototype property is not an object or null.
      at /Users/lgarron/Code/git/github.com/cubing/cubing.js/src/test/bun/happy-dom.ts:4:0
```

It seems that the following is a sufficient workaround:

```ts
(globalThis as any).EventTarget = (await import("happy-dom")).EventTarget;
```

**Comment by paperclover** [comment]
i get the same error when running this in node

happy dom is doing the following:

`global.EventTarget = TheirEventTarget.bind(window)`

**Comment by croqaz** [comment]
Also this, in happy-dom repo: https://github.com/capricorn86/happy-dom/issues/1085
