### ISSUE TITLE
ipaddr: the address has neither IPv6 nor IPv4 format

### ISSUE THREAD

**Issue by krassx** [oven-sh/bun#5850]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create new Angular 16.x web application and try starting it with bun instead of node
2. During the spawning the local web server, the unhandled exception is raised with the reference for more details in the local file
3. Open the file and see the stack trace there.

### What is the expected behavior?

Local web server should start with no issues.

### What do you see instead?

Local web server launch fails with exception.

### Additional information

The stack trace for the exception is the following:

```
[error] Error: ipaddr: the address has neither IPv6 nor IPv4 format
    at <anonymous> (/Users/build/Projects/viewer/node_modules/ipaddr.js/lib/ipaddr.js:934:11)
    at logStatus (/Users/build/Projects/viewer/node_modules/webpack-dev-server/lib/Server.js:2883:31)
    at <anonymous> (/Users/build/Projects/viewer/node_modules/webpack-dev-server/lib/Server.js:3393:19)
    at processTicksAndRejections (:55:39)
```

(Btw, another issue here is that the line numbers are incorrect and point to unrelated lines, though they are somewhat close to the actual ones).

After digging into it a bit, it seems that bun and node return different values HTTP/HTTPS server address() method call.

Here is the code snippet from `Server.js` where the original data is fetched
```javascript
const { address, port } =
        /** @type {import("net").AddressInfo} */
        (
          /** @type {import("http").Server} */
          (this.server).address()
        );
```

It is later passed to the `ipaddr` in the following way:

```javascript
const parsedIP = ipaddr.parse(address);
```

So, when this code is run in node, address contains "127.0.0.1", whereas bun returns "localhost". `ipaddr` does not expect address to be aliased this way and fails.

**Comment by JohnDDuncanIII** [comment]
`bun --bun run dev` fails on our company repo for the same reason

![Screenshot 2023-10-04 at 12 25 11 AM](https://github.com/oven-sh/bun/assets/9257785/3c800328-7660-46fe-9c04-fd2c57d24065)
