### ISSUE TITLE
Bun 1.0.3 (canary) - Breaks sharp again!

### ISSUE THREAD

**Issue by JawadAhbab** [oven-sh/bun#5851]
### What version of Bun is running?

1.0.3+01d2cb5d98c6e90507d1dfba962276cf2edf9ad7

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
import fs from 'fs'
import sharp from 'sharp'

const preimg = fs.readFileSync('src/image.jpg')
const newimg = await sharp(preimg).blur(25).resize(400).jpeg().toBuffer()

fs.writeFileSync('src/newimg.jpg', newimg)
```

### What is the expected behavior?

Current Version `Bun 1.0.2` Is smoothly working without any issue. But when I upgraded to canary (1.0.3) It is giving this error -

```
(process:36182): GLib-GObject-CRITICAL **: 14:04:08.849: value "nan" of type 'gdouble' is invalid or out of range for property 'angle' of type 'gdouble'
error: rotate: parameter angle not set
```

**Comment by Jarred-Sumner** [comment]
We need to add integration tests for sharp

**Comment by Jarred-Sumner** [comment]
https://github.com/oven-sh/bun/issues/5852
