### ISSUE TITLE
Do not include the whole bun in the binary during the compilation (reduce the size of the executable)

### ISSUE THREAD

**Issue by HironTez** [oven-sh/bun#5854]
### What is the problem this feature would solve?

High memory and RAM usage

### What is the feature you are proposing to solve the problem?

Reduce the code included to the binary

### What alternatives have you considered?

I was comparing compiled Typescript with Rust and I was very surprised that the Typescript binary is actually faster than Rust. Maybe my tests didn’t cover all aspects, and Rust is still faster, but it’s the way to go. The main difference I noticed was in the binary size. Bun creates a 91MB binary just to log “Hello World!”. I’m sure it can be improved. Sure you were already thinking about that, so I created this issue just to track the progress.

**Comment by Jarred-Sumner** [comment]
You can use `bun build --target=bun` if you want to build targeting Bun without embedding the Bun executable

The purpose of `bun build --compile` is for standalone executables that can be used when Bun is not available.

**Comment by HironTez** [comment]
Hi @Jarred-Sumner! That's not quite what i meant. I mean a binary with the embedded Bun executable, but only with the parts that are necessary to run the code. I don't think that all the 91MB are needed to log the message in the console.

**Comment by HananoshikaYomaru** [comment]
Just random come across this issue. 

does this mean treeshaking the zig code? I don't think it is possible for bun at this point. It would be a fascinating feature though.
