### ISSUE TITLE
lockfile had changes, but lockfile is frozen

### ISSUE THREAD

**Issue by jeremylvln** [oven-sh/bun#5858]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.15.0-83-generic aarch64 aarch64

### What steps can reproduce the bug?

1. `bun init`
2. `bun i express` (or anything else)
3. `rm -Rf node_modules`
4. `bun i --frozen-lockfile`

Steps 3 and 4 are the context of a CI.

### What is the expected behavior?

It should install the dependencies.

### What do you see instead?

```
bun install v1.0.2 (37edd5a6)
error: lockfile had changes, but lockfile is frozen
```

Another empty `bun i` fixes the issues and somewhat updates the lockfile.

**Comment by Electroid** [comment]
This should be fixed in Bun v1.0.4. If you want to try it now, you can run: `bun upgrade --canary`
