### ISSUE TITLE
Bun.serve crashes with seg fault when decoding certain binary data as JSON

### ISSUE THREAD

**Issue by PhilBladen** [oven-sh/bun#5859]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.4.0-162-generic x86_64 unknown (**oven/bun** Docker image)

### What steps can reproduce the bug?

Run the following using Bun or Node:
```js
Bun.serve({
    port: 8080,
    async fetch(req) {
        try {
            const data = await req.json();
        } catch (e) {
            console.log("Bad JSON");
        }
        return new Response(null, {});
    }
});
```

Send a HTTP packet to this server containing any non-printable ASCII character such as hex symbol `0xFD`.

### What is the expected behavior?

The server should handle the request, fail to parse the JSON and print "Bad JSON" to the console.

### What do you see instead?

Server immediately exits with `Segmentation fault (core dumped)`

### Additional information

This bug makes all Bun.serve servers attempting to interpret JSON requests vulnerable to malicious attacks causing the server to spontaneously crash.

**Comment by PhilBladen** [comment]
This also occurs in Bun 1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49 and 1.0.3+28f345346650dc94330b4a2cdcd1297df2916a39

**Comment by Jarred-Sumner** [comment]
Thank you for this. Will have a fix shortly.
