### ISSUE TITLE
Can node run code generated by the bun build command?

### ISSUE THREAD

**Issue by Viskeyy** [oven-sh/bun#5864]
### What version of Bun is running?

1.0.2

### What platform is your computer?

x64

### What steps can reproduce the bug?

1. publish a package using build command on npmjs
	* build command is this
	![image](https://github.com/oven-sh/bun/assets/50070461/1034725d-7e74-456e-82c6-fc4feac04e0d)

2. bun install the package in another project
3. deploying the project on vercel

### What is the expected behavior?

the project can be deployed on vercel

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/50070461/cd355b44-0322-4f6e-8165-4b973bf08538)

### Additional information

The node version on both the local and Vercel servers is 18

**Comment by Electroid** [comment]
To run the code in Node.js, you'll need to set the target to `node` instead of `browser`.

**Comment by Viskeyy** [comment]
My package has only a few js files, so I only use `bun init` to initialize it. The package will only run in the browser, so what should the `target` be in this case? 

When using `npm run build`, it works fine.

My project is using React, but it was created by `npx create-react-app`.

After I changed the target locally, I ran `bun build` and got the same code as before I changed the target.

**Comment by Viskeyy** [comment]
When target is set to node, no mjs file is generated.
![image](https://github.com/oven-sh/bun/assets/50070461/d95dc80d-521d-4fbb-aa62-1d51a08511f5)
![image](https://github.com/oven-sh/bun/assets/50070461/ae923803-d53b-4fb9-a9b5-228871fec7f2)
