### ISSUE TITLE
Express believes `protocol=http` when HTTPS request

### ISSUE THREAD

**Issue by Foorack** [oven-sh/bun#5867]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

I made a tiny single-file repo which consistently reproduces the bug on multiple machines.

### Setup:

1. git clone https://github.com/Foorack/bun-proto-test
2. cd bun-proto-test
3. bun install

### Verify it works with Node

`node index.js`

Go to `https://localhost:4343` and see it says `https`.

> OK : https : Node

### Verify it is broken in Bun

`bun run index.js`

Go to `https://localhost:4343` and see it says `http`.

> OK : http : Bun

### What is the expected behavior?

It is supposed to print "https" when running with Bun, becasue the request is HTTPS. It works in Node.

### What do you see instead?

I see "http" (req.protocol = http)

### Additional information

This causes `express-session` to not send secure cookies, which completely breaks logins in all systems. Had to revert to Node. 

This is the last bug blocking migration to Bun. :slightly_smiling_face:

**Comment by liz3** [comment]
on this rn

**Comment by Foorack** [comment]
@liz3  I did more digging and I believe this is because bun's implementation of `net.Socket` does not implement `socket.encrypted`.

Node: `console.log(req.socket.encrypted)` = true
Bun: `console.log(req.socket.encrypted)` = undefined

**Comment by liz3** [comment]
correct

**Comment by Foorack** [comment]
@liz3  Thanks for looking into this. I went back into the archives, and this seems to be a magic undocumented bool Node sets on TLS sockets. Major libraries like ExpressJS then depend on this undocumented bool, and has been for the last 10 years.

Breifly removed and reintroduced: https://github.com/nodejs/node-v0.x-archive/pull/6737/files

Discussion: https://github.com/nodejs/node-v0.x-archive/issues/6735

Related to https://github.com/expressjs/express/issues/1864
