### ISSUE TITLE
`bun install` does not respect package aliases in subdependencies

### ISSUE THREAD

**Issue by JoeyEamigh** [oven-sh/bun#5868]
### What version of Bun is running?

1.0.3+0b4a34bbd6e07096212774759ca6e8a7f3922e46

### What platform is your computer?

Linux 6.5.3-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. `bun create strapi-app bunstrapitest --quickstart`
2. once server starts, press control-c
3. `cd bunstrapitest`
4. `rm -rf node_modules yarn.lock .cache build`
5. `bun install`
6. `bun run build`

### What is the expected behavior?

`@strapi/admin` is a dependency of `@strapi/strapi`. `@strapi/admin` has a dependency called `codemirror`. Strapi relies on both `codemirror` 5 and 6 in their application, so they have an alias in the `@strapi/admin` `package.json` to install `npm:codemirror@^5.x.x` as the aliased module `codemirror5`.

### What do you see instead?

when running `yarn install`, the `codemirror5` directory is present in `node_modules`. when running `bun install`, only the `codemirror` directory is available, and has version 6 installed.

### Additional information

a workaround for this and similar issues is to add the alias to your own `package.json`, which bun will properly respect. in this example, adding `"codemirror5": "npm:codemirror@^5.65.11"` as a dependency to my `package.json` allows Strapi to build successfully.

**Comment by VrTech** [comment]
This also has an error when doing all this in docker.
I will not process ts file. Still finding the .js file. 

`ERROR: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1
------
 > [build 8/8] RUN bun run build:
67.51 17 |   } catch (error) {
67.51 18 |     throw new Error(`Could not load js config file ${file}: ${error.message}`);
67.51               ^
67.51 error: Could not load js config file /opt/app/dist/config/env/production/plugins.js: Cannot find module "/opt/app/dist/config/env/production/plugins.js" from "/opt/node_modules/@strapi/utils/dist/import-default.js"
67.51       at loadJsFile (/opt/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:10)
67.51       at loadFile (/opt/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:13)
67.51       at /opt/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-user-plugins-config.js:31:27
67.51       at processTicksAndRejections (:55:76)
67.51 
67.60 error: script "build" exited with code 1 (SIGHUP)`

**Comment by JoeyEamigh** [comment]
this appears to be fixed!
