### ISSUE TITLE
bun update always change lockb file

### ISSUE THREAD

**Issue by CGQAQ** [oven-sh/bun#5888]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux C20230424168060 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What steps can reproduce the bug?

```console
mkdir empty
cd empty
bun add webpack
bun update
cp bun.lockb bun.lockb.old
bun update
vimdiff  <(xxd bun.lockb) <(xxd bun.lockb.old)
```

### What is the expected behavior?

no diff

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/15936231/45d61046-e640-49d4-ab60-68882afb2e53)

**Comment by mattbdc** [comment]
bun update followed by bun update --save also doesn't touch package.json, I think it should right? npm update followed by npm update --save does.

**Comment by CGQAQ** [comment]
This issue is not related to `package.json` at all, what I'm saying is lockfile
