### ISSUE TITLE
bun test support .only

### ISSUE THREAD

**Issue by Simon-He95** [oven-sh/bun#5893]
### What is the problem this feature would solve?

import { describe, expect, it } from 'vitest'

describe.only & it.only

I think vitest’s .only design is very good, I hope bun also has such a function.

### What is the feature you are proposing to solve the problem?

The special situation of a certain function requires separate testing to debug

**Comment by Electroid** [comment]
Hi, `bun test` does support `test.only` and `describe.only`.

Run your tests with: `bun test --only`

**Comment by Simon-He95** [comment]
Can `bun test --only` specify a specific describe or it in the file?
I don’t think he can control a certain test item so accurately.

**Comment by Electroid** [comment]
Here's how it would work:

```js
import { test } from "bun:test";

test("test 1", () => console.log(1));
test.only("test 2", () => console.log(2));
```

If you run `bun test`, it will output 1 & 2.
If you run `bun test --only`, it will only output 2.

**Comment by Simon-He95** [comment]
wow， Thank you for your help
