### ISSUE TITLE
`Bun.spawn` event loop bug

### ISSUE THREAD

**Issue by Autumnlight02** [oven-sh/bun#5895]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.3.12-100.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

```
const proc = Bun.spawn(["echo", "hello"]);

await proc.exited;
console.log("works");

async function test() {
  const proc = Bun.spawn(["echo", "hello"]);

  // bun process exited fails when inside of an async function
  await proc.exited;
  console.log("fails");
}
test();
// need to do await test() to work
```
run this, it will console log works but not fails

### What is the expected behavior?

that bun detects subprocesses and awaits em

### What do you see instead?

just straight exiting

### Additional information

![image](https://github.com/oven-sh/bun/assets/68244453/f7530953-8dc7-40b4-9a93-dd2f0aa15d70)
![image](https://github.com/oven-sh/bun/assets/68244453/bd991b9a-e71b-4e20-bb8c-b3c14fcbf914)

**Comment by Jarred-Sumner** [comment]
This was fixed in canary
