### ISSUE TITLE
Segfault when passing jest.fn into another jest.fn

### ISSUE THREAD

**Issue by ivanbatic** [oven-sh/bun#5900]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

The following test code passes with Node & Jest, but segfaults when it goes through Bun.

```ts
// segfault.test.ts
describe('segfault', () => {
  function greet(fn = jest.fn(() => true)) {
    return jest.fn(fn)
  }

  it('faults', () => {
    expect(greet()()).toBe(true)
  })
})

// bun test segfault
```

### What is the expected behavior?

Test passes with no problems

```bash
tests/__bun/segfault.test.ts
  segfault
    ✓ faults (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.598 s
Ran all test suites matching /segfault/i.
```

### What do you see instead?

```sh
tests/__bun/segfault.test.ts:
[1]    62079 segmentation fault  bun test segfault
```

### Additional information

The issue seems to happen when a `jest.fn()` is passed into another `jest.fn()`.
The minimal scenario is
```ts
const funcA = jest.fn()
const funcB = jest.fn(funcA)
```

**Comment by Electroid** [comment]
Nice catch, we'll fix this.
