### ISSUE TITLE
new URL("file:///var/1").origin could be file://

### ISSUE THREAD

**Issue by fabiancook** [oven-sh/bun#5904]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Create the file `origin.js`:

```javascript
console.log(JSON.stringify(new URL("file:///var/1").origin));
```

Run

```shell
node origin.js
bun origin.js
```

### What is the expected behavior?

For `"file://"` to be logged

```shell
$ node origin.js
"null"
$ bun origin.js
"file://"
```

Chrome:

```
"file://"
```

Safari:

```
"file://"
```

Firefox:

```
"null"
```

### What do you see instead?

```shell
$ node origin.js
"null"
$ bun origin.js
"null"
```

### Additional information

Do we want this behaviour to be the same or different from node or browsers is the question here. 

This bug was created specifically for the [comment here in this PR](https://github.com/oven-sh/bun/pull/5825#issuecomment-1728441164)

This bug can either be closed, or left open to be resolved 

Reason I am opening this as a bug, as I would _feel_ like it would be a bug if `new URL("blob:file:///var/1").origin` was `"file://"` but `new URL("file:///var/1").origin` wasn't 

Plus, it was mentioned by @liz3 that they could take it on, but maybe as a different issue, as per the PR comments.

**Comment by skaschimer** [comment]
trying same steps on WSL. I just installed bun this morning. created the same file, ran the same commands.
node origin.js -> "null"
bun origin.js -> "null"

Linux version 5.15.90.4-microsoft-standard-WSL2 (root@4b885f886b45) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Tue Jul 18 21:28:32 UTC 2023

**Comment by cyfung1031** [comment]
I think for API discrepancy, just follow node.js which is `"null"` for `file:///abc/def/123.txt`

This bug shall be invalid.

**Comment by nektro** [comment]
Going to close this for now since Bun matches the behavior of Node and Deno. If OpenJS decides that we should change this behavior in the future we can revisit it.
