### ISSUE TITLE
TypeError on create react-app

### ISSUE THREAD

**Issue by HotelSierraWhiskey** [oven-sh/bun#5908]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 6.1.0-10-amd64 x86_64 unknown

### What steps can reproduce the bug?

`bun create react-app <appname>` 

also

`bunx create-react-app <appname>`

### What is the expected behavior?

I expect to create a new react project

### What do you see instead?

```
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...


Aborting installation.
Unexpected error. Please report it as a bug:
610 |   }
611 |   get stdio() {
612 |     return this.#stdioObject ??= this.#createStdioObject();
613 |   }
614 | 
615 |   spawn(options) {
                 ^
TypeError: Executable not found in $PATH: "npm"
 code: "ERR_INVALID_ARG_TYPE"

      at spawn (node:child_process:615:14)
      at node:child_process:2:40
      at spawn (/tmp/create-react-app@latest--bunx/node_modules/cross-spawn/index.js:12:20)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:383:18
      at new Promise (:1:20)
      at install (/tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:334:9)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:461:15
      at processTicksAndRejections (:55:76)

...

error: "create-react-app" exited with code 1 (SIGHUP)
```

### Additional information

I'm very new to bun and JS development in general, so if I've missing something obvious forgive me, I was prompted by Bun's internal error handling to report this bug.

**Comment by Electroid** [comment]
Hi, thanks for reporting an issue! Since you don't have `npm` installed, you can try with `bunx --bun create-react-app`. `--bun` will tell Bun to find scripts that use "node" or "npm" to use "bun" instead.
