### ISSUE TITLE
FFI Segfaults should throw, not end the process

### ISSUE THREAD

**Issue by Pandapip1** [oven-sh/bun#5910]
### What is the problem this feature would solve?

When an FFI function segfaults, all you get is a message printed to `STDERR` that says `Segmentation fault`. That's not very helpful!

```shell
gavin@GAVIN-IDEAPAD-5A75N8AU:/mnt/c/Users/gavin/source/repos/bun-fuse$ bun index.ts --help
Segmentation fault
```

### What is the feature you are proposing to solve the problem?

If an FFI call results in a segfault, instead of the regular segfault behaviour, an exception should be thrown that can be caught and results in a stack trace. (this is a manually-edited stack trace; I haven't actually implemented this)

```shell
gavin@GAVIN-IDEAPAD-5A75N8AU:/mnt/c/Users/gavin/source/repos/bun-fuse$ bun index.ts --help
111 | );
112 | fuseArgs.writeInt32LE(argv.length, 0);
113 | fuseArgs.writeBigUInt64LE(BigInt(argvPtr), 4);
114 | const fuseArgsPtr = ptr(fuseArgs);
115 | 
116 | if (fuse_opt_parse(fuseArgsPtr, optionsPtr, optionsSpec, null) == -1) {
          ^
error: Segmentation fault
      at /mnt/c/Users/gavin/source/repos/bun-fuse/index.ts:116:6
      at processTicksAndRejections (:1:2602)
```

This should be possible on Linux at least. Segmentation faults happen with the `SIGSEGV` signal.

**Comment by evanwashere** [comment]
implementing this requires overwriting the registered segfault handler and complex unwinding logic that affects every ffi function, even if it doesn't segfault. this brings more cons than unsafe benefits (recovering from segfault 0_o)

your c function should return error codes and check for nulls and similar, so it doesn't segfault

**Comment by Pandapip1** [comment]
Okay, at least a stack trace to be able to know what FFI call resulted in the segfault would be helpful.

**Comment by evanwashere** [comment]
that would still require all complex unwinding logic and overwriting signal handler to figure that out. instead you should rely on code that avoids causing segfaults and debuggers like lldb

**Comment by Pandapip1** [comment]
I was trying to interface with libfuse when I submitted this feature request; it's not really possible to rely on something else.
