### ISSUE TITLE
[`bun-types`] Bun `1.0.3` breaks `describe.each` and `test.each` for arrays of objects

### ISSUE THREAD

**Issue by mProjectsCode** [oven-sh/bun#5913]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Write a test like this 
```ts
describe.each([
	{
		foo: 'bar',
	},
])('test', obj => {});
```

### What is the expected behavior?

There should be no type error and `obj` in the test callback should have the same type as the object in the `each` array.

### What do you see instead?

A type error
![image](https://github.com/oven-sh/bun/assets/61602848/0b5e35de-4735-42b7-9593-5724c110e12d)

### Additional information

This bug seems to have been introduced by https://github.com/oven-sh/bun/pull/5838.

**Comment by Jarred-Sumner** [comment]
Is this a typescript issue or a runtime issue? It reads like a typescript types issue

**Comment by mProjectsCode** [comment]
yeah, it is just the typing that is broken

**Comment by colinhacks** [comment]
I just pushed some changes that fix this, it'll land in `bun-types@canary` shortly
