### ISSUE TITLE
`await fs.promise.handler()` shoud return a `FileHandle`

### ISSUE THREAD

**Issue by yukulele** [oven-sh/bun#5918]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.0-58-generic x86_64 x86_64

### What steps can reproduce the bug?

```typescript
import {promises as fs} from 'node:fs'
const buffer = Buffer.allocUnsafe(10)
const file = await fs.open('file.txt')
await file.read(buffer, 0, 10, 5)
console.log(buffer.toString('utf-8'))
```

### What is the expected behavior?

`file` should be a `FileHandle` according to the [node documentation](https://nodejs.org/dist/latest-v20.x/docs/api/fs.html#fspromisesopenpath-flags-mode)

### What do you see instead?

`file` is a `number` with bun

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/8141
