### ISSUE TITLE
`bun install` output deleting some error output

### ISSUE THREAD

**Issue by joeyparis** [oven-sh/bun#592]
### Version

0.1.3

### Platform

Darwin XXXXXXX.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run `bun install` on an existing JS project. Occurs coming from both `npm` and `yarn`

### How often does it reproduce? Is there a required condition?

Errors need to be output during installation

### What is the expected behavior?

`bun install` doesn't delete output

### What do you see instead?

Unfortunately, a gif explains this issue's behavior much better than copied output.

![Undesired output](https://media.giphy.com/media/5Fi8m0SMKHEJM0FQ2F/giphy.gif)

**Comment by Electroid** [comment]
Hi @joeyparis, thanks for reporting this issue. `bun install` has gone through a lot of changes since you found this bug. If you have a moment, do you mind running: `bun upgrade`, then trying again if you run into this problem?

**Comment by joeyparis** [comment]
Hey @Electroid! I just ran `bun upgrade` followed by `bun install` and although I am having some other issues (probably due to my own project) the error output is no longer being deleted so I think it is safe to close this issue as fixed!
