### ISSUE TITLE
Cannot do `bun add ...` when in a workspace subfolder

### ISSUE THREAD

**Issue by firtoz** [oven-sh/bun#5926]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a workspace with package.json
```json
{
  "name": "bun-test",
  "module": "index.ts",
  "type": "module",
  "workspaces": [
    "packages/*"
  ],
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```
packages/a/package.json
```json
{
  "name": "a",
  "module": "index.ts",
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "b": "workspace:*"
  },
  "type": "module"
}
```
packages/b/package.json
```json
{
  "name": "b",
  "module": "index.ts",
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "type": "module"
}
```

See that a depends on b

`bun install` on root, works fine

go to packages/a

bun add zod

it explodes with:
```txt
 bun add zod
bun add v1.0.3 (25e69c71)


error: workspace dependency "b" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

### What is the expected behavior?

zod is installed into a

### What do you see instead?

```txt
bun add zod
bun add v1.0.3 (25e69c71)


error: workspace dependency "b" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

### Additional information

Also couldn't get `bun add b` to work within `a` even though documentation seems to say that's possible, it just gets some other `b` package instead.

**Comment by A-D-E-A** [comment]
Same. I saw that replacing the dependency with "workspace:../b" fixes the problem, but only when in this specific dir. So it's possible to toggle between that and the normal "workspace:*" for each situation, but it's very inconvenient.

**Comment by bconnorwhite** [comment]
Tried cloning the [example repo](https://github.com/colinhacks/bun-workspaces) and running `bun install` in the root.

When specifying a version for a workspace package (`"@oven-sh/a": "0.0.1"`), bun doesn't seem to check for the package in the workspace:

```
$ cd ./packages/b && bun add zod
bun add v1.0.3 (8677ae9f)
  🔍 @oven-sh/a [1/1] 
error: package "@oven-sh/a" not found registry.npmjs.org/@oven-sh%2fa 404
error: @oven-sh/a@0.0.1 failed to resolve
```

Similarly with `"@oven-sh/a": "*"`:
```
$ bun a
dd zod
bun add v1.0.3 (8677ae9f)
  🔍 @oven-sh/a [1/1] 
error: package "@oven-sh/a" not found registry.npmjs.org/@oven-sh%2fa 404
error: @oven-sh/a@* failed to resolve
```

After changing the dependency to `"@oven-sh/a": "workspace:*"`, bun seems to just use the current directory instead of searching up for a workspace:
```
$ bun add zod
bun add v1.0.3 (8677ae9f)


error: workspace dependency "@oven-sh/a" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces

```

As mentioned by @A-D-E-A `"@oven-sh/a": "workspace:../a"` seems to work though.

**Comment by firtoz** [comment]
The workarounds kinda work but the workflow is unbearable. And if I make it work inside the package's folder it doesn't work in the root and vice versa.

**Comment by MatrixAge** [comment]
+1 and this affects my workflow.

**Comment by arpadgabor** [comment]
Seems like removing `bun.lockb` before running `bun install` does the trick with `workspace:*`. Annoying but right now it works.

Edit: seems like it only works the first time, when I try to install a new dependency inside the workspace it fails.

**Comment by ryoppippi** [comment]
Same

**Comment by kvnwolf** [comment]
Another issue I'm having is that running `bun add <some workspace>` fails.

**Comment by arpadgabor** [comment]
That was fast, thanks a lot @dylan-conway and @Jarred-Sumner! 🙏

**Comment by ryoppippi** [comment]
Wait, now `bun add ...` looks so slow

**Comment by ryoppippi** [comment]
Wait, now bun add ... looks so slow
I did bun upgrade --canary and tried it

**Comment by firtoz** [comment]
@ryoppippi I think that warrants its own issue, as multiple things could have changed within canary

**Comment by ryoppippi** [comment]
OK I'll create a issue.

**Comment by tanishqmanuja** [comment]
@ryoppippi, slow might be an understatement xD

![2023-09-27 16 43 26](https://github.com/oven-sh/bun/assets/40914272/ec5f32f5-f916-4a56-badb-62c3e23cc573)
I decided to SIGINT here

![2023-09-27 16 44 18](https://github.com/oven-sh/bun/assets/40914272/ab61965b-a8a4-4ebe-8ac8-f884eed42c52)

**Comment by ryoppippi** [comment]
@tanishqmanuja 
looks like the latest canary `1.0.4+e60b3607c12c91959ec795228cc299703d5b09d0` works fine.
Try the latest canary before executing `bun pm cache rm`

**Comment by ryoppippi** [comment]
@tanishqmanuja

looks like the latest canary `1.0.4+e60b3607c12c91959ec795228cc299703d5b09d0` works fine.
Try `bun i` with the latest canary after executing `bun pm cache rm` and delete the old bun.lockb, node_modules

**Comment by firtoz** [comment]
Confirming it's good on my side too 👍

**Comment by tanishqmanuja** [comment]
@ryoppippi, thanks for informing, works now 💯

EDIT: breaks again every time i add some new dependency. Works after bun pm cache rm again.
better to alias bun i -> bun pm cache rm && bun i 😂

**Comment by ryoppippi** [comment]
@tanishqmanuja me too hahaha 
Actually you can use `bun i --no-cache` for disabling cache (which I found in a couple of hours ;) )

**Comment by JonasRothmann** [comment]
I created a super quick and hacky script that removes any workspace packages, then adds the packages and then readds the workspace packages to the package.json. I have no clue how this works with peer dependencies etc.

It also only works with wildcard workspaces such as "packages/*", but yeah it is quite a simple script mainly to just add new packages.

https://github.com/JonasRothmann/bun-workspaces

Syntax is
`bun-workspaces -F @acme/api add elysia`

but prob better to make a script in root package.json named "ws" or whatever to shorten it to `bun ws -F=...`

**Comment by rizrmd** [comment]
bun add on workspace folder will add dependency to root package.json. Is this intended ? because when using pnpm or yarn, it add to workspace package.json , not root.
