### ISSUE TITLE
Bun install crash with DependencyLoop error

### ISSUE THREAD

**Issue by cmark1302** [oven-sh/bun#5927]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Bun install

```
[0.55ms] ".env"
bun install v1.0.3 (25e69c71)


error: Package "@humanwhocodes/module-importer@1.0.1" has a dependency loop
  Resolution: "eslint-scope@7.2.2"
  Dependency: "ttps://regi@5.4.3"


error: DependencyLoop
```

### What is the expected behavior?

Bun install should install all the packages without dependencyLoop error because yarn/pnpm doesn't throw any error

### What do you see instead?

Bun install throws Dependency loop error

**Comment by Electroid** [comment]
Duplicate of #5789

**Comment by cmark1302** [comment]
@Electroid i tried that already and it didn't work
