### ISSUE TITLE
Bun 1.0.3 and Nuxt 3

### ISSUE THREAD

**Issue by marcelloinfoweb** [oven-sh/bun#5929]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 20.4.0 x86_64 i386

### What steps can reproduce the bug?

It was working even before updating to version 1.0.3

![Captura de Tela 2023-09-22 às 17 06 58](https://github.com/oven-sh/bun/assets/2093128/2a4ba6be-594b-44b3-960d-eb03ef57338b)

### Additional information

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `bun@1.0.3`
- Builder:          `-`
- User Config:      `ssr`, `typescript`, `experimental`, `app`, `css`, `modules`, `pinia`, `quasar`, `postcss`, `vite`, `nitro`, `devtools`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `nuxt-quasar-ui@2.0.5`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

**Comment by nektro** [comment]
picture seems to be dead but `❯ bun-debug --bun x nuxi@latest init` does not succeed so that would be a good starting point

**Comment by Jarred-Sumner** [comment]
Please upgrade to macOS 12 or later

We do not support macOS 11 anymore, unfortunately.
