### ISSUE TITLE
Change default `fetch` timeout to be longer

### ISSUE THREAD

**Issue by di-danielngo** [oven-sh/bun#5930]
### What is the problem this feature would solve?

Currently `fetch` will automatically timeout after 30 secs, which is not really ideal for certain time consuming services. Even chrome has a default of 5 minutes.

### What is the feature you are proposing to solve the problem?

Is there any way to set the timeout duration in fetch option?

### What alternatives have you considered?

There are some hacky ways in the node discussions, however if Bun has a canon api it would be so much better.

**Comment by Jarred-Sumner** [comment]
Fixed by #6217

**Comment by morpig** [comment]
is it possible to set timeout seconds from fetch function? #6217 PR seems to be hardcoded from bun's side.

in my case, need a 5-10 seconds fetch timeout for payments-related stuffs.
