### ISSUE TITLE
node:fs/promises not found when compiling a CLI with bun build

### ISSUE THREAD

**Issue by nbbaier** [oven-sh/bun#5948]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create `index.ts` with the following content:

```ts
import { readdir } from 'node:fs/promises';

const path = process.argv[2] || '.';

const files = await readdir(path, { withFileTypes: true });

for (let file of files) {
  console.log(file.name);
}
```

Compile `index.ts` to an executable `cli`:

```
$ build --compile index.ts  --outfile cli
```

Run `$ ./cli /some/path`

### What is the expected behavior?

The expected outcome is to list the names of all files and directory in `/some/path`. 

### What do you see instead?

When running `$ ./cli` I get the following error: `error: FileNotFound reading "node:fs/promises"`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.0.3

```bun upgrade```

Leave a comment if you still see this
