### ISSUE TITLE
Bun with express type error

### ISSUE THREAD

**Issue by techtok4u** [oven-sh/bun#5952]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 5.10.0-25-cloud-amd64 x86_64 unknown

### What steps can reproduce the bug?

```
import express from "express";
// import authRouter from "./routes/auth";
// import cors from "cors"
// import { urlencoded } from "body-parser";
// import mongoose from "mongoose";
const app = express();
const port = 8080;



// app.use(cors())
// app.use(express.json())
// app.use(express.urlencoded({ extended: true }));
// app.use("/auth",authRouter)

app.get("/", (req, res) => {
  res.send("Hello World!");
});

app.listen(port, () => {
  console.log(`Listening on port ${port}...`);
  // mongoose.connect('mongodb://testUser:testPassword@mydomain:myport/?authSource=admin').then(res=>{
  //   if(res){
  //     console.log("Connected to db")
  //   }
  //   else{
  //     console.log("Error connecting to db")
  //   }
  // })
});
```

When we hit the route "/"  we get Type error

### What is the expected behavior?

This has to serve the page with text "Hello world!"

### What do you see instead?

```
Listening on port 8080...
404 | }
405 | class IncomingMessage extends Readable {
406 |   method;
407 |   complete;
408 | 
409 |   constructor(req, defaultIncomingOpts) {
                             ^
TypeError: Type error
      at new IncomingMessage (node:http:409:26)
      at fetch (node:http:371:26)
GET - / failed
```

**Comment by samnoonabrar** [comment]
Hi, it seems that the bug is not reproducible. FYI, I am running the same bun version (`v1.0.3`) on Ubuntu Desktop 22.04 LTS:

![image](https://github.com/oven-sh/bun/assets/36998653/297b0ee3-f90c-49ec-bb41-43ae56347925)

![image](https://github.com/oven-sh/bun/assets/36998653/cfb167e0-f8f7-4b9a-8abd-3905e267662b)

As you can see from above, there is no error in the console.
