### ISSUE TITLE
Inconsistent Header Casing for Compatibility with Node.js and Servers

### ISSUE THREAD

**Issue by prstance** [oven-sh/bun#5955]
### What version of Bun is running?

1.0.3+b651b16fdd959b349c09ec5d5056229dcd12c86b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

To reproduce the bug, follow these steps:
1. Create a Node.js server using the following code in a file named server.ts:
```typescript
// server.ts (nodejs)
const http = require('http');

http.createServer(function (req, res) {
    res.write(JSON.stringify(req.rawHeaders));
    res.end();
}).listen(3000, function() {
    console.log("server start at port 3000");
});
```
2. Create a Bun client script in a file named client.ts with the following code:
```typescript
// client.ts (bun)
fetch("http://localhost:3000/", {
    headers: {
        "Accept-Encoding": "gzip, deflate",
        "Accept": "*/*",
        "Connection": "keep-alive",
        "Authorization": "xxx",
        "Origin": "something"
    }
}).then(response => response.json()).then(json => console.log(json))
```
3. Run the Node.js server using the command: node server.ts
4. Run the Bun client using the command: bun client.ts

### What is the expected behavior?

The expected behavior should be to maintain the original casing of headers when making a fetch request, ensuring that headers are case-sensitive as required. This means not modifying what the user provides in the headers object, similar to how Node.js behaves. Needs to be fixed to ensure compatibility with all servers and to preserve the casing of headers as provided by the user.

Absolutely, addressing this bug is crucial not only for compatibility with Node.js but also for ensuring compatibility with servers that may not strictly adhere to the HTTP specifications. Maintaining the original casing of headers when sending requests is essential to handle a wide range of server configurations and ensure that communication remains reliable and consistent across different environments.

![img](https://cdn.discordapp.com/attachments/1038806259480137758/1152598423539814410/image.png)

### What do you see instead?

The headers are being converted to lowercase (case-insensitive) when they should remain case-sensitive to work correctly with all servers. In essence, the solution would involve preserving the original casing of headers and not modifying what the user provides in the headers object, similar to how Node.js handles this.
![img](https://cdn.discordapp.com/attachments/1038806259480137758/1152598623188693014/image.png)

### Additional information

It appears that this issue is strongly linked to #2288
It will be able to solve many problems like #4529

**Comment by cirospaciari** [comment]
This was fixed at some point in the past please reopen if is still a issue.
