### ISSUE TITLE
Incorrect gramatical  choice of word!

### ISSUE THREAD

**Issue by rudrakshkarpe** [oven-sh/bun#596]
### Affected URL(s)

https://bun-docs.vercel.app/#/?id=configuring-with-environment-variables

### Under the ``` Credits section ``` 

- On line no. 2, it is mentioned as ```based off of``` whereas ```based on``` would be the correct choice of a word representing it as official documentation of Bun.
- I hope this would help to make the Bun Documentation more precise to the users.

**Comment by FinnRG** [comment]
@rudrakshkarpe Could you make a PR for this?

**Comment by rudrakshkarpe** [comment]
I'd love to make a pull  request for the issue I raised, thanks for considering my issue

**Comment by rudrakshkarpe** [comment]
I have created Pull request for the same issue, I am looking forward to get it merged :)
