### ISSUE TITLE
Promise.then returns a Promise

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#5962]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

new Promise((resolve, reject)=>{
  resolve("true")
}).then(value=>value)

### What is the expected behavior?

"true"

### What do you see instead?

Promise { 'true' }

**Comment by Polygons1** [comment]
Forgot to include, this happens to me with async functions only (like Bun.file("file").json())

**Comment by sfrieske** [comment]
Seems to be correct, same behaviour on nodejs. Your result _is_ a Promise (new Promise...). If you do `await new Promise(...)` you get the resolved Promise, i.e. 'true'.

**Comment by Polygons1** [comment]
i am not using await because sometimes i don't need async because it returns a promise so i am using .then and it's basically an infinite loop

**Comment by jimmywarting** [comment]
It dose not look like something is wrong with the code.
calling `.then()` should return a new Promise (not evaluate it)

I think you are doing something incorrectly.
try it with another runtime. or give a larger code example of how you are using it in your code

**Comment by Polygons1** [comment]
i am experiencing this error on Bun.file("file").json().then(). the value is a promise, and that value is also a promise, etc...

**Comment by Pistonight** [comment]
`.then()` is supposed to return an equivalent promise immediately. If you want the `true` you need to do that inside of `then()`, or use async/await. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by jimmywarting** [comment]
`Bun.file("file")` is sync... all fine and dandy. 
calling `.json()` do return a Promise - nothing wrong with that. 
calling `promise.then()` do return a new Promise  - nothing wrong with that either.

just b/c you are calling `.then()` dosen't mean it will evaluate the value. cuz the code is still async.

i asked for a more complete code example of how you are trying to access and use the result of a promise. but i still need more to go on in order to help you out with the issue you are facing. i need a complete minimal reproduction of the code of what you get, what you expect and how you used it.

**Comment by Polygons1** [comment]
![image](https://github.com/oven-sh/bun/assets/47899327/e1573577-7503-4b60-88ff-20dd74b4f233)

**Comment by Polygons1** [comment]
u see, it's in a promise, and if i call .then on that promise, the same thing will be and not the json itself

**Comment by Polygons1** [comment]
btw, my code have 2 async functions and they are all at index.js
i have 3 files: index.js <- commands.js <- database.js and the config needs to be in the database.js file but because it needs await, i needed to export it on the database file and on the commands file to the async function (which i need to have)

btw i am working with discord.js if that helps

**Comment by jimmywarting** [comment]
And that also looks fine to me.

I'm all through a bit surprised that it did not print `Promise {<pending>}` 

Doing `then(value => value)` is pointless, it dose not do anything useful for you. 

you either want to do 
```js
const value = await Bun.file("file").json()
console.log(result)
```
or you want to do handle your code inside of the then function.
```js
const promise = Bun.file("file").json().then(value => {
  console.log(value)
})
```

**Comment by Polygons1** [comment]
btw this is in node:
> const fs = require("fs")
> fs.readFile("./nodetest.json", (err, content) => {console.log(JSON.parse(content))})
undefined
> //output { test: 'node' }

and i only have 2 async functions and i tried in many deferent ways like putting it into an async function but that function was needing an await too...

**Comment by jimmywarting** [comment]
> i have 3 files: index.js <- commands.js <- database.js 

Then i suggest that you **DO** post all of those three files with (only) the functions you are calling.

it dose sound like you need to fetch some kind of config files that is a async operation. 
so it really sounds to me that you do want to use top level await in order to export the config you need for your other files that do depend on them.

```js
export const config = await Bun.file("file").json()
```

**Comment by Polygons1** [comment]
look, i am using discord.js so i have just one thing to work with, client.on("messageCreate", async ()=>{// code})

**Comment by Polygons1** [comment]
my code is a class DB for the database (which i need the config for) and a class Bot (witch is a bridge) and index.js (the main code for the bot) (DB -> Bot -> async on("messageCreate")

**Comment by Polygons1** [comment]
and like it's not that bad for me right now, because i kinda need the config for the index anyways but why (an infinite) promise to a file reader?

**Comment by jimmywarting** [comment]
I don't think you know how promises actually works...
there is nothing wrong with how they are built or being used by Bun or `Bun.file()`
so i think this issue can be closed. It feels like this question is rather more suitable for a StackOverflow question.

`Bun.file()` works as intended - tough i think it needs to return a `File` rather than a `Blob` but that's a topic for another issue...

If you need to read a json file in a sync manner they you maybe have to use any of the sync method to read the files. like `JSON.parse(fs.readFileSync('./config.js', 'utf-8'))`

if you have `client.on("messageCreate", async ()=>{// code})`
then maybe what you want to do is:

```js
client.on("messageCreate", async ()=>{
  const value = await Bun.file('./config.json').json()
})
```

it would be better if you instead posted your code to a github repo/branch that currently fails with what you call "infinite-promises-to-a-file-reader"

**Comment by Polygons1** [comment]
yes, but how come that an async function with .then is returning the return value, and the json returns a promise, and that with .then is also a promise? like in node there isn't all that stuff

btw the code works i just want to know why .then not working but await does, like it's pretty much the same thing, right?

**Comment by Electroid** [comment]
To read a promise, you can do one of two things:

1. `await` the value, when used in an async function.
```js
async function () {
  const value = await Bun.file("package.json").text();
  console.log(value); // "{}"
}
```

2. Use `.then()`
```js
const result = Bun.file("package.json").text().then((value) => {
  console.log(value); // "{}"
});
console.log(result); // Promise
```

**Comment by Polygons1** [comment]
i am putting inside the .then a console.log but there is a promise

**Comment by Polygons1** [comment]
> Bun.file("./config.json").json().then(val=>val)
Promise {
  {
    messages: {
      '1': true,
      '2': true,
      '5': true,
      '10': true,
      '15': true,
      '16': true
    },
    channels: {
      commands: '1155082614382809139',
      verify: '1155081717867094046',
      general: '1155083754587557939'
    },
    roles: { access: '1151967195400769608', top: '1154066610584301749' }
  }
}

**Comment by Polygons1** [comment]
like why promises and not like node, straight away?

**Comment by jimmywarting** [comment]
promises are used for handling asynchronous operations, like making network requests, reading files, or waiting for timeouts. Promises allow you to write asynchronous code in a more readable and manageable way that replaces [callback hell](https://stackoverflow.com/questions/25098066/what-is-callback-hell-and-how-and-why-does-rx-solve-it)

Promise chains are a way to sequence and control the flow of asynchronous operations using promises. They are typically constructed using the `.then()` method, which is available on promise objects. Here's how promise chains work:

1. **Creating a Promise:** To start a promise chain, you typically create a promise by calling a function that returns a promise. This function performs an asynchronous operation and eventually resolves or rejects the promise based on the outcome of that operation. For example:

   ```javascript
   const promise = new Promise((resolve, reject) => {
     // Asynchronous operation
     setTimeout(() => {
       const data = "Some result";
       resolve(data); // Resolve the promise with data
     }, 1000);
   });
   ```

2. **Chaining `.then()`:** Once you have a promise, you can chain `.then()` methods to it. Each `.then()` method takes one or two functions as arguments: one for success (resolved) and one for failure (rejected). The success function is executed when the promise is resolved, and the failure function is executed when the promise is rejected. Here's how you chain `.then()`:

   ```javascript
   promise
     .then((result) => {
       console.log(`Success: ${result}`);
     })
     .catch((error) => {
       console.error(`Error: ${error}`);
     });
   ```

3. **Returning Promises:** Inside a `.then()` function, you can return another promise. This allows you to create a sequence of asynchronous operations. When you return a promise within a `.then()`, the next `.then()` in the chain will wait for that promise to settle (either resolve or reject) before executing its success or failure function. For example:

   ```javascript
   promise
     .then((result) => {
       console.log(`Success: ${result}`);
       return new Promise((resolve, reject) => {
         setTimeout(() => {
           const data = "Another result";
           resolve(data);
         }, 1000);
       });
     })
     .then((result) => {
       console.log(`Success: ${result}`); // Success: Another result
     })
     .catch((error) => {
       console.error(`Error: ${error}`);
     });
   ```

One very common promise chain is network calls

```js
const value = fetch('https://example.com')
  .then(response => {
    // this happens asynchronously and is being called once it finally get a response 
    console.log(`got a ${response.status} response from ${response.url}`)
    return response.text()
  })
  .then(text => {
    // this also happens asynchronously and is being called once it have read the hole response
    console.log(`text content: ${text}`)
    // Don't return anything here...
  })
 
// this code below is still synchronously execution cuz it dose not wait for anything
// and the response from https://example.com have not come in yet
console.log('this logs first')

// therefore `value` is still an unresolved / pending Promise
console.log(value) // Promise {<pending>}

value.then(returnValue => {
  console.log('done with request')
  console.log(returnValue) // undefined - cuz i did not return anything after logging the text
})
```

do you see how return different things in each `.then()` call?
that is what is going to be passed down to the next `.then()` chain

So when i meant that `.then(val => val)` dose nothing useful for you then i meant it.
it's like writing 

```js
Promise.resolve(true)
  .then(val => {
    // inspecting the value
    console.log(val) // true
    return val
  })
  .then(val => {
    // inspecting the value
    console.log(val) // still true
    return val
  })
```
removing all the inspection and minifying the code a bit then it becomes similar to just `.then(val => val)`
```js
Promise.resolve(true)
  .then(val => val)
  .then(val => val)
```
so returning the same is value is like passing in a identity function
```js
function identity(a) {
  return a
}

Promise.resolve(true)
  .then(identity)
  .then(identity)
```
...useless

you can only use the value inside of a `.then()` function or await the promise like https://github.com/oven-sh/bun/issues/5962#issuecomment-1732356940 have already suggested
