### ISSUE TITLE
`Promise.all` stuck - Errors as `TypeError: Cannot resolve a promise with itself` or `exited with code 11 (SIGSEGV)`

### ISSUE THREAD

**Issue by mkosir** [oven-sh/bun#5970]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Executing code:
```ts
const urls = [
  'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-05.zip',
  'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-06.zip',
  'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-07.zip',
];

export const downloadFiles = async () => {
  let downloadCount = 0;

  const urlPromises = urls.map(async (url, index) => {
    const file = await fetch(url);
    await Bun.write(`./test-${index}.zip`, file);

    downloadCount++;

    console.log(`Downloaded ${downloadCount}/${urls.length} - ${url}`);
  });

  await Promise.all(urlPromises);

  console.log('This line does not execute');
};
```

Downloads all (3) files but code stops executing/gets stuck, sometimes it also reports an error `TypeError: Cannot resolve a promise with itself` or `error: script "dev" exited with code 11 (SIGSEGV)`.

### Additional information
Keep doing awesome stuff, it's 🔥

**Comment by Electroid** [comment]
Interesting. It looks like this error is coming from JSC, but it's still likely a bug in Bun.

https://github.com/WebKit/WebKit/blob/35f2dc4a536f0ebc452af9168614e97159195214/Source/JavaScriptCore/builtins/PromiseOperations.js#L177-L185

**Comment by Jarred-Sumner** [comment]
This bug happens because `Bun.write` doesn't currently support writing streaming responses and it is expecting that the `Response` is fully buffered by the time it receives the `Response`. This worked in earlier versions of Bun because we didn't use to support streaming `fetch` responses.

The temporary workaround for now is:
```js
    await Bun.write(`./test-${index}.zip`, await file.blob());
```

**Comment by mkosir** [comment]
Thanks for fast responses! @Jarred-Sumner unfortunately suggested temporary workaround doesn't work :/

**Comment by simylein** [comment]
Does this suit your needs?

```ts
import { write } from 'bun';
 
const urls = [
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-05.zip',
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-06.zip',
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-07.zip',
];
 
console.log('downloading...');
 
const responses = await Promise.all(urls.map((url) => fetch(url)));
await Promise.all(responses.map((response, index) => write(`./test-${index}.zip`, response)));
 
console.log('downloaded');
```

**Comment by mkosir** [comment]
Thanks for the suggestion, but it kind of defeats the purpose, since I'm rewriting CLI tool from Node to Bun to make things fast-er.
After downloading files, other async operations needs to resolve in parallel, instead of waiting sequential execution: creating folder for each file, unzip file etc.

**Comment by simylein** [comment]
And if you create an async function which downloads one file exactly and does other await things and then map a promise all which you globally await would that work for you?

```ts
import { write } from 'bun';

const download = async (url: string, name: string): Promise<void> => {
	console.log(`downloading ${name}...`);
	const response = await fetch(url);
	console.log(`saving ${name} to disk...`);
	await write(name, response);
	console.log(`download for ${name} complete`);
	// feel free to do more await stuff
};

const urls = [
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-05.zip',
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-06.zip',
	'https://data.binance.vision/data/spot/monthly/trades/BTCBUSD/BTCBUSD-trades-2023-07.zip',
];

await Promise.all(urls.map((url, ind) => download(url, `file-${ind}.zip`)));
```

**Comment by MarceloPrado** [comment]
Confirmed @Jarred-Sumner 's [workaround](https://github.com/oven-sh/bun/issues/5970#issuecomment-1732539893) fixed my `TypeError: Cannot resolve a promise with itself` issue.

**Comment by Jarred-Sumner** [comment]
I believe this has since been fixed

If you're still running into this issue please leave a comment.
