### ISSUE TITLE
bun install -g not working

### ISSUE THREAD

**Issue by var-arora** [oven-sh/bun#5976]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Installed bun with Homebrew on macOS Ventura, installed the `uuid` package globally with bun, then attempted to run the binary from the command line which failed to be linked into my PATH.

```
brew install bun
bun install -g uuid
uuid
```

### What is the expected behavior?

`uuid` binary runs correctly and produces a uuid.

### What do you see instead?

`zsh: command not found: uuid`

### Additional information

Installed bun via homebrew

**Comment by cyfung1031** [comment]
`bunx uuid` can work

**Comment by var-arora** [comment]
> `bunx uuid` can work

Sure but there are certain packages I want to keep installed globally. `uuid` is just an example here. Global installs are supposed to be a feature in bun afaik.

**Comment by cyfung1031** [comment]
I found that there is no `bun install -g` in the docs. 
but there is [bun add -g](https://bun.sh/docs/cli/install#bun-add)

<img width="790" alt="Screen Shot 2023-09-24 at 10 51 03" src="https://github.com/oven-sh/bun/assets/44498510/3f82b4c1-9cf8-46f4-b212-59663ce4aa34">



However it does not work with my macbook.

**Comment by cyfung1031** [comment]
I found the solution [here](https://zenn.dev/siino/articles/ac3eb2a2b3ecab).

bun installation does not add `~/.bun/bin` into the PATH.

<img width="563" alt="Screen Shot 2023-09-24 at 11 10 58" src="https://github.com/oven-sh/bun/assets/44498510/fb812e23-c6c3-4601-b525-d9cd08bbccdc">


You need to manually do it.

`echo -e export BUN_INSTALL="\$HOME/.bun" >> ~/.bash_profile`
`echo -e export PATH=\$BUN_INSTALL/bin:\$PATH >> ~/.bash_profile`
`source ~/.bash_profile`

Then it will work.

**Comment by var-arora** [comment]
Can confirm after adding `~/.bun` to my path the installed binaries are available to run
