### ISSUE TITLE
importing json

### ISSUE THREAD

**Issue by jimmywarting** [oven-sh/bun#5978]
### What is the issue?

In your docs you describe that importing json is possible with
```js
import data from "./package.json";
```
i think it should actually suggest that this should be written as such:
```js
import data from "./package.json" with { type: 'json' }
```

### Where did you find it?

https://bun.sh/guides/runtime/import-json

**Comment by Electroid** [comment]
Potentially in the future. IDEs have poor/no support for `with` expressions at the moment and it would confuse most developers.
