### ISSUE TITLE
`Bun.file` should extend `File` not `Blob`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#5980]

**Comment by jimmywarting** [comment]
Hope some of this can also be addressed.
- https://github.com/oven-sh/bun/issues/4460#issuecomment-1725323631

**Comment by zg009** [comment]
Is this as simple as just updating the type to extend a File and making sure the name property of the BunFile is non-nullable? I'm new so I'm unsure of the cascading effects., but it seems that File and Blob are basically the same except for that difference.

**Comment by jimmywarting** [comment]
Neither `BunFile` or `Blob` should have a `name` or `lastModified` property, they should live on the `File` class itself.

I think it should look more like this:
```js
class Blob {
  size = 0
  type = ""
  slice() { ... }
  text() { ... }
  arrayBuffer() { ... }
  stream() { ... }
  [Symbol.toStringTag] = "Blob"
}
class File extends Blob { 
  name = ""
  lastModified = 0
  [Symbol.toStringTag] = "File"
}
class BunFile extends File { 
  constructor() {
    this.file = super(...)
  }
  json() { ... }
  exist() { ... }
  writer() { ... }
  formData() { ... }
  slice() { ... } // in case Bun wants to override Blob.slice to return a BunFile instead. 
}
```

**Comment by jimmywarting** [comment]
bump

**Comment by jimmywarting** [comment]
bump

**Comment by Jarred-Sumner** [comment]
What is this breaking?

**Comment by Jarred-Sumner** [comment]
I don't think we should do this. `File` is buffered. `Bun.file()` is lazy. They're different things which both implement the same Blob class.

**Comment by jimmywarting** [comment]
A `File` or `Blob` don't have to be buffered (unless it's constructed from some Typed array buffer). 
In fact, a File in chrome coming from a `<input type="file">` is not at all buffered into memory at all. (it's only stat:ed) to return last modified date and retriving the file name.

And in NodeJS `fs` a file can be opened as a `Blob` and be backed up by the FileSystem, nothing is really buffered
see: https://nodejs.org/api/fs.html#fsopenasblobpath-options

same thing with what i have built before NodeJS shipped it: https://github.com/node-fetch/fetch-blob

![Skärmavbild 2024-08-29 kl  11 05 06](https://github.com/user-attachments/assets/9cca831c-1d9f-4973-8382-8730eb2baabe)

Blob system terminology:

- Blob: This is a blob object, which can consist of bytes or files, as described above.
- BlobDataItem: This is a primitive element that can basically be a File, Bytes, or another Blob. It also stores an offset and size, so this can be a part of a file. (This can also represent a “future” file and “future” bytes, which is **used to signify a bytes or file item that has not been transported yet).**
- dependent blobs: These are blobs that our blob is dependent on to be constructed. As in, a blob is constructed with a dependency on another blob (maybe it is a slice or just a blob in our constructor), and before the new blob can be constructed it might need to wait for the “dependent” blobs to complete. (This can sound backwards, but it‘s how it’s referenced in the code. So think “I am dependent on these other blobs”)
- transport strategy: a method for sending the data in a BlobItem from a renderer to the browser. The system currently 
implements three strategies: Reply, Data Pipe, and Files.
- blob description: the inital data sychronously sent to the browser that describes the items (content and sizes) of the new blob. This can optimistically include the blob data if the size is less than the maximum mojo message size.

ref: 
- https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md
- https://docs.google.com/presentation/d/1MOm-8kacXAon1L2tF6VthesNjXgx0fp5AP17L7XDPSM/edit#slide=id.g8fe6c1657_0_10

**Comment by Jarred-Sumner** [comment]
Bun.file() has an unknown size and it may error on retrieving the data if it doesn’t exist. It’s not just lazy contents, it might point to nothing. And reading the value from it may change each time. It does not correspond to a file descriptor if no file descriptor is passed

**Comment by jimmywarting** [comment]
I still think you should fix your inherently web spec incompatible File api. 

1. the `Blob` class should not contain that many properties

```js
Blob {
  arrayBuffer: [Function: arrayBuffer],
  bytes: [Function: bytes],
  delete: [Function: delete],
  exists: [Function: exists],
  formData: [Function: formData],
  json: [Function: json],
  lastModified: undefined,
  name: undefined,
  size: undefined,
  slice: [Function: slice],
  stat: [Function: stat],
  stream: [Function: stream],
  text: [Function: text],
  type: undefined,
  unlink: [Function: unlink],
  write: [Function: write],
  writer: [Function: writer],
}
```

2. The `File` should not be an alias for `Blob` This is wrong:

```js
File.prototype === Blob.prototype
```

---

Don't mess with web spec'ed apis. if you want to bring in more advanced features, then create your own class like Deno did with `Deno.fsFile` 

if you want you can extend `File` while still overriding them with lazy getters

The fact that you override `node:buffer#Blob` and `node:buffer#File` with your own non spec compliant version make it really more troublesome
