### ISSUE TITLE
Latest versions of Bun have broken use of confirm() prompts.

### ISSUE THREAD

**Issue by infrahead** [oven-sh/bun#5985]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Had written scripts that used to work, and had checkpoints similar to following...
`if ( confirm('Proceed?') )  // never true`

No matter what enter in terminal, "y", "Y", "yes", confirm always returns false now

### What is the expected behavior?

for a value of y, return true

### What do you see instead?

returns false for any value

**Comment by Jarred-Sumner** [comment]
confirming that confirm returns false 

I don't think we have tests for `confirm` right now

**Comment by infrahead** [comment]
Starting to think you are a bot @Jarred-Sumner  ;).   To be clear, this was working for some time, and I'm not sure which version broke it, as only just reran a bunch of infrastructure scripting I had moved to Bun.

I'll try to write some tests (as part of learning Bun testing) to paste here if that is any help
