### ISSUE TITLE
schema.prisma can't detect the environment variables NODE_ENV

### ISSUE THREAD

**Issue by Majoramari** [oven-sh/bun#5992]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

- create `.env.production` and store your prod env in it
- create `.env.development` and store your dev env in it

run script from package json like this
NODE_ENV=development bun run prisma db push

### What is the expected behavior?

it should pick the right env from the right file, if I'm in prod it should get the prod thing

### What do you see instead?

It seems no env is detected at all

![image](https://github.com/oven-sh/bun/assets/33487552/ff6b2ce0-f0d4-484b-8fa9-aeb34327d43b)

```
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider     = "mysql"
 7 |   url          = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.3.1
error: "prisma" exited with code 1 (SIGHUP)
error: script "prismaa" exited with code 1 (SIGHUP)
```

### Additional information

I'm doing this to use planetscale branches with prisma so I need 2 different DATABASE_URL

**Comment by koushikcore** [comment]
Hi, Prisma's env wrapper picks only from .env file. Bun's way of picking directly from .env.local, .env.production is not possible by prisma. This needs to be fixed by prisma to accommodate bun. Meanwhile you can create .env file and load variables from that file.
