### ISSUE TITLE
Configurable feature map

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#6]
Right now, the bundler always transpiles effectively to `ESNext`. This should be configurable, and a limited amount of backwards-compatibility should be possible. Don't need to go as far back as ES6, but perhaps specifically `last 2 versions` for Safari.

**Comment by redjonzaci** [comment]
I wonder if I can work on this or if it is still needed.

**Comment by Electroid** [comment]
With `bun build` and `Bun.build()`, this issue isn't relevant anymore.
