### ISSUE TITLE
Support SvelteKit

### ISSUE THREAD

**Issue by niiwade** [oven-sh/bun#600]
### What is the problem this feature will solve?

We need to have Svelte to be included in the project creation step to make it easy to using Bun to create Sveltekit apps. 

### What is the feature you are proposing to solve the problem?

We need `bun create svelte ./app` to make it easy to create a new svelte project

**Comment by FinnRG** [comment]
@niiwade Would you like to create a PR for this?

**Comment by niiwade** [comment]
yes sure

**Comment by swyxio** [comment]
note that there is a community adapter here you can maybe crib from https://github.com/gornostay25/svelte-adapter-bun

**Comment by niiwade** [comment]
> note that there is a community adapter here you can maybe crib from https://github.com/gornostay25/svelte-adapter-bun

Thank you @sw-yx , am checking it out

**Comment by ryanrussell** [comment]
Any good news on SvelteKit + bun runtime?

This would be a great framework to get first class support for in bun. 

![image](https://user-images.githubusercontent.com/523300/181996608-a4476a06-f01a-4227-9acf-d95edbe21aef.png)

**Comment by paperclover** [comment]
Status on SvelteKit:

- It depends on `worker_threads`, though not much of it. Just `parentPort` and `new Worker`, and passing `env` data.
- Since we do not export anything in `worker_threads`, it causes vite to crash loading the config file.

**Comment by kansson** [comment]
SvelteKit is now working with `bun upgrade --canary` until `v0.7.2` is released 🚀
EDIT: There is still some work to be done see https://github.com/oven-sh/bun/issues/600#issuecomment-1664814473.

**Comment by gitblit** [comment]
This was a nice surprise. Thanks for commenting @hanssonduck . Looks like there are some minor console tty issues on Vite and some HMR issues too, although fair to say those are not SvelteKit directly. On a starter app built from the Svelte bootstrapping command, I have success. On a more complex app, I have hanging requests. Not sure why yet. But overall getting closer!!

<img width="604" alt="image" src="https://github.com/oven-sh/bun/assets/868217/c9f3c84e-63bc-4cac-b598-03bd9091bc83">

**Comment by paperclover** [comment]
Worker threads got it so importing sveltekit stopped throwing, which gets us past the vite config load step.

But

We're not fully there yet, unfortunately. I've spotted some reliability issues with actions and `.formData()`, where the promise never resolved. Though small reproductions dont actually recreate the issue. Something subtle with our streams implementation.

Looking into it and maybe we'll have it fully working by 0.7.3.

**Comment by paperclover** [comment]
update: found what is blocking sveltekit actions from working:
```ts
const headers = new Headers();
headers.append("Content-Type", "application/json");
headers.append("Set-Cookie", "cookies");
const entries = Array.from(headers);
expect(entries).toEqual([
  ["content-type", "application/json"],
  ["set-cookie", "cookies"],
]);
```
what bun is doing is duplicating the content-type header, meaning cookies never get set.

this took a very long time to narrow down haha

**Comment by paperclover** [comment]
the set cookie pr will make dev server fully functional. there is a different issue that is tracked by #3943 but i htink we should keep this issue open until that is fixed as this a broader tracking issue.

we are close. i imagine this week / next release

**Comment by paperclover** [comment]
did i say this week actually meant _now_ after https://github.com/oven-sh/bun/pull/4052

**Comment by gitblit** [comment]
@paperdave are there special considerations for running SvelteKit with Bun like changing the adapter or some other tweak? Forms are still hanging on me.  Looks related to websockets. I'm running all the latest packages and the latest canary build on WSL2.

<img width="851" alt="image" src="https://github.com/oven-sh/bun/assets/868217/5525e956-56eb-4fcc-9d3f-df7417b95696">

**Comment by birkskyum** [comment]
@gitblit I don't think the canary has been updated since this fix was added. You can see [here](https://hub.docker.com/r/oven/bun/tags) under canary when it was updated last - some 22h ago. The only way you can test this now would be to build bun locally, which actually isn't that hard, or just try again tomorrow.

**Comment by gitblit** [comment]
I'll admit I don't know exactly how the binaries are served. The README suggests canary is built on every push to `main` and I was assuming they are downloaded from [Github artifacts](https://github.com/oven-sh/bun/releases/tag/canary) and not from a Docker container, but that might not be a valid assumption.

**Comment by birkskyum** [comment]
@gitblit interesting, you might be right about that. In that case I wonder why the canary docker image isn't kept in sync.

**Comment by Jarred-Sumner** [comment]
Canary is compiled on every commit to main. Here is the most recent one for Linux x64 at the time of writing: https://github.com/oven-sh/bun/actions/runs/5794742061

The `bun-linux-x64` one is the artifact which becomes the canary build of bun

**Comment by gitblit** [comment]
The 0.8.0 canary is now running my SvelteKit app _almost_ perfectly. The fix for hanging await formData mentioned on Twitter addresses the scenario I noted [here](https://github.com/oven-sh/bun/issues/600#issuecomment-1669536879). I will post the remaining issue I observe as a new ticket.

**Comment by birkskyum** [comment]
There is something going on here - sveltekit often freezes and doesn't manage to boot the server.
- https://github.com/oven-sh/bun/issues/4371#issuecomment-1695270779

**Comment by Tyjust31** [comment]
For the development of bun run dev, I prefer to use a plugin like vite directly on vs code store because there is a bug

**Comment by Tyjust31** [comment]
To build for production, you'll need to add the right SvelteKit adapter. Currently we recommend the

bun add -D svelte-adapter-bun.

Now, make the following changes to your svelte.config.js.

**Comment by birkskyum** [comment]
Let's see what the [svelte summit tomorrow](https://www.youtube.com/watch?v=pTgIx-ucMsY) brings of announcements.
