### ISSUE TITLE
startup script: "bun: command not found"

### ISSUE THREAD

**Issue by arthur-adriansens** [oven-sh/bun#6005]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux, Raspberry Pi Lite os

### What steps can reproduce the bug?

If you create a startup script, with these commands:
1. startup.sh: 
`#!/bin/bash`
`sleep 15`
`echo "Hello, Raspberry Pi!" >> /home/pi/startup.log`
`bun run /home/pi/script/index.js >> /home/pi/node_log.log 2>&1 &`
`bun run /home/pi/script/index.js`

2. `chmod +x /home/pi/startup.sh`

3. `crontab -e`

4. `@reboot /home/pi/startup.sh`

And you do sudo reboot and do `cat node_log.log`, then it says “bun: command not found”.

Yes, the script works when I do` bun run /…` manually when I ssh into my Raspberry Pi. If I run a node script and log it to the log, then node works. The script starts a server at port 3000, but that's not relevant I think, because the js file is never executed. Sudo bun doesn't work neither.
I love Bun, and I hope you can help me! Feel free to ask me more questions about my system.

### What is the expected behavior?

It should run the bun script, but the log file shows “bun: command not found”. I expect the server to start at port 3000 on startup (the script works when I run it manually).

### What do you see instead?

"bun: command not found"

### Additional information

![image](https://github.com/oven-sh/bun/assets/79015591/c36421f4-501a-47fd-b588-619da039af90)

**Comment by Electroid** [comment]
How did you install Bun?

**Comment by arthur-adriansens** [comment]
I don't remember, just with `curl -fsSL https://bun.sh/install | bash` I believe. 
I just updated (and rebooted) to the most recent version. The script works when I just do `bun run /home/pi/script/index.js` in the terminal. But it doesn't when I try doing it on startup... Node scripts do work.

**Comment by grizmio** [comment]
please paste the output of 
$ which -a bun

**Comment by arthur-adriansens** [comment]
> please paste the output of $ which -a bun
```
pi@raspberrypi:~ $ which -a bun
/home/pi/.bun/bin/bun
/home/pi/.bun/bin/bun
pi@raspberrypi:~ $ 
```

**Comment by grizmio** [comment]
I  guess bun is not in variable PATH,
One option is to use in the script the full path
/home/pi/.bun/bin/bun run /home/pi/script/index.js
Or, in the script:
PATH="${PATH}:${HOME}/.bun/bin"
I would go with the first one.
And you should check if its really needed to execute index.js twice.

**Comment by arthur-adriansens** [comment]
Yes! It works, thank you so much!!! I'm so happy :)))!
```
#!/bin/bash

echo "Hello, Raspberry Pi!" >> /home/pi/startup.log
/home/pi/.bun/bin/bun run /home/pi/script/index.js >> /home/pi/node_log.log 2>&1 &
```

**Comment by niccoreyes** [comment]
> I guess bun is not in variable PATH, One option is to use in the script the full path /home/pi/.bun/bin/bun run /home/pi/script/index.js Or, in the script: PATH="${PATH}:${HOME}/.bun/bin" I would go with the first one. And you should check if its really needed to execute index.js twice.

This worked for me! Thank you so much, I preferred the PATH="${PATH}:${HOME}/.bun/bin"
