### ISSUE TITLE
Runtime Reflection API

### ISSUE THREAD

**Issue by Pandapip1** [oven-sh/bun#6006]
### What is the problem this feature would solve?

There are number of use cases for a runtime type checking/reflection API. For example, I want to make a helper to turn objects into C structs compatible with Bun FFI and vice versa. However, the 'vice versa' part isn't possible because you can't get the typescript data of an object at runtime.

### What is the feature you are proposing to solve the problem?

An API like https://rttist.org/, but for Bun.

**Comment by Jarred-Sumner** [comment]
JavaScript is a dynamic language

You can use `typeof`, `instanceof`, and so many more language features to support runtime reflection. You can also use TypeScript experimental decorators.
