### ISSUE TITLE
Redis : Can't auto reconnect a restarted server

### ISSUE THREAD

**Issue by solisoft** [oven-sh/bun#6011]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```js
const Redis = require("ioredis");
const redis = new Redis({
	retryStrategy(times) {
		const delay = Math.min(times * 50, 2000);
		return delay;
	}
});

setInterval(async ()=>{
	redis.ping().then((msg) => {
		console.log(msg)
	})
}, 2000)
```

### What is the expected behavior?

When the Redis server is restarted, it should auto-reconnect and it should returns PONG

### What do you see instead?

It just hang

**Comment by cirospaciari** [comment]
Looks like this was fixed at some point in the past please reopen if still get this issue in the future.
