### ISSUE TITLE
FormData video file does not have type on Windows 10 WSL2

### ISSUE THREAD

**Issue by wfl-junior** [oven-sh/bun#6012]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I created a small server for uploading files, copying from the example at https://bun.sh/guides/http/file-uploads

Here is the code:

```ts
const server = Bun.serve({
  port: 4000,
  async fetch(request) {
    const url = new URL(request.url);

    if (url.pathname === "/upload") {
      const formdata = await request.formData();
      const file = formdata.get("files") as Blob;
      if (!file) throw new Error("Must upload a file.");

      console.log({ type: file.type });

      // await Bun.write('profilePicture.png', file);
      return new Response("Success");
    }

    return new Response("Not Found", { status: 404 });
  },
});
```

And make a multipart form request to http://localhost:4000 sending `files` key with a video type file.

### What is the expected behavior?

To see the mimetype of the video file.

### What do you see instead?

Console logs:

```ts
{
  type: ""
}
{
  type: "image/jpeg"
}
{
  type: ""
}
{
  type: ""
}
{
  type: ""
}
{
  type: "image/jpeg"
}
{
  type: "image/png"
}
{
  type: "image/png"
}
{
  type: ""
}
{
  type: ""
}
{
  type: ""
}
{
  type: ""
}
```

The empty ones are videos, it works fine with images.

### Additional information

I am running Bun on WSL2 Windows 10 (Microsoft Windows NT 10.0.19045.0 x64).
Requesting via Insomnia with multipart form body.
I have tried requesting via a simple html form with multipart/form-data enctype and same issue.

**Comment by jimmywarting** [comment]
How dose the upload part look like? the same as the html page with file inputs?
try have a look at input.files to see what type they have.

it's not the `request.formData()` fault that it's not getting any type, it's probably due to not sending any...

**Comment by Electroid** [comment]
Could you share the code or script that you used to upload the form?

**Comment by wfl-junior** [comment]
> How dose the upload part look like? the same as the html page with file inputs? try have a look at input.files to see what type they have.
> 
> it's not the `request.formData()` fault that it's not getting any type, it's probably due to not sending any...

I have tried both on a normal html form, I checked it sends the video as `video/mp4` and uploading from Insomnia.

**Comment by wfl-junior** [comment]
> Could you share the code or script that you used to upload the form?

```tsx
export function App() {
  return (
    <div className="bg-zinc-900 flex items-center justify-center min-h-screen">
      <form
        action="http://localhost:4000/upload"
        method="POST"
        encType="multipart/form-data"
        className="flex flex-col gap-3"
      >
        <input type="file" name="files" required />

        <button
          type="submit"
          className="rounded-md px-4 py-2.5 bg-indigo-600 text-white"
        >
          Submit
        </button>
      </form>
    </div>
  );
}
```

I was having the issue when testing from Insomnia, so I created this basic html form to test it as well to make sure it wasn't an Insomnia issue.

**Comment by jimmywarting** [comment]
Good, now can you check and see if all the files have a type?

```js
<input type="file" name="files" required onchange="console.log(this.files)" />
```

----

one thing i wonder about is why it dose not default into a `application/octet-stream`...
```js
fd = new FormData
fd.set('x', new Blob())
fd2 = await new Response(fd).formData()
fd2.get('x').type // application/octet-stream
```

**Comment by jimmywarting** [comment]
matter of fact... could you do a `request.text().then(console.log)` to log the raw body to inspect if there is any type?

you would probably get a lot of data if you select a large video file... so that would be tuff to debug
maybe do: 
```js
request.text().then(str => console.log(str.slice(0, 2048)))`
```

**Comment by wfl-junior** [comment]
> Good, now can you check and see if all the files have a type?
> 
> ```js
> <input type="file" name="files" required onchange="console.log(this.files)" />
> ```
> 
> one thing i wonder about is why it dose not default into a `application/octet-stream`...
> 
> ```js
> fd = new FormData
> fd.set('x', new Blob())
> fd2 = await new Response(fd).formData()
> fd2.get('x').type // application/octet-stream
> ```

![image](https://github.com/oven-sh/bun/assets/61035071/674d9b76-9a8f-4278-abb0-f899c48e1aaf)

Yes, the file has a video/mp4 type

logging like this:

```jsx
<input
  type="file"
  name="files"
  required
  onChange={event => console.log(event.target.files)}
 />
```

**Comment by wfl-junior** [comment]
> matter of fact... could you do a `request.text().then(console.log)` to log the raw body to inspect if there is any type?
> 
> you would probably get a lot of data if you select a large video file... so that would be tuff to debug maybe do:
> 
> ```js
> request.text().then(str => console.log(str.slice(0, 2048)))`
> ```

I changed the code to this:

```ts
const server = Bun.serve({
  port: 4000,
  async fetch(request) {
    const url = new URL(request.url);

    if (url.pathname === "/upload") {
      const text = await request.text();
      console.log(text.slice(0, 2048));
      // const formdata = await request.formData();
      // const file = formdata.get("files") as Blob;
      // if (!file) throw new Error("Must upload a file.");

      // console.log({ type: file.type });

      // await Bun.write('profilePicture.png', file);
      return new Response("Success");
    }

    return new Response("Not Found", { status: 404 });
  },
});

console.log("running");
```

The log is the following when uploading the same original.MP4 file:

```
------WebKitFormBoundaryt9M5d2ghchJxtQkL
Content-Disposition: form-data; name="files"; filename="original.MP4"
Content-Type: video/mp4

 ftypiso4iso4hvc1       ƅ�mdatIb&�����x�0HQ�@O�{b�n�9%�4��[E���W�
                                                                 ^}Ք�Y�֦�T;ˋ
                                                                           D��q�N�vp    Z�E}ͅǲ���r���~}5H�n��;Ȧ�=���GO0S�b̨���jr}PO�)%X�T&�7ď޿��#�/�mޅq���P!�mM�t��(�,9��&|��2o�R��O,{u��)EH,��W��Kh[uHkC]P�;)���"�M8���>���H����I�췒Q?��*�(~�t�������v��H��w��c��tr��%ҡFV�Zo�0C��$L�6na�~ϒa/�7�PQFY�AA�+��?�����H�(̖��$���0cm��F
                                                                                                                                                             4k5-�ԪsN �F_xpUiqxF�Zo�P
�/f�+� �\��
       �I%�6���Z��;v��&&W�݂�M�2=�s<�(�f�X]��6���ҪEs��3��W�����LM��Z�3b"�v���eZY�ϴȱ>�j#���'�(�ݨ�y�{�k6\qIn��eL�\�)g>zD��3��]��9�dˁ�-`���|:�)Y�&�ĸbC���w�^��ȥ�]�����
m���&�=�)(�~H���5��5���t<�ʴ��+}д��æ�n�����䓀2�h�C�����eu��=�E2��|]Pa�Kj;�E�mƞ%{�Aԕ�RX��=�g�.�!�
                                                                                               |���{�C�x�d�0��ņ���]0 �תL�c9���aF�G-�(:����m'��
                                                                                                                                              f������<
                                                                                                                                                      ��s����N&��jk�d�|�z|�ת�c���#���FC;��L^��T���bj'�x���
�f]��b@�tQ�HI�p ��,f[�]eS�>�b�І�V\����d)��� �l���=Y�
'���L�d�o۫ѝ�1�=���@                                  r�N��Δ8��[�(�H�w��uFS�|Ġ^
�hSMC����Y�5\;�Hf��`�8XS.:���,�P�Ayo�jm�c�f\��L��e.�m�ϰJ�����zK��������J�
�*��j�rx��n�a��t����Y'�4'(+���\rdQB~�v�r�~���
��ϰ��
e�y��P_g�©�o�H
�ۖ�7����
      ��?������E��؛����zd��8��z��!�|0����'?��Z�L��=�G�{
��у���c��                                              0���[e\�Ɯ��6o6�h]�OR*U�B0A��B�fC-_����,d}�a����I��W����Y,:e�
m{�YqsQ8k��S�"��n����10�D���|�G"�*����~�ދ������d�(���o<�)�u����RnϦ��K;��:��ෙc�%]��iG���C}�/+��  �ٸs@
                                                                                                    ޡ�p��
9�)�,�)��6x'C�og�;
                  �j���M��R^q��R�#Rs    (�~v[؛�m�w�<蚝N �A�e�A�Ʃ�g��n̼���[U�Ǡ�����4���Y������L��cb�<�#Q�:ȬS��-�&����<\�f&Z�KB���:a ��qΓ�v�
                                                                                                                                         ����#���Ù>3B�X����x��-�~]?��    ���[�   R�P��(�
2�����K��1�     1�,�a�U�C/�^��J.��s�0^@�r+�����R/ܳSj\(>����Ǔ��?_��\�}9)�kݑc�cÉ
��YWas�,|�j�F�
.L�; �h�LW+e)�=�3��xc?99�*U��I���v��v<7g��f�Z�7
��X�>��()��
           g�<��g�������*QY�_���E\ ��������,�P�:���~Md6�m
                                                         ѧ�k'��s�)���#�!�5T�_8�e�o�YC?#�
```

Apparently in the text response it does have the file type.

**Comment by jimmywarting** [comment]
Then its clear that a content type is uploaded and what you get back from formdata.get("files").type is a bug in Bun cuz its missing

**Comment by yadav-saurabh** [comment]
It's not limited to `Windows WSL2`, Facing the same issue in linux for some other types as well,
like:
`application/pdf `
` application/zip `
...

woking for just few image types

**Comment by ghosTedBuddy** [comment]
just to confirm: i experience the same on MacOS.
the content-type is in the raw body but is never exposed to the blob itself.

i tested also with
`application/pdf`
`application/zip`

Bun-Version: `1.0.0` + `1.0.4`

**Comment by Jarred-Sumner** [comment]
Fixed by @yadav-saurabh in https://github.com/oven-sh/bun/issues/6012
