### ISSUE TITLE
Bun seems to be incompatible with the Slonik package

### ISSUE THREAD

**Issue by cooperaustinj** [oven-sh/bun#6018]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Repository from which the issue can be reproduced: https://github.com/cooperaustinj/bun-slonik-issue

The issue happens any time bun is used with slonik as far as I can tell.

### What is the expected behavior?

Bun is able to run slonik code successfully.

### What do you see instead?

Running code using slonik results in the runtime totally freezing. There is no output and the program doesn't end. It just stalls out permanently.

<img width="225" alt="image" src="https://github.com/oven-sh/bun/assets/12889451/85859010-658f-40cb-84a0-d58a8ac58f97">

### Additional information

I'm seeking ideas about whether this may be something to be fixed in bun or in slonik. I can also troubleshoot this further if there are ideas about how to extract more information.

Related Discord thread (no replies as of writing, but perhaps in the future it will be worth referencing): https://discord.com/channels/876711213126520882/1155612258928431226

**Comment by bozkayasalihx** [comment]
I've had same issue too

**Comment by alexhwoods** [comment]
Same

**Comment by cooperaustinj** [comment]
I confirmed that this is still an issue in v1.0.4

**Comment by MelleB** [comment]
Not sure: Is this related to #6121 ?

**Comment by cooperaustinj** [comment]
I can no longer replicate this issue using the original repo and bun version 1.0.14 🙌
