### ISSUE TITLE
Bun.serve `maxRequestBodySize` not working as expected

### ISSUE THREAD

**Issue by itohatweb** [oven-sh/bun#6031]
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 5.10.0-23-amd64 x86_64

### What steps can reproduce the bug?

When creating an http server with the `maxRequestBodySize` option and sending a request bigger then that, then bun never responds until the program ends.

To Reproduce:
1. Write a simple http server with a `maxRequestBodySize`:
```ts
const server = Bun.serve({
  port: 8080,
  development: false,
  maxRequestBodySize: 100,
  async fetch(request) {
    const res = await  request.json()
    console.log({res});
    return new Response("Ok!");
  },
});

console.log(`Listening on localhost: ${server.port}`);
```
2. Send a request to the server, with a too big body
```sh
$ curl -o /dev/null -s -w "Status: %{http_code}\n" -X 'POST' \
  'http://127.0.0.1:8080' \
  -H 'Content-Type: application/json' \
  -d '{
  "content": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}'
```
3. The request never finishes
4. Stop the server 
5. Request finishes with HTTP code `413`

### What is the expected behavior?

The server immediately responds with a `413` status code and does not wait until the program ends.

### What do you see instead?

No response until the program ends.

### Additional information

I don't think so, but let me know if you need anything else.

**Comment by Hanaasagi** [comment]
This can be reproduced in 1.0.3. It seems like the server-side should actively close the connection or return a `Content-Length: 0` header.

```
>>​ curl  -X 'POST' \
  'http://127.0.0.1:8080' \
  -H 'Content-Type: application/json' \
  -d '{
  "content": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}' -vvv
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080
> POST / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/8.3.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 104
>
< HTTP/1.1 413 Request Entity Too Large


```


----

There should be a `close_connection` boolean parameter that is not being passed down in the call stack. The `uws_res_end_without_body` in Bun might currently be outdated.

https://github.com/oven-sh/bun/blob/af0cb893b577ceb0cbcd6b20c17db4534cfef114/src/bun.js/api/server.zig#L5558-L5563


https://github.com/oven-sh/bun/blob/af0cb893b577ceb0cbcd6b20c17db4534cfef114/src/deps/uws.zig#L1770-L1772

- Bun
https://github.com/oven-sh/bun/blob/af0cb893b577ceb0cbcd6b20c17db4534cfef114/src/deps/libuwsockets.cpp#L1144

- uWebSockets
https://github.com/uNetworking/uWebSockets/blob/143db3034f361a5c1d57bb3179a9b100ab6396ab/capi/libuwebsockets.cpp#L1113

myabe upgrade uwebsockets and syn c-api will fix this.
