### ISSUE TITLE
Any way to disable analytics collection by default?

### ISSUE THREAD

**Issue by roostad** [oven-sh/bun#6033]
### Discussed in https://github.com/oven-sh/bun/discussions/2605

<div type='discussions-op-text'>

<sup>Originally posted by **0xMySt1c** April 10, 2023</sup>
Is there a way to use DISABLE_BUN_ANALYTICS=1 globally.

Also it would be nice if there was also a way to check current status.
Next has a nice way to deal with this.

```
npx next telemetry status
npx next telemetry enable / disable
```

</div>

Hi,

It was mentioned by Jarred in the above discussion that Bun's analytics collection will eventually be re-enabled. This is fairly important for many users to disable by default. Are there plans to allow users to decline analytics (perhaps with a flag when first installing Bun onto a machine)?

Thanks

**Comment by Electroid** [comment]
Yes. https://bun.sh/docs/runtime/bunfig#telemetry

bunfig.toml:
```toml
telemetry = false
```

Or, set `DO_NOT_TRACK=1` as an environment variable.
