### ISSUE TITLE
TypeError: FormData parse error missing final boundary with bun

### ISSUE THREAD

**Issue by Liliandev** [oven-sh/bun#6038]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux

### What steps can reproduce the bug?

Clone an astrobuild project with Form and form data submission, an error will throw with : TypeError: FormData parse error missing final boundary when running bun with following command : bun ./dist/server/entry.mjs

If i run in dev mode, no error appears

### What is the expected behavior?

No error should throw

**Comment by Electroid** [comment]
Duplicate of #2644
