### ISSUE TITLE
`console.dir` does not respect `depth` option

### ISSUE THREAD

**Issue by JacobWeisenburger** [oven-sh/bun#6039]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Bun claims that `node:console` is Fully implemented.
![image](https://github.com/oven-sh/bun/assets/31667350/7a6440c5-761b-4734-99cc-9f257b3bb44b)

However, it seems that this code doesn't do the same thing in Bun as Node.
```ts
console.dir( { 1: { 2: { 3: 3 } } }, { depth: 0 } )
// node: { '1': [Object] }
// bun: { "1": { "2": { "3": 3 } } } { depth: 0 }
```

Is this supposed to do the same thing as Node?

### What is the expected behavior?

`{ '1': [Object] }`

### What do you see instead?

`{ "1": { "2": { "3": 3 } } } { depth: 0 }`

### Additional information

https://bun.sh/docs/runtime/nodejs-apis#node-console
https://nodejs.org/api/console.html#consoledirobj-options

**Comment by danielo515** [comment]
What version of bun has this fixed? I have 1.0.3
