### ISSUE TITLE
The `canvas` package is not supported

### ISSUE THREAD

**Issue by Milo123459** [oven-sh/bun#604]
### Version

v0.1.3

### Platform

`Linux codespaces-0ca1ae 5.4.0-1074-azure #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

Run `bun add canvas`, import it and then try run that file. You will get an error that looks something like:
```
error: Could not resolve: "../build/Release/canvas.node"
```

### How often does it reproduce? Is there a required condition?

Every time. Canvas just has to be imported for it to crash.

### What is the expected behavior?

That it wouldn't crash, and would use the Node binding

### What do you see instead?

It crashes, due to it failing to load/resolve the node binding

### Additional information

I believe this is a NAPI issue? Not sure though.

**Comment by sno2** [comment]
The problem is that Bun does not support NPM life-cycle hooks. See #606

**Comment by Milo123459** [comment]
Closing because #606 exists.

**Comment by Davidiusdadi** [comment]
#606 has been closed - but there is also an other blocker: 

`undefined symbol: node_module_register` - see:  https://github.com/oven-sh/bun/issues/4290

I
