### ISSUE TITLE
Segfault when using basic AsyncIterator

### ISSUE THREAD

**Issue by alii** [oven-sh/bun#605]
### Version

0.1.3

### Platform

Darwin trackpad.house.hop 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:48:02 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T8103 arm64

### What steps will reproduce the bug?

The following code will work in node (under tsm, so I don't have to compile the typescript...) but unfortunately not in Bun

```ts
function countUp(count: number) {
	let value = 0;

	const q: AsyncIterator<number> = {
		async next() {
			if (value === count) {
				return {
					done: true,
					value: undefined,
				};
			}

			value++;

			return {
				done: false,
				value,
			};
		},
	};

	return {
		[Symbol.asyncIterator]: () => q,
	};
}

for await (const i of countUp(10)) {
	console.log(i);
}
```

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/25351731/178377136-6499da44-3cf1-43e3-8d5e-caa6625d1599.png">

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

The code counts up to 10

### What do you see instead?

A segfault

**Comment by Jarred-Sumner** [comment]
This is something specific to top-level await

Stack trace:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/709451/178433769-37148978-cc52-4155-879b-3c122755fb63.png">




The following code no longer crashes:
```js
function countUp(count) {
  let value = 0;

  const q = {
    async next() {
      if (value === count) {
        return {
          done: true,
          value: undefined,
        };
      }

      value++;

      return {
        done: false,
        value,
      };
    },
  };

  return {
    [Symbol.asyncIterator]: () => q,
  };
}

(async function () {
  for await (const i of countUp(10)) {
    console.log(i);
  }
})();
 ```

**Comment by Jarred-Sumner** [comment]
WebKit bug report: https://bugs.webkit.org/show_bug.cgi?id=242638

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago
