### ISSUE TITLE
`module` and `exports` globals go missing / cause error if the file has an import statement

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6057]
Repro below:

## globals.ts

```ts
import { add } from './meaningless-import'
console.log(`2+2 is ${add(2,2)}`)
console.log("AbortController", AbortController) //another Bun Global
// console.log("module", module)
```

## meaningless-import.ts
```ts
export function add(a:number, b:number):number {return a+b;}
```

executing this with just plain ol'
```bun run globals.ts```

If I uncomment line 4 of `globals.ts`, it breaks with 
`SyntaxError: Unexpected token '{'. import call expects one or two arguments.`

Then if I comment out the top 2 lines it works just fine.

_Originally reported on Discord: [``module` and `exports` globals go missing / cause error if the file has an import statement`](https://discord.com/channels/876711213126520882/1155340446659252354/1155340446659252354)_

**Comment by colinhacks** [comment]
Additional experiments, including the following lines causes the issue:

```ts
console.log("module", module) // as in the original post
module.exports;
module.exports.sup = "sup";
exports = "sup";
```

These work fine:

```ts
module;
exports;
```

**Comment by Jarred-Sumner** [comment]
this is by design, a tradeoff of our ESM <> CJS compatiblity
