### ISSUE TITLE
Bun hangs on `createPool` with postgres library `slonik`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6061]
Reproducible  repository here: https://github.com/cooperaustinj/bun-slonik-issue

Bun simply freezes with no output. I'm not sure how I can get more information about the issue.

Slonik: https://github.com/gajus/slonik

_Originally reported on Discord: [`Bun freezes when used with slonik. Any ideas for debugging/workarounds?`](https://discord.com/channels/876711213126520882/1155612258928431226/1155612258928431226)_

**Comment by cooperaustinj** [comment]
The discord bot made a duplicate of the issue I created for this: https://github.com/oven-sh/bun/issues/6018

**Comment by Electroid** [comment]
Duplicate of #6018
