### ISSUE TITLE
fs.rm -r not working for standalone executable

### ISSUE THREAD

**Issue by kerambit** [oven-sh/bun#6065]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create directory testdir with any files and subdirs int it

Write the code below in cli.ts file

```typescript
import * as fs from 'fs/promises';
await fs.rm(
    join(__dirname, 'testdir'),
    {
        recursive: true,
    }
);
```

`$ bun build ./cli.ts --compile --outfile cli`

`$ ./cli`

### What is the expected behavior?

Directory removes without any errors 

### What do you see instead?

Receive and error 

```
ENOTEMPTY: Directory not empty
 syscall: “unlink”
  errno: -66
```

### Additional information

No error if you run the code using bun runtime via `bun ./cli.ts` and codes works fine and removes my folder with all files

**Comment by Jarred-Sumner** [comment]
Can you try in `bun upgrade --canary`?

**Comment by kerambit** [comment]
Yeah, on 1.0.4+17fa9378e944781319919497338db302dbec6ea0 works pretty fine 👍
I'l check it once again  after stable release and if something goes wrong - I'l reopen this issue
