### ISSUE TITLE
Chinese Document

### ISSUE THREAD

**Issue by MorleyZhou** [oven-sh/bun#6067]
### What is the problem this feature would solve?

I wrote Chinese documents with AI assistance, hoping to serve developers who use Chinese

[Chinese Document](https://github.com/Onion17/bun-chinese-doc)

### What is the feature you are proposing to solve the problem?

I hope to serve Chinese developers

**Comment by Electroid** [comment]
Thanks!

**Comment by cyfung1031** [comment]
I guess this can be added in README as a link first, then finally merge into the docs.
