### ISSUE TITLE
`setImmediate` ordering differs from Node

### ISSUE THREAD

**Issue by kerolloz** [oven-sh/bun#6069]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

- Create a **file**, copy and paste the following code. 
- Run the code using `bun` and `node.js`(v18.16.0)

```js
setImmediate(() => console.log('Immediate 0')) // callback_8

setTimeout(() => console.log('Timeout 0'), 0) // callback_4

Promise.resolve().then(() => console.log('Promise 0')) // callback_2

process.nextTick(() => console.log('Next tick 0')) // callback_0

Promise.resolve().then(() => console.log('Promise 1')) // callback_3

process.nextTick(() => console.log('Next tick 1')) // callback_1

setTimeout(() => console.log('Timeout 1'), 0) // callback_5

setImmediate(() => console.log('Immediate 1')) // callback_9

console.log('Hello world!') 
```

### What is the expected behavior? (Node.js' output) 

```
Hello world!
Next tick 0
Next tick 1
Promise 0
Promise 1
Timeout 0
Timeout 1
Immediate 0
Immediate 1
```

### What do you see instead? (Bun's output)

```
Hello world!
Next tick 0
Next tick 1
Promise 0
Promise 1
Immediate 0
Timeout 0
Timeout 1
Immediate 1
```

### Additional information

Bun is aiming to be a drop-in replacement for Node.js so it should have similar output

**Comment by liz3** [comment]
Mhh my node.js(`v18.17.1`, linux) produces this:
```
Hello world!
Promise 0
Promise 1
Next tick 0
Next tick 1
Immediate 0
Immediate 1
Timeout 0
Timeout 1
```
So im not entirely sure whether this is a platform specific difference or a version difference, would need to see what the /actual/ correct order is?

**Comment by Electroid** [comment]
Using Bun's canary build (`bun upgrade --canary`) the ordering of `setImmediate` seems to work. But technically, it looks like "Next tick" and "Promise" could be out-of-order.

```
❯ bun immediate.js
Hello world!
Next tick 0
Next tick 1
Promise 0
Promise 1
Immediate 0
Immediate 1
Timeout 0
Timeout 1
```

```
❯ node immediate.js
Hello world!
Promise 0
Promise 1
Next tick 0
Next tick 1
Immediate 0
Immediate 1
Timeout 0
Timeout 1
```

**Comment by kerolloz** [comment]
Hmmm, interesting behaviour @Electroid

**Comment by ayonli** [comment]
You should not rely on the running order of setImmediate, Bun’s event loop is not identical to Node.js’. 

Under the hood, Bun may just implement setImmediate by calling queueMicroTask, like Cloudflare, which is more common to use queueMicroTask than setImmediate, by the way.

**Comment by Jarred-Sumner** [comment]
Node.js itself is not consistent across platforms and architectures

Nowadays, we do use a separate tick queue for setImmediate different than setTimeout, queueMicrotask, and process.nextTick. So virtually all cases where this would be an issue should no longer be an issue.

If this issue is continuing to prevent you from using Bun, please leave a comment and we'll reopn
