### ISSUE TITLE
Hanging when querying to table using lib `pg` npm package

### ISSUE THREAD

**Issue by bozkayasalihx** [oven-sh/bun#6071]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

its hanging when querying to selection query on table, its not problem  about postgres , i've check it its working. 
but i dont know its just keep hanging

**Comment by Electroid** [comment]
Hi, could you provide some code so we can try to reproduce this?

**Comment by colinhacks** [comment]
I can't replicate this. @bozkayasalihx can you share a reproduction schema & script?

**Comment by bozkayasalihx** [comment]
Ok, i tried last night to check it out if problem persist but that time I changed to TLS configuration off and it worked. I assume problem caused by my side. Thanks for the great support

**Comment by gggdomi** [comment]
This is not a perfect repro, but something quite suspicious and maybe related is happening for me.

If this is verified and all "big" queries done with bun + pg are impacted, it may be a bit critical? (if it's a regression)

Bun version: `1.0.6`
pg version: `8.11.3`
OS: `macOS 13.4 (M1 Pro)`

With this pretty simple code:
```js
// query.js
import pg from 'pg'

const DATABASE_URL = "postgres://user:pass@host:5432/dbname"

const client = new pg.Client({
    connectionString: DATABASE_URL,
    ssl: { rejectUnauthorized: false },
});

await client.connect();
await client.query(`SELECT id FROM some_table LIMIT 1`); // small queries work just fine, you need to retrieve 10-100k rows to crash
console.log('🟢');
const res = await client.query(`SELECT id FROM some_table LIMIT 100000`); // <--- bun stuck here
console.log('🟢', res.rows.length);
```

`node query.js` properly exits with all the right outputs after ~100ms

`bun run query.js` slowly exhausts (~2min) all my 32GB memory and never reaches the second console.log.  
Sometimes I get a short `[1]    15055 segmentation fault  bun run query.js`. 

Sometimes a much longer stack trace:
```
 8 |   var setup = () => {
 9 |     queue = function createQueue() {
10 | 
11 |       class FixedCircularBuffer {
12 | 
13 |         constructor() {
                                         ^
RangeError: Out of memory
      at new FixedCircularBuffer (:13:38)
      at push (:41:24)
      at nextTick (:93:38)
      at enqueueError (/projectpath/node_modules/pg/lib/client.js:74:6)
      at _errorAllQueries (/projectpath/node_modules/pg/lib/client.js:80:6)
      at _handleErrorEvent (/projectpath/node_modules/pg/lib/client.js:340:4)
      at node:events:2:48
      at reportStreamError (/projectpath/node_modules/pg/lib/connection.js:58:6)
      at processTicksAndRejections (:55:76)
71 |     }
72 |     return row
73 |   }
74 | 
75 |   addRow(row) {
76 |     this.rows.push(row)
        ^
RangeError: Out of memory
      at addRow (/projectpath/node_modules/pg/lib/result.js:76:4)
      at handleDataRow (/projectpath/node_modules/pg/lib/query.js:95:6)
      at _handleDataRow (/projectpath/node_modules/pg/lib/client.js:367:4)
      at emit (node:events:122:94)
      at /projectpath/node_modules/pg/lib/connection.js:117:6
      at parse (/projectpath/node_modules/pg-protocol/dist/parser.js:40:16)
      at /projectpath/node_modules/pg-protocol/dist/index.js:11:63
      at addChunk (node:stream:1940:42)
      at readableAddChunk (node:stream:1894:58)
71 |     }
72 |     return row
73 |   }
74 | 
75 |   addRow(row) {
76 |     this.rows.push(row)
        ^


(this last error repeats dozen of times)
```
