### ISSUE TITLE
Poor performance for crypto's privateEncrypt/publicDecrypt

### ISSUE THREAD

**Issue by naijun0403** [oven-sh/bun#6076]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

You just need to run this code with node and bun.

```javascript
const crypto = require('crypto');
const fs = require('fs');

const data = 'Hello, world!';
const iterations = 1000;

const privateKeyPath = './private_key.pem';
const publicKeyPath = './public_key.pem';

function benchmarkCrypto() {
  console.log(`Benchmarking crypto performance using key files...`);
  const start = Date.now();

  for (let i = 0; i < iterations; i++) {
    const privateKey = fs.readFileSync(privateKeyPath, 'utf8');
    const publicKey = fs.readFileSync(publicKeyPath, 'utf8');

    const encrypted = crypto.privateEncrypt(privateKey, Buffer.from(data));

    const decrypted = crypto.publicDecrypt(publicKey, encrypted);
  }

  const end = Date.now();
  const duration = end - start;
  console.log(`Time taken: ${duration} ms`);
}

benchmarkCrypto();
```

### What is the expected behavior?

At least the speed should be similar to node.

### What do you see instead?

Bun is much slower than node in the RSA encryption and decryption part.

```
Benchmark 1: node test
  Time (mean ± σ):      1.013 s ±  0.015 s    [User: 0.964 s, System: 0.061 s]
  Range (min … max):    0.986 s …  1.036 s    10 runs

Benchmark 2: bun test.js
  Time (mean ± σ):     14.536 s ±  0.247 s    [User: 14.638 s, System: 0.296 s]
  Range (min … max):   14.147 s … 15.020 s    10 runs

Summary
  node test ran
   14.35 ± 0.32 times faster than bun test.js
```

### Additional information

Obviously, I also evaluated the file I/O process when benchmarking. however. This does not affect performance. Bun is slightly faster than node.

I used RSA 2048.

**Comment by Jarred-Sumner** [comment]
These are currently from the browserify polyfills which means they aren't implemented in native code and are much slower as a result. We need to make them use BoringSSL instead (as we have done for other parts of `node:crypto`)

**Comment by naijun0403** [comment]
Okay, I'll always be waiting for news

**Comment by gornostay25** [comment]
@naijun0403 @Jarred-Sumner Any updates?

**Comment by eL1x00r** [comment]
up

**Comment by tecoad** [comment]
Up
