### ISSUE TITLE
classes extending `Error` add the subclass' constructor to the stack trace

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#608]
### Version

0.1.3

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?

runnable in node, bun, browser, etc
```ts
class ExtendedError extends Error {
  constructor() {
    super('Hello World!');
  }
}

function throwThing() {
  throw new ExtendedError();
}

throwThing();
```

![image](https://user-images.githubusercontent.com/24465214/178393748-6aab8cc5-c3b3-472b-91dc-33ab8b613bc2.png)

### Additional information

May be related to #185

**Comment by Jarred-Sumner** [comment]
https://bugs.webkit.org/show_bug.cgi?id=266943
