### ISSUE TITLE
Updating dependencies that are peer-dependencies of other packages pins old version instead of using new peer

### ISSUE THREAD

**Issue by hayes** [oven-sh/bun#6085]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Basically the issue is that if you have a package `A@1` and and a package `B` that has a peer dependency on `A@*` and you update `A` to `A@2`,  `B` will get it's own copy of `A@1` rather than using the new `A@2`.  This makes updating packages that require a single copy of a package (some plugin APIs) hard to update.  

I haven't created a fully isolated reproduction, but I here's the reproduction from the upstream issue:

```sh
git clone git@github.com:Enalmada/nextjs-boilerplate.git
cd nextjs-boilerplate
# the repo may have been updated, checkout the commit that had the issue
git checkout da831f4904445e0b4227f1cb99d460c1cc4513f7
bun install
cp .env.example .env.local
# everything should be working
bun dev

# update package that is listed as a peer dependency of @pothos/plugin-with-input
bun install @pothos/core@3.37.0
# Errors because @pothos/plugin-with-input now has a nested @pothos/core@3.36.0 in its own node_modules
bun dev

# uninstall and re-install the plugin
bun remove @pothos/plugin-with-input
bun add @pothos/plugin-with-input@3.10

# working again because @pothos/plugin-with-input uses the peer version again rather than having its own copy
bun dev
```

### What is the expected behavior?

`@pothos/plugin-with-input` has a peer dependency on `@pothos/core@*`, when pothos@core is upgraded, @pothos/plugin-with-input should not be pinned to the previously installed version, and should not have it's own copy of `@pothos/core`

### What do you see instead?

```
node_modules/@pothos/core/package.json -> 3.37.0
node_modules/@pothos/plugin-with-input/node_modules/@pothos/core/package.json -> 3.36.0
```

**Comment by divmgl** [comment]
Likely related to: https://github.com/oven-sh/bun/issues/1134#issuecomment-1732421448

**Comment by Electroid** [comment]
Support for `overrides` was added in [Bun v1.0.6](https://bun.sh/blog/bun-v1.0.6#overrides-resolutions-support), which you can upgrade to by running `bun upgrade`. That should fix this issue.

If you're still running into this problem, let us know and we'll re-open to investigate.

**Comment by hayes** [comment]
That looks like a usable workaround for the issue, but I still think the underlying behavior seems incorrect.  Something listed as a peer dependency shouldn't ever be moved down as a nested dependency as the package listing it as a peer
