### ISSUE TITLE
MissingSharp: Could not find Sharp. Please install Sharp (sharp) manually into your project or migrate to another image service.

### ISSUE THREAD

**Issue by luuktimmermans** [oven-sh/bun#6087]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bunx create-astro@latest my-astro-project-using-bun` command to create a new Astro project using Bun
2. Insert an image like this:
```
---
import { Image } from 'astro:assets';
import localBirdImage from '../../images/subfolder/localBirdImage.png';
---

<Image src={localBirdImage} alt="A bird sitting on a nest of eggs."/>
```

### What is the expected behavior?

Astro should take care of showing an optimized version of the image.

### What do you see instead?

The image is not showing and the sharp error message (`MissingSharp: Could not find Sharp. Please install Sharp (sharp) manually into your project or migrate to another image service.`) is shown as a response.

**Comment by nakasyou** [comment]
I got same error.

**Comment by andrew-t-james** [comment]
I also faced this issue today.

**Comment by j0rdanR** [comment]
I also got this issue. Fixed it by switching back to pnpm and manually installing sharp if that helps, but definitely an issue with bun

**Comment by hawc** [comment]
Got the same issue. [Switched to squoosh](https://docs.astro.build/en/guides/images/#default-image-service) instead (without manually installing any dependencies), works fine now.

**Comment by RodrigoTomeES** [comment]
I have the same issue with bun 1.0.4 even installing Sharp manually

**Comment by gtrabanco** [comment]
This is related and duplicated. See #4549

**Comment by ZeldOcarina** [comment]
Same issue here, any news?

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4549, we'll fix it.

**Comment by bobgravity1** [comment]
node version on netlify for me when deploying
