### ISSUE TITLE
Support Emit Decorator Metadata for Bundler

### ISSUE THREAD

**Issue by joshunrau** [oven-sh/bun#6088]
### What is the problem this feature would solve?

Currently, `emitDecoratorMetadata` is working with the runtime. However, it fails when attempting to bundle code with `bun build`.

### What is the feature you are proposing to solve the problem?

Adding support for `emitDecoratorMetadata` in the bundler, as is already the case in the runtime.

### What alternatives have you considered?

I am currently using a plugin I wrote to transpile with `swc` before build (https://github.com/joshunrau/bun-plugin-swc). However, although this resolves this problem, it defeats one of the major benefits of using Bun (avoiding this type of thing).

**Comment by dylan-conway** [comment]
This is probably a bug you're running into because `emitDecoratorMetadata` should be working with `bun build`. Could you post the errors you're seeing?

**Comment by joshunrau** [comment]
Sure.

Here is the [project I am trying to build](https://github.com/DouglasNeuroInformatics/OpenDataCapture/tree/c669260e21e7b9dc545d0c8769499f0e60bc62cf/apps/api). The current [build script](https://github.com/DouglasNeuroInformatics/OpenDataCapture/blob/c669260e21e7b9dc545d0c8769499f0e60bc62cf/apps/api/src/build.ts) works great (`bun ./src/build.ts && NODE_ENV=development bun ./dist/main.js`). However, if I comment out the plugin (and minify for the sake of debugging, the same command fails at runtime:

```shell
❯ bun ./src/build.ts && NODE_ENV=development bun ./dist/main.js
Done!
[Nest] 41858  - 09/26/2023, 8:33:47 PM     LOG [NestFactory] Starting Nest application...
[Nest] 41858  - 09/26/2023, 8:33:47 PM     LOG [InstanceLoader] AjvModule dependencies initialized +120ms
[Nest] 41858  - 09/26/2023, 8:33:47 PM     LOG [InstanceLoader] AbilityModule dependencies initialized +1ms
[Nest] 41858  - 09/26/2023, 8:33:47 PM     LOG [InstanceLoader] MongooseModule2 dependencies initialized +0ms
[Nest] 41858  - 09/26/2023, 8:33:47 PM     LOG [InstanceLoader] ThrottlerModule2 dependencies initialized +1ms
[Nest] 41858  - 09/26/2023, 8:33:47 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthService (AbilityFactory, ?, CryptoService, Object, UsersService). Please make sure that the argument Object at index [1] is available in the AuthModule context.

Potential solutions:
- Is AuthModule a valid NestJS module?
- If Object is a provider, is it part of the current AuthModule?
- If Object is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

Error: Nest can't resolve dependencies of the AuthService (AbilityFactory, ?, CryptoService, Object, UsersService). Please make sure that the argument Object at index [1] is available in the AuthModule context.

Potential solutions:
- Is AuthModule a valid NestJS module?
- If Object is a provider, is it part of the current AuthModule?
- If Object is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

    at new RuntimeException (/Users/joshua/Developer/Work/OpenDataCapture/apps/api/dist/main.js:35758:12)
    at new UnknownDependenciesException (/Users/joshua/Developer/Work/OpenDataCapture/apps/api/dist/main.js:36925:12)
    at <anonymous> (/Users/joshua/Developer/Work/OpenDataCapture/apps/api/dist/main.js:37566:80)
```

**Comment by dylan-conway** [comment]
Thanks. I took a quick look at the build output. The bug seems to be some classes aren't bundled correctly when used in `design:paramtype`. For example, `ConfigService` and `JwtService` here need to be `config.ConfigService` and `jwt.JwtService` instead. We will have a fix soon
<img width="538" alt="Screenshot 2023-09-26 at 6 42 07 PM" src="https://github.com/oven-sh/bun/assets/35280289/8e05e9cd-73fc-4057-ab49-df7409870fa1">

**Comment by joshunrau** [comment]
Awesome, thank you. If there is anything I can do to help please let me know.
