### ISSUE TITLE
Buffer.from with "binary" encoding

### ISSUE THREAD

**Issue by SheetJSDev** [oven-sh/bun#609]
### Version

0.1.3

### Platform

Darwin mbp.home 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

```js
console.log(Buffer.from("\xa4", "binary"));
```

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

A `Uint8Array` with one element, value `0xa4 == 164`.

Node prints `<Buffer a4>` but `Uint8Array(1) [ 164 ]` would have sufficed.

### What do you see instead?

```
Uint8Array(1) [ 36 ]
```

**Comment by szatkus** [comment]
The reason is that ascii and latin1 are both truncated to 7 bits. latin1/ISO-8859-1 is a 8-bit encoding, even Node documentation specify this `This character encoding only supports the Unicode characters from U+0000 to U+00FF`.

I think I can fix it when I have some time.
