### ISSUE TITLE
bun:test not found in repl

### ISSUE THREAD

**Issue by jdalton** [oven-sh/bun#6109]
### What version of Bun is running?

v1.0.3

### What platform is your computer?

Mac OS

### What steps can reproduce the bug?

```sh
bun repl
```
```js
var t = require('bun:test')
```
Errors with
> Uncaught ResolveError: Cannot find module "bun:test

### What is the expected behavior?

The module to be resolved

### What do you see instead?

It errors.

**Comment by Jarred-Sumner** [comment]
`bun:test` is currently implemented via transpiler transform to `Bun.jest(import.meta.path)`

**Comment by marosjanco** [comment]
`bun:test` is not recognized by VS Code, although running `bun test <test-file-path>` works
![image](https://github.com/oven-sh/bun/assets/20753930/6a658310-ce86-476c-a6e6-2ce915d2611f)
