### ISSUE TITLE
Error while running prisma generate using bun dockerfile 

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#6111]
### What version of Bun is running?

latest

### What platform is your computer?

Dockerfile on railway

### Bug description

So I try to deploy my discord bot to railway.app and used a docker file for a simple web server (baojs) using dockerfile. And worked fine. But when I tried Prisma, everything crashed. Here is my Dockerfile:

```docker
# Use the offical Bun image
FROM jarredsumner/bun:edge

# Set the Docker working directory as /usr/src/app
# Copy everything from here into Docker's /usr/src/app
WORKDIR /usr/
COPY . /usr/

# Install the dependencies 
RUN bun install
RUN bun install -g prisma

# Run project
CMD bun run db:generate && bun run src/index.js
```

Then it throws this error:
![image](https://github.com/prisma/prisma/assets/77295879/039017c6-06e6-4cb9-b69e-7cbd3a77b369)

### What is the expected behavior?

Prisma schema generated and run my project

**Comment by Electroid** [comment]
This docker image is outdated: `jarredsumner/bun:edge`. Use `oven/bun:latest` intead.

**Comment by lassejlv** [comment]
Thanks that made a diff, but now I get this "error: Cannot find module ".prisma/client/index" from "/usr/node_modules/@prisma/client/index.js" Have the dockerfile not installed the packages?
