### ISSUE TITLE
http proxy agent does not work

### ISSUE THREAD

**Issue by adamcodemaker** [oven-sh/bun#6117]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

I can't use proxies.
This code works ok on node 20.6.1. It returns a proxy ip. Using Bun it returns my ip.
createConnection function from hpagent is not being used at all.

```
const http = require("https");
const { HttpsProxyAgent } = require("hpagent");

const httpsAgent = new HttpsProxyAgent({
  proxy: "http://username:password@2.1.3.7:666",
});

const options = {
  hostname: "api.ipify.org",
  path: "/?format=json",
  method: "GET",
  agent: httpsAgent,
};

// Sending the request
const req = http
  .request(options, (res) => {
    let data = "";

    res.on("data", (chunk) => {
      data += chunk;
    });

    // Ending the response
    res.on("end", () => {
      console.log("Body:", JSON.parse(data));
    });
  })
  .on("error", (err) => {
    console.log("Error: ", err);
  })
  .end();
```

### What is the expected behavior?

the response from above code should be a body with proxy ip

### What do you see instead?

the response from above code returns my ip

**Comment by faintsmi1e** [comment]
same bug for me, cant use proxy with bun

**Comment by vikasg603** [comment]
same bug for me

**Comment by nektro** [comment]
Does this still reproduce for you? This is working for me in Bun 1.1.8. (You may need to run `bun upgrade`)

**Comment by vikasg603** [comment]
> > same bug for me
> 
> Have you found any solution for it?

Used fetch with proxy.
Bug has introduced additional proxy parameter in fetch call.

**Comment by Jarred-Sumner** [comment]
> Does this still reproduce for you? This is working for me in Bun 1.1.8. (You may need to run `bun upgrade`)

The example above is not working. The correct behavior is to hang, as it hangs in Node because the provided example proxy is invalid. In Bun, it returns the current real ip address which means the connection was not proxied.

For anyone here having trouble with sending HTTP requests over a proxy in Bun, one possible workaround is to [use the `proxy` option in `fetch`](https://bun.sh/guides/http/proxy)

**Comment by vikasg603** [comment]
Hey @Jarred-Sumner I can confirm this works perfectly with the latest version of bun.
I even tried https://www.npmjs.com/package/socks-proxy-agent and this works great in both HTTP and socks proxy agents.

Thanks for the update.

**Comment by cirospaciari** [comment]
Bun now will pass the proxy argument to the internal fetch call if the https agent has a proxy property, so this works fine now.

**Comment by nektro** [comment]
fixed by https://github.com/oven-sh/bun/pull/13780
