### ISSUE TITLE
Support `banner` in `Bun.build`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6119]
I need the bundled .js file to start with a specific comment prefix for the target environment. How do I get bun's bundler to embed the comments or avoid stripping them from the source file for the entrypoint?

_Originally reported on Discord: [`Newbie bundler question`](https://discord.com/channels/876711213126520882/1156639639822684250/1156639639822684250)_

**Comment by Jarred-Sumner** [comment]
Fixed by https://github.com/oven-sh/bun/pull/14370
