### ISSUE TITLE
bunx create-next-app aborting installation

### ISSUE THREAD

**Issue by FlyingTurkman** [oven-sh/bun#6127]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Windows x64, wsl ubuntu 22

### What steps can reproduce the bug?

When I am trying to create a next app with bunx create-next-app I get an error message "error: "pidfd_open(2)" system call is not supported by your Linux kernel
To fix this error, either:"

### Additional information

Same bug for diffrent libraries for example hono and react

**Comment by Electroid** [comment]
Duplicate of #5803
