### ISSUE TITLE
Bun can't find out TypeScript error in file?

### ISSUE THREAD

**Issue by Kayxue** [oven-sh/bun#613]
### Version

0.1.3

### Platform

Microsoft Windows NT 10.0.22622.0 x64 (Windows 11)

### What steps will reproduce the bug?

Write these code:
```typescript
interface testInterface{
        hello():void
}

class w implements testInterface{

}

const obj = new w()
console.log(obj)
```
![image](https://user-images.githubusercontent.com/26020165/178429734-27442713-5e61-48b5-8d97-b6a026216ac3.png)

And call bun to run the code, the result is printed out `{ }`
![image](https://user-images.githubusercontent.com/26020165/178429960-c47219e6-193d-4c29-bf91-31b4ab3637b6.png)

### How often does it reproduce? Is there a required condition?

Always, and no required condition? I'm not sure.

### What is the expected behavior?

Print out the error like this because the class didn't implement interface:
![image](https://user-images.githubusercontent.com/26020165/178430310-80d18584-2a71-4fe9-83c9-2a58d849419a.png)

### What do you see instead?

I saw the console outputed that object but can't see any TypeScript error.

**Comment by FinnRG** [comment]
Bun doesn't actually typecheck the TypeScript code. It only transpiles it to javascript. For example, you can do something like this and run it with bun: 
```typescript
const str: string = 1
console.log(str)
```
Typechecking should be handled either by your IDE or other tools like ``tsc``.
