### ISSUE TITLE
fetch() request with GET/HEAD/OPTIONS method cannot have body

### ISSUE THREAD

**Issue by dimonnwc3** [oven-sh/bun#6144]
### What version of Bun is running?

1.0.4+387f1260c9dc0cea667b44ec0152fff0cd4def25

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

using https://github.com/sindresorhus/ky library, which is using fetch under the hood

Following code throws an error:

```
const res = await ky.post(baseURL("/api/v1/countries"), {
      json: { email: "aaaaaaa", name: "a" },
})
```

### What is the expected behavior?

it should not throw an error and send request

### What do you see instead?

```
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
code: "ERR_INVALID_ARG_VALUE"
```

### Additional information

related issue: https://github.com/sindresorhus/ky/issues/527

**Comment by liz3** [comment]
Interesting i want to look a this

**Comment by liz3** [comment]
@dimonnwc3 This seams to be a wanted behaviour, executing a get request with a body in node produces the same error.
As a result i would assume its part of the spec for fetch.
I don't think this is inherently a issue since even though the HTTP 1.1 standard can have body contents on any request method it is very untypical to send GET/HEAD/OPTIONS with a body.

**Comment by dimonnwc3** [comment]
@liz3 it supposed to be a POST request

here is a one line simplification

```
import ky from "ky"

await ky
  .post("https://httpbin.org/anything", { json: { hello: "world" } })
  .json()

```

this code works in node, but doesn't in bun

here is also test for node, which passes: https://github.com/sindresorhus/ky/issues/527#issuecomment-1739038827

**Comment by liz3** [comment]
Il check again thanks

**Comment by vinyll** [comment]
I am having this issue despite I just upgraded to Bun 1.0.4:
```
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
```

Is this coming with the next release or maybe should I compile somehow the current _main_ branch?

**Comment by liz3** [comment]
> I am having this issue despite I just upgraded to Bun 1.0.4:
> 
> ```
> TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
> ```
> 
> Is this coming with the next release or maybe should I compile somehow the current _main_ branch?

can you post example code, il have a look at it then

**Comment by vinyll** [comment]
Here's how to reproduce:

```bash
echo 'await fetch("http://localhost:3000", { body: "Hello" })' > fetchtest.ts
bun fetchtest.ts
```

The error:

```
1 | await fetch("http://localhost:3000", { body: "Hello" });
         ^
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
 code: "ERR_INVALID_ARG_VALUE"
 ```

**Comment by liz3** [comment]
> Here's how to reproduce:
> 
> 
> 
> ```bash
> 
> echo 'await fetch("http://localhost:3000", { body: "Hello" })' > fetchtest.ts
> 
> bun fetchtest.ts
> 
> ```
> 
> 
> 
> The error:
> 
> 
> 
> ```
> 
> 1 | await fetch("http://localhost:3000", { body: "Hello" });
> 
>          ^
> 
> TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
> 
>  code: "ERR_INVALID_ARG_VALUE"
> 
>  ```
> 
> 

This is supposed to fail and will fail in node too.
The bug here was that the library of the issue's op was creating Requests where the method was falsely set to GET even tho it should be post. What you are mentioning is intended behaviour.

**Comment by yamiteru** [comment]
Hey I have a use-case where I have an RPC library that uses a custom binary protocol. I generate a hash from the body and append it to the URL so it can be cached based on the body contents. This way I don't have to include base64 representation of the binary data in the URL which results in faster encoding and decoding times. I believe not allowing body in GET is way too strict especially when the spec doesn't disallow, it just says we should not use body, but doesn't say GET request cannot have body.

**Comment by kaminskypavel** [comment]
```
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
 code: "ERR_INVALID_ARG_VALUE"
 ```
still persist on 1.1.25.
