### ISSUE TITLE
Support `TOML.parse`

### ISSUE THREAD

**Issue by amytimed** [oven-sh/bun#6146]
### What is the problem this feature would solve?

No way to parse TOML strings natively

### What is the feature you are proposing to solve the problem?

I saw the https://bun.sh/guides/runtime/import-toml page and think it would be nice to be able to read TOML with `TOML.parse`, similar to `JSON.parse`

### What alternatives have you considered?

Recreating it with a function that does `import()` of TOML file

**Comment by v3nntrnx** [comment]
I like the idea, though I do not know if making TOML a global object is a great idea, i'd rather do an import like `import TOML from "bun:toml"`

**Comment by Jarred-Sumner** [comment]
Bun.TOML.parse exists

**Comment by TiBianMod** [comment]
can we add ts types for TOML, now is missing from `bun-types`

**Comment by amytimed** [comment]
is Bun.TOML documented? I had searched the docs for toml first and assumed it wasn't a feature

**Comment by juanCortelezzi** [comment]
Hey there, `Bun.TOML.parse` does exist despite the lack of documentation

```
interface TOML {
  /**
    * Parse a TOML string into a JavaScript object.
    *
    * @param {string} command The name of the executable or script
    * @param {string} options.PATH Overrides the PATH environment variable
    * @param {string} options.cwd Limits the search to a particular directory in which to searc
    */
  parse(input: string): object;
}
const TOML: TOML;
```

(This + the current issue is all the documentation I was able to find in a relatively short time.)

However it does not seem to work when trying to parse some complex strings. This is a working example of parsing something:

```typescript
// Example is taken from https://toml.io/en/v1.0.0#keys
const tomlString = `
apple.type = "fruit"
orange.type = "fruit"
`;

console.log(Bun.TOML.parse(tomlString));
```

which spits out something along the lines of:

```json
{
  apple: {
    type: "fruit",
  },
  orange: {
    type: "fruit",
  },
}
```

And this is a broken example of parsing something:

```typescript
// Example is taken from https://toml.io/en/v1.0.0#string
const tomlString = `
apple.type = "fruit"
orange.type = "fruit"
str1 = """
Roses are red
Violets are blue"""
`;

console.log(Bun.TOML.parse(tomlString));
```

which spits out something like:

```
4 | str1 = """
5 | Roses are red
6 | Violets are blue"""
7 | `;
8 |
9 | console.log(Bun.TOML.parse(tomlString));
                ^
SyntaxError: Failed to parse JSON
      at /home/wiz/Documents/programming/lemd/pad.ts:9:13
```

Keep in mind that I am using Bun version `1.1.10` in a Linux machine
