### ISSUE TITLE
Installation instructions should mention the need of restarting terminal for bun command to work

### ISSUE THREAD

**Issue by wojtekmaj** [oven-sh/bun#6148]
### What platform is your computer?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What steps can reproduce the bug?

Upon installing bun:

```
wmaj@MacBook-Air ~ % curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 

Added "~/.bun/bin" to $PATH in "~/.zshrc" 

To get started, run: 

  exec /bin/zsh 
  bun --help 
wmaj@MacBook-Air ~ % bun -v
zsh: command not found: bun
wmaj@MacBook-Air ~ % 
```

### What is the expected behavior?

Either bun command working immediately after install, or installation instructions mentioning the need of restart

### What do you see instead?

`bun --help` is suggested as an immediate next step after installation, while it will NOT work without restarting the terminal first.

**Comment by Hanaasagi** [comment]
Hi, you don't need to restart your terminal. Bun modifies zsh config during installation, so you just need to run a command like `exec zsh` to reload. Just as mentioned in the console output.

```
To get started, run: 

  exec /bin/zsh 
  bun --help 
```

**Comment by wojtekmaj** [comment]
🤦
