### ISSUE TITLE
Response FileBlob.slice() return full file

### ISSUE THREAD

**Issue by gornostay25** [oven-sh/bun#616]
@Jarred-Sumner 
if I return a slice, I will receive a full file
```
return new Response(Bun.file(data.abs).slice(opts.start, opts.end), {
            headers: data.headers,
            status: code
})
```
So I try to return an arrayBuffer
```
return new Promise((rs) => {
    Bun.file(data.abs).slice(opts.start, opts.end).arrayBuffer().then(arbf => {
        rs(
            new Response(arbf, {
                headers: data.headers,
                status: code
            })
        )
    })
})
```
It's work, but in docs slice return `FileBlob` (`slice(begin?: number, end?: number): FileBlob;`)
And Response constructor receive FileBlob **NOT arrayBuffer **
```
declare class Response implements BlobInterface {
  constructor(body: BlobPart | BlobPart[], options?: ResponseInit);
```

_Originally posted by @gornostay25 in https://github.com/oven-sh/bun/issues/589#issuecomment-1180887894_

**Comment by Electroid** [comment]
Hi @gornostay25, thanks for submitting this bug report. If you have time, do you mind providing an example that we can run to observe the issue? I tried to piece together what you provided but I don't think there's enough context.

**Comment by gornostay25** [comment]
Hi @Electroid, check this file https://github.com/gornostay25/svelte-adapter-bun/blob/3c218a4a7728da96b0676fe3ecc3b3cbdd66ed26/src/sirv.js

**Comment by Jarred-Sumner** [comment]
In the HTTP server (Bun.serve) right? If so, HTTP or HTTPS?

**Comment by gornostay25** [comment]
https://github.com/gornostay25/svelte-adapter-bun/blob/3c218a4a7728da96b0676fe3ecc3b3cbdd66ed26/src/sirv.js#L88-L96

function return promise to Bun.serve hendler
>HTTP

**Comment by Jarred-Sumner** [comment]
Is the workaround calling .arrayBuffer() or is that intentional? If it’s not intentional, could you try directly passing

```js
new Response(Bun.file(data.abs).slice(opts.start, opts.end), { headers: data.headers, status: code })
```

**Comment by gornostay25** [comment]
I don't know is it working now, but early it doesn't

**Comment by Lucifer1662** [comment]
Should these [lines](https://github.com/oven-sh/bun/blob/a41150836a39868284bba70ad3d061730511a4c0/src/bun.js/webcore/response.zig#L2583) contain this.offset?
Otherwise sendfile/splice/copy_file_range will send from the begging of the src, which will ignore the .slice operation on the blob.
As both ReadFile and WriteFile classes use the offset, which would explain why .arrayBuffer() would work.

**Comment by gornostay25** [comment]
Fixed. https://github.com/oven-sh/bun#streaming-files-with-bunserve
