### ISSUE TITLE
regression: http `serve` performance on macOS Sonoma

### ISSUE THREAD

**Issue by simylein** [oven-sh/bun#6169]
### What version of Bun is running?

1.0.4+6afa78120ac0512bc55d00a8a1562d8f0eafa2c2

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

run with `bun server.ts`

```ts
import { serve } from 'bun';

serve({
	port: 4000,
	fetch(request, server) {
		return new Response('hello world');
	},
});
```

and `http_load_test`

### What is the expected behavior?

I can remember getting somewhere in the neighbourhood of 180k Requests/second on macOS Ventura

### What do you see instead?

```
Req/sec: 56779.000000
Req/sec: 57083.750000
Req/sec: 57457.000000
Req/sec: 57228.500000
Req/sec: 57312.000000
Req/sec: 57526.750000
Req/sec: 56920.500000
Req/sec: 57479.000000
Req/sec: 57584.250000
Req/sec: 57283.000000
```

### Additional information

Is this a screw up of macOS or rather bun?

**Comment by Jarred-Sumner** [comment]
Why closed?

**Comment by simylein** [comment]
Because I screwed up, there is no regression, I am sorry (I tested with parallel connections 1 vs 20 and not 20 on both)
