### ISSUE TITLE
Change bun node runtime version?

### ISSUE THREAD

**Issue by solonifer** [oven-sh/bun#6171]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.0-1040-oracle aarch64 aarch64

### What steps can reproduce the bug?

version.js file to check version
`console.log(process.version);`

running: node version.js
`v18.17.1`
running: bun run version.js
`v18.15.0`

### What is the expected behavior?

Output:
v18.17.1

### What do you see instead?

Output:
v18.15.0

### Additional information

I have a library that fails to run on node 18.15.0, so I cannot use bun in this project :(

**Comment by Electroid** [comment]
Fixed by #6158
