### ISSUE TITLE
Illegal Instruction on Intel Atom C2338

### ISSUE THREAD

**Issue by mbaroukhcw** [oven-sh/bun#6174]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 6.1.0-12-amd64 x86_64 unknow

### What steps can reproduce the bug?

just run bun on this cpu

### What is the expected behavior?

$ bun --revision
1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What do you see instead?

$ bun --revision
Illegal instruction

### Additional information

It is this CPU: 
https://ark.intel.com/content/www/fr/fr/ark/products/77976/intel-atom-processor-c2338-1m-cache-1-70-ghz.html

It is from end of 2013.  
Don't know if it should be supported, but from what I see in other issues, some older cpus are.

If needed I can run any command to diagnostic or I can give somebody access to a machine with it (it is online)

**Comment by Electroid** [comment]
It is unlikely we will support much older CPUs.
