### ISSUE TITLE
directory not empty, syscall unlink errno -66

### ISSUE THREAD

**Issue by andrewberth** [oven-sh/bun#6175]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

```
import { emptyDir } from 'fs-extra'
await emptyDir('<some non-empty directory>')
```

### What is the expected behavior?

the directory is empty

### What do you see instead?

ENOTEMPTY: Directory not empty
 syscall: "unlink"
   errno: -66

### Additional information

this works in node, but fails with bun. unless i'm mistaken, fs-extra uses calls to fs.rm under the hood.

**Comment by dylan-conway** [comment]
Fixed in bun v1.0.4, most likely with #6001
