### ISSUE TITLE
github url not found 

### ISSUE THREAD

**Issue by udinesia325** [oven-sh/bun#618]
### Affected URL(s)

curl https://bun.sh/install | bash

### Description of the problem

why does my curl always return a 404 response

**Comment by FinnRG** [comment]
@udinesia325  Could you please paste the output of ``uname -a``?

**Comment by Arielgordon123** [comment]
```
$ curl -fsSL https://bun.sh/install | bash
curl: (22) The requested URL returned error: 404

error: Failed to download bun from https://github.com/Jarred-Sumner/bun-releases-for-updater/releases/latest/download/bun-linux-aarch64.zip
```

uname -a output:
```
Linux deaa4d6a337a 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by FinnRG** [comment]
The ``aarch64`` platform is currently not supported. See #75 for further information.

**Comment by udinesia325** [comment]
This is my uname -a
Linux localhost 3.18.31-perf-gf2fd6b0 #1 SMP PREEMPT Wed Jun 5 18:40:35 WIB
2019 aarch64 Android

Pada tanggal Sel, 12 Jul 2022 16.51, Finn R. Gärtner <
***@***.***> menulis:
