### ISSUE TITLE
WebSocket error with ethers.js getTransaction()

### ISSUE THREAD

**Issue by farizrifqi** [oven-sh/bun#6189]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64 & Linux 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What steps can reproduce the bug?

**Install required dependency**
```bun install ethers```

Simple code:
```js
import { ethers } from "ethers"

const provider = new ethers.WebSocketProvider("WSS_URL");

(async() => {
    provider.on("pending", async (rawTx) => {
        if(!rawTx) return;
        const tx = await provider.getTransaction(rawTx)
        console.log(tx)
    })
})()
```

error while getting ethereum transaction on `getTransaction()`, which the console said the error exactly at [_processMessage()](https://github.com/ethers-io/ethers.js/blob/main/lib.esm/providers/provider-socket.js#L240).

...............
**BUT**
...............
It works while using RPC Node
```js
import { ethers } from "ethers"

const provider = new ethers.JsonRpcProvider("RPC_URL");

(async() => {
    provider.on("pending", async (rawTx) => {
        if(!rawTx) return;
        const tx = await provider.getTransaction(rawTx)
        console.log(tx)
    })
})()
```

### What is the expected behavior?

With nodejs and npm it is working as expected

[TransactionResponse](https://docs.ethers.org/v6/api/providers/#TransactionResponse) (ethers.js v6)
![https://cdn.discordapp.com/attachments/831620169011953714/1157452585557565490/image.png?ex=6518a938&is=651757b8&hm=7668bc4d8958c797e819763a3142a0f358bf006ee4a7faf306bb14c9042df639&](https://cdn.discordapp.com/attachments/831620169011953714/1157452585557565490/image.png?ex=6518a938&is=651757b8&hm=7668bc4d8958c797e819763a3142a0f358bf006ee4a7faf306bb14c9042df639&)

### What do you see instead?

```
236 |     /**
237 |      *  Sub-classes **must** call this with messages received over their
238 |      *  transport to be processed and dispatched.
239 |      */
240 |     async _processMessage(message) {
241 |         const result = (JSON.parse(message));
                           ^
SyntaxError: JSON Parse error: Unterminated string
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:241:24
      at _processMessage (/home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:240:26)
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:12
236 |     /**
237 |      *  Sub-classes **must** call this with messages received over their
238 |      *  transport to be processed and dispatched.
239 |      */
240 |     async _processMessage(message) {
241 |         const result = (JSON.parse(message));
                           ^
SyntaxError: JSON Parse error: Unable to parse JSON string
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:241:24
      at _processMessage (/home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:240:26)
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:12
236 |     /**
237 |      *  Sub-classes **must** call this with messages received over their
238 |      *  transport to be processed and dispatched.
239 |      */
240 |     async _processMessage(message) {
241 |         const result = (JSON.parse(message));
                           ^
SyntaxError: JSON Parse error: Unable to parse JSON string
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:241:24
      at _processMessage (/home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:240:26)
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:12
236 |     /**
237 |      *  Sub-classes **must** call this with messages received over their
238 |      *  transport to be processed and dispatched.
239 |      */
240 |     async _processMessage(message) {
241 |         const result = (JSON.parse(message));
                           ^
SyntaxError: JSON Parse error: Unexpected identifier "dc57600080fd5b50565b600080604083850312156111f257600080fd5b82356111fd816111c7565b946020939093013593505050565b60008060006060848603121561122057600080fd5b833561122b816111c7565b9250602084013561123b816111c7..."
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:241:24
      at _processMessage (/home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-socket.js:240:26)
      at /home/zeraubuntu/lastCoinCheck/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:12
```

**Comment by Spomsoree** [comment]
I can confirm that this happens and must be related to bun.
The same code works without bun.

I don't even have to start a subscriber, `new ethers.WebSocketProvider(WS_PROVIDER);` is enough to reproduce the error (after about 20-30 seconds, 19-20 blocks).

It does not happen with all nodes, but its 100% reproducible with quicknode.

Might be a combination of the websocket implementation and the web3 node.

```
import { ethers } from 'ethers';

let counter = 0;
const test  = new ethers.WebSocketProvider(QUICKNODE_WS_URL);

await test
    .on('block', () => {
        counter++;
        console.log('COUNTER', counter);
    })
;
```

It will crash as soon as the counter is about to hit 19. The same crash happens without the subscriber too.

I do get this error before the errors above are printed:

```
236 |     /**
237 |      *  Sub-classes **must** call this with messages received over their
238 |      *  transport to be processed and dispatched.
239 |      */
240 |     async _processMessage(message) {
241 |         const result = (JSON.parse(message));
                           ^
SyntaxError: JSON Parse error: Unexpected identifier "continuation"
```

The message tried to be parsed: `continuation after FIN`

**Comment by farizrifqi** [comment]
> I can confirm that this happens and must be related to bun. The same code works without bun.
> 
> I don't even have to start a subscriber, `new ethers.WebSocketProvider(WS_PROVIDER);` is enough to reproduce the error (after about 20-30 seconds, 19-20 blocks).
> 
> It does not happen with all nodes, but its 100% reproducible with quicknode.
> 
> Might be a combination of the websocket implementation and the web3 node.
> 
> ```
> import { ethers } from 'ethers';
> 
> let counter = 0;
> const test  = new ethers.WebSocketProvider(QUICKNODE_WS_URL);
> 
> await test
>     .on('block', () => {
>         counter++;
>         console.log('COUNTER', counter);
>     })
> ;
> ```
> 
> It will crash as soon as the counter is about to hit 19. The same crash happens without the subscriber too.
> 
> I do get this error before the errors above are printed:
> 
> ```
> 236 |     /**
> 237 |      *  Sub-classes **must** call this with messages received over their
> 238 |      *  transport to be processed and dispatched.
> 239 |      */
> 240 |     async _processMessage(message) {
> 241 |         const result = (JSON.parse(message));
>                            ^
> SyntaxError: JSON Parse error: Unexpected identifier "continuation"
> ```
> 
> The message tried to be parsed: `continuation after FIN`

I've just tried reproduced my error which `Provider.getTransaction()`, fortunately, it works. Then I tried to subscribe to block using using quicknode and chainstack node, the error occur after the quicknode counter hit 6.

My code.
```js
import { ethers } from 'ethers';

const chainstackProvider  = new ethers.WebSocketProvider("CHAINSTACK_WS_URL");
const quicknodeProvider  = new ethers.WebSocketProvider("QUICKNODE_WS_URL");

(async() => {
    let counterCS = 0;
    let counterQN = 0;
    await chainstackProvider.on('block', () => {
        counterCS++;
        console.log('Chainstack', counterCS);
    })
    await quicknodeProvider.on('block', () => {
        counterQN ++;
        console.log('Quicknode', counterQN );
    })
})()
```

Result:
![img](https://cdn.discordapp.com/attachments/1022111390896492606/1157883529485623296/image.png?ex=651a3a91&is=6518e911&hm=ca8febc80faf94f8e5173bfc85792344533c91819597cf3acb3836226a799a1d&)

**Comment by Spomsoree** [comment]
Is chainstack working? I'm hesitant giving them my details to test it.
The quicknode support was not very helpful, but that was before I figured out that this is bun related.

**Comment by farizrifqi** [comment]
Work for me if it just subscribing pending txs or block.

> Is chainstack working? I'm hesitant giving them my details to test it. The quicknode support was not very helpful, but that was before I figured out that this is bun related.

**Comment by Electroid** [comment]
This likely a result of a WebSocket bug in Bun.

**Comment by unsphere** [comment]
Encountered the same issue with viem, before I found the post here. The subscription body comes in chunks.
[https://github.com/wagmi-dev/viem/issues/1322](https://github.com/wagmi-dev/viem/issues/1322)

**Comment by andreluis-oliveira** [comment]
Had the same issue too.

**Comment by Electroid** [comment]
We need to test our WebSocket client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: https://github.com/oven-sh/bun/issues/6686

**Comment by icex** [comment]
This happens in Viem too. We've tried multiple WS nodes. This is a dealbreaker for us to upgrade to bun.

**Comment by ph1losof** [comment]
still an issue for me when using ethers v6 and bun v1.0.29 I just subscribed to Mempool like this: 

```
wsProvider.on("pending", (tx) => {
  wsProvider.getTransaction(tx).then(async (transaction) => {
```

```
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
249 |     /**
250 |      *  Sub-classes **must** call this with messages received over their
251 |      *  transport to be processed and dispatched.
252 |      */
253 |     async _processMessage(message) {
254 |         const result = (JSON.parse(message));
                              ^
SyntaxError: JSON Parse error: Unexpected identifier "too"
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:254:25
      at _processMessage (/Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:253:27)
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
```
