### ISSUE TITLE
bun create cannot work properly with a package with scope.

### ISSUE THREAD

**Issue by ATQQ** [oven-sh/bun#6209]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

```sh
bun create @sugarat/theme
```

![image](https://github.com/oven-sh/bun/assets/42485491/1dbd6ab0-9e43-4ecc-8ad5-551c4342f76d)

### What is the expected behavior?

```sh
bunx @sugarat/create-theme
```

### What do you see instead?

error: package "@sugaratcreate-/theme" not found

**Comment by Hanaasagi** [comment]
Might have been fixed by https://github.com/oven-sh/bun/pull/5716. Canary build did not reproduce this problem. Please try `bun upgrade --canary` or wait for the 1.0.4 release.

**Comment by ATQQ** [comment]
> Might have been fixed by #5716. Canary build did not reproduce this problem. Please try `bun upgrade --canary` or wait for the 1.0.4 release.

Thanks 👍🏻
