### ISSUE TITLE
`--bun` option before `create` command crashes while `--bun` after `create` works fine

### ISSUE THREAD

**Issue by mxndtaylor** [oven-sh/bun#6215]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I'm using `quasar` as the template, but it's not actually relevant to the error, only the expected outcome. 
Run this in your terminal:
```bash
docker run -it oven/bun bun --bun create quasar
```

### What is the expected behavior?

Output should be like the `bun create --bun quasar` command:
```bash
$ docker run -it oven/bun bun create --bun quasar

 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

? What would you like to build? › - Use arrow-keys. Return to submit.
❯   App with Quasar CLI, let's go!
    spa/pwa/ssr/bex/electron/capacitor/cordova
    AppExtension (AE) for Quasar CLI
    Quasar UI kit

```

### What do you see instead?

Instead I see `TypeError` is thrown from the `fs-extra` module:

```bash
$  docker run -it oven/bun bun --bun create quasar
11 |         }
12 |         arguments.length++
13 |         fn.apply(this, arguments)
14 |       })
15 |     }
16 |   }, 'name', { value: fn.name })
                          ^
TypeError: undefined is not an object (evaluating 'fn.name')
      at /tmp/create-create@latest--bunx/node_modules/universalify/index.js:16:22
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:49:20
      at forEach (:1:20)
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:48:0
      at globalThis (/tmp/create-create@latest--bunx/node_modules/fs-extra/lib/fs/index.js:60:3)
      at require (:1:20)
      at /tmp/create-create@latest--bunx/node_modules/fs-extra/lib/index.js:8:7
      at globalThis (/tmp/create-create@latest--bunx/node_modules/fs-extra/lib/index.js:22:17)
```

### Additional information

Additional platform info, I'm on Ubuntu's official WSL2 distribution:
```bash
$  cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

I'm using docker desktop as the container runtime.

> [!NOTE]
> the following fails in the same way - `bun --bun create` which makes me thing the `create` command is not being processed at all.

`bun --bun run ..` and `bun run --bun` are equivalent, so my expectation was that `create` would be the same. I haven't checked the other commands, but the same issue might be there as well for all I know.

I apologize if this is previously reported or discussed, I couldn't see anything for it when I was looking though.

**Comment by Electroid** [comment]
This is likely an issue with Bun and `fs-extra`.

**Comment by mxndtaylor** [comment]
This is not an error from using `bun` with `quasar`, I only included it as it's what I was doing, and as an example of the command working when `--bun` is after `create`

The minimal reproduction of this error can be done _without referencing any creation template_:
```bash
bun --bun create
```

**Comment by paperclover** [comment]
`bun --bun create` currently trips a debug assertion (release segfault). and is motiviating me to rebuild the bun's command line internals because such a crash should not be possible.
