### ISSUE TITLE
Bun watcher should watch custom extensions too.

### ISSUE THREAD

**Issue by fdserr** [oven-sh/bun#6216]
### What is the problem this feature would solve?

The plugin / custom loader thing is great, but the .<any> file changes aren't picked up.

### What is the feature you are proposing to solve the problem?

Assume `.cogs` files have a plugin / loader that works. We understand that bun's watcher cannot guess about the filter in the plugin. But it'd be awesome to be able to `bun --hot .cogs,.any. index.cogs`, or the like, and have the watcher ding and let the loader do its job on those files too. And a bunfig key wouldn't hurt^

### What alternatives have you considered?

Using the API (thanks guys!) I can certainly build a custom pipeline watch/build. But then I need to build to file for each refresh and load that, manually (even though bun exposes nice module resolution tools).

**Comment by Electroid** [comment]
We'll likely need to support esbuild's `watchFiles` and `watchDirs`, so plugins can register what to watch.

**Comment by paperclover** [comment]
Duplicate of #4689
