### ISSUE TITLE
`String.raw` produces incorrect output

### ISSUE THREAD

**Issue by tomaskallup** [oven-sh/bun#622]
### Version

0.1.3

### Platform

Linux malus 5.17.15-1-MANJARO #1 SMP PREEMPT Wed Jun 15 07:09:31 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

Create a file with following contents:
```js
const regex = new RegExp(String.raw`(sig|signature|AWSAccessKeyId|password|passcode)=(\?P<secret>[a-z0-9%/+]{16,})`, 'gi');
console.log(regex.test('asdf'));
```
Run it with `bun run file.js`

### How often does it reproduce? Is there a required condition?

It happens every time, the code snippet is from snowflake sdk and it looks like the `=(\?` is the problem.

### What is the expected behavior?

It should be able to parse the regex (altough it seems wierd, my guess is that the last part is supposed to be something like `(?<secret>`, but node parses it correctly and it works), same as `node file.js`:
```console
$ node file.js
true
```

### What do you see instead?

```console
$ bun run test.ts
1 | const regex = new RegExp(String.raw`(sig|signature|AWSAccessKeyId|password|passcode)=(?P<secret>[a-z0-9%/+]{16,})`, "gi");
                 ^
 SyntaxError: Invalid regular expression: unrecognized character after (?
      at ./test.ts:1:14
```

**Comment by mikrosystheme** [comment]
There must be something wrong with `String.raw`. Minimal reproduction of the bug:

```js
console.assert(String.raw`\?`.length === 2) // 1 in Bun.
```

**Comment by tomaskallup** [comment]
So it's a bug in `JavaScriptCore`? Should I report it there?

**Comment by mikrosystheme** [comment]
No, it's not. JSC works fine. The bug is in Bun.

**Comment by Electroid** [comment]
Thanks for submitting the report, indeed this is an issue with `String.raw`. We'll work on getting it fixed!

**Comment by paperclover** [comment]
whenever this gets fixed, we need to not skip the `edgecase/TemplateStringIssue622` test case in [this file](https://github.com/oven-sh/bun/blob/main/test/bundler/bundler_edgecase.test.ts)
