### ISSUE TITLE
Error in Makefile Execution

### ISSUE THREAD

**Issue by TaduJR** [oven-sh/bun#6220]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

"make setup" command in bun repo

### What do you see instead?

/home/tadujr/.bun/bin/bun install
bun install v1.0.3 (25e69c71)
: invalid option namesh: line 2: set: pipefail

Checked 182 installs across 193 packages (no changes) [128.00ms]
make: *** [Makefile:533: npm-install-dev] Error 2

**Comment by TaduJR** [comment]
The error , ":invalid option namesh: line 2: set: pipefail", is occurring because of an issue with the set command. The set command in the script is trying to enable several options (-euxo pipefail), but it seems like my system's shell does not support the pipefail option.

The -e, -u, and -x options are commonly supported in most Unix-like shells, but pipefail is not a standard option in some shells, especially older ones.

Option 1: Remove the pipefail Option
Option 2: Using a Compatible Shell

Note: This Error is caused by .scripts/post-install.sh on line 2

**Comment by Jarred-Sumner** [comment]
I suggest updating to a more recent version of bash and a more recent version of Linux
