### ISSUE TITLE
TLS authorization incorrectly rejecting trusted certificates with MQTT.js

### ISSUE THREAD

**Issue by gnattu** [oven-sh/bun#6232]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Get a sever with a certificate signed by a trusted CA, for testing purpose, you can use a public mqtt broker like [this one](https://www.emqx.com/en/mqtt/public-mqtt5-broker)
Then simply do something like below:

```js
import * as mqtt from 'mqtt'
const clientId = `mqtt_${Math.random().toString(16).slice(3)}`

const client = mqtt.connect(connectUrl, {
  clientId,
  clean: false,
  protocolVersion: 5,
  connectTimeout: 4000,
  username: mqttUser,
  password: mqttToken,
})

client.on('connect', () => {
  console.log('Connected')
  client.subscribe([topic], { qos: 2 }, () => {
    console.log(`Subscribe to topic '${topic}'`)
  })
})
client.on('error', (e) => {
  console.log(e)
})
```

If we use bun to run this code, we will get `error: TLS not authorized` even though with manually supply a ca by setting it in the connect config. The only way to get it connected is to set `rejectUnauthorized: false`.

However, if we use nodejs, we will see the connection succeed from the console log.

### What is the expected behavior?

The behavior should be same to Nodejs, if we do have a valid certificate then we should not get our TLS connection being rejected.

### What do you see instead?

The TLS connection is rejected even with a manual supplied CA cert.

**Comment by ad84** [comment]
Bun Version - 1.0.5
Computer platform - Windows 11 x64 - WSL2 ( running Ubuntu 22.04) 

Otherwise,  I'm having exactly the same issue as @gnattu, which I've also worked around in the same way.

**Comment by zsnmwy** [comment]
Bun Version - 1.0.23
Platform - MacOS

I have the same issue.
Any resolve to fix it?

**Comment by vaaski** [comment]
Probably unrelated, but for me MQTT doesn't connect at all. I'm trying to connect to my Bambulab A1 printer.

```ts
// src/index.ts

const client = mqtt.connect("mqtts://<ip>:8883", {
	username: "bblp",
	password: "0123456789",
	reconnectPeriod: 30,
	rejectUnauthorized: false,
})

console.log("connecting")
client.on("connect", () => {
	console.log("connected")
})
```

Running this with `bun run src/index.ts` will never log "connected" while running `bunx tsx src/index.ts` works.

**Comment by Frtrillo** [comment]
Still have this issue.
Running it with node runs just fine.
On bun you get:

`
TLS not authorized
17 |     delete opts.path;
18 |     debug('port %d host %s rejectUnauthorized %b', opts.port, opts.host, opts.rejectUnauthorized);
19 |     const connection = tls_1.default.connect(opts);
20 |     connection.on('secureConnect', () => {
21 |         if (opts.rejectUnauthorized && !connection.authorized) {
22 |             connection.emit('error', new Error('TLS not authorized'));
                                         ^
error: TLS not authorized

node_modules/mqtt/build/lib/connect/tls.js:22:37
      at handshake (node:net:80:26)

`

Unless you set       rejectUnauthorized: false

**Comment by cirospaciari** [comment]
Did some tests and still did not find anything conclusive.

The code bellow runs fine in node or bun since the cert is recognize by the root certs (node and bun uses the same source for the root certs)
And in the cases of self-signed certs `rejectUnauthorized: false`, `ca: cert`, `NODE_EXTRA_CA_CERTS` works as expected.

with well know cert:
```js
const mqtt = require("mqtt");
const client = mqtt.connect("mqtts://test.mosquitto.org:8886");

client.on("error", console.error);
client.on("connect", () => {
    client.subscribe("presence");
});

client.on("message", (topic, message) => {
  // message is Buffer
  console.log(message.toString());
  client.end();
});
```
with ca args:

```js
const mqtt = require("mqtt");
const path = require("path");
const cert = path.join(__dirname, "mosquitto.org.crt");
const fs = require("fs");
const client = mqtt.connect("mqtts://test.mosquitto.org:8883", {
  // rejectUnauthorized: false,
  ca: fs.readFileSync(cert).toString("utf8"),
});

client.on("error", console.error);
client.on("connect", () => {
  client.subscribe("presence");
});

client.on("message", (topic, message) => {
  // message is Buffer
  console.log(message.toString());
  client.end();
});
```

![Image](https://github.com/user-attachments/assets/fa24d249-02be-40ca-a109-1ae919c23c3c)

**Comment by Frtrillo** [comment]
> Did some tests and still did not find anything conclusive.
> 
> The code bellow runs fine in node or bun since the cert is recognize by the root certs (node and bun uses the same source for the root certs) And in the cases of self-signed certs `rejectUnauthorized: false`, `ca: cert`, `NODE_EXTRA_CA_CERTS` works as expected.
> 
> with Lets Encrypt certificate:
> 
> const mqtt = require("mqtt");
> const client = mqtt.connect("mqtts://test.mosquitto.org:8886");
> 
> client.on("error", console.error);
> client.on("connect", () => {
>     client.subscribe("presence");
> });
> 
> client.on("message", (topic, message) => {
>   // message is Buffer
>   console.log(message.toString());
>   client.end();
> });
> with ca argument or `rejectUnauthorized: false`:
> 
> const mqtt = require("mqtt");
> const path = require("path");
> const cert = path.join(__dirname, "mosquitto.org.crt");
> const fs = require("fs");
> const client = mqtt.connect("mqtts://test.mosquitto.org:8883", {
>   // rejectUnauthorized: false,
>   ca: fs.readFileSync(cert).toString("utf8"),
> });
> 
> client.on("error", console.error);
> client.on("connect", () => {
>   client.subscribe("presence");
> });
> 
> client.on("message", (topic, message) => {
>   // message is Buffer
>   console.log(message.toString());
>   client.end();
> });
> ![Image](https://github.com/user-attachments/assets/fa24d249-02be-40ca-a109-1ae919c23c3c)
> 
> One thing that may help is that if `host` is not provided when connecting via IP `ERR_TLS_CERT_ALTNAME_INVALID` is a possibility if the cert don't have the specific IP on it.
> 
> I tested using `mqtt@5.10.2` `bun v1.1.34` and `node v22.10.0`

Thanks for your answer. If I can provide some extra info to help, this is how I connect to my mqtt broker. Here’s the setup I use to connect to my MQTT broker. The domain certificates for my broker are generated using AWS Route 53.

```

    const options: mqtt.IClientOptions = {
      clientId: this.generateUniqueClientId(),
      username,
      password,
      protocol: 'mqtts',
      port: 8883,
      rejectUnauthorized: true,
      keepalive: 15,
      reconnectPeriod: 5000,
      clean: true,
    };

    this.client = mqtt.connect(brokerUrl, options);
```

This configuration works perfectly when using Node.js. However, when running the same code with Bun, I encounter the error mentioned in my previous comment. The only way I can get it to work in Bun is by setting rejectUnauthorized: false.

**Comment by cirospaciari** [comment]
@Frtrillo can you inform what `bun --revision` and also the `node --version` outputs? both uses the same root certs from Mozilla, you can also try to set the `NODE_EXTRA_CA_CERTS` in this cases to see if you got authorized.

**Comment by Frtrillo** [comment]
@cirospaciari ok after upgrading bun to v1.1.37 (from 1.0.6), it worked fine just like nodejs

**Comment by cirospaciari** [comment]
I could not find anything causing this Issue on the latest `v1.1.37` if someone is still encountering this, please reopen with a repro.
