### ISSUE TITLE
Bun hangs when trying to `fetch` from a HTTP server via HTTPS

### ISSUE THREAD

**Issue by TheLastZombie** [oven-sh/bun#6233]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

Create an `index.mjs` file with the following content:

```JavaScript
import { createServer } from "http";

const server = createServer((req, res) => res.end());
server.listen();

await fetch(`https://127.0.0.1:${server.address().port}`);

server.close();
```

Then run it with `bun index.mjs`.

### What is the expected behavior?

I expected Bun to throw an error, similar to what Node.js does. When running `node index.mjs` instead, I get the following output:

```
node:internal/deps/undici/undici:13220
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:13220:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///tmp/index.mjs:6:1 {
  cause: [Error: 00C868972A7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}

Node.js v20.8.0
```

### What do you see instead?

Bun appears to hang. There is no console output, and the process doesn't exit.

### Additional information

When replacing `https` with `http` in the provided script, like this...

```JavaScript
await fetch(`http://127.0.0.1:${server.address().port}`);
```

...everything works as expected.

**Comment by zomchak-code** [comment]
I'm also experiencing this, this looks like super critical issue, is this getting addressed in any way?

**Comment by gvilums** [comment]
Still happens in Bun 1.1.7

**Comment by cirospaciari** [comment]
This was fixed on https://github.com/oven-sh/bun/pull/15452/files#diff-9bdd42b0ef4b7ab715ef31aab6b8fe32578f5c7948774591bf46ff3aa5aec091R812-R815
