### ISSUE TITLE
`Bad file descriptor` when running `make setup` on linux-aarch64

### ISSUE THREAD

**Issue by cornedor** [oven-sh/bun#6234]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

and

1.0.4+ea956e58e9bac03b30d56ff74070603080913023

### What platform is your computer?

Linux 6.2.0-33-generic aarch64 aarch64

### What steps can reproduce the bug?

1. On a M2 MacOS I started a VIM using limactl (Ubuntu 23.04 on QEMU).
2. Follow steps on https://bun.sh/docs/project/development
3. Run make setup

### What is the expected behavior?

Setup succeeds.

### What do you see instead?

```
NODE_ENV=production bun src/js/_codegen/index.ts
Scan internal registry (3ms)
158 |     if (!exportOptimization) {
159 |       fileToTranspile = `var $;` + fileToTranspile.replaceAll("__intrinsic__exports", "$");
160 |     }
161 |     const outputPath = path.join(TMP, moduleList[i].slice(0, -3) + ".ts");
162 |     fs.mkdirSync(path.dirname(outputPath), { recursive: true });
163 |     fs.writeFileSync(outputPath, fileToTranspile);
        ^
EBADF: Bad file descriptor
    fd: "-2"
 syscall: "write"
   errno: -9

      at /home/corne.linux/bun/src/js/_codegen/build-modules.ts:163:4

While processing: bun/ffi.ts
make[3]: *** [Makefile:560: js] Error 1
make[3]: Leaving directory '/home/corne.linux/bun'
make[2]: *** [Makefile:1931: cpp-no-link] Error 2
make[2]: *** Waiting for unfinished jobs....
Build linux-aarch64 v6.2.0 - v6.2.0 (generic)
Output: ../packages/debug-bun-linux-aarch64/bun-debug

make[3]: Leaving directory '/home/corne.linux/bun'
make[2]: Leaving directory '/home/corne.linux/bun'
make[1]: *** [Makefile:1944: dev] Error 2
make[1]: Leaving directory '/home/corne.linux/bun'
make: *** [Makefile:1949: setup] Error 2

```

Edit: Also tested using a very recent build from CI/CD and Debian GNU/Linux 12 (bookworm), this setup throws the same error.

**Comment by jumoog** [comment]
know issue #4627 `fs.mkdirSync` siliently fails on ARM64

**Comment by cornedor** [comment]
For other people comming here, for a workaround you could edit `src/js/_codegen/build-modules.ts` and replace mydirSync call with execSync at lines 162 and 158 with:

```
      // fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      require('child_process').execSync(`mkdir -p ${path.dirname(outputPath)}`)
```
