### ISSUE TITLE
bun cache folder gets created inside project's folder (and bun ignores any attempt to change it)

### ISSUE THREAD

**Issue by tvardy** [oven-sh/bun#6237]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

After using `bun install` in my current site project I noticed that a folder structure of `~/.bun/install/cache` was being created inside my project's folder.
It looks like a bug that bun (or system) does not treat the tilde (`~`) as an alias for my user folder. There is also the same structure in my real home folder, but the `cache` folder there always stays empty.

I tried overriding the cache dir setting (to `$HOME/.bun/install/cache`)... either with the `--cache-dir` flag or with (global or local or both) `bunfig.toml` (also tried `.bunfig.toml`) file. I even tried the `-c` and `--config` to point to the config file I wanted.

With no success :( The `~` folder and its children are always created in my project's folder :(

### What is the expected behavior?

- the global folder in my user's root/home folder should be filled with cached packages.
- the `--cache-dir` flag should work as documented
- the `--config` flag should work as documented
- the `bunfig.toml` file should be respected as documented

### What do you see instead?

for example:

`$ bun install --cache-dir $HOME/.bun/install/cache`
followed with `ls -alh`
displays:
```
[...] many other files from my project [...]
drwxr-xr-x    3 username  staff    96B  2 Oct 16:42 ~/
```

### Additional information

I just went through the macOS upgrade to Sonoma. But the issue was also happening with Ventura.

**Comment by Jarred-Sumner** [comment]
It's expected that `~` and `$HOME` are resolved by your shell and never make it into the arguments. Every script on your computer is going to have this problem, not just bun.

**Comment by tvardy** [comment]
No other scripts are having a problem with that resolution. I only noticed that with `bun`, hence my suspicion that it might be something with how `bun` does that.
I now tried: fish, bash and zsh on my Mac, and all reproduce the same behaviour. I can try with a Linux machine...

**Comment by tvardy** [comment]
I couldn't reproduce the problem on a Linux-based virtual machine. The cached packages land where expected.

**Comment by tvardy** [comment]
Trying to set a hardcoded path like `/Users/myusername/.bun/cache` (or any other) is also ignored and still produces the `~` folder inside the project :(

**Comment by irvanmohamad** [comment]
> Trying to set a hardcoded path like `/Users/myusername/.bun/cache` (or any other) is also ignored and still produces the `~` folder inside the project :(

@tvardy Have you check your shell profile? I use zsh, changed these lines (remove the quotes), and it worked:

```shell
# bun
export BUN_INSTALL="~/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bun completions
[ -s "~/.bun/_bun" ] && source "~/.bun/_bun"
````

to

```shell
# bun
export BUN_INSTALL=~/.bun
export PATH=$BUN_INSTALL/bin:$PATH

# bun completions
[ -s ~/.bun/_bun ] && source ~/.bun/_bun
````

**Comment by tvardy** [comment]
hey @irvanmohamad 
I'm using `fish`, but removing quotes from my config DID help

was:
```
# bun
set -Ux BUN_INSTALL "~/.bun"
set -x PATH $PATH ~/.bun/bin
```

is now:
```
# bun
set -Ux BUN_INSTALL ~/.bun
set -x PATH $PATH ~/.bun/bin
```

**Comment by ryoppippi** [comment]
I faced this issue now.
@tvardy 
I actually did the commands you provided, but the directory named `~` is created in project directory...

bun version: v1.2
fish, version 3.7.1
