### ISSUE TITLE
Different behaviour bun vs. node with NeDB Database

### ISSUE THREAD

**Issue by rgwch** [oven-sh/bun#6238]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

```bash
mkdir buntest
cd buntest
bun init
bun i nedb 
```
Then change index.ts to:

```js
import nedb from 'nedb'
const db = new nedb({filename: "./testdb",autoload:true})
db.insert({ "a": "b" })
```
launch with `bun run index.ts`

Launch several times, and the created database ./testdb will always be 1 line long, e.g. deleted and recreated.

### What is the expected behavior?

The database file should survive launches of the script (as it does if we do the same setup with npm / tsc).
Every launch should extend the file by one line.

### What do you see instead?

There is always a file with one data line, with a changing _id.

### Additional information

If you try the same with 

```bash
npm init -y
npm i --save typescript nedb
npx tsc --init
npx tsc
node index.js
```
the result will be as expected: ./testdb will increase by one line at every launch.

**Comment by cirospaciari** [comment]
Looks like this is fixed at some point in the past (works as expected with the code and steps provided), if you get this issue in the future please reopen with a repro.
