### ISSUE TITLE
An unknown error ocurred, possibly due to low max file descriptors

### ISSUE THREAD

**Issue by vitalics** [oven-sh/bun#6239]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Use template from github (I use https://github.com/vitalics/npm-bun-tsup-library)
2. run "bun install"

### What is the expected behavior?

no errors

### What do you see instead?

``` txt
error: An unknown error ocurred, possibly due to low max file descriptors (Unexpected)

Current limit: 10496

To fix this, try running:

  ulimit -n 2147483646

If that still doesn't work, you may need to run:

  sudo launchctl limit maxfiles 2147483646
```

### Additional information

Maybe the steps in the description are not relevant. I don't know actually.

**Comment by Electroid** [comment]
Could you try running the commands that the error suggested?

**Comment by vitalics** [comment]
okay. I'll close the issue. The reason was the operation with a deleted folder(the console inside vscode does not show this). So I reopened the console and it's working now.
