### ISSUE TITLE
`stdio[3 + n]` not working with `child_process`

### ISSUE THREAD

**Issue by solonifer** [oven-sh/bun#6240]
### What version of Bun is running?

1.0.3 & 1.0.4 canary

### What platform is your computer?

Darwin 23.0.0 arm64 arm & Linux 5.15.0-1040-oracle aarch64 aarch64

### What steps can reproduce the bug?

```
import { spawn } from "child_process";

const spawnBin = "node";
const spawnArgs = ["script.js"];

const child = (0, spawn)(spawnBin, spawnArgs, {
  env: {
    ...process.env,
  },
  detached: false,
  stdio: ["ignore", "pipe", "pipe", "pipe", "pipe", "pipe", "pipe"],
  windowsHide: true,
});

setTimeout(() => {
  console.log(typeof child.stdio[3], typeof child.stdio[4]);
}, 1000);
```

### What is the expected behavior?

```
❯ node test.js
object object
```

### What do you see instead?

```
❯ bun run test.js
undefined undefined
```

### Additional information

This code is a simplified example to reproduce the issue, the bug appears when using the dependency library that currently running on a node without any issue.

**Comment by birkskyum** [comment]
still in 1.0.18

**Comment by Clemens-E** [comment]
Similiar issue, I can attach the listeners but receive no data
Is #4670 related?

**Comment by Jarred-Sumner** [comment]
As of Bun v1.1.8, node and bun have the same output for the above script. 

```js
/private/tmp
❯ bun b.mjs
object object

/private/tmp
❯ node b.mjs
object object
```

**Comment by Clemens-E** [comment]
The output might be the same, but as it seems, just the symptom is fixed, not the actual problem.
I still don't get any events while Node.js does, see my new issue.
Hope it's okay that I created it like this.
