### ISSUE TITLE
confirm() seems not working

### ISSUE THREAD

**Issue by botikho** [oven-sh/bun#6243]
### What version of Bun is running?

1.0.3

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

Here is confirm() function implemented in Bun, but seems it always returns falsy state.

Do I use it wrong or it's a bug?

### What is the expected behavior?

Expects to return "true" on "y" or Enter key.

**Comment by Jarred-Sumner** [comment]
Please try again in Bun v1.0.4

`bun upgrade --canary`

**Comment by botikho** [comment]
Wow! Yes, this helps! 

Thank you 👍
