### ISSUE TITLE
HTTP server port conflict error message unclear

### ISSUE THREAD

**Issue by cmoog** [oven-sh/bun#625]
### Version

0.1.3

### Platform

Darwin arm64

### What steps will reproduce the bug?

**server.js**
```
export default {
  fetch(req) {
    return new Response("HI!");
  },
};
```

```
bun ./server.js
12 |       if(typeof entryNamespace?.default?.fetch === 'function')  {
13 |         Bun.serve(entryNamespace.default);
14 |       }
15 |    }, reportError);
16 | } else if (typeof entryNamespace?.default?.fetch === 'function') {
17 |    Bun.serve(entryNamespace.default);
       ^
 error: Failed to start server
      at bun:main:17:3
```

### How often does it reproduce? Is there a required condition?

Every time.

> Is there a required condition?

Not to my knowledge beyond what is described in the reproduction steps.

### What is the expected behavior?

The server should run as described in the documentation. 

### What do you see instead?

```
bun ./server.js
12 |       if(typeof entryNamespace?.default?.fetch === 'function')  {
13 |         Bun.serve(entryNamespace.default);
14 |       }
15 |    }, reportError);
16 | } else if (typeof entryNamespace?.default?.fetch === 'function') {
17 |    Bun.serve(entryNamespace.default);
       ^
 error: Failed to start server
      at bun:main:17:3
```

**Comment by Jarred-Sumner** [comment]
The error message definitely needs to be clearer

However, is something running on port 3000? Have you tried setting the port to something else, like `port: 3002`?

```js
export default {
  port: 3002,
  fetch(req) {
    return new Response("HI!");
  },
};
```

**Comment by cmoog** [comment]
Aha, that was it. Good call. Seems I had something else running on 3000– now it works great.

**Comment by cmoog** [comment]
@Jarred-Sumner Amazing work on bun! Thanks!
