### ISSUE TITLE
The offset of Blob.slice.slice is incorrect

### ISSUE THREAD

**Issue by chawson** [oven-sh/bun#6252]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 6.5.0-5-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
//@file index.js

import {readFileSync} from 'fs'

const filePath = '/video.mp4'
const blob = new Blob([readFileSync(filePath)])

// The following line of code does not meet expectations
const b = await blob.slice(744595, 754372).slice(0, 8).arrayBuffer()

console.log(Array.from(new Uint8Array(b)).join(','))
```

Executing `node index.js` outputs `0,0,0,108,109,118,104,100` as expected
Executing `bun index.js` output `0,0,0,32,102,116,121,112` is not as expected

### What is the expected behavior?

`0,0,0,108,109,118,104,100`

### What do you see instead?

`0,0,0,32,102,116,121,112`

The above result output is actually the data at offset 0 bytes, not the data at offset 744595 bytes.

### Additional information

Modify the above code and the following code will have the same problem when obtaining Blob.
```ts
const blob = Bun.file(filePath)
```
[video.mp4 download address](https://github.com/lokenetwork/FFmpeg-Principle/raw/main/videos/walking-dead.mp4)

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/47651f321ae5eb82686da5d759e9b1b5b12340ad/src/bun.js/webcore/blob.zig#L3010-L3012

The `offset` of prev slice is not been added here 🧐 maybe `+=`.
