### ISSUE TITLE
setTimeout blocking in while loop

### ISSUE THREAD

**Issue by BSN4** [oven-sh/bun#6253]
### What version of Bun is running?

1.0.4+ea956e58e9bac03b30d56ff74070603080913023

### What platform is your computer?

M1 mac

### What steps can reproduce the bug?

```js
            while (true) {
               // blocking code

                await new Promise((resolve) => setTimeout(resolve, 0))
            }
```

### What is the expected behavior?

in node.js same code will be running non-blocking

### What do you see instead?

blocking i/o

### Additional information

as workaround `await new Promise((resolve) => setTimeout(resolve, 1)` works

**Comment by jumoog** [comment]
#3333
