### ISSUE TITLE
More support for `npm ls`

### ISSUE THREAD

**Issue by SamTV12345** [oven-sh/bun#6260]
### What is the problem this feature would solve?

We have a plugin system that gets the output of this command, filters all packages that start with ep_ and tries to load them. I didn't find a solution in bun that does this. Especially the path field is very interesting as it outputs where exactly this package is located.

> npm ls --long --json --depth=0 --no-production

### What is the feature you are proposing to solve the problem?

Implement such a functionality so that a user can locate the installed packages in a json format.

### What alternatives have you considered?

I found bun pm ls but it just outputs a list with no extra information.

**Comment by Electroid** [comment]
Duplicate of #8283
