### ISSUE TITLE
"bun build" with vite+react throws errors, does not build index.html

### ISSUE THREAD

**Issue by nickburczyk** [oven-sh/bun#6270]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

MacOS - Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Create new Vite React app `bun create vite bun-bug`
2. CD into folder `cd bun-bug`
3. `bun install`
4. `bun build`
   - view error that entrypoints are needed
5. add entrypoints and outdir `bun build ./src/main.jsx --outdir=dist`
   - builds, but does not add `index.html` file with links to built entry files.
6. explicitly input jsx and html entry points `bun build ./src/main.jsx ./index.html --outdir=dist`
   - build succeeds as expected

```zsh
nick code
% bun create vite bun-bug
✔ Select a framework: › React
✔ Select a variant: › JavaScript + SWC

Scaffolding project in /Users/nick/Desktop/CODE/bun-bug...

Done. Now run:

  cd bun-bug
  bun install
  bun run dev

nick code
% cd bun-bug
nick bun-bug
% bun install
bun install v1.0.2 (37edd5a6)
 + @types/react@18.2.24
 + @types/react-dom@18.2.8
 + @vitejs/plugin-react-swc@3.4.0
 + eslint@8.50.0
 + eslint-plugin-react@7.33.2
 + eslint-plugin-react-hooks@4.6.0
 + eslint-plugin-react-refresh@0.4.3
 + vite@4.4.10
 + react@18.2.0
 + react-dom@18.2.0

 215 packages installed [5.38s]
nick bun-bug
% bun dev
$ vite
  VITE v4.4.10  ready in 641 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
  
 # Verify running, CTRL+C (^c) to escape, 
 
# === HERE IS THE ISSUE === 
 nick bun-bug
% bun build
bun build v1.0.2 (37edd5a6)
error: Missing entrypoints. What would you like to bundle?

Usage: bun build [flags] [...entrypoints]

Common Flags:
  --outfile            Write the output to a specific file (default: stdout)
  --outdir             Write the output to a directory (required for splitting)
  --minify             Enable all minification flags
  --minify-whitespace  Remove unneeded whitespace
  --minify-syntax      Transform code to use less syntax
  --minify-identifiers Shorten variable names
  --sourcemap          Generate sourcemaps
                       ("none", "inline", or "external")
  --target             The intended execution environment for the bundle.
                       ("browser", "bun" or "node")
  --splitting          Enable code splitting (requires --outdir)
  --watch              Run bundler in watch mode

Examples:
  Frontend web apps:
  bun build ./src/index.ts --outfile=bundle.js
  bun build --minify --splitting --outdir=out ./index.jsx ./lib/worker.ts

  Bundle code to be run in Bun (reduces server startup time)
  bun build --target=bun ./server.ts --outfile=server.js

  Creating a standalone executable (see https://bun.sh/docs/bundler/executables)
  bun build --compile ./cli.ts --outfile=my-app

A full list of flags is available at https://bun.sh/docs/bundler
nick bun-bug
% bun build ./src/main.jsx --outdir=dist


error: Could not resolve: "/vite.svg"

import viteLogo from '/vite.svg'
                     ^
/Users/nick/Desktop/CODE/bun-bug/src/App.jsx:3:22 97
nick bun-bug
% bun build ./src/main.jsx ./public/vite.svg ./index.html --outdir=dist


error: Could not resolve: "/vite.svg"

import viteLogo from '/vite.svg'
                     ^

# HAD TO REMOVE VITE LOGO FROM LANDING PAGE ALTOGETHER, THEN:

nick bun-bug
% bun build ./src/main.jsx --outdir=dist

  main.js                       962.33 KB

  react-5f3aede0c899e67d.svg    4.13 KB

  App-76dd951ef99ed8c4.css      0.61 KB

  index-fb1fc30093701358.css    1.20 KB

[51ms] bundle 14 modules

nick bun-bug
% bun build ./src/main.jsx ./index.html --outdir=dist

  Users/nick/Desktop/CODE/bun-bug/src/main.js  962.33 KB

  Users/nick/Desktop/CODE/bun-bug/index.js  0.84 KB

  Users/nick/Desktop/CODE/bun-bug/react-5f3aede0c899e67d.svg  4.13 KB

  Users/nick/Desktop/CODE/bun-bug/App-76dd951ef99ed8c4.css  0.61 KB

  Users/nick/Desktop/CODE/bun-bug/index-fb1fc30093701358.css  1.20 KB

  Users/nick/Desktop/CODE/bun-bug/index-cc87b8dab844e2ea.html  0.37 KB

[43ms] bundle 15 modules
```
Folder structure after build succeeds, missing index.html
<img width="213" alt="image" src="https://github.com/oven-sh/bun/assets/33436104/c7ea48c5-d7f9-4353-a54d-41e00db7a8e8">

### `npx vite build` still works out-of-the-box
When I run `npx vite build` it works without entry points, without changes to `vite.config.js`, and without `outdir` flag.
<img width="440" alt="image" src="https://github.com/oven-sh/bun/assets/33436104/0b0994fe-8717-42ca-b6a7-4817aeae4543">
<img width="209" alt="image" src="https://github.com/oven-sh/bun/assets/33436104/6d969f29-a179-45a7-a210-1eebd85a3dff">

### What is the expected behavior?

- `bun build` would ideally work just like `npm build` (when using npm with vite) or `npx vite build` does. 
- User shouldn't be required to define all the entrypoints and outdir
- build in this environment should include the index.html file, or else deployments to frontend will fail.

### What do you see instead?

Running `bun build` in a vite react app throws errors and demands input and output parameters to be defined. See above.

### Additional information

As a side note, the build script does not seem to be respecting my vite.config.js file, which should take care of some of the explicit build I/O parameters.

Here is the content of my `vite.config.js` file:
```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/mathe-ueben/',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: ['src/main.jsx', './index.html']
    }
  }
})
```

**Comment by Electroid** [comment]
`bun build` is a built-in command in Bun, which is why you're seeing the help page.

If you want to run the `build` script in your package.json, you'd need to run: `bun run build`. Or you can also do `bunx vite build`, which is similar to `npx vite build`.

**Comment by nickburczyk** [comment]
Holy moly that was a quick response, @Electroid !

That was my issue. thanks for the help! Closing this now.
