### ISSUE TITLE
`ts-patch` with bun

### ISSUE THREAD

**Issue by Pandapip1** [oven-sh/bun#6271]
### What is the problem this feature would solve?

I would like to be able to use `ts-patch` natively with bun.

### What is the feature you are proposing to solve the problem?

Pretty simple. Instead of using the typescript compiler, it should use the ts-patch compiler by default.

**Comment by Electroid** [comment]
Bun does not use the TypeScript compiler, it has its own parser/lexer that reads TypeScript and converts it to JavaScript. If you want to use `ts-patch`, it might be possible by using a [`Bun.plugin`](https://bun.sh/docs/bundler/plugins), similar to an esbuild plugin.

**Comment by Pandapip1** [comment]
I can't find anything in the `Bun.plugin` documentation that suggests that it is able to rewrite files. Can you point me in the right direction?
