### ISSUE TITLE
`vm.runInThisContext` Context must be an object

### ISSUE THREAD

**Issue by volkish** [oven-sh/bun#6272]
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

`bun install requirejs`
`echo "const x = require('requirejs');" > index.js`
`bun index.js`

### What is the expected behavior?

No `TypeError`

### What do you see instead?

```
57 |         readFile = function (path) {
58 |             return fs.readFileSync(path, 'utf8');
59 |         };
60 | 
61 |         exec = function (string, name) {
62 |             return vm.runInThisContext(this.requirejsVars.require.makeNodeWrapper(string),
                       ^
TypeError: Context must be an object
      at exec (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:62:19)
      at setBaseUrl (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30248:12)
      at /Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30338:8
      at /Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30423:21
      at globalThis (/Users/artemivanov/Sites/x/node_modules/requirejs/bin/r.js:30431:60)
      at require (:1:20)
      at /Users/artemivanov/Sites/x/index.js:1:6
      at globalThis (/Users/artemivanov/Sites/x/index.js:1:6)
```

**Comment by Electroid** [comment]
This is likely an incompatibility with how Bun has implemented `runInThisContext`.

**Comment by SamTV12345** [comment]
@Electroid Is this something that will be fixed or do we need to adapt our JavaScript code to meet Buns implementation.

**Comment by Electroid** [comment]
@SamTV12345 This will be fixed, it's a bug with Bun.

**Comment by birkskyum** [comment]
This is still an issue. Appear to be blocking [RequireJS](https://requirejs.org/).

Repro - just install and run:
`var requirejs = require('requirejs');`

**Comment by quantizor** [comment]
I'm also seeing this with jest and current latest bun.

```
● Test suite failed to run

    TypeError: context parameter must be a contextified object
        at runInContext (native)

      at new Window (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:252:58)
      at processTicksAndRejections (native:7:39)
```

jest@29.7.0
jest-environment-jsdom@29.7.0
