### ISSUE TITLE
Segfault on some constructors when used without `new`

### ISSUE THREAD

**Issue by colinhacks** [oven-sh/bun#6281]
### What steps can reproduce the bug?

```ts
import { File } from "buffer";
File();
```

```ts
import {Script} from "vm";
Script();
```

**Comment by Jarred-Sumner** [comment]
This needs to become a function that throws a TypeError "Class constructor File cannot be used without new"

https://github.com/oven-sh/bun/blob/main/src/bun.js/bindings/JSDOMFile.cpp#L20

**Comment by krk** [comment]
`File` fixed in https://github.com/oven-sh/bun/pull/5881 with a typo in the message.
