### ISSUE TITLE
bun-types tag latest mixed with canary

### ISSUE THREAD

**Issue by ImBIOS** [oven-sh/bun#6287]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

![image](https://github.com/oven-sh/bun/assets/41441643/899b6042-39a1-4820-884f-ffb57e47d603)

If we set the version to the latest, then we did not install what we expected, we installed the canary instead.

### What is the expected behavior?

version latest should get the latest, not the canary version.

### What do you see instead?

I got the canary version instead.

### Additional information

I suspect this commit:

- https://github.com/oven-sh/bun/commit/237a5ada4750ff255781d91e004e5e9570f031a2

We already have:

https://github.com/oven-sh/bun/blob/df9461ecc58e2882afa34cdf59d9887d9242b5f9/.github/workflows/bun-release-types-canary.yml#L1-L54C22

Why do we need bun-types published in 2 workflows?

![image](https://github.com/oven-sh/bun/assets/41441643/9868a7b6-89ec-4114-9767-9c201955692d)

![image](https://github.com/oven-sh/bun/assets/41441643/fdf24f8c-797b-4c52-9dfa-5fe970965830)

**Comment by IronGeek** [comment]
This needs to be addressed
Currently the `latest` tag points to [1.0.5-canary.20231005T140125](https://www.npmjs.com/package/bun-types/v/1.0.5-canary.20231005T140125),
while the `canary` tag is pointing to [1.0.4-canary.20231003T161139](https://www.npmjs.com/package/bun-types/v/1.0.4-canary.20231003T161139), there's no version `1.0.5` :confused: 

![image](https://github.com/oven-sh/bun/assets/1383932/ed7c7905-d277-4946-b739-9a37210972f5)

**Comment by ImBIOS** [comment]
@IronGeek 1.0.5-canary is the canary release, 1.0.4-canary is obsolete because the 1.0.4 have stable release.
@Jarred-Sumner @Hanaasagi @Electroid @oven-sh correct me if I'm wrong in understanding it, or should We write docs for it too? (or is there any available docs for it?)

**Comment by IronGeek** [comment]
> @IronGeek 1.0.5-canary is the canary release, 1.0.4-canary is obsolete because the 1.0.4 have stable release.

Agree. And to my understanding, the `latest` tag should still point to 1.0.4 since 1.0.5 is not released yet.

**Comment by ImBIOS** [comment]
@IronGeek Indeed, it's somehow mirrored, 1.0.5-canary should be tagged with canary, and latest should have 1.0.4.
You can check my PR to fix this.

**Comment by Hanaasagi** [comment]
@colinhacks Could you take a look at this? thanks.

**Comment by Electroid** [comment]
Fixed.

<img width="675" alt="Screenshot 2023-10-11 at 12 07 57 PM" src="https://github.com/oven-sh/bun/assets/3238291/ca127b6b-53d1-416e-9e88-83d0229cb8a9">

**Comment by ImBIOS** [comment]
I love not just how fast Bun is, but also the community ❤️
