### ISSUE TITLE
Uploading files use Multer and multer-gridfs-storage

### ISSUE THREAD

**Issue by hungattack** [oven-sh/bun#6296]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Window

### What steps can reproduce the bug?

I have a problem uploading files when I use multer and multer-gridfs-storage when I request on server bun it stops in upload. array('files') and never responds but I use nodejs it's still working
// express
`router.post('/sendChat', upload.array('files'), sendChatController.sendChat); // Router`

```
import multer from 'multer';
import { v4 as primaryKey } from 'uuid';
import mongoose from 'mongoose';
import path from 'path';
const crypto = require('crypto');
import Grid from 'gridfs-stream';
import { GridFsStorage } from 'multer-gridfs-storage';
const URL = 'mongodb+srv://mongodb's `url';`
let gfs: any;
const conn = mongoose.createConnection(URL);
conn.once('open', () => {
    gfs = Grid(conn.db, mongoose.mongo);
    gfs.collection('uploads');
    console.log('connect');
});
const storage = new GridFsStorage({
    url: URL,
    cache: true,
    file: (req: any, files: any) => {
        return new Promise((resolve, reject) => {
// never run here
            try {
                crypto.randomBytes(16, (err: any, buf: { toString: (arg0: string) => any }) => {
                    if (err) {
                        return reject(err);
                    }
                    const id = primaryKey();
                    const filename = buf.toString('hex') + path.extname(files.originalname);
                    const fileInfo = {
                        filename: filename,
                        bucketName: 'uploads',
                        metadata: {
                            id_file: id, // Trường để lưu _id của tệp tin
                        },
                    };
                    console.log(files.f, 'ss');

                    resolve(fileInfo);
                });
            } catch (error) {
                console.log(error);
            }
        });
    },
});
export const upload = multer({ storage });
```

### What is the expected behavior?

Please fix it

**Comment by sp90** [comment]
Is it related to #2026 also please revalidate using the latest revision `1.0.21+437faa944` i got all variations working single file, multi-file and s3 file uploads

Havn't tried gridfs though but you say it stops in the array

Try `bun upgrade --canary` and try your code again

Alternatively try out my repo with working code:

https://github.com/sp90/bun-multer-busboy

**Comment by Electroid** [comment]
Duplicate of #2026

**Comment by sugam2060** [comment]
Cannot read properties of undefined (reading '_id')
    at GridFSBucketWriteStream.emitFile
    
    i got this error how to fix it any idea

**Comment by sp90** [comment]
@sugam2060 haven't seen it before does it do the same in node?
