### ISSUE TITLE
Resolving of peer dependencies for mono repo packages

### ISSUE THREAD

**Issue by co-sic** [oven-sh/bun#6316]
### Discussed in https://github.com/oven-sh/bun/discussions/5810

<div type='discussions-op-text'>

<sup>Originally posted by **co-sic** September 20, 2023</sup>
Hi, 

i have a depency list in my project looking like this:
```
 "dependencies": {
    ...
    "@mikro-orm/cli": "5.8.1",
    "@mikro-orm/core": "5.8.1",
    "@mikro-orm/migrations": "5.8.1",
    "@mikro-orm/postgresql": "5.8.1",
    "@mikro-orm/reflection": "5.8.1",
    ...
  },
```

In the @mikro-orm/migration package.json the peer dependencies are defined like this:

```
 "peerDependencies": {
    "@mikro-orm/core": "^5.0.0"
  }
```

If i run `bun install` it will install all dependencies correctly, but e.g. in the installed @mikro-orm/migration there is a node_modules folder with @mikro-orm/core intalled in version 5.7.14 (latest 5.7 version). 
Is there any way to tell bun that it should used the already installed 5.8.1 version of @mikro-orm/core? With node/npm this was working correctly before.

Bun version: 1.0.4

**Edit**: What worked for me was deleting the bun.lockb and node_modules folder and then run `bun install` again. But it should be possible that this is working without the need to delete the lockfile.
</div>

**Comment by dylan-conway** [comment]
This is fixed in v1.0.13
