### ISSUE TITLE
error for await without async could be better

### ISSUE THREAD

**Issue by Haroenv** [oven-sh/bun#632]
### What is the problem this feature will solve?

This will prevent you from trying to figure out what's going on, but have a clear error message

### What is the feature you are proposing to solve the problem?

Await without async should be something like node's "unexpected reserved word" error:

```
~ (master) [1]> node test.js 
file:///test.js:2
  await Promise.resolve();
  ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (node:internal/modules/esm/translators:147:18)
    at async link (node:internal/modules/esm/module_job:48:21)
```

In Bun this currently gives:

```


error: Expected ";" but found "Promise"

  await Promise.resolve();
        ^
/test.js:2:9 23


error: Unexpected .

  await Promise.resolve();
               ^
/test.js:2:16 30
```

This is for a test file with the content:

```js
function x() {
  await Promise.resolve();
}
```

**Comment by Jarred-Sumner** [comment]
yeah this is a truly terrible error message

**Comment by oculus42** [comment]
Related to #108 ?

**Comment by Haroenv** [comment]
indeed a duplicate, thanks @oculus42
