### ISSUE TITLE
Bun abruptly ending inquirer JS process

### ISSUE THREAD

**Issue by VLtim43** [oven-sh/bun#6323]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 5.15.0-78-generic x86_64 x86_64

### What steps can reproduce the bug?

- ```bun init```
- Add inquirer ```bun add inquirer```
- Add the script ```"scripts": {
    "start": "bun run index.ts"
  }```
- Add this simple inquirer cli
```
import inquirer from "inquirer";

async function listWithinList() {
  const reptileChoice = await inquirer.prompt([
    {
      name: "options",
      type: "list",
      message: "options?",
      choices: ["A", "B", "C", "Return to main menu"],
    },
  ]);

  if (reptileChoice.options === "Return to main menu") {
    await mainInterface();
    return;
  }
  console.info("Answer:", reptileChoice.options);
}

async function mainInterface() {
  const mainChoice = await inquirer.prompt([
    {
      type: "list",
      name: "option",
      choices: [
        { name: "List", value: "list" },
        { name: "Quit", value: "quit" },
      ],
    },
  ]);

  if (mainChoice.option === "list") {
    await listWithinList();
  }
}

mainInterface();


```

### What is the expected behavior?

The  expected behavior should be
- The options appearing
```
? option: (Use arrow keys)
❯ List 
  Quit 
 ```
 
 - Then if I choose "list", it should display this sub-list with the new options that I can scroll with the arrow keys indefinitely. If choosing ABC the program should quit, and upon choosing "Return to main menu" should go the last interface(not quitting)
```
? option: List
? options? (Use arrow keys)
❯ A 
  B 
  C 
  Return to main menu 
 ```

### What do you see instead?

- The options appearing ✅
```
? option: (Use arrow keys)
❯ List 
  Quit 
 ```
 
 - Then if I choose "list", it does displays all the options, but immediately ends the cli. 
```
? option: List
? options? (Use arrow keys)
❯ A 
  B 
  C 
  Return to main menu 
**the program ends**
 ```

### Additional information

Tried the exact same function with node, and it works as intended 

![ezgif-4-cfcefce3e4](https://github.com/oven-sh/bun/assets/69370181/69afc9d2-029c-4442-8c7b-252bad2203ba)

![1](https://github.com/oven-sh/bun/assets/69370181/4078c01d-ca50-48db-a0ad-954cbec8d7e4)

![image](https://github.com/oven-sh/bun/assets/69370181/dbcbe237-6ffb-4e5d-9df2-5658f63fcc6c)

Started with bun today, I don't know if I'm doing something wrong

**Comment by fradinni** [comment]
Same issue here.

I also have an issue when using `ink` library. The `useInput()` feature that is capturing keyboard events in terminal is not working.

It's working well in Node.

**Comment by Levent0z** [comment]
Here is a bare-bones repro of the issue, except the program just hangs when running with bun. It works with node.
Bun version 1.0.5, Node version 18.17.1, inquirer 9.2.11

```
import inquirer from 'inquirer';

for (let i = 0; i < 10; i++) {
    console.log(`Loop: ${i}`);
    const argName = `arg${i}`;
    await inquirer.prompt({
        type: 'input',
        name: argName,
        message: `Input ${i}:`
    });
}
```
