### ISSUE TITLE
http.createServer on('listening') gets passed listening address instead of undefined on success

### ISSUE THREAD

**Issue by sfrieske** [oven-sh/bun#6325]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 6.1.55-1-MANJARO x86_64 unknown

### What steps can reproduce the bug?

`var srv = http.createServer()`
`srv.on('listening', (err) => console.log('err:', err))`
`srv.listen(0)`

### What is the expected behavior?

// -> err: undefined (as in nodejs)

### What do you see instead?

// -> err: localhost

### Additional information

Seems to be http specific, trying the same with `net.createServer` behaves as expected.

**Comment by Hanaasagi** [comment]
There are no parameters, including `err`, for this function.

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0475ac7edca1ce6123f4e255061f97758087c0d/types/node/http.d.ts#L471

**Comment by sfrieske** [comment]
You are right, closing this.
