### ISSUE TITLE
Support `expect.extend()`

### ISSUE THREAD

**Issue by tinchox5** [oven-sh/bun#6330]
### What is the problem this feature would solve?

I'm working on a CSS UI library and the best way I found for testing it is comparing image snapshots. Code snapshots are not useful in my case.

### What is the feature you are proposing to solve the problem?

Implement image snapshots diff feature.

### What alternatives have you considered?

On  Node I use jest with   "jest-image-snapshot" (a image snapshot extension) and puppeteer. That solves my requirements.

**Comment by Electroid** [comment]
We can support this once Bun implements `expect.extend()`

**Comment by etiennejcharles** [comment]
I think this might be a duplicate of #3621 - follow here instead @Electroid - I might be wrong too 🤷🏿‍♂️

**Comment by Electroid** [comment]
Duplicate of #3621
