### ISSUE TITLE
PM2 now uses bun to start .ts and .tsx 

### ISSUE THREAD

**Issue by Unitech** [oven-sh/bun#6333]
### What is the issue?

No issue there, just wanted to share that I put bun as the default interpreter when starting a .ts or .tsx application.
So with the PM2 5.3.1 you will be able to do:
`pm2 start app.ts`
And it will run the app.ts with bun directly

Let me know if there are other things I could change with PM2 to make it more compatible with bun

**Comment by BrycensRanch** [comment]
thanks bro

**Comment by drag0n-app** [comment]
good job

**Comment by Electroid** [comment]
Thanks! This is great ❤️
