### ISSUE TITLE
Copying a file displays an incorrect error, using the source path instead of the destination path if the destination directory doesn't exist

### ISSUE THREAD

**Issue by Vanilagy** [oven-sh/bun#6336]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

With `baz.txt` existing, run the following:
```ts
await Bun.write('./foo/bar.txt', Bun.file('./baz.txt'));
```
This operation errors because the folder `foo` doesn't exist.

### What is the expected behavior?

It should tell me that the output directory does not exist.

### What do you see instead?

```
ENOENT: No such file or directory
   path: "./baz.txt"
 syscall: "open"
   errno: -2
```

**Comment by Hanaasagi** [comment]
Additionally, when the second argument is a string, there is no `path` in the error message. It seems that `path` field might be using the value from the second.

```JavaScript
await Bun.write("./foo/bar.txt", "");

// Output
// 1 | await Bun.write("./foo/bar.txt", "");
//          ^
// ENOENT: No such file or directory
//  syscall: "open"
//    errno: -2


```

**Comment by Vanilagy** [comment]
slay
