### ISSUE TITLE
Unable to install a NPM package

### ISSUE THREAD

**Issue by ngdangtu-vn** [oven-sh/bun#6357]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 6.2.0-10022-tuxedo x86_64 x86_64

### What steps can reproduce the bug?

1. Run this command `bun x wrangler`

### What is the expected behavior?

The binary of wrangler should be installed nicely to the computer.

### What do you see instead?

```
❯ bun x wrangler
  🚚 data-uri-to-buffer [232/233]
```

It keeps frozen with no error. Yes, no bugs were printed out at all.

### Additional information

- This distro is expected to belong to Ubuntu/Debian family.
- The installation was attempted to do in vscode terminal and konsole:
  1. First time I did with vscode terminal which leads to result above
  2. After I cancelled it, I tried again on konsole terminal, `bun x wrangler` simply displayed help message
  3. Tried again on vsocde, it displayed the help message

Simple like the Bun binary installer totally break after attempt to install wrangler of Cloudflare.

**Comment by gtrabanco** [comment]
I had similar issue with other packages, try:

```shell
bun pm cache rm
bunx wrangler # bunx is an alias for bun x
```

**Comment by ngdangtu-vn** [comment]
```sh
❯ bun pm cache rm

error: MissingPackageJSON
Bun could not find a package.json file.
```

I only want `wrangler` and my repo doesn't use `package.json`.

**Comment by gtrabanco** [comment]
Then clean the global cache and try again:

```shell
bun pm --global cache rm
```

**Comment by ngdangtu-vn** [comment]
Have you tried that command? Cause I still got the same message:

![image](https://github.com/oven-sh/bun/assets/68631458/301708fb-3345-4e3f-980a-5d8b9f90689e)

**Comment by gtrabanco** [comment]
Yes, it works at least on `Darwin 21.6.0 x86_64 i386`. Maybe another issue?

![Captura de Pantalla 2023-10-08 a las 15 22 25](https://github.com/oven-sh/bun/assets/1969593/b1a38ac2-6d38-4f0a-b775-211cc206cfaa)

**Comment by ngdangtu-vn** [comment]
Maybe I should reinstall Bun. After I reinstall (uninstalling by delete `~/.bun` and run `curl -fsSL https://bun.sh/install | bash` again), it seems everything back to normal :? Anyway, case close. Thanks @gtrabanco for the assistance.
