### ISSUE TITLE
Failed to enable File Watcher

### ISSUE THREAD

**Issue by lucaspereirasouzat** [oven-sh/bun#6362]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 6.4.6-76060406-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a index.ts file 
2. Put inside `console.log('test')`
3. run `bun run --watch index.ts`

### What is the expected behavior?

watch mode

### What do you see instead?

uh-oh: Failed to enable File Watcher
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.4 (745b6b94) Linux x64 #202307241739~1694621917~22.04~ac5e1a8 SMP PREEMPT_DYNAMIC Wed S
RunCommand: 
Elapsed: 5ms | User: 471ms | Sys: 765ms
RSS: 33.55MB | Peak: 29.38MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x55be59c104fb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.4-1696744298905.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

--- Bun is auto-restarting due to crash [time: 1696744298905] ---

### Additional information

Seem in the last update version, on the v1.0.3 watch mode works normaly

**Comment by lucaspereirasouzat** [comment]
works now on version v1.0.6

**Comment by vincentdh** [comment]
Got the same problem with v1.0.7 on Debian 12 (not WSL) 

Can we reopen the issue?

```
uh-oh: Failed to enable File Watcher
bun will crash now 😭😭😭
----- bun meta -----
Bun v1.0.7 (b0393fba) Linux x64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)
RunCommand: 
Elapsed: 21ms | User: 13ms | Sys: 17ms
RSS: 33.55MB | Peak: 47.35MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x562cdb6329bb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.7-1698070533078.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 322188 panic: Failed to enable File Watcher
Unwind information for `:0x562cda8c3bca` was not available, trace may be incomplete

Abandon (core dumped)
```
