### ISSUE TITLE
Incorrect Base URL

### ISSUE THREAD

**Issue by WeismannS** [oven-sh/bun#637]
### Version

0.1.3

### Platform

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?

console.log(import.meta.url) // file:///mnt/c/Users/a/WebstormProjects/BunTest/test.js

console.log(__dirname) // /mnt/c/Users/a/WebstormProjects/BunTest

console.log(__filename) // /mnt/c/Users/a/WebstormProjects/BunTest/test.js

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

It should be sending a url of the native environment 
e.g : file:///C:/ 
without mnt
   

### What do you see instead?

file:///mnt/c 

### Additional information

This causes alot of dependencies that uses  fileURLToPath  and use new URL to fail getting the correct path and therefor errors 
i believe this wsl issue but this is still an issue

**Comment by xhyrom** [comment]
This is path for WSL when using applications from WSL on Windows. When using only WSL, the path will be `/home/xxxxxx`

https://docs.microsoft.com/en-us/windows/wsl/faq

**Comment by FinnRG** [comment]
@WeismannS Currently you should keep everything in the default WSL file system, not on mounted drives.

**Comment by Kapsonfire** [comment]
No bug. the path is correct from wsl point of view - and wsl is executing here!
