### ISSUE TITLE
Support `bun install --save-dev`

### ISSUE THREAD

**Issue by sistematico** [oven-sh/bun#6372]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 6.5.5-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

```
bun create vite
bun install --save-dev @iconify/vue
```

### What is the expected behavior?

Install @iconify/vue package.

### What do you see instead?

Cannot find module '@iconify/vue' or its corresponding type declarations.ts(2307)

**Comment by yud0uhu** [comment]
@sistematico 
The bun install command does not support the --save-dev flag.
```sh
bun install --save @iconify/vue
```

After installing using the above command, you can confirm that the @iconify/vue library has been added to devDependencies

```package.json:json
"devDependencies": {
    "@iconify/vue": "^4.1.1",
```

In the created Vite project, after declaring as follows and restarting vscode, it was confirmed that the module was successfully imported.

```vue:App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
import { Icon } from "@iconify/vue";
</script>
```

**Comment by stalinkay** [comment]
Please support --save-dev and other essential flags. It makes pain-free to integrate bun.

**Comment by justo-yasskate** [comment]
@stalinkay 

It is supported.
use `add` instead of `install`, you can take a look here -> https://bun.sh/docs/cli/add#dev

![image](https://github.com/user-attachments/assets/ef532400-2456-4781-b645-5db22f5e84b7)
