### ISSUE TITLE
Calling `Error.stack` causes stack trace to change

### ISSUE THREAD

**Issue by al6x** [oven-sh/bun#6373]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Darwin 18.7.0 x86_64 i386

### What steps can reproduce the bug?

```TypeScript
function raise(msg: string) {
  const e = new Error(msg)
  const tmp = e.stack
  throw e
}
function some() {
  raise('hi')
}
some()
```

### What is the expected behavior?

```
> bun play.ts 
1 | function raise(msg: string) {
2 |   const e = new Error(msg)
                ^
error: hi
      at raise (/alex/projects/ts/play.ts:2:12)
      at some (/alex/projects/ts/play.ts:7:2)
      at /alex/projects/ts/play.ts:9:0
```

### What do you see instead?

```
> bun play.ts 
1 | function raise(msg: string) {
2 |   const e = new Error(msg)
3 |   const tmp = e.stack
4 |   throw e
            ^
error: hi
      at /alex/projects/ts/play.ts:4:8
```

### Additional information

This line `const tmp = e.stack` changes the printed stack trace, comment/uncomment it to see the difference.

**Comment by Jarred-Sumner** [comment]
Fixed as of Bun v1.1.13
