### ISSUE TITLE
`bunx` uses stale version of package

### ISSUE THREAD

**Issue by robertd** [oven-sh/bun#6375]
### What is the issue?

Where is the bunx installation location? I'm trying to run `bunx cdk` but my install gets older version of the package, this being really stale? Any pointers?

**Comment by ngdangtu-vn** [comment]
By default in Linux it should be hidden in home directory (`~/.bun`) but you can choose different location before install by setup env path `$BUN_INSTALL`. Here is what I usually do in KDE Plasma:

```shell
# /home/dangtu/.config/plasma-workspace/env/load.sh
# Bun
export BUN_INSTALL="$HOME/.local/prgm/bun"
export PATH="$BUN_INSTALL/bin:$PATH"
```

**Comment by robertd** [comment]
I’ve installed it using brew. Deleted everything, including ~/.bun and
still can’t install latest version of package using bunx. Something is not
right. Any other places where this would get cached?

**Comment by ngdangtu-vn** [comment]
I think I got the same problem with wrangler when I installed it with `bunx`. The wrangler still work even though I reinstall completely new.

**Comment by robertd** [comment]
Where is the installation location of bunx? ~/.bun?

**Comment by robertd** [comment]
Related to: #4989

**Comment by paperclover** [comment]
This was fixed in https://bun.sh/blog/bun-v1.0.29#bunx-checks-for-updates-more-frequently, but the issue report here is a duplicate of the linked #4989

To answer the question about cache location, as of 1.0.29, they are stored in /tmp, specifically at `/tmp/bunx-{uid}-{package_name}`
