### ISSUE TITLE
Error al resolver 'bun:jsc'

### ISSUE THREAD

**Issue by rafubu** [oven-sh/bun#6389]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
bun build  ./index.ts --minify --splitting --outfile=build/bundle.js
```

error: Could not resolve: "bun:jsc". Maybe you need to "bun install"?

import { serialize, deserialize } from 'bun:jsc'

**Comment by Electroid** [comment]
Try:

```sh
bun build ./index.ts --minify --splitting --outfile=build/bundle.js --target=bun
```
