### ISSUE TITLE
URL Pattern API

### ISSUE THREAD

**Issue by fkdiomande** [oven-sh/bun#6403]
### What is the problem this feature would solve?

- https://deno.land/api@v1.37.1?s=URLPattern
- https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API

### What is the feature you are proposing to solve the problem?

To create a custom Router

### What alternatives have you considered?

https://github.com/pillarjs/path-to-regexp

**Comment by Electroid** [comment]
Duplicate of #2286
