### ISSUE TITLE
bun hangs on run

### ISSUE THREAD

**Issue by JAD3N** [oven-sh/bun#6414]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Linux 6.5.4-76060504-generic x86_64 x86_64

### What steps can reproduce the bug?

I created a file called `hello.js`  and ran `bun hello.js` but the script just hangs and doesn't log anything to the cli terminal.

This is what I put in the file:
```js
console.log("Hello World!");
```

### What is the expected behavior?

I expected the terminal to have an output of `Hello World!`.

### What do you see instead?

I don't see anything, the script just hangs.

**Comment by illusionTBA** [comment]
Bump ! Been happening to me since the canary build 
![image](https://github.com/oven-sh/bun/assets/97645434/f6aee8a5-a268-4350-b695-0c7e10b0ac03)

**Comment by devinMcArthur** [comment]
Bump. Trying bun for the first time today. Followed docs, did a `bun init`, file contains only a `console.log("Hello World");` and nothing happens.

Operating on WSL2, Windows 10. zsh shell.

**Comment by Jarred-Sumner** [comment]
@cirospaciari is working on a fix. We will ship v1.0.6 today to address this issue.

**Comment by miguelmendez1208** [comment]
Is there a way to downgrade my version of bun back to a previous version?  
OS:
Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux

**Comment by sahibalejandro** [comment]
Fresh bun install on a Raspberry Pi 4 running Linux 6.1.21-v8+
`bun run index.ts` just hangs and does nothing.

I tried same codebase with same bun version on macOS 14.0 (23A344) and works fine there.

**Comment by Jarred-Sumner** [comment]
Once [this commit](https://github.com/oven-sh/bun/commit/b1063edf3e76a2ef68d2ba3eff686932f742c77c) finishes compiling, please run `bun upgrade --canary` and try again

**Comment by sahibalejandro** [comment]
I just updated to `1.0.6` but `bun run index.ts` still not working, it hangs.
<img width="855" alt="Screenshot 2023-10-11 at 9 29 01 p m" src="https://github.com/oven-sh/bun/assets/985268/c822bf11-c784-4a57-a60d-2c3376fcc8bc">

**Comment by Jarred-Sumner** [comment]
@sahibalejandro can you paste `bun --revision`?

**Comment by sahibalejandro** [comment]
`1.0.6+edb4cbac2b03c4350c6efcfbfc50bda5159800be`

**Comment by Jarred-Sumner** [comment]
@sahibalejandro please run `bun upgrade --canary` again, the expected version is b1063edf3e76a2ef68d2ba3eff686932f742c77c

**Comment by sahibalejandro** [comment]
yup, that revision works! `1.0.6+b1063edf3e76a2ef68d2ba3eff686932f742c77c`

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.0.6 (released 10 minutes ago) which should fix this

Leave a comment if you still run into it
