### ISSUE TITLE
Incorrect version installed when using versions like ^1.0.0-[number]

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#6416]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```
bun add @poppinss/macroable@^1.0.0-7
```

> nothing to do with `@poppinss/macroable`

### What is the expected behavior?

the expected behavior is to install the same or greater (if exist) version of `^1.0.0-7`

### What do you see instead?

```bash
bun add v1.0.5 (1bf28e0d)

 installed @poppinss/macroable@1.0.0-0


 1 package installed [1.54s]
```

### Additional information

this works on `Bun 1.0.4`

```
bun add @poppinss/macroable@^1.0.0-7
```

```bash
bun add v1.0.4 (745b6b94)

 installed @poppinss/macroable@1.0.0-8


 1 packages installed [5.00ms]
```

**Comment by dylan-conway** [comment]
this is a regression introduced by #6312 . Will have a fix merged soon
