### ISSUE TITLE
crypto.sign/crypto.verify one-shot methods don't work with one-shot algorithms

### ISSUE THREAD

**Issue by panva** [oven-sh/bun#6418]
### What steps can reproduce the bug?

```
const { privateKey } = require('crypto').generateKeyPairSync('ed25519')
require('crypto').sign(undefined, Buffer.from('foo'), privateKey)
```

### What is the expected behavior?

A buffer with the signature is returned.

### What do you see instead?

`Unknown message digest` error is raised instead because the one-shot implementation just depends on the createSign API which is not meant to work with the one-shot sign algorithms like ed25519

### Additional information

```
➜  jose git:(main) node
Welcome to Node.js v18.18.1.
Type ".help" for more information.
> const { privateKey } = require('crypto').generateKeyPairSync('ed25519')
undefined
> require('crypto').sign(undefined, Buffer.from('foo'), privateKey)
<Buffer 38 5b 58 fc ca eb b5 a5 43 6a 2a 5b c4 c8 ea 21 d4 96 42 27 61 47 33 a6 52 f7 a8 76 69 69 e3 c4 f4 76 44 35 00 f5 37 11 0b d9 89 e2 ab bd 3d ca 47 38 ... 14 more bytes>
> 
```

**Comment by elmpp** [comment]
This prevents usage of the popular `ssh2` library at this point - https://github.com/mscdex/ssh2/blob/master/lib/protocol/constants.js#L22

**Comment by elmpp** [comment]
@panva can you suggest any workaround at all? Perhaps a pure-js library replacement for crypto.sign() ??

I'm a bit out of my depth here

--- 

E2A, is there a way to call nodejs:crypto.sign() in another process 🤷

**Comment by panva** [comment]
> @panva can you suggest any workaround at all? Perhaps a pure-js library replacement for crypto.sign()

An unmaintained pure-js library serving as a polyfill here is the very reason why this problem exists. The only solution is that Bun implements these APIs properly.

They should IMHO not be used at all until then. The only trusted crypto interface in Bun for now remains the Web Crypto API implementation exposed on the global scope.

**Comment by elmpp** [comment]
It's a shame 😞

I'm exploring spawning processes to 'node -e crypto.sign()' in the meantime

Thanks for the reply
