### ISSUE TITLE
`bun upgrade` wrongly reporting latest version is installed and refusing to actually upgrade the package

### ISSUE THREAD

**Issue by wojtekmaj** [oven-sh/bun#6422]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

package.json:
```json
  "bun-types": "^1.0.3"
```

bun.lockb:
```yml
bun-types@^1.0.3:
  version "1.0.4"
  resolved "https://registry.npmjs.org/bun-types/-/bun-types-1.0.4.tgz"
  integrity sha512-MIXp8MXPqzjjDrBs2fNzODFgFB+Mkl/OdTsPjYaefRoBt+Bk8VEJc3S1bbs6pvBi/wCpPf/ZSmzfIyZ5w4gAMg==
```

In these circumstances, I ran:
```
wmaj@MacBook-Air server % bun upgrade bun-types --dev
Congrats! You're already on the latest version of bun (which is v1.0.5)
```

Double checked my node_modules, and I definitely had bun-types 1.0.4 installed at this moment.

### What is the expected behavior?

`bun upgrade` to correctly recognize old version of a package is installed and install a new one

### What do you see instead?

`bun upgrade` wrongly reporting latest version is installed and refusing to actually upgrade the package

**Comment by Electroid** [comment]
`bun upgrade` is a command to upgrade the Bun CLI to the latest version. What you want is `bun update`, which will update your dependencies. However, we don't yet support updating a single package, see: #6419

**Comment by wojtekmaj** [comment]
It's `bun update` 💀 I'm an idiot
