### ISSUE TITLE
Print warning on omitted lifecycle scripts

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#6428]
### What is the problem this feature would solve?

The `trustedDependencies` feature silently ignore lifecycle scripts if not listed in the trusted dependency list. This creates hugely suboptimal UX, e.g. `supabase` not working.

### What is the feature you are proposing to solve the problem?

Bun should print a warning, e.g.: **Not running 'postinstall' lifecycle hook for 'supabase', because it's not listed in 'trustedDependencies'. See https://bun.sh/docs/cli/install#trusted-dependencies for more info.**

**Comment by dylan-conway** [comment]
As of v1.0.31 we've added a message in the install summary with the number of postinstall scripts that were blocked. We've also added `bun pm untrusted/trust/default-trusted` for managing packages with scripts. https://bun.sh/docs/cli/pm#untrusted

![Image](https://github.com/user-attachments/assets/156fd01b-d5d3-47b5-ac3c-f35e70d86474)
