### ISSUE TITLE
hoisting does not hoist `npm:` specifiers

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#6433]
### What steps can reproduce the bug?

really easy to reproduce with the overrides branch, like

```
{
  "overrides": {
    "a": "npm:b"
  },
  "dependencies": {
    "something-that-depends-on-a": "*"
  }
}
```

this theoretically should reproduce for any existing package that depends on a `npm:` specifier.

### What is the expected behavior?

hoist the dep at `node_modules/a`

### What do you see instead?

it is instead located at `node_modules/something-that-depends-on-a/node_modules/a`

**Comment by dylan-conway** [comment]
This is fixed as of bun `v1.1.13` in #11630
