### ISSUE TITLE
Prettier breaks in github actions `1.0.5`

### ISSUE THREAD

**Issue by darwin808** [oven-sh/bun#6439]
### What version of Bun is running?

1.0.5

### What platform is your computer?

linux

### What steps can reproduce the bug?

i have this script in package.json  `prettier --check . `

### What is the expected behavior?

should pass like before

![image](https://github.com/oven-sh/bun/assets/71545960/c33bdd94-843d-4e3f-9b8e-3e7413b217ab)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/71545960/d5c11b4d-a7cc-468a-afd1-f1a3b2ee8550)

### Additional information

i downgrade to `1.0.4` for temporary fix

**Comment by Jarred-Sumner** [comment]
Please upgrade to Bun v1.0.6 (released 10 minutes ago) which should fix this

Leave a comment if you still run into it

**Comment by darwin808** [comment]
![image](https://github.com/oven-sh/bun/assets/71545960/4a000013-e41c-41c0-9fc3-fba406e3bc99)

still error on `1.0.6`
