### ISSUE TITLE
`request.url` has default port of 80 for https

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#6443]
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Linux 5.15.0-86-generic aarch64 aarch64

### What steps can reproduce the bug?

```
Bun.serve({
  port: 443,
  tls: {...},
  fetch(request) {
    console.log(request);
  }
})
```

run this and do an https:// request

gives always: 

```
Request (0 KB) {
  method: "GET",
  url: "https:// ... :80/ ...",
  headers: Headers { ...
```

### What is the expected behavior?

`:80` should not be there

### What do you see instead?

`... :80/`

### Additional information

I checked request header also in chrome dev tools, and it is truly a tls connection.

**Comment by ghost** [comment]
I should add that `URL` gives the same, including `port: "80"`, which is clearly wrong.

```
URL {
  href: "https:// ... :80/",
  origin: "https:// ... :80",
  protocol: "https:",
  username: "",
  password: "",
  host: " ... :80",
  hostname: " ... ",
  port: "80",
  pathname: "/",
  hash: "",
  search: "",
  searchParams: {},
  toJSON: [Function: toJSON],
  toString: [Function: toString]
}
```

**Comment by ghost** [comment]
upgrading to release `1.0.6` does not change the behavior

**Comment by inmativ** [comment]
I have this error on version 1.1.29
