### ISSUE TITLE
Hoisting peer dependencies breaks React Native

### ISSUE THREAD

**Issue by MariuzM** [oven-sh/bun#6445]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Run 
```
bun install 
bun run dev
```

### What is the expected behavior?

Should start app like it did on .4 version

### What do you see instead?

<img width="1452" alt="image" src="https://github.com/oven-sh/bun/assets/36937039/8635728d-4ecb-476f-9b7c-184f8510e18c">

### Additional information

Repo: https://github.com/MariuzM/bun-and-expo

**Comment by MariuzM** [comment]
Comparing node_modules i get
<img width="666" alt="image" src="https://github.com/oven-sh/bun/assets/36937039/0d3670b3-10fa-4343-85bf-0d797046bf31">

And on the .6 i see that it also adds node_modules in each package. not sure if this is peerDep related, but then why without them was working fine on .4?

**Comment by MariuzM** [comment]
Creating a file and adding this solves the issue but is this how it should be? 
<img width="197" alt="image" src="https://github.com/oven-sh/bun/assets/36937039/f2689440-5173-404c-aa46-4dd5d1967338">

**Comment by Jarred-Sumner** [comment]
Definitely a bug with hoisting peer dependencies. @dylan-conway will take a look this week

**Comment by dylan-conway** [comment]
@MariuzM could you try this again with bun v1.0.7. We fixed a peerDependency bug that would cause some packages to be installed incorrectly/multiple times

**Comment by MariuzM** [comment]
@dylan-conway checked on this pub project and personal 2 projects all working great now thank you gents

**Comment by MariuzM** [comment]
@dylan-conway but i did notice slow downs with bun install but maybe its just today or me, but something i have not noticed previously
