### ISSUE TITLE
White text on a white background!

### ISSUE THREAD

**Issue by pookah-net** [oven-sh/bun#645]
### Version

0.1.3

### Platform

Mac OS

### What steps will reproduce the bug?

Install bun.

The text:

```
exec /bin/zsh
bun --help
```

is printed with white text, on a white background! (My terminal is always set to white.)

### How often does it reproduce? Is there a required condition?

Just on install? I haven't checked any other text output. (--help looks okay; it prints black on white.)

### What is the expected behavior?

See above

### What do you see instead?

See above

### Additional information

As a plea to anyone writing a CLI... please don't assume that everyone else uses a black background for their terminal windows!

**Comment by AltriusRS** [comment]
What terminal do you use? Because this seems less like an issue with Bun, and more like an issue with your terminal's color mapping.

White backgrounds should always be followed by inverting the black and white colors within your theme settings. Terminal's dont really have a way of announcing their color mappings to the program, so it isnt exactly a trivial task to auto-detect the user's background color.

You can read some more information on how colors work in the terminal [here](https://chrisyeh96.github.io/2020/03/28/terminal-colors.html).

**Comment by pookah-net** [comment]
I use iTerm2, with oh-my-zsh.

I believe the problem is in `bun/src/cli/install.sh`, lines 143 to 156:

```    if test -f $HOME/.zshrc; then
        echo -e "\n# bun\nexport BUN_INSTALL=\"$bun_install\"" >>"$HOME/.zshrc"
        echo -e "export PATH=\"\$BUN_INSTALL/bin:\$PATH\"" >>"$HOME/.zshrc"
        echo ""
        echo -e "$Dim Added \"$bin_dir\" to \$PATH in \"~/.zshrc\"$Color_Off"

        echo ""
        echo -e "To get started, run"
        echo -e "$BWhite"
        echo -e "   exec $SHELL"
        echo -e "   bun --help$Color_Off"
        echo ""
        exit 0
    else
```

The text color is set to white.

**Comment by AltriusRS** [comment]
the color is actually set to `\033[1;37m`, which is what $BWHITE, whilst yes, this means the text's expected color is white, what is actually coming out of your terminal should be whatever color your color scheme has `white` mapped to. if that is still mapped to white, and not black, then you will only see white on your white background.

This issue does not seem to be related to the installation script whatsoever.

**Comment by pookah-net** [comment]
I have my terminal set to the default light color scheme. Therefore, if a script specifies that some text be printed in white, the text is printed as white on a white background. The fact that the install script sets that particular bit of text to white, so it's printed as white on white. That makes it absolutely related to the installation script.

I'm not at all sure why you're discussing color mappings; I'm especially confused why you think I would take the time to fiddle with color mappings? If the text in a script is set to print in white, and the terminal has a white background, that text gets printed as white text on a white background. That, to me, is a coder-introduced UI-issue. Would it not be simpler to not specify the color of the text, and let the terminal just print it?

Change this:
```
        echo -e "To get started, run"
        echo -e "$BWhite"
        echo -e "   exec $SHELL"
        echo -e "   bun --help$Color_Off"
```

To this:
```
        echo -e "To get started, run"
        echo -e "   exec $SHELL"
        echo -e "   bun --help"
```

And then the message gets printed in whatever is the default color for the terminal.

**Comment by alexkuz** [comment]
Can confirm, it does print white on white

To reproduce:
- delete ~/.bun, remove bun paths from .zshrc
- create and switch to light profile in iTerm2
- call `curl https://bun.sh/install | bash`

Should be just bold instead of bold white
