### ISSUE TITLE
bun (1.0.6) (after creation of sst project) throws error "Argument of type 'Stack' is not assignable to parameter of type 'Construct'.ts(2345)" .

### ISSUE THREAD

**Issue by Kizeko** [oven-sh/bun#6465]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```
bunx create-sst@latest my-sst-app
cd my-sst-app
bun i
```

### What is the expected behavior?

```
const api = new Api(stack, "api", {
    defaults: {
      function: {
        bind: [bus],
      },
    },
    routes: {
      "GET /": "packages/functions/src/lambda.handler",
      "GET /todo": "packages/functions/src/todo.list",
      "POST /todo": "packages/functions/src/todo.create",
    },
  });
```

should not show an error as it is valid code.
**(This works perfectly for version of bun before 1.0.6)**

### What do you see instead?

```
const api = new Api(stack, "api", {
    defaults: {
      function: {
        bind: [bus],
      },
    },
    routes: {
      "GET /": "packages/functions/src/lambda.handler",
      "GET /todo": "packages/functions/src/todo.list",
      "POST /todo": "packages/functions/src/todo.create",
    },
  });
```

Typescript will show an error ```Argument of type 'Stack' is not assignable to parameter of type 'Construct'``

**Comment by Electroid** [comment]
Is this an error from TypeScript, or Bun?

**Comment by Kizeko** [comment]
> Is this an error from TypeScript, or Bun?

It's an error from typescript but supposedly caused by bun (dependencies installation i guess ?) because typescript doesn't throw errors when creating the project with bun 1.0.5.

afaik this error normally occurs when there are versions mismatch with aws-cdk-lib / constructs / sst

**Comment by Kizeko** [comment]
I managed to fix the issue by using the newly supported bun feature "overrides"

Adding : 
```
"overrides": {
    "aws-cdk-lib": "2.95.1",
    "constructs": "10.2.69"
},
```

There was a version mismatch between :
```
node_modules/aws-cdk-lib/node_modules/constructs/lib/construct
```
and
```
node_modules/constructs/lib/construct
```
