### ISSUE TITLE
Buffer.write fails to write value >= 0x80

### ISSUE THREAD

**Issue by aardvarkk** [oven-sh/bun#6467]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 5.10.0-26-amd64 x86_64 unknown

### What steps can reproduce the bug?

I have submitted [this pull request](https://github.com/oven-sh/bun/pull/6466) which demonstrates a failing test.

I noticed this issue because I tried to use the library `bwip-js` to generate a PNG image within bun. The image that's output has the first byte in the image set as `0x09` instead of `0x89` (which is what the first byte of a PNG needs to be). In other words it generates an invalid/corrupt PNG image if run in bun. If I run the following code in NodeJS I see `89` logged out, but when I run it in bun I see `09` logged out.

```
const buffer = Buffer.alloc(1);
buffer.write('\x89', 0, 'binary');
console.log(buffer.toString('hex'));
```

I believe there is a signed vs unsigned byte issue somewhere in the guts of bun. This is my theory because I see that 0x80 maps to 0x00, and 0xFF maps to 0x7F in the output. Probably not a coincidence that it happens immediately beyond 0x7F -- the upper limit of a signed byte.

### What is the expected behavior?

For the submitted test, `0x80` should be the first byte in the buffer.

### What do you see instead?

For the submitted test, `0x00` is the first byte in the buffer.

**Comment by Hanaasagi** [comment]
https://github.com/oven-sh/bun/blob/4fab8fee2145607714d5012623ba00523c1b92b9/src/bun.js/webcore/encoding.zig#L976-L989


`binary` is alias for `latin1`.  The range of `.latin1` encoding is from `0x00` to `0xFF`, while `.ascii` encoding covers the range from `0x00` to `0x7F`. Here, converting a `.latin1` character to `.ascii` resulted in truncation of values greater than `0x7F`.
