### ISSUE TITLE
express modules not supported!

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#6469]
### What version of Bun is running?

1.0.4

### What platform is your computer?

Microsoft Windows NT 10.0.22000.0 x64

### What steps can reproduce the bug?

when I try running express with separated modules, it doesn't work as in nodejs

### What is the expected behavior?

to accept modules to connect together within express projects running via bun

### What do you see instead?

errors and bugs

**Comment by Electroid** [comment]
Can you share some example code of how to reproduce this?

**Comment by Bader-Idris** [comment]
please wait for some days, before closing it, I'll get to it when I have some spare time 😀

**Comment by Bader-Idris** [comment]
using ts with its configs solved the js module bug!
