### ISSUE TITLE
bun is extremely slow in my computer

### ISSUE THREAD

**Issue by NelsonDLZ** [oven-sh/bun#647]
### Version

0.1.3

### Platform

Linux nelson-EasyNote-TE11BZ 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

When I first installed bun, I ran into the problem described in the "Illegal Instruction (Core Dumped)" section.
and none of the commands worked. So I followed the recommendations of this section section and this first problem was solved.
But.
Even if the bun --help command works, the console shows:
bun was installed successfully to /home/nelson/.bun/bin/bun
bash : ligne 113 :  9503 Instruction non permise (core dumped) IS_BUN_AUTO_UPDATE="true" $exe completions > /dev/null 2>&1
Run 'bun --help' to get started

In a bun project, a simple console.log takes 55 seconds to execute. As for the example code of sever, the execution time is even longer.

When I try to install a package, the console responds:
warn: Slow filesystem detected. If /home/nelson/.bun/install/cache is a network drive, consider setting $BUN_INSTALL_CACHE_DIR to a local folder.

### How often does it reproduce? Is there a required condition?

It reproduce every time

###  After the last bun's installation:

bun was installed successfully to /home/nelson/.bun/bin/bun
bash : ligne 113 :  9503 Instruction non permise (core dumped) IS_BUN_AUTO_UPDATE="true" $exe completions > /dev/null 2>&1
Run 'bun --help' to get started

### When I try to install a package, the console responds:
warn: Slow filesystem detected. If /home/nelson/.bun/install/cache is a network drive, consider setting $BUN_INSTALL_CACHE_DIR to a local folder.

**Comment by FinnRG** [comment]
This is the expected behavior. The SDE workaround makes bun significantly slower. That's the reason why we call it a workaround and push for a true AVX1 build in #67.

**Comment by NelsonDLZ** [comment]
Indeed.
Strangely, I zapped this warning. thank you for that clarification.
