### ISSUE TITLE
unzip-is-required

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#6470]
### What is the issue?

when I try to install bun in my WSL, with your provided curl command, it throws this message:

```sh
error: unzip is required to install bun (see: https://github.com/oven-sh/bun#unzip-is-required)
```

so, I go to the required link, and suddenly I find nothing, the hash `unzip-is-required` doesn't even exist, I search for it with `ctrl + f`, and nothing appears!

**Comment by ImLunaHey** [comment]
Correct link is https://github.com/oven-sh/bun/blob/main/docs/troubleshooting.md#unzip-is-required

**Comment by Bader-Idris** [comment]
that helped me, but please update the link into the stout when running the curl script, for future installations

**Comment by ImLunaHey** [comment]
Maybe reopen this issue for that?
