### ISSUE TITLE
fetch failed when url not contain 'www' on macos

### ISSUE THREAD

**Issue by relaxslow** [oven-sh/bun#6473]
### What version of Bun is running?

1.06

### What platform is your computer?

macos

### What steps can reproduce the bug?

run the following on mac
const res = await fetch("https://blueprowler.com/Creative/SanctuaryMedicinals/SanctuaryMedicinals-1/index1.3.html");
const result= await res.text()
console.log( result)

### What is the expected behavior?

get the result

### What do you see instead?

program stuck there

### Additional information

I report this  when 1.04 comes , but the issue still there not fixed

**Comment by sh4den** [comment]
Can you give us the full output from the std ?

**Comment by relaxslow** [comment]
just no output , the program stuck there 
<img width="240" alt="image" src="https://github.com/oven-sh/bun/assets/5476899/b695c271-4b83-45b4-a5e6-182c2a919901">

**Comment by relaxslow** [comment]
after long time waiting , the program end with the following output 
<img width="438" alt="image" src="https://github.com/oven-sh/bun/assets/5476899/f8f83a2a-4a8f-4c18-bfb4-6ebea68c7d33">

**Comment by sh4den** [comment]
Are you able to access the URL with a curl request ?

**Comment by relaxslow** [comment]
yes , no problem with curl request and the url can be visit through browser

**Comment by relaxslow** [comment]
and there is no problem on linux , only happened on macos

**Comment by sh4den** [comment]
Sounds like there is an issue there : https://github.com/oven-sh/bun/blob/1bad64bc5e6fc2757a99dc7529d11c86835300bb/src/bun.js/webcore/response.zig#L1137C122-L1137C122. I'm going to investigate

**Comment by relaxslow** [comment]
oh yeah, thank you very much

**Comment by sh4den** [comment]
So fetch works only when there is WWW only on this website or every website ?

**Comment by relaxslow** [comment]
ok, I try on other websites, looks that  this only happened on the blueprowler.com. why ? 
another thing worth mention that there is no such error when I use Nodejs or Deno

**Comment by relaxslow** [comment]
I checked my DNS settings , is this matters?
<img width="1265" alt="image" src="https://github.com/oven-sh/bun/assets/5476899/026106dc-e5ac-4eb9-8585-2839bd560ee2">

**Comment by relaxslow** [comment]
any update on this?

**Comment by sh4den** [comment]
It look like that the problem is from your side, do you have any kind of firewall on your website ?

**Comment by relaxslow** [comment]
yes, I set firewall on my digital ocean server . but why nodejs and deno they can get the content with the url without 'www'
