### ISSUE TITLE
`bun upgrade` fails with `error failed to verify bun (exit code: 6)`

### ISSUE THREAD

**Issue by bacebu4** [oven-sh/bun#6477]
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 21.1.0 arm64 arm

### What steps can reproduce the bug?

1. Use v1.0.2
2. Try to upgrade to v1.0.6

### What is the expected behavior?

No error being seen

### What do you see instead?

`error failed to verify bun (exit code: 6)`

### Additional information

Haven't found any similar issues, also there is no easy way to uninstall bun (deleting ~/.bun didn't help as was suggested in #981)

What else info do I need to provide in order to reproduce this? And what steps do I need to do in order to upgrade?

**Comment by sh4den** [comment]
Sounds like there is an issue with the ChildProcess. I tried on my own and it worked. The process is exited with a Signal Abort. I was not able to reproduce the error with the same config. I will check that later

**Comment by bacebu4** [comment]
Well, I was able to uninstall it, no problem regarding uninstall process anymore

**Comment by bacebu4** [comment]
After deleting the bun I could not install with any described method on docs

- While trying NPM I see the same error as here #5806 
- While trying Brew I see the same error as here #6035  

Looks really related to the last issue I mentioned. So closing since it's kinda duplicate

**Comment by gkiely** [comment]
I'm running into this issue, is there a suggested fix, I'm on mac OSX 12.2.1.

<img width="374" alt="image" src="https://github.com/oven-sh/bun/assets/1948935/9e532109-fdba-4f5f-91d8-0753c47ea04e">

**Comment by bacebu4** [comment]
> I'm running into this issue, is there a suggested fix, I'm on mac OSX 12.2.1.
> 
> <img alt="image" width="374" src="https://user-images.githubusercontent.com/1948935/277404426-9e532109-fdba-4f5f-91d8-0753c47ea04e.png">

As far as I could understood from related discussions – just upgrade your mac version or use 1.0.2

**Comment by gkiely** [comment]
> > I'm running into this issue, is there a suggested fix, I'm on mac OSX 12.2.1.
> > <img alt="image" width="374" src="https://user-images.githubusercontent.com/1948935/277404426-9e532109-fdba-4f5f-91d8-0753c47ea04e.png">
> 
> As far as I could understood from related discussions – just upgrade your mac version or use 1.0.2

Upgrading to 12.7 worked, thanks.

**Comment by lnfel** [comment]
I'm using a preistoric macOS 10.15, am I doomed?
