### ISSUE TITLE
Can't find variable: navigator

### ISSUE THREAD

**Issue by l4zy0n3** [oven-sh/bun#648]
### Version

0.1.3

### Platform

Linux d00m 5.18.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:13 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. `window` variables are not directly accessible in react and next js projects
Have to use the following workaround
```javascript
   let navigator = window.navigator;
    navigator.geolocation.getCurrentPosition
```
### How often does it reproduce? Is there a required condition?

Reproducible everytime

### What is the expected behavior?

Should be able to access navigator directly

### What do you see instead?

`let navigator = window.navigator;`

**Comment by Jarred-Sumner** [comment]
Does it work when using `next dev`? `window` is not a global on servers

It might become a global in Bun later.

**Comment by l4zy0n3** [comment]
There's another issue when using `next dev`
It is unable to find the module `react`.
```bash
$ next dev
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /home/yt/.bun/install/global/node_modules/next/dist/server/utils.js
- /home/yt/.bun/install/global/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/yt/.bun/install/global/node_modules/next/dist/server/utils.js:11:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/yt/.bun/install/global/node_modules/next/dist/server/utils.js',
    '/home/yt/.bun/install/global/node_modules/next/dist/bin/next'
  ]
}
```

**Comment by l4zy0n3** [comment]
> There's another issue when using `next dev` It is unable to find the module `react`. I'll post the concrete error later

This issue, only occurs

> There's another issue when using `next dev` It is unable to find the module `react`.
> 
> ```shell
> $ next dev
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module 'react'
> Require stack:
> - /home/yt/.bun/install/global/node_modules/next/dist/server/utils.js
> - /home/yt/.bun/install/global/node_modules/next/dist/bin/next
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/yt/.bun/install/global/node_modules/next/dist/server/utils.js:11:37)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/yt/.bun/install/global/node_modules/next/dist/server/utils.js',
>     '/home/yt/.bun/install/global/node_modules/next/dist/bin/next'
>   ]
> }
> ```

This issue only occurs when `next` is installed using `bun install next`
Closing this issue, creating another

**Comment by l4zy0n3** [comment]
Created issue https://github.com/oven-sh/bun/issues/718#issue-1305290063
