### ISSUE TITLE
willCache defined after it's used

### ISSUE THREAD

**Issue by lorenbrichter** [oven-sh/bun#6481]
Was trying to figure out the real difference between `prepare` and `query`, and noticed this, not sure how it ever worked at all? `willCache` is defined after it's used. (Also is it me or is the caching code more complex than it needs to be?)

https://github.com/oven-sh/bun/blob/4fab8fee2145607714d5012623ba00523c1b92b9/src/js/bun/sqlite.ts#L323C11-L323C20

**Comment by Electroid** [comment]
Thanks, nice catch.
