### ISSUE TITLE
1.0.6 Breaking change 🚨 /bin/bash: --: invalid option

### ISSUE THREAD

**Issue by MarkLyck** [oven-sh/bun#6486]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

- Install bun version 1.0.6
- run `bun i` in a project with package.json that's using husky

### What is the expected behavior?

bun install should install the dependencies without any errors like it does in 1.0.5

### What do you see instead?

I get the following error:

```
bun i
[0.23ms] ".env"
bun install v1.0.6 (969da088)
 + dayjs@1.11.9 (v1.11.10 available)
 + graphql@16.8.0 (v16.8.1 available)
 + react-router-dom@6.15.0 (v6.16.0 available)
allexport      	off
braceexpand    	on
emacs          	on
errexit        	off
errtrace       	off
functrace      	off
hashall        	on
histexpand     	on
history        	on
ignoreeof      	off
interactive-comments	on
keyword        	off
monitor        	off
noclobber      	off
noexec         	off
noglob         	off
nolog          	off
notify         	off
nounset        	off
onecmd         	off
physical       	off
pipefail       	off
posix          	off
privileged     	off
verbose        	off
vi             	off
xtrace         	off
/bin/bash: --: invalid option

 7 packages installed [692.00ms]
```

**Comment by MarkLyck** [comment]
The culprit does not seem to be a package but my husky prepare statement:

```
"prepare": "husky install"
```

Removing this from my scripts will make the error stop occurring, is bun not compatible with husky anymore?

Same error happens when using `postinstall` to install husky 😞

**Comment by paperclover** [comment]
<img width="843" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/79167eeb-5d05-43d5-9afa-fad94f21a071">
cannot reproduce. maybe it depends on what your git hook scripts are? i'm not sure.

**Comment by MarkLyck** [comment]
Hmmm in my case the only git hook script i have is `pretty-quick`

https://github.com/azz/pretty-quick#readme

runs prettier on my changed files. For reproduction, is there a stackblitz or something that has bun installed? Or do I have to manually make a public repo to share?

**Comment by featr** [comment]
I have the same issue. Again with husky present and lint-staged as a pre-commit hook.
The issue is not reproducible in 1.0.5

**Comment by dylan-conway** [comment]
we have a fix for this bug in canary that will land in bun v1.0.7 https://github.com/oven-sh/bun/commit/2f10398c74b771bce738d636429135a679f52bdb

**Comment by dylan-conway** [comment]
please reopen this issue if you continue to run into this error with `1.0.7`
