### ISSUE TITLE
Bun.listen never connects, never errors

### ISSUE THREAD

**Issue by runspired** [oven-sh/bun#6510]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
function debug(msg) { console.log(msg); }
const port = 7537;

await new Promise((resolve, reject) => {
  Bun.listen({
    port,
    hostname: 'localhost',
    socket: {
      data() {
        debug(`Port ${port} unexpectedly received data 🙈`);
      },
      open() {
        debug(`Port ${port} is available`);
        server.stop(true);
      },
      close() {
        debug(`Releasing ${port} for server use`);
        resolve();
      },
      connectError(socket, error) {
        debug(`Port ${port} received connectError event`);
        reject(error);
      },
      timeout() {
        debug(`Timeout while checking port ${port}`);
        reject(new Error(`Timeout while checking port ${port}`));
      },
      error(socket, e) {
        debug(`Port ${port} received error event`);
        reject(e);
      },
      end(socket) {
        debug(`Port ${port} received end event`);
        reject(new Error(`Port ${port} received end event`));
      }
    }
  });
})
```

### What is the expected behavior?

handlers fire once socket is available or socket connection has failed

### What do you see instead?

socket connection never established, error never thrown

**Comment by Jarred-Sumner** [comment]
`Bun.listen` returns a Promise

have you tried `await`'ing it?

**Comment by runspired** [comment]
@Jarred-Sumner no because the docs do not document it as having a return at all. I was wondering. If it were a promise though I'd still expect a global error to be thrown for the case where I run this and know the port is busy; however, even in that case it appears to just hang.

**Comment by runspired** [comment]
I can confirm I can await success. It still appears to not throw for the case where the port is in fact busy.

**Comment by liz3** [comment]
the question here is very implementation dependent, first of all what do you define as a error which should throw?
Id argue everything should theoretically throw in the current scope no matter what its relateed to socket creation/client/data.

But if you have a defined error handler that changes a lot because then do you `throw` the error or invoke the error handler to deal with the error instead of letting the callee(the socket api) throw?

**Comment by runspired** [comment]
@liz3 I'm specifically trying to detect if the port was already in use, and would expect an `EADDRINUSE` error to be thrown

**Comment by runspired** [comment]
(also note, the entire thing I'm trying to write here is just something to detect that a port is already in use, if Bun has an undocumented but public way of doing so already that is simpler, I'm all ears :D )

**Comment by liz3** [comment]
I think asking which exact error to throw is too specific here, this is a BUN api and thus does not inherently mean it needs to throw node errors, but keeping errors similar has benefits, i have a couple of prs awaiting review so il look into this.
The approach i would take is to invoke the error callback if defined and otherwise throw an error

**Comment by runspired** [comment]
@liz3 this isn't a node error or an exact error. I would expect if I asked `Bun` to listen on a port and it could not because the port was already in use that an error would be thrown. Currently Bun acts as though it is successfully listening on the port anyway. `EADDRINUSE` is not a "node" error. Its an HTTP spec error.

**Comment by Jarred-Sumner** [comment]
@runspired `Bun.listen` defaults to enabling [`SO_REUSEPORT`](https://blog.flipkart.tech/linux-tcp-so-reuseport-usage-and-implementation-6bfbf642885a) - this is not a bug, but it is not documented.

If you set `exclusive` to `true` in `Bun.listen`, it should do what you want.

**Comment by runspired** [comment]
@Jarred-Sumner thanks! I’ll give that a try

**Comment by liz3** [comment]
@Jarred-Sumner it might be a idea to default that to true, i think it might be a better default since its usually the expected behaviour, but correct with `exclusive` set to true it does throw.

**Comment by runspired** [comment]
I would definitely say its more expected as a default, but simply documenting it is the default and how to change it is also fine. Also documenting that listen etc. return promises would be useful. I'm going to close this as this seems to be an issue with documentation vs `Bun.listen` itself, though if you'd like me to open a documentation ticket I'd be happy to.
