### ISSUE TITLE
Recursion without base case running indefinitely

### ISSUE THREAD

**Issue by lucaspessivaldo** [oven-sh/bun#6530]
Bun version - 1.0.6
Platform - Linux 5.15.0-86-generic x86_64 x86_64

### What steps can reproduce the bug?

recursion.js
```js
//(λx.x x)(λx.x x)
(f => f(f))(f => f(f))
```
Running this code using Bun this run indefinitely does not stop. if you run the same code using node.js you get `Maximum call stack size exceeded` error.

I would like to know if Bun handles infinite recursion differently. or is it a bug?

`bun recursion.js`     run indefinitely
`node recursion.js`   Maximum call stack error

**Comment by liz3** [comment]
@lucaspessivaldo this seams to be a optimsation by jsc? 
If you "do" something within the recursion it will exit
```js
const f = (count = 0) => {
    if (count % 100 === 0) console.log(count);
    f(count + 1);
};
f();
```
<img width="583" alt="image" src="https://github.com/oven-sh/bun/assets/21298625/681a65bf-6841-4973-8dd3-bfbd2fc9509c">

**Comment by Electroid** [comment]
WebKit, which Bun is built-on, supports [tail-call optimization](https://webkit.org/blog/6240/ecmascript-6-proper-tail-calls-in-webkit/), whereas V8 does not. This is often a performance benefit, however, it does mean that certain code paths that stackoverflow in Node.js do not in Bun.
