### ISSUE TITLE
Unzip is required to install bun

### ISSUE THREAD

**Issue by johnfn** [oven-sh/bun#6534]
### What version of Bun is running?

1.0.6

### What platform is your computer?

ubuntu

### What steps can reproduce the bug?

`curl -fsSL https://bun.sh/install | bash`

I see:

```
error: unzip is required to install bun (see: https://github.com/oven-sh/bun#unzip-is-required)
```

### What is the expected behavior?

The link works :)

### What do you see instead?

The link does not work. There is no unzip-is-required heading.

**Comment by jatroconis** [comment]
For resolve this only execute

`sudo apt install unzip`

**Comment by ahmadlaiq** [comment]
The solution to resolve this error is to install `unzip` first. You can do this with the following command:

```bash
sudo apt install unzip

After installing unzip, try running the command to install bun again.

**Comment by Advaitgaur004** [comment]
Sometimes there is a broken dependency, and if  `sudo apt install unzip` is not working, try to do  **`apt --fix-broken install`** as this command is used to repair broken dependencies in your system. It automatically installs missing dependencies or fixes conflicts from incomplete package installations or upgrades. This helps ensure that your package manager and system are in a consistent state.
