### ISSUE TITLE
I want to know how to limit the memory size of bun. There is a problem with vite build.

### ISSUE THREAD

**Issue by duolabmeng6** [oven-sh/bun#6548]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

x64

### What steps can reproduce the bug?

https://github.com/duolabmeng6/GoEasyDesigner/tree/main/GoEasyDesigner/frontend
bun i
bun run build

The machine memory of 4G memory is completely full... I want to limit memory usage
```
node --max-old-space-size=4096 ./node_modules/.bin/vite build
```

**Comment by fxck** [comment]
Couldn't find anything about this except this issue and this https://webdeveloper.com/bounties/how-does-bun-handle-memory-allocation-compared-to-node-js/

But doing `node --max-old-space-size=8192 bun build` doesn't quite seem right?

**Comment by Jarred-Sumner** [comment]
The equivalent of `--max-old-space-size` in Bun is the `BUN_JSC_forceRAMSize` environment variable, like:

```sh
BUN_JSC_forceRAMSize=134217728 bun script.js
```

It doesn't precisely do the same thing as it does in V8 .This will cause the GC to run more frequently. It pretends to be the ram size given.

**Comment by Jarred-Sumner** [comment]
> is the value passed to forceRAMSize in bytes? 

yeah


> and does bun have any memory limits by default?

it adapts to how much memory the system reports is available. so if the system says there's 4 GB, it will assume it can use up to that much memory. When it gets to about 80% of the limit, it runs the garbage collector much more frequently until it drops below 80%

**Comment by dayblox** [comment]
@Jarred-Sumner You have previously said the value was in kilobytes, did it change since? (https://github.com/oven-sh/bun/issues/1824#issuecomment-1596204156)
What's the minimum value one could set this env variable to?
Does using --smol clash or override this env variable?
I'm asking because it doesn't seem to work for me.

**Comment by NBMSacha** [comment]
Doesn't seem to work for us either

**Comment by ddibenko** [comment]
doesn't work for me either

**Comment by skipjack** [comment]
Yeah, not working for me either (trying in relation to a netlify build error).

**Comment by Ed1ks** [comment]
Doesnt work. Ram usage is going rocket till it crashes. While Node build uses maybe 1gb till it finishes. I have huge solving this, as I am using CI/CD with limited ressources.
