### ISSUE TITLE
Symlink /tmp/bun-node/node doesn't work after upgrading bun to a new version with Homebrew

### ISSUE THREAD

**Issue by feefs** [oven-sh/bun#6561]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Ensure there is no other `node` installation on your system, upgrade/downgrade bun with Homebrew to change it's version, then try running `bunx`. The symlink at `/tmp/bun-node/node` no longer points to a valid bun installation, and it should error with:

`env: node: No such file or directory`

In the screenshot below I installed the older formula `bun@1.0.5`, meaning the Cellar directory structure isn't the same as the usual case of upgrading to the latest version (but the essence is still the same):

<img width="609" alt="ss" src="https://github.com/oven-sh/bun/assets/25848712/8e08bf3e-909d-49b2-8ec7-73aeff1ada58">

### What is the expected behavior?

The expected behavior should be that `bunx` still works after upgrading with Homebrew.

### What do you see instead?

The symlink `/tmp/bun-node/node` no longer points to a valid bun installation, and leads to errors when running `bunx`.

### Additional information

I'm using Homebrew for my bun installation, and it creates new directories with each bun version (`1.0.5`, `1.0.6`) in the Cellar. Running `brew upgrade` creates a new one every time.

If I use `bun upgrade` on my homebrew installation, it mutates the installation in place and won't break the symlink, but the version won't match the directory version number in the Cellar.

Right now, it seems like `bunx` won't do anything to the symlink if it already exists ([src/cli/run_command.zig](https://github.com/oven-sh/bun/blob/e91436e5248d947b50f90b4a7402690be8a41f39/src/cli/run_command.zig#L456)). I'm not sure if the best solution would be to have `bunx` overwrite the symlink, or have package installers (not sure if homebrew is the only one with this problem) delete the `/tmp/bun-node/node` symlink.

**Comment by paperclover** [comment]
this was fixed a couple of versions ago, by putting a build hash in the temp path used
