### ISSUE TITLE
Visual Studio Code Debugger shows Array in wrong order

### ISSUE THREAD

**Issue by jakobgetz** [oven-sh/bun#6565]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

file: test.js
```
let x = ['GlobalGet', 'global', '1']
console.log(x)
```
- Put breakpoint at line 2
- Run it with the Bun debugger in visual studio code
- In the debugger side pane in the watch panel, watch the variable `x`

### What is the expected behavior?

seeing something like: `x: Array(3) ['GlobalGet', 'global', '1']`

### What do you see instead?

`x: Array(3) ['1', 'GlobalGet', 'global']`

### Additional information

It seems to me that the elements of arrays in the display of the debugger side pane get ordered by their ascii code instead of their index.

**Comment by Hanaasagi** [comment]
It might have been fixed by https://github.com/oven-sh/bun/pull/6379 in bun 1.0.5.

**Comment by Electroid** [comment]
This was fixed but not published, it will be live in a few minutes.
