### ISSUE TITLE
Error in make setup

### ISSUE THREAD

**Issue by TaduJR** [oven-sh/bun#6576]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 6.1.21.2-microsoft-standard-WSL2+ x86_64 x86_64

### What steps can reproduce the bug?

"make setup" command in bun repo

### What do you see instead?

zig build-obj bun-debug Debug native-native-gnu.2.27: error: the following command terminated unexpectedly:
/home/natu/.bun/install/global/node_modules/@oven/zig-linux-x64/zig build-obj -freference-trace=16 /mnt/c/Users/Natu/Desktop/Desktop/bun/root.zig -lc -fno-strip --eh-frame-hdr --emit-relocs -ffunction-sections --cache-dir /mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache --global-cache-dir /home/natu/.cache/zig --name bun-debug -fno-compiler-rt -fno-stack-check -fno-omit-frame-pointer -target native-native-gnu.2.27 -mcpu haswell --mod build_options::/mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache/c/9958f8b1e945d9d315546e5bb773da92/options.zig --mod async_io::/mnt/c/Users/Natu/Desktop/Desktop/bun/src/io/io_linux.zig --deps async_io,build_options --main-mod-path /mnt/c/Users/Natu/Desktop/Desktop/bun --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-debug.o transitive failure
│  ├─ zig build-obj bun-debug Debug native-native-gnu.2.27 failure
│  └─ zig build-obj bun-debug Debug native-native-gnu.2.27 (+1 more reused dependencies)
└─ zig build-obj bun-debug Debug native-native-gnu.2.27 (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache/o/fca6fd780c1695be22d89ea900ce0ed2/build /home/natu/.bun/install/global/node_modules/@oven/zig-linux-x64/zig /mnt/c/Users/Natu/Desktop/Desktop/bun /mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache /home/natu/.cache/zig obj -freference-trace -freference-trace -Dcpu=native
make[3]: *** [Makefile:1096: dev-obj-track] Error 1
make[3]: Leaving directory '/mnt/c/Users/Natu/Desktop/Desktop/bun'
make[2]: *** [Makefile:1940: zig-no-link] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1607: src/bun.js/debug-bindings-obj/BunObject.o] Error 255
make[3]: *** Waiting for unfinished jobs....
In file included from src/bun.js/bindings/CodeCoverage.cpp:2:
In file included from /mnt/c/Users/Natu/Desktop/Desktop/bun/src/bun.js/bindings/ZigSourceProvider.h:1:
/mnt/c/Users/Natu/Desktop/Desktop/bun/src/bun.js/bindings/headers.h:301:269: warning: 'nonnull' attribute only applies to pointer arguments [-Wignored-attributes]
CPP_DECL void JSC__JSValue___then(JSC__JSValue JSValue0, JSC__JSGlobalObject* arg1, JSC__JSValue JSValue2, JSC__JSValue(* ArgFn3)(JSC__JSGlobalObject* arg0, JSC__CallFrame* arg1), JSC__JSValue(* ArgFn4)(JSC__JSGlobalObject* arg0, JSC__CallFrame* arg1)) __attribute__((nonnull (3, 4)));
                                                                                    ~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                   ^        ~
1 warning generated.
make[3]: Leaving directory '/mnt/c/Users/Natu/Desktop/Desktop/bun'
make[2]: *** [Makefile:1932: cpp-no-link] Error 2
make[2]: Leaving directory '/mnt/c/Users/Natu/Desktop/Desktop/bun'
make[1]: *** [Makefile:1944: dev] Error 2
make[1]: Leaving directory '/mnt/c/Users/Natu/Desktop/Desktop/bun'
make: *** [Makefile:1949: setup] Error 2

### Additional information

_No response_

**Comment by yadav-saurabh** [comment]
I am also facing issues in make.

Just today I synced the code and started facing the build issue. My last successful build was for the sync when bun 1.0.6 was released.

Even did a new clone and ran `make setup` but still faced the same error
I am using Arch Linux x86_64  Kernel  6.5.7-arch1-1


I am getting a different error log:
```
make[1]: Entering directory '/home/saurabh/Documents/opensource/bun'
mkdir -p /home/saurabh/Documents/opensource/bun/packages/debug-bun-linux-x64
bun .scripts/make-dev-timer.ts /home/saurabh/.bun/bin/zig build obj -freference-trace -Dcpu="native"
/home/saurabh/Documents/opensource/bun/build.zig:236:10: error: no field named 'main_mod_path' in struct 'Build.ObjectOptions'
        .main_mod_path = .{ .cwd_relative = b.pathFromRoot(".") },
         ^~~~~~~~~~~~~
/home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/Build.zig:651:27: note: struct declared here
pub const ObjectOptions = struct {
                          ^~~~~~
referenced by:
    build: /home/saurabh/Documents/opensource/bun/build.zig:141:5
    runBuild__anon_7172: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/Build.zig:1833:37
    steps__anon_6925: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/build_runner.zig:914:29
    usage__anon_6918: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/build_runner.zig:941:14
    usageAndErr__anon_6710: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/build_runner.zig:1031:10
    main: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/build_runner.zig:301:20
    callMain: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/start.zig:574:32
    initEventLoopAndCallMain: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/start.zig:508:34
    callMainWithArgs: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/start.zig:458:12
    posixCallMainAndExit: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/start.zig:414:39
    _start: /home/saurabh/.bun/install/global/node_modules/@oven/zig-linux-x64/lib/std/start.zig:327:40
make[1]: *** [Makefile:1096: dev-obj-track] Error 2
make[1]: Leaving directory '/home/saurabh/Documents/opensource/bun'
make: *** [Makefile:1936: zig] Error 2

```

**Comment by paperclover** [comment]
@TaduJR try cloning the repository within the WSL partition, not on /mnt/c. it looks like the Zig compiler crashed there.

@yadav-saurabh. you are on the wrong version of zig. please update to Zig `0.12.0-dev.888+130227491`

**Comment by TaduJR** [comment]
@paperdave Thank you for you response.
I tried cloning to my home/myusername directory then I compiled it still the same error

zig build-obj bun-debug Debug native-native-gnu.2.27: error: the following command terminated unexpectedly:
/home/natu/zig/zig build-obj -freference-trace=16 /home/natu/bun/root.zig -lc -fno-strip --eh-frame-hdr --emit-relocs -ffunction-sections --cache-dir /home/natu/bun/zig-cache --global-cache-dir /home/natu/.cache/zig --name bun-debug -fno-compiler-rt -fno-stack-check -fno-omit-frame-pointer -target native-native-gnu.2.27 -mcpu haswell --mod async_io::/home/natu/bun/src/io/io_linux.zig --mod build_options::/home/natu/bun/zig-cache/c/d0d2f9ff91e9d0dfdd1e0e703b2d7af8/options.zig --deps async_io,build_options --main-mod-path /home/natu/bun --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-debug.o transitive failure
│  ├─ zig build-obj bun-debug Debug native-native-gnu.2.27 failure
│  └─ zig build-obj bun-debug Debug native-native-gnu.2.27 (+1 more reused dependencies)
└─ zig build-obj bun-debug Debug native-native-gnu.2.27 (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/home/natu/bun/zig-cache/o/722f275bea175e4384012cbc908ab60d/build /home/natu/zig/zig /home/natu/bun /home/natu/bun/zig-cache /home/natu/.cache/zig obj -freference-trace -freference-trace -Dcpu=native
make[3]: *** [Makefile:1096: dev-obj-track] Error 1
make[3]: Leaving directory '/home/natu/bun'
make[2]: *** [Makefile:1940: zig-no-link] Error 2
make[2]: *** Waiting for unfinished jobs....
        make[3]: *** [Makefile:1607: src/bun.js/debug-bindings-obj/BunInspector.o] Error 255
make[3]: *** Waiting for unfinished jobs....
src/bun.js/bindings/Buffer.cpp:25:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
src/bun.js/bindings/Buffer.cpp:37:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
src/bun.js/bindings/Buffer.cpp:40:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
src/bun.js/bindings/Buffer.cpp:46:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
src/bun.js/bindings/Buffer.cpp:49:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
5 warnings generated.
src/bun.js/bindings/AsyncContextFrame.cpp:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
1 warning generated.
make[3]: Leaving directory '/home/natu/bun'
make[2]: *** [Makefile:1932: cpp-no-link] Error 2
make[2]: Leaving directory '/home/natu/bun'
make[1]: *** [Makefile:1944: dev] Error 2
make[1]: Leaving directory '/home/natu/bun'
make: *** [Makefile:1949: setup] Error 2

**Comment by varshneydevansh** [comment]
Hi @paperdave I'm facing this problem in my Ubuntu 22 LTS I did tried to look for the solution but still can't find. Can you help with this?


```bash
 ✘  devansh   3297_stream_writable  bun setup  
$ ./scripts/setup.sh
All system dependencies OK
C Compiler for dependencies: /usr/bin/clang-16
C++ Compiler for dependencies: /usr/bin/clang++-16
+ git submodule update --init --recursive --progress --depth=1 --checkout src/deps/picohttpparser src/deps/mimalloc src/deps/zlib src/deps/libarchive src/deps/boringssl src/deps/lol-html src/deps/tinycc src/deps/c-ares src/deps/zstd src/deps/base64 src/deps/ls-hpack
base64 - already built
boringssl - already built
cares - already built
libarchive - already built
lolhtml - already built
building mimalloc-debug
++ dirname -- /home/devansh/bun/scripts/build-mimalloc-debug.sh
+ source /home/devansh/bun/scripts/env.sh
++++ dirname -- /home/devansh/bun/scripts/env.sh
+++ cd -- /home/devansh/bun/scripts
+++ pwd
++ export SCRIPT_DIR=/home/devansh/bun/scripts
++ SCRIPT_DIR=/home/devansh/bun/scripts
++ export BUN_BASE_DIR=/home/devansh/bun
++ BUN_BASE_DIR=/home/devansh/bun
++ export BUN_DEPS_DIR=/home/devansh/bun/src/deps/
++ BUN_DEPS_DIR=/home/devansh/bun/src/deps/
++ export BUN_DEPS_OUT_DIR=/home/devansh/bun/src/deps/
++ BUN_DEPS_OUT_DIR=/home/devansh/bun/src/deps/
++ export CC=/usr/bin/clang-16
++ CC=/usr/bin/clang-16
++ export CXX=/usr/bin/clang++-16
++ CXX=/usr/bin/clang++-16
++ export AR=/usr/bin/ar
++ AR=/usr/bin/ar
++ export CPUS=12
++ CPUS=12
++ export CMAKE_CXX_COMPILER=/usr/bin/clang++-16
++ CMAKE_CXX_COMPILER=/usr/bin/clang++-16
++ export CMAKE_C_COMPILER=/usr/bin/clang-16
++ CMAKE_C_COMPILER=/usr/bin/clang-16
++ export 'CFLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden'
++ CFLAGS='-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden'
++ export 'CXXFLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden'
++ CXXFLAGS='-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden'
++ CMAKE_FLAGS=('-DCMAKE_C_COMPILER=/usr/bin/clang-16' '-DCMAKE_CXX_COMPILER=/usr/bin/clang++-16' '-DCMAKE_C_FLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden' '-DCMAKE_CXX_FLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden' '-DCMAKE_BUILD_TYPE=Release')
++ export CMAKE_FLAGS
+++ uname -s
++ [[ Linux == \D\a\r\w\i\n ]]
++ mkdir -p /home/devansh/bun/src/deps/
++ [[ /home/devansh/bun/scripts/env.sh == \/\h\o\m\e\/\d\e\v\a\n\s\h\/\b\u\n\/\s\c\r\i\p\t\s\/\b\u\i\l\d\-\m\i\m\a\l\l\o\c\-\d\e\b\u\g\.\s\h ]]
+ MIMALLOC_OVERRIDE_FLAG=
+ MIMALLOC_VALGRIND_ENABLED_FLAG=
+ cd /home/devansh/bun/src/deps//mimalloc
+ rm -rf CMakeCache.txt CMakeFiles
+ cmake -DCMAKE_C_COMPILER=/usr/bin/clang-16 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 '-DCMAKE_C_FLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden' '-DCMAKE_CXX_FLAGS=-O3 -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden' -DCMAKE_BUILD_TYPE=Release . -DCMAKE_BUILD_TYPE=Debug -DMI_DEBUG=1 -DMI_SKIP_COLLECT_ON_EXIT=1 -DMI_BUILD_SHARED=OFF -DMI_BUILD_STATIC=ON -DMI_BUILD_TESTS=OFF -DMI_OSX_ZONE=OFF -DMI_OSX_INTERPOSE=OFF -DMI_TRACK_VALGRIND=ON -DMI_BUILD_OBJECT=ON -DMI_USE_CXX=ON -DMI_OVERRIDE=OFF -DMI_OSX_ZONE=OFF -GNinja
-- The C compiler identification is Clang 16.0.6
-- The CXX compiler identification is Clang 16.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-16 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-16 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- Looking for include files valgrind/valgrind.h, valgrind/memcheck.h
-- Looking for include files valgrind/valgrind.h, valgrind/memcheck.h - found
-- Compile with Valgrind support (MI_TRACK_VALGRIND=ON)
-- Skip collecting memory on program exit (MI_SKIP_COLLECT_ON_EXIT=ON)
-- Use the C++ compiler to compile (MI_USE_CXX=ON)
-- 
-- Library base name: mimalloc-valgrind-debug
-- Version          : 2.1
-- Build type       : debug
-- C++ Compiler     : /usr/bin/clang++-16
-- Compiler flags   : -Wno-deprecated;-Wall;-Wextra;-Wno-unknown-pragmas;-fvisibility=hidden;-Wpedantic;-Wno-static-in-inline;-ftls-model=initial-exec
-- Compiler defines : MI_TRACK_VALGRIND=1;MI_SKIP_COLLECT_ON_EXIT=1
-- Link libraries   : /usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/librt.a
-- Build targets    : static;object
-- 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    MI_DEBUG


-- Build files have been written to: /home/devansh/bun/src/deps/mimalloc
+ ninja
[17/17] Building CXX object CMakeFiles/mimalloc-obj.dir/src/static.c.o
+ cp libmimalloc-debug.a /home/devansh/bun/src/deps//libmimalloc-debug.a
cp: cannot stat 'libmimalloc-debug.a': No such file or directory
Failed to build mimalloc-debug
error: script "setup" exited with code 1

```

**Comment by ghost** [comment]
Something similar happened with #8188.

**Comment by paperclover** [comment]
please dont discuss new repo setup issues in old closed issues. it makes it harder to track things. 

> Can you help with this?

this is currently tracked in the (open issue) #8188.
