### ISSUE TITLE
Rollup 4 / Vite 5 compatibility

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#6582]
### What version of Bun is running?

latest

### What steps can reproduce the bug?

https://github.com/marbemac/rollup-v4-bun-compat

### Additional information

Backporting issue from https://github.com/rollup/rollup/issues/5213

Rollup 4 was merged in Vite 5 beta yesterday

**Comment by paperclover** [comment]
why did no one tell me about this issue until after Vite 5 released. looking into it, it is a transpiler bug

minimal repro:

```ts
function unknown(v) {
    return v;
}

const xyz = require(unknown(false) ? 1 : unknown('@rollup/rollup-darwin-arm64'));
console.log(xyz)
```

transpiled output
```ts
(function(exports, require, module, __filename, __dirname) {
  let unknown = function(v) {
    return v;
  };
  const xyz = unknown(!1) ? 1 : unknown("@rollup/rollup-darwin-arm64");
  console.log(xyz);
}).call(this.module.exports, this.module.exports, this.require, this.module, this.__filename, this.__dirname);
```

the require call is dropped. cc @dylan-conway possibly trivial transpiler bug

**Comment by Jarred-Sumner** [comment]
#7170 fixes this on macOS
#7171 fixes this on Linux
