### ISSUE TITLE
Bun will not close socket if receive not understandable request in Bun.serve

### ISSUE THREAD

**Issue by rinsuki** [oven-sh/bun#6583]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Run some small http server:

```typescript
Bun.serve({
    fetch(req) {
        console.log("!")
        return new Response("hello")
    },
    port: 9999,
})
```

and access as a https server, like `curl https://localhost:9999`

### What is the expected behavior?

If received bytes don't looks like HTTP request, (send some error and)? close sockets.

for example, Node.js will close socket with `400 Bad Request` response.
![image](https://github.com/oven-sh/bun/assets/6533808/4d1a30ca-84f6-44bc-8396-4772f1396ba2)

### What do you see instead?

Bun just ignore and socket will hangs.

```
$ curl -v https://localhost:9999
*   Trying 127.0.0.1:9999...
* Connected to localhost (127.0.0.1) port 9999 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
^C
```

**Comment by LukasKastern** [comment]
I tested this with my change from #8187. The request times out after ~10 seconds for me.
So it at least doesn't hang forever anymore. 

But the socket is still not immediately closed when sending an invalid header.
