### ISSUE TITLE
`WebSocket` client causes code 1001 close

### ISSUE THREAD

**Issue by Mwni** [oven-sh/bun#6586]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Debian 11, WSL2

### What steps can reproduce the bug?

```js
const socket = new WebSocket('wss://xrplcluster.com')

socket.onopen = () => console.log('connected, wait for it ...')
socket.onclose = event => console.log('closed', event.code)
```
[Link to snippet](https://github.com/Mwni/bun-bugs/blob/main/websocket-close-1001.js)

### What is the expected behavior?

No code 1001 close

### What do you see instead?

Code 1001 close

### Additional information

Some WebSocket server implementations do not present this issue. If you swap `wss://xrplcluster.com` with `wss://s2.ripple.com`, it will not happen.

**Comment by Electroid** [comment]
We need to test our `WebSocket` client using the [Autobahn](https://github.com/crossbario/autobahn-testsuite) test suite to fix these bugs, including this one. For updates, please upvote and subscribe to this issue: #6686

**Comment by Electroid** [comment]
Duplicate of #6686
