### ISSUE TITLE
jose createRemoteJWKSet causes segfault

### ISSUE THREAD

**Issue by m1212e** [oven-sh/bun#6596]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Linux 6.5.4-76060504-generic x86_64 x86_64

### What steps can reproduce the bug?

Install the `jose` library. Then use the `createRemoteJWKSet` in some way. E.g.
```
const jwks = await createRemoteJWKSet(new URL(issuer.metadata.jwks_uri!));
```

### What is the expected behavior?

I'd expect the program to start and work as expected.

### What do you see instead?

`Segmentation fault (core dumped)`

**Comment by panva** [comment]
No segmentation in sight here.

```js
import { createRemoteJWKSet } from 'jose'

const JWKS = createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'))

console.log(await JWKS({ alg: 'RS256', kid: '0ad1fec78504f447bae65bcf5afaedb65eec9e81' }))
```

```
CryptoKey {
  type: "public",
  extractable: true,
  algorithm: {
    name: "RSASSA-PKCS1-v1_5",
    modulusLength: 2048,
    publicExponent: Uint8Array(3) [ 1, 0, 1 ],
    hash: {
      name: "SHA-256",
    },
  },
  usages: [ "verify" ],
}
```
