### ISSUE TITLE
SQLite Database.query.get returns wrong result for a join

### ISSUE THREAD

**Issue by frostburn** [oven-sh/bun#6597]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 6.2.0-34-generic x86_64 x86_64

### What steps can reproduce the bug?

```typescript
import {Database} from 'bun:sqlite';

const db = new Database();

db.query(
  'CREATE TABLE Users (Id INTEGER PRIMARY KEY, Name VARCHAR(255));'
).run();

db.query(
  'CREATE TABLE Cars (Id INTEGER PRIMARY KEY, Driver INTEGER, FOREIGN KEY (Driver) REFERENCES Users(Id))'
).run();

db.query('INSERT INTO Users (Id, Name) VALUES (1, "Alice");').run();
db.query('INSERT INTO Cars (Id, Driver) VALUES (1, 1);').run();

const car = db.query('SELECT * FROM Cars JOIN Users ON Driver=Users.Id').get();

console.log(car);

db.close();
```

### What is the expected behavior?

```bash
{
  Id: 1,
  Driver: 1,
  "Users.Id": 1,
  "Users.Name": "Alice"
}
```

### What do you see instead?

```bash
{
  Id: 1,
  Driver: 1,
  Name: 1
}
```

### Additional information

To be specific, the issue is that the `Name` attribute gets populated from the wrong column. It doesn't really have to be called `"Users.Name"` as long as the right data is there.

**Comment by matsumoto0912** [comment]
It seems that the issue still persists, hope this can be fixed.

**Comment by jonnybrooks** [comment]
Yeah JOINs currently don't work for me at all due to this bug 😢

**Comment by Jarred-Sumner** [comment]
Previously:
```js
{
  Id: 1,
  Driver: 1,
  Name: 1,
}
```

New in Bun v1.1.4: 
```js
{
  Driver: 1,
  Id: 1,
  Name: "Alice",
}
```

We do not include the duplicated column in the result, which matches better-sqlite3's behavior:
```js
❯ node sqlite3.cjs
{ Id: 1, Driver: 1, Name: 'Alice' }
```
