### ISSUE TITLE
Docker image breaks when using prisma

### ISSUE THREAD

**Issue by alexdotpink** [oven-sh/bun#6599]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Run some code in bun's linux/arm64 docker image.

### What is the expected behavior?

It should exit the process successfully.

### What do you see instead?

Process hangs, memory leaks and CPU usage skyrockets.

**Comment by Electroid** [comment]
Thanks for reporting, do you have an example that we can run to try to reproduce?

**Comment by alexdotpink** [comment]
I had made this repository to originally report the issue in Sentry's Issues, but then I figured it wasn't Sentry itself that was the problem but bun, because the issue also occurs if I use other libraries like Prisma or my own web framework (https://github.com/grace-js/grace).

The example is: https://github.com/Fumaz/sentry-prisma-memory-leak

**Comment by alexdotpink** [comment]
Here's a screenshot of `ctop` showing the issue:
 
<img width="584" alt="image" src="https://github.com/oven-sh/bun/assets/45318608/911c9031-bde5-436f-8a06-f833aa9046bb">

**Comment by alexdotpink** [comment]
It appears to me this issue is Prisma related. I also noticed this issue not only affects the linux/arm64 image, but also the linux/amd64 image, but in a different way. Instead of leaking memory, it simply crashes (SIGSEGV).

**Comment by wwelder** [comment]
I can confirm the same behavior, memory leak on linux/arm64 and fail on amd64 with prisma

**Comment by CPlusPatch** [comment]
Getting the same behaviour here, I have Bun and Prisma inside a Docker container, as soon as I do anything with Prisma the process gets killed with code 139 (I think this means it got killed by the kernel for using too many resources)

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15309

This will be part of the Bun v1.1.36 release, which is tomorrow.

**Comment by kravetsone** [comment]
> Fixed in [#15309](https://github.com/oven-sh/bun/pull/15309)
> 
> This will be part of the Bun v1.1.36 release, which is tomorrow.

`v1.1.37`)

**Comment by Jarred-Sumner** [comment]
thanks i forgot
