### ISSUE TITLE
Method calls on numeric literals

### ISSUE THREAD

**Issue by ashsearle** [oven-sh/bun#66]
Error seen when hot reloading code in Chrome:
```
Uncaught SyntaxError: Invalid or unexpected token
```

Using `bun dev` using bun version 0.0.48.  Code within an npm package included this expression:
```js
parseFloat((0.0).toPrecision(precision) + '1')
```

The code hot-reloaded was:
```js
parseFloat(0.toPrecision(precision) + '1')
```

It appears bun removed the parenthesis around the number, rendering the code syntactically invalid.

FWIW: adding a space would make it valid:
```js
parseFloat(0 .toPrecision(precision) + '1')
```

**Comment by Jarred-Sumner** [comment]
This is a regression I think. I will fix and add a test for it.
