### ISSUE TITLE
UnknownHostName downloading package manifest during bun install for all packages

### ISSUE THREAD

**Issue by alexandros-megas** [oven-sh/bun#660]
### Version

0.1.3

### Platform

Darwin alexandros-katechis-mbp.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

`bun install`

### How often does it reproduce? Is there a required condition?

For me, it happens every time I run `bun install`. Clearing the bun install cache doesn't help.

### What is the expected behavior?

Bun installs the packages.

### What do you see instead?

When I run it in verbose mode, this is the output https://pastebin.com/1k6nCYPj

**Comment by kamikaz1k** [comment]
Also seeing similar behaviour on 0.1.5

Weird thing is, it worked when I ran in on the same repo cloned elsewhere (on the same machine).

**Comment by Electroid** [comment]
Closing in favor of #1452, this likely happened because your machine was disconnected from the Internet.

**Comment by devopsteam605** [comment]
what if internet connection cant be made and a private npm\js repository is used? should it still produce the same issue? can bun be ran in a disconnected environment in some way?
