### ISSUE TITLE
bun install --yarn does not generate compatible lock file

### ISSUE THREAD

**Issue by patrickelectric** [oven-sh/bun#6604]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Use the following package.json

<details>
<summary>package.json</summary>

`{
  "name": "cockpit",
  "version": "0.0.0",
  "private": true,
  "main": "dist/electron/main.js",
  "scripts": {
    "build": "vite build",
    "build:serve": "bun run build && bun run serve",
    "coverage": "vitest --coverage",
    "deploy:electron:dir": "electron-builder --dir",
    "deploy:electron": "electron-builder --publish=never",
    "deploy:flatpak": "electron-builder --x64 --linux flatpak",
    "dev": "vite",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --ignore-path .gitignore --max-warnings=0",
    "preview": "vite preview --port 5050",
    "serve": "vite preview",
    "test:ci": "vitest --coverage --run",
    "test:unit": "vitest",
    "typecheck": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/free-regular-svg-icons": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/vue-fontawesome": "^3.0.3",
    "@mdi/font": "^7.0.96",
    "@mdi/js": "^7.2.96",
    "@vue-leaflet/vue-leaflet": "^0.6.1",
    "@vueuse/core": "9.8.1",
    "@vueuse/math": "^10.1.2",
    "browser-or-node": "^2.0.0",
    "colord": "^2.9.3",
    "date-fns": "^2.29.3",
    "file-saver": "^2.0.5",
    "fix-webm-duration": "^1.0.5",
    "floating-vue": "^2.0.0-beta.20",
    "gamepad.js": "^1.0.4",
    "gsap": "^3.11.3",
    "haversine-distance": "^1.2.1",
    "leaflet": "1.9.3",
    "pinia": "^2.0.13",
    "roboto-fontface": "*",
    "sweetalert2": "^11.7.1",
    "tailwind-scrollbar-hide": "^1.1.7",
    "uuid": "^8.3.2",
    "vue": "^3.3.4",
    "vue-draggable-plus": "^0.2.0-beta.2",
    "vue-router": "^4.0.14",
    "vue-virtual-scroller": "^2.0.0-beta.8",
    "vuetify": "^3.1.13",
    "webfontloader": "^1.0.0",
    "webrtc-adapter": "^8.2.0"
  },
  "devDependencies": {
    "@pinia/testing": "^0.0.12",
    "@rushstack/eslint-patch": "^1.1.0",
    "@types/file-saver": "^2.0.5",
    "@types/jsdom": "^16.2.14",
    "@types/leaflet": "^1.9.0",
    "@types/node": "^16.11.27",
    "@types/uuid": "^8.3.4",
    "@types/webfontloader": "^1.0.0",
    "@vitejs/plugin-vue": "3.1.0",
    "@vue/eslint-config-prettier": "^7.0.0",
    "@vue/eslint-config-typescript": "^10.0.0",
    "@vue/test-utils": "^2.0.0-rc.20",
    "@vue/tsconfig": "^0.1.3",
    "autoprefixer": "^10.4.13",
    "c8": "^7.11.3",
    "electron": "^20.1.0",
    "electron-builder": "^23.3.3",
    "eslint": "^8.5.0",
    "eslint-plugin-jsdoc": "^43.1.1",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "eslint-plugin-vue": "^8.2.0",
    "jsdom": "^19.0.0",
    "postcss": "^8.4.21",
    "prettier": "^2.5.1",
    "sass": "^1.38.0",
    "sass-loader": "^10.0.0",
    "tailwindcss": "^3.2.6",
    "typescript": "~4.6.3",
    "vite": "3.1.0",
    "vite-plugin-electron": "^0.9.2",
    "vite-plugin-pwa": "^0.14.1",
    "vite-plugin-vuetify": "^1.0.0-alpha.16",
    "vitest": "^0.20.3",
    "vue-cli-plugin-vuetify": "~2.4.8",
    "vue-tsc": "1.0.9",
    "vuetify-loader": "^2.0.0-alpha.0"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true,
    "quoteProps": "consistent",
    "printWidth": 120
  },
  "build": {
    "files": [
      "dist"
    ],
    "appId": "org.bluerobotics.cockpit",
    "mac": {
      "category": "public.app-category.entertainment"
    },
    "flatpak": {
      "base": "org.electronjs.Electron2.BaseApp",
      "baseVersion": "22.08",
      "description": "An intuitive and customizable cross-platform ground control station for remote vehicles of all types.",
      "finishArgs": [
        "--socket=wayland",
        "--socket=x11",
        "--share=ipc",
        "--device=dri",
        "--socket=pulseaudio",
        "--filesystem=/run/udev:ro",
        "--share=network",
        "--talk-name=org.freedesktop.Notifications"
      ],
      "runtime": "org.freedesktop.Platform",
      "runtimeVersion": "22.08",
      "sdk": "org.freedesktop.Sdk"
    }
  }
}
`

</details>

run `bun install --yarn`, remove node_modules and run `yarn install`.
You'll get:
```
yarn install v1.22.19
error An unexpected error occurred: "Unknown token: { line: 2081, col: 5, type: 'NUMBER', value: 7 } 2081:5 in /Users/patrick/git/blue/cockpit/yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "/Users/patrick/git/blue/cockpit/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ✘ patrick@maccheese  ~/git/blue/cockpit   add-yarn-compatibility ±  

```

### What is the expected behavior?

Bun should generate compatible lock files with yarn, and that's not the case.

### What do you see instead?

The error message.

**Comment by yharaskrik** [comment]
also experiencing this slightly different message but same error

```
error An unexpected error occurred: "Unknown token: { line: 26780, col: 5, type: 'BOOLEAN', value: true } 
```

**Comment by nop33** [comment]
There seems to be a bug in bun where packages whose name starts with a number (ex: `7zip-bin`) are not quoted properly. If you wrap with quotes all references of such package names in the lock file, it should work.
