### ISSUE TITLE
In canary on macOS arm64, `bun i <package-name>` crashes

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#6606]
### What version of Bun is running?

1.0.7+378385ba60900be7bd797923c219ec489101f2f5

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

In any folder, run:

```
bun i solid-toast
fish: Job 1, 'bun i solid-toast' terminated by signal SIGSEGV (Address boundary error)
```

It fails on all packages.

### What is the expected behavior?

It installs the deps.

### What do you see instead?

It crashes.

**Comment by Jarred-Sumner** [comment]
this will be fixed today

**Comment by Jarred-Sumner** [comment]
Fixed by @dylan-conway in https://github.com/oven-sh/bun/pull/6609
