### ISSUE TITLE
cannot access ip address after async

### ISSUE THREAD

**Issue by ImLunaHey** [oven-sh/bun#6613]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
const promise = () =>
  new Promise<boolean>((resolve) => {
    setTimeout(() => {
      resolve(true);
    }, 1);
  });

Bun.serve({
  port: 5000,
  async fetch(request, server) {
    const pathname = new URL(request.url).pathname;
    if (pathname === "/works") {
      return new Response(`Your IP is ${server.requestIP(request)?.address}`);
    }

    if (pathname === "/fails") {
      await promise();
      return new Response(`Your IP is ${server.requestIP(request)?.address}`);
    }

    return new Response("404");
  },
});
```

### What is the expected behavior?

/fails returns the IP

### What do you see instead?

/fails returns undefined instead of the IP

### Additional information

Ref: https://canary.discord.com/channels/876711213126520882/876711213126520885/1164809635530817607

**Comment by a-rebets** [comment]
I confirm this as well

**Comment by kravetsone** [comment]
this can be closed with https://bun.sh/blog/bun-v1.1.27#fixed-server-requestip-after-await
