### ISSUE TITLE
error: CouldntReadCurrentDirectory, when running `bun tauri dev`

### ISSUE THREAD

**Issue by eveeifyeve** [oven-sh/bun#6619]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

1. Create a tauri application 
2. Use `bun install`
3. Use `bun tauri dev`

### What is the expected behavior?

> tauri dev

   nfo Watching /Users/eveeify/Documents/Coding/Github/TeaClient/Launcher/src-tauri for changes...
   Compiling mac-notification-sys v0.6.1
   Compiling notify-rust v4.9.0
   Compiling tauri v1.4.1
   Compiling teaclient v0.0.0 (/Users/eveeify/Documents/Coding/Github/TeaClient/Launcher/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 8.21s

### What do you see instead?

error: CouldntReadCurrentDirectory

----- bun meta -----
Bun v1.0.6 (969da088) macOS Silicon 23.1.0
AutoCommand: 
Elapsed: 17ms | User: 2ms | Sys: 4ms
RSS: 5.23MB | Peak: 5.23MB | Commit: 33.55MB | Faults: 197
----- bun meta -----

0   0x10652e434 WTFGetBacktrace

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.6-1697797396659.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

### Additional information

I did try it with npm it works normally but I don't know what happened

**Comment by eveeifyeve** [comment]
This is not just tauri It's happening to astro as well.

**Comment by eveeifyeve** [comment]
Still happneing with 1.0.7

**Comment by eveeifyeve** [comment]
Hmm Still happens when downgrading to 1.0

**Comment by eveeifyeve** [comment]
Found a Fix: Enable Full-Disk Access.

**Comment by wuchang** [comment]
> Found a Fix: Enable Full-Disk Access.

how ?
