### ISSUE TITLE
README文档介绍与 Create React App 一起使用的npm应该有误

### ISSUE THREAD

**Issue by dong-lufei** [oven-sh/bun#662]
### Affected URL(s)

https://github.com/oven-sh/bun/blob/main/README.md

### Description of the problem

如下这段，应该是bun add -d react-refresh 而不是npm ...

```
将 bun 与 Create React App 一起使用

# To enable React Fast Refresh, ensure "react-refresh" is installed
npm install -D react-refresh
```

**Comment by FinnRG** [comment]
Could you open up a PR for this?
