### ISSUE TITLE
Package and publish Bun on the Snap store

### ISSUE THREAD

**Issue by vanillajonathan** [oven-sh/bun#6623]
### What is the problem this feature would solve?

Easy install, update and uninstall on Linux.

### What is the feature you are proposing to solve the problem?

Package Bun as a [Snap](https://snapcraft.io/) package and publish it on the Snap app store.

You can do this with the [snapcore/action-build](https://github.com/snapcore/action-build) GitHub Action.

**Comment by Electroid** [comment]
Duplicate of #862
