### ISSUE TITLE
make Bun.write more restrict

### ISSUE THREAD

**Issue by zhy0216** [oven-sh/bun#6633]
### What is the problem this feature would solve?

make Bun.write more restrict.
destination should only accept BunFile.

### What is the feature you are proposing to solve the problem?

Bun.write is very flexible. 
```
destination: BunFile | PathLike,
input: Blob | TypedArray | ArrayBufferLike | string | BlobPart
```
PathLike also has string there.
so Bun.write can accept two string, which will not prevent potential mistake that user may revert the args.

### What alternatives have you considered?

we can also add  a write method on BunFile so that user can do 
```
Bun.file(filename).write("hello");
```

**Comment by Electroid** [comment]
It's understandable that if you do `Bun.write("string", "string")`, it could be confusing which is the path and which is the content. However, we can't make this change since it would be breaking.
