### ISSUE TITLE
expect.toEqual is reporting type errors

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#6647]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

```ts
import { describe, expect } from "bun:test";

describe("Something", () => {
    const actual: Record<string, unknown> | string | undefined | null = "";

    expect(actual).toEqual({ another: "issue" });
    expect(actual).toEqual("all good");
});
```

### What is the expected behavior?

no type errors, hehe

### What do you see instead?

`Argument of type  { another: string; }  is not assignable to parameter of type  string`

![CleanShot 2023-10-22 at 01 07 13](https://github.com/oven-sh/bun/assets/6713842/0193dc13-3df6-448f-b747-0b8690f4518b)

### Additional information

No issues on `Bun v1.0.6` 

![CleanShot 2023-10-22 at 01 12 28](https://github.com/oven-sh/bun/assets/6713842/041db5db-9dc8-43b2-a155-c8f70375e933)

**Comment by TiBianMod** [comment]
maybe related to PR https://github.com/oven-sh/bun/pull/6634

**Comment by Voldemat** [comment]
No, it is separate issue. And looks like it is default typescript behavior.
```typescript
function check<T> (arg: T): T {
    return arg
}
const actual: string | number = 1
const result = check(actual) // both actual and result variables are numbers
```

**Comment by TiBianMod** [comment]
## The types are broken since `version 1.07`

> I'm surprised, no one else has this issue??
wtf, no one is writing tests, haha

```ts
import { describe, expect, test } from "bun:test";

describe("Something", () => {
    test("ee", () => {
        const actual: string | null = null;

        expect(actual).toEqual("some");
    });
});
```

![CleanShot 2023-11-17 at 21 01 25](https://github.com/oven-sh/bun/assets/6713842/98972e76-5f34-4b22-a9c9-eabfc99f7f55)

Sorry to bother you guys, but this was working until version 1.06 (no issues with the types)



@Electroid @Jarred-Sumner @dylan-conway
