### ISSUE TITLE
node-redis and ioredis events is not working.

### ISSUE THREAD

**Issue by LMS5413** [oven-sh/bun#6652]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Install node-redis or ioredis
add event listener "error"

### What is the expected behavior?

When redis contains an unexpected connection, it issues the "error" event.

### What do you see instead?

The error event is not emitted, and this problem occurs with the ioredis and node-redis libraries, thus not being able to reconnect with redis.

**Comment by yschroe** [comment]
Do you have a minimal example which doesn't work for you?

I just copied the [basic example](https://github.com/redis/node-redis#basic-example) from the node-redis project page and for me the error event is emitted if I run it (since I have no server to connect to):
```javascript
import { createClient } from 'redis';

const client = await createClient()
  .on('error', (err) => console.log('Redis Client Error', err))
  .connect();

await client.set('key', 'value');
const value = await client.get('key');
await client.disconnect();
```

```
Redis Client Error ECONNREFUSED: Failed to connect
 syscall: "connect"
```

**Comment by LMS5413** [comment]
https://github.com/oven-sh/bun/assets/58144443/3f72b6a1-5298-4e1b-a3e1-03fee1b79b5d

**Comment by Pedromdsn** [comment]
```ts
import { RedisClientType } from "@redis/client"
import { createClient } from "redis"

class RedisManager {
	redis!: RedisClientType

	constructor() {
		this.redis = createClient({
			socket: {
				host: "localhost",
				port: 6379,
				reconnectStrategy: (retries) => Math.min(retries * 50, 1000),
				connectTimeout: 3000
			},
			pingInterval: 1000 * 60 * 5
		})
		this.redis.on("error", (err) => {
			console.log("Redis error: " + err)
		})
		this.redis.on("connect", () => {
			console.log("Redis ready")
		})

		this.redis.connect()
	}

	getRedis() {
		return this.redis
	}
}

new RedisManager()
```

With a version similar to yours I was able to run it without any problems.

**Comment by LMS5413** [comment]
Im fixed. Im restarted WSL and its working!
