### ISSUE TITLE
fetch fails on https://litudian.com ( works on curl/fetch) 

### ISSUE THREAD

**Issue by thibaultleouay** [oven-sh/bun#6658]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

const res = await fetch(“https://litudian.com”, {
    keepalive:false,
});

console.log(res);

### What is the expected behavior?

it should return a 200 

### What do you see instead?

ConnectionRefused: Unable to connect. Is the computer able to access the url? 

### Additional information

we also have this issue on bun docker image

**Comment by Jarred-Sumner** [comment]
This domain doesn't resolve in Google Chrome for me. Is this spelled correctly?

**Comment by thibaultleouay** [comment]
> This domain doesn't resolve in Google Chrome for me. Is this spelled correctly?

I think GitHub is adding some character to the link @Jarred-Sumner 
Copy paste it and it should work 

Rn for me on my phone 
![Screenshot_20231022-230646.png](https://github.com/oven-sh/bun/assets/13894054/e48e7b31-698e-4a10-b199-98f7979ca1a6)




https://litudian.com/

**Comment by shawshankkumar** [comment]
@thibaultleouay seems to be breaking for me on node as well, did you try running it on node?

**Comment by thibaultleouay** [comment]
@shawshankkumar 
![CleanShot 2023-10-22 at 23 18 27](https://github.com/oven-sh/bun/assets/13894054/8c49c1ca-6905-483c-b636-56bba18533ba)
on node 20  it works !

**Comment by shawshankkumar** [comment]
Yup, swtiched to node 20 and it does work. Wondering what the reason is 🤔

**Comment by Jarred-Sumner** [comment]
Copy-pasting it into a file does seem to work on both Linux x64 and macOS arm64. I'm guessing there's a dns resolution issue going on. But it's hard to reproduce this issue.

<img width="402" alt="image" src="https://github.com/oven-sh/bun/assets/709451/afe381eb-1670-401d-8923-3ca60995d28d">

**Comment by twais** [comment]
Does this explain the `500`'s being experienced with www.litudian.com on the litudian status page?
<img width="873" alt="Screenshot 2023-10-23 at 07 53 38" src="https://github.com/oven-sh/bun/assets/6759518/bc64dcd4-53d9-405a-92ee-3d714fda7402">

**Comment by thibaultleouay** [comment]
@Jarred-Sumner  so strange, so it might be a dns resolve issue ? 
I also encounter it on fly with bun docker image :(

**Comment by thibaultleouay** [comment]
We had an other users having issue with its domain, 

they fixed the ipv6 for the domain and now it works 

@twais  litudian.com also have an ipv6 configured for the  domain 

AAAA litudian.com 2600:3c01::f03c:91ff:fe8d:dd7b

it might be related to ipv6 resolution ? 🤔

**Comment by riprsa** [comment]
I have a similar issue with 'https://telegram.org/'. Bun's fetch is not working correctly. Also, using a proxy server, such as Proxyman, solves this issue. The problem is clearly with networking, so there are plenty of workarounds.

**Comment by riprsa** [comment]
By the way, I am on ARM too. May be especially aarch64 version of 'fetch' is incorrect

**Comment by LuisMalhadas** [comment]
another 2cents to the issue:

```
console.log(await fetch('http://localhost:11434/api/tags'))
% bun teste.js       
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:11434/api/tags"
 
 console.log(await fetch('http://127.0.0.1:11434/api/tags'))
%  bun teste.js
Response (2.1 KB) {
  ok: true,
  url: "http://127.0.0.1:11434/api/tags",
  status: 200,
  statusText: "OK",
  headers: Headers {
    "content-type": "application/json; charset=utf-8",
    "date": "Wed, 31 Jan 2024 19:38:33 GMT",
    "transfer-encoding": "chunked",
  },
  redirected: false,
  bodyUsed: false,
  Blob (2.1 KB)
}
```

This on a M1
Did not test any further. don't require dns for now...
