### ISSUE TITLE
Fastify autoload does not work with bun run ts

### ISSUE THREAD

**Issue by shawshankkumar** [oven-sh/bun#6660]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

Make a very simple fastify server and use fastify autoload to register the modules. 

### What is the expected behavior?

Server should start normally

### What do you see instead?

{"level":50,"time":1698008510325,"pid":8022,"hostname":"SHASHANKs-MacBook-Pro.local","err":{"type":"Error","message":"@fastify/autoload cannot import plugin at '/Users/shawshankkumar/Desktop/personal/internal/src/api/routers/auth.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.","stack":"Error: @fastify/autoload cannot import plugin at '/Users/shawshankkumar/Desktop/personal/internal/src/api/routers/auth.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.\n    at <anonymous> (/Users/shawshankkumar/Desktop/personal/internal/node_modules/.pnpm/@fastify+autoload@5.8.0/node_modules/@fastify/autoload/index.js:241:11)\n    at processTicksAndRejections (:61:39)","originalLine":67,"originalColumn":26},"msg":"@fastify/autoload cannot import plugin at '/Users/shawshankkumar/Desktop/personal/internal/src/api/routers/auth.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app."}

**Comment by AntonPieper** [comment]
Can be fixed by adding `FASTIFY_AUTOLOAD_TYPESCRIPT=1` to your project's `.env` file ([as described in the README](https://github.com/fastify/fastify-autoload?tab=readme-ov-file#override-typescript-detection-using-an-environment-variable)). You can also set it before running bun `FASTIFY_AUTOLOAD_TYPESCRIPT=1; bun run <your file or script>`.

**Comment by shawshankkumar** [comment]
> Can be fixed by adding `FASTIFY_AUTOLOAD_TYPESCRIPT=1` to your project's `.env` file ([as described in the README](https://github.com/fastify/fastify-autoload?tab=readme-ov-file#override-typescript-detection-using-an-environment-variable)). You can also set it before running bun `FASTIFY_AUTOLOAD_TYPESCRIPT=1; bun run <your file or script>`.

<img width="1177" alt="image" src="https://github.com/oven-sh/bun/assets/74819565/5de92cb4-889e-44d1-83ce-a1370eef5c6d">

Hey, seems to be working now. I'll close this, will work with fastify + bun more and get back to this issue. 

Thanks @AntonPieper
