### ISSUE TITLE
[webSocket server] : wss doesn't work on chromium [ver. 118]

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#6662]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

+ on browser
```
const ws = new WebSocket("wss://localhost:8082");
// const ws = new WebSocket("ws://localhost:3000");

ws.onopen = ev => {
    console.log('open');
};
ws.onclose = ev => {
    console.log('close', ev);
};
ws.onerror = ev => {
    console.log('error', ev);
};
ws.addEventListener('message', msg => {
    console.log(msg.data);
});
setTimeout(() => {
    console.log('send data');
    ws.send('Client sends data after 5s');
}, 5000);
````
+ on webSocket server:
```
Bun.serve({
      ...tls,
      fetch(req, server) {       
          console.log('income server');

          server.upgrade(req);
      },
      websocket: {
          message(ws, message) {
              console.log('message');

              ws.sendText(`message server: ${message}`);
          },
          open(ws) {
              console.log('open');

              ws.sendText('open server');            
          },
          close(ws, code, reason) {
              console.log(`close: ${code} - ${reason}`);

              ws.sendText(`close server: ${code} - ${reason}`);              
          },
          drain(ws) {
              console.log('drain');

              ws.sendText('drain server');
          }
      }
  });
````
+ ws works on Firefox and Chromium
+ wss works on Firefox and not working on Chromium
+ "income server" doesn't show when wss connecting on Chromium

### What is the expected behavior?

wss works on Chromium

### What do you see instead?

![2023-10-23_13-11](https://github.com/oven-sh/bun/assets/141234261/58938350-f003-45f7-98b0-8e57f9365faf)

**Comment by cirospaciari** [comment]
@truongan07 can you still reproduce this issue on bun `v1.0.11`?

**Comment by truongan07** [comment]
> @truongan07 can you still reproduce this issue on bun `v1.0.11`?

Yes

on Firefox  : 

![image](https://github.com/oven-sh/bun/assets/141234261/986289f3-d978-4cdf-91e9-b9770fdb83b2)

on Chromium [ Version 119.0.6045.105 (Official Build) ] :

![image](https://github.com/oven-sh/bun/assets/141234261/e569721f-6928-4d4a-8602-709049732043)

**Comment by Vincz** [comment]
Ran into this issue as well. Doesn't seem to work either behind a SSL Nginx proxy.

**Comment by truongan07** [comment]
> Ran into this issue as well. Doesn't seem to work either behind a SSL Nginx proxy.

I don't think that is a SSL Nginx proxy. If you run on SSL Nginx proxy that behind Nginx proxy is a websocket without SSL. It will work

**Comment by truongan07** [comment]
> @cirospaciari

That is an issue of "Access-Control-Allow-Origin" on two difference domains. I fixed it and now working. Thanks for help.

![test](https://github.com/oven-sh/bun/assets/141234261/c3160337-0632-401c-b938-f8e95f0da2d2)
