### ISSUE TITLE
Variable declaration error in asynchronous function (webkit bug #223533)

### ISSUE THREAD

**Issue by vflash** [oven-sh/bun#6663]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

```js
async function test(data) {
    var data;
    console.log(data);
};
test({qq: 11});
```

### What is the expected behavior?

console log ``{qq: 11}``

### What do you see instead?

``undefined``

**Comment by Jarred-Sumner** [comment]
This is a JavaScriptCore bug, unfortunately: https://bugs.webkit.org/show_bug.cgi?id=223533

<img width="423" alt="image" src="https://github.com/oven-sh/bun/assets/709451/17949593-b0fd-4c9b-8575-62160be8d2c8">

**Comment by Jarred-Sumner** [comment]
This was fixed long ago
```
❯ bun-1.1.0 /tmp/a.js
{
  qq: 11,
}


❯ bun-1.1.16 /tmp/a.js
{
  qq: 11,
}

```
