### ISSUE TITLE
error loading current directory when bun run

### ISSUE THREAD

**Issue by holiq** [oven-sh/bun#6665]
### What version of Bun is running?

v1.0.7

### What platform is your computer?

Linux 4.19.191-27107981-abA146PXXU4BWH4 aarch64 unknown (Android with Termux)

### What steps can reproduce the bug?

I install laravel and want to install the packaging, so I run `bun install --backend=copyfile` and it's work, but when I want to run dev or build it got an error like this and the full screenshot is bellow.
```error loading current directory

error: CouldntReadCurrentDirectory

----- bun meta -----
Bun v1.0.7 (b0393fba) Linux arm64 #1 SMP PREEMPT Tue Aug 29 11:57:33 KST 2023
RunCommand:
Elapsed: 2ms | User: 0ms | Sys: 12ms
RSS: 33.55MB | Peak: 7.36MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x7621f7d5b8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.7-1698060941005.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```
![Screenshot_20231023_184229_Termux](https://github.com/oven-sh/bun/assets/30729921/a0fc9e34-55fd-4922-8448-2289814e4418)

**Comment by Electroid** [comment]
Duplicate of #5182

**Comment by Electroid** [comment]
Also a note that we don't officially support running Bun on Android.
