### ISSUE TITLE
Issue with Vite: Script "build" exited with code 1

### ISSUE THREAD

**Issue by janswist** [oven-sh/bun#6666]
### What version of Bun is running?

latest Docker one (can't output it)

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

`bunx --bun vite build` inside Dockerfile

### What is the expected behavior?

To build. Outside Docker it all builds properly.

### What do you see instead?

#0 0.257 $ bunx --bun vite build && cp src/assets/_headers dist/_headers                                                                 
#0 0.269  Resolving dependencies                                                                                                         
#0 5.297  Resolved, downloaded and extracted [76]                                                                                        
#0 5.298  Saved lockfile
#0 5.552 failed to load config from /code/vite.config.js
#0 5.552 error during build:
#0 5.552 undefined
#0 5.568 error: script "build" exited with code 1 (SIGHUP)

**Comment by benglewis** [comment]
@Jarred-Sumner Unfortunately, I am seeing the same thing, but in reverse.

The Docker image builds fine on my local M3 Pro MacBook Pro (even though I use `platform=linux/amd64` in the `FROM` section of the `Dockerfile`, so the image being built is using Rosetta, but when I try to build the exact same image on GitHub in GitHub Actions, it fails during the Vite build. I made sure that both systems are using the latest Docker version (26.1.1) and I fixed my `bun` base image version to the latest too (specifically `oven/bun:1.1.8-alpine`). In terms of other context that may help to reproduce/debug the issue, I am using SvelteKit which inside is using Vite with the `@sveltejs/adapter-static` adapter.

My issue also seems related to [10811](https://github.com/oven-sh/bun/issues/10811)

Should I open a separate ticket and try to provide a simple codebase that reproduces the issue?
