### ISSUE TITLE
Bun.serve `requestIP` not working as expected

### ISSUE THREAD

**Issue by itohatweb** [oven-sh/bun#6668]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 6.5.4-76060504-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Write a simple http server
```ts
const server = Bun.serve({
    hostname: "0.0.0.0",
    port: 3000,
    development: false,
    async fetch(request) {
        console.log("IP:", this.requestIP(request));
        return new Response("Ok!");
    },
});

console.log(`Listening on 0.0.0.0: ${server.port}`);
```
2. Send a request to the server, from a different device (eg. open it on phone through a browser)
3. You get a strange IP Address
```json
{
  "address": "4294967232.4294967208.68.57",
  "family": "IPv4",
  "port": 40174
}
```

### What is the expected behavior?

The IP address should look like `192.168.68.57`.

### What do you see instead?

The IP address looks like `4294967232.4294967208.68.57`.

### Additional information

I don't know much about Buns inner workings, but the wrong numbers look suspiciously close to the `u32` max (`4294967295`) so this error might be related to an overflow.

Edit:
I've now tested this on a server too, and there the first 2 numbers are correct, and the last 2 numbers have this overflow problem. (`90.100.4294967212.4294967245`)

**Comment by Electroid** [comment]
Thanks for flagging this, we'll fix it.
