### ISSUE TITLE
bun install: support migrating from lockfileVersion v2

### ISSUE THREAD

**Issue by titouanmathis** [oven-sh/bun#6682]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

```bash
git clone https://github.com/titouanmathis/bun-repro-lockfile-version-throw.git
cd bun-repro-lockfile-version-throw
bun i
```

### What is the expected behavior?

Packages described in the `package.json` file are installed, as in bun v1.0.4. 

### What do you see instead?

The output of the `bun i` command is: 

```
bun install v1.0.6 (969da088)
error: Please upgrade package-lock.json to lockfileVersion 3

Run 'npm i --lockfile-version 3 --frozen-lockfile' to upgrade your lockfile without changing dependencies.
```

### Additional information

Some potential solutions: 

- transform the package-lock.json v2 file to a bun.lockb file
- allow installation of packages from the package.json file if the lockfileVersion is not supported by bun

**Comment by chimmykk** [comment]
Resolve this by removing the pakage-lock.json and then i think this when you need an exact version as opposed to a semver range.

**Comment by paperclover** [comment]
i think we actually could support verison 2 by simply not erroring when we see `2`. it seems the `packages` object in the json file is the same, with the difference from 2->3 being removal of the `dependencies` object, which was only there for backwards compatibility with npm v6

**Comment by tmisirpash** [comment]
Hi @paperdave , any blockers for adding this?

**Comment by paperclover** [comment]
i made a pr #6695 but never merged because i didn't properly test it on lockfiles in the wild.
