### ISSUE TITLE
bun add Resolves Old Version of Package Using .next Pre-Release Semver Syntax

### ISSUE THREAD

**Issue by andyexeter** [oven-sh/bun#6683]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.2.0-34-generic x86_64 x86_64

### What steps can reproduce the bug?

```console
$ bun add @polka/url@^1.0.0-next.23
```

### What is the expected behavior?

Version 1.0.0-next.23 of `@polka/url` should be installed

### What do you see instead?

```console
$ bun add @polka/url@^1.0.0-next.23
bun add v1.0.7 (b0393fba)

 installed @polka/url@1.0.0-next.9


 1 package installed [100.00ms]

$ (cd node_modules/@polka/url && npm pkg get version)
"1.0.0-next.9"
```

### Additional information

NPM and Yarn (v1) both correctly install version 1.0.0-next.23:

```console
$ npm install @polka/url@^1.0.0-next.23
added 1 package in 167ms
$ (cd node_modules/@polka/url && npm pkg get version)
"1.0.0-next.23"
```

```console
$ yarn add @polka/url@^1.0.0-next.23       
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @polka/url@1.0.0-next.23
info All dependencies
└─ @polka/url@1.0.0-next.23
Done in 0.18s.
$ (cd node_modules/@polka/url && npm pkg get version)
"1.0.0-next.23"
```

Without knowing much about how the version resolution code works, I am assuming it's selecting the highest single digit version after `-next.` (9) and ignoring anything over 10.

**Comment by dylan-conway** [comment]
fixed in #6814
