### ISSUE TITLE
`WebSocket` client reliability

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#6686]
There are various issues with Bun's `WebSocket` client that have to do with parsing frames properly. We need to add the [Autobahn](https://github.com/crossbario/autobahn-testsuite/blob/master/autobahntestsuite/autobahntestsuite) to our tests and start fixing the bugs in [`websocket_http_client.zig`](https://github.com/oven-sh/bun/blob/149668129791d7dae6486368a2fbf50fdecd2efe/src/http/websocket_http_client.zig).

Note: this is not to be confused with Bun's `WebSocket` server, which is implemented by uWebSockets which uses the Autobahn test suite.

**Comment by DeveloperHarris** [comment]
Unsure, but is this also related?

https://github.com/oven-sh/bun/issues/5588

**Comment by tscpp** [comment]
Is this something that is planned to be fixed in the near future?

**Comment by Mwni** [comment]
This makes it impossible for me to adopt bun at the moment. An approximate ETA would be very appreciated.

**Comment by LucyEgan** [comment]
Yeh its definitely a unexpected partial blocker for us, but there is https://github.com/Vexcited/tcp-websocket that might be worth exploring as a work around

**Comment by Electroid** [comment]
You can test these fixes right now if you run `bun upgrade --canary`. It will be available in Bun v1.0.15, which will come out today or tomorrow.

**Comment by wottpal** [comment]
You guys rock! Looking forward to try this!

**Comment by rori4** [comment]
I can confirm the https://github.com/wevm/viem/issues/1342 and https://github.com/oven-sh/bun/issues/6189 are no longer an issue with the latest version. Great job guys!

**Comment by ph1losof** [comment]
still an issue for me when using ethers v6 and bun v1.0.29 I just subscribed to Mempool like this: 

```
wsProvider.on("pending", (tx) => {
  wsProvider.getTransaction(tx).then(async (transaction) => {
```

```
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
249 |     /**
250 |      *  Sub-classes **must** call this with messages received over their
251 |      *  transport to be processed and dispatched.
252 |      */
253 |     async _processMessage(message) {
254 |         const result = (JSON.parse(message));
                              ^
SyntaxError: JSON Parse error: Unexpected identifier "too"
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:254:25
      at _processMessage (/Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:253:27)
      at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
```

**Comment by Electroid** [comment]
> still an issue for me when using ethers v6 and bun v1.0.29 I just subscribed to Mempool like this:
> 
> ```
> wsProvider.on("pending", (tx) => {
>   wsProvider.getTransaction(tx).then(async (transaction) => {
> ```
> 
> ```
>       at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
> 249 |     /**
> 250 |      *  Sub-classes **must** call this with messages received over their
> 251 |      *  transport to be processed and dispatched.
> 252 |      */
> 253 |     async _processMessage(message) {
> 254 |         const result = (JSON.parse(message));
>                               ^
> SyntaxError: JSON Parse error: Unexpected identifier "too"
>       at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:254:25
>       at _processMessage (/Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-socket.js:253:27)
>       at /Users/tentacles/Projects/stealth_ff/node_modules/ethers/lib.esm/providers/provider-websocket.js:47:13
> ```

It's possible this could be another bug, could you open another issue?

**Comment by ctjlewis** [comment]
On latest v1.2.4, testing OpenAI's realtime websockets, needed `await Bun.sleep()` for at least 500ms before `ws.send()`, otherwise throws `DOMException InvalidStateError`. From: https://github.com/oven-sh/bun/issues/2476

**Comment by Jarred-Sumner** [comment]
@ctjlewis that behavior is inconvenient, but it is correct as per the spec:
> The send(data) method steps are:
> If [this](https://webidl.spec.whatwg.org/#this)'s [ready state](https://websockets.spec.whatwg.org/#websocket-ready-state) is [CONNECTING](https://websockets.spec.whatwg.org/#dom-websocket-connecting), then throw an "[InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).
