### ISSUE TITLE
`bun reinstall`

### ISSUE THREAD

**Issue by NatoBoram** [oven-sh/bun#6689]
### What is the problem this feature would solve?

When testing between Bun and Node.js, I sometimes have to `rm -rf node_modules bun.lockb && pnpm i` and `rm -rf node_modules && bun install`.

### What is the feature you are proposing to solve the problem?

`bun reinstall`, which would ensure that the `node_modules` folder is exactly as it would be after a `bun install`

**Comment by Electroid** [comment]
Ideally we would fix the root cause. Is there a package.json or set of steps where we can try to figure out the issue?

**Comment by NatoBoram** [comment]
Oh, it's not about a specific issue, it's just an action I'm doing to make sure it works across both. I don't actually have a "problem", I just thought this could be a nice little alias.

Another case when it's useful is if I have to update a `package-lock.json` because the project uses `npm` but I'm using `bun` on my workspace

**Comment by huseeiin** [comment]
why delete the modules? they'll run mostly the same except for postinstall

**Comment by Jarred-Sumner** [comment]
`bun install --force` does this
