### ISSUE TITLE
Bun.env limited to 768?

### ISSUE THREAD

**Issue by mckamyk** [oven-sh/bun#6694]
### What version of Bun is running?

v1.0.7

### What platform is your computer?

Linux 5.10.196-183.736.amzn2.x86_64

### What steps can reproduce the bug?

Load up a lot of environment variables. In my case, I'm running this in a oven/bun docker image inside of a large K8s cluster. This K8s cluster is populating lots of environment variables.

```sh
echo "console.log(Object.keys(Bun.env).length)" > test.ts
bun run test.ts
# -> 768
env | wc -l
# -> 952
```

### What is the expected behavior?

I expect Bun.env to see the same env variables
I mainly noticed it because of the 4 env variables I was having k8s assign to my pod, only 1 of them was recognized inside Bun, but all 4 were in the `env | grep MY_ENV` command.

### What do you see instead?

Bun doesn't seem to load past 768 Env vars. Perhaps on of my variables is breaking the parsing somehow, but 768 does seem like a somewhat round number (3 * 256)

### Additional information

https://discord.com/channels/876711213126520882/1166504028771987556/1166504028771987556

**Comment by Electroid** [comment]
Congrats on being the first to run into this limit. We'll fix it.

**Comment by paperclover** [comment]
JSEnvironmentVariableMap.cpp line 116

![image](https://github.com/oven-sh/bun/assets/24465214/5af38d42-d11b-48d3-9aa6-30d10b521d84)

**Comment by mckamyk** [comment]
Nice.

I'm not entirely sure why K8s is trying to provide the name, port, hostname, and container IP of every single pod, service, and named port all as environment variables to every pod in the cluster but... here we are.

Thanks for the attention, I've got a hard coded container moving up to production for the time being.

**Comment by mckamyk** [comment]
You people are monsters.

Thanks guys keep it up.
