### ISSUE TITLE
FFI docs "how does a 64-bit pointer fit in a JavaScript number" section is confusing and misleading

### ISSUE THREAD

**Issue by silversquirl** [oven-sh/bun#6708]
### What is the type of issue?

Documentation is confusing

### What is the issue?

This section states:

> 64-bit processors support up to 52 bits of addressable space

However, this is the limit for *physical* address space. The limits for *virtual* address space are what matters here. Virtual addresses on x86_64 processors can be up to 57 bits long, with [Intel 5-level paging](https://en.wikipedia.org/wiki/Intel_5-level_paging), however in most cases operating systems will not allocate addresses more than 48 bits long, for backwards compatibility reasons.

The section also states:

> that leaves us with about 11 bits of extra space.

Which is wrong for any combination of numbers. Maybe this came from subtracting `53` from `64`? But `64` isn't a relevant number here, since we're talking about how many integer bits a float can store, not how many bits the float itself uses.

The correct value here is `53 - 48 = 5`

### Where did you find it?

https://bun.sh/docs/api/ffi#pointers

**Comment by KuwazyStudio** [comment]
This could explain the segmentation errors when using FFI in Bun...

**Comment by Jarred-Sumner** [comment]
If you use 5-level paging and run into an issue with Bun because of that, please file an issue about that and mention this one.

Until then, I'm closing this issue because it causes confusion.

@Marzin-bot most likely, the issue you're seeing is something related to GC's interaction with the pointers.

**Comment by silversquirl** [comment]
The documentation is still wrong. This issue should be clarified if it's causing confusion, not closed.

**Comment by silversquirl** [comment]
To clarify, this issue is not about 5-level paging, that's just an aside. The issue is that the numbers quoted in the documentation are incorrect and/or misleading.
