### ISSUE TITLE
Integrate bash completions into `bun completions`

### ISSUE THREAD

**Issue by evanwashere** [oven-sh/bun#671]
@evanwashere I think the file I need to edit for installing bash completions is [install_completions_command.zig](https://github.com/oven-sh/bun/blob/main/src/cli/install_completions_command.zig)

cc: @Jarred-Sumner

_Originally posted by @zombieleet in https://github.com/oven-sh/bun/issues/403#issuecomment-1179018252_

**Comment by zombieleet** [comment]
I am currently making the necessary changes to the file

**Comment by zombieleet** [comment]
@evanwashere The zig part has been implemented 😃

**Comment by max-programming** [comment]
For some reason even after running `bun completions` it's not working for me

**Comment by zombieleet** [comment]
@max-programming what issue are you facing with this?

**Comment by max-programming** [comment]
Sorry @zombieleet I uninstalled Linux now.
Basically, even after running `bun completions`, the completions didn't work for me

**Comment by bluet** [comment]
I'm experiencing the same issue.

```
$ curl -fsSL https://bun.sh/install | bash
##O#-#                                                                        
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 

Added "~/.bun/bin" to $PATH in "~/.bashrc" 

To get started, run: 

 source /home/bluet/.bashrc 
  bun --help 
$ source /home/bluet/.bashrc
$ bun --version
0.4.0
$ echo $SHELL
/bin/bash
$ bun completions
error: Could not find a directory to install completions in.
Please either pipe it:
   bun completions > /to/a/file

 Or pass a directory:

   bun completions /my/completions/dir
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

```

**Comment by mnpenner** [comment]
You can trick it with ` SHELL=bash bun completions /usr/share/bash-completion/completions` or `SHELL=bash bun completions > /usr/share/bash-completion/completions/bun` but I still don't get completions.

**Comment by adriangalilea** [comment]
I would like to opt-out on the .zshrc modification, I already have the completions elsewhere and when I install bun it adds it regardless.
