### ISSUE TITLE
Bun runtime doesn't install essential files for specific library.

### ISSUE THREAD

**Issue by yorunoken** [oven-sh/bun#6712]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. create a new, empty, directory
2. run `bun install  rosu-pp`, an osu!game library written in rust, it's a javascript port.
3. watch it install
4. go into `node_modules/rosu-pp`
5. see that it didn't install some essential files, such as: `index.node`  and `target`

### What is the expected behavior?

the expected behaviour is that it was expected to install all of the essential files.

### What do you see instead?

I see that it failed to install/unpack some files

### Additional information

I talked with the person who coded the library and he said, and I quote:
> no clue how the compilation interacts with npm/bun 🥴

**Comment by yorunoken** [comment]
npm
![](https://media.discordapp.net/attachments/1116047971583262850/1166870617287577630/image.png)

bun package manager
![](https://media.discordapp.net/attachments/1116047971583262850/1166870739421503508/image.png)

**Comment by paperclover** [comment]
Duplicate of #606
