### ISSUE TITLE
Reading from `process.stdin` doesn't work (hangs forever)

### ISSUE THREAD

**Issue by acheronfail** [oven-sh/bun#6713]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.1.59-1-lts x86_64 unknown

### What steps can reproduce the bug?

`bun` hangs forever when reading `process.stdin` - and is completely unable to read `process.stdin` in some cases.

I setup a reproducible repository here: https://github.com/acheronfail/bun-stdin/

Here is what doesn't work:

```js
// NOTE: this doesn't work - it hangs forever
function readProcessStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on('error', (err) => reject(err));
    process.stdin.on('close', () => resolve(Buffer.concat(chunks).toString('utf-8')));
    process.stdin.on('data', (chunk) => chunks.push(chunk));
  });
}
```

Here is a workaround that does appear to work:

```js
// NOTE: this does work
async function readBunStdin() {
  const chunks = [];
  for await (const chunk of Bun.stdin.stream()) {
    chunks.push(chunk);
  }

  return Buffer.concat(chunks).toString('utf-8');
}
```

### What is the expected behavior?

I would expect that `process.stdin` would behave the same as it does with `node`.

The fact that it doesn't means I can't just use `bun` as a replacement for `node`, since `bun`'s `process.stdin` implementation doesn't appear to work properly. :cry: 

### What do you see instead?

`process.stdin` hangs forever!

Using the repository to reproduce:

```bash
# this uses process.stdin:
$ node -e 'console.log("X".repeat(10_000))' | bun ./index.mjs process
reading stdin... # hangs forever here
```

**Comment by acheronfail** [comment]
Oh! On further investigation, I think `bun` is not emitting the `close` event on `process.stdin`! It does however, emit the `end` event.

Compare these:

```js
// NOTE: this doesn't work - it hangs forever
function readProcessStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on('error', (err) => reject(err));
    process.stdin.on('close', () => resolve(Buffer.concat(chunks).toString('utf-8')));
    process.stdin.on('data', (chunk) => chunks.push(chunk));
  });
}
```

```js
// NOTE: this WORKS
function readProcessStdin() {
  return new Promise((resolve, reject) => {
    const chunks = [];
    process.stdin.on('error', (err) => reject(err));
    //		!!! notice "close" changed to "end" here
    process.stdin.on('end', () => resolve(Buffer.concat(chunks).toString('utf-8')));
    process.stdin.on('data', (chunk) => chunks.push(chunk));
  });
}
```

Both `close` and `end` work with `node`. It appears that `bun` doesn't emit a `close` event on `process.stdin` then.

**Comment by liz3** [comment]
assuming stdin is going to be closed isn't good since it requires the piping process to end but of course we should emit `close` if node does, il look into this

**Comment by thecatblake** [comment]
Bun.stdin also keeps reading inputs when I manually type ctr D.
