### ISSUE TITLE
`bun add` fails to add github tarball to node_modules directory

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#6717]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 6.2.0-35-generic x86_64 unknown

### What steps can reproduce the bug?

- [add this pkg](https://github.com/nirv-ai/tinkerbuntune) via `bun add github:nirv-ai/tinkerbuntune`
- review node_modules dir

### What is the expected behavior?

node_modules directory reflects package.json.dependencies

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/10324554/4e671037-bc2e-443b-9f2c-79147708148c)

**Comment by noahehall** [comment]
lol the dependency was in package.json twice which caused the unusual experience, perhaps bun should throw in this scenario?

**Comment by dylan-conway** [comment]
Can you try this with the canary release? It was fixed recently
