### ISSUE TITLE
Runtime fails to use proxy with `bun`, works fine with `node`

### ISSUE THREAD

**Issue by Wilson9512** [oven-sh/bun#6721]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Environment:
Node.js version:  v18.0.0
OS: macOS, Linux
Library version:  bun@1.0.6
Proxy Server: 
When running a script that sends a request via a proxy server, it fails to use the proxy when running with bun, but works fine when running directly with node.

```
import http from "http";
import tunnel from "tunnel";

const proxyOptions = {
  proxy: {
    host: yourHost,
    port: yourPort,
    proxyAuth: 'authName:authPassword,  
  },
};

const tunnelAgent = tunnel.httpsOverHttp(proxyOptions);

const requestOptions = {
  host: 'httpbin.org',`
   port: 443,
   path: '/get',
   method: 'GET',
   agent: tunnelAgent,  
   timeout: 5000,
 };
 
 const req = http.request(requestOptions, (res) => {
   let data = '';
 
   res.on('data', (chunk) => {
     data += chunk;
   });
 
   res.on('end', () => {
     console.log('Response:', data);
   });
 });
 
 req.on('error', (error) => {
   console.error('Error:', error);
 });
 
 req.on('timeout', () => {
   console.error('Request timed out');
   req.abort();
 });
 
 req.end();
 
```

Run `bun your_script.js`
Run `node your_script.js`
Expected Behavior:
Both bun and node should successfully send the request through the proxy server.

Actual Behavior:
Running with bun fails to use the proxy.
Running with node successfully uses the proxy.
Additional Notes:
I've seen similar issues here, but my environment seems to be different.

// bun res
```
Response: {
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "Bun/1.0.7",
    "X-Amzn-Trace-Id": "X-Amzn-Trace-Id"
  },
  "origin": "${myIp}",
  "url": "https://httpbin.org/get"
}
```

// node res
```
Response: {
  "args": {},
  "headers": {
    "Host": "httpbin.org",
    "X-Amzn-Trace-Id": "X-Amzn-Trace-Id"
  },
  "origin": "${proxyIp}",
  "url": "https://httpbin.org/get"
}
```

**Comment by CsVeryLoveXieWenLi** [comment]
你可以使用Bun内置的函数，而无需使用Nodejs的Api或者Npm模块的Api。

Machine Translate -> You can use Bun's built-in functions without using the Nodejs API or the Npm module API.

```
const response = await fetch('http://app.com', {
    'proxy': 'http://username:password@hostname:port'
});
const html = await response.text(); // HTML string

console.log(html);
```

**Comment by entrptaher** [comment]
This is still not fixed, after a bit more research, I found if the address have `https` the request fails while the `http` works fine.

```

# using tsx and https://httpbin.org/ip

➜  tsx proxy.ts
Status Code: 200
Headers: {"access-control-allow-credentials":"true","access-control-allow-origin":"*","content-length":"29","content-type":"application/json","date":"Sun, 04 Aug 2024 06:06:22 GMT","server":"gunicorn/19.9.0","connection":"close"}
Response body: {
  "origin": "173.0.9.70"
}

# using bun and http://httpbin.org/ip

➜  bun run proxy.ts
Status Code: 200
Headers: {"access-control-allow-credentials":"true","access-control-allow-origin":"*","content-length":"33","content-type":"application/json","date":"Sun, 04 Aug 2024 06:06:25 GMT","connection":"close","server":"gunicorn/19.9.0"}
Response body: {
  "origin": "45.127.248.127"
}

# using bun and https://httpbin.org/ip

➜  bun run proxy.ts
Status Code: 407
Headers: {"date":"Sun, 04 Aug 2024 06:06:32 GMT","content-length":"121","content-type":"text/plain; charset=utf-8","connection":"close","proxy-authenticate":"Basic realm=\"Invalid proxy credentials or missing IP Authorization.\"","proxy-connection":"close","x-webshare-error":"407","x-webshare-reason":"invalidpassword"}
Response body: Not authenticated or invalid authentication credentials. Make sure to update your proxy address, proxy username and port.
```

**Comment by Anyoks** [comment]
I am experiencing the very same issue here. Took two weeks to realize it is an issue with bun. Node works without any issue.
I've tried this with ```axios```  ```got```  and ```fetch```. No success.
I get two issues:

```UNABLE_TO_GET_ISSUER_CERT: unable to get issuer certificate```

And

```
 message: "Request failed with status code 407",
  name: "AxiosError",
  code: "ERR_BAD_REQUEST",
    data: "Proxy Authentication Required\n",
  },
....
  toJSON: [Function: toJSON],
  isAxiosError: true,
  toString: [Function: toString],
}
AxiosError: Request failed with status code 407
```

Anyone looking into this? Or Did you find a solution for this?

**Comment by moinulmoin** [comment]
> This is still not fixed, after a bit more research, I found if the address have `https` the request fails while the `http` works fine.
> 
> 
> 
> ```
> 
> 
> 
> # using tsx and https://httpbin.org/ip
> 
> 
> 
> ➜  tsx proxy.ts
> 
> Status Code: 200
> 
> Headers: {"access-control-allow-credentials":"true","access-control-allow-origin":"*","content-length":"29","content-type":"application/json","date":"Sun, 04 Aug 2024 06:06:22 GMT","server":"gunicorn/19.9.0","connection":"close"}
> 
> Response body: {
> 
>   "origin": "173.0.9.70"
> 
> }
> 
> 
> 
> # using bun and http://httpbin.org/ip
> 
> 
> 
> ➜  bun run proxy.ts
> 
> Status Code: 200
> 
> Headers: {"access-control-allow-credentials":"true","access-control-allow-origin":"*","content-length":"33","content-type":"application/json","date":"Sun, 04 Aug 2024 06:06:25 GMT","connection":"close","server":"gunicorn/19.9.0"}
> 
> Response body: {
> 
>   "origin": "45.127.248.127"
> 
> }
> 
> 
> 
> # using bun and https://httpbin.org/ip
> 
> 
> 
> ➜  bun run proxy.ts
> 
> Status Code: 407
> 
> Headers: {"date":"Sun, 04 Aug 2024 06:06:32 GMT","content-length":"121","content-type":"text/plain; charset=utf-8","connection":"close","proxy-authenticate":"Basic realm=\"Invalid proxy credentials or missing IP Authorization.\"","proxy-connection":"close","x-webshare-error":"407","x-webshare-reason":"invalidpassword"}
> 
> Response body: Not authenticated or invalid authentication credentials. Make sure to update your proxy address, proxy username and port.
> 
> ```

sorry to bother, @Jarred-Sumner  when we can expect this issue to be resolved? may be it's not passing credentials when it's https.

**Comment by ibash** [comment]
Encountered this too. I only took a few min to look into it, so haven't fully root caused.
The library I'm using uses `url.urlToHttpOptions` (https://nodejs.org/api/url.html#urlurltohttpoptionsurl) before calling fetch which maybe returns different options than what bun's expecting. In particular it doesn't return `url` property but `href` instead, and I think bun expects `url` property.

**Comment by theodufort** [comment]
Still getting the same error with Axios and Bun v1.1.8

**Comment by G4tes** [comment]
any solution??

**Comment by harmanpreet-singh-safe-security** [comment]
i am using https://www.npmjs.com/package/http-proxy-middleware . not working but bun. proxy issues. any solution?
