### ISSUE TITLE
`bunx eslint --init .` Executable not found in $PATH: "npm"

### ISSUE THREAD

**Issue by RodrigoDornelles** [oven-sh/bun#6728]
### What version of Bun is running?

1.0.6

### What platform is your computer?

Linux 5.15.0-86-generic x86_64 unknown

### What steps can reproduce the bug?

```
bun lint --init
```

### What is the expected behavior?

a start eslint files

### What do you see instead?

```
$ bunx eslint . --init
You can also run this command directly using 'npm init @eslint/config'.

Oops! Something went wrong! :(

ESLint: 8.52.0

TypeError: Executable not found in $PATH: "npm"
    at spawnSync (native)
    at <anonymous> (node:child_process:171:24)
    at spawnSync (/tmp/eslint--bunx/node_modules/cross-spawn/index.js:28:59)
    at <anonymous> (/tmp/eslint--bunx/node_modules/eslint/bin/eslint.js:141:8)
    at main (/tmp/eslint--bunx/node_modules/eslint/bin/eslint.js:129:15)
    at <anonymous> (/tmp/eslint--bunx/node_modules/eslint/bin/eslint.js:150:23)
    at global code (/tmp/eslint--bunx/node_modules/eslint/bin/eslint.js:45:8)
```

**Comment by Electroid** [comment]
If you want to force `eslint` to use bun, you'll need to run: `bunx --bun eslint . --init`

**Comment by RodrigoDornelles** [comment]
@Electroid 
> If you want to force `eslint` to use bun, you'll need to run: `bunx --bun eslint . --init`

gives the same error, because `bun lint --init .` seems to me to be an alias for `bunx eslint --init .`

**Comment by Electroid** [comment]
> @Electroid
> 
> > If you want to force `eslint` to use bun, you'll need to run: `bunx --bun eslint . --init`
> 
> gives the same error, because `bun lint --init .` seems to me to be an alias for `bunx eslint --init .`

Check your package.json, there is likely a "lint" script under `scripts`. Bun does not have a linter, it is instead running a command.

**Comment by RodrigoDornelles** [comment]
@Electroid 

> Check your package.json, there is likely a "lint" script under `scripts`. Bun does not have a linter, it is instead running a command.

there is a script called `lint` but the content is `bunx eslint .` and not `bunx eslint --init .`

 * **file:** `package.json`

```
{
    "name": "some-project",
    "scripts": {
        "lint": "bun install --optional --silent && bunx eslint .",
        "lint:fix": "bun install--optional --silent  && bunx eslint . --fix",
        "format": "bunx prettier --check --config .prettierrc src/*.ts",
        "format:fix": "bunx prettier --write --config .prettierrc src/*.ts", 
        "start": "bun run build --watch",
        "build": "bun run build:before && bun build --minify --outdir dist --target browser --asset-naming '[name].[ext]' --entry-naming '[name].[ext]' src/worker_service.ts src/main.ts public/*",
        "build:prod": "npm run build && bun bundle.ts",
        "build:before": "mkdir -p dist && cp assets/* dist && cp manifest.json dist"
    },
    "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^6.3.0",
        "eslint": "^8.46.0",
        "eslint-config-prettier": "^9.0.0",
        "eslint-plugin-prettier": "^5.0.0",
        "prettier": "^3.0.1",
        "bun": "^1.0.6"
    }
}
```

**Comment by KaiPonel** [comment]
Have you found any fix to get `eslint` running? 

I'm also facing this issue. Since also facing [this](https://github.com/oven-sh/bun/issues/4598) I can only use `bun x` instead of `bunx`. 

Trying to run something like `bun x --bun eslint --init`, which should force the usage of Buns JS runtime still results in the error @RodrigoDornelles faces in his message above.

**Comment by paperclover** [comment]
Eslint does [this](https://github.com/eslint/eslint/blob/a451b32b33535a57b4b7e24291f30760f65460ba/bin/eslint.js#L147), which i'm not so sure how we can deal with for people without npm installed.
```
spawn.sync("npm", ["init", "@eslint/config"], { encoding: "utf8", stdio: "inherit" });
```

I wonder if this is case the eslint team would be okay accepting a PR to make this use `process.env.npm_execpath` instead of hardcoding `npm`.

**Comment by RodrigoDornelles** [comment]
its a eslint problem! closing the issue!
