### ISSUE TITLE
Cheerio doesn't work with bun (ReferenceError: Can't find variable: require)

### ISSUE THREAD

**Issue by yamalight** [oven-sh/bun#674]
### Version

0.1.4

### Platform

Linux LIGHTDESK-MK3 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. Install cheerio `bun add cheerio`
2. Create simple script that uses it, e.g.:
    ```js
    import { load } from 'cheerio';

    const $ = load('<div>test</div>');
    const d = $('div').text();

    console.log(d);
    ```
4. Try to execute it with `bun script.js`

### How often does it reproduce? Is there a required condition?

Reproducible every time.

### What is the expected behavior?

Script should run and output `test` (can be tested with node.js)

### What do you see instead?

```sh
→ bun index.js
1 |
2 | var { ElementType, isTag: isTagRaw} = require($d78f54e2);
   ^
 ReferenceError: Can't find variable: require
      at /home/yamalight/github/yamalight/bun-bug/node_modules/domhandler/lib/esm/node.js:1:0
```

### Additional information

It seems like it has something to do with ESM/CJS module resolutions, but the code does work fine in node.js using ESM 🤔

**Comment by Jarred-Sumner** [comment]
This is a `require` bug

But, for now, what happens if you do:

```js
var {load} = require("chereio");
```

**Comment by oculus42** [comment]
```javascript
const { load } = require('cheerio');
```

Works as expected.

Also able to use:
```javascript
import { load } from 'cheerio/lib';
```

This gets the same thing as the `main` entry rather than the `module`.

**Comment by yamalight** [comment]
yep, using `const { load } = require('cheerio');` works as expected!

**Comment by freedmand** [comment]
I'm experiencing similar behavior trying to use [`@aws-sdk/client-athena`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-athena/index.html).

`import { AthenaClient } from "@aws-sdk/client-athena";` fails with `ReferenceError: Can't find variable: require` (running with `ts-node` works as expected)

The alternative method with `require` is also failing (using Bun 0.1.4, on an M1 Mac).

`const { AthenaClient } = require("@aws-sdk/client-athena");` fails with:

```
error: Could not resolve: "http2". Maybe you need to "bun install"?

const http2_1 = require("http2");
```

Happy to submit a more comprehensive repro if desired

**Comment by ShivamJoker** [comment]
@Jarred-Sumner I am having same with other AWS SDK libs can you please merge this ASAP and release it? I am still relying on esbuild :(
