### ISSUE TITLE
Using cluster for Node.js on benchmarking

### ISSUE THREAD

**Issue by WillianAgostini** [oven-sh/bun#6740]
### What version of Bun is running?

latest

### What steps can reproduce the bug?

On benchmarking with a comparison of Node.js, why we don't use [cluster](https://nodejs.org/api/cluster.html) for Node.js?
https://github.com/oven-sh/bun/blob/main/bench/react-hello-world/react-hello-world.node.jsx

![image](https://github.com/oven-sh/bun/assets/22686401/3f6eeb62-0037-4406-ada3-8e0c268bd660)

### Additional information

Node.js can improve performance with a cluster as a single thread and the benchmark does not specify whether tests are run on a multi-core CPU

**Comment by Jarred-Sumner** [comment]
the benchmarks use mostly default configurations

we don't use cluster in bun either

**Comment by WillianAgostini** [comment]
Bun is single thread? How does it work in relation to threads for multiple requests?
because node.js is single threaded and depends on the use of clusters to use all cpus
