### ISSUE TITLE
`bunx @next/codemod@latest` still use stale version, not latest

### ISSUE THREAD

**Issue by ImBIOS** [oven-sh/bun#6741]
### What version of Bun is running?

1.0.7+8f42d8c2ddd85402497e637b3d8397732e373e5c

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. `bunx @next/codemod@SOME_STALE_VERSION`
2. `bunx @next/codemod@latest next-og-import .`

Voila, I still got the stale version:

```
WARNING: Git directory is not clean. Forcibly continuing.
Invalid transform choice, pick one of:
- name-default-component
- add-missing-react-import
- withamp-to-config
- url-to-withrouter
- cra-to-next
- new-link
- next-image-to-legacy-image
- next-image-experimental
- built-in-next-font
```

`next-og-import` option should be available in latest version.

### What is the expected behavior?

Always check for specified tag or version when specified.

### What do you see instead?

Stale version

### Additional information

Related:
- https://github.com/oven-sh/bun/issues/6375
- https://github.com/oven-sh/bun/issues/4989
- https://github.com/oven-sh/bun/issues/4981
- https://github.com/oven-sh/bun/issues/5024
- https://github.com/oven-sh/bun/pull/5346

**Comment by Electroid** [comment]
Thanks, going to re-open #4989 since this may have not been fixed.
