### ISSUE TITLE
undefined is not an object (evaluating 'Buffer2.from')

### ISSUE THREAD

**Issue by francescochiapello** [oven-sh/bun#6753]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

This is a simple `express` API layer code written in `index.ts` file:

> import express, { Express, Request, Response } from 'express';
> 
> const app: Express = express();
> const port = process.env.PORT;
> 
> app.get('/', (req: Request, res: Response) => {
>   res.send('Express + TypeScript Server');
> });
> 
> app.listen(port, () => {
>   console.log(`⚡️[server]: Server is running at http://localhost:${port}`);
> });

When i run `bun build ./index.ts --outfile=bundle.js` the code is correctly built in bundle.js file but when i try to run it with `bun run bundle.js` or `node bundle.js` I'm getting this error:

> 37802 |     return Buffer2(arg, encodingOrOffset, length);
> 37803 |   };
> 37804 |   /*! safe-buffer. MIT License. Feross Aboukhadijeh <https://feross.org/opensource> */
> 37805 |   var buffer = (init_buffer(), __toCommonJS(exports_buffer));
> 37806 |   var Buffer2 = buffer.Buffer;
> 37807 |   if (Buffer2.from && Buffer2.alloc && Buffer2.allocUnsafe && Buffer2.allocUnsafeSlow) {
>          ^
> TypeError: undefined is not an object (evaluating 'Buffer2.from')

### What is the expected behavior?

The `bundle.js` is correctly generated and should be executable with bun or node runtime.

**Comment by Electroid** [comment]
If you're planning to run the bundle with bun, you'll need to specify a target.

```sh
bun build --target=bun
bun build --target=node
```

**Comment by kirestein** [comment]
I got this same error running tauri npm run tauri dev, I tried run the npm run build --target=node, but it didn't resolved
