### ISSUE TITLE
bun 1.0.7 is not picking up default timezone from Mac OS

### ISSUE THREAD

**Issue by jpravetz** [oven-sh/bun#6757]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

OS: Mac Sonoma 14.0 (23A344)

## expected:

bun will pick up timezone (TZ) from OS, just as does nodejs.

```js
// nodejs
new Date().getTimezoneOffset()
// output
360
```

## actual:

bun tz offset is 0

```js
// bun
new Date().getTimezoneOffset()
// output
0
```

## Workaround:

Set TZ using environment variable, but this is less than ideal on a laptop that travels.

## Other Info

I am in Costa Rica timezone (which is USA CST)

**Comment by Electroid** [comment]
Are you running this with `bun` or `bun test`? (`bun test` will default to UTC)

**Comment by jpravetz** [comment]
Aha! I am using bun test (to test TZ logic).

**Comment by Electroid** [comment]
Yes, this is the intended behaviour, essentially to prevent flaky tests due to time zone differences. If you want to manually set the timezone you can use the `TZ` environment variable or import `setTimezone` from `bun:jsc`

**Comment by jpravetz** [comment]
Yes, I did exactly that (`process.env.TZ = 'CST';`). It does make testing more predictable. Thanks.
