### ISSUE TITLE
`console.log({ call: "uh oh" })` logs an empty object

### ISSUE THREAD

**Issue by dragonflyfree** [oven-sh/bun#6766]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

```ts
console.log({ call: "uh oh" })
```

### What is the expected behavior?

`console.log({ call: "uh oh" })` should log:
```
{
    call: "uh oh"
}
```

### What do you see instead?

`console.log({ call: "uh oh" })` logs:
```
{}
```

**Comment by Jarred-Sumner** [comment]
The cause:

https://github.com/oven-sh/bun/blob/d1244c8b1feb367220218f9c78dd73ce4cdcc76b/src/bun.js/bindings/exports.zig#L1852-L1853

**Comment by dragonflyfree** [comment]
Resolved
