### ISSUE TITLE
Error in setup.sh to make my first build

### ISSUE THREAD

**Issue by TaduJR** [oven-sh/bun#6767]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 6.1.21.2-microsoft-standard-WSL2+ x86_64 x86_64

### What steps can reproduce the bug?

bash ./scripts/setup.sh command to make my first build

### What is the expected behavior?

Build without error

### What do you see instead?

-- Downloading WebKit
-- Using static sqlite3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tadujr/bun/build
ninja: error: loading 'build.ninja': No such file or directory

**Comment by paperclover** [comment]
can you post the full log of CMake?

**Comment by I-A-S** [comment]
This is a little bug in the setup.sh

For now run `ninja -C build` after setup.sh exits with `ninja: error: loading 'build.ninja': No such file or directory`

**Comment by Hanaasagi** [comment]
Same for me, full log 
```
>>​ bash ./scripts/setup.sh
+ git submodule update --init --recursive --progress --depth=1 --checkout src/deps/picohttpparser src/deps/mimalloc src/deps/zlib src/deps/libarchive src/deps/boringssl src/deps/lol-html src/deps/tinycc src/deps/c-ares src/deps/zstd src/deps/base64
which: no clang++-16 in (/home/kumiko/.bun/bin/:/home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.1297+a9e66ed73:/home/kumiko/.local/bin:/home/kumiko/.cargo/bin:/home/kumiko/go/bin:/home/kumiko/zig/zig-linux-x86_64-0.11.0-dev.3312+ab37ab33c/zig:/home/kumiko/.local/bin:/home/kumiko/.cargo/bin:/home/kumiko/go/bin:/home/kumiko/.local/bin:/home/kumiko/.cargo/bin:/home/kumiko/go/bin:/home/kumiko/.local/bin:/home/kumiko/.cargo/bin:/home/kumiko/go/bin:/home/kumiko/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/home/kumiko/.oh-my-zsh/custom/plugins/kubetail:/home/kumiko/.krew/bin:/home/kumiko/.oh-my-zsh/custom/plugins/kubetail:/home/kumiko/.krew/bin:/home/kumiko/.oh-my-zsh/custom/plugins/kubetail:/home/kumiko/.krew/bin:/home/kumiko/.oh-my-zsh/custom/plugins/kubetail:/home/kumiko/.krew/bin)
base64 - already built
boringssl - already built
cares - already built
libarchive - already built
lolhtml - already built
mimalloc-debug - already built
mimalloc - already built
tinycc - already built
zlib - already built
zstd - already built
(run with -f to rebuild)
bun install v1.0.6 (969da088)

Checked 180 installs across 188 packages (no changes) [4.00ms]
-- Configuring Bun 1.0.8 in /home/kumiko/zig/bun/build
-- The CMake build type is: Debug
-- The C compiler identification is Clang 16.0.6
-- The CXX compiler identification is Clang 16.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-16 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++ Compiler: Clang 16.0.6 at /usr/bin/clang++
-- Building for CPU Target: haswell
-- Found Zig Compiler: /home/kumiko/zig/zig-linux-x86_64-0.12.0-dev.1297+a9e66ed73/zig
-- Found Bun: /home/kumiko/.bun/bin/bun
-- Using ccache: /usr/bin/ccache
-- Using Pre-built WebKit: bun-webkit-linux-amd64
-- Using static sqlite3
-- Configuring done (1.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/kumiko/zig/bun/build
ninja: error: loading 'build.ninja': No such file or directory


```

**Comment by nithinkjoy-tech** [comment]
I am getting same issue in my Ubuntu 22.04.3 LTS
```
nithinkjoy@nithinkjoy-Nitro-AN515-43:~/Programming/Bun.js/bun$ export PATH="$PATH:/usr/bin/ninja"
nithinkjoy@nithinkjoy-Nitro-AN515-43:~/Programming/Bun.js/bun$ echo $PATH | tr ':' '\n'
/home/nithinkjoy/.nvm/versions/node/v18.18.2/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
/snap/bin
/home/nithinkjoy/zig/0.12.0-dev.1297+a9e66ed73/files
/home/nithinkjoy/Programming/Bun.js/bun/build
/usr/bin/ninja
nithinkjoy@nithinkjoy-Nitro-AN515-43:~/Programming/Bun.js/bun$ bash ./scripts/setup.sh
+ git submodule update --init --recursive --progress --depth=1 --checkout src/deps/picohttpparser src/deps/mimalloc src/deps/zlib src/deps/libarchive src/deps/boringssl src/deps/lol-html src/deps/tinycc src/deps/c-ares src/deps/zstd src/deps/base64
base64 - already built
boringssl - already built
cares - already built
libarchive - already built
lolhtml - already built
mimalloc-debug - already built
mimalloc - already built
tinycc - already built
zlib - already built
zstd - already built
(run with -f to rebuild)
bun install v1.0.6 (969da088)

Checked 180 installs across 188 packages (no changes) [6.00ms]
mkdir: cannot create directory ‘build’: File exists
-- Configuring Bun 1.0.8 in /home/nithinkjoy/Programming/Bun.js/bun/build
-- The CMake build type is: Debug
-- C++ Compiler: Clang 16.0.6 at /usr/bin/clang++-16
-- Building for CPU Target: native
-- Found Zig Compiler: /home/nithinkjoy/zig/0.12.0-dev.1297+a9e66ed73/files/zig
-- Found Bun: /home/nithinkjoy/.nvm/versions/node/v18.18.2/bin/bun
-- Using ccache: /usr/bin/ccache
-- Using Pre-built WebKit: bun-webkit-linux-amd64
-- Using static sqlite3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nithinkjoy/Programming/Bun.js/bun/build
ninja: error: loading 'build.ninja': No such file or directory
nithinkjoy@nithinkjoy-Nitro-AN515-43:~/Programming/Bun.js/bun$ ninja --version
1.10.1
nithinkjoy@nithinkjoy-Nitro-AN515-43:~/Programming/Bun.js/bun$ 

```

**Comment by Hanaasagi** [comment]
Another problem, libatomic is shared object in Archlinux.

```
ld.lld: error: attempted static link of dynamic object /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/libatomic.a
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)

```

temporary workaround is  `-Bdynamic -latomic`

**Comment by paperclover** [comment]
the libatomic thing needs to be fixed

in cmake we have
`target_link_libraries(${bun} PRIVATE "libatomic.a")`
needs to be changed but we must link this staticly for ci and the release

**Comment by TaduJR** [comment]
> can you post the full log of CMake?

I just noticed build command is changed from bash ./scripts/setup.sh to bun setup on the docs(https://bun.sh/docs/project/contributing). I re-cloned the repo I'm building it with "bun setup" command. I will update in a moment.

**Comment by TaduJR** [comment]
It's slightly different error now.

https://pastebin.com/f4gACTti
Here is the full error.

Overview of the error
============================================
-- Build files have been written to: /home/natu/bun/build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
ninja: error: '../src/deps/libmimalloc.o', needed by 'bun-debug', missing and no known rule to make it
error: script "setup" exited with code 1 (SIGHUP)

**Comment by TaduJR** [comment]
> This is a little bug in the setup.sh
> 
> For now run `ninja -C build` after setup.sh exits with `ninja: error: loading 'build.ninja': No such file or directory`

Still same error

natu@DESKTOP-1MPMIJM:~/bun$ ninja -C build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
ninja: error: '../src/deps/libmimalloc.o', needed by 'bun-debug', missing and no known rule to make it

**Comment by MeDerpWasTaken** [comment]
I had the error about `libmimalloc.o` on WSL as well, and making a symlink of it that points to `libmimalloc.a` seems to fix it

**Comment by vitalspace** [comment]
> > This is a little bug in the setup.sh
> > For now run `ninja -C build` after setup.sh exits with `ninja: error: loading 'build.ninja': No such file or directory`
> 
> Still same error
> 
> natu@DESKTOP-1MPMIJM:~/bun$ ninja -C build ninja: Entering directory `build' [0/2] Re-checking globbed directories... ninja: error: '../src/deps/libmimalloc.o', needed by 'bun-debug', missing and no known rule to make it

same

**Comment by vitalspace** [comment]
> I had the error about `libmimalloc.o` on WSL as well, and making a symlink of it that points to `libmimalloc.a` seems to fix it

I applied your idea but now I have more errors:

https://gist.github.com/vitalspace/fddb8eade886f0be40501d2a0fe37fc9

**Comment by I-A-S** [comment]
> > This is a little bug in the setup.sh
> 
> > 
> 
> > For now run `ninja -C build` after setup.sh exits with `ninja: error: loading 'build.ninja': No such file or directory`
> 
> 
> 
> Still same error
> 
> 
> 
> natu@DESKTOP-1MPMIJM:~/bun$ ninja -C build
> 
> ninja: Entering directory `build'
> 
> [0/2] Re-checking globbed directories...
> 
> ninja: error: '../src/deps/libmimalloc.o', needed by 'bun-debug', missing and no known rule to make it

Hey that fix was for the first issue. For this one, as a temporary workaround, do 

`mv src/deps/libmimalloc.a src/deps/libmimalloc.o` 

while you're in the bun root directory (where you ran the `bun setup` or `scripts/setup.sh`). This one is caused by a mismatch in the build-mimalloc.sh and CMake file.

**Comment by tarruda** [comment]
#6800  fixes the libmimalloc error

**Comment by TaduJR** [comment]
> > > This is a little bug in the setup.sh
> > 
> > 
> > > 
> > 
> > 
> > > For now run `ninja -C build` after setup.sh exits with `ninja: error: loading 'build.ninja': No such file or directory`
> > 
> > 
> > Still same error
> > natu@DESKTOP-1MPMIJM:~/bun$ ninja -C build
> > ninja: Entering directory `build'
> > [0/2] Re-checking globbed directories...
> > ninja: error: '../src/deps/libmimalloc.o', needed by 'bun-debug', missing and no known rule to make it
> 
> Hey that fix was for the first issue. For this one, as a temporary workaround, do
> 
> `mv src/deps/libmimalloc.a src/deps/libmimalloc.o`
> 
> while you're in the bun root directory (where you ran the `bun setup` or `scripts/setup.sh`). This one is caused by a mismatch in the build-mimalloc.sh and CMake file.

now i got a different error.

[13/314] Building zig code
Build linux-x64 v4.19.0 - v6.5.7 (haswell)
Zig 0.12.0-dev.1297+a9e66ed73
zig build-obj bun-zig Debug native-native-gnu.2.27: error: the following command terminated unexpectedly:
/home/natu/zig/zig build-obj -freference-trace=16 /mnt/c/Users/Natu/Desktop/Desktop/bun/root.zig -lc -fno-strip --eh-frame-hdr --emit-relocs -ffunction-sections --cache-dir /mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache --global-cache-dir /home/natu/.cache/zig --name bun-zig -fno-stack-check -fno-omit-frame-pointer -fdll-export-fns -target native-native-gnu.2.27 -mcpu haswell --mod async::/mnt/c/Users/Natu/Desktop/Desktop/bun/src/async/posix_event_loop.zig --mod async_io::/mnt/c/Users/Natu/Desktop/Desktop/bun/src/io/io_linux.zig --mod build_options::/mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache/c/6b45aa40d2a8630024ddba745b6d7b9b/options.zig --mod zlib-internal::/mnt/c/Users/Natu/Desktop/Desktop/bun/src/deps/zlib.posix.zig --mod generated/ZigGeneratedClasses.zig::/mnt/c/Users/Natu/Desktop/Desktop/bun/build/codegen/ZigGeneratedClasses.zig --mod generated/ResolvedSourceTag.zig::/mnt/c/Users/Natu/Desktop/Desktop/bun/build/codegen/ResolvedSourceTag.zig --deps async_io,zlib-internal,async,build_options,generated/ZigGeneratedClasses.zig,generated/ResolvedSourceTag.zig --main-mod-path /mnt/c/Users/Natu/Desktop/Desktop/bun --subsystem console --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-zig.o transitive failure
│  ├─ zig build-obj bun-zig Debug native-native-gnu.2.27 failure
│  └─ zig build-obj bun-zig Debug native-native-gnu.2.27 (+1 more reused dependencies)
└─ zig build-obj bun-zig Debug native-native-gnu.2.27 (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache/o/ed8a4a842ff8df69703e29c8c11802a0/build /home/natu/zig/zig /mnt/c/Users/Natu/Desktop/Desktop/bun /mnt/c/Users/Natu/Desktop/Desktop/bun/zig-cache /home/natu/.cache/zig --seed 0x2eafa72a obj -Doutput-file=/mnt/c/Users/Natu/Desktop/Desktop/bun/build/CMakeFiles/bun-zig.o -Dgenerated-code=/mnt/c/Users/Natu/Desktop/Desktop/bun/build/codegen -Dversion=1.0.8 -Dcanary=false -Doptimize=Debug -Dcpu=haswell -Dtarget=native
FAILED: CMakeFiles/bun-zig.o /mnt/c/Users/Natu/Desktop/Desktop/bun/build/CMakeFiles/bun-zig.o
cd /mnt/c/Users/Natu/Desktop/Desktop/bun && /usr/bin/zig build obj -Doutput-file=/mnt/c/Users/Natu/Desktop/Desktop/bun/build/CMakeFiles/bun-zig.o -Dgenerated-code=/mnt/c/Users/Natu/Desktop/Desktop/bun/build/codegen -Dversion=1.0.8 -Dcanary=false -Doptimize=Debug -Dcpu=haswell -Dtarget=native
ninja: build stopped: subcommand failed.
error: script "setup" exited with code 1 (SIGHUP)

**Comment by paperclover** [comment]
re-clone the repository outside of /mnt/c

**Comment by TaduJR** [comment]
> re-clone the repository outside of /mnt/c

same error

-- Configuring done
-- Generating done
-- Build files have been written to: /home/natu/bun/build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
[0/302] Building zig code
Build linux-x64 v4.19.0 - v6.5.7 (haswell)
Zig 0.12.0-dev.1297+a9e66ed73
steps [2/4] zig build-obj bun-zig Debug native-native-gnu.2.27... LLVM Emit Object...
zig build-obj bun-zig Debug native-native-gnu.2.27: error: the following command terminated unexpectedly:
/home/natu/zig/zig build-obj -freference-trace=16 /home/natu/bun/root.zig -lc -fno-strip --eh-frame-hdr --emit-relocs -ffunction-sections --cache-dir /home/natu/bun/zig-cache --global-cache-dir /home/natu/.cache/zig --name bun-zig -fno-stack-check -fno-omit-frame-pointer -fdll-export-fns -target native-native-gnu.2.27 -mcpu haswell --mod zlib-internal::/home/natu/bun/src/deps/zlib.posix.zig --mod generated/ResolvedSourceTag.zig::/home/natu/bun/build/codegen/ResolvedSourceTag.zig --mod build_options::/home/natu/bun/zig-cache/c/ffc27ea8b19c0f8e9f8653e242baeaea/options.zig --mod async::/home/natu/bun/src/async/posix_event_loop.zig --mod async_io::/home/natu/bun/src/io/io_linux.zig --mod generated/ZigGeneratedClasses.zig::/home/natu/bun/build/codegen/ZigGeneratedClasses.zig --deps async_io,zlib-internal,async,build_options,generated/ZigGeneratedClasses.zig,generated/ResolvedSourceTag.zig --main-mod-path /home/natu/bun --subsystem console --listen=-
Build Summary: 1/4 steps succeeded; 1 failed (disable with --summary none)
obj transitive failure
├─ install generated to bun-zig.o transitive failure
│  ├─ zig build-obj bun-zig Debug native-native-gnu.2.27 failure
│  └─ zig build-obj bun-zig Debug native-native-gnu.2.27 (+1 more reused dependencies)
└─ zig build-obj bun-zig Debug native-native-gnu.2.27 (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/home/natu/bun/zig-cache/o/da8ea604f2f9a9e1c93afc81c42bbae9/build /home/natu/zig/zig /home/natu/bun /home/natu/bun/zig-cache /home/natu/.cache/zig --seed 0x6d8c98a5 obj -Doutput-file=/home/natu/bun/build/CMakeFiles/bun-zig.o -Dgenerated-code=/home/natu/bun/build/codegen -Dversion=1.0.8 -Dcanary=false -Doptimize=Debug -Dcpu=haswell -Dtarget=native
[1/302] Bundling JS builtin functions
Bundling Bun builtin functions...
Embedded JS size: 283081 bytes (across 346 functions, 26 files)
[3287.6ms]
FAILED: CMakeFiles/bun-zig.o /home/natu/bun/build/CMakeFiles/bun-zig.o
cd /home/natu/bun && /usr/bin/zig build obj -Doutput-file=/home/natu/bun/build/CMakeFiles/bun-zig.o -Dgenerated-code=/home/natu/bun/build/codegen -Dversion=1.0.8 -Dcanary=false -Doptimize=Debug -Dcpu=haswell -Dtarget=native
ninja: build stopped: subcommand failed.
error: script "setup" exited with code 1 (SIGHUP)

**Comment by varshneydevansh** [comment]
![image](https://github.com/oven-sh/bun/assets/20411128/54f8c56a-8553-47f9-aee7-edc913c9d35e)
I don't know why I am getting this? Maybe I'll try again

**Comment by varshneydevansh** [comment]
![image](https://github.com/oven-sh/bun/assets/20411128/48535302-c9a9-4c62-a548-7e87cd70cbb0)

![image](https://github.com/oven-sh/bun/assets/20411128/33520474-44df-45c6-8b63-149f1b53c61a)

**Comment by jrz** [comment]
Ran into the same thing on debian:bookworm/arm64.
Installing libatomic (```apt install libatomic1```) doesn't help, neither does using -DUSE_STATIC_LIBATOMIC=ON
