### ISSUE TITLE
underlying HTTP server issue when a DELETE request is received

### ISSUE THREAD

**Issue by fernandolguevara** [oven-sh/bun#677]
### Version

0.1.4

### Platform

Darwin nbk.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

execute a DELETE request on bun http server

```js
import { serve } from "bun";

const port = Bun.env.PORT || 3012
serve({
  port,
  async fetch(request) {
    request.headers;
    console.log(request);
    console.log(request["method"]);
    console.log(request.method);
    console.log(request.method.length);
    return Response('OK')
  },
});
```

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

request.method should have DELETE value as string

### What do you see instead?

an empty string 

![image](https://user-images.githubusercontent.com/969516/178743300-0fd82ffd-0a5a-467e-8a5a-f288a73c0549.png)

**Comment by ajimae** [comment]
This is currently an issue, when can we have this fixed or is there anyway we can get around this?

**Comment by lau1944** [comment]
Following...

**Comment by willm** [comment]
Also experiencing this, it makes it very difficult to implement a REST api which has other methods that react to the same path but different methods.

**Comment by willm** [comment]
I don't think this is anything to do with the `serve` function as this is enough to reproduce the issue:

```javascript
import assert from 'assert';
const req = new Request('http://localhost:3000/posts/1', {method: 'DELETE'});
assert.equal(req.method, 'DELETE');
```
Fails with:
`AssertionError: '' == 'DELETE'`

**Comment by willm** [comment]
I'm very new to zig and the codebase, but from looking around I found that `DELETE` is missing from [here](https://github.com/oven-sh/bun/blob/64b20cac8855ed439c8159ef263f2a40f59b3ce4/misctools/fetch.zig#L43). The `TRACE` and `CONNECT` http methods are also missing. I checked the same test as above and they also return empty string - perhaps pointing at the issue.

**Comment by gilbertoalbino** [comment]
@willm LoL
With all due respect, I am only joking here:
"Who ever cares about DELETE method in an API? The most important thing is Bun to be faster than Node and deNo!"

Anyhow, I found it today and got quite frustrated reaching your discovery! 
The guys seemed to do a really cool job on a lot of stuff and just forgot such a fundamental thing!

**Comment by Jarred-Sumner** [comment]
I feel bad it took this long to fix

It was a really small thing
