### ISSUE TITLE
(docs) setup error: 'ruby' is missing

### ISSUE THREAD

**Issue by gamedevsam** [oven-sh/bun#6785]
### What is the type of issue?

Documentation issue.

### What is the issue?

I attempted to follow the contributing guide, but it errors out with this error:

```
samuel@SAMUEL-DESKTOP:~/WSL_Dev/Personal/bun$ bun setup
$ ./scripts/setup.sh
setup error: 'ruby' is missing
error: script "setup" exited with code 1 (SIGHUP)
```

### Where did you find it?

https://bun.sh/docs/project/contributing

**Comment by Hanaasagi** [comment]
Hi, I see that doc has been updated.
- https://github.com/oven-sh/bun/pull/6787
- https://github.com/oven-sh/bun/pull/6788
