### ISSUE TITLE
Error when executing: bun run src/index.ts => Cannot find module "./util.inspect" from "node_modules/object-inspect/index.js"

### ISSUE THREAD

**Issue by IanTheG** [oven-sh/bun#679]
### Version

0.1.4

### Platform

Darwin IanGs-MBP 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create a folder called "server" then
 ~ `cd server`
 ~ `mkdir src`
 ~ `touch src/app.ts`
 ~ `touch src/index.ts`
 ~ `npm init -y`

npm install express and typescript
 ~ `npm install express`
 ~ `npm install --save-dev typescript`

Generate typescript file (when typescript is installed globally)
 ~ `tsc --init`

Install bun with curl command
 ~ `curl https://bun.sh/install | bash`

Exec zsh to initialize bun
 ~ `exec /bin/zsh`

Add bun types to app and tsconfig.json "types" array
 ~ `bun add bun-types`

Reload VSCode window

Code a simple express server in the index.ts and app.ts files that listens on port 3000.

app.ts

```
import express from 'express'  

const app = express()  

export default app
```

index.ts

```
import app from './app'  

const port = 3000  

app.listen(port, () => {  
  console.log("server started at http://localhost:" + port)  
})
```

Run `bun start` where `"start": "bun run src/index.ts"`
or run `bun run src/index.ts` in terminal window

Error appears.

I also uninstalled express and typescript with npm, then reinstalled them using bun. Same error.

### How often does it reproduce? Is there a required condition?

I followed the documentation to set up bun, then followed the README in Github to set up bun for typescript and expected it to work.

The error may be related to the "allowSyntheticDefaultImports": true flag in the tsconfig.json file. 

### What is the expected behavior?

Bun should start the express server without error. 

### What do you see instead?

➜  server git:(main) ✗ bun run src/index.ts

error: Cannot find module "./util.inspect" from "/Users/ian/Git/Backend/server/node_modules/object-inspect/index.js"

OR

➜  server git:(main) ✗ bun start
$ bun run src/index.ts

error: Cannot find module "./util.inspect" from "/Users/ian/Git/Backend/server/node_modules/object-inspect/index.js"
Script error "start" exited with 1 status

### Additional information

package.json

```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "bun run src/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/express": "^4.17.13",
    "bun-types": "^0.1.4",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "express": "^4.18.1"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext"],
    "module": "ESNext",
    "moduleResolution": "node",
    "baseUrl": "./",
    "types": ["bun-types"],
    "sourceMap": true,
    "outDir": "dist",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitAny": true,
    "skipLibCheck": true
  }
}
```

**Comment by xhyrom** [comment]
Express doesn't works with bun, use [hono](https://github.com/honojs/hono) for now

**Comment by FinnRG** [comment]
Fixing ``object-inspect`` is a part of #496.

**Comment by IanTheG** [comment]
Thanks for the quick replies. Hono works great and does most of the things I'd expect Express to do. Too bad bun does not support `node:tls` yet for Redis, but that's a different issue. Consider this closed.
