### ISSUE TITLE
When executing 'sudo bun run dev' on WSL, I encountered a 'Watchpack Error (watcher): Error: AccessDenied' in next.js project.

### ISSUE THREAD

**Issue by everyt** [oven-sh/bun#6793]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Windows10 (Microsoft Windows NT 10.0.19045.0 x64), WSL (Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64)

### What steps can reproduce the bug?

create next app project by bunx with typescript, tailwind.

I initially thought it was a simple permission issue when I ran 'bun run dev' without any privileges.
However, no matter what I tried,
such as 'which -a bun',
'sudo /home/user/.bun/bin/bun run dev',
'sudo chmod a+rwx /home/user/.bun/bin/bun',
'sudo ln -s /home/user/.bun/bin/bun /usr/bin/bun' and
'sudo bun run dev,'
I kept getting the same result.
Even after making changes to the files and refreshing, the changes weren't reflected on the screen.

### What is the expected behavior?

When you modify a file while the browser is running the project, refreshing should reflect the changes made to the file.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/80094147/d086083b-4efa-4e43-8e9c-fb3e254d47a0)

**Comment by lucadibello** [comment]
Same here with Bun 1.0.13 (running inside devcontainer).

<img width="375" alt="Screenshot 2023-11-22 at 22 30 57" src="https://github.com/oven-sh/bun/assets/37295664/f9c51b75-e4ea-4891-a889-d4c79533c90d">


EDIT: Fixed. It was a problem related to user permissions in the Docker devcontainer. Bun was not the underlying issue.

**Comment by easwar16** [comment]
aNY UPDATES?
![image](https://github.com/oven-sh/bun/assets/96469808/1988bef6-6e5f-40f2-99d0-ad14ec82c627)

**Comment by everyt** [comment]
> aNY UPDATES? ![image](https://private-user-images.githubusercontent.com/96469808/303029451-1988bef6-6e5f-40f2-99d0-ad14ec82c627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTk0MTIsIm5iZiI6MTcwNzMxOTExMiwicGF0aCI6Ii85NjQ2OTgwOC8zMDMwMjk0NTEtMTk4OGJlZjYtNmU1Zi00MGYyLTk5ZDAtYWQxNGVjODJjNjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1MTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OWM4NjkwZTZjZWZhY2U3NmFhMGNkOTNkNTcxNDUzNTlkZGM1NGQyMDFlMWQ1MTM2NDgyY2M0NDkyODI1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_FkKukjfkWb0lhX5WNvJtqPvpSxcsDau6UmZQXd8eE)

I'm waiting for an update to Windows.  I heard it comes out in February.

**Comment by easwar16** [comment]
> > aNY UPDATES? ![image](https://private-user-images.githubusercontent.com/96469808/303029451-1988bef6-6e5f-40f2-99d0-ad14ec82c627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTk0MTIsIm5iZiI6MTcwNzMxOTExMiwicGF0aCI6Ii85NjQ2OTgwOC8zMDMwMjk0NTEtMTk4OGJlZjYtNmU1Zi00MGYyLTk5ZDAtYWQxNGVjODJjNjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1MTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OWM4NjkwZTZjZWZhY2U3NmFhMGNkOTNkNTcxNDUzNTlkZGM1NGQyMDFlMWQ1MTM2NDgyY2M0NDkyODI1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M_FkKukjfkWb0lhX5WNvJtqPvpSxcsDau6UmZQXd8eE)
> 
> I'm waiting for an update to Windows. I heard it comes out in February.

That should fix it?

**Comment by albertomtferreira** [comment]
Any update on how to solve the error?
![image](https://github.com/oven-sh/bun/assets/60177437/1c10489a-b4e2-4eaa-ab72-40da4064acfa)

**Comment by ArianHamdi** [comment]
Same here on WSL

**Comment by everyt** [comment]
Just install bun without WSL on windows. That will solve the problem.
