### ISSUE TITLE
Unable to resolve import with "#..."

### ISSUE THREAD

**Issue by olebergen** [oven-sh/bun#680]
### Version

0.1.2

### Platform

Linux arch 5.18.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:06 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

```sh
bun add chalk
echo 'import chalk from "chalk";' > ./index.js
bun index.js
```

### What is the expected behavior?

Able to resolve the import without an error. Node for example is able to do that with `node index.js` (if `"type":"module"` is set in `package.json`).

### What do you see instead?

```sh
$ bun index.js 

error: Could not resolve: "#ansi-styles". Maybe you need to "bun install"?
import ansiStyles from '#ansi-styles';
                       ^
/home/ole/code/bun-import-repro/node_modules/chalk/source/index.js:1:24 23

error: Could not resolve: "#supports-color". Maybe you need to "bun install"?

import supportsColor from '#supports-color';
                          ^
/home/ole/code/bun-import-repro/node_modules/chalk/source/index.js:2:27 65
```

### Additional information

`bun install` from the error message doesn't help either, since the package was properly added

**Comment by olebergen** [comment]
Sorry, seems to be duplicate, didn't see the other issue before

**Comment by vjpr** [comment]
Where is the other issue?

---

Issue: https://github.com/oven-sh/bun/issues/234
Waiting on: https://github.com/oven-sh/bun/issues/478, https://github.com/oven-sh/bun/issues/1402
