### ISSUE TITLE
Problem Arises When Using Bun with Astro and Attempting a POST Request with fetch()

### ISSUE THREAD

**Issue by Hexdigest123** [oven-sh/bun#6807]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Creating an Astro Project with Bun (Enabling TypeScript):
Execute the following command: bun create astro

Next, when you make a fetch("YOUR-PATH") call within a <script> tag in an .astro file, similar to what's shown in the screenshot below:

<img width="280" alt="image" src="https://github.com/oven-sh/bun/assets/77574285/7f196964-4078-482c-b760-351a75ba4db2">

You want to execute the .json() function to obtain to json from the request object, similar to this:
<img width="619" alt="image" src="https://github.com/oven-sh/bun/assets/77574285/a716e392-a58c-4a5d-95f4-c1d19e9393fd">

In development mode (bun astro dev), this will work perfectly. However, when attempting to use Node.js as an SSR (Server-Side Rendering) adapter, you may encounter a warning similar to this:

<img width="820" alt="image" src="https://github.com/oven-sh/bun/assets/77574285/6052b184-a5fd-41c8-ab07-27d694ccb97d">

### What is the expected behavior?

I expected to be able to read the JSON content from the request.

### What do you see instead?

The error message reads "Failed to parse JSON". My guess is that this is an issue with how the project is built in bun.

<img width="820" alt="image" src="https://github.com/oven-sh/bun/assets/77574285/11c7ddbd-d05f-47e3-b860-06cf3bdf6096">

### Additional information

It's important to mention that the error cannot be replicated in the development environment. Additionally, it's worth noting that the project works perfectly fine when built with npm and run with node. So, if you are using Node/npm to test the bug, everything should work as expected.

**Comment by itsbjoern** [comment]
I was able to resolve this by patching Astro myself. Just leaving this here in case it helps with resolving this.

https://github.com/BFriedrichs/astro/commit/9f42bfa08062251a3d20f97f6a08427cb68121ef

As far as I understand the Readable that is the request generated by `node:http` in bun isn't exactly the same as the Readable required to create a new Request object using `new Request({body: request})`.

I was able to resolve this by creating my own ReadableStream but I think it's more of hacky workaround rather than a "fix".

**Comment by Hexdigest123** [comment]
> I was able to resolve this by patching Astro myself. Just leaving this here in case it helps with resolving this.
> 
> [BFriedrichs/astro@9f42bfa](https://github.com/BFriedrichs/astro/commit/9f42bfa08062251a3d20f97f6a08427cb68121ef)
> 
> As far as I understand the Readable that is the request generated by `node:http` in bun isn't exactly the same as the Readable required to create a new Request object using `new Request({body: request})`.
> 
> I was able to resolve this by creating my own ReadableStream but I think it's more of hacky workaround rather than a "fix".

I haven't tested it yet, but if this works, it's a great workaround until Bun provides a general solution. Thanks for the idea!

**Comment by itsbjoern** [comment]
Yes this works, I am currently using this and it seems to be stable (enough).

Just to make this a bit easier for people who may stumble upon this, if you deploy using docker what worked for me is to just place the patched and built `node.js` file (uploaded here https://gist.github.com/BFriedrichs/18903cd68bde039711921d531d31d894#file-node-js) in a `patches` folder.

Then just copy the patch directly into your node_modules before running `bun run build`

```
COPY ./patches/node.js ./node_modules/astro/dist/core/app/node.js
RUN bun run build
```

**Comment by wolfishy** [comment]
I'm using NextJS v13 and I have the same issue, 
it happened while you running the server with flag --bun.
also took me like 2hrs to figure it out, and I found nothing.

and thank god I found this open issue and im waiting to be fix.

**Comment by Hexdigest123** [comment]
> Yes this works, I am currently using this and it seems to be stable (enough).
> 
> Just to make this a bit easier for people who may stumble upon this, if you deploy using docker what worked for me is to just place the patched and built `node.js` file (uploaded here https://gist.github.com/BFriedrichs/18903cd68bde039711921d531d31d894#file-node-js) in a `patches` folder.
> 
> Then just copy the patch directly into your node_modules before running `bun run build`
> 
> ```
> COPY ./patches/node.js ./node_modules/astro/dist/core/app/node.js
> RUN bun run build
> ```

I tested your solution and it works perfectly, but I would appreciate a fix that doesn't require tampering with core files from bun itself.
