### ISSUE TITLE
`bare-server-node` Exits after a request

### ISSUE THREAD

**Issue by illusionTBA** [oven-sh/bun#6810]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.5.6-arch2-1 x86_64 unknown

### What steps can reproduce the bug?

1. clone `https://github.com/tomphttp/bare-server-node/` and run the `basic.js` file in the `examples folder`
2. run the following curl command
```bash
curl "http://localhost:8080/v3/" -H 'x-bare-url: https://www.google.com' -H 'X-Bare-Headers: {"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"}'
```

### What is the expected behavior?

Get back the data of the 'x-bare-url' url. So in this case with `www.google.com` i should get back the html.

### What do you see instead?

returns the following error after the first request
```
{
	"code": "UNKNOWN",
	"id": "error.TypeError",
	"message": "undefined is not an object (evaluating 'header.toLowerCase')",
	"stack": "TypeError: undefined is not an object (evaluating 'header.toLowerCase')\n    at mapHeadersFromArray (/run/media/Fast Boy/bare-server-node/node_modules/@tomphttp/bare-server-node/dist/headerUtil.js:32:18)\n    at <anonymous> (/run/media/Fast Boy/bare-server-node/node_modules/@tomphttp/bare-server-node/dist/V3.js:204:24)\n    at processTicksAndRejections (:61:39)"
}
```

then this one after i follow up with another curl
```
{
	"code": "UNKNOWN",
	"id": "error.ConnectionRefused",
	"message": "Unable to connect. Is the computer able to access the url?"
}
```

**Comment by illusionTBA** [comment]
**Update**
while not making it work, after upgrading to bun 1.0.9 i get a different error on the second request

```
{
	"code": "UNKNOWN",
	"id": "error.UNABLE_TO_GET_ISSUER_CERT",
	"message": "unable to get issuer certificate"
}
```

**Comment by danny-avila** [comment]
> **Update** while not making it work, after upgrading to bun 1.0.9 i get a different error on the second request
> 
> ```
> {
> 	"code": "UNKNOWN",
> 	"id": "error.UNABLE_TO_GET_ISSUER_CERT",
> 	"message": "unable to get issuer certificate"
> }
> ```

Also seeing this as of 1.0.9, still not working as it does on node, like you said.

https://github.com/oven-sh/bun/issues/6520
