### ISSUE TITLE
Cannot bun add exact version of scoped package

### ISSUE THREAD

**Issue by ashsearle** [oven-sh/bun#682]
### Version

0.1.4

### Platform

Darwin myhostname 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Attempting to `bun add` an '@' scoped package with an exact version.

Example:
```
bun add '@types/react@18.0.15'
```

### How often does it reproduce? Is there a required condition?

Seems to occur for all '@' scoped packages with a second '@' specifying version number

### What is the expected behavior?

The specified package@version should be installed.  i.e. similar output to:

```
bun add '@types/react'
bun add v0.1.4

 installed @types/react@18.0.15

 4 packages installed [14.00ms]
```

### What do you see instead?

Error output indicating the HTTP request to fetch the package from the registry is invalid:
```
bun add --verbose '@types/react@18.0.15'
bun add v0.1.4
  🔍 Resolving [1/1] GET /types/react@
	Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
	Connection: close
	User-Agent: bun.js 0.1.4
	Host: registry.npmjs.org
	Accept-Encoding: deflate, gzip

Response: < 405 Method Not Allowed
< 	Date: Wed, 13 Jul 2022 16:27:03 GMT
< 	Content-Type: text/plain
< 	Content-Length: 18
< 	Connection: close
< 	CF-Ray: 72a36240ec5a54dc-MAN
< 	Allow: PUT
< 	CF-Cache-Status: DYNAMIC
< 	Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< 	Vary: Accept-Encoding
< 	Server: cloudflare

  🔍 types/react@ [1/1]
GET https://registry.npmjs.org//types/react@ - 405
Loaded 8 hoisted_packages
Loaded 8 resolutions
Loaded 8 dependencies
Loaded 0 extern_strings
Loaded 95 string_bytes
Enqueue package manifest for download: types/react@
```

**Comment by paperclover** [comment]
this also happens when adding something with a tag. theres bad parsing with the @ is all
