### ISSUE TITLE
respect Windows "Hidden" file attribute before it is too late.

### ISSUE THREAD

**Issue by adufswdanq** [oven-sh/bun#6820]
### What is the problem this feature would solve?

bun on windows uses libuv for I/O operations and libuv itself doesn't respect Windows "Hidden" file at the moment.

libuv (https://github.com/libuv/libuv/pull/3380).

nodejs (https://github.com/nodejs/node/issues/41093).

I would like bun to take it into consideration before it is too late.

### What is the feature you are proposing to solve the problem?

respect Windows "Hidden" file attribute.

**Comment by paperclover** [comment]
Thanks for bringing this to my attention. This seems to work fine on my fs code without extra modifications.

I'm gonna add a new test case so that this behavior doesn't break.

**Comment by paperclover** [comment]
re-opening because it no longer "just works"
