### ISSUE TITLE
fs.readSync not compatible with node

### ISSUE THREAD

**Issue by maple3142** [oven-sh/bun#6832]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Linux 6.1.21.2-microsoft-standard-WSL2-maple x86_64 unknown

### What steps can reproduce the bug?

Compare

```shell
printf a | node -e 'let buf = Buffer.alloc(1); fs.readSync(0, buf, 0, 1); console.log(buf)'
// <Buffer 61>
```

and

```shell
printf a | bun repl --eval 'let buf = Buffer.alloc(1); fs.readSync(0, buf, 0, 1); console.log(buf)'
// TypeError: length and position are required
// code: "ERR_INVALID_ARG_TYPE"
```

### What is the expected behavior?

`fs.readSync(0, buf, 0, 1)` should work as `position` is optional: https://nodejs.org/api/fs.html#fsreadsyncfd-buffer-offset-length-position

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/9370547/1daee525-5e38-493f-8d69-5ffc0445fe22)

**Comment by MustkimKhatik** [comment]
Hey! I would like to work on it.

**Comment by gvilums** [comment]
Works in bun 1.1.7
