### ISSUE TITLE
Failed installs should produce an exit code other than 0

### ISSUE THREAD

**Issue by fregante** [oven-sh/bun#6836]
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

This seems related to installing from a npm lockfile:

1. Check out https://github.com/pixiebrix/pixiebrix-extension (or just its package.json and package-lock)
2. Run `bun install && echo 'all good'`

### What is the expected behavior?

`bun install` should exit unsuccessfully if it fails. `echo` should not be run

### What do you see instead?

Notice how the entire installation fails with `FileNotFound installing *everything*` but `echo` is still run

**Comment by IgorKrupenja** [comment]
Could be related to https://github.com/oven-sh/bun/issues/4200 ?

**Comment by fregante** [comment]
Yes. Closing
