### ISSUE TITLE
I'm having trouble using bun and nuxt3.

### ISSUE THREAD

**Issue by k3341095** [oven-sh/bun#6838]
### What version of Bun is running?

1.0.8+53d1acb0a5655deb69f54bd6f8222a6f4dd27633

### What platform is your computer?

ubuntu 22.04

### What steps can reproduce the bug?

bunx nuxi init bun-first

bun --bun run dev
error: script "dev" exited with code 11 (SIGSEGV)

I often get an error when I run it. Occasionally runs without errors. The code is 4 11 random.

On the rare occasions that it works, the 
https://github.com/hatoo/oha

With a benchmark tool called OHA 
oha -n 2000 -c 1000 http://localhost:3000

and the site just dies. 
It doesn't throw any errors towards nuxt, it just won't connect.

If I make it work with nodejs like bun run dev, it works fine.
It's only when i do it with bun --bun run dev that i have problems.

I don't have 1.06, so I tried with canary build, same issue.

### What is the expected behavior?

Web page freezes

### What do you see instead?

No errors, nothing

**Comment by dennisDappgenie** [comment]
got same error on nuxt3 with bun 1.0.11

**Comment by angelhdzmultimedia** [comment]
Apparently fixed in latest version. More updates here here: https://github.com/oven-sh/bun/issues/4743#issuecomment-1817794912

**Comment by 4F2E4A2E** [comment]
+1 using docker image `oven/bun:1.0.35-slim`

```bash
$ bun --bun x nuxi-edge@latest build 
Nuxt 3.11.1 with Nitro 2.9.5
[nuxt:tailwindcss] ℹ Using default Tailwind CSS file
ℹ Building client...
ℹ vite v5.2.7 building for production...
ℹ transforming...
Segmentation fault
```

```bash
$ bunx --bun nuxi info
Working directory: /app
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v21.6.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  bun@1.0.35
- Builder:          -
- User Config:      ssr, srcDir, modules, css, build, runtimeConfig, colorMode, devtools, typescript
- Runtime Modules:  @nuxt/ui@2.15.0
- Build Modules:    -
------------------------------
```

```bash
$ bun run build # nuxt build
Nuxt 3.11.1 with Nitro 2.9.5
[nuxt:tailwindcss] ℹ Using default Tailwind CSS file
ℹ Building client...
ℹ vite v5.2.7 building for production...
ℹ transforming...
error: script "build" was terminated by signal SIGSEGV (Address boundary error)
Segmentation fault
```

**Comment by Jarred-Sumner** [comment]
I think this was fixed in https://github.com/oven-sh/bun/pull/11635 and https://github.com/oven-sh/bun/pull/11494.

If you're still running into this issue in Bun v1.1.13 or later, please let us know and I'll re-open the issue.
