### ISSUE TITLE
Deeply nested objects fail to show proper diff after a test fails.

### ISSUE THREAD

**Issue by PedroGaya** [oven-sh/bun#6839]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.5.7-100.fc37.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

1. run: `bun init`
2. create some test
3. compare any two different deeply nested properties of objects with toEqual()
4. run `bun test`, test fails and diff will show no difference between the objects.

Alternatively, [here's a repo](https://github.com/PedroGaya/bun-deeply-nested-bug) with an example and instructions.

### What is the expected behavior?

The diff should display the difference between the deeply nested properties.

### What do you see instead?

No difference between the objects displayed in the diff.

**Comment by Electroid** [comment]
Duplicate of #6519
