### ISSUE TITLE
`bun test` reads env variables from `.env` and not `.env.test` when run from npm script

### ISSUE THREAD

**Issue by IgorKrupenja** [oven-sh/bun#6840]
### What version of Bun is running?

1.0.8+53d1acb0a5655deb69f54bd6f8222a6f4dd27633

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bun init`.
2. Create `.env` file with a variable, like `FOO="bar"`.
3. Create `.env.test` file with the same variable name but different value, e.g. `FOO="test"`.
4. Create an npm script to run `bun test`, like `"test:foo": "NODE_ENV=test bun test"`.
5. Create a test that reads the env variable with `Bun.env.FOO`.
6. Run `bun test:foo`.

Sample repo: https://github.com/IgorKrupenja/bun-test-env-repro

### What is the expected behavior?

Environment variable value is read from `.env.test` file.

### What do you see instead?

Environment variable is read from `.env` file.

### Additional information

- No problem if running `bun test` directly.

**Comment by JeffreyATW** [comment]
Might be a dupe of https://github.com/oven-sh/bun/issues/6334.

**Comment by IgorKrupenja** [comment]
Yeah, let's close it in favour of https://github.com/oven-sh/bun/issues/6334.

Thank you!
