### ISSUE TITLE
SQLite: RETURNING keyword causes syntax error.

### ISSUE THREAD

**Issue by JamesAlexanderHill** [oven-sh/bun#6846]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

Run the following code and it will cause a SYNTAX error

```
import { Database } from "bun:sqlite";

const db = new Database("database.sqlite");

const CREATE_USERS_TABLE = db.prepare(
  `CREATE TABLE IF NOT EXISTS USERS (
	  id TEXT PRIMARY KEY,
	  email TEXT NOT NULL UNIQUE,
	  firstName TEXT,
	  lastName TEXT
  );`,
);
CREATE_USERS_TABLE.run();

const query = db.query(
  `INSERT INTO USERS (id, email, firstName, lastName) VALUES ($id, $email, $firstName, $lastName) RETURNING *;`,
);
const addedUser = query.get({
  $id: "example_id",
  $email: "example_email@gmail.com",
  $firstName: "exam",
  $lastName: "ple",
});
console.log(addedUser);
```

### What is the expected behavior?

- `query.get(...)` returns `{id: 'example_id', email: 'example_email@gmail.com', firstName: 'exam', lastName: 'ple'}`
- `query.all(...)` returns `[{id: 'example_id', email: 'example_email@gmail.com', firstName: 'exam', lastName: 'ple'}]`
- `query.values(...)` returns `[['example_id', 'example_email@gmail.com', 'exam', 'ple']]`
- `query.run(...)` returns `undefined`

### What do you see instead?

```
error: near "RETURNING": syntax error
      at prepare (bun:sqlite:193:18)
      at query (bun:sqlite:200:14)
```

### Additional information

- SQLites version in bun is `3.38.5.` according to: https://github.com/oven-sh/bun/issues/2250
- Buns version of SQLite should support returing keyword as it was added in SQLite version 3.35.0
- There are references to it working previously in this discord thread: https://discord.com/channels/876711213126520882/1154499935060897843

**Comment by Jarred-Sumner** [comment]
Bun does not parse SQLite syntax itself. On macOS, Bun uses the system-installed version of SQLite. Judging by the kernel version, you appear to be running roughly macOS 11.6, which comes from ~April 2021? This likely predates SQLite 3.35.0

I suggest upgrading to the latest version of macOS
