### ISSUE TITLE
segmentation fault with @xenova/transformers

### ISSUE THREAD

**Issue by mnpenner** [oven-sh/bun#6848]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

Create `main.mjs`:

```js
import { pipeline } from '@xenova/transformers';

// Allocate a pipeline for sentiment-analysis
let pipe = await pipeline('sentiment-analysis');

let out = await pipe('I love transformers!');

console.log(out)
```

And `package.json`:

```
{
    "dependencies": {
        "@xenova/transformers": "^2.7.0"
    },
    "trustedDependencies": ["sharp"]
}
```

`bun install` to install the dep, and then `bun main.mjs` to run it. Output should be

```txt
❯ bun main.mjs
No model specified. Using default model: "Xenova/distilbert-base-uncased-finetuned-sst-2-english".
zsh: segmentation fault (core dumped)  bun main.mjs
```

### What is the expected behavior?

Runs without crashing.

### What do you see instead?

Segfault

### Additional information

This is the example from here: https://github.com/xenova/transformers.js#quick-tour

**Comment by johnhorsema** [comment]
Duplicate of #4619.

**Comment by mnpenner** [comment]
I'll close this one in favor of the other ticket. Still happening in `1.0.16+800fb1290`
