### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by ajimae** [oven-sh/bun#685]
### Version

0.1.2

### Platform

Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

### Steps to reproduce issue

- run `bun add uuid` in the terminal to add new uuid package.
- create a file `index.ts and import { v4 as uuidv4 } from "uuid"`
- invoke uuidv4 after the import statement and assign to a variable `const uuid = uuidv4()`
- console.log(uuid)

### How often does it reproduce? Is there a required condition?

Every single time I try to run `bun index.ts`1 | 

### What is the expected behavior?

The console should output a valid uuid e.g: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'

### What do you see instead?

```ts
1 | 
2 | var { default: REGEX} = require($36c46a9b);
   ^
 ReferenceError: Can't find variable: require
      at /x/bun/node_modules/uuid/dist/esm-browser/validate.js:1:0
      at /x/bun/node_modules/uuid/dist/esm-browser/index.js:1:0
```

### Additional information

From an answer I saw, about cheerio [here](https://github.com/oven-sh/bun/issues/674)

I tried using the require method like this:

```ts
const { v4 as uuidv4 } = require("uuid");
```

But still got same issue

```ts
1 | 
2 | var { default: REGEX} = require($36c46a9b);
   ^
 ReferenceError: Can't find variable: require
      at /x/bun/node_modules/uuid/dist/esm-browser/validate.js:1:0
      at /x/bun/node_modules/uuid/dist/esm-browser/index.js:1:0
```

**Comment by Kapsonfire** [comment]
@Jarred-Sumner 
bun detects the correct "module" path from `package.json` but doesnt handle it as module but as commonjs

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/f7e9b91701d60f1f1a319acf799871c20aee007a
