### ISSUE TITLE
Bun socket return response cannot be processed by the mobile device

### ISSUE THREAD

**Issue by faxlok** [oven-sh/bun#6855]
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

```js
Bun.listen({
  hostname: "0.0.0.0",
  port: 3000,
  socket: {
    async data(socket, data) {
      const test = "This is a text over 130kb, omitted here.Full English."
      socket.write(`HTTP/1.1 200 OK\r\nContent-Length:${test.length}\r\n\r\n`);
      socket.write(test)
    }
  }
})
```

### What is the expected behavior?

Mobile devices respond correctly

### What do you see instead?

stuck, No response, Waiting indefinitely

### Additional information

When the socket returns a response to the mobile device, if the size of the returned data exceeds about 130kb, it will be stuck. But this won't happen on PC.

I tried using chrome and safari, but still can't get a response

**Comment by Electroid** [comment]
You might have a hidden newline in that code block. When I try running the code as-is, I get this from `curl`:

```
< HTTP/1.1 200 
* Header without colon
* Closing connection 0
curl: (8) Header without colon
```

But when I fix the code to not have the hidden newline between the "200" and "OK", it works fine:

```
< HTTP/1.1 200 OK
< Content-Length:53
< 
* Connection #0 to host localhost left intact
This is a text over 130kb, omitted here.Full English.                          
```

**Comment by faxlok** [comment]
I guess there should be no hidden newlines.

I changed the code a different way and it still doesn't respond on my mobile device. But there is no problem with the PC.
`
Bun.listen({
  hostname: "0.0.0.0",
  port: 3000,
  socket: {
    data(socket, data) {
      const test = "ddddddddddddddddd".repeat(100).repeat(100)
      console.log(test.length)
      // or
      // socket.write(`HTTP/1.1 200 OK\nContent-Length:${test.length}\n\n`);
      socket.write(`HTTP/1.1 200 OK\r\nContent-Length:${test.length}\r\n\r\n`);
      socket.write(test)
    }
  }
})
`

By the way, when I use the code below, it works fine on mobile and pc
`
Bun.serve({
  port: 3000,
  async fetch(req) {
    const test = "ddddddddddddddddd".repeat(100).repeat(100)
    return new Response(test, {
      headers: {
        "Content-Type": "text/plain"
      }
    });
  },
});
`

**Comment by faxlok** [comment]
I guess there should be no hidden newlines.

I changed the code a different way and it still doesn't respond on my mobile device. But there is no problem with the PC.
```
Bun.listen({
  hostname: "0.0.0.0",
  port: 3000,
  socket: {
    data(socket, data) {
      const test = "ddddddddddddddddd".repeat(100).repeat(100)
      console.log(test.length)
      // or
      // socket.write(`HTTP/1.1 200 OK\nContent-Length:${test.length}\n\n`);
      socket.write(`HTTP/1.1 200 OK\r\nContent-Length:${test.length}\r\n\r\n`);
      socket.write(test)
    }
  }
})
```

By the way, when I use the code below, it works fine on mobile and pc
```
Bun.serve({
  port: 3000,
  async fetch(req) {
    const test = "ddddddddddddddddd".repeat(100).repeat(100)
    return new Response(test, {
      headers: {
        "Content-Type": "text/plain"
      }
    });
  },
});
```
