### ISSUE TITLE
Illegal instruction (core dumped) with last version

### ISSUE THREAD

**Issue by iezed** [oven-sh/bun#6869]
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?
Pop!_OS 22.04 LTS
Unix 6.5.6.76060506 x64

### What steps can reproduce the bug?

bun upgrade and bun install

### What do you see instead?

Illegal instruction (core dumped)

**Comment by m4rcelpl** [comment]
I can’t build a Docker image because of this on current slim or 1.0.8-slim tag :(
<img width="953" alt="Zrzut ekranu 2023-11-3 o 12 03 06" src="https://github.com/oven-sh/bun/assets/13198386/e347b4fa-cebb-44f5-95e9-b8494d3fc397">

**Comment by pro-sumer** [comment]
Same on my Raspberry Pi's:

```
➜ bun update --no-save
zsh: illegal hardware instruction  bun update --no-save
```

Architecture:
`Linux pi-sm 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64`

**Comment by woxxo** [comment]
Same problem with Bun 1.0.8 on Ubuntu 22.04, kernel 6.2.0:
"Illegal instruction (core dumped)"

Bun 1.0.7 is working well.

**Comment by mcornaglia** [comment]
In case it can help, I've experienced the same issue within the latest update. I'm using Debian (I've tried Ubuntu as well) in WSL. That's the error I'm getting:
![image](https://github.com/oven-sh/bun/assets/25534931/9863bec8-6274-4990-be53-11623e7ff5fe)
I agree with @snoopoor, downgrading to 1.0.7 works properly.

**Comment by Electroid** [comment]
We're working on a fix for this.

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.0.9. Please upgrade `curl https://bun.sh/install | bash -s`

If you continue to run into this, leave a comment

**Comment by feri-irawan** [comment]
Awesome! @Jarred-Sumner

**Comment by pro-sumer** [comment]
Fix confirmed. Thank you!

**Comment by keisanng** [comment]
Experiencing this issue using version 1.2.13 on NixOS.
