### ISSUE TITLE
bug: `process` referenced via `import` returns empty `argv`

### ISSUE THREAD

**Issue by antongolub** [oven-sh/bun#687]
### Version

0.1.4

### Platform

darwin arm64

### What steps will reproduce the bug?

```bash
echo "import * as process from 'process'\nconsole.log(process.argv)" > argv-fail.ts
echo "console.log(process.argv)" > argv-ok.ts
```
then
```bash
bun argv-ok.ts
bun argv-fail.ts
```

### How often does it reproduce? Is there a required condition?

each time

### What is the expected behavior?

```bash
bun argv-ok.ts  
[ "bun", "argv-ok.ts" ]

bun argv-fail.ts
[ "bun", "argv-fail.ts" ]
```

### What do you see instead?

```bash
bun argv-ok.ts  
[ "bun", "argv-ok.ts" ]
 
bun argv-fail.ts
[]
```

**Comment by Jarred-Sumner** [comment]
currently, they're completely separate objects and this is silly

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v0.1.10

**Comment by hiarthurbr** [comment]
I think this problem should be reopened, as on 0.2.0 this problem reappeared (at least for me)

my steps for reproducing:
```
$ cat index.ts
console.log(process.cwd());
console.log(process.argv);
```
```
$ bun index.ts
/mnt/d/argon
[]
```
```
$ bun index.ts foo
/mnt/d/argon
[ "bun", "/mnt/d/argon/index.ts", "foo" ]
```
```
$ bun -v
0.2.0
```

**Comment by Jarred-Sumner** [comment]
That’s a different bug, specific to no args other than bun and the script name. It is fixed in canary 

`bun upgrade —canary`
