### ISSUE TITLE
Bun 'NaNms' Displayed Instead of 'Ready in (time)ms' when Running Next.js App

### ISSUE THREAD

**Issue by devabdultech** [oven-sh/bun#6886]
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I am currently testing Bun with a Next.js app in my WSL Ubuntu environment. To create and run the app, I used the command `bun create next-app` followed by `bun --bun run dev`. However, when the development server starts, the console output displays **"Ready in NaNms"** instead of the expected **"Ready in (time)ms"** message. This behavior differs from running the app with just Node.js, where it correctly displays the time taken for the app to become ready

### What is the expected behavior?

When starting the development server using `bun --bun run dev`, the console output should display **"Ready in (time)ms"** to indicate the time taken for the server to become ready for serving the Next.js app, just like it does when running the app with `bun run dev` (NodeJs).

### What do you see instead?

The console output displays **Ready in "NaNms"** when running the app with `bun --bun run dev`,

**Comment by Electroid** [comment]
Related: #6537, #6542

**Comment by RiskyMH** [comment]
There has been lots of improvements to next.js past last year and I can't seem to reproduce this error. As such I will close this, but @devabdultech if this still occurs to you let me know and I can open again.
