### ISSUE TITLE
* cannot be parsed as URL

### ISSUE THREAD

**Issue by 7heMech** [oven-sh/bun#6892]
On the replit platform I've gotten this issue with a number of different libraries like `bunrest` and `discord.js` I think the issue is that the reverse proxy sends an options request where the url shows up as "*" in bun
![Screenshot](https://github.com/oven-sh/bun/assets/83923848/85a2b70c-de56-4405-9bf3-4c1763d4f475)

```
415 | }
416 | class IncomingMessage extends Readable {
417 |   method;
418 |   complete;
419 | 
420 |   constructor(req, defaultIncomingOpts) {

TypeError: "*" cannot be parsed as a URL.
      at new IncomingMessage (node:http:420:26)
      at fetch (node:http:383:26)
OPTIONS - * failed
```

**Comment by Jarred-Sumner** [comment]
The bug is that node:http's `IncomingMessage` class is using `new Request` which is validating URLs which is incorrect for node:http's `IncomingMessage` because the string it passes may not be a valid URL.

**Comment by Jarred-Sumner** [comment]
that's strange too though

**Comment by 7heMech** [comment]
Yeah, thanks for the quick response, isn't Request supposed to be able to be used just like in node in bun?

**Comment by noway** [comment]
The bug is still present in bun 1.0.8. The line numbers are slightly different from @7heMech's post, but the stack track is the same:

```
409 | }
410 | class IncomingMessage extends Readable {
411 |   method;
412 |   complete;
413 |
414 |   constructor(req, defaultIncomingOpts) {
                             ^
TypeError: "/" cannot be parsed as a URL.
      at new IncomingMessage (node:http:414:26)
      at fetch (node:http:377:26)
GET - / failed
```
