### ISSUE TITLE
postgress client not working 

### ISSUE THREAD

**Issue by piyusharorawork** [oven-sh/bun#6896]
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

``` js
import { Client } from "pg";

(async () => {
  const client = new Client({
    connectionString:
      "postgresql://piyushiiii:piyush123@localhost:5432/postgres",
  });
  await client.connect();
  console.log("connected");

  await client.end();
  console.log("disconnected");
})();

```

### What is the expected behavior?

it should print connected and then disconnected 

### What do you see instead?

It just prints connected and exits the program

**Comment by Electroid** [comment]
Could you try running `bun upgrade`, then trying again?

**Comment by piyusharorawork** [comment]
@Electroid  thanks  so it is working now when i upgraded to 1.0.8
