### ISSUE TITLE
Missing word (or phrase) about environment Quotation Marks

### ISSUE THREAD

**Issue by jimt** [oven-sh/bun#6906]
### What is the type of issue?

Documentation is missing, Documentation is confusing

### What is the issue?

The section on quotation marks reads:

`Bun supports double quotes, single quotes, and`

suggesting there is a missing third thing.

### Where did you find it?

https://github.com/oven-sh/bun/blob/main/docs/runtime/env.md#quotation-marks

**Comment by ghost** [comment]
Does anyone know if the third phrase is supposed be template literal backticks?

**Comment by ghost** [comment]
> Does anyone know if the third phrase is supposed by template literal backticks?

After testing, I found that Bun does indeed support template literal backticks for environment variables, so I'm assuming that's what this is referring to, as there aren't any other types of quotes (at least that I know of).
