### ISSUE TITLE
[Windows Canary] Panic: TODO: Windows makePath

### ISSUE THREAD

**Issue by SWATOPLUS** [oven-sh/bun#6910]
### What version of Bun is running?

Bun v1.0.9-canary.11 (98f20170) Windows x64

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

On windows run
```bun x cowsay hello```

### What is the expected behavior?

I see cow

### What do you see instead?

d:\soft\bun>bun x cowsay hello
error parsing lockfile: Lockfile is missing data
ignoring lockfile
get-stdin [6/10] error: InvalidArgument extracting tarball for get-stdinis-fullwidth-code-point [19/39] error: InvalidArgument extracting tarball for cowsaycliui [22/41] error: InvalidArgument extracting tarball for is-fullwidth-code-pointcliui [22/41] error: InvalidArgument extracting tarball for strip-final-newlinecliui [26/44] error: InvalidArgument extracting tarball for cliuistrip-ansi [30/48] error: InvalidArgument extracting tarball for strip-ansistrip-ansi [34/52] error: InvalidArgument extracting tarball for strip-ansiwrap-ansi [36/53] error: InvalidArgument extracting tarball for wrap-ansiansi-regex [38/54] error: InvalidArgument extracting tarball for ansi-regexansi-regex [40/55] error: InvalidArgument extracting tarball for ansi-regexstring-width [46/61] error: InvalidArgument extracting tarball for string-widthset-blocking [53/67] error: InvalidArgument extracting tarball for is-fullwidth-code-pointansi-styles [61/74] error: InvalidArgument extracting tarball for ansi-stylesansi-styles [61/74] error: InvalidArgument extracting tarball for decamelizerequire-directory [64/75] error: InvalidArgument extracting tarball for require-directoryy18n [66/76] error: InvalidArgument extracting tarball for y18nset-blocking [70/80] error: InvalidArgument extracting tarball for set-blockingget-caller-file [72/81] error: InvalidArgument extracting tarball for get-caller-fileemoji-regex [74/82] error: InvalidArgument extracting tarball for emoji-regexcolor-convert [76/83] error: InvalidArgument extracting tarball for color-convertyargs [82/88] error: InvalidArgument extracting tarball for yargsstring-width [86/93] error: InvalidArgument extracting tarball for string-widthcolor-name [92/99] error: InvalidArgument extracting tarball for color-namefind-up [96/102] error: InvalidArgument extracting tarball for find-uprequire-main-filename [98/103] error: InvalidArgument extracting tarball for require-main-filenamewhich-module [104/109] error: InvalidArgument extracting tarball for which-moduleyargs-parser [106/110] error: InvalidArgument extracting tarball for yargs-parserpath-exists [108/111] error: InvalidArgument extracting tarball for path-existslocate-path [112/115] error: InvalidArgument extracting tarball for locate-pathcamelcase [114/116] error: InvalidArgument extracting tarball for camelcasep-locate [116/117] error: InvalidArgument extracting tarball for p-locatep-limit [120/121] error: InvalidArgument extracting tarball for p-limitp-try [124/124] error: InvalidArgument extracting tarball for p-try
_**Panic: TODO: Windows makePath**_

bun has crashed :'(

----- bun meta -----
Bun v1.0.9-canary.11 (98f20170) Windows x64
AddCommand:
Elapsed: 643ms | User: 453ms | Sys: 218ms
RSS: 70.06MB | Peak: 70.53MB | Commit: 0.22GB | Faults: 18137
----- bun meta -----

0   00007FF65F9C6228
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

_**thread 21448 panic: TODO: Windows makePath**_
???:?:?: 0x7ff65e9a76e6 in ??? (???)
???:?:?: 0x7ff65e9bb2d5 in ??? (???)
???:?:?: 0x7ff65e9e95d7 in ??? (???)
???:?:?: 0x7ff65ea46ffb in ??? (???)
???:?:?: 0x7ff65e7e1353 in ??? (???)
???:?:?: 0x7ff6608b562f in ??? (???)
???:?:?: 0x7ffee6bc257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffee820aa77 in ??? (ntdll.dll)

### Additional information

Some api not implemented on windows:
https://github.com/oven-sh/bun/blob/98f20170a3d24daaedbd5c779d7a31a1aefd109a/src/bun.zig#L1963

**Comment by Electroid** [comment]
Thanks for reporting, we will be fixing this soon.

**Comment by paperclover** [comment]
bun install/bunx isnt supported, will track this workign in #7155
