### ISSUE TITLE
An error occurred while using the bun:ffi module: Segmentation fault

### ISSUE THREAD

**Issue by CsVeryLoveXieWenLi** [oven-sh/bun#6914]
### What version of Bun is running?

1.0.9+98f20170a

### What platform is your computer?

Linux sysdebian 5.10.0-25-amd64 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

### What steps can reproduce the bug?

**我不会说英文，抱歉，以下双语都是机器翻译。**
**I don't speak English, sorry, the following bilinguals are machine translations.** 

**只要我使用bun:ffi模块就会提示错误，“Segmentation fault”。**
**As long as I use the bun:ffi module, it will prompt an error, "Segmentation fault".**

**同一份代码很少会出现，没问题正常运行，正常出现预期结果的这种情况。**
**The same code rarely appears, runs normally without any problems, and produces expected results.**

**要复现这个BUG，请下载我的代码包，包含的C++源代码、Cmake源代码、BunJs源代码、测试用的两张图片、编译好的共享库。**
**To reproduce this BUG, please download my code package, which contains C++ source code, Cmake source code, BunJs source code, two pictures for testing, and compiled shared libraries.**

**直接运行main2.js即可，这是打包过的Js，注意版本和系统是否一致或者相近？**
**Just run main2.js directly. This is the packaged Js. Pay attention to whether the version is consistent or similar to the system?**

[代码包/code package](https://github.com/CsVeryLoveXieWenLi/GalGameNote/releases/download/file/debug.zip)

### What is the expected behavior?

**这是一个使用C++库opencv编写的共享库，作用是用来识别滑块的缺口，正常应该输出坐标X所在的数字。**
**This is a shared library written using the C++ library opencv. It is used to identify the gap of the slider. Normally, the number where the coordinate X is located should be output.**

**通过调用bun:ffi模块，实现bun.js层面的调用。**
**By calling the bun:ffi module, bun.js level calls are implemented.**

### What do you see instead?

**仅有错误，“Segmentation fault”。**
**There is only an error, "Segmentation fault".**

**要么就正常运行，输出一个数字，不会报错。**
**Either run normally and output a number without reporting an error.**

![image](https://github.com/oven-sh/bun/assets/102389677/feb5b6e7-bdcf-4ea8-bd40-d2b52f6c353c)

### Additional information

**经过我的观察的调试，我发现，貌似是bun:ffi模块的ptr函数，转换指针出现了错误，返回无效指针，导致越界。**
**After my observation and debugging, I found that it seems that the ptr function of the bun:ffi module has an error in converting the pointer and returns an invalid pointer, resulting in out-of-bounds.**

**你可以这样来测试我说的指针无效问题，查看返回的数据长度，或者内容，以此判断。**
**You can test the invalid pointer problem I mentioned in this way, and check the length or content of the returned data to judge.**

```js
console.log(toArrayBuffer(ptr(src)));
```

**Comment by CsVeryLoveXieWenLi** [comment]
**如果我没回复就是在睡觉，抱歉。调试了几天了，自己解决不了就只能发出来了。**
**I'm sleeping if I don't reply, sorry. I've been debugging it for a few days, and if I can't solve it myself, I have no choice but to send it out.**

**Comment by Electroid** [comment]
Hi there, why did you close this issue? If there was a crash, we want to fix it.

**Comment by CsVeryLoveXieWenLi** [comment]
**抱歉，我可能有点武断，因为我发现了真正的问题所在，开了一个新的issues。**
**Sorry, I may be a bit arbitrary, because I found the real problem and opened new issues.**

**Comment by CsVeryLoveXieWenLi** [comment]
**在这里.**
**it's here.**

#6933
