### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by Yash-661** [oven-sh/bun#6917]
### What is the problem this feature would solve?

Type Script
it good to add type checking as a feature in bun. 
I know that bun fully focused on performance, but it would be better to have type checking in typescript (which is developed for type specific). 
At least add type checking feature as flag that can be turned on and off by the user if needed.

### What is the feature you are proposing to solve the problem?

Type Script
it good to add type checking as a feature in bun. 
I know that bun fully focused on performance, but it would be better to have type checking in typescript (which is developed for type specific). 
At least add type checking feature as flag that can be turned on and off by the user if needed.

**Comment by Electroid** [comment]
We don't have plans right now to re-implement TypeScript. The surface area would be massive and it would distract us from all the other ways we can make JavaScript and TypeScript better. For now, continue to use `tsc`.

**Comment by gmr458** [comment]
@Electroid Is there any possibility of adding a flag to enable type checking by TSC like [Deno does](https://docs.deno.com/runtime/getting_started/command_line_interface/#type-checking-flags)?

![20240922_16h16m53s_grim](https://github.com/user-attachments/assets/4763d758-146a-4c30-9770-6545166590b1)

**Comment by kravetsone** [comment]
> @Electroid Is there any possibility of adding a flag to enable type checking by TSC like [Deno does](https://docs.deno.com/runtime/getting_started/command_line_interface/#type-checking-flags)?
> 
> ![20240922_16h16m53s_grim](https://github.com/user-attachments/assets/4763d758-146a-4c30-9770-6545166590b1)
> 

Deno reimplement TypeScript and LSP
And it really painful

**Comment by Yash-661** [comment]
If someone can do, we can also do

One simple idea I have to add `flag or sub-command as check` when this
runs, implement tsc name.ts internally and pipe that error to main console
where this, "bun check app.ts" runs
