### ISSUE TITLE
SSL fails with "illegal parameter" after bun ran for some time with Node's "https" module

### ISSUE THREAD

**Issue by noway** [oven-sh/bun#6922]
### What version of Bun is running?

1.0.8, also happens in 1.0.9

### What platform is your computer?

Linux 6.2.0-1013-aws aarch64 aarch64

### What steps can reproduce the bug?

1. 
```typescript
import https from "https";
import express from "express";
import fs from "fs";

const app = express();
app.get("/", async (req, res) => {
  res.contentType("text").send("OK");
});

https
  .createServer(
    {
      key: fs.readFileSync("./key.pem"),
      cert: fs.readFileSync("./cert.pem"),
    },
    app
  )
  .listen(443);
```

2. Run the server for some time (for me happens within 24 hours)

### What is the expected behavior?

"OK" to be displayed in browser/curl

### What do you see instead?

- `curl -v https://a-domain-name-with-letsecnrypt-on-it.com/` suddenly fails with "illegal parameter" SSL error
- Google Chrome will fail with `ERR_SSL_PROTOCOL_ERROR` error

### Additional information

After a few minutes (usually around 5), bun exits on its own. There's no evidence of OOM happening in `dmesg`. Not sure what the exit code is unfortunately.

So it seems like the internal state/the way bun does SSL gets corrupted somehow after `https.createServer(` been running for a few hours.

This bug report is probably very annoying... I'm not sure how I'd go about debugging this. But this bug has not been present in `1.0.7`. 

I will update this issue as I learn more.

**Comment by Jarred-Sumner** [comment]
@cirospaciari do you have any ideas?

**Comment by Jarred-Sumner** [comment]
@noway are you able to reproduce this on Linux x64 or only Linux arm64?

**Comment by noway** [comment]
@Jarred-Sumner I only use bun on arm64 so I don't know if the bug is present on x64.

It may take me some time to spin up an Intel machine... Hopefully I'll get a chance soon and update you!

**Comment by Jarred-Sumner** [comment]
Very likely fixed in the canary build of Bun. Please run `bun upgrade --canary`

**Comment by noway** [comment]
@Jarred-Sumner just upgraded to canary. Will report if I see it happening again!

**Comment by noway** [comment]
@Jarred-Sumner unfortunately still happens on canary:


```
$ curl -v https://api.diy-llm-bot.com/
*   Trying 3.140.242.194:443...
* Connected to api.diy-llm-bot.com (3.140.242.194) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
* Closing connection 0
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

```
$ curl -v https://api.diy-llm-bot.com/
*   Trying 3.140.242.194:443...
* Connected to api.diy-llm-bot.com (3.140.242.194) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* LibreSSL/3.3.6: error:1404B417:SSL routines:ST_CONNECT:sslv3 alert illegal parameter
* Closing connection 0
curl: (35) LibreSSL/3.3.6: error:1404B417:SSL routines:ST_CONNECT:sslv3 alert illegal parameter
```

curl alternates between "alert protocol version" and "alert illegal parameter". Restarting bun solves the issue and SSL starts working again fine.

**Comment by noway** [comment]
Maybe I could compile bun with some debug info?
