### ISSUE TITLE
Replace the node_modules folders with an alternative system

### ISSUE THREAD

**Issue by peacefulotter** [oven-sh/bun#6926]
### What is the problem this feature would solve?

The node_modules folder takes a massive amount of space, especially because of duplicate installations, and things get worse when dealing with multiple js projects. An alternative system could drastically reduce the disk space required and the time it takes to install packages. 

### What is the feature you are proposing to solve the problem?

The following is only one of probably many approaches:  

Removing the node_modules per project and only use the global node_modules that will be able to handle multiple versions for the same package. When installing dependencies, the new system would look at the global node_modules folder and check if they can be matched to the ones that are already installed. If not, simply globally install the package with the required version. 

This approach, I think, requires some kind of resolver that will target the correct package version on imports. 
For instance, suppose one has an `index.ts` file which imports some package:
```ts
import foo from 'installed-package';
```

But suppose one already has the `installed-package` in multiple versions, then the resolver should be able to find out which version this file specifically targets. In this scenario, the resolver could simply add the required version to the import as so:
```ts
import foo from 'installed-package@2.3.0'
```

### What alternatives have you considered?

None

**Comment by Jarred-Sumner** [comment]
This is implemented

https://bun.sh/docs/runtime/autoimport
