### ISSUE TITLE
Unable to install packages from private bitbucket repo

### ISSUE THREAD

**Issue by LucyEgan** [oven-sh/bun#6927]
### What version of Bun is running?

1.0.9+98f20170a

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a private repo on bitbucket
try and install the package from `bitbucket:YOUR_ACCOUNT/YOUR_REPO`

### What is the expected behavior?

Install the package from the private repo using current ssh key 

### What do you see instead?

It attempts to install using https instead of ssh 
<img width="593" alt="image" src="https://github.com/oven-sh/bun/assets/5268652/31ffa7c7-5b39-4983-ab67-02381ed76448">

### Additional information

Seems related to https://github.com/oven-sh/bun/issues/5027 but thats marked as completed.

**Comment by ngHblanchard** [comment]
Same issue here. Trying to install packages in a circleci pipeline: 
the script stops on the resolve step, asking for a password, even if the package is included like this : `git+ssh://git@bitbucket.org/YOUR_ACCOUNT/YOUR_REPO#version`.
