### ISSUE TITLE
`bun tsconfig`

### ISSUE THREAD

**Issue by alii** [oven-sh/bun#693]
### What is the problem this feature will solve?

It would be nice to have a command to autofill nice defaults into `tsconfig.json` about things like Bun globals and supported features (like top level await).

### What is the feature you are proposing to solve the problem?

`bun tsconfig [tsconfig_path=tsconfig.json]` will modify or create a `tsconfig.json` that will be 100% compatible with Bun at runtime
`bun tsconfig [tsconfig_path=tsconfig.json] --dry-run` will show modifications that it will run without the flag

**Comment by paperclover** [comment]
would be cool if this installs `bun-types` (or `@types/bun` as roadmap says)

**Comment by xhyrom** [comment]
You can use blank template for now

**Comment by Electroid** [comment]
If you run `bun init`, we do auto-fill a `tsconfig.json` with `bun-types` installed. We could do something like this in a VSCode extension.

**Comment by Electroid** [comment]
I think we'll lean on and encourage folks to use `bun init` for this. While we could add a specific command, it's a little too niche.

**Comment by alii** [comment]
Sounds good, this would be a perfect fit for `init`. Thanks!
