### ISSUE TITLE
`mock.module` is not documented

### ISSUE THREAD

**Issue by wojtekmaj** [oven-sh/bun#6935]
### What is the type of issue?

Documentation is missing

### What is the issue?

`mock.module` is not documented

<img width="626" alt="image" src="https://github.com/oven-sh/bun/assets/5426427/a7aa60a0-24b0-41bd-99e4-e1d3abf331a9">

**Comment by baublet** [comment]
Saw this while searching around for something. This can probably be closed. This functionality appears to be documented, now: https://bun.sh/docs/test/mocks#module-mocks-with-mock-module
