### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

### ISSUE THREAD

**Issue by gshilin** [oven-sh/bun#694]
### Version

0.1.4

### Platform

Linux gshilin-VirtualBox 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

$ bun -v
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
0.1.4

### How often does it reproduce? Is there a required condition?

always

### What do you see instead?

ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by jumoog** [comment]
should be fixed

**Comment by Electroid** [comment]
If you're still running into this issue, please feel free to re-open it.
