### ISSUE TITLE
Can't use arrow keys with `bun create` in WSL start from v.1.0.9

### ISSUE THREAD

**Issue by thuongvux** [oven-sh/bun#6950]
### What version of Bun is running?

v1.0.9 and v1.0.10

### What platform is your computer?

WSL

### What steps can reproduce the bug?

When run `bun create vite`, I can't use arrow keys to navigate options. It's work on v1.0.8, but broke from v1.0.9

**Comment by Electroid** [comment]
Potentially related: #1672

**Comment by tehKost** [comment]
still not working since v1.0.8
