### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#6954]
### What version of Bun is running?

1.0.9-1.0.10

### What platform is your computer?

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

my.js

```javascript
console.log(Request.prototype);
```
step1：bun --watch my.js
step2：Segmentation fault

**Comment by Jarred-Sumner** [comment]
the bug is in our implementation of console.log, the code is missing the check for the CustomAccessor

**Comment by Jarred-Sumner** [comment]
Caused by d1244c8b1feb367220218f9c78dd73ce4cdcc76b
