### ISSUE TITLE
Bun not able to match versions for @mui/lab using caret in version (i.e. "^5.0.0-alpha.152")

### ISSUE THREAD

**Issue by valleywood** [oven-sh/bun#6956]
### What version of Bun is running?

1.0.10

### What platform is your computer?

Darwin 23.0.0 x86_64 i386 (Mac OSX)

### What steps can reproduce the bug?

bunx create-next-app@latest
bun add @mui/lab
bun update

=>

error: No version matching "^5.0.0-alpha.152" found for specifier "@mui/lab" (but package exists)

### What is the expected behavior?

Bun should be able to update to lastest version on all packages including @mui/lab.

If i update from
```
 "@mui/lab": "^5.0.0-alpha.152",
 ```
 to 
 ```
  "@mui/lab": "5.0.0-alpha.152",
  ```
  
  Everything works but I want to be able to use roof functionality to keep up with latest versions

### What do you see instead?

error: No version matching "^5.0.0-alpha.152" found for specifier "@mui/lab" (but package exists)

### Additional information

Maybe related to 
https://github.com/oven-sh/bun/issues/4701 and https://github.com/oven-sh/bun/issues/4666 but as these are both closed i filed a new issue.

**Comment by dylan-conway** [comment]
fixed in #6981
