### ISSUE TITLE
Prisma and async IIFEs don't seem to work properly

### ISSUE THREAD

**Issue by Tenrys** [oven-sh/bun#6962]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I created a project mostly following this example: https://bun.sh/guides/ecosystem/prisma
You can download it here: [test.zip](https://github.com/oven-sh/bun/files/13282568/test.zip)

If you check the `index.ts` inside, you'll see that I wrapped everything in an async IIFE, as a test. 
If you try to run it with Bun, you'll see that nothing happens. However, if you put the line that instanciates the Prisma client outside of the IIFE, it starts working again.

I tried this out because I had a different issue when trying to use Bun in a project that works with node, where I use Prisma in an IIFE to get around the lack of top-level await. As soon as I was trying to use Prisma inside of the function, it would stop doing anything at all and move on.

**Comment by Tenrys** [comment]
Ah, I looked a little further, here are some related issues.

https://github.com/oven-sh/bun/issues/3137
https://github.com/prisma/prisma/issues/21324

**Comment by Electroid** [comment]
This is most likely a duplicate of #3137 as you mentioned, so going to close as a duplicate. We will fix this.
