### ISSUE TITLE
node-addon-api repeated calls using Promise without explicit GC call leads to segfault.

### ISSUE THREAD

**Issue by liz3** [oven-sh/bun#6965]
### What version of Bun is running?

1.0.9+98f20170a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Go to the repro respository and follow the readme steps: (installing canvas deps, cloning, building, running): https://github.com/liz3/bun-canvas-bug
2. Run the index.mjs once and then with `gc` as a argument

### What is the expected behavior?

Run the prcoess, exiting after finishing the loop in [index.mjs](https://github.com/liz3/bun-canvas-bug/blob/main/index.mjs).

### What do you see instead?

The process segfaults in native code using a argument which does not exist anymore, see LLDB backtrace: 
<img width="1314" alt="image" src="https://github.com/oven-sh/bun/assets/21298625/a37bd73e-6c71-47ca-915e-17688cb159fc">

### Additional information

Passing `gc` as a cli arg makes bun forcefully run its GC before the next iteration resolving the issue, but obviously this should not be needed.

**Comment by Jarred-Sumner** [comment]
Doesnt reproduce anymore
