### ISSUE TITLE
`bun install --frozen-lockfile` not deterministic in GitHub Actions

### ISSUE THREAD

**Issue by michaelhays** [oven-sh/bun#6966]
### What version of Bun is running?

1.0.10+d85bd49d8

### What platform is your computer?

GitHub Actions, Linux machines

### What steps can reproduce the bug?

I have the following GitHub Actions `.github/workflows/deploy.yml` file:

```deploy.yml
name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-dependencies

      - run: bun prisma generate

      - name: Build app
        run: bun vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM_ID }}
```

### What is the expected behavior?

I would expect this code to build my app deterministically.

### What do you see instead?

The build sometimes fails, and sometimes succeeds, seemingly at random. Whenever a build fails, I have to click "Re-run jobs" in the GitHub Actions UI, and eventually it will pass.

The `bun install --frozen-dependencies` step seems to install the correct versions, at least for the packages defined in my `package.json` file:

```
Run bun install --frozen-dependencies
bun install v1.0.10 (d85bd49d)
 + ...
 + prisma@5.5.2
 + ...
```

However, the `bun prisma generate` step sometimes shows the following warning (last 3 lines):

```
Run bun prisma generate
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.5.2) to ./node_modules/@prisma/client in 822ms

...

warn Versions of prisma@5.4.0 and @prisma/client@5.5.2 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
```

Additionally, sometimes the `bun vercel build` step fails, and sometimes it succeeds. (Interestingly, the build step success doesn't seem to depend on whether we see the Prisma version mismatch warning above)

Over the past several weeks, the build has failed due to varying different reasons, and the specific error changes every time I update my dependencies and lockfile. Currently, this is the error that shows up on failures:

```
Failed to compile.

./emails/Login.tsx
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

...

> Build failed because of webpack errors
error: script "build" exited with code 1 (SIGHUP)
Error: Command "bun prisma generate && bun run build" exited with 1
error: "vercel" exited with code 1 (SIGHUP)
Error: Process completed with exit code 1.
```

(However, this specific error is not important, since it's been a plethora of different things over the past few weeks)

### Additional information

I've been having this issue since at least Bun 1.0.4.

Likely related: #3932

Let me know if you need me to create a standalone project with a minimal production, and I can work on that.

**Comment by michaelhays** [comment]
Haven't had this issue in a while, may have been fixed with recent changes to `bun install`.

**Comment by Jarred-Sumner** [comment]
awesome! (cc @dylan-conway)

let us know if you run into it again in the future
