### ISSUE TITLE
NODE_ENV specific `.env` files not being read in during `bun run` runtime

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#6974]
### What version of Bun is running?

1.0.10+d85bd49d8

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a `.env` `.env.development` and a `.env.local` file
2. Add variables to these files
3. Run `bun run env`
4. Observe variables being loaded in from your `.env` and `.env.local` files
5. Observe the value of `NODE_ENV` (if 'development` proceed, if not, set NODE_ENV to 'development')
6. Observe the absence of your variables in `.env.development`

### What is the expected behavior?

Values defined in `.env.development` be procesed in the `bun run env` command

### What do you see instead?

Variables from `.env.development` are not processed and made available to my env variables during runtime

### Additional information

There is very little documentation on how to set this part up, it just implies that it should work out of the box. So it's entirely possible that I am just misusing it. If that's the case, I'd be happy to be educated on how to use it properly.

**Comment by JeffreyATW** [comment]
Dupe of https://github.com/oven-sh/bun/issues/6334?

**Comment by ghost** [comment]
> Dupe of #6334?

Yes, closing this one out. Will mention on the original ticket that the issue still persists with version 1.0.10
