### ISSUE TITLE
Can't find variable: module

### ISSUE THREAD

**Issue by jld-adriano** [oven-sh/bun#6977]
### What version of Bun is running?

1.0.10+d85bd49d8

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Made a repro: https://github.com/jld-adriano/bun-repro-4818
Relevant files are index.ts, repro.ts and repro2.ts

just bun index.ts

Basically have a file, import another one that uses the module global variable, and that file imports from another one

### What is the expected behavior?

Shouldn't error

### What do you see instead?

An error

**Comment by Jarred-Sumner** [comment]
Use `import.meta.main`

This is a quirk of our ESM<>CJS interop -- you can use `import` and `require` in the same file, but not `export`
