### ISSUE TITLE
git polyfill for bun build

### ISSUE THREAD

**Issue by sk337** [oven-sh/bun#6978]
### What is the problem this feature would solve?

i wanted to get some stats on related to the git repository that conatains my src files and  i had to copy git files from .git dir and add .txt to them 1by 1

### What is the feature you are proposing to solve the problem?

I propose a git polyfill the includes info like commit hash, git repo, owner etc. similar to the node polyfills referenced in [Bun Bundiler](https://bun.sh/blog/bun-bundler#targets) blog post

### What alternatives have you considered?

i can copy files over with .txt extensions or maybe make a build plugin

**Comment by Electroid** [comment]
Can you elaborate a bit more on what you're proposing? It's hard to grasp it

**Comment by Electroid** [comment]
This is something that can be done with [Bun Macros](https://bun.sh/docs/bundler/macros#examples). We are unlikely to add specific support for this.
