### ISSUE TITLE
documentation of quotation marks incomplete

### ISSUE THREAD

**Issue by adwilk** [oven-sh/bun#6984]
The documentation for [quotation marks](https://bun.sh/docs/runtime/env#quotation-marks) has an incomplete sentence.
> Bun supports double quotes, single quotes, and

Should this continue on to talk about template literal backticks?

Source of the issue:
https://github.com/oven-sh/bun/blame/f7f6233ea85867da681a910d3814954c84bba82f/docs/runtime/env.md#L30

**Comment by ghost** [comment]
Duplicate of #6906.

**Comment by ghost** [comment]
This has been fixed with #7895.
