### ISSUE TITLE
`Bun.inspect` is exposing private fields by default

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#6995]
### What version of Bun is running?

1.0.11

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
class T {
  #f = 0
}

console.log(new T())
```

### What is the expected behavior?

Log shows:

```sh
T {}
```

### What do you see instead?

Log shows:

```sh
{
  [Symbol(#f)]: 0
}
```

**Comment by Didas-git** [comment]
After some digging i found out that node doesnt actually support private fields at all, so here is my i guess proposal for `Bun.inspect`.

By default do not expose private fields and provide an option like `showPrivate: bool` and also change how privates are printed out. Printing privates as `Symbol(#private)` is a bit confusing since classes with custom symbols are a thing, instead we could print them out just like the terminal in chrome `#private` where private has a different color ex: light blue.

**Comment by paperclover** [comment]
ah yes, i fixed this in a recent pr. the private fields are shown in debug mode, though i forgot about class private fields so the printing is weird.

<img width="545" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/df402743-39d4-4fa1-9f91-22f88a3c3b31">

**Comment by paperclover** [comment]
hm, actually i guess if we want to allow printing these in release under a flag, that might be interesting. idk if this is desired, maybe open a feature request to expose it as a formatting option.

**Comment by Didas-git** [comment]
> hm, actually i guess if we want to allow printing these in release under a flag, that might be interesting. idk if this is desired, maybe open a feature request to expose it as a formatting option.

As we discussed on discord before, a new option could be added to `Bun.inspect`, we have `showHidden` we can add `showPrivates`
