### ISSUE TITLE
util.formatWithOptions type issue

### ISSUE THREAD

**Issue by brettgoulder** [oven-sh/bun#6996]
### What version of Bun is running?

1.0.11

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

It seems util.formatWithOptions was added here: https://github.com/oven-sh/bun/issues/3760

However, its type does not appear in the VSCode editor, resulting in the Typescript error: `Property 'formatWithOptions' does not exist on type 'typeof import("util")'.`

I'm pretty sure it's because this is commented out: https://github.com/oven-sh/bun/blob/main/packages/bun-types/util.d.ts#L129-L130

Have any thoughts?

**Comment by paperclover** [comment]
an older version of bun did not have this function. when i implemented it, i did not uncomment the types.

do you want to open a pr that uncomments this?

**Comment by brettgoulder** [comment]
@paperdave yep, I can. I didn't quite understand the comment regarding the polyfill though. Is there something that I need to do other than uncomment this?

**Comment by paperclover** [comment]
nope. the "but is not defined in the polyfill" refers to before i implemented it in the polyfill.

**Comment by brettgoulder** [comment]
okay great, got a PR up for your review
