### ISSUE TITLE
Bun install

### ISSUE THREAD

**Issue by GuiAlmeida** [oven-sh/bun#700]
### Version

0.1.4

### Platform

Linux Ubuntu 22.04

### What steps will reproduce the bug?

When using bun in a Vue 2 project, it displays this error and does not continue the dependencies' installation process

![Captura de tela de 2022-07-14 04-12-45](https://user-images.githubusercontent.com/5199435/178923586-fa700d40-4892-4845-a53d-9ed474e499cf.png)

**Comment by FinnRG** [comment]
``npm:`` dependencies aren't supported yet. Please see  #227 for further information.
