### ISSUE TITLE
Segmentation fault and Request body stream locking

### ISSUE THREAD

**Issue by ovx** [oven-sh/bun#7001]
### What version of Bun is running?

1.0.11

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

There seem to be two problems 1) the body ReadableStream is not being locked when reading it and 2) trying to read the stream afterwards fails with segmentation fault.

```ts
const req = new Request('https://example.com/', {
  body: 'test',
  method: 'POST',
});

// getting array buffer of the body to calculate body hash (for request signing for example)
const ab = await new Response(req.body).arrayBuffer();

// should be true, but is false in bun
console.log('Locked:', req.body?.locked);

// send request
await fetch(req);
```

Just for correctness, the right way of getting array buffer is using `req.clone().body` (which works fine in bun); Discovered this segmentation fault problem by mistake.

### What is the expected behavior?

1) req.body.locked should be true
2) should not fail with segmentation fault; should throw error (stream locked) just like other JS environments

**Comment by Jarred-Sumner** [comment]
Yeah, we really need to refactor ReadableStream to use a JSInternalFieldObjectImpl subclass and not pass raw pointers to JS. Terribly hacky how this was done and it was done before we knew how to add high quality JSC bindings
