### ISSUE TITLE
ReferenceError: Cannot access uninitialized variable

### ISSUE THREAD

**Issue by eandre** [oven-sh/bun#7003]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

I created a small reproducer repository at [eandre/bun-bug-reproducer](https:///github.com/eandre/bun-bug-reproducer).

Steps to reproduce:

```
git clone https://github.com/eandre/bun-bug-reproducer.git
cd bun-bug-reproducer
bun ./main.ts
```

### What is the expected behavior?

The script should compile correctly and output a single line `Foo`.

### What do you see instead?

The error message:
```
3 | export interface BarClient {
4 |   bar: typeof Bar;
5 | }
6 | 
7 | export const barSvc: BarClient = {
8 |   bar: Bar,
           ^
ReferenceError: Cannot access uninitialized variable.
      at /path/to/repo/clients/bar.ts:8:7
```

### Additional information

Everything works correctly when using `bun build --target=bun main.ts`. E.g.:

```
$ bun build --target=bun --outfile=main.js main.ts && bun main.js
Foo
```

**Comment by Jarred-Sumner** [comment]
ESM treats cyclical imports differently than CommonJS. 

After manually removing the TypeScript types, we can reproduce this in Node and Bun both.

In Bun:
```ts
❯ bun main.mjs
1 | import { Bar } from "../bar.mjs";
2 |
3 | export const barSvc = {
4 |   bar: Bar,
           ^
ReferenceError: Cannot access uninitialized variable.
      at /private/tmp/hm/bun-bug-reproducer/clients/bar.mjs:4:8

Bun v1.1.12-canary.1+8806bf9c4 (macOS arm64)
```

In Node:
```ts
❯ node main.mjs
file:///private/tmp/hm/bun-bug-reproducer/clients/bar.mjs:4
  bar: Bar,
       ^

ReferenceError: Cannot access 'Bar' before initialization
    at file:///private/tmp/hm/bun-bug-reproducer/clients/bar.mjs:4:8
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5)

Node.js v22.2.0
```

I don't think this issue can be fixed without static analysis like what the bundler does at runtime, which we cannot do without introducing significant runtime/performance overhead.

[bun-bug-reproducer.zip](https://github.com/user-attachments/files/15543871/bun-bug-reproducer.zip)

If you want cyclical imports in this way, you could try CommonJS.
