### ISSUE TITLE
Getting "undefined is not an object" on polyfill-library

### ISSUE THREAD

**Issue by LucyEgan** [oven-sh/bun#7008]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install polyfill-library package and use it as follows

```
import polyfillLibrary from 'polyfill-library';

let polyfillBundle = await polyfillLibrary.getPolyfillString({
      uaString: '',
      unknown: 'polyfill',
      features: {
          'es2015': {flags: []},
      },
  });
  console.log(polyfillBundle);
```

### What is the expected behavior?

To return a polyfill string

### What do you see instead?
```
TypeError: undefined is not an object
 at node:stream:1743:322
 at streamPolyfillSource (/workspace/node_modules/polyfill-library/lib/sources.js:97:1)
 at /workspace/node_modules/polyfill-library/lib/index.js:359:7
 at processTicksAndRejections (:61:76)
```

### Additional information

Looks like a internal issue with streams as it works as expected when running in node

**Comment by nektro** [comment]
Does this still reproduce for you? it appears to be working on my end now in Bun 1.1.10 (you may need to run `bun upgrade`)

**Comment by LucyEgan** [comment]
Just checked this on 1.1.12 and can confirm its resolved now
