### ISSUE TITLE
node-tar support

### ISSUE THREAD

**Issue by paulll** [oven-sh/bun#7010]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 6.1.59-1-lts x86_64 unknown

### What steps can reproduce the bug?

```js
import tar from 'tar'

await tar.create({
  file: '/tmp/test.tar',
  cwd: process.cwd(),
}, ['.']);
```

### What is the expected behavior?

Should create tarball at /tmp/test.tar, like it does with node.js

### What do you see instead?

```
❯ bun index.js
133 | 
134 |   [ONLSTAT] (stat) {
135 |     this.statCache.set(this.absolute, stat)
136 |     this.stat = stat
137 |     if (!stat.isFile()) {
138 |       stat.size = 0
          ^
TypeError: Attempted to assign to readonly property.
      at /tmp/test/node_modules/tar/lib/write-entry.js:138:6
      at new WriteEntry (/tmp/test/node_modules/tar/lib/write-entry.js:112:6)
      at /tmp/test/node_modules/tar/lib/pack.js:334:13
      at /tmp/test/node_modules/tar/lib/pack.js:302:16
      at /tmp/test/node_modules/tar/lib/pack.js:232:6
      at /tmp/test/node_modules/tar/lib/pack.js:220:4
      at /tmp/test/node_modules/tar/lib/pack.js:213:6
      at processTicksAndRejections (:61:76)
```

### Additional information

[tar](https://www.npmjs.com/package/tar) has over 10M weekly downloads and over 3K dependents

**Comment by nektro** [comment]
Does this still reproduce for you? It works for me as of at least Bun 1.1.8 (you may need to run `bun upgrade`)

**Comment by paulll** [comment]
Now it works for me with the last Bun
