### ISSUE TITLE
bun link <local workspace package> creates incorrect symlink. Symlink points to workspace root instead of package

### ISSUE THREAD

**Issue by wellcaffeinated** [oven-sh/bun#7013]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a workspace with members in `packages/` dir (example: packages/my-package)
2. `cd packages/my-package`
3. `bun link` (gives expected output)
4. `cd some/other/packages/elsewhere`
5. `bun link my-package`
6. `ls -la node_modules/my-package`

### What is the expected behavior?

Should create symlink to `my-workspace/packages/my-package`.

### What do you see instead?

Instead, it creates a symlink to workspace root directory instead of the workspace package subdirectory

### Additional information

I was using scoped names (`@my-org/my-package`)

**Comment by dylan-conway** [comment]
This was fixed in #11177, and is included in `v1.1.9` and newer versions of bun
