### ISSUE TITLE
`setInterval` & `setTimeout` are using node's version by default

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#7020]
### What version of Bun is running?

1.0.11

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
const t = setInterval(() => { });
t.toFixed();
```

### What is the expected behavior?

It should run just like in the browser since im not importing `node:timers`

### What do you see instead?

Its using `node:timers` which return objects instead of numbers

### Additional information

If the intended bnehavior is to use node's version then the types are also wrong since the types in `bun-types` say it returns number just like in the DOM

**Comment by Jarred-Sumner** [comment]
This is unfortunately necesary for Node.js compatibility and won't be changed. You can continue to use numbers if you'd like, `+setTimeout(() => {}, 123)` will return a number that can be used.

**Comment by Didas-git** [comment]
> This is unfortunately necesary for Node.js compatibility and won't be changed. You can continue to use numbers if you'd like, `+setTimeout(() => {}, 123)` will return a number that can be used.

Can't node compatibility just be done via `node:timers` instead?

I think this needs a bit more of a review since using `bun build` with `target browser` wont detect `timeout.unref` (and other methods) and you end up with errors when running in the browser

**Comment by Jarred-Sumner** [comment]
Libraries expect `.unref` to work. We can't really do anything about that without adding `unref` and `ref` methods to the `Number` prototype which would be kind of crazy.

**Comment by Didas-git** [comment]
I get that but libraries that want to support bun could just add a simple import and it would work.

Perhaps this is an outlandish idea but i would prefer for node compat to be more of an opt-in feature (or i guess with the current state opt-out) and get better apis that are bun exclusive/spec compliant. We already have something like this for example `Bun.serve` and i think a lot of people would agree with me when i say that we should have a way to at least opt-out of all of node's weirdness in favor of better and faster alternatives.
