### ISSUE TITLE
Codeblocks are not handled correctly in toml parser

### ISSUE THREAD

**Issue by xhyrom** [oven-sh/bun#703]
### Version

0.1.4

### Platform

Microsoft Windows NT 10.0.25151.0 x64 | Linux LAPTOP-J5PF3D19 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. Create `xx.toml`
2. Add codeblock to `xx.toml`:

```toml
[test]
content = """
\`\`\`js
console.log('Hello, bun!');
\`\`\`
"""
```

**without \ but github would change it to codeblock**

### How often does it reproduce? Is there a required condition?

Always, printer bug

### What is the expected behavior?

Loading a file with codeblock:

![image](https://user-images.githubusercontent.com/56601352/178944391-a9427a6f-f948-4c93-ab93-011773abdd12.png)

### What do you see instead?

```SyntaxError: Invalid escape in identifier: '\'```

![image](https://user-images.githubusercontent.com/56601352/178943893-60b21773-e78b-477d-b26a-cc19b94edee7.png)

### Additional information

Jarred: https://canary.discord.com/channels/876711213126520882/887787428973281300/997060743348375583

**Comment by jlandrum** [comment]
This is not an issue with bun or toml.
If you want `` \` `` to be in the output, you need to escape the escape with `` \\` `` otherwise if your intent is to just have the `, it does not need to be escaped.

**Comment by xhyrom** [comment]
> This is not an issue with bun or toml. If you want `` \` `` to be in the output, you need to escape the escape with `` \\` `` otherwise if your intent is to just have the `, it does not need to be escaped.

This is an issue with bun. `content` is a string, so you don't need to escaping. I tried it with one npm package, with which it works perfectly fine.

Check https://canary.discord.com/channels/876711213126520882/887787428973281300/997060743348375583

**Comment by RiskyMH** [comment]
I can't seem to reproduce, if this is still an issue @xhyrom let me know and I can re-open.
