### ISSUE TITLE
Allow mocking modules in preload file

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#7035]
### What is the problem this feature would solve?

It would allow mocking modules in the preload file when using `bun --preload ./preload.ts`.

Currently the following error is returned in the preload file:
```
undefined is not an object (evaluating 'mock.module')
```

### What is the feature you are proposing to solve the problem?

Allowing mock.module in the preload file

### What alternatives have you considered?

Mocking each individual test file

**Comment by Jarred-Sumner** [comment]
This is definitely unintentional
