### ISSUE TITLE
Error ENOENT when `bun install`ing with a `package-lock.json`

### ISSUE THREAD

**Issue by novaluke** [oven-sh/bun#7037]
### What version of Bun is running?

1.0.11

### What platform is your computer?

Linux 6.5.2 x86_64 unknown

### What steps can reproduce the bug?

* Copy the attached `package.json` and `package-lock.json` files to a directory.
* Run `bun install`

[package.json](https://github.com/oven-sh/bun/files/13322709/package.json)
[package-lock.json](https://github.com/oven-sh/bun/files/13322710/package-lock.json)

### What is the expected behavior?

All packages install successfully without any errors.

### What do you see instead?

Many `error: ENOENT` errors. `bun install` reports it failed to install over 1000 packages:

```
...
 + underscore@1.13.4 (v1.13.6 available)
 + whatwg-fetch@3.6.2 (v3.6.19 available)

 2451 packages installed [3.40s]
Failed to install 1109 packages
 installing color-name
error: ENOENT installing source-map
error: ENOENT installing kind-of
... (more error: ENOENT lines)
```

### Additional information

The `package-lock.json` was originally using lockfile version 2. When `bun install` was first run in the project, it instructed to upgrade the lockfile version via `npm i --lockfile-version 3 --frozen-lockfile`. After running that command, `bun install` began throwing the `ENOENT` errors.

**Comment by kamil-kubiczek** [comment]
i have exactly same issue, also lockfile version 3

**Comment by samuelnihoul** [comment]
I have the same issue on WSL Ubuntu 23
