### ISSUE TITLE
Typegoose doesn't work in bun

### ISSUE THREAD

**Issue by UltimateBrent** [oven-sh/bun#7039]
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 5.4.0-1038-aws x86_64 x86_64

### What steps can reproduce the bug?

node v16.20.1
Typegoose@11.7.x
Mongoose@7.6.3

If you `Ref` a model from another model, bun crashes with a syntax error when you actually load and save it. Not on initial load of the application.

### What is the expected behavior?

It shouldn't produce any errors. Works fine in regular node.

### What do you see instead?

```
SyntaxError: Import named 'Ref' not found in module '/var/src/project/node_modules/@typegoose/typegoose/lib/typegoose.js'.
      at processTicksAndRejections (:55:76)
```

### Additional information

EDIT: I just upgraded to `bun@1.0.11` and it had the same issue.

**Comment by dylan-conway** [comment]
This sounds like a `emitDecoratorMetadata` bug. If you build your project with `bun build` or turn off decorator metadata in `tsconfig.json`, does it still report a syntax error?

**Comment by UltimateBrent** [comment]
if I turn off `emitDecorators` in the tsconfig it doesn't work on bun or node. I think that's required for how Typegoose works.

bun build threw a new one:

```
TypeError: undefined is not an object (evaluating 'Buffer2.from')
```

running bun or node on the built js file results in that error.

**Comment by chadacious** [comment]
Hmm, I'm getting the same issue with now apparent workaround.

**Comment by chadacious** [comment]
It seems that in my case, this is only happening in a typegoose project in combination with type-graphql. If I call type-graphql's buildSchema with even just one resolver, I get the Ref error. If I don't buildSchema, but leave the typegoose code in place, it compiles fine. Seems like the Ref error is not indicative of where the real issue is? Will need to investigate further.

**Comment by chadacious** [comment]
Oh I see that @UltimateBrent already basically said that it only happens when you "activate" the Ref model, not when you just load the app. Here is a reproducible that shows the issue (Note that if you uncomment the Ref prop in the User class it will throw the Syntax error:
```
import { Elysia } from "elysia";
import { apollo } from '@elysiajs/apollo'
import { Ref, getModelForClass, prop } from "@typegoose/typegoose";
import { Arg, Field, ID, InputType, Mutation, ObjectType, Query, Resolver, buildSchema } from "type-graphql";

@ObjectType({ description: "The Error response for inclusion in other response types" })
export class ErrorResponse {
    @Field({ nullable: true })
    path?: string;

    @Field()
    message!: string;
}

@ObjectType({ description: "A response type for simple operations" })
export class SimpleResponse {
    @Field()
    ok!: boolean;

    @Field(() => [ErrorResponse], { nullable: true })
    errors?: ErrorResponse[];
}

@ObjectType()
export class UserNote {
    @Field(() => ID)
    id!: string;

    @Field()
    @prop({ unique: true })
    note!: string;
}

export const UserNoteModel = getModelForClass(UserNote);

@ObjectType()
export class User {
    @Field(() => ID)
    id!: string;

    @Field()
    @prop({ unique: true })
    name!: string;

    // @Field(() => UserNote)
    // @prop({ ref: () => UserNote, required: true })
    // userNote!: Ref<UserNote>;
}

export const UserModel = getModelForClass(User);

@Resolver()
export class UserQueries {
    @Query(() => [User])
    async getUsers(): Promise<User[]> {
        let res: User[] = [];
        res = await UserModel.find();
        return res;
    }
}

@InputType()
export class UserInput {
    @Field() id!: string;
    @Field({ nullable: true }) textProp?: string;
}

@Resolver()
export class UserResolver extends UserQueries {
    @Mutation(() => SimpleResponse)
    async updateUser(
        @Arg("data", () => [UserInput]) data: UserInput[],
    ): Promise<SimpleResponse> {
        return { ok: true };
    }
}

const schema = await buildSchema({
    resolvers: [UserResolver] ,
    emitSchemaFile: true,
    validate: { forbidUnknownValues: false },
});

const app = new Elysia()
  .use(apollo({ schema }));

app.listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);

```

**Comment by UltimateBrent** [comment]
Not a fix, but a solution: I switched to TypeORM. Basically same thing as typegoose but does more and has cleaner model syntax and works with bun. Hopefully this helps anyone with similar troubles.

**Comment by chadacious** [comment]
With bun 1.0.25 you get an informative error:
```
A type referenced in a decorated signature must be imported with 'import type' or a namespace import ...
```
And indeed, this now is working with typegoose if you import like this:
```
import type { Ref } from '@typegoose/typegoose';
```
