### ISSUE TITLE
the Zig version is incorrect

### ISSUE THREAD

**Issue by sirenkovladd** [oven-sh/bun#7041]
### What version of Bun is running?

-

### What platform is your computer?

-

### What steps can reproduce the bug?

Bun requires zig version - 0.12.0-dev.1297+a9e66ed73

latest version in npm is 0.12.0-dev.1286
and version 0.12.0-dev.1297 not exists in npm

### What is the expected behavior?

Add new version

### What do you see instead?

```
error: The minimum version of Zig required to compile Bun is 0.12.0-dev.1297+a9e66ed73, found 0.12.0-dev.1286+cc394431a
            @compileError("The minimum version of Zig required to compile Bun is " ++ recommended_zig_version ++ ", found " ++ @import("builtin").zig_version_string);
```

### Additional information

https://github.com/oven-sh/bun/blob/bun-v1.0.11/build.zig#L1C45-L1C49

https://www.npmjs.com/package/@oven/zig?activeTab=versions

**Comment by SoonIter** [comment]
the npm package is out of date, you can download the latest zig on official site

[ziglang.org](https://ziglang.org/download/)

**Comment by sirenkovladd** [comment]
Of course I'm just saying that the https://bun.sh/docs/project/contributing#install-zig should have the correct way to install zig

**Comment by tiziodcaio** [comment]
Solved.

**Comment by sirenkovladd** [comment]
I'm not sure, all I see is that they removed the zig installation instructions from the bun contribution page
Perhaps it would be useful to specify that you need to install the zig

**Comment by sirenkovladd** [comment]
fixed in https://github.com/oven-sh/bun/pull/7305
