### ISSUE TITLE
Unsupported core modules are causing errors instead of returning empty objects

### ISSUE THREAD

**Issue by PaulAsjes** [oven-sh/bun#705]
### Version

0.1.4

### Platform

Darwin Pauls-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run this snippet:
```js
try {
    console.log(require('child_process'));
} catch(e) {
    console.log(e);
}
```

### How often does it reproduce? Is there a required condition?

It errors every time.

### What is the expected behavior?

Unsupported core modules should return an empty object.

### What do you see instead?

```
1 | try {
2 |     console.log(require('child_process'));
                           ^
 error: Cannot require module "child_process"
      at /Users/paul/code/bun/server.js:2:24
      at /Users/paul/code/bun/server.js:2:24

 ```

### Additional information

As per advice on Discord, tried the following fixes:
1. Bundle before running: `bun bun ./file.js --platform=bun`
2. Specifying core module: `require('node:child_process')`
3. Removing `node_modules.bun`
4. Forcing a runtime require with:
```js
const moduleName = "child_process";
require(moduleName);
```

All of which led to similar `Cannot find package "child_process"` errors.

**Comment by Electroid** [comment]
We are working on improving Node.js compatibility, this particular issue will be fixed when #1424 is merged.
