### ISSUE TITLE
Rasperry Pi 4, Raspberry Pi OS Lite (32-bit), "-bash: /home/username/.bun/bin/bun: cannot execute: required file not found"

### ISSUE THREAD

**Issue by NoelNimstad** [oven-sh/bun#7066]
### What version of Bun is running?

1.0.11

### What platform is your computer?

Linux 6.1.0-rpi4-rpi-v8 aarch64 unknown

### What steps can reproduce the bug?

have a fresh install of Raspberry Pi OS Lite (32-bit, 2023-10-10) on a Raspberry Pi 4, turn on internet access, install git and ssh and then attempt to install bun using: `curl -fsSL https://bun.sh/install | bash` and then attempt to run "bun"

### What is the expected behavior?

that bun would run like normal

### What do you see instead?

-bash: /home/username/.bun/bin/bun: cannot execute: required file not found

### Additional information

i have tried rebooting and re-installing several times, along with checking if any dependencies are required (although can't find any sources that tell me that)

**Comment by NoelNimstad** [comment]
i have made sure that unzip is installed and the install command `curl -fsSL https://bun.sh/install | bash` runs like normal and returns "bun was installed successfully to ~/.bun/bin/bun"

**Comment by NoelNimstad** [comment]
seems to be a 32 bit problem, works on 64 bit lite. apologies if i missed that it didn't run on 32 bit.

**Comment by Electroid** [comment]
Yes, Bun does not support 32-bit architectures, and likely will not.
