### ISSUE TITLE
Cannot send a stream with headers in `Response`

### ISSUE THREAD

**Issue by alii** [oven-sh/bun#707]
### Version

0.1.4

### Platform

Darwin trackpad.local 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:48:02 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T8103 arm64

### What steps will reproduce the bug?

The following code will correctly send back the rendered HTML, but no headers will be in the `Response`.

```ts
const stream = await ReactDOM.renderToReadableStream(component);

return new Response(stream, {
	status: 200,
	headers: { "Content-Type": "text/html; charset=UTF-8" },
});
```

### What is the expected behavior?

We see valid headers as well as the right content streamed

### What do you see instead?

The only header sent back down is `Content-Length`, nothing else.

### Additional information

Relevant discussion in bun discord: https://canary.discord.com/channels/876711213126520882/887787428973281300/997077986236977152

**Comment by Jarred-Sumner** [comment]
This has been fixed
