### ISSUE TITLE
Fedora COPR llvm-snapshots no longer serves LLVM 16

### ISSUE THREAD

**Issue by dottedmag** [oven-sh/bun#7073]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Contribution guide suggests to use COPR llvm-snapshots to obtain LLVM 16 under Fedora. This COPR now contains LLVM 18.

### Where did you find it?

https://bun.sh/docs/project/contributing

**Comment by DontBreakAlex** [comment]
I was able to get around this by:
- Disabling the COPR repos and uninstalling everything llvm related
- Going to [Kodji](https://koji.fedoraproject.org/koji/) and searching for `clang`, `lld` and `llvm`
- Downloading all rpms in a folder and installing them with `sudo dnf install ./*fc39.x86_64.rpm`

I needed these packages (.fc*.* depends on your distro and arch):
```
clang-16.0.0-1.fc39.x86_64.rpm
clang-devel-16.0.0-1.fc39.x86_64.rpm
clang-libs-16.0.0-1.fc39.x86_64.rpm
clang-resource-filesystem-16.0.0-1.fc39.x86_64.rpm
clang-tools-extra-16.0.0-1.fc39.x86_64.rpm
clang-tools-extra-devel-16.0.0-1.fc39.x86_64.rpm
git-clang-format-16.0.0-1.fc39.x86_64.rpm
llvm-16.0.6-6.fc39.x86_64.rpm
llvm-libs-16.0.6-6.fc39.x86_64.rpm
lld-16.0.6-1.fc39.x86_64.rpm
lld-devel-16.0.6-1.fc39.x86_64.rpm
lld-libs-16.0.6-1.fc39.x86_64.rpm
```

You also need to add this to `/etc/dnf/dnf.conf` to prevent it from updating llvm:
```
[main]
exclude=clang clang-devel clang-libs clang-resource-filesystem clang-tools-extra clang-tools-extra-devel git-clang-format lld lld-devel lld-libs lldb llvm llvm-libs python3-lldb
```
