### ISSUE TITLE
Contribution guide suggests to install dependencies after they are used

### ISSUE THREAD

**Issue by dottedmag** [oven-sh/bun#7076]
### What is the issue?

Contribution guide suggests to
- Install Bun
- Install LLVM
- Install dependencies
in this order.

However
- on a fresh Debian installation there is no `curl` to install Bun, and no `wget`, `software-properties-common`, `lsb-release` to install LLVM
- on a fresh Fedora installation there is no `unzip` to install Bun

So it will be useful to ask users to install dependencies first.

### Where did you find it?

https://bun.sh/docs/project/contributing

**Comment by squeaky-joe** [comment]
I can back this, though if you are using the bun runtime, I think that you should have terminal experience enough to be able to read the clear console errors it gives when you try to install it, whether it be `curl: command not found` or something along the lines of unzip needs to be installed.

**Comment by dottedmag** [comment]
Of course it's not the end of the world, just a small nuisance.
