### ISSUE TITLE
React Spinners Module Freezing Glitch

### ISSUE THREAD

**Issue by MagiqueDeveloper** [oven-sh/bun#710]
### Version

0.1.4

### Platform

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?

1) `bun create next .`
2) `bun add react-spinners`
3) `import { PuffLoader } from 'react-spinners'` in page file.
4) Use `<PuffLoader />` anywhere in code.
5) `bun dev`
6) Head to `localhost:3000` and the spinner will be frozen for a second until the spinner actually starts moving.

Cannot reproduce with React and Next using NodeJS.

### How often does it reproduce? Is there a required condition?

Reproduces every time.

### What is the expected behavior?

The spinner starts moving immediately.

### What do you see instead?

The spinner freezes for a second before moving.

**Comment by birkskyum** [comment]
`bun create next` gives me `404 GET / as application/octet-stream`, so I used `bun create react` to try this, and it does appear to start the animation immediately (I reload a few times in the video here):

https://github.com/oven-sh/bun/assets/74932975/5cfc3e08-a505-4afc-b824-b3aba0d39f78

@QVGK , do you find this to be resolved as well?
