### ISSUE TITLE
Missing 'default' import in module - YAML file

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#7127]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 6.2.0-1015-azure x86_64 x86_64

### What steps can reproduce the bug?

```bash
bun init -y
bun add -d bun-plugin-yaml
```

**index.ts**
```ts
import data from "./data.yaml";

console.log(data.doe);
```

**data.yaml**
```yaml
---
 doe: "a deer, a female deer"
```

**yaml.ts**
```ts
import yamlPlugin from "bun-plugin-yaml";

Bun.plugin(yamlPlugin());
```

**bunfig.toml**
```toml
preload = ["./yaml.ts"]
```

Then run:
```bash
bun index.ts
```

### What is the expected behavior?

```bash
a deer, a female deer
```

### What do you see instead?

```bash
SyntaxError: Missing 'default' import in module '/workspaces/test/data.yaml'.
```

### Additional information

This code is running on GitHub Codespaces. I've tried making my own plugin, and it comes with the same error.

**Comment by ghost** [comment]
Will move to new issue, this is a larger bug than I thought.

**Comment by TheCactusBlue** [comment]
Which issue did you move this to? Ran across a similar issue.

**Comment by ghost** [comment]
> Which issue did you move this to? Ran across a similar issue.

Turns out I was using plugins wrong. Here's how you should use them:

**plugin.ts**
```js
import { plugin } from "bun";

await plugin({
  name: "YAML",
  async setup(build) {
    const { load } = await import("js-yaml");

    // when a .yaml file is imported...
    build.onLoad({ filter: /\.(yaml|yml)$/ }, async (args) => {

      // read and parse the file
      const text = await Bun.file(args.path).text();
      const exports = load(text) as Record<string, any>;

      // and returns it as a module
      return {
        exports,
        loader: "object", // special loader for JS objects
      };
    });
  },
});
```

**index.ts**
```js
import { foo } from "./example.yaml";
console.log(foo);
```

**bunfig.toml**
```toml
preload = ["./src/plugin.ts"]
```

Here's the [other issue](https://github.com/oven-sh/bun/issues/7186).
