### ISSUE TITLE
[sqlite] Having multiple `alias.*` in the query maps columns to invalid names

### ISSUE THREAD

**Issue by vsviridov** [oven-sh/bun#7147]
### What version of Bun is running?

1.0.11

### What platform is your computer?

linux x64 `5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### What steps can reproduce the bug?

```js
import Database from "bun:sqlite";

const db = new Database(":memory:");

db.exec("CREATE TABLE foos (foo_id INTEGER NOT NULL PRIMARY KEY, foo_a TEXT, foo_b TEXT)");
db.exec("CREATE TABLE bars (bar_id INTEGER NOT NULL PRIMARY KEY, foo_id INTEGER NOT NULL, bar_a INTEGER, bar_b INTEGER, FOREIGN KEY (foo_id) REFERENCES foos (foo_id))");

db.exec("INSERT INTO foos VALUES (1, 'foo_1', 'foo_2')");
db.exec("INSERT INTO bars VALUES (1, 1, 'bar_1', 'bar_2')");
db.exec("INSERT INTO bars VALUES (2, 1, 'baz_3', 'baz_4')");

const query = db.query("SELECT f.*, b.* FROM foos f JOIN bars b ON b.foo_id = f.foo_id");

const data = query.all();

console.dir(data);
```

### What is the expected behavior?

```js
[
  {
    foo_id: 1,
    foo_a: "foo_1",
    foo_b: "foo_2",
    bar_id: 1,
    bar_a: "bar_1",
    bar_b: "bar_2"
  }, {
    foo_id: 1,
    foo_a: "foo_1",
    foo_b: "foo_2",
    bar_id: 2,
    bar_a: "baz_2",
    bar_b: "baz_3"
  }
]
```

### What do you see instead?

```js
[
  {
    foo_id: 1,
    foo_a: "foo_1",
    foo_b: "foo_2",
    bar_id: 1,
    bar_a: 1,
    bar_b: "bar_1"
  }, {
    foo_id: 1,
    foo_a: "foo_1",
    foo_b: "foo_2",
    bar_id: 2,
    bar_a: 1,
    bar_b: "baz_3"
  }
]
```

### Additional information

Because `foo_id` column is shared in both tables it looks like it's column is skipped over;

If I run the query against sqlite database I get the columns in the correct order, with the column with the same name appearing in the output.

if instead of using a `*` I spell out all columns and alias the repeating column name to a unique name - this doesn't happen.

**Comment by Jarred-Sumner** [comment]
Can you be more specific if this is Linux x64, macOS x64?

**Comment by vsviridov** [comment]
> Can you be more specific if this is Linux x64, macOS x64?

Updated the ticket.

**Comment by Hanaasagi** [comment]
Hi, I think https://github.com/oven-sh/bun/pull/6690 will fix this too, I will update and make some tests tonight.
