### ISSUE TITLE
`setTimeout`, `setInterval`, `setImmediate` are missing promisifed versions

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#7148]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
import { promisify } from "node:util";

const wait = promisify(setTimeout);

await wait(1000);
console.log("Bun");
```

### What is the expected behavior?

I expected to see `Bun` printed out in the console after 1 second

### What do you see instead?

I get both a type error saying that `wait expects 0 arguments` and a runtime error:
![image](https://github.com/oven-sh/bun/assets/80978939/efa79a45-a02b-4680-a634-edf4e378108c)

**Comment by Jarred-Sumner** [comment]
ah we need to implement the special handler for setTimeout specifically

**Comment by Didas-git** [comment]
I think it should be implemented more like node's since `setTimeout` is not the only one that will do this, `setInterval` is another builtin that causes this issues as well and there are probably more

**Comment by Jarred-Sumner** [comment]
yep, we need to do this for all the builtins like this

**Comment by paperdave** [comment]
general path to fixing this is
```

**Comment by paperclover** [comment]
one approach to this is simply adding handling into `util.promisify` to handle these, but this will break if a custom util promisify implementation is used

the approach to adding this symbol is a little in the weeds of jsc but not that deep. ZigGlobalObject.lut.txt contains these defs

```
  setImmediate                    functionSetImmediate                                 Function 1
  setInterval                     functionSetInterval                                  Function 1
  setTimeout                      functionSetTimeout                                   Function 1
```

change these into `PropertyCallback`s

and then manually create a JSFunction with a lazy property with the promisify symbol defined.

logic from Bun.sleep possibly can be copied for the implemtnations of the promisified functions

**Comment by SnowMarble** [comment]
I found promisified `crypto.generateKeyPair` has similar issue. It supposes to return a Promise for an object with publicKey and privateKey, but Bun returns string value of publicKey (please check out the [docs](https://nodejs.org/api/crypto.html#cryptogeneratekeypairtype-options-callback)). I think this also needs to be handled specially.

```js
import crypto from 'node:crypto'
import util from 'node:util'

const generateKeyPairAsync = util.promisify(crypto.generateKeyPair)

const keys = await generateKeyPairAsync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: {
    type: 'spki',
    format: 'pem',
  },
  privateKeyEncoding: {
    type: 'pkcs8',
    format: 'pem',
  },
})

console.log(keys)
console.log(typeof keys) // it expats an object, but the result is string
```

**Comment by paperclover** [comment]
could you open a separate issue to fix `generateKeyPair`, because i specifically want to add the good first issue tag to that.

`src/js/node/crypto.js` has this line

`crypto_exports.generateKeyPair = function ...`

all that needs to be done is add the promisify symbol to that function to return the proper object. this can be done in ~10 lines of js code.

**Comment by evmd** [comment]
Still getting "TypeError: setTimeout expects a function" error on bun 1.0.31

**Comment by SnowMarble** [comment]
@paperdave Sorry for missing your comment😓 I made a new issue for generateKeyPair. #9469

**Comment by evmd** [comment]
Thanks you so much
