### ISSUE TITLE
node builtin readline alternative.

### ISSUE THREAD

**Issue by chiddekel** [oven-sh/bun#715]
### Version

0.1.1

### Platform

Linux fedora 5.18.10-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 7 17:41:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

// this script won't run from terminal after:  bun binarySearch.js
 ```javascript
    const arr = ['a', 'b', 'c', 'x', 'y', 'z'];

    console.log(arr);

    function findeMe(target, start, end) {

    if (start > end) {
        return 'Not Found';
    }

    const middle = Math.floor((start + end) / 2);

    if (arr[middle] === target) {
        return `Found ${arr[middle]} at index ${middle}`;
    }

    if (arr[middle] > target) {
        return findeMe(target, start, middle - 1);
    }

    if (arr[middle] < target) {
        return findeMe(target, middle + 1, end);
    }

    }

    function readInput() {
    
    const promptText = 'What char you looking for?\n';

    const readline = require('readline').createInterface({
        
        input: process.stdin,
        
        output: process.stdout

    });
    
    if (typeof self === 'undefined') return readline.question(promptText, charName => {

        console.info(findeMe(charName, 0, 5));

        readline.close();

    });

    let readPrompot = prompt(promptText);
    
    console.info(findeMe(readPrompot, 0, 5));
    }

    readInput();

```

### What is the expected behavior?

    node binarySearch.js

    [ 'a', 'b', 'c', 'x', 'y', 'z' ]
    What char you looking for?

### What do you see instead?

    bun binarySearch.js

    error: Could not resolve: "readline". Maybe you need to "bun install"?

    const readline = require('readline').createInterface({
                             ^
    .../bun_quericks/binarySearch.js:33:30 611%

**Comment by watzon** [comment]
Related #311

**Comment by xhyrom** [comment]
You can use `prompt()` function

**Comment by chiddekel** [comment]
bun binarySearch.js

     // const readFromCommandline = resolve(argv.at(-1));
 
     // console.log(path.split('/')[5]);
 
     // console.info(findeMe(readFromCommandline.split('/')[5].toString(), 0, 5));
	prompt("test prompt text");
    

     ReferenceError: Can't find variable: prompt

     at readInput

**Comment by FinnRG** [comment]
The problem is, that the underlying `process.stdin` and `process.stdout`aren't implemented yet. As a workaround you can use `Bun.stdin` and `Bun.stdout`. There are some examples in the README.

**Comment by xhyrom** [comment]
> bun binarySearch.js
> 
> ```
>  // const readFromCommandline = resolve(argv.at(-1));
> 
>  // console.log(path.split('/')[5]);
> 
>  // console.info(findeMe(readFromCommandline.split('/')[5].toString(), 0, 5));
> prompt("test prompt text");
> 
> 
>  ReferenceError: Can't find variable: prompt
> 
>  at readInput
> ```

You have old bun version. Run `bun upgrade ` for upgrade. (https://github.com/oven-sh/bun/pull/528)

**Comment by chiddekel** [comment]
> > bun binarySearch.js
> > ```
> >  // const readFromCommandline = resolve(argv.at(-1));
> > 
> >  // console.log(path.split('/')[5]);
> > 
> >  // console.info(findeMe(readFromCommandline.split('/')[5].toString(), 0, 5));
> > prompt("test prompt text");
> > 
> > 
> >  ReferenceError: Can't find variable: prompt
> > 
> >  at readInput
> > ```
> 
> You have old bun version. Run `bun upgrade ` for upgrade. (#528)

So after update prompt will work from cli

**Comment by xhyrom** [comment]
> > > bun binarySearch.js
> > > ```
> > >  // const readFromCommandline = resolve(argv.at(-1));
> > > 
> > >  // console.log(path.split('/')[5]);
> > > 
> > >  // console.info(findeMe(readFromCommandline.split('/')[5].toString(), 0, 5));
> > > prompt("test prompt text");
> > > 
> > > 
> > >  ReferenceError: Can't find variable: prompt
> > > 
> > >  at readInput
> > > ```
> > 
> > 
> > You have old bun version. Run `bun upgrade ` for upgrade. (#528)
> 
> So after update prompt will work from cli

After upgrade you can use `prompt()` function in your code

**Comment by chiddekel** [comment]
Confirm - it work's - after upgrade bun, prompt() run proper on my script.
