### ISSUE TITLE
windows: bun install InvalidArgument when extracting any package

### ISSUE THREAD

**Issue by danielniccoli** [oven-sh/bun#7155]
### What version of Bun is running?

1.0.12-canary.54+904134cc7

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

`bun update`

### What is the expected behavior?

Newlines in the output

### What do you see instead?

![grafik](https://github.com/oven-sh/bun/assets/2971735/dcbc2c53-5900-4117-b723-9ba8e5fdc02d)

**Comment by paperclover** [comment]
i thought the windows branch has bun install disabled because it doesn't work. the real issue is that bun install doesnt work on windows

**Comment by danielniccoli** [comment]
> i thought the windows branch has bun install disabled because it doesn't work. the real issue is that bun install doesnt work on windows

That doesn't change the fact that the error message is printed without newlines.
