### ISSUE TITLE
Changing accidentally installed dependency to dev dependency not possible in 2 steps using bun

### ISSUE THREAD

**Issue by MRDGH2821** [oven-sh/bun#7173]
### What version of Bun is running?

1.0.12+85c997513

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

1. Run - `bun install @types/node`
2. Realise that it was supposed to be installed as dev dependency
3. Run - `bun install @types/node --dev`
4. Package does not go from `[package.json].dependencies` to `[package.json].devDependencies`

### What is the expected behavior?

Package should go from `[package.json].dependencies` to `[package.json].devDependencies` just like how npm does it.

### What do you see instead?

No change in `package.json` even if `--dev` flag is put

### Additional information

The equivalent in npm to move a dependency from `[package.json].dependencies` to `[package.json].devDependencies`

```sh
npm install @types/node
npm install --save-dev @types/node
```

To do in bun:
```
bun install @types/node
bun uninstall @types/node
bun install --dev @types/node
```

My repository - https://github.com/MRDGH2821/Discord-Ban-Utils-Bot/tree/rewrite-sapphire 
Use branch `rewrite-sapphire` and open code in dev container (use VSCode's Dev container feature)

**Comment by Electroid** [comment]
Duplicate of #4852
