### ISSUE TITLE
Failed to find package "@oven/bun-linux-x64-baseline"

### ISSUE THREAD

**Issue by GHNewbiee** [oven-sh/bun#7178]
### What platform is your computer?

Linux 5.15.0-88-generic x86_64 x86_64

### What steps can reproduce the bug?

```bash
sudo npm install -g bun
# or
npm install bun
# or
[sudo] npm install -g -f bun
# or
[sudo] npm install -g --no-optional bun
```

### What is the expected behavior?

Bun to get installed.

### What do you see instead?

```text
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/bun
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Failed to find package "@oven/bun-linux-x64-baseline". You may have used the "--no-optional" flag when running "npm install".
npm ERR! Error: Failed to install package "bun"
npm ERR!     at /usr/lib/node_modules/bun/install.js:311:11
npm ERR!     at Generator.throw (<anonymous>)
npm ERR!     at rejected (/usr/lib/node_modules/bun/install.js:35:27)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by squishyu** [comment]
Try running `sudo npm install -g bun --ignore-scripts`

Then run `cd /usr/lib/node_modules/bun/node_modules/@oven` and check the contents with `ls`  
If you see `bun-linux-x64-baseline`, run `cd ./bun-linux-x64-baseline/bin`
Now try running the bun binary with by running `./bun`

If you get something like:
```sh
/usr/local/lib/node_modules/bun/node_modules/@oven/bun-linux-x64-baseline/bin # ./bun
sh: ./bun: not found
```
Then it's possible this is a duplicate of #5545, in which case you may be missing `glibc`

**Comment by GHNewbiee** [comment]
@squishyu  Tfyr.

It's done up to the point:

```
# Now try running the bun binary with by running ./bun
./bun

# then I get again

Illegal instruction (core dumped)
```

**Comment by Electroid** [comment]
This is the same issue as #7179, and we will fix this.

**Comment by GHNewbiee** [comment]
Hi, 1.0.26 has finally been installed by npm. But still I get `Illegal instruction (core dumped)`.
