### ISSUE TITLE
bun is not working with Dotenv cli

### ISSUE THREAD

**Issue by lefuncq** [oven-sh/bun#7180]
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

I have a package.json with these two commands:
```
  "dev": "dotenv -e ./.env.local -- env",
  "dev:test": "dotenv -e ./.env.test -- env",
```

Inside `.env.local`:
```
CALLER=LOCAL
```
Inside `.env.test`:
```
CALLER=TEST
```

Calling with:
-  `npm run dev` gives `CALLER=LOCAL` on the displayed `env`
-  `npm run dev:test` gives `CALLER=TEST` on the displayed `env`
-  `bun run dev` or `bun dev` gives `CALLER=LOCAL` on the displayed `env`
-  `bun run dev:test` or `bun dev:test` gives `CALLER=LOCAL` on the displayed `env`

Can someone help?

**Comment by bazo** [comment]
me too :)

```
"dev": "dotenv -e ../.env.development -e .env.vite.portal vite -- --host",
```

.env.development
```sh
PORTAL_PORT = 3011
```

.env.vite.portal 
```sh
PORT = $PORTAL_PORT
```

but process.env.PORT is empty string

with yarn this works ok

1.0.15+b3bdf22eb Darwin 23.0.0 arm64 arm

**Comment by lefuncq** [comment]
Hey, Bun now supports `--env-file` when running commands with `bunx`. Worked like a charm for me!

**Comment by MichalPleva8** [comment]
@lefuncq Hey, how does your script looked liked after using `bunx` and `--env-file`?

**Comment by joeyfigaro** [comment]
> @lefuncq Hey, how does your script looked liked after using `bunx` and `--env-file`?

Using `bunx` attempts to git clone the argument passed to `--env-file`. Did you mean `bun`?
