### ISSUE TITLE
Runtime/Bundler Plugins Broken

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#7186]
### What version of Bun is running?

1.0.12+85c997513

### What platform is your computer?

Linux 6.2.0-1016-azure x86_64 x86_64

### What steps can reproduce the bug?

Following the exact steps from the [documentation](https://bun.sh/docs/runtime/plugins#loaders):

**Terminal:**
```bash
$ touch index.ts
$ touch yaml.ts
$ touch data.yml
$ touch bunfig.toml
$ bun add js-yml
```

**index.ts**
```ts
import data from "./data.yml";
console.log(data.name);
```

**yaml.ts**
```ts
import { plugin } from "bun";

plugin({
  name: "YAML",
  async setup(build) {
    const { load } = await import("js-yaml");
    const { readFileSync } = await import("fs");

    build.onLoad({ filter: /.(yaml|yml)$/ }, (args) => {
      const text = readFileSync(args.path, "utf8");
      const exports = load(text) as Record<string, any>;

      return {
        exports,
        loader: "object",
      };
    });
  },
});
```

**data.yml**
```yml
name: Fast X
releaseYear: 2023
```

**bunfig.toml**
```toml
preload = ["./yaml.ts"]
```

**Lastly, run the project:**
```bash
bun index.ts
```

### What is the expected behavior?

```bash
{
  "name": "Fast X",
  "releaseYear": "2023"
}
```

### What do you see instead?

```bash
/workspaces/dough/data.yml
```

### Additional information

Similar errors happen for other plugins - most notably, when creating a plugin, an error comes up about being unable to find the default import for `data.yml`.

This code is running on GitHub Codespaces (2-core).

**Comment by Jarred-Sumner** [comment]
Plugins seem to not be called. The question is why (and also why when we do have tests for this)

**Comment by joy-void-joy** [comment]
Hi,
Is there any progress on this issue or anything that I can do? I'm using a plugin that crashes, and this issue makes it impossible to debug for me

**Comment by ghost** [comment]
Not entirely sure here, but I believe the issue is found somewhere in [BundlerPlugin.ts](https://github.com/oven-sh/bun/blob/main/src/js/builtins/BundlerPlugin.ts). As to what the problem is, I have no idea.

**Comment by ghost** [comment]
After looking further into this, it appears that plugins do indeed work - however, the documented examples don't for some reason. Here's an example of a working one:

**plugin.ts**
```js
import { plugin } from "bun";

await plugin({
  name: "YAML",
  async setup(build) {
    const { load } = await import("js-yaml");
    const { readFileSync } = await import("fs");

    build.onLoad({ filter: /.(yaml|yml)$/ }, (args) => {
      return {
        exports: {
          foo: load(`
name: Fast X
releaseYear: 2023
      `),
        },
        loader: "object",
      };
    });
  },
});
```

**index.ts**
```js
import { foo } from "./example.yaml";
console.log(foo);
```

**bunfig.toml**
```toml
preload = ["./src/plugin.ts"]
```

As useless as the example is, it does work, so this issue is no longer needed.
