### ISSUE TITLE
mock.module() does not work on node_modules, especially with default exports

### ISSUE THREAD

**Issue by JeffreyATW** [oven-sh/bun#7189]
### What version of Bun is running?

1.0.12+85c997513

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

package.json
```
{
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.2",
    "@sendgrid/mail": "^7.7.0"
  }
}
```

mail.test.ts
```
import sgMailOrig from "@sendgrid/mail";
import { createNextState } from "@reduxjs/toolkit";
import { expect, mock, test } from "bun:test";

test("mocks a node module with a default export", async () => {
  mock.module("@sendgrid/mail", () => ({
    default: {
      send: 'foo',
    },
  }));
  const sgMailAgain = await import("@sendgrid/mail");
  expect(sgMailAgain.send).toBe('foo'); // fails
  expect(sgMailAgain.default).toBe(undefined); // fails
  expect(sgMailAgain.default.send).toBe(undefined); // fails
  expect(sgMailOrig.default).toBe(undefined); // passes
  expect(sgMailOrig.send).toBe('foo'); // fails
});

test("mocks a node module with named exports", async () => {
  mock.module("@reduxjs/toolkit", () => ({
    createNextState: 'foo',
  }));
  const { createNextState: createNextStateAgain } = await import("@reduxjs/toolkit");
  expect(createNextStateAgain).toBe('foo'); // passes
  expect(createNextState).toBe('foo'); // fails
});

```

### What is the expected behavior?

I should be able to mock the default export for a node module and immediately access its mock value in both original and re-imports.

I should be able to mock a named export for a node module and immediately access its mock value in both original and re-imports.

### What do you see instead?

I cannot mock the default export of a node module at all.

I can only mock the named export of a node module after re-importing it; the original import remains the same (which makes it useless for testing).

### Additional information

Follow-up of #6884.

**Comment by nfarina** [comment]
I have noticed that module mocking does work but only for dynamic imports not already imported statically. If you remove your `import sgMailOrig from "@sendgrid/mail";` at the top, I'll bet it will work.

It looks like their internal tests only check this case as well (from original implementation in #6685):

  https://github.com/oven-sh/bun/pull/6685/files#diff-33d1285e4f8f34d2d01657e87aebd087f56f332997173a9b63bc0750874d8000R60

Unfortunately it's not helpful for the majority of test writing, as you're usually testing modules that use static imports.

**Comment by Jarred-Sumner** [comment]
I think the real bug here is that `mock.module` was not running the module resolver on the input, which means that it would only mock `@sendgrid/mail` which is only evaluated _after_ the mocked module is loaded at runtime. At runtime, `@sendgrid/mail` is resolved to a file path like `<cwd>/node_modules/@sendgrid/mail/index.js`

The following test passes in #7673 

```js
import sg from "@sendgrid/mail";
import { expect, mock, test } from "bun:test";

test("mocks a node module with a default export", async () => {
  mock.module("@sendgrid/mail", () => ({
    default: {
      send: "foo",
    },
  }));
  const sg2 = await import("@sendgrid/mail");
  expect(sg2.default.send).toBe("foo");
  expect(sg.send).toBe("foo");
});
```
