### ISSUE TITLE
Support `extends` in `tsconfig.json`

### ISSUE THREAD

**Issue by kylecarbs** [oven-sh/bun#72]
When using paths in `tsconfig.json` to reference files in outer directories, the compiler fails to resolve:

```json
{
  "compilerOptions": {
    "paths": {
      "lib/ts/*": ["./lib/ts/*"]
    }
  }
}
```

```
error: Could not resolve: "lib/coderapi/legacy". Maybe you need to "npm install" (or yarn/pnpm)?

import { License, updateLicense } from "lib/coderapi/legacy"
```

**Comment by Jarred-Sumner** [comment]
Have you tried setting [`baseUrl`](https://www.typescriptlang.org/tsconfig#baseUrl)? For example:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "lib/ts/*": ["./lib/ts/*"]
    }
  }
}
```

**Comment by kylecarbs** [comment]
Yup. Our tsconfig.json uses the `extends` property to a higher-level directory... maybe that's the problem?

**Comment by Jarred-Sumner** [comment]
> maybe that's the problem?

Most likely. `extends` is not implemented yet, and won't be a priority for ~a month probably. 

If you try (temporarily) inlining what `extends` would do into the `tsconfig.json`, does that fix it?

**Comment by Jarred-Sumner** [comment]
> to reference files in outer directories

I was wondering if this was the issue, but it doesn't seem to be.

When `above-the-root` references a specific file:
![image](https://user-images.githubusercontent.com/709451/144135968-904d3313-a517-4d33-8ab1-259100258d7f.png)

When `above-the-root` references a folder:
![image](https://user-images.githubusercontent.com/709451/144135213-7bef47e5-81f8-44ce-8251-f1e251a40b63.png)

**Comment by kylecarbs** [comment]
Ahh I appreciate the investigation. I'll update the title/description, or feel free to close if it's already planned.

**Comment by Jarred-Sumner** [comment]
There isn't an issue tracking `extends` support currently, so this can be that issue

**Comment by microsoftly** [comment]
Is this work currently planned? I'd love to integrate this into my repo at work, but we heavily rely on `extends` in `tsconfig`

**Comment by StephenStrickland** [comment]
Jarred, 

Thanks for all the hard work on this incredible tool. I was playing around with converting my nx monorepo to bun and ran into this issue. Where I have a base `tsconfig.json` in the root of my monorepo and my react apps under an `apps` folder that extend from the base. Looking forward to when this issue can be prioritized. Just posting this to help gauge use case and interest. Thanks.

**Comment by yepitschunked** [comment]
Another vote for this issue - we have a frontend monorepo which makes heavy use of extended tsconfigs. We also use custom module resolution, which ought to work via tsconfig `paths`, but the path mapping is defined in some shared/extended config files.

**Comment by dylang** [comment]
Hi! 

Is the difficulty here knowing which values `extends` includes, as well as what value to use when expanding relative paths?

Would porting an existing solution to Zig be a solution to this?
https://github.com/privatenumber/get-tsconfig

Is this project something somebody new to Zig could take on?

Thanks for creating Bun and any insights that could help with this work!

**Comment by joshhansen** [comment]
Excited about Bun, but... also blocked on this!

**Comment by Jarred-Sumner** [comment]
This was added months ago and I forgot to close the issue
