### ISSUE TITLE
TypeError: undefined is not a function when running `fs.cp`

### ISSUE THREAD

**Issue by weilueluo** [oven-sh/bun#7201]
### What version of Bun is running?

1.0.12+85c997513

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. create a directory name `test-dir` with some random files and directories in it.
2. create a file called `test.js` with the following content
	```
	var fs = require('fs');
	await fs.cp('./test-dir', './test-dir-cp', {
	    force: true,
	    recursive: true
	});
	```
3. Run `bun test.js`the 

### What is the expected behavior?

copy properly without error.

### What do you see instead?

copy seems to be successful but an error is thrown:
```
79 |   return fs.cpSync(src, dest, options.recursive, options.errorOnExist, options.force ?? !0, options.mode);
80 | }, cp = function(src, dest, options, callback) {
81 |   if (typeof options === "function")
82 |     callback = options, options = @undefined;
83 | 
84 |   promises.cp(src, dest, options).then(() => callback(), callback);
                                                                                 ^
TypeError: undefined is not a function
      at node:fs:84:78
```

**Comment by Hanaasagi** [comment]
Hi, I think you need `fs.Promises`.

```javascript
var { promises: fs } = require("fs");
await fs.cp("./test-dir", "./test-dir-cp", {
  force: true,
  recursive: true,
});

```

Ref:
- https://nodejs.org/api/fs.html#fspromisescpsrc-dest-options
- https://nodejs.org/api/fs.html#fscpsrc-dest-options-callback

**Comment by weilueluo** [comment]
Ah right, indeed, thank you 👍

**Comment by Hanaasagi** [comment]
Btw, Node.js will check if `callback` is a function first, and if it fails, it will throw an error directly without any file copy. I think here we should check if `callback` is `undefined`, just like what node does.


https://github.com/oven-sh/bun/blob/f5bf67bd1be516bedc9650f6630883c19dff6063/src/js/node/fs.js#L1201-L1207

Node.js: https://github.com/nodejs/node/blob/a628ddaf9e9adce3088e7913a21bdea9c04852a7/lib/fs.js#L3027
