### ISSUE TITLE
[Bun.serve] EADDRINUSE is not thrown when running with `--hot`

### ISSUE THREAD

**Issue by MonsterDeveloper** [oven-sh/bun#7207]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Linux 6.1.43 x86_64 unknown

### What steps can reproduce the bug?

1. Create a file `http.ts` with the following code:
```ts
Bun.serve({
  port: 3000,
  fetch() {
    return new Response("123");
  },
});

Bun.serve({
  port: 3000,
  fetch() {
    return new Response("456");
  },
});

```
2. Run the file with `bun --hot ./http.ts`

[CodeSandbox link](https://codesandbox.io/p/sandbox/dank-frost-mspy45?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp47iqth00083b6ehniawzlp%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp47iqth00033b6euqoutmjh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp47iqth00053b6eurf76y77%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp47iqth00073b6elqqyys8g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp47iqth00033b6euqoutmjh%2522%253A%257B%2522id%2522%253A%2522clp47iqth00033b6euqoutmjh%2522%252C%2522activeTabId%2522%253A%2522clp47mc8200s43b6ec7z0sq3h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp47iqth00023b6edzaifwoo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.devcontainer%252FDockerfile%2522%252C%2522id%2522%253A%2522clp47k4uo00b23b6ellzlrnvt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fhttp.ts%2522%252C%2522id%2522%253A%2522clp47mc8200s43b6ec7z0sq3h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp.ts%2520%28DELETED%29%2522%252C%2522id%2522%253A%2522clp47rin001ca3b6eyjy0odc9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2520%28DELETED%29%2522%252C%2522id%2522%253A%2522clp48m45a00yp3b6eymn96dgr%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clp47iqth00073b6elqqyys8g%2522%253A%257B%2522id%2522%253A%2522clp47iqth00073b6elqqyys8g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp47iqth00063b6edsf3hide%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp48dvlx02ro3b6e0g5rxpr2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp48dvlx02ro3b6e0g5rxpr2%2522%257D%252C%2522clp47iqth00053b6eurf76y77%2522%253A%257B%2522id%2522%253A%2522clp47iqth00053b6eurf76y77%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp47iqth00043b6e0kyhkf8n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Start%2522%257D%252C%257B%2522id%2522%253A%2522clp47mytz00xz3b6epqykqqoc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp47myvo0013eegm2y177hp2%2522%257D%252C%257B%2522id%2522%253A%2522clp486sv902am3b6emm7k39gh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp48pkoh001eeegm3ykk1w9h%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp486sv902am3b6emm7k39gh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### What is the expected behavior?

Should throw an error `EADDRINUSE`, like the one on the screenshot below.

![CleanShot 2023-11-18 at 17 11 49](https://github.com/oven-sh/bun/assets/16190582/f4cb0a44-cac0-4d34-9a06-17b1da7c3784)

### What do you see instead?

Bun runs 2 server instances on the same port, but the first instance is overridden: the request is handled but the second instance of `Bun.serve`.

### Additional information

Running the server without `--hot` (i.e. `bun ./http.ts`) throws an error as expected.

**Comment by Electroid** [comment]
This is an intended side-effect of using `--hot`. When `Bun.serve` is called, we generate a "server ID" using the `hostname` + `port`, or using a `id` property if defined. If you want two distinct servers, you'll need to specify an `id`, like so:

```diff js
Bun.serve({
+  id: "a",
  port: 3000,
  fetch() {
    return new Response("123");
  },
});

Bun.serve({
+  id: "b",
  port: 3000,
  fetch() {
    return new Response("456");
  },
});
```

**Comment by MonsterDeveloper** [comment]
Thanks. Although I intend *not* to run 2 servers simultaneously.

I had an HTTP server running somewhere in the background (which I forgot about), and when I started another process, Bun didn't throw an error so I didn't know I already had another instance running. I spent some time debugging why my server wasn't accepting requests after realizing they were sent to an older instance.

**Comment by Electroid** [comment]
If you specify different `id`s, and they use the same port, it should throw `EADDRINUSE`.

**Comment by MonsterDeveloper** [comment]
The thing is, I only had 1 `Bun.serve` call in the source file.

I had a process running this file already, and when I started another one — it didn't throw. So I thought only 1 process was running but in fact I had 2 servers on the same port, and Bun didn't say a thing.

My example in the issue is just for the sake of simplicity. So I had: 1 source file with 1 `Bun.serve`, but 2 processes with `--hot` flag running it.
