### ISSUE TITLE
bun --bun run dev exits with SIGILL

### ISSUE THREAD

**Issue by szwenni** [oven-sh/bun#7211]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

It is hard to explain how exactly to reproduce it because I have no idea where exactly it crashes.

The setup is a bigger nuxt 3 project which I want to migrate to use bun.

Installation works out, but when I try to do the run dev it crashes with SIGILL. With node everything is working.

I would have stepped deeper in to debugging but don't even know where to start. LLDB is not able to attach so I can not figure out which instruction at all is causing the crash.

The SIGILL is created after everything is built and the server should start serving.

### Additional information

- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2

**Comment by Jarred-Sumner** [comment]
SIGILL on an arm64 mac. Very interesting. I wonder how this happens. My guess is it’s a bug in either our usage of DOMJIT or a bug in JSC itself

**Comment by szwenni** [comment]
Like said I would love to give you a core dump or at least some stack trace, but I think the only way is to build it by myself and then let it run again and try to attach lldb to it to get a stack trace ?

**Comment by szwenni** [comment]
while going through contribution setup, I remarked one thing
This `export PATH="$PATH:$(brew --prefix llvm@16)/bin"` should be changed to
`export PATH="$(brew --prefix llvm@16)/bin:$PATH"`
Otherwise it might pickup the wrong version of clang still and output
`LLVM 16 is required. Detected CXX as '/usr/bin/clang++'`

**Comment by szwenni** [comment]
and one more, using bun to install zig leads to the wrong version, only with zigup you are getting the correct one

**Comment by szwenni** [comment]
okay so built bun and now using bun-debug the last thing it does is
`[fs] openat(2147483647, /Users/user/Projects/bunHome/project/node_modules/jiti/dist/babel.js) = 290
error: script "dev" exited with code 4 (SIGILL)
Process 94829 exited with status = 1 (0x00000001)`

hopes this helps somehow, I can not really figure out why and where exactly this is happening

**Comment by szwenni** [comment]
Sadly I'm not able to get a Debug WebKit version running with bun. It crashes right now directly with a Segfaul. Maybe you can help me how to exactly build bun against a Debug WebKit version (if this even helps to see more details for this)

**Comment by Jarred-Sumner** [comment]
We can't reproduce this, but please let us know if you still run into this and I'll re-open
