### ISSUE TITLE
react query + trpc does not work with bun

### ISSUE THREAD

**Issue by knajjars** [oven-sh/bun#7219]
### What version of Bun is running?

v1.0.13

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Follow the steps to setup a basic react app with TRPC and react-query, I am using Vite for what is worth.

https://trpc.io/docs/client/react/setup

### What is the expected behavior?

It should work when running the react app, I tried installing the node_modules with `npm` and `pnpm` and it worked fine, it just fails when I install them with `bun`

### What do you see instead?

I see the following error:

```
Property '#private' is missing in type 'import("/Users/<user>/my_project/node_modules/@tanstack/query-core/build/lib/queryClient").QueryClient' but required in type 'import("/Users/<user>/my_project/node_modules/@trpc/react-query/node_modules/@tanstack/react-query/node_modules/@tanstack/query-core/build/modern/queryClient-13f81fcb").b'.ts(2741)
queryClient-13f81fcb.d.ts(897, 5): '#private' is declared here.
context.d.ts(49, 5): The expected type comes from property 'queryClient' which is declared here on type 'IntrinsicAttributes & TRPCProviderProps<CreateRouterInner<RootConfig<{ ctx: object; meta: object; error Shape: DefaultErrorShape; transformer: DefaultDataTransformer; }>, { ...; }>, unknown>'
```

![Screenshot 2023-11-19 at 11 23 10 AM](https://github.com/oven-sh/bun/assets/19353218/08b3cb74-c771-4e9f-bcc5-158008ae9462)

### Additional information

My setup is in a monorepo.

- packages/
   - myPackages
- apps/
  - myApps
- bun.lockb

I install dependencies from the root `bun install` and I get a single `node_modules`

**Comment by Jarred-Sumner** [comment]
Why'd you close it?
