### ISSUE TITLE
Illegal hardware instruction (core dumped)

### ISSUE THREAD

**Issue by c4mpos** [oven-sh/bun#722]
### Platform

Linux dev 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

curl https://bun.sh/install | bash
source ~/.zshrc
bun -v

### What do you see instead?

$ curl https://bun.sh/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5046    0  5046    0     0  17280      0 --:--:-- --:--:-- --:--:-- 17280
######################################################################## 100,0%
bun was installed successfully to /home/user/.bun/bin/bun
bash: line 170: 119921 Illegal instruction     (core dumped) IS_BUN_AUTO_UPDATE="true" SHELL="zsh" $exe completions > /dev/null 2>&1

 Added "/home/user/.bun/bin" to $PATH in "~/.zshrc"

To get started, run

   exec /usr/bin/zsh
   bun --help

$ source ~/.zshrc
$ bun -v                            
[1]    121012 illegal hardware instruction (core dumped)  bun -v

**Comment by xhyrom** [comment]
Related: https://github.com/oven-sh/bun/issues/67

**Comment by FinnRG** [comment]
Duplicate of #67,
