### ISSUE TITLE
Bun inspector fails to load when ran inside a docker container

### ISSUE THREAD

**Issue by TiesDO** [oven-sh/bun#7225]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Linux 6.2.6-76060206-generic x86_64 x86_64

### What steps can reproduce the bug?

# What i'm trying
I want to debug my bun application inside of it's docker container using the `--inspect` flag, since it communicates with quite a few other services running in containers as well.

# Reproduce

1) Create a fresh bun project

```
$ bun init
$ tree -L 1
.
├── README.md
├── bun.lockb
├── index.ts
├── node_modules
├── package.json
└── tsconfig.json
```

2) Create a serve example as illustrated on the [bun homepage](https://bun.sh/)
update the **index.ts** file
```ts
const server = Bun.serve({
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
});

console.log(`Listening on localhost:${server.port}`);
```

3) Then create the Dockerfile as stated on the [oven/bun image](https://hub.docker.com/r/oven/bun)
```
$ echo "FROM oven/bun:latest

COPY package.json ./
COPY bun.lockb ./
COPY index.ts ./

RUN bun install" >> Dockerfile
```

4) Build and run the docker image exposing the 6449 port and starting the app with the `--inspect` flag
```
$ docker build -f Dockerfile -t bun-inspect-test .
$ docker run -p 6449:6449 bun-inspect-test bun run --inspect index.ts
--------------------- Bun Inspector ---------------------
Listening:
  ws://localhost:6499/7qlw3x8qgku
Inspect in browser:
  https://debug.bun.sh/#localhost:6499/7qlw3x8qgku
--------------------- Bun Inspector ---------------------
Listening on localhost:3000
```

5) click the link to see an empty inspector UI
![image](https://github.com/oven-sh/bun/assets/118288338/fff529bc-699d-48d4-847f-c479cd7b4706)

![image](https://github.com/oven-sh/bun/assets/118288338/0f46b82e-3add-4761-b9be-3e97d417dc6d)

**When opening the inspector tab inside the browser**
![image](https://github.com/oven-sh/bun/assets/118288338/917f1867-3bc7-4942-ac1f-d66e30b5e7b4)

### What is the expected behavior?

I expect to see the my console output and sources

### What do you see instead?

An empty UI and errors in my browsers console

### Additional information

Some more (possibly) relevant versions

```
tiesdenouden@pop-os ~/P/bun-inspector-bug> docker run -p 6449:6449 bun-inspect-test bun --revision                                  
1.0.13+f5bf67bd1
tiesdenouden@pop-os ~/P/bun-inspector-bug> docker run -p 6449:6449 bun-inspect-test uname -mprs
Linux 6.2.6-76060206-generic x86_64 unknown
tiesdenouden@pop-os ~/P/bun-inspector-bug> docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- The inpector UI connects and functions as intended when running the program outside of the docker container
- To get the node inspector working inside docker I always run `--inspect=0.0.0.0`, but bun then provides the following link `https://debug.bun.sh/#0.0.0.0:6499/undefined`

**Comment by Hanaasagi** [comment]
Hi, it listens on `localhost:6499` by default. If this process is running inside a container, due to the Linux network namespace isolation, even with port mapping, it cannot be accessed. There are two solutions.

#### 1) Bind `0.0.0.0`

```
>>​ docker run -p 6499:6499  bun-inspect-test bun run --inspect=0.0.0.0:6499 index.ts
--------------------- Bun Inspector ---------------------
Listening:
  ws://0.0.0.0:6499/922lv81lnft
Inspect in browser:
  https://debug.bun.sh/#0.0.0.0:6499/922lv81lnft

```

Then visit `https://debug.bun.sh/#localhost:6499/922lv81lnft` (NOTE: replace `0.0.0.0` to `localhost`)


#### 2) `--net host`

I'm not sure if this is supported on macOS, but on Linux, you can directly use the host machine's namespace through `--net host`.


----

> To get the node inspector working inside docker I always run --inspect=0.0.0.0, but bun then provides the following link https://debug.bun.sh/#0.0.0.0:6499/undefined

`undefined` seems here.


https://github.com/oven-sh/bun/blob/ef8b9efaa4bec9780323bd203a6c7905a5e086ce/src/js/internal/debugger.ts#L279-L281

**Comment by TiesDO** [comment]
Thank you for the quick reply, however I still cannot get it to work. 

I ran the command as you instructed (adding `0.0.0.0:6499`) and it gave me the expected output:

```
$ docker run -p 6499:6499  bun-inspect-test bun run --inspect=0.0.0.0:6499 index.ts
--------------------- Bun Inspector ---------------------
Listening:
  ws://0.0.0.0:6499/k9d26433xv
Inspect in browser:
  https://debug.bun.sh/#0.0.0.0:6499/k9d26433xv
--------------------- Bun Inspector ---------------------
Listening on localhost:3000
```

Then when I open the link and swap 0.0.0.0 to localhost I still get the following error:

![image](https://github.com/oven-sh/bun/assets/118288338/2edb452f-f1f0-4928-b69b-55ffc7f98f55)

---

I'll look into your `--net host` suggestion as well, and hopefully get something to work :)

# Edit

I just went to get coffee, and when I came back tried it with `127.0.0.1` paired with a hard refresh in my browser and it worked!

**Comment by Electroid** [comment]
Closing since `127.0.0.1` is intentional. We'll fix the other issue in the linked PR.
