### ISSUE TITLE
`length` field is sometimes excluded from console.log when it shouldn't be

### ISSUE THREAD

**Issue by trylovetom** [oven-sh/bun#7230]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

```js
// sample.js
console.log({ score: 10, length: 10 })
console.log({ length: 10 })
```

### What is the expected behavior?

```sh
node run sample.js
{ score: 10, length: 10 }
{ length: 10 }
```

### What do you see instead?

```sh
bun run sample.js
{ score: 10 }
{ length: 10 }
```

**Comment by Jarred-Sumner** [comment]
The bug here is that `length` is being excluded (and that is definitely a bug), but having precisely the same object logging output is not a goal

**Comment by trylovetom** [comment]
@Jarred-Sumner Thank you for your response. Bun is really great and I am also hoping to join this community. Could you give me a chance to try and fix this bug? Please point out the module that might be problematic, so that I can more easily locate it. Thank you.
