### ISSUE TITLE
Segfault when running bun install on macOS with custom npm registry

### ISSUE THREAD

**Issue by weyert** [oven-sh/bun#724]
### Version

0.1.4

### Platform

Darwin MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

1. Update bun config file to use `@company`-scope from Gitlab Private NPM registry by using the instance-wide registry (e.g. )
2. Attempt to install packages via `bun install` in a project that uses a mixture of packages from public NPM registry and the private NPM registry
3. Notice the following segfault:
```
❯ bun install --verbose

SegmentationFault at 8588209949584348463


–––– bun meta ––––
Bun v0.1.4 macOS Silicon 21.5.0
InstallCommand: bunfig
Elapsed: 3ms | User: 2ms | Sys: 3ms
RSS: 22.84MB | Peak: 22.84MB | Commit: 69.22MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```
4. Remove the `@company`-config from the bun config file
5. Run `bun install --verbose` again
6. Notice that it complains about it unable to find the `@company`-packages in public NPM registry

### How often does it reproduce? Is there a required condition?

Every time it fails, when I remove the npm registry configuration from bun config file it passes but it fails for unable to find the `@tapico/*`-packages in the public NPM registry

### What is the expected behavior?

I would expect to be able install packages via `bun install` when using private NPM registry like Gitlab's

### What do you see instead?

```
❯ bun install --verbose

SegmentationFault at 8588209949584348463


–––– bun meta ––––
Bun v0.1.4 macOS Silicon 21.5.0
InstallCommand: bunfig
Elapsed: 3ms | User: 2ms | Sys: 3ms
RSS: 22.84MB | Peak: 22.84MB | Commit: 69.22MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

### Additional information

Related to this bug in Gitlab you need to define the registry URL for each project that has published the package otherwise you might get 404s or 403 errors returned by the Gitlab NPM private registry.

I am not sure how I can configure something like below with bun config file, shown below is the current project's `.npmrc`-file:

```
//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project1/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project2/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project3/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project4/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project5/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project6/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project7/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project8/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project9/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project10/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/projects/project11/packages/npm/:_authToken=${CI_JOB_TOKEN}
//gitlab.com/api/v4/packages/npm/:always-auth=true
@company:registry=https://gitlab.com/api/v4/packages/npm/
legacy-peer-deps=true
engine-strict=false
unsafe-perm=true
```

at the moment I only tied the following:

```
[install.scopes]
"@company" = { token = $CI_JOB_TOKEN, url = "https://gitlab.com/api/v4/packages/npm/" }
```

where the shell has the environment variable `CI_JOB_TOKEN` defined

**Comment by afonsoduarte** [comment]
This seems like a duplicate of https://github.com/oven-sh/bun/issues/190. I suggest you close this issue and follow that one instead.

**Comment by weyert** [comment]
Closing this ticket by advise of @afonsoduarte
