### ISSUE TITLE
Bun not working with Prismic and Nuxt security

### ISSUE THREAD

**Issue by mohdlatif** [oven-sh/bun#7244]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 6.2.0-1015-aws x86_64 x86_64

### What steps can reproduce the bug?

Version
"nuxt": "^3.8.0",
"nuxt-security": "^1.0.0-rc.4",
"@nuxtjs/prismic": "^3.0.0"

Reproduction Link
Steps to reproduce
when running bun --bun run dev

the server crashed with the following code

```
Nuxt 3.8.1 with Nitro 2.7.2                                                                         11:05:54 PM
                                                                                                    11:05:55 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                               nuxt:tailwindcss 11:05:57 PM
ℹ Using default preview page, available at /preview                                   nuxt:prismic 11:05:57 PM
ℹ Tailwind Viewer: http:/localhost:3000/_tailwind/                                nuxt:tailwindcss 11:05:57 PM
ℹ Vite server warmed up in 5503ms                                                                  11:06:06 PM
✔ Nitro built in 1317 ms                                                                     nitro 11:06:07 PM
ℹ Vite client warmed up in 7864ms                                                                  11:06:08 PM
error: script "dev" exited with code 11 (SIGSEGV)
```

by using npm run dev it worked

### Additional information

as requested by [Jarred-Sumner](https://github.com/Jarred-Sumner) at https://github.com/Baroshem/nuxt-security/issues/294#issuecomment-1813706434

**Comment by Jarred-Sumner** [comment]
I think this was fixed in https://github.com/oven-sh/bun/pull/11635 and https://github.com/oven-sh/bun/pull/11494,

I'm going to close this for now, but please give it a try in Bun v1.1.13 and let us know if you run into any issues and we'll re-open
