### ISSUE TITLE
Buffer.from doesn't accept png as base64 format

### ISSUE THREAD

**Issue by CeebDev** [oven-sh/bun#7245]
### What version of Bun is running?

1.0.13

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
const myImage = Buffer.from("data:image/png;base64,iVBORw......", "base64")
```

### What is the expected behavior?

Parse the image and create buffer from base64 png

### What do you see instead?

```
error: Unsupported image type
 code: "InvalidArg"
```

**Comment by Jarred-Sumner** [comment]
This isn't a bug in Bun, but a little confusing Node.js API. 

- `data:.*;base64` URLs are `base64url`-encoded, not `base64`
- `data:` as a prefix not supported directly by `Buffer.from`. You must paste the contents after the `data:${header}` prefix, `ivBORw`...

The [`data-uri-to-buffer`](https://www.npmjs.com/package/data-uri-to-buffer) package might be what you're looking for.
