### ISSUE TITLE
unable to --watch on WSL docker desktop

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#7249]
### What is the problem this feature would solve?

when I build my container based on Bun image, I can't get the benefits of `--watch` nor `--hot`
and that's the only reason, I'm not using Bun when developing my projects

### What is the feature you are proposing to solve the problem?

allowing us **docker developers** to use `--watch` and `--hot`!

**Comment by Electroid** [comment]
Duplicate of #5841

**Comment by Bader-Idris** [comment]
I know it's duplicate, but I'm invoking a little action to remind you of it 🙂
