### ISSUE TITLE
[Regression] Update from 1.0.9 to 1.0.10 break fastify cors preflight

### ISSUE THREAD

**Issue by AdamSGit** [oven-sh/bun#7250]
### What version of Bun is running?

1.0.13

### What platform is your computer?

Macos 16.6 (Darwin 22.6.0 arm64 arm)

### What steps can reproduce the bug?

Before upgrading bun to 1.0.13, It was on 1.0.7 and was working smoothly.

After upgrade, the fastify cors preflight OPTIONS requests are broken, and return the following : 
```json
{
  "statusCode": 404,
  "code": "FST_ERR_NOT_FOUND",
  "error": "Not Found",
  "message": "Not Found"
}
```

Please note than it works with nodejs, as well as previous version of bun, so I'm quite confident that its a regression caused by bun upgrade. Reproduction sample : 

Package.json setup : 
```json
...
"scripts": {
    "start": "bun --watch main.js"
},
"dependencies": {
    "fastify": "^4.0.0",
    "@fastify/cors": "^8.0.0"
},
...
```

main.js
```js
// Importing Fastify and CORS plugin
import Fastify from 'fastify'
import cors from "@fastify/cors"

// Create a Fastify instance
const fastify = Fastify()

// Register CORS plugin
fastify.register(cors, { 
  origin: true
})

// Declare a route
fastify.get('/', async (request, reply) => {
  return { message: 'Hello World' }
})

// Run the server
const start = async () => {
  try {
    await fastify.listen({ port: 3000 })
    console.log(`Server listening on ${fastify.server.address().port}`)
  } catch (err) {
    fastify.log.error(err)
    process.exit(1)
  }
}

start()
``` 

`bun run start`

### What is the expected behavior?

OPTIONS requests working as expected

### What do you see instead?

See above

**Comment by AdamSGit** [comment]
Update : I tested with each version from `1.0.7` up to `1.0.13`, and the issue happend when switching from the `1.0.9` the `1.0.10` 

So, the `1.0.10` seem to be the good candidate for the regression. Let me know If I can help further. I would like to look into it, but I'm not familiar with bun codebase, and I don't Zig.

**Comment by Chrysochrome** [comment]
Same as me, and I've created a minimal reproducible code repository at [https://github.com/Chrysochrome/fastify-bun-bug](https://github.com/Chrysochrome/fastify-bun-bug), hope it helps.

**Comment by AdamSGit** [comment]
Nice, thanks. I kind of have a vague feeling that it may be related to `find-my-way`, the http router package that fastify use as a dependencie, more than fastify in itself. I will try to conduct more tests to narrow down the issue as much as I can.

**Comment by AdamSGit** [comment]
I have more elements about this : `http` module pass req `method` property in uppercase.
For an unknown reason, with `1.0.10` bun version, http module seem to keep passing method as uppercase, but not `options` which become lowercase. `find-my-way` stores routes in a variable `this.trees` which contain uppercase http methods properties, and so all `OPTIONS` routes are broken.

Does it ring any bell @Jarred-Sumner and @dylan-conway ? (Pinged you both because regression probably is in one of your commits in the [1.0.10 merge](https://github.com/oven-sh/bun/compare/bun-v1.0.9...bun-v1.0.10))

**Comment by patriksimms** [comment]
I can confirm that this is still an issue in 1.0.17. 

Is this beeing work?

**Comment by asomethings** [comment]
Use below example until the PR is merged

```typescript
const defaultRoute = app.getDefaultRoute()
app.setDefaultRoute((req, res) => {
  if (req.method === 'options') {
    req.method = 'OPTIONS'
  }

  defaultRoute(req, res)
})
```
