### ISSUE TITLE
`bun build --target node` doesnt output .mjs file

### ISSUE THREAD

**Issue by noahehall** [oven-sh/bun#7252]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Linux 6.2.0-36-generic x86_64 x86_64

### What steps can reproduce the bug?

- add this to a random package.json.scripts:

> "build": "for runtime in bun browser node; do bun build --entrypoints ./src/index.ts --outdir ./build/${runtime} --target ${runtime} --external bun:jsc; done;",

- check `./build/node` and theres a `.js` file

![image](https://github.com/oven-sh/bun/assets/10324554/108a8fbe-5ef9-4217-b009-567003d39aea)

### What is the expected behavior?

- build/node dir has a `index.mjs` file

### What do you see instead?

- build/node dir has a `index.js` file

### Additional information

- [according to the docs](https://bun.sh/docs/bundler#target)

For generating bundles that are intended to be run by Node.js. Prioritizes the "node" export condition when resolving imports, **and outputs .mjs**

**Comment by Jarred-Sumner** [comment]
you can use `--outfile=index.mjs`

**Comment by isaachinman** [comment]
@Jarred-Sumner This is still not working via the `Bun.build` method. I'm on v1.1.3. Outfile is not an option there.

Also, for anyone specifying `outdir` to use sourcemaps, the `outfile` option is ignored. This needs to be fixed properly.

**Comment by adeherysh** [comment]
try this `--entry-naming \[dir\]/\[name\].mjs`

**Comment by markledwich2** [comment]
it says in the doco that targeting node will generate mjs
https://bun.sh/docs/bundler#target

> For generating bundles that are intended to be run by Node.js. Prioritizes the "node" export condition when resolving imports, and outputs .mjs

**Comment by JacobMillward** [comment]
Can confirm that this is _still_ an issue on `1.2.7`

**Comment by barclayd** [comment]
Still an issue on `1.2.16` with `outfile` or `target=node` not producing a `.mjs` file
