### ISSUE TITLE
Bun not installing in Ubuntu 20 lts

### ISSUE THREAD

**Issue by hashirnouman** [oven-sh/bun#726]
### What steps will reproduce the bug?

open terminal using ctrl+alt+t 
type curl https://bun.sh/install | bash
error persists even if sudo keyword is added before bash or curl

### What do you see instead?

Warning: Failed to open the file /home/qazi/.bun/bin/bun.zip: Permission      
Warning: denied
                                                                           0.0%curl: (23) Failure writing output to destination

error: Failed to download bun from https://github.com/Jarred-Sumner/bun-releases-for-updater/releases/latest/download/bun-linux-x64.zip

**Comment by xhyrom** [comment]
try `sudo curl https://bun.sh/install | sudo bash`

**Comment by mikrosystheme** [comment]
@xHyroM I wouldn't give people the advice to use `sudo` when downloading and executing a script from the internet.

**Comment by hashirnouman** [comment]
I tried @xHyroM but same error

**Comment by xhyrom** [comment]
You can still try manually. In ~/ you create a .bun/bin in which you put the binary file `bun` from the zip you downloaded via Github Releases. Then you just add bun to the path.

**Comment by akomm** [comment]
-check permissions of ~/.bun and ~/.bun/bin 
-also check if it even exists or creating it failed. 
-You might want to remove to `rm -rf ~/.bun` and try again. 

The install command should work without sudo. If you sudo it, it will be created as root user and you might lack ownership and will need to sudo always. Its installed intentionally in signed in user's folder.

If doing the above does not fix, try create the directory ./bun/bin manually, again without sudo and then run the install.

**Comment by xhyrom** [comment]
If not resolved, reopen issue.

**Comment by MazeofIth** [comment]
I still have this issue. I've tried creating the directory /.bun/bin, checked the permissions for the file /.bun/bin/bun.zip, and tried to run the install script with sudo: `sudo curl https://bun.sh/install | sudo bash` (and everything akomm said). I'm on Ubuntu 21.10. The error I get is: 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5649    0  5649    0     0  64847      0 --:--:-- --:--:-- --:--:-- 64931
Warning: Failed to open the file /home/elias/.bun/bin/bun.zip: Permission     
Warning: denied
curl: (23) Failure writing output to destination

error: Failed to download bun from "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
```

**Comment by xhyrom** [comment]
Try download it manually from GH releases, you have broken permissions.

**Comment by deniskipeles** [comment]
> I still have this issue. I've tried creating the directory /.bun/bin, checked the permissions for the file /.bun/bin/bun.zip, and tried to run the install script with sudo: `sudo curl https://bun.sh/install | sudo bash` (and everything akomm said). I'm on Ubuntu 21.10. The error I get is:
> 
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  5649    0  5649    0     0  64847      0 --:--:-- --:--:-- --:--:-- 64931
> Warning: Failed to open the file /home/elias/.bun/bin/bun.zip: Permission     
> Warning: denied
> curl: (23) Failure writing output to destination
> 
> error: Failed to download bun from "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
> ```

Upon further investigation, I identified the root cause of my issue, which was related to the `curl` utility. To resolve the problem and ensure everything works correctly, I performed the following steps:

### 1. Uninstall Snap Curl
I realized that the issue stemmed from the `curl` utility installed via Snap. To address this, I uninstalled the Snap version of `curl` using the appropriate Snap package management commands. This ensured that any potential conflicts with the Snap version were eliminated.

### 2. Install Apt Curl
After removing the Snap version, I installed the `curl` utility using `apt` (the package manager for Debian-based distributions like Ubuntu). To do this, I executed the following command with administrative privileges:
```bash
sudo apt install curl
```
This command installed the `curl` utility from the official repository, ensuring a clean and compatible installation.

### 3. Execute bun.sh Installation
Finally, I executed the following command to install the desired program or package:
```bash
sudo curl https://bun.sh/install | sudo bash
```
By following these steps, I successfully resolved the issue related to `curl` and ensured that my system was using the `curl` version provided by `apt`. This solution should help ensure the proper functioning of related processes and commands.

**Comment by Hassan-bai** [comment]
Windows 11 encountered the following issue when using Chocolate installation.   May I ask how to solve it?

bun not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Failures
 - bun - bun not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

**Comment by leofgiam** [comment]
> > I still have this issue. I've tried creating the directory /.bun/bin, checked the permissions for the file /.bun/bin/bun.zip, and tried to run the install script with sudo: `sudo curl https://bun.sh/install | sudo bash` (and everything akomm said). I'm on Ubuntu 21.10. The error I get is:
> > ```
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> > 100  5649    0  5649    0     0  64847      0 --:--:-- --:--:-- --:--:-- 64931
> > Warning: Failed to open the file /home/elias/.bun/bin/bun.zip: Permission     
> > Warning: denied
> > curl: (23) Failure writing output to destination
> > 
> > error: Failed to download bun from "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
> > ```
> 
> I realize my problem was curl. **uninstall snap curl and install the apt curl** and everything will work fine

THIS! Saved me. Thank you so much.

**Comment by jakobbak** [comment]
> > > I still have this issue. I've tried creating the directory /.bun/bin, checked the permissions for the file /.bun/bin/bun.zip, and tried to run the install script with sudo: `sudo curl https://bun.sh/install | sudo bash` (and everything akomm said). I'm on Ubuntu 21.10. The error I get is:
> > > ```
> > >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > >                                  Dload  Upload   Total   Spent    Left  Speed
> > > 100  5649    0  5649    0     0  64847      0 --:--:-- --:--:-- --:--:-- 64931
> > > Warning: Failed to open the file /home/elias/.bun/bin/bun.zip: Permission     
> > > Warning: denied
> > > curl: (23) Failure writing output to destination
> > > 
> > > error: Failed to download bun from "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"
> > > ```
> > 
> > 
> > I realize my problem was curl. **uninstall snap curl and install the apt curl** and everything will work fine
> 
> THIS! Saved me. Thank you so much.

Hello Moly! This worked for me too.
Just assumed snap curl was a higher version and Ubuntu had started using that one instead.
Upon uninstalling the snap version of curl, installing it instead with apt, and logging in and out again, the installation script worked.

**Comment by deniskipeles** [comment]
> Windows 11 encountered the following issue when using Chocolate installation. May I ask how to solve it?
> 
> bun not installed. The package was not found with the source(s) listed. Source(s): 'https://community.chocolatey.org/api/v2/' NOTE: When you specify explicit sources, it overrides default sources. If the package version is a prerelease and you didn't specify `--pre`, the package may not be found. Please see https://docs.chocolatey.org/en-us/troubleshooting for more assistance.
> 
> Failures
> 
> * bun - bun not installed. The package was not found with the source(s) listed.
>   Source(s): 'https://community.chocolatey.org/api/v2/'
>   NOTE: When you specify explicit sources, it overrides default sources.
>   If the package version is a prerelease and you didn't specify `--pre`,
>   the package may not be found.
>   Please see https://docs.chocolatey.org/en-us/troubleshooting for more
>   assistance.

I encountered a similar issue, and I found a solution that worked for me. My solution involved enabling the Linux Subsystem on Windows, installing Arch Linux from the Microsoft Store, and then running a specific command to successfully install a program or package.

Here are the steps I followed:

1. **Enable Linux Subsystem:**
   - I first enabled the Linux Subsystem on my Windows machine. This is necessary to run Linux distributions on Windows.

2. **Install Arch Linux from Microsoft Store:**
   - I went to the Microsoft Store and installed Arch Linux. This provided me with a Linux environment on my Windows system.

3. **Run the Installation Command:**
   - With Arch Linux up and running, I opened a terminal and ran the following command with elevated privileges:
   
     ```bash
     sudo curl https://bun.sh/install | sudo bash
     ```

     This command appears to be the solution to my specific issue, and it successfully installed the desired program or package.

By following these steps, I was able to resolve the problem I was facing windows10. Keep in mind that this solution is specific to windows  and may not apply to all scenarios.

**Comment by applemate** [comment]
> try `sudo curl https://bun.sh/install | sudo bash`

this works
