### ISSUE TITLE
Use trailing commas when printing JS objects & arrays

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#7262]
### What is the problem this feature would solve?

When copy pasting something from the console to somewhere else, it's easier to use multi cursor or regex on it.
Plus that's the standard in code (default in prettier 3), so it will look more familiar.

Actual
```
{
  a: 1,
  b: 2
}
```
Expected
```
{
  a: 1,
  b: 2,
}
```

### What is the feature you are proposing to solve the problem?

See title

**Comment by Jarred-Sumner** [comment]
I like this suggestion

**Comment by imdevtej** [comment]
Can i work on this issue ?
@ArnaudBarre

**Comment by ArnaudBarre** [comment]
See with the team, I have no time to learn zig for now 😁

**Comment by Electroid** [comment]
Closed by #7334
