### ISSUE TITLE
ReferenceError: Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by redpandatronicsuk** [oven-sh/bun#7263]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create the file `foo.ts` with contents:

```
const Infinity = 1/0;
```
then run `bun foo.ts` and it will exit and print this error:

```
ReferenceError: Cannot access uninitialized variable.
```

### What is the expected behavior?

No crash

### What do you see instead?

Crash

### Additional information

The line `const Infinity = 1/0;` is used in the `@ltd/j-toml` package and when that package is imported it crashes when run with bun.

**Comment by alxivnov** [comment]
@Electroid  Weirdly, there is no error if I don't name variable `Infinity` (screenshot 1). Uncommenting `Infinity` assignment generates an error on `_Infinity` line (screenshot 2).

<img width="625" alt="Снимок экрана 2024-04-07 в 19 23 26" src="https://github.com/oven-sh/bun/assets/19705653/f310f94d-491c-4fb9-b94f-8558389145bf">

<img width="436" alt="Снимок экрана 2024-04-07 в 19 32 20" src="https://github.com/oven-sh/bun/assets/19705653/4bc5ee09-d5f9-4f78-bd34-1a9bbad17ccd">
