### ISSUE TITLE
Executable built with bun build --compile does not work on QEMU Virtual CPU

### ISSUE THREAD

**Issue by karlbohlmark** [oven-sh/bun#7268]
### What version of Bun is running?

1.0.13

### What platform is your computer?

Linux 5.15.0-87-generic x86_64 x86_64

### What steps can reproduce the bug?

```
bun init --yes && bun build --compile --outfile crash --target bun index.ts && ./crash
```

### What is the expected behavior?

bun init --yes && bun build --compile --outfile crash --target bun index.ts && ./crash
Done! A package.json file was saved in the current directory.
 + index.ts
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts
   [6ms]  bundle  1 modules
  [83ms] compile  crash
Hello via Bun!

### What do you see instead?

edge@karl-master-1:~/p/buntest$ bun init --yes && bun build --compile --outfile crash --target bun index.ts && ./crash
Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts
   [5ms]  bundle  1 modules
 [149ms] compile  crash

error: FileNotFound reading "://root/crash"

### Additional information

edge@karl-master-1:~/p/buntest$ cat /proc/cpuinfo  | grep "model name" | head -1  && lsb_release -a && bun --version
model name	: QEMU Virtual CPU version 2.5+
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
1.0.13

**Comment by karlbohlmark** [comment]
I get the same error on 1.0.14 btw

**Comment by karlbohlmark** [comment]
Wow, in 1.0.15 it still crashes, but it does so much faster!

**Comment by codikyo** [comment]
Using the Bun-Baseline Binary as suggested  [here](https://github.com/oven-sh/bun/issues/3312#issuecomment-1656566886) fixed the issue for me. 
Maybe it helps you as well.

**Comment by Jarred-Sumner** [comment]
This is a duplicate of https://github.com/oven-sh/bun/issues/3312.

Please use the baseline build of Bun. See this issue https://github.com/oven-sh/bun/issues/3312#issuecomment-1656566886 for more information, and leave a comment if you still run into this after switching to the baseline build of Bun.

**Comment by karlbohlmark** [comment]
@Jarred-Sumner I still get this error using the baseline build of 1.0.21:

```
edge@karl-master-1:~/p/buntest/bun-linux-x64-baseline$ ./bun --revision && ./bun init --yes && ./bun build --compile --outfile crash --target bun index.ts && ./crash
1.0.21+837cbd60d
Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts
   [3ms]  bundle  1 modules
  [46ms] compile  crash
error: FileNotFound reading "://root/crash"```
