### ISSUE TITLE
bun test: "Can't find variable: React" when using key and object spread on JSX element

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#7278]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Using a `key` and an object spread causes the error.

Sandbox: https://codesandbox.io/p/devbox/focused-turing-ndcqp9

Test is running in that sandbox `index.test.tsx` you can toggle `.todo` to see the passing test in comparison.

### What is the expected behavior?

Should work as the passing test does, does not require importing react.

### What do you see instead?

Can't find variable: React error message

### Additional information
Setting the following in a preload file fixes this error.
```ts
global.React = await import('react');
```

**Comment by gkiely** [comment]
Looks like this has been solved @Jarred-Sumner?

**Comment by Jarred-Sumner** [comment]
yes should be
