### ISSUE TITLE
AccessDenied extracting tarball for license-webpack-plugin

### ISSUE THREAD

**Issue by omariqbalnaru** [oven-sh/bun#728]
### Version

0.1.4

### Platform

Linux itadm-Latitude-7480 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

`bun install`

### How often does it reproduce? Is there a required condition?

Always

### What do you see instead?

`bun install
bun install v0.1.4
  🚚 license-webpack-plugin... error: AccessDenied extracting tarball for license-webpack-plugin
Checked 1549 installs across 1135 packages (no changes) [852.00ms]
`

**Comment by TheLittlePolaris** [comment]
I'm encountering similar problem with
`@discordjs/rest`
`@discordjs/voice`
`@discordjs/collection`

Platform: MacOS Monterey 12.4 - Apple M1 Pro

**Comment by luanpiegas** [comment]
I had the same error with **imagemin-webpack-plugin**

```bash
bun install v0.1.5
  🚚 imagemin-webpack-plugin... error: AccessDenied extracting tarball for imagemin-webpack-plugin
Checked 1968 installs across 1456 packages (no changes) [97.00ms]
```
