### ISSUE TITLE
Bun.file() crashes with no message given on WSL

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#7288]
### What version of Bun is running?

1.0.14

### What platform is your computer?

WSL

### What steps can reproduce the bug?

I'm a school teacher and this happened on 2 student's computers in a lesson just now. Both were running WSL 2 with files stored in `/mnt/c`, and I did a `bun upgrade` for them to `1.0.14` and still got the bug. It worked fine on everyone else's computers. Assumes a `file.txt` with some text in it.

```js
console.log('before')
let data = await Bun.file('file.txt').text()
console.log('after')
console.log(data)
```

... Bun output 'before' but then exited with no error message. No lines after the `Bun.file()` line were executed.

Temporary workaround for these 2 students was to `require('node:fs')` instead and use `fs.readFileSync()` which worked fine.

I couldn't see any difference about the environment for these 2 students vs the other 10 students in the class or my own setup.

### What is the expected behavior?

Script runs to the end and doesn't silently crash.

### What do you see instead?

Silently crashes.

### Additional information

Writing files with `Bun.write()` works fine though.

**Comment by Electroid** [comment]
Thanks for filling this issue and for using Bun in your class! This is likely a duplicate issue of #5960. We will fix this.
