### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by colossalchicken** [oven-sh/bun#730]
### Affected URL(s)

https://github.com/oven-sh/bun/

https://github.com/oven-sh/bun#illegal-instruction-core-dumped

### Description of the problem

I keep on getting this error:
`Illegal instruction (core dumped)`
I searched the README, found a link in the table of contents, of which was unusable.
Where is the documentation for this error? How do I fix it?

**Comment by xhyrom** [comment]
it has been removed from README
original:
![image](https://user-images.githubusercontent.com/56601352/179254825-628bda5f-df70-419f-b560-93b5f56fe4b7.png)

**Comment by FinnRG** [comment]
Duplicate of #67.
