### ISSUE TITLE
Npm package aliases do not write to yarn lock file correctly with --yarn

### ISSUE THREAD

**Issue by yharaskrik** [oven-sh/bun#7302]
### What version of Bun is running?

1.0.14

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

In the `package.json` of a repo add a dependency of:

`"othertypescript": "npm:typescript@4.5.5"` (version and package don't really matter)

Run `bun install --yarn`

In the generated lockfile the section for the `typescript` package will look like:

```
"typescript@^3 || ^4", typescript@^4.4.4, typescript@npm:typescript@4.5.5:
```

The alias part (the last in the csv list) should be wrapped in quotes

```
"typescript@^3 || ^4", typescript@^4.4.4, "typescript@npm:typescript@4.5.5":
```

### What is the expected behavior?

The yarn lock file should be printed correctly

### What do you see instead?

The lockfile is printed with incorrect formatting in the case of npm aliases

**Comment by yharaskrik** [comment]
I have a fix for this, just figuring out how to write tests

**Comment by ArnaudBarre** [comment]
@yharaskrik This should be marked as fixed?

**Comment by yharaskrik** [comment]
> @yharaskrik This should be marked as fixed?

Yup!
