### ISSUE TITLE
Can't remove globally installed packages

### ISSUE THREAD

**Issue by hustLer2k** [oven-sh/bun#7303]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

After globally installing a package with `bun install -g <package_name>` when trying to remove it using `bun uninstall -g <package_name>` bun looks for local packages and throws `No package.json, so nothing to remove`

### What is the expected behavior?

The global package is uninstall.

### What do you see instead?

`No package.json, so nothing to remove`

**Comment by huseeiin** [comment]
bun remove -g works

**Comment by slymax** [comment]
> bun remove -g works

doesn't work for me. Both `bun uninstall -g firebase` and `bun remove -g firebase` result in `"firebase" is not in a package.json file` after installing with `bun install -g firebase`.

**Comment by slymax** [comment]
actually, it looks like `bun remove -g` just doesn't handle aliases. In my case `firebase` aliases `firebase-tools` and running `bun remove -g firebase-tools` does work.

@hustLer2k you didn't specify what package you were trying to remove, but maybe it's the same issue in your case

**Comment by anime-shed** [comment]
@slymax The same is happening to me, so how do I remove the alias? I am on Windows, btw.

![Image](https://github.com/user-attachments/assets/1dba84fd-1e0a-46cf-a444-201b7dd161c6)
