### ISSUE TITLE
`%s` in Mocha tests?

### ISSUE THREAD

**Issue by vanillajonathan** [oven-sh/bun#7304]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 6.5.0-13-generic x86_64 x86_64

### What steps can reproduce the bug?

Using [Mocha](https://mochajs.org/), I run `bun run test` and unexpectedly get `%s` in the output.

### What is the expected behavior?

Not any `%s` since I don't get that when I run `npm run test`.

```
$ npm run test

> example@1.0.0 test
> mocha test/test-*.js



  numbers
    ✔ Integer

```

### What do you see instead?

```
$ bun run test
$ mocha test/test-*.js

%s 
  %s numbers
    ✔ Integer
```

**Comment by Electroid** [comment]
Mocha is probably using some node.util format and we are not handing it properly.
