### ISSUE TITLE
tauri cli does not work due to event loop ref bug with napi

### ISSUE THREAD

**Issue by ayn2op** [oven-sh/bun#7314]
**Version**: 1.0.14+d8be3e51b
**Platform**: Darwin 23.1.0 arm64 arm

![image](https://github.com/oven-sh/bun/assets/119342035/629c94fb-711f-4d31-bf29-f90ffaa74eb5)

**Comment by Electroid** [comment]
@paperdave

**Comment by paperclover** [comment]
this is a regression from somewhere, the pr https://github.com/oven-sh/bun/pull/4156 is supposed to fix this.

**Comment by paperclover** [comment]
though idk if this ever worked properly as 1.0.0 shows this issue
