### ISSUE TITLE
Bun Elysia docker Image works fine on local but deployment fails silently on digital ocean

### ISSUE THREAD

**Issue by yashone7** [oven-sh/bun#7322]
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

```
FROM oven/bun:latest

WORKDIR /app

COPY package.json .
COPY bun.lockb .
COPY .env.production /app/
COPY config /app/config

RUN bun install --production

COPY src src
COPY tsconfig.json .

ENV NODE_ENV production
CMD ["bun", "src/index.ts"]

EXPOSE 3000
```
This is the docker file I'm using for My Elysia Application, I am successfully able to build and run the docker image. But when I deploy to digital ocean through container registry the deployment is failing. I am also not able to see the logs, I only get [ ] in the deployment logs in docn, and docker version  is 24.0.6, build ed223bc. 

### What is the expected behavior?

The expected output is that build should also work in digital ocean.

### What do you see instead?

I see [ ] as deploy logs and build skipped for image

**Comment by Jarred-Sumner** [comment]
What is the linux kernel version of the Digital Ocean machine?

**Comment by yashone7** [comment]
I am using digital ocean app platform for deploying my application, I am not sure what is the underlying linux version they are using, could be ubuntu 22.04 perhaps.

**Comment by yashone7** [comment]
Closing the issue as there are insufficient details.
