### ISSUE TITLE
bun build issue on require

### ISSUE THREAD

**Issue by lucasshz** [oven-sh/bun#7326]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

MacOs

### What steps can reproduce the bug?

running on my application:
bun build --target=bun ./src/app/index.ts --outfile=./dist/index.js

### What is the expected behavior?

<img width="1223" alt="Screen Shot 2023-11-26 at 12 23 00 PM" src="https://github.com/oven-sh/bun/assets/22438232/908b926a-5f33-4d3d-854f-991051a2f4c2">
<img width="1121" alt="Screen Shot 2023-11-26 at 12 24 01 PM" src="https://github.com/oven-sh/bun/assets/22438232/bcac482f-f913-441b-96c6-66c99d532e3e">

on this line:
  var requireFunction = typeof __webpack_require__ === "function" || typeof __non_webpack_require__ === "function" ? __non_webpack_require__ : require;
  
need to be:
  var requireFunction = typeof __webpack_require__ === "function" || typeof __non_webpack_require__ === "function" ? __non_webpack_require__ : import.meta.require;
  
  obs: import.meta.require to works, application tuning after change the line:
<img width="821" alt="Screen Shot 2023-11-26 at 12 27 18 PM" src="https://github.com/oven-sh/bun/assets/22438232/795a38e2-3405-431c-b091-e053dd6d7c1d">

**Comment by Electroid** [comment]
Thanks for reporting, we'll fix this. In the meantime, you can always run `bun ./src/app/index.ts` and it will just work.
