### ISSUE TITLE
Docker Illegal instruction

### ISSUE THREAD

**Issue by rushirufu** [oven-sh/bun#733]
### Version

v0.1.4

### Platform

Dcoker

### What steps will reproduce the bug?

/ # uname -a
Linux d2ddad334cec 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 Linux

/ # bun
Illegal instruction

### What do you see instead?

Illegal instruction

**Comment by FinnRG** [comment]
Please verify if your CPU supports AVX2. If not, follow the instructions at #67.
