### ISSUE TITLE
Cannot export default Bun.Serve

### ISSUE THREAD

**Issue by LManeL26** [oven-sh/bun#7331]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Just lauch a server with this code
```ts
export default Bun.Serve({
    port: 80,
    fetch (req) {
        return new Response("Hello World");
    }
})
```

### What is the expected behavior?

The expected result is that in some other file i can call the Serve for some reasons like
```ts
import HTTP_SERVER from './Serve'
HTTP_SERVER.publish('main', "Done!");
```

### What do you see instead?

this, with ANY port will return 
```
EADDRINUSE: Failed to start server. Is port <port> in use?
 syscall: "listen"

      at bun:main:11:3
 ```

**Comment by Jarred-Sumner** [comment]
- Your computer needs permission to listen on port 80, which is typically not allowed without root access
- `Bun.Serve` does not exist. You probably meant `Bun.serve`
- If you want to use `export default`, you can return the arguments you pass to `Bun.serve` and it will do that for you automatically

Hopefully that helps
