### ISSUE TITLE
bun create vite or bun create vue@latest not work in docker or wsl

### ISSUE THREAD

**Issue by andresgarcia0313** [oven-sh/bun#7345]
### What version of Bun is running?

1.0.14

### What platform is your computer?

wsl docker

### What steps can reproduce the bug?

exec 
bun create vite
bun create vue@latest

Does not allow choosing project menus in WSL or Docker.

**Comment by Electroid** [comment]
Thanks for reporting, can't reproduce on macOS, but when running in Docker the issue reproduces.

```
❯ docker run -it oven/bun:latest bun create vite
Unable to find image 'oven/bun:latest' locally
latest: Pulling from oven/bun
bbf382c14c7b: Pull complete 
e10456e701aa: Pull complete 
37d7ca5b3d23: Pull complete 
0f7b5d54e6ad: Pull complete 
75d004294c81: Pull complete 
Digest: sha256:1e7e5dd2a5403b91714d0fc1b229da085f460a632f0c79037cbb0b60238c6434
Status: Downloaded newer image for oven/bun:latest
✔ Project name: … vite-project
? Select a framework: › - Use arrow-keys. Return to submit.
❯   Vanilla
    Vue
    React
    Preact
    Lit
    Svelte
    Solid
    Qwik
    Others
```

Once "Project name" appears, I'm able to hit enter once and it registers. But after that, no keys work, including `^C`/`^D`.

**Comment by chatblanc-ciel** [comment]
The same error occurred, too.

**Comment by pablodz** [comment]
![image](https://github.com/oven-sh/bun/assets/28235457/839723a8-c926-45eb-ad20-cedf53456bef)

all terminal in linux stuck
