### ISSUE TITLE
Compiling TS / JS like Static Hermes

### ISSUE THREAD

**Issue by wakaztahir** [oven-sh/bun#7357]
### What is the problem this feature would solve?

Bun is a runtime, Being a runtime still has limitations and cons, Compiling to Machine Code has these undeniable benefits

1 - Single Executable that can be deployed everywhere easily.
2 - Insane performance compared to anything interpreted.
3 - Native Access (pointers, memory... so much more)

These are the best features of Rust & Golang that make them great for writing API's and backend servers.

Static Hermes is a project being worked on by Facebook & Amazon, which compiles typescript to native code, However It doesn't have any support for Node and I don't think it ever will.

Python has Mojo for compilation, Even Java now has GraalVM, Sooner or later JavaScript will need to be compiled. Because Bun would require that last bit of performance and constantly squeezing performance out of an interpreted environment is hard.

I know that Bun is not looking to do this at the current moment and fixing bugs and being compatible with Node JS would be its first priority. But Bun would solve a bigger problem than just performance if it achieves this.

### What is the feature you are proposing to solve the problem?

Compiling Typescript to machine code using Bun

### What alternatives have you considered?

Static Hermes.

**Comment by Jarred-Sumner** [comment]
I'm excited for Static Hermes' future and we will be interested in exploring it's potential with Bun in 3-5 years after it is usable
