### ISSUE TITLE
node-pty unable to be run from bun

### ISSUE THREAD

**Issue by Moosems** [oven-sh/bun#7362]
### What version of Bun is running?

1.0.14

### What platform is your computer?

Darwin 18.7.0 x86_64 i386

### What steps can reproduce the bug?

```bash
mkdir example
cd example
bun install node-pty
echo "var pty = require('node-pty');" >> test.js
bun test.js
```

### What is the expected behavior?

It runs without an issue.

### What do you see instead?

```bash
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/Moosems/Desktop/PyQtXtermApp/node_modules/node-pty/build/Release/pty.node
  Expected in: flat namespace

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/Moosems/Desktop/PyQtXtermApp/node_modules/node-pty/build/Release/pty.node
  Expected in: flat namespace
```

### Additional information

Works fine with npm.

**Comment by kkocdko** [comment]
Old `node-pty` uses NAN, not NAPI. The future work about port `node-pty` to NAPI is here https://github.com/microsoft/node-pty/pull/644 .

Please close this issue.

**Comment by Moosems** [comment]
I think I'll keep it open until it's merged and a release with the changes comes out :). I didn't add the NAPI label anyway. In that PR someone even tried this and it didn't work.

**Comment by benhylak** [comment]
Hitting this, not able to use Bun.

**Comment by metawrap-dev** [comment]
Same

```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/james/metawrap/node_modules/canvas/build/Release/canvas.node
  Expected in: flat namespace

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/james/metawrap/node_modules/canvas/build/Release/canvas.node
  Expected in: flat namespace
```

**Comment by terrywh** [comment]
not possible? https://github.com/microsoft/node-pty/issues/632#issuecomment-1964234386

**Comment by Jarred-Sumner** [comment]
Please follow along in #4290 

@190n is actively working on supporting V8 C++ APIs in Bun

**Comment by xuxucode** [comment]
try this https://www.npmjs.com/package/bun-pty
