### ISSUE TITLE
[bun:sqlite] Non-ascii field names are garbled

### ISSUE THREAD

**Issue by mandel59** [oven-sh/bun#738]
### Version

0.1.2

### Platform

Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

1. Save the code as `code.js`
```js
import { Database } from "bun:sqlite";
const db = Database.open(":memory:");
console.log(db.prepare("select '😀' as 笑").all());
```

2. `bun run code.js`

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

```
[ { "笑": "😀" } ]
```

### What do you see instead?

```
[ { "\u0011": "😀" } ]
```

**Comment by noobyogi0010** [comment]
Hey @Jarred-Sumner 
I would like to work on this issue if no one else has already taken it up?

**Comment by Jarred-Sumner** [comment]
This was a console.log bug when printing UTF16 property names
