### ISSUE TITLE
same cookie set multiple times

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#7383]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.0-89-generic aarch64 aarch64

### What steps can reproduce the bug?

```js
headers.append("Set-Cookie", "id=123");
headers.append("Set-Cookie", "id=456");
```

### What is the expected behavior?

According to your AI (Ask AI) :

> To modify a cookie in Bun, you would create a new 'Set-Cookie' header with the cookie name and the new value. It's important to note that setting a cookie with the same name again will effectively modify the existing cookie.

### What do you see instead?

```js
Headers {
  "set-cookie": [ "id=81530044017920585945237314720407; Domain=...; Path=/; Expires=Fri, 01 Dec 2023 16:26:06 GMT; Max-Age=86400; Secure; HttpOnly; SameSite=lax",
    "id=60481077230751881896485248888496; Domain=...; Path=/; Expires=Fri, 01 Dec 2023 16:26:06 GMT; Max-Age=86400; Secure; HttpOnly; SameSite=lax"
  ]
}
```

### Additional information

This array should hold only different cookie names, not multiple `id=`

**Comment by paperclover** [comment]
for contributor, the change is likely to be in FetchHeaders.cpp in appendToHeaderMap. it should be kept in mind that this is copied from webkit in part, and their code should be used as a reference.

**Comment by cirospaciari** [comment]
Closing the issue bun, nodejs, chrome and safari give us the same output
```js
const headers = new Headers();
headers.append("Set-Cookie", "id=123");
headers.append("Set-Cookie", "id=456");
console.log(headers.get("Set-Cookie")); // id=123, id=456
```
