### ISSUE TITLE
Latin-1 characters written with console.log are garbled

### ISSUE THREAD

**Issue by mandel59** [oven-sh/bun#739]
### Version

0.1.2

### Platform

Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

1. Save the code as `code.js`
```js
console.log('English');
console.log('Français');
console.log('Ελληνική');
console.log('日本語');
console.log('Emoji😎');
console.log('Français / Ελληνική');
```

2. `bun run code.js`

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

```
English
Français
Ελληνική
日本語
Emoji😎
Français / Ελληνική
```

### What do you see instead?

```
English
Fran�ais
Ελληνική
日本語
Emoji😎
Français / Ελληνική
```

### Additional information

- Strings only with latin-1 characters are garbled.

**Comment by Jarred-Sumner** [comment]
I see the bug

In some of the earlier code in Bun, I assumed latin1 strings were ascii only in JSC and only realized later that they include non-ascii characters

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/commit/fd4a210b84da0c7e5f55ae31a7e8af805b81abaa
