### ISSUE TITLE
Bun.deepEquals (and .toEqual) stumble on arrays with dates

### ISSUE THREAD

**Issue by disintegrator** [oven-sh/bun#7395]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.0-89-generic aarch64 aarch64

### What steps can reproduce the bug?

1. Clone the reproduction repo: https://github.com/disintegrator/bun-repro-7395
2. Run `bun i`
3. Run `bun test`

### What is the expected behavior?

Tests pass

### What do you see instead?

Test fails due to failed `expect().toEqual()` assertion:

```
error: expect(received).toEqual(expected)

  [
    2020-01-01T00:00:00.001Z,
    2020-01-01T00:00:00.001Z
  ]

- Expected  - 0
+ Received  + 0
```

### Additional information

I've tried a similar test under Bun but using `chai.expect(actual).eql(expected)` and that works as intended.

**Comment by Jarred-Sumner** [comment]
This was fixed by @dfaio in https://github.com/oven-sh/bun/pull/7542

**Comment by disintegrator** [comment]
Thanks!
