### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by skyfallwastaken** [oven-sh/bun#7396]
### What version of Bun is running?

v1.0.14 - I cannot run the command as that also crashes

### What platform is your computer?

Linux 6.5.6-76060506-generic x86_64 x86_64

### What steps can reproduce the bug?

Run any Bun command

### What is the expected behavior?

Bun to fully function

### What do you see instead?

Illegal instruction (core dumped)

### Additional information

- CPU: i7-2600
- Installed via pkgx

**Comment by skyfallwastaken** [comment]
Update: This is an issue w/ how pkgx packages Bun - sorry!

**Comment by Electroid** [comment]
What was the issue and how did you fix it? We want to make sure others don’t run into this.

**Comment by skyfallwastaken** [comment]
@Electroid The issue's above, and what fixed it was installing Bun using the official install script instead of using pkgx.
