### ISSUE TITLE
console.log("%d", { toString: () => "23" }) prints a weird negative number

### ISSUE THREAD

**Issue by jcbhmr** [oven-sh/bun#7400]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

bun repl:
```js
console.log("%d", { toString: () => "23" })
```

### What is the expected behavior?

console.log("%d", { toString: () => "23" })
VM41:1 23

### What do you see instead?

```js
> console.log("%d", { toString: () => "23" })
-9223372036854775808
```

### Additional information

should follow this:
https://console.spec.whatwg.org/#formatter

**Comment by paperclover** [comment]
for instructions on how to fix this, see my comment in https://github.com/oven-sh/bun/issues/7401#issuecomment-1836779858. i think a pr should fix both of these.

**Comment by Sweetdevil144** [comment]
Hello. Is the issue fixed? If not, I would like to go ahead and propose a way !!

**Comment by paperclover** [comment]
the issue is not fixed and i am not aware of anyone that is working on it. if you would like to give it a go, feel free, but check the comment i left in the other issue.
