### ISSUE TITLE
%f not correctly coercing object

### ISSUE THREAD

**Issue by jcbhmr** [oven-sh/bun#7401]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
console.log("%f", 0.5)
```
```sh
bun testconsole.js
```

### What is the expected behavior?

```sh
jcbhmr@PIG-2016:~/Documents$ bun testconsole.js
0.5
0.5
```

### What do you see instead?

```sh
jcbhmr@PIG-2016:~/Documents$ bun testconsole.js
[Number (Frac): 0.5]
0.5
```

### Additional information

Chrome:
```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
console.log("%f", 0.5)
VM47:10 0.5
VM47:11 0.5
```

Firefox:
```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }…
0.500000 [debugger eval code:10:9](chrome://devtools/content/webconsole/debugger%20eval%20code)
0.500000
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1846606

should follow this: https://console.spec.whatwg.org/#formatter

**Comment by paperclover** [comment]
note about how to resolve this: a function is defined `fn writeWithFormatting(` and likely has many more subtle formatting issues. also, it is defined twice, once for console.log, and twice for bun:test.

we should add tests for
- `%f` calls toPrimative
- `%f` calls with `Symbol()`
- the above works with `%d`, `%i`

it might be worth reviewing the rest of the linked `Formatter` spec excluding the TODO `%c` spec.
