### ISSUE TITLE
`bun i` fails when using workspaces

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#7406]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

The issue seems to be related to bun trying to install in alphabetical order.
I have a repro here: https://github.com/Didas-git/lilybird/tree/ede05144f94b8130203ab0e2b25c3816708fefb6

But all you have to do is have a package a that depends on package b and try to install it

### What is the expected behavior?

It installs with no errors

### What do you see instead?

Errors.

For that repro i get the following: 
![image](https://github.com/oven-sh/bun/assets/80978939/122cd197-40d9-41bc-8885-32fabc0d8e7c)

### Additional information

Dave told me to ping @dylan-conway for this issue.

**Comment by JustMrMendez** [comment]
having the same issue

**Comment by andenacitelli** [comment]
I can reproduce with the repro example from the initial report, but only after I rename the `jsx` file to something alphabetically before `core` such as `_jsx`.

**Comment by dylan-conway** [comment]
There have been several workspace related bug fixes to bun install recently. I tested this locally and I believe this issue was likely fixed in #11177. Closing as complete, but please reopen if you continue to have issues with workspaces.
