### ISSUE TITLE
`bun install` fails when executing from inside a subfolder in a monorepo (Duplicate dependency)

### ISSUE THREAD

**Issue by wladpaiva** [oven-sh/bun#7407]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

1. `bunx create-turbo@latest error-bun-install`
2. `cd error-bun-install/apps/web`
3. `bun install`

### What do you see instead?

<img width="621" alt="Screenshot 2023-12-01 at 22 46 11" src="https://github.com/oven-sh/bun/assets/1843792/fe9628f0-1c0a-4534-b115-dfc751d343ea">

**Comment by itsmingjie** [comment]
Can reproduce this. A temporary workaround is remove any internal package imports from the root `package.json`.

**Comment by wladpaiva** [comment]
> Can reproduce this. A temporary workaround is remove any internal package imports from the root `package.json`.

or just `cd ../.. && bun install` :)

**Comment by dylan-conway** [comment]
This was fixed in bun `v1.1.9` with #11177
