### ISSUE TITLE
F5 on Windows

### ISSUE THREAD

**Issue by qwenhn** [oven-sh/bun#742]
### Version

0.1.4

### Platform

Windows 10, Ubuntu 22.04 LTS

### What steps will reproduce the bug?

Step 1: Run bun create react ./app
Step 2: Run bun dev
Step 3: F5 multiple times on windows

### How often does it reproduce? Is there a required condition?

On windows i see it often slow to refresh when pressing f5. But on mac-os it doesn't have this problem

### What is the expected behavior?

Refresh fast when i pressing F5 same on mac-os

### What do you see instead?

It refresh slow

**Comment by xhyrom** [comment]
Please fill template

**Comment by qwenhn** [comment]
Hi @xHyroM x
I updated the template again

**Comment by sewe75** [comment]
@hoanghiaquyen Where are your project files located?  
In your Windows home directory (below `/mnt/c/Users`) or inside the WSL (2) VM (below `/home/<username>`)?  

If your project is located in your Windows home directory please try again in your Linux home - this should speed up things a bit. But please keep in mind this is a comparison between an OS-managed VM vs. running natively on a hardware-optimized OS.

**Comment by qwenhn** [comment]
Special thanks. I will try it again.

But I think this problem is manifest.json loading error. Because, when I remove this line, the refresh is only slow sometimes

**Comment by sewe75** [comment]
You are right - removing the link to manifest.json it works.    
After prefixing `manifest.json` with `public/` as follows (#829), it loads fine but for me breaks at the first reload (F5) and the dev webserver becomes unresponsive:
```html
<link rel="manifest" href="public/manifest.json" />
```

**Comment by qwenhn** [comment]
Thanks for helping me with this problem. I think we can close it. Have a nice day
