### ISSUE TITLE
Latest canary fails to save lockfile

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#7420]
### What version of Bun is running?

latest canary in Docker

### What platform is your computer?

Linux x64 in Docker

### What steps can reproduce the bug?

Run a `bun install` or `bun install <package-name>` command in a project.

### What is the expected behavior?

Installs packages.

### What do you see instead?

```
bun add v1.0.15 (03298cba)
  🔒 Saving lockfile... error: failed to save lockfile: EXDEV
```

### Additional information

Could not test outside Docker as there is no `musl` build.

**Comment by Electroid** [comment]
This was fixed in #7419, try again and let us know if you still run into this issue.
