### ISSUE TITLE
Allow expect.extend in setup file

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#7423]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
// setupFile.ts
import { expect } from 'bun:test';
console.log(expect.extend); // undefined
```

bun --preload ./setupFile.ts

### What is the expected behavior?

Should allow extending expect in the setup file, so we can mock extend for testing-library

### What do you see instead?

expect.extend is undefined

### Additional information

See: https://github.com/oven-sh/bun/issues/7035

**Comment by Electroid** [comment]
Interesting, this is probably a side-effect of `expect` only being able to be used inside a test scope. We'll fix this

**Comment by Jarred-Sumner** [comment]
yeah it’s becoming clear that making a distinction between preload and regular in the value returned was a bad idea altogether
