### ISSUE TITLE
Better error message when test script not available

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#7425]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

`bun run test` with a package.json without a test script

### What is the expected behavior?

error: missing script "test"

### What do you see instead?

```
arnaud@Mac eslint-plugin-react-refresh % bun run test
error: "test" exited with code 1 (SIGHUP)
arnaud@Mac eslint-plugin-react-refresh % bun run non-existing
error: missing script "non-existing"
```

### Additional information

Could be niced also to differentiate script not found and package.json not found

**Comment by paperclover** [comment]
bun ran `/bin/test`
<img width="469" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/d464609d-25ec-4ed5-a515-3108335374e8">

So technically working as intended, but I agree we should clarify this.
