### ISSUE TITLE
Broken sourcemaps

### ISSUE THREAD

**Issue by MonsterDeveloper** [oven-sh/bun#7427]
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Linux 5.13.0-1022-aws x86_64 x86_64

### What steps can reproduce the bug?

1. Create a sample file `some-code.ts`:
```ts
console.log("Hello world");
```

2. Build the file and generate sourcemaps with the following script:
```ts
await Bun.build({
  entrypoints: ["./some-code.ts"],
  outdir: "./dist",
  target: "bun",
  sourcemap: "external",
});
```

3. Resolve the sourcemap using `sentry-cli`:
```
bunx @sentry/cli sourcemaps resolve dist/some-code.js.map
```

### What is the expected behavior?

The source map should be correctly generated.

### What do you see instead?

The Bun's sourcemap cannot be parsed by tools like `sentry-cli`.

### Additional information

The issue lies in the `mappings` of the source map.

Here's `mappings` generated by Bun for the code in the reproduction:
```
;;AA/////fAAA,QAAQ,IAAI,aAAa;
``` 

The esbuild outputs the following:
```
;AAAA,QAAQ,IAAI,aAAa;
```

I created a [playground](https://codedamn.com/playground/uzX5hjI4bMa8UxZTz0zIw) with some sample source files, 2 bundling scripts using Bun and esbuild, and sourcemap decoder from [this article](https://www.bugsnag.com/blog/source-maps/) ([link to gist](https://gist.github.com/bengourley/c3c62e41c9b579ecc1d51e9d9eb8b9d2))

Run `cat dist-bun/1.js.map | node decode.cjs | jq .` and see the output from Bun's sourcemap:
```json
{
  "version": 3,
  "sources": [
    "../source-samples/1.ts"
  ],
  "sourcesContent": [
    "console.log(\"Hello world\");"
  ],
  "mappings": {
    "1": [
      ""
    ],
    "2": [
      ""
    ],
    "3": [
      "1 => ../source-samples/1.ts -536870910:1",
      "9 => ../source-samples/1.ts -536870910:9",
      "13 => ../source-samples/1.ts -536870910:13",
      "26 => ../source-samples/1.ts -536870910:26"
    ],
    "4": [
      ""
    ]
  },
  "debugId": "076E75C2BF05B11064756e2164756e21",
  "names": []
}
```

The esbuild output is parsed correctly:
```json
{
  "version": 3,
  "sources": [
    "../source-samples/1.ts"
  ],
  "sourcesContent": [
    "console.log(\"Hello world\");"
  ],
  "mappings": {
    "1": [
      ""
    ],
    "2": [
      "1 => ../source-samples/1.ts 1:1",
      "9 => ../source-samples/1.ts 1:9",
      "13 => ../source-samples/1.ts 1:13",
      "26 => ../source-samples/1.ts 1:26"
    ],
    "3": [
      ""
    ]
  },
  "names": []
}
```

Thus Bun's sourcemap is corrupt and cannot be parsed by other tools (I tried `sentry-cli`, but I'm sure others won't work as well).

**Comment by Electroid** [comment]
Thanks for reporting, yes this is a known issue. We will be fixing these issues and adding proper source map tests soon

**Comment by supermacro** [comment]
Any updates on this? Is the bun team planning on resolving this in the coming weeks?

**Comment by spsDrop** [comment]
Is there any roadmap or timeline for fixing the source maps? Broken source maps are turning into a deal breaker for us using bun as a package manager. Seems like this would be a higher priority.

**Comment by cigrainger** [comment]
Yep we just reverted to esbuild. Kind of shocking something so important is broken in a 1.0 release? I was very very bullish on bun but this is 100% a dealbreaker.

**Comment by Jarred-Sumner** [comment]
We are still very focused on Windows (which is taking longer than expected). This is high on the list of priorities to fix after Windows.

**Comment by paperdave** [comment]
This was resolved by one of my recent sourcemap PRs, either #10999 or #11288

**Comment by Zaczero** [comment]
Hey, after upgrading to bun 1.1.10, the issue didn't go away for me. Should I open a new issue?

I create sourcemaps like this:

```sh
bun build \
  --sourcemap=inline \
  --entry-naming "[dir]/bundle-[name].[ext]" \
  --outdir app/static/js \
  $src_paths
```

![image](https://github.com/oven-sh/bun/assets/10835147/069ac619-3770-405e-ab5d-e7dcc41b513b)

![image](https://github.com/oven-sh/bun/assets/10835147/5a4ee9da-9305-4694-9ac0-89614a4466fa)

![image](https://github.com/oven-sh/bun/assets/10835147/148b0987-f8a0-48ff-ba67-fc6f3c7ff341)

**Comment by paperdave** [comment]
Can you upgrade to the latest canary `bun upgrade --canary` and try again there. if it's still broken, can you open a new issue and mention me (@paperdave) in it so it shows in my inbox. would love to fix any remaining cases.

**Comment by Zaczero** [comment]
@paperdave I can't easily because of https://github.com/oven-sh/bun/issues/918 I will wait for the new release and then post feedback.

**Comment by Zaczero** [comment]
A small followup. As of `1.1.31` the issue seems to be resolved for me 👍.
