### ISSUE TITLE
Bun Test executes entire TS file when testing exported function

### ISSUE THREAD

**Issue by lia-07** [oven-sh/bun#7432]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

I ran into this bug when using my Advent of Code automation script.
This is a working example of 

`solution.ts`:
```typescript
export function part1(input: string): any {
  return 142;
}
console.log("This shouldn't be logged.");
```

`solution.test.ts`:
```typescript
import { expect, test } from "bun:test";

import { part1 } from "./solution";

const testData = {
  part1: {
    input: `1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet`,
    expectedOutput: 142,
  }
};

test("part-1", () => {
  expect(part1(testData.part1.input)).toBe(testData.part1.expectedOutput);
});
```

### What is the expected behavior?

Ideally, the terminal output should look something like this:
```zsh
% bun test
bun test v1.0.15 (b3bdf22e)

solution.test.ts:
✓ part-1 [0.50ms]

 1 pass
 0 fail
 1 expect() calls
Ran 1 tests across 1 files. [84.00ms]
```

### What do you see instead?

Instead, I get this:
```zsh
% bun test
bun test v1.0.15 (b3bdf22e)

solution.test.ts:
This shouldn't be logged.
✓ part-1 [0.50ms]

 1 pass
 0 fail
 1 expect() calls
Ran 1 tests across 1 files. [84.00ms]
```

### Additional information

I'm not sure if this is expected behaviour or not, and I have found ways to work around this. I just thought it was weird and annoying.

**Comment by hustLer2k** [comment]
It's the way imports work in js, the entire file is run even though you imported only one function. Bun has nothing to do with it

**Comment by lia-07** [comment]
> It's the way imports work in js, the entire file is run even though you imported only one function. Bun has nothing to do with it

Oh, sorry. 
Didn't know that, thanks for telling me.
