### ISSUE TITLE
`fs.createReadStream` is not a 1:1 match to the Node.js API

### ISSUE THREAD

**Issue by gmahomarf** [oven-sh/bun#7439]
### What version of Bun is running?

1.0.15

### What platform is your computer?

Linux 6.5.12-300.fc39.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```js
createReadStream('input.txt', 'utf8')
```

### What is the expected behavior?

It works.

### What do you see instead?

```js
createReadStream('input.txt', 'utf8');
^
TypeError: Expected options to be an object
      at new ReadStream2 (node:fs:342:27)
      at new ReadStream3 (node:fs:333:45)
      at node:fs:45:61
```

### Additional information

This was mentioned in [a comment](https://github.com/oven-sh/bun/issues/4084#issuecomment-1670891415) in #4084 and marked as resolved, but that is not the case

The [compatibility docs](https://bun.sh/docs/runtime/nodejs-apis#node-fs) don't mention this discrepancy, and the [node.js API docs](https://nodejs.org/api/fs.html#fscreatereadstreampath-options) state that the second argument **can** be a string

**Comment by Electroid** [comment]
Thanks for reporting, we'll fix this.
