### ISSUE TITLE
problem in installing package. Windows subsystem 

### ISSUE THREAD

**Issue by m7medVision** [oven-sh/bun#744]
### Version

0.1.4

### Platform

Linux Forme2 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 GNU/Linux

### What steps will reproduce the bug?

Whenever I want install any package this message appear 
```
error: Linux kernel version doesn't support io_uring, which Bun depends on.

To fix this error: please upgrade to a newer Linux kernel.

If you're using Windows Subsystem for Linux, here's how:
  1. Open PowerShell as an administrator
  2. Run this:
    wsl --update
    wsl --shutdown

If that doesn't work (and you're on a Windows machine), try this:
  1. Open Windows Update
  2. Download any updates to Windows Subsystem for Linux

If you're still having trouble, ask for help in bun's discord https://bun.sh/discord
```  

### What do you see instead?

```
error: Linux kernel version doesn't support io_uring, which Bun depends on.

To fix this error: please upgrade to a newer Linux kernel.

If you're using Windows Subsystem for Linux, here's how:
  1. Open PowerShell as an administrator
  2. Run this:
    wsl --update
    wsl --shutdown

If that doesn't work (and you're on a Windows machine), try this:
  1. Open Windows Update
  2. Download any updates to Windows Subsystem for Linux

If you're still having trouble, ask for help in bun's discord https://bun.sh/discord
```

**Comment by xhyrom** [comment]
1. Open powershell as administrator
2. Check Windows Updates
3. `wsl --set-version <name> 2`
4. `wsl --update`
5. `wsl --shutdown`

![image](https://user-images.githubusercontent.com/56601352/179353049-64ea0740-cd8a-4248-857e-c2a484a3e381.png)

**Comment by m7medVision** [comment]
> 1. Open powershell as administrator
> 2. Check Windows Updates
> 3. `wsl --set-version <name> 2`
> 4. `wsl --update`
> 5. `wsl --shutdown`
> 
> ![image](https://user-images.githubusercontent.com/56601352/179353049-64ea0740-cd8a-4248-857e-c2a484a3e381.png)

Thank You
