### ISSUE TITLE
Spawned process isn't killed after reloading via `--watch`

### ISSUE THREAD

**Issue by RossMcMillan92** [oven-sh/bun#7440]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Simple steps to reproduce noted in the README here:

https://github.com/RossMcMillan92/bun-spawn-bug

### What is the expected behavior?

All spawned processes are killed when bun reloads via `--watch` flag.

### What do you see instead?

Older spawned processes keep running along with newly spawned processes.

### Additional information

I have tried a bunch of things, including killing processes with `process.kill(spawn.pid)` and `<spawn_instance>.kill()`.

I also think I should be able to run `process.kill(-spawn.id)` to kill the entire group of processes but Bun complains that it's a negative PID.

**Comment by Jarred-Sumner** [comment]
This is a reasonable thing to ask, but note that processes are never killed automatically. If the parent process is killed, it can become a “zombie” process.

**Comment by RossMcMillan92** [comment]
Thanks for the quick reply!

I thought that might be the case. Is there any guidance on how to handle sub processes, i.e. killing them as needed. I've been trying a bunch of things but haven't gotten anything working.

`process.on('exit | SIGKILL | SIGTERM | etc')` don't seem to fire when reloaded via `--watch` which I think is my main blocker to getting something working.

**Comment by RossMcMillan92** [comment]
Happy to close this if we think it's user error. Have opened https://github.com/oven-sh/bun/issues/7441 which I think is a genuine bug.
