### ISSUE TITLE
Add `-h` as an alias of `--help` to CLI commands

### ISSUE THREAD

**Issue by RiskyMH** [oven-sh/bun#7451]
# What version of Bun is running?

1.0.15+b3bdf22eb

# What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

# What is the issue?

Most commands have no help menu command  using `-h` and only `--help`, for example:
* bun install
* bun add
* bun init
* bun create
* bun upgrade
* bun pm
* bun link 
* bun unlink

And some failed color highlighting
* `bun run -h` in command description such as  `--config`

# What is the expected behavior?

For all commands to a have a basic help menu to at least describe their purpose and for color highlighting to work and not just show the color codes.

# What do you see instead?

`bun run -h` showing the color highlighting codes instead of actioning them
![image](https://github.com/oven-sh/bun/assets/56214343/21d28343-c043-4ef3-926b-43a3fbf7a26c)

`bun init -h` just runs the command and ignores help flag
![image](https://github.com/oven-sh/bun/assets/56214343/8a0dc1d4-c3f1-4ca8-aa2d-25161674c3b2)

`bun link -h` says the flag is invalid
![image](https://github.com/oven-sh/bun/assets/56214343/000fa1cc-2249-4e8d-be03-638738f61b07)

`bun add -h` also throws invalid flag, but I feel like it can just ignore the flag and show the help (like when ran basic `bun add`)

# Additional information

I feel like the help commands not existing is ok, but I would like it more if I could get minor information. And the failed color is something that should be fixed.

**Comment by Jarred-Sumner** [comment]
This is not accurate, the flag is `--help`. We should add an alias for `-h` though

**Comment by RiskyMH** [comment]
ohh your right, im really sorry about this

I saw some worked with -h and assumed everything... but yeah i would like alias for -h and also fix `bun run`'s help issue (should i make a different issue for this?)

**Comment by RiskyMH** [comment]
Looks like #7519 added this!
