### ISSUE TITLE
Bun bundle crashes with error message "unexpected keyword export"

### ISSUE THREAD

**Issue by KilianB** [oven-sh/bun#7457]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

1. Clone the repository https://github.com/KilianB/Bun-import-issue
2. run "bun run build"
3. attempt to execute the bundle `bun run run-build`

### What is the expected behavior?

Application starts without issues

### What do you see instead?

````
42273 |     export { $minify as minify };
        ^
SyntaxError: Unexpected keyword 'export'
````

### Additional information

This only happens for the bundled code, executing the project with `bun start` works just fine

**Comment by paperclover** [comment]
Duplicate of #4565
