### ISSUE TITLE
Path remapping does not work in tsconfig

### ISSUE THREAD

**Issue by Sub0X** [oven-sh/bun#7463]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Install bun and create a new typescript react project. Path mapping doesn't work with the following tsconfig file:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "composite": true,
    "paths": {
      "@components/*": [
        "./src/components/*"
      ],
      "@pages/*": [
        "./src/pages/*"
      ],
      "@utils/*": [
        "./src/utils/*"
      ]
    }
  }
}
```

with a file layout of:
![image](https://github.com/oven-sh/bun/assets/74270733/16a55d4e-5218-4541-83e3-caea08a6c61b)

### What is the expected behavior?

Expected paths to work normally.

### What do you see instead?

```
Failed to compile.

Module not found: Error: Can't resolve '@pages/gptdoc/Gptdoc' in '/Users/psli/Projects/tres/gpt_docs/src'
ERROR in ./src/index.tsx 7:0-42
Module not found: Error: Can't resolve '@pages/gptdoc/Gptdoc' in '/Users/psli/Projects/tres/gpt_docs/src'

webpack compiled with 1 error
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

**Comment by Jarred-Sumner** [comment]
@PaulShiLi the tsconfig is missing [`baseUrl`](https://www.typescriptlang.org/tsconfig#baseUrl):

```patch
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "composite": true,
+   "baseUrl": "./",
    "paths": {
      "@components/*": [
        "./src/components/*"
      ],
      "@pages/*": [
        "./src/pages/*"
      ],
      "@utils/*": [
        "./src/utils/*"
      ]
    }
  }
}
```

**Comment by Jarred-Sumner** [comment]
hm `baseUrl` isn't supposed to be required anymore

**Comment by Sub0X** [comment]
> @PaulShiLi the tsconfig is missing [`baseUrl`](https://www.typescriptlang.org/tsconfig#baseUrl):
> 
> ```diff
> {
>   "compilerOptions": {
>     "target": "ESNext",
>     "lib": [
>       "dom",
>       "dom.iterable",
>       "esnext"
>     ],
>     "allowJs": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "noFallthroughCasesInSwitch": true,
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "jsx": "react-jsx",
>     "composite": true,
> +   "baseUrl": "./",
>     "paths": {
>       "@components/*": [
>         "./src/components/*"
>       ],
>       "@pages/*": [
>         "./src/pages/*"
>       ],
>       "@utils/*": [
>         "./src/utils/*"
>       ]
>     }
>   }
> }
> ```

Hmm... Even with baseUrl, it doesn't seem to work

**Comment by Sub0X** [comment]
It seems like the default webpack has issues with path mapping so I switched to vite which then worked.
