### ISSUE TITLE
--exact option in bunfig.toml not working

### ISSUE THREAD

**Issue by Kleywalker** [oven-sh/bun#7473]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

Add [install exact](https://bun.sh/docs/runtime/bunfig#install-exact) option to bunfig.toml
```toml
[install]
exact = false
```

### What is the expected behavior?

`bun add` adds exact versions to package.json.

### What do you see instead?

`exact` option is ignored.

**Comment by Kleywalker** [comment]
Related to [this](https://github.com/oven-sh/bun/issues/5405) issue.

**Comment by ZenVoich** [comment]
Frustrating bug

**Comment by Kleywalker** [comment]
This issue exists in revision 1.0.16+800fb1290
