### ISSUE TITLE
bun is vulnerable to hijacking and typosquatting

### ISSUE THREAD

**Issue by RodrigoDornelles** [oven-sh/bun#7491]
**bun is vulnerable to hijacking and typosquatting**, as it is implicit that when typing a command that does not exist `bun lint` it will look for npmjs to download and execute <https://www.npmjs.com/package/lint>, just like me must be a common mistake.

_Originally posted by @RodrigoDornelles in https://github.com/oven-sh/bun/issues/6730#issuecomment-1842694950_

**Comment by Jarred-Sumner** [comment]
> typing a command that does not exist bun lint it will look for npmjs to download and execute https://www.npmjs.com/package/lint

This is not correct. 

Running `bun lint` in your terminal does not install or download the npm `lint` package.  If it does, that is a bug. Can you paste what you're seeing in your terminal that led you to think that? I will re-open if this is reproducible.

Importing can auto install packages using [auto-install](https://bun.sh/docs/runtime/autoimport), but that currently does not run postinstall scripts.
