### ISSUE TITLE
Segmentation fault on "bun cdk diff" (regression, worked fine on 1.0.14)

### ISSUE THREAD

**Issue by zenshidev** [oven-sh/bun#7496]
### What version of Bun is running?

1.0.15

### What platform is your computer?

Linux DESKTOP-LVO7EBH 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What steps can reproduce the bug?

1. Clone https://github.com/zenshixd/mirrored-poe-trade
2. `bun i` in root directory
3. `cd infra`
4. `bun cdk diff`

No need for aws credentials, it segfaults anyway.

### What is the expected behavior?

cdk diff runs as expected

### What do you see instead?

Segmentation fault, no cdk diff.
```
ubuntu@DESKTOP-LVO7EBH:~/Projects/mirrored-poe-trade/infra$ bun cdk diff
$ cdk diff
Segmentation fault

Subprocess exited with error 139
error: script "cdk" exited with code 1 (SIGHUP)
```

### Additional information

It worked fine on 1.0.14.

**Comment by paperclover** [comment]
Duplicate of #5398
