### ISSUE TITLE
Linux ARM64/Aarch64 support

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#75]
Gives "Exec format error" on an arm64 machine :(

**Comment by Jarred-Sumner** [comment]
Is this on Linux arm64 or on macOS? It should run successfully on macOS so long as the arm64 binary is downloaded (which is detected automatically in the installer)

If you tried to use an x64 binary from another machine it wouldn't work though

**Comment by ghost** [comment]
> Is this on Linux arm64 or on macOS? It should run successfully on macOS so long as the arm64 binary is downloaded (which is detected automatically in the installer)
> 
> If you tried to use an x64 binary from another machine it wouldn't work though

It is Linux arm64 (OCI Ampere A1). And I ran the installer.

**Comment by Jarred-Sumner** [comment]
I am not going to prioritize this right now. However, if you want to build bun for linux arm64, you can use the docker image in the repo and it should work. It works on my M1 machine

**Comment by ghost** [comment]
> I am not going to prioritize this right now. However, if you want to build bun for linux arm64, you can use the docker image in the repo and it should work. It works on my M1 machine

Okay, thanks.

**Comment by Jarred-Sumner** [comment]
Bun should do this sometime soon

**Comment by ghost** [comment]
> Bun should do this sometime soon

finally :D

**Comment by leap0x7b** [comment]
Maybe we can use the darwin-aarch64 target but modify it to work on a Linux environment

**Comment by leap0x7b** [comment]
Bun 0.1.5 is released with Linux aarch64 support. Can someone close this issue as resolved?

**Comment by Jarred-Sumner** [comment]
Done, but Android ARM64 will need a separate build because this build is for glibc and not bionic

**Comment by leap0x7b** [comment]
Maybe also do builds for musl (both static and not static, like x86_64-musl and x86_64-musl-static)

**Comment by joshcangit** [comment]
> Done, but Android ARM64 will need a separate build because this build is for glibc and not bionic

It seems the pre-built binary also won't work if system is not FHS compliant, e.g., Termux.

I think the build dependencies are `zig`, `automake` & `libtool`.
Other than **macOS**, I don't know where to find build instructions.

**Comment by mattleonowicz** [comment]
Raspberry Pi 3 has "armv7". Any change to support that too?

**Comment by joshcangit** [comment]
> Raspberry Pi 3 has "armv7". Any change to support that too?

The rpi3 uses `arm7h` but `aarch64` also works.
I'm using rpi2 which is only `arm7h`.

**Comment by mattleonowicz** [comment]
I'm not an expert on these architectures, so I might be wrong. But I have a Raspberry Pi 3 A+ with normal Raspbian installed, and `uname -ms` returns `Linux armv7l`. Using newest bun gives me the same "Exec format error" on it, so I thought it might be related

**Comment by mattleonowicz** [comment]
Now that I think of it, I have installed a 32 bit version of "Raspberry Pi OS" - could that be a reason?

**Comment by Toby222** [comment]
> Now that I think of it, I have installed a 32 bit version of "Raspberry Pi OS" - could that be a reason?

Yep
`uname` lists the version of the installed kernel. You've got a 32-bit OS installed on a 64-bit Processor.

**Comment by leap0x7b** [comment]
> Raspberry Pi 3 has "armv7". Any change to support that too?

Raspberry Pi 3 and later doesn't actually have an ARMv7 processor, it has an Aarch64 processor. You probably need to install a 64-bit OS so `uname` properly detects the processor as an Aarch64 processor.

**Comment by lynn2910** [comment]
Do you know if it is planned to support 32-bit platforms?

**Comment by leap0x7b** [comment]
> Do you know if it is planned to support 32-bit platforms?

Maybe not

**Comment by adonespitogo** [comment]
> Maybe not

Why not? Is there a technical obstacle that prevents this?

**Comment by daedlock** [comment]
What's the status on this? I cant use bun on aarch64 linux yet!

**Comment by daedlock** [comment]
```
curl -fsSL https://bun.sh/install | bash
```

Worked for me on aarch64 (Arch linux)

**Comment by harttman** [comment]
> ```
> curl -fsSL https://bun.sh/install | bash
> ```
> 
> Працювало для мене на aarch64 (Arch linux)

Termux or pc?

**Comment by harttman** [comment]
root@localhost:~# bun index.js                        Illegal instruction                                   root@localhost:~#

**Comment by donnaken15** [comment]
I'm trying to run this on a pi 3 model B+, `uname` says its `armv71`
I also tried the homepage command and downloading the aarch64 version
![image](https://github.com/user-attachments/assets/198122eb-49f4-4831-be96-de33bede81d7)

**Comment by Toby222** [comment]
> I'm trying to run this on a pi 3 model B+, `uname` says its `armv71` I also tried the homepage command and downloading the aarch64 version ![image](https://private-user-images.githubusercontent.com/20864393/355529665-198122eb-49f4-4831-be96-de33bede81d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDcyMTcsIm5iZiI6MTcyMzIwNjkxNywicGF0aCI6Ii8yMDg2NDM5My8zNTU1Mjk2NjUtMTk4MTIyZWItNDlmNC00ODMxLWJlOTYtZGUzM2JlZGU4MWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEyMzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzg1OWViMGFiM2MxYzJiZWVkN2Y2ZjFkMDQwOGQwMDFkZTk2NDExMjQ3YjQ1YTRhNmZjOTc4MTNjMjcwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cj81wEZVMqZWM0wJUS9I9uqdG4-DtS2OvV8v1RBPl9c)

armv71 is 32 bit, not relevant to this issue

**Comment by donnaken15** [comment]
> > I'm trying to run this on a pi 3 model B+, `uname` says its `armv71` I also tried the homepage command and downloading the aarch64 version ![image](https://private-user-images.githubusercontent.com/20864393/355529665-198122eb-49f4-4831-be96-de33bede81d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDcyMTcsIm5iZiI6MTcyMzIwNjkxNywicGF0aCI6Ii8yMDg2NDM5My8zNTU1Mjk2NjUtMTk4MTIyZWItNDlmNC00ODMxLWJlOTYtZGUzM2JlZGU4MWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEyMzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYzg1OWViMGFiM2MxYzJiZWVkN2Y2ZjFkMDQwOGQwMDFkZTk2NDExMjQ3YjQ1YTRhNmZjOTc4MTNjMjcwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cj81wEZVMqZWM0wJUS9I9uqdG4-DtS2OvV8v1RBPl9c)
> 
> armv71 is 32 bit, not relevant to this issue

I just found out, stupid thing has Raspbian 32-bit installed by default but my processor is 64-bit

**Comment by Toby222** [comment]
(I did the same thing when I first got a raspi :⁾)
