### ISSUE TITLE
Please make it working : node-fs. 

### ISSUE THREAD

**Issue by tahonaPL** [oven-sh/bun#750]
### What is the problem this feature will solve?

Great this is amazing project. But there is a problem with most basic components: node-fs. Is there alternative that will work?

this is mandatory to make switch from node js to bum. 

### What is the feature you are proposing to solve the problem?

69 |    * Polymorphic approach to fs.mkdir()
70 |    *
71 |    * If the third parameter is boolean and true assume that
72 |    * caller wants recursive operation.
73 |    */
74 |   fs.mkdir = function (path, mode, recursive, callback) {
      ^
 TypeError: Attempted to assign to readonly property.
      at ...../node_modules/node-fs/lib/fs.js:74:2

### What alternatives have you considered?

or please create feature that can replace node-fs api.

**Comment by Jarred-Sumner** [comment]
The bug here is that `fs` is marked as readonly when it should not be

**Comment by tahonaPL** [comment]
What about this error:

error: Cannot find package "dgram" from "bun:wrap"

**Comment by xhyrom** [comment]
> The bug here is that `fs` is marked as readonly when it should not be

For now you can fix it by adding `fs = Object.assign({}, fs)` to the module

^ for modules that expands fs

**Comment by tahonaPL** [comment]
> > The bug here is that `fs` is marked as readonly when it should not be
> 
> For now you can fix it by adding `fs = Object.assign({}, fs)` to the module

You mean to ??

import { MongoClient } from "mongodb";

**Comment by skerit** [comment]
The same error occurs for other built in node.js modules, like `module`. That's also read-only:

![afbeelding](https://user-images.githubusercontent.com/755212/186748576-ccd1302d-74dd-4571-91b6-217e15bf94bf.png)

**Comment by Jarred-Sumner** [comment]
This should've been fixed some time ago. Please comment if you run into it again

**Comment by TechFun4** [comment]
error: Cannot find package "dgram" from "bun:wrap" still occurs even with version 0.3.0. I am trying to use the node module, mongoose.

**Comment by mia-z** [comment]
Getting error: Cannot find package "dgram" from "bun:wrap" whene trying to use ioredis module. Bun v0.3.0

**Comment by Jarred-Sumner** [comment]
Will make a separate issue for tracking dgram, as that is unrelated to the package in this issue
