### ISSUE TITLE
Bun.stdin.text() does not read complete input

### ISSUE THREAD

**Issue by obedm503** [oven-sh/bun#7500]
### What version of Bun is running?

1.0.15

### What platform is your computer?

Linux 6.5.6-76060506-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
const lines: string[] = (await Bun.stdin.text()).split("\n");

console.log(lines.length);
```

then pipe in a [large file](https://github.com/obedm503/bun-stdin-bug-repro/blob/master/big.txt)

```sh
cat big.txt | bun run bug.ts
```

### What is the expected behavior?

The expected output is `141` 

### What do you see instead?

The real output is `30` 

### Additional information

Reproduction repo https://github.com/obedm503/bun-stdin-bug-repro

**Comment by Jarred-Sumner** [comment]
Can you try again in the canary build of Bun?

**Comment by obedm503** [comment]
The issue persists after `bun upgrade --canary`.

**Comment by obedm503** [comment]
Happy to report that the bug is indeed fixed. Thanks @Jarred-Sumner and team.
