### ISSUE TITLE
TS Transpiler doesn't remove `export` keyword from nested `export namespace` declarations

### ISSUE THREAD

**Issue by jhmaster2000** [oven-sh/bun#751]
### Version

0.1.4

### Platform

`Linux DESKTOP-A7ND7QS 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What steps will reproduce the bug?

Given the following `sample.ts` file:
```ts
module foo {
    export namespace bar {
        export const baz = 123;
    }
}
console.log(foo.bar.baz);
```
Or the following `sample2.ts` file:
```ts
export namespace bob {
    export namespace sub {
        export const pop = 456;
    }
}
console.log(bob.sub.pop);
```
Run with `bun run sample.ts` / `bun run sample2.ts`

### How often does it reproduce? Is there a required condition?

Whenever the combination of keywords `export namespace` is used within a nested scope, such as a `module` or parent `namespace`, as shown by `sample2.ts`, where the error happens on the `export namespace sub {` line but not the first.

For example, the following code is fine, since the `export namespace` is in the top level and has no nested exported namespaces:
```ts
export namespace bob {
    export const pop = 456;
}
console.log(bob.pop);
```

### What is the expected behavior?

As can be seen in [this TS Playground link](https://www.typescriptlang.org/play?target=99&jsx=0&allowSyntheticDefaultImports=true&noImplicitUseStrict=true#code/LYewJgrgNgpgBAMxCOBvAUHLcYA8AOIATgC5wB2AhsDAM76UDG8ARpUWptt3oaXIxDlaZNgC84AXjgBGAEwBmANxcsAX3QbBwkLAB0UEAHMAFEhB62RS5TEBKFUA), the following is the correct transpiled code for `sample.ts`:
```js
var foo;
(function (foo) {
    let bar;
    (function (bar) {
        bar.baz = 123;
    })(bar = foo.bar || (foo.bar = {}));
})(foo || (foo = {}));
console.log(foo.bar.baz);
```

### What do you see instead?

The following is the output of `bun build sample.ts`: (Compare line 3 with the one of the above output)
```js
var foo;
(function(foo) {
  export let bar;
  (function(bar) {
    bar.baz = 123;
  })(bar = foo.bar || (foo.bar = {}));
})(foo || (foo = {}));
console.log(foo.bar.baz);
```

### Additional information

The following dirty workaround works to bypass the issue:
```ts
module foo {
    namespace _bar {
        export const baz = 123;
    }
    export const bar = _bar;
}
console.log(foo.bar.baz);
```
Transpiles to:
```js
var foo;
(function(foo) {
  let _bar;
  (function(_bar) {
    _bar.baz = 123;
  })(_bar || (_bar = {}));
  foo.bar = _bar;
})(foo || (foo = {}));
console.log(foo.bar.baz);
```

**Comment by Electroid** [comment]
This has now been fixed, as of `0.2.2`.

`bun build index.ts`

Input:
```ts
module foo {
    export namespace bar {
        export const baz = 123;
    }
}
console.log(foo.bar.baz);
```

Output:
```js
var foo;
(function(foo) {
  let bar;
  (function(bar) {
    bar.baz = 123;
  })(bar = foo.bar || (foo.bar = {}));
})(foo || (foo = {}));
console.log(foo.bar.baz);
```
