### ISSUE TITLE
package.json import maps are not resolving - resolves in Node

### ISSUE THREAD

**Issue by sannajammeh** [oven-sh/bun#7524]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

1. open an empty folder
2. create package.json
3. `bun install p-limit@5.0.0`
4. Copy this into index.mjs
```js
import "p-limit";

console.log("Hello World!");
```
6. `bun index.js` - watch it fail on error: Cannot find package "#async_hooks"
7. `node index.mjs` - observe hello world logged

### What is the expected behavior?

Bun should recognise the `imports` field in package.json

### What do you see instead?

Bun does not resolve internal package exports correctly.

### Additional information

Works in Node 20.

**Comment by Jarred-Sumner** [comment]
Please run `bun upgrade --canary` and try again

This was fixed in #7505
