### ISSUE TITLE
WebSocket `onmessage` returns `data` instead of `MessageEvent`

### ISSUE THREAD

**Issue by bradymadden97** [oven-sh/bun#7525]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Linux 6.2.0-1018-gcp x86_64 unknown

### What steps can reproduce the bug?

Code:
```typescript
import { WebSocket, WebSocketServer } from 'ws'

const wss = new WebSocketServer({ port: 3001 });
wss.on('connection', (ws) => {
  ws.onmessage = (e) => {
    console.log('Logging e.data:', e.data);
    ws.close()
    wss.close()
    process.exit(0);
  };
})


const client = new WebSocket("ws://localhost:3001");
client.onopen = () => {
  client.send('hello world');
}
```

Run the following:
```
~/.bun/bin/bun index.ts
```
Outputs:
```
Logging e.data: undefined
```

Run the following:
```
npx tsx index.ts
```
Outputs:
```
Logging e.data: hello world
```

### What is the expected behavior?

I would expect bun to also return a `MessageEvent`, so I can access the `data` property in the same way as I do when running my code with node. Otherwise, I need to add a special case in my code for Bun vs. Node runtimes.

I expect `onmessage` to return a `MessageEvent` per this spec: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/message_event

I know Bun's native implementation of WebSockets also return the message data directly (https://bun.sh/docs/api/websockets), but I think when using the `ws` package it should follow Node's behavior.

### What do you see instead?

I get undefined when accessing the `data` property, as the _data_ itself is returned directly, rather than within a `MessageEvent`

**Comment by paperclover** [comment]
it is a mistake here:
https://github.com/oven-sh/bun/blob/966b636e5d2026bf535a85860895fab2c004dac1/src/js/thirdparty/ws.js#L686-L692

**Comment by bradymadden97** [comment]
Attached a potential fix!
