### ISSUE TITLE
'bun --bun run dev' fails if SvelteKit app path contains a space.

### ISSUE THREAD

**Issue by mattstanbrell** [oven-sh/bun#7526]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

In /Users/user/spaced folder/projects/
```
bun create svelte@latest example
# options don't matter
cd example
bun install
bun --bun run dev
```

Works if file path is /Users/user/spaced-folder/projects/

### What is the expected behavior?

```
$ vite dev

Forced re-optimization of dependencies

  VITE v4.5.1  ready in 691 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

### What do you see instead?

```
$ vite dev
failed to load config from /Users/matt/spaced folder/projects/example/vite.config.js
error when starting dev server:
undefined
error: script "dev" exited with code 1 (SIGHUP)
```

### Additional information

```
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()]
});
```

I think `import { sveltekit } from '@sveltejs/kit/vite';` in vite.config.js is failing and causing the error. It runs if you remove the `sveltekit()` plugin.

Tested with vite 4.5.1 and 5.0.6

Tested with JS and TS.

`bun run dev` works fine.

`bun --bun run dev` works when you rename 'spaced folder' to 'spaced-folder'.

**Comment by paperclover** [comment]
This feels like a regression of #5100. maybe not because it's specific to SvelteKit plugin

**Comment by paperclover** [comment]
not a regression but it is caused by this code.

<img width="655" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/573b21b2-614f-4032-8f11-2d127a1b4bff">

we assume createRequire isnt given a url string
