### ISSUE TITLE
Issue with "ModuleNotFound" in Bun Build When Using Workers module

### ISSUE THREAD

**Issue by sophie0730** [oven-sh/bun#7534]
### What version of Bun is running?

v1.0.14

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Step 1. Create a bun project. 

Step 2.  Implementing the Worker Module

Create two JavaScript files: main.js and worker.js.
main.js
```
function createWorker(fileName) {
  const url = new URL(`./workers/${fileName}`, import.meta.url);
  const worker = new Worker(url, { type: 'module' });

  worker.onmessage = (event) => {
    console.log(`Message from Worker: ${event.data}`);
  };

  worker.onerror = (error) => {
    console.error('Worker error', error);
    worker.terminate();
    createWorker();
  };

  return worker;
}

const store = createWorker('store.js');

store.postMessage('Start store worker tasks');
```

worker.js
```
self.onmessage = (event) => {
  console.log(`Store worker received: ${event.data}`);
  scheduleStoreExporterMetrices();  //worker's tasks
  scheduleStoreExporterStatus();
  postMessage('Complete store worker tasks');
};
```

Step 3. Bundling with esbuild
```
esbuild ./main.js ./workers/worker.js  --allow-overwrite --bundle --splitting --platform=node --format=esm --outdir=./out
```

Step 4. Compiling with Bun
```
bun build ./out/main.js --compile --target node --outfile=./main
```

### What is the expected behavior?

The main file, once bundled by esbuild, should be successfully compiled using bun:build.

### What do you see instead?

When I run the command 
```
bun build ./out/main.js --compile --target node --outfile=./main
```

I encounter the following error:
```
62577 | 
62578 | // main.js
62579 | var createWorker = function(fileName) {
62580 |   const url = new URL(`./workers/${fileName}`, import.meta.url);
62581 | 
62582 |   const worker = new Worker(url, { type: "module" });
                    ^
TypeError: BuildMessage: ModuleNotFound resolving "compiled://root/workers/worker.js" (entry point)
      at createWorker (compiled://root/main:62582:17)
      at compiled://root/mainr:62593:12
      at processTicksAndRejections (:61:76)
```

This error is unexpected because worker.js should have already been bundled by esbuild, as evidenced by the successful execution of the main file generated by esbuild. Moreover, worker.js should be detectable when running the single executable produced by bun build, as this process is supposed to compile all files in the project.

### Additional information

I've come across several open issues on the Bun repository, but I'm uncertain if they directly pertain to the problem I'm experiencing. It appears that these issues are opening.

https://github.com/oven-sh/bun/issues/7373
https://github.com/oven-sh/bun/issues/7338

**Comment by trawor** [comment]
Plz update this bug progress, so long..

**Comment by heerheer** [comment]
I have the same problem when i try to build with pino but just in windows platform, the same source build can run successfully in my wsl.
![image](https://github.com/oven-sh/bun/assets/22632184/9e704b01-be51-457c-9a2d-bef39d1ae1b8)
