### ISSUE TITLE
[package manager]: `string-width` is resolved incorrectly, causing `ERR_REQUIRE_ESM`

### ISSUE THREAD

**Issue by msonnb** [oven-sh/bun#7539]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

1. see https://github.com/isaacs/jackspeak/issues/5#issuecomment-1532498370
2. run `vite build`

### What is the expected behavior?

the build should pass

### What do you see instead?

`Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/string-width/index.js from /vercel/path0/node_modules/wide-align/align.js not supported.`

### Additional information

Same issue exists in yarn v1:
https://github.com/storybookjs/storybook/issues/22431
https://github.com/isaacs/jackspeak/issues/5

**Comment by kgoedecke** [comment]
@msonnberger did you ever manage to resolve this, we ran into the same issue today.

**Comment by msonnb** [comment]
> @msonnberger did you ever manage to resolve this, we ran into the same issue today.

unfortunately, no :(

**Comment by joeychilson** [comment]
@kgoedecke @msonnberger 

I don't know if you guys still need a fix, but here is what worked for me.

Add the following to package.json

```json 
  "resolutions": {
    "string-width": "4.2.3"
  }
```

**Comment by hyoretsu** [comment]
Bump, this is pretty annoying to encounter

**Comment by themixednuts** [comment]
I have this issue as well when deploying to Vercel, and unfortunately the resolution fix doesn't work
