### ISSUE TITLE
Syntax error on octal escape in tagged template string

### ISSUE THREAD

**Issue by kieran-osgood** [oven-sh/bun#7540]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```
     // index.cjs / index.js
     const assert = require("assert")
     assert.equal(String.raw`/\1`.length, 3);

```

Then run it with `bun index.cjs`

### What is the expected behavior?

Syntax is valid
```
➜ node index.cjs
```

### What do you see instead?
```
➜ bun index.cjs
5 | assert.equal(String.raw`/\1`.length, 3);
                           ^
error: Syntax Error!!

```

**Comment by paperclover** [comment]
<img width="865" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/4242ce8d-0f15-4bd7-bb9b-df532f05f363">
when it is not a template, it seems this is meant to be an error

obviously when it is a template, this is allowed, but it seems the parser is not aware of this.

cc @dylan-conway

**Comment by paperclover** [comment]
reduced reproduction, run `bun build demo.ts`
```
a`\1`
```

**Comment by alexop1000** [comment]
Bump, causes issues in NextJS when importing a client-rendered component from a server-rendered one.

**Comment by TechnologicNick** [comment]
Also fails on invalid `\u0000` with less than 4 hexadecimals and `\x00` with less than 2 hexadecimals.

**Comment by devunt** [comment]
This issue blocks usage of [shiki](https://shiki.style) in bun.

**Comment by Jarred-Sumner** [comment]
Fixed by @pfgithub
