### ISSUE TITLE
`bun add` or `bun install` ALWAYS hoists packages in workspace/monorepo

### ISSUE THREAD

**Issue by ansh** [oven-sh/bun#7547]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Create a bun monorepo
```
{
  "name": "my-project",
  "private": true,
  "workspaces": [
    "backend",
    "frontend"
  ]
}
```
2. In this example, I have a `frontend` and `backend` folder that hosts two apps. The backend is an `express` app and the frontend is a `react-native` app.
3. If I `cd backend` or `cd frontend` into a directory and run `bun add uuid` (`uuid` is just an example package), it creates a `"dependencies"` object in my root `package.json` which doesn't make sense. The package doesn't need to be hoisted if it is just being used in one package. This happens no matter which package I try installing.

### What is the expected behavior?

The package is added to `frontend/package.json` or `backend/package.json` depending on what the `cwd` is but not in the root `package.json`

### What do you see instead?

The package is in the root `package.json` like this:

{
  "name": "my-project",
  "private": true,
  "workspaces": [
    "backend",
    "frontend"
  ],
  "dependencies": {
   "uuid": "^9.0.0"
  }
}

**Comment by robertherber** [comment]
I'm getting a slightly different behaviour:
- When running "bun install a-package" it gets added to the root package.json even when run in one of the workspaces.
- When running "bun add a-package" it does get added to the expected (cwd) package.json. BUT then the lockfile gets messed up (seems to only contain dependencies of the (cwd) package.json after this - I need to run a new `bun install` to fix it). (Added a new issue #7844 for this since it could probably be considered a separate issue)

Note: I'm specifying my workspace slightly different:
```JSON
"workspaces": [
  "apps/*",
  "packages/*"
],
```

**Comment by adiologydev** [comment]
I can replicate this issue in a mono-repo using `bun install`. Any new packages added within a repo are hoisted to the root instead.

`bun add` works correctly though in terms of the packages being added to the repo as @robertherber mentioned.

**Comment by varna** [comment]
I have to add packages via `bun add <pkg>`, which corrupts the lockfile. Then I have to run `bun i`.

`bun.lockb` file is missing in child repos.

I use this script for now:
```JSON
{
  "scripts": {
    "predev": "bun i && cp ../../bun.lockb ."
  }
}
  ```

**Comment by robertherber** [comment]
[Related solution here until bun supports monorepos fully](https://github.com/oven-sh/bun/issues/5413#issuecomment-1936234060), use it by installing `@zemble/utils` and running `bun add-safe <pkg-name>` or simply copying the script to your project :)

**Comment by adiologydev** [comment]
> [Related solution here until bun supports monorepos fully](https://github.com/oven-sh/bun/issues/5413#issuecomment-1936234060), use it by installing `@zemble/utils` and running `bun add-safe <pkg-name>` or simply copying the script to your project :)

Thank you for this @robertherber, we'll use this script for the time being.

Hoping @Jarred-Sumner has a native fix for this coming soon! 🤞🏼

**Comment by stefanosandes** [comment]
I don't know if it is related, but I have a monorepo with some Next.js applications. Bun is hoisting the `node_modules/.bin/next` directory, which causes a lot of errors when I want to build my project. In development mode, everything works. Copying the `node_modules/.bin/next` from another project makes the build work.

**Comment by XavierGeerinck** [comment]
I just wanted to also +1 this. We are using `bun` at the moment through `turbo` and honestly, getting a Docker container ready and using it dev wise has been the most painful experience ever.

**Comment by dylan-conway** [comment]
> Closed without explaining fix..? 😭 Still happening to me... Not sure what I'm doing wrong.

Sorry, the PR fixing this issue also fixed many others and they weren't all commented on. What issue are you seeing? Could you share your workspace setup (`workspaces` and dependencies in each package.json)? Feel free to open another issue, I'm happy to take a  look.

**Comment by redbmk** [comment]
@dylan-conway I'm still seeing this issue. Here's an example:

- `mkdir bun-workspace-test && cd bun-workspace-test`
- `bun init -y`
- add `"workspaces": ["packages/*"]` to 
- `mkdir -p packages/a && (cd packages/a && bun add remix)`
- `mkdir -p packages/b && (cd packages/b && bun add next)`
- 
  ```
  ❯ ls packages/a/node_modules
  ls: packages/a/node_modules: No such file or directory
  ❯ ls packages/b/node_modules
  ls: packages/b/node_modules: No such file or directory
  ❯ ls node_modules | grep -E 'next|remix'
  @next
  next
  remix
  ```

The docs (https://bun.sh/docs/install/workspaces) mention:

> **Dependencies can be de-duplicated.** If `a` and `b` share a common dependency, it will be hoisted to the root `node_modules` directory. This reduces redundant disk usage and minimizes "dependency hell" issues associated with having multiple versions of a package installed simultaneously.

The way I read that, just the shared dependencies should be hoisted, not all dependencies.

**Comment by dylan-conway** [comment]
@redbmk `bun install` will hoist packages by default, even if it isn't shared with another workspace. We are planning to implement an option for configuring this (you can follow along here #6850). What it will look like is undecided, but likely it will be the same or similar to `workspaces.nohoist` in package.json.
