### ISSUE TITLE
Node.js `imports` in `package.json` isn't working

### ISSUE THREAD

**Issue by riywo** [oven-sh/bun#7553]
### What version of Bun is running?

1.0.15

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

foo.mjs:
```js
import {} from "p-limit";
```

```
$ bun run foo.mjs
error: Cannot find package "#async_hooks" from ".../node_modules/p-limit/index.js"
```

package.json of `p-limit`:
```
{
	"name": "p-limit",
	"version": "5.0.0",
	"description": "Run multiple promise-returning & async functions with limited concurrency",
	"license": "MIT",
	"repository": "sindresorhus/p-limit",
	"funding": "https://github.com/sponsors/sindresorhus",
	"author": {
		"name": "Sindre Sorhus",
		"email": "sindresorhus@gmail.com",
		"url": "https://sindresorhus.com"
	},
	"type": "module",
	"exports": {
		"types": "./index.d.ts",
		"default": "./index.js"
	},
	"imports": {
		"#async_hooks": {
			"node": "async_hooks",
			"default": "./async-hooks-stub.js"
		}
	},
```

`imports` looks Node.js's API: https://nodejs.org/api/packages.html#imports

### What is the expected behavior?

No error when importing.

### What do you see instead?

```
error: Cannot find package "#async_hooks" from ".../node_modules/p-limit/index.js"
```

### Additional information

I just tried `bunx --bun astro dev` on my Astro repository but couldn't run it due to this error. https://bun.sh/guides/ecosystem/astro

**Comment by Jarred-Sumner** [comment]
This was fixed in canary. Please run `bun upgrade —canary` or try upgrading tomorrow

**Comment by riywo** [comment]
Yes, canary worked! Thanks!
