### ISSUE TITLE
Client-side assets in Next.js example are 404ing 

### ISSUE THREAD

**Issue by saurabhburade** [oven-sh/bun#756]
### Version

0.1.4

### Platform

Darwin Saurabhs-MacBook-Air.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

- Create the next app from examples  `bun create next ./next-app`
- Run the `bun dev` command to start the app in the dev environment.
- Add `useEffect` to the Home component
- Refresh the page on the browser

```
import React, { useEffect } from "react";
export default function Home({}) {
 useEffect(() => {
    console.log("hello world");
  }, []);
  return (
    <main className="p-10 m-5">
      <h1 className="text-xl font-bold">Welcome to Next.js!</h1>
    </main>
  );
} 
```

### How often does it reproduce? Is there a required condition?

Need to add useEffect to the component.

### What is the expected behavior?

`hello world` on the console.

### What do you see instead?

<img width="1440" alt="Screenshot 2022-07-17 at 10 15 30 AM" src="https://user-images.githubusercontent.com/39492927/179384520-b71db3ff-0164-4aa7-a777-7c05601611f0.png">

**Comment by Jarred-Sumner** [comment]
The bug here is not that useEffect didn't work

The 404 means the page was only serverside-rendered

The question is why

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
