### ISSUE TITLE
console.log do not print the right result for `%d` and using the `valueOf`

### ISSUE THREAD

**Issue by WingLim** [oven-sh/bun#7561]
### What version of Bun is running?

1.0.15

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Execute this file

```js
console.log("%s", { toString: () => "23", valueOf: () => 21 })
console.log("%d", { toString: () => "23", valueOf: () => 21 })
```

### What is the expected behavior?

```
23
21
```

### What do you see instead?

```
23
0
```

### Additional information

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive#description

When the hint is number, we should call `valueOf` then `toString`.

**Comment by Jarred-Sumner** [comment]
This is fixed in the canary build. Please run `bun upgrade --canary` and try again
