### ISSUE TITLE
Remove `run` keyword from CLI when running scripts

### ISSUE THREAD

**Issue by alamenai** [oven-sh/bun#7566]
### What is the problem this feature would solve?

Hi Bun,

This is my first time trying Bun and I would say it's an incredible project!

I would see this feature from [pnpm](https://pnpm.io/installation) when it comes to run scripts, so instead of having the `run` keyword in each CLI command, we can just name the script directly:

### Current

`bun run start`

`bun run test`

### Desired

`bun start`

`bun test`

### What is the feature you are proposing to solve the problem?

Let Bun add `run` internally instead of explicitly written by the developer.

### What alternatives have you considered?

I don't have any alternative to consider for this feature.

**Comment by Jarred-Sumner** [comment]
This already works, except when the subcommand conflicts with a name of a command in bun (like bun build or bun test)
