### ISSUE TITLE
`bun build` doesn't use "bun" export condition

### ISSUE THREAD

**Issue by RiskyMH** [oven-sh/bun#7573]
### What version of Bun is running?

1.0.16+800fb1290

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. create monorepo
2. in a package (ie "pkg1") export the code using both "bun" and "import" (note that bun is first)
3. run bun build in another package (ie pkg2) using the first package

### What is the expected behavior?

The bundled code in pkg2 to use code from pkg1's "bun" export statement.

### What do you see instead?

it uses from "import" 

### Additional information

I am not sure if it is a bug, but considering it was mentioned in the docs (under runtime), I assume it should work for both.

**Comment by Jarred-Sumner** [comment]
Set `--target=bun`
