### ISSUE TITLE
bun repl: Cannot find module "colors"

### ISSUE THREAD

**Issue by JacksonKearl** [oven-sh/bun#7595]
### What version of Bun is running?

1.0.16+800fb1290

### What platform is your computer?

Darwin 22.2.0 arm64 arm

### What steps can reproduce the bug?

```
$ bun repl
error: Cannot find module "./colors" from "/private/tmp/bun-repl@latest--bunx/node_modules/bun-repl/src/cli.ts"
```

### What is the expected behavior?

repl opens

### What do you see instead?

colors error

**Comment by JacksonKearl** [comment]
This popped up randomly after I had been using bun-repl every day for quite some time. Running `bun upgrade` did not fix it, but after restarting my computer the error went away.

**Comment by nicolasdesentryfy** [comment]
Hey, I found a workaround. Just remove the bun-repl@latest--bunx directory in /private/tmp and execute again the bun command, that should fix it.
