### ISSUE TITLE
`bun add` fails when adding tarballs in a workspace subpackage

### ISSUE THREAD

**Issue by andymatuschak** [oven-sh/bun#7608]
### What version of Bun is running?

1.0.17+5e60861c3

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```zsh
git clone git@github.com:andymatuschak/bun-tarball-workspace-bug.git

cd bun-tarball-workspace-bug/without-workspaces
# this works:
bun add ../dummy-1.0.0.tgz

cd ../with-workspaces
# this works, too, in the root of the workspace
bun add ../dummy-1.0.0.tgz

cd packages/subpackage
# but adding tarballs fails when in a workspace subpackage
bun add ../../../dummy-1.0.0.tgz
```

Link for easy browsing: https://github.com/andymatuschak/bun-tarball-workspace-bug

### What is the expected behavior?

All three `bun add` invocations should pass.

### What do you see instead?

Only the first two `bun add` invocations succeed (in a package without a workspace, and in the root of a workspace).

The third (in a workspace subpackage) fails:
```
bun add v1.0.17 (5e60861c)
  🔍 Resolving [1/1] error: FileNotFound extracting tarball for ../../dummy-1.0.0.terror: ../../dummy-1.0.0.tgz failed to resolve
```

### Additional information

May be related to intermittent complaints of tarball failures in #101, but here's a minimal repro for you all.

**Comment by Jarred-Sumner** [comment]
The bug is that tarballs and `file:` are being resolved relative to the workspace root's package.json, instead of relative to the workspace member's package.json

A workaround for now is to `bun add` relative to the workspace root instead of the actual workspace package's folder
