### ISSUE TITLE
bun build only takes up to 3 files

### ISSUE THREAD

**Issue by hanselke** [oven-sh/bun#7616]
### What version of Bun is running?

1.0.18

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

this package.json scripts works
`    "bunB": "bun build ./src/FlopPoker.ts ./src/TrainerFP.ts ./src/Dealer.ts --outdir ./dist --target bun && bun build  ./src/Trainer.ts --outdir ./dist --target bun"`

but if i tried with 4 in a row it wont handle the first one.

### What is the expected behavior?

it should handle entire array, actually ideally it would accept a src wildcard or a tsconfig file is even better

### What do you see instead?

it would not build the first file if i put 4 files in a row

### Additional information

i'm using worker_thread

**Comment by paperclover** [comment]
cant reproduce this based on description. this script creates 5 js files and bundles them all
```
mkdir src/
echo 'console.log(1)' > src/a.ts
echo 'console.log(2)' > src/b.ts
echo 'console.log(3)' > src/c.ts
echo 'console.log(4)' > src/d.ts
echo 'console.log(5)' > src/e.ts

bun build src/a.ts src/b.ts src/c.ts src/d.ts src/e.ts --outdir out --target bun
```
