### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by SaDi-BRo** [oven-sh/bun#762]
### Platform

Linux arch 5.18.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:02 +0000 x86_64 GNU/Linux

### What do you see instead?

![image](https://user-images.githubusercontent.com/75570557/179396487-1f062ad2-5625-4b5d-91b0-e622c350a0b1.png)

I got this error. I just installed bun, and tried to use

**Comment by xhyrom** [comment]
From [bun discord bot](https://github.com/xHyroM/bun-discord-bot):
---

**Illegal instruction - core dumped**

Bun currently only works on CPUs supporting the AVX2 instruction set.
There is nothing you can do about it at the moment, you can only wait.
However, there are plans to make a build that doesn't need AVX2 ([#67](<https://github.com/oven-sh/bun/issues/67>))

**NOT RECOMMENDED (VERY SLOW ALTERNATIVE)**:
To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support.
If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.

**1.** Install intel-sde:
   • Arch Linux: `yay -S intel-sde`
   • Other Distros:
```bash
wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
cd /tmp
tar -xf intel-sde.tar.xz
cd sde-external*
mkdir /usr/local/bin -p
cp sde64 /usr/local/bin/sde
cp -r intel64 /usr/local/bin/
cp -r misc /usr/local/bin/
```

**2.** Add alias to bashrc
   • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`

**Comment by FinnRG** [comment]
Duplicate of #67.

**Comment by SaDi-BRo** [comment]
> ## From [bun discord bot](https://github.com/xHyroM/bun-discord-bot):
> **Illegal instruction - core dumped**
> 
> Bun currently only works on CPUs supporting the AVX2 instruction set. There is nothing you can do about it at the moment, you can only wait. However, there are plans to make a build that doesn't need AVX2 ([#67](https://github.com/oven-sh/bun/issues/67))
> 
> **NOT RECOMMENDED (VERY SLOW ALTERNATIVE)**: To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support. If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.
> 
> **1.** Install intel-sde: • Arch Linux: `yay -S intel-sde` • Other Distros:
> 
> ```shell
> wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
> cd /tmp
> tar -xf intel-sde.tar.xz
> cd sde-external*
> mkdir /usr/local/bin -p
> cp sde64 /usr/local/bin/sde
> cp -r intel64 /usr/local/bin/
> cp -r misc /usr/local/bin/
> ```
> 
> **2.** Add alias to bashrc • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`

Thanks. That's worked🎉

**Comment by xhyrom** [comment]
> > ## From [bun discord bot](https://github.com/xHyroM/bun-discord-bot):
> > **Illegal instruction - core dumped**
> > Bun currently only works on CPUs supporting the AVX2 instruction set. There is nothing you can do about it at the moment, you can only wait. However, there are plans to make a build that doesn't need AVX2 ([#67](https://github.com/oven-sh/bun/issues/67))
> > **NOT RECOMMENDED (VERY SLOW ALTERNATIVE)**: To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support. If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.
> > **1.** Install intel-sde: • Arch Linux: `yay -S intel-sde` • Other Distros:
> > ```shell
> > wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
> > cd /tmp
> > tar -xf intel-sde.tar.xz
> > cd sde-external*
> > mkdir /usr/local/bin -p
> > cp sde64 /usr/local/bin/sde
> > cp -r intel64 /usr/local/bin/
> > cp -r misc /usr/local/bin/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **2.** Add alias to bashrc • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`
> 
> Thanks. That's worked🎉

now, you can just use `bun upgrade` becasue there are no AVX2 builds

**Comment by SaDi-BRo** [comment]
> > > ## From [bun discord bot](https://github.com/xHyroM/bun-discord-bot):
> > > **Illegal instruction - core dumped**
> > > Bun currently only works on CPUs supporting the AVX2 instruction set. There is nothing you can do about it at the moment, you can only wait. However, there are plans to make a build that doesn't need AVX2 ([#67](https://github.com/oven-sh/bun/issues/67))
> > > **NOT RECOMMENDED (VERY SLOW ALTERNATIVE)**: To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support. If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.
> > > **1.** Install intel-sde: • Arch Linux: `yay -S intel-sde` • Other Distros:
> > > ```shell
> > > wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
> > > cd /tmp
> > > tar -xf intel-sde.tar.xz
> > > cd sde-external*
> > > mkdir /usr/local/bin -p
> > > cp sde64 /usr/local/bin/sde
> > > cp -r intel64 /usr/local/bin/
> > > cp -r misc /usr/local/bin/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **2.** Add alias to bashrc • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`
> > 
> > Thanks. That's worked🎉
> 
> now, you can just use `bun upgrade` becasue there are no AVX2 builds 

I have already latest version. It hasn't upgraded
