### ISSUE TITLE
npm pre & postinstall scripts of dependencies are not being found, tries to execute them from project root

### ISSUE THREAD

**Issue by iJigg** [oven-sh/bun#7626]
### What version of Bun is running?

1.0.16+800fb1290

### What platform is your computer?

075050162388.dkr.ecr.eu-central-1.amazonaws.com/platform/docker-base-images/node-16-node:latest

### What steps can reproduce the bug?

Run bun install in project with dependency that have pre/post install scripts in their package.json

### What is the expected behavior?

For pre/post install scripts to be run appropriately for each dependency

### What do you see instead?

pre/post install scripts are not being found as the path the scripts is `/example-project/scripts/preinstall.js` instead of `/example-project/node_modules/example-dependency/scripts/preinstall.js`

Example: 

```
bun install v1.0.17 (5e60861c)
 Resolving dependencies
 Resolved, downloaded and extracted [2850]
Error: Cannot find module '/builds/example-project/scripts/preinstall.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error: preinstall script from "example-dependency" exited with code 1 (SIGHUP)
```

example-dependency has a preinstall script that's specified in their package.json file 
```
  "scripts": {
    "preinstall": "node scripts/preinstall.js",
```

and the example-dependency has a proper scripts/preinstall.js script. Installing with npm works properly

**Comment by iJigg** [comment]
Adding all problematic dependencies as **trustedDependencies** does not change the issue

**Comment by Jarred-Sumner** [comment]
I believe this was fixed in https://github.com/oven-sh/bun/pull/7622

To upgrade, run `bun upgrade --canary`. Let us know if you're still seeing this issue.

**Comment by iJigg** [comment]
Issue persists with v1.0.18 (36c316a2)

**Comment by Jarred-Sumner** [comment]
Can you provide a more complete reproduction?

**Comment by iJigg** [comment]
I've created a simple reproduction repo here; [https://github.com/iJigg/bun-preinstall-repro](https://github.com/iJigg/bun-preinstall-repro)

The interesting part is that it's working just fine in github CI with but fails on my private gitlab runner;

It's running 075050162388.dkr.ecr.eu-central-1.amazonaws.com/platform/docker-base-images/node-16-node:latest

Here's the output from the failing CI
```
$ uname -mprs
Linux 5.10.198 x86_64 unknown
$ curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
Added "~/.bun/bin" to $PATH in "~/.bashrc" 
To get started, run: 
  source /root/.bashrc 
  bun --help 
$ export PATH="~/.bun/bin/:$PATH"
$ bun --revision
1.0.18+36c[31]
$ bun install
bun install v1.0.18 (36c316a2)
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'project-root/preinstall.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:9[33](project-root/jobs/5752175795#L33):15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error: preinstall script from "dependency" exited with code 1 (SIGHUP)
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1

```

From what i can see, the nested preinstall path is neglected: 
**project/node_modules/dependency/package.json**: "preinstall": node scripts/preinstall.js
**Path to preinstall scripts**: project/node_modules/dependency/scripts/preinstall.js 
**When installing**, Error: Cannot find module 'project-root/preinstall.js' 

Seems like path to the dependency **/node_modules/dependency/** is not taken into consideration when executing the pre/post install scripts

Or are Are pre/post install scripts supposed to be hoisted from node_modules into project root for execution?

**Comment by ftzi** [comment]
@Jarred-Sumner issues persist with `deasync` with bun@1.0.18: https://github.com/oven-sh/bun/issues/7627.

By doing `npm ls deasync` to know which package is requiring it, it shows:

parcel-bundler@1.12.5
  └── deasync@0.1.15

**Comment by iJigg** [comment]
> @Jarred-Sumner issues persist with `deasync` with bun@1.0.18: #7627.
> 
> By doing `npm ls deasync` to know which package is requiring it, it shows:
> 
> parcel-bundler@1.12.5 └── deasync@0.1.15

Seems the common thing is that the dependencies have a node command for hooks 

`"preinstall/install/postinstall": "node someScript.js"`

**Comment by iJigg** [comment]
Closing this as this issue has been resolved, thank you!
