### ISSUE TITLE
Error installing Bun on Mac M1

### ISSUE THREAD

**Issue by fdaciuk** [oven-sh/bun#7634]
### What version of Bun is running?

n/a

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Run `curl -fsSL https://bun.sh/install | bash`

### What is the expected behavior?

Install Bun

### What do you see instead?

mkdir: /home/fernando: Operation not supported
error: Failed to create install directory "/home/fernando/.bun/bin"

### Additional information

The script should try to install in `/Users/daciuk` instead of `/home/fernando`

**Comment by Jarred-Sumner** [comment]
Do you have `$BUN_INSTALL` set in your environment variable list? That would cause this

**Comment by fdaciuk** [comment]
I had 😅 
I've deleted the reference from this env var and the installation works! Thanks :D

**Comment by AstralBaby** [comment]
> I had 😅 I've deleted the reference from this env var and the installation works! Thanks :D

How did you fix that?

**Comment by fdaciuk** [comment]
@AstralBaby I was sharing the same dotfiles between mac and linux. Because of that, I had `$BUN_INSTALL` env var in my `~/.zshrc`.

So I just deleted the env var and ran the install command again =)
