### ISSUE TITLE
Eval Can't find variable: exports

### ISSUE THREAD

**Issue by Kleywalker** [oven-sh/bun#7635]
### What version of Bun is running?

1.0.17+5e60861c3

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

Clone [https://github.com/Kleywalker/bun-eval](https://github.com/Kleywalker/bun-eval)

`bun install`

`bun run doesnotwork`

### What is the expected behavior?

console output "test-content"

### What do you see instead?

```sh
$ bun index.ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const case_1 = require("case");
const result = (0, case_1.kebab)('Test Content');
exports.default = result;

import {kebab} from "case";
const result = kebab("Test Content");
export default result;

19 | });
20 | const bunTranspiled = bunTranspiler.transformSync(content);
21 | console.log(bunTranspiled);
22 | 
23 | try {
24 |   const tscResult = eval(tscTranspiled);
                           ^
ReferenceError: Can't find variable: exports
      at /Users/code/github/bun-eval/index.ts:24:9

26 | } catch (error) {
27 |   console.log(error);
28 | }
29 | 
30 | try {
31 |   const bunResult = eval(bunTranspiled);
             ^
SyntaxError: Unexpected token '{'. import call expects one or two arguments.
      at /Users/code/github/bun-eval/index.ts:31:9
```

### Additional information

To see a working example node need to be installed.

Then run `bun run works`

**Comment by Kleywalker** [comment]
Related to [7636](https://github.com/oven-sh/bun/issues/7636)

**Comment by paperclover** [comment]
`index.ts` is an ES module, and `exports` is not a variable defined. 

eval doesnt inherit scope either, duplicate of #2875
