### ISSUE TITLE
Bun.Transpiler does not generate evaluable code

### ISSUE THREAD

**Issue by Kleywalker** [oven-sh/bun#7636]
### What version of Bun is running?

1.0.17+5e60861c3

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

Clone repository [https://github.com/Kleywalker/bun-eval](https://github.com/Kleywalker/bun-eval)

`bun install`

`bun run doesnotwork`

### What is the expected behavior?

console output "test-content"

### What do you see instead?

```sh
26 | } catch (error) {
27 |   console.log(error);
28 | }
29 | 
30 | try {
31 |   const bunResult = eval(bunTranspiled);
             ^
SyntaxError: Unexpected token '{'. import call expects one or two arguments.
      at /Users/stefan/code/github/bun-eval/index.ts:31:9
```

### Additional information

To see a working example node need to be installed.

Then run `bun run works`

**Comment by Kleywalker** [comment]
Related to [7635](https://github.com/oven-sh/bun/issues/7635)

**Comment by paperclover** [comment]
IMO this is not a bug but rather the fact that `--target=node` doesnt create a CommonJS module. `eval` does not support ES module syntax.

**Comment by Kleywalker** [comment]
This should work work to be able to use [this](https://github.com/oven-sh/bun/issues/5105) workaround.

**Comment by Kleywalker** [comment]
Hey @paperdave ! I tried your fix in revision 1.0.19+906f86d6f.
Unfortunately I still get the same error message. 😔 What do I have to change?
All the best.

**Comment by paperclover** [comment]
it is intentional for this to not work.

<img width="676" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/4e878b0f-49df-45dc-a2c1-714916a9874d">

however the error message can still be improved as node/v8 is much more clear on this.

**Comment by Kleywalker** [comment]
Ok @paperdave . Please help me out here. 😊 
If I use `tsc` like this:
```ts
import * as tsc from "typescript";
const content = `export default 42;`;
const tscTranspiled = tsc.transpile(content);
console.log(tscTranspiled);
```
I get:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = 42;
```
So, if I use this String in `node` like this:
```js
const content = `"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = 42;`;
const result = eval(content);
console.log(result);
```
I get the output
```sh
42
```
But I don't want to use tsc. So if I use `Bun.Transpile` I only get 
```js
export default 42;
```
Which does not work with eval.
How can I get the same code result like from `tsc` that evals to 42?

Thanks and all the best! 😊
