### ISSUE TITLE
URL 'protocol' is always 'http:', even with WebSocket connection

### ISSUE THREAD

**Issue by Starstalker-awe** [oven-sh/bun#7637]
### What version of Bun is running?

1.0.17+5e60861c3

### What platform is your computer?

Linux 6.2.0-37-generic x86_64 x86_64

### What steps can reproduce the bug?

![image](https://github.com/oven-sh/bun/assets/56582130/b6642d7b-18ea-4686-9307-2c05e0ac2e6f)

### What is the expected behavior?

`protocal` should be `ws:` when using a WebSocket connection

### What do you see instead?

No matter the connection protocol, `http:` is returned in `URL.protocol`

**Comment by scdailey** [comment]
Do you have SSL configured locally? Most of the time http is sufficient and default for running locally. https is more common on deployments with domains that need certified

**Comment by Starstalker-awe** [comment]
My issue is not related to SSL, it is with the protocol not
differentiating between http and websocket connections.

**Comment by Starstalker-awe** [comment]
Small update. After further testing, I've realized that this is an issue with `Request.url` in Bun. When directly logging `req.url` I get `http://127.0.0.1:4321/`, while ***expected*** is `ws://127...`

**Comment by Electroid** [comment]
This is actually the expected behaviour. The HTTP request is the handshake, it's not an active WebSocket connection until it's upgraded. This would also likely break many packages.

You can access the websocket url using `ws.url`, once upgraded.
