### ISSUE TITLE
bun re-adds itself to .zshrc every update

### ISSUE THREAD

**Issue by mrdomino** [oven-sh/bun#7641]
### What version of Bun is running?

1.0.16+800fb1290

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

`bun --upgrade`, then `cat ~/.zshrc`.

### What is the expected behavior?

My config should be unchanged. bun should've modified it when it was first installed, and now that it's upgrading, it should assume that I have preserved it.

If it wants to be sure that I have not made a mistake, it can gate its modifications behind `[[ -n "$BUN_INSTALL" ]]` and `[[ -x $(which bun) ]]`.

### What do you see instead?

My config is edited unconditionally.

**Comment by mrdomino** [comment]
I would suggest a fix that doesn't depend on that literal string, so that people can configure their environment however they please.

If it wouldn't be too much trouble, you could fork a zsh that runs the checks mentioned in the issue and gate the command on that exiting 0.

**Comment by Jarred-Sumner** [comment]
@mrdomino if you add the string to your .zshrc, it should insert it into your zshrc on upgrade:

```zsh
# bun completetions
```

The change was to allow either the comment or the file

**Comment by mrdomino** [comment]
Yes, but that means I need to put `$'#bun completions\n'` in my `.zshrc` somewhere. If you did `zsh -ic 'whence _bun >/dev/null'`, you would get an exit code of 0 if the completions were there, 1 if they were not there.

With the comment approach, it would be nice to not require the trailing `\n`, so I could write e.g `# bun completions are in $fpath`.
