### ISSUE TITLE
Support for self-referencing imports

### ISSUE THREAD

**Issue by fabiospampinato** [oven-sh/bun#7644]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Simple steps (thanks @paperdave):

```
// index.js 
console.log(require("self/package.json"));

// package.json
{
  "name": "self",
  "exports": {
    "./package.json": "./package.json"
  }
}
```

Convoluted steps:

```
git clone https://github.com/prettier/prettier-cli.git
cd prettier-cli
bun i
bun run compile
bun ./dist/bin.js --version
```

### What is the expected behavior?

Basically a package should be able to import one of its own exports, even if the package is not listed as a dependency to itself.

**Comment by Moosems** [comment]
Is that not a circular import due to it imported the compiled code and not the raw code?

**Comment by panukettu** [comment]
bumped into this limitation

`compilerOptions.resolvePackageJsonExports` does not help, hoped `package.json.imports` + `compilerOptions.paths` would emulate but nope

docs on tsconfig paths support being ironic (as node had this since v12.19.0):

> This is a major divergence from Node.js, which doesn't support any form of import path re-mapping.

**Comment by romulovalez** [comment]
+1,

Got into this issue, this is something that is well supported on Node: https://nodejs.org/api/packages.html#packages_self_referencing_a_package_using_its_name
