### ISSUE TITLE
 ConnectionRefused downloading package manifest

### ISSUE THREAD

**Issue by 4realpatrick** [oven-sh/bun#7647]
### What version of Bun is running?

1.0.17

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

delete node_modules, run `bun i --no-cache`, wait for a long long time, and console output fail message

### What is the expected behavior?

install modules successfully

### What do you see instead?

❯ time bun i --no-cache
[0.04ms] ".env"
bun install v1.0.17 (5e60861c)
  🔍 @headlessui/react [11/12] 
error: ConnectionRefused downloading package manifest @headlessui/react
  🔍 @headlessui/react [11/12] 
error: ConnectionRefused downloading package manifest react-select
error: @headlessui/react@^1.7.17 failed to resolve
error: react-select@^5.8.0 failed to resolve
bun i --no-cache  209.55s user 236.60s system 99% cpu 7:30.01 total

**Comment by Electroid** [comment]
Duplicate of #4988
