### ISSUE TITLE
Unexpected token after typescripts angle brackets as type parameter

### ISSUE THREAD

**Issue by bogeychan** [oven-sh/bun#765]
### Version

0.1.4

### Platform

WSL2 Ubuntu

### What steps will reproduce the bug?

Execute the following code snippet using `bun run index.ts`:

```ts
// index.ts
type Constructor = new (...args: any[]) => {};

const Mixin = <TMixin extends Constructor>(
  Base: TMixin,
  value: number = 42
) => {
  return class extends Base {
    foo() {
      return value;
    }
  };
};

class Sample<P> {
  boo(value: P) {
    return value;
  }
}

const SampleMixin = Mixin(Sample<'bun'>, 42);

console.log(new SampleMixin().boo("bun"));
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Console output:
```bash
bun
```

### What do you see instead?

Console output:
```bash
error: Unexpected ,

const SampleMixin = Mixin(Sample<'bun'>, 42);
```

### Additional information

Bun, unlike `tsc`, does not allow any characters after a closed angle bracket except a closed bracket or a semicolon:

This one works:
```ts
const SampleMixin = Mixin(Sample<'bun'>);
console.log(new SampleMixin().boo("bun"));
```
```bash
bun
```
This only works if a semicolon is present:
```ts
const SampleMixin = Sample<'bun'>
const instance = new SampleMixin();
console.log(instance.boo('bun'));
```
```bash
error: Unexpected const

const instance = new SampleMixin();
```

**With `tsc` from typescript this is no problem as this test shows:**
1. Install `typescript` using `bun add typescript -d`
2. Transpile typescript to javascript with `bun run tsc index.ts --target esnext --moduleResolution node`
3. Run it `bun run index.js`

```ts
// parameters after type assignment
const SampleMixinNumber = Mixin(Sample<'bun'>, 42);
console.log(new SampleMixinNumber().boo("bun"));

// no semicolon
const SampleMixin = Sample<'bun'>
const instance = new SampleMixin();
console.log(instance.boo('bun'));
```
```bash
bun
bun
```

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/2593
