### ISSUE TITLE
Module mocking not working as expected

### ISSUE THREAD

**Issue by jacobarvidsson** [oven-sh/bun#7677]
### What version of Bun is running?

1.18.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

When using mock.module, I expect the function to be mocked, however nothing seems to happen.

**The function:**
```tsx
import { v4 } from "uuid";

export const getRandomNumber = () => {
  return v4();
};
```

**The test:**
```tsx
import { describe, expect, mock, test } from "bun:test";
import { getRandomNumber } from "./getRandomNumber";

describe("Given the getRandomFunction is called", () => {
  test("Then the length of the number should match 36", () => {
    const value = getRandomNumber();
    expect(value).toHaveLength(36);
  });

  test("Then the value should equal the mocked value", () => {
    mock.module("uuid", () => ({ v4: "mocked-uuid" }));
    const value = getRandomNumber();
    expect(value).toEqual("mocked-uuid");
  });
});
```

**Reproducible repo:**
https://github.com/jacobarvidsson/bun-mocking

### What is the expected behavior?

The test should pass.

### What do you see instead?

The module is never mocked and generates a new uuid every test run.

### Additional information
<img width="694" alt="Screenshot 2023-12-15 at 10 21 45" src="https://github.com/oven-sh/bun/assets/3352203/b50e703a-433e-4c4a-941e-c95d93108c51">

**Comment by Jarred-Sumner** [comment]
This is fixed by #7673

for now, wrap specifiers to mock.module with require.resolve so it’s the absolute path
