### ISSUE TITLE
Support nodejs `global` variable

### ISSUE THREAD

**Issue by yossizahn** [oven-sh/bun#768]
### What is the problem this feature will solve?

Some node modules rely on the nodejs `global` variable referring to the global object ([doc](https://nodejs.org/api/globals.html#global))

### What is the feature you are proposing to solve the problem?

Simply alias `globalThis` as `global`

### What alternatives have you considered?

We could force all user's of such modules to add this line to their code:
```
globalThis.global = globalThis
```

**Comment by Jarred-Sumner** [comment]
Yeah definitely

Same for `self`

**Comment by ken0x0a** [comment]
```sh
bun test
```

gave me

```
ReferenceError: Can't find variable: DEBUG
```

for the following code.

```ts
global.DEBUG = true
import "./path_to_file_using_DEBUG.ts";

// ...
```

**Comment by ken0x0a** [comment]
Write ./setup.ts as follows
```ts
global.DEBUG = true
```

and 

```sh
bun test --preload ./setup.ts
```

works.
