### ISSUE TITLE
I am being able to access private properties outside the class

### ISSUE THREAD

**Issue by pjlunardelli** [oven-sh/bun#7687]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. Create a private property
2. Access it outside the class

Example
async prepare() {
    this.fileSystemHandler = new FileSystemHandler(this.finalDir);
    console.log(
      "file: classifier.ts:29 || this.fileSystemHandler.handler:",
      this.fileSystemHandler.handler.data
    );
    this.fileSystemHandler.handler = {};
    console.log(
      "file: classifier.ts:31 || this.fileSystemHandler:",
      this.fileSystemHandler.handler
    );
  }
  
  Log:
  file: classifier.ts:29 || this.fileSystemHandler.handler: null
file: classifier.ts:31 || this.fileSystemHandler: {}

### What is the expected behavior?

Don't run

### What do you see instead?

Code running and showing information it shouldn't

### Additional information

I was able to get a private property to work via "#property"

**Comment by Didas-git** [comment]
I dont see any private properties in the example.
As for testing, i dont see any issues and bun seems to be working as intended
![image](https://github.com/oven-sh/bun/assets/80978939/e6074bbd-6965-4e82-8fff-77ae129f335d)

**Comment by pjlunardelli** [comment]
The image haven't been uploaded, my mistake. 

Is does work with "#", but it doesn't with private

  private handler: StringHandler | BufferHandler;
  private helpers: Helpers = { directory: new Directory(this) };

  constructor(
    path?: string,
    mode: Mode = "Buffer",
    acceptDir: boolean = false
  ) {
    super(path);
    this.mode = mode;
    this.handler = new handler[mode](this.path);
    if (acceptDir !== undefined) this.acceptDir = acceptDir;
  }

**Comment by Didas-git** [comment]
`private` is not a javascript thing.
its a typescript keyword and only works on the type level, it has no effect at runtime

**Comment by Jarred-Sumner** [comment]
TypeScript’s private doesn’t use the JavaScript feature for private fields and we cannot change this without breaking lots of code.

**Comment by pjlunardelli** [comment]
You are both correct, thanks for the information.
https://github.com/microsoft/TypeScript/issues/31670
https://stackoverflow.com/questions/75480223/compiling-private-to-property
