### ISSUE TITLE
Cannot find variable ptr

### ISSUE THREAD

**Issue by theoparis** [oven-sh/bun#769]
### Version

0.1.4

### Platform

Linux xps 5.18.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

```js
const path = new TextEncoder().encode("/dev/dri/card0");

// card constructor calls an ffi function with the path
const card = new Card(path);
```

### What is the expected behavior?

The encoded string should be passed directly to ffi and auto-converted (see https://github.com/oven-sh/bun#passing-a-pointer)

### What do you see instead?

 6 |     return 0;
 7 |   }
 8 |
 9 |   if (ArrayBuffer.isView(val) || val instanceof ArrayBuffer) {
10 |
11 |     return ptr(val);
              ^
 ReferenceError: Can't find variable: ptr

**Comment by sno2** [comment]
The reproduction needs to include the FFI code.  We can't really tell anything from the higher-level API that does not use any of Bun.  Although, from the error, it seems you forgot to import `ptr` from `bun:ffi`.

**Comment by borkdude** [comment]
Repro in #801
