### ISSUE TITLE
DOMJIT side effects bug in bun:sqlite Statement.prototype.get()

### ISSUE THREAD

**Issue by billywhizz** [oven-sh/bun#7694]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64 (Ubuntu 22.04)

### What steps can reproduce the bug?

run this script with and without the commented line commented. when you have the line commented out the performance goes through the roof but in a very strange way. my only guess is JSC is optimizing the call away because the result is never used, but that sounds dangerous if that call into SQLite were to have side effects?

I have verified this against a C implementation that there is no possible way in the "fast" case here that bun could be actually making those calls through the SQLite api, but maybe i am wrong.

```JavaScript
import { Database } from 'bun:sqlite'

const db = Database.open(':memory:')
db.exec('create table if not exists foo (num int)')
db.exec('insert into foo (num) values (1)')
const stmt = db.prepare('select num from foo limit 1')
if(stmt.get().num !== 1) throw new Error('Unexpected Result')

let last = 0

while (1) {
  const start = performance.now()
  for ( let i = 0; i < 5000000; i++) {
    const x = stmt.get()
//    if (x.num !== 1) throw new Error('Bad Value')
  }
  const elapsed = performance.now() - start
  console.log(elapsed)
  if (last > 0 && elapsed < (last / 10)) break
  last = elapsed
}

stmt.finalize()
db.close()
```

results with commented line uncommented

```shell
1994.904638
1944.289669
2116.445355
1930.737728
1950.9066799999991
```

results with the commented line commented out

```shell
178.502223
336.518683
16.724518999999987
```

i see same results on ```ubuntu 22.04 x64_64``` and ```Darwin 22.6.0 arm64```

:thinking:

**Comment by Jarred-Sumner** [comment]
It’s never supposed to optimize away the function call.  Thank you reporting this. Looks like a bug with how we specified side effects in our use of DOMJIT in the .get() function. We fixed an issue like this some time ago, but the number of iterations was smaller.
