### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _ucal_getTimeZoneOffsetFromLocal

### ISSUE THREAD

**Issue by liyofx** [oven-sh/bun#7696]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 20.6.0 x86_64 i386

### What steps can reproduce the bug?

<img width="500" alt="截屏2023-12-16 下午4 20 51" src="https://github.com/oven-sh/bun/assets/6176478/adb7fc6e-2159-4af7-b741-a7992d4828cc">
<img width="500" alt="截屏2023-12-16 下午4 21 16" src="https://github.com/oven-sh/bun/assets/6176478/d1715bbd-4440-4367-b6f4-0220bc02b540">

<img width="500" alt="截屏2023-12-16 下午5 02 16" src="https://github.com/oven-sh/bun/assets/6176478/70693dc9-4b02-4eda-bcb1-dae9bd3b4470">

dyld: lazy symbol binding failed: Symbol not found: _ucal_getTimeZoneOffsetFromLocal
  Referenced from: /Users/z/.bun/bin/bun
  Expected in: /usr/lib/libicucore.A.dylib

dyld: Symbol not found: _ucal_getTimeZoneOffsetFromLocal
  Referenced from: /Users/z/.bun/bin/bun
  Expected in: /usr/lib/libicucore.A.dylib

[1]    13084 killed     bun run index.ts

**Comment by paperclover** [comment]
current builds of bun require MacOS 12 due to the system `icucore`

I think it is possible to make this work but for now you need to upgrade MacOS.

**Comment by liyofx** [comment]
I tried switching to 1.0.2 and it worked normally.
