### ISSUE TITLE
Express throws body in used.

### ISSUE THREAD

**Issue by aquapi** [oven-sh/bun#7699]
### What version of Bun is running?

1.0.18

### What platform is your computer?

Linux 6.5.0-14-generic x86_64

### What steps can reproduce the bug?

Write a simple Express server that yield back the JSON body
```ts
express()
  .get('/', (_, res) => res.send('Hi'))
  .get('/id/:id', (req, res) => res.send(req.params.id + ' ' + req.query.name))
  .post('/json', (req, res) => res.json(req.body))
  .listen(3000)
```

### What is the expected behavior?

Send a POST request to `/json` and it yields the JSON body sent.

### What do you see instead?

Error: Body in used

**Comment by sirenkovladd** [comment]
try
```js
express()
  .use(express.json()) // [!IMPORTANT]
  .get('/', (_, res) => res.send('Hi'))
  .get('/id/:id', (req, res) => res.send(req.params.id + ' ' + req.query.name))
  .post('/json', (req, res) => res.json(req.body))
  .listen(3000)
```

https://expressjs.com/en/resources/middleware/body-parser.html#express-route-specific

**Comment by Electroid** [comment]
Following @sirenkovladd's suggestion, this doesn't appear to be a bug. Tested both snippets on Bun and node, and the behavior matches for both on macOS arm64.

**Comment by aquapi** [comment]
> try
> 
> ```js
> express()
>   .use(express.json()) // [!IMPORTANT]
>   .get('/', (_, res) => res.send('Hi'))
>   .get('/id/:id', (req, res) => res.send(req.params.id + ' ' + req.query.name))
>   .post('/json', (req, res) => res.json(req.body))
>   .listen(3000)
> ```
> 
> https://expressjs.com/en/resources/middleware/body-parser.html#express-route-specific

This is the same but slower.
Anyways I should test an older express version.
