### ISSUE TITLE
Linux local development

### ISSUE THREAD

**Issue by levkk** [oven-sh/bun#77]
Hi there!

I'm creating this issue to track Linux local development issues. I've ran into a few, hoping to document them here with possible solutions.

#### `require` Makefile target checks for Mac OS specific paths

```Makefile
@stat $(LIBICONV_PATH) >/dev/null 2>&1 || (echo -e "ERROR: libiconv is required. Please run:\n\n    brew install libiconv"; exit 1)
@stat $(LIBCRYPTO_STATIC_LIB) >/dev/null 2>&1 || (echo -e "ERROR: OpenSSL 1.1 is required. Please run:\n\n    brew install openssl@1.1"; exit 1)
```

Both of these are Mac OS specific. A fix could be to:

1. Check for libc6 which includes libiconv.
2. Check for `libssl-dev` which would install OpenSSL dev headers and library

#### `s2n` Makefile target doesn't exist

When running `make vendor dev`, it breaks because this target does not exist but is required by `vendor-without-check`. I think here `s2n` was meant to be a distribution-specific target, e.g. Ubuntu or generic Linux. A possible workaround could be documenting required libraries in the README and not include this one (it's almost guaranteed to break over time and with different distributions).

#### `docker container ls` doesn't find the container
But `docker container create bun-webkit` does output the container identifier, so that can be used directly, e.g

```bash
DOCKER_CONTAINER_ID_YOU_JUST_FOUND=$(docker container create bun-webkit)
```

#### build.zig does not compile

Last, but not least, I couldn't compile `bun` with zig because of this:

```
/home/lev/bin/zig/zig build obj
/home/lev/Projects/bun/build.zig:4:11: error: unused local constant
    const picohttp = step.addPackage(.{
          ^
/home/lev/Projects/bun/build.zig:123:13: error: unused local variable
        var install = b.getInstallStep();
            ^
make: *** [Makefile:581: dev-obj] Error 1
```

My system:
- Ubuntu 21.10 64-bit
- Zig: `0.9.0-dev.1678+7747bf07c`

I'll keep poking around and debugging. Thank you for writing this tool, I think this will be a game changer in the community!

**Comment by Jarred-Sumner** [comment]
Thank you for this.

> Check for libc6 which includes libiconv.

Oh, I didn't realize libiconv is included in libc6. I believe Bun is currently statically linking that. I guess can just not do that.


> s2n Makefile target doesn't exist

S2N will be going away shortly (a week?). In the [`jarred/npm-install`](https://github.com/Jarred-Sumner/bun/tree/jarred/npm-install) branch, I've migrated the TLS library to BoringSSL and BoringSSL will be another submodule to compile & statically link.

> Check for libssl-dev which would install OpenSSL dev headers and library

The `libssl-dev` dependency will go away due to the BoringSSL change.

> Last, but not least, I couldn't compile bun with zig because of this:

Currently, you'll have to use the special custom build of Zig. This is mentioned here: https://github.com/jarred-sumner/bun#linux. This is not great and will be fixed eventually.

**Comment by levkk** [comment]
>  Currently, you'll have to use the special custom build of Zig.

Edit: Spoke too soon. I got to compile the custom zig version without the bootstrapping thing. I'll document the steps soon.

That one is tough to bootstrap. It's targeting a specific version of LLVM and even if you have clang-12 and llvm-12 and llvm-config-12 all setup, it still fails to link correctly at stage 0 I believe. I also tried https://github.com/ziglang/zig-bootstrap, which they seem to recommend as the most viable way to compile it from source, but sadly that repo only supports Zig's master branch - just substituting your version of Zig into the bootstrapping code doesn't work (LLVM conflicts again).

I'll keep poking, this is a fun problem for sure; takes me back to school, it's too bad I never took the compiler class :smile: .

**Comment by moderation** [comment]
I attempted to compile `bun` locally on my Xubuntu 21.10 with `zig` nightly and wasn't able to get it to work. I tried and bunch of different options using the `make` instructions from MacOS, `zig build` etc. but couldn't work it out. Once possible it would be great to add documentation to `README.md`

**Comment by Jarred-Sumner** [comment]
> I attempted to compile bun locally on my Xubuntu 21.10 with zig nightly and wasn't able to get it to work

Sorry about that

Could you be a little more specific with what went wrong? I recommend trying the following: 
```
make devcontainer dev
```

On subsequent changes
```
make dev
```

**Comment by FinnRG** [comment]
@levkk Do you want to close this issue? I believe it was created before the devcontainer existed, which makes local Linux development rather irrelevant.

**Comment by levkk** [comment]
Developing inside containers is not everyone's favorite way of working. That being said, we can reopen this if there is more interest in local development on Linux.
