### ISSUE TITLE
support hashbang comment at start of script file

### ISSUE THREAD

**Issue by GabrielBoehme13** [oven-sh/bun#770]
### Version

0.1.4

### Platform

Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

Create the following `hello-world.js` file…

```Javascript
#!/usr/bin/env bun run
void console.log( 'Hello, world!' )
```

…then run it via `bun run hello-world.js`.

### How often does it reproduce? Is there a required condition?

If I comment out the hashbang line like so…

```Javascript
// #!/usr/bin/env bun run
void console.log( 'Hello, world!' )
```

…then I get the expected output.

### What is the expected behavior?

`Hello, world!`

### What do you see instead?

`error: Missing script "/<path-to-script>/hello-world.js"`

### Additional information

[Hashbang Grammar proposal (currently Stage 3, implemented in Node and Deno)](https://github.com/tc39/proposal-hashbang)

**Comment by greatbody** [comment]
I think you may be using it the wrong way, try this
```
#!/usr/bin/env bun

class Most {
    static readMe() {
        console.log('Hello World');
    }
}

Most.readMe();
```

**Comment by GabrielBoehme13** [comment]
Thanks for pointing me in the right direction! Making this change worked:

```Javascript
#!/usr/bin/env bun
void console.log( 'Hello, world!' )
```

…specifying `#!/usr/bin/env bun`, instead of `#!/usr/bin/env bun run` as I expected from my experience with Deno.

For others who might make the same mistake I did, can the current "Missing script" error message be revised to provide more helpful feedback?

**Comment by greatbody** [comment]
> Thanks for pointing me in the right direction! Making this change worked:
> 
> ```js
> #!/usr/bin/env bun
> void console.log( 'Hello, world!' )
> ```
> 
> …specifying `#!/usr/bin/env bun`, instead of `#!/usr/bin/env bun run` as I expected from my experience with Deno.
> 
> For others who might make the same mistake I did, can the current "Missing script" error message be revised to provide more helpful feedback?

So we can close this issue?

**Comment by greatbody** [comment]
@GabrielBoehme13 So, can we close this issue?
