### ISSUE TITLE
`.only` tests unexpected behavior when running `bun test` without -only flag

### ISSUE THREAD

**Issue by bhflm** [oven-sh/bun#7701]
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 22.5.0 x86_64 i386

### What steps can reproduce the bug?

Within a file that has more than 3 tests :

- Place the .only on the 2nd or 3rd test
- Run `bun test`
- Watch tests above the .only get executed, until it reaches the `.only` set one. 

![testbun](https://github.com/oven-sh/bun/assets/23338712/49b702a0-df03-4a00-9253-e0b251a59c8f)

### What is the expected behavior?

It should run all of the tests if no flag `-only` is explicitly set. 

### What do you see instead?

Tests being run sequentially from top to bottom until it reaches one test set as `.only`.

### Additional information

I've reproduced the issue on [this repository](https://github.com/bhflm/bun-bug-test-only/tree/master)

**Comment by mangs** [comment]
Thank you for filing this. I've noticed this too. Tests from different files execute as well.

**Comment by EvHaus** [comment]
Some subjective feedback. I find Bun's behavior here very frustrating to use. The main benefit of using `.only()` for me is to quickly isolate tests while in watch mode. There are currently two ways of running tests in Bun, and both are painful to use. You can:

1. Run `bun test --watch`. But when you focus a test with `.only()` it runs all tests above it too (like this bug describes), or you can
2. Run `bun test --only --watch`, which fixes the issue above but now when you remove all `.only()` tests, Bun won't run anything at all.

I would prefer Bun copied the behavior that Jest and Vitest follow, which is:

- No need for an extra CLI `--only` option. Remove it.
- When running `bun test`, if any `.only()` tests are detected, only run those. If none are detected, run everything
