### ISSUE TITLE
`bun add` hangs when trying to add `tree-sitter-php`

### ISSUE THREAD

**Issue by raulchedrese** [oven-sh/bun#7704]
### What version of Bun is running?

1.0.18

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

`bun add tree-sitter-php`

### What is the expected behavior?

I would expect the package to be installed successfully or an error to be shown if it can't be installed.

### What do you see instead?

The command hangs indefinitely with no output.
```
√ ~/projects/bun_test $ bun add tree-sitter-php
bun add v1.0.18 (36c316a2)

```

### Additional information

UPDATE: It looks like it does eventually exit with this error:
```
error: Failed to run "node-gyp" due to error SystemResources

error: install script from "tree-sitter-php" exited with code 1 (SIGHUP)
```

_No response_

**Comment by Jarred-Sumner** [comment]
@dylan-conway I wonder if `bunx node-gyp` is infinite looping

@raulchedrese can you try running `bun add -g node-gyp` and see if it works after that?

**Comment by raulchedrese** [comment]
I'm seeing the same behaviour after `bun add -g node-gyp`. It still hangs and eventually exits with the same error.

**Comment by raulchedrese** [comment]
This looks to be resolved in the latest version. `tree-sitter-php` installs without issue. The library still doesn't work with Bun but that looks to be due to a different issue that was reported in #6311
