### ISSUE TITLE
Tauri process immediate exit

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#7731]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

- `bun --bun x create-tauri-app@latest` (selected i.e. typescript / solidjs)
- `cd tauri-app`
- `bun --bun run tauri dev`

### What is the expected behavior?

the expected result can be seen by running `bun run tauri dev` (without the --bun flag)

```zig
➜ bun run tauri dev      
$ tauri dev
     Running BeforeDevCommand (`bun run dev`)
$ vite

  VITE v4.5.1  ready in 212 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /Users/admin/repos/bun-kitchensink/tauri-app/src-tauri for changes...
   Compiling tauri-app v0.0.0 (/Users/admin/repos/bun-kitchensink/tauri-app/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 1.00s
```

<img width="453" alt="Screenshot 2023-12-19 at 12 14 30" src="https://github.com/oven-sh/bun/assets/74932975/ac710971-dc1b-4f09-a331-0aa3f7aaacb9">

### What do you see instead?

```zig
➜ bun --bun run tauri dev
$ tauri dev
```

immediate exit, same for `tauri build`

**Comment by 9Morello** [comment]
Reproducible on Ubuntu 22.04 x86-64. The selected JS frameworks don't change the output, as expected.

**Comment by 9Morello** [comment]
Okay, so I managed to create a minimal script to reproduce this issue:

```js
// Run this script in a fresh Tauri app folder on a GNU system, created with `bun --bun x create-tauri-app@latest`
// if you're on OSX, replace the nativeBiding with the darwin one from the @tauri-apps folder
let nativeBinding;
try {
  nativeBinding = require("./node_modules/@tauri-apps/cli-linux-x64-gnu/cli.linux-x64-gnu.node");
} catch (e) {
  console.log(e);
}
if (!nativeBinding) {
  throw new Error(`Failed to load native binding`);
}
const { run, logError } = nativeBinding;

const runPromise = async (args, binName) => {
  return new Promise((resolve, reject) => {
    run(args, binName, (res) => {
      if (res instanceof Error) {
        reject(res);
      } else {
        resolve(res);
      }
    });
  });
};

runPromise(["dev"], "bun").catch((err) => {
  logError(err.message);
  console.log(JSON.stringify(err, null, 2));
  process.exit(1);
});
```
The script above runs as expected using Node 20.5.1, but fails with Bun 1.0.18. **Adding a `await` before the `runPromise`** function makes it work correctly in Bun, and the Tauri window shows up as expected.

I believe the `run` function is being treated as synchronous when imported by Node.js, but as asynchronous when imported by Bun, thus causing the application to close immediately.

If anyone wants to use Tauri with Bun before this gets fixed, change line 54 of `node_modules/@tauri-apps/cli/tauri.js` to include an `await` in the beginning of the line.

**Edit:** still happening with Bun 1.0.30.

**Comment by birkskyum** [comment]
I see the same thing on macos. Adding the await will fix bun, but break node with:

```sh
➜ npm run tauri dev      

> tauri-node@0.0.0 tauri
> tauri dev

/Users/admin/repos/bun-kitchensink/tauri-app/node_modules/@tauri-apps/cli/tauri.js:54
await cli.run(args, binName).catch((err) => {
^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.13.0
```

**Comment by birkskyum** [comment]
@9Morello , does it work for you now? I think my issues might be resolved.

**Comment by birkskyum** [comment]
Running the app in the browser yields an error:

```sh
@tauri-apps_api_tauri.js?v=2580b4ea:30 Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at @tauri-apps_api_taur…js?v=2580b4ea:30:12
    at new Promise (<anonymous>)
    at invoke (@tauri-apps_api_taur…js?v=2580b4ea:21:10)
    at greet (main.ts:9:36)
    at HTMLFormElement.<anonymous> (main.ts:20:5)
```

But when it opens in it's own window, it'll work as expected
