### ISSUE TITLE
Take some rest, don't work too hard

### ISSUE THREAD

**Issue by greatbody** [oven-sh/bun#774]
### Platform

body

### What steps will reproduce the bug?

Every one we refresh the commit history, we see your commit.

### How often does it reproduce? Is there a required condition?

Every hours.

### What is the expected behavior?

It's exciting to see the project evolving, but your health does matter to all of us in the community of bun.

### What do you see instead?

Every one we refresh the commit history, we see your commit.

**Comment by wenq1** [comment]
It is hard to define "health" and "rest". Seeing commits doesn't mean "unhealthy" nor "taking no rests". Difficult to reproduce. Maybe won't fix.

**Comment by jyling** [comment]
Seems to be a duplicate of https://github.com/oven-sh/bun/issues/774

**Comment by greatbody** [comment]
> Seems to be a duplicate of #774

Make sense

**Comment by Electroid** [comment]
We're growing the team so he can get more rest! (psst... jobs@oven.sh)
