### ISSUE TITLE
Change "Duplicate dependency" to be a warning instead of error

### ISSUE THREAD

**Issue by shyim** [oven-sh/bun#7740]
### What version of Bun is running?

1.0.18

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

I am trying to replace all `npm install --no-save` calls with `bun install --no-save` and it fails for a project because the dev declared it in `dependencies` and `devDependencies`

```
{
    "devDependencies": {
        "vuex": "3.6.2"
    },
    "dependencies": {
        "vuex": "3.6.2"
    }
}
```

With `npm` it runs. I know the dev made a mistake here. But maybe this should be a warning. I have to annoy the team and wait for a release. I think making it to a warning could save people time. 

### What is the expected behavior?

Runs like `npm` but shows a warning that the package is defined in both.

### What do you see instead?

```
❯ bun i
bun install v1.0.18 (36c316a2)
3 |         "vuex": "3.6.2"
            ^
error: Duplicate dependency: "vuex" specified in package.json
    at /Users/shyim/Downloads/foo/package.json:3:9

6 |         "vuex": "3.6.2"
                    ^
note: "vuex" originally specified here
   at /Users/shyim/Downloads/foo/package.json:6:17
```

**Comment by Electroid** [comment]
It seems conceivable that we should make this a warning, instead of a hard error.
