### ISSUE TITLE
EMFILE: Too many open files

### ISSUE THREAD

**Issue by zaida04** [oven-sh/bun#7741]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Linux 5.4.72-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. bunx create-expo-app -t expo-template-blank-typescript
2. cd my-app
3. bun run ios
4. observe various `EMFILE: Too many open files` errors

### What is the expected behavior?

Expo server prints a success message and connection information.

### What do you see instead?

Various `EMFILE: Too many open files` errors. There are many of these, and I was only able to capture the most recent lines since my terminal has a max line limit.

[output.txt](https://github.com/oven-sh/bun/files/13718638/output.txt)

**Comment by gvilums** [comment]
Can't repro, feel free to reopen if it's still an issue

**Comment by vladfaust** [comment]
I think it's related to `bun link`. When I'm running a Vite dev server, be it with `bun run dev` or `npm run dev`, and there is a `bun link`ed package, the amount of open files (`watch -c "lsof -n | awk '{print \$1, \$2}' | uniq -c | sort -rn | head -n \$LINES "`) grows on every file save within the project. 

When the same package is not `bun link`ed, but instead installed from npm, the problem disappears.
