### ISSUE TITLE
Inconsistent script not found error message

### ISSUE THREAD

**Issue by Creative-Difficulty** [oven-sh/bun#7761]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.2.0 arm64 arm (M2 Pro)

### What steps can reproduce the bug?

n/a

### What is the expected behavior?

Consistent error messages

### What do you see instead?

Inconsistent error messages

### Additional information

<img width="466" alt="Bildschirmfoto 2023-12-21 um 08 28 58" src="https://github.com/oven-sh/bun/assets/80907917/ed11e59d-759e-4644-97d7-9626c0f2bdff">

**Comment by vitalspace** [comment]
this is fixed in https://github.com/oven-sh/bun/pull/7799

**Comment by Creative-Difficulty** [comment]
Thanks
