### ISSUE TITLE
Provide better DX when someone confuses `bun update` with `bun upgrade`

### ISSUE THREAD

**Issue by wojtekmaj** [oven-sh/bun#7767]
### What is the problem this feature would solve?

`bun update` and `bun upgrade` are often confused (and I'm a victim too: #6422). The fact the industry didn't decide which command does what doesn't help either. For example, `brew` uses `update` and `upgrade` exactly the opposite to how Bun uses it.

### What is the feature you are proposing to solve the problem?

There's one thing Brew does very well. When you confuse the commands, Brew is actually super helpful:

```
wmaj@MacBook-Air % brew update node
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade node` instead.
```

while Bun isn't:

```
wmaj@MacBook-Air % bun upgrade is-even
Congrats! You're already on the latest version of Bun (which is v1.0.18)
```

**Comment by Electroid** [comment]
Yea, it appears many people have run into this. If `bun upgrade` is run with positional arguments, we should give an error similar to what `brew` does.

**Comment by BrookJeynes** [comment]
Hey @Electroid, I'm happy to give this one a go if that's alright?
