### ISSUE TITLE
Wrong and different output result for node:path `relative` implementation first wrong second right

### ISSUE THREAD

**Issue by vedmalex** [oven-sh/bun#7768]
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

import { relative } from 'path';

console.log(relative('http://some/cool', 'http://some/cool/api/'))
console.log(relative('http://some/cool', 'http://some/cool/api/'))

### What is the expected behavior?

api
api

### What do you see instead?

api/
api

### Additional information

work as expected for any node version

**Comment by Hanaasagi** [comment]
I think this is related to https://github.com/oven-sh/bun/issues/5440, and has been fixed in 1.0.19 . Please upgrade, thanks.
