### ISSUE TITLE
--use <STR>Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by harshmangalam** [oven-sh/bun#777]
### Version

0.1.4(beta)

### Platform

Ubuntu-20.04  x86_64

### What steps will reproduce the bug?

curl https://bun.sh/install | bash
bun --help
![bun_err](https://user-images.githubusercontent.com/57381638/179500442-65a71c26-5283-446d-b858-a9084df36694.png)

### What do you see instead?

--use <STR>Illegal instruction (core dumped)

**Comment by xhyrom** [comment]
From [bun discord bot](https://github.com/xHyroM/bun-discord-bot):
---

**Illegal instruction - core dumped**

Bun currently only works on CPUs supporting the AVX2 instruction set.
There is nothing you can do about it at the moment, you can only wait.
However, there are plans to make a build that doesn't need AVX2 ([#67](<https://github.com/oven-sh/bun/issues/67>))

**NOT RECOMMENDED (VERY SLOW ALTERNATIVE)**:
To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support.
If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.

**1.** Install intel-sde:
   • Arch Linux: `yay -S intel-sde`
   • Other Distros:
```bash
wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
cd /tmp
tar -xf intel-sde.tar.xz
cd sde-external*
mkdir /usr/local/bin -p
cp sde64 /usr/local/bin/sde
cp -r intel64 /usr/local/bin/
cp -r misc /usr/local/bin/
```

**2.** Add alias to bashrc
   • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`

**Comment by harshmangalam** [comment]
Thanks got it @xHyroM
