### ISSUE TITLE
outdated React Template with bun create react

### ISSUE THREAD

**Issue by imsamimalik** [oven-sh/bun#778]
### Version

0.1.4

### Platform

Linux singularity 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

I created a react project using **bun create react .** 
It turns out the react version in the template that bun is using is still react 17

### How often does it reproduce? Is there a required condition?

everytime

### What is the expected behavior?

It should grab the latest react version

### What do you see instead?

in the package.json, it is still using  react 17

` "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "web-vitals": "^1.0.1"
  },`

**Comment by facelessdevhack** [comment]
This is already fixed and merged. @imsamimalik Please give it a try. #627

**Comment by imsamimalik** [comment]
Oh my bad. I think it's not been included in the release yet.
