### ISSUE TITLE
`setTimeout` causes 100% CPU usage

### ISSUE THREAD

**Issue by 0xroko** [oven-sh/bun#7790]
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Linux 6.6.5-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Run:
```
setTimeout(() => {
}, 200_000);
```

### What is the expected behavior?

Downgrading to version 1.0.18: 
![image](https://github.com/oven-sh/bun/assets/55251261/0c67c310-a390-4054-bb32-b4c289f72504)

### What do you see instead?

Latest:
![image](https://github.com/oven-sh/bun/assets/55251261/4c78d25d-6c49-4306-a341-1d28006becaf)

### Additional information

Isn't present on `1.0.18`, could be caused by #7715?

**Comment by Jarred-Sumner** [comment]
uh oh 

I guess bun v1.0.20 will ship tomorrow
