### ISSUE TITLE
import rxjs operator error

### ISSUE THREAD

**Issue by lei1996** [oven-sh/bun#780]
### Version

0.1.4

### Platform

21.5.0 Darwin Kernel Version 21.5.0

### What steps will reproduce the bug?

import { from, map } from "rxjs";

from([1, 2, 3])
  .pipe(map((x) => x * 2))
  .subscribe(console.log);

export default {
  port: 3000,
  fetch(request: Request) {
    return new Response("Hello World");
  },
};

---------------- Output ---------------------

bun ./index.ts
1 | 
2 | var { createErrorClass} = require($de83df7a);
   ^
 ReferenceError: Can't find variable: require

### What do you see instead?

<img width="552" alt="image" src="https://user-images.githubusercontent.com/19546371/179539721-da2f13c7-2504-4e6b-9ce0-20743db4e9eb.png">

**Comment by greatbody** [comment]
中国同学哈哈

**Comment by Jarred-Sumner** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/709451/180519714-9c9a10b4-2702-48c8-b953-a3580a9f8f82.png">
Fixed in Bun v0.1.5
