### ISSUE TITLE
bun init doesn't use `@types/bun`

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#7803]
### What version of Bun is running?

1.0.19+906f86d6f

### What steps can reproduce the bug?

`bun init`

### What is the expected behavior?

`@types/bun` in dev deps

### What do you see instead?

`bun-types` in dev deps

### Additional information

My expectation comes from: https://bun.sh/blog/bun-v1.0.19#:~:text=or%20you%20can%20ue%20bun%20init%3A

**Comment by Electroid** [comment]
Thanks we’ll update this

**Comment by thunfisch987** [comment]
is there also something going to change about the tsconfig.json?
currently it creates the same as before (with compilerOptions.types: "bun-types")
what is the intended behavior?

**Comment by fdaciuk** [comment]
> is there also something going to change about the tsconfig.json? currently it creates the same as before (with compilerOptions.types: "bun-types") what is the intended behavior?

probably just removing this entry. TS already reads `@types` by default =)

**Comment by ArnaudBarre** [comment]
I've done a PR to do a bit more because the TS config is a bit lax IMO
