### ISSUE TITLE
Bun `build` with a macro freezes the build from version 0.0.16

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#7808]
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

create a file to build that has an import with a macro:

```ts
import { someMacro } from "../some-macro" assert { type: "macro" };
```

Then build the file. I used this command:

```sh
bun build --minify --target=bun --outdir=out/cli src/cli/build.ts src/cli/serve/index.tsx
```

The build freezes and never finishes, without giving any error feedback. The error it happens locally and also in the GitHub action:

<img width="1591" alt="Screenshot 2023-12-23 at 23 44 58" src="https://github.com/oven-sh/bun/assets/13313058/eafc637c-5357-4873-bdaa-ce89580eec87">

On the other hand. In 0.0.15 and earlier it worked fine. The build also works commenting the macro:

```ts
import { someMacro } from "../some-macro" // assert { type: "macro" };
```

### What is the expected behavior?

Make `bun build` with macros work just as well as before.

### What do you see instead?

Nothing. No error feedback. Build freezes and never finishes.

**Comment by Jarred-Sumner** [comment]
What does the macro do?

**Comment by aralroca** [comment]
> What does the macro do?

I have this macro to inject client code during rendering:

```ts
import path from "node:path";

// Should be used via macro
export async function injectUnsuspenseCode() {
  const { success, logs, outputs } = await Bun.build({
    entrypoints: [path.join(import.meta.dir, "unsuspense.ts")],
    outdir: path.join(import.meta.dir, "out"),
    target: "browser",
    minify: true,
  });

  if (!success) console.error(logs);

  return (await outputs?.[0]?.text?.()) ?? "";
}
```

**Comment by aralroca** [comment]
@Jarred-Sumner this is a reproducible simple example if it helps to identify the issue:

[bun-bug.zip](https://github.com/oven-sh/bun/files/13835610/bun-bug.zip)

To reproduce the issue:

```bash
bun build --minify --target=bun --outdir=build index.ts
```

In Bun 1.0.15 or below is generating 2 build folders:

- `build-client` - client code build on the macro
- `build` - bun code (server) with injected client code thanks to the macro


After Bun 1.0.15:

Nothing happening, infinite build...

**Comment by aralroca** [comment]
I think is related with this one https://github.com/oven-sh/bun/issues/7611

**Comment by aralroca** [comment]
This is solved
