### ISSUE TITLE
Support --hot with --watch for tests

### ISSUE THREAD

**Issue by icetbr** [oven-sh/bun#7809]
### What is the problem this feature would solve?

This reloads in 12ms
```js
it("2 + 2", () => {
  expect(2 + 2).toBe(4);
});
```
Adding this, it reloads in 45ms
```js
import lodash from 'lodash';
```
Adding this, it reloads in 50ms
```js
import fde from 'fast-deep-equal';
```
Adding this, it reloads in 135ms
```js
import expect1 from 'expect';
```

### What is the feature you are proposing to solve the problem?

Hot reload (HMR) for `bun test --watch` so that it's speed is not affected by scalability

**Comment by Electroid** [comment]
`bun test --watch` and `bun test --hot` both work.

**Comment by icetbr** [comment]
bun test --hot --watch doesn't. Although it likely wouldn't achieve what I want. I need a custom esm loader, or at least, external library cache perhaps.

**Comment by Electroid** [comment]
> bun test --hot --watch doesn't. Although it likely wouldn't achieve what I want. I need a custom esm loader, or at least, external library cache perhaps.

`--watch` does a full process restart, `--hot` does hot-module reloading. What would you want to happen if you use both?

**Comment by icetbr** [comment]
I want constant test time. If I run `bun test` with zero dependencies, it takes 12ms. If I add 1 external import, like lodash,, it goes to 45ms. 2 imports, 50ms. The 3rd import takes 135ms per reload. This isn't scalable. 

Mocha has "true" hmr for CJS, and with a custom loader, it works for esm as well. This requires node's custom module loader however.

https://github.com/mochajs/mocha/pull/4855/files
https://nodejs.org/api/module.html#customization-hooks

**Comment by icetbr** [comment]
May I reopen this issue with a different title perhaps?
