### ISSUE TITLE
crypto.randomUUID runs faster on node than bun

### ISSUE THREAD

**Issue by shawshankkumar** [oven-sh/bun#7811]
### What is the problem this feature would solve?

bun slower than node in generating randomUUID

### What is the feature you are proposing to solve the problem?

not sure 🤔 

### What alternatives have you considered?

Code: 

```const Benchmark = require("benchmark");
const crypto = require("crypto");

// Your two functions to compare
function function1() {
  const code = "some data to hash";

  const hash = crypto.createHash("sha256").update(code).digest("hex");
}

function function2() {
  const hash = crypto.randomUUID();
}

function function3() {
     const a = crypto.randomBytes(Math.ceil(12 / 2)).toString('hex').slice(0, 12);
}   

// Create a new benchmark suite
const suite = new Benchmark.Suite();

// Add tests to the suite
suite
  .add("Function 1", function () {
    function1();
  })
  .add("Function 2", function () {
    function2();
  })
  .add("Function 3", function () {
    function3();
  })
  // Add listeners for the 'cycle' and 'complete' events
  .on("cycle", function (event) {
    console.log(String(event.target));
  })
  .on("complete", function () {
    console.log("Fastest is " + this.filter("fastest").map("name"));
  })
  // Run the benchmark
  .run({ async: true });
```

<img width="635" alt="image" src="https://github.com/oven-sh/bun/assets/74819565/0b283427-bf56-4eee-a25b-a0a6e9999fdf">

**Comment by Jarred-Sumner** [comment]
A couple notes:
1) Don't use Benchmark.js for microbenchmarking (especially the `async` option). Most of the gap here is the microtask queue which is unrelated to crypto.randomUUID()
2) Benchmarks like these should return the value to make it harder for the JIT to potentially optimize away the function calls

That being said, you nerdsniped me into making crypto.randomUUID 15% faster

<img width="621" alt="image" src="https://github.com/oven-sh/bun/assets/709451/7e1cb305-8ab4-4ba2-a51f-b6cbc3c903c7">

**Comment by shawshankkumar** [comment]
> A couple notes:
> 
> 1. Don't use Benchmark.js for microbenchmarking (especially the `async` option). Most of the gap here is the microtask queue which is unrelated to crypto.randomUUID()
> 2. Benchmarks like these should return the value to make it harder for the JIT to potentially optimize away the function calls
> 
> That being said, you nerdsniped me into making crypto.randomUUID 15% faster
> 
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/709451/292734834-7e1cb305-8ab4-4ba2-a51f-b6cbc3c903c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDU3MDQsIm5iZiI6MTcwMzUwNTQwNCwicGF0aCI6Ii83MDk0NTEvMjkyNzM0ODM0LTdlMWNiMzA1LThhYjQtNGJhMi1hNTFmLWI2Y2JjM2M5MDNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxMTU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTYyOTA2OTI4N2VlZTU4NTcwZDljNWZmMTI4MmY0ZGIxM2VmMGQ3Y2Y2MGMyYzNlYmZiM2Q5ODA4YjU5OTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmpz_gXlrZCkG5wXTM74nXKSIPaGw6EXtFyxzoFHmZs">

Oh okay. 
Interesting notes, will keep that in mind.

Thanks for making things fast for us !
