### ISSUE TITLE
Bun.spawn IPC race condition with on message [v1.0.19]

### ISSUE THREAD

**Issue by asilvas** [oven-sh/bun#7812]
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

```
export {};

const IS_CHILD = !!process.env.CHILD;

if (IS_CHILD) {
  await Bun.sleep(1_000); // will trigger race condition because we're not listening to messages yet

  process.on('message', async (msg) => {
    await Bun.sleep(1_000);

    process.send('PONG');
  });
} else {
  const child = Bun.spawn(process.argv, {
    env: {
      ...process.env,
      CHILD: 'true',
    },
    async ipc(msg) {
      console.log(msg);
      child.kill();
    },
  });

  child.send('PING');
  console.log('PING');

  await child.exited;

  console.log('exited');
}
```

### What is the expected behavior?

```
PING
PONG
exited
```

### What do you see instead?

```
PING
```

### Additional information

The example docs is misleading as any real app that must load dependencies will hit this race condition: https://bun.sh/guides/process/ipc

I suspect quite a few people are hitting this race condition randomly

**Comment by Electroid** [comment]
Are you suggesting we should update our example, or that there is a bug in Bun? You'll want to call `process.on` immediately, before `Bun.sleep`.

**Comment by asilvas** [comment]
> Are you suggesting we should update our example, or that there is a bug in Bun? You'll want to call `process.on` immediately, before `Bun.sleep`.

This is a bug. The sleep was a dumb way to force a small delay at startup to emulate loading dependencies, which any normal app does. The parent process calling send will never be received. This is a race condition.

**Comment by paperclover** [comment]
Node.js buffers input until 'message' is listened on. We should too.
