### ISSUE TITLE
`process.env.NODE_ENV` should be `undefined` as default

### ISSUE THREAD

**Issue by guyutongxue** [oven-sh/bun#7829]
### What version of Bun is running?

1.0.20

### What platform is your computer?

Linux 6.5.0-14-generic x86_64 x86_64

### What steps can reproduce the bug?

```sh
$ cat test.mjs
console.log(process.env.NODE_ENV);
$ bun test.mjs
development
```

### What is the expected behavior?

Should output `undefined`, just like Node.js does:
```sh
$ node test.mjs
undefined
```

### What do you see instead?

Bun produces `development`.

### Additional information

Vite check this value when running `vite build`. If `NODE_ENV` was not set, then `vite build` will automatically set `NODE_ENV` to `production`, then everything goes fine (on Node.js). 

But Bun uses `development` as default `NODE_ENV`, so `vite build` just take this instead of set it to `production`... then things like `import.meta.env.PROD` will be wrong.

As a consequence, I need to run `NODE_ENV=production bunx --bun vite build` instead of simple `bunx --bun vite build` to get the correct result.

**Comment by TiBianMod** [comment]
Related to PR https://github.com/oven-sh/bun/pull/7666

also packages like `dotenv`, will always show `NODE_ENV=development`, no matter what you have on `.env` file

**Comment by guyutongxue** [comment]
OK... I should have checked closed issues; #7663 addresses almost same question -- but in a contrast direction 🫠 

Anyway I tend to believe that undefined `NODE_ENV` is the correct behavior, at least for compatibility to Node.js.

**Comment by Jarred-Sumner** [comment]
`undefined` is the correct behavior. but we unfortunately made it `"development"` early on and changing that is a breaking change.

**Comment by Electroid** [comment]
We are thinking of making this change in Bun v1.1

**Comment by Electroid** [comment]
This change will be announced and made in Bun 1.1

**Comment by marcospgp** [comment]
has this also been fixed for the bundler? I am still seeing it as `development`:

```
// test.js
console.log(process.env.NODE_ENV);
```

```
$ bun build test.js                                                                                                 git:main*
// test.js
console.log("development");
$ bun --version                                                                                                     git:main*
1.1.42
```

**Comment by vdawg-git** [comment]
Same thing for standalone binaries. I still get `"development"`

**Comment by paperclover** [comment]
> has this also been fixed for the bundler? I am still seeing it as

it is intentional that the bundler specifies NODE_ENV for tree-shaking purposes. i am not sure we should change this behavior just for `--compile`, but we could communicate this better by logging the word "development" somewhere in the output for `bun build`

**Comment by marcospgp** [comment]
@paperclover "tree-shaking purposes" isn't very clear - why would implicitly baking an environment variable be an obligatory default?

**Comment by willruggiano** [comment]
Yeah this is kind of a joke lol.

`--env=disable` seems to work
