### ISSUE TITLE
Makefile Error with `make devcontainer` - `jsc-bindings-headers` comes before `libbacktrace`

### ISSUE THREAD

**Issue by Omer-Shahar** [oven-sh/bun#784]
### What is the expected behavior?

Running `make devcontainer` runs `jsc-bindings-headers` before it runs `libbacktrace`.

`jsc-bindings-headers` uses the variable `BUN_LLD_FLAGS_WITHOUT_JSC`, which uses the variable `ARCHIVE_FILES`, which uses the variable `ARCHIVE_FILES_WITHOUT_LIBCRYPTO`, which requires `$(BUN_DEPS_OUT_DIR)/libbacktrace.a` to exist.

However, the creation of `$(BUN_DEPS_OUT_DIR)/libbacktrace.a` only occurs at `libbacktrace` (that runs later on).

This is the relevant code from `Makefile`:

```
devcontainer: ... jsc-bindings-headers ... libbacktrace ...
```

```
ARCHIVE_FILES = $(ARCHIVE_FILES_WITHOUT_LIBCRYPTO) -lcrypto
...
ifeq ($(OS_NAME), linux)
    ...
    ARCHIVE_FILES_WITHOUT_LIBCRYPTO += $(BUN_DEPS_OUT_DIR)/libbacktrace.a
endif
BUN_LLD_FLAGS_WITHOUT_JSC = $(ARCHIVE_FILES) ...
...
jsc-bindings-headers: ... $(BUN_LLD_FLAGS_WITHOUT_JSC) ...
```
```
libbacktrace:
    ...
    cp ./.libs/libbacktrace.a $(BUN_DEPS_OUT_DIR)/libbacktrace.a
```

### What do you see instead?

I might be wrong, but I think the code above causes the errors described in #741:
```
clang: error: no such file or directory: '/build/bun-deps/libbacktrace.a'
clang: error: no such file or directory: '/build/bun-deps/libuwsockets.o'
clang: error: no such file or directory: '/build/bun-deps/sqlite3.o'
make: *** [Makefile:740: jsc-bindings-headers] Error 1
```
It makes sense because this code also applies to `libuwsockets.o` and `sqlite3.o`, that appear in the error as well.

**Comment by Omer-Shahar** [comment]
### Update:
After running:
```
make libbacktrace
make uws
make sqlite
```
In order to generate the missing files mentioned above,
I finally managed to get an error about other files 😅 (when running `make devcontainer` afterwards):
```
ld.lld: error: unable to find library -llolhtml
ld.lld: error: unable to find library -lbase64
ld.lld: error: unable to find library -ltcc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:740: jsc-bindings-headers] Error 1
```
It seems like there is a problem with the order in which the commands are running.
Does anyone know if it is something to do with my specific setup (described in #741), or if it's a real bug?
Thanks in advance!

**Comment by Electroid** [comment]
We've changed our build system since this issue was created. If you still run into this issue after upgrading, re-open this issue and we'll investigate.
