### ISSUE TITLE
Align install `--production` with the other package managers

### ISSUE THREAD

**Issue by raulfdm** [oven-sh/bun#7842]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

`bun install` with `--production` flag should be aligned with what the other package managers do OR, accept another flag like `--no-frozen-lockfile`.

In some cases, especially while handling docker builds within monorepos, it's useful to be able to copy an entire subpackage WITHOUT the lock file (as it's "isolated") and only install the production dependencies.

With all package managers (yarn, pnpm, npm) this is possible, except bun.

### Steps to repro

1. create a folder
2. create a package.json with the following content:
   ```json
   {
     "name": "dummy-package",
     "private": true,
     "version": "1.0.0",
     "dependencies": {
       "lodash": "4.17.21"
     },
     "devDependencies": {
       "typescript": "5.3.3"
     }
   }
   ```
3. run `bun install --production`
4. see the error:
   ```
   error: lockfile had changes, but lockfile is frozen
   ```

https://github.com/devraul/bug-install-prod

### What is the expected behavior?

Install the dependencies without a problem, OR, accept a flag to **NOT** frozen the lock file and install the dependencies correctly.

### What do you see instead?

```
error: lockfile had changes, but lockfile is frozen
```

**Comment by dylan-conway** [comment]
This is fixed in bun `v1.1.2` and newer versions, closing as complete. Please open a new issue if you continue to have issues with `--production` installs. Excluding dev dependencies in workspaces with `--production` will be included in the next release (`1.1.14`) later today.
