### ISSUE TITLE
`bun install --frozen-lockfile` doesn't seem to work in workspaces

### ISSUE THREAD

**Issue by robertherber** [oven-sh/bun#7843]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

- Create a workspace with at least one dependency in a subpackage
- Run `bun install`
- Run `bun install --frozen-lockfile`. It fails even if the lockfile doesn't change

### What is the expected behavior?

If the lockfile doesn't change I expect --frozen-lockfile to pass.

### What do you see instead?

That `bun install --frozen-lockfile` passes in workspaces.

**Comment by dylan-conway** [comment]
This is fixed in the latest release of bun. I'm guessing this was fixed in bun v1.1.9 with #11177
