### ISSUE TITLE
`bun add` in workspace package ruins lockfile

### ISSUE THREAD

**Issue by robertherber** [oven-sh/bun#7844]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. Have a workspace with at least two packages with individual dependencies.
2. Run `bun add a-package` in a package in that workspace.
3. The lockfile only contains dependencies of the package we ran the bun add on in step 2.
4. (workaround) If I run a new `bun install` the lockfile is repaired

### What is the expected behavior?

I'd expect the lockfile to be consistent with the one I get when running `bun install` after running `bun add` in the workspace package.

### What do you see instead?

The lockfile is messed up, missing all dependencies except for those in that specific workspace package.

**Comment by johnpyp** [comment]
I've replicated this locally pretty easily and can confirm. Running `bun add react` for example in one of the workspaces wipes out the dependencies from the other workspace, and only another `bun install` ends up reconciling them. Confirmed by just using `bun bun.lockb` after each run.

**Comment by fredericoo** [comment]
yes however `bun install x` inside a workspace folder will add the package to the root `package.json`, whereas `bun add x` correctly adds it to the contextual `package.json`.

the ideal would be a mix of both.

**Comment by robertherber** [comment]
@fredericoo Yeah, this is an issue in itself. This got us to start using `bun add x`, but quickly made us realize we need to run `bun install` after this to repair the lock file.
