### ISSUE TITLE
Connection problems with a RabbitMQ client

### ISSUE THREAD

**Issue by PabloReszczynski** [oven-sh/bun#7851]
### The library
[node-rabbitmq-client](https://github.com/cody-greene/node-rabbitmq-client)

### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

## Have a running rabbitmq service with default user/password.

In mac, it can be installed with homebrew:

```bash
brew install rabbitmq
brew services start rabbitmq
```

To reproduce, just start a connection with the default parameters:
```javascript
// index.js
import { Connection } from "rabbitmq-client";

const rabbit = new Connection();

rabbit.on("error", console.error);
rabbit.on("connection", () => {
    console.log("Connected succesfully");
});
```

Package.json: 
```json
{
  "name": "bun-test-rabbitmq-client",
  "dependencies": {
    "rabbitmq-client": "^4.4.0",
  },
  "type": "module"
}
```

### What is the expected behavior?

When running with node: 

```bash
❯ node index.js
Connected succesfully
```

### What do you see instead?

```bash
bun index.js
269 |                 ...this._opt.socket,
270 |                 ...this._opt.tls
271 |             });
272 |         }
273 |         else {
274 |             socket = node_net_1.default.connect({
                           ^
TypeError: Expected "port" to be a number between 0 and 65535
 code: "ERR_INVALID_ARG_TYPE"

      at connect (node:net:257:19)
      at _connect (/Users/p/repos/rabbitmq-example/node_modules/rabbitmq-client/lib/Connection.js:274:22)
      at new Connection (/Users/p/repos/rabbitmq-examples/node_modules/rabbitmq-client/lib/Connection.js:89:24)
      at /Users/p/repos/rabbitmq-examples/index.js:3:16
```

### Additional information

I'm not sure when the error is happening. It could be either on the `net.Socket` implementation, or the way the library creates the buffers to pass to the socket.

I only know that the connection is made using `net.Socket`. Sorry that I can't give you more details.

**Comment by PabloReszczynski** [comment]
Some updates: Passing the port directly as a number changes the error:

```typescript
const rabbit = new Connection({
  hostname: "127.0.0.1",
  port: 5672,
  username: "guest",
  password: "guest",
});
```

```bash
❯ bun index.ts
4 | /** Low severity, e.g. nack'd message */
5 | class AMQPError extends Error {
6 |     code;
7 |     /** @internal */
8 |     constructor(code, message) {
9 |         super(message);
            ^
AMQPConnectionError: socket closed unexpectedly by server
 code: "CONN_CLOSE"

      at new AMQPError (/Users/p/repos/rabbitmq-example/node_modules/rabbitmq-client/lib/exception.js:9:9)
      at new AMQPChannelError (:1:33)
      at new AMQPConnectionError (:1:33)
      at /Users/p/repos/rabbitmq-example/node_modules/rabbitmq-client/lib/Connection.js:298:54
      at node:net:12:43
      at processTicksAndRejections (:61:77)

      at /Users/p/repos/rabbitmq-example/index.ts:22:3
      at node:events:2:49
      at /Users/p/repos/rabbitmq-example/node_modules/rabbitmq-client/lib/Connection.js:309:21
      at node:net:12:43
      at processTicksAndRejections (:61:77)
```

And in the rabbit logs I see this error:

```
2023-12-28 12:28:11.190378-03:00 [info] <0.14436.0> accepting AMQP connection <0.14436.0> (127.0.0.1:53924 -> 127.0.0.1:5672)
2023-12-28 12:28:14.252868-03:00 [error] <0.14436.0> closing AMQP connection <0.14436.0> (127.0.0.1:53924 -> 127.0.0.1:5672):
2023-12-28 12:28:14.252868-03:00 [error] <0.14436.0> {handshake_error,starting,28255,
2023-12-28 12:28:14.252868-03:00 [error] <0.14436.0>                  {amqp_error,frame_error,
2023-12-28 12:28:14.252868-03:00 [error] <0.14436.0>                              "type 206, all octets = <<>>: {frame_too_large,1431532544,4088}",
2023-12-28 12:28:14.252868-03:00 [error] <0.14436.0>                              none}}
```
Moreover, I think this may also be related to a similar issue: #5627

**Comment by tgrushka** [comment]
Yep. Having this issue. All day, and it turns out to be another Bun issue. Why would Bun have anything to do with the socket library? Is Bun trying to optimize it or something?

**Comment by DoKoB0512** [comment]
Bun uses [µWebsocket](https://github.com/uNetworking/uWebSockets) under the hood. Maybe that is causing this issue.

**Comment by PabloReszczynski** [comment]
> Bun uses [µWebsocket](https://github.com/uNetworking/uWebSockets) under the hood. Maybe that is causing this issue.

I doubt it, unless nuWebsocket is used by the bun project to implement the TCP layer. RabbitMQ uses it own protocol (AMQP) over TCP.

**Comment by PabloReszczynski** [comment]
@DoKoB0512 you were partly right, Bun uses a fork of [uSockets](https://github.com/uNetworking/uSockets)

**Comment by DoKoB0512** [comment]
I wonder why the it's closing out the connection

![image](https://github.com/oven-sh/bun/assets/123281216/321594ad-974e-4a7c-8d42-339b84d978ed)

**Comment by nektro** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4791
