### ISSUE TITLE
investigate console.log segfault

### ISSUE THREAD

**Issue by evanwashere** [oven-sh/bun#786]
`bun bench/log/bun.js` sometimes segfaults

_Originally posted by @evanwashere in https://github.com/oven-sh/bun/issues/771#issuecomment-1188433693_

**Comment by sno2** [comment]
Seems similar to the top-level await segfault described by Jarred in https://github.com/oven-sh/bun/issues/605

**Comment by Jarred-Sumner** [comment]
The top-level-await  segfault is likely solved by upgrading to latest webkit. They fixed it in the issue

The console.log segfault is probably a memory ownership issue between C++ & Zig code when the input is a temporary value
