### ISSUE TITLE
Bun's `ws` mock is missing readonly instance members

### ISSUE THREAD

**Issue by mmtftr** [oven-sh/bun#7892]
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

There is a missing instance member in the Bun mocked WebSocket. I found this bug due to a problem I had when I was using trpc with bun.

https://github.com/trpc/trpc/blob/4e101e3af7ce3ee92eb5c3f7d167d2a800e73a55/packages/server/src/adapters/ws.ts#L162

This line depends on this instance member being present. I checked @types/ws and it does indeed declare this to be an instance member in addition to being a static member.

```ts
import {Server} from 'ws';

  const wss = new ws.Server({
    host: "127.0.0.1",
    port: 3000,
  });

wss.on("connection", (client) => {
  console.log(client.OPEN); // undefined in Bun, 1 in "ws"
});
```

### What is the expected behavior?

I expected the instance members to be present.

### What do you see instead?

They are not.

### Additional information

My current workaround for trpc is to do this:

```ts
  wss.once('connection', (client) => {
    // @ts-ignore
    client.__proto__.OPEN = 1;
  });
```

**Comment by vortex73** [comment]
I would like to work on this issue. Please elaborate on this.
