### ISSUE TITLE
Fails to Throw 'Maximum Call Stack Size Exceeded' Error on Recursive Function and pins CPU on 100%

### ISSUE THREAD

**Issue by BenGearset** [oven-sh/bun#7899]
### What version of Bun is running?

1.0.20

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```javascript
const func = () => func();
func();
```

### What is the expected behavior?

`node file.js`
```
Started
file:///.../demo/file.js:2
const func = () => func();
                   ^

RangeError: Maximum call stack size exceeded

```

### What do you see instead?

Stuck on nothing.
![Screenshot 2023-12-28 at 21 45 01](https://github.com/oven-sh/bun/assets/113354590/42aac4bd-eb15-4de8-8103-fc1224029cd8)

**Comment by Electroid** [comment]
See #928

> This is because WebKit supports [tail-call optimization](https://webkit.org/blog/6240/ecmascript-6-proper-tail-calls-in-webkit/), which is not supported by V8 or Node.js. While it has its downsides, like the example you provided, it overall is an improvement to performance.
