### ISSUE TITLE
Compile code that relies on Workers

### ISSUE THREAD

**Issue by mkvlrn-cm42** [oven-sh/bun#7901]
### What is the problem this feature would solve?

I want to be able to compile code that relies on the usage of Workers, which are not directly imported in code, but rather referenced in a Worker 
```ts
new Worker(new URL('../workers/my-worker.ts', import.meta.url), { type: 'module' });
```
and have the resulting executable work as it does when running the code directly with `bun run`.

### What is the feature you are proposing to solve the problem?

As proposed in [this comment by @Jarred-Sumner](https://github.com/oven-sh/bun/discussions/7846#discussioncomment-7962841) in my question in Discussions, making `new Worker` create an entry point dynamically could work.

### What alternatives have you considered?

I have only tried to compile normally without success (execution stops because file referenced by Worker is not found during runtime, as it was not part of the compilation), and to actually do simple, direct imports in my code, like `import '../workers/my-worker.ts';` in code but even then the executable would halt with the same error as before: can't find referenced file.

**Comment by vish9812** [comment]
Directly passing the path worked for me: `new Worker("my-worker.ts");`

**Comment by derekhearst** [comment]
@mkvlrn 
I'm running into the same issue as you, did you ever find a workaround?

**Comment by redraskal** [comment]
> @mkvlrn I'm running into the same issue as you, did you ever find a workaround?

until that is implemented-

bundling the worker code separately, importing it as a text file (to inline the code), writing the worker script to a location, then passing the path as the worker script url

first, i tried to do this in a somewhat clean way with macros, but async macros do not seem to work on windows :(

**Comment by witran** [comment]
In my case, I want to compile a single executable for server environment that uses worker:
- I have `src/my-app.ts` that uses `src/my-worker.ts`.
- To make this work, I will have a single executable `my-app` that loads `my-worker.js` in the same dir.
- In main process code, 
  - if local env use `new Worker(import.meta.dir + '/my-worker.ts')`, 
  - if server env use `new Worker(fs.readlinkSync('/proc/self/exe').replace(/\/[^/]+$/, '/my-worker.js'))`
- Build 
  - `bun build --compile --target=bun-linux-x64 --outfile=dist/my-app src/my-app.ts` -> `dist/my-app`
  - `bun build --target=bun --oudir=dist src/my-worker.ts` -> `dist/my-worker.js`
- Deploy these 2 and run anywhere.

Not sure if there is any cleaner way.

**Comment by terrablue** [comment]
It is possible to include a worker within an executable, with the following caveats:
* You need to include the worker as an asset and pass it in an object URL
* The worker itself cannot use any imports except for Bun built-ins; if you need imports, they must be passed in as assets as well

Here is an example of using the [webview](https://github.com/webview/webview) library with a Bun server. Webview itself must run in a worker because it would otherwise block the main process.

In`app.js`:
```js
// import worker as asset
import worker from "./worker.js" with { type: "file"};
// import a worker dependency as asset
import libwebview from "./libwebview.so" with { type: "file" };

// start server
Bun.serve({ port: 6161, fetch: () => new Response("hi") });

// start worker
const worker = new Worker(URL.createObjectURL(Bun.file(worker_url)));
// pass in dependency URL
worker.postMessage({ dependencies: { libwebview } });
```

You need a compiled `libwebview.so` library in the same directory. For Linux, clone the webview repo and run:
```sh
c++ webview/webview.cc -DWEBVIEW_API=extern -DWEBVIEW_GTK -shared -std=c++11 -Wall -Wextra -pedantic -fpic $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0) -o libwebview.so
strip libwebview.so
```

In `worker.js`:
```js
// only built-in imports allowed
import { FFIType, dlopen, ptr } from "bun:ffi";

const cstring = value => ptr(new TextEncoder().encode(`${value}\0`));

// load binary dependency
const import_binary_dependency = bin => dlopen(bin, {
  webview_create: {
      args: [FFIType.i32, FFIType.ptr],
      returns: FFIType.ptr,
  },
  webview_destroy: {
      args: [FFIType.ptr],
      returns: FFIType.void,
  },
  webview_run: {
      args: [FFIType.ptr],
      returns: FFIType.void,
  },
  webview_terminate: {
      args: [FFIType.ptr],
      returns: FFIType.void,
  },
  webview_navigate: {
      args: [FFIType.ptr, FFIType.ptr],
      returns: FFIType.void,
  },
});

const wv = bin => {
  const lib = import_binary_dependency(bin);

  const Webview = class Webview {
    #handle = null;
    constructor() {
      this.#handle = lib.symbols.webview_create(true, null);
    }

    destroy() {
      lib.symbols.webview_terminate(this.#handle);
      lib.symbols.webview_destroy(this.#handle);
      this.#handle = null;
    }

    navigate(url) {
      lib.symbols.webview_navigate(this.#handle, cstring(url));
    }

    run() {
      lib.symbols.webview_run(this.#handle);
      this.destroy();
    }
  };

  return Webview;
};

self.addEventListener("message", async event => {
  const { dependencies { libwebview } } = event.data;
  const Webview = wv(Bun.file(libwebview));
  const webview = new Webview();
  webview.navigate("http://localhost:6161");
  webview.run();
});
```

Running `bun build main.js --compile --outfile app` will produce an executable that includes the worker and can run independently, from any path.

Code taken from the upcoming version of [primate](https://github.com/primatejs/primate) that will allow packaging apps as executables.

**Comment by Gin-Quin** [comment]
This does not work when building though.

IMO, workers should be imported and treated as assets, like this:

```ts
import myWorkerPath from "path/to/my/worker.ts" with { type: "worker" }

const worker = new Worker(myWorkerPath)
```
