### ISSUE TITLE
bun a react-scripts -d get return SegmentationFault at 0

### ISSUE THREAD

**Issue by jimmyMisa** [oven-sh/bun#791]
### Version

0.1.4

### Platform

Linux 94dd59e2d89a 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 Linux

### What steps will reproduce the bug?

I work on windows and using docker referenced at https://github.com/oven-sh/bun#install
First, create the container
```
docker run -it -d --name bune --ulimit memlock=-1:-1 jarredsumner/bun:edge
docker exec -it bune sh
```
Then on the container
```
mkdir -p /var/www/app
cd /var/www/app
bun create react test1
cd test1
bun a react-scripts -d
```

### How often does it reproduce? Is there a required condition?

Everytime I run
```
bun a react-scripts -d
```

### What is the expected behavior?

react-scripts required to be installed

### What do you see instead?

I receive
```
bun add v0.1.4
  🔍 collect-v8-coverage [853/1283]
SegmentationFault at 188


–––– bun meta ––––
Bun v0.1.4 Linux x64 #1 SMP Wed Mar 2 00:30:59 UTC 2022
AddCommand:
HTTP: 634
Elapsed: 47510ms | User: 58230ms | Sys: 15681ms
RSS: 0.40GB | Peak: 0.42GB | Commit: 0.40GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```
![2022-07-19 16_36_07-Window](https://user-images.githubusercontent.com/16359487/179764054-19785ac2-9ef9-496e-bec5-3190c924a963.png)

### Additional information

Tryied manytime in another contaier then get more error

![2022-07-19 16_31_36-Window](https://user-images.githubusercontent.com/16359487/179763690-3b929e9d-7628-48eb-ba03-454a1177ca8b.png)

**Comment by Jarred-Sumner** [comment]
I believe this was fixed 1-2 versions ago, but please leave a comment if not
