### ISSUE TITLE
`peerDependencies` not resolving properly

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#7932]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install a a package that requires a peerDependency to work, also install said peerDependency.
Afterwards, try to update the peerDependency.

If you are using typescript you will find lots of type collisions because of missmatched versions, if you observe further you will see that bun has installed 2 versions of the dependency instead of just having the one you updated

### What is the expected behavior?

I expect bun to just have 1 version of the dependency

### What do you see instead?

Bun installs multiple versions

**Comment by Jarred-Sumner** [comment]
Can you provide a more complete reproduction?

**Comment by Didas-git** [comment]
This is the most recent repro i can remember.
Clone: https://github.com/xHyroM/bun-discord-bot/tree/62e52832e72dd04b81960a9c48395a4cdf87762d
Update dependencies (in this case lilybird which is a peerDependency for 2 other packages) and typescript will complain about missmatched versions, looking further seems like the packages that have this dependency as a peerDependency have their own node_modules with the previous version even tho their version ranges include patches

**Comment by quantizor** [comment]
Possibly related https://github.com/oven-sh/bun/issues/7869

**Comment by 7f8ddd** [comment]
I can attest to this being an issue while using Elysia. I have to delete Elysia from the Elysia plugin's node_modules and re-install it to fix it.
