### ISSUE TITLE
`Bun.file` crashes when passed to `Response`

### ISSUE THREAD

**Issue by solenopsys** [oven-sh/bun#7937]
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

x64 wsl ubuntu 20

### What steps can reproduce the bug?

Code for reproduce:
```
    const file = Bun.file(fileFromCache);
    return new Response(file);
```

### What is the expected behavior?

The program must not crash.

### What do you see instead?

In browser have response but program crashes 
```
Segmentation fault
```

### Additional information

This code working.

```
const file =Bun.file(fileFromCache);
 const fileContent = await file.arrayBuffer();
 return new Response(fileContent);

```

**Comment by solenopsys** [comment]
Context :

```
function startServer(rootDir: string, name: string, bsDir: string, port: number) {
  const server = Bun.serve({

    port: port,
    async fetch(request) {
      console.log("REQUEST", request.url);
      const url = new URL(request.url)


      const path = url.pathname
      if (path.startsWith("/library/")) {
        return await serveLibraries(join(rootDir, "configuration"), path);
      } 

    },
  });


  console.log(`Start server ${name}: ${server.port}`, Bun.nanoseconds());
}
```
```

async function serveLibraries(rootDir: string, pathUri: string): Promise<Response> {
  ~~~~~

  if (existsSync(fileFromCache)) {
    console.log("LIB FROM CACHE", fileFromCache);

    const file = Bun.file(fileFromCache);
    return new Response(file);
  }
```

Maybe I used it incorrectly

**Comment by ghost** [comment]
Not sure if this is what's causing the issue, but `Bun.file()` itself represents a lazily-loaded file, so it's not actually being read from the disk - it's only once you call `Bun.file().text()`, `.stream()`, or `.arrayBuffer()` (with `await`) that something happens. Do you perhaps mean to use one of those instead?

```js
const foo = Bun.file("foo.txt");

await foo.text(); // contents as a string
await foo.stream(); // contents as ReadableStream
await foo.arrayBuffer(); // contents as ArrayBuffer
```

**Comment by Electroid** [comment]
`Bun.file` is a `Blob`, so `new Response(Bun.file("..."))` should work. There is indeed a bug.

**Comment by LoganBwDE** [comment]
Any updates on this issue?

**Comment by gvilums** [comment]
This works in bun 1.1.7
