### ISSUE TITLE
`bun install @lit-labs/ssr` not working

### ISSUE THREAD

**Issue by jefer94** [oven-sh/bun#7941]
### What version of Bun is running?

bun-v1.0.17 to bun-v1.0.20

### What platform is your computer?

Linux 6.6.8-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

```bash
$ bun install @lit-labs/ssr                                                                                    10:37:29
bun add v1.0.17 (5e60861c)
  🔍 @lit-labs/ssr [6/6] 
error: ConnectionRefused downloading package manifest @lit-labs/ssr
error: @lit-labs/ssr@ failed to resolve
```

### What is the expected behavior?

Can install `@lit-labs/ssr`

### What do you see instead?

A `ConnectionRefused` error

### Additional information

I could install it in `NPM`

**Comment by ghost** [comment]
It seems to work fine for me, is it just that package that doesn't install? Make sure you're using the latest version of Bun.

**Comment by Electroid** [comment]
Duplicate of #7941

**Comment by Electroid** [comment]
Duplicate of #4988
