### ISSUE TITLE
Panic: cast causes pointer to be null  bun has crashed :'(

### ISSUE THREAD

**Issue by Akash1029** [oven-sh/bun#7942]
### What version of Bun is running?

1.0.21-canary.53+693a00dc5

### What platform is your computer?

Microsoft Windows NT 10.0.22000.0 x64

### What steps can reproduce the bug?

Setting up new Nuxt JS Project via this command.. Shows this error..

bunx nuxi@latest init my-project

![bunx crashed](https://github.com/oven-sh/bun/assets/69312660/d40138c4-1a31-4b71-aa40-854d311728ec)

### What is the expected behavior?

The command should've created the  Nuxt js project

### What do you see instead?

Panic: cast causes pointer to be null

bun has crashed :'(

----- bun meta -----
Bun v1.0.21-canary.53 (693a00dc) Windows x64
BunxCommand:
Elapsed: 12ms | User: 15ms | Sys: 15ms
RSS: 17.35MB | Peak: 17.35MB | Commit: 58.42MB | Faults: 4351
----- bun meta -----

0   00007FF681AB1FD8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 4808 panic: cast causes pointer to be null
???:?:?: 0x7ff68099abef in ??? (???)
???:?:?: 0x7ff6809f55e3 in ??? (???)
???:?:?: 0x7ff680831492 in ??? (???)
???:?:?: 0x7ff6829dde8f in ??? (???)
???:?:?: 0x7ffa0e9553df in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa106e485a in ??? (ntdll.dll)

**Comment by HiceS** [comment]
I'm also getting this when running any `bun create x x` on Windows 10. 

Tried running as admin and full restart as well. Also Powershell and regular command prompt just in case.


```
Panic: cast causes pointer to be null

bun has crashed :'(

----- bun meta -----
Bun v1.0.21-canary.16 (47acee5d) Windows x64
BunxCommand:
Elapsed: 9ms | User: 15ms | Sys: 0ms
RSS: 17.03MB | Peak: 17.03MB | Commit: 59.50MB | Faults: 4274
----- bun meta -----

0   00007FF6701125F8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 16504 panic: cast causes pointer to be null
???:?:?: 0x7ff66effabef in ??? (???)
???:?:?: 0x7ff66f0555e3 in ??? (???)
???:?:?: 0x7ff66ee91492 in ??? (???)
???:?:?: 0x7ff671047d4f in ??? (???)
???:?:?: 0x7ffb9b677343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb9c2626b0 in ??? (ntdll.dll)
```

edit ~~~

`bun upgrade` also does this but the help executable text works as expected.

**Comment by johnwaweru** [comment]
Facing a similar issue on Win 10

```
bun create react-app mynewapp

Panic: cast causes pointer to be null

bun has crashed :'(

----- bun meta -----
Bun v1.0.21-canary.17 (5d6c6812) Windows x64
CreateCommand:
Elapsed: 7ms | User: 0ms | Sys: 15ms
RSS: 17.08MB | Peak: 17.09MB | Commit: 59.47MB | Faults: 4285
----- bun meta -----

0   00007FF70E5537C8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 10820 panic: cast causes pointer to be null
???:?:?: 0x7ff70d43abef in ??? (???)
???:?:?: 0x7ff70d4a710d in ??? (???)
???:?:?: 0x7ff70d2d1492 in ??? (???)
???:?:?: 0x7ff70f488fbf in ??? (???)
???:?:?: 0x7ffc7fce7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffc806226b0 in ??? (ntdll.dll)

```

**Comment by umershaikh123** [comment]
getting the same issue on win 11 powershell
The workaround for this is using wsl terminal in vscode .

**Comment by johnwaweru** [comment]
> I'm also getting this when running any `bun create x x` on Windows 10.
> 
> Tried running as admin and full restart as well. Also Powershell and regular command prompt just in case.
> 
> ```
> Panic: cast causes pointer to be null
> 
> bun has crashed :'(
> 
> ----- bun meta -----
> Bun v1.0.21-canary.16 (47acee5d) Windows x64
> BunxCommand:
> Elapsed: 9ms | User: 15ms | Sys: 0ms
> RSS: 17.03MB | Peak: 17.03MB | Commit: 59.50MB | Faults: 4274
> ----- bun meta -----
> 
> 0   00007FF6701125F8
> 1   ???
> 2   ???
> 3   ???
> 4   ???
> 5   ???
> 6   ???
> 7   ???
> 
> Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
> 
> thread 16504 panic: cast causes pointer to be null
> ???:?:?: 0x7ff66effabef in ??? (???)
> ???:?:?: 0x7ff66f0555e3 in ??? (???)
> ???:?:?: 0x7ff66ee91492 in ??? (???)
> ???:?:?: 0x7ff671047d4f in ??? (???)
> ???:?:?: 0x7ffb9b677343 in ??? (KERNEL32.DLL)
> ???:?:?: 0x7ffb9c2626b0 in ??? (ntdll.dll)
> ```
> 
> edit ~~~
> 
> `bun upgrade` also does this but the help executable text works as expected.

I just noticed that it's not fully supported on Windows yet, but their team has mentioned that support for Windows is expected to be available in January 2024.

**Comment by paperclover** [comment]
all of these reproduction is a duplicate of #8045 (although that issue was open after this one, but i have been tracking bunx there)
