### ISSUE TITLE
`console.table()` doesn't handle emoji widths properly

### ISSUE THREAD

**Issue by ThatOneCalculator** [oven-sh/bun#7955]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 6.6.9-native_amd-xanmod1-1 x86_64 unknown

### What steps can reproduce the bug?

1. `console.table([{"test": "✅"}, {"test": "✅"}, {"test": "✅"}, {"test": "✅"}])`
2. `console.table([{"test 1": "✅"}, {"test 2": "✅"}, {"test 3": "✅"}, {"test 4": "✅"}])`

### What is the expected behavior?

Non-broken tables

### What do you see instead?

1.
![image](https://github.com/oven-sh/bun/assets/44733677/88d1a185-0680-4475-955a-12d1982a2535)

2.
![image](https://github.com/oven-sh/bun/assets/44733677/89022748-4397-466d-923a-b3256cc2d4d4)

### Additional information

Terminal is kitty with the Cartograph CF font

**Comment by jatindotdev** [comment]
+1, this case isn’t handled as well, i am on the latest canary

```ts
console.table([{"test": "1"}, {"test": "1"}, {"test": "1"}, {"test": "1"}])
console.table([{"test 1": "1"}, {"test 1": "1"}, {"test w": "1"}, {"test w": "1"}])
```

```bash
~/d/classwork main• ❱ bun run mod.ts
┌───┬──────┐
│   │ test │
├───┼──────┤
│ 0 │ 1    │
│ 1 │ 1    │
│ 2 │ 1    │
│ 3 │ 1    │
└───┴──────┘
┌───┬────────┬────────┐
│   │ test 1 │ test w │
├───┼────────┼────────┤
│ 0 │ 1      │         │
│ 1 │ 1      │         │
│ 2 │         │ 1      │
│ 3 │         │ 1      │
└───┴────────┴────────┘
```
