### ISSUE TITLE
`bun create` doesn't recognize the registry setting in `bunfig.toml`

### ISSUE THREAD

**Issue by uiolee** [oven-sh/bun#7963]
### What version of Bun is running?

1.0.21

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64 （WSL Debian）

### What steps can reproduce the bug?

1. cd 'project/'
1. set custom/private registry in `project/bunfig.toml`. https://bun.sh/docs/install/registries
2. run `bun create myCustomApp`

### What is the expected behavior?

`bun` should download my `create-myCustomApp` package from my custom/private registry.

### What do you see instead?

`bun` download package from npmjs.org

```log
error: package "create-myCustomApp" not found registry.npmjs.org/create-myCustomApp 404
```

### Additional information

```bash
$ debian@win10-wsl:~/project$ cat bunfig.toml
[install]
registry = "http://private.registry.com/"
```

**Comment by Electroid** [comment]
Duplicate of #617
