### ISSUE TITLE
export a `SQLiteError` class to use with `instanceof` to check for errors

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#7964]
### What is the problem this feature would solve?

it would solve this scenario:

```ts
import { SQLiteError } from "bun:sqlite";

try {
  // Add user to database
} catch (e) {
  if (e instanceof SQLiteError && e.code === "SQLITE_CONSTRAINT_UNIQUE") {
    // Username is taken etc.
  }
}
```

### What is the feature you are proposing to solve the problem?

`bun:sqlite` should export the `SQLiteError` class to JavaScript

### What alternatives have you considered?

```ts
try {
  // Add user to database
} catch (e: any) {
  if (e.code === "SQLITE_CONSTRAINT_UNIQUE") {
    // Username is taken etc.
  }
}
```

**Comment by Jarred-Sumner** [comment]
Did you try running this code

**Comment by huseeiin** [comment]
> Did you try running this code

```js
import { SQLiteError } from "bun:sqlite";

try {
  throw new SQLiteError("hi");
} catch (e) {
  console.log(e instanceof SQLiteError);
}
```

the class exists but the console log is returning `false`

**Comment by Jarred-Sumner** [comment]
> > Did you try running this code
> 
> ```js
> import { SQLiteError } from "bun:sqlite";
> 
> try {
>   throw new SQLiteError("hi");
> } catch (e) {
>   console.log(e instanceof SQLiteError);
> }
> ```
> 
> the class exists but the console log is returning `false`

Ah, that's not supposed to work. The `SQLiteError` class should only be created from within `bun:sqlite`

**Comment by huseeiin** [comment]
> > > Did you try running this code
> > 
> > 
> > ```js
> > import { SQLiteError } from "bun:sqlite";
> > 
> > try {
> >   throw new SQLiteError("hi");
> > } catch (e) {
> >   console.log(e instanceof SQLiteError);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the class exists but the console log is returning `false`
> 
> Ah, that's not supposed to work. The `SQLiteError` class should only be created from within `bun:sqlite`

that is a problem when it comes to checking for errors and autocompletion

**Comment by Jarred-Sumner** [comment]
> that is a problem when it comes to checking for errors and autocompletion

`e instanceof SQLiteError` is supposed to work.

`new SQLiteError()` is not supposed to work.

**Comment by Jarred-Sumner** [comment]
Sorry, just to clarify

This code already worked. 

The following test passes:
```js
import {SQLiteError, Database} from "bun:sqlite";

it("Missing DB throws SQLITE_CANTOPEN", () => {
  try {
    new Database("/definitely/not/found");
    expect.unreachable();
  } catch (error) {
    expect(error.code).toBe("SQLITE_CANTOPEN");
    expect(error).toBeInstanceOf(SQLiteError);
  }
});
```

**Comment by huseeiin** [comment]
> Sorry, just to clarify
> 
> This code already worked.
> 
> The following test passes:
> 
> ```js
> import {SQLiteError, Database} from "bun:sqlite";
> 
> it("Missing DB throws SQLITE_CANTOPEN", () => {
>   try {
>     new Database("/definitely/not/found");
>     expect.unreachable();
>   } catch (error) {
>     expect(error.code).toBe("SQLITE_CANTOPEN");
>     expect(error).toBeInstanceOf(SQLiteError);
>   }
> });
> ```

i suppose i should close this then :)
