### ISSUE TITLE
Register Runtime Plugins in `bunfig.toml`

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#7965]
### What is the problem this feature would solve?

Currently, to register a Bun plugin, you need to make a new TypeScript/JavaScript file, import `plugin` and your actual plugin, and then register it there, not to mention also preload it by listing on your `bunfig.toml`. That's an excessive number of steps for just using the plugin. 

### What is the feature you are proposing to solve the problem?

This feature would let you register plugin's directly in Bun's config file, `bunfig.toml`. That's where the configuration for the runtime is anyway, and so it makes sense you that you could register plugins there too.

An implementation would likely include the plugin's package name and configuration for the plugin. You would still be able to use the current way of registering plugins if you were developing a plugin yourself, and it wasn't published as a package.

Here's an example of what `bunfig.toml` could look like:

```toml
plugins = [
  {
    name: "bun-plugin-foo",
    # Configuration
  },
  {
    name: "bun-plugin-bar",
    # Configuration
  }
]
```

**Comment by Jarred-Sumner** [comment]
Sorry for not getting back to you

It's a reasonable thing to support. But we are unlikely to get to it soon
