### ISSUE TITLE
Difference in `bun i --production` and `npm i --production` when using workspaces

### ISSUE THREAD

**Issue by Patrick-Ullrich** [oven-sh/bun#7969]
### What version of Bun is running?

1..0.21+837cbd60d

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

The bug can be reproduced using this github repository: https://github.com/Patrick-Ullrich/bun-workspace-prod-bug

To reproduce this behavior, clone the repository and run from the root:

1. `npm i --production`
2. Check the node_modules folder in the root, it should have an empty `@playwright` folder. ✔️
3. Delete the node_modules folder (`rm -rf node_modules`)
4. `bun i --production`
5. Check the node_modules folder in the root. We expect an empty `@playwright` folder but you will find it having full contents

### What is the expected behavior?

When using `bun i --production` within a project with workspaces all devDependencies should be omitted, as it does when not using workspaces

**Comment by MonsterDeveloper** [comment]
Basically `--production` is not doing anything when using workspaces -> no way of pruning `devDependencies`. Hope it gets fixed soon as my Docker images are becoming increasingly heavy 😢

**Comment by this-is-tobi** [comment]
Hi,

I encountered the same problem on my monorepo template using Bun workspaces, I hope this will be fixed soon as it is an essential part of workspace functionality.
The solution I use as a workaround is to run a script in my Dockerfiles (at the production dependencies installation stage) to remove all packages that are in `devDependencies`.

It's a basic shell script that will scan the project filesystem (omitting directories containing `node_modules` and `cache` in their path), determine with [jq](https://jqlang.github.io/jq/) the list of all dev dependencies and pass it to the `bun remove` command (depending on the correct cwd location).

The patch installation script:
```sh 
#!/bin/bash

find ./apps ./packages -type f -name "package.json" -not -path "**/node_modules/*" -not -path "**/cache/*" \
  | awk '{ print substr( $0, 1, length($0)-13 ) }' \
  | while read dir; do
    if [ "$(cat $dir/package.json | jq '. | has("devDependencies")')" == "true" ]; then
      bun remove --cwd $dir $(cat $dir/package.json | jq -rc '.devDependencies | keys | join(" ")')
    fi
  done
```

> *__Notes:__* 
> - *`./apps` and `./packages` are my workspace directories.*
> - *The script requires `jq` to be installed in the docker image and must be executable (chmod +x).*

The Dockerfile used to build the api:
```Dockerfile
ARG BUN_IMAGE=docker.io/oven/bun:1.0.26
ARG BUN_IMAGE_PROD=docker.io/oven/bun:1.0.26-slim

# Base
FROM ${BUN_IMAGE} AS base

WORKDIR /app
RUN apt update && apt install -y jq && apt clean
COPY ./package.json ./bun.lockb ./ci/scripts/patch-install.sh ./
COPY ./packages/cypress/package.json ./packages/cypress/package.json
COPY ./packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY ./packages/test-utils/package.json ./packages/test-utils/package.json
COPY ./packages/ts-config/package.json ./packages/ts-config/package.json
COPY ./packages/shared/package.json ./packages/shared/package.json
COPY ./apps/api/package.json ./apps/api/package.json


# Install - dev
FROM base AS install-dev

COPY ./packages ./packages
COPY ./apps ./apps
RUN bun install --ignore-scripts


# Install - prod
FROM base AS install-prod

COPY ./packages ./packages
COPY ./apps ./apps
RUN bun install --ignore-scripts --production
RUN ./patch-install.sh


# Dev
FROM base AS dev

COPY --from=install-dev /app/node_modules ./node_modules
COPY ./packages/shared ./packages/shared
COPY ./apps/api ./apps/api
ENTRYPOINT [ "bun", "run", "--cwd", "/app/apps/api", "dev" ]


# Build
FROM base AS build

ENV NODE_ENV=production
COPY --from=install-dev /app/node_modules ./node_modules
COPY ./packages ./packages
COPY ./apps/api ./apps/api
RUN bun run --cwd ./packages/shared build


# Prod
FROM ${BUN_IMAGE_PROD} AS prod

ENV NODE_ENV=production
WORKDIR /app
COPY --chown=bun:root --from=install-prod /app/package.json /app/package.json
COPY --chown=bun:root --from=install-prod /app/node_modules /app/node_modules
COPY --chown=bun:root --from=build /app/packages/shared /app/packages/shared
COPY --chown=bun:root --from=build /app/apps/api /app/apps/api
USER bun
EXPOSE 8080/tcp
ENTRYPOINT [ "bun", "run", "--cwd", "/app/apps/api", "start" ]
```

It's like it doesn't remove all the dependencies that shouldn't be installed, but it's better than nothing.

Without `patch-install.sh` script :

| REPOSITORY                | TAG  | SIZE   |
| ------------------------- | ---- | ------ |
| template-monorepo-ts/api  | dev  | 438MB  |
| template-monorepo-ts/api  | prod | 347MB  |

With `patch-install.sh` script :

| REPOSITORY                | TAG  | SIZE   |
| ------------------------- | ---- | ------ |
| template-monorepo-ts/api  | dev  | 438MB  |
| template-monorepo-ts/api  | prod | 286MB  |

---
*The repository is available [here](https://github.com/this-is-tobi/template-monorepo-ts)*

**Comment by Jarred-Sumner** [comment]
This will be fixed in Bun v1.1.14, which releases later today.

**Comment by darkyelox** [comment]
Still happening with version 1.2.15, the ---production flag does nothing

**Comment by vadolasi** [comment]
Same at 1.2.14 here

**Comment by NormySan** [comment]
I'm getting this problem as well on Bun 1.3.5. I'm getting all dev-dependencies like Vitest, Vite, Prettier, ESLint and more in my node_modules even when I use the `--production` flag.
