### ISSUE TITLE
Not upgrading correctly

### ISSUE THREAD

**Issue by M-Gonzalo** [oven-sh/bun#7981]
### What version of Bun is running?

1.0.18+925a94ffe

### What platform is your computer?

Linux 6.6.9-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

bun upgrade
bun --version

### What is the expected behavior?

Should be upgraded

### What do you see instead?

Still old version

### Additional information

![image](https://github.com/oven-sh/bun/assets/23223606/d8f91425-d33c-4106-a754-dc084439f827)

**Comment by Jarred-Sumner** [comment]
There was a canary version of Bun which had a broken `bun upgrade` between v1.0.18 and v1.0.19 and it looks like this is within that range 

Please reinstall by running `curl https://bun.sh/install | bash`

**Comment by M-Gonzalo** [comment]
Done, thanks!
