### ISSUE TITLE
Support different orders for CLI arguments

### ISSUE THREAD

**Issue by MarceloPrado** [oven-sh/bun#7988]
### What is the problem this feature would solve?

I was trying to understand why my `--watch` was not working. Turns out I was using it in the wrong order: `bun index.ts --watch` instead of `bun --watch index.ts`. Took me a solid 20 min to debug this.

It would be great if I could add these arguments in any order. Besides being a better DX, it would also allow overriding the arguments if you have a `package.json` script. For instance, consider:

```
scripts: {
  "dev": "bun index.ts"
}
```

In my terminal, if I wrote `yarn dev --watch`, it would translate it to `bun index.ts --watch`, which wouldn't work as expected.

### What is the feature you are proposing to solve the problem?

Allow specifying bun's arguments after the filename.

**Comment by Electroid** [comment]
The challenge with this is how do we know whether the argument should be passed to Bun, or the script that is running? That’s why the order matters right now.

**Comment by MarceloPrado** [comment]
Oh that makes sense - and also explains why you can't log an error. Feel free to close this for now
