### ISSUE TITLE
Canary: thread panic on upgrade

### ISSUE THREAD

**Issue by alekcunn** [oven-sh/bun#7989]
### What version of Bun is running?

Bun v1.0.21-canary.55 

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun upgrade

upgraded recently on January 2nd 

### What is the expected behavior?

upgrade bun to the newest version

### What do you see instead?

Panic: invalid enum value

bun has crashed :'(

----- bun meta -----
Bun v1.0.21-canary.55 (837cbd60) Windows x64
UpgradeCommand:
Elapsed: 11309ms | User: 2250ms | Sys: 3343ms
RSS: 89.02MB | Peak: 111.56MB | Commit: 0.15GB | Faults: 34118
----- bun meta -----

0   00007FF73CF82268
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 6364 panic: invalid enum value
???:?:?: 0x7ff73bebd5dd in ??? (???)
???:?:?: 0x7ff73bebdd47 in ??? (???)
???:?:?: 0x7ff73becddbf in ??? (???)
???:?:?: 0x7ff73bd01492 in ??? (???)
???:?:?: 0x7ff73deae18f in ??? (???)
???:?:?: 0x7ffd4200257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffd435aaa57 in ??? (ntdll.dll)

**Comment by alekcunn** [comment]
note: I reinstalled using the current powershell script, and ran upgrade without issue. Current version reports 1.0.21-canary.16

**Comment by paperclover** [comment]
In Debug:

<img width="979" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/d01a5788-a8c3-4324-857a-3def845fb697">
