### ISSUE TITLE
issue with jsonwebtoken module

### ISSUE THREAD

**Issue by VenkataBhaskarr** [oven-sh/bun#7999]
### What version of Bun is running?

1.0.4+745b6b94e

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```
const jwt = require("jsonwebtoken")
app.post("/signup", (req, res) => {
  const {username, password} = req.body;
  const token = jwt.sign({ username, password }, "secret");
  res.json({message: "success", token});
})
```

### What is the expected behavior?

The same code is running via node index.js but while using bun index.js it is causing this error,

### What do you see instead?

TypeError: Right hand side of instanceof is not an object

### Additional information

<img width="1431" alt="Screenshot 2024-01-05 at 7 04 13 PM" src="https://github.com/oven-sh/bun/assets/111889155/44d58be2-a690-4fce-9e62-d192387e307c">

**Comment by Electroid** [comment]
Can you try running: bun upgrade? We may have fixed this a while ago

**Comment by VenkataBhaskarr** [comment]
Thank you.... it's working now!!
