### ISSUE TITLE
`file.stat()` is undefined in  bun `1.0.21`

### ISSUE THREAD

**Issue by GoWind** [oven-sh/bun#8002]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

create a file `measurements.txt` 
```
import {open } from 'node:fs/promises';

let globalMap = new Map();


const numWorkers = 12;

let doneCount = 0;


let workers = [];

let startTs = null;
let endTs = null;
async function runProgram() {
  startTs = process.hrtime.bigint();
  const file = await open("./measurements.txt");
  console.log(`${file}`);
  let stats = await file.stat();
}
runProgram();
```

### What is the expected behavior?

bun should be able to do a `stat` call on a Filehandle object and provide the stat data structure related to the file. 

### What do you see instead?

`file.stat()` errors out as undefined
```
18 |   console.log(`${file}`);
19 |   let stats = await file.stat();
                         ^
TypeError: file.stat is not a function. (In 'file.stat()', 'file.stat' is undefined)
``` 

### Additional information

The same code runs fine using `NodeJs`
```
node bunfile.mjs
[object Object]
```

**Comment by Electroid** [comment]
Duplicate of #3167

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/8141
