### ISSUE TITLE
[ffi] Segmentation fault passing String buffer as char*

### ISSUE THREAD

**Issue by borkdude** [oven-sh/bun#801]
### Version

0.1.5

### Platform

Darwin m1.fritz.box 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

``` javascript 
import { dlopen, suffix } from 'bun:ffi'

const { printw } = dlopen("libncurses."+suffix, {"printw": {"returns": "int", "args": ["char*"]}}).symbols

printw(Buffer.from("Hello"))
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Calling printw works.

### What do you see instead?

$ bun repro.mjs

SegmentationFault at 112

–––– bun meta ––––
Bun v0.1.5 macOS Silicon 21.5.0
AutoCommand:
Elapsed: 62ms | User: 8ms | Sys: 21ms
RSS: 19.23MB | Peak: 19.23MB | Commit: 67.11MB | Faults: 739
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

**Comment by sno2** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/769 which has been solved

**Comment by borkdude** [comment]
@sno2 I don't see how #769 is solved. See my repro. Even when I import `ptr` the example doesn't work. I might be doing it wrong, but it would be helpful if someone could correct my repro.

**Comment by sno2** [comment]
@borkdude It is solved on master, we still need to create a release.

**Comment by borkdude** [comment]
Gotcha, sorry I missed that.

**Comment by borkdude** [comment]
I tried again with 0.1.5. Now this repro causes a segmentation fault:

```
import { dlopen, suffix, ptr } from 'bun:ffi'

const { printw } = dlopen("libncurses."+suffix, {"printw": {"returns": "int", "args": ["char*"]}}).symbols

printw(Buffer.from("Hello"))
```

**Comment by sno2** [comment]
> 

I'm sorry, I don't know how I messed up but it seems I had misread your issue as being the same problem with our internal code not the buffer like in #769 .  The actual issue with your code is that we do not automatically append the null byte for you.  Therefore, you would need to adjust your code to append the null byte such that you can read the data as a C string.  Here are a few solutions:

```ts
// 1. Include the null byte in a string literal or via concatenation
const data = Buffer.from("Hey\0");
myFFIFunction(data);

// 2. Construct a Uint8Array and encode into it using a text encoder
const myString = "hey";
const data = new Uint8Array(myString.length + 1); // initializes with 0 so we already have the null byte
new TextEncoder().encodeInto(myString, data); // might want to assert the result
myFFIFunction(ptr(data));
```

Also note I cannot find any reference to the `char*` type you are using in `args`.  I advise you use `cstring` instead.

**Comment by borkdude** [comment]
I'm getting a segmentation fault here:

``` javascript
import { dlopen, suffix, ptr } from 'bun:ffi'

const { printw } = dlopen("libncurses."+suffix, {"printw": {"returns": "int", "args": ["char*"]}}).symbols

const myString = "hey";
const data = new Uint8Array(myString.length + 1); // initializes with 0 so we already have the null byte
new TextEncoder().encodeInto(myString, data); // might want to assert the result
printw(ptr(data));
```

Also when I change `char*` to `cstring`.

**Comment by borkdude** [comment]
I think it was my bad usage of the library. This works:

``` javascript
import { dlopen, suffix, ptr, CString, FFIType } from 'bun:ffi'

const { printw, initscr, refresh }
      = dlopen("libncurses."+suffix,
               {"printw": {"returns": "int", "args": ["ptr"]},
                "initscr": {"returns": "int", "args": []},
                "refresh": {"returns": "int", "args": []}}).symbols

const myString = "hey";
var arr = new TextEncoder().encode(myString + "\0");
console.log(arr)

initscr();
printw(ptr(arr));
refresh();
```

So first calling initscr helped.
