### ISSUE TITLE
Implement a `junit` reporter for `bun test`

### ISSUE THREAD

**Issue by NateRadebaugh** [oven-sh/bun#8019]
### What is the problem this feature would solve?

For jest parity and integration with Azure DevOps test reporting, we need to be able publish test results as `junit.xml`

### What is the feature you are proposing to solve the problem?

The JUnit XML file format has been made popular by the JUnit project and has since become the de facto standard format to exchange test results between tools.

**Comment by Haratsu** [comment]
Would also appreciate this, for the same reason: 
Also getting some coverage report that can be used in CI systems to upload Btw here is that questionn just regarding LCOV #4015 

Maybe there should be some general feature / epic for most used formats:

Test reports:
- [*] junit
- [*] surefire

Coverage Reports:
- [*] jacoco
- [*] cobertura
- [*] lcov
- ncover

Btw supporting any of those marked with [*] will enable converting reports to other useful formats without loosing information

**Comment by jd-apprentice** [comment]
I'm okay with junit and cobertura at least, if someone is doing anything about it and needs help send me a message and I try to help!

**Comment by owenizedd** [comment]
Agree at least should have junit and cobertura, right now we have lcov but Gitlab doesn't support it.
I'd also like to help

**Comment by KholdStare** [comment]
Chiming in - We want to migrate to `bun` from `yarn` + `node` + `jest`, and have some infrastructure already set up in CI for test reports, that rely on junit output. This would greatly simplify our migration.

**Comment by itsjavi** [comment]
This is the only thing missing to replace testing libraries with bun in some workflows like Gitlab's, which only supports the JUnit format for Unit test reports.

**Comment by itsjavi** [comment]
thanks a lot to @Jarred-Sumner for implementing this! 🚀❤️
