### ISSUE TITLE
`bun install --production` still installs devDependencies of packages in the workspace

### ISSUE THREAD

**Issue by sylv** [oven-sh/bun#8033]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a workspace that contains a package with `devDependencies`, then `bun install --production`. The dev dependency is installed.

Or `bun install --production` in [this repo](https://github.com/sylv/bun-workspace-install-prod-bug) which installs `devDependencies` and `dependencies` of `packages/poggers-package`. 

### What is the expected behavior?

It should only install `dependencies`. `devDependencies` should be ignored.

### What do you see instead?

`devDependencies` is not ignored for workspace packages, only the root package respects `--production`.

### Additional information

This almost certainly isn't a related bug but `bun add` seems to break the lockfile (?) and `bun install --force` in the root is necessary before `bun install --production` works, otherwise it complains about `lockfile had changes, but lockfile is frozen`. 

~~The suffering is worth it for native typescript support and macros 🤤~~

**Comment by Patrick-Ullrich** [comment]
Is this a duplicate of https://github.com/oven-sh/bun/issues/7969?

**Comment by sylv** [comment]
Yuuuup, I'm pretty sure it is 🙃
