### ISSUE TITLE
Module '"bun:sqlite"' has no exported member 'SQLiteError'.

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8041]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 6.1.66-1-lts x86_64 unknown

### What steps can reproduce the bug?

```ts
import { SQLiteError } from "bun:sqlite";
```

### What is the expected behavior?

There should be types for `SQLiteError`

### What do you see instead?

```
Module '"bun:sqlite"' has no exported member 'SQLiteError'. Did you mean to use 'import SQLiteError from "bun:sqlite"' instead?ts(2614)
```

**Comment by paperclover** [comment]
this is a type defintions bug

**Comment by huseeiin** [comment]
> this is a type defintions bug

yup

**Comment by huseeiin** [comment]
its fixed. tho https://github.com/oven-sh/bun/issues/8107
