### ISSUE TITLE
Cannot declare an imported binding name twice: 'Fragment'

### ISSUE THREAD

**Issue by benmerckx** [oven-sh/bun#8043]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Darwin 22.1.0 arm64 ar

### What steps can reproduce the bug?

The following will error at build time

````jsx

import {Fragment} from 'react'
console.log({explicit: Fragment})
console.log(<>Implicit Fragment</>)
````

With this error:

````
1 | import {Fragment} from 'react'
    ^
SyntaxError: Cannot declare an imported binding name twice: 'Fragment'.
      at <parse> (.../err.jsx:1:1)
````

Note that any import named Fragment will trigger this when there's <></> shorthand in the file, not just "the" Fragment from the react package.

**Comment by kjetilod** [comment]
Duplicate of #7576?

**Comment by benmerckx** [comment]
Yeah
