### ISSUE TITLE
windows: bunx / bun create is not implemented

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#8045]
Hello , I have this problem when I create a project next js
bun create-next-app or bunx create-next-app@Latest

![ssss.png](https://cdn.discordapp.com/attachments/1193952433186033694/1193952433467048077/ssss.png?ex=65ae95da&is=659c20da&hm=5ac8cb0794e185adc5af474a8a0193cdc62422fa6ec2a47d1867c520657e9be4&)

![ddddddddddddddddddddddddddd.png](https://cdn.discordapp.com/attachments/1193952433186033694/1193952434175881216/ddddddddddddddddddddddddddd.png?ex=65ae95da&is=659c20da&hm=1bd766361190d0cd4d3f236ed0ac3d64cd44643b8091413cf534fc97fe9d1da9&)

_Originally reported on Discord: [`problem when creating Next js project with bun`](https://discord.com/channels/876711213126520882/1193952433186033694/1193952433186033694)_

**Comment by paperclover** [comment]
this is a duplicate of the TODO: bun for windows isn't implemented
