### ISSUE TITLE
[1]    14506 illegal hardware instruction (core dumped)  ./bun

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#805]
### Version

Bun v0.1.4

### Platform

Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

When I executed bun from the  binary file or  the download script.

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Execute bun?

### What do you see instead?

```
❯ ./bun
[1]    14506 illegal hardware instruction (core dumped)  ./bun
```

**Comment by FrameMuse** [comment]
I guess you need to give some more information about this like `logs`

**Comment by bokunodev** [comment]
i want to try bun. but i faced the same problem.
@FrameMuse where bun write logs? it crash before doing anything.

**Comment by bokunodev** [comment]
the original issue is here https://github.com/oven-sh/bun/issues/777 i think it should be kept open. for note for future developer who want to try bun.

**Comment by FinnRG** [comment]
@bokunodev This is a duplicate of #67. Experience shows, that even with already open issues, people will just create new ones. I will close this for now.

**Comment by ghost** [comment]
What I could do?
