### ISSUE TITLE
`bun install` fails to install `zod` properly, mangles imports.

### ISSUE THREAD

**Issue by svaterlaus** [oven-sh/bun#8051]
### What version of Bun is running?

1.0.21

### What platform is your computer?

Linux 6.6.6-76060606-generic x86_64 x86_64

### What steps can reproduce the bug?

When `zod` is installed via `bun install` in a monorepo, somehow `node_modules/zod/index.d.ts` gets mangled as such:

```
export * from "zod/libibib";
export as namespace Zod;
```

`zod/libibib` does not exist and causes importing `zod` to fail. It should be `zod/lib`, which is what it is when I run `npm install` instead of `bun install`.

This can be reproduced with a minimal monorepo setup. Just one package with the following `package.json` files:

`package.json`
```
{
  "name": "bun-bug",
  "type": "module",
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
```

`packages/example-workspace`
```
{
  "name": "example-workspace",
  "type": "module",
  "private": true,
  "main": "src/index.ts",
  "dependencies": {
    "zod": "^3.22.4"
  }
}
```

### What is the expected behavior?

After running `bun install`, `node_modules/zod/index.d.ts` should be this:

```
export * from "zod/lib";
export as namespace Zod;
```

### What do you see instead?

After running `bun install`, `node_modules/zod/index.d.ts` is this:

```
export * from "zod/libibib";
export as namespace Zod;
```

**Comment by Jarred-Sumner** [comment]
`bun install` uses hardlinks by default on Linux

So if you modify the file locally, it would modify it in the cache as well which would cause something like this to happen

is it possible you or a tool added `ibib` at the end of the import path in the cached version?

If you clear the cache locally `rm -rf ~/.bun/install/cache` and then `rm -rf node_modules` and then `bun install`, does it reproduce?

**Comment by svaterlaus** [comment]
Yeah, was just about to comment that clearing the cache with `bun pm cache rm` fixed it. Not sure how it happened, but I'll close this out.

Thanks!
