### ISSUE TITLE
node-canvas NAPI crash after multiple calls

### ISSUE THREAD

**Issue by 7f8ddd** [oven-sh/bun#8055]
### What version of Bun is running?

1.0.21+88fcfa446

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?
You will need to install the dependencies required to build it listed at https://github.com/Automattic/node-canvas .

bun i git+https://github.com/Automattic/node-canvas.git
(or use npm i --build-from-source in the directory)

```
import { createCanvas } from "canvas";

for (let i = 0; i < 25; i++) {
  const canvas = createCanvas(400, 400);
  const ctx = canvas.getContext("2d");
  console.log(canvas.toDataURL())
}
```

### What is the expected behavior?

25 empty images should be printed to the console.

### What do you see instead?

```
A few images work just fine, then:

napi: napi_define_properties
  Error::Error

uh-oh: napi: napi_define_properties
  Error::Error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.21 (88fcfa44) Linux x64 #1 SMP Thu Oct 5 21:02:42 UTC 2023
RunCommand: dotenv 
Elapsed: 2596ms | User: 219ms | Sys: 31ms
RSS: 83.98MB | Peak: 0.15GB | Commit: 83.98MB | Faults: 0
----- bun meta -----

0   0x55b372af678b
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ??? napi_fatal_error
8   ???
9   ??? Napi::Error::Error(napi_env__*, napi_value__*)
10  ??? Napi::ObjectWrap<Context2d>::ConstructorCallbackWrapper(napi_env__*, napi_callback_info__*)
```

### Additional information
I am almost certain it was working previously.

**Comment by Electroid** [comment]
Related to #5835

**Comment by 7f8ddd** [comment]
> Related to #5835

That issue was resolved, they just haven't updated the package version in a year, so you have to manually build it. It works fine unless you call it too many times.

**Comment by n1ckoates** [comment]
Is there a workaround for this issue right now? Running into this issue when multiple users run a Discord bot command that uses `node-canvas`. `@napi-rs/canvas` is incompatible with Bun also, so there isn't a working Canvas implementation afaik.

**Comment by Jarred-Sumner** [comment]
> Is there a workaround for this issue right now? Running into this issue when multiple users run a Discord bot command that uses `node-canvas`. `@napi-rs/canvas` is incompatible with Bun also, so there isn't a working Canvas implementation afaik.

What's the issue with `@napi-rs/canvas`?

**Comment by n1ckoates** [comment]
> What's the issue with `@napi-rs/canvas`?

I should've been more clear, it's an issue with installing it right now: #7617

edit: though now that I test it with latest Bun, `@napi-rs/canvas` seems to install fine.

**Comment by Jarred-Sumner** [comment]
No longer reproduces as of Bun v1.1.20.
