### ISSUE TITLE
Bun install error

### ISSUE THREAD

**Issue by kingcwt** [oven-sh/bun#8059]
### What version of Bun is running?

 bun --revision 1.0.18+36c316a24

### What platform is your computer?

FROM oven/bun:latest

### What steps can reproduce the bug?

<img width="537" alt="image" src="https://github.com/oven-sh/bun/assets/29888469/8e04c233-9dc4-448f-9517-e583977cc51d">
<img width="1455" alt="image" src="https://github.com/oven-sh/bun/assets/29888469/50fc90d7-828c-4116-abf4-b69e5e82d0e1">

### What is the expected behavior?

```json
{
  "name": "vue-templete",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "bunx --bun vite --config ./project/vite.config.ts --host --mode NODE_ENV=dev",
    "dev:dcp": "vite --config ./project-dcp/vite.config.ts --host --mode NODE_ENV=dev",
    "dcp": "vite --config ./project-dcp/vite.config.ts --host --mode NODE_ENV=dev",
    "dcp-test": "vite --config ./project-dcp/vite.config.ts --host --mode NODE_ENV=test",
    "build": "vite build --config ./project/vite.config.ts --mode NODE_ENV=pro --emptyOutDir",
    "build:dcp": "vite build --config ./project-dcp/vite.config.ts --mode NODE_ENV=pro --emptyOutDir",
    "preview": "vite preview",
    "prettier": "prettier -c --write **/*",
    "lint": "eslint ./project/src --fix --ext .js,.ts,.jsx,.tsx,.vue",
    "prepare": "husky install",
    "pre-commit": "npx husky add .husky/pre-commit"
  },
  "husky": {
    "hooks": {
      "applypatch-msg": "echo \"[Husky] applypatch-msg\"",
      "pre-applypatch": "echo \"[Husky] pre-applypatch\"",
      "post-applypatch": "echo \"[Husky] post-applypatch\"",
      "pre-commit": "echo \"[Husky] pre-commit\""
    }
  },
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "ant-design-vue": "^4.0.0-rc.6",
    "axios-https": "^1.0.2",
    "color": "^4.2.3",
    "ilibs": "^1.0.10",
    "jss": "^10.10.0",
    "jss-plugin-camel-case": "^10.10.0",
    "jss-preset-default": "^10.10.0",
    "lodash": "^4.17.21",
    "quill": "2.0.0-dev.4",
    "vue": "^3.3.4",
    "vue-clipboard3": "^2.0.0",
    "vue-i18n": "9",
    "vue-only-office": "^1.0.0",
    "vue-router": "^4.2.4",
    "xmldom": "^0.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@babel/eslint-parser": "^7.22.9",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/preset-env": "^7.22.9",
    "@babel/preset-typescript": "^7.22.5",
    "@types/jest": "^29.5.3",
    "@types/lodash": "^4.14.196",
    "@types/node": "^20.4.5",
    "@types/quill": "^2.0.11",
    "@types/xmldom": "^0.1.32",
    "@typescript-eslint/eslint-plugin": "^5.19.0",
    "@typescript-eslint/parser": "^5.19.0",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/test-utils": "^2.4.1",
    "ambiences": "^1.2.26",
    "eslint": "^8.13.0",
    "eslint-config-alloy": "^5.1.0",
    "eslint-config-prettier": "^8.9.0",
    "eslint-define-config": "^1.22.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-vue": "^9.16.1",
    "husky": "^8.0.3",
    "mockjs": "^1.1.0",
    "prettier": "^3.0.0",
    "rollup-plugin-external-globals": "^0.9.0",
    "rollup-plugin-visualizer": "^5.9.2",
    "terser": "^5.19.2",
    "ts-loader": "^9.4.4",
    "typescript": "^5.1.6",
    "unplugin-vue-components": "^0.25.1",
    "vite": "^4.4.5",
    "vite-plugin-html": "^3.2.0",
    "vite-plugin-imagemin": "^0.6.1",
    "vite-plugin-mock": "^2.9.6",
    "vue-tsc": "^1.8.6",
    "vue3-jest": "^27.0.0-alpha.1"
  }
}
```

这是我的package.json 文件

### Additional information

Please help me solve the problem

**Comment by AbhinavMir** [comment]
Kinda hacky, but does `RUN bun install --skip-ts-errors` help? I'm guessing it's because `isNaturalNumber` is either defined as an instance of some module.

**Comment by kingcwt** [comment]
I have installed system dependencies to solve this problem, but I feel that this is not the best solution. And I don't have enough time now to study

You can make a copy of the package.json file I provided above and use it https://bun.sh/guides/ecosystem/docker According to the reference I provided above, you only need to copy my package.json and execute bun iinstall to find the specific problem with this dockerfile. I hope the big shot can help me take a look.

---
This is currently my dumbest way to solve it. I hope there can be a better way, please
FROM oven/bun:1 as base
WORKDIR /app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb bunfig.toml /temp/dev/
ENV PATH="/usr/bin/git:${PATH}"
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN apt-get update && apt-get install -y \
    libc6 \
    libgcc1 \
    libstdc++6 \
    zlib1g \
    libpng16-16 \
    libjpeg62-turbo \
    libgif7 \
    libglib2.0-0 \
    autoconf \
    automake \
    libtool \
    nasm \
    build-essential \
    file \
    nodejs
# RUN apt-get update && apt-get install -y \
#     libc6 \
#     zlib1g \
#     libglib2.0-0 \
#     autoconf \
#     automake \
#     libtool \
#     nasm \
#     build-essential \
#     file \
#     nodejs

# RUN apt-get update && apt-get install -y \
#     nodejs \
#     file \
#     libc6

RUN cd /temp/dev && bun install

RUN apt-get install -y git

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

RUN bun run build
CMD cp -r /app/dist /test

**Comment by kingcwt** [comment]
<img width="681" alt="image" src="https://github.com/oven-sh/bun/assets/29888469/ec796d5d-9eb6-41a1-960e-6b02d2f486c5">
This is my current clumsy method to solve it. I hope you can copy a copy of my package.json file and try the bun install command in the Dockerfile file, and you will find the problem

**Comment by kingcwt** [comment]
I hope there is a better solution. If possible, I hope you can help me take a look.

**Comment by kingcwt** [comment]
Indeed, currently there are many compatibility issues with bun that cannot completely replace nodes. I hope it will improve in the future. I have already resolved this issue through pnpm. I won't tinker with bun for now. thanks
