### ISSUE TITLE
inconsistent behavior when executing  setTimeout 

### ISSUE THREAD

**Issue by shripada** [oven-sh/bun#806]
### Version

0.1.4

### Platform

Darwin shripadas-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Please check the sample repo:
https://github.com/shripada/bun-settimeout

All it contains is a simple node project with one file called [`timeout.mjs`](https://github.com/shripada/bun-settimeout/blob/37c04eda2115549d5b1f107405d6d19a28220ab9/timeout.mjs) containing just these lines:
```
setTimeout(() => console.log("I am called after 6 secs"), 6000);
setTimeout(() => console.log("I am called after 4 secs"), 4000);
console.log("I am called first in this async world!");
```

Observe the output from `bun` and then `node`.  `node` is running it right while `bun` seems to miss the 6 sec timeout altogether!:

```
❯ bun run timeout.mjs
I am called first in this async world!
I am called after 4 secs

❯ node timeout.mjs
I am called first in this async world!
I am called after 4 secs
I am called after 6 secs
```

### How often does it reproduce? Is there a required condition?

Always gets reproduced. No special conditions.

### What is the expected behavior?

In this case, it should have correctly executed both setTimeout calls and should have outputed:

```
I am called first in this async world!
I am called after 4 secs
I am called after 6 secs
```

### What do you see instead?

```
I am called first in this async world!
I am called after 4 secs
```

### Additional information

node works correctly and outputs the expected:

```
I am called first in this async world!
I am called after 4 secs
I am called after 6 secs
```

**Comment by Jarred-Sumner** [comment]
This is a bug
