### ISSUE TITLE
mssql throwing "socket must be an instance of net.Socket on attempted connection

### ISSUE THREAD

**Issue by ReeceXW** [oven-sh/bun#8066]
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Initialize a bun project, install mssql, use a basic example like the following:

```
import * as mssql from "mssql";

await mssql.connect({
    server: "...",
    user: "...",
    password: "...",
    database: "..."
});
```

### What is the expected behavior?

Some sort of success/error response from the database.

### What do you see instead?

A connection error

> socket must be an instance of net.Socket, code: "ESOCKET"

### Additional information

This works running under Node

**Comment by Electroid** [comment]
Duplicate of #5147

**Comment by ReeceXW** [comment]
> Duplicate of #5147

You've closed this because of an open issue that was totally ignored? A major issue that needs to be addressed

**Comment by Electroid** [comment]
> > Duplicate of #5147
> 
> You've closed this because of an open issue that was totally ignored? A major issue that needs to be addressed

@ReeceXW It's helpful to close duplicate issues so the context on a particular bug is in one place. That said, I can understand the frustration that this bug has still not been fixed, but indeed we will fix this.
