### ISSUE TITLE
Error: postinstall script from "@prisma/engines" when next.js app deploy in vercel

### ISSUE THREAD

**Issue by igmtink** [oven-sh/bun#8080]
### What version of Bun is running?

1.0.22+b400b36ca

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I added a postinstall script for "prisma generate" and deploy it in vercel.

"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate"
  }

And it's failing to deploy my nextjs project in vercel.

### What is the expected behavior?

I am expecting my nextjs project to be successful when deployed on Vercel.

### What do you see instead?

Error: Cannot find module '/vercel/path0/scripts/postinstall.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
  
error: postinstall script from "@prisma/engines" exited with 1
Error: Command "bun install" exited with 1

**Comment by Electroid** [comment]
Can you check which version of bun is running in your Vercel build step? (you can add do something like: (bun -v && bun run build)

**Comment by igmtink** [comment]
> Can you check which version of bun is running in your Vercel build step? (you can add do something like: (bun -v && bun run build)

where can I add that command in vercel?

**Comment by igmtink** [comment]
> Can you check which version of bun is running in your Vercel build step? (you can add do something like: (bun -v && bun run build)

![image](https://github.com/oven-sh/bun/assets/117252369/9a3d8248-718d-4545-819d-1219fe49021a)

**Comment by Electroid** [comment]
We pushed a fix for this in Bun v1.0.22. Vercel is updating their default version of Bun in their build runner.
