### ISSUE TITLE
Installed package missing vendored node_modules directory

### ISSUE THREAD

**Issue by jclem** [oven-sh/bun#8093]
### What version of Bun is running?

1.0.22

### What platform is your computer?

Linux 6.5.11-linuxkit aarch64 unknown

### What steps can reproduce the bug?

Install `@tanstack/router-vite-plugin@1.3.3`. The `node_modules` directory that is [vendored by this package](https://www.npmjs.com/package/@tanstack/router-vite-plugin/v/1.3.3?activeTab=code) will be missing. This does not happen on macOS (`Darwin 23.2.0 arm64 arm`).

### What is the expected behavior?

The vendored `node_modules` directory should not be removed, since this package relies on it being present (see line 15 in the package's `build/cjs/packages/router-cli/src/config.js` file).

### What do you see instead?

No `node_modules` directory at the specified path.

**Comment by eemelipa** [comment]
Here's minimal repro https://github.com/eemelipa/bun-issue-8093

Seems like bun install cache correctly has the `build/cjs/node_modules` in place but it isn't in place outside of the cache when installed.

**Comment by eemelipa** [comment]
Seems like running `bun install --backend copyfile` can be used as a workaround as it copies `node_modules` over correctly.

So the problem has something to do with the other backend methods, e.g., `hardlink`
