### ISSUE TITLE
Difference in `url.parse` between Node and Bun

### ISSUE THREAD

**Issue by silvio2402** [oven-sh/bun#8098]
### What version of Bun is running?

1.0.22+b400b36ca

### What platform is your computer?

Linux 5.15.90.4-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Parse an URL consisting of only the scheme in Bun:
```js
const url = require("url");

console.log(url.parse("http://"));
```

### What is the expected behavior?

I expect to be able to parse the scheme like in Node where the output is this:
```txt
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '',
  port: null,
  hostname: '',
  hash: null,
  search: null,
  query: null,
  pathname: null,
  path: null,
  href: 'http://'
}
```

### What do you see instead?

I get a TypeError:
```txt
1 | const url = require("url");
2 | 
3 | console.log(url.parse("http://"));
                ^
TypeError: "http://" cannot be parsed as a URL.
      at node:url:56:61
      at node:url:4:45
      at /workspaces/pfadimh-site/test.js:3:13
```

### Additional information

I am aware that the `url.parse` function is deprecated, however it would be beneficial if it behaved equally as in Node for backwards-compatibility.

**Comment by Electroid** [comment]
It's recommended to use `new URL`, but regardless this is a bug we'll fix.

**Comment by paperclover** [comment]
for someone looking to fix this, it is an issue in the node:url polyfill, located at `src/js/node/url.js`.
