### ISSUE TITLE
Log indentation missing when using console.group

### ISSUE THREAD

**Issue by verheyenkoen** [oven-sh/bun#8099]
### What version of Bun is running?

1.0.22+b400b36ca

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Create a script `index.js` with contents:
```js
console.log('Level 0')
console.group('Starting level 1')
console.log('Level 1')
console.group('Starting level 2')
console.log('Level 2')
console.groupEnd()
console.log('Back to level 1')
console.groupEnd()
console.log('Back to level 0')
```

Execute it with bun:

```sh
$ bun run index.js
```

or

```sh
$ bun .
```

### What is the expected behavior?

The output should be indented (as with Node.js):

```
Level 0
Starting level 1
  Level 1
  Starting level 2
    Level 2
  Back to level 1
Back to level 0
```

### What do you see instead?

```
Level 0
Starting level 1
Level 1
Starting level 2
Level 2
Back to level 1
Back to level 0
```

### Additional information

https://nodejs.org/docs/latest-v20.x/api/console.html#consolegrouplabel

**Comment by verheyenkoen** [comment]
I noticed it does work if you create a new Console using the `groupIndentation` option.

```js
// index.js
const c2 = new console.Console({
  stdout: process.stdout,
  stderr: process.stderr,
  groupIndentation: 6,
})

c2.log('Level 0')
c2.group('Starting level 1')
c2.log('Level 1')
c2.group('Starting level 2')
c2.log('Level 2')
c2.groupEnd()
c2.log('Back to level 1')
c2.groupEnd()
c2.log('Back to level 0')
```

```sh
$ bun .
Level 0
Starting level 1
      Level 1
      Starting level 2
            Level 2
      Back to level 1
Back to level 0
```

**Comment by zhong-yiyu** [comment]
I suggest putting this feature on bun's documents' website. Since the [page](https://bun.sh/docs/api/console) mentions:
> Bun provides a browser- and Node.js-compatible [console](https://developer.mozilla.org/en-US/docs/Web/API/console) global.
It'll be great for new users to get familiar with this "quirk" of Bun. 😉

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/oven-sh/bun/pull/15026

This will be part of the Bun v1.1.35 release
