### ISSUE TITLE
Support `github:` dependencies

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#81]

**Comment by Mouvedia** [comment]
One thing that is quite useful is `foo/bar#qux`.
e.g. [`Jarred-Sumner/bun#bun-actions`](https://github.com/Jarred-Sumner/bun/tree/bun-actions)

**Comment by Jarred-Sumner** [comment]
@dylan-conway is working on this.

**Comment by Electroid** [comment]
This was supported several releases ago: https://github.com/oven-sh/bun/pull/1875

**Comment by Mouvedia** [comment]
#1875
