### ISSUE TITLE
node:crypto { randomInt } cause error in bun build

### ISSUE THREAD

**Issue by Ray-D-Song** [oven-sh/bun#8117]
### What version of Bun is running?

1.0.22

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

bun build main.ts

### What is the expected behavior?

build success

### What do you see instead?

1 | import { randomInt } from 'crypto'
             ^
error: No matching export in "node:crypto" for import "randomInt"
    at /Users/ray-d-song/temp/randomInt/main.ts:1:10

### Additional information
`bun run` and `bun build --compile` works, only bun build throw err.
case:
https://github.com/Ray-D-Song/randomInt-bun-err-case

**Comment by huseeiin** [comment]
this is because `bun build` targets the browser by default which doesn't have node builtin modules. you can target bun or node with `bun build main.ts --target bun` or `bun build main.ts --target node`
