### ISSUE TITLE
Support `import.meta.filename` and `import.meta.dirname`

### ISSUE THREAD

**Issue by TomasHubelbauer** [oven-sh/bun#8122]
### What is the problem this feature would solve?

Node compatibility: https://github.com/nodejs/node/pull/48740

### What is the feature you are proposing to solve the problem?

Implement these and possibly even do it the same way: https://github.com/nodejs/node/pull/48740/files#diff-f572ecdefdbdf69b7fc591988665845843bc791a39d116607e27928089f54ed6

### What alternatives have you considered?

Not doing it, but these are super handy and I am sure will see quick adoption in the Node land so this will future-proof Node compat.

**Comment by TiBianMod** [comment]
there is a open PR https://github.com/oven-sh/bun/pull/7787

**Comment by TomasHubelbauer** [comment]
Thanks! I searched through the issues but not the PRs, sorry.
