### ISSUE TITLE
Unicode's characters disappear in strings

### ISSUE THREAD

**Issue by FelipeSharkao** [oven-sh/bun#813]
### Version

0.1.4

### Platform

```
Linux Felipe-Lenovo 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### What steps will reproduce the bug?

```js
console.log('(å)')
console.log({ unicode: '(å)' })
```

### How often does it reproduce? Is there a required condition?

The problem occurs every time there is a Unicode character in a string, both JS and TS. I have not tested the behavior of Unicode characters elsewhere.

### What is the expected behavior?

```
(å)
{ unicode: "(\u00E5)" }
```

### What do you see instead?

```
()
{ unicode: "(\u0000" }
```

**Comment by Jarred-Sumner** [comment]
This should be fixed, please re-open if it isn't
