### ISSUE TITLE
Error building devcontainer

### ISSUE THREAD

**Issue by shanejohnpaul** [oven-sh/bun#814]
I followed [VSCode Dev Container (Linux)](https://github.com/oven-sh/bun#vscode-dev-container-linux) to build the devcontainer but got stuck in this issue

```
#0 35.53 ./src/Server.zig:1990:47: error: container 'std.fs' has no member called 'openIterableDirAbsolute'
#0 35.53                 var document_dir_path = std.fs.openIterableDirAbsolute(std.fs.path.dirname(document_path) orelse break :fsc, .{}) catch break :fsc;
#0 35.53                                               ^
#0 35.62 zls...The following command exited with error code 1:
#0 35.62 /build/zig/zig build-exe /home/ubuntu/zls/src/Server.zig -OReleaseFast --cache-dir /home/ubuntu/zls/zig-cache --global-cache-dir /root/.cache/zig --name zls --pkg-begin build_options /home/ubuntu/zls/zig-cache/options/ZN5T5qs__MtT8K02r_1S-BHCIQm36qquqqxMkxJvDpZqrwQ-wS_m2895sSwEs1B_ --pkg-end --pkg-begin known-folders /home/ubuntu/zls/src/known-folders/known-folders.zig --pkg-end --enable-cache 
#0 35.62 error: the following build command failed with exit code 1:
#0 35.62 /home/ubuntu/zls/zig-cache/o/e595d78e6f2693e135c4b6b18d9b5f8d/build /build/zig/zig /home/ubuntu/zls /home/ubuntu/zls/zig-cache /root/.cache/zig -Drelease-fast
------
error: failed to solve: executor failed running [/bin/sh -c mkdir -p /home/ubuntu/.bun /home/ubuntu/.config $GITHUB_WORKSPACE/bun &&     bash /scripts/common-debian.sh &&     bash /scripts/github.sh &&     bash /scripts/nice.sh &&     bash /scripts/zig-env.sh]: exit code: 1
[39411 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/shane/bun/Dockerfile -t vsc-bun-fed96b9df3111f4d91bd4cfad3a6a73a --target bun.devcontainer --cache-from bun.devcontainer:latest /home/shane/bun
[39412 ms]     at buildAndExtendImage (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20763:11)
[39412 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[39412 ms]     at async buildNamedImageAndExtend (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20656:12)
[39412 ms]     at async doBuild (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:21399:36)
[39412 ms]     at async build (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:21329:18)
[39415 ms] Exit code 1

```

I checked the zig docs and wasn't able to find `openIterableDirAbsolute` in `std.fs`. This was a recent change made to the zls repo.

<br/>
<br/>

I was able to successfully build the devcontainer after checking out the previous commit which did not use this function, by modifying `.devcontainer/scripts/zig-env.sh`
```
#!/bin/bash

curl -L https://github.com/Jarred-Sumner/vscode-zig/releases/download/fork-v1/zig-0.2.5.vsix >/home/ubuntu/vscode-zig.vsix
git clone https://github.com/zigtools/zls /home/ubuntu/zls
cd /home/ubuntu/zls
git checkout 410a2dd6ddc44e598847fdbef2a4ae3d5e2ca5fc
git submodule update --init --recursive --progress --depth=1
zig build -Drelease-fast
```
I'm not sure if this is the way to resolve this issue.

**Comment by shanejohnpaul** [comment]
#743 Could be related to this issue as well.

**Comment by ram1660** [comment]
Same here. I couldn't figure out the problem.

**Comment by shanejohnpaul** [comment]
Did you try adding that `git checkout` line in that script? Doing that worked for me.

**Comment by ram1660** [comment]
After starting the clone all over again, it did the trick. Thank you!

**Comment by Omer-Shahar** [comment]
Hi, just happened to face this issue too.
Changing the `.devcontainer/scripts/zig-env.sh` file as mentioned did enable me to build the devcontainer.
However, I got stuck again later on in the process, and came back to [this error](https://github.com/oven-sh/bun/issues/741).
I think the problem occurs because the definition of `make devcontainer` should be fixed in Makefile, as I described [here](https://github.com/oven-sh/bun/issues/784) (but I really don't know, just my guess).
If you know a way to solve this, it would be great!

**Comment by shanejohnpaul** [comment]
> Hi, just happened to face this issue too. Changing the `.devcontainer/scripts/zig-env.sh` file as mentioned did enable me to build the devcontainer. However, I got stuck again later on in the process, and came back to [this error](https://github.com/oven-sh/bun/issues/741). I think the problem occurs because the definition of `make devcontainer` should be fixed in Makefile, as I described [here](https://github.com/oven-sh/bun/issues/784) (but I really don't know, just my guess). If you know a way to solve this, it would be great!

Oh. I haven't gone that far. I'll try it and check.

**Comment by hyuzea** [comment]
Bun master uses [forked zls](/oven-sh/zls) now

**Comment by shanejohnpaul** [comment]
Now it shows a message that I need 16GB of memory, but 12GB is all I've got for my docker installation. I guess I can't develop bun on my system.
