### ISSUE TITLE
Bun hangs if console.log is called while inspecting a Set or Map

### ISSUE THREAD

**Issue by chocolateboy** [oven-sh/bun#8153]
### What version of Bun is running?

1.0.22

### What platform is your computer?

Linux x86_64 (Arch)

### What steps can reproduce the bug?

```javascript
class MyMap extends Map {
    get size () {
        console.log('inside size')
        return 0
    }
}

const map = new MyMap()

console.log('size:', map.size) // OK
console.log('map:', map)       // XXX hangs
```

### What is the expected behavior?

```
inside size
size: 0
inside size
map: Map {}
```

### What do you see instead?

```
inside size
size: 0
// hangs
```

### Additional information

Same issue with Set.

Same issue if `console.debug` or `console.dir` are called, but not `console.warn`, `console.error`, or `process.stdout.write`.

No issue if `console.warn` is used to dump the Map/Set:

```javascript
const map = new MyMap()

console.log('size:', map.size) // OK
console.warn('map:', map)      // OK
```

**Comment by Jarred-Sumner** [comment]
I believe this is caused by a mutex

**Comment by paperclover** [comment]
you can cause this by logging inside of a custom inspect function too
