### ISSUE TITLE
Bug: `bun --watch` exits on failure when it shouldn't

### ISSUE THREAD

**Issue by EvHaus** [oven-sh/bun#8172]
### What is the problem this feature would solve?

When using `bun --watch` it would be nice if the watcher could continue waiting for changes if a failure occurs.

### What is the feature you are proposing to solve the problem?

When I'm writing code I like to run `bun --watch myscript.js` so I can immediately see changes as I make them with my script. However, sometimes I make mistakes in my code which causes it to throw an error. If an error is thrown, Bun will stop watching the file for changes and exit, requiring me to restart the `bun --watch` command again. This is annoying from a DX perspective.

It would be great if Bun could continue watching the file for changes and re-run it again, even if it still throws an error.

**Comment by Jarred-Sumner** [comment]
It is not supposed to exit. It didn’t used to

This is a bug

**Comment by EvHaus** [comment]
Seems to be working as expected in Bun 1.0.24. Closing.
