### ISSUE TITLE
@astrojs/upgrade package errored using bun

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8174]
### What version of Bun is running?

1.0.22+b400b36ca

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Run `bunx @astrojs/upgrade` in a Astro project

### What is the expected behavior?

Updates packages

### What do you see instead?

`error: could not determine executable to run for package @astrojs/upgrade`

**Comment by whitersun** [comment]
try bun x @astrojs/upgrade (this worked for me)
cause of bunx not something wrong syntax I guess...
