### ISSUE TITLE
EPOLL fallback on memlock issue

### ISSUE THREAD

**Issue by Milo123459** [oven-sh/bun#818]

**Comment by xhyrom** [comment]
If you want to report something, use bug template

**Comment by Milo123459** [comment]
Jarred just told me to make this issue, this isn't really a bug report, more a solution to a bug.

**Comment by Milo123459** [comment]
Jarred just told me to make this issue. This isn't really a bug report, more a solution to a bug.

**Comment by xhyrom** [comment]
Okay

**Comment by DeveloperHarris** [comment]
Interested in this as well! Would allow me to host bun applications on Railway using https://github.com/railwayapp/nixpacks

**Comment by Jarred-Sumner** [comment]
This isn't entirely fixed yet, but in the canary build of Bun `bun install` and `fetch` should at least partially work. There are cases where Bun is still using io_uring, but the HTTP client doesn't use it anymore

**Comment by Electroid** [comment]
Closing this for now. Tracking fallback for `io_uring` here: #785
