### ISSUE TITLE
Provide Single Executable Release For Windows

### ISSUE THREAD

**Issue by barziahmed** [oven-sh/bun#8181]
### What is the problem this feature would solve?

Hello,
Due to some technical reasons of mine, I need to use Bun as a single executable file, same as Deno providing [option for Windows users to download and use Deno as single executable file](https://github.com/denoland/deno/releases). 

### What is the feature you are proposing to solve the problem?

Please consider merging bun.exe and bunx.exe into one bun.exe executable file and provide it as an option to download alongside Releases page of Bun, same way as Deno does.

**Comment by paperclover** [comment]
it is already a single exe. they are hard links to each other when installed. you can access bunx by running `bun.exe x`, or by renaming or aliasing the exe so that it's filename is `bunx.exe`

**Comment by barziahmed** [comment]
@paperdave, So if I delete the bunx.exe I can still use bun.exe without any issues? And what about providing download option for executables in release page in github? alongside linux and macos zip packages...

**Comment by paperclover** [comment]
Bun for windows does not have a stable tag yet, so it is not available in github yet.

Please re-read the current message in the installation

> Bun provides a limited, experimental native build for Windows. It is recommended to use Bun within [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) and follow the above instructions. To help catch bugs, the experimental build enables many debugging assertions, which will make the binary slower than what the stable version will be.

>  WARNING: No stability is guaranteed on the experimental Windows builds
