### ISSUE TITLE
`bun install` hangs on Cloudflare pages

### ISSUE THREAD

**Issue by westmark** [oven-sh/bun#8184]
### What version of Bun is running?

1.0.22

### What platform is your computer?

Ubuntu 22.04.2 (on Cloudflare)

### What steps can reproduce the bug?

1. Create a barebones Next.js app in a Turbo monorepo
2. Configure for use in Cloudflare pages (https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/)
3. Deploy on Cloudflare

### What is the expected behavior?

`bun install --frozen-lockfile` should finish within a resonable amount of time.

### What do you see instead?

`bun install --frozen-lockfile` never finishes and the build itself times out.

### Additional information

Downgrading to `1.0.21` solved the issue. Running `1.0.22` on my local machine works as expected. Wish I could provide more info, but there is no additional output in the Cloudflare log.

**Comment by Jarred-Sumner** [comment]
@westmark can you pass `--verbose` to `bun install`?

**Comment by westmark** [comment]
@Jarred-Sumner Sorry, AFAIK Cloudflare does not allow editing the install command. 

Also, the downgrade fix was a fluke. Just had a failing deploy with `1.0.21`. Gonna see if I can get some help from Cloudflare support.

**Comment by westmark** [comment]
@Jarred-Sumner Would it be possible to add a `verbose` setting to `bunfig.toml` Or to be able to control it via env vars?

**Comment by westmark** [comment]
I think I fixed it. Noticed that some of my monorepo packages were referenced by other packages using the version string `"*"` instead of `"workspace:*"`. Since I fixed that I've had 3 deploys without a hickup. Closing this now
