### ISSUE TITLE
windows cannot run scripts if the environment contains invalid UTF-8

### ISSUE THREAD

**Issue by djkloop** [oven-sh/bun#8197]
### What version of Bun is running?

1.0.23-canary.48+407f42718

### What platform is your computer?

![image](https://github.com/oven-sh/bun/assets/21050914/5cb3a664-8621-4fa4-864f-95156f275a29)

### What steps can reproduce the bug?

 ```sh
 "scripts": {
    "serve": "node --max_old_space_size=10096 node_modules/@vue/cli-service/bin/vue-cli-service.js serve"
}
```
![image](https://github.com/oven-sh/bun/assets/21050914/f1118ed5-5b5f-4e64-9011-77303c35e422)

### What is the expected behavior?

normal operation

### What do you see instead?

error

**Comment by Jarred-Sumner** [comment]
strange

**Comment by paperclover** [comment]
i couldn't reproduce this easily with the package.json script alone.

**Comment by kafaa-dev** [comment]
getting this error too on version `1.0.25-canary.16+a8ff7be64`, I'm using the baseline build

**Comment by djkloop** [comment]
![image](https://github.com/oven-sh/bun/assets/21050914/e3dcaa83-75e8-4baa-a0c9-11f717a29b5d)


```sh
# https://nuxt.com/docs/getting-started/installation
# The default command for creating a new project using nuxt is also not working
```

**Comment by paperclover** [comment]
funny how this happens to starship prompt users
