### ISSUE TITLE
Desktop app using bun

### ISSUE THREAD

**Issue by elycheikhsmail** [oven-sh/bun#8205]
### What is the problem this feature would solve?

building desktop using bun. I don't see any thing about building desktop using bun in the bun, neither in bun roadmap. I don't know if is possible to dev desktop using bun and electronjs (or some part of electronjs), if this possible we just need a doc for it. Having possibility to build desktop using will make easy to adapt js+bun as first language to learn instead of python

### What is the feature you are proposing to solve the problem?

Building desktop app

### What alternatives have you considered?

Electronjs, tauri

**Comment by Electroid** [comment]
We are unlikely to develop our own Desktop framework. It would be great if one day Electron could run with Bun, but it is heavily tied to the implementation of V8, and that is unlikely.

What is more likely is someone in the community who wants to develop a new, faster Desktop app framework using Bun.

**Comment by elycheikhsmail** [comment]
I successfully to run electronjs using bun and https://electron-vite.org/guide/ I just replace npm by npm, I hope bun guide will include how to run electonjs using bun. I know bun team focusing on server apps but there are some use cases for desktop app also.
