### ISSUE TITLE
Bun compile Single-file executable how to specify platform?

### ISSUE THREAD

**Issue by fyapy** [oven-sh/bun#8211]
### What is the type of issue?

Documentation is missing

### What is the issue?

For example i execute command in MacOS `bun build ./index.ts --compile --outfile buncrypto`, but it is executable do not run on Ubuntu 22.04.

How can i specify platform for compilation?

For example:
Deno JS has `--target` flag https://docs.deno.com/runtime/manual/tools/compiler#cross-compilation

**Comment by Electroid** [comment]
Duplicate of #3473

**Comment by Electroid** [comment]
We don't have a way to cross-compile right now, though it's something we could support.
