### ISSUE TITLE
BunFile.slice() ignoring end parameter on macOS

### ISSUE THREAD

**Issue by tryggvil** [oven-sh/bun#8215]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

macOS

### What steps can reproduce the bug?

BunFile.slice does not handle end parameter correctly, on macOS.

```
const contents = "1234567890abcdefghijklmnokprstuvxyz"
const sliceEndSmallerThanFile = 11

const blb = new Blob([contents]);
const blbSlice = blb.slice(2, sliceEndSmallerThanFile);
const blActualContents = await blbSlice.text();
console.log("blob actualContents:", blActualContents);

await Bun.write("contents.txt", contents);

const fil = Bun.file("contents.txt");
const filSlice = fil.slice(2, sliceEndSmallerThanFile);
const filActualContents = await filSlice.text();
console.log("file actualContents:", filActualContents);
```

on macOS the output is:

```
blob actualContents: 34567890a
file actualContents: 34567890abcdefghijklmnokprstuvxyz
```

returning the whole file contents instead of the slice

### What is the expected behavior?

```
blob actualContents: 34567890a
file actualContents: 34567890a
```

### What do you see instead?

```
blob actualContents: 34567890a
file actualContents: 34567890abcdefghijklmnokprstuvxyz
```

**Comment by truongan07** [comment]
- Get text of file before slice it ?
```
const contents = "1234567890abcdefghijklmnokprstuvxyz"
const sliceEndSmallerThanFile = 11

const blb = new Blob([contents]);
const blbSlice = blb.slice(2, sliceEndSmallerThanFile);
const blActualContents = await blbSlice.text();
console.log("blob actualContents:", blActualContents);

await Bun.write("contents.txt", contents);

const fil = Bun.file("contents.txt");
const filActualContents = await fil.text();
const filSlice = filActualContents.slice(2, sliceEndSmallerThanFile);

console.log("file actualContents:", filSlice);
```

**Comment by tryggvil** [comment]
> * Get text of file before slice it ?
> 
> ```
> const contents = "1234567890abcdefghijklmnokprstuvxyz"
> const sliceEndSmallerThanFile = 11
> 
> const blb = new Blob([contents]);
> const blbSlice = blb.slice(2, sliceEndSmallerThanFile);
> const blActualContents = await blbSlice.text();
> console.log("blob actualContents:", blActualContents);
> 
> await Bun.write("contents.txt", contents);
> 
> const fil = Bun.file("contents.txt");
> const filActualContents = await fil.text();
> const filSlice = filActualContents.slice(2, sliceEndSmallerThanFile);
> 
> console.log("file actualContents:", filSlice);
> ```

Yes that is a workaround but this is a regression. BunFile.slice() used to work correctly in previous bun versions.

**Comment by jdalton** [comment]
Related:
https://github.com/oven-sh/bun/issues/5980
https://github.com/oven-sh/bun/issues/6252
https://github.com/oven-sh/bun/pull/5186

@tryggvil do you know which version of Bun it worked in?
Of interest https://github.com/oven-sh/bun/pull/6259

**Comment by jdalton** [comment]
@tryggvil do you know which version of Bun it worked in?

**Comment by jdalton** [comment]
Of interest https://github.com/oven-sh/bun/pull/6259

**Comment by Jakisundays** [comment]
i have the same problem but with audio files.

**Comment by tryggvil** [comment]
@jdalton  Just got around to verify this but this works correctly last in version 1.0.15 , so this broke in version 1.0.16 of Bun. Btw. this is still not working correctly in bun 1.0.31.

**Comment by gyf304** [comment]
still not working correctly in 1.1.17
