### ISSUE TITLE
readFile does not trim utf8 bom

### ISSUE THREAD

**Issue by xavikortes** [oven-sh/bun#8227]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 6.5.0-14-generic x86_64 x86_64

### What steps can reproduce the bug?

Having a file in disk, in "/path/to/file" location.
This file can reproduce the ¿bug? (https://www.dropbox.com/scl/fi/d4zs6aoq6hr3oew2b6a9v/test.txt?rlkey=20c9d257pxd5emjjzd1gcbn03&dl=0)

And the next ts file:

```ts
import { expect } from "bun:test";
import { readFile } from "fs/promises";

const FILE_PATH = "/path/to/file";

const fsContent = await readFile(FILE_PATH, "utf8");
const bunContent = await Bun.file(FILE_PATH).text();

const sizes = (text: string) => ({
	blobSize: new Blob([text]).size,
	stringLength: text.length,
});

expect(sizes(fsContent)).toEqual(sizes(bunContent));
```

Then running normally like: `bun file.ts`

### What is the expected behavior?

I think this should match the sizes of the file and pass the expect without problems

### What do you see instead?

```ts
error: expect(received).toEqual(expected)

  {
+   blobSize: 342190,
+   stringLength: 339292,
-   blobSize: 342187,
-   stringLength: 339291,
  }

- Expected  - 2
+ Received  + 2
```

### Additional information

Is it intentional? Should I change some call to include "utf-8"?

**Comment by xavikortes** [comment]
Ok. I think it happens because of this:

```sh
$ file test.txt
test.txt: Nim source code, Unicode text, UTF-8 (with BOM) text, with CRLF line terminators
```

It is matching in this another file (the same file, but without CRLF):

```sh
$ file test2.txt
test2.txt: Nim source code, Unicode text, UTF-8 text
```

I still don't know if the mismatch is ok in the first file.
The `wc -m -c test.txt` is ouputting the same that fs.readFile

**Comment by Jarred-Sumner** [comment]
Bun.file(string).text() trims UTF-8 BOM 

fs.readFile does not currently.

**Comment by paperclover** [comment]
Not a bug in bun. `Bun.file` intentionally handles and rmeoves the byte-order mark. In a recent PR i made it will also handle UTF16le marks.

node.js does not trim these

<img width="674" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/8d69c7c5-f992-4536-8411-533f18d31425">
