### ISSUE TITLE
Bun.Glob does not consider the option onlyFiles correctly

### ISSUE THREAD

**Issue by vikingair** [oven-sh/bun#8231]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

Run this file:

```
const glob = new Bun.Glob("*", { onlyFiles: false });

for await (const file of glob.scan(".")) {
    console.log(file)
}
```

### What is the expected behavior?

Should log all directories in the current directory.

### What do you see instead?

I see only files in the log.

**Comment by gvilums** [comment]
The issue is that `Glob` does not accept `ScanOptions` as a second argument. You should pass the options object in the call to `glob.scan`, like this:
```
const glob = new Bun.Glob("*");

for await (const file of glob.scan({ onlyFiles: false })) {
    console.log(file)
}
```
Also see https://bun.sh/docs/api/glob
