### ISSUE TITLE
Astro forms are empty

### ISSUE THREAD

**Issue by camiloux** [oven-sh/bun#8236]
### What version of Bun is running?

1.0.22

### What platform is your computer?

Linux server

### What steps can reproduce the bug?

- Create an astro form
- Build the astro app and upload it to the server (with nginx for example)
- Try posting from that form
- I always get an empty form data when running the built app with bun.
- It work just fine with node

### What is the expected behavior?

- Get the actual data of the form as filled by the user

### What do you see instead?

- Empty form data.

### Additional information

This make bun unusable for Astro in production. Not being able to process a simple a form in production. Work fine with bun run dev, and work fine in the server with node.

**Comment by Electroid** [comment]
Duplicate of #8092
