### ISSUE TITLE
Unable to debug with Bun VSCode Extension

### ISSUE THREAD

**Issue by monawwar-appointy** [oven-sh/bun#8250]
### What version of Bun is running?

1.0.23

### What platform is your computer?

mac m1

### What steps can reproduce the bug?

Install Bun VSCode extension and try to debug a file

### What is the expected behavior?

It should start the debug mode

### What do you see instead?

I see an error in the debug console

```rust
Failed to start inspector:
 131 |     }, this.#listen();
132 |   }
133 |   get url() {
134 |     return this.#url;
135 |   }
136 |   #listen() {
                        ^
EADDRINUSE: Failed to start server. Is port 6499 in use?
 syscall: "listen"

      at #listen (internal:debugger:136:19)
      at new Debugger (internal:debugger:122:27)
      at internal:debugger:98:25

```

### Additional information

I checked no port is in use. I just installed the extension and tried for the first time.

**Comment by 2Lavine** [comment]
same problem but in mac intel
debugging with web is ok.

**Comment by monawwar-appointy** [comment]
does the breakpoint work with web debugging?

**Comment by monawwar-appointy** [comment]
also, i am having issue with ngrok, it doesn't work, always giving me error:

```
1212 |         this[kStopReading] = true;
1213 |         if (!(error instanceof RequestError)) {
1214 |             error = new RequestError(error.message, error, this);
1215 |         }
1216 |         const typedError = error;
1217 |         const { response } = typedError;
                    ^
RequestError: Attempted to assign to readonly property.
 code: "ERR_GOT_REQUEST_ERROR"
```

#8258

**Comment by 2Lavine** [comment]
cool. I rolled the version back to 1.0.22 and it worked normally.

**Comment by monawwar-appointy** [comment]
> cool. I rolled the version back to 1.0.22 and it worked normally.

which way you used to install 1.0.22

**Comment by 2Lavine** [comment]
pnpm install bun@1.0.22 --global

**Comment by Electroid** [comment]
You can also run `bun upgrade --canary` to get a fixed version

**Comment by xencodes** [comment]
@Electroid still no fix

**Comment by nick4814** [comment]
I tried `bun upgrade --canary`, but this did not fix the problem for me. My issue is similar, also using Windows 10. 

### Error
```
Failed to start inspector:
 40 |       }
41 |     },
42 |     close: () => {
43 |       writer.close(), pendingMessages.length = 0;
44 |     }
45 | }, parseUrl = function(input) {
                           ^
TypeError: "ws+unix://C:\Users\[USER_NAME]\AppData\Local\Temp\fee8lxqt44n.sock?break=1" cannot be parsed as a URL.
      at internal:debugger:45:23
      at new Debugger (internal:debugger:124:14)
      at internal:debugger:100:13
```

**Comment by smultar** [comment]
I have also encountered this issue and am hoping for a resolution.
