### ISSUE TITLE
read postscriptName as Buffer in fontkit, but Node is string

### ISSUE THREAD

**Issue by loveloki** [oven-sh/bun#8252]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 5.15.0-88-generic x86_64 x86_64

### What steps can reproduce the bug?

fontkit can open TTF or TTC file, and read font's postscriptName.

in Node, postscriptName is string, but in Bun it is Buffer.This can be reproduced in any TTF or TTC file.

So, it cause can't open a TTC file by open/openSync api, beacause inside code get it use string but in bun that is Buffer.

As shown in the picture:

![image](https://github.com/oven-sh/bun/assets/14935777/3f37581b-e88d-44b9-911a-c000fd8e3938)

```javascript
import * as fontkit from 'fontkit'

const path = './YuGothL.ttc'
const font = fontkit.openSync(path)

font.fonts.forEach(ttf => {
  console.log(ttf.postscriptName)
})

const f1 = fontkit.openSync(path, 'YuGothic-Light')
const f2 = font.getFont('YuGothicUI-Light')

console.log(f1 === null, f2 === null)
```

So what can i do for this?

### What is the expected behavior?

postscriptName is a string such as Node

**Comment by Electroid** [comment]
It appears the reason this is failing is because we do not support UTF16 decoding in `TextDecoder`.

<img width="1261" alt="Screenshot 2024-01-18 at 12 57 33 PM" src="https://github.com/oven-sh/bun/assets/3238291/c4f05e62-1cc3-4057-a093-f888ae996afe">

**Comment by Electroid** [comment]
Duplicate of #6084

**Comment by Electroid** [comment]
We will fix this, but closing as a duplicate of a previous issue that reported this bug.
