### ISSUE TITLE
Error in create-cloudflare-cli initialization

### ISSUE THREAD

**Issue by qweered** [oven-sh/bun#8253]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 6.7.0-arch3-1 x86_64 unknown

### What steps can reproduce the bug?

bun create cloudflare@latest

### What is the expected behavior?

installation is successfull

### What do you see instead?

Error: spawn npm ENOENT

**Comment by Electroid** [comment]
Is there a stack trace available?

**Comment by qweered** [comment]
now it works correctly
