### ISSUE TITLE
ngrok tunneling is not working

### ISSUE THREAD

**Issue by mxvsh** [oven-sh/bun#8258]
### What version of Bun is running?

1.0.23

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Try to create a local tunnel with ngrok

<img width="770" alt="Screenshot 2024-01-18 at 17 42 20" src="https://github.com/oven-sh/bun/assets/31907722/b5548f85-eb08-4cdd-a9d1-f1c0ef50b0e4">

### What is the expected behavior?

It should be able to create local tunneling

### What do you see instead?

```js
1212 |         this[kStopReading] = true;
1213 |         if (!(error instanceof RequestError)) {
1214 |             error = new RequestError(error.message, error, this);
1215 |         }
1216 |         const typedError = error;
1217 |         const { response } = typedError;
                    ^
RequestError: Attempted to assign to readonly property.
 code: "ERR_GOT_REQUEST_ERROR"
```

### Additional information

I tried running the same code with `Deno` and `Node` and it worked just fine.

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.9 with #11082
