### ISSUE TITLE
Installation Apple Silicon m1 max arm64

### ISSUE THREAD

**Issue by j-mendez** [oven-sh/bun#828]
### Version

latest

### Platform

Darwin Kernel Version 21.5.0 root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

```sh
curl -fsSL https://bun.sh/install | bash

bun --help
```

I had an older version of bun installed and just installed the latest today. Upon install the PATH is removed etc.

Upon executing the binary directly it works `/Users/$ME/.bun/bin/bun`

![bun CLI output when executing the binary showing error with PATH](https://user-images.githubusercontent.com/8095978/180441981-44e8c7cb-a476-4ca0-bfaf-0ab91d77da96.png)

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

bun to output help commands

### What do you see instead?

zsh: exec format error: /Users/$ME/.sde/sde

### Additional information

![working image of bun CLI output when executing the binary](https://user-images.githubusercontent.com/8095978/180441273-a7cc096a-d81e-48b7-bcad-d15a25341f8a.png)

**Comment by Jarred-Sumner** [comment]
It sounds like you have a copy of bun in `.sde/sde` in your PATH and that copy is overwriting the `~/.bun/bin/bun` version

If you delete `~/.sde/sde/bun` that should fix it

**Comment by j-mendez** [comment]
@Jarred-Sumner thanks for the tip, theres actually nothing in my `.sde` folder with bun. I did a recursive search across all of the files in the folder. My initial bun install I ran via curl it the `bun` command worked fine. 

I see this added inside my shell config:

`![`[ -s "/Users/jeffreymendez/.bun/_bun" ] && source "/Users/jeffreymendez/.bun/_bun"`

After removing the bun command properly works. I think this issue will occur for new users as they upgrade from older versions. This issue could be used to track how important it would be to add logic to fix the upgrade or put a note in the README.md.

```
# Bun
export BUN_INSTALL="/Users/jeffreymendez/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -d ~/.sde ] && alias bun="~/.sde/sde -chip-check-disable -- bun"
[ -d ~/.sde ] && alias bun="~/.sde/sde -chip-check-disable -- bun"
export PATH=~/bin:$PATH
```
