### ISSUE TITLE
error: cannot write multiple output files without an output directory

### ISSUE THREAD

**Issue by andyjessop** [oven-sh/bun#8280]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```ts
async function main() {
  const result = await Bun.build({
    entrypoints: ['./src/entry.ts'],
    naming: '[dir]/[name].[hash].[ext]',
    splitting: true,
  });

  console.log(result);
}
```
Gives:
```bash
{
  outputs: [],
  success: false,
  logs: [
    error: cannot write multiple output files without an output directory
  ],
}
```
Adding an `outDir` produces the following results:
<img width="270" alt="Screenshot 2024-01-19 at 14 53 44" src="https://github.com/oven-sh/bun/assets/1304307/7083dad9-e2b8-4279-b64f-78576c8bebf1">

### What is the expected behavior?

I would expect that not having an `outDir` will produce exactly the same output, just not written to disk.

### What do you see instead?

The error above

**Comment by Jarred-Sumner** [comment]
Can you try `write: false`? I think that exists

**Comment by andyjessop** [comment]
I get the same result:
```
{
  outputs: [],
  success: false,
  logs: [
    error: cannot write multiple output files without an output directory
  ],
}
```

Full build object for reference:
```
{
  config: {
    entrypoints: [ "./src/entry.ts" ],
    naming: "[dir]/[name].[hash].[ext]",
    plugins: [
      [Object ...]
    ],
    splitting: true,
    write: false,
  },
  onDispose: [Function],
  onEnd: [Function],
  onLoad: [Function: onLoad],
  onResolve: [Function: onResolve],
  onStart: [Function],
  resolve: [Function],
  module: [Function],
  initialOptions: {
    entrypoints: [ "./src/entry.ts" ],
    naming: "[dir]/[name].[hash].[ext]",
    plugins: [
      [Object ...]
    ],
    splitting: true,
    write: false,
    bundle: true,
    entryPoints: [ "./src/entry.ts" ],
    minify: false,
    minifyIdentifiers: undefined,
    minifyWhitespace: undefined,
    minifySyntax: undefined,
    outbase: undefined,
    platform: undefined,
  },
  esbuild: {},
}
```

**Comment by aboqasem** [comment]
The test is there but commented out:

https://github.com/oven-sh/bun/blob/b433beb016470b87850f3c018974de5f2e355d52/test/bundler/bun-build-api.test.ts#L171-L200

EDIT:

Although the test fails, the build succeeds with 3 outputs.

This is the passing test case: #8315

EDIT:

This is the test case that will fail with the same error:

https://github.com/oven-sh/bun/blob/b433beb016470b87850f3c018974de5f2e355d52/test/bundler/bun-build-api.test.ts#L220-L241

**Comment by BjornTheProgrammer** [comment]
Also experiencing this issue with the following setup...
<br />

`build.ts`
```ts
const result = await Bun.build({
	entrypoints: ['./src/index.ts', './src/entry.ts'],
})

console.log(result);
```
<br />
<br />

`entry.ts`
```ts
import htmlFilePath from './file.html'
console.log(htmlFilePath);
```
<br />

Get the result
```ts
{
  outputs: [],
  success: false,
  logs: [
    error: cannot write multiple output files without an output directory
  ],
}
```
<br />

I would expect this result instead, but just not written to disk...
```ts
{
  outputs: [
    BuildArtifact (entry-point) {
      path: "/Users/bjorn/Desktop/testing-bun-bundler/out/entry.js",
      loader: "ts",
      kind: "entry-point",
      hash: "eda25f46c19faa74",
      FileRef ("/Users/bjorn/Desktop/testing-bun-bundler/out/entry.js") {
        type: "text/javascript;charset=utf-8"
      },
      sourcemap: null
    }, BuildArtifact (asset) {
      path: "/Users/bjorn/Desktop/testing-bun-bundler/out/file-66945772f0b34e9b.html",
      loader: "file",
      kind: "asset",
      hash: "66945772f0b34e9b",
      FileRef ("/Users/bjorn/Desktop/testing-bun-bundler/out/file-66945772f0b34e9b.html") {
        type: "application/octet-stream"
      },
      sourcemap: null
    }
  ],
  success: true,
  logs: [],
}
```

**Comment by ezekielchentnik** [comment]
Hi, I'm experiencing this same issue. I've also tested as others above and found it does work if your entry does not have any imports (maybe this info will help debug)

**Comment by aralroca** [comment]
I have the same issue after adding this import to my ESM file:

```ts
import * as monaco from 'monaco-editor'
```

Easy to reproduce it.

**Comment by paperdave** [comment]
this line in bundle_v2.zig
```zig
if (root_path.len == 0 and c.parse_graph.additional_output_files.items.len > 0 and !c.resolver.opts.compile) {
    try c.log.addError(null, Logger.Loc.Empty, "cannot write multiple output files without an output directory");
    return error.MultipleOutputFilesWithoutOutputDir;
}
```

the check only makes sense when outfile or stdout is the target for the bundle (impossible to emit more than one file)

**Comment by BjornTheProgrammer** [comment]
@paperdave I created a pull request which solves this issue, thanks for the pointer!
