### ISSUE TITLE
bun:sqlite: Statement.run returns void instead of object

### ISSUE THREAD

**Issue by vbhavsar** [oven-sh/bun#8284]
### What version of Bun is running?

1.0.21

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

When running an update statement, there is no way to inspect the number of rows affected by the update. 

```ts
import { Database } from "bun:sqlite";

const db = new Database(":memory:");

db.run(`
CREATE TABLE bug_demo (
  id INTEGER,
  data TEXT
);
`)
db.run(`insert into bug_demo (id, data) values (1, 'foo')`)
console.log(db.query(`select * from bug_demo`).get()); // => { id: 1, data: "foo"}
const result = db.query(`update bug_demo set data='bar' where id = 1`).run();
console.log(`result: ${result}`); // => result: undefined
console.log(db.query(`select * from bug_demo`).get()); // => { id: 1, data: "bar"}
```

### What is the expected behavior?

The return value of an update statement should include the number of rows affected.

### What do you see instead?

`.run` returns void. 
https://bun.sh/docs/api/sqlite#reference

### Additional information

better-sqlite3 returns an object from .run
https://github.com/WiseLibs/better-sqlite3/blob/HEAD/docs/api.md#runbindparameters---object

**Comment by Cheapshot003** [comment]
taking a look at this rn. I'm a noob though, trying my best

**Comment by Cheapshot003** [comment]
nvm I give up. sqlite3_changes(db) in JSSQLStatement.cpp seems to return always 0 and I can't find out why :/

**Comment by sidesteps** [comment]
same as #3284.
