### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by MikeyA-yo** [oven-sh/bun#8285]
### What is the problem this feature would solve?

it would make bun available to much more users to try and use it, and test it

### What is the feature you are proposing to solve the problem?

Windows support

### What alternatives have you considered?

none

**Comment by mGranTY** [comment]
Windows support is being worked on, you can follow the progress on twitter/x or discord. 

[Twitter link/ x](https://twitter.com/bunjavascript/status/1747073096295874990)

[Bun Discord](https://bun.sh/discord)

Duplicate of https://github.com/oven-sh/bun/issues/43

**Comment by paperclover** [comment]
Duplicate of #43
