### ISSUE TITLE
Can't install project dependencies (creact-react-app based)

### ISSUE THREAD

**Issue by lomeat** [oven-sh/bun#830]
### Version

0.1.4

### Platform

Darwin mbp.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

1. Open front-end create-react-app base project with webpack and typescript support.
2. Wait for a very long time installing all deps.
3. At 1000+ dep, it freezes forever without any logs.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Installed dependencies. Additionally would be great to use similar to "npm ci" to avoid updating packages to the newest.

### What do you see instead?

![CleanShot 2022-07-22 at 20 25 24](https://user-images.githubusercontent.com/33469504/180483041-ab98c3e4-b0b7-461a-8834-c17e7ada67d4.png)

Freeze forever w/out any logs

### Additional information

Tested on MacBook Pro M1 2021

**Comment by Electroid** [comment]
We've made very significant changes and improvements to `bun install` between Bun v0.1 and Bun v1.0. Specifically, we fixed some of the issues around hanging a while ago. However, if you can still reproduce this issue after upgrading, please feel free to re-open this issue and we'll investigate.
