### ISSUE TITLE
Dear all ,please allow me to leave a comment about Nodejs community management because I was blocked by nodejs (just because I mentioned a bug that they all admit to)

### ISSUE THREAD

**Issue by introspection3** [oven-sh/bun#8300]
### What is the problem this feature would solve?

There is such a person in this world: covering his ears and stealing the bell. FORCE A BUG TO CLOSE AND ASSUME THAT THE BUG DOES NOT EXIST. This is the attitude towards bugs. First of all, I would like to state that it is not for them to fix the bug, but to raise the bug so that at least the community will know what the problem is, not hide the truth

LINK: [https://github.com/nodejs/node/issues/51507](https://github.com/nodejs/node/issues/51507)

### What is the feature you are proposing to solve the problem?

![image](https://github.com/denoland/deno/assets/12368358/b7fe3a05-c575-47f7-b7b2-d48ce3014510)

content:

[html.zip](https://github.com/denoland/deno/files/13997873/html.zip)

**Comment by paperclover** [comment]
this isnt a feature request or bug report for bun.

if our net.Socket / Bun.connect has leaks, please report that as a bug with a specific reproduction.
