### ISSUE TITLE
Globbing /tmp/xx/*.txt incorrectly returns empty list

### ISSUE THREAD

**Issue by pesterhazy** [oven-sh/bun#8304]
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

await $`rm -rf /tmp/xx; mkdir /tmp/xx; touch /tmp/xx/1.txt /tmp/xx/2.txt; echo /tmp/xx/*.txt`.text()

### What is the expected behavior?

"/tmp/xx/1.txt /tmp/xx/2.txt\n"

### What do you see instead?

"\n"

**Comment by angelxmoreno** [comment]
I have experienced issues with globs as well when using [TypeOrm](https://typeorm.io/data-source-options#common-data-source-options) and using [routing-controllers](https://github.com/typestack/routing-controllers?tab=readme-ov-file#load-all-controllers-from-the-given-directory). 
Basically when I start up my server using bun, both globs return empty but when I run it in ts-node they return what is expect.

**Comment by zackradisic** [comment]
Fixed by #10121
