### ISSUE TITLE
error: No version matching "x.x.0-next.x" found for specifier "x" (but package exists)

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8305]
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```sh
mkdir reproduce
cd reproduce/
bun init -y
bun add eslint-plugin-svelte@2.34.0-next.5
```

### What is the expected behavior?

Bun should install the package.

### What do you see instead?

```sh
bun add v1.0.24 (6fa35839)
error: No version matching "2.34.0-next.5" found for specifier "eslint-plugin-svelte" (but package exists)
```

### Additional information

Confirmed that the package is installable via npm. Also tried adding the `npm:` prefix with no success.

**Comment by Electroid** [comment]
Duplicate of #9023
