### ISSUE TITLE
Require function from modules.createRequired does NOT find modules

### ISSUE THREAD

**Issue by robogeek** [oven-sh/bun#831]
### Version

0.1.4

### Platform

Linux davidpc 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

In a blank directory run `npm init -y` to generate a `package.json`.  The `createRequired` function is supposed to generate a function named `require` that can be used in an ES6 module to do what we do with `require` in CommonJS modules.

There are two scenarios to consider -- a local `require` and a `node_modules` require.  With Node.js v18.6 both scenarios work fine.  With Bun, both fail saying it cannot find the module.

Then run `npm install mime --save` to give us a normal module to use

With a file - `required.js`

```js
console.log('In required.js');

module.exports.hello = () => { return 'Hello, world!'; }
```

And another file `test.js`

```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const required = require('./required');
console.log(required.hello());

const mime = require('mime');

console.log(mime.getType('txt'));                    // ⇨ 'text/plain'
console.log(mime.getExtension('text/plain'));        // ⇨ 'txt
```

With Node.js the output is this:

```
$ node test.mjs 
In required.js
Hello, world!
text/plain
txt
```

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

The `require` statements load the module, and I can execute functions in the module.

Specifically:

```
$ node test.mjs 
In required.js
Hello, world!
text/plain
txt
```

### What do you see instead?

```
$ bun test.mjs 

error: Cannot find module "./required" from "file:///home/david/Projects/bun/t/test.mjs"
```

Then, if I comment out a bit of the code:

```
$ bun test.mjs 

error: Cannot find package "mime" from "file:///home/david/Projects/bun/t/test.mjs"
```

### Additional information

After filing this - I downloaded the Canary release of Bun 0.1.5 and it still shows this failure

**Comment by Jarred-Sumner** [comment]
Thank you - this is clearly a bug

If you do `require()` without `createRequire`, does it work? Bun supports `require` and `import` in the same file (transpiler rewrites it to `import.meta.require()`)
