### ISSUE TITLE
bun:test freezes (command never exits) after upgrading to 1.0.24

### ISSUE THREAD

**Issue by EvHaus** [oven-sh/bun#8314]
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

After upgrading from 1.0.23 to 1.0.24, Bun is freezing (never quits) after running my tests via `bun:test`. Downgrading to 1.0.23 fixes the issue.

Steps to reproduce:

- Clone this repo: https://github.com/EvHaus/test-runner-benchmarks
- Run `cd benchmarks/bun`
- Run `bun i`
- Run `bun run test`
- **BUG**: Tests will be stuck and never exit

If you downgrade to 1.0.23, you'll see it works fine.

**UPDATE:** Still an issue with 1.0.28 and 1.0.29+a146856d canary

### What is the expected behavior?

Tests run and complete (like in 1.0.23)

### What do you see instead?

Process never exists. Stuck forever.

**Comment by Jarred-Sumner** [comment]
@nektro this is probably the isEventLoopActive change

**Comment by vedmakk** [comment]
This issue is still blocking us from upgrading bun to any version above 1.0.23.

Tests are running fine with 1.0.23 and are just hanging with no error on versions above.

Did anyone manage to fix it for them? The problem persists also with the latest 1.0.35 version.

**Comment by garrettg123** [comment]
Same on 1.1.1 and 1.1.3

**Comment by Amatewasu** [comment]
I have the same issue. The tests run properly with bun v1.0.23 but freeze with bun 1.0.24.
It also freezes with bun 1.0.36 (latest 1.0 version) and bun 1.1.3 (latest version).

**Comment by vladmundi-mettle** [comment]
Had this issue running tests in a React app project. Upgrading Vite and Happy-dom dependencies resolved the issue for me.

**Comment by EvHaus** [comment]
Thanks @vladmundi-mettle. That's true. Using the latest dependencies I can't reproduce this anymore. Will close.

**Comment by Jarred-Sumner** [comment]
@EvHaus btw in the test-runner-benchmarks repo, the `"should be able to toggle the collapsible content"` test seems to be taking up much of the time in `bun test`.

Commented out:
<img width="305" alt="image" src="https://github.com/oven-sh/bun/assets/709451/919a2188-2af3-4921-a52e-17f04bf7b050">

Not commented out:
<img width="296" alt="image" src="https://github.com/oven-sh/bun/assets/709451/df9b2cc5-0e83-4b80-8656-83b8f035a0a2">

I think it's because we haven't implemented jest fake timers yet

**Comment by EvHaus** [comment]
@Jarred-Sumner Thanks for looking at it again. That test doesn't use Jest timers though. It uses `@testing-library/react`'s [`waitForElementToBeRemoved`](https://testing-library.com/docs/dom-testing-library/api-async/#waitforelementtoberemoved) (which uses `setInterval` under-the-hood).
