### ISSUE TITLE
Fix Hot Module Reloading

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#833]
`bun dev` has builtin support for hot module reloading CSS & with React.

It's disabled due to bugs and also it lacks end-to-end test coverage (there are tests that check it runs, but not that test modifying a file, saving, and that the changes are reflected in the browser end-to-end)

The main bug is somewhere in this function. After receiving the code to reload in the websocket handler, this function is called:
https://github.com/oven-sh/bun/blob/7914adff1e61c48f27ff6f71bc0cce46c4d1e4f2/src/runtime/hmr.ts#L1331-L1526

To fix this, you will need a debug build of bun. `hmr.ts` is embedded in bun's binary (so you don't have to install an npm package for it), to rebuild:
```js
make runtime_js dev
```

For now, on bun v0.1.5, add this flag to enable HMR:
```
BUN_FORCE_HMR=1
```

Help would be appreciated!

**Comment by noahehall** [comment]
@Jarred-Sumner is this why [bun-community/react](https://github.com/bun-community/create-templates) doesnt hot reload?

**Comment by devmozao** [comment]
I tried the `bun create react` template, and it doesn't do hot reloading at all. You need to build again and serve the dev server. So I tried the following: build everytime a new request is received on the server, but it's not a complete solution. You need to force the cache reload on the browser (CTRL + SHIFT + R)

if I find something, will post here.

**Comment by noahehall** [comment]
i might take a swing at this over the weekend

**Comment by vjpr** [comment]
> You need to force the cache reload on the browser 

I used `watchman` to watch files in my project and then send a websockets message to call `window.location.reload()` when there is a change. Works well.

The entrypoint's `artifact.sourcemap.sources` returns the list of sources involved in each entrypoint - these are the files that need to be watched. `sourcemap: 'external'` must be used.

Let me know if its interesting to you to open source.

**Comment by noahehall** [comment]
if you have to hard reload maybe it's simpler to disable cache in the dev console, think it's under settings / network

**Comment by Ashvith10** [comment]
I'm on NixOS 23.05, using v0.6.2, and hot reload does not work. It does not work even on manually reloading the page.

**Comment by wintercounter** [comment]
> I'm on NixOS 23.05, using v0.6.2, and hot reload does not work. It does not work even on manually reloading the page.

It's because `--watch` only watches from the `dev.tsx` entry. I simply added `import './src/App.tsx` to `dev.tsx` which made the watcher work. `Bun.build` really should respect `--watch` and add the defined entry to the watcher.

All in all, things are quite broken this way, wonder if the templates are too outdated and there are better solutions already, or it's simply how it's designed to work, and let Next and other frameworks handle dev envs correctly?

I myself just wanted a simple SPA with no extras, and currently with the default template neither the watcher or HMR works.

**Comment by TarekMaza** [comment]
I just created a simple bun project with `bun init` and the `bun --watch <file-name>` doesn't work, every time you have to stop and run the file again to see the changes

**Comment by Zikoat** [comment]
`bun dev` was removed in version 1.0.0, so this issue might be outdated and optionally closed. Maybe we could get a new option in `Bun.serve()` which enables HMR?

**Comment by Zikoat** [comment]
This was asked in this stackoverflow question: https://stackoverflow.com/q/76427355/5936629

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.

**Comment by LahkLeKey** [comment]
For those of you landing here in 2025 and avoiding a vite dev server but are having trouble with the new beta HMR with bun dev on the template from bun init react, tailwind, shadcn (should work with other setups as well) 

This was the solution I landed on and am fairly happy with it outside of having the production flag active when developing locally.
Saving will reload the dev server,  you will still need to manually reload the page, you can tie in watchman as well for a window.reload but didnt want to go that far.

1.) in build.ts add a watch / dev server start/restart flag
```ts
// Parse args into BuildConfig + watch flag
function parseArgs(): Partial<BuildConfig> & { watch?: boolean } {
```

```ts
// Development: build + start + restart on change
if (watchMode) {
  console.log("👁️  Watch mode active");
  let server: any;
  const startServer = () => {
    if (server) server.kill();
    server = Bun.spawn({
      cmd: ["bun", "src/index.tsx"],
      env: { ...process.env, NODE_ENV: "production" },
      stdio: ["inherit", "inherit", "inherit"],
    });
  };
  await runBuild();
  startServer();
  ["src", "public"].forEach((dir) => {
    if (!existsSync(dir)) return;
    fsWatch(dir, { recursive: true }, async () => {
      console.clear();
      await runBuild();
      startServer();
    });
  });
} else {
  // single build
  await runBuild();
}
```

2.) package.json
```json
"start": "bun run build.ts --watch",
```
3.) Optional error boundary with source map help.
```tsx
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { AlertCircle } from "lucide-react";
import React, { type ReactNode } from "react";
import StackTrace, { type StackFrame } from "stacktrace-js";

interface State {
  hasError: boolean;
  error?: Error;
  frames?: StackFrame[];
  isMapping: boolean;
  showNodeModules: boolean;
  filterText: string;
}

export class ErrorBoundary extends React.Component<{ children: ReactNode }, State> {
  state: State = {
    hasError: false,
    isMapping: false,
    showNodeModules: false,
    filterText: "",
  };

  static getDerivedStateFromError(error: Error): Partial<State> {
    return { hasError: true, error };
  }

  async componentDidCatch(error: Error): Promise<void> {
    this.setState({ isMapping: true });
    try {
      const frames = await StackTrace.fromError(error, { offline: false });
      this.setState({ frames });
    } catch (e) {
      console.warn("StackTrace mapping failed:", e);
    } finally {
      this.setState({ isMapping: false });
    }
  }

  reset = (): void => {
    this.setState({
      hasError: false,
      error: undefined,
      frames: undefined,
      filterText: "",
      showNodeModules: false,
    });
    window.location.reload();
  };

  copy = (): void => {
    const lines = this.getDisplayLines();
    navigator.clipboard.writeText(lines.join("\n"));
  };

  toggleNodeModules = (checked: boolean): void => {
    this.setState({ showNodeModules: checked });
  };

  onFilterChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    this.setState({ filterText: e.target.value });
  };

  private formatFrames(): string[] {
    const { frames, error } = this.state;
    if (!frames?.length) {
      return error?.stack?.split("\n") || [];
    }
    return frames.map(
      (f, i) =>
        `${i}: ${f.functionName || "<anonymous>"} @ ${(f.fileName ?? "unknown file").replace(/\\/g, "/")}:${f.lineNumber}:${f.columnNumber}`,
    );
  }

  private getAppLines(): string[] {
    const { filterText } = this.state;
    return this.formatFrames().filter(
      (line) => !line.includes("node_modules") && line.includes(filterText),
    );
  }

  private getExternalLines(): string[] {
    const { showNodeModules, filterText } = this.state;
    if (!showNodeModules) return [];
    return this.formatFrames().filter(
      (line) => line.includes("node_modules") && line.includes(filterText),
    );
  }

  private getDisplayLines(): string[] {
    const app = this.getAppLines();
    const ext = this.getExternalLines();
    return this.state.showNodeModules ? [...app, "--- External Modules ---", ...ext] : app;
  }

  render() {
    if (!this.state.hasError) return this.props.children;
    const { error, isMapping, showNodeModules, filterText } = this.state;
    const lines = this.getDisplayLines();

    return (
      <Card className="m-6">
        <CardHeader>
          <div className="flex items-center gap-2">
            <AlertCircle className="h-6 w-6 text-destructive" />
            <CardTitle>Dev Sandbox Error</CardTitle>
          </div>
          <CardDescription>{error?.message || "An error occurred."}</CardDescription>
        </CardHeader>
        <Separator />
        <CardContent className="space-y-4">
          <div className="flex flex-wrap gap-4">
            <div className="flex items-center space-x-2">
              <Checkbox checked={showNodeModules} onCheckedChange={this.toggleNodeModules} />
              <Label>Include node_modules</Label>
            </div>
            <Input
              placeholder="Filter frames"
              value={filterText}
              onChange={this.onFilterChange}
              className="flex-1 min-w-[150px]"
            />
            <Button size="sm" onClick={this.copy} disabled={isMapping}>
              Copy
            </Button>
          </div>

          <ScrollArea className="rounded border h-48">
            <div className="space-y-1 p-2">
              {lines.map((ln) => (
                <div key={ln} className="w-full text-left font-mono text-xs whitespace-pre-wrap">
                  {ln}
                </div>
              ))}
            </div>
          </ScrollArea>
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button variant="outline" onClick={this.reset}>
            Reload
          </Button>
        </CardFooter>
      </Card>
    );
  }
}
```
```tsx
import { Loading } from "@/layouts/Loading";
import { type ComponentType, Suspense } from "react";
import { ErrorBoundary } from "./ErrorBoundary";

export function withErrorBoundary<P>(Component: ComponentType<P>) {
  return function ErrorWrapped(props: P) {
    return (
      <ErrorBoundary>
        <Suspense fallback={<Loading />}>
          <Component {...props} />
        </Suspense>
      </ErrorBoundary>
    );
  };
}
```

![Image](https://github.com/user-attachments/assets/5f096d9c-2754-4217-b47f-cd09ce5fdd00)
