### ISSUE TITLE
Windows: Non ASCII characters are replaced with '?' in command line arguments

### ISSUE THREAD

**Issue by crispy-strawberry** [oven-sh/bun#8331]
### What version of Bun is running?

1.0.25-canary.16+a8ff7be64

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Execute this command in any terminal emulator that supports emoji - 
```
bun -e "console.log('🐇')"
```

### What is the expected behavior?

🐇

### What do you see instead?

??

### Additional information

# Reason
Bun uses [std.os.argv](https://ziglang.org/documentation/master/std/#A;std:os.argv) to get command line arguments. This value is "Populated by startup code before main()" according to the docs, and this startup code does not correctly handle non ASCII characters and literally replaces them with question marks (? 0x3f), so what bun sees is `-e console.log("??")` and therefore ?? gets printed.

https://github.com/oven-sh/bun/blob/353f724a9cd12d1749e974e92bbc47d9138a6601/src/bun.zig#L1847-L1858

# Possible Solutions
1. Use `std.process.argsAlloc`. It handles utf-8 correctly and uses  [`GetCommandLineW`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew) internally
2. Use a combination of  [`GetCommandLineW`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew) and [`GetCommandLineToArgvW`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw)

**Comment by crispy-strawberry** [comment]
I tried to see if just setting the code page to utf-8 and using [GetCommandLineA](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea) would work but it seems that there is no non-UTF16 alternative to `CommandLineToArgvW` :(

**Comment by AlttiRi** [comment]
It works fine for me.

![image](https://github.com/oven-sh/bun/assets/16310547/eb91e5c4-8e1f-47c4-bb82-1c56c70806b0)
(`console.log(process.argv);` with `./bun.exe ./x.mjs -x '🐇'` too)

---

BTW, I have enabled UTF-8 locale ("Beta: Use Unicode UTF-8 for worldwide language support" checkbox). https://superuser.com/a/1451686

(`chcp` prints `Active code page: 65001` in cmd)

**Comment by crispy-strawberry** [comment]
Interesting, then this suggests that changing your code page doesn't work if UTF-8 isn't your default locale. (It is already done in the bun source code and I tested it independently). I suspect the `?` come from [`GetCommandLineA`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinea) which might have been used internally in `std.os.argv` (i tested it and it seems to replace non ascii with `?`)
