### ISSUE TITLE
Memory leak with prisma

### ISSUE THREAD

**Issue by lobomfz** [oven-sh/bun#8336]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.6.9-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

Repeatedly calling prismaclient.findmany()

Example and reproduction steps here: https://github.com/lobomfz/prisma-bun-memleak

### What is the expected behavior?

Memory usage should stabilize and lower after stress is done

### What do you see instead?

Memory usage keeps grows from 150mb to 500mb in a few seconds and doesn't stop growing. Got to 10gb in less than an hour.

![image](https://github.com/oven-sh/bun/assets/24996359/42eb5e55-2d80-473e-b67b-8a70d59b5f65)

### Additional information

This does not happen with Kysely and doesn't happen with node (if it does, to a negligible extent)

engineType = "binary" doesn't work at all

**Comment by Jarred-Sumner** [comment]
Thanks for reporting this and the reproduction

**Comment by jontybrook** [comment]
Related issues:

 https://github.com/oven-sh/bun/issues/7864 
 https://github.com/oven-sh/bun/issues/7864

**Comment by lobomfz** [comment]
> Related issues:
> 
> #7864 #7864

Yes, we also encountered that issue and been running on 1.0.18 ever since 1.0.19 came out, but this memory leak occurs on all versions, including 1.0.18

**Comment by ZTL-UwU** [comment]
I have the same problem in a project with drizzle-orm instead of prisma. Downgrading to 1.0.18 fixes it though.

![image](https://github.com/oven-sh/bun/assets/49156174/4ed30976-f0f1-4c02-93bc-64662597f78b)

**Comment by withadne** [comment]
Is this issue still unresolved? I'm using Prisma with Bun version 1.1.30+7996d06b8, and the memory increased by PrismaClient is still not being released and remains permanently allocated.
In Node.js, the memory only increases to a certain amount and is quickly released when PrismaClient is not in use.
