### ISSUE TITLE
enhancement: wait for additional input in the REPL mode when inserting a new line after a square bracket

### ISSUE THREAD

**Issue by matthewrosse** [oven-sh/bun#8343]
### What is the problem this feature would solve?

This simple feature would make it possible to write nested code in REPL mode (for example: declaring functions).

### What is the feature you are proposing to solve the problem?

The bun's REPL should wait for additional input when a new line is inserted after "{", similar to how it's done in nodejs repl. Currently it looks like this:
<img width="430" alt="Screenshot 2024-01-22 at 03 41 10" src="https://github.com/oven-sh/bun/assets/63936600/d35da9af-14dc-43a2-84c4-2a4b6847f5b9">

**Comment by paperclover** [comment]
will be a part of writing repl in native code: #947
