### ISSUE TITLE
bun install - 'No version matching "__" found for specifier "__" (but package exists)'

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#835]

**Comment by Jarred-Sumner** [comment]
If you run it without the `npm:` prefix, does it work?

**Comment by rgoomar** [comment]
I tested out removing `npm:` and got:
```
error: package "tailwindcss" with tag "@tailwindcss/postcss7-compat" not found, but package exists
```

@invrainbow I got it working with this line instead of the `tailwindcss` line. Although, I'm not sure how that affects any of the code that you have there:
```json
  "devDependencies": {
    "@tailwindcss/postcss7-compat": "2.2.17"
  }
```

The package version was pulled from https://www.npmjs.com/package/@tailwindcss/postcss7-compat

**Comment by invrainbow** [comment]
Worked, thanks!
