### ISSUE TITLE
@napi-rs/canvas memory leak

### ISSUE THREAD

**Issue by 7f8ddd** [oven-sh/bun#8351]
### What version of Bun is running?

1.0.25+b7b0e28b1

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
import { createCanvas } from "@napi-rs/canvas";

async function test() {
  const canvas = createCanvas(600, 600);

  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // The memory leak is much worse when the quality is high. It only leaks when this is called.
  await canvas.encode("webp", 100);
}

for (let i = 0; i < 5000; i++) {
  await test();
}

setInterval(() => {
  Bun.gc(true);
  console.log(process.memoryUsage().rss / 1024 / 1024);
}, 1000);
```

### What is the expected behavior?

Memory to be freed by the GC.

### What do you see instead?

6-7 GB+ of memory usage that never goes down.
RSS: 6980.23828125 (MB)

![image](https://github.com/oven-sh/bun/assets/141754874/1e01ffcf-cfe7-4b96-910c-eef86fce6b29)

### Additional information

Impossible to make any kind of high quality output without having to restart the process afterwards.

**Comment by twlite** [comment]
This seems to be an issue within the library itself https://github.com/Brooooooklyn/canvas/issues/716

**Comment by 7f8ddd** [comment]
> This seems to be an issue within the library itself [Brooooooklyn/canvas#716](https://github.com/Brooooooklyn/canvas/issues/716)

Issue was resolved with https://github.com/Brooooooklyn/canvas/commit/9a4ade5f965e43896894dbac64a8e2b358313305
