### ISSUE TITLE
shell builtin mv misleading error: `ls: No such file or directory`

### ISSUE THREAD

**Issue by pesterhazy** [oven-sh/bun#8363]
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```await $`mv does_not_exit foo`;```

### What is the expected behavior?

mv: rename does_not_exit to foo: No such file or directory

### What do you see instead?

ls: No such file or directory

**Comment by zackradisic** [comment]
Fixed in this PR: #8846
