### ISSUE TITLE
prisma generate can't run with bunx on Windows

### ISSUE THREAD

**Issue by Kayxue** [oven-sh/bun#8366]
### What version of Bun is running?

1.0.25-canary.5+6019665d4

### What platform is your computer?

Microsoft Windows NT 10.0.22623.0 x64

### What steps can reproduce the bug?

1. Install @prisma/client
2. Define Schema in `schema.prisma`
3. Run `bunx prisma generate` 

### What is the expected behavior?

Output like this:
`✔ Generated Prisma Client (v5.8.1) to .\node_modules\.pnpm\@prisma+client@5.8.1_prisma@5.8.1\node_modules\@prisma\client in 54ms`

### What do you see instead?

```
uh-oh: cast causes pointer to be null
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.25-canary.5 (6019665d) Windows x64
BunxCommand:
Elapsed: 20ms | User: 0ms | Sys: 0ms
RSS: 26.19MB | Peak: 26.19MB | Commit: 69.33MB | Faults: 6565
----- bun meta -----

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 19120 panic: cast causes pointer to be null
???:?:?: 0x7ff7476b3da6 in ??? (???)
???:?:?: 0x7ff7476b7974 in ??? (???)
???:?:?: 0x7ff7476b612f in ??? (???)
???:?:?: 0x7ff74772c893 in ??? (???)
???:?:?: 0x7ff7474d1492 in ??? (???)
???:?:?: 0x7ff749879c6f in ??? (???)
???:?:?: 0x7ffe25c3257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe26a8aa57 in ??? (ntdll.dll)
```

**Comment by KilianB** [comment]
Is anyone having success with `bunx` and prisma cli in general? We attempted to execute `bunx prisma init` from within wsl2 and nothing was returned in the terminal. It did not crash but there was no feedback or files generated. 

Fallback to npx is working just fine.

**Comment by paperclover** [comment]
Duplicate of #3827 (prisma cli not working) and also of #8045 (bunx does not work on windows)
