### ISSUE TITLE
Broken Link to Bun 1.0 Video (Footer)

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8369]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The footer at [bun.sh](https://bun.sh/#:~:text=Project-,Bun%201.0,-Roadmap) lists a link to the Bun 1.0 video, but the path is relative instead of absolute. Clicking on the link opens `bun.sh/youtube.com` instead of `youtube.com`

### Where did you find it?

[bun.sh](https://bun.sh/#:~:text=Project-,Bun%201.0,-Roadmap)

**Comment by Electroid** [comment]
Fixed, deploying in a few moments.
