### ISSUE TITLE
`readline` does not read all line when looping with iterator

### ISSUE THREAD

**Issue by michaelchiche** [oven-sh/bun#8370]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.6.6-76060606-generic x86_64 x86_64

### What steps can reproduce the bug?

I have a file
example.txt
```txt 
1
2
3
4
5
```

I made 2 versions of the same scripts, one using events, and the other one a forof loop to iterate over the line.

events
```ts
import readline from "node:readline/promises";
import { createReadStream } from "node:fs";

const stream = createReadStream(`./example.txt`, {
  encoding: "utf-8",
});

const rl = readline.createInterface(stream);

rl.on("line", (line) => {
  console.log("line", line);
}) 
```
the output is correct with
```txt
line 1
line 2
line 3
line 4
line 5
```

but with an iterator
```ts
import readline from "node:readline/promises";
import { createReadStream } from "node:fs";

const stream = createReadStream(`./example.txt`, {
  encoding: "utf-8",
});

const rl = readline.createInterface(stream);

for await (const line of rl) {
  console.log("line", line);
}
```

It only output the first line and ends

### What is the expected behavior?

Both scripts should loop over all the lines, like in the scripts using events.

**Comment by alexilyaev** [comment]
It looks like both code examples are the same
Perhaps a mistake?

**Comment by michaelchiche** [comment]
Fixed ! Thanks @alexilyaev
