### ISSUE TITLE
Contributor mention links are wrong in version 1.0.25

### ISSUE THREAD

**Issue by Ryteck** [oven-sh/bun#8376]
### What is the issue?

Hello, I don't know if this is the right place to report this kind of thing.
In the post of the new version, found on the official blog, the links that redirect to the contributors' profiles do not have the prefix "https;//" with the correct one being "https://", causing a redirection failure when clicked.

### Where did you find it?

https://bun.sh/blog/bun-v1.0.25#thanks-to-5-contributors

![image](https://github.com/oven-sh/bun/assets/38978217/82ba8948-700a-4bb6-b295-222bc90d5601)

![image](https://github.com/oven-sh/bun/assets/38978217/4c3aff39-8824-496a-9002-1416fd62f108)

**Comment by brigitabi** [comment]
Hey @Hanaasagi - are you already working on it? :)

**Comment by Hanaasagi** [comment]
This requires someone from the core team to take a look. the release note is not in this repo.
