### ISSUE TITLE
Fetching package.json... error: Linux kernel version doesn't support io_uring, which Bun depends on.

### ISSUE THREAD

**Issue by umararshad4** [oven-sh/bun#838]
### What do you see instead?

 >> bun create react
Fetching package.json... error: Linux kernel version doesn't support io_uring, which Bun depends on.

To fix this error: please upgrade to a newer Linux kernel.

If you're using Windows Subsystem for Linux, here's how:
  1. Open PowerShell as an administrator
  2. Run this:
    wsl --update
    wsl --shutdown

  Please make sure you're using WSL version 2 (not WSL 1).

If that doesn't work (and you're on a Windows machine), try this:
  1. Open Windows Update
  2. Download any updates to Windows Subsystem for Linux

If you're still having trouble, ask for help in bun's discord https://bun.sh/discord

**Comment by sewe75** [comment]
Same for me on WSL 2 (Windows 11 21H2, Build 22000.795) but got solved after following the instructions which upgraded the kernel to `5.10.102.1`.  

To enable automatic updates for WSL:  
https://superuser.com/a/1709473

**Comment by xhyrom** [comment]
From [bun discord bot](https://github.com/xHyroM/bun-discord-bot)
---

**error: Linux kernel version doesn't support io_uring, which Bun depends on**

To fix this error, you need to update Linux kernel.
If you are using the Windows Subsystem for Linux, do:
  **1.** Open powershell as administrator
  **2.** Run:
     • wsl --set-version <disto name> 2
       • If it throws `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.`, turn on Virtual Machine Platform in Windows Features and then rerun this command.
       • PS: You can get distro name from `wsl --list -v` 
     • wsl --update
     • wsl --shutdown

If that doesn't work (and you're on a Windows machine), try this:
  **1.** Open Windows Update
  **2.** Download any updates to Windows Subsystem for Linux

**Comment by FinnRG** [comment]
@ohsnap4  Please fill out the issue template.

**Comment by xhyrom** [comment]
> ## From [bun discord bot](https://github.com/xHyroM/bun-discord-bot)
> **error: Linux kernel version doesn't support io_uring, which Bun depends on**
> 
> To fix this error, you need to update Linux kernel. If you are using the Windows Subsystem for Linux, do: **1.** Open powershell as administrator **2.** Run: • wsl --set-version 2 • If it throws `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.`, turn on Virtual Machine Platform in Windows Features and then rerun this command. • PS: You can get distro name from `wsl --list -v` • wsl --update • wsl --shutdown
> 
> If that doesn't work (and you're on a Windows machine), try this: **1.** Open Windows Update **2.** Download any updates to Windows Subsystem for Linux

this issue can be resolved by ^

**Comment by yewyewXD** [comment]
I'm having the exact same issue, did everything the bot told, but still cannot fix it.

My Machine:
Windows 10 Pro, version 21H2

Happens when I run `bun create hono`  and `bun install hono` on Ubuntu 20.04.5 terminal
