### ISSUE TITLE
Run interactive command like nvim in Bun Shell

### ISSUE THREAD

**Issue by gutenye** [oven-sh/bun#8397]
### What is the problem this feature would solve?

```
await $`nvim a.js`
```

does not work

### What is the feature you are proposing to solve the problem?

I expected it to run like `nvim a.js` in a bash script

**Comment by Jarred-Sumner** [comment]
is this a meme

**Comment by gutenye** [comment]
No, it's a feature request. [Find out](https://stackoverflow.com/questions/27045726/stdio-piping-issues-when-using-vim-in-child-process-in-node-js) I can use this 

```js
const child_process = require('child_process')
child_process.spawnSync('nvim', [], { stdio: 'inherit' })
```

**Comment by gutenye** [comment]
@Jarred-Sumner Is there a way to pass the `stdio` option to the Bun shell? For example, like how `zx` does it with `$({ stdio: 'inherit' })'nvim'`? This would allow me to use interactive commands in the Bun shell.
