### ISSUE TITLE
@napi-rs/canvas async segfault

### ISSUE THREAD

**Issue by 7f8ddd** [oven-sh/bun#8400]
### What version of Bun is running?

1.0.25+80ad8d57f

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
import { createCanvas } from "@napi-rs/canvas";

// You must run it a few hundred times like this to make it crash.
for (let i = 0; i < 2000; i++) {
  // Adding "await" makes it not segfault.
  (async () => {
    const canvas = createCanvas(400, 400);
    const ctx = canvas.getContext("2d");

    ctx.fillStyle = "black";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    await canvas.encode("png");
  })();
}
```

### What is the expected behavior?

The application should not crash.

### What do you see instead?

error: script "start:dev" was terminated by signal SIGSEGV (Address boundary error)
Segmentation fault

**Comment by 7f8ddd** [comment]
Related:
https://github.com/oven-sh/bun/issues/8400

**Comment by Jarred-Sumner** [comment]
Confirming this is still an issue. 

<img width="574" alt="image" src="https://github.com/oven-sh/bun/assets/709451/87bcdae1-40aa-41a4-887b-f96d9007d4f4">
<img width="886" alt="image" src="https://github.com/oven-sh/bun/assets/709451/176a5517-4e4b-4f78-a9a3-0cc1925722ee">
