### ISSUE TITLE
await $`ls *.js` returns all files in the current directory

### ISSUE THREAD

**Issue by rickyshelton** [oven-sh/bun#8403]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

`ls` in bun shell gives different results in a trival example vs zsh invocation

```
❯ ls *.js
zsh: no matches found: *.js

❯ cat bun-shell.ts
import { $ } from "bun";

// to stdout:
await $`ls *.js`;

❯ bun bun-shell.ts
index.tsx
bun-shell.ts
bun.lockb
node_modules
package.json
math.test.ts
```

### What is the expected behavior?

`ls` command should filter to just *.js files

### What do you see instead?

`ls` command lists all files in directory

**Comment by alexilyaev** [comment]
Was literally about to open the same issue 😁

System:
```shell
macOS 14.2.1
bun 1.0.25
```

**Comment by zackradisic** [comment]
The bug is that we aren't handling the case where a glob pattern doesn't match anything (it should fail), so instead it thinks that no arguments are supplied to `ls` and returns the result of running `ls` with no args.
