### ISSUE TITLE
Built-in Support for Rescript

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8407]
### What is the problem this feature would solve?

Currently, Bun only supports built-in TypeScript - it would be nice to see support for [Rescript](https://rescript-lang.org/), which isn't as popular but is growing quickly and has similar goals to bun (faster, simpler, without leaving ecosystem behind).

### What is the feature you are proposing to solve the problem?

Direct support for `.res.js` and `.res` files, which Bun would compile automatically to JS and run. Rescript also works through a compiler like TypeScript, so this should be similar to implement.

### What alternatives have you considered?

Manually adding Rescript to projects.

**Comment by Electroid** [comment]
This is something that can be done with a plugin: https://bun.sh/docs/bundler/plugins

We're not likely to add it as a default at this time.

**Comment by ghost** [comment]
> This is something that can be done with a plugin: https://bun.sh/docs/bundler/plugins
> 
> We're not likely to add it as a default at this time.

Thanks, I might work on a plugin for that :)
