### ISSUE TITLE
Using Tailwindcss without build process - Nextjs

### ISSUE THREAD

**Issue by yensubldg** [oven-sh/bun#842]
### What is the problem this feature will solve?

Can use tailwindcss with Nextjs without the [Tailwindcss CLI build process](https://tailwindcss.com/docs/installation)

### What is the feature you are proposing to solve the problem?

Same as npm, yarn with script "dev"

**Comment by rgoomar** [comment]
@yensubldg Do you have an example of what behavior you're looking for? Like what works with `npm` or `yarn` that isn't the intended behavior with `bun`?

If you're looking for a similar workflow to what is described in that doc you linked to, there is a [roadmap](https://github.com/oven-sh/bun/issues/159) item to get an equivalent to `npx`, although that isn't implemented yet:
>  bun subcommand for running npm packages or URLs that may not already be installed. Like `npx`

**Comment by yensubldg** [comment]
When I compile with `yarn `with Nextjs there will be a next file which will contain the compiled css file without having to manually do the `Start the Tailwind CLI build process` so I would suggest automatic execute `build process` instead of having to run it manually or install the `dev`

**Comment by yensubldg** [comment]
I also had some problems with `bun` when installing tailwindcss
When installing with `bun add tailwindcss -d`, then is there any way to launch tailwind init file generation, I tried `bun tailwindcss init`?

**Comment by nachoaldamav** [comment]
A quick workaround for using tailwind in dev without rebuilding the css is using the CDN.

`_app.tsx | jsx`
```jsx
<Head>
   <title>Next.js</title>
   {process.env.NODE_ENV === "development" && (
    <script src="https://cdn.tailwindcss.com" />
   )}
</Head>
```

`package.json`
```json
"scripts": {
    "dev": "bun dev",
    "build": "npm run build:css && next build",
    "build:css": "tailwindcss -o styles/globals.css",
    "start": "next start"
  }
```

**Comment by yensubldg** [comment]
@nachoaldamav great workaround

**Comment by mitchbne** [comment]
Another workaround is to use plain old bash:

Create a file called `dev.sh`:
```sh
#!/bin/bash

bun dev & bun run dev:css
```

Make it executable `chmod 700 dev.sh`

Add the following to your `package.json`:

```json
{
  "scripts": {
    "dev:css": "tailwindcss -o styles/tailwind.css --watch"
  }
}
```

Run `./dev.sh` in your terminal.

Profit 🎉
