### ISSUE TITLE
[Windows] bun doesn't show anything on stdout

### ISSUE THREAD

**Issue by jgranduel** [oven-sh/bun#8423]
### What version of Bun is running?

1.025 canary

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Version :  Prerelease : Canary ( 1407683f9575562e16e90445dd6646f8e40b7880 ) 
[https://github.com/oven-sh/bun/releases/download/canary/bun-windows-x64.zip](https://github.com/oven-sh/bun/releases/download/canary/bun-windows-x64.zip) of 2024-01-23
```
> ./bun.exe --version
<nothing !>
```
 
Previous version :

```
PS7 > bun.exe --version
1.0.23
PS7 > bun.exe --help | select -First 3
Bun is a fast JavaScript runtime, package manager, bundler, and test runner. (1.0.23-canary.24 (3c785c88))

Usage: bun <command> [...flags] [...args]
```

### What is the expected behavior?

bun should show version and help on stdout!

### What do you see instead?

nothing

**Comment by paperclover** [comment]
it works for me but a new build is there by now.

i am on `1.0.25-canary.37+eeb10f3f7`

if you reinstall does it still break?

**Comment by jgranduel** [comment]
No change and still silent with `Canary f1f861fd74e` on same Windows as previous, sorry.

**Comment by jgranduel** [comment]
OK, solved as of today ! Thx
