### ISSUE TITLE
Docs: Add description on how to install specific version

### ISSUE THREAD

**Issue by sewe75** [oven-sh/bun#843]
### What is the problem this feature will solve?

The "Install" section of the README lacks information on how to install a specific release:  
https://github.com/oven-sh/bun#install

### What is the feature you are proposing to solve the problem?

Add a short hint on how to install a specific release:  
```bash
curl -fsSL https://bun.sh/install | bash -s -- bun-v0.1.4
```
  
To avoid the prefix "bun-" and allow to use the release version without prefix change line 65 of `install.sh` from  
```bun_uri="$github_repo/releases/download/${1}/bun-${target}.zip"```  
to  
```bun_uri="$github_repo/releases/download/bun-${1}/bun-${target}.zip"```

**Comment by surajpulloor** [comment]
are you working on this issue or can i take this up

**Comment by sewe75** [comment]
You can take it up - ty

**Comment by sewe75** [comment]
Closed as of comment by @Jarred-Sumner: https://github.com/oven-sh/bun/pull/848#issuecomment-1193697983
