### ISSUE TITLE
bun:ffi corrupts some double values passed as arguments

### ISSUE THREAD

**Issue by jjrv** [oven-sh/bun#8430]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

```
import { dlopen, FFIType } from "bun:ffi";

const { printf } = dlopen("/usr/lib/x86_64-linux-gnu/libc.so.6", {
  printf: { args: [FFIType.cstring, FFIType.f64] }
}).symbols;

printf(new TextEncoder().encode("%.17f\n"), 4);
```

### What is the expected behavior?

Should print:
4.00000000000000000

### What do you see instead?

3.99999999999999956

### Additional information

Adding and removing 0.00000000000001 here:
https://github.com/oven-sh/bun/blob/864a726249115d5d146a54af85d29dc04f093d48/src/js/bun/ffi.ts#L251-L263
is not safe.

There isn't any single floating point value other than 0 that you could replace it with.

Also, if you replace 4 with `-1n` it will print `1`. That's a different bug in the same API function, it's always calling `Math.abs` for no reason.

**Comment by Jarred-Sumner** [comment]
I think we could get away with 0 here
