### ISSUE TITLE
Issue when fetching File/Directory stats via `fs.stat` and viewing the birthtime

### ISSUE THREAD

**Issue by RadhiRasho** [oven-sh/bun#8447]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Fetch files in a directory using readdir (both async and sync fs cause the same issue)
2. use `path` to resolve the routes to each file
3. Fetch `size` and `birthtime` using `fs.stat`
4. print out output of `fs.stat`

The code below should reproduce the same error

```JS
import { readdir, stat } from "node:fs/promises";
import path from "path";

async function list() {
	const files = await readdir("./");
	const promises = files.map(async (file: string) => {
		const route = path.resolve("./", file);

		const { size, birthtime } = await stat(route);

		return {
			"File Name": file,
			"Size (MB)": size,
			"Created At": birthtime,
		};
	});

	const detailedFiles = await Promise.all(promises);
	console.table(detailedFiles);
}

list();
```

### What is the expected behavior?

I should be seeing the below

![image](https://github.com/oven-sh/bun/assets/54078496/1d33f3ca-6769-424d-8ba7-c80486a33790)

Code ran on NodeJS (v20.10.0) using `ts-node`

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/54078496/efea9bef-1a70-46f9-98da-a3be8b3c90fd)

Bun `v1.0.25`

**Comment by AlttiRi** [comment]
- https://github.com/oven-sh/bun/issues/6585

https://github.com/oven-sh/bun/blob/47e7e004b15c2b4a144c4ecab55d43360b43b0ea/src/bun.js/node/types.zig#L1534-L1535
...

**Comment by RadhiRasho** [comment]
Closing as it seem to be a duplicate
