### ISSUE TITLE
[windows] Get `Bun.build()` to work

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#8454]
We need to make the cross-thread stuff work right

**Comment by paperclover** [comment]
```
import { join } from "path";
const x = await Bun.build({
  entrypoints: [join(import.meta.dir, "./test/bundler/fixtures/trivial/index.js")],
});
console.log("here");
await Bun.write("/tmp/bun-build-test-write.js", x.outputs[0]);
```

Event Loop related crash when using bun.write with it

<img width="1062" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/c3453803-37a1-4efc-a261-da326cac2d22">
