### ISSUE TITLE
What is the rationale behind `bun test --only`?

### ISSUE THREAD

**Issue by DaleSeo** [oven-sh/bun#8465]
### What is the problem this feature would solve?

Currently, running `bun test` without the `--only` flag executes all tests/suites, regardless of whether they are marked with `.only()`. This is different from the behavior of Jest and Vitest, which only run tests/suites marked with ﻿`.only()` when no flags are given. Personally, I often use `.only()` to temporarily focus on debugging a specific test/suite. It simply prevents other tests from cluttering my terminal output. However, it feels inconvenient to always use the `--only` flag with Bun's test runner for this purpose.

### What is the feature you are proposing to solve the problem?

I would like to suggest that by default, `bun test` only execute tests/suites marked with `.only()` as Jest and Vitest do. A new flag like `--ignoreOnly` can be introduced to support the current behavior if necessary.

**Comment by aarvinr** [comment]
For anyone who wants to work on this, the code is in [`src/bun.js/test/jest.zig`](https://github.com/oven-sh/bun/blob/main/src/bun.js/test/jest.zig).

**Comment by Electroid** [comment]
Currently, `bun test` does not execute the global scope of every file to discover for usages of `.only`, which is why it requires passing `--only` on startup. This is a technical limitation that we need to refactor, not an intentional developer experience decision.

**Comment by Electroid** [comment]
Duplicate of #7701
