### ISSUE TITLE
Getting spammed "Error: NOTCONN" in console while visiting pages

### ISSUE THREAD

**Issue by jdion84** [oven-sh/bun#8472]
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Honestly I'm not sure how to reproduce this.

I recently updated bun version, but before that, my server would constantly lose connection while visiting pages.

Now, it seems this has been fixed, but instead of the whole server dying, it just says `Error: NOTCONN` in the console.

I'm not sure if this is just a mac thing, I think i read somewhere that this type of issue was only present on macs.

**Comment by Electroid** [comment]
Fixed in https://github.com/oven-sh/bun/commit/2a6388d50bcd9604e1287691cab146b08dbd1011
