### ISSUE TITLE
import.meta.dir returns "/$bunfs/root/" in single-file executable

### ISSUE THREAD

**Issue by ducviet321** [oven-sh/bun#8476]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 5.14.21-150400.24.18-default x86_64 x86_64

### What steps can reproduce the bug?

Create a file test.js with content:
```js
console.log(import.meta.dir)
```

Then build it: `bun build ./test.js --compile --outfile test`
Compare output of running using `bun run test.js` vs `./test`.

Running "./test" gave me result `/$bunfs/root`, which is unusable for my application.

### What is the expected behavior?

Should show current script directory

### What do you see instead?

/$bunfs/root

### Additional information

Although `__dirname` is deprecated, it's still giving me the right directory

**Comment by DoctorGester** [comment]
Same issue, seems there is no way to get the current executable directory for the executable produced from --build --compile?

**Comment by Jarred-Sumner** [comment]
You most likely want to run `process.cwd()` instead. If you want the path to the executable, `process.execPath` or `process.argv0`. 

The original file paths compiled executables came from are not intended to be stored

**Comment by DoctorGester** [comment]
@Jarred-Sumner `process.execPath` works fine in a built executable, however I wanted something which works both in `bun run` mode as well as in a built executable. Currently I'm checking if `import.meta.dir` contains `$bunfs` and switching to `path.dirname(process.execPath)`, maybe that's ok?
