### ISSUE TITLE
`error: �������������������������` (and other variations of this unreadable error) and `error: ENOENT reading "/home/hussein/bun-svelte/node_modules/validator.js"` when using `validator`

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8481]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.1.66-1-lts x86_64 unknown

### What steps can reproduce the bug?

have your `node_modules` up one level like so:

![image](https://github.com/oven-sh/bun/assets/122984423/fdc35ffc-4ed3-4024-b690-ec8d1ff5ff36)

and then simply run the following code like in the picture:
```ts
import validator from "validator";
validator.isStrongPassword;
```
the error goes away if you put your `node_modules` near the `index.ts` however.

### What is the expected behavior?

for it to work

### What do you see instead?

errors in title

### Additional information

i also got this weird thing: `error: �t&�t&�t&�t&�t&�t&�t&�t&�`

**Comment by huseeiin** [comment]
doing `rm -rf node_modules`, `bun i` fixed it but its still worth looking into.

**Comment by btakita** [comment]
This error does not have the `code` prop populated. The `code` should be `ENOENT` to be compatible with NodeJS.

Instead, the `message` prop contains the entire string.

```
{
  err: error: ENOENT reading "/home/me/project/dist/server--dev/index.server-2ODBLBI6.js",
  "err.code": undefined,
  "err.cause": undefined,
  "err.message": "ENOENT reading \"/home/me/project/dist/server--dev/index.server-2ODBLBI6.js\"",
}
error: ENOENT reading "/home/me/project/dist/server--dev/index.server-2ODBLBI6.js"
```

**Comment by huseeiin** [comment]
closing as i cannot reproduce this in latest bun
