### ISSUE TITLE
Integer Overflow on large file sizes when using fs.stat()

### ISSUE THREAD

**Issue by rhld16** [oven-sh/bun#849]
### Version

0.1.5

### Platform

Linux ~ 5.13.0-1034-oracle #40~20.04.1-Ubuntu SMP Thu Jun 9 14:02:29 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### What steps will reproduce the bug?

```
fs.stat(apiData.path, (err, stats) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log("stats: " + stats.size);
});
```

### What do you see instead?

Inspecting file size of any file larger than 2GB will result in a negative number. This doesn't apply to Bun.file().size.

**Comment by Jarred-Sumner** [comment]
Oh wait, this is on Linux Arm64 right

The issue is here:

https://github.com/oven-sh/bun/blob/main/src/bun.js/node/syscall.zig#L28

libc stat is probably 32 bit instead of 64 bit ints
