### ISSUE TITLE
rename "macros" to "macro" in types

### ISSUE THREAD

**Issue by William-McGonagle** [oven-sh/bun#851]
### Version

0.1.4

### Platform

Darwin mcgonaglew-macbookPRO 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

1. Run the following code in bun.

```javascript
var object = {
    helloooooooo: {
      message: [12345],
    },
  };

const transpiler = new Bun.Transpiler({
    loader: "tsx",
    define: {
      "process.env.NODE_ENV": JSON.stringify("development"),
      user_undefined: "undefined",
    },
    platform: "bun",
    macro: {
      inline: {
        whatDidIPass: `${import.meta.dir}/inline.macro.js`,
      },
      react: {
        bacon: `${import.meta.dir}/macro-check.js`,
      },
    },
  });

const output = transpiler.transformSync(
`
import {whatDidIPass} from 'inline';

export function foo() {
    return whatDidIPass();
}
`,
    object
);

console.log(output);
```

This piece of code should have the correct output.

### How often does it reproduce? Is there a required condition?

There are no required conditions to reproduce this.

### What is the expected behavior?

The expected behavior is for the code to run correctly when using the property name 'macros' instead of 'macro'. 

The correct behavior is this:

```javascript
export function foo() {
  return {
    helloooooooo: {
      message: [
        12345
      ]
    }
  };
}
```

### What do you see instead?

If you switch 'macro' to 'macros' as it says is the correct property name in the typings and documentation, there will be an incorrect output. If you follow the test files, like the code in the reproduction section does, it runs correctly. 

The incorrect input will look like this:

```javascript

import {whatDidIPass} from "inline";
export function foo() {
  return whatDidIPass();
}

```

**Comment by colinhacks** [comment]
Fixed by https://github.com/oven-sh/bun/pull/1972/commits
