### ISSUE TITLE
`Request.clone()` does not clone body

### ISSUE THREAD

**Issue by danthegoodman1** [oven-sh/bun#8515]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

macOS

### What steps can reproduce the bug?

clone an incoming request

### What is the expected behavior?

the body is cloned

### What do you see instead?

blank body

**Comment by danthegoodman1** [comment]
https://github.com/oven-sh/bun/pull/6468 related

**Comment by Electroid** [comment]
Duplicate of #1381
