### ISSUE TITLE
dyld[50957]: missing symbol called

### ISSUE THREAD

**Issue by 0xdeployer** [oven-sh/bun#8527]
### What version of Bun is running?

1.0.25

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Install node-canvas in a typescript project. Try to build and run, or run project using Bun

### What do you see instead?

Getting error `dyld[50957]: missing symbol called`

**Comment by Lukasz-pluszczewski** [comment]
I have the same issue, it's still there in v1.1.0 (canvas@2.11.2).

The minimum code that causes the error:
```ts
import { createCanvas } from 'canvas';

createCanvas(100, 100);
```

And the error itself looks like this on my machine:
```
dyld[34691]: missing symbol called
```

**Comment by Jarred-Sumner** [comment]
@Lukasz-pluszczewski please see https://github.com/oven-sh/bun/issues/5835

**Comment by Jarred-Sumner** [comment]
We are tracking this in #4290. 

@190n is actively working on supporting V8 C++ APIs in Bun.

Please follow along in #4290
