### ISSUE TITLE
ParseInt returning wrong result

### ISSUE THREAD

**Issue by mathiasrw** [oven-sh/bun#8534]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 21.6.0 arm64 arm

### What steps can reproduce the bug?

Run parseint on a number smaller than 1e-6

bun -e 'console.log(parseInt(0.0000005))'

<img width="394" alt="image" src="https://github.com/oven-sh/bun/assets/1063454/0701a371-71cc-41e5-b56e-5deaf8ead625">

### What is the expected behavior?

It returns zero. as that is the closest int

### What do you see instead?

The response is 5 (instead of zero)

**Comment by Jarred-Sumner** [comment]
some quick investigation: parsing the double returns something close to the expected value
<img width="549" alt="image" src="https://github.com/oven-sh/bun/assets/709451/e0ee2e3e-d43f-4cdf-b77f-2400ad724210">

It appears to be a bug in the Zig standard library, note the 5 in the buffer there:
<img width="298" alt="image" src="https://github.com/oven-sh/bun/assets/709451/dd2a4e44-fbf6-4bda-8095-7ac8eeb0a594">

In `std.fmt.formatFloatDecimal`.

**Comment by Jarred-Sumner** [comment]
actually, this is a JSC bug.

The following prints `5` in `jsc` CLI

```js
print(parseInt('0.0000005'))
```

**Comment by Jarred-Sumner** [comment]
Actually, turns out this is not a bug. It is the defined behavior of `parseInt` when given a number as input.

```
node -e 'console.log(parseInt(0.0000005))'
bun -e 'console.log(parseInt(0.0000005))'
```

Both return `5`.


```js
bun -e 'console.log(parseInt("0.0000005"))'
node -e 'console.log(parseInt("0.0000005"))'
```

This prints 0 as expected.

**Comment by mathiasrw** [comment]
Learning every day...
