### ISSUE TITLE
bug: failed to install local packages

### ISSUE THREAD

**Issue by Namchee** [oven-sh/bun#8535]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.5.0-15-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Prepare a local package to install and a fresh `bun init` project
2. Run `bun install <path_to_local_package>`
3. Package failed to resolve with `Cannot find module "<package_name>" or its corresponding type declarations.`

### What is the expected behavior?

The package should be installed correctly, since I have no problem doing this with `pnpm` and `npm`.

### What do you see instead?

Package failed to resolve correctly.

**Comment by Jarred-Sumner** [comment]
Please provide a complete reproduction. There is no code to run here.

**Comment by Namchee** [comment]
My bad, seems like the problem is due to my buggy package setup. Closed.
