### ISSUE TITLE
Bun Expo Adapter

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#8536]
### What is the problem this feature would solve?

This is more of like an ecosystem feature. It would be nice if we had a way to host Expo api routes using Bun serve. Currently, in the docs there is an [express implementation](https://docs.expo.dev/router/reference/api-routes/#express). The source code of the express adapter used in the express implementation can be found [here](https://github.com/expo/expo/blob/2eb32ff30e17a773b04f9bb00bc5c9c56b752285/packages/%40expo/server/src/vendor/express.ts).  I would guess there is a way to translate the express implementation to Bun.serve, however, I have no idea how to do so. It would be great if someone with more experience in express could help in this.

### What is the feature you are proposing to solve the problem?

If this is implemented, it will be possible to use Bun to host full-stack web and native react native apps.

### What alternatives have you considered?

Using express (not as fast or good dev exp)

**Comment by itsyoboieltr** [comment]
I found a very hacky way to make it work:

1. step: create `index.ts` in root as below:

```ts
import path from 'path';

const WebRequest = Request;
const WebResponse = Response;

const { createRequestHandler } = await import('@expo/server/build');
const { ExpoRequest } = await import('@expo/server/build/environment');

// Expo overrides the global Request and Response, so we need to override them back
global.Request = WebRequest;
global.Response = WebResponse;

const handleRequest = createRequestHandler(
  path.join(import.meta.dir, 'dist/server')
);

Bun.serve({
  async fetch(req) {
    const url = new URL(req.url);
    if (url.pathname.includes('/_expo/static')) {
      const file = Bun.file(`dist/client${url.pathname}`);
      return new Response(file);
    }
    const request = new ExpoRequest(url.href, req);
    const response = await handleRequest(request);
    // The any is needed, otherwise it throws type error, but it still works
    return new Response(await response.text(), response as any);
  },
});
```
`Additional comments about where bun fails`: The line `installGlobals();` inside  `@expo/server/install.js`, causes the bun server to fail. Interestingly, it does not have much inside: just some global overrides for Request and Response. After re-overriding the Request and Response to their original implementations, the bun server started working.

3. step: `bun index.ts`
4. step: your full-stack web and native app should be running in the browser using expo api routes :)

**Comment by Electroid** [comment]
Thanks for the suggestion! I think we will leave this to the community to decide, it isn’t something we would have the bandwidth to maintain.
