### ISSUE TITLE
Have bun.$ reject its promise if exitCode is not zero

### ISSUE THREAD

**Issue by mathiasrw** [oven-sh/bun#8544]
### What is the problem this feature would solve?

Shell commands via bun.$ are always resolving so error handling needs to happen "manually" by looking at the errorCode in the response. The impact is that I cant use the expected way to deal with errors for async functions. 

It is not so much that error handling cant be done checking the value of errorCode, but it breaks with the philosophy of how things are done in JS.

### What is the feature you are proposing to solve the problem?

I propose changing the behaviour so results from bun.$ rejects when the value of errorCode is not-zero. This means that the below code would return "Command failed" as the binary echoXYZ could not be found. (This currently returns "Command ran OK" with Bun v 1.0.25)

```js
import { $ } from 'bun';

$`echoZYX Hello world`
	.then(o => console.log('Command ran OK: ', o))
	.catch(o => console.error('Command failed: ', o))
```

### What alternatives have you considered?

You can polifil this behaviour by wrapping $ like this

```js
import { $ as _$ } from 'bun';

const $ = async function (...args) {
	const result = await _$(...args);
	if (result.exitCode !== 0) {
		return Promise.reject(result);
	}
	return Promise.resolve(result);
};
```

**Comment by Electroid** [comment]
This would for sure be a breaking change, that said, I’m curious what @zackradisic thinks.

**Comment by zackradisic** [comment]
I think it makes sense to throw on non-zero exit code, and provide something like `.nothrow()` (this is what [zx does](https://google.github.io/zx/process-promise#nothrow)) if you don't want it to throw:

```typescript
import { $ } from 'bun'

// Won't throw on errors
await $`echo hsdfjsldkjf`.nothrow()

// Set the option globally for all shell invocations
$.throws(false)
```

**Comment by pfgithub** [comment]
Right now this is especially a problem for `.text()`

```ts
import {$} from "bun";
await $`ls abc`.text();
```

This just returns `""` with no indication that the command failed and no way to get that information out.

To handle it correctly, `.text()` can't be used at all and instead you have to parse the ShellOutput stdout manually.

**Comment by rhyek** [comment]
migrating to bun shell from execa and this is a pain point with my scripts that have many shell commands where i expect execution to stop and exit on any unexpected error.

**Comment by rhyek** [comment]
this helper function i wrote works for me and maintains the same API:
```typescript
import { $, type Shell } from 'bun';

const $$: Shell = ((...params: Parameters<Shell>) => {
  const rtrn = $(...params);
  const originalThen = rtrn.then.bind(rtrn);
  rtrn.then = (onfulfilled, onrejected) => {
    return originalThen((shellOutput) => {
      if (shellOutput.exitCode !== 0) {
        return onfulfilled!(
          Promise.reject(new Error(shellOutput.stderr.toString())) as any,
        );
      } else {
        return onfulfilled!(shellOutput);
      }
    }, onrejected);
  };
  return rtrn;
}) as any;

await $$`echo simple`;
await $$`echo ${'simple2'}`;
await $$`echo "hello, $MESSAGE"`.env({
  MESSAGE: 'there',
});
await $$`cat nonexistant`; // should error
```
prints and exits with non-zero:
```bash
❯ ./run-wait-for-db.ts
simple
simple2
hello, there
cat: nonexistant: No such file or directory
 8 |   const originalThen = rtrn.then.bind(rtrn);
 9 |   rtrn.then = (onfulfilled, onrejected) => {
10 |     return originalThen((shellOutput) => {
11 |       if (shellOutput.exitCode !== 0) {
12 |         return onfulfilled!(
13 |           Promise.reject(new Error(shellOutput.stderr.toString())) as any,
                              ^
error: cat: nonexistant: No such file or directory

      at /Users/carlos/Dev/projeect/run-wait-for-db.ts:13:26
~/Dev/project git:(develop) ✗ 
❯ 
```

i'm sure this can be improved.

**Comment by Electroid** [comment]
We do plan to make this change before Bun v1.1. We will communicate this as a breaking change

**Comment by Electroid** [comment]
Going to re-open until we make this the default behaviour.

**Comment by ianwalter** [comment]
@Electroid What about the `$.throws(false)` suggestion from @zackradisic ?

Seems like it fits nicely with the API, no?
