### ISSUE TITLE
Request constructor does not support body being an async iterable

### ISSUE THREAD

**Issue by HCanber** [oven-sh/bun#8546]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Node's `Request` constructor supports the `body` property being an iterable, i.e. `{ [Symbol.asyncIterator]: ... }`, for example an `AsyncGenerator`.

Bun doesn't!

## To reproduce

Put this code in `index.mjs`:

``` js
const asyncGenerator = (async function* () {
  yield "This is the first chunk.";
  yield "The second chunk.";
  yield "The third chunk.";
})();

const req1 = new Request("http://localhost:3000/", {
  method: "POST",
  body: asyncGenerator,
  duplex: "half"
});

console.log(await req1.text())
```

### What is the expected behavior?

Expected output: `This is the first chunk.The second chunk.The third chunk.`

Executing `node index.mjs` will output this.

### What do you see instead?

Output from `bun index.mjs`: `[object AsyncGenerator]`

## Where this is used

Qwik uses async generators as body: https://github.com/BuilderIO/qwik/blob/c52c41520db418465108a0002e2a0ed01ef1cec8/packages/qwik-city/middleware/node/http.ts#L63

Currently bun can't be used with qwik if `server$` calls are made as these are handled using async generators.

## Support in node.js

I can't find anything in the fetch API spec about supporting `AsyncGenerator` or async iterables but it seems like node nevertheless supports it. Given that I've found the correct code :)

In [extractBody()](https://github.com/nodejs/node/blob/v21.x/deps/undici/src/lib/fetch/body.js#L203) called by [Request.ctor](https://github.com/nodejs/node/blob/v21.x/deps/undici/src/lib/fetch/request.js#L467), if `body` is an object with a `Symbol.asyncIterator` property (i.e. an async iterable) it's converted to a `ReadableStream` and used from there on.

**Comment by Electroid** [comment]
Fixed in [Bun v1.0.27](https://bun.sh/blog/bun-v1.0.27#stream-response-bodies-using-async-generators)
