### ISSUE TITLE
Docker workflow missing credentials

### ISSUE THREAD

**Issue by theotterlord** [oven-sh/bun#855]
### What steps will reproduce the bug?

See this run [`2722127295`](https://github.com/oven-sh/bun/actions/runs/2722127295)

### What do you see instead?

Username and password need to be provided.

### Additional information

They must be added to the repository secrets by a repo maintainer

**Comment by Electroid** [comment]
Fixed for the next release.

**Comment by theotterlord** [comment]
Thanks!

So glad this has been fixed. I deploy a couple of bun apps using docker, so it's genuinely useful.
