### ISSUE TITLE
Reload .env with --watch and --hot

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#8554]
### What is the problem this feature would solve?

obsolete .env, after it is changed during the program is running.

### What is the feature you are proposing to solve the problem?

Update variables coming from .env file when it changes. I guess either the .env should be just reloaded everytime the main file changes, or just watch the .env separately.

### What alternatives have you considered?

re-running the program manually after changes are made

**Comment by paperclover** [comment]
it'd be interesting if this on windows could peek the system environment if modified through the GUI. i see limited uses of that feel limited to me, but it'd be a neat touch.

**Comment by Jarred-Sumner** [comment]
I'm pretty sure this is a duplicate issue

**Comment by paperclover** [comment]
Duplicate of #2521
