### ISSUE TITLE
Add "--trust" argument to "bun add" command to add the dependency to "trustedDependencies"

### ISSUE THREAD

**Issue by pierre-cm** [oven-sh/bun#8556]
### What is the problem this feature would solve?

When adding a new dependency via `bun add` command, `postinstall` script is not executed by default. In most cases, `postinstall` script execution is necessary to have the dependency properly installed. 

Currently, the only solution is to manually add the dependency to package.json `trustedDependencies` list before adding it via bun cli. I understand that this is intentional, and I share the security concerns this feature aims to address. However, it can be somewhat inconvenient having to modify the package.json file manually everytime.

### What is the feature you are proposing to solve the problem?

Add a `--trust` flag to `bun add` command that automatically adds the dependency to `trustedDependencies` in package.json before installing the dependency.

**Comment by paperclover** [comment]
im surprised this doesnt have an issue already open. this was something i said was a blocker for trustedDependencies but it seems it was never included as a part of that.

**Comment by dylan-conway** [comment]
added in #8943
