### ISSUE TITLE
`bun dev` is not working out of the box for already existing `react` projects [WSL]

### ISSUE THREAD

**Issue by FrameMuse** [oven-sh/bun#856]
### Version

1.5 - 2.2

I will update version as I test it.

### Platform

WSL2 - Ubuntu 20.04.4 LTS

### What steps will reproduce the bug?

- Install bun
- Open existing `react` project folder, for example, [this one](https://github.com/FrameMuse/react-template)
- Type `bun bun ./src/index.ts` to generate a bundle for the entry point
- Type `bun dev` to start dev sever
- See it started successfully
- Open the link the project is served
- See it serves successfully
- See it doesn't work with `react` properly

### How often does it reproduce? Is there a required condition?

Always. No.

### What is the expected behavior?

Existing `react` project should be served by `bun dev` as `npm start` do.

### What do you see instead?

- `Bun` sees only `index.html`
- It doesn't handle `index.html` properly - it doesn't evaluate variables like `%PUBLIC_URL%`
- It doesn't call to `./src/index.ts`, which was bundled previously
- Console says `manifest.json` is not there even though it's in `public` as well as `index.html`
![image](https://user-images.githubusercontent.com/53980482/180650143-ba64bcbc-c6c3-4376-8ee4-394ae2cf532c.png)

### Additional information

There is probably related issue #723

**Comment by prime-vimihi** [comment]
Facing same issue.

**Comment by Bhardwaj-Raghav** [comment]
Same issue for Next.js Project as well. 
![image](https://user-images.githubusercontent.com/47305069/181876069-36b5a015-70a3-4d0e-a0b4-0759a3e2130e.png)

**Comment by FrameMuse** [comment]
As for `0.2.0` version - still not fixed

**Comment by FrameMuse** [comment]
The behavior has slightly changed: now it doesn't mark urls as `404`, but mark as `302`.
![image](https://user-images.githubusercontent.com/53980482/195860307-de014083-2fff-4de5-a4f3-3e4a54ebaf82.png)

I wrote `alert(1)` in the bounded `./src/index.ts` file and after serving it again - it seems any code is not being invoked.
But on startup it had detected that there is modules that can't be resolved.

**Comment by Electroid** [comment]
Sorry about the issues you're running into. We're growing the team and working to prioritize ecosystem compatibility, like with React.

**Comment by Israel-Laguan** [comment]
Same issue with react app

Tried to comment on the manifest line in the `public/index.html` without success
![image](https://user-images.githubusercontent.com/36519478/201492906-c290c294-553c-4063-9b37-a5c77092a408.png)

Erased all the files but `public/index.html` without success 😢

**Comment by kacogg5** [comment]
Having this issue with v0.5.8. Work around is using `bun react-scripts start` instead of `bun dev`

**Comment by FrameMuse** [comment]
> bun react-scripts start

That works!

**Comment by birkskyum** [comment]
Since the `bun dev` dev server is removed, this ticket is obsolete.
