### ISSUE TITLE
Windows bun create next-app crash

### ISSUE THREAD

**Issue by snatvb** [oven-sh/bun#8573]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

I've used: `$ bun create next-app`

I've got:
```
uh-oh: cast causes pointer to be null
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.26-canary.73 (17fc1e7b) Windows x64
CreateCommand:
Elapsed: 10ms | User: 0ms | Sys: 0ms
RSS: 23.51MB | Peak: 23.51MB | Commit: 65.90MB | Faults: 5882
----- bun meta -----

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 34252 panic: cast causes pointer to be null
???:?:?: 0x7ff733729f96 in ??? (bun.exe)
???:?:?: 0x7ff73372db44 in ??? (bun.exe)
???:?:?: 0x7ff73372c304 in ??? (bun.exe)
???:?:?: 0x7ff7337b36cc in ??? (bun.exe)
???:?:?: 0x7ff73354151c in ??? (bun.exe)
???:?:?: 0x7ff735d8ba83 in ??? (bun.exe)
???:?:?: 0x7ffa3ca6257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa3d80aa57 in ??? (ntdll.dll)
```

### What is the expected behavior?

No crash

### What do you see instead?

Crash by null pointer exception

**Comment by jdion84** [comment]
Windows isn't fully supported yet (coming in like a week I believe). 

You need to install bun through WSL and run it through that:

https://bun.sh/docs/installation#windows

**Comment by paperclover** [comment]
Duplicate of #8045 which is already resolved.

**Comment by snatvb** [comment]
@jdion84 yes, I do, just thought needs some help with debug this case to better support win version :)
