### ISSUE TITLE
`Bun.file.slice` does not work

### ISSUE THREAD

**Issue by Jakisundays** [oven-sh/bun#8581]
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 21.4.0 x86_64 i386

### What steps can reproduce the bug?

**Steps to Reproduce the Bug:**

1. **Load an Audio File:**
   Start by loading a full audio file (e.g., an MP3 file) into your program using `Bun.file()` or a similar method.

   ```javascript
   const file = Bun.file("audio.mp3");
   ```

2. **Determine the File Size and Split it into Chunks:**
   Calculate the size of each chunk by dividing the total file size by a number (e.g., 4), and then split the file into several chunks using `file.slice()`.

   ```javascript
   const fileSize = file.size;
   const partSize = Math.ceil(fileSize / 4);
   const chunks = [
     file.slice(0, partSize),
     file.slice(partSize, partSize * 2),
     file.slice(partSize * 2, partSize * 3),
     file.slice(partSize * 3, fileSize)
   ];
   ```

3. **Write Chunks to the Filesystem and Read their Sizes:**
   Write each chunk to the filesystem and then immediately read its size using `Bun.file(path)` and `fileMp3.size`.

   ```javascript
   for (const chunk of chunks) {
     const id = crypto.randomUUID();
     const path = `assets/${id}.mp3`;
     Bun.write(path, chunk);
     
     const fileMp3 = Bun.file(path);
     console.log(`🎵 The size of the MP3 file is: ${fileMp3.size} bytes 📏`);
   }
   ```

4. **Observe the Incorrect File Sizes:**
   Notice that the size logged for each chunk is not the expected fraction of the original file, but rather the size of the entire original audio file.

### What is the expected behavior?

Each chunk’s fileMp3.size should display the size of that specific chunk, which is a portion of the original file size.

### What do you see instead?

Instead of seeing the expected behavior where each chunk's `fileMp3.size` reflects its individual size (a fraction of the original file size), the observed behavior is that `fileMp3.size` for each chunk is incorrectly showing the size of the entire original audio file. In essence, despite splitting the file into smaller parts, the size reported for each part is equal to the total size of the full audio file.

This is evident in the console logs where each chunk, expected to be smaller and different in size, is logged with the same file size, which matches the size of the original, unsplit file:

```
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
```

Here, `7163309 bytes` is the size of the entire original audio file, not the individual chunks, which should be smaller and approximately one fourth of this size, assuming an equal split.

### Additional information

**Code**

```javascript
// This function returns a promise that resolves after a delay of two seconds.
async function waitForTwoSeconds(): Promise<void> {
  return new Promise<void>((resolve) => {
    // Set a timeout for 2000 milliseconds (2 seconds)
    setTimeout(() => {
      resolve(); // Resolve the promise after the timeout
    }, 2000);
  });
}

// Immediately-invoked function expression (IIFE) to handle async operations
(async () => {
  // Load an MP3 file using Bun.file and log its details
  const file = Bun.file("audio.mp3");
  console.log({ file });
  const fileSize = file.size;
  console.log(`📁 The file size is: ${fileSize} bytes 📏`);

  // Calculate the size of each chunk (1/4th of the total file size)
  const partSize = Math.ceil(fileSize / 4);

  // Split the file into four parts
  const part1 = file.slice(0, partSize);
  const part2 = file.slice(partSize, partSize * 2);
  const part3 = file.slice(partSize * 2, partSize * 3);
  const part4 = file.slice(partSize * 3, fileSize);

  // Array to store the paths of the transcribed files
  const pathsToTranscribe: string[] = [];

  // Iterate through each chunk
  for (const chunk of [part1, part2, part3, part4]) {
    // Generate a random unique ID for each chunk
    const id = crypto.randomUUID();
    // Create a path for the chunk in the assets folder
    const path = `assets/${id}.mp3`; // Path where chunk is to be saved

    // Log the size of the current chunk
    console.log(`📄 Chunk size: ${chunk.size} bytes 📏`);
    // Write the chunk to the file system at the specified path
    Bun.write(path, chunk);

    // Add the path of the saved chunk to the array
    pathsToTranscribe.push(path);
  }

  // Wait for two seconds before proceeding
  await waitForTwoSeconds();

  // Iterate through each path in the array
  pathsToTranscribe.forEach((path) => {
    // Load each chunk as a file
    const fileMp3 = Bun.file(path);
    // Log the size of the chunk; waiting ensures the correct size is retrieved
    console.log(`🎵 The size of the MP3 file is: ${fileMp3.size} bytes 📏`);
  });
})();
```

**Console Logs**
The `fileMp3.size` for each chunk is incorrectly showing the size of the entire original file. Here are the console logs for reference:

```
{
  file: FileRef ("audio.mp3") {
    type: "audio/mpeg"
  }
}
📁 The file size is: 7163309 bytes 📏
📄 Chunk size: 1790828 bytes 📏
📄 Chunk size: 1790828 bytes 📏
📄 Chunk size: 1790828 bytes 📏
📄 Chunk size: 1790825 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
🎵 The size of the MP3 file is: 7163309 bytes 📏
```

**Comment by truongan07** [comment]
You did get it correctly work ?
