### ISSUE TITLE
Should we use @types/bun or bun-types package?

### ISSUE THREAD

**Issue by bjesuiter** [oven-sh/bun#8585]
### What is the issue?

The bun website at https://bun.sh/guides/runtime/typescript 
says: 

> To install TypeScript definitions for Bun's built-in APIs in your project, install @types/bun.

But the version of this package is at 1.0.4, compared to bun-types, which corresponds with the current bun version 1.0.25. 
Also, bun-types seems to be directly supported by oven, which makes it seem very legit. 

Which one should we use? 

### Where did you find it?

https://bun.sh/guides/runtime/typescript

**Comment by bjesuiter** [comment]
Additional finding: 

the bun-types package does not lead to ts language server being able to find the Bun namespace, 
but @types/bun does. 

Not sure why this is.

**Comment by raulfdm** [comment]
related: https://github.com/oven-sh/bun/issues/8301

**Comment by jdion84** [comment]
Using `bun init -y` adds the following to `package.json`:

```json
  "devDependencies": {
    "@types/bun": "latest"
  },
```

So go with the `latest` of `@types/bun`.

**Comment by Jarred-Sumner** [comment]
`@types/bun` is recommended
