### ISSUE TITLE
execSync doesn't work on Windows

### ISSUE THREAD

**Issue by LStan** [oven-sh/bun#8588]
### What version of Bun is running?

1.0.26-canary.101+2d9db9b28

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Create a file:
```
const { execSync } = require("child_process");

execSync("echo")
```

run:
`bun test.js`

### What is the expected behavior?

Run without errors

### What do you see instead?

```
error: '\"echo\"' is not recognized as an internal or external command,
operable program or batch file.

   errno: -1
   code: "1"
 syscall: "spawnSync"
   path: "cmd.exe"

      at new SystemError (node:child_process:790:27)
      at node:child_process:173:47
      at node:child_process:219:45
```

### Additional information

It works with `node`. 
`bun` in WSL also works

**Comment by paperclover** [comment]
this wrapping of quotes is very interesting

**Comment by paperclover** [comment]
smaller reproduction. this should not fail
```
const y = Bun.spawnSync({
    cmd: ['cmd', '/c', '"echo" hello world'],
})
console.log(y.stdout.toString('utf8'));
console.log(y.stderr.toString('utf8'));
```

**Comment by nektro** [comment]
Fixed in https://github.com/oven-sh/bun/pull/10193
