### ISSUE TITLE
`fs.copyFile` produces incorrect permissions

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#859]
### Version

0.1.5

### Platform

Linux paperback 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

```sh
touch test.txt
echo "require('fs').copyFileSync('test.txt', 'copy.txt')" > program.mjs
bun program.mjs
stat copy.txt
```

### How often does it reproduce? Is there a required condition?

Every Time.

### What is the expected behavior?

both files have same permissions: `0644`/`-rw-r--r--`

### What do you see instead?

`copy.txt` ends up with `1101`/`---x-----t`

### Additional information

does not seem to take permissions into account at all unless the initial permissions deny the self from copying. contained contents seem to be fine.

**Comment by Jarred-Sumner** [comment]
Fixed
