### ISSUE TITLE
`Bun.gzipSync` should take `BunFile`

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8593]
### What is the problem this feature would solve?

proposal: Bun.gzipSync/gunzipSync should accept `BunFile` (as well as `TypedArray`, `ArrayBufferLike`, `Blob`, `BlobPart[]`, and `Buffer`? to be consistent with `BunFile`) as an argument

### What is the feature you are proposing to solve the problem?

it would shortcut:

```ts
Bun.write("./file.gz", Bun.gzipSync(await Bun.file("./file").arrayBuffer()));
```

to:

```ts
Bun.write("./file.gz", Bun.gzipSync(Bun.file("./file")));
```

another issue is that in TypeScript only `Uint8Array` is allowed even though `ArrayBuffer` and `string` (and others?) work in runtime.

**Comment by Jarred-Sumner** [comment]
We will add .compress and .uncompress to Bun.file instead of more polymorphism for Bun.gzipSync

**Comment by huseeiin** [comment]
> We will add .compress and .uncompress to Bun.file instead of more polymorphism for Bun.gzipSync

understood. nice :)
