### ISSUE TITLE
Statically link Visual C++ Redistributable on Bun for Windows (`-MT`)

### ISSUE THREAD

**Issue by barziahmed** [oven-sh/bun#8598]
### What is the problem this feature would solve?

Hello, 
I'm on Windows 11, and when I try to use Bun, it doesn't work and asks for Visual C++. Due to some reasons, I don't want to install Visual C++. 

Deno works without Visual C++ or any other third-party package. So I hope Bun can achieve same. 

I use Bun from downloading [bun-windows-x64.zip](https://github.com/oven-sh/bun/releases/download/canary/bun-windows-x64.zip) Canary version.

### What is the feature you are proposing to solve the problem?

Finding a way to discard visual c++ requirement.

**Comment by paperclover** [comment]
Work started in #8194

**Comment by paperclover** [comment]
> I don't want to install Visual C++.

This is a very silly decision. But I do want the binary to not depend on the C++ redist. I'm still surprised windows ships without this.
