### ISSUE TITLE
[Imprv] Get rid of `usingnamespace`

### ISSUE THREAD

**Issue by nitrogenez** [oven-sh/bun#8603]
In Zig the usage of `usingnamespace` might be dangerous in some cases, it's worsening code readability, and might raise compiler errors due to it's uncerain behaivour. So, the request is to banish `usingnamespace` into the shadow realm as soon as possible, and where it is possible, so the transition to next Zig releases would be smoother.

**Comment by Jarred-Sumner** [comment]
No
