### ISSUE TITLE
Separate README into documentation pages

### ISSUE THREAD

**Issue by leap0x7b** [oven-sh/bun#865]
### Description of the problem

Putting the entire documentation in the README makes it more cluttered, it's probably best to separate them into pages.

**Comment by stefanprokopdev** [comment]
Hey @leapofazzam123 :wave: Can I help you to separate the documentation into pages and structure it? I would like to get involved in the project and I think documentation is a good first step for me - to help you and to learn more.

We can for example start with separating the chapters under the "Table of contents" to their own folder and files.

I see there already is a `docs` folder in the repository do you have any idea where to put the files or how to structure it? It looks to me the files inside the `docs` directory are not related to the documentation for users (README). But maybe I am wrong.

**Comment by stefanprokopdev** [comment]
Hey @Jarred-Sumner :wave: Can I help you to separate the documentation into pages and structure it? I would like to get involved in the project and I think documentation is a good first step for me - to help you and to learn more.

We can for example start with separating the chapters under the "Table of contents" to their own folder and files.

I see there already is a docs folder in the repository do you have any idea where to put the files or how to structure it? It looks to me the files inside the docs directory are not related to the documentation for users (README). But maybe I am wrong.

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign it to me

**Comment by Electroid** [comment]
We've started to work on the official documentation, it will be moved out of the README and onto a proper website. Stay tuned! 👀
