### ISSUE TITLE
bun build with --sourcemap=external does not include the source map url

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#8655]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

running `bun build` with `--sourcemap=external`

### What is the expected behavior?

include the sourceMappingURL at the end of the bundled file

### What do you see instead?

nothing

**Comment by Electroid** [comment]
Duplicate of #3325
