### ISSUE TITLE
`Response` does not support custom `statusText`

### ISSUE THREAD

**Issue by sstur** [oven-sh/bun#866]
### Version

0.1.5

### Platform

Darwin computer.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run the following code:
```ts
const response = new Response('', {
  status: 418,
  statusText: 'I like tea',
});

console.log('statusText:', response.statusText);
```

Notice the output is blank. The value of `response.statusText` is an empty string, when it should be "I like tea".

If you run that in Safari or Chrome, you'll get the correct statusText, but in Bun it's an empty string.

### How often does it reproduce? Is there a required condition?

Very simple repro; no required conditions.

### What is the expected behavior?

Resulting response object should have statusText that was provided when constructing it.

### What do you see instead?

Empty string.

**Comment by Electroid** [comment]
Fixed by #6151
