### ISSUE TITLE
support two different websocket paths

### ISSUE THREAD

**Issue by terrablue** [oven-sh/bun#8666]
### What is the problem this feature would solve?

I have an application with two websocket routes, e.g. `/chat` and `/twitter`, each with its different logic for `message`, `open` etc.

It's currently hard to branch within the `websocket` object passed to `Bun.serve`.

### What is the feature you are proposing to solve the problem?

Expose the original request in `ServerWebSocket` or any other kind of discriminator that would allow userland to distinguish between sockets used for two or more different routes.

### What alternatives have you considered?

Monkeypatching ServerWebSocket on `open`.

**Comment by Electroid** [comment]
You can set custom data on the WebSocket within the `fetch` function. Based on the route you could set different data and branch off of that.

https://bun.sh/guides/websocket/context
