### ISSUE TITLE
twilio client hangs

### ISSUE THREAD

**Issue by AndrewBarba** [oven-sh/bun#8673]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```typescript
import twilio from 'twilio'

await twilio().messages.get('xyz').fetch().catch(() => null)

console.log('Never gets here...')
```

### What is the expected behavior?

The http request completes (success or error) and the log is reached

### What do you see instead?

The program hangs when issuing the `fetch()`

**Comment by wwelder** [comment]
#5642 #7260 related and probably the same bug?

**Comment by AndrewBarba** [comment]
Twilio lib uses Axios. So im inclined to say all same bug. Not sure how reproducible the other issues are, the one I have here is very reproducible so hopefully easy enough to debug

**Comment by Electroid** [comment]
Duplicate of #8673

**Comment by Electroid** [comment]
We will fix this, just consolidating into 1 issue.

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5642
