### ISSUE TITLE
Permission issue, also bun --watch forgot reload the socket for e.g.

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#8680]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64 | Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
import express from 'express'
const app = express();

app.listen(80, () => console.log('running'))
```

### What is the expected behavior?

Normal reload or load the script

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/130649230/7d3b7c34-6801-4e11-a107-0b6b8f44bb83)
![image](https://github.com/oven-sh/bun/assets/130649230/1efeb414-0864-4985-a0f4-2d69a76c1a42)
![image](https://github.com/oven-sh/bun/assets/130649230/6f2a660a-70ad-4415-849b-fbc3a173cf5e)

### Additional information

Doesn't matter if is a windows or nah.

**Comment by Jarred-Sumner** [comment]
@gvilums we might need to do something different here:

https://github.com/oven-sh/bun/blob/6cff1d7e4393c497e365665587fce18198734c73/src/bun.js/api/server.zig#L5750-L5751

**Comment by gvilums** [comment]
Am I missing something here or is this just due to the fact that on linux you need superuser privileges to listen on ports less than 1024 (which is why a permission denied error is shown). Running this example with `sudo <path to bun> run --watch .` works perfectly fine for me.

**Comment by ghost** [comment]
> Am I missing something here or is this just due to the fact that on linux you need superuser privileges to listen on ports less than 1024 (which is why a permission denied error is shown). Running this example with `sudo <path to bun> run --watch .` works perfectly fine for me.

I can't use sudo, then rights are bypassed.

**Comment by gvilums** [comment]
If you can't use sudo you'll have to listen on a different port, for example 8000. From my understanding this is a general issue and not related to bun specifically (correct me if i'm wrong on that and I'll happily reopen the issue)
