### ISSUE TITLE
Setting Serve ca forces server to run as https (with no cert/key?)

### ISSUE THREAD

**Issue by etinquis** [oven-sh/bun#8686]
### What version of Bun is running?

1.0.26+1f0c1c81e

### What platform is your computer?

Docker container

### What steps can reproduce the bug?

https://github.com/etinquis/bun-ca-repro/tree/master

```server.ts
import { Serve, file } from 'bun';

export default {
    port: 80,
    development: true,
    fetch(req: Request) {
        return new Response(null, { status: 200 });
    },
    ca: file('./bundle.pem')
} satisfies Serve;
```

```
docker run --rm -it --pull always -v .:/home/bun/app oven/bun:canary bash
bun --hot server.ts
```

Prints that it serves https:
```
Started server https://localhost:80
```
And any requests I send to it close immediately.

### What is the expected behavior?

Setting ca alone should not be possible.   Server should exit with an error, or follow whatever standard protocol is for a misconfigured server.

[08/24]
Amended expected behavior from `Outbound requests use ca bundle to validate certificates without affecting the server.` as this is not the intended purpose of 'ca'.

**Comment by Electroid** [comment]
Setting the `ca` on `Bun.serve` affects incoming requests to the server, not outgoing `fetch()` requests. There is no Web-standard API to support `ca` in `fetch()`, but we could implement something for it.

**Comment by etinquis** [comment]
@Electroid so ca enforces mTLS?  Or am I misunderstanding?

What I really want is `NODE_EXTRA_CA_CERTS` https://github.com/oven-sh/bun/issues/7124.

**Comment by etinquis** [comment]
Also, where is the server getting it's cert/key from if it's not being set?  I don't have any keys in the bundle.

**Comment by etinquis** [comment]
@cirospaciari Thanks for the update, I was looking forward to `NODE_EXTRA_CA_CERTS`.

Does your PR change the behavior reported in this ticket (specifically setting only ca on Serve forcing https without a specified cert/key)?

I'm waiting for the dockerhub canary to get updated before I can test myself, but as I understand, the reported behavior won't be affected by support of NODE_EXTRA_CA_CERTS.

**Comment by cirospaciari** [comment]
Passing ca on the serve will force https since you are asking to the server to require a CA certificate from the client, this is not changed, but you mentioned that `What I really want is NODE_EXTRA_CA_CERTS https://github.com/oven-sh/bun/issues/7124.` and we are shipping NODE_EXTRA_CA_CERTS so I closed the issue it self.

**Comment by etinquis** [comment]
@cirospaciari Thanks, appreciate it RE: NODE_EXTRA_CA_CERTS, it does solve my original use-case.

I still think something ought to be done specific to this issue though, as it results in a useless server (as far as I can tell?).  For instance, it should throw an error on startup if key and cert aren't specified but ca is.

**Comment by etinquis** [comment]
Amended expected behavior to remove reference to outbound requests as they aren't relevant to the reported behavior.

**Comment by etinquis** [comment]
Also, looking at the docs again, I think they could be improved as well.

Docs say:
```
Optionally, you can override the trusted CA certificates by passing a value for ca. By default, the server will trust the list of well-known CAs curated by Mozilla. When ca is specified, the Mozilla list is overwritten.

Bun.serve({
  fetch(req) {
    return new Response("Hello!!!");
  },
  tls: {
    key: Bun.file("./key.pem"), // path to TLS key
    cert: Bun.file("./cert.pem"), // path to TLS cert
    ca: Bun.file("./ca.pem"), // path to root CA certificate
  }
});
```
If ca == mTLS, the reference to the Mozilla CA list seems irrelevant, as it's not requiring/validating client certs based on the Mozilla list unless explicitly referenced, correct?

**Comment by etinquis** [comment]
@cirospaciari @Jarred-Sumner Can this be reopened, should I create a new copy, or is this a 'won't fix'?
