### ISSUE TITLE
Bun.file(1) FD corruption; GC bug?

### ISSUE THREAD

**Issue by argosphil** [oven-sh/bun#8687]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.1.31-gentoo-dist x86_64 13th Gen Intel(R) Core(TM) i7-1370P

### What steps can reproduce the bug?

I'm running this script:

```
async function f()
{
    let f;

    for (let i = 0; i < 1000000; i++) {
	f = Bun.file(1);
	console.log(f);
	await Bun.write(f, "hello\n");
	console.log(f);
    }
}

await f();
```

### What is the expected behavior?

A million repetitions of
```
FileRef (fd: 1) {
  type: "application/octet-stream"
}
hello
FileRef (fd: 1) {
  type: "application/octet-stream"
}
```

which would result in an output file of 7000000 lines.

### What do you see instead?

It's strange enough I have to paste it here:

```
strace -fff bun run ./bunbug2.js  2> strace | ` cat >out
wc -l out
666634 out
strace -fff bun run ./bunbug2.js  2> strace | cat >out
wc -l out
666606 out
strace -fff bun run ./bunbug2.js  2> strace | cat >out
wc -l out
666606 out
```

It's usually `666606` lines, corresponding to 95229 loop iterations running successfully plus one last `FileRef` output like this:

```
FileRef (fd: XXX) {
  type: "application/octet-stream"
}
```

where `XXX` is an unpredictable number corresponding to a 32-bit integer, sometimes negative.

The `cat` part is necessary for reproducibility.

The error message is:
```
3 |     let f;
4 | 
5 |     for (let i = 0; i < 1000000; i++) {
6 | 	f = Bun.file(1);
7 | 	console.log(f);
8 | 	await Bun.write(f, "hello\n");
           ^
EBADF: Bad file descriptor
   errno: -9
 syscall: "write"
      fd: XXX
```
where `XXX` is as above. The `strace` indicates bun is indeed attempting to write to the corrupt file descriptor.

### Additional information

I don't know about `bun` internals, but have some wild speculation:

The strace output makes it seem likely to me that there is a GC running which corrupts (or frees prematurely) the memory area holding the file descriptor. This is somewhat reproducible because the program is deterministic and GC timing should be almost deterministic. My conclusion is this is most likely a GC-related bug.

Experimenting with a FinalizationRegistry confirms that the first GC is happening around the time the bug strikes. With this program:

```
const registry = new FinalizationRegistry((i) => {
    console.log("free", i);
});

async function f()
{
    let f;

    for (let i = 0; i < 1000000; i++) {
	f = Bun.file(1);
	registry.register(f, i);
	console.log(f);
	await Bun.write(f, "hello\n");
	await new Promise(r => r());
	console.log(f);
	await new Promise(r => r());
    }
}

await f()
```

run as `bun run ./bunbug3.js | cat >out`, I see this output:

```
[361456 lines omitted]
FileRef (fd: 1) {
  type: "application/octet-stream"
}
FileRef (fd: 1) {
  type: "application/octet-stream"
}
hello
FileRef (fd: XXX) {
  type: "application/octet-stream"
}
FileRef (fd: XXX) {
  type: "application/octet-stream"
}
free 51636
free 51635
free 51634
free 51633
free 51632
free 51631
free 51630
free 51629
free 51628
free 51627
free 51626
free 51625
free 51624
free 51623
free 51622
free 51621
free 51620
free 51619
free 51618
free 51617
free 51616
free 51615
free 51614
free 51613
free 51612
[51607 lines omitted]
free 4
free 3
free 2
free 1
free 0
```
[edited to fix formatting]

**Comment by paperclover** [comment]
interesting bug report. i suspect this is possible to hit with other file descriptors / path strings.

if you want a workaround, you can use `Bun.stdout` instead of calling Bun.file(1), but that isn't the real solution to this issue.

**Comment by argosphil** [comment]
> interesting bug report. i suspect this is possible to hit with other file descriptors / path strings.

I haven't been able to reproduce the issue except on stdin, stdout, and stderr. There is code in `rare_data.zig` which appears to be specific to stdin, stdout, stderr, and disabling that code (by removing the "stdin_store orelse" in the stdin function, for example) seemed to avoid the issue, but I was quite tired at that point and am totally new to zig, so I need to experiment more.

> if you want a workaround, you can use `Bun.stdout` instead of calling Bun.file(1), but that isn't the real solution to this issue.

Thanks! That is indeed what I'm doing for now.

**Comment by paperclover** [comment]
it sounds like we are closing or corrupting the value in there. these stores are supposed to cache the values of Bun.stdin/stdout/stderr and i think also the 0 1 and 2 file descriptors. So this is probably just isolated to those three.

**Comment by argosphil** [comment]
Is it possible we're simply missing a `store.ref()` in `blob.zig:Blob.findOrCreateFileFromPath`? I've just published a commit that changes that, and it appears to avoid the problem, but I don't know whether the refcount is now accurate:

https://github.com/argosphil/bun/commit/e735cbb4df8bd8a551b96d6741b583be9fff9269

**Comment by argosphil** [comment]
> I don't know whether [the store's] refcount is now accurate:

I've now confirmed it is: it drops to 2 when all `Bun.file()` return values have gone out of scope, which is what it was created with. As the store is fundamentally an immortal object, that's what we want.

**Comment by paperclover** [comment]
would you like to open a pr for this?
