### ISSUE TITLE
Change bun r to run a script instead of bun remove

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#8688]
### What is the problem this feature would solve?

easy way to running scripts

### What is the feature you are proposing to solve the problem?

changing `bun r` from `bun remove` to `bun run`

### What alternatives have you considered?

nothing

**Comment by Jarred-Sumner** [comment]
Instead of `bun r`, you can omit `r` or `run` entirely 

For example, if the script is called foo, `bun foo` works .
