### ISSUE TITLE
Expose more embedded lib functions such as Bun.CRC32 from zlib

### ISSUE THREAD

**Issue by jhmaster2000** [oven-sh/bun#869]
### What is the problem this feature will solve?

External libraries will not be required for performing tasks already included in embedded libraries within Bun.

### What is the feature you are proposing to solve the problem?

Exposure of internal embedded lib functions to JS.

### What alternatives have you considered?

Third party libraries or FFI with external versions of the embedded Bun libraries such as zlib / tar, however this causes redundancy.

**Comment by evanwashere** [comment]
already available as `Bun.hash.crc32`
