### ISSUE TITLE
Process exists when using `await exists` instead of `existsSync`

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8696]
### What version of Bun is running?

Process exists when using `await exists` instead of `existsSync`

### What platform is your computer?

Linux 6.1.66-1-lts x86_64 unknown

### What steps can reproduce the bug?

https://github.com/huseeiin/create-svelte-bun
see `src/index.ts` line 45

**Comment by Electroid** [comment]
Same comment from the other issue, mind sharing a more minimal reproduction?

**Comment by huseeiin** [comment]
no reproduction bc i deleted my code. closing
