### ISSUE TITLE
`--compile` flag doesn't respect `--outfile` when bundling `.node` files

### ISSUE THREAD

**Issue by jackyzha0** [oven-sh/bun#8697]
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.2.16 x86_64 unknown

### What steps can reproduce the bug?

The `--compile` flag seems to suppress certain compilation errors. Create a project that relies on napi and notice that `bun build` on the file will raise the right error but `bun build --compile` seems to say it compiled successfully

### What is the expected behavior?

Raise the same errors with `--compile` turned on

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/23178940/9f3814a0-6866-445d-aca2-246480bf96ff)

**Comment by paperclover** [comment]
working as intended. `--compile` sets `--target=bun` and some other flags, as it is not possible to use --compile without them set.

**Comment by jackyzha0** [comment]
Why is this working as intended? The `--compile` flag should raise an error if it fails to build the binary

**Comment by Jarred-Sumner** [comment]
Is it failing to build the binary? `--compile` supports `.node` files

**Comment by paperclover** [comment]
> Why is this working as intended?

The error is due to the default value of `--format` (browser), see

> To load node files, set target to "bun"

With `--compile`, this is flipped to `--target=bun`

It seems this is not clear and documentation and error messages should be revised.

**Comment by jackyzha0** [comment]
Yes, it fails to emit the binary. This still happens with `--target=bun`, let me see if I can put together a minimal repro for yall

**Comment by jackyzha0** [comment]
Ah it actually does seem to compile properly but it doesn't seem to respect `--outfile`

![image](https://github.com/oven-sh/bun/assets/23178940/f103246a-f9df-401a-8c55-0cc59f921dfb)

**Comment by jackyzha0** [comment]
https://github.com/jackyzha0/bun-compile-repro

**Comment by Jarred-Sumner** [comment]
@jackyzha0 looks like there's a bug where the outfile is becoming the basename instead of the directory, so `--outfile=dist/foo` becomes `foo`

**Comment by paperclover** [comment]
thank you for the reproduction. this specifically only happens when a node file is included

**Comment by jackyzha0** [comment]
hey, any pointers on where I can look to maybe submit a PR for this?

**Comment by paperclover** [comment]
build_command.zig line 297, in that code block i suspect this might be.

may be worth checking if this happens without --compile. ~~seems likely since the absolute outfile is already decided~~ it might not actually be, not 100% sure.

StandaloneModuleGraph.zig line 525 might be the wrong directory

**Comment by jackyzha0** [comment]
Confirmed that this bug was not present in v1.0.23 or v1.0.24 (but only on Mac OS??) bug seems to affect only Linux from my tests so far. Let me backdate a few versions to confirm

**Comment by jackyzha0** [comment]
```zig
var output_dir = this_bundler.options.output_dir;
if (outfile.len > 0 and output_files.len == 1 and output_files[0].value == .buffer) {
    output_dir = std.fs.path.dirname(outfile) orelse ".";
    output_files[0].dest_path = std.fs.path.basename(outfile);
}
```

~I suspect it might be here (L299 in `bun/src/cli/build_command.zig`)? For including `.node` files, `output_files.len > 1` so this path to properly set `output_dir` never gets hit?~

hm nvm that doesn't seem to be it

**Comment by jackyzha0** [comment]
spent a few hours looking at it but couldn't figure it out :( would appreciate if yall could help take a look when you get the chance!

**Comment by dominicporteous** [comment]
I'm seeing a similar issue with compiled builds (with embedded .node) after version 1.0.16+800fb1290 **with an unchanged codebase**. Using oven-sh/setup-bun@v1 GitHub Action.

_I tried the following tests with and without `--frozen-lockfile` and there did not seem to be a difference in the results, so it doesn't seem to be dependency related IMO._

### Observations

With **version 1.0.15+b3bdf22eb and 1.0.16+800fb1290** (and probably earlier) the following command is successful and produces the output file as expected:

```
$ bun build src/bin/run.js --compile --sourcemap=inline --outfile dist/run/linux/run
[252ms]  bundle  901 modules
[75ms] compile  dist/run/linux/run
```

On **version v1.0.17 (5e60861c)**, I see the following error which does fail the build:

```
$ bun build src/bin/run.js --target bun --compile --sourcemap=inline --outfile dist/run/linux/run
error: script "build:run" exited with code 11 (SIGSEGV)
```

From version **1.0.18+36c316a24 -> 1.0.25**, I see the following error which does fail the build:

```
$ bun build src/bin/run.js --target bun --compile --sourcemap=inline --outfile dist/run/linux/run
error: script "build:run" was terminated by signal SIGSEGV (Address boundary error)
/home/runner/work/_temp/a621a6a5-649e-4a5f-9c67-9a1f46f0c5be.sh: line 6:  2184 Segmentation fault      (core dumped) bun build:run -- dist/run/linux/run
```

With version **1.0.26+c75e768a6**, I see the following error, **which is not** failing the build:

_Note: I am not sure why there is a jump from 901 modules to 902 modules in this, as there have been no changes to the codebase other than Bun version in the GitHub Action_

```
$ bun build src/bin/run.js --compile --sourcemap=inline --outfile dist/run/linux/run
[295ms]  bundle  902 modules
[79ms] compile  dist/run/linux/run
```

The output file `dist/run/linux/run` does not exist on disk as expected after this command has exited with 0.

We are developing locally on macOS and the codebase builds the executable as expected on the latest bun version (1.0.26+c75e768a6). There seems to be mixed results with the macOS runner on the GitHub Action. Sometimes it builds, sometimes it doesn't. It doesn't build on the latest Bun version (1.0.26+c75e768a6) on the macOS runner.

**Comment by jackyzha0** [comment]
We've mostly been patching this with various OS checks but an upstream fix would really help make it less brittle

**Comment by oliverjam** [comment]
Seeing this happen when importing any non-JS file, e.g. using the file loader to embed images into a binary:

```js
import file from "file.png";
console.log(file);
```

```shell
bun build --compile index.js --outfile build/run
```

This outputs to `./run` instead of `./build/run`. Removing the file import fixes it.
