### ISSUE TITLE
Bun.$ (or Bun.spawn) thinks all dependencies are git repositories?

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8699]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.1.66-1-lts x86_64 unknown

### What steps can reproduce the bug?

https://github.com/huseeiin/create-svelte-bun
see `src/index.ts` line 165

**Comment by Electroid** [comment]
Could you provide a more minimal reproduction? It's a little difficult to cipher through

**Comment by huseeiin** [comment]
> Could you provide a more minimal reproduction? It's a little difficult to cipher through

it appears to be because I'm doing this pattern "bun i dep && bun i dep2 -D" where you run two commands (the same cause of https://github.com/oven-sh/bun/issues/8700 somehow?).
