### ISSUE TITLE
Please detail how to use ArrayBufferSink and how you implemented react ssr with it

### ISSUE THREAD

**Issue by sod** [oven-sh/bun#870]
### Description of the problem

Given the tweet https://twitter.com/jarredsumner/status/1544614183840276484, `ArrayBufferSink` supposedly is one of the main ingredients why bun is so fast in the examples. I'd like to understand how this is supposed to be used, so one could play around with trying to boost string heavy tools like webpack, terser, linters, transformers or compilers of any kind with bun.

Also where is the source of the react ssr that utilizes `ArrayBufferSink`? Is there a "before" vs "after" string optimization diff/pr?

**Comment by Electroid** [comment]
Hey, thanks for reporting this issue. We are working on the official docs for Bun and will make sure to add this. For now, you can take a look at the TypeScript [types](https://github.com/oven-sh/bun-types/blob/709d735a85a810585d13758734810b5b77f97219/bun.d.ts#L337).
