### ISSUE TITLE
Bun.$ logs stdout without asking it to?

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8701]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.1.66-1-lts x86_64 unknown

### What steps can reproduce the bug?

https://github.com/huseeiin/create-svelte-bun
see `src/index.ts` line 179

**Comment by Electroid** [comment]
You'll want to use ```Bun.$`echo hello`.quiet()``` to avoid going to stdout.

**Comment by huseeiin** [comment]
> You'll want to use `` Bun.$`echo hello`.quiet() `` to avoid going to stdout.

thanks. fixed by using `Bun.which` in my case.
