### ISSUE TITLE
`bun --watch` causes console to detach but not close process.

### ISSUE THREAD

**Issue by 7f8ddd** [oven-sh/bun#8703]
### What version of Bun is running?

1.0.26+48ed1dfb6

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Put this in a file:
```
setInterval(() => console.log("Hello, world!"), 1000);
console.log("Started");
```
2. Run this with "bun run --watch"
3. Save a change in the file to make it restart (It won't happen otherwise)
4. Now try to Ctrl+C and close it

### What is the expected behavior?

It should exit the process.

### What do you see instead?
![image](https://github.com/oven-sh/bun/assets/141754874/85bb3208-eec2-4e75-b702-ba455c6040af)

### Additional information
This appeared after updating to release 1.0.26.

**Comment by Electroid** [comment]
It could be a bug in Bun that's specific to Linux, doens't reproduce on macOS:

```
Started
Hello, world!
Hello, world!
<save file>
<console clears>
Started
Hello, world!
^C⏎        
```

**Comment by Kusigeri** [comment]
Try to update kernel version v5.15.146. I couldn't reproduce it either. Not on windows, not on Git bash terminal, not on wsl on Ubuntu.

**Comment by 7f8ddd** [comment]
> Try to update kernel version v5.15.146. I couldn't reproduce it either. Not on windows, not on Git bash terminal, not on wsl on Ubuntu.

I've seen one person in the Discord reproduce the problem as well. It doesn't happen on 1.0.25, just tested it. I'm using the VSCode terminal, btw.

*3 people
![image](https://github.com/oven-sh/bun/assets/141754874/4921e781-3dd9-4c9d-8137-8523bca52c81)

**Comment by Jarred-Sumner** [comment]
What kind of terminal/shell do you use? I wonder if this is a signals issue

**Comment by 7f8ddd** [comment]
> What kind of terminal/shell do you use? I wonder if this is a signals issue

I tested this on the Windows Terminal, cmd.exe, and the Terminal in VSCode. All of them do the same thing. The process also won't die with killall, you must use -9 to force it.

![image](https://github.com/oven-sh/bun/assets/141754874/e50268e9-043b-4956-99d2-d177f0dd35f2)
(cmd.exe)

**Comment by 7f8ddd** [comment]
> What kind of terminal/shell do you use? I wonder if this is a signals issue

Doesn't happen on the Windows version, btw. Same Terminal.

**Comment by Hedronmx** [comment]
I am experiencing this issue on Fedora 39 with  Kernel: 6.7.3-200.fc39.x86_64, Shell: zsh 5.9

**Comment by paperclover** [comment]
Duplicate of #8788. There is already a fix on canary (`bun upgrade --canary`) We're gonna put a release out with this fix soon.

**Comment by 7f8ddd** [comment]
> Duplicate of #8788. There is already a fix on canary (`bun upgrade --canary`) We're gonna put a release out with this fix soon.

Technically that's the duplicate, since this was made before it, lol.

**Comment by paperclover** [comment]
i realize i just said the duplicate issue is of a newer issue. it is the other way around. either way, it *is* fixed. i just saw this posted in discord and didnt check the numbers.
