### ISSUE TITLE
More detailed sqlite error messages

### ISSUE THREAD

**Issue by jonasb** [oven-sh/bun#871]
### What is the problem this feature will solve?

Currently it's quite hard to distinguish what error occurred during a query. E.g. currently when a unique constraint is triggered the `error.message` is `"constraint failed"`. As far as I know, there's no way to tell which constraint failed.

(Also, currently we only get the error message, not the error code. It would be good to get the error code in the exception too, since it is more robust to check an error code or enum instead of the error message).

The output of this script is "constraint failed".

```javascript
import { Database } from 'bun:sqlite';

const db = Database.open(':memory:');
db.run('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT UNIQUE)');
db.run('INSERT INTO users (name) VALUES ("john")');
try {
  db.run('INSERT INTO users (name) VALUES ("john")');
  throw new Error('Expected error');
} catch (error) {
  console.log(error.message);
}
db.close();
```

### What is the feature you are proposing to solve the problem?

I believe that using `sqlite3_errmsg` gives better messages than `sqlite3_errstr` since sqlite has more contextual information and not just the error code. (I've checked with `node-sqlite3` and they use `sqlite3_errmsg` wherever possible)

Also, by including the error code in the exception, it would be easier to make sense of the error.

If including error code in the exception, I think it would make sense to use extended result codes since they are more specific: [sqlite3_extended_result_codes](https://www.sqlite.org/c3ref/extended_result_codes.html). Extended error codes probably makes sense even when using `sqlite3_errstr`.

---

This is how `node-sqlite3` represents errors. The following script outputs:
```
19
SQLITE_CONSTRAINT
SQLITE_CONSTRAINT: UNIQUE constraint failed: users.name
```

```javascript
const sqlite3 = require('sqlite3');

const db = new sqlite3.Database(':memory:');
db.serialize(() => {
  db.run('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT UNIQUE)');
  db.run('INSERT INTO users (name) VALUES ("john")');
  db.run('INSERT INTO users (name) VALUES ("john")', (error, result) => {
    console.log(error.errno);
    console.log(error.code);
    console.log(error.message);
  });
});
db.close();
```

**Comment by Jarred-Sumner** [comment]
Yes, definitely should do this

For those who want to contribute to Bun - this would be a nice one

The relevant code is all the calls to `sqlite3_errstr` in JSSQLStatement.cpp:

https://github.com/oven-sh/bun/blob/b11069420d7c84f72605f15e5921de7ac4a0a208/src/bun.js/bindings/sqlite/JSSQLStatement.cpp#L179

I think the main requirement is freeing the error message from SQLite. The easy way would be to immediately copy it into `WTF::String` and then free it. The harder but slightly faster way would be to check if it contains any non-ascii characters and if it doesn't, use a `WTF::ExternalStringImpl` and free it in the finalizer. If it does, then copy and free it immediately

**Comment by jonasb** [comment]
Thanks for taking a look @Jarred-Sumner 

I looked into doing it myself, looks simple enough but don't have a working development environment for Bun just yet. So hopefully someone else can jump on it.

Regarding freeing the error message, [the documentation has this to say](https://www.sqlite.org/capi3ref.html#sqlite3_errcode):

> The sqlite3_errmsg() and sqlite3_errmsg16() return English-language text that describes the error, as either UTF-8 or UTF-16 respectively. Memory to hold the error message string is managed internally. The application does not need to worry about freeing the result.

**Comment by dawidmachon** [comment]
Just wanted to motivate someone - I am really looking for resolution of this issue, because Lucia and Bun ;)

**Comment by KianNH** [comment]
There's also [`int sqlite3_error_offset(sqlite3 *db);`](https://www.sqlite.org/c3ref/errcode.html) which can be used to get a character offset for where an error occurred (in the event that the error can be pinpointed to a character, i.e syntax errors).

You can replicate the shell errors (which show the input with an arrow pointing to the character) with that.

```
Parse error: near "(": syntax error
  eated timestamp NOT NULL DEFAULT current_timestamp(),   lastchange timestamp N
                                      error here ---^
```

This is to say, it'd be nice to return that offset in the error so users can map it to input if they want to (i.e if they build a CLI using Bun).
