### ISSUE TITLE
bun --bun run build hangs with NextJS 14.1

### ISSUE THREAD

**Issue by mrdomino** [oven-sh/bun#8725]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-1011-gcp x86_64 x86_64

### What steps can reproduce the bug?

1. `bun create next-app@14.1`. (I used TypeScript, no ESLint, no src dir, yes app dir, and no other customization.)
2. `bun i`.
3. `bun --bun run build`.

### What is the expected behavior?

The project should build.

### What do you see instead?

I get the following output, followed by the system sitting with all cores idle:

```console
% bun --bun run build
$ next build
 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
   ▲ Next.js 14.1.0

   Creating an optimized production build ...
```

### Additional information

Straight `bun run build` still works because node is apparently used instead of bun. But it will fail if building against the `oven/sh` Docker images. So this might also appear as "bun nextjs projects do not build on Docker."

This appears to be a regression between NextJS 14.0.4 and 14.1; bun will build a project based on 14.0.4.

**Comment by Electroid** [comment]
Thanks for reporting this, digging into this, it looks like Bun has a bug with `process.send()`.

This is the minimal repro that works in Node.js, but fails in Bun:
```js
process.on("message", (data) => {
  console.log("Received:", data);
});

if (!process.env.CHILD) {
  const child_process = require("child_process");

  const subprocess = child_process.spawn(
    process.argv0,
    [__filename],
    {
      stdio: ["inherit", "inherit", "inherit", "ipc"],
      env: {
        ...process.env,
        CHILD: "1",
      },
      serialization: "json",
    },
  );

  subprocess.on("spawn", () => {
    const data = {
      fn: () => {},
      toJSON: () => "toJSON",
    };
    subprocess.send(data, (err) => {
      console.log("Sent:", data, err);
    });
  });
}
```

**Comment by cemo** [comment]
I can confirm that this is still valid with `Bun v1.0.29`.

**Comment by erguotou520** [comment]
I can confirm this in `docker` build. My `Dockerfile` looks like
```Dockerfile
FROM oven/bun:alpine as builder
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
ENV NODE_ENV production
COPY ./ ./
RUN bun --bun run build

FROM oven/bun:alpine as production
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/package.json package.json
COPY --from=builder /app/bun.lockb bun.lockb
RUN bun install --production --frozen-lockfile
COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY --from=builder /app/next.config.mjs next.config.mjs
EXPOSE 3000
ENTRYPOINT ["bun"]
CMD ["--bun", "run", "start"]
```
The `bun` version in `oven/bun:alpine` is `v1.0.29`.

But it works well on my `Mac M1` with the same `bun` version.

**Comment by hiroyamaguch** [comment]
Is still happen with Bun v1.0.30.

**Comment by erguotou520** [comment]
![image](https://github.com/oven-sh/bun/assets/7945757/9735f364-4e9b-4ea3-a1bb-98cbe78688ab)

Update to `v1.0.33` but still stuck

**Comment by cyrus01337** [comment]
Doing `NODE_ENV=production bun run build` also causes a similar issue if you do not have development tools installed on Fedora. The same behaviour is replicated the moment `--bun` comes into play. When running without `--bun` it looked like a dependency was missing/project dependencies weren't able to be built, causing it to hang - wonder if it could be a similar issue when involving `--bun`?

**Comment by jiushiwoyuze** [comment]
Face the same issue. Build  with `bun --bun run build`  will never succeed. See the detail.
![image](https://github.com/oven-sh/bun/assets/5416077/6cff195c-5a99-43b9-872a-554c44fedeff)

**Comment by kaumac** [comment]
Also having this issue running `bun --bun run next build`

**Comment by lomholdt** [comment]
I also have this issue. Anyone ever solved it? It's just stuck on `bun --bun run build` using `1.1.33`.

**Comment by Malin88** [comment]
Same here for nextJS 15.1 and bun 1.2

**Comment by mrtolkien** [comment]
Not sure why this was closed, the issue still exists.

My setup:

- `oven/bun:debian`
- Next 15.1.4
- `linux/amd64`

The build hangs at `bun run build` like everyone else here.
