### ISSUE TITLE
Bun.env vars no longer typed in 1.0.26

### ISSUE THREAD

**Issue by ebidel** [oven-sh/bun#8736]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

The [recommendation in the docs](https://bun.sh/docs/runtime/env#typescript) no longer works for typing `process.env` vars in TS:

```ts
// env.d.ts
declare module "bun" {
  interface Env {
    AWESOME: string;
  }
}
```

### What is the expected behavior?

`Bun.env.AWESOME` is `string`:

<img width="655" alt="Screenshot 2024-02-06 at 2 34 19 PM" src="https://github.com/oven-sh/bun/assets/238208/75bd2e73-c62a-4f5e-8408-ff340935fce4">

### What do you see instead?

`Bun.env.AWESOME` remains `string | undefined`:

<img width="546" alt="Screenshot 2024-02-06 at 2 33 59 PM" src="https://github.com/oven-sh/bun/assets/238208/a5098d82-f447-45f2-8cec-84cb9be5ed4c">

### Additional information

https://github.com/oven-sh/bun/pull/8195 is the likely culprit.

I was able to work around this by adding bun-types/overrides.d.ts in my project's env.d.ts:

```ts
/// <reference types="bun-types/overrides.d.ts" />

declare module 'bun' {
  interface Env {
    AWESOME: string;
  }
}
```

Should `overrides.d.ts` be included in bun-types/index.d.ts?

**Comment by Electroid** [comment]
Thanks for reporting this, we'll get a fix out.

**Comment by risu729** [comment]
I also faced this issue, so I opened a PR.
I apologize if someone was already working on this.
