### ISSUE TITLE
Creating Request from existing Request

### ISSUE THREAD

**Issue by sxzz** [oven-sh/bun#874]
### Version

0.1.5

### Platform

Darwin XXX-MBP.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run code:
```ts
console.log(new Request(new Request('https://example.com'), {}).url)
//                                                          ⬆️ if removes this arg, then it works!  
```
And got this result:
```
❯ bun test-bun.ts
[object Request]
```

### How often does it reproduce? Is there a required condition?

Always, just run the same code I provided.

### What is the expected behavior?

It should be the URL of the existing request object: (Running on Chrome / Safari / node 18)
```
console.log(new Request(new Request('https://example.com')).url)
> https://example.com/
```

### What do you see instead?

```
❯ bun test-bun.ts
[object Request]
```

**Comment by sxzz** [comment]
Oh it has been fixed on `0.1.5`

**Comment by Electroid** [comment]
Thanks for reporting this issue, this is indeed a bug.

```js
console.log(
  new Request(
    new Request(
      "https://example.com"
    ),
    {}
  ).url,
)

// expected: "https://example.com"
// actual: [object Request]
```

**Comment by Electroid** [comment]
@robobun 

```js
console.log(
  new Request(
    new Request(
      "https://example.com"
    ),
    {}
  ).url,
)
```

**Comment by robobun** [comment]
@Electroid here you go!
```tsx
[object Request]
```
<details>
  <summary>Code</summary>
  
```tsx
console.log(
  new Request(
    new Request(
      "https://example.com"
    ),
    {}
  ).url,
)
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
