### ISSUE TITLE
SyntaxError when using Material-UI (@mui) components (includes emotion)

### ISSUE THREAD

**Issue by ShlomyTuby** [oven-sh/bun#875]
### Version

0.1.5

### Platform

Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Create a new bun project using react template
```bash
bun create react
cd react
bun add @mui/material @emotion/react @emotion/styled
```
Update `src/App.jsx` (use `@mui/material/Button` component):
```jsx
import Button from "@mui/material/Button";

function App() {
  return (
    <Button variant="contained">Mui Button</Button>
  );
}

export default App;
``` 
Start the `bun` server and open the browser
```bash
bun dev
open http://localhost:3000
```
Open dev tools and look for the following error:
```
Uncaught SyntaxError: Export 'jsx' is not defined in module
```
<img width="870" alt="error1" src="https://user-images.githubusercontent.com/15658636/180858065-7bb8662f-ef28-4497-8248-a26affc6bef5.png">

### What is the expected behavior?

Material-UI button element without console errors:
<img width="576" alt="button" src="https://user-images.githubusercontent.com/15658636/180858325-2ca791cb-58d8-4cec-abe1-a510637f9d1c.png">

### What do you see instead?

SyntaxError in the console

### Additional information

There is a reported bug for the same issue on the discord channel but I couldn't find a related GitHub issue.

**Comment by Jarred-Sumner** [comment]
I think the issue is that bun is interpreting the tsconfig.json file in the npm package and that is causing other things to break

**Comment by davidriverapericas** [comment]
Hi, I'm pretty sure it's not the best solution, but I would like to share how I sorted it out (manually):

Edit the file node_modules/@emotion/react/dist/emotion-react.browser.esm.js
[Line 135]
From: var jsx = function jsx(type, props) {
To:      var jsxfn = function jsx(type, props) {

[Line 406]
From:     export { ClassNames, Global, jsx as createElement, css, jsx, keyframes };
To:          export { ClassNames, Global, jsxfn as createElement, css, jsxfn as jsx, keyframes };

Then you'll have your button ;)

I hope it helps a bit
Cheers
David

**Comment by drush** [comment]
@davidriverapericas Did you submit this as a patch to @emotion?

**Comment by duy211099** [comment]
i have the same problem

**Comment by Rodzman** [comment]
Hi! I'm having the same issue here. Is there any solution for this?

**Comment by davidriverapericas** [comment]
> @davidriverapericas Did you submit this as a patch to @emotion?

Hi @drush, no I haven't. I just applied that change to my local and it worked.

It would be really good if somebody else can try my approach (https://github.com/oven-sh/bun/issues/875#issuecomment-1206457865)... @duy211099 & @Rodzman?

Thank you all!

**Comment by Rodzman** [comment]
Hi @davidriverapericas,
Yeah, I've tried your approach and it worked well. But I agree with you
that it isn't the best solution, just a temp workaround.

I thought about filling an issue with emotion, but I think that only bun is having it, so maybe the solution would be to analyze and change the way that bun is reading and parsing that information.

Thanks

**Comment by davidriverapericas** [comment]
> Hi @davidriverapericas, Yeah, I've tried your approach and it worked well. But I agree with you that it isn't the best solution, just a temp workaround. I thought about filling an issue with emotion, but I think that only bun is having it, so maybe the solution would be to analyze and change the way that bun is reading and parsing that information. Thanks

Thank you @Rodzman for your comments.

@Jarred-Sumner, what do you think about that?

**Comment by davidriverapericas** [comment]
Hi all. I've tested again, creating a brand new React Project, this time with Bun 0.4.0 and it works perfectly, without any manual change in Emotion:

$ bun create react .
$ bun add @mui/material @emotion/react @emotion/styled
$ bun dev

It works to me ;)
