### ISSUE TITLE
Bun global install is not working in a Dockerfile build

### ISSUE THREAD

**Issue by baptisteArno** [oven-sh/bun#8753]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

1. Create `Dockerfile` with the content provided here: https://bun.sh/guides/ecosystem/docker
2. Anywhere add these 2 lines:
   ```
   RUN bun install --global cowsay
   RUN cowsay "Bun!"
   ```
3. Run: `docker build --pull -t bun-hello --progress plain .`
4. See error: `cowsay: not found`

### What is the expected behavior?

Should not error out

**Comment by tapz** [comment]
Any news about this? I have the same issue with pm2-runtime.

**Comment by productdevbook** [comment]
`1.0.35` same problem

**Comment by Jarred-Sumner** [comment]
I’m guessing $HOME/.bun/bin or $HOME/.bun/install/global/node_modules/.bin needs to be added to $PATH in the Docker image.

**Comment by productdevbook** [comment]
```dockerfile
FROM oven/bun:1

ENV BUN_INSTALL="$HOME/.bun"
ENV PATH="${BUN_INSTALL}/bin:$PATH"

WORKDIR /app

....
```

dont working :/

**Comment by productdevbook** [comment]
`env: can't execute 'node': No such file or directory`

I get this error when I try to use the global package
