### ISSUE TITLE
Unwanted Webpack Deprecation Warning Messages Triggered

### ISSUE THREAD

**Issue by exgphe** [oven-sh/bun#8756]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.3.0 x86_64 i386

### What steps can reproduce the bug?

1. Create `webpack_bun.js` with the following content:
```javascript
import webpack from 'webpack';

const compiler = webpack({
	mode: 'development',
	entry: './webpack_bun_test.js',
});
compiler.run((err, stats) => {
	if (err) {
		console.error(err);
	} else if (stats) {
		console.log(stats.toString());
	}
});
```
2. Create `webpack_bun_test.js` with the following content:
```javascript
console.log('hello world');
```
3. Run `bun webpack_bun.js`

### What is the expected behavior?

The webpack compiler runs successfully with no warning or error messages.

### What do you see instead?

Running `bun webpack_bun.js ` outputs the following error messages:
```
webpack.JavascriptModulesPlugin has moved to webpack.javascript.JavascriptModulesPlugin
webpack.LibraryTemplatePlugin is deprecated and has been replaced by compilation.outputOptions.library or compilation.addEntry + passing a library option
SingleEntryPlugin was renamed to EntryPlugin
webpack.WebpackOptionsDefaulter is deprecated and has been replaced by webpack.config.getNormalizedWebpackOptions and webpack.config.applyWebpackOptionsDefaults
```

### Additional information

This bug is also triggered in other projects where webpack is even not used but just installed by other dependencies. (e.g. I found out this bug initially in a Nuxt project where @nuxtjs/i18n and @nuxtjs/sitemap are both used). Therefore, everytime I launch the project script, it outputs a bunch of these deprecation messages, which is annoying.

**Comment by Electroid** [comment]
I presume the same code snippet in the latest Node.js does not generate those warnings?

**Comment by exgphe** [comment]
> I presume the same code snippet in the latest Node.js does not generate those warnings?

No it doesn’t.

Steps to test it in Node.js:

1. Create `webpack_node.mjs` with the following content:
```javascript
import webpack from 'webpack';

const compiler = webpack({
	mode: 'development',
	entry: './webpack_node_test.js',
});
compiler.run((err, stats) => {
	if (err) {
		console.error(err);
	} else if (stats) {
		console.log(stats.toString());
	}
});
```
2. Create `webpack_node_test.js` with the following content:
```javascript
console.log('hello world');
```
3. Run `npm install webpack`
4. Run `node webpack_node.mjs`

It outputs no warning or error message.

**Comment by paperclover** [comment]
minimum reproduction:

`esm.mjs`
```ts
import * as commonjs from './commonjs.cjs';
console.log(commonjs);
```

`commonjs.mjs`
```
const a = (x) => x;

module.exports = a({
  get a() {
    console.log('do not log');
  }
})
```

the getters should not be called. 

<img width="561" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/2fba4816-00ff-4eec-8c06-305a8f2a050e">

we are just iterating over all exports when we should be using something like CJS-Module-Lexer or something alike it.

**Comment by Jarred-Sumner** [comment]
This is due to how our CJS -> ESM conversion code works. When you import CJS as ESM, we call getters of dynamically-set exports. We can change this in the future, but then we have the same drawbacks of Node's approach where you cannot use named imports for all exported values

I don't think the problems the fix would create are worthwhile, but am open to revisiting this after seeing it cause more issues
