### ISSUE TITLE
bug `import.meta.main`  inside CLIs  1.0.25 (was true) -> 1.0.26 (is false)

### ISSUE THREAD

**Issue by aralroca** [oven-sh/bun#8757]
### What version of Bun is running?

1.0.26+e171f04ce

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Create an npm package with a `bin` file  with `.cjs` format and `#!/usr/bin/env bun` on top. Then use `import.meta.main` inside. 

Finally, create a bun project and add your dependency to `package.json` and also an script to run your cli, some example:

```json
{
  "name": "new-project",
  "module": "src/pages/index.tsx",
  "type": "module",
  "scripts": {
    "cli": "your-library-with-cli",
  },
  "dependencies": {
    "your-library-with-cli": "0.1.0",
  },
  "peerDependencies": {
    "typescript": "5.3.3"
  }
}
```

Then run `bun run cli`

### What is the expected behavior?

To be `true` (as before 1.0.26)

### What do you see instead?

`false`

**Comment by paperclover** [comment]
<img width="802" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/a4d492c1-60d0-40dc-94d2-c7c8830ac49d">
its not following symlinks how did this even regress

**Comment by aralroca** [comment]
@paperdave I tried `1.0.26+2bd4fe578` and I think that this introduces a new issue, so if you have in your package.json an script with `bun build`, example:

```json
{
  "scripts": {
    "build:core": "bun build --minify --target=bun --outdir=out/core src/core/index.ts"
  }
}
```

Then running `bun run build:core` appears this error:

```
/bin/bash: line 1: 35823 Segmentation fault: 11  bun build --minify --target=bun --outdir=out/core src/core/index.ts
error: script "build:core" exited with code 139
error: script "build" exited with code 139
```

When before this version it worked. 🤔

**Comment by paperclover** [comment]
Was this directly caused by this commit or is it present in the commit right before?

**Comment by aralroca** [comment]
@paperdave no idea about the commit to be honest, in `1.0.26+e171f04ce` this was working fine, but in `1.0.26+2bd4fe578` stop working
