### ISSUE TITLE
Support `bundledDependencies` in bun install

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#8780]
### What is the problem this feature would solve?

in this example all dependencies of this CLI are bundled by `bun build`

`package.json`:

```json
{
	"scripts": {
		"build": "bun build src/index.ts --target bun --outdir dist"
	},
	"dependencies": {
		"@clack/prompts": "^0.7.0",
		"@faker-js/faker": "^8.4.0",
		"consola": "^3.2.3",
		"kolorist": "^1.8.0"
	},
	"bundledDependencies": [
		"@clack/prompts",
		"@faker-js/faker",
		"consola",
		"kolorist"
	],
	"bin": {
		"create-svelte-bun": "dist/index.js"
	}
}
```

### What is the feature you are proposing to solve the problem?

bun shouldn't download `bundledDependencies` again since they are already included in `dist`

**Comment by Hexagon** [comment]
This could be considered a bug instead of enhancement - if a bundled dependency isn't available on npm, download (and install) fails even though the dependencies in fact are available.

**Comment by huseeiin** [comment]
is this finished by #13723?

**Comment by dylan-conway** [comment]
> is this finished by [#13723](https://github.com/oven-sh/bun/pull/13723)?

No, `bun pm pack` supports packing bundled dependencies, but we still need to add support for them in `bun install`

**Comment by pociej** [comment]
> > is this finished by [#13723](https://github.com/oven-sh/bun/pull/13723)?
> 
> No, `bun pm pack` supports packing bundled dependencies, but we still need to add support for them in `bun install`

What do you mean @dylan-conway by it works in `pm pack` but support in bun install is needed ? I have paclahe json where i. have dependecy listed in `dependecies` and then in `bundledDependecies` like this : 
```
  "dependencies": {
    "dns-over-http-resolver": "^3.0.3",
    "postal-mime": "^2.3.2",
    "viem": "^2.21.0",
    "@vlayer/web-proof-commons": "file:../../web-proof-commons"
  },
  "bundleDependencies": [
    "@vlayer/web-proof-commons"
  ]
```

When i do `bun install` I see my deps  in the node_modules however after `bun pm pack` `@vlayer/web-proof-commons` are not included in tarball.

**Comment by dylan-conway** [comment]
> When i do bun install I see my deps in the node_modules however after bun pm pack @vlayer/web-proof-commons are not included in tarball.

Could you open an issue for this? This is a bug where `bun pm pack` is mishandling scoped packages
