### ISSUE TITLE
syntaxerror: Left side of assignment reference

### ISSUE THREAD

**Issue by sbhehe233** [oven-sh/bun#8785]
### What version of Bun is running?

v1.0.26

### What steps can reproduce the bug?

Stepci’s [official sample](https://github.com/stepci/stepci/blob/main/docs/integration/bun.md) throws the below error, which they claim is a [known issue](https://github.com/stepci/stepci/issues/202) with Bun:

![image](https://github.com/oven-sh/bun/assets/55295768/c984fcc0-8ec8-4323-b6da-d3dcc55a4e9a)

**Comment by paperclover** [comment]
Minimal Reproduction

`(a?.b)[1] = 2;`
