### ISSUE TITLE
Regex failing

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [oven-sh/bun#879]
### Version

0.1.5

### Platform

Linux gabriel-fedora 5.17.13-300.fc36.x86_64 #1 SMP PREEMPT Mon Jun 6 14:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

* Create test case file: "test-regex.js";
* Write to file:
``` js
const regex = /[a-zλ_]/i;

if (regex.test("λ")) console.log("test succeeded");
else console.log("test failed");
```
* And see that if you run `node test-regex.js`, "test succeeded" is logged to the console; however, if you run `bun test-regex.js`, "test failed" is logged to the console.

### How often does it reproduce? Is there a required condition?

Always, no condition required.

### What is the expected behavior?

The expected behavior is that the `regex.test` succeeded.

### What do you see instead?

I see that bun's regex system does not recognize "λ".

**Comment by evanwashere** [comment]
transpiler bug

**Comment by rempas** [comment]
I have tested this using bun `v0.6.13` and it appears to be working correctly for me
