### ISSUE TITLE
windows: bunx fails when node is not installed

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#8795]
### What steps can reproduce the bug?

install fresh windows and only install bun

`bun create vite`

### What is the expected behavior?

it to work

### What do you see instead?

```
error: interpreter executable could not be found

Bun failed to remap this bin to it's proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues
```

### Additional information

This is a bug in `bunx` code that doesnt ensure a node binary exists before starting the bin.

It is also technically a fault of bun_shim_impl for not having a fallback for when `node.exe` is requested but not found. these are technically separate concerns.

**Comment by JIAFENG123** [comment]
I have the same problem

**Comment by OmarAfet** [comment]
I'm facing the same issue. followed the instructions on [this page](https://supabase.com/docs/guides/api/rest/generating-types#generating-types-using-supabase-cli), I still can't get past `npx supabase login` step, I used `bunx`.

**Comment by JasonGaoG** [comment]
The same issue to me，is there any solutions ？

**Comment by FireBird22** [comment]
> The same issue to me，is there any solutions ？

For now, install node. I guess it will be fixed in a future release but i don't think there is workaround to it as of right now.

**Comment by AQian0** [comment]
bun create vue@latest will also not work properly.

This may be caused by the fact that the Vue/Vite team has not yet provided enough support for Bun, or it may be caused by the fact that Bun is currently not good enough for compatibility on Windows.

**Comment by paperclover** [comment]
> Vue/Vite team has not yet provided enough support for Bun

This specific issue should not require any work from other projects. I will fix this soon since it breaks bunx, bun i -g, and other things.

**Comment by paperclover** [comment]
as of the PR, this error message is been improved.

![image](https://github.com/oven-sh/bun/assets/24465214/a001d694-585e-4d7f-aa58-b3d2a0d38c73)

though, to take this screenshot i've commented out specific handling for `node`, which will immediatly try to run it in bun if this path is hit (meaning if you run this without "bun" in your path, you may see "bun" in this message)
