### ISSUE TITLE
Glob patterns starting with "*." and having multiple wildcards fails

### ISSUE THREAD

**Issue by pierre-cm** [oven-sh/bun#8817]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-15-generic x86_64 x86_64

### What steps can reproduce the bug?

Considering following project structure:
```
project/
├ test/
│ └ example.test.ts
├ index.ts
├ package.json
└ tsconfig.json
```
With following `index.ts` content:
```ts
import { Glob } from "bun"

for await (const f of new Glob('*.test.*').scan({ cwd: "test" })) {
  console.log(f)
}
console.log("done")
```

### What is the expected behavior?

According to [Glob API](https://bun.sh/docs/api/glob), I would expect the following output:
```bash
$ bun run index.ts
example.test.ts
done
```

### What do you see instead?

No file matches the given pattern
```bash
$ bun run index.ts
done
```

### Additional information

As a workaround, escaping the first dot seems to work correctly
```js
new Glob('*\\.test.*')
```

**Comment by pierre-cm** [comment]
I suspect that the special fast-path matching used for components such as `*.ts` could be the culprit.
I believe that including `*` [here](https://github.com/oven-sh/bun/blob/a3c3dad351c2ef4a2be265be970e6bc0d127b690/src/glob.zig#L1137) might fix the issue.

**Comment by pierre-cm** [comment]
I suspect the special fast-path matching used for components such as *.ts could be the culprit.
I believe that including * [here](https://github.com/oven-sh/bun/blob/a3c3dad351c2ef4a2be265be970e6bc0d127b690/src/glob.zig#L1137) might fix the issue.

**Comment by leaumar** [comment]
Just wanna add that escaping the dot doesn't work for me. I'm using 1.0.26 on windows/wsl. Globbing `*.md` and such in a folder works and lists files, but running the same code with `*.*` or `*\\.*` finds no matches.
