### ISSUE TITLE
setTimeout causes extreme RAM and CPU usage

### ISSUE THREAD

**Issue by Toby222** [oven-sh/bun#882]
### Version

0.1.5

### Platform

Linux sputnik 5.15.56-2-rpi-ARCH #1 SMP PREEMPT Mon Jul 25 12:39:20 MDT 2022 aarch64 GNU/Linux

### What steps will reproduce the bug?

```js
setTimeout(()=>{}, 1_000_000)
```

### How often does it reproduce? Is there a required condition?

Happens on every run.

### What is the expected behavior?

Effectively idle CPU and RAM usage.

### What do you see instead?

Extreme CPU and Memory use.
![image of btop, showing extreme CPU and Memory use](https://user-images.githubusercontent.com/14962962/181000954-6aaba1d3-7b6c-4c8a-bca7-dbc2ee3e01a8.png)

Quickly increasing Memory use.
![image of btop, showing quickly declining available memory](https://user-images.githubusercontent.com/14962962/181001056-d318a227-c1bc-4d5d-8c2c-36cfd6f409bd.png)

### Additional information

The same applies to `setInterval(()=>{}, 1_000_000)`.

**Comment by Jarred-Sumner** [comment]
The problem is that there's a spin loop in there that really shouldn't be

**Comment by Toby222** [comment]
![image](https://user-images.githubusercontent.com/14962962/185417963-3b117376-08be-411b-944e-ed0c862f25f0.png)
With v1.9, this seems drastically better. 15% CPU still seems excessive for a single running Interval, but I'm not sure if that'd be this issue or a separate one.

**Comment by Jarred-Sumner** [comment]
There’s still one extra spin loop — that’s the 15% CPU usage you’re seeing (combined with a sleep(1) for good measure)

**Comment by 0x4a61636f62** [comment]
Is this issue related to #1403 ?

**Comment by Toby222** [comment]
I can't seem to reproduce anymore, so it might've been fixed already?

**Comment by Jarred-Sumner** [comment]
This was fixed awhile ago when we rewrote setTimeout & setInterval to no longer use spin loops
