### ISSUE TITLE
Breaking changes for Bun v1.1

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#8821]
We do plan to make a few, technically breaking changes to Bun v1.1. We will very clearly communicate this as well.

* #7829
* #8544
* #9255
* #2472
* #4892

No longer planned as part of Bun v1.1, needs more work.
* #9267
* #9243

**Comment by paperclover** [comment]
i think we should revert the `__esModule` thing for the runtime as it is a step that Node.js explicitly does not do, and due to that, most of the babel packages load differently in Bun. This breaks the `astro add` cli, among many other cases.

**Comment by paperclover** [comment]
There isn't an issue to track this but I also want to make `$` accept raw strings instead of 'cooked' strings. I think @zackradisic already has this implemented. It reveals some open issues for transpiler bugs but we will fix that after.

Edit: AFAIK this change was made and already shipped.

**Comment by mGranTY** [comment]
add https://github.com/oven-sh/bun/issues/9243 to the list xD

**Comment by paperclover** [comment]
adding #2472 as well because i have basically all the code written for this i think there was just a failing test

**Comment by birkskyum** [comment]
Time might be ripe soon for pulling this off as well - bun has become quite capable in the past half year:
- https://github.com/oven-sh/bun/issues/4464

**Comment by ptasheq** [comment]
Are you kindly planning soon to implement support for custom TLS certificates (NODE_EXTRA_CA_CERTS or an equivalent)?
