### ISSUE TITLE
spawnSync() does not honor "inherit" after position 2 in stdio

### ISSUE THREAD

**Issue by dhbaird** [oven-sh/bun#8844]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Linux 5.15.0-46-generic x86_64 x86_64

### What steps can reproduce the bug?

```
import { spawnSync } from "node:child_process";
import fs from "node:fs";

const fdA = fs.openSync("/dev/null", "r");
const fdB = fs.openSync("/dev/null", "r");
const fdC = fs.openSync("/dev/null", "r");
const fdD = fs.openSync("/dev/null", "r");

const inherits = new Array(Math.max(fdA, fdB, fdC, fdD) + 1).fill(null);
inherits[1] = "inherit";
inherits[fdA] = "inherit";
inherits[fdB] = "inherit";
inherits[fdC] = "inherit";
inherits[fdD] = "inherit";

console.log("fdA =", fdA);
console.log("fdB =", fdB);
console.log("fdC =", fdC);
console.log("fdD =", fdD);
console.log("inherits =", inherits);
console.log("Output of ls /dev/fd:");
const proc = spawnSync("ls", ["/dev/fd"], { stdio: inherits });
```

### What is the expected behavior?

<...snip...>
Output of ls /dev/fd:
0  1  12  13  14  15  2  3  4

### What do you see instead?

fdA = 12
fdB = 13
fdC = 14
fdD = 15
inherits = [
  null, "inherit", null, null, null, null, null, null, null, null, null, null, "inherit",
  "inherit", "inherit", "inherit"
]
Output of ls /dev/fd:
0  1  2  3  4

### Additional information

`bun.spawnSync()` has same issue.

**Comment by dhbaird** [comment]
Related question (but doesn't block me) is: where is fd 4 coming from? That's extra.

**Comment by dhbaird** [comment]
> Related question (but doesn't block me) is: where is fd 4 coming from? That's extra.

The extra fd should be resolved by https://github.com/oven-sh/bun/pull/8841

**Comment by dhbaird** [comment]
@Electroid would it be possible for someone to take a look at #8981? It should be pretty good now (after a few rounds of feedback), but any other feedback appreciated too. Thanks.

**Comment by gvilums** [comment]
Hi, sorry that this issue and your PR got lost, we were working on major internal changes to process spawning that were merged very recently. Running your example with the latest version (1.0.33) gives the following results:
```
fdA = 12
fdB = 13
fdC = 14
fdD = 15
inherits = [
  null, "inherit", null, null, null, null, null, null, null, null, null, null, "inherit",
  "inherit", "inherit", "inherit"
]
Output of ls /dev/fd:
0
1
10
11
12
13
14
15
16
2
3
4
5
6
7
8
9

```

It seems like the requested file descriptors are in fact inherited now (however, we may be inheriting too many file descriptors now?). Does this fix your issue?

**Comment by dhbaird** [comment]
Thank you @gvilums! And no worries, appreciate everything Bun and community are doing, and big thanks to looping back on this issue. This seems like too many file descriptors now (not that I'm complaining: it definitely exceeds my requirements! ;) ).

**Comment by dhbaird** [comment]
...that is to say, yes, it resolved the issue, for sure. I didn't test it myself, but I have confidence in your result above, and happy to consider the issue resolved. Thanks.

**Comment by gvilums** [comment]
Ok, great! I also just looked into the extraneous file descriptors that are open - this is because we open `"ignore"`d fds as `/dev/null` instead of closing them. I think this behavior should be fine for now.
