### ISSUE TITLE
Type error when using arrays in bun shell

### ISSUE THREAD

**Issue by mk12** [oven-sh/bun#8848]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Create index.ts:

```typescript
import { $ } from "bun";
const args = ["echo", "hi"];
await $`${args}`;
```

It runs as expected:

```
$ bun index.ts
hi
```

### What is the expected behavior?

It should type check.

### What do you see instead?

```sh
$ bunx tsc
index.ts:3:11 - error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'ShellExpression'.
  Type 'string[]' is missing the following properties from type 'Blob': size, type, arrayBuffer, stream, and 3 more.

3 await $`${args}`;
            ~~~~


Found 1 error in index.ts:3

```

**Comment by paperclover** [comment]
Duplicate of #8848

**Comment by mk12** [comment]
@paperdave I think you made a mistake, you marked this as a duplicate of itself?

**Comment by paperclover** [comment]
Sorry, i copied the wrong number. Duplicate of #8550
