### ISSUE TITLE
`readline` module yields wrong and incomplete values with a bad performance (compared to NodeJS)

### ISSUE THREAD

**Issue by cpixl** [oven-sh/bun#8850]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.7.1 x86_64 unknown

### What steps can reproduce the bug?

Generate `big_file.txt` (1 million lines should be around 25MB, increase if needed):
```
$ cat /dev/urandom | tr -dc '[:lower:]\n' | head -n 1000000 > big_file.txt
```

Create the `test.mjs` script:
```
import fs from 'fs'
import readline from 'readline'

const fileStream = fs.createReadStream('./big_file.txt')
const rl = readline.createInterface({
  input: fileStream,
  crlfDelay: Infinity
})

console.log('Starting...')
for await (const line of rl) {
  console.log(typeof line, line)
}
```

Run script with NodeJS (starts yielding & printing lines immediately):
```
$ node test.mjs
Starting...
string ajqrsoyrabfleslmw
string ggwazolafkjersvirfrmynnucihuywtgjli
string eubcujmhoboaecf
string hokkaxedir
string hngvulerbketqp
string egilek
string bfwowqdnhfmbugppibavbamkbjdbnropmezvarj
string x
string dlfgywzzjmkrvj
[...]
```

Run script with Bun (yields values wrapped in arrays, 3rd line always `undefined`, and fails to print next lines):
```
$ bun test.mjs
Starting...
object [ "ajqrsoyrabfleslmw" ]
object [ "ggwazolafkjersvirfrmynnucihuywtgjli" ]
object [ undefined ]
```

### What is the expected behavior?

Print the following lines:
```
Starting...
string ajqrsoyrabfleslmw
string ggwazolafkjersvirfrmynnucihuywtgjli
string eubcujmhoboaecf
string hokkaxedir
string hngvulerbketqp
string egilek
string bfwowqdnhfmbugppibavbamkbjdbnropmezvarj
string x
string dlfgywzzjmkrvj
[...]
```

### What do you see instead?

It prints the following lines instead:
```
Starting...
object [ "ajqrsoyrabfleslmw" ]
object [ "ggwazolafkjersvirfrmynnucihuywtgjli" ]
object [ undefined ]
```

### Additional information

Notice that there are 3 bugs being reported here:
1. Bun apparently tries to load entire file into memory before yielding lines
2. Current `readline` implementation yields arrays of strings instead of the string itself
3. Third line is always `[undefined]`, and 4th line and below is never printed

**Comment by yschroe** [comment]
This does only seem to happen, if you use a `for await` loop, right? For me it works fine with:
```javascript
rl.on('line', (line) => {
  console.log(typeof line, line)
}
```

Had a quick look, what might cause the problem with await, and maybe these blocks of code are worth investigating.
As far as I can see, the `AsyncIterator` of `readline` uses `EventEmitter.on`:
https://github.com/oven-sh/bun/blob/a0bcd0f946c874219bb9726c39e15f2558d4d10f/src/js/node/readline.js#L2459-L2469

In there, the event return value `ev` is always wrapped in an array, as this is the default behaviour for node.js as well. (Does anyone know why that is? Seems counter intuitive to me.):
https://github.com/oven-sh/bun/blob/a0bcd0f946c874219bb9726c39e15f2558d4d10f/src/js/node/events.js#L369-L375

In node.js' implementation though, setting the option `kFirstEventParam: true` does skip the array collection step and returns the value as is:
https://github.com/nodejs/node/blob/a8de25ed1523594dd6bf0ee08a24f146d38cb4e8/lib/events.js#L1158-L1160

The `kFirstEventParam` option does not seem to be implemented in bun at the moment and that's probably why the lines are wrapped in an array in your example.

I do not have a bun dev environment set-up right now to check, so this might be wrong.

Still does not explain why the read-in stops after 3 rows.

**Comment by Electroid** [comment]
Related: #8370
