### ISSUE TITLE
Fetching from Sveltekit SSR drops all headers while running Vite dev server

### ISSUE THREAD

**Issue by dimdenGD** [oven-sh/bun#8865]
### What version of Bun is running?

1.0.26+c75e768a6 (confirmed to also be on 1.1.7+b0b7db5c0)

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I've made simple project to reproduce the bug, consisting of 2 standalone apps:
- Sveltekit app that sends request from ssr with `Authorization: Bearer TEST` and `X-Test: Test header` headers
- Express server that just logs headers it receives 
  
1. Get [sveltekit-app.zip](https://github.com/oven-sh/bun/files/14239320/sveltekit-app.zip)
2. `bun install`
3. `bun run --bun dev`
4. While sveltekit app is running, also get [server.zip](https://github.com/oven-sh/bun/files/14239329/server.zip)
5. `bun install`
6. `bun .`
7. Now go to http://127.0.0.1:5173/ (or other port for Sveltekit app)
8. Check console of `server` project

### What is the expected behavior?

If you run sveltekit app with node (`npm run dev`):
![image](https://github.com/oven-sh/bun/assets/26517362/a231fe50-c8f8-4595-8f11-713ec0710db3)

### What do you see instead?

If you run sveltekit app with bun (`bun run --bun dev`):
![image](https://github.com/oven-sh/bun/assets/26517362/f967f7dd-7453-4de2-982c-b193d3736f34)
  
All custom headers are missing.

### Additional information

Building Sveltekit app and running it in production works correctly, so it's something with the Vite dev server.

**Comment by dimdenGD** [comment]
This is still an issue on Bun 1.1.7+b0b7db5c0.

**Comment by Jarred-Sumner** [comment]
This is no longer an issue as of Bun v1.1.20.

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/a1cf76fd-7f01-4003-ac1a-046fba849ef8">
<img width="431" alt="image" src="https://github.com/user-attachments/assets/fefe0649-526c-453b-9305-f87985b39ac6">
