### ISSUE TITLE
Implement `performance.markResourceTiming`

### ISSUE THREAD

**Issue by kansson** [oven-sh/bun#8867]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

https://github.com/oven-sh/bun/issues/8867#issuecomment-2119091614

**Comment by jprinaldi** [comment]
Any updates on this?

I'm running into this same issue using SvelteKit and `@sveltejs/adapter-cloudflare`.

**Comment by overestimate** [comment]
Minimal reproduction for a common scenario:
1. Run `bunx wrangler -v` once (to mitigate `error: postinstall script from "esbuild" exited with 1`)
2. Run `bunx wrangler login`
3. Press "Allow" on permissions grant page to trigger the callback to Wrangler
4. Wrangler fails with `TypeError: performance.markResourceTiming is not a function. (In 'performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState)', 'performance.markResourceTiming' is undefined)`

Any time Cloudflare's Wrangler needs to get data from a callback URI, it will crash and burn. This is not ideal for local Workers development.

There may be other issues blocking Wrangler from running, but this is the most apparent.

**Comment by LazerJesus** [comment]
+1

**Comment by LazerJesus** [comment]
temporary fix:
```
$: sed -i '/performance.markResourceTiming/d' shims.js
```

this removes the offending line. 
i run in in docker after build.

**Comment by kansson** [comment]
> temporary fix:
> ```
> $ sed -i '/performance.markResourceTiming/d' shims.js
> ```
> 
> this removes the offending line. 
> i run in in docker after build.
> 

Maybe this would we a good use case for the new bun patch command?
