### ISSUE TITLE
assert points to the wrong line

### ISSUE THREAD

**Issue by chenglou** [oven-sh/bun#8880]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

This file:

```ts
import assert from 'assert'

function calc() {
  return 1
}

assert.strictEqual(1, 2)
```

### What is the expected behavior?

assertion error points to the right line

### What do you see instead?

<img width="493" alt="Screenshot 2024-02-13 at 04 50 19" src="https://github.com/oven-sh/bun/assets/1909539/002f9125-15e2-461d-8aa3-1dd34d96516e">

**Comment by argosphil** [comment]
it's pointing to the wrong column, too, so possibly the wrong field is incremented somewhere?

**Comment by paperclover** [comment]
@argosphil in your commit, the off by one column might be real and in the stack trace printing as you found.

but the line being wrong is a much larger problem that transpiler's sourcemaps are wrong: see #7427 and many other issues opened with key words 'sourcemap'

if you stick `// @bun` at the top of the file it will disable this, and the line is now correct.

<img width="593" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/8b4407e4-fa19-4e36-a912-1e52f0bf6de0">

**Comment by argosphil** [comment]
> @argosphil in your commit, the off by one column might be real and in the stack trace printing as you found.
> 
> but the line being wrong is a much larger problem that transpiler's sourcemaps are wrong: see #7427 and many other issues opened with key words 'sourcemap'

Thanks for the pointer! I've found, unsurprisingly, that fixing the offset in one case makes it go wrong in others that used to work...
