### ISSUE TITLE
[win][fs] The second part of a UNC path should be a directory (`path.resolve`)

### ISSUE THREAD

**Issue by AlttiRi** [oven-sh/bun#8882]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
import path from "node:path";

for (const p of [
    "\\\\ComputerName\\SharedFolder",    // <- here
    "\\\\ComputerName\\SharedFolder\\Resource",
    "\\\\?\\UNC\\ComputerName\\SharedFolder",
    "\\\\?\\UNC\\ComputerName\\SharedFolder\\Resource",
    "\\\\127.0.0.1\\C$",                 // <- and here
    "\\\\127.0.0.1\\C$\\ProgramData",
    "\\\\?\\UNC\\127.0.0.1\\C$",
    "\\\\?\\UNC\\127.0.0.1\\C$\\ProgramData",
    "\\",
]) {
    console.log(path.resolve(p));
}
```

### What is the expected behavior?

Both Node.js and Deno:
```
\\ComputerName\SharedFolder\
\\ComputerName\SharedFolder\Resource
\\?\UNC\ComputerName\SharedFolder
\\?\UNC\ComputerName\SharedFolder\Resource
\\127.0.0.1\C$\
\\127.0.0.1\C$\ProgramData
\\?\UNC\127.0.0.1\C$
\\?\UNC\127.0.0.1\C$\ProgramData
C:\
```
There are ending `\` at line 1 and 5:
1\. `\\ComputerName\SharedFolder\`
5\. `\\127.0.0.1\C$\`

---

7\. `\\?\UNC\127.0.0.1\C$` has no `\` at the end, since the prefixed path _(starts with `\\?\`)_ is assumed that it's [already normalized](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#skip-normalization).

### What do you see instead?

```
\\ComputerName\SharedFolder
\\ComputerName\SharedFolder\Resource
\\?\UNC\ComputerName\SharedFolder
\\?\UNC\ComputerName\SharedFolder\Resource
\\127.0.0.1\C$
\\127.0.0.1\C$\ProgramData
\\?\UNC\127.0.0.1\C$
\\?\UNC\127.0.0.1\C$\ProgramData
C:\
```

Lines 1 and 5 do not have the ending `\`.

### Additional information

`path.resolve` function should take the second part of a UNC path (that starts with `\\`) as a directory. 
So, it should have the tailing `\`. Like it happens with `C:\`.

---

```
\\ComputerName\SharedFolder\
\\ComputerName\SharedFolder\Resource
```
Seems `SharedFolder` in this pattern is always a directory.

- https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention
- https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths
- https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by paperclover** [comment]
Has already been fixed in #8469 which is available on canary right now. I cannot reproduce these results anymore
