### ISSUE TITLE
Problem with the Linux Instalation

### ISSUE THREAD

**Issue by vicdeveloperr** [oven-sh/bun#8883]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-17-generic x86_64 x86_64

### What steps can reproduce the bug?

Executed the instalation command "curl -fsSL https://bun.sh/install | bash", i get the next log:

```
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
bash: línea 159:  3205 Instrucción ilegal     (`core' generado) IS_BUN_AUTO_UPDATE=true $exe completions &> /dev/null
Run 'bun --help' to get started
```

And i have instaled "unzip" correctly. So that is not the problem.

Also, after of the instalation, the bun command doesn't work

### What is the expected behavior?

`bun was installed successfully to ~/.bun/bin/bun` 

### What do you see instead?

```
######################################################################## 100.0%
bun was installed successfully to ~/.bun/bin/bun 
bash: línea 159:  3205 Instrucción ilegal     (`core' generado) IS_BUN_AUTO_UPDATE=true $exe completions &> /dev/null
Run 'bun --help' to get started
```

### Additional information

I have instaled the "unzip" package.

**Comment by guest271314** [comment]
Have you tried `bun-linux-x64-baseline.zip`?

E.g., 

```
cd $HOME
mkdir bin
cd bin
wget --show-progress --progress=bar --output-document bun.zip https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64-baseline.zip && unzip bun.zip && rm bun.zip && mv bun-linux-x64-baseline/bun `pwd` && rmdir bun-linux-x64-baseline
```

Then running `. ~/.bashrc` for

```
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

**Comment by vicdeveloperr** [comment]
I think the problem it's my old CPU. Have minimun more then 6 years. 

What are the hardware requeriments for bun?

**Comment by guest271314** [comment]
Did you try the bun-linux-x64-baseline release?

**Comment by paperclover** [comment]
i see two things

1. `Instrucción ilegal` (`Illegal Instruction`) means the CPU is too old for bun. We have a "baseline build" that should be used and picked automatically. The minimum cpu that bun requires is from the [Nehalem line of CPUs](https://en.wikipedia.org/wiki/Nehalem_(microarchitecture)) or anything equivilent. They're from 2008.

@vicdeveloperr can you try [bun-linux-x64-baseline.zip](https://github.com/oven-sh/bun/releases/download/bun-v1.0.26/bun-linux-x64-baseline.zip) and report back if that works.

If it *does* work, then we need to figure out why the line in install.sh
```sh
    # If AVX2 isn't supported, use the -baseline build
    if [[ $(cat /proc/cpuinfo | grep avx2) = '' ]]; then
        target=linux-x64-baseline
    fi
```
Why this does not get trigged on your machine.

2. The script should not succeed after the error. It seems `bun --version` is fine but `bun completions` triggers the instruction. At a very minimum we need to report this error and fail the installation if this happens.
