### ISSUE TITLE
`inflateSync` and `gunzipSync` don't throw but return an Error instead

### ISSUE THREAD

**Issue by MarByteBeep** [oven-sh/bun#8887]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```ts

{
  const buffer = new Uint8Array([0x12, 0x01, 0x3, 0x5, 0x5]);
  const compressed = Bun.deflateSync(buffer, { level: 9, windowBits: -15 });

  console.log(compressed);

  const decompressed = Bun.inflateSync(compressed);

  // decompressed isn't a Uint8array but an error: invalid stored block lengths
  console.log(decompressed);
}
```

or

```ts
{
  const buffer = new Uint8Array([0x12, 0x01, 0x3, 0x5, 0x5]);
  const decompressed = Bun.inflateSync(buffer);

  // decompressed isn't a Uint8array but an error: Zlib returned an error
  console.log(decompressed);
}
```

### What is the expected behavior?

Either throw or return `undefined` and add `undefined` as a return type of both functions.

### What do you see instead?

Return type is `Error`, without `Error` being specified as return type

### Additional information

Also related to https://github.com/oven-sh/bun/issues/8886

**Comment by jdalton** [comment]
Thank you for reporting this @MarByteBeep!

**Comment by MarByteBeep** [comment]
You're welcome! Thanks for fixing this 😊
