### ISSUE TITLE
[ ctrl + c ] can't exit Bun's process when using --watch

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#8888]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- bun run --watch index.js
- on Bun's terminal i type ctrl + c and nothing happen
- click to close Bun's terminal but its process is still running in silence

**Comment by truongan07** [comment]
This did not happen on ver. 1.0.25

**Comment by Jarred-Sumner** [comment]
Please run `bun upgrade --canary` and leave a comment if you still run into this issue
