### ISSUE TITLE
[win] `process.stdout.write` fails

### ISSUE THREAD

**Issue by AlttiRi** [oven-sh/bun#8896]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Window 10

### What steps can reproduce the bug?

```js
process.stdout.write("");
```

### What is the expected behavior?

```
```

### What do you see instead?

```
1 | process.stdout.write("");
    ^
TypeError: Failed to create UVStreamSink: uv_pipe_open(1) src.windows_c.E.ISDIR
 code: "ERR_INVALID_ARG_TYPE"

      at node:stream:155:85
      at NativeWritablePrototypeWrite (node:stream:3706:141)
      at C:\Dev\test\x.mjs:1:1
```

### Additional information

Using `process.stdout.write` with [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) is required to create  progress bars, make the console more interactive.

**Comment by sarturodev** [comment]
I think this is the reason why **bun repl** (and other libs that depend on process.stdout.write) crashes

**Comment by aryzing** [comment]
Not sure if related, but I'm seeing spotty `console.log` behavior in async functions/callbacks. At times, there's just no output to the terminal. Using linux. Opened https://github.com/oven-sh/bun/issues/8907

**Comment by paperclover** [comment]
8907 is not related to this.

**Comment by paperclover** [comment]
> I think this is the reason why bun repl (and other libs that depend on process.stdout.write) crashes

I think so. We'll use the bun repl issue as a tracking issue, but this as the underlying thing blocking repl, vite, etc.

**Comment by L4Ph** [comment]
This occurred in our repository as well.
It does not occur under the **C** drive, but on all other drives(like D or F or etc).
