### ISSUE TITLE
bun install doesn't support `file:.` path in `package.json` dependencies

### ISSUE THREAD

**Issue by jjrv** [oven-sh/bun#8899]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

In a directory with a valid `package.json` file (or if the `.` path in the command is changed to point to ~such a directory~ EDIT: the current package root)

`bun install --save-dev .`
fails.

`npm install --save-dev .`
creates a line in `package.json` and a symlink under `node_modules` that's useful for local development.
With that line in place,
`bun install`
fails.

### What is the expected behavior?

`bun install` should create a symlink under `node_modules` pointing to the path given as a `file` url in `package.json` dependencies. It should also be able to add such a line when told to install from a local directory containing a `package.json` file, picking the dependency name from that file.

### What do you see instead?

```
bun install v1.0.26 (c75e768a)

error: MissingPackageJSON
Bun could not find a package.json file.
```

**Comment by toxeus** [comment]
This works for me. My guess is that you don't have a valid `package.json` in the directory pointed by your file dependency path.

Example: 
```json
{
  "dependencies": {
    "foo": "file:foo_dir"
  }
}
```

You need to have a valid `package.json` *inside* `foo_dir`.

**Comment by jjrv** [comment]
Edited the title, it seems only self-references have this issue.

Here's a full transcript:

```
~$ mkdir foo
~$ cd foo
~/foo$ bun init
bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit

package name (foo): 
entry point (index.ts): 

Done! A package.json file was saved in the current directory.
 + index.ts
 + .gitignore
 + tsconfig.json (for editor auto-complete)
 + README.md

To get started, run:
  bun run index.ts
~/foo$ bun install --save-dev .
bun add v1.0.26 (c75e768a)

error: MissingPackageJSON
Bun could not find a package.json file.
```

**Comment by jjrv** [comment]
It seems if I install another local package, Bun will also install its dependencies, create a subdirectory under `node_modules` and symlink each file inside the other package. Meanwhile NPM will only make a single symlink pointing to the other package, without pulling dependencies. That's the behaviour that's needed in the case where the installed package is actually current one and it needs to point to itself.

I wonder if Bun has a philosophical reason for handling the linking this way. Compared to NPM, Bun supports installing a local package that has been cloned but `npm install` hasn't been run inside it yet, which makes sense. OTOH if developing that package at the same time, newly added files won't be visible in the requiring package. Also, can't test on Windows right now but I think it only supports linking directories through junctions, not file symlinks.
