### ISSUE TITLE
`bun add` does not support packages beginning with `@`

### ISSUE THREAD

**Issue by svercl** [oven-sh/bun#89]
I can run `bun add lodash` but something like `bun add @mantine/core` does nothing. I've tried wrapping it in quotes to no avail. The output I get when adding an "@ package" is:
```
bun add v0.0.59

Checked 254 installs across 259 packages (no changes) [6.00ms]
```

**Comment by Jarred-Sumner** [comment]
Fixed in https://github.com/Jarred-Sumner/bun/commit/d1df057d08ca0aae08ec8a16250ef0f4aa1588d2
