### ISSUE TITLE
Bun.write to redirected stdout writes to beginning of file

### ISSUE THREAD

**Issue by silversquirl** [oven-sh/bun#890]
### Version

0.1.5

### Platform

Linux themisto 5.18.11_1 #1 SMP PREEMPT_DYNAMIC Wed Jul 13 17:27:44 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

```js
await Bun.write(Bun.stdout, "Hello, world!\n");
await Bun.write(Bun.stdout, "oh no!\n");
```

### How often does it reproduce? Is there a required condition?

When redirected to a file, the `oh no!` from the second write overwrites the `Hello,` at the beginning of the file.

### What is the expected behavior?

```
$ bun run test.js
Hello, world!
oh no!
```

### What do you see instead?

```
$ bun run test.js >out && cat out
oh no!
world!
```

**Comment by Electroid** [comment]
This appears to be fixed as of `0.2.2`. If you can still reproduce it, please feel free to comment and we'll reopen the issue.

```js
await Bun.write(Bun.stdout, "Hello, world!\n");
await Bun.write(Bun.stdout, "oh no!\n");
```

```
> bun run index.js > output.txt && cat output.txt
Hello, world!
oh no!
```
