### ISSUE TITLE
Support for 32-bit Linux (x86/ia32)

### ISSUE THREAD

**Issue by edwillard** [oven-sh/bun#8903]
### What is the problem this feature would solve?

I would like to use Bun in a 32-bit Linux environment for use in VMs.

### What is the feature you are proposing to solve the problem?

Producing binaries for x86 Linux in addition to the current x64 and arm64.

### What alternatives have you considered?

I currently use Node but would love to take advantage of the speed improvement Bun offers.

**Comment by Electroid** [comment]
We are unlikely to ever support 32-bit platforms.
