### ISSUE TITLE
Spotty console.log behavior

### ISSUE THREAD

**Issue by aryzing** [oven-sh/bun#8907]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-17-generic x86_64 x86_64

### What steps can reproduce the bug?

When calling `console.log` or `console.error` in async functions or callbacks, at times there is no output to the terminal. Tested with VS Code terminal and system terminal.

### What is the expected behavior?

To see console output

### What do you see instead?

Nothing

**Comment by Jarred-Sumner** [comment]
The bug isn’t with console.log, the code is very likely not being executed 

Are the async functions being awaited? Please provide a code snippet that reproduces the issue

**Comment by aryzing** [comment]
Thanks, I'll double check. Perhaps the issue is with Elysia. If it helps, this is the snippet in question,

```js
export const app = new Elysia({
  serve: {
    cert,
    key,
  },
});

app.use(cors());

app.use(
  trpc(appRouter, {
    createContext,
    onError(opts) {
      console.error(
        JSON.stringify(
          {
            code: opts.error.code,
            message: opts.error.message,
            cause: opts.error.cause,
          },
          null,
          2,
        ),
      );
    },
  }),
);
```

**Comment by aryzing** [comment]
I don't know what to say, it does seem like there's something that's not quite right. When using `console.log` in other areas of the code that are being executed, there's no output.

If I figure out what's going or manage to consistently reproduce the issue, I'll let you know. Now it just seems random: at times console.log/error does work in async fns or callbacks, at times it doesnt.
