### ISSUE TITLE
setTimeout on server doesn't work like nodejs

### ISSUE THREAD

**Issue by rahbari** [oven-sh/bun#8909]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

in node setTimeout return server object and can be chained, but it bun it return nothing:
```
HTTP.createServer(this.handle).setTimeout(t * 1000).listen(p, h)
HTTPS.createServer({cert, key}, this.handle).setTimeout(t * 1000).listen(p, h)
```

### What do you see instead?

`TypeError: undefined is not an object (evaluating 'HTTP.createServer(this.handle).setTimeout(t * 1000).listen')`

**Comment by paperclover** [comment]
Duplicate of #4964

**Comment by rahbari** [comment]
it's not duplicate of https://github.com/oven-sh/bun/issues/4964
I didn't say it's not implemented, it returns undefined but should return the server like nodejs so if later calls are chined in nodejs code works as expected.
