### ISSUE TITLE
Is there documentation that I can use to build Bun for 32-bit x86 Linux?

### ISSUE THREAD

**Issue by edwillard** [oven-sh/bun#8914]
### What is the type of issue?

Documentation is missing

### What is the issue?

I found this [contributing documentation](https://bun.sh/docs/project/contributing) but it says "you will need to already have a release build of Bun installed" which is an issue without a 32-bit build of Bun. I [asked if the project would support 32-bit Linux](https://github.com/oven-sh/bun/issues/8903) and received the answer of no, so I want to build it myself. Can anyone help get me started?

**Comment by Jarred-Sumner** [comment]
Supporting 32-bit would involve many code changes which we have no plans to support. Bun's runtime relies on pointer-tagging and some other 64-bit specific code

We will support limited WASM builds in the future (which is 32 bit), but it wouldn't include the runtime or package manager
