### ISSUE TITLE
Segmentation Fault when installing packages

### ISSUE THREAD

**Issue by Twiggeh** [oven-sh/bun#892]
### Version

0.1.5

### Platform

Linux twiggeh-linux 5.18.6-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jun 22 14:16:20 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

```json
{
	"name": "yikes",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"dependencies": {
		"@apollo/client": "^3.4.16",
		"@apollo/react-hooks": "^4.0.0",
		"@emotion/react": "^11.6.0",
		"@emotion/styled": "^11.6.0",
		"@graphql-codegen/cli": "^2.2.2",
		"@graphql-codegen/fragment-matcher": "^3.2.0",
		"@graphql-codegen/introspection": "^2.1.0",
		"@graphql-codegen/near-operation-file-preset": "^2.2.14",
		"@graphql-codegen/typescript": "^2.3.1",
		"@graphql-codegen/typescript-document-nodes": "^2.2.0",
		"@graphql-codegen/typescript-operations": "^2.2.0",
		"@graphql-codegen/typescript-react-apollo": "^3.2.1",
		"@types/lodash": "^4.14.175",
		"@types/react-router-dom": "5.3.0",
		"@types/uuid": "^8.3.1",
		"apollo": "^2.33.8",
		"babel-plugin-istanbul": "^6.0.0",
		"copy-webpack-plugin": "^11.0.0",
		"deepdash": "^5.3.9",
		"framer-motion": "^6.3.3",
		"graphql": "^15.6.1",
		"husky": "^8.0.1",
		"lodash": "^4.17.21",
		"oidc-client": "^1.11.5",
		"openapi-typescript": "^5.3.0",
		"pretty-quick": "^3.1.3",
		"react": "^18.1.0",
		"react-dom": "^18.1.0",
		"react-router-dom": "^5.3.3",
		"uuid": "^8.3.2"
	},
	"keywords": [],
	"author": "",
	"license": "ISC"
}

```
`bun install`

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

To not segfault

### What do you see instead?

  🔍 semver [66/289] 
SegmentationFault at 188

–––– bun meta ––––
Bun v0.1.5 Linux x64 #1 SMP PREEMPT_DYNAMIC Wed Jun 22 14:16:20 UTC 2022
InstallCommand: 
HTTP: 214
Elapsed: 35227ms | User: 35290ms | Sys: 141ms
RSS: 0.30GB | Peak: 0.19GB | Commit: 0.30GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

**Comment by Twiggeh** [comment]
When you re-run it seg-faults at different libraries :
```bun install v0.1.5
  🔍 argparse [119/256] 
SegmentationFault at 188


–––– bun meta ––––
Bun v0.1.5 Linux x64 #1 SMP PREEMPT_DYNAMIC Wed Jun 22 14:16:20 UTC 2022
InstallCommand: 
HTTP: 129
Elapsed: 33182ms | User: 33229ms | Sys: 177ms
RSS: 0.32GB | Peak: 0.16GB | Commit: 0.32GB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by SelfMadeSystem** [comment]
I just tested it now with bun v0.1.11 and it didn't segfault. I'm on `Arch Linux 5.19.7-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:33:28 +0000 x86_64 GNU/Linux`

I think it's fixed now.

**Comment by Jarred-Sumner** [comment]
I believe this has been fixed in 1-2 versions ago, but please leave a comment if it happens again
