### ISSUE TITLE
Infinite loading on non existing paths on a express server.

### ISSUE THREAD

**Issue by rayanfer32** [oven-sh/bun#8926]
### What version of Bun is running?

1.0.26

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
import express from 'express';

const app = express();
app.use(express.json());

app.get('/api/hotels', (req, res) => {
  res.json({
    success: true
  })
})

app.listen(3000, () => console.log('App is running on port 3000!'));
```

```bash
curl  -X POST \
  'localhost:3000/api/hotel' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "name": "Bellisima",
  "address": "North Hampton, near lake bloomdale"
}'
```

Bun with Express Server doesn't handle routes / paths very well; if you have a typo in the route, usually a missing 's' for plural API endpoints. In my case, there is no endpoint defined for `api/hotel` and I'm seeing an infinite loader because of that. If I do not pass anything in the body, then i get 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error</title>
  </head>
  <body>
    <pre>Cannot POST /api/hotel</pre>
  </body>
</html>
``` 
This is correct. But it should be the same when the body is provided too right.

![image](https://github.com/oven-sh/bun/assets/37145078/aed137cd-0392-462b-8f94-e3b27b7b0069)
 

### What is the expected behavior?

Should return path/route does not  exist

### What do you see instead?

Infinite loading

### Additional information

Node js works fine, only facing the issue with bun.

**Comment by 44kia244** [comment]
Same issue here. It seems like something in express.js logic. The `express.json()` middleware already call `next()` but express does not handle the not-found case.

**Comment by 44kia244** [comment]
After some investigation, it seems to be the `node:http` that bugged. I have opened issue #11115 for it.
