### ISSUE TITLE
import.meta.resolve(Sync) should not throw error when module file cannot be found

### ISSUE THREAD

**Issue by ewmb7701** [oven-sh/bun#8928]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Using `import.meta.resolve` or `import.meta.resolveSync` for a module which does not exist will throw an error.

```
console.log(import.meta.resolveSync("./render.png"));
```

### What is the expected behavior?

I expect the behavior/ implementation of `import.meta.resolve` to be compatible with [the specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve), and make no attempt to access the path.

### What do you see instead?

`import.meta.resolve` throws an error instead.
```
error: Cannot find module "./render.png" from ...
```

### Additional information

My goal is to determine the path of a file which does not *yet* exist and to write some asset to it.

**Comment by jdalton** [comment]
📓 Node has tweaked its implementation to not error in exact file references too:
https://github.com/nodejs/node/pull/49038

**Comment by paperclover** [comment]
a duplicate of #2472. this function is implemented completely incorrect in terms of what node and the browser does an the linked issue is about fixing it.
