### ISSUE TITLE
Build bun on ubuntu 22.04 in docker fails compile Server.zig

### ISSUE THREAD

**Issue by greenpdx** [oven-sh/bun#893]
### Version

git master july 27 e468a618114998d075c6dcf7fa920004ab30e430

### Platform

Linux bun 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

failed on  $ devcontainer build

### How often does it reproduce? Is there a required condition?

tried twice to build with same error

### What is the expected behavior?

it to build without failure

### What do you see instead?

Submodule path 'src/tracy': checked out '2d8723b69b39721eadcc296451012828899c0f17'
./src/Server.zig:2032:47: error: container 'std.fs' has no member called 'openIterableDirAbsolute'
                var document_dir_path = std.fs.openIterableDirAbsolute(std.fs.path.dirname(document_path) orelse break :fsc, .{}) catch break :fsc;
                                              ^
/build/zig/lib/std/fmt.zig:746:9: error: Unsupported format string '?s' for type 'u8'
        @compileError("Unsupported format string '" ++ fmt ++ "' for type '" ++ @typeName(@TypeOf(value)) ++ "'");
        ^
/build/zig/lib/std/fmt.zig:698:52: note: called from here
        .Int, .ComptimeInt => return formatIntValue(value, fmt, options, writer),
                                                   ^
/build/zig/lib/std/fmt.zig:463:31: note: called from here
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/io/writer.zig:28:34: note: called from here
            return std.fmt.format(self, format, args);
                                 ^
/build/zig/lib/std/debug.zig:93:27: note: called from here
    nosuspend stderr.print(fmt, args) catch return;
                          ^
./src/Server.zig:54:24: note: called from here
        std.debug.print("[{?s}-{?s}] " ++ format ++ "\n", .{ @tagName(message_level), @tagName(scope) } ++ args);
                       ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: error: expected type 'std.os.WriteError!void', found '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set!void'
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/io/writer.zig:28:34: note: called from here
            return std.fmt.format(self, format, args);
                                 ^
/build/zig/lib/std/debug.zig:93:27: note: called from here
    nosuspend stderr.print(fmt, args) catch return;
                          ^
./src/Server.zig:54:24: note: called from here
        std.debug.print("[{?s}-{?s}] " ++ format ++ "\n", .{ @tagName(message_level), @tagName(scope) } ++ args);
                       ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: note: error set '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set' cannot cast into error set 'std.os.WriteError'
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:746:9: error: Unsupported format string '?s' for type 'u8'
        @compileError("Unsupported format string '" ++ fmt ++ "' for type '" ++ @typeName(@TypeOf(value)) ++ "'");
        ^
/build/zig/lib/std/fmt.zig:698:52: note: called from here
        .Int, .ComptimeInt => return formatIntValue(value, fmt, options, writer),
                                                   ^
/build/zig/lib/std/fmt.zig:463:31: note: called from here
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/fmt.zig:1889:11: note: called from here
    format(counting_writer.writer(), fmt, args) catch |err| switch (err) {};
          ^
/build/zig/lib/std/fmt.zig:1896:40: note: called from here
    const size = math.cast(usize, count(fmt, args)) orelse return error.OutOfMemory;
                                       ^
./src/Server.zig:62:37: note: called from here
    var message = std.fmt.allocPrint(arena.allocator(), "[{?s}-{?s}] " ++ format, .{ @tagName(message_level), @tagName(scope) } ++ args) catch {
                                    ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: error: expected type 'std.io.NullWriter!void', found '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set!void'
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/fmt.zig:1889:11: note: called from here
    format(counting_writer.writer(), fmt, args) catch |err| switch (err) {};
          ^
/build/zig/lib/std/fmt.zig:1896:40: note: called from here
    const size = math.cast(usize, count(fmt, args)) orelse return error.OutOfMemory;
                                       ^
./src/Server.zig:62:37: note: called from here
    var message = std.fmt.allocPrint(arena.allocator(), "[{?s}-{?s}] " ++ format, .{ @tagName(message_level), @tagName(scope) } ++ args) catch {
                                    ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: note: error set '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set' cannot cast into error set 'std.io.NullWriter'
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:746:9: error: Unsupported format string '?s' for type 'u8'
        @compileError("Unsupported format string '" ++ fmt ++ "' for type '" ++ @typeName(@TypeOf(value)) ++ "'");
        ^
/build/zig/lib/std/fmt.zig:698:52: note: called from here
        .Int, .ComptimeInt => return formatIntValue(value, fmt, options, writer),
                                                   ^
/build/zig/lib/std/fmt.zig:463:31: note: called from here
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/fmt.zig:1877:15: note: called from here
    try format(fbs.writer(), fmt, args);
              ^
/build/zig/lib/std/fmt.zig:1898:20: note: called from here
    return bufPrint(buf, fmt, args) catch |err| switch (err) {
                   ^
./src/Server.zig:62:37: note: called from here
    var message = std.fmt.allocPrint(arena.allocator(), "[{?s}-{?s}] " ++ format, .{ @tagName(message_level), @tagName(scope) } ++ args) catch {
                                    ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: error: expected type 'std.io.fixed_buffer_stream.FixedBufferStream([]u8).WriteError!void', found '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set!void'
            return formatValue(value, actual_fmt, options, writer);
                              ^
/build/zig/lib/std/fmt.zig:627:35: note: called from here
                    try formatType(elem, actual_fmt, options, writer, max_depth - 1);
                                  ^
/build/zig/lib/std/fmt.zig:178:23: note: called from here
        try formatType(
                      ^
/build/zig/lib/std/fmt.zig:1877:15: note: called from here
    try format(fbs.writer(), fmt, args);
              ^
/build/zig/lib/std/fmt.zig:1898:20: note: called from here
    return bufPrint(buf, fmt, args) catch |err| switch (err) {
                   ^
./src/Server.zig:62:37: note: called from here
    var message = std.fmt.allocPrint(arena.allocator(), "[{?s}-{?s}] " ++ format, .{ @tagName(message_level), @tagName(scope) } ++ args) catch {
                                    ^
/build/zig/lib/std/log.zig:144:21: note: called from here
            root.log(message_level, scope, format, args);
                    ^
/build/zig/lib/std/log.zig:189:16: note: called from here
            log(.err, scope, format, args);
               ^
/build/zig/lib/std/start.zig:582:28: note: called from here
                std.log.err("{s}", .{@errorName(err)});
                           ^
/build/zig/lib/std/start.zig:565:22: note: called from here
pub fn callMain() u8 {
                     ^
/build/zig/lib/std/fmt.zig:463:31: note: error set '@typeInfo(@typeInfo(@TypeOf(std.fmt.formatValue)).Fn.return_type.?).ErrorUnion.error_set' cannot cast into error set 'std.io.fixed_buffer_stream.FixedBufferStream([]u8).WriteError'
            return formatValue(value, actual_fmt, options, writer);
                              ^
zls...The following command exited with error code 1:
/build/zig/zig build-exe /home/ubuntu/zls/src/Server.zig -OReleaseFast --cache-dir /home/ubuntu/zls/zig-cache --global-cache-dir /root/.cache/zig --name zls --pkg-begin build_options /home/ubuntu/zls/zig-cache/options/ZN5T5qs__MtT8K02r_1S-BHCIQm36qquqqxMkxJvDpZqrwQ-wS_m2895sSwEs1B_ --pkg-end --pkg-begin known-folders /home/ubuntu/zls/src/known-folders/known-folders.zig --pkg-end --enable-cache 
error: the following build command failed with exit code 1:
/home/ubuntu/zls/zig-cache/o/7728caaa65e05674b30a49c969961f23/build /build/zig/zig /home/ubuntu/zls /home/ubuntu/zls/zig-cache /root/.cache/zig -Drelease-fast
The command '/bin/sh -c mkdir -p /home/ubuntu/.bun /home/ubuntu/.config $GITHUB_WORKSPACE/bun &&     bash /scripts/common-debian.sh &&     bash /scripts/github.sh &&     bash /scripts/nice.sh &&     bash /scripts/zig-env.sh' returned a non-zero code: 1
[424290 ms] Error: Command failed: docker build -f /home/ubuntu/bun/Dockerfile.devcontainer -t vsc-bun-25d9bbe3bbd077fa9db9c9f1a4bc1ab9 --target bun.devcontainer --cache-from bun.devcontainer:latest /home/ubuntu/bun
[424291 ms]     at buildAndExtendImage (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20763:11)
[424291 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[424291 ms]     at async buildNamedImageAndExtend (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:20656:12)
[424291 ms]     at async doBuild (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:21399:36)
[424291 ms]     at async build (/usr/lib/node_modules/@vscode/dev-container-cli/dist/spec-node/devContainersSpecCLI.js:21329:18)
[424294 ms] Exit code 1
ubuntu@bun:~/bun$ uname -a
Linux bun 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@bun:~/bun$

**Comment by ram1660** [comment]
Related to #814.
You can follow the issue there to get yourself going, though it's not a real fix for the problem.

**Comment by ram1660** [comment]
Update: Jarred pushed recently some updates about the devcontainer and it seems like the issue has been resolved.

**Comment by Jarred-Sumner** [comment]
Please use the version of ZLS in oven-sh, as it matches the version of Zig used by Bun. ZLS often fails to build when there are incompatible breaking changes in zig’s standard library
