### ISSUE TITLE
Proxy Support in Bun: A Must-Have

### ISSUE THREAD

**Issue by Sephyi** [oven-sh/bun#8931]
### What is the problem this feature would solve?

Install packages behind a (corporate) proxy server.

### What is the feature you are proposing to solve the problem?

Introduce proxy support, similar to what is found in npm and other tools.

### What alternatives have you considered?

Lack of proxy support in Bun, presents a significant barrier for switching, leaving me without viable alternatives.

**Comment by Electroid** [comment]
This will depend on: #643, which we will support at some point.
