### ISSUE TITLE
lsp

### ISSUE THREAD

**Issue by steve4650** [oven-sh/bun#8951]
### What is the problem this feature would solve?

Bun promises to be the all in one JS solution of the future, but it does not provide an LSP!

### What is the feature you are proposing to solve the problem?

An LSP.

**Comment by paperclover** [comment]
what is an LSP needed for? You can use the typescript language server for this. See https://bun.sh/docs/typescript

**Comment by steve4650** [comment]
The LSP would provide all the things that an LSP does! Jump to definition, format on save, smart renaming.

Yes, Bun provides some nice types that can be used with other LSP tools.

**Comment by paperclover** [comment]
The [TypeScript language server](https://github.com/microsoft/TypeScript) does all of these features already. Bun can be used with it using [`@types/bun`](https://www.npmjs.com/package/@types/bun).

I don't think this is worth it to rewriting or extending these if there isn't any gain in doing so.

There is also a visual studio code extension for bun which would be the place for adding features like package manager and test runner integration (there are issues for these specific features individually).

**Comment by iocron** [comment]
Since I ran into a similar problem and didn’t want to install Node, the only solution I found was to force Helix to use Bun with the TypeScript LSP, in case it helps someone.

1. First install the lsp through bun: `bun install -g typescript-language-server` (make sure its not already installed)
2. Add this to your ~/.config/helix/languages.toml:
```
[language-server.typescript-language-server]
command = "bunx"
args = ["--bun", "typescript-language-server", "--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
```
