### ISSUE TITLE
Expose AST parser

### ISSUE THREAD

**Issue by DavertMik** [oven-sh/bun#8968]
### What is the problem this feature would solve?

I want to use AST parser in my app. Currently I'm fine with `@babel/parser` however, I'm wondering if Bun can expose its parsing API to allow parsing and traversing of JS nodes.

### What is the feature you are proposing to solve the problem?

Avoid using heavy parsers like Babel if the Bun has much faster JS  parser

### What alternatives have you considered?

`@babel/parser`

**Comment by paperclover** [comment]
Duplicate of #2729
