### ISSUE TITLE
node fs/promises watch bug

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#8973]
### What version of Bun is running?

1.26-1.27

### What platform is your computer?

Ubuntu 22.04 and WSL2

### What steps can reproduce the bug?

When monitoring the file directory, the filename returned by triggering the change event is incomplete and always lacks one character at the beginning.

```javascript
import { watch } from "fs/promises";

for await (const event of watch('/path/any')) {
    console.log(event)
}

// Running results
{
  eventType: "change",
  filename: "ilename.js", // It should be:filename.js
}

//

```

### What is the expected behavior?

ditto

**Comment by baicie** [comment]
pls assigned to me, tks

**Comment by baicie** [comment]
I can try to fix this, but it might take some time

**Comment by luty81** [comment]
I couldn't reproduce the issue.

My WSL2 info:

_WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
Windows version: 10.0.22621.3155_

_Ubuntu version: Ubuntu 22.04.4 LTS_
_Linux RYZEN-3800X 5.15.133.1-microsoft-standard-WSL2 x86_64 GNU/Linux_

Is there any special condition to reproduce the issue ?

**Comment by vamsaya** [comment]
> I couldn't reproduce the issue.
> 
> My WSL2 info:
> 
> _WSL version: 2.0.9.0 Kernel version: 5.15.133.1-1 WSLg version: 1.0.59 Windows version: 10.0.22621.3155_
> 
> _Ubuntu version: Ubuntu 22.04.4 LTS_ _Linux RYZEN-3800X 5.15.133.1-microsoft-standard-WSL2 x86_64 GNU/Linux_
> 
> Is there any special condition to reproduce the issue ?

Hello, after testing, we found that the reason why the change event filename is missing the first character is that there is an extra / symbol after the path.

```javascript
./path/ ❌
./path    √
```

**Comment by cirospaciari** [comment]
This was fixed at some point in the past please reopen if encounter this issue in the future
