### ISSUE TITLE
require.resolve unable to find node module

### ISSUE THREAD

**Issue by roninjin10** [oven-sh/bun#8974]
### What version of Bun is running?

1.0.27+c34bbb2e3

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. bun init
2. bun install @tevm/contract 
3. Add following script and run it with bun and node. Node will return the path while bun will fail to return the correct path

```typescript
import { createRequire } from 'module';

const require = createRequire(
  `${process.cwd()}/`
);

console.log(
  require.resolve('@tevm/contract')
)
```

### What is the expected behavior?

This should be able to resolve a node module relative to process.cwd() like node does

### What do you see instead?

Node is able to resolve this while bun fails

### Additional information

![telegram-cloud-photo-size-1-5084681159350266970-y](https://github.com/oven-sh/bun/assets/35039927/38698475-bb22-442b-aac2-7f944013e418)

**Comment by jdalton** [comment]
```js
console.log(Module._resolveFilename('@tevm/contract', null, false)); // works in bun
```

**Comment by elix1er** [comment]
bump

**Comment by henrikvilhelmberglund** [comment]
Also an issue when using TutorialKit. Above workaround did not work for me.
