### ISSUE TITLE
programmatic access to watch mode  in Bun.build

### ISSUE THREAD

**Issue by terrablue** [oven-sh/bun#8975]
### What is the problem this feature would solve?

esbuild, to which Bun.build's API is pretty similar, has `esbuild.context` which creates a reusable build context which can then be [watched](https://esbuild.github.io/api/#watch). Bun's watch mode is only available in the CLI.

### What is the feature you are proposing to solve the problem?

Expose a watchable object (either esbuild's `context` or something similar) that allows watching the build.

### What alternatives have you considered?

Use esbuild.

**Comment by paperclover** [comment]
Duplicate of #5866
