### ISSUE TITLE
Confusing "Cannot access uninitialized variable"

### ISSUE THREAD

**Issue by ntkoopman** [oven-sh/bun#8983]
### What version of Bun is running?

1.0.27+c34bbb2e3

### What platform is your computer?

Linux 6.6.9-200.fc39.x86_64 x86_64 unknown

### What steps can reproduce the bug?

Run the following code
```ts
console.log(foo);
const foo = false;
```

### What is the expected behavior?

I get a `Cannot access uninitialized variable` message on `foo` on line 1.
```
1 | console.log(foo);
                ^
ReferenceError: Cannot access uninitialized variable.
```

### What do you see instead?

The `ReferenceError: Cannot access uninitialized variable.` is on `console`.
```
1 | console.log(foo);
    ^
ReferenceError: Cannot access uninitialized variable.
```

**Comment by paperclover** [comment]
Duplicate of #8441

not the same exact error but underlying cause
