### ISSUE TITLE
Response and coppied stream does not terminate properly and sends additional bytes after body

### ISSUE THREAD

**Issue by KilianB** [oven-sh/bun#8984]
### What version of Bun is running?

1.0.27

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

This time I got an 100% reproducable example. Run the following code. Postman, Wireshark and curl all complain about broken tcp frames. From within javascript the original and both cloned buffers report identical bytes.

````ts
Bun.serve({
  port: 8080,
  async fetch(req) {
    const res = new Response('Bun!');
    const [stream0, stream1] = res.body!.tee();

    //[ 66, 117, 110, 33 ]
    return new Response(stream0);
  },
});
````

### What is the expected behavior?

The http request to work with a forked stream.

![image](https://github.com/oven-sh/bun/assets/9025925/ff4f9e2b-5df6-4533-a19d-86cdc957d700)

### What do you see instead?

Additional header data is returned after the body was already submitted

![image](https://github.com/oven-sh/bun/assets/9025925/c6794b4e-38fb-4c28-b5ec-67c5a92eb998)

### Additional information

I saw a `// Trace/breakpoint trap`  error message twice.

**Comment by ricardojmendez** [comment]
I am getting what seems to be the same behavior on bun 1.0.30-1.0.35. The same codebase works on node 21.7.1.

**Comment by cirospaciari** [comment]
I believe this is already fixed.
If you run into this again in the future, please leave a comment.
