### ISSUE TITLE
Port in use throws segmentation fault 

### ISSUE THREAD

**Issue by Drejerdk** [oven-sh/bun#8985]
### What version of Bun is running?

1.0.3 - 1.0.27

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Copied the code from [this example](https://bun.sh/guides/websocket/upgrade) into a ws-server.ts file.

I already have other Bun services running locally on my machine using ports 3000-3010.

```console
% bun ws-server.ts
zsh: segmentation fault  bun ws-server.ts
```

Downgrading to Bun v.1.0.2 shows a more correct error

```console
[0.26ms] ".env"
1 | const server = Bun.serve({
                  ^
error: Failed to start server. Is port 3001 in use?
```

From my testing, it seems that all versions since and including v.1.0.3 shows the segmentation error.

### What is the expected behavior?

When failing to bind the server to the requested port, I'd expect an error indicating this, as Bun did in v1.0.2.

**Comment by paperclover** [comment]
two errors are being thrown at once and webkit has an assertion failure.

heh.

**Comment by ethndotsh** [comment]
I can confirm this also occurs on 1.0.28 (if I'm getting the same error lol) when trying to set my port to 3001 with hono, but strangely it usually fixes itself after a couple restarts of the process?
