### ISSUE TITLE
WebSocket server: Await within async fetch breaks WebSocket handshake when client provides a sub-protocol

### ISSUE THREAD

**Issue by Drejerdk** [oven-sh/bun#8986]
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157
1.0.27+c34bbb2e3

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Whenever the fetch function is async and contains an `await` within the block, the WebSocket handshake will fail, if the client requested a sub-protocol.

```
const server = Bun.serve<{ authToken: string }>({
  port: 3000,
  async fetch(req, server) {
    // The async await below causes the handshake to fail 
    await new Promise((resolve) => setTimeout(resolve, 100))

    const success = server.upgrade(req)
    if (success) {
      return undefined
    }

    return new Response("Hello world!")
  },
  websocket: {
    message: (ws, msg) => console.log(msg)
  },
})

console.log(`Listening on ${server.port}`);
```

### What is the expected behavior?

The WebSocket handshake should be able to handle async functions, even if the client provided a sub-protocol.

**Comment by Drejerdk** [comment]
Updated the description and title.

Originally, I blamed a call to global `fetch` to break the handshake, but in reality it seems to be any `await` within the `async fetch`

**Comment by PaddeK** [comment]
Probably the same issue as mine from a while ago https://github.com/oven-sh/bun/issues/7514

**Comment by wakeupinagear** [comment]
Getting this exact same issue (1006 error code and all) when awaiting `Bun.password.verify`. Removing fixes the error.

```ts
const server = Bun.serve({
    port,
    async fetch(req, server) {
        const url = new URL(req.url);

        if (url.pathname.startsWith('/clusters')) {
            console.log(url.pathname);
            const passwordHash = req.headers.get('authorization') || '';
            if (clusterPassword) {
                const valid = Bun.password.verify(
                    clusterPassword,
                    passwordHash
                );
                if (!valid) {
                    console.log('Stopped unauthorized request');
                    return new Response('Unauthorized', { status: 401 });
                }
            }
        }

        if (server.upgrade(req))
            return;
       
        // rest of http + ws implementation follows
}
```

**Comment by wakeupinagear** [comment]
Update: Bun 1.1.0 fixed this issue for me

**Comment by Drejerdk** [comment]
The async fetch does indeed work now, as long as the client doesn't provide a sub-protocol, ex. 
```new WebSocket("ws://127.0.0.1:3000", ["test"])```

So I guess the issue is not fully resolved - Await within fetch still breaks it in this case.

**Comment by 4-0-9** [comment]
> The async fetch does indeed work now, as long as the client doesn't provide a sub-protocol, ex.
new WebSocket("ws://127.0.0.1:3000", ["test"])

I just tried it on v1.1.1 and I'm getting the same result. Passing sub-protocols results in my sockets closing immediately.

**Comment by PaddeK** [comment]
Can confirm those findings.. omitting the protocol helped at least since 1.0.15. This issue should be merged with #7514 .
Looking at the source my best guess is that corking is not handled correct in this scenario. I am using node with uwebsocket.js at the moment and had similar issues if i am awaiting something and touching the response object after that.

**Comment by Mat4B** [comment]
If the query to the server includes "Sec-Websocket-Protocol" in the header, Bun does not return "Sec-Websocket-Protocol" in the header of the response and Chrome drops the connection (Firefox works).

Chrome expects a response from "Sec-Websocket-Protocol" in the header.

Bun returns "Sec-Websocket-Protocol" when we do not wait for a response (we do not use async/await).
**If we wait with the response (e.g. asynchronous access token verification), Bun does not return "Sec-Websocket-Protocol".**

**Comment by PaddeK** [comment]
Just as update: The problem still persists with bun 1.1.11 and 1.1.12 (canary)
