### ISSUE TITLE
I hope the single file can expose bun's methods.

### ISSUE THREAD

**Issue by haozi** [oven-sh/bun#8988]
### What version of Bun is running?

1.0.27

### What steps can reproduce the bug?

I hope to package it into a single file to provide independent cli commands for users without the bun runtime.

But internally I also want to be able to use capabilities like `bun run xxx.ts`, because after packaging it's already over 50MB, which should contain bun's source code. Is it possible to expose bun's capabilities?

**Comment by Electroid** [comment]
You can compile your application into a single-file executable: https://bun.sh/docs/bundler/executables

**Comment by haozi** [comment]
Sorry, I may not have expressed myself accurately
I now have a `cli.ts` file, I compiled it into a single file `./mycli`
Now I want to implement the `./mycli run hello.ts`
capability.
Yes, I want to call bun's `run` method internally in my code.
