### ISSUE TITLE
support importing react & react-dom with `react-server` condition

### ISSUE THREAD

**Issue by subtleGradient** [oven-sh/bun#8990]
### What is the problem this feature would solve?

building a new library for React Server Components

### What is the feature you are proposing to solve the problem?

support runtime `--conditions` flag like node.js for custom conditional exports
https://nodejs.org/api/cli.html#-c-condition---conditionscondition

> You must configure Node.js using the `--conditions react-server` flag
https://github.com/facebook/react/blob/59831c98cffe0edf706238b067928e7cf54d1065/packages/react-server-dom-esm/server.js#L12

### What alternatives have you considered?

Only way I found to import it is to reach into the node_modules directly. But this doesn't work for requires that happen inside.

Importing `react/react.react-server.js` kindof works:

```ts
import type * as ReactType from "react/canary"
// @ts-expect-error -- couldn't figure out how to pass --conditions to bun
const React = (await import("../node_modules/react/react.react-server.js")) as typeof ReactType
if (!("__SECRET_SERVER_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED" in React))
  throw new Error("expected the React build with server internals")
```

Importing `react-dom.react-server.js` has problems:

```ts
import type * as ReactDOMType from "react-dom/canary"
// @ts-expect-error -- couldn't figure out how to pass --conditions to bun
const ReactDOM = (await import("../node_modules/react-dom/react-dom.react-server.js")) as typeof ReactDOMType
// TODO: figure out how to verify that ReactDOM is the server build
// TODO: figure out how to make sure that ReactDOM is not requiring a different React file
```

PROBLEM: `react-dom.react-server.js` has `require('react')`, which then imports the default build of react instead of the react.react-server.js build :(

**Comment by paperclover** [comment]
I think adding this as a runtime + bundler flag would make sense, and not really be that hard either.

for someone wanting to implement this:

`options.zig` has this code, which initializes the conditions list by default based on --target
```zig
opts.conditions = try ESMConditions.init(allocator, Target.DefaultConditions.get(opts.target));
```

some work on this struct can be added to allow appending onto this list after the default conditions list is created.

**Comment by igorwessel** [comment]
@paperdave I tried to find test files for this specific part of "exports"/"imports" but I didn't find anything specific. Can you give me some direction?

Nevermind, I think I found the test.

https://github.com/oven-sh/bun/blob/b6f3405fa78b937d8a0bc9b00ec5829b176b9f58/test/bundler/esbuild/packagejson.test.ts#L1369
