### ISSUE TITLE
Bun runtime stuck at fetching when using axios library

### ISSUE THREAD

**Issue by rayanfer32** [oven-sh/bun#8996]
### What version of Bun is running?

1.0.27

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
import axios from "axios"

console.log("Fetching data...");

let response = await axios.get("https://trendlyne.com/portfolio/superstar-shareholders/index/institutional")
let htmlContent = response.data
console.log(htmlContent);

console.log("Data fetched")
```

![image](https://github.com/oven-sh/bun/assets/37145078/7efca139-103f-4e81-8dcc-0388183b7cd8)

### What is the expected behavior?

Should not be stuck

### What do you see instead?

Stuck in fetching for long time, this issue occurs randomly in 1/4 tries

### Additional information

I posted the CPU stats as well, unsure what to check. It seems like the buntime issue

**Comment by Electroid** [comment]
Duplicate of #8673
