### ISSUE TITLE
surprising Bun.password.verify behavior for "bcrypt" algorithm

### ISSUE THREAD

**Issue by argosphil** [oven-sh/bun#9009]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Linux 6.1.31-gentoo-dist x86_64 13th Gen Intel(R) Core(TM) i7-1370P

### What steps can reproduce the bug?

From urretf on Discord:

```
const pass = prompt("Enter Password:");
console.log(`Read: ${pass}`);

console.log(`Testing Sync`);

const hash = Bun.password.hashSync(pass, { algorithm: 'bcrypt', cost: 10 });
console.log(`Hash: ${hash}`);

console.log(`Verify result: ${Bun.password.verifySync(pass, hash)}`);

console.log(`Testing Async`);

const hash2 = await Bun.password.hash(pass, { algorithm: 'bcrypt', cost: 10 });
console.log(`Hash: ${hash2}`);

console.log(`Verify result: ${await Bun.password.verify(pass, hash2)}`);

console.log(`Hash from sync and async were equal: ${hash == hash2}`);
```

### What is the expected behavior?

Verify result: true for passwords shorter and longer than 72 characters

### What do you see instead?

Verify result: false if the entered password is longer than 72 characters

### Additional information

This is fairly easy to "fix", but should we? There's a test for the old behavior, and what we're implementing isn't, strictly speaking, the `bcrypt` algorithm.

**Comment by pilcrowonpaper** [comment]
This is kinda expected since Bcrypt has a maximum input limit of 72 bytes. Honestly, Bun should throw instead of silently truncating it

**Comment by argosphil** [comment]
> This is kinda expected since Bcrypt has a maximum input limit of 72 bytes. Honestly, Bun should throw instead of silently truncating it

The current behavior isn't "silently truncating it", though. It's "sha512 on hash, expect the user to know about this and apply sha512 on verify".
