### ISSUE TITLE
`bunx --bun histoire build` hangs

### ISSUE THREAD

**Issue by dszymon** [oven-sh/bun#9011]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

1. create a histoire project: https://histoire.dev/guide/vue3/getting-started.html
2. run `bunx --bun histoire build`

### What is the expected behavior?

```
[...]
✓ built in 1.70s
✅ Built 1 story (1 variant) in 2.64s
```

### What do you see instead?

`Using 9 threads for story collection`

**Comment by birkskyum** [comment]
This ticket uses the new histoire vite plugin, so it's related to, but not a duplicate of the repro in
- #3787

**Comment by paperclover** [comment]
the fact that both hang make it seem like it is the same issue, let's have the original issue track all uses of historire, since people searching for it can find the actual tracking issue for it

Duplicate of #3787
