### ISSUE TITLE
bun install errors out with: `error: FileNotFound`

### ISSUE THREAD

**Issue by SoulHarsh007** [oven-sh/bun#9012]
### What version of Bun is running?

1.0.27+c34bbb2e3

### What platform is your computer?

Linux 6.7.5-2-cachyos x86_64 unknown

### What steps can reproduce the bug?

Running `bun i` in a monorepo causes bun to error out, while `bun update` seems to work just fine.

### What is the expected behavior?

`bun i` should not error out and install the packages.

### What do you see instead?

```sh
❯  bun i
[0.43ms] ".env"
bun install v1.0.27 (c34bbb2e)

error: FileNotFound
Bun could not find a file, and the code that produces this error is missing a better error.

----- bun meta -----
Bun v1.0.27 (c34bbb2e) Linux x64 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 00:04:21 +0000
InstallCommand: dotenv 
Elapsed: 15ms | User: 7ms | Sys: 20ms
RSS: 36.71MB | Peak: 29.81MB | Commit: 36.71MB | Faults: 10
----- bun meta -----
```

### Additional information

The issue is very similar to #1815 
The package.json includes workspaces definition as follows:
```json
"workspaces": [
  "packages/*"
]
```
removing the lockfile causes bun to throw another error, that is:
```
❯  bun i
[0.71ms] ".env"
bun install v1.0.27 (c34bbb2e)
error: workspace dependency "@types/secureflo-api" not found

Searched in "./packages/secureflo-types"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

**Comment by ndilsou** [comment]
I'm getting the same error on a Mac M2 Max.

```
$ bun add wavesurfer.js
[0.36ms] ".env"
bun add v1.0.30 (1424a196)

error: FileNotFound
Bun could not find a file, and the code that produces this error is missing a better error.

----- bun meta -----
Bun v1.0.30 (1424a196) macOS Silicon 23.2.0
AddCommand: dotenv 
Elapsed: 19ms | User: 14ms | Sys: 11ms
RSS: 22.92MB | Peak: 22.92MB | Commit: 34.62MB | Faults: 289
----- bun meta -----
```

I'm also working out of a monorepo.
the error only happens on `bun add` in the sub package that has a `"other-package": "workspace:*"` in the dependencies. 

The error disappears if I remove the other package from the dependencies.

**Comment by lpbonomi** [comment]
I get the following error:

```
bun install v1.0.30 (1424a196)

 + admin@workspace:apps/admin
 + aws-helper@workspace:packages/aws-helper
 + blockchain-helper@workspace:packages/blockchain-helper
 + database@workspace:packages/database
 + e2e@workspace:packages/e2e
 + eslint-config-custom@workspace:packages/eslint-config-custom
 + frontend@workspace:apps/frontend

 7 packages installed [247.00ms]
Failed to install 1 package
error: FileNotFound installing avsc
```

**Comment by LIMPIX31** [comment]
In my case, this was due to a missing `version` in the package.json of the packages

**Comment by Kamilczak020** [comment]
> In my case, this was due to a missing `version` in the package.json of the packages

This helped - in a workspaces setup, It also only worked after setting version in every package.json in the project.

**Comment by SoulHarsh007** [comment]
I can confirm, adding `version` to `package.json` and regenerating `bun.lockb` fixes the problem.
