### ISSUE TITLE
Bun.serve error callback is missing the request

### ISSUE THREAD

**Issue by BennyAlex** [oven-sh/bun#9015]
### What is the problem this feature would solve?

Accessing any information about the request that leads to the error is not possible, since there is no request parameter for the error(errorLike) callback at the moment.

Users want to show different errors based on the url or user information, or as in my case I want to set the CORS headers dynamically to the request's origin.

### What is the feature you are proposing to solve the problem?

Passing the request to error() callback

### What alternatives have you considered?

idk

**Comment by paperclover** [comment]
the reason we dont have this is because the error callback might not always have the request info. if we were to implement this, i imagine it would be sort of 'best effort' and potentially null / invalid. not sure of the full details

**Comment by BennyAlex** [comment]
ok but I guess in many cases it will be available and then of course we have to check if its there or not but still better than no info at all
