### ISSUE TITLE
process.env being replaced by the string value of the variables during `bun build`

### ISSUE THREAD

**Issue by 101dal** [oven-sh/bun#9016]
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Build a project with the command `bun build target=bun --minify`.
This project should contain environment variables imported with `process.env.VARIABLE`
Example of the `.env` file:
`VARIABLE=Thisisavariable`

### What is the expected behavior?

When building the project, the `process.env.VARIABLE` should be visible on search (or an equivalent)

### What do you see instead?

The `process.env.VARIABLE` is replaced by it's value in the environment file.
For the given example in the code there is directly:
`Thisisavariable`

### Additional information

The expected behavior can be obtained when replacing `process.env.VARIABLE` by `Bun.env.VARIABLE`

**Comment by Electroid** [comment]
Duplicate of #8125
