### ISSUE TITLE
Npm link equivalent

### ISSUE THREAD

**Issue by EladBezalel** [oven-sh/bun#902]
### What is the problem this feature will solve?

a way to link between npm packages using an `npm link` like api

### What is the feature you are proposing to solve the problem?

`bun link`

**Comment by Jarred-Sumner** [comment]
yeah this would be nice

**Comment by usrtax** [comment]
v0.1.8

use `bun link @iuser/ui` work , but use `bun i` not work
```
error: DanglingSymlink "link:@iuser/ui" not found (try running 'bun link' in the intended package's folder)
```

devDependencies use "@iuser/ui": "link:../ui" is in package.json


<img width="1074" alt="image" src="https://user-images.githubusercontent.com/110233389/184107613-c1404835-49d8-471d-a4e3-b0931299b2de.png">

**Comment by xhyrom** [comment]
bun link is already implemented

**Comment by wacdev** [comment]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/127726508/225329710-e989b1e1-092d-454f-8a3f-838db6740781.png">

`bun i` not work with link:../_ in pacakge.json as image above

**Comment by branaway** [comment]
@Jarred-Sumner @xhyrom
