### ISSUE TITLE
Bun install fails to find dependency version for range specification

### ISSUE THREAD

**Issue by tylergannon** [oven-sh/bun#9023]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

From shell prompt:
```
bun install eslint-plugin-svelte@2.36.0-next.5
```

### What is the expected behavior?

Install package successfully

### What do you see instead?

bun add v1.0.28 (70563847)

error: No version matching ">=0.34.0-next.4 <1.0.0" found for specifier "svelte-eslint-parser" (but package exists)

### Additional information

pnpm can install the same package no problem.

The requested package depends on svelte-eslint-parser@">=0.34.0-next.4 <1.0.0"

This package is installed during creation of a new Svelte app, if the Svelte 5.0.0 alpha is requested.

**Comment by dylan-conway** [comment]
Looks like we are missing some of the logic mentioned in this comment https://github.com/npm/node-semver/blob/ac9b35769ab0ddfefd5a3af4a3ecaf3da2012352/classes/range.js#L514
