### ISSUE TITLE
bun build --watch to pick up new files defined as entry points

### ISSUE THREAD

**Issue by sergeifilippov** [oven-sh/bun#9028]
### What is the problem this feature would solve?

`bun build ./src/*.ts --outdir ./dist --watch` does not recognise new files being added to or renamed in `.src` folder.

Process has to be restarted for new files to be recognised.

### What is the feature you are proposing to solve the problem?

Add ability for the `---watch` recognise changes glob based entries including:

- adding new files
- renaming files
- deleting files

### What alternatives have you considered?

Tried running `nodemon` as the watch process.
Tried

**Comment by Electroid** [comment]
This isn't something we can support, since the glob will be parsed by your shell.
