### ISSUE TITLE
Bun build overriding node_modules packages 

### ISSUE THREAD

**Issue by mGranTY** [oven-sh/bun#9033]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64 | Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1 -create a new folder  
2 - `bun init -y`
3- `bun i viem`
4 - move `index.ts` to `src/index.ts` (create a src folder and move it)
4 - add this code inside `index.ts`:
```ts
import {createPublicClient, http, parseAbi, signatureToHex, keccak256, stringToHex} from 'viem'
import {polygon} from 'viem/chains'
import {sign} from "viem/accounts";

const client = createPublicClient({
    chain: polygon,
    transport: http(),
    batch: {
        multicall: true,
    }
})

const a = client.watchContractEvent({
    address: '0x0b629f47430E7070FB7864cA3affDc2643aB59c3' as `0x${string}`,
    abi: parseAbi(['event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)']),
    eventName: 'Transfer',
    batch: true,
    onLogs: function (logs: any): void {
        console.log(logs)
    }
})


const account = [
    {
        address: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
        balance: 10000000000000000000000n,
        privateKey:
            '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
    }
] as const

const signature = signatureToHex(
    await sign({
        hash: keccak256(stringToHex('jxom.viem')),
        privateKey: account[0].privateKey,
    }),
)


```
5 - create build.ts in the main folder(outside src):
```ts
const result = await Bun.build({
    entrypoints: ["src/index.ts"],
    minify: true,
    outdir: "dist",
    target: "bun",
    splitting: true,
    sourcemap: "external",
})

if (!result.success) {
    console.error("Build failed");
    for (const message of result.logs) {
        console.error(message);
        process.exit(0)
    }
}else{
    console.info("Build Successful");
    for (const message of result.logs) {
        console.info(message);
    }
}
```

6 - run `bun run build.ts` twice:
 - First run:
   `->bun run build.ts`
  `->Build Successful`
  - Second run:
   `->bun run build.ts`
  `->Build failed`
  `->Could not resolve: "../../../{projectName}/chunk-25e1f98dab1f766d.js"
    at /home/granty/IdeaProjects/debug/node_modules/isows/_esm/native.js:2:7`

### What is the expected behavior?

Build Successful 

### What do you see instead?

Build failed with error

### Additional information

For some reason bun build is writing the build result in node modules, overriding the original modules. If u move index.ts back to the main folder (outside src/index) and run the how to fix steps, it should work as intendeed(copy the node modules to dist)

How to fix:

`rm -rf ~/.bun/install/cache`
`rm -rf node_modules/`

then `bun i` and `bun run build.ts` (only works the first time)

**Comment by paperdave** [comment]
going though issues; i remember this was fixed some time ago (i don't recall the exact version, but i cant reproduce anymore).
