### ISSUE TITLE
Bun keeps installing and updating packages at the latest version and ignores the version specified in package.json

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#9045]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

WSL output:  Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64 

Windows output: Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Step 1: copy and paste these commands into your terminal
```bash
bun create svelte frontend
cd frontend
bun i
```

Step 2: Compare the version that Bun installed and the version specified in package.json

### What is the expected behavior?

**Package.json:**

![image](https://github.com/oven-sh/bun/assets/146823477/658b9643-1634-4d9c-b11c-f09548e730b1)

### What do you see instead?

**And the packages that Bun installs:**

![image](https://github.com/oven-sh/bun/assets/146823477/ed7fd565-956a-4e6c-9b17-c0131030b02a)

### Please fix this major bug ASAP!

**Comment by yschroe** [comment]
Maybe I am missing something but the installed versions look good to me. The `^` allows newer versions of a package to be installed, as long as they belong to the same major version (see https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004). 

If you want the exact same package to be installed the `^` needs to be removed, like for `@types/eslint`.

**Comment by ghost** [comment]
@yschroe Thanks, it worked
