### ISSUE TITLE
Can't import jsonc as config file

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#9055]
### What version of Bun is running?

1.0.27+c34bbb2e3

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Bun.sh can't read jsonc file from import

```js
const jsonc = await import('./services.config.jsonc');

console.log('jsonc: ', jsonc);
```

### What is the expected behavior?

return an object as :

```js
{
 a: "a",
 b: "b"
}
```

### What do you see instead?

```js
Module {
  default: "./services.config.jsonc",
}

```

### Additional information

I want to use config file in jsonc format for comments

**Comment by Jarred-Sumner** [comment]
hmm this is supposed to work but i don't think we have tests for it

**Comment by truongan07** [comment]
@Jarred-Sumner Hi my friend, jsonc is very useful when used to create a config file. We need more comments to describe keys.

**Comment by Delapouite** [comment]
Here is the relevant part in `fs.zig`: https://github.com/oven-sh/bun/blob/main/src/fs.zig#L1668-L1675

```zig
    pub fn isJSONCFile(this: *const Path) bool {
        const str = this.name.filename;
        if (!(strings.hasPrefixComptime(str, "tsconfig.") or strings.hasPrefixComptime(str, "jsconfig."))) {
            return false;
        }

        return strings.hasSuffixComptime(str, ".json");
    }
```

So

`tsconfig.json`
```jsonc
{
  // comment
  "foo": "bar"
}
```

`index.js`
```js
const jsonc = await import('./tsconfig.json');

console.log('jsonc: ', jsonc);
```

```sh
bun run index.js
jsonc:  Module {
  default: {
    foo: "bar",
  },
  foo: "bar",
}
```

**Comment by truongan07** [comment]
resolved in v.1.1.5

```
import jsonc from './config/services.config.jsonc' with { type: 'text' };
```

Thank you support

**Comment by truongan07** [comment]
resolved in v.1.1.5

```
import jsonc from './config/services.config.jsonc' with { type: 'text' };
```

Thank you support

**Comment by RiskyMH** [comment]
btw I added better support for this in #16244 where it should just be able to import `*.jsonc` by default and parse it as jsonc.
