### ISSUE TITLE
bunx create-next-app@latest freezes

### ISSUE THREAD

**Issue by khaireddine-arbouch** [oven-sh/bun#9056]
### What version of Bun is running?

1.0.28-canary.13+260572289

### What platform is your computer?

x64

### What steps can reproduce the bug?

I don't know how to resolve the issue, since it didn't even return any error

### What is the expected behavior?

Running bunx create-next-app@latest should start building a Next-js project by asking some questions about the project setup

### What do you see instead?

when i run bunx create-next-app@latest it freezes for a little bit and then exit to start a new command

```
khair@khaireddine MINGW64 ~/OneDrive/Desktop/Portfolio Projects/revamp (master)
$ bunx create-next-app@latest 

khair@khaireddine MINGW64 ~/OneDrive/Desktop/Portfolio Projects/revamp (master)
$
```
![Screenshot 2024-02-23 013203](https://github.com/oven-sh/bun/assets/66341920/d074484e-e605-4cab-9ade-8843caa52fd1)

**Comment by Electroid** [comment]
What computer are you running this on? macOS? Linux?

**Comment by khaireddine-arbouch** [comment]
I'm using windows 11

**Comment by paperclover** [comment]
the bug was bunx calling `selfExePath() install <package>`, which on windows is not a symlink, so it just ran bunx recursively. this will be fixed in the linked pr
