### ISSUE TITLE
incorrect behavior with shell

### ISSUE THREAD

**Issue by qcdong2016** [oven-sh/bun#9060]
### What version of Bun is running?

1.0.28

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

➜  ~ cat ./1.ts
import {$} from "bun"
await $ `echo $(pwd)/123`
➜  ~ bun 1.ts
/Users/mac /123
➜  ~ echo $(pwd)/123
/Users/mac/123

### What is the expected behavior?

/Users/mac/123

### What do you see instead?

/Users/mac /123
<img width="276" alt="Screenshot 2024-02-23 at 11 16 31" src="https://github.com/oven-sh/bun/assets/6292878/dbaaa3ab-d614-41f8-a5ce-7e6fc1c3a4e2">

**Comment by Jarred-Sumner** [comment]
This is fixed in Bun v1.0.29, which releases tonight

To try it now, run `bun upgrade --canary` and please leave a comment if you continue to run into this.

**Comment by zackradisic** [comment]
To be clear this was fixed with #9005
