### ISSUE TITLE
bun --version should display additional commit sha

### ISSUE THREAD

**Issue by moderation** [oven-sh/bun#907]
### What is the problem this feature will solve?

`bun --version` will display `0.1.5` for both the release version of `bun` and the post `0.1.5` canary version. This makes it impossible to tell the real version of `bun` from the command line

### What is the feature you are proposing to solve the problem?

When running `bun --version` on a canary version of `bun` it should display:

`0.1.5-0d4b4c4` 

where the sha matches the canary build commit sha at https://github.com/oven-sh/bun/releases/tag/canary

### What alternatives have you considered?

N/A

**Comment by Electroid** [comment]
We should do this, but may need to wait a few minor releases to fix the check in `bun upgrade`

**Comment by birkskyum** [comment]
can be closed. `bun --revision` does this
