### ISSUE TITLE
Add `bun list` / `bun analyze`

### ISSUE THREAD

**Issue by sequencerr** [oven-sh/bun#9070]
### What is the problem this feature would solve?

Analyzing project dependencies. Maybe in tree view. Maybe more global tool for analyzing. With deprecated label (if any), total disk size, sub-deps count, vulnerabilities severity label (if any), etc.

### What is the feature you are proposing to solve the problem?

`bun list` / `bun tree` (idk)
cli tool

### What alternatives have you considered?

`yarn ls` (no tree) / `npm ls -all`  
Haven't used `snyk`, nor looked into it, but would be great to pack one more tool into bun instead of separate.

**Comment by Jarred-Sumner** [comment]
`bun pm ls` or `bun pm ls -a`
