### ISSUE TITLE
Windows: Bun install fails to download when $Env:http_proxy is set

### ISSUE THREAD

**Issue by ZTL-UwU** [oven-sh/bun#9072]
### What version of Bun is running?

1.0.29

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Set $Env.http_proxy in $PROFILE
    e.g. `$Env:http_proxy = "http://127.0.0.1:7890"; $Env:https_proxy = "http://127.0.0.1:7890"`
3. Init a bun project
4. Add some dependencies.

e.g.
```
bun init
bun add react
```

### What is the expected behavior?

Dependencies being installed correctly.

### What do you see instead?

```
bun add v1.0.29-canary.22 (5147c0ba)
  🔍 @types/bun [11/12]
error: Syscall downloading package manifest @types/bun
  🔍 @types/bun [11/12]
error: Syscall downloading package manifest react
  🔍 typescript [18/18]
error: Syscall downloading package manifest typescript
error: @types/bun@latest failed to resolve
error: react@ failed to resolve
```

### Additional information

With `--verbose`:

<details><summary>Details</summary>
<p>

```
bun add v1.0.29-canary.22 (5147c0ba)
Enqueue package manifest for download: @types/bun

 [0.00ms] [cache hit] react
Enqueue package manifest for download: react
  🔍 Resolving [1/2] [PackageManager] waiting for 2 tasks
Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Request: GET /react
        If-None-Match: W/"d13fe651ecc5eadfbb486c6b999d9db2"
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

  🔍 @types/bun [11/12]
error: Response: < 200 Connection established

Syscall downloading package manifest @types/bun
  🔍 react [12/12]
error: Syscall downloading package manifest react
Enqueue package manifest for download: typescript
Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.29
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

  🔍 typescript [18/18]
error: Syscall downloading package manifest typescript
warn: warn: Syscall downloading package manifest @types/bun

warn: warn: Syscall downloading package manifest react

warn: warn: Syscall downloading package manifest @types/bun

warn: warn: Syscall downloading package manifest react

warn: warn: Syscall downloading package manifest @types/bun

warn: warn: Syscall downloading package manifest react

warn: warn: Syscall downloading package manifest @types/bun

warn: warn: Syscall downloading package manifest react

warn: warn: Syscall downloading package manifest @types/bun

warn: warn: Syscall downloading package manifest react

warn: warn: Syscall downloading package manifest typescript

warn: warn: Syscall downloading package manifest typescript

warn: warn: Syscall downloading package manifest typescript

warn: warn: Syscall downloading package manifest typescript

warn: warn: Syscall downloading package manifest typescript
error: @types/bun@latest failed to resolve
error: react@ failed to resolve
```

</p>
</details>

**Comment by aihuasxy** [comment]
same problem with me!

bun install v1.1.0 (5903a614)
Enqueue package manifest for download: @types/bun
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

**Comment by thatsgolden** [comment]
the same goes for Clash users:

<details>

<code lang="powershell">
bun install v1.1.0 (5903a614)
info: cannot move files from tempdir: RenameAcrossMountPoints, using fallback
Enqueue package manifest for download: @types/bun
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

  🔍 @types/bun [6/6]
error: Syscall downloading package manifest @types/bun
Enqueue package manifest for download: typescript
Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

Request: GET /typescript
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.1.0
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 Connection established

  🔍 typescript [12/12]
error: Syscall downloading package manifest typescript
warn: Syscall downloading package manifest @types/bun

warn: Syscall downloading package manifest @types/bun

warn: Syscall downloading package manifest @types/bun

warn: Syscall downloading package manifest @types/bun

warn: Syscall downloading package manifest @types/bun

warn: Syscall downloading package manifest typescript

warn: Syscall downloading package manifest typescript

warn: Syscall downloading package manifest typescript

warn: Syscall downloading package manifest typescript

warn: Syscall downloading package manifest typescript
Clean lockfile: 1 packages - 1 packages in 57.4us
error: @types/bun@latest failed to resolve
</code>
</details>

**Comment by manudss** [comment]
I have the same problem. Http_proxy was settled. And I need to have it settled, are under corporate proxy, cannot do without it.

**Comment by zhuweiyou** [comment]
same issue

```bash
bun install v1.1.2 (c8d072c2)
  🔍 vite [11/12]
error: Syscall downloading package manifest vite
```

**Comment by Guyutongxue** [comment]
> same issue
> 
> 
> 
> ```bash
> 
> bun install v1.1.2 (c8d072c2)
> 
>   🔍 vite [11/12]
> 
> error: Syscall downloading package manifest vite
> 
> ```

Bro, replying "same issue" does not help anything; it doesn't provide any useful information to fix the bug. You can just press the emoji ("reaction") button. 🙂

**Comment by aihuasxy** [comment]
I would like to help pinpoint this issue, but I'm unsure where to start. I'm ready to compile 'bun' locally and then debug it, but since the compilation process for 'bun' also requires 'bun install', it becomes a chicken-and-egg problem.

**Comment by ZTL-UwU** [comment]
> I would like to help pinpoint this issue, but I'm unsure where to start. I'm ready to compile 'bun' locally and then debug it, but since the compilation process for 'bun' also requires 'bun install', it becomes a chicken-and-egg problem.

I believe you can run the bun install script for bun itself without setting the proxy.

**Comment by aihuasxy** [comment]
> > I would like to help pinpoint this issue, but I'm unsure where to start. I'm ready to compile 'bun' locally and then debug it, but since the compilation process for 'bun' also requires 'bun install', it becomes a chicken-and-egg problem.
> 
> I believe you can run the bun install script for bun itself without setting the proxy.


(base) PS E:\github\bun> bun install
bun install v1.1.2 (c8d072c2)
  🔍 Resolving...
error: Syscall downloading tarball scheduler@0.24.0-canary-09fbee89d-20231013
  🔍 Resolving...
error: Syscall downloading tarball ignore@5.2.4
  🔍 Resolving...
error: Syscall downloading tarball @eslint/js@8.51.0
  🔍 Resolving...
error: Syscall downloading tarball no-case@3.0.4
.
.
.

**Comment by ZTL-UwU** [comment]
Is $Env:http_proxy present in your Powershell's $PROFILE?

**Comment by aihuasxy** [comment]
> Is $Env:http_proxy present in your Powershell's $PROFILE?

Yes http_proxy and https_proxy in both $Env and file $PROFILE.
BTW: I'm using the company network, which has a firewall, and all access needs to go through the proxy.

**Comment by ZTL-UwU** [comment]
https://github.com/oven-sh/bun/blob/7b5065c1c9d46d838d23f0279a508d0bae3357bd/src/http.zig#L2632-L2644

The problem is with `proxy.ssl.handshake()`, which throws an `error.Syscall`.

**Comment by sansan-mei** [comment]
> https://github.com/oven-sh/bun/blob/7b5065c1c9d46d838d23f0279a508d0bae3357bd/src/http.zig#L2632-L2644
> 
> The problem is with `proxy.ssl.handshake()`, which throws an `error.Syscall`.

how to fix that?

**Comment by hero** [comment]
The same problem...

```
error: Syscall downloading tarball @types/bun@1.1.6
error: Syscall downloading tarball typescript@5.5.3
error: Syscall downloading tarball bun-types@1.1.17
error: Syscall downloading tarball @types/node@20.12.14
error: Syscall downloading tarball @types/ws@8.5.11
error: Syscall downloading tarball undici-types@5.26.5```

**Comment by 442283045** [comment]
same problem:
❯ bun create vue
error: Syscall downloading package manifest create-vue

**Comment by guyutongxue** [comment]
Seems fixed by #12750

**Comment by LeonKohli** [comment]
Error persists for me in latest version:

```pwsh
 bun i tailwindcss
bun add v1.1.26 (0a37423b)
error: Syscall downloading package manifest tailwindcss
```

**Comment by guyutongxue** [comment]
> Error persists for me in latest version:
> 
> 
> 
> ```pwsh
> 
>  bun i tailwindcss
> 
> bun add v1.1.26 (0a37423b)
> 
> error: Syscall downloading package manifest tailwindcss
> 
> ```

@LeonKohli new version with the patch not released yet 😄 you can try the canary version by `bun upgrade --canary`

**Comment by LeonKohli** [comment]
Oh, thought this was already in latest, thanks!
