### ISSUE TITLE
Bun fast-json-stringify

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#9077]
### What is the problem this feature would solve?

Perhaps this would make Web frameworks like [Elysia](https://elysiajs.com/) even faster and raise the Bun in benchmarks!
in Node.JS Runtime [fast-json-stringify](https://github.com/fastify/fast-json-stringify) implementation 2x faster than JSON.stringify 
![image](https://github.com/oven-sh/bun/assets/57632712/cd90726c-89c4-4dd6-9373-43eb14ad9a83)
but in Bun, JSON.stringify is incredibly fast! Maybe fast-json-stringify can be done even faster?
usage example - 
```ts
const fastJson = require('fast-json-stringify')
const stringify = fastJson({
  title: 'Example Schema',
  type: 'object',
  properties: {
    firstName: {
      type: 'string'
    },
    lastName: {
      type: 'string'
    },
    age: {
      description: 'Age in years',
      type: 'integer'
    },
    reg: {
      type: 'string'
    }
  }
})

console.log(stringify({
  firstName: 'Matteo',
  lastName: 'Collina',
  age: 32,
  reg: /"([^"]|\\")*"/
}))
```

### What is the feature you are proposing to solve the problem?

It is possible to make another Bun API that would implement [fast-json-stringify](https://github.com/fastify/fast-json-stringify)

**Comment by jdalton** [comment]
In this case Bun's native `JSON.stringify` looks to be almost 2x that of fast-json-stringify in the first benchmark and close to it in the second. As fast-json-stringify loses its advantage with larger payloads I think Bun's sitting in a great spot to use the platform (bun).  @kravetsone if json perf is a passion of yours please keep us updated :)

**Comment by kravetsone** [comment]
> In this case Bun's native `JSON.stringify` looks to be almost 2x that of fast-json-stringify in the first benchmark and close to it in the second. As fast-json-stringify loses its advantage with larger payloads I think Bun's sitting in a great spot to use the platform (bun).  @kravetsone if json perf is a passion of yours please keep us updated :) 


Bun's native JSON.stringify is really incredible! I think it would be possible to make it faster using JSON Schema as fast-json-stringify does. the existing implementation loses to Bun native JSON.stringify, but maybe the implementation in Bun would work even faster?

I just find it interesting because in 99% of cases it is the small size of payloads that are transmitted over the network
