### ISSUE TITLE
Straight Docker instructions would be useful

### ISSUE THREAD

**Issue by jdmarshall** [oven-sh/bun#910]
### Affected URL(s)

https://github.com/oven-sh/bun#developing-bun

### Description of the problem

Heavy brew commands don't compose well with other applications that may need to run on a machine. Especially if the only reason for installing almost a dozen modules is just to be able to build a docker image??

Are either of the Dockerfiles included in the source code suitable for allowing someone to experiment with compiling and running bun?

**Comment by jdmarshall** [comment]
see also #814 #743 

Too many moving parts scares people off.

**Comment by jecepeda** [comment]
I agree with what you said. 

I've tried to develop bun both in OSX and Linux and it seems impossible

**Comment by Electroid** [comment]
Totally agree that we need to improve the build process, we've made a lot of changes since you opened this issue, but we still have a lot of work to do. Will track this in an umbrella issue so we can make this better.
