### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rojvv** [oven-sh/bun#911]
### Version

0.1.5

### Platform

x86_64 GNU/Linux

### What steps will reproduce the bug?

1. I did bun:

```shell
$ bun
```

2. I got the Discord server:

```shell
$ bun discord
```

3. I joined the Discord server.
5. I opened the `#releases` channel.
6. I opened a release page on GitHub.
7. I found the repository's homepage.
8. I opened the repository's homepage.
9. I saw the README.
10. I read the README.
11. I continued reading.
12. I scrolled down.
13. I got to the FFI section.
14. I got to the Low-overhead FFI subsection.
15. I read a line.
16. I read another line.
17. I read one more line.
18. I got to a line with a link to a benchmark.
19. I followed the link.
20. I got HTTP/1.1 404 Not Found.
21. I then figured out it is a broken link.
22. I opened this issue.

### How often does it reproduce? Is there a required condition?

It is reproduce every time I...

1. I do bun:

```shell
$ bun
```

2. I get the Discord server:

```shell
$ bun discord
```

3. I join the Discord server.
5. I open the `#releases` channel.
6. I open a release page on GitHub.
7. I find the repository's homepage.
8. I open the repository's homepage.
9. I see the README.
10. I read the README.
11. I continue reading.
12. I scroll down.
13. I get to the FFI section.
14. I get to the Low-overhead FFI subsection.
15. I read a line.
16. I read another line.
17. I read one more line.
18. I get to a line with a link to a benchmark.
19. I follow the link.

### What is the expected behavior?

The experience should feel smooth, just like as follows:

It is reproduce every time I...

1. I do bun:

```shell
$ bun
```

2. I get the Discord server:

```shell
$ bun discord
```

3. I join the Discord server.
5. I open the `#releases` channel.
6. I open a release page on GitHub.
7. I find the repository's homepage.
8. I open the repository's homepage.
9. I see the README.
10. I read the README.
11. I continue reading.
12. I scroll down.
13. I get to the FFI section.
14. I get to the Low-overhead FFI subsection.
15. I read a line.
16. I read another line.
17. I read one more line.
18. I get to a line with a link to a benchmark.
19. I follow the link.
20. I should get HTTP/1.1 200 OK.

### What do you see instead?

I see this bad experience instead:

1. I do bun:

```shell
$ bun
```

2. I get the Discord server:

```shell
$ bun discord
```

3. I join the Discord server.
5. I open the `#releases` channel.
6. I open a release page on GitHub.
7. I find the repository's homepage.
8. I open the repository's homepage.
9. I see the README.
10. I read the README.
11. I continue reading.
12. I scroll down.
13. I get to the FFI section.
14. I get to the Low-overhead FFI subsection.
15. I read a line.
16. I read another line.
17. I read one more line.
18. I get to a line with a link to a benchmark.
19. I follow the link.
20. I get HTTP/1.1 404 Not Found.
21. I then figure out it is a broken link.

### Additional information

The above is enough for today.

**Comment by xhyrom** [comment]
https://github.com/oven-sh/bun/tree/main/bench/ffi
