### ISSUE TITLE
Update path bits when we update Zig for unpaired surrogates support in Windows

### ISSUE THREAD

**Issue by jdalton** [oven-sh/bun#9122]
Zig now supports unpaired surrogates in Windows paths https://github.com/ziglang/zig/pull/19005!
It means Bun will need to change `error.InvalidUtf8` to `error.InvalidWtf8` with its Zig update. There's also added methods
* std.fs.path.fmtAsUtf8Lossy/fmtWtf16LeAsUtf8Lossy
* std.unicode.fmtUtf8

**Comment by Jarred-Sumner** [comment]
We should generally avoid using `std.unicode.*` at runtime (comptime is fine) and we have existing string formatting code that handles utf-16 & wtf-8 conversion. Zig's code for this is not as well tested as ours and slower

**Comment by jdalton** [comment]
Good to know. The change in Zig seems to touch many things so there may be more adjustments needed. [The PR](https://github.com/ziglang/zig/pull/19005) has a pretty good summary. An example of some changes include:

> * `std.unicode` was refactored a bit and function names were made more consistent (e.g. lowercase le changed to the more common Le)
>* WTF-8 <-> WTF-16 conversion and related functions were added to std.unicode
>* WASI now properly handles ILSEQ errors and returns error.InvalidUtf8 (now a WASI-only error) in that case
>* Windows now does WTF-16 <-> WTF-8 conversion everywhere, and errors with error.InvalidWtf8 (a Windows-only error) if any user-supplied inputs are invalid WTF-8
>* Anything that incorrectly talked about UTF-8 was fixed (e.g. NativeUtf8ComponentIterator was previously incorrectly named [by me])
>* Some error sets were updated/narrowed/made explicit

And

> __std.unicode changes__
Renamed functions for consistent Le capitalization and conventions:
>
>utf16leToUtf8Alloc -> utf16LeToUtf8Alloc
utf16leToUtf8AllocZ -> utf16LeToUtf8AllocZ
utf16leToUtf8 -> utf16LeToUtf8
utf8ToUtf16LeWithNull -> utf8ToUtf16LeAllocZ
fmtUtf16le -> fmtUtf16Le
New UTF related functions:
>
>utf16LeToUtf8ArrayList
utf8ToUtf16LeArrayList
utf8ToUtf16LeAlloc
isSurrogateCodepoint
(the ArrayList functions are mostly to allow the Alloc and AllocZ functions to share an implementation)
>
>__New WTF related functions/structs:__
>
>wtf8Encode
wtf8Decode
wtf8ValidateSlice
Wtf8View
Wtf8Iterator
wtf16LeToWtf8ArrayList
wtf16LeToWtf8Alloc
wtf16LeToWtf8AllocZ
wtf16LeToWtf8
wtf8ToWtf16LeArrayList
wtf8ToWtf16LeAlloc
wtf8ToWtf16LeAllocZ
wtf8ToWtf16Le
wtf8ToUtf8Lossy
wtf8ToUtf8LossyAlloc
wtf8ToUtf8LossyAllocZ
Wtf16LeIterator

**Comment by paperclover** [comment]
i was closely following that pr. it is very exciting to see it finally merged.

the pr contains breaking changes, so it will force someone to address the unicode changesw when upgrade. probably  a good chance to double check each usage is valid, when we should use simdutf instead.

> we have existing string formatting code that handles utf-16 & wtf-8 conversion.

didn't know, very cool to see. i think in the zig upgrade we should move away from everything. but there are also some things in the standard library that were copied from Zig to correct, and those can now be deleted from our codebase.

i dont really see a need for this issue to exist, because it is all work that will come from "upgrade to 0.12 stable" or whichever release we pick, which is a load more than just unicode changes

**Comment by jdalton** [comment]
@paperdave

Things like 
> i don't really see a need for this issue to exist,

promote a lot of "STOP" energy. In that it stops folks cold without directing to a wanted outcome or solution. By your own words you learned something from this issue:
> didn't know, very cool to see. 

and we have things to be aware of
* > the pr contains breaking changes, so it will force someone to address the unicode changes when upgrade. probably a good chance to double check each usage is valid, when we should use simdutf instead.
and 

* > but there are also some things in the standard library that were copied from Zig to correct, and those can now be deleted from our codebase.


Devs should feel safe to raise awareness or try to improve the project without fear of being roadblocked at every step. 

Notice the difference in style from [a recent interaction](https://github.com/oven-sh/bun/pull/8949#pullrequestreview-1886485626):
> 
><img width="915" alt="a" src="https://github.com/oven-sh/bun/assets/4303/580ef142-a5f3-4c0a-bb28-97c06035e070">
Here I restated the intent _(gleaned from a code comment at the time before rebase)_, provided positive reenforcement, and a nudge in a direction with a desired outcome. I recognize that getting signal from the noise is a challenge in CI runs. I'm building on the intent, and inviting discussion.

vs.
><img width="929" alt="b" src="https://github.com/oven-sh/bun/assets/4303/616a0ab2-43e2-4120-84f1-b763dd84180a">

The literal red X, the "Do not use" reprimand. With no actionable direction the issue stalls and is closed. 

<img width="307" alt="c" src="https://github.com/oven-sh/bun/assets/4303/d89a80bc-134f-4b44-80d8-e4988db5a949">

If we weren't all core friends we might have lost a contributor for good. It certainly isn't a great internal feel to be on the receiving end of it.

I'm a big fan of incremental improvement. In my experience even if something isn't perfect, being malleable, and giving folks time to work through things has proven beneficial time and time again.

Here instead of _"i dont really see a need for this issue to exist"_ It would be helpful to know if we have an issue tracking the "upgrade to zig 0.12 stable" task already and if not being invited to create one. Now, instead of feeling down for daring to open an issue I'm given a task to create an issue, tracking the future upgrade, ensuring things don't fall through the cracks, and helping future us out 😸

**Comment by paperclover** [comment]
I'm sorry. thanks for being extremely constructive about my interactions. i will improve.

i should have said before that i'm very glad that you caught this pr from zig, and took action to log it in the issue tracker. 

> It would be helpful to know if we have an issue tracking the "upgrade to zig 0.12 stable" task already and if not being invited to create one. 

we don't have one right now, could we make this the 'upgrade the zig compiler' issue? it is something that is talked about sometimes but there isnt an issue logged. 

i have two things on my mind related to the upgrade that are worth sharing:

- should we upgrade to 0.12 stable when it comes out?, or are we just going to continue to upgrade to specific nightly releases. i don't have any strong opinion, but i should note that there is easy tooling in the repo to bump the version. a reason to keep nightly is smaller bumps of breaking changes, as well as ZLS using the nightly (new editor features come to us sooner).
- i think we want to release bun 1.1 before zig compiler is upgraded, which is full of breaking changes just from 0.12.0-dev.1828 -> current nightly. many places for mistaken refactors

i should also share this search filter that i use to see what prs they label as breaking, however it doesn't contain everything as tagging is not perfect:

`zig/ziglang`: [`is:pr is:merged label:breaking merged:>2023-12-09 `](https://github.com/ziglang/zig/pulls?q=is%3Apr+is%3Amerged+label%3Abreaking+merged%3A%3E2023-12-09+)
