### ISSUE TITLE
`bun build --target bun` causes unicode variable names to break

### ISSUE THREAD

**Issue by johannesspohr** [oven-sh/bun#9131]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Create a file `index.js`:
```
const ä = "hello";
console.log(ä);
```

`bun run index.js` prints `hello` as expected

After running `bun build index.js --outdir dist --target bun`, `run run dist/index.js` fails with:
```
SyntaxError: Invalid character '\u00a4'
```

Removing the `// @bun` at the top of the dist file makes it work again.

### What is the expected behavior?

It should behave as running it directly

### What do you see instead?

```
SyntaxError: Invalid character '\u00a4'
```

**Comment by Jarred-Sumner** [comment]
yeah we should be printing these as latin1 escaped values. This is a regression that we do not do that. There is a flag missing somewhere in the bundler code.

**Comment by paperdave** [comment]
this does not reproduce anymore
