### ISSUE TITLE
SvelteKit API endpoint stuck on access request body

### ISSUE THREAD

**Issue by oskar-gmerek** [oven-sh/bun#9145]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

1. Setup SvelteKit and run with command `bun --bun run dev`
2. Create +server.ts under routes/api
3. +server.ts content:
```svelte
import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ request }) => {
	const data = await request.json();
	return json(data);
 };
 ```
 4. Send API call to that endpoint, for example with content:
 ```json
 {
 "status": "good"
 }
 ```
 5. Observe that request will stuck on `await request.json();` from unknown reason, nothing under that line will not execute,  there is no errors even after a few minutes. Nothing, just stucks.

### What is the expected behavior?

This endpoint should returns same contents that was send to it. Exactly how it will do if we start svelte in node env `bun run dev` instead of `bun --bun run dev`.

Or whatever else, if we change the return, like for example `return json("status": "ok")` should return `"status": "ok"`

### What do you see instead?

It's stuck without any feedback.

### Additional information

I am not sure about it, but this feels for me very similar like old problems that bun had with svelte forms processing, if I remember good, that was some kind of problem with CORS. But take it easy, I was not following this too close and this is only my feelings not properly supported.

**Comment by forcefieldsovereign** [comment]
I couldn't reproduce this - appears to be fixed.

**Comment by oskar-gmerek** [comment]
@forcefieldsovereign Indeed, it looks like this is already fixed. Closing
