### ISSUE TITLE
Problem with sqlite benchmark

### ISSUE THREAD

**Issue by krystofmatejka** [oven-sh/bun#917]
### Version

0.1.5

### Platform

Linux KrystofMat-T14-lin 5.18.0-12.2-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.18-13ubuntu1~jammy (2022-0 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```
git clone git@github.com:oven-sh/bun.git
cd bun/bench
bun run sqlite
```

### What do you see instead?

first problem is:

```
src/download.sh: 2: set: Illegal option -o pipefail
```

and the second problem is [Northwind_large.sqlite.zip](https://raw.githubusercontent.com/jpwhite3/northwind-SQLite3/master/Northwind_large.sqlite.zip) returns 404, but curl downloads it, unzips it which creates an empty `northwind.sqlite` file and benchmark then fails on `Error: no such table: Order`

**Comment by xhyrom** [comment]
Fixed by https://github.com/oven-sh/bun/pull/989
