### ISSUE TITLE
`bunx vitest` hangs

### ISSUE THREAD

**Issue by cecilia-sanare** [oven-sh/bun#9170]
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Linux 6.1.79 x86_64 unknown

### What steps can reproduce the bug?

In this scenario I'm using `nix-shell`, but this happens in other environments as well.

```nix
# shell.nix
{ pkgs ? import <nixpkgs-unstable> { } }:

pkgs.mkShell {
  buildInputs = with pkgs; [
    # Without node it just silently hangs
    # nodejs_20
    bun
  ];
}
```

**Minimum reproducible example**

```sh
mkdir temp
touch temp/example.spec.ts
(cd temp && bunx vitest)
```

### What is the expected behavior?

Bun should at the very least complain in some way and ideally inform me that installing NodeJS will likely resolve the problem.

### What do you see instead?

Bun just hangs silently.
![image](https://github.com/oven-sh/bun/assets/9692284/30eb1d04-60a0-4b31-85be-7eeb42293911)

### Additional information

I've hit this multiple times and I'm just used to assuming this is what's wrong.
However to developers that are new to bun this is an *incredibly* confusing scenario and most people wouldn't expect installing NodeJS to be the answer given Buns whole thing is to be a drop-in replacement even if its not 100% there yet.

**Comment by Electroid** [comment]
The root cause here is a specific issue with Vitest and Bun, would you be able to share any code so we can reproduce?

**Comment by cecilia-sanare** [comment]
Hi @Electroid! I actually included a simple method of reproducing it with a few commands in the comment above.
But here's a small github repo as well that reproduces the issue.

https://github.com/cecilia-sanare/repro-bun-9170

**Comment by Electroid** [comment]
Duplicate of #4145

**Comment by Electroid** [comment]
We will fix this, didn't see that we had an open issue for this already.

**Comment by paperclover** [comment]
For now, it is recommended to use `bun test` instead of `vitest`, and opening issues for any features we don't support.

**Comment by cecilia-sanare** [comment]
@paperdave 
I mean, the entire reason I'm using `vitest` over `bun test` is due to the lack of support for exporting to `lcov` which already has an open issue (#4015).

Also the reason I opened this issue wasn't for the same reason as #4145. 
Honestly I couldn't care less if `vitest` worked purely in `bun` or not.

My issue is that in a variety of scenarios `bun` will just hang silently rather then giving *any* indication something is wrong.

**Comment by Electroid** [comment]
> My issue is that in a variety of scenarios `bun` will just hang silently rather then giving _any_ indication something is wrong.

Unfortunately, we do not have a catch-all ability to fix all scenarios where Bun hangs. If you do encounter something where Bun hangs, please report it in a seperate issue with some code so we can reproduce it.

**Comment by keithriver** [comment]
Might be interesting from "just use bun test" point of view.
I'm using another tool called wallaby to run vitest and it doesn't yet support bun:test because of limitations they found on bun side:
https://github.com/wallabyjs/public/issues/3220#issuecomment-2735231739

I feel if that integration won't work out one way or another I would need to pretend i'm in node and bun api's don't exist for most of my tested code.
