### ISSUE TITLE
Musl LibC Support

### ISSUE THREAD

**Issue by theoparis** [oven-sh/bun#918]
### What is the problem this feature will solve?

It will allow bun to be used in linux distributions such as Alpine Linux or BunOS. This could also potentially solve #255.

### What is the feature you are proposing to solve the problem?

I have already *attempted* to implement this by creating a [patched dockerfile, build.zig and makefile for building bun under alpine linux](https://github.com/theo-os/bun-musl-build). However, it is missing proper FFI support, which seems to be an issue with the internals of bun (as FFI and static linking seems to work with [deno](https://github.com/theoparis/deno-static)).

**Comment by benatkin** [comment]
Found this closed issue that suggests JavaScript Core may run on musl https://bugs.webkit.org/show_bug.cgi?id=187485

**Comment by brynne8** [comment]
I'm also using Alpine Linux and being unable to run `bun`.

**Comment by dargmuesli** [comment]
Please add a :+1: to the first post instead of adding "me too" comments :pray:

**Comment by notramo** [comment]
WebKit is shipped on some `musl` Linux distros, which implies support for JavaScriptCore.

**Comment by Nyaa97** [comment]
Easy to compile against musl libc.
I need motivation to write a "normal" patch, but its possible.
This requires:
add musl flag to tcc build in Makefile
-fPIC in build.zig
turn off checking GLIBC version in build.zig
turn off force GLIBC in workaround-missing-symbols.cpp
rebuild JSCore

If you are trying to build using only clang, some additional patches are required.

Tested and works well for musl+clang
![image](https://github.com/oven-sh/bun/assets/39170352/bd3ade57-55c5-4a87-b2bb-0ee0a225a9b2)

**Comment by theoparis** [comment]
Why was the above comment marked as "off topic"? It is showing a temporary solution to the issue and it would help contribute torwards a permanent fix in the future.

**Comment by brynne8** [comment]
> Easy to compile against musl libc. I need motivation to write a "normal" patch, but its possible. This requires: add musl flag to tcc build in Makefile -fPIC in build.zig turn off checking GLIBC version in build.zig turn off force GLIBC in workaround-missing-symbols.cpp rebuild JSCore
> 
> If you are trying to build using only clang, some additional patches are required.
> 
> Tested and works well for musl+clang ![image](https://user-images.githubusercontent.com/39170352/279450296-bd3ade57-55c5-4a87-b2bb-0ee0a225a9b2.png)

Great. Could you please upload the binary so that I can temporarily use?

**Comment by theoparis** [comment]
It would be nice if you could send the patches as well.

**Comment by Pyroglyph** [comment]
> I need motivation to write a "normal" patch

@Nyaa97 Would it not have been faster to type `git diff` and paste the result here instead of typing out all the steps?

That aside, do you still have your working code that you could share here?

**Comment by Nyaa97** [comment]
I have updated my patch to musl, but it still needs some tweaking
If anyone is willing to help, I would be grateful
[musl branch](https://github.com/Nyaa97/bun/tree/musl)

**Comment by slogivewd** [comment]
Im waiting the feature to be supported as well

**Comment by nektro** [comment]
This is now in a state we're happy with and will be available as of Bun v1.1.35, which will be out tomorrow Tue Nov 19 🎊

**Comment by nektro** [comment]
let's track that in a new issue
