### ISSUE TITLE
Bun is returning negative numbers for file system errors on Linux

### ISSUE THREAD

**Issue by 9Morello** [oven-sh/bun#9187]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 6.5.0-21-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Run the following JS script using Bun on GNU/Linux:

```js
try {
    await Bun.file("/etc/passwdr").text();
} catch(e) {
    console.log(JSON.stringify(e));
}
```

2. Check the terminal output

### What is the expected behavior?

The `errno` property should be a positive number (`2` in this case).

### What do you see instead?

`-2`. I see the correct error numbers according to [this file](https://github.com/oven-sh/bun/blob/main/src/io/io_linux.zig), but they are negative for some reason.

### Additional information

The following snippet reproduces the bug when attempting to write to the file system, instead of reading from it:

```js
try {
    await Bun.read("/usr/bin/some_protected_folder", "some content");
} catch(e) {
    console.log(JSON.stringify(e));
}
```

The `errno` property is `-13` instead of `13`. Every other property in the error object seems correct.

**Comment by argosphil** [comment]
~I think this means we're running into UB in a bunch of places in `sys.zig`, and also that our checks for E.INTR/E.AGAIN won't work because they're comparing -4 to 4.~

~But I'm not entirely sure.~

Sorry, I misunderstood. I think this is bug-for-bug compatibility with node, actually.

**Comment by 9Morello** [comment]
I see, thanks for the clarification. I'm closing this issue.
