### ISSUE TITLE
`node:http`'s `ClientRequest` never emits `socket`

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#9188]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Code that depends on [`"socket"`](https://nodejs.org/api/http.html#event-socket) being emitted from [`http.ClientRequest`](https://nodejs.org/api/http.html#class-httpclientrequest) simply hang. Here is an example:

```typescript
import * as http from "http";

let request = http.request("http://localhost:8080", {});
await new Promise((resolve, reject) => {
    request.on("error", reject);
    request.on("socket", function onRequestSocket(socket) {
        request.destroy();
        console.log(`Socket: ${socket}`);
        resolve();
    });
});
```

### What is the expected behavior?

The output in Node.JS is:

```
$ npx tsx ./http1test.ts
(node:76013) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Socket: [object Object]
```

### What do you see instead?

The output in Bun is:

```
$ bun run ./http1test.ts

[ ... the arrow of time continues to inevitably move forward, but yet this invocation yields no output ... ]
```

### Additional information

It looks like there is already an implementation of this for the response, just not one for the request.

**Comment by mikeTWC1984** [comment]
Just spotted the same issue with on "connect" event, callback expects socket object, which is null
![Image](https://github.com/user-attachments/assets/b4a719c9-29cd-4b86-8fc9-e6e913abb260)
