### ISSUE TITLE
Shell docs cannot be found when searching docs

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#9205]
### What is the issue?

when searching the docs with `/`, algolia doesn't find these **$ Shell** docs:

<img width="200" alt="image" src="https://github.com/oven-sh/bun/assets/70074722/5cf7ba0d-ad9d-484c-9e25-490ba13f0d7e">

<img width="300" alt="image" src="https://github.com/oven-sh/bun/assets/70074722/099030c3-f778-4aec-b3f0-655ad51312be">

however, other docs can be easily found (e.g. tcp)

<img width="300" alt="image" src="https://github.com/oven-sh/bun/assets/70074722/84141849-eebc-41b3-b0be-241b3e6b1c72">

### Where did you find it?

https://bun.sh/docs/runtime/shell

**Comment by Jarred-Sumner** [comment]
Fixed

<img width="624" alt="image" src="https://github.com/oven-sh/bun/assets/709451/651ad881-48fd-4a5e-92ea-61365137d061">
