### ISSUE TITLE
Hono framework create bug

### ISSUE THREAD

**Issue by DomPeliniAerospike** [oven-sh/bun#9207]
### What version of Bun is running?

1.0.29-canary.51+dcf6f244a

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun create hono my-app

### What is the expected behavior?

a hono framework application is created.

### What do you see instead?

PS C:\Users\dmpel\Documents> bun create hono my-app
error: interpreter executable could not be found

Bun failed to remap this bin to it's proper location within node_modules.
This is an indication of a corrupted node_modules directory.

Please run 'bun install --force' in the project root and try
it again. If this message persists, please open an issue:
https://github.com/oven-sh/bun/issues

### Additional information

I did run bun install --force.  It worked, but it still failed afterwards.

**Comment by paperclover** [comment]
Duplicate of #8795, which has a fix that will be merged soon.
