### ISSUE TITLE
Adding support for new windows in child processes

### ISSUE THREAD

**Issue by KingKDot** [oven-sh/bun#9211]
### What is the problem this feature would solve?

When running a bat file with bun currently things such as

```bat
pause
timeout
```

won't work correctly. Another thing this would solve is getting real time console output from the script being ran (this applies to more than just bat files).

### What is the feature you are proposing to solve the problem?

being able to open file in a separate window that isn't apart of the parent process.

### What alternatives have you considered?

I've tried to use things like start in cmd to start the bat file (that way it's in a new window) but nothing has worked so far. I've also tried changing some of the other settings but have had no luck. I could be completely looking over a solution but I don't believe so. I've also tried using the shell but it doesn't support opening processes in new windows on windows.

**Comment by KingKDot** [comment]
I'm not 100% sure but this actually seems to be an issue with bun and the nodejs child_process api. When trying something like this

```js
const processes = require('child_process');

var file_name = "test.bat"

//execute the file in a new window
processes.exec("start " + file_name, function (err, stdout, stderr) {
    if (err) {
        console.log(err);
    }
    console.log(stdout);
});
```

Output in node is expected but output in bun is the following

```
475 |   return fileURLOrPath != null && fileURLOrPath.href && fileURLOrPath.origin;
476 | }, toPathIfFileURL = function(fileURLOrPath) {
477 |   if (!isURLInstance(fileURLOrPath))
478 |     return fileURLOrPath;
479 |   return Bun.fileURLToPath(fileURLOrPath);
480 | }, genericNodeError = function(message, options) {
                                                                  ^
error: Command failed: start test.bat
 code: "1"

      at node:child_process:480:61
      at exitHandler (node:child_process:61:45)
      at emit (node:events:155:95)
      at #maybeClose (node:child_process:715:27)
      at #handleOnExit (node:child_process:540:31)
```

**Comment by KingKDot** [comment]
@Jarred-Sumner would you be able to change the label from enhancement to bug?

**Comment by paperclover** [comment]
The error 'command failed' might be #8588, but regardless i want to keep this issue open, specifically to be visited after #8456 is merged.

**Comment by KingKDot** [comment]
> The error 'command failed' might be #8588, but regardless i want to keep this issue open, specifically to be visited after #8456 is merged.

Good luck on #8456 lol looks intimidating

**Comment by paperclover** [comment]
is fixed on that branch now

**Comment by KingKDot** [comment]
@paperdave so far windows start command works but starting a process inside of the current process with call isn't working.

**Comment by KingKDot** [comment]
process hangs it seems

**Comment by KingKDot** [comment]
Nevermind ignore this, node does the same exact thing.
