### ISSUE TITLE
bun install from symlinked folder

### ISSUE THREAD

**Issue by guybarnard** [oven-sh/bun#922]
### Version

0.1.5

### Platform

21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

``` bash
cd ~/projects # a symlinked folder that is actually on another logical drive 
bun create hono ./bun-hono
cd bun-hono
bun install
```

```
Failed to install 2 packages
[9.00ms] done
error: Unexpected installing hono
error: Unexpected installing bun-types
```

### How often does it reproduce? Is there a required condition?

If the packages being installed have not been installed before the error happens every time. 

If the packages have been installed previously (say via the workaround), no error occurs

### What is the expected behavior?

```
bun install v0.1.5
  🔍 Resolving [1/2] 
[49.00ms] git
 + bun-types@0.1.5
 + hono@2.0.5
```

### What do you see instead?

```
Failed to install 2 packages
[9.00ms] done
error: Unexpected installing hono
error: Unexpected installing bun-types
```

## Workaround 1

``` bash
bun install --backend=copyfile
```

## Workaround 2 

Run directly from a folder on the os volume, not a symlinked folder

``` bash
cd ~
mkdir bun-projects
cd bun-projects
bun create hono bun-hono
cd bun-hono
bun install
```

**Comment by Electroid** [comment]
Yes, we need to fix this. Tracking the issue here: #362
