### ISSUE TITLE
Segmentation fault when using Bun websocket server with non-existent cert/key file & system reserved port

### ISSUE THREAD

**Issue by Zekiah-A** [oven-sh/bun#9224]
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 6.7.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Segmentation fault when running a bun websocket server with with the cert and key pointing to a file that doesn't exist, whilst using a system reserved port without privileges

_example.ts_
```ts
const server = Bun.serve({
    fetch(req, server) {
        if (server.upgrade(req)) {
            return;
        }
        return new Response("Not a WebSocket request", { status: 400 });
    },

    websocket: {
        message(ws, message) {
        },
    },
    tls: {
        cert: Bun.file("/etc/letsencrypt/this-file-does-not-exist.crt"),
        key: Bun.file("/etc/letsencrypt/this-file-does-not-exist.key")
    },
    port: 443 // The segfault seems to occur if this is set to any system reserved port
})
console.log("Things are working")
```
`$ bun run example.ts # run without sudo`

### What is the expected behavior?

Server should throw an exception, like
1 | const server = Bun.serve({
                   ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/etc/letsencrypt/this-file-does-not-exist.key"

      at /home/zekiah/example.ts:1:16

### What do you see instead?

❯ bun run example.ts
zsh: segmentation fault (core dumped)  bun run example.ts

### Additional information

I have only experienced this issue when the `port` field is set to a system reserved port, such as any of the ports under 1023, and the  command is being run without `root/sudo` privileges from my testing. However it could be possible there are other cases where this issue occurs.

**Comment by Jarred-Sumner** [comment]
@paperdave your PR removing ExceptionRef very likely fixes this
