### ISSUE TITLE
Non-deterministic behaviour using ArrayBuffer/Uint8Array/TextEncoder (possible issue with JavaScriptCore)

### ISSUE THREAD

**Issue by mmvsk** [oven-sh/bun#9226]
### What version of Bun is running?

1.0.29

### What platform is your computer?

Linux 6.7.7-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

I published a reproduction here: https://github.com/mmvsk/bun-buffer-error

Basically, there are three typescript files: two files containing two different algorithms to encode/decode base32, and one to verify the output.

In a specific state of the code, there is one produced byte (the first byte of an ArrayBuffer/Uint8Array) that has an invalid value, moreover:

- changing the code in a totally irrelevant way like adding a `Buffer.from(constantString)` (without using the output anywhere, without any time-related operation) makes the bug disappear (see `src/main.ts` line 5 and `src/base32a.ts` line 101) in the reproduction
- it works as expected in Node/V8

I also tried, with the same results:

- in an bare bun project (`bun init -y`)
- on another computer

### What is the expected behavior?

It should as expected, ie. the same way as under Node/V8, or when modifying irrelevant portions of the code. In my reproduction, the with the output of `bun start` should be:

```bash
$ bun run src/main.ts
no error at 641 :)
```

That is to say the same output as with `MOD=1 bun start` and `MOD=2 bun start`.

### What do you see instead?

In my reproduction:

```text
$ bun run src/main.ts
A <> B decoding (B) mismatch for base32 of 641 bytes

  EncodeA(I): 7F3XZRV3WJ5X2UM5YEN2CKJDFHOCRC... EncodeB(I): 7F3XZRV3WJ5X2UM5YEN2CKJDFHOCRC...
  EncodeA(A): AF3XZRV3WJ5X2UM5YEN2CKJDFHOCRC... EncodeB(A): AF3XZRV3WJ5X2UM5YEN2CKJDFHOCRC...
  EncodeA(B): 7F3XZRV3WJ5X2UM5YEN2CKJDFHOCRC... EncodeB(B): 7F3XZRV3WJ5X2UM5YEN2CKJDFHOCRC...

  Hex(I): F9 77 7C C6 BB B2 7B 7D 51 9D C1 1B A1 29 23 29 DC 28 8A B8 02 02 CA 57 CA 99 B9 0B F1 23
  Hex(A): 01 77 7C C6 BB B2 7B 7D 51 9D C1 1B A1 29 23 29 DC 28 8A B8 02 02 CA 57 CA 99 B9 0B F1 23
  Hex(B): F9 77 7C C6 BB B2 7B 7D 51 9D C1 1B A1 29 23 29 DC 28 8A B8 02 02 CA 57 CA 99 B9 0B F1 23

  byte #0 mistmatch: (A: 01) <> (B: F9)
```

It's the output of a console error printed in `main.ts`, where:

- `I` is the original input `Uint8Array` (generated using `crypto.getRandomValues()`)
- `B` comes from algorithm B, here it's fine
- `A` comes from algorithm A, where the first byte is not valid and always starts with a zero, in the 641st loop generating a 641-byte array

It works on Node, and adding a simple `Buffer.from(constantString)` somewhere without any effect on the rest of the code makes this error disappear (ie. that first byte in the 641st iteration of the loop is defined as it should be).

**Comment by Jarred-Sumner** [comment]
My hunch is either

It's a bug in the code for handling rope strings in `TextEncoder.prototype.encode`. `Buffer.from(constantString)` would potentially make `constantString` no longer a rope string which would cause this to happen

https://github.com/oven-sh/bun/blob/cfe10991a4793be3fda2fb6f34ba615fe1240777/src/bun.js/bindings/webcore/JSTextEncoder.cpp#L260-L266

Or it's a DOMJIT issue. We use DOMJIT for `TextEncoder.prototype.encode`: 

https://github.com/oven-sh/bun/blob/cfe10991a4793be3fda2fb6f34ba615fe1240777/src/bun.js/bindings/webcore/JSTextEncoder.cpp#L223-L228

We also use DOMJIT in `TextDecoder.prototype.decode`:

https://github.com/oven-sh/bun/blob/cfe10991a4793be3fda2fb6f34ba615fe1240777/src/bun.js/webcore/encoding.classes.ts#L26-L30

**Comment by Jarred-Sumner** [comment]
Update: the side effects specified in TextEncoder.prototype.encode are wrong. Buffer.from(constantString) fixes it because it impacts the heap object count, which is the only side effect we list. I'm not sure what the correct side effects are so I'm going to conservatively make it not optimize based on side effects
