### ISSUE TITLE
'fetch() failed OpenSSLError' when sending HTTP HEAD requests

### ISSUE THREAD

**Issue by jimmed** [oven-sh/bun#923]
### Version

0.1.5

### Platform

```
Linux [HOSTNAME REDACTED] 5.18.10-76051810-generic #202207071639~1657252310~22.04~7d5e891 SMP PREEMPT_DYNAMIC Fri J x86_64 x86_64 x86_64 GNU/Linux
```

### What steps will reproduce the bug?

Making an HTTP request using the `HEAD` method to any valid URL results in an error message.

```ts
// bug.ts
const res = await fetch(
  "https://google.com/",
  { method: "head" }
);

console.log(res);
```

Executing this code using `bun bug.ts` reproduces the error.

### How often does it reproduce? Is there a required condition?

Every time, if `HEAD` is used as the method when `fetch` is called. Every other HTTP method seems to behave as expected (even the exotic ones like `LINK`)

### What is the expected behavior?

I would expect the above script to yield an output like this:

```
Response (2 KB) {
  ok: true,
  bodyUsed: false,
  status: 200,
  url: "https://google.com",
  statusText: "OK",
  redirected: false
}
```

rather than throwing an error.

### What do you see instead?

Executing the above code with `bun bug.ts` yields the following error message:

```
Error: fetch() failed OpenSSLError
url: "https://google.com"
```

### Additional information

This seems to be the case regardless of the (https) URL I use.

**Comment by Electroid** [comment]
This has been fixed as of `0.2.2`.

```js
const res = await fetch(
  "https://google.com/",
  { method: "head" }
);

console.log(res);
// Response (0 KB) {
//   ok: true,
//   url: "https://www.google.com/",
//   statusText: "OK",
//   redirected: true,
//   bodyUsed: false,
//   status: 200,
//   Blob (0 KB)
// }
```
