### ISSUE TITLE
`Script not found` error message when running Prisma commands

### ISSUE THREAD

**Issue by marvinruder** [oven-sh/bun#9237]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Linux 6.6.16-linuxkit aarch64 unknown

### What steps can reproduce the bug?

```
mkdir hello-prisma
cd hello-prisma
bun init -y
bun install prisma
bun prisma init
```

### What is the expected behavior?

No error message.

### What do you see instead?

```
error: Script not found "/home/bun/app/hello-prisma/node_modules/prisma/build/child"
```

### Additional information

I cannot pinpoint this issue to an exact location in Prisma’s source code, but there is a line in the minified bundle that reads

```js
childPath=path__default.default.join(eval("__dirname"),"child");
```

Changing `child` to `child.js` there removes the error message, but then strangely another newline character is printed after the command exits:

https://github.com/oven-sh/bun/assets/18495294/99567a1f-feb8-4444-8bd2-38c9a5703264

(There are two shell prompts without me pressing any buttons after running the command. The second one appears a moment after the first one)

This is reported in https://github.com/prisma/prisma/issues/23339 as well – not sure if this is an issue with Prisma or with Bun’s module resolution.

I briefly mentioned this issue in #5320 but since the main issues there were resolved, I decided to open another issue specifically for this.

**Comment by Jarred-Sumner** [comment]
The final boss

**Comment by camero2734** [comment]
Not that it solves the underlying issue, but you can skip the part that logs this error with `CHECKPOINT_DISABLE`
```bash
CHECKPOINT_DISABLE=1 bunx prisma init
```

which seems to just be for telemetry collection anyway (see https://www.npmjs.com/package/checkpoint-client, closed source apparently)
