### ISSUE TITLE
bun test freezes

### ISSUE THREAD

**Issue by jeffshaver** [oven-sh/bun#9275]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Linux 6.7.7-100.fc38.x86_64 x86_64 unknown

### What steps can reproduce the bug?

run `bun test` or `bun test <path_to_file>`

### What is the expected behavior?

the tests should run

### What do you see instead?

it shows the name of the first spec file that is going to be run and then just stays there forever
![2024-03-06_09:47:31](https://github.com/oven-sh/bun/assets/5390616/71ba6a2b-8a67-41e9-a72c-660934182885)

### Additional information

on bun 1.0.22 everythign works as expected. if i upgrade past 1.0.22 it starts doing this

**Comment by Electroid** [comment]
Would you be able to share a minimal repro of the test? Otherwise it will be difficult for us to fix your issue.

**Comment by jeffshaver** [comment]
in trying to reproduce this, it seems as though its just a @happy-dom issue. upgrading to 13.2.0+ seems to address things

https://github.com/capricorn86/happy-dom/releases/tag/v13.2.0
