### ISSUE TITLE
vscode debug does not respect breakpoints when using async function

### ISSUE THREAD

**Issue by dotneet** [oven-sh/bun#9290]
### What version of Bun is running?

1.0.30

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I've set some breakpoints in the following code but vscode debugger through the all breakpoints.

```
console.log("1");
console.log("2");  // breakpoint

async function a() {
  console.log("3");  // breakpoint
}

await a();  // breakpoint
```

But with the following code, vscode debugger stop as I expected.

```
console.log("1");
console.log("2");  // breakpoint

function a() {
  console.log("3");  // breakpoint
}

a(); // breakpoint
```

Here is my launch.json configuration.

```
  {
      "type": "bun",
      "internalConsoleOptions": "neverOpen",
      "request": "launch",
      "name": "Bun: Debug File",
      "program": "${file}",
      "cwd": "${workspaceFolder}",
      "runtimeArgs": [],
      "stopOnEntry": false,
      "runtime": "bun",
      "noDebug": false,
      "watchMode": false
    }
```

### What is the expected behavior?

Even if using top-level async, debugger should respect breakpoints.

**Comment by dotneet** [comment]
I found additional strange behavior.

does not work:

```
console.log("1");
console.log("2"); // breakpoint

async function b() {
  console.log("4"); // breakpoint
}

function a() {
  console.log("3"); // breakpoint
  b();
}

a(); // breakpoint
```

works correctly:

```
console.log("1");
console.log("2"); // breakpoint

function a() {
  console.log("3"); // breakpoint
  b();
}

async function b() {
  console.log("4"); // breakpoint
}

a(); // breakpoint
```

**Comment by Electroid** [comment]
If you add the `// @bun` directive to the top of your file, do all the breakpoints work?

```js
// @bun

console.log("1");
console.log("2"); // breakpoint

async function b() {
  console.log("4"); // breakpoint
}

function a() {
  console.log("3"); // breakpoint
  b();
}

a(); // breakpoint
```

**Comment by dotneet** [comment]
@Electroid 
with `@bun`, works perfectly! Thank you!

any official document abount `@bun` ?
I looked into this but could not figure out how this works.

**Comment by Electroid** [comment]
> @Electroid with `@bun`, works perfectly! Thank you!
> 
> any official document abount `@bun` ? I looked into this but could not figure out how this works.

So the reason I asked is because `// @bun` tells Bun to not run the built-in transpiler. That means the issue here is that our source maps are broken, which we do need to fix.

**Comment by Electroid** [comment]
Duplicate of #7427
