### ISSUE TITLE
Bun interactive shell `bunx bunx`

### ISSUE THREAD

**Issue by pi0** [oven-sh/bun#9294]
TIL, you can use `npx npx` for an interactive shell within _npm script environment_:

<img width="493" alt="image" src="https://github.com/oven-sh/bun/assets/5158436/d325422a-81b2-4eb3-8e1c-28302528d7ae">

Since bun already has a decent shell implementation, would it make sense to open it up as a universal interactive shell?

**Comment by Jarred-Sumner** [comment]
We're probably not going to do this but there are multiple community libraries that have
