### ISSUE TITLE
Wildcard sideEffects warning using bun run

### ISSUE THREAD

**Issue by vikingair** [oven-sh/bun#9295]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

Run any script using `bun run` while in the current working directory is a `package.json` that contains wildcard side effects, such as

```json
"sideEffects": [
  "*.scss"
],
```

### What is the expected behavior?

The current work directory was not even relevant for the script that was executed with `bun run`.

Also, I would expect this check to only be printed using `bun build` because otherwise side effect imports should be completely irrelevant to `bun`, shouldn't it?

### What do you see instead?

A warning such as

```
9 |     "*.scss"
        ^
warn: wildcard sideEffects are not supported yet, which means this package will be deoptimized
```

**Comment by vikingair** [comment]
This issue is btw in my opinion just something else, even though related: https://github.com/oven-sh/bun/issues/5241

**Comment by Electroid** [comment]
The root cause of both issues is the same (e.g. it's the same effort of work for us to fix it) We will fix this now that Bun has glob support.

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/5241
