### ISSUE TITLE
bun init not accepting Ctrl-C or Enter on MacOS 13.6.3 for bun -v 1.0.30

### ISSUE THREAD

**Issue by funnisimo** [oven-sh/bun#9297]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

% bun init
bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit

package name (myapp): ^M^M^M^M^M^M^M^C^C^C^C^Czsh: terminated  bun init

### What is the expected behavior?

Enter and Ctrl-C work.

### What do you see instead?

^M for Enter
^C for Ctrl-C

### Additional information

process was terminated with: kill <pid>

**Comment by Electroid** [comment]
Unable to reproduce this on macOS arm with `1.0.30+5a8830fdc`

**Comment by paperclover** [comment]
what terminal emulator are you using? the ones i try do not reproduce this.

**Comment by funnisimo** [comment]
Go ahead and close it - looks like something that was because of my environment.  Sorry about that.
