### ISSUE TITLE
hot reload (docker) changes inside the container

### ISSUE THREAD

**Issue by KH93b** [oven-sh/bun#9300]
### What version of Bun is running?

1.0.30

### What platform is your computer?

ubuntu (docker)

### What steps can reproduce the bug?

create image:
FROM ubuntu
RUN apt-get update && \
    apt-get install -y curl unzip vim && \
    curl https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"
RUN bun create elysia app
WORKDIR /app
RUN bun install
EXPOSE 3000
CMD ["bun", "dev"]

build image 
	docker build -t test-elysia .

copy 
docker cp id_container:/app/ ${PWD}   

docker run -p 3000:3000 -it -v ${PWD}/app:/app test-elysia

If you make changes inside the container, then hot reload works. If you make changes from outside, it does not work, although the files inside the container are changed.

### What is the expected behavior?

hot reload

### Additional information

I tried different launch options:
"dev": "bun --watch run src/index.ts"
"dev": "bun --watch src/index.ts"
"dev": "bun --hot src/index.ts"
"dev": "bun --hot run src/index.ts"

The file inside the container changes, bun should see it, but it doesn't react. I had the same problem with nodejs (espressjs). There I used nodemon. If you use nodemon without the -L flag, hot reload does not work, but with the -L flag it works.

**Comment by Electroid** [comment]
Duplicate of #5841
