### ISSUE TITLE
Improve error codes on sigsegv fault

### ISSUE THREAD

**Issue by isakgustavsen** [oven-sh/bun#9301]
### What is the problem this feature would solve?

The current fault does not expose why a build, fails but simply that it does. When switching to pnpm it outputs usable codes. 

### What is the feature you are proposing to solve the problem?

improve this code:
Error: Command "bun install" exited with SIGSEGV

to something like this:
ERROR: Big integer literals are not available in the configured target environment ("es2019")

This is the same codebase ran on Bun and PNPM

**Comment by Electroid** [comment]
Could you provide your package.json / any commands you ran so we can try to reproduce this?

**Comment by isakgustavsen** [comment]
[package.json](https://github.com/oven-sh/bun/files/14529515/package.json)
[PNPM output](https://github.com/oven-sh/bun/files/14529553/build.error.sigsegv.txt)
[Bun output](https://github.com/oven-sh/bun/files/14530070/vercel.bun.buildlog.txt)


it was run on vercel so they might also have something to do with it. The full error points to it happening because of the 'vue-email/nuxt' package, but i have attached the log in case there is info im not seeing

**Comment by isakgustavsen** [comment]
Working on a reproduction now

**Comment by paperclover** [comment]
related but i dont think i have an issue: i want to rebuild the crash handler to be more useful, so that we could resolve the crash and hopefully reduce the need for reproductions.

**Comment by Jarred-Sumner** [comment]
We very likely fixed this. Please let us know if you're still running into it sometime in the next week and we'll re-open the issue.
