### ISSUE TITLE
import sqlite from "better-sqlite3";  new sqlite("sqlite.db"); // process killed

### ISSUE THREAD

**Issue by sroussey** [oven-sh/bun#9308]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

bun i better-sqlite3

in index.ts: import sqlite from "better-sqlite3";  new sqlite("sqlite.db");

bun run index.ts

### What is the expected behavior?

No crash

### What do you see instead?

❯ bun run index.ts
dyld[54040]: missing symbol called
[1]    54040 killed     bun run index.ts

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/4290
