### ISSUE TITLE
Execution break when NODE_ENV is set

### ISSUE THREAD

**Issue by emiliaGonzalez** [oven-sh/bun#931]
### Version

0.1.5

### Platform

Darwin MacBook-Air-de-Emilia.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

Create a index.js with the following code:

`process.env.NODE_ENV = 'development';

const a = 2;
`
It will thrown 

`SyntaxError: Left side of assignment is not a reference.`

When some file set some value to NODE_ENV execution breaks with that error, no matter te value.

### How often does it reproduce? Is there a required condition?

It always happens

### What is the expected behavior?

Dont break

### What do you see instead?

`SyntaxError: Left side of assignment is not a reference.`

**Comment by paperclover** [comment]
note: duplicate of #556

**Comment by xhyrom** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/556

**Comment by xhyrom** [comment]
Closed as not planned because this is duplicate (no because this is not planned), follow original issue for more informations.
