### ISSUE TITLE
bun build linked sourcemap option

### ISSUE THREAD

**Issue by sk337** [oven-sh/bun#9314]
### What is the problem this feature would solve?

source map external does not link to the source map preventing browser from automatically loading them

### What is the feature you are proposing to solve the problem?

add an option to the source map flag named linked the will add a source mapping comment like this
`//# sourceMappingURL=index.js.map`

### What alternatives have you considered?

I made consider internal but I don't serve source maps to users that don't have a enough permission and I cant limit the internal sourcemap

**Comment by damonsmith** [comment]
My workaround for now is to just append the sourcemapping line myself after calling bun.build() in my build script - 

```
	await Bun.build({
		entrypoints: ['src/index.ts'],
		outdir: 'dist',
		sourcemap: 'external'
	});
	await appendFile("dist/src/index.js", '\n//# sourceMappingURL=index.js.map');

 ```
