### ISSUE TITLE
Bun shell not able to run package script with keyword run?

### ISSUE THREAD

**Issue by thejasonxie** [oven-sh/bun#9324]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Create a shell script to run a package.json script named build or any other...

```js
// in package.json scripts: "build": "echo hello"

const command = "run build"

await $`cd packages/${pkg} && bun ${command}`;
// results in: error: Script not found "run build"
//-------------
if (command === 'run build') {
  await $`cd packages/${pkg} && bun run build`;
} else {
  await $`cd packages/${pkg} && bun ${command}`;
}
// results in: $ echo hello...


```

### What is the expected behavior?

When `bun run build` string is created in await $``,  run the script build defined in package.json, 

### What do you see instead?

error: Script not found "run build"

### Additional information
bun thinks the keyword "run" is part of a script.

You can check out this library I built for more details on what I am trying to do: 
https://github.com/thejasonxie/bun-pkg

**Comment by akirarika** [comment]
Bun Shell escapes all strings by default, preventing shell injection attacks.

Therefore, your command will be treated as a whole, similar to the `bun "run build"` in bash. To disable this feature, you can pass the raw parameter.

```ts
const command = "run build"
$`bun ${{raw: command}}`
```

**Comment by thejasonxie** [comment]
I can confirm passing raw parameter works!  Thank you @akirarika!
ref:
- https://bun.sh/docs/runtime/shell#features
- https://bun.sh/docs/runtime/shell#escape-escape-strings
