### ISSUE TITLE
Deployment platform 

### ISSUE THREAD

**Issue by h44mkk** [oven-sh/bun#934]
Hey, is there any platform which support Bun runtime for deployment?

**Comment by theotterlord** [comment]
You can deploy it to any platform supporting docker containers. The official containers aren't building rn (see #855) but I've created a repository that builds images with github actions [here](https://github.com/TheOtterlord/docker-bun).

Apart from that, there's no simple way to do it yet. Remember, bun is still very new and has a lot of bugs. In addition, could have breaking changes down the line, so I don't see anyone wanting to implement first-class support for bun yet. So for now, I'd stick with a docker container, or deploying manually. 

There are also some community templates on [repl.it](https://replit.com/@bddy/Bun-Template?v=1) for bun.
