### ISSUE TITLE
Bun event loop doesn't exit when using Postgres.js

### ISSUE THREAD

**Issue by gvilums** [oven-sh/bun#9348]
### What version of Bun is running?

1.0.30+5a8830fdc

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run the following:
```ts
import postgres from "postgres"

const sql = postgres({
    user: "postgres",
    password: "postgres",
    database: "postgres",
})

await sql`select null`;
console.log('done');
```

### What is the expected behavior?

Print `done` and exit.

### What do you see instead?

`done` is printed but bun doesn't exit.

**Comment by Electroid** [comment]
Could be related #9349

**Comment by ajohn25** [comment]
Also ran into this when attempting to upgrade to the latest Bun version. Through some trial and error, I discovered that postgres behaves as expected up through Bun v1.0.25, so it appears to me that the bug was introduced in v1.0.26.  Additionally, based on my code sample, what's hanging is `sql.end()` which is similar to what was reported for `mysql2` here https://github.com/oven-sh/bun/issues/9349#issuecomment-2066522657


Here's my code:

```javascript
import postgres from "postgres"

const sql = postgres(`myConnString`)
const result = await sql`select 1`

console.log('this will print', result)
await sql.end()
console.log('this will not print', result)

**Comment by gvilums** [comment]
> Also ran into this when attempting to upgrade to the latest Bun version. Through some trial and error, I discovered that postgres behaves as expected up through Bun v1.0.25, so it appears to me that the bug was introduced in v1.0.26. Additionally, based on my code sample, what's hanging is `sql.end()` which is similar to what was reported for `mysql2` here [#9349 (comment)](https://github.com/oven-sh/bun/issues/9349#issuecomment-2066522657)
> 
> Here's my code:
> 
> ```js
> import postgres from "postgres"
> 
> const sql = postgres(`myConnString`)
> const result = await sql`select 1`
> 
> console.log('this will print', result)
> await sql.end()
> console.log('this will not print', result)
> ```

Thanks for the detailed report!

**Comment by mattbdc** [comment]
Possibly related #10273? Never ending scenario, mention it just incase. Checking in regularly to see postgres related bugs that's all

**Comment by mattbdc** [comment]
Same situation in 1.1.7 released today, [ajohn25](https://github.com/ajohn25) examples doesnt print the last line, it hangs on the await

**Comment by mattbdc** [comment]
Still broke in 1.1.8

```
➜  bun-postgres-test node index.js
this will print Result(1) [ { '?column?': 1 } ]
this will not print Result(1) [ { '?column?': 1 } ]
➜  bun-postgres-test bun index.js 
this will print [
  {
    "?column?": 1,
  }
]
^C
➜  bun-postgres-test bun -v
1.1.8
➜  bun-postgres-test node -v
v21.1.0
➜  bun-postgres-test more index.js 
import postgres from "postgres"

const sql = postgres({
    user: "postgres",
    password: "postgres",
    database: "postgres",
    host: "127.0.0.1"
})

const result = await sql`select 1`

console.log('this will print', result)
await sql.end()
console.log('this will not print', result)
➜  bun-postgres-test 
```
