### ISSUE TITLE
install script should automatically add the install directory to `PATH`

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#935]
### What is the problem this feature will solve?

when i install bun i have to manually figure out which `.bashrc` file to add these lines to:

![image](https://user-images.githubusercontent.com/57028336/182020931-1d27d45d-cd12-45da-98af-be39e308eb56.png)

### What is the feature you are proposing to solve the problem?

the script should do it for me

**Comment by pepper-lees** [comment]
I suppose a dirty solution would be to:

1. First test to see if the install dir happens to already be on `PATH`
2. If not, then check for common `rc` files in the home dir (`.bashrc`, `.cshrc`, etc.), and add it to whichever of those files already exist.

But it should ask the user before automatically adding it, IMO.
