### ISSUE TITLE
`bun-types` url is dead

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#937]
### Affected URL(s)

https://github.com/oven-sh/bun#types-for-bunjs-editor-autocomplete
https://github.com/oven-sh/bun-types/blob/master/dist/types.d.ts

### Description of the problem

the file linked [here](https://github.com/oven-sh/bun#types-for-bunjs-editor-autocomplete) is a 404: https://github.com/oven-sh/bun-types/blob/master/dist/types.d.ts

**Comment by xhyrom** [comment]
Could you do PR and change URL to https://github.com/oven-sh/bun-types ?
