### ISSUE TITLE
Deployment to AWS Lambda with Bun Failed with using AWS CDK

### ISSUE THREAD

**Issue by hhimanshu** [oven-sh/bun#9372]
### What version of Bun is running?

1.0.30

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Hello folks,
I love what you are doing with bun, and working to get my APIs working with it using AWS CDK. It fails currently and here are the steps

- Clone the [repo](https://github.com/hhimanshu/bun-cdk)
- Install dependencies using `bun install`
- Deploy to AWS using `bunx cdk deploy`

This deployment succeeds and gives you a URL as output
```
 https://djrass482a.execute-api.us-east-1.amazonaws.com/prod/. # This is working for now
```

But as you hit the API, you will see `{"message": "Internal server error"}`
<img width="945" alt="image" src="https://github.com/oven-sh/bun/assets/6589036/3dc97166-b25e-4e91-b827-7872922ba892">

In logs on AWS CloudWatch, this is what I see

```

2024-03-12T17:16:47.331+13:00INIT_START Runtime Version: nodejs:20.v18	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:b8c2913782bf648152634d2f893a4c02250aec5884edb545f64c2bd7268d214eCopy | INIT_START Runtime Version: nodejs:20.v18 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:b8c2913782bf648152634d2f893a4c02250aec5884edb545f64c2bd7268d214e
-- | --
  | 2024-03-12T17:16:47.409+13:002024-03-12T04:16:47.409Z	undefined	ERROR	Uncaught Exception 	{     "errorType": "Runtime.HandlerNotFound",     "errorMessage": "index.handler is undefined or not exported",     "stack": [         "Runtime.HandlerNotFound: index.handler is undefined or not exported",         "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",         "    at async start (file:///var/runtime/index.mjs:1282:23)",         "    at async file:///var/runtime/index.mjs:1288:1"     ] }Copy | 2024-03-12T04:16:47.409Z undefined ERROR Uncaught Exception {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported"," at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)"," at async start (file:///var/runtime/index.mjs:1282:23)"," at async file:///var/runtime/index.mjs:1288:1"]}
  | 2024-03-12T17:16:47.430+13:00INIT_REPORT Init Duration: 99.04 ms	Phase: init	Status: error	Error Type: Runtime.ExitError

```

<img width="1204" alt="image" src="https://github.com/oven-sh/bun/assets/6589036/21030691-027e-45a0-ac1c-5a7f64565e1f">

As I look into the [official steps](https://github.com/oven-sh/bun/tree/main/packages/bun-lambda#step-2-build-the-bun-handler), I realized that I had not done this. I need help in finding out how to achieve this. My upto date code is at [GitHub](https://github.com/hhimanshu/bun-cdk)

Your help is greatly appreciated!

### What is the expected behavior?

The API should have worked

### What do you see instead?

Internal Server Error

### Additional information

https://github.com/hhimanshu/bun-cdk

**Comment by Electroid** [comment]
According to the logs it looks like you're running the code using the Node runtime?

**Comment by hhimanshu** [comment]
I think, you're right. I changed the runtime later to use `Runtime.PROVIDED_AL2`, but it did not help. I guess I am missing the place to bundle the files for the runtime, isn't it? If yes, I would love to take help and learn where I need to do this.

**Comment by hhimanshu** [comment]
When I change the Runtime, my code looks like
```
const nodejsFunction = new NodejsFunction(this, "BunCdkFunction", {
      entry: "lambda/index.ts",
      handler: "handler",
      runtime: Runtime.PROVIDED_AL2,
      layers: [layer],
    });
```

Then `cdk deploy` fails with
```
Error: Only `NODEJS` runtimes are supported.
```

This is because my code uses `NodejsFunction`. I think, it needs to change to be

```
const fn = new Function(this, "BunFunction", {
      runtime: Runtime.PROVIDED_AL2,
      handler: "index.handler",
      code: Code.fromAsset(path.join(__dirname, "lambda")),
      layers: [layer],
    });
```
The line where I am confused is 
```
code: Code.fromAsset(path.join(__dirname, "lambda")),
```

Should this be direct path to `.ts` fil? As per [Step 2 in documentation](https://github.com/oven-sh/bun/tree/main/packages/bun-lambda#step-2-build-the-bun-handler), it seems not. So, I am wondering what I need to do to make it work.

I hope this gives some clarity on where I need help. Thanks

**Comment by hhimanshu** [comment]
I sat down again to resume this activity. I fixed now and [here](https://github.com/hhimanshu/bun-cdk/pull/1/files) are my changes.
These are now in `main` branch for anyone to be able to use it
