### ISSUE TITLE
I hope compiling to native binary was added for Bun.

### ISSUE THREAD

**Issue by Foxchandaisuki** [oven-sh/bun#9375]
### What is the problem this feature would solve?

This will make JavaScript, TypeScript programs run faster, with really compiled native binaries. It can be a killer reature to the Bun's alternatives like Node.js and Deno.

### What is the feature you are proposing to solve the problem?

Compiling to native binary via LLVM could be a way to achieve programs fully compiled before distribution.

**Comment by endrihoxhaa** [comment]
Already Done  your can run bun build script.ts --compile 
for more check out the docs
https://bun.sh/docs/bundler#executables

**Comment by Foxchandaisuki** [comment]
> Already Done your can run bun build script.ts --compile for more check out the docs https://bun.sh/docs/bundler#executables

That one is just making a standalone. What I meant was AOT compilation of JavaScript to Machine code at build time.

**Comment by sequencerr** [comment]
> > Already Done your can run bun build script.ts --compile for more check out the docs https://bun.sh/docs/bundler#executables
> 
> That one is just making a standalone. What I meant was AOT compilation of JavaScript to Machine code at build time.

What do you mean? Is it possible? If yes how? Isn't JavaScript interpreted language?

**Comment by sequencerr** [comment]
I guess this would be JavaScript to Zig transpiler

**Comment by Electroid** [comment]
Bun supports compiling your application into a binary, but it does not do AOT to machine code. Bun is able to leverage the JIT in JavaScriptCore, which is still fast.
