### ISSUE TITLE
Move Docs from repo to the website "bun.sh" 

### ISSUE THREAD

**Issue by andronasef** [oven-sh/bun#938]
### What is the problem this feature will solve?

REPO should look clean more than that
so moving docs to the website will make it more useful

### What is the feature you are proposing to solve the problem?

Using one of docs generators like VitePress

### What alternatives have you considered?

Keeping docs in Repo as it is

**Comment by andronasef** [comment]
I can help with this too!

**Comment by Electroid** [comment]
We're working on it!
