### ISSUE TITLE
`TODO SHELL SUBPROC onReadChunk error`

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#9380]
```
❌ test/js/bun/shell/bunshell.test.ts - SIGABRT [0.40s]
  
  0   0x55d30df9092b
  1   ???
  2   ???
  3   ???
  4   ???
  5   ???
  6   ???
  7   ???
  8   ???
  9   ???
  10  ???
  11  ???
  12  ???
  13  ???
  14  ???
  15  ???
  16  ???
  
  Crash report saved to:
    ./.bun-crash/v1.0.30-1710274948284.crash
  
  Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
  
  thread 7171 panic: TODO SHELL SUBPROC onReadChunk error
  Unwind information for `:0x55d30cbcf55a` was not available, trace may be incomplete
  ```

Tested on Linux arm64.

**Comment by tiptenbrink** [comment]
For me this occurred when running $ during a response in Bun.serve. However, first I had to make an API request. So my code was something like:

```ts
Bun.serve({
    port: 5175,
    async fetch(req) {
                callApi().then(async (run) => {
                    await $`<long running command here (5+ seconds)>`
                });
            }
        }

        return new Response();
    },
});
```

The crash didn't occur when the command completed faster, just a few seconds (I was pulling a Docker image in the long case). 

Furthermore, if I changed it to:

```ts
Bun.serve({
    port: 5175,
    async fetch(req) {
                const apiResult = await callApi();
                await $`<long running command here (5+ seconds)>`
            }
        }

        return new Response();
    },
});
```

the problem also disappeared.

**Comment by tiptenbrink** [comment]
^ nevermind, the problem keeps occurring if the command runs for a while even after my change, but only sometimes. In this case my code didn't even run in the main response function, but only after a separate event was triggered.

**Comment by guyutongxue** [comment]
As a workaround, I'm downgrading bun to 1.0.28. I list `bun@1.0.28` as a dependency and start bun with `bunx bun some_file.ts`.

**Comment by tiptenbrink** [comment]
Some additional info: with `Bun.spawn` I'm not having any issues. I've tried creating a minimum reproducible example but can't seem to reproduce it reliably.

**Comment by zackradisic** [comment]
This panic was removed some time ago (can't remember exactly which PR)
