### ISSUE TITLE
bundler: allow a way to define what global variables are allowed

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#9382]
### What is the problem this feature would solve?

This bug went unnoticed in bug for ?????? amount of time.

![image](https://github.com/oven-sh/bun/assets/24465214/8c1ec412-6b9f-4d93-9329-6598b690d7cb)

This should be a compile error at least in the context of bun's own codebase. but secondly we should have had tests that hit this branch of code, as we currently don't, and my only reproduction into it is via some form of flakiness of native readable on Windows.

### What is the feature you are proposing to solve the problem?

allow an opt-in explicitly defining a list of globals or having a builtin default of the globals the target likely has. a bundle error occurs when a unbound global is used.

### What alternatives have you considered?

- it would be a bad idea to further increase complexity of the builtin bundler. ideally as time goes on we move more features of it into general purpose features of the bundler.

- another idea is to simply use a JS linter, or fully migrate all the builtin code into typescript, but these have many shortcomings.

**Comment by Jarred-Sumner** [comment]
IMO, the real fix here is using TypeScript.

**Comment by paperclover** [comment]
there are 37858 remaining lines of javascript within `src/js`, as well as the fact we do not use `tsc` to check any of our code, as well as the fact `tsc` currently **crashes** in our repository. but this is likely still a better solution, but a longer term one.
