### ISSUE TITLE
windows: tty stdin raw mode (used by create clis) doesnt work at all

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#9383]
### What version of Bun is running?

yeah

### What platform is your computer?

Windows

### What steps can reproduce the bug?

use create-t3-app or create-next-app on windows

### What is the expected behavior?

it to work

### What do you see instead?

does not properly enable raw mode

### Additional information

Related: a specific case that happens on all platforms #7718

**Comment by Jarred-Sumner** [comment]
for reference, the following does nothing

<img width="735" alt="image" src="https://github.com/oven-sh/bun/assets/709451/3814f475-674d-47ad-a15b-60bfba9b37d8">

**Comment by Jarred-Sumner** [comment]
since been fixed
