### ISSUE TITLE
"Attempted to assign to readonly property" error with `power-assert` package

### ISSUE THREAD

**Issue by DetachHead** [oven-sh/bun#940]
### Version

0.1.5

### Platform

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?

```ts
const assert = require('power-assert')

assert(true)
```

### What is the expected behavior?

no error

### What do you see instead?

```
$ bun run asdf.ts
32 |     switch (typeOfAssert) {
33 |     case 'function':
34 |         enhancedAssert = empowerAssertFunction(assert, options);
35 |         break;
36 |     case 'object':
37 |         enhancedAssert = empowerAssertObject(assert, options);
                             ^
TypeError: Attempted to assign to readonly property.
      at empowerCore (/project/node_modules/empower-core/index.js:37:25)
      at empower (/project/node_modules/empower/index.js:83:25)
      at customize (/project/node_modules/power-assert/index.js:47:24)
      at /project/node_modules/power-assert/index.js:64:20
      at bun:wrap:1:16354
      at /project/asdf.ts:1:23
```

**Comment by Electroid** [comment]
This is no longer an issue as of `0.2.2`, tested using:

```js
const assert = require('power-assert');

assert(false);
// AssertionError: false == true
// code: "ERR_ASSERTION"
//      at node:assert:921:52
// ^ (this error is expected)
```

**Comment by basemkhirat** [comment]
Still have the issue in bun `1.0.20`

build command: 
```bash
bun build ./app/index.ts --outdir ./dist --target node
```

```
$ bun run ./dist/index.js
43767 |    * for-own <https://github.com/jonschlinkert/for-own>
43768 |    *
43769 |    * Copyright (c) 2014-2017, Jon Schlinkert.
43770 |    * Released under the MIT License.
43771 |    */
43772 |   var forIn = require_for_in();
          ^
TypeError: Attempted to assign to readonly property.
      at /Users/basem/www/express-typescript/dist/index.js:43772:3
      at /Users/basem/www/express-typescript/dist/index.js:17:72
      at /Users/basem/www/express-typescript/dist/index.js:43810:11
      at /Users/basem/www/express-typescript/dist/index.js:17:72
      at /Users/basem/www/express-typescript/dist/index.js:43965:35
      at /Users/basem/www/express-typescript/dist/index.js:17:72
      at /Users/basem/www/express-typescript/dist/index.js:57437:22
```

**Comment by braden-w** [comment]
I ran into an identical "Attepted to assign to readonly property" error earlier while running [Astro](https://github.com/withastro/astro), was able to fix by running `bun upgrade`. Thought I had the latest version of bun but turns out I was only on `v1.0.7` when the latest was `v1.0.26`.

I know this is for a separate issue, but this issue is the first that comes up on a Google search for the error I was getting with Astro. So for anyone using Astro who happens to be getting an identical error, just wanted to add this!

**Comment by AdamAnSubtractM** [comment]
> I ran into an identical "Attepted to assign to readonly property" error earlier while running [Astro](https://github.com/withastro/astro), was able to fix by running `bun upgrade`. Thought I had the latest version of bun but turns out I was only on `v1.0.7` when the latest was `v1.0.26`.
> 
> I know this is for a separate issue, but this issue is the first that comes up on a Google search for the error I was getting with Astro. So for anyone using Astro who happens to be getting an identical error, just wanted to add this!

This worked for me, thank you.
