### ISSUE TITLE
Invalid template strings generated after compile

### ISSUE THREAD

**Issue by kikuchan** [oven-sh/bun#9406]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Linux 6.7.5-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Save the following script to a file, say `x.ts` here
```ts
function func(...args) {
  console.log(args);
}

func`☺️`;
func(`☺️`);
```
2. Compile with `bun build --compile --outfile=x x.ts`
3. Execute it by `./x`

### What is the expected behavior?

Should be the same result of the `bun run x.ts`

```
[
  [ "☺️" ]
]
[ "☺️" ]
```

### What do you see instead?

Wrong sequence of the string printed
```
[
  [ "â˜ºï¸" ]
]
[ "☺️" ]
```

### Additional information

`bun build x.ts` outputs unescaped UTF8 string along with the escaped one:
```ts
// x.ts
var func = function(...args) {
  console.log(args);
};
func`☺️`;
func(`\u263A\uFE0F`);
```

**Comment by Jarred-Sumner** [comment]
ah this is due to us printing as latin1 and then somewhere else reading as utf8

**Comment by kikuchan** [comment]
Although the last `bun build` still outputs the mixed string of escaped and unescaped, the first `--compile`d executable outputs proper strings as expected now. Thanks!
