### ISSUE TITLE
[shell quiet & lines] don't work with returned text has length > 65535

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#9411]
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

- quiet & lines don't work with returned text has length > 65535
```
import { $ } from 'bun';

// working
// const shell = await $`cat 110kb.json`.quiet();

// not working
const shell = await $`cat 26mb.json`.quiet();

console.log(shell);
```

download for testing :
- 110kb.json : https://drive.google.com/file/d/1jEe5Pzr2wn21o-U8z3q02OJh3231S9oN/view?usp=drive_link
- 26mb.json : https://drive.google.com/file/d/1guA66f7_6smvVslAOJCTMBiUOtv5y0nQ/view?usp=drive_link

### What is the expected behavior?

return ShellOutput

### What do you see instead?

returned nothing, hang & high CPU usage

### Additional information

The same error if i get 261000 rows from Redis by Bun's shell

**Comment by zackradisic** [comment]
This should be fixed in my https://github.com/oven-sh/bun/tree/fix-shell-regressions branch

**Comment by truongan07** [comment]
> This should be fixed in my https://github.com/oven-sh/bun/tree/fix-shell-regressions branch

I hope you early fix it. Thanks for your hard working

**Comment by truongan07** [comment]
Bun 1.0.36, i tested 1GB size of big data & get 588675 rows from Redis. It just worked as expected. Thanks for fixed
