### ISSUE TITLE
`bun build` should prefer scripts defined in package.json over bun's internal build

### ISSUE THREAD

**Issue by kvnwolf** [oven-sh/bun#9421]
### What is the problem this feature would solve?

If I run all my package.json scripts with `bun <scriptname>`, having to change the convention to `bun run build` only on that case is confusing and feels wrong (personal and biased opinion)

### What is the feature you are proposing to solve the problem?

That if a script named `build` exists on my package.json scripts, it should be executed when running `bun build`

**Comment by fdaciuk** [comment]
The way bun works is how yarn also works. If you have a script that is the same defined in the CLI, you should use `bun run`, like yarn does =)

Maybe bun could give us some tips, telling us that we have a script with the same name as the command. It would be nice =)
