### ISSUE TITLE
1.0.31 bun install fails to resolve packages in devDependencies

### ISSUE THREAD

**Issue by Leni-Vienne** [oven-sh/bun#9433]
### What version of Bun is running?

1.0.31

### What platform is your computer?

Linux 5.15.0-88-generic x86_64 x86_64

### What steps can reproduce the bug?

- Have package.json with devDependencies, a bun.lockb and no node_modules, like so :
```json
{
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "eslint": "^8.38.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-vue": "^9.10.0",
    "vite": "^5.1.6"
  }
}
```
- Then install some of the devDependencies listed but not all, like so : `bun install vite @vitejs/plugin-vue`

### What is the expected behavior?

Only the packages mentionned should be installed, without error

### What do you see instead?

```
bun add v1.0.31 (e2567512)
error: eslint@^8.38.0 failed to resolve
error: eslint-config-standard@^17.0.0 failed to resolve
error: eslint-plugin-vue@^9.10.0 failed to resolve
```
And a gitlab runner crash, which errors out the pipleline

### Additional information

Happens on my gitlab runner and on my ubuntu VM, does not happen on bun 1.0.30. Have a nice day :smil

**Comment by Electroid** [comment]
Not able to reproduce on macOS or an EC2 VM. Does the gitlab workflow happen to be public?

**Comment by Leni-Vienne** [comment]
Here is a repo reproducing the issue : https://github.com/Leni-Vienne/bun_dev_dependencies_issue
I've tried to narrow it down more but it gets quite unpredictable with the bun.lockb file in the way and I had to add some production dependencies to reproduce the bug

**Comment by Jarred-Sumner** [comment]
Confirming I'm able to reproduce the issue locally. 

Minimal reproduction:

Put this into package.json:
```json
{
  "devDependencies": {
    "underscore": "1.9.1",
    "lodash": "4.17.21"
  }
}
```

Then run `bun install`.

It installs successfully:
```zig
❯ bun install
bun install v1.0.32 (7c9f0763)

 + lodash@4.17.21
 + underscore@1.9.1 (v1.13.6 available)

 2 packages installed [183.00ms]
```

Then, manually edit your package.json to look like this:
```json
{
  "devDependencies": {
    "underscore": "1.9.1",
    "lodash": "4.17.21"
  },
  "dependencies": {
    "lodash": "4.17.21"
  }
}
```

Note the `"dependencies"` there.

Then run `bun install --production`:
```zig
❯ bun install --production
bun install v1.0.32 (7c9f0763)
4 |     "lodash": "4.17.21"
        ^
warn: Duplicate dependency: "lodash" specified in package.json
   at /Users/jarred/Desktop/reproo/package.json:4:5

7 |     "lodash": "4.17.21"
                  ^
note: "lodash" originally specified here
   at /Users/jarred/Desktop/reproo/package.json:7:15

Checked 1 install across 3 packages (no changes) [2.00ms]
```

It has a warning but overall installs successfully.

Now run `bun install`, without the `--production` flag:

```zig
~/Desktop/reproo 
❯ bun install
bun install v1.0.32 (7c9f0763)
4 |     "lodash": "4.17.21"
        ^
warn: Duplicate dependency: "lodash" specified in package.json
   at /Users/jarred/Desktop/reproo/package.json:4:5

7 |     "lodash": "^4.17.21"
                  ^
note: "lodash" originally specified here
   at /Users/jarred/Desktop/reproo/package.json:7:15
error: lodash@4.17.21 failed to resolve
error: underscore@1.9.1 failed to resolve
```

It reports that `devDependencies` failed to resolve.

Part of the problem is when `--production` is in use, we should never save the lockfile to disk.

**Comment by Jarred-Sumner** [comment]
@Leni-Vienne are you using `bun install --production`?

**Comment by Leni-Vienne** [comment]
Yes i am indeed, but not sure yet if it's strictly necessary for the error to occur. Take a look at my repo above your last comment, it might help
