### ISSUE TITLE
styleText is not yet defined in `node:util`

### ISSUE THREAD

**Issue by rhuanbarreto** [oven-sh/bun#9437]
### What version of Bun is running?

v1.0.31

### What platform is your computer?

Arm MacOS

### What steps can reproduce the bug?

`@types/node` doesn't have yet support for `styleText` method in `node:util` that was released in Bun v1.0.31

### What is the expected behavior?

Typescript to recognize the type for the following import:

```
import { styleText } from "node:util";
```

### What do you see instead?

```Module '"node:util"' has no exported member 'styleText'.ts(2305)```

### Additional information

I'm using the following type libraries:
```
"@types/bun": "1.0.8",
"@types/node": "20.11.28",
```

**Comment by mangs** [comment]
I have the same issue. The latest version of `@types/bun` (1.0.8) does not include the types for `styleText`.

Repro:

- Failing GitHub Action error: https://github.com/mangs/bun-utils/actions/runs/8299807436/job/22716354131?pr=7#step:9:6
- Code causing error: https://github.com/mangs/bun-utils/pull/7/files#diff-b9ad48a6f77b6b09056eba8f72e4e9d011093ae6ee1f645f34c7454116a5cc6eR2

I tried an override in `package.json` for `bun-types` to `1.0.31` and that didn't help.

**Comment by rhuanbarreto** [comment]
Tracking issue in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69212

**Comment by mangs** [comment]
@rhuanbarreto These types were [added to `bun-types`](https://github.com/oven-sh/bun/pull/9945) a few versions ago. The PR you referenced has them added too, so once it gets merged we can remove them from `bun-types` and fall back to relying on `@types/node` like before.

**Comment by rhuanbarreto** [comment]
Problem solved. Thanks!
