### ISSUE TITLE
bun start not working on Windows

### ISSUE THREAD

**Issue by codebyaadi** [oven-sh/bun#9442]
### What version of Bun is running?

1.0.30

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

I have my package.json script set as `"start": "bun --watch run src/index.ts"`. After running `bun start` command. I am getting the following error: 

`error: Failed to due to error TODO: spawn() is not yet implemented on Windows`

**Comment by Electroid** [comment]
Can you run `bun upgrade --canary` and try again?

**Comment by codebyaadi** [comment]
> Can you run `bun upgrade --canary` and try again?

Thanks! It worked.
