### ISSUE TITLE
environment variable loading is broken with 1.0.31

### ISSUE THREAD

**Issue by wwelder** [oven-sh/bun#9445]
### What version of Bun is running?

1.0.31

### What platform is your computer?

broken for me on both linux and macOS

### What steps can reproduce the bug?

created a repo for minimum failure case
https://github.com/gopricy/bun-env-bug

run `bun prod` prints "production" as expected in 1.0.30
and prints "development" in 1.0.31

**Comment by nektro** [comment]
```
~/src/bun-env-bug master                                                                                                                                                                                                                                                                                       13:37:42
❯ bun-debug run prod
$ NODE_ENV=production bun index.ts
production

~/src/bun-env-bug master                                                                                                                                                                                                                                                                                       13:37:46
❯ bun-debug prod    
[bun shell] $ NODE_ENV=production bun index.ts
development
```

looks like running `bun run prod` should work as a temporary workaround. looking into a full fix now.

**Comment by wwelder** [comment]
thanks nektro! I didn't know there could be a difference

**Comment by nektro** [comment]
generally there shouldn't be, thanks for the quick report :)

**Comment by paperclover** [comment]
Fixed in https://github.com/oven-sh/bun/pull/9689
