### ISSUE TITLE
Regression in Bun.$ subprocess interactivity with @inquirer/prompts in v1.0.31

### ISSUE THREAD

**Issue by alextbok** [oven-sh/bun#9458]
### What version of Bun is running?

1.0.31+e25675121

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Use Bun to run a script that spawns a Node.js subprocess which invokes [@inquirer/prompts](https://www.npmjs.com/package/@inquirer/prompts) (v4.3.0) for user interaction.

1. The subprocess attempts to use the select function to prompt the user to choose between predefined options.
2. Observe the behavior when running the script using Bun version 1.0.30.
3. Repeat the observation with Bun version 1.0.31.

Code to reproduce:
```javascript
const program = `
const { select } = require('@inquirer/prompts');

async function run() {
  const foobar = await select({
    message: 'Foo or Bar',
    choices: [
      { name: 'Foo', value: 'foo' },
      { name: 'Bar', value: 'bar' },
    ],
  });
  console.log('Choice:', foobar);
}

run();
`;

await Bun.$`echo "Bun version: $(bun --version)"`;
await Bun.$`[ -t 0 ] && echo "[stdin] good" || echo "[stdin] bad"`;
await Bun.$`node -e ${program}`;
```

### What is the expected behavior?

The script is expected to display the prompt, allowing the user to interactively select either "Foo" or "Bar" using the arrow keys. The interactive functionality is expected to work consistently across different Bun versions, including v1.0.30 and v1.0.31.

### What do you see instead?

**v1.0.30**
Working as expected. The prompt is displayed, and the user can interact with it to make a selection.
```
Bun version: 1.0.30
[stdin] good
? Foo or Bar Bar
Choice: bar
```

**v1.0.31**
The prompt is displayed but does not respond to user input. The user is unable to select an option or otherwise interact with the subprocess.
```
Bun version: 1.0.31
[stdin] good
? Foo or Bar (Use arrow keys)
❯ Foo
```

### Additional information

Given the v1.0.31 changelog mentions significant changes to how subprocesses are spawned and file streaming is handled, it's possible these updates may have inadvertently impacted the handling of stdin/stdout/stderr streams in scenarios requiring terminal interaction. Both Bun versions confirm stdin is inherited and is connected to a terminal, so the regression might be related to changes in subprocess spawning behavior in v1.0.31.

**Comment by Jarred-Sumner** [comment]
This was partially fixed in #9402, however there remains an issue where the event loop is not exiting 

cc @zackradisic we need to improve the test coverage

**Comment by zackradisic** [comment]
This seems to be working with bun v1.0.33

**Comment by alextbok** [comment]
> This seems to be working with bun v1.0.33

Confirmed! Thanks @zackradisic and @Jarred-Sumner for the quick turnaround.
