### ISSUE TITLE
Regression on Bun.$: `mv` causes `ls: No such file or directory` or `ls: Illegal byte sequence`

### ISSUE THREAD

**Issue by aboqasem** [oven-sh/bun#9459]
### What version of Bun is running?

1.0.31+e25675121 & 1.0.32+c9a70f168

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```sh
touch tmp.a && bun --print 'await Bun.$`mv tmp.a tmp.b`'; rm -rf tmp.a
# ls: No such file or directory
```

```sh
bun --print 'await Bun.$`touch /tmp/a`; await Bun.$`mv /tmp/a /tmp/b`'
# ls: Illegal byte sequence
```

### What is the expected behavior?

This was working in `1.0.30`

**Comment by damywise** [comment]
I'm still having this problem, though my OS is Windows 11.
Bun version 1.0.32 (the latest one right now, I just ran `bun upgrade`)

```
bun --print 'await Bun.$`mv tmp.a tmp.b`'
```
results in:
```
warn: Called translateNTStatusToErrno with OBJECT_NAME_INVALID which does not have a mapping to errno.
ls: An unknown error occurred
```

Maybe I'll check which previous version does not have this error, I used to be able to run just fine until I ran bun upgrade sometime ago.

**Comment by Jarred-Sumner** [comment]
This fix didn't land in v1.0.32. it will land in v1.0.33 though

**Comment by aboqasem** [comment]
You can also wait for the `canary` version then `bun upgrade --canary`.

@Jarred-Sumner how can I check if a `canary` has been released for a commit? Is it only if the builds succeed?

Checking https://github.com/oven-sh/bun/commits/main/, 4a6cda8d807c391b26a18182343b9d15510bb034 build has been cancelled.

**Comment by Jarred-Sumner** [comment]
You can run `bun --revision` to get the git sha

Whenever a newer build is pushed we cancel the older build in progress

It should release in about an hour
