### ISSUE TITLE
in v1.0.31 process.exit(1) does not crash github actions step, but it did in 1.0.30

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#9460]
### What version of Bun is running?

1.0.31+e25675121

### What platform is your computer?

ubuntu-22.04 (20240310.1.0)

### What steps can reproduce the bug?

These lines work differently in 1.0.31 and 1.0.30 - https://github.com/gramiojs/types/blob/main/scripts%2Fcicd.ts#L14-L15

with latest bun (1.0.31) - https://github.com/gramiojs/types/actions/runs/8307039677/job/22735827448

when i pin Bun version at 1.0.30 it works as it should - https://github.com/gramiojs/types/actions/runs/8307179301/job/22736095823

**Comment by Jarred-Sumner** [comment]
This was fixed in #9449 and is now available in the `canary` release, which will become the release version soon. Sorry about this! 

Please let us know if you run into it again after upgrading
