### ISSUE TITLE
Import indirection via `package.json` doesn't work with `bun:*` namespace

### ISSUE THREAD

**Issue by sgammon** [oven-sh/bun#9478]
### What version of Bun is running?

`1.0.32`

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

1. In **`package.json`**:
```json
{
  "name": "some-package",
  "imports": {
    "#tests": {
      "bun": "bun:test",
      "default": "@jest/globals"
    }
  },
  "devDependencies": {
    "@jest/globals": "latest"
  }
}
```

2. In **`some.test.mts`**:
```typescript
import { expect, test } from "bun:test"

test("2 + 2", () => {
    expect(2 + 2).toBe(4)
})
```

3. **`bun test`**:
```
bun test v1.0.32 (5fec71bd)

tests/sanity.test.mts:
✓ 2 + 2 [0.23ms]

 1 pass
 0 fail
 1 expect() calls
Ran 1 tests across 1 files. [7.00ms]
```

4. Replace import in **`some.test.mts`** with:
```patch
-import { expect, test } from "bun:test"
+import { expect, test } from "#tests"
```

5. **`bun test`**:
```
bun test v1.0.32 (5fec71bd)

tests/sanity.test.mts:
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'expect' not found in module 'bun:test'.

 0 pass
 1 fail
Ran 1 tests across 1 files. [9.00ms]
```

### What is the expected behavior?

I expect the `import` indirection to import the specified module, and the test to pass.

### What do you see instead?

The test fails.

**Comment by Jarred-Sumner** [comment]
This is confusing, but `bun:test` doesn't exist. The transpiler converts it into `Bun.jest(import.meta.path)`. 

> SyntaxError: Export named 'expect' not found in module 'bun:test'.

The error here shows that import indirection via package.json is indeed working - note how it says `"bun:test"`

By the way, `bun test` automatically rewrites `@jest/globals` to `bun:test` (as well as `vitest`) - so you might not need to do this in the first place

**Comment by sgammon** [comment]
Gotcha, thanks for the pointer. Using regular `@jest/globals` works fine. FWIW I think Jest is doing something similar, because imports are showing the same behavior with Jest/Node.

I think this can be closed

**Comment by sgammon** [comment]
@Jarred-Sumner Unless... would be nice if the Bun transpiler allowed aliases like this. Happy to re-open or even attempt a PR if you are open to it.

I've used `imports: { #something }` to map across platforms before and it could be a useful pattern.
