### ISSUE TITLE
Bun crash `integer cast truncated bits`

### ISSUE THREAD

**Issue by hiepgia** [oven-sh/bun#9481]
### What version of Bun is running?

1.0.32-canary.21+5fec71bda

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Try run my React ClientApp on Windows and it crash

bun start      
```     
$ react-scripts start

uh-oh: integer cast truncated bits
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.32-canary.21 (5fec71bd) Windows x64
AutoCommand: dotenv
Elapsed: 11ms | User: 0ms | Sys: 15ms
RSS: 24.70MB | Peak: 24.70MB | Commit: 68.12MB | Faults: 6174
----- bun meta -----

0   00007FF751A5A9B8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 24012 panic: integer cast truncated bits
???:?:?: 0x7ff7506b2f51 in ??? (bun.exe)
???:?:?: 0x7ff7506b644c in ??? (bun.exe)
???:?:?: 0x7ff7506c85f6 in ??? (bun.exe)
???:?:?: 0x7ff7506cc7d5 in ??? (bun.exe)
???:?:?: 0x7ff75041157f in ??? (bun.exe)
???:?:?: 0x7ff752f10ae3 in ??? (bun.exe)
???:?:?: 0x7ffd9158257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffd92bcaa57 in ??? (ntdll.dll)
```

### What is the expected behavior?

It should start my application.

**Comment by Electroid** [comment]
Could you share a package.json that can reproduce this issue?

**Comment by hiepgia** [comment]
I will need some approvals to share package.json. I will share when it ready.

**Comment by hiepgia** [comment]
@Electroid : I tried to re-create this issue with a new repo: https://github.com/hiepgia/bun-env-crash

#### What version of Bun is running?
1.0.35-canary.4+ee5fd51e8

#### What platform is your computer?
Microsoft Windows NT 10.0.22631.0 x64

#### What steps can reproduce the bug?
In my local `.env.development`, I have an environment variable named `REACT_APP_DISABLED_FEATURE` which is used to disable some features that aren't ready to ship. And in the developing phase. We set an **empty string** to this which caused `bun` to crash.
