### ISSUE TITLE
Bun silent crash with webpack resourceQuery

### ISSUE THREAD

**Issue by xoxoxo** [oven-sh/bun#9484]
### What version of Bun is running?

1.0.32+5fec71bda

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

 import svg with ?url example
`import closeButton from 'assets/icons/closebutton.svg?url';`

example webpack config
```
      {
        test: /\.svg$/i,
        type: 'asset',
        resourceQuery: /url/,
      },
      {
        test: /\.svg$/i,
        issuer: /\.[jt]sx?$/,
        resourceQuery: { not: [/url/] },
        use: [{loader: '@svgr/webpack', options: { prefixIds: false }}],
      },
```

Bun will crash silently 4 out of 5 times (means it works fine 1 out 5 times) what helps is importing some of parent components as require instead top import then it will crash 1 out 5.  We import these components for ssr as in renderToString.

### What is the expected behavior?

Should not crash or just throw some error?

### What do you see instead?

Nothing. Sometimes works sometimes crashes with error but I fixed most issues if there was any.

**Comment by Jarred-Sumner** [comment]
can you check if this reproduces in bun v1.0.30? i'm wondering if this was caused by https://github.com/oven-sh/bun/pull/9399

```
curl https://bun.sh/install | bash -s 'bun-v1.0.30' 
```

**Comment by xoxoxo** [comment]
@Jarred-Sumner good tip. So i went back as far as 1.0.7 and seems to work perfectly fine any version above crashes

**Comment by xoxoxo** [comment]
seems to be fixed in 35
