### ISSUE TITLE
bunx --bun vite build not building

### ISSUE THREAD

**Issue by nojaf** [oven-sh/bun#9486]
### What version of Bun is running?

1.0.33-canary.5+9e91e137f

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Create a new Vite project, https://bun.sh/guides/ecosystem/vite
Run `bunx --bun vite build`

### What is the expected behavior?

`vite build` is executed by Bun.

### What do you see instead?

The `vite` dev server command is ran.

**Comment by nojaf** [comment]
Interestingly enough, I don't get this with `bun --bun`,  only with `bunx`.
I'm rather confused about `bunx` versus `bun` right now.

**Comment by denovodavid** [comment]
Seems related to #9499, with `bunx` not handling arguments.
