### ISSUE TITLE
Destructuring elements of `Array(n)` causes `TypeError: Right side of assignment cannot be destructured`

### ISSUE THREAD

**Issue by aboqasem** [oven-sh/bun#9487]
### What version of Bun is running?

tested on 1.0.25 & 1.0.33+9e91e137f 

### What platform is your computer?

Darwin 23.3.0 x86_64 i386

### What steps can reproduce the bug?

```js
const arr = new Array(1);

arr.push({ name: "name" });

const { name } = arr[0];

console.log(name);
```

```shell
bun --print 'const foo = []; for (const {} of foo) {}'
bun --print 'const foo = Array(); for (const {} of foo) {}'
bun --print 'const foo = new Array(); for (const {} of foo) {}'
# undefined

bun --print 'const foo = new Array(); foo.push({ name: "" }); const { name } = foo[0];'
# 1


bun --print 'const foo = Array(1); for (const {} of foo) {}'
bun --print 'const foo = new Array(1); for (const {} of foo) {}'
bun --print 'const foo = new Array(1); foo.push({ name: "" }); const { name } = foo[0];'
# TypeError: Right side of assignment cannot be destructured
```

### What do you see instead?

`TypeError: Right side of assignment cannot be destructured`

**Comment by yschroe** [comment]
What is the expected behaviour here? For me the error message looks correct as you are trying to destructure an empty entry of the array:
```javascript
const foo = new Array(1);  // [empty]
for (const {} of foo) {}   // object destructuring of empty

const foo = new Array(1);  // [empty]
foo.push([{ name: "" }]);  // [empty, {name: ""}]
const { name } = foo[0];   // first entry of array is empty -> cannot be destructured
```

Running the code on node.js results in the same error for me.

**Comment by aboqasem** [comment]
Apologies I just updated the issue description to not push an array, but instead the object itself.

However, the code does not work in Node.js as well:

<img width="942" alt="Screenshot 2024-03-23 at 5 03 19 PM" src="https://github.com/oven-sh/bun/assets/62098043/7bca2244-26ab-4245-82a5-2aa57c54defd">

The only difference is the size of the array, why shouldn't it work?

**Comment by aboqasem** [comment]
Safari, Brave, Bun, Node.js. All of them do not run this code.

It turns out:
```js
const arr = new Array(1);

arr.push({ name: "name" });

console.log(arr); // [ <1 empty item>, { name: 'name' } ]
```

**Comment by yschroe** [comment]
The reason why the version with `new Array()` works while `new Array(1)` does not is the array size. If you iterate over the array created via `new Array()` the length of the array is 0, so none of the destructuring code in the for-loop is actually executed. The array from `new Array(1)` is of length 1 and is initialized with the 'empty' value. In the for-loop the code now tries to destructure 'empty' which does not work and throws the error.
