### ISSUE TITLE
Version 1.0.32 broke Eslint setup

### ISSUE THREAD

**Issue by thecrabcode** [oven-sh/bun#9489]
### What version of Bun is running?

1.0.32

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Create a monorepo with turborepo, making sure to have eslint installed in a pacakge. Run the lint command

### What is the expected behavior?

The command should run as expected

### What do you see instead?

I keep on seeing this error
```
@my-app/reservoir-protocol:lint: There was a problem loading formatter: /builds/apps/my-app/node_modules/eslint/lib/cli-engine/formatters/stylish
@my-app/reservoir-protocol:lint: Error: require() of ES Module /builds/apps/my-app/node_modules/chalk/source/index.js from /builds/apps/my-app/node_modules/eslint/lib/cli-engine/formatters/stylish.js not supported.
```

### Additional information

As soon as I downgrade to v1.0.31 the issue is resolved. This was not happening with earlier versions either, so I am pretty sure something has been introduced in 1.0.32 that broke it

**Comment by nimrossum** [comment]
I think it would be helpful if you can provide the exact commands used for reproducing the repository that is broken.

**Comment by thecrabcode** [comment]
Unfortunately it's a bit complicated to replciate as we have a private monorepo built on turborepo. What we have is a base eslint-config package defined as such 
```
{
  "env": {
    "es2021": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint",
    "prettier"
  ],
  "rules": {
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "no-mixed-spaces-and-tabs": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-extra-semi": "off",
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/no-namespace": "off",
    "no-case-declarations": "off",
    "no-extra-semi": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^_"
      }
    ],
    "prettier/prettier": "error"
  },
  "ignorePatterns": [
    "example /*",
    "tests/**/*"
  ]
}
```

and then for each app and package all we do is to extends such package as such 
```
{
  "$schema": "https://json.schemastore.org/eslintrc",
  "extends": ["@my-app/eslint-config/base.json"]
}
```

Running the lint command works just fine on v1.0.30, but if I upgrade to v1.0.32, without changing anything else, it breaks immediately due to 
```
@my-app/error-protocol:lint: There was a problem loading formatter: ~/repos/apps/my-app/node_modules/eslint/lib/cli-engine/formatters/stylish
@my-app/error-protocol:lint: Error: require() of ES Module ~/repos/apps/my-app/node_modules/chalk/source/index.js from ~/repos/apps/my-app/node_modules/eslint/lib/cli-engine/formatters/stylish.js not supported.
@my-app/error-protocol:lint: Instead change the require of index.js in ~/repos/apps/my-app/node_modules/eslint/lib/cli-engine/formatters/stylish.js to a dynamic import() which is available in all CommonJS modules.
```

It works ok on v1.0.31 on my local, but that also fails when running on Gitlab CI.

**Comment by Jarred-Sumner** [comment]
@thecrabcode one subtle change we made in v1.0.32 was to hoist `devDependencies` above regular dependencies in more cases. I'm pretty sure it would only ever error with `error.DependencyLoop` in those cases though. This was to allow better support having both the same package in `devDependencies` and `dependencies`. I wonder if this is a workspace and there are multiple versions of these eslint related packages?

**Comment by thecrabcode** [comment]
hi @Jarred-Sumner, thanks for your answer! 

We do indeed use workspaces, but we have a turbo package which install all the eslint dependencies, and it contains base eslint config files (we have different base configs for different kinds of apps, such as next config, base config etc...) that we extends from in each single app and package. 

So in theory every app and package should use that one "central" dependency that is installed in the eslint config packge.

**Comment by Jarred-Sumner** [comment]
We will push Bun v1.0.34 to fix this tonight

**Comment by cuquo** [comment]
the error with eslint seems to be related to ajv, Eslint uses an older version (v6) and with the new hoisting is trying to make eslint work with a newer version that throws a `option missingRefs`. I will confirm if the newest version fixes this

**Comment by cuquo** [comment]
I just installed the latest canary and it works correctly

**Comment by thecrabcode** [comment]
That's great to hear! Thanks for the quick fix. Do you guys know when 1.0.34 will be made official?

**Comment by cuquo** [comment]
@thecrabcode  "when its done" I guess. I usually follow releases in @Jarred-Sumner Twitter account. The dates there are not accurate but gives us an idea of the ETA

**Comment by thecrabcode** [comment]
@cuquo sounds good, thanks!

**Comment by whjvenyl** [comment]
nice.. I'm in the same boat as @thecrabcode since 1.0.32 also broke `browser-sync` 
eagerly awaiting the new release

**Comment by thecrabcode** [comment]
Just downloaded the 1.0.34 release and I can confirm this sorted the issue out. Thanks for the super quick turnaround guys!
