### ISSUE TITLE
`bun install` on macos creates a cache named `~` in the current directory

### ISSUE THREAD

**Issue by Zuruuh** [oven-sh/bun#9494]
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```bash
mkdir tmp
cd tmp
# basically install any package
bun add --dev @types/bun
ls
## ls output:
# bun.lockb
# node_modules
# package.json
# ~
```

### What is the expected behavior?

The bun cache is stored in the user home dir `/Users/<name>/.bun/install/cache`

### What do you see instead?

The bun packages cache is stored at `$CWD/~/.bun/install/cache` (`/Users/<name>/dev/bun-install-repro/~/.bun/install/cache` in my case)

### Additional information

```toml
# ~/.config/.bunfig.toml
telemetry = false
```

Verbose install:
```bash
bun i --verbose
bun install v1.0.33 (9e91e137)
Loaded 5 hoisted_dependencies
Loaded 6 resolutions
Loaded 6 dependencies
Loaded 0 extern_strings
Loaded 338 string_bytes
Enqueue package manifest for download: @types/bun
  🔍 Resolving [1/1] [PackageManager] waiting for 1 tasks
Request: GET /@types%2fbun
        Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
        Connection: keep-alive
        User-Agent: Bun/1.0.33
        Host: registry.npmjs.org
        Accept-Encoding: gzip, deflate, br

Response: < 200 OK
<       Date: Mon, 18 Mar 2024 16:54:08 GMT
<       Content-Type: application/vnd.npm.install-v1+json
<       Transfer-Encoding: chunked
<       Connection: keep-alive
<       CF-Ray: 8666be2bfb14024b-CDG
<       CF-Cache-Status: HIT
<       Access-Control-Allow-Origin: *
<       Age: 88
<       Cache-Control: public, max-age=300
<       ETag: W/"d91160a8f357c77d42f3764ee85b12f3"
<       Last-Modified: Mon, 11 Mar 2024 08:25:06 GMT
<       Vary: accept-encoding, accept
<       Server: cloudflare
<       Content-Encoding: br

    [102.25ms]
 Downloaded @types/bun versions

-- BEGIN SHA512/256(`${alphabetize(name)}@${order(version)}`) --
@types/bun@1.0.8
@types/node@20.11.28
@types/ws@8.5.10
bun-types@1.0.29
undici-types@5.26.5
-- END HASH--

Checked 5 installs across 6 packages (no changes) [122.00ms]
Saving 1 trees
Saving 5 hoisted_dependencies
Saving 6 resolutions
Saving 6 dependencies
Saving 0 extern_strings
Saving 338 string_bytes
```

relevant env output:
```bash
HOME=/Users/MyRealUsername
BUN_INSTALL=~/.bun
```

I updated directly from 1.0.30 to 1.0.33, and I don't remember having such issue with .30. 
Also i've tried to reproduce the issue using the docker image `oven/bun:canary-debian` and didn't get the issue

**Comment by Jarred-Sumner** [comment]
Very strange. Is it possible you have a ~ in either the “BUN_INSTALL” env var or XDG_CACHE_HOME or another environment variable? You can print env vars by running `env` in your terminal

**Comment by Zuruuh** [comment]
yeah indeed, the `BUN_INSTALL` env var uses ~ and not $HOME 👍I did change this myself so it probably comes from this. Though, I would expect the tilde to be resolved to my home directory implicitely, wdyt ?

**Comment by gvilums** [comment]
@Jarred-Sumner correct me if I'm wrong here, but usually it's the shell that resolves the tilde, so this would not be something that bun should do. In fact, if, for some reason, somebody wanted to use a directory named `~`, resolving the tilde would make this impossible.
