### ISSUE TITLE
bun test --watch --only has unexpected behavior

### ISSUE THREAD

**Issue by Zombobot1** [oven-sh/bun#9495]
### What version of Bun is running?

1.0.32

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Technically this is not a bug but it breaks workflows which were possible with jest and vitest. This is a serious argument in my team against migrating from jest and vitest to bun because it will make development slower.

For example, during development the tests are run in watch mode and it's possible to isolate specific tests using `.only`. When the isolated tests are fixed it is easy to re-run everything by simply removing `.only`. However `bun test --watch --only` in this case runs nothing.

### What is the expected behavior?

There is no need to use `--only` with vitest or jest. Bun makes DX much worse by introducing this flag. Probably in watch mode it should not have any effect.

**Comment by Jarred-Sumner** [comment]
Yeah the —only flag is bad
