### ISSUE TITLE
bunx Error: Cannot find module

### ISSUE THREAD

**Issue by denovodavid** [oven-sh/bun#9499]
### What version of Bun is running?

1.0.33-canary.5+9e91e137f

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. open cmd or powershell. (I haven't tested new powershell (pwsh.exe))
2. run `bunx cowsay "Hello, world!"`, or basically any package with arguments.
3. receive error

### What is the expected behavior?

```
 _______________
< Hello, world! >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### What do you see instead?

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'C:\Users\David\AppData\Local\Temp\bunx-2793055151-cowsay@latest\node_modules\cowsay\cli.js Hello, world!'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1
```

This is the same output as running `node "C:\Users\David\AppData\Local\Temp\bunx-2793055151-cowsay@latest\node_modules\cowsay\cli.js Hello, world!"`. Notice how the "Hello, world!" is included in the quotes with the script, causing the issue.

### Additional information

- `bunx cowsay` works as expected, printing help information about `cowsay`. Adding arguments causes the issue.
- `bunx --bun cowsay "Hello, world!"` also doesn't work as expected, only printing help information about `cowsay` as if no arguments were provided. Also it prints in red text for some reason...

**Comment by danielniccoli** [comment]
I can reproduce with 1.0.33-canary.5+9e91e137f

I can't reproduce with 1.0.26-canary.31+2f8f77eeb, works as expected.

**Comment by denovodavid** [comment]
After doing `bun upgrade`, I started receiving `error: could not determine executable to run for package cowsay`. I removed the `.bun/` folder and reinstalled; same error. I then deleted all folders in `'C:\Users\David\AppData\Local\Temp\bun-*`; and now I'm back to the original issue: `Error: Cannot find module`.

bun 1.0.34-canary.20+b24d3ba5b

**Comment by Kinjalkashyap** [comment]
I too am facing similar issue ig.

### When I run `bunx astro dev`:
```sh
 bunx astro dev
16:18:53 [types] Generated 2ms

 astro  v4.15.2 ready in 799 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

16:18:54 watching for file changes...
```

### But when I run `bunx --bun astro dev`
```sh
 bunx --bun astro dev
16:14:37 [types] Generated 5ms
error: Cannot find module "../data/patch.json" from "undefined"

Bun v1.1.26 (Windows x64)
```

Any help much appreciated!

**Comment by Hydra777777** [comment]
same things happens to me
