### ISSUE TITLE
Zig stage1 compiler needs 11 GB of ram to compile a debug build of Bun

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#95]
A lot of perf stuff for Bun happens at compile time, which costs memory

This will be fixed eventually by Zig's stage2 compiler. However, need to think about some ways to work around this in the meantime. It is okay for me on my machine with 64 GB of ram, but this will be a barrier for contributors.

**Comment by Jarred-Sumner** [comment]
With latest Zig, down to 18 GB.

**Comment by mfeckie** [comment]
🎉

**Comment by Jarred-Sumner** [comment]
Thanks to https://github.com/ziglang/zig/pull/10482, down to 11.3 GB.

**Comment by ghost** [comment]
Wow, I'm lucky I have a machine with 24 GB.

**Comment by paperclover** [comment]
on zig `0.11.0-dev.2777+b95cdf0ae` its down to <5gb at least on MacOS with no zig cache. closing since its not too much anymore and its definitely not the old days of needing a machine with 32/64gb ram
