### ISSUE TITLE
Slim Docker images without all locales

### ISSUE THREAD

**Issue by khromov** [oven-sh/bun#9515]
### What is the problem this feature would solve?

When getting the official Docker image from `FROM oven/bun:1.0.33` the base image contains 30.6MB of locale information:

<img width="473" alt="Screenshot 2024-03-19 at 17 53 56" src="https://github.com/oven-sh/bun/assets/1207507/d422ebf4-03a3-4988-9718-9ffe350051ae">

This is unnecessary for most apps. It would be good if there was a slim image with instructions on how to add the locales that are needed for your applications: Since each locale is usually under 1MB this would save ~30MB per image.

### What is the feature you are proposing to solve the problem?

-

### What alternatives have you considered?

-

**Comment by Electroid** [comment]
We do have a slim tag, `oven/bun:slim`. Does that have the same locale info?

**Comment by khromov** [comment]
Thank you, that does solve it:

```
FROM oven/bun:1.0.33-slim
```
