### ISSUE TITLE
postinstall lifecycle script not running after bun install

### ISSUE THREAD

**Issue by shoham-utila** [oven-sh/bun#9527]
### What version of Bun is running?

v1.0.33

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Add a "postinstall" script to your `package.json` file, and run bun install

Repository for example:
https://github.com/bsShoham/bun-postinstall-bug

### What is the expected behavior?

I expect the `postinstall` to run and show the output of the run
for example for the following script: `"postinstall": "echo \"hello\""` 
I expect the output to be `hello`

### What do you see instead?

nothing, the lifecycle script does not seem to run.

### Additional information

This behavior is inconsistent with NPM in which the `postinstall` script always runs after "npm install" whether changes occurred or not

**Comment by shoham-utila** [comment]
Update:
After further checking, the `postinstall` does run, but no output is shown, not as critical, but still a bug of compatibility with `npm` that does show the output

**Comment by Jarred-Sumner** [comment]
yeah we will fix this soon

**Comment by shoham-utila** [comment]
Works in v1.1 👌
can be closed if no PR needs to reference it directly

**Comment by dylan-conway** [comment]
Fixed in #11647
