### ISSUE TITLE
"." cannot be parsed as a URL (URL contructor)

### ISSUE THREAD

**Issue by Dan1ve** [oven-sh/bun#9532]
### What version of Bun is running?

1.0.33

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

Run a test that contains 

``` ts
const urlPrefix = new URL('.', window.location.href);
```

### What is the expected behavior?

No errors

### What do you see instead?

``` 
const urlPrefix = new URL('.', window.location.href);
                                     ^
TypeError: "." cannot be parsed as a URL against "ignored"
      at new URL (:1:33)
```

### Additional information

Calling the URL constructor with a dot (".") works both in the browser and in Node.JS, so this is a compatibility issue.

**Comment by dylan-conway** [comment]
What version of node are you using? This does not appear to be a valid url in chrome, safari, or node.

**Comment by Dan1ve** [comment]
@dylan-conway  Sorry, my bad, I over-minimized the example. I updated the sample code. Now it works in the browser  (e.g. in Chrome's console), but not with Bun.
My Node version is v20.10.0.

**Comment by Dan1ve** [comment]
I've also learned that there are similar cases like `new URL('/', window.location.href)` that probably also don't work in Bun, but they do in the browser.

**Comment by Jarred-Sumner** [comment]
`window.location.href` does not exist in Bun or Node

If you can reproduce an example which works in Node but not in Bun, please leave a comment
