### ISSUE TITLE
SegmentationFault with Next.js on macOS

### ISSUE THREAD

**Issue by dev-nullified** [oven-sh/bun#954]
### Version

0.1.6

### Platform

darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Created a new next.js project using `bun create next ./`

Then started the dev server with `bun dev`

### What is the expected behavior?

```
➜  bun-example git:(main) ✗ bun dev
[0.10ms] "node_modules.bun" - 58 modules, 6 packages
[5.00ms] bun!! v0.1.6


  Link: http://localhost:3000


[0.06ms] "node_modules.server.bun" - 50 modules, 6 packages
[58.32ms] Next.js ready! (powered by bun)
[82.18ms] / - 2 transpiled, 4 imports
```

### What do you see instead?

```
➜  bun-example git:(main) ✗ bun dev
[0.72ms] "node_modules.bun" - 58 modules, 6 packages
[11.00ms] bun!! v0.1.6


  Link: http://localhost:3000


[0.59ms] "node_modules.server.bun" - 50 modules, 6 packages

SegmentationFault at 0x0000000000000000


–––– bun meta ––––
Bun v0.1.6 macOS x64 21.5.0
DevCommand: fast_refresh tsconfig bun_bun filesystem_router framework bunjs public_folder bunfig
Elapsed: 2203ms | User: 27ms | Sys: 35ms
RSS: 15.53MB | Peak: 15.53MB | Commit: 73.41MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues

```

### Additional information

Only seems to happen with bun v0.1.6. 

Earlier versions of bun run without error
```➜  bun-example git:(main) ✗ ~/Downloads/bun-darwin-x64/bun dev
[0.10ms] "node_modules.bun" - 58 modules, 6 packages
[5.00ms] bun!! v0.1.5


  Link: http://localhost:3000


[0.06ms] "node_modules.server.bun" - 50 modules, 6 packages
[58.32ms] Next.js ready! (powered by bun)
[82.18ms] / - 2 transpiled, 4 imports

bun v0.1.6 is out. Run bun upgrade to upgrade.
```

Doesn't seem to be related to the version of Next.js as bun 0.15.0 ran Next.js v12.2.3 without issue.

**Comment by xhyrom** [comment]
I don't know if it helps, but upgrade bun.

**Comment by sahharYoucef** [comment]
same issue here , any update on this, happened on 0.1.8v and 0.1.7v

**Comment by liho00** [comment]
same issues here v0.1.8
<img width="697" alt="image" src="https://user-images.githubusercontent.com/77238199/184500420-f79bc8b6-8ec4-42a2-9330-68860a05a933.png">

**Comment by xhyrom** [comment]
Its fixed in canary build

**Comment by jgb-solutions** [comment]
Just tried `bun create next` and it failed. I'm on MacOS Ventura 13.3.1 on a MacBook Air.

https://github.com/oven-sh/bun/assets/8051752/4a152a79-9b20-4d13-9090-61d177d91f25
