### ISSUE TITLE
Dependency version mismatch in Vite 5.2.0+ with Bun installer

### ISSUE THREAD

**Issue by jasperkelder** [oven-sh/bun#9544]
### What steps can reproduce the bug?

When deploying a SvelteKit application on Vercel using Bun as the package manager, upgrading Vite to version 5.2.0 or higher results in a version mismatch error for esbuild. This issue does not occur when using Vite version 5.1.6 or when switching the package manager to npm, suggesting the problem might be specific to how Bun handles dependency resolution or installation with newer versions of Vite.

> Error: Expected "0.20.2" but got "0.19.12"
    at validateBinaryVersion (/vercel/path0/node_modules/vite/node_modules/esbuild/install.js:133:11)
    at /vercel/path0/node_modules/vite/node_modules/esbuild/install.js:286:5

**Comment by mquandalle** [comment]
I'm still facing this issue, is it really fixed?

**Comment by jasperkelder** [comment]
The issue I was facing has been gone after some Vite/Bun updates. I can't confirm though whether it's fixed or I somehow got lucky.

**Comment by mquandalle** [comment]
The issue is now fixed for me too.
