### ISSUE TITLE
EADDRINUSE: Failed to start server. Is port 3000 in use?

### ISSUE THREAD

**Issue by stefanos82** [oven-sh/bun#9560]
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Linux debian 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2 (2024-02-04) x86_64 GNU/Linux

### What steps can reproduce the bug?

Code directly taken from official website works as expected

![image](https://github.com/oven-sh/bun/assets/1777466/b19e9f1d-4f30-4a0d-89d6-af92a4a0152b)

`spawn.tsx` though with

```tsx
import os from 'node:os';

// @ts-ignore
const numCPUs = os.availableParallelism();

for (let i = 0; i < numCPUs; i++) {
    Bun.spawn(['bun', 'src/index.tsx'], {
        stdio: ['inherit', 'inherit', 'inherit'],
        env: { ...process.env },
    });
}
```

produces `EADDRINUSE: Failed to start server. Is port 3000 in use?`.

Is it really a bug or am I doing something wrong here?

### What is the expected behavior?

To see the same output as Elysia.js that works with `spawn`:

![image](https://github.com/oven-sh/bun/assets/1777466/53d4f149-6a25-4603-8da0-22e64d6bce11)

### What do you see instead?

I see this

![image](https://github.com/oven-sh/bun/assets/1777466/19b8ad03-4a66-437d-a783-9cb20021d254)

**Comment by ScribeSavant** [comment]
Can you check the port is already taken by another process `sudo lsof -i :3000` if you see the port already taken or your program just working on background you can kill it with `sudo kill -9 PID`

**Comment by stefanos82** [comment]
> Can you check the port is already taken by another process `sudo lsof -i :3000` if you see the port already taken or your program just working on background you can kill it with `sudo kill -9 PID`

Only `bun` is reported:

![image](https://github.com/oven-sh/bun/assets/1777466/e0a58924-9b50-4bbe-955d-f3e77e615587)

The problem is, without the use of spawn, everything works as expected.

As soon as I execute the aforementioned example, it throws the message `EADDRINUSE: Failed to start server. Is port 3000 in use?` but if I run directly the `src/index.tsx`, it works just fine:

![image](https://github.com/oven-sh/bun/assets/1777466/9985164e-6d5e-463c-84d5-333ffb803994)

**Comment by ScribeSavant** [comment]
You can't run multi server on same port you should use different port for each server like 3000/3001/3002

This is not a bug, this is how TCP works

**Comment by stefanos82** [comment]
I have already tried this; still the same message about port `3000`, even though I replaced it with `3300`; it would still complain about port `3000` for some reason...

Where should I go to change the default port for `Bun.spawn`?

**Comment by ScribeSavant** [comment]
Here is an example 

```typescript
// file: index.ts

const port = parseInt(Bun.argv.slice(2)[0].split("=")[1]);

const server = Bun.serve({
  port: port,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
});

console.log(`Listening on localhost:${server.port}`);
process.once("SIGINT", () => {
  server.stop();
});
process.once("SIGTERM", () => {
  server.stop();
});

```
```typescript
// file: spawn.ts

import os from "node:os";

// @ts-ignore
const numCPUs = os.availableParallelism();

for (let i = 0; i < numCPUs; i++) {
  Bun.spawn(["bun", "./index.ts", `--port=300${i + 1}`], {
    stdio: ["inherit", "inherit", "inherit"],
    env: { ...process.env },
  });
}

```

output

![image](https://github.com/oven-sh/bun/assets/34011883/21eefbc4-3616-4d21-b04b-13e75a8d2041)



## Do not use `--watch` otherwise you will get error after changes

**Comment by stefanos82** [comment]
These are your sub-processes; which one is your main / parent process that gets spawned? It should be the one that starts with port 3000; there's no reason to benchmark each sub-process separately, it cannot be done this way.

See how Elysia accomplishes the working output and compare it with your custom implementation, unless I'm missing something here which confuses me even further...

Here's `node.js`'s example with `Cluster`:

```js
import cluster from 'node:cluster';
import http from 'node:http';
import { availableParallelism } from 'node:os';
import process from 'node:process';

const numCPUs = availableParallelism();

if (cluster.isPrimary) {
  console.log(`Primary ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http.createServer((req, res) => {
    res.writeHead(200);
    res.end('hello world\n');
  }).listen(3000); // Original example is `.listen(8000);`, I replaced it with port 3000

  console.log(`Worker ${process.pid} started`);
}
```

The execution:

![image](https://github.com/oven-sh/bun/assets/1777466/fa9398dd-da76-4f0f-9a2b-5665f07102b5)

The actual `wrk` benchmark:

![image](https://github.com/oven-sh/bun/assets/1777466/c718c3f1-8a4b-48f1-9dcf-9c6eca1c3dbd)

**Comment by stefanos82** [comment]
Thanks to FrameworkBenchmarks I have found the cause of my problem: I should have added `reusePort: true` right after `port: 3000` [1].

[1] https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/TypeScript/bun/src/index.ts#L4-L7
