### ISSUE TITLE
Segmentation fault with drizzle + bun:sqlite after upgrade to 1.0.34

### ISSUE THREAD

**Issue by antlanc7** [oven-sh/bun#9563]
### What version of Bun is running?

1.0.34+f90bb7719

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

On WSL, after upgrade to Bun 1.0.34, segmentation fault at start on a project that's running ok with 1.0.33.
The project is using drizzle-orm to wrap bun:sqlite.
To reproduce, create index.js file with the following content:
```js
import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";

const sqlite = new Database(":memory:");
export const db = drizzle(sqlite);
```
and execute with `bun index.js`

EDIT:
actually it's just the import of drizzle to make it segfault.
```js
import { drizzle } from "drizzle-orm/bun-sqlite";
```

**Comment by Jarred-Sumner** [comment]
Confirming I am able to reproduce. Bun v1.0.35 will ship today
