### ISSUE TITLE
Bun gets segmentation fault while instantiating drizzle orm

### ISSUE THREAD

**Issue by lucassusanto** [oven-sh/bun#9583]
### What version of Bun is running?

1.0.34

### What platform is your computer?

Linux 6.6.10-76060610-generic x86_64 x86_64

### What steps can reproduce the bug?

Steps to reproduce
1. I have package.json file
   ```
   {
     "dependencies": {
       "drizzle-orm": "^0.30.4",
       "mysql2": "^3.9.2"
     }
   }
   ```
2. Also db.ts file
   ```
   import { drizzle } from 'drizzle-orm/mysql2';
   import mysql from 'mysql2/promise';
   
   const connection = await mysql.createConnection({
     host: 'host',
     user: 'user',
     password: 'user',
     database: 'database',
   });
   
   const db = drizzle(connection);
   ```
3. Install dependencies
   ```
   bun install
   ```
5. Run db.ts
   ```
   bun db.ts
   ```
6. Segmentation fault error occurs
   ```
   Segmentation fault (core dumped)
   ```
   

### What is the expected behavior?

Bun should print nothing then exit

### What do you see instead?

Bun prints "Segmentation fault (core dumped)"

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.0.35. Please upgrade
