### ISSUE TITLE
Windows: Bun cli breaks nushell and cmd prompt

### ISSUE THREAD

**Issue by 66Leo66** [oven-sh/bun#9587]
### What version of Bun is running?

1.0.35

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Running `bun` (which prints the help text) breaks following shell prompt on Nushell and CMD.

### What is the expected behavior?

`bun` cli should not break following shell prompts.

### What do you see instead?

On Windows Terminal:
- Using nushell, after running `bun`, nushell accept character input but not Backspace, Enter (nothing happens). Pressing arrow keys does not move the cursur but inserts `[C`, `[D` etc.
- Using cmd, after running `bun`, cmd accepts character. Pressing backspace deletes entire line. Pressing arrow keys inserts `^[[C`, `^[[D` etc. Enter works.
- Using PowerShell, everything seems to work fine after running `bun`

Also reproduces using `conhost`, thereby possibly not a Windows Terminal issue?

Here's a screencast:

https://github.com/oven-sh/bun/assets/33322229/dee1fd75-9c44-4a7b-adb6-e46a406f0567

### Additional information

bun is installed using scoop `versions/bun-canary`.
nushell is installed using scoop as well.

**Comment by Jarred-Sumner** [comment]
This will probably fix it https://github.com/oven-sh/bun/pull/9588

**Comment by Jarred-Sumner** [comment]
Can you run bun upgrade —canary and let us know if you still experience this?

**Comment by 66Leo66** [comment]
Sorry, I'm currently away from my Windows machine, for a few days. Will test asap.

**Comment by mirismaili** [comment]
**I upgraded from <del>`1.0.35-canary.4+ee5fd51e8`</del> to <ins>`1.0.35-canary.23+e808cdb72`</ins> and the issue was resolved.** 🙏

**Comment by 66Leo66** [comment]
I can also confirm the issue is fixed. Thanks!
