### ISSUE TITLE
As of version 1.0.34 installing local packages "file:/path" no longer works.

### ISSUE THREAD

**Issue by devcaeg** [oven-sh/bun#9597]
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Create a TypeScript or JavaScript project and configure the package.json to export the build of this project.

Create another TypeScript or JavaScript project and use as dependency your previously created local project "file:/path-to-other-project".

Run "bun install" and you will get the error "MissingPackageJSON". This worked fine before Bun version 1.0.34.

### What is the expected behavior?

The expected behavior is the same as before version 1.0.34 and is that local repositories could be installed using "file".

**Comment by Jarred-Sumner** [comment]
if you prefix it with `./` does that work? instead of `file:/foo`, `file:./foo`

**Comment by devcaeg** [comment]
I tried `file:./path` but the error continues, I also tried `file:path` but the same error.
