### ISSUE TITLE
Bun shell hangs when reading response as stdin

### ISSUE THREAD

**Issue by cheslip** [oven-sh/bun#9604]
### What version of Bun is running?

1.0.35+940448d6b

Also tested with canary at the time: 1.0.35+39d1287f0

### What platform is your computer?

Linux 6.6.12-linuxkit aarch64 unknown (Docker)

Also tested directly on the VM running Docker (AWS ECS): Linux 4.14.336-253.554.amzn2.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

Running Bun in Docker with an image built with `--platform=linux/amd64`

`test.js`
```
import { $ } from "bun";

const response = new Response("test");

await $`cat < ${response}`;
``` 

`Dockerfile`
```
FROM oven/bun:1.0.35

COPY test.js .
```

Run `bun test.js` in the docker container

### What is the expected behavior?

Process exits after `test` is printed

### What do you see instead?

`test` is printed and then process hangs

**Comment by Jarred-Sumner** [comment]
The code snippet above does not seem to reproduce on Linux x64 or macOS arm64. Is this the exact code snippet where it hung on your machine?

<img width="382" alt="image" src="https://github.com/oven-sh/bun/assets/709451/34e9abeb-e4fa-4295-8870-0ea3a3026118">

<img width="324" alt="image" src="https://github.com/oven-sh/bun/assets/709451/e86852f0-bdfd-4f35-a84d-bcc632036e27">

**Comment by cheslip** [comment]
Yes it's the exact snippet. I can only reproduce when running in a docker container. On my local machine (m1 mac), I need to build the image with `--platform=linux/amd64`.

![CleanShot 2024-03-24 at 18 13 23@2x](https://github.com/oven-sh/bun/assets/1493003/cacca9f4-83d7-49f6-9434-259f7e28f260)


I noticed this when trying to migrate to Bun in production, which is running on AWS ECS on an amazon linux2 machine (Linux 4.14.336-253.554.amzn2.x86_64)

**Comment by cheslip** [comment]
Looks like it started with Bun 1.0.31. The process exits as expected with 1.0.30

**Comment by Jarred-Sumner** [comment]
> Linux 4.14.336-253.554.amzn2.x86_64 x86_64 x86_64

I suspect this is why. We aim to support Linux Kernel > 5.1 or so (current is v6.8.1). Usually it's easy to add a polyfill for older Linux kernels though. The tricky part is finding what part is unsupported. If you can provide an `strace` or `perf trace` that would be very helpful. It likely is returning `ENOSYS` somewhere. 

If I were to guess, I'd say it's our use of `wait4` instead of `wait3` or `waitid` but it's hard to say without seeing the system calls from strace/perf trace

**Comment by cheslip** [comment]
Yeah I just upgraded to Amazon Linux 2023 (ver 6.1) which resolved the issue for me. Should this be closed if the issue is only with unsupported kernel versions?

**Comment by Jarred-Sumner** [comment]
Closing for now, but if someone else runs into this please leave a comment and we'll re-open
