### ISSUE TITLE
HTMLRewriter: `element.getAttribute()` returns `null` instead of `""`

### ISSUE THREAD

**Issue by georgpukk** [oven-sh/bun#9605]
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```javascript
new HTMLRewriter()
	.on('p', {
		element(element) {
			let fromGetAttribute, fromIterator

			for (const [name, value] of element.attributes) {
				fromGetAttribute = element.getAttribute(name)
				fromIterator = value
			}

			console.log({ fromGetAttribute, fromIterator })
		}
	})
	.transform('<p data-test></p>')
```

### What is the expected behavior?

```javascript
{
  fromGetAttribute: "",
  fromIterator: ""
}
```

### What do you see instead?

```javascript
{
  fromGetAttribute: null,
  fromIterator: ""
}
```

**Comment by Jarred-Sumner** [comment]
Based on this code in Cloudflare Workers, I believe this behavior is consistent:

https://github.com/cloudflare/workerd/blob/39c0d91e3c2bac5cb05b63fe538cd84b6c6578f3/src/workerd/api/html-rewriter.c%2B%2B#L663-L680


```c++
kj::Maybe<kj::String> Element::getAttribute(kj::String name) {
  // NOTE: lol_html_element_get_attribute() returns NULL for both nonexistent attributes and for
  //   errors, so we can't use check() here.
  LolString attr(lol_html_element_get_attribute(
      &checkToken(impl).element, name.cStr(), name.size()));
    // TODO(perf): We could construct a v8::String directly here, saving a copy.
  kj::Maybe kjAttr = attr.asKjString();
  if (kjAttr != kj::none) {
    return kj::mv(kjAttr);
  }

  KJ_IF_SOME(exception, tryGetLastError()) {
    kj::throwFatalException(kj::mv(exception));
  }

  // No error, just doesn't exist.
  return kj::none;
}
```

**Comment by georgpukk** [comment]
Based on [workers.cloudflare.com/playground](https://workers.cloudflare.com/playground) the current behaviour is not consistent.
Also it just doesn't make sense for `getAttribute()` to return `null` both when the attribute doesn't exist AND when it exists but it has no value or the value is `""`.
And on top of that be inconsistent with what the iterator returns.
