### ISSUE TITLE
https.get() ignores option rejectUnauthorized: false

### ISSUE THREAD

**Issue by alxivnov** [oven-sh/bun#9615]
### What version of Bun is running?

1.0.35

### What platform is your computer?

Linux 6.6.16-linuxkit aarch64 unknown. In Docker 4.28.0 on macOS 14.4

### What steps can reproduce the bug?

Just sending a request to a server with a self-signed or expired certificate with `rejectUnauthorized = false` and it fails, while it should not (here are the docs: https://nodejs.org/api/tls.html#tlsconnectoptions-callback).

```js
	const https = require('https');
	let url = 'https://self-signed.badssl.com';
	// let url = 'https://expired.badssl.com';
	https.get(url, {
		agent: new https.Agent({
			rejectUnauthorized: false
		}),
		rejectUnauthorized: false
	}, (res) => {
		console.log(url, process.version, process.versions.bun, res.statusCode);
	}).on('error', (err) => {
		console.log(url, process.version, process.versions.bun, err);
	});
```

### What is the expected behavior?

I expect request to https://self-signed.badssl.com and https://expired.badssl.com not to fail, like in Node (look at Terminal):

<img width="769" alt="Снимок экрана 2024-03-25 в 17 54 30" src="https://github.com/oven-sh/bun/assets/19705653/94a8209b-4c55-4543-9e55-7ea7165a1c82">

### What do you see instead?

I have an error in Bun while sending request to https://self-signed.badssl.com and https://expired.badssl.com (look at Terminal):

<img width="894" alt="Снимок экрана 2024-03-25 в 17 54 38" src="https://github.com/oven-sh/bun/assets/19705653/c2fb27dc-0e54-4914-bca4-cc2e280ca9e8">

**Comment by jelhub** [comment]
Try using the key **tls**:
```
tls: { 
  rejectUnauthorized: false
}
```

```
const https = require('https');
let url = 'https://self-signed.badssl.com';
// let url = 'https://expired.badssl.com';
https.get(url, {
  tls: { 
    rejectUnauthorized: false
  }
}, (res) => {
	console.log(url, process.version, process.versions.bun, res.statusCode);
}).on('error', (err) => {
	console.log(url, process.version, process.versions.bun, err);
});
```

**Comment by alxivnov** [comment]
> Try using the key **tls**:
> 
> ```
> tls: { 
>   rejectUnauthorized: false
> }
> ```
> 
>  ```
> const https = require('https');
> let url = 'https://self-signed.badssl.com';
> // let url = 'https://expired.badssl.com';
> https.get(url, {
>   tls: { 
>     rejectUnauthorized: false
>   }
> }, (res) => {
> 	console.log(url, process.version, process.versions.bun, res.statusCode);
> }).on('error', (err) => {
> 	console.log(url, process.version, process.versions.bun, err);
> });
> ```

The problem still persists with Axios+Bun:
```js
const https = require('https');
let url = 'https://self-signed.badssl.com';
// let url = 'https://expired.badssl.com';

const axios = require('axios');
let client = axios.create({
	httpsAgent: new https.Agent({
		rejectUnauthorized: false,
		tls: {
			rejectUnauthorized: false
		}
	}),
	rejectUnauthorized: false,
	tls: {
		rejectUnauthorized: false
	}
});
client.get(url)
	.then((res) => {
		console.log(url, process.version, process.versions.bun, res.status);
	})
	.catch((err) => {
		console.error(url, process.version, process.versions.bun, err.message);
	});
```
<img width="641" alt="Снимок экрана 2024-04-20 в 16 49 21" src="https://github.com/oven-sh/bun/assets/19705653/d5a90795-4931-4f3c-aa45-f2c51e9b85e1">
