### ISSUE TITLE
Bun prints in console [maybe the full] source code of a bundled JS app on `console.error(error)` of caught exceptions (WHY?), while `node`, `ts-node` & `tsx` work OK as expected (don't print it)

### ISSUE THREAD

**Issue by supfiger** [oven-sh/bun#9629]
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 6.5.0-1016-gcp x86_64 unknown

### What steps can reproduce the bug?

Below are the repro steps.

**But first, an important thing:**
I import an external package (e.g. `react`). It could be any other.
Of course the problem reproduces without large source code (your own or external libraries, like `react`).
But, to explicit reproduce the problem and see it exactly, for clarity, we need a relatively large codebase. The easiest and shortest way - import some package.

**Reproducing:**

1. Go to [https://replit.com/@supfiger/Bun-issue](https://replit.com/@supfiger/Bun-issue).
2. "Fork & run" it.
3. In terminal run:
    1. `bun run build`
    2. `bun start:bun` // THE ISSUE HERE. You will see the verbose output of the source code of the app
    3. `bun start:tsx` or `bun start:node` or `bun start:ts-node` // All of them work ok as expected

### What is the expected behavior?

It should print in console only the error data, NOT an application source code.

### What do you see instead?

Source code of an app in console.

### Additional information

- The same behavior not only in [replit.com](replit.com), but in a local computer as well.
- The same behavior not only with `console.error()`, but with `console.log()` and maybe with other methods too.

**Comment by Jarred-Sumner** [comment]
This was fixed in Bun v1.1.1 (#9832)
