### ISSUE TITLE
`Headers` issues with bun-types|undici-type|@types/node

### ISSUE THREAD

**Issue by bjon** [oven-sh/bun#9634]
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Create new project: `bun init -y`
2. Replace index.ts with:
```typescript
  // this 'Headers' come from /node_modules/undici-types
  const headers = new Headers();
  // headers.toJSON(); doesn't work here

  modHeaders(headers);

  // this 'Headers' come from /node_modules/@types/node
  function modHeaders(headers: Headers) {
    // headers.toJSON(); works here
    headers.set('X-Hello', 'World');
  }
```
3. Run: `bunx tsc`

### What is the expected behavior?

Should compile (tsc)

### What do you see instead?

```
index.ts:5:12 - error TS2345: Argument of type 'import("/tmp/bun/node_modules/undici-types/fetch").Headers' is not assignable to parameter of type 'Headers'.
  Type 'Headers' is missing the following properties from type 'Headers': toJSON, count, getAll

5 modHeaders(headers);
             ~~~~~~~


Found 1 error in index.ts:5
```

### Additional information

Also fails in VSCode.

![image](https://github.com/oven-sh/bun/assets/280413/70eebb3e-d5ae-4ffb-971b-50284c99a1c7)

**Comment by bjon** [comment]
URL has the same problem:

```typescript
const url = new URL('http://example.com');
handleUrl(url);
function handleUrl(url: URL) {
  // ...
}
```

`bunx tsc`

```
index.ts:15:11 - error TS2345: Argument of type 'import("url").URL' is not assignable to parameter of type 'URL'.
  Type 'URL' is missing the following properties from type 'URL': createObjectURL, revokeObjectURL, canParse

15 handleUrl(url);
             ~~~
```

**Comment by binyamin** [comment]
The original issue is a duplicate of #8081

**Comment by dertieran** [comment]
For me this was fixed by adding `DOM` to `compilerOptions.lib` in the `tsconfig.json`.
It seems this was also changed in the `tsconfig.json` generated by `bun init` here [`7111318`](https://github.com/oven-sh/bun/commit/71113182c2a5228b447b836ad4b7bf705ad7e06d).

**Comment by bjon** [comment]
@dertieran thanks!
