### ISSUE TITLE
Load `.env.local` and `.env.test.local` in `bun test`

### ISSUE THREAD

**Issue by april83c** [oven-sh/bun#9641]
### What is the problem this feature would solve?

Re: https://github.com/oven-sh/bun/issues/5230#issuecomment-2021190982

Currently, `.env.local` and `.env.test.local` are not loaded when running `bun test`, meaning those environment variables aren't available during tests, but they are when actually running the project.

Besides, being able to have a `.local` version of `.env.test` would be really helpful by itself and wouldn't break anything, even if it's decided to not load `.env.local` because it could break existing tests.

### What is the feature you are proposing to solve the problem?

`bun test` should load `.env.local` and `.env.test.local`

**Comment by paperclover** [comment]
<img width="734" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/9b41fdef-86fc-4885-bfa3-2c1e6b494153">

there is already code for this. and my pr was linked to this issue as fixing it, but this code has existed for a long time and i had made no logic changes.

**Comment by paperclover** [comment]
this feature is already implemented in bun, so the above seems to be a bug, which may be the bug the pr fixes which [i explain in detail here](https://github.com/oven-sh/bun/issues/9635#issuecomment-2021350123).

<img width="511" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/2a058f20-a555-40d6-9f92-79faec2003ad">

After this PR merges, try upgrading to canary using `bun upgrade --canary`, and if the issue still arises, can you try to create a minimal reproduction that causes it.

**Comment by adhusson** [comment]
using `1.1.5+b257a3097`

<img width="383" alt="image" src="https://github.com/oven-sh/bun/assets/2977/9ad4e17e-d8eb-484e-a163-7b26db7b94f2">

**Comment by zulrang** [comment]
The problem is the `.env.local` isn't loaded during tests, but is always loaded any other time.

```
~/buntest$ bun --version
1.1.8
~/buntest$ echo 'k=v' > .env.local
~/buntest$ echo "console.log(process.env.k)" > index.test.js
~/buntest$ bun test
bun test v1.1.8 (89d25807)

index.test.js:
undefined

 0 pass
 0 fail
Ran 0 tests across 1 files. [8.00ms]
~/buntest$ mv .env.local .env
~/buntest$ bun test
bun test v1.1.8 (89d25807)

index.test.js:
v

 0 pass
 0 fail
Ran 0 tests across 1 files. [7.00ms]
```

**Comment by april83c** [comment]
Yep. `.env.local` is still not loaded for me during tests, which was the point of this issue

**Comment by debrisapron** [comment]
Still broken as of v1.1.17
