### ISSUE TITLE
Bun binary creates a dot folder in the home dir by default

### ISSUE THREAD

**Issue by lgarron** [oven-sh/bun#965]
### Version

Current install

### Platform

macOS

### What steps will reproduce the bug?

The install command on the website: `curl https://bun.sh/install | bash`

### How often does it reproduce? Is there a required condition?

Consistently.

### What is the expected behavior?

I don't end up with a new dot folder in my home dir.

### What do you see instead?

```
bun was installed successfully to ~/.bun/bin/bun 

Added "~/.bun/bin" to $PATH in "~/.config/fish/config.fish" 
```

### Additional information

When I try out a new program and it insists on creating a new dot file or dot directory in my home folder, it's an immediate red flag for me. 😕 In this case, I wanted to try out `bun`, but uninstalled it immediately. I understand that I can move the folder, but I'd be concerned that this would break e.g. auto-updates in the future. I thought I'd file an issue rather than ignoring it.

I'd appreciate if `bun` used a an alternative like:
- Following the XDG conventions https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and using `$HOME/.local/bin`, or at least `$XDG_DATA_HOME`.
- Supporting and recommending Homebrew for installation on macOS, so that no special directory handling is necessary: #272

**Comment by Jarred-Sumner** [comment]
Bun creates a dot folder for caching with bun install and for global bins with bun install

**Comment by lgarron** [comment]
> Bun creates a dot folder for caching with bun install and for global bins with bun install

Apologies, maybe I should have been more clear — I'm asking for for `bun` *not* to do this, and to use other conventions instead. Shall I take your response as a wontfix / should I file more specific requests? Thanks!

EDIT: looks like https://github.com/oven-sh/bun/issues/696 covers the cache dir case. The question still remains for `~/.bun/bin` as created by the `bun` installer script.

**Comment by s373r** [comment]
For future readers -- to install to a different directory that is convenient for you (e.g., `~/.local/share/bun`), you can use the following command:

```shell
curl -fsSL https://bun.sh/install | BUN_INSTALL="${HOME}/.local/share/bun" bash
```
