### ISSUE TITLE
Implement happy eyeballs for sockets and fetch

### ISSUE THREAD

**Issue by cirospaciari** [oven-sh/bun#9658]
### What is the problem this feature would solve?

auto fallback to ipv4 if ipv6 is not available
related:
https://github.com/oven-sh/bun/issues/7260
https://github.com/oven-sh/bun/issues/4066

### What is the feature you are proposing to solve the problem?

https://en.wikipedia.org/wiki/Happy_Eyeballs
https://www.rfc-editor.org/rfc/rfc8305.txt

curl implements it and nodejs too using `autoSelectFamily` with is true by default since v20 see https://nodejs.org/api/net.html#socketconnectoptions-connectlistener

**Comment by Electroid** [comment]
Fixed in #11206
