### ISSUE TITLE
React typescript 

### ISSUE THREAD

**Issue by DanielVain** [oven-sh/bun#967]
Can it be possible to add an install option for React with TypeScript as a default language?

It's kind of a nuisance to change all of the JSX files to TSX every time i open a new project.

**Comment by xhyrom** [comment]
You can create local template for now

**Comment by DanielVain** [comment]
Wouldn't be easier and faster to install it with bun every time?

**Comment by pepper-lees** [comment]
@DanielVain The readme says PRs with new template/examples are welcome. Create a fork, add a React with TypeScript template, and submit a PR and reference this issue #. 🙂

**Comment by DanielVain** [comment]
> @DanielVain The readme says PRs with new template/examples are welcome. Create a fork, add a React with TypeScript template, and submit a PR and reference this issue #. 🙂 

Only if i knew how to do that..

**Comment by UltiRequiem** [comment]
> > @DanielVain The readme says PRs with new template/examples are welcome. Create a fork, add a React with TypeScript template, and submit a PR and reference this issue #. slightly_smiling_face
> 
> Only if i knew how to do that..

here are some examples prs
https://github.com/oven-sh/bun/pulls?q=is%3Apr+template+
