### ISSUE TITLE
[windows] Bun build and minify with input for non text files causes error

### ISSUE THREAD

**Issue by RiskyMH** [oven-sh/bun#9671]
### What version of Bun is running?

1.0.35-canary.35+dea877f19

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. get random binary file
2. make index.ts with `import file from "./thefile.file"; console.log(file)`
3. `bun build index.ts --outdir=dist --minify-identifiers` (you can also just use normal minify)

### What is the expected behavior?

it to copy the file into the out dir and be fine

### What do you see instead?

`uh-oh: index out of bounds`

**Comment by Electroid** [comment]
Duplicate of #10026
