### ISSUE TITLE
winston's exceptionHandlers won't output the error to log files

### ISSUE THREAD

**Issue by dunadain** [oven-sh/bun#9678]
### What version of Bun is running?

1.0.35

### What platform is your computer?

mac intel 64

### What steps can reproduce the bug?

[bugrepo.zip](https://github.com/oven-sh/bun/files/14787367/bugrepo.zip)
here's the repo project.

bun index.ts

### What is the expected behavior?

1. when exceptionHandlers are enabled, uncaught exceptions should be output the error.log file and error shouldn't be output to the console.
2. when transports.Console's handleException is set to true, errors should also be output to the console

### What do you see instead?

uncaught exceptions won't be logged
transports.Console's handleException setting has no effect

**Comment by Electroid** [comment]
Duplicate of #429
