### ISSUE TITLE
when sending large chunks into a tcp socket at once, only the first ~128kb are sent

### ISSUE THREAD

**Issue by sayalovesu** [oven-sh/bun#9682]
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```js
const crypto = require('crypto')

let total = 0
Bun.connect({
    hostname: 'tcpbin.com',
    port: 4242,
    socket: {
        open: (socket) => {
            for (let i = 0; i < 3; i++) {
                const data = crypto.randomBytes(131240)
                console.log('sending: ', data.slice(0, 100).toString('hex'))
                socket.write(data)
            }
            console.log('sent total %d bytes', 131240 * 3)
        },
        data: (sock, data) => {
            total += data.length
            console.log('received total %d bytes', total)
        },
    },
})
```
`console.log`-s stop firing after first ~128kb, and looking in the wireshark, it can be observed that the subsequent chunks aren't sent at all. 
if i reduce chunk size, it stalls around 128kb anyway
`.flush()` or `process.nextTick()` don't help, the only thing that kinda does is waiting for a few hundred ms between `.write()` calls

### What is the expected behavior?

all the chunks get sent correctly

### What do you see instead?

only the first one is sent

**Comment by Jarred-Sumner** [comment]
While confusing and different from Node, this is working as intended. The docs do state this but need to be made clearer.

`socket.write` returns the number of bytes written. That number may be less than the number of bytes passed. 

Unlike Node, Bun does not buffer unsent bytes and leaves you to handle backpressure in the `drain` callback. Think of write as saying "send as much of this as you can right now" and it replies with "here's how much I sent". This does not mean it will make any attempt to send the rest of the data itself. 

To make this easier, you can use ArrayBufferSink to handle buffering text or binary data and write that to it. 

You can also use node:net if you prefer the buffering behavior of Node
