### ISSUE TITLE
windows : chalk, sveltkkit-superform

### ISSUE THREAD

**Issue by zhihengGet** [oven-sh/bun#9683]
### What version of Bun is running?

windows

### What steps can reproduce the bug?

bun install v1.0.35-canary.35 (dea877f1)
  ⚙️  leveldown [1/4] error: ENOENT installing chalk
error: ENOENT installing sveltekit-superforms

### What is the expected behavior?

able to install

### What do you see instead?

able to install

### Additional information

able to install

**Comment by Electroid** [comment]
Could you share your `package.json`?

**Comment by zhihengGet** [comment]
nvm ! it started working now for some reason :)
