### ISSUE TITLE
I can't run bun run dev or anything with bun

### ISSUE THREAD

**Issue by Popa24** [oven-sh/bun#9688]
### What version of Bun is running?

1.0.35-canary.35+dea877f19

### What platform is your computer?

the command it does not work

### What steps can reproduce the bug?

install bun then create a project using the bun command say Yes to everything and then run "bun run dev"

### What is the expected behavior?

to run the development page

### What do you see instead?

PS D:\webproject> bun run dev  
$ next dev

uh-oh: integer cast truncated bits
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.35-canary.35 (dea877f1) Windows x64
RunCommand: dotenv
Elapsed: 7ms | User: 0ms | Sys: 0ms
RSS: 24.18MB | Peak: 24.18MB | Commit: 68.45MB | Faults: 6048
----- bun meta -----

0   00007FF7594B73D8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 22572 panic: integer cast truncated bits
???:?:?: 0x7ff758113733 in ??? (bun.exe)
???:?:?: 0x7ff75811662d in ??? (bun.exe)
???:?:?: 0x7ff758117ae6 in ??? (bun.exe)
???:?:?: 0x7ff75812b004 in ??? (bun.exe)
???:?:?: 0x7ff757e616c6 in ??? (bun.exe)
???:?:?: 0x7ff75a96e103 in ??? (bun.exe)
???:?:?: 0x7ffaa4b0257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffaa62caa57 in ??? (ntdll.dll)

**Comment by hiepgia** [comment]
Seem related to #9481 which caused by empty env variable?

**Comment by Popa24** [comment]
YES!!! this was it, thanks
