### ISSUE TITLE
No doc on how to install bun on Termux 

### ISSUE THREAD

**Issue by habibthadev** [oven-sh/bun#9709]
### What is the type of issue?

Documentation is missing

### What is the issue?

There is no actual documentation on how to install bunjs on termux terminal, I've tried several sources like using proot-distro to install debian, all to no avail.

Please, kindly do so in you next docs update.

### Where did you find it?

There's no actual url because the doc doesn't even exist

**Comment by paperclover** [comment]
Bun does not support Termux as of now. Duplicate of #5085
