### ISSUE TITLE
Piping from `/dev/null` stdin on windows fails with `EBADF`

### ISSUE THREAD

**Issue by gvilums** [oven-sh/bun#9719]
### What version of Bun is running?

1.0.36-debug+3047c9005

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

In `cmd.exe`, run `bun-debug -e "process.stdin.pipe(process.stdout)" < nul`

### What is the expected behavior?

Nothing happens 

### What do you see instead?

```
1 | process.stdin.pipe(process.stdout)
                        ^
EBADF: Bad file descriptor
   errno: -9
 syscall: "open"

      at lazyLoadStream (:1:21)
      at getReader (:1:21)
      at ref (:35:29)
      at node:stream:2291:73
      at node:stream:2747:77
      at C:\bun\[eval]:1:1
```

**Comment by Jarred-Sumner** [comment]
This was fixed
