### ISSUE TITLE
Bun Serve (with SSL) wrongly returns 206 Partial-Content when sending Blobs

### ISSUE THREAD

**Issue by dl-eric** [oven-sh/bun#9755]
### What version of Bun is running?

1.0.36+40f61ebb9

### What platform is your computer?

Linux 4.19.128-microsoft-standard x86_64 x86_64

### What steps can reproduce the bug?

1. Spin up an SSL-enabled Bun Server
2. Have the server respond e.g a Bun.file

server.ts
```
Bun.serve(
{
  async fetch(request) {
    return new Response(Bun.file("foo.bar"));
  },
  tls: {
    cert: "cert here",
    key: "key here"
  }
});
```

Observe the response will always be 206 Partial Content.

### What is the expected behavior?

The Bun server should only respond with a 206 if the client adds a `Range` header, meaning it wants and is willing to accept partial content. Reference: https://www.rfc-editor.org/rfc/rfc7233#section-4.1. I think higher level frameworks like ElysiaJS fixes this, but I feel like this is worth filing for the backlog.

Also, Content-Range doesn't specify the total length of a file. I see this is a deliberate decision[1] but I think we should consider making this behavior (1) documented and (2) configurable. I can imagine scenarios where developers would want to not hide the full content-length - perhaps an HTML video player expects it to optimize their buffering logic.

[1]
```
resp.writeHeader(
    "content-range",
    std.fmt.bufPrint(
        &content_range_buf,
        // we omit the full size of the Blob because it could
        // change between requests and this potentially leaks
        // PII undesirably
        "bytes {d}-{d}/*",
        .{ this.sendfile.offset, this.sendfile.offset + (this.sendfile.remain -| 1) },
    ) catch "bytes */*",
);
```

### What do you see instead?

206 for every Blob response.

**Comment by dl-eric** [comment]
Probably low priority. Frameworks like ElysiaJS fixes this issue on their stack.

**Comment by Jarred-Sumner** [comment]
Fixed in:
- https://github.com/oven-sh/bun/pull/12979
- https://github.com/oven-sh/bun/pull/12978
