### ISSUE TITLE
Too many comma-delimited expressions crashes transpiler

### ISSUE THREAD

**Issue by soitchu** [oven-sh/bun#9756]
### What version of Bun is running?

1.0.36+4bbcc39d2

### What platform is your computer?

Linux 6.7.2-arch1-1-surface x86_64 unknown

### What steps can reproduce the bug?

`bun install binaryen`

Put the following in index.ts:
```
import binaryen from "binaryen";
console.log(binaryen);
```

Then run: `bun build index.ts --compile --outfile out`

### What is the expected behavior?

It should output an executable

### What do you see instead?

Segmentation fault (core dumped)

### Additional information

This seems to be because binaryen has thousands of expressions chained together using commas:
```
(A._BinaryenTypeNone = () => (A._BinaryenTypeNone = Q.Ja)()),
(A._BinaryenTypeInt32 = () => (A._BinaryenTypeInt32 = Q.
(A._BinaryenTypeInt64 = () => (A._BinaryenTypeInt64 = Q.La)()),
(A._BinaryenTypeFloat32 = () => (A._BinaryenTypeFloat32 = Q.Ma)()),
(A._BinaryenTypeFloat64 = () => (A._BinaryenTypeFloat64 = Q.Na)()),
.
.
.
 ```
 
 This is what seems to cause the segfault. If I change one of those commas to a semicolon, it builds without any issues. I have a minimal reproducible example here: https://github.com/soitchu/bun-build-segfault/blob/master/mini-repro.js

**Comment by soitchu** [comment]
Fixed by https://github.com/oven-sh/bun/pull/12384 in [1.1.19](https://bun.sh/blog/bun-v1.1.19#improved-comma-expression-folding).

**Comment by Jarred-Sumner** [comment]
Great
