### ISSUE TITLE
Response.redirect(url, status) ignores status

### ISSUE THREAD

**Issue by sstur** [oven-sh/bun#976]
### Version

0.1.6

### Platform

Darwin tampa.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

Run the following code:
```ts
const response = Response.redirect('/foo', 301);

console.log(response.status);
```

Notice the output is 302 when it should be 301. Actually the output will be 302 regardless of what you pass in for the second parameter.

If you run that in Safari or Chrome, you'll get the expected output, but in Bun it's always 302.

### How often does it reproduce? Is there a required condition?

Very simple repro; no required conditions.

### What is the expected behavior?

Expected the response.status to be the same as we put in, in the example above `301`

### What do you see instead?

`302`

**Comment by zhuzilin** [comment]
It's an expected behavior that a redirect response will have status code 302.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

**Comment by sstur** [comment]
No, it's expected behavior ([mdn](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect)) that a redirect response will have a status code that is _one of_ the following: `301, 302, 303, 307, 308` and it should _default_ to `302`.

The second parameter to Response.redirect() should be one of the above status codes ([spec](https://fetch.spec.whatwg.org/#redirect-status)), and the resulting response should honor that choice.

Here's the relevant part from [the spec](https://fetch.spec.whatwg.org/#dom-response-redirect):

<img width="790" alt="image" src="https://user-images.githubusercontent.com/369384/182902644-f522d497-d559-48ff-83ad-1885d0023ab6.png">

**Comment by zhuzilin** [comment]
Sorry i didn't read the spec carefully enough... The pr should fix this issue, though the RangeError is not raised yet, just like TypeError for url parsing.

**Comment by sstur** [comment]
Wow, thanks for tackling this and putting up a PR! I don't know enough about Zig to know by looking at that PR if it solves the problem but it seems right. One suggestion might be to add a regression test, that might help the reviewer have more confidence that it is handling the status codes correctly.

Anyway, thanks for your help with this!

**Comment by sstur** [comment]
Oh, and you're right about the Zig implementation not being spec-compliant in terms of throwing the right errors, there are at least a few other ways I've noticed that Bun's implementation of Request/Response don't perfectly follow spec, but I figured I'll raise those another time (or figure out how to contribute to the Zig code). Thanks again!
