### ISSUE TITLE
bun installation panic after installing eslint in monorepo

### ISSUE THREAD

**Issue by kaungmyatthu69** [oven-sh/bun#9790]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun install

### What is the expected behavior?

no issue

### What do you see instead?

thread 21300 panic: workspace windows separator: packages\eslint-config

???:?:?: 0x7ff6ea9ee11e in ??? (bun.exe)
???:?:?: 0x7ff6ea7ea5a8 in ??? (bun.exe)
???:?:?: 0x7ff6ea7ec197 in ??? (bun.exe)
???:?:?: 0x7ff6ea6118c9 in ??? (bun.exe)
???:?:?: 0x7ff6ea648f3c in ??? (bun.exe)
???:?:?: 0x7ff6ea642610 in ??? (bun.exe)
???:?:?: 0x7ff6ea6f54c2 in ??? (bun.exe)
???:?:?: 0x7ff6ea421603 in ??? (bun.exe)
???:?:?: 0x7ff6ecf57e33 in ??? (bun.exe)
???:?:?: 0x7ff8d6d0257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff8d80aaa57 in ??? (ntdll.dll)

### Additional information

https://github.com/myanmarcyberyouths/breeze-web.git

**Comment by dylan-conway** [comment]
Can you try this with v1.1.4? I believe this was fixed in 1.1.2 or 1.1.3
