### ISSUE TITLE
running bunx create-next-app uses NPM to install the dependencies instead of Bun

### ISSUE THREAD

**Issue by Amir-Adel9** [oven-sh/bun#9791]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Initialize a new [Next.js](https://nextjs.org/) project via the `bunx create-next-app` command

### What is the expected behavior?

The project's dependencies should get installed via Bun

### What do you see instead?

Instead, it automatically proceeds to use NPM for installing the dependencies 

![image](https://github.com/oven-sh/bun/assets/107762758/8419964e-24f4-4209-917e-4cc4159ff24c)

**Comment by cosigyn** [comment]
You can force it with `--use-bun` while waiting for a fix

**Comment by abhishekpatelmc** [comment]
I encountered same error, is there an alternative command to make it work ?

**Comment by Davut-Atajanov** [comment]
same error here guys

**Comment by Jarred-Sumner** [comment]
This is fixed in Bun v1.1.14, thanks to @SunsetTechuila
