### ISSUE TITLE
Erorr bun after of install in windows

### ISSUE THREAD

**Issue by joansebgarcia** [oven-sh/bun#9797]
### What version of Bun is running?

bun v1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. First execute the command `npm install -g bun`
2. Run `bun --version`
3. Logs error

```sh
➜ dev  bun --version
C:\Users\johan\.npm-global\node_modules\bun\bin\bun:1
MZx

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
```

### What is the expected behavior?

![image](https://github.com/oven-sh/bun/assets/116913262/98c5cb47-aca5-4921-816a-0b600963aba8)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/116913262/50ff71a6-6a74-41c0-8b1e-16fd6fb28fb3)

### Additional information

Thank for reading

**Comment by VietnamecDevelopment** [comment]
Same here

**Comment by Bader-Idris** [comment]
the issue is that Bun didn't get added to the Windows environment variables, do it manually until they change it, the default path is

```sh
%USERNAME%\.bun\bin\bun.exe
```

**Comment by Bader-Idris** [comment]
it turned out that in windows to run the app, you should use bun.exe, until they fix it!🙂

as

```
bun.exe -e "console.log('hi mom')"
```

**Comment by gvilums** [comment]
Related: #9783

**Comment by artulance** [comment]
> the issue is that Bun didn't get added to the Windows environment variables, do it manually until they change it, the default path is
> 
> ```shell
> %USERNAME%\.bun\bin\bun.exe
> ```
But if I use the command `npm install -g bun` it does not create the .bun folder in the user folder (at least for me). In my case (I use laragon) it puts the files in the path  C:\laragon\bin\nodejs\node-v18.17.1-win-x64\node_modules\bun\bin.

**Comment by Garruxx** [comment]
If you go to bun's official website in the [installation section](https://bun.sh/docs/installation) you will see that to install bun on windows you are instructed to use 
``` powershell -c "irm bun.sh/install.ps1|iex" ```

npm is available for Linux and MacOS, but as you will see it is not available for Windows, so the only installation option we have on windows at the moment is PowerShell. 

### This is not a bug, it is just not implemented.
![image](https://github.com/oven-sh/bun/assets/109706264/d6109d72-9cc6-44fb-b50d-6b760749b36d)

**Comment by paperclover** [comment]
Duplicate of #9783

**Comment by artulance** [comment]
> If you go to bun's official website in the [installation section](https://bun.sh/docs/installation) you will see that to install bun on windows you are instructed to use `powershell -c "irm bun.sh/install.ps1|iex"`
> 
> npm is available for Linux and MacOS, but as you will see it is not available for Windows, so the only installation option we have on windows at the moment is PowerShell.
> 
> ### This is not a bug, it is just not implemented.
> ![image](https://private-user-images.githubusercontent.com/109706264/318863509-d6109d72-9cc6-44fb-b50d-6b760749b36d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjY1NDgsIm5iZiI6MTcxMjEyNjI0OCwicGF0aCI6Ii8xMDk3MDYyNjQvMzE4ODYzNTA5LWQ2MTA5ZDcyLTljYzYtNDRmYi1iNTBkLTZiNzYwNzQ5YjM2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwNjM3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTdiNzU3NGE0MzBjM2U5NzIwZThhZDI4MTE5NTliYzA3NTEyZmVjZTNkZGE2Mjc1YWZlNGU5YzFiOTRjNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ma3dj1EW8bmIEGbZ8t_1-GH14eNEmg8doF_LafXW6c4)

Hi, thanks for your answer, the npm option is provided by the official bun account itself https://x.com/bunjavascript/status/1774966012745814120?s=20
For those of us with security-restricted equipment, using npm was the best option.

**Comment by juliomuhlbauer** [comment]
same
