### ISSUE TITLE
crash on `bun add -D @types/flow-remove-types`

### ISSUE THREAD

**Issue by subtleGradient** [oven-sh/bun#9798]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```
% bun add -D @types/flow-remove-types
[0.03ms] ".env"
bun add v1.1.0 (5903a614)
  🔍 @types/flow-remove-types [1/1] 
error: package "@types/flow-remove-types" not found registry.npmjs.org/@types%2fflow-remove-types 404

error: InstallFailed

----- bun meta -----
Bun v1.1.0 (5903a614) macOS Silicon 23.1.0
AddCommand: dotenv 
Elapsed: 72ms | User: 71ms | Sys: 13ms
RSS: 78.51MB | Peak: 78.51MB | Commit: 100.48MB | Faults: 0
----- bun meta -----

0   0x1054d1a08
1   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

### What is the expected behavior?

I expect it to not show me the `bun meta` stuff

### What do you see instead?

a bunch of `bun meta` stuff that makes it seem like bun crashed

### Additional information

congrats on launching v1.1!!1!
I'm excited to try Bun in production and on windows

**Comment by subtleGradient** [comment]
I am not blocked by this. Reporting the bug in the hopes that it's helpful

**Comment by gvilums** [comment]
Minimal repro:
```
mkdir myapp
cd myapp
bun init -y
bun add -D @types/flow-remove-types
```

**Comment by Jarred-Sumner** [comment]
This is not a crash, though the diagnostics information should not be printed in this case

You can see that the package `@types/flow-remove-types` does not exist on npm: https://www.npmjs.com/package/@types/flow-remove-types this link 404s
