### ISSUE TITLE
HMR can cause an infinite loop during client-side updates

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#98]
still narrowing this one down, only seen on replit so far

**Comment by eastlondoner** [comment]
I think I have seen this or something similar.

My hunch is this happens if I make changes in quick succession such that a new HMR is triggered before the previous one has finished (or finished being processed / applied to the DOM )

**Comment by Jarred-Sumner** [comment]
The bug is a cache invalidation issue related to the watched file entry changing file descriptors due to being deleted

This file has code in it
![image](https://user-images.githubusercontent.com/709451/148049984-aa18bd51-d8c5-48d7-9ca4-52b428ad4e12.png)

**Comment by eastlondoner** [comment]
Cache invalidation 😬😱

**Comment by Jarred-Sumner** [comment]
lol "Possibly fix" closes it

**Comment by Electroid** [comment]
`bun dev` was changed in Bun v1.0, it will now run the "dev" script in your package.json. Because of that, this issue is no longer applicable.
