### ISSUE TITLE
bun.exe instead of bun

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#9800]
### What version of Bun is running?

1.1

### What platform is your computer?

windows 11, build 22000

### What steps can reproduce the bug?

the environment variable is not set after I installed bun using your preferred command, whether it's with PowerShell or npm

so when I type: bun 
it does not understand what's that command, even after restarting powershell
please automate the process

### What is the expected behavior?

please automate the process

### Additional information

the whole issue is that in windows, you made it run as `bun.exe` instead of `bun`

**Comment by gvilums** [comment]
Using the `bun` command should in theory work fine, the `.exe` suffix shouldn't be required. Maybe there's a subtle difference in the shell environment? This needs further investigation

**Comment by gvilums** [comment]
Follow up: What installation method did you use? If you installed with `npm` this might be the same issue as #9783 .

**Comment by Garruxx** [comment]
This is not an error.
[Here is the solucion](https://github.com/oven-sh/bun/issues/9797#issuecomment-2032464955)

**Comment by ghiscoding** [comment]
probably fixed by today's v1.1.1, see https://bun.sh/blog/bun-v1.1.1
