### ISSUE TITLE
Bun crashes PowerShell after terminating a script using Ctrl+C

### ISSUE THREAD

**Issue by DavidZidar** [oven-sh/bun#9801]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I'm using PowerShell 7.4.1 on Windows and am experiencing crashes when I terminate my build script in watch mode by using Ctrl+C, but it turns out it's really simple to reproduce the error.

Using the following script:
*crash.ts*
```typescript
setTimeout(() => { console.log("Too slow!"); }, 10_000);
```

Run it using `bun run .\crash.ts` and then press Ctrl+C before the timeout expires and PowerShell will crash after Bun exits.

### What is the expected behavior?

Ideally PowerShell should not crash just because I choose to use Bun. 😄 

### What do you see instead?

PowerShell crashes with the following stacktrace:
```
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
at System.ConsolePal.ReadKey(Boolean intercept)
at Microsoft.PowerShell.Internal.VirtualTerminal.ReadKey()
at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Additional information

This does not seem to happen when I let Bun run a script to completion, only when I abort using Ctrl+C.

**Comment by DavidZidar** [comment]
I tried to reproduce it in Linux but it seems fine there so I'm guessing it has something to do with how you handle Windows.

**Comment by gvilums** [comment]
Unfortunately I can't reproduce this

**Comment by DavidZidar** [comment]
Hmm, that's strange. I can reproduce it on my main machine even with a blank PowerShell profile `pwsh.exe -NoProfile`. However I just tried on a separate machine and I'm unable to reproduce the issue there so I'm not sure what the difference is.

**Comment by DavidZidar** [comment]
I figured out it only happens to me in Windows Terminal Preview, I have no idea where the problem is, maybe Bun is innocent but I've never seen PowerShell crash like this before.

**Comment by DavidZidar** [comment]
I found that I inadvertently had an old version of PSReadLine (version 2.2.2) lying around in my user profile, when I removed that version so that version 2.3.4 is used instead the problem disappeared. I can only conclude that the problem must be there somewhere and not in Bun so I'm closing this issue. Thanks for the help anyway!

**Comment by adrifer** [comment]
I had same issue, updating PSReadline fixed it :)
