### ISSUE TITLE
Cannot find module 'bun:test' or its corresponding type declarations.ts(2307) ts error

### ISSUE THREAD

**Issue by ViniciusCestarii** [oven-sh/bun#9803]
### What version of Bun is running?

1.1

### What platform is your computer?

windows 11

### What steps can reproduce the bug?

install bun on windows using:
powershell -c "irm bun.sh/install.ps1 | iex"

open a ts file and try to import functions from "bun:test"

### What is the expected behavior?

to be possible to import functions from the package "bun:test"

### What do you see instead?

Cannot find module 'bun:test' or its corresponding type declarations.ts(2307)

### Additional information

![image](https://github.com/oven-sh/bun/assets/124843824/c8ea4dcd-463a-48fb-9408-7d5438a11631)

**Comment by gvilums** [comment]
Have you tried running the code and seeing if it works? This would help distinguish if there's actually a problem in the runtime or if the type declarations are simply wrong/outdated.

**Comment by ViniciusCestarii** [comment]
Hey i runned it and it worked!

the code:

import { expect, test } from "bun:test";

test("2 + 2", () => {
  expect(2 + 2).toBe(4);
});

bun test

bun-test.spec.ts:
✓ 2 + 2 [0.04ms]

 1 pass
 0 fail
 1 expect() calls
Ran 1 tests across 1 files. [26.00ms]

but the ts error still appears

![image](https://github.com/oven-sh/bun/assets/124843824/10be3314-5bdc-4060-8b5a-28cfa16a4677)

**Comment by gvilums** [comment]
Have you tried running `bun init` in the directory with the package.json? This should add bun's type declaration files

**Comment by ViniciusCestarii** [comment]
It worked perfectly! Thanks!

**Comment by sebastianbuechler** [comment]
`bun init` did not work for me, but `bun add bun-types` worked.

**Comment by karlhorky** [comment]
It appears that the new recommendation from [the TypeScript docs page](https://bun.sh/docs/typescript) is to use `@types/bun`:

```bash
bun add -d @types/bun
```

**Comment by karlhorky** [comment]
Similar module resolution problems with `bun:` prefixed modules in the `no-unresolved` rule in [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) or [`eslint-plugin-import-x`](https://github.com/un-ts/eslint-plugin-import-x) can also appear, eg:

```
Unable to resolve path to module 'bun:test'. eslint import-x/no-unresolved
```

I reported this over here too (with workaround):

- https://github.com/un-ts/eslint-plugin-import-x/issues/92

**Comment by ChiefWoods** [comment]
Add this under your compilerOptions under tsconfig.json

`"types": ["bun"],`

**Comment by KrossaNoah** [comment]
You just needs to add global types declaration in `tsconfig.json` file 

```json
{
   "compilerOptions": {
     ...
     "types": [
          "bun-types/globals"
      ],
   ...
 }
}
```

**Comment by mhaqnegahdar** [comment]
Here is what I did:

```shell
bun i -D bun-types
```

then in your `tsconfig.json` add the types:

```json
{
   "compilerOptions": {
     ...
     "types": ["bun-types"],
   ...
 }
}

**Comment by atul-5242** [comment]
I have a suggestion — I think you should consider placing the test file in the correct directory. Initially, I had placed the test file one level above the directory where my package.json and tsconfig.json files are located. However, after moving the index.test.ts file into the same directory as those configuration files, all the errors were resolved.

**Comment by mattparlane** [comment]
If anyone visits here from the future, I had this problem and I solved it by deleting the `typeRoots` array under `compilerOptions`.
