### ISSUE TITLE
Catch doesn't works as expected with AbortController

### ISSUE THREAD

**Issue by Zig1375** [oven-sh/bun#9805]
### What version of Bun is running?

1.0.36+40f61ebb9

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

When I use `fetch` and then receive response as a stream and then abort the request, the catch does not work as expected:
```
Request was aborted
Test completed
AbortError: The operation was aborted.
```

The third line `AbortError: The operation was aborted.` is NOT expected! Especially after the `Test completed` is shown...

Code for repro:
```ts
const abortController = new AbortController();

async function test() {
  try {
    const response = await fetch('https://bun.sh/', {
      signal: abortController.signal
    });

    const stream = response.body;
    // @ts-ignore
    for await (const part of stream) {
      abortController.abort();
    }
  } catch (e: any) {
    if (e.name === 'AbortError') {
      console.log('Request was aborted');
    } else {
      console.error('An error occurred', e);
    }
  }

  console.log('Test completed');
}

test();
```

### What is the expected behavior?

There should not be the `AbortError: The operation was aborted.`, because there is try/catch around the fetch.

**Comment by danny-avila** [comment]
Has been reported before

https://github.com/oven-sh/bun/issues/9429
https://github.com/oven-sh/bun/issues/6520

**Comment by Zig1375** [comment]
Hello… is there any progress here?
The issue still persists in version 1.1.20.

**Comment by cirospaciari** [comment]
Duplicated of https://github.com/oven-sh/bun/issues/9805

**Comment by infrahead** [comment]
Haven't read through all the code here, so maybe irrelevant... but one thing that has caught me several times is that common Node.js code uses pattern ` if (err.name === 'AbortError') ... ` but in Bun the err.name is just "Error".  Instead you can check err.code for 'ABORT_ERR'

Anyway, I wonder if something simple like this is complicating the issue
