### ISSUE TITLE
A tool to uninstall.

### ISSUE THREAD

**Issue by Drogobo** [oven-sh/bun#981]
### What is the problem this feature will solve?

Uninstalling it. I don't want bun anymore.

### What is the feature you are proposing to solve the problem?

Some uninstall script to use so I can remove it safely.

### What alternatives have you considered?

Going to every single file bun makes and deleting them. I don't know how to do that.

**Comment by Jarred-Sumner** [comment]
You can run `rm -rf ~/.bun`

**Comment by aral** [comment]
You also have undo the changes to your shell configuration, e.g., in fish:

```
# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH
```

From ~/.config/fish/config.fish

A `bun uninstall` would have value. It‘s good to clean up after yourself :)

**Comment by mathiasrw** [comment]
What about `bun install --revert`
