### ISSUE TITLE
Error when creating astro project with bun

### ISSUE THREAD

**Issue by DAVIDS2405** [oven-sh/bun#9810]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Windows 11 

### What steps can reproduce the bug?

```
bunx create-astro@latest
bun create astro
```
Whether using bunx or bun create to create the project with astro, there is a small problem that although I skip the installation of packages or not with npm and not with bun with previous versions there was not this error directly I installed everything with bun.
 
![image](https://github.com/oven-sh/bun/assets/85196670/03604002-3209-4c42-a052-905f27bdbe4d)

### What is the expected behavior?

It is expected to directly put me that it is going to occupy bun and not npm

**Comment by Jarred-Sumner** [comment]
<img width="438" alt="image" src="https://github.com/oven-sh/bun/assets/709451/61927372-dc61-48a3-90c5-e136cbf12350">
Fixed in Bun v1.1.14 by @SunsetTechuila
