### ISSUE TITLE
bun shell does not work on windows10

### ISSUE THREAD

**Issue by wk180** [oven-sh/bun#9819]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

save code to file `a.ts`

```
import { $ } from "bun";

const str = "cookies & creme";
await $`echo "${str}"`;
```

then run `bun run ./a.ts` in pwsh

### What is the expected behavior?

print `cookies & creme`

### What do you see instead?

```
2 | import { $ } from "bun";
3 |
4 | const str = "cookies & creme";
                                                                        ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"

      at BunShell (:184:69)

```

**Comment by Jarred-Sumner** [comment]
Unfortunately, I'm having trouble reproducing this issue. 

Is there anything more you can share about your computer or configuration? What drive letter is this running on? Was bun installed via powershell? Is the bun executable in $PATH?

**Comment by wk180** [comment]
I understand now, the full path of `a.ts` contains non-ASCII characters. Once I removed the non-ASCII characters, it worked.
