### ISSUE TITLE
Setting env variables in package.json scripts with more than 16 characters fails

### ISSUE THREAD

**Issue by adrifer** [oven-sh/bun#9823]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Add  a script tag on package.json with an env variable with more than 16 characters like this:
`"start": "AUTH_COOKIE_SECURE=false bun run src/server.ts",`

### What is the expected behavior?

As far as I know, it should run with env variables of more than 16 characters, at least it works on Node.

### What do you see instead?

When the env variable is AUTH_COOKIE_SECURE fails with this:
```
$ AUTH_COOKIE_SECURE=false bun run src/server.ts
bun: command not found: AUTH_COOKIE_SECURE=false
error: script "start" exited with code 1
```

Interestingly if the env variable is something shorter than 17 chars, it works perfectly. So it works with:
`"start": "AUTHCOOKIESECURE=false bun run src/server.ts",`
but not with:
"start": "AUTHCOOKIESECUREE=false bun run src/server.ts",

**Comment by is-jonreeves** [comment]
I'm using Windows 10, for me long ENVs are fine. Your one in particular though `AUTH_COOKIE_SECURE`, doesn't want to work.

If I remove/replace the `A` from the start it can be as long as I want. Putting it in an `.env` and passing it in with `bun --env-file=.env run src/server.ts` works.

Odd
