### ISSUE TITLE
bun.sh Windows doesn't detect/uses proxy server

### ISSUE THREAD

**Issue by KarloDerEchte** [oven-sh/bun#9827]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

1. Be behind a Company Proxy
2. set the proxy server 
``` 
    set HTTP_PROXY="http://your_proxy_ip:3128"
    
    set HTTP_PROXY="http:/your_proxy_ip:3128"
    
     set NO_PROXY="localhost"
```
3. Run bun install
4. Get a coffee
5. See that bun install is stuck in resolving packages
    

### What is the expected behavior?

Ig it would be that bun install installs the packages

### What do you see instead?

its stuck at "Resolving...."

### Additional information

When I do bun install --verbose I get the following
```
Resolving... Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

Response: < 200 Connection established

```

**Comment by MalteBoehm** [comment]
Same Problem for me
