### ISSUE TITLE
Axios not yet supported

### ISSUE THREAD

**Issue by sulvii** [oven-sh/bun#9828]
### What version of Bun is running?

1.1.0+5903a6141

### What steps can reproduce the bug?

Whenever you try to use axios you get an error. Tried in multiple projects, all of them threw the same error

### What is the expected behavior?

Send HTTP request to an endpoint

### What do you see instead?

Error: "zlib.createBrotliDecompress is not yet implemented"

**Comment by 8xu** [comment]
Have a look at this. 👀

https://bun.sh/guides/http/fetch

**Comment by sulvii** [comment]
@8xu I was referring to incorporating support for axios. I am aware that the fetch API exists.

**Comment by 1cedsoda** [comment]
This issue is the reason #267
And there is a workaround for axios https://github.com/oven-sh/bun/issues/267#issuecomment-1854460357

**Comment by sulvii** [comment]
Implemented
