### ISSUE TITLE
`bun` command vastly varies in execution time (10-20ms, then 2s)

### ISSUE THREAD

**Issue by MAXOUXAX** [oven-sh/bun#9829]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Install Bun on Windows using the provided command
2. Run any `bun` command, like `bun -v`
3. Measure the time the command takes (or use `Measure-Command {bun}` multiple times)

### What is the expected behavior?

The `bun` command should run the same on every run

### What do you see instead?

The time the same command takes to execute can vary between 15ms and more than 2 seconds

### Additional information

![image](https://github.com/oven-sh/bun/assets/24844231/bd41a7be-a9f9-4a56-addd-befbc508b1fb)

**Comment by Jarred-Sumner** [comment]
Guessing this is anti-virus

**Comment by MAXOUXAX** [comment]
Indeed, this doesn't seem related to the bun executable at all, since I cannot reproduce this on my desktop PC.
However, the funny thing is, everything inside Windows Defender is turned on, both on my laptop (which had the problem) and my desktop (which doesn't).

Closing this since this isn't really related to Bun itself and will be a PITA to reproduce
