### ISSUE TITLE
bun as superuser

### ISSUE THREAD

**Issue by colossalchicken** [oven-sh/bun#983]
### Version

0.1.6

### Platform

Raspberry Pi 4

### What steps will reproduce the bug?

```
supreme-overlord@world:~ $ sudo bun
sudo: bun: command not found
```

### What do you see instead?

`sudo: bun: command not found`

**Comment by vrmiguel** [comment]
This is an issue with your system's configuration rather than a Bun one.

You can likely solve it [following this](https://superuser.com/questions/453246/sudo-can-not-find-binary)

**Comment by sovetski** [comment]
same here, @vrmiguel's link did not help
