### ISSUE TITLE
running `bun create` results in an error

### ISSUE THREAD

**Issue by zilllaiss** [oven-sh/bun#9833]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. open terminal, be it poweshell, cmd, or git bash.
2. run `bun create` for any package, e.g. `bun create astro@latest` and `bun create svelte@latest`

### What is the expected behavior?

it expectedly created the package

### What do you see instead?

```shell
  🔍 giget [5/14] Illegal instruction at address 0x7ff70e8f84d1
  🔍 colorette [8/17] ???:?:?: 0x7ff70e8f876f in ??? (bun.exe)
???:?:?: 0x7ff70de1465e in ??? (bun.exe)
???:?:?: 0x7ff70dfb77e6 in ??? (bun.exe)
???:?:?: 0x7ff70ddad834 in ??? (bun.exe)
???:?:?: 0x7ff70df66824 in ??? (bun.exe)
???:?:?: 0x7ffac28e7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffac3ea26b0 in ??? (ntdll.dll)
```

### Additional information

I'm not sure it's related to #9808, but I do have the same problem with them with `bun install`, but also extended with `bun create`. I've also tried the suggestion given there, but to no result. I have tried using Powershell 7, Windows Powershell, Cmd, and Git Bash just in case, but no luck.

It's easy to reproduce as it is only for creating a package.

EDIT: I've just found out about this issue #9810, but to me this applies to any package, not just Astro. Added Svelte to reproduction for demonstration.

**Comment by Jarred-Sumner** [comment]
This was very likely fixed either due to permissions flags in v1.1.4 or so, or in 1.1.8 due to setting cpu flags of dependencies correctly. Please let us know if you still run into this on Bun v1.1.8 or later.
