### ISSUE TITLE
Bun crashes when using `create` with an invalid package

### ISSUE THREAD

**Issue by rgilsimoes** [oven-sh/bun#9837]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

```
bun create BunWinDemo
```

### What is the expected behavior?

A workable project in the BunWinDemo directory.

### What do you see instead?

╰─❯ bun create BunWinDemo
  🔍 create-BunWinDemo [1/1]
error: package "create-BunWinDemo" not found registry.npmjs.org/create-BunWinDemo 404
???:?:?: 0x7ff79401aa91 in ??? (bun.exe)
???:?:?: 0x7ff794013554 in ??? (bun.exe)
???:?:?: 0x7ff7940135ae in ??? (bun.exe)
???:?:?: 0x7ff794025a4e in ??? (bun.exe)
???:?:?: 0x7ff794025a56 in ??? (bun.exe)
???:?:?: 0x7ff7940c616b in ??? (bun.exe)

error: InstallFailed

----- bun meta -----
Bun v1.1.0 (5903a614) Windows x64
AddCommand:
Elapsed: 765ms | User: 750ms | Sys: 31ms
RSS: 52.24MB | Peak: 52.24MB | Commit: 93.75MB | Faults: 14397
----- bun meta -----

0   00007FF79546A4C8
1   ???
2   ???
3   ???
4   ???
5   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

Segmentation fault at address 0xb2c7ab1010
???:?:?: 0x7ff91c164813 in ??? (ctiuser.dll)
???:?:?: 0x7ff96159dd62 in ??? (KERNELBASE.dll)
???:?:?: 0x7ff9630fd38b in ??? (KERNEL32.DLL)
???:?:?: 0x7ff794db277e in ??? (bun.exe)
???:?:?: 0x7ff794da48fb in ??? (bun.exe)
???:?:?: 0x7ff794da433f in ??? (bun.exe)
???:?:?: 0x7ff79402f7d1 in ??? (bun.exe)
???:?:?: 0x7ff794032af4 in ??? (bun.exe)
???:?:?: 0x7ff7940c3442 in ??? (bun.exe)
???:?:?: 0x7ff793df1603 in ??? (bun.exe)
???:?:?: 0x7ff796927e33 in ??? (bun.exe)
???:?:?: 0x7ff9630f7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ff963da26b0 in ??? (ntdll.dll)

**Comment by dylan-conway** [comment]
fixed in #10758 and available in `v1.1.7`
