### ISSUE TITLE
Terminal garbled characters

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#9839]
### What version of Bun is running?

windows bun-v1.1

### What platform is your computer?

windows11

### What steps can reproduce the bug?

The much anticipated Windows version is finally online, thanks to the bun team.

In the windows vscode terminal, when pressing the up and down keys to switch commands, garbled characters as shown in the figure are always displayed. Please fix it.

![Snipaste_2024-04-02_16-38-23](https://github.com/oven-sh/bun/assets/121753618/8fa4e46f-ad1b-48cb-b993-92c843a52c9b)

**Comment by RiskyMH** [comment]
This should be solved some time ago (I can't remember where or when though). 
@vamsaya if you still get this, let me know and I can re-open.
