### ISSUE TITLE
Top-level await leads to uncaught-exception not exiting the process

### ISSUE THREAD

**Issue by daniellionel01** [oven-sh/bun#9843]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.4.0 arm64 arm (MacBook Pro 14" M2 Pro)

### What steps can reproduce the bug?

Running the following code leads to the process exiting when the exception is thrown:
```js
async function erroringPromise() {
  return new Promise((_res, rej) => {
    rej("oops");
  });
}

async function main() {
  setTimeout(() => erroringPromise(), 3000);
  while (true) {
    console.log("still running");
    await Bun.sleep(1000);
  }
}
main()
```

Modifying the last line from `main()` to `await main()` makes it so the process continues to run as seen in the screenshot below:

![image](https://github.com/oven-sh/bun/assets/35135912/9a5e59e5-69ce-425b-9ae7-94e27eecffa7)

### What is the expected behavior?

The exepected behaviour is for both scenarios (`main()` and `await main()`) to exit the process, because an uncaught exception is thrown

### What do you see instead?

The `await main()` version continues to run the process

![image](https://github.com/oven-sh/bun/assets/35135912/9a5e59e5-69ce-425b-9ae7-94e27eecffa7)

**Comment by toverux** [comment]
@daniellionel01 Why did you close this issue? I am still seeing this behavior with the latest version of Bun and it doesn't seem to be a correct one.

**Comment by kravetsone** [comment]
Looks like this is no top level throws

Also I guess it works in node in the same manner
