### ISSUE TITLE
Wrong version of package is installed

### ISSUE THREAD

**Issue by stijnvanderlaan** [oven-sh/bun#9845]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Run `bun i`
`"ora": "5.3.0",` is the dependancy, which is installing the correct version, but it has `"strip-ansi": "^6.0.0"` as a dependency. This is installing version `7.0.1` which is not compatible.

### What is the expected behavior?

It needs to install a version of 6, not a major version above it.

### What do you see instead?

It is installing version 7.

**Comment by dylan-conway** [comment]
Can you share all the dependencies in your package.json? I'm unable to reproduce this with `{ dependencies: { "ora": "5.3.0" }`

**Comment by stijnvanderlaan** [comment]
`ora` is a dependancy of `blitz "2.0.6"`. Which is a devDependancy

**Comment by stijnvanderlaan** [comment]
I think the problem it upgrading from yarn, removing all node_modules seems to fix the issue.
