### ISSUE TITLE
Bun runs unreachable code if it overwrites WebSocket global

### ISSUE THREAD

**Issue by untitaker** [oven-sh/bun#9848]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

1. write this code into `lol.js`:

```
if (typeof WebSocket === 'undefined') {
  console.log("no builtin websocket");
  var WebSocket = require('websocket').w3cwebsocket;
} else {
  console.log("yes builtin websocket");
}
```

2. execute using `bun run lol.js`
3. observe console output `no builtin websocket`
4. comment out the line `var WebSocket = ...`
5. observe `yes builtin websocket`

### What is the expected behavior?

bun should enter "yes builtin websocket" 100% of the time, and independently of the branch's content, or bail out early because dependency resolution and auto-installation is too complex in this case

### What do you see instead?

bun enters the "no builtin websocket" branch 100% of the time

### Additional information

i have code written like this in order to run without dependencies in browser (and bun), and with `websocket` "polyfill" in node.

**Comment by untitaker** [comment]
It seems that replacing `var WebSocket = ` with `WebSocket = ` fixes this issue. I would argue this is still surprising and undesirable behavior, because the above code works in browser (even though possibly by accident)

**Comment by e3dio** [comment]
In JS `var` keyword is 'hoisted' to top of function regardless of block level scope or branch with variable initialized to `undefined` so it's not running unreachable code it's just standard JS, probably better to match Node behavior for redeclaring global variables than browser

**Comment by untitaker** [comment]
yeah that makes sense
