### ISSUE TITLE
bun run run causes bun to add another run

### ISSUE THREAD

**Issue by coderbuzz** [oven-sh/bun#986]
### Version

0.1.6

### Platform

Darwin Kernel Version 21.6.0

### What steps will reproduce the bug?

Add run script on package.json

`"run": "npm run"`

run with bun: `bun run run`

Bun execute with add another run `npm run run`

### What do you see instead?

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1284811/182999030-23d56f29-8968-4a30-a1a3-7280357ff54b.png">

**Comment by birkskyum** [comment]
The "run" script in package.json is being executed with `bun run run`.
