### ISSUE TITLE
Bun on windows, inquirer list press the direction key does not work

### ISSUE THREAD

**Issue by QingFengGod** [oven-sh/bun#9870]
### What version of Bun is running?

1.1.0

### What platform is your computer?

windows x64

### What steps can reproduce the bug?

 const answers = await inquirer.prompt([
      {
        type: 'list',
        name: 'type',
        message: '项目类型',
        default: 'vue',
        choices: [
          { name: 'vue', value: 'vue' },
          { name: 'react', value: 'react' },
          { name: 'jq', value: 'jq' },
        ]        
      }
])

### What is the expected behavior?

Press the up and down keys to move the option

### What do you see instead?

Press the arrow button to display the history,
Press the direction button without any reaction.

**Comment by AwesomeKalin** [comment]
+1 Can confirm that it happens to me as well. Also prevents cancelling execution with Ctrl C, meaning that you need to restart the terminal. Also happens in cmd, powershell and git bash.

**Comment by MuellerMarvin** [comment]
+1 also with shad-cn/ui

`bunx --bun shadcn-ui@latest init` will not have it's up / down selection work

**Comment by sanjithacks** [comment]
+1 same 

```sh

bunx --bun create-next-app@latest my-app --typescript --tailwind --eslint

```

Left/Right key not work. Not able to choose

**Comment by blk-raffy** [comment]
+1
Sometimes I also have to press the "ENTER" button twice to confirm

**Comment by blk-raffy** [comment]
![image](https://github.com/oven-sh/bun/assets/34171011/20e479dc-8cfe-47db-b443-6eeb049f9402)

It also break when some process ends, the enter button just create other lines instead of terminating the guided step

**Comment by Arctomachine** [comment]
Probably having this issue too with create-expo-app. Arrows not moving selected option. Impossible to ctrl+c it on this step. But accepting selected option works, and it becomes possible to ctrl+c it on next step.
![image](https://github.com/oven-sh/bun/assets/29041820/cde1adf3-ada5-44e3-aa88-fd6f720640bb)

**Comment by ianram0s** [comment]
Same here. Running a fresh bun project with latest @inquirer/prompts version. A lot of issues with most prompts.

**Comment by heerheer** [comment]
+1 here, waiting to be fixed XD
