### ISSUE TITLE
Failed to resolve @rollup/rollup-<arch> package after "bun create astro" command

### ISSUE THREAD

**Issue by yy-zhong** [oven-sh/bun#9876]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. run `bun create astro`
2. skip installing dependencies
3. move to project folder and run `bun install`

### What is the expected behavior?

Install all dependencies correctly without any error.

### What do you see instead?

```
error: @rollup/rollup-darwin-arm64@4.14.0 failed to resolve
error: @rollup/rollup-android-arm64@4.14.0 failed to resolve
error: @rollup/rollup-win32-arm64-msvc@4.14.0 failed to resolve
error: @rollup/rollup-linux-arm64-gnu@4.14.0 failed to resolve
error: @rollup/rollup-linux-arm64-musl@4.14.0 failed to resolve
error: @rollup/rollup-android-arm-eabi@4.14.0 failed to resolve
error: @rollup/rollup-linux-arm-gnueabihf@4.14.0 failed to resolve
error: @rollup/rollup-win32-ia32-msvc@4.14.0 failed to resolve
error: @rollup/rollup-linux-riscv64-gnu@4.14.0 failed to resolve
error: @rollup/rollup-darwin-x64@4.14.0 failed to resolve
```

### Additional information

pnpm, npm and yarn all installs normally on this package.json file.

**Comment by takkuumi** [comment]
use `bun install -f --no-cache`

**Comment by Loongphy** [comment]
I got a similar situation after upgrading from Vite 5.1.4 to 5.2.9, and downgrading solved the issue. I hope this can help you.

**Comment by Loongphy** [comment]
It seems to be caused by a custom registry.
https://github.com/oven-sh/bun/issues/1830#issuecomment-1409741101

**Comment by yy-zhong** [comment]
> use `bun install -f --no-cache`

This solved my problem perfectly! Thx!

**Comment by yy-zhong** [comment]
> I got a similar situation after upgrading from Vite 5.1.4 to 5.2.9, and downgrading solved the issue. I hope this can help you.

I think vite's version isn't the core problem here, been trying the latest version of astro, and it installs 5.2.10 version. Thanks to @takkuumi solution, it runs smoothly now.
