### ISSUE TITLE
Spaces in directory break `bun run`

### ISSUE THREAD

**Issue by Sukadia** [oven-sh/bun#9879]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Attempt running `bun run dev` in a directory containing a space with the following scripts in package.json:
```
"scripts": {
    "extension-dev": "cd src/extension && webpack -w --config webpack.config.ts",
    "program-dev": "cd src/program && nodemon -e rs --watch src --exec cargo run --target-dir ../../dist/program",
    "dev": "concurrently -n EXT,PRO -c cyan,magenta \"npm run extension-dev\" \"npm run program-dev\""
}
```
(Replacing `npm run` with `bun run` yields the same result)

### What is the expected behavior?

Bun to run properly and account for the spaces.

### What do you see instead?

```
X:\Some Useful Stuff\Applications\Web\Slash-Playlist>bun run dev
$ concurrently -n EXT,PRO -c cyan,magenta "bun run extension-dev" "bun run program-dev"
'X:\Some' is not recognized as an internal or external command,
operable program or batch file.
error: script "dev" exited with code 1
```

**Comment by gwj916** [comment]
This happened to me too, thinking it was nvm affecting bun

**Comment by MAttila42** [comment]
It also breaks `bun install`
