### ISSUE TITLE
Nodemailer does not seem to work with Bun on Windows

### ISSUE THREAD

**Issue by kailoklum** [oven-sh/bun#9880]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Any attempt to use bun to run any js project with Nodemailer in it fails. 
Running it using node ( Node 20 LTS) works perfectly fine.

These are the dependencies in package.json on a very simple Nodemailer project to send emails.
```
{
"dependencies": {
    "nodemailer": "^6.9.12",
    "@react-email/components": "0.0.11",
    "@react-email/html": "0.0.6",
    "@react-email/render": "^0.0.9",
    "react" : "18.2.0"
  },
  "devDependencies": {
    "@types/nodemailer": "6.4.6",
    "@types/node": "^18.18.0",
    "@types/react": "^18.2.33",
    "tsconfig": "*",
    "tsup": "8.0.2",
    "typescript": "5.4.3"
  }
}
```

### What is the expected behavior?

Successfully send emails using Nodemailer with React Email.
Should return success message of
 
```
Message sent: <a021c114-5054-be3e-734f-50213af587b6@testing.domain>
250 2.0.0 OK <a021c114-5054-be3e-734f-50213af587b6@testing.domain>
```

### What do you see instead?

any projects with Nodemailer in it fails with this error.

`error: Unexpected reading "C:\Users\Test\Documents\Projects\Nodemailer\MailProject\node_modules\nodemailer"`

**Comment by SupertigerDev** [comment]
If its an existing project, try deleting the node modules folder
Running `bun i`
and testing again

**Comment by kailoklum** [comment]
Thanks! Didn't think about that.
