### ISSUE TITLE
String.raw incorrectly handles some strings

### ISSUE THREAD

**Issue by drewlesueur** [oven-sh/bun#9891]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-1014-aws aarch64 aarch64

### What steps can reproduce the bug?

Strings.raw does not work for some characters like • and «

Example Program raw.js
```
console.log(String.raw`•»`)
```

Running with node.js outputs expected value
```
node raw.js
•»
```

Running with Bun outputs incorrect value
```
bun raw.js
\u2022\u00BB
```

### What is the expected behavior?

I expect the output to be:

```
•»
```

### What do you see instead?

Instead I see:
```
\u2022\u00BB
```

### Additional information

It works correctly in iOS Safari too.
Also thank you for Bun.

**Comment by drewlesueur** [comment]
Going to close this because it seems to be a duplicate of https://github.com/oven-sh/bun/issues/8745

**Comment by drewlesueur** [comment]
Update. Using String.raw specifically appears to be fixed in v1.1.1. However the deeper issue (https://github.com/oven-sh/bun/issues/8745) appears to still be a problem.

**Comment by Jarred-Sumner** [comment]
I don't think this is fixed

**Comment by drewlesueur** [comment]
Ah, you are right. Not fixed yet. I incorrectly thought it was fixed. Thank you.

**Comment by Electroid** [comment]
Not fixed, but still a duplicate of the other issue.

**Comment by Electroid** [comment]
Duplicate of https://github.com/oven-sh/bun/issues/8745
