### ISSUE TITLE
add something like Bun.chalk

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#9892]
### What is the problem this feature would solve?

Styled console.log's

### What is the feature you are proposing to solve the problem?

To have an optimized [chalk](https://www.npmjs.com/package/chalk) built into Bun. Nothing big, but would be awesome to have it.

Proposal:

```ts
console.log(Bun.chalk.red("..."));

// or

const chalk = new Bun.Chalk();

chalk.concat(chalk.red("..."));

console.log(chalk); // automatic stringify
// or
chalk.log(); // pipe string to `console.log`
```

### What alternatives have you considered?

```ts
import chalk from "chalk";
```

**Comment by mangs** [comment]
Version `1.0.31` added support for `util.styleText` which does what you're looking for: https://bun.sh/blog/bun-v1.0.31#new-util-styletext

Downside is there are still no types for it in `@types/bun`, but the functionality works

**Comment by ghost** [comment]
@mangs how can I contribute with `@types/bun`?

**Comment by mangs** [comment]
Good question. Why didn't I think of that? You can find it here: https://github.com/oven-sh/bun/tree/main/packages/bun-types

`@types/bun` just references `bun-types` directly

**Comment by ghost** [comment]
@mangs `util.styleText` was added in Node v21.7.0, and bun-types depends on Node v20.11.3. What would be the impacts of updating the version of `@types/node`?

**Comment by mangs** [comment]
I added a PR here: https://github.com/oven-sh/bun/pull/9945

**Comment by mangs** [comment]
To answer your question, I tried updating to the latest version of `@types/node` using the `package.json` `overrides` field but that didn't help. I inspected the types manually and the definitions aren't in there. So I made a PR myself. Thank you for the idea. 🙂
