### ISSUE TITLE
Bun crashes when trying to run any subcommand

### ISSUE THREAD

**Issue by cartercanedy** [oven-sh/bun#9897]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

The bun CLI is correctly able to produce the help dialog, but all subcommands crash with a `Panic: incorrect alignment` error message.

### What is the expected behavior?

No crashes, able to use bun i/repl/x

### What do you see instead?

Full error message:

```
Panic: incorrect alignment

bun has crashed :'(

----- bun meta -----
Bun v1.1.0 (5903a614) Windows x64 
BunxCommand: 
Elapsed: 4ms | User: 0ms | Sys: 31ms
RSS: 20.39MB | Peak: 20.40MB | Commit: 62.39MB | Faults: 5113
----- bun meta -----

0   00007FF62102A4C8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 48264 panic: incorrect alignment
???:?:?: 0x7ff61f9fabf4 in ??? (bun.exe)
???:?:?: 0x7ff61f9f939f in ??? (bun.exe)
???:?:?: 0x7ff61f9f4bf9 in ??? (bun.exe)
???:?:?: 0x7ff61fb88cca in ??? (bun.exe)
???:?:?: 0x7ff61fbf1108 in ??? (bun.exe)
???:?:?: 0x7ff61fc83442 in ??? (bun.exe)
???:?:?: 0x7ff61f9b1603 in ??? (bun.exe)
???:?:?: 0x7ff6224e7e33 in ??? (bun.exe)
???:?:?: 0x7fffd9047343 in ??? (KERNEL32.DLL)
???:?:?: 0x7fffd93226b0 in ??? (ntdll.dll)
```

### Additional information

The machine that is having issues is a workstation with an older build of windows 10 on it. I've been able to install and run the cli properly on my personal machine running Windows 11 23H2.

Also, the processor on the pc in question supports AVX2 instructions, in case that becomes relevant.

**Comment by cartercanedy** [comment]
bump

**Comment by gvilums** [comment]
Are there any further details you can share about the machine where this error happens, to aid in reproducing this?

**Comment by cartercanedy** [comment]
I'm on a Lenovo P1 workstation laptop, processor: `Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz 2.81 GHz`. Is there anything else that you want me to add?

**Comment by jeremyVignelles** [comment]
Also happens to me on whatever I do on my work's computer (HP ZBook on windows 10).
I installed bun with npm because unsigned powershell is blocked by company's policy.

Bun v1.1.4 (1.1.0 did the same). Anything else you need me to provide ?

**Comment by gvilums** [comment]
We're currently working on a new crash reporting tool that will hopefully enable us to debug this better. Should probably be coming in v1.1.5. Once that's merged it would be great if you could run bun again and then submit the generated crash report. Will update this issue once relevant.

**Comment by jeremyVignelles** [comment]
I updated to 1.1.7 with `npm i -g bun` and it works now.

I noticed though that when I tried in git bash, it tried to use bun from ~/.bun/bin where an old 1.1.4 was still present. I removed that folder manually and it all works now

**Comment by gvilums** [comment]
@cartercanedy can you try the latest version and check if you still run into this issue? If the crash still happens a crash report link should be generated, that would help us a lot when trying to debug this

**Comment by cartercanedy** [comment]
Still having issues, but the error message seems a bit more descriptive this time
```txt
error: Syscall downloading package manifest bun-repl
error: bun-repl@latest failed to resolve
```

**Comment by cartercanedy** [comment]
Actually, I take that back, it looks like it was an issue with my corporate proxy configuration. I constant issues with self-signed certs when I use npm, I wouldn't be surprised if that's part of the issue here
