### ISSUE TITLE
Bun install: ENOENT

### ISSUE THREAD

**Issue by codeman4033** [oven-sh/bun#9899]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`bun install` on any project

### What is the expected behavior?

`bun install` installing the modules just fine with no errors.

### What do you see instead?

error: ENOENT opening node_modules folder

### Additional information

The node_modules does get made, and even after it gets made it gives the exact same error.

**Comment by Jarred-Sumner** [comment]
Fixed in #9729, please try again after running `bun upgrade --canary` in about an hour (or wait for Bun v1.1.1). Let us know if you run into this again.
