### ISSUE TITLE
bun.lockb - why does it have execute & group+world write permission on macOS?

### ISSUE THREAD

**Issue by beorn** [oven-sh/bun#9904]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```console
% bun install
```

### What is the expected behavior?

```console
% umask
022
% rm bun.lockb && bun install
% ls -l bun.lockb
-rw-r--r-- 1 user  group  549200 Apr  3 15:33 bun.lockb
```

It's just a regular file created in a way that observes the umask: no execute permission and only writable for user.

### What do you see instead?

```console
% umask
022
% rm bun.lockb && bun install
% ls -l bun.lockb
-rwxrwxrwx 1 user  group  549200 Apr  3 15:33 bun.lockb
```

The file has execute permissions and is group+world writable.

### Additional information

I couldn't reproduce this on Linux (Github CI).

**Comment by Jarred-Sumner** [comment]
You can run `./bun.lockb` to print the contents of the binary lockfile as a yarn.lock file

<img width="753" alt="image" src="https://github.com/oven-sh/bun/assets/709451/58ba50fd-468c-4c99-8e1e-7e1a7ef38ba6">

**Comment by LitoMore** [comment]
@Jarred-Sumner But why the `bun.lockb` file has `-rwxrwxrwx` permission on macOS? As I understand it should be `-rwxrwxrwx` instead of `-rwxrwxrwx`.

The behavior is not consistent. I can see the `bun.lockb` file in your project is `-rwxrwxrwx`.
