### ISSUE TITLE
`Unknown file extension ".ts"` error on `bun x --bun mikro-orm debug` command if Bun installed via `curl -fsSL https://bun.sh/install | bash`, but works OK if it installed via `npm i -g bun`

### ISSUE THREAD

**Issue by supfiger** [oven-sh/bun#9906]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Darwin 23.1.0 x86_64 i386

### What steps can reproduce the bug?

**You can watch the issue reproduction here:**
[https://monosnap.com/file/leHk5PYE0A4p5aB674NJYVpv0mRbld](https://monosnap.com/file/leHk5PYE0A4p5aB674NJYVpv0mRbld)

**You can see the code here:**
[https://replit.com/@supfiger/Bun-v110-and-MikroORM-issue](https://replit.com/@supfiger/Bun-v110-and-MikroORM-issue)

### What is the expected behavior?

It should works OK and works the same no matter how Bun is installed, via `curl`, or `brew`, or `npm` or in any other way.

### What do you see instead?

It throws the `Unknown file extension ".ts"` error when Bun installed via `curl -fsSL https://bun.sh/install | bash`.
But it works OK when Bun installed via `npm i -g bun`.

**Comment by supfiger** [comment]
It is related to https://github.com/mikro-orm/mikro-orm/issues/4701, but I already use [alwaysAllowTs](https://github.com/mikro-orm/mikro-orm/pull/4702) flag in `package.json` and also [Bun's shebangs](https://bun.sh/docs/cli/bunx#shebangs).

**Comment by Electroid** [comment]
Could you confirm that the `bun --revision` is the same for all of those installations?

**Comment by supfiger** [comment]
> Could you confirm that the `bun --revision` is the same for all of those installations?

* `1.1.0+5903a6141` - from installing via `curl`.
* `1.1.0+5903a6141` - from installing via `npm`.

So yes, they are equal.

**Comment by Jarred-Sumner** [comment]
This `Unknown file extension` error does not come from Bun.

I'm inclined to think this is a bug in MikroORM. It's also possible there's a missing `code` property in an error returned from Bun. If there's an error `code` property we're missing please open an issue for that.

<img width="394" alt="image" src="https://github.com/oven-sh/bun/assets/709451/3fbb915b-339e-4bd0-8dad-c36c04632c2f">
