### ISSUE TITLE
New version bun v1.1.0 Windows AMD64 cannot be installed

### ISSUE THREAD

**Issue by aishuaikang** [oven-sh/bun#9920]
### What version of Bun is running?

Not installed successfully

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

C:\Users\18333>powershell -c "irm bun.sh/install.ps1 | iex"
Install Failed:
Bun for Windows is currently only available for x86 64-bit Windows.

1

**Comment by aishuaikang** [comment]
![image](https://github.com/oven-sh/bun/assets/68257609/42d3c218-f96d-44fd-8f8e-78a6a6d01aa1)

**Comment by aishuaikang** [comment]
Solved, need to run cmd as administrator

**Comment by paperclover** [comment]
I'm making a change to the CPU-check. If you want to verify that my check is correct, can you run the following in powershell and see what it prints?

```
((Get-CimInstance Win32_ComputerSystem)).SystemType
```

**Comment by aishuaikang** [comment]
> I'm making a change to the CPU-check. If you want to verify that my check is correct, can you run the following in powershell and see what it prints?我正在对 CPU 检查进行更改。如果要验证我的检查是否正确，是否可以在 powershell 中运行以下命令并查看它打印的内容？
> 
> ```
> ((Get-CimInstance Win32_ComputerSystem)).SystemType
> ```

PS C:\Users\18333> ((Get-CimInstance Win32_ComputerSystem)).SystemType
x64-based PC
