### ISSUE TITLE
Bun shell exits process with exit code 0

### ISSUE THREAD

**Issue by JUSTIVE** [oven-sh/bun#9927]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

run following code with dependencies 

```typescript
const runner = async (endpoint: string) => {
  await $`npx get-graphql-schema ${endpoint} | grep -v "@connection" > ./src/schema.graphql`;
  console.log('a')
  try {
    await $`pnpm relay`;
  } catch (error) {
    console.error('[getSchema] relay compilation failed', error);
    process.exit(1);
  }
};
```

### What is the expected behavior?

graphql introspection should be done if endpoint is valid graphql endpoint, print 'a' to console output, then relay compile should run.

### What do you see instead?

graphql introspection works fine, but the process exit right after it. not even 'a' printed out.

### Additional information

the process's exit code is 0

**Comment by Jarred-Sumner** [comment]
can you provide an easier to reproduce code snippet? as-is, this code won't run

**Comment by JUSTIVE** [comment]
sorry for the incomplete information. 
I found the exact same graphql endpoint which generates the same status what I've got.

endpoint = https://graphql.anilist.co/graphql

- the command`(npx get-graphql-schema {endpoint} | grep -v "@connection" > ./src/schema.graphql` perfectly works on my native shell(zsh), with exit code 0.
- the same command in bun shell, shows the same issue as the topic.
- the minimum reproduction command is `npx get-graphql-schema {endpoint} > ./meh.txt`. without writing to file works perfectly fine. but when I try to get output text from the command like ```$`npx get-grahpql-schema {endpoint}`.text() ```, also shows the same behavior as described on the topic. 
- ```const {stdout} = $`npx get-grahpql-schema {endpoint}`; Bun.write('./schema.graphql', stdout.toString())``` worked without an issue, but ```const {stdout} = $`npx get-grahpql-schema {private endpoint}.quiet()`; Bun.write('./schema.graphql', stdout.toString())``` in order to suppress printed stdout from terminal, also doesn't work as said on the topic.

**Comment by JUSTIVE** [comment]
the issue also can be reproduced on 1.1.1.

**Comment by ashtonsix** [comment]
I've encountered a variation of this with the `.quiet()` modifier, where this code never prints `'DEBUG'` due to an immediate exit:

```ts
try {
  await Bun.$`cd ${path} && bun link`.quiet();
  console.log('DEBUG')
} catch (e) {
  console.log('DEBUG')
}
```

Get the same bad behaviour if I use the `--silent` flag as in ``Bun.$`cd ${path} && bun link --silent` ``. Works fine if neither the `.quiet()` modifier or `--silent` flag are present. Switched back to using promisified `exec` as it's more reliable.

**Comment by jimlloyd** [comment]
I too am hitting this bug. This works fine:

```
    const { stdout, stderr, exitCode } = await $`git ls-files ${dirPath}`.nothrow();
```

But if I add the `.quiet()` the process exits:

```
    dlog('getExistingGitFiles: dirPath:', dirPath);
    const { stdout, stderr, exitCode } = await $`git ls-files ${dirPath}`.nothrow().quiet();
    dlog({exitCode, stderr});
```

I see the first log message but not the second.

**Comment by harshjv** [comment]
This issue can also be reproduced on v1.1.10

**Comment by kemicofa** [comment]
I'm getting the same issue on `1.1.12`.

I'm attempting to simply list some directories and it just exits silently without any additional information. Any code following the shell command does not get excuted.

```
await $`ls\`.text();
console.log('hello world'); // <- never arrive here
```

**Comment by 0xroko** [comment]
Also getting this (1.1.15), only happens if shell call is inside a function:
```ts
import { $ } from "bun";

const main = async () =>
  try {
    console.log("Deleting");
    await $`rm -f db.sqlite`;
    console.log("After");
  } catch (error) {
    console.error(error);
  }
};

main();
```
![2024-06-22_14-53](https://github.com/oven-sh/bun/assets/55251261/e93f2dc1-816c-4f81-a44b-ef8b2c72783e)


This works:
```ts
import { $ } from "bun";

console.log("Deleting");
await $`rm -f db.sqlite`;
console.log("After");
```

**Comment by MarvNC** [comment]
I'm getting the same error on 1.1.17.
After running
```ts
export async function downloadDumps(lang: LanguageCode, date: string) {
(previous code ...)
    await $`bzip2 -dc ${archivePath} >${filePath}`;
  }

  console.log(`Finished downloading and extracting ${lang} dump`);

  return filePath;
}

```
it exits silently without continuing.

**Comment by mattvgm** [comment]
Having a similar problem with 1.1.22

With `.quiet()` the shell exits without response if inside an async function

**index.ts** - WORKS

```javascript
import { $ } from "bun";

const output = await $`grep -rl "function" .`.quiet();
console.log(output);
   ```

**index.ts** - DOES NOT  WORK

```javascript
import { $ } from "bun";

(async () => {
  const output = await $`grep -rl "function" .`.quiet();
  console.log(output);
})();

   ```

**Comment by Jarred-Sumner** [comment]
@0xroko @mattvgm the issue you're running into is https://github.com/oven-sh/bun/issues/13713 and is being tracked there

**Comment by mattvgm** [comment]
@Jarred-Sumner I am not the original poster but I added a related issue. I can confirm my problem was fixed in the last version, thanks.

**Comment by JUSTIVE** [comment]
I can confirm the problem is fixed now.

**Comment by raoufchebri** [comment]
I upgraded to `1.1.30`, but `.quiet()` still exists.
