### ISSUE TITLE
Bun.serve: ASCII characters looks weird after upgrade to 1.0.33

### ISSUE THREAD

**Issue by krutoo** [oven-sh/bun#9929]
### What version of Bun is running?

1.0.33

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create file `server.ts`:

```ts
// server.ts
Bun.serve({
  port: 3020,
  fetch() {
    return new Response('<h1>Hello • world</h1>', {
      headers: {
        'content-type': 'text/html',
      },
    });
  },
});

```

2. Run by Bun:

```bash
bun --smol run ./server.ts
```

3. Open http://localhost:3020/ in browser 

### What is the expected behavior?

Expected text on page:

```
Hello • world
```

### What do you see instead?

Actual text on page:

```
Hello â€¢ world
```

**Comment by Jarred-Sumner** [comment]
> HTTP has a default of ISO-8859-1, which even one HTML spec described as having "proved useless" [[source](http://www.w3.org/TR/html401/charset.html#spec-char-encoding)] (they don't even go into the fact that a large amount of stuff out there labelled as ISO-8859-1 is actually CP-1252).

Try setting the encoding: `text/html charset=utf-8` 

We used to normalize an unspecified charset to become `charset=utf-8` if unspecified. @paperdave did we get rid of that?

**Comment by Electroid** [comment]
The default encoding should be utf8, it’s somewhere in the fetch spec. This is a bug.

**Comment by Jarred-Sumner** [comment]
>  after upgrade to 1.0.33 

What version of Bun were you on before? Going back to `1.0.3` exhibits the same behavior, as does 1.0.31 and others

**Comment by krutoo** [comment]
> What version of Bun were you on before? Going back to `1.0.3` exhibits the same behavior, as does 1.0.31 and others

@Jarred-Sumner I forgot, sorry, I just noticed about this behavior =( 

How can I install specific version of Bun?

**Comment by krutoo** [comment]
bump (i will check it soon)

**Comment by krutoo** [comment]
@Jarred-Sumner It is still an issue in 1.1.24

Can we fix it as @Electroid [said](https://github.com/oven-sh/bun/issues/9929#issuecomment-2036892059)?

**Comment by Jarred-Sumner** [comment]
We cannot change the default encoding charset, as it would likely break many of our users who did not specify a charset
