### ISSUE TITLE
Bun upgrade to 1.1.1 crashes

### ISSUE THREAD

**Issue by nojaf** [oven-sh/bun#9931]
### What version of Bun is running?

1.1.1+7543bf936

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`bun upgrade`

### What is the expected behavior?

Not entirely sure, but I was hoping to revert back from the canaries to the stable version.

### What do you see instead?

Bun v1.1.0 is out! You're on 1.1.1

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.1 (7543bf93) Windows x64
UpgradeCommand:
Elapsed: 3166ms | User: 0ms | Sys: 15ms
RSS: 77.84MB | Peak: 77.84MB | Commit: 131.59MB | Faults: 19197
----- bun meta -----

0   00007FF61469EE38
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 33456 panic: attempt to unwrap error
???:?:?: 0x7ff6132dbef1 in ??? (bun.exe)
???:?:?: 0x7ff6132d9a65 in ??? (bun.exe)
???:?:?: 0x7ff6132dc526 in ??? (bun.exe)
???:?:?: 0x7ff6132e9207 in ??? (bun.exe)
???:?:?: 0x7ff6130115f5 in ??? (bun.exe)
???:?:?: 0x7ff615b93e63 in ??? (bun.exe)
???:?:?: 0x7ffe84fe257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe862eaa47 in ??? (ntdll.dll)

### Additional information

`bun upgrade --canary` fails exactly the same.

**Comment by tindecken** [comment]
i got error EBUSY

![image](https://github.com/oven-sh/bun/assets/4727197/02f16cd1-f2d1-44cb-9e27-645116492e22)

**Comment by mavrick** [comment]
bun upgrade
Bun v1.1.2 is out! You're on 1.1.1

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.1 (ca1dbb4e) Windows x64 
UpgradeCommand: 
Elapsed: 3328ms | User: 0ms | Sys: 0ms
RSS: 76.98MB | Peak: 76.98MB | Commit: 0.14GB | Faults: 18994
----- bun meta -----

0   00007FF73E92ED58
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord      

thread 25484 panic: attempt to unwrap error        
???:?:?: 0x7ff73d56bdd1 in ??? (bun.exe)
???:?:?: 0x7ff73d569945 in ??? (bun.exe)
???:?:?: 0x7ff73d56c406 in ??? (bun.exe)
???:?:?: 0x7ff73d5790e7 in ??? (bun.exe)
???:?:?: 0x7ff73d2a1603 in ??? (bun.exe)
???:?:?: 0x7ff73fe23ec3 in ??? (bun.exe)
???:?:?: 0x7ffed91f257c in ??? (KERNEL32.DLL)      
???:?:?: 0x7ffedaaaaa57 in ??? (ntdll.dll)

**Comment by nojaf** [comment]
I reinstalled Bun from scratch and upgrading now works again for me.

**Comment by skcc75** [comment]
Installing from scratch works, `bun upgrade` crashes.  Affects 1.1.2 also.

```
PS C:\Users\user\dev\entriwise\server> bun upgrade
Bun v1.1.3 is out! You're on 1.1.2

uh-oh: attempt to unwrap error
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.2 (c8d072c2) Windows x64
UpgradeCommand:
Elapsed: 1436ms | User: 15ms | Sys: 31ms
RSS: 78.06MB | Peak: 78.06MB | Commit: 0.14GB | Faults: 19242
----- bun meta -----

0   00007FF79A64E048
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 31620 panic: attempt to unwrap error
???:?:?: 0x7ff799280c31 in ??? (bun.exe)
???:?:?: 0x7ff79927e6d9 in ??? (bun.exe)
???:?:?: 0x7ff799281286 in ??? (bun.exe)
???:?:?: 0x7ff79928df67 in ??? (bun.exe)
???:?:?: 0x7ff798fb1603 in ??? (bun.exe)
???:?:?: 0x7ff79bb4e033 in ??? (bun.exe)
???:?:?: 0x7ff9c616257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ff9c6f2aa57 in ??? (ntdll.dll)
```

@Jarred-Sumner
