### ISSUE TITLE
`bun install`: index out of bounds

### ISSUE THREAD

**Issue by jonbng** [oven-sh/bun#9932]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

`powershell -c "irm bun.sh/install.ps1 | iex"`
restart terminal
`git clone https://github.com/Akademiaapp/website`
`cd website`
`git checkout 817807794173e88a1705464d3e14c1e39b76cd8d`
`bun i`

### What is the expected behavior?

It installs the dependencies

### What do you see instead?

```powershell
PS C:\Users\jonathan\website> bun i
bun install v1.1.0 (5903a614)
  📦 Installing [12/403]
uh-oh: index out of bounds
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.0 (5903a614) Windows x64
InstallCommand: extracted_packages(11)
HTTP: 78
Elapsed: 8867ms | User: 6078ms | Sys: 14125ms
RSS: 0.22GB | Peak: 0.22GB | Commit: 0.36GB | Faults: 90039
----- bun meta -----

0   00007FF6D87CA4C8
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 23272 panic: index out of bounds
???:?:?: 0x7ff6d751051a in ??? (bun.exe)
???:?:?: 0x7ff6d751123c in ??? (bun.exe)
???:?:?: 0x7ff6d738193b in ??? (bun.exe)
???:?:?: 0x7ff6d73784b8 in ??? (bun.exe)
???:?:?: 0x7ff6d7372610 in ??? (bun.exe)
???:?:?: 0x7ff6d74254c2 in ??? (bun.exe)
???:?:?: 0x7ff6d7151603 in ??? (bun.exe)
???:?:?: 0x7ff6d9c87e33 in ??? (bun.exe)
???:?:?: 0x7ffa754d257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa76e4aa57 in ??? (ntdll.dll)
PS C:\Users\jonathan\website>
```

### Additional information

It worked when i reran the command, also works on my friends pc. Maybe only happens first time after installing? I am happy to provide more info, but i cant reproduce...

**Comment by Jarred-Sumner** [comment]
@arctixdev can you run `bun upgrade --canary` and try again?

**Comment by jonbng** [comment]
Yeah, but it already works on stable, it was just the first time i ran the command.. I dont know if this makes the issue invalid

**Comment by Jarred-Sumner** [comment]
can you run `bun pm rm cache` and then see if it crashes like the first time or if it works?

**Comment by Jarred-Sumner** [comment]
and also `bun install --force`

**Comment by jonbng** [comment]
Actually i just got:
```powershell
bun install v1.1.0 (5903a614)
  📦 Installing [192/403] C:\Users\jonathan\website\node_modules\wrangler\node_modules\esbuild\install.js:132
    throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
          ^

Error: Expected "0.17.19" but got "0.18.20"
    at validateBinaryVersion (C:\Users\jonathan\website\node_modules\wrangler\node_modules\esbuild\install.js:132:11)
    at C:\Users\jonathan\website\node_modules\wrangler\node_modules\esbuild\install.js:283:5

Node.js v20.11.1

error: postinstall script from "esbuild" exited with 1
```
But that could just be the lock / packagefile being invalid 
Edit: That was before i ran `bun pm cache rm`

**Comment by jonbng** [comment]
Yes, after running `bun pm cache rm` it fails the same way as in my initial issue

**Comment by jonbng** [comment]
Also on canary:
```powershell
PS C:\Users\jonathan\website> bun upgrade --canary
[5.07s] Upgraded.

Welcome to Bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/5903a614102704a627e6add42fc5668eb7acb68e...main
PS C:\Users\jonathan\website> bun pm cache rm
Cleared 'bun install' cache
Cleared 0 cached 'bunx' packages
PS C:\Users\jonathan\website> bun i
bun install v1.1.1 (013bc79f)
  🚚 sass...
uh-oh: index out of bounds
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.1 (013bc79f) Windows x64
InstallCommand: extracted_packages(2)
HTTP: 43
Elapsed: 2336ms | User: 1140ms | Sys: 2406ms
RSS: 107.16MB | Peak: 126.53MB | Commit: 0.18GB | Faults: 42780
----- bun meta -----

0   00007FF6DBA9ED48
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 18380 panic: index out of bounds
???:?:?: 0x7ff6da7cce7a in ??? (bun.exe)
???:?:?: 0x7ff6da7cdb9c in ??? (bun.exe)
???:?:?: 0x7ff6da64469b in ??? (bun.exe)
???:?:?: 0x7ff6da63b247 in ??? (bun.exe)
???:?:?: 0x7ff6da6353b0 in ??? (bun.exe)
???:?:?: 0x7ff6da6e8ae2 in ??? (bun.exe)
???:?:?: 0x7ff6da4115f5 in ??? (bun.exe)
???:?:?: 0x7ff6dcf93d63 in ??? (bun.exe)
???:?:?: 0x7ffa754d257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa76e4aa57 in ??? (ntdll.dll)
```

**Comment by Jarred-Sumner** [comment]
I'm able to reproduce this 

Slightly more information

It's an index out of bounds right here: 

https://github.com/oven-sh/bun/blob/b8278052d2229817ae51ef003b90c6152b7baff8/src/install/install.zig#L4620

This occurs while installing peer dependencies

It does not seem to occur on mac/linux.

The dependency id is greater than the number of dependencies in the `buffers` struct

I don't know why this happens yet

**Comment by vanshavenger** [comment]
Getting the same error when i tried upgrading bun to 1.1.2

`uh-oh: attempt to unwrap error
bun will crash now 😭😭😭`

**Comment by webpro** [comment]
Apologies if unhelpful, but here's another case (bun v1.1.3): https://github.com/webpro/knip/actions/runs/8610517732/job/23596175702

A workspace in this monorepo has peer deps: https://github.com/webpro/knip/blob/main/packages/knip/package.json#L77-L80

**Comment by vanshavenger** [comment]
For those who got this error while upgrading bun can use the powershell installation command to upgrade to latest version instead of `bun upgrade` or `bun upgrade --canary` 

Command: `powershell -c "irm bun.sh/install.ps1|iex"`
