### ISSUE TITLE
Bun is ~20x slower than node.js on a benchmark setting props on a function object

### ISSUE THREAD

**Issue by btakita** [oven-sh/bun#9934]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.8.1-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

Run the benchmark using node & bun

```
node ./proxy_benchmark.js
vanilla x 1,386,398,241 ops/sec ±1.22% (96 runs sampled)
proxy x 26,280,830 ops/sec ±3.74% (86 runs sampled)
Fastest is vanilla
```

```
bun ./proxy_benchmark.js
vanilla x 48,252,387 ops/sec ±5.82% (63 runs sampled)
proxy x 7,758,912 ops/sec ±2.23% (90 runs sampled)
Fastest is vanilla
```

proxy_benchmark.js
```js
import Benchmark from 'benchmark'
const suite = new Benchmark.Suite
// add tests
suite.add('vanilla', function() {
	const fn = ()=>5
	fn.a = 0
	fn.b = 0
	fn.c = 0
	fn.d = 0
	fn.e = 0
	fn.f = 0
	fn.g = 0
	fn.h = 0
	fn()
}).add('proxy', function() {
	const fn = ()=>5
	const o = {
		a: 0,
		b: 0,
		c: 0,
		d: 0,
		e: 0,
		f: 0,
		g: 0,
		h: 0,
	}
	const proxy = new Proxy(fn, {
		get(_, prop) {
			return o[prop]
		},
		set(_, prop, val) {
			o[prop] = val
			return true
		}
	})
	proxy()
}).on('cycle', function(event) {
	console.log(String(event.target))
}).on('complete', function() {
	console.log('Fastest is ' + this.filter('fastest').map('name'))
}).run()
```

### What is the expected behavior?

Bun should have around the same performance as Nodejs on the benchmark. Not sure if this is a JavascriptCore vs V8 issue.

### What do you see instead?

Nodejs is >20x faster on the benchmark.

### Additional information

I have not yet verified if this is an issue with the Bun runtime or if this is an issue with JavascriptCore.

**Comment by Jarred-Sumner** [comment]
If you have a specific application / script that does something slower in Bun than Node feel free to open an issue. This is not that, this is a microbenchmark.

**Comment by btakita** [comment]
True. But many of your claims that Bun is X times faster are "Welcome to Bun!" http applications. Which is not much more than a microbenchmark. No apps will simply serve "Welcome to Bun!".

This benchmark was unexpected, so I'm not sure what to make of it yet. Reproducing a larger app would take more effort. So I'll see what I can do about that.

I'm optimizing a library that I wrote, so a microbenchmark is appropriate to make some decisions on how to implement an algorithm. I was surprised by the result.

I'm a bit concerned about "betting on Bun". Especially if this is a JavascriptCore issue. This makes it seem like NodeJS has more performance potential in the long term.

----
Edit: I have to eat my words on this one. I found a [performance issue](https://issues.chromium.org/issues/333584632) on V8 wrt WeakRef. JSC & Bun performed the best. NodeJS + Deno had runtime performance desegregation on the [benchmark](https://github.com/btakita/weakref-benchmark/). My library [rmemo (reactive memo)](https://github.com/ctx-core/rmemo) uses `WeakRef`. So I will have to put out a disclaimer wrt to V8 performance issues in the benchmark. Hopefully it's fixed soon.

**Comment by btakita** [comment]
An interesting note. Bun v1.1.1 does better on the benchmark. It seems like it's a JavascriptCore optimization.

```
bun ./proxy_benchmark.js
vanilla x 50,776,832 ops/sec ±5.41% (67 runs sampled)
proxy x 7,349,312 ops/sec ±2.41% (85 runs sampled)
Fastest is vanilla
```

**Comment by e3dio** [comment]
You are micro-benchmarking assigning properties to functions which is a strange thing to do. If you micro-benchmark assigning properties to standard Objects, Bun is actually faster than Node. So now I guess you have to ditch Node because Bun can assign properties to objects faster than Node ? How many functions are you creating and assigning properties to per second, that this micro-benchmark is more important than an HTTP server, or more important than setting Object properties ?
