### ISSUE TITLE
"bun serve" not supported on Windows

### ISSUE THREAD

**Issue by gweinfurther** [oven-sh/bun#9942]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

At a command line, type "bun serve"

### What is the expected behavior?

The current folder would be served to the browser.

### What do you see instead?

error: Script not found "serve"

**Comment by gvilums** [comment]
Hi, I'm not quite sure I understand what you're trying to accomplish. Do you expect to run `bun serve` in a folder with static files and have that be served, with not further JS involved? This isn't a feature that bun supports, neither on windows nor on any other platform

**Comment by Electroid** [comment]
`bun serve` is not a command, at least for now.

**Comment by aalaap** [comment]
@gweinfurther Not a command, but the behaviour you're looking for can be achieved by running:

```bash
bun x serve
```
