### ISSUE TITLE
Bun repl does not show input after starting it - Windows

### ISSUE THREAD

**Issue by Tilo-K** [oven-sh/bun#9944]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Using PowerShell on Windows:
- execute `bun repl`
- type something (you should see no characters being typed)
![image](https://github.com/oven-sh/bun/assets/17810881/b0986770-6cbe-47c8-915f-64ef2292233c)

- press enter
- you should see the input being evaluated
![image](https://github.com/oven-sh/bun/assets/17810881/6ca4ddc6-533a-4612-bd18-64efeb758d9e)

### What is the expected behavior?

The input should be visible

### What do you see instead?

No input before pressing enter once

### Additional information

When doing this in WSL, in the same Terminal, everything works as expected.

**Comment by gvilums** [comment]
I'm having trouble reproducing this - are there any more details about your setup that you could share?

**Comment by Tilo-K** [comment]
I'm using the Windows-Terminal 1.19.10573.0
https://github.com/microsoft/terminal

The bug appears for me using any shell, so: cmd, pwsh and pwsh without a profile (default settings).
The bug doesn't seem to happen when using the old Windows Consolehost.

So after investigating a bit more, it seems like an issue with this new terminal.

**Comment by naijun0403** [comment]
I have the same issue too.

My environment is also pwsh is the default shell and powershell is version 7.4.1.

The operating system is windows 11 and I am using windows terminal.

**Comment by panmenghan** [comment]
There are two screen recordings about the problem, the first is using `bun repl`, the second is `bun-debug repl`. 

After the first line enter in `repl`, the arrow keys are not working any more.

https://github.com/oven-sh/bun/assets/51240264/edeb88a5-52e7-4053-9ec2-5e85961cc519

https://github.com/oven-sh/bun/assets/51240264/06749c20-2ba4-47c3-b172-521a6213954f

**Comment by Almada2021** [comment]
I have the same issue in Windows 11
