### ISSUE TITLE
This package works in node but not with bun.

### ISSUE THREAD

**Issue by rktmatt** [oven-sh/bun#9946]
### What steps can reproduce the bug?

This is a reference to this issue : 
https://github.com/nuxt-modules/supabase/issues/266

I've seen in Bun 1.1 video to report to Bun things that work in node but not in Bun.

Thanks !

**Comment by anthonyfranc** [comment]
I'm having the same issue.

**Comment by Electroid** [comment]
Duplicate of #9948

**Comment by rktmatt** [comment]
> Duplicate of #9948

that's not a duplicate of #9948. The bug in #9948 was something that worked in 1.0 (I used that command successfully) and it doesn't work in 1.1 apparently (I haven't tested 1.1 because Bun just doesn't work properly on my framework)

But okay, keep both closed if you're already giving up in what you say in a video just a week ago or so. Well I don't see why we should bother using Bun at all.

**Comment by Electroid** [comment]
> > Duplicate of #9948
> 
> that's not a duplicate of #9948. The bug in #9948 was something that worked in 1.0 (I used that command successfully) and it doesn't work in 1.1 apparently (I haven't tested 1.1 because Bun just doesn't work properly on my framework)
> 
> But okay, keep both closed if you're already giving up in what you say in a video just a week ago or so. Well I don't see why we should bother using Bun at all.

Is there another issue that you're seeing? When I reproduced this issue, I ran into that error with Bun 1.1, which is why I marked it as a duplicate.

**Comment by rktmatt** [comment]
> > > Duplicate of #9948
> > 
> > 
> > that's not a duplicate of #9948. The bug in #9948 was something that worked in 1.0 (I used that command successfully) and it doesn't work in 1.1 apparently (I haven't tested 1.1 because Bun just doesn't work properly on my framework)
> > But okay, keep both closed if you're already giving up in what you say in a video just a week ago or so. Well I don't see why we should bother using Bun at all.
> 
> Is there another issue that you're seeing? When I reproduced this issue, I ran into that error with Bun 1.1, which is why I marked it as a duplicate.

thank you for getting back on this.

You ran into the issue during installation, for the package manager part of bunx in 1.1 that apparently do not work.

The issue I linked was during bunx runtime not during install. Bun runtime did work for nuxt before but it didn’t work if Supabase module for Nuxt was intalled, that’s why there was a ticket over there previously.

**Comment by anthonyfranc** [comment]
> > > > Duplicate of #9948
> > > 
> > > 
> > > that's not a duplicate of #9948. The bug in #9948 was something that worked in 1.0 (I used that command successfully) and it doesn't work in 1.1 apparently (I haven't tested 1.1 because Bun just doesn't work properly on my framework)
> > > But okay, keep both closed if you're already giving up in what you say in a video just a week ago or so. Well I don't see why we should bother using Bun at all.
> > 
> > 
> > Is there another issue that you're seeing? When I reproduced this issue, I ran into that error with Bun 1.1, which is why I marked it as a duplicate.
> 
> thank you for getting back on this.
> 
> You ran into the issue during installation, for the package manager part of bunx in 1.1 that apparently do not work.
> 
> The issue I linked was during bunx runtime not during install. Bun runtime did work for nuxt before but it didn’t work if Supabase module for Nuxt was intalled, that’s why there was a ticket over there previously.

Confirming this, I did a fresh install of nuxt once I added in supabase it fails.
