### ISSUE TITLE
`SyntaxError: Unexpected token ')'` after a comment line with `#bun`

### ISSUE THREAD

**Issue by solzard** [oven-sh/bun#9947]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Linux 6.6.16-linuxkit aarch64 unknown

### What steps can reproduce the bug?

1. Write a comment line including `#bun` (e.g. `// #bun` or `/** #bun */`)
2. Write a function definition specifying return type with ":" below the comment (e.g. `(): string`, `(): void`)
3. Run the code
4. Get `SyntaxError: Unexpected token ')'`. The same function code without the comment line works fine.

The below is a minimum code to reproduce the bug.
```typescript
// #bun
const _ = (): void => {
  return;
};
```

![Screenshot 2024-04-05 at 03 44 16](https://github.com/oven-sh/bun/assets/29563481/b891fc19-7f9c-46f6-8a24-435c23ed5892)

### What is the expected behavior?

No error is raised.

### What do you see instead?

Got `SyntaxError: Unexpected token ')'`.

### Additional information

I first found this behavior when putting a URL to the Bun documentation into JSDoc.
Even though I didn't change the logic, a function stopped working and raised `SyntaxError`.
After some experiments, I started to believe `#bun` was the cause of the error.

```typescript
/**
 * ...
 * @see https://bun.sh/docs/api/hashing#bun-cryptohasher
 */
const generateSha256 = (plainText: string): string => {
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(plainText);
  return hasher.digest("hex");
};
```

- `@see https://bun.sh/docs/api/hashing#bun-cryptohasher`: ❌ (`SyntaxError`)
- `https://bun.sh/docs/api/hashing#bun-cryptohasher`: ❌
- `@see https://bun.sh/docs/api/hashing`: 👍 (No error is raised)
- `#bun-cryptohasher`: ❌
- `bun-cryptohasher`: 👍
- `#bun-`: ❌
- **`#bun`: ❌ (Minimum case)**
- `foo#bun`: ❌
- `#bunfoo`: 👍
- `#foo`: 👍

**Comment by Jarred-Sumner** [comment]
The `// @bun` comment is a special comment used to tell Bun to skip running the transpiler. The error you're seeing is because the file is TypeScript, which must be transpiled.
