### ISSUE TITLE
[Windows] Exiting a running bun process with Ctrl + C messes up the cmd command history

### ISSUE THREAD

**Issue by moruzerinho6** [oven-sh/bun#9952]
### What version of Bun is running?

1.1.0

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

```JavaScript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

(async () => {
  console.log('Running...')
  await sleep(10000)
  console.log('Passed.')
})()
```

### What is the expected behavior?

While the process hasn't finished executed, if you force exit by pressing `Ctrl + C` and then press the **up arrow** to get the last command that was executed, a unrelated sequence of characters will be provided instead, such as `^[[A`

Video examples:

### What do you see instead?

After exiting a running process and pressing the up arrow, the last executed command should be provided, for those that don't use something like nodemon or watch mode this is extremely important to quickly run the last command again.

Video example:

https://github.com/oven-sh/bun/assets/58047457/0ca27626-06cf-4e3f-a17d-66d552f26ff5

### Additional information

If you continue to press the up arrow you'll constantly get the same string again and again.

![image](https://github.com/oven-sh/bun/assets/58047457/535c7533-8f94-452f-8c77-e7c33335aa22)

**Comment by moruzerinho6** [comment]
Still happens with v1.1.1

**Comment by moruzerinho6** [comment]
More context, this only happens when using Windows CMD, it works as expected when using Windows PowerShell.

**Comment by techroy23** [comment]
I'm running the latest version of bun and this still happen.
