### ISSUE TITLE
Bun fails to parse complex TypeScript generics when running tests

### ISSUE THREAD

**Issue by kossnocorp** [oven-sh/bun#9959]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

First, clone the project

```sh
git clone git@github.com:kossnocorp/superstate.git
# or
git clone https://github.com/kossnocorp/superstate.git
```

Then run the tests:

```sh
bun install
bun test ./src/tests.ts
```

### What is the expected behavior?

It should pass the tests just like Vitest.

Run:

```sh
npx vitest run
```

And see the output:

```
 RUN  v1.4.0 /home/koss/src/kossnocorp/superstate

 ↓ src/mermaid/tests.ts (0) [skipped]
 ✓ src/tests.ts (24)

 Test Files  1 passed | 1 skipped (2)
      Tests  24 passed (24)
   Start at  07:24:47
   Duration  382ms (transform 41ms, setup 0ms, collect 37ms, tests 13ms, environment 0ms, prepare 104ms)
```

### What do you see instead?

Instead I get this:

```
bun test v1.1.1 (ca1dbb4e)

src/tests.ts:
108 |       ): void;
            ^
error: Expected "?" but found ")"
    at /home/koss/src/kossnocorp/superstate/src/index.ts:108:7

108 |       ): void;
             ^
error: Unexpected :
    at /home/koss/src/kossnocorp/superstate/src/index.ts:108:8

108 |       ): void;
                   ^
error: Expected ")" but found ";"
    at /home/koss/src/kossnocorp/superstate/src/index.ts:108:14

 0 pass
 1 fail
Ran 1 tests across 1 files. [10.00ms]
```

### Additional information

The types are super complex and WIP, here's the code that I use to validate them working: https://github.com/kossnocorp/superstate/blob/main/src/tysts.ts

**Comment by dylan-conway** [comment]
Thanks for the bug report. Seems our parser is failing to transpile types like these:
```ts
interface Foo<> {} // we are expecting something between `<>`

// failing to parse probably from combination of `infer` and ternary
var bar: Bar extends string | infer Bar extends string ? Bar : never;
```

**Comment by kossnocorp** [comment]
You're welcome!

Tell me if I can help explain the types.

**Comment by dylan-conway** [comment]
We have a parser fix for the types, it will be included in the next release

<img width="620" alt="Screenshot 2024-04-04 at 6 53 56 PM" src="https://github.com/oven-sh/bun/assets/35280289/377947a8-59b5-4306-93ab-f262e499d242">

**Comment by kossnocorp** [comment]
@dylan-conway thank you a lot. It is inspiring to see an issue resolved that fast!
