### ISSUE TITLE
bun init didn’t handle uppercase letters

### ISSUE THREAD

**Issue by jatindotdev** [oven-sh/bun#996]
### Version

0.1.7

### Platform

Darwin jatins-macbook-pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

running `bun init` on a directory with uppercase letters like `classWork` in my case it produces weird package name.
<img width="1552" alt="Screenshot 2022-08-06 at 3 26 37 AM" src="https://user-images.githubusercontent.com/59236972/183216536-3fa523c1-d5a8-43c4-9fec-1f657de0d4d4.png">

### How often does it reproduce? Is there a required condition?

Every-time, when a directory having uppercase letters in their name

### What is the expected behavior?

by default it should convert the directory name to lowercase like npm does

`{
  "name": "classwork",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.1.0"
  }
}`

### What do you see instead?

{
  "name": "��w",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "^0.1.0"
  }
}

### Additional information

correct me if i am wrong

**Comment by Jarred-Sumner** [comment]
ah, the code that was supposed to do this had a bug and that's why it broke
