### ISSUE TITLE
Why basic operations slower than Node?

### ISSUE THREAD

**Issue by phibersoft** [oven-sh/bun#9960]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Write this to a file named 'main.js':

```js
function perf(fn) {
    let t1 = performance.now();
    fn();
    let t2 = performance.now();
    console.log(`Time elapsed: ${(t2 - t1) / 1000} seconds`);
}

function generateArray(length) {
    return Array.from({ length }, () => Math.floor(Math.random() * 1000));
}

function selectionSort(arr) {
    for(let i = 0; i < arr.length; i++) {
        let lowest = i;

        for(let j = i + 1; j < arr.length; j++) {
            if(arr[j] < arr[lowest]) {
                lowest = j;
            }
        }

        if(i !== lowest) {
            const temp = arr[i];
            arr[i] = arr[lowest];
            arr[lowest] = temp;
        }
    }

    return arr;
}

perf(() => {
    selectionSort(generateArray(100_000));
})
```

And run on both environment:

```shell
node main.js
Time elapsed: 2.4052746000000003 seconds

node main.js
Time elapsed: 2.420402 seconds

node main.js
Time elapsed: 2.4137412 seconds

bun main.js
Time elapsed: 5.3418615 seconds

bun main.js
Time elapsed: 5.3452694 seconds

bun main.js
Time elapsed: 5.3464818 seconds
```

### What is the expected behavior?

Elapsed time for bun is lower than ~2.4 secs.

### What do you see instead?

Elapsed time for bun is more than 5.3 secs.

### Additional information

I know you guys are too busy and this might be the least important thing, so if you give a pseudo way to investigate/solve this issue, i can try to help.

**Comment by e3dio** [comment]
Look at each part, this line Bun is 2x faster than Node:
```js
Array.from({ length }, () => Math.floor(Math.random() * 1000))
```
That leaves the remaining code, your extremely inefficient Sort algorithm. The real question is why are you using such a terrible method to sort an Array ? If you simply do:

```js
generateArray(100_000).sort((a, b) => a - b);
```
Now Bun is 25% faster than Node, and both are 100x faster than whatever you were trying to do. So in summary, Bun is faster and you are using a terrible Sort algorithm for some unknown reason

**Comment by phibersoft** [comment]
It's more interesting now. The `generateArray` part simply iterates over each element, calculates a value, and assigns it to that index.

And here are the results for this code:
```js
perf(() => {
    generateArray(100_000_000);
});

// bun: 0.653 seconds
// node: 4.510 seconds
```

That's really cute. But also, the `selectionSort` iterates over each element and sometimes swaps elements. So, the operations are very similar, but bun becomes very slow in this case.

So, what do you think? What makes bun perform poorly?

<em>Also PS: Yes i know using built-in Array.sort is better and selection sort is very inefficient comparing to other ones. I'm just testing and trying to figure out.</em>

**Comment by Jarred-Sumner** [comment]
If you have a specific application / script that does something slower in Bun than Node feel free to open an issue. This is not that, this is a microbenchmark.

**Comment by e3dio** [comment]
> The generateArray part simply iterates over each element, calculates a value, and assigns it to that index

No it doesn't "simply iterate" each element, it exponentially iterates over every element in the array, you have 2 for loops nested in each other creating  100,000 unnecessary loops for 1 sort.

> So, what do you think?

I think you are wasting time on things that not only don't matter, but is 100x worse than the correct way to sort an array, where Bun is faster than Node
