### ISSUE TITLE
bunx --bun vite stopped working

### ISSUE THREAD

**Issue by Garruxx** [oven-sh/bun#9966]
### What version of Bun is running?

1.1.1

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

ejecutar bunx --bun vite

### What is the expected behavior?

  VITE v5.2.8  ready in 1038 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/109706264/18bda550-901c-4463-83d2-fa97081933b0)
```sh
44331 |         sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath)
44332 |       );
44333 |     }
44334 |   };
44335 |   try {
44336 |     return fs$7.watch(path, options, handleEvent);
                   ^
EBUSY: EBUSY watching "C:/Users/sanch/dev/Web/react/xoukan"
 syscall: "watch"
   path: "C:/Users/sanch/dev/Web/react/xoukan"

      at new FSWatcher (node:fs:105:27)
      at watch2 (node:fs:284:199)
      at createFsWatchInstance (C:\Users\sanch\dev\Web\react\xoukan\node_modules\vite\dist\node\chunks\dep-whKeNLxG.js:44336:12)
      at setFsWatchListener (C:\Users\sanch\dev\Web\react\xoukan\node_modules\vite\dist\node\chunks\dep-whKeNLxG.js:44383:15)
      at _watchWithNodeFs (C:\Users\sanch\dev\Web\react\xoukan\node_modules\vite\dist\node\chunks\dep-whKeNLxG.js:44538:14)
      at C:\Users\sanch\dev\Web\react\xoukan\node_modules\vite\dist\node\chunks\dep-whKeNLxG.js:44774:14
error: script "dev" exited with code 1
```

### Additional information

This worked fine in bun 1.1.0

**Comment by Shenlok** [comment]
I'm also seeing this when trying to `bun run --bun dev` on a fresh NextJS (14.1.4) app scaffolded with `create-next-app` (using bun canary `1.1.1+ca1dbb4eb`)

**Comment by danielj247** [comment]
I get the same issue with `bunx --bun vite` - only on Windows machines.

MacOS is behaving as expected.

**Comment by Jarred-Sumner** [comment]
I have a fix, just cleaning up surrounding code to make the filesystem watcher a little bit faster

**Comment by Jarred-Sumner** [comment]
The fix is merged

In about an hour, feel free to run `bun upgrade --canary` and give the fix a try. It will be part of Bun v1.1.2
