### ISSUE TITLE
Why FFI Error ?

### ISSUE THREAD

**Issue by DaisenTravel** [oven-sh/bun#9968]
ERR_DLOPEN_FAILED: Failed to open library. This is usually caused by a missing library or an invalid library path.
How to do?
Thanks!
![FFI Error](https://github.com/oven-sh/bun/assets/25305480/923fddbd-1203-4abd-a024-957a70235f51)
[精伦外国永久居住SDK通用二次开发包V4.3.0.3_通用_20231009.zip](https://github.com/oven-sh/bun/files/14879385/SDK.V4.3.0.3_._20231009.zip)

**Comment by DaisenTravel** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DaisenTravel** [comment]
This is result
![FFI Error](https://github.com/oven-sh/bun/assets/25305480/9794b4b1-a07e-4bdd-bcd7-c93aa46b7ed8)

**Comment by paperclover** [comment]
it appears you are trying to load a `.dll` file outside of a windows environment (based off of `/root/buns/...` and `SSH: ` in the corner). this requires a `.so` (linux) or `.dylib` (macos)
