### ISSUE TITLE
Segmentation Fault after a script intended to be run with tsx is run with bun

### ISSUE THREAD

**Issue by touhidurrr** [oven-sh/bun#9969]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Run in CMD:
```
git clone https://github.com/jmerle/competitive-companion.git
cd competitive-companion
bun scripts/build/extension.ts chrome true false
```

### What is the expected behavior?

Script runs successfully. Output with tsx:
```
Created build-chrome\manifest.json
Created build-chrome\LICENSE
Created build-chrome\options.html
Created build-chrome\icons

  build-chrome\js\content.js     1.5mb
  build-chrome\js\background.js  7.7kb
  build-chrome\js\options.js     6.9kb

Done in 176ms
```

### What do you see instead?

Script runs successfully (?) but with segfault. Output with bun:
```
Created build-chrome\options.html
Created build-chrome\LICENSE
Created build-chrome\icons
Created build-chrome\manifest.json

  build-chrome\js\content.js     1.5mb
  build-chrome\js\background.js  7.7kb
  build-chrome\js\options.js     6.9kb

Done in 132ms
Segmentation fault at address 0x7fff71870e38
???:?:?: 0x7fffc386129b in ??? (ntdll.dll)
???:?:?: 0x7fffc3860ff6 in ??? (ntdll.dll)
???:?:?: 0x7fffc3860c9c in ??? (ntdll.dll)
???:?:?: 0x7fffc1727faa in ??? (KERNEL32.DLL)
???:?:?: 0x7fffc0f9bed7 in ??? (ucrtbase.dll)
???:?:?: 0x7fffc0f9c098 in ??? (ucrtbase.dll)
???:?:?: 0x7ff742671c58 in ??? (bun.exe)
???:?:?: 0x7ff7423e39ab in ??? (bun.exe)
???:?:?: 0x7ff7426fd376 in ??? (bun.exe)
???:?:?: 0x7ff744b761ca in ??? (bun.exe)
???:?:?: 0x7ff742671b52 in ??? (bun.exe)
???:?:?: 0x7ff74269c56a in ??? (bun.exe)
???:?:?: 0x7ff742689789 in ??? (bun.exe)
???:?:?: 0x7ff7423b1603 in ??? (bun.exe)
???:?:?: 0x7ff744f33ec3 in ??? (bun.exe)
???:?:?: 0x7fffc172257c in ??? (KERNEL32.DLL)
???:?:?: 0x7fffc386aa47 in ??? (ntdll.dll)
```

**Comment by dylan-conway** [comment]
It appears to be segfaulting on exit
<img width="442" alt="Screenshot 2024-04-04 at 9 39 35 PM" src="https://github.com/oven-sh/bun/assets/35280289/ec8ad2bb-a632-4345-a7c3-816d31da580e">

Likely this is the result from loading `node_modules/canvas/build/Release/canvas.node`. In the debugger loading this library pauses on an exception.
<img width="553" alt="Screenshot 2024-04-04 at 9 41 34 PM" src="https://github.com/oven-sh/bun/assets/35280289/eb408903-4a29-4e69-aae2-b24e444463f8">
<img width="1017" alt="Screenshot 2024-04-04 at 9 42 44 PM" src="https://github.com/oven-sh/bun/assets/35280289/05eaacba-f479-4830-94d0-571a00ccafb0">

**Comment by touhidurrr** [comment]
**Update:** As of `1.1.15-canary.1+3ff29955a`, the issue appears to be solved. Thanks everyone!
