### ISSUE TITLE
add support for "link:" in package.json

### ISSUE THREAD

**Issue by usrtax** [oven-sh/bun#997]
### What is the problem this feature will solve?

```
❯ cat package.json|rg link
    "@iuser/ui": "link:../ui",

❯ bun i
[0.05ms] ".env"
bun install v0.1.6
error: Unsupported dependency type symlink for "link:../ui"

```

### What is the feature you are proposing to solve the problem?

use like pnpm or yarn

see https://docs.npmjs.com/cli/v8/commands/npm-link/

**Comment by filiptronicek** [comment]
Possible duplicate of https://github.com/oven-sh/bun/issues/902?

**Comment by usrtax** [comment]
link is a npm command, this is support "link:" in package.json

**Comment by filiptronicek** [comment]
Thanks for clearing this up 🙏, thought they were related.
