### ISSUE TITLE
Windows: execute script on Windows mapped network drive fails

### ISSUE THREAD

**Issue by DeWonderMan** [oven-sh/bun#9973]
### What version of Bun is running?

v1.1.1

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Map a network drive
Place a script file on a folder
Run it with bun index.js

### What is the expected behavior?

That it runs like nodejs does

### What do you see instead?

If folder only contains one javascript file and no package.json

H:\RnDSoftwareEngineering\Public>bun index.js
error: Module not found "\server15\afdelingen\RnDSoftwareEngineering\Public\index.js"

H:\RnDSoftwareEngineering\Public>node index.js
RUNNING

Or if project including package.json file exists:

G:\TestFolder>bun index.js
**Internal error: directory mismatch for directory "G:\TestFolder\package.json", fd 548[handle]. You don't need to do anything, but this indicates a bug.**
error: Module not found "\Server15\MvWonderen$\TestFolder\index.js"

**Comment by dylan-conway** [comment]
Fixed in bun v1.1.28 with #13909
