### ISSUE TITLE
Package not working on bun

### ISSUE THREAD

**Issue by Mrgaton** [oven-sh/bun#9975]
### What version of Bun is running?

1.1.3

### What platform is your computer?

Windows but it happends on linux too i think

### What steps can reproduce the bug?

use the package https://www.npmjs.com/package/html2json

### Additional information

```js
103 |   var fillAttrs = makeMap("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected");
104 |
105 |   // Special Elements (can contain anything)
106 |   var special = makeMap("script,style");
107 |
108 |   var HTMLParser = this.HTMLParser = function (html, handler) {
                        ^
TypeError: undefined is not an object (evaluating 'this.HTMLParser = function(html, handler) {
    var index, chars, match, stack = [], last = html;
    stack.last = function() {
      return this[this.length - 1];
    };
    while (html) {
      chars = !0;
      if (!stack.last() || !special[stack.last()]) {
        if (html.indexOf("<!--") == 0) {
          index = html.indexOf("-->");
          if (index >= 0) {
            if (handler.comment)
              handler.comment(html.substring(4, index));
            html = html.substring(index + 3);
            chars = !1;
          }
        } else if (html.indexOf("</") == 0) {
          match = html.match(endTag);
          if (match) {
            html = html.substring(match[0].length);
            match[0].replace(endTag, parseEndTag);
            chars = !1;
          }
        } else if (html.indexOf("<") == 0) {
          match = html.match(startTag);
          if (match) {
            html = html.substring(match[0].length);
            match[0].replace(startTag, parseStartTag);
            chars = !1;
          }
        }
        if (chars) {
          index = html.indexOf("<");
          var text = index < 0 ? html : html.substring(0, index);
          html = index < 0 ? "" : html.substring(index);
          if (handler.chars)
            handler.chars(text);
        }
      } else {
        html = html.replace(new RegExp("([\\s\\S]*?)</" + stack.last() + "[^>]*>"), function(all, text) {
          text = text.replace(/<!--([\s\S]*?)-->|<!\[CDATA\[([\s\S]*?)]]>/g, "$1$2");
          if (handler.chars)
            handler.chars(text);
          return "";
        });
        parseEndTag("", stack.last());
      }
      if (html == last)
        throw "Parse Error: " + html;
      last = html;
    }
    parseEndTag();
    function parseStartTag(tag, tagName, rest, unary) {
      tagName = tagName.toLowerCase();
      if (block[tagName])
        while (stack.last() && inline[stack.last()])
          parseEndTag("", stack.last());
      if (closeSelf[tagName] && stack.last() == tagName)
        parseEndTag("", tagName);
      unary = empty[tagName] || !!unary;
      if (!unary)
        stack.push(tagName);
      if (handler.start) {
        var attrs = [];
        rest.replace(attr, function(match, name) {
          var value = arguments[2] ? arguments[2] : arguments[3] ? arguments[3] : arguments[4] ? arguments[4] : fillAttrs[name] ? name : "";
          attrs.push({
            name,
            value,
            escaped: value.replace(/(^|[^\\])"/g, "$1\\\"")
          });
        });
        if (handler.start)
          handler.start(tagName, attrs, unary);
      }
    }
    function parseEndTag(tag, tagName) {
      if (!tagName)
        var pos = 0;
      else
        for (var pos = stack.length - 1;pos >= 0; pos--)
          if (stack[pos] == tagName)
            break;
      if (pos >= 0) {
        for (var i = stack.length - 1;i >= pos; i--)
          if (handler.end)
            handler.end(stack[i]);
        stack.length = pos;
      }
    }
  }')
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\lib\Pure-JavaScript-HTML5-Parser\htmlparser.js:108:19
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\lib\Pure-JavaScript-HTML5-Parser\htmlparser.js:365:10
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\src\html2json.js:6:5
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\src\html2json.js:168:14
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\index.js:1:8
```

**Comment by Mrgaton** [comment]
i need this package to merge 2 HTMLS and this is the only package I found for it

**Comment by Electroid** [comment]
Can you share the snippet of code you're using?

**Comment by Mrgaton** [comment]
I'm using html merge I will show the exceptions I get on the console

**Comment by Mrgaton** [comment]
103 |   var fillAttrs = makeMap("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected");
104 |
105 |   // Special Elements (can contain anything)
106 |   var special = makeMap("script,style");
107 |
108 |   var HTMLParser = this.HTMLParser = function (html, handler) {
                        ^
TypeError: undefined is not an object (evaluating 'this.HTMLParser = function(html, handler) {
    var index, chars, match, stack = [], last = html;
    stack.last = function() {
      return this[this.length - 1];
    };
    while (html) {
      chars = !0;
      if (!stack.last() || !special[stack.last()]) {
        if (html.indexOf("");
          if (index >= 0) {
            if (handler.comment)
              handler.comment(html.substring(4, index));
            html = html.substring(index + 3);
            chars = !1;
          }
        } else if (html.indexOf("</") == 0) {
          match = html.match(endTag);
          if (match) {
            html = html.substring(match[0].length);
            match[0].replace(endTag, parseEndTag);
            chars = !1;
          }
        } else if (html.indexOf("<") == 0) {
          match = html.match(startTag);
          if (match) {
            html = html.substring(match[0].length);
            match[0].replace(startTag, parseStartTag);
            chars = !1;
          }
        }
        if (chars) {
          index = html.indexOf("<");
          var text = index < 0 ? html : html.substring(0, index);
          html = index < 0 ? "" : html.substring(index);
          if (handler.chars)
            handler.chars(text);
        }
      } else {
        html = html.replace(new RegExp("([\\s\\S]*?)</" + stack.last() + "[^>]*>"), function(all, text) {
          text = text.replace(/|<!\[CDATA\[([\s\S]*?)]]>/g, "$1$2");
          if (handler.chars)
            handler.chars(text);
          return "";
        });
        parseEndTag("", stack.last());
      }
      if (html == last)
        throw "Parse Error: " + html;
      last = html;
    }
    parseEndTag();
    function parseStartTag(tag, tagName, rest, unary) {
      tagName = tagName.toLowerCase();
      if (block[tagName])
        while (stack.last() && inline[stack.last()])
          parseEndTag("", stack.last());
      if (closeSelf[tagName] && stack.last() == tagName)
        parseEndTag("", tagName);
      unary = empty[tagName] || !!unary;
      if (!unary)
        stack.push(tagName);
      if (handler.start) {
        var attrs = [];
        rest.replace(attr, function(match, name) {
          var value = arguments[2] ? arguments[2] : arguments[3] ? arguments[3] : arguments[4] ? arguments[4] : fillAttrs[name] ? name : "";
          attrs.push({
            name,
            value,
            escaped: value.replace(/(^|[^\\])"/g, "$1\\\"")
          });
        });
        if (handler.start)
          handler.start(tagName, attrs, unary);
      }
    }
    function parseEndTag(tag, tagName) {
      if (!tagName)
        var pos = 0;
      else
        for (var pos = stack.length - 1;pos >= 0; pos--)
          if (stack[pos] == tagName)
            break;
      if (pos >= 0) {
        for (var i = stack.length - 1;i >= pos; i--)
          if (handler.end)
            handler.end(stack[i]);
        stack.length = pos;
      }
    }
  }')
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\lib\Pure-JavaScript-HTML5-Parser\htmlparser.js:108:19
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\lib\Pure-JavaScript-HTML5-Parser\htmlparser.js:365:10
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\src\html2json.js:6:5
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\src\html2json.js:168:14
      at C:\Users\mrgaton\Mega\Node\CoreServerSource\node_modules\html2json\index.js:1:8

**Comment by Mrgaton** [comment]
I just made my own library for that so that 10 year old protect I don't need it anymore
