### ISSUE TITLE
`TypeError: undefined is not an object (evaluating 'packageManagers[packageManager].install')` when trying to create svelte + shadcn-svelte project

### ISSUE THREAD

**Issue by jackra1n** [oven-sh/bun#9983]
### What version of Bun is running?

1.1.1

### What platform is your computer?

Linux 6.7.10-200.fc39.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```sh
bun create svelte@latest myApp
```
select Skeleton project, TypeScript, ESLint, Prettier
```sh
cd myApp
bun install
bun pm trust --all
bunx svelte-add@latest tailwindcss
```

### What is the expected behavior?

Installation succeeds without errors

### What do you see instead?

```sh
➕ Svelte Add (Version 2024.02.160.00)
The project directory you're giving to this command cannot be determined to be guaranteed fresh — maybe it is, maybe it isn't. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0

YOUR TYPESCRIPT VERSION: 5.4.4

Please only submit bug reports when using the officially supported version.

=============

PostCSS
 ✅ successfully set up and repaired (it looks like it was in a broken setup before this command was run)!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.

Tailwind CSS
 ✅ successfully set up!
Create or find an existing issue at https://github.com/svelte-add/svelte-add/issues if this is wrong.
152 | 		}
153 | 	}
154 | 
155 | 	if (install) await installDependencies({ packageManager, platform: environment.platform, projectDirectory });
156 | 	else {
157 | 		const [command, commandArgs] = packageManagers[packageManager].install;
                                       ^
TypeError: undefined is not an object (evaluating 'packageManagers[packageManager].install')
      at /tmp/bunx-1000-svelte-add@latest/node_modules/svelte-add/cli.js:157:34
```

### Additional information

i also tried to just ignore this and try to continue with the installation:
```sh
bun install
bunx shadcn-svelte@latest init

┌   shadcn-svelte  v0.10.1 
│
└  TypeError: "paths[0]" property must be of type string, got undefined
    at join (native)
    at Zs (/tmp/bunx-1000-shadcn-svelte@latest/node_modules/shadcn-svelte/dist/index.js:1088:20)
    at Ys (/tmp/bunx-1000-shadcn-svelte@latest/node_modules/shadcn-svelte/dist/index.js:1071:19)
    at <anonymous> (/tmp/bunx-1000-shadcn-svelte@latest/node_modules/shadcn-svelte/dist/index.js:1098:45)
    at processTicksAndRejections (:12:39)
```

**Comment by Electroid** [comment]
This is a bug in the `svelte-add` package. I've submitted a PR for them to review, you can encourage them to fix this with a thumbs up here: https://github.com/svelte-add/svelte-add/pull/333

**Comment by jackra1n** [comment]
Hi @Electroid thank you very much for your effort. `bunx svelte-add@latest tailwindcss` works now!
Unfortunatelly `bunx shadcn-svelte@latest init` still has the same problem as I wrote in the "Additional information"
Should I create a new Issue for that and close this one?

**Comment by Electroid** [comment]
> Hi @Electroid thank you very much for your effort. `bunx svelte-add@latest tailwindcss` works now! Unfortunatelly `bunx shadcn-svelte@latest init` still has the same problem as I wrote in the "Additional information" Should I create a new Issue for that and close this one?

I think it would be best to open an issue in their repository: [huntabyte/shadcn-svelte](https://github.com/huntabyte/shadcn-svelte/issues)

It is a similar category of issue with `svelte-add`.
