### ISSUE TITLE
windows: (bun: v1.1.1) bun create & bunx using npm to install dependencies on windows.

### ISSUE THREAD

**Issue by vgseven** [oven-sh/bun#9984]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 (Windows 11)

### What steps can reproduce the bug?

creating an next.js app using bun (1.1.1) on windows with `bun create next-app@latest` or `bunx create-next-app@latest` uses `npm` to install dependencies which consumes too much time for installations.

following screenshots shows the process while installing `next` using `bun`: 

![bun-npm](https://github.com/oven-sh/bun/assets/81641747/61d70d3f-3f25-41d9-bc17-150464afe551)
![bun-i](https://github.com/oven-sh/bun/assets/81641747/e035cbc6-78fc-420b-8a85-da1549676a52)

### What is the expected behavior?

I have tried `bun` last month when canary version of `bun` (1.0.35 - 36) rolling, the app created using `bun create next-app@latest` uses `bun` not `npm` to install dependencies and init next app due to un-function state of `bunx`.

bun (1.0.35) is fast enough to install and init next app using bun, but currently after `bundows` release to process of installing any app takes too much time and I think it's because of use of `npm` behind the scene.

bun needs to use bun again for all functions of bun...

### What do you see instead?

As shown in screenshot bun is using npm instead of bun for installation process which consumes too much time..

### Additional information

`bunx create-next-app@latest` uses `bun` to install next app which takes almost 94.44 sec.

![bun-i-linux](https://github.com/oven-sh/bun/assets/81641747/bffcba5d-cd02-4b6d-8dd4-81498ad48cc5)

**Comment by cosigyn** [comment]
You can force it with `--use-bun` while waiting for a fix

**Comment by Electroid** [comment]
It looks like `create-next-app` is using `process.env.npm_config_user_agent` to determine whether to use Bun or not:

https://github.com/vercel/next.js/blob/f9ad49fc6f57f3bcf4f508b59deab695f06c74b1/packages/create-next-app/helpers/get-pkg-manager.ts#L4

It's possible we're not setting this properly on Windows.

**Comment by vgseven** [comment]
`npm` is the default pkg manager if none of any (`yarn`, `pnpm`, `bun`) detected. `create-next-app` works with bun if flagged with --bun as @cosigyn mentioned above.

needs to be fixed, want to use it for prod application ([vgseven.com](https://vgseven.com)) on windows...

**Comment by vgseven** [comment]
bun uses node internally also and with installation still on windows.
![Screenshot 2024-05-01 073635](https://github.com/oven-sh/bun/assets/81641747/8b0fccde-a08e-4911-9e1a-22f78e9ac582)
![Screenshot 2024-05-01 073806](https://github.com/oven-sh/bun/assets/81641747/82efd59e-0d54-409d-b2af-7ccc946a51cf)

If it's flagged with `--bun` it install with bun.

And mainly bun doesn't support access or have added `bun` for installation with `create` I guess. I tried accessing `bun:sqlite` but vscode says there's nothing named `bun` in `node_modules`. When I add `@types/bun` as dev-dependencies then it starts supporting `bun`.

I think if we're using bun why node is still accessible in that project.

note: using bun - 1.1.6
