### ISSUE TITLE
Bun tests succeed when they should fail.

### ISSUE THREAD

**Issue by fivepoint-0** [oven-sh/bun#9990]
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. Create a Typescript type model in source code.
2. Incorrectly use the type in a `<any>.spec.ts` file in the tests.
3. Run 'bun test'

### What is the expected behavior?

The test should fail

### What do you see instead?

The test passes

### Additional information

You can test this behavior by seeing the results of 'bun test':

For example, I have `src/models/transaction.ts` defined with the following code:
```ts
type TransactionType = 'incoming' | 'outgoing'

type Transaction = {
  id: string
  automationId: string
  timestamp: string
  status: string
  success: boolean
  message: string
  type: TransactionType
}

export type { Transaction, TransactionType }
```

And I have a test defined in `tests/transaction.spec.ts` that runs a particular test, that misuses the `Transaction` type from above:
```ts
import { describe, it, expect } from "bun:test";
import type { Transaction, TransactionType } from '@/models/transaction';

describe('Transaction Model', () => {
  it('should create a valid transaction', () => {
    const transaction: Transaction = {
      automationId: '123',
      id: '456',
      timestamp: '2022-01-01T00:00:00Z',
      status: 'success',
      message: 'Transaction completed successfully',
      externalApiId: '789',
      externalApi: 'API Name',
      type: 'internal',
    };

    expect(transaction).toBeDefined();
    expect(transaction.automationId).toBe('123');
    expect(transaction.id).toBe('456');
    expect(transaction.timestamp).toBe('2022-01-01T00:00:00Z');
    expect(transaction.status).toBe('success');
    expect(transaction.message).toBe('Transaction completed successfully');
    expect(transaction.externalApiId).toBe('789');
    expect(transaction.externalApi).toBe('API Name');
    expect(transaction.type).toBe('internal');
  });

  it('should have valid transaction types', () => {
    const validTypes: TransactionType[] = ['internal', 'external'];

    expect(validTypes).toContain('internal');
    expect(validTypes).toContain('external');
  });
});
```

Both tests pass, but it is obvious they shouldn't. In the test file, on lines 12, 13, and 14, the model for `Transaction` has 2 properties that are completely non-existent on the type, and one property, `type`, has an invalid value for `TransactionType`. You can see this how I see it here:
![image](https://github.com/oven-sh/bun/assets/30638902/4b9976b0-e3ec-48de-aee8-58334172e2de)

I also created a test repository to replicate this behavior. The results can be seen in the Github Action https://github.com/fivepoint-0/automation-api/actions/runs/8572484428/job/23495136058#step:5:17 and the source code is available at  https://github.com/fivepoint-0/automation-api.

This is my first Github issue here, and I'm pretty sure this should be caught by the Bun engine or Typescript before finishing transpiling. Please let me know if you need any clarification or further information.

**Comment by fivepoint-0** [comment]
From https://github.com/fivepoint-0/automation-api/issues/1:

Temporary solution is to run `tsc` before `bun test` so that code can be checked by the transpiler.

**Comment by Jarred-Sumner** [comment]
Bun does not check TypeScript types. Please use tsc to check TypeScript types.
